sprite $image209 [243x224/16z] {
xDY5WSGm34JHu_ECfMp_rIupiq7pEtY9UTHGUTueK3O3cqKYkriszr3aMI9tbCWYYoooo2ABBBB88eiiiiWYYoooo2BR3S_U34MsF2yIsMTcyxR5DvBTpJmM
ULOdP0z85bbaaItGYYro-KGMMSkNo2ABBBABt4mYYoooLkoA4nb0C39cCGwPMCKWP6p526JinTx9ED97psISg5ioSRekoGFErXyP5xER45ux-GTNbAqVSiPr
CVT2nlNHEY0Fk2rQwsJS7j4o6NV6LibueDGY6G_M79buE3P5JdXAR8QSyRHI4-I4fzO06S-EbPFnYbWn6Q-gLZ9UMOrauiNLHiOROaralAbgo0blYrMG1xot
ycIylS9a5AaW6SKgH2QADUd63fVZjc4W0BUjSoIm8F7-RzkHSnvx0tOKgTPLmBP9Vd-p0CcJY1AvRCCS8bS5Ss14BZhI7CNBo5Fk4ZKYLntfYAulvYYi-aZ7
gFJw3SVCUiVqVkg3O_JQNyJrYnPE_PMUaYZ5TtYT-k2OVfz3InCKBTyPJ3TvKVGEO1tk4wyIsmtk9NFtELH4zIM_eczmQc7pOjhmowSRDawGhvoteSFqwcy6
uoPlIvtkKrNL9gx-77QNYrY7GNIQwXnwLSN7oN9ftgtcqtrSL_6M6pscrQPX-Z00Ub75MsxGCA7TRRYx3_tUc-amMLuLLJNtQR0vzFigfjm1pC7pcCIqxwgO
Smim1y-fLlskOujp3p17nuH-vqnpxWBcO40kg7YV34cSMF4-MJA7ZorEMR6DO-HPhE9zijIjU4sMSXLpoe45DWwHfVPCHxBKhvZ9MhPYJYKmnZX0dbA-OYQh
rA-OoLA_OYPB_Oev8iLlffZoDrCCeFKhvfXsrU8LSzpqqIGj6iV1lf4VZqRcqXN_96z9EDsAK-0dUOkerg-OoTjAbw-OoRJI1MycZsHQwQeppUGyAmqx3MOo
hNJHYfdCqrroYvaSqLKhPZ9FjzQwcI8vebLBLipaEDtrAcPoZAYMEBRsoRpIbMOwajShNQhYI5wlT8cAzycyqhagXfyayqfNgNXDRcsrqfbl9ev9yAd9SgLB
LBmcYw6jfxj0nMjoW_KRN5Yue68YSw5jvyBADzDCtWsZKrLydimhdQdYysHUwKplonZ4lUtolqwtNW2c0Feh6XRD4PtgPk9CG3kXrT0Eh7IEBUROXgPx6Ut4
IYS1hwUxjGCNLfvZQutcTDcnYsgsYXaTW6hwORFsyzyMLZfTnPpE8Z5hJxpRyp3N5bOwMyKSwMtv-wBDyPCCc5omqdWjc2EDE7oYRMGOUhomSbOSfpi6C60n
tQ8tUtoSd-v8zhb4TzK4nzOPDE3k0riMAvrkfkDAhybFj25Ej-QiEAvq9FiqmFf_VOFgdS0ytP7iFebCqvsjOaR_Ezd7HkxI8ZfRnHmMHRBG9KqhVTERQJ_e
ZSasYTmxqE9AfpcezrSQ08ZS_luXfelfJbfnFBkxWidwU7jp7xAOxYJ7rlvATzXNCimUxkwsMkbaCytHtZujqztd1tduUmo_ETt888vek0-0oF93e8-8ljlD
T7ww3M2o_ltsmEvtK5YMXcFHZmucEtwywVexQBOjvjZNbGQHtJkrJDDzycQQVeT8fq-_0lEFWCYCJbdn-Wqgm70cjxPQQIG5nvKM0p2-aaMajs16ceDw_ptM
O83DJx92HNeWvwru_Hm3x0iP6xe5SiAAELF2T3_9DiSx-ZpPxvhvPRhL03p9xZu10vEpLnpFiGxx94yVWPo_uhZIybJgT4mFv0hWU7QBlPFDtIEvZfZHxsIC
isHF4tvwA633Jf3DyuJVe88jnycUA_opyWpPF5-4VbO2faV8dZFQFj4A4oQN0yUFl_t1v9fYHWToAJ2VOyV8NY3Q3f2zI7hxNRANIG_eXihWkD9hifUBD2QN
5_CNxqZsee4q8jSNkq6bBSXUEO3szYlPQmSRciXUF_e-tGtrnJpTqX70vT48uF9ct4dy3m
}

