sprite $image326 [591x429/16z] {
xDAd0G90000nY_lzfwKe7FN4bsI6ZBUuF8m6DeMVa2aBXKnPA6IgGc5J-0cPib38b8L2fYeKDeMVa2aBXKnLA6mAFo5J6GgP-b38r8V2fluJClMXaAaFXKrz
A6JgFo5J7mgPXB9fmb38v9DCquL29g5icl4JCWabqtoXi4aecIRyX4n2oJHVA6mIIgQvFo6JK3RD7mgPV99f_b3899HDyuT29fzacZyKDWabar0o7V09cOIo
IIYP3WY5J3x999HDUuL29fza4ieceP19A9byacd9KDWab4n2oUGJDWabar0o2OLCpq_O99HCD_Rj0xUH68R2iDXz_nDl56pGXEeHvqrv_m5IFv0kT6Mc_sGw
ax6clvcxHsOIr18nPORxrFDDgZffrTiz4LFcL3HsDLrblGuKDTLq9ACdKOzy1oXYoZ0TIm1KDmT5JEacuzpKF1_dYPeoJ0OgjQYdW2AcT1turFCoe5W39Gmf
F2ZMG0b7gkxcYPegJCPL4ulxW2AcSXrNJwDk08gOqcNS8_6wj2TgoeOLXn251qLCrJ2N4ABme8YfGiPTawWhWIAcq77lB5ezCS2IGo-zBb0CC9ZmQNI0OhZ1
X1zHA53KL3QUboN24p6bZcUcfuCYff1nOXBXVvd-rFtjSA28gJ_zhDMXpx_qWs8Dc3euhR32LHiUbGCy4HEAqwhARIig1mmeOW9pMb6fm5OU7VrsxhCvqQsS
rYfSDu7gyaHDfNjE8UkJ3PoQZeirMq0Ha-sXD6lWr4TAQpiexZaV1_jFgO5J-tsexmL5JIa7nr9-PWXEimgzyKCexhdr5Hmafrc5NMFZySM13PRWd6PXw5UX
YAdqm8wRbXeuGRQU90uKHzDwwe7dD2iNs83YQ6euvuTocgL11XHlcZOCfWPEm17bNryQK9Crl4pJpAdzoFqVU_U2DQ6A0m4OGaZYlVFO_sx7UJlliTgk87zg
1HxwaqAKq-8GgCBa7TwY8NBYTzwyxwamnKGFWxo44xwXDg90tSGK0tnTokV41oLUe6vfSi4nyJdnGLbvkZ4rMOVMJ3HE-Q1-_0bF-DV6XtTzJlXdWIE0_4HC
CP6jWPTomkTZSGAe3JJfzmTs4ZZTZTokzv_gAUvaW8icJ2pEAV_Fghe5aX-02TSqFDx7oHywyMa1vSTeya6uGRCukPdgUFI0fmMM7u4fl8DJ4vyJ7r5v0fQZ
mDH4u4H0HFOKssEA0JpGhSK9HyJt5AK9-FA7m0bxFClt51jZYe4K7PyJ7r5v-lPFB1vKJbH4m7ucdaqrJU255O-Jin3nFSM6cCAWzxqufxqYiQsdGEAufk9q
PiIUe09B1rQUnUd1MsmhJGFGL9oU7PPjCCMaQjgJK_VDF0KQHpGLf-TVKs-XAUG1JSMfQUm3Al3e8vgAK_FO15G47dj8Kt6IsC8Jwnlf6SK9gBkNWMBziYD-
8YUHqS6wm_DMJE78LBu_fowYEktFF8m_HhcOy0nWNsLVJdz6PFY-dCLJoS54cvmijkKaCbJD_87hxH6l1SKygwX1uCJlCpDVU9nUXYaiwQ2RPY-Ax6kpkB_I
4_aWjHCuKVeCpSoPnkDDcYnfZ4AvVVRcEoyuc9X3r8F0YT9dU9npw_51yKV8w9pmFejBSguv7Wy54stFQSIwd3gmA0BJ2U-YsA0ofcydS0BxZ1aZB0sueEB9
pBJ9APJQP-obfiKhG2LDtfxFIO0-ovkUHj0zvMjoU73ud3IMY10MuoHGQJ-f5QUxqzECnK7bFQX85AUxOpQ2woaVK_ZzEwquJQ3jbWELEpB5YN0Fya3bBYj7
SRfc0AEs4gZuLf3xh3XDO2Tp8K_f3obHd92xq6D1KFctcHGdQ8rWGGY0ANiHO5_9U2sd2LrmFYZcNSRFQpavCgldUoAi0OeJaWwinRD1hN6J5ITyMWzUqZ55
M77wxbE41J4WfkAKdxaWfqZM55gSmDYQLmnXAaxvMVMA7yHKd8fJv6cAKPpGT6JZYGygc97YX4O0JhGGCV4v5IT-7iHKd8fJ43NnEHKdVexYL9mUm_JBSR11
wQQSYjCll_vwdDcAK-qxZJHC9wS_fJZLDkPdEKvBV-B41ZMB4nW7hfWsDLquKK5PSVhkoCqqJ2SdkYTlXDJtJjIUkt2YWofEtttRwNHCLqvqKBBr7pVd3no_
vwwS052KcqpNE1XbRtkm4pgcAoU-9qtTFb4k9_vAVF1xxig93igWm_R5QQpLpiTbQhfmueE2ViZYr84BflJSbHFWYRIa7CK9sM1XzTmDJcVo5q-zE04NBXnC
DpcTITyNj-9ql-kKqNC0fpF98pEAq_rxq0cOG4v7yc4MBqvtnwmJUWxbT2RrJjFYT7SXheJD0PpJcSIswmjm6cguAFvbEwNdS4vdyWPd9dAwfWkaYZyvTHec
dDEnq-Xe-o0oT9elF3bDsg89vtGcwwi2NVBROX5LG1Nl___uKzEL4n-K0UD3u4IkGFwVa-AO04v4K1qO808dl08tc9oGdiCv7Ia748pF2Q_0QPxvmQ7mCU6S
pYHCJps74vukgcPPjnw_vt1EP_XZfDcSy8NLD6hLIHOcdDD1dvwQfNBAhq011ehRSpYdC-o7k-u4JfGAzAzUi13Ug02SMA2aPJpTZGQ4kBU0dtBrr9x3EPtX
7WUU6npB0hVNlLDlkclF4JaTt8d2NiO9trx7BzS9c01EF53UWR5YSk9N87x7JKBF0PoOe6P3bkDyJjIz1Mo0X809uCG59RWdFYV-ti9ixEdxsdDyJWUlxWQP
KtxwZKjLmkO0m8aDoXhRaxGD8uIU0pZnGUa3degJ4teEuSG79HzxAawJW0dYnFVaxKDFnMaGUWxYXEU1vHFsV5USX809viG7DJ_nL9ow4tgEp-dWl9KrCgTf
KyVA1esoEO1pueCIuhfJm5_hJwhwXfe0J00d9YZlxKQKpUaQixLKJI8cd1CUWYVn54xNkAcke4e9YoOo9xwdPgcShggcYhIq3ERKX7FYWpBWhapdT5Kr94qJ
ZedA2S_tFNLVXDCrP5M3tNCu9pueWvSD-PnIbkk3W0ddbE-fjriHPtA2LAbqWYQav-YS-A2y4oOe7gVhGw0GD46O-9pmVDrJjwKu4Hy2bTLpEATyK3vktwI-
0YVwSdrcl579vtHy_rIbUZudzdBT23r7u4G0DTlTz9dF2LSrskrq8_GSWHC5b27Z-rPEZcXo0YO29v8d1pf0ZCCf7rCRSCynE742Z380Yiw9ZwbD0YO29oge
sO3qoUR4nzIDq7C4JcHGrZ5G_X9EDXeISSBc084JtPEF1cNu2pXDOUus0PW8dDYWPiCYSsrEhhr1wKR0nEB41-NIi7JrPJbDQM2Ki6XYSkA3qeP6vegSVFJM
zfkQS4xy2GhEc6jnyjaR72LWudFYWveDJn-s2YUVql1q0tkEpoadm2CUA6fcShfQmgCiJ7nEV4zXqZwAJ4_aPDhRHnbEw3a-f_p6mzFLCZZv7FtJApSs9Zud
VkDf-pYYnkHqdPRmJ7xFyJdbBw5mKWnEFbNQ0r6dlL7XSyfVGl62Sp852ewpQE9pAb0u9mSa0MzxaPxZSofGE2T__4IT68QfEE6WyZdPTyxG2Vv6fJYT2HmK
dvEPgQfyxO3lO67YSofGegf3_XH04BG0HtkkEE4Vr-qPVU1po-84WDBUTakV7e_rN74wW2_HzeaOV7okE06WTkwyhWvZAau0g9sdA9a1dyKiJe2dZLTHNVrh
c8hJ6UJK6YVyJIQyvueJ3YhcUAEbIVZhY-84WAA9ubl2UuwVtw_h2HBLsnlInmm29hwcCrk12kEAmhyqndEiYmdmn0ldv0WU_1p4ZZrtPbDG4QO4KiZNwljZ
sg3nK59yIZltt0OJ54wAJsb_JFk3Yl0v9EyHxa9fwvxR7zGrnZObGm5914m4JIzRGk6c6F-HsKM1EMc3djjxWkB_xPmC31B-HYKVKu5w_1YA08wsMZHjs7Wu
gwawHFfzHA8w3M2qRSyLg6lSpgYU6VBlCbJF_84zEpP280Q286W1SFa731u9h356JmhVfLNfdx_-RzimMRnrTWweGJ1Pl6LspW6rp-C0K8Fi750m3JHDGF7a
qkI06cNdWDe4qpAUx1nG7WU2c2oUdGCAfg0cY-VI15GlEsVnO08gcPspU30veABPEQ1W0ggRdNE5yaV50TKF9g3idCKB11DGTYxW2IYOWB9pfNZoEB09A3jd
yM3QQmBAfIaSJtRE0GLJBg3i750mzUF9pZcWKfXe0ihEMJn_LFe11PF5itE1W8B9ujcvQ0uec82oSzc0yZW0b9tZQPgTcmOKJCk0idFJW8A9fsbsRXfG7WUM
0MNdfW4rnKIJnNDfcWQKdLi654myJRDpqu22QHfGTcuPK33nDCtEJGFA7vLbGDcvQK3PEPwcmJGDA3kt32YObW55qp2U3YQWafnW0kfeuYd92IQW3YQWafnW
0kfeuYd92IQW3YQWafne0kfWuYd92IQW3YQWafne0kfWuYd92IQW3YQWafneukbW0Yh92IQWZYQWafnWukbW0Yh92IQWZYQWafnWukbW0Yh9YIQW3YQUafnW
0kfW0Yh9YIQW3YQUafnW0kfW0Yh9YIQWOEAfoGace6W2gia99g1Wugd92IQWQ5AJa-_oRPSE2W00OG08zMzj17Mx9sJ0fp0JGeMR42hCX51X9dmACo5Kk0cX
mam85MR2ft0JGeMP42hCX51X9dmADo5Kc0cXmapu56P2g70JGeMP42hCX4_X9eGACo5Kc0cXmapu56v2g30JGeMP42hSX4zX9eGACo5Kc0cVmaq85MP2g30J
GeMPy2dSX51X9eGACo5Kk0cVmam85MP2g30JFZrjuW
}

