sprite $image212 [299x191/16z] {
xDP5eYCn38JXGBia2-BxdpRCwCmyxlfMNlycjMytpEVpeL5VgMBjDL8C6jbUerezSwofc8gfc8gfc8gft5_CLeHTAjzeZn5AAUePll4u5W5bcC_XuIVj4OOQ
QeIVqtQ5W4qeYSouYjNE4G310CzDgQjMqOweO4rhZSnqhHUnuZHa4NQqMcPKG6Dd6ohoEXLBGQg5oNPbXrQHUKX5EADoN7bivI4LuH6flayLcOqA7ZdSmemg
gfCsSWDUK0yJR2ruzruG735KFs6eDxJHcQ0BMmdwC1R-Ks6eVXmvJnXBqOMtS84-dBBmuIPyfFhnHBrXfBCvO-6JCLG_uMl-1avI_NZtrWHz6ChSv6y_MOAF
8DKtgg1B6UzhhgjspdMxSLk7mcTL9ExAlF_Rdaf674Y2QOeJhzfnzh-gkNw33G8G6FqKGPy-tj9xJiebJLY8yAdthAJ8J5rj5v8e7s2PwiTRW79KflTXeRX7
D_dzwNVO2dmpAhCxBaHE_kyV_PIz0QYm31DX8Mp5UfL9zbJbBTez5Dl1CjudgK-PpG8kr8r-BgWyi1m7xv9KM8AS1P05LrIc6_rqK4IhbnoMumYeC89Q9Ep9
7zKiWVMIIGg92EzsD2eONJZFMrHaNzvRPDVqZkfqW-WrcnWaPbw3fjRQwcYK0wmL1nvhYG3AnPiSvx9Nz1xoAb6ggvfrEbrJrZmR7si91sNHZPmSdcQgBzRk
UKnTDjITLSrgIfUxaDLC46wWsY2vk9GZh6lkUh5ilfAIzLVKwjenq8tu4egK7uyHbBkH7RYjSb2k5tgnxa7blgarWRKxwqqp3mjww9Ym1L0XzwDOahFaLKBA
CvNEgxG6nG-9jqQCO2-l2jRG8I2ppKb8XxBCDEfbAgaGL3FNZRPrkkSOmPj9dqBIkeBY7TI4bJrjWU1rL8WgcLSPrgssYMWXfPY6b4jmdzy5xpP7QlQqe3mz
hR1gnTn_hbr041p55ZlaJTsrnXdYmV6swZ-u28PZTPIgm4A3Fb4Pr4IHyAtoz5e2ICX9ix4NhvH5LYnOro7D4oOf_AeEf2v2KhTVhgw9WoVyW4_mciU4ahhY
K8R9qxsAyOep5WTaJYfNvyI13-DracomvIoJWbMUhUHCwYXWggv1M1nWf7CgJbteeBxpA6Jc1gdHEifgjs10iNOrIqDnLhBG0tq7AbDXbkzOay9GHqbzC2kn
aF6FOcK0yu_vhek-ysooZImOKwoZPgndD3WsNIaqNhBQedZHL_yMrGKMBLwiqp0eg42EokkeHyFYaF5JxIxw_dMlux-RC3F3D1KOqwKsO0t5-SDX8GksMJgg
9LTzGu9tnvWoCvO2fOwHMWGabpQs3WY-Mruup2P8h5_w-4jKxa8e8t5LhqATJR6wdW2McEBkJORHEAe82mkKli12t89oeODw6bYx8QBDDfgovY3J5TRKyqEp
DnKrqRF0ojvac4CRHnLJ5jHfgj2IDnQ2zTlrE5IBabvd59Mdh5fgAsUXg8lXDM3XWPJQ0AeKreAgDfSHNRM-12pIW6gmrvbDI6m-f2ouTHYI1fd1Ix3oAciU
wtMysnFwLvm45jVbCCoJbCjyQlSQi52CDVGwfoSjI8iqTI5CKwrfal8OTbGl0mj7_wXHhLTMCX-q5WxLqtlclNmMZ5Jl2aNmSR2wUvqJyXy7SrHUE9HQhoMf
x47D-yeSv7u9uI_tO9mLVakl0qEeFA-dBiIl7bhCjjixb45G5RW7wczWeQyP3u94CQMprohyXq4Ee19OM64grL6PVNcFwrRkpoO6qY0QS25oUxkT76GVovEe
A2KL2mUVE5IEMN4VEYYQO6XyJ6-vdv_0WesQZxxx9bYf_wf1AevdwbHg3QjYYeclKWpvnmow4FLBS5JSr-uLTeTLuhwyVAzbAjLNnOmINwKOyeyPSs5y_s2p
GhFc4uHUzRAQ4-MmobHh0JQpn7kvkEDZEavCg3KaPSkNGGxVWA5R_KqW9oRCggnBIRhtZDSGxPZnZnc0HPVut7PpYacIEeY-7nPDYG-Jb4MmJ1nAtOgrZI49
glwKXN957Z9IijUNIlfXKHyhADC4CYTA9mvxLj25eGrBKbOW6-JDwLakHkXLEOAPIePgAgXzBbpI-qxOuy5ATpwcUMAQDahIblXqVXSValwpK87TWA5EYmhr
k92XG3cua7gi1Np6VhiXXjmgtpNHe0iXtfh3iY99mcfHpLoOJnmEBkIUX8tIczHtGmoZvHadBaGrpJHME5IzYgakHijGBQfpRvKrJVTTADI85PTqUC-CrsUU
qz9NycqDtGrcIIQ0K3DKxLwdrbBQi1WQ5DhUqwtt83pZ0opaDYmpWrv9XYeFgpbJtkiiwRqCTCmLfE_SSr2Akty5glMOsQr1weG1nUmUgdfXLTQIjDU5C4r9
okeemL5Q7qDsy9wqpqAluXEbkp9jLDP6LU4phfnLPwzJ87SXrJkYniU0sXMKmDwo5tYrBsNPR1nv2dQWCijHkG2W5cVL2Kl59mvxKT-uu9Z4GWLcxhr3uZ9T
4vVG4LP8MG7rhlTXxBhjcg9orIkhVpfXUQzJav9qH1Gj2Mms6nsAXl1CiEb2HvsSRNnt7z2Le1eFBEzrQlrhM2YxH8_2ZQ8XFGizAF8xEznTav8cg9BrQy_k
6Qpsn65GxPCJDSWJL_HZxi8aIH6ozTUal03dMYb1bGQMm-hiTNpYC2AWofOMfMGRDnsw7SdEGhP5ilMU4AjrTuR8ifpkt7fTM1TOqoSiwtOXWqySJihz91oo
J4nPOXOwcwpRoGi7fSFSGKZCUeTPfKm5xN8_3F_S3Qp_dKjPFd4Oj9wmMbR4-xskMI19NEkpB6LXMdypgTrlenq0h7CMmTRS3w-moWaN-iBVMHV6NsG7AnGE
iwc0Gqtyw8L3BZHr7Rw78UGYV-NWaIVjLOOo3QGiB6SFm-qlidL8mEc5Jb8qjET-98owiJR95POPGIvc_RgRIURfgk72WPH5KCyTXX3eUCewh2EnsiBAygB1
bGKMIXAjdhAQ3G-ppNukeCxAq6PrTU6vbEKJXtxjyWUhRL9sk9LibamQN9OC_lWAXxyuUyfQQ6FZ03H5Fo2CacoLd8KZLHRvnA5RknmbQfUKxI2ZmgGXILpW
i68wpmy_Li6klMIJ2xe4K9Ao7DO78P3rzJe-SHXq8ObTN_DuE5tLA1fGjcUXtCpd9e2TryCmoLRjm78LwkrrVEBGAuo_25MFA54BxdCftIWQhkTcsX0wB2SB
TnIzXvhMeNb-Bmwg07MxiBeBpwOicnL2HBaskEJOxLJAylik3Jhwla4Vcx4JwoFbaLLByIiI9tgTaoKfi5d8vlvhvOf50-xzo25ZPOSVTNdFXnASW6h3SjNU
_EvhjxMUJLdiCNOzyp9GPeqHgP-5-IGPQGSAxtllO-32zr8rdEjrpauS46f4jSlfkWkiP4GQLq-I-wXsV2jDTxndVuPrijUvEt4WeUnfSlBj0YsRDFWpLqnP
MStf0txgyDwWpevdMeSX-3WpGPMoYe_p4Ub6s-t-7IZEXbSeiwRdthYituMOf_VTE7Chlcl06vE6e9qB6Hil_ABtC3ltndMoru6SbiHZAqULky_pEH-AXaIt
ydSoOa0rQNblNDQVilA9Gwmx8K6LAgAoGvBATFVF3yo6qNlKyDxZKrO-SK09PrC3LLOrSAXR_JzFil9qxurpj_SUxqAgjKubhT7jQ1vEtHVbR5WzSRK5kVXQ
l5FqdWsn68TbrZDn05OpDyzf0thTcdYltuLAFenlUE_Hi4pqK3Xa4mSGgdK8bGl--Y9OstkFXsMcOkaLmmEjSLIvW1dEfApskVTuLZR_cUK0Y_mbs2DHqUtb
qeCwlFTuMEiup2nVktqWAf3MrbBBUvxE7wyKrOVTkcBOfWKyZ0fDNT9sOUFSUxHqdzO_75LwnR1ZrDTIJ4P4jwRF6K_ypxmNTGohsMxsEjCq7bZHN2XkjcJw
R7W0fJ8oQtcy2urjJdIzOdW7bbegWGWqQxYlTJZkyzYiEEAznyCojJcJgKyS80ac3DazWILKqwKYEeJadFG0FEwz_xRNEHw65D9nvaB5m0EtkqQuEmXnxpsF
8y0lxyqUKayDotkTZGjH3dP2ZQ0eKWthCnci7kzvI3qrhDZhPBVbA0kiZVMaiMlaUbhlHNqq26KJX-Fy2YELIqGbsTnVtD-zNMw9zmAe9mqiaKDZw1E7UCeR
xZ8OroZCrsVomXF46jvxObXYFZyDXSEroEAmhzvQSeTiVSOXmmjuhm-MhZVkqhNRiAz-SjU8ESn3NyPxKNO3rOTQydOLYk-hG-UB-_t6duVZ2vnxcIn5zKVj
sEkSNhl5mwwHuS5xT5m0Yg2UseKgiwCACfLyuj3lGkEAX_Uk_0BUQnGEfke6FAxTJesrMs0yFWjBKtZxtBEdzbwKxh68MFSLGvVVniqt_dmgywBUQxlGpaqS
uctSD6N9AtjllDUXPE8WxPlZTBlVizQivVLX7ISEcauGSa7qtlmYtXlVdgdJreNKQeeJxsMBho-aaIk6-N9x-zhpgtflVE4FVEAGlLumkUazJRmNGVr45_h4
8LcSiLdnXtflF6NjYonItzVEX0VlPKi8FpTb-Ov3hCuPxdhF1XPVNxzmmDtu7U0jl1TrwgBlTF-AZc3xmiUxk30SXeb0hjuZdGSQun_MwrHkrPpGyDwxmG8H
nZFU-_FJv1b9ZdmE2tyiyfRUYx0KIk46AazPel26tejQhsLcg4ptlGw-g_TS2wbAagGeExog87XBxqLKm3OtbC1AlKVklP-gMgQfJ5Ftn87Uqdlnxo6M_i81
tyvxhl3dP_fW6JUM47uygrfoLhditRoN_zcwkKDAZIM4zmciVpfWCK1oqV5TLC-ua9EbytSIBB3wqZk_c_To5xPW6REjgDxJUr4IO5bIgjE_Mfxh6telTw4V
XbjEX4YBU8MszTulh2au3nQHXvNSzDvlPFbVMK97nPdtVc7nzRR89Qnq8NVrtgyemYfbgf-ePCts6hptAt1O5nLdfRChyTwl3GChe1kWVeKNMEMJ5Tdi-cLp
K85LTL4f1Qs1wbSGnNTG_QgUHVMh_vqmuAzEeFhLVzNG_1y
}

