sprite $image390 [266x272/16z] {
xTm9SkGs38NXMbi4e2hV_xRn1cQXhT5BmFdR3DyDvYlXWMJ7UNcw7AzvUTavthCf7e_ZCzkXPplqR8YUxT2p7NesHCzswDaEFTkXPqDajaFFTkXP7UAud_r1
z6o7dktGio4osw5dE_Gikpdrx0-YPpjajaFFXkZP3ZtR8RCTUZP4ptR8R8UU3T6p7JBReMSxP3P4po8EZQNW7JBj_o5nmo4bK0f-CDgQ4hf3Ii0KV46a14_1
Vn2y1EzGBd7ysC6ebzWEcPy6KU-GsGuzp-JG38GudWZYqS8KXqKflBrJkE2mA4N45KKR81QMkA8O75QcCFEa41pMax2tT0h08IbuXu42WJXmXu42SE0fp0OA
2nCSIiCxP2AEf10S2eCxZ1GCn853N5CSlp6amqZn6Wy370W9-pOU_a61G2G5xs1ndkyKBJmT00eUmi-tT8g3o7CCnlcUfB03oLCCHkODuT6YOHByO6G-3fiq
1UzmkhyVApmG2RuWCj5QSt-ynXsXW0iYytccYZUA8moZu0UZVSJ27W-eDPlnW-6jny3MD3DuCDfVut5WLM6l0GV3sj_ZN5KqUmjM44F0gh3tG9ipCrR5WL4O
i3c7m5NHx3FSO6JeKuNr49jpJ3ImAZ90GOmnSZuAB4pOd9VXLsa6AeXnbNBx8qCLn3WVE8NDtvpFFn-P-KVhw_Jp5KzXm60Cyn7saoZytcH4qnAUXmgeAdIB
2B_nKLWJOz6oD1aAtI8kACnpCFHuP6ao5Bf5nAL5f8ESCAmqZoPJfCJLY0Y38PGcGM4t92uj1WgjD0-8GhQ8WKAmA3nfyXGHqonytAGyXTsGg1-HtAHCxBlS
aWWljCXDsY2Afbk4DYBgzSEFdqBHR9Q5nV6K7uN7rn2jtRVuwSUhl4LyEHp-CTF2Po5_50OxZ3VBRsh2scjCjz0VydW8FyyBYRJGwq8_S_CErnBXceLyl7gM
WlYrH5JL1VzHN1N47GczBjIFWX-Ccn9wNKYlLuOFXY3ntOW85kn5hDt_jU92eg0kw8jOatwjk9QOir7TXuiOwE2VCtiXKL0Nt4VHjD_vupnlIEXrmT_EjPyp
_JnlIkXr8TpEyOAmynGaYkiYBsBeO6H1d9g4RY5Sn9Y2oC5G9Ef79C_SG44CWo59r1_0ytZ5RivJbgYl2yjDYXL4YpCZIvJUr-kFL_PTBWf2bgYlYzoaWMtE
0ecY4SdIP3PdWKJTHeqiJM1p5aWK7i2pD87DMI1HMHTPcWPipWA9ohh8asO32aAIgBSe_oygchmvQoJgwoBd0zYS1HAbTP7p0HI4B55V5y9yb3vAbKdK7y3r
-T2FrdqmgYNgHqIV3tqmphDUelw-Rdd_03PdWKHbNNXMnToZTRr4VLs4L1McRav0GgyBeIeADcUvHFs8P5Mq-aSfJ4At-6jLHFNFEQo4VW3FKyKZlFHe3KWK
r4LOjcRbvkGbzBgmpzQqsit9I-XrOVbt-BMFKho4FY8UHowGgit9IsHSEe37vm9fjPkJbz179FoH58MFKho4VW3tJmglt9oyX5uNIN64rnO4Bw7VrpqiAIes
9o-XryL8eJzASH9wNVXWyJs5-YX5IjJNHL8SvkBHcfMe7v6aADYSHHAiXK_VdBn4k0dtTMbpyXBr1t3zvnnUedv4v4SfG0Am43OdAr6_KSNDYKYG1t1jSzPB
u2EYRqvUelw-hczENgA-BeH7AK22g0jzS_8IzNLHK12GHFq1_69p0X9WNSY3mKlKZyWeqHq02TxYOZ002N94-c183hn4_NrzA0XE0XwHOND24hp5K12a15eN
ogEKdlWg_e-qHqgWdyNCWWY_4JiUAO5Qp2m8lvFsUAG46RTv1H4t7LA2ju07upNPc70u1q-7XILS6On59VJ1M5D2TrXCGX-CT5XIGlyW5fFG7TfnfCCw4hg3
j-CrwR2cXDyRZDVu-RAUX3uOXvtdWXAwGujpPOdR1P6N__KazC5OKq9tM512tvpjnlzT6SxypPa5SIt1K_o-mRYMu2r-q-QybiZyH0cf8Ev8y1QJ7FA3yFCK
952AsGKXIC0MSpUd885RJDsSWWHlCN4m90cUOf93g0wynPo2q1ruYocFKZe4Jn50GJofHQ53mM2G5jMFKWKGa0Km64zA0JZeOIJgDsUOlGYXBAPlph2tnFDR
p1wC_1EIbwUdcBWvqy64fW0j9cxE70oXCqcB__f1_Ch1XUt1Mimk2042ffYqEJq7Gv20BQOyIaKw21AunSp1K2HuYdcRKvFWBQeB8WT3bT0pJy8hDwSimLlS
-o3Y8ouKXEwWPux4hJHXSseElCKfKPYmEJK8tk8iYb0GrO4a-88OGqdmWp66awZVdBm5DHZrOIJgDoTF0HJ4are0c_D9BO22G2dg9RnuC7YB1GgYo6A1mIYo
-DU3KUp0Komm64KMmD7wIIqMA8WYYwBDkG15KK4iOB7gOEWMgphe5giEXavHi3aNiLXrC7IBWaUfHIXMBGZTek1HQX6BLGj2jrXrC7IALJUdRg4FngeMwgFK
kXPIGInD8HN4qXPSGV2vad1WCC1yAn6lSS01p9SIyH78WRVe3Xd8WRT8Y1u8WgT8Xnx0WK_-muVY01nuY_m7HmPou1F_x50QWazQR8UqI8TjGK3y0G
}

