sprite $image74 [223x162/16z] {
t9g9SYih3a3PGKid__-tC-xWkKN9RGaxJ16VjzwzZoMrGCht_nEyyVsXOATziDnd1h1XvoC5KT0-I-vZ1G4lWCyDNUTJv3uoWe0w7n2w3mpW5vg1pudSHpI9
XhDyhbpdC_8I_dQRRy_bQl0L_cm94ZwbHVTVGiCh_dHUPjT9qncwlrpnxd_uyjS40PzIWni8roNuz-mWEK4qb-3-HIVuGoK8MZDm5_W2sqVmIsy6ruIwhP-K
qujkiWJtRmOgFkzQWlYS5fm9Ns13lpPTTFkNeBqPU3VW_IZaHb9JCdIlPk3TIE4uo5BpvXAapMu64Dr8GgOqo21pSIE-RZAj09pAp03CY6Fq0Ed09F9pWmn5
7QRypwGo4qezH6O8xav4fWsc5MY2ZxjEflxOKW-9kHTfQCmx30pH2dFpPqmOyKeFaNxYN8W9TNQHww4fFIRNUeZ4sEKix2BN1GarFKG-6EriOjVHzEPPVpDu
Nyyrn8q44JVIGzXWhBv0RyanXW1tqklGohnShwUpZHm0j1AiUdOsa8DMKv0p2Hzp1JJH6gmH_0Mt7DmbFkI6QBXzf1L-oWWiDikJQOG2ohrupK3KyE0Py0aj
EHC-Ws5U4-gl2Yhx47tHeyhfWf3M34I_p2EmK46VjUY4feuqb6oPdJLOmnBXrT3fZzu_f5zT2rPbxgm_5mIdO5iN4LEs3qJH8ZUvxCd4HhkGIeEpLvJatGCY
NCuqZ2NOthDhIJpHOREBbVWu-8VZOAp1kEvZRi5UWWOv-zpvyVX7rbr2FfY6h3iOv8o-NCqqVcKjgFHNKURCX98giXB-kGs6JUHemyU2bCIRTbfmRX-Iy23J
W3eIqzLJ1pSIoqDgQrbaH9loqvUGOkuCZwXk933X5KpUlOoVAC7P9MG8mL_WHf3m6WBt1hugNT1w0dkTHFWCZcuIUvEmdy1Uf-9pgdkFWegWqWpSUxIbUhxY
CnGvH8YhFjrESI_JjpDlmH3UgmumpfVcYQZBaRucg7vTTZOt4jC5qGtODcR4HBeWlLE00V0QaHfuF4QSEolheUFZ81A2fcCxq1NnYPz-mZ4UcSWar_K81Tgn
tHVYnw3vQrP4I1oOZamHB7bvT3r5SFROJaNszcORncGotrDqkK7lbH8C5QmdaLW0XgbrVVIJs32poRQY4tg64eHeEhPJS18VKgdjHYqfU2S9HBPxYW8TXz2p
bg1Xqe94qUdeTY3InLXqKizUWeRX5N5sioGcvOtfZSr0wCq87fZSW6ye815c1T-O7lusGPp053b5Jo_1uPpcArtyhFp6uL5cIqHRNkfwfdEQsb_feEoDUOa7
FtjXsvk1fcTl4df_vODACCmKY5d9bchBIrtFBeX9_qYP6NDuwWPyi5uErcQWwzcR13EX8MCOMmx-KH-igBXP8JwCUdP18lkVpLG6jzpwT-Dl8EGKFQEW7Q8w
w84bz7OvJM-zOBaOCAt8IxiUxQcdotL8PMCzFZJ8mAPwVEYGYGtrIBMpwz4UUb9Erric263I0rYJbrrlaI1KxpEeUf35J4E53ZD4QmHR75PKGczOhSMs82zL
FTrFNtV6Tg4tJW8JJEJbCZqfgAyx4rpejQJCD1Iv1NeMGOXY6YFrvFmoWIKlb-lfWY07ebX7FRdoBM2HMwI7C3LkaZk9qJY_i3JeSalqcaie1BMTX8vzVaby
BDLplf0cQ5yBYlcbBhTOpxdGviTDEdb9NdQ-lsrwOgrdN0jgH5WfTuDDUfrASoNebU7qYgBhy7TdGiyL6h3l92I-h2kw7hgEIU-d4RVfWUZbS7fTNlBt21hq
y7pIyEfEOhuPl1uvYK6FAFVomxaCRNvTCz13fmlMCpc9q3aN2QFt2MO4gInh1hgSBbZxPzvk_-xLbD7a9x-WDkBQPd3DrrEz3ePx-RnIWc5jCr0mw86_Ln3C
dzCMDmETIxtKfSx3I3hVeZYxzwJLUQdpTQ7NPmo9olbsgFrjCoUulXdey5LZW1mpqbbybMwoI3dD22xDozS5CJc7esrf_YQPdIz2S3SvlGHRk4i0zZu8sINA
obN9p58vUvEWwWkUVX6XK3PUbPOtWtakJsYXTJywzKINfttpKlSxkqFpDwT_UiwBk-2EUQaBdaQDJh_se-UT4srmKpcz1D6VAlMMdgUUxrDtf84zYquFO3jp
iPv6FthKejGZshBeTC7YxhHyVx5Kxv04E-QbBbX7lNCCYWL9ike4jjRlFc60hZVqzf4jyr8Fu4qmqQaNXYcXOCbrV7q4QwDJp-CvxojqXIfdv-jx6LyNJT1L
mZJe2RPg1lO8_ZjpGYpqZ1tbT3zCzwai8JrdhsPWlohrre2ai5Kpi0iMVn-TAMoPbxeVvjuPDFOCdIu8qQItiPpUvdMzdUMKhHAMHXeRsqcOPjbQJa8g_-b-
hWuOYc8OYdsNSlQVjipqw88TRQ15FNgBcZqKrEeXeaeF8ULxQ2dRGywwN0z9XNh8Aj13sNff3t7R9JqCpExX8URri16JUrkiJEm5RgRqS3IsXwdjc1x61dkO
-zlRukztZnIsttj15bzwfFBU8vbuxf7GlKTIbnuD7G
}

