sprite $image182 [156x262/16z] {
xTi9bXit30JGx291aBp_RHDwNbkkj9UAMcXK_5WNc3z0FMYVRqavP-O7OHXBXbdvRh9dfgbxW49ALyWyycdLFbBFkffAgzQ-oDcNHwiDagj3cW6BqANGK5TI
T2SQgRkHXbtpZu2kddG9DFV-EUvfjHldZIuOnB-pMBkpRExz7CzOx0Cs2aEZTVM6ym6qKuZQ1PSDFNpj7f5ZEsyqhNOy3N6twRYoyRLxnD2Ci16rAmaRvMiN
Vzdusbc4ZZWVBoxM4ih6wqPqsRBkIINEHqBjsBB5ruxVQ80ku7oarWxAHcpqmiEO1PoF-7l2borGztZFKzsWsWMUZ-krIoWRlzY4il7FdkvuhE9hXwFx9Qbi
c6_WiZUAEiG9q507jbiUg_ZQLR1bdO-pxcJBtIZYq9PxFiuuWxubdezpMdccPfSDO_0dTShMlK67wdTiZrlBvcwr8CqKDkhUFc18i_ID7YwChMJIy6JWq5Qo
7giScd-MhMIK3LsOMkr8ktsZRkWwmuwmhwkYQeym3BdHcrmOicmtkJ3Ssp9HhWekmlONSJw2N1XgemckbOZpuOIB2Ni-ukTLMHkMZNSXYtUjd6rlAfixVoRE
Bi96b8rryVDYRUUoXPnLTF4st6YWYxFnPUDTF8ktOTbu5ryltaPiDDR5st1i4QxhDlkWWQi4k5wnVKdpIwuGs-6gzO8hmbQgjMPNpjURRNO2XBjuMmN17Nla
RLOJviNQh2QuI1le-3NUOpl-tbD5ZolUXk5S-JPqtMsRf4l7XguyMoLSQRPQ2LcMROLWPTW2actRDXEskPkkhNipMLllRhgstb9jsxPjsxPjsxPjsxPjsxPj
sxPjsxPjzh-pRTksRTksRTksRTksRTksRTksLLrRqRKDOLlHjHLTMnMs5LrRqRKLNLjvnRPjHTTMT6r5rrPqRNy8syfRRAKKILjPaR6XwpPRSx0Hha3Rl_zr
SyPMJZ6Bi25kwHhbGbg4pSwTCIDSa6f1jbh1nhcmfHPaWpj0kx05OJR04Iw0nTgGS6PztnLlGybtM02xouOw0dQxhJAm11jNiKmRwX2MPCFmi7XRivCEOPas
uYSBURRkpMHje5EpBPsfsbQQYTfWiKesq8dPlFbddOdPMdVlK3iPc_iO_Obpazhf6EDfwtAsxg8sbxKjd3THszAfzWsZRzksRTistpR6vZ-xhMhPjitRFt5D
MxEsue8sDnzZz8MJixKsFiMRwzby73XTssYkQ-lDnMpUnX51MtyEJkw-EGnEokPDqLO_sNfpMTl2wTgEEz85RGlNrzW4RGktOgsBsTmFdNSrsrYw8oAsUTZ6
w2vh0vs2RO1jBLR6LYRO3fs2pIVO3fs4RQBjY81jJbNRcAgsXPAqjJb5RG3JiO5BoFR7nA1jfDaCCEasx9UW3Ln2DWJ8sE20ATaU4o9Zcn0Pcr6E-s-lZNaX
nsyMtc-pUJLrnPhtTzXu5szRkjxVP2jNIMY3nLwmKIu-JuKjtHNRV7ViO1orUz4s0zA0iMhtacs611dL_1NRZ0eU03F_ZxOP6gkWQxpDPdZ-CAmTPvitvSeJ
r_XKCoaOnYZTc2an4niOwdG6njVEfa86wCmCNEcnHJg4UOo_0G
}

