sprite $image404 [90x96/16z] {
hTO9ZlGw20HWEwifuFxNVKeBFQSrNP7pOxJEzWdL59sKpDH3v5pB_DaQH21ddUokbtiDP9iAdwg0X3sJtarLzNzwOjXomJTxNjRGBnh7BBX2EprbwUNOkXmJ
IMSl0pYNdaPV6di6tWIN8KSjHUnxQPm9k6dq0AsMyoOZA-DZn6LiCsNHe65xAJ9rvsi4QhwNshHF53efgxdviOdWMrvpSi3wASaj3SJAMTaqJZfaeArbXkns
QJTQjbAcoNSRUvahAo0nRPqhnzfny0cutkM_zZvNljil8wdxkN6vqwy_I3T1b9NBtMvltYXmxOAZShdRYbBgDk0k9sx_dqhbe66kTH-8-_ebwOEsSZc-xMYG
U9mzlx9z3T0UPJTJwMzZ0q7qWU1nPxlLfB8dz0ytz6Sv3XxwE-i8cD0mDoP7IzHyvKtZWp28h31tMrd0pwEFihbPoAnfV80dsVxAMxWZzkZEF0XkZygyQTmU
aad0Wt5pUMtSVRQfp0CUjxaS0ITi8f-cchE1tx9-9hisb_Es4pbjGwtBRijTJiUjNCv7SerPboVQNCutaChvjStTY3p19dBULYhduzwOd3-SdSXv6nkHqpQa
4ZCTDtP2fjV62IBcxKQyR2HgA-5oQyFSIhFfDjJShLIOphNLtCorbDe6QRpuiFl8fMmoQ8-w8L-p8sz7m6PVSgcdvkrmx_8rQpRk2ABBVRP49144aKiz_ZcI
S9bylV7g-qWY22h7hACD92wLnni84Z2Ln-Cc0JCvucu3CaWG8SiFT_3W8L3gEXOY3yLjRWIsWwXZ1yyNRfMp4RSzoiJ5oa1oy4Eok-x48WqSbDtEEkJ6mTkW
x2xBW4WEdilks1Znie7-tBH4t3xOjFSDz7l0wtkI7xpJfcNZzfTD6pzulpKjFskpBhzislZ1FpOjrK3IjCJ44zvIJUC7hzZBy_m7
}

