sprite $image419 [242x176/16z] {
vDc9SgCm40JGqUZiaSZ-_zykDavap941AqM1NzrxTxg5nURVCG3y-oI2tWU5HYKVKt3rCGLNSlsy7vKP2wwSzvCo2zPTk-3hHyvG-RfAtYzeoMKEi5wwoldL
auyPT2NkaeDE0SikEUXWi4BaSe5XA6BLrPxGaSZX5zTwGZiYSwd7Ddx3H9JmgylaHQAUXSAvyrQMRe0hP4xGeBjqXSXGYNJde7JMVYj7WzFVjWLAz12WTyAu
LQ07U-ANAX7eMNemm5ap2xOmz2rYcvE-z4VwOR3LYVgjcAg4hUGi1LU9dWHiTvA2gq1F63XLveGTB3rBs2EUOD0LZNZeUGv77cV1FfvepwnJi4JXq6bZ9wOn
JLhFT1CXSbJcZDteXLT_aK8kSj0tC0Zx1NgbFGU-AtBGfpFUGHC9gwAXErEAOCOnUVKYqQPP9qS3aqi-vDDPy1vF4qPJCAKk7tBnnBkOfkAllpeKAGKh3YXO
AT4CXtdUq9sLhkkAODK1ULKiaNRMYMaG-xXb8V2VJXij69gJLlxpp-Pxlu9VoK5vzQEkB5v5fZjpApWB9j8VJrlGXgDvIqzqMqO7cDdTC1Cdp9Al9dc_q0ej
YFCVIIYZWiF2hszUCvg9jC3DtJdygE1ewPk5Y629uF2ybQCbCryLwVDc35ADMtzYsT61AqDBmckqK0iErb1bfJRV_h4jQ2hG8Xx_2llJOtHK6KkkZ0fkdHbj
CIqoupl7e-1anx-cb5Y6WXMEAxWoj2m2VbnmTACnHodTJHPe7LHl5Ma5Z-ySoHkgEEIkLtePMnmR69PMrJj7TlJ4fFBTha2mpP5vaMX5JGVFCsCkjxYxgByn
sbvG52nXD6PV7cCMx2UgWeyPjJLKcPWLxUeSaXUW3JX8DyJDWWRaWBpmf6LyLeovJMRy8KCAkZ5xOsEBQN-XlH3na7HZnjEOKo_667hUU-USPMRJevvn8RsP
MT1UCaJ6H-MJcbBFzvYPLDX7R97-AcyAth8nz6FefJaR4pOHj3t0AGRlBC-4CyvJOyOb4MmdRV96RmqjYo9j4XjhhG_1audTJIbvL-OtEdMMsT0gHkbAOT9Y
PkkS2o54z4GazqeftO-CCiGLmHuY6uCEwrqDQjWw7vDaSt_LBQ9C6v5Bft2FYvqaPsbvZx0XIVcfv5w6m96Q2Na-Oo_dB3TT4UoMkzoJTnCRwqE2l3PK7c_m
Mu-hZvBbYMALElSDvHkHNIz0XjdwY3ojemn_vb16ektOnuJMvDv87WXKw85TG2wzbx33xXJBKB6nRTxIrSJApE9ydAxtvuXX7gavppJ6BYIqKF_HUQ2Rjeno
rlMk2gJckwuanuP6Z7jxuIArfFn4b8c7e3reM58pZxCXmT2OuV3s0Qw9zPcbhbVFa5wgsql1cid28n3Jha5N-OMWiKWRC23rXbN4iw4nonItvrr9t3upqnRf
-sxv7JfBP7fXTmowodySET4cyVa4_NIDu4PTcw0kk9l8S-I0KS_M9_KZFmT35ITbNaNYnfajRPDGrOKFiYHNCqVDbLAVE8kW2Th8evfRk6NhV0Y-5nK7M96u
SSsUDkArXsuDKKGnQ4NYzfcPjiAAfuMNaXM3LYHkFMtQp6DLVKqMKGnQaRXjpU5_EVQ192iG0q6qnq-e1NN_qtxlxQ94h1IRDtX1DMviRuzlGY26vbD0_CJV
I41CpSyHw4QzJFov-9qwq8aDceZvBUmy8Zt25tXPa9XF-pb2NS6WaPYRhoFK2GmQYVcqJoFMC_JNZelvPHx1Bk000p4tNqUqpR_T0-8CymZt00SOYEbnVenm
L-05OdgPhoCUU281CJMVWFY-zRSx5tFpOu3EOD10p8xpPO1EOD10p2xpQP0Um0l4nFmOg0iOD12JQJ_XRsxoIldlD7FCvWl9_lLAYPAqpfamRLjGdZBenLsV
cWbcGoKjn_KzFEqZiid0-YbycVERVD2jp8QzlsSbpAa7kCzbvWTO3Sm9tWvcFkXLIYPFA_T4IZUR5VGscRObU2jFszmJdaY9qoupw2RJdloDevNP77y4jpBR
nDvUv8G3NDey-IjM3tF-0IxsTCv_8jLxEdEl2vHWBl1AMMlQvWdWgjFcWtRbbNAPZGuwitMohC6WiszXXhyPyZD8jeH1DxZC2QzO3Sm9hrYLpGa7k3Xvya4t
CtipBdywUmeuFpzUx7hbW1Y2MqoRYrMYuyGganqYLgdonQvg9OjLiKInYfOcLjrInAhTtc9N-MnFiI_gq7vYLvVs4QjJaujTtO9YDSo1U5NFmcBrBIHMwm9Y
TM-ZMA3QPWTFf9uldWx07NgHMA06PWVUdjDsuErfTd20UqxRWRUdsS6WUqxRmGLkrmzYlP6-YLUzcJw9zIgz1m
}

