sprite $image264 [188x137/16z] {
rDAn3O105CFGyfI__xu0bOkq0EStWHLblMcMrToqvSxw3E8RtLa_pLWEqz6RS7H4M0vZEKn7RyBH4M4v8Yo7wUZDE3g4vOYm7AQZD-FeC9P3M8w8ZjwCeyDO
3c4v8ZfwssZqinaxGN9OPu40t20X8Lg-_t7_nQxCfhnwGvn9t2VuYcgm4ezqhY8No2NqaOu202poUNVH6uuyDFhnvhfyfaG-xwjBnVVqoESzyeuV4Gytxv7C
wui-5D-Z8w9eHBY_jFQHZk57semmYFQ8I8_YbN8NV4zbUAcZYsZnYF6YuaG-1TyZOmu5L6qKQB7n6ls8T1hMkbXh0gX9wu9YDXweVVnzNHJVKu9k1M86e9cs
0bXh4T6z_jtInlcJBZw7chUca5g0uaKh8DRxiFnR8I4_VT9jqff1kfi9f2gaTrK16e-jaFvy_OXybfCUim6GLb56jmg82ceqAMouHVt9-dZ2ZlOvH4K0Y1NO
QAK04AWx1L_orDh7Kquw5K0feW2aYFHXAW0QrrCKgMJa-PEkOnhsQDEowrNA65LAX629FAKuunaxshQ1ZpHJs_KYDdmMt8sEq_h8PomddLHyIHrLcmA0qR7a
mTh78Z__x9An6Rv7tKljea75aiThFnRvoHrjq--gglXiMFASsezu8FVhWZMrCx3aIRMF9vnqyTdaFYcM7NrMxPzJ5vkEEWhMjCtn-oGrvFcJVXpkEXhkVwRm
DuEV97doJu3P1NlCzSTdgcNat9YHpztE4uElx1QtkaYphtTd27uT6TjC43WFUrBFkNsWT0njhNykhvfWJ-Mi-7tQdBcX7_QyVcxpi3QQ2iojnqTTZZVZc9wG
5supBR_PyteM5BOQlHl4lFRFFL1fCxEZuadvOayNXrvwFtvzGdgltkKsnTIEsjoOAlfYJ-j70TJT8qRt0dKhNO_FL2I6hf4S-chFwqsjArhqNTy5rMkfQ9EM
sT5jCYTVxNdyt4PjJSeOVKGCRmAp4XoIsj5yNLPxNizj2-icFKOR4UucFbdJ9pqlN-rv_TosQ5ujmdk4TzB_xAJFEo7FwhjNZ-WzSZkQEkdpRdWEprtVUumv
EtuVFrcNrHwFwfsfhr6T6y_9Ltih3nPdPfu0EixNPRKBB8i_mgYf7JqhN-qEb8UlFSlpdrsSlxONGFWpl-xDvf9uTfsIh_O0W3XnBcVxrxficReax0qLSAv9
71nzrhDhpfHTuGMDV5o_RLl7FwMdwfAp3mZRigpfshEU_oKzPz9UKJcW9Cs29se_zDn9dpDj1pe9aAn0ErFxsKwSz3dpzWv0lM3iTYFFw5aUFEcSZzWLQ0AW
xtPdTvAkuy7Yk3noqkTyn3u08xl0o0eX3ThPuO_MVbhwb_HCXhTK14b78IkCDEpnnvSsD7NIEH-syr12o8gnsnL0FrDxtoOJycn-sYhYmru1O719mfEeIpgz
z-zwXt_OcniW9oxE7ygthH_XbqZxi7TsQ267Zx_Kyy6Xh_XHML5t-pZkJBjV-_VBLttG3SKKu66lk8_dk-hIb_1B103ai7TWmJzBVtxcgzxTAyfX1z2z0MmM
2_xTTRa_UeDzs0TPG0CQbrnWw6ljjHrssUrrjqlXchVBLtqCigCs-s87H0UNN42-DgS34lBL3ZXFu_dOjoY9Pn7QfxtJK87A9UyV-geVnWPrBt9ixr4S6rno
1VawUmM0GeFlTXadYiDJtwAyFXIeSREtmNROytgUdNbU7oh1czsFqta_hwXBlZW_xIwGnZrzqRzPlkhxDxi2WZf8biglUKLTydhxDdUC8QZaM4xc5UIh_ekT
us0tM-pairwwvtFNlWUL0bGkUKdHy_Voi5C0x6m7qBdaXNL9FT4EkwgYadROrxpWMvJMyx3hqHaAQkqizqV_zfclnV6Wo65te78Of0MNN8I-_gGj35HMeB81
WApuIyXNlG70xSuO6YcLF6B18zUGh_gcgZTxnI1LRdzhglB8wrOqNvnFEshiTaCX5Jno8VfQd7wpLm1oDAbG9MtlwPpNt-nqGDW10Ag5HwubN_NZi3EAi06T
7QWySYtvYWzjnw-fyAFj7R24lRyZ_9A2oZBOq4aAEeya_hfuexw8GdWyC1NE8vSS-gelGE50SGvW_CxUtnj-JpsE3NaaSz3VhnT4X_p2tfUyNQ_G2bti5wIl
-Wu0PR6lyYlYcofiiI_oY-fPss9Vv9VLZyM-V8kkgxybCVJBuHFoo-aJtwBBwHCplvm-GRySFY6_d3uXlvm-8R-SFd5TBeV_sw7_5m
}

