sprite $image124 [312x218/16z] {
x9dPckCg38GH0a4Hl__hdiLarBGICfzyayIcRcRB-a-LjWuVAf8QWrTB2QsrGi6ZfLZRBkImv8XeKo4j7ew83lAKkHLHbQlChOYg_6LkHVHecLiHzPUv5L4h
yPIv5L5_cLiHjG87XrP4lMLkHVHucLiHjOhXjLP4Azg3RXk7LreHHGgvMMtRuiRrhrC7hDaMDofjAbtcsPZj9RSLqQfiocYsnIs-ZkZmG0nciznMHESJclmn
s-AMuTW829tQX1kbrKMV7zhIYCrooz2bTKNK2DjliQsI9LuuelFlppDksV2-Q4JP8DR8LiljiIKZNpIYzeip6YXqqJDkCXdvBXPHUZBUYJxrePyo9Z6_KaIj
LqZinQYsaPi-m4heKX5DimsiAlLn5k64-KjT9w92ymrCCPHX-4LxQTsBH3I-CYR6hQ6JkxM_gCJBH7Hkp6ncjStn8uZJHXJoC7jOGH6WJNJ6CiVLCNkKfmyQ
MeD3bKyRKVFD1Ds2JBy13XTCbqeyPKJpqzb3w05H7IwOFWcTFgBziOWXidRFXzOWpIcaSqMqngVhGQMGxyjLjQt1q3nhcSlmhmUWpYiQRatqaKrroZB7ZlM0
wuWdzry7PvarzO24JXZHOco5rjBG5snhQ4U4zFKHPVjOdJsaqw7CWMepIgOrdA_CCJodoJ57kILp3fct1hyAVML4v-i1-3vx1225G3irI4hbQMl8xQ1kz9qH
hJoRFL9hvPv1OF1bdhS6lxQDpX1HdJrYRm9fvwQ-f16HlM0Uq6txM6vK_AV9RhHq_nMw7fIEAHrVKwtPFfPRXdSzK6wXTbXQoLAd5tXomNIRxMEvCRodIUG8
fP7vnwxKfpGyz81yi3LiTz6NHTHk-zfRyq0ZORHLsN-DE7Z1j6Rhec-AQ9ci1r6_VwP0gVRPWwMr_Uj9YSR31o-Osu_eYoBA4yAYQxgPFRZ9T3FmjuRRDkEM
SdYhOl7D7keSkZS4Etl8dbpQ2PTwS4srr2otMD-yj6RuJfEAJUhz-wl_IWFr3A9KTBFox8TRui9ckMLect-BsBSUg5AG-wfU52JtNnHbfrYEhwcR5Jtv3wIt
HDHzcXGcIcWedS7G9Je96cRTRFXuBvYt2JSnfUIJ8YeqcJt6S8g-mjv3SqU9txKipuQQUgo-CTvxcsDuJvD8WHAPRWX9dD4RPIunHCL68UyFncIeYKVwASda
utvSHDMNsA60neoXeuceriC88VTvZMT3ZVZdDyPxRtEvlP0yzsNwsT__9UPSbDx6GIYigoM4ylwls_4lnsT2WiDCf9gzszxTvYi73bXfma-qz-E_jxddvgsM
OTMsmw-bwvsdFULwB0R7TEEtRCEdlAHdaNzfebkZiDzeZMgbGym41RbOlvWQEpc-ynK4KEXH82KWe2DFovcjzOzNguFRIuC0E8EfCPAxxGlezgg2SKXcOOpx
Vm5FqRWHNpLEnlUjDPEPtBJtXVCbUhqfgx8iXQDu1JnM_NZ6jFEaXB-V59HlaUZrfgm4Zxr7eZ4l9Eaz8lBqmjI0PgQvvD8j4jKtPJ9zFD6Rz_0kZRGCkga1
OnnIcXert25HVLCclKTinPzl_KhUMqZEmw_WfKtMJpZn8EedAdL-cPE5nDuQwXlGVDmbU0y0sBCkr5FPLsM2zwpEtEO7vVyjKNrJXilFna7uwNrvaeJtaAQc
dlXue_dOC9hO8qwGwEMcB1qPc80fELz7nbNJ-zQaZGgtbJbVgCRV9AfloY3VCFvQJvBbU7hxllEaewcKTsVBTvMvM8c8IlX9elgc31VZ5fsl4EvstAZVtxTk
dwTJxe_7ezzJvZ8TiVbV97fze8EyV3zpP6G1Nsqym7zLTj7-6C7_lyo5IeYiI7H2QwZXt7jivqEHYXzqz9qdUe4JNPGVPymNQmbVpDbBr7ZAuuT87z_Q4Jsz
HqN-e69fxrihy6LY8L54N-pcP4EGKOAGwAJM81l4UCXdkdxVIWb_t_XTeahAhIrpaJx511-kd_MhQ3bKjgAD1xWkgeP63Ictlinjf4L3p6WD20h8GyEtjPBW
BoIgfDpgCiTj6JYCgH9RpE2Wh2O9WAf75rMeCIzDkVQ16wyY9pUOk1ffv6Az70_44B_fXQtZqWfBmfq_SkEsW9n-rg_iL0eAc7uSivwzW59ZwJsaCBclIRdU
5Mv8kGdah6VzOYZQU003Z8bAyHwWjYhbk5zmcoPM-mQJw7erILaeLfUeG3grF_IkSbj83gqX6RyfNcLjzCLCJTxl4v9DSFD9S5jLvh31D1_77C4PnSuWqIKf
rv_144EDWjkQCeSnrNOS4y4Kq4M_KqFCiYJSmKt-gcdWDb-i-WRpsdjK3F7H9b4PKrAkTmI__wffpCl8oJ7LT1oJ8lx-k_TOa798DWIBUa49t5Q95HjCmt5C
oZ8thoNA0k0iIz9VWz_LmhoQ7CRKhwj92aW_WqInw9tR7xYBuFhs12CMYHMjmR2QZE2cKfDi32dNVmB77supBoU73QPwSa4CyUOksd5nNSfz534Z5eXLZgdw
oGN241-rmeRKMfzoZTLa0xV5vB31r4vDreWYnsoGAB3X-cmNh543jzLY3TS7d2WBnHgzHzylylc17htpL4l2dTK-oxoQ7CPKPJLPFVggnNlWy_FRitsk9P4S
1RVbOesNfoV8eulQl0TBD9sXsKknJg06Ril9aNvw0aDyCHMsBgwCI-UjFjS5wrOOiLAi-VF91S8Gdwnx3yP5NEXFFfCjYMw5UJavI56UceoONvZDtgC9xz6V
D1XCfbeIK9FSrekrl8q7bCGH6RFtKAJR7mmxVmsEVwC6Rkl9nNCy40kHpUGzc4T6il0U8z4wdcNC41VA_mqRkAqNQvMhoGBp-_NZzLEBklT0ha77IWx_J0tS
rfDBWv18GM_eelpeNRHHwJrm4MPb8JLmMozMgczTjFYaKfCm1g8txy4lWCyda6-wHATYM-_cQeHxO_ugKPYB3aAAzq2PEo-AvZo7MY_UWYg5JBFA72LPv_IF
XqR1fp9n5Tv3MhkE9rT8j5Dmpi0jZItt57ARDozqXJtZBhm74CDxe9c2utI9PkTCt8xXiamHQn9TrF3n-lCwl4UNtkDaoCnB2riV_icORzkU9njF8CVZY6Lb
ozu3FWs0n6FZDg_t7f2ebLlzoxMCZFjDh9nTrhkeEXMWmk6ECjN_HgrrDHZRQZP4S9x-qgxn37BCh7yyVNn7wsJHMT5l5qlK8TWGv7PmpRaqovEOFXwixgNt
GBzTvpqWKN2pATKLJivFT7FslSTh1i9xu2buZ-KIjNEZH7_WDgw1fenUzhr7xqAwG8n9TRttW4Jjt7Pzvl5jpwb3ArylThZZ8dh4iG2H3opq7f0emkpVF7CB
03T1hARjDGZY8QtuBPUedLj3TQlCBSA8J21dsbx3UmprAUjoZTfKYTgvXTpEX6j_6UUPcMBSsWIn6hRNSgf_gFrslKHbVB5j0uftWPYtFU_QOVTbjBOavHW3
5dGgofxIdATBrCxjC6oZAzIuLxXwBBSdYDMKSa-Yt0NMFjej_p-9shcT4y8pMzEUTA5LxmhF9QVtLRdt6Aouo_tHUedQkQ65RaUQ5UTYOnf49vKvlaoLZeCV
Z8VqgMEXHEtS_8udb1r93ZknEju9f27X2MNEP4cmzq1Hkw6BchcDGlPNv-22WtSX3w9jWbXD_G6DOIJTKcgGg1vqoMsCfCu5N4qk3j7MFsUI5Kyojp_8gRxV
9L54QXVSoBaYkD7EkgKz4vE39tdvpxH_t9g7SgHC38HRaqVjU__7_OEOmYmkrQvrQK6Ny_ch_XeDy1iYn_NpiViUSKNzQJutpKWdRcoGIHsfKG38-lD0qq3D
-P5pVZLwtoEkg3_INMu362TkB42Heae11hj5agU_9bPpVBwInEzxn1Nr9q-76nFocTjMRycugULFoTDV4vRLIL3WlaSaR0sdYTISSHl0F7FZpCOj6pSAcd7B
06gWvW8hoHzHD5fpneq9PUCssZWYsN8tRRFBnardCfpXclCZ5wSMLpHSSysuTS2uzQ_dUPLFsDX-ionmyPhp8_TcYlerfqKDZd7RCbnFP4LtRfQzAKyVtiIl
3_7T8wvelERQnWr0RRA1ctC1pf2XQP34AhTg_3HGS_vAyWQA1cfETsvA5Ooz-KXgnahXPdfZix-XIu_Nd1yv_dWxHVsQOpLkOlNMaQXrSLk_28XnQmB8Hh43
BL1pVkISOdi7HVsQoqXa1WHv0aE1JswSHT8mRge64TsuLQVcef5xNqNzckl5K4pZKfWtEEJey_5wEXEayymjJku0og7s5ehwDRVMsvdtQ-k64daSkL4pYiED
gZyXwvifweyCFiu09ZcIRDoWp8Ti2c3NLNKyZTOSlvBZEohgrnmRq5hHRjn6CMuf0MaxD2o4WkHo8oEHkuYYViqr092vxo4Dc1m2qNLe1Me7C1rkGNBy-1sA
2dxZIEDnh0_gpas1JAeWBPC5DcDngqXD0pNdHkxZtHJr9ur7SgsJp82k01OhldvCv9utETLalERuSHL5_PexS6C1ibgbhT4gg5pSD4E0-cja_NNKHiAVcNgM
pOgDEerWcZD33qmEUuWbhuHhBZu-DSrmvhVNd5LQfo9F5a0cfv9DbfCxjrQ7MJp8dvRrKehwDIV0yhCPE79Ke3zmwm2aJa7-_7CQ8_VB51KuyuTgJWlckcSq
054ouS1DCoeRrWX9DMHLUa3M2ohgrvmgLL1eu0gPZzp8qJc1ggC080VMPe8HgBahAkhNt7wxo7AdsT0S9vcX0cnfHDRbSa3M2ohgrnoh-TiCNmLEQPe6qZmr
xCYBMu3S9HNrjxbcF81Yt4eQFFw6AH31uZRP8SRjTN9NLzIlkI70pgrJ2RI7omSMDrcKUs2RkwwYVirfaytFvI2GIpcWrMhzPjouvoqWwrKLzMjkzCa3jzEf
LFEsiYZ94dgN_mgAnW-jRUScWlJ0TL21lhCjafe6PBs0ee53Qz-vJSsTfwaGNTpQIcI0t7KLzPyNgY2fSLjsoX6j9gIf2UZC00Ju9hWVLrVKhpa0Orqvpw4o
h3QT1gy3ypirnnzNLzIlkPdG5pSBbG4wxIHRtggo8Rr-WL1-y0QA-jlSvE9cpCPZg5G7q5asoGM3BvBxdmzleQXVSsdFMr7sKwWqRuesGHOKlWRE-F0UYler
rmpL7geJrZ59GMC33F1pSaj6NbPHVyhaOTJu02qX2J8vIftdr-QixfJFoN7HuAjXgxZ0UDlS2jKwr9yVnMPavHX9oIVaFW7nJehwDSTkeQg0SiZNenV4M3y1
Tx2HjrBKhpaMfCa-yoIrpTF9r6JAV3O79BoPelvh4HaG-xcvltp-ERE8z02t-oZgrrop6782KYO5XNJLVCxjTehwDQTLPB1llm88MVACShkbedxDaGCelG00
MG0DShkdedxDSJEKihYLN3N2xJQA-bFFAma6AURfvkpuDZT_U7L5_Msk0QLWSSkZ02F0pLNqJfFcbwTUYridCqGrmEssYlerDtfP_JR80GZmGiq55BrTpGr0
TsuswIcuEoaQt-PANzmc83eJKe2Rg-YDQuwVtB9ztGBS74LlNdEoSLiRNOfo6uARpobKMe_SvDzsxiA6OIW8Ot0Pzz-tWdBOuLzUuPFEeSi3Rc14C-xcljms
m0sCQ43c-hkTmOYcPEwqfMwtNO86pzm5k84HpSiSSCiQKRxzjMjq8oEQdxdRSTlW1aSqFtCDRfKR7sPEDv0vtK3cT2EPqmrcxaBTp1nrCtFGpSnHDpD7tSoS
RdJxIpV-PwPkVFkBkvavxcRck9kPusvcZYtmcZd6PkRO9nap1zfcvbvkzxqY7JBtShkeqJbpxEHJlnUoOtRDt78l20y
}

sprite $image124 [156x109/16z] {
pPcBSjiw34J19uXTwFz_zuvfgPH3fNGohgztNf7xEeC3BgDKNfUWBSfd9Xk06kJpaXfwhCY79LJyIKkVftD4uwVfFAU6ZzCvOldZT8u7rW_JMQLYpzO-IgT6
aM2unNrJ-JzJx6B3CWnqzwrzZiuYUnhT1rkewVqwzRj6Izk9BHkWyVqwvviWQH_STh15dThkhJh73HeLp28IsDbKollRBkZb5T19xFPGIFVDT1hjktN6nmgk
tIhWn9TeVAVEuIesOeUx4QJ-CAM4z-iC5QXnB-9-71INiVmkdJfqMifPn71B5f68RzBIMtIcurFUU8nH3ECuuBje_DSwhHoV4hLObbH3vRWXWk7RbF1lTORZ
KseC4bkGrA0wZaF6zx7qSftpDM20YbgGXXkaI5aU1y2mwOjrphsXX25BPGm65B5wd87qj-D0Vo5RiUlUeCR6AX8p09C0EqpsQxxYClqwUx7E-HemaGJKeYWn
jYZX1hau3lGJM_mdEXi9Ywbl5ItcACboRYYAqIFvQcY3BIX-ttPJJHKPrq1fhJ199H25a020UTyokn-7DgCDjcpZmFzIvroQnTXIwChCe6f1IWqAGmb1wcd0
SLPwi4N5dlA2kxCCtYOLKIgiyvOgaimCbgn8F9-NXYdiR7bUbD_h1Eh1QoYIcO81LPgAc1dRVRkisCCzspFJuJ4j_bxdrz9IaP0CG906INttZ-sYfTE0a-Af
rF1RdLDfQL7K63KVlH5palXmpzPzr1bFnSelTSwbHQIS95Z93ILcKxHGxE6UHOSBYaMMQnVEEWrJfj9A0WOnq68AKWWOqCuwSmDe81PPhLsoFvz7nRUfexIY
v7hpPf9S9SFEhrlxRosmZknE_7hjAkpuVD8v7OTq78VKO6WYMa8xzKO1qK6xJWDzspRYTsiN6wpNKv5aYwcFRtxCQ98wRhRpFNleR9sHllKuVxDsnM3tmB1A
Fj_XySPfhO7ZdjsFJ3rqRd_Yi1-l7M6duDjCxm8fbvspx3gF--gFpcDc_eFH6J7OY2kwzN5GMFXw3MYshXD3fm-rZYT2vucDX3r5DrwDUwRUc7IEOUsFV09j
OvTmiF4viVExW9M7YwIbeVDXoPuT7TtlRAMl7VaqtVHgh65S95eCmADEm332vUYyXnBRlUruvCcrimxpeDFko46xpY-BnXFVtyy4lMTZFJxOirYxwLeTlR7h
Z5sdsT4RF2Re_3ew_oiSnnGviXOxNethgJUqTC6uPIoQ7SzdbFNeU08bVqgdZ__nOVbUkfDE641-7HvzsSHZX2FFYatZjjjFH6n3vyx1GolSUpCiHpU_z90_
fciddVLAvx1fCDuuV0ngNIVqYUrviML_sxSqwmJij3eaEoJxB4OHzop8hjZMT1RINMVjEgVUyFjG3FqgFQwYm_BnUrTald7EMgm1K0LeUXu4z_K2Dng0czJR
btOJ2tC_aN65jdcRg2ocvckwT2zTddLQ1zeSz1tPwJIGy8vZM94DD2JXbxXAaheMM-HA9x4l5hqpadySytpDhdKM4PbjYaBKLtHizQJJEOhs4EitiORDhNzf
Fz8Pv8hDLPg6vThPtte3syP3xDR50Z_JAPTiLLLA0v-XyqT5zBj37bV1VSLEYxRnIPqp6qYgqAGwwOi-cJj-z0R761_RRwrJWronUKqaKtGLj9309TtydSNe
ZG777-gyPki3Io59ovBZIkmyklwutmY7ur_el6QBH6CD0LbQIQGlwERlB4Pl4B2fDzOwH-0FRA8KTS9hA57GYYtNpXvVLCmClelzlSwUK1_OIcJtIWHjgKMH
wiXtG2n7TyGNlR7GEHBRYSs2tjbeCMH8GL2AbANOnvNYeZTMEaUo-S764gMwmKcKmfWtpP2Kf2tepY_lF-mDtop9zocuMyk0YBRxeDnT0vsGibMnLP_m0OM_
rJadwE4rIwlIKl6MGUQO2aGIOdAr1TqOtKjqpcjdeYgv1ek2hZb1SXP9dkAgJuxHSNk9pddjp12qY1OfhCdOdJPf1zj4DzV9otJEQ-SrjjBqPb8aarcAbtXZ
yqNRhNyQw0kTwxMh4g226qvCP0iX259arVMFA3eSdz4PPSvwxHoDDpQ4Gb6wrn2P8hD4MuZj07YfphdjJ1IrIMhggiu-n6OrW4kwL-kSrqu3GcL8tYGxoH9D
GfRg81TzycgTyzgXUmtL97GKWrIJ_XYJBzRkrJhdjYjIGlGafLzZhh68LYaff9NOr-iSoLsiQv3CcBo41fAjI5LnIFwcJ-mLEjSfTD9fO4nR4KdzkQc9UKn7
dqnqhzIvRZlFWKMiMR7-d2D2RY8Hrst7r-bShnrYAKAF4gftk21PfTN4gz71hs_rIUThreweGeQ8gFV7d4rIaSQPZivhdLbUdigEes0AEKQs3cICjONY_49t
u-7BTQxNJgFbW2G9dIwKtFYGdOSBdIzDsg-nd4gXjHBlSF5mEj9H-0QTyzfLoIQnY5gxFOFNR6_GEQ-Tav2gKfjKuqMyvpqwvxNp6ZjR3DNzckrjEkUrqtHZ
GvDS5snlq3bVihM9GM9CCzkxTSvjrzaQHNrYUxVEUUqC4AMKcUtzEkUrGxnWM-Xysze1Czkay_q9-zhbQpQL_pNnUAMOsJQJHTwqTf_9rjVkOzdwsdqgcqXi
dylMr-vZsKGA_6FP-jfz8jjOky7MPEI3rgwFBSYdfQ-TRrxa0nCgkI7APoQQoWlp7m
}

