sprite $image374 [262x220/16z] {
xDbNcXmx20LWb0NKsFlVxRtTd0h8gPpL8_CuVgh_4t1eV_mTjVrV-gYFAzUsConCeHjApzfMGs2HRN20XAwam2pkERXQ1-6V0nI-vh0CWcSO7ROb59P-3a3u
vy1ZoO8ENc7HRG64-mwoWC8DXsqH19GiipKxkxhR5ji2Js6rhSdVAbcXBHYrR5i0uPy3etx2OG65E-D1tod2Ic4I2Z6qXHs0K8cehJmUX9bx88hVrnRloG5F
eRYdiE1p47vK3OaVrM9Rqa7uMf4eiwi5RasdW25PxW2yjv-YL2uE69BhfGVLYqCvXcJ_QOVjnHHK3uPUmO76MEN6KeM3Ao9AAuq7LIc2jZWg8p_ylCE7br48
eQfpw04BSurR4meKXxPeCM0yBj8MK6XPdCEEKDeIMtDN8EgkBQmQKLfXFAXAD8MgZEVW4dNel-BMtEPFJGKA8Ja7kpMH8DvvUX1L5IXG4DSMrHBr0ZUt28ig
1oX8SmwviLNlxzb1RDshbFPKO8eTRU4gKNd7MrE5uQ1GeFIPK5qn8NxQeSyw7U6WsYCK6aArkxd33uw7aM9I1PNTGPe-5Ie5jotSK_ZEKFtszZPIpAZW79J3
Ku6gkZ3PufwUldDAlfrriPXGeSdP5gASiYdapERZgeTqsq5Wu2HWCPr2m5OudeCf98gYdpXadoRl8tYB2HKeY6-BRWf1PDoQZUuVtRfz2K64TKQ5NbrRI6wc
G4EeJZ__53QLnxzDgK31juLgV2fGqcjRz7piYlOD1VsoWMvlqod4fm8L5TSMBK2XDxaw7CipzUz-2ji6W_aKE44X8IpjRL5DeL4SRiqx_y7xMGIHGsUsQqgL
zQaGiHNEK0q5geWLzt-WbUqB0s7_-tGdfOMbXq9WOVMX6Wgb-b0TYT9T13yGPbHGnMcTgobGPhyrJI4VxmILzrsH-vtHkC5WJWLycQWA52YgNiU3TbCWLZSU
-l5xLFxcKy1sV9jPGTNQeWKezERR8a4XPhJ5jwQaVgKP9ks8Rbyceb94xAPCx1p450AbSKec8kfVUGgk6IPMOFja6myA1QfZUZ25gDpzUFXSGspE02gJAnpv
46492jc7Qiwcq8TGtVDN-i5jn_aLMZl6W_JpflIX6WfKzl7fApVV3-D0c5-XkBPefc1RmOLgADJsgKFTUqElpU0CvbUWTccB7fifX25KDrCexftuPI6Rtuwl
eQ0zceB4TZg8AH15zQ4Q2jGL3YvI0y4tm_mA7rHLkYbW4I9KLoW8-vkxHIWa5wfBi4WjxdQSNm6bc0GFXQ32UePgK-X3g1OsXUZRekUEf-1knzTGs1zwD8KU
wjaM2WKgGrjKKmYYuysjRZk-Yi9vBeWfx9-CjWXFXQpDXsfEfY3aGxLiRY2yYi8r3vHTeV4Pggi-5GebkV6JdBg1y38A_eek-mh8SgO79ifsHxYjgJL0eVNT
Hz0ChwVWlknSX2vK5zoKGwWk8iCxmKDuFGKkuWSV578_G_LvKmvj0OKzSjqmc3SxDdT5Ton2rnRL58A83zKrG24trHi6KoTekNpPTH7A9LIR0jCGghif98gt
592fFiweK3DVnqCBfi3XScig52YFwS4Kw6O_RFfWdVEQ2jsrXPW2qWD2TTaL-XYgxoiWJqoN5y8-u9o3vlsJMSvGNUnFrOKbKH4et3IOCI-KWcigiVir8U-V
Z0Lvf0Vh0RzZomq575cpvWKeKFGDFtuomXB-LCPVgh-XW0DZoZi2OIbIVzuHNDruoBj2lOJgli_3f4EetcuqmwHtXFLzPLnJiRjGtVPFBfUsQFQd84Ee_e-P
kzjosuM100uOOoHozltVzl-nZ1A6zgpIKvBWk_Oklo8OoRW_A5WnRAfWkQX18HI-s68AGIXKTmMD5AfPuSTv_9PVZ_MoI5qXKwZMCq8XZQ6wAt1wQ4unRArW
6vzMA8GaD4sGhd1F3sZ4qLFAFLGtns1Z1Mb3MSZZrIoLHRPPh0wX-a1dZJs35Pnv_6uAwTIXBEI0GipSQyQkK8TGFL_pq471Upcrwqq_SsXG24dvZMrN2A5G
g8P2gJWfdMBOMK7gyClQ5OFWhwai3ll9rp2fBdRD8zFlTURnczxqo-Fs82SKmi6zvectTpIfXaAWydVcyPigXBDnMLWRpQ4Q2fOUCA6Dfk1i21ihN14A6SD6
AmieN7EeXa9-b8KAAV26iBy2BZPs1SpOh2pqicugqQafjIj4f0SRuvi2RmZxAzJxlWU5AErnQb9FgUQWIeU8Fa9rWWBrZlihz1zbLnEwWgPhB8kQe92cK0q5
6K8rkYagXkqLR8KhVfXqXNjZW50jVHOxfmVHhZ2aXvuNddqvjOy1oa4j9TjzHz4nL5zT8QhAb1wIZUIiB6xKE-wke6AF_TwXCKZj2eL3jNI5m9FgSdI5yn6g
LPuTHE-3WCaf7AmnI7J_Mv4Uh87aKDqLa1x8OFUrC7teTk5VqgQeNU5iHSPGNHvVIv33OGg5HcxRhmLXXQ4ZnBvdAJdaiIpiNkmrX-eU6pN5yZp2Xrz7P3Q0
mecl2TNI0wNaxa1jD8LgA8JeAD08KlTO1wnWxP7QZ0qAQGhLmzSImwcPIS4pwA-sjp1W1HgkYkemOyjj3DNLgYKfJQhr2GNEbPiWc8AUK11hZtZ6fagX-j5J
AfK5A_Zp-8-VZgnmRuygta6PGqbTeSQB9zLGY5EeXe9V3D_F7kk0SrFk2hdfK1Owt_IpOICKvlJWA72JjPU1VgzuFMDNA0VQ8ql9kEbNQL9TJ856SgE2CuQz
jGqGQ2Lq1z6ADhgEPN5btFIB5AhheQsVcpIflZaRmlZ7keq1wW47GB9XGXt391IWOwVcxzD3-s4Xj1kZYEnY00LpA2U62N5qq6mA9vT5F92rgpaqPqCWXRSv
g3ofWB9eK0XHnb1TBxlsTb9wkBf23WVIGtEkRimA8fz7W08vo045FIbK5nioy4YkTWMa1rFWXK06iuBeEul1Lx2ok2g6JjHhwWa5cKDrLz3ZUtzmYe4Ly7mI
WHNme2pe8rih2r5xHS5b8TPD7RzvGyVl95ZXzGvV8d-Y89NAGWyeN1ogZ_krDogBClUK_ZoU5KG_j0vOeOP3g2ogZTuuFTYChSHfKaqA79STXPSvgFovGWYd
aeD66xq9XMg-zcQJwiOAyuRWAuX-VMWXi4A8XSlYXC91eLeFKxXeKdsI0eh1KU17ts_02bVuVb9b1_l8DWfDgajNEC1ca-eC1JeTNGLsUBi1A-39l3r8j652
uVHWzxyfL4E1Yi5LME-WyhSAy_QWvuMXK-9G3GNDDAc-KU_eABo8GMI1GZWQXseeXAGKggKhn526z72Z3S5NMEyWiaOXcOAjT4bG40xLkIiSRRmLfU8Ok0eY
zKq6lWA7QiNGQGhLKBZkePfUKleAYzU3od85TcZHXauwXceC6UZhiHKA8kzQ2Bu2zvfGA1IgDTcefVB4pVzeIDOwgBnAWKzD6pf56L_WbDmLShmS1SgLJppv
JGl1Ls07Uq5D8pcwwVTiDUWp3hgWTrof00VDPrU8IJXKiuB_1HrAOarPYBnUGIbKGo54fKbrzHNu1Y0K5go7AWiUJw6cYtlk10KjTFq32fu1pb9NuVbUKrOy
gev2c6OFMhg2pA7QLRYf85oJWlkyMW4EZWAQ2vG5tGwcKArFVZq6XUqSF8KG2uNgcg1GE5JVV8D9OSdsK1SvP4S1iuTXUy3GoTB3ps_e-0OW55OwB6AeXwFm
o-n1RVGsXkeVJaSGaSAwij153YKw2Y6KALH38MUKXVFrs5ygoFKMXzDJY5EOL1uwgROVJaTVmN_q7Gur-mhiK2CKjASAPqDm57OvBQxaAr1PqF-bxdyznWhh
7RuMEPJiAh13WmAzeME3fGhwbjD2r5UOou8KvgZeA2ml2rqM9dq53jMi00ESdEiLHBxUu-0hS5cmWl_1Z0ezYzV3zM-xPeAiI0p3K7OITQfz_zFEFfgrot_H
5m7pZl3AigE6hW6fXMlxmqCxqCB6THHOi5zD8B5m_hjhyaPm8GWiJD0r4mliclpxnqZ2eBNGuV6GMTZjht_4OkGEQ463fMiYiV1Nr-HJqM31kXxQVjl2lrsJ
Ws2pqCCIYtPABEps_1G5Eh1QiCIY7JSi4BwwwI1XG1Q87CXAbjJ26ChbQFHmtkiiZCKs2Fhr8B8m5lqWM6EXiB30F0Uagppa5lmBmUy1U9U5OHW4ZuV4mfmE
zEi1RxGmL0vEyIuwHB5uWuK1aOGM2RPv05vcGH-69HIiNGEsB1XU20e0aOVCWduXX98kufHRy5y6VopQ8R6W3OCUvU_SsnR6164mTSrj2_xkIFnTSyE2OI4e
QBAk-JyBweKmluVBcHRKtN4D0UwkERHX21UGUXYJNKT_r_nXmH26sJqCmoVs-TU38mppUp0uc3uMmeLGtaFScE8EoDF1xME1c8RY3aXj1sJrErXZGeeF0Ydk
W3mTsAucMamFZ8DGDnPnBvpwXz7YZe0X35Kzn1rIUmx8MdiEI4VfGI2eFGZ4ycLrVY08GtKFyK2Wj0FI8Fw_PfNN0-8XgH6679HsG5fj2GG21mKy88hmb92i
XoX5SGSawOv5FKHLbauGXKd2KCa346O-0m
}

