sprite $image26 [252x301/16z] {
vCyv0S10402XcchzkusAt3SuO1Q1IGBepj6TGxYExXowSuJhwCwXEuVk7E4wkdFepg4xHxYExXowSuJhwCwXEuVk7E4wkdFepY5Sfpk7xXowSmZNwSwXEuVk
7E4wkdFepY5Sfpk7xXowSmZNwSwXEuTmdUuSkdFepY5Sfpk7xXp2TNJdwCwXEuTm7TqvkdFepY5Sfpk7xlnZnqwt7DLX800xUwWg-VqVzpAjCtHmheT9Jy8Y
ex-eb-y8-nHwHK-qgoU1Ll4acnqzsQwUR5VFXl5aktgoNJtPhfuDuyb6zQMzwz2ClhG3ZW-fdxG3xOo-jBUXhziH_zAhsqNww2Fg9-qjlFXrExhe-hezk7xA
3eJ6r-tnzLDsAhB-JtPQN-eGLC-wdRAl2ZfwI2Lzi9_JyUvu8fuUKjr-ItsT70_qQWRIW_gJ_PBIyP8klmSFac7qbARi9qkf-sMNsu4GU4WJzflRZoDxv_eO
yhgzStlIO0yHygbfEt1n-_txl6y_wBbysjuTZh_iLpDXi6zQ3-alxRYdGs-7W95zgoy-gB-tepkcT2IUx2IsfwVqYXtexa1Xzv3FZU4XlMe7dknR3FcGtc2_
dCwTuxcTOq-zmUuX_-9u08udDYX_tNv9wN1ALnyyG77jU4ZlidlOWvzuK2k_yI6zpNvr-_d1lkPZJxtFFeJyHplWU61BGt_TZfFRCPptrSPSI6-sT-aejmk3
VOLwK6-tu_OTyjs-of1FwPrs-MFS3nxo2pj5h0KFwJDsu7O32ZizxQnYz90-PmSAEsLUx9RNK_FPFV3uu0KihASqfxrBlyhn100kXeVqhtQ-PB_ryhllD4tU
k8mUr19sE_dNdS7jmFnwIhFRuVQa1_lyNxUGbh2Vt7vxiCyTz20jOx-v_V9mte5PzTHITfmJUllPZ1ZiCyPSIilPUtbVDm4Z-pnVjv0MjUDoI4VWoIxnmwC7
jR3TgxJhyo6VqXhjDFFwtB67j4hxQTXb2oZmSyhdj_iY_-Xuu1DwQgtsIo-_ETw4xvIF-UNpstsXUtNxxyvtwI6js7vt-s5axnm_htn-Emx3CllR_XuzjNRx
rUrNCwDtlYVcGbgz7SU3tCvnf-E9-UJpsxjZweigEl_bnGUr3JkwSqhdfqxzFEPIMh-ztgcVxx8XRTb-krv_u-5uO0xvydRFkVSlkruyzjIcxPxrKkfyyA_S
-9G2sAz8gSZuatf8OUoNHpimWGSLmNvtUnhP9uuzfH1s7DqE-zxe_ZdcGefYlmrsZNvb1zTNv27ikAJpbvtbh-puZAT2sN7fwKS-_qgAXPvIC3kwowL3rJxe
8OMpUzNjheVKg9rKO_OFqtVxRj_jktstx_RTljkfXkqvgs5xpcpOdgrHknURiU_stRxRirgoxtPOi_PXyjQa7L1nrp6h6JjWXJrdDcC7KTYpDMD7QUzB3Tip
mzftkwbPEyrKjLjiEsG6yF_jMR7ja43J3-pOldtquiiVypDshimk0b1XzvYRoT1scX60-4IoufvdPZ0xp5GXqGfxDiQoomoeaiebXqBPGRvWTtqOE_2IFGUt
aytQQSPMxJ1JtQxOTfc1gYwpGzj1WcPipbvc_A5HJTY_r2hjS3tutKZ5iWyZVsu4RNpFCnlZtNKr4GjxpXRBJcbadrXgAdIchTkzMhOpjbrgrswcQJjZscN6
gZqpj1qombInAxOT1CmqRcp3FeIUSQDQiCj3Vca7hBphn7XsgpGoPppQBLimEyrOQrHXprcRjADY1uMQ7QMzBqQo0o_PiqMrxtOP6xPRtPvZssb6a1Lx3cq7
vVxsx5vc6jlLX5toq3Es0zQ0tKTEbNQmYNkU_vLtdplFwa0GnuVcWDTexlzkZs2aMEVnsv8OME9_olUVQ9lggB9TfM-tnrJQdvaNEm-nPw3dz-l88-pAlvri
sKusR9U-jAUKx0nxkjGklFsFPEjMQi2UzI8jowfI2tRfyz9e2C9R4tRIL8nzNl8xrR6dDJcs2oyxW6M4jlnlxVQQVJM_TlNSxZ40QRDR5Rlzi9j3k_IZx5eb
fOez9lzsuMVPkthRNJctIz_lTcpss8vTJPYctPvYStPYQv2yBRlmmsA5tLAoRxQNG_xJgr6l0RlqCTkNLLaBTkbbrzhFmhTXfwbO3FaDsFDX3s0Ue2tVWbq9
3mrxkzsQiKi_oFxmRAyl5_uX-_2oFVcpyxNCEkGX_zPsljw487kAJktrvUMGxznUdovyjzXFUrhNT1SxFybapdPRzyo_NV8QUZqlOLcLVpihP5kopm1wRVda
tSuwcOfn0Zf0UDzsrYj_Y15czBlT7DjPjnslvG0rvoQtTghA-8VidMixLNMzx4X-xJmg2x97h-Sw7XcwiDjJz6ZdeM7FvqpBmmFwnKhHkgPhxJmdCqaaadph
GZjFoxQUeZcOxEaoEzM9UeaU00RXhOBTkxpyjaul_1LsNb6sXu1H6_vyEtaXNdR4I-nKL-b7sRNU-RbsNflP0Ym1mEdRdTTd0sAGFSKJxVGGC8oxtU9vThge
_BQEFS57sUaeO8YMSNdGjKFiz9LjPRlamjUsK_dJopvt64tusdOgZthPUpo_hPEgskatKn50wA0jNzDEpsLx3FcD_4fsAkVwVhTZhccdSg-VP1_hsNcNBChU
LJlUUPzim9o_iFAndVSAw82Xobp7smK0IurvddSCc-vJE--QRNrYfxgl_cqxrRtrxzbv_qozQkTtz8QTtzEhTgelqfVs5kGKtWfx0_AiB-mDoAN_MJlqKb_A
sy4NyeRq1RqXVI5lID-UFEEpl3rzctJf9MyJVvxyFm
}

