sprite $image29 [244x174/16z] {
vDO5TKG134N1SZCV_RkjWZBlVGxc1CzlpW9dAe39YI4aRga70C1IA79B3K2bmHV4r5xEvCHmWUAMUhmrIwp8mEJ4a1F_V_KTOceVpv8Jmp-zJp4r09K61uHA
lQ2bleEMsZUa9yRnv-zJgTJGKaDBFSJG0osr7qnFZFapZsQer0Uqr7ujFJ6Mo2030B4Y0tfYB3an1CdeYQ4dnlp0VIgL6bfgVpmzCPR880C0iI83Uc8iEJ44
oUY9eIV6VEe-bKhjt-UfNFlGRIG7Om1y9TD-KfdtVzj5PiTBGp1bPxP9VtYt7Us3ICGIybanYUshgK72b3ljh07cK7-ks-0NApX97EhuEcgoa42IMR-_R2va
tbbxCv5rrjvSyixQcrFD-krrSq7QMNjpvbbxCqba_JZgpGN8edxTJ3BjhBsva6bdxSs5QGgEXfcKENV1lRaaLRVD9Ul7KO3Up3opZdjp8MZCMGkEKW2pP-Qx
PSeCq9kPQzOo0ywSx_58PhJCHAPPompGcWjBdbaVPiMQKnNyC2l6dEaP9L2P0NfpYbc3b5bgPqxmU1JaGpFepNf66LPyceagDEQX2nxWQIRFawlos5p6lLk3
jm2tdsgrEsSLd0EXWyf-DbLenPZ7kcMgrZBlBRKxPtAeWeEip7i0C0NtPjsjHn7BV0H-rZAxWZD6679jRXKyG7lE_SywG6lswcKEQ-x-yGXaqxopdZM_c-S5
V62k2ewEQ-tDEcfAWYKOymhQSzOjitUnp4QDZv0VPiQqmPkxL0VuabbgWBTkpol9TMlShNjyF9AuRHOQ94u4vccEm_pYtRhFMdkpr3gvUPsdPTbUlbiZkggr
Dtirvk0sJLlrJbXAjtTha5VC-ZYA3pCnRwFShOEyQjPHBmjvx3daTcQfer-np5wzhATvYeS5BzqKFC2hvbeTopf_cDSmT-jE2YxnTRE-RcspplapT-j-QktD
lk2XSxu_QcFMur4_jVPchzOvAxHctJBxgRKtUtK4KCUQLV3eHkpDVjQFqZ0NdEe-XkpDNasZzcOIAdW7GpRcYsfnQxFK7TJQc7tURS7PDf-pxg3Mrkn3TzGD
S-4FTGTYOxvMS5fpmUyfU81_mjnMM_DlAVWV42lXPktDlruT_7Fazb4tp5B7IBL-hcRJh5aFLEldQczs1U-_rizdtJPBFPxO7xKtcrbtDEJhwgPvYz2iXndo
StLb9kuJMvXPTrXhZmPfpJniK8ZjNZrIhTj7BNEfr0mmjWqg-02rzcfZlgcb1434fzHWLsIfxPie0H9QCGjFjMRTxP1zMAafimgkgpP1CgGUPSZjWijS5Lnc
yfM2zoVswjhCsx-Uvi9NPXsy6lm1iHwFtDktPasSvc9ctUkG_L4Ry_si3ovB0QbUn313zkgRj2wuzbuL0z7_aBtQc4lzlTEap2funxNsQF0qr6RD-eCNA8Sv
LaZTUQszMfFs1IUsuE7V9cnInr1YHUPcmMFR3lFREYrIT_trwRdweLbg4YImpl4MsnpVpMMqGrRQvWBW9WS2Rziopn4o3oLMccPgrXzPLyph_zCICWybLa0u
izHdbcdw7zWkcSlUKq2oNN3yI4pRjMxloWW59-uphp8FAdvUy5gzXSmZaXMWMN3YFYmZYvLuycrLnZoiMBFsPjAO1nLBtJ0NKEOKPAcjcQJCESIQjJUJCYSG
suAp-kary_imNgczcJBdE6IflPbaoIDMY8QviAGJwwWlcB6F7E22UHyyxx3cZ6BDsfZpYNt1lRdiUGBY5VEUA-1JyvukX34RSSg2bznagOrvJvm0PJRYp0Kl
8gSF87DQiNzHa3X_21pcz_qh1M0f-s_EDm
}

