sprite $image108 [239x173/16z] {
v9S5biH020N7X_zRvlwdNO-i4mzGDwXN9D2FBI1UUCJWWWyOmHOTT2zCeW-ZfFKlND4GGHY_ub6M-1qwJkk_C1I85za47JusBVJuk1Z326CmucAE_GTE64kK
j0rXP1kI9Ld1T6gKiWsnR04_crO46kYZhBoYyhquIDi03JvazRvYU8xb2p1PkEfjHmaRdcFhWJb5LfYXmuCiKj7gWkRdE9MYrmLComfpQNGj27EoRAShshlI
QDfKIgSxQ2dPacr8RTq9MzYARFEZAfd3jp0jVRGTp3cDkokJhRGD67rdMPDjc21iK7RNXpGdo5eBNFLfLnEk1kROm4JVrvQLbA7YlhEqz-j_t7uygVD63uSB
E2NjzV0Vfszpd8UybOZBTaVKT5sat7yhgOptSp4-ysedIewpEXI0xv641D8ix_-sjqo7CdzY4etRRTKs-_HdT00vtRcwgjAvgz4m_mRURmtj9svTbGtkmMXu
ynlf_4bx5NUCXcDMkXFiMUoLt34QnhsdSBwDB-KESBltsk77DhEQr-QvLzwp_BAbDLLLosBpNDnuaSulhJxATkpTt1yuXQCjrtPK_O0rUyCrKtlBDRkjezU7
ZqVRlVOMAs1RS4qP0AZOaciC-JwudWxju8PNJOWBDe7O4RVGk3X2x91hqd-tt37yUtlBZN3x29RXAVR4jOxTI-oLQ-EFa5xRqVdG3cwlES9cXwqyEAGsSut7
Wm0UVw3OCxSgZR_E-eRhBLMfFbvpEtYnm4TViUtSyZ1o4IaoVcAlsIsO-kEu_5UqxtczPRaHDGyM--8QZvzpb-W31JdOcIVmwjEqQDbQOFFSvmYRy4lzRnHA
v-BHtgFLOIPxYlcfzeoJ7dxOqhbdxvMrjHJNLKfxZR1soxAmowtQ-5dfFP0eiQDvALf-p_AQNzgPMm50NpjQKbytsTRcusSyThMF1JqQ_Vzfp_A37Ih5PO9u
zF8TN0G_neNOyzh-yltdsH3FVPpdUcEKWmWNNYhvi9absSoipo_jViMfFSj77-Tgup4qd53Zu50gQdl9H9otAZC-sAfW_otbzKvLlUto7k9qZKRESgC26WKb
tXzAIbCZ7Xv4zEOWClbqy8uDUd3JX7zSNLUWD96Oof_1odCZZck63PyKOHcR6vi-SMr-Lf-_ro7FRTu5UMv8SGEAj-vSdCATDQw8EtTQSoACrNkzCtFc3ka3
c-TkBw_x5vldAYGgGVfZci5jyfOl5UHr8jBF8q8jz752Q3ispUqFA28Fxj65HmCibAYqM4IuKAUySgjz7W2h2Jw4TjR-yXos_vtHZPxZHa7nK90J06xB28lM
rNXV6DlYoNgyhreiqSST6vx1ZWSKaGCFhZEaLi00KwBHq0VtIdltyiOiyQxgAkpK3H5vy1U9iLNVe0qbOWasoxsQqpHtX7PKU3gqCtUK9xZXXG1g0AWGUNZp
vQ5qZfiERRgFPsvwWGUhQQd1C05GdK1zPb0_EfGIt9BbdW_jpCs3FVOoQ5I6Ae0-Cn0Mu8kuRO5Dzl7EpODz1xl0lAe9k1QKZGisFtYxOsbkle_ps3LtL6w1
6u59N3Qge6vSGDfHXB_FZNDzdE2cEze5eAORjqA2K8n1xU1UMP3XNX_Q53VVqSrQbqOq3OA65x0V74hRpO9MXS6zBhG-7b22c-XeZxtuiQ04Rk503Qq3h8dX
lnVoeSqlRPwRZt1KS5DfGG2f4pG4Td0A2xyfkRgF4zoJXv8100U16K3dwc8qh8cw59ldvYDS6UZPTUqTBT34HJfrYVhsIPldvYFijSR6xPtjdJjNFUUzBBHv
RZx2GVrkLVPcNbsax-_ZF3SVOIMGke8wjshrY6I4hpzyyjppfx00JC36TGAahcVX6swCMUxvKxWoyE2MJMxh25k-ZxEXlOoRlrUQiFLczkREgCi8snsXpNFF
JqgnSHkpDeD4hrQUHyCMopu-E-RbkPTsTETM022mkvP-h_RvNcd--zU5Xq-2cU6UZx1MK5C6UG6W1lOfmjks--kkqEQvvoFipcXHGKu0GsPkHCVS5zeyzto4
3MobSzKBC7D_3UuYjESFdppt-euce7DhX7pcPh7vqEQv5rsa5UI2sfVQlTOsS-_kuppt_BrIt52-1eS2a4tS6swC2UxbUnPH2mCt0W6wSsy8RO9x-Ibi81Dm
9TJUsOExE6az6TgRkNcm4j2vP0qySy-7zdvklgER5d1Z49ZG1lU23xXErD-u0Uo5lQ1M1cnmxmtjqFvDU2_eQ8y6SLSgWzlkxUEX_M5mn2Y5LBKwkBSTFZjs
r2qT7GK03UxzVJpNhml0YKc9n3lt13OkrDuKOMyUJzp_DsSNk144CH15nI5hv_wtZIWe25Zx-li6JwuQw4QbVH-Sw6_S5vrZ3nvUseLtN-5vn_eS7wZmd2oj
J_J876-zU_3yUhMpqiulhA32iyZn7kih_AiSRqlxjxdTRy61qhf4wo_6ty_p4Xp3-WgBqcvcjed6fPs55O3joySdsfVMW-tBPp-FsqG7Laihp4gRJBJ7Ud3e
vUC_f7rf_NSbm8OJ_VmSm8BJ7N1SqG47Scm_f06sL65GsXGObBO41fijUO6s1EPO3zvpNwxZ0xbNOX3tTbK6S0FA1HXeIrw0BO51QKjWjjd6OGVuF2w1mMfB
YGRO4XZak0G6gorv3JPpd0NUjAKDWzMMm01RyW9i2Hnu-SXRGx3QqeO1jlGX3R2b1GDjgS80Mzemm9QyuELJ0WDi2GnoNF82R0aCj2Nm8Umh
}

