sprite $image141 [238x154/16z] {
vDQ5LG1140HHdErQtbx-qU8mk7DMbS5_FIVJJ06CoH7tMQmMR-DPKGnRDOMrSbWh5HOmMG6J5SZUh8fzmrVh8YiGmH7lv9mRtoyOZfYg2Ovuo-Sy08qNmE8D
Vz7OqgwAUNluks8uuYe8h5lu-YRyIwl4yd-Ph41JMAjrMItU0MYyp5ZRp1Ts-pzNZVbJ775riQHLCMy7D5uMBWvhPR82RJwhOjx1caeSmrOpM0NSWCRBYejZ
r-gFTxLm1w3nXgqKnH5JgR3Wi5OcAn2H5SZuflM4RUSOjX9Pl-xjxAIqh_ucEkPbRvcim51ftv-tTvEtq_5uhxerq-L8LXq8fuHO9S_xF-wDWkfH-1A7io-8
6Tk_lwZyMYAhDKbKNjrfbObALDwTbZapj-3wEYsGCgKU5BV_FoqpYI27ZhFJ5bCYILH2nzbfRJ0Ywzk_qzhedPB4rNVyfCrgDimQGOJ2wjicBQ7gU6YjPc59
LCFgksZDj9fPDojBtx3JQD7Q6FhGMg57txZB926DwUsOr6OP8iWXuwmgGDBbxQ9M0UM8-gfzgJO6A4zlLVlpboK5rDU-lhwUwtmX8DlqjgfPpsQ2Hz-kWLYV
i-eB0KIMjqCVMfEvJEQXKKByqaxUdW2KvMsPiTQHIDZrlPvrqIvShGIqtisiYPhrjJn7k0ikLgTTSIu0g9krOaCVx54BNpzzrLcTzgClwKDhLjRot06_2zuS
OgTrtiu0KLdUFhJM4dDsVMyDiTFwiQKlDRFkotD54gIkrxCwhSSv0zH7VqZVvRbI5eOClJR4Ewt7MG3mydOqCrCISFOczbPMf_MZQvbaMzwEHGk8u9ugnrcF
j3vzENsMvq62rZD9SdtlcJfdMjSNQItF3O9X9k3Co4Dl2_6PrfV9NEVol6Wj2wT7NzLhGdoczVDZwOkwQDkQHlpgUoNhb_qYhI_FaxQFIQi9b5tVAuJTd-nH
Nvf9rZc3XmvoVIyHzipgSLxwljxMTtSc925V9Yy8yGbsdxwC_bxrvmokXLpV2An-tYgdFxHUF8CaGRg62F6kB-Mol7sBP_ZqZSJg-h8NprRhQEJw1WZnTXTC
OwpTMQrMimgVlXTEdNESjG2GjJkFF1zm4Sf-5xmzn7wyYLsxSywVzoYSoVMzO7NwhMTCVPbdRzN6UfzI-DNtOc7FosHvQD-h_Z0LI09tZH7YVVgMAkszwe-r
FBk-SLXTNvJrN5Vnt1jxbNDxY7TzUU9-MvuviUjxuzGvwvjaUJicTUS4yIOsG8Ytks3rvRbn0YYdlr_VVvZLzQNQvlCTEcab9yw4eXf0s4tVnhuy5qwePWb9
G4tl5VQiBwyjeovQ5V8czb9Xp_gIEAqDLVRfUy6Q-0VkWWyju_CQbC7Yq_T6OSzLJih2ZFwfSbgbv7V1kqEyynO29gs_1eNh6uVLzML6MnNiUfqYoQkS027U
NwHGVwUHpRy5ANkLSzVKEHzRJMplqrjTKobxbHCYnBk-IQUtOwOvrUnDx9LJvwollmOTPYsRPRY-LmkxuqvzYVDxzwrvLZdiLKw046_J5zcMjpAnJLpVGAok
RoxDpAhuLvx5xuBtXtYlSgfPBUzxq3wwJzzBfywvYKNNKjugfy_bsVKD4EAzYKKnVmywIYOHSDT8hAwlLpcVon5OuFhUAUovofdUlijL9m60ClHQOS_J5zIz
gXkB5bJr3uJunt-NrVNbvMqVEcdNILs3X7YlSjBqLaV_IUlwXc3rAcU8VqVKQG5HrMi_YSzDB4lnJwbrI1qt2Alh2vcqXV4vEiyVkDTTeM_fZIH9PgTTvtfX
zpYF180avIH2tsWj5gjNEIHPaYJUQ2E4UByBagGiaduRxQsahY-9VCnLDJEdZSJgooH_aZmvJVMm9jxFsvWVsa9E6q3OSnCBWjD6PVNfcsboEcq0OGzLZjF6
4tRNjymagshS1-kyVZRMqBmRQsZSxPCuDE_sO4FpRgoXUVyvrly1
}

