sprite $image343 [223x285/16z] {
xDW9RkGm34JH8TcIBBfz_-DEzZsLNR7ouNU30YXym_y0k0w7m-7WIpzXnrdDIuiprvMUDvhnnaNF1uLsbosVO3t1aa-mdk2fvskgCMAGGY-866WzK7V9UeAn
vFkg4MAWzGA80Ui9Hi_FQ8w8WLR_phgQajPFY1XeIo3kKck6Y85M837GJn0H0srnn5rgpH0nq0ea1le9pXi3r1EqccDKc-FtvJ054GEjnqmnO3t1ah-X6YC6
EXA866XB86AWDKFSfLRt-ds9UeBMSYTh06AWhESj9lX86UIyRLi0Og363PzNTxpBQm68WHXt9Q1tUIjuCTWU2LuCn3n834RFypR1k5j1Yy5JGOl1Ky69mUXv
LYU8mR1vPSUxL9mG0yq97ocQ4pvID2V4G7D030REina-KZG7tEMeUJ79NMfEY87cX1XeJlX8qPmG0yq8CT2C40FD27Uf6I46cX5Ye1aX1fhDT9TwtFXvPPtW
BWVDYrRAkbwqToVApU90483D3PgUzt_SFH9tbSaGoehIM5Pbzd9kla93IuZiRw_1QNbS6PXT3oHEo1kPT9Vxp5tEsnBhOg31B-0HT3MGE3tFqkL0Sx-E1nFu
bEEITNkAHv0UIDorl2j7QC29UPS2pVrLF0IWRbnUpzEt874luEb7gBc_dXU1wd6fv-c1nBs89sX1ESwHmTEreC5huo40XJWzJzQ2n5N7YpuJX86SfmCQ_DMy
pVA0Wd4fuj4d01Bt-hENaY7FPu9nAUozbCmoWGASY4TV7b0mBcKy5005OI08XbyReGQlaMU9G2kPfn5N6Q-u1OchbmVB2Oa8D7YjFA2a1Ochb-TtOCe7SbnM
pNC2VzA2TXK8F-SvSbkGFbn2MyVkTkjNTvRbyF0mC3D20du9poOUyVmJ7WyuCoGCVWKlZO-hW0nUF1s69u6yeCXvzebZZTaydesiCqYMc8Vvjgy-bvSFf4xF
MyCMRFT37YpwNinB_PqqBUjKn2E8G8IGk9p7fXiskBjlzxVoUVaZLCzZq_NR_b61kO0NWFHTpji-CTtwzTSHKndFdcX1EIyDzn37rmSzUY_ZHI02KCp3T8yu
SsUHivRopbjGpyFIiUbsDN-y4yvAF-VXf0N5lEqU1Wk-g3jsNW7ll0KXvp4Cfl1DfuztUpcFbM8BYdaCWo75aygXMS0Bm3ZJLlBM40PxIsTUmCjeGGKFHs50
IlU_Bda1BwC5DRpx9SLZRJVg2dWvBKWUeETXfax0Esn1yYoPd6SVWxOtL_6E9w9mf9GWvc7vUEy85_AEWIcPklUsdk-KyQAFGBYKnv3lrcqpQ7cmFOyi7OyX
pnLxKl5Ob_BYRPR1Cdd8z5t3uuelrW8HZtK9Zok-M8DfUJ0z3mlxRPod_hiJk0buB2MFAxunSNyXdC3tvKrZM1JP44xWc_9OtNPsitgkbcUZFS4BYoAC3_JL
A-LXvfBxZ3VQoMu3wK_mEYifp-NXyn2dSrwVlZllfDV9Ixp6RsUy2VvThQJNn8k7qrdcQfq5UBMyyI6waCjZrSdZqNUyF3J7MpwwZZyvjSJZzjNe0tyoskBP
vw7RZTdM48_xEtR_BnbjyBY_q_C5sw-8jrR4s-9Ck4SZF8PUskVVr0mFV29bDppN9dWClJaSbpN2wudP3yy1RyYpuz0Rd6KT3s1-EruQnkFGMuwER7il7gOm
8U7514V_l_CERyFZ8obZ33s-Dzxw6hxorafvT4JU-30CmotePSSRahyNZw67XpEyAuB0Us1ry_fq57hJVZ-oMswi3kJDyDfvtNeSUebtktWpZpwUROTvLYql
uCtVx87tZ_kHe_7g6QucLVFulkFGM_caNtXWqTw3nugXPzoFx1R4urlUY6Th3Bs1OJ25S6SOl0SFossCeNSCCUu5YNZzh_9utHyFbZd7a8KR8lNpEDaYBpRO
0MGnTo5FFslf6Mu5a7fvAMngDSMRk9tQ98-FhpV9unpR9JM_cCVGczlaCVJiBNdmSnxRO_0cUGozfKqUGm-jyYQ-rI2FeRUsobivDXlaCVGcRvHdt4HeaCVG
wz0gh-U4h44UGo-rofjuwwX97ZgkObKrlPAtyXvOepnpRvMdAZtlZxUqp1lCQ-4DlytZFa9BF7VMjk0g7ERRPRphQ-jk-JpWBNZSwStcEL0_3-owV9xNomkF
_UJpa5AgbyVjtv_oB7rKdJm-zbF00u42dY8CyeE1mFfuQsow_62WJy0JX45kCDW340AU80ooUI2m0Xx3e9H7rcCBri1Z69JpY48OeGAU90pEUKI54IhW2S8W
DnY2xr9U38FoO20gM3Du-Z0eMZ745dm5pmx2e3mOy4mBwdbOIcJ7FDkXGaXayDHXKBvYY2s8gtYsQpf1C1o_rlCO1Y8UZjkEG3KlXe4c62AAhw7bfLtJ2O8X
-498Q7YSWIbvpxOWUJ0JX8685zlk64WUpCn4zsRBQzpXGjgTlmPFjM06fk359T7fQt0E85YEQtZuljKGNzChM8wBU0Z0qv18S3SJX868vuu0-Tvg30P166Xu
22qOHoZV3mQ3O0QcuLb47OT428RI6PYUTugAFZW-toK80sKmHDHnI30O164WuvrFE6Cmk9dWbu1KmN2o9C99C0YMumgUFxSa2i4W20FDsKlFhXXW_2Cb1M4W
uXrFCi-30PM4GQm-FHKCCIGO34PU5M4GQovP4f5PJHZ4wfQO38ISBudu9agMu_hgjxFaEmy9E7a5OQ2kyQaMZ72uaoS80rKBFhaaue81cZ3Gj-3vaWZk09cw
CD2tuF481Opv9rYEQrimegBlVaC9WgRJrFHqIB10dY8Cz2rulYIoSEMKtvlLjw25O91krEbJy7X9n63Gpi3qBNYOx24OX66WRy48X1jN388mq5Q_dctQXc0G
X86uXjCM3C6Wde7fMp2617ZbL3UTlWNZ23K6Wtuvhc_1c88X6FHXe6_160o2ZReQMX16fd8vhg_v6CXW48U1lhhrmCTJ27aOw6lO8f31e0s3wrim18C-3Avl
GRYJfmw3wrkGl6r3M8utq8BaBRUnRm0M5xlaDLPpiposOCiytcz2c8KrrO88QTTM2wRnrd1rBUDOV_LNV_LN_m8
}

sprite $image343 [112x143/16z] {
xTY9qgow3GHWiHfRtRp_uwPWK34volWV_GQIt7jrzlKhrBIBGVudvvyPXYUrFfKoTqzftLosoTCpt9ZBCNbu8BYbl4tgdrZbEJV7EENY9a_thjBFCjpKWO-J
-hk32ySOxq1zydZXAbrmWHYRLnc9iRq3uHZREn2FiRq3yHZZmGLYREf0VAQkfGFnGNfabJPWQkX0T9ICUSFIee44KwW33GCovasDMimRcu83OrwVcZNp7kW0
dNVtAcsmfjix4FAwrWu4lDOEA1dpseFptdnV1o9UUmS2NlCgoQ3Ns86Oryz9jMML8Q-RjrMgQiCg8zw4urzgmof3dke1QeCMyNudcXRtLA7HfIhOu2a2ecaj
deQM2hBPUr-gHZiGzxvUge9DtWWz1-f4hxLvVL4JVuuHPD2R_3wBmiHwZ0fUuQcQw68CQ05ljtwA4UHLtdv5MerHen28cWVKbge8QZzT7w4VOrJ4DKr3Fu44
lOVZbjJ_l5Gb4DLUBticueDd8S6B886GXjGTpIO_UNY9wcDao0Evz293IbtDErl-PpU0W0UoZ29Z8RTpRAnv2YS6FP2OHFfC0fn5bW_vkSxPKYCUi0VN9H0W
sKjFikgPQ9U8sFNbNcHI4iV7eaBKFHzZmDDHP2WyJfKYaWZ-vFaO0VAhvxxjFZaqCXzStVCngeBGRpoEUxzt3RDn1CUwvsDK8E1Xpx7FAuclFGKE4Afan6FP
WAuV4eYwvqM5AY8UCOjDbqbywLdZwnwSjvrYmsplT2Umxdcnui5Ttp2ypZ9YFYynu6dLMpNXtpqxoq2MmNvvbOVKoKIyUUTPHf2pT8d4LHxs2rY8z_pMDvz5
L-8Y3ypIRG4fyKSVRC0FVPX_vKqopI8oa1yy-_ab7j79WcxxryG7ZzTvu2AYwxBzyqpSvU7q1XcER3eGDryVg2BBwmUHyRPzBid2cgN3iLQHHDpXwIYZtVsz
J0J8BDkKesSRx6RudGSckncnCVbuXDYc1x4EVIPvgPTWvTk9UJiWq_7WpW9UwP6bh6Vvqhfq8WdaUQxXMe-h5bhvbi6U_LH4nkAqTWzBDn6lyeaz-n5CBhXh
ybliWQXiBLzeLmIGkC5BvitRltatGDxd4RqCgpFkyi1yt8vFUPDq89_og9sCn7FU8fAVz0RfGJxbiUpgSzuievAFUHWNXWPzYxS2VD1B976lXzFh2wC3yfSU
gM1SAuDyyW2Wvf68QZePuZr0YwBYXSPUDucVP4WfHHNNU7YzRgfvm2u2xPwzfgXxgeVOvjaRdnyyw8lQbzhW0UJIITqx0xIbUY_UWRe7m8dcjNR0UzO74rKH
za3NWMeVB41Z4VBiNRcVUX_UluTv3S5L--1548fltvK7F0ljFK1RAhxeW0KNkRvI_2MMh43my0hqmOjWtODzq8rvWBUsxqae0eTN93-B3ZXNgqKLuGx4-s3V
vm8Wq876FgYIYihX5PuPE-YjUXy0ExoYCsJ0-k2-jpuqTC3Ff8TOwKD31_nqIV7XbY6WQEs0dtwnfVxH2YqAk0wuu5fYz6Tse0E1cGhWbWf24UX0PBhPnMXz
27SW7gF2pZY4En2FqIvHGQ3o4Di-eyLuzY7GWOOOzUn3e0DDCTezokmwS4UCW890uF1gZf7KUPP7PeyHX3mrVGB8BC_Da0ETUtB-cNy1
}

