sprite $image251 [146x109/16z] {
pPa9ZkCw34GbhpAf8FU_xVyPCouxbBeQWQ0siQiDy85LN2Rp_3ws_-DvezZsk1MGnNru4FS1Gjm6274V7iHjW13v-jNV0sd--EYFUIJdx3xwsmA1gAUvwWNw
5yLl_aYnFSXSwAcOHUsRxWKwGhTQt0O8qLSn2zb-ZFiK2D6_G1sO252zG6iLgOTYla1B264XJ5qLcyASnX19dJfQUWWlbZM6CH6cFegb6DEXtSIGsYkcpj8X
dkMBn4xD2wJYWCPBmSOm43krBH03CZiHf5P328eXKYdxJEpKJh6d598xsp0xDHn2HTmr5csp3c6eJe9M1Qfye7FPDakiIzS4gFw9obJEFOKm4wR6Ye4f3UK5
GXPBEyNcrJ6jSKX5EzKNIxi2fHXy6f4vJ6tin86UxkvunUJjDDOcGVrEQQ7O62oGXjc9t2bVAeODWK0MsCdqz8kbckhh0a4oYq5ryqWLEyLvgySNG8XNnZtc
_93oT1hy0ecWBCQNYYtfbL1bUW5jZnreB5WysM9XG0ZvrjBJluIQXZ4_CcpbBRwOdOXao4aA121dQMEo0arXZxZ-i5ZMG814FvFn8OJS_uuCqIpxf8JDNPRD
xBG0jnpgxnokM2hrV0gds6GhBPPrcs8YWktvL8LR6h6SS-TZRup1OhI-ytTAd18ha14v9DBp4tBhaL3Ji5VjiJzEYvEE5WX4O290wzxpst397UQTQOrXqCTX
AsTnoWCYOwAAJUZvYDo7nLNN_50ewqvP9XY8m0HSJvI6OwUgwkEIEmphYyaiX0KySHXaz4Gg7xXQT7JSaoFt7gC9KrZ0T0Gv8eJKVl8uvyQKE-TU1BN40iw_
Av0dGfGLs-PpxgFdaJpgqVEgQpmMi787PO84nIwXCY9tFlLylEHUrdq1p-S5l8IH58WGESKI1iufzxk_biloDukhJBQ0JU-958WGEKjZu23ts-8gYvwNVnYJ
BM0z-pmkTI1EfCxILX11xbDogzfqwNd9WiVoKG04HYJkyC30GUvJSh4EyyruUPHAWHYH-iC3QSIb0NfX0MyouV7QTndXYPvd9gdj-Lanl4zfvBJSznWLkLLb
_zXy3iK8qRD296b0xemqRm-_RNNk-UMmz8GUNQqXB9G1LPWmS91xE98ZztJqbunH7szBOmUkziWKiwwIPvt91iuvDmQEfR4oMa6ixr8yxq38o1JJZ_yIhvH9
aFioSB3yuVmiU4IFKiKmbnMo_I1TFkL6GR3yyUgtyYXy2857p4YKoQKvUlwwWFtGM24O0LByjK849ZTm5lIyp7u1RyVHFS3IJ37yrH7La5GjUHIp5VwXZGMS
nkFkjKU44C70uuay4tf-mYqzxi_RWCC3Er3d_P404HuGrPYcP6ccQy_ZyC20U6Ionz3nuF6nYNx4Tc72yiUHeLdnY07nwmB1GANOyrRj9FfvuuwbmpUIIuWB
Xb0XJ1yzF-N20fwp_Wf86OyP2KWL9i6HaHwFKy-RRCJIu262mTf2fRCZOtYxTthlL6nbLY1k811n9ZioS7ZWw9xtHyIt1aASylyadQeA3ezBprSKumRYI6GI
PBqQsYOcKOmOY30HwMnA8zBc5pqtK4Ecpn9f9a3CG9o9Jm8StUPpX7wnCff8f_jH48cboStHcaac71u0-agm5fC0FxCZj2cFH-9s4beW1IVXQTPr2EKTtvT9
kM3Dc8XqK8okZ8vbKheoEZDn0_LbaWO6QhfOj861MfP9c86wCpKmKEF5GWtKlKpivkZFn6wE_aoz1UEJW7Ly_pAncwC_4-duxaogr43zoqHu-ZCnmVepiGBr
PmBFNP30SnSc0Dqaj27FVm
}

