sprite $image115 [398x285/16z] {
xPoBRiIs3aJr92bl4F__tzwRXP0uNIfmKmiUEtFwVhTxC1nHzdQz5A8Vh0WGxRGL1ReuFnzaKGNHGKnViBAU2OSKIZpe0a882QeWEaZH3eOF3YaS7pn9uVXW
C71riBpnVJ0NdR12G1STMQV2yZvvN17hCa1yC1WOEeWUWAq0K0P0FkW2m0TT0FYW2u3we0o0UF1K2n0F1WCW7hoh1V31N63u8A8TH1_CnQthd38wPTq9JxK0
uuedAMGTB6_yUSKXDR_DMTxqGHbEVT05c0-sDzwuOYwO3ygWZdV5ep0OK505VL364Bh0WXi6VJ0NOoW32QCBBDvP64ZG1HR28GK57xJI1uCnPE6RELZSDnVK
GHVqiUYTA3n9qGU7r10-zOOYC1XGi33eWxaOGndKmI4rP64ka33c0Wi6WpheOiWxPK31mg0Fvc88bWiIe8OKmNguHo275CSLXvH8ILa0RaiOZ5fo3FydbZ-g
Gr6GccBu9DO_w0F5HC_4bdIwZx_eGcgEmQNeN_81aOaKXjI_SzeD29bu3KMCJZHkx-Di4rucOYuYdpQoWd1l5pKdfoXIgQ8gwLED_9Ld7oTcedWzaN8LVPAS
qa3WVYwafEYfA2BQAKvfOB3SoOMJ2QSTofSYXUD6Lr8bZCZofImwfO63tQUz9OSDCMr-iqZ_Kw9J6bZSvrHRuxVJKqt_l9DAJccWKUwpUPSOKwxQsVf8TIiZ
Ap0taD4HqIrIucRn2rvftBC-59GSNgd-xXwxjdA-hBl9SCRLk3Ganx0bbGl7GnIPtkxZqf3ideilUbcYw4W9NqHnP3d4SiLffLSWZqkZ1WUGPxNtb55_c5FR
PAHSlZsTofVIiQW3T76a7qGbUJaN9xbGdPjUWkYNnlWUKRAZ0puVpIvP6dusiXkdV9tjl3N3zr6S7l224xtfbaK1s6lZ0ZusBV2phFBFq4J71R2FzWHTXwH1
QVpyRBOMKHpssi3tqSTE7SZQTvk8N-Uj0p-kfCJFGIGvoM1MPHrI0CRM7XiN6LTbSq6OXxFgft35WXsFjiKKdvetXRrxLjLqYVUeMyFtuQUW33QICdZWZhCD
sbuRpIvmlEfayHVoyG6vWriVxGMxp68UgrSSqIcCBSZrqJhmFlmS57bvEfYzAE5z3STS6ovsdKU1CQKKmmOPFf-DfKIWSMNxRE3NX-GmeWmBeyZtlx08d8xc
Wn-F55pgza_nPbDDmD_YREsoFfnyP1d49pcM0BUFzXCNk2pPakjeI6KPlJ67TNVLBgoZlzAMqaUJv-hMlD_PaX6gl6EEZR4FV4H7fzfXHzJKvnG2ujYOu0FW
UmTZ7rLniBqscbt4XryOpee1YMFZyl6ewRKjydLyj7tO5OTKVUsHLA5rj7OR7rA-kIX-P8e2q-wZexuCASTK4MmPz_4XsKj6Hp9wRzZoQ3VmiVFIe-QAxUBH
RTp7XtkWnSVQuz5jt7rSuTEMHxTnFn_kdJdwaEesRkF3_xQ7N658EJPO7wUuM1wEZHlNHyKUKewD-zP7BD0kF1lthOyio4Fg01iNUgyzLUXJhMFZnl70BWpF
1dsSTghrRTnqN64FATy6W0yEASV6YUEABheD-ZZdLElR0F31mkWq31qSKjq6X0-ww3O0V718EJREFEtIHRU140yEgMxZ71-y1l5j0FZWa79id5OV759Z6sRJ
uy4XvUD_Z6Vue0i_6ofgS-k3Gyfdy0dAl7ZGnNuRzbIXfihw-2-qnszOL-VJ4z4d4ySLNVWsrkNLHXKzhZxCEAHsidxm68L39_cW2vyV_cUJJoDpweEhjy_Q
iU_hdpq38dhOyj6CmTXbezEy-Z0xhZxeOf-DJfjT7tInquPV7zt8v775ml1jhCjBVKprmM3uDlpwQDm-TjyFJh6nldlrOLFgWovy6wVM1ml3j-7NX_NjOveF
5aPd7M3kvHMt3sT8pRR1-jZ_ZlCC6sVN1uUKRsEydDlXbrTcTB7VXhzzi3vwOKoruUFMXzaVhm-tCERRyEj3ZwuF3YdVnlxwE2uU75A-ZVtr8OVM1rtuDdpi
X_e07bVuGygtyVlw4FJwm7VXszYlmrHxGlxGwShQN1dBEc1_VLGr-ni-seAH2zR7_27rlZgSlNsOePwam8BXw-ZRnxthew6qz_xjO_Rt3EZ2Pt7heqrzCP6d
sZ7XhFfWOUolZncdNGwftsyVDh_EEQJslybWaxx5oGtZ5u-Y5EDhEFY5iQmES-f3JQtDZ0SBmwVusqUtSL4Vjg07OunN7yVPQ6Ot6rAsEioj3zy6lW_V1VwG
6jV7jZUEyM8yrVxsiiIUFtLCf_dWgNPC6-3i7wZZoW0UACttST3-OJpL7k1Z-hXYOVWq01-G9wctzHGU4FL15vttiGw0-W0PKgmFV1Ui3slmCl1zcF5KUzIu
Ke1u0ApUh0-0Dn1O7mY5SV_wO65WrGTaOTZw3TO72yDdEUkqoo7bC_loYgltlw5Crj6C6mPIF9gX5mPFkooCCJRxKIrMON1S8RrNYy_xb75blWyMnk_ZyNiV
ciJHmI6rY-NeHxKQYZEkUAhTnt9eVNGRnGO-siB2-1axj3uqnA8XLzkCFPvgptenKKEH77B9B_N1mjY9jUFgeqgpa4rBteuhs2_5t7_xi50aIqxMlc0mphWi
qQhDKbND8OYgEJBeOW-7Z2iJKMkMY-LOGqZIRPpYWgShqrAhMSqfv10bP-qsJf71-b39fPgMM49kJMgtSL9vipwinghDMecJUsFT0Ul3f2QnPZbRjq4Nnr-M
rDfsObMocjKivjh0_o86VftNgcs_ZvAqQPdK6-iVOZY1jEt6D9LihMVZ-FQc3tLiZ37BfMgtmLmS_gr1SssCCOsbsw2Cm_DXrlub8jt6uIwemzhlM6Que8zp
RD151yd6kX83iB7F1VEXijV6_DMRFcf8Cis67mooZ6s4a6sQ3Ty5UGniH4aXL9jeOtKWletqjfGGaaopiVeGtyRRMyiX99rXOnr37hwDjuV64FLu6-_hJv1t
nyRJXqHjDhGnAHZ4j_7sIDfgjh6D-J9usgrn-R9HGYZcsfZtF8byt_viQoD46TYOdmlwa1Zgbuso-AUhPMumIEjeJikNZRU79MSvNwO7WpewslulOrcUDZwq
I0onEZQckY3R3xka-BJnGQiX3ctCTy7bGsFeDfxe3Xlp2eC-96zjj1qsPhhWzY7MIhB_OCFM8-7sKK9OzjcO7moEAqt1V1idj3VpOJKlherJN71SMVlOECIn
SSwGulQXCSHFETt6YRbWVNGRgjfjd2Q3FgocJnlMRPpfWlNnn7eu5eHNrlXeq7esWCgRx-qkvmqfujZ0SK4T2r1XqCS250pMnmBaWlbOW5nGnm9K6FInGBWW
oyQ6hMT3GhUnGa1QMouduty
}

