sprite $image5 [118x88/16z] {
jPhfThCw34NbMJgMllT_tBi8RRnyXO6KTl_BnBO4Fb46-eIOSgcjCSiRvbPhoIdG7n1JgPiBW3Y0JT_ghxfJQUnrntAkET9ZOcuYJdYgtipXYRAmCzuqjn-A
Gsu2-J6GbZulimha6G2NZmfEeyn7G6gyxMH014VycJSsQNL1aoKuHW2fWIu8LL1f2KEEAMb54KYXKx90vCIAbJMk3zb5mEcaq0OHmUzQYyh6ijmea3-pWiEY
knlU6Xg_qPzQDn9v2kIBHZEHLRk-w2ih2tQwn9LLifDMZ2CSNTd2CW4M-9tJKGCjhIXUEbbzSimEAHIQE8RJMxssGBmrPhUffgExfRHuSbwzDaCEhDaupct-
WjF1Ki3J8ciziWeIZIqZHzQaG0jJMBuSTLuAlbjEWuH_F5lzrSuhgmXG_EwgSSvj_FykDaLTM9ixgTugWkc2Jw-xKET9RfxIgXf4LbOKtrzl5G77wHAOb-9p
rxg8k5e7hoKsd5bTROon54yKKv5JAwelTOFnegliJ2bQ-lTIMd1EDeFij9XUD3sAp-93xc1qGAOlKXzFcmUop6fTta1tkeW_iomtG3lEcWwkPQkeD55Jo2sO
abmolodBt35qxUyt1Z3V4gS2ES47G36SFZ7BjHUbYUCiqRFrfRE6aLRdD9PJC4Tnyr8V_V6oaWlf70P5ZwLk76Dvm1ov2QQoO8v-AEG98mi2dsoCEAVJ0-dm
bdUYNqdT4ny0AL-9lYCpo2xwBu7Se7S8X5ijkTJACfdPHV-Fh3YggULuy85w7f-xuQRKDuJBJZtxE1Yg-F5PkjoZgm-EzmRm0U26g8sHNKNmxa3SANA0Aiv6
2Hy0VaP6zKiP8sZkue1QNrlNeyfSMtPB6TQYukYcYZDhdIVJhlreHYvkN3-rgghrfHLjCZIp3W5gS4EZMyfizQMgujYQ-oBwWJAasEzqutfTMg4xnzOmbOHf
998qPwuVrwTQNQc-nqoEwA8V74VcZgKul1Nw3LRMTQ83pMKkE5vQeGCuwtMYenyj9LnOLIVjoXfoJl6B9WkuyKPhpEdKghRGCYtX1r-6J5AlzTRhU4-dLY_r
slQv5RUiyDBnWOH3N84dLgXZshUw179CBNM1V5lxT1pJDm-6kwuh-b5tsURdN7kVByfGPwjfbz_55wh6IITScv-3xXI5OEh0hpgz8D3Kuj_kC_J0QK8KTJ1v
yHkjDVLO9YAsXNU87xJMOo1Q5FjCZ4qvdAxKZMfwBiRdZJLTOK8xC3t1DlCzDJQZdXzD8-r4zNZpxiP2X_uIUgFVgzyKqsl6CVl4zDWLrcXGJJ_1tbpB_4aT
DDC_mc-QpxLcfWT5tglP46ZYRfEvi77T47rZofNLRhJNK_I6Dr6sJ2_oc44Y4SLk5rAc8rAt6zPYXI9p8M8pUpKtKqQ-s0YcXOu9R7RBciqiKQaPfgKm1RNE
SYf5eYMvsnrhKjL8TQiF51h5JE4qLySslLckjsOAAKKY24MhL9aePAAbrboXdYHc5zRtjxP4I0Gcmhz6OUNiXMwGONRHuGwegMNA58mfce58xT1P0pdkUBtL
pBxtGjbA5gkKFdLw4glPQhyEGTY4LeYYdqdC38K-95IO5zVOhCMgErPZVjqRACvIC-ijqKz83MeNUz--9WwrMSavq8z9LMv5kmsZQMyFbEDxMQZQfTisj7E9
z4k4L9fqLJDd7tU2Qmv_zKSzT9te46urnq-4_m4
}

