sprite $image239 [240x181/16z] {
vTW94keu38JXMQZ1wfRH_MyxRz-X3KcChFmt-CeIIX4pimzTuopPbywZFO-usK-rg9tzLdNjUSImUvtWSQkliOcYLCrqHRNrnJPSAwRLbRf1zSNsIiMqkWBQ
ykA_J5HBR9jhnRIw0fzJ5SMsPyMqkcfQNO4RL4DiXuLYMbtg6rHVR1DgnRIwlo93i7abMzpwOfiUYcbrrRIwObmTqcXhtYRO-qjmWsgABKsjc5QNO74BYM-M
C2GOvGfht2nl4_wBgosszA6OLdSfjhYwOZT8XmcZNEasmTOhnY8fHhcMcFnLRCk6KIyfHdcLRgDUKdnELHbgUlyEjWf9R_1BLgFssEi8y5Em8ZtUtzw3F8kO
fFTELXFZlfVkvFUiI9Uxtk_L7shoN6AojFWluQstni9RVQZ9-k8clFN4mbjugCbpYSdJY6_2M_8sKLHjgCbpYSapYU5yekMrTE4jzSHq5zvAOhWBRoKn_4iy
1PWklAN4S1VUIcAuIwzkeHialAMUcEx2MqaCT-6j98Qxy9PQO_e1NcAHnzLUitN5y7lnBhbTLtrZq1zv0_nZpZN1T7_ePO1tiekl9eO_Z7ounUQaBoI6YqYg
N-dhEbDD7_2Iohi8cAuBKELhN6FuI171uTmignZqKM_4kBSrK9HWb9KtVDpR3EcU63vSV6dO-w44GosqsXinxFqG4edfhtdZCkxLOYJG2c_4e3VFKCEVBNvE
UnE9GT_gZTj3xtTmWZNMMktzK7ievdDY91XbuHL3xMW9XbfejNTSxEyNWxwlDowxhd62nHLUDTHitvlyYGcNQUyoQmpwKTw8VBU9xWTwe-qfneHHbeK8UTOO
xljwKzycq2TuqtnYqdsMLm_ruMiCzubUVOsF7MhG3_HkNsDmL_44xRRR1EfcZRBcRbzZS21aruv_Oe938SdYRlx410V3jCMznQj1Yy7X4epozji4ZeUqepn-
cy1dGjPH7l_4_8b36HACieg3jUlLD3YxTbpSRW5GXWIBAnlqHkD0s7rn4NjteSmy0k182KPPXf47Dd2e1AEie-fw_OyViwjHbEK6QR4ELpVZ177lY6DhGrwC
BNA2KTPH1uku6NcmkCUSABCUjoQf6y68MLseQkHLURlx5d3C319ynO3NoHnQ7RVtghVtMuWoYhttrxoCzzJUyxxnlhYzL5hTP2_ZxStqHeOmoTiZIvZWxRT8
rF7UIDQHtkwHBnpdZPmTv4L4r17hKSvSsziRsSEUtbiiq6vUnYBjuurrQjkziLROuksEM2wE9Hwtd5Xeou753Lgi9xszUopU4zxkFGeqxFMe4KQylIFA9BtT
FKebl1xLQe-yKJ7SzKRH_koDmlq45TvYQ-mV4juI2MzXiV1M4_k7XBSMcC9RTAZZ90blmOIt9DWPH_K_
}

