sprite $image277 [312x312/16z] {
xDM7SG0n20LHvS2f_tezE6VxpqrcNmah0IaW00000000000000000000000000000AXZcusS56ZRdeoIP5Hpyt_bK9OvgHpAD2ULGnxcj7Besvx8vJW7MZdK
PK_aSfm3fHnoQTESKevejSrjJYb7j3QqQfJpQAqlqrtNod6NcfickuvRKR-Q6rkFzg94_MhwY5xddHcjMcrFvergBjw0kh7lH7CzOBM-xbLp5ckjwIDwVb03
hJLzHC-FLgXg3-ITXsBqk0s49GeiQE__k4dEybbhIRCaLxHSygLSR_CFC039tQFIgHhcpy--7s6G-dPHUqxwusb0AqdT1gfcflyF6Ph4JOUeja5_NhKexjOv
UTJXlnu7R5rcKsia_Ed6LipzIebYybzkRDfNejR3zETuQ6m-k4JxbzH0lwv4HvWD8wsl0ChoYyoMT93PC4lpVNPPVajdOtUt8QfXIiVpfhBy2hDPdzaCScL9
JU0YxCVEREBkfgFCXadL4lqLoeK7izauis6qKg87ylnpQvJ7cwq_6P80qlmpPOiwFX0mL2bHeDpFQsrvO23K4Q9bnYMAbVjfiicTPZEbVrW2A54Cnn-L257l
D9jff7V234hqXoiNFd9qU21Wc1vOPb2YPY2cc7w8RENU6atqcIMSbAZwEoP0kM-NZM-jqKmR-8xHt5qp9RPpvShoxRB9dMQJI0TYEJERPdHyga2vUySslLEs
H4Uod9ZD2dsGzR7DRS5Vbk-JBUgDDSgWH8zcssnvLEwXw-NmJKKQxJwpQG8bUZJRMg98ENKJCQ3SBRAb6sKhe4IFPcCw8p_ylQhAfjpy7RAfD3C-3_ZKR8a0
IBaq_rdPCXqfo6oOOgv0kJjb6rsZxbRYF-JoIMP19OhDXfNR0i8Ub8ktoPO7o-PlR6qiwxCyO62sAf4V0c9LJczQM-TLje4rwWziEtjID7mKRBOwKVRAwItA
pSjNolPfP1NJ24OsRBOwITpaJ3dwwdatZxjLzYDRU6PGei1ipIIzKRbDjZIijVafP_c9yq3DNQYJRAvdofNb5yZc24O-0MRBr4_PA-SEb1ibcuwHpG6mvc81
Pelq4cpse9nj2tyOFe5qoZRKR5a477q0kg9L7g_ZSXWkMnoJ28vGP3O-Dvi2itK6nDRdnYit3vFDkyrMv8ZrJ1-LhVL8daSsDnuWctURBR4Cc3u01IcNvc-G
JSUPBRASooOq1ZPNeDmGsMA7REFCbf6TCurX2uWZSK0c393DCGnB511f84c1SdnDkRbFjc5cAm8faKQIxGkKcvSUsVedNMGsUKecmC20kBQszidMRpQS1tSg
5zcXSZzGDePvK8VJMENMBNNG3N_eaMsesUvNBglR8ENcBvJD2Z9R8sfQHhSvg5pegz81iWqscvfkFnqU4En8kHo-NpPijYGLp4iI4p7xkZPdSasvG1TbSuH6
DBFLS7U9_CaK76aaIR5oSrjpuulJRg_PMAge-HkcNpS75tEzyBoQoZNPiDak1OBwYdtX7Cps-iFqPQ1iTRDr1VTHEBMnoh5Wue1lFCMoZJ8RLauVk-lOW61v
HfWmSnel6pPRUqlOFOxHRIGPrERgrhVA9-l6owOH1q8_wfwJc9Xj0J5c57cAoeHP1iWspcmu82J9w82e5Phd2HBAUDaqFgyADLM1r6UIGNDmtlOIq5hZ14d3
PRDI-VjqDz7DEzqpoQ0vk1mUdnyIALngRbYsNhEjc3DHTfS-x4GuutXPDZ4_KqxT3LVfQDciDFGISsLm1bPLplQBVnumVvYxdVYRuGXI1ikciIqGrCnK-j5L
BTE7jiJv-loXUh8TurYWiR9Xi_77inQWLplgLYARghqU4AcjAT04u947HzXiUUlik_7_nPb4ixfrN7kXZGMUX-GtlysekusKpKgb9joT8yLY7S91BnpaB_so
RKlS_jWy4SLY1aVUKRBLpRRgzlRxP0THsZtDkRoYNDd_cNGDdCD47I_vhUETSpNk9GBTUj6ZuymalR38gzbclFqFm0AKAsDamsPBl4zxtaB_idAslulW-F8Y
Rsvdlbq2CDmLsUfc0zkIDC3_KAzOVJyk0G61WbHXasNQWARB0nupIAp-sAggRZ_NSbiQvfKGAANCpsQIOcgoaPiJuNqAHB9jP90CLsIpKl-RT3UrvX1bcZ-H
_f6F4gEPPF_Y0y_1PTyXzNEvWqfddWwy99jrc6tLBLEKrgwsp7lTLfOpwUnqtKyjNSDybmZWtPXwwai6DK23sTBkJyH56rCqppje4p9ouqp2gJaHz36dJlum
Sr-c0ulsosOAp8RF9zMQ5z8uxqdpHWBJt64cAVIPY7THLInRDd0iOlrLAiJWWqAzX-7zkiq4BAE7zn4P9eBfGJyWMt5qB9AjLpPBHDcUc2tB5TAy9uPFmi49
p5Ofpjv5b9qzRTrDjVBEZlqVqdJ2xDfRfM-spnsJPHVyIJ9roqkSeUCsx7qcENiNmSSKVjTFdycc_aQOpc3hj1jGx8BPO9ucTsKptlaFBn1ikzGkASRZ-ATw
N3dAIIAyOM2vT-tJhReqOte3rTmbHZQb-P4i1y1CKa6Vo9RDLyfqZdXNcGfX4ii0mYRGEkj4TNvtOLWenYTBvefqKyuIOIK2tSYjHxSytcpOSBHk1FhnBH2q
75eScaamPbgJJVo3C07KjQDEu_X0m1qkB6p-ZgLDp_9qwjI6enHz9bjK_q21Qi1mXi21C0mEWUA_zWhvGpdz47IvVdfdJsGptyWJHDsqLJY1PXi8Bs7UMDZV
4M2uRlHPacRpZJ9Xw61Sh5kfhQCgRPH4oq8nSSFIGEflP32BNAA0HDZS1f6p-EwmMm4LWCbXirEM8xGRsR9-acqEusG3YR1bAMOv6tomst2DkXkZ3tfYMOXh
lqU8Cr6O7oYZPCE9u4PJ1VOLVIgSnbeWkEjwXQPTkpl90Orejr_9No9RCj-mPQeHt8_AzPbjnLmJ-8WiM46H2fh1Rh_IyKXKAxA1HD0mrSdRxvxFXTFKDdsO
Im9tVLWtgbNpGY_wxVXi3f-0i3yWyzJ2fZHJFj6DcpS4DJTtr-ecLL_L9S92vMRTE6Pn0xB1HE2fZUWV58fbBroghADzC_jE1DpbLKiCPxh5zacDYIYxrMIB
2kQF2WzgPtfNhd7w49LEOhiAgf9Zc6cPDqAMPimv4fquBk54y3Gr4tRVNHJBXt0P1yBsngA5xIgvX9vUfQh2EQrn7ZEhTA3hREHFPSi6ve-UQ72BxsNuPhPO
knrrQPZPEAtBKrZ_q8y2N7Ax0YillYPv9Xixd3_gw5uuIgoSwhUZidsb92I5VPcj2doMWKlEXMKyUxKZJWGDKn_a6qhFI61cQrqGvWWSES-R9RyGZZ0HyFo1
OT-GdiDmSucKtBtvCZd1bNLbALyfsvD4uAcVsLg4Yzm_iz6y8rIbpJV9LXpC7nt4dc-kE2gdrJBTuDei75Y-Xe8JmTFq6Wo4kte-cQj-A_EUT8Tiwc3-k52f
Nb0Wz0-xX4J1EskKGU0b8HgUF_ep5GjNTW-A-uN3U_noYzyI77PTv-a26GkN-FDJ0NMhA5TI-lUrf9PDc51K3d2e9STesOg3-UDwY_CCNoigCpzLhj3ywSMV
IewqB9J0ciIV7BTy-TWc_aYPhgAdmaK-lbPa5dDhMTr3Fd_UkowTSNMovW_bGj8ldZ-YLkQFReAT29VF1Wzb5WV2fOPnZ6FOBBb6JKanfimguobusFKu3M0v
2iVIUK39bO7jS2OoWy-hyrjnBvJAo23Deu8KZx_kEOdq3hju7CD1mC-F0vOyB17OyI8_BbHD-i7Z67wGIfMec6cGR0A2z3hbid1KFGfVvZtLFmcD2D9e3XRv
0V1buKBj7pb2tR1fo_L4o0Q2T0mord6nePIftYJZPTcAWqL-4BE-85o9j8HbML_KAjE78gU3HQdcmf1TFuFM1XRv-uNBowP1V5DErtDlLQbl24lBVI5VR6tg
ZnW8qg7ph_Tzy20KuCWblBtIpVnuEJDJqORxmdnDjcGTGJfEEEqwOWly_AD-8RtVbp3p_dQ6o_lbZ9O0VYWk9G8Eqlk58z3cuO8mBmmSEP_S5mOgUgsriOD5
_dk5M-fN2A4-Zd6SJ-yBLVNYiAiWIBzRkFZ2KNYfgHy5q3_iWY2zIJWJ18VQh9NhOqN7yq0rqyxMXeDqF45xXSDpnOnKmSM-2C3Dp5pRMblnpY0TFyUrNih7
biYLpfrrGzrMjFjartcwXLbQXLD9ItXsv9DgaqfgzfkvlTDniWisqfk4Stt-uagFRsLouSE6G2sfd0LYxxWUQnGFknwd-s0aN9syx2zdQ0bXeIpQC0QcXgzN
SwjSMe4WlOFYe5Ohy79KGVNiTYPkzuLWC0RAkNMqDWtJlQGEuV1iGi-F0y9sNqWKi-YfK8TtRNZyY0g2z3x8NgZLs70EHE2-43-SjDOL8HbOhUvaUK6uK8_7
hiybk5kE6Ozj7D6mYuFq_bWrgR7qxrw11QFkXIWMS-rzeOKJuVvODUtzBX2gxrvPdc6kcIYQMwL6ITtn7UatfuDhvwqMNt_sPYwPtHtKA6Xj2XBXkzB1Uf8X
b8PIvhPljmGv2beRJzzCa4xBSTocZ9PH9LRUq8EqJQ2reKIud-9zbbFbdDAJjpBql4gjeP5oVDhQulGJY0RYePqSbn32ntrX3E-EZ78ccnPnKy5a_AuU9yBz
10MMQoI7mtsXbFyXAgUwPQ8aRercomPMgnzPg_hgov5GwZ70yKqEm-UwkBNnFFqWo5wsN0A3RkMRtAEwArgiDlH79G9U7leFbvR-DnzuB-NulBN5wSUHWEMw
TzRMR_lMMY1G1edmimYlMOx0hezdjiP087QK23_VSjh_4ZC9cDcwlp459yBFjvm90AsaX6UsddzpSJAG2B_5ScvTfPhFPxP4bDIjrMoKGIBy8ilLsvnAfh0-
dO5Vvle-ioa-rds4_GSd0jwx-jkShZoTsGZCRE3h0S4zmizbBWwKkuAvcRjXi-7MnjClOP4lKSvCwzC75T-Hfjz3jClAgQhKoRH37DmZ_0xcxDUKCv0epyqM
5GoxluV0LvGpTnCrrowpPGF3xg-2z7Nbr5t09u6XsOYzCkp-vZQ7g-_iay1iRercY-hTm-xFNo3wJRTMgO6PBL9j_D1b-iNC-P9oZcQsFSN1iFkdb0DwDBvs
BdH0tC6ZcR-edCeByD5ioK1h-tlAzKk7pLOSjBO_hLoNT1n1ZOBMzWUOa_bLqsMgrwZdwQyHrG5c-fhPsC52-hSWSOXfjzcYEbX8_noXs3Ffj987S1_5Psr_
lz5Xst6Y0r5yJvh-DeUsLF5TRZARBTEV9sJp0o0gE0ApuV7ZxvkkRhnoq2mLyGDv-c_xTerWCGm3KD0Kjkz_t6N6GFSzKwTwbjIb6t7SsXvrdUVfqRmiQ_tv
anAwakVQhdlSqUwKvNAwAVHfs9tEZduM7zFPqLFAgLitXa2UjeF3bi8JqhX_O-kdOIDFwvvgKmnV4CkqdgwctIyxMvSI_aGgJx_1rVTcwrHsZnenvV8Wtsmo
000000000000000000000Eu1
}

sprite $image277 [156x156/16z] {
xCu50O0m5431kVNlYri0OFBV9JZr7G000000O6DEJhN8fBBAxUrCB8iMTpgKf-nLCtmkYmPtPf-rjzCpisQ2tRYEGr5Hu8J9-rzkHw8ilnyQZbBnIVhs-ETx
03o0gYe2CuJ_s2uHbHwPgVdjp-HMebnPdg9cxkRwDoLRSwRI8pDtjmyy_qapC-KcJzbBDd3-0pCgKJk7s87R-ijpbYbtbT0CyVRhPcPFiwd3373ztNPMDU7d
2R09_xKrGfcAk0e7PZCkJqfVwVr5oqHREpbkvunF7aL4EhrzqegwIj3E0E-VIi-oqzwPO2BgZaMBqucufUcLzsQxb2dBzQAX6oLi9rBNDwbLy-VnzDTgbV9X
Hmm3EgZf7QFM_VbEUrqqbqAPSgPrIKq6wlQO3Qxfnshiol_GpqQKD-3ucdEfVCPTkQGVgMNvXtwwSpxCw3o-kbNoWyAckwcfSlcHcWbVwQT_SFvVhQDe-02r
UoLFEzCFEF-Z6cKrbajgXz_-VtkUsgdtIe8TYu3TzzNqMZ_ThUPIUTFJygZFesYZac0dfflSvjU_RPTYDKDyiBMCCbi_Cz3bCMb7qT2kYibfHzzLa-0KJ6e3
sGfsBrgkF4tQPAURdUecsEd7QengQ6PxCtE6TiP5Ew3SL7SxC_t68QFCNwivg8rcGWR2ec7fSXzsfjVFBEKU7z3PR6_eerTGD2sX6KRs6u-0DL13ixbekD86
Ovq4O6H5hfxP5AZ5HSDs0aCv1aC1TczHcul68WZNItQvgScbsZrNC_z6qRvlrw6nyIE0lg66yOIY0QgzH7Rns0MFWFMwsXT5SpcU72rVigkATdbMIx7QNBJs
icXgvgQZiVbIADfmY-pQfQhDEqsYVJW-5ALUAbqNfAS5AQ_LWgBblWaynyR9bA_7Rbxu2TNeYwh5Xq0rSbDrbGjZHvb512PE6TKINr2RYjP4MAr7Tkhk9Zl1
cO29LVXmylRLi9c7HSCGQ5mvKLFT_aSr3iLzOXzPDSzpH-EgpKMZjkVHJ5x1uYoc4e_TK3F55UGuRbNubHeM3QVN9HTrUOcQkwa4TaIZO-QFuQJIfv16QZON
xUY3MM_W5jkfRDWPYZcWgZBa6cKYMXD68LOBYYQgeazwsclveFK-xPDf5rC-Kw2V7Z14Qz1K1JKi6eR0cKrcSahZQP_MtE3JuTuoBjD9KLTnLympaPnv80Kt
LZS0hYUUJzsQDD7J0QKFrePZP-F_7NP72ivmxcMzgsM5F0Y2LPEYSz5YMXgijAQD0k-IOv-CNNoaGDrqUA5QqHj3KfMV3rkbF8g68OZXNOcsxYpR_riAjaDa
l7EvbT8V1JCtLADgxXKEWye9zbCteJbMCMKNkadZjgRr0rphnpwPqJ69nzrtDoUy3CRFt9XonlFv9RmPfR8FVzkMmShpFa7sf8DQvZryk7wJwRErswOGV4LR
QLFQ-kAy5R5ApB52K4tyWrjRa7QpAGjkvR-1LxEvKeLM4DSw1crbyxR7Ghu0rOhvHltqxbLtmyAT2nTkYqlxVDdxkdnAP4axH9Hs-dMrPlkYdpuQYfkxiWYF
mi7d2joMNjG4AKiQD6ZhxhQcsCrC9pMYFXOzBHEooVNAet2kXPw4GDLKaBOyKMZvGun6SqcUuBsgYk1UeyoxcgxB3Fb6eyRgxZr3qM3I46OMhTjXJgb-sWcz
rapnpw5hO_-afhiQlCUHlXNEA-K6do1KE9Yqjcs8t9HRhOS1TwWm_i_CMVy-rFPWst4FPj9u3crQH9_FvpHf8uzxmLHro6wnB2mNGRNcEts9oBvX-F3kuQHH
Ec2ufS60nNIYaO9ZTyJqcu5SU3une0i5YRr48peNxhGxvYKtvE0DwLCCkFSkKiUguEbzTBsfbSQp0tP7p6g-ePaUJpyJKKMpl3irbTxQw3ctrbdxtcRgtrIh
Dk-EUEJszqV3fvU372rdwnHarx8Nb0_PslgbOq3DfzqHKNr7iJ6ATUDqG7AGZydBUBRY2k9Q8sBVWDtnYdORgqG2JfKQ9VPSBok_sXsOWhPSeuTosvQzXs0T
QggFvP63nCO1BHO4D8G3kH7CjUcv_yT9q9xN8Nl0wt5A-NKAces0vcNveLnBdwzw6wUqR3ftsL9A4ocqhbGuJi5Ok750hylXYsDTYkA72twmz0_PVUUf0D6e
GK1_B9VlBzemiVJiRAdfir5J2EXtvNn71QYqhd3BjGwJrC1j3gYPeLtTrQf1GBzB1xcPLdAkNNkX5Tu3EXxey6j_UHJkWsdKue1UMyBHeijffw3iU4_LJ2Xh
n_-g3DeODVOWe5Sfxi6Ygx2_u11C8L1dCHb0FxD60RqEcTlPrscRu6de2H8B69TkYgjZZ9f50RrE4dy-T2KjS0XWcsG1HZFzl_saveE-_90UzBNNd4ixvrtt
nGQ__aZFQEgdVh8Fwl9ZIj1NXQ_wDLUHuo0Sk5PH0NgX30lNy_86Lha5USNBcJSJj54kx32Xy37bvahBUsWEfPiIYwb0rCmm18zHivkavLsGtakduO-XDd3I
vvzvcQSKlBDqSsFRvwzwroOw_GJqUK0DKl0cI4AxNcjZcIODYuQZPdbvEzKyM7Qg6awQ74MZxd0Btaxg7jYzdZGSjHj32jxVsDZEJ7IUj6FKfXVHsydgRb5c
DpFrkMZZis3wySZtKrxQcIaK3VePBjptsns02W15Wtu62_VT5F6uU5Wqx6TRVedC3pitI01UJ-odb-Nte6utqCFoSRaNhIfijTyaZN-omV3fQET1xlS_2blj
DuktIpcaGrhTQ5tCuO3-0Qamw4t0wlXBFJUVCUZdN-hT9ZzpjxByFIat6NxkjkD-ypuLxM_zt6-t_J_QrkN_YaIvrDPxg_I_zk200000WW6O_gd5W6-hdG00
000Q
}

