sprite $image165 [135x312/16z] {
nDI5WGCm34FHcEtz1pxcgyfLtWYnVjQjf4hNTZ4lKjPMrlFErpvQywLjxI4vl-oPYCy_iMyKt_WJaHgWbHafm8pNUuuBQgHO6pLIh9GQAPP2ZHHpsYZu4ua1
c1FnkLB8kXljkPvJ8yLQgQF0KgYHOa6D56idtmF7IuqKIw56YWKrKgoDEWgib1efbaAD5FEhHi6VY0z92NKKME1xKBM3IDbQmJtOKa2aRC4U1OwN_nRuVnSH
VoR6Jd0TXO4WW8Q4UAd5zp_kO6B0cHKDX9J-0PwwklbMy5r866P5olWk1Ejl9b-4G9fQIVYg0x8hOoI_1m7j5-EMcmEw749vPJp82g510XVtiJ66L1qIB1Yu
6j4ORHnIWGpn8WZjdb4JMME99WtWmb4qnbXhGMCKM920An6LCJ3T9mjh9CiqwXy-VQG_CyWmj5fesJHXVGv2-UTmPX3F8NSC6J88ND17pw3m06igems48Av0
z0mz8pYdCZGFHAT_Lcd_Yv5YGiTenPm9eRo3aIO8Qnf3WWK1EAsFNOmAoIJP62xd3GIqTp5YPQpDp0pB9ms4yZx6E8RKGHQ6AOFAmC4-TZD6f0R9FQFGWWZW
468_Wod43j8ORI3EmC4ZtSy8SLiHgJ5KskSCEBOK-naX8pK8kJ0ilPQLmA4-zZEISjVCoZ0BQ90uSAIx6JKnXAsPbI5RxNeFzB6NWLGPRokoChY-4W_qiOz1
0KuzXEB2iFU-4YlY22DBAWmrsufePUnx9OBsCKQAO658JDtDGEgFvb-lHCf76L92PTYSADkAQ6COVtqKGVPX1alnp2Z5Y27axNXN1YsrL-89YD-N8XStHd6A
H7DKY1Q6QT3CmE4-6kF-piYcZ9cXKX0YYVV_l5gcack0tutYEACKSMRKC28aClSGQcQO3G1qY5COg8mfSM4WaWYPmhOYBub4DWZM8_tlu8rXfv1T6G6p8qUg
C0MQkGqaSqs3XFkOCkNJ688K0oeZPxfEGrCAOsJfLsGBudqOXZljinXFfd5CPfmKmOLPZI5oNf7j-xxbUQkAnxcCy1oVS9uOfHGZvuL1vf3xx_ih66zJ7e-p
6M6212gzTaCXaYkatb7gt-y8m-rJZ3X1ekPjAAuCQe64wC8L4XuLyIb6PWpZc8sOL4805yYBKOpO88_R1naHAImhaaECWIiaH9GVlDbPckjA2WJWlaD5007S
_U-slnmaLVcC3ywJA_YL0XJ6wrNPFFZx56EV0K6cWGgOgYO4Lg7kkZzuphyECUGmReYLJEg0LvOouLKPMK2ktEnZFtE6aHdbsp5A93BB42K9tjKj1x9Rao7v
F__xvoFgpGnJgWLozSo7Ag9Iv6HKTLKPj4h4tIMPPxsRuVJ1i7AuLlDcQ8rH-51q1psg4zZrg_SpL16JqULX06U9k2G7V206ez8b0ESOtNs5G15KS3HlX2Ju
LBIpkcKd6QRgYiNeTaXo_0iD2E0v6JOuPGSPtbBfOWJWacoMY8Eog1gCj2m_okYIVqfVXf22Qxv7W1eCXRcTOeYmUWc1AL9LWIi2mCmgbS5JZEeWDHYml1Yj
W6MLx_aEW2dFF7WRKGuh0X6-G-20EAAaDTyv80xg6CEU1-ukZoS4YWm1Am9WdsCCZB5P8Z33bpjrEO84iEQxmnQMfnZxWxPgjBw4m00Y9ZJJtD_9y6yOv7vW
hyMGFeV0Cc3bzxCCJ-xCGnLWkY4x12R7ZKN5KGRSS3qmGOVV3bXaTzUTtyynY7Ns0rCoHFM4m4jHW-7S9NAA8T4TJq-4_XEf711uLuKAo8vrOtcAaQaER0Wp
NTa1oojzTQuGM3wWSOZ1M27G0ECg4S-KmoTZd7P4T-U0-Y56cAqGACwUkJEF8Pxq5RwtbZh4o9Ps-WedC3DFJWYlz1Mi2Z_AYEw-XwY3A_DKkZHmTOV0ifCC
LtO_wUl9F0e1fXq2gxhy9ADB6G-3bBGoJu3fbfEHr656Tzgp2LJ0fDoPnnpmSYl9ZGSO6enqC6S8v1C2qn7PiZlpa8EHUOnHdGQl9i1OZCpE99KTl3CFbQQq
Kupui18f0fBdimaCMafxlay8u3p5i9rvrWekl8AVDd2wvZi13iCn1ku7NdE3_BA1mnC1SgUlGumhv55t2BmXG6hFTxV33BFzm9RTtmc1SMUUjpB-UM5utajQ
Ju3n4WAx_Cxl1naWTyWh0oXoABH3e7O8t3lBOmmddimp3OBb7G8pSZ3aEmASOYZTHTmFxEezHZKOrOe4ijDMVdyFmruPaQdMPDoPvxyaTMzxAeZixbchVeX1
dmmBmFS3Xr91Uq9WJ4yEQRoVWS5GS3AgtDA0JniuVq9WUYo6JZ6wSiUUT8BxWnQIx65Ko_mam-jJ21GfETQILWBpKmWCdcIaklJy3-kIVFzW0TrhXy3y70Bh
_OmkAPxTbo6aA_CmWx4tWPx76Bv2OF5XQ8rHhIKj3Q3SQj1uYf46gcO8rFq_R0KiEnrxlWFO8V0O8vomR0BqMgsfod9ujkpAF82BaNQC8Gs84wZog3i4oX3I
oZn1p4EUOgW6nBX2OBgUJQ180LS407rHpZ1yGu2vdHNuPGC7ubf8fPzZPCcozfkf7G8V251tvZ4xo90gl3OakW2z_W-RjYF0qTjGbiT-CnG0knq9xbUry_if
HlW0PBfAaXj06U8EWQwe6GAvI-GCOm9IAlak4Kf5gYS4tXMg0ZBsGYgFCBHhD6jTJBX7vKwZMfC-16INpxNs4KRL0ap8rRmhZVgz2QmayYeHVnVZtyyCUTmr
MhcRrrnhZCAhPmYavGw1Ei58AJm6u2gHMf2GH7vAN-5rbB4XBoLYBYdWpmgktCunQZeYlbiY0gEU_s6JxsFmszlO5v9vbOZl4WamBBi6ewBAJpFk4idAJyrB
Ak2JaMuwphWXOVLblfC0mgsaT9ndR4UMx_bkzto_Gw2TPpoGktbjVtcd8-1_ZF7zvlMN47YSiI4Jy3K2WEAad65yp_7T-Kx5dsMyplUxUSynRiNFIkHktcCC
yFkCPxxddkyQa6CCV9Zky-iIuTiPiHZuWFy4KldIl8SO0yBu2UIbUOynPBzyCxw_lAfpZ4ZWuyCb_RfvBOynGCmIYTzftZZ4i23iroLop_TJZ4nF4S3lDUyX
1fMg9WZyLecyZV7nbM6cR491fFswH4unEbY3qUKkW1_KZo2Xh6EChcuYgpeDyE1FI-GG0r4z6KDJWak17y_tU1C3hunS9Qhggk4nIVxZ4Zd6w9Q8x7delfVL
_6CCod2j35JTNKrNag4MlzEyMMSO9LAJGVKuS7K6BRC2Y3zq6_8ACFzFkvccIy-RG3J3TK5HGFQ_sWn6RRdpVZ-lUWL7ZIoT1r424AoxAAdi95Wfd_FzF0Qc
mMS0knZLnjMBT8Guv_jvZ2U8WPXczOCXcVawtyzZx8c46IW7lvhL5ai1pcFO6ahq6Wmz84JC0xt5UOpaz80TQqBo0U6Koe7BZsFu7benXyCV3eAhLClVCyzX
hDzwmA48gbEP6SYC6GPR2d0Cm-NWVg0dLUMOST50TYagu2t3PGUAmeMH6LMsKrIXoZJBb8ZixWg7zqorU1p20EU6VO9s9QeKu61KTIMikzk1wuep64QBMmBJ
aG6ieKJ94H-CDb8t1gX369q-lb5Y08vdRjNM0rmrrC4yYz7BlgRyr0mbKbEKcmFHNSH138Hk34rotFWyq5ESPdNL19po94QMyZRp7YcrdTLnHBW6Wr5r5ACx
PL0j2GnpVMOut6JmBAWZF8vX4D2MmB6ld6Fq_K0FTMJo64PF44C0eXu9J8Vqdbi5YqeTm-2zu11WITKjWQbEcMMAJv0QPZXOb9qyYMunbmIko2DVGua6u1m6
reBNk3cn9P0mu1bAb8vYV2V72Nubn_rveFUminY-5cpgZYs1gR6lPsuLPp5IU9BZ0V3_9R1Y-_j138l7UM2WxxdL03MbmWhQ7SCm-qwEKpBJlrAw9R3YBfNn
4wG-Pb-qU2N7gUgFZGQoEoC3tZFfgyvJ6Aag-qgELpbYIU34WhsxyvQpKtl3fMm33U0dEPwIsPR0WjL88708msJBleZKawAI0humkYqOTLW2ArOdi4Z0vq8B
IVn8O24wgQCOkIImgbi6lfBZX9O4QcBbvp0WLI_xgcxpLtASSDR2gDCIs59j-x9NSjmHQL4ZWPwd9R02knCeHqXQoN4QJBS4olqOXWmn4XZJ2GHNMou3stb6
0kEW18QPMbZ9yHiZC-3gV2N7lSY34cZtWfs0L_0ZWLKYGk8Jn00Cnb_5m0jZt-3HdOmjWN84NybnD-0OnfOyzlINc3ivZbToFD9EOZmBzln30WdVpiF36BJb
FAmbWNf9u4wE_oh6zGU6dYQjHNmbns-CTSDVh3YA0GVsWZbrMH8OCQLQMyIFOPW3B-S1bKHqvaXWAwe3hfKSrm4C5-2fDJJzE4_FCRhQB1KAUDTAZX_2iCoi
jg_a-Ap_aS0S2IoxGSzWmEAMm70W33_RUQYFVPMPQYJG3c5OkOq4oYG0h-IuB_jgavWZWQSmkhEMVOK3_4gExnPS1UqWndYUZLyLmO_pK2AY-cd1fP_4I6M_
tc7VoN62hYM1giwZ65qgWvPz-IivJZ3DyyO8rs6Cxi3k14vol9Rpk05Cg2BFxOsuBdZT4iZQxx1pZBuwS2E1Ee7X_yFutu44bW1u34PcbioYyoivJjSvZFjE
Wpd0bgkNVQt88p_ECpy_Xp5NoKXW1NDB844-GMg03Xp569096phudHn_d8Tffp6cCjeIk408xWwS7y6eDyRy8PPpitvBO8Uj8FLn3D9l4190l2IGgrGhI7qO
8nIq6mIKcLGtI21ZIcNBttyHm_x4C2fzjWYLWjSZWHbtgMebn_Ca1c1XyBiopCe0gvO4jeBmNibndSIONqnb4DboR0ciW7_UONz-2UFdZS7hZK59Tk_6aC9C
ppiid4i2_GI6u-S1SS0Y3RS7kgJ07iDICKO2ps3OjK0irkDDSBQ897zr0bjknp1C_82OVN-y214-7BWTBCvXLCRz1G0N0FFvU6tkD0V96ep8pfCOgPWjSbsO
9hx5ll3IB6eaa6SnCdCgSrtl3sT0RYn17IbxCFBtCMuGpk8tnWPP4iXCdSJ8XG7yV55i1G00kiL13Ar_Wtljxvy7Dzt1ekHSwdJwNu6OE_q62G97YnAPIVl7
3sr0lZ18nhs1FUqiXbBYVuex3zm6SXYAgh59ylslkqlA92Qpq3PhufUA5ZpmyyjA7vGpThgl23EBcf2joDDD6Jm8A1UMUp8gmInsj3oiyHfJUcC2pFMs8YpI
3H661i-jw4846PW0CjYA4BHOKM4nkeeyeu7KBHP1aiR022rJHnn2DX3kNRheCCo76ZwZWSZM50kW2Z2sMfZd77PWi4zZ1IFoa8OYgg48bmu2hSWq3sWeYggm
pOCUr40IGXIoTrG4PRmd181h4fxCane6Tx9ai0uKMri0wum5u-V7EGs-QJJ0W3GPh2iK6mL7CXOCdTB8bNzgGAseg8rDHAWFduOmaubOAFtWYkRS93GCA6rT
Uv3OPXAXs688UZA2vpHIoXdwHDM0zuAs0j3i_ec6XqAh7xOYShAmDIcvb58RiqKnj1IrNE-07WglquBK44teg4RAVrBKGKLa3ascGcohXs9PY3_G4FDP3HUX
vO7YAmBtK1JV8RKygs71D1Pn4UHXAu86TLzHhKTN3R9au70e3MMCxWDNaJuxuIglMNbXVHh4X7XI8pSUXdc420rR4HUXECbbQH3ImL0ozM64I2IZRwcLXePE
WsCQH7nkHNjEgOL6YDYyLt76e5hWhK64BEBJ82GweJ4X6VZJmqGmPnEXFZkw1dSnaSv8XdokCJb7ItW4aKn9woIXmUWQmY945emGoO5fI4aNgkY7-oc2kQ69
e6kGc0UoA4mVdwAZfHkm_k6NkrpB6neYgokiGbs4FzEOcFvA9jLGcNalRpH5c2qOIuRviyBwKjofiZIk8XGUSMw8GaYVJQFNj0NcqZ2JcuW_q3DxClZ_fs4b
tPF1DMnDhYko2cjODX-4Cidps58aD5xJLoGAQtWo4Se79TrJfsjODDTaubg-X7mQ7vLq3mxN215s4Hl5xTpuhAHxCb__9MkiY0ZfH28Pr_Yqf7kgX4OamsGo
vc6LSOq39Tq2tJLY8C8iNG1PB9bOqHCbtKFJDK94xFHy9nE5FLBIFOL28poiB0XabI7NE5JIVJAXyJCPHAkjQvmfwPxSGkCrhnDXHFGLFLVIFPb2upLC99B1
cyRsUdM4CYw7sJKPrpXRqZqjDEO84Q9_3cL0EWh5cNeHyMaSB-cUBAyuGfO8rUeQ-vAUfugNnk2SSmcDVKdF0yFlGqhBkMuqhAJFaL4rthb8JhcAQMnA-Xo5
Nv4Bh2zOsOWs9NsEEZoNdfEAu63OBCMZm5oFC0DMKhN2jQJfr-2nBaFPDJObVPhILMEqcyQewPTfNSlY6bxIBm1zZ18QLjAla6bWQFIIlaQXjuQNz6kOHadV
9n-G-0C
}

sprite $image165 [68x156/16z] {
fD45ZWD134JHfhJv_jTTELgka3iM1vwc_hGdDtdtzjRrBQAytY4keYAfp5DXSGfNH6cS28DKVaxbqWz2_2Ra84k6W2jbcPyX0D4zNWu116GfXYXdMI2WGkCW
16Rf1o4mo-qGy3xBMHRCg6OPf58zbTzP-eOGnImOefu5PjIpz0iOrInjgUXRYaKRAPmhvk6jRJTpEqFK8zBeQkvk1ufQv7dVRPfv72ZcyMcOBl94Yegcy6ce
EOcbcOgMXKz3Y3KH6FGe11eawgZS3m46BsRY_0e6tPs1XcnYOlN0Hxale24lAHPnts3Qn4pN7pagWY7GKBDz7IIVZm8Ap013pCdaQv1_nbLuduyC2wUFIkrm
gt8OXm4mG6rPafDv_xVTsxPmsOM59ZF0l-yahexJd6PCWmJgV4A7yaiXdeOF8pJzC2QBB83kVZWcAPtB-DCmEPr-63Aj8orssnApVXN6y6ceA8OzwD6K2YXv
PnxjSXlZZi48i7fskRj5rAae7tjFt3GII5BZh8JHWy3nQlgwO5H6KYYgkyjZee3S7lFOxXeYCmAqfUuQe-6kShszrLs3RX08k4NMc9EQJhOqxXhknXZAohA9
tN0pOFTjGqTE9wbADjXJtKxOlca87pabPK1AigqLmw8LwaaFiPab9BbaC41c3vUxJIA2H6NMWf6P9VM4khkLPgICM3B0oAAovEw6PsT0jMIma96aH7TNzu0g
IYk6ke5Cg4svnXobVzgmPBZHPkoAZen9hLWoF1jZTebPDZmdUsZbkUYZ5wgaIfBLMi_OS6fCshG1LQRN3A5KqTtqQ58P9IImbh58qdF0tMs26PGoRXblXw54
1QW6TwJHaxkQM3AGaSNYrGjx5dRrli6KbHb9jsYVlN1WRIrqGwn8VlP23WSMZET-2wY5FZB6h1L3u-nZPr2BMkY5fs5mEljXI3IJIbHRMGk6YqnvqCEqCbM9
uj8ykeKSvtvh4MS3ollpmCDmDqjNBtHsPvGgbeossrKWVMHiJaIIIyQfg7JkjzqDAw3xnWwuTqYogBCNJaVUDsnfL-msTVL2DnThUYXzAT3unnxtCgRBE8Py
AQg2sDQwOJqLP4hAMZQ-b6LN2Yj6zrDvbeMvO8JaVNmhoufH0Nr1z9aMtZSOGFa7nKj6HVBxWXQCWbZnqu8MZ5GR1NnJxXZlb-5spQwiRsMvR_HKpJbAAdvL
xXlCddmOiyYlIlTzms8pFMPrKwvINyfzWr44HhkwMsH6hHkPIMhqnxk3aLoVHssWbDIEO4mbv5vwBWL4W1JLvvB0X7ij7ygCBBSerJosS2HN3BMhLRjYLith
35Hh-N3DwHAIrxl368oLUSH7nae2H7AmhHN3r6Jsmx1ePGd7ebOCWaAscprCAP9CeFAEmO-rHB5w6jtTAbI0PAmOZ4AIDkGTmHm8gA8MZ0GYaWJf8sDZ8ACe
ksyR5ZC2wfPQd6qCPouPQeFrULO_sj5ar8hHmpK7KLasZvoEhkHT8wEYXyu-faeQwibknO8XU1BZOOWo86QnpHN3f2hTWzsY6KTGkMHKW8KnNDrjCZ_EwWi6
4rbIdxsmXS58AMF525HaYLSlhBxEwYj6iYftnQBR76qOKRvj95FjvrcTHo_iVzomOhXTmvM0MX-zi98hnhdVNcTrmKSlL2mQl7AgIeemMrpBUerhl_qygqDQ
p5X4OhZP_trMNp4oSqlFHf_xhJ8enQfHkS6Wh_sMaMJMca4ZDdpPRoj0tp6sJoEHh81Dg-Omna1mmOW3AIEYT6LCurulhCkeYCpAJ36Igd7qGYONZ3OE1H0Y
4jIvtouPencxSenu35IRIuQxZVn44XbPLRbaU3UU2eb8vfBHtQujW3YL8fcvQ8ns8HzAxifXi38M343j111RK1d9Sm3tZOeixWOoDFo9LDqo-ifwPE9GsCv4
uBxncXg7iMqH0UHfa9brrzY_gMzPaSAkP6QT1ey5tJDUNnvCP828RTkDSHh7-cuPkx0bwmWcOujCwZ2GGE1Fen_64G5hLx8g3YMoJWFrbz5ZucMxZanYnNia
UHfL103-RlGOFhxmnwb8jRrd5Z83P1LPVywZy-EcGOtHVIZ8oBmYLiNwpUWnwktBvH5zV7Mjt0tmH70PFmlwdtiwuQVo6NK-ZU-2u_iT4lJeqIqHcIZ-dlN6
Z_TPthZxvtCkuFyRFGRVVW2UPJaKxivbV1Vqw_sUw0-bgb35J-CfTFvrnmXVfv8_p0ElDsvByNf2t-lHO_3clQjDL-OOk8ndi6-F8otkUjdwQNmhn9sosDjB
wDEejoNYJ4kRZx-9Px2Nn-RkxUNrDSSpsEiZpCStu9pVWhrKbdnxBEPxi9SBy-SS_WC
}

