sprite $image169 [184x197/16z] {
xTW7Zkms48HXPwkhgvVtFwtJRC4RdeQYo9P8O7xaZH-eW46LSG5M3MMYhBtfoFFZOKEQm3ovtJ9Q4AssbT3vfxwPMebkr_Ks3FrcruQa6oG_hATM2NV8z6Tk
zuRbr2hXnfvKRhFqstA7hPOxRBKUMoMyisU1mwPiERPQZgqgx1NXfjQ2mvQ4RsPBmcs1Ako5uBQcssrDk2tJjUoNsnPbsxQesnPbsxQeswvblzosjDjUxijw
kG_sSbj3B_VB_N93pUt6X_nZaxbtcEeAD-GUubJujtHt6S9yDsuAxcwvxYxdNfxgzd_TXvWGys1qHxAxuJXdSRDisrPtjcUfRd1B2gbkJtCxtIqjqfBSp7GZ
pnrClKs87BQbkad2Kjp8TFkYRf84KjmUzCpZ9d8Ed45OJk33ZGntvBbTRXlFjZmtA7S276bkCDFj4RIKA7SAd5bk_-J6AcvG8UN08y9JsKG6tEHEOnCPS4G4
Kjb41jpbJcCJ6N16H2wRo837-DU9SzSDc_UnT3vnmoPrWzz20XmHWLmsaG3tY4YwHvGZ0Su8fXsst0dm6EXsLjtAvdaiGHvtmt8VoturdS1mkOznmxaRQEFX
Z8WqjTmRTh8UDrFLTETc62sF2EQebP5csCtiZjS9MCj1sWOqoBDV9t3MU-p8Xh5oF-q6U2H_tv61kZp_TG8uZwKTsO11TBcPSNiecFPOO9HSZsN2GIitbzk0
GNIv4ypguuviG2Ez_tK2kBCz63_io53zTA-w0JXFXiyxig4XCsjyBCM5kxCd_xeZ2zvlZuWWwH_YgFphZYnuFzuUxfJyuuuiE4vczeaFkHFPSkkTqfKzyZIt
x-p8XX6bkNrtHxQPtVvaHxPvtH1ROJ3SizZ-T4Us6Tr-O4Us0Mxdq71eHxP-DpWmFxeZsrJdZOOTsVhSzB67VNn7jYwt3rEZiYEFaSkD67YBjEx8PZUwfJO_
iIFRMRSFSADdHxPJRdQxNUeJExBa9zoCJdN_ZjmkPpYZ2rrN4qup39Kp4D6hPj-E3Cdj2hVGth0ZZvCp_8pRCMv7bho9JZQx7MthfaCxSatUGAUpnUtuWCxR
aUjqUXnqk-FSZeo67HcsANjg9-fkT-3o7LdsThUxGs2PlMD7jfOTkMPtZmXyhJvzv-_8iWjltzqPoxVONjcHcpPm-z_F25PdvFuT-UmwQC8dxB6PExBmj-_8
rZN4NhqZ1xGZR-ZiWXtPNploLMuikoFx_ewysPmxijibExA_TkIljxQAHNVam7UupROZ-t8xykuW6rFlo4-cpPGTEM_zLZ7hZknFT-Ge-45ctJjoyY8RPSaT
ELWmtuvStpQZ5Cov8_DvHV3gffc_nmfTLqV8FS6ExC3XoQt8NPDlgJlonqcMHog2hxGZHnIvAt9Bsv7TSMAIBO9VlYDhb6r7YortdJvgHvQutIosGlwEh1bP
ucQpYXQtijgGh1tvqxTCzKxVr4EfEiROzXqP4dUmLU-SAP5svAGPELW-vvXgHwwprVafyqgtj5Lu-v2CH7SfG-4gTqSEiSV2LPgRPQ-PtH5blvdTvLcJkYDO
dZUbE_XMQateZYW7cj1T3lLRWZjNhUPnHx0qbE1ELgi4TwvQtUwMkhaxtH5HpdVMNU8kjRh37MHH5yhPumuTzO2kSqSmoi2kS0SfzC0ysHqCbfpiiBiqkOCo
fpNQ7Gnzjivkb3iYzCAxgYvtn3iQvOugRiQZX_JHWynuApUtxrPEabvcpF0rB-jaDxZ_1W
}

