sprite $image210 [294x194/16z] {
xDY7SUGm40NHioJcWoR_RAzGvho4bfUu_KBe6lmrv_kZd7TI_NASCpQg_v-JKWFiv27XPsSZtib6mpaeTR-SQgcfxcCZucExb_FKQyPxEchAJlKODcACXCH6
Y8qO6vMTMZsNU4Y8FqUOs_uvmldOaDW8YOqG8o6n4RBQ2B4HuxT8naD23Wy9kTflVplLMugDaDN7XdX8I6o4n4R8uJSan4QCZmrPFIJ4HeoFZR4HqdniY8V4
s8Yn4PBtDaYUqxVwm7niI7nio7lumzPpgikm4H872Vdc8I4U4fBNh-GzzHupJVNDJgHIjPxxEpbFVQzbASy9L5hMs6bMQMXs0fL69-TfNcbPgwViDAdaF85A
pXEiD3IV7QZaF85ApXEevBS2N6dmsO5ArvwdvwZaFF5AGqliDAbqyNdgpr39UMALd2TUQN2U-ZQlv8-MdgeLTBhmipj0fKuw-P_Aw5IDTBfkfiOofTfjpzCt
qibvolbCdVnF9SwJyqITxscUd2VdoRzyNt-Ud2SxhUtNFDtojuBZHtjsmXif3aG1U6ScZUqw__-_NJKb0Zm5YT0nZObhZpbqVtAzuEU8fosb8NqAbdvfsN1w
4gM4yTJN3fL6feJnr3iLL9gE4tmzzQy2LCArwvqAAXLANpZrU08bK-hnj75fcPNSJSflYITstnrFeEHk_2lMZaJTVV_QWPBx90ThTpCZ1QKTJg6Ks2Qbp6aP
J_bMJiIgeBJxw-b9abdTSqf3PgRHwOQLBukYqlvu2fCYbeTGudB7UA8m0gNzQnShbYZEaXiHPuodEnY1qW6d81cLt9LeF4wtgNo9HOyfOQSIJfd3Zq89Aj-6
3z9X9UnK8iP79W4bYAT6ZL3fU3nbK6gzyYLM73yo1by5HTtM6vVQZISMFQg4G-juIioqL4fG-JQwRAZqSZnbNYd1rrFRHgZqqjVJIWaxbKO3wNKblBI0qlfo
Hqq4KWqbZ2TKWhLhODcgA65Na22NshcqnB9P5ILqMYeLeOHhntJbPJFpMafO-SvANrM-JDTTDlDj9l-9eQbJWSxNE5ywdj38tAieuTfXvwlvefKlbf5cxcvM
KGcTGidyEIM8hXfFB3E2cPjLLdB1obTqL4f3bajLlhXiSPBYt-fAZfLlAcnUKahvIfKl6isX5F_LKzgkVBKCUSXynSgN5mRcRhQzS-9UoodMBezdoLs9OEs8
w2BN4VEbKvMJXCDukPjhEkZf2jDL2jlHoJREabSPWHUfvyQ5twpqrdWYHeV9oCrhBzjsF3677YX1F9s-R13UOGL-LGShNqCbYAVttlrd8rDVh1nvvH6iV4rX
uo2UtjgFcCtd2GvITQTOkxdo1IM8fxUMaM6q2YO_QV15ge0InDCxoyZF3u59oSyRWdXQAM4ylRECD31IFtK8lWf02TRkj6N3CLlUTiLF7gnyuOqSr-xiPSEF
WOrpT7eyvINCf0UToYdBXlDM8uodDSj7vlLVC9rbX7DwQcztAZ25o2rZF9qOI3WEywQr0oLrjw5KY2Tu7Md029n0oMb8rIujD1gPszMDq2albMJyQr22U7hz
TMGFapZCTUAf4DkabCiFnnFnuYBhri11sdoH8XBd56AK8Pv-v7KaZBmL8tIQGoYKc8WInjFhopOQcJM2X9Nll5mKIk9ALA1JUUsd_wUHUHj6UBah2wT9oLqe
hrFya1FB361JMTkK4QuT_hpBqD0nlVBC5aPH_ZTcX9LlJ2439M3QRuHDRLWrXuJn5Fd4an8i7TFHwuZjV45gQUsokeRIKIRiHsOZTslI29tmcscQn2nCn-x-
OJHPRNzgDnPFAUS1XrXLw5W_iZ1oRz08Az_jAQoimdIa7p4Be_LDpc5QN3kSpCeiodIaiFLF9pSmkfTJUYez2XoddMMaRRoEj3YsYYSSKk6FHAHCtrWsVDfk
9f3sTofucEJZu_5t-7BjM7Q_8Ad3t6hj4YcLyhSCIT69q0Z75Onkx5H4wLz-_Cb5LOY-zO84ozRyy7Oy9L8Pqfz_VnvPL3YWM7UCxGZjjkC9ZzFZyOypyzE9
YQJ22rBpQvUAg3moFqUPUJ-IECpjdShmRIM_vUIvKy59cLKLb2eOjV_rL0AAfQfH-vUMb0cKQWHI-vUM8H7BBpv8U9poPbCWtMYSg7BJ8IN_FSFeX4eTQNxV
_2gU2aitmkEKKObOkf4ZKqaxbSIdwKw9DvJyruu4qnHFeDIDy3ZbnOklT2CSXhKhpAWateU2QN8YKCA3r8zJ7cE9PTkeEz7JgSnAQDI7EA28bqeOI7ru7jbn
aBgJx33gK2A01DF7HYNni-P_
}

