sprite $image133 [160x204/16z] {
pDUtiSK050BHL69b-g_sU_FS9HHGmPaXshDtgoJLwf0aqShJDuzk7NJhe9n7jmwwTT2jWt8UtJfeqtNw67WTlcFGbVYC3gfrUT_YU7dVhDkCBwzZixwyBkwJ
vVtxehm15_Ujemxsk6-HuSLzXzFbVQDE3RxLwF8-QU19M5_-MkVBwvmlhylxv7XvdzTvNrxdVNcTz-Lu0P_HHNrUr-cJu-LzisuRV1fyaJ8RT8ClK6Q3xWBV
ujhdfK_2-39bfXiU6DzrrxxswPqu-q1kN8V100o01TNh-z_s3HtPoyGGNwnuet_AbhHlY28DivxVtzEbFdFFVRxbjqgR-imyz_aZ_qmNCUjIdxddFazyxzMv
HKoun9Veiltu9jtpuLNT_dh9VGalop-v4XW6B7tfyr_nvOt7eWsgdUlBTJu0jHA1-Qc-d1UkeaB8Zg_wSl9xTH7UImMKS6GvqvVhmhH2rSgc26VwyiOpPO8Q
Ndj7K3_J9qbfLGgKNiqAaf2TwKjqfWq0MYzIe8UJdkRBIziH0BjrX5R4dQYVuCjqRdvhF82gsf7CQzS6pLxovJn_G-EvLAa0K4IPiBJmMh3ixhzSOvxdv-yf
Rem0GAn3sNfLHXAdt9Tu4jrHdpurdbNjY0swQXjAwQKYSkpuSf7vMtoMlASe5ApLT1iFrGhDweul9valyZ9ldbaUdEvSLCfzFA26vxwyekRB76wyIxXJnOBX
JDju247jBVVbys1xl9Xy1nfl-9IHrD2q0Tt70nhdlbnXU_yH2z-oyMOVeeSX4nOPuu6G-rxG2H_v_NIY6putKXD0vhhjvypdtzQvClCDj-Vhl2Zjao-Sk0Aw
Sv42aFXMiKItzZ4pzxe-kzbdXb04tHW0CjzB2LxxW3_IiuTPwbC22KFjIFtXg__8r_cHdXnUvhEEvWP4hKZYqpVwXcvEeilw3qKAiCjNN-DmRFmkd_5J_bol
uIbltizOiM8algw2A7kIXK_TPztDnsckbqjCkiId7OfQwciLGNTqiU_JvqyOkZn-kVZQXs3nrTUucXMeHfOpzdsIVGNp0hZsXU5N7wbpOO8UZgovRh6liyW-
K6pjyoy-v73hW5pP3B4dkiItp2WYBuIU9YOVF7pDtRH2SMzD2lH4zxhl6fUmXJ0jKkOh5gOTgLMtHjZG4ju1ttKCgYw4oS_vwgj24gPC09MBTYpcf8dka6y8
lzs6aVgsomC04aOYud2gFT4TymtXjugiVfbzTFTjbmV8GydUkZAI9hfZlgJ8sPWOS-uR9GM0fjgGQdYh1J7X7VPjGjdHHGoTyEPp_-8Z0e0gGrcvc1QeLZJH
7VUDHBeDpLNZ_doq27UFsJTAMe5OUIWxbuxGtItHPJxBddkvhxC-xHeTPPzyxZxNrmqQKh6kKc_ZeHsG6tkYItt2Dc-5jMy0GZ-LrfWddxXxRBvBE8ao51Nw
EnuLoDqMF9aToipccJlttGWXVqihFFd4t2DcNoy84K9y7m-WNdobm_9mZ5gzwjiqyYZjv5Dtc-VN5A4fk35yZCTGLhLzdH80__N9CT_m6AiRy-JxcE1FFWGD
Wr5I8VxOpukf3Qy0rUCbtpNrCTjsXhFlotwvk92Q0TPUNFLZF3PRcWwe4Q_ux9huaappUmaVkSy74-XmTWJ0wK8tIuCQuRRhImxlTT_d-o723k62103D_Fzz
_Qd_T7n5hdlT9pxvh45pt_RprdYfJmj0lzKN0VMJJxQlI7G7VEQVV0ND_RQVTOEdlWOZ6XrkpDbddiUk1tpgSxRztA6eDFTzNmNY2j2Y0rbo1vrExSk-APEl
4O5FINmDMaJWhVVgAFR3jzJzt1UcYDrfuNCDXN8xnCsdL1BVihJ7VG3YMr8VOui2UZ_53cNKUUcBX7NCv-5Akl0f3J_WreHycmyQsbLfZ_hIcAU-wM76K6A4
mA83SemSq1tp-Qwl0q1zJ4SOK0HtZuNlp_NtV0sGRh9sKqO5YIdvuVschtlRV1GHF9HJCjrl-aRkFcXQ1t9EeZl9fp1I8_5DkZDyVVW64qXYvRkUweliXJNH
dUJBizmfv_jM3xFpVKbfJ_6Xfhn4zqPVn7TzTa1tr6TnrttRTxoqntrno9Vhtk-B-9alqHtpIUQB-9alUNq_wAjDvSaNntsvxhYl07QLD_honZlkgms8bVzh
vpvm9OLX00pJNS7tl-qkccTXFOQif24PhyH_WeyIbRJRV1_hF7ZvPgMncn3lyObdz_bKiUzdmezzKNUhJsNf1k1FVK5tiq-LkaxTLz0LV45NmSV1zvR7LFJ9
tJptBLU-ytuVkl95NIMV3C7tJhU7_CuNUTLyAlsbZn4yEWDLf8LF1_VnkgVlzYmWIQ6cFXTIr57HHzpCvq268wAYZn5g-7fyu_CalhoYZmcg-EQ-6qbLUNpd
Kmgwac_NLV71CdNTBCfTV_Qf-uYAFWQiuNFXsFL0Pv_gZuz25xewFcyUklxaqnyVKj772DLzi4pHvxhTvxeh7o4SFghWS-4uYFjSfyf4HHyZ11zo5PyB0TmN
T4NVomQk4wlfyzmdH6MVAWIVwrhuBdLyw5ZNu2DXQ-dZV-a0ryD7xBeclf9EPTSX1X-IcBNqNVDqNKLarxdFTL_siIy3hq88mOSYzbMVwzp747p8hlkQptdk
8_VfggwhxbikVQux-yJKQXPqUnS-trzryf5OtQ8k0gEFdVNRHroRPywR7NZoESzEFjSryCtZTE5pdVtsaR2ryp5FyyaNT8Tlixy-za_RpBTj-nj42hweSv_j
wIfYRLeE7yz057m7pzEeQkkZRTic8WGloMNvxXjWrGdZ_wUkI-5Rnc6ObhteipG-Nc5oNKhVjkqwehm-dP08a_hWDNu1SlgMUMAQ8CIIoBSBft79xFEYZpFx
LCmo-zRleHxVuvF7z_WUt-DxV5yjksz9xhFilZcvpxBxkkG-o-wpn_TXZ--pbl_FnybzP9bzQ9ROXsJ9WXXRlauZDwzGpL83LyjQOfyBbmI-Fm
}

