sprite $image209 [243x224/16z] {
xDR50GCW341HtDb_tBehQI-nly53OmXbKolUICgtlakKESxHnmoooFi4agEIMPV5a9MSbCowecI-AJbB8jS3kIYPU4fMSfD7xWToLJBnbApa8PNSp7BU2oE7
sdlraiXkzDv79YssGFASOqnXv7s50xah-LrUoHHpOia3HAuSoDEi5UIH8mEodqf-cP8R2x8rIoK6v32Lh6Gbv-juIhPu8di8UP0c9oK_fkGYZroFP4kPd4_a
025F9UFEIIExNBFxXzo8aLsg-v8rrmfdietrN7mcHn3PKG5VAvuv-Gg-bjrFv4w574fzwdIb6pqo77mj_4psgC4-rxSLVo4d69aS-5e-axDPQc0dkro_rWU0
R96JNQehjSw5R5DThGqeEQ3zY07e0Y97kk1hQsI7bHnAXLSyNVAsV3FRRYE7WQYsRX8Bc___jsDsv1FBDJ467Yqifzwpt0DKS4Kh2M1mK4haSmOO7PGC6O7p
kGI__nLv9J2FNALZP6PWJ3aI80VcaSvo3979WJ7r4loSSkKpZnZwz2LouJl4-OE5oFp0c2L0PZp4-OEr038bSEoWY5ov3t5SQKGMSk3uO27oh8yyzw_q2iWi
vf7VRa1cD8-yWo8oFt1SwNTaPJMF_C4gW4mE75Uw0ZAvUSHHVohokSZhemR8bEQH7xIn0-UXZTiyyb4pUk1yplJcaKyvFkmGoxHPACpZ_WxARnvv1-K7pZie
_I7EPw47pgUU2Hvvxb_fYSn32IfzL_EmhRiyATy-MFS4rjRxPa_JxWbKo_iRSLCHrIS0DvlW4DlWjSrRV_XscxTcivY7ZbatRQwFVXooIHvvTEjzqxVuPWyS
yOZDOXxQt4GtLzsQFcp48pQFUUoithVUsyD6F68JlNceRsvRRsvc-fWHZ-XppIE6xjrRVqlJ-xxlvf4NUKvKrNlVtFn-bLPlWFnAO8prliFQvlSQCI3FziXZ
-rRVISRC6o1F-EQXRJEzrqv3TCuVBrcpkrucHEP_yuX772Fp0rjhCJAQ1_-8CHe0quyOew5gyOyuHkO7jjO2P3GFwfYt338_i7eBeg1Qz2EEed28sKUSGUO7
jjOooATL-4USG0Rpu1rn78L3J3xYE0h0v2EEeyUBqCUy9QBomtSQesPAF-9KxE9QLV-U4Niz7bpN8hJGrdBHy-4maDUrgFuL8ovlm3loIEM3rlI8JuVVo2EY
-hD7l0xS6-HHwHyyOZaT03ceDFbbMWOh8FDKMhtbKey35P23IbFBnqwAo46bYI_JyH0WJxxTvddv294HclyonSZWeBpo4IB3mQ8UyGAqW0pRpIyVCJ8SBFhB
52DZfTdb8qR6IjEFE4R6IjFBHuoCbQQJZpmoLffPFcBaKe9AKya7nWNur2MeD9bynCZYLeBjvfAF6BcOr-1WJVxo4IFZG4jmi8Za8qQEhpITVEIHiT9JlidV
5HahpIGV6CNULectcqS-CCSLeCqbKMa2-O2SgjORQ7KhYKeJo0VcB5e_ufYLHALVUfbEX-zcKIaesV5sJtwPuae3amJielhQBmJylvpMymAVB_ITpN_1Iu5A
SuqOiM-XnVsAgDtN4NCjKEcfvIFE-Ty_NvIj_K8sSy5Al-8x7_VByNA3y-bVD1lCLl5WpIaV-Ut6cFc0LgpqN1-Byz1V8FVj2dslxRR7oaU-qeZSUxEHeDBJ
o4U-qeXyXNOhM6cEonHN6f7txVOQEEWqyf7VRaGUq80CsqqmOipbpyYzUGKb1UZfv2FESVaQMQv7EbrfVP5yv2jjvjiDSgrc1IizhNpaAsrcTeDSpeku1jiz
aNpaArtr4xAkbqllJOBjdaW-yfMkvX-HpNtjR_6WqXDVfjX1YumsR-_8hUzn2xPxviiKLxhOxbytoBA8wOhGf2D61wrkdv3rV5ajUWVDZnWkqqihVOlSRRbe
y0uwctpaAsrNvFTK-zCxwApoaQzq6SZUtsCVa05wJld8LteWM_k4N0emb_I8FI4VJtPGSJDh7v55f1PWjedb8t-m_EhTLsGr5Qc0J72P4WwwGtz0jW5T09b0
Fe8SORkloBwr7Jf0JdmRSSPA5ntGL-HXesPkW4nrcU9AL_FVo5jlW4mW7-bAovLIjsvR3v0JNmYOkT95V4VUtGIHy_91KUaTsThta44-E2gz8vit1sGU-SWx
gDW881F9Hzv1Qu1C8H_vZvLche3C91zvyLPp0MGk-SW_cjJ_wDY-meXfAmt8WNpmvXmXusNYpoL03bu-U2iT8rimOl9A5qlA1t-bYn7AHzv10JcI3_wSAY07
yi6VYnH03kI3Fej80UH0FjXpAbhB5JaX7-o5bheZP-I3lz5I1ZAtVEJ_rqQrh7pmLzgIyi6Viyma7_y
}

sprite $image209 [122x112/16z] {
xTY7Zjn830HGnMOpIV__jxUzWgySE91cXhsvBY0uF504gmqFNR8A3UyJSHk_cwplAK_l0e_VKRPlAVly8xzH9e_biPHtaglxt5isNs9v-Qho_9xo5X7yjMLV
OtdjAoytP7aBUNiVUNNpyYE_HjrB7t4ybRVInLsv77PnS-e_CrnXuVL4fln3gi8jKkVRia5ET8MFYD14MoYFwVBSN4IOpRtsbsVwtqMqlpmrDuZSa6it5w7f
dv-T9a-50nVhNiS-yWZtfhtyyqTIpYcEqqYT0xcd2reArZsxEUSK5dAsRiW9XNNThWjaIIciyw1G8USKrdMxlPyBvCpYE5ytv7vkR1EvkoGMrdLQn5np2-jw
LBEButgMTt1HgEc5TVswty55eQOKbZnWBndkjZsqxgUBGpOtTRqNLdk-i8HrTrMv1rPpooWiCLNRz8wVx-wMKrWlyEP-SMxr5aqg3X7RLKql3Gmvfx3CcENA
mB6yF56KAbS7XfnVMB6hZcXK7Fd1m93VoOKyKr-N5J1a55RNWGDvAjrSd58Wex0w3Xp9aTj_O3StvUuR3gEBb9xN93S6TXe7AOMubwqMkp8FGvDVxUuV6h2L
OJZabfflQ-owJ0FabYhISM3GQrCXuvDt7fYFWI73xdnA0m8Pw-vrIdKS8XdhxdHAEaE577pot5CA_f9N80PsPdVSbes2JvvqIcL0Wgk233lhb89eYKCiUTqH
fbJwTL21dNHASMQgXwnKWWjBweuuop5s-zzVEC5-y9GmS9XnciiHbVO_BeKhFddQASNuWcKpbw8g1Fk9P_YAlPQ2Y9iorfrsId4cs4NstLNnoINbb6vd_btU
DvVWmf87nheXlqGACzxFZ5Cw_-HYXro9AzRzN7USs-sgIRPNMIhlIlZazp_3zw-Rjzsb_N_VAcFTTpx3ZwsRLG-PYCgVwrP_eZlErarjn2Q_HEdtCZzvXf_E
N1h7vY-oKQdr5qqdfvIGuvEhRKqMPIf7DAKxpjTDhDxatPGXdvrIqhh5QDLMQR5iGNTahRjIaMrtp7po36Ukkx2POUQyKpf_FuaLyiapdB_k2ldab5BNZMZs
APrV6EJubBgk6t9mIlqoqI47fzGxSsss1gVKFLCh5VNW6UwVcQh6fzG_Y-Hqnty
}

