sprite $image44 [110x80/16z] {
lPSBhkDA24Gl_QV0R__BVHEZC8var0cQtD8tIk9Zg8AsVpAgQz3FBua606w_0-iCPWPM_JwhBh09cEMxh381Te4xVTSmVj4NxMliB1UmofSC0zy8-FVJGFEE
vVPz8VM1_lKqj1MpzjEGJxqfOLywzGdxqgd_edqrC6nZNzgmLmM8YxBBZ3e3ixQBRYj5hnSr1hUaONZrVTxINhmYio-LUepdvrR_wBwsqHvoMZGD-zGxZQOU
gd2VhZQAwk45KZGD-pNbDB-34x7cU6WkDkApSsGq4rRxSDSRhQBw5skqIyIfzkbbq6AZHTCG6tQb5T5LB3atxfTkttNHTTBmzZ8ZR-ALnYmwBZzgemsUer_O
5GgU5vhRbrbJKA6dVIg3oXHLbQStuv1FbrcvEPmX8dQX_eocT3Fnl0SrJylo7--NsNxNuqGKg5bHM3t-qo82ZWGUzDdXF4-OoAnMeJm7Zzbm5HmBtABKSxYT
6CtIPuLXrJePBEUNQ_ieyVxXVBPlUFfCZSuKM-4TRvr5D7Z70f-SS-hOOIpwk8k6TUPvVv5kgTy9LfleeZ_GoN2T_7rjlim4RDhxDY4wpcBMcdEERZPAiozv
Ar6HDtZMh0A6Wb5UygNJlkETeCU39W1lPFTV6GnRccNqCHUBwgHD94sGup3QlZn8zVJA0q13_qY4RH5EsJRnSDgU1pdxPnbH7URKwcHxKhTDF2Mce9qOLAY1
WLalXzfOmbHwTmF9abrBAGktJNIQ2_VhiVehVVcR3_gR4_Af9QluhebEYtb6Q-XavgYorUEg0uhst4XtD1ZBQH7FQ5vH4mL4LVWnQQttiVZy2ELYQAE5BAS5
zg5x4JZiJawYcWJFIoxZEUrYM4WpuOPMrnpZVg5YFRwPvBIhOLkQyvpc2fvUxv-duQo8ve9VYIvwcsQia1RP1xr840p-LN338bfStkTlL3330ffkU9yB4KiF
xOXvG88b8Ui_QJyqH1FbnRi-abgSodgxdVacNXP0vVTuUTRh6-p6lhHX9kr6ST7CsnSRPlArvjhPbsyYb-2D2ZaU96P9-marP6DV8lM1SlOXP5dgO-sd8Prw
Lzw-s31F_LwqiI-N-bXbIIpaKf-tBv7wMFjbbafzUXgEK8iIgCqoqqJgyzEWzuPvwhFgec_MfflKv-tJHEhpqw29rEVjqrpgayjCKwdFBZDDf3vldoPIdrzc
caXztZvDf3w_pFGqB97wr3JuuVnzTOWTphyZMidK_my
}

