sprite $image325 [346x251/16z] {
xPs9Ukeu38KjBv93vuFtVzfPO8feG9YJngBrzJzxbzovF-94tjBJhw7-nsdImsiFjzEh8bD71x5xbkqaLwM3srcl7TnEhmvgfzWzt4wELTdHxKHg6zpjv52L
3cfdm3gudLwTt4wn-mruPy2McBWQ7AUupVNAAOH0MNQEXDbfPGfdgEmP2RDW2uKhaR5RsQIQS0nVI58DmjG8Y9KKLkmOjpDWrr3PG-qCM0M9sqbuEM3tYTiP
19A3WaN2SffK80WGjtcAtHG4YZtWFSo0RNHQBR9igjiPi6Wap2vXsH2mimDhapS6BDw1oInO3TWjK7xIWSt9RIbXEpDk1GY2lU9scNDQ05ZSrZ_NQmwx0CRj
-1rieR2P6RS7C63zutPsMji7l3DWhn3m2MWvP_oXR7p-nZQzbnBdWFS8TrfQUSKqMoMJGmSsM11eMjfcsmaDHiBuYmRwTcwPjRkAyJkmMc6pwgHjjdqLcn74
uccGfJRD0bSPJgtK5fAiUq_RB70LYm6zAXoDW0NCcbTfCrmGs75BHIfWrhnAVPMnlDfnc--ylpofbSa8s0O3URNZDd45p09N6SJjKd4uwbiOC6jUPKYtTHj5
0nOsgvHSDp6aLmKqko_7mRtwcrK65-jlLWc3U_Ktgmph5JSxljj37SHihQCNhBzPPJ2lkDdXrIvr6BDA7hjW_SqgPG2lJcPnHl6AcnrNBTT1pIhZ5Qp2pcRV
VwXCgWzYc_L1tEjrTBDATXOxlbd5s-luPfMtUcKUs6oLzntboY4aSJOxKDcsZiXb-GrcHRYKd7FwZvnpAIoWM_-74L2HtSqInNXna5AAaOWscnKkEHA5UoYc
p2t1yjOZSd7dk6KMMLNSsK_1hUP8uIb4gOXuZnpiWCKt0VeZ9L5uZPZPCnAmxSLPVfZM623egLpNW5qJom_ocYdWH9R-SHksd8o9yaEyfhPNl3ew5sp6Zstx
U-rqXBVs38BMoHXFy7FIH376bEAbYxE8tCkjR2o6yYCADXfIpvshhBeuGs-f9WU7JkkTGO1rBPJC5vrpH7ypktijU13uanzfPS7RC-9guz5fQUgxWpyEs8OJ
fXPtYmHi_p62S3dF6QIK2miY5f_Gu8If_Rq1AoMI7PQsMFmLjz-LNFTnk_bX17u3KueihsSiyJUpXAG-fMkdHJs2eCGjBoI_C1uKuV8VninX0T-DIxyWoDAf
8SN3HwZnPL9INFMtpLUdr0RTEYs7XlJLXYYR5QjtgFODhjXvWBizRkwqfDk-8rojn6TAEBwQPWbV7TefO9NuNHXO06kN4dz1Nfv5YlmiLAXkLNi40dPlpCfh
a_OCxlBiJRFnM7y60dPtoBw_js5CBA1M28W31HZATYVMUnByYCas6GoNPFnVDX2F1vTkVqT7z6Lf8-ZhLEwiOsKRW0KaFxE4HacRZDuH6JMh77s3mBzcyO1X
E-kb8fo0Tj8rPpEGipvcIIh40YnqTSEdDqXe6fHlh4OlXsLPF78MjvDsxsSv65ZwqlRE-V3niQXQXzu0q2C4Zi7QK6XIx5uY0mNxyI_BcNVVnWHG2uY5YpO-
YNe1lAfPTUiv1bEoFMI2fzYav5kuAWN90YP3UYjWFzHimsqEtI6sVcLyJbZ8hhL23R7swrfU3jWxizlZbkAtoVYldFYrVf4CNuqtJWBRPWq2DQiupC-YI8uF
oojBDOdFfhvBjATdxPUK60Y2bLaaRktwmS7tQbFCBC2TQgs54zszwOeyVwzaA0ZKx2q-6mrmlQNabmzhvDRs4Yuf4btF9qXha1IX85YRRSTj1DPktmkqmxzz
uum2ULMpQnps6_XlFihogbT2nMh0scRRSGiiKxyLU5-NUeN5gbV3h4_S-WU24eiq3k0WCnCQ193PvRViHGJdwgo-GepjirHGhseMTzjXLuTFsEfnnSAYb9mY
OGTPD0WGiuh3baJtibNeJ51sB5WrEshS5ZK7Gra0hu1PXm6l0rAeazV31smM6F3sZuIIMHpFXgfNA61nizlZbif-VIcblDxdAWnEws1Q6UYq0BD892Jq9SVD
AaJn31bJ_F0HVA0j0xm2Pk6uJTnhBAN8XbX83Rin5TKA1W5k5kzketfrC8iXhCthVOkBBHhWPl6uDGBMpIoE27CvmsmOHO80Duj7GfBgPTO1eDC2p8AHe44m
h5d3AsOMTvj9dxKmW5d0AseMZzikmwxiOnOFMDmihbOPqQm6B6uMvqypgrvHipW3c4M2mD7iChvP3G8ViyhWPZK8tCmg0vjLhwvcbJUQPS-0zJUxZ6XM0zR5
R2qffipLSEjljZW4WOTPfkkCY-5s4BCQ13vcEIY6so7CgbSliwjJquRQKSmUFjpCbhiZBORR0SogLm-pCQpXvOu1p6eGE9cj-fIWz2cvW6hzpVftMhXP2HVI
sLysrIw_tQnwTJBBAlRiB-b_hN4qwni4EC0DJFG3QdOljvAIVDyifoJlzegRZL_p8IzDjU2X2ygGMU0gG13ucittNQnGMKmsxyMa0fW5hW9vzQ_Phof5Tfke
uQY-8aDcsrV1Wy3VB2y8c_Uy9m7Cjg-2Trh-NHSl4430hYY0MVCgb0KE0d-rLTC0OVDcTogOsVPL_Bt-TJgT3YzEoEG51doYjfBaTRCIDv-pNhfvFPxED0tf
q61Fj_cLCoJ5DAi1QvCz0rOvNJc-SWkZPGUry1aIsonmLi8_29HNRc6ot15ZuhfskVh8vhCPaHjc6wzDB8v1e1nFAmvOqEh7ATVLon35gblyo9vj5ZYJvkZr
z8WDSH0_usnLuEbLjqqzjbdW7ALRmDRJOwgTblIuxueF5Xb4Fm34xRv4Vai7Ux91YrQbbDQu0Zvck1qgFoO8sd5RuyEa5H7E5o-vOHQDs-raUMUdPNF4HxWN
BwNvbHMFMvmaFoq8b6hhe_fOEsbNPfXrYbigRnbodLx5Ni2DJ-vmqJ0BnEquGM1Zs5lTz8Ll2vKDirvncpozQhs270_6UvxArziQPVcSMeY6MI0IqZYTbaqz
F5ORacZqNZ_0vwGrp09k2ta5hBzNvQ5QTLjLGguQ1uPPmEq00GkxhKb_3ET_2fLy_bl3B33W7Q3J0YCXNrL-cYMjiVJChEJQfmEB_1CwBPoZaGXvgVI_GlaK
4M_CLf7rJXig7IA1ya_rYjTjeKjzrhFGY-wBMrApKVFuPWyJySjkC_tWW3sUTc8TaIN-P_QI39-wRymgLBwQ3LI10Qz3f-LGi9ZRXLFMuS6dJpMhvAzcWq03
ta4wBNoY9caLMcP3QfZT7BUKH_1wtu6fpbWVfa5aIQfMpQ83Nd8OoZe40LAswfFhKcbjjbxFEh5X5XZm_hQXB8unDKk9rhr1Mj-rr2piDWuGi7WavA3SckMR
JvU6MJHkypjN3_tAjj0pirMBrZ0Bpo-cmOB0TdlvNP_pWDGWtywNis4MYeG1WW2lMv6wnCTcorcxOHPqEqIdXNTWwTwizhc6MJ0IYc_0gbXN7ZPWLAy6yvSr
7Z7CWcv_nb3MFnBYhTdunIm3PW6rOmM1yh7E14vgDjHRiyKmYxdr3uB3wKqyE_5ORircm2pirYDW_R7DKjraLdbp4FnbUFN3CAlZsuTcEUVIaZnymE9gpuE6
YyubtPdLZoR0xOYT5kwsva3vyaDVIbYRNIrJDXWzOF7LyrnZK5QzGRrxRehDy460RwYffFvM_Mm9WDh5yZfAfuKFU9bKNrMprvGDaLGjw7Ov3DWHs1XxbUvd
PEB_HckvQcymU13WRfEMh9gzFGDLuzbxcy6zuf4WYKA8ibgvqTMnYrfUNi1vzV3dkzLDI2kpDxxZyXBZTbfu92XgTdq-JukspLX1W5DVCAjxamfm37t8WiNT
scPrkJ1UTk4IO7RuWCNTgjbobXhE905cm0uZr-lsk9MhsNhk3II6AmKmExvN_9H3_6njwTBFyjLj0imE60IusxLS9ghNrKXzUkNBVTTXUZKZWNMsXc-Eb515
p4wlzjdph0s1H6-pEgSreDfwILhT6OQPdGLhk-NRZg1czvez3O9rg3_Lwx3LrUpnD0x6qzM8rQcRsTDOo5tKffkVuOsRdMBRy-B8ZCpq2cmNTp0BT5gZj0cI
NCtMyOJQ9vyuGcPd440RQbBCWDdf5HWvLA3hSjX6C9BRpcPrA3i-uU1fzlH7qT4ixdL6mg5J4CowxLMmisnxUPrkUtcTaJ035kBOnUpq2aL2htgTRdlLwtJR
I-oya_NoEiksr-JshDlDzJh9p-ksbzWP2RsypaZejIexwtRMwxvFg55wYPrbsylhTDlBwvm3wpNtChk4MR2zJkVqgjTPjtEAeDSvqrv1C2EXrqc3sO7jNg-J
uyLjhplNx6vx5UoCX5_bzHy
}

