sprite $image187 [275x201/16z] {
xDQ5OGG124JHnQ7_WkDEpdsPrmD_M6w3F6Nv0JIhAdZv09Brpcbv0UJrJHSWgrzI497wPNnIEEe_HeZ8EoH5wnSaHRAsSyRDDBOCOhMNLDnC4pnsU3TpGaGQ
6pgyKmTPeeuJFEDca1Ihq-ZAXnT9uQXp24P46gEfmxjPAYBIfE1c6kUnmxkPuMQQrB73kram8lBeFxvcNO4X8WyxoEpLZ4uAMLsN4swc3_8AXdTAKlhm8YcQ
TKD6YCYz9uMYRYzbxF1kveIRQMpiy6wMUh_3EtAG-_0YAH9rfnGtqwJSVdYH5CcwUqPJXtUpL4IaIHaxl9i58oADqLLl1acnUap9k9d6wGh3EpmfFI98YjOc
GmTPebR22JVJsDZXtIpblCEBf73KAZaX8dsGpp6yI8f4hLmmRgOnEdfuaHJ96YDvyF0UFyXMp-pT1vAaAmm3u7eJi2NPSF_RlgB-3N-7zUP0qxh1VDMMcG2p
MRv-ndUYo9OBsJCsHB6NaYHJ6wAq_qgIBJye_bQJICzAkI4HdvLoJI8H--Nzlv94UbRABScpKcv8zgoKzbAIF2lbckHPARSa-wAyr2JYbcVyWcJVIYb9DZtZ
roJIdcTykoHvcg0L97kYC0gI7L6epA-JYDm9f23Py8EYo89aGnH6Pa6o7meLMP7iLoaJf2Qv7pxspDmdmOueL6P1WlrG55cJVDs43pWpDGatcfu3f2OXm02-
Wa8-rEAjIKB0rnk54X-eH6gIqs_CMPA8ZpGpDSb752jGg1a-pkAjINhF414q0An893xApDGaOuoUWiZH1POa8XzbPcgIFadKDSP8WXM9n2L1whHhacuMOXy4
s4SGh4WaBhXuwxndfZw66OqPAVPq0w6HTog5nAee9v2290X-9W77c2IaDtDm47PjugtP5T5YCrEJ23CyrUj1WcOmGsJ0SO52k3NNELnhyTRv-7eDUP3aS1ma
1eDF53hSJoY4l3Ng8bofHEfy_YDwIfEnqqFiEaZURUfGvvCR4R16NONhpyoHyrKBCgV9IA473B39qWCCvsaXWp3JJSZrGMOkBx4fCYDJK8UvJHN40CJpAOK0
T2zSV6QEN5tReY8Z1QJitTrXu62CJaKV0R3-4IrNMhmroQbI8bEWkKsGZoGo4XeTO4aYSU6PENBdqIE66Aw0crixI01pW4Dm9xMC2PNVdRlFoH42kW1hJWr6
mfkPWLqoK7MuG8aK-V9DK8q0wTu78tYSKa24W_fQkCxCr2GpBuwFOU-QCXsH4yHXpRhE9nHpaRndmZL1PiftrDJ7a80Onod5394N9AOlc8XBbSWvzGkLZAGC
78J30NSEdGO7Z8W2PPd5UyvNByeo78X4QsOu3hDdW9ZHVHDniPavylNhr0JWqUne4sO0u2L9I77VX6lDp9caVgX2j80Rp9mPnsu-cypeVhZ0ugr9xYzaodAQ
j0RsW7kxDI4Ab2LcfYQvNiW4Hu0mOWH0RusNVQBMM5JACY3N9FL2xYHQ7m82hK4dWGZ1AEAlcb3v2nBVyMHqZD4ZWu1WauIu8Y3m5r4Klm84hz_phxIO8zq0
0kxK8S3hB_p_xiuisN4TXg6L5siWAEr_kQy7tbc9AsYdqRxypPzE6JYKx5A8z9mkCzCBUxy9C9ePF9uFn6_Bia48-LoPQHV-hcJp7aj68Fc20FjGjEBbC_FV
7zz2ZsM9M9Pz58e-CzZeM-Zsa1WMA3W2HGzarCkHkmgnh8-gb3EMIBySkz7opfS3dQYKKubtslNulQUuiRv-tKnJANhnFZJZhr1wgxtYiVGuleDuII6lXTen
frsRB3q2yJ92NiUHG39wSHUaHo1UCZrrXH98vcpko_C3FvmUlNXv8QzGtf5y3HNSdme5FXJYvIjbOL9ip5c_KW0CJZ1HYHUyU7aXUwiOTKqBY7V8PnGlF-D_
VgzJTbgLXg8Nx_5AMOHiyPIGJA3D32VUupD-866XV2lnyfNYC1uAL2LIbV_vYDkRGNiKYaIyed_ts_OUb7ej82hb_E8zVcnGUsqDp8EY5wz8o0u44X-pRPr8
ZroyEY4x0icSNeix0KMuuzLNIY2Pexg3IC_JCxCZNhsGtv0GGfQALryfLl6AX82Y5A--Kj2Qlo8n451qujKB6RKtTtASTQbuzPKII3WeGl5gPlmr9kp6vmGx
Nj6C_t2b2CGhJa_PXO9cVnV9eCIh5_8A1ULQGI3H7JNhPtoy8ccbDX18nEBLLmhA7ADiHY0HYbS_umUIEL4QWKGgNdsb19BftHq4aXFjU9__OlqLoSvkK73K
V2uXz-QlIEv0II1UibBG-WWaTvWa42zzZczjTpUOGRoya7lVsGtc42zVAUvtDpu9n7jinbzP9H0lF-ElKD318D6BLtziWB9r3iceqipeNwoZrb8iVaifNhvI
KCVmBOuDyecNd_5_8vbpMeGdetZvGxT0CYsG4E9D0kLMUW890ab6yV8VpthjOq52YJUXaArXGKA8DwUGU-lxI0ZnPX4oQY39B5v-nWyagSNBVpphpeetVwKu
_OutVwMa5oy_uwSNBp_ZqnzNvKzFUl7oCpujtlmpFYlU_486cvdybG8sC_ah1Up9QduXWyrCVYZjdsNc1m
}

sprite $image187 [138x101/16z] {
pPi9SZ8x48CpR6v9RNB_qxuDcef_CjLPJFlf0dmrqZS6L_BsynoiRM__WsmNa3Yj1pc1040xhkKu6d4BsGxhE0wDn2F4PTLSpY26B9hBoOWXCPTbnOmXsrPj
BdP2dBTQS_T3EnMR-vnIexT68WrvsMhCpKESrnOp6brhRlrSmjmyum5GPMxESgeOIFrSjWiJa6mkrUOc1q1PCSa1K6TkFfSwS_C3eCpSV2vr0yahgZCtDxhE
tFm0A2icdqkTkVbSwipDvr9Wxfm3u614KOXJdRdvNEQOE_y0oCsjDNg2kPE-BqX8KcMqkXEHfNDHTsaP2yuZIO9IOdIGI5m-bo1PMT5b6qYMifm6ajLpOP2i
VYmjI5Qpg3-HY4Hvw3r8Xd01Hv2GwrYetZ-GW5h48kyZ2LOybYWcI1uxBLvk53EIz2x0KFjSefYHvFrTL5VXNEXz2EAPKDxflM8kmJ463abolRkhDVN7NApn
TIpgJpaPGQbV9MUp1k76GhQcM_ZIWKJUjZC8Uk-Ip9frKg8acYd25nOJkTyHKDsXPZ1Nz-waXiNm5UQEUVpweWXQCtTlZHr8B9fMJ6IuAd31hgvc1XabYNDP
w7qtu_M9kajkQCrlvTX7678knvZnIWaKuDRm870NzGYdcZlc-SSwGRFsU9-ukmyLJHv8n9ylC0XtQox4-yHfltukp3Xw__HIHzsTj7OtcHJucqEQwbcyVNwV
GeSH475700QMoSNqZiFkvHyH7qdg-RiKfnQZdQktsm40FZwG2fPXkhCu_99T4ZC-y7uMygcYASNObb-SKmy0iv-mCETWScqTHiTZwMvYKj6FYZad465qL0Hs
XCXaUZ26kMbQKimm5u2IO1OY_nbECJVFwJuNKa32yWjpquJH_FXgJLdoOX9plsGqxMBKKyZXpCtDpOh9ZQR9BpiLJJ0tpmd10bv9xh3CC3StEbX0Hbj_XbFD
pOscaJiMpJOtdmjtZFQfvkO7m70m3l6vvkO7GA0O6qQIkURc5GMBNMKPIMxk3ADDVTJ8NsHkVW0060v6VvcvkT7KHuly5-PECvf1yWjpPnXDEnk3P3GtAMQo
qOH95ycBYjcVYsIyalAHWzEBoR_IYH0fJtx6rCm5HddoCwRWpveP5kUlr5SRZHj9c7jU-Oyh39BkhQ2Ov2kT9-RM6PsyKWlduc7kwfn_LSpV
}

