sprite $image72 [112x81/16z] {
lPU9bgCw44FBnajjlF__t7S8L0YeuyvmGcjs3x6Chf49NTB4BT6VAJLLbKf_f2eg8geyqHzeObLvIBLdkbcvBsuXbPRk1YS7gHIwJKLERe7nJd1X4zw1yIvm
SLEHxIqOKvN3Dgcn1C3uVN2gBK74WV6xu91M1OpVVGQK2_xt7dFwKdaDPlmgni97S5jYcsc2gmBZLygBWq-NpSTYyWgB-aPvrSt5ULkFEUTrOGAXNmSNKhT2
axXAt_nKp3kbxWQbUkKP09chsv9i-3qMOGuhqvwlW4EPoj5F12wDKlWSt1ub2lnGWV52UQ5KTVTJGIbsm-VbXMxIQyaH1ECbolzGSQc_kabZFIszJqSigHnH
gzIOv0ECLKx5d8uZBV-skLgEa03ZgBpsOaez1cC4DUsBAh09OgRn0Rv_a9zsQR-sr5RBoxzZTdMPueG6Z5XUa7eMVmwd_L9VfVN5S9FDKRCPC0x0FPHvTWsL
2C_STBtGN7F4q9-Ik4N4U1Z7k6klfMuAksmckymI3OGOiRmg3TLDNcMLnkfwo0tAQ_hiyo5jD5GxbsguXQoF4vfEVZd6TvKOes9-kbpDJYDkTUVNdkev1WyR
kORTx9jcvnIFfTlv19tDq563BFi-ZRpihj2-jGI-eoLsT9iVVgP7HtEE3xLziE-PrixClKwuYpZ66aHfyo9RTQBetlRQYJ6cTs8_RRUYuHOodr_z336MKtzA
v8nRoFURM9B9Fu7RP25qbEdqAcGk1TpAON9rRyjdC4hqCyIeVXuohlcbjzdmLW2Sp-ZdFuSgPwdxlB7jxZ4t2C0T_5hA7K9zAwsRt_3Y7HpuwOC3XFgRNrC1
0RYJ7Z4AKIbK_5T7LJtunT0mIlHJ8lLCuWeOJtLRHOz-ogMh3gD4FqiapjIOqW2ZyhGU9xlV-jMai8xSqCyhTNVbWXYHMkwxNqj04i6XdoabxJmtAesQlGir
AgwKxSzdLxu3Xt9rC_E-LcocFf5C_KtXQ252uI7dxypc_onryysmTavKcoHY_z7HN3A-UmxSG3qHPLuCjJNBYJDrM_ow-CyL5yS_77803cvkta-FnT6TgMWY
MVnotEFW-2Tg3ltwtirUQ5JpTP_cH7NncgYwcGyn5ls7ABtHgrQCjWosfrzl0unP1b626C6l66krYVhgbudr7KOuv4PHma5zmfWrKrrmScflGlty6PY3E6gR
_C6dUY5ceimGAcW8RlH2cxlPXh4R9UDr5U3uEJW1SF3ychdKQesQTyezKNS3ZDV03J1Q8dMcjFmoPGMC5y6XjZtIgZbJDiiaPHd4KA-3GunRhIRrJ6s1K03Z
kBmoeSOOpOKeLw9Mbv_TD31-N5wVgpucbyVdkYLgESiUwiVbXHfZT9ueS-s9AZEHMcWG9IUwfCmFZ6gMacHYNVogs28VdJeN5HZDErMXn8jV8W6_mJDm3QDL
IaHjzMCFl-lFm1XZL1pu_NhgNCUedPSiqMzSNjSnkdcZYIdylWDkZB4GWH-2kovyuKWK-nFAwykAzqQsy0itBNIBoWEZl_evbjSD67S_BAzRC9hvXVAwZj7C
uzIvM_72WU3kn6XGNZU7UhMy_WS
}

