sprite $image137 [238x180/16z] {
vDQ7ZIGn30NHk_LYIvpyerrNmFWXx3hMow30BtJlljFBUBUJ60XDAruqhMZT-Z8kM0xR-_d6k24qhJ2C6D2q8ZIjo7OFjYOvx9wc5I4OCV3WEEoUfnM24GFF
cbQaOCI0fnMQLZotUx0roM7tDAq8mOY1S1nspzCAmuW1JIiU12C6FAtmj48J2qyhDAs8Tb-TskOux9wd5PvMQ6BXQOMd5PfMX2OMdbPq-dL2JTEAJJ1Y83Mj
-8RM9hqv_g3G71OfQcNEjJbdqTgjDnUzU1X_NfIrkTO-TxHGrYRdfRM7ifRUqKZShCNQ8lhtvjwCNhr5hQGt8PbpdbhDpfj5RVivauYrdtEdthXHExTzRunE
thgtknr7bHW8mEUVTfKTtlzjpw9OIcepE30a6eUwYVRo4wwXwUwzryRT43DEMT-RDiYuLHOUPwrlQi6R4C0PwvlUgqkqPwqlyXieL4lmfEDyoQWMyCi9lLZH
flTSuqnVryBFzJQ2HnHQyYprJUiJxMdg2qOKMaljEUfBZqAxm59xWiKaqbfeGQGMzBg-_QsrTXXufoMollmyBoFMjMQBTfgWMdpeOX8UXTRCcDghCljRrBUv
jT0ks4KxKhjWK_jvYqamejIEoNZ_R1VzJKj-qjk87klQ-4Ax_8fMwzj_Y6kjNRLurEP45_LjQwsVRMe9SkXVA_QkhnPsltPAhQmskeypFGfjU3pJ_hxQ46_x
8LOj6C-qauaMNRTom2YJUuvRjTbVhM_p8TRU1hTgjR_TnXbfBRNNqjRQ_BUPJBHkvVItflQoHPk_qb-fRzV27jVQLTkbllHuZnQWx6qqM3n3hSUr9izM_rf9
VPjQCtDyGpk6zbVgswomgftdczOsQX_tDcxZZ6Q5LUsIr0Q1MhlojQ2Bvtv3hDevxkvSrDhr_bBgssY8LPlUQtoBTYfN6mwWqn2hDfFSe6Diqpv-BTpgsso8
LQjU64ZuTctsL-hRogfQzJe1V4ihtu9D2gjQvQPtdrPN6nVnDYZiYbR6URjs3EclItsR375gLxqEswgTH4jv6pMnfdRTwy0shMb_-RRwCkBbMgrlhLtfhzQt
mOCLRL7VhLfTRUXYieSrjRMtr9RzVM5zmOWtQNMS0p3iqkRP82PxLNtfyMfjNT-zMXlJhzWhZlMHrdTgjRvxj6RWcAuPaFh-f5MrjNU7TXestJ8ErHUCb-KY
idgS7JOsQYNZo1LlUhpjoTPU0Y2UQZ44QmVkYEBzrhg-pxIFrc-_VS6ViEgtOAs5M4TYwyNL-uVO2rbTtqNrjTR7j6u5w7lgYn-qwhSHx0ijtTrqY3Mw4zkk
i7LzLUlNS4oP0Ksn4zkdi9fO-JOQTCzGXrYrnLPEWy8MzRtNfZLZCiIgJQvu-nIs_ZR2MBIkmVZIYc8djbDXw_fIhHo9BRMhMpbiOAssShPQKUp4TdgmTNsr
iGOKsiMriXFRrQhUk5bHMlDEBDPsOi6ULlM6376HUYUsmr_YEg8LwwfsFDnIoVfwvmURkTC2pxMMsiSxiH7kdQsPxThLSoFc_RGNU2_pc-FkiLThScw4HVkI
vpk_FRuqRwSsVrLxRKLhQsfZdrRxczhqThQczh9JU-klKRKyyDPfgXtvRCqCBz7EcTxQoNX4gzR-sb5e6rYxQNt-6EquFCdpt5axL5iysoFM_jhyRqb-mDfQ
gxrrCFPeVVvaRH2UsiFM_jfBSBjsdZzTg-lasjfMomZMMkxKpdsriHZye5QjVRMH27-HzZ8trih1md7jd6cf_VrOdnYMoczfvyRQbKjckxHgxQkrufoirBQr
ffRngAtE1MjjQ-pCCKrqrTR7-hMsitMwnkwqvBDpGG9MQ9jR9wFx2dQzleMse_NotzKwo4MR0jzsh5zeEp_OaRTChbPklfLJQFjP_qkiSS5UjUIkOsuIez0s
iVxp2_dVdPLpk3iBQrLVgfOH6UyqmZd4QNIliBLNjTs6U2nGcoOiLXoyLBUYdTl4R4n03l7nMogfTKPgqzf6QqQn7lJUxpaoiUsqhxjrbNkENBHfRSKLx75k
thjOj7E_WA--P9Q_gJrlpg_LgFRqARJdz8hsz0dHdZ-gFNzKU_wyM_i_
}

