sprite $image123 [260x195/16z] {
xDIt0GCn34FHLe1qylxRccoSSpQ8Dy9dMFqGCpCp1YT8Bf1S8FI21IOFLLw2BHS8A5yWDIS8Bf1S8Bb0S8Ba0W6o1UhkGYEhH-3ZN42a0XXALvXy0LG-WoqN
22XV84qd8A5S081U1Tu3BK3iEVQx2znJGMu9a0dkh031Cr2hWBiBF5QXY-m0sYcyaTePR74CtWYQ1J2MPV1c43o3leJ1UyYTmPfQUyrkMuU10CmdG63ak__b
tcEuAfL8gLY1nwhdL_DEld90qlR3ya9o87osWCLnSFneWQt1-XdYKFYyGR1LMFfdZ2jy_2BOAcm5FgKGuX0OoRY2V50DnlC9Oq6TDPYly863O7uXzADgyFbZ
GLoBm8zm_rhux_q2JHOTpkSFWfzkK__GO_3ora7GhzGF_2ltIRsZ1dWyWvUftFsar4m12lkGj5tK1Cn07AU5c_V3SGDUluY_zC02SUoJT-s73WCAgVB1VV9U
1KmG63V8ppTItIYeu_XyMmryww14UpjJUqMc7P_lhm7nDuD4JQHHpR54CrX3jXQgJZu-tpy8ACIl1krtpKNJ5uDgAq5andqIRtXnfSYGWFtPSVk6wcOJM0sw
G8ZBlt2V715WOXaQ1CN-hcvGyMl-nR8ru682zVK9ToleG1ezmz8NmGY26JHjZOCb6GO9Kqd1140XgCnxW4Mc2_G8MVgq6qCm0x5rO2cIGqy5MjnLmRaKscI2
7g1j5COHQ3qQSxM_NiiAa1cl1K9e0z7np1Re1b3k2eC8PX2rlIAKmtC6v5fPeFBh4rM6xfJgLF3lXy1MeHs4QPja26OGilHFUhwVjVLm7QW27BVgUQT2lFA7
iP33Fj4CGjoWvRutZaQNVgkU-r9FlMAm6Gld1eOGefqN-kKeVZNWUbu32rGcFn6XUirWEnO634H2HWpFfF9Q3JKKgh-_k8QW8mJzLYsJ2Y5wtG2GGuLQwYRf
HG0A6MKLIT9lKJ7JbtrZz5bQp1cEUY7uajFJ0eTd6Xg510vhDWRhkJ66fESZST7keHCGr6zmSbhe16RG_sn8QoLK-NrjBhOvjhF8jXV-Lu2hJZ0uEIrmN0aQ
XVYKi7V4XZuJXREzhrWPXXzrDGEVWbuDq0J7XI3-cQ3HUXHc5kYtUsC9bZHsK7oyikZVnqVG3K8k-4dXW82ntXUMraCnR0mQlnHqw8pWC52_W1aKgeIHiL2D
O6chWOHKx7Z0jbji3Tgh42GZPuHEu520nu0v5y7GMAX6SF9uOdy48QI6qwFo6kYbO5aDWEi6cZGtgWgSZuLAInimI0P02XaO19v5y2nIDxYi04WA52XZdtOm
5aOCQeYd04qtDS1bWMxWGB2lHAnHg65WB8mODCR08F3NuB4pkAO02vT2gP2cTZ8M1Wn60cyDJ61dOBbg01Kk84wb38m5hu6w5a6lmR417EV4NBZ6LdX_V3vI
u4gxw921BFv5yEZf1fSLqCEIgOHMAxv5-rXmHvOvDTWRN5V0DfGbIMudfmLFy9XHWtC3u3A2bY11SyN0QU52rBi8J630mBSKe55gBG06neAZ1d3KOC30jnJG
g9JSYgIvXH1t3KnWpC2lK1CbAd7gM301Tms63VmAAbce24yR2-glWI6E6_WH83bIh7dEM91bOWt63VmABB54mHyAGOC2isimRk1Ne5BKzalNMC1Z4qSD70QU
VLAQBOZi60kwE1U1rS1Xu5uAbaA0yAMn8CkK6dWD_0fHW9go_FLO47SDJC1lu5SeMP6AnByzBUZ3lGWwejV0lqzAe1GnF1RsWm2-GU0ty2jev5Q0yTE2B9Dh
u3VmAr3Cw3agXBGUJAc1sy2lW8FaXbtagI3BiXi4_Xhu3URlaneuou72S-cl1lg66ZWCt0gSDTIANUm__60GB5u1ly5y1U4YILb_ClZQOaSDvXdC7migL7F9
UcYW0ul0B-0ty2y5oS9LHFcRWRwj1du3lq9EDPQSDmQxmB4VEWpUM8Yc2ObvP-2jmOKi3WFd3b5ga011Ep1OuAY1o-3TXIYS4JJi3Hm2DnZu3ewIQkQCP-wf
WT_0hw34XMDcm5K34_0O-1JyOq5YJS0TDUYxmkqAcIhWgS73lGXwbdiA0HRWyYB0j4LmvrZevyHRQ_1_EtPsyp0C0s7mtLov_sx_anK88IQ7MC9WlyIs3g8D
O0O-Y3Q06VWWse1am8FODyX01cOAkmQr1aPW5Tg0_X1uXIP06NY4wy-WS0P-2gjm1bvXEeCcsBi01I3Wfm0o00fIe0aeGhr01b81_1yo1P_1Qqy12dW5B-23
y1duANW1hw05l4AjmLTaZ-0py0eWWu6xHnMo0C76rPI2py07eGMyGl2_WG-Yy0-1dqA5Rc3_haSe-0ny43u3h-3_3tqGuIFmKmZ_8V0AuHlmGOIFm4yXV0HU
8Lp08uHdu1Ny2Bp2W82-R1ZW3FmK_0YyWXVm23u3h-17u1MyW4Vm6NW5FmAlu0KyWi_0A_WHU0Klu16uW5S89_0AuJ-57Y6Sm2k4P-0LmWKyGhY0LmWdy0hX
0lwpQxY0dq8uWLS85_08uG9U8PB0tzq6MC1F8Lp0A-I92CwTEtVkt3S
}

