sprite $image322 [197x284/16z] {
rDI3WGG044FHCVel-B3Mh9LNG_BfHbh1X4so_nW1u-YbKa9blPL2YBHwZpEXaUX3POJ5-vGImc7LWs2WhCuSAAkpKg0bpLAWiWfu3OaUmEIMlMzH2dI6MGfG
LcVEE5cTbG4jQPPAtq2p7nACazLPEUDaTLOAT8PP2b1MPyuuMPsLuItfyxdLwfS80ShgpFaZMKMynY-rPe8hEGW3KGmO_9FS_xmZPkSlUQAdY3GSeE6rNQN2
13hf_x3RTXoxAVOdaNQUIA5F8dg8ytW0eso6a6Eq6Y0DFOGOOvpMdErM3p4mf9QQ6zYj6EAwBbant6xDkvTz43ACo1J8Mju5CJX4FTMCeh7R9eXJYE5qIOcw
2-8KzbIXNDFp5WWjndn8XwxJGHodiAVS-DRe6o1g7nWIk-s_440QHGrnbPJZUBcd-6oGH3GGTMpqzkyzLPSkNyta42dvaZJuK2oDgeT8jY8DRWzhbUmsYXnY
RBHWjt0QdvF8W00Z446aLBcdm3Bd8pUZ4QFh8PArPOnkTwxgE6AiSeXnWYMxZG8YZlgNnGROhGeYfV9s8mty6-iTSe4a8e80kuNDOPPL8Ob88OOqs6vxNdmY
S4WYOeYKCjbjrDMfQACa8eVuc4GEg7yDSZ5E8dA8PFvrJ_doOrFOl3cCe1KGc4HwMNjiYWmCqy-A83Y9D5jvR9eFv_0w8uMu3-d-2tGrfZjS3eKGRBTHG0mJ
BZ20D03YfdwOH3gAOQmsrtOXsUiWEAIJkG83sAq88fc_VdyDO83N6G44IsFDNCldjQgl9f6-195UdOaKO8XUxVKa4WZ1IOHNlMM8LkmkYRZ98P91I0TZol45
0RpEQ266tO8qa64cu6_VUf50iDsokSuCuTbWG0L91224qeWyCH11ohK79n66aDfj-SZG_OljhBI092A0W2G2ncGn26g64a0IqKBmJ6HEVTO70PG0auWOWkrs
DYQl1YLOI28g21v1zmIBIm19H001IGGY0vG0f44GGhjr4vG0x5O00IFeg88IWDrg85BAN_jKBy8IJ3-hXaZzF0wUYUJQbL-iwY7ywvb8kCbAC4j3377vxKp4
-vulLkKGVF7Jhvxb42E9F8tHJ0x1hpFw9ORW9A9VvwM76Aiy9utZkiGGF8BM8uWXA8de4SvB2n6NKqZNY-4IGxnTpXS_SITjXO3lH4ITj1K2f27j93s4RWJD
2BiX1D8WCJmB8KyYGmmFG-YbyQsQUrjY6uTX00h9bfM8-l_VtJjsjyu39cKd3DpRQy_Kn22YKX8A4EAUo3jlKYa2-IQoOfSZz7P64eeHUZkZXw4MaL-6hxrh
4VdHMB6B4Vcu9Q4QeRSp-atI27m4yNuJMR7B4OacGa8j8h-u58HwX6uY70RzF6iGUZkpOdyvGjzO5OHwX6uYQ-_lHkWcic8R8CHex6s6kCTj2j6g4FScaa6i
inJ19f92nDhFNej0crb46n6pbI9m9H4Rw3DYD7C4S3ptEjmHmBdsexiZqAw8g_qSulm61FlnNiCPmS3UpyCT0OorPtT7e4sEXYs2et6Q8nYtxWZWYZsRDOAZ
CSmHZ5jp14V37C4cuenWt8Ry6wxlHd0qt170ODmw8z3cZiiSmIRYZW0EdeaO8pWQrWYEnd1709rd8iu8u0ms4LS4I_hLh15i8iCQmRXTXpM2SVjexWYqQyVr
2n7fets8HpGHPmHmieaO8zX4l15i8gM8HKHoP_Y8GaIa4Lodx-6EG5ixhcQEm8grrx17d3mJCKRi4nWhPZT7S3lZZM0JyKRm2FgmHl08UZPp1D1dh66Eu16q
EOBR6Jl48ROp5eWkZg0z4HmDSmJlYPWZs4Iy4HmDSmJZrXp19kACO1E9OOvWt5eYz6Za4V5919k8BqB7RJsY2OHOXfiXU0JjZk0ot1d1PVXfZk1snXp16wlk
23GkmuqHl2VYZU0zaUQE0AwzBsy4H-CqHx29c2FOHFv4H0RHwn1i8cib4JkkEWHBUYGH_1vm8G9ufX6nsMNA48y48ZR_ZDai4VnQFHd34T4VF_vZx7Nu8O3p
UMCykXy2RTpVgQlP8O0sRumr_130SH-Dv-67U1sDcDqFWNQ9qJ10tFw37pOHEmHmYBYrGA2Dbz5eTWYyZiOQNWZ6xH9nQu0GJSG3yMuJ8Q9z6GBeBqtaL0Xy
4q8q4Ii4CEwZCRiDGZGH3uHe8Xu8sKGi4Bg9s260DiMPI35YGJowYTGZdX2FQ28621MtNWWTjps-5Q57epiWT1Df1WWz6iCF0VJxExLE2uHk8du8uFx1Rr-7
0K8raLY62E2sdOdOXmD2Dv7cXm2kbz4mHA3D-94Hfm52n-sp-o60Sxqq4GU4RY9kY7lS9kw9FFE8-j5OnGXWYD4mG8ZHi440ufw80KASYHWWn7R6026tCnO8
lPqnGCZHYDaS4Fguq0sXjpC62B6TSK4mRiLe6234FH43XDZEE25q4yaZaiSJ-IQIHuYM-O4caaU8ll-99f97p8OFFg_By9v5Y5BseIRIKWZH0GgQoDi8yK6b
86xVHkWEKzP4D48FGqtSnX28cbXzlucyWn0ridWqDAB-JT9DH2DqhDR7BH7fMArh8ezEH5civhSpiOA8r30KDn4YIcCrUq-4Y4HRhOzR8ahVfEmz4I9AOpL_
J-GL8SuElp9kYKZ4Qlbe494v1AYFMo9IiLe_6X5X4AlY29e8iGWtY5iHgmwZaJ-Oh6yYyVODjjy1
}

sprite $image322 [99x142/16z] {
jTa9bkew30HGUROai__j_aEJ8-1NazR3aTyyNfAoImpq-yfZP8fSgJ4pjnGdL9Ox8Lo3W3A4ZoMp102fix0jaNvv9Eq0RCd5aPGf34lcTP7a8mH4Hhuw13Iu
fyiswcUa1OG0aPIz442uD9846_NgIEfq0bztod00cv6mEWqvyXABn4-eB-jPAWjqYezO7cDMEvqGYODOZWkPsJhcdoEPgYv4UhODQ3Nl9aIN0v6PtlhU7ybS
gdMe6OvJzunaLY-HgLWahkuemzqfHX0rMO3WSKljk1Wpf2SlGQb39D3ZTShFhyfaPh58l0HHdce6Xc0xLkRuoQ9qiKYy1Br4WY5OoFpuiTYKWKXE28narWzF
JQGUi_9vhKx28f47CjBlKr6E-vyniNC28n5k5iAhq0_PLVD845L-GMR1fs_3hi4nUO70IF2ep0HtIKuYuLy9IaCV23Ek_2g8y6pbhEPPaJWI_jGfZrkUZkCt
MeQQTn0G2MxND8M5HyqlVvrjyde9IXsBIve9eoQoLTg0P_FdX7M6lXlIZwXU__zK-xHTOPtY8Z0IswxfxU4B1YQZU0cYAeRO3CU7ZmRtx22iKmnvZknKsk__
FKJY82ZBUwSaohLF4SUp-Ueb-AtcPThTzpoRzn7o_qvXnx98U7a8dBn-O_a8g7ateCj9GAVu0HzH16hUXTm1D-6fUGnXVK50fvpUemt24ua1tn94KFDmZxO9
oX0901i4H08X896yX2CI0FO8dBooVbcYoq7u9g_e2Y3eMVCl01AqGLYdF04aLDi6SKIYIqw89NEMBOAe_K4ebJdo5b61mBWhzq3YE1UTwnQXVnEKnop11DqZ
IS44KUCUGBntLB98mWYYF6UE8wnrHeeZB98MJL0QN2C9YoIO8AeMIGXXaVW9SH8OIN4HRVqnBz99oSwPumYBfDKumY899wZeBD44Mys74MAJDuwmoHj879rI
7CJU4qwB98R0clSJwYLiyaOILlEHXDLyB86Hx1DLFjIyYz1l28iacB1EYII8EhT8mYA996po_aq8VKjO93NgAYoIEVMCMAfIzmXAfuJgKbsSjmXgIpyJK_K7
6cc7w6S45NvSYBOmWgZ90v4QHjYd1slcA88eFoE98eZg4OcqAE8HoReZNC88IkD399KTX7e8edAFH5MrfmZ28bcsWMC8IXqYsIGMmSeGoLLNWP4ixK64dHAB
f5rBO2G1X4LYdLA32BAQ5vvHX7MAQWqZdZNFEOA0ceyYo35vVKthYMH92I2mvcC8YqGjaW029cy00PCtW82Q3o1WyWOGKFC-uYRaNbZpZjDzMsUjuAdvFuZR
xQJRl96S4ZSvQMX_frGZ0D2-0Rn5af7mX-2Fn8Xd28Ks5jPy7U_43SRaJYIFt4LVYDlgwIh09kyhSRlDJFiB9w_Tg9liXN3UANS0fk-LaUZ6HdLFNckBe5Nu
uqRz3m
}

