sprite $image316 [295x198/16z] {
x9g7akCu34H5Yg4RlF3_Nxi9hWCvDWUwlBJuAkrMrfj60rBvztySalnzuqkw8cfR4j_JbaHfuehQagIrvehQKNhWUDfHKfn0xIZDH6rebWQ44r5xu0odedQK
_CdRKRekQaU9NaLjI-f5l8hQKLB4cRmTfItgWwIP9MLMKNlWZ1qeip2FqXP5mwRED6nH9cacYg-uuN4mJOjfs87YI_RaEPQSYhhbSS0Pkw8CEaY3xCcZ1yuZ
b9jN55tIyPs8Fpzvl8-b4eu7YOueUTUAeaUDHqU-v-HTd3SZu7wYw5FYCP3lTnpGePuaa8D9Ejb4v5RlBtJ0znmb03Nr0oUi8TvdyYwMKiW0jCRrS6BKMBcY
tk4ue4EnGOiLG0b9VZnmjf9w_uhoZu2UimBwqEKmGddpYg93FJuGL1FYCV3U5SKHFqsvgQOIfZUKQV2_whs3f18Y27H6ahG6e4WZqc3FEmv4blqLYnyZxIAa
Vh2Gmn4AWNgQFNtgb3W9b2pxumn-ZZd0mqXfpKef5W0bcZrXiQLd6YnAZgWbBULXZG6e-loIXfs778BQQmZFIq_cKHedRz5vqqSUpYMn8s38cJhWELbwPcd1
GBbNzqjD4ewHK04xD8qafi7-kPeePx-HFxh8A8sggSJH7WXOo3fokupDvbAID2EeiOy6KLCI0V9Whn5eR8sZrWWdGmjKr9LIYjhELZHQwHb0JVrW4KWQgXBx
5nVXn9CpUKj8WcKYwRaKQdS4wCxJd4LgSwTkwNMlmKAkBEfwSOSC0BqBoravwtW4sBUeapP48csvYlAZ58wH252tsEGJ0UFJSONnYPUiA7vE3azhZA-sM7fe
CdqMjF5vLvmyUW1f_814K5fZZQCzcMXA73IjAOek-khMzV3t_qOIAA6t9m1HMaDDlJus0lQenaeLHHzyfqJxk9twdMVsvCUk2-YFgm2z3apIA6gLG8ducfGS
yM6BvKVEJZi2REa5ExfLaz1ORl9QaukQ8A-tM55xJSNqGKlI_j0q-tF86gA6ON0roNIBGVNrGMDNAi89Ynm7hVcYEatfwGXGJVNum3beCXQTl4jFOffivurR
Z2MCQHBJ93HM5TNQLL6goTvbzRtkA_bceYGj4WBXK4ihINp_rztBJRUQCK8hx8wM7UBwx-FhWcI0D033pBQvscewO2SlDLDpu8hppAFJDirhLQoEZUYr2mJO
1KXPIfJxPL2aqaygrXIhOTyKQ0GE2qyqS-Pv4ntDWNdOWsjeiezn3K7UKeFo4Ep0f2QWRPTSOJ5IboYFGLx6D1qk2evn9ozHxlsWX0bBk4mru81I-imJfhxC
4oPAz9e50WBe_A0YfWxDmwPYqAPWNo00To5fzZu_A_DSqPTvnZt_wdyU309tyarHrBm-vq6TgiY5UbuPliQz4OrVOKHoK57sBfFjF2uhV4vpSF8HTM3YVKon
nrYUKQA4YNT0sTlU4iQ0QNwCvdc8_hRStWDfWHbKcJHfU4npu7uBr8Q9VCT3Aj0kVI_XnZek_e0IvI7wCy_ufYQWzNMqfueZlb-YEjxo1oBw5NIqKLvF5Ojz
E_Ewtl97eWvX2t7aLvY_NQBSl_UWb6znBSEVSvgXticy_A0GcgM50BKHR3bPWWVrcSnRfchQfU-TDm6ZK-C7qNEw_qfGTTHmU1dQ9W3pjiAgfQNd9BcWC_Fo
bwZfTPU-NzZNCNWPTx_2l05xKedYnq35ogtzbVmAmSieUYv5d7z5viKcG4uNyt14feHaz2iCzL6WU1DK_q6dwBNlp0xy2gFzZXA54WOcTkpjrDshyEs1_tiN
DKVNdTODYtaO4Iokams9tiN99lyEC-FVaR54rQ5ntIc1T6jN0A2qldC2A0DSehVN9lBoHvWF5ARWkfCN6CEhbr7qYDA8NgDqFF4i1b2fCg_ySDqjKh4m8XZG
D06jQLR3WYsbBdzsttvGxDkPH5y7WuhfvRZy2W7hZ1SQlFp2cQQBMgAC0U2HYicqM0BMvUSMX-p0b6F4ebtwNeUvOQhJiMaHXqrKn45sOCfGeW3K86Dr6WzK
p007FJHNapbW1tyZEp0bo3p8WA2BUvPMytPwlfbbrLmrVWMrv8mCBc5A0WfRBCC8gLWO4Mpq7AKLlNQ103l-gyYp-xCqNxy8KtJTxKEJWdYgADDieGjJ_7iY
g9KdZ-cv9IfYKhx54K7qA-YXMVDIU78MjHvouffbn29E9wE05fyoxooXMb3hkZejXAzhgbcKC4KL6tSLYytLR1q7dQIlQmIr_LYk4Oim7QfOBUQlpLK9fiNJ
uFflkFis7D3tyunOuaNYqghOzhrPejSi4D3Jn0fJZ8HJOFaLMXNZr8hU97p1j7WUVe8fsOeOMzJeLzXdKJF573qJ6vvWIfLvmdHiMfngD2rsX7TGIjCS79iM
npi7dJocb1HKWyd2Z63nO5hiYmvAEPe3OPBeQO4WJ07I3KofLyG0NDt1t6zQxCUKjKHjAWRvEeRQOLhimPGT5DlkuCzsxY2vYXW6ml06W6dPzxykEsfg42-_
0qJjMBFCyaktofPJ-Ifmn_tNJFkjMFIuunOmrP-YE9CgcVnFKM9AwqpQ1Ke4IWnfdUcIulCqJ-mGiCvayb-G_b7pX97McQvBdsL4SQHr9Xue_yF1_sMwjXfH
LKoxDQ-22K21tcqFnPakQJ5B2WpWtZpEnA7qQn-wPk0FfNJ7-tjyXPKK0p3vD8yR8IcntsECGPdgeVWEd4D984fZ02R3vd4aCg98b3YJFrGCzEa91QA4cVoR
HuXueFIGfqprWU9ASoOwCt5Ae98eOIP_gBWZvKmld2wbKG9CXitZIZdJJEPJ0YKzeaIP_A46OBh_-4gSb4Q9C_atJpUD1rFEfok5IgB4cVoXOfKf_i2TH0ap
-JTlB3E1Q0AclQ3McGQu568c_-PnficOD0PWyeRYisc-eHGuIfp9ltbwWDn8SZpnA74c_q2Dn6c-a0DH0apRGSN3AVkIBG5OC02cSgZtxWVUK0eG9S2quuWQ
8vLA9pg84b0oRHvtUdquYCeerKC5tChLHgc-UNhFZlSIGZeBIijHchCKwDytZx_JSTSv0TDUKFpLbqS9C6ryVv7Y9f0OmoZLCzN_pK40f5ec_oVY2PISeSw9
KlqJiGoG_9iNl6_dGgaUoNz4AUhxvZ-YL8_atpm5xjl1KAf7yc-U0lVjO2Y3llatJu6H3eOoGF9ldg9yAFa7YaVfP2X5FPB__SK0oNz4gNme-JUFH-beA1aW
-O-eg4Vo7r7rKV9l7e_IsL0CwNWdT0XeA1IbXa983OMGsWafDHH2QYY4r508gPsGKaCXf8P2IErqGm9AnqA1A3NK283KKAXkxOIK6WeXDHH2QYY4r4x_HUad
}

