sprite $image19 [126x306/16z] {
nDI7ZGCn34HHPw-6nBh_RWz2-eVWD939ty03gV2m6hD7Jvfsbp-enwQzO-aTy--3A5gMJcgngV30YTHZKylIgSUcbgMJMWOdjTYqjzYqmBuCFotvqltkIsww
tzvYqugbrnx_MDczPUdKOrFBqaajDlNOPBooelMFYlONTfE_ZS9Q1gUm_vVrro-Ytl-lX_hycDNpGc_nT_GM7xtd-D5Rnezez1NHvYiJj_Zu5ObUFVwqqMjz
PQ8N-uf4h-QdZLxcOwEN-ihyL0_fLmUENZO-DdgLhoHqm_TiJmzf-O6Z_tvyR4l7zvVkw_Z-qdtTvx5TtVS5z4ANxVis-lccJtav1_vQFnrEs-BniJ_G3uVp
MEWBuHDzTjKYNv7VwuVZFLOS_xGD_R3Y-9NfwREBF1_RqEbuytr5UZhvnu_jw-xhKvAddsxtatVysBu-fEre7ByYVVs6hd7z-lMPzX-lTQAaFAv30VXej-IQ
zt_TMuHW22JTSwTj_E_hLvQEP1vwJxsBNbN-VxT_uFzHxxrjrQTMANWUgo_e7j4hwCOhNKpVEbtjXfJXv71RhbFhMRsddFcQYtMGaNkhtlZCjrgh0t3oxBsS
JdYAvJfi-tnPYfCZRRKETMwPlPstlnRh0AbPxprEo--rM6VbwdNLVcwhTKZJgEfvtlvSh0CmjkoNqxT4jxjE11YY-W_jNwT74WpKIkjw-SxNzQvh4JQJpErg
-Kekkhl6GzVDk6p_ajHv3HtUerqltnMwv5C7GyNpe_rCe_sJTN_L0QN8Vcm_jzgxeJbRrpheHfpT3zDdLHMFwPkiIxpf09E5z-wxhrMLXDrlYr8tT919l7po
pHSTFbNdKntHSonVRYcOfykBJeGp7SBMMetsBzAZFNGvw83oDlssKhUYAvtk7xrIrkbZqx9-wB2WhEoDL-bHF-W0r6mitqcwF7NzJUVjVIcRfckseNkxwNIf
6oJDgthA95qyZzk6agzr02RUjkcVeeE7BjlTxHUTecxbTo2-cBgXKokhNgNjxpeVKwU_wm31tQQyi1b3Xn2CWavq77J09MVe4ZbqzvlGv1VT371upmcLT_zy
ON_MlHWECEc4okVGfU7VwD8s7VYxBjQ67daJz3SzagRfeA5h0KR5PpezTQtzxZRtXOsRmFIf6pL_wa4hzAXTEDDpw54hTD5De3CT7aENv1LwDC0eJokVRUZR
KpXR5x6jydQcmtFeLWoThyEk-nu-T3Bwi_xFfsvoekj7waH0Dby_pRpSAs_nclaLkkQbJdd8_0ezscNb4VcQ-QcwZSnVwf3NpA_GDIvr2Xsw14tJcOSUzQyo
7pbDz-msKdUjFpElq8cLRxrurxqTT7_HAP-wJwoyzkuEslGwwZZDF7pcl5jgM6yGeRVKlUZaZqthu9YyRMu5406kzMnFdJ1Nf-obF-dmfnv9StL8fbbBkRwx
3rtdRniYqUn5LthBeNiisRJUkzvrUTT1DlH5Rnor7Y7DplJRqRtoROaE2FnMW9_ro4KwO5GzptNQTIjUfiDwkQhJjHwqJeSeU_LsgKTXeGwmHkzofSkyllEx
JavWvUhX5peHrkaLO0K7N-cjhTCH0UQVCq_BT4x3BnCN2okVyQdhCVCBTRTVT9sTUGeQbIy_q-cfnwFoFab7y4D7Ez7DgWtTYoRhzD9tFT6rznYLdtrtQZJq
yXETifViUil9EfntNQ7sgJkuojoJuR1rbLTIdEaW9izUv03Fhdp-dFbzwLhlvW2cwPAw9OdECczqrD5wQnGAqbbwszgASVUcGmzxqw7ajmBCqfbjLFupy_Ik
0qxLatLgwcJe-DYqVDHXlRkA3Vq_dQitheP-SqaewQX3ZI9xcw1Bo557-j2RWWI2DnqWyzvrWfxjeVD6KkXDDu616Ip0cSxLM_kxxl7GwNNUpRU-N-hWfl5t
lVnuT_Ye_5tdzgwFdywlF9Y6thRAEttgCaTdqg6_Pbu81fMhokia7JZgTC-y_zXtNgQ7RYIFlliNzUSRft022pNwdexOTBhfeT-elBted1iP1lrIttNeuurZ
VUWatzJ3HjytdNFqNO9WQojVRxiEZA6NGjUchcswoycyKnFOMftuHggVw5QoUjvJxkI9pgMBTIg_rC6yMWyR-l9vrzReOjD-GUyjsq57VbFFrlbLvwPWNg-F
ay4XXzITwp9P7tuhVacTNEYiS_McjVte5IDrLpgBJjus0VAxNy6gU-MlT4wTh0CSU_cp70RYIzsIf-jGpNiRecWZhtGfdQ-RgrNVZZlaMeVAL3sLRhgxnAFz
cVIXn_ZfvBkBRBgRjBuTA_-U3b8Mjp3VsryzZOaEkg_HxpjMMVrsr1_jpvHlwQQYR6vkBj57_DVhZG3SL1LsStVRfw-w_gh7NtKN1JPLbCLlPqnVawQhz7_k
EaY5tNTVmy96-yjAc9Vg01dBrdHLPVFRsQSlgotNSLFrhev2Q3xARxPMDx-7thVutGinsb-jnIgz_B5fJNZREQPAU_bzyoiwBz8R-uOTGg_2zz_IzfX-SZxe
CaS799wX9tKBEsb_Hl6hphDqmFpHwx5pjkLhRY5x-wFQahi3K3UsHzLbJF_sMsFvbel8hij4dLGvb7qxzrl7NeZ3svkPFb-7oDP-sMgjpz3RcBwyyzvviZwE
-UEX7RT-VtkhXuEdwO6NusvaReUT8_huhT7-RBH2DspjtpHLqlloCtdyLjvzorYZ0nfxw9zFpllRMxrqZKucvgnx-J_NqEFjzKYPhqCCDAP_jFza-hnehgu0
Y03oU60wGl--VBFRT9qO00aqMEA-SvIktjwQhUD_lPm7akKi38Ibbi1fmlrF-mVPSXdZj-mymL1fyrTAtOGjanYzJ3zkMnySvUzFfvqkIPnVUoy8yr0w4aWc
7tNNd2CH829T1jA9pVjsyKqtySKkZVtfVD0De7mjlykGADdYTHZTHa-PI2QzHEtJx_GncRTbzAGclaNJWnM_GZVnktilYA0yd5vwxwav8DFaC7tcF_QygO_z
06VvLR7_9SJfefRXrtJ2yOCqdPgZ_NfUXKKRcLUJdzDxeTABRblQDfrL23cvqYewqQs1c_HzpUQziCiUwTRp8gN3rdIs7oJpNkm_xgUqhDXXyf8EenEcnFsL
5fgE3iUhp1jT4x8EK5fHOjKM7SaEFZtfJf46tNyWEIDEdo_an3PNErqgg8y5h4oGF6tnbn7uB1tVBOIonGw-qU4_4ADhahN37VKXi-kwBZjDae_Uwym3IBJ4
wKIxpax-tS8z_QByPpfH3xhXGOHbNKy8gwJVegSa2a8Mkax_GGVVwToDlfY0sQQDRajqXs9Wx52cT9nORtZMpCT_VCjFTExGyoINS_gD3mLf6aelxiYvuekC
elijiQJzOMXIhSgl1ns3OgTKdDFhyiDYP_IdAwpdYploklpPJRztvg6i1_LoOgscZw4OKdUHXtDwLNuTHAVxvTJpz3jTEjFlbrFfrVJnwR3IXRw8qSkcz_G_
b5ztCAdH3HwWsqdkF1vRzhDF_-Fq2KdgGlULpmjnmAZ57NdDrwxqRLLl-kfky7dwUj4z_HTOSKUUipvxBuJxqDrgZLfepYb3pkLfcTYy5v8xqhUrk1ekxyZL
nJVvvWyg6gMNQz5ASuhobzyj54KlkfSV_Z3aKL-cpxPqr-yMfdvqBt_Tz8NtodBP-FQcU_czwU_JpyHCu-WclkN3K3xdmCLt7DtBx-cllNSqVLjpzHWjUWe2
HjAz_3avjVRUaNGlVztqSav_bFxTuhluQfL-a4gK_ltTmA-vq9nyJXzieuKOlSrV2kzDBaFMTqXRbFwzDlYpN1wZo_r-D7PRNmMj8RukGz6U_tHwk_pLmn14
-z7RvTUYwISGgqJedqvly0llzHq7zdlrT-cVTtWx_TTtGL3amu45-utoXvJsq_lzPtptteZIVZhx3RnxBqZ4wQ6a_xpy0QNrm0DyTQNDrdM1JdzSNytolw6q
doumpTNsta9fO-otfez_HY_WSVwY1JrUy7ArlLUTtfhmhsT0aFztFRzzlxkYz4_VHepXHmeUd_w8iiN3R_d9M7w47UT72XwVliQ6UJ0_CcNnz4SA7Wy_0e-7
7x6oE3y2Z_CZxBZuNZOljOyERxz8iyNJ7v6sE3yITppz_y43cvTe-6zt-hy
}

