sprite $image105 [338x235/16z] {
xDbLjiCm38JXW64i-RJxN-rbSCemfMJ-zmlzZgJI-YN2PsjMAkEx8WfE-4yO94-UgShuYx3woh2h91Z2mfDMNvuyKrK0y4nLG1F5L0jF9jN24qqLpgcJ5zEJ
RohFmwklCYwecE2e0shkakDw4aNbMTofeZgWJXRLmdD5jV1SKNaIHUK9ymEYW42lytJdVR6lXTyKJOj-Ovefdgtewlet-rhuLdGJNvx7yztj-utol6P6iJDv
NcPww5SAz9Bd9Xmgo_DiKrloH_mHbCoR2ewc0Jt3jE2KYZnFN7t3gMLvdc1gE2TvyXCeFPkBPy7Jr6a-wGcKdppfTVAajtfDpumdJWCgKpn_uPKy4wukfnX2
Z2bhJ1dpcSR-ho4at2fV26WS-cd3RKoBluGeRpxRniptD7TVW6TkFTi2sTJSNq1qXMkBay4CBUyGgGl_tUmNlZsWqMgj5cznJel_jg253wL-LqRwEJN_QyuB
dqCxZV3wcsEWdbFpfgMyOafUsppnpcdnITE7CDS36gnkPg5T_KJoR4NnLPxZ0HrBdSGyf-PxHFDJlJ5zv-uyTDjeWXWSNzao3FB-R_iNHM3M2zCdZUcJ8gBy
9QuVXbnk0TA-gdS1McduIQZlYe239ucsKI_Mc6QUEavBrl373oLVPSl90DMA9Hsd0K7qgMwXgxKnhMrW9xCqsQGwFbOJUe76n02LYltIKziYcbHcI7jJgY-m
vVnSAClRKl25EEqXW0h5ApGchRQG-hJPNzFMZnDkeS_ZAHgJKDycwdtDnMc80LNwgxUSMjX9dKBDngdWgVHYZOdiHkf0kftI-l54x_dQ0nhJI1q8W9lzN9n6
kqlFRlYx0ZIsYJeYm3aLSUhN2pKcKX-90X4HICHfNY_HcD2MYJf-8mrSe8BBbjYOFltRC_SX_M60pjIlWmcw_o9iRoTR__aRazvopbDxOShbYRPVnJcVMyyR
eFd6XBYW1Av_rjOBU8WRKxl-sYqd6zCydFmtDe6b8D6aJdeUNSkFfsbC8tM0m_aJWG2Rm0Y-BSyMfxNyhuSTqkl6X0WCQpmO30Fu9snIfVmcMYUctVwiuJX0
T_o9JhmtV0JO10YUYYUAqpAeVjiPqsrRpix9957Q7qGtZBiyateSqbhgIBJyU6HZmhNBupgct21HA8iSz_T7_FK4fjhm8z9ouVouneIuiYHJO3Xy_dJSKKGv
FOqfSGwgjJpoa9wM7vdEZKahjZEShw-YUlkOgI50ius9I5a_0Hu-ttR2Ggtrz36DwBMucUxvnZGY9LFHcAJw8iBq3AOHagd3y0nGhRgG-d2SJAI0R4nQiPw2
D1JH267zam_fhoUV06TpIiSvGBMmVp_I3cYYOOlJCjQNMnhJbJeGk4naNAboDPgsdC-2j0EV4dN5wPvvrZ2wcrJ78MsB77UjCZZ5hy01KLESbcnZcc8K68Zs
ZG6QHBhvUUA0gClwIxOnJGkxRamvu-zsmyz4Vmr4ZKmhVuMuwLd3E9mHCzEnCQM4Foj-DV8CKEC9o4JK4wSakjntI4-FSv_49i2zVaQn-ACqz1jf4ftKlX2d
ubn4DwQHA5ZkfyQKLtVxlWCpqLy3RHArMNyJ2vDyri3CHF2g4mUDARSwLIzF4ctlHAAJUiqoNSHkIMyv0O23EXpIjo50yy9YNEy3iyYpKIIQZrEz0oquVDPm
xPvaAhQSUJNRaCQDhyv3gEiupT_JyI4eXS2q6eb3-hHMpv3s6r-TTmHbYbDzCefzMhZnyGgF-l4XFJv73E3J8LtS0ze__hYW776gJ-_dnaIaqmhFPmtKrB0a
J_wnIj9YHHhgWu9onAc-OUAp1WxJD9oGX_G49fWU_77HjiypZIw38IX3dCf3_620idnY7bCsfZq-650A-7dV7tTf-toK2fwIg3zEnqKg8X03LOH-rZ3E80N1
Kmmf5bibxGU65qGDrfUlIKWG04TADYQDxHROr2Q2DAEGF8-8-kEKhCPtDwGW6jCnKuHoFBKxTw9T6VwOg3zErpOWnNJBMHQzvLJqD4-zDFdL0mcYdZWbifW1
D7t6fEDK6NvMJH7Drohgn3X5HEHkvH231CypYNOWGPHgjZW56Ko7z1ccdFVJNTy1IVJiE8LeJ2ccWgTOcVo6rqJzrjVlIBzonWJDCz6Ul3n9zFGu5G6Q6LBS
UjjKlOOt4FN6QVQG7dV6ADxyH7l0GDIzsIzyrf3ZgPdgVRtVy9he-N6QCFpKGASwUjPItm43KL-SJkVHwG45nCPK7kBlJfv-ej4DSNfF3vtvtRgj3s-C1ZxL
Jzw5dXcdRSyuNtZyqFgLXlX-dk1zlTlwfaVbsl1wT1Ecjna-XZSbQJLBdBOiJytKR_gEum4bKPVryzTx_MQakE-FYpAzt_22QCRw8awjInH0OFVyCHQFwViX
JnDHnccoyT-pH242kFUFgtWwxWvGCz7exPGbwiu_ri-U_8RNHC-FqrKmjQYATSdBKn0zCqxr4hKq0rCzedx3yxMuWwZjUVI-Y3drZwY_CKcYvrjVCzt30pJ4
Y1gtd5wY_YMAMYs3kek5tiRJHzJVfCYKshwKg8XMDl48tzMOt4JzSLhtPO9QE-v6YTxAlhwV-0JFunNUITHlVVqNicsrnurJUK6vl572yqx3-udwcPQDJ0Qi
fVQ015dBlYtyD07KtfZyHFrnoj8lqAphjk-bb4lptVTjMybHQjshlp6TIfHgAQQ4IbHvBTjUldsBv2VgjpxjlwPHhjjUwWbRplE8qleffbJbIdCFIi7IR7W_
Kd-SQgpR0TTbkGHipQ7CDoO_Kt-SQjNhMZHe-n_Zbpd-owvvu3WC0p4GrMf9_F_NNkzTM7ddm91F68I35UD0uRzFwHtMAPyMvybNl_mddbCdlO1E9y8M_cqg
KFsjQF9yJfVNQVp9QPqcNA02bnHGU00ffbE-yDPfdATr6X-Luq6ghydpEKsi-lF_oW5CYPsFlvYiKxxmRtFHqMdy0lKb5TsONFtS7wYPyZpvdOyTwQrJMg3p
QKZrvGhFxto5vscTpWiKJ0SUfkXd3TPflF3MQRpmV1gfKtvZajdvjW8LtW_J19v2brH96EcjKq2WKjNVIcBXVKd5BoO-Wz4fi369xtnB2s-TbjfLUJxdaghJ
qiS012fxIPKwxh9CeAv-UUpreiARQQdZCHey-U_voWkt9Kyaw_GDjsz6-Yc1-cVwbXjGU2ufH86BYKm2KK2WQDA80WAbaa0K42YROua20kLJZoIAF3dvjEE8
BX6ecOw_PXVE1I3QT-tKBABpXNVr9mgldZIYTR-EtBPZ5rS8H54K19Su-OVB6hU6iUeGwjptaUhqwuCtqzgJQVs0Cgq7YhGUADFQasdjoRH-GFs8gWTgfhMd
dLxS-vhYj__prGDr-hKdqnT0rOig5rKlgaqkgbnKwrnKlQXoKHrpKVMYwaMLYsgTYweNLI-gN5Izg7fHzQBAHTMBQdCbkeVIxBJsP5eVFDBQa-baG4y
}

