sprite $image368 [354x282/16z] {
xDm7ZiCu38LXaceabVkVTzFWHI1ev76ehUy_mWVWWKuneO1GCRD2-qAbTxSij2y8F_DMip3j2S97xjfQoLc4OeFmcBSQlHqG7lDAMuDmTrg480nX22C8G_XV
78GXZ20COGWZ24COmWZ248PmAUexXI4iT4zALTqd3E4ZaLIAgWS9e_eM7fEY_hqmqfVm9AODGHX16C88mX26C88mX26Ck3NUA8ogtSkxX56sTsc7C1AreoRH
meYhVLGvL1Xb6yfnmYYfsPYc664apIOr3X16rNwe1WjZWCToZ30kj7cQhWeZRdQgnX2-LB7J5GZ_lcI_AiS8uqARfmBXyt6r2rM-88mBBNug89pKhfTYX76X
pMjoGHWNMjGSGpXRI1d2qmijA4r1mhZGpZz8GpXRS1N2muKMNOuHneMsVf26y00SEiSGbZACH62582pT4sNRLYO8zwxCrNRL1CBtAedQhYeJXBkNhLC1uNik
L6nR2SBt6dEpJRb0-57PDCVURmd2ppplcED-kq7uo8IgXUQtHn0UvZZI5yAVUQ6aOGFy3i9RvlZmXV2G2jUWWO3mf4QYCGC1uQDnZYDy8JpFXNB0G43uXvIv
HlX2U5ubqUy60iBJhdskEVX2U9a9bMy60iBh6dCxFn1Z4FQ-gb3IwxuGbhmqNZz8_-GBOQBQLwbGNGtmF0WJwuavbZOTY4KGlYVhgPZCyT8NmlIgh8qJvN4W
JWJXTtsP2jV1DqOOmkFdckC0huKXN4_DyMo0ry8GbZDpB9GN0x4Gfl-rC77hgvIvtouAG_YUQ5ybj-l24BwNVQimXEyL24VKvi84uU_BvZyB6uI_ITHUmdag
JCKX_DrVcL-0ZMV2H1N2PqkgCloLsVkhCXKcLWYV_tDjuxUssQTmzpmHlYSEuMNLtkNFTqbuFpAP2Dyh3k7pRpT8rVxiGwxnJ9W4mXVU43e8TuVmrG5U2n_D
XRD3U3uGvuLLPi8VSmpXusPO2OyrUiQZC763yD4VxTs7bgIu3WPWPqkotlzrRsYNeCiSzu9Qi7GTVDA46x-X_bKmDRrcq0Wtoe8w2ZiNy14UAZI5S6iKPiBE
9L88O_myuOIe4PO3VYiifnuN9gnX8lpXtpz5rAR6K-6i4Lw_Q087uK___gaviRKmObhcpX_s3Q5wus0hZ115-CCgDBrnzQR2Y3M8y8TLQFh7E8imcGWZ5dFX
wyVgjiQKkZ0O2QC8Vro5fZU6y0XFAZIxE4x6mjL_Q8McZsDZOSJyaHMQtjXU635zR8McZsDROOJmTu1zCIIU6rTROSG_4yT0oTSh7cFAbi9_A2gWDGWHBZ4E
jiA8yKy8zm8euILnx1N2E1V66lw8SAFionN4ZMo54Ok_lt0_5CCbSMmjZ9Z-YF1N75j6nMN22F7smdAATHoVBtp_oYsAmuLnR2-CMEuxaDXKL05EDtRsmeZf
hWE9DXwmZOhpXEyVnnsoRK_ssKpul9IuVHo7EYSmQwI9kRNjYUR2Sl8DLqQph_6AO90GVBKmOhhTocY-AKucNo5C5miZX3kjZ4PXmygDk9-Ow7pXUpNI4h63
i6qS4yk9BfmXVEEeA8XRuKoprKG4NG1VBJoUU9ETlGWxLmpZM7nNOGXuiJ3MS9FtNaJOUJ2AOsBU2ZkNoLZuXd4yI0t2paMQ6CS0Ye0OX9qhjiBtY-E4E1Vk
Pnh7FYfyHs7duM9XX7XnXJONbZD4nS6vflXEXELZOY-iQQJjM-HTmlc7whWU2U1HM4wzM1YnN5IXxHSccZNI0Gu4n4GucmdVA8uJuX5XS9cELsxYQo_S5CAN
Dj81yA2ml5nuOAv9p6S94og4BunZ2SzZmiu5FD18KsDpuTLN8NpXN3Fl797NKTYvjBEHNdtjXHkXGlZ2E8xxbn2KL-4LOqySYw-niFYEXyZWRzY-zhsNTGMw
2e_4yqQQcCyILb1UsaZxSdYH1dwVy7f1Y1gV9Qp8WckZ8gbMbMKZ33_DDSNNNhYHAQjz8nr1kGmc78MTcrPkXVS9vzRmcB2jhtqS-_gBTVieFF-wMpWWt30C
mdQ-ryTn_kM51lARqYtIxuHx1J88smJmzN6S3AwCv45OvffguNxoAcmLmDV7SQWcbt8eYN1PeeT-BTmeYR1rG5pLIAksxxDIeGldONAi59O3uIVXXjUUScP0
xBcHiX46qWlB8H6s3eZpupW2cWetogDmTlcuCCMyQvjlxMi_rooe5oQOA8_2pjV3maWJORqlr9hJSagjS4aSXweM1XTfdx1p0Us5sswEdC949CHKuEovPWIj
y7pFN4TXvn8T4qQYKLWHm3N77KzRI4LXSA1oIshXwMA3yYZiN3acZ4Y3yC60W7p0m8KC9pRIlcY5vuiD2gEmEoWy6iSZ0G797wzR3oCNkpYU2yyN6-1_AIp6
et0ZSruviPnNkKMry7maN7ubF1B7dRubs8p8xHlfP2xSYFJ26-EuAu2Jjrj3sCTnrGj3e8coMdWqZZi2EDdkskqRwG1guMdb1bufF1f7RdJLNZYU5yT9Bpox
i4rP9pmI5rB_WpqUZ-PwNXmNhV3ymZOblV1gh9uLXAgPEYPb8nqCKcWgFB-m3K4XRFCnzKKP8L7HI7jWvcJGIC-5dSF9NFDCuRBhKOnd4sDbvfrTID8BmtIk
UPPmzJkV5GZd4ZTcyWUAGhrmXJOx0DR240_aNV4d4XCpc6tlw4VXx1BDXD5OEEtUdslYk1pW9MQolA92FmfBTMmWhAxGJFR5iFzb7yeKJBVyHDN_8EnyDH3M
LsXWioyEUmEOgtFHlaVFYt23i1cw1rGB_t84xejPcrlt1J3wzqVJRgwPribFtGxT4vqdd7_LB2JBXvWO9PfUqicmaOOWmetoAEp0G5XHeLcskN10E3OkYnb4
gqjjrUTriR4L9esmNONswpXE1uHX5PR_1fjn7dmJzADm26Gjd1JbbNfVx7yi8BZHAknn5JQSQuxhD1g5fNAp4YvUyxpfu_YzQdZtXHH3MeJ3HXZHh79hwzaA
ErVDXEk12itc-avzBnhgyaD-ZRxzN1YYMOD3Fmkx00fXNOLclI-ktv_Q5liptNyeC3FXPBfTeQbmFv5s2pSw_g5EfztqosjRyUKdCnwtdBGHpkkVdMaZFH6M
irUOb1MQ_iGz7rr91KGSHX1n4FPr4cS6SMmWJ9ebnfctAUiYtFyWte17uPPU3t0yQTbDlnLk1XMQRHoFmk4h8qBFtpG88wOugGCjvvfwuQO8Y7JsnMjSX4D_
leXxscPY78JDtkcF-ADnKGhJyGSumDdlmNXPmX86LnWJDkR-6zH_uF8gF4sSi-QQsrjLU3mWm2kA6xEBrucO4H0HMsrSdSFN8vmMuVeIpWSgDAkv9iXSSnK-
6X08Ydc9tNimdfWf14HihnabCViU_-qbImnIpvGBlqSbhRErEWWVySMYY2hz6JymbPbp__mpzyUcSUk_XQ-zN2IgBYWgD8kv9iXSKuGh7bnf58i0rW-3c6iV
IwxLMkkkhhJNhm0Y5CdnQxzEfNXOvvfTEEEnD-AA8gCiSvZPTU5ILk7IXRbJ9zMErMgkIT_dcY9yu8sugghGx6e94VR1fL7OGP7ffg95Dc-avMGyilC4HOji
MWz7PldXA2m751MQUICz5oRyyNX5XMRPqtdyHs5G1uJvN7CKLjwtpbU-vOcy20SGOM9mShn1XMOtrnJX_I-yA0BOTBPMc2akpv088pNtEicWHRQEuupxBvs4
YogqDFraha_m-sojolzbWmhDEeupxdvb5Ywlq4RWcJ0Yv5J0883DvveYt4ZnqKtN1R2lxUiXO9e8srHezdDD4IRSSmw4lN5003D3_7gAFKo4JLfa-xdcbp3f
xxL7kE3hJZBpgnxpIqu4sWYR1B1z73VuvUELJWzW_7RD3nRXDWZdortjFypXp9tHj0W8pBpgLH5sDQGk7E722ktSnSEvVuB9JO636uJxIOs2y_KkVsbWCXIs
Z-Dv4I30VYkS46EvqrzycKs5nvFEMTt32xXosWehAhHxnx6wzjPVyOdCfGFJzXdE_rQ5Tjg7MHts-glprFT3dd6JmxueAhIRnx5NrDxQ2Yt4h-UXhunIAsuH
fbwYfHi4i7bj5HL_WheB4I2tFR-g1UJuTjsd65PevpVIzXVKYqcBNC9hr1jV4Hoo24_-wVW9SGo6jVUy24ZCBA60s6IvoN4LrWR4_UCuMFwdGt0JO5f-9zC2
p6z9Nswjgw-jYc7j7TqKUFkpm5n4U1B07nB7HkzApICzlWCJzt0et7SOuGOjyidVXs4JzlDdKEv7-VuVq5xU8JZddJTeaM_VI2T5sE-eq0HLRl5KpBvIG-Or
c31PjCZtRwIzelRUyuSKgQoteaf_pQX1uRIKS3Ojyltdcl3Bi2zkrc8Kb-IYzUlbmomrckKra_jNRg2klUVFOEabS9AxgSlBXuNBUiqakxzxofd4BltZDPFE
wJBBoA5narkgisicdnp7u7MrT_gEMjw4KHQUheCoW-oJeTfNQFTlf8CYxByN0Qcn2AV-qeL8oszpLBJ8dnJ7oHqzttmZCcDOJ7sbHRWdq9h7rakC-pVI5eEj
mCnfULQh2xWAoqNh_lkAQoQVr4WNTHunBJU1ARgji1nGN3Fvh4OwQOLHHX3PkU_2cM40LbHe7nR7_dV2xbquSLiZIxt4-B2vPea6mas4-mfEySrIdnp72Ddh
XCDMMEOU4HGXzD6Dz84dEIJWhN1T_rjhhGPBZC-QQugodmVFrs_vc2krraPXOawhy2TLQFONXA2a5BOuXKigi7nTLodlmimyV78-Be3jxsj2bGElhpkgY4Yo
HNuJTinf5Vxq0BQ_hqdSM-JQVnZSLZX8lDIJM-GFko2qVXzQUka9y20iOukqgnj_udZqbLYes9YJcmZ74E3Z0yB-lcRhYmeHPgaXC6s44GvNQ4yS4yiBiijY
AFOVSHk5uSWrawUHNWCYVOyQkVg0jDR1IO2FjCXF8oq1KTwxbzSaBQx2hvUHetq0V_vSKrw0atbE3mqlMqvw2IEMb41JeJrnt3EtEp9pNhCXaJpTGTyYFt6y
2bVkZpEsTP_Sn5xVmZsDj0X7QJWMuS0K97RqIumdAbRXujnBkBuldSkiGdjEFY2y029zty55br1LeJsDz2ZylU509oTLJOlyDD9pOLyRuhhb3Afh9aySpuLB
OyP2yajXNuNsdB9JEFMRgW49rZyRNG0_ZVGeB0r7Y_t9XPIAJG0_SIp2eLzbNyBNe49xudZiEEgQlcPBZAUHNeLHG8DbY_p4iGYl9vWkCPwvvYZiYsM5ziJn
A6pS8Z-Dz2WSJLlaPwuv2dlRQoPFL8p2nR92UquPXTDP5TeJnzo214T-MCvef0c3hwUso4ySrtChjAUHFZM0dnCkgD2UEBvnY_nV
}

sprite $image368 [177x141/16z] {
xPk9RYBD3eLFxULZz_k_xXKn6Q1k3BJ43nqfP_QPB9zglbYsgSRxqoNXLsMgj99_4x2fcP8oHwyb_GhWhzWfglNN07ki_G6l-GF-0_u3Dljbm5DKxIk_0rWJ
KgcjZodKxVZ0eWd_ablv5S27pH_m7t3vNS1bSfRV0vm7AUJ8lmCuDQ6SGcdf5m1NnpqZrwC3vqdA9UGiHmPEtN5la7iwBB3BkuRIZWbS9kNdSDR30NifYqAE
700VHjv0vOC0LmbmOvKT-6ZohYgNGm0t3NW3bJyDt5eBX0XK_ZJmi54xdqUM-c7WRiPUnmxaMJvymgechStdYJLz6bZLPdrMPPhbpmEhwNZA2wfjdmTsPFOw
oSUuTX1WL_ck5uvx463Fh3r4fkCU2zZKIrnWmz60NULM9mCRZW3SRKwxHPRQX84D1m3UEXeNBuQhVC7Tx3Z0re7KLIELNTw30GCzKjbnZmVShCcYygpDvJqe
SFf_bVjmt0WO7mP66deJpkC15xa21iXZ0-T1gkGBiFP2Eo1mcmr0waAXgexq3xW1xN30PPASnRSH9s3JsY_0I784u7KfHPBYm9uBCBgA7GKuBUtZ1NZcVy13
KMaHy6Pf0NxhKefNPHV9le617fzmVG-mooi1i0z9Ly2e5W7x1eZwcHKbzIhMBy15Gs1A1rJVk5-FaKTw0bY4qbG_jg8aRpe833u2zlVvq7vzFMGJaSV08lw_
yP-a1xYX5onF0LFQVsDldp5nhF9ZO5zclZva3xSDiShj6M1VShywOYejGevLPWWi5s1VShyQM5LrjB7NYySdx7crokryOBrDoYva6G-1FPpbbGLOFIPFghmR
s5L-NG7MVvbjF4HMivrAl53bzeLtizDfzqiSRRF1dS0UIdrHBwagDDKdLAQU25Et_S2nolllQgYrDA_NrbqOxzStIvr5R0zmhFB-NjA1WNAhCgEDwWbu4AYq
lS1hYTilxpKm87TLfkEUJnX06hOBU5LvVo-v0azslLAv2nSRRe5HmfbExW4BEVF-KlOZCFAq7rLst01unLK6m469spy8gR8wC53b7x6hlEpNtU4GUDkK5wmT
jojstTKuqSsCUSQuycAqkUpNxv_mPY5aV55e_o3avzb57AFrwxMrE5DqmeiDSYVxIrmA-h5l1Hp3Aie_bKr-0Cx3Pbw1NTuuiShxnsBzZXG71ggU4m2h3kHh
u6s73OlA-yTYlMIch0K0XBIxmCPn1HpWyZinyYpxvqnLNfK61-PCusTWs-RLzZAIroddy4p_YpqgfoOCWQrwR-3f3WmKSU0rv0NOSRd2ocWrNmkQIkrJo1qg
fqw6m42xdB8K1mQ6_GWimWlmQWCvU_10PGvwLqhTiovnOAGhbqUMB-0M0Gk_WHSRABtWJd8Nxb2v2aDWJ5wgcUfzO4Vct9GBRiA3v4x-g7AAQbiCx6jg3-iT
O0yvUKV65B6NNTTwqo13u5Nb-y32UqrObR2FJ9CIg9n72TRM0J2gNIs3Hm3y-0kdpBiF8an6kwMU7glC6s1jroeBdmAcjBHKfB1YnMTCjGmyKPNPhu0jNwii
6WB7nRy97vbPA6jesifpNRnNbMapdu0BWBu7cBEiDZokM8Eon2Q0ae1U7pSNvCWd4_eP6F8qCAMj9n6UVtp4f5W3YXLWSEJ7LPd-cYU_UucHnKBWk9Jr5JTK
-NeiKPC-Ji3TWSaUZqlh-lSR66Zy2NYpyF3y2ExLaBLGc3KHCNw_QDbEm9sSvJcLUGCCJ7FWTMYBIraOPrWaDaaGRXEdp3Dm5gbFJqsy1Muhy6QCv4s3t3CI
JH5QHX8Je2K7xbgw-_Fq9C88UErxEODIjYGgra8XSnidwh9rG1hGmgN5glAgcp0lm4lVoxx8ktDKRjiSL6dG2OmJi3OKcMNNOl3I58ZvjGxXprCGMrpAxeII
pxnMqMa5i0R8Lb3O1XkYt2znx3nVwvZSLjoLDtLozymv1b2RPa2B_sa67UPpAfFVRJ5_ce8udfCthiOS0B8vy2bz_oOs3Qu5mu6zbDqa1QNisI8njWAayGNS
0AGHbxBdInmTs6rOXDWjxpLGQbltXYK38YKtwI-vaK8zEQmYQzAUuh2MxCxPf2UWqJBWX_-gMnwK1MctmUkybfKPgDQ1xi2SvR-zYY1iY_axdWAhM_CDNWTI
rPIdjF_yUJJM-CtloukyDPHs1aQMmPvUVvqc1WvKZhjFdKYity2DCx_ZcKgs-BPRNChAw5Kqbw-_AZfGfjJttAhXZDuybZTDRJbroa1gFc-muxMfCoJEWVbX
AKighl14qWPaSgJttGpZYDuyafVEAvPGEb1bbhS-7inwxyrN6ngw9VGvp6NgyZ9vuyPpJOxDNqfPivwtXYHcjPo0lPIz-Q5cEd6WiWCL_xCL54l8gWcDjSfQ
ojwbSWtVFEDSk907Ee5A86yTQP9IF_LW_lqlysGDwDeJJy3Y1zufxNDFZz_VNkUlGytu0Yx4AS4y_4QLAQFS0rOuS6O5oXrvtrVYI1drbYC1gNH-0wi0MMG6
qhzVPI4fixTMoobDPXKnRUKCR1N8mQBuhIglq1xR1WfDphtw-S1z7VcHt6yyzVoYkIQaSWP6wI85dqlSUD9OliJPEZ0DI9g0J3OiEOJAGlDvdRICJ0KIUsxl
adT_uwaJG3VvOitR059m7-aGAZjmrWgGGF8nVbOS9Juihy2d9FBhbphPSAIKIVu0t5IO04mT2GTB5Qx0XLlF7Db7YiCbDU6jmpOJal1ELtQK4kV0gG0eN4lP
qLI-SJW5YzxZgUp0ZL9nzAHEEd0HDlo6v47HdcOmDXrLPSwCNvJssbBsFm
}

