sprite $image15 [296x190/16z] {
xD2n5K00442nMdNxJmiBUBy2aX4ozriEGsWgKPRAbAKoPIbCQMfHbigKfJ9bAKnf2b6M6akLfiXIPQcoL6cAB5MMAasLfSXIPQdIL5cAB5MMAasHfSfIfQco
55cgB5MQAakHfKfJPIcoL5cgD5MM8akLfifIPIcoL6cgB5MM8akLfifIPAdIL5cgB4MMAasLfSfIfAcoL5cgB4MQAakLfSXIfQcoL5cAD5LrYRg4fNDREtU2
WqeE0m7KINfnN97-_Myxlm4BHgZ0io-sZ_14LHQbYK7PZ4n90H6faW8YKWK5HAHA2Y6eafeMaIefM4Ige2uVSoWgLL9c2FoaIWg8I9MKtQ2-IHKKx25bng1A
odFtDNmbzVmvCQaQpvrBWQQle1pfS_XAoYmYLVFQJcoFK6CBZlJsktAf6iDQkAR2zscmViuFbDINoDt6h-hUmbTIhkHE7wIoGs7zogd2zqN9dLwbh8uo7hbt
fwgfzxq0SVe18fNnp8Urc5FLr6laY1EjATTQSAaqIjo9rzHQsZM751Pr2eJFL6GpXygav4ungJNbv-nmgHIHuqwyfawvfft_Ood32ZhnciAK-_JfY0aYHvnu
-DPIQNAVtMigH-JSAIPbAlifZpayV0cKlZjv-Bp7-n2VJVzVKWWmXQGMpfVVammPqw5AwJLyDflqfnEfgIoHur8BkicBqoNrVzWZs0emnQNMWkevn9tQUJOH
SfH943a6jPPUStHtcgh7LUXUK-aYnqUlsTl32QQwlTLKAJdKkJsS0DCs_hD76Vkp8iUbkZkTJRK_ZpAmbCN4fOwjdGRCiysfLw4V7hwKaUDGkhVzxWIRkibu
thWasGl4QsgSUZbTNA8YJLqgQUHuJVN3dOxt6vTIUjPKQuUv4xbnILLClAPaSoTouv9WBn2hgNweoj5skOOSPJ95ZjTKE-IGqVsOFBociaQErvGSOxRH1xaO
Jh0N2DRK9dtJrhSkrv0RbrIHuuU-iP-j2QcfV4hyq2VZul8XDow9YedNLFVSlROKB6SnyPhQv7N8Qw14aUFX6_8S8y_rSqMErvJFV7zWLahNgDVKVVxfftZs
ZqOkNbEJl8FDMKoyfiXp_OIHur97zzoHy2NO2qGlXfKyryyPEHw-py_rIycb0i_r4nKJbmeyry-p5-2ZWI-F4qME3_kaZqYbYvnFu5kPJ7i1FWX8fOmSb-8r
LKh1Bu_j7oYcRE6BxmLAwl-W5F_oE4da_dXDbL8qV5aZvnF_WuHIYjPKuiZnyBcKGzc4_GE7bFzSJSrn6YnhvE97cTbagC5oHYvUKzf4P9-0bTAdyCtBIThn
gQOCMPYub0svZTTKicAAXy_EvfyV6onXvE9IkzocxHDcH2aH4m_VtEGs_J1OmiZ5fRI_rbGfyV0TNbCJi70n9PIQ-oDyTeC2iZFncXgtEZS0AICNlt7Hxawb
zAscsZG0nSJ2XqVuTfjsEQ6K0ZSkDb5AWHiNAwL0JNdklZ9L-0m1fPAAALNu5X1HAgaGKuLlBKIKQezW22XL-B0YJ2MrW81IXSyC0QMI-gvK4sSgg7y5qoy
}

