sprite $image276 [277x277/16z] {
xDJ5WG8144N1NHZN_AD5hzW_qbI5y5hsxm40000000000000CFvg4bcEJTFiunGfd-IgdGBpF9UkqjprGP7bfdoJRioAt1HVao5CShFMlfmnBNApBcN_QzDc
IKglobzprmT9gaTfeWUxF75cxqmKsyXn83fHym9GsFp_tsuKQoqnObbeK_IwDQaznptdInK0WYtx5P6aDeK4_e98YWI3y_fKslyAR9j50lYBsQJE8m4ShuGa
InZ9grjbssKJu5y0vPy9cxmgbRId3nk2yfUehw4-ZB0SnqTY5hN9orjb5nB5JXsvvnJ3n6Z2vGS--PbFsOJBZzg6Y_gaJRZyQ5JIzhQdzscRSFaXhox4epPv
CIYylWfMsWJknokm3OjjWiCXgV2bDe6Keo4fvkwmTJQnadxfI4oo-YzXeKrQUjDse6Aos2QQqrN7I0xSrrROcdeT9JaBAwoa6nNHbbCwG79MsiHAEgkx592I
qZUsYRb76x7DsQJVzahDwPkUSsh09j7ecBHQVgaslVdYkS2IRMyhstUCZZpD9jgNqjRrORhjRILzEoOxAgp5YFHODFS5TY2fwNkT_kmvqP6SHYgeVO4bafR_
-GP8sgN4JaI78A6gIlHTKdHwOm9kapWJTqrSyUkqLjDt6M9jCZf-5aeYeWLsehYiPe999lu_II8Y1NO2ozhDoNnq_29k5bvWUStz_p5fpuXE9zbPO2TQqRgH
3JeTdLvM0WKs5g9SlpCJeqW6WZosYG4MmfA-UcHJTvjaCfRbZmiiV7oeCE2kG-VyfKniDZfEfH_rOJlpQ5NXi7jOk7VBFr_69CyoSIeqbfmB4ibljEwmm66m
UonVjJs1sooJG7YoC2JlMBIJgIgCDEZ5L-S5q93icJOnk6jVRngyHs04ozgAkvQ9PLfW3OD-JR3O0CjY9XLpqOdPfDqXGKqZDM24vUi-gRfDCedRvAwOe2Kc
6M8n_LFhVD8MHGUD5rWrrvouiZfqEHRk4uaocR19rJkLHCHU8pDe4CkyJyGqf7cRz9AITcEn8PRd-qI3ch19qx5QJWzK0TAVbs59ovYWnJP9DJrI0xGJpDon
ZafAMPUK4yk1JL8mGrd-G63ZRUdpmYCJJ48sgKeLnt9VSQ7tUXQJjeA9vJsR98C5IilzFBk6IWepMMWJ0wAbvIkmn1U2ksqINzK35irG4iTgAgSbJD02Dph0
XKMN2NcOeQohiQIoe9nO2TW4RYKhJ07jr59ac5j8PUhx4X11GdtOtI63T_oVLbh-yqackJsVYPLWWOKxMLC7IuijCOiiA2SIxyF6iK0dIiiK5GrgrYPSDgPY
i4XfgVOGI_i6J08s2Lpq0F7Iyh3YVZsJk4su0CUTJPvOMXOmCTnhmYPKS5LOXoIsL2WsWMKj4swJS8ea5mEmlprNF2ejYvdCsuHNN3JvP7jkZx3yNvYWa5qz
4s_FVHRYax-RKab-7fDmT2HmqectPzm3YvGMA5L9AIrdmcqYEY6CgG2XqY8VxpgtBsKYmRr978iDEZGhBO7OjlIczcLCK2OgBDqscTdzmb7ofvX8UjTo9jmc
yu9hLUZzr19dCaOvnSHYJ53cAYmlkP1S05XmQgbArTjhMyv4xkvqp9xa57SembDB_R3nFABodmac0PkuatSRrqujRTSbcrAZp3EHmGsn8wVcqA14FZ6r0De2
J7WHAikOe0pD2wW5e4XDs-d7MQVJLafj7qqjzvkMtW2oYqasV8891WhOvBs71ifA_d6hq_atjrnbZCM6Du9I0dE030-FFPFsB2QeV_H2my3fLEb7htA1CwYN
PXVhslLsg5ig5Dt5HDoT66MIYTxbsHtIn6AlQSkFCPGpbpgC4KfHtBy1ABLpL-0OgVvBAvYWtaVdaYTrryUgVqBPRgopoV0gfENchljqnwJ0Vwcx-93dCD7H
U72v9HLtYq1XLZdhrCPJ2zpTffWq-6UCWf6SswGRGLNKtNV7vxITeVHKU7kEOoc3w10eapvHUjemn2ljwGP1EuFE6w72haBsCydc1CgaJr074nFsZx0tnX1t
gORQcqU2Lo5n9XKTaoWKmqZK9d9pdXL0EyNpu-wQSuDrRJhfIFWy4t4VG_avnmHrV01pArd3hlvpU2jmX-GCb-rtWKdvbsQt49L5vyoabymmKVgfFmCfWA6g
Schk3lDVafpJHW8qmwI0CJbhBnEeWTk4AzYLByQewXVXMcpoyvWqZkIij9V96NDJkEQ-miwhvBCknhZQMwyLM3-KMPI9zapYLi5OCnyrZmVeh7U7R-zVUR24
0c019laQ7VmasiMaykz8C2_fgPpKpsetN_X8vZKtjuTCQbTEYFQ4noO-Lxt_M5WsiNDN2kO7gDa6L2hln5nJHgdADE-LStdfL0FxIf3vX7HY9jbZbFdeI2s5
7--tVjFKgmGMX8G9wSHSSQFCLzYwNTO11AVTWYWXAF4vjlc02LCKohHDv6PoPrJqYYMV0l69Cz414ow9GP50XOql7JSbCgtRC3ydtQlCeXDHhAQKsGhRVjnA
kKnRFdNv-SoSBvb59wQGLQORSTdnwsvcKblQBWdQShCP9igPSBazj8gHPL9SRNU1iBCk_xrJGZgn_mphxhNLEscUds5Jj9FCIyWGs-se0rHWt2feWUZ4joPR
qxLgwIeXDeb0wR6Wa-MP2jjoshOj_mPHIovLxFPIBrTPneH79qx5CRIAtDia7dBPs4P44htmUjgQhO0nYKDnb7PdbN9NOH6_MsWt4rYcJvuQfz9rOiuaJaLI
aSugWtS_pRqL0VQUyKxqoRQ0IQ0JXwdKz8O5RwgZ2WkN7FlSNgK3M_cn18haYUZm0ELqnl9c5IKLre2MahZlWfBeonTvGIjk0IPXAlQ6MG2hl14RJF4OYj11
lP8dpsex6YidyRBoMoL_FCCQ8bMbqhS7ylEPLDg9vwcqP-nXfJMvQRnRlNknhPv8GvvdKabq9gYWa6MIMPJ8soxaz3jr9Y9gxq-sTqOchRNhat8-_crPvjkE
aEZCKScZBG72rzc59kFw92bxKYRRJZR2PBROZYgikud2zxtLb-YJGXTGRQB4yauyJqK7ZTWSAgA0xRcgeCk3BT2wmwhX8NQ-s3RjP0uHVPIXIfT9cK99Sr1A
l1FFJxR3sybTK0gTOWk5KZzTJWe2J2Qee8wZ7PXEDlQBBjGETMAybGNHuNM5Aaobq3DpULhpQSkYmvShSKdDAUMpzwtbyrhf6eDMykLUi6wdxaLggQMswsYp
5TsfCj69brEHVBfT6TticgMSRhQGtHRw_EGwvAdQvtVs5HDC5b6Hcq9IsPDJOqyscJmKYrCcwwc4hiRfaqJNJ4K_eKgZivIApTt-nQUMfFjLfgApdagbOnd_
HqzpQoR9qz6Pfn8VxHl5rIWk-VHX9zi4axLKCXr8Dy949R3E1tkzhz0XzZjHgQTB3YYlBAnZ9U5CpZ8UdJPZa_LKJ5gjOjVEi9rEbvLHAwMq_iOmLL4rAJdb
gbJcU5DeYCLg79nAq3Tqqj_uvrMuLzn8T8XFrWfXAkmuNEcJjkVZlukZi_uS9BH1jq-qOGCSWtMISYRhjPzAcLqcWVq5XKVdkrFXjtyfz0weEzJSFbeJDCBa
-r9fp2XQkYSSYWo-J_FQwAnlGlmc8uLEE-PQKceEUedHCpa65KblUv9s_KhhxWKVtJh2fOYxaVi_mkIxHyXKrAwru7Iz5ppp8NZvpmGJSlytnMGz5Iu9PiPC
EzcWmhBe7212V05LzKw1MzaIYCwnp592iucvIwu0QSGiEeUa4X_OpAsat01kasnE3e17Y127qZxkE3bLT_BjPqbqZccM5jzF0mRtWKreT0vhblOZl2qmmCOs
oKQO7DOiDPqNJaCaPe5rFOdEmSt2FfrYplcsV83ea2NBbDnHYhfnc_3e7Dyil8RKuKyNQUcg0jA9loaMp6DnAod1CTWb1QBpgXaoDtCtOXCIdTV70j2VSLHn
A2Pd-ITBYo7utKx46PFZOuaVY5i-K7IuV7V5DVgQifHqgEXmUGnBu3NbbWBHUN4iscT8SZfmT3WMXqO5XxkJ0akYSrmi5iO2Oyb9IgBpybXeSbA11mRx5yTI
KgT6R79KUPWBJKucqJcod7099YTL42OlYuLEQtmuUHbvb4jDlGgnoSjXSPZHOi9jmhlEyR44Vwe8hoQlpiMK5vCYSCBajR6u0pOe9hagt4bqNXXB3yRAEu_I
13xGpnUNZsINTq69VluBv5oSoUjh2ibVBlZvBzDVcupr5mbH5CbVBZ__snuSo000000CyhU-nrVT00000000000000001
}

