sprite $image427 [119x86/16z] {
lPS94kCu24L10eb5cVlVTXQ7I8v3EJKkTtxlMvx50wo6oo5b-7cgc9dKtq9BjsTw-HqKMMscuO-efBQFye-a7YFrPr8ZFr6CBME6uXz8JQBy0wafcFwCLBML
doZ6ba1pnRTBxJqxO6MzN_6IAfJebVhPtqBtILNQdriEFLJwhOhNIJgkVIo5JCsKSKD6HUvKFBsvjma6eFd9LJtEHdSftXz1pMrz4WUhYAydGjORfdW9M-0A
ORXkdEwx9qfwgzooVhNX-rzmCzNjcojbZzhmejHzEhVMEZy_YZSeHsdLN6g8oHLVNx_kFa8ggSTXNYTKz-ZsYuhZS_e7Mbzbhk9lqrar53Uyh1XRJ3n-57gr
hvgk3qDPJNTLySQIkdi23RgysjTDtp-BP7MxNb4SCy-xUZVi_s64PllgqxIruxzxDhMawuE-JshCmsidoNnSdj1LqWsoZAWblPKepYOrvY6YnlXgNxKLTLeB
2qep4ydNHwuuwtjtUVqjBj6-UsYug3OR62e1a9xqbZBcKbTK-Bt-7r3h0BZzth2TEGwmXkAJwrQHP1CoS-iKrNBN8rKHGDnKMdtJLZHEbcuxgNkf-KuAgMnk
dwa091HYZwTTtP3VymvR8Qa8RL0cpQ_5XNfqu75hLbrYZeefX-x_RJpXcX5fpqDYRMBkljMcbxKrrpBB8xJ-B2l5-fomePsddEuRKgE7l7K_BhCywiCzXxxQ
rrGgpE2ph4q9W0AvMn_9CilYu-7-2Uxx1zOAAqWivZuwGB53T7O3VuEEuVu9ZXqJe-vz3NdLiPq909APEoopFEFn684zS0zN5FS6qFONvGBGNFCMb5EeRz30
Jl1QoUlwgvirzwWsiZ407QXf--Rr3Mm2rdL5eGty_Aru5lnudwxsjNEfGGriUc1hw_qrPoHvjqVx9gimaNh0vc1wNvwQljkLFoudSbRVm9w1jRw_lzGwlcCr
EWddWbU6da9JxFVUMdjwRSqsbnd3YgJrpR4vT_MMnd3L0EsNMIZ9i6g-e2dMSl1hVV1iwBBVlksvVTM6uiAczSsnbMnyxQtd52UBK7k5Y1w6vXoBWDs_zvQk
zgKdDB2j_nkHBffBpR46hK4V2TVKlUzwAt-F-qnItpDi_uinxQtzhY3j-LLIPmxrFSSgGAjW9-k3twwIYvhb3FfuL9ra0KAeRffnGp7DUyOvr4-XHW0SxJiw
c7TJ17Rlx2F0oVhWRz1n1Xqj7ZsANCrzC7JamT7KsVg8z_Z5-ewrNeluAuFB4712Xc8v-1IgNwHgWLscuj7H3OJAi2gvOhLhzGsf-op5NgY1L2WotDXwM-3l
yVFwDZXcARO2nR4oa2iWrcHVNXiQGKYo5Aivj8UmA_QIjDQb-cezq3B51VeOBb1BANKflWprezHSiV5_SZisg0rizFeD_B-bveg7KV46X0NHN95VpvF6BqdD
5PiB4H2ZU-aDi7c0Rv1whjWD2nHthgtskRYIeRaiDPzY1Mqqt8HB0Qgs5DybDPzYmYuscAbWJTRMUNsbG9xlYZi2EL2jKA4DdxbDQgvuE4k3ZemLUc03V2wL
uM92yHZAfTG28BxFk45gdjcylI4XMOAzJMe-nG9ODC4cKBicDPzYOkAHOE-KcY_glCZvdILoY-84UxVKN76ENL9l3-d8iFTBpHNds5pg_Oe3Ux_KN762JQNU
htXXSwb_J75WSwb_Jd5WutyNFqee3ga_JLKV8VMtOPVhKly1
}

