sprite $image286 [293x209/16z] {
xDe7SWGX50DHPoD1mVrFw-mA3dmvX-rtX2x4Xfdr8wOaUMr03zOEYRQPq2JjCq7Fj5KWqQsvNiFIdcyEbzhmkW4LZaXarRYC8YmjqKWKuJ9Aa2Z2qX8cKO94
aRd-lQcFunX5I9GuusC_GQ88IqkOH8bsI7-8i3bzBH8bp6TQWaGHbfOmYHATfIKuHWd_gqHaKeNDTLN8fD-0H8b6eaIZKO944H8bJA8_zUZfJ1KsfmgRKuMl
0vVw6-PlVaE4gqaLCbb_pIHHOhAq18aI9b72D4hyU28oDHNOdFMVT9QM8564H0dJA46Y28aYV3DAc6EKc2HAa2X2ewzvzDHDfj8OLe7DZJ6gmyJNWJx8LBBB
J6okMxUPk9fsndZCrA_RkGzbnsqO2iFUHX8uaFF-Rvje31TjJWpUA8f783azTVSRuh-YoexB52FTc8QTkTQ9P7QVESY0gnV9XawJTYBDD7KWEHE6JTFF7gIP
fWW9DjEqOM98jMsOvac58RMwPS9a8aYbr2OpJUjwXxGowIPDSpCHf2AwOPed5OQa1db9ayoRA1J937UbcIQETEEHbSTcchG7QQP9kv1yriPDq_LlIDKOqZof
n4WpJLkaHf5ccguzIFEgwQSZrLhadv1cckv8qfGZpJGfxaY_lbLGfC7lxpgH8rqktoL06l6aygIGrkgto-No4mHfv3GfxBcqIVlvbv9o99wcSOXyGHha-mK4
QTWqWVpMcw3Ua42GXaiJDLXCcnf16chc-AGfxaYBcJGGf96OU8nKiKrJYv3otqG1sH9R9X2aeTBa7E-P2D8uCyU9_l0jqOkK-oQAmjYwlygj84YZfKcDBt-N
svawaLHPcZJZDdAaTTcMAKA2WgSf9P7PzlC9xKG2WZIb8N8aN-gRoP4YfLptTzKiHDhEN82KxoQAmhgHd4aK_KWyJKc8E9AdIQKRvlnf8aG1agV9TViMJrEE
RUIBVW6dNl3KQU94CP8lgDb-9cWI8exaQIBZckcaecRxa9o9M6UvYQAmdKYkPAdI51F5I9n99MEQOBO3QNUQ-AEdKyOeHlA5V6bIs0wat6cAYMAaE4tsxvQI
aye9OaIH3ajJ4nMIfXDi8u9qrCm9L4YQJaFaICSoIQkgwapGan1nfCFI9AsKflBfDAdPaKZa_kvNaKgHpywSmWv6Yg-QOgJoCdEc9o2YI8UboP5A-LYQO7Oe
KfocVgGFfKdDZaUARwB4IDMXn5xIf2UOD89qmCpvJggb-gUPU3BfMOZwZUYZfo-4UrNodsx_Lve-ISHFAd6JMlL_72HD2IPjnyn9ysrKQeDNbAGfmwJ5J35I
QVTFnKcQ4XBrNmv0cizQAMA0YXq_Ste4qO5fmZFSLSqC0drD4vmfJOpYcUD8ljfjtvY8-NgUL91kqZXJY5Hzrg0cy3AH-xi9YNYQED9praGCDoJow2bDZFXD
b63SdCVC03Gu4dag_jbjX0E4oCnnfEsiYIEHHq_PYFX9XIFvt_DPSp7okFS4Pv3TQKA4P4331eamVIP6rsDaU9euaZsMmflDNzZ9yZCjJXD7Wlyz3tVmL3mD
4MSYI3vYzx-nsKaxPaxFH4G-BM18MvFW_TrKsuZVt-r7ucdAHiHdReFK5eAqxqsKyn5n9YZ4aQxNnJZITGdIb2P6F4sh0veZNQySQGdITD8BxFx7lMfcfYiJ
bdKlqN5Rbk0bkJmnUlC51hGME4Q85ASf1v6lrxu8teGRmVkx2RSHlx_Ba4YsUPfo4l437KSYJ2HD2OduLHD7MWWJJvDc8U9CIfXkIB1LgUVJ0iK7ReXyE4sE
j1W84ZkfvDr6ljZC-RXT3RR4dnRa9E9fuk56pwS5QIUDFth2wxXvkCC_dq4pRoEUfZVXzkDU_Kq5oOdupC4LOByZDRzpaBxNCPCwaW7RSKCfjRLMIyL0H3nD
WF5HqbBQkcffendrVrgWfRPrIIio8X7_j80ZYQ4MZ4aKlxyBtqahLnlKA7vXfzwGrBGM7PCedhbMcaUfbJOQ4RySu57oLIjoda7sfwcM1rB1cDk8drJuLgf5
1oMAltgIKWdIK4Hncb1TgNnzt3IR47z9pfMgdzz6tKPncl3ub70I-Lh8p6bTZIPHa2O0qoWygKoY84sJA9Yv__uCCfcMKNJYDCr9YqygCT5acaHncgPHdAP9
nDULRwQOQCxSD8hlxqwY-Akdc6XU3iH4CqsnqMGAYIPJJ3JN9v-3_0a
}

