sprite $image55 [260x168/16z] {
xDc5LG0n401Hd9qzwxzQ_EdYS9R9Bs7YBylM4Y0MiU3DeWNWhf0WZq2LFO4i0e2xmi0d5eDCFdUpD6xc6qpduSS41RGHWX-PHUVXnqpBG79Re91DXHi0TmK0
TuMai6qBW3n2KiWM18LjBWGWhy0AZ1j1rGi0AInGXN0Zg7e10E4ogFBGxqDt1K0U8G5tXM0VlcLGvUnR1bKQ2rI7-4DsLqYEOJx0LcYT2lSSoY1S1LNq11jl
2nnMJm3a0Pu6XisH4p1kXLLF0CpI0kjl2vpE6dD0Ne5podlX9AX2E0SgmRLm_UipJUW507A50ewv40do2ZJ8SoDuBDTSS5lNOI1g_ScPjjx_RbySGaXH0aRy
WEOsrEmW1-RX9pfBNPo0vGLFAM9q20sVh_NAm0SN4Aof1KANfq02gqDWn_AV0dBgN9m2yhPbMPY2CRYbwBfQC0P7shgVWjN2mI6DXIZ0CsZje91beOAGdmm0
gUb6eQwf1MD0ZbQMrS9am2wog1QCWP8KijUqf1QCWO12elUstLAn3WKyQa67a1HmtBMmrlWyVO2kf9BQscfQmCC741MI8jhJIkCpoBRT8PWFG0gehKujB43W
uvFKSeFGHKYA2WIajdveOO6j6X-VdvyxoMCmI1Maaj91GaZJWf08JU28dTCE0nH0pGU4aD9gS2s0dnQxAH9rsrBf90KcHmxHknOQYA0Yc0pkeMbXgwI0b3iC
ShGSLGim0Wy6Hc6a6uG-G494AIIbzu1QC0AEmKCBkPCGGWP91JMQ5gmC70CBoRi1Ec0-09N4Q2MM5eo0Ps2PVR8Caa8L8OdXjkemPU0PJ2tOxxLlWOIIlMqX
jchhXvw1eu3Z1xS-IAgAGaaUQfp7jY0Yy0oy5ehO8Zd46EItrm8S0SV0QK6WvWDZqBhJGW02ni3dQsgXAWcbwC40r9PiomH2YC0py5gmtwiaZ067BH4L1DvS
19w13-TMFPIaCI26g6tL8Dwx33o3CorKDGP2GiXkVqeD4W48U0QUWctLLWkY49AzzpVI0dW9WG-c5bhQCgn5S91It0q-606lXLkc3y11eZTtR8jM1buBTdY5
KAIJL96HRNmcth0VMZxsPuEx5am0Gg8fgKgqwfwmX2a3do_QiQsP3o1G9T6tUng8U6NWGve7gvA3L1iQjhHjJWkH27WAXm6oOf1KMo8qRvlRgiEKWGzeNt-k
85KXshVU9eM2lqE17nTKU34aKUttgfBQasIfcyMq4BKCl1PACnyaQIDjbhbL1-c7FdwhRZWOZAnri_m9BU0toi27yzW6z6I7zs-f8EAMWTT2RgaT2AffqMaX
8W6_LISSCqEtiTbf8Om8phLGZXy_o5w_Gx3nES94S9uFcXQC0KOj4q7kfeK_LGPVlu30A6Wn1gJKrlDau5wsHH31kHRo8AKgO4qYDqCnI4JfX-TQi2Si8bL9
wVRmUxEyHWkl5C7vj52AafHqxmjkMeXL1ZwWQQ63ng3APlbzBO3_be3VgWN3dcjiC-xO5aK4FfXQQEakmytYj12j33o5-fWFZgG7XKRYTGHU_n7u6tmo6BLb
Dpw_vs1yNGipfRIQt5RzdeFnTIrOoYsjE2syuM1ylI3gDmQbjkAq4504da8s1XQdXLyGmTye0_-oRSl5uhKGIWJdutCgC-t7iGq19e9d-sHs39mMmfM1FxRb
1mDtWt_JmVYw5j9aa4mBhay6B0D_RCl685cVT5e8q0-Vqe8n-D4dEubGtU1S2vink5FufWKb4PI0Vzbc3DoqK4W20KHmULfuQ2619F62_V3FJGl584m69EAM
WPyMYgNM1uCp2X48U2qapy02X1B1-LQT3mRPCI3nneFnTIru1XQyxs1y_GcBPs01BXoAtZRpsEOPM81m8l21QS4pc04O6O4Vdq6Nk0Iy5ludWprCIBHqmY0g
0JyjN6Qm1mj96Rp2O0yOaXSOS8-PvndiSVCiWprqdc6mHmyy0xyTnSyfWtsHE0QB4R0u1aPWhO2UmRvUVZ3Obynt1lkg-PeCFlQ5OmpsL-S_
}

