sprite $image70 [110x80/16z] {
lLU9igCm35iWbsNp_x-xJ0qrAVLurZDTlVj2YIGhUNyos4PR_lmdB0q0bVz3LWb418pjzrpRK2uGq7yivzhn8gCwyFhmKyDE4O-CB2z1VsXVERdwQllKhtuW
ub0HHvayr9t-8FNqTAhGB-oh9k8tAuDfIAN-ySp0ldpgdVW5zcKD8tlOKYwMzrQTQKYc_i1Rg2hZ-cplxnKCJ59d3GETAFeT2BTh9H2krtGGMOpo8bvWeVLu
gZ31s0Y2OpjT6AG0rIMT-ZkO1pFHdKrN0G4PG2MP-XbWq8EDY44JWB4cKkzWPdl2fY5XM8BDApC_zJxG8pOuPUQc7iYpOGpODCGY0gq3EJPGrJp7zbLwTqBn
zeTHM--zbGRw0cLO6g8oA-DUlqlrDYSlxEn5o6Aj2_TJ3xBwxQ1_1cEpnPjzZc7sioOE6KuuT3BMoHWhiodrKsmB739Wr6rTrz88ndw7Y9qDPjyZzJQI6-sC
Jxnhq1vrXh1Dg6sqwT5QPkRFPrvhAm-SBjvTK3fQmhBGfrlNnrNQSGwROTNjHgNVe19SgIV4lJQoRDku1hKmI17ILLtMVNvCN1Tw0YjOcDL-oFqvonFNHhWO
6NyF9NCp5TzSa5tu01w3qbZu4rVU1Uqr0Ps55Fm1YstXQux0-wvindVh7NP6W8X5uSoZSQqazZVxoMPy42x-LS7W5VP7yTr5F61iPX_DFUStbtiSAIeBcOWp
ssJVuhSoWTQjlCh3sHnNlNVE8Yg-1K6aMPgUk9GYPtU2RQM7Y4ysim_5qkImBUHvnp9nUMnc7slYScm4I_qCVW9aoB6POJ6RyUNPJCIOZIyfCYan4ICs0tmt
PZR04z5dY_c0Fe076qO70X4DB36Vxg3eAMniUaBQlvGXb-nIeNo1VVMyanBUfza0kZAN4HYcN0VPqK_iy-7BdVHY8xkWLVY66NHj6uLoykrik9Iqxu1Z4NSx
uGiYFXRlFh0CuLX4M-tZi7RAJ9NuG6M9HRHJsWvh3tRKra-k0a4iudZA4jjdDoMx2N3CXSsxmyLotjRPbIjClOUbXTF0qgVhL9ZwuAuPsrVi9X2cFa2Xc8yI
gVTGmsb8fDv7N6OKfzurB34DYTHxYCiiCAp-4rLSPedKkuZBJ1AfpzidGUfpg920BPFwiCnYDajz4dwPIIBrUViaaVgKVSPci7CzGAxC997wl7sII7s-p2IH
-doPIIBr-JAJHEhpqo29rEUdGHAfJvSP9rAVnah9rFy5
}

