sprite $image330 [577x415/16z] {
xDi5SaGX40PXdY3tlt3SanMWAhFozINehdz8mG0000000Anf662jhQnf260fxPcyf7w0lRspfqw0hRPFwfOw0DRIlj6XGi2IspTwL0ZOQ_kBUfuAGReVegxf
D93kXobBEWQa-m4waXxI_G03IG_oCwH2aEwVZ2SzoC-u2e7yZAiGfFjXFjSD8BS11bG8Ng_1TGFINT8VXloCOzsGxlFa1F8pWAHtSZWF5PBkyr0X9uVpI7hf
_Wyg1Ea-ksv0kbitfFiyrWtfFWyLSd8OaFIGxjODwHwWGf3krWtf7gr2aExM3UaUd_IGxjODwHwmRa2wKo7f7g12aEvKIBe7gn2aktL3kiUl6o0_rWto4v_q
aEwItc_1U1M2rqlIsosea7IdGbU1TBTka1ygPBUuIgmRqbtIEpcqRaZtwoSds2qalNGFW0f9ToeatQqRTeixK258T-k6TBTkIFShNJSWtQcGT9Vqqjsw8Tsf
4AIxTKEwKo7fRjsGxlUPz93krWtfRjsGxbH8kbCXI7Sg9Dsj6tuBMZUaktM3_C2w8TqblTr2qfCVAYJTOTsGxbJ8Ra65fBjrW_o02abtwuPqb_HE3gqRqXrP
kaFIItSg9Dsfa7ItRaXtK27fRjrmScZTkAfqXtL3kbCXwIxffJkoT0SLakxM3UbEXQIxTUCEqnsINhfRDwIxTKEwOx_YT0SLakvKYFmWtu7ymBeXtQqRSRy5
OTruREzUaXn5enWAOvpOvhB__VQC4TrTb29IzVZE6axabKB-oU1wGQL_9Ff0fLzd__mq48NMuvWFh1k1GCUnVo0A1G9HI1JA17B7h1k1G1GIXKA1t37hHY0G
XLJwK21tpBgH2kIFa1zwv09HIANF1Jgi6w9G890e90e50hbZrer080g9Ge50xfXr8n28GjQDG21tpBeH24GXKIWIo1rJwME1A6JTo0LonqIXN23hXdKZ4CWT
4uKIWTmnwqOk48LK-bmWTyowaGj48Uj6Bf0x9Whb0b585Ce5SiT4eLoWKo5ODxRZ1kwOTICKoBfXtSW5SiTEh1lh10QvOohzkW-5LFf4e7sVuqGK4eLk2tIX
a2XatRWbqBwxOw9G9D0-1uL4eK0WTyowaGX48L4e5qYbjsu40eb2AdqWa3jctOW5Kkdzq2CKI1HIwNE1h1kYK22GA2GA1GA9GjQDG22LNXGA17B7h1kXG1Io
RkG2YKBMZLmWKKWKoWLonrJwN20AMJToWQmRruX2p_q2wyQFOjtusYzmnqIXI22LthgH2wJIg_IvGEwOTICNY4BMZTmWKUWQbVxnZWoYa2YqVjon054elcCK
icwyzWk-Qzs0A6JTi6uyHQ40wuPA7sFTU8X28IgzA9IXqZzLUbWtkeX2rWrODs3T-8qHXJQL7dxe4G3h1gmRlnhOjyKFFNuMx7ES0batxe8vZbCWKUW-zBaf
a2XqWlquJe7kOjt07850YtM3Fe50rWtNAn3eP1E5w7DR8Ek6wvK890hH9n18fNUz0e6i6tQBH23FM5slG23hXkiL22GAqISGoBhXUYK2gVJq2GJoZDNr2WIo
RgZkaK3M3TSh5qWKShroWVgLVjjh2j4d5wY_RgpBDgKxvdhb0lMZqBeioxkmRj0d5QY_Rfm2RPqev7hb0lMZq2bGuOwfxh50_NNZ5EXLY4AkLofGlzAV0gtB
LeX2z0a4wgqRrm8jZqAb5tu2WNfHw5gWPIj48Nz-0e6gKUXQeAP2z3bvBZUeHQ5hWTvJk6EkLo1GxOvT2xG-tjyGXLJtla3vHpgl1LgMTI_SCTSh4AYtRinw
UbD8q_I91Ugl6-_7jK25EoRy108Lez1S2_Gf_17ov-U6GDLA_oDfUWqKeazNe6__IETrclwQODrmlGe2zQBGvpfD1r68FWM1cb7eTIbGqCTShu90pNLZFjS2
JQ0GVGe2DTUDwpGTh1kkLonG_uxbQNeB5FBdfo1GyHdhUxbEqy4Teqz1eEAwiGLfslKg2DIjz7cQ7leS1O4AKIXEqzi4VuHShu90nMUirsdw7Tmn-XG4AZvZ
VLscwLVmTiFrAWZKZ4BFMsbw_EIm8D2l7OK-x-27zwvNNw3-surR0kKAkLwvGFrr8n3e6FeK1Fh5dx5k5m852hbU1O6wwyQ-NWWKt37w50JgLlht-qAWG27N
gobG_ndh4TmnrRqiKFyPQw2GwrKKgBzkV9q21NVCzUe9r8z2Zqk1WdM3FWM1ckl6jWNVAtUzcWBv5sHrVGZaNv05ruj0hV-xiQlkD_aybWx-1Ld_UkNCSxcD
A4IV_0ERef3mSxmVopMYa3y__y_-N4xSiRiAkLvVIu7gHpfFyZlcUhsM0luRg-fUvIaAgUuglUhUhVIYaEeUiRwj6wgxTKDr5uNgxCAFTIFHHtMtRgZkrWtL
_RTbAqIXlxEwBmMi6t_CRb6uNjODrRs0Ig-wDoYi6wfx4-k6wYuAgUvTH27LtRhn9rVtTIbWtVXJma-XklkXX-fUmBgXkbitLFScef3ghjAFru9Dh1kgkoWq
k_1JnReX_5WtLFSgrWsl1LNwtVMgOjrGtKKX7_e9iMwexXcYaF0JOjtmePyG7-bKtMD48Qy5SwmRgdkEIc-toF6HJjKznpDMrJt7kk6rO8uev4C_0NxeeRe7
M3Uy5WomRgZk0Pwngku1rWtLFS2weRgVY481NWjwnXhXGp_MZHpXHnJgexgBGggxTSFrmbgzOwgx7tgexjWA2Wa_req6meyerA_kKEcz5hHkzAyNHA7N0kk6
wYuADQixh1l2ZqfV_T0Fh1kgkoXKVIq8bLvr5uMwkmNSCTNTkb6jxX25L7VhHlL3Fn25L7VhnbJ33pnZLTsj6zNg3b78zHA5l1OCiMw4rHtkM5ZTuHbh5dvW
tKYgEwmRarHtY4AJN2_ueSSarHtMZKbU2q8KckGRlH259Wa_i6vCKjrXtPZajI3yq6EIwmNhnYIl1M7TcAIwGnIQPBU0IZz9-85rOvBg3b5eakeEwyOarmkY
q2JL7TQDIS8FLFf9gZki6vE47uX2atpe1ohz9DKTej0ahmNXZarItM7TcAIwGnIQfBh3kZ59TOSeDCbhGLWt9ldG3x0kFm000000000000000C0_
}

sprite $image330 [289x208/16z] {
xDU5SGH030J14r_-2PlfSGlCFvs3TahhDW10pFYw1DxxGTaw1rRxHQvJoDbl9jOX-Em3xUiThFU1mob2xWE7KuIOVS74WlU-eesq2yNu21EaNMWdxK8ProKa
QHScIBlGJjg5CiP7ID8kJ91seOth4if8kxepqYwCatQXZF4Hal4H9aZx3NmVjRzK6TSb96aN9aYxq4RQXJB6HzqPQHV6IRjGndK9ITg52T8kj9DseOpn4PBn
4IOO7w6TwnBAkAxh9c_Whn24ST8kj34-GZ8-miGlJJl9pzcNaNoV_PSaroLCa7QXdRGBPQJzkad6HnXdV8GsqYxaZtpj93_tFz9EseNxzivpjz4O1eAMt3uk
zVwlUrsuD8bt30CixEN_j04u0yQjEFaDnuwGLDJSxLYFLDJS7Mj4Kb7pduDZCL9HSoT0H7nzJ40FgQ9U2EX1LTJA03siYae1AVaX87SbFm3aC2L_0-X1LNIf
0oGLnO1qVGI0T7t4W7HzpEc-6Qae0EJGzT4ClXbT7yssXBHdpUmP4VN_0sHO8LBoczaEaQwF2KWg2W0j4Edwc82aeZsWEN2fQ0T8Aee1cK7NnnxGInNf-kYJ
YlPi0GYsGwJhezjlGbBHAldjZeyHwVgOSpwmtpEfw1BicQwFTZFjsLv5_PxPCwb8Adevrr15Kj5daoyLQS_El_TCY72SJbBHSip74f2kZyCmDe2KVFZm9I1T
7_OJpmAGhe-9Pm58rmTyJW1egkYvaWyV2q1A_jok0D0JNny6dnC2ogi8mPvHRrS0Q9FyVrRHECuM82BUhW1GIaN0ss_Q0nLHuua1vLKqlsc37mXKn9hs653-
-dW9gBTWpvZb4mFANnyJqFbq6y6U4M_Nd77ViCXS7zD1lm4T5_OzcrUx9m3bauzp-mtehQrfjoi6LAoYOm9gS6OLpUsA0TMhQ08QvmvQ5KqyzO3YvECo0Vsq
zV0v84rx3AXUHNy1sPNGrl1H0oZ_Zn3qXl61hOrvks90bTV7_OMj0nKHu8a1rQlefQtFBn6HRLSze3azIhxr5xQcs3CBy0I0wfEF3m4vZ19FFQ1JkqPxPkq3
GEuWI7iEK7toRnDGW8X1FZ6W-kjZsZfux8Ddks90zIewsaU07CQ89mPKd_o1nVw3JJxrWFWVXZKV6Jv-IQAeVnYM4SyuUWKK_eTXuPaPTgu0mlymB9BRTIs0
aRW-TcD4yhct0XBipxpAoyVwbt-yWYNtZ44-IBIBD_dryhbLSY1u4YXZslbLP0Hf9qW-GTe9L4INTfhhWpJjJDS7GTh9LSIMTiBhWo3jtCbt8qrx_QIl3_jQ
-LnFBDFIoIT8E_lrGI0Vzkk38EtaoQTCE__raT-kX7puhu-Yj8zqslcl3uAqawk88EtaAZAAjFDV7_11a7RQw-F1qbx_1XYvTXN9X__w84Wxiue8qiwT_9ny
whUBF_dvj4j516adk3wIZmPAHN7QfQ8uxKe-WNm8hW_6jFDV7t7QbVo5VAIYCErAVf1s9N-JTgaeIBjKH91s4XM18EtKAW91sgdt30Hffxu-G91swki31C_X
fKu-zccNYa3mQ21VybyW0a7QgPEFVTgb8kpJBXM1u8a-rDS7zccNYh1FkrJa-xHhhf_VBer6ez5eD9hl
}

