sprite $image292 [236x171/16z] {
vTc7RYCz34LXD4kYA2Vl_xQRhNVRmFAS2ML21_sl-u5NgU_nsTVUjyXi5wof7QHg1wdQWAfsaAeTf6e7gTg0gdQGgXsaQWEgsa6gTf2g7QHg0wfAADr3QxmT
g6e3gTf1gdQGgXseQWEfsa6gTf2g3QXg1wdQGQfseAeDf6e7gKecRQtMMeggjRRsqjepoW_YxR0FT7j9xGdcRQePy2jBMxqzrMFkYr9RkPsej9VGielELvTZ
mKclFkuhIMyNj4uBRfhijlP4ad8jm0P8wxo4VvHAT5H-MalvCUcu5gKrGCs5DK2DmreUAlywYciDK2CloxK6gBcmzdItJyuU5qKjdsqjHhLSoXVCLwo8TFs2
bKt5gVoil6fGowLwhHpJnxY_tU_3kzNox64La8PCkFdRxzt76FONjs4ibrh5qYwbj1-rWn43BQBo2Pk4VsEz7dpQ0LeZGQg_7JI-PdyzMAerMsYz2_TVRDU3
DOur6BpgSNTTLbQYDLjfRP8T7NOKMP7MZ0SN_F2m7LZD95riBMyJre6i1gYNViwfprZjR9BYwgjQLJSS_zB_2MkrqxdtgxJ0wXDMGy_Lh8_XxXZRtKT78vx_
d7DU-jNAJjkxZwyv6d5_UDP69lppp-X0sttyYdtrxmyN3CxgOyZwLKkSN-lioua-SzLRFJTVMQKzuLJmMzWw3gd-Sp65JSzLxxCVYFwRQyLGA-bNQg_wkldq
V6MLziH1-OgbxVU_fDxAJTJpyvLLzJDEhRXTyiCr__6fiDM__WwGoZgZ5VKeZ_uztVm4PPqRSd-8xSAkfafwO0LQOSkdK1kRhwnyoCAQbOLKpVVOEdzQV_Xc
hLujBM2-nrO-PBVBTrpPV8-jNDklFMt1qcChVxPkrsbB0mzrnifFUvMsWOSwP-LQbnRVbC_tsCg7B6qhGLyyT1_KohLMpt1h0ryc0IluGggRk00AfR9YxSnn
hSrvYvpWeG8h6BAuFy3bc5db10yLMQKb7nOq36kjVbH-L3zgJKeoNsxbGnROG62-iePeLG-G0Yj_jihjEFvGkPL_jwViccQbm8g7t2FcowtIWgz9W-RBhVpP
1isNM_cGUynykPLhUuoKM_cGVSL3LUyUg3KOatxDFMZ8dSuNKWErldA-AcJ8Y-TxlVRu5lq5f453xWiVQh3M5pvK5VDibyutyhG--hBvnclNIiE6lF2Xfj5U
9GqVSlnyWxNhvvjWo5YQHjl3fNp8Anzgl7RTGqqmv9LIVjhG-QRHylccqKP9rp_R7YDTVrh-K1DeWn_g-Y5ZQG9jx7pN3vdFDuqsLXe_v4nIherzgEk7p1zg
5YsM9i9IQYeja-RI4casBP2cmm9gEYsGfjC2QJeiaARJ0cewBP2cqm9fEYoWfjC2QJejaARJ0cawBA2cqm9fEYsGfjC2QZeiaARJ0cawBP2cmm9gEYsGfjC2
QJejeAR30cawBP2cqm9fEYsWfiC2QJejaARJ0cawx1hg5m
}

