sprite $image387 [423x231/16z] {
xTr7iMD100J1yvx4d-qo-6xwcOh8Oj1AUJUVSF--xQFN-0Iq20Mi40Mi40Ma60Ma6EMb6FMb8Esb6862D82210hI0WeIA4eJ9qYWA4sS886Yj72Y57E2n8dI
zquulr4gHYaKfL2KCb7AX2aJfKgKAjKl-O5If0YFAa2A22b2f0YH8aQA42c2f8QH8aPg82c2f0QI6aYA8Ac1f8QI6aXg8AcXf0QI6afgA2cXf0QI6afgA2cX
f8QI4afgAAd1f8II6afQAGcJ6afQAGcJ6afAC6cb94ngA6d594oYX4cOC57294oOX4cOC0cJC64I9aoOlFCgJ9Y4IRu9WKc-fYVVUSKaJ9G6Ji94YHCc-RS1
J04dIWTCyhzIb3XXadyGfHHWmiJ9NyNBmGkOvBGPERl9GMXoh22cW1EbW1CbJixvbbFpAGMSC85oWv87A52WF3CNA52SGCbxVA3ada-WF3aNA4wWlD4ddt5m
2a1n2aXn2aXn2aXn2aXn2b1n2b1X2b1n2bXXQc1neiLfZ8OfHyO94oPAc3XHmjGFaoXnmeG94oPCb31XmeH9c31XmYHCtuT9c2XnmfG9ap1HueI94YPCd31H
ueHfu4G94wM14oPEb0PEb3XX6ZXHuaHfxqIfxqG95ARFhSif_RqRTrCwwRxPa8wwRJMbisxQJEcuMmPJEk-EkPGMNR-LqgYBTqBQTUL8IkCkcWVfghQh6afg
82cYf0QI6aYA82c2f0YI6aYA8AbYf0YIAaQA6AbYf0oHCaJg4AaZf9QFdj7v3m
}

