sprite $image164 [131x294/16z] {
nDK7beCm30HGqrKiv_wttPHvHTlW8Opc0lmm8_Au8FoCF1B3I1f06Cbw4OrzSZhmaLG0aW18Un4p8sa8taak0Ed-9SX5yE6qL03IgODS19y8TG3a8JYGL04Y
kG0aVWVnpES1og74ssXyPN96uBC503alOcCa3S7TGl53Z8TI0KXE1pwI2a0aguFzIV2zIGKW4W3qQADnLX9V0IBf0BKNW3WjMkr5KE6aIBLd7bLL9G_m38jg
3a8D8MO6ulOH84HC943StW48p4GiTnf43G61c9v16xTsW10CjxKX3k09G8ZS2W01XiwJm0Xs26uI_KU0a3EuINJlm1DWS9FetO4d40YkZUuT8EGD7j6x0qyG
8SHDeZF04rIPa6iFLCqE4gggT6X3gnqcM7iXw584EZXEQ0P4y43z8HudgBLdJ5NvDqHi1CS9GCGdWGvE4bfa4Xvmdj2iXjh02084j17vIcYr027Q1Zg84u0u
ySr61p52O1AkWoZXp86YWnXXaeQSc0G0GK8foyz57FfcOmHn0ezbtSmJdeYzIVWHHBT0Qnd44T36pYHS1y4vsbBcMJsXsSuaV0VnYz1jA9ivmiu_gEiWIC23
UPmcCaTeVq_2TH0c38JV_DpbL1tXxqcOI_meyU1MNvEedj3ivu6grMi9TIxBZ8VgMWevmc-Ja8i9pyXM2cPWD2oEuDheHdY6XdbY_6RvGS21zYKquozUpInR
T5o5eM23Uv_vp_QzAg-WEDNzwNpT_h8NM35IecBp4kM2GgyZmK9u2i-SasyWr3J-FWqMWlWE2D6n7uGkOdzh10iXHU6VNPEb_eXoPBMoVmTXL_7e-geYDOvZ
Dy4qc0YdS1CfAwRnYd8NjJn-0-5qtRJWB1u4TAKjEi83aSJ69SgvulTTwoOZzEXwJda2eMgD3gduu2985DuksjQ3C5G0v2vvCX7o6JUEHDtFukPg5X1PP3BF
Ga-EZQchb3YEqqKw5Xegmiy-uuwk7uGeR1fNw2OhOhcfnTFW4kLk8dNyaYYN2LR7SnoZA-PYYunGOjoUj06XYiVpCedNpHLb5FwfqVLr2kFsQaMqKxlmZdkv
YSK3kYNJ_i0LiYYN-TrrN5ExYjHOQ8o748KjpcAxH3dDiD3G5T5SqVK78Mul3pYsA7UHxFD5w2qsgI9fa14inbsIbFsACW_SNkwBAqh1ao6U0EkOEsrnHgj8
sKI4hbBGTPSKLcQO0QufKPGODvmjH7dWiD2GHRbCp6Ddk6pjBex5XQw8KVwMiWIS-s8ZODpP-elGFCve4MraX1JZRdVAqgxRIprriYXpYC_K_KbPTXKjSKQF
mIGYpFoEUxXeVyx2AYO6nqiKPOmxfb4LeZnmU6mj9iBfEipZkbEMxiXbwQ9SJSNN9SgDsylpO2EWwpbTphR2IpMHkhW8Mc2l9OrNbEBxThPK18nx5xK3iKvX
zHg2K57cSRp7VQSikvca6N1aKSugKj7rLvJBrR7GR1u2p2Ew7WWH26--ACFPVbAM1JZNjia8M5PoiZjbmJi2uQSiA6mYVI7wlDuHkDWYfonzV_E4TO3KR7rJ
5jRxY9-cZgut-QGisl6EW8U0SMCQ4EN7sUvDGuZ2_v6oF7141Em6tvHb8X0MtsI46lkh9UrNob8klzys5K4IxChfEbAMD6vdoqHmaJQ_US8wXTKId2rLb1Wt
yWIaB4K4pZRp452ue-kl8aPsE5ks8dPrJUERii3PDZe2nftBdRBWZ1R9aum06_FNb6NUpfOhIeoxHTVNAQmjuAfePIAqAyYe9ZcsffxVJQegLvIh-AVh46LJ
WRDr6W8A6ynZRD0Fd44UF0IaBEqZoilPBZf2ZFkRifGhPUayXFud0iAsbiJMAqfjjxEb8WZ6ZJnXdS9Q0ITYcuWmiXHq_KfPfjjzUqqQGdnWXkVn4IKAmzcs
nK90OJDaMrVqsQwKXOY03ynY6f-KnSNpP2EWwpdNAsM1fORjvY5elLAMUQKivUDigGW8CfQhvMXCL_Nsskwqc8DmSPjNdd2dB72sF55Yt0rTlr8MKxSuAeki
YAwMekjtoZ8Ad2rRbDyFp83msExEHi3Ea9Ej3m9IbZAv2E88CgBhWH0UozKN4o4XPK6U08HuL2KHvd7SJJtrJye218UpLQee__w16H0CpdPj6a8KDiMH00A-
7s0h0a56xXkYtFlZRCa83JOceUjn4EC3iquM9OAC4c471e5tjcam4UmECapA1W9-iasurzH8Pzpe-gs8XlsLY81n8q-u4DoaRlRkY74hLiHRbFX-W8k03ypg
-Xu1nF2JZ53miZX91S854SwMA4fz2l-VblD0Tbo7WQ2LQLFG_M_x0rLkGhCEc-O4xYBVL0dWz6FPSKMWFx3R4BPRNsIivwc3K7lxhReGkEuqsUPGzlQR3O4V
dhSNMvPZNV9BjZSHPTM2cPGTpGWKp1w2WDTbHc3Pjest9GG1hyk9WCRNzmaQojgUyOq8ZwJndVk4Zj1dB6yeAPYnPG5Xwkqt7mBNlJm3Ml8fB8pTraJebWK4
ncut0ctuQIgAWDVbHFYeyJ7PZWK4-vPb4OsF3vSfN0ZI9to8niUCDJj3oNLpwZcK7Mvt8gZ6ztBBuW_bVhyKpA30wx8Yy5WyZIS46f-CtRjto_9QusFU7zOm
8kI2sNOjcCthfM2sFrm8iGrSTuZ61znwgpQ4BnfVRx-52m47uRl6vqC0uZQzrlZmka3O_pO28_KyDWZH-8AnsuNmLkEx5iocwaIOBnhVxQdnnLFZOylYGpZk
oTeKZMz86fyFWJuXfouQ7mKp5mBEriijor7ws6r4O9710rsyqFYS25tZcyUXWA0Qdn7XbSONQ7nziYr61DNubhqX7576kRVVpA6igl75AutFYQ0QttOY29mz
4L6MOMJB4bdZm-io8w3nWN0lXsXyFWJL-0Zbc3I-kHeHLECh9u8Mp6vh617e4wBnnKkDpuN0TTUayKMttu5RhGYgyJK4JWMDpuc0naSwGZG-Bu9eV22K9PKT
ItWHiiOtxo3mHX1DuxCYP8tl_9E8Q3yyhFVU7vZ2XY0QN-jvHQ3nCMCvGwaQ7w5KZS-5m7KdZGy4qVYS2AhnHOZ6vqPWZ9ccDK1GZS-RYAJn3PLGgiRdGr2D
RtgS25dZYzeAPZQ4TjsS-lh_bYL2DRvzDOQIw-RK2MMRR9zmrNSA38yZfmw2Q7n613I-caA9OuZNPKJW4t4Qfmh2Dj2UQ6Et5I5hVES-8UA5nkT4K8sl8PmQ
Nsg_EHF1TUCZD0JvPqbby6zPLcw3KER9rhzbgLdZ0q4qFl-MfMjy4MXyJBP613I-AFCuta6uRbbAM15Kusi8fyQN9jkx4s79YunponBjXqVH-3h2_fSHLECZ
4RjeV2O42cPpuTHpsR5FjeSLGJM-XW3SMiAFWCQtWo0QdnT1DJv2EJrailKXyCM4nXVnuvPbSo9aZU-qwIBG-0xWV8dWkfbi2UK5RZ4YeF5nwY2SZk7k3YLz
mc4e6aecMp-2QdmHgl6P4JXdtR8KURDr8kYfHxpI-3m8Zxe705tZY-1nea-yrOLGgvRF2QLgV0w4Vukv5zm6GXW8eFa7Wc7kVzh-K97PZ8Wsmsxc0EqJjlCt
COJuZ4Zr5DeQNtlscae0blUTbouvapM-cGH39NY4vIKXdBirlga4m15OIrH2NPffQtptUGI046fBP4Vu-yV7ThDZNUERGa1B_Mky9TYdBDT9GmcV44WrFA6_
nFvXEi7WCaRqdxB4F6aeGNAXBU48xiUEEW4yeSKFQCvaZKyaW6HGZUG8xbvOWO1XnWFQrlYEGZiQNkL2gr5yybqOIWmoRedbymOXY80nWbI34dJ0k2KigmIi
ovrLGo4ON8HgsDk40X-n9JX11_0SQ4ki9q087z2L193erLX1m8GK_fZj2O906T3a2090GNY2051QuYN1C3Fy6NHCm1QvBSuX3WZOAkGOA05RfZk6XoC80WMH
8YDW-_W7gMT2mIxnnz0J2dQBwqXFm9wv_tUa8s3ln5gAHi0dKe-X4Wn2n6gaQDaoFfSOOfe2-0O
}

