sprite $image410 [260x173/16z] {
xDStSaD140DHUKr3Pkz_MsK8HUy-y2AcR6AdYkjwPYHsasRM1eb32MbjnHidKSRllzjM0WJEGUBS4YQmcw8BM0iyHWK9oAx0LIZu6M3H8x3a4LZo22nv1JR1
Ap0rmLqjGSH7m68Fuz08MEnTL7O3ONaHn1rPLuUmm0RYFWdm1n4IO3SHyFslUownq0niGCGRsAq5ZdqKRCu4Ry2a8_yDXpu8Dap98x2rcx3K9H2W2O1fWlyY
336qSmInHq6q0M6Q06W2e0b0mVVGEWDG4y0oqGZa-kqCF0JQO6W4e0sogGbe0w0DuBSDqFeatg8MzKUzUIWv2iDWs9AjTlNzt_OMmf_5MIK7usN6-ROwCksp
C4gXnIWEygZAWYBgERlOrvN7nNWC8WKGrsRUhRpHBceHeIL78tpho_59BGk65hr21Z_YEUu0KFC0Ibr8qFk9Wzt_W3i7L5xHOfHn1u3iIKGFEg3tTu21jFA0
7NHGz4qT4541vDZ_1HQLLgcKvL6b3NJTw1pGAmUQm5CuOFz0w-xCjuT1DUck2rmM6fgnEW3ot05bKtcRma7ja-BpNucSskTlxu3-wu2fwkf1gTbS3d02-38s
At7A0P0N3cnPQCqzR9xgL0xamG6TTK24nN87fPMYjxxDiPwv7HG_wO0LYP0xM76z7RdS7kCsjmC-w-1stFJIGMsGuQkmkHpKihAhYabFEZ0aGkg0fUoeQyjd
Se03vsxKI4uvs1B1KmV84qm2jsbo0WSuQaUA2do0vYSS64Av0qSXLh7oIHmKPYg0KBdig7RG0MBakGEijzwhC9_3GOyXH6M777RWYAKEK3D31iLy3aW3U6T1
3Zf0q9yvQ9i3k1fsyEER7LJlmzpbnp47Zc3kWBkJncRA0oAgul68ybtFGGV8SiyTU5dHJOQCEsZVue3Dp3rob32L7tI0HCWTrD9L4ZJkuE-traWvlacmWmwG
29OviBAXcmoPsm6GSmxGgCzg949zj43luS3EEi1rxqcjRBNiq647VsVC0vm-NnpSwoDUMrh6dZVYtVSVrpWm_p8V-7478Ra3hCTqNNxuzGFSr7AD0xxNnqfd
hutmbZjGXCb3Iwasc0VuRDuL3ZvWhbo0dd4GaZgWUjiMIWFdmHe97zYzn06L1sgSSX2KEU1eI2tq7NKGbpbmIXISSY2vWmqbygvd6r2mS8M3qa4IPnq4fGw0
s_fRH6xhgWCE1cS4vOLa44mgGG1BFD1uGVSEUA7sgrxnpC6ZA4JES_6djjqMF8Pvxa16ts-Su0w6KGU6NFC11-yZeH9HpUSTgZxmuNtGuasHrlHVU_TXApSG
n03KYDvF0NhzL-kSioyAuh02uUtmyeqkhrjyc_sbCRj1y6E602aZM0R1B46W7c7t-mn1YqBGha3xmgpCyZYpID7ir5Hl4Eq6UUMox0Kzg1c4MJOTrsG4K0-0
d42WsQ3z9WmBlGRPW4w4BA3L840r0iPW4DmzGq26W3K4h27WTVfU6FoSzYa0Gu2akGYVi_KEmJ5_phWyCPqr-3cfhC7byx3d73Dm-IZaveFZEFdlMoVkETKC
m4LdjkKi8m3hyci-1m2klEYLwm6E_v2OMxtmZAFcfWUNV5nFac_tb2IEdGEStS4Dr1D4lO5sWj1ke2RvZS2c9gkz1cYl0L8lOF_Dhs2wcn1qDo7Q2KAvGRGJ
BEq4T1CasWcMsjG3y9AJFH6y1G
}

