sprite $image380 [224x237/16z] {
xTthTkD630FWNcEHd97U_srxLEzu4wm2qubP3rdXVu_zbO0lsTlsXAY8o5OryYDrTNM5eleUgFLkfrPLE4IgMh2aDZn5XJPCKD8gGhEFGYqsGzkZdvVqhm8-
AjG2lcebHH-U48LImCTdMC07GZnX2L-rTqFqyP9g0HyNbl2P5fWX-5fhpXbgJb_lpLlIttBw7X2kENtTf5X9qNUvQ34X-YwBEakQqxSBBRUG-_OKc27rmGpP
DwUKlW8pP3uiAV_cfFbyLMR8VVwIgkRq-OMovlJvPoX9VVuPIbAVlwIQpFUuC8ElK4dzlcJVdBYlm0ofhy0CgQ_03Aclm0o9hqX9kO-Nr2bCwlFFK7Fw_3_0
K4dgyyymfO_Fq3u8DO4lrmovBwAaCeilJ9Z0b-WZ6_SLc27n1PRK4lWIp93xWakQneVHQNwF2VV5btHvaK-_WPlobtwvB_JTCAdF_qk_cjJdds4gtro_zCjz
LMR8VV4pL6lfVFuPwlwesNp-achhFR6FbtGyObOVBwcsPZsnZmlttQNsyHdkZrN8XpDilLVmOKdB-L1OpeUHuhxBotodx_ITlYMFx_ITljDt-axVwJjzf-_q
dRxJT_ha_-SxVQVlz9s-qtVwMcbVCnLPolfstPwbf6_NZTJqlGCkrNnuGLdA-L1OqMSAmWA-TTX8INFvC4Q41NnSMC07GdolAE7Rb9Gqfm_JYB20Zy-mWe_F
i8AFlrTKy75X0HyjgLJmyHbMyF6I5l1nOGKVds457vzX1H__o5R0nsSOu4jPKkvhsyj3Ibh1nxyRvlHXJCaCq_jM5L4bCqpjM-KQ9ILDxFi9iKQ4INtl4UpV
e96KlbK4V8sy6wRpgO1l3obfBf-CW8y84_bKFlMn6MRnYH0VBMa6dmZtSU7iFXNYymYdzA6E-_WCbtbzAjI78IMTnSTrtDVTCuptYMxtOW_xEX7-fxv5zjpp
cUcZlkwOORplzf3S1q_GvUkEaaRxv1RblZtwg8yButtoCSn7XCpNJSb7jc2VO9JuY93wHEtU32N49uVXFZo1myT_W17cGnu_8Jv1__vKX0g3V49o26H2_HNu
aST-oYOHFg6nkqAz9mGUB-cpVIhtidnDY3wL4IhKv_g8YyzG_IMzlROmOO0FZXScH1wP8V75y4QsRvGKnaTE-5JVHHxA-hXm-817XEXh_PerOdd-6_AI0eyA
ZtthDG_e_fAlv6ipnF7n6Q9lz7CW-pENX_dhApD47Z_XiM_4TSdrOHT_9LtP2GN4JCXz8_tE7ULxyGhzqTORzHqzufu0dlj3gLzdxL-ApuTtT2ul-Bs2wwvn
-J18b9604oxaXAIQjnpvS7x7Ltmsp__Ta4VjAXkA0z_GiVmKEceJyv6DL_DMmlLNt-R909ffy0dzGlsWW_-U38y9IMq2toku3Y5j-437qsy-q-WRAWZfy0uW
Lz-wFPPr-1md39uX3W-pMYF78mqrcq2eNCV3WMQXmlKQEaCStXDpypr_Xk--lTo4xK2e5d0yQ6Z02RLTJV262oN5uQtRSzDN-ByQzMuuX5ZIZpe_pr_GFL4b
NU1ZOSVt2WDUX2zKg1ilwNlTkiNvDhNGLr8Kec-BuUs-4Nk5SF105-2BBYaAzUPh6_1YV7kYJhWS2N_uLkXcY2zwXWeFUttZjzQtGDrXBonEYCIH81oUBtw6
BF7dYv_X1BnOeKxWYotfEW6lm0m9B_wLT0vUu3SdYTTHNdn9_me_dZDhmXFYyNWiXn1r4mXr0bte35MVhICycYMgf6lOxUgKrAzBy84cI1V_lI9-Tra_q11S
hXbUhWauNVGCjJbnA2IwYMRe-DNBjzq5mWwwcKgAlxpfFTx8NwYRggJ8uxwt_NWO1Tsa9LNRTTHtkVemRs_RDgKGZyT_ozLl5v9OuBU5QZkF-lJjMBQejTRW
x3FC48_7VP_ef7tx5-pZlzwFun7VyVAqzHxiuxyYupyUzrtUoEtetKDdw3yUlyFXxgntufjaXWgwll9oul62-yc5Zn-lUyi9noE-5vPKNJVu-w2RZV2cAQas
rrFaFAvxeL2XOiQ-B_3fjMWG5pgFv-SntHmpLFFswoulKk4lAJqU-tuZP7jSzx8FD6eFFCTc0ZoevdH2HHttjMRBJr-Ru7XyXlROKsnxTF1i0XsTeJOoF2Ay
bbHcq-49sJSX3hHbZ0zuKmaRxHSNwcBJwL183k0GpgT3uJUUul1jSwOD7tsE70YRdImttrOrk-zLkdy
}

