sprite $image312 [213x168/16z] {
xDBH3G410CRWPrVOVrlvPm2kwRT1apxoiYIlI_Aw95-Mr9Igaf9ILcfAoaf9ILKvBY_uromEOHRWgm9X5cDx48HPZEr146OnjWVXJxDUZh8zoDWU164MOtiG
X5cCxK4GPZ6s1q6OnTWU164MOtlmMRszxZQkmq00fgqBAPB1UV-dtMrJDiTmTg06LLs9ltlxm9b8JX7WM6vP6BK-2z_ITMxMwoYLjz75gtKcVSpY6VodITGM
Os6KkxKFLBjdJHVA84QfMg0q5hOC2wEOLUKmRPqCOfImc8XeavX5gsLs71ONKNSBbAvpSy8eTnSn5JM0MeFrb2iHQypM06hI369KTAaPiwc8j30jnCA7hwcO
0jAi6KGeDxDGkQj8M-ls3b3oEAPQYsDgAHP0iSjnrBuoSwkKsPiqSmMe5LbkwgsPgIcu9gsJGRCZoyp0CRKMoqx3h0eMjKm6RtwwApLk5aVlYYnz8uNfV62T
IIfhP53DqNjaJoHEARS5MEOUgEvmJkzJPhuv1UcE-eAgbVGvF3DBtGFLLMbp_L-LfwsMcZzGFLRTgxkt_62LDYKhI87gi8X8tTqaFQREbq5rVqPXravK_Nsi
fbUgfNfvyiuehAf4nJz6ytpL2X90GLQcv9yZBrRheZ9156OTlyquFKPi0fQw0rIFTL2vFgfLV__shkPzL5zrU7bdirzccJj2lSxYEqf_-S5OtH4Aix3AtaYP
HTH-ZwNcVLHVPKTK5P5NL7e92QFwBDaJdr6QSxkCXKWOrMTb8kBJ0t-cRPDhCgX8Wr7zQhMy4QNJc-rxvh9TKIqr_mOABgjf8TfEZIgPETMVhnOWzL1zbkbE
MrCxJjkOIq8Qn1fFmgW-IvgT9kyrxRBdrcCDBbCVrMSXPE5CLFOjRJ9qMRXC63LAHKIvYUs5o_up6GGaW1h2eifxDKk5UHVhiqOa3wC6iOYvRcQoCwSo_EQa
vkDHVLNEp9kOvRtiPUZD2PCmQX1BjyARrCIPICPU2249eqQnX8Y4DihsmkY0CW7K69PAaurvv-U_N4GnQsJo0ZLE5RUAkZzXtmUhT6Jo0ZMKjHVcJSzh0gek
IzqlG7LPifLASYBr_t-imv8NgB4i8Jh4hp7BOqonJ1MGhaHXbHrofim7LNlU5sO5QG1g4Ek8Alj3rQqMADC5AC12g4nxQBvUBJKVXnhFOgv4B7AibcgJfa2b
aRnngF6gnbmhotEr15VBVIngFEl3mrpt-iKKVfzqk_tt_UcfH9WBaNpj1UFxfDiFg_G3mCpRKxN0HnG6a01g22lEgL2LKxM2DXO5I4DPZRdaGF4TbKklMXEG
C2jGYL8ay4uZgfrL3KxUU9Ko5zhUIG7ZHEKEnAkQXOHPmbmAox5QDRA8KBEOC4i_orJpfuhlj0nHqv0mIuMvFL8e4gYDGjKKeAOXXGfV0MFUZGcTm5EPC2jU
sa_LGfUbsKYOTVSyCA4RS4xTWEdIQZ4HXmgTKzEHiCfKx_lQg0mxV07fucefSqtrz7G5K1EkgLyjY9gLX5MDMVIUmehYDxK9Lwin9tnEpKx2rU9Sq4SU5o2X
43872QCmAKmJgjJ-FGki2R7Kq2om9iJ2Cu0q7sk0QJxL0D9yh3vfGHOaXMb9LcTDQwewQrgJrI6joOAabLN8j3GBaDPcdKXXMfm5rhIs2f3MPVdD3IHlNTOR
0v0MPeK8c5PL0TBQB0UajLaEJ6kh06bjrXZJNm
}

