sprite $image165 [135x312/16z] {
nDOBakew38JXC0JRwcvvzh_R6pFAuzOySgemyR-2hoG5_FbgjlGvEek68efjOUmeXaFiMuCGmo7Leg4G-wCw035k8B3pXeyYmd14D0z7H8EEudl3Hn5XE28Q
ZuYw7iLuYBqSkY763eJMgmv_vsCXrhaw716zyEOU2R6tLOOZeWu_cfT1gbtHy554yt14T88O3R7Bmt14L4_sCM8prKOsV1J74vbkzso3gv-trWmRt5DH36CX
dAPRjjP02EJJD1KCTK3kZJ6Juo2WjwOb2mTqEOJoZN7d4emE4hXu7plZLhWamGK7haO48yOXLSWXNWIX7vgUPRPSefCEuB9HH9_tkQq5mQXmGG8kGmI3B1_j
esr9BgU33kAz7-bt1fbkiHQwtEc4wtqGodzc48-R7HXoo47WWdqS6HJkOAinOY04SGrYP-YHmMUD8PT3GkzRfViPe-I20oCMqnD2kPypoW9XAnWIN120dliu
PpI8SIaONliD1FJex3PAApRpnN1vfu5G_c-CUKxb05aPJZae0_hiuvmnemJ4ZenA5qG0NH3d39QK3v1Wn43SW4uVwJaZvVr4f62eniyPqESepXd9K092hWoN
lewLG9Tzd3EAxB2PZU6ie8D4Xu_qbD7AAUsRsHXoLtoz7VPnna1fZEE9Q6DmVoM-jezp1WLuEK8ehWpt_PNO4_6TOP8gKsi_4UsCyrTY7CLhZ9B1XL5O3jyC
TePBEdibKlugGofe37SkbFr4j3CSVpwA8FUN6QpLdunQ7Jabsp_UZK6NufNO1_6TKUJLWr6zP28S3QALuNJGQTySb7TXc5EE9qEr8cKI___drJeLQm7VHj65
KQluPBIOaGffHmZrP3W301mGNHXeZAMyCf199AEmdqXBbCY0OFz8-p3SIp9lZ8Idmp9LMHAT5WCnRWKaVSp5AE_64AISq1Xcz3ODBLNcp7eyaJtaZzljza7t
Nem7opmNPruKoIjDmH3vF97zzttlCJN5lIyZFUO7t1P6hTLX5embItRyVVyAyxHql_Tcf0MIgF9r6qgPt20b9Il7zplIRNeN8o-GhESrL6yCQeMax9KR9DqR
ubqCOqxpR8vSL5C2LyWNepfoGExJ6naP9QqdOYddn0sICkgIrXD97-zYH0sIf9B-uzrSS2RdLI1wNrrG5F3lVxTNOpj9zwTvIHecApYs0HyHOmgugXO8l68T
5RWvQFyUmX3XTa2yv587M5dA1Aioie3Stinl_PaPZCmeReuL8f5PZYX9O5Ut26It5eR4__xhlw-eFupXIhLWjdFcfOgebDd2gEggScY724b9pgm_ZK6ZblOG
r4xU3Eqo2bRNAl6CwWHE_EhFOwWY5aONmm5R8K9915YrxzrAIW3cCBhxaa0PJ67VaZT24hWecbRTyaaCLtN5nkWc917_MviaWBambesK3sAmfTA54G0b-GeH
mkHHrVHAp-8eHfVuPb-EaC9sVO-0gUcbSFeKXexzsHj6oanLWKi1uEwLoh0fZEemqv90pmkZ5V2iugdl02p5pC7TY2Ay38ZWaK1bYuYITdqt021COnZ-BBYx
68y4oYm4R0N0-QOmrXLlQy5BlaZJnH5c07Pz9tp3sXJ6kT1sZDQ710OGiK0pdPp5C3iBPcqCwLq2ou7jxxCOJ3lEOoh0zO1i2KpxjcDHCOe1Egu56upWpG6F
xEvw_7qCmx2_is2J756zGC1Ir990Eo4oXI4PYISdGl_8JDbIWbqLAY0xzexb54QcEd10B9FA3dXUzjMv9R2u_7q8ms9Be0DkEqIOAO8RewgQY2M1m8j36E6-
9L2sSkPs7aSyzXNC7hMlREdOLz20vJovGEoohx2gu2X6TFTTH0bRphFTK_2gMmBB9p6ex7xiwt4UXG3NaS2g7hQlKiQ3OIPfEq_0afuB8qt36DtfJoTmztdo
E8yJOD5Beji0XhvX966v9D0U2KmYikMtyvXvIPbZ6DNfOBK15XiZipDN6GsxdSUKhlGfZ7XvoKm6ICod4nZcAPtwla00sXI67-VPBRXWXRrru7JLTmFC08nX
u5xmhXjc7nquF0gGnxw6C2x9CpqIU840gLFVwSCOxcV1djtVaS2udMSKWtatQPc0nHS9xEBZxtCOC3kILmwOR9sBZWJgIE3fMOvXyB50ktfDdhS4PcGN81u5
cC9GaZBS2wRwb57byWr50jdfsz-7C29JhOLnEyy_QQQxsrDXoEvUiSeX3EF2y01u5XnAXVaZWR5u4W3YpsD03YXiOLJHqu6t3XmV2Kp6nj0KHbSUxKaQR5ze
sqOVZ6ev9p5ORn8eCudOJLe9bcyI63Q9aUhIyn-MahZgEmKZwqXWlajW_NcCBYcUtfSZfCjvBCFYT0APOnZS4bZsO6YNKUqchJbWMX8ejocCT9XgIQ3k_x0L
yEmaJdq7i2Lm3YDey5mIoDgfgSeYk6rqEmz0MQIFOKX10mseOjGjWRj9kvqd3Eipcy9GfHHkMmAJUZg1CXDmAG2C6sK6WmS4oFqdmJuwS31S3Qda74QMFEkS
J1q9V420kft7VH13gc0Ta5XcyVK_RFfHWD7TK1RZd8m9WDyS2Jj7TVnz2YDOAMLI9OaEc1nnIo0LwwZmz2mdC1P0IYMU436fpDGB1EmALG4Pfo6L8nWwCPgr
DoR8g3msgbtfGq1sSRMrHp2gDi02kP9tsoZlJc2b8QyGuGY667UCLfxaTMgNKR1wIQ1vTYT6YtceqgyGgGqIaipUx2jOenWRv6k8E2K5-BJWYZw7KOiZuhiX
8bZKynysRNGtpePaNY72F2S32y-k9O5HnMcCEqIoyYrvpHJWmaYwfZ4UaF3wgEzc08BBleXvZCEHnLFV_QhlZmJwFCO3SYUldvjtSGJurp2-dxmSby2KlWEo
03uL02ORz8tlSNotlflYxs9yhUztyivXF1G_3f4dUSSmOD_7UEfxdlekANmC0o_Ny_qoHEoFOyJ6m0ly2KZbb-ITmW1U5Zy3-KpUCGpvBq-6v-PLpM540gyN
9VqwUJt7C63hP12_axmnXE5Xy5-6o5FVfp0ocJ80lvUyGnYcLBN1WDyAaIaCTsKR58RqNuV85CPg0HlKHGgmb-b78A6iCOokRaDMTJh0i9-6o106edfXVACf
WLBWn_KzfZ1oXwYgQssBI-AFGsGCerioPA_FoDEijh-6ON9SBOFL9AusAir2BVjEycRDO9JCj31CQpT0TOPvPWKGVsatn0fO2a1mnIfJsKcmKhxh-pm6TeFF
07Ongesd5-a8STVtUOnx40EnczKtXcJcJtsVndXU9An61lZHhBOu2Z2FOUTHejV6q0r2H1UN0inZ97SFs75UIDuWt4VbAqIcCVnvj68EXzyS1CzH7N_FdCCu
t_c1Gn5Kfp8pa1dxCTXHW34CbuFF3tfILGvbInd8BgsuQHbUDd0eF1YPKMNF55MeCiqo9QvAN-7mtgzQF8Omm7t3teDs9QeKuCQewafOTxS3hrVCO1WjbWIc
8mCuZn8bHrmORQGM1gWXZ4xVlb5Y08xxtQgT7t3LK0Tp5gEFVUtZfxX2XDg7iZWGtKKCOY2qCBGdnutt3tgAkrbTXMK1EOcHfLncthLux9dLSKIuDWQZQXIZ
EsLG7GaCSrrlEDnay2oe8pp6C0ZeaS1jNxdBwFiFUgWZasCOlGSn123gbi1qIE_lLi6YKcCON0iE0PPKBGbCTSeiKxm7gM66mKDv9a-YMymZWMVaaM-F4WsO
JDXhmR4dn_588670_IXH6iNud1md-34vxlSFUW-RnV2pO5DtF1AOslObktTi52E5Ut8y07wLm8h7tmSnB6xdWO5kSO44g7rKm4xUCGoppybnIcRw9wKbWHLQ
4iXha7hClcZnDZbELLys6glIHmQyqvU_TqvXfAhiOtAyoX5vxAjRIm8xbvnDnOPBsGOQm6joF2MpHm8BLbi2WI4Cantx8bBt59KKy8FHRS6eOGciE9t08W7V
5rf8uYM1XUYaHZ7oI63LAbLycnmdT2HGtIKRn81KVUohkitV9iS9PnsCcfR0bkgnBtkR77T4MjIMGCzf2Qp0qmcK8oHj6pKQJ4i2vJw68KDi2OpT2GHFMou3
Z_Di2On12GmpjN0cnnT6Pi3L-JOvxaKEIg2j1Ji1h-0bWLKYGk9HWBqZnZ6CvmQFxcGy4YX7y6rot6tMDyw2sRk_n7mcn_4sEHuvR5zdmPvV9L24Fyx3OGpQ
SHxMaK2zIU0pEJwC8LqBjeYFoV65SMxu5oj6CU30is3kSpaI6B6FweI8Zs6O0s_E0sfjGkQMm5PK1ros5K036BxiIvRS8CTvUfVHqsQfKC2xOk_O48PbPhLz
J8xlzTyIc5i2onRe30OibWI60s7ut-Cyr6LVPQRQ4cX365PkMm9b4e2toN4_zjKcCHS6fp2wiuvzXGFyc1n_Md0Lj46CxNcs_Qe8Niv3YOZgkmMNFecHodxx
3_i-EKxGTIHGrJcAqQKowDYNlqsE4qppN1ZX6iRe3ZoTG0LSgkCyRW0JgiYvs8ZN2rvB0dbt0lkKqRSEt9P0JM3uDunl1Gai0V3O69bPCelEZybnkkOmrfq6
Su0jLn_xEYEFl9ndVpw9iJO4ooo2-KWWGTw3r00T6CNO87lOqC7FoV7RUPWsZR5FHey47X22JmVEHp3gmdWsnB83_bK2E-mCKezZaBv0I03n9e4yHtK6gOSn
Ga5R8A3Cf5eWWOnzL7RyVHR3gFGT8bGANhS4PgoZAkuGoTdOi33uEXbcPO1LHm9RGNYVoN6DOgmlziaWikLu9B1YIM2l49d0uEiTWv9iHMD8ONPt0XlE8u4-
WU7utmtYW4KQbWUwfC3p34l5M1YSmR3N0R4uFs-2EqGa-LidiEKsXc7Y1MBscRm84Ruvi1mivZ0gOsK0y8t5V2UlxJlDGR8sHcJd94OgTeYyNjXDV8ldmakp
g8NXdCN8p7qohzUJE1V8mjBQ3TcDaNyUOu5mB_x1U42E139JanZhuyxJTu970G20RZ68eRCRVDR-_ddmeRCvZDoNEft-FH1pfo-G831wAB5Yz3__essG3moI
iGBOqsOnb19b__utmhw6YBkJPDWAaUbCaSl-NznvQ3SImb1q2gY1pV__xLhI4HwopOMnx_QQUzwJb9vaN3VwRKHKWeZzj9ohSIcL9H5cMFSV8qBCOZ2J_kPf
8-em0sN2dDTi8u8vzH5bOaDKv1mDGB5Q690JPOASLXI0mcY1a0WBQnZcWmdEqG0WsnGhOETCaFQDgDPY1uCY3I-6-IGDXLL3OTeaSquRL_F82LXH5R8yy4GD
G9q7Hlk9YW2NwcevWoSHpPoeuP2WDGDx0RQnpTbsneg9-p5DOv51OpnNgCt0xgLO5DIRiM9mbiQwqwYHznqKjR546AL46ao4BgAb2CzBOrqJZwNaBVcJFO3s
E-Ybn60mH3CCypIMcqYM2ggHmGSqRJaddGG48qf1tmyR4LOcQgZ8jcrx8h8gYYx5lXsV1enIoAy5gY5CNTZ5FMviwg0YN8isisipJfHYNN0yea6YkHeXWku1
72EIVvQYn0ofvLGDBoOHSuW05HiHC51YH9c5HJNGcicJIqd0fOW7xY9I1S6NrwnYOICD91MPkIc9YYDy4C7Y8m8EzalEhe604qlPK8eJ8hqP_H7Jbi3GDAYd
WKWpHxGbwXfTnFBsnIa5zosxXYP0aHTg73X7exORcKSF7v5rDH6KAX0Q96mYGe06Jz5epXAz3CriYryIB0IXmSICQCKm8az9eztnPkee0clIRWA_6yGUY5Kt
uOhMDf0vFkLd5-axuyJTk44g9CmK6bCa7EcVNRA6no3YTuEq66-62DxKQ7yYbU8QHn7i7lUxuR-FxwRH_eP8QBZ981AFw8cY6NWhZVOFAhk6Zyam8hwmZdRp
NYdjtonSkyQbneZqXLMYcJTAQV_dobr3gncQwK-Mkz2BQTJs4FckqKKeH3oAT-v6UnWwQ5pkLuGPDP7Up2iQxHcMKhj6RuPGPSp3L-PvZVOi41ez47_WmXb8
itXbHDiBSEqQTn6xdjuCFxkmxKMkqZMw1wa1P7yqYqzejDTP3XfZCm3gmGzhj3UHmnKv9a80yFY8jhUHmnKfBXBDm8CQRGeo7BEXcKSqsYngwHgrT15yx8gs
YPHhlwaXyjZ2jic8QzY0k0Zk-_yqsWbSIooDGVhCzpyrhkqKkFQdXvIqhli_D6exZKkvrbZSmkkoxlmtZNOgrJJS8_iBh8f6z449f_HUP5rK10hbZ_GnShKh
ud4ewxwF6kr3Y2sDn_6RHliWOXebXSOt9Dn3DVYdHliuKcviWqRx2gKKE6Yqhr6uQqZx8k8QwTA-Z5xqhRtBBm
}

