sprite $image391 [181x164/16z] {
xPs7ZkCm34JNLMBH_V_d7XmJyAuHC9Q7Wh9bKAwWFSNlXbI0ytvi8Q6SrdMPft7u-2QPnC9RDlvbut_l0oJTYIt72OZi06_8luWQvZbs07i0QNsd1p0aWtDp
y5FU-Bi_W8dKm_OVmBGzhQK7zimUjd-0j10ppJsmrqFjQcucOavZ1-en-shxsR3NeO_Q63PrKNjX09k8E4yzwcyL0BkZslexrPxxJFPlgNOI-Orgqp9qcUpV
Kcsq_Zgg_JVPtrzjgx_hQlzDzc-fziGYtqpjCJCHWDrXiWyhCn4Hy_UPx0inaOM_XzfJFf1ppYJozfDzJCm7yYFlhlPWPXYp1N6alThp2JaEcvPsDNSsm_As
QW-hWnoWDdCUMzPSVfvtgxyfEyZDrSPhpWskTfxQoEodvMJ7QoxtKHkN6NSaNkt1aHd01YOxK7Flg_RicD5BRRpcsgizupLN7yRLHckkYoDfQ5Lp_IVxB0up
eBQqL7jLZgKsjNMFF1AzjAugmXI7ROvesP3B8senVhJ-3Be1jW4Rz7D-kQksGOi4Eq94p6oQN3Y0KtyEj01gn_BBwybkq90ZyGSG8X9oAiy2E08SuColZnGc
baBE32S0E_W1679H5bK7UbYIZJ5KRJoqmrjZEj14ATaO0zN6aIqifQWBpS8vfSoG8_78hw152C0EHgRDZ3t_V6XXoYdZQkFChCMOjSZiGujmXjIEHoxP01re
mTN6PTO3MN9QXjVGfZRa22wp8LDAMQUNqAOsxWXkXd9EcRLSWSRLnclEa1DfkGmDr5-a6RITeGBQi6lg3pVZGDPDPZj31JJk22wpQZsqZzsqvXBP6NneEGAh
ZTUS6F8DQ62ousRKG6DgupLdo00qCDcXciEXuzKcf-OC6O06r0Pa1g01jP6Q0w11Ht2PSMXyQVNDe6HcD87sbrQqvW1eGErxCfiP83IkjY-pMtFnq1Ql_h2Q
mw7n-lDbFceEXiQnWPe3e66rQwucmT38P0Tang1njUjdTdjeVsbzVJM9XyRLhZ03XiRL9elp3Op6G-Dg0pK7GAEEk5UJzj30qWh834BVNbgTcgjXrh426bKR
a1c0HXrHr0mSkdvfrO8W5qiLDEw85lTguYFhaNcSncb-aa7md2SxKdCgx4U4yoAMGBKTCm1a2-LrdIGmDjcTgmcAp3cjys1EXpfoJ-QY_3AKrcMmVuZXsDB6
Z9JMlL649JZao0oQCLdb2ULWRCmCNsQBK4h1sDN8SadcqOWDEYLg2OtBR6QSe4EnMzISqPwW0nrfKtDdw63iu9exP3v3HpeINdC-TCeHsF4rTmuhPoEESgHD
pPtVSq2ns4tDi8nPpP4WjIEGAIKQNxuB8_33ncMcd4XqW_QoIA3Qk1dxfMUyyfgNhshJRMpS37vSCmtQoqHHQZkNrcioFv0BNNpDIumZICsP6QN8NF46em1i
IERT35sh_lEd2cNG4LZcaeVgDnYXansekOSPF7rKPq7LFZFNoAn5bhjlC8Am8PcbmkR8oUuY-pKdETsbDhNpJRNhPRQQKqfP_js1njM-QmPly5fMx0LkDvTM
jTJLdEJzTy0dZQZzYLdEtF8rEP7k0v3stodmIKEJ_P3ZPNYlEIKhF0K-QMnfrUlPaJblMjjVo8GY-qih3cqoao5NB1t8qef_qdHycLrA7ZqGN6qSschkG6R0
37HfhJA33pEM1k-IkhoqribS33aD01s-j5wL-RCP1CWCJFOQQAivGwwuMxLRMgjbnciEd-nNp32PA-zM3PVM3ZM7JtONkV1XHgczMw5BgpFPWPhhftQ7ciCd
-qMPaPgBd-mTQWx_EkevCbvpxPRMfz1dcR6QYrURHPxFR0LcTjF9Rj3nLvE6Iwj10rUJ3ceRT8UP3Ioj1XryDMa_sJz35w6AcTrFROCsC_2PtJupgMI3Bgh2
5JNN_UUxxSZRRqf5pNLLMnvAY45NpEo-Qkio9D4TschkxJCFE_i63THS7tOIeEQwPMrMS_y1
}

