sprite $image323 [213x312/16z] {
tDg7RZGt40DWjLM7_VvFcyAKmOypvbPPqOg7QEd91ujtOlH_hgJzcKzJwQqXtGwfDaarOcg_fDiZ8OPEdfKp-D4aLWvXqsBWvDbWzVO-rTB9atnOEdaISoIa
MZfvacgEXDWZ8UPCI3T7Ggev4cAFX9Wp8TqS2Vd_N5sDiHeZvan8DqT2JfBCiNeto1g3hUedK7pM4TJenbXZM6C9obIr1CLd7K1PEeDZM6C9QXggbg3cD5Gj
GKqpPr1GtycgtuZwnZEOlWs573Y3LDJ-CtZvfBFugDrdC7lddCzAjTYe_Qpa71AAzWZ9H-sibgXShCePfACsLwj6ztSkvOh1HH7EOF4mgTKgN5JDOo-h9eZ8
rT9HnOMwymnc3mw_MZhAkTXtiKeGZrejX8Z2ltdB6QpHIM9uNwrEHJbVdd-yNo92cowleX0goZsjbfG93ldCI4qF4wLLQxLCuYYfDgHSois9XdfKhPhUVE1L
hvt2n48zg1RA8_-4zgL9_zRYeP3Gz3Eedpp_zIaB3j7wnKCXgI-TmUmaQD1hv9E-DEMAGKCXQpUd4jvSYYxv1pSjJ9HUhVLbc6-P42PglLeNolHbobqJmaCX
QS_jlVhR9gJpK4YUprbYkjhDS57ErySNml2bgUReDuyICG6b9RPd5yBuOe9eOPGGK0z7oVLo6wmNH6z7IQMYdF_lrSfY-biKdEJ65OE0UZXAvCCyulTUHF6g
JGi5zN2KL2y_ZfBmEnAV2aHw2AX7rH9JX6ZbHoJfJ1HkJckiuBwCJwMjX8bQhnP6bjAYs-6Xa3XMM3KfFwAbK56kpFLHWiHSsuDKAcg4vL627z7ZK57BeoJN
jYMTYDBsVc_Sy53wtkSctKNbPPG-IhYXehHgSKD4ATLYgpeLvVoXQdtGK4WuL2qYIXybrFIDg3eMHWatXO8wNoqUIXybt51Gvwl5G9slrWSFfUzzRZYeupSd
8khWAAaKrFbgyL3w8oGt1DJnQdKYId-4998c5QNlVHPfSb7Vl_SX-HNLF06bFq9kJP-8e92H2IZr8NptoNj5vTHxug3IR6IMDFUbKtcqm44bQhNwbBoWd2-Z
U0gADaf0qb3umXmN0qMwEQ5CEWf9lKS2YlI98IGDXI_C6WWemjwNawUY45zHBG9gQxNavEae-LUFYu7QLosG5b186ZqIKDlslf0qrEKaKYq2wd6rf4phA1Vg
o9w0UhhtSVBMKLAjdWYeXzLII3fA_jKj4b0FgjNdV8H2ogYUW5hV-q9wZaAr2AZrQg5CZr1wjMfVHptV-mff4OLS62MIrbPHp_T-dtCh2gqkde2wNQq-vbwK
Z186IlzVQK9Ye31A4WUbFqAYJ2oKxFszAFtcX3AnK58j0aeR9MCIKL8j0agvEKqkIlR-6kgQyS4lEYQZf5gpCr2erYcKytqM2WhLEeHoRRHn4L38E8LgBeqM
EQX-38KlpEgjeT3gRElu8R6FP0ebUzySoddiVMCet9ooAPHKonHAzhunb3n2sa79A365ahrl2YLxtnHAgcK0fLJhE2fjGCaZf2cKF49QG-6bf7XBA7dVDuO2
1TKoXiBU3py8rQkx4xplMqB98wGv54P9EORgaODolinpg5a30uKFYf7Fe5BiQ3K5bNjFXpfrZP4ug8YzV-Y38gDQkr5v1dc4FF3f5-gide2IKN80XKjRte-I
HyWZA5pQ4W4bU_y02iU_1GfAgHORXMeLJq0frIAZa8Hg4L3lgpKfAAaM0IMZv01AghKPXVWwomaKZZ-gjHk5H5Jh00hLkWWevH6IZKBow963GhNy2HIEVmtR
KRBt3w2aMWIKF4AIKKgr22Yf5WcbnQDQ19Iyb31HMhKy0INl-oIKdjXczXGKpdSYe6uC7Unz0ahUzm-WKAqM2IYfrdUZPEyJK39AI2WziSyyjgFaVVy42iT_
DWuAU_yColanM-2WdA-7K6uqt9osev1Zg8ARapMKx7r3ADdxbb0oIYoXP9IOGidUjuMIlQ-a_3GK4jieNaFvduP2qXYNAPHKonHAHeabb3n2UaiesVksK4YU
BJv3-UCefLfMK58jQoWP9OPGCaeieUHztn9AHeafb5JB54ggPGebUzyQ2jNgnr0z4L18dZETG24jS52kp5d32HHIF0cL_gpM8TGScOFo-DOwWqArE2ZdCKgE
e50j0af6oH4KghKT9O-Gfr3pxV6VwoZP-sJKbogaH_tVczTHSdEAN9J2ge62misfUYPAPHLFG4crQ2XTDIu2IaO95QLMYu2IKS90VOxthEhtesIKC52VdrrL
8Vangavbxsz7_PdnbZKI0INLOg3kdC4M6IXKQxH0GDrZ5RyVXKHKYu0IbbOj0aeU8GceMwoU22XvX6IWFkUDQWK2Ijxt2QYRrMAWKAr_7o73FjJTZ_Th0qgl
Ljo8GZxkL8k0aceHKFU-jG87XRqV2AYRrTgFaaT81khUXR1oKDZx11HoPvHmKCuN5khMA0aKrDPEwMVmz-hiuqfo60YYO6lTJV-ztNljYE1f-Eb1F2119EhB
DwVhleJolrOAvT7AePQ7zFqGolVWPLz2UId9ePQFzFqQQh6dj1BAevL2URHogEKXfII5yhvVGldDgOJoldzCeJnQ8PIphliOQdsqxWdKyf1e9L3ZbTflJlVd
Pb6-1sUqxey4ogDLGldnVaoXlE-7KFwS-mgX_ERqEhLGFj_NxxG1bFVz3igZzRoaK3w4JA5y29b2UIafeVpcb49vj58ex_ifb3-bbL0UhHJAXv0fbC_tKoWV
GePGpZgbK1wj5CfBIGdbqKgXV0WPGZdhVaoXF5ebbD-SKYYFLWhbfQI4yb9o3g5y0DH3pRwVHdcq9Yf0WcWDL834qLgFUYz__Tq62r3RMoQVxqzKW0IJae4A
c21Q0nKWmV4-K04I7Ey35I317XoeW0bkJWCL8D4U72WW9LW31QO2Qw20b8ZMGBL8Sx7c1wGU2qmz5f1oqNe2gRTOOEgnWDHZ0QaNBI3r5WjCFHQy4_LOArVf
7m
}

