sprite $image245 [241x151/16z] {
t9W7akCW4039JDpx_siteCCk7R9gBWEzEM-NfprOtsPdVWXVG6yxwk8zkpcZWUs7cJx14xpnpSjom7XcKrqIVa1uPalTxdkjJ7l5IznqRvNhJl4EkY88Z3y0
-yNR4TMIH8PXs4ANhtmRmWmhAuDXci_2c5oeW_9cqypKZJcxBo8CohkiecPAldAZ1dVWCowdJFPuXKMO6Q9xuijYokPuzO0fkJEXBgHCndXxkoh5ku44YoWN
QxmbjRSY4DmbOygmxYfILQZjqnZTAtn5dFk8dOowpvC6PNT711nOQnLrjC5rYDUGCgwrYeI1lY-acsc-NL58wyGhgXI0ly3aR4J4wUw-tl02UXqlCnNlJ2IW
2ZWoNxot9uqQd8sYoWc4S6HwNQ9kZD7PyFLvVpvDoiPuHNBa1cLlrCtq68bFQ8fBzzPusubP-2VY3HcmLyyDmf5Pu-sJIM2D5qHBu3F_Uwx9CCqTRL3wcNY5
LGpAaqsp26Ku8cRhDBkCqkCTm96vBcaeboDUyogAGCnowIjIwtz96QpnFcuewohom1Jh8NVrsqfH9Xoe4woYXbhZxO2grDlh1IfC5GSckBfEVQs8ETw4Ud0h
3C65VwTCrdWV9mtpAWhmaE81xCOK3O-L__aqYtuYAZyHRmQiBLrL6NyRk0_QpKDTTXI6mLyA0TjYp_k_xNwdEBV5Z9mXRBcz_6ChM8AqdpdjjtPWYUTtSpnf
57RdjTwFpMmKzfbfNLvuvV-UnqLyc83AYdVJxb03a_MFE1wLif6HHjUrsjUYNT5Q3I6mUeLrdn9xpHSln929DDP370eN9cktp-Lp6XFdYZqcth3xU5UqgRV4
vUy6aM1EUrJATAHXyAqo8LuOnfF6At5ianDivSIBTkXt6_Akw51Yqj12H5yJaLdnuZZWMoKTQHYk7rPG__IiBjJlnMUR-V82epcN5QzOBGxrx-yccvgPQTjO
Jpd7HIafNWUc_txR9rI5-GfCravhGqkRWAoSAtBYX7YDc3JqM7YJPKNmTWRKgBt8boPSaKC5SMxoKIzz4EVkALuUMEjA3nhd-TA_DW7xdfxJzDG0dstoqrMm
w6TpGTUjnhe0kfdHujYhdBux3FfsNi0yiHIIrw569eiLnwBe-pOhsvJhfI7oneXtC6cuiFd8GBu_lR-K0Rj7B1mnB-EjETI5JP1DpCnoSrfWicuMMIIFV0nE
0e6oQYXUguRid1R4kG3AeNbYIHEFdZRboqIDDrv-JbiLCZ9PjNLB8-k8E4QMzNAhnEj90_nMfEwxXoRho8qX9dAhoF-E-qizeVurMRwjm7Zn6c6ox5ZSAvDE
sNHChCPjoeVu-T9bdBkNz9mMcoppSngqDV3A0s0dpXVvzwc_Vi-vu-xJjj9pLQi_dzv5d5iNzIqozCej1ZQJkqNsY75jHFSbn8kEemnD5hp3OgyS0xzJPFtI
aCPoK_tjRZYtoZsJjLQgo4OH3v2bYfVnGhnjbVDkE9qPO6Io4CzfMoEAR1Ing2MNnxaA92ADPMzndDkn5NzuaB5N0FmKilUvx7mpoze6dvxvdHawpes1vnFx
ICXlHPzGzifa1UA8f1m3cyeqPE0ulhyqFj9epAGHFkfZAGV0L94PP9zpaOuq3979ykJJjw9Sd1i0pokoTryY8L4hNr3N9rb2p6ciairiGf6ZEPTFX23oAiwb
vxHc4hUrPOc598Rmjo10J1f2kmxjtUhV8CeHtrUo92ADCCw5kFzFp6bwnhb1aMrwaPDtmpKqMUQJ1d_BG7xJ0FJQD5xLvpraPP_D5LqtUHNdoie_gzeWpZKd
LflTrrfITyD7seNk2PErxnXacygtDLzaFiuj8vFbnE3djEid0JGWdbXavgxQMkI4kZ1PFt5kwi8R77X0N4zYt4A---HQ6h2jiUSm0T9pcY7OsuWHP59Vwnxn
VjLrE3Htqy8tSrlRG5u4yRI-tYx5oyIvbHQl--vWQG0yeSZCoSoooI3EhPvy9hhP7tq4hmE_NsJzN8IKbwQoj_1kE4f5UavpaqNWEZ1B7A_skVJbcBde-Rh0
b7VuHDrt1xWgCV1zvEPBeYAtZRyRpkTz1QVlPd55FpXY9O0TEPBork99Gpsxk_CE7oVUSxpaa2dYSPNLotXrcB0gFvFwd7PgWA-HueCbDYM9czv8Ds50GhpR
8UVv4eNh2pruMNXYaVaujwsyoH8_TayLnnoOAFA3oBZp3XywihXYS62-o3GoHGhRFCxb0p0PJnewu7NWwuMtYjoKgInQxXs-PPUp9PBbLM0C_7nVkyNdNL63
xRibnUky1F27ljVNN9pBRqNrysShRk2A8G0cYimZKqtDko8PJnewB2y1V1kPK_6KT_ZuylfYhcEcaUd8dhyRBkVh0eGh2ihh5PvTP3woLxQyshliQhvItMm0
-0exyKF8MfRCtV0ihfUNh_3poB8JaOODWJbSBp2zc25zVfoxxFMCS_FYDO0fSBx8ZyMvgtPikzqIhnW8NfhuUIcxU8DB7_bkxWmlZpnVoaiDubokcudwyiZp
fQnjlReRFk1LJU8wRtBX3IahBULDhQtYSMvQl4nv-MLF8KjntjLwjmPC42yZt_d8_24hyG8k8LwollpIF367h7KDt-7ZkvbNBx_iCMJHR-ds-pOXFruzZqok
-RZpaVL1vBnuyNytzetWC0m3KRG7XvpxdtPJjxOLlYAWNxfxOhOFRSyWOp9VlDBmmRNho7msTuEoaVazKZ8e6PdFPi1DI8uBPZDB1v0J74MaTXQPBzuEkDd8
VF5sTLzLEu7C5o_mfYFpsGou2SaHVF5UdoR5W0oE8ZownmVssmdpNvaNBoVp-6okJ-RtoFha43XwBsv0ydQkd2LEvejNVJXFSI0vuEBDFx7vyAet9moG8LU6
vIVp_oFpasFZNkNaRNtXDm5l7N9CF2GqaKiKRIgfHSGBTaBRkuRBD0N-w_qNi3VN8ciYmCrRK31_1EOdh-HskMZQ19OB5npiwZ7my0C2O3-aTU0mAp-PSEkd
MR2Vs9WI3p-sSTdOVWC
}

