sprite $image234 [236x172/16z] {
vCyt0G0m402XcUdzkusBjCC1Sm1C0a1dYi0qiaLa2uqjAbb4jj3OGcEBIXQHBJIsqDYYaaLa2uqjAbb4jj3OGcEBIXQHBJIs4DakQim4XtaM1g8X462mxt_T
Vqq_h4wTKgKqojDMTN_2nWDmg2MdbEBwBtUNzKtBbjQmM83xsu8rOrYOknSoc-QuEDo-RM6fMrXyS6zPMFBwod2DAUTSxxuZmr2vTEDMe8ORsy9GdfSqbQOx
8jB-0xULzKtNt7P9yhkZhMyQYlpdsJ292qsHh6a2UwAMajC_u2CoFAvIpTOqFukMRBCJXkZ5ag-NXI7wfYMjdyrNtjH3kTOMXXAwoAQgNJJ7S29BzBQ8zJfR
u7NzhisOrXJEvAOS5aE2nqMgMLMmK-Ahx1HJpXYXFbT-kAHjuQdsHQM_6bBFJf-LxzeV_RnjuQcktHHfiQHgifC8th8j3q9LYRrjuV5RrTHLCulg1zcf1DiK
eehmlcsdcw8OLNcrg4a-3KyrsWzh0qIr_BnjGGHMHJ2cB5fA6MrKF2gbgQfvliwt1HDxhnfLEu1CS_x9JcDpfjWFDzKMVpT_qE4AbgvA0uXkP8u28KUI7L6j
eRyyKnOMyYhAgbMbKGiUkfhzLdPJGnFLlEnCZ8smy1uSbRkjgP33pi2SKG7JL6LwR0IEbnMDYhefFRSJOWLJdDedMqnjMpYKlgnSr2zdxRf1L7LapZ2zRKqc
_Qxim7Iev1LVgQQc_zC6veo5stPAR0J39IpyZ2bWEu3svzr0pOtwkxR54NszzYTghqEoJnGgUCxaqOGbgbY_sxOuf53JvAEYbZOqPuRuUcm41bqhjLqZ4v4t
WJ30AL-_a7NxKjlYBPbS8xakEwjWUCwCstxfj8S1rxZJrpNkz0hTAUtmuY7fOFdo_3bzsiC8eiyZH1-0dZcyDsjaEihfs8WnckmqUWOFP8TKiXy8npb_siDa
k54RHgccFywVzZ2RyK3erFrstBOP3ZyqFJzdClNbYTCU9kDVF5GmVhvQOZqR6p4P_-8XKMKw-Shlo_P9RCHa_3cJ0vKUVv38hzfsA3PYDdpnG4iTwq7TCoil
xTXfhrqrPo9LffEl611DHhOeQTVCcQSL2txvCeS5KDKn4XMPQkjVFEJ5a1lNlS_OIPZhN6IYRGxknOET5OcdBLPVDNv-4cwY3rUHdymPlcBmJm22y3Ujve7S
EXJ3G3TrtV-w_wS7AUjWTcHFTzydaG0nB5Z1eS2q0YRTFlYu8MA8pipv0qXiEGd7Jbb9wmtXVFzFR2kzk2PXL4C_2ITfidfQ7pp000ljARwkdeItFLYFX_N1
0_k8h0QOX84KM8dM6yB5agRX_xNvJETAPu1Lqlg0kxN1EHw1Gm6T0LPFwmFklb2p6dgTALWzx0mwO_lQ2SQZkDJSuWjMHyl7xO_h1ECHE1GWPLPFoyVj2pMh
mUaCitfQhpFp13hpM_CPQfrXLW-Bnzr_y3g3piHu97M6MJtjhxwcl-zluP-5pY0fithQN2qTZ42TnzGPYE7YKcEXMjP-sbifbEuJmbvdxeuIdfKlhGYbs-31
wunW5RGGIjU6WUUPFdWGh8As2gKv8JnSPvZLmufG6Wn3hJDqoYshfrMXz4Y8sNn4y61OcLRkCl3zs-lCjT0Po-ff_znStqAUok3X90eLM0siNq4AUSBWeG-u
1MjFwrUGycMOPrJmu5azBUyomCk71G-UrTj6tbodbxFv-E31ipxMDcPLZxVhrUgCOdMqOWK9_--wsE31itfQjxc-RjlhlnO1zqDPlMtifxt_nTY7QG0m34L1
Gaal-q-Rji07REvvWxCaL0uE3sTMk-sT7nxs-neUjUsT7nuszMjWmRPtgyziwj22RMyS7kv9XnQCZNSE3riwj6RREpyyREh0Wctlrk5XIuSMR7kWp_nBXvQC
ZK-YptmnxLhdze7xdBgnODkR0-6vT6ZHs0Zwp7vsR7nu0NrcOS6s1_hCU6vi78S788Lbo_fChuM5sfSjJDy-jBxFz5fVg5xhqzUNhPVwqFhqxRM-ptYjJr-F
VTFIFhI-K7kj3whlFrZQXzOFXBtMznclbUdRbwsKzg5bXTfh8RNNEccFTT9UwwIzrb5xhPFsM2VjjOxQQvsqnpffhtNINkkelTP9UwoJzbf7xRLCsckTjCSw
QQzrr5xhf3tMINkje_PQ9-srJjfZdRJNEcglTT9UwwGzrabxhQFsMYVjjKxQOnsrrpffhssaFm
}

