sprite $image369 [277x207/16z] {
x9W7aeGm30IThP7__zuBcq6NatshwHymXRefmcogrB21P04WELmWgUD8J-40YGrNMWmXa2AuHGedoHrRg9RKi8LgYHMlKIDbOf7YECEl8ybhXYr-yromWsh9
WeyYXJBncMUROQh5PfXgoHrVGxAV35CjHYPKInPyctBd6QPQh4oebeAVf4RAn2BbxdwjKItscvvgAO8DL8lDCDLYCymRglWBMdISuTUfbCd_pNE5WMgHeTX1
jSWOglXRQbn_bFqiL8kC0qgrs546rN936qScgAM4PIdZWk80rL81tSr2jSXGw7OMvbaECj4nJIrIbXnbzYmzhvdaoJVKqdgZs5dKerhiA5IB6MKp2_CiunO5
PgebhZYAAZ1NBGkU3mvCLKjUJBIuu5qjylApgskro6jNeketp_BAk-1QBM8cMK4jEkBKKHxPkG_bnc4O2A3kDXRB___SQyfuHpbvn60WWIcSThsyP1T8OX6m
rmSrB20hKSusFwNL8f9MYN8tdK4o16ThfIWE3CCYaceK5yi8rGAsLewozD-i6y_mzdRyUgX42R5icfpMw5QvljrzEjKPcfF0uAVAaOmO2v0_XYSImWpakNpD
BwkMvNSJifMZX5cs89c-DmHAORLe33V2R08Q0KK7jdErW1I9lZS6IhnQCfFJMXi9XMIK9R5CHaDfZJjN2zWqXW6HbAEOK1gZB43661uIHIoHQabBJZtA1JEK
ZWobLCiAIIdA-Muk5Ac4goK-XkjHz93FQvHuXkB9gKUvchr2YLTBdAGUHG_vBACqCbejWPr-11GzvFCQPPkj1IuI0LMZg4nMKLgBZ-T0SgfHBcPTA8rXbW19
3OhAf1CbDKCW5tVwUXGzkD-F4cG1EdRwOXGzk1z5YLTBVt9qU2fuSByR9M5hmPE48bb3EUutXaCe7weM07CMPOM0lbUCeZ4SHkaVpqx289QEvDIXNCt2A3tZ
MK6X0oOLTf0Ke6WCXr7wMF3SXA5gOSSOBa1HcGHH-ZwfWDaU_CpGvAIshKRH6Cv2qS4YYNxHCqDKSWP0qHXEHU4Y2qX5RCOYac5GT2Tc78Lp5FB5SYOIiG1G
SgfHjDEdeyosbcKI7UYdwr5K9laeypcavFZo4KazYiea7qKi-e4Eat8KZU5y57r79ku3esYdtnN5nqUvMly11aMflOmBSHHoP9JuPLm0366Kne5HudTYmXq6
H55Q6nb5OpWG7XY-7efs-XYA0_x5K3I6moZ-DUEZClb1qHZ-MYZjSKeOmryD1NO_PfT97CKn28hPDSnoCSj5CM0G57jSecMIWW8NYfbtehGDKNJpmQxtt0i5
i05HTFD1VAUFey1C3XWBHTMouptt0Cp6Hh77kU1gwf5HL2t1CPoFulKe_TMIOu9r54CnYivbd_J0yTyBNFaEnU3rAAgMxNiMxxxCHz9Xxr1i01HLozOJMJlA
x8o9el6yRTrgcnqFXOxuVKtdUmAAM0P18M4wErSBf89UbBOz2Xq6n6vgLRMaiAoZEDov9OgI0thyfjRuU0PUisW-pr4Cy2rHHCBcFLV17PC_WG1_ihXOD9wV
9lDtcuqxXSyNj7Z7TOetI_vK4uGW5eX5EymC1LkYKEphA0Qd9OvdGIncI6S_52MdjJuKaDV3uPfMBK9Pob0D2gVajDQFSZq89QbQy8e5A41HcVIZJ22dLPPh
9uiObgjbPnIwNf7TY-8JoibkEPi_iCm2Y6KL1KX2qHZ-20g8qriu7YbR2yImMYro86OePa06YfBJZGB0m9FkUTJc7wyMYC60rGpfamfp5Cj0eKCaVIWWtSoE
Giduf0Bql-xB402OvQCeEJqeClbJ8nUx_rrgzVOFL4j7mtPiBSaelzix3oN9KI28Pk7BzFz_xXbGMnt7YbC7CRgjSEjtz8BAp2beOTOzaMtIRHrJ3u2u2Yq_
AsDOhepj-92qd0-bYwJFHDHKsqIbL2ZUTKQuCqE51nKPslENe9WUHi9YLiZX1Ghew3vYv5EnzA6O3A3qnAJtMrqerMR29vJipjfhbWw6uL2Xbhv1OP41b86O
Z97KGA00a2gQeWa0vObNf_jyihIeMVlItw5m3ukDRNWyY6ofG1eKOck-aq1nFt1Q8YqYxVS_eJ3B4CeJoR7E4JFD8PGAnT-XS9c_Ze7cfQK_njr1wM6nSJ8P
TuvP9W3q1kK_NZVcfdfeZsK8XKK6K0PYqcCIK2jlK7oB72MSVdfoNbhwK5X4-b3wOb9fzSei0ju120sAU4gdt3CMphJdVlkOi7IWJ7HEBR4292jFA9pA8Hl-
VlBlGwbhe3xu3igS3OkQCfiId4O0KPGgb94Ddoyj1-QLRmFLPYYVb_VPM4oihwyS0zyoG0H4zaK8b4--HiiVikSTbivGmPIV3xnnaoUKaPXejsqqFA8Ql2GG
CyK3Dhmi-Ol8XgJLv-LzDYSc8dVFYGQ0YYKWTKOdtvKMcP6MzxPuSXEfK2R5nDGIS1TN9ndmNxmbofsS_EiQs46vIuiTplHLdTYJfpkKLevdRFZyv3-UL-xM
mEu2pCFV3OlehG00KW7WbJOzdBWOTadotwy1tL_sQ4SxHxWj3P7gm77h-kBntQ9pXWgwUs1zBpaQODKqqhrnjbYIKvwuntvPyjyUk0_bUAPd0k0SWDYW71kj
hKt-yr3wdQF2bW6Gb2UKiGslI2szdyz1wIEv6QS69Ie3YC84NoR4P6Not-k5MGVAs8QrDaweK5A3miLFPFhbqcAx9vP_XMBQGxATm27D0F86vNmn-VwyKjJs
ZT4P7Onik9Jsy2zGqa1C5jfp7ulOFp-no0xA8AoP111Ue4Y6pnEPVddoL-jgXSWUIZ_JQz5gm-K19N6P6AsjbfOT4v7EOMuRBHEpG0g0Yhad59xDz2k72kF6
a0tAQBHc2HMAamf54X1cHslhax-DjMA3qkySqn3Ge8G6XQERp_JhfSM6aLqgbFuV44i0tg6SPSDBvfLYk-3HwOy-j8O1dfzGuhmDhvUMdLPqIgGFQuFYM2iK
PdT2fbyeBVQquOaIDUEKIeEI7r3ASXiUdrGOo-TSYHbl9xGSGBn1EK5CrYP_gvqppIIZLZ9NHw_2e5W6s-NhY-9OFcTBRTlTWj-WSF5bNQO_xH3K_2eHCIO4
bLSePypfrzlpjC1gPFCWpNMczeII7Nv8XTFVfy2Eb05oW2ingmFYHAPVRS-dbJ1R0PnLwQ323gKb4mxuMUNoIKXCMIm2qHosuoPXS6hjuj8YQfQzc0Uo4k1K
25H-afYS_we9CNO06m6i1800ojoruUjBYp1B9L44S2njQL3ksV3rfKNQiGCD06AkEXBRwkkDrgulBM8toI6o500kj45Z2h7y61i-_vqAQbQznOjiIj9xcT3b
fKL4PMEY7hMAnkV1csR3bobNVar5JBPiuj0g2pSZ6sJwYzgpc6biHu3D0X2406HkV7BBz9Uh-Al34gcf_lxf0acRM4TSiIYDtifGowjv88e5WEe2oKrCBbe-
Zvc4eWeWDJJzJmzVNrhKScNcFKlG0Y2Rj8KopFHNJIrYIa0GLSr4MW6n0zAwqThwUQNUgdwO5GTKABN2mktozSdVjfs-WCTXFgmThQsVLqexhoPA5Gep0HXi
br_UdiL22wztA2M6nJQyVgWWriAhfDIWZ6tu-j8YIYsP23KernUJSV9lKBmMUkXDnF-tA3sXr0e-JzZm9QL5xn3ynAVBhvhy9QBMn7RvXPD_8U3zLHM_YrA9
CLtNXkVdbNiR_brXdPZy2G
}

sprite $image369 [139x104/16z] {
pPk9bjmW3aN5Zfx4_F_dpYaxEWoT8arCfHbbNtqFxygBJD5c9OxqVr6X0gZXF8Wh03C3nHqcIGo-2vnEWiGAxeLwJ1b_PzCBAFw89Db01fZipabYTKgPK06U
56euA0aVKiQzoUQCCd4ACYeJ3qeo5b33ppRmAMLCajK2P_Ulik6XZYcJ9o07bAaoOVdvngugJs4uVTXP4H4yXAdneoZ01SD37MdiAZVBMMNC5OCvgOoX26uO
76niGx65EQjCLKCuhCnuNjbJ9dxqRBkfZDz4iUDkBmnQtY8fTjHT68Z-Pmy5Rmxw92NHrjgUBQpzeC-LmGj4iUUAOn71NagG2mIQFtDUUGo3LpOgviesYZnJ
nh8HG9ks3w2eYioLMP3azOD-1gMfFaYfPzEQjkrL2H2v6l61CWQYxQez55SW7ULLguqzPhEFaXXiAClAZ0qi1hA54XdC0yfoIkZPgBPT51kcT9HrPUHkOB5i
Db3iWNr0MLPcb6G7nIJX2Og-LmO6CpJmY9AU3LFcAEzIWZIvM8O6taKnIUOe5XCwo6Kq015jOjbieTZ4RG6bfyIY1WUWW-oWM0ElePWoC10nLmna1yMR92ie
1j3Q1MLb61EKdOaRvYXDvVfHP1LbR-86_155jr7M9su0e4rdAAtz1KhU6vb3v6CeQK4IDf1rLpw_AjR0Fu8YsJqVcHkADiK7KC3fcnUZtw10NYYCVHGR-pmR
cGFC7qEniSz4aeLIGz4cUoZs2k31cnN0hdVo2uMbwGRATEmJwxUc01SHU1T5MvF9f7395lJRaZsK-uvgCYbSwo68mLpQ6WhMKOn405kL1ye0mrEEg2fk5Bik
hQ7ehqSYG-dAfBZOIX0n6C0alb5u6SL0kYkzXBrRUt5h392kp8DLKRl9_1t5atCBrsQ3mAYCj6OeWczHj3K3-Gq5WAF4YRvLfaCCoa1KOUs4fdEKBibLNr44
d8aOgF6Ri-y0OJyQxHBArvd6W0AjvE2fCWDvVdSxgZ8giuxIixcnC0WRYGY1t6paxiiSPbH6MpCKO4GPip4G6S_XHCKH1uh8Rkac5mOnfDH_uqPX32W6CcI3
_vKm5v0NJxMKwfTl_J4gCyub3OKxZ1rzderM8ghauTmacsVADDKBHG13iGP-dmq4L3nLSfo_zl6gClnEcUk0Tsi3VMu7Y2apNWKLMGA5a9ZYwgkpkAxCVLnx
swd3J6EG1D1AL1tL6BZMy72a0EaG69MvCr5xU9zA0Yt94HKYxzYoMOGf2yhW1kbJZQaa8ece92g10cUtCNwQANCVrr14Pjb88UU84nLmzKy7flF6jc6ATXHz
bur8GI2EnD4nXwTxY_wiJ3-D6CexIU2e1aAaMbSb-TjhWPbYT1VAbzjO22vR0t68N2QIR2kZmmh0LaN6R2AbozRAamRULyPkvGPA7REH6dmaBfHZuVZvxMYc
3DIYw9G36IGJvKYSg6BUmFlAo9NDjA0eaYZgozPQ_B_RbGPH5VuJIIBAcR84_xI1rsyVC0SHIFAPOgQCokdW3aRXn1H2g1kIh4-PvmM1k9Wf55zAhVu7jglF
Id80bKJH1N0yjmTO14mkKyr42H-LP7s2Tm4g1y-Hd6CkNDoP_U8YBv92HBaI1Plc7DWWhUp9WQyp2Poh6v9itZve9I8laIHJHUNiJdtY0Y3FDLLFrOMTRN3x
ocWaPayl1ByZoRuoW7C8H2LxUyuwzN4KC3cfH4Mmsy3xoX15xo9NJsShCB-Gc2EThvHy6XhuQ4fRsVmN
}

