sprite $image213 [312x205/16z] {
xDU5TKGn5CHGi_twBpZCvFqA9xf5wCoahv1dJuUfnuMM3b6DQwkaawdCk3DpEedoY4TEofnQFBFDdEgAPtQPKvxnYl5wvjJZ4PWvmxRFdCgAZNtct1uaSuQD
PyxjiS-Sfsfldpd3jcVcMa3Ti47LKyNCulPWHZPiJFTKCQkwFPXP39kP8zk3wvwg5vWv4ZOpr-9JZUpsOBgd2cVExM7cQdoXaTqUJFDKqSovFPXPF5KqSsuF
fhazQEOC6pEBfuePRW-e6JQQERS7CxEdYkc63Mfk3vevmqOpvwbYkji3QeQDPivJHJFdzc2wOOEQsuDPvRUTAZFNupWpr-8uCrVMEVjsjkim3W9WE831cENz
NtSKajcdTTlPAtntRZyT_JXONTzm5FlkyTaH-A-7hJEtR7rmEdFBx0Evpjno_q2kCxUyuAmpzxPRoNNcFd5pxynzvjQP-yojC_UPstTcZlxcUVgrSXF_JZTH
wynzu8O4R9svjzr6B1lV-o-dz7UvPGOFxSozxvQva6TdxdqtXm53-ZRtXXkkSbiHF3jpRxWTmq-tJ1-TkTVTXX68dMwP0tbqvbxkco9SRZpcuDcPUz4jGv2i
t382EtElkgL1POxFFsnmPsxlHbvkomXa_8X8t9dRk0dDSijGWDjjYT5wbBbUf2yxLPHShtaQ16IdcsNEqPbxTAZWV17WVG-XSR2NMnfrvXwUSSlDCVnq6xaG
6AmGaQ0pz-20s2KdwEMMCG5dkTM6gJFtuE0iEHCM_N6U7iDknEsdLsTESS3jDkdWk13rgpTC4_wK7DkTEMA_BYKB0Mz41lxY3PCSVqtcEE9qgyojShFQC3sG
wypfbRd1AFUb18xXfrjjc6ppqjgPuu5QRhLXMlUbn7pjCzUPYvgdeGW_kIbhlnTkCaTcrpmDHhBBRHBIym7HcLi3w9gd2-XWBxSPFgLlSvlCpK5URhO8fDnU
UeBep0bfkTM6wNBBP19vdhdEd9BfDK-3VdGJ5DmzGNJc2F6dUJh9oYqZgJzQDvch3TFj1kU04BgV87mZrvd3kDpcGfZbbWau-6dcEdF6mbfk6HEEsstAtExc
EdC3xxaGXCDEDytKhyuS_ZMP-tcUqi5HRhb8DdATEVSvlDpop1peZOYFFhqwS_Ed0M7bLhivAJSADThivdet9wnBy0JpsirTbv8nEdERzq95Wd8BO0A9Sik5
hFrU-D9kBc2c8X0L8kutJ9qv5SeutJ84qCfDtMNxwjLF49CKhkK87iDFjvSsJ9svCV1oeqKWVhz7aCXMhZCdSRhLRWxqGXJQRfWwSsDvCFty1568YTlCzHC4
qJLF7Mh3L8X6lFbDQsTk2g6Ncow4oOKOvBwJwym9pNAh3TCltPvchZDdIg4EUc-OFDFBhN-0likS4j0zJsl3L6vVBMTn77_9RUv-Wc1AHP1o-ruvYupZpnxv
vOQ9gJwzVcZVJ73sX64W6Y0XyGJkVzqAHN-dEvekfbYP0tHvme-nnPSx4qzp_JXlk4cQsqkryJx5rfbeZnoEyoItFyhMFb-OHfaZjpZaIEs6cwevNfZw1eGa
XylX0ZT5S_ayUiQlmU6rOXEuYPhBTMqP_UmMvf7ZY0hSTCtbV74xZo33IcegDrrpGmJT0f2Zs6HkkkOmkFKUG7CKcyvDrnoEYziPGNCSKPsRhZd3nUtIt5l9
SKHTk55p6DCAl55p754lRlpwouwBsrqdmGj6r8SRVvc9OqphonuvKdFcng-_UdzV9w7O_BbHSnYTv3qzc6BpvqRDVTr9y0BDSKGTkDreRamhOFNdv5v0pOaR
DMV3Sh1bs-p_9WUEg3ytfc1qaZwuxQsLgcdENsm2DnVDNTokEtfLDES_elVf3jpuzHSwsdxzhRd9RrR_xl4yDsfkS3jhxNedyH_HvxdniuXya9j6xlaHPLfY
V3HdkGrkJDCqzpmrR8bnqrpD-9hRNkL7pbziJ2-9yTGSojg-XYGEgx_OcAEc1y8srvaAePCyFAAs9lzGSmpdL2VdFw8tOlFGN6SWl5cV7D4zFHPgZjdnM2U1
GAqjwT5GSsFXxtox2iFgtZq4iJbehfNE2EIynPQJ40_DMU_5xib55vj-IEUS2kHSHrGGcxVcX64Dk5JfMQf2xW6n7IK9STMSGYxwKgLhJYVdlrH5q9n_zuYW
EV_k4K9pxajL2Cq1W6_tYA4vu8gVsA9e3YDEtIEEvl2HVz8zFCJchpbokn13ewOVTCDeZjoMWYl2YCfBLJJD3MwRrNm3JXJRabwUhTq_SaikMwe5WCDI5KTp
A3lsX9OhWBZTGyz-FwmrMR6j0833KXL7SxOQIbhG03WST0DfhcOhfQHb1-2mL4NIt9foifRvpCa7tOXPRZLdUqi66AuuB5M1sbp9-8ZSFG9dkntMFHj67BwI
YQGvonKZXqFtYAGva9jmq8sVzKvp4ZS8OWklEN9pMAeYNPZ8JH7Rr1ovEInLCGxfv2OlLLDp83TzgOgVybDov2OSTAVco4rOggRco4te7bDpv3QxXz3co4rO
ggRco4te7bDpvARyx75gZjoKW-xK7Bd9tMDg3kGc77IdviXjBbN28Hta9YnLKtE3coQscQMIcxfKJStXq9UgcMmu70ww0LFCftjy0W
}

sprite $image213 [156x103/16z] {
pPe9qlGc34J71hHq2y_zJviz-HU-AiZOKUWJl4AlMfhbzQzJhRpspAa0zDoGx130tG4vTaDh3lypyBeLMJ7ujy3ALgBvzvbhbp_ERu6t3RIh0zb4k_nnZi6e
NNvlV9rPd-IBDchtl_N6FB2wasW-zCaMuvnhbzyRS-rs6-Uunl9xuxvs-QADsgNsnatjyaNBr-uOnhcDTjNXJmJ-j7Qd0VvGu3MvD_Arc_V6VUtoUsFU9qT2
RsHhD_R6ym6i9FH6-Xeho-FCNsFFaJr_j8EhSFbz0X83tIRQWHpeTj4EP90hWyrVOw09I693xK0rjU2Ese7QepNVKJk4wANcIcwd7QZIAY-jkfrse7QM6gwK
rC7AiSBcbueKVwFaqjKPcmV4AgzMd19gs4YxGnZMz7BH8bTKCMwatQaHfjNUVWebV3BOvAEzM40RALvBND9qCjXSxIe2KkMAKY6a86_90dPEjQEBHuES_dPN
nKPhxBIWjjglLinSJJqsMcF50weXiEfsiObdzibCkuPmANYxY_NcPcIUThga7SnLMksNLEDcsabpwpYbcq70lRGZ1LVJLl6sghbhRAuTH6kFMkWQUwsnGqbh
TgbgqJUBRAUTQiMbnIZTzhgUgeUBT5UljVSgcsd7SAdwnjaW7SBzj0C5hV0oC9LkuNgYrdRrMar1vjAzLgudZHPQ-Ir8G8l-caOOrahyETEifqFq7alVL9Cc
L2UJwC3Ulx7DhoTfw4GA7QCFR1Fj49q_1l_LE0UswVK4iiVmTC-FSs2RvZGIuzFXwN4ER8lQaMGFOA1xU9mZspmD12E20zn3P1EskNRedI8Ow6wBDcURQyUW
GeqFqZ7wd6sUwYIqXpxN9_Y2hFVN9sa8Dnh_YDz-El0BielrzL4E9LJuH-pkO1aZMG-vyxy3_XM_fnr6ikZTZfl_rnZPI3mX6ihhRXf8Wm-BufvedUtrG0ub
OUI7TFnod7eyzhygSWpmyJZzV3sNYY_fFXndVVn_V1m3PFN6_6WV0sJrnlnw6jc0ZDwOfs5aSmLIUcEktSXMp825teXdUcE-nhu5hLLp8BCtrhMpfiKScRsn
hXsqd69OxurSxKG1OB4tihKp0y19RsIb-jXqNEsDVEt0pDwONq_V1rpjZNpjmDNUoDSEdFH6UWJVs5Px8ryxCBitrezsCBatrezsWFcziVwLPnzwOu-S2dRK
rvuf_a5l_0e
}

