sprite $image411 [443x295/16z] {
xD4v3S0m542nELFuios6NbzwaKt1Es_Tj0cK1HATXGgj2TGsywVDdxQPFc_sl0Nwl3NtnCdpTdzFd3rnyiJTo1CdJvmySJVopCaJvyxShJnnxip9C-TknPdh
CXTchijSbxakSrtciinrcUjIrsKkoroNkYvpMUQwl6NvwdAMPItBMjTfQ_JRYB-HVgFTHZcEyXlbDyfnXDyenn6E8nn7E8vk7E4vmd5qumZFqOsZEqTuZcuS
tJcwStJdwCxHZQCxHtUExXpTERfpTEl8pj6Tepj7Tuvi7TqvnkTGHtUEyJdKCJw7EiRdKCUFSwYxsBaFhDTH60p3dv0ifFqlU9en1eBJYyyTlQVzDUq9n92Y
FYiwjvmjJC2BTbc4Ks8ftmNTnrD9MEFREci-JR2cxgu42RfFbr3pMw5qbSuyfqBOXGTBfxFpawMewJleo1BMWkxJ4RRuJZg-HfSoIlo7qVdf4jJkf9EhTFi9
vZ-3pazBPwZP6-Xe7ySfwBusO-ehT5g7RaR9WkvBCoQzGbV1wYcA-vz1vwUGot9PAd0ibzbJT0uWcVVTAo91DqtmMFcGBeqHBafdf0iwJ7gCBlDYlcUBdPNE
grpGxPU5rVO9boIVcoxenF-D-_DOrk-OJqiNT1bOsjtJuQB9MUc2JW30ncsrAaddegjs_ZyumfGzFLpNqRwBeuBSdlWDkg3Bz-Lh1GfDn-kwWz0bhfiYGDv9
df7EpqFdZuM-r-bWqa5MIVyuNT3beOPEbtnu4b8cLgP-OkRouy_J1TtH3yeH1x7QbCumYRn8wa_fWWubdj6vT6POOwnvHnTzbIxlVwrJEYViBO8sUZTTqFL7
cEcVhj3bwZ2dozYp3XBBgtH1Do-rDog6F6rqMfNcTCxjA5CqsVVeWYub6kdardhUsb7c2Otar-Y2BhbBJxVKGULJkkvYc7Vpv_8Jkg2JOjFzsPpEkqT3nfR_
bYxewX0wffDcrBcXnB-X2pejjxzLbcCwgbZjiDFVq0LTxb_-J7vCfq3hk_oMBkXimwb6XtG9Mzn-ctv35tJUxsdfCLs_9dV3LZwaYzAxwIZdGkLEQFDZkeGz
TkVzc-_G1LrVBm8-fbEqcSLkoYFlBqYVe1CqwJ4TeOsv1v_JHVWadNRV7j8L6qgOP3VeWevVf5jqGcVOuqCwmveg9icSBieeoIjq901Fw1nxUaYtdSWmRWbh
Sxf8KD8dwMffHfUwxuO6el8ITTv4zUehmY96ARzA1yz3xJq3CgVh9rI3-2Qvqqxf8cpvCocrT7scskrltQ8RxakwVyaJkiXGeYVS-F1rqLbIkQcRqyzfkKAd
vKHtflArc4pe8ddsACKOOrhKc6RR9EkMCkl1OvqCToKhtyZ1Raf4pnwbO8mMqwessIOHBzWwdeOi-w1lrTs9pUTqyKBC_FH3dGnmi-Mqk67FQ9nN6rJhvOga
kGVTGVpqNegXYSqnYPrcoxHBEZDVC-bvW-xsxRyyfLxXtDECZZ0sfnkTnBiqwAxS_C-nLpZt1Lt4YnbcfHjqRea6EGgwuq77pxgdF9b0UR4oLYR9ZAxFAcB_
2HwLDDuRINXfAmKWdMnZwtWSeuIcPKetZz4NT2LvyUuiuasfTVEySwaRcl83T1Pqqp9gwgyde6MsNjTXxlG7w9pGna4ttgF9tr3MwO0U3sBIGtGosscBZzzG
_jXDKiSTsVYe9G_HAPhKWsxBv8FpK2Q0BiUFFKINKKlPWsvSC_c74hvSdMa7isOtwIY9-Tdw_MVpBUfVIcLv6E06xT_jtLTj004C1K48nnzjUk_Dlgmq2-6D
_EqpvRRfX0xTjftGaME7Jjxw38HENjW97RgU7RbbEw53bxKZLxL3LxKZbwL3bxKZLxL3bxL3bxKZLxKZLxL3bxKZbxL3LyKZLxKZbxL3LyKZbxKZ5yKZbxL3
byKZLyKZLyKZbyKZ5zKZbyKZLzKZbzKZL-KZXm_S6Y0vTEHswSYX0xTgHmuTk5KwSEZ8xTA1OmTkaGuSEd2RTk3GSTkauyOEt1uTDtJOrkomeSEsPKSD7RCb
EsReqB4ZzpaTENRes97xd8uSEtBio7rkXuuTENJa1kp8iICtZaUE7JXsvDWTxSXr8nSEN3XouS258rSEN3foxS0HxCAXEwvAmf6xhmM7xdWMkBq6vkAsqz1W
uCQR78pRQEEJSPjgPREI6xdNOVlRrdSxcmrTuDZ9ZSu7RPdkc0dNjDpn3r8MJbKvPU5KbLCMJijm8gSgdB9mgief2wSgd9RXH4vLE6NXL8LJ5KvPE5NXL8LJ
5KvPE5NXL8LJ5avLE5NTL8LJ5KvLDsNTL8LJrKtZRBe4
}

