sprite $image106 [239x166/16z] {
vPk9VYCv2yGNaCGXv_qVzpiQnzl4PhgjKKRPtjfpSlz_eXeeEN-j4BBGN_yMGLLLPVntq1PHLuNhmoBhGr8k3WjDWuGkRzgeTbaBaqJIIriOGnrVlQ9h1dl5
fbJqG0qkP5hMOvNhDPzSrkKYffKpiBSFkN3pYRBRnySLS95FmZhkvKthTNm9t2BdOICkNBkE8oworal2TWSDkD3-SQiXr9Ec3RZH0KoNQZvUo14tZbyDBbB7
Bel0yhpxrmiqdwoUjKvU3TTlFZdmhTlarN2zQNCBtspIQhW-hZW-O3_QJ59-8d3LKLaA-sERKj5l5UEFZYlcgy9FRZxp9UN7RJxNhsWI_NDg-BCcnWjQEDzy
LbfulMcv3AWUM_Y7rd4TgfZ38Qp3ykOp7pTVAJgiCEq2ND-V-ihcSunR-PnQmCtpZxxIjCUuPpzS0cw-6lULTJmVDuUDkD2qB6e-yt7p7A_lNvn5opUV-RWn
e-tXyT5mxUOp7tU33RZ8tpzNLjKbkFOL5reoLyutxVfYllM1W7Qy-QnyLEMPPSDLfXt7tPHUEJYiPPzTOK4TJy0T3cXfPLmnZZiUqE82qqx07LQ31N75EboL
0jzlMYb5ti4LbdTn6pKz9QPvTPpdPT1EuahT70PKty0LUkC7OZXaWv7c4_s2xGGkKnZ1CznaR2AParTIQnXDA_f-xP0Su0RO01nmy-SFr0bv9JPcvWeZpIS0
G944DskCKEG8Lo2vLXspC1I-gunSr3Q87aXnQpQo9RZPKP7yJbEYnWyr6ca-aGFv9IxZlfY4AuQVFy4DTH4wnc0sA1pKJZUV_ASXYRZnnTd5IR7jogq6t7G5
c63XRXg1vVSlvw1AmDszcrZeSKQxDylXc577B8nVS7it6GREVvezReNTcsb_ur_XuU0SDw-XOva-uPu5RkLNegyjve5B-vfjku_XFKEvuvPS-EuB9An_s1TS
btBKX5-EAENLb8RxZmWp4CuTwJq4IN3FMBZCYBhsDO-XIESEkWwRu2OLFH6NrFNYFaXmmjVDuXx7XLOXuBwgQ9bvkYJPwUBSg2M6UVRf6YaFt1Hu1Yw6yOc2
T_Up0Ct8-IEiuvBempKHDw_eyKSL_mqauUuTPDSNeSciboMQmxfiRs_6tay3S_kL2cIDI1live-oUtX9sJrpxhYrfOhd3_MWZfzpMekekON7nupONR4z4AjK
s9Nrf3730cothrV_Pu3VdTNgqypSzWj2GS2oMpY1zHYtdkn0rhEZtQx-d_NsNCdF2ql4ZMS39HPcoHV0upKpF-1RV_76tiU0ytMKatstGJOf7E8olhK0cjrU
r76EcrjuVBttK3IV0y-lzwo7iWZxjw5xBfCJ5auMxu2RxvzLz12NpzTnNjmHTxoYfHn6SzdD5TPNmQiafJoQyyVVHOjmOky3CqKJvhWkBWW0MFXrpio9OOvD
UzI58wuH013RMGl7P0NgExS88XgKuGRRdyxvesaJN8PDPEzRM6gHANT4-OTpgKEcJN4hk536cj9ytAZXEivnQyDNl5q7W5VXHjYeMoncwrO0K2SCqcjnxIMi
u0u80QHll6Mq2w_7pO_sfd7VBG1aZgrZNNWzRbx7lOOqmpb9D-mwD5Uknythc9-pAe7DjuA0GuFqUjpSjCz9PE_iVKWBsC0WlHWtDwsLv-1LYQqp0W3tBWE3
z6BStBGDNkJCXa3QnNbT0nMz1ZVMSPJ0wrYT05hlUeQtImAy4DVwArYbx1QXURzLlCyPJDHqmC8BSBCwtaoRu7g_zV_MZHu0MuARp9MBS2rjFYdk1aZsEKqQ
mgPg0nOEkBMTLC2TO5flFYck5G1IFrvM0A3g1tswekKBxeXuZcdjRjeSjni2O5C6W2e0eDqA0FSHu77SMHFZ8MvN0W24JzogtGWmAUV4mXDnnqsRNYf6Rre1
LzFxaugFsfAb5kOw8ldjYL4ZR1Iq0CouuUhMZm284MWxHHsqyA36w_ZeeXAu1-129DjUf0qstPT-BuH0dW4lWxsrKpVhyQU_joFkkXMtzBPFiHYhJGWxlctp
EHOy0nX2iTw50DW8NBpX0Y3RiOK7D6FpoPLNj5Er_tCqh9kHkG60V2Qq90ijd3UVyyAl00MWg3OrKVnS7z0UWNJHHS3fnFYcIFkBheJL51_dMX-uW6t0mkjC
criuyle0hUvdj0sNAm90iSa7FBxvZ0cvFtNXrZlvwVQ681kk-4ExZ7NX-N55rBY5XSMNfUOmfJckln7QYKs9lxcE7NPOHVkBhaJMNG_SNc5xTEcuXUV75QCM
ZchUSyrnxtr8dRiIsq15Jp5jpId6BUmFAUczr4SZAjgt_fJ4y7E1RQJvZ3SbZznh1K1vDA9Qu1EtZ5bu_kOphcAH5nsoUICgu8guyotifftMVCwlXa8Rdswu
SlyZMS2TNj5vyva4cLlOc93uyMIsvWbjm9qDR0D3rBocPBPlH0nG8-vK2-UR3qqapDETs7STL0Bk-06FnsxJBVm25zcy6vU0EmyuZojWY69yhhJokV2wUntN
cCNIYaw1vsy-yotiJ-N2102Vk3My2EtOmZ8rhlZUfcGDmVM9Q_w6ObCg-dKTJp3jQBfZDUBsvaaj30Iqmt75VELvfRg5xOxRjR8nUYiUjN0EEx3vJBQmIQMY
_HFNp4TDilDN3ZAObQ-niCkzMwYmzHxlqDglyqgzMJv4nUQpICYlSSLJF8dROFbLNYdsyM435xLhB1nn6pn4lLj5udHxqFlHVWJS_A9shQ3grzMm-6J91Hst
RDWQSAE5nTdiS6A4LPXv5wwrAm3S7zVK3S1vq_dIxcms9wxuqtFb8vkj07GtCa19SVl70pStxRpcCp_TqNkQ1K1RPRUk1728Epih_rEhuSPOAZZkDcqO7UCE
PEMhXFmgtV5YncteECOTtdpMDoLhX0XGkjvn3OzmUxyjQ3xphXnuQqJtAxJ7AbohFE6cwdK1n-YLGqFglTv7oRhX5e_XSzpnvhD-hjHcNG3eWIkmANoOb_0K
qwwVAtrJsC-NH00e4NTLN37_oi5VL-cFglj58IEWHTpnpMUzMWGMdwi-SMLxImsu4ozgrrjODbZ7zITL0TI0Ep6kM3zNQYKYk2zB0DWQ00VSgHUrwvkIMRiF
7IGUt570NTnyvbyvM8MoBKlcKIrQm9qTLwnV3LNyvPKREg16tFaJu_gvibjnJYae0NTcNB7Umd4NDXCJ3RXJwtXzKugNXWZbgH75Ghw0XKCNfklXHWl7AnQv
6cwULsfhqg-BwnKTTLrS5-dbSQEANHetj_3rSLqabyUDAdfvtAXg5yVDBNnzNBVmvN6ZYYMuLw_ew-EwW1qtUH7sHIryItvd_A8MleLW-UA2rXVT1lqN
}

sprite $image106 [120x83/16z] {
lPU9akCu34D9wYGex___xHvIp6elar5gF0dgxCxnB4245FfjfTwOlYwk2cZvDhKeL1NeYRwetA5BG1FwagG1we9M_awmJdNo5y0ps8imniUjJZqirevZoBU2
TTau7bpE_B69ZHOVn-Gk_pDzG3bGLUtaJl-1dZuRh0kJR1tmQVxKxCJTR3-SW1R-oEn4GIz2pt-o5DyNqD8dPcSleF8V3nRF5BqlVp1OQ99NoY7cMxFpzdS9
zATmu5QmaLjwL5tSIu_XneNY6RSXgfrSFoeMD_TojnITM-ChLwuTKvWveQURfUZhtNB7ubR0g_DUAUwvxlCmO7iHsfVYdiku71VOJVE-5A704wxtHU02eRD3
pFlPGPLbmOKBRIMNfWXSG7Dg2EGOSvBNmQ89-IlEXTRr6QaAvpvKEFZsB6OkhHL-DJieliNXtCUpyyEY2nTTNXJ0zI9KsbH-FJlPap_dDn4HfvJo32qxzteO
ISKlOZPjKrslYibmWH9HQzES-S_KvYFqnGrtZjGZkPvSEybD5UxLJvtvarGYcgI6lDn2vSV_Bf_W5xs7OUHSGp_N39-BNqaKAcj5WCgc3gwtG3mUqooIqVRT
ieBAQw_mhyuNbuspjdjQt6Msaz7JLJzzhddkulLeVOKz_V-X77psExwrMIlDJZavN6RwTL-jhP6Ai9GPTbtxsHNsrLdQNjkmmvQkPl-GR_sivnmz_YL97l-V
N3s5oh7yre8DRhYvGiolUmDDl5dnVc_03J-vYX5ZzkMIN7jotP6PEQybhVLkUl8Qy-9Muk9BlfA15i-5zV1zhY1mdvqBrvITcoXHmekOWNWEkcs1wn-8Mi4k
BNiBGJbRd2cyV-xhJcxnE0vD2qHvDEfZGxx5XJdLyjbNdH9oSMw8-JONFooktiz9EmbWumcvltUFvRt5Irtev9h8w2HclJascBsvj_DxmI8HENSqQaUdseb4
Nv1tlrFuhM0BdRAfJ4qv5Mg5uTGGCpgzbkfsTXgJIyz9Oag5CdAs4FFKvdTesbgyWdLbJ4fFqXeb4GRAZFbPTUArTi7c-Bl4Xjam3717ffw9H8TAioVag7U3
ZP9kKwEoedOHpM9WaXvZZje7Uvp11YMFcGIIXt45Iw8IOmxQbwBGQvL7pBbQIcQjAETHATlMx7qfHiMOXutEEcme2uvAYhOvBdQbk9N7cQMd1YQkXPfI7J5c
l5-AUtdCcIY1KsDYNTmOCzulHTS-vWfm7aZ9dBinUpCxEt5RCG_C8Nxul25lIl4zIL-KnbGxPQMAN7HpDb-33RFpdlAa31IYoTMvs-q9UL-AKVkOXsQPFYkK
srfncEOOxDW4kuzvigbsoPfbDMcxB5aDsrBypPZ1jL8IPZJEbWdcv6x7s9JYsuedf6ed7PbLY5DccEi_Jn5ByRxgm-pCBR5AiaB_vxh58vJY3PrdS1LcbJnC
67EQdHjAyOPYTGvhZ2ncXT5IWNEFNIdUZzawzQEm2ZEhSpUbU4ViCNCLxfoiY7CtfNWxvgd2p2gS6hVXt1kpy_u9sGGfDQPipaMcpybFI5XdM75kACMFnbpx
WsjC7vTVX0fHVUGB-e9ycj7jN2zzHNv2cdrrlNv2VfVhCN-VwnUXxtCzvd7yPVHbSJCx3atqTIMzSmZz0m
}

