sprite $image242 [272x194/16z] {
xPs9bkis3aHdRm85MV__jREqQsZ8i6cn4SSYrNScYO-oNwD0Hdp4Mz-6Yf2Ld1fnNDQpexBbrqQbb79o8niPHAJysYYEavQ8tjlGCnlvHx2nBEfhH4yT5R75
f0X26pcd3IoBqeaFpJzEsaPjGIdVJWfCpjL6Biv6HOek2ww_BiKRqVCrZkyFC65WrBQD5UUnmP28yBDTcuWMESNQM-viC1wwN4j4jJOHFWcXcRiuZF6055K-
0IrDtrYz3I9SOsyhhV0pswiNCdbK07PJPKY41M7cB4rQ8fV7ZSD_Xdj2Fz-DrHlHkJVdPjUUSMiYRAC0BSN6EkyQQ_Nhzqt4Fw4JXG_DPRR_ZYs26WyiTerC
ZOVnYSZ6aZSoLN4el_wwEUTAA_Ipg6-rjBH1HATg7DHID-TierBzt3TMChwHyhXnW0NXrbKMXDqisVK9f3Z63itJpJaBWdvy4GYS9QzY_1AHgCEaADSD5WJz
rCOge1y-QHef8xyhBc5TTK-u-n0srcgfYGnK8x5ni22qDX4-0UFXMoshA1AD3Dmuf7wc4nQ4qi-jrIfjZ6walJbd0DIz6cHZzPRuX8nhfBt6Sjq02yAjgom8
L4kKD8UGBs-3Q5XN9PulXCtv34RYvjo4tPJng0LXk6-izTKf6Tn8N6FTbrtZuLPQtqGq75Zs2xcCqZXO47hNM0NLqd9hjMHq8-tDkJW_rryhdvY6WzkCaGE_
ArQubrxAWl3hQcorQKJqY3Rgr-ysvzT0r7ZuLiigIiCJy4Cs3g6M6XAZgRYkieh8-A6H6txTW3m-jyUjYTYYRb6UmKYq4R_-s5Xz4uagHcuZ9Pv0tjwScyLp
UwcjTd6jji5GQwzu2d4hXbzfwOIjjh4v7pOqGe8Fl3wtbx0v7zs8oXQ_jvI7v_P2Iu0K9kkjYFpb4yL1r7_P6bvwIJXV20pSL-KHC5yYRdDkvauJ_Baz6Jqq
AezHGwb8wzn-qJ9DZHHnj48ZZyxjwUTFvCqb8crGZRJExHrZXqPUefiZHZ0UczC4ChuHbK2xZSHp-myXSlb0SOJGn7Fx18VRmijkz6xjjN3aDaDenD7NHjgR
yr7NNXNItqRa0pRU_cC2eD85cXB63mtGQKHXCh4HeD-8uO16z0_qyQxG3BY51_bj8yx7Zq8pPnl13UqqWX8OV-s5fqz8EHxvmpniqPoEyKE3UpIZOtmZ26X2
n_Yx4I2Y2HsZbmWUeWaTOnl14pJXO-JGu1cQq37mRWJFqOIEOKE35jhmCQaHD55jwfYmZU05sl0nOubSq6kaa5cDQAUHKcOtqYUa38d8vJr6Ie9ntWHWjv52
vWuDTg0D7xDjMB5RI1bRY6ZAHpGofeVUq60lEg8DMz3PHh2RCXpySJk-HlIKFkB01RVsdjG7mhtW49gS3obZSRMXT59sXWR4PcgeF6JMC731xKRQFcon2Npu
AsiIcaW8JTF7OZQ33yP3h5u3fP_GM5_aPR6bNIDZxCZym8LuCVJrsWjYzjA7bW4GbAVtWkrkF9wyo8krVHo-G1JrjbAy5qmdMBJvmtf1bkLLIvMY0pIES2-u
ET0vreY1C2_3-eZtWcrxBzXPqjRhCu3OAn-75D8Sk107EjE9DhRmhaHU-3Xc1sdT2_ONGqMTfMPZtRrVnu5VSbZu-jtKbjXgOUA4_C28b6CAmVszO77tWcDZ
zGETKq9gpHqAVozOx7Rb4Im8DmsDhJOETAQFJYDkukbH2FEy6Ozd0vrZg_r6wQFF24NWC4BylU0uPTIDO72x3xRQueq18gBTPxgb7518ZSUowFDvtgwArBLQ
1WuY0kj-FLIE9QHU57Vhgctk1STMwvDL_oegecRqqM6a74a88n6Qo8w1pkA_MjfmFY8D7mHQFijso2mOZyS3dUt9nL16HM7qyHHj-c19VX0_P9O5uLOCA9ye
dSGH32mhg0YCh2tQFhWR_XmQrbMfVXuFN9329wQquQ927vr6obSf7xzZMOVCnddURdCUMgrB5esQCYhEHvEBOOlGnoSpmqY4UTwx1pflrrXFzzckqiVdIcGx
P5QjniDF6ML8M11neBDVOwEFDdS-jaAuzViJQ7pzRXIlt4z3mzr0vx361XzzHe8FHlJFGczVlvyo6WSwMnZe7DVOVX_4GaFzX94u34zO47wWiuQ1pgW3dRyH
rpYwVP16OAhnzvS6ZvVYCBpsG6UboB36zlhm-C1ym8W_J8hdzdwWis-rrHAsctDOsWUDM8b2lFbt7xaj6ixjuxeQ3sx36flpGLWW518HDUWV5GvJhyE_ysI7
q2S3dJUjDcxErIplWxGBX4MILo8mKpyDph_pR9pRkoRYaXNMsAmFZokGbf94S1HcYACajkyyzSb0Puq7jt6DpVlmeBI5C3XqqbyOfYfn8itpUTuIMoqjiTNw
DRR9GX-Tw1U5j15OZnHH_l6jmLO8hmOPZyR1hLjZsopB-YDCef3sloHKv9aN4LOneEsXaZlExKrhiaBZm2iTwq-n4eIq4570lW6WIl3za2PqzqIQ-FNNUBXM
YxZ6fhBIHhk4-5AuYY2gsZtOoWzqRln4p8gmnhPOObRwMyXNIP2OIDC-jsUhxMiSMHycMI69mLRxp-rrJ-DOhgmvv2jd93tOokAvVT_ctEl8-x2aaDmOf_Qv
FHl7pgYGDIyaOmH86MdyHCmTQ-pYMDEaX2G7Mpqxj-_PdDlYMVDe-RaHL3GnLB8W37Hsc_CE6_IH5q8IFdAX-VdcFFh8epys0gIC-6pqRyvf8_h80_dwFmaV
kRLNkjVOXeyiqF8J8qW82Mr4EZVdBHzvx2T64CWFbUni76qVUIFafpwoisdLqDqusZxogI4TFl9j91cLjezyZP0E7xasOb1LM28g3Hz98q8PfCD7mWZtT8ce
D7JaCCR6q_2HDkA17Kq7bGYLUFfyGBkDw15j4DEg9D3maLffZck3IkZaEP8mCa1K8eQsaw898wFP88l1LKgl4HsoSRJnBRAKiZSqDALlRHosVWB3ZUi_8bwZ
ueoy9ohhnq1bMSns-X1dPEoeHDIS3xETFaILdsUoGTo5vxq-MYMY6DO60TcTbs1aY3MsVxQeTTI72uqE7vK8zgCIZ0mTbRmGRwG-Kqr5nLOoWn4Z4nH7FZG0
fhD1hCT8XuybeMEuq02OeZZoDQB1Hzx6-6q4m4Gsyg41aDSnKMW0p6o3e8U4ZIc5f7HC69g4ZIbh965ZIYDdi44KEqXipgTi8udYc38qUsrSLZAvaHFL1idx
i7Kk42N0SQRYY4RYyOIToGO9Fjo8MZkT3cyaplosizaWvkfZbuzrSYu8Cz0RFcoT7pLGmSlwMCy17RpAoteUZ1OQFjPJSO4d-h3rR5ZBntf6dlfOpyf37vVr
n0GVjfuRs_fOVp7w-BNXGcDEnoy6UxED_m
}

