sprite $image430 [199x140/16z] {
r9hfkk8u34GJBxAYzFB-RpiTOqW5JGNqW--IcZrpluQ3TMJPzDzFviyA-NlLhFzYjloB6O1S3sBPiu7ykJ84WboFmXQNZUtA4BWWlwvPJnxaqak189U6G4Mk
0d7D1K4fBWrYRYckM5a04G2vR3sv-UJ240XosNh2mBP-IGXS4BjcFNcGIpLP_SgUzIS6qV9KzFiK2Qv4dhPKvPNr_L9ecKPc-I95VeMMGkiyxKajeCWNrPDq
24ZMRzZMWsQdQGHeoWd8DqhHyYx5kkG7n_nJhkDInCsUggsshffs4FcnveiGgg_Dtel8LhkznJQ3wp-o85XFMjoxuEqfBwljRx7-Z288OL0is75yv54-IGzb
QAkL7QGgRxwVdJpmSoxwiZqrVmjwS5tqmpTpNWg_3Spr_hIvmMEBs81G-Dn_G16G0juZ9CdjqnTeJsZs_gmelaNuDFBdGVmutai2asLxq8ZPy6ok26Be-kSL
6H3uQ-iykJIiE3GRgp09KwHoHJu2WIM1qMUpxSbsRyBJTiX1FZ1vO4bWz3Xuh32CkBcGkHwfh7YJ9I1vmhJ3u87j09FKdZ_hYeXyFldK-6HBcY2kFO4LYB50
_7POWfKLhoS-zc7o0km63hdIOQx7csyS0YUcUGGM1GOFS8ZQWQx758bBGUKOMJAs9_zZYrysxAvyEupF9_4pXOr0ROtsH3zggAzPIEyBA1Aefz2vYBAlqejb
u515-EWR1rbXAIBd8Z3RfKrRzig1qca5S8oS3kFDDm21WmT0-6Z_kUQDBws0yNuxv8f48UBd8fzysqrWryJuqTVrj1Z8hu0KBRd1WwLsLFELWyPJHGBDDtex
ZaD61OWpCUxH9lM0uGl8gbid5oCW4GX_BdebXlIVKYcE0Eg77rXuPSMRRE1b81qvcxQQeKlnYT4VM5w3nALGyI-Z2y_DLro4L1l8GGydgN48LCJ2zKJFHRbn
CJ1paIudj5LoE65zGxMf_l-2lBqKv5n4L7mgerorDn73jkeF9_ZCHwNMAY9jXxbp_0AAmE01pzpme4UNKsdBEX2mhKAFUBDlIDrpWz4xnniK_Dh6ztxdyhmW
mV6KiVM8GD_G1mQmB1tZBI_ujGqcoTCYz7yqEnCqq9u00zAs2ksB8NhEmAzjCDxbZb4jt3S26DBwnz5BIbBLwCjeOWGFbmM7aFE-WGUM08OqVOmcsbHh4Wsz
3B8TNBRkCWmXyRx1emwYPHdLARMAQg6z7pHc8pLgOyVft69VvBp6G8ZxkxQEqP-rJ43C7CZhsmASpdc4j2UEWH1x3Tac-FrvIsCJyvqnkSCbzFvgrPyT-gFP
edtZFEtHPdLHD7fW313YEXIGknPVggtZdWd-_n130tqZWB6j0NpcWD4Zn7KS7lnjietB3m0HJMCwPr7Udiun1aH6JHyO05BmxfwToRn6JzEUmuqTM7Z3bROC
ipb6hpebhXzBfwXVC6OydmYcRBO4edepU-dX6ADf5QA8EjV9Wd5SbTbT80O2_Z8CTBsyuRgSBHWQ3n5odV1cu8rH30IfgH95gdFTVPz6tsS3IlVBQAsd263s
QmniMjnrNloQM5rXUqfF3hLkp3a6ciqnF4W9kCuXu8G5pw0uzzFw6GQqq0Z66512sw7_ceoTYs0ZWWY7g61s0CCFAFphY2Ikc-6GuUzJM5-JSxFZ66H0OQxd
vWZTjGqyOtsjCRC18eY1JKiqeiWWfDSsPEa0WvaTn-2ky-qGGGIl7VWNESrXKBFZ66ako27kCCAsGmGXN-GG238HWzbnZ7cQqjkkdso7UdukabosmCSLCnin
h5MFqL-OkNu--aQ-o5cV4ZKRCTGlnpGbM92ew-Gtk0L31crwjRveQo9on2YrZFL04F2DkpvNZPwBucRxLHqkTXZ0g7cQwrFSOOHjXu5p4T-p8nZ7ArpLlZ1z
8Seq0G4qhKAtGmYQ7GsnaCOwXhcJIR--J8113YFCzUYDHzni3BkBbcc4x-jLkI9ky0YR7Slunibnr6dknPsQrC90vCLs-5ztPu8Z8Gv3qM_7Mtgx_srdSMf4
Yr99p5Tdn3JQqCuhvs4RuaBsctqigTwkS-OmIFTYDHE0hiHkLmgKuqcGln4Ghb4inVDhCuC-pXG0fAq_fv7ACLugOc-asSpuuwltoQdZSGQCCenbFSO9v7M1
GfhDZWoUt-wVPngww5JaJ42l5oYSsHJ4svMz5etXi1b0nTK2XJ6RWtY_jlEbTvu7TFgoNZJZ37A-1ChioKZH45T00cCsWg-Qhs9MHZovpeEqsPmKrpTKbS9I
eDEE_iv7fiEUNEUELECXBeEKhCPjGFNHtnbW3eadrna8rkptVxbZiWQWDHMZ5Q_6032g8awkysRpKbm7oNRTMl5-gUVMWMbDJit8RhCx5FH6t19qogv5zAYu
cl4xo1ZvtvXDWjGIemy1HD1r_5mWSRW-hBQQtHJy3FBAVRa2Om1y3bXVZnyXYNWq8yG3VkRV8nX5lCMU1LGACBIZaP2gZicf6I4Uy1DcColBW9m5Y0i4GCnb
lDe2YTDDQw_PF4XsDFgeQ8oo40V4w_0zylNlNRJPNpyxfby-EfUa8DUQciVBWIOvcX72R48AUe0WZqUk0rRGRB1_GE95WKAR_Rvdy2yXeS3AA98OdWB0ZetF
wwRbHPXDI44EroHq9j3dKGaJ02xoFVN7Sftliu_6QDSyQG5UvNsg5NZKlp7d6MHLJRpPV2Ykz28EQAHtlJiS1d65d2-qCh9hs53RAGMlI0vqAY-13nW0Mye_
aLIgZkAbs0mI2jWqe0I-kf5wiHtRzaFmMQHYL04MG0338QygA2CWc4p1Pv615DWm1Q0_XS52y5cap5Om00m2WrXFUx98YIjqmDq93A9ysWHIC_fsYoGmTgGx
lXSHm454WyWKEnLH80d52OYj8EMZ54LWx3ARRzUJm20p1N_mSvjfDrfF_1Hj6W5nFv0qGehxWQJT28AVzqyZ6gFx1IIDaE9-86atMa_ydp2a4JNW_HH98sh0
-wsiDA8nkXz8sg_uoa3QZI3uGYkDo1JtSptjLtmF9Ur6wudlHT88YFkbmpG2ucuWRsyptzx-zz_HwcDxpluJ
}

