sprite $image194 [346x136/16z] {
xDU7RQj140FX5srp9IpxhzOvACUZudnG1OCLSR_lJBiTWSwqHRyo0bCGAGl2lgCiMu3knCC0FUnYeLdj4M6XPLMJwNGg_VEXeAqSGDP3ugArXoVl2DgNjqEL
PWowM-W8NWUbuvHNW4RmE5nh_ch9EdkrUDHejl6a1BegXQmnP8sXQieJxwiKiiRmm4efnZN5DwzB0HnjAO2qEY-ofXGZaE8RqmfqvKkiTKdOrXIsDOQiAMHD
AROrXPV03Ch-Km1f9mgWREbw43Mbg9h2sog5MqrfeeRKxJTb3geq6cLLcaFPTlVmffGzigfkNNb__V7xuZtKAzs9_QlQFSCT-DTViPTsxKFPKIm6ml3cqDqw
lF_JRZ1kMAkyp701-s3qJvxAN-aASSjpwr3ROzyUKPDUi2siRTDHMhAjZQPvMhFhslaisUoQTsiPhfHjIJMnBd_jLrWwgnPsmF9hQGMqPwmjjtm98DDM09wz
LVqVwe9ieYrOBXzMC-lY-m2UqXQiJTViW2pBsRO2uAswWDg6xvELQIkC4xkWcaMNPIVQWcNUgfbrbImvqfOhr1OowWfPKCoq1PjLloHhseBTEgfPbgRD5Upj
MrfVbvKkJei4czwmlYuRZQQzB6mit05RP8MPjc3z9h2Fx6LfaM67VGAeKLOSQN5LMAFkBXlDj5U3PKoixHXPmRHNSWLlhBOzI1QGJ7ibM7-dTNTPJRAYQQy3
wnsmkon4X6KZU9KJ0NTOinuWImAqx6NU6N1lEAe__AtlMTQq1Rl3EaYo8otATLFDj9nacsaBTbFmFY0js-WJeM1tsGUOPG5zwhB5yR1E0CKiwutmgR2_32y8
Cwqiop1j3UmUgnQWPLkOks0ttWV2c6KRFctPueMm3gPDiXxR6jXzQCEo3DFMm6vRjQQLPTEoBTZDjB1iE-VdlX3gm3KjX2nxokSOfK07i9asp-pvDW95gHVN
YPPtsfXuUJfQY1Jj-cPOqtAYdMG3PwArB0CFhcruQwOTcsJFHeiWAI0DR0-qMPR4gKw4copx6DZdXstSPTNOxOc04FB_wK6MGwg7vzWagsutWa-iB1kM7Nf9
QTbQjbTQYe-q08AK3DjHHaoox9CM8gNq4JWg-dCrxTsMOTc8BcaH90CpAy08sRMpc2vRpP-fqpjfIJm_1AWRg-E2QrSt0jJ9P-gau7FPG6xeDTy8MVQjrvV8
u89i_wxvNPUMdV_pNRASxW1WshDPTkWypWyoqhApzullVyiofis0ssuDaXAcE9oWcH6MVH4jRd0vYgJeKHNkiehJZ6k-lopxCbhCApNBKhTLO5b9eHEvEiws
icoYFVXApTxUgL8G3rzKVmpkRBOIfYGSInjUgTdRic2w1iuNCDgAS9p_SQYi-1zLvATLVcYTrfQInFiVI1qZIuseJY8LIRKDP-ukoJ6aZX3MA8k78iCE7z02
vm74m7FP43z9rI6rktCQJzAEZiYgnRkwwGh8jU6JQpWwYbJmOUwv0sgDhnIX8rPgwP87c9Pl8gruj6W5WglFiMBxSgPCdL2sP4iMXREfFvx8ibXsYS1LnlHl
}

