sprite $image38 [381x218/16z] {
xDAr0SDG44J1LFVf-g_M59j9D5F2sysT0G0000000000000ezqL-6rEKb-MdA9_ApyZ-pmM8ydrJFaJvfRo9yWzvY_1_xyzK_Yqlg6KMaPIPw1zbRaw_b_vE
BtzP6EbdDQIVa_I_8t-K8tjdWXivZ4DHYY8byjizS__JpfP2nqbBiAdOFUNbOUabNe0NWvHAtwh_4uz-mNvurSo9KkAirH_zQs0_QgOlPFjB-f-AKnCjMDN_
sCT-23KfQFBezuFTF_RxO4SATJ4Sg_zPAc7g8ZZK_ZEjSkh3s9F7_K_aF_eHmZHpel-GkbEd52mxNZL_N9Apsfti6mAuffMnUxpXMgOl9FMxs8-ffsrJfqmT
5D_nrh4X_JTnpzIaTeskkw_KX2Fsx-k-RHybDOpMbliswVhs4K4eOigLLzN3qpuJWikxT-fJqCAAy6iG8yM3Ks7oQzjtH30QcxTgHXUXFXLNjW_y5VbbKFwr
n_l0GMMdBJzUTc9Sr7syuRRbHnlkTUqZZFDGXIXvf9Qn8ugStttSVgeObe-QUkxZNC9zi4OBVY0VjkE2rsNbjwTEIQmcjd7vbR99eYMiVkamFtw05-7qNpYh
EG3FmwCT5oe0t3I_hYd5CCuTLqyAPH-HRuaDkt8_zu1pgd7vXSHl5sHsx8-IEbgu92sj5I_FgM9tBltW1qj8uTwIIqtPSG3tSDzkdls9GS42LrBimoE__J1p
xyCQusGuY7laerRBkD4NIcDqT3VvE18byTuQOMdKfqV-KNtNQKdonH57SZltxRvRbkwjCRX_v1_OTutfXVZeuFwHx_PVV7FVBVK_080N5T7g0AoKaf97xnRd
IkvDSw8F4gjX5SlBDHPNMmuyKraHNtAY5oprtl8BqrUu-4hPMGvllAHNpJ5w8O6tw2YftrQ-CVr9icqBxHcewVTYbpHN7TTJXgbSvjCrXAW3QGNzrFPfN9Ph
vOesbdPQIx-4_3gIQ5eODDGlVtl1qIY3NaF-Fn0XnSCYIybKuByBK5wDvEIh1wWGeGR2V0s52-SLldgoKn-zd_mIqD5Kc5xNO41NJpRgan_vNqWTQ8d1N_qv
hPzCVGGXBXyAhss-AYm04oN_Ni7wfxQfzvCF2J-AzaUvK285CX7x1xKdir0FnWtbEqUJb49VI80HEPp-0t-GkXr3g4soEyg7jtratrge34WPADiUPTqfjtcL
JP4hHuAnfJ4L5W5uO_ZUCdqd5STTvGDL4Yt85NroOuoe0ji-Qx9lToiNYYlF6C6AIivPj5XmIfm05KXeokeVTyjIp372T0NvSRXXMSN7t_bvvFzaMgPGAVIT
WYEPtrN-z9VjPwXmv1FwH_uuNeMuV5AXKfO8YUDOVhsh_1aD3eqhgpJ23KSotL9-EngYqZhcGERtbJyT7jbPaTy8Jjr6_dnqM6r5_k4fvUcMyetPi4q-N4Zl
A7_24VHhYKgdGh7Z2EPtbZyVs6a3yk6PAlPdUc_vqo6TbXq1-SVrtVczvS_O6rTI823_kBuxNLb-tA5A_BSsplpEydUmRqKoCsVHwXkgXyfwlVAghsiMmq-O
tb_-X66gq18kZS5zH3uyap8jaOfXvlUNFm-hvtYMJoMyIosFwf_E87yQdS6sOFk1V6Dg8OuHvZF8dp52fZR9XkLReZPvoFq9v0_QrtYeoQeg9otLmzyneGWp
dKN-X2WUZFDvoVH9aXhBGIT7bFaiykFsZVh8bZwQId1Jqo3pUUJF258Zyjkrd3qWloB6T0RvSVlnbnVgnjQirCUZxayaFsu_RnPbMokvKvUC6FF9v4zxTTpI
-JMj7rhswhVpkUJ7xLlQLdGyy8AFxfCAdyycFsxVSyjJHK0-RzhFDtlG_Vdan-t3yfRD02XIohtmJx-wTJwb_BXzU16c3r9MYtudGLdPMeEbE8BCPvK_JwCx
mBWFj6P63_VHNLxciyZ_DVy9eeotPlO35inF9lzu-yxKG8vmVrxvSVlZwoxPS83xayi_AaXboWlpweS4f4ugFsu_Zbij_w7wGS70yyblWzCnpPUHFqyu5tEV
VvxF_do-nxxDhpFA_pUxzM4aEGn3GJG0T0_oZ_OipviTmreGAhmGMbye4drdtpy-z9yzc4tZGulqNUFBqlNsGDluANJEpntoM43V_06TXv_GDdz0y_Xfq_pS
gtdy9JgcDq-cTCiVF22F9e-8NkazFRxqoHyyA0_7mw91-IxnfK7_u1bvF7bAd5uUlMJy9UBCyelP0A-8el3zso_oceYJmY-IBIYlYutTWzUPJIXxH9HtNyms
PAU8gAlEahtgxnUVl95yHTzCin7aKh8LvJhCPdJQry5ftxR-j9_wPbDE-q9AQvgDwRIlWzE-a4xxEZhjw-2ahwFIJTQOqwDaZHb_MVePlv3NWyxi_sFoczUb
St7-OXxzQbuUplEoaCxgwznqLbz8dTNNmIbVI9stPI6KAfeLfh_htepRE_TNp1-6UkdDJtyf2JyVm7icFrJTt1tCEmrGtTBTPxeFVE4dSCVUXoxSmuNSQ8Y8
kWB_51jKLBnDg8_jmO4C0000m21_wtjyrGy0000004
}

