sprite $image41 [110x80/16z] {
lPQBrfim38ERX91OJlV-RxiB3TMfWPZ3wA_TU-5R967pkA9OItZyaC8iWEIVWKq24G5g-ZuhLK0M0IL-bnKBi83w7_CtuylTHAcbldWoVJCm4b9bV5ypKGJz
yk5xyOKPaAxruXMT9pdS7zWHZV7TsVekM1hZkosm8OrtmmrZIiIZzVXkQVsOHg5ETmJcqtWttD5wZYjB0_puphUUDgLK0KE3PBReUdofmbPW_H-G1fHWF-lV
3NxhIw2xQQNnifCVdnyOHNlY6r7oWH5EV6xh1Oh3TeVQ85QGwKBhGLxTjsTM5MeGdniOKCbJBM5h11Io2e0V7vN5jkk3hshQ7OKcBdS34-SkSW8prPZO0QYa
lq75b6Bu-sTHjIU95IVYeubKCaVkFEWY27GlfUaWFg_rFIVpBi2GTWP8TEu66nYbo7jLnQBTwz7SWs76Is6hXicc2gbppZFB2bOlgsukqtUH2GoeyrRbRNiq
DGlT3z14KQco4R1sYCiPrPbj5QpEIwaVxPrzs6rV5dIxsNeCO7nynFoHDfRNWZUUiDgYR_VJATgqSvdeqCAQU5FjFC0Peu9k6pKlBubtje85eC-d_XNwlrJs
b6YRiJBhvojndlDEprv3GDlpHUFnh5HB_3Y8YCeK5dicKNbfDILajAOROJ7n-KzyoSZqT8AkBwgY_yvTD9WIP96cW5ZLYLrN2CLPijb5mKpR7XXf1yTZ_q9L
V93MFtTtKH9g3OoqOrvtQFxSAxdKvU0b9xEBEWnR4qaRy5JdmELirfND2Qr6sa3MWAQml0zM3gDDfLfLRM2MDZmUp78UFZP1OGBpQEJvEvYx2CUjtz9yNcNd
QbYtT7pVrdBSUfzcu-CI2wLX_Qlgp45ZM-_IXdU3n7KvrvNsVe9Eq969LDEJF6W92Gg1S0S9L68Sjfxw-th6QPwgSiDmu-cuzTIlDZ_2hEIDuuF8bYPEO5G9
hswTFTw0vfeeaOFKv_aqw35BFoRUA3x0eRacjjdEkpAAxu26SoRQPqS_lW7DOI4TpJkNPsb-OFbngAnduelTZBEjfox41ual64wqtb7qxOHAAQ8WQz1wJnDE
y1GCp6cz9tUO-O5L1kOg5ZqMBhJUaJFCHgt_DMZzfVWm6bFbSK73NTJSrliwFypQKM1EwztuV1fn-Gh3tqND7LE-pW-pvWTsOtpD7LFdvU-YveofU-DhpdA-
DxxcZYbVvtTHUu-f_s-zFypQZQttTr5Zwx-f-8glBRF-djRxmwmvhRytFYxdxokKYwt_0m
}

