sprite $image65 [260x186/16z] {
xDQ7RSKm40HHPtDM0DL_jpRYppbpRafusACqtpi2-Ph5DG0WipOMDRq04A52sCWyWaKbO588xEvBD0Bn53g0Mm70hT10Zj01t0gSMlG2G2O1WMWAZGiIRs1H
XXc1U0hX6YNUCs1H2G0PG42eqBb10un0DOLmize0VmGE1MvTp0ABNk0XC2jmnqe0Y5bWKGa0hGWWPe559V0C2Xti23n9_Ga4h5i8u5ReF5jfuX4iAW4WTpq3
jmA0Mu4Nw0uFWLfX0d0hy59riS2Ykpm4gYz41t0hyCALm7KKmkjN14090Bb8mAt0M0MnmA8Bpa2fq1YsN706BWM6hua55XN1WOEOWgHfjy6K8AdlClWlMDgv
0xt27_dcbjn8R4DHuWtYpkn_kncHFRBWgAhpSaKj-PTVFeLx241iWAs0gW-M8q230Xz4ePuo68Fd9mQYCnX3Fv92Pp38Fr4BdS4O79zO2ft16FAHWUWCnj3w
90hvbC4WnoTfuO51ev0VHQ4n-5Gjr5C6OzX7QG783k7ZkeK2WF9d53W_eXGAltxNgdfzLWgVq3x_8V3xDsfHcFBFPlItdwhh3u4R0nmKWhw7GSFvdQVgmYAm
600x4Fuz2-gfqhJmPYAuCuW2weaMA17gBhgEtZG61mEYk0SYkJ60gqQmBqhlHg0pCCqTYAO5aa9eXeV9flHcCUWCmhJkMh2_39ZS5GZpq7TgdpU1pc2mU8eN
-Zr9EOMq01FnR5fuYnXq1bffxjgri7nW8Wcp2WixA5t_FdpE00YpS9btBJWDDY3KIDMESrwKtaK4dO4KfgfwgZreWSYcAqf52wMcdaqBLuz1To9nJDtTW3Oj
a2W0uzlvX9lRs9JUWK1deC6i2RXfXEQ35eWTCBkTJy3TshBjuYBe352cMd2By31zr09vcXtdSMCW9elI6uYWCy0q9ZShk7ayQa47Ym6bJBxgW2qFIfUEGMSW
WmrJCuMi05E9KFyAX10RIcSohoo8nAPKzGu4VbNjDPAg9g0g4nOLvivVMWWcCPs0BGO1D_VMFbyt1hzG-8M_1U_BYQGQG8IFyQM5Sc8980u6SBFmfeNB4hWL
oNgCWvH1NcurbHsODmQazZ1L4tbj1bf8TO_GJUdICLZdVpxVmZ4lCYyVCETcO2xne8N1iXWGPohW5YwlhON22O7R-MBmbuBHxWR2YVt6G3JzSQfc4Xs38eWK
WAb679Gk6OFx-TVhD4mT5A61qiN0qZtKvcFxl7nGQZfXbk5XczBLOh15q1WS5987S_prWQDiKRW7Okhk4yE4N9T5FLKNe2kAuCwWKGWYieE10TD5icc1YGnX
I6O3IbKYsbHz5H4q1Xr26P7QOa1QqsUPXMa-jiyY1a1PPkc4MnXlIfSIGMVGAKmPhEjkL5BRhL7sPHjB06P6gdDPjFrMVHqHT0RVj40x-9DjTqGUqPPjH3xD
KI8EU7XxmlA217eCJXWSzwJJbjzqadG3pA8ls-wZ5AU7jz-ghnI3pk2x5WPnO7eQRVc9fhVscTXHcauK_YA_LVyhZV4fWwu5yl29AUPLwcaUgctPvguJfNS6
JGilUH-UC-WKWWTh0kRCeO4ozq6FMjXozF2J9omlT1-UC-WGLi4dB10a3gIjww9DrHoTGLkslQO8pXbq2ZfO981IibeCsArhGQGnQ5furVlmd47N0h4aIar8
BTP8tNRmIcn-yhBj1KLmpg1hWMXEJIHl1cxfVTaclGoCjXQgNY06LVXt4VI_lMRoiMe1kHWufdguzD-gEmJT-oRK__q-_Ay8T2qGSo9ZCq2gQ6hJmgCKUR1p
qy9BYg0JEAUGGko-650WjQQwFopRfZOTZ276xSEG5xWFJmcSQu46-us1iBW2fHxHfkg7EY0YKllXzhb-FWPzY3WQmvK59vs0crYQp2TQa36OY5p63tulLYS4
wdz7e2_RzZ-LIbOUcEfzsNRK0H7n81biOumjpylSX-TQu44oaPh26i0qzLJ_hWMciJWGjGz3Bd4VdWS2GIGP2eJOH9cxXNSjx3fOYT3s0loQ8dW-LG-s0bn9
foLItSUt9onq-njCetylLfUv3y_Rvy4ouL5AciUpXD5Vjj4k0Zbfdtz21FX10bqBOhRao7am6AC_OU5M1ssglaGCpYau4LkXJ4diO30uMxSWhGwQ5gvCeE_W
kSgoRBZT2xwrpqpqZtBEH4bk40QY0UP4gkZ__pRHNBYDlBjAnIuBlsJlEbz1WteEyuKX0Sv3JooqF7WncQeX3z3IIXVZhHHW1vzF5HtCohOEcAhZRGExR3lT
m074WbQI09Hj6vw7B6lGohQKpkW0Om7-09OY1i5osOOEyhj6Mdoz64pLUvcG_M073vHNZTJAjkKDiNuGiAmDKR_WtpKIJDKzPzA_x_XYx8-5HlfhuQIzAfPj
7LTIwhulnhwoRR8Ej3qugnQOgZlk11O2d8VBL885dvwtv7mk60lTELdeIQr1ju4zLIlbyrzZ0Sisv4vWuR-UXxzbE_2S10kfYuLp5ujlQgZpSDa2p8klNbLZ
8It5GgO9DM8GsB5mIMqTF1zkKHjsBAGA4ch08B0jrFDd4QIinMBH7O1bMtC0r3rVZFsne3MIbj3gOz8kOonacbE3RWCx5lAlzwCCgRJhCKxL5-e8Qm1vnqA6
FcrUjfMKpjJ3SRU1_SosrvKnMrErVZRWVpyFIO2zn4BVgxQfseR3RuD-gjOyo3WrNx-omEizWhezdxSTAickaMm97288_8zLWmGu9tjutKTGjuVfctQv6Wxy
HT6kQQyNwocLB0iSwcBidwgHR9wG7F8yz9TjMA6W1Hvd6zXJjLaeueRWa3S2Vzc6km4jSCZpq1yBk11mGp06GVnjO9TjZHCfO85ZRmD_B6HIO4EmupmCAu4k
2RiqjC0yh04isy01Ml0snk5ZeT2CKOF0ZeMa3cxKmOu7Ji9Rk9xFT_8va96WPNXa1OZVWGo8pu4CYgDFb67vgGCPcfyuaE7vpe4SWIyTi1o4PGTo86m7SYou
To37eyuSo26PEf33ydOWH-RfGBRc3m
}

