sprite $image153 [209x152/16z] {
tDa75YGW309GDL43S__pRk-DhUxWlm7FuBEqGtgHjQBTeY--WJNQ3QBuGMLlviRcPx2w-RHzROTjd0I_gTA-F5z7wjRbyL-bFa45Hf4I_1cOfkNnxj9Oe63L
fGd-eWgxykX8epsbKVnTgFLqgReiZmurpCgZrUncMxMsuydFER-kqgmyMeLPURJLlSgZ8SpAewtkLHwjXi4vvvSWpSgZJRFoQFlO3VkKtG-KftXGTUTfEx_P
zStZCDpAenDvbKUhxbKUhORPEUVyoMw2_nccsJb7gpXL7gzZGvyKlEOkmQU2C2kFjiU1duIZa6PRjLR3h3pQD2kFXZ0kZpuCwKk2WmgpQTEMMHmDuwzS4cpE
GZr1ExlVCMrwxCQcgxGlZput96XjYVBuMQ8yVgOuv_W9yHXgPujfiuFUOlCc4NoymckizJRCDPaAn6iaxuW44kzSiamF0YAIRw2tcIu892Bv1HAHh0FvHmA1
go8LWQiYRG9NHLe4Reg4971Jf0hYn-Xr79-3XC3NN4950_4pJ3AXjI84fyDhjhRuiffpmNbMXu6e0tbv1lQ_tOjkQuc6yhlv94XxTd0q6VS1yKSYj7puvJxo
sLGmNANnJro3KoBJ-NubUyoVuEYqGC6l_jSKwD2nbFY5yHW5ZazVIEEVIKxqXq4Bz9lVPAfmukap6l-cmemk7pCQTkpyouSAHsYiKVzD_uXtFZ2-rKZBR3eD
GN4Kmex1HlqtNHFU-RXAQaQ39xKV4VYYyMr6xQuZFoBJMHwSAa5LCG3_gdW0MY7JCQLp8mukZn-HwUmvCRB6ZIoFtwA3ZeN40x3E3IoF7n5sFfwHPSeXhpRx
4G5eT1mZQACqj3njHA3nkP4Qbnkb83q41VUS69r4T7b8sdtR8IX9J-aqebPf_3seK4b2QqMl4NG7-2qtXlxtYI8prcNvbz5vH1RIa57T4hcHDfzbtJ0bzaPa
IkEl2Yb93HAmFkWnWZQ0moyHJjp88darTaRkfBlkiPBQgEubaSHi0Rqe-IqYz00ufZn68OaWqxg3CAFECsSX3IdFViQ9f9sFbd9cv0bPIADsITbC42axePfp
mOSHwLi6bCS8Jw7wAfJhXn7f2U1rttFyXF0gX4seQFUPQuq6tVUkHw6bvBD3Hy0JCePi9h8fDqbUTsW-FNIV2-cTvMa_XwB4lT1IpoFoXFRSMXvZvaQMQNar
Ahcq7w_zGZfYHrxWXah0-WB1TUaNQXcnraiV9IhhaRT2w17I2xxdUEJ7cPkFFXRH1KATvUd_kgr1U8cGygRoj6SkIbwF-4BgCM3dTkH6bN0IqKL2LfuB2C-8
adlcZa9GZzlAquu55L5NgBz22jw_S3Q06qccnIjHVq3gVC-vXiGDJ19T8RmAgSzzvMa77MkGx0Zr1wJEB-oBcFdyxwSi9qBcWquV7RIjkN03IIIV2x7BnxYp
FEte9g98vCu7Jo7JWQFZ2vKWzp31Z4AnOxVK-IbaFcXrVC11YxHdsgcJAOCR6YKzXLeTw5-4D0QvaKHkFCz4cARm_CE1r68gfjD1CwhlDwBEkzJi62RjrJ6Q
KNqhyH44whoR51hiMZz80Dh9q2tqCwpoEKvJh8zyZ93_uaCRrKEOAlUOZp7rAu5Mda4aS4UTsWmhqUTZvHckPEEX9UhdIW1rbk64ELTLBSsdHd-L08juF24u
2y7K1yJ0zlJlFlNZGPIVOVAQ1B86-H6iIV_KqIG_HjGp9TYm_Z521KvqDCfFaW0STOWalyfK2JGwckINIGfJmaCdoA_IRWiZxSh8ZnDY0KcKmJR_0G
}

sprite $image153 [105x76/16z] {
lTa9RW8n38NXxBQV0_S_RakKgJ1HbtJmV1VuPJrsmZyK2ENWBZOyS8t1LHKSMWfkYk0PEQKIuHLbft5Mb3p6yKzbXc49j-mopaeXBJcDixOeEOspQaxZh3Xv
ZMC9K9p6MLN7SQpcE8xLtCQn1Crn78lpnfl1EPGSnx5Qz1bd9Tbn78kYtpYM5CznlZ_AZkDxLAnmq-muZZYQSHn9DEFutXIhu0ArYE8A911SGI0Y5wM6IqAJ
V-UQ55-L8eW19rmXufyIRUMIa7ACIqQ7zx_xDPYEVddtMr_2SixqxZTpXZdddINxcJL39dq5mKaqC-OaA8QbTFgQgHoXem5JUkDdEiOnKH-UIo8dFtgl9s5c
R0aYR_momG3cFKj9FfqOnwhQkpwi9OKyd1ndIj1Mj7zJak7SE1Dt2doxzMvAzYIH4-DCIJNb--tJBDcJ8DEPSORI4MY48C-bWtpP7iUgNOAC43MCqdhIj3dE
Uj4CIQDlGzFUE5PMZJn2dHe_bMnesXh7YggvZj2jC_hteUzBKiDg9PtIxV1zwB0pZbKxuXXfKDMTq3hEzo9wpUj9EichdN4iweXyVmrXEMYou-o8K8vwjo6T
8LbiZcDNqZfBnqXg3ZBCE9keQmrqkz_loe-E0Z2PDSGb_8TqRI5MQf4U5LMOZ676sHMbwtW09TKQOcMJiSmu-qYx2f7sUloMybr7pJZxYcZlNNAOAhvPg8Ip
KgaZCqM2B9IZprzwOa1RS66FWd8A7knIKDJWAF4Z1QZKu2ppV24uumC
}

