sprite $image103 [338x259/16z] {
xDg7ZSCm40LH8rdxgOFTVxMNSmvp8B6OAU7XamxIURtgfhEHdgofdhofe3ofdhofdhofdhofe3ofdhofdhofddTjKlq259gfdjHCBLN5cTfMl-ae70dwyKoj
_b3aGptVxjH60Sb83PGdrVFvqRT2qxJm3eBYwOct2GhaJ0_rpxbFF3tn8YYUdhz9r159sJ8IIM5Hb5JKt2KfLLKqXV-hJoXJIOzrKoQHrgdh5z5accbBpwfa
dkdMykM6131rfi_SGf1g-WmkqHJeELmqfNyfHLD4r9dIefhoeXvzLdJ5cPuQY7hqIL5DUT4bhzEjWQWp9KINDaq3qQLCnzv0TA7hDFj-qK0Kc2dcsKXqlcd6
tabqlkdOxsiXElywpVvGQZGGdJtJF0xqYhqxqN7Vve40Jic7o27Gzt_S3raZVnkXLylCrrRHeeEZz_M3E95bfViGLPrSTBmf_1BJHoOM7Mzgxa5qheq-C9eq
UaPHdQbEW-WuKuFVYyur-a5fc2ayPiAZABEWD6OdPHu3qqiCKuW-BGOlKuF7c5w3IHwW3epHem-FGVWpPX4TPvhtDFVPH8VKQRv0VJxH4NMQBr2VJdJ8wES7
VZRHWQQMyPnKT4ITcjya5EYielz2dL85EgleWD5F5UYaeWDCCpicztb5ywOWwfGlqFb5-wG0u0wyPqe_SiulsZS5S0udOSeKwFoYCGyYd0AsBxB1GPWIZvo_
IXI0NmEpjYr57Yaxd20bTao_IVHW14pRlgrBhKKkgUOmnfGV-Fb5RLrgAH9Ijw_VgGvY9qNic7wFQBl1N3PrTz-BI36tcFuJ5uWTqoyItUL8ARKkwxOtEviL
gyW2lBlX1r6WlqjqQwgt3lxrHntsdYc80lrLeiKxsSygJPk2s355qKb9uQjKxsKzgpHB2dhWpqnt0o8lYXggj6CQH45umhJDz3DjtXHrEwiqQGgwGCz5ZLc6
Ff06qTigRGxBcoA_Ouh1OJ_l3GZVPF4VieeOtY05Lw2dvzGt87m_HRagZQPW1nvshENPH4qVEKMh_nGheKfxfeWxfdo1Jdm3uWrHRw5AUwRW1zxclm7XBI5w
x4gH9cKyVyqD2DUKAAfKXoMYokwO3BC_XUeZC2cUY1vLcWbVeBE9wjr_kw48tCaglGyvy45qoaluQgWvKT-a62oNTpnjqXiGtnyFBsAUIfKAouOeqAb4zOZT
7purJyMAh6vggRmny1FUW53jYMwoUovDP7VLb2c80fr6L7kYvarMVmssPLaRxewVeIbJ40C_YQXgNnGM7-nHd-_huqO_IGfYnpI5gEgFeYuLSIqUgHgeAs09
Kn03Fu6eQaQqYeLFzJzPyVhfj3ZiPrDaTapJYMfET7lzi4UHCqLVFvss9waIeg509nBL6BkBDzd2DkcQTd-YtoT5ea3d4bNDYW9IRqNNVJr-PG-VJWxxmHI9
0fr9z2zzGzHBGPpwBsPRlcXVMxOOO7rJT0T-Ej6c7T74KrCz7TknHkC7FdttQS8R47g6BDBj8RhygO0M7qSNeF_D2503V-QlprwVVLEWl1IfoYDFlwh-4Zq-
y7kcoE-OOc0V1Dhdl2M5BuARPwRjIOhxsr3TQu-W2lHSopg3fwhPhQatsUyMgVgtARAxdKdTVPhm1aJJ7qMZwVsZ_V8GBPOG3QCVHK6yiVy4KVqvt_GUi0Zk
jgJL-g8TKroGc1TEuqN_qhHeNAQ-XpDIFKYH4usZ3txW_JD4DIyQJO4mzguII3kYOPdYVKyZRa2CAD0e6atXDo-RcZoo824QJGzHS6_inujgDXP8moO_d9Ak
6T5e2gv0Fq9Kyp4Bfl7P_insa2P4Ovs2BD3neb12D9XU3aaZQVCOaURzx-qoTnol6RS-6T5e2YlLOzQ7QC6TgBfz7-rx9dR_gZE0gdrB2b_b5D3Th-TwMrhq
Z1exyEVlbW6Uh6WqXLuAi_sPz7R_x0GHwuiIEwOWgcs09oiQJQ_FJVjPdYKSuZzYd6Z-_1cg_xQfCkaL7vfirq-aBHwLdb4f02kQUPg2FZFManSrjSi6QZtt
zjljPzCkbH7Ddp_Zt_sfRSgcRt0-tBS_Lqgit1Rf9jKPqVJn2VxD7zqa-dUBnbs-5ZbGHMv55rdTUD4uy7rH7Rj0UT5paRfLEHD4KMLpLK8qUEP4LTTXdhoe
0USYTQnNKOJDKtFY1aJ-_1aQCkACYHUDYzIz5NccnfC-y_v57H05sXTL6xH0UL43wdKrOdkAxk6Zli3DUgPW1_uKZHdboOk-7kfXgxTFeOii_iEb4X037qHZ
XdZoeWQlnLw7j0K25DcSk05XxnsVt6TCWVAYJLQFYJMgZl1wAOhoRvXx6R10QL63BwAU-BwzlxwjxuWoBvnCEndWIOiQ4byJHJbgj6kAV856UmEqcm6UjAYl
qeZlCmPJkDDlxE4ExOSttVNV5JLOAV1kgXIyYCOw1LsW5fhqFWCMA2VgUzWjVNSnhxTCGLxHCVUagCe0JqBKu5NqXoLgGJIOWYnG3wAT49v3H5ltmsaNMTqj
vFO6n9jt797OFz6cq46Y1bzbxynyMAAtTGfYnvJPaVAcEapKO4NCxsD5P8zBD2vJ40DFYUeCejva-HvqyR14cHiGSSUK4-LDnuaQiDpFVNk08lj_VhAtTanf
KTwq3IIrk_lDMEKBD25gH87oelctq1Xb2j-atYpG0zGo8GgK49rdzE7rvQIqrUFesQ6M2OW29KJdCOMLopxVjlBmNFIvnUH5Ou7IeZ6VFFhmNGgEejiNUQGq
TmVCKgP85oWl6jC--Ea9liXYkYz5lbBtWy4iHmfYu0dHcKOVAF9CMVNqp9aYzSZP5-KoYZH1qfwS3VuS-BGfY84FefEOvactKfPT3yxJCsUAp8wfByh7FdJ7
3uTxu4oIWYXGGdIoEaNGp9k2AT0eokSZZ_YYPjuKH84IeZC-x9Ec80iqYl9f7pZwF2c80YL4fwjJtXITHqvUTFu7KzuKdG9bHF-hKyI17oIgzZj67uaT4oSw
Vvs2CaMdG1dH_qOVbmA53nTLdNZqzI9gnC3_htqpEMuW1cAWxWCFClzixG3uKzSAXD0XT07ZuQoyDjfDIel2EnlrTwg5JvFM-ojTErqCKCueBzG_fei12Xhb
VVexNHJUUXtrT_fHGD-mpxsKyaRVT40pdCgdy25EvU8pngc-Fq1F4y3diIzWW1AVH79YAeF2PpcLmSQKvLG-XGyPfpBOGBDYAey1wk-KDogyy9ivfOsYFXyJ
m3Mc-aBXnmImTIg3ZIdBgGuk_7i2M8zJ6MoWMJ4LC421cqYGKnbiJ5bEPVT4uhaTgbI6FddU1pgLmGQQLNsjVTe6r7-Jai76b1LJ6ToOifmAy0a4DCYf30Pe
rZYLmSQKvLG60pIh-Z8Oe5bEPL3uBAKoy9arJcKmGBDogd-V1aVw8ASoU7A6AGqelDkFUdYVpIbL-4rHVU8yMtWSrITEXUBK9y_9mkTj9j5yuemeeVshFsOc
3IXFVUAC-iHHXUBq9iBJVEACxVBPc3xcxz72yzGdpjZWoTdF9fg_3b_uWliiD_n8N_ZVXHM-y0NtMKxuFyEN9tuJANpX2-wptF0DjF01BRpFWlii0n-WXGze
uNqMt6VXFo8LFg25zrbCRqn_
}

