sprite $image224 [236x176/16z] {
vPtHeggu3a3JDgHDal__tdkyXps3Ye66Yh9dlQh2eYbjGwhmRbBEY4YrriOhr3yWOiaPhalAYBLo3xKIbcivPvngumDKmfmke4cDnz3gLBvLE3cQSIgMh_Ei
ZTz6dSebspFkcpykEbK-YqO5FaQXnYTJCLr0zBAwQMhyGKuCvbBvqpHAy7uIDVuAQhbUayPfKtgZQUClWpAy1MpyXTHyLTEuxVccrxSjZR-Scc08kV45e27Z
AL-3XcTrrEjtsrpvKamGPhgFaG2DpwKL294gBwaGe0PIQW6EDYqoVy8LZnwcfS37h-KQ_uhK-5gkyR6sC8znfHDTOt4yyIXNFCarV3yclhBhJ0byyAgkJ57L
JTUo3ftb6fAj779DR6leMQuHsSgEgqlH8QvggqoHiwQGwkpgCxtDjGLRY6AgiwjFrGTaX2ldSCUZsCXVkzOBFau-NUm1mLX_zRl_n1vrM6wgvex120zEHOip
CJpgkgrHEd8xb23cwayNK-jpBIcKefewaXur3rXYDEVzUrt9g3ztKrD79E6OvHGvdNLlkvefmWE-HiiTHvsSUGivhjlNB7F0rHqES5SxfTgTtAvcdkjsbstT
hbatXlb4kuQwtBfIP6ZckcwVEdA_AulPyi2-Hay4E5r3xCRaklfHd3ZYohEjeg-n7PQqRvn9RPvuOgThMnuhuhgOqd625-JbZ8YS-TQsAT1VKs77TNkauvZh
mhPkMjWDV6sBKoLq1bHKko7C0LTEYxV6NLasLbrr-JOf42BpOjqKSAL5RmswBZNqXKQwNyAq1FtKXUcAA_7UXgMugwEn5W7gtBYt5yR2hrnnzsCjFkxgQz1Z
121qK7HX6dPjpXlxN7sDz1G1N605TvpXOwvS_8xjBw9Vl8EsvkREVCiPPmwxrlcYZt6TDQQDBC3AVCitDU476jtJU0S90CUvpc-29t3zkse2XzoUJMSqai93
00guEjylhklZsSgKNeXEuXmcv4e0F1X1U8ASyvNwE5igKzCV2U5XhWo9nz8oFCDhoEACvQSBpXwEQPoCF1HS7o7PjLr7UJ0udL0ynieBNDt79fsGXq7r_RLK
ambxYEgTfihTafTu4BMzlRGec_4UH6Jz6tFbxmBXjQfo1FpIGbTANYvim3SYVmajkmjF6T7r4trt-4BHsDXHlh8GrC_F3ouZAFnPyiOYHGQMinD_2d-eGGkf
jesK-HVQ5d5CerrV-SFSf9gJD-cXRcNy-HZ2nrZ9CL1maL8tCp6dktevjML-FgpgT_quedoOvJETn4xuXbGBEwPTY36FigsB_7m_2LPfuzQo6dBrar720SXF
98x0-PwWhN28v6Nynp0mrQ7tmLOdp7aUCN91QknH0-4RQ0qUXVoJKI1SRIPgFI5S7TDeMyY9c-OJxPymsU1p2r-wU5KTxctNvfY6RoYHqG-z1Lx0ji4pZKVY
tESYhfJ2UsgrPvT5Q8EYatJkTwtvm6PJ9Iy2_BvTUyP46U6Aq4LvF1LOPHhbQZDwt7M2Rl3UbPsQeUEkOZ_8GTUQ3c-5DsjEfVbXL_i7FUJQ2ZYKVJzn8Azb
0G-xYZzTzrtBheuwDRlH2cnhc2CBTD3LblIwvjsLaXi5Yp0jpaUIL-eNTrLReZ7NwgPCbrJOqX1_VrLfOLUnUoJYMlnAoHkgkhbDh2rEoVlEgAizqkywRLPA
2k-ekyI7wz-S3I8XLxL7jC_LhyXVcle5YqMUtkPk4Ebt5Nj6UbnJtbafwHSi9fwlykw2nTBjQck8w-hWPFmzZVLKdDhM1f4-LxLLegv-nl_HbekJz-qeM7HT
VLLVjWOh9TSraXC0JgLvm5Ni5HftVSpu-yScFm0UAyrzfaxL6OsxPbunzG-likDXmZROeUh8Egxn1AUwzyB-WdbqL2EojRCYVzjMzovECEegjeK6N95kJFX0
ZJyowzddWgwgpmT_DOJh0sr7rWDzLHyvtNNyOSHs8fTtLTkDNDpLUj0hkufr8fTqzQV0ZkmrNTLSr-quRjTmzUEtxejZAG7eV5TrR7GoXsN6A82UxIhcmSLy
z2JN0OSHDHS2sq8kuggs0OBOZ1_84k54Lx5D4jHG0yKPxohxFgS0nUmCsyzVeGO0PjUs5RLTu9mzsONADKrdvXydkgojs6uQt53hG2vdEbFcn5WNUgtWdL7u
YtMYSgqcNMOZoUnIkgBMYy8F5a7b6g8FANMo62gN49sRTKOjYigPeb7mSGlCvtrzppWCIzYEeIeVzVJ9i2JP0CRxoi8p3i4zaur1LUHqJHzvyG3rD6FVKcqW
6PvGSuWhIu_ZK4cdNYxR6z4RTvaPcT4RzZuQh87s2n6djkwtuHHu_3Oo_6TaCpY8_IOGNEHtgVgqtwVw-sKpxA3zKjNVEgcG13ifzWvgWHl8DaCtx2-DRhIt
J0nzajXewFalbE36ykJoi6DrqTvwKvG7LncgYj09lb4Lqi9rj2edw2Rnw8LLRcPAS8CMhcDL2K9CDegqY1IU5MVNiQgI8KZYaSrw5y_ohsiUfqfmW6bS6eHi
HkWF-kCwK9Kp7AFPSShwgW9kv64fMuJ351wJ771p1cn7gJ04r66k13DqxvhE76Xyy2skmux01KP2xtD5kD7EDVMPTC2zgPK_tBlAlFpIaqrzK8UCENRdAZ-J
YNAwgG_oWUUVDjFkNEV83dMJbk2Tf6O1qdA-a9vSBGVoUZh1-q49DYpKVt-1YmwkwHh2EQIgyOTbQwv6NJDIcU1CiCKdSFdPrVBkWKThXjF15hkF52lFhWB_
vwEYFbYrmnRpV8MOY1zoQtDoZSr1ACD7oHFR6JHCy0qKUgylJna2NCwtJGM-aOnrf30J9lXgCb8JEuOqAWckGYvKkL-PcQRPydgKCX4nipaeSoF2Kk2z_0y
}

sprite $image224 [118x88/16z] {
lPe9Tjiw34L9SSG3uFqlzyT61ZCGZcGh_RTpg-eA71uXdwHNs4fjVOmvwPivH--jbfmk4FjQlxi0a0EuwqV_KtTfOthTldpskbqtRdNOxSu2tCtvYh9DPpnf
7c-ASnq4UXlGAA-NsKrv0M2sbmekLkPbG7qxxyJYlEOTfxpRSCghzUOZPtxC9qBUyxP8PrIRpz431eKWWeWmI-pCmsePAIJKjXBHwGE4vMxJf3HZwwI0UCqK
FBGp1wDBT6WTRrcDaZmDPwmTxrkfnhVprjpd-88Shf2S8ojQBFMrvgatDK01B9yeghC6sWOAhCOst7x597YhIi_123jj1JchyxgTdpivp1bQ2UNdZaIxrcqP
a3gntDsd9yOMhYQ_x6PaLPJdwMq4UZ3BpgDWBXFQvwuLOvrKRyrGdTcT3EZBaY3iX6t1ZVPhHLl7rrk9MANxA5b6qgQtRqlAgNBtLkDHnm35Le8ervIMDG2L
aP-zPMr9koWJHLRqtL9f_5ZD-vmyXOZ0oc6SLrR1qpoKlHnh24Tu8uDLHru31M8hpR7Hm_bZzMMXxPuY48Ff2rREQNrsgCxDEQSgap6AqNQgAXHRXNxGxdOt
gooR9TSf3wS1DOGSfO7EW95za85LcNghfTGsI5JvEVtOy0AqGSUi7SXSxYpwZJ0m1kYOCL_jjfhG2l2ew66hbbONyObU5GSNMd1U0tF9eQ4Splosd4-NM1Az
YPFkH_zLxIXFYQu2scUDVhgAV9qwUMeyfR-Z7uSBz00xTIpHpqZzXHuSMUtKwVo861YqWhf6Fnq29ZhZ5H1ezjPgRNtIOfuk-ezWsRDy4dxIa4idB3s9mGew
W-nSDwlHmtVkDGj-h2EI-ZaB3_Lj2O3uzHhRsaGPOpFQxW8L71pgySjdcR0BbYRAmDB0h8XOiR4LL1TJtddBbk4U9RPQgI9XO-gYVniiGkLtWmWThbsFhP0x
Ag4LurVqguZyxf692AvT9mgjhARbm3fTzECfhOmowOETTdq4LgWO6hzS-UXVUkIDRAHykrxQlXNo0m9hbEZM8-SXohG-oegtoZC8h66Yi-faPNAFyfjjbMga
dRlDlCF-rZrATjPOgeB8ccijsoSZEYJdc1-C2KPrra1gsWiVmImR9xB2f2lAnzPnmMhIK3l-IQtyx8JwKTv21hrZzOLENSi54IG4531wn7WKkaWL_VTQPY8E
2QroqziUUXC_epgB18lvDO0OLlsbQ0bwuBq6U6UJvjHLd5Q5_yWfkdDxIccJFLGOVr6cYaVlwJKry0RYYqvHF3QK1EZROYpAlLAJcradngj5XagRLSCjOsy-
fuOPLM9KjcHiul5cSoFGWLb2uxfNlsWg9z2lU_B2yez7w31ZFBMnVKL2uaarXie_npRD_wvLv7H1-psmglh2d5BoDDMpKepUILM49gie7hySeJFjKLZFIRir
h9-7XyxxxuzGRMcVF5NFIKklZ_sMKh_TfSVRb4iAgQA7KivtoztD7zQ14rBLuLHHkV7qGEMcW7nOIqxrq8cI3YXGFHZWBCgzZyvY_-CWnhcb4rJdTLPRZtIt
veD3Y-rj_wBNHfZdp0zhaVAXrwjEeqnHZLUJw8sirdv3JfledbBHqela3bKDZesjrVHfVQpFfbx9ewHtA8FrW_sKoFNJAbfIchegPTQStgPq4cTMddsmq5SY
CX6UZJnCUOLS1qGNjVr9LPuF0VjBdcrBVqGkRH2Bx1tZQeXWzfh_rHVgWMM1cUReTNj5-1y
}

