sprite $image246 [241x173/16z] {
v9Y9SgjA34GlsunQqhp__zktGSg4nd6ms7rgovwSQgc5ysS7Mg2h_dmChG3u7EMcroNbM-j-Z7ATCINTMBbAc2FLTzRz6EMgmq_akoct8Ewit0e89ZTtl4Jt
LwupVekQQ_LHklyYzxn4ZAhtL1-X2_KlqcLzEooRvW6zw-5btO7sahxfNLrtL1VStloshXjoxYxcNClRkgxoFwcva6_plgwRV96x-bvrfUhEo9ZKLlUfgv4k
3pJ5VFcwKlDPXCcdZhcMYAv3Y7F7t8PqtOGvTMbt0LqQQ8gvkkJwakxJnbB3DERwSkkhJZmRQ2rgXXCNM1kPPcuiE78MizDETWfDCm-qQ_uFE2bBLrzYdDLV
86FCyW1SHSwsp6ricdcWrVC3TLREpQ7j78kN6mikUOmwMBazohU9wl90E_9tn0ndUUPCqRBYnZBDn5cKQud6om6hvJbW9eSFTXSjgm7G0iy1rsELgxnEl6wy
mFFeh79pccDaR_Zo0bDX7tENgxHIlAul5fZQwn3bMiBREw2G1o3VNnVsqMtbx_WA5TOpvNrNkSehRQ-ROYni8Ba5XPsgZTig7g_Xcwzg9bugRp_NuROgFRtl
MDZo4jHrZv1hYOrp6N1JdVYAvaN8t8rgpz5Mh8kUwL0IYmixLwTvjYgZT34WP1nNRWzz9SYwnHGZtwWot08XnyOPzWjTLu24WyfA8H_boxe6yeqhAocdwi1h
L2XU4YPokB2RetmBnVlIDrxOyP2xg2_72trX75Pkzy-tZB3fTmn_trghpFy5GghspRSyZrVjNsYsro_iPXjVUnslagwval4goXJovhuShu5zpLq7I7Yz6mLf
3l2bU7jyeDYwXQsEGCXnNzE9Bb58E7wZAEGjVNcSMLVDtGPSLpLcvLJjvwjFV5FsKXx2wxUN6OUylI_7Er3CoqEuDrObuxKA6qXinxH1NxVdo-kb-EYTuNjr
rS76jxgkD_JbSHwhkjipVELL7W5qg_lo-dAyI5AABn2EACiO8DTR-jgShhcFbfTno8hACW5eD_FbU0UyZ0DcuGTXPI60L6tcIyAykumRUbJ3XIqpWBihxikl
5TJCF2UbR1alRjR_jEWJjim2D1luOeAQkQcJy4-uISXO26hhbNnTGQZIyhucqbxigwRq4BAgBoil9LBO7AoNOb_6kOhwyleoYuqX__BM4pOBfsI3C5LN4_F5
G5pP0uLDymmhGmsICLwWJioDStokYm5GSo-Bwqkcb7_vIqS3FYhhk6yuPBNY_U7sNXtBZ8Ke_rHt9phEspeKWEzSsx9upc7V_stl4eFu4uMA6RS89iGwxlgL
CXSbW_xrbuStn35rxNZJgvgtJaRRtVsTWRCqSKICueL4oJk2-Tg9yhbsQG2ZdqK2JYCxrKOIRtlroWjAlRLgaiS9HOpyM85Szbe_kjDA1hdYrVbnXjonB4iJ
JiZvl2sMFf3AlKOnzyRCzGDEo1UzHdTNRpjTByzrRvPFOuwIk2VUlTETkTViQ4wDJCcSWWbx5V889SMhi2lB2O2KAy3LE2uBSsyCcJza16fUUntmYEHAlhOh
ApeKtlCISdURW2F5EnCoDG6BTXR83pvm1xgmGnN2_n-OUgr5Pnh8KwzSc3E5lNKSDW2HLun9BkpA5y7wovNcD-8dplH8VjzBTwtBiWf3hcrP5iCTMQJAOElN
8lVQce59G9F0onVNjitSyLYmiIwhUJm4ukKjWkqV1U-tCoq-XVAeLAfxiFlDfkHMinOgVat4vCAvr_eDJFq3O8LNQOVYjRtHXOhuLXKyywPWg2PssRcOI1uw
h-wD-XF436otzgjJS8oNNIwTWzsHZissTmJZhZOZ_WI926YMvBfz1gQIzfjueqplMTbCHWwcQUt_hy8SdcfRbftZdyksxRXEzXdOlUQDqMCdmJ7BfOb3xivj
tUYybnqTgZc72Rijom9UlUURprsGq4jUBCSqJPW5EHFF5WQ_nP1ztfu1SX_UPkxDvE-TQuEhiYYNmD1jOzf8mcvaLmQUBWpq26GFDMjRTJBsxkw5kQlcLNjS
YH7a1t2aTouM7XycJvEsLReFkSLJrJAxvjL-Dqp37idpzE9skkBVEAPbuA4qAnuZnlFqQWY5lfGjodR9griZ_ZT3_42UfJV6vesFUPNRkcx0ystFRa57-PuF
e2jPbCq0a3WJvrvP3DCFP1xaX1kle_PrxQwa2bDuNXvsuStxQ_NTt9NE8GVTBdW3Z45ie5oK9CpUMydTXw8aCpuLREtRJjURbxdoanN3xOfNE6PB3k8Ocs19
e5w5vH6QGJ5BiYGLctBTAyQTnq2UnRmACrqJF0AfLuwj3sGWfDVl1bvyG3QvyoXyQ3GKOGFbBg5msnEXutuJY7JNlpiGFIfyBxsAY2CTAIwHHv3QklM1IR7V
bMQyNA8fvn-oLBmVSDYzRkw5xc8_m3zM5kTtxZwUxhZjgRuTZAD3oLNmKZvPbTFZ7B7ywxeuYXAxwQb-zMthSbHlEDtn_X8bIGS7Sx0YeYj5D9R9QHLEsnPo
986HhB-rAZiizqAFSVyjfWKbSVmzvrKO9xs8hhRVaoaHoHnI3y5AtdNuRT91d97t_yUTc4U9GNxRCwjKqOs6G1Ilw-2NdnPjGOtOJfEC6tZeKRY_xRaRMrwz
jOhxkU5An2wHtH8mD4Ro6-5s8WQj6u_RulosfxDUg8YnOZCEE_3cEsndNdVz3DnAxSBnB1ATt_RKkz7pGq1ylruVVGsO7sVFmFNQbODTaZldO_EOPEQP5zuc
0yUVdtIZy7hKw25-Ea_9HDyxE83FnkPcZsJnf2i3Rt3jVi7DlEu1hjIkx6JdnvJJZitMWDfXV-yo5nPUCZ_EHomXBDMksag1bv2XusO1nf6kal7mfs7gdOFh
SnS0d01cBsW41I3zoXDAzHgFNWgQUNqDtkNQ1P8Ky1PvN3JGTcHdGjm7JSeTl1atOikj-Tn5JC3kt7kDp4ZnU3FKYEJFZNbiJeQzu_KMk3pMMksIky1GL5xG
PEvoLrO3rKtpSnqdgy0jW6iDYeSugdCz06GhyNmUmuoBihSFRQdIeBB1AyYeSq773iGFamRELtC8x3slze5RQr3Cn0UvsBs28hIEXsJ6fKUoTZtjZR3SE-UM
VyMsyJKPAFNhx0Kr2CFW2Sbi96la0IDtxWrkFPPAakTWIXAgNLbFynY8SIGlf5S5xlKa6p3txgtBNRNBRTmUeOaeVnFxEhS-XH38gcuIK6zTQGsFMeL2vhCO
kBbNhS0jJ27brnNk6bY3ZjFRWOBtEhV-9jV9-UARdqzCFsI_dbwsnF6191SM38WTzvgvjyxT8hkNOq6TFDSJoCvztmp9zKWMm9IhFznBn36UaumQB8A0t9cE
pRiboCzohx_909YSIbfhtTqrQr54iJJdtZgt7eq5Cj3Qdcr00fJLRB3IZV1HRZvTvs8AnWI6USV1VEVAnyZSYxKCgSU6Cp8q-Mm9CMWcmHYR2ydz53UIt3a6
CXZjhG29IycLYjphiM8khWTA_rLGv2xNAFKnf4u6bLtFiaTbkyuDhzMvrujNbGpRzwH9GNtVXsdw6bSVuCQvhf1bhI4fONAfN9ZvsUpcyTDO6RtaHwYuLzIv
SjViPkvZzPgm72Ra0-WNSVDXayGKLW_y0cxzLIREziM_pTK7kVdeLT-ZmDDUz7kvKRtAPB2rfjVNzZZdxX_cveD8QP5o0eLcz9hxynl-NvSv6PCc9LpaAhXV
GxvHUEBLBDYgtC-tvVfYKVSctD-OvN8NnbTaToJZiXdVnWqohv7nYhi5ztUISSLCphc_aPcF8dKpBnpcBoQ39ttt2yZRX2mDQCpVtfYPloHMIy6t8074pmNk
5vDLZBYh-h9OUWh-VcwzCQiI-4fkNh8htFLxiL6oZH4rxlV7sXDmZVljBtET-_taXW2NkT__Cb_O4Rux5llU7U7wC39gRIrmlpX-bcQ1XhNFQVyB
}

sprite $image246 [121x87/16z] {
lTg7cjmm20HWUul5373l_xZvLjOXsPpp-MxBf3dr3mYqcpBzDfU2-pnzF9S593zEpmi801-cv_lAVfg-WQiRz39_WfLW1xgycxucbW1eN_BUKIuaKcXkPkyi
UKaiA_jmlRnlbkKdLckvvYhbzfwYh-0XQsvIH6IvlcE7ZbapPv6QbvUzy2SsN6silBZikH2x3AovOIqOKbvQzWLxby6EZIRHQBbVNdD5xbWTMNEhLY6M0ZRw
-OxF2tENROpNHXUmF9BfvxSeTtcSB9OMiCbI_auVb9iRBPJo7NcQlaWkroBZP1MY314YqSzCbRhlMQF40H_Go-M9vOroini7V4pVdvggVBhkHiG1vo3eN_Jx
ddStgKf0QiBDz7VHyokcoXzvi067dEae-e_BksED6DrCvztAHMSNnzFiDGfqEDDvobBHfzmj6-M28vpbJ2_pKwusLYsEET570txzksjiR0rLprNTseFbh6iU
R79hZEKidOi-xsgmLDBryNHwoi1QzFtthd5JhLayYPoYQo2N4svgCrSNPjGUf7uVqoMAFkbgb1lLHYYd1bnQKEPVkhLYgEikfgffm5FwzmpjlkGzoiTRGzkL
UwxXuQxpZLlKUywDOqwXKYGFUAwNNoWntVzt5P4ZclKpgctBpgwqzuTD5cOtODsp01DCRm-vtoDSRswHkCRkoiDxablMoi9ST9zpsMSxq1BFu6sQPcgdERgs
Szsb66EpqbORGN9FnuEfj030F4sBwJTDwzcv9Ctzom0mts4z1lanK6VfxkEOBrf3RjvlR8zNTH62Ia1Psf0XRxMoRbPEeNCi639FS_z9Rf6jwxh0sYDkrDhl
dxUQaWD8FsoikKwJHgo7uoZJ_SkrFjhsfIh7-0WsvS9HndfRh-ccQ_fTQU4gbceGL0YWfWHuV9_a2LVpUCO0IvyHJwuvxghjSMcxHxFxehteV9yOHbYb9BWy
O5BDekIuDwArjKJw-AZc00xl4qF9EpMwYcagfiHAcm_xIvK2QEqoPHqdWWIWiMs7zmaUI839TSOYLzhTebppiXZRlN8hYlKHLo66vFla-6rPTrsdwMvQPN3z
8k1ehRf_dxkvgTkW4l-xJuvSS-it27PXxxBQTvUvlKlf1hBsc-fvjwIKx9fRXLl9cMuNnXNQ7ikD_EclSFNeFZ45Ogl7ds4kzQy0r8vaytPzrb6cSp3Zl6my
wXpZuAfNroxjxKygkXG1siYjHwbrqI9q5SQhD8_karZgpUkktwQMHRSo0QB_Dks-463-wpQYnan0K8yh7jfSJpXofMrb4gN4Ip7LsKt6tElGGEA89fMZwpPt
UIxxTfDT269b0FPbYleFtfIjhOWsrpMzJ3rvnaYGJSYZJAnYj9u0Sz7nJHRk21_D6DM8KGswjTvy-7upmPOcWSPwP_thsiWyOm7N1KKAQtsiFNPZpAmQGGQR
owrXdF5XqTJ-Yf0l5-7QU6AOXj3YEhMjYw7Uuw8PLtYSvVweoRhLyTt3bzoN-vNOj5W3JNPMpDbhTcUQjvPKRc9JYaRLATl6KnKWsBfisJtFvg8ZusODJLYF
6XX-UEgo9VPNHQj6zyMCSTIQvfwD3VVBvJAToJN6cr41udYfvjkZLcJMph5vl7VzLhDnorW5njTsQcBFvoAc6pel562QUhnhibkmftFZqE_0n7l7MPyJQtza
8_EYMththajDDsvco_pdVorNItSP-l6-derSPQ0Z15oJ-o8sQ7IQmPZRtXrPNO9zYhOzpNHFlPRDLOSzXczWyrbdckzWCnrsTjtjjMnUhiS37udxCKtocsZh
QN3SKk_9lD2I_5usw7lTha-pCMTZFiF6OKTm_V1_77pOYl8NzXy
}

