sprite $image279 [312x312/16z] {
xC610000082W_QaNgG800000000000000000002ONVjGJXq6eZ2ikkMiHDx_RQza841eXjY9dUj_NDAcVREAQ7ycduWf1VTAMo5ZdoRlnhQLYOzkJD6DQiiJ
Ao2KMJ7StTWsDirQgX41K1u3jvK7jb9xoXsEadlMLYG5o6ejrk08BI7ldhH5320tDkUuLbMqEBd7RNdgKZIuvQERa7lSLjYxbLfDseNHqxMvXHXZoYbwzrD5
He_haCd1pRkrv3F3JadwKJSLQsnGhCmjgrt5_gVMQKzRwArddNgotg_8UL9S9QjmotOM03ihkxdBWgiukaNaMU_twLHAWRRGlx936dvceUgX1OsRbrBlLZxH
llwY_D38PGR0T4W0NSIu1QaFAYUrkx-KdtY2oeCS3r-c9QYLCMptVbsiftvskDE6AajWSuH7sRwdVuBWPYqHYwAbmXJSqjsEQYDiWvkpI2rk4P5tIuY-omP9
yyDbEXNNuOPdYGimCtNpvOyRARNoqjrKkze8D-TXo6w-4X5ntvi6k8MxAJCmpiq598vkjZgRrLPXegNl2ymwrgsNECmvRgZr29SNxIQiUCNDPPhnlvlKGo2Y
k60tPS5hRfwpcwFGsKezfXrkkMxCUD7DHGupg6KYHZrLEbmE2tLJrfVT7D7qQYomUban5QAuI3SMlEuMfjrJVMAzyyoust6EVcbkolg6cyiq8PhWP7RNxjVe
s6ubOgE3-onmSDCKHT4oA-NnQp5A2t83uoqtH_csmikHV4q_aylYEyspJeKnFZq7OdSZZyNbPt5ZmVZaN8Z3V-och6-wEKhlk6rkYVvZDs6ywnRuhfl6HIGp
kidRRfxzNJUtY7W-DtxVpN7uVzrKttUJzB-wzTvs4o1-syq77rxjfztOhaBBngTVtC9ttQ9XR3e4LOi_x2RrAW2bZi_SMJg56x90qT9-63uTpT2_DLF0UgBW
p989wUVTofS0M1dTbPl_lXifH9aX8gpA02Hd4L4LLJMOYWoEIX1HeTznkrwdDhvBjwXmttSRdUh-q2MucUXHK7MKMqZH7UByVRSKuek5j0ItevPmQuHROcRo
Uo9s4xYnlfZ4HRY9zS0zVUhckPUzQmMQmatEIKQvfIMuWOUhyD1JjyH3Ajwvc2Tnmv1AYnNFqqMu6SCCu7ruvaO7DuXpEKxdfiBCmdnw4gEg_LoicwZXYHls
NRZ1E_RJkO6O5U31IR88E6SI4bmbot1JCRmnRv30Ra8tLVHqk8ZsYwYABiNjAcEStAmyxDpDE4tZnYoaB4nqfDCRuSZxAswt4Zrpgm-xT0lJk4dkR4IaV70Z
zpNgNbd0aNx1ZUrMogFNgUd9JTbFv4OZt4GXb44Xwy-x4Mvbh9zkYiV9oOrrodLA8gAY-pXzJG1L5WZ9Sjn4td8pciID-CKeBiJDtd8JuqdSV3ZcmwaOlkO_
-t4tARUoyySXvN4ukTb4ynP2waxKhWDYR8MK-myf-TW5VOZnLztghOgzjvzQciWjnx27Yh6xENzmYq8XCp7va7xRxNlpTkdcft5hJAtKpy4jTiP-ySCH5Z5l
nQvxx_c2YPl4BLx_7mkFI-jsesdSGgINYdktpItRI_7AtNHEjxhRxQhTZ9RZPfzkzimj7zqIycnkvUDZLskfotPx_delzfs_tfkTfTdS6XlAhje01s2PRc-y
lv2S2nRcSglTJM2o6zWEBTDjW1DxwkR2uVsiP6ukjzt7HmMdrDrmtc-wtSzitFlr8NZldEYCReLZ295sXej-Rp_zRdR0SSveFhUIOolnxemCTkQsriznUHSj
pkPM2y0Ce9pOJj6AtO8JSpEw5ODsBTo0upMx1QFvt0g4Syg9jDe5s_hTnFnyRgR2AH7fRlV7tBAncysji2chPi77hjWPslhTpFnyRXPhKK2aFsym-qDkRDdD
vvPz22oSfJznA33xAsx9nCtebdpYBCIgKgioY-9Fk2L3cCyDcb8nWOegYJ0J4Q_VRM3pyxcfS2GKwswIcLcufUjpisC7DpRrRZutKSg2NJ5LS6O6CnDZTMvs
5dh6pitdLbGIQTrLG9LRr4yHhCpDpklVQd2pke4Jbre7Dn9k2VEwtNhTOqutAvAeD3Y3YcWd4rRXTRi1ChDRGKuPpQq8Y8MPbKLvtMwOtysKKfBkffoZoD5D
L-Q67t2ZkjjzL1ig1gBcLWoIaxHK1C9wUdzGLlOun32J6t-qZcvT3hMvQQOmkAaQ4sDjRkVDxzQ3rOv7AOi8L04c-dIhzzmsDzHg0AUaAgOenaJo9-RDJ-b6
vsxOprjLbPXKKM0LJCHOlLlFJ-osgtOAjU-dcXbQ6rM5CBFz2RSmarknbjPTAKL5pKffKYhCT-PjSokzBZUurL8hhBJgnwwSDeQkkBcT_tyhGuTzeJlMGwM8
2CkZUTlSoZ1mjKzWAGPXean4JzRfvbQjrTsgIiejwZ6pw5stpQq7oJcb65BqUpKUKWoLUdJRtBAg25EF8J76qCj8cVU9AA0fjb8dNQ6R-kdT8b5kfLPkAdvV
I35qffmpYqYEdwrptaBmKxjrj5vZoftD3VdWtQ6cEBHcD-TyQFaftL9l80d-vEPFRXtkI1VMwZOK9dJhXQ5kTJE_B_JsRfjRS2_bPtNRt3QtpMrpys-vRMuk
hDDjSzlSl7Sz_vhRvXPIY355IZ7-VJSN9dCRdea6tnlljhczsihTN5YNs-OMr-tcmYHkea-3NfIws-R6YIYptYrdKMKYObBW3xXvFucRv6w2UsaC39NZ-mp0
wjrScC8jvLUBcviB_4PnSvkWzRdvpUrnqj9hD-StjtkfAi0jkU4MxhhvHII_voRCRxWjfOMw-StjGNVTWjlS7gQzpUszbk6skQdq0sU7od_X5jott2JhyP3Z
eRZCMjVt7lF_wgPoEj0FLS5eDn6CQ4slzqwQwjLztUlqnBRj2_Oqd7py6swRM_3kJlHUiES9lPLRZ5jdcxXId_Ucm0BSrFLyS5CNweXaeMxFqx3_MCBafJeY
NUsymSqKrVEA6M2jKi-ppUrhUew6ioxeDhUlsINQ7Jc_kNtfhjhGKIwkTLyGDqzXpuRU0xYypTjbyH5RppQtMwKzspCusjmkeu7jAHnlRfTnPtiEnzk-S9aK
FC-gRFDscM9CfflRPJek-IDkFkOKUodlEtoJZlUXdFjbKKN_gsunQnvY7Vh7pNceDnB2G3WWK75v_yUziXTs1B8vDzBcAojhWPZ_Mmrocculs7YxxYy5Ozej
wswfrVVq9aOIgyKnyKketQYIF_DSI2HwVSFWnMvJrUzNPanK_yzDn_LkLANFVDvoCPM_qhQPJQRRHKosgxOqXeWfRhaP5vSP7z5D_OFAztAJJ-L6RDzKIkdp
k2MYyWBLbuZlKycVnuqAVrlzCxYKeVHXvmB9RjNSsKnL7A7z235j2RcMi7uDxaP0jabnddER1_V35-ckR2OKKEMyZflvhqDjPsshqdQ6X8OHFKWT4ppXnjL9
FJTst92MkCJE_9B1KKvfVPrI1PrRdoe5wfYOpRsTco0TUQ4bYfr8AhKoMk9Lt3AfVR3Kwv6fk1gFtAZ-qOQrBEL6nQGrPdkdPlmUw1vWp2P3onS3wODn4WBq
Z7YX2F66f7iRuXQaD69Z4LLXW5lXRubOcqEZw52EGs1NVKn2e7wzEBl9rsb5o5kUvmQduqUjB8PDggpZbabXADVWW18oD-5wZ1lo0wzWfp8QdFRxv6LrIjLs
eq64Yhivi5cW8H1kydKgGmWZ2zS6LpotFA98YxXb4XZqLrHZ6mokRXeCheuewY9kLAnh23XO7IfKzvJ4L0sfCD7SA1aRNxm9TVbObtE3as182_mDfm9y65ON
zZfBnOaQHasveTi5GkHZUxZTY0PdOQTf2RTCsep6zUVpfon2mYYPeBo9cu2RE7z3W4Ix2e5Dt2ajgLEgzgKL6iazWMD9AK-urHNSCebma3_HyEwGcjwCAKJ-
k8Qi2QUu4r_-S2ie22iquIOBkE5Ky69VOQ5k9oT0gCtPJSYQqAH1OyCBeqFnyyuj7GCBNU1lYLXgaCxt35eIRSl2pNkuMU1srTVGKtk3IwVu32tu_XlHz7Dt
ZDHSD1yshsklo0X2IKS3mEa1Wpi5S2TwUPqcgX5M21zKNFWnoUWXWWOk6jpXV1f_n_ErtC9ta1XL8w47VK1X2LGzZxr6Yn5m2mPkrVa4EuDB_lV8ZiU6uVJd
LNevDoe6LUo94ShptEHMRl4yulZ4evZTpnm5XQhdGVBoSo6H60G3yQ52yeWC7-0H_itwPXjdzPwKDl06gGeHs9mwRFhwdyiGLVxwgfTKIg5UW9FusD2T5FcN
SKlyavJ6VpbQAASrFmTa_K5wkqMvF2jgVsHw_06YjmzNoh_RWmC200000a3-h_Q3Qa2k0G00000000000000000000000000K
}

sprite $image279 [156x156/16z] {
xPc7agiw38Pna_JB9kVzt_PQE0aiIsuW2QVwcn43IljMXMt3cawdq-bqEfrEfzFfT3eT5uBxJSsIGf5-Hpil40MKVqCvLYbb19I6tusWq77G0eK_QsYyzoyr
9Iamvg9GZQSCi-HSIiw8hxWfj6Je6MwESwbYQdhb-Fi7ixBuI4-JvWMQYv4djHhY3ky2X5a-iGifZqkQq7oLYuQZTOTKyFuz96HTOeLRKSh1ldgMIlhCoYye
tzGabdAiSe59c3xYjW2ITGs6U71TYV9OcDndtKHqmsqOuf721KATLANuKJU8RhiDoHteA4O373uvRmB5sanbgFYTHV09kOoDaf7yctjw1yWRODXTECzQPiPA
1hcFk8dc3RGzRT4WUeG08bWXz93zFTsUDfN1S7DJNKtdRNI3_FYvRlSkcDlsBXWBDoZeVQ3OxoRuFxVWbcx3-uYvxUuf7lNKeFZCpJtaLRTORgYMBNIOK7hc
HbWDcWKW8lIgstYNo6MBF4n8Ukeca0a8rm1gA4IO-MMtt9ZgbWNvAoMx5Att_fbR98FfE_7rkjtSKDM8jCnUHaxCv5Tx-lW7tesDmkjk-GQoCZFAbtjGoSm4
k7rkmgsHAYBuW5kv0MrkAvXPLFnpDn6OaRb1AW0KHdnxJujYoosJkS4zTOj2mYIgAeiR54jwsIqeRgWeJnvB5EO6XETrOsPxhWZ7cA91CkLUTiip2dFBNr4o
txp3pGSVWpT2z366YdT6U7_UIjk5iImPsxnbjyij-8amdSTwChqWlB-dPRsdBTdwF3nt2t6Ry4RT7hgLIdFBiiCjpYySIvw9RxiPoanOk5RQdX8TSDFoOxoK
3xcLEygSv-lc5fYTF-AMBnVXgjXup-qhu-eo3yuDAHroan3qwlPEtO8-OV8GVyIjgA29JQJJtCIAAyEXNP2Kj9plDdaW775JWV1uoSRfRip30RV2dfdpgFW9
FILnHzmqSGQOcLZFSfk_nmx34JT9EjghXCzpAqQLYrNdW5kHD5OtOHR1oMuo77MBEcOcCSxkwMwtTFbHSaNog8b403RNoubxkj_jHtFBfLGt88FqTtFJF2fn
jGBXDtGhDSQBiln6RcCnk_BZKh82mc8Nvxd9eRfLCWII4bLOi-Opw-RskWLXIecZSuEFiSgnS0WnXXFTAllSedc4-kphIvnhlzUSvpRvx77pMtzignaVVmEt
OPi_sAsxUUTg_6otmUrpy-RchhHNEVTRkAq8DMF9izq6j-jlN885p6YPN-yMcOXb1fI4sJA_tis7H_Wpt02e33T-mV-C7W41y-pcbcwKDg07R3yPxxafytRT
FiBRFTsUDyKQdO5YpUOhJjg5xq3kw9My2E3JTLl-ttbuuZPpebjUWMzkkWkpjFWVZhhbiaARseBm4Czb_Ng4nmpl_qnkPZlXoxX2XzS9JrfQ3hsvZfMIyzI0
qIZlkpsME-HMpAnDVeriRlvpRcioXltuCbQpnP9Nr_31dfOL-SYRZRcPBUJ2RrAtM7JD67-JUOkADVf1j_p8BQGG8ZEd42bQn6J1N8zaaInIJGYbL3Dfkahs
5BQCHRqY_avwx_lfG48izPg9GCGrH6geIZj3Uu1WcIIII2WHQcZDf2GMN3Fw7N5lxO8dPffWvXRpoUk8iDG8E-TjUnUiYTIwL8DQ45iyIHYtlWhRkHtf7bJJ
qTruOHSSSsiBrx1E9LY2rudf8jKBcXyr03KHjKjHc6ODt5zwTmh1kySztVoU5OIP8So2nOb0AfXZwqIu8cX9J8VRUw1rbI6-sRX8p1IExS9KVj2r4A0OhoSf
ygrMmYcsed7DOl6mNO8jOHUCgQgqhFjLXtKYxTg5QzqyImLe8ItsdM1LjtPabdiJKaoWjd1wnH-OjyZjwxNgjChSoWYwf-8jPS-InRCgrxe9xkUy73Xf0nTl
3cc_csFXUKuM0zSEm3qbwnJFTRkbvxenBEQ1IraR_6WNllSqSBeotLx53f14f9o8OOT5VdbWC1a2Wn9Xuiiwrs34BswoVnT8Y2T8iFxaTX3mTpTUkzbrWvbl
TPw6GSbaE4CRRkyzn8i2AlOHolK8q0EOpQUP4gGrVUxetEVKk0xUxGuNnwn6ALStw09ipLk4qMQPh1lov6yA36eVVDqC0ZX6kYq9jNLTtW25lTdGQ5p6wxpb
fptrT1hLCzqO34yYShlvUdu2sSqQfvFYy2BkT8QNwNGwdKwdq-bqEfrEfzFfT3gTpdy
}

