sprite $image266 [188x137/16z] {
rPdhcgGg34K510a9x_-wvzXNQzXVZQcKPjZ_vjghSIMRifSB4zCoQsfh5AOatzf7wdpacTftobpaaTeXjCub-cCeJYCwI9r4T9nj3j5nACyXEWwbEKJ7eJ27
w3Xr4j5noXoYuz0wX-Wu5ESG7QTE8ZhEDedeE7aEqN4epI4w3eKvHCUfauYEKsOH7NVL7ABZK9n3T9pg9dgXPixc8Zgb9L2p9zylUWtByXvuIfUAZbUS0jwd
g-hpxHmSkaeXEaO7yAQKQqN7NoUGGrUfHSTxBT6_rrNrd9j5_hcksauk1UhirhJwgyl3Wsq_fqwrlIVvkgjBnkWKbjpyXxQUVgPqG3TFBTRIBZesPfF31M5F
g9xQPpelOpwYVwMuVQwAf7YOKS3l6gItlRYlgXtGk7qbNVG9XU95xz6BWAURsfEicQuPsamw1mCo9addfsEUDlNGcaJ7IsO3nWJkqa2EVp4KqWwjKdGSEXmx
CgR-eDT4c7tFMj_NLTiBRLt0iQTVz01M_U5lnaA6eLM93lO9UXOi3-i-ut_-sk5NwrkNtw6CF3wBrFbnU1CXziFXDqqslUXOzmA-d_fzx3zwXWhO3mbhrNML
NdGqbU0qPFoj2DcFYHe6Ia1qzQY2tuio8Wxd3X8q71HUBE_3gWA_j_8mLGNuZg8QMY2wYZq2dZ8-7M4REqvcnR63JGwQTXktkBGhs8cvAUcFd6lxpZZu4Lo7
tyWkGipChpg3sSl0djxEJY9VxCpq4Zjs9eE9VZCxou5T9quPPXLzF-MoFIDoOD_pKYi7jDz7ZPRjZUmY0plpAtS20htwjNRv84q-mnxAAT41kq9x1ZRG0Cg4
qHjcJxNtSw9ZTZx93jOVnq4a-VPexNzZ3uNx_pcX2s3NqHSW_3Oy39RuXTu5iX-FV8yeo0_iId70BKl67o88XqzqnkT-FF8khD05i9_TbuAaoSjGMJly-dMS
c7sj21oJOtQjE5B03seOV9GHBi24T3Xo08vrmUnwUcQm_gGUHFY1ttt1x2kT12UHf-nAxIMF1yzz1V0ewUF80JWAiQZPMN_m4i_1fvK0k48NmAwWxncj6d0D
G640hY07x2fnXC47QUvqwfK905U8ZjaL-v9x7LVYFfdXqoE0fmwBWbqZZlG4RZNIPV_jVMcRuKKKx2fwxepabYuv0fyDv2PsB8vqMj2ydhYPA4HNiUDWQpO8
RqTdCR23m4sNiJPiraNFhjoNl0ycwAZBoVNi3AnvW4_Kh24MEplES_XePnTDY7MX0NuTbho1tC2ktvVIU_dwy2Tit8lQK6Dj_ZpvZps_IkzY4rsTRIcipf_m
d3RhKXTr-6FIAgj3Z_1x-5PooJyBmdJqExomINIzBhz9pNBqtELMqMbvJ368Sw_eBIv3AXlsvPqZYXB9UlJNYru6QeFsbfkkEdLvbdAREA8E1G1irFuUNHYC
g8Fsn2zt4OvrsolohX75oQpDfQ8lkcoi3LqaUWkBDk42xOdDNMJGthOlpIFgfhsvYxoq9_k8EcbFREwYcxH_XowhWTYcFLtGHGxQatb4xzU-4HHTtqKksk_m
vYvoqzxSHOxQwrzTW3XfR-iYN-qjhowyjJTqaRlsXYvorzxGHUxQ6xh8NNj35xbhR-WYT-qDNNHzudFj3LtahhsXYzorLuoeKq9Li2kwo5TxGnUvQs_e8dVj
3QyktBKtT96xzeOHTTVUq4NksXj6r5rxGnUvQsyOKNVjSHVDeJqSqKcq1rqqZVOYwp9fyiLTz1y
}

sprite $image266 [94x69/16z] {
jPS7Zkim34JZxXbI__wt_Ots0572TRZm3ahwa_944lQZad6R7Z-LOIMv3Zy3Nq22vFAuFzCUR92ORsQFMx0P_7swMNYmnTzkqp_ZW2k0ZlSMuLsa_oxXoctw
9JpZR-EDmljq-il2h_5OlYFb48uEVul-XKJ0zs6cSej-2GVNVo-Pfgv_3E41ZoEuncEfLY6unNl9vklTjO0GV8_tLYU8Q_v-eNzwBi7uzkO0zs7XDNyRheL7
m52v6E9VpA-ZJD4xo_1XsoEMjFzb-LO_4lsvy7xh8CX9bICYvYtXxzC7SnQnNmEZBWSt423qyR0WU4btfNDMrRWJnpfmaFDZOmJ_2TFsoeUwgnVUYncrpkY8
znQSUu-ThSYhFv-pKnma4CzME-j_8qGFmiv4Vo-yA_Q58CUJEHyByfaUNtkdtzwovNMLzftdCfRG-y1eARwZRrhmqxsRszyaQYQXJcYyDOBNT83Ucbd2XoH3
vwiYxUbJVwp_sTxi2Bke3ZNa1n0s_ODtteU5pT1BQUuk-Xlzq4OvdF_UniVkwjLe9szkRzX1LtguJGSJjfvjQzmTPqt5jfiHU94YUi87SGWXOw5X9oW76CVT
_w4xjWLRz8GFLxVA3G6AuovqB-MLtbSFZ6VZmspGSL81-fTYYvvk7oxVS9zVAkDj5MPqXT3NJz-4_NBnb5nAJfSUc8-wwYDHOOkUy-617o_OajBJFU4B_rVE
OaoI21Tzfd-rVNXRzsOLuM8tJezXjQ_uiDQ8d8s4xSsNuoB9KlqwpgeKtmPDK7ZE1tAs9Uo6yVbk8E5_L_XpSls5AWosBHtxGZygmjUEUwcVnATIzg63VgOV
tn7-iNxXaGkVFxWd-xfvQGNX5VqruNNzAHjZwJw-06-DYV2YVc_9k2fdfb_JDQxgMSnpUYwyhb_qGlTKzOkUZwkw_eukuOyxifftz4BtLFHxAmel3GTloRYw
HR-tP5pTehyYlAxVAzrJrryK_WS
}

