sprite $image41 [220x160/16z] {
tPbPWkie34Lj30OaEUn_j_tc597ZI-6eWtE-tb133bo1WFB_GVa7vIF9V_XOiv_GXvdLfF8nK5PyqAHfw5FCFjEEyW7bogGCk70SCNHXCmnzHg75TLtJzOEP
5M6UVhF4IzjbHPodE_wwmQIiI3_LZkHokkoE5gQQlCD5rV8orQGBhfXP0TmkOqVKuLPpmStQ0xV1fuvobvk6BcE6tGRV3suP0DmKenSQTXlVZdAF6sPyitwt
d8OzM6CtpFYJrk-MQRWb1Bl5t4eQDexO3UE7dJJiXXdN3BjXXZ8BFZMxnMKTPL6vPSZwymeXGBVx_xan6fKCYUwtm1oXs_ssmR_VBaFI5uybLGQLcxh-2kyD
9cM0il17Rga-Zi-uxD8R2osvwO5vVUhcfqUM3BcPnX7NMesBksxhhDLIRk1ThIE9nBtFhDnsnc1Ecr1kW6pYY66HC2cS-hiY2Z0p2cR-1iH2o_HTF0jJRiVC
30UpMbCmIrQJ1Z4hD1pCTMuscnCmCoexdxiW5lQDQgi8vowIyQIbzLamjwQoMtW3XMOpTMs75nUVbnqAfii7wtvQ0hQpQx3cepsNM6GzBBJ3TT-tjM7vt8w6
Uv3GKtRXQDrVvtjN0qYlx_UNbZwNHBBxzGLkyJu4xnVtPx9fOsfftNnwQJ3Jj_lzuxABcMNxXp35a4G879CCJZygZi0D3Z3B9i9CVs0M-IduZHyzfnVPvHQe
AYHKTgJ_1HIQoVdW6usLUkc5wnecBVrj2_M-MEFz2uynPYyBqjv5qxb2m_kNpuZ6EEhLjD-kfstSoEiGXTn3TB1jwIqxoZsGRDbfkwWBANWt_y3v446XWRO5
SieCNoEanmsh-efPxnO1jYtTmSnxuxoquNrOffh8zGe1YpBkn94vTvCE9crrqmcSqEEz7jYEQIUHyzJ8x7ny4aom57UGgi6QfmdAKPxEuTAUNTQiqpa8ZPE-
QELvEecMyvGroyanfFm5y6bKA7jnIeEOphZX2KdJK-APCj0eDM7UiJivWZrkhvutacrZrdQSfZFC-GlachuikvTE6x5iVzoOg7RcW6kxRKBewJYjk2pRcJFN
9yQVy1yUv3QX5DTM_C76_EmwoClBbkPvII9KnR5oUxHZaQqH3eSheCHfXo37c-2IkHMHJPY-zEzRxQQ3cQcDlPD9g4D0NdzoWMtPoj884rM5fjoqNV_9XDGL
y-hc-_y74ddy4dh98Pwa2bGDaEiycP38nhyBE6M-HmYz_RZOOQRS-knyyyc4-6zOdbqHF3d4ftOpLWk1WiZg2e1-SFps4rhlpZGictRJK6-XeHifd2bGTZYE
sWtRuJZEAp3hlZjpiTqCks6xw7fVhF7T6Rv_qGqMTcilksg0EswaOWXFbmHMVGw1GWDk6e9lscrNltvoIrXZohz9CNYd2adTdQbXmt7KRjWE3V0gZIyNxMy_
MvpLTedNVUpMRYUItN6XHN2UyC-VN8FQBa6XAHX0o8v4gBrjQRw49XRo2mcZE6At_c225slC_3IOFm1coAtR3hSj0FJsGmmAxRJR-VC1ncS0MFUHMxyTVh76
XBv-7xkzEfW1k-3z0CSHkvstm-l-aXv3kFj5JMQo6RWnKVUBDJ-wxPvdV6ySiHk6Uk8OH3YhWnxldcSYDBDoqtPu5V6qCQdhPRV_vBgYGZDrmoqqBPM32EMi
tVQUN3qBWK8pTiDjM9hLlP1oqzS8IqODbe6RXl3nicvqjTizPxIeOn8mitJ3TXlvgMfqjLjzUxSAwFVDtThjPADw7cRjTYzHuOq9D5WTb7uvOCSvjxbbOX37
FaefT6RgCDWDnBjVxIVS3Tcw4SiPivDsH8PkTChCsWwxsPiPb1rmiomqXKNPzRkzej2CWedTZE9uAmg3O08tapXAKHZO8RVPPDq7s9HTknk9mPmPb1rmCrZt
RUrQtOmBpJwOsCs-qEpj2BgHWPb9sU4zmDOCS-ktGtTxmI2ERmick-fwaWqQhBVPiQptObk5R1ii-s1I9RT92ejpIqWYRB3kls7gT549aq6XlTkEY9c835V7
D-y70vcTjpCyoOmJJ8DrVq0xCZ0ReEn6YQD6k1E3TN-yO9A1sH1smvhXDWop6QWDKdOoW1d6m0sOZMudtMRZsyaeQXWoTojlnDQjl1b3j_9-ZDpA48Y1Mnc6
LxkLeNYfMnaCUfbR6P3Nk9L1UO5R6PTpRbB6veHR6PvUjt89kjpALVYsMxaGyYstSZ7QtSe5QNGhboGrk9NBWjpAfJbqArVdgLlv06wxRkL3q6xbWtXmAn_5
xOjR-JZ-kfMFvAVRhVn__0S
}

