sprite $image65 [130x93/16z] {
nPXHSYih34Gba0IeoTl_Sb-6OK9YgkBhOEFpDNoXAautsFH7GavCRuIjk1Ubjo75IodkET9RYDczDDnJeEs4rFVlCnXl5a2Bbnzira5kzz-iG-W23FRgm3Rl
FuvYWmut0impoAu4ThRgC18usAX3h-3oJtXHtf70pJhC0kpLWTCZ-u-YtfN0mOkAMhANF-9PDYHm8PaB5RnDXrc0RJhSJ-2EPCu2xDLXVWHjra6Mzbylwbc0
lJhC2Toimve0w_Tsd2fuhmvp0lVei2x0UZBN4xXUr7C2T-kmAi1wCYkc2JRhu0ae4pjr08SCBnFxaWacYkKTCwGm9Y1IVviEVGBYz-WWVOB6stJ0w6hnj-XG
a4OuRViCZWh0bJfHyruTK3yg743fHo5PTMColNvyV5GFoG7a5ixePceEtxJ_GKM8bXs07TMaWYoQDipW-3Yfu5J4ogc3G5LpaQx3QmKO4qYsf6s68gAkcYsz
M0U_zZyzC5CtqwP32fQIgkV0oU4lFO1E1IjK1KaiunCBvgeMIJKxNjC0FmOenIKeLBLaZRdf40mfKCd7JFwg0-W08FKSs_4NevxCA1P9Kyg77lx2_UlHI4IK
aDXoKgDuwH2PigghFJMPZflzZmEf_LzxPODHHDBM3cvinPeUpqicwhn_du0ekiUW5CmyzNOGDaZJ8sJu2mJewqgTGmSILqifQzSXdkr090N-P07mzKaNVEgG
nLn7EnmsZcVSCmKO4mn2SULKJ1KfXEB0kRu6n3C56D1tn8jmWgX5abxKGUaaPlYJ4lZ5vsUXdnXo47EBbDAb0pKui3Xy_G1-x0-XMpZ1WkL8LimqDnsuZn1O
WMSUG3MQQJf836IIODhlxJR1CK98yFK4TZBJpAL3fEoYXYIfz6SSVn9u_C1Q5S0Z_O8TRP1TKif9j3_Z-A2_wXSIs0LG-XtEhaSRI2hQaWWO4tSZ35WK8D5z
Od499QjekpcQ3amy_S1wM83FpnpeFbs7K8hsHTUXCtHuE853WFiOKX3j2psBkdt_LjH-vm2K7Y4SEj1L1wSEtwl3xmWm9p0nFKXqbpvDuDXq63Lc5VvO1GVw
0ueIlXhfHeTS0L-euFkCUvlu80QsNjGDmIVk2nNyppf0pn52u3EP_Svs7FX21J-a0uzYxZgmuyIztalWCdeLSrlqUzjmKH-fu3KTHZ43ZZ71RnNCjCvunl5m
uplrWGIk87vJpDC4am12JyRmJUeCzp710mbSWlCePdPSCzJd9l3-lTq_jLu-rbc04kbL31q26WxS9l2_gO9VeSDe9FS50PPqYEZyxH6qhaDsN4mLl0L5nKMT
AdWFXdfx2ebf9wERwwZWtSHIsmJZ4RGVzTO58u7xOGEc2jvCA7zFuFy
}

