sprite $image14 [295x208/16z] {
xDY7bTWm30HH0gGG-Y_OESkwjuwdCBy7xXjmlBgjmyRBCAlVMUC5yEoFQeu3iEYlqiVFO5L_vsYY6ANlrHhVWMNlC57x23YIDlOOfRrjl0EltZcUA2BWMFbu
jjMQD290ieY0OyH1zAzA9m8aOKI0eXQZ9Ab914ZIY019FEPxyXWJPT5_IqqYG9B6A4csPqO04xNrlr7EA4d2Y0398W8aDNbladGYG19swmWW3gB_hvgCqZtl
5wz-5N6t262YLh-cyhj401FbsIUm4G6IMaI099q8a8Gzz3Av_XVBrcTKamYGf5yf0fWeYpwtMaI0f2QZ94aZ0YH114XgCKgISY90aaO4dEv-MNrTDOa0IJeH
S9Bx9VeOSQ1701FbrJUIpYX9WWYGrFh_4S14UVPjfJtwCj5jH82a5gCaAIS2_ldzilM3BDwRf2OH84ad0YHXH82Y5gCagKa4IDAK2C1RTkpOjg8e1A9W_kRs
Nwz3Hrzi0OSIHcW1xXTBH5D4yOLqtoyCK4MKd9ON2mDK4SK0rVtYt-atLFSBQgZxnS80rVt205L4MPoAA0QebWC6g2AA0QhxnUBKYuK1geXYWEh5mW1LH5cS
Aawewdkk2khpJgQSl7Sn1VNNpfajjmxpC1YY5bAanFT_st-HaYgDFQUBJ-VKRd7NsszC30YnqJPaxvJ-L4XlOle5PUt3cAJgJuKqCRLkxr16KlrvyxOmkNkp
DwMznMBw0o4jJDxV1DNS6qXKVzgyBKpr7T-JDlSCnAe_x5DQcFWTcCJS6G2owkKXxMEITs2grhkK781GJ2-zcUnZylO-4o-bcMW6BcnH4z8-9iJ-DYO6WXGI
hH50gdhnUTjYYYe-0rGpi-xTTYH204HIDQ5bKPU7j32LnDvi438ptn_1ZCm1iNNEQWmWiEh5vsrfmfb3bqhlPhwVerWab09mRxcefcbHruSqnJP03KoQTM0Q
wfjqwGRYX51TesWb04drwlCs1PA7jUuUodqxURNFUCc4Q2wvcWG0HVLw8M0h0AdQezntGL5phm2GIq3klMIr0Y28wfNdRGepM3zXwdqpUMJT2m0Wb0omjsGI
0O2gNddU5YO4Ves9RFCzLMi9KzEYL6hMVCEibuKqXPkeliBKlBVNc2JYGOa98PVQCLLCBpflKtXHqbVUnD9VOnB2qhIeKDS79ggNX3I51-M5gKbvmbIASS3K
igW7nQfNdBSjfcbHmxqrjITlwkvM2Xv5Qn1FPr5gxTEO0AgJIA_BmXUdJ9pmR54F2aNrOlEsZsbQLEkFoMakBjNSUGC6fM189DDfB4hRHuMjYfcrXUd6IQox
6e5o2Qy7DG4Wwr4b3CnwDKZxcER-qbymyMsLQPoye30zUxSGm8bDBP_0egmTnBGKwstosXmtCvCSG0g8S8fF5fKv0CMRgQPLiPm0qa5CStzf_h0HCu3Y334L
ZZiMHUwzwMmEgEePvkqu9e1tsii2Y9dL2kIdSC0fLFTkQhmiwWIGZc82oUjQhd70n6GLgH3dvt0GpSVaPNp7YiNQbs1wh5XcTLSo47LW8k4Kd-Db2QNFoKlV
hcBHTaJuix9kuYLDJARCSHClSv1XKIOqzvTBG6gADnHuSRh5IyfS9onEA5kBqj5J5O0oikhfDfEj4juMrHTCvLuD26Ykmy3E_XARjyeixWQOwMbDQQhWFLeL
Itoe1aWdfX0GDnKBMEDCyW8pCptnlDM0TwkOCJsELWJgmDJRFLuk1Sv0ibpT6snoEYaaY_Y8Wl1cjAgK0jR9CMygbfgbtp5brKlFsnBjL0Enm1G0XHsBobAR
qiGqAvQpGH9yHcbdjA0TW7V4jDbVH3A0-HQg8D6JcLB49yNFeqKOOW6OurF5CZ-mM-HI8AcU9mHOmkT5UzK0q0smocMlOfddhUvXLYoNDAMjubvxgGQOcN3Q
ShmV94RSzfSJp9i47DRkQCtXoWMqB2gQAs2tnYfnJRDYkL88sDV-onFJmfGutlQNikAbQG5xMrSittdUClwMY3VL0AZUlgPogrYqLdUVc0Y8JUzTL54zHGWu
hcqrW6IQ2yWupef5HFeTKou1QjvkTJc9wVSC0OI_hCoRQW1KG6QMSaJYLAMvlCJBd6BtVg_BOzLlQ4e9VrzXsruY3amI8u2YLkaMBoiFg-TPbwyJrpE6WCFx
Iou1o3emCGqme5kyh8DZq8Uwl9YUCWGStrzA1cgL6ACpWCX4TkD4CsJ5jkfo4jLl0aaZlbBRzZ9I236YHeJgakKUB_a-gFUwFFpDA_p3zUHNAspRIn15vzIw
EySPBxl7LR6Ckjnw0GAowZ-7n3YWGnKBQbApxfriIEFZe99wQou18L5WrLFKayULUUVweewQTsBApnoJgdi3Gc6Gw3b2m77njXf8PithnBIp1x8t1QnMJaYg
Pmq1nokMOfemCN7Px85nW3FJ53DGLCyR0evNB22RjosojmVEy4dh2ly4zUHnRQylW9VS5FRsGF0DqoSg5lqc8U1unPAPw7wGMFP2LWA9KGcnO5OifpEbunLB
R6xb5Y-xPr44sja34ubvrxoky4yK0evNB6LOKhIfZEeWJd7d2f-hPz6wJbnFK4_-DOkokk9b0b04gC8nx-o1pf9l2t6iUe9wykzLB5LMl2G0we1PPQRj7bXZ
xoMl4zTJr9F7HKA8rPhpFLu28TyAyuozAtnnIwoQrXN-AUh9unLBqXf0ivQJaX-UNpZjXAoWNjF6ehxuZVBVgsHWrN924W6Uc99mt5pXPyJcdDU9wtb2mF6A
PTLoOxJom9IdHMsVshctKbINHPrWCpcgrLxAIxmCEQM2R6OYkq_jufggrR2ky4zGJnvMbdijHo_xInwOh03Oky9NpzqBabQGwhL2m5jN-4eF5GlIQ0q0sdrg
pwMvQtStg9cUefuyBXAhz7gq1gUAw6N_gLszZKulwK1yF0ISGacUHYk7B5e1JRl_v5boAlEPOM0wSmWuNh5KK4y0ujvJUz3np70SKy5fjFz4712yO4mUnSt-
8cOrO68wTmWuViKoL2D2APlzHHAmC9qw11n_8WR8Cv3YRiLo35F2HkUrgD0p89RJNiLYG-SF0SSj2W0WPfKAKF9JrFmifXfmQf7ilR_8V3dWJ9nU6cAtpmwT
HPnS-rVuWGUc97oxmYTJTy-VmrHmVkt_WmlLIhCvc1KBpP_L-WmcmLMqRIy30RCvg4mZNf9rbuzZgX6NqVuJSRer1t74IxR6c9Yk5GAEN-577PXI0P9Am4Sn
5LnEssf0265Wgaw3uy9qhSta-FwIQYqnoVoBimrTBmGSly97YUe1KTs5REY4zUJNN-43gOBCkgyYvPeXuFZ-GbRDLo0uPptvzLVumMJbfY-h9yzViHIr9fYO
hXi2Zb_X9uvOc8w4WEjRrCHqydhoww_m9wOBXu3ZL_Y5vO_nal5ZjIOlDNSZ6_ggUlBy5GkPzJ_KSfRmmnKVuYNRFgQ2NysAHSMw5nkwR0WuNh4airQmWqaZ
VhNY9MLW1rF2hpRnqeP-JUcDYiM6VaF06_kB3VsvdlmLrOMfu5T__Yt9j-l9NnMpTzIJlmgIyC_rNm
}

sprite $image14 [148x104/16z] {
pPg9Sjiw34L1B2InKE____P5hjaDTIidakdJPflrZd3W2sS2NmHxHtWhIjKFQe7tWTNq0rE1Du6wwHth16y0DlqPQxXS957JNx3LMd4tJPZooh6bH8krAbKJ
YxMQ8Zt0LCgg_N-CTLugqdAjIbNJWxn8Aqw95ckLHLgk5LPz7cjuVP4yJoqlB9BZMYtO_mMl2sd_rslrIP7o5NFT_g_MAekqNAky_wkroaMoMgifqlcf-BGY
MQvL5cc1LgSKoNLNJDx_rLhb8bclLH9fjLPv_nTejK2aT1ml5obZZLRj__F7SHPfkLQbfaJBjJBJnUJN1VSKQhbMxgjJvUFObuVATUEUKYtNodrrgdmSkxzL
AlufqrjfvPCtqihz_L9vmbOd6fwnbQayHhXdhAzAPJ4YmcFaJAsPBKjqovGVrjRBWblOxv72HXwWHH1GjvUBTCUZfqmkjJS2Ldlrs6OciR087yCdYeXg3Kir
UrMY4J_Gs6VNmiSsmYULk9dMWjrUEBO9Y8VlZ6sRgNG484at5I2rboMQ09JcEzlGZrItKDqQG46gNGL0r5uaqWG-88qzauLlDwcCOQSGKIzxQBFhYcH40cwm
nTX6YticlvzyIFUltQuUMyu4fUw9jtkcuKW5TcvV6QTMruvj0XDiCSOstCBDhQBW761fsWk8sMNxdpDDI6FiWTomTDBACrLfMzGojRfgR3dJrEfR1nDIk13F
0RROZATM5oUA0PEfrSvcY2s4LMOgrZ6KfbQNY3GPaV_kQtVS04b8Gkcxx6B3k4krQqIQZD4A94YzbZq5aXanqjIgiet1RcRNZMqVnX_XcKA4h01HcQdCs5sQ
NPN86HxnuzcW05UizrJKWC9tqUmIaMg1l_1T8mIkv8rfFhgmpU5JLupvtqNg2F-0PWe22YKI1E1G3hEghM2pSyTc1F-c_1XWK-8cZCt_4tS66ov0tSuRcmiS
Osg5H4MY8bQh_EtWkoq8gvqaKjh_8rfHwGqhS97mhGEAtkPVpSxO_oJIKQqGExlLi8YRxBP51MhsPP4O4iUr8XrRS-_bsy_DjWeitRws_v1uHYiKQ-BUva2v
CuQWc7swI7eIwNcjWCCtnVj0iQ0hpLUhKuhaUQrwgw7XJ3mtaaLK0BkTKoJFQzN7s7r29Qay7vsOzdd5N2vI7c2DgEuCKjGgpG5ALMq8OdPQaHm7kGAxHqDe
qV37SIpTT1x7HulaD10bR7WXQeAcGZzIgJ9GjuD5SYP5tAq1867H422QijU-DPFkXuhaPB3JN3chB83tCQ2eZT7TVPnP9CTbdtN30e9JA-nUkoUJKf5SGY7w
yLKBopqLClH8cTB-NvPgQeGCJUL-iXFDvtHkaJn_nN1Kh480TTEKAUt_fH1DhOHGjH9Ms-pFcSPf-t_yYYaQ5KcKslJfilq_VXopIYUGtQV3HNAzLbX9XdNt
5I8zVi_LOwZxyIAvNgkRJpryZKYFtyf33p-XI4xK2grtzyU7v0gjT8IwFogIDLg9p-SqYsGvo0mjFBqZMGkIXgSYMGsRfrzjBQUqh-___m
}

