sprite $image342 [200x287/16z] {
tDQ7RSH030LHP-j8XVwhTKw3u4JSKgFfuE5p1MrxA9xRxCLxVeOV4ioiO6O5CpEOMC7C2cPcCBE22HHwo1f_Ig0GIqw1f93uR-QJOkOnc5Z19Z63cHMiM-6N
J87ghU8jc9Z1JeAVa5ycteAjOWOpArZ3jrPuN6iWgoG6PrOmiuA96SoiO685EmWZZw6ObsCebaMlY2S57E8ndj8hthAVr7lsCTvJAygEQGSAvdqOp7jIpAjW
tfDYtZ6OLy5aYhBZPdSFWtd7O5u5itnhouvLCCPJtfDYNWNRDuCAnhnZC86YufW49uMyOp2lWdaLpFGJmfXt37O81HshwwJO0SQWGwkWOywKATZ7myYdR0-3
ZdWA4CSOBDw3nA1W6SqIA0gEJ406It919KVJ93ofkgDF0aNPKPBqA-WeF9F6awAZC4clWeu62HHdS1Ga3MEW_0cI0WKSOoQ1uWoEWgHDGKT9qdzIT1IUIQE2
ZZ6JG370KP0qZ057GTAleEEipmIA1aTX4YhQ7NL9Zc4yKc-twwwgEXI0GH24nFk_t7FsthIh3ZkSFCrSQk5dMH--DI4GBN5G24hkL4YE8SIYxtq6mosHcq9A
QtHj1Davf9eaznmoelip9javh9BB5PhSTWHbVGPBcbmRKcLoE1B9SsEQdA_0aCAXn64Chgj2AZioCd7O9UShrXeS6vCInzzA4rrFpMyVqmjLmM6JS8YScz_J
ekkgTOB00eVgNmWkEJU__QAF3ttx81B7-Zi9ACx9x_Jwzyi3nXnhavZJv8pcsYQ_GztEF2Q4EwGQq-GSnbfU8PMLpLJYK6bNP0WkrNCSovCHPJUZBKEMTuVK
DZw_9QBhkOwfl4-rmCgqdXiaBRlFTIGbKwscpEZWadvmjRGusw77gHFHWH9CaozrLEOm1DVT3csBCJWCaliTdZewQJAYWwV9rpacwkW7ruWEBXdHmTFaH4VL
3ntXsD5FaxCScbm-TF2_CP7wyK5mdU8eatFHufZHOGakxh0V-Royp-IU8u738h4xUAGxjx3DuB73q_skEKr-xn3NHZGu5k8mf0bns0zzNZzo_3TLq64DBhi3
aw2Dyeb3oBdMA87-XDqHduwvuo3xTaM7CRWU3hNq6J3GFRGvYOCloTDA73Q9whyJQdVKVnbX5oLzHwPzE7jmjGQSsT6-sD0kE7tWcF4lz1tz7RqQyXmlQ2uE
mwJl2BkI8oO8Bhm61zRb_6ZOIjU1vKF0OP8OwmUl0sNNZkexAdd-OP2O7Vo2v775GObZubc5QRwAPPWTafIiErwVHLqw3app_5k761t5Eo5LC91-RSVXzsen
3kxexy-5vEkyhXhPNd461qcF6noQFOaSUTw537l5dYEvnh_UKIUQ0SkpZjSsNQY37wBgzGwPtMC8YHnzFT2OkOE7rUMEnRi3n_HdjPqniD31DoKNEoJWe_jz
5KpufApl4FX6Bd9eyYz6KX8Wo_PPSkexzB-FerxgA1CyScMxRzcs6oRjEYgi29SuP8Qd-FGiw1NEjvKuM4TKht9WVhjP3jRF25-popt7ZBVZV4VTvdUXjmik
lA53nv5XHtc-GvCZ-KsgODar7EH7nmBHTxO3ypiApk5rokuIbzry8E-RfFLq1tzBXuy95YXvg8yTEaCLEjkXcUOtFmlEaFLOqkFJWNiqNzSB79ZVbGgm2k8n
rXNYW8GhwoKEznfPkntH-XRyCtFeA-7oUesZbzzucVgMKrxHiIkeMQznQ2U_CHy2oQc23fW4ngaEUKJ7aGAhO29ljYPqm6HBf-iS6CITAgY9lfVR75E2PUDA
1__UU1LaRwuBL7XOmx_G4TfNlwcPKy0L2HsU_9ltEzh1AMvJE6c1dqI00nFkVWTMmHWWzjL3O4MQ6VSxQY7F1U75rWY15M7sVWU-VC62FmhiUGFyaJRx5Ows
Ae73irEMm4zK8ipUwC2TF3Y4dxAcRRaBaD-tE0ffxeAZy2vAsXv20ipUugZaf0wEn7TXPRjN393Vjpdm58SE3J--kDxkPuRPUnswRVuKh8AUP724GyYDZWeE
-0bcKQo2y_6x-Lw_oQ7vgBcRZugbmDRaVWTlxcBuiF3NWDb_lqD_QkxwmzX9i3-_tG7vFIkBdi3tZr2_xtOiDB-nJAIL3TNrYnoTvcx2LHZ7LphYOJ8x6SU1
-OrLs-imZbb_EWkkWpYcgZzrHFC03duMnIfOXd14wNH4lOpWMBJN4Ptqknt5TTVK0flTSHq9qdnSHu2Jrh0ERQsTuHqL7eiFwQZvMGNdWHsQN7nMmML01_ui
hRqTewCw93usXm8dgp4Ss1bjZW8dgq4S-4f5SzHr7So1dL4uT0pYq8FNuj9u3juP7SQnW8DqHaTpiCxec0wPyO7ic0xeZ4RvVtNtWVKs3CC0k7jOa77_qtQN
NOfHnWGJuutkyJsHYF_CEI_fQDdl25oEnJk9EKENu_Vz7dO5_t401GvnpsYvOkMOGANZhVimm5kEiLKv_FizoOKZtb-jnk7VRqR4wsTFEFpxJIuSGf9r-FSR
F7Q4v8p3lz_aeGEGHw8T_lqcfGDYk9JZNJpdsHTgnuGOBkLu_wPpf6JlXYJh0FeKidUNpQKT_koKZhoatq4AXv1qExGYsRln_OSxi3FbG6AuEXraoZ4dz73r
EyYa0uY14f961vbstFhFXwhVGIOSaUrOqkzWmh6Mh5Mz3ZBXM4k4giF1I7hF4yDbT_1-nqn8p0wAYFDGRHM_40uu74pbO3NKaOG30MfNHCIEImc-AieTWtc7
a0WLHe3gGXOuaf8uc1v5ldVrS8MYSi_16iSKadzLgEnTiioH6ovKtdwGPOwHQ2lrVgz-XRwVMWnNVU-2TGujYUzNzovPwiYtLOc3B7RW_tTyA_kS7xBUaRZS
BVgS7z3Xc4WCLyNd_90M1xPjoqXmhdTtrkJCZlzadEXTLWM9UtTNlm2C06K3rcKNjIlFv_xUfKYNP8iCv1sipr33PUXT9kF_gl2UtgKjzmnNh7UoTndfFHBL
kmYGgQNymvNlNJO4oOluVE-oASYlIU9wbttPCiELwrtsPY0rND6xplNs3rVSqG3NOVWbudxgbA9_JVBtKuCFp2RMHDnVOb1uBrKsuM0s_P9GV0tC2lyD_C5-
y6ao88Ohxg1mAlmT720OxWbfN9ER-y5dpEqrYPE1GM66oFkfQOXvJHRdmUVEVjnSi3By7Jo0S3WK_ZLPF3x8o-JeUNtWbR9opA_VuSMoSl2IkRmZSdL7PB-y
8u8H3buwuI1vTGcUHF4P
}

