sprite $image159 [248x185/16z] {
vDbLLWL140HHdCxwgDx_Qd48t64axWxYP3sTkOXAafeskJDLAfWQ7OZAyqBBJXoAhNNbdNSCsTWeMJK4RsUAoJkVDcGd3birRDcGLQDarR1LGvQDabMZPDMO
6t8UYChpouQi6YTR-jqbElOEHENvKqDsucZPsB1LGrODMpNQbOrQIRMllBAKkQ0HYCe3qR47eiqxws2hXkt48Ql6-KAVsCkpZGrPDKfMZLxeI-doR6D3LerQ
w7dNyYxBkHFbkbaO2i3EvaL7Ck__jdykBlFhde4CTQwdW4ztp_fLefPeah_LxHL3wO1owX4QL8QL8_hMNWys1zLk779wT_MRUZTOllMTMdU22wcxZTIwatob
5XzO3ZZvGAbmtr8E7nbAlbQugUJZou6XvHNkCULIuRvJimFZo_Uo-z4HjphcaOYlwMqb-E1ooBeioySqlMqRxWDVOhQlQPhcXzlq3l9bZcgHxMsQlgBRnfTB
LA-RY61zcnR4Uflfs7AdZhoeVAW7B_bwjBZ0n_IGW-H3PMKsKhrjNFatHPWD9BMQseWRggX5To3tReTSJNUIZy26MjwjkX_rtgDSITw_shb9RgPHFPfSr8pS
B5Sd7mGkC6CtEBQF9eTQtYqYJoN_NsrglSibgTczl7tI0gww8wdx7TfPpUwFQVg8RdFD7kN7juxX0hEY-x67BXk0NRqyzRhrAuVQ3-vjIdkexWweUv9tEhGB
gTcD-TijiTvP-J7Eu1ak7QhPZNL-i96GID7ZWVAgqdx91LbsOJvNEv1ASbCbDydRBpQxjrMGOfgJqmEIzw5cjopVaUTwcrcq8YLkfePUu0B6idjvn5sT9_K3
RYoFJDcaTJcKhUnU3xKydMzBSjFTyMAzv-bZUy1fJskznTbzNB4vjrEhxSzoTOETxYHlNCtrvhicIpSk6l4xtpUbmQxHFKsWLkCczT7dNgxcv6wmK-g5DkIa
BhgPdUQMf4xtJKu-JzCCG2qdRxZ5sPsTM_ojAjytRIiEjwcXeLjNWLcrUm_aTcEfEZMVPgYbvoHlhyKv8QOqfwQ_02ydTqDtZvBKPzsHQfQLaxlO2zAOcjq4
vpVueTQIpZrNVgSrz-vYTrxkvnRtmu2Yt8paZHriTkVbVcvnzul878hYtMDZBSxkF5oZFAaDXmmeoLEBaBoLTnUxot9-WsEdUfSME8AtrEBipikTsbq-oPzh
TWSqFTI773xIH8kpcoCiJ-ea1-JjROvmlfLm0pt9Mr2pcwCivxbbY-kO0FJkIkgSl8c3pMuEA5plR_Vxmqsx-TC2nsDC0mURt1Locbi-f-ajrjj8xXSuKAI9
5cStHqloXqVUfpS1aFbO4BUsWYCDj3YvA-HFSyig3iborVI0uT92YvVTFmxj_a5-7_FrPda3BKxkAdb-7sCvrPla3QYJkngEtNkoktcI0rV81MQNkrdEuTtS
RoM6A-1GkynTBu_gyZxsShcG-bftMPx4j8zT8cVrzUuo_7atDqjoN267shNkUhaPxUPfCtaPdDNNkpaxABIb-atKNYqNKb_YhfVpRaxxsAla0hD_vUPcvs4y
yrzBTN0vqUANgcitL99dwgtwYv9B0-goFAaZdFTlDQ1Upke6s35ItirJezDyJkwSlCc3pVdv7ZaDSKYfQlQM3dQztC-fHljtRRCtUR0vwuytw5PNRvOtsU8S
S9pQp6WVgyDBMorUBrU-GJ_NxDAiEYztzIu8gvhzzMeDuL9uTcuHL2R9HPijTbbkDAT6I4RtAMKuoLjGrm_jti5oG3w-PlmWXxRNufpyjTkJUnCXsllyzUEs
8cYqs0ndkNF747p--WHahMZs9jNbqHK4PxaiWBpDPRcshixBWOoSRP_p1mhHLWysfseY0V_hzdMHEyGq0C_BryyBtAHke-GiVv6RrTtAjUs3pP4QkLpe3lyg
-hkIYv3xfBglPfTrMLPods3t9j-MxspaRbdDaNeugqN8VKhTpp6Nz2Moo7r2tLEphqvDxZfsP_8_q8M_C9YUK7TOycrDnIPt5-hpsygMrEIkKdSgJswGkt8e
xLP-tXqeNS5Fk4dTgHodt1gwoAlTePkyqXrwoilS6ZhBQzoXm_pU7VgC_CuT-irltA7hd7M7thEUSUzXW1JTsvPtXr6ITSjIk4yD0mNibkEoYToixZ_atg9Q
XDrXl3XtP6yYxDOmP9mxgRrRmx19RidSfuQHaznHxTq8WmUIkqyDu-VX1cxXPZdkukRSnyrXztroLtSWzur2xXk5t3SAkUy4rqllbVu3
}

