sprite $image62 [260x166/16z] {
xDW5Ri0m00J1SdCNoVd_Qylj2ilaREO9gxC3sv_9lSqiJxfPDP57686qGY2jq03Y0gZu6E3QMm2jznW4Gpm2c0j0LS3qY1Y9FK8WhP1FEX4KiDoDRRv4F0Ai
yWBplpwl-Ixc4K1S0Drcqy0vXH58fv2V8pu66E8241T0pGaWBe1rWkUXSWhvVU82gEuY0CmZW7W4g7W3MFx5ZoBn59f_GtmC0l46i7X7W9f7WAF0hsrXoVys
T1S1O2w0ey0FFYT7PZB48y3lFGyrpyabSrh5nm17WMyw40sS5Iwo1ult60JYOu1-m_FGk8KHG7Kj1D83qUoMxY80hiKZm57WpGeNSLW_yJpKF2BYeYz01JH2
ZJx1RVlckIFR4OB1Enr87-jz_xUrcZCMsY2SFLSSi_5tgQleIOV2AZv_TqCX0DExKm3kJ24PuEP203UdO4y6znR2a6F_CxYf4EPl0Evy50nlRy7WjXGC_lQ9
WSYzA5WG-CY0VqoDBDn7WwyCjYWP0BkD1byPa3izA8Lehy7t39mVKqA8vWGg1aAgExFGN8El32R3XSvPs7sp40G-pFixaW61vId4o3tPLeDayEv0kg0h691P
2j5m7tvaSEP33nQPd_zaB0iARKEG3982JvmcWfdYC8p1GQ6j1iaWvXS0eEdHH5ixX00MHnQw4aW6UHHCzjM3HHf2wDWjX8WGr0oIWenfSGI4BY7caqApVPY3
zu_ph48S0Uo5SoBcfXIYcmPv278iX5Y_2I7WTHgHjuLU6lZxjmC0EeSU8Lnf7mOkZnbq6kp3yWnypC9wNXSk1XXC71GQQL1-tYNsfCnv2J44Zd64o2mq3C7t
MTX3eebAUXYu_XXvVUwp3siXTDlLHAM7k_jWvgJGAmHb7AyUF1Zk0wuFoYpqqQ2cG7lYDD583WEt7vc5vWGI0lQqQABIOU1398Lef45DGTXiX11q2M6F_JCV
1VFwKlGNAOn7704mOo1eK51efq6z9yrzk1i5ZST-J0aApVPXlI54z0ZX3xB3W7_A9zlmnww5Vrs8-R0GGjWUc_FPvsOXgA_FD3IQ20u6JYE5Q1I2-YoOi8oh
1tGOC2mec7NRX_N5yQ71O9CvSJpxd5def46z9pMQ2A4GWkVao48t3MeATFK0SyET1PXvVUwp3si8jfvDtAJEugvZlam8-nVtOPq5dkQd1q9R3esrKeXE6jH2
RE0q4MiZQFYaeD0iXVNrMUQC9X99qB19E6FTzc6TXRCYI5nfNNduRz_g-L82cOKDd1vWBqi6WBKBGVqWOaGJYHaN0zQWq6iVrXHi3uac6grWe7ArqRg5e1R2
Z4uFTZ0mi6OMUcbGFuZ89b8S0maADo2G56XmDd7f-Saiz0b13S7OD1XinPM3bKByHo7mro588Gw3oMQ03GEWGQEP1ZK5uSD070QOBe1pJtRIeAPmCRWUJ-ip
3MUispwi8LotPeueaFnpdvIodvz0nf7uC72O7I4Cpx4NF3vy8GNNmy6P0J4WANGBGVqM5aeXpjXA2YzuekWrMU0K8aOo2xtsOHr7eMST0PW0Lnhi1WHI24qX
mWMLfD1f7zP7GIuX71Pwc19R2D7j4DH2y0uX5009cmuB2hSWa4yv4fuCp3QhoTOKeiy-h2aeFnbCCU4Dcv8KNl16WfS9eG1WKusOOLio2o-u5hv6Y8i1Z5XC
bWK90DOh13M5dAMgic0xXMYo3-inn0X77eXCbvZonhSKq4g379onO90xaeKGMUYfGIs44Qdn-K4AqMOVrjVdd4Z2L4LceMK8wZOACNG3DfzxigS6DOL80hO6
3G3MD8Kr1PKDrMdO1W3r6MXBmVAn9Bou6BU601OocrOmU8_fJO58yXnq9b1dOLamw4wWtfF1u5u8OXmVn-z68APYuEyzfxu-Ut48xaB1RqaW9XaK1Ev2mMzB
82bu4hWj1BytWg3WhoJmAm
}

