sprite $image365 [225x214/16z] {
xDS7igGX20JWPmIKkVznDx6PpVjiHik-m3zVLVTGlY1JYFBBiKcLH8HREfEN6uk5wu6yqkMhK3ckcopVfkU3U8t5Xzifq-l6y-4JUbf8VXwclFlqcEMNuPOE
E0k_9jPjpyAlU3kTZ59_U1RapyFzYNkQoFyRfkQdj-aKKnDhMVw3is3PwcJKBvHFBIl4yczvlfEHIRvEVJyzfzjtYgdx7_XBtcOdeyg2FC_9A2oBOZsD7z_2
S4lXfs5nk4IVXkL2oe7jn2HgYZ80kCYJ8NEYY4mb1ZW7YYWzHm2HH6u93hJWfbZWG3IHCXvuS4yD2EzfXGDFdQ81LOrtuiamu4D3fWW4Fem8do8G-5314vao
44Wy0dhQ4mv8CSGA1185z5Iee81HHEuP1epgQKimODWKKS2uAMOGq38YffW0mE2Uee1633aP663eoG01BJ4d0mWa7X6l300m-cG0WB74ZWJYJyQOcZ50_Cam
diA0-9uELOK1yITZgeA0-2bQDq50_1Ijcp0WVefJ5GJ4zzIwkGIOXWF2YSQ30V4zjUd50nSz-ASg58ZfgU-cJme4UkAVSORlPW1mpHJDuxeP0LmqnQ6FXxfk
HW2NJ77C3vzmF3nmJK_j2mQqwSK05n67yGmuLRS3-fvwdW6jct701SGnpMTHtG_uwvuEuvq0z4JZ7GBqFRNJS0pG4sryvm1zJurq5D0oJWSIZyE194k15tY1
5tY15tY15tY15tY15tY15tY15vXfdWnCJTvsTnvAZy9034uFrYxl_xZNomv7T2XOSIQUVZNVMEAp-S719mDUflR9WAUfjLO1upC0wm5E5J3HslGvWDVMAc1c
e7qVqqS0rWESiFo1rti3waVa89Q4qxi0ddSVu5G10ngY7p3QxTZXzBJrvrocyO0_Fiv5Bn-01U4wucX0b0CXnF81P1A5d3e10_KL65qD478w0X1F7UTrHOdb
DiGnW87dNjMwrS--iOhJ040yUpRBhNnsSnL108Nf4tDwMtnsU10veCXNn_Mu2V29d3OV88-dKCK2I7BAg-W73EnwQ_9U0wXNqGy8uGH81YXLiGJ431XecyPr
0-2EAje08H_dnG6joj010_eBp1pGgGmT44qQ006qvrG7394lCWYW6r4730qFESySq5b57J0Wumc01cK8W3eV8cS1aEUK8tO2rF6U0-ooaT810sewPK33weq3
xfY-UHO03LLK0GDYEZL0Wp8qm53JAG8QbA401aGy1T1GHHKmrFBfW5vbSC20LZuLq5z53XZGqYa3sgl80Q6bqm2uRoF50JEWfLC7jEUK0shfr03FZV2eEIMh
DmOOAXu7N8uhAe196HnGAPyEU3ZU0_YHC9SofXw0aJCVE3maBC_6cAee0Chfh83ywGeubS40bNJgWDVoxy2f308eg445F4sj36jEu_j80R2cKmUiq-T7r04h
dWh8lnyBC2X302JbKm4l3_zLYp9qmAe67V1Ofy-VqyU00I6TnFDNFdr-n7N0x8ENzoF_Paz_5MCDC06Y1Y6UvuNRjwtzEbkn0l9z4iHqNWx2z5bp6cb99tCx
9-o-UikAroMTxKJT_iegLi2CPYYVC7skdAPL3LKEViJLBAIpV4ktZwXY6iedJ9zV6PaidReQwX2cprZ5JkbSUxWfq0OYye6GyAQ2Lm13G9IhsB116HOrLC00
N9DO-6aLzwUpg649w4H4-KqffxeQAA0nfnonIpgpdOLdN_jF8cXE7MfOBjCY_3a5I4xtgM7BEqh297ghgAlXjEqjit1LiOO33VXV5NUeWIFUVJcj_ove5VLT
Wp3EBVnL1AsYhWPjN67FAO27LTonQn1pkX-H4guh0z593MEL0Jom8dBEVchWoh3c55XJndSr28143PkKWPUltdwmPLyrZ5S6541T3UELqG02AAf1h-ABSbe1
3MfWENtDBaC1XAo6uRiCB03b6qhldzCAQ533-DLR1JIeORmoAg113Q8ocW6n07hKCBwA7305DUnGHYz40T2Z1hyo9C2yMQdyLUI0ENdAvrS61VIhmQyC0kXN
Wt-NWPm9e4aDVcLKlYI0NZNuTnc8xm2NnW33fWQ_Cl0JfLon2g1R3VuRKuXV3EMALG2jQl3VcAhVIrUkM0NGgGQ_CkgTtJoMArO1bDJWLuPMHMIHmB4iSly0
Xb4DVcL4vRij3qREVLlsySf0FbnX_gXYMildLqRbQ_-INE4edt-NKUN07Nuqbi-_oq0QLvZZbO4WpmlOXryPIEFDX_7Ag6utNqQ6t9X2EiitNXcHv54oz_0h
0zxjtNXbfFVEttXba1yAVKPEpNV-nYl3VETll3BCQXYlZFOsvViA
}

sprite $image365 [113x107/16z] {
xTg7Skuw20JWkCbYGNd_nxr_sqayc3Z2lgTpUlr6R63YyfQfOQvbUFjXDIvLHEhyWxYftBLwCzVn1t3p-k1Ut_tVVHsM-j94dcHThW_iusVbWoCfKgTh0wji
syHURkhYACSL4CXy7uCFpPFBS4rYHI2t0ch0aRncHEOdzoH50ezHhjFfy42F5P4SaLDH5d8TP3qJfIYai-gfRIUcs26FenopeDwAOb-KGnRCadLEWlO5UUc8
46pjAIBJrp41MiEAT9JBa07BMXCaHoG5bbKqIwvJ0bn9vg8S4k1QIar7MPS4I38PvTGn5WJNAChyjej1YYUYn9m04tqbfwtqW5cId9bbmSuHgJTEpV8We_p6
8TbBinpOtLVsCWkwljQlHuIzPBKb1nv72KCLzl8gC8uIrXh8NGN6KKBRhG0gru9-swcrUvbT2SPHuiPT3yPzrTP-34ZIVWX8KluCy1_u3_m73aL_ABW8VYGu
LOYega5aBUL2CBwzzW0X0gbhEG-Muzjhekh8D6WeGtnxxUa9m4-JmBvcGHM1x7Prg80093U7B6cGDoGd3qxw-aFP8tEWGjWoVzasgf9qVINP2K8-2kuAVEA9
zlhAA7j01J6IymweGDpNqWFgHcEK7jIEA4EGn_Fawi4leopbUw3ARa7DWnrHXY3sFRKMWOmIKLzZC3wUjHQ2nr7684BEWvv4iEr2K9t7gwi8x8dIWuZ2Yy6E
A1seYBlfGQFI4UKMrAYRMv1LL6CoY78B8kXc0BwD0WHar5S7HjrawITlM7c2Zhw68BaOvECqz4Gf24265u93uVyMaC5Kng2QvpvMs_GyNaJ68_89D0sxIUvT
vytnM3rHAa55p55S1txkAwxmlH4XQ3W8prghO_1qiYFA5sWu3AzXUWrVXGI5xqNvdV2QBRnoaS3h617NJL_hm77Gm0j8x937tPHxU0GLFIG4BigZRZv7WGLJ
FHAnAv8y6eNYhdP9PWufmE4e-4l2VbAm8Gz6mTKarXSbi3rb5DuINzO7KSOYyCcEzvYlyr7UE8j78QwnggP8QsQEm-o0N9I04uqd9ET7uR8eTGkogWilhA5t
H0X-3c_gV7EdPqG8kZtMKtF7jjk27U6bHiI3DHw5yoEYjW7T7WigEoAmzYG9Vh77KYFYlJQEOXpyWprsTaIWhTdxzFhuikRtM3hAtRx27g6DhuylUtTxB5-p
-4C-bpLREAvQtgwiWYq9IsoJN9GyNcARf4S4bjicsMsdbjec-MtNKjial-qikKtoVUKedAh_
}

