sprite $image42 [220x160/16z] {
tPc9jgEu3aNbsPBCvV__zZt3JJKf4muEgH2okslEj9SbsJaUtuSmCu_VIERALze9_q6-rgoIlqYD6xv4x8VNaEzPinR9tsfs_S9Cl8rSUpf-fntl8rzO3NF5
kV-TTjoBNDWCytFXuOYv_ABv0EmkQnODaOcNjFEyIR8qOHEGkzpSpux-uFEr9YPl4sY92NmTEy6DjkH2RQUW72sjuF8LrWwOUMh0RNUDHZFq4FFPkvtYkRyE
tW_ykMOPpls6dhRxuEdeQHUU7_Ev1op0n-u7kQ_HZ5d_4suxVRjQPwC5zRJ0QTZVTlAn1woAus6uTok3DFhyc9FCi9l9PIZtAbRAKB9ftCvUEs68wi8kLZFc
UpVcQXVDecZr_4Y5Tw3_bPoNeQXmwyQYPRXrePDXK3avTE1zY0u3s-fm-yoDs-rHZiZMeZqxX6RXlTIII-dscHktnQDoRCnEiEC6K9X3KUOjjybkAjgzV4gW
gYeCt1QFEi-EdmEwdPzaAh_MpV0nphcvw7SxDM9dFi4DyWQpqznOFaGjns1UxSRYppRBqHbgiJxcdSy7RNUMMVA67cC3rWk6R7fvsw74mACFbeCXX8syHJB_
8gOLWOc12VYhDyQ4FIyHDkJIAnSjUnnpU0BWACZ_axm8j02EEQAX7cpcbeXZsdwxdwu0Ay15sqFSi_O-7qt3K825WrDBwvZ_GpTW4gJ3m3rvKOPcqfKKEocw
SW9fCI6nQ4Ku-droAtaHcUSBKwGdAPuJ0wnceWmJfVp-oXwMvSskQRldzeCiNKdnb1Z0RB8-hbgfoengDTJGo6Lk42s3UDW6s4uwa-AXA3VavfwcFawa-SW3
6xh7RgHAnwxjEfFYEPh37HdA-kEa36hf7hUA3y7JaVtWf-zA9ef8NYFHFQuKUPWLgQ5dWCUmtBMZFOqMsOZvCZq5RZlTMOwUdiTNjGqvGu23rtO26kq8KNWB
zVGaUBDZP9Oj7NFZJUIGM-1jHE35xkjweiNIqpX1IRkeRAVwvP2TuKqoFOlD1QeLrIsx-HxfdzMDmvltH6fgVOVPCAWYkw6zlYNd7s4tEWxDgJYqh1tFl0v5
uHtPhvisRGUEuvRBi8vih1nGCofhHDDUdgkWAwIRMxjq-3ZkfAmJ7fmWy0XEkcEOcRoh7E_S-jlEv_KNjaJuaScrWwy8Fg57RAR33Qs0mkmwZgiOQh0XBSMy
fGQZYaE5veI-jWfhRhZjai470ocJN8knTG8vQsWDsvuyuqgJAox7nks6R7Ue1jnCKiGI1gk1hyB0h7N3ROVZ6Ma62YIK8jk3DEoQ-y0D5YPRi71LhkiWQdbj
HQGCx9glmc3k0xUUjhDS53m8q1PRkx7QFEmiH-o62pEW5j1gPmbZwsleriPgOa-ZOJV5np3G0bBjE1Xqpr6QOcjUPS_S1swzRJUr07hBmj6PTIyNfGomZKGx
6msxuMFOhGMGNNrSzhJ4kf14vtyIHk1o16xzTYgy0z79BzCI7If5LHW3vpvm0tR7415Dj4HAKH7XFd2ZOJVSTlr448vZS3csA4JESiDcq0qZ9xhXHiDksEvy
Dznes2tvA43k33TSZjWjJETkO7U26ov7x6QfObaFsGMRcX2kTOislh0SiPiXSfR8CDWFO1xjCd1B5jobWNBiTtD4hCcG5J1Jy3M2pnjksO6xD6ZMxvQ8acec
2fhv6JlVt2EjkGKKOk96wtSJIvHLFP5ayWBiKA9eK-lMFigaLpGQTjDCLQuk7nFvtcDOzarUrBWraKDuHJbYDvdbeYRZrP3jtSgbI9CNHLgIcjnHYq2pLxXb
nvfDxJR9wiY8gWYm0_S7C0eQuBVSrxWnKPpbvdsSLHE5Nhj8nw8W_CKQ8zemrI7RggXvcfcUo8AsU_RQBY0pASEJZEDOz8xRMecflyYqV9R8Y3RW-mE4mw7B
yBnQHPTCLcwUbhvgkIeuxGhQttQmqGfej6DchLqYSb8LZQeZCoS2KLLjw4p3D1vfD3bkrjf58ZFDRQc_5J_FQMKY8mVR3WVynyr-nd5RRa8q4zNAScHdPKdS
rtQ5BMoqrvVZbjtqWQgF4FbQFqJJ8TffWCSmV3M0BtQFcI6xx8nZLJLJGJ8Hrzz63VKdwMYxzjeklgFHMhJ1pTViy-6IU78JcpflHyJH3Q__SkvtoOMvxznq
A3Gwkn4vxjxjZXsmC6M4h7mfi5N9UIB_nuqezBVT6-P-bvtGf9J86A8qkoax8Z9HEzkkckbvPgqSswh4L95VDzKyHHsvh-tUCVSneWkIg8gfBZgxtTQpj-tE
CMjPI_P2uqRK4nYzvnZIR-U9AF_bbgT8h47aZMPbV8hyLziP-SjDDLdkk3zuruxMltJ9Q-EceihU-NJ4xWsDXkqQjmeRQaPcKvXdp7sC83TFCs2tEwCSCMNR
RKh-7H4bq7OdpFtUmencwNOxj_0KHWExiyiHsmaltPZcVK0UnBHowexMRxTqarlGaATYZMcddUZRTZJC0pUzkQabgnfs7iDER3Hi9-RNpTxSukshgpR8sOs6
-T45ucaHrLROvGTkAdB20Ul8RZShyS96Rcuj0kR-EMOuKJ7jziShRVTnvOZjyg-EtBcjhPzycXcsS_EPn3kUtCAlczMMqniDeyt83C9K5GCHUNdaLZvjqR0T
6vgOt2fHWDj7cU68lIBgQS84uFOnvOXtEuc6YA9Mjv3gxr_bDfv4MThbn3gvHPK0t3xH3EzsavigkrUuZIUpwWRcv2NCsj0X0BShgRLfc0Lkrp5hxKIEk-cP
ClYGUSHj_3Gwt2vW1evXmEqoPgsT10VSG89r9ZXqw7OhuqVJ27MuZH_FisxZ9NZARRmAtMxZXUXp6o_6VhVnWknq6o_9ZsAtyR8Wj_7IRBcLyUeyT1k_W7Mt
yKjetSOlujwjZD_5mctyEcvkurTItTwfzZy
}

