sprite $image400 [130x88/16z] {
nPg7YkMy4eILfQvFEk__k9UnCB_WhES4NJn5sgo22dItrts1qAftVmXVJBBi_Wp9P6PIY-vF49ja1wGQ_a20AfcTaEMxxP1DPYjawLO3D9cjkDaEOH5WXLJy
FGcKx0AoV5C2hw4MxqZWDMOoxnJWPZlaQm5kIMPiChZWS4SoFJAZi-XminqyI09ued1JClry_2CEBVs_6KWBX_kbiDwRQnsP5Wft9jE4NB6Ax6_iu46OYZCc
XzkJEPs8egLyId5lCZq71D6hWTbdKdYt3T4j2g4cbpjCAMuiwaOtLoG4ARNqaHt4s9R2WwXMd3g2vghqjXqOZw7TP7f0zEPQQPDCylItf50Vey_DOj-9GaIF
4BqwAxP8yUfzO_IjwHIw5H2MvMj721zv8OKOOt0omNqBdqqwd0W8VB8AeXRplnOrVGnqCXbzPpeLWbnh025hhe50BbjRfBWKu0SFxQm7WYb-Qq8ejPmkYdeH
e9y27EXjPpeL0A8fX4acEsiWB5egpqLz643h-_I-CvrEfH7Kg6WWgdpaG7HgQqck2UHyd_xeNqsd9w0tL_iKFqqoELaIGlKewbEArG1z4e0-7hAT_L0I2gLb
4AqrPns1kImXY7afwfd0LG0A8t-HmDLN84Hn9g3Brpe3sTQY1ZFHdmHuL4UEoOMD_L00GjbYx0YHd3IBsae3A9R3B6fDAou256S-fDIA_r20PmRqv5KqoOJS
_rNKKu3bVQBpsUMK9CjVxuVGcxUECBa4269K1M5f5ZKc7m0j1XYFnuW-kk9Swbg6jayNT6bEgWr1AIseIx9Pr32BMg8cO4tWg5Mk5KUpCPQXxUC5NMi1Whbg
XY3L6a78wYpg0ui0mONYilVzyHXS36sN9x8L0YGijAC0QKfECCMVHHrRIKmEfm0e9E-BSxKVlw9bQFjaGLzR6QAN8NeBbjea4_yhQWF1w53pi51pz8wgny5e
wCNyl5JW1GEM0WH2c6HAK3AGgdpgI63HvU92ypc4Gu2Z7VNxEfKbUya02MAo3CAgpQ8MBaa8SW0WErT7SleXCQObVg0NwrGolMO0EWiG8LzQcKLTPr4BwCrv
nuXkM68ASA2_l7lvOdhD00J5KbYAMdHpiwY1BfAp7jqOZqU7ivtGzJgrbk5B1kg7-4S1pg9E7I6o4qWm7j7fKHO1vW_q_EzQyLTslAOGahg4pVb0z1_1DRin
b8CUqJ76Zm1BEuwXzzQfR2yu1ESBNL2pXREeCo08CvWZfTa0o_iN34p_ieFq6uNm8rVhowGAkRGW9BNPI8mpWOiI_Vr3HsY_SGXJBf0mEukwdKKDh08iFv2j
-3APucJWh8FKBLYUWRJfH60HOFt11OMhP5xQOM5m5hLRYXg9DO7h3sJNaChRtn7IoW24Ybpf29ZpmVFxEdwWpwuSrwVqubS67K4uYxeiyy7J3_JvfIURBdqp
6VIIwH9ghW82uCa0OsNmEe-laocrU3B8Pp9pom4au5c02RqLXFVi8DMJmOzSTXPr5O8rWOp_eCio-FpJcfcaoM3A9JIBkeEU3739G6fXu-E6nCd0bVboIS0Q
XHLitDWkawcL0QoJQbSVAxfsxepNoMHb05edrHLTkxVMwwBEAuF9uIq1hXFuHJ9N1Y1G7olGXmdyF9bXPS1B0NQkc_4YcRds2m9T6mV_JufQ-ZS3PFjNxWz7
AE3N15uBi9dCbSD60ZUIkNBu884RKbmNDMmcSBUeWGi1zWtmzdBJsKdWVZ9DMmdy-_yKiM-7_GJk9tF_4_p60NWZWVjIx0kmNzJx2TnFvhu0-ydSJ-2-7LO3
t8_Kj5-1-ycyM0DkbE9h0Vu7
}

