sprite $image233 [272x184/16z] {
xDa7RiKm30JHz6X9GBh_QTEBi31QYlnfppl2W9IBndv2ByOxf3wDWQu9EMIeOMASLcZJ7SDX60uJr339gXXgE5R51CDXgE6eOO8SfbF3KCC4EGmrNAU6eOOx
qiivGPh-mHt3OQXXaXgc5xvaOccq0gjIyXY9q3gDuIZrtQi9HPfsqHWEGmqJr73aCDHmb_V6GP57NPHWLGmr70U7OpWCDHmr73ds-UxjAcFrR52agHY6Ozbz
xvsAwWLUHwj_vQKcZ8Wc56awWE3W-5KHgI-eKQT8IDggf9C6oGmfDcgSj4XcHaYF2sgK-ExDLzFID1tMutDxTgBao0t303HtOWAm_lzhSxbjr5AgtZPhrcEr
1hbJvxu5ILNFGOzD16cFhZaqW4N-YilPyuo7it17i0Y8SzJZgoBsC4WiBe8Knjf3apa8B2q2THvBYr3gFH2nAWWaPO-LAm9GJ1uhYu3T_bXBvA-yFzXvH02h
hX5q-vGIOjcX0TXxYB6g21nxB2WITu-8vB61881breX_0ix-lcmWXbffQ7WFx07laBL4hYCF8W9W1xB6QyGUwTww8KjLn1xvtdgfhYCI67j83FZiEh681jdV
s-sVowpL88SUm7PlgKua5YZ7phtLBJozY3Nsxotl8Z19d5nZ_zvI7Ka4uwoBG-Fx0jzRYuZfA_m9oo7g-_VM8lO0ueoZqhPW_zwIlGSYpZCgsUFgN-ac4W5P
P2CvrrVuO9VsI7TlVLuOTv8pVOKFSEJX-5UwUsy1aeoONCGQsSEn1oIfkxVsaE3pE_-es2F78Fsz5M4F2TDM9C2Z7ZurU_SsVtIEwJNiqOS64SVtTZl6bmaN
Qv1FUhI0GSJ1lVLHDaZChs6F76IH_jvomg_m0JxduHWaVmInosnVuK5MFIpIav1mV-Rvw1nasSDxTNnlIH_bEK02B7diTyJtbZxACrG4TEeUVeqa3smYr1GY
80iU-oAqnoqIqmbwKuyWwnvzehih15mHTI8nm-AeUxWZi8T5HaSvvjGWMmM4J6jazD5vWb4fU3Z9muj4vEWeHynGZhf7-wttyD1y8mAG068w3R4za-IHHK1x
YB387AD2aUsvZ3n0qYAyUq2oo0mQf9fJyyXhnDTOz_yHCSUeK6o5P8yyD1QIApA11jLgYUpH3mqU_I35rui42sdrT1wz2BNrGw95tbH3xaOjmZ0aAJ7rOwj8
lEsDzUAe1-EGswKbtG_H5PdpgjH5I8fTFpxkDG94NQFUZJh8k1yVD3H1IOZF69MwoBWVJ7krgY69A6lKdwDraKS_w7vynD10Zp1Uy3WlvVfCFqYLHI37GrFN
aAxjXmG-BVOWHlseF-63oi4h7kTraKjGj0U9hXyYQq_uW9n-QDv8mo9nsKIsVe10waVr2G-DW_BZlFtey3O381yU8D7l3qgKI22YCYeEetfLr5wGs-zuNFvy
U00aXlrmHSeQmbjhMEJF4BrSINnBiOqGoICYCTkeP92uRFDY4I3jrUDFU6XtL0hTCCUhHBnF2GzDwiVc8eEyO75GQY-FzsatD4y_uR4pAc-kuGIzJoq2v7wa
3uf76uBgg93jqm9Bz9-ODNZ2nux8ZAEI0ulG8kD-I4U7XjKRQurF1iaYVJ-KNYCxDnVrJpwVdolweV4J7bi_AE7ciYl2-gWeSRpTqFJxuy23DQmnNJcSj527
JtZtOrUakaQPFdAyune1-lsXtTT8UN6mEUyyD93k_Q3xuM_EB_W9v3iiLXvyZKoiKR-zgH_v2HyN1wpjqIb43DFlZ-47nIXeeBrtzeUc_o00HDH7XSsPQsZ6
_P0h4iKFO1EBzFtmgK44wZzacdLeXAuV8WcGG4JXgCmHZaJsFYYIW4KAepBfq422nlsuWQ3mZMDY4M2d7uT4H5xRbC7ExIL5zuFs00A5pJ7tqEpq0q3XnJ6x
o5u_CFtYg3_X-MG_MigPrWYUxaSxIM8yD3lzg6hC_nevv25pd2JH3mr9W0SyHAcTBxaYz1D-tuD9uwH3GvyQUx3p49jpPX4FZ_j14Q2ZCtFaDGB3s4EbZnpp
hn5xk1yzI7FEFpGEZPFtw98YJ7MflZZcNoEv7nIG5iTQ5R47lJ_y_bfJn1xmasDT4NkG0DoELK7i8GAknweYj4U0vbXLn1viguS007jy9Njy9Njy1Pt7bmVj
iNm2eDfBFVu1
}

