sprite $image21 [296x246/16z] {
xD2n0K10542nMlNtdnOsI0NkPOJCyxRB19fWgYMAQaccQgAfbc2g9OfgIQPgagcM8AebqfAgIRM4Mb8rgPPKIwWbLPDg2RMaQb8jgPPGIwecrP9g2RMaQb8j
gPPGJQebrH9gITMaMb8jePfKIwebrHAgIRMaMb8rePPKIwebL9DgIRMaMa8rgPPKIwecr99gIRM4Qb8jgPPKJQWbrP9gITM4Mb8jgPfKImYNG5C7UsQswo0C
0z69i-ACTF__Rw-W3g8LspFuTEyRH_58O_fq0pUba-fqYOlgEZDTuAPwx-kHSiuytJ7bflg7CNpEcQVh8-Mc9hrZoaqXr7vjoar5GAP-5LCkYXE0T3vyRggH
L038PyFdfbfLiW50QCUct5HBfPEOsOafP-Df8c7aWvXoKosNneILkZzyRggr7B11skxmkQY07-8qH6rCkIda1ECafbmKW2puuhVAE7tn1B6CyfZQHScHJod1
Y8A5DFcH6fPcJwpc9M91ba-lCeFEWM8X95ay0KWUKuRoGsjAEr4MKoa1yoVWLKOvi7utY1ap0H01yFADI-VATxyRCLK29CCeBns-pWrBlolO4BB0nYu2hzsu
AB_uQwqAlf5i4vZYMsDA-SFV7tP82H1JzCOgqtdFarMPUGBB-pOkIkvu2jX5Se2ySUEYvAudgH43YS1AJ4kgR_zvVfNHpWDFGAe1HiQM787ugerBfx6VJxdW
YsBcNhPnKVBS4qBD023cgv85UDd6HSapJptPvGk0i7gYfarC6K-kCfsddhZMu6p3PfweSNX9C9wxSUayfqqaXuUITpqXF3scb5UqNCaEGsh2J1cU1f8nU5wL
qSvBMYfAOYLM-KJGy3I8-QbtPSpIfQT6nOPS0e1_Riv4wN4K1i912758x_-wUn350-taf-OsPk-ToL_bhw9EgoKIH5i4Bl3VaBZSjUISKyubWVQ8UuIJA857
mCJbhfIyRtcSpjZAOE829u9CtQharda1PyS7PpKylXybv8HIdV9xKDZAOE9olv9pJkaRdUZUUsnbyAnRcRjHSaw7QNfG39CkqQVY6t7kEJnM-tvEXsaAGeGo
5TxhU8exorGp-m5ERfgS0nmHw81vnrPcJMdDYMamJN1GfjZCgWCY3ZksCatjnpXPMvccJ2CdgmoVZpibBce_TggQjG-cAV3X4SB0gNafRfYuDFlHutlsRqmJ
vLRhYqDEoEaxP6flIhY7WMhKgcghXSR49MITEQqJb-rB3lSmK8saUw9MSnWJ5ogTqtXuaRZiJSdFj6SFQYJFHwrfIbnYaKKhWudBvYNdUnXoj241J1CrTL9n
J5pyH4XS5gtCXbvWtGS7RsMIEgbC9_F047SkrlNtB3dav7XGfeu2gbK2c8VmVOdBlYNdd29zYmkw1U19fho01e-GvBqeqI9nsPMISmg7QGgTKxLAascABvag
SJGF8I0dUiI5J6rPSiu9awPcPZdCOwf3ffm3kQq2JlslHUAo7oNdv6eqSMfr7bEvoMwAvk4uadr_CT92fhOfEQmxUEx-uvkxHpTD_kbbRO0pUeIaPgRjYOWM
hSmcNW0vMPwJ9kSasdWoJQngjShu-4TmKBAQgMfodLiaBfkK79usFJUL_h-ocHMQJ9DmgOxcg4hdr5_aqGFkvN5bI5nsAhctzpPSOffpqahl4nUGgL2ej6Vq
88Ee-s5hcQ2LsOGIvWKeprnXPGKtxa2cc4jh_KUvqe-2pZsB2J0ytgJaC2yWI9g0qySnbPi7bXWoH0-18Tm3cTg8akzXP2xk8lsvFMeQEQ5fEW-FEKardX36
WLCi31xXyYM7zpQeDNUHutDJSKxorZJrY62iIX8H-9LUVB5rJYvJu16kJGbzPexFPZVDQiIr0-CGmjaqHKhpLEQGxZY61nmUf9rJfuMjpDLB3lE2ycNIH3Af
aLzyIM6IAJauFJZoL7n9gnmo1OdBjTzCkDSJlqYQ9FGG9OR9D2LqawdwIrEC_Q-nyKjySC9MvkAKd5Eh1PCc75Dv2YTDZbR6-K4VpAvVGIYurHnaIWzEsCfS
e4bPSd81_vWqEREdKr0UPIgSym9Nya30CCJGGJqv4Q5CNL2Oa5D7WqaJeMboHzKAojGtxOuql294VaDHdvoubG29osLBpi_h2rdBCcbov_a8T6vbg9gPPaT8
KoxCOHHqVZcgXCFZor9oJWxA1JmCnGUcgNZWqag0ggJIss0j0MqMIPzhZKsVSz8IKQOkLdB8wI0b6FFEfecxN_GtmrILNAYulP-RdqUj4_CGm-3G0s4hSqbA
pcaabM0Q5UPMHjGvMGsZUV2yeAWPp_h5IKQtuNsaS-AQ0tY4YvKSSd9IhVbxAAD7SDD4sJcrE6tS2PMcXRDPEsLJurpBFGAzEXdJXCFZgtW1v3I1-j8ZF7y1
EBaLa2ACLq3y5VYJEYbMxsIq4AxhNwlaa1CM7-inEg2fbQ7gd31nIIpLCbviGC7p0LZ8GoU3CdMLaaDEI6hm2DQOQg5PTDgJayp3OyhbIIB2nGPm6-uHA0oS
GAQkHCavmHbzPY-7MgEQoTJAX5oZDto3UI22IyN-Yadmql4BXqnzz_1OxMzpGfcABHSc7POoKtwPIBYAdhiVntEy8bROVUa6DEd02LgPwr12JYXJVZedBPZ_
OXzCHU3_3wzmmGEFG5scLb-GW2Lt0KuWKy0fV7rDWPBhbzSV2Ks9CIOIxX5eCJm6IXVXvA1ccUgSebIPJ1CU8ZTDdeLsqmJpgxD7-9xXiTfLE24f2Vu1fwsE
poVom1E8ngQlrHa8UeGNdx1OruStqxKueKo5r5ffaBZCujIqycYpOYnWcZ9_z0Xm6XIVKxeM9oHLelTbCZSWb0dsC9Idn3WXa9XfABvsW4PIf7eYfNPLJfYu
FFXZuXABjBvVaD-RfdcmvSLd3Xp6xAncwg0EKaxfefpMYKjEpecAcggPJebnBpsKAN-hcVzK61vBxPncKceNvlGTYSkmXr7GD25QRtvoBNYth___ah9pEaXj
G0bQcO-92wVIwh670QO9qCBo2qnb-hw3liuJrBKfVLVY4faUi8S1fabh_R3yGc4O7ZDBSKx7Mse3J5Xyq83C-KcIgZpqVM2QpC6YguY9XkAJNAhgH6e3IaWg
ulBza9zG4iR-parJwk-AB1--Ie9ZdEvVgGAfNIYTMnaiFiuqTsgG_ufQgnNlQ1-trsLuCPFEnpR2X39rzWYfn2alWFmtH4hzdnBXkb4W_vxErmd0QIjAA5Fd
3xBuggiZ9ZYlKCVINm0oHK4cii1f6qf8glZ6tVn1HZJASqYrPi9je5pTLC2ENgIquBGJ9MnbF5Qp5wTnp5vh1mAcYJY1GKyvu7K-rASDC2qJ5-qTI7n8BaBZ
SvTS0OWtFuEkmV3OVzqCE6r1QIrJrcfHtpOVrKW0Y5Sbw1eilwHg2qwxKCBXCGNY-Tw6FtSy1-8vJWOzWNc0_kvrTgM4CeNtDlovNUX1fevW1QlIovMb8QTj
CM7nuRqDV-xtmOhWnUEf-Kai1JdjImcdCiobwPmNk4nnqmyoXSNdLIcvLk2qCILCN5YOC2-WZu5ufc6gcM5uJ07zq-QOi9KvtzlWCH3t-toO_reM71uZfyqf
eKoHPFbYQ6x6WvTy5Pzfgm66nyXfSqeeKs_pWf2FG5nxNW1LoG-1br56Fxut9GHL4dAQvbUInGTyO9hyoF0c14vtm8JP51uSitEf9Q9fwjJ2vpvORq09cpuu
C6RF5KtJmUcnuBGx9HJq-S2ONKg6O2Kx80aBJfjZGb0rJfXgXZ5xH8EEOwfSsuBJpfImwVD3QfhcCHKOTFXMlDZUv0Lw3qf8gid8oQmmcAP-8F_rKwGiEErC
2HENckQTHVWsG0XMl2e_vmLw8qmeKpHmQcR3jm6wGN-V_ygxl41lHGdTL5UZwfmClWqmAPWkDmz1Sj4rf_qfeKonFZbPgJoP9d5IUHuU1uvhNx0_9Zz3LONS
EgTgLkcS_vf471ulEDs64hOoL9oJwVnjWB6fMQq1TbmMd6v42REfs9wShDOqcIOfgGdqE6d1wIwKKAPyiQvpQchAO9emBw2yu7GRJ5Xyx9T1EoUpGlFG7FE2
iE1qCqhOob1nJbwCXsbQpitrvfGmSOcjlNndmbKM2GjEjwQ4YGitvsID1zCqdRZGfrjYmiGbPFUTMYgzot_vb1VSbD9QfjntgfMpJEMg2qxtfOIjJAo7xpp9
L4cou7HJJ9Yui3Tzrc4rkAO0U_R0wVwKC749MJidZJ0yviKUnkqfOU92-CMJld4dkHJWT6jAwrOcrfcJjp9qya_tnRGkFfUfVzkt2ni6eY06ek7-EmwACl99
5XxiR0dlC_ZdX9W2dUOfySRb_3Y7nsCwpLFYZKkiE-UdWKmyoiIwmccg4gSf5iVTJ2KUPGgdeKhCQBFkS9hAHAaYjp5LYJSkHMvZfbBU8-JSXaoySSd_C5JY
ut7ERQZ46vUSsr0fJLENSBwJATsuq4cbV9IXaqfvyDtff58UV7IIAKi1gbEoItLAIdLC3hv59UklItLA3hvEoS7NCIbLAZbDDKf2bKnARK7f1G
}

