sprite $image262 [176x129/16z] {
r9W54Xim30Hb49ta_p-tZ6bTYjnnTYW3uRLEPpf3w_HAAA3qCap7UvXUWkxuX8_NKE4hrkXk60_8xIeyufCkfHaUk5eAmHQzSuRjyNcd2dkytwd27hrKXJry
XGgE3LTAeTXmvMnZnzyY5yJPXhjcMrDik58AneOhfHYE3JTAqGnFu-scEBieyAQZ2ESxLBWey1J5QBjJXJryDixgyN612XM1LnzdhWPtTJoB_9SuywuJGxX2
YdbqXar1f4zI6SG0OBrGYleu4o2IHMWGHsQeYrfTuDNFi8X0iX5Hh1N9pOXwZHJrSMOUYGWCQbq44V3HgBEN15xz39EEG60GGHS7mjeWObIW1-9CUc3588Re
32mCchHueWGkZpEFp11Y0KrahlSFBGo0MqdW5STPh9Nm2LQQaIjyOkYd1N7M15vjEyjOAKP4Qwr8CsiEE3TwHpSK8BMRJG2ZKniU2Gnp0D9A-uVFofKyR8nc
iaOWVznZXzT8KTdELCTIGU0zralk9XxHsfKy3OZy-L_7g96Yi9q50ci5f1tSxhqN5lN8JF3X1LyBsraW08p3TO-VktT-99Vti-NVU-sVboaxmyuqF7OyHMJm
jadL8BL7EHRwxfgu1f-rBvXh4qYpjFOpgeYTnjrG9eKwweYCUVJOkLd0KKSkz8EZEDqYmh6XGEFAKPpvjbZxm9KKYg4WEcGSsFzo9qVFRzHNgeUz0KheoCGV
lKAnm1Y-0xBCFxtXD6Fw3YZoxruUXS_eAiuilNpnCL6hs38_wWsd6IEhs29Vz4QuiumNO1LdlkxLKUXtcejf5Evxmsd6yYgk5EvxUSQRjeehXVjU7aLS_pEU
JQsjlGypdWuHRkrzdF5gzt2rNdwtvIQiuaozTppZ_Ow2tikZiAaW5YYKNW45zTo_XK2Xz0eeeEV-sJC42gLNA6QU-uyh1GfABy_udBRC42XelJoAwn9gvLw-
M82hz_8e1BXwBt-A9GgrzuXeBhOKvloqkX3iraSXy-VbPe_6Okta_foJHy5JyBzkFcP7Y_dQ-gZzF6Dp3MuPaR4rm2s3C-RXrfa15FWEMs__qtZW5Ajmx-S0
YZ4AzjRl6W0AX49zXzp0683x76D3uFACURZFCpO7u8AChG4kpfY7gpFMKLWmS7d6PW850YxFs52uF6CtWG80bsHiZi0TprYZeCFb6SDmnpDcuOvdpC8TpvY5
Evun2tSyurwuEcCTRYzZ6MupOn5kEsCDRZzZ3Mu_OmrkFsC8BizOwpsOe_ACERWyOtklDm2up2p-Hky67f1dhC7jPwp1xMUimUrdhC7jPwp1xMUimUrdhC7j
Pwp1xMUimUrdF0hk5m
}

sprite $image262 [88x65/16z] {
jTM7ZYGX30HGGjDGPVZ_pxqmmREMci7Y-affOorwiht1drB2VqXgPCjtjyQJ1CWQRwqj8F5eneqOkP7W8xWF8rOIrDo5KQ2jd-Po7u4jHhwHm6AaVGBJUXT6
ngnMCOwDzR84Renz0jjynk3FOGby67u24BNLHdnlRibzOVWtjKdDkGXgSs2u2K2HbY87SgpRaw57LXjgxKYbGKey6hSnbE0TI2zdEGVoILJzrWB3CGLTpbYw
r8gM7z_zMWoYk2uCMFFPIE1G8oumyfp0_YJxZrSiBFGqpmYiXJaPosAKAO7zEM5s74w3uVfPK5hq7mx5A22-Fm7o4oDXLVmupOPW_cGUVWiIR1JVGUn8sdmi
aRjGH7zgWV5WMuyoA7tyxVtRJ5VpOfIrzTthRAOmBqOPxAFtJw_GoQntAxRBlpn6Dxrk36NMKRO4NNirlYT_c3FisBvRRQ-_kUFDN0tiwBDUFtFK1ni2q-j-
ibtjsBf-ggspNZypHG13iEZrOX26m4HQ5zbyiY4m6GFXu6Qp8R2r_NpyQvE-Xm5UFxR5ztcIgsos8WLDXWF3GJ267C6aq8cXZvt2siGgucXsmTeavym1l6nb
3fCSAmnBO65B-98Ybyt0Wg1NI-1cnbS2fB1CmWH3Pyi3wsUU4fJWpkLg-s0tcBTWDVFLNYxj9lDYQNsvkA2EfNN6hhO3TelvNs5d5zG1kpLp3jWjPiVIRitS
uXhkCileDToVs922Exy1
}

