sprite $image278 [294x294/16z] {
xD2n0K0m002m0G3yVoqiW9ssoGcP_W00000000000000081sCxqXouwZzoUoFC-p_3XwVtAqATeRDGixPxOO9wy4uMDGI-ejVl-tFJ5s2A2X9MYDmu-dxhna
-rnTAYIHMU6F4XAPd5u-2d5YP75w-GYGTlLYzALCfbwpzbk9glh1ZEn0Ud4Qgu7quZGQWMJgPp9AI8_quZHOWMIBHOH_0YDO158-Z6ZIJof88Hr4DEi71LB4
aun4VuoF89z2T7zCOQ7aO7HdIcCuDMpoIAhtPmJPmUZ6PXhF3PiOkb-930i1kXZDkcjeHsO8kGyZqNiEMsHLPNGocgLoIn-fgZZM_a9wFn-HgWfx69KAuwr2
6qYF64aQbKA0snW9K8uOIPh5uRTkCcmJ8pqvRBPY-D0D66Ln3Pij39F6__ZAbaITHh8L_kW_RAJ8-Y7nCBALPqp_Ur_hyhlZguMjtKXoHk6lremcNHyIIZSZ
sMLWrhXcDEdgWTJNI7P-h_r4ArqtaO2riv7iO9erXdSgT54ZvOv6iiLXgqobmWMD5BiQoHROa6PTpabPFyNFXyHRI8bsTIqdaQgZR7ioAG1U_cv1ccFxcun4
fP5gkiYqHVas8wMmLaIgwngvBTyLsrXBRHOHlXYdST4avVdJnd5h95hBMcMliBZvfysVsYogIXdb8fnAI6uZ-PT_KLM4wIky-GjzVS3_318UCX8_BRLPL0bc
WhnCWB_c-aUG7Dl_hkK_bqQQKwlW90kt_vCksJcsASTF7f2GPLP3QXUfDN7w-oSJYuEJpqazfqr_2zSi7Y__O0pRIad-Sc9oS78vYG_4DZKmqc9ivkNVJcs9
uR6oA7iu-I41gqeVI3fhCpd0BSi_XdrbaJMdRyCKPaXTfatNAfRyUcgRGXMUCNqV9vWWIQTfqqAhLTzU_bKrXvg0Ll54_2rZzmL9dWDfVu0WbyF641eK-Tiv
VJtV2hNg2ADYWEpKpg5HQHtZ99yVNGOIDp8gmzlUQhECPCVuX8YVocd-mRWXwGCnDAOsIG6qAfmviJntkHidI4AjSXZ9tceJqqZr69S9jC79woH79FcDD2lO
giVuyWcqkvDoXqZIkf7g-zefcAh7-78VghEJiZ-IR2Er7v1W3BRgRPp-gYSbxD2It4QQbI4OikA9gLGtID4TIRQH3X-G94SybUfLkQbLFH8fKuFooNXw3gVn
o6jRtCz8jaJuT3nf_x4hGi8I-uq4sVxTUMw75ugd_pq94iFXr6PLX3ZLGl76KsTEHKeOwc0aQzX4LIK1gxAd5VZZoG_9RoGRanPNxX726U5ZJYSX8JMgtKZ9
C5ATqoJX7ksfJuo70FqX4JYMVnPTNIgxGZm5y3M0LYCTwXhwwEO4d-EKnS791ybl95jSG6AHq_6aZXZtGV8RoHRpruppduPvlen7LdLW2e3kIF8RoMvFIPXO
sBkdmdIM4qG_9F_IPiyTHo1L_vxA-Gk7pP2SHafaosu5BDvMO9QTNnL8sG6fiv7iLb14UUu7YIkGYBf2ehte99TOlUt9_Zd9TqAI5DonNMzFv-89p9as8VLj
06Jy5FrwS4-OHShsP9kPgHIhIOawGRADbAYJ-EjAYV2yGLUEdVrtsBXn_kIp83cCv98enpoVS3UENLeDBXScxM0bTXZ9YcrFUq8HQTzJoMicN4pozq32oj-F
kQENVelizcGt0AQbqA3K5P94-_IVLKN41ELlJwdM09Xt3cZGe8JTdagmbWQiN3rNzxSdZ7O3K5Kkh8JJjuIAbVoG9DPZcvKpgLA3C48OXm-D0NBAQ6zbLjjJ
t3peR79f7jJdGiBG5DlSDd9fV5ig_Fvm315tEMtRKpPRY4oKbgrhYRKxfBgHGfuZv40YnRUDlZunbcTtSnDWDjfJtZ6YFCgoyKcGC9YnBQhABDgQIFXMKlgZ
CUr4b6JSRK-uk42u4FFEut99oGz9OYMsFxy5SYkcL522nGIEcKgfAa7PdjR1EDS6fYAvBKuz867ruLjLuEiz3Jv7QO3bHsddW1D9LOhxF77pNKMXX784kA3a
WyIn7jkioWaWYIgrAByLYkkFZ5QmveIuxLX2w-2c-EWS-20biIbXqzC05xt6rWh9c78Sub33H5Aq9xEGoYwal6sNJaWSpMahRuyqAYo1g8fA2cyh9RizLSMy
MzMnV59nGBACb7PFqex6Tr3L2AYymPIDXnQnwTYxmQH7ASbZjHj9b22oCXtKiAB4AKHIN3NDGANirZglSkRonZfJMkWi9C7GqhP5Sa9LXvcYg2h5m2ffU1j6
c1H6EFs4BFkGe8GqwIGaZdPisu5Kry8tGvxlvmY6qPYvHawoknq5eYMbIMVk9qksJoZymYz2Om20YFf772epLnVl5gKeUfGIosDHW0IrsFOhVmtM5n6UESLs
Cp4p6OfbJVgKl9SwQAKOGdSZsMrWZgT9r6mciVVyObcJ5bOgT0WIcQSuFJMkCGqqSP85FIHJh0coIECjUrIR4dQoKgQ-6hPFl2YoOfV8baWCgD84YTIWDEb0
Ah5ZsfoOHYXs2gWYLX7LblSGk81KABTRAJjYspjqSKifj9rfr2611MbMEoKmZDHV77sKPjcGefYGPhLE77UBRKmH8APQ05DOG0dcnBKBzo79ZCHX9kmKspdC
__HSumJ3dfbI5qX95tetzQlDJCcQjlQDxLJi5HbYnZWyeXIwGCe594l43MO28xPLXRY9Kpvg2MRACGomJFCXSGz8M42ofSeLCn5OiQrA8JHjay2cBxPVnyaf
meTY9kxY9D8YawgOX2qpvKfiYtvWJFKjW6qAqn7nXsYM2n9m2QbEQSM9PIM6UcoB8W2hagraUEcvGbX1adBSwjfiXzPMDy2TBLKvrXRJFu8KJKWs9LN2qaon
jMrpqvvRk02a90QZEYLDyPDJYv7QGoB3E0p3vr4_puK9yBiXsGsW7PF4475XfhGVs_E4rOJZ-WYR6NFEoFygax06gMucWJ1naW-H4TkiIf0QLlyyL988OvZk
AYNy5aXKXrJ7nDFW8ej8CcDRbClLlxwbXliLQeZFWHIMOWDINPlxo0bJA9MArJ-0g1ovQnCjYE4Pa1mDmC24pU-wi0YI7gC4vgsks1-IqG0yb3ItRv9mFS6B
ysjh7iUdGaerI7vCkSlkBDWCXsT2obf0yb3IvD-In9nInYs9M7ba0Ugg71P25wHPnat0jBfJrdxJTen8n1W_FXn2gkqI34-4H1L8VanvaKF2ebpjaRE6F3_E
yzfg6OkxE4-4n0QayvXWSzrsfaI8P7F2iNBVA8VXao3Wn6dwS0Jafq42CI2vCPMnBSg8o2hSUcTxj8OCTfsMoQTbjaORaXyJb2L9cTXA9tWpwpPKyXhZbnT3
wWGf5P2SaWscLBqmLR__ZsRDpCPptuXqKh5e00OaLnzW2FdKnPV1SalUK8hMbmVqGq9LQ_VMZmdfb71OnvBffMJMJ71l0b35INvCGWUK8uG02LT3DwHAR0ts
TPFH2uaTZFfZYiFRSW-ISmI0X4obWZLImNq-YVu6uCTKhqX3fb8uEIrE1DDVejvppLBPqG2UZ0agcPl7zQOk9W28sNr6RaDABaZzCGtsDb6i_SinGGXVs32i
Y1vJSZI0fsEohXVLfmXXjQdBqq9GX9gl0VWX-J6DffU2lMxbLN50Eg_eQG3FnuJ6wbwz7J0OFZpR080BI5V0D1WT9vbUIiOZYwS1-27rnyJpnblcoa1ccrAg
lf9KRm0EI1vCodLEZ3aZS-M8OCYLHnRSluFERP2oEY1rnsGhXM7UnsKC-oUJiVxa9d_KqW3GXjHVSXfJ7XSt_6Qd4TUA9DJU8AelRXv8Vano158jQZACmuVJ
8YwV0WFMNaTJFlHug_B-7T9pc0OxQp1itCE4rNieCic_k5sWNpRT3i3Msm7CN7nucSNDpd0_9IY-QloFp7nWWzk8f8jCNV_R0QAI8egGeMWsWAjZ6Wopj59Y
qHm2aCh1lLi_93ycFhZbDAJJjmDOEKqUuORJMmFI1SB9h9KZP0DXVMzRb91LkHP980QaIq_TWoFRb3wXfS5sKla8PqTIT43gAZ7jL5SANmCOFa1nXd5gbILR
aSCd9Sc0T64xsQiUhAnMtgvJFdQX9Ai1wSeXRbS3iEOhXSHQRKcEnUsoKsVV3YZVZyhs3UdeMDokQgVwLblvNtP7LJOYoR6uNTXEQ5CgyrjKsOWan-9sPJl1
eUD_DdxdTCdSjZ6fd8Zl0Nk_UUE7r5-_zFZOSHxttpUHrjycXwN80UcgTcBA4MBA_0WIPIuvsTC6R42w9YUNH6LU_GrXj7FxYj8JOsUl_e0cRWoX_b1oTJkv
EUL85kqKxCNjifAkdCpHnNZftBQbFUE9sPusExTloed5i9yrRL4CI3VZ9AeYAeURP4W6f0jBJt4I5KHgu9H3FRVloubLQEB4zMcpS_lUd4GPaTN2XE39xUjp
uiQnKrLpskgvVNzER3wMH2EI34YNv-HwRh6dBU0D81MSl8KyXLj5air9sM6asqHIAUrWg1pMoWQaEt2QGI4r2sEuJIJPd1oEog4MIV9-4-aZCRU-Jc8_kDr8
f8ya5L88ZccxZw5iKgawRVf-F-cUH9ZhHafYHDBDG9ces30I6KQwdKHDYGZpraWGCwa1wPRI1Z5X_X0Ixt1zlxtKh_SVeHUZHZqJqWkKlFyylOpKg1UaLhqO
DQgLqKkjZ5vwCJhrn2Sl6Fzl3mu4000000JvMpz8jGq0000000000000002
}

