sprite $image308 [232x334/16z] {
tDK7gKHH40L1CZV1yw_sXytjOAboq726kRxN_7VnveDVwOVEaZDBhYouikJAaZDBhYouikJCaYiBhYovikJCaYiBhYmvi-JAaYiBhYmvi-JAWYjBhYmvi-JA
WYjBpYovikJAWYjBpYovikJAWZDBhYovik3AaZDBhYouijZAMcfcxMDMrZhd-9LhdtIoaxtXAn_umtom3_FDdkoREzboAqlAx66MUvZbJhRSNrBkPCkTRBcL
vVwISW-ptCcM-qlAdMovaostijp3BFSmovrikPCjTxBbLfPxcEKUPhcJBNUofLUsiup3BFSmovrikR-atCcMETbgvrviPJltMj9Xrdko-y_o3lENMplHSPLN
WW2CMUskakxxl-rLvaUPEccIrWbWE6ujisYRJwx27fDrf9XsBwdnoD7dZna0isOYgxCgxoO53nv1INXRKv9k-UnogP5dEBUbPcqKKvt0PdYjZSYg4pUfgP7d
EczHKmFFTofAQzg0KfpNrnHa1UVLDJModlEoFSR0IivBQmgobZEkQON8rdFMhwcHrPtrQsfWVMVzceAixgmVNYClTTOv2XfuWRDwJK5UxQnm53Jo6cVLcXfv
ZRDgU0sys5bbZm5veRDMJOqNpV_C87DkJGsyQcoDOOsQWjSD8D9JQmfUEUkVQZjgUkTYglD7UcvD3Ro34pYtfY1luTmJtbXgv5sSiJGExssLwjnNKnFfXSMq
PPxd4ZkFtsCgAZ6bxcUIXSxzUunT5DaoTCz95Zltr_IAo6BiT8QFJkBGFGQiDalg_XnyT9B7rTHORJ1qhxC4JlAWchBUMEhSJB7J30SS1QzbTaFWn9gzRsgg
J5p8Z9tF2DhtDJLId5MPGtf-1xhPB9hPTpKriAeJlxJyt5rI-OlF9tnLKv1rdVsgxF-ZuQ6SkJc-Pr-7bwpid5uVhqCtWe7JIpMyTtIMbPd9TRAHWJC8Rx4R
EKlFnwIDGq7iZ6jw4oV6xiUv-3qaTkweQLqdvaSXPJdnXJEiwUNEdDP6Cg-FMkvmnZMjxzJ_Cl6xfypKANcUCo9dB5s_lSgPVjSGtQlJba7scTWPr_Gg9yIH
rKJaKG-wO-1qqY2ybPrPDinn_Jxbign6cH8uT-mnPpl51f93zsb6xmoWGKshEdjvnAQFpZvm_iqUOxMTMazsdoTmxgcfEi-jvmdEeAPLdPFKa-a4Px37L71g
FHCVCnphZ6jweXFKWJvBkNnafY-SuL7m96Vfn_Vr9DAVi34NueaVTZY3e-31Jeolgp9hFSciHhnKU0wSEsgwuioES69EUbEWZNpYxN4C6gOCpK1y7jfVKv8u
vfuwfurZZTGpsdeI0-UkFORu0NElqmPzdFZReFXaE0NEdJLTtvBjSMhp5ANrZEzp4JXtrNHLxdSYkVEug-VspE-Z3UoKsk_lo7rEJPzJnVMaVLXoV3dcdA1p
xW-klHgME0SJ3tJ2x3Gdat-JkGXSxekAIFer0zZfzDB0UMHmHrzFZBfHbYHxvqwdbmREuu8hEweU9IQvrlqOREmREyFfW-lhcPE6D2TvGf_XX1tWn3Aanp6r
R0RNrrC_Uz7dKYRTY4vo0ZkT-X6d0Pl1zVKitVOCk9bJbJ8zV72twedWckzkJepkBzqCBbxhkScSUKydPd_BKrmmJN9iNAVtofHvJsTEsz7pmVMxvnHKypvE
6xhDmIiaRUsU5YxczKujff_i8EPUZha5dS5REdqn9QO-k5dAwp-zc4HvAsSHfPk1BhZFxwcJ-_KIZEGTdHWwdJJbakLNYJwu_PlRob8eSoidfitdXzILBhXZ
i3_UqJcyAFrToVkje_oZpWbypkASvfpyvvn-OuVN9FU4-WUTgL16LNw9WthUsUaNPt1Ek7gsu1p5kNrOvxsS-CuvUyxYwjcGS-2RuCvDEdrmSrlEcM-2YpQS
uyQoGPWzst0EUZNYWzkN1fn2IjHPv23SY7FpQX9oNT20Koxu5j_Q4MGppcdxgPhb8Do4Cst_6fbimHb_cgGXfrn4escdND2sxHnaEHjsPbdEXfsMP3dRTIB9
mxPT9tfFRysfBriI6dPYalk2TfqvoVLFiyxIw_lwLfqOEsKswkpdpZ4RS_fPsBHJNocrxnn1jkzCcMpVcMQoOQT6jdtdKCY6dLhCzfqpsBPJYjcwioza-ywq
a6pVEO5a-yx_jtSdkxN3C0n0ryynmF__siujtyJUKaWGnf5MZNS7i2gnmusbp7ScLJlRsSvsjhETxMndEzlPpdQsivtjR6SxsubRE85RE26SSoad89rp6wiu
0MZdnWzQlBWJtpdvaP8NTuBruAFvhkm4X9Fr2HtNTGBQoHgKNjC9uTJIApe1xTHItvcbrFFJRrFYyfZQESOGRHhl11uvMQHHUWqdL3tiIxvTCTy96Cv_Q6pJ
S2TC9scYJIETWE4aL4XJdK39-I-DxaGdAivPkxnqPYaVv-oXf55EeEeSf0bfZXCeEx-ZqPtXHDr9cjUcTCOf0Nzyyl5i9uoonwUMqXcYz7EsNWLFSs879orE
cz8PfzGvkz2cT0OetPnjp1Ww8vX-pjOqFdxgA4vI-ZbRt-LNtSTfd19uC3wTDftRvsc0qilPJfj-dXxenAvEX_RlYr0ddJ7AUixMbvVE36KzP-jLSEDSIM7M
SxQMSdwcAFsS_OEx_CNS0fHEpZRRb7-E5AS4TliEzAhRFaw3cFMShVSbRaOnodhErgiWpvAKsbdVSlawrm3bpZcRZtoTQm3pi9mzxDUvrfK9EPjVXIYrSvoT
it6yKzECd1sWZC_PEAfsozc_cBEJbAoSd8rZAo1dKtc2j9gpGvN-vJqWPmC8a7evErMfeVMSNLUcj-cSu-CqLgcbn-Tid5JbCCgZOAM6MZcRyxEkp6zJpiyw
CxzDtVa980zgvsnVcNzv_PmDLhwqdhC194lzdEqhyzkKXsLb_kNLFwVsbVcNbp-dpcVMLy71-LbNvhVfd7JMbVbjolbfCEEbPiu6S5Mepjc-Cb-gSxQlp9Uo
NWyEO2QrwVjeeREep6_JmJt1L-PBzU-p0Ima5Ni2bMj9wQHoHIYTLAuedLzGCjUJqea5wovEtCK9tCH9APbhGwbSMqhbsj9evZC
}

