sprite $image199 [36x288/16z] {
xT97SaGX48FXjMantF-svk5oro3qWdCO_HlILxsYzSfTJLOeIJXfE46-pSHAWWrMXCLW8SBCamBI39L26UgHJ0iMKHPJWeamfSH4jEbgiDY0DDI361iR6niR
6niR6niR6niR6niR6niR6nkRs-tOp3vMGbU79b48n5qoZ4APMSMEIPPR9Xo228H1p0GG1f5g7EkYCBhVrnxOP6b8QJCKZWmfQKW94p4hI1CWfGmhROvLZTTs
KKspZ4gH9XL7PbS59Gq7QHYnWZAp0bQ56RqSSFuFIKb3IffKE3Ifj0bIqWGhPSvL41AgjZXJDSskgjqaKggEMg-KH5oQfrxPQktGZ1eXRNguOa0AoamAa2RL
1hIPObFsJQ9sOB8lC3OsDZOsJHAEYAxCuXa
}

