sprite $image225 [264x192/16z] {
vDX5bWKn34DHKmpxNt0pave-HNTUm-Zvb9nSJAdGyvuRAToqva48iJNFseHKp2kaCs4rxonXepaVSkudyQoCgvMVIwLf9H1280Th9ni6qfcmdczBvMWb5XnF
0cldQ2LMkjqH_Kj9qaeiE8O1Q-De9LQwqn5D_3ZM_1kNY-Npdye8MhdjgQqv1n0ShSJQDpYYoMP2QmugILg91SSmOEqShSHAELg9BP8dWGL7Ax4sWbPUugcT
0zIAhDxwSU1Xg52vfnvPyy_y8duuTUYxBo9hgrCR3qEwVCAYDfg9QshDB3ro60J2aInRCb3tF-xigxwemtJXniDhzZzGGA7skCMlVhru5kssXbFtrUrs_E-Z
Tkr1cLhsyH-FsWVxAyMZE5A4WMzbyIXQnX3DSuZNYb7lD4HBUvfmZvE9VCF9SDQyxNs_pN560Gn2V4QCJEGRJcA0xM_kQ2MsF7gzY-6a07HpiTrF0sP9gKV8
g9rlE8a1ECi7PDjG_8onXGf5I-YLQn8FPflV34pL041QA8djBeQJ6c3jNGPTVZ6GtzHWHmaaqUjTZZCAOCxGxPWO_0XH0u0HIU8e2SAmB0wSHzk-HJlEtmna
zTbRu56aXHfE78avp5HMdwqJ2TeB7rjmh-H9h1bCvJ6JQDcZTZjZGaI_XOXNNwVHd9I9Envdt2H6YIlFTiFZpDYt-ZNQyH698outHsKCf_WujZBzRUxfe_GG
cSY_slQz_ije8ZhBH7lnHbx7bOdWBpyn03smLhTSOUYjEAYlI6YBUtVKQrP9Z6EZVgG2EF-azfhZr_QgHF3BnAoN_NgxglRGzXXKZ6f0Tq2ZH-tu5qv7A-pK
Dgj4zIKjBnFjilR8AvCQy4VRAzSTlxOHsHx3XpUnl-MIB-16z4f25McPK42g0mGZ4tj48bnjX8h1jdNkyADsIqq4lqo80Irs0zeTlPAUa-BD7mLwy2hOY5v9
j4VoSAR04GnYLBOaMi8XLIpU7EXb91oMIPceLxWaAWdfGCd4_4CZ-hsOAaEYlkw-lXu3Eqy1K2L8g1slVeustiaQjYG0G1aG2kZ5jJ7_kyj2KTdRYYf3Ol8F
BudjOrjjPoa0gXG9CG3ZMX0hSU0bGXJ0p47rQQAnCh4k_xx-d6T23HC7kZYqlK8eIwHp8WPC7EZYk50c6boU-o0eJ1nO4lsI0S9iCRrIFKCnXJf040y5wJ38
F3dm2Q66XnnucOZUm0KoLGMV46A0WmCf4w5h-82wP_X1K9Wut4qcTfX_bsdUad1mO43Cfte-6kmVbjlYJWOd1rucP0jg5N_z2ev5n4t1po5V9WH__VmFqypV
A_qSU187lLP0fp_Z8OWgVc7mSyYNYG6Tw0AZh34OvCEI83XG6_b6QkGCOhtGDOCvA10Sk8tyMPcei4TFO-Ou07K80y4XPoClxsUvBB9i0Ef81e83BnFQY5RX
ytq440S5WWDT7CyPTmFgpx9gC76K1CaXmRWxOFuiQrXZK0F1WGF1oqI3kNsVSWBcA0cUGwXnvn-d7IIa3m6W7WeyXvSRTmhnRqmmMR8Fuf2qaGlKtunCXKW6
WWDht36jWZ6SU0wlDUvs64r1WKWE6HlvncDG0yaXNoQgcV0b4SmXOICNI085aaEySNUI6ga0po5V9ZgC50OYb8mppBXhCBOaU0xvCb5XaaO142KYqhWpGYCL
TBnr9IBEk1D8NZ9yKwiwb0XwrEvVSg8qXMPH-3tajeJYc3NUaahYxwLdpo8XIc5G0nUpLrRoP4BDLDA4eRvDKSya48doE9jagJAH9Wph4-oHK1n9oV3urbQ6
yd5_2eud6lN-nI6HlNAEZ1wQqolzJxWIUcX2htH4mgYTq2iziTsoE1HSU0wCzvS93UcLdaWOjJDxPO9Cf5CWtgt5ZjhvlPAAFR0uSWsdAV9a8jTmugD-hjQC
YY26eI3qtIR-zSO4CopnS6-1gs3ambOA6oe49-1XHguS1k0duHYvlvM2aGl1gN8c-E34FsH3ArlfepOQdFZ76xc_bVwPy8FJ1chRmMaIjNs8zetStqhVo8NW
j7qcVdahVTGMWjFeXch1QSt8fQsSCt9XAoTH6ztAy9aGjdBIo8NWD6daGd2QH6reA_DdGWXEawZTt4hUo9dWr3yJGd2QD781eYTHkxcLl94p4DtVqEPMyaOE
1wSiQWl1QTB8cQtidmbkAzkepK1q_qmmMzb7RIOuzL6R2KxzCm5lPTR8cU3KFnFCLlPHczlAjf5JmQbkvCpNm7tKRcub_-SN4vpwgCriPT_8cU3KFnDCSEgZ
DhEL_JE11AS-Qby4elj6VX68xf-9En2S7W
}

sprite $image225 [132x96/16z] {
nPU7jkCW44E3JHt4_t_kLhQOn8XdfUZKhKzdvagCRwBsdDpjetAn_53uf8LGhFoGPVyf1tksqcLf-uI3BLdv9olHVG04AmVPkx7mtS51blTFWD3rTYnS6Xm8
M4XvdBZmBmTXN8E0XP17Aew5daSkAy6z9uyg5deUPInq4BZCdfbJD-JHrh5uJHxDSagP624BaT_7_TTeTXzJAVQEdBfezly8_FyhTdj8R1vwVHz1YDi3atii
PejOw7ayNMstmR7Gy-WdA_Ef6CT2BsQKRMOv5ADOwCMCbjm3859qVHZPM7thnMmDOIG1hJKKFrI9YeMBLivKc-r_Xl_hvwDQAOPMmu8BwrYeXr9jjUISI-q_
lwisHCV-VS-f_ZvQnKzLizwJ_xaWSnm-ojJtqKgE8SHyTD4ticKZEPKF9REImdQOsuXBOA-wSYYPbHntT_hFQijkOHGbJ42W0_3RV7m6_5vuPFKz0O4CW6DK
M-u3Og_w98za07oAgDkltrnzrNcxMSbX_rgjLFZVK30NdgsXHz2xhxzorkAltyj6Zxr-A9qhRXTVUyFssyJ2iMVpDhbyzLYVibi8MwrJ4-7hrzylMVmx75hz
hKvDME-zBoZPC41Fdi3MQfsxGE-zPGKhF-G6LoSojEvXwiA0k6oWx_yuF3Tpq3rG5wtwPG-btbCKx0I4hZgO8DSJKqRV11r4HHiyF0cBYD8za45OTp1wqB7m
68BPvMtYOFHGJS5YG__NI4SBzIwF4myCYpAjRgiFxSPc0mZ4Wu15gG_jvcR36eW70Ok4HnzbpZ3aaNlW2pd18k2E7qGVWM4Dn8E2nOwJjs2o1kA1OP766fhy
zOa3ue7KDy9z9CZxUCd3Udrd40Tet8E6HGHRmqHe5PTT67eVUf13QIAWjIrNfcbz1tVpiCjhG6jb_v6g0cKXGBFhQ_XRDi445rOlEq3xhtHT4h0GGCY7hjio
DV7GXGB2_Mtchon4007XuQiZBsGTXB7i_yUYItHH6ylZv1PQoAaE0hi9TImu2F565JaMKXxTRK7hzQtdKSBYMZ67HGDNwviNyv17AhU0XPv7ZWKu5deUTIo4
F5AjrxUQHowNAbLJywXZWUVaKQflF2EFGdtFF60vZpeMa47GSuh5G-cLM80SIbnwVOCKiox-gaCkPXqBJ3vSDAs_wfXykAn9nm9o7dKi8ETHpodaFEglEkGy
wlKDEO_wgmvoABq32pJfKD8LQuMOHrqkwuVITm
}

