sprite $image395 [354x246/16z] {
xDPPRXXD30FXvw84-Fwd_VSrdSJjXR16ODrWFWZiUNbc_AINPC1rCaVNhnnUFt9u_SZnlJSEu6Vw1ld2XFSMuoiLFgtm-ekllVZwYw-z-DeBiBq0smkmlG3R
2x2x08SumW4UHHpX08SumX6ES8WZ7E48AyBcAiBcMdYBS76P07-rJxWrILWl2uKhmaEEMC9VRHI-9LPXJxrH-9PO9TvJX6-9rR83rrhXresmdLYzLxXB5vzV
Rk2TmjV4RJvYrLRXM-Cs4rTl5pwDJ-6I4tY_S7T9Fn5s4bSl5hv4BYTnzMBXiohfnmZoF7BxXK_cAkalQad_AfGimFk5xojvWIFSBHby8smvOrL7s61y-4RO
O7puHlYifFVpdhuTuRCglVzy8-n2LXs-4NuLMUyVXmZVA-iLtEDu8_m-P-aRsSCsmf-3NGThXB-m24SumX6ES8GZ7E48HpZ2-oB2teYmDK0HzWKHjlj2HTWK
HDZl6s6_BtI4lS2AiD4tmdvVg0WxVIFi1rP7sESRORylL8ITlX7s0zCHjlgY23jz8-m7fY9izOMEiDKNHTZg2-eGMu6f21jyXmlN9b_Kyn8i09uiN01BVA6c
2iCAN-Y9yMSRV55FJ8msPf4mFDmNgYTMCDMOjzRpXNaqi9uW38_rXUgPYO76i5aO7kcBUgpmD6AM2HUCCkQzrM3XGSQmJxWrXvWFf9uiFCIOfS858upvMFLC
ONY8B_JWy1FxWTM34sPZlo_KauN1xRjTk7Wzjs-4CGBl5svnazitmZ3N5zIJAxw4c0XRZVdaUdJYFgDlXlYlhBwP2G03SFw8Fz4OKth4JFYDyQNvmdvZhDNq
cV0JuqsrJ1WClck9XTqO5XBxXS4Wl9AuM49CpHNUOgoUcV0QPuo5bpZ6nL5UF8DmZ8s960yGDixnVkG2DfpnYLnpX9SQ8zK8Ph7E-7IkcYti9_PN0sPYjR7w
2uC1ngk51VkDgx-mOZ-nUe6mmNYBS8lrnhLFc9Vhs2zSM1f4h7wsiCOR_zhEVUWypYfX77ye1gRS__MUpmpUR7CKBUR8LkQ_lU_x4o8O4_EpBvn5Rp-EvSd2
h2ePxudzP9jCZOuM4DTEnyyNrXbX0f2lFHxamZnqcKYr0AZN29kn2xCeDPk0jwAQ05pZQyGkBAgS8eig1IHL0F4QN-kxXRa35o2oQWO05G3vAc3hUzSIh4oj
0oDIKUnH0r3dVDSRooE4kI_CiWa7mCRmjW6uqjVwHc6xie09xobXfqv0lDRN-hwhPbRjO_OGZg81LhuQsFfIuJQ0Ax5MMFLwN-kxTYzP6SYi18prcGgi5RxM
TztZO4bCSNi9YsRifMdWzSRyW3kXhBgBvfR246PjsDjM-LfVSpT_pCFPBfC3_PVz3DgyxtfYVi2Pdr-4KTDklXds4vvhnJSUmYp2lmhtMEsx-JsmF_jEpbn_
-AfosSeVmgeK0M2vh_NOUKBuT8Uo_jX9Czf3EACtgDjxNtz49f_ugaGOS44l366ndmYj2uS3-0d6V1DWSxKD7L7DiE8GPYcsGXEEo8VlCupvBi0qngcj5gmn
3tVJNAXN3j_76CjTNkLCEBCg0KYKDg6NyD7mVHGntsIT9fAHMXNL00JR6Ov3-7DWVsmyqsbIcoIejZ6KDGCcNETzvtl6earEWPd72gB3eXXqKWRo3Nnx2udN
0uioTU0nQfj1LwBKxW1itVxrJjxzymLamcp2F3RJpdrz67y-W5cruH0cxBPRTpxnVQhn_nkOXOz_jrRy8corzxu-ZD_xagXIolsR0Bo4zGsm6t_kowfQW4og
6HPtOHxRQEcjhnk_zpNXODSIGpImbh4lcH1I_TJNZONVtH-AA2OSI8QmTMDVwoQFeH3pFHV68LmFuIS0MpVOcXTcEaiEuMh2T0XF-3xCc6KTxskJFLJjml4G
pa_njMWMMVvHrtZVD82HwINC6HENo8ya7ifNwpB_LPYercVvMZGV6_DdkFp93DyQSqb_23_Hzp2-olb4MZwnFNnf5qsiUYPiljzeF6B-DVeysrRljI7SIBlu
Ou4jkaC6764LrV4TYGZr4bytVW67meTmfhHTu-l6unn4pjYOJFZIkvnEhDh6iHBbMePmR5Vvkl7OJIDHbOGY6guvQEt6OmLCOhVUMBNOzdg9CxvkpF9ZzfMy
qqgNZGDwSfFIYLbKQpRWylCsPHgtwUTytTW6Rlpb76NemcZR1UyaScFL2Y0Um9qMNTYmPu3Tc8MEpGOsQTByYt2Oy7NYFW778MmtCfhadRLqxSbDTZSUAuSX
RAzo6_QlsiOK0AJsxxvkp6gcGpYfmigyzQ7RwiG4uSIxRmluMVXuF_B-qsrk1Up6R6_HwkL3k8wju33zJW4t5bNTS6pc7CAb2qkSNg2vyLYNmTxizekmrUQ0
dPYLq2kgDHp2fcxiSxvkV0ZROcq8Hn7CdwDqur-52_0I9YwxRtNWtYN20Ry8_rSbzpswGXXlZvbubmWdPfApOoRUj70arHQf2sz_0_RcX8kTwYaSJyzHUbF2
O-SdKwxdljw4S0jhZfcuiGaVvSjzdNW8hph6uyOluHNdADtOX9TE46uyXDCgNoTcRKidO3Tchg4izNNZYHMmjzpNM-_hhGVsrljwotszzRxUUc1lkQ-ttjTR
3-ojz_MM-thhVRrR0_yF
}

