sprite $image71 [220x160/16z] {
t9gBOfow3aNzDjgoq___spjad1ioXjcumobardcsTHuhaemby-VV0RdnvnsH1jxE3BBWZTK47s-KZZrl5BCtjPCjmdi6hV46PkzebuM3zmnQGzze2-bvWvYz
YPsCWlSqQuGtICSiM_pse2Lht4JiVgVPvCrCa2q-Vcqw1jEmKJR0HSjEQ3f-utvLsMMoXJZp4xzLTi2lAxIUC6qk_qNf6ArPmwRhFyf12sqBbozkXw52-pLb
nmij64QyQkYK5Xh7fYi-3oQwx--27CEklUzpmhNiX1-mblXabYnYIevXCbttWDMoheXPWf8Vbv2dtMNK7dSBhMKoIwHKZG-hiX2x4ynOiGNKeiXcIOQMYi1B
hd6TEO-MCZbpnyqXWiY3cmXA_R6gGCws4yxz-qxtH2krGAHtQwkoNQnw2YupdDDIDPXOQb6H3JU1VfPTr5eKmW2kCi62rbfgLSYsMx_ghDX1na1Bj5MtRjMP
OzeF6GOG8Mupfm-XvGM8sp17crt9JQOZp_idk_KS5xJhkGbEs1qtISHjc4kOJIbwsxKy1zXzd5neALYpWOkJS99bZUlnGSj9A8dqtbmlkzQu7ci7riIuvtPJ
j6O7FkzebLm-qWvx1bX-Oajssl5FuOzBJ582jAFCrWmGLeFcZfuNSRFi-NGn60gV9oIt-_v0ZYcqmAVUapF3f9KsujxU7dbjDpZ0maurwsFAEQSOtBxPEUxj
RUE8iXkR5A_E0jpQTe5IloXbTQD9g-qjFFaPx3w6ZKsArsS1ljygC1lTq1kbp9Pb9RXvlRsTB2axRiVt_STOoEei87KnGwr5yRqIqDAcG3-m6tENqXL27hKB
WuMsCGkmZy6Trs6jcE0Ub-OL9W4cDtv_CBxlDsngwKZ35hUc8T2gpWp3xm_mshvlhDlYCRnFHgeeOluUbtQsvGCtX6D8KzkG2sQCyUS11lRzCQn2dg3Pl0Jf
3qRs_N4Sv1bu8Id9zGX06-jeNi8E3556yIWgJy14t81WNY4FtAuEOQVAvj5GW5nPo2jfwPzdl7rO7LVfZw0sbLgKc1LL1HlgatFzmFcU7C-qhgAnFyGL1J6h
LMy0P9Kc-zXlOGEnMt8y8qDPGxkRSIaq7KkzeRhB3g4_9w-JjvfgtWhXcoSTQkPcMkgtsux4bAuBnYh5xthnP-ftu5m6UWzYrjnss-LTpOPgNvqsvCVpgUqM
XGAQjHwbAa_7pcr7sSKTBokXm6wrtTEDdDORRr-KzHvssbTelHktgrKzFngWm9bXGYaWzPYucTRQk_rzsSMLPUhD8F51hTz5ma2XTMu3PKVo4kLX4SD9xTMW
9Tl5YZs5Hjp6oivch7yPSbRh6bqy-r8s3wHZvpPc9twn8sFzAnNPPsVZvY43MgluWNsVk-qxXf6Zpxm8oT5ip5fhmTCAHoq3wKZSc1rGQac-sv7x7sMH-4JF
9vIx6Vait8ouZIOcBm6KKclHANhRF-xIfAMIYCn0-G6Bk8qdPbai85-uw0-vW3Q0BO2yI6VMkH4x0lLxS4kVNiEVdQSZT-E9ESuFjtZGvuNMfoW1EDujo3Yy
q7gKWckweLI6xW3dk74pxiO1pdBZwSZTkDr9RjoCknsVc6dQuvRo0Ub8t8wsosxfWCwjMtMS6NVZYScl4MnwwjPMcNZ04usu7MSNk-lRpgrRDLne71s4oFKZ
73-jksNNh-BfUAGR3nsVgSOLj-pxHJnemsw7so7tBoizXBARbWi6p8vrGyP0zzFV7_oKjIllFEX0EXxiPbtUtvRhu2Yer08Cc1tjPeoNBZ7989D0veui7Jb_
zhhTY1YoozPG7DZSSTECgztOxMPiqWNqUogHcF41FrunczdfDkDnODdHYrre_KiMhzVlTElbw1wmVP_iCLXeuq5hx71B_bxxZTVAph5q10umQt2tIREvaVM1
iMkxdGF-eymQt4sJCSQfZjdL0aykTezEnnvGD_NjlwE9kImxB-M_s_UtARgEcEQKMyLDmKSPISoI_js-p-rwj_O_TbQSyKDs6iY-Vu0PWxePm9exUQJiglZm
7nSQPyCjVlsFJEQBDFQqgoUa8qjCQNtN_PmnPVD_yj3pu00pSWmP3nrYsmZCp9Jk_UJy7miTi3iZ7RdTyfqv-NGJrNpFLDdR_PnanfzssPc6vg-0kS__fe7k
vvn2uucPREicvSijVLPS6kX-3ZOhH66axEnd9m3Rt11drNG__1AxazEHsocWDy9SRwqE_Ums4tZPdP-E_5a-jSVT39fRFtIuf1a_XdbZhAZAfqnQz2vZYGaz
pwon7ZWd6cn6SulMp40xkrCBZVFHoSKvIkw-XzoVuOWhRWfSBXtvdX9Cmo7T3sGw-TvD5SJiLBN6bjnodymEseEhfIEtQqfPq-BLytst8oUOCT0_octwiK-A
heFJ2usZQwHFAtyFuXOuVT_dRBb1isrk6-1wXSRjqbUnHPl9fIIkPSRjnBKRUHNHvvnkni5wz-EPMdcfapahTA4xBHEtwmIDsxKNOJ9nkwGPxm-ovMwNLUDj
ENMxSA7niZlKxS_9w0ZbVztFnG43GHH3iVFWwx_QC7CMxQyEv3G3yamt9CnnGyRKDvJaIM-8cUw6e6bkQEhZRmWRT-j86tD3tj0R5eRSS57_lc7alnjcVh_X
9_zumrBzuOQjRpUiVRhXhh-xLG9uVIE8vnjnz8SReTpSAk6SRuIqlx6WBG
}

