sprite $image237 [191x233/16z] {
rDY7UUmm30JX5vomaCJ-kxKkhWC_E9kSlu81XJk5zhFYe4750NM0XmXZ7hs96C-y08ekqD9J1zYY8iRUC2_0VHXkW3zXl07Y_HBmVrDY7hq9y6TP4lFaBG5_
bYNeqHiptkx7FY5ydG3_z2NctjW3Czx4Z3V0BxQs8O_Un8mtCVV61ZzPVXtpw4tCU8F6smPO-XBWpxB6t1k37hqnuqtGU6FM6pJUeF46-BEi3RZ9ZkYFQK7Z
3R3q9PKVpW1ka4Tl8iRNtnI3HSK_FKAp-o0g_cyu6nHSw7Zb3Jb-MHHKkUmo5KHQbeFSIS2zSVvEl7Zd7qYafNU-2RJqpZUHziRv9iJUMBuamDuK-Ib1uW-o
Gu2bTpvX0CTN-QRPzwREJyswDtM-QTfuouectHlBaZHflFDhcdLld5_JfF5r_jt3s06ql8UKVG__xjslkOxUKg7iKgHfgZ_BPyiZTI_1k7U1AdvTL-NBtUyD
i6xhkWmOG6LyBxzx2VRu5nD8W_TcxURthy1oA3zCiEILnkvDaVzoWCX3_-yEeCVcxKIvSPm70h1yMs2t_FvF-n-hiSkTC32Oraw9UzQL-X0sI4YboV4vNmku
dcQGwpRGBC37Wn_vMa3SRWrFDqauBU27Fk7haXPuiIL2yTT3N-Th2s1XymhmSrFdQm6w0U12emNStDJvMW3uLCDf0H-VytMf7zq2_iPXESxN3T0EQ4Q2R7oT
l-AYim7Dk0MitDJvkWDvWk9VmljyJH19-Tza0_pSkFmyGKWIPED1WrzDq48fSilSEFoy098mDi37At-LZMq0vJwJ0lpGZ_7bEMiqGRe1BVnV_IXVsnCezl3o
6aJ57oP-cA-FkY07Tm1aEr-Zk04sFd_M9Kbyyci18EVpJH9aXxxELnr8BeK2f8d95feoCpVvmlppiswZ592smEindYoyrDq8ppOdvtuy2sZL7LWMWcWV2eYj
yA6_XmuEhBU0leXG__PunDSVrTMXiW6w4dzicfk4hoq050kuTMlPFFIT7yMkxTK2QG4lzFLu_sa3jizDpjS45Pycvxdr_TlYw_nw3sThwz3dVECGhUlzmrBv
TW45lf-RSRwVe2tnTRxgMcKGAlBzqDVvcY1Yl0Ms3FquNmi0CTe2y7FZyRK5C9YWORtY6ro-5e317eOk8_Hbljy2Fbz3x_Er1LA_oTVG-tpZQJBdrqFly_KM
gBO0T1cXz_dQ0fKveixNtBXyVuuOv2lUv_ijCCulXDxarr-eH0poMmZUu_ktGCJAVpFvkV7vcY0GYHze8NmRx_ErW7m3GbJ6OMdmqnP81w60h16yp_Tl0UXA
S-Fp_KEqpjS9mUVx1OppDJS-txy5wdnzw-Vp_HP0WQ-XtmLV4vJp_T2tbl3j0ZA-7tgIyICVVeAOyFtGC-MJ-BD-MK3AjqDFVk8lb9ID9oZXcw4d2_n52i1u
0GdV2JrOuvi5HCHFV2_qDRxupG9Ku8K-_o16-Lf0Na7zMRTveU__zcCEuLi5g1-w77mIdfWZUdnh0xRYC-NhbmhAfxK1c_39dAyDH-LREx2-EOXmyNCK-6i1
82byPmSYqA9vU4ISJX_v-l0jVAE5lP5unRTsEU8ZNmiGld46kVYvWRWUei3NHwSddzOXwk3vpCBzS2_nTV1zyOrxs0jzmwezNefyRG4iAtzi0to-uCbsFbJv
U2iWvyFavxcPNtWIrwaL-IJU3cqIb6jWrF_xq3_rQ_ZdCfzyRm7b3mV8pSswvkDrWC-t126_nGfy6q-sqwd8XxvlUh-6YKNu5VylGX_WruNBLE1h0Ng8llZV
ClIHJ_uYzBhkKtpaQm7arpbY_MUzXycQVyMCvqRNV9vk-X6myli5Q8A4loovNt-GXs-Nm_H-zBJeyFCMQ2I5BmMuV0szBjmEqtH5vysey4ijiFBb8ilzhF3N
qFVnz-CqNLeVh_oy1TO28Fpb9JFuMMxYF4sdwByPLNwf1MI8amqOuok-_HJwws4wtj4DlVBJ144-n-ZpyIi-izpSZadeXPyN040IHE4_THL-FJUOJzDqrj0t
5FbQ0F2rWAKtnutoIJ8D_Mny1AntZnG0aifVXKFyDTppQEZhVDq0iZD7FFb_cg3Ebqco4_h3jT7_25WT2rjt40AVNLpbzoV9Pqrhw2KtLJvGFaH9uSi6fFot
IVA0KkZBV98VhY0vH8N_se2CBzwlhq3QHK8lkIdo5s9aZk3AVouYvrFM_N3x5le4N-8l7mkG196GYmmPN_Nw2cG-bKAl-WvV2YYq01PPn4zyrUiha3ZrnvjS
ZwNBNnP-I90EGh9AV7q5KW-zwX-F3h-m0U_NC4YEyFKLI3VqfTpmyV-bV78f5F3z6cQThwz01aAl-iTpBI8h5G2mFqSeFprtrejh_ZRJpnLylFIw0re0qacE
UWjq-SZuk4pJTBnpCFJWu-l2BpQWFmXXu6EmkumtvGy67fsr90LK3r4EykCgeH_6w-eM0EI3d1QGy_q_CS57idej0Ax2wWkLKNuzzAJWQni047a1sW9r_d3e
HLyhOEKFj432DpuUfuQ-dY00wmDLjGMYpg_d1XHZlG00MEUQwYWTHNuTJuYldg1t_b9kWIeVnScIZy4LEY20WxT0WLyBFS1XlDx3Btvzb8v8-VNSL3gsVWiK
Mk3bJ_drq1lhDtF4smSz02A4FpuXM0l3aoZrWvX0Zz-YYBTNz0h8hk7svbUav6QuO-qMU9-35g1zNiP7m5mIaha1045YJ0y9lJ6SkMVGofSUhl2DatxR0W2k
Lm56-EMnECcDNu3CGKITNpmiDx3cJvCh7t8B5FZkUEDlG7UGO95lTEpcBQ0Vosp4h-lz0dIEiFb4CrZ-86JnQRQiFudIu4jizfAWEb_qUqcGyQlVGm6xnESj
m46-jEmE2XZYys_ZyxVIojzXRl8MKFuUOvCdgCxd3koT0YfyxaQlBL3bxmYlBI3yFUDrHNNY9EAnmxNK-EHZfoig_5s9ymAIcNwdA-EZxLslBP3cPly9si5i
vhnMJ_JxNihdNfbv1oI_-RslFtmc-htxq_Dc__v_F_N_1G
}

