sprite $image297 [264x192/16z] {
xD316K5140P107Dw-KSB_7rq0RFxwGgXbdPrjVoz2XV21TW05-12k00Ru09S21lW0bm85s03N80BOGDSW0jm8Mo02t01DeGBS04kX0rm0RCj73zeXebwqh3w
e0aYwgSF66_XrmyOQw7Z0HCqyB2fjsru63MYqF204HPw7z2zqF-0veRt7qwxgyFR3pNc0YxCtEUQfIeGXM6GK7Qu_zlju8GwzjTrmBtwaLa_9YTUAImOtN2m
puobnWxCFwRGur6sd7ubr_q777eeiPx1Sgg1Gq__JPKTQie6YFKAFjRohKDDvvGf1-kHGqaVuPHOh-1ZpJiTs5ds6OTw39yEbdrQdRDGWLsqmQ4StshscLuE
hHc7dDAtys7pQOMiOo14_-fm_ZUtz9491qjfSmUKXK--KzRVAotxTQ93FuFPsA6cr8BreGxseOiKU9tWuElxVd0zZPDJsjq1Qx9FFcIL0gzJDgmFAPTQQzbG
sK7stvnmuEHZrZ7mEhd3FZvEO5fA5GvOBQF2-dUEtUfl1_vQNqctZzIuoEmqu33P1X9hZzsoEppj9Nasc-adZx887UZAtC0mTC2atLlPFbFQZeupgB0oxP3g
649Nq1qOEh0i-hn37kn3DOML3dvl7JWCRZ-wWkYGku_o_9lW49J5j4DJpYRqSpTZUl9BP8f3FSh27PfzJPc-2V-ymlmSgK-nGuL3kCTY_y3UbGp8ZGhiTdsK
lVv9yNbyTY1e-Ly7j9E3tCN0I-IZP8NdRToWDpW4ysuojoYmqJqx85DxB3fmtitd1WLiV2G7tsFHWRjkNO8AIh9VeWa7x2-mnueTEfedKO8CEeGzqS6OO9tq
eHiT708CgWGLv5NIu72zdpmD4Ww6MuKEeIlmU59sw5uMSC2nr_NCCUWBPLKTYcF20GkbBA4hHBtDTjLXjrC-1_WxxY3SE9b91RsHmZhvvOlzv51J57UG6Ybc
Ka5lh7sKTWpe6CtnnUV0gk20nbgHq1dC61zG-ra7xZUpJpvPGhz1n2bzuE0PEOmYGgWtob7kSk11p7nSuGQ7xIDFdr_OyKNz-A8h3anvMXFzVDBt5uiTdfyN
EyolayFKnnLUNru64l8wUPj3VrZXvVNrvICQX37DBz6mdrn_t_nGE1oc9FG-wiasvEJ0qra-9nQVVZrU4g_kuCKXXVkVaqD2uE2dimC7d7u92kuWIyJxuUiE
bQMkxhFYXG4ESd7m4bromEdiqA6fdQGhkCCFITYfkQE3_QwRuoiuy7HswXnc5qg23YmE_LnkxC0qDCY3Spcr9EYWI-pPfyDL1oyBct5eodHm1JYWECJbuL47
bCN00Mpp9K47NO9bE-VW-mkUpj91lbrGWGui3hrzc5ydtT5Y1xLzuC901rs2r-cw0we53b8x2GKwwCN1uzDv1qSiCmvyPFLYIT11cX9x_Ix99omT-hPjTF2o
wB53gL-JiKXSBWawK49_Fgh1uNUirWe7BmiuoCSFK813B77ZEKoynzAVbsD9q64WSPT3lCUIdfzq1S4XB0xTmSnmFeazrbM77YyCWWCajEUhpy6FOOzrtS7Y
XK5oS8d77PgD7CPxBE5vUvI4v429-KugT4ZJUops3nwqb2m9tO75SVq_l6E7mlK1PG67i6CBIq9mq2Jy0OZ1UTHsVdyptcFDlvz51Ts14jSVY8aT-AH8lCUQ
V5-F2uFWe4dm4iqxnCtawFrDOM60WreSu_TvRVkQyuo9zrWpx_Eo90G7NQBv9Rhyd9Zbr4SEF09iGKb83dfnc5-Ywy_BxKyZ1nI6oGfqqAT4_FaFZFuv62rb
2nO6tK6Nw9EZHFyWV1u85WRTGIyEE6IJa-aWBGnqq2MMVQuQIq9rq8jZlGCK10T1Oe43Ia9mq2IMEL11T90breGBW-wW5iUwS65ufwxEQW06OY26VlVcZxPt
kmGYlPs1OCMEuk19Z7F1jgs4X5IYWiAzv9CeeV0Dok4fD0nRg1nZ8GLFmeUXpMV2Ax7nJ7Wbh1nU2K0YW0BEX0-3peGFWvN3Am58H2ZXC-6Ly9dm5BmSFWnU
3Xy6BuTNmihXbSWc0IZ0J7WbV2Oy1I-73uCduN-bpuHNmcS2A14gXwNWIVWmU3by63m97mOlXrV2_r2WHFzoU0fU3Xy6JmA4eTDCK2KyYBPu2aStT40000G4
GAn_Qo4E_1PXcoQsB00JHaEVo0j8H5rG9bg3Cr4Mf8YmG4s41MeYD50JOO6A20lKH6YW9i82DH4Mg8YmG4s41ceYB50JOO6A20tKH5YW9i825H4Mg8dGG4s4
1MeYB50HOO6Q20tKH5YW9i825H4Qg8cmG4s41IeYB50JeO6Q20lKH5YW8a83DV71mW8
}

