sprite $image59 [130x83/16z] {
nPS9agGm30GDs9Qgokp_VxjpCwUOKoO_W2AKgMwNNz2ybYlPdAIjvIfM8m6GVIbNi7GG3n1NhAA2E21zkq00l6Io3aidyHPYdWuDn4SGTTO2413ea51WG51c
ZW0nH9jKO0ozPXOO49QPlu1OX_G29-jGmm9ZwDkS0izrc2j0h4D-WJ54dLNWsQ6UAa2iGtw1vsKkimM8TSXVGAp3EgV0ypAd2H3ha51Wng4-5o2_p2LOm3GT
pWlCBtDD4o0-rES5JjOXLO3uWHK_GoRf41SuMOSUBs1IcIAc41zgAPXXcWwZzs26MMNArEt26T1bWfbVDe9s6KsgpajcuDZtOQ83erwm2cg_nKYZJAxc4cQY
iTzHLWVeem-WkpXp0G-KKYfXmsK3tIdE_Vu-oXsTx0DqiLBY504EoZsBaJRWRBrJd230WHy_qG2Th1uSoPG5x3lMyaobGyq4c4cSyFr_gkKrNTvCHdLtYTa2
ZFxHUq4ctB9Noz11BnVWQ_1cKgUCFff9p1E0s-cxqKSN_lWtateXm6ZbXCNWSjc06KGc56XBEMTrz06QL2KniS2O2lO1eEaE_kNttnPufaENsX2E6R8AZ7Lm
e16wX_oR0WC10ZQuKQ3kOMA1CPKQ14N-R0RgfG2j_8GcQlHZ5Pa5nZf8hcE6n09ZDkVkSFWnGrQ1CHNOUJZ9l09ZbaPXi3FI8HRWAF2th2QPKmymiS2O3NBN
4qmiCAPHB-3d2nXnWJylS-Y0p2imPlMXPtWgG2qvL0Gp10LcqFZHAiuBpDNX0m620XDre88Jd4Zbonb6840kNUCO87Y6PBFQCK5mWlFPC5vCiCVFaFGoH_md
A9_bNeVzz0JdbwaH53YDIYk_u0O
}

