sprite $image427 [237x172/16z] {
vDM5SSL038HXcQtrJAx_RZCRV6X6xTV1Vo2b0u2IX0waaGlIo7NS-KXnjNYIWi9hGgsaaqfbi7NJprCO9KP8CM2SJY0rqDPrJ1BWiqhaOfO0BpZqryKIGgsa
aqgjJYe9fP9GAkcqab0gXKhrglAhvU9EKx1W1AypiwnszF4pjxQ5iG33cioCyWQzJflgfOqhG9FRdw95htEcLZQoe2tiJdc1j_p9h7aeQNB2GBZ826tv_T_M
uMVEDNtGPcITFQlBaVqGQXff-rA2UmAfQ_unGltkIZKWwafGP2Oy9CW_RihJW_ysAeQaJS9cmc-mz_n7IF7tBTsnXcgFQy8-lvLtkXIQwiY6qXrleoAjjlM8
tc3x7RMgwh91vTifrM-3XUeeEzZoGStmEwguGUyh5KyhnyqxM9JWVA5UkDMYLA-FRX1tLQgALx2eaWtwLaer87Zf_WIRxXBSLVa6lMyoE2itI1WemMieA9Md
TDz7HLsQ8SYZgZKuIlS5r2b4uKV46E1qtb0Bf0-at52wxuzkzEyOTQzBKiCkVOl9U0Vttw6slIv9YoHzLfCntaF5aCKQGaqJvRMQZ7TH0Gci8RplIFfUDHde
3QMaRaP52IxSEhzlCfRNUJxY4cj8dxAn3wV9-FKdkCMJQ23IQWqbxjAQXZum6UM_nkKbA8S6AR66FHrx57wJuI_MJ3--Xk14Wldp7elo9PC1sOhRZs_cghFK
JGdcwJg363iPRbJi7E7AduJVO3lH9P8kSlzuJ8ONbJ_9G_xiW8mP_CcAeGf5GPJW_p8PnoSvXd1TehZzobCXIk0n6LvMl0mmWZ1Tug4JCi8EGkbwJ8ORbQjB
4405QyZYojHj1r63fARcC1dYHENg4eHOGnvzRbbRQtBQXnOnVVPEXhXGUUa69i4OwqMMbUnWWFGvJ8Q3bLn2J89vJBHuQhzwEnbkL5bGcGJpQ9U88qVRj-UM
qeNa7aowBwizXdlmhk7W8U6oLxTNVacuXpHzFPADCE3syIn4IF66EfwoficWyrUzPbJZzIY36JMlID9gx2yLcmHZmGPCA8-wF4QiApe_DvXRmtFqYw5YGaCg
m0r8lXM7qApQPIhTTAcrPmKBdB6qeN2nm3rcDQCyk-Bj6aRe6Xwk0sdB7LrbbiRE4whI5QqXTCxAOnqe8oftSjBNWzidfuBc0H9TqHx8wkmQPkhaLYMAkGbm
mdCEaDYAzj01uUaQRgt0JEXIYZg3lpMAgXvMDCSNMT7GDMIsAlOXlUMuiRpndrUTvRjVqO7wzQK6MYw8KpqMtF2p4e5DvE6GO1RwDM4Vuvu6Dpmk9HfW4yqh
kb0dx4DStZKi2njJeWJlEkkAdXECi7fQc1erh2gyMkh5YJOHmh2Y8wq0It19rxYmzX16nV_sAjXkDwDPdAW8E-EqE7zI2nbga7UTNGaT9nXXEIrFNsoaFPJO
T0xUTMPTygSLOJakfWyvi3sK1-kCLbAm1zJgGoMm59TtZJFYwhZqgCTrgD6XO0rcr7k24TQ6MmEVcAhg-hTcXSlaBseoepvK2cieNQvKlBSSqot9PZFgFy48
woZTPXaBXVgmGnkw5vN3UaetzGT_YsyEyTTP72UOXDffrt55FWyQSNEuBlbnzSi0-qjB5mQD7AEpQO03rG3hCHcMeGQwCtxcUnRN2KPOdrBnkUf8-v4GM4CU
iL-7F9hJQeVLOJ0PGYprKzJOD-2vVoxVw4D5M1w6qVHoZsOo_IBM4BG0cpd9WKfW_Kf5kgvWxAarP1Vq6HQWNB0wZ2Q3tp_dhY6veBCZhG3hmrrD1Ztg-JIu
uHTqzg9oMB_9mFi7a8wlSzLrk5yE9zW3AyRaZbCd0v3Ownpdwn2LfjKFcsFVu3ew6Q9gw1gkcQqKrG-RvgcZkFPEXgLhkAdPHa-m7pPEKV2PZ7xg6kvHfSIO
hiW_ejEq-c73zQhSq3fCXjHdhtDTWwBwOSUVn_1p3mAjLwbQU3XG9gimL3ziKkrpu6OjNQ9KhWOfBrO_hCmPQeFK0gtLPA0rL0yhfjKFsoVic3yGN8F9u5r3
FweVTavOvcasu98UHQ2wv3_1VjW_chUlDJbo40p37yg0m_rVxOR6sTKhrwZNcBC-V1-Gz4irCm6e9R0RxJvaF8-6vsqznmueV5vUDxYRrrIPYTJtxpvUApei
hSJPOslPdhiF6JByp7f4_SVwJrqP6gZxQdL599SHj6vl3ndTijeQrAWFbz7Ole5_7cT5Xbrfzo6ZQH8ri0zer4-0XjXdYq2jSJtHM7StkVLy2xOZQhGrwcgM
P_a-JCsOQs97lSbTAuaQqg3-5zU-mOx7OBS7kGbGzURIjUp56lLybh_7JiHym8nxzQtcfb5ZWg_hMbleaQdKUnn5_TvjA76nniPqWzifaQccj-YoQzNR8IDX
WeDwXnjp74rjtsvFjjpTXcsqUTGF8Rgd7T06e5u1QD7MHLLV5DqqDpCmtUT-_OV80aE0RZ7Oz8iRxv_GraWHR-D-te05YKWqe-40g1ze4wXRhirfxXxFD5fP
ZtxB563pA9T_ikxhtPENgLYkvh5BM-N60tFYOhs_KoamlhqWL6qGQ_YdocthETTQl856LG2XQ8NoNSQCIZvPpxchV3rf2xK2nRp4T5ijTjhSuulSAxK-vVD9
AtHVW4oXnMMGSJRBVXo3Nyor8N6L1nd6jozL0x6c6st211znEyFT00hq0T5HKs50ixTnp--i_mzNzO5jyd1gX0mhRNG5w6_WUkPYtTzrhQbreCt0BfYkK426
t-DwVbltTzr5r8e8BROGc_BJqqt2OdqzTyAiWCPkJ9-KPGkWwgzo_ppgzPFh0FCE6lHgaz8fKA3jZw7p2Vvm1t0Oc2UeQnMBN-Q3sW1CQ_UDDY4Rdjs6uXrP
BNvqRxHAhDbVoSi9r0Fk4gXBgyLChqelj5LXx5-fF85wnBKE2DNS155XI2J8QwodJl1vSxK2c0_e2XCgmDny-4kAmUUpNAYkW7LGwAi6zZdt_DKbZwlc2ve9
HHj8FAC_hnFh0VLr2R8pAunQfW3e1diomVbSQmjaGHK4R8DDtfVE4sHd5PZ2ccM3FSs6-LnRtca6HQQ_6fj0tLuFHclGQNlikJL_f-g08hR5dazmVdSdO8Nv
Iko6ciZLrhpH3h07r8nPjgaRx45WoY-_KmcBDO5xkxFfgdFkowZvItTV2Tamhxa98IAFcx0lfN7tM4i5l9QRCC5vseHzAO-RGCtZ9cnCUQTkGWpEQsu2DO-R
dWr_puVEg8J5cjVSXBRcSHEwciSz-0EGX3hyQ9z0pMjkmd6Jnqr8_7dSX0zoUGaoOG_EQsx2oPh7pUdgtm
}

