sprite $image67 [158x227/16z] {
p9S5Ukn06CCUbE89tF-sPLBH1Ozr0ds_l9la2B4lL-ZeHCirdNxB4-hSG5TJegLCZgYiAccx6scJ8sLDYGhkrgPtiNoUigYaxN0aFBXIlnF8LVajtq1bKSbU
TZXITZXoKUP6sfgIjhkHiiCHHHzRFdlPuKZRuaZRtKYP6sbgIgJYmsdT3f-pZDjODzzkprIzThFjzbZKpRTROb5Xr-LcsoaNrRTJsksQBhTnhMJRnGRdsvta
1aUQVgc-dPHq8rs_LDBbHYe6vzjTp70ZSzqObSoDIXlI5PLCEnpSNgVhNuHC-nVnxLJaHhlpWdyHCE5how1oSBHJaHljT0of92hjhht662eu7BbhgW6_EMxa
mKZNUfeSbJmQIJnVteqyCRBz_FSat-w94UOtQN2qOrxDYqexmoyJbNP6tb1Ksj5F2aHrx8RWDzUDTfoVqeCZ0t1-yS7HZY1l8AfZnxmAkz6EyE6MZagx7vgV
u-RR-VykZ9gny-UdiVquaWOmvkSEphyT_An_5_yJsYyBFNz-Zfk_EoTl82hidBn30JVOUVDBHEK_YcJykmGEnxTFmmzklskthVRyf4jcx0F9TXCA0YX9Ga3t
_hVhHwFhXFq_LMyKcAnAfxXn1F8c7Sstt5r0tgVJlItxwcMw8wNoRnr68Ys6ju8NwLfodvEdVcSPlr0U3Rn81-6SRrE_ApeBuGLvaGwx6-Vujqw-fV3oCbtr
foxDkbOdtyswxGEBNHWcdKHbyjseQn_OniDzpgHRIB-BTAYbgPce7fgVT0lfTvckne-ga4pEHP9TroRTGlfTeIigXT08xznECloVRg7x_RIk1QUJsVITZ5Da
5zBl6XsI6oUogD7DkfNmNgCJISVZE7LXwYWhlajqgLU4caZBfyvFtNWfl3-fGotrR75PzU3gq5bnc6xHf-ip7RxJeKJl_64jZj5qcQpEkJBfbiFRRLMwBwTz
0BUHOybqEva5ddMBtGKZoFX-5QaC8ySsqqL0ZoRTQle9o6zqXzLfmUVRPZeztc9_lgwRXnk-gueMJ5UQWZbqhThZY7NT44dtzVQ9IhB7DMpITL0UEW_uWVEL
wphpVQz3YOb4q5HLcPPnT_sFEDYTYqctuFjMrpOPIWUCDeoYl5EBsopaEpZfLdXVwP2zinlobGWsMXDPpobHeuy7kA3xsVzwK4OfXFFIvChw7Y1mevsxTLem
JHSw244WbMaPD_YSRhDUKQNRUSu5E3lbGLsI82YdGgfeNdKhgiw6vtHg7tvl0Ca28eqoW3KHIM_NjRC2VGzgssEij56MW2EpUVNVmljroDw37Ecrrs13ggaa
IdGRUVGOLzwlAy6olVNCyfRz2cTE_Pckju0_hrj9DXMckgsTJBRXbCxEpJh5pq9PZ2FjxbwWgoFXcorqFWqTfDR93-XGCWV94YsFfh59LymM2-xNjQInP06q
rRSCvAu_h3NVhKEsePbiqTMlEuRkq7WOVz-kAzwTkhzlkZ4r5R7Ii3_Kt_VhaaJ9NXMwCR4gq4RbHi8IxcOTI4JJoNBuC_5g2hLuKLl88E_M8MyaWkd62jon
0TW_C7yc8HfvjmubEgzmcauhyAR4AzCMTw-kAT_0waodjMJqlACQBkC1dJNUoiDqMaksWKwmAGO-eTjjC6NJZG8TSVROhVq-gTkucKvEEnLxZBcHZ-fYRoX1
EfiKDkm1yc6TR-4ZayuM4HiTvECwLpKVf1kshFIhxz1b_m59LvM7ZV3X81_NAOOzxOOkssvPm3VemZacXcwR1iEpkdZkRT91ozART4cwGxhcDV7VeSjTbwKh
qbNdziQNw8wkAwFbINUeYpoYut_he66AR6-KNgOB_Jkpynbydswy6JcsHhvFfyhD1FbANR5tNQ_KDRU3hzMnaM_LRIJVgWiPxzLfRBrL1_B5ElxHldqZFGx5
C02kb-J-kFzf7Tc80msSO3cXebrze_UWu71NVhgVxgVxwNuwlB8EIrtL2-c0gSk85z7Xb9m_nufu0HqwENdQvzTXw8PlKnt0TNNY4H_J-Msai-sBK3etZdPM
BAzNXn6swRZFhmFMTMDHUpBhk4rqDXOJrrbjl1LyUVqwqF3E4fzL1nBQYWYs_Rmw21qfnJ_Yi-Y0zT1IiCca0wxHzQPZaq474j6ANaeoFLYNk58tDXsT-jyV
xWF7xpxbzkk_AVjjlBDYgeYuLrUuGKSivEpIXz1tuBXEBEhodz5c6--izaLsPtqshakrwVexngfCAuwtWcsr-TwvikctyIT6DSMjhS2rkVH25Z7__6QqSLsH
HMLJTcTTEDtPM9sYhh-I5Mw8U6Baq_aoc-xZnZlBjbfFfBDM7FA62ssSaRVPtEUKex0otRPE3HvHBT-Bx2kPqwPzVChkhDEcbpTMflDbDZqudhfy-rMUNhfj
khraUI-y-om0VX-zq4PLvaqs__QBBD5PY3ZFVYMU666CkAEIJumGSM-_lbVmutXYTVkfpk8fKK-HHLjHaF4lRnH_OWHq_6UN__I94I9s7--ijlbv_8cHuxRR
VgopwBo2RtOMcwQ6RzbPR9vO_pO5hv0L7LuaVrCNLNzudGmTNYslhGDUMmUqhe1NvJtnmEq1
}

