sprite $image129 [159x231/16z] {
tDY9afqw30JGm5riISt__-wBWwThY8DACDU6UfrzFsMrC9DV_yFO8lEjUGlIT6FUx-1rOrw9Fc_DMt2l2gPvoxjP1QreLXvZh_lmggRoQlHn7rxHJELRb2zO
WNc-qqe82WbbDNG5uZtTWyUaFxwKwy_PyphMQsfvEKbHfSAyk89cpuPdELb1fPIaJZXFbmrLvifZe6lzqkze_QdtDRnwDdzjBDQVBxvBAsZrR53N5c8BOuN7
2IyoNxknKgJKrFeHo7lkAbxIbQG4IghH2dnTnYimMqa48bSUAwZFqJm6ah6Ig05zdB3CutdrjApy6DIK6859MS61F2ZMhnZRQfG-FcHU0tbP_v2-0MMhWJH0
VOpZrJiiMmMoSTHOMy4y3-EbkX6PLQJ6gU1x6iKJL18rn5nQGQii9McZsQtWrszwZE7L-hcQyHKaZ_KhaNsDfhQ2GtYv-08QQIluVapTUKbOFry3QTOQcbua
zk2nVex66xgfI7hDFNa9l33sDBe_T1CHoU-FhlA4xpo-hpWQP-WgV_8nuVpEv6tgnsJTJDY_vmZCdvZoCui8UMtzjXhamD0Ngq19Fpl2wIKbvEtKBrv1OmLh
ydCwZNjB3NbxzOlVSvmmWQ_f98vPoDkf7pLU1REe0Gjz3867nkhmacxg5rY8CbQ6F8xun48qFAT-_Zt7D3m23op9d4HSNbi_lu8EZmc_jdAk7Y_n9uCLP02G
jyapU7GUpw-VV-kMQCufaNVu09yYGLuori-hO5rPRcnA3I_UmBS4U4tzd0eIvlAObuURadYyKFtQllcy-83dB8Tu_D38cV1HdkHfJoToaCUN0s_23F2T9tlP
-R3f8G5Uh7vC9j1KSeR7ytsp17dn-gKiv9KE17ZqnNNanUl7wvz1XCVytRyfd-6nVWxCvmNt8ybPNYgKxC3Ey2GvrsoSn_Kme-iZF7dvnOlpadegCnKvmPFP
BrwSb-pVC9MSrZYyGFrUSfx7-Z7u3ZlFutXd-IalOmzsdiVnla_p627id_fplCJ32_1o2YJ6o-G5ZkyTuYtGuRmtrzPFxRmCvid4jtStoWyUnlAUvJgBn5OW
D8_afL-JnAAsLE10dapSs_248UDuJrRlK0L7yTvlOOvKy3JF3l5I4kPG1MK8Jx8m1okO1_2ONXKSpsC55xs85wzWPvuEcF187cC4tf8dogTWFvvzOeSXdNXg
0nuov2r7UGRvOJZXFZpzs4D68ppa8po0q-rGmOPNed6U0kXmpxcy1Hhb6S3fTgXWmsDYF02mplVSUPu2FBv-5Tnkh27C0sB7T_wUQpUt7ZE2XyVZwrV1l7gu
iOeG3r_f-gh5pfdor0o8h6sDzNsPRbT2LAEZvNYxLB3b1GDqyoahI1uGvt6qyV6UVyXmO-7mlD7IrwU2t5W3UG5TPvzmmb9veWO4TGDyVCXysrYBwORuE67o
9AORvICGHtJ3VAmWuZedAjAdWeZhHlj44UKPc8435hMJZxj11tXIvpm11qSD3c_W0SPRfvNNig-SAwDck1wejcUmm4DwD8vHW_UeCRq4nuYnVGE1yIiCC35S
15I36z6lhmB2qJYe6ByUAQJD3_yB296O3h4nAWf-6nJgpsc6K7XgnXkbBr59YqHuQ4fVC4RZ0Hg2eQcLVXwfFBDesXEpSpuopRH9-Td_shlFXEfr60Z3IdEY
6Uz_kn-z4rr7ZYEVotb_qHbYwaFBtg2AlLlZuoy4XAxMCNz9LT7HEXXtYmrlIxhS1uk0sEcwjtt8STaJulUXX82OOoBA20WCktJAaWT2pAKh9o3cIyDH0iA5
0x5tISZz2mXUEWxvC06r7qXK4H0QZtCJa6hhCwPX1GK4X9OB2MFSKG82s6QR8fz4GE1Ps_m4P4CkoDffRGd8VyuaS1K10QH_cIfOh1X-0WBibIG1hnX0UHO1
uPSgTEehd1qZ8A8EpjeJK2O01quv2GYgFbi1u1SWFm7v3QXUWFed87HDG70GKC2w6oCWvV-RWEu4nCu923T7G7S2qbyl3BiW81uc8ENLuvHbni9BZOe60Q4N
0i8E0Uqik9Y0zbOG_ub7RBRjhn2G_Xa2el52EmY83by9923r4v3nL089Y0Hmc5ceE8E0Q7-T3fYMuISWUwAjGFK_pm8t0K6BSxibLUad8BOd85GIKBwGW3IV
QK1yAdT2G7S2Gjy4b6-VWEu4HBrj0j9k2CY-Vv1Zy9O82C66PZzVReR6n1CGKjS4j4x6WySJq3pG-k8HmGGqo6OJ41X8G12PEoQW92AC8Q0IPHb590KG453o
AwygZmtPoaz0zQeqoLF9eJREUEI9gJmt562CyJLhQSH10fhafSMX5m3Pz8U0yYflQIw8C0p8823r4H07UMke9o1ygzfPPlbepkLTGq2hV2vLweeT3gElojSs
zuy1jH0WZl8jr1eGpnEWFCht1kHUuYG_6xINTRD8n_icsMdByM6KtLAEJWSncdDigzYDckFY8aRH1woZ53GXXvIai1H-wUp6BV1TSNydd0OvsdpLGAw3U9eH
FivkqjRZqY0rZIjpitIMweP56vtgAESq9kIJC_uxQFH2RhEStpXlpDLfcgHLmxZKY3FMUP3M3VDwV2CtrrNpdtJQ56NkuVw7r_M7FIrftHJy1VAsTPcdeMxO
0m
}

sprite $image129 [80x116/16z] {
hDM7akiw30FGNHTH10d__-U-iQXvcYnZtoW9Rozx1a3Qp-MjzVVdcxSTLhxgaRJjEzOgf-TEwlAbhjj6f_j1-VrILne8yB3ziwvxwqhInLYhyS0dC-w7Bclh
IWTTYlhnoOmRJyUCCD9fKaJzyBTdZAucpbgT94efacQSyvmqq4NW9AIKKet4-fPtZAuj6LsbjDAiopiUX2xg9BKdizfAnupp-OhIMZBsP5siCUDqlb90H3Bl
oUZpCmvFn5hNdkplZBelaruHToaINNkoGHyqBTjhI_vAorSgxGH7iaVQ3Ih_9fUYnjEJWlYr9yipEW0jjyLNKMXtOiBprp5ZE2eYrKcQAbGknKK0LRNk5N7M
aFycSxPpLLNW8kEkK1rUcz2b_JRDsBJmLA7xat0rjE6D2ULXnjvLAbtx8RqEDuKcJqfC61V9pAAjbV3YeDi3LvgMl37Xc36kU-Em9ovxCYOiST6rQl8K9N7P
awAq1ebKXRbxP1jUJhX1BxoO424nxj9Jn8QBwfqd0wARGVNAq_ZG4bnxCI6xLDkCzTA3dAynQFOUG4LjKinuxKLZoPv37i20ukwzcjPJXSKhIz9bBzswGxFe
ySgQzr1ItIHEvQjLdvynPfpoykKPF_TowS-zEEkVG1CUxYFc6Uyzs0kbNKjvrVFP6Rj5w3FF77CpXgSyBtjmskHpf-TpU-OPFGUyd_7_hl3iEPq-zsmylVvL
U1RFQNFFnaflOVE1VXunzH8SNNC3ZyF4Ip2w0ZSS7JebwhZ4jGblDyoZtt3E-OYcwOpi66SxtuSpxyUtHTXu9Ap_lkFuG8kIPdHFufGs01eSmO_M_xLg7ZeE
0Z4Kl9Q2pVl_tpqHQqUi35ROZQ-dp1bBF4rYBY1j3HfbBhDs2yIta4PhbFmbsJG8SKEwrQnLq9ZMubhb3PYO6zJCzXmp3wa4jiDP7AenmiJCJ-Es0zooAjfC
m8nLecUSgnrtaCSB743NC37o97008uX6czlXH1hugi7ch0jJ_eNvnHw94GFZWciGBy3YMLBE5yc3-2PISQxtSu97l3IaIbQ3SKJaLHS7JHVCWvcmtERMnHM7
IrwbmB8D2c87zpYbysYqmHnWDnVh8Y1g5mvsDEV8FW8m9vQTXDNnW2Ef8hLIjKXgVRK-Zo86d8kVTRQK6GCE7vfB0t0xDx2vm1Au7N2SI4VaYu_42pJFFhJT
D4GKMPTyw7fWYRYYrHGlUXj9m9G-P4Mwz9r1K-r3fCiP2bZbGxsyu06vY1XedG-vqb18BFF8BCf92MFKNNjdFaIua5gVyY4eT5pwa6eVAYHfp8SquaFsMHzo
V6W2btredVSXJVeG0GEdyo7D-f0zrDq-wqFFtouCWZZkG_hxiZaVMZeVybZp9danBywFmeUsjxINCnzoFtozW8Xa7_BN-zd9XqWN4Y0BqQ4FnIBjTiM7IAiy
2xMDm4Cd4yU7aX0TFUCPD81LjdI_7vQM_G9apeVeZhfD-X2pOnzb4oqUNlTm7_OX7L_fyVCSQR7Qt_ukrtt8_keDvZKVMe9MrFTjUTE7TBAvp8EyBQvN5Jwq
95ZPvU_zQV5KiFnLBQThw2ssUAssdVJjh-ph7m
}

