sprite $image8 [133x89/16z] {
nPS9jgim34ETEPRf_fVxf_0cSao_QKtk1j29T87G5LBl9T1IOcDcS8sqZiBWlu1ReZNa3lu0M18ZDl0FqE-E4IeF5iR83EQrCL87QzoqZL31fxHucvOwu1eM
D377AE4sBNN0sKrBi8ukYh-MEcZHOGnsQl3MqdUXkfPsqBDt4_xJqBMqJyD3I_iqlBMqlpNynw1Fmr5Bkwx-MjfrzMz2xyHVIvtYeAM39mOjFJj93UmDkDYk
4_wTw5hwKuD1Io_0YMX6mBU25cX2HE2Gm_PBBl_0siEG7Qmy3Fa4wmv3le5LceYiYb6q429OKOd8VJ60msiyAY4Stnkzv7OOXXB2xp2GYI9_0u8MbH1-CMhf
Fo9yVj-Rt103pFYv2GY-lxXYtznZ50g53qtm3aOd6IE6tq8pKPaYV0BGNwfV9y1UXnQ1PHFwH_2QHg-LVoA7OzWU3w6Tn2xJY4GPIXCZmhQD48C2XnWjvQv7
aByPVeIWyDPfOBTI7yE8S0ZnLzVtnIWnDHxeJHn33FBRfX682iwRq48G5TbUJO4nXyxdJIWXtgJhU3pml8d15E9rNJiHjNCjHmRz90OPBtIIGphLyX3XmObc
hkiA_8-MXsF8f71Hrv8BdsevHTWQdPFOs4aZeiQc9Y8zfHYdqMhJjPmZ8DECHLTj4uOc2arOfm6Ui6Zvw85Khkjg6WCI6T5qXHe1JxGiP2UsqnXcBGrDABeg
ATwefLrNPhPeAPckex_9OMcYaW6Bhj2QC6XfGFlnSj1IHV_nmdITU5rB-vlSGqkxhd3Gqluc1noqjEiAgvO-kiAWfTiqFBIqlyaDMlhfgcZfJEGfX45B7rqT
jBJ_U1cqTD1rFuqJBVr9PVXgqDBFr-rXqDBBLuEMNYJ6DIr_0m
}

