sprite $image92 [236x172/16z] {
vDF55GD13C1G3_gu_LSR9htDEQ3v7SYmVK6UR4l8ctLA_R59zbIobvAybEofP2ybUod9IycUIlPIifUIl9JigMGl9NafsLF9NahsKXAKMc8JHftQsgGQ4JML
jKajhfgmDc6Kk2j35fimIxmgKrIRr09CXvn9DTxeYjhS6G7xjort_QzYZyIQwNhhDWn4mrLSkhp_sxPourx5uH6aoIKzVxFeEoP60u3UlglsDgJzbRPYRR-P
TAJIUgzXH1iKrgFUIugqnOqAEKgixuVTJbHxxnbiQx4c7oNQ-QHCYxOzPStUwZ_UJ1e_mjYsVcXROdrcizL8lxqXZ4FQRMHRP4tkMl_nBjBi3rOSs3OPhDnQ
9frsVaFey-XeMsHMR2tjHdgzKLzAb6nhiqRw1TRYUOOIzAZIqRPXODGRZVGYKZuBbo5_c3NJkQ-tBITg6H4Sy-BZN65WL6YaIQjGAoReLTQ1vU_QTZAfRKMN
hh62KTzfs_F6Dv5jRLO_v5fcMoRb2IuEGO3LaEVvLwJLSsP8Ms3nSZYMR_B3uzlwhXgMsPP9_UY95Mtxwr3wY-eGDUrLOio_f2aDeKkN4nHOAMxtVrDW_ftT
Dj8KuZ8iNb3ERa9y-IJTLNZ-tJHQlI4CP5kR5N9cDsgzDl-AiFg2EuvjQx9cDYhClxFpnrZvMhPbrW0vqrk1z9vjMzgDSEBbj2kNKZPWnV9rsu4KvbzXsjDR
Noln3X38ceU_b8v6lPNUFuTLdcYpKct4G_bgJRTEgsryRLOZPzJzwqzenIVQh4REaEnh4vP4QYUUoNenPsRPbac5Yvh32xQyQlD6pf0ulNNRCYed7giVXUyL
CEfqsp8f9nwhVT6uy38OLJRH3LZXYQWBNoZO_mCSgcoYZIMGKk8nQrICojAdFK0Lh0Eis11sYVGuxKLfscDISStqSNUUMMHRYJIwX_o_Ec4T9xzMldhRg6j0
0QnwGvXZSExGRhaGKhepxPqOhqnWJKxCcSHx3H_JIo7VBEFQQoLQdLKowj7W2Ep24nYdfdBYyGgqEgkGCt2jGoUSJqq2f9-ijSnbTPj6okAfYJBvmNgRjdOG
BhWDesQXKiWaUAWFLg0LMA6xs5flHNWVIIPXqftrDcq1fPEI2p6DGOC3KthCRvoQh8Ef0rX9oNRSVrcPdtl729mVOJkSHTbIi9ZJYL61LQ35lD2LHXwfNEey
DPNMaLMd3RyBr3sEjDNoT4kjhVLF2JbppbfB4Sltv_BR0tJmXgYj5voQoAZ4gXzj7f8ADHrB7noHDZMLtf5LfmraePBZ3M2V6v0AKrDf7LbrMhBGyPtYBe0-
AWuV6fsGCy2gmYQsqCDYJvtbXazRwtYaR99iv0omchIgXNRWrhzaPOh-gPJ-BxQ63-Fj73U4p2hImgO_VZ-XPsw0skcRFmWD8RFgjDdnEc-K6w_ChLaVPr9o
Xbbrs8PttbSQQY7DX9n1LgOLxhnbwJaZi0AjT7ccIsa8TLQcdR-yJDBYmMRLOVNBCptDu505Le5MkFC6wJaZiywthPGpTaEei-AqfzzvwpcZ69LPvzjMdvg4
yWLMWLQuF9kSCpghRbifV_ISqLbrMFtEMy-PwQnCgzzvwpcZiwwthRvuMCIgjuqp5WywgmwhVyFP2mjkdNLA8L-Szg9WL55_0yVijb5VFEYeVnkmCcqrRAil
7dHKe9tTDkgB1vsKQQTEU_SRmf-Lxr7hRIlbZ8uw7vQdlUaD8PEkjwsUCpgfJgktZShYGITTJrkSKRxpZRhGjbp8SNhvwhJwj4SvivvqlMtrnODEgiFgqzxy
d66jpv_vEVFsGex2uc42wSgsCSrg22V1wfS4iVN-JpNsLG0W34LHx1UkVy682Ej8IFls3yBtbMxxWlG_WVn2elv5-yJXuQVOHy8teprLMj5wdwbeFNmpM9Tc
jATA8rhlCszXNNlCfOslzGDtHUjzfgBry4rWZv3KjTvdEbgbfhGaZM55MjE2DAS5QauBqXmMf3ajK7DQaEQm8CrfGPhJ0ZMd1MaDEv3Mj0DgJJkGrhG3QGqx
aDQq0sfDEv3Mi0DfJJkWrhG3QKqxaDQm0sbDEw3Mj0DfJJkGrh03QKqxeDQq0sbDEv3Mi0DgJJkGrhJxH7e1
}

