sprite $image296 [285x226/16z] {
x9Y7aUH03CH4ZYEb_EFzFszd-zpw1K90QT15BKUYHBTb1lZ8pAZB9y1QFX9bUG_Ko1U6Bw-0HxwZsV88MC-FFAK7Miu8Nw14xg0Ryoren6O6wQafcCmwiH7f
8JQanrh-X2WtU2jyd-6yA9aUvbjGR-zM83rwlh_FC68ZqqDir4LnIxS2wIaZv_2slEUUQNRryqrwQkH16Cvyo_GmtuB6V0kYNDEjG7fqR4XFooDIcM-P7bwK
J0_pBTD3RDH5mNpBz10RGJTY8sZ6VAlq41j1dDUisyYpeXlpBTD3RDIiCz-2uSotJ0-n4JJcMwRdl693UgpbnT2D-JwJYy8ZBumepBUW6_Dzael2cytdc_HO
VpJl8o-Qy8DjKqnYGtfopLsGddLRT-aXFUksRMjU3yFtB6UkX_GyoRcgjvLjdtAkxkE9ibyvf4V88Jr2pXMcf-vD3kcHSaYFblC45uMGmqKXv90U8OTP5t98
Zv13UeGSPbt88Jr23kaHSfXr9OVqQ3caHylXPuQGGtg47D8Zv33hmWGNnRU4t6fwll6I8lwtQs_RaS8w4u1buvDAVl_N_Gzjc28imsAFTuyx97NPT_cMA4S6
_D1Z_GPDeSuFgvuRDDJvETL3d5fhtwOm-777Ed7goTWm-74R1N5gduRHX__NSn-7JnI37xPH4AVf01oR4vqVLJt6qT7W_HALD8VeZxlCi4t7YizMJMF8vIGm
CmrENE0KFVgZCDjqu55VGOZdEBhQ1lo4wh4jiTGjEPu-LukiSUNnrKCS1Aj_Kavq32BKUVv6GPpAdEcWY8ZBU3MNquTl5CJHMFT9gOkJHIIRcUaYul7WOttv
WfCeOseMymcEGvC88k7P2nTniCC9uWfYhv6po69crSpWHSh3xr5j3VXOcHCHJPtHWOhuROql3Uh9ht28Otzml8Wi21qSY3XikzZ2qNday5YrBSdgbYWYWixe
m1OHDQlRw8JdRXImIfnIwXOu4IaQoo5gbaNYjel1lzePJtosq0QWKpgrE17Kq5aVu7RFLH0f1fzxF0-WsU5O0dMGIws7oT6NGVepEcPH91b4beTLJuCW3Wzp
9gUo2zfymB66eqWmS0zz1WzOliOahL-YyUlOj6Gk3el8igrRwI7LGnhYi7KOX3qDbx1jwLHfazFYynE6n-e-jaj9VHpOFbX499IssaU3RCdstNbGwocEfN9S
pJas3BpyIJ68X1MdshVcWTKh74GzREQaESnEYuT1N5NVSEetvY4DOmSTpeujcJHVW-IsmNdXLCkkuTJwJNL8SufZIDbgI-OrUezdSIwehJYrMcmuttDuOFK2
XycXsCl6q-Ogsd1gXTPwpWDy6ngcEnGXHX_Kx3RECS00psmQHa--F56p0PpyVJOArFD8W7KpXYCIkkpVOMmO4PVm3XoHEF1ipQKXZeWlU0UEkFpPFAGvYRoo
w3jm1YupPfOD8siYnd6O8biYy94yi7eRXzKpWiCKBoq-zPeP-60QHXXVXd4OI_AAZoTtFHzTDiHXWWxZC0WDvxIPFtfiYCD43ECmwXlEG3FFeo4EupA6SPYq
uOWCLCyS6k9qgsSSHuaZ3lE71xMEuDol7kBODSxYv1NClkk1rG6SlpdMLMJ19Kwor71cNMQGPX27rNCVHoJQ5KuxkPnDlUknoWpYtDyeu1kcNU7KMdp3EU7v
mB4Xpa3r8BlMuvSurOhLEe67D0Cu0zM3s31nXREFNMphysaOkOo_MJtQNjOakuTJG_ntFAXr46UqUf1PFJTmblvKOkBOtCUvlr6KWY_lihpUmZcxOiC4cX6S
w-e9x6qDk-gvnl7_PgCWpRjmhkzHmnvFbuPfzt3wKudPPSF8lGGznv5K2hvKZyyt7gjNtDksTLXzDmuJSOvZo7zuecizVec3A6kIzO89D0Cut2XwE6RkM3qH
nEb45-9aTAfdGjaCuFGlC-Bw1-wg1yLlrNEEKwsu5GU-vuu9OpE0qwsUN9OLHrmkE6mKnEd4abjn-kuOe9c18-vOFTcG4neEaFNhHk69qmjymw7xE8_LEWc7
rKCSCsHjE6RfK3tNE3KIXvK_KZseTGfEVwF8JIAx5UTGFJTnMdmU71vOdOBJhnwUDDclE29Xjr6qzrPs3qUMQWCyf9cAm_4mBVpcQSL9kgkU9VAkvnn7muhJ
rS50sKp0sLKF9JHhmp7J-8SdjpyRbpXMTMauVyk3oap7OVMW58vHR3YspHQRETebJhNi9DHwnZFmHCt0uV62lD-j6iv-Mosywpd7gTLIhFMSPu1c1Wx7OzSo
oQquZZ_ohkSKfvdKAnqCF54JS3WUq0nMJyC1V-GrynNEFfPkRXImEX_dVlL02ruuPaMR3w-Pezt4kRDHa6O-pltgARxXg2OE5wld3WxTUpoacO0pUgmZkWr7
9EgNwbdq3iwDZGArVZuEbseKLa_K3IVmYGkidciSqFqOV3CSRXIi7Yi5Amv_tRtXkiRHlNkV1_PTSCInUXGRL5vnp9QbO7_NuufTuXYlcTKwFAIPX3DUFKMp
QpYUmyNg8SxL1wbglTJtnuGPpwA7wb4j6joA8xdWy8QBEFsRmfaubfqmRwWUrG8h2Gq7FEnBUyFbNZXEh7Q3E0-dUBd8-4RHS9hK2ySiBshxwY5EFxhCmK4G
vatLqt3CK5QS8XBuXkiKXp4t0SUIl2sidgIicGr75lus0MVE4yLmEioGOLlDQCC9k-hn3IVRv-3e8cyBguVTmv9-uUnk2e4NZYpu41oByW_Y2sYoyUJKSCpl
rYQujaODuCmwliUhPy-ZOSDXSHjV7m_Wp2YRySkCuqgnn8OZclNu-dWg3ZfbCw5w6WxiU5Ce2wRXM9H_7b-iKptQSFZMQtTJE06dbSsCX6xrD1mGPtTJE8ep
VdpFhXw_uI3fuOFKyezn46HYNEvKJofuuQYus7j9yNuSBlzpi_Ihf-7iNm3ofd08P_pudbyzUSLncWiwty8Fu0oNpVnZVSE1TTwFlXt7ednCV2OFZZYMM3ry
IJ60C_Vu7jye6evVSVPwPViM_dquwkNJ4bZ7sscbsQyu4hF2MhRg6S0PEhxdLq_3CIHjE6bVFN7WxSF0yJqt_2wof8PZfaKRZi4dLizxSAny90shXr5j9HHM
7CVgGV43EAF7z_oDWiidabznn77D-Azt3g9yV5osBVpYCcuu-y-U4hwIMCk4utl6PORjlxX4mp6aX9DniLScx0gpDWgkNhdXMAGUKwapuVYUL3s7vQ7XY4Gz
7vq9kyAqounTosZqAqxIZ3ESEMKp_nuLMj1m35bFTERj2lEhfpGSGnx1OTbysxX-zRnmhDWXpSOcx0gpDmeKLayWJYUJZk_vbnc46iR18ay8goSh27MAC__u
dd-FcgoVISVt_EhPRnJP-fbUDlEhvxnp9X_Vyr-F_ZsE9NbI-Xl5N-9CkEgRib6STyxygxxvrVEVubYGfoV2hZEzRERVevvd-l4zlthECtzNcBzHd6RwhZ0_
2NQI-Rl2_FXy3qSN-ObPYlKoi2iyltg6h_gUTvd137mMyFnZVQ1idhfHC0F7z_CtYhFZ-xTw6WwyCB_nPO-ZqijlzPpZ_5RFByxrPSR5rSrlzPn-EF6Re47U
d_y5
}

sprite $image296 [143x113/16z] {
pPQ9SgQy3WNbtJf7lF_htXj_1CYlecQW29wkTTPqcRObkKviBSe_Gr6erY3_1Bb3LHMQPJwnGLVGaymbL8Lk02rEZ-O8j4nBA7Me0vfdHUDiN49JeXdCJ2Wx
6PVGn6Wyw6yb52kyZGSjlH6Dkznd03M-CH4SinAApSdCIsXSxgkWnHScmWKVhU65otqfeSdH-BdnKZJl9vITpBo4V3GJ4_9hnCo4_4IOc92V2Aydv2_tyqBv
mSlzVaAv1dawcllRQrVjBffv2S6fJ4q8f1EQc1189pGn8N3ul2Aa9VoTpcjVBF-bpjI4lCxqXBmEeHCJyZhp4m8vGwYbKvstXVpSy3hp4_8wynFo9gyc5F-W
WwuV8Kn9YBGVCb_WtOJ-esC4IP3GFj0XCsFr63f6A8RC2eXXz7v2_F9fjRT-1DHIGRoU40bgCpEjHnqL4Mdl9qIIZVP_s0uwHMA9KebtLu-Xqpyws7qqYngB
TEBTLsZN2R6rWmveJ85yznNQTQAKJGTDrCnqvFFU0S58KlLBfqlMRnz0Yfan9ZQyDJT06phezWNuhGEo28nC0I7sToRh9-3rU0Qe-wCS0iWO44IoalpbX603
3Zes7LqVP1N9II9348aaVlM0G3lgOFWilGwPrIUEbp1easZ63VoIp81OVPH4KMw0xBKJ0GigX_WlDKtRmVSFqTOQw420hGpZnnE27GbjxyAf00UTfKZ59lJy
Tng8nFv3wFnqYaXqp-AJCaFdSv7nPvqUH2JtvnAYEMHGu8IyZh68n93qcJi6sfcEk8ISpW0nXY6_WWTadCuW-OHMdSKsbZPyij4BtPVnEgS9GQBQJeq9HTBG
kN_fOMV8WL3XXQf8tWvegJ5nqMPs57hWQ9pE83RlercaSjbr_BE8HsIyZaz8GVOeeNkT7DhrX6XsGSSbbAA2R46Icl67JleyeOHBw68qNkSqeIHLntGLARGV
Ear4Bcsle5tJyGbbQOm5QqBM3Zg6yLkrEw5BCbx7azOl1YsDGVgQKCn3PqD3iNJS5cz7Swvpd1jGGeD0K-T8wAVEaekbzVCEWFj7utLyGkDOaaA2WaH9aexF
z9TE2YBW9dH1vehEkdgCaBLBO2lOcZwSJknC0lSiEfbREZuXrM4HsIHZd9M4zaDdCUNvEmspftH6GXX2YYePgh2Ha1vqjh2B7sIWFQaZeN8LwZ4JENOGwo3Z
z-byw18RLx3BFAJZ4-gA8WLA-mmo-w-EIDAZ4Er97P-G5YcMydT2IpdgC7_9ynk0zgYEJqYrLYPfQq8fRZe3JGSTNhRfKKuuIKYLq2GTgNqkVHqfxzJREWko
N61DQ8olJf4EcgPgiIssepTr5XQvIDPDI4NGFtCaIU4kr6_gj23NAVY-P2r29Gsr9DBkdixUt2r26px3gakaWfzHts_h-6Xk9fGI5T3FVfzmKuTL77SJKZQf
ssHTdCxrotqx8P3eQ98mrCPaNNpApqTpdX3G9Lc9tzkYgjDvy7AVapu9AT0AYnG5nsIDNkVwvRwV47I4Kvd65ymIkFFRqVZjbJfygYLfuz8N_9KEaZnEFBn2
KJfoFvWGvpekccSJ6Y5tIb0udT-CnfEtkJ46cUAFEkgYUJoXTRyFW7BdsaHuFY5L1NUy3AkyGD9TY3jFN-xhgmVWT4udmWi9wPdEWYAlCX8wqs4DyZP9-OFp
QDvCoEaWoIH2vPxpmsl4_UtreDE2p2NfAdGo4MObPCmo2x-zqheu9YQqDFbto5haAly3
}

