sprite $image301 [390x238/16z] {
x9axZkqm34DBarIX_Q_sVOmHx1jOWMVYLAFJt6-bav21xByO4vg_JT7-aJim8lxm7aKVCZ87wZ-_xQ4G0SbNJ0uey_Ser5awO3Y0xBrwg4B8B4GXT40B8twQ
Sj092saXW0eZnpqK8Xgei70RHlDTuGSf956QBDW_HXWj73GUh8TYzC5amJgNCBBrNU5dg4AuMB21vakVQoFcpoY8ri1F2pOZhCBeabF-Y48YfCH2U83ihgAD
p-kX2Y6t4EGL_RmUgX6k5YopmBaGraRWFwFsTloqO9c563OLoJGg-d4zrDvkmqB0NW_CArhyRYmLwcnQ28IaeeSHVvMo4F4JWsSxMWzbmJOjOBAGFpJvcvG5
YJ5vwMwluMzG5iJu4JsD9DtlDVmePI4AWLA7K2Vg8NbeyctAWkrO86BYCot8zXg-Hrcm3Ginsei7v0uQJzT3MU0qRoub8Dzh-1dAWZJ6Ey7vs_GmY7v3OJiM
-jkOE7I1Y92wEtemJoZCDYm83VpwYk388eotr7zulzVm9ULWmu8uKcY2M7mR4cGcRXqz5BPZWMYhDlXBpfaeHug3CRXkIx-xQjx_QVVgJ8CsCef9CJH4Uxlc
pDTOuhUyhrKw2gZ1NAD-tW5QPf0fi3sb6EBg-EYX_xX6HMIGAHJjfzu_8LYXsPXh_B16HMIGAOmSeD3CwkhbEXyzt5_FXjq6X4o1M8BHyjKci71OvIMkE3nd
VAWQ7ZtSVrjgKdpt3385VG3q2Q1xOLWuVVoZ4njp3TxV4BOez1ufQF0tRW3QLGDigwznRpzOAdR_GJ4C30M5WMO6Tx9QRfNbyX9-tD73nyljhtLyDn0I1H-1
wD1u2bHYkXdTtXvAorri3MKO10fBCABTPLXvH-82RADIsMve24BXvPN2851OpOd4SUbyk5wh0aoGSM47FzUuTV5zaOFWAUZCb1A1k00ncC1QY51JxGS5_82Z
Xo8QNr_znjMsuHXu2ZO2bOz0T9jJ4Hi_0E7d6lsUP_YwHHW6be8FHfBwPTKW2wl3IcMxOV5TjuZgHeu2uODeMgMCLCEPw4sF7lHcR8bcADYz9x-gDLdr0NUr
ol4zbFlSXFfL17TGOFKkFgmH26viOKSSzAiBnerxAFtIXW0kPTzdnlarHK6hNWk3zOacLgiBd0KOu5Q95JAMRGTStXwQgLoZeJA5NFNwlMeV09QA-atT8qJP
isvpzA1pE_kFdYdagXVT20FqLPYrl9qi-q_tH2uzjojY5mMaMFFzLT3E-8PpZGlFxPwsEayXLxtIwm3jSvDZBuP73-soSxjP2hdgvHo0MBxQmKDYxEKDZXxi
tAvy0LirMVMIRw39YLWXqnbVZBrFp1o6fgjIg0aAsrKlkbK_Crquh5RnfTZB1gADhufUYK9Z0-SevAeN-FLLXJCHUqaCRprSnHvqRZT78LUzyceAkAYlnTwB
7psKFE1I8meKnbMlbgfUbaAAfpdWOZZNk005qGI5_LKlWuook2_sZkSQlT-PWgOXZK2-wgLXnxlpljYxFTV0VIce909ng-gbG8XIUBjZhzkC5YBNl22RASnK
lVBcL9YElQKIYpP4haMXPYdaipGm5P9yx6M8lV-d06uTFVGVGm6-rCLTKHOJtxRAlKKhaNOt2kNt7bRUaR0zsVQnbodsLWqCGKFJ-rBeqnHgdNVKXxrd6pXX
TJxsDb0DmHEv2uMYhRxdgXUawYN_kZlsgYyWMJJO-_KezCyKx6GwLxtYGN-ElKrZhyr848ksSursVGf-0XUhNd7oPzmWM8-bqA0VVH-Qtef3dwRW_JA7rhPI
-hOvzcvHQ6jxuBYlyJuGfYbe-FHYkCwPLdFi3HJ47iQXwLqOR5BeXW9QonIcgbukxEJO6oWizb1yxwE7tXE5VS-2vXxjWhcm8vdNt72maxzCeNgLiUWtiuV-
TGfT4X8pXVcgrx8A7tiblsOAx8_Nenlc6gSocA7GopV0K4cvwfLlE9Xl6lm8_V5uh7wftAnKdiTWXe9AEN3q2Ps_v4cprPdOco6W7l_gzKjDSmsqCndifo2_
ZpB3Z53r-deyfQnQeVHRyl5K_v0OmeZ8kH0oXIuoze3u6ZrVzLe9oOMUFmmMG_YGUNInGUGi1fb2J_-dyc3KuP8dBJAcs6k7Hqz16BnKI1RDEeb1ff1K21HS
sDbtm-5BmGYrOg0gXAE7nuaCb48F588z975hHirqmo5JO5S6gZM3pqGUZpCXz2fobeAt1_cC6uMg5vXMlTncv5L3Ytuy_XI5ZLq5doP6YS7uxG5jRsXjOLL4
-PPcCt8gE8l-e7SY0uamCgim5287cFk3iUhLqWq7Au0oDZGCd0huT4lwyTHv42JE2uKvCS_unbKlv1iEFdWHnX22whCXF7NgPhG850gJGg2WTpXrw-AmwXNS
81X2iWVMUp1G8HZ2X3r4SLmAG5KMSZhDzl3uhNCDmN084EPIAyigLxqon4b3K15liHaHpOlLzulggGMKLQvwiSRouuevrTjjHYgmMyrlInX_gFDrJYk2q-dK
wnqPg53VvX0jWg7gvKKvrmyCaaw1e8Pm88SqYxPLh_L3mdI0uDFflCurX2pmMnmIXLpryc98fzDwayteU7i8ahf5aZU40pXKrHzBfmVRW-xnsQZ10z9frB2l
UC9cT7HgnJZsn7WAZjFf4HnUluuJDwEyBSrpm6PSQh7gXT5cT0Y7rKDv0eDZKolAQABgTGG3dvLaSpp140v8hO72RDNh20QFJnJM74up11Lwq8Gzx16dqkay
0qD1FpQdR4OgaFrx-fnQftZWsCreH46tfNCPD72MGYxoePLHgdeTny1JK0w7ZYioWq1XVkRDrbfbjSQGJWzW81IKmtc6G6OAyqUYXaAgUXt9G24e1RM7KpOZ
Cb2OKc6Qmk66e0oKmkosrFzkxqvu7CLY802d3tYNuV__t5sOwL8xecCcbgcevTAnXyx95vTVtY0HL4PFAyYw6WwEHxt23Q1WEzWBmLz6oByQR5cS3_8voiXd
08LZXsjFfqyhB3i27Am7-QhpKI__Gh0Lz1tNnGi1-KS3HCmxxtfNJaK_wXM_46m5kvQ25iBJ2hBgBED71no1j8Bng5Um0HGCXujEfpfF6jYrTAHGY0i12gP3
z4Am5EmoqX73GIdmJgTQmMReaTSLXt4OsEkX7TtRDOO1Ci-d7C8NWiuJPOISFhLIhYkECqtJAOVeXQ3Z68HpfzP6Fvrg1OC1n-mUkn1q70Q867VUjDFfiSBP
SUZX2m5nbD7fzK0udHeA9nsY5mBYDB3N0_zqgXMGSiOXTY4WHXbv7KYdKrlX_7hmNrVOSHhOjKGvdTeAvySXi8mGPndfZ4C7mkdKLYWpni5oQ246jiAgugsb
GJYT6WfbY8o2QJ0SMWqmC1L4rP6xbjXbf1LgQrydvceobDOT3WrnDvBVWMkWytTa1GopzNM6WsCG_DlPNqj0u1iWyYSpXi5sg646hOyHxa0O1CC030t3u5WF
RWCWXDRIAmq2eeR1MKj-1883nM1P5ZslNvlX_lEk3WUNGM0jSK-dID-Y_pIefFlFkZrqgF46V0SRmVEQABaVXWu5t5hyx71c79fZAyVL4jy02h8EnO1PUF32
FwkMuWS1MLmEV0CeIE-BLYXQmM0m728D-BKaG70eZ3yANLLIdGuLR8TMBpH0XEZWCe32kYwhgDMmz1aNgr1G3iLO3m4B8N8z40sWi7_ktuUXJLlcdnMwzUiX
O112rmFF07jXkobMcw7D_-V-Mov3AHWEyGRyzU17G71CtJNsB8TT8x8xGA4Qwy5hW0zMQBKKRu3i2Z9MA2pj9mKmr5BRZsiQjUH3mATwbGFF00eTYs7KyhF2
_cyDd_JZIutk7GJL5-6rv3cT-WE5iNtjQj7H2bz5TFBNGtUMqNgb0sSG4BpiO2yZGs4F54o7KmX6jLnJImlD00nxbbvqR0NxKgCx5iAL3a8pG7J9smhO2zxr
O9VHDRKav4502c8eu2Cs60m7my3j84jm6V4LzEzfaMOyoETO29vQYZRWA-0Z7W85UnpiXM36MKl-XG04lWBMmn0e60wECdAiX-X1u2iKfM0wc0OHotGX63WI
eg2FL8w5u70Wd4uz2LFGuz2xqHw1jSHV27OiXLuD1SjXZ_6j3NRWbv6THme3FmmC1SF1Q8-mMl8Rq1oWC71TOIdOuq3vpUjT27I6gg-D7Ygylq-ESGXT3uxh
2a8UAi3XME7ZThjzUcifo45yPSHtQCSCnmgtwL4lKMe92Xu3laCzS3XI-DmKtbzpFKZ0wPHUIuSAyssB_xGa4UiXO13u3be1bGG5mdeW6F1hwK2XlDzkRmKX
h0U20TVXIA5C7pFbryD2GA3LagM046g9Oi1tq0fy1o4Oq6h9gu3mBZNyfrF-E3It0lzImpy8V0T3WReU20OiXsOeC1s4O41S3xO2wywRW42ifI4oF0ZyIms_
0TzXI2z6EBL4CE0vt3qhF1itgjTTQX1EfqG7dOyR6CZhuNSE0c8gt3vVO3qiF0E-m-UcyCPV3rG3liCR_dw1k1w4kn3u3XCK29SQZZBwVGplLvnQq-2nmypy
zI1K0xw3F_uxRt4CGZ8urWE_ZD91NiCW7VodqtJmNsh81OEGus0EmqK6wI3oI44kC4Y7Ba9_n2KT1XJIm0vL8GqGieB_T9eEVeKS18Ifa0O8LI4D4Bg27o4T
vYqU1Rz1CipJ7eU2to0Ty5PNMy4so3m_2asapN3G2l48wL1RcQhisJXcA5nca0nr_7qP2XWchH1la0vztGA6yNSzG27-kY8Tsh8YUAlhbWw5u458XoehWcbG
2k46oJ00y9sXGY7U81qgtaoZEwb18HuX7LhVizmFGuT2l44wxACWca4hn1ia0rvagHGEzuB_T9gn58Qgf3v18NuGqg7tLUJ-HPQZJaeXs20Psbv5ebvaENO1
A8GRf4FxCmJB-BQWgrA8HqY7-jL5togfA8K8WypHC8Yi7Vkvbp8hXN23PAXtBxAKLhRCnmeIWv0ELIbq_FyZXJ23T6XTTeLnzqRN6GfH1fc3koIfHMU6Ghn1
CjJDORJZfyAkMmZfK347XmeSWxppXWBJ81cW46-GCHNO2Eb0NShf00M-GJ8C9a8wG85la0w3WP0EV8NCQoXaNaCXyneAcPTGoBoMGZe8LI7p4WgPbr58Xr-F
y1y
}

