sprite $image168 [257x209/16z] {
vDS5RaH138FXSiVEW_kVjcWfPQRf_ubNw3WPxTj_bwvunr9iEzA96hd-8CO7Zy1gRGFN7vpuu14ClUm0N7_W7h_7aDiVGTt-PkhsDtBz0OuV1iSFvF57aEkF
wUE3Hr3w8WDSVu3ZXsV_t_zv1Qu_mF73KyM7Ri6cRpR0zSSsmzlFl0C5T0JMJp8uVapmzdD6e5zYwlOtS-iFa-C7TVkRmVK7ENwGuyVidpsVPt3ziO7Zn_J_
-pyFN7_KByJ7BC6v9W6kFmoE7mRd3tByOCR_-Zkm9dOEhZ_8yOEw_StW-cE0wu_FVFKYxq2DU0SAw0Yi_-jnrGDJVpmk6nJ_yHrKPGGnHB2tkkB-nOAuEu1U
0e6u1v0Hu3W32CkYsUuDu9fe-WHSQn4de3m0jQmhSWbSrwxZPm12ZU2odJFHTXk50QWJsw3Du___spb6Hpoio4rVkWGxrUpCLbs4mWMQhUvBB5jO8_WS12pB
3W01yGSH8Atx2a0Wv_mv2AWaRG0q_nB8f77vwlS041K150HCH5UlVW_029HrmC94bwx-i08Q12o6u9BL7mEu9pG4o1i28hfkzNi0ckgC2BK8oZgWgrQ_1w1E
F4zusNNWgzy389lj2oBmrHy3K2_Q8K1R1vUh_XZ0qY1mhU1wrUy141ClXk1gwy1NV_mnI2GX0cH3S9dgZm4W4Isyo491Ar1NlbJrUnc2mcf3m1Iq0YfnbUgF
Tu9e29ZSEd08Bb3ziGmP0gRsjW1i6P369Qe_1g08Y4X7OKP302oOJPIlKFt7CWHsLYey3FTi_oboedo1wWza233NLi22mp3C2VGl_QxW0jKVoj0qMIjWLW19
I-9XLt3owezb23Li7IW0843YG10ka7uiGnN1f03mDXCZvZaGXFDM_tCPGiJvDkUSyJQIR3no80YdddxV0yescAaf0W03K8PX14E0f0ZEdRwNeMMJ8TSA3439
DIUiwy1QmMchtmCm4n3P8m0S9vAT2xbrSDBfzpA4aGn16GOM9cx8W4DmnlGzW6e2R3BK863jaSAnA7T1W9SN8f2X8WAaULK4h0T64foPeLdY2QVV0q0dGvYQ
ZqGzC19f43XHFc7wNeRK15eP0gkl1a5mVFvU0iGlvkzb239cCm6J8TL1OXqcsfO1CJ-q0jheq9ccFvQXSQec85w6mFL8G-14-KJfUm1gn8yoX2P3kmCZ8IDW
0EmZiQFU_xeCbOsloL0gCcJBWpH_cKOm12JqjIiup_GVov3fO2j3CERTWH4CmotR1XJyMK7_wSSov4m0iW6WCZI18L00ATdXYHU4_glV0q1I6V8ci9EXbBvQ
GG6W19W3GUX_-f_B4439zrvqcFR3Y0OWAG0l2Dsdxm6O2HpA4FCUmRG1o833l06O9tTcnjHpzJ-N8JoM8HlEOyevmp2LVpf1SAdUyVGVov2mc-vOXZHV1Q1a
yjszCoFgEtqFe5eFKHcbR0H26G950CDSPfjqf4L0HFIMwuxNPGWQ6PBRCCOoXDYIcPEk40e4OOit77czBaFsEH_B436f33a4xi38NwhtMVqUW2Orpj-MeIy0
maUYt6NrnpAKBIalGyUtvu1CICHBX029YYPsLlsn2_YF_xi2mBlA43WPcYUJ8T1HHN3qrAwlwhTOrvqCjRkzeeDp-fAX-rw6i94XnYy4H0w1RGqxgtu3iBOo
v5jyTZ8q8mB6CgG8IWaSFhNhgFezW5Y6qClGFDTM84w6h4CKaeTFxNggVW_0JE0dPOZG0EG2m8R9MaIB00Mj5VHI_Hx0mgqCxKq0CuUtvmh0P6XkEmGB3RTK
IvZ1hOCEgjy3M9ItVT1J84FU1DAzbQ4Pi3bLbxGL26WIv5f13zNl0TZt1pGor108P0W26HgXdghBN5P8LW3-KhsBwZS0At3vWo9ePOZ1SgL6XYYK8IMGRPWu
QujG02_j2bZ-Glu-D6Ks6PeiLr8mIoH3azgW6mO5W301KraRJfJVMFqMiWQ1-2qPmYf3lZRIRLi2EGz9276-VqkKYT-GlaFWPUZPxRduvG5ppWf0Io138mWb
-gf-_qrI_0qPAcF51DmwK03rm2WuAuYh_wtv6mAJ8Hgpwl3kzbmapRYN8N482W45qEJwJ9I9tvw-hGEucmmL6toK8Riz9zRVkzjpBPcKrG-EpWgwgdwF83aP
IWYn344iGpfSna9HfX8TzFuZ15w6fYf37CeGLHd21a4PaX-yh-cg-Zq110NWF-U93014CiHLXkp0I0n1j0uwgtwF87DyUwu0Rgd8KDBXAaEtUsutaeQ03X3q
qFkFlrgKmzlpkPKXc00HzZAKgmpgiCWYZMgskuA_Opul1M6L8Nyj0WSoH8yo15O4uViQmhB8MFfAtmAHsKp0RtNoWGo9bo6h3RjtQmX0cVmooXtq_YWOuwV4
vRVHoH00jZ8q5m0codKRbQ4Y8580HH6ag-dtWk1b27uWG_Emaw6n39jgBcaOPjGeHEo4df2ai_Gjy9aC-UK1KvKXHCm8pKPocORXdXIV6013mDsbRmJSK-Ad
CWHvBqDGMu4K02av01hIpUAF4TWg1l-KU2z34CgGhOEa0EYF0rX_Qqo8LOPe64OlG_9KXcmuAu2jB080_Ks_Foim6ShOo11L6S90XjofUhxVKywGXnm0w2zz
Zu2EP2YwFQyoHBlXdFymWFLF1M8iGnZ94BGoz7Yad8TW2NGx_Vwuf9MXv9uIyzqwX0c2A09i4SG0Ufr-lmwcMoj38xG7HekJeJAiCkGGO02Wu_JzQOa2q7hF
4tePWfqCyOCCjVi04Z407LU_Hs0ov9yIUnc20nc2Bm38oo86eF_qRLS0UF-n32MrGIz3K3i4MGMWA07fj_fzO0am6OgU4kSXCJLVJ40gGtcu9Iz3e3NmIm1u
_Sk1U2X3UMnbAA6PmA4C4G39OW1wddwFeChGhhzv6KftGDZBKDu1K0G6u0JfMo1JbI6cOna2U2v3Y2y3-6zzNs3TwWHFYKs6C9IXCTW8dMZw_Lc1oX0zaI6z
FJ-MeJEbxulWvsG8VhCCoTf137PiI5mYa27vGpAqTXA4hGoDxYbn8U1_Mjxl0B1s5Ct6PkjoaGoHCu4SoD0Pq_S8l0pPS71x7W0uq-AFBnD9KYn3mIF40C0P
fz-VcLKPoiWKF2N6Ye0206TCtuloQ3AKYmpDUnc2sY4G0m2dh7w_3jAO6XcQ4H7sCfG1N-y1Q-T1-2X3pLDYaw5N0Qmd2CIT325YhZ94CkzbI1o02-Hl271K
0FxZtsHe-Zw0zJo1Q3Bq-BvcC1dw9e3rL44A898XIFaL0ElPOWD0j15uV6bV0C1t0And36JR1il3-veOm5NIzuAWoy3Vdlyq05dF6sHdPh4CUG2Ncdv_PkOE
Z20449zuNW11zFCgaPy3aFKIWHZ94E1J0EjL0bJ-gWmXnZtWSkdx8l0ov07u_2-8m6He1q020ElrOi96XYZF5G3A8Wx0UiMmzpKRW9qB82_xzm6oNZPAzvzt
CYHCm4f0tFHV5q4hGyACW581h5SFmBqCINqUmEAg_z88C3K0IX5iVx5-I6090r13ri-9ZmUmmkS2i23wM00MpFy0_0Fm3y3osG18__Z904eOW8yBRbWOW4-D
lmpWVm
}

