sprite $image283 [279x214/16z] {
xD2X0SCm00GnREJzfsqJ_aU3f15qltTUbx4oOgJ4YvICiVAwd4dA9YLO2L8sAK5Ai1AaR5A2bI0bIDca12j1oYRbJvvv85aGWa1Kn_aWmltFkrB-tfpOBFig
JApKPJyc1899dah_G33vGs7cQ33v-yEBdZyN2IqLa7t1n4E91vE_Fo2WcFpz0PaL8n4OP6-InEWCCZT9ud3wO0JyN32PttzwOiL8WA4s_eLY98BQH4Vw9ac4
OLSqisBY_PdeMZ4ZhMBY_L4-YtEgMLB5nFkZL6xXj8g9IgNVBXIFPnKgMvFYKZblssCyzyISL4sAIsMbSeWvvBi64WJpyQ4yVAcO8tNkrc6sBcHHJBm_w8tl
IbjTydGQUmX951FlZwD7APNeA9FQxTvOQWc6TJmKe2TYO4Xb7OvrUUjWubAvGvc8-3OgBfFAjltxG5mgUfBQiyXH9lUkxgcOU7ymbTkbbSVXA1vY7EMpjKPx
AaO-r9zUyQmFO5iyn4WhLoxwfOhvor8PcCVtEH0KhbSIndEDxl9_82uLe9SoQM80ftrbE7IdNR_LR9zF3XyVoep-F0jUa-ZsthRF-q1SAi_F6YwjUqDm5L4S
UgVWORRD-u3SK7CUkexhG0nr71TfkEN___RvPf0GWFS9CXCAo7czxkP4v7XqooLmdZN9wvasgEL-10YiuFY5vSVTBnWgnY15QPQuJTEj_YAuJnJ5qxAZhjFp
MEqFSVCqLqEI35AK7Et_DvJ9GmXjSKFOVVl0U2iKGzhjY_LdWrmU6m4VObRyId2oOgWOdvHI_dSSdLyj2bSZmhF2za6SoaNIaWoNye-VM-3qQf779Yic9H4-
n9H_NTkLDwIGmLAIVoM9ctBbpTmqhskEvYVyHnjbjgIGUeLnLXhl6tXODXwRVEZ5yIVdERNWefHIBp9OIbiCCXGpGxAydjwu9ipLK2ed1kQ7d2k6pAz6gVDp
CIJWc0eXFsOnifH6nIHroWdD1-2wr5_4dHyYID6qj9EKH6f1FiEL_1lpkitSiCtv8PUb6CJmOo8lDl3Ov68a3sM_cAXNwVbvCqcH6kxxKqD9Hqgf31G3X7PW
-YicQb22OIWxl008Yl5KpEdcJYcLiM80fvX0OtVKy-CNWqIicFuayURkaq_wyGjX4ODaGCMiB9KFvIUezoBzMlmL4qlzv51cG0q71aGGimiLytwfqBLD38Yx
OXgb8kQ7G13JgSMV9BrKcgVFK370A341gLJQ-N4b2MTy-m3mgL9nYm68VrYJ3vMAgs90x4dwr50cjee1HeanvCUN911hnHY6yYUJLDjQ_1LZa6984eWrIOPI
SOe1Heanb8glOa3i5UFC3y4dAWR4NJ7-_20UFtQydoGGRvAC-Q6H9tWtIMXWk7Amv0TF8wIyAGR4a2Ip51wIC_MjVG34b2HT2WGZvAsA0GQBqKi5f6ta_IG5
GDp3MiyF47HTBlGMf2JX5uYtOlJy89GHfrTCy6HQawJdvno0adJe4IicmC2E5bDxynDzBuDd-TsAmQd7Z1KZbWfw3pr1KPD4ATHYhnYbLA9syYj9qAoOJhyW
vYIvFYPs7kQndodyltRLF8Q9wSYFOeLUI6tqRjV_0SHVCMqf4AqmHmJbMhUaDa6BT63qznllVYb6d2THIugYnIy6NPTh9LzcwRk0gCtyj7SlOAIO_dUhFSqw
j-tQp0zz2beC5QDze7rFacQx40Zv4RGu3WowBgZph90kBJr3sQA5OlJykBL0k135PmXPIaDB8qIbLqjxA6jQ_6BGU8TRnwNxHGfIgCMVfAlfRYwSfUDbTWrb
NOjVp9LtkHnqFEOAGzcWnP4aNQvUAWGO9CRxAO8X36M75d_5GB2Y3cLTYxzYT2yXvCUWPQb3AWQYbPOKevOwJMiCIL88_rMhLAnQokDREur9KdH84Kh5fELW
5f8aYOcM5BbKsloLj2HBE2k684B8d98VQlchQKdgi7q02FxV8W1fK-xNSg1ecPU7byqyhFj1DAGeMWu4BIWppuk_OeYmAIjQakjQW7KwY76B4l6L2hKaWXPi
FxqBbCrVCSHPAjH2hcl1Jy4Kr6ak8oj66Cg25d9PInn_TWVoq3YJf9UAheLSr9B79N0_Vk-_Sb2lttGjvAAM_J6aDuuaOyNeGrdNGYvfYKT-waCEN6BC-Mbh
8HUq8F-KvUAzSj27igw5NDCouQTSRcd5VUMW3sLT2xccXUMo77vsRvBqeQnh8MqjpukecbhAirnkqq64UH_mIQ6MosBIHLv4hQa5MIxvJ-wOhLSEy9KAjKXU
vho8MdED1Z1dh9RSge-_Ckq3xbAX5adCVgGbuTOOpmmXlsEZHOmvFzGYYKaHoOOibpqpj02pxLRJdHzgKSNKPKe2MIvhPcW7PjEjfZq_rA9xGRd_XAK2ptAv
iMccn32ipLAeHHU3Ki6TCJE4r58smwscLYgw5bqCk3FEUJwGMX1BZnU4eLGCMZGlCIKtlBGWAxZ2A8PIV5fqCUoJ1TIINXRJPity-BNeOfRKKfzQTl2QoYCc
CCoABcPdXZ2_bgOrswM3qANuhUXUufaX1cfBBQlZqs86Iz75b5jcY5gcstfhQT75n7WfkfXjcbc_IsvDrD93V55--iL4ePOIwvGKN22-8Z_wi2x8-uVRWaj4
V5z-I8-Mnntl7LU9-3uff4TBvRPuXVY2KX7lOWeNQu7uWb8HXlKybPSWA4HyGNw4OLt1SoEA-Rxy43JPT2r0V4L-r8-qRL29yEV71zfQLkX4Z90oNWorY8me
bV5YOk43dSO8AUEze1gq6AJOW8Slj_9VEtHGXJ000r3ClsiCzFOBR7cDX7mhvbifBu_vIihxNxwH0iJihn0nsod8otAA4hEQuiGihaWnQodMorOA5hEpmiMi
f7WnFOLyoIbcJ5nHOreA6nDIv9Um8iU453acfCWl8KME2IjoJ4YHOqAA_19Iv9Ym8iU453acfCWlOKME2IboJ4YHOqAA_19Mv9YG8iU45FabhCWn8KME2Ibo
p9XoB-FAnOmf5pEcNCouSYzZoiMCAHSpfbpCk78lOyh5_2Nb0m
}

