sprite $image34 [321x227/16z] {
xD0r0S1000Gm0K_-rHRNuj-QICWu0G3KTciyedqpFd2NBChxdaZBT7inUpbxENqnVR6kBrNrhUoPXvQaEWn4ozcMfVV_d_kExO9c0zsRTw7ddWIs9zrJGXhw
5odyqAVQkschjROcqlMZaBzLdqhDCJW0qHGxpeTKnBw9TzPN7CWcy4Ws2wdsjrJuEdYv3O4hRJ7bN9gfIEzzh8MIWaDRIfkzvhtqQOqhNoP3bX5IkMTTvpxK
p5gMzp7ONzfZoTfCcBC3J6NPPL9m17pMz-Z7zWn96BZ8Hri0iAxqAB3nEcyo7NZm2M_WZy-yB6f7GoK5ZtWy8xmElEu0LJv3xwwF8iGUD6o4ezFEQySABySZ
QgVSs9yk9mb0ie78RjI5b4irajWtk1kPnCTo379NW-Vw2lmZWcgI7VFa62n2WOTy5lOQ0L1tgth7ChPJgbj_FPzgqMEWl7Us894hh6PP8fr6giuCyHat_80t
OE3qyD1pgUdkI3y_xRTBRYOWMbatoczrEuDsJiI0iV7ZIevZCvffRoKpLfv9UzItkd6cpvFRc7WxWo-6byJs-xc0gSKvJ7Ip5XzxcQdLQJPDcLxjERVojmIK
0FxXYhr49Qifo55WEgIJ5RogtNDjeD94xz9ANav_iU-JS5fPbEIc2WyNKcdITREXyued-whWod-STIlm5Z08LMyGml_EPXVX1U3NBDpf8MG76krwBhwci5Km
izaOm8mDtquoU7r_0QXxCr3rsrJiiGWK_1nMC9iHPvbCUMus9xru1kshYCC-yGQWcu3fANEZgdqhaYkVYMn57OFn7IG22DSsUDOu5gwk33Mpp0ckmnUr7w23
8SuKEMYdRLclwuzrwZ48tUeiPdKSIxhz6Bfvy_CRaNvgqAxhZpCSN_wrpdcE4VnX0bkmOrlP3MQzwYTspr_zYNWCYjzUgkHkFqFpxVYMYqYp4oxipzG3JhMu
6S8rE_TkluH0WQ-vh3_EUybCCoPgluwoVp_LAnlydtqxNNRRXg4u3e1BR8bu_yVjmcasTIB_atkjGy_uVE_sAq40bFDuVfk3u5xOnqcU_TlhMFVj0a6Dt-ow
llytmDKzF_S8pcwqWVyphmkOzs_VCRPRVcf6dUFpxgIllwRVJ9thxZCoYfdFDUHX3UV2VgI8RNkEOBCPyhT_JRzlsskCV4fkZdlJwm9cdINsdEnrzkBN54oO
lUpvlDpf1Rkwt_fv0se5ttxvzXCBlW77s--3MViNl3pl8vYlchUVMF0D-FPJ2xu1zHavIj2q_k7KyZ2rrX8aOmN1p9lHbFRnL6Sna9QvWD-8Q_ou82VSCnS_
WDoFftoUO9S3Zimmbje-A-6VHZZKWfdtQ_rcd6Vn8pWoYv4uz-E2KMij7nDqyH7Ct1H-iugzm9vYPxcf0Pk11FNZAL5EkZ8dZCoKpZ02FzALkU2c1Vm2oZSQ
oBExCXYcDJECs8ztvHKdcSnDxCUlmGXVhuraTdkGY7P52W3y5M79rBKGVmZOUhiYGG33mKAys1RIUhz6403-Yl1Bvgf3eBVUBnAiK31ydHhETE1tbM0XW3Eq
XlKzkFKB0LjGm73KX_KzkFP-gI06F19M5M3OQNg_Lh1om70mIwltu78rO2iKy4Xurm3Uo0qek0O1u86mPwutn7YV4Lw3NB1e06Czm0e1ZmFDoB7UKs1N29O_
g-5xvdfxN9481WTq1zkSyYL60bWneBih9y7CQWzIrn8yyJDN0BezIb_g6Zpn4upIWtnEYhxIDNZY1xg8u3LVLyJSJzT5ChyOI5j7yDJFslM0tK1ydMlmrCzA
fhO9ys5GTGsU-fbdQXUvzOlurCziN0veBDuN4JptipttQm67WGYBkFWX9tw2EMRaRZHD8-Y77Ft0Tn7bKu9-8GdWfni4HzuC9rOOPRxwEVkjhtwErYya1y1p
FsiAGFqro6luf831WvPW4T7FCa7zPagcu8iIJj43Jh_L0FL5p07F_Im4W8iNSG0_8M2r6UaimvUvwRSYe7oMuRkSlHQWVY49u2S6NBg82_1JDv6LYxX403yz
e62MeNuHr6-cBBI9y5dcgNv1_FI0WeK4-WNrcwc2nmH94NE_07x2rvYRWT25HEzdJVuYhPzbk9_-GNNBpMOqimptyseWWZyhahiT8bX8Y5yhXdBF8VYiAIjY
xjTQ6CcMWfy72ekO-xNc1Z8k1omsevfbk5-hP3p85Fqf4Sb2mlrc2bo5fPEqVY6fF_cPr_OjBbX4o22eBMBkrwfW32HpZA28iLzfFyR96AZuVPjWba5-ziqF
7i5z-WdQi6oMuNupP8hHj67XGiBzUXUy1fBt6C4rIFoY0K3m5YFe8e9P1lbLr4CKovngbk5-4z05FOHysPGMCJz_lGWMERIBo8gO-tNWPqq1kELk9Y_Yev__
twyvUqrTvnBaGO3Spyt1yGDNe60I52maoA-vYPvY-7k2O24XVlFuXUY34d_M5nGnyfjyrLWs0BZQ8CDd6UvNmV63GypwsnoVPRWVE7vWY17Ki6QMUU0NXhFf
0BEQe8YFvo_2pIeuVg221JKiAUBg_jKl3dxi-Ebxy4mEDvFCCiKzPWv-X-D7iYi1ivbfPfdgxj_y2Zj--hVKOqPkDgDOIDpyu0UE7zY31Lz6H0j9cFterm_7
ZyK7zjEt4JxBD9HgDlt0yGCjHDb6P0l9Dxz-U3Z0sNDe0UUpgcuXAG6E7_X9XonR_jtUNQYt4SH00BvbajFtVzjwh8FS5XNmVL4qPMx-ZBmGelmXQR-c8dFu
Lyw_gI4bloKTW9VcXjZ7TpN0ws9-1dXnpCy0JV0QFnCa1O1MGCJy3F3YcD_5WWP8vlVEV64_4pH0yqE-c9y96g2TWUTO_zwRR-5dWYy_T0fQ0H4oloSB3lDx
rn2NfRu3WrAL-waInEjdfZUF_GZBCgH-gWJvTUDSUvjVnP_jGZzLWXH0SFyIwKtrGtk5Vhe4C_etHX0M2Q4ihYxyT0bM-1N6S4CslUXj9iao3ZzTWftVo029
U9jTIGh6LxICmq-Nu700vFuqVekrblzT9whnBaQU_mJTwHq9_DG8WW3nVNimR8ytcGX_r-WHIyvAxgav_0q2Fps251vyu6YZSXS7Z_IVGsbxwq1Wyn_FnBrK
u2SvrL5yI53tovh4FJn349s6taEu3E97K2ICxTbHrFaXVrz0CBMt6XOa4k-gJsBjONGC_MdZ4evVwvXa4bn0Qn1qADqZr4hjArSy_IQs7SUkqOtfUT2s9JcG
e7ugnfZYl7f61ZaHWJ2l0unDu_JxqRk1RxF0JulWl0C6aAD9g8Rz9pENSQfWhexFCN8_ZUUwD04vgdllK4QQ9foJ1FNJAqXkcc3oc5xQU-b-0MmBufkWVee9
AwIcqnh0qbR12HZn-3N1wgjQ41XvUaXCFCXSmS1hnXhA0-Xf2EgdcP37SKnhR2htk5Kshzj5XAf3BMdS17ww1T4lr-ZLH9yozjlht7fD3fQ2ivj-GihC4-lO
1tW9smVrFkuFZcIIyUadR95bNCYT7_1kdBGTEOw3iyjmLhruoEyNO9ZSWjIocXqRPa_y6q88iVGtJw_-nMIKw9Rw83jlc8lqulwRjX2XNbBmvVM2udmIlEAV
-hpSHA51rhuvDtbCRvvaQMnsvrZvtfzBzCnmdbpBi_KCqRX4Yd8xWwHvNXKChAfOB1QBnMAnM7u2
}

