sprite $image304 [236x172/16z] {
vDQ5bGDG24HHx0FJVy6xSNVFvDR0EuEyGQ1CVe8r9bBuQM4XX5nWhLs8ERQL2Yahx1d2I1C71NUeszg4YZTEA6NS6O3ya0SkuDoXRYlZsfdJKfbsXZZRmBNQ
sNQ6RN-qSAEKBvEuGn24IfYjDUvMohKpfms2ywN9rl58RT__41AyZOad2F9Gjpd1GtYniYzu21cp7LZuP-PEb1jbOY00pyLe1lB-p_kR9Tlrh-o9t95LHTUz
H-0B4XBa-EG5A7TispfdYFL-QsEH6Mj59DzW8Oos8lqkSmRMJRpPODLfzvWpiChqHc2zoTgOOOgs-jlMFsTuQpf3MtMs6oo4sYgjbb9gwvPrM5QTTeFd6LZL
-LHbrRJI2IktDlhdZ6aTggj4MJKjTygAjJ6-V6rhJYhZH-jf6uGLXHCyPsmhpgESkTZLi3xI2IlMnkWvOrippXrJmhQcIbY3snOdRrlnhoVENGmhi8GLRHlG
g9IrJPpGtuPjPtuwuKPOuzgsZ4bOItgazd6DMLnE-uGxOKNR1ZGgOUriLM3pewpups7bQrkVNuZbwwJEp5V1b6gC5UbXBxXjgswZQkx3m79Mf8KiXBPLjr6L
-OPLqB6mCXabQ26qhLV9zjQleZMjgFl2Mz6sKOtw-MUwSHqJLZwRQo5qMmT6gc55nugoKgcEEUEs2dYsjLqDorhzQ-Cs4RTL66jpMB65EHhLQStlMSLdHPfx
pd0xehwToyG-l4ntMf5H8-QCY655fWvVmoAVRjl6xMRzSzQwl0_ZO1zT6-jW6wEzRvKprdmT2-l6NeZsoJbJiUngQojFUNTlojWbZ8CvsxR_xdQNXtzlGj6r
rzPDNGxdsjX-lvA9tohfoe1rrN_YNXlBy7nBQFTQUxAUN-MNQqupvWnV8_N9EhPQpjHjsDQ6PtfOZODHJtl-DGcyCndMv_j24MLTAaHP5vjzfY-9yMbYxr02
AmeEwKih2FXdQ-jiPDCYZLq8hLsampgIZYojszCSa8ZlagluFowhLc5KrlR8zRyAzk7rL919MEc-ap9dX3LZwkB_cTE-pabP-TOxzW3howzn6CDlcvILxzdz
wpZsFSPQ9qYBVLXTLDAQ1oVzUbYXTLjh_gTVSvCpMy6KI6TKfsBl8wsLaXvVb_MHzx3BRqQwqZ1pNfnjrrPHVwUjsJeOaLCAAxIkDH5MT29IfxAAFcjjBSR1
kFAzhC3IMhGSoX1Md1OysffL-HfMlRPmvGkhHuiEBi-x_rRIbTp6rDRsr7MsjO3Abo-ioExQ_6551kwxoYeeHSFgtFnHlh1gBT-gxBDwLLJRAkfWh1HMlf1n
UEWMLYcFQEl01UAjmZIgjZgq6JDzRKMBOXz6HKp2YeCHZMfOoKAkryMnhFtbtRiHLXoCB5zjzLpQhSrNLZNzyyixgd1M78mlNrYTslVU-pVv_pwC4kQifDIs
Gkkqwk3U56s5rB0IsjjPqQYS5OKSPCqnLfGlRuMMj_Rs55YvUnDVlhmLseZl3MdKpF6NBwoSrc_5Bf49griAArV8Vkl4Pkkteb49gr_Bx_xZKrP8FLPeVssL
HzG-Z4q-4rPN-SBglxJsxgzJWEMjVFd2IcjvwrW-3sRnMY4bh8IMjbRKyoFgDNXrM56-bDNPjkllbyZuZXFSc_IByCPQUIcitANrxuWQMsWh6ZNK2gtVEflF
2cc45Lgd5UaEAyetoWgjqufKsehoZRUYa7rx4oALjg9yuwtG-gp8Q9MqGXflXJRuPxZzZQep3eUMjSePpkflL6HFRJgmEs5575Q7zDZI8zlxkDGNsXYhltmH
mGB-jZMLeRNnloF5BvquCmZCNEkhlhJ1Ld-ZDlLYVd_FYg9NsZ2hlr5xUaf_rxeev12hltn7JY-InplMwobj7A-qyibyfdph-dDfMxTZUutTfpy1SsQTRRUj
nraMvJZ2jVuvOwJRrcCk_fqR6pDdrYd3jFwvjUr7jDRVg7RgjAn7neKDAEI8ESEtBQmjfNeSnwWfjy5gunir9oAv_smzs_v1_Qw3NMblLxvysy9wASU1xXz4
sqQNRwEOM1iDwvwGGRLj_9pXixsmDbZ7k9GzfvJtmw_rIsTEV1PFUoZkTbal-bwkEvNMthbHxRMnNyKz9FsroXyLgfYujD5pnjssUql8Fa3ikB1QUxT6fTP6
_2HUEIQi1_OeHo5xodUwodVzjFSzgUKXX7NJUnIlzRru8CAjZRtcSZPgJRXLpx8HhyrzKftEU_YriP-L3D9nSDh85m_-jbL14TlPRpLd-BKH5vRNnhzuyATD
9IZVYrJPTXExHy-PuBOTrm0UMB4OhV_5GsWkazwaIlgl6VCuO226OLXwaVUVDprlYoauS0RJWFYmnNdALDIyjeTaNnvLh13-M1lVVtwDLgeydCcllTe_DQgR
Aj7ppRNnT1f9YXyUVdRjvR5m9gzj7c1u0BIn5qjHS_xaiN0cl_Ro_6_W1hGnp8-61pxhlBO0PpIr1OO7uDhh1U0Ce8sz09m1hhrU0CveQWi8eKORWU51eut0
m0rTU_C0dD5SUy3meD56W3EQsW83juO_06Sqrnx06KrjWQ9ghZr023Mr1OO7ZJO2prTpxG73W-RQ0pYZgIqmF6Xg2nHLeuq0PpJN7b1KZJO20xT66m7EQ6eB
30yQ_W33WoIxqo95lG8
}

sprite $image304 [118x86/16z] {
lPYBaXih34G5290Qv_z_zyPerh9TQ39xAVla_Jm5hTPII_-N8ZtHbqbD_rBfgrJ5tGfb-Xf5e0VecRv2xb07QEahWK9VmEVZPNSwaFAbG8qln9iQD0BQqYVR
4dlv6vVx-NYjBJ4Ux-VQ4WEjwLDj-NYy5YZQjHmMyMu4Ydej2JNGqdvRpDf4fClndUE_BcRTNf9iRJ6hG07L-HqwFzeBm7uqwm64TzjYLbNXd5Afgc0YFP0g
SEjEYxmjRkteZw51TOCGiLltbgIlFpzhebnhPQ8wdizAH4dmOlLuTzQVMOdw0528qL9vMFFKcdLZINgWBrPaIinSY9eDri4yK5vQhyURx78NLZbYAefMM1_C
m6jWZUCzNty-mrgvbDfjXj_-EBirMfBdWSPMg4eN-xK-GqJARetYZHyBiHLtc1XsrcSoKG-iSRpnOm5mQsNccecQsWmxA6zM11y3hrqkQiLJNm_OPzZFAcw5
iAoyVF6nm4Jyi9PqK7s6VOZLhJrHwbZ6U-MnCBkI3wkl-hTSeOce-0pRHbhE25gAsk90v-BfXnNI_g9udM7hSOTRqIo7zHF70usPTz8RaK3BO-hOhFxVL6YX
97hGRPiilS9HM_9xx7Th8Kev9wBkCuoM3YaAlPCaQX6W2nP3BceBMBFDi8-7ZSx26Yuh3E22DLbpIXTfTwlDCBhtV6bjQ-cuOOo5LXxCZjL6r54V5sUvelbO
J6lgCkdIa_szbNJSRhTn1xe6cD9sp72R4rt4PXZTb-XXFSO7Krfq1MvtXcdNNfaQmM65xVwZhyWlntdlAyTEiyRUJ9GLprkYKeNjOPajrOMr1Ki2u_Pi3QyP
pBxzPsA5ikdHY0fqPKLVBbXpklNqcb-tlsNP2gCIyTeQ1-hMm1jRYUSRCR96RLbQ3PnOU-j_QRrPSu8RZfoHrK1eLHpO30iHoIMhEqFh00BhHBgepJ3cW0VM
852tXjxutQGAs9OeYiZgbtjkTR2ojbfhovIwsXu6pu4-jPepiCRUU8P_j2TMt0961F1kpKzMCw2bo6gN6reHECtxR7tWRma8by1gpW2Co6lNx5O_k-Lg89ZX
C-UVMsfsi5VG_RY7jUi_UBRYr2c9ACkx5mFsknRlxpy7StfGBJGfQePdAn5ZO9WNxJVMK-TWUb0nWDUpCcKC-sseTBd2lo-t9teYMP1kBRTEFF0JB_GAveob
ckaD2zBFEcvCy-OztfXBWQBG0ZR9OSKGQgDG4VlDK-sLG2i5D0p0h6KCfJgdg9lsp7ifq02F5qHo4sAcXaBoeyMLouq3ZIawlJrHoLHdj2cRDVHURqiCsnrN
8f9wjtPIhpD-xRnTB7l3tQAj3vcXYfZLlTS3_IEPBfBxE3mfFyhZMkosvJnU324UjS2rxjreIqp5r3PAtXq7kss9utrCipjTYxssnDYIX6AiE7U2AU1Yl6CD
jjjo7czyrlYni8ajoS2wtvRpU0Dht9PzsE8Dh55RzcaMRs2zt9RzUB7HbeqMlGVQw2CmNhnRRVdzaZnOFAq_H1Rtne-5JyQxiVusbkI5ny87MXIilm_7kx7-
DfRapTRVTsaRRVaF
}

