sprite $image228 [214x275/16z] {
tDS7ZWD124HHnPs66hNlVzgDjSd8EVB_3PumU7fpbUAZ3Qib70aLVwAPt22OPfHmWt8qaqk02JIkZ0FX1kLe9ZSxcKOS7MrGBd4cHpEv1jUSvffnGRH1kQIP
t41SYHhEv6WcDn0BLMjmpLkwuZObpUGIiL2rIHkKevbSjhvykyEP7EF7Lxk_YR5U8nxIf0tAuKoEPdA3Xd8uawEPt4lhQxwx1JEew_zxPKQf_tf96JoN92ME
9H5TCelbacEjb_JChd6P2hPUUdPMNg22kJ8RkCvG4LrIHWTMdAYo2xLUKX_NF4bb5cYzv5Zh9JLpdQAghkpiqWvMBgFn6qKgBgkMwBjUqWvNBAFlbLVD7r6P
VS-6IeIF3QcnQ-nMjNQTgbBdDufStt4jkrMmzP88hbbLfxEUq7M2gkqRHSAuYehc4egLErICAoyHNQe1FgBaKECA2UXAYUVIAiTPhrnNgnZZiiagZYkrMWLo
sNI9werQCr5G78U1QE9BXsNu_x_TPODwutRS8vCs4pJthOTKHIazb_iu2ejKL9y_BcLggOfyC5VUGvMyA_bOBfQwSbMb_0uM_pqcfVhmSN7-ZgJjV31NmyIK
bO2euhfwYEel7-yJ4m9DaDVVOTfJmPNNq2wesYqGhYelkw3wYUcQyh8lNv_g-lBYt39bCL1TU0rRGUa-TgckpyMDe3g9QVuQPfujg6vcl_ou-cvULpEMItFr
tRokflthSlMNpv3PB-JoTZVlKodNDSVLT_C-bUncSSKrp7qtxrEL-wr8rVwLGfHTK3NLxNulvPhowhkvOLRtMyaNStcxcxTKEYobk9JBsvUlxu4pkVRg8bAk
2Kocp3vZN0W6B9ERswacowj-dC1d1SLMgldoGkp8QtZv-8zKCierwK5ltytDPHpBUzsGNnGKn97CFl_TotxizeiyX9ggttx4zxnxdNLp3acacLMlI-y2lIL4
yHb1vHHPMYhfSOMCBl9RRXIhcxS5WKGQAhdTRfqsWnH9ZjzoexouV1H0v83gThzjYnHPjsf7LGhGMswKXicqV25bEQRIpEvSuhhBa4if-A3YwV9wIL21HOwf
v5ygsIOJ7LIlVbZbIHK2JtRvSJV7JL0DLPqJGYavXAhDH4MG7xy6Birr-PS5rL9fALKfiNw2mH3SVrGYoO4zH8tBQt3vOinYfqhvcuh8yzCtikSyJruzDyyi
RQcW35HhLAerQVkr6_B44DLRleF9eKSH2zNZ-nJpayf7Z_LM1TfHJP7NG3m24GkLTaFe_RQBxEkib9QAQi8QZWZAIgNTW5U5eQ_Q9yWKUUADOhmtL50sAks6
Az-ekCAoKV6K6yLsRw1qof3PNLQggdtWpOkdoCjuRmnIxTt1XusgxH93OfuYBuEWU8EpKSc-WwrBHA5uzEgZz_YaIlYh7qSntXlaWXnNQZAxDF82vmxR31xK
x5qWsurodeh29YZsot90rS_i3LSwt2e6qlDVqCNVavVbteZBOgKg5PNTtAAKajolXQW-KmhRByAwcAXqMFBAyyrOXQZJylhJlK5ksIeEUE0uLn1ZYB9X_Nnl
vB0yAx65QfnBJqednX1bfEh7evoKAL2mpyec2lHKsGaMKQhpN3_S6xW-cHocrQWh-xWWkCYL_OUL3UvWgVwzGVx9jC83RuJAvCs0UX2hEw1JgjFZEeX7jQ3Y
XcUaihiUO2avfERdaVAF_mk0s4ZLtXj9cJp5PR5IzRcOUJz7fIgIcZz0c4lfSp40Zr612ifz2GfMnMCZLIiAXADe3acfclRBetet2WAEK97_YaVFWY-y5I4P
gTekap-AvhIYKbNjArLlN6oagWKLTu9IfeJEl84j5xf0tDue32oK3by8fJgTsGDhFDeBIj-ixBf2vAQR6EYGbzAIDjLzRryULCmlFo2icjjlt1SUfX6tGC1M
NjoR8q1cFOYPQgwSg4aXhr3XRkFqkw1uHYe26Ck0AT96HMkgvSNy-2oPgpymJ0MxZTig_QyjDEgAT5R6mpsgbr1A3hxz0OHSIf_BJkKfLO9Iwu1JcRq_BlIH
drCkENYgs-TS6qUHSIhTE4r_U-i8urIs40MGbQhyKysPy3Qo0a5OSMOCD8tz___jatV8IwLSQ1aWyfft7oFjf-xg4rBI3i0GviMdtLJeSO5oyG1Lhxo02X9O
_VSEONw8oX9LVn0wfgYw6lTqoRhOcAIA8bdjbVGCrTWL4jkkG4NPoqCQza3qECQxJjRicjVDSD-GhxkCCvvJwe-3J8M2ej2HEgYwpCB_7tB5Zwtv0GqS-wdG
upWNTtjWVujLDPEJVLSXu6WXqGTrctuh9wa-u-5n8XTtKlL71wXZBPduOBzipmF2MxqaODrKCNvx7ENY0QgkfLGv3iWBg7AyNFaoYXy3nnXIBvLzUnnEOax5
G4kToVS75SWBgOhlZNbk3A7V0u-pHv6BzzwQFPsHbvTlBdR3_S4S8tx0ZNu_rPPausYzLA5RNeJbPfKBg59ijCIfsrPS_I5UorORUI1GTKHvv69vxHS7gbC3
Gbn3XH_9YdBnzfVD_c1jYrmSvVS8LF31EQh8rH-M6bjhRrBFJ6thHSlBulKIzOVzL9chlyUfU42bxsdbYVL1MrvnZchFxjV690QeU6_IJJKkhrcgS7XSe4dC
0MKagBqk8atKx6CjLX7oMaLrrSNjTPTxa_H9CP2YmsYKBr14qV6pL5Jz_IWrDY4es_UyZxoi7NV30iLj9nLw7FV56qPpC5YxPf-LLrPST-X4-gXoOn9pOCBU
10pMhcxBEdavK3smpkkAYrkSSgAWjl3N6pzpyj8zIhdVov-ssKvIxKbjHL9TH8B15DMloyiT1j_TL9-wkArx4p1OgxgrpkHxMbuPJWh1-gdq96RBFmKLExO7
A-KbeaRgjnMEAh0lXdjQrM0TsuELydBnGI-LWSS1tX4SM51CXQzTbqTv7wdPArLKoIh3FQrgCAPQ_xAMkNokOkBgBqE_KGqsG3KcBy2Qfle8RK5b7w0QbXUO
QvOAjoAGRQl1-gZWxvV8QvQA1MNxBWGbgJgzQanUUO8gGVLdeZpgeEhmgaax-itrWvucrNVrTvH7__SRxZrKyybN_tkzFM1MiwQkgg2ut-YYca--7H_8xK5z
9PgiJRL3UGJrRAUkVb5Uk3qmUwQw5JEJL5LGWGKLFlhki-jV_aextcwmFK2goYMeFgBiDzBbxzk3-rr7X-NomdAJgMvLNaWLTRzXOjEZgEwsn2nT7rWCnbJr
PFj9vQhVo9sRdllZh8yERQxSeBeL9ohgDt2ll_TGQQwoN5vysbIgtu3XcVLGCTVwAEzdgOpxZOp3inuF7EVg_-0SbJtr6p0RtBjqnLZhYoXT9xMfja_gD-85
PuFTL8lbrONLfZByIHpkHflXirJtssfvwGyhLuiA1AMl5E-dgCvdho5prP-9qAJ2yaWFppgfyFo6l4By4IJAWyjCKM6_eU_enskdhNvTNW4hG3yWicLD5JOI
52sopkfgVVPIOrGl3mptd8kExExjpV23T93gxgkBg9ZWchZx7ohtx4qgkJgjUFrKV9RsA6YnggkRFqWy5qqLO1gDoQg7ghIfblKepzk3QgbI3LOabLoTLhmq
GBLQNex6iYy7B0TEgMuegRR6bUBhCDKlzYY7VRpAgtALp5GN51I6ZZ4FN2ylvwBMlJn8l9GlUJbHWSVnPdY4QhqRyW47VDYhoikHoerMfn0wvgdMSs5aHphI
LMpTqH-cMYyl_lI1ugLuENGbg8AynbHF6APQNqIX1vOlUrKaJNM9EXV7UQhrRbXTxwUyE0QYn_7pdd4FNDkZ91EH7UA5eDge-eF6SPXgNbvyZPWwaNAuNl77
dv-fKcfUOngbMY-l4AA8x2Wlfcebgt6gzVAoWygg1zPW3l8Ikb8Fogf73bCjxb6iNfl7o0xoQb3jKLufjWcgzKLK304ZEyXBKcsfSQMuuO5v6wCQxr4mQ5JN
GmUiL7YV_H8VP38NQwhhPZDKutiKInpPInKPKqKfg4yvvOIzIPjgFHVyU-o5GLxaWJ29KRbuq-yEXgZ6eppJe-jLaRdh--oOYzMR7joRQAhrKLuVShrA9--p
wroSfQ2GwWLSjKml_Zt045JWSTmNx-97vYoake_Mx0wHlRXBAgx--2SNmI9odcfUNk1wNkNrJCNL7-9j9AWbLEDxb7Olp5IvyQ0COw2-frKAKwsFydfxS8Hq
a9VKbNhS3LJfC_WWrBoyzFQWsgiPsGCB2l4C13NkVlFoYY6ANXZa9Qdqu-v8Fy7SyZVI4DDub4-flZs0YWdafQZq9ERAWiespZJVe-3su8Qzi8xiZGTbMRoC
-uBozKnjUV7sGFV270Fr7VrsDFTnfl4U1TyUKAfgLqoy5G514TEidUQp5_R2xSYkgZz-5p8L9URDfQUS82z9XPEOpLXGx7olvi8kk5anmHvkkQ3MS-bUM51X
zIVB8mnyh-Tod7BUQld4L2djBAXNCU4vsmiNekBoABiu0FLghXhPgHSkCWPU8WbglenT7-Mv5owtKaKcgJwWF5eP9TRtA3pbh29JLBKyqe8YGxtU3SMO_PcA
-eri52LUV7Glp96TgIBq6qHLYEdrN3pbl1KrvSooWN-zeNIFmhrmExBtb4UlFqn5KyvdghpjUNaPk_wmhcgnhYDxyw7L_LyxHdduWGIzC5A5BVeRG1s7uo38
YwXc1FLwDzIHtINKxVxl7dB38x8JrJiPIdCLhsH0fJFKEs5LUI6LZkRlnbMnMbJlmSGz2cpbtXgAYoYUCUaWyOPk25JSGxqnbwG2g3Vb4bHloiGzohlRgIql
jjFxSxqxa-vHL8PwVousrFkVhs8tlpq9Sorplly
}

