sprite $image305 [303x193/16z] {
xDY5iOCn30JXXqbE_upLVxLXHbqOzYjXpSuNeOb4ELOn60QIgi6WJLqU1ksAB2BMuHM9q5HbWa77vHg4JcbPHQnLC3HLPKA67h4ymQRbOMQPU4eVnuhiguvW
kXYnF44i4tS7pu2PvGcEmmbMv9_gc62g8vXkY-FGnCmoCRCyGInFOnrwydKrFGBhqDCHonFiMPvtZKMmdfu3Kyj3B5CZbeTOdk2YvGbYULxv6vvWUdv1B4yG
ozE8vHcrQxzR2jiw4C1PI6nB6gVl_xPbLoMxYAGwv2GMaCoz_Ki__OvdS82FnsB-5B2X1HRpoc3vOozQVClxRpwzfvRcWx7U_rB1xusb-QIxmxPOcXA0zQPQ
caFhbS0oQG9swmt1wCEqD5qmLZnN_9CtjGitzw8eh7Yk-6ihKm2N1xOwPuEZ5UV5_99UfQdG0nSx_tq3C7gvMwdbOGTikt6R7gBNnD8y_hisMXen11035evb
C_Nl6xvl6Yuec8UL6sDP6dP2syLm0Uu1uu21jn01M1gsN4uZX-POqvCKWaKiXciMh92Uh7PQCtwtLvfR4Glmo3KvOJ-05FUHrgHCSwmPBZjXXOWOCKVBFKhR
ILciQIxRICK2KvjuMX7FsG9CSbcmeZsK9bWt0aUhkHSBV2v0HbiEgA7Lch1hYULpQG4PqWfBuor_AowBvND1M2JWOLhZlaqsnlAvTCBYmAPLcjuTV2xh5GWs
YT982rZ01Oa52z9YmIAkAYBC0LwHMehbSzLhB1SG11QBvNDLZU7Qh97CFjZqQo5ObglESYbOmslfcDPO9D0uN4FzpGENg1Tl_nKhsxJ5OjLokOPhvhbIjpAO
Su3iw_5Obiju6QuJcqPk0iQQgTS3i5okuP5B_kCYvBmn61iIyt80rdAkBdMdGXisabapxzbsuNskqGkMAtyndK_SzxmHc3_y3Hvubd413rnI1Fr9YBkoMIEL
9FYcvNFPDkA1ItFbIdr_eeqttoOIo-S2vhYupypdhx9f8wTVZyMoN9fQLMkQIvA0kro-ykbqRWmMZ-L_8c6v-YI2SZbTJXseerQDZ5tuvLmfNNg145ykW0Ym
uNjawD7okJGELzTnoG3udA49Q6Ge5kJkotsPuT98JjHJ1hXB0ar08-Em7dyy8ZDS6f8-fK90lX0YmEAnBDWSbuPoV-cPTRksRMJm0uyDp_pCQvZYuiouBNxA
2Nz3Mu2zt6Xf39ZcaIkNnD1mp_TSVQ9r6_d2FRHScWUkKagML4J_LS6Vr5HouZN1NXwB10y_WpPbB5ULd36HIo8MKI_U0PR-ZD14HFvmeQIESicCnvpxYbhH
02nWuMKIQv9B_fuk4kHIoZJNJ_Yr6ybBi7WIIvJemKl6gS-9mQbdcD0lL-NS02nwjCQJPJF8DJUkKhBa8h19YS-fQgJah5xy0LXWyewMZOZSJNq1pCU71J9o
LIwzuFN0UClHibwwOINrT2KJ81ak_79Lwfoll2CYsBg75km7G7JgJndrZkloLMvS-IJGY0X_qC8JZrW-buA1Kqy04OQX_dBLxdGwa-NIHkvXj6nu15CrOBYc
ZboNqpMT62u5UqCiOMUqdZXX8vTwATUv_mPBC5mAjYyi3Uwz1as5SdMLlq_OLp5SeOraQJHQ_W6hmmXMW7DNQotdAzYbCrnnO8BrHcim5il1wesh8fs-GtaA
x9rxAFyiot07PhbgHNVb4iab1Yn-j6pmSC1gLYuDNqu2KAQ0HeQFbjz8vUfolOLrkoXn51YlDrggjIhO3rSXt7D1Sio4iI2cX_wjLPC1IeKD5y2v03VJLc2C
De-7oy7opv_A7wwgFA14DwvQMpGoVhJyHkfA2VtXAgGwKhBSk2eCs4UEbWycHUyDWbgXN8B2zS-4rMh0zZ1QDaMzy0rsSoZbBAXIgv0e3oVbCc2xmh8JnfcX
PwdqWihr6YRyv9ThkmaJX8pMSZ1ICCwTe9BI45V3vKnO-6XjXsMVYwHaV8SmSbMGLEMQ1jj53st62SjQ2kNIaE6oOFl2qeYPi2g4AQxr9unVUhHyCCgYvuiC
roO7J816NuXjV0kh85OkPELQ7umHqCCD6adQo89Vhc6eJYF3UcYm8Xgf4yQ4aMlUIy4-ThJyMzZuh0XAXckTHlAgerK3fEmjBEk4LUNIDgu4nj9Wj88c33DJ
ltp2106ZrUQvoEMo4zPoj8nMF5WfOhXSi9QZnT5Grajo4SFbW347Z5PyVYSi6Qwb4yO1enMn-GwNCs6hZfR_BNxyfGB6Qzc4SS3ZOG2OyLhQIAcrmKyUWYCh
WN6jGsqmMk5Pev6CduUeWCV3KB2w34okM3vN_6Z5JvYmQhbSyJUj-4QA28IrYyeLEbhnO3uNHh3w15R0-s7KX5akG7uQMKC-quf_a0IUv89EMFnenJVIv_e5
2nkj-1Fs59TQU8-D7p1QDipcW3bSPfPO0aShlf4-boqRnuvMF9ZFPHePziGJ3-PpEM1XFpsAlrJuN8h30O-7mO45yxd6r83HUja9yxc6sD6A_tHw0LV0JIiy
enSMSEsYX_xc-rmxml8dpEVQqsZv4-PpiNjvs4yZVIxni7RLI9zhnrWMx6akZiQA1_EvxEFXZhq0byjUImymXyiPhRszIVfS3FtfqOvJrClXiZqy3fZ3PNju
WFqVru7rkFcpNBZ7EWA7osWTuNcleShXCzb8PfdW6WwS6J0UmLok8p81vdCTO8kuZWdpkOwmo7DSXzVzHU8WyHfv_TDpf-l8y2JN0VOSrn5v5Qv_0G
}

