sprite $image356 [170x245/16z] {
r9PdUXj95CHsdRjwHhh_QPq3dEeZ5HvX_7Q0ki0dta-pFf9xFrcVYTtrtVh1dLbqBHAv9tcd7jx-hdUB4EVm-cVDwaG-F7ab7vwOFDK9l5hNy9_yGOd0q-oQ
zJ0Y5oNouKdidiIzEycMYnAx9r45sedyFSax-OCIkoSP6DwNwrqHLUMw9h0FJ-IU9EhXISoU98TvU7gUvpyn_3u_ulTS-pWVQFfkVFY7cVutFlm3JJFhUPpV
aN_YWTkJk2yJyNaoKE8UdhY79-xXYS2p34_SWH9teCJrdQcX2lHXfcyDmnFJTwQE-nDF75_g7sRwQdc69-xBHBI1TjDuBbCtzGLAZB-IkkahioTDTxo1qdHb
xyHmcRhfsyy_vjun3a_JRul0LJCy-IwNR2GWkKnavnTNrV04SaZ0uqdJuke8bAQ_9H1Fe3J5io9Np_0qBGa8XeVfdrqJpV0qBRaAXeTfIK3W2TFcEXveDoLv
gbnRe0ythRbE3zzDUmBpmtVJUh7cBrCtxHThVlXkMdx1ZdfsqvxhUA0aoUMkoV1b8hkebeirEJo_y-S12SmDpqwJXxloCZsxQNVj5ul33vXUbW1TPprf-g1S
6UYOwVMv9WXqslJQYnKCFsPwdCT3SiNmSwRdrQvV_zwywKwkopKG7JGzFWlaybopZsFSb2-L2nFu97aBKwfsLtHz6rEwNfBhUIjJ1iXSTQOb0PbfJS1bIae2
1jEUgykqv-eoxRcgJ7i2JbEw1guUqvvheZBj5yjbsdE5wNQOzWG-lwZ4j5-iZvw9nRJdchKFIQSzrvL3y8bgpueFlykKXAQ7qfG9H7jFzmTsvw00020205Y0
wz_tl1K0MuAbwv1fc3DzfgQcfgQcfgQcfgQcfgQcfgQcfgQcfgQcfgQcfgQcfgQcfgQcfZsZlvdxo98K1e8ml4y5_FS_xHZLj8FGW4m9nOxTr_KYyz6u-LBu
2P3MbC99kgLOJxe3S7x8D5QJGa5gh4zAmKYDzMafNoaylHsnWdIdA9NCp_gKL41PkibKu1af_5UQFe2c0bEbK9OUWA-wFYHDdEFdoLHWfXIkfHbeh3EbS4Eg
0_1ZOqsKxlZusO-BkhxnJIwuAKqHOUiwHufDUVPTNIFUBuKAgG6Qkhv5AYga3kWhC5uALL8PeB6EbqAjL0PewZfOAXgaSLJvDhpMQT8Cf--fsVcs3TavHWeD
KWVqRL3aOqrmEgbN-Oqrw6iuT4YlLsfyVFwgMmhDKia3ptz0KlViGvyqRgrKTS--g8k_Cd5TrssJkYQAwZJDq-kagqEAIVFibpTMz-n3exH-fUOajKd52Aba
WUR7ZjRPXp7IxUPAJOsp3wEaSRtpExupiJD6wgVSjs5Jf6ef399wbMr3o-pJdOPJb9nGZPGXQLcfaMfcdr69wfMQZNUbmcH2NQjdduxq_-EVdKRgdJEiKQfh
v6Cz02tNrRRXtv4QdLCtLjBbH64olQvnO_Q1sLP_PK8oqXbENzVMAnDCoe5QVML2c3nJWUmjIfcQ_K0zNvaepJuc3rQWEFi02rdBLoQ0TQnHddqUZDzO_ie4
9izNu0Did6jPirDPQg1hLC1VcM2Pw6ZDn0yfIwLytpInMWftpLam9-cMnA8vIbauHhguTNqee0yfwoTBcPtV
}

