sprite $image252 [89x236/16z] {
xTo7Zjmu48HXPR83t_zr3yG8MzZJkZoQRbra8Jfz47wunzuu_RnTZddAtofzMpQx57cjhgdkflAriYJ2kq7McWgRdRIvvC8lMhsrVDZCMti6RlySUC037l20
1spRGx1BNHw2HOxv4RXlUmRkM-Fk9XSuu_z4QnLHmAwd6qmzbvUXBzWDR2Zr3aFD6bY9_VUpVaDKvOUL-HFOJelk-0GsIjzFFPUwdl0xzDjNlf_np8XyF_Kc
vtQp6_H-vw-2Wewd1WBvJPfVEOpR3ysl74Xo3xCWlN8uEJNWvDI0KrC3ZjDr9J19VVVA0QUafd0yDM1EswtK2u5Z3rrcmCdqJk7ubPUhc7JbYn0vTkMRFK3N
QLf5D9isbwL8tyMBNBbwQtB-iPI71jjXCqcbhRCls3I3nkC2DlGWup9Om7snrAXmXUCzpDi5_ep-zhCA5h1xj0VOxt3pQEhs2xWr3wGcSD-7gNyFQzNxFTJz
zt0fNxIyGPy7yHPSYjpfqRbtuIlzQzZRBRYGr26uqwH702Qfet0VwH60IUe0J5B7O9Ow0lCU8PZJ8PZt2C6S3iEyXyEzmlKASrf0-yd-21yKvZtSpG8meP7x
3inJOo4Oz4LMJu2lFTHR5COKTFVoOAJsbWeZTKk3CGeFUC0Gqk41-xyH7l201ppW0G_OLQJcmvtjgycmoTTIOLF1QXfCw0YyL497u6bQzIfB1ho9aeV-65vh
PmZzATmjo1Sw01legno2kqNe2Cpf27pfOI9O2EQfGp3l4O5X6QNlmxo7n60pqYC4yzGXsEYLHs2UEWJp7Y6Oqn6Ofux0F7K09Zq2CA43C4yTWddg4Cnxn63w
WXg1UUeuZA57BepKsJ1wX65E-ya6uMiFxsmU3Dgj-oamQ4m97A7LSs5yI2WPneU4yk7EFGIt_oOyuFqfUCs01-nFmWCUy807FE013xWy1K-BF0HFqwQFm7t7
K_0qrtputABvyBbTas6i9CFOKfDXRDLycAUEmzDSqc6UEWxZolDWR4-7aJePnXP9Xh5Tas7iI8QnkQR3_Cevx1i1QMeE7zExAtVWEXE9NJc7ZTIbLyvXtmb1
KtEuKe1SEOTbcJxT8XVO-Zpu_NQG6l3HVyQR7rDq-v_W_ZDUvoYBr82dUKrWyTycnpNaRLVhiAvJ-Wvp-bBp1m
}

sprite $image252 [45x118/16z] {
xTG73Xin34JHxHB9OUv_t42GmGZUKPRfbUxs0_rTbqzpohaaPwyYMlSSBYOYQciEmzI0D3Ptv36-0V_7XMkEDVDjMgirx9blqo6gPcsnY6ZPFhks8vC-AjSy
_K33uqpIrwji1ynkdAIVeYhLxAPP-ileZRDqCyfvkeNHu2GzC5dEqWDR9Zrm9ZrmBbqHDf5-TPTAtoxL9E_tTFsGRl3N7O_B5UuDF_DEEtwrpBarsJ5W3-a-
O7VLQSiTIn6Uhd22IrN6uM0uUDU1dU4s4ka9N8Rq11xI4tX8J-368_tjtL22ntIrm72XkDJEct_6aMu0mPp3tGXc-lV2-6VnVmoLciCmapOrWwkPAU4KBrVJ
XDFD8agMSzmSunntJJZ7dT_IPvYtSCmvnw7V-1IJz1dcBS8nvph3D7s6QNe61y_Xu70mpDC18vXpLL6EERSiDZLu5ZVtrLX_sERwJ-7_65-2JqKUBsinfF6o
R1LPtEOGv72VIC_WICzWaivnp2x8OPxESQHV1ew13u67T8O1zx86Okc1uIvx09OUk9qVp8tlUlppus9eJ4V7Hq4biIGThij2A4ktj-V_2
}

