sprite $image200 [69x217/16z] {
xThPiXiX38HXTf0wUV_N3JNXbBiIl8diqN_j-SfkF7U4MHejXiEApCgPaULgv60loaSzcP4gjseq8iADOboLilwc9jzcEEuXb7KQsJMA6R5F8vHv6hdRU7qQ
bGTCFa1u6WDYF6u8PJrkg3ohvwS8v7ajFKDKNgW-H1GGoZQDy5Un7dV7HddtJIYO2MMP9cAcyceZxn5IhDD4a6AT9khxYfGDGenjcgWcHLhQ86yhKYCZ2Xip
2YCA8zCp8Gehq-8DKN2gRqwp48MP6NaYf73wEjIZacA1L84RGWod3wJr326aRAcLR3uz4Gw65i8T8Dm1mfqWd0snEpKIOe9KTVtjRP2kDiWpJYb23FsVY2EE
EEA88uuuueWZZZZYY2EEEEA88uuuueWZZZZYY2EEEEA88uuuuaZw4KZz4KZ_4OZy7CGH_MCG_6C8v4SWUeueS8uC07AAD01wYcJCJf6Wf9YH1bAiICBL6HBw
gPBvEhOS8A5YTO84mKhb0Fa4Ogp8vvi2Ey8ApCXKA1ko59lJqq98USyH4TM5N8e2Rq5o2G08GMhOjdrQwDOh8o7a0Ue1XjKEcOpWZVR8h8mpP9Nx6RAAJSm8
brvsf6-HLInTdm8bXh1766f3i4b7hta27_MlY8IxnLngQ_sgjLfo2jyrBYC6Qry
}

sprite $image200 [35x109/16z] {
xSu5biKW38LXWaTUzx_SeUdmbARZod-iyXsu3ahnpguGOG9BH494gj4y15T3ncqhs506YsWwoIJxa-YAw2IJACB7INnBTD8z8TICIIYRCIPbOS81od1Dr1YJ
ClFGwAHEkXbFKa86mWoTADgRr0WH6ugmaMuweowtFwAaet5AJ2HAJ5ILM8hWYjnAwdabHlnXP9999fbaaaaccQGS4te1ePz3-4C8yY79maV4C_C1SKNKM0I8
cMtYIBXb4ZwnjaUWaUKaOgYwaaKAAnenbes0hug6FHFdV64PAkca1QasTUtq3PMSLg8gvaeNWZN7zLTPbWQl0XzYZ25uSDeJ
}

