sprite $image367 [354x273/16z] {
xDa9ZeGm34JHxBO3zx_kB9bzCgkRGaIgTuIlbgc6iAWYKdCC89H41qnbYaq7K6KgEf6Qma4eYtwjbGCgKsewO2fJh3g0AbCH_TvX3pykD6nbBZHGPIhgu1bo
N6WpmCEF1zWZ1mSkD41Y7c2_6XnuW069kT3yMdYFgXvEmYigeW0Imq195EGbCGymJ0fK52fpeIbOuKSCjCg_o6YL2mrDkD3G97AXeKKkDBJ8XOQMkT3GCXSQ
MkL2GwjSQ6YD2mrD-143JI8N6bha0KPBN6Z_n66SJP6OEEgsTODLvZ0krhUX6nC3PBENme3A7CP9xAKme38JnsOs5JwkCeTnCNihFEktLMRYh3OLdlWd1bTR
wJOLFh8o4zTj-qDZ_rdcQgkZszpONvc9vyBJp_YIbTl2XUV6bwmionRsD-PB-RyMdXFtIoRMk6xXkV4LBuN9geL5t8tFJDpt7XSjN4FIbyHJuwiajctVTokh
5WwXUi-ndTNtaPdcLGidzpcsKmx44tiWQTd29hx6Xk_xmeQsQc4DoLpdsCuu4FVKt8dIwoOC1M2PNSBl_xoTXC2n8-8m_c-ceEwbwnVcHCZc7eIPtMB2iGeJ
kLlRM7xeApigSwcLujWy-PAfmdGlZkMN0G5WOTGw9xpIfqNNX2LbpIp_Ir98LhueCOiy0mNUIpYH4INytPX_4i2eTz-ysqLoM2eUX8cyF7GJS-B_XLW719_g
YR-AS8PnCbMOKWrNOHv5vXy7CAeihYESfU75Wt2Ir2-kbRXF_Fk0M4qu7w82mkG687h4l_TTJnZ6Hs4pAeoINmS4y9SJpe8utcuBP_bv0AFMcy1BcwQ5sy9P
-AS1iQWmotjKYDmG_diOyxSERLLXlqKLn_U5C_yg81OM9Z99nN6qDuKp_o0WTbshJk0Hnt9NEFDF0dXzOJaQtnA-JpmImEiBftCSZmYpt22-7S3h2nCP1Z6F
27yqbXy518eN4XP7UW8lp0F2dutb9nqQojCYvQLCrPemQa3uafX_5n1xNkTvg7tv9Co7jpIw2x-CDVdVTsZu92JRHMuPW0SJU2EZmjV6_9C0tgMiBZFvQSPY
gp0HZmbtNX0Q9xuPmBciBYHydAePJE27XBy-aUP_7i1ILfSIFaxL8eHD717-Pin_3WWTm0lEXn4LToRmScai8ntQU01pNdO2ZpWsPs5-rkMfUOZuxm7njhgj
Tyi03pcQCBzz0Y8YNZWvvsoI7F8tOzqOIxuVm4kUcliFERW9-uHLdIHR737cVzMXhIeSlAWuRiA6dAXFWAimaS7gPsE-tw4XW9UU_FGUSfWgJAHNnH59pWLw
O1lpdpkqvMThhXF7HLYbTUsTSnDEtutvhntQyi968yfHEBAEuoPijk_6Sikt7n3CUKbXzaVZDs5FEgmXJ6I_nV5LGEI13YstF-M8YDAAmkajZekmgyBTEBP5
UE3-xXy3ED1UV-TP6uJNkcLWZaob7uvR5JQzEDuWp5V6V-hGqaRqTf1ZGokKAoZYkhSCYd0M3-4aAewb2Hjp4SVtEZIm5k7AkiMuWh1Dw1jy4-PmEEusiYBS
ZMC84tfdDTVyon6Pgh1xuFhNM7jwuYqoip2Bci1l2S8iP-5-79igJEPJ7DzuYF7QoqzXz_YZPuxjkoz_ivqzWVbH0gRCk6LWfGhZ8Ds4gVE-PjmWB5tZcqVa
H67VoV3kNxCUUQnoe3oviCFkEdO6wfO17rOzX4KVfAK9-_x5n-40pbXbGm_Xj2UYieMt_BfuE_VqqaI6yEaOPo0SYt0-63VXr8bZ27VZ-4Q7zYIbKA2ffB1X
biTltSp2MpWd99Zq19xFdm24UwCCDYf9O7ndXXPUmlIeyXiZ-VbRdbZOCGgkC6ObV5prX2JHeuouAM5bFDYXQU5CvOik4f7TfnMsYPMmxWmWt9kgGLZKQiG-
DrYzqQ4fuHpfKUdv9p6NcB53qyBw8GU4EyOGLZTjpac2i1uFu8_27AbLcdMs5fXxmaaKas02RzHK3S8VuvZqQt3Z0TmN5Zu3xvC7C8Jx1pK84paT1hwyjV8f
ZY6Caj4EBVU5swDF8tFEXqtYpyBOYeAjwCuJU1t745Qh0SAk9T58G6HB_2QSvIMSg8Y_QkO0HidrBGC8Yxvs1s4Rb364MnoF794zqLCuXbY57NETIqW8QMyr
Uq1eOJc6mRkmDrZjJE0tVTD6jYfCcsXXtQ5LKYwRrJJXN8HHqmbRvX7XTEuCteIf5zQ-2XC57SU1JadofKE3SA9dfVA7Vjyd5pQH1uMFSTmcyCcGdi0VHncO
mEjLtnFk1p248vLofUyB7uJJL4VaQs7ntLi6TG8VZy8wZgK9swYChuKHm1166NOGtbXrSXC7C0gTGHD673Fc4fWFssDKg0cyqN6SDosi0xWlZ3qSTRZ4-Ox8
ryQOmDT85GpW8VmnZds5Lf-0Xx0EY9wmAV5WMZ_ik-5Y9-pGT4d_ba5gmdMPDypDkgCCJE3rgeFmnMicd5x2PRX3hWbFUil0yq39-Q2c9_3u1C9HM1_ZOXEE
AevBNH-HiwDGIBsK18Xxw0MmJ7BBmF9GoLjde8G_pCsSQ4HCuDKe0yBeq5G-LE78HLWUVnW-TtTsqWvD2nyX4eGf5k61kPb-Mkews_XB04DOTb_UEGbkqbi6
M-3HaY-t35ZDDLkIRDARgY59r6ed8Fh2ks20Tj7TsKaxD2sivsP5s1PXjL6H99quTarOqji_6Y5wBXUgS7Rqg5SdqP-_eMRjqBImdYYOzgE1SQypW70lZf4a
RwECKuYoAzkqP6sTG3Xg9Ly7zDDsQ5fOjx1Hch3JSqq84tMcQg4AltN7Xn2jDsQVJI24nGDuqbi6WVc6iEzinIPioB3w16IhmeXZqJ-wesxiCADi3zqWxDkP
parwoy0ntnFkTWRENTqoyFrR1bAMuq4O1-ciHZRX9PmTlkciSEvrQAfcU8WnBanMnp5VtZ8GYwbEr9yFXDlBstYDvqtO2n-4muIt3D2XtHSsAexFmb7FT21i
z2w7y9Em2cT7fSmX9HoBhS8sVmbWrDm1eONLGUqixCdegHg4oR2EuqrDu6lG-jTZJId2ELCHJjpjqFerPOTsBVpstL-4VHKkgpgECO7N5ny_2AUNpxRx8coA
yDM0NjTKH-HhuRHLOThqBODahcuPY86mZcFf2_FhwywB8zJL4LaNR_DsQ2XinQjR1Zb6xFFE7LnCu3STnttX0hmnLs5BLWOwD9H4CtK0e_GB3kmbevTGjmpi
vIq3apfl2-gKi5I6Q1AebAHlxx3fLJjXXwPBk3U13n0-7jJCLHnZ0gz76KTXL93M6wVn04PysCcEoFsI0uGqOJBIXD4PNCtDs41OrAf8HpZa1rONM8RUSFkz
iEU_bvpkRHtcPbNuE6-mQcwcBtsP_zWx3zt8qHW6mzs__FxFUtt2YS088NIEUONeLtS_15nA6lx37zlzNPZdtauN-tT6P9xVbeUF6DADW-tDjfSFqxtPMhKC
-97Z_Id5NIhYyx-xc2KqhiWH5eInlGo-DoDxpU9Q-avu5Olut3uMcn6PgsuPW73UwKnlJaAsQY_2n8v1UDG4eT8-PjE4nWadEmPXbWn0cBoU0YT9dnRydSrr
L8GlhODWE29pmeJnc47ug5i6KRGCqYhZTmiWX4K3XcmJ6YSC47a3Fnr5ou0TEMBvkcLmVaauv0w2RqBZX84f4KOoI7OSNxOCplchbW5yM4zeMQu6p0apEpxA
bi66lHcnumE4yIJ2wq-wwM8MA-StpuJ62NF6WxGC-Dvitg9g6Io1j5OSCTJyPfhGQiB0b0blqrcr3FYJ21yR-072QokXlSlU83XXnAj46Ca04Ay3BOEDlkwO
jvTNr1QhsCTYcz1gmi3q9-5OofR1LhKCBg5beF_TSSoU2QqcJ5e6vmp2R6-6bi4MdPQ1RXzZdnuvOlG9vmryO0DFLkpOmBFYupKBBGCXl_sbrSY0TSAyPR0G
EqRBO6LF8e2mDYBN-IBwtpxUFsBq2ICPb2s3jMmPR0E4gSNA-MtWtQ1nJ4O6h1F6475E8Cm-88IMmIQs37G3ZiylN-rE1g7xC32TsEgyst7a3JonOn0c2KtE
RzS7wfOTBsDO4BvYiBqPZXpiMZgJPL8_eS4-Ck5npWOZSYDB3FOwno1sNBOCmAXd48ImRiVx62w4SswOgfR1kNqG7djYt4feu9i9Gvi0-1XEXFEj3eJdKRKC
qYhZxqXeYNYMaDnM8yBLTncm8yU1Q-dooOxx2GtYX9L1UjfT21F6-5OKRiTBqJBe6N1DM1oavyE8CFb1nTwC7Jb067lDVaAh2Ul9RR4ZV0LzdMClMmQlxDnE
Q3LXw7IouuZl4HvRLDzbmEnul0Y_idD5KCyN8Enkn_4DmlaL_hGtm_ei5n_J1hwPq3XXhjrdzmF6DM6SdDCOXmqyEN8Gmkg6xKlyezRgbDpYMuG_JSgmuw9b
G3RmWW4ZeQc4TJlU7a3C2F_EiMWPK3i6uKP24mbZa7PUOtB2cDFUTphBYp1ztN7cX4EuWUg4zK5w-K4xveHVciddDNdB01yG0c4zeUc4_UsO4uOsOiSh29_1
MmPoGkiIrlUQFvRSQiBa2SQqWUT73j60kuIXmscGZf8mD9y4ulAnWQSV418JMfymj3hQCISCBK46wR9b82UqFc78Qv2k2TTs3CAHxLWmY2PX_q6w9WoHGJgm
WSyVtXOIMfUm_rupAiAr7ODmxk0AHum-OV-zPfI4ePNQCMyPA4UCFc7_GVfRXFd69vOtmh1ZoO3xXFq7QObmBds1CDowaT3ulrJBVw-f4-OjWvSTTmoOkmgH
xI3T9qpscgHbe8_8N0BVfXtlTnCEXN1cF9CRHzE0mRUbm-BZcVXqgq8ubxv0-7c3WFRdEnuWF4O8X8kM0KVr05-z0BBUJ7X428JpncS5OGE3W0iRTEr0U8pO
9CAvWokq3CI4fckrw8k2CBGAX9DL7CWIJnfmixsqt4OOxgKGnY3zqfC93VUEZjQR2O_O9SBv1FAu0O_LhFeCmj0c4CwCUoDoNxj9VPyJXfQ2S6t73oUqoQXX
pWd3ZYN2-34sJMYwjfi9ZzWLmc3idj3QWtIVCBGAX358soUqzbwpJnYQ6U6QiVE8h6kzc_0u9utm5Tu9JTT-C-4HcqRuUiA0DzUtSq6urDeWx9_G-dlDFk5n
pWt2zWcjRyTzmYFsGoRiRy3zGRfF60g1i6z2wm_IVS9zngu9hQ_b5i8wuvypYCN-Ixz0k5zyXAn7vBuTjmdtVupD4rf_a6uIxZCsFsBqjVO8zndR9xI-jWxX
FcAN8uR184q9zncR6B3H87qImXt61YEoYHrpmdt6zoOq9-qDmXt41YEoqI0Dmct6DM7N4RblnpBXFcE3X6PYntt2V90sE6AO3DASSF_7s22XkTan8TnX_Ez9
Q5x5HyWWeLcdupxYVq52Cty8tVg8eSlmGRVxZXZ_MyM83yA_jdC7HWZ3C1H30TpiFp9JF02ZFuHEYdjTR6YV_w6RDhHmlDxGFly78MjeuNZ14GE4DDW2GmCX
3GOCBHmp08TZcyZXs7zc4eu3X7_Nz8PMIED4BgGN9B9vrmp0UfEXyPqIsUDu7o0AwUlsRviCpOTqXkP3EW3hFJCqlidGF8uxOlYGrW1kmmsjNHqnV4W721_I
-eZHXXjQEpwHmx47S3ZMYTp66reX7I3ykwO-OhGdJ-Gstj0oDm_WtZMreRNXYTmkVyG8nzxG2cbjQ6sueRNZ3QsGzeOMZhMXjV66rhlcDmFu1G
}

sprite $image367 [177x137/16z] {
r9c9ajkw3aJ15K0tUV__Sr-P5YrbEAgCKrAUqranjHr9fneoBVSbgfOKv5z9A3PIyxy1dMraGaVvx2IrBz5FXWxLPZuTUifx7YqfVBWDQrG-9x7Qx-CQFjw6
FUvcRl73gkmyllqTFr_UYJlYdZwqobRSIPm_NzulS_by6pw4EBvdmnwl7s_3MiWVN6NN4zylxngt-87oVWhnE_Ak-VihH0dtFxszVt-5P0SVWR-D-_yev6Hm
S0R-5kxVB-HG0NVm4C0NtiyXJeJx95wWtyQzlv0JUK1UeTtUZrku5vWuGIRy3udZdS3-kidWaZyWTZVtEu5JmhaNzFTn3Qrfl15Ob6YdNlXxhMRcxBt1QxW7
k3s04NJUv1NPtyHjlVNcZfksdZKaXGY65y2gCl66l6YzjTxWxe3Tu4Kma7GHbeIpli1FR--6It-csJsB0sGDp98RjfSoTsoPzVPZUNiZV0IjwqsB0sXu03Cj
74iXdzl0QSF4lGju89E8cK4Nu9-KXKyRTboEiTu2R6Z4GCOvCEc_iU4exy2z3JW6Rtogh5-1dGlnUPNnO4Ex4JY9SY23N72mh92VsJ3otpt0MHHIXidV01s9
ONvUPGjkwqnoVPIi1X4w6h42-n4Plw-o7RVHRm2E3ZH2X3aOLoM-B19ykzY-m-q4kjsY141w7ZsyAE5VNppXFv5t_91tBWwo5ScC2t3ZXdmWzlCgcxYyTN6q
PwULmg3cu6C472LMrFK3YPkVLzcEUr-jLHjGR4HKhz772BOgXHAnV21nMsteatUy2u-ntzV3rZOlN5qb4MDcCwE8--A5evtRC77xRJsSHBSd3ze0JcKR6wD0
PV7YDpRWyRyQ0cvmE9DL519d1R2aiVkcsHKgYVOhycx3KcNipD8weuYKUFsvZuFD729K7uk33GzWtrHcQoQ98VfHvRCg0tllLL9hKKfIbEjF0HzXGnHcqKOp
WBIWBW5in1WBWoWEAfzK6LjdXXNjAgMXgCkLYGOuk3tviJZKdC3OqI8ikyf9r0ugVoSlq7g7Y2DAYrAPnEtoKq07vvElaXdKkLr15cOfZMqRpKI0CNvRPMFi
BWAL015rYLSkZkBxX_f6Z19JH7NthTDytFCyLQQ9CCSndbNP2tY01bnNQyds-yGyEwqXAQheDj92eSYkScAMsaP9hrL6xxqFu2h2A9BOhreSKG7VWMU90SHp
SMnUD3X5OFE2-01cgEJHXgUy9gLheOjOaT1G_M58lQhAt7y5HlB111l0SUpZ3H4gcPlPo9KYJXvj678aAKMak8YhIEjFGyerLUQ7F4iC4fwRmfnQnZt7D9ig
YSLdNs00BwyvIS9uTiDXxTl5X0lbdG4Qu2AibOGP6eyb1ZQNn23MDfKrRi2zJPV77HPD4at4WVvqnLclgR9ZG81xYPa_dxpvgyJGe6DnABcLD3aNsvCNoRD4
PYakSUkBKNHsGPKjmDkJ7oLMpCV8Puabp4xBehwTrZj9pYhhxLaDdYKpYa4dhhErhfVQC85dYKbcLEVhoOzBc2ghcmXjZhFAq5k5YrYIa2Mstezgztf1bQt0
Fe_N357TT1ivWAFkAWlpV7KUyjOWmQC0mr-HEEK5DY_gTV8UQorDBrWKLShhj2sLKM8RCiheOIFv0B8mD1Dn6qeKR_rOT0FuYYfRWVSIutDnw1m14UZhWbgH
IdcCdKaaHf4gOYhYfRQZ3VFavn9vL-3vbG7St2KoYhrEsm9K4gVPLP_tlBj8-az7ZvKeuctQC72tz7of3HFuy9M1cpVek8HDreQnED9kTfZ0nOCK5P6GV6wA
Nr_eFLvJPSVW2RgL6Co6og8kULSvCOYsgN8UmFFyNYIWVvLt6vjTQiC8jYS_lpBmvsZ74gC_W3rFbKbsY8Wyl2sPgxnpr6kgx1Xy-Sh0d-CiiLdIAkeINYgp
Ss-nlicxlD2_2HpgYGqdYmCnCvgpFMTifsrJPPW8wwkLJQHyEKbRnrulgR8LU6i48AfhFfHOfkI9Y2JCBvLT90_2Cnjc3ryYxmeyIqndYOsnLeeui8qw5aS1
YGPvlKJkLVQrsNgzfifMu95zSHGxb1WqR2ERIg44a1qP6-ykxnpVNXoZoju5dei3CMwdRHm5aN0yRNERdpYMAljsp1VQi0AJC2ETITJBw-3u0HptJalYv2Bl
oGXBxrNP-y1Z0OkwHBPvS9mP3wTj2h8jLRRA0ISTq7Y1lEV0_dpoeyJKDX7u0FQucyt_rMecgh43CH1ax_l_VpUUTOgDO7eL6hUutijP7ZgbGV8_qh1UcCTh
2AT_gCm7Vlk2QTlvGQzRXFSUKQp9VeWqrF-km5_Ud3W_2gyBZEBUZUCpaoZJDgcolra1c5oaJlZ1j6qC95WPZ2ZlnfapRHCgA-4Om22VTsqxze7N8DILmOZ9
EoI74MKTNi9HW8coi8HB3F1jp_szh0n6b7-dRO_luLt_3p25ueI77MI0bt0D5vIL0JC96eTK6VW5M4JPw7Gi0IhmKYTomSg0JTC9OA4o_bk1oOMAifaBW4Vj
BdIAwsbu-7xxVOBneQRF2M2XE3_A01Ek6r6kqxQbfCeKS1_benFb2lmtoYTM1kiJA9Krm4Hvjr6KFy3KZbCjAuFX2wKo3PnG7C2VOfXTLWRtkr9P3qmkZjie
3k2osrsHHpfEh0owDF0aehRhrcCkCG7-kZAuAznk8dBUuCOvtaeImDzM1hLuabBA5dwK0LxgC0CcogmCXCfa6hIF_IW3pDKAu8BCoe3m6cce7SzM7C1u1-1Q
D0wPXfT8W_w3SwCCCDwP0w-DGwZC3QzUtlV0zHW0fa0sLDOq3Kzn0EET7S0Ko8xA-9dMjBW7vZG0hcMhR6yjatfWQcp6PnLGcQKuWEk4Vb81bLbH1hZM13cW
CaTn0FV40PKvKGQuHmwep8aom3roG6M6uW1MltS6t8UtJuCVPO3xGmwepEdM0FV8GPNvYjF83BI3AjDrjiP4KPNfycSkKPNfyiU70PNvYlFBlvNvYlFBLra-
ohxA_FB7XscLvQFigomVvRpAyehpLPRlrlaq-6z4PrIMLrnUPVae-ohBAouLthpYyYhBHzbNMRvRvszb-IZxAilNZbnCmkkc8Q-uWChItJgWihJY0YfBAowX
idoKxm6L1HKNK5bMSTkcuGS
}

