sprite $image230 [283x192/16z] {
xTeBbfiw48JX4oCXgQfbzh_RUvaJx7X2uIWF1aJ_I_XEjoG_fZqh_vSdRnLcRdhDGvcJE3uo6iTXbkWeSoXhJHwAodT91uVH9TybtNJ5xWB3SSglvp2wV7aO
7vnSVYSV6HqSHkUxj973w72fNVB9GVbRPOVHNU3ZakEKVr1s65tsGqRd8xEHmspaCBhi5xREHqQ73c1ySdBPl-0ZetEOZHn6HpzaT3uo6pdCYLuvBCSfJmSg
b6Dr-5ro79GZ1h-mTNVV9Tq1TyctAfNZvxkqaU-I3WwZW--Ipc4sSXWThlFuRI_voEXslvSSf_IHo-ZWC3g7sSXFturyP7JPONJ_2CPnK4H-aPFmmLcFoiPn
ICSHaPV0uU_J47xa21hVAa7ZE9fcoLyvWiQF747ZMoLe74VGN0mdjz1SxSYvjzFuLZsZoYzowd1n76w5SkKZXoe_SXO2E8wYAGLNFNBoDaqUKyhmmLcbcRii
3jxGp6LU52U_fHbJkUfM1Nb3bPp6ZuhvaRFGF4B-eAcSSno-X3JJ64dwaSDFbON6xof-3lXEupZKcLqJv_uMfwHSS4sSwP6YIGBdIbi5HPDIkJmELyffBbyL
PtDmIlgE0t0bu1fZemTdRYmN6npGtlwKcTFSE99Nmg6PJI_T-NFueCdaTN1WSzEdn5MLZJBq1xD28t1GS9dF3g09cZdAh9hrZKDxDAq5Ykh_6Vl5WPcaML8q
NTl0NffK3JHzu82cQTvVv2PiEi2XVMxQ2Cqq14wxIu96jMvZlLtae4aQtPgDSJFq0ADfD8xP8eC-S62YIVR-8jSumEbWD4qxpflp-9Ixf6bqgpIdnn4mWaQs
JbDFV1x3H896XzKt3hS2phXBcaQtPiEv4el2EH6Cfcd7UTA4Gfm91oOIDEquHkDSIRKQ86nmHXXDe-DACqsrU8x10Qs1fYr1KqkX2eU-i3LDU-iqBDJXHBka
QTfnCDex6W8dsYLDqswJYZrf871E1ADfsd5AmaAJmY5VERIswYHgnydZGXD970q7hJ0hD4rnhLGEzye16s6gJN-QegaC5E44ksH2fYr1KvFn83YmvgQ_r3fD
DkfmP9WwDTHwMPcWsTy6t4T6zyg0bEr18y_ZJWwPzYSW5feOv4NUnuNTlbNnEqt8bL-20-uDepEk5LXhBTZTHi9eckaVjafZCqsa2DrSsEqueSwLNIyh76jY
bjPfClUpmHVVIpgkldB8lN2-xYNJVXwdzAJ943Yz73BjNtGjDBU0Vua37dHYzB_TIdfUvQPiEjib7IYlShbLEpz-Qvs-A4YQH15slR3lqzSbQFx1AmSysF7R
FZYnlg4XTZba6dPflrSEQxN2hR33XRtiqg5mShA51YEuP0Bddy1mEaZWIqWvyoFS4l3yqwJ0wU6GqV4rB5CJw-ELOyRViJahZCPvqbGRGPBL-2diy9NuCH8q
otzFhFAdqDSkwHHD5LD34jZXKy4XSH2UD5Qv5dRwIlo0hnmi1x4PruE0QMuwUFUVS6XbkRn5wEkGqHbVGaw5SqOPqDU5hUDh0D-6atugQ8_juNT_TxCwdIgG
xnjkvHCEEhgmTNnRlgNXXN277r6EZOEyq4IE8t-ihvTCEyuOneKc3xTOo29e6l-ET_uZ1mm0I28CyHQ7CNzBWgRXQxm-1YVTC8HCCePXoEcMGa0pZO0vDyw8
K08YI0pVljrkCOSnDzASUfVqPuUKOefC215bB00HScoZgLCtPVvO74eWomE48GT-T9M9qLi5HkGqCfQOIF9ns5ndOZHEYKCU6L8Onq9YkFqQJQr2fYSS005X
Z1XY9f4JNcXaKw_nnr8SKaH48CaYQCGXqxjDpZaYCe1B3O_Vtd5A4ZHgbww48sZ47sMwp_XIV4_JEun-vJnItybSAguc3nd7aIFZEF8x6RUHJpp7aRlaE1B6
RUI70iUHZr_7aVUIuyX3nctan3ZEpZB_0G
}

