sprite $image167 [275x208/16z] {
xDc7cSGm24HX0q8m_HTyEUlJPSVXxy5lMEsoA-tPbbT5F064Ba-A9HvrMUuK2xnoMUX9npjf2xcM-AXhHUH5VJqQcCWcdCCBp8KHHWHV26KTthbqOHtUkMmL
aK4QtINojQwqmpld5H6cf4XB_4uOxV3ETQc835nOXtSkZN1uUMvyIqoG9aKx_b5U82cU-5zf5P5B9SK2wt0XkDufRdp7gjBgcnc4ddbuwPCYZgsqqpq1h2-i
8ZBeMX4vLLB44tl8ThvVlAI3h84zTIMuta_-RD0I-qkhY0p2ZZcybHJ7eQHNH0vsfLZWY489XlSSVsw8uyYQL4Jslb8qS7nTAoAx9KKySHRPX7Luvy8g8eDG
sk6TSs4Tthbi5P51sFfF09KKJvnTkbH49abX7DwvCCBXNV_6buQhSLdXxPquAVFXvHXalsN7JdJjX64WW9Ob46R6_F_VTekAh8kbT6-9Bsz_qNhacLXiq-zw
1J3AknGIPHhfultrDv4IMPV-nPleGfOaiivHYIIj53KJx5Dd4ycpfQWzv56FF4zT-oGIWICJoj8XoOYoptqICHbAcRea4W6ahnGfDSg-T4WoLiesTqdUbI8U
e9IyKgONaddp9kyBMKHTgyDuLuea0fS3-QuKIReSH929AoLUrIWoRwKi8Ob9YTEppG69p2GgAqejqtqXaPbbJa-zJqbk550taXDBDREabGAPtKdEhSWQIhOB
6JIxau37V97aIWyeYqZeIL9LIWE9I4oYNIHcIIe53IGcSKVdlMS139oPc4Ho9ATPS25ZO92OH8uaHi6ecOb9p2Iza0HRofWWCOdQFpt9mEa1PJqINEjA-zP8
HarF068cyIKug6ecxOUvPx3qG1OzOgtq92VdlPr80U0mA0qa9ZdcbPv4fP5ubB7Iuqia3ivHgk-IEZMIOL4yI4mYma-9K6ex6Z8zSMRwUqaxKcTGdee21Wwz
lUGRoJbOUkBCz4daIDgcfXuA2GoHcPZ493cIS53YIHa390wE94yIeX0oCfYK9sSc9d4ckf8Je6ppiaEF6fGOf4z2ed7efk0hHMlPDyW2b2Td9YOn59Yvz5Yq
fMZviDKsKK5w7WiIavos5hq012XbtYj81JMBPvL8dqJyrCwPA4NIuq1OlcqfnVk_xHwbOCOuIbsrlVHuUuVyxvFWmpfJK0o9PHCFIakzixLs3fHtIo8-4lvb
MlWF1QfIMcTyz61CLYZl6JEcBWiIO0mrmOCYKELS61yI3oHEIdcFc5bRKKhZqhJ0wVz36WjN4dSJ-Iv9X4kCVKP2L7ZU8M56uZ21fHaHwL7yTlOjOWOz4574
5oGKwdIj9fCHwFNpiBydE6Be49vQ6-m7OaI8P49oA7vTDfwP5bYGM4fPncOdfMnU0VX2wqG74vwHcDAO7WhBYMa1p4X66oBBsBpasOkKiZ-9e4SALAIT8w5G
U8qUGCzd72XojADgB9k4-mLvV-6LI4GPok4S2L5eSkfnBL0CIKfzV4w8wzWCSQ3i0-8Z4VMG-2b5LoY693IM2Tk4n4afEsF6HvBKHsBAIqevPm95pcEQcgVd
ihjBkGD4QiviIAggoaCa5ChyvNKU2bHR6In0xzFZcQ7uAML_uMs1Y18E9Dr5ugGK5ugYrY4supWjhXCzsmkl9Fiq-IQIjI3xAKLA5IZ_cd7kGTa_yN8aYf68
nbqafippP-8y51RcGeRaxigQjyQC4GaD4XSaIIOaZYfVHWy4u28NK_CAPNFX7HHPTNn5aXlq6Wd5TXKz1odeXJK89tes5LwEhAY1PYGGdKM-Kb-s1gi4UcqD
uiGltP54O0z9nl54PYIhw97o42zwMYn3SCCQX9DI_cpCI0b46KS99aezFOk4GlKASecbC1Phq9-QrOcUFrHuFn-64Iam6193mrqarpr-2RKprBS6PoI35U92
UNqI6S5M0FduqmeTT21ffpZ9aT-bJ4XOzD8QX2f2Z4EyjS7hT-ySA0uKeWGaYb2a0uaZSlLeRQ1QK-yypSlmfsQLqDeGPq9--TfCaIcmQYUAOA8CL8eKsKl3
vCXFAOQ1S-yCxHcFhK534inhTg2yBebWPD51r8vr4KLfHB4bogqvE3cJe-ikPUHsc1P37rg35ZYLxKKvFVwhp8YHY81CGKOw9bgjzjc81wIGeukKOfbo51QC
CFGH4_kxgV5qKEiKvDTCl04IA9P0b0PK6n7vCTCY_MSgIuyF4MvaI1vxoBsC8HyIgxDqUqttNeaeTp1PvOHssmSKXyX8vEX-bo80XapsiGjbf26AMbKTA2_e
tZjH63Z-I4V_CKXKmO2U29p8rVqkXR5sPF2iGMRX7kfth0q4TxU85jJD8WKzaAWdgO6ULHxpk09TJ0lteOY0Qv_d7YUbV9VfNMs9Q4YWg4G93ns_vrLuWJ8r
z3uKMGvgJw0y2SH_9FmPG1HB94hY5wR_Kd7THAxdZsVJyFAYdEZvXiBBDLTH7RyU1PCfYpSHqZSezkMXN9m_bZfMP_09A2iGlzDAHmEIOHyZqsU2FH4kaiYp
NGgCWdV-A277uHpKEYdbsIi0CdNDHDa-W4f9oGFI8tsRmjgbA9mXvq3IXpXJyxsKmdANIB2HDrlWIExsOSy4plHjkczk69BOXwn7ngeUb6SBxmWKEqOWIfg9
gAD76tXVc4JyJUGZ9WYr3-UWraafpzGPH3fSfKGKjH2PneDs_nNAB7SUIgvzY78HdQ2eoKafBX1VZQYfggMHHlGmguv4Bz1jlrIvr24VIFKaztfGdZ6zenWI
gYhHlcJtLW0RKegaBc13SjiQlBq2A36pwlYiCV685Ywf33ZTExrOQLn73sIUSU2qkEicak63u8Qv4u4Mech9t5uBu1VUrojVMeCg0Xd3cPgTw17_ZQ261BEg
FhDeCYIMKdoDHA-MxvSk0ytyjzo3shjG6b62FObGQY1g6YrmEDZ5veOayd3mMKmBG75hQiOQFGR5HO9CeGD7GZrsgnZ7Ji2Hj41_KcbP6qn8Kh8b_-NK32Tw
F2ITgDl5ID58H36H4pPE4jcHKcmTtN8JvzGFfr463uemVYD1eeHZ-nE75ZeKEhOcaMk_r4oBrFlSpsEUSTQ3sZf41BC4qnSwo6ya7AZqU3G2gXpihUgP82NG
7iKkI_H05GUIkP_t3sernrXc93EoOpzQy0j9Cr-pi8ekdOZJlMzH6b-XG5LZxLt0_1k0Rmtcr8U7nCf5_qI2Sdn0XewispgHv_pILZlBXwG-HGhqt1hCrFWn
aeXF9CdC2EKGrP6p0jYSKbJHyf0FhHaNXWzKI-uNIAXDIAej1P8wSjPc-rCAsX0PeU321ODgp-CHaaX4WQTNCaPs_BkzIUJwW0aY8zKPmAE3MXz9FZmy_Cub
8VX4C1BjbhysaFad7JxyzbAKyW19GIIYRXMdqw7oYjtxwzS6pCwCSsODFa9YlemPLIX48GtSDl3sAoqfPPbnN2Wo1TsAn4o8O0qzUF0JXNUhCdlEuCUj1Plm
YiJkkycGkE94_xig2vHrnbcXsBxf_8VCb0E9DWV9tYJo_Dh0_wP1KqrbYE3qZB8Q4aH3yeB2kwl7DslGASYfk1Nd4ucE8oHVi3RRqwL05jDYWH9ZwrT8KDFm
p-_UHA7ofGjcIk4QYGB-NVZxA3Qv1QNaSOda1Mkp_LsA3sNa_XmIZ4Xlf_35BtMksj1pVO2agYCkWTvHeLu_57I_ueI63OLtQqg1GV6GiEn98ZlzKYlF3f8D
QxDTFRvZMZX8DdJlMrCAL6L07IGRaiXESyC4-qc77fBtBxptpwndqoBtsqWaqqkrFwNufiM6ovcDcyZL6YoftqA25kd_KN5WjGQROrfiMm7iJobIdS3PimBO
xvT2bNDrrj6xTk_xUtnq1yckmhk_Ir5TD_GR3Bmzyi-isTdGxrcRxU_ndQl6FTtx_Yx5qVOLmFwrmQhjAu3zFVwgdPSp-rNE7ih-9BA_IrcLwEzM6bWazDSh
ymyIpo_zGRBs-3z8V7E33lqef24_I9n3KQ4VBOFFYkGdpwv8VfHvq9_KFm4
}

sprite $image167 [138x104/16z] {
pPTfZlCu34IfpPB8Aj__jhDqX5WEfpy4iH5DzVRteVcAZEHImjQo_1-Ic_PUewnEhDfxxzgt82iJjgxz4Ur5rgKCZi7Iagn9QjfFKQrnaI0kGvT5WemiqYKx
3gVB0a5yXYxV4CI1hD0bd9lxEqjU8CW2NRmWYtI9hhbhTF62BD8bky6iqINMJpZyCRf_jI_InGcoHXVVt3MwU44MwE85kJoY4cvRxMjqyOAiqSNV_aMwU44M
wE9N-_qZoei4yT6QthhzxmfoxG342xV_6xga2uBSgmjwkh3QxzG5G8k-kGjqWG7cE5Re0i00rva5kk0HEr1MwG8ubaMweFNLB4CNzFP3OG1igIu01ecjr2LE
98Gj795kuKbYn5gMGQ9eZKzT5e20WyHiQ-Gg5ZNo8058SCc839n9I1BSly-Y8Cya0C5z9_dD4IauOi_kW018VbCNDJw3sW50MJlnHFdIY0my0XtRldQI1mfX
W-KBWvaz6Vfw5fX-WyEtUFyIoo689o51ZkuCbjRCwNAx89v4RJBsyJSNkr-NCHWVsBWxjUwSkmEoL3FSFQ8n61zzz5MjTP8d5kfcjjszNLuuG88_2Pi1zjps
vEGhpFhc6dsp89P39qcAnFP06TsPMMZ0gKMcDmi2ZIA5-24HIHqmCyDBTseT9BiRqLtDJRBfH29I583PMLYcpK0SV6v45mS3cWIQbFqWaR3PWuKJozRCZcvV
qqNX1OaAoQya3rrW1mj0gsQ50yNfSes3JO9iaBmxaeSk9nO-kpDG9bqk2aALReCaANcGpBeSA32EN67nWXYelSSV4eBq91BghCjMR7HdFtNxKFUpvYQ9u1QQ
58HAEXAlInxT0OzkWxhfeSi7WY2a8hqBL3BjMBNYaf_RfLOpdRi346n9tJ5wNv3E4lSgBSSMSpyui8dub34YLBFy8WdOYvcxqMyAeZ6Ob1GQeaZdaHPaZjV5
j0w0ITtQMOoEvOt1M8ZMHGeQUj7Z7zAJGt2wq7se1A2ssTGYqtTlVuhSczHz2-3-vB0YVqnMm600YVtbGoKu-CpfykjWUgTA8rL227fK4LiG7w-BcOtk302m
PmKu-Do8Vk6mADAQw0wKK70CfaLv8w6EHa_TuVxepk1pB5uGWBIGDibLgYNbnA59tigXoxaxQahu1wF-KH1AQYAImBS5yRgOsIniRSZseF8tshmWZIfzXnJa
MFaCgXFaJLqE5BEANnwCE35ie2MHNiNsBftpOBeJv1rTJYmO1F1tyJXP88aGYPYwb4qwGYO72aZDulE-Bi2ZEnt_sUqp2eYGzYsYIgsp8FI2VA8BmPQwJTqP
B5QQuIT6aYrkEq9YZ35qMfe5eHFaGrsqA3fU7umQ-o01IHCHOqW8eUwrx-G5GNxVBhs_TWUW5NqXoGp99A68SMG8SZtZDGAp1lTWx7KCvq6IixIO44M2_dxx
Rz2594uVv42pfzOqAIP14dkfSBV_depNYEyEvkv0ybv44abt-szBhC-bU-fERfX8GjuHP2FUMEtNTPc5fSRHOWmIidUEU45kr-KGrifCChyUI7_xRzR5REwE
LamaiV7zstzzkzZCGjX4yi7jlwuB7p6RI2xS_ikwM6eOkRJQh-kYwTZsLrRxzUs2hH_R_eeWrtMn1fpwv0JvbYxJjX-2B4Xuw6B7T3JBeiG664RSQb-W2m0O
tErVeWjWIB8wGvVr96ExE99rwdAGB4-s3qd-1W
}

