sprite $image203 [225x164/16z] {
tTY7ajim38JXH7BZWhBU_stZkKtX5QJXXANnJ-5OKx-1H4hUSskjxOLhhBAlC15jhEZqnb2PnqhpM6KVAyrZfNcidA_EVdflh2gn_Klt9trn-VkkbSV7IlDO
0Lw5pURMGbKv6loivjqvTgliOvLvh3IFbUQnqZnMsSTGcSVcU76fJ6p7XyeyLfh7xa9UqIcYfVVylikOLDW-wBOiBTZozLUhSeZjAE2NNn4e8RQc0h84dXRO
4dWw8Bidl7RAW2nXV5fWI_0b01E9-42qhgiBlAodC32Jw8oCfDjj0DxuwxAiOM0UiJ47UEL2u4DsIWIssn4yFN0ixfiOo8Ay-O4D0TxqG1Oy6dpWvT69otbP
pY-_LbvC0xBGz7oWNoQG1Nm-yFHevN9wzMjD04Q8Q7y7t1urBhOi_R5SbzFsiWY03S7nlGVYqPNBmza0N9OJNfPi80lmOhke__HUuy0nn7aj3Xma0Q1JuE5J
0-F4vkS3OJO0OIO5ihXl1FO-0ArtCP25VGHw7xnwO0loEBdk0gsR4CX2F3vjvW9XMY2By9W3P7fWmy0h1sJq5GKoL0UQbGQYcndA0j6tpOp4Ya3h6u4arWAI
Ho25g0K4UGGo50B2g2Dm81O1aiVCnZuNU5s6ye3ecmiq-rJWACa2akS33SyDDB8S8CFp0grlBd0Cpma4UGum9DG3oVE0SQ8UQDl7cHlKmFZu2FI34XZdCOiA
zK2-b_d0654FjBu5W2HE30Hv0Q3Pp43oWa33h42Z8GHac15eVOi2VQ8U2F82G5Ue1_9eY09zeXv8NWZe4_L0z2q8z9i1IDv1G8CQQ2ub3cHG0grlXm8PL42G
TpZG006GHqC061pYklxz_w938t3e0o1v0M2CY6rxXmPkFqFxrNWP7rvkSExE031AD6jiH0yvbz5-jWtr46zitmF4bfHj0Lz8Y1HUP7oipqYCtvtOsSnJX8Md
5oTYneUlKpKt4Q6z9I3C8QA7V9zEdEneE828oOu6NwWd8iPB8AfuHi6HHEN3j_zzY0nHVtSAxbF1qJ0X4S4NbqGY14V3x4Gay0IxZPJ7xXb7XebuyVjKFpxz
VegUi7VgY8X-DUY9GC97aPWeUFW4H05F-oWcl9Vb4WNlPReX8e4d8Gg-6WJ4XAD1I4J2tQab9l2qme0lkNicyBvBoWBkif01xBkouu42L8YOC3qjCM5wMc72
-BJ4XF5fYGayBJ61fpqL4tpQ8IRmjCG4dbQOS3HeYGdZqn8JU5fY0azBJE1fJyK4drQOi7VcrHrW2Hxx6-3EgX2ByKZqWTXBv07tCdq8x7kbtWFtOi5OIHyZ
SE3L91RcaPZD-mO
}

