sprite $image214 [277x262/16z] {
xDWrWcKn30NHCLkIlV_b3XZw-_LmCrI5odJ2--NTbxAx7YZAzo8EPrL6rK5nbpELxrdpM1mePggjzoiAADRwkq411HHGG04555100QK_1WKKK41nMBmO2YYW
W9AA0-LQg2AIG3ahClEWt5BLiMr7K6xfshQlAA1Oww200WeeVy-_C0eee802YYsK00eee1ovl54IAAiWkb6qUb16HLK7IbDj6PHHCLDHQwhM-nqAA8kb7oYW
x8yVZHAB_r0e_P4eUzlExiEXf4UWP9b5K6w9pMqxWtAYp6txYWAAjVxiAA200WeeeAHFWm8AAFLPKK011PIqKOe3PUP5DefA16MKR8pRRMpR5PI5CbIQgVLU
GDaeUzi-KK2P7tyo550SAFSBLR83vSmN-L42vIJP1L16BijHyQ3S8_bMphaWjv73K13y4o0cklzfzoDFL1vxjQ-AZaO3i4-GwYA13YtfNsfONKhX_o0VfMJN
Kh2IdSvOIlKf9VDpP4qfgVF_8ZwbO2L82vOoDajIS9XWH1rAmKgmbXzA4I3bYc626Vf7f6HBIZ0ovgGStxPxlAwImXFqE2abzazlsyLMgs5gc9AIXl3ZRPkj
jHgcp4aPOt_RreslgAJpZ-XfJieG-NZRPeEjXcbXHieZUjca4ann80MqsWpPWHIWP88UpKl1hJQ_dh4Koa2A7IMOybrADIEby8leoQgKmY-aHOjICh-OsYQa
E0WJW4n8SQ04838XnK6O06H2YWCb2D49ASR312DZGee39G3Hwqe9XT-5w4Mb57udxOfICh-RT3KfkVFxQH58yTXgc1g058zAC1b8yTXgc9w058zAC2q0AHvR
3LE159TAC1b8yTXgc1w158zAC3MSB2Mp1GgGuZ9CC0b8SQa40wIu31EC02akbM04IF4O9XWH8CMZ4epeIwI4mgOP2gGuR3MCZAqlrseOwGigmRImOAjXoeML
zFIsyvUkschvVPTInZMLrF2-TJOslMIhzK2XSewTMqpzz8RJY-PhlRk9aOXAF_lJ2NhbLYiVOxp4UchgRthXVCttcTKQSuxj92L8oljRhTP_tUVKkLC-uxy-
EthjlvJNK9bRY94edt1CTlJg-PfIuqenvtR2CPcK4ljx_l3RQoIAfR_scEoeWQV6NahBH1Hp2larkNP4ZRohHQBwCMJA2u_9ZXfvQkn4Zx_Jl23NZgYLfyOU
Ot_vDDbHEq-DDUHNAzbHI-zg9RzW3mCfeDKSW8x9Zdf-QiJ714l1IlmV4ombDdRAsFwF0PIiT4omb53TAXaRO00bonmJBALuLe8PM8d_FOobP5xic60fkIzs
JB2Kr1Su9fW1miHXhc46KEBmc60621E7kOOPG8dJOuAbXBAQ4Ym5A76tXp4Zysh713DOPB4zZ66k8YiT4umMufHyQf7POnA8ECMOEj2oq379z0yznN_8B0iS
4qmFj4kvKqMSxs7CI4G7AJ4raRLlJYFwAWMC5lV7H18Tf3meBAiUaqhqH4e4wzbjhaca9rB0Q76TQ_HCoaxk8glb6f02Hek_Op8o4P02HelRN3l23obWj7ZE
DInb9xF8Ehc6fUmK4T-v5Wb90QF5PQvDI07bR_nrBTASb7sqkCqrB0MC5hUvXgM0zUmirx0KD5gyAD4UQ4eAA7zdkOQbfF94InNnccjOok0CHek_NCDIncWf
xe171JUvXgNea0hMixDSmr9kjviEpg3y3USQXkCtANSh7LIBqMUJUIbyk-rImAE2brp3KdxT2j-qW_9tjOUn5BtzmxPB2GH6YujSmrB6Tf120PI_kME2uVgz
KxPVlyPlAIaHfGGU5Mpb6gOEpaSfTnvIChTOj8BHOYlNCB6Fmvyvwb5AP6RPDidlNCylU3P193w4VUgVfH2F-x-fWz5YBTSmHQGSfiLdAPlglrA80dXKi9Lh
cD2EewNA9obtHej4u571HgxDZvPKlafXhY60yhUsXp5P97_IyaMA3kQoIm6F2fPo3HCefczIvA5VIW3bRtCFOs9w9cKJsgM0yhUNQvYK3bAY02bWj9ZOmvZm
MGiHvG6aW4U5o-RQ_1qAH5GLI06ZvTJFa9-ZXOX21rB0QBbihitVeK14IO0KKFv6zZ3MShn3XHzIy6YnbclpemL80QFbXC-Gdwy5I07hsK2kpOqM80MC5bEv
XaVB98N5SAxXEpH95JdhGqddav0M0eyA1dCD4u0M8WhWKS5Qhlty3dsO0wF5PgxDQw5yzmBAtsIkpOyMQje24HWjjlRm_6Z9d3-a_DwD0JmgsCcr-JjKjv5s
ARzZ6vJ_2xxoTpKjQMnvb_9O1m6C5YkvDZzQSakxbCVu2w3y3UNQVFdlKdO61VIeSFvVkSw_GqSfIW4yAlpuC-H6j51H8EMmdctbsloRVvGlKd9DpxIOohNv
qK94vOiKsIG-GTJ17iPtA11bFKhXRQj0Yf5Scr_FWUfn-vHjOo1b_ZFaPaRBVTOEUQpafWr8cSerOtSeowP2wR5z4fWf4xbcKKiHy8SGA0NdciNHyiUbW5op
CLfcfU1Sito7TYUjWPbYDjVcop_fna2AsLoRVrGOsvQ15AkvDb_-3HIjnpsCxr0JS59mhhdI0X1rk8VnUiPISAxvqmAaW3tib9XcfOn4Vaa9Iy5xsFzemL8a
adTY0bB07bvAY-X4hdaVBQBuc2mtMaH1hgruXqH1hgseHHJasXh4bfvB6OdMf4WzIF6QQ_E_gI3gDjVcl_WikjmUnh-f8BfShk7VLDYbQAPbmB-f80foRSNH
CXJiuVN8CXJaseeKJdHf_WO
}

sprite $image214 [139x131/16z] {
xPU7hXkx3aKbKcNOdF__svSvJl2Cy0uX63potB9GazCMAEuDkdmpC4Sjjw0oCvLR0C8gTr4H-uUg_AVodyf_AdWN5JZuW7ke32MTTr6HntrKx2Cgk64gDrQv
_wuq4TDw1vN6B2PKRw3IbLbKuHOg8ceQgzGnOO-AcSOFT30Bt4E5HGm_eJAT2edUHONlflAVohY52hAeCTv1XOH5bEwYedOJ5L7RgL87ZNe7bTg9YQcLCZwi
SehyXFc0pwgqW-d9QIGRLRm8qoly8HLy4NbnML21P97v5F4oeGgS_zDA8d2AN33gjGeGYwhW1f4Jfdwj8imYrhD41Z65y86NAkV_9AbKB-9Xdd2jejQpgdK5
fb5_gnn-AlaYiKpBLV7LkWuVLoejgLhNOMBELy5098Jr4QYaLEiwcgW2WSWI6AhaYyGjurHogtKTfbxB2JgLl6fT3tPpAlcDjlvAWKg-I2mpAhoZqeWf6wOP
g8JLcWyp1ofnjUR3aKeiaWzRI-xuzuLvf5OhynWK4r-SCJ1MHOWdbCxqRinOywgLUpj6VxUDHIsnqPWPovXZlfSXpQtMEUOS2EnUDKRi9vfRhKnZGEsjk_J7
8pdHx6fbchF0wFsWDLZiYUOt6dFhpCVarP4ubSHgvUaVA1RnAd6rhiFh2NOghbftm6glgAlMROYPKt7LkdKaNgNshI9Y3dKYMqVYLJQBYFqLcdsrhYVOg-1U
4LQxGFUAa5nvgCdyGAbvrEo03ljMHQv5f9NI0Q0JVteajPmg283VNxGSZGJBIOSly9jNHeAHp59ULS2jpAwtOIY_6F34hSoUaUWu9PmAu63UEnA2ydywlD8c
yxvIqrxAbSfpPJOcE5G1I0msnwNsnAaWdEG6c-C4NwaCQW11i7D7mbWyuxVAmoOk13ivmLu5OVumwm20mSga9jZJ0NzDHHy346gmCga9zanuClJ7uzIgDLYP
p0Hx-j7Xf8l80AnZ4g5RcSIp9A2EsPuZq5EbgJvwSIsJbE1QOd0-izFxgM9gtAfhcRm4nxG622TF5PK64ApCUsV9A8jKm2yLK3EJ2YTkPHBEaYMUWobrwkCF
bSMBK_ID10So20L8NrJSoYIKskehOIteLDpAP2GufY82GYdWS2kJK6fBhmIlOB0o2nyitgV-QNB-Jx0o2sT9caojfUBboh0kbzhRA_C5TW2KVhwRMvc5ioI5
t_KhhQ8-64jr7rBo4no_KaD0_Sg1Qvc5ioHP1a1DpG3mpvPPJt3MoXGqC_twywysj5ngUIjJ2vlPgMBpfMl8TE4ioNqbXAOwAW3qxgOI9pXV1h2L0W0Ld4gO
u7mgFZMm1If1WbC1F6s6jK0bEy7n-S31hiGZoPTvXO84RtWbf-9ARP-CL_5doVvNeeIp9ETy00fARVChaIkr_S1400Jo2TvFEmO0K51g6-b7hsH1WZS2St9G
Qdj1oXx9_m
}

