sprite $image69 [180x226/16z] {
rDO7igC038DXEhPCkVzjbupJjQytwvySu1kF0kpVdFcfNIdFXD3mMo9Y-5qGK6_E2GoPKnDd0dyz3bf7pW218tCc9ix4o1a4Xin1J9mDOk9CZ9nP0R6A6lwr
2Xovl7hpJ4ZjtvO939aJ4sTGc0Kd9ixKnDbMuFbMujPELVypmdyZ4nDdcy0iA8Y9C_ksMUZSslnlKZWoznMnb1hmFsxuADahf2RE18PC0MBYx0DVd3fgUCKW
yDVZNfm5l6nm21oPqnFph5sZ-TuSm6qwXSDmPuw0QtHdrb7ZtXoGKaScTUh8f6OTeQUEJ6dMYCSW85xYELGNhskYLGQ2PJtQzn1HfpZDUzCvgQlEucBkPe3L
LSLfRgSvfW0DfE8iRjim6wCTMLrIdEQZmzoqCmsar2pOF7PDqrj1zKbCvici6z6spT5GRI0v2xvpExdFpRbIiqPSdBoDpZ1Uq2qFfCQGUSzkVPFrCqXTO1Pi
zkDdNPenJpoGCk8q3zOVvd_CcmcMsxoEHZ4JK-r_ktqacHOLdzARViND3UIIlle80fLDQyDDb0Z6Br9FaU-OUNXgmAvrR5gJ4dot29aYtvppI8l3PV6fDVgt
j3wrkFEPIMEcXiROjSP8lSczxn6Vt-0uZXbEhILL-LFhR-JR9_CGding103yqfhafWZvXiWdywR3E9W9JFSpFjAQznt41_Ntj3ZTG4l7FPf1REYgzKqHyYNY
q-SEsPZ5Xk0k28vTwttXZTQFYdpFdEA-eOe9W28UMWky5lcpWcH-4Dypeu0ceEu7Iq8mnbYr1hZH-Zajxk_1TCr3X-CQT5TKFN9lq4sL-kX5VPyRLfOl1Gwj
XmBPu7-jTJueyhqRmondHlYEAip3HEbfhU-rkFy6tynJQrGp1EDdjLw9_tlcKsjM0XELnxI-5_cUMTt50fR5Vbo3R0nil4bnqVhcg1yLUVLP8mTSbkm7Yo90
QlQ4rbEB_zeDz3AuhfdMx8QYy8VMUgFrmyIdp-KkLsXwQMs688nNhPLkSkyvBQxCYNAyOJ-r5W7nyTRwO4QZ_xvAdSJ_FJDfYkLHo-7anP15Quk1l6fDfAGt
kVUK5kVTFT9ofjoBcghzVBIW3G0zYX2TjRMmV51dFf9ldswmvynddbfZTWAUMfFWkAOr2ibDMZyXykepuNcdJAqfGm9uqTgCGOJFVI03A7zg_O0Mz_VWlBnt
M8XSj5O1rZ-A426xwG0_G7mm3zE5-Jn6e07HXQVM9Ag8jcejfAJogVL3Mancb70VdoctBQqYE_XVZoy4DLjx2hfH_wBr4yJJ3RrcyzHXjvWIJN59ws5CDZzF
t9mXOVdK-W4jhZvtw8fy7YDWuUYaVMU7riP0WdYqoWHsQXRzrFeHufCv-RVB6mYiMs3HMf5ycCBv2x4moo-2PFS_pqo6bd2zl55nqTfBWX5FhTMTyQAri2BO
9_LsX_ppp3Z2BIKKxIoIgPCNhGcTkNIfhGSVYGt0hzzZT_j3w_vvWXbiv4Zjabs7oTn-qNemTxzq67Yat30-pZXSVdjy_Jp3ZAQMKXtbfmxMBalA7TUv4IrQ
cncW2luHF9BFC--4AP7HRKnJ1s5nY4K7O1SRO8lMXg2gYzPhJ-5vPksqxAZ4zp-l0Ta1C-LsGmPsdlj04MMGfGCy8-TXPlPWS-tsZAWEbLDhxq9SZf4OkmDE
hP45sEobTV0ywig7praY3KPxruZAAddhW16SGBXehHLiWFi-z2X2Xg7AfGECfVwm6-WrYFRFCBmwVU3K6YbXv4LhPWU_Q6q8HhYqoh0yQhoOknxnUVYcWrHK
krTMZxVMEC2xQTMQOnPyyYf268QRqNjUXpKiTMVkciZ_A3E2st6C59sL8piZwAq3LxFY9Hr6DzBPKq3PKENT0SOISzwO-z3Z7sP6It5xNNhaknkHsS7uri4e
MCQgjISLCHrQ0m2P0fgzjFPa03oCxWUOQOnqEo-zqLareYjAO6eDoTh5YzO0YQDiry5thONSs7ZtASUZp1k5srdBeLhkHnrToZHJ3gJQODNQSBmAllTWmmZq
bNKXpp5FdzSd2jVcngZA7gSELZOKQD6QiiLmxG0poC6i4luaC-pCel0-HkReyeZebbC7H5Cgm_T004Z9cHtFmORemIo0zXmpk-pCse7mrXfpSyEoXS9E7NGM
V3ArJk4kFGSRCfcVzZbqOovrcbeBqUYA3EOgGx9Gt6cYdMYvz12vUip11W7y3UQZKY00JUl2HMklx6AgpWoSEg2R1DYf0u3si77fZM2PsxFCOBd_Or9bjMWD
KfiR6TN1zDP17Qfiwd30scMmWUKZvUbly4W76jhDV6ejkniZEgluhOD0Tk6gjLo31qizzK5c6UWsqu6YjHoMSI7lRaHrgf2zTE0kSdXfZH-z4Kv1nYTp8zpj
RCI8z96wynYryYYTikrCESR4uNHsW9UbaSz-WwYlktkMn6YbdNXgJPoT6PvTFd3gi35tqTa1NXPLwfFCWCe-TNnfpTqQVEw3AgjZP6KxJXqGDldf_8NEXJNS
vVbx477fBt9iF7XgZTwPwT4LoJZJsfAIYSyE0fpvBF4Simhkp7f9EQ1iBODJQz_TYCfEnbE78EqDbqwj7xzJ8YBKZtkGvQArT8iiVyAcLLankgFiFH0mqcw3
K-l7cUEr582Yh7tL6gErPX5oLAdHTLIfnZXrm6WJdeEDoIpq5FFiRHyffrqoBbfpjGu2cFC8giqDguuEd5gZijcb0upbdlmGyz8bjZtbR4qvt2otAdxFXvZ4
kpt3kstHOTYb0umrHjfZp2VrheDqQvuf1u1KRV4MVI1u7LMgOJZAhEukWutDZS4FCf_KxvGZMjFQjLhfr9gqEYeKgmVEMcvPykmRjl8oilb8EVR1nrUMf-W2
cj6jc9sHHEDpi56Epp7NfBveBTsY5wsrskJK6YdRq2EpasdJuGhT6VeSyuI-QksrFhKK0KPPvejiqvfTyUWfPCjCkPEPsUDHdqz1Jgsv-tng-QOrPzlWiwS0
kniHsQL2K-l93A1FCdzI7ocdNRHEmIL7baxHWu7xsbFG2pCznjozKa_eNGUgrjJBt_faZx1p7yIR6n7HxOFsVKncV8xvup-OlWMPAIUNj1wMRNJfAMJNoCvE
UjUas1RZKUQ3-bCGFWO_vRCctKH7xn51fzPeNL7xKR_dTTW-Kfzb_kd-LMkfLaLO7r_PfdXgFJAwHbHq2UvQOul7qyo_239Jhf9WQM1eMPJ0kG-kYehndjTf
4I8zpdodDLURyzB088gs8QVMCdnp8wDxC4aa0ppF_AlMJW2SLYMhrXGMRKijXz7HPTLHITHb-3ppZTPs526MjcgDtiENQflKkYF3knDRHzZZpFTQRr9ejl6Y
DPf53rgq7hr_Z1ip0_l3p9-2V6eDtYE35gt1QdZogVMSrs7_9P_ljPufDvJMnvTwkz2fjQHtnrzaljVwIBcH9R2qcoLzb2rF5DpT4EE_oNolDMSFNr8Ea4U7
BRqHtDnmJ_cxp9EwVpwrfh1inQdrNctxQ8Tr7stFtzs_2DBzgVN6s1QNdW9QXws3ZMPH_llCFplpBuylZJQ69QtLhODU-uX80g0lCbT-QWrM5clA0KYbpSzJ
o-chp2lr-lYA7dhfAPXrCX_riuTzqurVqpf7bCAQrfbM3W3qW-JnFUR9_QaraFSOkchDrdKm0yWNcPUByRC86Tu3rvGREPdfgymdzOVMEDg7hrhZmOnVP_xf
_bLh6-syfFNEREbVPfv7_LiH4kEFmSRFiDJlC_-cjG2GZ0wHPSxrmnxoVUPRhId2Qi3KsWe1kBxFVAyrMQUEgNNAzvdFzMjQeuNDNYfr3ln_mdolDMYb9k-v
mHR-67FrVyHyhpMFyRu7wK7cwlwFcE-rvgp7xy5zzGtpV_JuCW3Kfvd_hpcxq6qO2e8eMWRlFE__VsqXCALrf4rzdLnnyIYQmBDpYbtgcQqUAcQzs_Fp0sRE
Z7tgc8qUAcviV9e_htjmvfnZbzGq3-tCrHNWk_7WConYjbhdcCjh2lUwlN-u9yt5G3hcIZs1xztfh6wRLT-luyrMIstpmgirj-T2tJKll5fFY5cP5JhKC9U7
BywShb0tpEKLOAi5YQjPTysZcFKqHMW84piTr5rpEUif525YoFL0ckR5MGjza5tVN0-44jUrpFNXoqzcMkmwvafjSWHFTjgPGmtpxrbhA4IBwuLqpKDMq-Bb
vsB7x6zwpmB8VRND9xRZNKc0kA5kc8TiXiNBQgasZyLiviNBwitCoXMQ2ZLdpfKAgsbphfUlAM1cYm4rQKu730GnfoFKX7bEAizwPNEIwQ2ELSq95uTEczKm
vmQjQyvjcjSpApVhQ5RVlBtOQMSE_SUSG9t3LzyyPruA7JhFd1VgnUgkEIzOMDqn9rx_y7NQ7EckIcqpyI0ZXo-R0J4oQvk1rpTo8BLPwQvFNPlp-lAiRGR4
tAnj1iJSG6m6n9JQPe2CeMq6n9nQW9XM2o3Jhti2nEy
}

