sprite $image424 [260x173/16z] {
xDY5SKGn40HHizNpgxJvHsjcze5ezeNGDTg3Q8c_a6996pk8PLmWlk4n2iJ-H4nB78vAJ8X3AmjCmEjHS4HP0A3Q5nY_GgK9JNCA7S_21Grfv14uJu7cjam0
MoO0Ci5GIn2zN6G2Y35SWtq4PGF0Ee8GlPNeeZ2IQAmYlc4n1347gSPnC1cp1NpF842R_-EBM83J3JZy3qon4jaN0DZfcw1t1G3l2c9Tsk4PM4v1u1u10zLu
12zA9W1b0b0c-2v2nKfy0N2FKCW8O1z165AyLONz4F2aJ03nGcG4VDMS0Se6a0c0iQv1DYZtEbs4GXUttDndSkGu38RX3ndOUF_RBafYjQXEasIlEO-pqe_N
R5AEPXvP4mQWbIh7rdpZqe5GbpD-HQk6HBE71aQ0r61uuxe87p8bAbwHSuEuRs24vf_UeBvIWq3Zpstmnx_vbHfeAK0sDo1-S763-hS-g875cJvlu3SCW4q1
iPWQP3sGLHfudTdJ1ebdxA61sFusDHPg87OcFziWeoe0KDJs3Yalqk3HJpPmGfIZvTX4LpUe_wD1HZYQkUiD0M3VvDIWSIa04gaI02BhDvWFeFDCfuzJ204m
niPh-sYP1c9Fn4C3vq7s1iPYEJTm7CZHSfa6_bq3XGm3wTP0q69gK3BsqnWKNCiqe3TVCRY8eB7ekO4K0w2Q6oGs5jZP8WrUatbTy37H2yQ8a4BJkS5uWoZ1
9d_B1buq7kiyDfyQ906WSGgu5cf0zxxH8312K9uRb8oDYcOBDR2yf-yR9CQamFLa742h7CqNQk1fCw-ozmtgTZTGp-O3oXeHrsaGZXczQI06W8gmotE37Dir
LveJ6Is_jy509TXmdHie1XblbcX0QFKz3IAc1egDdHiacc6IApJ0qS2YyQi619aQZ6XvRi3Zrcd3140NQ11eN8uMrUHL0u0oTkvZazIvGQEeC4LBMUHhPqNJ
jmr22RizY2jJ5A5PMTmriAengie1iWKQ49gNex4qkckG10mSRh9_E1f806H70uKSOwkIbxX7SZJA5tCYtoe198H3o37zyxmkv6svhStr3Vxza9LHwh61t1eO
6ccM7FkPSP2fmIu4MgiqCA3vQ43S22rqMlq9qBmT3BO8mKJd1aDKIrLbVF46GUEpNY4jguMg4Z0rC8xR4YAUupImO-UF3GR645Ssk3P2C9hNuN6EFoHRZhsd
1r2-RE0Oyais61pWUf3OI3rd1CWnLTJB1dcql4nUtg22uyMAoLQlfEXHmseJsfvSXrYZBlHf__OmFAA-HqPyOtVMjVvjV_pNtdraDnP3CH3jTgIWKFlVhUVA
MRGB62lUWqzozBXm1s1J0qW9G6xG8j0YG14emZy0zv8Gq2EmbHe09H0YX2BG6GY0NM5mE2MmT85EYaf7XgMputA72vU4aqK59N0PfDDbkJBB4e10G6BmmLPi
2q8s0EeY06w3WDiW05w4P05e3R9L01t2qdqh3riH5e4Q37f75I1lGa2F07e4Ql3Hk_juNaO99gr2U7OgC5qLiW6vGdXT78lXwGWE1VU5oF89bqrDRP2xBoJm
2mdkgZ2OADTiNxaD8c6gBA-kxRWVmFmrEF7-tE4mCBb1xdJcOjhaZZ_z8oD9jWWNMGwcpWJTdRm667AY17e3z0HWDrYM04q-JWXeQn1C6ISwu3mU9UWDa4M-
4014Bm1R182w1W7aBHWeO-x0zk48v0H1dFor__y3
}

