sprite $image340 [232x334/16z] {
vCyt0G0n002XcQ_-tKP6ok60VrtWFnv0Oud64Y9DD9RGMAAnX4WJZIKqbeWqqLX2Oud64Y9DD9RGM2BIH6C9ZIKqbeWqqLX2Oud64Y9DD9RGM2BIH6C9ZIKq
beWqqLX2OmcH9eqbD9RGM2BIH6C9ZIKQIrUZESYnh-E8mHW6mk_4Zt7_rJfTNkSWqeAtWsy4Nf3yBvJBpbVMikruflnS_cGFvK_sKBxoKFPXNie-p4knaqM9
p9BDKYVBKYVBKfKizRk4fHucIvqiIs5IoL8dorALBFKmMUft2KkTB4kTB4jLijJ3PAc7oL8dor8dor8dor8dorALBFKmMUfXijJ9idszVFv-gPDbgPDbgKgM
-bt2uW_JTAf29qkdL3bATfcidggKmsH79Q0HXqddPIO7QSHasK49QS1asG55QS1aaNIG0be1auMpGJgWP09gMYfla_Isj08E4yw6ySvCbivvQSbkS4wVgPRR
d2Ag0Oh9DZWRnjkgf9ErZrTsbtFmJBNSvHmSRost90r8eMnpJerNoxFEjwMxUfXq3emNoWRdZ5JsXBFvJBNSxloEjFOnMJeRnWlbWBDPAdlGsNMcMfxfhhud
_HQqbgUgmyDf6Qyyb_G5wO_6g-LH9wGRdEdWPFd-TfFnKZdlrBPdAe-dGrkELylpIRyahJyvMJgtEjC7Tkr4rraT1WAmGzA0Oy_xF-vTZuxLOeE4qZz0EzgH
aFZQ35dQ9i3fdFrhAehJEVlNj2bE4_VvfKDDJNaofwhyfClW5U2aJk17sc4fA8eJEw6TQgfZB7F9_wGikkziNUQO0KYT9_hDlEqK-qOEpp6Y8vnQwIbbmwcD
cGz93TeK8vop2GEe-qffSapQ51ZWR1Ejmw6piULGJGKOuQpa9GLEanuTl8eHJitaXsDdB3sjir6KuZaj7DJqdCw5uWJE8pMDdUEP987pmE2DdUEPn84pa4eW
7Uiqvd5dF7ZvJCxsf2hCF2VwpKCHEVUbpEqqJY6oL0K0QA7_aniGE0_KTAXpCcNHvwk93_m_8PXZHZiVnbnUEbk1JUU1EMQOautP08jIKKJE0uDti5EJpmGQ
43WFIeSwRTHohz-puvgESxRuv63RsQEc-7FER8lrdivuy8vnsaj8EpjZwPznyW9OaetQtivun_O7d9AfUklQXFxE_QMWCQN_MLxrLaBB6vpxWnTs0Dn_LrAz
Tk9DpkqT6m1XvhvEdkZLMUWdZ-qxwwRp-1m3_HUisj4flwRgx5FQzftPSVOOl8sP1J1dZsAkdREzXRRlB8wpo-1bKNHqBeayvxG_R3dPBOxpaBJPDGNwEIKJ
UKxPNTcsdpkN3aw3jZUjRolvpdddRQl5hQySJdklC_jEkpxjVJxeu3JfkvmKEFtpTcVMoHsS9dsNamCdh-N1iL7jw9JsBcSDd7LlvndChj8lvjJUzJHd2Lwt
mQBmz4uAdDEEys7rlOApHKxQSIORjbTmpi6lcRBZP5iKNi9PNftP7ERSk6--XfEEEUthraiuM-ISjvt5wdmwfrRUgwSvgrsPDyy1J-TSahE2AnlEU5kcmLfe
iDFsK1BD3dd3cUDF9-cPdBQ7cgFNINMSuTXSWkgETjf3Jz4JyvPpYPW5Pt9oiaTk_W3ClF6-fHGj_7MmCpuMUVZrhEpCdvRP__SRupHEVT1JabzFtdQQg0QV
sM3dilbV7yDWvGGzfIe0gOai4yxZp2jdyVPMnN4cUaxEprUIdjf9tj77x3WBRQVXD4vxM7-IK7lcjNC-m1pchBGnS0q7nocxpF5EbjX9wjJJSIB7oabm0gSK
uWtdujJJStB8B8hnJgr4cyvfjSTkdZF-GcTWl9CJxJX9LlNqdUAFsORnpfQ90cTy4bq29pZuCWSwRVUrxqmlut9ndC5ogYh6EqsrxQJsN4znd3O-BCcKrt0-
01Wj8NO2N7vg-M00vtSM8ikgdexJ8imDbZCvs-fApQ-RbcBrZ9oMKpgBOErSo5AUwdbHPsB0SUhBsgzPFI_fd07NYKAMnVOZvPBEXo9oCbaAh9uNT6O1GYSI
MSJgUJcdfOddh6IPhPwNTMeXzfn2bccnDSFLd6RpdSXaoJQLNjB9YKBdGkle9PsIYMAd1flkApdjy3rseWHB-eivcNQS71xFyozSR-14Skjfj-O6tC5PWtg2
RMLy1wUiwsctLk0kJXI_dc0gYXivb-179M7WJauyCJCijt4w0xVUrzcSUjxHYKGMtDWv6pFVsIdch7TssfiewwsT2zdnvvsTiD_txkqiH4LnVsVB3RY7imRE
T-Vh_3g_pg_pwvm_mZanFi4v0n_WV2W-m9a5kBypCV01JW4-mecpER_Eh_FhB79pfotoxkzSC39_TtCVkd73G126qLB4tONU_sbJbKcv_B0mRWFITNLe7sI2
zxkTR-JysE-gF5_IEUJKndmlvl-TFVsYpZhUMObEW9hETrQoi-iurXPECK_-HxShokahsLaBf9bELe8JeVbELihfIFET9pjPckza9JkxGPhiP2KxfvkX-Sxp
ldEj0ccgavNiBD50ckPa9JiVQSVF5Una9JiVQN9dEvd9Jj50ckXa8pjP6kLa9JjPYb1snZ6vi_cM1Zcbz9nJPKZ16Q2yqTaW3N1AwJeBQ005Pm2JdK03DpjJ
bEna6al1cQAKqvUICq3fT3O_5GHd69CxMxGRsnISAKfsJXjVlE1CKB9ptQFzFObP7S1qE_jfzwMKCq29JgOTzPJqKiePf9IJeVV7hbzNEq09Jb-gwVeePm3J
xsnuK6krd2bAlxDvx1avCvH-P_DOFNBcCDavrZQzU7A6ADdPwmRjSHeTe1sZz3kR7xoKSYOe_SxcSRgkgnt0VFdELjReQiSe_Sxc6DMrwWpbotUsfAj7pW3b
dSvc6e-bSoM0-TAThQbwvCnI-ftzE5L3PmSeGplxV7qdqupE3b0cThQKaL9D1tHsW5BIaCu-NtS5T3OeCxTfwVnqbVbIlxF5J9LoPoSg6UftTgIIfNPdPofP
wdPsC5FBYL4uFpEL3BtVsJKZfwNCtwRmVMg7cNt6B3W_3MNq6JFGsQnCb1gTRIdpfJEz2ftCp9ToP_lA_6sgYzMcCl-MmlUfBMM-LD-djfdvqWE-JsqemxTf
px2JbVbIxcnWxY3bpfPo4-dqKcSRobmeTxQXp9VopxF5t4OApnCiPVuPizJPeDpZbjQCd6Bk9-sH4vHxI4VEbd8JAF-TphdF0kTKjPWRIkKyDroxExMsTsg1
Sr-fc9j3fTnSAkNcqcZcLm
}

