sprite $image125 [241x175/16z] {
vTlHbgAy4eRXIa92KbKszt-tknlrMwsXtCR0pz2yPwDwyAmA06bdsYN-Ba-dYM-TXulEuqMduQBpSD5vlEWqN9HFmqL_Z9iPdOBCx_MNk2SY2_EfnDpQURZe
F5nq6Yyw3nUTXelAURZeD5vq7Yuw3HVbepyLjVTrcl6Yyt3HURZe7-OclqgfGRohboEjql0F3vbv2_0_UuaItWRyhrwY66q9HljpRN3AdpG0RBGtrmPd_QG4
iDc-NXiyyYT5WErsvcuFhjk3kokOomxSVS1etC6x3nZjmDq7dCf_IIxS3Iu_VGuUo1U-jyDqcy1bZC4v-ixv8PKcCBm4yUPaxWENWHxpgGKCBv7RLWnkAzZc
WfmjiEc56Et9jS7PqMAf1PpfdikyAVcBEy4ZMSK6C8-6-6kdyTPWsul61h0cGynxS6rmfbSL4rodqHBp3bmBN1mH2cdCOmf4Q6W0imwck6paRGSFX99SzAUB
H4Av_hhFLiLNOhG9jnsSwLuG5RuccfT67AcfpAkICwy27k3zuIA5s3M3qSWhaXbrWGjS8iRXc6rmkpZtSVl1UAK8FqLpRkW03rpNnUq7UxeMAgy4DwGYUf6F
mL5ugOsvERq0bthT8hrSL4KOjOAZij6cNg9eWqUwnNKYvW9nPfMtLypjNg9aWV62RzlnK2jnbRUBN9gzZY1U0eSxeGaSn8XzvUqYysTUY6kmn_jDO5wk65wZ
l38NjyaGrM2t9hW4msks5XSbGkDByCWeXwU6Ty63wMqd2t-KZW_Y6amrUAIdt9lWtE95PTqx3SqFOXESci2U3J6yBNsjmKLQ28qrsAq9rWnlMutSabwL8w4n
MMVfs0U66Dx6cgQRwUtiwt0d669u6olmhWf6OqNe0YDbU5lx0dTBy5ZlrULuQsW08-7FWtT3SAclIwAtk17SdyZcO7RspNJ-Zy6YAh8osBtOyLW7F793rUEt
VBScs370rPU7LS29miVS6VmMkRmi4hnIWyNZfHuml4IXS7EY5u3V8EkhChnUfDIwqTf6pgu132_4pLo08UvyNd8Yl00MH_TIzGVZDd2YQxuqhsQ0UydnmRi4
vap8tr_Eu3Q0Cz47OhbSa3pKxrq6omCk3CCGt6TtMh5TB7gfmQXZnyEBi076USjgU1UiGvCON2GTObWmNnlyMXpL0DTfQ1A3MuFRoR30Qu5VYrs6rm0RObSQ
nWjmDraqm5k1aMWql4cL5y35YCMROfkBP1Nn06y5Hg8SgCebKU47S4ikDwncWBl9eY9iWf4gHqU_6xA22t2t65mRt4_crs2GbSSO_7SXZaKlu5RWFh70Qu2x
oGQuIbGljnJQ7Z0D5hSTB6k3aGYZJd0MOpKtWT4sODGFpcgCrqf5NhSRE9WvqmkkdI2ppy4bfvZ6lFHmNRqqzmliBrRymWjk3rW-13j7rMzMoXY3lxuOOhwp
I_HqUp5X7vEDiZEyu3Q3wzh0g7eeJ8uU6dx8ET12hjahy7Q0KGSOvD5JrO0NtmCNmmjkBnWrWsi26JM0YpUyuFQ3KGSOzOApM_JAvUsafVt1BAxsYbxM1gCs
i1zBAJa5GZW_ZuCZL7_K1ek35zoMfB46S9IBpbraz0ION2xpYve7u9BWemF0flZ12-xQOFGsECkl8MGtA_85Jv82NLGLV3G1R8lXnNZN0tCk1hdjrb8b4Wto
VEMKG9v_k2W2R2Mg5hSVFCmBhaLiR_6a0XaI7l5Y1ROIQpNtWoFDkL6UQW0ZLQuJ5Mu5Wxi-cEvvjiaskA5MiC2x9hWGeIpFRGkcTcu_UAGvPuXt0uExDZZH
JqLAeEzOgdO1owMdwV-21_akMBzWVW4UqYS5W5TSpKYdQLBLbqiwpYuiwYe3tDsAN3HTKp78cRvBk43DioviYhS7ztAH9Rw3iyWOY4Go4OLiaBS6omfUj2ps
joLDWKKutV-E5Kf5tW2y3HUnTTOA8d9pYz2jP8jBMAUrLtETg5OC-av4S7z9zmOnoNfP8zsIQvE7wpI76UcBk1zhlgxqAjugsS0ByiA8YqZnD2Dl9-j0HAFK
7OUBTE4eTWNdBwQPohVVE6JPNhmL5wbMYvfYuHbyk_bA4cxkWJSbzzzOlPKy50Z5-p-74eY2y8n_xc3SUiW30Spt__eN97kQmHIawXYhsJvVZ-uEZZxVn5ua
Ny5UwWx4HRgmrHD78fybt0SBSDtkv-RsldwJEGNd_3WBMOPP3_1okn-yxQaktbpdsyJpQx0SPpMZ-i4ntnPpcAMFu5HM8iikN93h4OzNE9L7SA38Av15z_6Y
9u4ZedG5fsSmkIJF7OrRxG4LGh424_dS9TwNY-H1x4pmNE2AV9pneiLRhx46pqLvxbZSMbnccnC3J9u_4E_0RRZRB354NWBdIDyvY54ZTt_lmWxs4hX8ySQc
_VutLkt90fW6VW2_sBJV_U1jhmBF9G4ui0X6NBN1QlwQDaxrDo3GdCypU2vUhrkot45Mitt2pXvNtncCM8mEngqNTd8qLnx1OhVxfQWzbNfx8C_WdB1HRtSq
Rdst6G0kmjYqVasM0tdhirTs08i4N9pj3iUj3-KoW-FjWIfkwPtsIaMhNuIuSGOJRmRM2Usyhel_zNyTqbRWQUSWnWxsjR0DUDe_gNQmvtm3-21S9B_ZORC9
wwvAUyhNwzFO03uO5t-cG2Nw92k3ftyjLMb9Z-j5kWaOt8EJzPW7RotMLS7m7f-iX-SYrHN1qo7IjS3JKM9T0wpJWLBHNl1qiAGFF1qmqO_1qp5J_Goiqs4J
rNRmTEYa5JmTFj46yFGNahV1ElsHLDy2J-WFaclmr_Id-X9z2TRfpwNw0ZpzoLHq4QpJdqsG_d4l4dq6_sakn01F9qX4HVGaN5oY5DvJ9AfxdQl-1m
}

