sprite $image413 [243x176/16z] {
vPhfWYgh3eMP2n9Qt_zjhrxnEAJGPPJU9VtzEWDx-3fP1HLg_q-WSe3sVuZIo7zAkF4dX7Df_1df8iX_IdZ-GeSYc5iwKn7CBLsUG9CBprzeAXZJxiJpIvUN
sCtVqvAvUdf-wLtHCd-89PE6E8KyatHuQhmuOsmi3vYinDcR_-DIwKCpXJYQ__3vWNEOHJXPSqru93r5Jo_Ut054-fk5Ip0hkANqcIF44f-_yJd6oCOa-EP8
5snZwcDJUS0q8SOZJVHLmd9ZKaLwj-bXhGmnIYnzw7j23FGq66d-ter97-b_BfqL8VRvxjyNgzYmlcXZihdodL_b-D8Pb3Rz0c7kIRLAvLh9Y-uk3yWR44PV
ckXeNEuQc-g1xCHkjJ7fN228qtNXZcvKxhDSY6kjdEpLIgQjZSSAnb65GeldSXHcAbAvDEcRbRIfYxi2G_L0EVPiv2OibQzM-gkL0DiJFfUlBe4k6bBvX5W9
4BPYBAKldIgLNMSbncQ4fJHJwIlBbJYqXKir2JMDlh9SYKER49O0odesqzEuyZQbgMnQkT0cX77b3KfJ6QgyEUSTVTGtnN2hRCldsDXJgopHExE62oaNc2MF
bSuVy_NMFCA51VnzdjnXqU2lFP9V2a0EqbTYOmQduJQDSYPaLklp1qUwJtw2qK8NTsMKSFR0d0eGXgKNXuu42m_fwGYDdhCthnBAEdxCjJGUOWkDdfDHO1Um
NUm7k_lrTBeCNhtfRsc8v1_hFoITNxzmYL0hNh3EU-yitDpjNPeJil92LWbBehnSu4gmiOkPQeDf2VOLvqe1lSF2lobINBYqMItIrJPIlQT4Y_Ls6mb-EDAA
2vVU13Qj22zS6toaDZYjI2_zuQ7ygMUrzEjV0gJkj4fQU6xTJ7HMe9D49Iy3q9kZ0P56dREYfvimTCMQJhwTqaLfaLPPye7c34SwVsnZaZtTBtBihMtImIY1
pg2a2h70kZx2sBKATwNPAZJraIRqTAadLowFuBgOzua5-wPeHt28zJ2Nnp0R7NYaomv_HNmVn-K9LAs1m0Cj8UonPJw1e_8CUb_P2c41DU7nLJOP7tpgcxhM
oa-T2VZfr_m1wLX6FoAnQrfYVhwc7NT6bpcBlixKPP6RO86kQRbMVYxTFchexClunbmUuyKkMtjmM3_fG-MhV8G8M5cybAXzYX7BCsZSo3tX95F3a33NfYoa
yJUOGBMBTB3e9AyLcLP9OgadLFYY37Vtohi2TwXauHDXzaP2LNlIxtVgHHcNfe1-UaWrcnLSolU-QKtOB6iMEQnkJ9K1OQ4CHpgxpe47FZIxa9PyCbXIx0p0
3YR020eFiL362uqF9QXUd2NsYBaWZGaUGU72KbaVwR3kNApHOBCKaJMsS8Y5iaAQv0Wi5m69XHYEEkcCDo5MzBHKraVQfTML8WO8lPCoN_y40w72WB8YqdRf
_1Awn00bSElMpe_QYjCbsjDIMH_fsFrRNZuxnh3nOV6u7aZMBkZ612etu3EeFFl8XPmzTC_AmcNj9uY6653MHDgBnsRlPBi4-zYNJki8A1qkBFdX1n3usy8B
QGdEI6n81VYj6eI66AYoKhej0gqhtP-GB_-BYGe00IK6bDNTpLGmwDpWygLO-kBWmb8PbzP3n4n2kTrI3H06bILZlsRKoU8XbZ02RVi3Jhp4k38JRL9P2cFA
gFJMbQc2C0njMfag3By0RLQPk2gKntLtZgXoZWE4SMMzj9pGsGGfHp4yH7jwb3BUtN9wuvQdokcoKbTYN7cazEB4I50govK3X55blBkHYNpiACkLGIMCAm-J
NkIOlQCSnSeCXbYjFAYxavLJ_XNbvEGohCHQvN7In6bb-75lvsI9cI3XaShwIH47rTSFbO2U7grSYdeagFdwOPnm_M6GnIP-MPekesS0T3vD_9PntLTGsHYx
AAHFesTCMCwdSM5SUNy0L3xWCnffUItzdCXuJ-jBVA92oYrgsaWx8v5VFupkwGk8SaFNtS_kurp6GwndVmEct2yq8CtnySR410dhIon0bKrW_coa0m_Vc4x2
WlfKEINn5P0oqkCt9ccCI4jbFlsL2tEXrwNN8cr_8yJxHpnJvc9FhHrT_aIaqoziJ3_xnz0JPKwdCaTZVE4tlpG9z0iXtksVKXyhqx7CwLIggDsbi_lj4EFI
KfcF9VAjEsqYxHdKjTFbO66OHyf7MKkbDQSwqlLtDYOSwYk7zim-Ftgzhhl7z_J-LQfGRYNrJPdfAA-Ez6XXtYjOVQt8oHp9V20_EO-LD_Z4A-ARqXJDDUL6
sNDIH7fOY05XJBhuLMLdZye1UAs48HuhZ3jpTgPXwV98etXGzhsZDmqKnXzRUcawJwRZxI4qNPvfRtStZGinpkucqaTfJtSRbr3MIjFdXW2VREybCtULioBI
8z-OzB2Weno1C-YmsUM7GPM1C-XMGom1bG_aroDDFF8uhKUhtA3jzxH4hToWiMEFyT8PK0Qwczxp_TcDivNI9PoL0wBSfBTnkbI_IsTtKaw8SeEs6MBy34ed
TKovGGFUc8OZ95oBDQJCH1-yHHoFF7YVEziMvY2KUzB4xmdp_jTPARFDP45bVayOs9Z6InVJG9M_JbXABoELvUbo4zBPcaOPMcNSUBmp-PEnvM7AFqruEzBP
jpCemCP3Z4kN53D3Q8nflnag2qOexpU5GldRUbeoLBa9Vxdqr_QqFjAAZUdR2wruHVnsQSNfyjkx-uj3B46LyUVq99MUfi9ufP6lFIPpXWvRSra3xyIpEGD7
ZzcaWSVMRDBJz3I-OG72inLw9cF93b9k6zF4qi0TqspT3MnCiqdB4aylBTwOvgIkA--dHYWBuOcbnUboVcaXF3LqLfxQKXRwdsrC_mC
}

