sprite $image257 [260x258/16z] {
xDZbikCm38RXB5WV-Cpc_g-s83UUB3DLVW-qlv-H0jvNVw-DT3yokTSB_C10sej5t0bi7mYwLOq0IW7FVzKGW1o2RlaMNH31OmfciZGGIer1j-MPkcIx4881
Jm9eA4ZkbagDWSOslDus9WXhRSCO0_gMjcrxcsF078Hg1Za7RxOjXW5bbp7WM0NAzmA-1vGomCE0tKToW58zW_Cp0geQn4H053FOfq64ydMfjHZNWtBt1I9Q
Qp7-WTKCSkg9H1W4e5Jh6Mai0u4OOOu1zrBBa0X80N0-9XPxRsJ48S1IxutPE3zWQzDWlZ5LEqhZd8Cv1SKGV4jyx46t9E-b0l9etTaG4FTY7IlGZt7GNg_M
0ZorrukFvqCKDcXf4CXA6q2tW9g3y7OOw1wB6hHxGTqp2nj0cSMiv2feT3mkxgNQae3Jm6d0SWIDUkI1KEfzeMNGsK1Cab82GSsSANEHQs4BKATyDBu_DqD4
902fS_weTyzxR181CFkiGUyz__Ld5200pZvlSEhv2BxVuAK_cG61E0NWynQ7mSl-JqOxiZPx-mrDWtOkCUQ0d1oEEMWV5n_dxCzTLpd2KSpQ3nMV3b-8NqYd
bi4oM0RBO1aiWsMm39R1CbW6o-3Atfsefye3OHmdixmpamIy_xlz4g3Q-jHgF-q1M_ykvEmdlmSqOfVD3SubBfhWg-oh_6gnj8r1tbE-aG7ol-dI-TVmKwPR
6OI5ctdq-hYDSXlrZSVokOlMXhddVH8FpIr2JD7RpA2ukpAnABEOAhUaNqISTTwOj9X5J9OUwE0DLw5gJBQTWOH3uQ8Ak0AgYkNY45P3k2eWQcfG5PW-qW2U
rKoD6PiPp6y8jEBpepZ_S65cwDVMPWPGnKxQp43IrX4JKH8XR6SGffJKLJWb2f7EegQWz6zY5I9IbWqDF0gIvbfoIibhAIKbQnjB_oOYOTdOO8sM-zwyaVIF
ebvYfiqCzDD4pgCVRqC3lC_SMcuUvZZbvapffzkBGQvr76lDPQo6OvxiWm51_cVdEriwfhinY0XlMHkSxmTYK1LHrqGyF2Rfe2QqiG6t1DTI8dOlxkfkz503
zi361Wb2rmzs9KhKRkj5qj8Z318JRMsWcVdgP8G-CEc3OhHqRbC3OhhDu8VRqg35Gb_7Ugl1KwuFKW_wIMxcV39WkHedVf_m-zALjZPG64JInrGKyrg0sfX8
qzKuqJ0GjqiQ1b5EILIOEhBHtWt4FBAV6n1XVkgIUIp3rMQ3vE4Xmw3T01uvsZQFkpTGwV7705ZRp3y_6v1G6ZW9IVh2O4ZBWsmYNbuKjaqRxzc0UdmfMUDk
81hkncwWTC60ttV3WfbFoMO6a9jIRWP4b1JfyZAH4ylx37gHGSxJpGnikAaapO1LHKM4JC5qWu7daZz7jkMj2-p7W9rkCH0rju0pr6yo012V6y3TsaNtOu2i
jnYawyyBp0eLPlaqxWdcjBMZOo6npK_e_4a68Aq6L-D4X8Yt1HKyt8JOvhcj2n0U3yT6VhUotDI0FUS86aHL8MTJXQXyoq1p1dS3A-FKA_R1e7-cJ_lPiOxJ
uH3fs4uCO33pCmEYRnc8r-8g2dZj1eTsoVFST3QWDlCntCqZryF4Ep4WD0EaGUN-Oq5ohRM4kySurd6S6SOu6N3xFnI3mZpAUC1E38PaXk7BRZUehVajp5fo
c4NfktoDem6r8o6WsX7oU8Yz6FGUPA2BGQq1RObw6TlEdzyV2wD3HTGiwcyr66jhZ6KfgEhbS9ZAqO37Gw0RmBmPs6yqQ09Zlxb2kuB2fyDK5mCYGamEcBbr
WqdesCO64lmuWzPOny1geCZJD9uCF1iibnpM22QcLaexC42MXneKZr23AYBSVPp6_7OiYBb1FMTWR0S9xULO83QcnnXWwWWPuL5gU2wrRUeqBGP4nCW61Q0s
ZLEXNeVOoJfn44vfI7oVmJIEOuqwUgt5t1rkUPhgcm5fCOX25LEjSNgtUoy6gZ2bEmtcnadDGWqjY-am7WtOp027MZDm8jg50MapqDG6yt6HxbiZJRts3y5W
eggYvkrdIZT8BNOp3oXYggEatQmJ0NtGOo9RNGqCC3LOoyV-6Wd2gKNPEuzvEKm7JxzmVS0UusAGtICCvcxUdm76DmDtWwhbHMe_1lIuDTAuxWTZH9uDpChK
3ARLGDnWAitWq9faBmRwiFM1JQl1D6KBHsJtdCTnCI0Y6mrcWMxGotjP9-BX1kihPgjJQGOrbtK_a6aqm68-WpB7kzWF4gk9fCSQj4PtYnfHSWxBOpUGDlDO
NYaSrWhlwJpIG3Gq2Ng0GMki0ODvbCZXPguYc1yep2nA7wrbfZqP29JlCpWi1Yx40isvrl3iPWOHh7CsZxoSQ5ihe8qDaZG3wLDWQjT763WHYmbA7LS3GDyC
9ZVtoALsWpLiQz0IUTXZul988Cm29HzhBP5d0riDMcE4k-ToE9L_qHffCGWLKMMP3NB9rWr4x714E3SejBL1aWSR6A0gi3eNrki69uI82mQxNXzeUjSb0_KU
e2rH-1pcHD0yngNI4QRUOQvkRg2PhnkmNeqJo_zkKmDI692k6QGRUbg3qpaKOsgN2mPogNICvEaDr0t4tpsNDXkuYEXimA8VarjYPcnxJZNdJd3g-mQHFRg1
c6PyFuF2DZKOY6Yupu0eKUe6Qg7V3mgrPrWZuJoTawJ7MCABVxymyuqD2EcwGRebuYl9nNXR0yjwjy7zFS77fQLB4INgFRC1MOHxQXJI9fik6OWU6qvZ7gZ5
pFShxECS2glZAuCm4PaDH0qmL-Nv5pLHsyeQCwSleWl3JGsi6NXg1YaHNJOGYGpfTODSIXILRW0ej6zvJe5CwNAQMaIduNpLJGq6Yavmwg81t7Kr4Cyvcym6
bWQIr0sWeY8C-zH0pLoNYLE4yJ9KXM5pW_L1uBg1U3P7C-3P8BGRT025TWD4b80a_jn0r4oMYJFCQ1cA6UQVVOOr4ZEBHpQMOTdZmQq6IDGLKWBF2H2KpgDZ
-ldm6PuRXHamHziEt4B8Qi2hWNproKjyYfX5vuINJOlJ4woHv5IIOxF76Ztr6ideki6Fjulr0VF5Dw6JmD-Az_bZYjO-31GAw0M3dADTBRj7UEJZT-J18t9H
tzA0yBP6cakN34ejjKRnTk-Hsmyyr_OJZp5WsjHWIEusd7NvMB1ZRdVdQr5oFC7w8Frqpsz0vwMpv0yOh1BBRVsnA8i82xUn_X43ujx9W2Clt_twpnYSHgVx
7XF_4OFp4g3l-oq6h-U5by6Fzmm6BmEM6rAL5bJML0HoIseclyGWrvABJRMqJIdLI_4-kEu05lqb1Z1pL-z5SLSpkFaj1e3itu1M1AORutRzLazW09a3fP-9
di10QKx_bO6_36BOeG5uxXSQw8qnAPReXzhEGD9ksj3WPV0oS8MU9PkraO79lPFNKxWtEpDuVO-glsJmCdWPl0nU1Y-3by7Bu6NmCdWP0FZZ1bYobm5Wpsu0
n_yqm9CP0EjDvnjEDmzN_QzzSr5k5GU2QFQ1kXjlNVx_Q_VXgGAvxyWYB1WItrElCPb4ccDf15JbqG598efR8caP9Q8oy_tMWUxW8M94tzE14oLfNWVoTH1y
MmVR-y6lSu4dEf16wUKEN09ucWC5Ppe8U9O3pNoPvuKVqxwC2gQ9x-f0T-xXkpgG94RurWwcB-TWEiH1G7q51qSS2gCrILxIWIHo2ewM49IBEH2d0tdIP3wk
uG3JuVGssN2U0qslObMhURM3Z-crS6t7rIWHfHpYW8p_SxlTfbFGEWjZS3U1ifk3A3u81-TmauAnxy1KR7V0gDwuJUVHjJ0sa9Zja9Ao5A-e_sG7ZcQw3fpv
uHi06eNVKSsOCvtBw1Rw3hITV1sOWojjYPthl-PcS0qtT_0uU-t2vHou1Tic1t4n1sxXS0U1EVXhkWhM57wCEf0hDCN-2vRReGxiJl6Y4cuwciiq1Ey0rOVZ
kQ23oHqSp_iwS0iNTJ3gLLnd7SWus86FTSnIq1lnp05AG0Np1Qa44ESSH005Q6K04W9A0H5KFw5VWe8qXn5GcsWhK2c1WbRbhiLp4t4RvAwRnjuEQ5KrA_Uw
BFVo3jXmGDiAULtjMN2fodDXkMSxOEw0f3emSXZCaOBg1sHWkPQSPVibwnxCEiC6I7OSl06fWv4qKKtGfsm6NRYQpphWMWV_h-XXDLiiTPNq7J3PetN8NhW-
bTkGgjW-P5FzL4CWwrEXla_W4g84s2yLpLI32b1VO7ayotty6Cd_9fuuO6-AfLCu6zKSxw3eJbOvVvv_sq4wcGCAxqfUxq0h7CX7YcJomnI0b0W_XA4wv19c
XQSEb3de_85r3f0uQ5NkOjA5053l1O7fWG_WuLHed0jQdU795keGqaMxNApcb3a0yBYkMCL9I0d9klxaxs7bxmNFzmBzO62sBr5b0p_C0UiUQzFRJmUhSAC3
DXtaJH6DXYGyBWG2h1jkVwPvXTlSzV-oFw07lYhi5L3d1iKtmyEh6qZfkH07H_A52tKOi7K8zDUFjZjetRCYw3YWlWaarSA-8s2i5O3YZ0865b-Tih4X011B
uvOBBunfrqjtBp0_Dlhth-uWNamr7ZzuS0oFLplWCmViBWcne59Go39ZGws9AV40DriSi0JiBmcMWiK1HCmytmgqkEjfRmVBHTgdBRsZMWRwBkJFVKHWBsjH
En0Rw8lHVNnVBfe322MdlvRp7hz-K_GFYtonfnVLFmtms4o6PIkK75X9H_dOxW0z1ww3zhInR8LYcC4D9PtZeFi6U1cwTZ0C41giMRMhbtdF0VTmqATsW648
1GFrMlprolQRyYIHnK6pKuh3CDmT59k5VRBfxeaFk15tuAZH6YJT7Vmv351zbNuBOZra5tpv1pPwFRZLrtf8jpbsd-DLXY6s0aiWsPII6zDzqNO7IO6bxw1O
Di914LAD-Da8hkA0-T5ikxV_0bWOxa088XTOFlfh6c8h9GKsn7e7-ICsFz-Nmq4e-H9Oy_QGUJBjUnYCae4A9fpjmS52sG1sWGU3L_0BlItuZod-_UHDkTtB
_mS
}

