sprite $image324 [214x324/16z] {
xDG5SW0X44HHrc66sjp_j77hk66_yc_mYcOkAFsdHOef9iaGgFGgZad3cBI8GMadngG1J0YNfIzbc8VIE2ODOz8Y1wKkZ4aRuFAXN6lwNPZnQIl6fFLdehdE
z8TvLmz5UouteilT_jfbFQWAkBfGEMw6VfUnNEv4bp_rvwopgIhdKgwsgWoPeQeAkhof2Z53LQ5SgW9yBrMLTpLI4MQeAis7TgdADoy-Gwkl2c67N4DLXIbc
X4jL8Im6kFAYkcjpWEkLAapxu3DKrMDp7DprMaNuNgzLzRxNMbyLfcFW6LuHSn-whUGy7CKfJL4RtBp_qsvDS73NaQ4D_n2DzfLjFzXaZfd1JbLckSL7b5vb
Tge-XlKMV5LMgSmaMxwUPhcqoIj0fOYealxTgrNW4gXKM_vEdtjLC5u2bMpBdr_P8lYE8b2fjlnb_xm4uoLGYIAg7iPUTOoNGAKRhzDuESPBe5AD5xl2B1rV
7-Zfcxf1fHYlaldiVVstN0In8LEPvGvhnLLFFi7ryvrZ4GfS4fNTO-rZoEQRVEXkmPRNgVfwH9KyNn15iEMLgjM8giURPLvD455ArUgMppR_mLk_rk9ynFfU
rVAMl-QHb0sKm2LGhMnv5k3PldaTJDlRrsOLNvNVkqgTR4PG0fT2vOwecn_AWjytY5JUY2glg7hbB8qeL7rHvOoechvGa0HRNg3oNA8-KSTl9A1hBhtATuaw
35GvanclVDNLyTAhN9Ueymlr7r8wxYhOXbBLMaInq_Flf7oLjl3QgLhVygo_oPiaS8bLwn4rUPCqZ-RfLMPB4SMRfBxBwrNh4PMDDqdiqglMn-jcadGklMhx
h_Fg3bNyh_Fcgd6igCeAFlxNUQXwpGkgPYkl-eG-4uMgspLkcQh5FhI1oYoLSQfK0Sz4JRT5RktGg28UsfZlm7FKf53jsl9zSRFVurQfp3Pl-RdAKksdIcMv
RNBDLNHFonhLdl7gYsrnZP84gf1dekOgIsLS7bLCHCrLJ4G_12h6QykMdwkOY9f5AhDpuvP7rRx_Md6hL6OR8khNYeg8KgYsHDI2YeXIgFP5r5p5w-mrALJR
8cf1HKG9L9ks_8AAY1AezZnOtXTKH9H0jMEynhEY8gAMLJNk4jMVPqr5H3bKUyQhZsTPHVUige8kKVzObbKSZseMgDGHnOVlHwhIY2YtoghcAoMc7wfg8w84
gbCOKUFvkQho7KMX4cnvJ0uL4QLGYRPy1-HG4L4-rI7Pydqy0XKHvLOfBb6OV2eYIgHoZ5V7ubOHKGAL8w8mILH4b4FL3aT4CL1A5PSeXyfrYS8aLF5LEOjK
wn75Xq-luX8bKgrVeZfyjOg9wAT2jNw9mlHULHqgBb42rSAMxy-pGKL42LJpBOzfXug84gZcMvw1sgao8gevLVE8mhH3HKG9LFFnUfxDAY9Ae9gDLv3Ah8nB
e6AyF2hfyQYFubOnNXxLqvJ7evxyAYBAyLxTeoIHobeVjqfbsJLNkOvBfIf4LB3AxEZz4Ad-YQWSh_hSfUzlisrPHKJ5gooLjnFHogAAY8fLiKl7AL0HKS4g
yhiT0XKH5QmYlslogLOkKOPtYyfI7RT0nIKgMaNtd08LbwXW5QdIiaGrtV8zG6L6H7bLRFbu5H4bK7692bOHKGgLsK541Qg8A86A1yk3LKIKGCLuXQk8A86A
Y0fN4L425H4LhYAYbbMzB5oYWbL4b415H8MhE1u9L4HKj8hZKNQhcDNdY5JnQeE8yghCk4G5gqfQk4HPlzTK9yz4nQg8A84gSucALNr6L1AfpCvHKhYAY5Ae
YAW55IYzYeXIgImJKI6gVhz4b415H8MgY2Y1YeYALX5H0XKH5QxY4kLGfPU82bTnYHAeU2OgNCKbIgDYoyUhZ8ZogtYmF5f5H0bKNAA2LKIKGaL4nQg8A86A
yOfM4L425H4bK1MFYeZA0XKH5QuYeWGg8YfQHKG9L4HKi8h5tC_XLn5HXqFLab_5aqV5hM9MkqFL-wrIcOsd997AhBW-WNS_PQfAHBbLXqjbgROiKjr4LBJA
x6WbILGN4HMlChlw9L8HKV4giz9FaOg8YbTPRZKBL7nL3bQHO2LfL7nLZbVDnul_UKL5H0MhIB1--5LyLJwZLOnN4gWOhs0L2NQBL8nNlCg8AB_gkmVBkqMe
Y2Y1YajKi8g8KgXU8sf4gDZo4XKH5QmYeWGg8YfOnQItB51nYGfN4L425PUeFQfvu35U0XM_RmXMCUdjyAkuH1t1AYRz4QY8g2TKnMkCMwKokxb4nQhwJKIv
LJRQqflw8zNpVrGN4ILG4L71AY9Ae2AYebL4b415HCMgY2YHYeYALrckDGjKH5IqYeXIgFYg7AzYl0GgBb4ngd6zH9H0nIKgNCKbogtYgtBB8QfpSeaIg1Yl
M1MNA96AIrIyYeZoghX4nQk8AAUAIrIELh7b9IeYAbR59UgGg8YeU1KHjQvw5YvHaIeYIg5YoqUh62-1YajKk8g84gYuHBbKnQyYeXw_YalKxL0zDRjLRAtg
Lt69ygYUvquYbOtMJvNABf_g6PT8zLn4b4FbsUpZuTKFXIez5n4Ly5wz_j4rQLH4L9XgFBp6hL3nq4QGwjLr2bH4L93grTMoKtKQFLVsgtwDxrqbILICrrRL
nqV_dZKkWOg8sgtw-40rsV8E5PUepQgvwtNIdn-ek4JjLC5wTTq25PUeZIfS2rl-ENwYuXArLxKmNcuL4RLHnJQSH9H3DTdoOuTg_Z6y5IeYQhDg_jFh5Adu
DyPkLCrTBOjKF5YUDge-wZIY12h6QxDgFbwNG4L4RLRDNLsW8gAEpQgvgoMtYeXwTglcFxrkbShIqyzjgeM84ga64RLDDNUrGwHYo-zKVVoQHfH6HKHjKAr4
b495HErLpMEZdtuLM_xDUDqIrVfuPP6AyTgecc_vaYGgnck3QYcYlbSTQwgNY9AfdAv-25HSebGgjwicWOfBr6RL_3lABL1nYTgWMlsgB51nYHAeDAwM1Igs
l4Ob6I-1YYqlK6a-XhT2HKI9LFujVmfKH9HKvOseTLLVk4IfLDw84gWOBvdA7L425H4bK8d6wrfJvNSg8agWqhYUqwqYehf09HglMwKogmALRBnEZKerLxA8
ElwiveuE28XYA8W2GBZzT-iJP0U0IGS76DbdlIgEAAsADr5U5KUKLyKHvLLnHBsaMlvGnH7bLV4coglYCr5Q5P-9ygfu4-LLyQUyLyKH9LKngnPU5KUKLyMB
Ng-ApqHfLHnHNXL7b5N5XpRMQbLI455I5M-Yl2hUH7bLV2RAh4eA8aggueZoglWtYbgLG4HvLV3lFB6ADr7Dh1GgtaHfLHnHNXL7b5V51ykzAhxUe5NnvJol
YYFAg-A8Kgi2jpYmgdWJrQWK9ex3pVHHrVPVH1nHwqQbUA8ueXgLm0GlGr09JF0oR5G254LKeqAJn0KgC6bUXgpQ916wM2K0DH75gfZcb0MglKFJVsmCgIAS
MweufqWLxmogjb5Fgzh5FfjhbKp0BZ29NuQ04hl097uPtciw
}

