sprite $image122 [277x208/16z] {
xDP5TiH040JHhLKWt_-qPinECmnKn7hml-n-kfGq8Y8Y8jeXqBQu2OQNnKEw5amy2oJtPuXY3HCR93P8R9ZO80bOGeFb8ZvTCfEbQaYax1OKIAflmaH858NB
f4UWRDyWKHHEZgf0eYWHmMNo6YNkc_a0Mxtq-ZPY9dV9-tC4YLueKeKsYSIpL9Y6c2YBacX3I9H5IRG195eAYMcSYUQ3n0Q93H8N9hOJ984bup1jpCG5YGqI
6oOsI9Qo8D6g-sX8zcEPINSp4oLH54xEVP38J1mACxacxqxNN3U19W0NEzq5kV-x_PRnmHeRQv1FEYPB_Sg-l0_LGg19lgEewd-PXA-kM6_v9v7uAycNcpEZ
w4ZzvomJN4bfltEZE7tniPN47gN_tcNyhfs_wWOKgPS-sz0vVtna0xi59SAbkfgpRTDhekeU50S0FibF7UAUjsVHJIW5l-App2phIzO_zgyIUvI88o7BF5eQ
znorw4QKcZn-Sg6kiv_4_f4ioU5RYhwTlmU9r1LAo5NP6bLAzBVVuWRAdFhDHPiQi6mmyKv-Gd65lP6Z0QIKh3qUA7FgK76jxRqWqjyr0TmFAFdLU2J3EOe4
ZEHE_QtiV0oFVmDtYY8dJupJbI8HHxH_wCW_LiiDRC1NdBn6gMDZiKQPIU0NxJ5ZAVyVc-OCaw4oeyIxIKqnX7ZiuTChb1emuXRjCLKfjrIZnt31FJAZG3gV
jcKkdw58zXZnuW60_HFNPkL8d4WCLGRAMFuPHxoCt_8DHKh4FQuq1G1_qZrRblAGoSHIvV7VAc5aJELoe4X9epRtvrLQjCTEHMjvI1qazYe3XVgLYky9xVvd
EU_mcCJUg6xH7ZiMKfvKr5hb4SKD52sFctVUcAQu_4MYTT4UGnRocQMAjShJJE4nHWFkSUqbIgXZenTltQBQf2zGgDMIPMf7VK2HfaTuF5-4CeaKzc5esXvb
Nw0iM0nLnlHuIWa049B34HVIrnhXmz8BlPbTBAvHfj7obwYC9Q4_7GvatiwEVe6CfD4Ueul5TWM5d1QBkShn-9sJLbSSaZtOFt8bpv7Vxb2EfmbFAj-s_tF4
h-zzMll8bJpvPraYbXag6Cch5qBx39Bvzdc5CkzQp51Glg70lsG9Vp5AExbzNg7CeyKA1VKBnKLynIMP6-H-HX6hhnG6YewiKEOE6Q5e0n1RS-StENanQCMa
EGFbz7w8ho8JYm6AzWOWTGOSyR4ylpAM9Y8dJwVIh4pcs-UsG5cFblTHf3S543lpj6zzTK0Lqk1wsBmP39HRseIsG7bhj2GVpk8VJHH0w1Gy9qx2qytNsERJ
QCwswNSjKDuTBUqaz0yc0sLUMwYSKAPb54T_3EPAUp62r_LPZvPrn3sPwA_Z577JKcdt-amPZwcwwCzrbiPNL3FAShIypo8U8_LcCb2qJ2YTHqUSUqPBOj6V
GT1UhvwJfy-wGqN-Z8dUpvWo7bCxxwkXzDOQ9OTdblF-cCoP6SLWjAnD1iga4beRS-FOfr1hn3qkZwCtuwzE5oWcesKsASTO-tRmLWFkoMqib6cR__sAenhq
PshE0iLojCmc1yhurPg3Syx7qdex_gprPLYp95cZN1yjTM4I7amcb16s_myV_gpbjMat6oOh5DlHSfZaOJAXdAskzGKxxOR96gM4Qj2XCvE1mXEK34meBqkK
crrprYW08WrOyed9G0dZjUQ8PBVwuheui_uS94iKHSue5gCbu9RKcaueUgk2Z_ccAbAInyYbpxjeJJ9CPXIwnEHCHaiyJ2QKW4LAFn4PgSseEJF9Z99G16ho
U8ut4ukl8oNvwSRGdkGKXHwP5r8li4J4rcY14gSRG_lcdAEKJ8zA5hNOjUHXOlSP-YHYJZAZL93UCmBLODTY_GCBcNrcjc_E_4ZEh53u38ETl-cFjcGT8iOa
iyayQ7E48D9dgf0KUN-qsAFKqeQ8VNEMA8m0570-qY6G6L7V6IrYXpB7dgHTkpQjiT3dudn5S94PG7xZKA781XJBvepmESbJIWO5cY41sM2qcABOawnHw3nA
0Pbh0fb0LeFHOeXYtvmrYWRKYb-Jbm9HL1gCbWqexCjbiaOvWiBA13WFaTN6HQuUGULSrz6-fpbhb8o0cbnr21me5gE5Ls99icxETHGcGACZGw10E6NTeRrf
w-QyZq9LHaSgH22QwduM-s6oHfcJu8eYLqW68gSiHykcy7IP6A2mEk0BXQaWtw0CHij64XEMx20LgfN9aKAY_CqxrFh2n425oWeD0C04BoX_wz522v9R6dzA
XVfG0-ZW_OIowb2fVvFc6BDKHiy48Z8iKBQEbjQNMnFJ3i4xHsHM5EPiy7ZUC4pC5ul4uEWI5QK0dWOi6vfZlbeqC7eAQaJrwKg7FiZ2LNFiLKO4AQ86fu8X
zGwB_1sQOy-I0TG8nF6AMA067Tf0OjeXGSrE0if0aTsZXM-RsBE8AeIbBb1CHuizYVreYIu4Fg1akNvUMQffSmnCR5WYe0ye7b4tT8ZTu9bZDrgKJoX0UUTG
GVOtnrw5JoY-UkIFZXOQDCUMPKOX8qX-RBHi81cvZ8BAJnugy9Ja4_yDJLsYf1iAGXhzCHWj6vfZ-VRiuGhfNG8W1Yz45YJxMOg3f_SK7tWXEeqMis7IFli_
KbYz4AdtfCupnNwqiEzT9jUFAvKUYNI18mQZnQ0vcpia7Yx1yvOa5gDbtHnx4_lHWh5Il4_rxT4YzYJxLPY331G0cU-oY5rpze-MEG6CA4djEaJ3PMAVQoYE
5O1JgniY0vBjAi5Ja1JfpSUpD1gGRCcbbI8e39uKlSmYhNSQD6TJBg94i03nMeU4lKyeTYJxjxWI1ug7G-0gzHV9ZDAwsQP-_tDee3XtFr58YUVf_HKARKds
ToZTLeedeoVp_xPJ9rbkXJ0KXYyzw7AEzh_Rc4gVOB3JriFwPqm_9DNnkbkVe6mtvv8iWo4wia0IaD9JA8FaWYRx7MfXWB2WUWJddqBPaLoMPUG24wftR80y
ZC8Bauouhk5MyuuCa19aYxBVd1DKF0AZ8nEaeF9MSss1iYKvWaN80lcCKZ85wJxA6IGZxdA1uHCAsW9bHT9rT11BnQrMtr3g0kKWab7VgCGuKCele-Wruphn
hI4F529IYZo3ejUjSvFpp1zHF50UHj7HiIeL3cye0aJK1r5qT31B3H65Y0sHoJs4egF3MSGN8WYG17MFeeV4JK84mZk7j4NHS-fSbmA3PqROeEXPSLT5PIjB
53qkuQO8x-eAHK-CcnAGxwFegNKkayPxA5qFZhlcA7fs_HTGzFoUHUdw4Zs5eg-IeKmpb6c6CgqRoYH3cMOeqmnbLZUKMOOopL1cTKEPPIZJkg5CaXcAldpz
HvIkgjRtAFfjnj9_DZ6L_hE9iVIVped5lqTYMPPbMPPbMPRr0G
}

