sprite $image302 [264x192/16z] {
xPhPUjiw38GjYglKvVtVziIqEbqWkVCXn2bY1ZVP4_iFPu0X_FsVLtkhxzDNEsfs2gZPANoIQAAcfu2QdG9gUWgekJ1yacX4JKBX4qIZQquAjSn3ebrNN9PO
9OZ9AAIbLsgYPi9Gmd9Ko4tKDCQmBZyhjfEQHHAejRRJUdqC6PA0A4vh8aaiQtjMBzqh_wXaIiA_CQ12CGBXlrUYf5NAUkrUIRHEr8ltoX9ectZnNfaCRCAr
CQnN__beOnF-UsMiS8jyl3KGXtTZmE6F-AXB1fKDGFZhbVbFDB4A2pMm2MUzCfsXIQVAkQwFFqJN4pJe7aLj4_ufvBCdNC_6IIg5eZxs48qd72M9oDrAe3wG
CSJbhEA9CY05Wr7RrH2TXI_cS98w3KPjRqDq5ayuNTg4mQZjg5SctYRuKTiT1I8nrDNQ9lmFqGdQrzX49aWuxfMGHCR1I9nDA1Av_-LCMQ-rVoKEXKquNyxK
-4pxwMBUKYHotnTEIMZ_x1lpYJYAur6RNyuKuHPNsb-5JJXFv7oknBEeaT5-V6eJDT8zr94n2Esl5zelX4tuI-HyhtoFzfFtHCxtIj4q2EtxJUJwNidFpyv7
RVs5KyX2A8JsdITo_NAcDaNCzZvgyyiPk0Ml_UjHsraYvusX0CqOxPVLnwZD3z5oENEk_SnhFmzAv0wMCtJCzfx8-I6w00qdQ5xxKaUAvPTjhvGFZT2--8pG
FjjkxMs27w8vGSkX69_ndiZvT8rQ2K5hljLWr3RebKAbZFQHoBcOFIYHsruu5KhxIH6pjLFvTTdrIaFjBtmYNrYRC5tEa35xhVItnZOaaQSJ9cRBcMWRi_M9
F8Vp2SjeEGFvKZVn_riYB-jr4nc-d0bu828x4zet7RMVMkVWvOnE-_KzepP_0VuyV1WiPmO8EZN-Mvb4peHHZIGa-He8xOlF34pa4aJ0hJOtJgXw9QbzNj33
lpKKTj16gPSpzjflgkKNlYbBC3o9nfq6Lj3ssfVjDfwrTge82d--S25psbUCskflJJX98d6nnL10jrXhKsLd_RVoow-GBnuRJw9nbGfw1nUp5T-gZjdrhBKR
bo9cSzhNn-ph6DpusZO52IFjIu-Xbr_dCPYdy6NV5IJ6n-prNOllqnZCrxP_-RA_5G62I5tNsZUFsU-Jn1k5pa59GggqhWOnc_jMe5D8uWiu3117A8JsxQPo
lJ7q0WSbYKXftsBKJl8_aJN683YCiedhc_Y1KtaSqYj10HoK9FYOFJ2Hu_p70P8G7CROX7qYn_aVq2jFEDZO1AzzVlcLJawXLXAImnYRi4_aiPwxabuIu21h
mAXjbSXxfG76G71GYSC-aIDR3EYL10Sr2Hc8-PZDBxxBW5v9Sz3tK9D47fRJYaf9y1pquiZBq9YDRvMrgdgbWeF3H3wmL_8S31AvBcRBLhaaLQyaE1ZRHD4d
yb063T5Q3lQ9d1crCsndq13DSx0UjVdb5x-SuOs1v-1Yr2QMCxmaA0v69BJBBtnhoDmGpKk2vs1l4tpC7hAS0GM2WoK9zMjCXruuyHpysOHnh-Gv_Ej47crw
9S_1oQXjAmaz1v2mNNx5GSiPQmxsYJmCMCwCvH2BRIAN70mkd0Pm2BVGJ6t2PZbZmE5sYvjX8gzHB6S6N3WPSBXNjata1iiP6mwtK4r7xP7B6JCEIoUnDjD4
FcevOyWXRAcJA5QZji5oneJ3lhUxF99T8ZUuS3BXiEzr0GUJvTU0vOmj1vXaHjEmM7wP6GDVtx__jL_4moIt64AiutheQhwSuIdq-Wk7mnosnqUXZHkrW-ro
XgTmr3D_wErYAVkURqSLWnvgOWmy1jGJdsph_HJWS0mSCEqld7WAg2VzeeRxcsuLMxdZQ0DwgD4GhQU0kkwRUruxXwM7yUFjEyLHWmj9K232Jr_i7EBnsI7J
H7BGAr5FINHhHFB6KDdUtXjoNHK9Ox2L14kYhJ-DSS4n2EWPJKi2IIDaZnGaYHf-9EyL7CeFXLG4KQqugXDZuCLnVnjmJ1xlnGE8ceG3O-19zEGTkYrqfu0W
jdiBhKb_SUT44hnDX5k0C52F4v9lYtAkSYG9tYRYljVZGA2MkuCc_kBEloIuiIeU3f5w9psu9FHMWeHd2Zo9RNcCLSkZawxT9HCPElmR0q-YzJlRVdNx-A0z
EFJUIdKE_yR0W-WmEe2mFpZiPS6qIP3mB0c-S_JAK4Vdi6yH5nE4EFnAWYUHbeS6IdV9WyCHGxTzF0al52I9LXjS4XoGFmXnU9S4tpdWahzmoBYN84Yufi2J
W4k2moEOrpvo4RVQpes19v4VBWaEk9_9kDKcIBZjbJo95lS_EFHnSyDbBY4EtvBWnG4EaCfn7CYvohyaU189wIlUYSI-uIW19q8Z3bSKUCCyadUuSmY7M-RU
JmWIpes17xMNu-8ktu5q3d0BeeUwDmQUHBgX0bOUVQwgn3JXtXXu4blysIGIE6HO9ISE_vBWurV3L8ar1t4a_4k25qS9VIl-kCt5CMaxGU8ZKg1svCZVJN0G
97mRWvu4rXniRQwDGKzYGvzWGMoU9Q47aOyBcHORY-A3KU1VBH0U5xXfi-S02gv8u0LbiSyKf43yOz1F4xr8PJYde1ymEmY-SNYde2UH5nm7elnZq9EeAM_c
_UAxozgrvO222n8EABWWuG232n8EABW0uO222n8ECBWWuO222n8EABW0uO222nAlZO4dmLDuRH8aXPS7CG46YWH5OG8I18KfG10KfY11O9Y2145X2X84XIb0
41Ic845Wc884GM4A4WI5AK3CYK6Ia1Jc924eJ0f2K9YKXC0mAGb1OL8Ie30v262Od8G32ly1
}

