sprite $image192 [207x164/16z] {
xDN7bIGn30JHOoMobV_Mxew-Z4IG1Q95UF1VKbmMTkcSWzONmdCFYcDUNckA7N9pIdzI5BGrlIqyzHo6vxQMRh-IObKzX-7PFPVXDLs6vt9C_uaSdNBFQNWh
bz4NBGCDCRQV6t6vRXffIqHDPwJXbBrD1fW22Y01JzQopIWh0jC0Ivq8Q82bxjG13SNmDDC3C0j11Xg8qVTD14tHA25X9e5ze4O92YTfT1-FOaGQ1Wrj0on0
13n48u3P7MHwqYY6WmJd0TC0300HpvbhD2y-qAnjD3VigTFKUw16UmGzBJNSuyGx03JbdWyEqcZFHZm7ydjgtyZ_StpbC4r3JykZne-R-3Xjvq6Qdfu_QBH8
8u7Z1iVfDm_dI0tcWHnT5SVah2tqn610Kp0FJRV5sPfnjZQS1qStpr4Cf9ldgA07XzwTK5snFyUgoscEqvp2UGw9XvfohAe2SB9lGHphnd6MuqEMewEhnZb6
-keSqs_1_-xDHCTH7WZ2kXTtLSNl_xJ_iGYLb364Rev1-VRU8SPVgXmECU1TuN3Awe3fjeNYfd3oImUCR3mJsMu9HuMk2Vcs2JVO13bbmmc9BV_PHjnGDKKs
d0Q9KOY7SRqDymSTIaBBhnunBhT9hHphCD9rYwnFtaP8XEEkITmTZmc9SQaDfreu4WjNFP28YsmYPMF0MITgFcAxmWQKs39LSpXbdmcyf70DIjaOQ06LUxkO
rztvHSlRE1mwddq-9cIX4sN4x2q2XqCwdhHFeoGoJkiP9H4bcw2iGzJkwi12vyY8yQTk8om-aV4nGPrIkPXbXFnzQLVDEcBrdYWMeJWQZ3y3yZRB94ZDeFei
w38MYMW5b-0Y4rEbQAwQ248pHCi7PA6IKMjkXsNADY847qnhFXQQsQdK0g0qb34jOoFGElQf24rXeTafMbiJ2P0oH3loM3WiG15A-hG_OrgGClmB04JC0019
lejF1HdZF8XPIVQf1MGZKFiXiJ7MBi9fp4K3bF6nq9Yf1SaT9aHC7gOWuwQvQux7FbKXu-KnWaHyU7rBPxFaGa26QCU5NFu802OYcYCv_hrYv7iu_jC-QQCy
THdpDcyiEf0C4VSBsQLYur3yDqFxt6aqfMGQtcn22_7kWvPZckvqyR8ni8BhbY-ScMvJST561dQh5yufvLNo17xO10V_p0TKTvfiacGmruOjFQ-WEclFEKnZ
ZtmqXktz_z06Mp7Qum0fizgjy68onCE4WjJOPli_BVGa6JV8C1eq_6zgA1JFbB4DPJxb8tuIYeYwiOV8oTWcg15a1FD2mLVlBnoIaOT8oDXc328WALSvzB-q
8XxY5PaFWB4D1qLC67akntMK2iOswt3RPomKp9qJPOQ801Cs7FXi2DieHQ3oicqN4J-dIYO2h1hHAoE1NOOGRL2aFeZGsvrZrF_2f8lMy2obBHrxEw0jexWc
dO1psImQVzfqhcmCwWFShHJOks44kEMo_ORJEkzHslvpIj5E89pADgJVxHywVTqVb2arxxn-6OQZsTJ91sH84eXaKZ57Gce7FfPZtQPJOmWBPQH8034pL9W1
m6sH_9pw_sp72b85o0N0SA4uPcmkWJwZLU3N_oAMyQf9wpZT1ZvQnZOp_2GK81yW0-gOZeNYzuI87JBg9Z7UtN3lphkXTWcrkoBAxvUzPtn4HlYq_UPWg5qs
Pk_eTncHtjkUhViRYUnd8ruQI-wTOpVsIHa5U8rBVW-sCQdzHV94E3zqfj9zH76tvnIFz9LJTiW-Xb9UoLTUP5N49ewbR6CEbCDIsJNl4QnooCPGQKXwHalz
0CwiX66DudjXNdq3cO9Jj6PYbJSFcnHWtqIc9BNx0jiUL9t-4Hs6inVm7eMVqijfvACnBvq6X-WagBuBFHndyqK-FG6_oURvFkn9n0VBl7gUBocQuQDxzWK9
KVqGNz8pGtv5D8OFIkPRXAAVoHEI-GuXiby3-UpZJ9x7b-on9tEa-YqyFfWyVFhYpyClKJ6F_nZBG_Am1YNr9t70XFsnYB-vJlu5
}

