sprite $image183 [233x170/16z] {
vPhh6fiu3uHXV9RW_Y_tEoGaNbgv91sgFh3pPxVdl7YaaHmcTysvXkbVeDJ-fppV7JFKzbIwDIPAUwl6ssBEgUrKS4_Es7QwQwcYDalnRgxDRQ0QRXOfOnNS
B5B6IlEz8cMi6cyNANSjrLZRfyhp3LrhAzqaKkvQggdzXWfk42b4gTwWE0t56xZsNb4J6ws2wsqfHAbUCrBk5JMfdQWQhX0fD_OlIZjVwLfRYhz__RSKNWKt
TMqcIjKjKdWLM7zVl5kar31etpNSAb9wZyr4gNeM9v-QmUkkq3zImk7CNECLjvHZZ6By7bnsI-dIfVtWpMpw-wAHqYNBgl63Xfuk6odzJDUbVF3lr73HI45f
_L3RF7HlLy558oM-INKLc1t9BjNhp7i_TJPTTKywSa-ym9PYVDQvTFlgxhJWiC0vp7jTUKGQ3mpXx5f-pqoTjDbbwZGLfhDpK_FeJDVThyp4NI7lMbuwpX9T
miUFk0Q7IA578HbqM1NpI9ceyO-K48PPWluCTkRDFdU5yUmLPPmbgHVmR4OCuLzNrwRvrnrsxeUTpCRBH8t_8BGdpVQHYc4gebHzBxxi3ZkRVKV3sBl4LEWG
ANcoJReKqwIo-_qVFql_ugmfO4P8fRq5qusYisrIW_zG1Sx5MV7J0zDrts6FJ2g_LqDfzeoKOaqyibPxuijcaShWe8yJpB4uvycQU6InF_kElvfE3z_PoIjI
ocIFwsfyTWAKZ9hKQDNH3ItC4oqKgAta4YcIzWKlrWF8Tl3OJJeoiNr-fDZZJbnUeC4cYlQcCfCsA_ZpyzwooXighOjrSb2JA8Zf_tBconxnp5LpmRHfLh4U
SXMZH8U6hkpz6r-SnyqWTlnraOqrBlRNQ69_Hg4dxFEtb75YY2xBkgvQmWHLyq33WQ7PKatjP8N9p8QDTL5TZEOwDdGHSWksNSkhM0D3P_qVgfWE3KD3Kwfn
72dy26XaHcSLEzZ5DdHKkfGmPOyNszBujsBgoeiqCtAbqIeYRII-4nt7WooINwoXSsR3q9HqKTMpKSCN6VqeM7smedUekjzSbS_rTLKTeFATw6YqwRrfNIG7
7HWtBa9Ywle_wUcai43HJFNC6NRYMPLrxTf1RLI-4zaHOxFQ1JhLXNPj1xLH-MYn8yQMCIfquvAOUr0LQRmYlz3NZ6xvHTdYxA1TSdudwggVdy8xSsPToEAq
GNbKZ453CpNkmvXcMOHphGtAesO3yDljkS_-qZafrzgWAYTted7479-haAwrGNdKWxlZ_EsfAEbQ6vH7BKStneqGWMc0Sb4Jd5_n7LlU1hKbH2UY8uQFb34e
ZpeVWmP7rzgWjeGOSic8uIF51kLBjKwVQFPphGtA7sfWNulWNKk0TbGkMhhcweHfW_AeOBzCvukJ1rNXEr5NyIXE6vH7hVFdeF1sRGVbKSFqXRA3QmbG5Q4w
KTViwzeEoXygc3VlUDVoe2t99wXv-bBrN4mUL4B8UemwVmiQJYvEtheHo4QfqczLrdEBamVDG3eirIhwfUHar_AW1GY77rJNRxK8wzgpGHi0KLKfCaQLtz39
LmXykW1eZvEDbNIVGwGme14egfe05BhG_36xD1zsewmg0NPN8kHHd5rBdb0Fkb5ybYeYUrVe7YaTi-4Ptx_iHa6q042Gno6oX-hlsd--c2ZZsGWGJS3MbIgI
KAZ-hjKqTSrbt8rGDG1RDyf0g4If-hlsnrKPTTYDIWEmpKWHG4cLA5LVrrgBLPH1DqePG0k8M_kLYaYKgYEcHdiXpeDk584W4K6qFRjl00Z_-aNAFBwBDBlH
8qGJqBG0oA_G8L1T8cM8QKTDt1fH0Qf60FL9tmXIjqYnPKTDtgAb0La24AIlRmIgIwJOiajr6nPK1OWDcsVR1bpo7qjL8LnRnguTHqt3DkS6XFAUxHDGdho5
ZXf_rzgb6l3UO0A0ziAFMwDAX7yT8kNpKfKSq5uUHf0-CKK024tLyY_lMZvInhAdmlQesef-VXlsDW6BSLT8IBb1w7kX6ObQzldwA6S10Z4LkXVdqLJuG9CE
-kOM08YqV_b88PIrAm68UyxS6pFg2QbwOgGmfPfUP2eHwDYjGrEeuboSuwYfeVR3xIsuTMg2r2DIZgF66Wl3gpMrJcsWUbnyyHfFXKWLY2_GNgJvowcGlq9W
NMjFXTsf8c63Qm3YgqZ3O2hqZnI-LCksnEG-ukEV_szSG52OVAGGKs7TyhDjS3KyCpRRZKcSjvJJeaPUpJU_GDDh9HzTTf_lMfpCDxuhh42G3RGye2l6KID_
CrBugR1ieEs1bpgeWUfnyVLdegRWTJTODI281Y343cgZyblABb8y_2iHg0_GfWce5K1A7NI8wXyf_5GODz02v0IWTb1BGhkMY1GgQafxWWeG0X2qWmvHFIBb
_AZPJbItpUqGLBalEWdHfTeYsglZjWz0kKZnL-obMjgMeL49K9SjXL_W100A0KfiAQwb-WXH8K29I75Gs9LgKWAKtrAyfa8fbG3b8yLpAYH0YOilDw7oe7oa
-4-51AZhbi9VG12Wxf72Nq2CvH0f7gLwB8SjnM4g9429IF5N5WgKtrByItKiXqZnZXfR3bkAzrHeoo5IlAT2MqIaN2jgY2tbMgNg42dkKw4fOakvLjGGaNAj
KYKYvLfJeVM6_mqq_rIgHAHSgrI9IBbMr12HSgsfa8YKQqs5HAHSAshiIBbXgH9RohMcGY9IhXKrFL9kBTI_4Id_1G
}

sprite $image183 [117x85/16z] {
lPQ7RYGn3uFNSXMbVV_7_Sli1CGQYU1JodUNe9knADBpoD9NVVmnTK4nvIybPGAg2XtbhoJBKEWBQFiRpQPGWbN_nimtW2b_OEOEj9TVDBFh9ldxrhPziabh
yvFT0ORyV4n2oTlQdzMacH5OxSTZ4eD4V99cKdBXjhRyKEV5t58T-25hsv6PizA5e_ZapIItI9bWCoQHSM8cLE7pyM90BzAFNZypioiKZaBLV3Es5KlIFLbG
DRi7Ef5jHiOafj5AtAf54Jnw-PYGGIiLzuGhKezUEp9JeUhWKDNcFk1pQ-kXcMzM5lqVLhUh1jPcpEpbutguLnsgM8-BXNzwz4eO4-3Zb_1qwxmg2cEpFNhP
c60rAT8M5CgTWT99rDSnE7_qP2AsyQLK5jGMhwUy7jedfZ8-YKy3TERZpJqv4DqUlVFE0vSJxVERRkiRM7iS4x_El0RIvMDbCNbfoBt9GTB-CIQOl8UxZYAs
tNzjxV2bjUUTfy8p5UPkKCNWHS7qV0rqb2qc9uia-WBWNrADxdPe2BJRaIQFtCDl6F8enkrwA3G6RdPYA8_SvmTpLu0RDKn3OC-d_GySRH5fs8u1jqXCG_ud
UOaUoR9FMEaRGnwF0eII_gHeB7ilAM7yjpbtjT3CIvAY1fniqRvBkwx5PjuOGRX59CvYF5cAnh9S4XA4CPuiHMFPkrCt5fAI52K8juYqSr6QIT4TH5j49X9c
KZIIvHRj28ud6ueI15l4s1nFDXP5LwhkNRIpCfEbA6brkonM7r-mS3pPM7G836-oyAz0KlBf_gRfgwZtYg0Pap4X_dnslCcgJAjbEY-RmZoGjFuemzo831Nf
ZWaFP3DctlYyOY_BIEjJQZCjJPEtXKUJPHYg-eUfexOwn6OPCsTjQAQz5Ss7jRv4cehsianwO6t6JDzBlCoNjIeoJ6OJ-12uOfVDJtPzqk6oBjLQbhSgpGmo
LQhw9fkC2UhZKnhS31q-H8QRzLfBXIxVhCt5v4jUyV5PH5_-LlLP1gtDnoIWpElqMg_V8cesfIodR38cCPU9M6PeSejUizvaysO6rfgr8glsIxIPw_Re7SU4
PeRSpRZQl58pfGjy59b6sNYoP3CpWCq86Jvboh8gx0h3uMIrFivXCtQnMLORAfNEKjRyeFCEOJEYpLbqj27zGvIgEEeyScujPj4bKjTBb23kFCb8qjgXgDAn
Ytek9kVMjgBOHUsuyvBMQZSz4sNdvU6ZfoKKZJilRsqecez9t8mxfp79qyrju-3Ju8Ui9Pw8IJ8-nFCnoLlhYPYacv6YYPZaa4dHj9bvQvsV1WbopMX-QURC
p5lxvAV1to3BFDrvUHhc8yj_0G
}

