sprite $image423 [180x260/16z] {
rDhNijim38JXz0WB7k7zdpPrquJZO30soVL_xV8DPk-aaEp3yQrugWxsN6A6U8e-aylEqCxCZbm8TnhDronKIsBvMLiYgmy4IIolfhXAIanpsMSbCT5rcvL_
UQNLbkghJS2hUUhJYbfgyvZR1-jNY7sc6LRLLyDf5kAoss8fSwqsPp4bn-FLyEdc-zL9lC3yGBMvhpB3xerY1iCyCzX3rFWj_XvccSCVfGQSsPyYv4wTlJmo
GuII6g3Eu2o9VGJREX1o6RqNCVCnHimCILrmS_mcmnWqBxbruQsu52ym_rIn7ZVdOuKPj86rk5cynWmImVfS1d9Nc2_ghfV1nqBpLTtZCehNcQackicbUBMP
QAf9JTnYo8lDZ09tJzPwoElDpFfHlCtSHuF4NUQ-6Zu4p2qrnPlDh26MCQCnP0KpAuUiPQxL54kPMJ6BpMOAApHdeM8cg5HJh60sLgWftcrEhjjeq2DWfgew
DNp8c8qLQee5pAUnIasAWDbOgTQvih4QxPgxo3NDx2NcTLXPoyosFuzlcsCpkMz-4NWktpJ7p60Jp26mYsJM9lVDeKU6xnGVNN5j3i4ZqwnF1glC8KC6gymX
J8Rl4PztaE5Ro9-DbKL4PQPOvSq_nFVWoRnQ78qZisHUJJvQHsOtpQ5qvRZqgZcKo8XKDeSKELxDdMP1yX6tefbY8NByfzD_caEOd7FuS2to4JgH_BMTkygj
80XY01XEQsdkVzlyXZdEzAfyWfBb1uiV9U10NlkHnoj1HZuc8z-qAtaCvEy5-UX77jEb-f77MSZ8oDMFF90dMCPeKpCoyjAFF90ZIVp5HruQBWCvadEHxoSb
bsKaSWJ8kPgheHavORvHSy0S8gkvd_b2pGbpfG1gxcPkI5xKR1e1CdFv139_xLIecfdL_BKm7sfc_aUo7q5cSoxJYAJXwQCRqqYQVTCncpEpEJCpE-tCpEmN
nJIOcM_KpCoS9VSt7_tCvioyk77HD9XJySlDxAkEsPoPcNtLvLFcpCpCx6iZ46PcNnjvivTMU3K1CxEl3MPcvcfeNiuo3MPcPkRbwsPlb_MgLcPcvW2PcPcP
cNdUh8tCJtFVpVnoBkkqm0S
}

