sprite $image346 [271x347/16z] {
xDQr5KH13CNG_Ca-l_zgbvaPTQE9DUJXRIH9aYH9aaHImvp853rPghA4COgi68JiA6DCUK0wQmOXHs6CBTIVVgxnW3HPCGYvK7bFjj3UaoruJxPXZ7zuGYgt
eZqQMp36DhmdlpctZzahbnjcSo26tJ-9st-t-xy3w9hOiGSGIo26cl_qB46qaq2LaSmk1ZsBaNiQWURBg10_6_7eqLYFQ2U19dPI8TRp9UHs4eZA2DHE4lKq
0hao0jtyN2i4FQTnEmdaoWXqsNEja91nqu1KXc3gSrsF37Gq_c8ugUCw6IyT7GrpKWUwKCPBHpjvqUSQzBa6xIHe9q4xEQE3Ipj9EXf1E_cw3ck836WdGPzh
qD48-bo3ZaRGJhwY0msK0Uqaw7FThSEZEadQIT1EWZxNRJgOs4dIqTYZGqCxIVfSWtOIzBa6VQv1dslGqGZQoJ8TcYnZlGvhQ2VhTLZ2aiO_r-IJkv0aJUya
-MX1TOKGiuuF1_Iy4B6IjqAvHuZCSHrwWeC-31VekEH035Vea7HUYCn5EgIZnSXmbOwZ4sAuJCV12H5Sf-FOXCXSf-DSCOQBTVYxGWHtwZWn8JAtwlZ-XCWm
GyStYZ6CqU7TGWHJTEmlHcQS3ZsxX1YcwDW_8OAXEhnUYCnO7Uidn31Ln_fY35Drh2z6vduTLh3jGcIuKaUYODlJDKpGuUTvjFr014DqIE5ZnuJ83DAXvtcq
SK8CetHO7nIZvPsSVxJULOpCG1sIjA4O6QRgM3yXXgawra-8p6WTqiAdAyDa7LvQZ66s3lmIyaOnAKGmNWUyzNHJI7GoN0TsFDst9YHapDQ1FvmGXutfiRmi
lFTqVx1l9rfoWpWKXdym1eEapFi_xMoSKuhfybIsSdbmbAttvOkbAxhTOXDnw6CG_k88KPk8GzkZVcbl5xDvECRBNduoT4LjDWxTWUZFT8oONOQZBVgEkt_S
wF-9GrVuSnpINeoGYtDiWJ_AeSSZvFeSii0VudWzGgxF4VdZ7CSX8tfn3k4T7CUXUt6ExMqSUW1oQOxq1WwlWn5oMGxbhHpI3aR8HJag4Dx3SGpY3rsD8qDS
tigX1slg9JaYvFTo78yGlHo70Etj7CSZv68S1OAUmA478-HY70cIdS1nUDAz58S2spaS8uXwnro6em9o4iVn2Dbng9p4KPC-YraxY-DuX3Y7Yfp38GdgivWz
a-DuXAY8MN_e10uj0Ckpc3sRGzh1234zw_iiBGA0F8dPCpcEGLfhtUG4ZXLwhKzYzdIEuwE_dfCi4J-tZZ5xAeUNWxYHsTaSPOnP_HI7Z1oYft84W3Zqq68V
ur3vA4S6e0un-maEhmzo201fYDdFS7XzZ4FJaBK5WdsQGpx6qO3U7hqMM3_FeVeXZlvf1nrYzaCSNYTmgEXNZWqwWSVi3JXqIm2BZ1pgMUinEpc7hD0hoC1X
1O3MdnYWpCwXArxBoA5urWeWatDi0V2IWSCwbdZCpimXYNtLaSEprcDsLeuM00Yvjj8Vt4OEpre5wbKv_joT2R7gVsdy-BhZg9sfFw3EGPwC8mDGr7gb7hGZ
XmQ0nMEsS_ZBJiAHXrMZT9Y1mxCsuXTFsipcuiZU74CD70h0wZ7hDG_7vZdoWgDdBGMYpShHNECbXq2lTLOEZHwgBpbieLUTbQC0g_qeHwMNpiQXxJ4TWxxc
s3r6iiauQYoFLCbVg5IFE0e0srmSag0zDYlPKTGr0h4yvz00IxEfEEfkxmxVM_X1BZ_bi1msixauLc3f3u5pj3M0bppbKBNPE1OWzuSUdxUKoBwsWSDhBWxr
pI40n5BM26Fbct0q_mHvKh7JiDw4e_YNn0Fx2cjLCmbtkZeIiFg3k4LJ1xlDx8Z-kJR7I5NtIIptu500sNtvFAHDnpD_TBpOR5wE2aJ7gLiLVRAOb0T7KPk9
e-rFhFd56NPOtND_O1OENK76IRhP_wfj09k8Omj-uNkuokkBuoGEEPD35iQRt0G8BuEus8mSAxratmdfrPQsw9GSaLvvI8qN6eZDoA70s2qBq5veL9kIem8h
W0Fei6IgZ344nURao824NRSqOFb-rcRpQl7tDBvTcoD2wECqU3E02nHm6ysuneGS2YIhksv9-CEou8D2_RwE4pc-wNaS5IYc0M3r2mRrp0N2fgPrxHYXsRGS
kLy9A_wz9GLlZyPOIUstwbeSkl-_NRf2mtkYWeyEPL_16sM6gwC6duj-9Uow9TDXV91uPRKvE7mmwfVHORjksR-CuBMwwmmScxV4VdJikYL0_7h3824xnZmS
7Y1-9UowHVg_NbfIIgMfsMGSEXvEF4IyMxQZnM8w3bk6etpp46dWcIjNuZ1v5yTuwqN1HqcWsomGR7uEZuaqZWxlbgLlxNDp-1Jy-lDPSRz_QWEskt0K0Deu
EZnRQddlwB1_N8b302VmqU5t5gyGx2uS5l5ijGJeBcP84T9zE38y37JOFmCGWN8R3b_6VVySgA3TXyCY3uGoX4YZbzw88_kUdiOG2VXakGb7ypqzu27YLEIx
SFWbK7nqZ5H5RyMn0YHxUdGD936x5KS52FhqwBfLivjnQA27QNonVyxFuTsI_UXwSuxQqxG2nVvoA02QWVQNewzVjDG7wb-E3Q04I7Od3ZlWK805ABVdy6u1
sh_QEm_TMa8WXggzjcDs_lzhNoLbfDKH-qAA2LObKJqN3pQtxCPHdegnSNItzEgwSVGBzVSP7MVEm27DnV4DFgdnCRO6usYQYYFWaneV10RZQD947Erh6FY4
S3I5vk5my0cRvJWENnoPKt74yLUcECwSXgFoE49EE1Z6E0u0ueOZSpQEBWB2EFnWy2Cb9UR1EEJd4yRHcdY4C0x7hS4ucj0nZCCG1kDG9m0y08UVJnX758-0
Om273mp6KH30eVjnSEHCYN97nJE8mmq6u-WYnp0EHv_mAAq8m360msjhSEuGZX36uGc3SmUE4CPXwHCsot7m224Slbk3SmSuXd3OmM0S8PgYVGKuB67mGGi8
2Yl0OJ0q20VpkF8FuB3Q6en3GiSyMm4EDnYSEy0nTIN0OUKJpXt3ZW4SPZ0uTwWYuDpUSKWHSlL9Skue2rg5dZ-jMBum-BxZnahHcZeaAvym3WwclEgKvBWr
nkyxnXppH4LsC1Y7gDvJI3j2JI5Fdt3kkAxtp4FzeFM3mJXAy81ZjlnFa3iCV48uL5ztTWmy1yq41kCGrFjh7f0xl6YaNbJl3yWT1aE3SJ0FlXxJCJLtP7uK
77Vh_V5CKiXqQ_1zHo22kbqWTvZ0u4PxMU71CP0xJ7p2kKCtwttytHg0mm06tNUCr_iItXGXFvymZhXTxsVbZdntIJFgVKI74I436A0cglV3Xsw3-mu36B11
_hFUTs8o61gianpJDSG3SWShFvRQ1P3nUW-vmmx6k6Du5UsF8kJi4mR2zNvExiWk2o1Sxo5tUCBW4J9Uxo5tMC7W5CBTjiBgVvGt3NRCQBtlqWqS2V8-TBi2
JXQ6uJb2-49P3N3GuMeuGhZU_-KqdZlIJk2Ogvft9tUafMuSkf0xV65misF73EUE15cdaEgODfGxqbmIyBYREt81WMCktcS176SkeJOmGY1t00nl87peSkv8
q8g7hkZp7GbQS8HmxZXpEN6HmToHe8M0L1ubTm2CnHq3kGDyiYeGpXq9Mjyn_Q156Ei3wOufkODXh3z2ehNdECuahG-a5HpvoNHAbpWa4OprHqZ5aU2Jp-IO
Ca0ta8sZZ92DeuoGWcCxfj3OG9worzOfFTyQMnDtnjRMrjRMrjRMrjRMrjOl
}

