sprite $image407 [260x173/16z] {
xDg5SSL060FXS6uLkFwxpN0Ui-4_wIjXHsRtEOcBz35nFRtrOOXxg5U7U0JF0UpIbs-1JRu1DhMI1Kp7mCIQmGQgNoyRO1w1sIG12DipmQOtrn5iakqADYN1
oYAm366V050IhERgq5XIPW1A0aY21ID8hCPo9q3J1bIWwQA0AAR0qq2f2oUbFHbFO9DpWFiVAnY9yDt0fXG0b0JNJ86H9G6G0fUS5OHx1E7XWWF1U0d2Hn8S
My8NLfG4XoByOkUtxy1G4e3wfeQbp02K1EZ_jFY9BVSPRFu0Benb1g2DEqJl8OWqm9lI0FxOjGyTHq8O3C3O5DjNt_zfhyp-Zgp5AL9GZkJoNrtCHE4JJB-V
u6qW_PGnHFEwb-UweYYXRHmj-j35OFUabnZYzccSzLEzYyM85q8R7otoo8dmOvK1GZqtyF1834e_Ow3zGdILWQqpG4Xo0q_LsO3E68no8MDB0wJd1XuQaq7f
Js_G_gGoJIE20N_Kooao6PHL1ezFZpDPEuMl5mmQwitBf9D1Fs_0TGfjQ82epttE3Co4KQ-J0Uav0unLBQHjQO0uGayDJ1r1em4wNJHGzWChDzdRm318pWrC
uuXXm1mcGcQW3HjsRCEyjO5Wa9eRs81HD1ZUApUefVIFhg9esjl0LyEO3122KJ3uw4QQ6I3IZowanpAWjhU1XCcU6JGO1GFyMyyO46R_qUUejyqDpBziD9WN
Guy6w2UvmQ1u_dLKTpTW7rXke9c1ebzg862Z1WUoPpSWj4K3TDJS06qDcvRwcWQAmQK6w3Ty7Sds1dJPGBAruBjAJGtmEGv4QY-uJmmJ8JVmCGzytEO6uxPZ
emI3q2wv0Q6VkC7BdIE5_KJLp02kmvglXQS-L-x9kNAiZCm0RYo4TVGIrqnzCi14O9eDUa5WGRgr0GZAo0sKKDVPmAV8PD33_83WMeClAmsKhzn3SO9cYG60
qkk5QhtmqRcklsRwkSv06nL4CWEfNYRD3Apd1lXvj6FBeuctCoYuPthhFLKIImsCpXbq_tytBQLAtS3WldlhOcSCUchGIZrM2hfMCLky5hxyusSiqS0eCv1n
_9TFpSiDVguru2lFsceGcWr6Qk2zgTdU1l6PQcv0LBkQvGO8fmO8phkO_LHfKUvx7qd7AIAgKrscUhAv91jOOX3Sbnfi_I9ARg05aOKluyXp6HWjcmOms7iY
gA-B62RYsdNnQvfcxpTLvMtmFx-dYTt1x_RkmxYn60O2w9spLpF_zT-j2t1KbhX01UIR9J4HW8a1ne3N8M0t1ko604E0CS0GuDyGO0pmDWJO3G4CmVfF8j3D
43D4qBxrkbmAPhBgHljiLQWEGcWtY7A3X7Q3-gdh0Sr1GBL1e1aXw3Pmsjgwhmyqtnt0490nO0ZkuLlSPbVP6_K8jx2rhsIXPyf300m1syrsXEuanELh2604
Rgf5W6Q7tDdA-sIn3Enl46nPKi2-1txDQW8Sz6vN0i3XHqwM0237dVdf7ll0_Z7mMoN97W1tQB3dJlbyEQW3t2b1h5_RpmGQgZu4g0y1gGy1zI5WZmoqDOKt
gFuD68Ag6W4Z8FK2ddhR8O3s323j6M04607r0DG3i5mZ-
}

