sprite $image155 [274x195/16z] {
xDo7gGD140HHFCVK8kKVxJVopO6ydweG7hsZmsdvz8fLjLnbx1jg_4NaJiP_7BPGH9DeR2DIH9CGqIH5MAN9kX0OGnDM7KUfXXvPNnEYgENZAOxNpeH84wBp
7q_F1tDyA5FBWHmtgPuUsJSV529DYaWJ8as8xe8YoCoasdlCJPXQUXmt6SqzFl_85f4cFAuqgQOUsSVjf8ZS2P4x8TA4fpRUdgI8D25wXOaUa2Qbn_mxjgPt
1F6Sy6RLMtbeKaJlSavm8Al2H8_PJkh57ivaGUHCY9m9qLlF145c9dgiUk8r8N8cP5uJu4DDwWaUpcHmcDTaWkDr-uGbSYP4NXEErF57Po9o9aHUaq7aJFYc
HfZSuk5C0FOUpYGOSIOB8cS2D2FXiZz9SIPZdJC9aLNE94HMEPCGwM0opfb9YloIMnz8RaGX442T2SstxtzQspkiljGrhGFCG4LbyQgXg1eLatmdmZK-9dMk
IIIfH8QR215TSqcgvfcKC26HaIRSdRxYbSd4cBnqxfvdbYaaa29cvbb3K4wzIP6Z0dDCc4IBH8OAoeYO217FeznCc8mWOP7iGfNBuHb0mYBDWLfhzKRnd6To
oiW7HuiCCD4aB8BL5PPDCc5ukAlVj5btHiA0662YI4Z4VlweBGBu51DgAKd4liH3f03aDl5Rcp09YqJMGsGT9cO3bYoJi4W2BV81SpmRCqpUYWHGMsJr2px1
f4cq29uYM8lNYTbzJTw8E8dGwDpLX4bO97P6l4Nsw0mmaIAfH8f6vwucMgH3iaNgKwHP6kpE9hi9QiYFNbUveL3r5Aa39UvhKgL4-2033emTbC9zJQY1OX9_
DTcZqpIqJgJ9HJtu__-XPYW5qU_U8dJOQvEhWh08DyFt640YD3hIv9eUB48aEoOqEaNN2Q6fs_w27YooIRG9019PXPC9BcfIKaIGSCS1D8OyxBN9nJnOX4Xa
J2pxm_AmtsxNCc4F5c4Ith3wEbbGe_ElNVlGZcE5mG0icf249hp_szx3f9czAwz2oWvU_-az_euAKohhd0qyJ94HNMaTgPkkOdM8T7tGEkne7Th3HDKXCjAc
NtdGEjey8tOB3rkagpuqcIvr3dqyJZO0SOdOhTDkhecFH-Da0mzRnAZugGYajMPS4rkRU0CFIwJh7BjrLB-9J7ViBrucgZuHgqZirg7xhKCNdx3g5PbZaSmc
x6cTQv6eBeWO9iOuqT4kQfnEhbOcggiY8uTjCXt6xjvEeaikObqJcSl4kOdlNHCNl5QPgAw9-5l7FjWt7NMK8U5roaHrGMJ1nBmcFaKWPBn8cUYwYD-4wspo
zfhu54arG2nNA1FL1P454c6hTRw975hWJUiygqnKrqLi4k_1VXOv3aa06PzP9gfB8jqXujh4iyW8HmW5dpPDT4caln-3qJpOpoA78a0ipoaJNGLP834tSMkJ
o4ZB0Ea9PQ9hwOwewk4_sBT3soJoRPpyupBv6nRhctWM6Q40njdaCY3I5zAyryIpo8W0MdVhB-7H-cASusI8H4F4A9Dz6iPlKgTaICqIkIsJVK7yjvE6240r
H8mosTB3tpf31DWGCSfaHm-_2KO084F4sCDxUlWtSGc0XeZHEVySv4l_atayJZ27t8v3Svj4x3BPeq3i78xMIO2g0AWyYLXbihE7Vvm4181GRaM8oJYkFUE8
-Y_72PO0Pt3s626ZSpOj47-PvF-9yFUGyVhQfXv-a_HM15FwIS96vspguJ_Ob_XJ944CYHnbiiC0MT_4jGmH4k4Qid21p9D9qpcx58WTry4-H1JXyPLGWZAr
3kkSVJtyumG10XMMd8M6GepJEFdLpj5d7r5_VnENcECHYs2gepw4SHedHkViLo3-SLBI8KS4gf6-5ejm3jCu4PspfuU_TJ0aEIXa2eovG1OMfXJmfuanJ7Rp
y9ia2CUXXO556499fq9uCqx8DKmsyF2Ean2EL0k7AY9KCsGUDkNDE76SrfRkAb-KfDNG8WIEA8E0Gaf08i8PYacoKyFO8gO9HO1SKoP8pC9S86CTE36ITJBP
fc7iDBLDX11hJXo0yhbiC0AThHDvH0O9wPHD2yJ_e9Wh1gPS8Nuhav8AY-GoG8R8BSdc7YFd9EXYaGYdB281CD3e4mfGYJcmo10nINRmi2FlR-AOHtyW92OH
GS2GEDOXGlKC6o8RR9YrjSCne8YaM60uC4Ue2T-8r3j_RCS2yPi8XaWYKY5MP6PA58QDJ6-jhOlqAyVQEXaoYnHCW2mY37oAa2cocuUTPhOEb640AIUM2eE5
M8GDaSMRP5kDanf6gn0bGC4emW52OU7xxtfkN21-4oaXaGY58ZcB843XB4Bh8dsRYDKwvpXXaOWY1GisG65JnDym6xSEdPkOH_-KejeWiD2QI3UodGc6Y1cO
Qu4e1ySgR8duFNOV9m3fwpidg4tBYaZVD5-iqmcVExV0c2DveMlwlcdlFiN8aG2AiMjszbY_FLqYn5eDaPqzrXyK8-AlYRI-SVmlJ_j5-aU9sYQMYENn2YQ6
YE7n2YR2f8Q8CK1Ue4uUY_IF6RsDLwIFl8Y9HqJwXuxUGT5tHVe7ZngnHFgKJv7-2laLaVuQSOlqrygNHoBzzVA-I7_9F1RvDFaKwOSXGlrreoF7ZKX_xQXE
3TIQz3EVUTwTaFy
}

