sprite $image408 [260x173/16z] {
xDP5eiCm40JHS5IzaEv_si3gGvWKUNhg087djgtMhvN4FGcrW0dnQ94aU2ML0DV_DAj15DwM5602ZclW8mMOWCyO-70rW43qMwAA7Yd8Wo3eqOcUjH6hO8z0
xr8097i2G4a0IeA14CJtoXaCWw0qAE2C82HEydWiLiGu3R1yBuCj4qZqU06QIY2cc0mMqEbf8IQVwF0I2Bm6YK3fXQU0hq81TmIYrkvDn2q9xbGWV3K9aEm9
02K1a0INbo2mHy2gsawhcDLE4_O869O4a0P04e2I0DBWzn24_H0gs0y1vvunMCwFROCXy53psR4DzrNeMHdFeAmNitu8Xs-R5nvlUo3GXmmE08Sw6BpwRGS3
FcGmdtKnUFtRqW0sQO0QU_RC0ykP50R2W2Gavlu7tiMogrt_Ow9pg9TQ0ONFsNqM1k6zTrzDjSeZ9yN-zIoJkSRfn4zYO6rgZ93qLikScEwoKviwmEbjdzVo
F79RZ64rwwR3PdOc2x4DhINz6fzqkoe3BLF32YJvG1LMPeUKJIr6AigKHylCWqEZyVaKUW7vgjilzN4w0um52CkfefAlEZ6GmWo4iZCN7I4xYG5qEWEMVpPL
Awnwp40BCO105iy2LhyV1iswrMtSqF-rD-UbR-DRHFHCLJ20c87sBaTa4HAFy8pKHRUu2OFSfc6grJjr1lTcIuCOL3KJJySMxcbOziCreFP5jrima8nuMh6S
gjF4lbcnUfESSk12YqoaIUHE6FX8iSLJ2Jr7CgXO6SyGEB2SmG97Yjm7WygXDODA3-4Gc86N4pFeU08XLNbFHxlRCy3uRSrWMwpAGHNmUEND4Sm0u8f0E7Xx
1aOFxfg1bvM2LoPS_6YtPBoGFG-3yLS6-YWCtWomM3CMhVnJ1ceaVnW60vkmGESd37IvvwCmm3V3anXqj7ii1avVQFGK1eYGkDjzCS2NN6p63wAB_PO1IY9L
6u-bzyG0mQBktJPJTc6tcWF_Ze6NZ5dCl2v7QO9kPlV3m0iaE3XLy-gt3D0muuNJUe7qNXZWcOiDlCB-4mEqWFXNs0aCFYx682eOf2s5PBzdmFyamS-8vU8C
MfrA1eRhHCAtfB4qfkg2GQluWTIK32Xs7Tgs6yT3jngjnrXqk_oVwp55rnoYt6vgvh4vt4pL-lBG3ugYgbftygww_TVUNU2y4GH160rdKfRctV-s4OOvFyow
-Zk1_TJBzES6amyJOs0Cmcuts6OGg1-4W7Q3GG2y7mFAjmfpz_xSk-vpQmXQ4PQlcZ50Xg1m568G_B0C0Sgs2UMZu5Tb2B1IJu0z1608G9A2VQF2UGZj2Fwf
8U1zmSvXpI34lvTw0KQ0TNc1c_-kUmI04RWiGh9GRU1XsotxGjVVHOX7xI86O-2H6m8C0UbU6G13W0p1oGYUhWm1XW0P0lOGu4sz04XEF4XkN2ZYZ8xvGEVv
1dbmByUKl_p1kJi1_cMv_M-0zrpDO3_eXcKvhFpFsEPXBXYSR-0txUGF__vsPhyN-F_zZPkZEs0VvdI38Q3TOBKJ9BGRQ6a4xEOD8g1-25ZjCu3s6K2-5tX3
-HX4Ey4RxGGA6m6f5s04FXDihQLy171t01y1
}

