sprite $image59 [260x166/16z] {
xDO5hWGn40DHmKBiI9Fxd_OpUBNCKFsEK6fdPjo99NcGDUlRmD8_OmkavS2nrd2F876FWFWiDEt0dK6g0f8CA82EeC0Sn4o1UGiwbga5aXlWZu3qBEXqnXP8
niuWOOyW-TaBi2jq1UGWhC2ieCipjq2g0izp2vEk2lWMhZDs1icLG58L-5G591du5AwRZOSoqrrCs1aaxWnI5VXK2IHZ2oJVkG2xWXuAzmXI5P3aEnG0LvZf
WJNWKxWEEuDaR87Ki3D8LU0JTWR9bK0ITWR9t0Bfih-5u5lGqskuft2TDSxGz2BCBP203y6wAd3y8BfU4_O8KXNuTCJNW5n103wY0B629NY4BfQnPb9WteAG
nWgxAlHkCMK3R8LPDkYsaAPe01z4xtulrzoIvDX183fTaX0afE_-TtkZgyOc_28SvMTB-JU_9yW3gfwc6rF0nU1n23Ok19uCUaIJdGlnP43wSSnjAU1YG1aY
jYK5EDrn62b6Vupzj00FqXtT9yH8VppcPXGGvCM0OSt8QC38FRaB0VAJ3pIYatRqNRG09pynQ235V5eZELlReX3mO39m6n5Yf1rEgWOss9C8PlmPZEFqWMce
alR8ytbz0kJxgsasC3f3kv8nL4TgOTaQ98F_uEuElUGuEnX2paS-8XOTWcJmJ9mK-X6aAYQ4f1nPY7K998FtGcWBgZAq1odcrbOh19pyDeEa01cd3wQ566E-
NQE0DKMG33w7qBipX3w7aNnCs38K46J58BLWCqB86CEV3EnwIJdM850po5cmTlb0DHxJsfZJay828YWO90N828hHvzkqGRRswbhmu7VpuNC0gGMy--1a4Fsr
2u7uuHdul127n4S67818KbYd1l5D04bXpZXzC9q3z7Qyf1RWrH1K-N2Tp_tfWr3j8Fqu9FVaeZN8vFdSBXyq3NgFw2-c1SIj6cJyZ9u-q0dlfBU7P24Mga5D
0NsI0s7IISgSyYfxybSG-FYgLiSuVQ3NqN2qrC9A8gWB8GyZlViqiKkEgOK5pi8VBOJHEuccP4XuopsvbWZgFNdvG3H2I1nvFgzLWxeGrqzoeIeaXumin5Bx
i2w4UCWf1f03n2Cfh2A2Ela9FWJJ1qYygP_1OYAeAMWpXZ2qWOoF31nOJ0Jr-MomomSMoS0ToucWBaHpSW3psOKC5gj1JS56n01f5mFBGgnLW_fyHZ_I1nF-
joaW-ESGP26wdmpWdmMhxSEQWkBfWtbD0P0KrX91VJvRUrFNC8MxmxCGgucW_k9ehcJCquh90Qk9eBuMN8DKdVQE92ciLODQ2qOgmYPI2d-Ambyda8t011bZ
-cTo15OJGNq-Qv2ZYIM3P_0F_73o1mi1KYAa5zV24YAe2w4z6798GM656jJdympIPEfqLyy0I-t3UXHWGPja5vTXdi5QDQWfcDaaQMunF-i4rjg7zVciCqu6
fC_F8E2rFfFS3znXVZ487L8KuZNUX_Ure3wKeU9IR8W5H51IS3St5P_klv02olye-hVYPqIIGKB0EXT1dV0pmwPxGM4H4TGlAUcERr1ORH_M5E205nJMh456
_REWACHoDSXypW2V_xdGFgpZHR1E3UvJ05xhCBwV3oM5bKHmln3tHR0UXViYM48BQnF8H4NXPWrMBWHk45Y2meqNye9QkB4FrzF23H4iM8Wj2DGKQWHxK8Y2
m2uGeY2m2uKe2En28OeNyYuGeXY2NIX4GM0N2b7KO1SAKGp1BX2Y8B0BXIW8x48X4i6s5289R0iXai2s5EBl8VWV
}

