sprite $image18 [236x176/16z] {
vDhfTk8w3C1nURUMS-Rzt_P2RaKNS8A5F4DFVj_RvD-An27-ine-wy_lXMOdgFnbnUZjB9qtP-bK9-bKPmbL9mbL9mbLvmXL9mbL9obLvoXLvmXLvoXLxrpQ
Qhwe3TsyPsdF0Mv2wUZa_L9RX1yIlbSjUYdmG7sZMdIJ0Tux5jqq6EZu5hNeAC50GKVcKbSmaWGT-QRwjn9wSaprds5XTELMwdzjOkzMDAGwg_1G5o7qjYQr
vHmlScxJiPegkAVNdBOZb8RFyq-j0Rv85VTHXXyoo_w_jNm_GdEEVM4emq4jSujm4nlB1SqijMBpZ7tjmffm5ua8RhaPPSCu5bvQKwvBLHdt4Kk2Ywgb4wd6
MFy1LWsFnFzRcIQV5LJtYNLO6cHwifLmNu21IXwn-Bm80qcSMc4a2xuUYpwjjBoLNezrUFA-Hh1FQuA1BeIlnleyjuXNQuF7eWZXYx4-QtaIhnd6Ud04UopE
wX4UIEXrRMhXyUL01ySUY_EuFpuRXzRHNp9skS1bhMCiLD8jiH26fzPEwOdMh7-tNcxHgPAkjLwAHHDYFJRBfZtp390FM-ld0z-jJZuGpdD8rLp5n99rsEoj
-YnKzNT-OaBqQBMZpKSw9HraOsk2JTeQwUu8hyQY8nAzP1LBQuPDG1rU7zwjYhZ29ZJyhhUIKmnm4LBAfVN15nrDIzrRqHkpNaSxgfOVtqLokxlFPBq8BOX5
ToJuxMDR4-n8zTjzXhJKqvfKhUtwC80vm86GKUU-w_WkYSKrc2lCqliC-bkOgX_RALdlCokiRKNY01EYZkzlR6q1fWHYN6PnAanhkCvKQsybNvHcI7MExQtc
N5jRqzg-RKtA7Gy5C0Yuw-vk7KjtQnrlJUguBuD9mGDv-aoqTTtM930oNEug_jkjIGMC2irV0-g_tPeKmIY8OLZQycqTAO-1MIrvP7mcX3uYl3yvKoijdk6G
ni0iZSNnKfhHHOS1bh48Lh831hh8ygr9OnMCiknemvzXD73QcjJ128Ldxt_5yDJhkZKfWqaIeRap2UYKgfXRWfkaMvFSr_v08aTdKYCetJn4w8cstrWla6J3
AvxfkWW_SIROwbKdsH0w8nQbfPwncYhJPqBF1ipb4byHuLEw9PKcpaHFnT3gZYBCG4rTWXXNAZ2bh4n5alVu6b5LN8VNjVQaDuKCXr8VlDjpj6neD32YNFG8
Eq9X4U6isSjQ6LUeuSkIcUcQEtY3bHl95PDWr4bmfxTbVotgjUQARdT4h2KbZKmftzO2mlJrtLwew8-TB_BZ7G-Qgqz0IMwOwUxTNcpeRSNBehBp8fMOlxNU
hmMOzI_bFy8NI-upLKi7LwqaFBmBXXKVMtPPEBUBdpiUT7ndMXNTRmbhpM64NnpYNX9y2BbYrl7JqibMnLpqOzjB2lhbLkalZV26x9VRH_I3QcxLBM7tx9Si
-S1eaemx7ggs7cy9knVHX4GH6eHnAk6UfgtxY1nVPyWDuxmuyTNOeDNs_ZOO_wsA_DvdHKAVrkBuB2HVERocLEpK6c4WiUtUgjYlbNXrgv1bWkrJN654nASr
mK0MDawmmaamaBrQAmnqOUC4AtRwnuhRTJYDHbZOCC7-Knpfy1Ur0XSH6KsnQVPKHPbYn-TIZZuDDSriacgFrohymWGhdCIOxxys4XpBa-jRuXQ-7Q6A8TKf
LWHRILVwTGfFVeMQZux0lQHDwOP7K98HHaFjLpo_qaguYmP7iAVQOv7qR8vUhPYNVCI38vXJDNQLObf0ZzbJrySc697LgVPO_rPUdJhsjsTOP7dg6E4Argr9
_gdhOmrRa-nOvFrYovAZoGp60TzDKWbNf99C8lJ7qhwj_N79WLYcyQfteBrUwIcjIrqVwxyroNz-_UVOlZN9ZiMC2NyJal_AknFTHc4W0CC1NEAOIlF-Rxje
nCg_tEm1Op4J-Uzzzwid0NIufhOFalvhKSLfa3t6Lnm6sMjynJB8yQLCO3LemqgP0Fk1MjubsQtKbe-JCe7Lfer_G1N5dga4bzgjRFkmuILL7CuS7Su61LW3
D-gICe7Lm0qBPGAiWHiLoiHW1JSib8aDIszG9wd46hdmEZZjLl_rBN1seX9hN-0IXqbgY_KKKmbcT2l9vOmHo9xKEx1KxvMZGwRjFWfle1gmuPDni8BOA5Hj
8AgCGjL6eMe3KD4eL6qKgZO0jIVsjTRopm_Kj_bvcmEr0tPzeAdK3wHcbwi7MxQxfAo3bPN6blWsAxTHMLVhrEuXLgrDzr6PtVhQonXQx3YNQKtOPYJTA6LM
AvPo_TOsRfUjuODPFxBTI6L6ApWBtKgYbVTRJm-frjawwHu59D6QpKCifkpMeeBwQbRnt5ZnL_6HQaRhDjVxeg_7tl6YjDPZsIS7AhfgNVQcXuOHFfRtwurL
xuezfEoAbJthxJ5Z_VfPfMC6Qrt3T50mn7rkhzAvwzRq0cLQznITOCNHD_b9sVdx9gOZpDuVSrPFAJDPKsFDhNNIqVQLCeFrqPGQQz8PTvUogzRC_ygWs7Vd
_Za2b5sopZmDJhzTxLf7aRBJrgrUtk3Kjx7EaQ3idFN9C_x3s5fN0zIF-rhtlbbUzxOVRwwr71DAxdr9X4PmiX6SR0Wd6uF9Hb2sHJB-0W
}

