sprite $image215 [294x265/16z] {
xDt7kgCm68FXvK7IR-R-htPA9hqOd40mjhurzNtOuVAhcG0mVuGZW0adHqmhEOa0g6IAh994HPfIif9IifALh6GbArd9IbPoLhAIbQna9IjPgR-iP2KhMSbA
LYAiD1d-PQLiE6QbJ2GECQoKFP008tkabGx5z95MYlInafMiH2lvMxAIbRuIU5GAMEbLk5A2hFGy4Jme1Hd9IYzVdPH2LExrhIIId7fzAqcCbApqCkf_oKgP
P2KhMMdvh6GbArd9IWIiD1N-HIlb8evPAPCuuoUmbII2aPALEXeInTMKeY4bVL_9IbQoKbZ9IXyq52g1foE9NfG8e4Y9m4L9NIZXM86IH5AAuq_WzfLmYGLA
8ddy2To-4cvYWP94K97QLoBkOe7IySZMbOWdqKhN2I-YbKuHm0IJbP2FaQo4wHITAs5ML7IiX89wLK9Px549vR4t9RpNq9CItgyRfHzyr2kbr9BIY4zZ-qfO
eiQLi5GDAs71sAWI5auDAc65MbCYrgab9QmNMr7wmQgD1Ke4Zqe1r6GqOFLcA-cY92ZgGS8NucmbwUedSEh6w1XdAucao8g6LX9VYvoh996AzA-UZ8vH9J_k
Ab72zrFiJ0cRHEr9YTWgnbwKX2rJx469sBxgbL15OzLAgAPwbL1LTIgXjeRwb51ZbIcXrYfI8YekhsIZOwn0QK3zRQqqOXzjgeJTn8mI1nkT6bye4G1iTEwf
4exPwDoZaeX32XkTUr1wsDN1HW1lbEAWf3N-EX6xZezAIaih3TXzN5jfH0kHgogXbHYhAU4FDtPXOr4C0r5qafZcGV_bBhPWaFujuIZeJ-f-IfJuOLrtlXBB
qfZRThbABCiMO9pgIbIwM5Li0CgfxZTDwM9P0c1l__CQkUUob2uMfjZ1E2TyGGOExombTgG0e6xD2obBYIq9W1CCsTvfbAJ4dcpXb-Vyxxsk5sMI4ljoKpAs
10NMiv1ob2wsTdQGYWKW6XPIZXBRyoqH2wB6Q5X82KeSoHO0yGrWAQlwzSXGubXk5W0WUfPMBQGKfU1e3cp-fijAtf4PIlEJIC7XNx4jVo6bA7stToTAZl8w
5819l80bk_t-RtilC1dd_4IqAfxD2cUsscRxIXPorDr9_q3Yz3iFMxzI-ZUok5lydOz_MMa08t3wBOUjNucIvN0kNKfeH3z-iM26XTIlHCsSQ9DdIqYxGASI
uKSQq2hFfWgfNmc7oCS2dIqjapgKmCYi4kNIhvIIGIKqwbPAoROIvzAjb99j9Sf5bUUtzYU54IWPBYGCmLlxev5n9Sf56oQ2j_O78zDANFHvl5i1RR9WP589
2qclj3izzszALfLmZjG7Fx0PZEmgKIvlAS5d4fXKGgC-fPJCAt4kVKev6LN2GkfKeWubcuNKhqIc2qbMOjjAN23lAYKYkqgKtqQge1JTGcHJYVXzeufAyNxt
YJgK31PIhaUb_oSIwPNi7xRwMkdkPY9JIfoxZ8vAU_n2f52oNqYYqfv0f5IoNqYoqjr58eMIvQwjK8BsDAnIr-DVLeBuHAHGCjcH54hGdcGbmtFacL808ZXs
WfBrGfALC71fGINpHdebkBHqA37j_teQuF6lLS94edubPY8kXSOe9BqIjgSE9VXT8nMINWalBVrAOyoHUYLCsDeJxHlpN38JvtUK1fWZtr32Imlzs9WpKIuT
IeDq9BqIjgTzOxuQbVUKnfWZpvLSS6TEFhNVqA4qGaUIbLmavjEAYhmbToYDSTXafNcl53-UKl_ZNw_4UzB6uOPGwY-aTvLu1IAARW2bxa9wNyclIimK1b3g
AwGE9NARKcPE_jzNuWwZ3gMTXagjXNa-LQ8EfG4AIL9gnungtPZSYH8dUaDfX3doNAcrRAerVrNcirfAyY9OLXfXZZnNMbhbq5UTGoqFfTjqstwTGKdUjCXA
GnmsxNQ0SgsbVZMbQJegoOjWMMcCnx-ibFsp4fTQdvHSc2Rd3qgmQL4f3L98cAQ4DnFYbQaqfPIypmigmI9OgJHA8M4UIfafWjAUXz9jIObAoQ04cnQbqZY5
XDcKljPVKfks8w7Ij6GIb8H5iA0qm1mf9ES7r-9RUJ0gbPm59MXF2gLX2aakgzcrya2bDR8IJWMoqXXpv7c8dzjJ8BqIjYTPQO0vKX5-lkIw-5CfoKhOdXHA
mnusT6f3k5e95y6oqW2FV_MnIy7fbHJj2PI6BYJCx57fjcID4bnQ1AMn2mcJuINTQPeS2Kh28bXGCb1843Xswtqti4u9BoseDCmSgS_Y7JejAYLiJwWqxkDV
pbVqSEoYIWalBQWqqXof3soSRWUbu4-S0f6WPA6GvFOqev9Fi40GsXCeZTkrzLC1AkrTAWf4xT92b6Z_NPc81t_yow7eNoXbtkE-RKzCHCnvDIfigf0m59oe
5E_d2SJCb8Xf_Orih90mIt22qdn6r6nfBmusM4ZOdbuh1OLI-rqyvXof3yVbg4I0f52oM4WOFYX5TrIPRWgbOUR8VgMb6U7L-2OhsPWZzKf96BodDQAInSE6
OTKzRl8tS9hHzYGyQY79IekejEIuCjrGgMnX8dk5XA6cbED1n_c7KYdicnCeBMuXiZ57olcfDFk3qfpZGsaxaAlJKMc_j1Wj9DoOb_tIWeabkwPKydpRcL3f
zIAO3HXXkBHBotCSDQNTAMo73fNWfKnRXIHVMj2fdRWzIL22HJ3PAoGCHtJwhnABIbjxCZ57wbzJGQLufeIBOEE73LzJGQN9iqhfxXREjesmFQ7I57LAzyYc
aJ0S7UpBf_2ij2YK31lXfWMgQL4hsKUI5y7RaSkiKR9l92-20vTCKz0esKUIfm8tytsQVhbIDP05d2QzadqaUIguVQSqisaZEHJ1wQvGwhkGM9WAEfHC5XAs
fr-jL2rczhAI2nwKFWq9Bos2KY3c6PG-qmZR4ogbn6iYA7qa4bvQK2dp7gTMgkOpUqafA9Lo_O1GTA-LeawfVaXIUAdaDKhrWy97fUGrtRj-j1B5DYzTHeBI
x1IpTwuVhPIyvePIFoxy_JtkGaAb-PNIPOHAvBzLolL3qvIMu53fAYHasik4AO3IPOHEFmZQI0bA5vByTK9GwUl20IQAxgXqoHoSKW0bmUXoMlok92DT-ThQ
qypV6rtjAR42wN9YZT7bDC25v7y
}

