sprite $image265 [188x137/16z] {
r9a9piCg38GBnWOltF-uRwcIdw3YaYArIZwjtIVEsEEaZwy2ZxiIMHXlgJmK-H--OUspx9HmB-N8SY3VI7bYwRYFxMEHZllOFcJfk97jINpohOn-7zi3omo6
2sTHuqQspsEb4FFLROyoX8QlCLw_HJdjEzbbRH_PSNPyC_DBk78MqSHJ-RfPn9ZQku3uSjCUMLoiLYQ8Zm1PQwtgJFjBPf5QRPXwq_vYMLJsLtHdAtEvo9AJ
nOF38oJAt3-P4SRTmNYXTV7Fn27kXBUVOxZAkeWB1rt23xF89w-TiNo1TP73ejqOVsDq7uxhNy7mYopoOKgJmWFIZtPxFulyD5NEXF3ASsxMMaryyY-CxgDc
rSLQmFxEzY7BX4mi7TeXVL292yCFMxHTPuH4HIOKIc4oQ4luRXRvFnSJPdPaOpnt8lFNiwX1hnwB2P7o1YB4bsBYnFO_QL5EoqNvgksppC6mwiM93x-OHOsS
mkV2ou8LrrlKnofZ_C28gRIG-eORYtmW_N-C2URr1ogw9vLCuVY5BFBYL3bJ6Xv212IMim6xRdkI9RGj1CfFCb7X_z4cMkKpQC7ewwYgcTM6cPcU5hrkU-3J
PxFTCrg5CIPUiFrY5lL617-ESixu9Fl2J_za2GjPDF-oI38WnqbEP73QQytsA1zAR_FQNwT279IMAJWTjcRxn0lITs9-MoLmLJIhhji-idm0PnoezzVO-7v9
J4KNQhQQHLQhu1lrnLsxABoSxnQo2xPVo2ArMYq7RxvgPukWxcadVIhNnMcFB1-0n4rzBS4vVvMfjRAOSqL4rchEb4wgZzCiyc-L0d6hFOuxNgtgypVQplZI
ew3rxsy5WcQjAIMu3Jw_onkGc-zx6mIMzf8SDqOE_HlvpooCuKFpafT5Fl3YDBLgoH6_eJAI7dKxgEvqd2ubW_AgzEPjhJLFXlL0Ejgk74S7FeTLvRnw1cTj
ireUKm6zisYtoykeabEOiUfvzHpTpSrgdWd0lgFt7i2LQmSssxIhRvpvNTwo-uO60joSXLfjM8w0R2UYfMa_hzwgKd34nu5h7BC7hTgURS2fX3NhjQlmwJGj
OQHIPR2IEabUXj93EP6mRDPhdwjdm3QsZKRUrdvUl6bKsE88NY9sUu4HYZDRRAJTDyu-323_rRuChrTynvU-xACsRUbRm6rPCqUxfxxzIXoEbJWkhXpemsjB
sVvGzw8NS7SLCqUxRnoEBpNM2e_6qDJ1pJJKrx97swK79-BOpD7U6FXbC5QiT6liQ0vsTXzuBFHb7xKlTNFHrzvWNtkR7zR5kmnSKAJHlp1uirGRp2FYpYwk
TbyzmO6qro6rvwZkvOK31-qC1pOVbnYXONKp4Xp0tYw-Tj_sLW-eRDGZexVscJPuGUi1SvzZjObst_RE2-DtEutZlhdX_Zje3gm-B1U0pLQq_rkCVQ083iH0
57MsPUl-vzqbJDB4_atpwmG5F54WjttXqj2ziBUIsTAz9jJcgBlVFZ9Hzmf7WGwx--qpUVUQ4BZmxZKXS07TNJXPmhhNH0XSSFUQ4BY0xaRxJDRTPv-DYVjf
JaZGQyxfUDeJ0lIQPvt-v_JRPtFsrw_S0zYRNAxfBGjXht6vomTsjzeZw3M702Smz9gBjBUWrom1u6ZGQrR2NeDUinCu2lGQk5KHZ4i_z9hv6Wm7GVyzuxSg
2FIcR3TWBq47MuNO0-WeXBq6lMOE04U0th1Lg7qy53hFJjXhq6lEVlP1eVVded0g5mwTP-bYFm3wwACDoEK4zGPi5MWUqv2SxN2QeIyJo9YjweVk7Qq7lN-h
VEZyQ7teVAjywFmPuaFdMyMX-qVhG-TRvKFdpn0VEjyg7pf_XlZG-LRvqFbMSUZ-Ld7e_bPnwFvMSUZ-Ld7e_bPnwFvMSUZ-qNBe_bPnwFxH-j3vCuH3zu-M
G_UtYaFtZnP3ztCEXVuF
}

sprite $image265 [94x69/16z] {
jPQ9ZkCm34FNYIzIyl__xY8DKJTe1RH6XdjCZibh_2m9_VTJzffqT7-sHgBy3JjLaY2n_m4yWyJ9RzlDxBsVR184MTFTmlaCxjIVwcJNLCNlz-WlUCAH3qbW
h7zTE9ZF_IL0tg1_4rinwxNIRUhFzmWdI-qqTpUY5H21_WNX1ClnSMax_XwB0ZdrhtUFKgztXL_KhyrKyA7z2x6eFxN9rj5XkpxJOQOxl-dNPhx2UwuTD7-9
iTVS2KxzQKMudajRBhNr8wtLl3zObLG0ilmeNFiPfr29zCVZIkaj1ulENGAd_krBuGf87yOc5qhQSeEDOVhre3gZxk4C09gvcH50xm3KimJ8U3R7mfMyDv34
4PAcZoAfAxtidKfGdO5mCXyISgE2SmCAv0DrkrRE70xnk5Bmh9PDppUTLu8aIj9v8nZeZuMJfaLgQT0ZNS_hbhbHUQ_EZCylNXu35rha3gfXzcvpxcmOmzbB
9Txr1vkf7jeRQTvahnCs01jEzYH7OnZRBZll-kspapBNvKXFFCqkYePHyb9_hsIZVS138qb8Xoo0AaJPmj2Sq5RZ2Z6t8nzxgAOffBsETB28Dvw7gPbBXmBw
6FO8h_nIGBfblJ5XMZruH5us8wi4sZ2Y5774zc4APuvoI8MWd_YgojSXs7HYaB9zE5dIwKvIXhle5xxA8HFa-Ip1hdSaffXEwWZ-UX4usHUwz13bp4DmBYLN
0v6FIve9BPSZ8Ejvv0Hr24bveujFVyHuERJp22Hn7ZldvUUHKrBUwQeUd27duUKYur-Gb80k_c8a9QHBpohRn8xewtn8U4nVroCf0Jru_NKfedlCNvOowPaH
_tjum1xSZtaHyh4aHN2l6fyMwrcLCkQtrgqlwKSi1PVl7B5-ueSg5DlUlgwMY4yYbX8Bd_bTFn0Ax-dA_K8_lf6YAWop8-R7KcBXl-i7lX0U9ONTHI2G4WWF
z9l5VFjI-89-SaduDN5t-LWH_Xxf3-WBmh_eBXyBmkFkYkaINjROqX_G9RmjI8cxoqSuPvLr_QB7mjVrN-d35uN7tILwB7nTl-Wt20-7cuz3UBwNFOVR2Dh-
3ltcGyB_8gN_LeN_0G
}

