sprite $image309 [270x175/16z] {
xD0t0SD0002nETFpHvlkSWHS9GWQUtby3AQBTiZuS54kIaQuA1VbecI4Yt9HCi95kIWN9IDSb8kIKIx2HRae6U6YN9IBaX4koaN9A1VXeboKZ78HBaf6kGWN
vQ9ab8jmKIvAHha85oMZN9IBSF5gtqvq78T1C02tIPeqy0Fl_xHxD47ZY2vgfBsA---zEkUJmMRi7lF1-1qUVCAYFWV_I6RHbmVuaOZa65rv27kQXS8_itew
yX3mqz1Q8xz5O_NqvI72JOWoY_eU8cWiVePfBPVJ6g9CdcuvP2iLg2cOwtAihsg0eMQc09Zwzf2VCTiqklPm3Mqqvj8UhsXOep62-ciVKKDL0E2sZZFrLYvH
0o82O1peCdDfZvSq83-2-RuEy-q2rFV8DNQFPRaEupXo_NB9DTnZM6xNwLQ_VUGQxe7xF8xJRUoiNAA6Bu_fEgx3E13gxxQvXhVJspYijwL--yWrt6EXSHx6
2QZkaMku1-PXeW7egNr4ZRPSvX40Qi_wgOPBG4Im4D3LRFkqYwfx0EZ08zSmg8gWFm_Na6EXACoNXm0TbOlObcEbg8Yge3iFiMSScuZsM2uUk8OA3ABYtQE-
H-HeHrcJ3KCKtPGBMOXpDBsZ3mzYs2yvLBnt0AZVFeW1sBCunwDSL5r2jg3YOPq1rqWyGYDjFAYC1m69nkOX8fk8qrJqy2B9DGpkOV9r1e5xe8u70q4Zyr1l
gyvGg7qG43NoSi76eMB5oeKOhsluyl0-QWyILF5mYwYHUnpsc2hjWu5J6k6cnKIroF8W0Bb6xh4FB-R3opjx4EEiHfpbH7sS0zwvN1Z8DVAuHlkD3_cbntiL
IQwH7zPXUFGEu4rtMmBEQEId3_NUyPx32p5-ZqPxM1SL7rxUgdqmy1iqucmhlbJUwB1EmE_GY1wwBOvtccs9yPirul0YxpAyC7uxHXnUOCXd_O8M-V22_ttM
fzzj4Si5Fja-HFJ_BHVYtucHpt8cklsM3NELYYGVNbJXTr79y5AiIDABg0r3aCos1NRL5m_htZi09ELIh674j2ySul22u56iOUJ3Yy8vVk5HhM7a5tC0Jkos
TOeajezsbilQQSKYoI-Y0AQaVTGiabWkS83LE3ci5zXLJmml0C7kchIFGWqZ7rwmQV1zDEN4erJ3o2-YLXDJCKuEwtKQHkuX0h1DPChPxbAjOSGqYqCdKW2P
HwKYoJd814n0FhmKBP9u-Y1LkmC2fFVwDIsY1yqBW1TUqHNOLTCqNxYVJv4SJcirZ1Y4uSL4n3c2HwKYoJsikQ5pZk1HO5SzDxmOL4G2XwTMmyZRnruqwKUY
YZMCV9OJXOcadvYhrp2YH_ZcUbWUx1n5YoHwF1ZCksbIBWMB97h8Xg7-62Ofbpf5adE8mXU791u5TjLJhme5I7QNQWqZlvXJbpZjKS32ETn3OLudafHBhOQH
3o_-M1kGnADEaUGNStu6ISgbiaLyHGVHusaCD0SFjs2kOn7B1V1BMyFk0QpN4Syyc1bgPIoYXsiSznYQCV7niBuj336pOXWUU9wzN1zd79S7Rol3h9P5zDWm
eErXdUy07pnuzwXd4MSvzIDPCxoiy-eUpW6paXPnUDackQ__0IrxDsN7O36hYU5n3I-NzXRgZYsyOx2Q5RM87WOzlWc2X_V0hBH5V5K8O0blO3nYjJ7YgqBW
igBnu3PIsIBE-WhWSbidtZt0nvIsYENoq1Wkq-mUU2HmMEqq9mrUByioqFu_dbsbFePxUEXodoxpme24k4LF7hVfEbw6YIN6BNhYe6cyh3HBZ7KKV6MQW6ur
eiSohKwWFv9hrFVWHHe2pJNgSw3HS0xhBqyrh3yDpr53lnQ7zPcFHfZbZXokqMSW1mxjMyEavL3vQ1ppqVXeV3G-6X-Dy_bR6jy1
}

