sprite $image266 [188x137/16z] {
rTc7aYGt30FGpjqYgV__N8UDE0krDQp3qILKj2-znK2QTF_1cDsJffdPf7hxo8Hoo7nop5n3drHlD6qwEMO-EMQ2eS-ejrSoWNmcl2KomT3dq5i-qyanRJev
PfQXyynNEcO-EMPAEUBhXpwfthIPJuwPJevf_zVGhpP3zRIoVLaLUAkVoxCkYmXlnKE__f7hy5OmTAHhyQsWTA1hyLOW1xeORmLoknVCtamMuT1vdWLpXGdJ
zALZsehqrjsaaSin6z8jx2Fj4UlrSZivlQtBQQfeXyx7te2kFRN2qlbYxe0N2FzcVMJuffBpnPn8_yXbicZa_8xPWltVqtHH39tNRcuVsU47QgQCe7HMy1Na
5S9kF-Gucq2VbHFboXQpH_SVZ_b-2_09ERzaRhAOrNiO2Vx6zMfIVRFNqg1sjfZdY_xiZThVSZmwlRsQ4zPEQj-_wIkvwk5tRkdoVqC-t2ViiN2Wmst9_dY-
_4RacQpVnVduMEpTVpsyUsDsA3-dvqFFp_qYFyyJzfxZwr0yn0vPa-NdIpTsAibRg1Z_rqRjc2s78FBqKIN_RukHEFHEifujgxTy3h2F_-_muKNoHVREab8G
Uig-4SyrFZhXCZl6ytIyoSapxGs_2rOajtltD1wTXtrc6UmRlXpMsoEwUrv__6Y_1lkkjqUysVFwuyVDdEH4Y-qUOC_fh-6iif_d-cFtJ0JOKtXyqbdP_JxE
QBc5zWYmWpxzcg2HvzN7tk8mclCL-tebv61FwPsieGrGRvnktBu_lRyqTBJdyKwkFz-68SNdZexExLYvzt-IA1tiEVr51dyF3uR7za7lmUnO-LiY8GTxKazU
PSNu9KBu-avttZjMtiCJSh1dzS560wzV3ll67r3dQ3yU0gT3v_OyFc0q3Kxmy6Y4NsG9ErHEuBnqRi_htSdr5myCuGlVtOpRZmRmb1pjUNsSO_7U3u9dsTyg
Pt0-bxJTyyN7zXf-Fnh2ytAqv_NzP5SDUHb0FG1Fp8NRy_fmyaRQUtlfOs20P-JSdiTxVyOhqQBx-huZmal78s7FwAFlv5LDzFZtVp-zTzVBkJslz-uuRi2V
6zbpEX4IEzT7Rmixh-ILYLBExNdyJV6_J_VGsRdUUp_vR5nGki0E8VZO0N-Q915YEyV7h_YzAUHAEuRWfLzBUgZjc15_m2MlALrlv_he_NgJhnQka-lj7Fzs
pn_HUrJ8CRVdyr-yxtT7kdxed7uJV4uV_IrUNVfx1FZmUhb4xprgvzBVq19z_T0nWjcNpaMXBvTt1g_NkwfplLulxq1NuUk7hjVNo-lrBZYYKdtbxQBNLyv5
FvmwURtULVBwuQZbUhrEtZj0YeQZd4kvla1UfbTTwFLwGUVbinVEfLulbDVhXV9wlKvUZzSz5zNhTQNNwtNoUhtkkQWUh-kyNg-Zr-jrydgzJbwFrydhzRhR
fLwlAxrUhvFNutLhgTVhEg_Nw-Zr-Zda73-7dElf4Pr4J-ZJwCbSfi4J-JJwsUIeH_biUlZeOZeyb3wT7kJJwV_mMlu6
}

