sprite $image145 [238x197/16z] {
tDU5aUX040DHmwnHct-u7mvre6Fipc2hHlNiuSSrBjiyMEXg_zSw3XQsUTilQmE-STblscfWr_RTMoV-4NiBTRxJkZzMWmusjCr4TNBhX1uiURwZ3JPMJ7No
VFb7xAqZKPrS8wgJsugfJjQ8ETYi4L6TN57K0MfKs_xUrecfJfulKPrSCTN9yoMgarj7eZgvnbGddpDJdQmHKvsi4L6TN37LoVDbgfFdIrGdjo3LoHLHdTms
CTN96X7LoJMcEbaZfZfP8wOwURv4TNB5L2VFbwbEdYzHdLmRYUhaYgXERfkOwcIDYEha6bETh15JdQmHKvqyNw8wkMAga-VBKoTtYAPExZXxXwcJEzLx1wlZ
7Uh_8wlZHtmPMHq_uil8wlWHNyPNfrjiTVQpUyAhumclZYUyEfwmWrL_cF3gUC8FrXDU7K_4pyIOy4Vi2Q-E9xmwdl3gU08Frikl7Hjfi9v8_pglV-r46wmd
l3gUyEfumglZ2Q-E9xmwdl3gUCAhumclZYUyEjw9FsBltCy3_rP_xQzwxjzcpWMvSHs8WVidHI3tF-v-PPJspHCLiTPTdie5KDDGZvBOAUngMkDv-S8chMq-
BmznTcjXUNdhrBJaUdc8AybaNXxYZ8OUOIqmBvyrQRDSA2zVsAGzX8NYyeMj9Di2yh8Gpqd6yl8GLvAvk3p4bMGkBmzn9TbZW_BoMIl97gqF82zRsBfRQq_R
MWVYOeMTazn-3O0p2t4bMVjkVm-0Cmjn9TbAMhw-cMIbI9xWJ48CF9CRbPVFchIsIbeSvnIM9xdc7O1rdZrZtsqX6SCv40DXFmthX6JGHaD0Ldtvy652Cb1V
3cB__cgn1yaws-qpZaaUuktFPwid90FrfGhx-E3jaBFSf0Ng2nRMNpyyPjXPhjMJ3gWlLDZzctWBoNAs2-1CMUV3OVhXcKpavQrpd6PbkR_7sW2SGUiSHxOb
9wpaTzTtl3J4tbBOp9zuihN71N2ch5D7Ll8gOs_j2JQ2hLFd4TNwQvvd8na86-lKj2whVKTz5-AIP-B9oBOBoWlrVLNhL99j5PoVK5-zSTQPacm_exuyn1TV
0tSCgpdENTuMSCQjCq-Rvixpzf1zEozldMkIawxYlEsvx9NwykywyzqcRF9M6ssIvEtECSbRvnx94vn_P_AuQwDXpZeB99_bLKrRSRQJbt_NkPuQzhI-DMt5
sScBBTQ1U8tavBrCMuz9Et5HwooIFCzhpOz9Etb1wzpThMMLkNrCRh92oXjkdUkHzL-InqLUzNEOirmBjCuwoL7hp4QdQHFMugrpFOTbxFFcqQMbl5sMhP3C
MMUTPBzveRuioJs5NIDPrfsyjlgSPCuwwoGdhtGVvtuaXRVEzNpU_YOvpwkoNarm9acETPRcwz2HPBUs-O7pjbtQ22KvrbcVZqr7ad_jApZtThLUzKgoRGcm
pjfysWuvt5lhJZTlrBUG35XdQRuC-NZvM_lSib58zXD8ThNE-dmhYUxRg1yFCyGwwpWtPHPiL4Z6hBDkeph1ULpdxL8XcNZNMRTHdHtdrgzij1MIKUkiVF7r
ESwzNzOt9DiYhRDUtxvItumV8zOww_KTa_hEy_vpaejrsFfUssXFBDmww_MTsAWydK-MorjdVJwTsSZMrahU6SdhrW7dotbzjtQAi_UHNiywyvdOgDQtaWnR
XxVHaMJ0Ei0nQSziPEy_Ue9rU1kvT_dCHeNa9rW7jP7RyLSv6YLlI0Qi0zJtLzpKjzf8JjedM8UiR-AwsAZW35W7gQybdnoJ3ivYhCCVanLbIGQimzh8SjNG
djU0TT1ZqhsrcZ_D1Qo37fEZrRZ9-_x2Bbc7jv6t_V5Smje6h0FNr_LF9yaBM8UtaQt_Novf7Tv62RiFRXt-NT1PhddhyB-Pj1sI0Uk0zJrPxZxukmvVNxkG
35g7FoQpNDmw_34f9ozX7HxdRnEI0UlWUVkxxsG3rY7hwmne7VwOB2JJxpgyZKAoPTuw_36PvPgs3c-ZGZ9f7Rw-4QuCMES5wbj89gt3soWa0zPvaVhAW7LU
vPYq3LZdTMnam3glKzynNj0wFm
}

sprite $image145 [119x99/16z] {
lPc7JYmn34KdixCfTeR__zo7QVTTYKXOtjWgT8xsc6FQyQ8fhPz7-bn3ngWb5_heCjv7nfK8BKsCQYFzaKLzcj_l4QabqIz6ndCxz6m4pJ5TAlmok9rxercC
8ARTIyNiYwbKOMh2YZcQDLTQoVFBCUsDPctwDIikV_3x-fYkxe0YfZo_7DEkQFmnnO_Ids8wTqOJZucNwgR6Ot94uuafxZSUKpoQ-8fBzVhrnnIF9XuJbhe1
hFwZ51-TjpUQ-CYyxplVxssJ4GtxjPc_BNMhtnNssWa5DitlZPc9qH0sBHh2PaMpmfujmI-mkNuPU_KKAB3RerbXIytp2-oL20KsBHh6gYP5mrYPAcb-WTKv
0Sxm2-nKbPtHhB4gakENiGPEWm8By5Q_Z9tQ1U10D5vihHtSdNuPsrfj0-10D4vigxN1TC2l4slWpnMBxF0Bvlsc_sETfW5rKkzM6Dkg6wnkw7WSnpUs0eoO
DlYzzJhUv_iczmemnHI6ChST7oDJ3QjJcd4zAnRr-psDYKUhEdK0J355es6_trWrx2UOJNDCSR_rmEW4rqn_Wkl2TC1lBmTZ0LQOhXHJE1fv00ci0HMcnvJA
CGMZUGB8M0LOkkZibMFoGp6j76iimFRigB_758XcXTM9vph7P6-II3HhB3zWZkdptGBHhB0o66mnGRHEcq0qAooRvhFr_MW3qImbGpQVBM2d0_esBPhbdFqB
DyHuGzYq61ZOK3GybtnYgnZk4yltah3UQDRpL8C8yNZ5mFgZMKzf1W1FsBHsprVoR8v_kem9hcsOmG9inEzwnR-RLiQkeNBv_s6f11Q0WNKU9PvrJ0gmm3Im
pgFaN_6SU9Qm_gFqrvXi1gqOsCLHqkSHcj8-mRtHsGBMTPJyfWs8imMiCnf_J7oiW7KU9NzCqiOFti2kQ08nIQTpuOWcjkB9M7yq_dcAGGdh-4uUZGbOHpJn
5GFhYoOU4x28PlTOJC0weWcRnd5Cy4insI2Qh7cgdQaalnmJZbBcdEDrVly1
}

