sprite $image118 [239x172/16z] {
vDg7KYmt44PXPVLiUF_7TIJ-MuiqfsOQhkXAplO7VP2qlk4x9dLBuRTChDi_q-Blq9RjPUel06VRtiRAujZKja_Jq-BHwhHbmSM4kdB2kGjJ4buuMfsU5uzM
fyMb3X-PXHDE4ktI2SSsK2vr2akq8E6rejMfoqUh2IyHxTe95p6icB16owSk7gsEvGLkZCibhC-yjHFMFLuwONtcBPsmHhjsmXhj4WdpQFbOZGlS64722qUh
2IzmOmG9hnkjJbqlMfwm_pDlxOGrsWKIvj4QdW6u_CXe8qy49EmLhJ-N9yoZTU2IXFsVUSgDyoDSaB3xZL6vRPiV4ov8sF-PnxcRS472JlyBtf-h2ViVFlxS
pOf3jEvSdZ2FrekRmKNQuSRenkK9ysZzkUu9WvPSk3nXVcFaNCinfCQvF64UBUTQbAK1N9WmZvPpNzVE1bmmnJtQCJUyJ8LSdZ2FbdCDStd2F5hErQTX0roG
yB4tnfQAxUFMbt_7jfjROpqZOG6CLYUs2Qx-ryI-bzkY_BjOmdoFBSlVCiVTUgrjxpMZPtc5meJvuLFb1zk9joehkvUlncEVULaBE96Rm7-bbVbemTSlDeVl
xiiadh16om_rr7Tm3RQxA-6M9gBbXtgsEQxL56s6g__fE66DreuvrCk0QzPhZkpEN2DA-D0RerNTaY-uFRxySS352VSy5IrF-2ctXG2uHoOyZhQbqJmkonEk
jLhYW1ic_bqyuNBABueexroTFhWpJmnEMAFbN1t4XU0-1KwXRpe_dyiVv-rwkRXpxPkub-k_S_dpkQdFO6_twm2CkR76CxZyEdYvtUyltD56zpoQ-7Wu3Bdf
AJT_EQejazWNhe1Fk6Re3BW9NDA7U_p2VGTZR7dShREubbcqT-42yE3QVW0NFn5qZuKBDfe-03dtyUqrjSSlKk4Ac4Tx47VyXPtTO-NYZIu1VNXZOov_-IbM
kHnSm4Tpb9jvjCh56zsYHBkB6tSjSurxenMjS16uIhJdSJShE5hbyess_EmMb_2BA0t-NM2FbSl1FSbk3Rbjy6b6UbvF0j4EkVnUEURszbPXggq_uPBHatRC
LV3nt2PdbntDbMYLYy7-NBB7ocLWlincyZk02x321Ga3xc00LmuVnbMmCnTZALV1lboynvohO5SkntAkRhGhb-ynvohOaykndAjW9oxOOy15O7-kVciHbs-q
FrUndCl1_bp5ZkTo9U2pk2PS6YtdSd0AT1BOOy056-t9LIpZKh0pL_UOSZdOaQjOoXKl0DFXdytmiT04319s68cMpRM646A__cImxZ6UMu_XlycR-qRxOp_-
B2c-2VllyQM4ZnDz4_QFLYVv9kmVhKusXut6Xm-FDeSdKpPVi7-qmJDX_sYRxB5lmlxH3iRX5FRwragqCWwdiEiUbp0xiPsmqRvxBD4E9frmA3bYJR3Z-RjP
EqmZ88Q100h0xlR-r_KRW96-vWRmlcIIXeHfyxb1EppXVqwCXB1lFlM40TgRbH4W3D06jUz8U09e2mPfWPOHddh4l1kqb328UPBmDDN6lE1p0S80BIGypKl1
RiOJvcXz5vuhOvud32P6IhZpRiOJhjZD34zu8cXH5au-R0lG8i8DnBoOCFYuIn3p7E5WObILl7G0CKyI3YP6KF6P5Enc9E4OhINyxGS6CKyI1cWbuVG4xslz
3M4GysGN1Z5F4WOnJn86CKzsuO8J_CY4GSoJX0UU62jUEe29KH86CKyIVlvX2z1wmW2jxC80hHoa0Lf9k2pc-Te-85nmWX-PC40h2PVkPdpTlle7Q2LX4FCa
OR2RaOJ1RaOI1hiPIHYWbLaOe7Lrc57Ckm
}

sprite $image118 [120x86/16z] {
lTa7Tjim44LHeHBpGMN_kqrXsaXwX0je_DFY-anTDPpSFhtKQhWjNwoIB2-kXc8oCwcbbTbyLEqeRt5LDJN9_arMmofOUvYiB8BrMyASsqjr0NFST6Iv_5NC
uGLs2JF00lCAM6PU0SlC2s2PUG4iC-ThdnHvp7mfh8ORCC_1gkJ1gfXv7bPnAFBytIrFmlfkABXmksLDCNjOw4RHUeGkCuzXJMRO3KOJTCVCOzXnL-uhpXUO
FmVBNPb9r0NcJy5oLotUab4NcJy3oztqIqI3xlkPysjL9d4t3hgIYPd7iDucDecwsyyF6dQbbfmNC0Ci_97PHFUhjfd8Lot3PJ0pmwguTw_FNPF4tSfi1tC0
M0YtvDwj-wuaQmLkPsyPAZ8ph1wtfN_VvBhQSlhvKVNThd_h__vUOEOloMhngoN-kr5SjnwVtLmtLlzJnzVFc2CSFBITFxg3yrLzx9wlmACvc5v8RwEDkxna
h-NUPQklrxJllJ-LPVLXMmNVltzVU_1zM6BVetg_7zq-UlEsHRW_KpV9xVJ-REht-z4z9iCz_loW-zx7h_NzxhfO7ZzVgPvrLK_VF-Ye-YwNwVdPN-z6NRCI
Jc6XsoKwMYPyFPBgQLUopB3KvKls1m4bzpmP_xhpwo_1GdV8ZDsKIoavDUoQ8IntkSnTqz-HBrMvYypSXK4NONsNfhakmtANo_DTGHMwmxBIu7m4NQfoTyoi
D3WFGbVzoDBwQ70E7ImAOC-x-_lBghdaSh9SHJSnxrkF6mQvhE7miSDhyQUBuIKpCuzXUJ-_OkbsB6jSjWzkNEtPdHRwTMKDgtjzEXtDbjyFw_SUvdbOfHji
dbbZs0BHAMPVvJbOsdiVpVEm4ymJi1FCqx3pp1h3RW4pp3mkJyFECq_0JZ3FmVBUP9w7vGN7ZBkFBjRYpF-cZC8Ji5FC-mXsUkMql4_0JZ1p5s2lPjuHDi-K
c9cxlhe3xENC-mJi3FEEZzZh5ziENO2zVDbswCBxKzWqCrqlm7uTy-uE7WiMc-lwWmVlUkPz0Imm7zVR0FQBcJl0BbYo6TWV
}

