sprite $image256 [324x221/16z] {
xDc5TK0n34FHW77_WSlC_IhttHsa8oVZPvWHSoZWtLq-3iEklb1x78ALVIFNU3TCxtlUNOkmwWVAnW74-DRxQX4p-Xcnnbl0-WK-nzkmPnxJQv4O7zivx9bR
miuXnaejicTk2Jk78XHgaRFaSskH6EixXnW_haLujIAfnLqjOUUiwDQLSPReShDdT3dPCpgVx9clhKLYpCxPsPyb9Z6MbRDdTBKvItIvs3EwcCHOLiQUqUKc
nhfSx1cTJs8iAsFFw7BppAgBzUT_IpvVEJ7MrMRFw79nbkXYicTqpZEhhlP_EakeHMi5vv--PpZ_PlPFLvizeuj5Z7K-EKjaPSHObvkpH1UJ8jJvv2oHrUQP
LPUB6EjYicTaPUmPNMtsZ2uNCTRvPC_8oeYnBlUl-IrXv-WnfXQz_xOopX9TBlQCBYPdYQoSFQEh_GDYJ2qgUuPQ9CQdxPqBakfM34J1nk3Raht_tUOpnAzU
LvpHq9TGHgYNS0eTgUzye3ld8FTCQN4uetrohiCJFeCtGA1OzOyz29bYQV7SDdGgnBfpfWsTIh7kd7C3-YYM5Yy0DegQ5klEQG2OOcbH_1Zg0rrQd84-YdNd
ZA080rrQl05z54kB0oZ2G9SMh-0KHSv56cMcM0CzFl0vb2dMgzWCYZ3GLVzkSnCerhN83EUVKAmx9s0upn0erft333i6kdufudnds46nwjzriGsYgCNIucJB
WWsYfCNIuW3OkhIOOWtqbilk3rDyzVQ85kjLRASmcw-w5akB4xvYomgHOjM_4TWeYbgi-dV6hzX3MgmV5Wox3pU-kZ3GzIesOSlESea6khJ8GgJbyf0Mwyu1
XMxk6kWujv5-f59Qb7B_HuOx54kBFmpyVjzS0IXQhFe7SzykxRP3SOaera2RkpjrlbekZmNknF0qp7XakPGMOSuCQRVqtDmVDSRCa7PBk5ngeE6-mv1s2rCi
BUwEyJv3tYtye5DQP8BCa3FSTl2K5ac40KFQBQH5Aork7yA88UyMlha5BUOco0mvumpXvawlHNCF60QxHRcvizqpCSDujy0_Leim3nW6kwMqQEu2GzejHF7p
xXou2mpv8OAp-FnH564kC8nsop8_GX50EeBCKFaesWOn_t8nTubXl5kS8EOTQBWB38FTGX2pKuHv1yEujxWJn8nQDFTEXfmfW9XFYt3lPHZt5hTvJZlGC7-K
eRHR5imAnJm4cQ6qMsnxnyccHRYh3ECCRUTC5BIOv4F839NTeaDiG0g2p53SBRoSCxpdcBl8KF-lGcu1nBUY27UTeRvR5WGGtqUBC9SOQXbcMiu2n0DIDDTo
KZFHNWaX7d-WuMfwleBv5qJVWmYy4qMOlveXznON8MuKtvgW6q6HTukR0F4u5CqxCW_4HDyj3W7YGGOQtf4sdZZwRZ7XmX4e7cwC9uQXxnO1uc46kelWxKma
kdVB_fa8w1JpZp7l5W6YCD276kDB04NQBRP0WiWKtsIChm4GTRVOOe4I3pJGUC4ze-mMMro4o1GFFiO8nhXpe7s50F7LMiJHnfWtj2rBqvJ853FK4dr3--hz
41jmI15YVCrtNiDN4o4onGIrHCtOR5aWAf6rcB2Mw5fiq2WUgPP88kpNeWwHA2QuPxGxnrYB3Ih5GzGITOpxjRY28OfQJ51Br4pyxoaRP8h9nbZNeWwn0Jbg
YLx_Z22-d68NmLaKuVFl7114SQ3V_fbLpvcqY1wA6Mg9_Yhcg_T_51kGe9Qe6RThiNkWaQAMw5fSdwB51FUCd6kWHM6WizqpSOONQj6ENqjqBIwlq2Bi1S-i
2Qx51FUCclF_haNpZWZtpF6rQ0751BL4ojX-haLt2mOwmJqZPS9lrsBCCAQOVunrBPgx1LfCK4lK37EinOsXUQ3516EivH9hyGx6pDs2WNxcJqkIQT7S_-7u
BSM-MlAM1FbLRDDYmpx3BqAm_nnec5dYUwPVYsO0lXZoVk5njsVLahnQT7Uu6VOWtb4aU6Rjl7CYBMxBsTrtbuvReZ7MjMZVQz7SxhXWPeHNPcYNKwwCNrhy
Zg8RS3zp_3UA9Z0KxfaaMhGlKXip4nWApwpfjBY1iktEaHbYF6ND45wBPkP-PwSpjEifSyPcGOcc8v4O2hKaQIQG5WE8n52xP_9hCOBen31VBT7hNrYYpS1h
HdfcJQx5xwz5CnSO2i-igRLe0KFzcJLR_VjEYynGgYNvCv8M1OP2BScN2rsB0aEXbgJBETAY4qFfdicVWRGeC1IUMPFUEVjQX0KCXLgIMeix54E6c8eUrJ_I
Oimm7kFI8ZCKQqbfaHd6jQGouL_NecyngPQK5dSOnhMaCioaHIE6KYqfBJOZXaejAIqIGtfchOJ_LsmrPgZLaj8YCNoqbbGkToqImwebqWyB_1T3zPwf-kTR
JAqbTUSyuzVWIelzkwGopWTuNVWJ
}

sprite $image256 [162x111/16z] {
pPW7TXin34ItiA7e_iTD8Qs0NkbD2h86vmJ_wGynQs_-f9QsbNDK8gh7idnxeP6ohmcOY6c4AIqfcCd2xLnLiAKUQmgsCELbwdWsfdVXbXOLRE4LL6V2AVk2
WgzrZ9qGaFZBisF1yNLCG32eOyI4uDWGXbwOw3hY2N6eZhamE7abmL53c87WyCk31SVN4Kz8-EN14n9qUV24-5EFkoV4dxp7N1Z_vOaNRE5w1WXsN9v0mVWJ
FE0RmN5v0YR4COHkmV5rT4o8OmZZ1UCwnbyOd784V2CuXj0_8M53U1J45tzvZaR4037-yZGX2cR4GtWoCmF6-CjJkGSW1jVnu6TeqJeM7W6gWoyFyPIEk5eT
CrlML7qskY36C-RBtbN865_79gqsOrpmybHL_icuRXqJYmhL1LLJieijUb6zrX2IT4PUiOxKwrYauyYYTSpxTl8JKK4T0xDjUvNE29vCP1crlsSIVZAkLKSM
rOz_DOXmL1qnd-esShGdeoelCeIYFTD7Zl1ATMJL2-5uCLR76bf75dqbj1SJNqVZCyBBYs5LYXf24so4bdF-6Mjh0NLaKK0ulnWUY5zTHr65X7Pu3B5zeMfM
nOGZYMV4zunt2yQ4zcAK1gAZZWx1WD1UZ0n0HnqTWW6XlHW1Y83HBnWJsei1Y8FnJZvCQ2z6k4w8zwW6V9XmJFMCA7Smie8y11AE5oC44OczWb7gZW77YvaG
MVZ_Cc8-EWm4lXYT4ETWrNx1oIXm4WD4mEWKNA3WwyQej7gfebirvcilWd4EKcxL436ZNp03mL1rjTVYKyq22rYsVqfM9O0u6FryM33ENdiT1w93jM31v-R8
GG-kTI02He_Wl3cJfDVH444T7HFYIkbr9Fmp_kE4c61NzgRI_ecHzLx1bfDx7HapHWYsv5v7mdNqV2FuirVLTwhbyZDw9yHvUUILKUMTQdnXj6mt9NtKKOnA
LFYLqJ4XtkJhvH4LKVciEa0mgAD8Xvp4Y-CRuPuwTa9L-r4L8BPz-uea6NMqNwrZ3MAT2VtV2FuXDB73jHYXRqByG_Yur5650Q5ZGZn3A6qQmiut4Vedn9_S
wqYV4SNnP-OzbsUken762iP362KO3-5SHp0XOSawrL70XCHbhuzVTHJyZH1VHnOm8R59CkeeO4AYK_H1jJO9lp1u2AcEJNbGf60yXFqt31QCXz3-KxbezYBk
4_qT
}

