sprite $image263 [188x137/16z] {
rDF75G9H3CNGF-Jd_libWnRUa1dT2dGSjb-LsbhLYRRy9C9o-CgTzQbEE7H4M0vZEKo7tWdB4U6vm5WEOpb4Xzv5E7GOos4iXx0S4RrePnmwZEKGbYEYG--C
GuUn7C9oH5YE-RpeRZRrJvTFOvf7VJrhEKxMzRpykNmtBlu--hmmT2ph1NyR-dQSu51yVQ0xZkD002w02O6y_tLtHBcJh9arORjPB-V_uIj1T8lejyYLBtGM
aoBrhzVUbbElSXtMoZ78PVrdvF6Xrzv5fOeSblBNzBfEBnTvyc4YQbPg4pCjvUyKPrqkX3z2Ede6YZQrbkOmDEVlZzxMav_gCWGWW5MRQKvow2K5z5-MoqNE
FdoMdmYe9cADihJvFwRlwJL0JnUwZ5v09punabeJJIWYbTRF2XgGH-z6kG_5aPoclYHgPaqhm8mY2TI-C7eBX2zriT4PPxZoV5DoCTEQCv8U509BGByW3zsD
wkWLn7Yapf8WjQ9Q6K3MnphDjfQFovMVLhgUFI6SOIsdlbRCK9q_c87wgThh1uPE-gikfU2HUZYfqQzMpJ49WpvJd8XSw6cbD_mIIiAPf5mpVizPd4fWVLjl
aPIdkXZXjr1hX9aYkARC5hnVU_l0q4b6Jy_0GW1hmdFeB4vwg_OMoeLJphfSmwfe3VT9io-DmhNNaBmzhNGdt8NK2F-QyjYNiTfRA7opqakv6wrNtEUoBzTh
RvyOUlOXR8sufgjC5FylB8zzYKMDltyt8XrE8AvQm8NnMwedl91yrZwloRkxlzcNslji1J5LPN2cdoGNl1OgouZUk_kotaVxOwLBiaf402UgZS3yM33EU3ci
valoQL_Mzp6CVwxq0vXLcHX0pbGoG0IqKV1wiWzVaSzu0EzZz7okzFu05gkK3dKfb1aetGWlXtJqbQ9VxCkZRs0RgiAOeQO9-T3NGjbwmkkflQyFVTf3Uk_3
XqjLiqgOITg8QW9OXYp8sKOFoASzgXyLrAQ-FFH5Cr9hiqWlfuRgCkDXlBR6O6r5JJDcgBNilIx8EN2DNkmX_T4PGj5owDD9KJDQe4kWBXTxJEzZc1HGqvpL
X84wUlxMOlH-Pu_h-nWg6KabPRNgNH5OZ37vjCVnKzz56DLQjhwq64ll7g_BrHxNDqfgWSKObr_jSRs93r-x6qNhSc-Fw_te_TfYZ0_ztXx7czl2r5j0lc0F
5CSBNahouO6w1Epkh_VcbTcJB0qzP3UBtAg4yD_9lVk2F6ONb7Lz7xtYFy8w-e8yRWVC0teldpYcUt_JBX-jFLjWw65x3IxxszhNY3nkp-xkpKErZoz6xv-m
ixihAAJt73ocNtX1EyDz4gf7zCQ_5kFma3nkJp1t06ZXsYyUqxr_obuWFdihqOTLlPwBCIgFsnkgCmZG-CCgVtqnzlMqVxKBYe89SFUm_elotlx9lHs6L908
v0luM3n6dxcrEmWe17OZa7nH7vRVwmNi0509oUdSDjVibz_Z1MdQXP0RWFlQRwfBUyh5NgPT2SKjaT_QVVlGx_K-xKwFij1XP_DhjillzGIG4qJgFy5X1wo8
NxAXBY_WAv8Jb37ZhhYzQ7VBx_KcpZ06CmFk1QXyj-ztr-LUxyREaBFl6V2CExnlbz_hdO4sxNFu5P2IBAwFroMWpm0gu7ukUO9a8CNnCNaGBpZYZj_i21Kd
NfUmtZ9VxUnD0deFo-Dw9xYUTaoxU0RTw7VBx_LUfbrEk_jwSSBoz_KdDayxFpxKMklSERLTz5yfUXpV2EuqxNdQoJE0SdW1_vNDTRdNYpj-ioUlmDoNSkdF
xhhSwt-tP_S2WDphnUwxvVTwdsoRnVSZZwl0BtcdBgErR-45G6N0wn6WUPhsM_r6-RsUSCHnfZZTsNrxNUvhNok3721cmAVzBj-MXuzeoQSOv8w8FLwNz_MJ
d8Fsk3oUgvqhoEqZzf0dhay0G2u1-mRvHTyIWxm6x86wV5pl8Cy1-rM-1K_a_9wzpMpHbu3z8j-eznArpxhiral8FkNRzVU9rsK_FYxVhu_NPRy-Bj-lZzTb
lpuktu-FrsM_FYxVhu_NPRy-Bj-FZzTblpuktw-FrsM_FYxVhu_NPJy-Bj-l3zTbV_ohyly1
}

