sprite $image97 [294x226/16z] {
xD0t5K0n3C30wPTCveysVJO0lpi6KW1G000006W5000000000000002WBW00V0A0_zk8J6lt4_cbrw31ZdqbEGp3C005HJMwtF-usnbk4cpvjeWZl34mjFvY
iYcr_U6KJZQ0qjmfyxCISKedeWJKraOacRWIOfuoJCaJjSim9O_osYMJJHNSmckNJZOW1SmfSw_KMm78F6L2gP_dsQgmUSguactRUHxrjzgbazbeRqmTk7Cg
DwUCAnrd_w0HFa_fPFDTQTOl6ZfF6HlIkqBn6JPFcVbrUslGv5NmaBdjeHGq1H5Ttids_L69p5DjVMsZUwMYGCxJOzaUbQeXKdAUtEWjDjMLf7hNyYg8ilct
fELJgKsWJqIMhjrq8M-Sg2W0wP_Va-GytSeMIlEqucy2lGEZhpvFq_Rxc6t7UPeMnNkq0z80h3nFOHHASxmnTK0BFjCRCDgojOkoHUBb1AA2zxG1Q5llAd0Z
adWvkRih6pd6Lt2odSP6dvlTU5JnaJu0B3TFS_yXDZu0NEasJuwonZnvsMZetwxFasUHDnLkn9KUvccTsjdEmvMYTfu5tbJeX_It4iIThZjFt8Z7Pc5ACKz-
OLxtUhBzpzWeAg74vadRPUU96_765OM2vVArusNZIe1MaFpxAd2dYngv4gGAQ0fnuZyjrooRAx4ZQONhwRMTU-5n8mM20BpDQsXY__-_Uy6EUvtIphWixkHh
1kwPMCzFhbueKE2BH2ZP6MxoyOH6l1B30R5plol0iF5Ao86ncy49ZNWbaYC6SZpD5JPKGexnyUJV29MEpt1naau5myOhCPkav7zNW6Nak19oI6R64yJEQTXu
9UH8MgF5pkDumgl8zvN2wqrIKjNDlbx1vUxfVIFi15wTuPBsbNmTMZ1iOqeG5d1wKie3km9_HdXhAH0M64-WvB1JqL-Zgx-Bpu-mmB9EHJPG8c87uycR4Ihz
TgffnyauOWKb1-C9mZQcr9cq1WmBnYvfTdLeGQDnfUwqoO5JtoJ9JXx9Gul7iA7ImNZosAdW5sbSoPY8yGHhu2BOWn4gMUnWF74S0X_85eZnv21ig6HEvMZt
96Jbgrg4Y9q38rD29uWTS_64LmlQqqli2Zo43PLiF4NYq89BdlEedIaGZ-iT687Is7YIvzXrfIqSx9wSX0sLq2dBcxi2kH_RxXzaKo9s1Hyf8yULk4CBh52k
b_0L_tnG7ag574-V3nkln8ydl0YMzkjwlNp98uyfbjj_DptO5NW86ohXOZeLMxbrfYpVUHIvA-tj2hgJ0wC39JYq49kar5gxNBTOhvSWoRvdDoKjkvsAWx21
qjXuqlvbghVS1VdE8nPJE9uS61qhiPsAHKxZFNT5ldVfiPeIDPu-7pPUYHzFnY4IEbNFNPMdNNe0fV-WKwcVDk8xbTk7SbCgyfp7aCf3AP2n-tpOU2FS5HoF
9x7SYM0Ueu64VxjJgVf1e_SFBO_SIGVRAH5KMn5YF7aQI6zsAcBd5Dah4LIrf40SMXo5xVrE1PLmbtxR5GHYL-3HYEzKJ0dpY4f4x7o5xVrEHVPkMa8r9SB9
XH6_Aq0EsUyuaoaHuyb1s0OEBN9G8fXAJ4Idui-8xrGISxMmrLP-xbIswZTiU6ZXArySJtOCBZ7-5BkirTaNQRnJmJm-AUcMeVArnrBLgH6kWOjWKCBnbBIl
wZPiE9v6BeB31afV4am9dDmQyPqABhjfYVMcX4wcfDLfs0OlWZ6FCUC7GKp9d1mROQV2NmJBgtSgiIeukGlR-4LmUf572RaYKtDgX1V1_Av0NkOnvVANKstU
ZCPt1Lh4OhVxCECl9wTVf95tAg9zv2TvyJ0Z5L3oP3H-4HpirSxkwrN9MhyYA7atuczQJ4ctWn-3KY_NgmPGSc_4ZoTJgWSFCqehlvaoA7b4uiSJnav02NS5
NIcqwrL1QGuZ_d5zCIKyjDnNQA4_p02bIOpuyHGgAC5usahxbM4kpMF4FwwF-UZ7eFIs4vIcGHhlL5AmtJaeJMN4NmGVTIgeDAFHUAU2IZCWZHzQC8y1b2Op
GgTjO3o1adUZyKu5buGee3ITqVXDY_GFG6bQ9FvnFIf5BS_jzzH6VAS2gtS2DO3IN4RZ5y6bTQO4IdCZyUE9xmJy6uqVMkAj4wYWDBaHtwayLitjKY8gpM_4
LxvzXLnWltGA9FvnFT49p6t47rfGwKn6VAU2IcSouZiLL3eL4j-fWDB9ZFZn14edC-B_m09GEXKIVsZ9e7GU8tuyGUBEOyGVMb3fj4ROgGmh8TByumcLpco4
dGgZDByHN_cYqaA2GykEqZA2JcL7QHd1eML7QHbXfs9ApPGM4kmAGfO_IgrrfcNqmtYAgbf0QHdXUDgqhw9zcT920gUgi9RHJqwu6AF5n1Wj9mPfEJ56Yuan
MawCqN9Ya9OJOxIO6AFbz3z0-WS
}

