sprite $image124 [312x218/16z] {
x9g7akiw28Q5EaIJVV-dtM9yYIANE-AqHDOtvPJjty3oG_pnej0t7nE5jMvp4n9mokYp9kGfH65DqQnJcyhSjAOtDwq9jwb7eKrHSjFQiRa9qZ6AD3UBJL5p
qvf2t6nHbRbPRFf8CgrbtB5MohHs2deJgAMKwUtSMZ3VO5jiqnkTai3yu9fYE_KshMLdLb9JRAVUPeiA5gNOX6bjbmYc8agndNgRBMhD4u1YRSyR4KvjI_Pe
yQ9jwqrUWfWjkWLBm_QJNJnxMBE7E_16DHTkKMUU2DAoUTSRDSpiyOD3GZ0Cx7YZ7Iwx7WWsqpTHIcypJscNIscJzK20I8oLJgKdRtJ8bRE7H_4fNVkKHUYC
2sOFQL51ZAOg_D8vVX1hzvxr01BLOBqriBaR_I_NQz60z4oGjz12kSXB47XgBMwoHmjA4oFrW0EtQ9izqkuxYLJgutwHzI0Ybw23Pu7D1RE38Liqx6QF21j5
kRbWzZ1yYsQMQOrrCZqteo4I3M-kAtkiGZAOi2vNkHqDOhEN-_3h0GBxieqtYlAUf66C5ctN0vThFO7_bChQhAa3czEk1t5DQLxcmdOq48rg3hjEau_i4TaE
16SWKuFNZWRXFjHficxSGBuvX-oFXX5BJh4Ue5kpXq7qni1Y3QFtQNSq159oAqET9ZCOJvJM7aIiwZBypj5GIXcXHILxM1u2Vl4cTGcYQ7l1r1NRothJd2Qv
qFpw9yfwa5YJrwwfBMLXaFL0l9cyobg8x2j8QMqlcDt5nWnnciHWKMm4zmXom2aDDpCWA4T3-O_tqjQU9hFCrb3Py5YNLLh-jAYwOBR59hnLzZXO3wpy_04C
-CpPmqMYnKvCrZZy3HVCKl76JouWCL7Mz2PxE8hjPg0V3STFV-6_pi6AxC6L0n8qdhD7N3eN5iCfAzTKiNRWZPZtM0zotN0nhp-_r5yY1Ev1J1cvMDtHYrjH
eKsyaV0Uwu7WJLnNzIGY7VyXAjbYqg-ffRpeqr-AqsHq01u94pkefWIRW2hh1l6Zks3UzhrHoqkk1stsg9ip1f42dCeG7gAoPBNzK9DrlzzeXzS-JQ8tuA6P
XXYz2yY3CYHhh6W34vPtneDGOpNpz5zVc1HFBk0Y1Q7kCMGr5dERKz2Om7dD7OMQs9tV_lLj3Zls0mcl_h6_-qTTVd5t9jgjspmG1XUH14Pft_zf_mLIO1k9
0gSIhtkCxhREak_C40E8zpObnIMDFZTlOrDZQNjUguSxpzz6EBpsMWGagFpTpGN-FEGVccZJFH8b4Hw3TpFVW0mg8mWrpvF3Q_V14bPtDnUC6otwvR93KLuo
b9jh40Ok2ZNFavEuNa0j7eTKXQKGjRkdUFkYF7gSdtpVEXP-cfmyLIyusA9DsV37KjuFhtoNFPADxV7Eawl--yNr0h45cxAUqstlKLcgIiTdZw8w3KEDqLnu
9hdvrA9DcPTFOlwIFHBLJPOv2ZNAUAiy7znyQl6cpB97aPxihLzV6eiio_w2fl91zXXYXOre6d9zJSSMjuRn1UYoVyktx74FW5CUvkoVhcE24z42cL9_iX_4
cpBz-BDniFdsyKbssSE7cc7uq1WogV0RKJ6VqbgyAQkx0kiDKwKqk9eqm_UjzM1KU9taMEi4jdXJLdPT5Q9X9Fl-T8jtdjoIDLMNRF4gShpN2MhXfam_BAtO
QJQKr_R5YD-tDZUT6hMFZu_r9PhZkpf1BRZGmSc_dzaLsObgD1vevM-wwFgn5VxyCSUFTO3jV6iOsVOUpHugt9FIETvvMg6HwwBuiFhJPXNs9MUf-L-IPiNC
kwR6dIfJ3zwtZXk-XU4iQlLdpShVbVWwtnfyWx27qi8_lczLpEPjVBLe8BafvFvYlXXSVDTlt28AzzQFnWFxtEtSFBNfafDORUV9nNVzE9iEd_dLMjNnTnPz
aUGW4y3vCTLZAujnE5fDyWtGIDP5ZwW1JdBJ-ofmBRduGaUXmfiMHpGUt0_nxVXWM_r7k9RQkdxB3N8XkVYkNw-yQR5mS1rpM2_WAl3PmniJwnp9hUiHDq3u
MdBnNR-IUp0USBsRgE0jwgdDaXpM7xXDC6kqmMJ-UJN9YtFiiKKTqalxmxe6tEQGwy653cv7gydYeszCpN-_NY8sVvV9SPjopFaDPdmTqmgB7NQHHQT9xk1t
P7BSPXnpVaoDhsDQGMDUGqZDrrMH18TtcOpRTMQDDvXXzZ21ePN0eWTrYUJM-_9RR-KsaPmVK-Fhc5nk_nvdZscImnhSPS8lmF793MPy7PCNfyt0ed00huea
goi9i5rBpe-fuMgIiyalwA9kqNjjVy0QSSEANv8xrHhYrMGnRY4rOuDOSkifSFZcQs0YER_1Z7yZAOmKTr7FPiLKoNrhOlmU79yOKmzlBl1jY2zoHCsaDLzo
WaEn6RVPv9fHEherEShja0C2YpfizldLAVYGcd6RRLQpvlUhILwSOyFiOLHNm7wWZtN5fP44AmxxB32Td8sf1wl9aLnV3RB7NKFzyknwRIJn71stwMPr4vLZ
nCbrqJ1xmADPuJnxPDOBg1ct-UJOKLD2VeZl2AdPDwjJb7srJaZ1Pb7FRRvP5pSUk2uAplNPlGVyXr1SEvzh8aaSXO7vvCoA_jPa8IC8F9qzn6MFzPC6Z4aG
ISvICsxppTg_Z0TSxwF8cUonMtVzm2tE_mmE9waPj_daYeq7RY7IdieUmAP8kEoXZrYpCAmUZNV-IMp6RRvPXrdKAR1m_EEjviKWUwZMd8y33OVK0cwpoLKb
v2MOmYwgvzRgswZF7lQX8LsdKFFSvfkLX--YwAa6r0p6ZkXBzi03O7j2zJR1eW6tcMbkb3p2BhhYdX1ihFevUzoEEVqmQiunjLFSfEQ5hphckBfpBlhnOF-z
tj74jza3UsFL9wTPLFVcYAjkM-vBoBNqz4BNnJEiFdjeFMGFtqpnCSEYA_v-YbiXhNw9MQllel6FjzhdbZrMdpsC8O2v1vk-t7fMRwqbeeOBo66xOZdmpDxZ
bjCSeFqh-nepiuUdzYoteLfRzEyNc1KBBK4NFTf8hihBVUEc-jFKP0smFSiDcHAhx0HNa0CG_7XkVFUT5RwpMh-TRz7VS6EYn12YUaqc2IpgDqPHzh1-Epjx
kFj8SGrj2vNIXMdkztiFsDdlRxrPzfXlqUUvSMK5rp0oNpXwnNiFnU6jQoXjKfsQFJorvxa9qQ9TSBbqQCNFYnseVdoF-5o0-0VcPmzVYAjG0YGRkAlC6c-l
3P1xo1z-ixie_luDDxcTRWEGGjHn9RbuUstPOtUV1FtMKPiYjfXRNiG49wgu181BQNA5MUFjjP_gFmxxxNoB-efYcq99b1beH0EontrV8bCa1_iSpimk6llc
FA6BFitD0fjsXL685WpIQjUODPRS9r6i3kkwjLlCj-ZlkTc4m9cqAXfHbf6eupfoGLzrUmzbPHmdPuz_oirQQDjbrecAW8dacamIt-6uk_W1UoYOEYPPz7bk
IG3a3a2MJ4NKfwcZxXQ-vfYB8udjFToyFzMY9xZfGKPta8Ge9yhBHbIkCciSIRGncEXUIotk2vIKMuPLfRAPTcWoMIGcTxu_-Ab-dMxHSzoOg3jkJCIGIjHG
wPP9gZXoLqiEzdcqzvWlDgsVk4cXxBYXwL9fv0QDSdic8MfovfYB9MUt6LwMFM9oncqG3SSDbQYcAe94DD1Laj1sSVQOGn19Bjfxo5bgLeVSaAauRdicoSfD
L7y2x2zRJfWrZ2JntcE-s7ojHzm64NjkuABSYd93egRS2X4jSefS74bURb5V1zoGgMxSHXltI3RTiIQxejo4i-8ySSm5aekfpRTeJAufjqwatFhNULvKQLlH
zd1IS2UEkKXoyorwdfnKKJZARPjG5qSsYN5JxN4ANjwSw0_JiyTbuAmBP0MpjBI1OsRRp0t9GxbjXzkY_4JEaFEHv1KMFKzEZ9j04Wqx-G18-LJXVk4PJVDS
J_t4CNSeENpCi-Zrv1RbblHuwvGXYt435kMbt5eYIXl5hlHE77DUSjCFjWdajg6X42KgJ3I4wCODN5CUoktpjdrNRWiUwhJaPbjqXkHwLHIiN2hA1WSOdH_x
AMTA7SRjDBcFWrhbAh5z12XEajlZBHVhhHjAAkEEcsgp7d23o0cpJhJeP793E-N8QUD6EY_OZS94f7rLl4zF7dFuIWwNMVIlAVzRy6y2IMjLkd8RLRdbJ9It
eM57c2WVSWFEIswL5uZjz011bDXoYCvP8-tXbtK-xKJ4nkqISbZdMdG-ETPNDSPDYChsTXLQ8v7MsBajb9jSSSojHcsIHUUJQnsQIMGNODtlOveYx_HchwXF
7tDOPtVH-SVS7JTKeY8mmG6o95gmSvD2YMYvngp_yeCjtitP0abO2MRcGW8hkSiXghoAIyZDjkXyi-gHrY5K65Kx1GlGqkv9uzQMiTzckYAJpBVeV7ASY7P_
DWK7Z8MeFt3JZTt2YGe-YsK2kGaMdKPEAl6-CngaGIJJ7JSfjA3HNWc0AB8bzUbcdKlj_BIlMwKA1LUn3wrMeuE95XcLYFIPBPdGm0Ho4omwZvojYrHtKiZt
pgmEJKJxP5R4l3p1h1CiEecS4Yki0vZ-krCJAyXzFQThAECsXzm4QfF8DUL1L9LRpGE57zf7IifjJyF9SOl8lOFOzXAt9Kb4ngr3yB3fbMhhuBHJxXFIt0Hg
ypjhIvi_TmyIbLe5LhBe-QRSO7gxtAmJgCqbPsjVu-QcKYbRP140zRgx_FF5Dj-iMisufKJvWUlGTQQnhIatkSYiywdDNgHtuyPI-jVEcsJdraoHrv2RJct-
q2hARNVdmrrCoPHPCb57sNhmBy5zl87O3euv8Xfxv_IYKgnQ7Ggl4p5-GGuVRq3ju9ZZJ7tdfg9IG2wJR7fR18toymr2iE8DB7eiEVxafip6ewX4T3LSjxkP
YGQU9FT_FdW7iHsJGpQzLK5tefAoMRGbAeagdWEdVF0Ur8x9DKLbekfUaTiRxBRlbs9okndn9XOzNgJBtYHQfgnBor4NzjVczBWJnEImEculNnVDlnRHRAYd
Ui-eK16CaGK8oDq0uIqi6fFhAYgThqRwEdfHeaM009oiLdWFYyRaAcL6vyA0D7QJgIxh2g9Q7RSti6Zylb15LGLWktn-AwufzLznUoUBnajDoc2YL1cQEm9h
XjmYQkz1JfQaTrl_NrkBg8LFS7idYyQjTH3LhaCMS1W-OcxlPj5uDwSEHTgvrRB8F-3sVjJYwy6wD4hgKxSEVfxRMsAB6qIjj7Chen8z2UwzgSNaDFdkt3fG
ACbJNdrxQl7xmbxtysq0Gzlh4gDx2spdry5YtBHo2Eujg9s_mzHtRaoKX3Db17M2sdkrLkDMzE_j13U7xStDcZPkUwBB_stdhWuO1c80XfQvzVxJbj5_ft8i
ZV32EU1kqVNofzUzMv-wHOMonisj1zsYIDGDg7KQRjBdRb6hj4Vt3Bejerp91Bb5ggJSeDKjghRAluDRt9PnpbDkqU0MjvJJhI7ePYlePjJDg9j1DwDkHjsC
kXbqC-fcrCsecq4tesv6tUmrRignNRI4OsURScoIlNAUR6npICRcASVKb6Dioltk6FqE
}

