sprite $image372 [413x326/16z] {
xDMtZIG13011UyW5Dlze_qzhQKtZK9r2KLp_HCTjLqLjiZnekZfeiZnikZnegZnekZfeiZnikZnegZnekZfikZnegZnekZfeiZnikZnegZnekZfikZneiZne
gZnekZfikZneiZnegZnekZfikZneiZnegZnimZfeiZneyA3vhGuRF6W2F6W2F6m2EcWgF6ZmeFcSHzFLqMwO1qwQ1yvEbGTETtdWX7dWT7dWb7NWX7dWL7aM
pcwJPouNE9lKcRt0EOxT5iyZ3PovmwdnpAqCd9rZFjEPasdWx5Sy9rsqn-34U9vfu3mYp2PuvYKDdFiQhsVsjGsS7_2SH0Fd9SByP-VkbMm7OHW0z-3tVztx
VzLaq97YRBQmwWmDts1pv6M_a-TA4noYyoRFgc8umU6rxSMA5XpWV3yFQ3XESDw_Lg-3p5wOw0JdxTR3QMhz-JZPvf9wllohPsrAKvDnWE3mlD1iDjm6ux0A
HhwyqMmsln8aa-xmz2jQS6xoh1SgMd1e1VCJdNv50qrmiDEljHv-VRvy3CwxhMTjZIOuFPxrLSqcEC1veVKOrsSN9vcqtNhw5IquEay_qLbEHGkEMS5wX-T8
iuXROa-Y8tQbrMWsr6skZPj9bt6jxZKRk8tLsSjiC7NtMcqs6xYjgi4THxqy0yVWQLQquQz0q4LKdV9_zO36hsYxQZZETcfR2ObElzcWeWN7uIaZqMatc-1y
pcqkE0PFgza4npiyPIKwQtUQJN1CdZ8IdMv52ux9KqRWrgremT571i1HUUvKj0jDSFJ3KrlNSMdgK0aJUqeym95u6itcZ9FOS-zZeJAYk4wp2SvnFBD85z6Z
kCxrEJWqLplXw5bFjwA1RIOE3wLF9qVbKKUT-nFRK1n-UpxWOCa77dNK-O6c1kF8jGquVCd2frQpmOcQYsFo04UgRPrc0xRWIAq7E2fFu_eCjk08X-U28xIU
TaKBZiPpnVayuQvrkw9XMN1a7k18jMqfDFnRSAJM0nnTjDbiWcCS7k2eIuuqBbjYJs6lWICkwLoVVPp4dbN6ajiLBJYiX14SOmcvXt6su9mL-5xhI-vUduD3
5FXUwqkwpGRVHkBms_C11mWVUThD1cm3SRp30nnv2JaQ7jjO77klzIMzYWQsmJZsNkjB7gbeDHw7zP43Zj1wn55dUsYGr1Cu-X9IjGosu0Xx3HnvIRlP14US
Xm975sqscy4uoqez3pYyzMHeqFo_gtx2R8YkjuO6-MDFuBYYViGs6uVN8mE7wfWqUGI2ZkEddesPGIzY6pO4NTXIFs5sHViHsoWQuD3RCy7nHFiHsoGQuDnA
cDqS-uc8ROWDSFpKqvuPj2VKO1j20no3vuBZYpOZjX4qm963cmCE41JHViGsn0OuVke973V7xaTiGsY0O_1SS1pHH_ukTmWDS2oU2uvKs-gneS4G6k1m7N8d
ba5trGPDBs8RPBF8bdeud8VUmoos0JJ0eLjguN2Uf-OvDO86EFpsp77iLo3zY6q43N1uFU8uzaId7x4DiG4Evp5mi2H3WnvDA_O4Zixpq2EG6aC37DukrdcF
TPs77e7K31lWM8UdgXepWqQpmRS9DC3nU4hGmP8y0k4q5WwVXnxA6kF98n12O-FmrdF5ySjX7e70niVXUtt54NZo2CIc0KxdTxuIIkSHY4_3OqzcuqvqyWZ4
iG4Esr8FX_Fa4OX10nowfGQEm9D78A1HSVZjsS31Ylpdg3ODSFYM_cJlJf8TXs4O3A_XvFxdxRLw-eC75Msab7sFNrdq8qN4mA67voo1oCCn6ZU0mpoxba2a
OXeVXtaOXtcY2VM28pNI13XGUX27TR9Yi-98NsiJNSNDPWPvY-sbFXqfmM6UV-5Sh-7aA4bbF5A4O_sSdqrqyXPR6OyKuh3EkkEUR87aIo0Iy7JQX5TnLvmi
EIfeiQb7HufmmjjD_XO85njYamAU7XhyBsKSTy2zeSKc0KyxJNuLTsDobCcc2Xt5E0OFu0mcHqd0qqyJ91305WWaHyKjDkdfF5AEm_-b1WvAHnDgnf4wRVPV
nTsR76Mo2NIwQV840dyB95y2OHofW6QYxRa_EOhP64Vgec4SBZs0CvmS1V-iNfiWWG1mvfAZ19zIcZI18D3PjmHo2J-bDDpsV47RCvuPv2ssWAV09aWWo6S6
UOkDSQHo6lWlDN2iBP2ynGOuyppITXouqc7WM5iWQOljOnofa8Qlud82mNt9KGwEr62J9n0m3fzjFA765fkBepwQF84WI8vAba1y7AcCPiM1qcFWaFIEUOwF
8rNGv5Tnmvb1L6m0Pvv70pZ8WpYiaoT7PJWge8aJ2CAPGN2YXJXI2OsVG00uo9ClWUGuKe5DT1Ktd1aa4-eSHogWYH88WZM3T0aanr41JThsp6S6UOiju2cW
WQku3ixrcasEKlHvlesemZWuyybHaKz2CuK3F0OE_5RRbq1kUdWqzg6tPmi7U7OlWSGuqgDjv7Kz6GVEjhrB83cEL833F8pZR9Jcynp6wTSn6ZUCaoT76Mo8
qyzZt2P4dD7aACRfvp4w0mOEbPvi2IJ7oNacSQnwaSuCiYMG0AVjuR6-P9zmykGeP0jm-dYyhYVWX4qWBZQ0Kyp3ECpp1XnheXErs1Ydl_IyWhOdu0maHm5E
-yD3Ry-C0pe3oL5Vp1Cb4AoVpt-hgIMG_hCjI238ja2OvfqlWVG_F47RCza2oLjiadJEDiJnjq1sjDYamuCu_aGdNm9PS4xf0PnRawDEwI6RJtdo9P05vvnj
WBE0KEb9lmbanJayW7DPII1PiGbmkalFpzgUbnc071MR0Pp6Zix_koYNiGMow-l3fSC3SK-G13AG77LueC7b12374-eLvvGUcAXOjww1nawEEW_FFqyqlx-T
ptDMdCFpJngVPte9vFixElWVCvqS9Gteb3myE8HS46QIewJ3yqVSKxXGici9vArndOVou56_FJcAdwY7sioN7gp2tXP8lWGoZ_F8b8ybxWbmFk7PDSzv5z3C
y02Dir2oQmdaNK0pmuC_LzoG75LWCzJH4NoCBP1TGuC2cfHdVg5aqnB8UuwcdMTBSfJ7DaNJpsFF3F8MsvHDlyxshmzdjYcQVfuRagEcQFfvhciyEMhIfby7
UFOkWRpcQFfvg3EmUmbaWAQO9vyPSB4feAdWmSx0pYMG3fjSPpw4AfrG5z3qXb0Ld6YjFFdC89nGpzFqytpQbCwMG0fikaEe2efDAqy-CpZ5nk0PdnaKl3wt
ykGXLET4Ut08rJdH0fw1cG7G5Bm-L_44wU5V-lhS6KBru69pU4wnkUriOvxp-dmR3-iyUDHvphPpejt7ysbw-A_sx8M6eH2AWg1_rtZWkoIp5YOzb_GLQPoU
yB5nUiBFPwUdl6XEJ_XJfzDJFZQsBRneUC8qjYsyQ7Z2psVR5buqFE7disqB7niyuMDZsyB7nZywuKMpRU55mnDUDASd_7psu-aU6pneraEJZaqwDEdGb4EJ
ZaqwDEdAD4hJA6sZD8tAD4hRA4sZCetID4hRA4sZCetIDahJA4sZCetIDahJg4oZj8tID4hJg4oZj8tID4hJg4oZj8tID4hJg6oZD8tID2hJA6sZD8tID2hR
A4sZD8tID2hRA4sZD8q-fHa
}

