sprite $image354 [179x274/16z] {
xDiBQkmw48JXiSUEHjtI_fTx7yTGS1e1OWhSvQ1UmKVoKnxdyRh_tf-VxVMasqhzxyu7YSzwtUUjBaKJ5LVs1u3tKlyw-QIt7rXnXxJu25eahHznlB8z8cBv
fBSp6EMJFa8Jyad79eIJnh1DtodpT9w_po4rR9DrxA8HYmvUZ5W_wQD-Vv-tViJvISScj9F6iF5tP3MXdtGSDlcaOyJydLlAiF59wqSSavQAEF5ZwKOCMyup
_22QIFbOkXDWOl0IXYtj6HuYLagQ7pR-pFU4OMFEMz-b8uvdhNUIVDmE3cJrY5kFPFqcIFAP0WPPludUIV9UCY86-K4HWwm_R0GvEMAGnP_E97bB63QEV2Gq
GP7tXASpGKuPDf8i4J78aiD6alE7BPBr8YR9Xn0OPAtN3eAC9fGY1bb_s29PPjX8yguOCSZwmnPlKnWsWgmTCSZPxyuqsIoX2OByVh_SpNIRYEIjr5hylpFH
9a0E3pi3Mgs9IDuhpXnrA891FXp8Qd_GWX57CfIeGopYI3xT2JJH14b6mwZ3zC2Hx4JIH1C4cQY3UEtWoSW1WwVIn9WyhiDk63Q2JDH1H4oG2JJH14yc1ey0
4sGYQQ89WapKGO09Ce5cck39VD8OjWJoAEca9Y9vgn3ErC4tmPFF2qEWxmA3NDmCQ29fH7m7sO4caaR4jv1X9kf04pUHByLa7HLrC62U3FHy7NPVnBXN82EF
B-f0nBUGFo1zapIQI22tzbNIQ2A3t5kRgYCcZIOIoBstBv86E8FSKCLSqldaPlXkJoPjhIUHuvTkhevh9dB9M8F9EdhF8uT69z5DW0nqI5gRF4vQcpnEMfeS
wm1Qcpn6YvF7IMkJnqbBayShNKsSF4vQd3nEMfiyJbgTF7w6WzmaoUCwBggxA7bSH-lDggcInnzBBVsjPBuE9DsxDXbemsI8av4qo5sR3FIJo41dabiWpzu3
oPvFhejCt28lyY8lyY8lyY8lSllDv4LUv4LUv4LUv4LUv4LUPB-HlCZssycBlCYBtDh3oCsjUjCcHx25_-uH9xlLYh_IVWIvNTg0rYQx0uqwvCb0rp_ePv3T
W4OTwcHt8kaiSanQdDmkTqXQcjnxCoGTwf0bU_cOnwIzQPDBgKJIEMIWm-1faqiXaiuY4qbdaOcaiyX4qfP9Bfylagvx9Xde-Jh-RUvEj3DLWI00JxiWDCtx
FsxMzkfKv5fuvYVqsRBd6wPIkEH4NHoCPEj2haUwLCQ2So_8nNgGVPICj4NvKoUR9kr4ndHKqUeXlYBxPwls83iwtxLqzX1NoVx9lSWOQV_k46AOx8Fe7kJR
FTmYP0B8c8vUvFeUhZDWhyXcTleNzo3N2o-lGAsHiq8wEf2lz_0u4sId0he3kHBfRMB8dcD8HmVoTQI34EIiYEv0haLQB_DSAGn8HnyoHZfRkIURNQCxa24T
gjciCEHYIaJwEPb7M-78MI77y68FigUZyEH3YYzs8s-H85DerI79c6DySJoocVEgwHYFN8o9j5Dj27BMf4oapIsl9YyrCfzZVz4BV00oykhfy08VW4pb-FWx
SYEGZKBxyfSo0jaRG-yZ_Ocr8SYcgiH23zSOH3hiKp80cUZZ_KKlS9fisa9EROsXN3Mdr48sJIc-XknegkNKZ2NxPyHNaCtOQjQcnjZHho2Nh5oahJYPDMUb
5hez64has3DiBYVClj04cY6l-c2tLYzm87CBdPh9EBBb1-YZdyd92kWcCiuKIVIH3bzgccnHP2CYJP1zbjHSpPgjqEGq-z8GaMR87cc-cbiR8o-mD92E9lBp
I9ltm3tPWi3I89eduyofZiPq-BNpUxAb2PU6I0T1zbcKY7JJYPJEbQN1FPmdumGs7PzpsnXMkTknGKktaPz7MkyQmpQfFKrPCnOUJtuUwTl6y13ZoEfdkX1f
cimNdalP4wcy_E_JbDNCCaIwYOmZ4Edc4oaBDu-9LpD0FoVpUtZzhCIYt3rDMSqG7Gao7MdCySsb5vthJrD6CaQQ9_EHFhzOhiXvhMS2oTLqy6I-yF3I2nRR
ae9Wu-ib6OwbaJmJJYRIs1XORBAbZrc1d5KloGNI0UJccIk5PyLifsEnBUwAC-whUaakge1k8TDdMfRnHCh2txq0zyqb7fyEvFnVtlpT5BazqkbZd7mkDdpU
Sn3e84-7vYFBtszGoDvZiZCGZPTUqlwbGy9Pu3yCqCKK_sOoIMu-BDNiZN6469liY3HigvfEw5ryIeSUv5MUSF6m54-aBCZ5Pb59nmIHTZ6Wyx7A8jF7F3DB
1B6JqqGyoNx53jhJuM8qOp3a8NjEGCvpqfbxC7py6UdAiwXCaUm3wjP8E_bSA-bcueGTfDVF9rlcj9Fn47QQfJqTeKAEcc38IEFpoIpuqfGIrml0WvMUua7M
uyqfAu7U5yrLi8TxlVlI-0eJPZBI1gTAYNYG7kpXmIDz0gVve5NNJ1xkuLRo0c_YqDiaqzUS8-sPu8uq7-_XuN9RLmOj_gDqTD1t9aWBaGnsffJ9T2nxQtr6
siLnTahVMPH5E--J6Jx9ElEbApo8tzRvmfCFjCIyYXTkrs3uI6GZlHwR6hd4_8zVUmVIXKSFNtByF2oy1-9_culsmWlIGynlw-mUpe_CCaZXiVFowbxvmXi0
t1hfTG1mS-4jDncUHjp3_-3CQrYbAzX70fCEpIO03jl7X4MebkXVU6hbRxAicq_0o8mHwMobcC0I-oHDyw-Wrzk7Kf_9om4sU1TCpy93SL7vAOv-nQyx6KzQ
48ptOUVD9vNlsRfRiV10ZFTXfyr7uMxHxqp0fr9Tt8SDBivmj-YtPZf7MizNUZ4M6PRVvrSBJ_FbVTWfU2hyTpc662yym_kmvrAEHeIuT-5PgQ9atR9to3Wp
HRn2XeKuH8Yny9wtxJi
}

sprite $image354 [90x137/16z] {
xThfdhCe48Nne8ZMgIBtVxapTfc8VMX_GqD_cjIxB_qFFcOFZz_ElANm-8EPLW0IXxjX4OW8iCrZuIWG7s2T1eROuB3RieH18PAxvmpAxO6B6PHxtjnbEuNE
Qnh1bBi_CDjRx0pCGzV0ni04D-Lk3yovcm9JY36v8xbZSdFWZjmKk7ri_I_tbUq3UzxBSVkTgpcJF2A4Miv6Cj-KsqFaV2ilqk7UoFFl0vCyA339emBVoh4d
S2bpO7G49dbSuBeSUgvfB8yApFBWm2od8O5PNf9gTmYMFGGKlI5OtjJ_ew8t1CkAmku9mVBR1ZfTbjq653s1wx82dAGUk5NctEqXwZBbRdLPjf8kSZS6PZaT
AENcm8soADoat1IYMLRKRO3SLhcmERS7RfNJlpAqe3at1MwJi_sOXDmssG1KRQZcBjaFdNDhjaxvi8dE0-IwRIDalpfuxi5hfjo3P4eoL6RR1icSEvkEa3ct
AlfbjaVTKjZ6i3D8kOUTGPvx-ID_v8_yaJ_oybTotcNzdyZsHx8fO7yX6mGGs1_8-aMBMeUSwxAw3HqkdxODbhFAJWk4x6uvRL3AFKPEfmqTAgzhMlSabDlX
Pu-y9hT5F4dXPakFKxPcURVhIRRfKSWADCfi-u8nxsmfYw1PfjnFNGwth0416cNAdHob6X2qo9n48ik72a6hxBQwZItKQnovc-GoDpJF90Dl6sYKFJTKpMpY
6guUTgFiDZGNCjKeSrkBlFuaNrVilyq3P5wn_wJMBTEA_USHDPHMtDxPQhBoYg46hSf8LVhd6lYUM-goYgmr-xR6DRVMQoWW6zaaYpdDAuQQgcQcpGxxNdui
S9jMB4SDfjDMjM5N-H6INcpeJGtBMQR78y8KdflaSgRD-2fDDQuFHWlbPdcVMQno1V4QfMlBUQZRoxwJENUznXfEUDcWRgV4SZbXfTpPLCl0ytKB1inKYzma
5xdrcXkYzdOrVly06sPcHP92fedNt33JucdF_5fpt5sNIvjbpaqrzWVEvRrhPx5Jpbazz-foO9DpUuqZyBH119A2_nzFjijMtClSokMrssjeBFQAGEBnVrus
f7ZpbslKSrisi-HdxBfDp_-FY2Z4HqrLpVBq287MJRajRt6YhG6lt0iyjyDFsMmFTpIzpQrwVDO-AUyREtFlWwzp727p2TpcFcvp4nIrVMFXCN_bXZrnaapp
nFayWC8kSeUmvywQUlQ86YL12hkTj7CpQeI1Sv-7tL239YddtfEqmvoabhkU8eJ69BDKSxCxAdTyatCetCO9d5lrTR5fJN7gkGPUR6YsupBNDMtGs89nRXHR
2oqTS4hYhxaxPi5Xw_l5y0x3dpLqZT_WaPylQLhNXF8bR5_kN4WXYetQXn-nNgHlLuj_
}

