sprite $image403 [146x186/16z] {
xThPkfiy38NXV-W0It9y_rVRkMkN9aP2PWiTy1qs3iyRI-dSJsfzwz4BX7NRrPw5aXgc1nL5JEimNEQfPC9gLGgKVqshiyJxAKNwO3joVnB7hmn9sZA9C2yA
MI0_Qia1qNJfBJtaHRZobaGaQ4eJ-Kq9e18aaGdJvtIH8F-I84Rf9353jgWSIHmXLrIE9AwGAIf74cU5H3O95ubmwYNjV129a-AYtSiLVsU9ZBTAzYKjsnry
34HvbsI_MSwuf9278IwIIT4wQWcBC2DQd7zibqDD_3d9_RjHpRaa-Fz42ZbKJ0I2FAO44LPVa8084P7uIA8j89AGI62ReAqbYcZQzRJM0oG4HIBOyOWsYfOL
IQAnwRk7eX_0Gqs811WCZA9Vn0JHy9eWxItb3oQ869uMY2b28WH4eoTWu_dpXLoH0C-UnWUdYXYuGDk1CUI9c8uySP7VP83qrJCH5x6eQF346H6BY7JqFCo8
s66HoihYf7KlluWBD6poZfXVfCQZC2jYRf7uI74HyuhCfs5MnE0M2J1Dmke9Nf78D0chCrlaUIJy8hk7AMAO8Qq7Sei4Y9DMVn1Rn7P8E4i4RHuH2ruJ3dYQ
JyI02CdhaTPSedcJqwCj91B1qMs2Ts01aMaAWEW9Y8AZymqi88f-ws22w8cAR1E40Pw1XKN-Jmy08d1uX9Auo7q1_WMQ5x4mYGCBY8mmvOcBuYPxWSuN2H1R
eBZ83i61nKLsY7lYedaJ1vOZ4Y3cYOliu1fOYeWXy8rN4GsBx82Z0nFmwWAYWCaOc8AlXaLsEERX3SP5Td0k4BQ7uY8xmBT0sw01KS1a3MnhiaNniESH3B-G
jYWUt0FRPelYkGUsRNataHxqC2I9k41sI1DvGPed4lX-IvSeCasGrf95zdzro1S9i3EmIqGY60qiNyGm6bY-YE5fO5UB11XuyaKCRmjKGKGJ3ruhOXnO2H5F
rHVrNa_KUprHHpbHx_L4lHSIiK8YLa_K2udOhuDIGaIJjbv6nEgBRj4jkaMtw1RTebjqYsxHBRf5j-WMtQ91MaV42ebOFL77UIAT536j8sA5HAoUg1SIiK8Y
La_K7tL4h9285HAnGY9MJzHHHyGAYLWX4Qidwlc_OxFpYPZwJlMfN2AcQf_giy4bOcgSwcVa4h7TKzfFoY_Ilq-huGdd5F7qgrFzt1OvjBFFf_hvMQBNfzK1
YhSh6fnMboVUK3GyhU_c2UqiHBHfV-UUHO-zqzeJsegq5mZcpkR7dItKrCv-1G
}

