sprite $image344 [254x325/16z] {
xC610000080WXFrj5wa20000001WyklhI8mOY87eFu7EFrnv1tbfUJI7pk0LPsfs7-Gnv5QxnljKYTVud4ljdwFAZaQckeVFr6clMd-FNoRQ7ZvJdJrJtT1d
RhXolqvk6_fC1VOMlpN-ERSzV2RQx9bUnvKhzQFnCBSDVQQweSzKD_IPweO-eysUgMxXCzKzVEOsUoQtsJDTy2zNwTTOaWliL_txCbQckeVFT86zuFfvx4cd
_Ckr-ZMsvgwXp-IgeSyChKC_1D1gDzlqrX5sABGFyxdAeT-czq5sgBjoKTkLozeMFgjP-67OfjU1TcWR-gpjocLjLovhkt9Psy9dRLSkQnlwh6teiu8hjrpl
OwzSrhRmMTlGPmsVTh-kRUYpjYkN5NpQhT7hDZkq3NtMR8UsAvUrNRciRUYpWl-PbzFxPZjS_VGos_Heo9AkjSFJLvTs-StpdkpxJhwOqGFyHh_CJhsrqs_O
gfUqpI_OhT_6bpb3xmr-mndw3UzlE4gliSulSun-zVFBSA3UI_o6e_GhtrzmddxH-ikSfryr_eRJzClyXcFrsNo_p0NwNwt_1liU_VpnDroYdp_-Walqyw-V
p2tw-Ujlk5J_VFq5n-gJFt_zPOxMUmn5CzVVSBZ-lKJ-Y_5F_oJxVlrxoVpnbxb3RqqVVndkq7_sUvxVS8t-iqsQi_w2o_Jprb_cElsqzJTSgPUUNp_3ZNhR
Vxl-Rycr4-N8KHYCuno-06dV_t6tUbZllveK4rTicA7HdBdpQtsA5PDKzQVs-1IRw5NX_s3y-zXbDxwHNaNkNFtQspKuOqnef5VvwVXB3tnQpAjS6xtaqVt1
rK-qWrxCVnKQw8KONnv_bfiE-kFKEtbUdoByA-FFwsWV_MBEEjgUO5zVVaLKqJSFlgNvJ-i5__NnxwOFB_PAyzkUO1FjlqF_WgynwwsqFy76Bt-1tlxgkSly
lO7--lZtrwSNEkf1ynleQ-F_n_LxDekb-Gtqr-BVN--DCOkgRZI_XHv-VVlfhvVSS3Q-lPM-FlxzzBB6hulUhsUjDB-DlZx-lVI7DU7BecVrLSdasbhgw-FV
NXyztyiemL_VDrvfgA-FVskzRCQK-i26fv7cDzPBgl0Rw0dzL_rAirKzpM-fhu-_jDAda-PIkUXvWf1hRQYdIh_WVqnFw7Fjeah5zskSCxbIQtrz_1leWpMv
bgHljRrR3vhVGryVV-u7odEX3rgKUx-T9vRcjzVNut_U3qJ_NEYfL7o9buNcTz33B_r9b8UXGUX9Ee68pfoLUkZhuvya7r_TqwUb5dhs6-5rgQMFlZx-COcY
VoxqbE1KsSrRnHvwgj1BLj_H1rSBVRde4Ngt5Ct_fuSU_bFR3a6sMbQvwCbwBhcIQ7vNlQJ7z0IvhcVHazsI4LrDBjzFZ_--dj3NzInws_-Xjq5VHVExwQa7
z8JUrlGiUe7G5qSxlf-Ukgqdz9lOt-aT3v3nYKXmg3cUFZe3gAudueI-RFveUdPLUwZ-NfyZGkZBvjlnUXy1VQVtPEJhItX8Xj83-aOlPAIim7iOhFU0Adg8
TBYivL0TIYyfwm6XhozwGIirbZwwFV_he-eLlLXUChXULcEoNbIlwICtCGRN7vPxanVqB7h7u7hMbkjw5ZsPL9_Ov2VKxxp9N7hMkJYfNdZ-XFg3wzs4-eL5
Rouz9rPoHG_eO_IHwzs4-eqtc4lFeXSdrIUUEvUUHMyTJI_oZDvphZcEFZYNdj0BvveZw3cWWNz3Vt2OFuIU0ngRxkkZw61wRmpy6tfg93rdiZREgAVYr7eJ
fjJ3drflZYdryEVJ-nt-FfzU2_vaUZtWRnVrFdwA_es_Nj1pcFyHUWq6ldohNqK_Hr_m5_b6drG_JA-nuAElr4VfDLfpbfV9z2L_Ehqc-4wcqsjoyEDK-f9l
vzEhm9zGh-AdrCEVMQ-oJAc7FxDUPPrHJwqdNcRJytCOox_jt8TE944CXE7BOLtDll_JNbgkBWm_CfcQiHK8Yf_QxiAz4hNMmVJc-rF90-hNLwr3wkzVen_z
w4S_-j6FVlIZ7_tvmFghysFf9QNf6NTt_LfwcFxjbm3xK-a_Ag3fKQ_BVmwxf_xzAS7E-jEbxgV_geIcPtsfWD_HvzYjHx_kg0zgUfxx7yNdp_gWWsVz0dv3
dsNdnEFsPtrOqtFY5Pu_w_CEdXElP3xuGHzWxoSUy46VOcUzpP1-f8yQU9vxys7yGPzsy9nutFwi3xDpuka_CxG_w3FmVFQ-yRVZp_gaWMTzcNdJ-BC-vznP
RpAddq2VP6Uzp8Jq0tqOdlCURdp_0Fe8Ut_3FL4lW3x8pectxN8UV-i3RlhsVc_chUbdlQgox9nu9bUZ_NMnLuKrFUjDQxI_UoNBRdr_nJlTwB_-JHAUzRpY
RSVVfQeWE-lL8jU_kQXLbMNdEnzMNEg5aXCloCvvlxtOkHTApliaF7V-VqnEF-UzgYhFpc-wpVIJt_yhmjv_qrKh_QJ7IRohyslGuuqFxU_42xAp_YuhtWaI
Bw3fITzUyVoz4o_ApedNN_4kSMzz5Bx_AIPUXKwyF3idNlk1q-__INQNr5hnC0gqwlARc9kU-NTVyVJxLr47t_VVlkBvvpIxwqgj5nw-2fVrINRNwet_ZNy9
2Lur-mEVClxmfYlhWmwU_TqL3zvqa-my_cRo0wUMd7XvJS_Zt_k3nuaNVV3S_hpkO-BrxIdN7wVVYHAFxVjf_uB4Wu5Fz7FxQxNqvw1Qju-_luV4Qzdpnx_y
AQRIcvxJdyVVRxhAjlFuS_gvnFfpRAr6-_-eMg07U-xuRn-xImlqqFIfus_oDl6qeuFlf_yrtdgmxxFz_VulQFez-miI3-onXUFlnCEct-luUy6r7ktvVk0x
yQ3fzzp-fMMz3txlVjTQreDzn-ClwztqE_TlzKi2-xxRNp3k1_0VJ-_nFwZU_iFgtVuo_eX-7T7kzWzB-VoQcfgQcfgQcfgQcfhw3W
}

