sprite $image221 [77x114/16z] {
hTO7agGw48JXb8HSLG7tl-rJqmho1RCzYDRyOTTzooGMBUOT_YgNQqtucs8zYfWlrBE0kLofbPMfwLAzzFrqoqMQcCwN2pCnNRuGKzF9HPYQJfNSz7HgDrnu
X1cvsUdKNkdyTCJkVjRb0NRF5Vy0k-UoUuJDJqTiVZfYyzCHcvtkYirFHsn-EcBpqn6RdexOSwsc6snsEcBpqn6RdEwAwVHqn7oPdOuOu5ETcOwOufslNqz7
xBJXvSlfY5MmzELqt4mzi3XgtqpdU3QNQ9Pn55M_u3I-C5PhFBz8HVI99cONx5oozaHkE58_C6cbo_UVw3rdHyHOG4jLvU9zvDG-OuAMy6L0xggH8dOjkjYd
MjVkVUJ46376Dj6DnoVsapFxZ0dFecZ3dD_DFdAg-XkczV-f8cxy4shVO6j6uIDJERVA3NQTGwfi7YOy73iNTz0XZ8b5kBs-0MhHEm_4XzZc0EIr_fzJZvuy
mbR3gx0Ahys4Cp-0IKzrAycZvNXT1B0yWl7U3MxrS01A_ss7en00f_O4amskw5iJDUsMgsRLfIh4MBXW-afQLf6yxvgQsO9MEFz7kSTOJQX0rzngWbQiGkq1
jZbKlBLMM1s0q0ngEeoj1fTmQekWfNnyrTOzfaUs5RZiqCe5G5dpSLPFxUNgBLRVRH5Dym0a0b2LKhfHxQsfZM8Mq4eUs1o0NVeHKHivcrBbjUwEe-Y30LYs
MYir6SBOXYENv9XiazhYYNo4hOfUMG3OQZmYUNHaghPMz080j_D2RQcDOmK8ai7wYu3QCAQ2Lea04-DQpx05WDi2cDk5Qpt22bfvTs1vvLgZ6AqWkmTR-VED
Od8-jBpPAhIMdJVu81QWUb08lD2EP3LzX0dE5ZjQvPoVh_0XBDEgqZeqS-_vDsDFC5VDpk-TLGzjqqTOr-9xbePrRjrBp9jLVOXPGZfl0JaFRjisfJM0zTyG
O_pUOMEOyBUk7BKSnZ34dzpr8UY0-4_ChXXGv9zQj_fz8OCOVDMV71Eq_2W6BF8R5z4AEee1INxH09pVKGCOfsEiu2WgByWRZDDzrB1umDKRx7Qw2h0yX05P
FcW2feCOtCVf4dh9_es13KnNedU0jnliRZeMeRVO_NGKXZ5Efv-uSOm58JUDyU4qZN6w2UnckYcCqyrZd6u2kvbk1kCTDeznkbcC9NBJ69_hynYdcyUk3wTv
ZDCHOmNiuNHNJ1pODzCHqmNig-c8PSoL6zUnYiduIbIFgJYTMSHVjLp6-Wy
}

sprite $image221 [39x57/16z] {
XSy7UiCW44JXOQdRSl_Z1fI2zB6sN-B-2uznHOtmiLHPkAKFgWnXdh2-GzGNMiaehuyItadFY6l6ToUTGbRTz06vffYPoHEM5ypq2KSEsGaxdIo0mYs5x9nO
GnPFF5aySJEtRUE9YpbdVi1WOfqAGAhwyhUCifXf0Kt8_cPYNSE6hQr3LMEeF9bDA4mWdeaUKDH_s982yCz7yfYuhjlCR8nrx9GRgYnqO-kpcMNr2whzNAFs
OAegmi95vMUMchQJcRkRAsMzJd8kb33yO3hp0MGHPXi9it8mvPcMJaXYKYVfkUul7VVJ95FDI2f0CrUHVzON--rhK48Zr88sYIdBSPg8M4q5r316NSHC0iQi
6KIjG4NDP3axcBax0Qc3N7YvaFbeaZ0TwfTTpWBc0dHSyRKqO6vk6LKkHVfxrC6wZ8HiNXVhpX8npPXLjHzdhXQoXDp4c5bzv66hWpLtwUPkgiAo7ZrYn6P_
7-XQvPAx7moepyNUaDHFXjJKxX58flC7Mr6_GUS4j49oC23ppGbXbdIpZh-ARASj9tJVhFsfvqGtxMOd2oOUR9V7TY7R4sDsr2HYPwdhItPEFDbPuJlxMYok
oXzphH7O4nTpwmblep4L4pvMkE3g6m
}

