sprite $image428 [233x164/16z] {
tPq9Svn838NLXmx0vVp_Vxir22yZqlCYXvI7GdiV6VCXwVMJeEnVFnhBS_owRJZVl8R_xMqnvscFbVMcd4uOKM-TpeXwTqoFEv5-1Cmx9ZKsvvrHOzLYrDjX
th9L8-ODwpSsvtrHSTLYrCyR72atRDNFMBNtgrzSjNbKkm7cRUhtCsBUjdv3Svv3_RXprKRKMsDUlrLdW7cdLetDQKaMQrKlZOghLbjXos1s8g9cbwrVNBL-
-KN-YCc5FBfTCgcuQerfYwgGKrPCZy9NhjzOjJ5B7kqrgbOAKUNYKqriJjalFnQbSG-OZNwBfbTjrOWv1gLLbKmAjMUffHXNR5KyZCsB5Zf4bRLCUzGgZo9J
3tVbGgZO2CtBp2_IDMXYVbpyrEYPt73zVbvcXR0iSn-1yehvBBLjMkOrKLPfZwhNIch0F5xDL4UWKMhhj9Qz_m89MctNcMhmC3OlWrQL8BNLdc_KuWMVLgNF
oqmfdgGG73GeV82Z9bN9M_Kw-xrOlZ5uFdx0e5KbqQeNsEzfUudPTqmpKF0jeKhldgsjKumWjSlk6weS2pxRgaxwxgsqgGLN6pGeteock5Mn_hvzKx9i4I-y
g7z0z0qzrE_HGBoXLK5pvchuIMgZ98UyVTT0N67nPJoMMY_cc3UaIZ_Mgh4vZRkbEAL4gKM2tA5ZxlOpzHin2n29CB55gKM2xELvGfMMVzsS9dK_pr4SxLx8
yZ7Ql8mktzet3CI_RKwjkVFSnb8RnvT0SKWODX2uLSzZMdkr451zBRNUdC4JWE85ZZdPgkUF5Ajq3BQjJ2KiCQC69UVLPedXDjMgvqzEBNI88fw_7VGuMO_d
rGPNHj10uFezivN6PUTfLcZtuAG2zYZ0G82adiF4PRU1QZje4BgakjLY0TjTe4h009-fMbns3cfmiZw6EfZhpO32JXY8ppD-3vUT1GqAapNYf7sD4YcCItwi
mQsQnyIYxs43kuV2jjQUHrLIM4fYh37SgldcHF8s7KW7TWz6t-u85gV21rJzXYfzd1Z6eBs9Kej3d6C6UyCeJc0l2dRTPuUn8MQKMXoRqiOa6DCewg5LENOp
JkgvcLDQNuFNA8F9EjUWCayUfjmAlGn-wRhy0n3gdAfQsEmUEfPQ79wKjZXZ3uomJ-Fabtkl6sBYs6-aLYIr-6Gfiqcl1CFl7bYofNPNfzywrHUJTQv1opDa
gQppp8Ezmt0lKP4KuAC6O-OdQp_f8MUZ6ANBLpDCqL-s_MEphijCpUnr_URtU_WBcnIWXdPKdTBOd76Ensby39LtNIRCB28QS9qqS9xSxabzwT0UZA4ZQzV9
6UUHVOztBoi5mdjikC-aSvOJJzRwQcuqwJLAAziS6UCew7SFI058Q0XFhqtREVEz_fJowa5AZAelZyYE965PPWbtBo-roiDODI1NkDa7AJ5QFnIhiF_D7m_w
6IpPlWqgkXNliap6bfHQy205nAOwi_zl9nJl-w0YMvkkXMjS82h-mWenTzMPWlN3WQKs3ohsLIOVZuIQMQzYV_c5hRzCf4nFgjEze5ESKMg1tGEWZccTlpoI
2OkQuZTdBJWP2xlQLmjCXppEPYUau7kWekQrke7Eki5BXTjt3X2Qs2GL-Ttw6G85TYyB6Z6bzg_QTL17tVzzOfVSn-yVbFe2jMqrVqg3S4Z4dDGp5q7zFtgc
aozAiGrE-fLuC3WpQb3iklAW0JFqOW1rr8vG8qMHmKdlnCU5XoOQ5DgzFAXZMezN5q5vKoN9RW2h7ZvhkERkPcNV-e40atKMr36zCW6ejwhMfg1Lnwg4nAdK
KEodf1QBaSYAwLg3GLbMLMgeLHjSc-C5PcfG1He4IH_P3AS707NKU5CmHM53HHwZ2f1Qy97921e4G8CgrRGgLJ5SvA3OW-iwZHeS7W2Dg52L8aNLnD4RYprA
BSvz3Zfg40QDuutMgda3WO_UcAxVD0ZbtdfBSN8PjXi67Tf2h4h3LhKw8h3nv3VClJ5H1ZGAA0OzgqgnFI96E277hw-CbDgVhFMi1dqV5DX2P23aZw0LB35T
umRHyng4GJ4g-XXi86PF4jfBx7RFDKv6e8mnum61GJ4gAWne84AImXBpQFU0KcFGGNDXK8mAL0aOY9YakCICnOo7Mu4QX9ep3mg6LJ3MsF4WyeK8MBB56rUI
eA3K82X6nQh41CQQgK-lDGWSIXWKMPeyABM1AXNE6eXsQDLbE5dlcD123BCMHkSpe5HwmXOcnnhu80KVIQMK0QYDV106jI5d9ngYwj-e4dvREORPDA-nx05y
K1vqCNa9IjH6gjJ-ma3a7wGiXnYKjxQKr1wRnsGCsXeHLJu4i8NGG1YKsdou1jdqlV3xPQeY4d4RKMSkwvzZYC1XzVZakjkv9IRsGNdGNrybP6OFt0ZACQLH
bIpTgk112WwiGVcO7JH8WUfAMubu_yi0DGwhs42SMM9Y3SedzDU7anveLtri0VI8YhvgtEv2gSq7M0Ga4lhgYNVzVnQ6NWcfKWSZ6ewy3yedz1Lf8N9MmdDv
OOC6ufpKOX-KvtJGZz455Ae-IdLJRgs3OJMdIdAcES69bYjSZtb0IbJN5qhO9YlxULex65Q1WUYdC84QvDpVw_SwZQZ5ruYBY71tulomwWQYJMUa5hZEf5K0
xpnQfVwaIvqBLJDTcTi85QdIzDCQ5AqV_dv-9hAtQvacNQT27ZjWh4hlqY37NFBl9HTgQm7N5PJhFjO4r5x0dVy17mIgDebQLr0XiaUxcWzR0HC-MVrP7uJV
gyVVPQ5JyOVMEZKYVyvQJ8Gpm-eRD0YyL8_VKFRsbCUVwpPucKoJgGXGfREOhSg_RawCwYbLQqJgnl0BfR6fb0Q6rP-SnN1pvbhLghjUi_Ay8obKn8uI38VL
l0_Yqyq90fsgFdfOeMhjWMehwEg7EPQmY9qhErp-vwiMdwfSIxVDBsabSlEqydkxWc7r1pK8O-QF6YFtIzBy7qIh5x8hqy4MsXjy4CJCgv8ILNlwXsQolrbb
6b3_vh0_QJhYYO83dwhw_6HRQUlHiXRqaLKCs3Vm2iAFfHFhRzkV8SdMesQLYkUZhoKSjeLYbzAWFAhMhyKqKp4fH5KhrIt5wccDm-grD2YFAfLMeax4rcYD
jXr2pTXykNOSLd6SjCadCE6focK3fLAezlz1bKYyiBs4ixRGA_ojwVImOrBNl3KgPMLKFtIizjPbVpZgh9i0irrDW_AdglLk_21L8dPnqcqoRnPK60whKlfx
CJ5gV5EUn5kq6bFJviR_WDgg00rwGtD2r95LQWxgurodBjPsu--ihuPLeCdPTCu_ystaxC78Ny_UkLcZNafPkzV28uvW2o-ZGHWrWl9a_GlKfahiJSerC9YA
YFgm6cQnws1YrBQsevgNBZje8Mhg495r7rRzpBb0SsBKmqpEMjKNtKeFKEPGkQ64VLW56dIT7zuqnwHA8P_4bQWwA9KUG4DQrRIMAjCLgnRNhp_EjaSL2w_U
g3dvYp2pUbrCZDgfJVA0grIPg4iXn6BjtCpvtfy6eaGiH9qx4TLpe7ZlzUwVxy8aHAHK_821e1V_0KRug34HzqcTg5A7eDTlJdogSbMYnbI41ODU7nEtgarS
kDFn63qF6Z3VXZeV1vfQISw3ndHUx-Sr5gBMJuiHrg1BjAeKwafa2FJApPblLLEpMXM1NhavSSmhQd0G2FJowSotAWQzF6Q-LJ7eTJ7pg5dGyyrvVLHhLpev
ptjz37g-Qg-lIjPkW1dh5uDYp1kW8j05BQMlUjH0K9pEUw1QkmqcHhLs0qpmjWS63PWtIQery63iJgZMm6Xz9rIju-Qy1Me41KlfEoLLAqZddL2r0imxeMgz
BMP4rNfZJ2TTMUVPvda9xlsEh1u_dyt_
}

