sprite $image152 [143x150/16z] {
nDc7UkCi58HXTSISe-Z-h_Olao8PWpp8OVVRNlC-0tRQ_bRczd_Ehqb-_82zVSRSnBmXn4L8Uv6z5NwPukRsPhzZETzN_DG0955EalZGBH9-mq999lovYJoX
vFip2sMFvoyjb6pI15HpHYAbFSZbNTfxa0pJ6eGhZBauZEwvpoaCqzG3As2yW6dhWPc-J7iFO3gclGSmbu-flGSmQuTXU8CZO1fwyCWnQjfwT8uBc9OUF73C
OgjmWmF4Pa7Mc7IDsuFmn6aAWZQE9sz-DlJeuv0ZWF3JJT2rnXCE0_04O7PECCaUC4lMEG9Jxj-lW1ur3FOwFsLVrOcWZCCa2y8qzFquhqPIlGWN6jzb3bzu
6BgVnjNTtEjF3SLjJENmnIuz7VqupTFOTrqVtEp6H2XTq_sXQqqaPWYsVMPXxFhLOFMt23cDpd4pNpZCwjifJDraaTYwCuEWsN5nK1ElYsr9SHWGEL0oaUZ1
YVEnI-lyQ2RVdlAvZw2d3lIaSTlJYfevhs5h7uzzP56gCT-VGa4JU6-e4JmIADNOdYb_SS37LDnAhGCYtHMYz8ES43bcFlAejdBhQ32lUfK6LZugXep6rkx_
i5qqBw175U5Huxvd-yXnECvOjfYvZu0TdZ99rx2C9dASjOJnDInXNQVZk0eY99Za6gkSYHmhSUBoVs6AdESw72LFEAMUENnO3LuQ9onVUSef9st3a3-hUIk4
vJiptQDes4VAMSW9hpbHcqVNiEpZgbjVSuARMl9y8yv3pa1E53ZwQGct-AT73lhh9q5RVeBAKK-A-LbZwChhiF33MLtao2V5wZZhSLeYHz-68SDPYnmxvd6h
sqOimrasOPuQZVikzyoPoXmFLK-4n_imSi-FhC7B7dnvmfPmT8q-pz0nsrvv0iXHDBxVvepNTvbv325W8qVG07jb1sT-TNcOks_aN0PYs5rEx3xpxNMgXjtq
TCbfbVFN6h0ReEIjmMvmXUEQfXw4qpiIB4eSLNFVCtHi4AvEcPDYwa7Vd4MzFNOPs7tG-lt1bBvZlRrrLaTs3tJwY06RtZYhCgVUCtvvmirny93PtHDBdWgx
U6iS21pDannNZ_fna5IyrHMUwQN7cAGnv5ibZv-lJxzMZOCquJ4lUzZiiWPvZQ6OoPxfspF4WaR46AvIFRvqtutmxSYGq-0vKpXmmNFwD00RbaYHspf7JNCf
hHbe0a2FpTrHtm_3q7UJkRaB64t3FguqO1p8CFVTkJ4tJSOYQ3GFs3V8tSBuiyyC_iwbHhXJ-daPs05YSGrXZROHa-jG21hTav_TlxBwe2PWcBqJz1GCQuvX
geOrrq3ItCUXCbrJBq9zcgPUX5lP0-VVPkuZjs4WY8BeVehW_M_hfAoohGPd6bz_vwY7Kex79yayPyJ7Mt4eS1AQFCUFZwKryPEoxuMzbsR4DNxeC9_caREV
lX_5dAOqKGrPZcxntsi8fD5rrYvEJiF3KKKICn0dcmQUJiX4qx0zSmYcmMTpGcbE67C8fZ5dG2pDQRAcqfncRIQDEQT19irfs4CcZJcdGI2DEFxR_ZJQA7Xw
qpYF1tId-VsHTWgUxZJEum5zQVIOjl9eJ8DucSRx9mC0wzECmiS4B0KPuxDtuUXQ9w9qggddSUAvD2XDsUDnMkVnP4-9HFreSfgw1-OViWMOI2FFmaVRdQRB
OvObJjFkyGwdyMW0pNpU3gj0lYMnm9DAOr3sL6CF8Op72f4m2P3JB0Pn7BCtVHfRE8r1aCDOL3SXpTfjG1M5C2sZE6Foehr9uENBU6Dh_FJ7Jm
}

