sprite $image53 [130x84/16z] {
nPc9Rkiw34I7uYPHyll_pts1VRlotjOeLEPW2rODe3EJnCOFQTq9JuHiH0p5qv0Huq5qmLFW7Z5E8hoX7FA8yKg44MhH4UC3nJf8Zv68pYYYUQG0bJgGfVEJ
3hK291rg6lXl8ZfN2b2h0zc8SOiOHhytmNSpI840fJha1jRfa1judnXAkovW90fro0tShSD-0V9GLpHmtr3d1kuWkkmMeAAPb1fOgqCMe5Y7jac0tCmD3QpG
8GbGgqEUu68TSWDhTSW25EYG6bX33ADT4xplUpi9KAv3f0JLEbZhip93_Xbd08-KeL87GmCqNKMX3WOT3UIpA4CUQeCijuOdwN0cODFbGf0nnpDqCEWIj-dy
B1rSm3h5FVepT8XvGAt1RAWFTwhMOQxZ0CYCqBkhJpM2H9aEiOu7UC0km1XglbG0YoYwW1ESY3DQ3t5VMgD3p7LSu8BK2Eh1mwDYg6CTB-25PWhgDdXqjAJ3
_lDpWai72dE53auwx1SW9xXqeDaXqpmDzSu6ll3u6FW0cH49n7Mvjj_G8JwUlnIVQQu4NM8wUnhgdUUVE04PlePQpSTewPVyDW4UMKR3Fr1lK1rgKngI3hi4
c88F91tWtPnDaDPXomKimoUo3e1FriiKZTZQmACJlaLSm2AWz7vhGmCPTpXrO3IxVE4-Oqi3_vkAkvmwyE6D031ap1q2f0P-guEwTWQ4aWwR6fX9Gysh0qgd
3ZCA1FY4Mci2A2KTDapmFPef0GnG0t3gi6c2xyD-fYTXmWEBg10Wwm1Y5hu4dR5fWkz3QWsDcONmCjJx9XZtTM0Mned6t3V1ztKGa33QgGDPnCO6tjU12Er5
Xpw_RU1Kx8NCwDAX0Q0vO-C4tnzgeZz6Kimvutu3j-h0qluac17_443mQwWp-4fm4ka2yWJlrw7XId0HDoPulmvdWXTMWG2vcP8Jl4nm4TfdId1ES1raStrE
q0cbjFwI84rm6JpMcI3z2Yv4OysvyWJNwZ1J0ujfu-SD_1y
}

