sprite $image9 [236x176/16z] {
vC-d4S0m000nREJzjmtKNLXwUMsWURK1CBzhx1POhZIMWyYJnfF4aqQKH9H4b4AKH9J4bCAKGfJ2bCAKmfHGTQ7cNjTS1M4e32iWi9BS__NkEHySOvUHfsw_
ltFoRGKjfVFIG6ahWVhDj7YlJ84QZjPRe55OdB8AsCOyf0EaqOE0oNEjG5nw3ojCpc9nDsjSYxjQ4P3Uonh7udRMiFReGUJjnFGYAm9KrYgssKLM7XiwY3B6
sbl7tteA39Km5NLwr88XgVsfnwQ5A1LjUjZSC21PrrDq2gIfljKlTJ0ryFNCZTS05hwLgX3ID4qrC5S5h22eSUjZHdu_0ng8wZm5h1mMl3N5XkqoVPOxSmAS
jMA4jLgPd7n6cm-SxsNCxTaEbRUQP7_OKjFCN9aJODsCx5bvB8vPLRJFxW5LwdbApJq1l9gPP-MnE6e5HElabHerpPHZrvbYvbfvB09MG7HdsEAxFlFtM-N1
RRUMfriDRodIv5Mv0TYuwypSxJM1OwMnY5eXsgcdLdrjwiGLjNv8uLXfBEBMtM4x_yIgFmxdqbehUN8hQYyfSB4LK2q45efv2fNm9XMuLXwBaDLZ-5Yn6g6s
pzCtRCL8AyGQCS_w4xVVyYaTOiK0Ao3Ex8FVgVZ3qh_E0EUi66i5LDBcj89VEVTR-zUPKLOmjRPUAi56csVewb3yYTk_pfotue0LOgkmrTO9sWthH0ihLQnh
PQa_KrFM6bq9mcPzwvW5Vr9TcBDNgGKu1Od5m7WhHAqN3xh8kq6mcUZlv1hhnZaCK-U8pL3NFv1AL_EbyGPI_LLhUxTwN3EWljSWPWGq5csDB_kLJwlBNKL0
BxTMRpd81Fk9w4kcBudWksNvFwqj-RTu2DLcPrKoQXqz9wrBPYO8rBEpAdbrPTgXwidVMF0VLUVTjR3plx7YFwcd_HUUCc3efuPBufVzr5uQDFIl7xQe3sve
TTnZLt1jnBBViThERyIrjRItVK873lqbyFl6vQ_ePxZI-D2_qkglCVJewKkin5okBGC6AXepzAzFaTRhyuUhn8h_jQtUqva_r-U3poezzAyVjYr-iZbZTUn0
5GnAzSHnbQSCLC6mD7wopS-upeXYN2BuhDMIKtebf9JAqewFrZvyCKOCmsibJN-QSuLRSQY2aQcDXkR9BLVUEdxsHUYnY--gcnVMYk5Kc2b3IB-hXDIhSZSI
oJ0uCRF0JKtnfR5znWSswDRe1nJLp2JoxgkmByUuDORClpXFqGyesaiQiMfafwJFwCvEFyBQLGwyfthUMacYprZedUOf-24WuhQEiBPv2fGQjPPUHbdjBJrb
xNaAbYdij0onYhqd0IinK4ktbxJDtB0jnCGTjzf76hPMtz7igyuDsqPCt56hs6SIixRqQ5-72W1HhTpdN8YTva6hVQKXQtwqKrAeVPVuJlhkyd3SAlQT7BNQ
xexyTocrON4n5Mx3Ocfng_tig1KpkLDoVyDYrlNtYfITOHkqglrC3rbB8NTA-XiM_QKutH-s-RXLx7T2MFcTaaugcLXEsl-0I3bkjNK1Qs1z_ftXl-N3RrZa
hMhhD60DBFk9LMRTLxICiehzJGBMoFgyI25E02ZI6Ajj9IUi2Ouq_f93h8smgcqMiCRMvqLDgMzRJblLd8BMXP36Kitdh69U6hAM-jfILhKnMimdh69-wba3
bK7_gGhvWLL3L3CTPrtqIVyXHMDKCnrchQRNMiMCmzxVAaPqcRMDj8fH2Uvl5IEJsrlLwEJcLZkIhhRYfNouVfbLx63Y_3ZVLLQD7sdSAY0Q_f3gWDyHw0Ah
M31vFZOIyQGIgU1EYGNwLowTspeGWp4GpgK5flzgttrCP7iP_GAdWm-aj0T9znCBmP5d9cbazP7Flo_1aG-IEcGDjEEb3hWErwvzkTpgzZfEwf3rHEswNWzX
NsiT8isjRfzpNeUiPrrvNNT3s80xVLA7hDEvXYOXx6YkeLdOEfThQ1mOEzjhPqurDc_lDS0PMEVik-pCWnUmqS1h0jD1W0t4cLBCwLQJrntZ2yY46c5pzMVh
fs_PJpi3vjGSEpzwi523XHeiFLQemK8D5cZHGWqMQh1GWuKMBD221Lgqq88bgeWA1L9LH8K2gIgWgWAfwf421L9L87K5KbKWLGLILG1r1L9N07K5K5S0TGrG
r-1q3KvNuNGTJDUX13V9-0u
}

