sprite $image247 [241x179/16z] {
v9XPcl8w44FVEf5AJkz_jNUYcEgIlp06WyrvwX4udwHClzqW2NBz_HP00W39hz0buH345-cwCYVN9G8pAnF43MOjje7OWS1ykYIm3y69opn_od3Vr7d2Cz7y
oY0g86rmtJfeaWRMvGEw0nklu2EwAXDSHUQGEl4LuzMPelbrJSwWdMxG7R7KQuEkCwLlr1rrnGswGwwuLTVPPlILCt2djmRT4JlTrER8JBuqfHXi3b_NpG4m
nTdNTNC80EF7QxeNmt-CxKjLGF-VWNrDDHWS6_H1ZgaIdE20yLBLu89jD5zJDOOhXgepLGyH6IPUgZLUXsDSR5X3l95rqdY9NTwdktMFrvahNlVzFEMNnMlO
XMTwwx9xl2HvyOrfZdZ5FLi4QAMRxlQoU2tH3ShRWF7clYHs8FKfljGZC0qtqc7AwylY5NFT_ihFUcXL_YMfSs8Rflp9TIvdGhnfkcHFPJwZpYLoVxmy_BC1
4MhxqADp-HyYZRakJQLmMNXRcTGdrhb4PFkzZRR5rkKVLYkbY8ZGr3zULePho7NTjWYBiofHVezlhalalhHo0Ci5KEmr6PGxppVNjLoNfk9mkI9EcJAJ1UKE
letJTTrew-Ez94wP0c27xwXElksw86EHVRo1E6MNfSoLE_ZoURfKkKJhiWUyrsVbfDVzV7DT48wL08Ddd3BXExxejPMt-9R8lYxZaJajTPnoLDRxVKLayOPM
xnwsuYdgrfHDdNphTOa8LTbhytAuid_t4b-xorU69Dw0bS0ZlQRUvMl8uisLjJPC-SM-EsrEucMGfxLD6QxSsrVtnMiAVzioPRjIBXryw-Cj1uIWt7wA0crx
WM_ZUbMSbYd7gyspihO-lcBYIvePUJjXfthAk35bwhs-z1n8yp-aTlTEUspACeIZrujz3PdlylFpWuC30ljJthRjmIcN7Lys-5R42-eiNF1dUBRTGg-pARlt
lZ8w-SAAUAehxnKk3Yjk70M7Ubw-VzDohjkDmZ0GBZTZpSZm_c-x9pJgGRLZK3QTltlzCXeasQGtumiu29DANz1IIUujZlxWkp9PFiDxgncPkxN1wpoDmp3E
gKjyCyfUq3_WvGKkdZ43jJMCvMamZUklIwlmj5a9hEhvptdjzxNNXpmE9-MgjgCjgYRU8hnud_TYh3BDmrcZYXVlHvdjno4Wd-J5PNhPJJeyy53_XOmlZZNn
ftZr5QzFHQSIi3hUkU1YzjgsooYtVsZ87_82WTjzFLiyKljjQjksM9GzS9nNx_1AH2XvCjoaxOY0QeDNl4KPyL_nuWvlNfTbIQlPXvnIMaLVVOHgzWOMnr_0
s8atUFKZl7asI-TiFRSKLQ9_uXNgokg1PIVxo07UeBtf7DhS_YtpD4rpoXtYooZNm5raRUeJlDatNagbPJ1DsKrUXDwSDdFbC7Rsa1dZzRXzhODJ_OoRpfz7
dRGxTOqgmsQn8KSFe3kyCOS7iEclQUP5eD6CCAk-mNsd2JTvjSihDwNJ6MWfw8zUAX93pbeQl503RY3ZYfSnNY_eoSDKJPn8ZdTgVhXyUGQKMVk1vsOiE2FZ
abV_ZpTd-xq5wLY0fyIALw0kmoYTHbMV0Q6qUKKDs27_6MzU3i9nNd-cQzKNppwUAc16GNSIsLnTYxPuyHtIVSz2Df3rbTxdNOQgqG1qJxd3eloi0CtBF4tp
mw_UwEKbcMufymdMifl5JX1Uy6gSTtQD5yq2U7uSoIgWsVpwnEKbh-WtC8GDzO4LyVoEmrahgyvy-WsJ_vw7AISRli_xX99NbptuwJe7CEu3MrRUwB-3KzBk
8Sy4gPJiTunBPn3fyXx050a2wpiDc9C35ksFNa0l4fDqaF4YlmPy9FOkiNs0OLw18ruBWwDNkXYzX9Uy1am8gBU0dRqnOA7-f7H6nIlq9LtO7Rr6bLfyoKjr
mFoE_mrYmxqDl2xpF2-sun-ZGMwl-EHqujKYNbWyS0ts3T7Y1VKNCCMGBu0X8TxbrsC6x7nrbfhdyNaWK1i5Nm6vo2q1LiuUc33a3d3qFQGyTHypThqoseuF
BKg0sdnC4AUxYLnubnVK6jY8FN9jRmpOfswXT3hlR3u-XERmpIBBz5q0UfFNxAs0syYLlJ5WJ0vuqgglNZLUMPyrlgm_sz5tdy3TSgPw5GDk8djxey3q3i-b
Ftfbz29X5N3eTdoXsW1MlaBstz2F4WEZt_22evUu2faXCHtsrZ9WJsp8pjuWi6yq4mhwerSEZbvnU-q73O9i80kLzFR6YOyTVnodrDhmw6fwAUm32-Kfa8pR
QmPRY5l8hQTLdpWDS_Q3GETTHELiDEDQj3zwZKhtmkA1ZOYznbi34sTat0zDdhw-leQb_Kr-qvgIBNWip6cPbnMbKBeLC5eaOFkB2bz_xuiztfsryCwLs3fy
7HhIwzyoMQRjbAVpCgfo6N_Thm6m1R2mleRgsriwm8OSK9w_VdJWD3HVFdPpEWtVB8h7y0rRMKYx5Joincg_SiFUKWouIHn77hzEiYZt3jSJclThvcbh-BPt
5W6gAbKD_uQz1lmnuZnzEUGbFdgjxh7zuYw48f2Kyf44g-zhNWyCVW9v7HtokFPVv9WAxezU9X0Yf1qzGyyEGy0Nk0RSjJYEd0Q7FFcwXdYWmEXb8hKeS3hC
0N5jhsc_8euZpuEFifobClOsF7g7rmQmoj72QBnumB0_QvHI0nlovwFiMvJgEeqFscbjR7ZCFk9ipMwQCuiI94GCl6jl1MpQeiWsIIbnCyg78oHTyjeLiEY3
euLCUJwQySshk6Ll3HolQuXTv7Wp5b_NFihu_VVblDgIhohBSGIoiYYwxzWIp0SvpTueRnmPJ3ylU-llVdhHeapvEKoDItOte0wtXGmUE3HxuxpnA6kHu-Bv
eJqIvVQXH-gzlzQy2YoA-_Pk-mlXDhAU_xQQfHDbpsjQ8N41KNlVhsjism-lDYV9gscpDtgPa1-IbiBfZIF38QFisqFxJhlg3KKPq_NXEeuN6MPRhuBszd7Z
KRRhoWCUgr3vUntqTPr-cUTBkZIP7i2F4MvzqrxTRqc3BOgRhYb9KNQdJM-K9dV8ezAGodeWBsl-2tlVxyfbKwohbgBtemp5Okinchn6VEWDU_UGeiGlUcYU
NaUPvGWkUb_19UK9Z01l63S-RQezjJMoE89KhVv2FEGk1NCMnGcNONi_7sNezc3Uzi3Ys7bfMPRaFXRY0_P-EihKicqK4GGMnqee1_3NrzWxTFuyxlkB8mj0
HNZQD1t0YhIGqMPKpv5nvJ1oAJcbhCf-b7iMcn2tL_V_5iDTkSYQSYcA_kBOsOYC96nlX-Fla7LxlaTPyERYo2TomGrxDOhx-IXpsrvyYRGRvVRS-g-Riq1k
A8QXO37m94ltFst9LI6Wr6_6gPKTBcPdF-bJafVGdHGPsfLDYS6H70JL6NZbGwIPkmipE0Rpy_A3OtPkGaGmi2fJUNqInBbDaxwFodPHc_NoykVihM6psMXJ
f8FZQdbvPLXhsEkbqxaREgzFPzZOMaSE1yV4DtGJtmcwpE2OZ8w6my4ncv_meIkfhZd3_EKQQcvcZfE3u_rpbpkmnPx8kz2gtB-3mttOKnnJunUVlqFeBh0g
7rolsFq-lRaZNw_ermVZochIJszYVn4XVDTJjgROxGwss0Noygloz-bDFg__AwbnUdgpLbu-SfpUj49v-TEvuToiWSdh10iCZkpQw-jWev4BvkLNPJxlZIc3
q2shdFlwge1NXjJA6sYYZ4otNjv0PDGPKbGta1Jyj0R2zhIlUWaWVqGp8cy9b30jgXlGmk7hrJ198FBMhbmtRmudtBmmX73pqjYei2VKLIRorbwkYRorbGdV
sig4RZrskR3V8cUDnMyMd13sA_4A
}

