sprite $image53 [260x168/16z] {
xDU5SIX140FH3uPjNTLk_j6QRPdvKFD2wD8SZAK9a4OoxbG1G2EIUA85Zy2g040LIAemyGwD09qFz75qucDLuDW7SSwddGIC8FCW411TWUzeuq0alaS18qY9
822x0h-W4e1wS06h0e0gmHuhT6RG3x21f2c8-LG1G9K0g09Rhy1YAW4e-Goivsx0bBi14y4ZC0MFmAe0eE0pC0MFm7hm1coiuWJBF8Y6XLPWa_ho1OAdC07X
5TYuy-02riUS4BimzmYYAuWzQRaRC2Llm897OCejO9h_33A-5Xfx9sOOGTP5S1XjXl_3ZFVaEHPQ0Gkj80v9oGKi-GmiU0Icu0BsuHcaLvY4XHx4DEcoVFD0
SfrPmIYn0-3H_dVxIhOfpxt5Ive_gVjRmgdc42nlGq6EEjxTRVE2SCATA5ZD0826swuKaW40swuKai6PjgiMiXPE3fjg8HcW2080JRVzta8ow5taB0ZPIGk_
CR0OhBoh5f91T6RPJWlp6uFcqPiFqLCBl9CMFWoOHsyHWuHJ2tENV1s78G3EATWYWdf_Ki2jjF1c4AxGF2YYYPvQeB4H1SEN3veqwXGHmYnRQS7S5Ku8rZHC
SKR8jARFQK6tU0eU3_VvD01gX26BYONhDdtIul5u7ExU2G2fXQDtnXankJNPG0lcZpF7OUxM002reOSJZPWQ9YAhRzKUZpU35mLv5iI8u2xSD2AGNzE2cjko
PV1CNbPzFBKmZKTCOeiWCz5LjP04aa5Iw0Y0pxVGaPgJX_6IMtMA8FFBbLrF2ZoZYokJHwWs5LnjgpQFHytWSFSffmPL9M82M-Y8oSevBQnJ1ZM3rCBJ06pX
E4XbH1ZIIbf80ZM3xreWCtJlg1x6DaKXjR1I6TGCZd0tXPC2UeGG3-E88GIvLQz1e6QGyHoVnKFwPEOuOG3U_jXcIQ1cK6f16_Vm1kfF1kybOhZRRVjXpQ3A
bxitVCxF7eCQzPD17_BPgfSeWsHGnrCBQeFTbEbrVVuSsnOeWuf1hGLYZs02ieXE_3csBK2WO51g0R4z6Q1wTFN9UYCjf0YkC4WAzjH2woS3uT7rTNs-anOy
hY78H6xL9uDfYXhXrFjdgxQxba7cwoXIQk5rVGv5DIUFpdeBBTYLDr1JwDadctHIyWWb5eJyXELk_J0Jn_-SzxI0EbN25OU73X__y6ERNHL17Kyje4GO2a_j
uLq1SgjUKmJr-8pgXZuPUuG_6UHMVOD-UE4Hr5eG1OzWREwAy-IIMbYp3Ehn6Nk4QEEkqDf0ABRg1Rh1VviMkaaB4yL1NG0ABQn5eDO2jWXhCDfP7uKMLYk3
-jZMJmQDfa0cZsst6Ool9xMWsc0A8cHI2xPc6THRTGCz2GX19iVdTVhXVz-gdufyZys55XOJGJq-Cm50io7o7SBViLN_U3MuFYsSQU5Tc181DG1njpL5K6i1
MaGeSsg1UjxWRt0e-d7o4vRkePo_pW9gZizkIucWpdXhWOPmZyclDZ7XJ6xLAvP1FJuJzGYJam5soAYvtMT3_haMnDyCf1TzShqogCVdyM901fdKmi84ClQ-
mPDWzeLCtk2NB8Fws0OV1WXGRDKt6OolQu7WMsyKfK8BgvH1dQ-t5ZB48bXirNVfXzUreFXXmAnSRDKB4yY2a5JX6L4gjB2Q2EgjEXcS58fZsxtsm-itUCve
eONrog3-iequexyTstv0u1_y2EhnEIaqoEHMVRz-UFtOHXy6MH3v2Sko13AVFuOa0rGfnkTrH53deuKt3EMhMZ2_4O5Q2_aWHAcumIzN1hKMiYXoMiW-wRPa
6TGt-6JmIq6GkvlTPaF--LQT35W-5FoChLe6zRIG51A2lsAN2SHnc-GDlcRWRhQK2EfO_bPTC4WATnkChsk1QWRkjcOPr5iriSWt1ZK5NwOCwcCRSit0pPOK
GQs5Z7j5mNmr4TJ7jcHGK5Yp3EfZMyrWJGAr5YuoE5P97jjg1giYgCVdci4U158BxVzYy7Mi5wyJ5zx0QX3Y0eBLACHM16eAKHBOYqBiX20J_ub179latpCu
DahDm8-zKZ0ujelznk3OCjyP7Dic6SInSSmz_eP7y2y
}

