sprite $image66 [79x113/16z] {
hTO9Zkmg30LG6mzWu_pzB_UBLEZX4TG5ARzHqz7r3Q26FmUr47nisDnTyJCO5NSpSvCFO2atx1ml_113iOPrptDwM5gdEgZuiBIViryXwe1T0NSEZTY0xLV8
PS362jSFnnmqsIzjlyBnS6nME3ySyuqL7vKsWlpEZUgpNk5wQME5pqeR3mqk78xb2eVIdbJ8fOxQVeLUtOTTzokqgFuXa5zS7GBkLtXo7mkOFMgD-11OZrmR
zv6DFOwZ-Eaz3zYmu_1JYgUWr-CSYyYr1zm6QnnV75dz1zpQitE9HQCE6ozZdGCYsmLRQGC7bDpgAjXB6xc4n3bMA-nxZkaGY8ei79g-vy3XnRMDYq_0-Pvp
3bFRU02dUuxZlpYWbAL_ux724PjpZFpQs7JOU5xQdACN1ubo7S1PQNFksXWm9P5UuV2uJlQSS8a0syP5-iFQmGasvH93vnWI5VCBwm4dfKquRXnqBg58_033
VIXjml79cGA-E6pfsg7X-kKTDIRQvDoX071RbeamdJSvbM8N6B78jRz4-EI8JWwHf5hiS-V6sBcMMQcsbOzr3jh6huFIbatNmv2pjHDu_Ct5DzS_wlKz4X0H
jlyZyclZTOuxz_eKnFqhKTtcqiLXIlXLgwulYyX0NnmJ_wpLLpd-XojAr3dSukW7Hv95jzFnm44IuuznJS877C700Ns2u-US4CyvNkU-txk779-So2-kIUb1
kg80mZ_IuVTTMUFwsmHQ519TNzRq2TV-4fLlJaNqucYJAmgeVAKJAOyu91109cB2Crr-nhMMKBXnFTtgCUvx2WFIoH79AvtcROvBRXpzIAVBwUftEbNuUZwr
8TJJBNECm3a3g3AWqlMY9CwynxLW0Y1P07FXHDSnvkNkSceSS8keZLDzIQegr3cixt3aDTTy7YvivfLEzRp4KXOvTsUh9GCmzOEYokMLJl8YLwEQgnw5-iyJ
j-duVQwwPTTQa00fqIjTxiTudMiWkri68EAlT6nxwPhdBXecwNoRa2r_7sD0NkLQG3E9aWWI8Q5WWtcRQw1uSKCa9aZVxmpYsr-sTkvQMN9OJgt2uGUXTQvj
N3YC4j8tjvUkW-hP3TkoYPznVUDIhU2vCIvoqRW1p1mcrF8jVefowrbngPu8KvCME21htXXGYvidMEK0nADEDlRpDLxZ0BNUDcZErVdzT744d9DAlGzenPnW
uEwn_qBWccc5KgsycIuZz9bNQ5IhSEUcqGuZ-3MOxolChbQvSnEiCWoJokGRQpMh4VDm2hV3Djqu8cRHIhhNvXMQTsx0d4Pbh72C6BUb2VmnT5TXU8sRS1dX
x-6xZOyO3qU2zqR6ZIEMIXihd78DYw6qXGg7T4DfgnL633TgTRJ63swuKSkJMeMT6s_K-f353swyKLiLTixfcTLV_wWH_uqtQh_2esQ4JmsvlO7z3m
}

