sprite $image370 [260x285/16z] {
xDa7Zbmn38DXz80_gTdxdpOznlDiGKrxD8_mkKfw-RD14Y_LUI0vvGPsPex1Pd0CZi4nE0R7u1Yasq1s1gbN06Gdu5u36p3ED1lOa4ovWJEp38x1CJW6no0w
1fO-jJRIBWQuaS3ICi19fG7mtI3V8JeDRC39Du5U0nliJBV1Tu5wWry4F8u1Khk19TKfY3SCQ190RncG7e67z6GG9AeQIh0Rn0XdcWniBuKV0lecq6PWaC1U
nw3GO6s59L1di1I4CyK61bq59kepi9Evn98A3URPW0e2yOv1B9m60Rrd420D0rXU6Um2Ks3WXR0Pn53pLxID1CjW4wWnC2o5RCUWnc1JoBO9gWnMjP0bK6Qm
5C10De98FGO6IIIpnIBt9i3NW3DxOYStRoHwook1vERpL_InGSFyrI3UDuYJkRs13Mm6pyUWmE1P8VinQ34mmBD1d0k1RswmAsGJQ9X1UmMn3DOnk1hGyKV4
TbuBVE7kpfOTjs4WW6RFHNVJ__-tMLmUNNKP4AtnWqmy9hEV8c0G1Ean152j3ImWCW5rlkG4q1K2r1D1wn5cgu-gMfbGvuuQWGc1rBsZPkMH6LWYQ6v00gM1
28tHti0Kt424Yzpw6hY2F17qBnNvZ23xF3G3eAs1AyWIWRSIHlyg4JyC1EPrKiSAYNnIK2tGps0RodI4AWn6HmDYCp05AHDeQa2-ibreNIdkMWQrWVn_zEya
vgtrpkUEraCp0nTmWsZUING39RaXe9u6yzRwXaADZWRprhglYyPTD6-j7tn4DYBO6RY2Ae5kfI8GRk2jTQMjzMO6LXsvGfK86XeK2baOc8hQtToPjzR9hYDg
knF6QMlTKHXWlvixA0pgZyYsDQ8RU1ZuP4elWoGjA0q3BvzRtTn9qeBgC52ZCebX1fuMD16G6NIfapqWL2G2wVluhTzXioj8Hs5019eOc887H27GxQI5F5B8
1BpDhYu6EGAfJC0C1BOg4d6MW1gIkXZa2ae5t81irqYi3AHyjy28-6fbm7gxe2U2pI3YjZJ15vafk86K2U3R8D2eeUmAAiD0PCIt0LRE2fO2gaaSZMGHnCu0
6kfpUSUNWWe12VT_EaJS1SRY1hOKN449WNIN8UAH2JX60uDAWVaYU1msugv0ZGu6jK8ky30W0QX1bvqdIkLXEqR_6MfWa2u59Ri5DsXnqC1PgUoBe3POk4u2
3nIK2jG6N7Cm4w-KoaCvWHjWpPnGr4Tca0a0RY02gxRLE2-LFGosLgeP27U1LGqE5PHk6RKxaVkn2AInj46zOL2-QTxzcWQFHt5IAcS2ahwLJ61XWrgXUWnb
Mog0_vnkLMBTLjOkOAJHnI1F2pd1KAMah_LxYK1ju4TikH8Z5hxcdYja0hM1X03N3OLSmNSBbO7NYWqC327TBKZCb8Y0D1eOk49-o0XNicVvEnYumax03CAL
f4sWWu5_JkuIWIK3_uuEML-nWO4jXKt03NOAkqJGpS3lTxg13V0zmi26TpiPq0JSuA501FodOR6xRdZBW4GypjdS05Y88Duoo7UMMEjDUWBd3QJqP_YRAIit
4-S68kndv8ydhTPCF6KWH6aWRLN2Uit4CmPq18tiwI2rQ2RM1dx9G-dZIGnsQ2RM1cHs6ngGjL9mM_ObeBc1tuoNlo6stZSzaXC5PGG-hsHXO0R0QWQka1k8
4Xr1kyUJt03KafKoS6GWQkZfZKr0oGVe8fKIC4MG2pnYmHIGbOfXbT9oLUBHjBAcuMBT10QMh19TmQ_iA7aWG6aOBFEjPkHKGVOmbWZa6SC5_1DolIendrRM
hf48DqZ2m0qY5Z0uM0goQmigxpUuW1k0AnZK2f8eBv3A_G8YhvIaHGno1Ohf2Pll5_ppq0tkB2jNYOGI0bUGXO7bnnNcj43EbeB_as08kupn50Qhp6aXM_sb
WRQBuQwWeOd06CiUERk1a3uq2ieJWOV1cWOaSeFgeT4a4GmJkFkjPU0ATioA3A4E0nlc_bhCW8GRxEOHvrkcPnPzwkt7Fm972F0H36-XkK6U2Dm0r6U-fKnE
buBTu7hbjLMWoe-V9s06jO8DPQOASe4wFtwSW1lK2dS1CwZt2yVvKPyaSCFS8FaNEavavmj7-L68-BX5487N2MG4jXGqIGHMOttC5rIUNmOYm491Xs7WTMR4
7vyYSDu0Rk3x1Hs6WHj4V4WOd3Ue7v6YHE10m0r0Nhi8tZ2eh_jWaWXypwMXIzV0cmQa8ypt2yuI0LrP9dp56mQo5jgv_SBd33D7_Bo1adFM-NuX5xZE0F66
WIYl3dvclx2VORmu3CuRK7S6rAsc-Nw1FiLvUHYSDx0Ph6mfwAKmkD209S1hjJBpFc8-ZnIrm7K6DnmJOAvGzH7vj5-8T1BZwVyALuU16nX2QS1IWRPV64aY
o8TqBluqS8Evmb3w3hlF8qqIWOywtpFHfOl03LoXDZZ-OW8SXe4Jw96XhXLm0rUe3Ug002g1z5cXBKjVBU0616O6TK1m4WOki3C8N9O8tC0LQeDQuNK13JCm
XKi4tC0LQWFYt_BCPBjn60Q2bomYY8Z__xMpPayD3Jy8RcNOnznI3zM0AVY-4DRW2uFMTe46n61EmNgVK_2W1iYWcO00C008_3SMmaCQ48FdY0Wm0wO04AoP
0ODkhKq9F3Eees1sDGEc48ZnzuL94KmPDCaGFCz1WiBh77b8Wpc3PW82u4902Am53n9uHTKuwNsOO90Huldx0kr39j2zjt-bbnDW1daAtNa8cC2p2npBQP1q
mM8GM8YO1kxTdVeWBuIr58FqACIBe7-vbJ6r19X1de9xa00mW6oL29X1dW8K0Ma033XMMWJCW1E741m2Pi0fcm5ca1-5205WaAPmrmv8xuTGkBmFcS4yLg81
CyXJY1G1CvXdbp6u_dmEQ02tSYGg1jUFmXK4_Ckjd17YC0Pv2go18m5mGKkXps9X24G0DN3eWsGjM6qVMBGMK8FWhPol1Ija4ASGB0BQ2teXUZ-40kn38f1W
q6ohej2Vawo5onh0k_AnGcoMEfRpen3KW1d8hmKxXCBbVHXW8Am5wtaAxuRWYVRXOGoQ9VPaNeXPBO06ipyrY7n3P8MO506yiVMMotvA8U3VPGsUR-LinWaf
pFSXtye5GaXh8LW43fqee52o9oSQq1jRR_KGzbiB4TSWpq0l15Dm851mAqCrgeLW1ZxHe8A1z7nc1XxuvjGhLE3SsQs4yA06px420l9QyCbFngzGh5I3-bhW
UAm8uY_hYO-ogbfmBe8Y0cRZscprGZWG00HUfO5-5Bhr6sgm3ug-5ae8S4OYHK8m0W41-PxqoqLWjHU1NWXFQf17e2z7rnE8vwv629yKWGi8AAu5Jmv1de2-
5bokWRuMd7ujwFVXJH_RN5y4-bgeqc24enT2NWHw2YxKG5yB_AvyqYhaF1v3mUL5eByM_0m4nB-gNVvGfAVWyYBG2-5o3VHxqW_ImFf8H2k4FycBG4-Xu1Uo
ADQ46MT9KyN6URAhXs1L8RPnkfXCWrM5692bHi5id3Ysc0QSnJJWs684EAjfmB75270Mqu1pjnW1ZXLei3A5yOrZ1GHMXB2FRv_LYe2pcWQSnGXmjiKquDXY
Gy2n1845Qy7kndyRMwm8EAjfm4aybovYn3uMoMeQS8ohSB40WGK3HR1U38PWNGfZwIXcu2S
}

