sprite $image359 [243x176/16z] {
v9c7iYGh34EXoGRk_l_NRdIzISBjVaowpAcyWIer4iZCZzTGVfD_V11KIlaeqUK4VOJWN2xvf2rcY5OFCMBn7SOihXYpjc1CNZl4cA-L17zHKR6sfp6qjgSn
jBPWp4BjKi_QMuofQml6q0gUNj_TPPx5FOrPMZ265X2yfEYlSc-MFhKmH6iBnkHlUHFdlA2xYuGtngzsZXM9QCrlR5n8jEpfj1bcIykuMmonCsUuDI9T98Av
8dn_TvFeQNibU858vrBqheQHpl_nFJIN7QWI5Eto-VN5w6F-pcMBMczvCu0m8xdG6qzCL5jlqHeKQI3vlKKN9LHxhnv76aZMyww2sTqTHzhdNSbf6v_mRoCu
OtTdwEuWIywExV1YTzUTTka7egC1s4sG77PBct-6OABzUpXWT-D83oL7gobjhswNrlp39YowR6h9sIbB6xrwH9I6fjfwIzQCkEXam12lY7GMFNsrWQD8rpYK
3Em2baIaLtGF5DD1fCdlI4v3-zkdHhf0i6ISFnuUQgtOtGc5M3-7FRrT4lcT-I7PtnY11BuTOCi5av_o7e-FOvo_P1X9CghZ-aW_Tu2WuN5iWrOo2F54f9yr
FmGyFwWaHnmDNl9v5rO-E3-C8Yr8beCxAcrk8j8JbaQYso3IPvAtU4F0bewjDs790LyFQvV0NMAaJqBwDUGCnDT6lEHJBYpQRvTkqB227DfsYVJFFPyIxGcH
9jtBPT0y2SYE35Rk7iAIGgHfNl6eyzk8HUTD9nbO5cobTF6N0GyO4Hanqh9at2xnLZusqYG_UmZk0hUqADaR9K5nyGDeNl2m4g8wL6iLhOYNiYdP9qUQYWnH
t9jmdFqtGOpc22-CY47QIlct00pDTm-5kpOZuySXtgYtuLO6nMy1YCawBRjBBJb8OrBbhSHve7R7I1Sb_2mD23h9qSfZ4jL-ymRigT7vf8e_UXam9rX-beui
UGORRtxMsKhlZNGV7NCunFfdwIsVINQtRBe1wj-4mbjfK-kjqkL75yAbSJSTKooxorl3sDQlm6K2vvstaaznqZosRLaIGhAdzP4MiBLTChYdyUJ5-N74dZu7
f8hDG4M03Wh63IiQWKBdP6n56YoofRzM0eA5AvsA310y4Mc0P4Kc_9Oal7nGun3lzN9W1WW1nTFl85Xo70yPn8lWSU9QHi0XHfx649KfvA49M17WyI9RgTgA
7_b4Lq2rrcdHfGuVDfGZeestBnysDss8lH1Yz6Rpc_-jETaJWkIWk8ZJLP6DG4R6WIzgJ_yx3ckT49tC3aA8GMvFZocUpwAz4BCPglw6OSc2kwSbOoiEkY97
UkDzktU8MsV933r2ChRYLbgIkdNhcei9cq7sD4iMH4zB7bbH6F-egTjbEIoO9K-8pbx0MJFeIAqEPsvNq4qCLWAZXXnYAFbufAcFgLxgIBYWsrIOYNO9Xu61
vECRJMq4RisdSmczwDZ8VplJBcLFi-GPqOGfKM75wsS0Vs14F7OJOyaJaJvgHJnpkzAr5rCwUZ5XoJEHdh0YSQIvK3oWNG8gve3cYOx4xcuPjKjtZui9IvuJ
FT-HgFK7jajPyhoxyyYAyiwGjbtMYH1h9FzgtZwG4mc288eA3pK4U__JhZVXY0no-Qq_DtZgIYh7w7Lqtv68Tfd9_NJdZlHYfGD27CWLkkz8OQRRTjcJjnbq
5Fk_N0vn9lVeyyUJof30KBlCv8mkTzFCMrPw2yxa7Ztty1L77-9p6U9CpkRfFz_iGtpiRn4pEL_JlcVlGrmifeBSeOklEFXscSazEhzdhtfviPXwCX_ftCk1
cGxaFjAt7EdSoul51903Ed_5WRRBdin7EhTB8iIPd2DTVZe3jSkUp4VwU6MUNVPaFjAxqxj27CG0EI-iPv6-GEso9_EHtl4XpkGUNNmwmxRBV7tP07JuT0Pj
brdy_VfVSqIV0hXhbpque87Roj0kKV2_QsZqdqZpxJA3mq7JaJvjIqCSqC1j9RkOCXX6vt_qtL_NWtjp_wIeV7O9Y1T6klYy1G2lZVJg4EVhWM_futNzOg9F
EatfiX3V0tHTf0KplJZIEZ0VwJKXRgwXqEitiI3IWfdc8Yq0soBDBoR_T0CXTgD700Rg6BUO7e4XM5ZiOl9Fzq2_MeA5PGenlx06235mnC1q0uk9lExlHmy0
baKQ0ElHNBiKHnhQn7xq061rf6UJWVaE2Xon_Q01i1qDW0LeXhn151uD7B7T383jQ01iHmDWknaGsz40s8u6m7QqJim_7WFkYUq73JoFjwE1aRQZ0R7T383j
Q01iHmE_qtQqxeZvnsC0s7xG0DYE1a9ixw2w8-RVLW9W-tG3TTgE1exOlh00i1qDWEtJ3OZjQ01iHmDWkna0sz50kxHtK01iNrYVDjFV
}

