sprite $image364 [211x249/16z] {
tDQ5aHr140HHiRQgF_XlhU0WZnaddmSPNREnnxVseqaEHv7cH4r1S0LPBdN83GVDYHphorqgkX0gEX4EdY3K58HbWdxdqRRLJYHPN_DKeY1qdI31ayeBY8BG
1JQtUbGWYGeaJO4agdbTtKGdWYW85GMXeY9K58GF-Cwfejh0iRwy8r4GAdX4WEX4g2W8fY28Wb1H4JPH41RwS3-Uw4IeA0ZrR2uuY8BWsLnGKH1-UpQ7cau4
KH2g2dhyazgo6j69K54GAWXwv3_ID70SAft659Ka7L5KSwATDYixOXf9L4aYHBE-6K84KTjvqdZM5v88IMVvg3ddUL83oPFgmF6aEhlzmB2-xlPxaXPV7q4a
6Q8wVwkt4sJ7KI08mx6FI4gF-vzsbbuKBpkCVsocZE00xlx2bHc5v7UUHe98RH4Y9q6ajfWv8y7qRG4oqWOed3aWRHOfnUb7HURO9b8Eycz9HHjC7nItawea
RJ1z52BFql3qwTOpv_MmHQGOv8qdRH0fcpaWRHQf7o0W3K-VBjyDPev90uLU8smIbnOtapXIYlEC2xWyH4nYKvmNgKgBPuv9FdrCgbMBGKno598ObHyY9dcX
4ubH-I5YagEGn97Adpac-VGHIR1EP83uF2zjOJq0Ac7cyC3A8FL85qJPA1c83wuCwf1WySi3COctS3a9hXtfnSqaD5L9KEA0oWWHDnv7oaamVVapnwInI8M9
u2QV3c9I5KOgeefkyjapnmTtEukK5F6Hcpo0W0GeDzdafKLA0CgvBq6aqekRIH0f8C7q9OG8IJXzJif4YK5C0XIG8589eCpx4aSgCKHCWaW12QOleRYH1DC7
942bpHoJ6EKaQJ1IMI0cSQISDFws8wkucSIHSjBa2qGEqJo9f-yqqkJR3fwvUHAZdCHV5A2WkAT9F7rEceiKXsYUnAWV9BilJKTA09ecyVI5L0CwX2Bbe6GI
euh21czY-Y14-IGlyJcKXMWfgLiFxxoJ5u0MaC04aGBG8jBSz9qxaCOBNJLY8n8N-ezQs8h4JmFFyyOawGrKt9V44wODIVosOpiIzvis9F4Bn0r9_09nGn97
QZyIHsf34hz0t934Bn0t976aTYDneKk_ILjjuXofE4DRtPTu-g8MRVKjCQfej_iIxnEnKJsuQSFx4a_VXYH6xKZYI6r7OfCs9_7qCQdM6v4OnQJGSSHTI1mf
9aNKUXpb3YGs8UdwO1r7lGM9fuz8ryUMeombnGie8tL0_3NbayvXqvFxadzcAR7wqQJ6KJz8KHyKjHV8MfAAeN3w8gJwPF1K58j8ZghZg5B3i-GcbOAe_CPJ
6KT9dVjIsCVLM5qFWzF79NwX5AlhmQUFIVGVWUdBhmUC59FyStdwyki18WKa-vyOQdazSAHunol58xMk7ZnIJEgRZaCUgRNrmDF791q757ecoIs0OjBrDTKp
7FL1aX4mKamwxL-XIENN0qUAIL6huhhYmewKGugmUe188IdYnzZXZfHV3pnzu_LGZX9d1xMw7cIeyUtXEDJRPXLv94wIHmf8zgdss0iYbKBgMunBf8XwdIjD
4AcyxS48dKW1oJzJ9eBfoyWIMIH7yHEYvvSfcBwiUf1wrmucTMOh0gOlhnxwOqZrG7Njq_UnUk18zKlSFm-kykdRGt_wd4lF7YWmr_H59gc2nRZ2PmyKcCWc
kOKZfO7j0IELJBe8K_NWDq2EL3B9bWQE59DqY3QWYDYW7knIMtZ_ldCz-FdzVYa0bK7YFPpheV_OAtYjow-7yTsLdpr4mAKYcMGMkWuoAQfAmAKYcHJX11v3
_f60EclTUAJQN3r8l8TpFVYJIRXKCAcrwNhWI74zn7Mf5LugcDJqlzQ3e1xuHm9uJsTIQzFrm94o4ln80E_fJ68KrmEFuHWfEWzRB5900XHi3sZXUl1BRGr-
EGqYC64zI6pXUl0D2540SXIJ9lPmUFOmU4-N0aI0Igk7lWdkwJK8vEThiXvWTsKItzDhCCZFUzk3p4Br02Q8L008K5mFRYaZzG3R9aJg4IaQ7I2zkuVpZbV4
aNf0QWD7JE9do8Fru9VQmf6A3eZE6_N0koi_UoX7eK874AB6wu4B_OqV2TZqiOWFaCZYN8sHLE5I0I0yG0ABSutKDS46X20-G7fj3sVISGJiI5pSV3vQ3-Ke
evUADdFcwa63suDTQl5IqIQFlf7EuNeGr8E3x0yKw59H6nz6NQJM9kfXyaS22WZHozFt-mkFJZt060x-I83kwNCEHyM3HnNZUxWw91zclgUNqfBE6rVRmHy9
d8ZwAvt4kolNWmS6R_BPfC5do42YIuMbBPt4XSxF7l1A-_KjRXyXyJDas1xWdbvRQ_eqYIF5sqDd0xe8doRHlZVox44FDY03V9J4aHhw0mL7_GZHd_zmdD4-
P-9wu3zGy9T_qVuy0Q0KL85wW3zGi0sebAy69ns5zH3FdpsKIDY0SYB5fFFRR3fAIqmSAIR5zS8CKBUPFY1vobgzvVJvCsGdyVD6GAqoGJt0upavgXptG7az
d4poPG5GgoFb90QjdxulAlGE2PutQYagOFgG5F3ztwxGaJJoiRSgT2Sng1-f6kqUA23XKCD5VOdf2IaQ7oUjHJ7fbO_5As0-YadHHi_NIbBJCAczSY9xy3ZG
I7hZ-uyy4QEGrFOxG6fRdYUajkk93gdjV1wHskx7I6U0Q2yKZDnU1qZxea2q8yhUGoITVm
}

