sprite $image46 [222x162/16z] {
tDJ74K8130DHCaW7k_zgoQ3XGav_NmSx3lr5akHg9EkeUKg1wzEb5R8ja75XP5iOsHQ0E6fVMJSPERSmiYsg1yRM8m23WwodzGHaMnYvb0hauAA8RU7P_xPP
R_3FWsFswPsCR0jcN23Rmg1d4i4SN33RWhYKOIFd5jLVL_eYvE32tpuuQbyfS7aRtinr8L8OXiBstbpw_g-x2yKvjYuBrZ3VJqITRt9AKq8lgZkdq7sg-pYb
47XpA3_EiRTxNgyIlTakqq1vrEtzTk_Q_OYkx5RNdGVkp0uyuiQNThwAVi9q7zPse1IkxOZVC1U07KYoPdV0wJAPdVXiA64tuX9nXtu0xr1or-lEFfvCbtR0
PGAWbbBoHYcb4W2vkrtOWOTR4zZLE2o_Cdhb6EOFxaBCesFr7r-8uc3tf1xHjHqhZH-E3ceQn6R5z38SlnxITiEE-4ats5LjMWQDjAkTcG6t2-RXKj6cV9dC
pdDki2iisYGDttyA5sAuqu-FtQR2DDdP-rMwRKUq-J64LWcykz5zEnBxmirsVK_Mway2w6CkbPYPQidHkvCoRX5deidEldnCz-rSeHtHfjbzCujxS9kaGAsZ
mYL-lp7tKEu4tob4vdvqIuxbWAcpMSWOprYb-vJD9hA8gEfsIMWKz0mteX_sF6mLIi3jW0d2GyEVHJSpuU9VlKnlJVeFXaeNk15fwmZTnCeDy2Uub8R7tsR0
J3LyxsIweEIlzv_yQKC_fcN6dSjJQyhZLfsLvyC1-qbl7NxMZGe-QTJ33UcBqbI89ZzDGrTfvcV_jikX3Df5YfzgEIEg6NgLVabyxXKi8XXq5wbnxAzEJdUe
Ng3VmhQX11LRb-mcoKtz5QYf4FImziepSnNwFIX1sUIod_iha5tle0yzGl6UcAkG1IyRfzW5XlvgZd0eXnvQ03B1B9G0ZnGXBBYykJ6DbEI-7WMbs4GJiFLS
09-myilE2q8911sts-F9mwPWwCTaH8OT4VCHjeYwWTwd-Eu_sYMoWk5cMhkoTo7L7tuqaj8Xc915ChG3R6XNyGd7uv3B_tnQ5WUxQfXCm6BdXtI5rt4euiBu
xWllrCEucLH3DnKny-FviSvwl3gFbMgY3a_dso3SDvC3jdDhJJQOB634AnByIYIbkDUeNw5UFBT5D5HL_hfa8nl9zHEosFa9gb88tw0sSb1cwRTLsT2cK-dO
fd2jmSucdeBYkKhm4ufuIVtPn8IsqVT2H3gAKIXXPrE-iQ7o5PU9jHpI8VXNxxandMwTi4qeOMVd9u9ika906tShG2y2BbOrSuETLJnP6Nh3lYpJkqxFIftY
S3Khsomus5dwiPARXq7eB3bxr_DPj36z5Y7an6R1ZNPsyHGT8XZAz9-L-_VRFSR9M55Xgr32Rjsl7X0G3jCCf13yjE59MVDufwl2Xg64tM8yYpiW-4RtCUCm
YMHc4M6g1OEVkTATuZjXAPImM_R3aUTiEWoS3p6bd7DACNZSDH7h_BVTGYY1dC0BTWNrMCMb1JkuNTa1_g7TD3n77I-8D8urosYt6ahOhSLpj4lpTBWffKl1
K4JRDDOCzKTsSBjb1_YstJGrrwRz0Savd1hwLBTRL8vpF8Y3tK8eORVi1xiQ_ZKTvYweN7Fq3fBE-P0AARfediUQBXVONUm2btQBySmNq-4kY3sECTdQqFqI
nffZjc6tiE1Wj-utsk7jfH01tdGsHw1_cVykIp_7WoixHYWNx03VjejuUpd26x9nEdDalEEyOmUtHJl0j-m2QHEc1H3FV6M7UytiXFc6dVFUkuwlT1-qNNzn
5tPmCx23tvNTo8NT_J-q54hOhVkLDzjX5p2mk_IhRxU3cxtTlFogEyVQ3hk0lHrW0dnntstuFomjEDYj-x6UypExTWuFJyh7xH1F_WzsjLjt-zDjdUGu44CX
6DvJADp_jhtfwMqo68lW_3Vu95wvXcx1bml3jbqtY_3cbzBGLVh6A9V2EW-Devn9rtAejqdLFboMhTg7YvxDvw5qbBjydROP35_fA5ldYMKR9NNx_57kznMy
0ZT90L_JmSrepBDsbFdpozjyNzaeVTuCXit6bSuJdYtgAnnb_kVCjr56JFWGi0NEBt1mIL_suFA-peERmPXdTfJvyukECkzBZZBFkv0TPNwUrJRV5pYu0XzW
sMfzG7QK-VExB5ktpta5WgLr2fVKIVbIEhsfY4uwXaV3rk-ZOUltqR3r-sZWUdY-JaNjrgcihJhLnLqwgh8zEjNcwrITgLDxXau7X4MT3cb5ftF2opeTrMiw
7TVpEkh0Ra_gT6XuGgU3UwIJKP-FXgtVHmFNpwDXw_VHi1KtTTI7XNywVM0_EXbr-vWTvHS
}

