sprite $image319 [489x355/16z] {
xD6n0K1G50ImMlNtdnPs0FSkMI6hpNPP53nNL6lkcDPSKQsveTfpoRJcYchD5TMULMiUDgrPjURyQi-gDK-RrgpQStwrPjMQJMiEglQiMhDfpKdLdbLhLgqv
QLgpQi-gDQlM732jMRLdrPfLQ_vmshDgpQerczQislC7rPfLQpRjMRLcrPfLQtvashDgpQergzPishDgpMzLQpRjMRLcrPfLQpRjMRLcrGSxTwBag0v3OLXU
i7Lc-lrVz-wft9ooXv1fHOZuhssMtZ-GA9gAE_EYNix-qekvrvFNNw9Up5oLarUFdDMB-OhGBBt2DQ6PUZ5V4fgf5_CLePbwXMj2i_HYlYOqjvWl2yqjvej3
BseSXSudwoWq5lDpq3XPcQ7tMyoNXUOMy-MW5pK-6ngB-RBGt6AE3RsesNb1Op57XrxKm89-R367XLxKMD33BikyeBd570nwKSC8MhUISowROfZsVmFNQlwh
sZ2k_vlk_1z1Bsh01bgpt2hwgtVhauycQKmj_vP7pZTPXbxIW0aqFuqm8YiZQ4roRuYfy__3PWODV38pcvBYZhGCe5KUIm3Nvj0e9j3ngM46NOLhCp3fvBmZ
dURG45Deu8EP6VgEo2c33Q2J25U6nySOkbf38oIp8RGCIeCfIz1L1ZNQq7Fe9WRGqQbX2LrbJqoJ3A1bzm3PP0vTnGQQ-qncXcQmF13JLaG8cgHI6XmWlIQP
G6kh8bRGt8SoCpIFq49YMQWEtj2f0vr4kr2PlW1BQ2u8ip7qdRO-ofOPDAzV-giwGCUdXZsqt2B0D87c3xFHyT8SeADJ0-RGTvBA8rb_2Prd6w2S4Xe1c6sX
Arr5qJzCeUcYZVx10JegDM0DJIDN-TIiOsYQy0Ky2HoW0rF37deyWkz6PGRD4vy-a9u8cWl0R0MT61ftcp4qd_VySVk9eV4Pp0pDgvMXHpYTD_a0-ju0-bOt
W8v53HVe_29q3m1DNPPvGNDNPLxGN03c1HsV6fxGSWnwepkW0Q0vFsONw7mKcfXgM6YuClj3C-4-D7qWjOEEJmqtw4g2Q4z1WmJfpei9T7ngm0zwOzT2f3De
SbKY3G8DN8-PpGWeJSvCXkRZeV4W20QDkCoQsYiF7kWZM9f1qoGeT7oq0D1KL6SHgIyyIfGUmUe4caUrjCStG0HeBXhp_PGiBpmSc5flYKxmAJJI7Qht8hUA
ENHBBHWrB2etDTs39Z4gOmUwoR1k3LsDJleupAocJqAtVJ26dXyW6IRGV20N61J8MUN_jUUWaGTW1JDeagBK5beJ3QopKyEanbhFGQi8bx0FZIh2RJ23vcEh
1v26JKMul0yzFZTr3tey2WfCeJSQM1O5S1vDuAJFGAEDdFUXaTdP5BeC3Yk3JiwyVr75PhJxxcN5az2eDBSjePDm6JQTavcrkFOCDD0IlUZCKz3GGgznOmVT
HWFhfD8mBik12sXGscgjJN6qNclTkldhZ8qFv8OpKiEy8eDo_1UKcn_85KOPC9ilwgJXeUS7Se5LPsJcrSUrSD0UYvepS3Q_9DlYGyyFP8LL9ipsbsJneUql
oJW3PkDBiXGBsczHSpRCzfTayQ5HHRZiBWsNL4QrID2UbsIS0RFj9LcD0-sygBctCTT-gDcYBW6WNwvwIUCRasygNHXQ2ZoeGNb1SuMWyooz4yp2BTr_avOd
rLUXpHSrPy1i0StjVUI-_ybng--_IPL9cQ1_AuLfHimB-dWDfXavBsZ_HStPC2_eusKOHynEq0kwmZmZvWNjlwHP-eSpz89MlACVFtzuGY_ez1xchw-VFudw
_D3-VHzqUS_P_FKtj07rWlQy3EF-PluR-dUf5tJ5kNvznLFx3atIvuAkDHAq_o-aUMeJj04rj1-foR26KD3-ZvWmCqCpzKcU6rC4WlP_Q8odDaFVfFseTVPo
186W_TSpCpEq_qdTPLH596Z_1xjvQZEqFtMRhEUWqFwNOSHCq6xKHKOflW6w7QWRG3kiPvhQ1EsvgjFqtc1yw2J2rNTEROPcQlSdkWkYGVjVXZ4pGu-flTTp
I6Z_zKpC1Er0JOfKHpHe_xial9mPsbSwpv-1ZGzTX2iEKvkWNQWrxQpdsD3OthgUcPcX_QYRZDfm5MY-Lw8EKvkWVQXbL8CFz5PIoe-LEagVXEQPbTI1cQ2T
f3MDrhCBTCtoRFsr6oR5OJaJj2Dr7gpdzqDlkyh7eVdBhmxBcQ1TgGlTCte_z5QJY2Kq6Yqa-wbz7Dh-hcYZzMmBFHxPnj3Gh7-oSnywZlCm481bIsxa0FV-
J_ltVn0bYE5uUI2roq6vXlw18wvyjcTh4zftgFUJu_atGo-LUhyLshUr2UrDlK_TdP4njC4mnuKMu0Qq7tNb6cOFRR1_6K2xCXFQNxhnU3Q7DjY_OaABuWQq
DpLZ3tszikUsNSaH0fhCvj2CZ0fzld_LnU0AD69h4zg1sWkwJM-7sU2ksxkrxQ5L1eC-tx-cjXWyrF1ajeTcP33efRuTvh-L1u8Mt8lUZOm2VRv_6Jwcz6Us
XoPrVEZp_MiT2beK7j0g0q2VxrzZGIlW0wqgBj3pvPpkNuD12-00pOW3TFbYPYgF0oqANsWL6GUQbJqGD9dTe1aP0vhxrtZGP7Q2PYG-D2jxF6W1tA4P2GtD
_Mj0Q554WbQ92yrX7X6QpExGZ8I4vlur9BJ0B6eOYGWzSVzoWVPd9dHuwlYlv0G-d1cDAPtGP3Q33aYTq0AOGuUZJcXHZ02j8WaTgBK97Mge4rg0OQ19dT3-
p8IEGvtGeWW7RNzK9pIP1u5c9A4TMji1cjH-qFidyOGMXI-qFtNyh_k6PYQqltH2apaEj3rrGWiG3TgUEg554GxQdZgXoHm7sbuweGM81crFdT2Y-5RGZ2Iq
0xC3j0gf4vhCtn2QGvtG0ZX0nwOcT0kMwJQqA1oWerEt4ZpDfxNZGwlyQ6Y1HzGdycEX1JvHhyYFX1Q5KzGlylEWBp8V-xU2LlbXq7AHf9NL0TgVEZwqQMkl
fTX3uzUlN-6fuqCRCkzJ8RIjipUro4-05bnCAOIsPWu_r5iBdisCcT3cpF6fnuyeFeLUR9cJEjY77GbT3PsZINzJQW6yeCcSGnsbjUsXoPpK8Pa9RUsSrFw7
yp4RGvCvfGrYUDzPRA79dDG6CRplj8KcSr97Qksfs4FJEQdzMvlpR0fDvfGEn6mFJUQa3dCuzz1Y0Ktcf0vqEE_JyG1z643JUK1gaM_Qsb9BiOOcSmvrcDPU
Ih659dDI1sfjASKMciv97MhNFeoXoJo-j0p1R0gz6Z3dK9j753xGP4vgXyFP0detS4vgyzQsXnO3vfGsRcr3QFwh0NDIEp1lbw7tydVQ3UUaTc_jVIhjAdJZ
4Ns3EQazcO_ADVe2D9lx1dDAUxPsAqzxjBw5vb-itin9pIYkfPR_mm8uWHOET0Zdf1RWO-Zv1BfttcCmvwseA6v0b_O6ch8xxxbzcNEeoNmBkgple6jtceTm
Jce5xaAN_GrqMVLOU9O7O4vgAjo2Ble2_HBnPqvfKNmDUdw2tb-T_PcJcioteKlheO_IP_9tJch1bUnj-jlpwA5dKcuTD7hdTeCvgLsO9vfrqEj2pAE3Rjsk
visSqgANtwIYT0VzKE7w22s5MTsPare_kDLczWuQ4nSoGZ-kOwjwEoUru4faBdsc7beAymWDNLjR3tWpvsiTejUSoqls3Xhx2pJZpvn3hRZhN9OU6aiF7SWv
gGKVEi_hoWglJz2OEsWdvgI-pynDgnxTKlOCZGuw27C-m1J5jP1suy_ERw2bWmx1d4Ejk9pjwPfwVmUDlOFsTqvgmVNeapFm5XhDuIbLKbkqDl4sWAdleBcG
LNLdJccvyovLnIbqF-tJ0NVdf9PR3o8L3rbFeAMKpOSvgUypyuHkk0gDtPyvgKNnQHftw6Vesa4p_imfhVWyV83naFfo1Hh8EQa5DxBJz0Lwxw0Tc9FQeBLF
ttuitCy8xS2S3p3Dc7jJHb-VHyTmpg6-oSpRw_TrJcX_vgGMtCx6uNsfS-sEQtVcf1R5_IpFrs9ixWf2D_LdpWUOTvdf-0AzFWvnBVC1T-SSQW7CeRisRvi_
Sr8Blfg9gamBzZ-5abeKNqxvDoyhTmt3dD9aDe0-dd_UqY3EIIs08VJovBp6O4vgKTYabcw2jrXV8Kbgm1XwLW3xNBYRfJCpF7J_zaMj_AqaSvzl0BsNo5yX
IMgOvTGvcPdXeLlfCoEGSrB3BDexhw6OangCwIbT9HPpKkDtIDS3mPnJ6gRPQgrjqtZCIGtxH6HEwZ_RemC10000047-reDq2Y7DLoFFJoFDLoFDLoFDLoFF
JoFDLoFDLoFFJoFDLoFDLoFDLoFFJoFDLoFDLoFFLoFDJoFDLoFDLoFFLoFDJoFDLoFFLoFDJoFDLoFDLoFFLoFDJoFDLoFDLoFFLoFDJoFDLoFFLoFDLoFD
JoFDLoFFLoFDJoFDLoFFLoFDLoFDJoFDLoFFLoFDLoFDJoFFLoFDLoFDJoFDLoFFLoFDLoFDJoFDLoFFLoFDLoFDJoFFLoFDLoFDLulD0G
}

