sprite $image75 [223x162/16z] {
tPk9SgDA34Lfe1T9xUJ___Q5o1LY5RdG5lNeuTGwUuwr8ZAV_oD2NtpU52RbdeAqmlULK_8Ty_Ac0QHDRYPtomWA0Jvk6pg5Rz1IRYgOoN2d5iDCoXq5FqYv
fo0rSryvPRv1kuJS87IOVqMk38V9_yuKP6hNI__CdaOhBNg6RkNyUahN_TAlHnyzBob-FU9kG-VNK_eiEgmtvcBf_56f4DIpVbGVht3N3_Ea03t3HF824w1F
ELnxCns7-roU1qYa1dfyOXqmOsxm-xWwT5Xl35ibM7hEK38WlRacPmaoNMo7zHuoR_Y5r6U64ZNfJIoF1qtU4hnG3kiHSNtKx2r1kh2ZO3qYgG_PBC4MFxve
6E3EIGly9SZpnfRM0lDreSDwcg4q6htCr4OFDp0sUgiW6JsXLlZ2o64zOebcFLEzopEK83WvmRP6J6_07vV9AUatj99COn5w3xxsh5uVAvLMHj1OBXAaDwY_
4AA_phk2zJ1No67Ct9k5NFGZfmHlOx5upqH-O6FnStNeS6Fnmvv-MV8XKagP09kDXHrwpW0AATDmbD7HM9nmU-JQzHoDnS-RHJSxz71Z2K9xb9rzgC1h1PRp
w-76alXlhPpYD8QjX_dyz-kNXhnqw7aQIybndWAufo4zeeRGdQuNpPNb9JUVuKBtDAodD8JEhOSRI-6VS8qD9sseXmN9WFGYYu6R6ilmvRKTBdHFmtfOaA2U
PQJ7AvKWq-0X8ZqBa6j8pgdm2uJ8Wu-GW9w5aHpM0sqDDdatOmPw5j1HW1vkQxZ9-vdBjXuMX6arDx-fyuShZ7CgSRC4j_HmXZQimGc-9j1mkRocc0kB7cfu
sleTizN3RvMQjdofsv_f6U7AzAMbr5fb-K710r7rS02vHO_DQm8l8KmnBU6glxoq2UlDFWMVdWZpSRt2-fdw6UUOYKMjLY_pnUbxJpGD8L8VOWIn7dXJru9K
eFKYQ4gmHMy9nKCM-BYUVgRHPHTD6kAliPO0z92SwXb1fBVzcU9cE2UxiT2EbKrHYMrw6eDL3sHeD7hhPpfYhN5QggikNIEttVz0wX_KM-GKi_5ZlVoID0as
-RMy1Dp_d7eWBwsU2c8zrDQMS9MjPcXpKqxNi-t8wgs2MC_yFPKc4oxLKg-6-vzNpnQTrGCbYDlQhxzlROQE-vzFZr_bAilEGxV0RosLkgRXQIyMnWOzA2SA
4cISkxpWUB7Wr0DvMMMntVHZSe7lVxH7ESpcC52gsee0mMlUMDR7KGJavRgrRC7NlR6Km_3BC31v2VISWlZ5WXyy35GEwBap5BzOy8E7WTbQ706yweqbAZem
zyuMdC6B1IUuwFH70d08uXSBIfnNeh_eD5Ys10_uyVcDnLPbEAdeyDpp1n2_M4X0pvsNKi7SQn3qD1Qd7jx0yDmxFqEZqPjoWvudBy5WS0hYHvkv03t_CC1p
3yFEt5IHYFJyUMbL0Nx1QKimkVGsDh2_VmJq_1dAVzpJnWBqd4LdVYIDDFY1UzfizHp30FxeW8z7KFxyxr56pr5qw4VxUY6oGr3lQLk2mUYrv-M14fHTmX2I
zvvMmW09ZgA3Fv9TbjmYSMPeJIrw_g8xhhTyOKN4bw4xxpt3kKNNebU-Ts6P8Zipb4QWrvINe0HVmxnyt-qEl3HouJ24x2t1782UQmEpFr8vHJ3ZzrFsy4Lf
Ay6INoX4PMpKOwbDHMVbbBtU4YGFcgCjWd70xEjnomRs-a5y_cQljt3K6wp414hGeUST1hReBBYtw6IUbamT2mYWGyyv382SWdfB2deh4GtYhg1Vx_rXyF6v
JGMzHRyA9gC711rwO1Wq5Ptbpzwoy6L9sJHGKu8EFPINt3OC6WMJVWbn67ByZg5yaVTBCBsXvny661QnqFCED0nfqWOZovYVQ4UGttgCv7UA3jlX4kHX8PPX
cCDp-grp46IeF8vI-OmDx2XY6FMjyJ0iTlhueBs6OGdoSKuikdR1-6t5GJlC6j0XEwuLlXkO2EYNhOBBBimQH1qBIVLcnpd6iO5LF0pQ_JYEcf3FiH1KByWN
1FOqmBaRc5jGSrJhhUWSr3ei3NkQuyd0g9ebnI-etNBwQInBnYPrnKF2ujl071rbPqYafn1fOeugMxGC6GWs5fqu9fqhG-U15arjAqko_kYzTq_p3uEJ1NyQ
IyXPYq_rtWkWVmFpOnh7Zu-kCAkUrcM3e6y3Em-sBUQNaUhbQL1PaA6U6rYJdBy4XpHh15drI4hu_X4GxAdei62PMVJiLPvw6jHqV8rfti2mdP_D1y6eUcCH
reKK289XS4tHOJyLAiygZEOP0cGeIyjRI8USJt1SX5HFMVLG0DisC8USKt0fluprLhXX67WUUyxTq-PVWs48Wc2yWU4Rc2DqdY6HdfqpZzev4SnIFSFW4i59
1uEKN0HppGRMpeSjGP93W38x-3X-JOPoWvvZ0xj0i8NgARh-1IikCpmC-XUidWsiVx-AYav_1Cv4tGjMl87XlEnVqB61zU_tAj1LqM7QzIexRhEz2jR-Xm7U
qp3LCmpw3s3rl8NiNx1wDh3-1Qld1jP_2RgAhly0LlyDx7eQvfx3haF12ehk1duL5DqD12iO1ZSGh20lRo1OGLxUmGyCWni8rfVGoQTo5q7GKcuXM87S3Vpg
xUGKe_TvErGFoDt0hzvLJWNh_tmc-Wy
}

