sprite $image96 [296x190/16z] {
xD2f0O10400nkVBwxnOSab6yIGbPzvlT8Yo5AKifobAPqjIdBFKfIptAKf_IT4mnWQLfD5MMAakHfKfJPQco56cgB5MMAakHfifIPQco56cgB5MM8asLfSfI
PIdIL5cgB5MQ8akLfSfIfAcoL5cgD4MMAakLfKfJPAcoL5cgD4MMAakLfiXIPQcoL6cAB5MMAasLfSXIPQdIL5cAB5MMAasHfSfIfQco5DKbwXAQJcpjsqUI
7J4C0z19_OTXeVkVTf8MgDAWML_ERX3EsrS4tKdtIRcPDT5CwUJs2YdrL4wLL4l1QKhLK2tblaXrIgUwV2tb24QgGvoOLEV4AUOVk9hgb4wEaUfmfo1IBKMT
OYbVftHoWrHBSQTOhwOwn8akz0vnOWkzKpevojVXJd6tL3kXV1sBSUOKBGMbp36eKryZ89uV6HyvTGhlaRB8wVIPJvMaJfWfNQNfDCETC59kPfALWzCCTT8U
AKza88KJfFGg1oU4EyazxeJIlbD8NIDu9dL22YSPAKi4JalEdR3GLIg7398fH9q4f3nP1WkP9vLR6K-UmLCxJIcDoi69ny-S4b8QId3YENT2-mGgjpZHKATh
ZfGbyWkTC58NhnoSwXHEaBgwKit47xZWdrTvUUpRIZpVd9nS8-XM3l6nE95lN8GhXnHEQ9zSvNWM9p9I9go4U2HWo4X1IcWnyInERA6hBIOUJ-Aqj4-oSlno
oikHCk7A8N1QgR2cT2l7Fyv_kX4dI0bMZaiTXoCHe3ApLfh1FC69Z9JIOkB1F86A_CydjPXuLY8F9xSogfNZKf7fd_btFzUtlw24E9mo75GedtJb48TJnhzw
AsF-bvKWDPqoMFj45nENcavpJP5lN9Ik1MgeYF3y37qs9RgOUFaM9xBGzIh7PmfEaoeTCzLAa8hlJedogIuclgRSdyrdu3IbP1SJNrEFnukxWoeW9LevBlNy
-d0Sn0bNKrALuvdpT7iwNa_UNqbMZaFPm-tsydBw_agoSbpgm3o12kMJLuBKyujNhqJr5XEFRxo_4bfCDHHVwDgLGogdNozb_w4Ibs9dPJGhLqFHWmtQbUDI
_8nsAorInHbjbMk1EjGfo9fIMqmSgZgZhLqvf722bD2rG2rLdz7MgnnFvRG_KdQToksVqTPSJFjdjCtKhWLu2YTS8uWkflqpsgALsp-ZtKgVYOqpsYABYQTm
2fHFSp7jdz5MhTp-6MtDoksVqJQJhXoSaZgnaN959UJS2LAjHCve9xj23sabjAzoSbCV9gHqycWbCbB4gPMGsgcPu9ILKoiXfLCh8VKURoMaSA9CFLArq-WG
9wxKAPt0r25ELAb3d9XIXpeDaWwSDfZQQTHfgRXBgQNYBgMM-XUOtW4
}

