sprite $image138 [144x293/16z] {
pDXfbkCW40FWdp4gYhx_RIT5BuwjcMbuB8eE4Bw7bCqVeqdFu4CNraJUGuFqawpNb5C3wAyedG6LfjT8TmtMV4Ov7EP4n5Ln8AwASsWqn3bJn5Lnr1gERZYA
6HrqEGqfugeuwgeuuhlXGCpXg3KSyN0u46iuXxWgZbh34LV5mV3b06bgr5Lnr1gEU3WSY2-7KyGQZbh3wNawi2KGNmwdY3KSrNkylRI3XhCvHqDLij80qaX5
PY2DKcJFW8QZcv7LfBV8wJ78CLKG7X8fSzXxWM2c5vtdMhPB8DKWkzija6h88oiDvZN6WMGu_kB9D2D1LQyUlucmGyIQq-DELxIrAlQmQ6zLx67HLWrx68Gj
x_5_UrYqPpZi6HQDLyMURJCY3NbsWdWux5aguk5qUm0IBQYgkQ_q38aMQ9eyeLa4ClTUJuvpruWiUxE7DUCYhghJaurVPP88vjxZAUvEXurU4QYgTayf3Zfh
I0IggiSJoKZpHAJfznIgR716F9psFOV6_oqYqDJXi2SiG8xI-aNZm-7tL_MOvU8pPiIQ_ls41sWhZKLSbViC3snWHZISOKyAK-v_x_DmfdWIOCCpWhdFyAHF
J-gS4K1LpV4ypEAmmxfdH5LDyHmNJz-CI3FcyNovdwDw3BcujOb0mndq-CtJFoCUplX-JW_E6RLzXP1cnEFiIMQfOKPhF07oTB-VmnfcjCOJ8cSFq32ZHPuG
0Q-UHtWQPZJVK-htGpsKFSb-cz42JvpsUMYwUs96wRypmWfFlQ9wA7i0cj5oZt-ULW-zU1vXg1xGZCWpyVi2zYFAx8bTWMQqoXCKm79GQcaPEFi2VU_lw0im
V58IlCxeuddyVE-JQA47-PmHSFESt_lHw1wF_Soeb6nNpnzYpaFPSMI7ePNVT9FW_F_NlWrjNHPAC2SPsjt9IKVsiGIYrFqL7pUgDTgHLfuTMQnHlpv2eqZO
UAxFzRdsjKRCitPhj1CmyRoEj88rGcpYOOqIFfxEp-lhshUFHfjuhlji563X0IYFBQbHtqTsyrGX3JoXypDhT7WwFXwUSlWCaLTlLwF3qrWXUBnvlZNAglJp
i3yYhx96GJp_YoXaUdXGbLlmd4yQQKGySF40XLnBvcTE8iJZyXaPvw0YFmkDt3prTVut7gcHd-SwMkKM-NcrHjTtTfwl99RhJNucZNmyt8UVxvYdUxD-qtpN
dyxFQ8qEo2slaaOsdkx3-sWgpxD66OK4CiEO3_lQbolsBQ-oHWKajZS_iqOwF_VBUFwUZUSSxKoXMPMnDkNLApx6Qouov1_HXs_IIERvriZ5qtquQnGhRlcv
DKeWxVcPDSfRdezB8vsV3VryQtJUEvsVTw40-FEpq4Zm6A-7Snz-RFhlypDhz1XFnD27aqOYF-FJFB7FN3FsuPT6zZn_SAuaoZmz5zFLo9nNzpf0vw0opxD6
TfxLH0ZLXvD6oENcEKINj38_iqPEdamcwZwSy-hcGE_Cyx4RQEp3IICV3p9M4urzE7L2nlaYXKQo3wU6kiwz9ZxC8uZUzU6iKI4JiVV7UH90hdNJw9wVUvXV
KGN0akSlXOZeRH_U6g4AaQu-eOb88vcVkrhqzGateX_tuQuyVuXkG6CV7YYahty-Ru4WylRXSv-WDNgw3--v5wJHRerYsVjmtIUyrMZ8p_O-uKQKg8nrpy_m
ygmTeqOwF_lx1ALHo3uSzLIVe3KQ-d1_dy14Sn_kxnCaqTo7-_k46v2_3yzKVKBNKfh8nXCxXpvXqCZ3SqvOyNIVy4OZtxmSGvymQ7Jwy0Z3l3pt2LgZquV7
3ikydB9Fc3L2rQTvNdByL9zm9pBm86CrqT0dQ8q-ptDcmTPex1FkH7k7SrwcFe5vD965vopKQusQX-PteP67f-VbiK_G6eLzNiv2Zdq24OLxNfxxX1kHWwVw
BjKQgJv1Q1JFpCjpd_0Aj3kQnpulvz0dl59G8dSyD2__k4-udPTvNfxxX5sdMWlZV9fAexbFiFA4qaZr2PrNlJmtZNxS9uHxNXOQJNr2M9zVLRNBt2V44_Fo
6us8nzVFotbvrgZdmNXgNjOQ-NaADvuLLBkGHdQUNvgNpwzOUUPvMMjavG4AMytBwxr6oyg3SLxM6Xbv4lahytBt2ObqhKVRUbx-5bgZxXCCF2MUIv_dPLUV
qFavzrxZl9n28niFn0F5FvgNkqzmh4VZvGtDCypBhZuXKU37MEBXULddGtukFUHyUayYrhpQ6ltil6pauUKD2ERvvfwNTNvkZUIyp1hjxU9PdUTtr4iZf7bU
dlEFUA3OEo_FULu_buvXNYuB3-_de3IQv-MdrgCTQP-Tbw7pCsiav-NdULeZzxpCF43xJ7drff5_NkxuB7Xk6lddPQ29zhlyt4d4FY_ZrOVldUDwjDRe0PwY
1ugPfpNArxBl9tYgfPNxER16U_bvEeczMuz66lbu3X7e_FLwDBuQcNZKUZJezMWlZQppCheFfu-HpFEiKHOYaU7mv_3GS-bRv-VMw5gFvkG9qeXvxXgTrzNB
mqcirwDHRtQzZ2WO_A4yprjUw3pV6i75mtquxPn2F7JVp_JowEVI1S_Ho97deVTpO8tUvsS7Z-x3MQDXFmVABH_W6VfmNjxmxPOF7JnZ7ywT4ETv6y_SXxT6
SZsQXUUrdbhdPqfYp0EaXsVkmxCrMe_u0o2pAaMULnhvVGPeeE6ygZJoVxxo72ra7yvRNlXvEj0FVJXTZTmy21JYEd-TdraZ4q_tprolgBpA6jbugllmez6m
dqEsHg_hONhUBxgfJtruBxGywz6MaMT7aaPJ7xvVSucHf-kLkGzlZGgHpUF8pwoHpi-j4P3myAnpFxrfj9Y7DGh0dtzE0rM8QmeJ-PdxS3_FtgZMYF8pzU46
dbHzE6iqzk6VvSdOYNa_XpmQFPDNOq_hBmxAqUWXdf3hBuH6iW_7vtaYugVwSBsVWuNd77Jemt6-Iz67UtXs3liRaqRc_Dp_PLLEVJXhvESv5vp5F4AZTF5y
_ww8cETyHpkA5ZAMXUSEjBCA-tqVtjMYdQU9a8Addzow6ce33m6HHblsuQnH_DNCVMGv30GX0DsxAN7_qqx64TjIYJSj9Yx_Sw4SbggeHo0difxBskZkV7ZI
0w3WQ-JVRwmQwNqE8G_aiSk-EHz-izt7-Npuo7X8oWCxE9t8bCU-nocr_mCgG__2YA3py-vyU0sT3qzuJDpQo9yFLurY-y_qiJMwyrngbDYV1yInMMoDNkm_
x_C00uRpScYgqTt-giw7x_40fZkhQkJEX-_tc0zdVOtY7dB0QDRNo9qFRtkuBQUNDPAd84z0qwjHP5vinGujuA6I4LbFHvCRMjy3AbbHqqEJK8qQ7cPoyZKo
deOcDBJI-V22F3bERnEYzxF9qz2aQtIvdwIXoTS8wpnW8yqQhV2maNwDv9cWiNiYhpqBc-dNw8K7_9SCay2eeg9v6b-ZQHh5U0ndciXefef2cho7F9I7StFd
8QTxyFCzf9dlAHI-FU11F0Lo57aK3qFv1
}

