sprite $image357 [168x241/16z] {
pDO5LWH140HHdEciaVkV5eV0jPYDVu9udRMoxMoCaKrlt9ENPi3zcCXmLoBsIYWF4uWy4vDySjZV4l9AH3uvLdabv9M8yp01UIOcUIK4bQhITK1SEbfC-qmk
Vz8QdToFYSHTYPmfFpw0_2qH-MDYaZycLdabcdyahMSwTgIU72MkHER5F3cLo-AlhEMM_Z3dvNUTwzwJt_DFViyxUMfUuFwKm_YOLC9zcF1KWiE4-p3XheJl
k-XtdTD13nFkoM7yBWBSXmdD7_Ol67ya0VTXml0Z-RlECz5XmZqv3bevBx_hBD_aTC9N2VTXGdoOe3FnJavdKfKuA-cydw8gmidfVAXBxL5AvK-Hbc9yo-Ge
qaBfOR-B0D8OttEOAD8eDKrEvzlIn5L9vvip5HmcwFp7yJdCZix-KYPlx6m_KoRlxkm_qp1vNsV_-BbcnLwI7TT1C01ZwsaU-r_klTqXvjZ72QM2PfJXL-87
ANQKSMUy-N5btAaLRtu-c4p8YyxyLHeE9hKD01elEFCnnRWIjBhZpCOq7ym1PstiELCxAX_C2Z-5hZFVVE8mSmVFYOXngT_oE7C_FkHJfQcOvYz9Bc2r3POF
JfMcOfg_9FjBM90RDFg-vtFDpry_gDk8HH3zztn6chyaNrslh170ut3s_AfKcuzECAF7EKJuwFiheivU2iSq_tfhEZ-zRZRn_DaPZscyvMo_TdWKVNOoHsAQ
KdOxCuPduHUd20TY6cuvpmrWYXO6d0-f--8B3yvhmCl5kTvtLE3gaI9nrCdjVcZqP6xVvWYrbgN44dREKzFUxkt7z_vPn74kIn5P9Evifk8hVAi3cNNsnzFv
a2x4b4MTsQVHF1LpdcjOzpnvxy-b8yqxoPZFzihX_-zORtxUEJ-EDJKM4ThrDdASlZJljCT51IixE1uRaF3KCJh4TNwEwRznOWM-JlTsdIIUEm2KleCDaUlq
OnftwiQasriJj0xR-bQTNQVV_BXJc_hZ73hGe5L561ocutIa8QVAp5cKLsoIxixflkSNOXftTdDQFCU9XtvxrkqehdCrfdcdBaWKEcLiPDYqvwvplVdhJkQd
ix_7d7UR92vl9Oaupe1qpObbFfqlNj5LQPCqM-swNmDE9wOhJcfwJz-TfA6yhYBpHPn-J5cPZfCLLtyxfuOIBZKoJh_vB8peE7cUaldBsU1HUyxflVWO4Tdf
EnbYevkJjmUpOChfDnz9PCa9zUR4Y--reRR94dFwKXluLIVCgtDSFnqMlII3JXzgp6NdHXTdlNuw79LajMYzWawefzFYsSW-Y0ITViMSi9iJbUcJyav2YZZ1
dFr_zkm2XM4m1iCmTKd2xd_QQMheV5_PMxpOytiaT-oddVQQCuEvKSrPRftvkt0rPzjidNbZXfpJYuspoTwbd3E6ZRFCHrBF6UtAQUNW8UhqSd5wAXMTI-JH
f5BK6UqIlKaxlSheJTmPbkckkZDIAU-CltBYh6qFpdmajPsPgQaxlRK89UTZ7qwSE77Yn8aJ9qwSE77Yn8aJ9qwSE77wZfmuSUAqVJWFfshhPBbX68R1y3r4
XFT_sgvqDrGSsUmWAavgJf-NtrF6jm4xEid_u1nKPznUjfUJd3WBgTz9YdD1wdQIuXIesLahjQD2QdQoSjwBUsfragKpUI9rELLPzIvGhpEeAoeIgSb95iv2
wdLIfquKKejpKBRKUvvSJdBH6SBBeyD9MTrx559n6fHBlGjKd0QbE6kfE6tCkdSrYzEZrDv_cFGeJeDIdL7myfHE8086fJYdlD0VWKYkXtc-zpmcrwLKf_A4
dmi4F4frOiPJFheTWGqd5Xy-shrJrkvTpU_CW4j9Nghe-Cx2fIIlLOHExs3NkLvHmybY_TxprEvzi5YtT_qnBlPE_f6pk97jta6sdJdXpNh7-TxPsQMA0kz_
mg7COLqQqhk1sVwNAJjgA0qV-q3sRbBcRbDeltUGD4lpTAftoemF7v7SXj8WNUsTCil3rzuRJCStQgLtKEPz-6kzKsQHQk-eEWhI3ptVEsLMgVQ-hlHB3oNm
gtFGkp61rhs3_eLAjNTLxYJ5ArESpEqZ1RJtmOTEe9FU-UXX8WK23QNfuMVlejnAci6dSt2ZAVDmSgzDdDnlFvrtWdlkftFR3N7kkfiuTztXvFQBW5tv3
}

