sprite $image140 [238x154/16z] {
vDU5SUr054J13mPDgqel_smTW9a4Tqu6NRChkEqKRBUE05giBTuL04Z3i1NxXXfkeCIxG8itr7039LuVh0fBanMQhCY0pyG6Rton9Yi67EAvnzdtQx9Y6N1X
PyqhVguC67RAldw-55aXHLPmLcp5lW4TyovGujtiKyxWjMDBaHNPplDVD_lwGeiNDLneyIuEBZN30fgiMFOxn1tpEbTDLgJ82jiEdud3vuKMhnqwoxzHulJz
b7K39TwWnGjAl7SkLdg61Pgiq6GbspV-wyRF2otUKCFz0orUasgo8j-uiBEyHhRTNcvTZUmLRLOztlNVdPdUU47xr9sTu3YEmr0O9hLQV2yzzx_jW4u4eGt3
i_HM8c_meVYNB4L5Mr2ltMb5j0VDTznfHNBeVA_QeYNyEY-jbAmDuRrJAwccr8DxfpRPoAbes7p7zrhIakJ0-ThtMbghANQ-KwiWZHndlaTGxvZQ3BYM8saE
dE_KakWa0NGfHMl8V84ojJG30RA9XimNV0574f44SX1c874SDLLDHomkNw_NNm2QleyWaiSWOMIMAf8DWQm-x-UBAf9AfOiDS7Qg8Y9HyiNhFUSlyS388bBc
ttTgWzm5mTVKdiDtldKS96dsqVhidwzRbzPdvYkT10ZJ-i4MBGCnh4jxvbj4P116OchFqwWQTb_YgLtppbUJTwjr_d4rrUJvRc-TsiL5Jo9Yf9RQisi7X-Gz
Jr-tFcZTQqr5MzFIQwt9jJnKodvtGJZlKRlorLfB-sWvHlDycs7R9PxQwnWmalWcbv95EacGHRRATreVjIjVbTvAIo86SorhoRbg7jZKEhNttYQvLzUITf0S
P9PIf1Ys2_PPE_Cj-TJI3Aw5htEMPjWhs6VjpFV88bBFRc67gs4fLKaT-otnitRcAuq0oVvvkTBwXNz8mV-p-ioxeAQ3V0qQZ6HphNp9VC7_PxsUleThYRQq
eWtOQ8c_JT7pVEw2xTCjfrPK3mG8zZvV7MUto5DRYkSR8DZRV9EPaQnLrrrGgY52i6lMNL0oN9jQFh5wtWKR46I9r-2TRpwrjJKLgKIMN3GT-BfM_W_hUif9
IQkMetRNqhBgp3V64b_pbPfQQUtKyW2grZ-NBtx2gVESRqwrzVAE-22nxe8nblYQR-w-oOtcMbejElFTzTHvphSsrn9ra22xICbI1W84U_SncKujnsW6abr5
Q_9y0opnxUcRZ1naTxK1JN8HptU34_R_v9lWMWuZZMJLCdz8sJxOkvTOrKAN0gw6bdaN313iNRwINKjscrgVPWYon6liVVhMJdA0N5hFDv3r-fHpzckkdPC6
GYpnrTj4kXrdjrLbJJ64ilfyU-ShxTJs8Zuhto1Bl8RlbzZksbPRbZNQiU-fyvolgjRIQrtS-HBxDUywFtuNxBMq93u_Dzy_7UpzntEllQXyFzg0h_T9_EEd
xv6qhKrUemS217kNRxvkyintrrFdEL-Lswc6FK-TvzDtPBaTppV84b_lWhUJ3aHPukjJpktaWL3MTVe-vBjviDV1GxuT0OBzWNn_Q8dtoVV7FvssoNSZwu-V
lXq1WhqC7_CD4EpTIwpSJZ5iUEeyZm5Mv9uBO9Sb_l7JLm4Wo19VxuAtMfzD_nC_UzkzrYT0i0_vNhN1hFDZCjzherbNldVQYDZrCRcq9044j4xlobVTwTgO
rddw9l7fwVnl322YzPflNjgms9LlIwSJG63h-bbVfpQqTPw-VMvoSAiFraJ7-dp3dFXM7ovjUEjQvmiskFTY3UxzVTQ_0G
}

