sprite $image291 [246x266/16z] {
vDX9TiD024NHcIr17Nd_kyrF-oUa8orwTmVlG0L7jt6sNRORo_w4r1oxiPeDjTp6QZP0CwpxkhyXKOEs0_2Nkq9iba0jjssePcCr6p5w_lC-zgP4pTbc_nJh
OpKRQhdjG3NRx9-VVQX1Mw2QxPZJZ5dpRVynmHgq0VvoLrXpDcIq49i5yA1B1shGDl5ZYVMXvcmn-iD17wlPGCjjWMkMN5ClT5-ijN3BdKk0pG9xq4_6_XJh
3rf8ossClznk5i5SAp7ISXkmMG3NgW0Sj00kT84qPvltuQ3_e6riSt_GGbfk0rohmWcROxsBjDm6R1RIWpRWe0NOBC1c0Loh0d3G0cmMmBKg00Sjm6O1Dile
J_jjap-Mz96Msm3Nga1wq4PQRWCs2-b16t3G0cmMG7EtUfjxhMh0GGkWkL4TmwzL3JXe0JOBi5bE-BzLltexyQ25jDm6k5O5qeCsqd8Ri5acVopf0mvQWCq2
R1R0jIe01ot0PW5Sgm9mq1AyPiaCMhEaieDmhSHIr0qPjAjNId2Q9JAzvkU-LdPNldqjoQq3CHY-NHDGy_sVzcG7eQfTr42hnU7yjnF4hxhfx3a1aiJ3xl6b
vk_gPzq3Nup-plxkVWUpk1yPTuQvMVDT1zsxzpRtxdtDMW6ovllyR3NcRnBtBeCMPJTl0C3OUBcr0P30lUv8ixg9x-onyN9h0CIzvNBtQc3iRbQrF-wHRExL
5FUcWrOryMs8UqkpgZy-nYlNEy3igJ-kZtim0EsfBxi7k8FwkplSh6XVlNoz1xcBMjOyTz0aRbAhEzBi_zzgLQlRCEUgULPBCcv1xwVMDLTp8DfNgrlD-wcr
SRxU8BTNw_KUWjxlNkkQYpcJxQlL3SPrjreR03TMzsm6zfvglAMQxwbcY7f_zVxgczb7ZlgvQLSzm3RLwlRDS-Qedt4VDMUl1WBK6bmtKBDN0v7g0S13S_Pg
1AjXc7-d1d6HxQl7kXfusGmSZHg8LmElcNir06F5drBZHJHg_btfgm2tKmCdTHtowacDFTJ0IItcq_SzhSQtJrBZN1Lxz7NruQaRjws6f8CMzLNsV4LzTe_R
rT2QL_ciMiOzRbKVrPWxDFcqMjVSLrSLUdJtmfDgTVlggZbhoGpgIq-ezVd3KCll9nVCoyZxrNgzNVKnvqbD3-shbTslkQzcC-Y7HwsXTGzn6serFpzghLes
XgskployMlj0l-Q-cXRQL_S1lTjJg_aPjUyUhwlh47CKkdTJtUjgDHE9wZbMrdnTNMhEKgzVRrMlXoZqkdiOQY1DlVwps7XLZKIrzlirltnSc6XVxL_lgse0
0QEsVnQxTbv4g7ttbVCY0UspSKKDvAhxQ1qOQmMWDUF0o5Jxu_RD_e8_Fsx3dAVMjbBxxiuyPwxQP_T78LFLlhi_24bcgdrtVmnoqSrqzHoG-bDGsVdgFc7q
P-3tDb3hclSd8CKTe_RT_G4ex1orx-uVprD9Qf_TFvnIZjftz_-ZYjHIrBwxVp8RTe3QPijpLQqbgFs8_YMkkZrrLknwJpKtLW-mxpurHfHQC9glFWwIH1HR
CFUpg_vJ0p7e5OkZFchEx-eOzg95r9VCUUfQjWXxsNnIXx0lKAwhgwQgyH607XsbTrySjAeHC-fr2O2hPbKZLkspgsQiUeXwpRrWFZsbYh-gHyYemLix17tm
fCQEwgDApLbg6EhrvTvNtI_ttkhUh6XWA_MXPa7lgIwvq6BUNwtB7Qd6lMfTxbGrRb4towtnQzN4hUvgbZjPxRkhCMUhuQh5JEIhVNVLYXdyQZLnfrlCwUhx
tK2msc0RQ4Ig0TUSFEg9_eYVPGP5dJHiu7FCO8QQw3BGsUeX9pNT24LhUbZjNZEOeSPLje_c31asORiHY-xLXEU6WGvc-sPGrFbix8QUm_lVveX6zwq2B7Ed
pcVRPioabXqUcZEhTOfXFcPQlEY-RcRDl6hT_PAPCpEAsuw2pWniu3QPOmP7oI7heBFTcY4MSpfRUrsiw7otjkxjBtG-tA-cjhzx_X_RdDotDxclxCky_yZd
Tk4PyPy
}

