sprite $image300 [213x174/16z] {
xC-d0GCn400mw6xllsrGacU7laiRQ1qE80OuMG5AMa112vJG0YMqK8BZ05OvhwroVIjKSiv1wNwjNlElLMuZIlLVgzp9frlxm8qh2M8mF9ktMGJc_gVTwD_P
BYUMK4qaPUd38nizW3gKwzyEdcrfK7PjL9q6PUkcXsMJYpheDwbpImTDwE0DB7i_gq5TShpxzpzChfcM7mzKztJGFpr-zh-fYrZ-y_6mNJggQwPbIxRElq6r
_ER4XVQ0kgE3a41TmIhnZZ0jFzxrF8V89fkd9ViGbSdQ3i9eIDjUb9HjK938qcan8DuXUpj8sq2LlPm5gKSjUL42eK6jcvRi1hMkWoetg7siiXlKkcd9_WPK
uEOK83MeHHrKkK7jOvL9YzfolCkaGUsPbieH51ryULAFMd2ybvr3mHeVKnOrtq6LmwXvLjbPrFoqP4-XO8qsBu-YWsbI5ZNFAZkBck-Wx2ng_kQayZUYwYZG
mM3pUbJfXpso0olRl1wbWouyhJm9bFWHbPnMVaoa-Hc1QGN7H9gV4RWv1Pj78e_f3IlPl1wbalWveGxccqUUH_-HR2dDofD0FVsAelyJw22i-9W8_qbXK95f
1SRKe60Lh5W7yyq3zJ6M8wnyyq0HEfYRLg1v3IhQGMvE0LA3UkbfbHr0vQTrFisI7KFD7-yqBuUQxo3DowBcMRBpgFpn3elcnL3pquAKHSrtiEmmQfvL7aDD
tfp6KACt9-LHynqyDOCAtvmQHS0KFzvBvsYKbE-Wk4CaIOCiIA3of8bfrI6QCUMdLOAaYfFo7Sm_9aZJh9T-J8cRKqsJyjFYt8kJPZl8cWP9uUCTLELDWzC2
5INbEvX7GOgoPb6GqgmUfK5J_dW7bI7bEvX7GPfbvL7FUDnF2rIGD3yjK47IV0T11KdpB523flpD2LIGD3yjK4dIV0T1vKrvLeDAalBJ0XKapNSGL90qpmAL
Cysp6bI6b3_UGIL9ymyBL90qptg3ggDQQa852rG9NPQKPmbKwQ1Ba_8iC4IxJR3UDTLk4gghIB1qYFQJY21TOI8SVxg414jbksuXaP7cpUSo4hcBH2uZaSjC
v2uJkGn5BaEHor04r5r9cVu6
}

