sprite $image25 [235x171/16z] {
vCyv0S10402XcchzkusAt3SuODQ3AG3eJ969GYQAJ1GwKsIYa8cYCqKc2faeCb7eJ969GYQAJ1GwKsIYa8cYCqKc2faePABeJ3zcxKIvLHq6mB2yO5lBp7t_
jxr5JJIfALNLc3dyPr_9DnWmc8zk2-rrOUEEM7nMOM4TxsV52wdQ_Q3hgTQze4PDvUt0gDQTe4PjydOJLRkHrAWRlTs1gjq6QjIAf_Kzz3Fg3R06TQWJBIiX
GBq35drgBmcqLCVFrDfSgdK3w4pj6LuguoTg1gWkrRe3z9NQuMl9eHhMeMh_5ZfJ4qnbZmgfkrJh7qfdQeEzpsDqLDZh7XMWkLJhtqAD-lm9oQC17sq-5QfF
jQw6HgX92FU8H7_xd5fWiZhKwx4Oeq8nYlF9PTYXtG9Kl0uQe0xGIlseW4Q8oF8HuHo9D7WqNgX-bqDzAXUOsWX_Y8NWip9HlIw6-bII35-ged-UF_gMG6Rj
3lLQB8QfoD80h3I4l3dmqrgYLBmGwbFLAkFpC2tR425_kYyDj1XLknBgKv54B2RqgSIWDQC6kapgKpNYZt2C_hkREAvAB4ODTINKfnglkrHjA34RDTOLq3Yr
_evAe1arslLGdmhZMggrNEfJUxMIJGnSAhfKl-LGVmuybMf7wqegNWRjgVbKhPxEWQtXK7lw5VyQQLF3BwbkxUUBJRKx7w_LKBlHBB-Z-iTgWhtDg6SRyriD
jGT8wK0TxT1mgTjF4qExfSsu18knDdZM9ohB8VQe_K6XYJglygM-08l1P9Yr-GiP3hNRlVctL3fip2yCzM-e3VZ6GaQ3pmeRzR2n38-scDM7-f6mRRxCr5Ri
ZvfBjU79TA2QLIhOna9O7-f7BvjFNwWzmKlvPsgplqoCHltf4LJ223Ok7VNGrffvKZzVo81-JcqPNgH6BTzjhCHEJbe0QdLmoaQ5kNH67GKi4ZIgMmjR4KDK
lsedcMtO9T64SnMip881AbICOV4IgWBa6UjEcEV0yn7TXD6egwreq2keYUdreL5rTYa9OOoQCH9TI8NIyMLL-Pk9OGQhYKeZr2gCWPXMKdixd9QoSSYeny5R
TTuOepQX25IO8rYIRnhmRCZsfF86KsEcTh26GcSgoZ5AOFyc-C6P8rZYOsPA9AyB6MsI2axKQUmUgOCFzPUDKGIgL0VhLMoa2dzToC02LYMXYPh1hZ3ilynp
t5Xax1hr7MioZF1X8KEmQIZ7XOmDFjk42LtgSMFnWuxv7MoVpX6lL2J-QI5ZFk9yQeTdNIW2DUexsFaSSLp8i1FVH6tJMTId3fFYhwN4Cb7DId-qaj3FZxpR
JCsmLuJGeyxMJ18vI6Ug5RIoxBOiuZtTBpXbzwQ_fmhh_oGS7Rj6TR2UjTavufng7zlcm5qjbJ50HPPg6mj3PseSIq92_dFW-OwhcoL0HH8M2enTXngsCY46
dmC_gID4LIi5Tgb3TR1EGMgFKZ40TQW-zlvKOd6eFdOzTRk0Qj00DMYDFTqVQYdBgIJYK1tiUYg1vbBZq3WrZWqjP51HJ5rAPN6eFdOzrURkOnsLnOdTQ2Mr
bezs7uEMLb59t9ZzQDrxI_9yE4eLjBA4IYn_f8uy76oKkk7NER3jLaWBg1CqH0KewDpUnQX747TurDwaaZWvL80wOLU_joGL7kNcK0FGE5Lhx60ZiwLS-mjr
UZcw_fdAieGAp05i-0qNbknIVUWYAWQiSIgorBUe9BACsfbxyx5ngbd7twd4if2wCLT88u0DlhT48lMFL0SQfMRcf6TF1nkVxbiiNFz09P6rrCG8saQEDJO7
dZ_q60ur2erJWUorAMO76ve3pmSTXwWiYwbv5zQ9wc0Tgis1vyYXng1nQWROqaHri0xLVH_OfvB81TGD88DHVQjHStsx4ogn_Bt_pgaTBADws0eBwyxO3Ke_
EgCYQDce3lPgAibRKks4og1jHdMiwwbheTzZUzgf1LJveEAsTGTx8PKNG4-m3JBh_YmFAkgU9WVBiZ3dlmrApx7KMP7jGQsWTVuHIxmmMZLsFIipxJPyK1Dy
Lfr3TbqBeJws0oH-K07CUZrs-K7gOwdKLsgb2W2D7UmzTwcFvPS1lB7-mCz6wWxsHb3VocYdfPtQFazDD72d0cHqh3SQkpuMwqxjdzIXFr1IvD2PnjVetb0V
Yyn9MP-w1dlTg0xs5cFNjrfzn_6ckWpQPbG7UokeZrLV1jM1PLJ7Uhknwv-VNgZ5g0xsnhlKEh5kZojFDwg3lHtKjr9MAd9HAcz6NMKblWWQn_QIirvTbJgC
kWXx9JIEjQ5SZ8e9e0u7UzEnwsDr73-e1Dh63lQMKD_Q0I3rjbCLxDotttZi-jWDda3xAHIsebZwTr0VcxzGCtVdzkw-OzUtLW0m96mq082OXuEzmGKcZiKn
b8fW4-BEdFE8MUy0zR4yTYhlO9iGvzDZbkuyTdqibQn3EMDHgrA1Jw9RG_qTopg21uy40AZK1D38mTvmxFhOvrCOt026KfqxdXj3VMnLNS5YrFCh3zrmxCQj
QR1IjqsjOz0PblxlvgwH88XXA8Wka-z_tcMUBYcS-XqvVcQI8fgKiJVSUwoEyVvxXTWOA6EFs-LLDfxKpuq5MfEWV2Dp72zgy-wH96Nh-AK-ChfGimP06SlK
z-i7KDEWZDrzKtUt0gY9KdxtU5CF1JKDojDJIqs4ChQbXa8PUrXMr5GfMq_RWfeCvHr5GSs5ChQW1aCPUzeoLI2b8KjK0HInG1L04SlKNkh0Qg2zjOTgi1rK
X2sbBci9TM4Bg0rRI6rO9PIj35LY2Ih5WjIA1QZL2b0h5g1MB4YjLe1QiG2rOcUHNW
}

