sprite $image102 [236x164/16z] {
v9g7ck8y34LTr6B-ylvlk_YZtXW7XI-Px9YplL1EvAkn5Vu_03lp_rTWLxx7T7nRGqPNHKOtHGOtHKPNHKOtHKOtHSOsHQQlKPrEfsyfQZc1wz2cbUzOlXU-
nRJo9SiNNSs6Dgt08yTRlW0-SBIY8lC7Zc3QTxKPewYsjjOoXccRsCbUCOOfsXRhCOfffSnCMqPHhPJ9bXd1rC_efiZefiXVhIfdcCx86Hr1rXfKAASO6b8Y
bbziQpE4qB8baVnEMmCu1n-9zBVPjg9-uiUwHvignKOcPI8MgH1HIerk5hkYR6wcWqtpV8coskkU5V4_okL2dRtD_jevSjSqlcazocbcoo54MR5vFh2ej3w4
d090RjFAOQQQe4PUb3ogny-HeKBXJbP3_BP97QRbD7CrinyqjTpMr8_6S2FAwZdo_bz_hDD-oLOZPzM7hJXCVtIsQaY4idZ0d6TzQcniNQO3Pgk6v5T9LLAN
wYsa0fNjgQAhpTdRz56IFAjrp8uof_embDMkx0_FLcsEW2gaiEgoBIFL3PyekLPnsNsJt6-YyLKGKtthhAx2cdWQN07J7MsjXVehBzT6mpdEZsunIrFOpdFr
R2TROXzJqwLQy6LXIyRmniT17GjhqL7O6bjxmtQcg8Ch695RbrLADT5ybKivNXSt5bR2bMD7KjsqNU3kbYXUHPJprOz2CbE-L9lrLM7PZhEr7fs4GOSIkt7r
2-7vM1TJczXiHybQ5td_PI9ZbOGYN1gXzEGc48cVjxK5s547dl-pyko083dUv26mUzlA6RUgqLBZn0xb8uBhhhPomM7gS8KE9UOYWUkUidAdP-ftpOg7FZcW
hdrR0L1rVM-Ya1Wk2fi3oEj-jYQ8ET25znPXn0OTodFjThKjauAhweer9zOWEEUMwEXG6VhwVhAb5ElQ-j-SFlrRv1n2P7LtA1XER4gPkvR917WhAyt6YMCM
kybbKuhtukPt4hJfLWBFlNFNQglhR1Ccx5hgp7gv47ATU2U-kf0d_RovQUjQySQsVy3EzzkDESJ7e37hkmwLzYbhEVLSdR55iufWKA-xVBBAlRXoF_Yqq2vb
BRC9AxhwOukJRC6Jd5B2lwrzYk3W0t3OeGbFBoQiwEgFRJljPD4gcsvdrcXtb6kVYb2uLZNgTgRbvQTNmTM_a56MBoinfloe3bucoPqzPTv1jNGdh6N6vBOL
k6zLWxcm59KYZitnBb-KNKnFKz_Llv1HDifbwojCIPPkksRiIjjN5KmBcfuAuBLjRxLvRc2fuDZyHjebgwLfLmLO6ziSFdp3aW8GispSWwVsByjh9XENhSGd
MpOVjJC3srQtj44zWUkd2rcXG9aTeZbqeAri6rDmzTksgid_8JoXX7OS0BQDmHjVW2ksE6L9Mdz1KYPH0qGefxQE6f0ajYtbv73rn3Q5A0i9ZEaA_2EcMyAC
h3kPeklwXImmxlteuuYQzuijcABhUbj4ANtoCLD90OcyWwd3TUrfJmZhsmRPMZXk7zjoyhlwOziYGfHIWk0I_QdMBf0KY88WYE8Vv_wdNVUAXPcCaSw-mGig
yRkBo6o7bAQL3vdVdMm7c2-mnf27q-PRiFWx6tjFd7UxeuD3vhSTv6tZVzBRfvKCcMjvjbmQrlcpZLUjBGWrgM4LP0iVrB1MoNPp9ria3MkDRFdRniCTQLXB
PxlSqb3JMYFR-syRsNpJQiXstOWqhP9imNpJMZFRNMOB7jImCkmCsJOW3MlDRDlcBpRdcr9WhP7jdo63K06snjj6DD_KyY43BVoqjmDIsP0toy_l7y5yHThF
AUyQcAypMn2gCLlmEgCUCWZLekNpjMNBfS9i-NpzGpuSWNIU8RT2ynr-o2HRBYqmPABbeVgpFGAfA5ik5R_-781Ka2qErPOjdwyjMourPildwy_s2AG5i21R
89LcUm1IGxOqL5-sxG3cwnpo_dG2KkEGsoiCp5Suv7SO-E91f_rSAvYl3lif0rA9DgqWL9CshKSW5MZ3Af06bbeFG6hJXWvGBLeWrMA1LAi5LAqMIBLQ8DLY
WLIh1LIj5aYrMY3LOW5LgmLIhHP8jTgGUWzOnGUiuWDMxm6h-81LVC0gFc3r7h2A3rZ51wpY0rRl0QluW5LymEezOFLh0LMh1LAjTXRfCm
}

