sprite $image412 [151x217/16z] {
xDNPRkiy30HWILuY3UUqx_-q_t9I0caGHWXjmRpGN7Vv88x9x_7vGlilty7IVe9WA0s-eg3GVWNXdaeJugdYkMepScN5ljgx12XL75Xj_I3QKscYeJIu01K9
1bY0AvT5yoGQIeFHg7YmrWAwq0vdq4j5Ww6rWAvsPg8zbGPZbxe_XzT-RKE2Ox0sB0Y7qhYR7j0r70K9YUAVU2YGdxBgU1Mfh3XLXr1PeKf5PSLP2Y2f2JO_
JKWK6GC5FYLOgJI1lh_7n4FrMLyNpA_BMd7HKv4CDZ_DfPlApcKglasqfx9PRNXCbCsI2vP2bxLU-FtPh20eCbYfD9Sk1JkNBWKx0KfbimHnvaTbjGOH17ag
PTr_JmG8WoAh_gwCUZ2X8m9rZO61hZmC3t8w349V7YXQiQjHodg63PYVZoKulM8G7cSzLGou4gMiqoSfv6aiEMjPW3oFPLTi_FmW1ikks7YKh1aTri4j1WTg
pobPBBjYeuzoISbcsPCK34HXIQd3yaxIZv8jfJUiFcp8KhXbLHNXxm2cowZOMK_LYgBopkU8uJAMnMaeh4cpWi_v8w8mPyNyI-6UfP4lMO8Ep9ga_oYlYigL
P2jumLAOesBUIwEiZQIiAHaiSLJCVMbI-s4LaBAdPBC-gTZXKZLkzrgHDQTtB4V5_9T6MQKjARrbySD9-Y-DiXvJn6AH7qtIUMbUitRoDKltQdUIwZfoQRBy
Ogr24WOBK51tMO2KOvT6MRfDQxwzP0b-qgyOXChoNnfb_UMq9IM3fQu-Z5IMuzAKHZwmTb6omNg60JYBXJjAj_e3Qo5v9nkibvF4EQoQJDPzZnai6pQObPUa
gJQhFqa_g-HdrcCMq6Br9-bdvHiNcrKgQR5ic9CbTLjt_6LjGfkLTw71wi0SBDd-JYqt4Y1jrWRIPdKgPh3wbwQGfCqgZUop-XLJLlVIQEeRLgvaXzM56Iph
qcXMcxMH3fPnZpeisTEl58krWWwMMJ6I5EcMIfFb9QjKqi6oAqO25ajqRVTO87qiks80APqxirJPtx7ePDakaEzP-jclOraAqyhtM2gvQUNFPsayh7eVvnYM
nijQ7rchdCqIvn1lfBAMHhfPTZvYwO61ih82BsQLnsgn2aEmgbvgJGYM55qFWLXwXcei5eekhK0iR4bzWLYQ30PavSQ0h08Uo2ZMAep7ofMCnzg5yLWho72i
qiXmh7mZmx7Q9Wp06fV9cgp9cgp9cgp9cgp9cgp9cgp9cgp9cgp9cgn_gpTp98TX60Zc0k3v_sltK1KKiAps0OEK9wAYxHAQcBtylLXnJIpN5R4a3L_n0bYX
n8B_JP-EfJq35NFrOzsKM00s5ol2b343iAbO4T9zB0UkNgnmbqwmt6q3i4QiY9HA9yh39Dkm8ZJaHAnj3s2rpI-n2AmVAt8fC9Pj00POzJS5oWzNCKzTME6X
3Bi5YZMyBPq5ZSzJ4vREmyOVfmQi48ID7oVvAQm85uJAPmHZhFhze_9XnHBBh0MAouSLswbgM890-R1Y2LUyVnmsVc3Dc7LHSVdmgtEtZgN0vSF6RrQuYOBG
WdXWVEqcweMyRBnRmjKxkLu-n-4jvOcgNZxRSMo0AfJFEvzz3O1gBvyw52kFIpMfhDuq73I-N3wXT_EQyVdGC3_WGkEvV7XLrS5ugMRv5BwfwbYg3ZSHJ6zM
B9S8GuNfKzdiIBby1EbI33u825BrJ9BBXwtgd-JZyb5JQ99SFW5GtSl2VNyghCyEnV9Se6fJpCt8z2MJjBlA2z89nkKZI1yObqy8qWi6vQFvEVs0DMogHI_C
3hSYGj9oiB5yGYlZ8vMxmVpcPS0ADu2Q3vPOeSk4iDPpGG6k18Fl5PRbPZPfhVy2
}

