sprite $image182 [156x262/16z] {
xTiBSkGs30HGSIIAFr3tFsuop5eBZr9Tic4Ci5li0yGlO1UW_Iq_ax1kUqhvcPJYjeR5IHunvTUawC0NDWRxd7srbSMCaZOxsfWPZf4kxFb6qcf1UnbQgV-b
N7htU3VjaJx36ikhBmQxgHNcOZghsl6kLOPYEglQHKmRgJQrUm0QrndKZfMDTOrefF6yltRxbKRKpn3PrMwxlEY0yP1DxQvb6pC3kZTkkzUoCTazNThUiJuu
xHfGEvs7NLzVj8E0seKth0y2D5mxtVM1QTU50lQ9RjaiQeVNHxyJ0cVCe6otQxSPbOtZIFUCRN1zuE0pfbesSUtKRvLWdsnQwyEqTlXMsTOEhm_hsks0Pbox
xQLihOk2FjeLruUyTi6WR40dUDWTh0-Dskr1xLR9QvU2GTcG3k0KRfNWwsbNk5MoCyRtyBjk5Sx_uuB1-a0wZek2MwMZosUIu5RfrAxaCuRhuwe3DgkoSHot
6QmFYAkPsGpM1qZBlrCGBO2owQHcbcfsgwwXLZYjL2zb8wf3ncZr2sKZFLSxOOnMpTS7Sx7KPqnl5LyPF6NGajMjej5y8AjrDRXLo9NBXwpczwyFgYKZs9ca
iZvmxJ4Cs_2jqdTXMqYWRBekRjCk6tOLvhfalrEsfkt2Dhm-r5pOfd6hIE32jbssFhxjAiWclrMNTN_RzGomoSf6LA6hGXUmmVKXTnNe0ZRXhQ8ccXUsuLkb
xS8sVAlaBiowRukuRF8r0ODj-4NbBe5j1MCJkuIs-7bizEBA0fVKngyLfv78fMBxS9KYS6dOSgcjLSdw-c5RoY0obznMW4VsZd9RBR9vgTfg4RYqRKmdU4OL
s_dpJjMzSUdRjWe2NVgsK0nSjx-H12vjsoPmgTiAT1dRIW4oOzi8O5dQxcNQufzaguvjHDMlhLEhRcszK_Lhw-slj4tRj4tRj4tRj4rR_6DiqpPjqpPjqpPj
LT4sRTEsJTkqgMJQfctQfctQfctQfcrtR4j-RMjnQtjalxRarnQpMzkQtTf2zcjBVcqnkxMjsQqj9B-sbDtQOdPhYzcdRMKqVxP7_WbRpbd15iMsFA9XsoMs
uNgRhT75XbowjlJodwzqnvOlgVNdRTV_zqhjfelJL6pNpjIANTUKgcGhvLvdqB_oKRA1FG1Tl0MADepB2APjuuGB2xdKRLS9Od7OEsqSX64Mjd87Pc2xLp43
6m-06Tbu0EpjjbQ1Zi5CRF2VB5ZREhNgriPqxcn3LvtQHbfrPIlCnXxMauthlDceqQchpcoj4tLMEqSsekFelt5KNRtfSHpKpxYpTN9g8tUsnxb3YAWvjGrT
zshZyM-RjccRDfgsEpRwsst5bstQgFqRycbhjJ6TAnlLyTqxSDvihHqZrCYVZOuFd5_RqSYlhJToPgDsVCIXhVyUdBlzHcnmxkw2NrjlvDR6S0vjz0lN_Ta6
hZ_7viysSCzKDpia_B8HVUZStAoo_B8TGpVYnRQVjkFevCiMc8tfFDZYmcm3Hrvi-y9iN6TlYyl5DdJsjh8jtCPYRajXSMfBZsLnQIinB8j7Mzd7oDpPyhu5
fhAsSHSRc1zRtjV0ELVROM1ZBcUs79dBaIqnboTRYgpszZRiihVbj36N8njpURBb_QPBT_U2CoInLUfTR0CkYQtKHbrg0-jUOXkwtcKsu1BPpeSLs2xhNfxC
ViBGVTDsTScpbH5Mk-_Oohfe99PdMEs-OKjXqScQ2qkbhzeoEvFQewlq1LlQmgARi7_IjPisjZ0qyqWlvRxnuRgyBLj65Fmbff_ef6AuTlYNHaPvPC6oCAWT
UqdhXEZg9N7jqhfuIbXZogNaj6-M5Vi7
}

sprite $image182 [78x131/16z] {
xTg7SkGm20PWLqaWjE__kEU8OSSPSfonkEv_UietuZTAtUc7MRQKIoavxUiy3MPDvPIqZbXB5aUIxtih2u1OAoAKdhJSmvRISr0SyVOx_SqyPZq5cSkRNzlV
6FLyyfPRfU5XjSPXJ-gRNNFo0n1Cl7Dz3ettJ309iUVT5YuD6JldKtrfyPKcYF8Ssp9dNThtwjlkb7Q_lasLPevhrxV8SZGTVttPcDDTtsvWLdsBTpdiSHVx
HbtsaBdPN0w7ny_MiHncVNmwOpaydcZ6ZV9mfMUqD4u5dccuj4Rl1GOqIlD8Z87xHcb9BCJT-79xKMAgPtFUA2q1CCMQSQCS4cSrbiCbiQQMmoy1d3LxEUYG
YY41A4tTA94GR4bhNt-vfMf8mdofpR8SRabhicgLV9AjOQrAGYLTqCHmI8Q6NidM4C1O0fysdmGbkRKf6v9VIoRbFnk0GVarmt5FMX4YjLOnKci8-0zfZvR_
FktH7ctvvTgZFTfS8hK4WTfMM8C8RIc1sfmZjLG2jQq4Qbk9rBAj0R_RgI4T6cf9ORPs-fr3tYEI1F6o1j2rDuK0wXStXyR_XT1dOWgy6k3Rq9HV0_QKT5D3
G0H5tTEgUA0blqPDFCwergZouJY3MlS0OhGZxV0mI7irvcAqrhM6GRrHqDdc3utpUxL7eqYjrafXMgNNYoXCQw_E1MglA8seQnIbjKDhrC8sf1SNzJMa4jMO
te1Qzm8qc02ECMFkGjrOEpWQrke-iSRUa5PXdLZh6T2mOjccQLZZz-PzwTQOXWWYZMc822LjB7arM_9hjkJNR4aqkg29D4zs402RhNNfsWkbu8EhpTGIInUo
zrQGccXwpDNrqXvaJsk8w7_brWRTmSzQBskP_9cJNb38cr3kB9azgShe_N9zdBAlqtYs300v3L7V
}

