sprite $image259 [347x234/16z] {
xDe7SYem303HtxyaCyxzJviUUiURvjqZlD486RYxD3CBDGPMkT4VHHZOOLdkgtHXO5svGpfSr-VgUXu8MBdk0WHNME3pp8CB65n75iOLbiSL5hXoFRY0mNLa
SLnX-KFCWuiVN4UMnnNsCAv53ko7di38aeChx1BN4ahPn18MJ5WmOKVcs_T_lbFXo7892oOiL_br0TSVHvPBs6iIj-K75uuibx1WmeBvlmskScIvX0NpyGNc
o79rORac_WyNdmSNLxaBk8G5SyboXIFB9IoOkm3C_ss0kGkuGbWkl-424nRCNS0Lmd892-PNXs2EB5VtLSlbmGNsVIRMGooJeNLmaqdSX18t4ahRf1AtbRXG
hKsB6pojWqlHYakrs8DRueuPswNjdBY1qheLY7fxQY4kDxIJhzpYFiMMkCCunLtAYWlIkd91sYLkpXf7wrRu3z9wvGwgse74HOOsOtBR16czSY7Q2BT2WhHU
kHojXrXmj6u5a5PSYFRmLYXnhwHDtxvhWRHk1PRMttqXMbTkSRJYZg2j0xIkN8Rsy8yGvUHUG5jjVsw5kD4s3zEAUxdjvHMm5SJTExZb8SRXUYm0Ms4-t8xY
VlmXvieLjyIzi09nFSJGbVlr1jULwyfrSiELUsskN0yn3x4s1BVEnNKhB8Pi1N6xMy6LwygTS70zn7oU-JnpAtJq47jWvpvoczSM80XF7AlwMVjVxRk9Q1Ya
VaXMFAHPZkCF1wtCgFhvHDnzSdVRZntt1v72xPDxop2blVFayhicrwIq--JUC9BItj1snoKfxPrmaN_xNNV4C3FQEqmkKoA_Pd9DhgGzV9rrPilBxrW5aZdj
xLU1YRRACzmj7bpCbRIDqxJvBmKslWgON4_RN1HBYoPDWGslWbbqkB7jajR-tUxaaYFTwJ9X8YQ9_DlqlspniI_cfhJD8wMq0CLrmdLJasjoOzh6ySb54sd5
rMGxgq1o1zfsYlRpixYYQDp6Ac3kHDkEqf84uFtrzVNjW-y7TnkhWCdTQDlNCLeJWTT_U_jaicKZk2PtfMrnNccdtW6I81juHepaxhJjJslx_Zhr1Z2x5xRI
oSKyZ7QEsqa0NkUs4srMkmec3w9jpCujYV1Ps_VkBQfnbRWa3wOjRWCJuQEs7vCjzDokRHKm3wPjjgXpsyujQ8osLHnSJ9v2Mzo6tOGUsqv2DBgcLJ1vAcrN
mVHk0k-bXIG1YPeLtH4ZUHfjmuP9OCBzPFx88RQn9nVpLDfMB2HzDW6MjD4rh8B96BJ5ZNPTMv8mU-GmDgx90BIDOcaIYskIEACTUN99HgBjmKrnOsLdjEYu
auiPZxQuY6dVQQTWs5Km6P6sJpSkSP7le0oAIp8SRQiLckQCLc2yoSMCJ5lShckYp6WZmnrSJ0QdBIuocK9f6uFXcXN8rdPEgxRKTWXSXeTj57T1spY92-nR
iAnOfLq4Owp2DR0Udj279peJL_OjMCJvjgTmzosOTxRj77U-2YF2VXsUsjSPjizRXMjW_tTuUhaPxZwoFrs5A6TCBhYFx39EuSAZxuYPTSisl0skx5jm53V-
kRDNWHtsvvFBcRZxo2uROXMkWUKmR1zFn_shdVD0hY06OUXwtK2atF-qwRqdY_AREC8RpRCDZBaks7rmKvGh5-GfrpShbm1Mojt1JNP7bM85Hq2I9Rvz9TcF
dn0PLf1aFsWt_XTSx60-i-D2saLCBg0D8K9WtnVN2hk_SEq-k1ouu8CzbRUlN41xdaNcXUiqu9xzt0fomSSNiREjppD7G2xO_FRrZa-KAx0RbUkBVHpSCxbW
uzpNbnd3dk5AiXlWlhQ2BwtNTVWpN4asIRbUtDVL-y0pMqKsGxaJGBJLp5Oy1XS2cw7SrYVGLyowj7Ye5B2oWlNP9xmPogpb_YAM0rPmlJStOBHIIx4s8k9K
kjtyRH0VwERelTO8GqGeiddjnj6gERpuisoJm4gvuwO0h_QCDWkiBcAzr-4OzVT2mEL9ryNtSAtNRWv4H79afLoVhVO9H0XizcWoCDem80XWfLnl3eJ8ikQ-
8R2ikM-mm4gvmNhLIhcqo8ej3QpW2YnjBLTaQTiWBB2o0WsiuEh2HHjD9aLM5U-KImChAz0-DLAVd2PPAPVc0YcN1bRAbGjeso2io4gvFB22omChvTB8Ihax
17iD
}

