sprite $image104 [236x164/16z] {
vPhldkIc3aGB40ZKx_--DpFyt7izrMmxQhnUa_Cj_tF6AfV0Wmj8MYB-4yHI_o47B4_8jNO4YoDQdsZ2maIjEzQDRIYLM3IsKb-XWkL8MWTeNAzdnfImNi-C
oUi6bT6mQ52PzeXhzWnZZmLSyq7J-xlAiV5ztDyr7ZGbrsM3ogufBD4pR4gkiTGg2_RCWrn3ljbfBnuSNtOLfTFU3HP2Z-l-PPONw9c1RQINcSgzUsQSs7A3
qnxtZCVMxdRQa-h0TgQCtB1dnbYhlqFJ_Nh6ZyRxzOoV4kxNCtxaVZtZHzFzUiPFYJUuU9X63hVh6JygAmULOxjSpunfDra86SV-l6vGUNbUO24yVDvTjsVu
-BVAGZYcsUE7QqohzGnVrsmjS7R_X0k3kl7_mwLnkPxPiH-k79Rf6LPz_1mkMQ1d-BNK4VVQUFv2g2MBI8nHH7BH3n-jEKzxv_TCaSW38iNzTZBNQU_ydj4S
CI9bbstpdFRExvaSPx_fcfr-soYd7QcJvX3AttFRcDHZUjaYblzipwXSsTigVx1dSZW_9_DZAphXF_JTgYa6_9u_6jjG4WtMft49gL3JdXRRuskZb7-8d_wS
XH9mg8V22R5D691A9uUFBXxI-xiBJQ_-usboRCThOyZbYT0FsASQz62MulT_F2UQXLC-4kIo8qMj9wdoOmrIEebQxfJOMjEThEhdBLwE_RVJSvewfyVMpEe4
su1VXAFZ-qqE9xQj_7IrLiiE_UonnWFD6pRJTEBNa_R8v6hMb6pTZnNX_Uf6GUrFEiU9iMsF1xbsFegjOaUXL-8Wg85UL3AjRUqnSlqijWKxugkg8wqSNprf
eTZwJJVNaCFErHzRTeMyMs5YtezloloaG_xyxZ5l_pTvv-gFBRiY7rbD-PKSwKpvuSLZVgP1qzxLFyWWsQCt1RnHSDlwlnBaMEg6Hlj1SzdozYdKCynuemXv
4nUdQQVkCC8po0L4b4EcBpSASI_9ErFRcpxCfjX6-4YPDuhqOwPZSMNLw7LbX2ks2YzfawBTqHVRzkWq_fD6KFySiYtm4dYZuDrH7DVc568Zd8ESCG7QAEYS
U0Wo9TSFRGkyy4OnvJwAFtmHxjXgW0C--iIPzups8DSviKqJvZU1a4zCoNNE80i-8kQNuvi-6LzodMKh-934fh5CC2NN2R7LXBc4F65yoNLIR4l4H4Gdc9Bh
l47E0JuczmoJ1sf6rAEsAXVytXZjn4GDC6C42Bav1jaTsyazmxG8m9YARtGuoEV7DaqDwdRlP8oY8nV4TaBFC0KTOpA04054cntRytk6gH6TqNEjfW4mmX7R
YticeJFEQpLhCHfnTcpJx9u1Tgv41DBtCF_fjWsJWwe1xCf3NAnJ0_NFQR7Dytk6N0dv9HlnHPuUs_DxHe0ZhYRFVaKdjfDZ6yy9Ahio2K3TN2F9pevjA9Dx
9k2uQuleiW34QWJKc5Rdd6rbhgb5uAYhVcc4lal47bRv4gzrNcpFxnacDIDGdnk5PI2qBzdlFvNdnpRExXbWJ6PNQ7-YOjO0o6wX8kediJrb8HmJbEirDujz
YFMNh68Ks-AAxVo5KF2MM6dvntFvBm0AkNe7MTEPFNC8QQzETN6_MR2hFxRdzyoORhFH4hwG_MQXzDxsn_RydZaUMqr0g6PjsomQkNuIsvDwvZYf6Y75-iiu
a-idWppxui41zsT4iTwox5gzjjDxnaKev0fftvQDN4jGLsndNpouYKfbYmW0IguLY8xOdXrKVsoV4r8vhm5GHsodNd1_0A-DJV2DiQi0UT0_Vbl_nSECs5OP
l8SB3R7Zj3Vbui4FhurQpTYr0ZZQFqKlwHdFscWxLmgiUazx_eLmBdbqlyY1JGZ54TiBUkRWQQzI9nKWML-i0CVQU7hF-6DRKxyTei1c069PgYEsxWlk-Uo3
g74_tA7VLFIRk0naHzlw5yBvb9yz0_m8R0KG-jCDweYjksVEZctBm2wmsmXRflVtCBPwGL2TQ-C-i7s4DrV4vcXRJy-S7rjgs5e1HEkk6aXs5DjpBXwchOsC
02K3oDqLrYAG74lonUFB_SCKG0A0khbQwxTJgJhQrd71VHQfZNvf9jdJrGH8Pe2yMnkrJUoP-MGERE-bpVMvDkFjHuBwU7Wkk2-ChU2BjhccQldRSl-JuK7M
Bx5hWke_xVKHtboV5pO04CUdlIus--9XFa9heswk6ysm3N5hRBjDg-FYuUBObcYRQ-o-mUpvuK13CUAnTxKBnjTxsllbQbNw0NvpDWNYo7NYnSFvQoExRW0G
eFP0ZrolxHd_siYk2iWRLyV5mqMKDwu2l76zk6Vy7mcQ_71LG7_hwhzuk3wsDUzSBK0EkFfwvlhOxbq5QF_ELV1N4yhGjGBbtxWM_FN4Ed2rW7JSjGRSWTHU
ksRWgAj5t8NyqhK2SimruoxmsfYVl_rsn5L1t2csLRGhltUj4VT3ABRjlQi9Y5l6rj8xruoRmgUzCd2TtpFNhuqj3Lnlq3EERtjXw8gxmsjZMTULJtkhkd9i
rtS5yigk7DjrNPbOrtLbKblNbSdhkZ91btVbsBBhakIshYjJLdRbsBBhkgIwlYl7TdprlTxQwBYIkErfRtntkE3QAFZp_0y
}

sprite $image104 [118x82/16z] {
lPPhckiW3aIBXoHKxlslTnBBbs_2T718Ztt-taSPdPG0tv9D4sucINiWk9NQ0YkuZMojenctaBIz87VebJRYbySMQoFSyiL2zPVCdorTt9OHVsHk-rdpHNhh
xvaFKdnGlK5eZ7SdbzxUgzeodlPdemtjlKnen-dNjBTQMy3g5Mqvn_9LmvsZwOzj-PBwfxPy2-K6eIFyqHk5zkNn8tYGRX8QcoDIYwtfpTQ-vfcvf-hQaamp
eQOg8cedHzsQhIt9-ZvHIZULijZRt8sJ9RdM5YqOo2goqjxrjbZvIx-iVDMMsWURqrUxHDEOLK-5fkDlsg5tkMQZtg9cMgQVhEERr5lkdomPIB9u1vhf0nDf
PoSL7pKXLLN92tep0dhROn-qDvH8-5_9HLJAWbvhF6ATTDCdxvfl26pmaqMrfYE-VABN-LEmGphPPhcAe0oh9fJs-6a7-ekon8-NUwot8zRUdnLrwDteDlJE
DsKf-vVpoNpC6TqZCFBCB4TyJQFUyS7EGsympLLCg4ScYghcz-tb8vR-xmjwx4IlO4ftYmFzFTTRryjWhbS-oKpd7OepzzHnp6DkmPIYaazV15tlwrdTNt9N
3fi-UX4u8pEyTfpFv57lmakadlKrGfqTbJRJQnbdbBFXHkOcwATi08HqVwjNq_cBu3ppnnBGKmr58FGZjotgJN8stCZqZ0SzrL4sKxgVwbqNsW_AYXtsM86G
B2XEVzyYotyGgZXmvpygb8u75g5plUj2My8_o2FNdGMDo2mbGlsjtlIDq09qIkEHaPqeh6XihCLVMZJghLXOVqTRNX6FjPIIfEIUadFFTdAcTsMucoMC98sQ
5Y0x6vApmkayQUzykCwj2ytuZHo_7wlcjZMKhKJgYLxxj2q3ervwgYpePzL6VwjteIqZerx50uzKZ_J9c3zPVpEwtbQGzxHOazedpJRaBhHbHeunDsV1RfIE
IdelLy_zJAZWCwh7qgYepYSvam8bwOFUSw497z8lEm4qbhCpmwfCb-JuM8Ysh92EBHpbCLX3PaPkTFUvtX0wRyjPYop4YaAUgR0-vfxx_h6mJjSROZCQCxp0
stW7gYstvRn58HQPp6232korlURJjgoJZGon4BAW24IGNvPasxQ5zRUWrscvaHa9K04QhIz9Fg9ErzywqlNcv2ekGDqlXYTnfqJcGbiMz38dabj5JVrYeE-f
lIqdGjVrEbjrTmeCzfgwq9Oboc4n5bMfG-fIMzRrnhsdgOofyRJ-_vECnztRF658ZRPSGcwXrrcH1g-AwwYXbzRFoZsq9Ln9acYHfFzEBRYM_f9iJlPKN4w_
0szDxNVWpQbzITwRslNUdThrHkgTYEzRukVMrD0Rk_1USll3BlmF
}

