sprite $image326 [591x429/16z] {
xDg7SSGm34L1w8u1_JVidBC51sfcjmd-UM1yYgrdYny1RMRcF4SPd6RUcgSeWMtaex75Vj3okHOxmNdcCxid59n6lcNicL280-_fMnHWD3qtMnHWD9Kc5EB0
-xuU3Q3dr_JO0UzSOKBXel8rzRiBHbDzGY4EFAhSNJ2QYj405vNAXC95fUJnxW9jPbcBTo0Eb2OKua2ThokqBAXFACI1-jq5SQ0U3H07AdSNn86w7eW3_pkX
40TCA7hMrISKua3zxeBHLB-x80xKkRkug2nmTy5eCg5SLDQPK8W39fIBof8J2d6WVdV1HQL-Tq4SS7SH1vRI0t50D63hkI0JIXmmeSI1rRYxY0Cc52sNvUuY
3hYxY0FhcoqG1qmeSU3m4mgZoTr5732XwBaWTnVldBkBYyhXjS1e4WrSL0upeJ2Qt5rSL4meUgx3X79HEVxT1N70X187t5t4WUDFACG1TnTnO8unsfLBzku5
IM4TXyAmBSjIk7V_-vrYdgdAl3WqlqrQPm5TbFkB9UI437kcjslihndkFYEYRbsvf6wtZ9ZkPbsZRVQabR-zXQhXG8IxMVkfcBb7_hfpbneEvDDHRvz9Dv_n
Erge6Wx47DQ4h4NbRRVKS21yzCR6XiVjXWOr78XvbeIRcdcNSvTgciAjhOzvR7FkKkcJeSIJubkeYWEKA5BvRIrKDKqfz4fO-fZVqqBLS23TskwncL_GGjNj
bk7VijhTS-jpbpfH2QJ4yQBuSvSQ3YIoB_6Y-7ENQfhoYpkAFdEdMrTgE32jVNV618O6DHp0Yjp-HKzleIeM-CQqFZRv5gfELFYDQVqMfP-xL3n_SVCmOaKB
LSE1iFiNUcWbQZWmErjzf_yZmymCBFRwQbHyp-MpuveKddyHGCajL6MaZ8ddT8OrtGpeogk5ade67HFFwQpAXm5RTRLGslQkO-8vdL5PHzVaUkvIyGGlm6u2
frUIqmq5TRvrfJ8IErFeO-OHAYV-vcABJvoxr70WnyzGUaRYj8gKPPsxl939V1F-EoMTaqwgK_SGrj1W9739zTFHXSv9Jqv3MwXH9oh2yWWJ79ZJMTJum489
BLGD1txE4i_fd3d0ALIl4vKVlj3wU5e2E25LhyVxvovrelBUhHuS9-3cKQzRLzuRfwIzSpi_m4bA36Y32glXm2dnpiO4SEAtAAzRL-Gvoj3__EQSz9lSBUkH
OMb1iilV5a5EVCsRTVUlKFwd-Z38Iax8VthKyoulr_uXzlSy9nwKPJqo_DApc6aw9fuJ3ohgLrUQXR0x2pqJpua7DN_T8yFw_pkavVr6JlfyQFpkNrtn50kz
_iTvJdgY4xzaxB_mXvgSxqnvJjTOUp4zbRhwstxTSW0_4Uqw9-PbLVgoth-5ykE3caOUtySfBuYqnE_xgTQHmcOiNA3xSye8zs7MBc4z7VvBVhyXkq2Lu0GW
8Ztb-1MllZ1WQm8u2OXWJqVO_LzzCOGlT7jn4X01dcxHGetKDEbMUKxwrxFrdj9l_LxC0HGwbHE02FEqVcX0d2cvKEWmJYWYOPwf9lfDNoO-XGChZbCoY7XF
nxpbUp53sFemJdp8GORVxsNYgMegJkzlrsbtUvburplFulJ-9HRzLYyJ7szgAaujxhSY5eUK-VQo5QUUm2sXy8cAbdnVKt5g1jmIoWu7n9YigJZfNIj_xi8V
eEcQYbFBdHU6ElA87z9Kd0nugcRxRTQuUTEPKvMxJLkeaSn_TXo_aPFPw5YvMzz2sNiLA9Mj_FwSkfdxZB_n27gDqhzaEA0FC7l-0av_GnINxGBlBjDM3GUW
pIcEst8o6-uH-GEVjmFFaGB30JKcT9a09woUHUIswpGN3GVqnA87tNnrKnJ2BWvsu_pGOA8FKYV02QbdQkQIRJoD6mw0cvCV12U-dkr_vKLdcYPoYVe1S4Bg
cPwywwNN9xr2WNFIwzbn2VsPz_W1Jrx_4CRXkt7gGbCafWDTBNtkCfBVlXFW9DOpCW6q1kovYyN1ppK6K3Y4UiR7WDw0F7UPIpRlNC_9JlLiNGAu_hWMoXFu
gi8iZfFz8hyzVOgp0SC1DVxgrbsS0gWYoBbBZrLVLEmeJgSrKpPqleNYbpDVlzAAqzIgtLxdBYDNhann0gv1xjp5OcLREOhJEKDODNpvz1CLFSfrLfocCCdS
Q6ZWkVXBoh4r9pxwh6vz2sMv-ZApuYJr205ib5qO3gnk0k8Z6L_BQMxqWNsV9RIsO_RdbCgklhw56hcy1oXE-YIp7qp2rE40Vv4L9trRvwflnuS3rqHn-cp3
4bpvTNZjYXFVYyV19GVRD5tZnKbCxFY9eql3WUAqFdj-uYaVQHIdudHDEbpdpXd5IKrN1q_ikOlbmSMAaneJE469VccQYbDnqkENzIfEnKbFZalJL9oAavwm
n_53AKx5wN4y7ZGelocdulJ7dqzEZrjnghdJM8NfpoUdPufJZJ7Vo-FFPvwSO52pE8b9uHDZMzE94m2gxYZ0Lcwkm7JYn7hA1gJkTqBht8aJ3geuVVQqCtbC
PqxdrE19B1qRBHnSvwwSpjdc8lCz7eoAR_jYPpYcCoVUaoyTdpZBYU_41r_dpfoksMDPUd6ITlL9OJfjJITEF2Zf7rcSkl21iJftvdJD3YtbA4xAW8MlSrTE
rwnlddfn4ZwuePYkd7XG8VmdYrCNvcHSdRjokcRnoepYzFerc00caTDZySCiMPnUNRCEr3cHqpDBhpGlJgysuWuC1sHEpooiTdq3JiD35yL_xCJht3dpyNza
tUBCJUxUwoQfuZUdZc7IEJtkj3hUteWDdv4RRqwJRvgkd7XGjgmLyFP-pDm5LTpx__YjwSo91nN2-W2Su1B8lvnKnoHm0a5rOO40Jde9t6DpmkkSpkcnv064
W3dfCRiqLd1hO1WcdTCv2xQdleQJdcxk4MikFR3EwPpEuTV8LtFI6wiPQAap59FEwHnyUsf1SDgu19gmK4YTqpcTGt-vwmbmGafWVlG36tcYedEw1dwYPQp-
BKLojg0_vPfydRjoqi8-3ZotV2mB6QzdHo-wSvq3EJtOZI9sv8ICrutVdCwOT4uygEp2Mf6S-1AeNt4Jg7C29nBKR4expdD2PmlQ0Xc0IU34WZBT4y-9dotC
Hc_Vvph7StfmvMx0dDQdl_1H7HWE29neKD5eJzPk60FgdC291-K_uAau9L3d54uyA7lRKt6Q02Q94-yfsvkUYjC0wfp4IG_IFhMUnUaI0p39d7XGynrFnQad
KETuJW_cL3PWJZEcZvqD1Z8Sq3dne0piEqtyR_rLLR-X9W6Jm8a4bRsz4ASvdHEnbwe9Oj8vwG4yMSAShibmtq6L0qqJp8dtr68ffxEgwMPjMGQvDUcSU52X
NfKyfsjoKRi-C4myftC-xwddSaxNmAe6MUTuJkTyt5FplJZnxVe0CEcSrdlgxQLOafmaLMuTqAJKEPmJ3oexi45ndCvV0WtG967YEUdvkASUMt42lmGwLUTq
Jkj1vMWlPkGEdF1sVG8dAXjoUdp-gKhFzPpeTZs0EWTm0a3DzchwNCz9LpNQo-a1r3c04m8gbFNzLawfQ4e04y09yfH23R1WEAt7r8PSvmXEJ3w_oXO0f_MO
sWGm0PnGKBC9wPFcn6Fg0TGvW1CCAhe6Ah-4Kuocn18O3W2SS4yvcfIHNy1f6Zbj4Z01d6XGiscnkJUdzDwaz00mKPnuK6bDI_VSbjEq9iQ1fedan8FofiRc
ZfnozDROhOddjFS69MVClJZbx4sE0vXuJZoesVJq4RjmocbDJm-apl6SU50vsbkYvafEPqjw7CF4S-8tgB3sLcpcGaxXlRsLaK2TupcjhtXwkiSAJZb7R--b
1us9vyHNF6zlnpn8JkTjIS_awnpFQNqBfPCYEELqQpyGJ-n4XUUqleNYedCA5meSqpJnd0gKpYbFajwF9L3dK4u5wie9-W4C2mrJST91hUSKdtc6piGJbU8a
t0fbYpd54v6RzVQP30eJpwb0cRiF-ti4GK83hjMvuaJVNBT_NBtTiZXT0jo4jdNwJFbso-9q3N0dshwna1-VAqu2g3lNlEufOofE0gWxRr4szTySA4w2fnjt
KTsJmyHpMX_bgJKc_919htF5IGTrpF6DbYRmwWioCn_xWk95yPQ0EiVb3slZsDMJ9AetDlejx00cEBCzuxjkK59YUr7T0tZr1PxZ7-lUOrDGm9CZT6mcy8ed
Fe_pablk2afDkEr7wRGjtR3EdJFszGIG0YdTiSv5kyQt1GMGeYZTiccoTid-BPIUdCFMVOMxKBhPS62q_nGxTWUb9sXJDYwRqhsRfljNlAifuXsPtVoq9zsv
pkN_NCnv7r3yQ-Ti29204nLWEF2VqlD6eA37KEpgwFvrpjibG0k5UT9PJVSXF5TWPkup14Rt6mxSk8NIan4H_iomVvVXpqH4v05awnELbnAt1SNdZdSEN58j
L67ICiNNWvOdFliF1zebrK81kULmuB2cfqU14bB3WLzoxiAdcgRxtxfIJTDVshi32m22A0QY723z5tnD3Bxrfea_agpDmW4ArICSe50zxfpU9KOuuEBr20TC
LmAUd5kcw5r8Ku_UHJX0eGxmn5lC7jCLTwxder3cbXqKYZHHg1xXWDxb2gJ9TCLRp13J5OrA3uKojzIxtBjpfCbqHJZGu-APM_QOhWW7UYYKkQNUfKSuGA58
Kn0EzEXTI9FfYd3W7XJAt992kNFde53cbgOhfEdmdJDTCRVKkv2c--XTp2rDLtnz4I0qCBUyXIV3mW4AfL4vYzx5t9922GVkedSnjpHTCRSyYzv5E42XlCLC
eL32WHAzYt0WnSKJ3gIOhWW7KlGkme4IlOkvPGg58aqffYl2WHGAvIrc2OLovr8ebBbbYjw5DEbTKeG39QOhf2c5GdcBcKAXlCKieL3cbYakdhbbYkcAS215
xs9kMQ9t4GwKKAYPMtQOhipSiiEJuVdweeD2ZJHrKAW91phqBXCETEXTvivrcAxCtBA3GaquqA5tcRbb1uKQQUfmyMPksQ5tcRbb1uMQkMM7tcN2WGuADOrA
Xzvbme4EqvK91peerCmjEoZKD2eT56h2WGwzoqXJXuituK279yCpj-pGkyoTww1G4mvqKAW91pfCL-OjPWU56cdgqBjCED11eMPksQ5tcJlNOReoSyiEJuP7
cZeerCmjEoZKI5E7tcNUOdQuUCA14DCLSyiGlGjf2j6x20T2A9IvPOZfYZiNGg7CBKCebBbb28KAvvRGkuJI1BrB60x0T2KC1q2XmZi7eK4ujmI52iC1k7ZX
t1AcAw4qWKA5SqleNSAv9IXKEBU4wKeO3i2JuR1H0OKAmm5Gg30SWEbAEBU4tYLiL62w4eO3qBk4qWIzInWEW4A5Sqi83S8x1xrB60w0GeNX0FGkuLjCKAXG
cg1t2SC1cAw4SqleNS8x1meLpYr1eS9m07gNS6u95o-K9fYkX6yneNS9mm5Gg71k2GeLIXDCLy961HGgd5l2T2MySw1GoTpoVNu
}

sprite $image326 [296x215/16z] {
xDk7hICn40FGoPp-6xwS5_Ad4swrc5S28H6KWvnE8EGZmz7TCBbbQFLtfR8oDFktb1lcolq6bwDXrVyganlcolsMAdyOqIiX2rDCpTJK51DPKrDCHrDJWVxG
r9IXMV1vf73APWjmKcSBK12p1JYmsGASqYacJimMk6SZp1QOZP3zAgcp1JWnMu03dot0APijm4cTOkB4R04ER8g9KpfNZfEp1JZmkN8Ss6m1JkhLYmcegioC
dpApgd3fZS0N4oept5HbHSqyaayCVgrYGgMR2ayjaaghx29N3XMkyXZrA5obfWozWdIJPraazgyfhVKvCdaLYzgxfc9vaEJ5r1D4JMrKJ4YJzxWLLUfUMo1T
tich5n3xR064ohjfOAEdJFpFah3Qv1CNmyiAGhzvsRADSs-1nskq-Yi0FryrT58u-KO88YLU7OTN1fMMvfatWkEHbCpfd7xFL7qqgTGT_srXKUXM8YTYqfED
7kVO0dmTs8yQ0PlJSTdh8uzm-4R5P8d-YSxfg5nkMTRKQOe9Jkp1HtFYdqA6yzIK5hVgZkyBFgV73rL-9kzEjvvLOJ0CDu4GgJt_qzs3Qxb7d_MLM-MTyhk3
lMnIa62dJcK63wGEVFU0qz2ag7oAgKp9eIFO4WuvyMkNbXy-bV4ctbwZSYU-nD8axWUk4RH1fIKlSkfQgiwut3dsvZ7SgfAFaqxx_CyDBBIcVyXAIkXg2fo0
plZxXys_p1C3NoRabDbQr5A43e9Qwkp5ov2ZlPDE0pe4AilKnSicYmDpsdJaSheES1ZDvorU9kkepy_HsXysgr_0PFRCToA7KkSqCXN4DDF94lIuNDrL4O29
EV4eeCVbuaQc14pKYKU0UUArZKm57TPv9zrKTlY14-mylhB3iecl-KmdCo-rHiiDe-D3IhzlvwKVFMi1JaYdR3hvpkzNkwzTtnhhRcyNEkb-pRpbvDLxcffT
FOyxwTIA43hYbTdPAsGi0AgJBS19wlX1Qh5lHS5R-ixljZYo3-0aKmk4l0IObxVhM_1FQijffxndIrxWv_F2fAjudU34NjlvhY9Tc73QvHmdVcYuJF6TbmPE
sYIdfXCFbYd-KdcOTlbcB8qvyKfUQ9dZAQS7cVPsFBWJ6zdvDPiVlH5j7j297voX1BRJEo_BPtQAoruumC_vrt5gUkh2aw-WG_FFx9J22KKwA4nVroaM767W
sL_OYKTzzf_Yr1OUpsVl4Ahy7AU-lfwzGwdwrNxlaYezrtNTd91KVB5nveEctFhwXrE_v9ILU3lsJmA6pQmeE4svTTsTa5GUEVMttp-f4vy7SwNDYKgvMCe7
pC09N5S1ARV5xYIaI0re4vpeTJfGcAHJFtdIV88JIpl7ARSxOIdJPuqxFMg0fHP-vLwF1VuPhtuGKzR9yXTBT-8kFVm4ufJRd9OEfC32AriFjcqfBoyOF3bF
kVtxnA6AFY3kfBdotEdZIjgfTtn4zRIJpaR1nVemz5X0E76fmazTdchf4SKBDD68mZJWrE5Ale5H1OWz6rdhcauvxQI3JORBUITSlDBmtBe_ToNfnALSG56d
izdeecI2b1DEAaYPgS3fld2GSiA9GpK0DTafWP9oub8LzBPFTGem5j1ENCe557CoSOyU71KK9kpK-p2K9NFQTsrUn5LWocad3YK-Js2dFSvpELNIJbmgJPzB
xlHFhWQvdASST-fz5CeQTZhcYkfcW4ah8ISkvMYtB9hrPBxBLMZAdNVgmyl35JlfUA_Mru4Bbi09IbL-0mr-VRml1OoRHCe19o8L3or5dVYkEMiWvO0JW4f_
QAaaJhmRtXCfQISOuxqPfG4dsWbVOSff9npZM_qy4ZaDtpVO4ojf9nwWtQT4ZZcH-tHNa79tEdMqWSqZppYrwc2thhXW2PnOi0riLYA9KqOni5iNf1npuicd
mxGJ_vSE2v1om0d5jRS3iEDP2hZK19IW4uVYKfPRjE6R6rbDSC5oefEMCWJ5dXLWn3JRIKzbVDAA2foap7VgUa0u_Nyaz5Y0EotFkwMMLYR_BubEEUxKytc_
L4QP-3ytEkKuqwizoYAWI80X8WqhBPT9Idshiz6la_h5bCCkClBQmE8bP7hM_MtRXEGJ_mQ1Z19qLL2bjVrhOMAMr9Q346lhRbtsc9Do_rqXgNr2cSB_FBar
xIJjiEHC_U07Q4AP4eicnSti06U_QPWGkhqmhI6kt4n8FYsMsVuHcQpRlbzOc4ml3CvDlj-xjxiR064O1iBFiTX_NYRW7qkVcX60divn-M_wO3h0bFwW-Yvm
C7r7w3-bhGGc05FYaJkuLW9WIdfASnX60KTWmRGIfb9p0H1JlWiSrnVnCJK_7ha3C6cOybtW65F0uODSm7U4_iBora1HndU1OqS0dbHrONaqW2EmBW1X2dA1
uv3YEOBl0dIKwIyi3rp0mXG79XPJb0l8cB9TmCTK_yZrBXkrocDuOMb5cG7AozxXAs0AS07T4HGNy1q1SG4VKweBU1iNPM7fOqfn0HzJ29ZyADEwo5GO8CeO
Bk1ZQhAroyl-zCjZOs7fOog42_YOIji504T8uJa1Ba16cH0XnOyo8Lp0TuGGvQKVPKAuW8-f40jBtn5IkCYq8gP2k82FgH0ku4UP4EMbZwbW8KKjZ_CSJ0KN
y1qXa0l8vN68aE8xGWWNy1qXX0luc38MbhuZ62xWOyfm0HzJHddfHnd31NnC6UMb7sMCXQLV7Xiku6DgEHSe_NbiX1I_F3P2YXzb31VmosEZlFIZZE42VfGn
NC37b55U-b76S04VKuOB-9Wooai_oXWku6FAS05_usAKbxuZ6275nnJY0huZW2wm0m
}

