sprite $image11 [236x225/16z] {
vC-d4S0m000nREJzjmtKNLXwUMsWURK1CBzhx1POhZIMWyYJnfF4aqQKH9H4b4AKH9J4bCAKGfJ2bCAKmfHGTQ7cJlTRPQ4eZ4T4OEsrxlzstw6JQHhYTikl
rkVhcVotWCeX1J1GMdEWTZ4jtiktG1LxQpNGA2mEMGtUndn91qYZ5m7Pxrg1kFGQLiYEOd4rQroBgreHa5xB6iVYSjQmTkz5pCypyIGh0bIlrVIqawn-REWY
yXXhgmq_QoamLS9KbDjM2uP4_QZ5beKe5VMssLGn87kifUWIwARwhMkfmLE5lpRxvci0Yv1rBJkawNOhWRKgO8M36hTkC-Rt4L3Xg4o1TTY9XT-QOjDsMMzJ
pJC0ZbenmbhK7LvzHfrsZFSyvl5iW-gpokR-j7KjCrFn38379imzgn-BVLOQszIzeEBwFgNQ7G2zgjIp-h7OQmMCvTOhLTSoa_VTPxBKjVgn25W1uujfYxKs
-P-tyiPZD_ElMuMtYFvoMNmJiFhkCrFJ_nawLZSMKIkCpVMjPL-RckEEMZwaw5ZTMCIjBwVjX3MoFm-dN6lDywrRvlhQT8vrPMG75iHq2vNm9ZLqhNuiujQL
uS2QIeHQluPlr8gHLfYgPvqrvhtIPPKEi6A05R3EweFlqUOzqdcTg4Ui66LT6Udfie9lTPwtNjzdHbdXgTRlB0bFUZf2rqlfBDoE-ynXAtPOONe8ptesG9lm
c35xfSHZDI_bFefUQtGd24zhpwxPy2DoyOnUkZRW22SM0_DROLJBFUXYxmR3qupVitEiJyOmnCuLIoYFVo3bHlMbyGPI-xlMUhDskH9GtgimoG6DDTQQE--S
H3-ZrfpGywsT6ub9XjUPaQH8qWnho_8thJNr7_4GgawTNSceTVIQz5YIP0ZKviwkvDdbsmig3_wD6N-eChtS2pl-DnRyaLfw_U9f0wP-glWBvOtNiK5J__nf
YzALJf0aZllQPPoROzjlN_N5tuXpg-dLyGaEdFgB9EAi-ZlwCxhI-DG_qzhVOsZHuUlOYJbTcmTCL5JFr3y_8ZtipmzOq3j_u-aPs_rznX3yhhgd_ldJjiO7
MsUkZfseXa6H1wuh_yf4DGoByS4s_SPzneXncQtph-GvlQrOAQMyrFspjGtVZ35XU3Md9_V8kQ1Rxb0D8wD6G-TRjxduhHg_-aes_gsztxHuhHXEXKGF8Nsl
EAIzYkz18Wc3Cqc1XvhSbyRE6Uyue5kY7r2a98lyxwjvNyTyUmop_-KyHJ-WA4cCM1avATbdjCv9FuUrqTn3M3fkBKvYdx6uJvgdu8U078zr3ckTRe5ITUsb
vr5MlSL3rZRVWiqkx6qPOZMzPm6hOwBc9acias_QPiV27RVg8uQjfU-e-ghvfcrrBDnHg-apYrbhsZhNGGDWPF5zpiLnqZnerLSCMUUjavBcEdU9DMiRsyDH
gsdDzbg5PMl7trm75XVHV0SMfngtwhwzLcnDL0CS1nPdFlvUi_nYsWQjr7tSPStPVr9opRWu1W3uUjhE-wscxzaUwzQ9V7IYpOxjfDSV4CdxhNeiO0tipw-C
t1bFtWEBVYlr60FMmBQVgNZsVOrvbDNqCmjO8_lpPjan042aCLPf5xPwJ-HZu2k7gOsmKayBM6FxyqRHzTkMmrQgKz2wEAInoFcOrTIB8Mik_xVaX-eOBQO3
LbC_zgo1yg2VL8LvmyeGLU8uwy9V-WafZ54b3hCMyLohQIkUPrs6MasEJhFMaLQJAyFrhIPdTdahvSukRjMUYFjgIlFkscbMqyui-CVNph8oVgLngy7Hy2yf
1_mTWKwmclfnm3TcO1O9QrJKAXgkbEbbZkVZgsJSecWhmpNYDaIRqQuzV5ShjHqlB5q3JBgwra-GhgqrofN1G3cZNLWg0GQJBgirkIECWFParvHAzcQbTiKh
3TurW5fNfsiCvVWhwfkLqgMuHktkwwoq8j4k0vK8c4G0bAx1DIhMtLbfXQET1_LdTsUbJKVwbtlxIcuWXc40-aqWCtl_qwOtf6f1oKkHN-xM6yWT9kevTQGh
VPSS4bMT4cT8iANoHTwfQL8-wUO3HY7cjp13i9UB0KvT33xp8ByBJ2RZb94B5g6FqT2ZIzGayJhoxIW5k8WQbEE2RJJVQ27uRbILiIiMF-nODCCgwyUieoML
ltpRq92Atyu8zg5AVDsmuvveWbKg_lw24BseNR2-10smGes1vFTzqAfYy69eGUsDPGXr41lSEjGuTsbi76eCNc4phH-JOeFxIBsCOhzeQQyPcsc9n5vaxAGL
QQHRkJj8_LnGLpj_cGmT59RcbuZQMY9qEFNMm3hIc9q48og6IyJf50wdgWOMYLIthsrLRIKkuNMxZiDl1u0Le2hrhNeVrtE9E2bLwv5iVe2yaHDXITLgQTLx
GQ0Y7QCUkVhmSY_LwRzrE0IRBZ5XCfY0N_7ohQfTNjcXCDtDgrJ16bnFx2irKj_gS_Eb9KeLQX9KgOhrkVuVFiqUfcyjNQTLg4qLR6qk19gr5lQAqwCgDkz5
jJoLgjYybxY0QLjB90mASn9LiLVtfG5Hhg7wsFpx100W-L3-710010C040m0rx-j463RNuFRt-AfxFXqhcIoPB9aicIoPB9aicIoPBAeRCbaoMIfP26o9PD5
P8jA5f4j8bc8R17PGcCBZIqqjj3OGcCBYIrGw8925nIsGA3hHvae48X--JMQmFF5i0a4be-KpMwCuGK
}

