sprite $image199 [36x288/16z] {
xTh9akOW2C1niwW8-FwlEy7kSaeWxNUSXVybswyySID9EWlW4vGhlNG1pjhjae9BrI4PSOSED5tQtDQK3qpL9dzYo1WmXZLXn_1o4h5hXfh2DQg_mDpMrAGZ
OovZG1DAfagAe6CGQI6-UTHWz03qZUg_Cs72X0aJ9aoOC672X0aJ9aoOC672X0aJ9amOyCnn5sWDodMyxB_kewoBhjkQrfQdm-ojRCqQsvr98JAcF6PHP4qL
CncD7ADZXGYiCOirg8vXcaeUeJCR8yrxCK-iZ4gCgBqHnHkpA6jQrygQJ7rHx1fYfNJucAqIir5TpEWLzMdyeqGCevHA6QkiaRR6FugC8TOAYcDMnT3Pc1Lz
pGRlvr0froZbcgdupM3NofhCNQdj7B9JkucswYI5hEgfqaRrdXBGZwgBIOLULHybGVYD4BjkcjRQzmyEDxsRqJaU365ZKjC67CEyDteEVJCLIwvH3ND-aPf-
CEae0FLEhqRrdvemOSA4gTPKRR8r1ws4ZcIxQ25NyZhRRm67IqILXaG8-PIdNm
}

sprite $image199 [18x144/16z] {
xSv7OiGm34DHkfC4EFS_Rgpcbfvjz5trLf1XDNTR1saD1j-3ZKtM18cs9kerFGHLh8an4-Y717Fn4x4cIvEroGoMbaFSiUUuIEaVIfSkNRfq6UPv6aGsLD7L
0VWgcgHOUQzDu3LJejR46h0GFDY4p6z_HJNMdB57NaGZYfq2y6xAIiqYIR5MaQifSAVhmcIanoSByUN2ZNZOw03ZTLf8eXsJbKGsTni6lOdP8EAHUq54gx0C
SP7LNIL9QHUPvk4cfRz85v04xP2PESnoD2a87UKD
}

