sprite $image183 [233x170/16z] {
tPY9TkFA2aKbQWJApl__xKivKdXQ2pNE5L5NrxvZvkpcC5WVjuEVqCVqu4QTMvDHc5ZpYKTcJwr0CseIQaodMV6C2SivloeQJ5zDOVfo2hENKwYpLrE8iwmK
czdBAT04cdEguWKcQCxPLF4oDBkcCC61C8SgUZAxfa2pfrPupbvEONPDWMPFhL16qOpeIHurlq_Vwi6oZgcAdjImT49LFZIH9gPb9u-rQWgX8tbTX80ASvGp
B0UWZh9gq9aQboC55NZqrzOst70zckO1haBqXzg3uz4qeSe_gYdPu4ShRvdIltZlfGKAIb5nrTDx_rNuHF-L4hzD-K5WJwJEFvNQiaj1bVZoqRJY2JIwfX15
PoqINpwa5n1lLsN_Uq_8PwOHptcEtfoIMo69ALfjAlm3cvCudzNqSVZ8YdYVAlh3vxk4Mr1gVKEh5dH5jYQTJ5YcOqaDdaEkb11ETmd8dq4-bjg0XjEiKTab
sa0wl1_GPh1xR_tpX5sbsEauU6tAU8VGqJJh9ILbbngCy-1Bdx2hEdSu6DdrKqLVygA7j1Krf7JuV7mJklyGgYd02Y4L_0RKD1AlUaWrVvkRXr0LAIZxBkb6
WXLIqcy6cniriMWN3psgVl5bjKb9ARHpVWcliYxQnKDD_zqF_bLDUa1qLutYwLDGAHuhlxkhgF2yPTRMioUqe5Qqk8lQHKKNA1qylpEYzoYUB18mUjJazvvA
w-TERBjeq8sY_afbDQQkJVtr2w4zw5igFPfMEM3LA92Q_uB_ZTy-twar-AuHatRjLf8MjGDT4PrKA_gIj1keFHfjhh4XQe4c2RJoxklvHL_qZK7SskFnu18M
O5OB6en0NomgkYDLajqWhesv7OQh5UWYeXTK6Tqfoi4WhbsLr8I6qq1VXDmVV4dib9qXhgG_nYOzqD6X5aGek4yYUmqcM8JSI2qeaeCe-vlMHR3M0pNAksiG
pwm4-XBScDrLfHhs2VTgM7wvWaoeUiW-iiCZv0TtwBScaNtQK5TzDCg1Ju8R6rrDxUCJTZS5JHHGHNREwIHUcQ-czY6YZgffKSc8XglUe4jjbrChefwggoww
eW59z9s2AveT5iX3DIud97oNca4Yt_XgSugeGFwJIAZlL-5xvwpShZQdYBggmhbem2Fc78PbfKOEgHLHDzKiNkQACUTme-xfa5fTbCbf4jahnguhEQHMHFrK
u_97ya-hmWwf5L4DSfn4meh-w9g6wDLL4nQ3YExeaRT51NATHFgAyKSq5L4lrTKM3VUdLaIzL9FuEAmOXvMYYbvlrRgymtfpQWKs89T99AIxKokYFgfbUO-r
tgmfeZwgiBn9lBKv1VOnJSlRb7kRKqGzLElwlYZScreHzL0Dom_8pgbr5cMYIvD8M5rJwoSgqAL992J7rFg8Og9tLFFoGwgNffSeXP3PLbr_AXhycjCfkX4W
cwqQbnzJ7PhJLJG39BDLA_4F8OVK-eeMW63-elpuAOqSKkigYW10tQpGkIhz1nmU8RYACW3WgxAnEgNF9RN-eX6WC7E2_by7LITDVz7y6hiKG9zAplWtf_1X
JgFurQeGrQlmHhXTyVp4c4Q1kcx_RrV3lrLKkgXfcFRG4YVeTCSAobKuUcfRbxHK8q3b09torREXig8wU6fDrMvM402s6obsuLILLXqxjRPf0KYvvpP0tCOl
LOY-hUglAPuAfzCe0WIA4AY_rNq3m5tv9NRJ59xwDEeaJW3OwmjvNpgAwhZDQHSrGgTqkVfwetxPumscr1ncxRkg6JhOKvkxO23zvLk7XasjhReT2ym4474_
a70JBfb-IvLyKsktAi9svmO8vVksJm3boxTuhHh_bM9pA5FOx190_r_SzIDJ0ENOf_4rzVnI3e1xXY6GN4pnzGvaLl8xU6frLSpyIGMfNzVUw9uXUrRr9ar1
tQZbyDRNuK00mU4gz4cjW-bBZKJqsvlWa-YGNuULug6QkixHCyjWXgfirT5JgwyQJBiPKmGGRHJf8pH-QlMYrb2bk3A2KQmLKszDVqzHrS_2i8yc56j5TUpc
jAz2I1KWxgBIf5cv2iThJbjLaaeKDZdiR-vD6fIhSCpcjA_2ihs8oNBYm___l_80OjJcjA_2xL00tEHg-DgnMHzCTDEzvw-w3z-yYwRj9Rc8AghEvNpwE-hF
McgFy2PQNj8LpbSDEMkofvfz5PPD55zwIKGLLVUdqhUfbbxIBz4-RgcRXzX5TUYUbUAVNufTiOjYBsRjoKtf9MgfKXktdFfL63VHtgGzkLL4DSZf4BfTbGf-
YH90wCbb4TMXWLDhdqh87A2J3T6EqqgvNnKZu3vnyGtHOSkfqrWekEtGo0wYhfh-MvMwQ74GTTRqLzrkVGTHrqF8VwjYXCGEelxbz5yrrLrKD0TH5Vn5FqRX
wI_gx-c_Qchm56qVWy42PJ_HSGHrLGTHAUUegZPEvHnVrKbpV5CdpV5LdPfpV5MdSevlEecchJgDfbo5EdPpJb9Kevppg1gQywWQdlEe6fhpgEgQ4vggitP6
rTaqXVOdqO-fE1LzVim62qfgvrITCBLwgqwkAKKLpSbLnNDorR-X-Jy
}

