sprite $image114 [239x174/16z] {
vDi9SkiW3CPn1099P7dtl-thDbFdIyOnhOWn_P-Wlv70pVPlbypitymXrluCk9hPdm7RJNLsBJOx5gkpOx4wknQxpex5fiTYFBaMcnwBwV6jLuEcdd2rjkhi
UunDZyLEinzQRFf3YysEnIRGJdg4pQa9h7E1JmPDlT7ctmIZdG6i1iqCvchzgZpkatR-0HiqDRXMUqNLPjzZRAezpe4YPx6r9ffi2fzHog8ZlhjZheMRYCjO
0pRVDDnbZvlYXf9mrp0RVQtcdQO0HRCnmDOdLSaBTB6L9ddIPjZblGTiFLCAmDqPR3tZi8ZiQVN8Urm8RggTlTOpeN0RswRuQ5eyj9dXObxlU5Y9trWI-wIh
RQqU2biYh31Sp0xUSRICrvCft5GEu46mETvWPV7VCrjResErfB0ibfj_h8erD_2JDiDpXmHUvukrD-He9KUmXhZ0mSNSrb1ObS8nOCGmIIcSo7xM65XLpOd2
WwYOR_eZh7WDDAT82oXOrTohBngjlYKY9MTcJYb6K48fWtKNC6APdXQQeoI_tnili2sBmJjMSuY2UjnPrQmNbo8NSNm9vV2HWs7HnHdXim4FBNhRmNPVt7sU
At-KschN1cqBbpvARt7EHTvJVSNR0MBhRJkqc6AsSnh0stf7sy62-RQ1gnqct6UrPpcETlnzHZ3RMZfiqk2rhQEDOVnqizUWGtA3s3QmpS4bsrITXAksgLEj
4t1fcxQUJwVJCo_7KMlJrjFbSZe1-419qoQ_OJ-v1mMNbjdMysN1FTN3WGMqpx1Bxbjrgat6GmlS5N2YJQNtybiYOjqhsxMdymMuiD4U3o8YYYanvo9g_cc4
JLxRO-02s86BHIwYlcm2xGfsmSMg9nSZBgvlL-c6XmzoiUhBnIYcekPHqcs75hdh6vr2eFj-FMQrlbN48XS7t9wybNDECOODvHvYt6Fa-e6nhy_7KgGEdnGr
x35o_S6OIkP43yLPUkunSljwiVB8J6AOvkYFHIvMkttZ1YAsHP_BxxV7oEqFnYGZcHM_UUEAHMv_C2Q97eFX6w0EUmnS1w_7potIyjz_zi4YTqymVl-JylTh
k-IpnyZT7Qm9lq_sIVSTBNBNiwxb9TYCGlFL3DWLxju3njyXK4cDTrM5FNRWTWVp0jnsLm7MXziV38_Yw79eaJiGM6DOH1vOv0xbjGnSXqEBt647x39Qv8u5
5lxcYWFMWTlf8uVCy3v0SjbZv0uou18myXWjSaS1QxZB2OlSCJRw_ftubSzy7BWxW-FoQwFgU6YHEyP6StWh5TU73_Q_E_kuZY26WI1wam6fgVoprKtUBXja
0vN1VzjODmmRyCE7fqXwx1F069f5vnTZ6Ii0RzDAi62nwFmToy0H1NQS1lR70h48hh5ZuGcRO_MBzjwn7fpme7QX2RdU4Tuxrel3SSV-tbrOu3eE7ieTkvzm
oB2UazOVhRzNlsD_S2YnlYUin_g3nn9seaZWDJXQDt08iVxW8SJQdR1-nrxW2EyTwy46M8D5otx1MozQZ_LVT3XYzN_Gwe_MVz53f_K7XozM_--Ez6ZzN-1g
MY3ES3dM2Iu7syxbS7kvd6yR5uzY3_V2fdmkLYLp9svbSZ5iPd5nBOEBSNBkn3ij5_iUTDoWH1ekPL9mgTGgbsBTht0fsErSQdORbxhzdqlfufzSglSVBXtw
AvSk_OLBetxdqgkVkVJhUouj-uvBr-ONN3htaKlphhVSIVzUkOZoF-53s6S
}

