sprite $image270 [188x136/16z] {
rTg9dgCu3mHmMRuaotx_n_sEq9D5BAusayc4hhtF5EAFO_DhUcUAHlgPITfQaq0_BwnjIwKVbb3RCvhf9wKq5uq_2xgFX1y4VOkqP-hFWYvCKG7x6qFVkcO5
x6yANPcsXEBOtnzwA_j_K6_EFjJcXkvoR_QbkQ6xt9jzKZ3qMxDd1KE_CNiF7OFmxEy6lLMduTxiauAXtvezAnZwhTc7YZQwjsPV6XhwdTadHKE_CtjMCFIL
H6Pnx3y4lUhLp-Pok7MQFm9Tc4AHUEdI8sB_VkX-ODoKQJ6b0lOVMT5BN_lirEBKN_sBq8Nt_qnwMRXqeMEYl96zXpx_e6Wz4xvqYu3X6zcdxpS0fLi2bzu5
V5UzaJthb8k3CzfaSj4ihdrNrVT1nowZ3UMpIn-ol4NJ_AcjI-b30ldKSJ9qzD36zq0N9foWOxZBott8sYVzOVQiKou8JY-xlx3u6nlC-Zfqm0N3iVm57GmT
FhIQw9NaXhbWE9Qe3ZnqmWyjlm0TSy59DluV-PsLuLNsGLvz_I_3HhmyiDx0wvwrr7PCvOlpKwOaryfp6yKziO3z8lIcgRJUooKoQHl-bVjLkWQttW3s6BgN
7gfrMvq1Qtt-ARZjODkG5NXTXjvA-6eXVIWlSd4tCIvzx2YJjNwPVGNCewx0IPOFjHRWv8tBjBscwz0ZkSJs7HpMaw8H3uwuRVzNs9ulGZ-RAeHJ6a_-Fe1J
dbnWUmcNeH-J9t30V26SP0f8XQoOFOP-J2ZdS8BZidXXGJ52trxJ6dIGK8SoPB4AfxXxkDAU0VIrfvgbbnKk-CxmX0jiBm51pu5yyDhWDUD4ApkcW0jgN-RG
NGlOGnbomN2I5G91xJMTGh-qUqfM01S8XtN21Jbrgpq3w4ifbkHoYMYvzFJYIQXAqulGVQBQwErYZQ3AeTPmyNgxdt8NCzrL_utZh6R1AofDbaNMGfVEa6DN
NgrtCJDJW1qbzT5B8CesXgm_uCzTGsff-NB7wBQRUkzVtUqVE5tvoYYKdt_QmHIdhulpqiTnEmozzsTtD_fUbuTkQJVDfJS2fRT3sLhekvH_STbrz-sjbwMX
ztoezIsSUFQ_3eBXH3lXuhfxE9Q-7xgxFIjmWemMJabK1l-HRwwzdtJtS9JnqCNzynKufVSy7KMPpkW8VTBTmv4m7tfp1LVWH1kAGEKqUKRTejv1TmUdbydG
BQDRqaVF9tU-PyB9V3A84-Y-UsvkzFeSlMSFDr0UJkDZYOLj0-V3_sS2tNUFCpYk13WPGJZHXcLQITpDIiOmjowUTo_Kfd2ytgIyjjzxm7boaK2BYVnyHcVG
VNSXCQldxQttCbc9KLBhspqh_KGUIYGYLjVSS_7TbOefrIaSorkVJEi9nVgGP9EXWuHOUlTSGFVsU02poAHz7orIo1Sxi5W7ssFqvMkU2-fkn1Rf8MS6PmZJ
vHGjodGjhCCEN71t9YEswhiVuKIwbb0oKQWbN3eFdAmkk7kaIbLPpSncS5gxDiCiuVA1kanM5zGz4vDzcKbfjbus0uyTs5xLnTKzJRwCSFT2b1_T0zL4PjFH
hywmfeMNl3wnWLqNw5w9zAjxYcG6seCPWbrXxYrYwEARjxxQNOXjwyxcvdu6fyNlk8JJRkXngPFZnK9t4_NT6sgFz_OvJapOT9tD7NF1tStstHjNWt1w3JCk
QU47F7oIkQ6hzLUwLo9giBtr0dQnw8nRoOTrZ06uh7NNhC_kdDKcxC6HDeMb7_3mZy4bBkZSb7xDNLZD3CDfx7l5vH_msFq5ve8JFGv9H5Of1eg5EIg6i-CR
S7EFPBjdsVpGMxyM9Sg-sgDxjSeKcA9XE4y0yU8FUBGORVYXzsknxQvNyn6gbfMoLPBlu3m0SA1BgMCBR8wJTqT_bvWb9CfcXMqBW6E9wMguEovwaOjVhGxi
0r6a_7KQb0BWWEqnFfQym4N9nxDNaPRZfiU4KcvsZExac5uPVP1jvAz1zpcoJyaYgPaGaMBsxSAfD8FJw19qbmbx9Q9es_13e8JWjDRB6fVcXluIT1_FNZcs
Nzs9inXiRolRuzUuAC4KytdEVLimCPmMty35GyUHUVUl3MPbFMzlNVXjNF8IIPrrrsqrIjIcSCPKP7s9Yn08MEtZldi8neJWzFpdkRH0892z6k-x1rQPjxTk
wSzoiKWuc7sBk-uKES0LPoWVkBYXlmCwPg-_kYjb9eKhZZlTvJxi_T0nUzMjUwNAs_SOWjFB6HTjRuEEsPjkxnb9ECHaPXYE9SVbxT0n-yRC518r3bQRDeCx
j3vQwUFlGiViGs0o3cQYiirUoXIEus9_0JfcNqhWH_UYGipLJ4Xdx06NTq77x2a-kaULRUSi91FsWCixeUDDJYGkh4BPEBZkRlI0orkXO_RAdCbrX-q_01sl
zg2xWwEVW8xPQswxxZdB-UZLFWKTinTAlxgV7sbLs-UWO_OFc5ltr4oisZ6VX8xP2mNcQ4BIH8GrLT3z0z0HUw6y_K6ICb6g98S7-fFGCVic-hKvRh4MOYEY
vBhV0ZfUxTL2CeqMZq_iNQ0JuHUOOXOfcjNTy6y27Q_s4bbD7sEl8JodVoVe-4rEf2XcOXPPikj-0-YOlGMIzD1l8LCfPdOdw9YzHWjcbQA6I1JCx5xGCNlB
rMfc8gOiPdOtw9YzM0rI8rCrCxiVTCnUYOYAwtudw9YzvApYkjyCEcPllZk6VZVsBRZk0FeDsQlh3g3VYBtFlQ5ZzXZwhTdxxeLk7zx10T1lclHi3w3VdZs0
Vdls0FhjsGFejsSFeDyzfRqL-dy1
}

sprite $image270 [94x68/16z] {
jTK9agmW30PW2GdPyFxNVIMT6gJDB5RxKiji-a_u2FHsfmeBRF-hICsibV-INSL6AJsV3NmaysXVyTdiqipK35_VcGay2wvc_187iU1_35pF75KVumSUABBq
6loFWAlPskWJ_06kMShd_05-QVmH_W1NhT-WbPBmtmDlMo5CEuU5_oxu6F7n7d6zP5E00mV_NV2vvi8CAnek3z_X1xvEOLKkynxcjLKC_XlW_8P9rkARwmmL
qfG_1qyxAUAqRTKaCowicl0du6fAwMFLJFqx07gz-3kuyRV_NBu9BznU5wdKdy6jWQGTZi47odHHwX4myZbzG4-xMLKlps1muOKDE40YlvKSV2uCTHqxe3hN
K5TnXhUxKoa1NoU5b5QKMVN4KxbcTtDTmPFpt1WcIivK6gKR6C81RcPSakTQ2PHqYpTia0z8JFy0ZwMap-68IGfQeEGZeWT_eD2M5uXP-oQX5QmbVSdws5lh
vg-JdnzYxhGLxPGTB3noCEcUzpwolNTpTrCrjtU0UQUWM_1Uhqd0jxRGTzCZiU-lzCZNjpvOOQv1pY5q7bseorMtkweTsNkFT7SR-GBhqcV1YQSQlpd35aMz
cmwK8_j8RpFVFVYtGglrv2bY5-i29LeOA2Cxqb7D9uzJgXaysqREwUIMRMjzeaHfHwRcCxzRZQLU2jJDOCiBpIVAJ2T4KZ_nnmvcyPGThHmbqhbG4nVzol_k
4xvKo2-MhSWL9T9bKv9QgVk9VuxSPVAGt__MOb8yicUP6paoKgJFwQp9M4IQrCln2V1BklkHtbf3zzc-cZFC22YhiiBNy7yTdtujErfMGo8iuhRap-albmdn
iVKWUuOIjUzLNoALaB22z8N7ABApwUV2UuuIuRrj6zahiJMi6ZgdVFnkF8ll4oLh_3NOfVd89yHEOgXzuP6QfrCSdvwZp2iGPAHrhM1QQ1wko8ThThKUA6cs
BrCR_2nTg07Pv1aHhLoEpo_WImL_TnUaHapkQC5Zghv-D3QVHpC7lrJmcn9HGw8QFd4v6LvGlW7FzcdocrAZXXLivL78KNBmg8JV5008qAE2nxbCb3-1f_nk
N0kXg1m8v_mSvNlmdByxjgg26mkUUGBb3dZExrWRKHNiasU4tmRF-OMHaKbvyiSKtWJF-Ji2C36QzOZtVXyyvnyu8gXKYMCw8_mkUCvlteqRKjlKBKdFmE_n
TmQdsX6iZ_GFm5D-DsYkZ1Ji7u2dbu-o4fOYaVu9U7xv4026p4VWER-9H7eE_Y5_Duxq07-i2ljftlVT4l3F-7ka9-1FyVSz0N-Atti2_Xp_JV1_
}

