sprite $image36 [216x294/16z] {
tDY7Zkmw3eHXYrL5IlA6zt_R5IbXZ9ClmlJqsNzQwe3uWRPWp7-_hCj-rd__wkntyUyqqVuO_hgnNVQF0l3_XifG_OttrBMX-BKh-ujKVoOVrllBhkioWpK3
YVPx-74zyJrDZIxANPABL7qasdNzcePlUxyfWH2XzBWobo9w9fVzn8Q7zNIz4we1BeeIvIGz8joBAL_HUrUxVfmPVjBRg0nf8ZUC2KfFuXYzyepse-nDOQaI
YVm3agPSdca55h1tzJwwyxhU7rOg230oQJkvwbjoLbohYFG-nf3pdyY-V5Oae3EiKueyLsIAw9MwosDeT5xl34iM1ME2i2Bu15BPEJgMAt9UtSMrjv8zyPrW
5mWxDvOXIuyyU-RbgYth8tF6cFzWP5_7Gh5WPiqEYxazx_9ozOfI94pTOwfTVu3nQrWDv55TLxeguXo6z4e4w1kctYDfMhRq_Wds9ImZK9ZDCYkLkCBAAFyu
3rsabsk9GemnPsVlRmXh02rbPbQgZ4og97SgUV9qhNftahrWeyCNR3BcVzyCTXbufbN1jWec2G2Xvoeirohg_ieqFEQCxkCF4tirYm2EwwWgWWQjQDYo28XK
mLHJytIjvNt437yds7L8EB3Q2R0b2aR1NG1hOX6nRo_srGXvkkOo-PnTluVnbQo4F6qNZMQaCMMDSY-Q43jHwWKRGQPh3lO5izy_tx-IHGD0m0vi_z00K309
ej4hCqRLEyZj6kxgS-KH2NkBAp5PEAoF5mqDHYQAPfAEJ7I1vGhs8Cl5HTDOhZbyJk5tCBxC1T3u32fLLgeDmofXJfFW7k4bO-mZiQThfJuzPpPyy0q61gjX
dN9EQJ8YhIGQ95gwtD4yNILpzYheuUcQuNuknc6_WxtkpA2XEX-PBZQM3ccI8LqceqVbb_fkU8jopM4ZOQ7Phs-lYEf4li9bTgP5qCxVsK1Se01fZypaJbDa
T26sgvCgrvHwmZXcN5yxi7qwyCm8EAH2DJC32vQPoJEWJldeGPQBVGHxpalJ8tanxc-6qb_jkeZDmaQTBTzXZUHQsZ2QqREGkIDoM0vVEyUA2nIvVBbcp75z
uP5ubU8uQaWF2hGq6_VT1RW3vGgt5ikLaHrzPAxbMNNFzvZ-XHTYImBFc596esK9h67He8GPvUwquw8TLtVJs7LgRbY-Hv-_XlNF7XUKbaVMB0S5yBXgatXS
BdCFjrfz1_YefcDi6EQyf_Slkn0RbA8ZUrx0Di5ggvar-O4bQmLkLWnnkpYuOOZxldlSNtKX6eKLzyj0F2xZny1CsO6v9IiZ5alUnmYaAtnEzfnNzBvW_Cs5
-CcNeQ04F1CxDDGwtz5KsHcOAQhk5hwV3-liu5ofhpLcZFkEcBzoyLDXJQHWXuNpTaomFIkSOrxEX17k6zPx3qDFLy4yve4juEtpZk6__d_Yfuyh5MTSkPvP
DTAiCKcjN0uuw8i47PTPf2i3vawXEZRkkFtwYXiCX9Glmp6TaHsN6GcJdiTUQtAF0qjMTFFZ8kB0h2_NFIFksRx0TGai5ec6xJaBjchCcZ9ZiW1Bru4LgtTu
iKA3VLPWkkxbklKCp4ayyVeqbyjKBX64DGCQrahInz1aKDRaChetZnrKh0yOnZmmZw5qTTttkBwzFXuRFz459eiwbo1GDjON4aPAPs0mm5SoFp1BLeLOh3uM
gM2Oi_jo-Omxdtw_ZJoqpxiCcIOLZJGUZXqIUSwCsd7HAo8gcNclHaSeaZLpQdKiHb-kE-QjdzxO03_LPH8tZNP8p_OngLoaUHLWifAt1vQ7l76CUM38zrlB
TfyJyRKrke0orVh19QEo1gFSZTiLvkSPAc7b2bfFLy9QBzUKp_lkexTNkq2dUAv4WMTcE2ufrRataznTRRF2cvj7BrYv0gFZk3fKhhlpNaNtLxjC3fTXkqpf
4WcKI-Ux6TNa6R1TWHRHAyTcZG-OJVVjGfs9qQzNkrnq1q4U5_4nfEswx7pngYbPReIEguiZbctbJ1PZJlKKQVgzyll5BiBfNYHya1uNOGQZCffNiiMYrItM
J-HcZIcVqrMu75VS-UWx-MhNjLtkWc2jI2nNaYwZZbOrgChanbYvnN7v5Pir9th7p8RkMtUjPMwlTJNfmtNcqynoIvwfQYeHu9KkyyYws2knst7D0HkpYeY-
NAFVSNUzb3NbvbuqkT9sCE3UZykhvXdD65NlvicYwjWuBiFStUITURhYbQevmr7ZoZV_bGlqojAVgER5EaSyF4doOas4-t59vHe-rdeTAeiWFboaV-jYGjrb
NgdHc2HPiZB1BKPrdWrzhLwi2Ey5ure-nwjKcJl53vTyPKUK7L3p2XSyAlFZwirw7rN7Sb5rYysCMtJNoUWfVH6gN0h2NTkMbONFvwAwoqn4PCz962Rhu-HA
LXPwplbzVzqninUfvf0y1EvHuN-qskbsgxWIXk6WchyYVV-NUoofs63iOESiv_s1IVUUdbMYCkuMkNDneqQgTvztpLDehXmLc0GpTeZdNFAmxbBC_bXLXOeP
gr3JvouPz-shVWQ0sQh5tDh0aKL53Lkachsmr4m735NyBQfIDcCp9U9o7NNApAsHZBUACt9dPhBE2c_5Qcg2IYbdudrkxe6zlrHLJiDbR4BKvEYIyKwQfuzi
HZnPBlNzl8WGwIfl1b1WvCp8qVO1FOxz8QfotbncIlKT5De-uEYyMIkNBeEbJOGsLpIFqERx9Wn6I8vKXYjmtr-gQd6O_7FP-HoEbssnMzsuDZRtPiKAf-2Q
bDZKPKgCSPcXwnBukCo02vVAvZBgbtiNbKVs3IzTLHzhn8mNGKN5Id2_I3VLDloi39U5cF3kEboxzh005olW5vdFI8kbhGKgKoSWkoKo1SDbwVYi32zATIDz
ukBfKYeFwNXhFbVLulCKSgXWYugLu45Bmt3bvs1uMQQwY_2ZImhKp3OWDzAkiM85IqJ8OW6GOsOavKeL7pwpxAx4PsHueqHtkVB9jOD8RSHVJIP8g5ZXYrlZ
Y02SC181HywCSiIUQHtul4-YgioKxd8dbkSk4JFbHiBYrLAi26dD1WjW6rS5WdFa8X7ehipLycUOVr9Lh3GRBdPbReykvQKHgutrLmblh6NnOY48Y7aQvuOF
qhOipTAq8_C2Xa-YoWKfrnXQ_TorgaYZ7aipyr6p-tsX2uTHiG1Het6V48JoydLhMHPsozNZmjNxe0ev4fkkkfW9oOYivwobKVQA9K8RTnqvgbYaRgorZYhN
qXJfo6lOjUm__5Hu_E1owIxnM_N-bhnUjjUg-TOYNTLpmin95809BOKgLuTvLhZg_nbL4BEQnnENavLBr7jKZ3EdDaSuVpMFMUqB20EaPJgwHXHlmV0hLRb6
BBijPnXFZfgxcnnTRFMgVXGQDV6siH2jXiMjKCTQmPfTkAvXYSkOjbXqsB9o5n7JGJY2zX-Oz8hCk9551EjGzKH3bbQeS-rhWp7AzLlPYzyaT8nzTqMeA_Fk
4Yt6wI0QVJMfnwfjh93MKRrBLoClrozbBtwNqbsskn0QuSIwkOoFhd8gDvBcKR46HipSbkgPQuSrUGjsbhqulqvtwUvAc4M82p7jeCFSh75hh1wX75jjsuAE
e6SJAzSHHl6U2oVNbIoOZacnwY16T9jB8nRTDxpA_8QA-gQ92cn35J2cLfNiv3h0ckBDJgxHMmyO3Z3JY92unU4ct1gDbexq29MewWv0D2CPDwnZOhljmjNO
VolBGsyyO75mGVoVg-SS8x7YK6nj-o9qeK1b9ZjhLBYbVPrXpV1cyUZArm-O8VSwIeV4etZbEm53TIv1qcYOPNgpi2EiAjS9ne4t-wzSnruzO8ey91hUOIxJ
vVkS7WUcD4wJs42jjyBC-1usFEti6f7XtORhrFL1vCX3OMgwJyeaHg8HHoWGtAXM_1XOhhqKOdSwksfU3x0cyRui7xiyY9x7D8pzV13tEJaFb39fmvROTALP
Q7ZOau4jps7aUBTyrkjDNuKZMBGUi-BjFh0R4ri0gjWQ0qithAjcBAnoXjN07c5DtrIj-RoBZPZ735242bdiprcO0FtAr3Gm8rI3g8Br5cnrYz0phBNbxAeu
ta1zVt_dIvZJnUQ0mns0tVqGhopCBEe01wfkhKZOCzUUvPhIH1uVCQBMxnzWPAzLvNeXaulDaHvGt99-2LM_LNkzvmTD4OD9ijTTy3NLF8EEi27xAiqPrYIk
KULwAREhWQNDWTLvu_EfsmVctA_62X3-mSnzNQCHdM756xfJv9UgShsK1LyD37eO6DGnKiCi63lHXRsJGh9WOTvrAe0-TJtNQLoWodNTwu65cbqCJ4eAvqM1
775apnIhhRrKPjfX9zUZZkDIzTgLZmCZFy5S_CU1bTI4DTIGCt1cklJjWUYkS8wC7LQkfmsSNg3AzQg7WN7Smpp43ER5s3YLYh1O_RUir4qyUtrWwVr8oc5Y
LwvXimjLkLu7Ff_44ymTfZHWnOCh4AuYKekmdgiHTF6i0jv7zhqo1-Gjro9-WNhVbK7tsGCiW13RlhMt_TIyTr88a3CTcX09rwoCk-hxUpKtbLQmdrqBMvJg
XFgzA_K4ynCiBBPHXPutOTTK39YCnIF8dclO_00XyEtDmlx9djOKUJ6gQzVhayXnXaa7n75rcDNnsvyhA6dKhMHcZBVwIhof4kD4yy-kHJn7SrGVSANJ0-nU
DZYAdc0cHQZd2YRYveU7iWPfQyJj-HgBaPiPFtUH8MU5-e3hyIJA6PPg_W-MUJSdCrVHmHJap5eHLzSRAR6EpCBfqTKaJgWFkP9VmW0tYNaezpd1LPKijsHE
Lv7QxzOqzpKTQnKBgzox5lRSLHzs1Js38U-3s2tbSLLcLVDQ4nKqJGSpV8mor-XtwvORKW-kfZYXFkfAfrCSU9J1K6kalvhzysRbGjXkewlM-LjsMSf2t4wh
ebH_u4fxW3b69rYCgI3p0GPJGuRb22PvKtXaDLMPO4VG3NLQ5N_aIgLpXaTPJ4ijTDzWpbhBSCBSOaqlLTLL8-UsD8tSLN_fIg5p6dYamSmT9Ge9jriEFJnZ
PdrHmFsqURA2Nw5-xy9l9yQ1Px90k8jwJpnd5bFQqP7vFtRkGybH70W3y2LrLktxl-qDApRyt21WhBQHw_vAZXJVj5e3CeMA8Ges0ge7NRRa8WmM71opxhco
hSzPHSGYmeMXLB09G0rmsPfJamTE7pisarOZOLLfqULLw2h3W6g02xTzFDrZbs60fleTfUPkgi9YkwOMG3tgCiZHCJ1c-VduQD7LJDLsFHXGFUGoJ5z6MzP7
i6RzA8iELs50TLgc_snTYwp86PHGuGmL1bddPRnbDHg9zWkrtEuh1uK1rHMO4R1-qSgdDbMcPLscIBuANTTb1Lo0QpSXbe-ijyLkgtwigIXqUNnPHi3gvs_A
BnMwFFpBClxdLYXqUHp8l1Eb8ze_fDP9W6geo-CHcPiK68wTMQHJgYHNN6upj2alyyFg-txz6pTI9u3AS7ayAaCav4cbGXV2_00sJWQeH9V7MDdpIuKkW2KF
HaJbk_9bg7gY2s6U8aDKlkkwpC_dkIfqfGv61zJpNFaoK3tNbTfcW7gTwxniDjTvsLGkX8LrCvlhV9jDvZelcy_bCKIMxug8ZYkhpIBNf4oba7Z7bTDcaOWo
Bcl8m3LCzW9NA9LV8U-u4jeiosLSCDnnPRHPv9KAu-1Aa6MxN5OLHj2LFHXZ_5m1eHz80bUwB38785lKiFMr05V2O4np1Q18V7L0Wu4hGPRiOlsrPIbB35mP
Wp7VXGSOLfOek79agIxIg93ek186unXNn6R_BUesDC3bSKOMCSRbGhvnVR95xhX63aR_jV5u-6ZfhCl0bI3pg8DSLCwvy7FkARAezIMk6E72DiCX-7HNT8wZ
nfJi9oEUwJ8yKN4VBOjQN-4Ic0wh3uI5DzKhN04V0zS8MTGNkGpQ2rmZP9Xy5vPBmPKZktpSwyf4n1eNNDXT50ak1nGchfmiabvtAQm2W6j0m8IkaweMFUj2
5WMuidFiSYuOl-GAXZ_7RLn6PHC-vy9QSzpBfGK3Z9uBrziewcrSoAAFb1OvvGfZMCE-XmjP9CkdGjTdXwvMAc3ToUNRrGfhByIH2vT69UgjN47_QNakpT5t
mLH3LkkzN88JzA-2MTy5AerwCvTJOs49pxXGTJUNjBaFmp2m-YwsgFKkBYmDnHPB5hNdmhNv6xfq7OKO-FI-Yq5_AnTZkJ1z5vJgPgw0xhhcYdfVby74DxqB
sylVpoMmW-_ZuZTpuGw_gKlVT1nIlAUha7hKjWQkIopcdmy_3_lSBYjxqQbTGRimczY50n53CQshNp2TsLLz5qPJksh87iodSs72L3wYwtq7JQYvR5vNj-dq
tLpLtzHL-KrTEfNhVvSTpeSaTTPw-RwBDEgCBi43nAtBA-JsBe3mqJB8fF-_T6vNx9sz-CmkP_c42iDmGfSpx3-Koz355jEu74-py3h2-DsbKAoRkX1G_FWN
vwXr8XSUjYEByFDpkG8MQE0ACAiJksep24mayDAaBiPBW5nA2yUyBhpYIqs5OEbmPbSKo4NMPByxSDJPNRWg2iqshGix3A-tczzL1LGQTLo-lT9LZU3Aj96k
RwzqrJ1X5WNK81V8ybt7-RVxkRfk08g1AFZlwEJsNssOqO-aNKq7i-r5rnTTNz3rHTSNqVG5NLzqVN7Rz0LTNqJJ5_Y_WX-vl_YDzOk_sBxuX-UB_uNVY-ku
lRYMrOiHDYy6URmOP_1YZlYBQSelLiY-WaMIhs2Tu8izn5vi8_GATf9viPl4YmFgNvnH_0gEgNnnKjKhEAtaHOBy5pcIN-H9V94gwtKXMQIyA73y5TGu_ABC
vU2BKeTUGRKZBnHiVo5Yx-i66HjVWPHTBzHiUI4ebb-8MdkXQ-65jiaNycPUWO7n5oR6NlWOU67bsXTshddXwDyNfkBF5yR-U67jbrTWxuTNqC6t5qryVj78
-ujUNbwqy_WAajq3
}

