sprite $image414 [294x159/16z] {
xPs9Zjiw34KbQY4l1uZ__slVwiHqcw36J2HJiGwsmLlR0vAY9CfTcdC3NgEGPQAAFwF0Sbbkm74KkbmGV8Vfw11NYYZ5ZvXnT0oTaWwXCfFj438b7KAcf4Fa
Y_QHSy43S6LF0eMQRHTKjO6aKVk2BmLmS5ElQCRY5oWEeoQKhXDE0c-CjvvFJGh_w3yi9uAnK61M8vV57KEZc8wEShgacNutV1IgFfP__tmjRoRZCxdDcdIC
hfAc9tmwsgbopu32DMWlQUOTC3tDghIZPIZDSCBLK8-MH9W5hd1dgL3u3yeyz3uO3U4ODeW7pZgqGsBOaGHky6Efh7PYelM7OSC9BP0A0BnQge_SYm8toDcM
E8PO0QGrX3PZQT2rhbaz8eRSLpYvPn_14wTQgk5_ogD-aqZs5ql0MPPiFM8OJP1awf8NpiwuLGd7hI3LB12k_y0oc2Pjbt8a0F8MME0SmqfCTQI6GD6mCgMI
mqf1YM57B0Cr16W1K_Y5l7FagCkydNaCLocy8iQuHTZvzBTagUaX8wLmXwe0mlTChAEK9ZH3kEIKInN-FSVA-XT6MUY-q9nyZobZqAnzG-GScaE_xq_gmzBC
kPLaQlLUKX00afFuRmSKZQbXVt0YEPWS_A-HoZ9pZbPDHG0nYr-KHsiLg_USkw4nGbkp53P898K7QPIcgVqoPyco-wl5kwK5pP4KzYIfCHZYLRTpUwHGl1j9
HSnUpxJXN74AhaQPcTVZ9PDi9fGadtLnvt5Wm1wZf3MKjh-Q1TrHVpCwbJP7QxsAzgz66UXmj_rwHmnPGqcI_QlCw8opXr-c9jM7ihYPYnMI-j-NBuuqsRFC
l9qD639GmWdboUNyO4tyhDjCWgsBYcL0JUtdKgY2APmppgEEdu2LO2YcY-e_pkDuqZBQNPtjeY8z_dh7M7AQTJMQrTyeA-PlnThDajkiAsRrNxcRoLtBa-_v
Paancu9ap6pcCWjQu_r9WLtzGtmKfoJhheLAQd_wbDq_lJ2MI235zak5IkvHdePuUv6VPXe9WDAbF8tnt4cIRP6OZ1QX3aVZepmBOx8du3N6yYGZ2nenpdFL
ickHv6cF7cjZIVuzYIbFByUX4hVkAVsdNJAfPIkM9KlZM1gaAqZoR4DCpJOj0tuifX3ld1arfL4D7_g3CJRPykEl96bGbWRrP6kvDSFi_DjMkNk1Mg7wJ69D
L1k7al-0Ag_Flo4rasaBsadoxqdIytMV2xtro7VqBtyo1M9On1gYpCw_ID_BqxuGcRuWL-6IY2WLdfybV6OeLG6OZ39fBCb_xadDHiWzT6hOaTi-HV5lIkXk
Y4nonR27sFq7dpkqJcIk28obA5BY6vv8BRrGxLB5EThtYT6yxXpi0-9e2DzxA5erRJyoVeJcfJzD9-pZxeLvsYorxmhyMxBrQDEqNkZH_srenG_G3x5afbKV
cW2KI2Bv3Nkxhu-mnEQgZitnhyWsifA7IRlcBwGAKCsmECUtFJ3NuIrjFWm4eR27nkYUUhxzAUOlnBUSgSW7M8BaQBoa-7GqCye0HHnjgPbY296I4HRBBjHe
W2AkQ8w8I7foctcF9lQl2JqeJ-krkI3shgdldCh-XRcDfL8yTmIAzZmPvJNnHQl7M1r7K_SvbI8YzYDF34ac6tr6a_QRKx7Daf5asgXwuM2ovUdrwsdVEQTz
hyijnDPSSRtGeIESjeAK-SKaXdZSgmYw8hNaNAe0PLUVp8rwba5phltdrf9iQs4iKvCT3RDaiSyJHbhdskzP4c-pqRjIFZKnxUfHViFZpUKJewb66p92Fpx1
39_v1nqNCuJoZjvoSQEfVLUUdH_8VU4Szhsb_yi2d469xQzKnW-d78ARGql_3MO66baQtvETylLloOB-64Tp0AmfItzqMZegwhkgzECjMMxwtSbiz4UNC_dU
htJ8M6fVfHJBZal5aaNrLTNni4ukOp8j7U4s9RbhkfPnSLMwPpWjW-D5qemcMJu0dKNfPvgc98lCcdG8FKtIzAJBvp43wHZQLz8KfSk7CyFe83EC3j8iZAQf
st9Hz3s9DbMfB7_cRm
}

