sprite $image223 [236x172/16z] {
v9Y5TGL130CNJEg_u30d_dXaPHeud3TwstP0uBtz2qRW2MlyTCSRqiXHV1Ap4JFn3M9jX-CNoYcguHUasWeoOf296a2ETRxEv0XXPt8cdwWvFXWxaslBr1bY
RGNN4fElCpdU-JgJOwqOXZiGGb49PkC8t8rtFb5pbERt9PYD4qlYe_uW99YDXXKGFb5pOXOOX5JQvfqXrbQnEiBOcLnRWiwKcOtTi25stCx440vjptT6rfWN
CGxO6MqlE8EsUjaDzVhzaJDzMBb8yp073xB-JlQnPsVoFMTrPwDS_SAzw6oSSRr8lUHiFD-PV34NqzPk3PzWBMolpkGuLaDswapE8xNcWHpD3WBXfom4tF-w
hvoJQiUcOLU_AZj_XfwcqSn_9-sb0NPIEYJjuJvZJFH-nMvtMZmKwvEjUiRVUeV5GxKAeIVVjSRCuGEXSH8PsTzyUmfTF5X_O8bntngtUB0sIelRMfKGdndc
1q3wbNlt-lQ5kRI1ZOtuWdlq4cLhFN__nzU9oXQOO9UeggvHi_jMfoSiGLJt1VTYUSPLeLuyXxCCNthE0llC7bYV3y-65tXUF0SwE3RY0Moz0rEl2UtYv7IT
tM6VkUvefcRbbKLK_I941NpcrmMMRaAjl2ahigYR6Vz9rmNcQc3jYuXy1JPI-AQ4LIcRv3gz7oRD-SswlVbEKtRqlyAluHUfI_uis_JqRHVD3smR8nTzB4f_
trFoxR8oclRAF6IXIKHog_MpB2pjvN7CYpg9QDtGUH71qbu_QIMVYLXNsN-ogs1_4SMSOf__MNNtxPrL5a67Lm1fWuBi4bKUzNEv6wagWwJ2x4yB1fuwdsYV
sNhlaqYV3Y_OyPa3Q1kQPDjaqOyZmXCcVMLbTaKLbOhlfTjJIP-gC5j9s0Z0gc-itgNTFrxmLJLGr3VMFIq-3oV_TnyHqYVMC5hf1xoIpQeRLlT6jiLOrr37
eXlMYD9kOYn-Yg5zDwmnilL57GRI3MkKR9iVQHTbWr0th57-myMfVLc5hKLzOmrlP4euQI9LMNRIDzPusW6txnEfeNqthB6qZ8wDLLJOu3DxrdZPhc8Mwb85
XBfXFLMsQM92tRF6qtQBpnY4Qc5bVl3OM0q-Os0z8ErbKcMuVQzP3qXxmo1KWFM1QQ_zGQYY46jmsWlo6PmrFktX0o7E6ZysuWCXplguj5SP60W1rlkdlKo0
K17M-u-Dm43eoXe_DZPW80nWPQQej5SORL-SDJxj0JxZpXelMy1dd5dZ_GTOF3Ypne-Di52lp-H3Q5SqgV9_THr1Ymdr-hmEQOsFfyMBEjz2nK1WpoVz6geo
dKwxWFRz7fRRaRB5VMR_vdQ7P7kkKDD-vup0daXwwwuXGuryfi_i3oxRiuHwVJSu63X7-KpwnQxz_sRjumg1A8fXw7vG__LI0Fcdowk0v2FPpFzeO_ES-JpD
hdstdZCWjeupps-zDdhEF3-iZVES6NjMORBj8SwCFGCvt_OyPq1iJt7cXw02RPm8wWHdD7_cXuU14srlFgWJFr_GzcxxXH1e8-0CY2qGmkS7sfxY36bxyyF3
m35jlFOC3pwsgmVkWLFQU07EWBPtP7ZmiLMSCMtluF3WjV4wFZp0jWSum_W3XWUcZO0pJ1i1PrZR0yC3YoqO7fWs0iwms8BXWMaZu0pJHZ0yiDY2uK6rlG1d
57_ImyF1Fma2GgZQNa08LTiB30ygje7XGRMz06UKDWQ61zNs0fnHiGrmHcbZW3DA6mESKMqlm1dLzWB3WufjO7XGsXWO7XH_0iE3Qdi1pgYs5nWUb3O61cuL
su0GghONu8ngUm4XLDfeWde7
}

sprite $image223 [118x86/16z] {
lPY7Tkim34CZMnEa_lzpkrTu8XfEcV3jYIDUNyZjvTxPUqkN9q-gustASqFBm7igUdvUvjunlWPjUqxcrZ1-1wZfAK0nhWQFnvjjvYVU_T50pJmSRweOgy6e
wO6sEBdv0K3jSWcy4ROGm-BbRQ46ewH7sKBW3RU5m1iBbCWdIvAt1QDidSKRPSl72JPwpVa_oxMqCadvFejI1Mu-cKuj4dXfeBPadS8WyBAss5sb08iOeFRF
mQh4uqtLsB9U1Pfp9rWyVFq1DIsnO-Ildr4boTTVsvoDr6GUTlCZYpTPAuh399dd0AFkxtyzRRc1nNjpMQeoMYQmzEl_Tk_E7KZSBH1LHQ-x7rrGhnVHYP8q
jjoETenF66Q16JVjtHQsECdOLwaxkZt5GKdoBmkYVLkSTOnqS5RhF_-o06sBmrQv_fDqS0UcIcV2-J2vQR_gJFWb2GnocblaHVJhBwJSLGvOYR2nvQ2_2rG5
45N10QZv7ilb2evkhRINKlBkAm6PSueunsMVuGkll-ZyJkLpA_scjrhk_4xbSw5IgD2ooZIfv75XAchHLOeRcvhJf9x3czpCr5MSWvhK8BprCDEcydZp8ZD3
STCMBvN7ExPRnWp5mXO_bLzpInPeSvRhf_Avrg8YkiZaKWKaNcJ25YBrF5x75j79ffx7IzX2f_9uwu4jTdH2_nqBmfQhpAcf2ftB3zQPEkTxesvTsJNpcSv1
iN-tM6YkU9b_7IznQnPlkQRFKXDl4BDSszqnU24kq6mYG_3wjgplPCQY-sqn4u2NiCMRVR1hve6kNZnulC1fMxXFx54boGFTBkHidSDx7cWGNXUebil9AJvU
0kXi3b378ZUNg3z--9AyqvP_MgHS_V53tO5ArzyzU8bKqfO8YvIo9Hgl7huiyCFVWHfWo_cILCAMUBmQQ0jVaXfe2ty7Qg0jV4cgURKc9W2l1jh2bwI-P_As
19Ma4a3ZyGRQmfUa42yByLF7_Sjz1G
}

