sprite $image254 [236x172/16z] {
vDK7hiCW44NHmPKnZBB_rVvsVoT2Let9EpkupmPk3-1lRXBS8L8AbLAef4Ab52AbK4c5IYbKIY5I2fLKg9H2fHGYfL19XKefH4gXaWgLKgYKuYbAS_PJdY1r
CLlydC5BLtkNDZzduD8zcM7Qnwtbzroz9yzqOXupbj8jcQMzUr21COyjl-T4m9IznHADDDgFx1_c_kTYYTQKHwhr3yc0pO6_Impw8rEAjVDpBWQa_ykiGzJw
jnhbRz6SctS6UxpPHZks_ijH8to-ytFcoO2bHfGIxJBNZdM0scn0sjp_9HqHzUWiSyrQRvKQTJDW-jkUAVrU9XcmNRJMx-FdH6EhKKjtcKiUMqU3dpEzCcyc
J7R2C0oUGBWI-lz_RazuWIzPvVcDTsZdRFUKRLcIeKrf-LC7LEPvsjgH4krIMuQjZ2ygCpnBMpjIqXRUOG5IKHbJsdi-kQLqXpeLehOhCprAMvrdvA2rTURk
ZQ_c8VsXRIdEiscFUKOdDvh5cgWHMwXUQC_RnXAtHJvPe9a5AKiHGTl_oJPoF6Fly42TOId2VDUVFNwKzhvh9mrwq69JPrWARg7IslICRRGdDnuUrXPH-MUa
sZvX6-t9RH26y5wAc2yg4w4_pzBsdUI6VnnheWxNqRwgJ9WVj8tsvDRNcV4-scLSiOMyqvv_SklfJAI5eif4LlC1s_X1SejxKsVAQAUcoapRascFI7K-ET7K
EZDmjDig4nPFsdv_SWj2Pp3QK1bX6nrewvNSjCvmj3NvuoDfxvtabcFF40uOxJxvPv-qv__8MElC2fsHv0TjoqUok_xOaSv171wMkvsSEDf2iztIdXlITH0w
CuVZzus2QGRQUgSzGhKV7a3IkENI4ZAjJTjq8OHBslCONqNKYyszRzAnj-fMYez_shE_yI1q9jwtPjcaccdC1Zi-wFsGG4FLXmUMeVIoR5BDDB6pNTEUdQWy
FD0Cba-BNoKQbGqE-8l_GmAxph03jHdCe2rtR3yRH5J6vo41aMf6eGDjCuXUdfiKJ1FPO0a0uv7sxEFB3h0GOTjJbKvfZNGsM0Vi8BUqjtsoVbSiaBI3b4Yd
voO5qsPiES1lj3P_EiSRa4hza_MiISbqsh16Iq0sEE4BBAm4LhQ6yExdzTOWILcdqzic3NCx6mHcugKNEDx7cZLOVVJgvHNs4fiKTWG2VjP1lFgsWKaQwPwp
GcjRWoHbdKxvBUhpQaQkcRYnJHABV9WrMjCQP2FPRTAMRlhu_F5QY8Jn9TgtaHvOiugNDlS2Kc8SJjgEYBqzmUNA8fFwFRfWjT4sz6XRZFnNj0s8lU0hZd5G
l4Xdt6zgmMf3guzUR2IxVQQzc1fDZH3STk3e1beY1LOZRISpRMaR6qZdm5ZH3Xmwq99Jn6flRHwrlU7JAIRtVSyjeb9mgJF3_kSZyWv5eXAh0ssdrYUGjYCy
0iUNWhlKEhFeGCln1LOpMdtq8g_B8AUlO_i4mHKw4vQs98HL8INMFbhBqOl-_zevS7K9q1dWRra8Ehcv9Ygnsi0QZbxu19vOhJe3rU76ZvdFnHHMErfzz29j
aMcMbixiGcTeJmjjoze6KeNLZhQ_8p9ulVv36ax3DOVMdJbMvVbHsTD2sxAsCRu2Az3wsiQoOazrYRTx1dI63-fRh_ATJUHxoIQiTlqPkcclUA7YeCRtT6PA
qfwcZF4rOtLFUmTHfywBr0K_nBjbJmUXg0Qixcdl92h-r8PGY-e-iGGagXshBUsrwCHV9BURja1dkgAQnjVQpgAf1gpkQOzzuvsvVj99yRxzd57eZ1MhLzhZ
qUU65Zg3ZrJ5cuizNMr8YTL5VvZsrhhvdSD3KQ3R5W1jgJCEM7ri8rTo7CTmw8nuqYd4E-qPH7N0wflss8GidtIkKnodhHBlMUYC0rRdj7UW5OU7LAPwW7WB
dN73Qazx-f2RKkUDcXUuAstZlYVCoFTWTNf8mCDBMu5UH9WBRSTasBvshCa_xVNVg5cNPTkE7JUdL_64phXWdSBYd_RqV-MPmiKLdTuexTGP8F70-dixeBSE
3mcKpXHg_jjWfNZG6N-i_qALQzhJRzJ4rqB-rSrzw0Qlmb00lfaGWzJtVzgEdBZht21akVfZtBtxDO1jY2hqiqZgR3rZz-pssdVKvCRyfk7hRyLUVV4w9BYx
esPVvddPIqtBicobtd_7FxGY4c5DtHxl2Uf4rLRjgwWo3r-xTKCMt5pAHeuLtodfsnbzlQCKyT9bBMNdAsllzbZxer0wN2OgKrzU-gpb_4t4iMoa5KjaGK4X
hUD5E_MCBcivy4fUnQ7RuvYpdBdquzF-I8heiPvbmRkLigrnsYx7xsDDQ6ucQl6G8fhM-T3NyeVrFqFPI6S0cRPOy4SKnpp3L4Gxvwo2rxRJ2htva40BmaQZ
wpjyELfMv1srGcyVoDi7kT7e-aivMbR4bzLUMo1xtgvOcskUQSJ_MzVrftM-1hRva43k6zt5VQBsOpS8hsubmrfa9IntUuP6Tpcg-0_VjfPpJfg0WnKl3OLK
SyN2hl1VIrdB-VN8Hr7hLo6Lar7BZIxzWoT_AGTRDM2Tidxa7MhezcxJId4SlWQjR6GzYrQyjftaHJm6SdKTlaRjGjOFfUmOpGAoWzOppzYrPDMOhpfPYeFM
Cy_OiR-iCpRCjDl3lFNIYhFKheKLAKXtKz_XCtY43I0bBLcn3AC3IDThw-zvAy-VgAnbAx0JhkHqLXbxezjxwaLbB5j1n7o5Kh9MaQGD8cLjrlPLDohAbNP0
1PwmJns-RQtCC8aMJggcreUqZyap_TeqGNjsOXiqsgOOpstbGL8k6pKsNOar1Tr462bhbn_M0wzFOZgIBy-IibQRzwHKvDXMI92BobXCsnch5QMRXZQ2bBL7
pg3I8jo9bV9GAMiHAw0BTJiDxRFoJ5lBrAnjRBTMdYvbxAvBr88ggaSRIChPThroREh4IeaXPUsnQIimbRu8GsNjrsZE1ci0AM451N5NH9AobZRPcX5CobhS
PT0L4QdSxOd16aFA-ISPh36ahDqDrY1KrdfR8GsCDKZ3QWtIi5e3DQpM88sAhU6b2BkLgIDewn1IXDNAqlZOEeeKORM2Ef2s3YH56AoG3gMj3UfesZgS5D6m
adH4R1rHYc3hi5JMrc6bhAqa7HTRIJgkjX9rN6qbwRZQIj9niPMeusehISVLrdyYVGC
}

