sprite $image270 [188x136/16z] {
rPg9Sggv3WO_ovjasU__kFVEn5b-q2Z6bGeuFVjw-dmqO5FKtwIrLlycRV97pITI_nRIhlpDqQtz-UQMFsVEpSd--D2P4Az__OT6p_YNREpFDnV299Hsldsx
Kl05rSEp5pFw1PFzoQCRpis--QFZxEpROlHpivVRqICCnsRVRgW1XbEpRulHpys-BKO_DtlP6DtF_i3HJyw-BKO_D_jcHzyZ4h79_WMXLwdOWme0f1U4qsvW
GYYyaqoeyGNPMtF9SqXpYF4fzKNPkvsNpWyrdrgyUn2UbBsON2uItCiwT67S4zbC_vnShaJjUH6wHXZCa_OrxqMbQu9BwVoQzwhcvt8JpfWzMw9gX4ielvQz
kBbOnI440ydWZIFQguukfG_pabE77Vq9Jrel5vyWOzIhVUxEwB_zf6sBN9nmUhdyXSRz0-RFivTLBduucjz3zqPVFscVbeiDHnFgCADltQkUaeibwVWNnYwb
NP0VcayuO1CUEY8sIRtTXlh3q2ULDlSJGk8zUMgZ07bXlpUwfD9wBrl9f3d-pkDLkWG02_izypnFKkQuua9IlwOiSF2E3TPUziqd9RnRS1z2Z-RoHMuHQmAF
uX_GscReDlCeZuIJDDzhhSF9CvUVsBV5XnUnhS8XiQA8Yt2esV-hjTyEtQxwRJYbaVFt8rpAp6LfBvkXMx8JZhFlCfoa4k0IRkmtGxS4vu8KR2xhdrWG9qB7
VZDqIwWc79F5O-4KynXksblpX0N4lQnMNJyoD7FPj9VlGiy1QwXfychsYLhmINLoMThxeHiBrqF8ZM4TJj82muQz7Nthz9IqEBaimo6HW3s8suNTq2r54szB
HCsb9soIsorgGjyZYexUDZM228LQ0tQ8sjiDNLMlwjWZrDOay-8LrNbP92dOkaEEVZNlNV_5YNr9wgEN06GTWnz_WZV29BM4X-_keryyjK_t6_akj3E5qEUV
Tdz5_-FYB8GrrCpeqztOruT7rtHPyw5F14flTxArO4KnvXDLOw-zF3HwptTQot2Y_Ly3WTFYFpAvNDoDVTUq7hqQYKKuWKSBW8KgVVSVZQvcTEFkPsyjsVpp
LJYbz-nEKToDJ2xMtOR3mH-zEO9-E5671FZa10krMtFjZhi9fnTdTCrm2TA7tJUm-Pk6J7O8aujnpysPtcHl3b1EE8tk9IHW1UNx_uyrj-xH2sTA-EVlTJXJ
GZCU8LwsuZ7Kv6BT2veRpcszIGWFG3p3-SY50nuaqjSxzi9ykZDOjQeJJY_kAx5FQdq-PgMRyXRs04YckSd5kWkA2geRZkRfapSKGj4-EAatka-8fPlGNVU6
f0MPsGsdHOIywK2itJyU-qJj9dJVNK4QmM1rijS-cB1DaIA4FKY6sbnyToKeIEjqzyA9s2EK38HQmjPzO0md5yyzeg8AYQgg5qvhUnjc3jiNwkA-klZk6GHz
RoObzUoL0rpyurNLZ4T8vite4VS2v3VtW9gWhdnxTCEQd0zoV69pJbqBzmh8ktkAqzsrpt3nJuNPdDxiWSV9PUNE89tkf7DttrvRNEKI_jDD22xLkrwitPNb
rhrvykkpVOvE4-g-pcPpIDznLxswDwewyUnhy799gozu69BEqHtpJVSAeFds_fMMylAEM-rxqHWcbrrtoVBfJbdKozw_qgQmzGMF-JGmkUoxJzAxEvXMygqt
klMAMr_mc7_XvhBlhfm0hOW1iH15SUpjbJRuvZQI-PXblHrT-nwZLhr1tjohLa8WH6TxSwMDcr_mQ37gCAFlKVz5xs1KpOAi5RmAvoq02jYYZicFpQsynimX
8QiMCk8c74s4NQYRNFRD7Vi0HEJtso0NnzuSZtUk9J_8POnQgsilp2t7MOyoKcwE_4HbP_h0tcrqVtIld9GqGbGPWBZJJpPkfNbE_fDSrl828EeSFmIaXNrv
z8j9_UVcQtkXs3xSGPc_brVDM69osG_THorpTwtWLJWjRkMo7_g2xzpV3vYLnBcOTAPdvcBntGLPLJMXUTlhg72e9fTzyttxU7KFGGdVXTFp2tBnxKNfwXv8
sBVNhka5kVZJjtXnHwIW4oSSeVjSz0cv-DdBXxiW4yIJjnzzvpwUPExRYqptYae8eeRRAieBSbcyqo8KC8MOTEA7eydayZHpAz-8226XKT3QfEaYd5PUaOkV
VGW4fQ3AmdDxBcuuex_GtDgN4kZDlGY3gAeon0tdDRduzeXlxb4O0Aeos2ddXQFxuKHG8M5afQ3MNKymzq_7b67SFNjzgRcrL_7T9mUCxjbBRXVtdAt_GUPs
UaRwS0SWQZWW5y-U0M2wfwQirSYVOcxj6O4eAeCRCvCa8t-AkhLdvFa7Ja90gk3OZFi9vbQ-iRmVZbki1QG0ad4_mjn_jHSDIILgl7_6dcNkVu39gX5HjLx6
Fr3TsdCaKG54jOO0sN6lBq3lYOYioggHE1ltCypzS3YzrQyXenHLFTNSsalKe5eH9KGWgEh1wdRxNBLc0WYPLVLaSolFMWFNIAYhtkiHs0yJKAoxDJ_GddCM
NhZNaz1RZBinFrU-1UDkp8-r5y-z7ehUuwkVRs_CZqPzzr6FntElXhFjVVNpxNtpy-NzqC-tzpS_tzvLFn_zNVF_0m
}

