sprite $image287 [269x187/16z] {
xTk7KZGv30JWovRQmyxxF-q5MAxOhjz3_mANi4nNldnVgQNPT7xH-7yvANi6_X8xl-FtV0_7pH-pTqCus9xYUpXyc8qjlZdWry6-5DPiMmwdjF_YpjbpB5vY
-t7uW6933loe8PSSjvt6WkFEsOt2x6euiCVUl0UzUzk9Oxmil3_dccEJXlJ_Orki3emfqDy4j3eevHj2aRjIdu8vlDXJXx_R40wgdbcxEgV3uB8hhG25q11r
TTWM3UbLpom254NFBEI6H5U75JYdrYdnrN5RTLdGOAZ1vUh0oik2LqRvrV77e242HwWhlwpP4A4h4GuiIC51nTMXKqnS7LZedBRfNV55noBE8NHb2OhwNOat
9CuXT6MHiPY_EcvhKanuGa-VZXQZgFY4Rh5bCVa9lI_GaD9F7QPHw8aEH_xgw493vdK596_kdFKQmh70M6Ht1G95C1wW4BgoobHme3SalIitOLbCN1rt2fK3
wuq5nuM6g1nhKUWSQ4BSEMliJRqhl2mIkf8m5iJ13OboB4Z1SO52vVXZLGhcu8OahmxXd4xiIaZUt3dhZGN717cL0taK-N7dBDeGJlvmt9OPY_chGwQeFnsc
KjHV7H2MHRtXq1jIYiF25Due5JXYoyAj5SI0TauhMg3ZaG8zqf3uu_1psbU8TxRelIitX1EQI3maURWCdId-Yx0iE7480IIBGi3m3rkOuogMqX2mXO3X7xPm
l1lFNnQlESvX-eSj358igI5CyVGaZ4NqfZh4UEOvlUSudeOO_c4B0_HOUaEU_iir1ITkaQzXbnJFoRBWMEgok4UWY9G4FvqsDKuK_h0iHXX-aS3krEEPo-8U
mMBIO72I6ZB2CEVCtnZpHqEZO0pdp6_9V0pl65jmP0gtoHX8QmXZmDzDMmL3f-2GHIKCIEUKCLo9DJq89UESCePhiMKcGsy8nrnCcutXCobmJN4FT8p9FR7v
vvIN1GU0Y35xD5AM1ME876toQ5ZMic0CY1WJ7yWzvvmoXiWHwAsUxlEVlONqtZKEQpyN3rZCV2jBnEZIT5YalM8yxvmoXZWSiRt-VZfizbjPEeR8WU0NM0MA
n7FA62g7jK3ChyhIEopnd7BEhckqMEovl3-2W2UVKtx9shlAWHQEEG3wDxcrt7FA58HnpV7HYJOpVubPesISKxPWZ6iEj4d9NnOdOznBTdJIeD6OaFHbGHXl
F5yryCL7mp-n8MECOLVWTHionXXnmBuiHRGX0iPGeqr8sZazJWLZo04KM1P48M0CEE1rbeM68MYiVavlfunnnT6zpZdLCPWZNyCcK6WOOuxkPSwfZZ7MGCuv
zGatHCKOSm1MO5b4CPW3tGkSqoW6luUEZkNEwN76CBJXMEBPcvyiuXWS6WuhS4xZ6CpXQoyB3WOOeiPK3lkijxBqw1ZpEPXY_bXmCC2GEM1BKt088vt3qJ7X
sLlC24Cyi-ZTxHE7WYYcZmL7mnW_eVVFyJ0dYGaKIkx_hawHESWZE1CTdaJ16iVJSVOUvBXx8FvvVGSD1PtJ-HQSeCOZ28a83jIE2I_Kvsem1wz--3iaPkxe
197PaBY6CmU1t4dkiszlukvl_ooSCk6SpjPexPM3DDW4muboIi9OA94mMWCDHo1v57eqZ6R4KOI2es5GLy8SSz_Aci_HNkEaKMGiE1e6TwKEXQv1xyv5EVBF
gHu1GrWTmR78f-1e67ncgpI4SsWOl3ggK704Z0zt9NrPwD4m-CoYo5Xm8604LqVyXNfU18pOwW1Mc0gEW26iZWMUlQL0m-3LKQKX7126s9MrzgOUmWXmJFZU
ObfkXA6kZYfZmT4m-CnMeU0GXjgLMQzEypdGb1XrfSnOC8St9KuSPIYuAnuOZYeK7F6R6VJnM-OvpLyTzDbHnR7Gkz8VDOfHC8V965MdGbyTJ76Kek0SrwkZ
_5ZeguCnYb8mXqaOLIbO0oPWbBRWhiGncA8a1-tFiXIS6tL5mAX6mQiZYi4MzRh26FKfk2lT18p25Fn8QW96TGjU7Jh6SLBAhGuTuwmOVYHbZAt6WZaKZ9DI
jolsBiQvIOvEEOGtU-i6ZC4KU-K2upYtop72EBSCOH35XXoCSMuSF6ASk-SPuvk2VbLzKlOC-l5rp-a_
}

