sprite $image89 [236x172/16z] {
vTZNWkig38NXu2O9NVZzd_PKPvUL0cHvUn3ptqqDdor8sRyW-QVzMoH7tqSwFbP-RsmgDhOK6rgAZKt5nfPYOqkneQNOs5HiR2asjXGRMeh5fewl5QAWql6n
GZUs51jRYWqjnSQcOcDBiR6bsD1KR6mfDhOK6rkA3Kt5nfPYOqkn7gNhxUFwnCeViPeIsakblDLL2dMsKJVEsfLMIXqBruOQhDA35AsUwmDh5rgfgRXm_a-w
aFBMFhJIarMkb5vlnIwGNckzNYjzMkLAwVLMx4hfzLRi0ka5rekrSgPrM-RqR_EoSLRiP2blNTBjPsdUA2l6Iq-qRka6pPmLuwXdMfVROucqOdzIkgPfgxIk
Fu5pIeWjMvUq45XQkaquYBXmms_TVtszQ-TdVu8TlvzMGaj9PRxVcxN2EXtVMkJeZjqghDlzhzD6Q9dnlVqeRKNhmynkntUcidM6uwpOILAyJqVJ2oiUJElZ
VoXQuVXUJiHANNYiBa-j04loU5Yj9Ui6r_MqRIkrgSsuX3VMz6G2xrDPieffWYdQpj1AGwOJQBUNrcStFxsnGhRYgn0QAutPXaj0AxnYIh_sutjbgwZ1dY6V
RQKzjHMqoxE5mozXJwsOAh5jQUgXVLZ2MLRC1BUjLDGaJOMc6pHjX7MQtZpIT2EtBKgnMtlpnzPov22Bq5QiR9MZcR2slsoKeDRsbuqY5rinshfe7LOakdLI
TnCYqhfUPnLtLwdAL4gbgT0Dcim_jxOzr9ghRwgvMLbh_gw75s_YdYkiwz7qkrNzTPeUBgfdbPeqkvkLjVgk1Gd_ydyilFqSLjCN2RwlqYRfOKLiVIk-ZpPt
KwcnpaS9hVAy-Ub5XTuEfXcXtK0w7LUwO8Mgh0jUr5mjrUntw-VQ-SMHUBvrupOgMDkroviZyMJhXASVI2lFLViKEp-_qlNMTAzeJSJpZ8FrC-sQ7e_45kjw
_py5AupGt3w-Q6tNggrm97BMzDggDiFfLob5AwODsWMFH6A_WlNfntYRDuylMZyUPDK9DkffLioaPQEgFycCquBqH2kccHZVmqfgdwyjyTR7LDl65pCQAvTP
2IbQCOrerUnrLanvA_4ddBHinJIKrTm9gsaSgteXAwOnh9gTi8AsQwkQbxEgj7ChI2chQSzMpSvPCUt9YbBQYccNLlFgh27LVgmevQsONc3DJUDBMtbjkdsQ
PaBAMZ7jn6hUchMdFLWrEslbjRoLa19MGcl-QPaONy9AQDMikyjet9gkJxCJLaBRjnJRBPBMdA7kkuNHgdFKVuk1rSnAesZLM6aOhJb7ZOFbnpUAbfU6qHeh
3QDLvwXniFpuHj7oqZ1QSuvw0TQqcviQuzRoqZ1QOwL1jFn6lHwh0SRtF6q7qfwrnag3QFcR6WVBIyDeZPM6qPgJr2XQVdp3O7bf6AsnqZ1QTOxQATRqWl7j
zTQgiT8mMdEI6aNBZsy8h0QIybenLXf7or93QIbfC2mZZQObfE6q13MSbf26mnBIS5g26avBICDX2MauBI4DfoMeuRI4D1oMa8RJ4jHesXnOYj7MFL2STGyM
OTtZzQ5r3zadrZripTOzSatMFNhLrds0wgpx85LOzt4gMFUn0Yj81yPca8wipK0TMPj1Eh8sWtHaR0RgoDeCqe6p_2NIlm4
}

