sprite $image54 [260x168/16z] {
xDQ7SO1034HHP_FtPdJzL-iSv9onOFLA-ACzc6i3q7IsS6VQ8fcMHARpQITumN46tXN4Mxe0oBT0vfF0znRud67mM-Xx2tn95xZM1G23Zu5JXG3mhi0FTG5W
kBu4cNmBP9kVWUqjBFooc1iZyViwmRKk0CZe8NZR-OQ-1hwdm2fcOOF4SX31YkhEmBk20EyA_0zr0g3I3Bmha7WE8YX0jWMo0ZEmhI1AKO42VXKegGjSAp03
aq44nVaUGTO5hdM1FtmMs9HmFO9CAnGmgn00tXNOi1FR0jdlF0JU5HPsGROpoBh0TokSatWEWlsHN0jaYXzy3Tm64UpR3twAV6v1EEW47rGOmiJoTeCX-mhZ
L4Du3-AoN3D1bXm7WQX84B8WVzVzJpkRNTKBu-YeMR_bFCABu4baaD9kJo6bDHbvQme9qzOmC-As41AmZjOixaiX0S2wjEQt7OY4PaAxtKmByGC31e2khUcT
jF3bsra8KjtrqC8D1o81zDJ9JM-hXOH6XqnoYA1RQzZoPaj4okw3oM6vGM-dXTztPz4apM7UoIdGZdQhxtCyGj2J5Zb4aodkw2PDRgI5216uQv0RC099XtQz
aHQ2wT846CdDfqAIL40xRgA5uCT7PbXhWCVcvDOig2Cxx1PQYFpuBO_CdDeQe4uI3jV1x08pMVtxdFpuFN_KQJcaYQgJOFJcv53lJor4h3i6JmQFBvcx5do0
f47dCAOjhON8ZsUEt-Ak1G4cQNC3b0mvjkg-ta14ykELnv6N5cPOCBkC34IezgA5HSQWCdXf0S0aDpCCIIQ0eeKb25G6XnQYjoQgavjpearIkwlrLhRg9KHG
6Roq07LtCe4UEZZLcnGjh222ok2WiA4rm9AfwP113czOf6oBGg0m-FQt4A5a01k7Dn7qqi4lG61dK1A75g18qbpDlOaFBHty0cDmCAXXvhHz8FQjsfjid1Sl
sog1og1gGT3TWjp-OC21euFVCcEDCJXdyEtt6PwStWGRX-KiPTi5tyFAu3Ix5g2UcpSPQjt8AS1J2zSNmJc3ydtMtkGesqAs0UkbRBlc65G6vrhm9i-oJSW1
BHtyEWHg3YqqyUJcOMWa5KKBbnD1HN2UF7uBpx9DBAXRATkkAO8FFchEjT04S38nq7KZkqWfszORWwe5TQOok_JaqE552zSYm3SGx5krjoRehj-KRVtGGcHS
Rmm-7kycNcNRjfTjOcGsXNvEBVmz4TJKicqoktYcHAAKROk9e6xL-5gszRriKv5FLhP5_cCYgDaomvzbM-TKcQJwKErQjkf5H533PzdM-rwssLws7R-5p5Xp
3AeMq9h0ufkoJG0hPTjd9F3byJTIEtZDq6JeSwlkQALiMsiCwbOj09BihjgDd5QswWNUm_FaKRQf9VlC3GYcGTIib6shZK7ju7lNIMw0Xq4KfOF_B0JoKVBF
QG4zENiO339oG4i7Vu4D-RtK3buzjavEWmnoQwB_jHQI_ps1kbKRIODOSc9pzAA5o_q8tjS2_0y6m9XWbiks5SUWbcrmDyWs5I0JMigs5Tx3d_yMVcUmNxOb
8ZkiQ66PCQZXhWKL6MIgmoMO9cBbuFMp5KN_l1O4Ww6CtaRI--ZFiYtY2XjopVjbcpJHteqaLASxerosNMarU3-lopQTfEO6yVqClbosBII2yx8j0iaqyPnW
kMoxnchmzx_FakHmWuDCAPTj2uv1_Ise1iSuoZPi0zQnT_1nrO_n-rg0THja03qGdC-3ryXOKmJdbsrXwMX1EifMlS1x-7CjgCMquxBDFRUoLIybWlFBDYLf
GysSt1hALhtU6DGE_dNPPiS9IzTMVWkh4QYNRLs37FjMJLThxT32VtT8y0b-2oCvHXX0qlvWyAuMhYA2yyisZ1XZtwfV38eM5Xk3si43WmmTy1U3Skhv3pN6
drWBSCP-jT5UGMPcB2U2cYzFBNGtalqR1fA_9sAzCJY_RCCalJ38ZFK8rCJN4vPU6HmKtlyOnwFa4bhGmc1FNFPZ_FvMRISCCcAvCQZXheLM6Ho9PTx3dvTj
bS4piUeOL2rK1g_4eWJgmUivWumrHL2N23jda5oLGDN2EODr4TIj-ep1oWJgRm7lCNYibioC-HQ3nuB9Fm_F2To60iy8t8W2JmZS2G9F4Do90cz7e59W8N2B
n2c3nurI61G2jwB0Gk1-55W8t2dRLmPyt3PF1ezR9vF_0u5V0G
}

