sprite $image185 [229x181/16z] {
xTk7ZkCw3mLWKiqIwNd_n_rBhf4B9ajaV3PMJ2C7TNi-yAZOiqFpaahhuvRUQg8B9jK-R5g-6h6DFwHVYbc6aqfN2RVXPc6wH58VmqzF5wsgJQ7mQUDbshMg
AgAtY02LZL1LkU7a7wke6cU-nAwwgIpQd2Nngog6Q7uoz5bInxynGtEKFGUlgWmdeIkRks_qXzauUbLzPSYpX1V7u2a3Nd-o8t2Z6ktwmqvLhrJPv5JrIfKj
Pep6kAUo7ESUD_R4NdzIdCCHL_OIuN0qHgYo0Gz7P9UDTpZ6tsMvxJWSW-so_fCZ7ZrfPUlBgkALhMUyuoWciqezszldydTLZV36W9STEmvQsSPnxZZuBjlp
2SO86ACCCtTWnq6LlNo2cNQC4On-cCbj86F4XpcVoRK3OqIY3ypAyuWJnkZyzRsbsV_50HyZpXmj1IBYp2LFs57d4UqN_YQy7ic6Y2z6d7dqLikb0rCybbdv
e0tL_dlpcOVjGSaXpe-8oY5xK6e388PQd7a1YB4MP-a0CTJYv0figBFYBCuuIn5Vd86M8jxQcdOS_0un0BDbT2dAE6tawUCjhrkR6d3m1pfI_AKOZzaIS2g6
Ouub1peLyKVhNZZKgOXVX82b6BUr766A-7sltepEYvkmUNgxHqIFSuohyvNPCKREOndJulnovCWwJDemMMLSS9Jz0JakXhI9NrU_a2ANsNXyXIWmocZt0LK1
bC6CeWxxKdDKVLGPT_WRkkY6V6AAwdM8TwIg0ECC83J8w4pvKniD4d066A911cUACqG7wJ8bu11zfE-Cjn8j4c066A95Udd-2y8DqIA1SGOOea42p0X3j4Z0
6M285Wam8mpH8iCmvPce9ZWITyxlgOyCmGI6220_-d0D3156kgzAvcys419lhPopftOqUbucJhJfLO78f5kjgc0zjSaq58d8ySEK1wA2wKHfACW4XeaRHT4C
9gBK5OiSki-g6YASpdHB5PG9L1OOeoWSgNHFVOTIJsUqtqAR5Otig2ncL33Ic0X0JggiwXl6k10HXCGhEx-gpKVMDkPM5ZVYo49SnW6LdROSvLT8ekM0oavQ
ZajE0Y2Xodx8k5OY1f1ePUSln_L_AG1oWj8r0aG0ERcorYY0443E7YPkN5SCEKM9RpbME1sfOiO16W4YY9ouCEtK0U84951PtoY0445cdQkqHfouAlyUILM1
m9KL7R3Hfj0E95MPDqorHXmfcNOXYPSvIcjKnP7Qc7OYYN9N9z1PWc-hrkOXUoBQZoGgSiJ2nBUSTNMH8nDXIE8c1rGMDAwhYzHA12E9qk9zUi4UfItHCJf4
3xam_Gx9kYKzweVpqKNtCyKZ3db1z94Z4Rr2sWKeXPwoF7ziJ3b4d5yOByRe8yq7VeaaBgqLfkSq---fxDlmPJY1Z1Pf80xIYuzSVtv-LZ6ZH9b0LH-GsXEz
5obtvC-w1scLkD4YxR5XC_IVvFt8fOfko1_TYLJ1ZHvIAZb9DwLKsf7jjbw9cnsb02ScRhH8RKn-Sgs5QLyMKLcshzRUaIAwAm8OZSuW2xq_J5koh3UaoExB
WGWmHW-PwT1KNNzMy79WdIAwmpWLIVoNbuCjmDCKWCIJEt0vi4698my0YQKCu7806yqTRXwIkA6N0zoeZMb3IgOfIOiYbmCSsTEzHD9eLl80BWS8qjxXE6Mc
YIco8NSG8QHM-c3QJRdk82B8XUcZINqxl8v3ZaGVJnxlr3qXfT0fKkLjnaUaDZfBkBtBQ96w93fHKdyBqI979fluItCrI60n1bYQgqLgOpfbU57SQ94zaPF0
ItCrI2bqwXJ1Z1QPwEJf034SiW76W4ZSA4qkYRIF_XmAkRJTnfw8DYJJoPE6gev4t7SH9T_VRen2vqyk-LStlJy_-ZDJh1JvtPQwC0KEjzT6u0uNuARdFFg7
JXxg8xKoNIDLF2Jsw1_W8Gnuz8-vD8756Eyu0Tx31KaTUi_2TDKatTBemf4lCdg-oFZv8kFdYxnCliWlyeiCydfT4bqvPQXgdsxyBm
}

sprite $image185 [115x91/16z] {
xTM9agCm30HG-RPRulz_Tuj0HKE5Y8q7fQxflSzNtM279X9AwsECNXDzAMLWF8BHluA6Xl4ZnLzCuo0ErE0zAXuEzgm_xz5_r8twyPFiFUhkxEWshfTOeSsE
A5hm06FNYg_cIFUBUPoAEcwv6Gmwwecfu_gDwZzk6SCIzS-Ams7K6ECwl3T-u-fxew9jtdBdfjFtnXwt9vUAzbjKuonOXl7Uc4KDr0IxKV4QRMcceL7H2ARG
M2V1OrFq73u2eU0iEj3BVw2f6I_D17hv9kKE0vn4Mx9VKWESGCs7Qhyp7WyrDUETkUkX-Zn2-wHcun4weVk-UHYWmxwPyYOfw1RUxTJrrwxHLhiuCFo3uu_0
rrg2Xs6wY61-_XIUe7PSuutgdGRmCu3-cND13RIgUq6Del0kQEphKD2gwb3GeQfHq1TLq32iVUzV54RL2VIweA1Sxlk9QO8xcSamsJ3dG14kH1Jw5GhW0z5g
Y1feJPLRYWANcnRQquHbL5mK_PqeZrhf9zae_sfSi3rgBozafoINuqu_Hf581caLdHfLriHWa1FZMgB816cFQuiY5XdOCArnjp-mF5cONib6b31XMY-EYaZd
98MgHIqJrwEACFXPiHBHsR1hOXSJXJAMk4BQiWTw8Qk8LDgIne__7k-B0WE0YaTGoMNip96aqihpvv4VaSTjOXJTmJDHoOKBqO4yIsA0XMLPJRmrDQ-ZAba3
FGCHZgTaPEcnooBozWApHINxGOYr9ZfFoe4eOLc0lHPEYngZRYG2VPQo7nYSxeijnjd7voI5jg8YqFKkeg2qD47kfrGMEQjfYoCHDJIQISQo25IqiuF8sqeq
cIhBVuBWRTDAlqre8jUUCBQMFT8DIUCItVw2B4XqKp9iSpk6meNkIwZCi4HXS0jqQ-9uQyfEPhevbS7o3bmmF4ZXZXDp_zXlSZyPQjtkm4EU7_kXPF99xAAe
tcw-oKCEcnRwGWhBJYxI0dqZpqSgFTBN4jjAPlfceZ0Z_97J-IFvkoHrvagJ-GS
}

