sprite $image12 [236x176/16z] {
vTs9SgCu58LXG0BfBbNz_cyxdiwXlBH5BiUg48f_zbvI_eB4eiYPFx7u9DgVyoPq5r2UJ2ozEwcJxvnElgiuqMMWw2fGT1KekWWKNGMAhY955v6YYq3HHQJe
8b9q4Icw21Lrb9PCL4-cbQ_oG5HaRxKGzSBAHrQLQ7q-fHsax8iGrn-p8bvw3gkuVegLirbvhPpLAeJqN5OUAwUpqjgzBoAzJzqEiWf1ZLhLttQGDOwbNaJk
OwsblllHYPWgD5MMuRjcwPBvFrNkjC1IfGpVDXRfaBvM9_OKI51X3JHLYLGaNasn-KfWXRMY791Emx0Gvoh2AW4gR_sUaRv6G950opWGrXXMujQ9cxRpi9Pg
P03mLjJ3kdXpUBKPPTmntdEVsxCDQjpgcjhJDdIQ6PV807Xjb1IpeZOrRZMrEZPVq18wJbDf3e1MnJrgHMrgt2gYjWojfX8wpUHzrvdithJ6iK9OHTGsfgtS
gsFyVYj_Szjj-SUjZdiwcOPMIsm2bjXrPgp-VoeDQnWhh5NKQkZGMbkRwfOKBP1Amnh62c_TdBRZ8zPI-zZcKafEGxDiU6mwqWf63c35P1oe9lahLI6jyaBb
hM04iEeBGothyAMjqiiAHWcSPt7YtjMyIhjOvJChqiRPHvupJNkaIJ5HMIlgQ0LZUdjQaQSQzrlRrvbULebKoZCBrfVUZb1NGOqJT-0wyx5LO0sb_fAywzq0
hIwlgUMerEIrakVbCNEBMjcL87bRVVUQLVx9R0wCteR2cELAMEbugwXvpIteh8uhwjlKdjDZh6_6iBY9lDUwBA-_OShLl2tbwqXjhrexh0skkyZoLH5rxmz5
VQrlnsI6TOkB2EX1riQ5HDrLjbErMswtLENUFFzEQvdQjtX2LKOyt7Qg6pKDxvlSNOMefiQgvD7bOODg7tx4BB-ePTnS2_ly8oxoIwhJzeEdTfZwK_cjmnSb
uuvgQgn97TtIb8xYjwpVvoxBiGMM_VPLDZwY75kPjhPFMCUfF-FZ7LDxHJy9f3sd_f7MzXf3POTlO2NcS6tkC56b45F_W4pIo_fyXnDwuoCUdbfzlCwea4UL
cFf7JLkiptUyUFMTg2gTCllWTMLYeXvZHSOFjl4dhZDgqYzLMIjBJjCqt9gcASzb_sojtHTZrALx9Kzlhf5fsJM4Q__hZ7blQ1gQWHkoOlZsZFhSyRlgnZbg
5L2xMYr2c9vR62bQOZSIaqldrDs9cvhSbdBxZ7Tiq5tODoYQkolprLUDFex5rXXI_E5yOj-WwBUCiHgpKxBDg8sTVW5hDGqFOVVFhKkGs6RCuPtc4_ac8DpM
VMWjuq0qbT1QUkvbzRyPRSNwF5aAOOUvYrNzAoMiWOcQgz-oCiQcRGwSk7ch8wEjo-P6txKQcxObSE9chUfhobdBzDs-3bCHKRCbzZwNm4vpqkg-PfGrVRTJ
KaFxBkMUritbOTwgVa_tMdrpHpwaaGsBivl6DYnEXRVwOtkjCWPtIcvlM4ps-cjLyyQq9QtcZzakQyxjuTiU9sfpO028RK_RjD-g_fm6hDHEoSTCKs0vQViD
8dc_rLyZhCJwF1YlN_8XDYp6hUQl6M4bbltKbyYwhrhkPLN_DoMipFgyQWuC036P-bZzNVg1TH98-progDSULlEt4LPkVLxDBVJBPjhQfYBIEaFQFxFqcLMz
bL7MlFpVd5ygVRGoibPGurXOYNAdxrGbwHkh4LHWUrbd-w7la6845TXUriNjE2ke1FQKLlL0XraBQQMeI4zcvQX8Jsyr3wSdj_gUJ1uhqvHsLm-pgkzC-T-E
Zh8Q_qfvgqgWxfzIw_0nY0wmgfFfpsEPFZoeo5JEbFf7sOcavjlz2GpaSmGfOJtRG5P7j1NPoQMWmafeJoI55TWJQzMyenMPdbGAAgndrQh7-mDiF3sJbBSY
EzlW1PMmOYYVwP322kovk6fEKM4z2nTGpWhiARY0ybHOJy05bBVoMDxBEtbg3omoq-ESl9MllrVXx43jZCK1rgxC_bHW3nT32UOnLfwikun0TgPoM5vzIz6N
31a3vAd8JnHlHTUWecjGqIMew3hK_bWJyOr4x0WgZwtfLdMKqwtr9_3ziLUGfblgNsaUrtSiVPMUgrsedRNw-Fz5ilMRhBcEhvipNOPRED3pwniSV7XkwK3j
Z_sByg_A-awEEZmslLgduJ4Zh3oLn-8GLRyR30VxLiBHpSzMx50R4puLl9Md8deGOmZ3F5Ptntxd-cYjs9pfZlSULLWduYlaD1MnWnX369Z7SJq-MiTrfA_k
16jo8bgAo46SC8Jpmx36ZzQxjJwmy6i9QmygeWRnEeHn9575_8FrQOBZwmYSbQVos7N4LenD0Hw10IkEyziFCYvhqaNQNuiXYtyQK0jXlRVqeFR7udZEzo7y
Qft-jIR2IaZxQp4_COIFEgwWykqOn8eX3DGSjHBdfkvI51_4wn36O7xvsTPvkE17AIjFvRN3MhdVAahi-fguwsj_AGeCOcJtOpKz7jR1LojOEB2uFf5MNifZ
uRdxnlkR9nUSQ-xMXn_osheVrbxI_jgNxw0XeAV79nbOxuzqAOtDvvpKIzgVcn-7S8_drzHBsbzRLzCxRF9dAyv8Q38dh8Iqc_RVHQ9bVKwNT-jDaY5jh3VD
XqhHtgrGtcphPu-78ZykNift5IYw2XHT1Oek0qNdTFATqybtKYVVMPbyvrNo_IRZVm
}

