sprite $image70 [220x159/16z] {
t9jjakCg34KDnXW9IFQ_svbKkojDhYah2b4vEN_Ucy_u65si2C_L3gR_NByHfX_u-zJephUPjLo-p-pxrYuGy2rsr2D_mUxOv_FNx2lj4gYitaLgu2zPj1Ic
__YL6huYQCkqCQUFjijOZcwwir3BPvVZF3KynYvzK3bYq5emTloPGOjksYE0t0Vk-s3rcR7Zew2rVD3JZe0m7U0JDNnoq92GJhzqpBAW8Mw1mlpOe1q_3zBf
6omvs8Q5ivWbHT20G2rdRR0mQCu_BjHXxEYStsI0M1vhD9CNnExy-txWMXw5kPRL7SRk76RzZTzJhPaVtL8kjInxgJk5tOLf1swNmwsb5YO2D-9SAhUncudn
xplF18jBpN-MOycrPA8Tjv_VM_x4pbEf-Gpp8cBQfLcEcMl9J1stpMvrpGBlm2UPEcuNdFoj3RvVBRhTxqHUVXUOJp3h8m3jrcOTqArPvuN1J61djMXOcCtL
ebjp9ogK8y96PXAxpUp0RRDZ4c1RZdBGJOE1cO6RjHsJZPkzN2AoSREtezTOqEqiTandSYCsCBDoGmpAqSmDCLWqAxSqpsbmOS97sBdXFXj6nkw27-5NidUB
RlYyQFy2vwHnStuEouqmU_USs-g77zjnzoC2FGsNKdyf9JyLD9WNjIZDy2EWDeJaMkxKMbcivWu7HkaLC-oPdeuTC__z_yoATODZEzLxVOAXuqmsS2c2CIrf
pTQTlpin6T3CYmR4hbSJE7IqOPiN7P-MisBV1vgPb8rThIo8dNGFwGUDLMOf1kzk-12JfZ1hUYbsB3XiIgfoZEtVvACkTXCGPB5ZoM6JpimTrrCwX3ZJh7f9
9GY25dH12uA3qdLIWhU91Vi-CCSObo0WmaqwblDwEOoTODzNW5UTfXvhSxGrwS7OCPX14Ic9WcM3rcPw1UnmLy6-hw4faNu9U5ZULu3slHEqaUiMJDpcHCZW
LSDRkCfkGPoqR4_T36OvvzQEyqkVWWkIUqNfCfIk2E5JbqkzoJ7ToQNcC39mdFs-6ZTktecOaB0rWT22rdo37tvM_xJ17P3BxhsQkRtLkGY0wzhU042pKd_S
mAxKajm4-4LAIErV1nNdrzAgaS0i1-6tBRwPtTtGBkv-kP6HeStbEBlVw_4BuHNn4TrlMxjchLjcRXULTs-J3AQ6l1rffvJWBBo7wDjMfnp1JHGxjv8ApjeP
Nd-iKMlfc84Rs4a65NAOUIiFVluiGBxlLt3Rj-iCAWBPiZZ1joqmGpUCtTxk5Ca0RT3GhH-xpdpG2YyRQu0PkBqdTciYFPoyF6ZeXd0dTheJ0JSv7vQufXjh
ZC_EWA8JD5XYDumTpssMCp_Zrk1816Q-ts0Tk04Cyq78iYuoJZbwxJTO0ZT1x23B1cvRXxi8zlsEcpHsMvODtC1153Hq4ySERfwD6t4M1WtTvB53CmEttbA-
uePsO6RlXcPwjun2zcvOZZetXC_b1cPwDxIpTyDorBiXFCfjUlaGTRXRPZw16vIZpWrXUpSinq5k2DkweTb0DuJDtJ1euztaiLlJ4sxhe2SQaXNmyLWgIDsY
c_mwg1pHRRJT0lEYljlgOK0nm0pS1XLcT3Wlci4Dtl888yeHtKRQ9G_pehxRuaHpGJ0JSxtexOx_QVVITujED1TalTcDh8PnrN1CYswzDpxr-pvIhXk32fFp
_ljaw1Oc86P6C_sYtRaCiEkFQH-5UmF-SUNOajNW-O48FDWTPeQmtWvdYN9WxZWYQCYmmeJO0V0QxSYW3RR3qt8XCzV1vVXcEt7iy61tlDduJQKMEeoTWndr
m79yT-mSw1mTx0usGouMiPkf5eEW3NuUu4igY4i6-_uROYTuDqmJDBqPyhusBB1nEI8yx7aGtzTWNQvAojWcSto39N2mUDfvomRBFdPM3PQSowZO5If63PPz
OHesMFQ5QT1W6HKcsbcLe_tJRjI-dw_02M9d63Jxs6tyAyO-2000GXY86JZ_Ub51AY6C_W3ZQ7LIvdNoWkNNJYwQNpicywTTJEPR5tXOhtGncTV57jPU5skQ
ryLa7XTBHw-BoRmkHlEucCphOZAlYydyfqFptF_xOe_9_636nj7hOatpkfZCusBZw7KncVzqY8sZRrrCvdMnSVIwcCphOZH_oOmjcczTh6TU5vFvmOpHl2uc
yuCPatbTZEPrqTm_
}

