sprite $image385 [295x218/16z] {
x9g7aYGX28PDAD0NtlzfBz53wVMswtXHnczJzrJ-2duftCz_7Vf6-TnbmoHi4nqEKdZRk8E4dgWDNS0jvIwKMhQN1YIbBsgNKb_KXdh85BL1UfzjYSROaiRW
BMcCzDgXL2Biphk518pEkL2sg6w_WHCYRb6tah9tIg8nFhsAf5JrMuNFkw0gc8Jab73-ANiuEE5hlqMKDtaS0b-ZtqfmWXOHE05eTnvVGac8g1y2ZMB-V7DA
WiU3b5YYPp0igGvlNuWmLUSSqdCOjbHtdI-QKn5f0ZQzdXGtQYVxK4vzyZ0Ai_bD0FZBz9sUB2jcDh_ehbEfdQJAg2H3cZxHFHYQO-ua00o8Oi7yvaqhoEUR
IQe3Fx3SRpK0CeAVH4Z-_TPZKvfeZEpRPOey-vuanRoawt0GiDdK8GcGyDOI6vNKZwWwoWCHGP5tC5fDz2m0EfuBKUG57HeCPXFJ7D1iChDJV35uqXrpcaeJ
vI9D09Dpqt7CYSfUern3IZ-uO47JmLEYalHR5LAT8Sg0fbbHc2yX1Vvs95zTay0qIHo_lEFbDSsB-ZcJCgIKe1Yxtpo4-OY2kfPAT0z2fhTONDEygEBLKt8r
0Us8Ebhc2ihBcHSqfY1sDWUylARfAQgzh8B76W-jHDJHC1zHsd8XocoGkgVVYffIuTyXIge99Qoa0IFTifwcu2B-XiwJRAesdF92YEkB4atE9VhrWiBmk4R0
im7FNaouU4If9XVuDqGKE25X2J8HPD_xhuprD7dctz1vcBJTCjJxJQItMKyJkKY_8Q8An6y0Dgi3xto0hypSwNRSEWu4O6uYYO9yt_zjPp6EqyM8aj7oc2FS
DV_Its4XuD9-xvMOj6U6Ja881Sxa0Ru4ScMPrlcXwcEPGcpgWSAkWFEgAiJubSFgX8A8rPEOyYUJYdqOnRV9m_xnyKqco_0CiQMGhQjxzY__W0aVmuGQcQb-
qwAW7_-fxvhNDbwpz5ukazTFBp7meDFBmamXRESj2hf_6DDbyx86ll7ss2hLwsdpYVELCPMksZTc2h5DeInln7G9rJfT5bF5tCwITqBu2APeam0pXI1wJ9xb
pSezDl1W45EYNSmxzGWcYzasChLH2h2y4PCFgWmNdptUSy8Zc49MLSdCbCSMfOmqCYdW60mIRP13ahVh4Kn9qLLxOgOGculf78gRqiOtCLbkr2EO91HH1JE5
aE5ZKiLbtZutnBKMllJifJyyUNCcQr6DcI8KFYPLd3RlJM8OgeeP5dcpoYEOGkpMee9eCYR42X-J0jFKbJuyMR5Pl4QQFn-UFDxJyMQbfo-c18IGsWaJ752r
_VqSgbBFYhM_fglsK2XZmZOmrIAA2c8A8SkKAMruusQcRQLihTkf55NSlXnpVsYBqi-Ip4p1OiPCeKoPeethGm5ldx349jBUcQU0vKnMlMYtvgerMCmaEvX2
I5tVWJ8Fqyab6OtKAjroM1_PelHLp6IRbHOTJ251tqXUZtp28YtbBdR48ZLQwfu7nKme8rE3ecOF4zvgKPkrxiFKaBlqfmu7K2h9p9HYXK8TJ3ACwvuZbZ9z
w_haiHmirI8nMTz1TZ25aEKSol-rXQT2AKJO2M0ckqDeqS4KGdl_sKPFu_U3UklFF3bGXOnGsfWfGQ7OJfWACrK5teBgPSXRItncvw--Wid2CNp0dfW9gK6b
Jvcq9sQggRsJl3AS7LJQopmkUQepg1R7pKe_tTEXHc9whqMDtx3EPXHl7BD0bp0TauUDcK8eShhrHLFXYUkzuS2-OPsthzMKfDdC-WxI_h68wGYb0rFOfanM
8rEGjr-MbS-WMGOtARxrn9U6wvZcBUfw2kUGCbFfxq5PzhevbPullybul3HSnSHGIbLZI107as9ZfXIAk9B74sRwcZIBj1IAEs-BcUOjAa7EGyU5Gao75WN7
vSic4Ysz8isTj-LCSoXrCLdLSU9wOnwlXvShlHRxke83QJtJiKKXkPbwd39175M6W_AQNcZzj2cjPUguNb0rEfaKsv49ugk-6Ksij8SvtUtf_h6QAQMkrr35
nmIev94947_rLbiNwQ_JtyskT_eaR-kPR7oyIfvq3zEMkch7YmcG6vLvgzVuZfYHrZFPS7WDvM8oRyt6f91R5QqdVKxZpNxLnY7W_ySKeTV96vds4wOGAnJb
HqoPnoWw8QUbj9e9BoR9SWd5J0h1d2a4g5tLGFKMbEKi31TLdP3MCq6OQVgG5pWoxR1Re7CcrLPePBhbbBVjwzgpq10mg_sNbGJZIzvOvr3CjAk8G4T2Pd9i
vxmFnpQfqPHe25Yxc4I4cMZSFYIFcHIVQt_Cv3dJpUIrrq_-snhbRJKJv0zJZGDJbnEetV9cQtyal6AwtQ9AJhbK8QJbJ28l9aLXfXgsUV9sQqgsgcRDgqLY
SYRFVroodac4cRggP6QQjoZTBM_3t3H2eKoPxaDHKrhE11cPOXPL8IRUk7BoUEsVZ0sIYUcdoQEyBMVgOaLCTZg4EBxaFKBn07mwNpNeIG5tyxQUIMJ2P8zH
fGnCvT2Y3CdgVBxYahjGl3DPpoHomXII7NyF3vvZWsjFTmuLozzGD_AscgdZYacAgBOslEJDtSV4oUEA8LRSX3AazKmYSibaBMfW2X5EfZcKdHRTIPurfVLC
aE-Ph4NbCBpahV0mpPDdcpD_Bn-7WFLC4F4mXL2jHV7bU6mEfXVKWQbeByxaSTxMCtMH2wPjtDE9gDOuN8vdcJDLN2IFcPmjYf7MCubSCgdaSRDIeS1uELwd
J36s6HHmO3e-PGKSGy129f5h9fi4c2ca1jNYUF1yzf0N69ccxyG0nr9Qn2JYOLBqyILlXcfBtp8Px7do2ZDLxQV9OwJrJF-8Xsd-hWIA6dqFdd4ArJCpbKD8
SHm2rZE9lC6aaWUcNA6ewc32_Bi6K1NL5ebftgAuAQrdWZXgV2MNY2dPHt8moVoL75J31iwpPH0pAClRUgOkpXelmXinsQTlqS54dvuhs2GWp1Hc4JMazKpo
Hk7wNGas3rEeKoQBMKy3Ksuw5AmfBMU2KBsPF4a34vggb6tArDF0rFg4oOYrHMAAXnRryQDQWdHiKP6PxBi6CoP-K6VDFykKIJOejlQ7YKBwOwOTWbyO0bmj
QcCcUnamPrAKF8mIstHFP_l2WMdS4Tz6KeZelc0fJQ44usQbdMzzCJ25A4UcHYsAcD1-mCINXkY_qBbzoTCSl2zvaSR1L6PC8NHLr4XCyWhftRpPdv0GMR2I
vb2eqScag96PKf4lQcPgAb0KOdg5z2wI_QOW8h9cASrRbFSbhnHcUhMedfYff0OLPQOG-oqclZGq9f4LIsa-76pkbxozCvFrR5jen1GiPicOQDwwdJTc4bsq
bevGFt_mZ4vCDWcW_e29NZ8Ga_j7OXNvdzNWLAEN2Tk1oOgPRBE2SfzfLpeh9oPlykHte52SJAgIfqpQui2KksglnBI_FmHmGQYm4cfiKTd5r3v78sAYgina
BOgPRZQbaScVFFmI53nCcuthBwPnJVPX2j-Ws8ZfJbCQcPwGF1SJ__GrUyaBfM8c6yMa49DtP_9noiHGIrVK6PDYocGyAjd-U_YANXmsA_8PKcBoDwKvqoDQ
r3wkVUZ5IzwM4YONmTYOgOSY2iwpFszSknng_OB2tqox7WWFJ8eslmYM4ed9GkfWsjLs9dwczIrgP5BCCibCrqymkZ9JY49ChhpvcR0OwiMqOqPunNHiKHg9
YSved4E0dqa4wrlKFY9P0PTCy-HXSpDnK_8pSTqxoBo_eFPTSTcyK8ZfEdcI7Kmy1Dnd4YnE7huT6oGRamEgRnuc_NSxPu8aDmX3qV7E26gu_scpk5pvfXUY
Cj7FqArtX5VMRq4BeTwKclYYz9n7w0jDjOWgDEdhJQ-9tnpesuRIKZsYPcYgN4zgDFKcgcJv_5j4GLFbUh954_XkbGU6ZqNgbRSDqAHe0XIQcY9A-1_KCIUs
LTyouh1I2QL6JI0ecWE-A5m5r28Acb1l22Mrfbuh3vf4wX5LAa4e6MXIU2ABWgOmhFM8IifGQjSaMGEryg3fyPIS23Ifce1sJLa1FwAW2GDrZo8gQPg0TasI
zGX5LAdfyPmO8YeLeMIZIRII-A8-fqBJyZYYojVMLfg-iWP-vHtjuqdJ_2oY4fe08qqXNq4udXQ9iYx59E_yCA9GRoQQ95-5ecaVv1LeUdOB34aMcYIt80HD
nvReiTGKfFI4UhFGDET629gECOrjE6iQfX0B8EaAqNfZRp3MXCEAB2TDzn7L82a9OKysHLFO7yT-GXFQg5PDAP9sFukzfkquh2p_VE0vYhKaGD1qpCklmrdJ
QVyOeTxQeMZQRtDbEMl2MuC6ISnTwqQQmbXeMlVt-z24_MCNtnVmD_UBXQPzOXoQvcDDniVLILuGkPyIY3Q7EbbEcX1H2atSKD9ZT8qfXQPzduZC5KsDzPRj
CT249teOKGqnXkco9bOeyKStPIqqOVyOD55_tzeHi-5oQ3gcvA0f4IHryK7T7LQ6RNS7JHs44cF4zU5X9OpGr1PAS-RpPIDAra9JsFUF1MWYr5idbJUVDVrv
TvS8Dm5zYGhJMTEnvYyrXPBa_ueOHHGqOGpCeEcc4OooVD5eQW-b_YDgqcXgRmBwZwXHfwajbFhleYGKcWYXr554AGQUkvC4n2gYQfe8eTHBH6q3D1bSJ_AP
hSul0Pe8zTPXvO7KOnF0VswTzFKMSmSOjUM9qNJtVtv9Z53gFw8IGaazFVc64PKO9vF-8oenwgt_M-24wqc2f6uZAb5E9lr75BFU-9N780F_e5h-VdDH-MLm
IJe2Mv8t1q3o2-AVaX9nIJgOajnJo2-FVqgKyulaTo5ulUdmUbFYafHOI79FStvR_5DI8Yv9XqwI8xf-qj5zIiwNJf8JTFNcY4wIevJaY2gKdAYxBd7a6zJR
Jm
}

