sprite $image35 [219x281/16z] {
xDe9Zjim34PXB5aTAhd_RHkCsZwqHC2fx4G_MRyB61_ebV3ZlLs_MdvswptITxrShbTlworvNPVUBvoZsREKhdDt1RPykFDNs5xGUhTqC73U1gsN1qRGiDqI
se1HFBPUIo0xzLxONjEQDkxmX14sJyC6hScFZBnjwRsWDNaP1MDpD73ACcyBQBgsms_PyIji0KtUzZG00yVOuejDrBQSpsTaq1XRVB5fsWvdQ3H0qxFzAJiS
3fxsBAAHa0nQbs4RevdE9-T6DDAHRKKZ3TbVj6uRlDP8XhRP7P8KP6vio5BJ5cXhtqRKR5TesDQyGv9DbdKQjl4tVvygpSiYcc-kpDc2h-niD6nhTYC-cohh
DcZW_dsZvPj9yxRXFQIKRLckqC0DRO-R62smnJj_UHesSC2yBARHD1asSBYGXRGcICFcYsKnxJwF5jkko0AQpDXkq7fhP9eqRE20ELaAMhU1GuSBsOkXXJIR
GNCsdvTHBEjDaSKsO5ucJiEs1B109aRhDWfWoEHfs2Y2nJBVVH8D7A5Q8wC9D6n1m929qsYDJ9H68Omi2Oq2Lo1JefdTNA7BooHfs9mFLYJJf7bRd3cP9WtS
g4oQPaCmVLflN2PBem4OCaqQZS3KQHIwz6NGV14BMIuQGGfaYMYq7WOjZwtfqzemJ9_MsW1CMWRjsG1Cd8QjZS7qQRq1c3oD8bSY6JOAM5bfX6cBJ8MsVOzP
xRH4CjffYMIqqnB9QASbab4z6UsqH3Ag9wDwD2ed8oideteogYUZUZAg9oEh9wDwCgedeu8mgYUZWZ2g9wDxGHWLX55165b15vLqKJMMpwoJR7dyh-tjxTbd
xkEV_jcYqHmQsOTWbF9WrhxJHsJqVXZTFqAZX2_mxRlPEqPcp_h_xjlJVb1V9qcln20CW8rDumdUk_zf_pdZoiZLLAArNChNhA91V_EUHAC9bqpf4ig5fRO-
T778r349s33PhEKgAeUqFjKxj5OAiTt3-8zLf4zmPwbbpcpJEdspiWp5PzPgvisUJFaRncDhPh5dxkp8Plw6pRsLnQ8YD5n6AUM-jwAhJGC2qpIdnBgtucW2
KVHenqM6qzQh1WMaZPIAxequFhPXmOvM4esz4KSvbDPJagqHLriD34BZHBgpuQjR0Et2cPIEdH6W3WKuMYKQ6oFE1nf9AvGtHhml38-RfaJYt53_3K9fbmUT
gACZm9D8cX1DS0HuOv4qfkmUKUHdQZWj4sChoAj_aJGb4cW5-d4MIHj45PXv1redQb4qZQKreXv5WsKu3ThHbwVLd2Usymuq1Mc0B9g63Rq3hPY5d4tZQHn4
GsNnj0dJHZsO-P0sz5IQv0F-Y11DXQyfHzSJhnP5kxJlPT-fyxohYQ4s1MY3dsYbYBuUxJz0atlQ9VqaMWsXVRPhB-YDuaeOXYLLbIwOXFtlzgZ4Zmo1etQm
CMGUVzDZMnsSvhM4SjsSj5gu6AtVGPDj6ldJQVkdRPWcJKGsQ1GFe55y1mrRZh1OQmcoHN-MXaaJPgivMj7Izvcq_JRGF3DPz5CNlx__9ArEcbYqqdK7qDBR
Q1xhSQa3hJ-Hjjy6sasm7ZTrtt-IXaaBM8-hLCP_cTQBCFzVMZYHjjy6MiHwNCT4bFucRUZBfBNM8_L_bAOtNNCzak9ljNxT7bhtTQmDDDzSZv9YzDme-2lI
iFCBooQDj11Zb8RCiroM5aMOMTXjqsAkAQCTD0RjE5jTZoKXjrwFb68C3PdG9Mb3Zqtatbn76cUQRybEelKFJ5fOqcOx2ZSlDSXEeQdjtxH-8LDDrV6_BZKH
kYZj-skz7ZNeI6jTQkBfMhJsUhp7H8sFQf2TGeDjntgiDIuroAvAg_kZL1wjYhc6xA8qh4TM67Gqhtsf1JgN1bjxFMBEH3PeFiRe6x9hqlffFKusze-lnq1N
fk7pHrmuehTbr-SVwr4LQzcvDDYQjBg1Y4R4dii39BeUgRIGyQLflRxXzdD_P05qjlNJZo1xYYR7qJ1fILWnNYOQJKwPrcFaXknKMZzyDsXUNOoD16Sk0bfT
ZyiWEvU6QMjl_R0L6f9S_THOLh9L5wFX-prrFO8p2-kHbdc-10s8hhNrYoC6J6-NZFLwz78fsh2zF-OyVbw8PQau4gd2b6AKbUpgD7m_d7FPvaOMRdB28ot5
XknK6XXzur8RRLGm8b9jumUr59koysb3ur8h_n5p_M4XYpPj8jvJJJnVdrP_o2iELnhRd6EQ9KfZyGtPwJIio3LDSANDR4pE4TKFQfvXW-nwj66JTfll8iIi
96SrDwr7PjXQClONeetZn8plzWiJAst2CJup3gn986BF9zFwxOQl7sEz-OhCvKeJ4PiZ9erpqwG9myQ1NqJhIzvt_MiQXYsQvqB2iinnqOqoZ_KusLv4woTQ
EeQ6aV1egz_hXz3ojFDpxRAqhotQZND2rbAXbVyTQDZv7yptvz0mRMjQnoLXPbnfM8oCdJ_yFHeUHwvXhkeMGenDvD8qj45BV8_KDXBTQjAkJXjMjDjCHb9s
nsaNuPIJ0sdXfRJRL4M66Qsa3vmIOvP5_YEqRa53ligMSPTfNXxkL1gc3RIQtw9XqkJFqI13aRKd9qt2uxJRMARTNjRtdNQxrz_yzgGbUJZlzz3YxNLDxnPt
gF_gF2sJBXVymrs41jcyhwzRPBh7vHVf-bzrEvlMQJCQAhysc8AmkdpwqlhRh_erBOBsIXjeQzoosy6q55vFmoQomlKhsK4qT0GDWmQlX_vGMWBjTJRGzlSy
3RsQ1jaLQDsh__tpQGTr0Lf_svtBfVjGyh2RhyYpQCzFMsToiXnsK_e9INT8lw5rUrEBgwEWmzJLXkwW7gTrJz3i3CEW7Ttm7bhco7r4rw6XPsXaN5sFLYej
2Z773YLXOZ-f8qRpeToFzKnv54EyZpcSGGjLGqOcMdAcH0ahTKmsHj6QnR4URsH3ywDjs27Jdg1rqpacOo9eoHf3NiWOfqF98_5YZV7ZkM8KncSP5izvo91P
zkePQPJ7KiRX_JGo5Y-twq1pE95W3EEe4UnM8p8cOcX6gKkOIngbqz4sxP4Dtq_G0awEZ80MwjR2Eax6-15FaazwCUgiuJB2KmNlh0iZJVqQdhQ3DZn1ImMY
TwcS7q3J2GOzojutZPH7GKSeuR4lJtAWA8eAI6PZo8wsuJHP9HRh4JHdZ8nnEJKnEITnjgTG7jLYyApxJahw3jCO6PUIroF7T4LgEsXfJ-LCT4Mcv8oaf3Hz
M1jFTThb96aOEHbTPAQYlaEPqyJCidjasdvQiaPIB2Y1qdBD9ytJo1arCev8tr1EcZW8QFo3Hbo3x3ssQL9i4kFcjBGkw6pvnIYaMFyEDFMM71PaIBEwOL-x
QReYdV45QI9kCJy-fkWP76DuCPBa8PkUH7XLrEpmZ36H0DbxR7YHhO5cl0luwp8EzzEFUgAYVuMHB4Ocbccg5wGhxzd6wOMmQTZVNXeRF83GuSMMyVmCpe-m
16SZZoT6PtHOdYenHSQ5wVDTL9arnWpFj9CMSCLCj6XrQo0BXUXvbY7DHzY2Z6FEp6poUAfcRQ4bAaSx0zaJyIvQiae2RRwZkvWqZ_DbR1XZWkdIh8_6qFsf
b8aqFngozqrS235fiTxZGOfUMB2xOUJZvYZeWR4y5s-EEXnfE1goj-1Y3dSlJLZmo1YEACNXPU6aJqYtrFa3RNXn9zbqZvSGlUuh8t4ugFZspBtXlzP_L8RE
Pp6p2HkbHmibyyryukfm9IF2p7QAdGXfl4mURJgQs4s9iCZqpw43F0NXdBD4pXK28PxQfre3yQ14FFjToV9ACa_G9qZEM4FEEdAvSbDGZcPniz-w04AWAMlq
4NAKimer0SJ7LTROB3FMhPhHsZxP5Mz6FyEvk7A2bXxpcPmklVfdNc6vXknfssCoSYEFnjMaGclDGx2QMyqRRNKS3T4wzxCshWL33TXnDDfe1NEkPIiNMGsm
ysUDshIQQT6ilUIiyKCoP-rZjCUdZLzdutVHt2cq_GlIFKUZ7Ilo-1qIjRUHHGV83gDPR2EljT4LPartlQ6LSMOE-scZSpR_RHejQVJFpqTi_U3cx3ERl-pi
KTjSPQqp35WpVBisqpPcpPsm86bDS-EDev5cLgucJu6ACmKqiHwSDtcP3G473f4XnvHDsh0dKnCMIzQEE9wpzCzghbX-0_DRljKBDpuKCSOvqpOzWGt1JGWX
9g6VYPT_h58CLou520L1p2u4GCw8pIpOW_USy_ygfSIQcSMdA3vz-lJfqwTFdpvz-Xy
}

