sprite $image135 [159x245/16z] {
pDhfTXif50HWtGNKT2kJzt_RYP3Bomq6wYYDLVzcpNUg0A-__sMkV-Vtal0wv5LroAlga1VIfSlb8g9gPkwUu7iXtUV0zp8wnhTUn_ZMwnZVUXtdMw_ZVUjr
l6-zJf8IllMwpFZMwt8IOj_rEkNEt_hkMDzwdHA-zSjw8dphTQYHyArRrW4bVCjrX6_Xij2nllKwLyAtV5cdFhwjr-LanBwBbyqvGxV2LwurGkaM-hP7UpAv
B7Ioo8TrkNDdIN_EvuDbsn_VyYgVfg4kswBpb_uadZ-HKNVGCJuUXkJGN_VS1Tr9lYtrV23rbZKzqVTPXtsZJhkwd6WVhtCtLKivdhyqE7U6ltk6BrUQgOWy
D1xtrVwvivIpdtN-vA7x_1PRz4b_MUW-aYjl-rVJUlXG5doipWRjiUSEEaGIpjzFwhpQy94X-49_DZXtftI7WpVsQLhS7NWcBPxaw5kh0w-Da-X3hAiJI_cU
z2bFyLpQE16D-qPT-bldC14yhZqHHD7VJ7UyZkT1XqIV94Bt9A-KaWDFGZJwD7tMoPV_JglErTxYWKVQm0kula_kHlU7v6ignkt3xD3nkC03hkz3Wz_7JI-8
XV9877ZGJVgihzDG7eyBFDYcVEAGj6AgAeAIUTv_fKIU0ZVsGUUcyT-nUrJrxPzSvF5lPhgvo3EHMHzq4jzAwCpkl2haopjApBK-VBC-qV0nEkZamTCQJobT
Is6hQwmxxOkVtqHTvRqb_SbMIjavNAmFlB6lubo_rO6dA2-N6YTrF4_LyaYdpV8A2gHruDct9iLlXY3UNXOgY-KXVTnM61vGdcBSBBGdq84NoaEsRdKCJu5f
wQ8Fki0pb3VXAnpFMZ3t-YV3rzA1X_AkuK_gw1YUVp6PgeOF3Yej7V0eBvMGWzU15xU52Mdw1Bh8mvCSqzAnFEj-d5FuOdVWXV86liBorBil8HgJs1ruiRpk
_IWK3-MvoD3NqEddyhOohc_dUTxT5Zv4cV9YVriXURWOCkdJ1Y-K5qDC2nwphG02NU35ZsSnEwCh6tWJ5mCu-BJD2-N5yBpfyi8jQF5Gtj1NU9xsBaQmD7Ks
B0_pRjCyrucBeOE0PoXlK5zXUTYMmaKUNfMHRwTvgjYMmo5JvO5N61u82LOQX_PcoYiRozCQRsohb0wV30n2ylI3fpmEkd5v27GKp-Asb0swj9t12nU3Bmwy
N8WGF3nwF8ujZ-TXsoTmL7ay3zloEBuydeUBmUEW8yhZU2ZFALlKZSlZyuL7wHQK1nwsPMtnv5rFuU5YqBZ8AtFPTuANyFKBRulbdSN3nU1r-0OWSp7sW-Ib
cMrxCkha7IJFnkKDQDIhSjmOdest7SbIlbwdTVljDdluyfrds7Qi0uoGFS_hbzVfB4F6vFXrEnYUTyg3h57Q1XgPso_KDyNhb3UMyTdll6EUv-056M11LfxC
SUUXlZ6lniAUH6TqUPLtC3m7ZR-SV7cLX_h6F9HtjWpbFNW7mOECVJRu7E2XlWdU2XdA0my-YiTV0Lu7ta7nU1cV0xn9NruaWmwyoNapSpcVdnQyMHzagtJW
JVUtMWSUVA-c0m--LzE11zzhwI9l_BwiUb7-RzUyrjlMWJ1upRy4x_-qfnSwQqheYoIUIpUC5xGbp8S7Y6FjyZSOOLfHbmUDZZncWA02m2bF8AKdlVm1Vgv1
aCeNn8C4IEW18bbE0WKgLV3b-XAW5o1FxcyrNafx7O5UmOkMBYX54DHhy4y2ehJR41Lh_fk0e0e8h7IBuBy4H6cR8QWgS4j0bBHU4MXOvvw0e1ROxWY0Qk5Z
0eAQ8G7KU85KA_Wk0K6Ta0I0Jwr8zO6GWAXpm7S9I5VmoxMx51BGANvuI41GBj74EiqFBn8Gg5o8rmc8kNPl4n2KHXHmb0SpD_RYsmG4PO2Qo8Aa0R9oOQGC
4FK9QByWdZe6NYGWx9M3MXCGk4-kAG7nsY9832SWPiZ51FGi2AvqQqz0KH2Sx8RP2GYSvzQIW5ZTBp2iI8PVU3G12RXcA19Obe0mTAWcWDK9wBEJFtlEwc1T
9w3Sr328nn80tW6U2W8M9w3-1eHD2KX4esDpQE4j0Qax0LMPaMe6VtS2tro76b24GQl9ZXyJ4CvCGC7lr0I4SnDGzCktk-k9FtK2-af0_4f0Oma8noUWX2Um
eOtnIjXXjYSWRfThJ43S8tTo0c9V0iBU1CJA11G5eLLWA05nLmBIQ0AAXkDkKQuz0N70SFXd0jwTW30_0H7XODW36rFIXQPRGFsE931o2sYW0R6z0DKc83Kd
83mLe5i6mhyq5A3n13H-smliJ43NWhmIp9Ode2Y91PU0RaOX0KrhGFnAG9bsTptzD0deAm5HGKzCJonHmWSabb2XZav0V4v0EGNZUNKx-ASc8511B_kMpVEw
FYe1KNhhfym4LEF7KnAG9KkHGnAGYvoUW9wNSIb-_ix5XemNZQAU_3u18Ia1gPHIzoEuvOPIj2joPQu1zru2al_KSqjWsPc0_AtyYTrqykvDG2GQAqifmMz5
0s8ujWDwXrM2NbjW0Q9bz0AwBW7P9VXL6KOG25BjJs_v3xZjuMwXiwswtB2NNWFg2Iqb-FKa86150RBBHpoKWCWf1IXkRPnVFdO9VClqYxEBVl8PSYgVOvza
5_5XTj7F1prt4JXN3kKDzad_K2BAerHXd_Kt4Vqs6zfsQK1R_Ihaylx7M2xjI5j6Q4kb3rdESiiNTCMsflsRiOGo0rdoT3Unp08p1VqNPJAsx3bwPH7oc5TG
cmrjTSpH3dBhaEn_rdplPKcRpE9MFypo_gaomEy
}

