sprite $image86 [277x277/16z] {
xC61400000CXXFdRpkElMXC000000000000000000000Py--hXo40IY8_g8d3lrtk-iSnzacpfHmGJch6XbEopufJacOHP9zaWGgac2Ix9EbowFyIJ19iEMI
o5BoQlubL944amIJ19C4amIJ19C4amIJ19C4amIRF8aiNNghc-fFuk_IfFyaeQe31vC4amGREuaigJbFbgogus4f8th6gP45vX9PS7gjSMwvDgZ-BMqh2w2C
dIL3eCX2AAoIcX7LFueiZ28Beun_Qab_AB8GYYoCKcJvP-TEboF7SI00_m08uaXWtlzjDqWfofRtK1_KkZWzsNV_ynT4Wh9TzUyer7oZnlN_4mgHRC-o7aMK
Ulp3Sa69B2NMsAXQ_7cKAX0HAu1_MEA5Ki7alTbMBFuqIZLK2JM_OV6tYZw0aWUAeAgageo8PAl6TNyAnKKp1qeQ4NFVYqKVQLf2URE1Kk2UODQzMFmPb4fb
39HMLKh4cpMkFO9IsKJpG0acekPxiVXg51ieKjuiZY4YQeraDvQrA1HLw7E6JXJF4g8UM-rdzuKeGbA8FZY2UWwK-LUYxHhNbw70M1eTAEBD4bnLsMcoO2yM
MuK2A17PHAcqPbmZmuIfsMOilWe58SG7IbLspWF5aBpX8h95A82pbQiSpTAyAedokFcJn6OilWW5K25gEL0ujSM1aa8aJFsFPObEr2PA5QGJpMFJlUBV5j62
_RmDYpT2PRIfGSSdMhIgX6wk_dyxbakFca3QH4cYtlD02QPvzV-JM2w5qOau3fGACHyePSmXHB8VowfgQKHve5HvEr0qAvbeGUFkoc9i1H3NKE6EWL9LUjnn
zsDPD4DgGiGvK2oQvaJ9JWSBjcDPD4DpuKoKAckYnwcHT29gXWNxUKSMPwAe72YLqZ1GfAhwWaMq5qjTPeWuf0sKKccQ1qhGZCH-BEjcI7AWQ5bpa_fGeVwd
idWZwWF5gbBvXT9amIBQbqMPip1Ggemi9ugZX0QBOJ-MDO-9Oim7YbZpWO8gfvdc6xBKeXbYdoYLNMoYf19femsl_ZDBhhWa0wLN5MIYL4fKyeB6tPUbKvJs
VXQj3PnPmESTTqUMMB6U6v6SADhYG87G31isPF4bCqJzGCdi4dqASOFDnbsmYBPaKQAiylaxH7AWZDzbmIBQYoKkCoJPPQ8KkCNvEEHqH697bZMFYSVs2KKN
kDIXClzViL-rOCaLzrG9hGgHirbwWYVAPYoHkUQbGK9abGEbIja7IgigcoXRiGGoSz4djxsH2KyKbouuKC3KSMIJQa7c1MN1UcuOABqWtGTAvKJPXYMG9yeg
bkZqSVDtlg3imJ99C57MiNWZL4oKSX8C504sOOd3v8MoReQQCXqeBPecBYXltRZ84PmeQraw4Ub4gR9c4sK3biWpo2yegzOpvu5IsQa16x0WNrc6SbtFnbgz
IrKLNYZlN2sHUOEovhEuH2rVA6_EWhn5MNR5RHE5WVTcYSodK6RgwthEYVBEB86yGLayGorw8m9WWPdtQrnaBaUvl-9E58ttP0da4oZtLrmAG2lTy7Oio7m6
vVunSQ9KfVbxLKlaVmqUVnUM4wNADDw81Nc3yYmBOD2eCdF3cx14pjnCpxCiBgHbLkd-gooBZyazolCgq5vgLGMBRs_So5o0ie8bh5kDY7up2t81oZ8MJK6L
m1tVnnAP2r3MFJt3cMB0fFatDMuW5w2iFYoMWfjgUP05cGjGrhEO8AlAks45o_fZ0joYh6TnCq6vljPp_3pBWyS4DoXFLOiob-bhXZmNDEwIWZrGyWRbgHdg
CL2gmW1O9HvdGSuix9JrBDwrigeKGA_wocABMIANc3pFujAp381NVMQn0CniPUDYaSdprH9AlNGer4L5cyCGvgjO8bUQF7zhmK1Xowa2mqnu5m2-Y0LhIPvd
yO52v1SKm5ab1alyzdv6lht9JEAIxAGvK48n8WP4iEhiblYjneqzJ6RYgkAjprAnSr-h6TnPF12_nOBSnMG6rtXaYYlEABl3kxH1O3-ndxSz9aVgAmiJlL2Y
Atd0MLlW9nRHRiVa_h2q0-LCxsn0d8txyooHzrd_kUhrBARudDww8OB59aly50jsCRbdkJuqXx8PmgJ5PH7Tlz0tSg_HkLSH3Pmn8tE4z1RuYKM4dKrc0bzZ
gXrdrCY0Q7gou9ubSaUJ-zDYPFfYaQQ3fOl_o28AO3-IUvRPgqxgBnPMHKHhvfT5rEFVMP29_KpkLQoP1ypuuuEU9oUqStnUHCtZ2qiC46ouTUvPmkT7RoBo
Wfed9qGvXj69qhNPPvQ30zZodDopYB83nlewBQRSPxMmuqHHTmwrrtu-CO0jIUvL4AqtHpYhlbYQT00YNN4csBKfpfmWmBOczopIrE7EtLyifFqOBfnnywui
VgASlsrjSbyjxd1jyl5Vf1gXWLTSXDqD7nx0pXLxpzALFU2joybmFJbdL36JFzCfV-sL-DAuzlhqv8pr9hZ6D3wX97OtkR_BYOWXWhk-M3XmJTW5PNkJUvRe
R0Rt9XxuhxcYt9Dips9AvwSdOm7AORA_2jJ80jwqnU-YO5-IAylrqvEtA0jCjc5fNH7HHEFNKJO7cSbBuogTdvxyPPI__jM-NQHD2CHW4FvTEdduxd_QSGiE
owJUqNKjWBOSpA_2zAJjZA8eqHNtp_PUKvH8vm-FwSbHyr6KZ7d_jCpsACh7NvblZwAKFDWOnPMKUT1iVHGb5Y-uNxOsYbABazkjJKJn0as2E1wovIYgmC8J
xc8K5U71V1JLiJgAAcbBKJmagM9-H7ZvhuAMegYcwIYXIJ4sEQ6YoYQYgBWOvVgbyhf-59t0RyBb12_N54LawLrEC7hq7ExQ0000000000000000000003W2
}

