sprite $image217 [258x160/16z] {
vDg5SGKn5CNGDKF__OOJ3OG-BUbse3FuF5vMNgWzB-A5Ebysj0QnpO-DxEt7mDdlDKZqAmrIdpzi56y_1ev-hq6cNscG1vL_6GH1lysWqAype5zh4EY_TAE6
q_Hh3KAbtsWGwhpBQl3sOt3KyrTeGF_TLwErdxLufESFfm7dhzE0VgS1_Lw3JB_EWFDVQ43_wkjfR-U_qu1-hK6WtsT0lzE0vm-d0UU_rY3MkQ_rlB_pTtq3
Rpy6rdusyahF7qu3pb-j0VtxDx3sir5MUFxm673-EmtezneK-dK6z1_Q8DpX_5SQqEyquFb3O23evpFEfSyVMeFuNDwPhJUkyq0mcqGGtO3V_sd_HHYRdCZ1
R5PeINLtpcLzTh6rJ5pqg2GEalb_ji_1EutGu9oVWrb1enwQ_8MaGZs1Wv8uA2GM1pYhWq8k3cWygGDXA5WSw1aT20EeufmEX47BmTaSX87cm7Ws1s9iu1H9
rFBU6wZ6nbcIgFA-DW2UAOdDGJCWvMS7n4aSD0CGmRcI60wQ0TLmSA8SX0Ez6g11KUgPSX0EcW5t0hNekHQIycgWc3kf7-LSIOHzDc3o8UKq2maqmyq0I53T
EPUpB2IQcMbb859KgUPkOU3mEQ0jwAJWWfPQMSGTYm5K7Ze7C0lgoqTL6aco2dIcgP2aIj7ZEW3jYYpl2uCB427Anmy3g4KFcWDQeyH3evk3Kbd3W396ul4S
q7hcbuNtsd8GSQpgJeI3GoKHzZDpz-u80z750DmTd6ivL191-yHqDH0vQ0ZSNL6dkVOZCLRKRg6j-EYV8KldG6Xc0Ar-Y1va8S7kyDu4H0veN90g068XWQkL
Y0Dy0OBFzuudrTl9M1KgxZw3985zvu1sdzMJvTVkP1JeHBUP9Bdl9DA2rC0w1reKYkc70MZHdIOHzZLVlLNBe0emXm5Hh5SYTXo0W2_tcVgXB660JaMLtUM0
bg3jAFWo1rhArO0RK6LV3cW9dFCth9G1EWCwJv74bWDoVm48QbV1F0VzRJJ7D0lsiP10Iq2imPn-A8igbUfkTTx7Gg9bbDz-sH8CQf6gh7ItUGyB2VQR1So9
eTnM8ajnPs4O0GFWwNA0FojWpbJ10ALIG0a3YbAVTI7n3mkOqrytQr7AkrmNaZxdGgBzOm7l3cLsAp4Cq0bykddm33c0FQA0UGwaMqZoP0i9V4G1yw5CrMP0
orH5dcSXqHvKm3m7RI6XNqZZaqXxO07p7FGBoNLcC3W7U5G1yw4CCj0Y4Wl92eEXEG0tA62U0ufKoXmBAHYua6YR532_RYQaKi3I38nA8cop0kOvY8Nq8MoC
M4ZOk81v3ce1ce4XIQHjMi3ykhajf6104cavijdVwEel2HWCo07i6mgOtqPReoi7XW41I0guHGvwjEetvO3slGNCXtAZ6Yk-8GSqCxUluRVzoIv-Gjs1pNE0
HS0bAU2t_UtxzugL0SN6IOm0N7n00TFRQ45j1ZRAGGJ0tTnzJ07p71In-4y2cpY0BIm2V501y-jcdMSko4Tz_0KJQC75tVqoh81v3fGBm3pfWtD0k-9XO501
y-lcledbNXBnW0NWJj9zN07peHp0tV709CAw4z09a9UqW8DpG4vqLwx8_z527e2MVmT9-EW2vaEvY5DvLm7C-3TV03SB1KQIO5x0yJc0Jb_UEw0P_-44T4CO
o0iuFWUrih7-6E0FJy2sWjmO6HXRmFowEGSA_fu3t3i1Bui8JmhuH3bWzZ4m_j49QDSEU105V7lENtdxBGVC7OIaM_sS1EpI32G57C_RxtyL3EaNe1s13f3m
DegVgu3vK6R-CK1s0hOh89AWt_wl6P82Fil9cA6LXE8B1xJWLZ_lDu2xFra1ymTCzwa5dOEx2w3_ohk1u7KJ9WNSJmxgN8eeeNqErYVWTGPTt4Zp3JRWi9CH
MakT5LS7HFi2t3Mmq3RWRaXEHXMTooGWGWAnUWpY9EcN_kkG5727EQZpB0H9neSVu4e0ODwTW3ieOFOcrXhCeGSjW1rEWAt_boZW7fcI74Gjup1O6G1l1Yxk
MnPm_536NGC4ULj1IG7tUpBc1lnYR4VWnWKSVysuDj3V5D--WEE7CkuOsE0gUFp9-4S6BbS3d5wEmhlIU9-rWJW2OmCUXxSA-oC3KS13KPJskmOk7WKy61zA
Cwx0oa1ImDq74U4WDn05F2ZlbMRC3KG1ZyiCccKTE4O1yvdyoO4g1ZmB7ZsJhJc0Af827fH9QTOPE6m1yvbiTiq0aW8UEGSA6eamSE02vZyd0sWOE7m1yryK
H2lWIHqW2dXIfggAAE297PINx-Q_
}

sprite $image217 [129x80/16z] {
nPW9hkCm34Exno8fp_rFEqkT4cWdHV039-O5-60zoqrFstAPolKq8Au702ECgH-6S9q010146654lH5kHzONrn-CuFfm_U48DzSFGN0z3aTmFPoZ4Uu115OJ
GEo0S7whNqUuZwitmhXw8vpxr3zSFmB1zHY2S7d0zGCGN8yX29V9zICGN8yX25VNzqDud8VLmmWRdllU28FgZG0ZR7ZkUo5SnjIl8zoySuSWt43N7u4mVIA4
Q88X212eaGYGI8en2W5IGq1W20Br8k0O14e21o5S6m030n4e4Sc0LJWMeL0YgZ0LDOHZ3q7PHa1buT4sFcjvPug1oA200n4YgCpawJmf1SGa0K59n04g19J_
Wd-_HK8Y8AAgb8Qmime1PalCJsAAJm36H4cqZRiDVqvvVOXHOWHP0P4IOHNs6Bup-NkWI4842uL0Go0HUmpVKNq1M8MOA911gn0x3D_HxUs_6AG82bav5Nen
zHs-eypmRsMhaA90KINKsSQOJz_XxRtUAh04b25sLU6zNlRlCrT8Gg24W82iGkVJn_NqBS_jZ82WH9V5vAldw77wdhQTII6JCK6siSFfBykth88GO2eaMOKE
Ly_oVOstin01XYGZH6oeNvHlFSyh2PHGYrNOSFNMvLjMePLAcn5SloZVUguX1_pnOWemr-LRLw4rI_oPZG5gWtmBAipjIRLuCQqFlzODyYrVII4e1IGZh9z-
hVMRV1jK82M-28omSlfrYtpBsxdrLiy1Np-f8wXs-EARV5lZtsmY0Br2Iaig1FGwV39JI_9jLm6KmuQmDFm6KDNaEv_wv0fzX5GIiJHyrKPX-RhaJecV26e8
ldgUlhBM3VAjRUUt84Zbh490ldfKfcgrVFro2KaEIm5VDdA-UBNTFbNBrpStI3G17aK4HUzTRo3BrpqFocdjW7AEgEVqUygtV2KTIlIxLwNd5UWht_9sfkOO
m0vQlXrpVoC0qmIMR-TSaUB_0Byit-uvJvaomCApUyWX6C3Fxh5vi250xTcz7DhkhoWHsl2Rh-DI0FpiZiYr0B9yGtABwRGnVm
}

