sprite $image20 [159x271/16z] {
pDQ7KXn138JXoxlgxZhU_sszd9njT6ccrBy3KF4hIGny32a--t0jCaiWubTmdTpFV77PrGQtnl-2qUXiWL7bi5TRu3KUo6IlPYU8UBZL5vSP79tD0EEL5eEz
bXcyT7KDHsS4Z04P75t3CtsAOSqRdUS0OtIBmUJA34PNPupBPkpLvtjaYUbT3VPQvelBu8lBLeEZAnimEfCD8teQWEi-mMZDTtGPV74PJ77r2OPH_naTu0j4
HE5htp1lFheEa2J8WEc6-HaYJ87ywGilt_AJPpf09CyN-9Ddkc6Gra1cdXk6I5iWAF6V08yDKqgUum0X9SyH2AhY4Qr0IWMl-P61LF2QWP0ANlC9WYfutIT8
gU0rRnXImMlUCAY2rmfCNC5htZ2bWjSCX5JnUZSCgk1r0waYbit_LGig0zWuG4XrP1yGL5OlLse1KXh0c_J8G7gKnw8vG52FyoIGdBpX6bVpdX_W6q3euVBq
GfgxuHfNyn37DJ-Vls5Gp_AM_UcINs0saDBplDq-nrS0wnCSiDUAjtMC0ZZa16jSpTjQY0kddI2eztYNvNnOPfqWfNTvbzrfaTvu1QkzliSx73RUzl44IODV
GL3lylR9spfJnCYVSuaRiTnRA-8sGt844D9WtlbmMWSzCf36ytQ7CIS8QWflkyKpNmQ22QGqYRTrW68jV2KHMz9CtYwMop7qF538lSxcdRyrOoVAQJFD6e1x
NyV9_T_jAMd8yG2_PPBF0ZgBQkUfdfvN3QZv3oSykcVhJkGnGYe0sjyl2dF5_N6UhpoQF03q7jqJ-59Ut1tkV5RvVetVZISN7elC6Nml7bzu16ozZE3RyG1e
sVRVa0V0FN8xupVbGPdo_hbloYEoMaxuxNY0omY-8Gy0E7lC57nB7b2rxw-wL_7a6vu8p_xLM_88THd1D-5XRqz5Abg-SBuP3s7o0An7RiPw9nxilFbqqQM1
9_BOwEzvYJmNhT5rCY_ZGHvVUBJnvXVEdNWs3n_auUJfpWD0cvQk4tdW6q__zd0lcqnRZZ7Ev05DreM7-3YFcaJ6ZEdJU735iz8lUBJpQEKLaCqhCfx4qr7u
_xnUUO8RZtNbpH4SlOpWkJog_8AtiGZILjvyH8-S3QpgqNqY3r3WQnvY3xxb0NUmNsPm0vx90pZYGGovuqc1p4Nh_DaBEkH9y0qFDnwoFuLd8_68ft9xDHHa
Pr8yWSTTHpmSzxDtuG7OJ_FqZWTa_p9xU-dPlE-lXXQ_aiUA0FKrZnLUoVEEUrxXP-ublP8de_201_NYsTEuv-KdpnSUl-Pg7F78y9KyucDU-ajvtdx8wzSU
henwszbB0Omyv4dG2taR0evufl1Q7YmyN7ZBIl2sF8WXRybZmurbnS3rVZmPgOaW2lUyV0VUg4JiedjUl9v7jV4WXxmb3z0Y4RoVpyi7U3G3XGtVaYSZ917R
tu17_uitSkCDUJqFxtayHYT2tFBmFNX0KNCbkE89lmSF2IGHuZgMUII-1KzQPQu4dxm474tlmHizOvbM7bYz2MzU3QkLTzxL-FXB7aXjF1Muvi4JUNp00xH4
78sluz41R-CWrCti8R-ULvyyxoiUfhoSHmjF35OUZwOtuc470XVyuK6_1u_emXi4d9yyD7m7dZfkF8Y5TtjpxNKyjCaJn-VnxA-lHYeyZrU6VyV3ySp3xKn5
WE37ktV3GpgLLoCPl-3XmbERFCrhdlAfFArHdj_pE6Zo15OUZyJpUAFPHbKxViU3cNiq-lhcZgOpUPcLrPLop9kS0AYRsTCYq3DucTLxrSQhv8TutjSyG00x
WrUv0wSmSxJp0KzaykGkzqxYTUt7Edb1EIgBl-HfuCQZZcVnjlhJmLBlgaxvYeUoy-vN0ZwFDxho0gpPotGwdhsuvb6SokjUHd3ZzGY4_fedXjUvrtWgxneO
rYDjtFCGTnwcmSh3hfDvqtS19iUeQhdc9OBQpgFRbO3iTDu4rWwCFQRJ-OR7ZXiFSk79V9xFMq-uzfXEfoiU8EmyZK-UFe_NjG2xiaOfhJoOF1Du1Uzw1Ckb
HkKzZqVZYtZh29RalidG3Gzgq2juAx2Nc3Qyvdcza7SzWXklMt7bYS8BUTSZs1KnEkoJHvtuMjuwWkrS8wle3m_xbRDtFu8-Orfnya2RG5xCcxxhc9R90yBd
yShg6BXiCiay6VSyFuldwbDpF89bDaPcVi6pitYgAN48dBxWwgnIV2xFnSqjlptXoZscC-JftRCmhoDWhJ6T_4IUgwchXSOni6Tbr2Ypf_5KIZHKm-nhtoUm
LBgp2f_4CpCBrLJnwWT29csVmP2dyBeqzkwvIPRvzy3gZPSPV3AlQiU4kMceM5QuFH8orPqvsb3zJDwVVhYhcMcMQQhb0oFOQJ4wyanUrvzFoqrdMUwk_aWA
Tjj-HP9Fv6trP-9dzoHLmzs-Jy6AsfFQwTohaHTWx5V3nLt3zA4Hh5reU1vl-RpgiarcRcAUZwnQNHazKixahQkd95k8ksYsFxHgYOtEylDuAp1DpJn4FTiV
UX6xTMMNqrcywnCE3JLNpJQFHqQmTbwcuKcy7cE6Mkr0jp_TixjLw_0t3pc9Tm7c4ZAoTqyixB4HJCjH7YVnha-uGpmxNCtLGlsHa64TdNqAxzUlqJtSwlFp
F5ijHSFKpUfxO4RbMRoF_XX3WNpTZJrKGpL5AlgnBvpdyAoiDnuWvt8bpLNTrCoY7nl14tYZk_hZrnYguW2s7fYwQfXaT7mxWgVmAiReNxzs7Z4ZOAufw6vc
wj5cRXR78NC2Bob7VtnOZo72fW9SLw5hPkAn3sBgTwlMZ_FAOlJuDJusdYen09dBCe8vkwUkQj--vtv-zggxFtxz6aC8HJWGjj9QKb2ZFLLI9Vox4JmbblVk
gHeBJnwWhqVSRliGcbeSfapL1FuaRme5aPZC18cK5NXfO8Uxk8c7MdJaqHN9EeTdwg9AP6hA0X0tgzRb9RTVu_g2rvLrLlU824MPY9ZOAAv6li9CpMT6kyKN
lDD-7HKLLtMMJS76F0LNgvQhxjqp3yqdyuWPaGI52H45ep_6xJ9jfXlFDSoidieJKfLK5TKGLuuUumwe4Uscbcof_bIUA18Ig0WY4cQtZu_Rr8reqr2R9npd
yUg6HoJ2eKhCBkQItT8VIsWigvOLQwg6dyVx_RlNkiGoeUb-UocxQ_pXNR-8PqgRgxTRdSMx0kwnZAP2UomxPxltmhiUGP4mzMXtZJg9jm9dBDiUoyP2b6sU
2-ys1MtldgcRnJcy5RZ4CZAnSNQgBxpx4zRBgbLgTHhlzsNW0KCrMCmis8JttBtZNQVWtZqtSxCwWRS2amaG09ZsMAQDDsvuURrgsTuzIPLqyv_aVKpUrGa7
mLOY8QwIVLy9WFO9h6fNSzyliTda_GZkO_o-zvMn4A0G8kF_vX4ZnPA2OQPX4cuwUJ-ZMsahi4i1NCnuygh6M7WO8h39rn4CiVZitWcu1TWb8CH4a-VIAmy8
YM--BuMPkhl-36yUwm4m2LYS9o-bLXwwYUFcgrfMBGardxoV6BfZO2aAKIvPsnTY0YCX8I0Znvg2vZ9vPvphRSYKm7erqiVq9Pf9gC9ULryurVq_yWuwTnyo
Kf-yeBZmG94GINOUuNKA_bVUxyUg-hOY_yoUABkQCst_4zYwQatUgQsRrLzKeZFlwvOf4I7grQBmxxmLz-_0169IrK0IKHFNTLFOTFrFjaFSuy34K55cOdFU
DyExLUPSt34mWH1P9828MSMqRttdwew1IU7g8YoMOaAitIkm_XeuSJ_aIs14P3PW918MlVyPilv-R_htgciUcOchgaY8AQiU_CPojkw-WGbAMmagRq--vVN9
k6DW8YkRglF-lzWTxycuML_4Cj4rhxl_QZFvQM02o8nb514N_pVUWljPeA6A4gEuin3Y4UzuRJh7Lm9x8JERsCEyjNE_Vbgs0eDtNuWAyR_mpf2jksfaCAon
_3Xl3jsPm2bX4BNFMAuQun7UxzFhua50Olh3Iud9UzwDE0O6mH8ifJPvpmoJOw0JW2vlZ4FUshhpQ-maXUEhSRpJdT_0p0FUWdkgRht31xpbIhoa3dYlniqw
vith-j8wuCsrwTNr9UzZVFn-X_gAz_jDQk6jOV8-TSVx-FrMLGjllYJUh3vvSnr-Hs4l2-Sx-dviwluF
}

