sprite $image419 [121x88/16z] {
nPU7TlCw38EjJOBI__wFUxrQTZ1ce-FaVcTq2oT00AlBF9dIyZyG6u0MtoqRAi3Cu1hUgbiOV03ExvDD1Fu4eFI-SFahG7k3tq5T_lf9URLk_ggcZhywwaY0
QjNyFUhuqWefI07VewxXbHLISvUbWHMD-XKLKh2Ad5uheFIY2YbO9GB_n5dHwN0LqBAerqRKzrP8GLqMm-iRgvK8vkcxeu7Ddu7I_IwhqvRN1x2Zdg-GWdBw
0LErCRY46ofaEcrw3QuvHe8VjLyXs-cJ-lD9jQe5YBUYVhWss_6MruSKTwTQVeKyfrS8FoOpKtTNrA-G3ThoISMtqOeyJbsuA-g7Qx-drMkTZTexDac0oLXH
jq8UOL48dsb63320768CvRaLpPgPwxHw3TxyRBq3tFAc4bdWHEsvRB-dbNY-eYH3JjMmvD5XhAXV8TzfXRSp0_sJGtL9LQIB-S3qm_MTLk8gLmJbK6qOGyH-
QjKmKI7BQRMgfZEfCLJKaCv-kBxJIjYFgEWVoMBbJm_CuihgSQYMNqt6lovGnTfCSQ25F-_Zvt6K2p6dtnrip5HBNaahCOOGLXzY8TFlOjpIJKMYLakEuR3L
g4MmIvBRHTH6XJGZgeUW4eeqSm1YJ2ddKafTQKIeDBJBHhKiMGQLdD8tmLmRiJ16JrR45NryeVUkgXOG4LmqDSHK6a5wtu-JBg359gHAV1ZbWpx4aWQdN2gX
xuAzTm7qMciGpb5AfR6l3HcZYrZIEFooVfBCYBjG_H3FkpWUo_RH-n1B-V4VFdAQUXyg7c8fZtP_bHsRZoA6j7C5CCWuNufGIHSRZ4DMXVygZMWB1yQdZwFJ
CTtP37SSo1TiStodzUgb8H8nD_hbiYBVm8JJvhyKsCi0msLJs9UEooEClJTbLTYJzfrMhvqAcS8Au3ZjUsrNo15UWUkqxRNliY8sS9msABQmLiWGje1tsVAz
rWevmcxKORc2uBZi22km7vQ-rxvixt89VAUL1AT2IXyZisfxVaCkyIkaib8sXwwblvvrYVpLvT6FAsvedj_F0hcI7Je7aVgDqj0AcIxdxmzoBsg7FxjSVusy
E57V8Jl8c88RelR2HLfC4az4_LI57bBSgETTRfU36wQZHlSgv11f8cfZ7uqAUUJdevQdAZGVzMo5V49pefwia8-_ehCLidbwHVsdq0p5yNkYGlT4VLqXv5bP
VqM7ubNetgXlgD3SYZuCzuaAJQteH8NkYTgkq0rwtefQuHeLkYzgMtXY7sTNz8TiBykBI3_yTguOhujwPXzlML7dYl6wg2VsyPuLrNry5sUrj49l8-vHwpw-
aSGYUiLuAqKGbsd-0m
}

