sprite $image217 [258x160/16z] {
vDZL0SCm5CNGSdrVQFzf2rzQ8AopWHBpjBBwcupe_ukt7-9-wJWO2vWq7lK7s8O_uEs7jX_HzYFQViJR3sy_jFs8jn_UVdZxuUs7jn_UVdZxSQ3dZyLu-t6C
uI_-1bsjmll_uUt7gEt7gEt7GzkFDkr0QblQ_u_cxOUs7qtRZsZx4My_lFtGzYDhFNz8nq6hOuYs7x5DVy3RZnMkVvQvK4VcxOTi_0Fn_dzu_p-y_n_UVdZx
OU__bcCdogthF0o0_wMnA02at_zjxrIkwpZig6jkOXbdFxFggmYn-QA1Y5x6VniXFxa1GBamUBe2Ehi193O3djK0KZEGwwG6q4BG37160qYh0Szaa0LEKmV8
0jePkCvc0DSMdgGI4HyAf4eSEqc0Ebabmcu4hEmDH0oViXUW6LCb3fzh0Q0PdAqEk0d82PPwkZh09X0XiXQSR4FIAb0yGi9BELSbqlr6mEt5ocas9Cgl12XH
YD1Kph8XoLy3BJ4hRIOYV1COkWxaIm2g1QLM5OjW4s3Lq7L0NxDew3NLY4aEQo1MCAu1vU-PPxnV0vg9vULDWBLWq3gG-xN0pg1KrKK00ique85yb_ariHcW
e4fIHOJO3CQgHFfDvYNDPecX2J0YgAcMeIgHyYom6L1RZ141rijKosuKw1fW0990DZ2vEoclBuP1DYIwzmLcsrv6MJMIouP4fIsH1n-0B93gW6OLX4N4r0J8
OzU1F2KBtBwCHbmKFkarnwv4UKeMo0Oe87Xv4o0A3bg9TF-QG7uPgv7J8c1WtX9vn0B803dxHTaM0ON0QeUh0tbA5kYFGba5mibgnpAGVn4WPni5NWbWkbnL
8XUe0nP0Fd-l3dOVemKla_4O6nBrc_Fd9H4GX0YlKzwGECG0z0rgiGfLHVZKsP0EFW3zEZ2hAYL2vKraDI2VhWweFm38ru2boYXR1C2RIdGTPG0qTz8tG87i
_xPkI4WRqWW5q1y5LIDjtP38MhWp49--07p-IR2h0xlQa2nlI4CKG7yKi0cWNAhPysn8yZi0P8DjG-976n9Tmvm_6oXlI86y8Ob3343_6g2OlMr8HIsFhGFU
_G9a0xCgcoAq2QGDQO01w1dmbO0gcy2ZAf5-Tu1S1zk6z69AIHlIaGUWFmgra4aWLU800z0R1Ti47b29yaS0x4U1K4ggWoCNGDyW1ydWRdL0FG0WZK8AQZAG
EDG0z0rKNPLtgODy_dZG-VkZW0ZoxdN01Z0_5g0b02O1yCwLIBKZngFEtn-5cWJ-l0xQ-ICy8XuFa0sA-Ti_oRiOq5iQG3p1-NCTO9hKOY_rxxzXejPJlWBC
Jt7-V0sm7dcwu8_hGBucaa02U811xiGYPGF-mGOG8IdYqUVlluoC2FvX9TAlNi0GAStF190DBeg0KWZ8nHyLm5R_mMQSpl_WyEPL244v1EYkdmn0kByHI1Br
NEVFTK1SJ6lIDN3zuWKCvus0vfHd68LQjILV0tvZ0FPRKBZsDJ2dFDwW7uBwcW4_UW7d1X49u4bIzozZxngullK2hhzvB4ddVvhWYmRwp83RqTr38dtU1DBv
3peAJlG785O1Kc9iIt5gmEDU0_PUmEshBOcAz_zD5-1m1gWImPr1Be3tzelh7I017DAW5buPV5G0kv4Fv_iLy7p-8zP1dKenYDZLGNe1rni_Xqlv1JpoDI1g
gHEu6eYx0SW2BGdWq0OmJELY51S4SJS0xzFVYY2j06COr6aoiMaq0r89W7mR-yuESEGwuBJmS2l0dG2fhV_dt80Zr84jF7XD4g3U1URq0XxQ88SV2eZIkWKb
W256eIyGiwlp18vs3P90-b1SSyfG1im2-GaSmU1R0lCcC8yIGAwFamMM9p0179w0_Ys1TFuX9i6_Af1se24IWDoLmYQGCmyOW7B_ca2C292kGKTWJXdu6W3e
ddzy0u330-GLqJS30Zp3-VF3w4aWdVya1W2O04vYGBd4Qu7vL0a08B49Q3vRi8Rf0fpDWEdyPpDW0ZYR0VzrW7y
}

