sprite $image429 [199x144/16z] {
rPdhckEu2aKtkWFfoli_xJapjhvAACMgKENssEllN3hBQ0DIt_ysB29olpZIuSjRT3wkAs6vhiJbHJxa9HSinUL5M2PSk1AMwqfO-C8MbkjAMCujSNcH9cuk
N0hBTIKi5vQmN5Z2SbqBIxgSHAloYcj9S09YEvk8Lo9Z8V695gqFhqGXe9FvB1KH9pNW2IelHKwVx01Omikiywab8j29wFptMVUt9tIIg2Hqjh9UpzcU29t8
ggBAZuhGwwmV-rh0ZHtjAJHL-HVLfwHGbUD5llQUKDzjJrHNYIxoi4CuNCJ6rkPqdkoYAi-eP9Fr0pssOiiR4ZRPOb6LXoIEYyYmLOm_efRXN-d9bfNIbKr4
ZXo7jkmSOQ2oJhZya1YItOEIZKWzD2Bo5Vqg4ae4K6Ib4ZhKL6rGg9YZLRwBIDtVOloGblArFHLLawNXk-iRu_2lIDYcQQcsFMNH8IZ3TrVb0x8kcwXA7ZJu
HNlYqJU9R6PTNh6_XFsGLkDLUwg3H6Jf79Dr-GvbWiMs9viAgt7KE7JihXQggfEkPhBiplh-4eKU06Dx6i_-9CkErNVdRPn5Ev9CUtgdFLEP_6ixhRxY8vls
z0hLZFarTXo7OHAH_INizgIRNIqicaOdjdaNJnCHduJtNZIlMEXHjbdclFyub17_lMYaubzu-9sKkT2Yunc77xjAj6ZQquHrljHfwtADm_qbnlOq4fSew6mX
e-fRVNUHiFS_bJa50EZvCQAOcJYs9fKu2yZ2hkqfiAhCQVYN9jqW1Ro6siRRrWRwIukXFKtXq2yZN7CWR99dD-1t2i8xjoTBMfj0V3A8EO_Bk_xa8-sHRFsy
5sMU1CCGKcMxmDZ9MSdtaRf84mTRzwAjjmsk-Nb8nD9aKJ3pOtXt67hudEOenUJPXiO6txDC-2JakXZeEEUegdfxkEN-wyMZXh71CrVRZG8R0pFd-bSVA-r1
tvTuTMXRX24nr_oKvNuHOPty-VfwnNIWDttx04wURGmcozANa4tyxMdaThlfMnxpPviHIeLLjO_YvExXlb9q3LLdUx9Fe1QA-T6D5j7W-KZ5Bz4rlXLfJsUT
ltaiY5t1REUkIhkuTVGT3uvRBtvjSiVkstbvluTx9VHcD6OYumKXy_04IeNCncssSzSDs2zXDQp8_D6YiBayKr5xWGZDREUU5TClCMhCHVBMexZgyAARs6pd
kxSdkLdKuI79H6J-efjfyMN7YkaiXTNmY70S7YWTpuEsX--Hx5737n5azZyFlfgSYPtdQKHz7g9QJDOdxtusINR574lcBuNLS8k8oVeyGZP9mquyVX2kFWch
uOt8FEiL1XDr4v-XP3K4ntcQQFZ7OUAn1LcelcfFbRwMh0KW-ahHKR_7E0wp4ScmRDsBbfWDHBU4rV1dVUl5prv3ykQzg8zCIvf8U3Nyup3OH_5W5_ln1Zp4
RAvn-mRrUCp7eH6fPDSzktXCHcPsbC9eE4HSg-_JLszX-rwacaQDKSAlqNX3nBVwwjQppRInbSbvycaaPDbX7BxrRCC9bZefXKyZ0bGc7fxLbpDDxqMjyift
_Scl4TQvwygw6OUUlncS9V5cy6kKIY1sZiCnw_vxqKJ2hK6eAX5HPnxpSLWSppQEUUVH4A2gCY1gS4Kar6JQqmuIReqbZK3xpJWqJ-zURbvqX9US9g3-R1mQ
OjldFFar6X3xExZFOymwrKCa_lovwq05PDdyLRaKyOjaiw4xkVt8uXz63L9LRg92w4ShPt5dFSin4hVxYgYX8EXA1WWegff0nLCGZabKZZXFtM8KaHnr9I8e
4rWr0g3g4Jb6udQx6-mF_DGegXL9DI0I4DeWiXy_heH5Hz8oVa6YX285G7Da_O3-PDWKAKYg2h0kIPSyzk2pIOnPxuKGWAKdWsKzSRAlo0yaZCN0K8xGqghn
cOoGHLFW_KHqRubH9050K0OozSSb0fK8qtuFa31q2OT88L3J1eXa8Eiw4eTzwm09C-xS7YBoETXZqIKg2OYibdE4mZAsBEB7_jkKrbt3S7We_2BryRCPG0HA
66-vRWa_BeUn-VBdQqb3Y01OQ9c5pVIieuUslo0j0DIMtMGj3i2BLLJrY-XFrwVVYrH2KYr0h02XtzKZMgXE3zsn4duHAKKrBmPHyggHAoeGcaTadyt3xs5J
KXi1fO7MhKi4W6t0vmY5HKSArk6kAW6DaLhe8xwpRoWSfN29PAIyQ2mHRyXL230BoW6Rh9yNzv3IMrIHYYKl6QJFx7EURX_t7MbV5r_HMfQe92qe0D2ag6M7
_gJtdJ6_Bu2AD5uAKpCAGY4a_Sg-I-3-8b808c8Le4GK85JGxCtt71AZI0PGDO44A0W46mqheYUIi1xAAMW3IWLLKCa8-fgZcwo_Pmc12Jbd0Y7g1dklu_kB
j1I12ag0YRZXy9dj5v664X0IIihxQ1Y90mkY2IqY1F5h77-UB69D2CYeki599SQA4C2JY9yh59OFSpKa2H27naainehK_3kDGU9uZpcEK9nPn76dEBF8jnPo
Fm7oEmsJx3CNnD6UpYpYUE8_iuX3uimUZZl5cKKSJx9d5d6qfpEBU8VsIQU88nHdBiXrAc6PQjolmuVL6C_J5GjoMGahOYR5TKNCdUAw8fSjXPqYfXGNHVK8
YVy3
}

