sprite $image201 [134x222/16z] {
pDG9bk8m30PXlCegSV_pJcVMJ9u2ziDnfqxmySlaqLs8kOYqBP6IKtWiBsHfnwIkbQJQJf8SLXcalQgc1ORexp0-I4YbobTb_8wXjAvAU3ie_sfv296RrxWZ
DlvFquG7uINdFp0f72kT3qBQO19F47Zb7aFLNP-TfU4Mtd-ZZXjsKYJrJW6bupaxTK5gU1mg-CahGyEh7oAnKz7ERo6ywxtZyExggA8e7Ud0LSOLGUXCHwvI
3IzJ7z60MOwqKppDGppLHIWmpv5tYgSv25SH6anbb9rYSnmClg81SnrrfzWoCy3CDeElg32V4NQAGwuY0_CTDGmfWd89GyA8GlYWDunkHUAZz2MZMz6uaD6h
I70XeyeBHKx-gvZFq5D5RD3YBqHaHkCC1BP-_v-vce67CFwavKkXi9vXx3BtRSv_77OmsDvWjXraEUDWs1JA2eQU7UEN8i8oXc_O59cfjTDm7iHVXR2AOIT3
R0fb5KDzmrPGODNJS0rR4TOpx5Xc9UC4OOML30NCgRAMOMx29RMpCA_67SPG5ZCm9xW3WyiQkGct68Fr36MbWlunu0utuJiOsgDOVnEznHYDRs6mL47V6C8T
ngYiPVXZ5EumHk8EOqGkhsECyAET-yno7eIXC7m5fWXd_zlzwd3IS3J5kV13xmgU8sbAggum3EWAmq1f2mm3kIqm36m4XPgAq0XPAm5qWM40TO5X0AdD6yP_
Wsv0R8oELzAo012AGezMqby0hXI6zUflcZYCY5wSg4ZeYSvRIG5wPU8m0dfResIyAK0u2bru9RB4IY9welE6aTWhQSPXn8ah4VfAhFSHBN4OOOd3G9qt35pR
vYa2LlZ36h72VIPSascAZ9lAB4N1JM7QOU2sCaiXk2dEMad0RNMI8e8-3FlTocME8i4S1bynwQcsZFk2hg10dg4eU4Xq1GKIuJnj1NG9HLn2WRA4GkZdcJ4e
BQ509IiIHWNbAZOCIrn5nBXALGIC2yfK20vAJ0KEApn5mM6YD4N2SL5PYeWN9PP2yAh2KHIyJ2hbRsh2wu8o5056aQ0eC4llFui4k_nsHG3iofiL6VUH_hmQ
lx98Fw_6RN8OQeo2ysj3ZQlWC8m_8II6yMylXw76FZWdUeie0WB3l4ryetAoObTyftpgGlQBubjjUiOeEkAx2aGzQHIwNwuAyetgxSVmke9z77exYAwWR-Lg
C1LsKhuvYcuOA6W_AzeD0mLZ71sXxIeuGm74-cL4Dvoe099-2T7sopiKaAoVHcWt31GqHpUyHG58iXsrNiOfpYkMbn3Ta0aAG58zWjGa82WwPCiw9e2ewDzq
Lwl-hTR-VNTiHKz4qBCKl5pX2bUumiuLhd25ArpX2bUumXMkS8KhNE4ALxZ25QvmXIjSuGfNkC8LhaW7YW9cieyL4GkiH45E1uWcO5UU45N0B-f-DuWDSmgv
Grg9UEWt
}

sprite $image201 [67x111/16z] {
xTX7RkH038LXLYu-zjp_kjFnGO8oQsVeNniVICfs1rafbTQVjPgZU0gvzL_QMxckvAxz4vMqcBA-PYn1regjBzCv4XhC03Fa5Q3gipMa1c7DyCtouWRujkRm
foEOTPbM5BDqQv04i2aHEwTR82n-20DJ0fHt42wJ7lXbaELw-uYMD_4m0s1c3n91SS5u4en4mruwDrQ915mnreY6KmQR4g5MtlA2WGcXPfgbcDSmWm5cqe6h
Xdq4l3Ap2BWCmq-m38UX15vLk0m2pnfSnaIm3gTXJ76--JaOC3m6l8PE2Ay17u4-QN9Ezoe-0YiNxHWUemAZ5osuse98y8x1JI86nu29Zeq1Csb3OvXfbcn3
OnI-27Y9AgzqQ9Fm8khG68clgTunj70JznXDnZRXCUBG9abUzO4nDCkhF49KUQV3zvJYFGRlAM5aZCWnHecWVYB9fpnEIFVUK_an8tc9JaAQbqWaWWuJaftt
Z2Ai-OWm8O9wY2RJakCMMcLMSH1PvhMh1A_9Ghz6y1IUaohtM1Gl4NoadiUY7C9jy19kG_aurejwbf3DGZyb66IdTameF_PlL8u4y0FtPd5dcGz0mZ58Xpr8
x1SgLli09FQBLHTt843Ye50wO0HwIeyB19LScpxxVE7d8gRzBU8cRk8cRk8cRk8c11J-LV4LQJJn5keBCStowJy
}

