sprite $image224 [236x176/16z] {
vCyt0S10002XcUdzkus4zFQ70yRTR3N-os61vS_6hXPuVZdiTfKd819z_mi4ka2W2mfReD05YIuajY2nXSOM6bk8R17PGcEBIXQHBJIs2pLdeXsh2aHHbR66
___UjpAG5OtL1mhVjTrhleFDZeN0wJAqeqO7zI6ojASi3WgDKek3MLkwnpNEVup3z5ckVbbwdAlRbgvopJUvablLxnhlSYM7wMDToQ7wM5TogcBNS4w-qPMW
gjDr9Jr3xdGbgEgjuI2Nk8gUaZokX5JzypNzRwxLkum3LTiLK-G0N-5Act_BudR5h8Lwo9KiM0zmTCnNA4lO5HCg8Sesi1Z5sQqeLFMxOesmVB1cwY2lyzjk
g8fTWp4Ce96MnbPw2c3UbP0gTisQ5mDRe-n-GC5HlhUu1bKnHcDfr6qva401dB9I7d8bf8fTmN8Gk-xJMim2i2YgWwu4LA7h9iOoRqpRRDLxfJ_Ki5X4rHjS
YLNR1sEDaGfuCJLOFqYcAvObbsjR-2K23LYMkM-TMQj-81H7NMdUjMtfo1pUHZ-mPh3V0YjgrW-4QSQL_AxDja0B_I3QjZ6L7BV598f-m4GULxh4bHYSkihl
VyPXSR5HEpVDkTASQzCGGsFT7s7gwb0jpVJSDHDcsjNGi2f0NZouyS6OoNADlQuqwOerCZNi1xTDa6OwvKfNk6ADzKy5a3LjxNM6_g4hwm7ZNsIqDpVsMs2T
kSILBdCb4kE1dCwkb7jDbUb0pNigzJ3XQluZk0jirohhAz6jDbCOIidLhdtNP-2w7osdrH1DR7-Ct_LYE1eFOcEyN8wxfP2gD0cc2rrf0dWURz0PBFe3jodO
F9hfEnFFLqWoRMs4tXhZqKf21gPkkwKfqYruOx-aJAzWaPscyEx8c-bTmBd9faezCFFv5RVoW8dQL6NsYg7I-v3NLrdO1LUCz2RKxUN1aw-O-ckcMy6nd_ZM
ZW2-JBW1cCzVt4OGw5usS4XX6W15gs-wr4HrgLOGcR-XRM1WwfdwGZVp8LL1Rj9BGOa_pS4qHyiOO6w2AJ29kS7LoDGE-RnB5KzzFomqnV4xdPMCydMh1cgc
ix0INMLR3ldy6CPSDQQ-1m6kdZ2AoK56GU8yu3eEMoONAqhyvxamwf1ziPKKj-rxnTX211bkSPIlusxGLV1Fef3ZwMtATQI42p3rt0kcQobXCLbp_uP9BnwR
-qVdxwgBlVUr0bFN0yMp-aLmm1krhMVpbQx4UCuvNC4zXPKi0wrtnVM28WoTiIkEJBio1iaz5G2x9V2Qo0vNC098E0x5o9QlSjLlPDurJRwxmqgWPsZEbRN1
BbVxuEcOjgeLTvhxNVK7SRYY6ARH_X8qBB8jkyHfLxQtwzWrT4tKLFM36XQiyRA78a-wwc-yNJ2uKn8qB2xfrtZOlbYPSPMTg_XS2ufCVoWBqk3NxrU5wdPb
tSCUru0w9LL51BucLdyDwTKrlQvwPDmrmKv9few-oqWD1WsBQtQvYXwHCLVGaTzCOSDYu3__3BmWCkhA-XSUSLqtt2c96XPR52TdgQH567RLCnYu6e34tzOu
Z-94qGiYOwwYftXSxSJVigLWvBwEXaNiAcemwOhp-JPjZG80dUOELrOBSRcQYR_zsTag0BlJt2PXLKFMwxgHOMf_l737bmcOw50rP0rNVy0fu5ausZ0VWIgG
1QvudS6sqdiuYLvNLeGuN6F-8CK3nV-LsSXxBX6gsjpuMqEe7AWTgKUqLJ5yZwl_OsnL33_ULRGRVhYhZY1FTcKTX1_hAZeCFz4Lg-8whaznPNN2rE3WuB_o
xaCtLXW8ep1iiSnu9Dx_RM_8FL9CUZBBdq4-AgbRFaoNh2rwQ_DVroook9hQQXwggQpnbx6l1dNrhxAJM956hAp8zfk4LdCFM2C3H1ghVVDnArQzLh-4Lh0d
rbhpHrhHsacbKB7gjVhjUmNx_UmCqhYLsjbMNgYTLROgwuSKAzXpSQtvhwXObLmz52jO5LSFXHgqmiqEnHh7uatjX1h7KcicS0gj-l4rd67gmx4Ci6LYGerZ
7oz62LDhZPFjHqQGXr79ZwnjsV-GKMkzK405cx-ubSQWqXXK6e9AOr1f32eDGgKng3G6bGQW7erbmlDjSIfRV5_BLXLG1TZozYEKfYseqzP581LWRrEVlRBQ
7r7f62hDdLL0bM9PHQix4vXBRuKga2gqSpTlOu68LK2LOYkgRdss5-i5ga0gqDvt4oUjFDKSgu0gnLuPoLrOdwcpG2hHWdh_rxJyEPKUQ2qJbRrrJY2b0wrq
Io2b8wstQQjcaD9Zzatr-jJUQdwPjbeEAOMFERIpcdCoSHL81LfEbQZkh2zhTX581TgvFr-OtrXPYoqWpQDTNcRb5lPDuMkwLTCljzY-lPMr-9vCIf4BsCjR
Asjn5K05t3fFTFNhMwjDpmcW4cwzRODtg-vBASkhUslSN5joGibrhHaQmTcNtfdVkwOk5JE_U3rdcOp_
}

