sprite $image24 [201x147/16z] {
rDg9pgCw30LWmfROiTJtVzfPUdzqEMg3AQTMXgDzrdv_78EJFk8YBtdSBzBC_HZtfuYRMpCmjtPWxip0t9g1kJK3Ssi7viuCp0qOjwC8dJixCBTcO6xDmDpJ
aGCeFHXfc6X9VqQPXh-PAKf_Xip3Jz9AKBexrZJydp4JbAwCF0wGhlKbrpCDhra8IYV7ChnD8kghKyjjPIo4f4FBXH1RfM_BzRBob7Z7EkooMvgKYAtIkUMc
OZkJ8R74IP31Fm9NCu2OpVXu3AO84wthjgMhMPNT9vTgfjEsLbKQwSR0wC_FVPI_3078ypTB-bahbKYAyAbcCfVd9qN8vbp_Mwk3137ovukoCH2oEO4HGMaz
ezFdb2hIWFobQEWiVFICdefS2a8WKHJl6JtBjKm02PUS68kcU0XFEV6Cpd8j8q1YAIV6ejMiyf1OoOcn2Fe-0ucaE6FHzenMYOFuOLekjAkIFqffG8WGBPVC
ECsPWs2ObiidBGKWL2wqt9YCmkQGWIaT80pbO2oIr1roNdBy1fx_NGXItB78Pdoe7qHVDhUecKfPnoY8WCEXw0H78ISTIxLzScf0w9npR9CrdDpesy1-Mknl
gZvJwvCI115mU1GyX78VdUKl0lk6cOvz85XVTVREQz6Xx_wH68Y0mwV8TFWvyevfzVtA5W921hSAtD2qAwjewzzm8IiS2CHHrcqYgKSGRQwhC-hc17LBnTyg
swbX6vAbbNG4AHDS-GO4Uq_ZV7C-SJAHZzh5YbU-mK46GlmbIOT_P6dSC_ZHIvGp5rFPEy58hyMfVejllznoQKE6nHdzYxvlyN3ej9xUkne0QNoAZAE_kIt-
_5PHine2sJ8jMPufwvm6TDIJRqFpgGK12G-9oNB6mKlY8KFAdWCbF2GiOpbyicqIZORmcGwlmnmA0SbBYcJWSY3bkn0nqpnF0n6ShQl3Q51eIDd-2xaIcAlR
LzV08EhBUVlLQXUJyGh3NGwUuh_6gzPFKvmh362qAT-4yD_ioksgSgCz8TZ1bzR7KJkJgjqW6GxFrDaS12LyHMOypbI2mMoLJ41miF9RRkYY51ho7AoybajG
mbS41oiX60GbBqUG9L-W45NLe9ph-sbjGTOhtrcf3YDaKURTP0sGVJUTXOw2Ww2uLzUJ80IUqMaDPV3rXSSY29bndc32Clot5iL3g7cdIi3GqENWwmiEePef
PaOoWYbu28N1iQWp0odjUuQfOO2nYDqSyOjIpIGrXcqng-Hon5FyRqTalgewK9QNgc8OGZ3OhQBJu8n5vwFsOHwFRovAIJ0MCLN5GNZAsgdbFlxak_LbSu-M
-tZ6laiHSHW1lUh1IFHWBEh02A0mBPTnVBk-EZ182L540LKLK5y4WtJqfn0CKeAKdbNLVr7ugegXT6NqfqGm-AtIRtF4BqfyLVMdH38meVMbuGn-gtJV7F7r
nM-E_XIUGUVBfta1Z0W9MbG10GhQ4Kz1pHQ340mkzhlxEI0008G161I1_crDeVwZ0V-WC8521OKA12f8J52eGA02WGeI4nGg4AX0eK9Y0e6Apo8DL1w8D23I
W4W3bGSY3OWqeF8Wqe180o8DY3GWqW2U9Wu
}

