sprite $image178 [435x264/16z] {
xDb7RiGm58DXTKilxVwdJO-c6nbN1lc_jNS4J4BlvSy10000000000830000C7nenrxMXZPPJTvz2KKuD0BhaZlYYtfc15RScJ0eXqPYWtUNekxVaHABhWl1
7IJrq2YnKErT3TgLHedvdizWtwhNhJHABBWVsOuK-RyZ_yJKx5HoNLR9ZC3oSObTEAuqXRyZWHqF-s9N7NqHgr1e3FjiDsN5IcFODnlHakiq1Z_3ljeDyfN6
iB-jk5qhZS3QeSIINH2lD8RzhxMu-niMmzuNkqiDUxnXCUoFI-nkPSUp3CC-DfiYkIvjcHbdPrzjehRBMOPXNsoIoxECmE1ds4iEVixE4mYSPJWxJw3mXiMm
dwu8d6KOzaALnh2VNcAJpZ9Ox-nyIUKDYxDpiWbqpZASdVz9fJ7iESkyiNSckihZC1IcQHOd0TttVzlXwexrWo6SW5hBg3xQPvz-TUpwE4RFTjvD2gF5Fayw
9wksZDlEMFgsZC-JAgfktyFoULAYjglAnhQC5_RqVmY4gz9LPBtWztbIBX5sBKssx66vxHm5CNbschDbt7OkwLVhtLLeQYp3jepRpb44cV6KvlEaIHGendjO
RZlJe40nQikuxLm1MsksZDlE2TfdfbAQsyw0BP3wQB7RpXH0WMBBbl72leB2tfejuxPpsc0kJd6qs0lxia5XhzZ3SjkPvYwycB5bt7QEKmLA3J6bbEagB_W1
C2E5VH4RQYLU_T5YB-mBY04BjepFazPr_lclfmSjvBRC3hRpfeLz9QAy2CoAAStdIHD8OWYplYtZjvrh10KA-dxJjsLydfH2_EX9PkCzB9ydbTzlFbgii9yK
QmTZHjcMyTlE-FlDRPcckSO82t-_kMdTc-OQemqAUxTbUkzDUuqHLbw6ISnjcVwhfht6oB0nOtyHV-y06h2TrGjxJscTcQcjCTfdRFX0japlh6QYi8SXx2cj
twXfhZ7wV6oOrX0pDTRXHejxduUsgXNsiSA_Qebqq9JMvvcLdQv_iUOA-xYS5APLBTioNQfD1Dc--Hw2eBmEmlqGjan_L8F8QCU7azxxs0xrSAF5_Pb0yR5Z
ro_NjvyZ7MtZIsVXG6j1JCreAQ_BwQeGKcct2ipiO1jV-ZGqVjTKFtJbne8rFp0B1aQBZKBZJApQJYgd1oNv9-i1UrXppCIxTbLMJFmXX4L0upzBXxHbPfY9
Tqt36ga2KbvllyZez2S3FIoZbQDurpGCoCUgi2P-MHef7D2sHujdmqocjBG_il0ifGIEz3PMYQ4SBANL0REMLL8Q7upBiu8R4QjvFS0Y_gaAH3EbSPZ5TvSd
KLnsA6rDzh1W7qJqIrcnxiiiqDC75keml5XBB7_TvA9YorXqOrhJJMd4TBYNLTPNBHYATwTc9dx0Z5qXfPc6bczVvxBxnr2uwbKApL64bx2weu8jOu-PX1Rt
JMaotOyJ5EMxy4hq-6G3QOmMsuTMLNfOb48uZT-E4cyhs9YVdLzBKRDbxASqjHvMUcP7r_lmYlJyaQR3zR0gI6aQjimYdxuChpNNGIs-LWCzBCCfhUxgMOKw
AEPf6021ZcBBz5beQhOCBQSYYtaEht4HdezZotGMIccAjanjLyblvPV5NDIsPR9nPlezh2I-bL_R_g4UovRfGWXQ5RRCpiyc5lpAXwjYfkFOCfrbgeUL-Ljv
_AUbbdIKIOFE-h27bTi-eeaWb4e76ItkB6if3VUsbfYfjaR_V9XYThHOV_nAtvR15p6UkJNn8BTbEijCIiEVj6d0Ckl_cAHDQFgsZ1GsFgFco6CDtvRIi2sZ
VyEwwaOyBUPJ6hPbz1980yXqb0sTZjPi6PawsrCbRMIDJfEsZ3uqKF1hs38HXZCfrlciS9VE3K2pPykiaUDe68PB6oh79UqnWyaAP3sbQHVy5AZbKIehuFef
fR1vQSj9uKiBVgsKzlnVK5_Sh9R6zhffcI_bFQn1ziYoXJKcHd9kPCik3Cj-IjEtPUHqo9854l6gWBcH3UjxblUmS9KMrfJMS1eSo71k16lUIZ2JqgpQCcd2
UQ5zmekF4oItPV0p2taSNaNZZM5zlotJzb7DOlWAtB7OmKg0Mh-gXwLYon2bguZ07OiT-lT0OEEBsp8iIlAEnVQA9wpmlnQHqhhtiC0TYnsKNvDAcQZVYKhY
G6ldom_BRPcPRsNAQGrNfKJR5_OXbTg5n4FgbmiZquLcSRGumMAUOf3xbjvNNKUqMcSD7r4_NswGkIqJNtyhvsMBuRa4SOsHjIimWSnoIbCQBPRXXHk1r800
zfLn8J6mEsHkoz34DzIQ2bsL8pgfSH9R4lLfCJ61p6qPDDrJFX-UYxBDKljGxK-_dCw_UW-PZnQ7qMGiXVdXkInujH6hUp6eo_a2a6deMqQBm_WbgIBCvcpd
9TK9MX8QHEQZnJAqu_2mIos-Ud_acrO0Bwb-XiZSbhaJnzWuFwty_k32FZpMXzTCTM5c61f6vYcD9-JgqDbcnOcnqWTUVp1GeBKpHEOzB8ai81nBnhyH-emN
8mFC6Yu_t9OHoC2CRmA5_Kf3NemCduuOc3uqGnjVvDdtCiPMq399RS1B80FGveYvBLD6vo_QK5OMhkdRW9T4Xg7fay7CZ6nygIczNCo9bxlKm2biq7SIo10p
rW_GGMsP6kykKHIvcBFcY5wLoC10W0ba7q7pWfyHqMWn9_vNvkV0BYDrAMFCx8yMXmTczSu01TCe51YO2324xFD0ynxMBJCMfJNC-9irCZ0HO02PRMZsRPau
l4iHG5SwOM0OcQUqpva54X4qLzYdDu2zUb6_cPc-BLF-6Vsi0dx5bqCmDPJ2MFX5zPJsaHSTOaefXjDSOR_E0fF_pqQXsHyjnaFOeRuex1SIm00lwz3iRtp1
DsCYlJeJym0OvhLPIdDR9iS53fjo9erD51qOc9-EksnygPJ5rHYXz7WcGbxwqDoMaL-5IG13l9HFHxTbP18BRGDWsnNyRilWDibdm3obwT-MEO4G0xoKeVaS
5Yrp8RR9_xFRCjjzQ8UwDJ2Mzx3s6I9E8iGmC4zfkgF5yfzB69W-D4zfOzCiD44C0FFJKNlZYyoHQLTWBCJCKnfEOk1GP63ApDoMWLTmGziV6Ei3PEt7RHbX
5CGnCPrVXmDoMqPoJreXnWB8t9P1jvsBOeYn039LQFOtliWQfew8_UmgCyZisp9oZL5L1yPwbzXP7ul-nXUyMoSqHM9IRo7ZhNB76oqkomon7oMzHKmFcQ4U
5iUb9AOOObApnCGYmCFOCl4aYUc7cDGiCNra1dfO-VJDnFIHgTio-DTpdXBxCKjC7vboIiFxIIiWfg99OWQGATeoJ5IAdX3xiKXCOTsclOql-VIeyaN4321J
isN6IxQZ0MADfROyoRujC_xrdD0UYFrO9MO0cPujSmhXz5prUuWPGAOmMWoLluUO0MGgjWnGaCH-R1Bh2XyWfbBQMEqxY2byCbgrPQGI_xY0WKDHcPXzMsOS
PFnCd9ZL7fOCiflTepQ1TGLYrXVnoo3Z16yrn1I8cRTbMAlmWPsOsHuMgppum9OFHKdia2cjFR7kZPbZgiJizx0M9gREhCr9UzRBlYqJ69aoj6RrKBIVqb9l
0tc86UnXIMHIna8C4pj63olqDfO-C5btw1EpRyiisiissgpE1eZPj6MgudLoIOnYGI6cJyp-Q75KsseZWTNVDsObSo5cluT5NGlQyz-XJlND47DeLMNPXWHM
ml1EFhhmwwUZpeQKyR2od6Ss0CnwmQ-ng0rU25ZhV8ZvwRZ_AgANTqTPYKCC4dDeE--FWZUqMKkP0kOfhRTTbtvDNI5bPKpC0wsTB-STTu--TL5xgPYOG-kN
2oFRFj3QZ9A7s3izh7w-CBBDeRLPqLzAYnqIyvJ6kPwHRGYj8ScFwb0nC3yT-uMryJhjzhREzOA9ERIRSdh39R_j0u7LuCSKHFOXjFPVUtTq0Z0Cmq1qWCZx
hzi5388cSH3SZQ27lzre_G13hCkG6RJ__GSZG_O6RHanq0oPCvi78qDcqUR1o93zHViFviMe8_lr8M8U33GrCyqSckeN66XgPff0K_qKmqpDIXxj8HXeSYkT
DrjROA2fl6lRIp0QH5CbWO6sL05Yc8M1WUQzvi50omC3pNibWN5eYW83RQbIm43pNk_1G6ky0i0uj3mlq9PKIM2WLOM1WHO7XbcS5sXnOA35UM4M1mPQd1Te
SM2WnNbX5kS5MfmNQ75UeBtn-W
}

