sprite $image290 [236x171/16z] {
tDX5SaGn48DXKuFkV-0mAGnT6LlVUdRJVydrsl_h3cz4riAjrVJDnBqSJLiFF8lUX1dO4W-LpQPe1DuJUjbsnqUyQvylMtexyx6SEZj3XBDrV8-hXIgSxKWG
tMoxuwUYQvylitQU2IASxGZyNWx1dH5uDYuGuKEUYHBpu0SX4tWs6eXmjXFLbjxEV2pd6G_2G8Ne--zCc0LA-EOxatOhvR9zkpFfTWz5SkowCs6F75MYRnhg
iq0PssvdqbYYpjfhPznUGw4OkvqlSu5dumSxyvQZrDffPzuAb9gN_l0GnbZIJxCWswr2PKwNxdb8jkExeRAWIu-Di-LGcTlt9Ft_SLsjUUt83SKmr5LNBl__
k-c9CJ3094jvpns-fkmGvbbA6fTkUtnyjRBhiN4kT5g2xMSU7beOLW5ipM-YiWNfDgVdGTL-UMpzWL3xfR1TYGDt1eJjJ1ou4yAsJSI1kq7OnaWSk1k4xLBQ
CvrZctDbp_IFhT4pXba8MxDdB6JxnpO0fmosorOKNmhRqNYpph3AOBi-qpFgJa5YwyVNVxJyjgTxnl_jn6Eh1qBUxMD1ZgrIsGUsSnse_MFR9gDdK6pzRMzi
rG-qzOhj-WIeoM2hnyRveTn6TeNjg7h69pJwmdRO7-oPph3DOnTklK6uBsptSpkEeygi-7mujljv_l3gFrgTr8PZkn_dJw-5RZFqvmi6sszEBwybGRwIIc2h
u_lgLRlrWnp0a7p5zyLh9RO1O2lYU_FwpjZg-DwzlYsssgdo-ZosjK7Me0glRucj05Lu5MwBWro8RHFnbLulLPbzU6ni8hxAgtwqVeZhWnmfuYky5heLDahT
feYlyAhS-l4r-iS0LNWLsBh3H6i6jWQemgjuj4vycx7j6Q0AhyAjvJH4KeLR2rJjLRirG4rZRBJZgxtwRbz1hT_sGen9jbSTP7qnlIaqV7yFiWBLzwhTwlZU
bQ4_VJDwnlEgWwnxHZnwzTSo350DhzgjxXcXfk5BksUqLp_8_tNw2ltNcjipsglljjq_bYQxgKTlWggz-a7E-9-RL_u7_661UYak5_QZpUjZ-KgxPxHNt-rM
g6R4LtlrWrolC7h6y0gv5V6jzgg334Z4r_1gkEMSQiKgtF11za6zj4t3sDx7hU7qM7wzi-O7cO-lLbpl8kwMs_xZ-_AMNlGUPCFfFW-l6jDnspEewt3NjDK7
cGUrtNnsYwtVCpTrYQqFwZ885VSFtpDQSmcslDEyUaPeTR0bGDKzepNMOilt380jtJC3q3z4psY1szu3e6fXszvkW2fwXiMs7bJHCmYsVC_mOwD_UF0rMa66
UqQBsVRymqEPLWjRe6SuRCcUuVk71rLhyR6j1rN45yIscvu1jhtomqEtsFhnJQDdWB4Hw1bWstleyA05R7j0pu1ZO-tXeNDi0L2niH4O2B7-wRTdwhya0EAB
ZOr0ps3O0Zs3OGiS7h1j3m0LmnRe6Mnih3jmzuyjS7Z0naRWy81jU_pXuVE-901w1jlsW9x1i0Lw1XiRWO4Gwn_Wy81jUyQRTOQOiP7f6UPB0k3mW64Bz0os
xG671sni17e6s_Q0di6m1K35naPW8CJ6Hk3mW6rxG7onRGyuF61Z8z0p6BR0uG7h7m1KRDi3UWR3bW7rAm
}

sprite $image290 [118x86/16z] {
lPVjTkCW44E30yCmUD__TJVVYNKQuGnWxRRzrzj8vzfmykPS99mEpf9BiH8FPGQv82ynFHy7ZHVc8vR3KULQUSTAEghSJKodpvk0-QXvcSayAp1VDKkOEIXa
-hm1oeNCiIWYqpUllrnMSvXb2-V6uRRabDjSNORQekaIBMskX663ggHhPD-ymygz1B2JB8eAp4l8jCGYTxd8pO0d3qcFBP8meaLlFqPR565GvBxmZdcPBQzs
QV8mYyBsyQTPABV78lxYLW9krXpTBsxExRA8lrjoHyqIlEyMOzZajYWI9g_ORn4EYf6O6ia_pni4c6nNlqNXYoqisB5_NYoNRmDSpxmBsi8ZebOK83wBq1Q-
QYusPDuJC5lQv34rrprKJV7p5tPoRQrMszmjHxIhPglhQlKI-u7REszTBxamTt8t77NEQ-lwGTrLSu6QTt6XNA1EgZb3kK3TmmLAcokAvIArpLLiL1hpAfIB
L9YNC4KLvwNb8XEf_EFcLsKmxvTteC2WGDt5LVZpCqmdVD0c5Ml6MoHm5JPlbOjK_BZu54RbLRPUP68Beo8N0HXLc9wKkuszEBHcBNkYWhPyIQcC-tC8Sqkj
PgHcTmXp_LSMhTNgQAunvfh3zSXFkHuc_w2FIq2oQWEvb5dZnptPCQ-htEtbxkoOrr7kSe94ezm1vLhyy_RQMtFbvNwxgIldzWogvBP-vXRrs4BYjeZRaWZG
Rr7xKTHEwo7fjOMd_P3qsy8ZU-SrXosaviQylRRuBJ9UBh65MqIvVbju-4FIRmiFVqXwREctgDSMtqEopnRlGvBRuWy_Qd1R_E573Oyj_HRrs-9v5_biwNr8
mZ7N4Oz57blwBIAsJ9pNOqk_HPDiuKUDEiiMVjHWjaoqo5_kVm
}

