sprite $image191 [89x221/16z] {
xTU7RXqx38HXj5kMCrg-_zic2wRd78sMebprkw9z8DGCkxiTn-7L1Niie4DT8CEEo5WC0y6o7eOPk0G6sOStlE4DjmrlUCCRtl26DxpX3HVyWrSDXtjL3Tln
ereOFsGhXW4BbkNmHOCiXuFx9F26DxpXmynMm1PLmw56g8DF-xqY-7zxq3aFsvCcOUkLXkdMBmVZobJtOKJIlWiZ6h77uMYSJiEQJiFQ7eMPe1Ni5h_TfGy9
kpFWkxH9sFtwZjlqeU0ejOjPMDDvMDCQJj8IJijd5oQGfhimC26RWlEqWlEo2JXF_olWl6mApjC2piiKS9866mfW_Cr-JS09-M8Vmi2CZDO4dAB1LWo776mn
32FR4ZZO1J2MmmGv11jWusj1nEySWDjfXDs2eU285ymXcA61Vy4d7XIm3S211VixRC-FQTX3CCPXnD0z-IUCEt3OO3KSsONtu7QX3s68EkU38RFbOEl3OIVW
6DgwSCZrSD09630qzRxbOE1S1SC4t2ZW_1-HW8CjXI-Bj0Lmr8NRoJKmcZVUXJa2WytRJRWDm2J0ysGzx2T6wDimS7gBfQw6OzphUok6WURVQAPWGuUEzNXE
Cmc3OPxUqh1SwXcuTmavSwV59Io7OpsIiAQJhv1kmwBNXJVijV26DymF2c-Ogs2hEiVkSYqsl67_ZF26-I8mLi7-4M1_bx2zowMm6PYFuHpTnfV2Li6OWALi
APWQpXyA3Tig62jXUtSJww4ft80JT9k0OUMmZjEm9M4jQvXPs1R1UkzcOCl0Fh741FWSjY7C7i0qzYRsvCICNxn0DaGCjZNXUk9GX1vm2MsuIDg55y91yx85
dAE37OIPVjlgPcutOMPXNGAcryaK4wTboearhM4VRndipCAw9R2cXPkdXPkNXPkcALbT3wRFzGJs-VW8zg9-XuEjftlk5m
}

