sprite $image422 [181x276/16z] {
rDe5SYj138JXufVfbbVtF-qZ1RgycRL28yrVc9Y-QZDux-mbtwQRIRv5XqcRgEtKFcGDtZdQ-tbPus_P6_DP3Q2073tvDBiA_wendyUcANaUrwE7fcp-JSYD
qEC-l98ZjyTnAHhZdGvtDxvcYK2MpAo1cYNoPG4fDDb9JL7dsVNezDYTq7csNSULw3pRhbkEnfZK5PqVknCwpsw5vj_cwj4HpIWpTWUqc1FiFcXA2NO7D4zD
rMo2DaQ9iM5c3zGrv3aRj1SqIz6SXpispHwZbv2HLRyo6LMX6QnhTB1XTa9Nc4DroSPBIkHSVInu6XJNjThiXAwP6MGOGfP7rv03JM7CsU-ZIyX-CqdO6NGH
sKtAgEqw5f15_Ibq2JdYnTJ5P3NdrSrcrlXXD0l8QNMxbRNPVR6FEJzr5TgYJwZDYj1cdqMRLQ7DFgks2tGnMLEqsGMw3rcdbd-r9klpeYbwfPcHVQH0cqGi
91-8196TsYxG_gD1Oc-qcZ_5haG3drIp4CspkZyQvxWZ6jmH3Nu2JHIWnnXuxSDe4klH8pfDdKGJM8aMihAPGYjv9Lh9giwZII0owRRsvpB9gKCP-3Dw-S-I
CbE7DNGyevUIyrE7CdHtw9ilDQkQZuUclwHeBp1dr64-N0hqJvEVnYVGGiRz-G5LCwjwHgQIbMrUOCvD3P1UqVWysgiQ3vkXlOivZ_QcPaNt8HyZYqORyw_n
ERGtDYkQFSX-vCsAzjB6Pz2-YLdGleSPOiOkPa7x7cQ8sRSpSnEpek7r7Idoa_yD80xlKChyfttxi8qWXe40w6o10fxzT-iEd9z72hCL31PA5rHaOUwL-DPm
_YHD9-4jcwLcQ337G7CoCt-2Pgv833GdSqrMWRcww30u_YdCDNaPQCxFpRkbUHrLD3Dq75MqmQ7eelTVYixJp4lH_vVzYVbTqJNew6f-K_Jrw1o8teg67cX-
EAneQEY9vfY8NaUDZXT3kZ4QMj7GqBV6vZ0weCt3lkZEvcL8zqL3GsyhNkVZaY4D3GsTq4O7D3GqjBq56jhY0GqDRPc6XhPuG4D3GqFR4A7zwc7nW8Q6XeQ6
XePsEUuYD7HCHA-9wFU9w0VBD3GqD3Gqj9Ff7Q_bQ1hQSoqqD3Gqj1TCXWSqD3IqJoxGqD3GsqjJQ6XewDRkx9zFq9FSEINn2Nf4uJaiqHtz0G
}

