sprite $image315 [236x171/16z] {
vCyt3WD15CDGvr3D_MzhiFNcz5S0MQhIQ_LzgHc2IXufUQJaaPA6IXufUQJaaPA6IXufUQIaeP97IXufUQIaeP97IXufUQYaaP97IXufUQYaaP97IXufXL8l
E_R8mtxfI2k5I0ki540jibAK52jzD_VeM2b0McIb0EcKzKtRhHH07RVUMDyxM2b0McEb4wMlMvcrNjkzzUFbJfGZrM4eW5wlie2gz_z_-xeDE7S2MHGLLcsQ
VKvR1bdbH2PPMJjVggdhwcohpfTgm1vvZfLZgfIjY9Ei7BEeNCCzWaooSaoGSbISKH_l9QunGygGWIt_Mfj8KmgI_v2pTRvMluaMS4GYg_J2ZN9RzA6Uf64g
b9DrkfPS-IvmHXXMUTFJiKsfXWCGqr7m4GZlF1qVGGf0k5YdQYy5-rFifhXksve1UZPracxRLe3s1hLNBc-u0FBA5SXadOLbgTrQWHVrXGseREtKLsGa3P2U
LmHDA3qNWArpjVetQqRU3aWcgo1kFHfY0_Py1SPdi052rcbQbjgjzRH6jY9jFHHHJklMhQl3Ibgtr6ujvxfcyBeEdo0ENmCqe9rhtCWw2wlgiBQZA1T0oAe1
zTZ6HIDopoEIPiGEpmXArabQ_NLmwtHQDGEb_qfIjjPEaF0c2P2QIknB2GJHbW1XwnIj6e9RujrAFni_zSE5kkUAFOGAfghJgiz8hqSTicfD8QHwwOSb1SHo
TYOHyIIzyzJKRLLzYYg3cYVCJBCuj4ufRrLztXg1gWwjHwfjK4M_iTRyYkQmKWaLFvQbzdKD4-PDTHocl5gcsfzC-N4hF-xLgsMflORJyrRDj64CMhVq-c6t
pzQMOynoiROIOwgwHqaVUNtbvJihFmXTMFrZ5FwmsPffmSbQgSKGwYjQu2KZwpSlE8FMABNDrZAGHJAGoTfvILe1Gjy0eRvpxFk-Q0q_zOWqxlcRLbqX_EzJ
xo_7sRknDI0VHuAg2N7TU_-i6U7e_UEm9hc9G0sfNQlkY3WY3cj1l3_JOHt7Mc3fUKCOCufrLCNFOS4QgDRP6f_L4_N3bhFwpr7K40QfUIvHo7e4pM3qCeDP
x5OajSJoaBKYR3q22fS5i8xP6j1wBWWQZpfGG1-ohkkoF69L8A_T1EL-E2AkdGTvWvQTLxNky2KW_TvQBOkwRUjB-uYr0aWf09NVEThwJqTqKZZok3SbCIKW
wA-jOf9swsLftLPw5NKgMLKYzGA9yixhxE_UEJLGe_PhwReTLfDMubrSh3qavthJ3ql9e_ZQAszdNdEH7yxgxI-zn4jALYfaSt351Ncoz-UgofRo9QjN6-cm
zQILsr5J-RAL2jdL8iuwqmMnb2zRMUjh_P-qSYTgB5-sijPpf7lOAbG-1YbRNLgXDy3LAd9xNwAHcdELzelPMhLlLBOw2lbSrwPafP55QfSb2nzN2shuk4yW
bBEL8m5YtQXiTMXvNUMJjONxxYRGxauZfodXTrOjpLo-RBtL-cVX4L6tJIC2zSCT8VlLWgOLgEks5a1KWFpA1IZVM8tbUxMwbfPl_0mh7SfNWEyGZBDDGjQ0
slE2f0bvd7cSLf9Uh0xjjMsxt24ed-OIOTmXK60rto6mbozR_LeUKa-vGs2NijMrRNb8VLdNVB-kGkkwTAll3W5lLBkLbzP-pX5WkT-lifspmu0oPXJfMF3g
sAyajLfPQp-_9a3MLO2eRCtzsTiYiDydMBOb0w8DI4j_9bUssilNRcMjtSelqg1afStDTmWgvLd9QYfVbvMrTcjla4A-zCCrVBHJajwvzBnHRhQIr66bGZPO
PzqVPgdVobgxbUC1AsrKjvMrXhd_F2jlLB-LjJ_V-ddqleIzVErMBkJlR_qyS5PtbozRlLe-wKonijHkzHGoNsAOOUMDQhUwbfRx_gbMaXgi7cqB4-x1kCkN
hPv2th559rYvV2TOISjLN7McbQGph5p8DOXEi5BvJhAoTkBNvhDqdfMrqx_d0czKU_otkhLNgxWZtLfzqdUuiCkyxv7oV_DqJ0C020H1i0RmhvSI0Kp2leF9
xytzI8LQRuNvtYCXUwlCrsgzbKjHoFJmKEDQFrGUiZyZzQyjv-krOQdNHeSQdwsIvaBs-TQrFjz-o4hQrquapONiXrhN-g7sGnRIv6jzldMjpxUlXTBuR2UG
9b_hXrhN-g7sGmRIjDRdcmtPvzlN8casP2djQ-rGwo6xeVQrJjh7GcfVwwHzhPFsjKxQnpfgN-kaVQsJzh5EsjSwQb_hf7sja_QnZjhNEcbVwwHzhPFsiOxQ
rpffN-kaVQsZzh5EsjSwQL_hf7sie_QrJjhNEcbVwwXzh9FsjKxQrpffN-keVQoJzhLEsjSwQH_xXte
}

