sprite $image273 [189x243/16z] {
xDS7gjv034NXT7jQPl-hJHC_Xw8WbFAk1dmMO3wk-_xNzVQpRWrhdz3zezOS_PZp03hyRdZqXVttTLsU7dnP_lKp-ExqLaLwh9-lYjhHD_JW2_A_N5yizC7q
QvMP_GkX3_0r-1TsN-_ZqUljvE6xYrzLx9z_vkdzwsPPQllriiEFhXlmwsiHkvN4BwdzmWxUz2vUhySE_jEdJrmt2Rn8VuF_QKUVmwyJyQImttztsT0Ks4t_
fpUiSleE7dtcEQ_KtoyyUkm9lEB2QGsy5NqUO0TF0Znw2eO7Bvk-WKUFFO4NJDzSlM_tyRhfc-5DRsL_0tNJTqTF2Rj0tmsFthLNnQE73zqPlX8UFNpemV3W
5VfkUFI4FHXUXm_r3Ripl1oFlWLsTtYTVg2t7Bblr-F7G8yVkMClX4SFdw07TX4UFNpVth7JqkZ1e-y1tHbUYqUF7tbWb-FH-_bsFNv22kY-NOg71D-dOw-5
fu3ks9NuEOVlHnxOfVWvl607TZ4UVjoiXvyfEdOztahHiUlnLjOknAEdM4wh39uIz49u2k3OA-BZrhdu9RVJojlrUFGhHQ-6Xv-cw_4_oz7rTl1MGYx7ewT0
NXPFeLjlfpnGZwS7Bx1R3rvWjnwym6wTYAS3xIImbzJFVR1-2phHJcgxNhzbAUrw_PQciklrMzuuqKw2zwfOl-iac5sctzKwaaxpI3gTIe_zSn-H4FxqzBH-
Lyq3qtTowpF9bHW40l2W761q_zDkqCjEG-iDjS7zTwdsLnXjMHx5ifiDwJFTj5qiozVhxVjPZF7TxWFiVfZRVy8_1Qsa6Bnpz1xdGygbTZxS30k6lvt_iVVa
jXdoCPNMcRNDYh-hicplOS9TgXqjFlhQHHjUVAk5tkI-yC9Q3YS4qUDsVbzxx2lVAH-ExABFmj6mtpRVbdhvU4QGeFQvzxpMgvg1WkBpjfMrMjMKG07jdRQq
LgjwSuA5CNpS7AyiXNLZ0WPTV5sfPSMSEJvjVgLMEoXm03mxogACsiJM-9-ZZQZZjQfHUtmc3zVk-bannGTAQ2ysYqUDPw8gwa0UUtm7Jbu4u-nZi2c-4Z7K
Yp7455_8GxtxPy8d2cAtUJ77s-ro6ECZHQoOFnFUPJ6x6pR75x0P6JN61rUV2QydiJs-eTNeO4tXBJ5N_WHuXl2Smizu7okVZEy2tmsI7FxWlG-PFnJF0rby
3t_mCw6UYMS10-0l5p-J-2FnEltDnSz4FWllMM0zjlXuYVVfI-1x39x8l_lzt-aVYDVePsqEaMRyl_goduGNF4E_-40p5_woxn-7Pns-pAkXQtyx2HzMy4Cq
uHWYNSHFldmWNePgeCwhkSoxVlzGF2lm76FmD_7fO_53yR-cpQkvZ3juh_Pu7eghIJUlvk2zOlWeAr7WUup1tJxvrbfEFvClKfizVXpYNvcx3oLfGI08m7Kx
GP3Pu_tVzdUKtl8K_Ts4zkNy5TKxXLmAcwtX609lH3cUZCVDbOLlbTPe2DscdRw8H_wBxuKzyCzRquMWN8q8DS7lwVtcs0a_GhTvQoY685ls9lZV7NoFrY3q
y5F1RzdRuEzv_qrnRXyp-XcLhzkRuVCkNkTuX9csAozA5y1R6V8BF8BAL-pDyEZDTcj4gdQkLrxf1Ro-ZC_xhL7donhVLIklz3pUle0liqRO8xB4XrhbbLhX
eTzj3MeZjShJmjxHItXv0vytyLrPTW_J-1Gs3I4m4TNiv-FH6Yao8a5_q1f2YfrRug7VsTS8QkCUuL8WjEPFO6-CppkxOUZ9CpqhZzRCeqoNmTlme4LUyF2N
rdGB-o9DyAxVsihpU2SgdjMigThRut-tAi_Z2HCBkixezw8rAYVXwxqfbRyDUtVCUX5XAQtfWoxixV7GLr-X3YPVUyWnD3c6VeONuJFnLgyyapym_zocmeYd
j4PvOM-Fh_V6RAeybhrSjJ8NS7GxzB2VXRTSQKrabf-fyaoZtb_2ra2OLKQxyabuf8RlIkL7l3_GuvYlx8PTpygdu_DzzSS8nMaUmeasJmyyjcRIRzevsX6y
ULJjhUJr2ootFvLdNBo68KMeoc_XxKludikKnze_3fjYQGroFZxR8h5KNg0XnvSvAPV2Mru-sx57oiJ1hXqBVt5yQJCgF_4n9w-6puOaymGed7nZGkLZY84_
YazluosdacnZKkMKxqQaCKQzFDuYy7yos8CSoLFuz2uUUaDYnUuBtrqFRnaBdqeioGhV3tWvb3uT_USvZdytUVO4_BZ0TxxmUYY7yEbZ-9nMiNkKcPrjI7yi
gIa-ZVygBY_rTulA4ptSXrWwcEFuxWjuy3runf_xE3vq7y3d0M-LxXGsx1_7zrt_Djuo5dwTQPTlbhw1J-5zV09-9z_1z_r7UcEDyP-BvPokZlz7BRdeEWw3
K70ms8PSQVl_Vxl2A4dlljrzZoJt08awHWapYxCudejVl8hli_-vE63FXH_5syFUZb_6umVuSEoIld8MLl8tVqu-UKLUBc7-Ftd3Aa_ibe_8ynlvcqLMVqJU
aShAfEIz0TBBmW3QV9SJL-wdZfvvJEdNI2ostFVj9npdTuCS9Jz0j85cLn1LWJJENkPH3zN0Zfeq1LdLp55MyVlb3Qje9U-G-tF9dq5B1QDbbigILyrf5goz
Ynz7wBfAG2uz6hhXdhmWxqX6nGCyWvwpE6yMrbDHLzQULvFCQHfvp2gmTPFhazoJZttvG_Al0pbA7aQEIcc0UQpwpZM-3ITKPIdVw9apZ0ttP5i-mh28GO_K
pKFQ0aP40z0HoPsJsQq9u35eiUXOXDplMpOV6yGEIzwH2CLBthb9povNZDwkF2IJMChtT_BSMBhlyBOj7y8CMboRztY73oKdptb2wzcgpKii38qGHjmyzZYs
vGthz5j-r73CbFMCBlIdRA6qI1oyZgIXULWivlHuxB8jxqZ3J_dJQu1V9et-ITP83ERbEybkXxeaw6EVNVaGQ77AEwZV9lNXvsHK7fbJklhCUdPw5XhXWcHF
WCShRCeRzDhLB3j4e7ckEGjghbIsPKXheB8cdKGQ6gKjmgRxllrKpHzNzVgPgskfrZsIta1qFkLHhyYANNkzejfTiJKpuNNt97uPxfxdDnXUDBeN4H_RjGza
nM4W2CFTFIEysVU_xI9B85mgth0uRDA7Af9-faWEypPvt_yvW2L_0YwrVTxkoqdn1bwhBuG-PVEEZeyNRkQ_q4Vj0wf9D_Maj-fIJB5yivJlh9jFg7OEbk0a
d99bCgzAj_bQYfMRFTxKPPMJT4mJWFT7xAGPG5EnPD_v4-bLzQKtvcwLMoRHPEOGW5Ux2KcGgAQ5Dq5vo7lsG3bV9bDUD011ESL27UiS4E-sLkepIYRWmwdV
XUsURQZtz6Jo_VWhYiJpkMSRwjClUIb-ZIJUYRVZt_Dnl8Bu3OFVNczXlTwAr_Ruk7r3F1_fJtpFYy7aW_OZu_jwMVYUhm3yQPEFsjVrgkadJpv-qpF-aSML
iDIJNVlHyUPTULlCwI5S4IRcvbOlCxNmhZt5yN6_hPHcTpgwy03kQ6mFL-FpfSz_AprvOSlobCmjaO24RDxEKGXfuKnzwojleR8Xqh3UL48rdm6TAU85claF
Cmp3C0p3Jm
}

