sprite $image184 [169x243/16z] {
pDO7ZYDH203HpJlmEzp_j1EPL4eM4kwg4pnzCEtppiLBfxwCIkwCpzBFZ4hDz5CV0acf6HKJCvcCwQV-28GifofkIp5rFtK5aiu_a9IQqKZycipxcYozpyd4
pya4J0lr2DGklS_9Xfb-waCCv7rE9cQo0QQU6kDvcUmO-6yyrC194bBZdYqda-Ms6qyIoxNlFUZ_k6Thsm6rJlqr_zGhtUNar9lG2vYLUEh5R42lMSxAUvAG
zYGnxN8ovM-z1_rp3PDfbvEPFaIvjhq7JSFKA-tKcOZPX3gMar1s29OJQJv4Z5s-d6k_BS7tiWKzmZ9rfbnEHkX_qqbY_kKaLBgSX2xDIMA4PWgdJcX6hBNI
DdL2Qnf5rJ3PGrH5rPmaLhOeQcgMavKDLC7KMGqSyvUS9499pTHCdT2Le3gcJYWVjQWA9g7DLPrVJa97LhMMSm3AKvM2gGFQcF_ur0cTecPDVGnAQlQdFWhj
doeonw7z-NCvvw7zKyMJD0zT2UfLKoUqlwfapfIvK6DLPqvIvXCpTeB4DWX30TJOh4Aw_tKRywDWfmqUF7GCtKZNr-XBu9nl-30CYUf89diJlafFrA1sdAeq
aXdNPVc6PXfHVye3cRGjonTKBLtK_rxrPVa11VNUg1hVwzaqe0Z0dL4rVYIbfG6z7rKQVX3v2sY-DQg6CuMt1fIPRqHrVDKHqHPKX67fYkh8aPHrHyi5bAYx
_ZpCITRaGqJDJoWNG0ULCe-3id_9ec3j4TqQSxGMz3ggfOS07NHUxZYyudtlVq9L2k75g89m59Iqo_Cdecji3lmpDL7BEH3gpyqJNZlNW1RRHVt7GpaUe6lv
w-nhbvhG8xLnLes4fjK3YaKYmdl3SmlQZkfuACAPZr3_ZkXs1OMq4TMHKDw1JW2jjGy5_1FQYYf-70ubBNQ5BkaTqHQq7TNXKFWsLgWjK2UyBel95z3Mg1eD
HTD4KMWemzGmWT-6jgCw61gHoGyqBFkA4JtLWbv7TGYKkPxea02AovrrI6e7j3MgxaEPDikVLk83L91IKoBQWFP4zJuqE_tt7MRJ0PgqzJTfG3kYUX_AmUWG
AeMc4vJDP-m3wd8RUZsg00IuOsKTc2PBG7CVeUBq82tGDR5SGQ-ZoiBKTyDdsXnlMjoybZSMAm2AsBwJcoABN4Eleqg9M7Bcdd16uLMbc4qdgFxgrlXyjEzD
1PMb0qg8P7t01Eq8nGQxsz1AfLitVCIG8TQWyXTK_njq6tgiFzqRJvkMj0wXzMyesvS_y7seKcz3sTIf6LLg-Hig4IFfDhHIUw6C7_9EYTM5vVaRojHenxxL
1wKjrtehWjrNEuN3VXWqTq2phG-MsZn8eguq0nJdfIrxMy-XEjTtVFf0usDGp1gpRtcjlLHFIXocW6w97uCIA0HpVSku5DheaCeYmU2yV0WQQiCGnFNdLwvt
EXRyBKz1KM64DDPUGWm2l8k6yn5e2W1jzG1oXrwAcao7Nqxy39GipiPw3IQOlLI_mqxFomUWk1hdqn2AzS7u7DUyuhny0kf1qnAl26ckk5CAyCCZKFIoKv57
I5FjfTEWakUWR41xN-pmKNBszThkONuUYbRdzrZ7zIFQJo-nATi7eF-UyWbDi-7kQLSjDrxd6Q3eTG-IGoGDTFg6Mva1Yf1kwALGdpgDzfhnF0LKR64nUWbU
qF6BbaJcW2Aan0RbZd2YWJ8kStD04T90xocLZrTv1dCEA59fetODGggTFX4KgLpHI_MEnFD1aKg3SkjBA_D1-VWuX92QmDD1SSXhkP5PcqLcX7eujTmniSm9
JNLqwfeJoWRGE3jKBA0qFJIWwNbwA1LdbCcXE4LTblcXukoVTkuatL4WXW7m6cFG_K_xPlTGIXidWDgBqXlM_qTPpXoQpvvGzwqVL9G9vKpeX4xeX4xeX4xe
X4xeX4xeX4xeX083e2Tq1q6tZb20eUkoM3Ce08P-E5Ef7eh8IB2CgeU2e4HLGtFcmzQRVKhjlqE11Eh9HTL2WHIwcX5L2cLdqdgYog6W9AqdgGmA952I4bK6
HGBDgKgeWr9hVQmg4HIeGis6LHfe1HH91W7vY7eZ56Ke-vXAK06ptFeOXHkXEoZrrlEe4lJchkUjPz_WlnmAF0lTVBN2g5uAzHsKKfdOnxUgyVqhagjPRpsF
GknRdHEbAh7_yrz05So0ilHeL1VxB9wCoQtFpty9ltrFgOm9RlrnbQBsvw0u1NNBVDnw3PEXkU-wrZjEGxdgZrU1dMazS19QNwNnVKyY9aEzk4hZ-vvKJ6xz
LXpLQBt0cRQUVTpwpwilOTQVWE1Hy9zxMJ8cy5ALBEvbtRgIwbIZKNsvzJkkI66LdcmzBeez-LZKgFK2Pd5K-Q58kVK0D5GUXUzphq514OvglVL8ebXLdx72
Z8AY7zNZrg-8wAWZsjRZrYE9O5LLMm-A_lovzNMdUbN5Yxidc9fL5N0va-E7v--FoxGZYNvKLt_SUWT7J-NMvym6e-gRExSUaJuNrJ_CL2O0_QZSUb1wK9U_
MuyMCHhLuMd77LqoIB-50NLqohzV2qMt47JxXA9XR8H-sD4p8xHn2Det16sRWEvedoyen7a7
}

