sprite $image308 [232x334/16z] {
tDW7aYiX40HHFBI6-r_tctMzha9UOlATWOhi82oiM8y1Bm_xfmQssErD2M3Dt4W1gjXN3JdJDCnX7szizglCVhAk9rXB77IcgTiHXTKIRMJMCBKUMItH6k38
Sy2PLZl9pa_1R9VeaTKIhGAEFDXCYrsdfvqSULThaTKIhS1QecNQCFLCMItHMcIrH2li9-j6PhL4wv7L4gqj-M40dMcnHnXfhGy3vanZjmUgW2Uxy2cOxV5w
MlN8s_Sf69izJM4DKnjvWICFCzFORG5jWGy3m4ophMDaLakq7bajqIgg9Tg1r19jcvoMQ8Sv9wKbsc6R_z27QTjySRkMB3hCDz2M-33Va5koJKTkoMU48qy_
MHUkjVGm7NkOZjcIdu17tg_OJzOHFWpqatMibcYi8qzZ3zEnZZoDrHADyM5m7EF3u3XMIpHMIpHMIpHMIpHMIxHmLDlnatMibcYC3uFZM2tHM2tH61y6nx6E
F6rNdyzNO0_JiOuyZNNaQOmFW-DOBT6mBN5_sRaJtSPX7WZ0aczn-Fwl-n_TjBCDdH28OalXchZIkn_4CLMvy9rpa91AwuH8j62oVbfs6W18j63IoUsFWD8m
BKidjpyY04G2jIoBVqft9OM-kGQYJFF6KQgQgwnG6Y6OT69NAX8ac7G2s6rU2T6oT1BLFAQYUgmJFSHKe4SxYJ8nZQ2aitbCgJpKsJYcedgYizMC4UXPpfOn
fV84fnVJpsnPw_HZ-i5AEjl4LA0dEvl4bCgJd4sQLrJREa_P2WgqXVFic5BPpddyLb1KEtFwCUrVIUUPpIlGriupPWoLJPmdnLIqKQL9g3awfW9jLVEj3S-8
ARHTRH1AAsBQgv9EoF-b5J7jEvXqVadbq9WAj0Sd88V6bCh6pehczQMYseUJqfhcxLb9PrLCXTAMmPHrMPRYE_7s6NEY4dDENvN5TTRF66dKidoY9g7FdFKn
RT6ocDBVDJvrAl3E6NEUKirZpl3KgVg-cCfvIepflbR7gVgccEfv9JcPcdsd252_5MpBJAFZ18VX2p4b4msPllEd1UNrc8egdUSon_pp2hjE6pIHrs8gq5ET
86txcIwvEFi4AQoNOWhLSvt3JJdyeU7_oaNLSJ9dhpMlwidE-VxoEgO9wZgjbCtRexFSc1inekeudUOjqf6p3Fh_oZkR0j_fnxGJ9wRqvLmvGrvmEZ5jxiJo
5KWk9rvmkZ5jxjpoToAtFyn1AvnEJ1iv-LScE5D-Zv6oBSi6p-bB-RA9CtCDaUwTiewSCuwp8gOdE467RhzCsAQSM9FZD5AdUKzsRXoOEjrUvwsitqPMSPmL
C-O4vvGOpp4zgybnMgWJqrET0-Ef-QbpS9miVyR8UKuRJqtFot5MnFHm9-DPuwo8wLdEcV5KpGSudHbpYfFnpFh_6j_hz6Dwe1CcdhoMha-P-GMdknKyo5c6
wN4y5VatRDgAuWS_LZYThU2RdPZkLsLXF6zi6d4NuSLnLiJqXkFBAkMIVvqKC974ovHJ6kSDoYhkVgWsfZm0bdhdbdUsDOodEtgoEiwg6QFu0ckjKyQzoqbX
FDsTuUmuAsDwkqjMvsJoY3BnTCvpuJYhOdfJrZkHpNxSn7E_5dvLfTDAXUzJhNMo-upAZwSAbxpMIQbnGespld7bth3wVJ3h6vqGESofsTx9N0bdbR4ecT_x
GhpHIQdlh6zSlYlVRIKApPcpizPffOxpVOtBYVfhAp7pM9UDNU-qKjTPtxWsdjnAPF0jUvsgTnBw1YVMCQUKf_AWSMqyCVxzPCpP3AAtErc-q_yNfn6xZMlZ
MT9-ZUZFIILhW6tSlNZ2EURhpOd9_AQsSUbYF7UPY_Rcv2NpleffJ64VSteELfatxTEvvVtMiurhf-ViHBCVfunfjq08SMPwYhEORPn-C5cRWOYvEMOMT85s
wMGmJSqxZRlPBHtO3fdAlfo51bkZsiQTzqvbj-5s2AQiNfnS2IhchMnyLyesWJ8yEAqiNE3Ud9XthnyJtsNtk9Cp7tjqZdjALL3rU7IK3tNEuFjNunJZr8zp
si4Egydc2lM1pimcl5FP9MOyFyyvcWyO9qmy8pWduzJ1YMTR9rvpBfQpcdX6SDeFmCGpdjCsxXRBkUY3naKCvyHbsstSGICu-G7HtSOTIWGdILdLD2utmW6S
kqUJu75122SF-5QRsWcgOPpp_bLruqOuXZFllnkRQYHdSJO3CPmyY4Pi9mze0plvtepOpetB6TafcSiPs8dCYsrW9mPB3-WiER5hZokqTM8svmKHdLisnpy1
dMKmz-i3EZ4bmupd79PacC6SjbODxkGjfVZE2HhQoPEy-Cwyg8PsicNZEyUY6jh9OCPtBj3OJWOpl7Cegl6TULLMNESC_HUSZZACKo_dvRoSb_DoNixBUJbx
gijvEI_dvRoSb_DoNixBMVu9fumfjfFF9ehlN7DwuDGeJZuFPz-fa1XEJ2azSQ8KaG3E9QLdJZvIygET9IUMysY-3tNQv-5WjxwXye5EpXBV2Q7q4vqhWNGw
qizpbY4vJb_QlrCcwfuxLPsOUivEPedl514dffqwjvnS9uiqIZ_0oLdYEorDYf7swSHCbk-qDCQqQ-TAbEEqKXFJRfrsblXEqgoq8wSVJDzfQNHtvEGcxnMd
EitRcNFDwKMdWZH7wZXRjgpl5D8UIDixUM3milCPZUwcJiwI2YTfJamREqjE5KwFnZTREHdC6gTBiz86plzsTnwu3GGn37Glklp_k-u-fcT5X9WWGlEv2n11
3LDsm4iCpXvQ1TKdBimUPnyRChNxzCDdbUsVbapL9-eb7cStF4Pz0e61DRSZhNsyrCzJWS10PN1sJwRpwMKJvIKcPrUrPFeoFUy50WELmzaTcJxlLP-Wb_YS
FJ2yjxkk2WK2Wm1dVp-ycJxBy1A3imTNmKc-GYnvFcVtEfL_qbxYS_R0BEl7AuYN-9pTbAb-xGhmaZ1dw_8sxezx0I_9SxRs9Mr6G60GuEmlLa7THmWppzbw
hevpZNi9mTcwdEGhsV2Pu-moZdFrHvRdxEij832mV8NbxDqYKDMmpondoqiIjTmdEPiNfcfr-2NEFegpVIz9rgPOpjQIbwujoTaAd_ErR0nlWBCL6CHhTMmC
hy7PXfS0CZKusmuCyhKpPEfnjkyblCTSll7ZtcPWGDIw9LEVi-KbL6tBX57TPOJFG2rt5epUIlwP4YOlK_cdiUH1jJ5aAlyCU0cs2lgSxOyiHMpLuEn0O039
L9oTz1AUsCJPoS20NmLrPrAOFB4ffqvw2KziogbpmkI9xNfJ_faB37YPwlV1abx2UupyCnaOyCGcpavw2Kziukoab_349ivE1GQyJ5NNEx9UmdlCpLhKPoWm
u8cjj2VamcUUs6Pd2Ne9BzFIdf0C37YPgi-Sb_2heAQrfgINyCGsdsom3GgJ9pRr-GzhMq2VIEs0FbcFqR6boUB3Us2THMGAhBC8iG7hB52h_PzspJC
}

sprite $image308 [116x167/16z] {
xTdfbgGe40LWK4IDPTx_SQV1h7jIJ4ew2far_dJjttXl1dfoNC-PjzMxeUFZ_ckMaUIoKp9fcqU9yvR5hAxJ275QamXqZtv0aIyIwjErXb94hGEAnA3M0KLY
KEjp-r5NG_SYorYjjTfZDTTgtuzwmCkG8ik0muFxOG_ONcGTfP_iZR_4-dYjmI9YRmOKsQ5M7usY_JWiYhIgOKYiPQtc_R2ROZpex2ABcFR3FYo_PaoHY5LQ
JD-nI9PZHkm7n1OpR3sBn8pQZ_SPj1-d6R8VnOpOZt965batVVVzA6V4VfGpC5RCcFsecqyNUJNdful432mICwp8qfptGR72dEQLXyGAqySS23qVA-Pr_o2e
puaOn4fCz7IHC44HqsD5bYPKWlfOh32PeR95PH632SfGAubOp58rY3RJK2kAj9g6MY6QpR9MGwm6ir0xnug9XTbQAujz5e9vLPceeuWX0jeSCCdFPkUFAXLg
do9XCjIcMYsYggY-cmIreLQoYBo6EUoboMsr4Xj4URtTjkl9b9Q0RKNgFhbZGc4AqvtAB1PoSrypoTdaV2dyJS3CR2TpkE5aegrghIHYCNLFM6G9RjekhziR
LNxVJEsnTsuY5TsZQ652fOyg6KpT0-lYdEUCGOI9tg3-rEJ5pKefM4sYGZsPPS1M4pt6FsBUIbMXDSmBNSnAm4OpP6rECgtBiQ6Uh-OrOBAQyaln8jwTPjN2
17fIZMOgSbPsvubNirfhkwau2RBWcysordPJDzByxvBhbEMm_1n39TjghTdaMrCfk4LH9ujmS3x4dKMF5rLftWHCT6Ton3dEgSxZ8n7DqdmvunjKkJFfTPD4
dQS842tCRrHgFczdbodKYHSLBlF6HAtK-hhL5JV9f7CMO_vluFI5JTjC9herLONpzV1NkAXpczmaclv1rWqcyusfiWVlV7mBL_U3qEWIVfnyYqYxoT-QIhFB
io3SmzeqrOg9qijKpdyMcNg7evtV7uNyffrCbTKxpAAYuRWa_wgJ9vSdi4eNKpM_D33JruNDgSubAvHMPA52j9ieSgSSi1SvmlLO355X5bNfPKvViQaU7xFa
S8yfUkXeJg_39hwU0dH3qC-OIF15yLUugFCHStsP-wjFXBiDCVDs85oI9qr8GGNX1ddUZFWuXJjjyhmf0N7gvgBe09FpOVSQXlYagIi-n3njiiSXCCp4-JhA
L9wn7Cq3qMPkQI4d_ZsJsMvknmtDauup9vTc0Zd2n9F7M7FQ80uoFGwwCIPY7MdEEyH1vhoAoc0JuaXJ_eNc_-R_vl-cyjSGZJ5Luk3hp4zGRt_tOHFlxRoP
j1CzQkAzdRS-QOVQropVsodVAQR-Pla_2CzzubAxcqeXSuN9H50xcyhHlSqfsKBjO68_FfhGK6idK_SPMfajLE0zJEK0wseAhX7uZqqL55dlynAmtSHxdtMJ
gBZ6_8_Ln47tdKdbInSuJCD1TsTAaInKc8Q3xiOaC2L-d55iEkXk-mHJufHXutxKJGPpnVE_RD-FUfyCvg9oSvygs8-MFgl9SYA93VlHsEUdMXbzslQZtYUO
4a_3pERzA8Ukz-mFjHBwjEn7EKpqwPvzmj5dmuD0owmCzSHSBfdOlX_bp1lp2wqV2laB3Gy2pHEeKAzuRhlbGQ1zOd9gBrsSyVNzCCs4MZy6B88-A_jXcdc_
rfh_gVU9_R3FSgxrXAFFodwOnqUkrOe-Qm_AzfcsZxLI4eaDHTfgnJsRkQ58UwtNW7VqYGU1hkFBlK6VZGUTlLQ6Uf34nODoxmcejRXdNny47gaLzspJGMUl
DM-BOJ_iUvDZPUj-sEvosLosC434NIwRqo0HUoCgVeo7MWKFvyDcsVjM-IS
}

