sprite $image271 [203x277/16z] {
rDRhUkCs38JX43C3aDJztsy9C7mSxy7z5SNxRIJttBu5OUdZ9sgjsQFMFlx9dX3_iAVPoze_FOxdOF_GFDhfZvALjRTtjFR_Wq9bxmnfhvbFadV5j0OI1gC8
s6iDljJUJa6Nv2wHz4neVyKWUxl169M_H6KUAycpMDUVEAqaxpQOne9iIm9KEIDpfpln0lCs5eD0P2BzCPKKHVHLU5xsfxyLRtJ8G0ByJAHSN1N8wQeGVOpn
XxLfxsEnSjHGU9AxF2f5tydTOsZe_mPZFxSZdvOL4oDMq6UGF3dgOuGxny1RMW13ASnAaiap-HdBkbmIUnyhLyneRsTfALbPXXMvEUTJAahFNFB4g7iCUxqm
xVujuITa_tybzu_SdRuATm5KMLBaxiDpDC6tigJYlDQsnrXK72jGH71Tehnxv0dhpXXpTaLxQRbt9g31OAi3WMW09JzVo5wKXGZ15oM3ByjuORbxNS2dHSb8
D4h2odU4UL9M2YcIeX4B4ztjrUwt6nT-I-n1uTOWCGJsjZ14UbgqBa-CQbbYpjUM6_Sa6Lb122CoYNbtT-M752kHuTvN8-GQjInz_lQb_1D734ybnMYmlUxQ
bdEyThHD6SFPnrnnMVpLkjmd8Iexbu50EL9ZXQ70mlIGw4NHSAN5UopFYoDcDtuBm_BJQY1vPrdCg1KW9pqSI0fpKvXhp-JafipXC_p5kEzOUHfnB2iq5AGi
HYMeTWMU8t4mN3qJrxKeCpGy9pD-iRHRnzACED5uVW4q40P9j6qnUcGEYxuJOgHboEVADVbpOp62U8fd9csViPNH1NVQjb3mdeq1Hb9cPwI5OxQV6elPbl0n
4Y9lUs4eAmi0py0baIB7aHJt8IN5HwyZ5hF_q5WQmBASGtK-O2qvb6hjQPiID7VKgmkqB1XZT2wAvaoBptW-OkssHpwj9BJ7mKfOCx2Hwr9PG9SfAU5ciIWh
HrUCZ34MPGwbA9wFs5qdh0HdoMrFOxN_A4YOLcQKfwKe89AI0MFdxBCiAOgdiTXD9om59JdRWGPk7M4yJtkJV6NqSApBl5UWHZMfcGtCUGst-q_OFayycFEp
AMpCMsbCde4fMK4faOz0JqhtlYtqULtXzvym2ZHipEyK82ccpBn2ywZ8tfrz8T8oDURUbeMxhYcx-plC1BAH8FRFCoKdOcpAM1Q1YAoUZUZzS-Ux9uDp-fYz
NpDuzxA055PVne53sHDX8hHomlCAOLEwVqHIoiAnbtukpHN9kNbPZ12f13ns_PC1WnbAaHwvW_kjMDWKk2KbWsOrg4MvVFJBxdtW4n94mAmOV4m4rd0UAsef
SNtGFSgI54GF-wHGFYiLPN9S_TPbQO8IGzO0o3EOTXwG1CxxlGDkHTaMU5zj2yTKp8mz5kNoVZsDnRwR0cwAPAIjshvWO9aeDcLDDBdBF2eX9HcMHJ7cjdXC
xqc9TVts0lwD519Rmfh6uq9HmBCduWSy8s9dwDLObb3jlFgSoCzSbXdN-FYzclQtK4H8--Tt2ashkXkCNe49SGjnKqQzkyoCmwDCruXhkJxko-Y4gAtXLufj
IjO8awjv5c7h8g9tAYM7KX5vNv1wu5zs7mLo2CMGJ29Gb7sJcbPi--iBs1Gt1wElu4L13nuAYtA5rhgCeHifJZcJeg8y9iFpE851JPxbHwpuuT4hnA8Wnd3D
BDHLbCvhvVrMYZk9rF1mjg9kQCOIUIOh2W55trbonah--KuSzLMi4UiULxkDmgAup2JmcSBzgA_CArD4tSpxBh0bOxBFYJnc6cie_QfbwRXBqYYvvBKmZJoK
LBH3a-feLSs1oAn_PXnPJYGdat5UkgxfIU5T56CD9IaI2DGJSYjC6QXK45vPKsHTx5cWCpPbTkEiXaVFqpLd7twNH49HHD-Rls-sRzanjBqhR1xP_lBgZjpw
lYbXcjNbkZAFUUaM2FjqjwBGaoE93mhuTKj0btrzlSyZ9gQYeoJhWtrJnAA4ByuDMw8ytYvHxevrKSdXePIgDjshbf2LhNlF750VcMiiYQqRPXOn8YdZZcr1
pAo7zXQSomybWsTatS-IXDkXj9HKx5iokt9LT5sQdo-KVSnktpkGghiYJEuy52ZlvkTU7uBHPR63UaPsIqg5b9ptISxzzJLZZAJC6UrR81OpgqPIIEe5HSrm
thnsBNftytNZs4rlMv8EZLhvUNa-8dlVn6zPzUo94cxuZtKxqMqSsQ4mV5LS3XVb_L_tXbH5Ta69R4pxdwNtRdyWQGrWp1yKwG-_MW8XTCOCOllE2TvXiCMH
3MGLwZOfdVDd1w8UQo9eZH3nIb7XRGm-llKpZShCje6Mk0slbDmfZZ0yEvNiI_6O6Nru86ir4WKOK3a-vERlg3-oPsx8WyBS4XrCTb1SnDsP8m8QbKdmf6Zz
MzBZ3EEZfxvc145JC1UCHKJfnw0D5PnZCIKswwdCUxTn8DWZmZXIhGmERL36SxfzwBttcWcVbEDVybWp7UZqyTwbn3-FH-ziZFCO3aac7-CmppHaBBbyV20p
Kz0pPKw06HKfkXyA_uzX7QaVyOQOYHj7KO3ZkT8FoBmkmiTEVKrDk2dpNz8K9PokKyP3I6qslC9Gf_Y9928hBa9HB2mkbh3naLDVow8eNoWWdA9gGAWO67Oq
xtsOXqeSALba1q5_4KZtpBYasoS7KcMwcW1C9qNvNAd75x8DWLK3XyHjM8t4QnWUbMZmfFZ8AZYRqfP_EHcoU5LcY2dCc7bIGEU_Zo-KYKJOZfGEYRjiPDu8
upvwYm0EYQZLW5mphKs_vFo1Kp_BxxGfOc0U-a2meXyrWrXHqx3PG4kCnoX9nnvsZ8QFcV2ebQZptmzS_9QDVtdllL80Q56-O-cd8rV71v42WdKiriqFXcIe
WtyepifH9M1As_nVm2XGKraiQzW-C91gBeET5AiUgrMA7meUOp6J8VxTkS4-92fJtkh5JSesPBUueuJBVpXr5vZ_Gac8c2bE2kCGMITgtMbo6GMfZA836OM3
nsHCIbiyLyhx9yCMVyMrCFh4oQD-rL0p4vml_dpfe7En6W8QctaNmUZN8WwY7iTAgUZ6SlV8h87SKAhYm9yfRiBe3TD6WAqIiOwU5ija45nbIiAfrfrvj6Dj
JCl0GddtP6v_WT0Z5ZifuMfol72nYiznB1icJ4Dw8ACb5GkFVis_BFgSonWS5yhhH-Rjhm0zfoSbtU0OUY9u6SVyKXwBvIfJ8kteVg6Sbc6lADUJkPsaBHGf
oipLNPGP2uKnAL0U9EOCdusMkB0xZrlAjCWBo_LaRY_CcPxYbUA0roK8ZfEPDmFXUY67mSXdgX6k18FAw2PceJnRo3DUXh5GRZ2oKFn1CNLtSNSeX8asgkeB
LfYV0hPvxpvS-YcCeLRObJCffsLKwl4wtHwKEupISnPv1dLNRq_5ooj_B9RHF7UdWUZSp6XIbglPYh9OoE9rBbTAlZeMF552tDLEYXm6o1JmOooz1ymspcSJ
CR1QgeKoBKFZZPnMIdT_B1Bv26NnwN6R1lAZas8SBYGUeTgEVTyJW5x7CWxAQc6FDxBHbBNR3VDyIXNN3HFp3dBU2B55HqNPAyY0qMAP2xQkM4M8TyBMbBMx
3SkduCPush1riwWS9ipACOCU5DTGDyFediUohMEPYSSRkUGllRTXYN1HDImRDYa1KMQfUHn3ESSIy7qFoy5poPQnN2nlN__-bR_rvuPPFcKU6gv2QWy3jFvX
vW6FpZbc9c6ClT8zO2QN5Pk3MIclhp_thw-Yt6ACRiU2Y133uqCYtkP_IqDZ9XQpmUZ3hx5ySmP0bzEd-HshXVrs85ta2upyVVXXeH7XUkngT6fnn17hrvHL
iYeBTZStnxfYtIIibe6RWTnIgjTZCNShxM7sTPzCOwQ8C17FPF-nkCQ-ns2LnrZMJiVTzPTZeTnY-Fh4FrD3H3YUnoBNiP0medvXyCyy7RrdCEFVBEk4rkjV
1x9IxYsu6KkYJqBdM5R2j9cmICIFFJD3DVVmiYGJiAxO3SWk0tcVKXXVnuBrLnZK_heMSOU8UdqjProGg2MhiRZlPlvaMJmNaAu3UPyo2z2InthwC82z3SjO
J7bCLItMJBaWbMTQ5cSJvUtedYA-3kHzofai5BvOQdAgMgBl3CmYel00ob41MPdWHANKYdrzxGAtjdH_EGZ-vq3UfmGjQQmMitdv3WPWvXopnsL9PAXO7Sfv
PIr9ZoI6tbA6nftZVKg2bh1QKYq2ouf9L9aXENEIkLdgDPxwXds_heYlZ31t_PEoYMKr8Vz6IQObYnMZYD1fw80yCXpdfWhaJ1A72dlu_hNNdc4JfLyfv_jC
C_wTudHlCRN3ufgT-8_IJHKnfz49HrQxuLlo_MK5kD65CjJpX7o6ahXOLao4WJrw35LVIPYgaZ-cyPqhicLxclcUTaYE9pylb8rjSNo8ad9lgKAUFW9JKeN7
UUO73sezgcppxkuzb2xW8G_Aq5WWdwCaqnhYYa7aqrpoo34bKCuP2h97kqvBoiOobailnzjvlbamhMbSC67UExHQ3EK1IZDHi8947XsG6Y32HZr2be5ycd8z
VHA_OCBGEnMPZozC69uJKJBFFRmWPmMfV6n3V75yYd9lOOkuQ0nc9ZWU-mh0edPiPgAvxxb2Beiw8Vz6YNZFiYxPgecUY4MKQxaYiwXJ_pytTxXUJWz40LpP
J6Oo9_T_k--BFC_VWNGraPKzdze2lywCbO0gEovfS125hhPYMUujj53bysgw6FJwMv1e3ZXtLhf98oJ3dbplkjalaHiC5wTyYa1YL4lkPkVV4zqSXHnDb5HI
nyY3POdfFinFfdR9IqL9WRHI4gM2qHFdl1rICAz8h4eluxabC8AimQHmJpbZBFqU5T4A1BcHGfBt2tCiEOMwnc8u1UtjO0f1rcA49KMpYDepXSRpEqF56Y1D
b3ec2L788-MpgAeQ9Imdwi3U3gOqO8whidoe81oekmE-qiA9onSucE80qfym9XKDFHPy3i8KnvyndlGvPmbHqm07Kuh5gvXgJAE4yjs6In29PgaMSdIcE7x3
-Ceaof22CALOa3wE8STdA8u166T8VmfRl0DcR46OmfXsYuyi25FOqh_Bo360qXj31HbAOOptmf1ZBCNH4qEGWPJ-NOOyB8Zk3PW9AAqZipsbVMIsfpHqsGIK
1imO2jnHeJHqsLYAMvGGH9qf7J1ZAR0OIiI9qWCpaE8guLy45Kh7aUbFGOg1Oxd4YTA_oz0NOa8CAekB-oSn-4HdSH9Hkc4gbBwT9MfM_c3lKnohHwO_XJih
9fnrUls5APsxh3ybXfBRWmakFY5APymdAMAugLKBnR46yp6AEltLmpbLIll8TA40J35a3YgKNXX7EmKcpfJya4g3THePv4PAEOWqKjf7ndDkfyGGVgUWzc3S
tcMEF9QYHEc8GSxZA5uvshTscUSyacBbJ4JfWd7aiPHOUMRSWE4TLHz1yJ8gHEc2oQCfUlvZ8aeF2yVVeS2fDrTJd1V47jmxO_YKjLiEedYJ0g7rC55QGexr
5Dmi3CNVeY1IKVfHd1X4MRrK5xn1SU5D2gRqJvs263YwcW8DbyIRwq_RKLp2NGJhAAv2FRafXIKIIcm51Oct9hUdGChTqGGWNN-BTGgD5qcsf23IIhtKI52b
mBKeQ4usfkZzlR5mJfrouV9snVOKBwDntt1UePJG0PKeooQKM2JqfnKKgiZM57vAoosdNf7nrkJNK9H7_1ABNYiIRKrkJk6viCn1pZKATTRtK18zM56g5Egi
BIdSNx77WdXx2lNNr1JiX-Aq99-VOlkXnFrGn7T32N8zIW1EEvjpKH1AH4JerT8socay9SVmD6BpKIoyI9gE0db14Sn4gPV5PgBKBN4-IlOeeKJE2IMOWyA1
U_aQoiilUgNuN9HQpwKzK7BS3yNsGqcD5FioYbSeCXS5BoanOHgAqJ_-ZcAUVuiTluQYPVELA9HPA90ozPDHK1cLgIWmmTENmMAUWCAG450vG1QAgETlfV2R
R3WklFBAQiXv2efc2kI9x_ifLfQ-N1EQb5aewU4brIGNdKz7yS1tt6CWt4GKoDLYJc_pq3mV9UlDgfxU6p4VnGEbaoJRprTij2hod1GNXaZAUL9AJWGnv2wK
GzY0afCGf1FbS4pZAHafYaIbnM4pvV_e9od3eeTpblrG3aVR0wKaxeToMFP3EVpO7YWbiX_AuPIcfb1-T6eA9ynAmNAupp7DI45aHKcSZWBzEJpFCXdbl-hE
0yLX88fYazvq_-jkf-C2aLV9ky67GP9fdllxzVxsHgVSzcDsbtSvvNuOIpkynIcFurYntUtbJ-4qLkxysgTm7WjpEuRjHB8R2vCxXkr4iZIxOmZu-pUxOmZu
kv5YYFYxGSTW7xAMlxvYgFZhAuQAlxvYgFZhAuQAl_uZe-AlhnYKGvxWh_V8gFZhTmn2o0ipFfMfHE9t39L8_8xX6P48_1KxXaealcAeHE9t37h8Puf1vc-e
62h--Xr3oj_rM_78y4A-LWmwVxEEGUPls35O_EqV6MR8jns3nz-wOx3ustSC5d_xZi7YRzynp1-odhzzns29f5SCbaXwnM25VDynM2Bf7nc2IAeT5a-v2lmj
EWPB97t7OF6txnWi_lOTWnNoVSTWyRVl62p-zeh12lc-Ox3usoi6YR_zplT_vEyd
}

sprite $image271 [102x139/16z] {
jDU7MkIw4WJWjQJk2ctU_tNloXACPmDd2RU0IVxiVwebqe_FvZYEjd8SF_ulsS1EdzBt6rVkTNhlt-gionvFh_J-dKxhOqHaPcJ6Q7TdfNszH1zZ8ei1a8ZZ
SN0pts3q6vD04j4VFLU-EAjvYL_Aa40UtyFiUHnjAsDtcM4AxPbfNq3QSIbxRIQI29A0sB_Ex9DRk-wMaZaYmGH8a8ndvhF8P3RIHym06IaoOS7ZnqfV-JGo
dJMo695pQCnC2819zVk67iU7bNxFQ6ECZ1x8gmeoBKwdtzxJw1-kCkvA6prYEWEOTOI4bInel_zFbMbFnhKkCNfWEaG28YYHojkx6ksZU_XEzD6ZjyWHY14a
HyeAbhBKrXdZuoExBhmpheys1vOnaXb48YL01LPyTcJ7-4MPPV9Qbm0H8H6GIKewblBXaSqTzUWnroX6p-mz4J6LAOJjP57vEET38nipUrKkeuyOOyH882F8
e23Oe4slCkidqOS65fFP7wF7VA55vW2ofwWCMI0zF_hZp0zCR5trpOaUqUOBYOmCPaeOiZcgX7By-4n6l39nWNrQcIE1FaW60QKCi9nbV5Q9FXOm5X4zCqSC
1FQt2q4K9QbmV08vHaR6At3jtoaW-m0HP6PAXL4ki2HzN6d9c4X4pidb-ipe8t9WCWa3Pa8r5QF6HslGvhnytfJhGKyWWaI7921jcA9DY_qZDMJBoAj0vjYV
qNiW0q0WaY6PtRQIPSgJGliteyFJi1cPQvT5zDYZ0gv5wPIGHf8kXQkWaYGxZ_yULN0RjY8Hs1EBZ016WXaP28hAW0qBHXawzwcA_weXM_AACf38HApF039c
ZwGG4YDiE-6YQ4rXEUplhxZbHv0PV5CmbHw1J5A9384sGrMLTKfsQJjeVr_nkw4g096n5LmxRYJ9e9GTjjAWMSMH5r9UsSlpNesTAkRyY1oHQs581AchLz8g
XCeP_LfHk-wCulXh3IQrgvmEWFCpoIdi7im-YRI9m6Yl_pWDdrEvEUE1FDT0xsCawFePP99vNJwn9nMvUfYPhH_tVyyQp_DngUTjSDPzLXphZ_jB4J9nGGAa
J6GCJC1MZcCPMvc9AdddUHjKrStHw6D6DKS6uMtjSmguE8C0SxHvvQrCg1sTzZFZFBPoTtBz36RDW1J0J290fIIj7hA5Q4URqbOcq_8n__lor6RsGImbQvM1
20ioA16saO0mTuSo-x7xND8nqK7lt9UdNlCsigcCkYA0av05Iqa0SVMeiicucArifi7MhquzyXXPxppN8Cd4_6G0o9IAj0kWprfxO34xRTRHtP3hVAbxB7Cf
iL-W334rlspODYmYgyvJ5aQxCstcwBZrEC-NbxEUOqU_iaiIfefR4Cj6KYML9RyOiJV0pgBYKUDA_HekPVYL4InuVIL9mMl_-VHi6tqpjpHv4jlOobDscVHc
D2682PAunbWIU9v5dIz6JkRkz9HtZRyff_iAtXZPs3j5AXkGJwsfpzVotgQ5gYPnZtzd-0iZmQPBh6jcCkkqu5bcNb0OMpa6zw3ULsRoZTb7JH4K88jrbY6j
drdoUSwfZJPhf3RnBqh5PjBBEKlN1QMw17a-aEnvy6U4E8ArZNzJpXfBQQ7jb2NIX6pwBFDnvBgJD_6EOjjFJBJ5TDZoRcJPcimcpdMYvj5f_3MdBqIsdfdS
J0lQrfPS9MczgIrSHsiIxobd-IrtX-FDWNn5tXP9IOzNB-JzBf9tP3_L-IbSJEi1NbULY8m0dtyOxhodbEK_EyxUfj5c-fLBbFrKur-KyxHkpfqvYp7Qplmn
E8BwK8r7b__rQXywpeGm483tYWs6cVT_tLyvfrfxyS4k_wWbQfzm8HM47oSw3hLQL4L4YmksTunSkJ2xPVF0qziJOJaHPwntx3enoJ5IvUg4zkmwuHW3YZlq
zYHEOYHAA9jdX-5CO7VbR-t18SK3HcU5qf6qPqI1bL9xK9BsZ2gz-fSI24hIdX45LkGdAaP49MyF1evHBrOXWnBRuuxdxmf-ZDBmyr0HbEY4zWmeUkqwQr2o
zbYke5UuOgGhbYaNvkwODV2z0ZRHgzA8cr8IvQaz5uF858iAMQKoKzpnAt9AmRj9ZbCDyes2VSLhA9qagYjPsG3SqR0RfPIsg-3og31NF4xiARYkUDjJs5Ma
HoLFLBgAfo0gPAyYOfnJ0bAicuhqeC2AE79KWOesaZIHzgeKlyWQZoicsac2Y8fNqS33olEAMsTGj3QG9oXD2dxRojh3k4yhLMgo-_CAxobYn6e5vJ-THTlr
CodMALNkKLkcT15LqKj4sdkbJ2kqnrcaB5FOh-zogeXYWH9Iroi4MrHinLcYKa6UVnQJoYS5v7aAdXQqtPMGWmfgUMdBHL7ZoOfvB_o5kRe7dg-8UUir5EfC
fOke0QsAIESg1Vu6mj-DBLFOhePsfiftnwH2Kn4j3SoLxTCmgH2j-VDSsRQ2SIKcLpQlscfb-p0iLZmAh5A0kx9zDInH0DAU_f1JiK01sRwtvqX7hemQNRQG
pvOpOmPqxmyB9MCmPEp_tITV7GmOzNFxBP-6umf0_cxaguFnuTt6guQ9uOt9LmU3mpjNDPnYP1SEqWK9mpjLDQGBCXZf6530P7X7LWVfy8wdu6zAOWol3WOM
PBvg61tUgTN1Zg67ZRWw61hUsTL1UhldoLS70xVxVDMGBCXSucir1ePtlcgu6dt065yTZ2p8_8KJRlSL-Mxm1LcR3xEfuVq7
}

