sprite $image56 [130x93/16z] {
nPM9ZYiv24N1U0NS__-v8rTQLeLPc9JyoEbDk-bmxWKUadf3-29O1_Cey3Nou346Sy_m5QWpZmlcbY2Sr9Z7XhaYX89by7Y3HuaMmCBSANG1XaWTiDxUD_08
qC48OE6H8n9eiJg42_1t7V3FLV1msCd4Y0GwEaGA491Caq2NNTG12VHqEBQ0uU0aCo21ZWu10ZWw12JGqo4WWQuEPmI8rG4V9j2vsm42E4KTlm2hGq02Jzpj
emBuTzjFO9WElW0HoSHwQW5-KGSaqDCXN03BtvFf212WWyWmHEiWB3n2iScKd8Ddi4Kj15Z5p12gWwnPKW_KmTvj8LZGq6_f80GlohTqs1C0jk_e80IRr5MY
9n0LWXkPOtKGdMO2W1Au2jOvVoT8261qY7b_Jq0vmIOccInpiJy3oXb3TH2TRnC04cMuOulw_0BU9gW4a8oHfgYFBs2ZcW66DeG5HkWWEkzeamOaAkMQ81F2
mXRr-GLi16X8mIoJbmX4cM1p_cwpJejS9SIKgcfFLoh8wd1M08l0eab7QdhfGCi5eyD90Ioo_zKAXPSE1gF3eGNO2HR4Kg2g3eGBiaLzV05sWgN386oQOB6B
-ipTNk_x4m0sQRkO3XMrNO15fyATDBO8W9JfmDssxrkqmZkPEL-ZxA9-r-6O00kTSoImN3e0NksmIAQevK02z_kIOM71rGvv9HFN13adHuTJ2x0w557EhxjD
zcwVU7zs18FL0OlgU1LriaLzG002XoezfJRbAcfqYlfp0GhuO9UAkK-fJb4V5C12B1cgp0uNI6ZkziC5z0J_co9CqCUkg6Hqu0SBO8AFQD8JsA9EhUTB1-4F
AtXgWKz9_IK2hcIcLp2nYFRrbqNuemGsX0TSTnlohBU6hAmP0BgA23-kuCzqG1wrmqKYW5JAsj6QG9YVLB2FBMfAxQUazwAkAXTyA84MMzIfrJ7mNjH5vHTc
yIhu6VPkDotjLTJuFe6Rm2DK6KHP6NTHPsU2NS6dm2uDowX2iF0dM6X3E0WDAKXpvEnCO19uaYoSSnbATeAZ2VJlDacr9fvDe7-tavE54mdqYngWcWdE9j0l
QZE1ay3ZuDAXsmbs0Y62rEM6cWJ6G4FD14Q000hhVGATFreW5coYzy_0L72a3aQ0MFBImQdW01rC1OU3_Va2_W8
}

