sprite $image366 [190x198/16z] {
xTXfSXix34NXp081Kjp_RjEPuQb5-KY-x9Ztztl9vwvZ5YhzvljWPLlNxlmwWPNVCoNUopQ__YVU9lV_5LpztVLypuJhVc2z_p5X_BFh_LuUxNB-NypAorFO
nmLMBarYp_E1pCJ-gmNdCZZx8h3lV_zKk_hp3qa6_WU5_sf1UStiNh-ixbVuJoLDpVy9zs6_5x9xHJF2vpE_yOS7VdK_uGB_xVGH3_W2Fz8dlo9_hZziFl5x
NcH-hZze_f4cUZsvNfQ_SRqo7ojKByxdXFHw_nUcL-TVaBwgyozEzAtAyp6WRwtAyo7wLlL-e6_LN9s_0VtfP2xEtu1-Mr7dOq2_JPyFqP_a-HlHy_pvY9xd
pmVqK-HFzFfy3EYdo8VezNupejU_deNeUVvyG3z5_a3_r5y4-GEzFdy3-Ydo1_efyWVwAOu7e9yX7w1F-UZyG3z3_aRq-lmDwVNv6z7pVFY8VlFBNq-Wd-5u
0FePyWTwUVvHWLxxUdhK2lJIV7oZ4ttsnnlxerQWX_dpP80Uvi-J0NgMFqy6w64-F1cWXtvk1tgSZyFScPxxGUx3Ucq-NcCWcG6zuFNqQ2rsaXdGw_BvwOY1
PB3-ziU3_r94IWRgxvz_ZYRfKp9KV__yVICaVTGgqu_ddwFvgnz81kjvFjcUDiBcUkvFmMlq_7Y8sbHwxazsWHxb4xKsZPw_dbwRIC_pyMXDfEV7GzGcq_Fy
QnFesLohv_ahzNn5gUT3-gLV-gLV-gLV-dXF-gLlxqc_z4lVbdxfBspfbtxfxN_GB_tIB_tILp-mFhmKEwY-UlavEw8-oj_PuVJX9Urm-l3ijwFfDty1Vec-
9pt8HwFlcnxufVg-BV51_WBzHaz-aBz0t_yjG3u2VSQ3V3JwZ0Vv2FJ93ln2VVJdL_Vyi-Xx7iXVe4zua8zAto_jlESNw_l0Wlcv7jXn_bm_W0VvA_JdX8F-
jzTl8CO7VgRFU44-G9_i2Z_NjzVY-V70zHqCl9v03_0q7wu7TdmyS3t0u-E1wm4Uvy_rpCxpv_e0KfW_rmCcE1w0FWyOGVv0J_4y7rFfn-TxVhcUvwFNyzUJ
wqNvo_NyTkPwPVvShyoVwwNvQ_NyU81wUVvShtqzaLx_wmlr-douNlzwShtgzZIfdl_B0zFhysTwVVv8ht_z1NfuE_iZFz7hyoTwVVuEz38_q-lpONgz7-dr
nmFKw_CVq9_xj7o_g1SWn_snh--pxJokxpFEn_JH9zs8la-yI_e--VRqVVwzhE-7sFFwVfITd-hxeVPGBo5mFkbTxmTuzJpY9lRl
}

