sprite $image167 [275x208/16z] {
xDO7akmW38JX5oOWjSpS_xQBDzhLLB6JW_exmb-Iu71FRhF3Dx66eYZ8TnFPsugd3-B6j3DC8zAX2UdOg0XJ4EOAmcgM8DL-JoF2F5qGHIbsYaH7H57i70bs
HatSpgSW7JeYh6X4c2i8gzePfY2iQ6SOdZ78ngvBEzFnr44KPM-tKZKYx0c3A0hizlPFz1FHe1Ix7uq8Amh2_A63Q7kgFGgD28E2C4_ty8xvvlL-x-TJa0uT
4LPKX6bdEZGXh2W8gzePfY3CjJEitlJtdllELblJfC2UcrzvPxGz6rlJfBYzZAlyH1HbRw_6DI9CGKwEKdnmLVDj3u0pFgil-Pt5RB0poROdOX756aM91e1x
cY8DXaa2Cyka398qWBkbKWT9cdHDR914KIX9qktP3v8qy6nH1abIHl51afGdfOoIw44E85QqFG57Q7lCLqdSGr7C5hTaEIS04f-KyfraSKxWGEQJKdjVDGIG
-wHmaYaYzVOO9ubfZXA9e_27f3MPCc-FyvJaZk88IbBzVvcQd2Tb7WTEKdVRc6OHsHvaVsldJhGLkN4m0CkxBVtYll_Rpg5yu1gCm9E41ghHhDcJxqYoR5Mt
gCuaBCsVIVwkwc61tYAHaUIlQYa2xN5pBj4pYUfVqb8OgYR9EO33t6UPUQSrOvC00ybcCbKFxnJ49i50Og3iisRimW5mGM9CANi3iKdGV-L8ObJFlch69k7p
kDB_gvFijNe4EWSWLuN35Tsa_uyEiRFgOUYjWF3LG2--w2bHXjXPI-aW5WbVaY0LLGDbFzN30ZMYtsl6Nb9TKTqtIWUnII0ZYO1JrHvxhHwxPkovHBV0Gg9y
8WgBMc7F9JsWXzrLZrqpQtSSxPEQma8P4sKFDMC_3c0WcHB5pfGTW9Y50s0akOaY31LZN_gHDMEJ32ROJ8p39_jG61-LA0iWnaCZTmvC2cDBGKmbCzH0-SIQ
iKcK4wiErNEEaGY1SkqPPLJFnu7O90UDoPX8nb-NVAai0kFPu0ERY4q2IGdQ0r0BfOHQUSkgzqSnG9P9-Boqi1C5gf9APHogwoRNA1zPC_QerfhsW8KYKEMO
60Vn6udHKjwvPenpOt5fWPj_3Yaid4dCbyWF0L5EtbVzZPyVkJJ1I6AOeBSP4QbUx77s8se6rH6HnqZomnX2P5W4MlCy-gyJz1ew1endWtS7wI94Cf1iCGtr
yz82LoJQEOOxudkr51Pz72YLQ3FXaMGssL06aWa5ggqqaQjhiyuepFo-JGJLawCaPIAvXT9DeBVlE514xxC0mCLBWd4Wl-d1Avw88fJTJ69MptGwdKb2g6su
DLzSco46okj0R1BHYSGmWHYBi1E9Aom3sq3oufR20bqd2MgIz92vfSmclN1Y6sxDGxgyUafP0P4S8tUIhAfYaDWjPKQ1QacD1QXrI9uHnMufhpzuYoEYW8sa
6YIMYOsYoBb9l-CO8wvHFIy_U2NGCHmlagot54bPe7o-uxm1ob8JOK_aFH6rTP9vIZ4IXOKvaKpdqOjQ2aFNH5o1-2kI83P9ZuCiL0y4u2J6hTbgAIy-U1jv
LcsN9B501n8Zv77rR5BG1wj16DNpeeENFIkoev44ehf0CezkEeL07wy6yGVsfIiWw8aaRKkHWMIAdpjnhtgAJqsmi1g4qLB-RCr8Sjlihef256fO9bcVKf9F
YJ7E-7TlpMfKpnywU4-9qKKIEePuLs2Gs76mMafokJBKNWsE98qLOg8yluaqrvy0ulP_CxJHHb94TPt4xhC32Oi-N0r25Sxx9izuDbW2KNRa6n9H009vA09D
9MEHh5TF3hNoS5-6VMjMSQKqCMx8JtysKqHoh5g9F9We0fayUJP9LaBcHE5OAqDhnFtLO2Tnp08rK9xOHD2YQ2CgYkg9l1GYNmB5Kg2B9ElLqsBPbXPDxwu6
U-5axXbbpFZFMaQqG0H4SdByVow9PZg6j_zW60AF3sG1Mc91SqtlcVHV6meF7zGQ1_9pRhmEuiWdHnGQLCicmlykG-mf1I9Sg9FSto7Nr9eSn6VZqUqP8Bfb
HApWdXWLMljxGEB_0CJeimAWoR0-Db5QQAB8MTL0USBqNebSm_Q_jCqVZKGL3Fm78bPBOKnx36iro2nSNVuldWq4gw-8lQXBhnHKHw96621BeHX213eEzFUg
HmISwtZlCLhAIiqibatM4maKcIZWlmAnnrc8J4iB0qMc3sedb5MGvIJXKm6HJvueYAwVC-jXxalxG6zK3rIlCigedl_WuEKSiwYsSr8mzOZo112Zppx-_37b
ThqPD53-RHFXIBJbG-uNNrL5fDvWdr0pTsTycAj1LN7HD-E3sgMMiluL0FMe6ebY_mkef12U2cAZ69USZQGsCMxDQos5PLN4zIjlx8KZiKv9-mIH7eUrvKOd
yRMTs8RAMKSHwDeRWAzeZYWSIQYYUgfFE7ZDm1ZtJE1oRSO7jGijPVMSWISdgXg8l2QY7kqP87R8OgB48ubo4XrGT0YhfQo3z06ag6fl8uN8wAfF55dVbogd
tEI0aASsOwFyawMt5-qaMSLl1o_R84yBNaAHK0NSIPPNWyjF0Cb7LcsdCyPlrS8ff0RhZpay3MHziIxZ7GTwqsHwYMJO45mmJYBGr2Tu5TUp1GltkrUYg0Ya
DUFMR5IF24oHx08s4N_gee4eZotb1IMpSY2F5vhnLratHAoY5AA0dX8kPNTKyBrms967se7dKjW7CYv80CNIhHdNrTDHJ194SXNO6khsjehMtmJCw4taDIWZ
IGY91NXyQuPHFHP99QhzYv5q924VYAYyfcRMfnIemfLOnFZK3pUhp2n4OVoI85207El6jzDmvYhMQ-OrVHQguaAjupoForipHfAMcuXWZ27bgdVoIyAEKlL4
xWZERZjwshkaYFri05Li9ECyRtzGgz7xD9ACP7oiYuGpIUbxpSGgQamY5iWhMmfKrUTQ1So_0FPgC8RQB998nwWd4cor4XZQeYvF8kzHFILNbeE4EbGAzFPg
C5BX-oGU9vBGbn7ApgiHXiYB-wmgIcnoq1pnOE43rHJh0n8g0qdkZmBXVK5wo5GzfOaqb_1W2mRL6jiz4az4ZeSiQUtuQtbbD7kpwe582_aImFwWrYQ9smuF
lxt4kIxojYbYBv77d-dmxWylHKftI18y4TMDH2jjaUIDGUnCOJRlEFDgy1x9vk3xeWg9o8M6jUdzBLlAvHt7Hlab4Pb8jYM4sqWKtFXZG7g8lHayB3sm2Kya
AewE4V3E1-_wE3kG60ziW4BazayoapOIBGQ9SSwyFOhzWmPxv92QoEtFA7CdWNz4ylFcWJ5-LuF6WHoIUUASIBGjl3H_5Cguj9XHl2_r4GboQFXOaHw7rIsO
Qd2FIHGV3j9Z5IN5zfZauq5wy1fAYtM1P0yWSw8ONxMXndo792-9xAnwK9D9ih3YtHiAEef5mh8_4FjhWt7fOv7ihMRiYu-nj5WdmUSPh4yfK9K6DKXsbI7h
pmQQVIW6YIcoHvHnQH6hGR9SC_ivU-obnIupP7qrc48rI7OEOgy6Yx6qM7X7t6jBaRnMEFkpiASKZjbuZZP1TjzIK0qI2sJ_AAh62xq9idyJOUE5Va5aloZc
rV3dRmhOOHoy-m-15LEAV1Db0lbcoWJoDPb4lYWB8ZiFc-IBCf9yumR9DsQIRzWaNvIHv1ipoJTka7n3W3-xhlaV
}

