sprite $image356 [170x245/16z] {
p9O7ZYjB3CJ-fFMqr7t_u_uN7EgbWYCq9DBc9IowxF_AsVPLdu1PzjRQlk0zvrCxypMXFQUl9ZQmwDg44e06-Zkd6NjuWSrrQuwLV7XUhbecWtA51UhP9jWo
UVOL5wXtdP67XotMrfvbuntUBnPecGYBvGF5vhgszrXvWVfSwOSNfucsJ9wDVdYnhxnbyel52zGl5csPF1ilKBzOlCFxN7dBv7Eb7TwpyfR9vqeBr7DYBPCd
EZjGUOx1FRo87D_1B9Cd-v0f-_1dkCkamv-11zh73VOoZI7eWOfd3dz4e8AvJ0fKq0ylcCia17EPX00kau4UgA2zP_BGtZDvw8SNj6Noq9R9Gric3prGGJ-y
e2tJuwOBB511MoOFFL11MoOFTPcyAInGRpfb16APFEV3xsjc1l7mulgCZvGhwV3Yzf8KyKCr0CjasCvoSgKTNgQIKm8iJvaQLqoWCbMVolNGGBsf7aUv0Wvl
J4q2XCFBrBX600vlJ5skzOVtfZO1YgTClUlHWNhJZ4_bQW9ztzJdUkZXlQbFeFxmtlJznT8obPdwnQe_l3VrBx3rdcA9D9XSYmCLSpEg9jU2PJBi4KRLB5Rr
uMMQ6Syyh1dbXvTfPiHJhWNBP4oTgryiS_W2qmSJa6kvfqpVo5M1bfW-dMk42RJ0rAdwN7NuEjC--Ykvwl25fkDfr_Fl7M2Q4S_b6XAjDEtdw1xFDRBt0qpr
ICM32VoGFCPKge-udXKFCfNh8xcEmqmLeCcLOkeJu9dw16YcmYH0ClMvyanzhZnJd-lHfjsOcWI8fd8DkS9CVQuHE5E_M41JdwjCasFg4_ZngmaozOirUaQG
J7skqRA3ElMvjkYiPvG8cVwa_hdVCXztbMadcsQ4J0VKLAvqKn7Vs9q38e0000XW0D2_hmW0_DaIB6OwHqrDJKrDJKrDJKrDJUUOwVItgQcfgQdfPBgDgQcf
gQcfgQcfgQcfgUbeUY5JqpvaEjL5n7HfxZnq6mU262gvUqZ__-TU6Toc4g9z2o8QbFJa8IAVTZV5F2_B5r9oXwIyhSjtqWTgRwJtmzBp_PTCQrUaE3Mc96tM
dP3oiYw2LBDwqlo5xu7-xUqgv4czcNeaAIc_hNbIRQOjqWVXMVEaRQPjKWn04G55ch_mcdG0liSrJwhD94RtoKGWIjfcygGDQ5YZf6mpUL9-0XJ6IfD217Ih
-sNYclfBBhoRoPAYgdHSywGKZsjfkg_YMXKcvLrTU4qg0KLS1MdAJBxx6n68aF8Yq5ptDU1uDaBAcp2J8nsQSd4TfAbRfoTbVQ7IQMXI0WoicJnfZt2-J4Dp
0aoOoPDgG9q6Lh_C-KMz6xSxiSRgju0vCtbIhzGQ__uAOCnClb46iCRRmSdktzPbahIUKYf7ztDcylVzyd7jxhE14sRIyrzz0eX-cLap-UvxfGxWb9aqwUjA
xG41vipa6-Nxr6ylqtspcvidVJofL8Zkfowy9YtlVFL_9kRDvEVcbj4w3G_soyoOIS-fH9-iiKRtKsRIStbPgJr5WB60wbclhokrqDqFcadFyVwYKflHa9er
KpIkllj-DpS_w-MLLMfp0aoOoSz16qkdeVfbJfjfFgv6gVzUeZDJRixrhB70xKRHc2bWB1dNSjttPih75QFx13XXfhon_Ca4nMukDPTtLdCoOSoKdyDrCmBD
AqYDcUB6qYSJell6JE6uwWYKxlw4cG8tM74oCM6cgB54zoTsSycuwfE9YJLJz0OxW2VDbB_1DkTxJd5UTZA7zmY8auaPC-MDrOW0PysKly4-1kcacV9nRTBJ
3PST0MfZDUcwp0OqRwn1kkDPBm7Iw0qs8D5GN0CIZSmPFo3Htm
}

sprite $image356 [85x122/16z] {
xTO9hjim40DGRt4apgZtFsvTi8i2VWS3ZxgR1tWG2SdmT35hsUTfR9OdWBAD9ET7HQqLACimSpj81XYqmL90asnz36Y-a-pOiYPDZlaQu9cPTYr2fgRbDH8p
EUsyzyrLlJBj9cHkMewffhALqoR7L7PBNAFaj5iHCZ1jlhbUh_YRZAijSOrEI6yjTusKj7OaCwR6l9sYy-DgSoOrfZPd1ZTdHbsZZXGqCQQY-MkaQ7vCHJbc
jhcYMuAK31XJm-RPCHMTiyqLNKk18TDSimEeC4EYkQIGWm69veBob80XGIhAKu9wQimU9QTiV4n5UnP8D1UqcpRHN52PLff7ypH6fjNcyHIGascLZ0S6iZgj
ZXb7hMDbMXapXfB1oRJIF8owdsuWP1JrPh2FMMqUtxJM3wSrJw0ybQW7c4257OEI1Tc1gE5rsZmg6wHG9o3i85IdzUPPLATrGnxL3Jo5AflVL5KCHfb_6BtH
6xtH6xK_7BtH6xrH-rlGJyDHRwqktu0KsfFOfkcRK954IVe-7Ud_zVCdBVFKeVw51IwZ77ETcFxV6HM2nabxK9JwP2-W7FE8rgSjQE2OPUbChG-gGPGaEAQY
13kMQ81qZdbUdo0guYTzpfEY36ZrH_RcYkgRd2HQlxC1ekUaRIfg_LVR1PLhz1RLSxwlxtoJRr7eERM-NgFtgCivfRwyoVDuNn_smfxMTrwZq-n6jWRgopKw
pLAe7fPULQBoQGzahIvNjQild_PW7kZPRxQRrESr2cP-cbEL-lffZsSjtM6_rMz4vKt6iw5ZjNvyJBrUFLjPl_kqNydIJylwtPky4BrUxcR-qQSzDIthyzEU
pCnf3N1vauaiXH-PvbNUP7PQRorPN5_kWIBDwClTfulv3
}

