sprite $image56 [260x186/16z] {
xDK5RYum30JX1uNCMehlVzis8XT_vlLtX94toKiJm4XZ8LYKhgOeQGbHB6yX-2RDyACku3G8Daa7aoswm68m0-iAOcUH3-cLVSZv24eN06Gm0wTJu0XTu346
8OusZ0kKwJi3IXTO7cC6Re_Zv0oCPr1aF8FI1UxadtmIPoRd8oXTu9OhF751naTGTAC5h2iCDl3u9xcQBh3Su4DW-2mCSNqZhsYAcw2dl1PkYCb3i9cCZw1q
0K1Nc85nXLUAQGLkcsHSe7I1nUGft6pu7a7HD2vGEW4GnWLA5rYcSO6IHmjnxvJ74SMp0W-Z2nnQOV9WmlW8IYTOZlqCd7w8GJ6jW7Xi6haP5Zh1ba64CB6X
GKZkfn3lX7U5YAuGWS9e48pyvgryyz1nNOU1gAZYml6D_lzl7xpFpgpWB7rB5cjQ1pseEGY75AK0empeoi8h1o74YGNH0wySX93cFcE13bPANx6GNpa8ClHQ
47JGMooeVdP0aj921pGEIEcjJz81aR6t3a479CwTXIFeWEI--kHB1q66VYmewA0bTX8BYkNNQmVTZC-w_FhLEEWe5cZ0TC3n-SPbO3ZeONpU33GEUea5bi7H
GGm7RdkgLj30PmUvqCBByLdl5WH71odbB1t40WsySf1I-T92PYpu3mBJGSebtJGM-2Cm74ZQB8WT2tSpqFR6k5a8n3nL-oy3EY2H3epn6NeF0tHGmahEOKNY
wi22br8E9mBRmO0vxR4Go4rYWK5WEm16QQjV_8_FB0FJmHHt1uiE4aZotoTP1hO3w21xv6FEdmFI69yP2rxBW3o_ULGe08o93foFpom3cueFfXGaPW0BT1Gw
M2suFLNJWCt-7ESZ49DY0Q3vimGh5bWG_ig0y56IbX3orCI2R1BE-gHN0tImmczU52jJf8NYSDd6CZYdxZo_UG5qwnOhaGuSdAgjVcWxe0GC4c8S_m_7ietF
T61E2yxAW5J2M0Z3wW2Ojl4v47FPvj807L02vXHa61KhOmo_HM8iU0a2KbiOY39YHOVGa4ukfTpz2EY007iWpe02Q6OaoIMTZCyE3DWEQ64TdzDyS60ksrWG
Fig03exiiH32V7IGKiadopOV1cm779_ZEAKs3rREJzK-og1rOCH2YqHkdyrOS630Tj2EpuI7Y9pEncS7PN3gWATg8bmifFExwkiDnhO3EnOsafRD0XsOiN3n
Ch0D7CVdbGIUgcCWF_c4HR_B0D7FiP1UZCzdoxPB6w026t2Va9vdIs9C2tm1xYi8x5Y8-41JUFA3qyAt1O4T2sNS8Z_HGKhdJrYkLmQF-gSyE3uN0Bh50WV7
V78fvRWC2B07udXOjgsKU7AgTjKFJyPdBjlcVTbc3evy0UxU02raBjkuVQO3umNu9O9WgV_6WdRPfZf6Ot0qOi7BZy3kap81ocKR1qSx5dxMmAE-XUUQKMRe
uMnv_eJbCeFnUs914dUmft3Pvja0UPwgPSO7fOt0ixjgfq7GeizbspJXy8SWEH-VVHjensS98Sq71xypFlleXpOJza1CYY6q3jxxX4MnND10UoaLenmS72pa
E0xItbMxAWEx8CQljy_yQ5Y0vPcTmbXmr0tiMFXY-rne9vL15SkynuHmmNA1HT4x2eBxX66QU9uiJJ6egYxOFvg0KmiA1mRQPTlAo2OHMmSoVqWGJeqVgBeA
0jl289k3PvUGt2P5cHKO2n-rqOAd8B37vyt16CUn7P9ot3O9yuHf-mX47PS1cPwdwb4nHa2bcP7P9nClAq3KMndOoxOu3N7r4OAvVOveQ0h2fO5ssIOH0AIK
R6oVHN6muAWVdbzA5GLauWCE3ev71qGTbm5PzZuf8sJQOlABxRE2q89t0xGmIf0m0HWaPreuTN070-qBS0M6XBqPodSxg5U2ssST4ZWuIkDWDXnuLz2UgXC0
ZMaxNISvS-3KWDqdPq1bXiP0tkvWgPU4TzMwEi0Klyz1lIfy0PvN1nWaoha3pmRiK_K8e6JLSkh0THdOiP1cb09eUhU3UdrugYwf051vguFg0xu0J-zsKFsW
F5LZVj-SM5t1MCZZsnnKRppurFF4mSqCs2_0nNBWtu1zAMKxk9a2-r8gmd3WO2PwnwLK-Zi7rJzyl5F-ni6ZtW1UIas6W_kKWHqB-6C7zLRWInRBG2SI5gCC
Uh6mT620F7xVGRqlo-yvMEgjiHtGG5yMbeuC4Cj1xOQl73ngHxnsK3lZwA3sXxOEQfzyTb2xPNTGkmPOVg0R_0S
}

