sprite $image379 [96x205/16z] {
xTI7afn034LHPsYfP_Z_lpNjpRjCxVK57FKsL3ugz5IzFENQrboNinBjBkVexIbnl3uFbqxmgtdAiNZcUHE679bnqeGxDtBh4-O3_E7Udd243oTu_s7v0Mem
Flm4x_C9thzpmQqw_zqQOf_Fb-HzFi7xV4dSrv_0_TuxdU3yooM3Jd1-J3Ei8SBvqzJe9oX_12z9-jFyPW9uLxd_Pabn-nD2-Re6xa-pg07vsnE2rC1zloJk
-rlbFgyXd3_X9wCbzcqDrFSr6Dy_6TpdJqOJlgW1--h9WBw_rO2-hs5clh_LeBwl0Vg-XY_GzxVAV5z3DEhx9mFv_bO3-Bw6o0vyVQk31RwyrLXHuCibHGuT
-EfMXmXyLSETVm6-lDMyz0s_0GXC61RtUOBwlWRc-pJc-xH_n-_blqra-UNpb5z--UMNVoc__9Sfl_pooo-__FBBdyill_poo_y3t-UURJxHpsXhplL7JlAV
9iod-HbWWlVvahpFbyJz9T04xwzQP88QdFz3Ym0rE3_ZRW9OalBlDB0axJzCYAq9Hzqdgy7xh0RlmngypvVa_OoR4-P3_A616gJFQ_0-hy7x_5QvpvSaVJx1
-ljhIERp6hXlQk2-MnBtzPAuxoTmtzV0VL_3jXz0PqlQzfS5J61BslRNvDu9x_XW0gbXsmS3O0st_KEMDD_s3rhIE_wovrQ1lsj96S3VMGFmTzK0V543zlsI
kEydSD_NmFqHyGd0rqkYlbyIzVsjSjylgQyyyFM4tXFwlWRkt-NwKpK4ylqd4DzF60q07ou9lCyyNVeyrkUnFe_qUQpFOtqUxDi4z7sexqDz7-ZxTEZxKDy7
-ZvNwFi4z7sexxFXz-N8lF6NetFlPtQWgmpwxjzTlWC
}

