sprite $image45 [110x80/16z] {
lPO9qgCw38I3TxMKT__ZlfG3Sd2Ce3paxrfcdm-hMyjZHgxavV57MX815Fy65WZq4eh_FSiNW0W00TdzbkKoKDyLIsMcvOU6HQeiYijQK53ugM6rW1gMdzdd
LiEAtzNr9_Oj2Q3lolc2jR9tgXesJ4MytJvVrB3ngxN0TwKUAC7u2tTqWoRlfQZ_kVwl-fomsdT7wgkqY8aLWlQx-TtquP_7L1KGtdGMAAAmvFTprszIQwTJ
lmf2_k59GDHeHCBniMHXMgNspQM-YPcOTqMjRWcna6h2FZM-KsLrD286xMHqWnNgaNfQByC-sx0Pcc6VbNf3EAL1Xzcrr5k2jsb0oRYsYvPrENSQlorZ-AvO
FrdjimoheXW-5DE-j2dbKagEVlYsrR18fxl8XxVyzukfYOLV4f4137dHBpVjSyP5gXQT2XoxtL3yk8W3siWYRDQESOBTRkYxGSjilWtGrWrkMPoFHut2Kbot
skCWzN5J-7OqXeGAerQOk1xDhfVVQ6fV2LzZYcKLZrwPe9Eampbx2cetw7BUgnm61NbdDbLQVDWAEip21mkRXWxcGreucqwwYnYaIZ5Lsr8STMA6pgqkgVR4
AC8QLsRbMPaa4VJzj1IcglmbtzncPV7poI-XktJCVeCW1-zyBDl_0zv9f1aP8D2-U5QQFk_YB85KCMYWNTX9MNYnAgtnWjiqJByEUKDj3kjnr5YDni17lmN_
eP30j0ajkkENRR2uCqnfAf2APIU5rUPoeSwRDCP9hXdk35DQpxE5r190Onm7Lth3bDRpvcaAs1bcq1YOfwdG33DeLVXtcXfcq5IuWmPb6JJbpTEqY3RDjWyO
qG2ZY0RDVXwGCz3JW988fqLK2L_WhPTJADZJG55N_pdhzViHLtZRf8t4ZQR7bC-MOShwZ-DZINpC0xfeBBdHFYuh68QftlUgAtpsFEQelA-VUF258hRjwUci
d13ovYLW5_79kzibugoSB6Luzp6V5r6q_6e8osavKyzgbm0CmqQVwSfvEQ45qKlWr30SM11mmJxNgd79CEEqZNnkNrxq4ZWtB7T5dBFFGt0fzOQkTWFA5PQQ
h9gqppHCKtzHPyFCCCn8lMNViIPJFs_VwQmVQDu-cAb_JCZSHN9OnE9cMFOkafiCi-sptoPnbcFl8ZbOphEoXvaOOsf6zYuIOpaRckm6CSRK3Oei1pGnnjHD
zib4wkUxGOpbVBzzOYpdswIxI3JrFvNBAyr8_UtsYP7ws-rZA_NtTyDawly7
}

