sprite $image101 [236x172/16z] {
v9lhTfj038Ij-pfv_-VjlOL9rdE271nCvo_7b4_IIDhjoUKBv9Lw-I-aDNueBkUNvFYjyhEZ-bXKfovagm5AEQrHSxoJdzEeCMOgEw5H2n1FR5kjzpMxL7J8
2USCifxHjZw7olFPrceGraMffvWpd1LiUvuvmrb7-Gdc36KzWMt1g8mLbVASSwR1-eodlHXp-MGKFRTjhKQ3zHdNHWLIL11MjEsp6hNg7yE4jOfKm97bysJ6
RTQGkRlBdi-egKkwaHMVpdxvN1SFPM1ZPCMd4uKyqPn9tAEG5Jr91l8n5qAU6OarQ-AZCLVPSUSCpuniYDGnRIivYCeQaJgURN5wyCpmI76L7s_EyCpmI76L
7c_EyCpmI76b7E-2czkMHuehZZTdU6PufBZA3ZLdk88OzS2sbHmDbHEZ7jMsFfegMFOxygFD6PwP6FUexD16HTMuKwd7cJFxA-J0HirmKnKi43NthAPjZsZK
2bVXfh2eezbMSpkd0IQHHXt8jh4PTEEtYEKnREiRmxu2HOF-qM9VmFLgB2UFdZFSI-enpLcbczpbbDB7BeISrAAskLhYwzP6xvEAPSVSabypVwpQ1hBSzbFf
LdBP5yoPb4cRwKqHhyVQLg9RlX9_jgLVokgyeXNcnryyE3Xmq-nCxIwa_hZpJC0l_QDsIF8YUypQA3cwg76he6oQHQtRvfDwmDheeuig1VzdHM7BRhHwRy0s
rqQh1kfIloKaX5E3nUtGjU-q-dCcANv2viXDRgss1zfqatcMVrJPNNEcbCwV4lWmOffOHLzoFHQrRi0wcwbnZsszfe7YUuM1knYhGubghVtbDI_ZcfCQww7H
D6gGnvY20lIPykqWhk6JaeBNA8VHwjXs7YDZ_Hdo6C0-rJix2TWMIqUM0D4bgRQlZK7QEBDpGlnfOcEoP6Yk_MKrUJ5fFcnef6oVC-MqJIk4duKqvkFFqBRp
Do-YNuFonaB88bcpIUXJrDARBQlGjcXA8rMsTMsKtBXz-QHBEFz7nClOf8Fva-XOkVKPjVcqvniNtlaVeYIvMb6BUQhHjlAsT0oxJrddS18ogSYjno0qrRmS
VgfOdq3Rlab0G1ozkzBxUsytZhSBgpIk3PXjhLQTs4cq22iwAd2URLIiMFN-TNnP6t-b05XBxpkgfKw6nnPfVOGrPDihKtwrLsIDku-bBzSxM2K_KiEfFMiW
AnH7X_Nw-l9olNPPdVMc_hK860jwKstyFY1zVNtveGKsgR0KhUZCWOVz2o33ToT-GbBLgdnV_x0kj4HaCmjoczI-kDM2RZdz2hu20Ud2-W7Q99iPx8Zu6ydc
nQs3NMthte_b2wnWsucARcQ6DiFVQ3KAsMhoPh8cygGYAqzjET_CSfROM7zDMUk-g-35PFsdfCZAQODO13knt_1tRB9jJEu0UFCeKhx8ocdH8SxlO9Byrqp8
XkaAGDBuA215LfxQ5D89uAlgrXfX7xEj5elWzELMf7pdh9ms-0t04805PssmhII_89xOLfEG4bP6Mnw3g2utOF6wWI-CFlM5i3D5aFAbh7p-S2N2pfsbpBPM
v7sRT7rvfQoe1cn08HBRbfCv0syZPcK2KiRQfqtI5-6wOM9RYHkb8DKdvQn8suVL8ki8h8tJtIUbWKgCIbZRjYqbcrifX29mpipzROsaDbXxgNMsfwQWRMVs
1ZT7WxJ1sgLDORGEZqhffR9MjtmvQv-MRgeM0rK656d04yet-ZufP-t3bby8RkdyW5q1pTcRvSjPTwUzgEVWIbVIbnka7TO-hLn0Qf4pW4et9REsKRvjrlxQ
c9CzNrHzaQfCDiNipva-w_rh8rgG2ytT9-spzcdHYLpSrVtovQnzMiuh55ECStBIFclVjboPYq71laam6-NBMRkfxQiQU4rIP7qyRP7nsIZV1ckVjh54-kEI
scVjsnOlsoGVIjfdxQSsuH3R9ksoFf2shBVreb7RgXPd_xI7Qgr9xRHUR3m8DeLSVkz2YefVmNr4Qal9hV0kvOkgVy7TcxQStVRNxgHZ5Mczfv2lz_vfXSJE
HhKBoAyxf1Rc39FchaO5xMXRd3EsoYO-gBtALwQbL3lG-flqNHQzIRZlaTIh8kEkjWq1Mm8h6ZdsBrzKVBfjow7T2h32qqyltxnSk3v__fIkjbz5Ldowlr7t
jsqkVHPOuUbUSuRBTfYsX7LyhzPSSXI8WXWsmn_kVs1sh2CiqqdTeAHdnPLk7rGDMxmh5yB_T56kZVckPixaSqBOWbtfy_tg9zupUSXarwSFgg6D-Qv-plZO
vhlod0b1rRGntvNd31b-xUMxykA13iSst_NvOiK37wwDmQuKr3XdV6qCTZq0L5qRhvVF5EICUktfELE4hPmpDTZgnKCLjaB13SRMnjyN3mNQs02gV-qrvOol
ZLxnq9W_Gl5GY-sh9sVyQqy0jHPR8MTgiJLpfaqRlUAXJnjxXD2_zefoHlz8W40TmrR8cThyiOk7fcjlv_boRTp96NxjWPoPmrOek6kr4O0wX-rEpl1hJoWU
QhKHFDyvR7dniAEDEpd3hprOF4nfumwe_De3VzRDQIF8cJbj1CN37BOWP-Qq4GZXd3Q2uc4EMv0pSze8YeSvR84GpcaZA1xchZq0wXos86V6vdmCg6y
}

sprite $image101 [118x86/16z] {
lLUBUl8w3CEEBmtm_izxwCpMQ2tzTFWpj2jNOIcotSkxq0ovV1ZYomFsML9R2ja-nzdomRVYmHlw6KwDbUooOgLTN3vbwE9VDrR-JzXhMKHHh1-nLui652xy
dRrIdA1m0UsTdnQirPSHzZTfARWFh7LpP-zqGtMzrRCKxdLpaq0cfwMGMfK_QwtYDD7U-ORYsuAxasI6Gl1jqN14wCoqeCneEC9bahY8431y3vkHbZsisYDW
WhqWtXvzyUnz6J33NXGFaU7sXCT9lIwJ3CqmbGj0rFmLjSqmr9lyK7r1VkpmvEpbqr98ao8OPSrqA__4ahQNDzJakwRT6KflPKk-Qsyx-yIM6J5K2aASgVHU
Mhnwe-l-QGaEsdA8r3VIOjNaTP1aAqDZR5XwritEqv87bKPlkq6JwUNAK5738k5TpWnDHNUZLgGKyAAEYOMEmqv-3JuRhSvsOgZz7fhwl0dUM2y-SH_EKTRc
2Ags5ob2GwDXQkFRhO1FsRP_RPl3jZcL2lL0YlOvwprrrBnLgN0IcybeJhHwcofMXhHe_1uHjYqBQGWPpfSCegMtrintkVVAb9KDkTNK391bxrFSFCcIFFw0
5aUzjUorKYPUniIVzWw7xmYjM8b-ti9pURBwvPHrwTUItHf0Dl51uQMdd5vvbSBzPyGrH1JdhL-B5zO4ECLjo54sFvaXEfwcxrLvDokkjzljkg8VzMeRaYDR
UsdfyhgtsHRGaADnqc_tbRLe1zuYRObT0YQFlUfjrIKmdBhZVB9YkI4GxNgh60eGptRSsmJ7JhQwEOeBhCXxrFt76ngX1xrDTqCdSkIy0-jUvWDQ6mf0UorF
9XsAYwo5CzfI4Up5ApghV1ESnKhmfbOd6C-9hlJYuohd2m0CHLQIrmKsKAkTCDRTBQETx5nWAB8ozZwDr3RkQ-ccKfn1Y8kidBr1R-4eBiMAl8YmOXwWhIWf
SP5rpyjUNHKZAIwoSlRYbFLw2ic9hBs_LMw3LPym5F3W15g6TrXGI4CHzvl4AYOhytx1D4PSvBodh1sDuKLnpozJ-lMCi-ltSiJBd3OomiRB67g_3g_tVkqS
RnLgMN-YU8CLznQW4srlUXKdTTcnMDta35rqjsebAND-aHHhtIJ5xQKJWhSNMEcqEBBHzfwmKcb1yFRkMFcqd489cO6LJiivh3EynKgcXO4mzZPL5MVI8XSI
GZH9HjnxfOK0bI8oBLUdo7Xx6KEJ5fTF4T7-UF1Dyd-bPPQz_KQaXGJV93lV_YRQszcqJBMtJpIKJr4_DXJ5dMvldvSMladkMISOIin0PbcORo-Rbhaf8fQ5
IT31tfbfuPiaqVwcsblbCccPRo_J_kRRowHblhstMXO-2_y7G_y3
}

