sprite $image166 [135x312/16z] {
n9I7jIGX30GNDo2rb7-wD-wjrttVL0JrK1UNdv9wpvVfD5bPqbo9CkIWJfJ8NQwCCaaYBVB0d8bKUQ7D6yKD_aHIbu2HcP46CEEjG_vFeqOQCmerqfYUoP76
4w566bF9euWdGecKFv4gtwIbNxp7aEzJgP76Z4mUHHmlDTAOHeqqPbJoFU9uoP764w566jEeaSQCGXv5F15ofF54g976r6-DWZ-HAYHweeuYfasun-V_zoPq
HYRV8uutY9HDcpEAEDx2quZ_zrHAgKEcigJTeijaTDLeqoNCLer59qkuRnf5eVCau7vgBC0XmjU1-LMZwEu1Wu9-3xzfBDXmDLDJjiHDemXMp05Jc720tx1B
BYiD6mvNWnfeJt7JIBsi3AmOtCu7KPB4JGFQpfK2RdO-YFvnfAyQWDJpB31pMr4prJ-Dz16i6XkZzfk6mnK6LS8z7ZNCkk1w5pE3cYa84eyQxgPuUf3V_qNm
ZxVpK6mTLvBeNWKIg5Ej___RtNrMKmG5SrvYZoOx7gDEjU2U6oB-6GOSCGoMN2N5EKQmzoLBOq5f7dCe14W06uQHaLLGqbCC7B21v6cy3S4bUPo70Z0aixPz
ljVaCME40mZdWJWndAgg16B685v0U0CnFnXighhhqfAUXn81jeC4QMyCRydeKYdEc-8mXBqbem2pAeoDaIxDuxmf3kCzcJT6VmFA5jUKz9yt9PD9aCHOMqIs
LrVcSOw1muCYYR5644O6Nvd7EGRVYeZ4Y7HL5q6SOnYO5N5BZFsMU8qKCuOTQSPlYcZ3S61awG8fpfiIje-A613uWs7obdX17YVFi6GKUpAx8ZWn73XBSmd4
_9m26SMlYe3j_PR85NaancqFvMLsa2z5I10F1tB5KSmOR77CYiH7aO54kW1Ymh0ZY_9F54aMWwQI_eSF7Ku3S9X9aGYEYkJZ3TAUZxNZk13Z6yGdYkoFllny
3nnnCSOncLcH8uSU_rWbFde1ngaYSpBz_aDn8OO989YJEPdleEL-FSOsp0yWv_Ezhy_x_NAClIdskI9xUVCeYa8PTN3uJ940pBC28sBIuLmHmAO_Aa89VjFX
x6Ksq1u5Rin5FIylDXYjzyUpnxLDcMVv-NptrfdcY8kRCi_oy_bkID1hCSwB6k7Vobk5CHVrN17RK8Z1FrV4W0j3YNzULC01sAx3c5EOv_j-A3KOSmfdyxqu
bBceytolnpXFOLR4neKO_toMHzHXs074IGgJDcMAlZ5yKjHPcmin-evXudZq-klo-cKACAGuEh2qVrRUgC1eEdgnzDRE5Cb_mkKOIAsFHx_ehgN_haW0BWa5
GM_QZvvbrNFjlofYe4PH2T0EOWThMvTLlobIUXh09nbikpqNBSz-A6en1X0lmr6HjZxxkkgtYvWf2YLUB_EbIEzjMTPfbbU6ujVhXOrw6zhPrdNLDD_hC7uu
JCIeIFmeCi_togP01F4A7vEncQy0KTaKmAzlHUmmyoolQqh-unM4Z-MThW1sG5LJDWxxDIbo_5URckUKJrCWF2io91D_IrCC46z5zAiYG7rJNavJ0t_FTxQ7
AHjV7fgIYippVS8eRWh-AqNYIepxRqrnDcLJ1BxcUnN6tXHdKuwAV9Kt2Z40nokEJSceV4p65HXpKmBmGP7NKP5hCLfYd3PbL2J8P6envgRaC9qKASJms9Ju
EOPPaSXa2Z6cfioAu46Hi2j28QIJfhmOfqWcKuQ1X0DdD7DJ85u9fmOaHbmPYWEGXgRuTLI4JqRmJkPw30W0IMDJvc6A8rW4gA-z1YD1JflYC02F_rcn47KO
8E7Vcx8fGll1e19ZKcHk2e0bLMBCYknDyTOKe133ta4uKMGxZi9Gx1X0JePfyEorfu4ZF2foRCgcoBE-ANRuH96_jIaEnvSYf2BrJV7Npfn94GCUE0f3yGuo
9lDtDoK5dHKvDkNHBcxA8p4G0H0EdoXoQCg2nVKOwdtomc4V584jcjwmu7eCUfU-FxlZa4nTKtOCw5rmJ8QO52beodh0G1k8JnMPcbA00PgJcHKnZpLJAi9W
KEIqlB2ycyBb67G0QKZclBn2hGW3vPFtkI9ZCk2AK00a6-b4aUaA86emeFC6qPwCJyjR4qes1SC_Bs-YL65aCZC8aoAkmDWRInS8wC_sL-Kr9ONTzpZgGgBT
x-rCaI8CIsfD38hyO9me4e3jwp4GwgsD-kbvRsUA00456F2G-jf7HLe_c-zL619_klaaOwFDYsc-bs8i2jX0_0gZ3YTJf0uZoo1Q0uSZzj4mpVSwZ4Tsq3-A
EC8Hq0Lmk9mvejOD6t0cux3ZeuX6HLpjXerlWjwQY4nckelKks7xiQoWtlPaH89aUI_7UCvkXDkgE-oA6618fWw3qGrRVpwAn3uy3yc4Ap3OtRY3Lm9olaV0
31BuAembCOvkt9SLScwBrl5EiPVNS3b6CBbX0-0SgyT79kC2ZCcDmnGP7aRaTRKWb4M13RxZTCF6hQKY0yPs8WKOWeyR3R_TS7XzFhAyewKWqEKOmuq_l0vk
X7LZxMCoETzLWG4jGOmPtJ0i3qC_W02Kk74Jai2FpGqRt9hTddREzpsPAenkaF3jnmqRiBq-dzWH0DBXbbY20M50qj6D_WytR01_ALA1aMC3Iz8VxCqD_RXX
WzULiRmrRYG6aWOtUhfXu_NXiRnLRjZWnKZiRYpO3i2XvccibhXX-xPsIFySZ6vaKZj8cHkElgnQsQQ8exCyx7GZpONMQZ3-R6xOqX-HKwH_kM6J8hUAARgx
iThSC23XzRaUtKXhfAvoD-n83hNP3HiBNHvAZ6wqVxZXs0wVzdQ3jni043KO7kQ6-N5ZdoByxePgvqRRtB314XA_kI7AtB3nhSbsVCPNHnAJ6pKO4kd6EhZX
q7f3I1hTi6imOFYIwOCRZfNb2HBKkm5tIM9s0tjvl3bTxaOkdQJH3R_Ti9NdbMY5Rh0g31BBZnis-GnpGuwzlPLkI7YBNVtWXXUMPoQnxnNACEuCjwyRnWSt
Sdnj9bkKkP7o8MbmGtPF9ThJVeDOKEL6Zg_zreDzSCCuqbM9IZSSpsL5WupFmGqsVrJe1W3XtdGZ9J1stiodQqylcABpOY47vyBHZK7aYYcwko7SYHnOxRcx
4SO1DhZQ3J-6fHCM3vQdZsxO9Kq9HZVQgXkx0-DtROzySGs6_tBf94rkb8Kokv63SmM9lySD9E5v8HbkptkMz-164GP8CBiHvixQa7HmeouK96Otjl65XElT
u4zUVNt7RXytschtPJklOZVsfPDyNng4nuMa8s3VklbgDvOTmv_1kQOR-qAosSUxJXt6EgH-S8DXV2sRoHOr6FluajG8OnktjhbXlvTEqiKOpyGuVlFu79PE
iIyaXwMJ158DXZ-BXQM11BCRP73wUPHWDDi0eNNLWYIOtKXpGUgw72ElFTb6zgNJxeRVRYIiIp04ztqXQT-7fTDoidIgTcDVEY7KPpVicgO4eeqBoOKms-4p
k-4Q36jquslffBRyjdIgmHZTu8x11lV3qgdRs9KOJ6xaqcc5QUbKXO4a1ZVsfLExaLU0qOswqv34x8QZiJnuOzQx0P1VyfSRuzAftWqdoBIGR1WxAOlT4Duu
seyR7XQIdMdfL8VH3Qz0qhIGV603RiFIYI8txePulOoaT6DUEXcf5CDtcvVzvlXUI0RWs9TE5Q5464oOYB1t1t3qT6DQEfLWP0aYycUj3p8kWnko0H1Ihy2G
0C8H9lnMXCcDSNprVXd6keSYGOOIuOXjS3wLRkHYeM1yxHW2f0mbpoIGwClaXbsA0LA64ZQHYZnP7lwumVLBfyU8OIU8FsVYbq5YTeD234DOuXDAEB0boJ4l
dOem7eRNEuT1r7Z5l7Ggmm3V_AugI9keGJYol0StwZ3MZnL88aCPVpRtxeRhGd5mgAhVeKH4v81plHi0V5KrGt5yNiBiXYyDHH9iLOsiwYRgFbT9Dwemu5XL
OqlAK8Ro0b258U3tggQeaIz948iQ3CDULOS_LVr1iYDmlgGKmx15asSIUrNVeGmlaN09HZEyFbNrKDLZURUbKuyIDsvcgAg_gXhlK1omBJvQ0KPUYS-hQkFm
Xe7HzMu0zgUgCLRLOMCZuNSeZZ2kK9JvIZnNDL-I62ev3GdWTQWgMoZ3IqenpgkQekulsQ_GDQ6SLFNr_JmBBiKWupzzddM-12x6Q3k6jsaE4TuAkvVNGtdX
KepRemyOXZ1PLJDNrOxmZd0Pnlr-Vsh3k9kXcDwhQebuEHBcCyslnBZVLtdju9l7gcwXpEK5uCh2VdvVX_iYt7nSB8I_osk70x31N8kHA1q7QSLF3l8hI_gf
Qiqmtp7I4VvfLGSCgGIZYx6g1eaCPQYg4uFhCPvh1_K-L3MSvVs86bjvmGKOImSWEUQg-kN8b_Wj3VXQZ3_tLG0ZoFyLToOuheGm5CJiO7F_wturwkU4YVmt
KBeq1oZ9KmxDB3qmbCzKHRVvnIcDJiv5QAY8bUfw93wsHIMv2yghnoMof8g7X6LzzNvcA5B9tVZAYav6BnOwBqTYtQ97D9ftRynNEiiYegaMbmMfOYWYHvOv
H_U3n3BcbueWrUeTDVsSbNDRLBBxX0hUJoUtHxlw75p9-tnTwME_7zgYbPooJWQloOF8JBLvJ_NuaRW7PvBUtWhtYfUJhoUFn8ZKXlBKK9CPxrNB4k_kCfT2
xW_ufXf3qCmOTxnox_Srs8r8RG93Ox0iyLf7ugr8RJ93OmX3P0ZM5nI0x4LgGvMX8H2vXw8N2ykHU2DIOCNBcY_YjOx4-v7QfAuQEXayfyYGTOlkHsfJFhQ8
VR6m7wcDBqEZqVrkRz7zIEt9gCOjOX-9zoEreIZQhax6sg9sfFjGKOt1AYA6XdcysiVtLxlmc43ZRAGsKLxjBY9_qk3aZbAqNOZOMzIET1-gQ1Udn1fBKutp
aThx7Utgwp-ZQjYHdYTsVFnVf4N3ZlGyb8K7vjBdBS2YOKHw7b-7pYNFv_1v5FbJfES9ZBdqC2dSydU-ALOIUYcuESllaRglKNdCRRve8D8lSlyzS_wXmS5z
cNajqg21I1yWTUO83KJw05Iug4RtxZ4yD13fKv2_DBnx70e797u1
}

sprite $image166 [68x156/16z] {
fPhDikCW5yHkRCTmMirz_xVzVX92EKLgXfDXvPLABLZwvozdh-Vjvv_ExOnGFVu5SGz5HAZktnAEgdWUgMpV4BQYY74KzziN8Qw8w5co8QQJohBt41D4vxOS
Oa9CMP8XqbcEYJ2TVi_947EMMpB4vooVGqptcSvoJ3EIMVh3JaAYP-dtEOL8Pfb3fBFSfXdfBBVz7jF9PZdY7m_jjeSYfAy9Rjwskm6-WyYjDT-sBMpx6ufe
xS4e-mxOUHVSEWFE4xfATaPd22F0NIL9w0oQ0TnT5aDC32DmLz5QY9bXX9l21YtCc1dDjf4LtMMTC1ZFWmJ4dx9SGamCw1G8HPjTvX0p0mP5qMQLUSRC62eW
R4yKpJFcBOFo3fb3p0oUzmBO34h_K4Hecl6PuMxnHW6GejGtmdnuC333Oa04O1txuRR0i3zIWBfl-tsLqG7lMUBOjdsPCGIkMK3dkaUxpE22ikE-bvRRyYbB
Ms9Wy5JazR78cE-bGm1M6VCC0EmC0-OjAG-RZxVBx96_bmH3W6r7vOsIOQ0Gs9GIRfSO6GP8W1rdqIYIPBJsKgbdiPs_5_2lFGR9dUBS5hlzqYaUHP9Re3KJ
khxt_1RiNrzL8B_bBOjPRhgzRR6vPd62qRVWNr-p93qmhotmofBq-ErRUA1Qp_Bzbfx52knbXYtUj_2u9ea40zIt39JZHB7Cm032rooc0Xc60UbzYr6EOGEl
BCt6SKzwW0tNB2OWrnJSAMCBwmmROtTApvBSOaBWAoMznKPwKSQWzItQm00pnN5FC2o19BqFKcGO3CWR1MKOe8-3K69B1vJpZM8dUaG0Y7BdaWKoZFAYn7LG
paD68TgeItvBCH11QxvSKTh3KHJXrkY1rxVi30-LKCZDq2a9HlUemYXae0VECEhJGyyiWfUArXanFCphdX5a6DBmi6fL240YqnHHGnYhIgPJKnu6nTCZwdDP
258Unb8mF5mX0f9tgo9fUFHxpda0LOZXOI2KyuWY6wZ3moRjKMIC5CCZiuNXOSv0M81JZ2fr3o0A8k4HdM5HNnx20E0K8mpebC54DQwXj0UE05uU5WW4UDt3
r1eILbIFUn4uuI65B5I4SM3RMG_L_ZPhVJAmIJ2AiGWP4r9dv7e0LWsCNMf8tKCP3ucNXrGjyXvXYD8zulh6KlS2bE61Io0Wv-6e0EQf8rlAUwW40Yd_neP7
20kTJm_yJOyeCa0T7iunkWUc2B2mKnu0xXwEMX4LasM8a31MA2o-yR2ZLXbSQxZVY3ECAZTJzVB0LSat1dPpztbuM3RARcbsQmXU7kjlx00RXDi3WqfLzx1X
dM4OAiJbhQymwZ6Q8ZUtvcR0mZZ50BTcH6lzesGzr8TOk2_AUmm3Cpu4iCQOc-871kMQngNf-42IrXdYpG1e3TlecwRzUaN3pPaU4eyOzhXUi5SPnfPvtQh1
e-aYOo-zXwVhHQmnjkqeXHXDFUA2MVJOjssxzo7Nwqqq_H_YE4je632kTutXLhSpm4ZkJTMRMajDtNxBpo43e7pJf_7n-FdbIT7JGDNGT_szgS_NdmRLpGO5
hUbdNspgrkhsCywkrcmZmNcmqjIjQVzvEtUQRHFogoc-C6O2z_aVak87HT6ReZyrTVduFyjM-w2WlJUT9MBxHEXPtBEqXiUMASJy8ykSHP8_DtM_p-dCML08
MymUSuZvRD6pICFZ4c9V_FbChR-vAl3qi5TEpmAndHwCESHA5hXlfmQZRXb2ps9YtuvInyFEdqFclkrxQVF3pcI9_pD-fuUTod8U-r6cXvtkil_LuRy
}

