sprite $image394 [443x348/16z] {
xDd7SSL034J1Cu6jKlxHoewykOz-TmXyHQox0m000000000000000F190G000FvZE7QkA6l7RcayDkqAuqdN74-wmgd9jQ-cAHxNbNHjKrEufEkAn_LYesR9
uugDiYLFkAGhcvh29LrRFELYes398s5Ye-378tkHsAs9HyB4Hi7Kv4kO4Q_6rp0p1Ur2kiOVBwJhZIVT7_4AxiQaIpnJiokT9QysdIMlpvzXwWuAqkrOychI
MVAgq_N7ayxTM4ywKxCzNN-ysIDTvTtOdYDTuv8tvqZNE3LdZtILyH9EkhObRqv85mNFGGadNUFKp28NSpidkmTsxYL9GYI60UWMoNt_wyv_jA4pIr4eihB0
tiv_NY25QTnLNuudED6XwTx4uwUoKdH0q-tzuo1bvPaEQBgjKrDmlz01JRSZdh9oJ2UxnYEpxyRoSA9x3Xv80uvayi7Bbvpey1Wy0KpbPBS5dk06TC-mA_8b
7W_8ReDtOnp3rVbFlY-T26PuX-m-_swCDORZByfFE8qantHZkyLuzB9IV_BTwOGtePDT7Y-VbMh49z3DA-yOsAsiFC7vMVaCkddbOMuNgBnuoUbFVj1f94Tq
icF5KZE_4EXFVXITy4Pq1o2x15w-vFGdFuvEgJcWartqkx7yGl0KEWCFXs4NgBpCGl10kd5gyZWqiikaPhxa7aHduF4mx09uWP9xEfrIKtG3kq3bPHU2fXEU
w0ox_8FtHiardL9JT9wTZvT_wzLq6WgFXsdduv7fjrvDToQWw0PsWK-bimj1qoarUOpiM87K32m4pwHpy0xDO3aFuAKMWgRJaA9pxNmy1XQ2fXiFSHXseNTZ
aP9hEirXs0LICxGGZEcQJYEx05vm8MYwqk22dVLkB5vocgOpxAvLNc0XCEYQphRpKpEq4FXqJIUxYtZXajCqdMLtfVAI2q7JbOR7t2xmuFabbw5hEYru0puR
pytAfjDSfvETvXqyVo5eEGslqCbEUlARul4LNGAkwj6daJuTpdxbFtYHXU1HlqD5FquDq0tyFBnuoLMVHlfqXjyOBvcLqcSzupGoH3Vcu-pTM60XEEbNdqPM
cNHpl_gPF7ZHajDV-00wfMQUJdv_mzGGBxSGr3DF8yaWtVdXcRmR2vTSdqRcwKOFdh8oL7BFeYiEy89qGxpaGj2daLKQNAOhqGtmSbdvwDD8SWtT6EzTEFHf
91VI5PCBmOFfb9hhw8INAha-ZKpI_KpfgfWekQOxfoPZT6Cx9XQ2fXFU0ZeD8oNNT4hD85szcanMDftmrj6buVeqSXbTB2kRJdWxqbMVHZfsM4CNoigc4rw0
Zc4wTvFeJsWNqULAhkbajnDTmN_hqdIr3rrnwMbaqrM8JYNdJjDX3xhwo6baqnKDka1MvkcQ3dY1v_yOlEd0HNHAE_fquuMWwO2bT3zyPUULNDFf-zLLTAy_
aBTAhkdm_rXs3D2z_a3UNmWQ3gI15wIRuxtCoZwDX8PLmbj2DqtDN5PA_8PmefFTChentcmXwDD8oObkW1Ube-YcgJbR2Feq4ZZH2MyLdV386LqbFgYzAPou
XBUCJdX3kcBaWzeRmedEiylJwIRiTxhK1xLtb1ETXtUDhcRNTJpJCNOrSaSuqHbuMRfnvVtoO_0-ZGGCEk6jeJjNNgZaRaK7ZqvsI-ZEgPahESqTuKJduU4I
dOv5vdY9XU1ET811Dy1RGwVAosMb1hU0y-cA1CWiNKs7sJDo3O0RoDbqUl0MqXNJP-IY0su0PzC9Rm6TXg65u4o7Uy69piDZX6xzQIJmXNYuHYUxXNJ9CtBH
VHqU4A0JtaKwYcxvQIJmPNX0X4vuEz9vcmI-omw8qGbl2LqIJdJVX8SWdUomXYv-OGTy3nuGf1FUDReAqvNWRBhzxO0qdV2MqCKlxF3BR0sNfoikeOjVsE7N
sLakJrTOHfUy6i5WDeRBqz6Y6s_aDEW2P-Gc7VQ5ozFLHJhW4wUHmEvuM427QtJ6FovPSgBR6mzOGSThT7nz4sOj144wu1lXH1Tvx2BNTLL6LeRfi2LSdeuN
wOely99PAV5jyR2Ghd29pZwDp5wDR8e7BANZPJgbveBJo88xsy7bwGflqL5qAqyZ2O2r9nxMqp51DqxDu1av_mE7Etl1vUaA0RenNYeh1IUwZV20pz3n7Rho
hkkgScVaUbAncHtmARf2W6w8bpiZfxNNhSV31-aOePFT-3JoQbQARYCyu9DqXG3T22-q49JpDcKz7l1XEWReHgbvVI4uWMCREyJf8e-TV-SpFIZFB0HNwO2z
uKGNiOjSrrKbIqvqE-01Uz3n7Reohkigi124w80et2vqXIoTy2fGSZ4wvEGsecEOJfKNABaS7H23s_cnYrpN1HQ2B1sGWDlDBaadl41MXkaGWDiCZmQTVt6W
2S25wO2yt0RlLF9qWPABqm41k9tmk06TIYv1byV3hdRuD9soCaMNjziL3pPT1UYCh0pGXV6mAHvzEbUkad2YUmOUMVx0fdFbAfcLediCNla3aywMgm2SGzUL
Hu-kTEIJe5DMNg7hoeD3L___ppOci11uT5rvifjk1bLbuWMoqgFhogFevd8kdfcL0RgkF8Xk95SQ0y-32z1rvSdEa7Fid98BqNLgSaPN6XFFABaCNQUcx8o_
sC4piZ97rwc90PtnMwLDEcLbZgxnP6VyLSw3PsHbaAuhZw9p_XBXkNI2Iz9rvSdEMEWTFAFaedITcZWCDwVoZ9BBqlMxCTzj_k0P9PUbwyeZABOhU5vMvkbw
oxkCPsHbWguhBszdP6M2hYilZnU2Mq_NgHagkVLqZHSgkVLqNNd9h1HTuwruy9ILtqRNgIcunNIimeNfr5HM1iSWqKThLwRn_cJlpfQpPO4W00-2Yi3zt-w_
1DC5qQmmn53T9z-QewVe0NoNr3LV4mdvFpgEl9OCXqD1RyPmvBNa5xeo6riHfqatVslsXFlIz4elMKL4Dasu-U_6HdObnjmkB_6QSlEtvi2knDRIP3cZ2ZS_
thYk19sL7AiAD__86mU7KITdDbMv-HVUi0D1VAMBSiQhmisFfpxaS99xtQLuEQCBDp-UUbVY97VO_DiDequLRlwHD-ZMwqNCLxkKLLTk_eKtwDRBcunLx5Ay
BjpyUAf33ZVDDbTajKjHXfk_DHM77EQSWrQnIrb6m4rzDwRNbJZ7BOAEB7OfJbbk_jRKwqhG2R96B47P6-68ftOWmBUL145iIib8ZZRS_2DFxK00EY-2O0tA
eYqt_yZJEyaTUzwbh298I0T6dJBS_AsfSUkLvOpWGG6oOvUojS8HJ-dMAxgy4yaDYJZiKjJXvXzvIhTU6Ggx52JXCMkh71TUnwx4ciEf6xiKv90Ssmn7l6vT
YLLtM41Xbu8uZBfMEBPcDpWiEn5anoxbRNop7F4w3JaabbOEkvHTgfXsEBPcfo67X7AuBTYb9AbYs-68rwChGyH_VDEOsAKa9sNMTZYsPajNmYtd_7EfT9p7
19i94QylD__TM1iStiSS_URM358gRScUGozAcGvmRCsMhiG9t5iifhenRJe9OpBLg6k78ruFEAYuIsD6F6DTHH3N0OuZhxah3oE8kJJc2LPlFCLtaEF8-zc1
0DkJQANCPO-9XtF5DVJYUy2nDN_KbIZBNUhiQCmghZYgcwqF7F6QdX1OkTAXCUjZN4ZhgTX9ZYFl-t2G2tB9ZiQy_lKk8hPVLtBX_VnriLxUeSCAG_9FYTax
mX6lXWijSg0xKhYxREwxujYQ7tRbEvArtEelTFK1NAp6vGdnFkZA4DExvpaFEBoq4dINndGQS6pDsww4q7jr6M65Fu3ksfYx1Xpnq9NthwLqxdRHsMBDfQL6
kZQcYXnRyoEuvE_AhgpBXFVnr7G1XtMranplnkw7N5voYuYuErLJl8V0tbPZYjgtNcnD3BdR5y7UqmL1NGOZjtGn6krRBwwysrdsmTlWyFey6-xkC95LkIjf
Tqt48xXxkXWM4J4UO-wUpeiT1aSyqDcFpsGYigMYBCs5Rl3b2V509v_GkUe-9TXRkWOvucdH7UMPO0bfAUW8b_DCkbW-gbjI-TytmY4Ff0lb3OgDrNCxHxWY
ZwCxrnpagglcbN957aPNOfcOq9UW8roHXz1XqHroncC5jjvw4K-VBc3GNMwVpKwukpo5BfOFoCyhQdRbnta8NTMGou9t6Ll2VP2dqCcRs4DXo15FWUwGEWRN
bPJxABz5XqzDn-CWn1yFWQDTkD2157G_UjSECvuErr_niF4DtRU673EQhlpyg53HcM_ACOFfGl4co2DwGUptuPYHT1aksjVNL6B9RJ-2OqRH1NnNu2lTbk7M
7oyvPWZTzWBdgrSo-zMvfY77ZA8x5a4wFGPdHj159qMwmJ7QTEicLJhACPfqr_I4OmRIsSvmp1WwbKSxp00wi-aiEKQRpgd1CQfqLhKh6JMwPTTUSemEtOWX
noZGZHfoJ3UwyKEEwKXd1WyvfXVTEXoEQQJxcqEEU24UkFNwQt9SUN_srejuPjwkvEl6_csF3eW0W000Y4NGlwqIuDrMOMCtmdE4u-Z64PuZ74StZd0SuJd2
SNJZ2CSHdYCSHpUEy1pXEC9nTEC8pn6Eenj7U8vm7E4uVeYR
}

