sprite $image139 [238x161/16z] {
tDOvakCm44JHcTu0_2nIzxzj1_UjGdIR-IovFv0GyVgR62m_5YzJInudjgqhAGRop2qSn4f-kJr7KgpaLel4YLnh0NMHz3hMhiCbdRC0h5e7qKcSHS30h7MG
pHcVMXrZKIX8sHsiQAtHvRs6hGFeEd5XDcBQWf1PRvyTx8hqt-hBPiHdH7QylSE8MuAGHI_9XKr5I9mrgn7VpxavjWuGMMyr674kVJppq2_iFPJrDeCHvwG8
hYnR1qhdt1jSs1JvwyhhOE_dRDLQIztFEJYJdl9Cl5S6zMREpxcmjPHt1pjfAvI-hXumuhMdlc-jq3PaSuP7N5WelyoQXvBRJ0w4BmpG0Jg__zlUtIzI8ufB
olXfgxnTmJbyXKReMPtpuYxNRD_6qyRttZekdV6w2AZyjNshlXslUvDuyXx-KlcuVM_L65VVDDUvrRxbdsR1RyqwLM_QbxDzfzxO-SVtRDY-dGr0XozNjzkR
R4JVfJ_ncjZWvGclJ_yEdsTVUQFlOkBZzksh_9-RJrLLlcjynwnJRk1sNkhsN_ir_y3MwRGlRKrTVTgOh1FtyoQkqj-M6x0TEzSEz_CDcqXzMkTPS8Dh-yEv
heQ36j37TPu5FrNR7tlMr70WhKzhcmKRdzhuY8a328y6wuVjx4V5FsPYBIQEaojGdzDgvoDzqCIXP9uarWPlMKTYpyx7l9yniPJWyF0XwWplR-IXV_lO5XtU
uopeZx3MKAJYjAuilUSr40hz-zWLQDbvLzvgq5uudUJGK1A7Rsmhf-RrVoI74Zfn1cWrDBFWzbR-tOKr5nFdlfpxb7DkvmeF8NY8GBeqrRHpLOFsWebPmv5A
xcFubjTyOsS3Gy6m5i6fZQgilkxBjwf1UyN42WtkJFmKTuyKEWZl3cPwcZWzb82kgkngq5vWDPYvC_5ENnufp1VQ6XvaS8M5XWSWwgBigWRj1HEdXo857HSM
P-shwKs3uT33n4mWD8nVO-tJzbcfy62A9wpdTdwmqeC83wqAXn35_R7HPtKrQAzadIHIet38Ucvdgfwi7kGSRwdXGMXJzekilqwxOmqFPOYxXctmMgl0K2Zr
Ok9PM0UH_ZSlcBXBsyywhC6qDZBUYNeL7KHuLcze2CFRsIN61TOkRNyIhvkDHo_3nxBrgl30DB5JuI0sPHyQgv5vksBYIVknrqGNJrXBBwexqTR4J8_QbTsh
epNC2uMTj1zx9hOFUFUprU7jxR_CgcbYrdPsKKY6HuErJzjdjTru6Tw8vREiCqiNU9euzPnThA5CHSl4nxI_P6B_5DUbToRsKEAPOv5WF4qC1p0S3qThC846
wp6owpfhUKexaRlsFJFny12ItfHQGvDrE31Dl1wb7HCRq07jZrypyJ4llzpvFZOn6TgSYN1kBYOoDHJ2WrmPFTOgzcdxhCUuMFLINeFsLnEVPvrK4ACMlFKe
9PiD2y0jsdx37lEUN12kqjT9Z7acuiu3SQ8xKk3wYqYEolPm0bHDsdvXz-3xsvWw5R4riVP7DceeZ6VHmsZdkYghLzi-wx9h_IAziDfdg0vbRhBEmlEITNZ3
e-WQJB71Qi95g7IvR-lGnBMGU2VnTDTCiTP9FEjwvzb6t8d6MVIEYG5O02_tRHqMTZQXopuixvim2eI6OiT34PJamLoopWouPi_41h200gmBj2Uibevm9ozF
MU71V6OTXyV2ivZ2hsLd3Q9z4WlGCg342rEgx3epyJjU7xFEm8vdrXaAfbVMHyJr9kiKsvFOIy_JPzV5tzywLTghgaTBtccSMXLBODVgVWSpFDJCEfFLSXNX
4c03B0AwphetyUvh06xnma6CoUhX4EDnU-Mzx9XP9vD3lQm3eBY0mWHqDAKkR9slh01uOcVjb1xOc9XBO5zP2OR6C-iusbb70FqwZh-MjZ696wplUBKNZQs9
FRoQE9V0lh8gDPH4is7NigeCUXbG5dsHjOuR5bkrsdSVs2L93nFFiaC93aSxi6kTmlEwO0bGSnGt6tQdTllAoU5WUes_1ECbwqGgMwTJLKbL0ik0YzFE6rh-
feQTQhVl3EoRwBETNLpFn5PW9rG4daU50NZjM_o-hODZiMTdGzEcgucfQU9srY6WEoZNAVMuBbWb-kUil63YAtRspE-fs6OTHxQppZg5zPXIIqtARcwTwwnJ
RF1EXO8SDREEkrbdPbY1In8hFwwB3soTgQljEql9bIwPtQmpConT1gi8J5-xUpfL-KB3NcvVrb2Ocu0hThSEeVAcNUbrIh6pTNwiduuhNp3nTJlV5ZpmRcBt
D-pZ5fxVCTOjrDywjzl2wrNNMA6I6dQUYZNWzf_4voqimEjreV-LToUuTVCm482xr-2mqVrFsyKomlSyq82A09Tnvb-xwuF8cCmAm6OQrZjtS3hRabPJko_b
MrzmCzRGxjswxN-KzUa2aIO30mwjz9ebYjXiTXT4jeWZVGn-cYuGevEE8xJibM_KqM-yopvzaRD6xESn2x--bAAB5Th0Zg_Nh1yiKSIHNFlcYpZwTdkUBhHL
QzdxUagpBLN4kfoNh8ZNj1tJXKchreQNCsvVGR0tUjaQEzxHl7fqqjg4jxyfVV3KMVBgY-KNoZ5BQAlMQcwqhshOrVRLrfWkoBgWLLxRLCF6HBAfzfqiOfuk
OanSq-RRLrdx7AdAEM_bwSBYObUr4OXo5aKSbo_BELF4F5s8XbtHwlPLR-s9QA-moh1rNQkzkeWZ-VQTirfRrUQzMUkeVGCkhAcBNTUUloFF3Q8gP-01RXSK
iT3kozIRhbVCqVmnuVR0lS0wq7P5oYkgMBmJ72t15nGnQyFQWxnNRy7ZBeV4Qkkw5gUHRuOxsWhL3dkTbRNWRTkdlHijlXMihALZlR6SDxduHgvhMDRQw4m9
xxaPHSDUCpffBLmrby-tRsBnlTeQsjP0bxjKpjWsRjYhnaIjjUF_nakO-xHNMYzhMDRk_mTWu3NIPjgtLCE6Dlvl_vjFrhN0pFNMQbWES7YDhCVRm2plBTQm
d0FxrBvdWwNQjruHSxhqwMbaV7xBSEjQG-ixDifvD3eiU6jOWnlbF3oufRo5BvQzWBYaLFjMjKPU3c_Nqf5NohcGDMBUhIwq-NAkzDJHvMncfbQ5r31PiuZP
Ytx4n1welAXiZNBshlM9qPcvW1KkuiX-y7RqC8ojNMlQQyKlDeAjhqMyAbXFBt9eRtqhZyxHlZnEclHY8Y_j_-PvjigEpi55_OlbXr6FmyYglUMjp7M0HkV4
mxUiDRyg3B3SlYZxrCbxzJ1fP2r-iNhpbTeePzGlOfrV1_TrFXBNY-BMV3bthME4jVrky_5MDJ4w3rO5irbjgnptOtJsmUWyfst50yHh9azU4ren9jONWrS5
irbjUIUFpcvX3UrzhFngsB26zYvMNXNiCKXehRslu75LE5lTxtEnNCx1zIFtiRANlmh2mbEdk3VkraDRjc7NLuLkxNofRUyzfoz40w5jTyZfIvMCjEqcCV1r
SyFUDwHjTuuBwzsrxGDfs-tZPBsrbgttrxOFf6qV9Lvvr_a3
}

