sprite $image389 [96x121/16z] {
xPdhjgCw38D9I8WbE_F-ZtjM6-gLjimkK7Bk_ZFtRxCbZsNJQKgoX6bOnK9IqZ0-2O0iSH0VIW0W1ucqcAvVeGpX9xqL0SeOV_LU9354eC07dt6QmdAv3N3-
F6MGIDVoYpK-c8i286M-afzjTPY5tgiNycStc6id0LTQ7Nh-uol48GOxdpUFGxpMOAhpcQSfuQAHaL_u2d29GeB8bnbCzFnIZDwhrnZSym6gNZQv6vZE9m3_
2HNVsY3D0EtuxZK9V3iobj_pJI-m8Vt4Tnl2Tn7GLyUtrGPe-TRW1cnyNQlQ5V4cvlXdlbMx8jwM5pxPyVjuY-TMiRIBFuU59F8t1bjzuSEd7vCe09perS1d
lkEjBcbrc1GgUIxUuFso2kByUROBugtO2dpXLmjlyOOJyHQAsif_Vdpwz7kAdvi3yP0DKQpn2tj-cIRPZBUmuE3aJZ2jjeGdVlBfXvw_p210v4D6P9MuUkto
-_HxZZSn0eSdTrYzTZxzFmT_5syIpyIzo-_J3zhpNIaUFanInxz_zwAVuYqVctPgBl-kUCF1-p2s9xPVF11lXsoOOMgLysQyzV6ZUl9wozJyDlrKj-E7uE5u
2w6RVdlYxSi5kEVpD_6PS6hPop_4MtSTHY5vPjcRTPjlLgMBDwYFZClYBMVdYtgldeotz_YfSIFUYEcgUDFk_AV_pEFjwCWmgtoADqpXFTx8-MRQiP5HrExF
lx3dBnlnHZ1DiHmU6Q9QDGNsyiz-7QBdvqGUVgKKYvQ7rox_HhoHB502XoPtN4GahBkmoxyLRoJHVcj_BuKCYE2kQoT_xjxlQCUdAwMwRxLGfOYK3F99VXUi
v_T_HtOuMqGQ7vujBhyRlCMtMlDdlDx92X6igjvxrNurRVCxNvrlSSVmWQpV0Dhs4AEOrYgXctvTzNpkkWqWmfu_JKavz-V_zlYsMdR8txHNnKEVC8NSTJP-
uATzRqWfSfVfpfSfWO3_K_aXViAkzcpFpfLVPiMjukVhaBi3KeIwyjVbbkaXu0l_YFp-Y1Ge2nxB9ntVxqT-dRZy-nC6eYKK8z9TRwRtyz-SlxlxlSHkupn8
2L4T_odUU6J-z-tIy5wPs_5MJhrDCvMu_Zm-tOTMBP-Hlw-S5gR6pWM8tSvj5J6SbDz3actNdnSX2UP-YAUNUEDH_D8oQGc5Qq39Unzy8Rye0PfIVPUQtnhv
2_d5rYOtitQwl26ITSFd3BzQHIv5WErTET5S_ZDyCy_KxUSBI-lLN-KqVyTzM6qv28yvEFzJpP2ZucSGzBwxkW88G1jVCjB5_5b9iF7RjJ9V_ocYDJu1W1gk
vbjzP22frTAI1_7RONhfnzwpyslZAswbUHXV2MejynB6y9jA0957yUlQIZAChoHe5YxXAz_vRQaQoRVh-Ffdy9LZ-Hp7znhFrx5yvM2-_Xbyqx5yyZ9-LDED
kem_pM9Z-5w9O_bJiNyh__Qd__DdsZ2-luOUofzY6SJtcc5Z-5wPDepl1-8GlbUKSNotOHZVRHZ6ztTAW_XkGtiHeDEeIb2h4gTnjV338Vm7
}

