sprite $image415 [122x88/16z] {
lPU9Tgmu34JBkrNW_F_dpa4Gd4PDsXFFK6-XUKlkiQubE_XxGiqEU3w-a9I8f-EIK4J86l1eOgNi8Oj_jj1oXlAKRfTtRiz3kbNm9K_e3fK6t7K_8TY6ajnp
WetkvmHRtKy8VaQt5VoCRfU5mi7ybxgZ2Yw3CRed1RDWB4wuiREV5goTzE_8NVViMNYGNVwOafIiOOsJPs4d2p-cAjbqs4mdALasjcWeFzwEnuMikjtKgEna
rfprAzTIkRqLQbsBS7-yabNtxAXKCZE08486939fnmdfaIaKXo8NikgU6vLA5i01KRzOOW4ya5aYDd89C6IZUqYm9JF3oVRB0qXBX6T4460ZLy2GZUw1KQan
Quu8ImLgz41YG5eod0IlvE0CsUWU69LtvCYDpEgGw95s-nNgkHYoqJqiMCENDNVoiUO1ij4z99Wimgjd9H-UFT-JIGxhrb5f4k65bxqjuf1Oz2rRibAI_ZUZ
Urnm0E0gB_qixkndYY4V_yyLtbsNh62RulQcEMVONlpIPvY-2VMXCqmJz__sIRUzLVACDk_tBZxjwVFrhS_jBOiwZMOv5zrMSFsHe2wKp8EjZmFUdqVXznHT
TVYrksErFcm3E3WfOKiK9lsGA54_59QWaMh-M-NTxLWxQO0CxIfDPT2df-XJ-rfJ3Hd-jhiNYWqTR9pKj2KBYtuebAmVAclII0NSTtPmfRmDb-KjEiSKjwGO
az-Tg6UDYBtfzZj95GtpRQigTrsNjspsPAUwAjpT7fGpnvs4GYRLG7cRPMrDoPrj4u-QbTTxZkGUURs7zGbKRXQySPMiw1ksFshs2pdbaekczdjOx8fjeTkw
TlBTilCnYkx8AJYSIPtC78Itt4w-PxFuGZ5asSbHI-AE8BFQiyeMsf3Viqc-ks_Bzt9TIFMwmqmCrv3lT1zagJsAXOy_TvWbsqAVvEKQtfEliz65bBV8q9gL
QyY6FK3MvGwJjT26FC0srIxA72LpKUvdijLjTzW0sGWsv85bswugFPPiH-KWMKDBleaXMy73vCwU-FxP57g0R7Gh6V5pGYTtxa2rRTZ968pmMkYsBkqDESWw
mcPnO_72pZqOlfYUQXA0n07sS6oX6t4XjxR4uxQzh9zrSp0lex8jPIFdzW9USv-4TK3tSBhWrhnh5t9hrGCz0xf7qmLBNBrRbTov3BXaMhSLxDr1BkqKd63Z
oe3kJ-c2sLhOoG9fX-3YO3AbsnQQpYqxkRNWrxPtaiTjuenkBkV6QWK8IaODO5F14JRZkidFWYNNhmg775oBW6EpWl4NtRU2T_0Q0B2YEi0tfhAsMy5Mzt39
hU3LkngHAoY0sof_Z4gJATtsB6m9ozUoaUMhx7siez9aGhVbAcNhNIMphMnzL9fCwRQNZbR0rWXHSZEZKZElst3tOgzVoJN9vrdubqH-O9lBJelWbw2szQQJ
XfD_PtTkNtD8I6rLmGutcTTjxpW4T4UhuCc4kewkMT5rQVOin8JkGRAE3XKy7tjTkYURit0-NdKFaCrPE9yWwm3PdeN_WsvB7XoLyxgLF2fuNlSDUN1Kpkks
v3P-5ixhLlA4u2dTIlx3g9pNhMGxAX_GRSx29wBNfObEcjEzh2hu-VWwrKd_
}

