sprite $image131 [191x207/16z] {
rDeBZgCm48JX9c6mSLMozp_jFYq9XHh7qwojwJh15-lF2_WHThdyNbXz-JD4nXSWD3uaVwtucFm37WZQJKm-AZuc_nKFXCO3KQEl2uq70kaX5XeFXEb6BpGU
YD5DJ7vvfqTeF12c6xtGU210Dz7u4FWm_AV6wuM9NYzCz7fXejSBqurUQ3mG9dgzC1-MUj-n6yRWwsx8IFnymaVWQpmOYY_mSVYxw2OClmXy1Bxk9WfVuuFm
TJUH-4-1Zy3NtSJWQppm2C0NqL_baxFvwOHtyydfV85tyad1dzkDdqyA_cIydy_vV85tyad1dultyqd1dzoDdy_f_ApndczTSZfVuUdYav8_7KywuY4dytNq
f8__cCs7n0VXFsKtKVWQ7uIlem_2pn8VXA-x2S3lwGPv07yMdfiPNdNyBlpdcsvmCrlfutCu_umdU5XPR4DF-y1qlkxcIEFDTbBmXMfsFFi1h_Y5_B2D7NnW
2bz7h_bblHEsy3qVcCy_u2L_CrkvsVQM3ypXw-WrFo-sv5f-cu_vV1pmcc-saUHYXPglyPp1F-4Llv05PZj99WY-m7C2N-0bVx-jCFiWiPhausMSm1VHQ_xD
B74nMzV5LWg-m0_dAxpcsxsGg_tUaeHCu8VpDLxp_vfnNsuRX4pZoO4_6dQXRxJFbxNrcg_r612zcy-wddW07pytyEpYD_3TV3ZvBJnx-6ZeU_bmwlUsNlFX
mBVuGDtp_qLFSfVyUt7W6tnuZxw5Vx2a9FYEwDlywtZDJuhVWt_qyQ_Z2vhytE83r_bmwdF7ZxDSAFZ2ukCFYFxLyAaCb_daC7mr0AIK0Iw-NXxo2u44AVaG
y_C7uAkV47pW6hyVdzEMXBuRdnErritNUBtqPvk9e-ypf3I2tu-lS-1dy3lmTMyVg2-IdpcAtyQlbNry0MZWSyhbRC2Nz6G7lw-RqxPaZqyfU_gpVE9_3T_F
R-kt98Vg5_YwrmVgFhSAV7dB5tYrFUdjqDtKvRsWRwMSEqj9y1tuNxpPYOxhF0W5O0msS22Pll_J_akhiMP2V6-agh7sMRzO1-kuUJpszCiFuFDx0E9YnC5s
vFlV-7dzEhNliV1xB7BZkCRV4e1IlyIl-7XSMRblgFRZWCPlF72f1scN9bduAAFxpZLyNpy0Zg4tu1f_2mUacHV-H1P-mLzS-te4ubVe7Ij-FLsaDzO4Ztfn
Mftx1NzrxLkSwxT4mHT-nIUiTUZ085rqwyBFgdylGSZ8Yg_y0WmNRX4gp7Bs_GF_3VnS5eS4US8yZg6l_9eRT28LTsQ7b6zli0F_7Vpac_-AUORPv3iAVvqR
RKGT8aqqmHSEplLXUNrDytD5kas-uw8-Cc5Cn0vj8tIWa_sL__xMp-w6vmZWUs0zpl3kSRxr8Iv4JM7CZ51kmbdudZ_8x-5hzOn4XjdaewnPsOvR7w16DE12
f6B64k0BtNhYt-DFyboU1U-dbMtRqaLRCt4C8XeGPj7joC_z51-FTzUYDvpYWJYKueWm4kV0Qt2V1xwUydEnzJVmvn4Q1vAEtleMF0TN94xv5_3lyLLrmLzL
jZtHIQq7MdiDBj6O_3lmaw-lTSBtYQ_ytYnTHciOy4vqdV_uDB_YQtXYA9IwSs0G5VwdyPCVySllUGZzaj_bcNrjLFYVnqz-VcqsyPD_sFh2ZrUr3wT6XVz9
VEL_fHhWar_mo-npRyrfyl57_lRu4F_hAPxyWbzbVv22Azy-kVMrytpjuQgJRsPMyP57lZ3B5WV-22Ev0J_vcG7xCRfnfM_kuSpkbTzxuzKhaW-5P_zVx_xD
N-4FsMVBN_ncOkYaaENMtpAwA_onDBputwCxCgGpwmRM1VwUqItw2to936_iEg3KRy1FlZz7jtIUYb_psRT0Rmsf8inRgSKVv9i1feLVy6k-Pa0R3J58C_0D
MrywJ-LFl9l7cf_pjYlIU2HuNC1_lh95UJrnpe_lssxheHs3niJVm0-SLhOuVb8RbOzdU3gzRhlCI6KM_go-LhQVuK7-nFlKuvIVQ8r879reT7Dk7ZRnz_2_
GjNXap-bFl6EKpuRax516v6WSvEH4tyRVtV0RVBZxFL4vMiuiRLu3Qv1MmzWuc_Yn_vl-_QXepa80m5uMuB7GFp-RtiYjyaisPIh0KlnLlLFaa4set-Qb2CR
Bk89yeVXjVG-dwdUXMFnVNoD6jZzI1Vn15Vr3tbNlAxFL0DkwnkcqzosoA_wve1VNdLGDaLPdgcK-5lvK_nwT5E5FrbNXg_FLEyW_cv-njUZAnN-Y3-Fzk_h
CnMR_cO-qZHLhNuLJ_2PQkdzaKr_ExyStXLFlk1gLI-zNvwfFfJu1dmM-ISR5tk_ZFQOXtlhYuzl9Ll-pz6UesKt_5-99tASH_kXFxx-IZoHuh2kjDeL_poU
O2qh04A7_FDuWgKXTCoNWv6D-ERyEbt1PJp1aj2SprMTVE83SCX726tvrDEFgtY2VTC5NwNoupoUODzqmazJt3JFTJm18HxHcl8_LtNosVH7VEAXqHhpwrLT
BqOsf9mMl13VYg-vIbU0KxnA81_4D-F7pQgE0tnASmuJLZxKh3q_RLxPT1SVSvwNu9KlICPgV7Iv8-8WdiW5lVA5VTEUNw_gM_p2Z-IBMlFYgfvNFFd4R_an
fTRwUbL763TyPhafrtoHs5n-FVFmo9BFcxuZVlZE9rwjveFuJlWn1letyOJPmhV2XwfrKo_BpPEBdpVFgZTR-FFVnBxfYZ_5KG3oYP_zwVFVPDOdFuCt9uu_
HT8b7t7A23owYM6u1tvCPTwi-UQ5pwFhai-ZwvGVUNGzyYNcZ11yyak91BTy5ldccM_ccPyV_X_MmzU7__0V_iD_-8Vbd3_wvfjp_kYRRyxves--EUUFllds
y9jMJ_o7B-QQRuxvOkvg91xci7XgpMSvvriOoNTPenF-3m
}

