sprite $image58 [88x147/16z] {
hDQ7pkiW30NWWhT9tlzrRpCSNL7vN-PeLUjGVR4Hhn-55L_hW-hkqXUtTd4tCtTk2riRkziLDrfMI-Rsn5rXIIkeNxMHOAx3pd4hChSW-6p6GYqchJNchZD1
YNcUhJnkr2gpbSSLVpjRDgN0dCrMdj-iTkEC86Skp5QD6JGd-FtCvR15vdnfwyoeXTQOkLK4ENE-j7LcBC7cDwWDIr9ZrZ7SabIOROp5pNOospRMD-FXS1Vx
KWpGJcFzN_PDYLZ6MDhiOzlL75zWsy9ct_Pzrmvqh8S7yuBM8qOThtLUmknZlw8a76-6ElCRDde1XAuLAJ47GSJSeN4yCgZ0VBL650dV1dmWLvW3DcBz-cx8
K64Es2V6GhS1tyoOC-S4SxIXugMRCF-E869g-1Z0mom9SqemHrbGcIWCdYCIvenWZhL6OafXq1vczf5YvAqH4qOrDI6w3VfrH0EIQCvXispQI05DrPZfV-QE
Gpd52DYybuMGG4nrOcwoEQB6p2K4QQyQ7WPmOZ05y_435B8Rz6dD7Jgf2X5Cp23qnfXMUuRDUutnB6GYO3L326PWYTMMO9vXyrxjBCY7BZ42E_BDtD54-EC6
dGZoNYGX30CWq606svG-LdiYo1tC_v5UPccowo0C5eC0kyx-rtk_ZkEk-8pDxRcUCFcHX6CWVKjDMUE3TnZ0uKU2NbzVABeuc5_ZjzWYZghnKLcX-hIspqRT
uUgtoowfkOLxt6gM8q7TjD6lx_prInaUHPhdckHJpV3aR73mVFTbuVa1ms_UzanGcwF1OKoJPryt0pUE4PxlBS9qZ0PVsYFGBJuTxLRXZmH5bZRgVkvDtPYt
ezs5Snbc3-3hV4UaRmORHcofRLcJTf7Gnjp0-WpqzmUBKQF2tVXHcK65pz7ezzYRZ_5xZX6MxfRN4VIWTZYKFPRQWNa4h-2qSV6kwEW1wj1JQkj3Sa58Slrl
-MB4UdRrE36BHMxCfEL8T_botLT9f08mmSQyFgZFZDoEfdbqvlOQaRmVtUL86gqFqz2uw58zsAXRmswx2U11l37xDL8QPzKWoz6e2tE8BGQg3qUdhxsfiQIM
Ner-9zqW0YL_aff7w3iqnWWtRVIh6RZc9ZoafZuYGpudoVAHZRh6l7LWTaZDveyZsTMgNb-lEwRTYqPlt-sb9Z7jpLjPrfcRk7_U8TM4b4e0yklUZF8E1pC0
pxxITGZmYxNThS71qt--gjDJAC-pWYlNMnpgbwkwKokEixfxypN7j4UWFtQ6gyfnLhJcvk4_zLMyC8UAwVEiJ6duJTHE1f7KMCj3L1-OdMnmYBIVzoPjYArK
MvNNuv0D7nTOvrkXN8y-OXrnmLYFutDsShBykTG0JeL5s6OWkZ1xq1frimndv7ZLIhFDG0G2s60lV-syEn08kHaigL5X0Z2ZeOUu9VRJ9Q8S-ic0555X8tzd
IUHcyCHiMNRJlQKcREpDEPZaSwaX2bYOGowwDsRrYA_NdMCeZkipidXZBaA2AWf0MlaxxxaT3BJqnbo52_EQMx7HhxlzV4qL0AdmK2ZSrbacL7jzlLyhdjVK
5UWihargat8zZh6omU6zDtSCE7HXjlM1qo11-AXNOsvJdmmKEaBNtgnQ8vMuh5tQcPlIVhQRJm4O0Xs92xFb46HwOswwz-QPQWwvZe2Aa40OtBmnjnsJfzIm
6S3dZHaCx_YOzTG1O8A5EML9BOTSH_YShvRVplkJJxynZxY3Cozhfqd75w7dwmeavqwQmNLMP40gEdMXzelTJ22t3kwHIbbhRyxNIFt5RW16BAc19VT8wOty
VRr-b1vlXGBT32HuCmXAQsz-JFZ7A-HnLOyXAscox6QGtjgRg-v7vNc-hkJ2xBbJROJ1XgDJTrKUzf1Q26u6jISv5SnepEtpwy0ijQ_glAKce6cxtmCpGpS3
WrOipE2eVjs5sG54GaXSoGx6Ezd_9uUDMR9yBr3VmNa9Jz6i-uIH0Xk2hJ3iP1T4ibttm7oPRZ5G-9AQAQZMhtjYNWpapO02CBC_jxDo6QJklIanxSBCKT_g
TsC-azqZ5T-ikwrjHx9dsZSu79Y5qDlH2jetz71YrlrQiDvR_9lzdchEMfZ_QzKyL3E6WHZSTNQ6-lwlsqpr7uvyWWZ2ZZ0Vf_CCPzxa9Px077MBTdNw3a_w
csAqQopb4SQyoKiyeGNprz8SIXXzXtUbRJ7QYyhtj-UxA8EvfFSjeE_oLnTpYVIw3uM-FSoOfroEiJvIe2jlbvJOpwJhqgPUzTE1iNmzrpdQB-OaZ3w7-ddv
44qxoy4kLNufZHaAWNwInsWRlc1jKG9ptfUr9IIZZLnjsPYHgIq3inWlM5jQCjemQajYHjkNO7zSotO7nPCh15WFCrAXzJ7Z0Upt3G_PGLyHMb_ieE24S9Vs
Q8EXzIKxw6y-j4QqPnYXDHJpaAkjFm
}

