sprite $image243 [236x172/16z] {
vCyt0G0m402XcUdzkusBjCC1Sm1C0a1dYi0qiaLa2uqjAbb4jj3OGcEBIXQHBJIsqDYYaaLa2uqjAbb4jj3OGcEBIXQHBJIs4DakQin3wtKGXi4cRCZxF--j
kpZaA3U2Vz7lpEugjf2TF4BwPB5v22SkZ_2vIeFSYBaZJgXTNsdSH35zdSMc2RMBIxNon3Nrvl04vlEC-gHrSThaHU3LhczK8z8mlNfbMzYscQKlOElY81tN
jlsmzcs4WthAjkihZK9ZLhDj7YL5RuLWFTlcOUf-8qTdXC4k8pQFKshT7zG42hoaRR5Ip-ajJxsUiktVD_B9VElu0aVQjebG-wjIe-5Ep_RsnggDZ9KcovUX
lPtdh_BdSa1m4_F4chR5yssFfyTXdjyV6z4Y2il0piFBsXOkedmPyBcquDY84tMY3Fk-1m6iD3PU5YZioH2dPz6foOcog6qlWyFjIc1igshpQhRbSyRg_mSL
i-bq1KYof6tnGDWmIPNYYhbygjOlOri-PuBMyxHYvZ-sjKiqCfypJkMLlc81b07RriWaVbRjl55DxfGgoBPTLrWZnYPuMNv_REHp9gekfcAjwP8yKB55rJe1
_FQsTpdWUQ2qDNB4PNWz7T-NfSpQDkGBlZbdieBLEbm6szhwfJRDsDQLV0sbbCoPSu0HtKDR2I6KzjavszgYFKKmPLIKCwC3lbUj3tAZL69iH5UQuej55Rse
PUR6Wucgh7qwtdYTPeHjkIlDgwKA5SliZGURZb-w4MCZJ7IU8Qa5dQkOOEYXnxJufMsxTObEmoh5IOZZBMu3OR4rySIsXnATXrHwbeGEjoy_lJ-KXSfjUpZH
UHYbA0bncll1fNj_KC4GWh3Og3oiL6mf4wTl9Bbt_XIyxV4vmyCgnKbe4yWPUkakzPK-oMsR3M3ROtA6XrJQB0LiwxwuTCTs92Epk0eIVGx-M_0w7epCOO-7
6ZIB9NA6XhvaR1Bo-6xLSoZZ4j6-V5_MIgebad1kwQvxTDQd_P1nl57vFrv9jKGIZhCbl1AeMRY1a3vPLUk3qKQEGi7dJot7tw2Kyl-uQHsthPTl8k1AV6lx
TbfdR6l_LMiVg944CHH07IRNWEz_soLkicWi7ZNYzmqU9Q7GQe1WL-RIFzQ65lQUyAy6mxUs3jQVqpPfOUrg6tjF_5VZuVl72jh6tXF-rK2TAQoclMrAMm_V
sXgGjX2-1zR9jl6oIrfRiMsSJzlrx5dNWcaF0vcbnzRHjBtytvMSBNpxLa_RneAxs463j67Ts3RM2-vo1mtXsxPkd_R-B1xg7JGyQjUwQTgh5zpr3XgaFUks
QQzUSDSxw4P325Pj6_i_KkiTT2DHmOhrf_yZjTv1Dy8NhFkclTEt3TF1RScj9tMhJti_NN2lNgbTJx3kJDjwmNrydh502bPEspfHZ-zr5uIlMBrjFFu_SofY
7UgCMNtQkpn-UXXrAwH5-BBLjOrJs_fUryFNhPws7zV6lIv9tUfjusVZNjV2rwq-xPqQzxeW1IjEUtMFSFk0EeFMVMtZkHZ7YtjThpFrzmLMRXjFtNlTzHJg
bs2zRNplrHcaWjRhJwVEk1IqCktrhqYNIWUqVyPng3D2VMdQhkzfUsuaAag7q_PpTwAorgSzg3CW7KhRZ_rrfe7Tt3RUYYlINTBnj8M64AGZWVooEkDOrmua
wc0W3qldjPoe0TeTYJgVjlFXE_-qNcTYj2oTr4w6xtpQpalddtQfD4NhTIP0ko5ynzCsIUfFEv2eWzg1HnsiFsFI-QVrXZ15wtKcHlj8a7hQ1adzQJrHSxHA
ZTAID0mhqZGjKEEq88tJWZGE2z8uBL3Zj22Dmu8qJWlIE2rGuxGWZSE2D4uBr3WjIEEq88t3WZHE2zGuBKZZj22Dmm8rJGlIE2r8ux0WZTC2DKuBqZWjIEEm
88tJ0ZLE2z8uBKZZi42Dqu8qJZiZ_GK
}

