sprite $image205 [242x176/16z] {
vDQ5aGGm28LXuddSJD9_jUUs3kk4huD_8Z0VWl5k-Z7mRJg1VxprlcjEUjqSSyPU3WxOIJFZ29xBUS49Sp4GMAtNKpD3h3lf_MzCumP3o_u3rlFIQt_Pxb2n
_vnn8QC7xEUOSHMsUZqruvhOM_0x-xrwQ_IsL1UusWofdeWeDeXruxqbqAVS3JSFYDL0FqA1dDq7JF_52ZcBlJtJjcJlENU8bK1xQ9xpi7MX8-qNB4qgg2RI
Vif9nLOc4XsNB4ogmPg9T5B1ipzdoFL8fuK6XIVerVpIYX_xMPePQlbgp_YDUNFHbIG5mV0YYjYNxFk_xIubUp7CcAB_ogbshfupQVE9Fw0m_unwcu5nPqqo
FXet6HWtSmEUIBwLrsrCbO1e333VKsSmjXeIwo9aN__Q9v8133B0FZgl0ZwcCf3nZVOjEeOSDbxI4PisCxJ5BuJwTk3ef7cCmToNb9FLlssvHyVa_5K6dkTs
fP55kqP-P6L8xUPxFBJxB0vngWI_nWCQNy7RkKm-rZsnrcbYAOYSxwyJrkc6rGKSYDVDQTEXimBH-MO1gpbb-lN5WeX770r8mT1x97wWFV9GJyPiqZ4KOBuh
0hEPIalcgTBbR38WAF74dztpexcjkgItghhCwmqrM619YS4cwdYVWfU1Z9yzqEPvojvATOiaD5CMbHzaLYIbx6OcLsAQs3-4Zsr3vAo0XyuCFv3kRHF4qTCB
Ugkgftc1ZJrv-UiYqazTBnNk8i4zzBxkhtu9XCT_7fi12_nnRPsXzcKsywi6Q2_8-VZ0a7YsAqkmIHEmhWbYFUtFMvEJsEuP5azU-aNCcgxqUnAiCOa6F5Ty
09LGe6H5vUm2pXT6IKPdcgwLzNfYhVEVrjBNYdi38XLOwIVFhrpM5nFxPRFR8cijXmIAL6WDAUUkMYabbpWN-A7xuun3IhwkW0ybl3xt2C3PLfqFctQkBLfH
Qgi_431joeDTRSDLxG__CpFTVTKZ0xxNmRvOfP_CPJEHxNidecBw8p8F8_Dwg3vjFYKYwcDK8ge-NJ-2vaVirqqbPMYhJbIptnF5epFDQEgL1_Mf--hkFi-c
xCc6pjoy-dU3X74v8vqDSSZbn3OxWNmU-Fbyf1f8zwDF6xV_YCkMc4uGZx0i8EN7w_ry9fXvlwwOdlhVG_tF_wRw--cOK_tjj7TtcB2xVZnVxuFu-NZWMgPs
Gt3AQTXu9t72pAC1gG0ofA3TVW_ZTU8KirPaNHzIQsqv6tSXf6NcyJJQXHYIiwNwlA66RXB_-3sjqKCd3dGWpXpjJikwfKwdN1KctZ-UhNlDcZdGWJWlvtLT
sUmvHApTmrPTN6TMm94uB-TrtH9gPF1jqPUXOuTAN_QQMbx0aTYH4tAcjeZRPbH0fntbqzRgXDPaHDeGf-MieKRMyZMo_9krfWGSYH7c-F1uwddFiwhzwDNh
4i530Ro166KMTwhQKS-bTHwM4ZnK9gLC40SvdnUtaR0P1Y7sbYYWMy1u4yI8cTLlFG8GO-rEVg0JnB2SYnleCs9bdaPcv41dY77c6bwm4vwhaUTNWl2cY74v
Xof5zfssw80ET8eOD_DIYIgvdV834YMHIR40Oe1vNsqKPgw_YaZjs2We8W74UAGA5UMjvnAQgRa84f4GOjpClOIkWHsndmbCm3XnPCOxGo9n5mzgZ0aO9yQP
DNJ_n0k7rj0I1Hnec1YNi-EmBa-Y96j0igzZ1nedZinW5rzRtybA3mSVvCM98pFUgTcMDrzbVzLX1GMC4-FCiHitrYUzoODG0UF4E7AKSnkz0Eq5m846Y24v
zmhyLslWG0F467EZHEa8J2bnOfnP2b0U10uqG0mXAmCbO80N8CQOeu3ZO0KED4XyFJEV82wQYaWt42EbTgGkQWSQ6Ny-GUPBMgEeQkP08yCQkb1clFtjh-Bk
C1k280Y2C02zOUv_Mm3w7vGNqJVuNbPEzS3kvQtbvVrJyINpxUNqCJtqFcpV123L-UPYieeNS-_SFFtB6RF0-r7hl0-qMU3zo7M-q3VI7l1-v4rrDNX76dlz
El_cKlal1UxDra3pWtzB5JQLxSrZpWjiRwfXWUS1svlAtqZEQA_Q-_jpb36lamRU3vdPy_frxWUwh_CweNhzJUKNs1zjVw3zqTQzlTalS6_k2-nlP_yTgQ-p
_exKc_q2zsP_eFljh6-aFcQ_mBtP_o57Vzds1xglyzXx30M-MGwu7sraRnypihSt8p-WUpCokAypya3tCIDxUpEZWUxF8OXRuJncT6_zOo7aAsMVCtB0lHdv
WTMRaRtzZGHvdlkOaRsz6HdScv6zFHdvYTLVF943xcD6lcBrPkI1xit80ztN6TdRnupixSt81UxDo07tPcHl_qw5xErZHWRtPcHllvsHlVrFF96z_MWZWtip
yesZDrFb-mG
}

