sprite $image76 [223x162/16z] {
tDA54OG000F1zuTW_LUBIqPnk-qWSyaE58IL32fiPKGAUoAcSoAESoB-qY7BEU8w9-0u9p760H-gS1fYEYTYEaSivuHSvuY_T0AMSqAMSyXqxcRfWY2SHT6T
odqVZwzj_JLk5x1WrapNt0PXACgE973V_t7Rb4QVerWPtrbIdr_TEsVWSeNZ8Nn0Y-4FiUraRqHWXrvtwNeA_qWTqsEvj9pAA8KSlSiBieUClM1rz6g-z0uL
NszkaeCIkz6xR-3C3XTlEXbpenIKL8mUBNlNJwwtSdO1Pmi6rIkQp2kUeSG6Ht0KgwUjuVifrog3ThH3EHcz5ReTbLteCd9KLiVfJnUrrlYeHoKOwfLgVhmg
kaoywE6OMCCpxJ9-maVqQAFK0qBZQmXw6TbtNCFrGh_26CCUCddVSPsPmYBVAFL6-OAV_DSoaB7D7eEIwQutjeN-lf8fxJD9__ScKJxkk8SvEYnaB3YR8uRc
9X7naxSVAVwOgP3DvgBDRSfq_5pUBMTBV58yqhDba6MRyZUnOKVYZv1VxvDhkJiHD7hDA2VUvf2ruEJukRnhI4chnE-aU2FzmUWzxSi-joNtx9Vv1E-GAsQU
ek1WvUhOfkm3ss4_-UdpiaTJuhwU3TtQbtk_5dOKVkC2TdRefiJFwIMQAgUCHx_ARrj0yJjWFjpOIFLgLseuAWD-Oing_DuYAESlgh7UzNXRF5_Koovqrgz0
VhWWtdHZRfntWc7HPT6TCZXap6ol3pyRmLzWYIlTH7CHjGnE-NN-MK5Mq6T5NLl3AGF7RwJF-SbtoTLOZbPGijMhyMW2UutC1x_O-QS4nVz093Q-emg6rg9V
1g_zeF5wpzU7bAmTzu5UjBecT2x8zS4Yc9o57Ywgh_ISCZZfzxZgZF2rCgYsbz89kSHF-z87l1xXVdJwyv2cUaqKstJn7Zh0hm1-eE277RSVC-_5rhT_Z6f3
v-rB7zkMXJ44t9V-HTKEK5Qk22ndxuMnCGwmTFwp8gltN0RU1EPJda-bmJYud38qWahr9p285frJ2USpShtTw6G7hefEO1PiHCKZoAV8uPZwF87DET3G-T-W
LkyWIIJ0JlM0wpY0TohPuIWoWYC7wldNSJnqgZ67CAvdWLxXA_49PmA3w3ayauaTFGpXqunf6FqRphhY9Vexz6I8V5PFR0TtNAx5u14ReEUsz1Z29v4z_Frb
O4aTrRElBDpq747ihCjVdy12YS5GoEXXSalF4KGw-7lAODHWgQYUxijjfsSYY0w-tp61RNCDV8Qu_vDqTkcsJVNG1Im7Xm0eHuSJcDwvNEZiNBpJmmHx30V4
qW4vzrIoTouB0VjIzJ11QZaS4NCZFi7XGy9XxbmEXCbPlI6dtl4RFSTmHAe4hBvpAWsjL4HFGsVrm0MKCM-5GiKpx4WP78seVWJfTEXK3nTa-TigSsqp98Z5
7r4fxoabmtfYvAmUL1BBK5foWtYk37JJXXCGi2-D7Ywu34TtWf8hlPx08WrXNCyVKXmzU8VYGQJYJ9MO7h0lLGyMn8DOWqCcIC-LW_M623Z0-a6CmQSYUaxe
O3rTG6mDfUU04flHYzN3AGD03n24WgWKIWSHtEkLpM6AjoznFHN43CVDaAjdc7axcYeBxVJoy11tN-9wDeBWKQD1j1FOyLIPWvA0mADw-0BwGMpvU08xlDYX
UbOErxE2O11r-3RFPdMg1FI0q5azN10_Qkn3GXdRR17Hiw53zE08efs_hkFEErk0deOEqyCN4EnylHcGmcDG1FIGVQbwxn2KCPpdOy3guNA_gwzpsm2260Q0
wU7U_hjrwatypPaGrS509BIxy22XFnZXhQKZdWET1yS0U9HGvwsvT9u3dRVcqdcUKEV1CJ2UBt3xVY2NndFWJn9s0evu3jn_Cf3BTPxd0T-lWF3c0Pq1_rz7
EF01C86xdqzppagebsuPhE34NBu9d8oRMC7zU1Vd2HrNkga9zLpcWNdSg0fwBiz5CQ-2ZWi0X-PodGs00uv1h8BvN4wiu6wuE31Vkd12mxdC0uVZl8BPNEQ1
WMFWSm8mciiySD-pkSmdD83pkG7uPkbkC8IEn15QNVv8-0jiA31GEfyTWDbZaA-WugO3APVpWO1hy86k0GYu1Y3W6e05EFb9WAvXWO1h00Ak0GYFb0OVhAu1
2BW687p76tm5gvE_8E0QDWYu1Y3W6doWQwWWu1es2CUW0GYRQqWeF2yR5WYhQm0Mh4u-yx2w1Y3W6X8Ak0OWu1fye6i00gu12BW68E0QVE4p_W4
}

