sprite $image87 [236x164/16z] {
vThRbk8w3mJWzb5oyX_U_sttf72pqiL23bhPxO7KJLynmuSbopZyVqBaJ_v_YKZFPQJ8LQJ8PQZ8PQJ8PQJ8LQZ8PQJ8PQJ8HQI8NeQgoteTwRfUGYfjtNAH
HKKk8aK-Neho9Ql8HpRgiZvO1VdSyaL-ll1ZfGY_y4EaI7km2kMTgVRAocC-HChQHGMXV8AKT-8cp_8fKcXfKTz2AyveKx7pZb9_BYD5BYD5ha95BYD5BYD5
BaD5hY95_a9fSKVCjFbIJlbovs-xHvOfLbnFJP1Ei4wuHnQPO9rpZomlMTVZKRRQzyWYyWlI2TQ7UsH1vahPAcUyf2tkkrM_T8fLbz-_MvKvLkMxLU5Ca_gj
ScXT5tdCBAdVIdiJQyqBnsbKvBHrHPfrYupCaugUQnLja5gP8hMjfUGjfGwjh9L19aYjDrxYrpqXLUCbhfnEzLjBeADlEjEAd2lrM_FNGq8zsIfUwLbMfeP8
M8_Lh_LBwyZAt_8oNlND3IzOwodQyYS-QWwX7B9-zsgbPKx7hFXuaaVBKiGXBH34EhQM_QeYaV03QqOLP0-MgSYBKXGYaeVM-52obHRsYPMsy50yMfOYhr3J
VaCj0-iEHlneMNaieugyMk7RsM6u1djYCQpt4YvKbLl6ri1ZsQTjMii-jJfA-9PKdrZ9nVvgM_aKuc_RrfgGLevbMTV7jy1MBiAyotSFf3Amwh8sEeWSRDl6
rgPIFDgshClZMs1hhtShUM35jnpbdgb7tY1PeQq-xRfguhVWjexkJ5zhMxo4hOYpRV4M299Ei_9_jHIgeZoGFh5wsnPlWTlsD2jNKKjFDdzEenjMiZvlswzN
4yhG2Y2IxrPFOXqz9P1RTbQhRJrlmMFr9J-HygzNoVfOoDNx9dxFolEdFVtrQgCeQy-tSiZgBcH-7iAtSGgWNSWJhDw5rH_IHklTsbYRmbzjBHr5sAPqhkXM
Zf0slbfKChIcsfFSLYGrB21fkNmNw3ayVtfoCHAufjRLlpSLAva_LEqBI6VNnaTCijg5BClw92p9soVjjwvFytXmgho0tSPsiewrkY0KFX0dnHEceJN4da3M
vMaUFjI5f1pkOCfesd8I2QH_qkUV4KjyQDIr7PMoLNa4ZR_jvS1R8gJ_XZNnxaVbQnwBsQhXJv8OXSpQ4fvlYVuQ5iJ-K4EnovVF5MpD0KbwK5kZjINwzwRn
5GnslvVAbwqft1BrMDjc-gH_rfJVMkGXSJXd49upjZK13EouRNMdpJJJ76S9mweQZJbZDAfLmwt9jh973ic2Eo3U4jbQNz-RYdcDLmxE6TjQiQB0bWF7nef_
iGRQ4ibQ75RZ6k-bESFv_quJqQlTZDY53ErIw9C-tufio2o-yaNszn900aiBEofaQjGphRnQZZdJm_TDBGEx_KcjPwZLRS67rkApijPVlZ-jgdt4IgkqEzbj
YmoiQcTiHVnIiageTwno3TjjExQsrKexnzeCALbHltN3LlQD3rBprrMDHcLhtvA0bURNilLuajCwBb-sOalQxSQQGYhgQDi9LXsLBrkbBsYzBN0CMwgZRRtM
wBFQSuQjFGaBYWKEcnZ9pa8EVkjPvMjP5TNR5xY445B6ohgqoMyzIMfQWGnPDc59zsy2Qc25jRzjRRQKhOn5IjxOsWGRbcFQHh_r_4PbAwAnMskvaRScLiVy
ETFgBryRsqf0j0OafX0otRiDvy_fLl-SiRLQKqg2ZKhJpTjF6ALhizg536r_uxaSpqjMZvIr-maaJL3J6nnewGUiCYpa6h-yAIUNxrYBNQdNjDJG0opK8srn
OylfqZ4stTPFystOPabz046TTDIsENYj_lBrQdKJrP9KTBCgrZZ1YepRDYTFgd_E-BNoZK8XznifWVMMOI5NNL-Fdb--nwTjsgon3wGCQxfjMhKDjSrlFLzg
JzkD95XXIDBs5tpwLczDMrVyZUhNYjoBTul4RkshhgDZer_hNrI_zbwyI9yvGFMRZ3gUjXEaRgpU5bRxVEq3Dc61IqXoGY6x3uIdQoju1OFc_kmoeesnINFK
eNNEcVErk2SFwD3G4mDPxODKdLg-TXwno7tc896iTjjEaFgm5RW-Nq54NPFLRji9SyQdrP9IQRkP0pbP7VF7Vy5zlfO3QyTMiZhQTdBvsjhxRoggqQzMsqwO
Crvis5Bkj-U6rMZR2NF6evNKjoM1-MRLb5BrjEtyyhMrDK8RTr_uSlSxsdQwrCPg2JsfMzFBZqIgPyxCqGAth-4GCdQjusrR_OqwfMtrlZT9QTgVQthRrYxV
kTfIj7MhqXTTHEn2hkgOCvEmIBVssxRoOs6J-MrFbjNHg5Eri4f0KiJn0glShrsV5NBTOFFBruvbHVhl42giwScEV8Cvf7ErfJy5gQsc26k4ET-j7FskLaVv
JiPg1g_o8fTdrljOcJrd_9SqkhC26aTML_dErswqgh5R-u_WHbQNTBvMKq2wLS4VMRsDEd-Fsbl17rgz5m_pjLfB1ZFqqrFlLnLzOds3yZMsP5WJ-XL_Kv-s
GbOAITy4Mu9kkdItIa0oMItf-sWLgolTUc_ZHDOtf4BBAS2YNx4RrueBrf4LqdVJ0fXJwDROdtwHzUsazhK5hDYQT5_5ovjAxMcRMhxztVH2rhUYsjEsvirQ
-utZlcENDvNQZxlILhonht8aAqdV6wivuJk0D4KfavMeRw-z_zfF4bjP-lvQB6pIfbgfXadw6Ley38cXDh92-c5OZG59RsVr_zgYVAQLjPfZoEqphS1oFjIA
NCQANCQANCMANCQANCQANCQANCMANCQANCQANCMANCQATEldKn5Oho3jscMAz1y
}

