sprite $image395 [177x123/16z] {
xD05bkim44JHY5LLFVjVxe2jZne8TXnuYPdkwTsb2gdKrh7MMoqfxBPRAXty24jZlzUqIMsi88avahYsESHSQdklbXp3Cjn6ukl8VZroB0tyAxGSwyIToIrU
XPiQ_iSjwfyZYZytDX97n-RjpI1EYTtNMmRtLcQSY9DZzlC646Sek87pMRmiRk1w7d1t0pVYB8Kd-8lguqxOgIhC4GUtywg-45CyL4m_S7cnMQSDWxEPJJxP
WMBhdk2PJ1CEYOxWP6iY_mOS99QikO974jy3I9bCtDjhxk2v_SMKcQpwWsUnYNjnVS7Hx7WofVKsAtvWsRU9_4gxJ7TCE6y4hCKaaXDMWxijy6-JtkEQtXld
_joJDWCUiYdPttc2RT_qtbXFEOAJdQLuKs2PWXiudmViDk72cm9dK3S4Zet4xO139G7QhO0B2DmEE7LYIJS1Zet4US7XhLZpG94bYO5ef9T2wliVTzsGC5jh
HF4b9l2D2uhNBvtgQQZumlKl6lIaZ38QXDJqmkQZKcMg8H7sjl2kXJU_i5Igh01XjzChL5POcDoj3juRIooir9chijB2JbMbZ19uOoBilTTufn4IQQX4s2rf
6k6gh9g8MrWlodaqv7_WnvKuAJr1PTM5lpyoaBibmXiJORy0SO1ofBAeS3x4DvIP06zfOVx2m5Kxf9OKZY4EK7wbieIjMh1qF49TcKDIz4g8ByeZSGRDAWi_
KOvL5eSb40SeHpIyRspkIH27g_L-_mfVoaICyj3NZQtCn4-KsrkZrNzancEmyPeHX_P4E1NY6EKX_24mB1oFbfurNqkQbK4SAwvTbD-sfcL07A2SEdHj0SCl
ziIl5IVKrw7LGFnKN1xAfH37A6_oRU5QYCb0SMzHldMB87RTJ4MPLcbYkc3pEyh1-UFd2jDKpSGxbF56EK2vlZ3ffnjxC_I7t8ANZHyfJDzAO6rWOp8ux4MA
g__JqIUKG6D3msPm1WbG3hIMiL-ZORAZYIy0mWjlqcK5BNlXe9sn6nfDWHxSReQAgzzBaDwWWdRqqp4PmFiUPLhI1oPLrUse0oe0J07XQNYNjeFAp5cOpPRI
JqCtG1GOtd1av5yQAzqo-ZRePmDO3XpjcrpdGKCMofRWO3jjkc88nHeEbTJT2Xu-BXNsjknZesQskm_8PpPYgEf3PSctyxHV4nhz26003nOFIHafJxavM9Xz
mu5KkcqSD08TNJLGMHBATvWvZFtjynh7-HoW7O0D6C4wd8aopSFEzg21tZ3PlqIcCWCQyb7-AcJ_CrHi3tW1wC1q1PGaTLQCr8ITx_YmkPbz_udFdIIml6EP
OAk-K5dYQar-w_YzFHzjZM8JEDwnAK86AYj2-ROcxOOazHdwQLWERElOr03UPCMz3pyJm7O0P-pWI56jk3ZKpyOwgWxWa87AAb6EgweQXGwOZs5ZY6hmd5-c
k3YqymNlLlJFnA4cgYmVPRFHzBFGq0xQm6GYlFaekwgWkU0i304mWmDcfUBYcCjV87X7QtFfobo7yr6cwm14q0bimIB9D1hoKJQRm3Wc60eiT0QxikBC26LV
W73OrnTEE59Ke-mBRG4cQDppPAii7sLV0DenGTCVWZT-dtmMthxNmRxFo5d9Nwql4jenHAY1oieJlqzU9D0bOGQtNd6tS3jaqf6YVhNsYQLCKrazojovyDOh
BbLbzIWdhyFrA3FpI56_MkUgh1vbSYNIK8zogihgCtDLzZi
}

