sprite $image285 [293x237/16z] {
xDc5RG0n50JHSBB_9Bl_QWE2OzYmOLu98-zXBeC-P5mqEis41qqYxu6M7YYoaRIH5n3QbIVGaPGtE4PM9X9jPUZQ2uaiBEqObLxqAIpD4IHo918vQEG84Zc2
H8xkdup8bFHZM9eZiJJ7GuiV-NyUIxEGo15SZ1maih0q2uaSpopDmJ6oj9Y8J8CkKEb5_uQbEO9Zv22H9R4q1uai97BSLFcHdyEaAsGA5MeWaICg-G_2vbI-
894ZM9g39oCBItD4UM_xP0fLwe6bENxmYcmawZlJ-Nm7LIz-xeAJ2hZjb_jzzwszE-5k58c109pCpaoCgYJz_r-xHx-EbiPD6ymn65FlsFkOxqaLQ48CoDrS
vdznTveiHu98yJPUHfFkHC5Yf63g6fT4RrrDI8cTwywRXKZ1LC_5X8XSJDEHxh0kfSeSoSNKAEv8gNGnLOm4b5CpuIaaAOaWryuL6Hg1nA2PBgRII4WI8c_0
9FEG1aO4teDf3f8CZDYhARcO4b8FWKGWzPYkQkeHW910UfUT-_B7wKgZ0WbNWmyVg0aX9T9LJNMZG8h8srTJtuXI8BqPqsrQ8KaDANRk_4nJZ513kggfAmjf
WFIEEoTjemRIEpVuHsdKG7glQhBnGceZHTvivqGAemhIjNEzNoQ89jBxNZL9IXHI0-cDgqbomcW6qjiSeiXtIDIHhftxaXmG8qWNato7Cv3Ux4v568Fq199q
8gSV9W4P9BEHfFlw-he9piq4SW5IT_jA4PoOISWbIBy-FlvAI3SvRJK9kGYf-_pu-FYHbBgJVfqJS2dIlqPvbcx06Pb0Slaa_PVV_ocTyKv5oEL8ykF_KJhV
dOg0Qo3XAo5znhgTP-U2Q3cI_9NtxIR0gPX0Fez4BLlfHvgaxcI7A48kGd9Z0V7py_DBpdNRA-1I92TOIfpiT03aGYIO4QPeXw_B9EHo990mDpJZ_gA7A0Ak
W4GZ4fAoYMIeCRqkqVpYfXgqjNFc_eBL14PMAMv2tJ4UrVh19OxB9EHQI51ZAc-QWqPCZiGtz1nxqzOjRWNT5DD3ob5t3eoiNTnqLx3fueu8ZzhWmiXwnOrK
t8RKtcPi8caF2Q4a1oTQNjmAV1Ttshs95mE7V053m6UGoCd57Rkd68iLatGu9f1F8h6110oBMmtgXiVXuKu7X7mUYOtYLiJmH76hEwSZ7QMQ17mIAIkrEYc6
9ugRvkJhtFO6qG8aaCJe9DMBcwIvJa0w2XF8PKZ0A1BOA-vYzs2kK4v0Ea0r2OkiVGa0u7juGFTUSJFjdav0-jFL9E1sI57Sbeix3qygxiSNJJp8mIN8ZP4I
1mV34yMjPg1n5Ea0J49kZcHE67DnCtPFSt7JG3TEHDf_vuJS6YcAMq4pnF2eCHTt73bDHeBinoJW7aZaNN5JeMwCtOixbmb8--uSo7sGF8Q7W-9c53S9TsiZ
xSyaZEnJt1h57SD3CoO-AW1h8-rVJG96TYtkSlVAujOMqlxL178_942PXoTpbCNDTd5FPDgEQD_YvbrnGnLc5WzvPo1jUwSYvBf8xW-FRmV5ROpYnlpYthwQ
15mVoISKDt9nGpMvvE96N3qrYdlddGEv1PBxxE9c53SqTv8raFPZ4d8Jf9Hl9DIBstl5pRHx-btSSUJ41j9EEoVWca56aawwczowRXmfXYSU66dgf5pS2j08
jmRIJapWsa52wY8Df69uehYBQyX6SS_TkSCGWIGbJTB_2QHA27Nl5JTJSJCNDvykRf6Lc8IhnprJ5KeD943D4SD3e5_SHe0w2ocMx2Ohx9o0Mo2vypk0I7za
KG-BuYPI7vd6GzxxS89HlAQov4u5t2AUmY80cFBWIJ_1NDoCYwQvnHr6wTKmMLPDmctYEVM_9XX934z2YjtZSyMTNftxJ-csfC65MyNxgVmbZ8KiYnjFNt7B
hy_FN_yfnIWzKqq2xe8KGVylZ3HC34yKDy5yqJGJwUFV_FntZBfefVbCu8Rnnp4CefuPj7_Hf8WxbpQI6WT8-QsmBlPjxiu9DurFoHrIBkUxueOIRle0QL3j
yfdU2akjT7lc44N00o2vom0fc6XE6cSKTt8bWSZF_5ROBP3cx9o0MyUdPeZaiNFay45J6ocEnSlNC7__Dqao-qv5oECWkHL8AOn350MZkA5jf3ZPZ7obIKfJ
0SnY4kuHdv4HfFARbQ0JYZjEDdDkV_tuBI9pJmS4F0vIHEf8G5mqJIpkE1RF2Q0vJ838aP0YGwI8ke4wkRZZ8dtk8Ofyxvv0ZjP94Gcb0YdEAwSLTt6oEOSf
Fjm1ij_6-Vm0e0LIxI5l4wboiZaZbEBpL734TOjfejMGp2SyToikqXEIpbYuVeGyBf8RK9y1vPHECfOdcswSSVvzwAzkPP14Ah67I3OeReRh3AFStiT6Seo4
3ukRW-9EMgQpZC2yUpWkKfjfOd4FJpQd6mb9n3N1GP7QJ1EAkt6o-S0eM81WEZQIotoa69v1SJ-uQBhxcjR7asCYHPv0AazNehZJxkd3GH8MI7jKa_jsJEtY
Lc1Gt77Rsrms4e4KJCAZ8aLcJXB7YriLvjeo0Y615E7naLpc5dS-NQcTRARVQHhjZGHVAKyNDvJqVBAP-GncR1ZjZEGhHgOYiLhSH1HtucEzj24x8_cwcOWK
mnFlpyVmiFo6dbffoxv8ldvc5hU2vQjWvRVGk_5ksMHN9DycCWLf-0vlxDxmjbU7HjWLoRUAJK0gXgVOFJSYYjiIKccq8v9l6P4vnQqQnPtujBXeAajxJoJV
Ecsanl2mVrv9OcWqH2AtGl8T8irrqoZkkzrZ-fqexl9kf8B4JP1ydzYZucPHt3eeRYMJe_GBgOf4hexa-sLoSPDqx-qUpU8jriQdyn1zfLSpYhIBMwEuy-ym
5tVYIuviVJeFqLTwFQ987GanF1mEJnHtSimaOLH1mhf8_aTIHnh_uGlQ_qxCvgVp43dh8VcVIXrfv8SlgB5tnHr881f8AIzg50caOVh5RVUx1uRH7aZ-XrD7
Yk4P53UZk0C9coFv0IAePZWySTkRYbk3P6ia-262UYe_VA4exbsGr2C7PQh_y0Kbi1UIHmxCD2nkg2KexB9kVhG8wXaMDwAuDqVooF6Pultvua7JvaX-qA0r
JOpYXc8Eqgc8OfYQhq3FB-up6RM7IQ7VPoQMTcv39FN3HrelhUeJnNscAOeOKjgtlReLai_8WHiSK6xLIVvAQI6fpYlkangrRtlDDofkVxtO-3GvkJwIlsPa
JCdMxoJrbmtg8LP42gApCQsCv96JCQs7v6U8R8la9yc6I7wYR8JavyeMIEgdo-f8Vih8caX-riXwI7xYtDP1yfD7bYFv6sGXahz9bY3vs-Hf97-ho3D8FiY5
57-bHNGX4IajeWifCpMDBgJu7Q_dGefP8YyaoXWI0kb2yWTl1F12IWBjwwGBAGjCGBgG_4Aw3uP8pWjfcFwdytJkRfrSI1Kb9X9saGjf62M9mQVpN4XtIHWa
abBEXLIc_k4y7IwaGOIzP94BwIwinhs5T545IHtfYh40aGb8LsGAqXMPWdG5sDZe7m
}

