sprite $image235 [236x176/16z] {
vCyt0GCn002nsPFveqqJWBJl9mQQQnkVckSrVjPOGc89YISKdX1uGY4AcIYPA9KecIYPAPKfbIYLAPKfbIcLAfKfaIcLAWjDxzIRQPB3A0n6pH90o_slEokk
Ihl8XoMOQUVzxY9-ZOH1o2qxg5zZI-_Kmq4cAwqwM9Ubtt3DXuDAYxRqhQvaD_rULpAgVgkhtPQ-rTKkIz_lIWRJhtSbWwhDDQOXXQnKlwjTrlaGLKS8MMbk
Lxki-nyUQOkhw90yTRNBhWHNbl_AjVZc5Sik9jAB-09POTKhBVXY6CkkBng5xb3gVLTEldpjhBbYOgKPDHn7sleEgcIMtVCoI8qGBHbUlSM_3cDPChc617SG
ytaAzKO0k5snBDbSaxRZ4w7GcFBZwMER1i2O05tdicHsLIssjAqHHC3zH4rKfYlYVbSLz4HN4bYuGG1SQQh5kEt6gdFNAFet5C7RzftNftYiC02k55NiEfSb
k-kvnwb71ska-mjtdctDNl-_Ax5UVney19YiZ0FW953VU6RiYcN9vthQIhenjQmjJ1VkbiFaA2L43bVQuDe36MXqMPvjubFE6OWUkMyPQT6L5bo9vQA1P2KV
BXAVfavNsk9wQcZ6iZq2ADbDGpl3TzcL_AuTHaUIS3cSDgjg-TUKQSMLThdYjCtN22WMqond-6vmfHskPzg-uCJQqpRI6RvhhbtMMJ3uy1TjTWu1-osGg0zp
xHfr5CGuth6fCcq1gDfTkyRKzHoh9MIQFvkAhuHdTyNZCtIzZYQVDewf2lWPl-jUE0zEFEXvMqcNWaSXxGZJyrnntMHU2YQYLahh4mvD_MnMJSE059mNOvYU
2Jvuaj0dM4G727VJd1ez2rpsUqscY5c6dhqIa-bnj7YCYQeq1vJYGlc6yEsgifhwiT9pAF28JGvUe2hvczI82fpAMr8_qmDe2H_7UDE8eJuWKV5nZ3UcFlqk
g3xlKYsWsFZGUItgKgsJQuG7sYPncUAAlp3zBjnh3CFwl7trnPMONvKTtkaKdocLIUeBhSAqndcdSwtFxrDzkKRSxtgzqqdkOEkX0L9_6PPjWKmXB0HRm8N4
7R1k6KLMgma5L_ot84fRuCLoGa0L_qti6uf_15ihESMZ4s9-LK8qjF7Qvogq2pc7AcaqJI5NoyfKGQBwjm9xAGbKydExxIgxDm_R1yp1qiA7vvLfAoXEy2sT
lrCotStN_RjPrLsknV_90mT3drVyIRLi0jZXQkwKn4THRiU0sEu4pqrNT1s2NM7TnDvdp1fX1AoxCdh_OrTxec8DPTXflkwg7LbqBRFmdLSQH1je1rjtPJtX
5TSQWKzAPt1Z3GRzCQcjku8BJ8Dh_gpowhr0eDROtfP90l6EN8qtvUnrVU5kXmwdkOQgIiGBzzYrq1nzn-6AtpC5V6GpV5RMMQUvlmj6z1qnk-AA_pditwXs
3PorFEiq1wwsNWysk-PPfwGmQ5WSFUgiyoaxNVMAqRK4ImCMV-gxpCpNM8CVY7XSHQ-8nJN4cvsIk84hqIMafftciPbTsTYCKTsTagZlyXe0kDEyawskriwJ
kj0fUTN8aokViogvwKDnqI6hhXMOlcj4NFVjLSdgTiMg7QkhlJxVqpQ1000BjzsLzHC2N0qT-GW6lmOwpG4P3sEMhUP6N_j94YpSa6nMnRBLq96_gwA7Fn31
hbWLopOyg-aVueK2D0XWR9ZFVvPtBxgDma0OXHEWO6OixVk_xIvIJZ18Yk1N7U_8HvTUQ5G-F43l5QYVi5RvhuRGSYfT-ABTf52fdNMHter49OjjXQfYeraz
Nyw2M_ETFBBLyiqihDNpxJoc5QgEdOLI2wjbakSu2ta3gsSvjszPzKLn-V547iTgdZ_tvzeWcz9thKXLAuFyfSo5ZCCaM8LfR1xIprIiWZQC52lOk5hp_7jM
SeifXOfLq8QPNgnWBsU1fBgLFDZmGXMiZ7AO9SKADWoN9LMeM8DmWKfMi06uG7KgrW1SeBeLR0klxjIfOFKSRrkdRcs_leQJLEflOrbW-mPJfu9jBKO9iubL
9ziT8yXgLB0ryotRGiyBxe9GfuADaswbBgZK1PLwe58NLEg2IXrGwsa_V-lBsDg0AcAV_7RkLjf_ks6TplzmPjnUuc7y_FUONiVbSQmMLSUoqwdynpw9vsW-
M3acD6bMdQfZZVtTUhARmwDiEbYXqY1PTQgEnLUwMTLn6lcnSQo5Qs3hZsZLfIGESVbiOdJVR2-jp_s_FyniNNa4LQQIFCGiyS1Qlh4JLYRukMq2kyXMdKhY
4AEs4fFziOKL_ChcrsDagoubQOXvPYcM5PljLex4VfirmQfJTIpBoUXYPk5UzFIsEczUzB8-Hp9DMb_xF2104Kl6gtdnR3sqAjJwM4v0rg-15MbjBHVM7qQu
WHLgTIrNc_qyd8zxEtyyNzFyB-dQf4jrBRTGHfXrfl5y7TuwdEoZOjMbEXRSJl12mztsV7zTojcTLAikrRLG9rQIvxaJpMyhfwOLMnFMfbAwCiICC9fnvRVY
k6Izds5bRMJHrzFF0pUHqgKXBYz7PUbWzTFM5MlHgahhQnbXcixKqfhjjFMc5MaZxSHUqtBwWwwbbTc5UjCAj1KtZLkvR1dufoclVietITDZQvWp-cFMM0gt
GGsWr0cKEe5IBr3gnKczE2ceKoygKo-kKkz_Clu5
}

