sprite $image6 [296x262/16z] {
xD2f0O00300nNTNzjmM7ZUExZ91zWZbjO4ccMeAfcYog9PvgoQTQygcQFAgbQoe3DcDQGYsfbbHDgYNKagf9jOHQKYsfcbHBg2LLasf9jOHQKZMfbb1BgYLL
ase9jQHgKYsfbb1BgYRLace9rQHQKYsXbbHDgYNL4gf9jQHQKYsXcbHBgYNL4gf9jQHQGZMfbbHBgYLKasf9jQHgGYsfbbHBgYRKacf9uL9awM37FdGoYM4W
0AStv_sVzzQ4tneHpdkzP3rN0JK-sOFYqMzZKltAO2dBZTAzb4cH-6XG1aKqnlr8cHHT6ThocPGutKkP5AqeDMLGuhIFb6Lp-XrI9cLGUqrPDgVxaJ8f8aNA
yi5fTdtv3EeocjSVbmP8RIDbKdtC2sewvxAoV2RLIfrNt1NVlYfbK2sLiPok1AMcpAc9atDvs4Xz34tkfreRzvEaa4bXUDlUJtM4JYuqaqAbvSHAwEIlFz5g
IbRkBViy-HAifd2On8cXO9vANbxrwSidIkB4KZ9FsLjDSGRDtObcZg-zIr9JgJ_tAODAwEJ2AYON6MnzzDYdZApSxiH2nJj9IS-jAL7QdLO_fOGr5VCpdp8q
jyXTfRzuudk9b_ZsX_EiYmigeTFR5vOJ59DBSVteYuzwoiZAxKwjyZEuEqdARYKoMKaFkhWCcfz7xYhYX3N5UvVASoukhAGvDNR2U1PQAK6zk9o_Sj9FfJJe
9zavByyOIJro-KH9TwBH1udJjdm-FkBYGlFMYIDEc9pW0-PIBYudAydz2PsynveAq5Y7rXIkdBvtG_PEYcd_A6SXKshgH2MyFy4ybGnIy9GviwRqbTllJqqc
A0TPCTauZFAKEM-OzdVmIoEMc3t_MoC-PROe5vVJbD2fYqPA5rdgD7eDdvNMCJKrQFw84w_SqiZHzSwVwujdhwaJdZAAakw46Y6KzTqdjQRo42YegRDMJfoc
t5LG8xxFIOEQsfPFkRYSeYHEhR5KHmqK6BrwlBXWb8lBCIk7zmBQxazOrBrdzzqrTPJI5sREH5cHN0UYvTsIC-Bz_zU-cS4KBXA4cOMmrLiilT0dfBpMCTJ9
IG3XnMuiStPC_TQuh1yvsp_nOXVR6LF66U5dncNzMO1pNAgq3_xf7Bxi5gmooqVEzYfCmrKUlZwON77xc5BW1vmEzuWfVND6y0jYQXKbzazSFda-8uoOIWjM
cGKZP_gdz3QcoYEc5fmHrb6o_LF88RoBgK0njS2uB1Wvsp-v5CW_fS1d11hC7nYNrMS1spyzQEGJZ1bJxUYr8AOMZ9pXdpnvtmulkN56G2tbE1R4r9AHOqvz
iRDZPvmHK4KwjWN6PG4bqp-vGS6_XdOy3fgrdnYNzICtzq-3ZOe4Ox4BuTe--NV6PJqbzazCG-LojcJ_5FE5L6X2CMLU7cy_SdF_nC6Siz8AdE9rhSb-S6gj
-YT4ORxAx4zfxfzwrTUpfN-CMX_IOOcrkC49gBPnsNtavlvfhBcy0lDWXjn3QN1gq7JX1FY9STc_cUR-APcQVBpZ9mVYr9h42wSmCIuBAFtGFuqLc5UPu5uu
DRt7b0nEHamjM59-uvzoC3Jv64pcTAlYxg32P9LP44o_yK-lcfoCo-04d9mGUYkM-rg8PAuoku-SxPzcCMKiTba1F3ZrmJmBQC4qBfjJiltJ4OEjoQ7bxMBd
Qn809wTdum80oJOk6u-SxP-wM35YIXjKF0zcv-Hh6vnEnp0uvSagipSbVlyJYrzUSwCl9oPQPOgl0hGRAuJdLio3an5JMuwSxPyShxHCWslGyBaAMbyL4QWL
q-1adH5sEmlC_HDh0UF6ZWOpg6ZJlYeYS2l66AUNnxkE77-kR4x37rQ5t1DwF8B4RaLxbTbjv7Y_q-6VJ1f6ez4mISo2XaahEikuR4Q9EUN2_icE8alDXVuG
1AdQY1F3pq0oOsh3aUFFbTaN0raINQMVmvQkUukgtiy5TYjsJYtOgyn-b6olGXTJ8YBXzSOk9FO5gi-S0hNYoGcOnzJwaMDEMaf5C_pJoKcgvrKcvf3O5wXU
EBaS2JvnCXwGi1SbUhwAs9EIv5QPUiEbc9dJyoD8KcBu9wZ9vV5M8pVtJoEWRbLvbUc_i7zIfVXc-AxYNruUAx059uufN-MlYdILRdYLDZuAQi1_U2s9rYgp
5IMR4yTK5159V9K-AkBYLSvMzDw0Fnnwwt_wxrmUDopX929Ad9Z6ENpHF4svMjhmAcCYBVXyr_3zvN73adfiaeEJDsWuPubXzYfZiRFWqrt3ryP5iQXKX4Cw
POi6rw3XggyAeAVKTuw1xnhcCQLOLkCrrM0kBc7U6p5MGHEviVhICVJu3ryRbuPrTNrDnLd_kp5ybd49SlCggG30XrPqZk0d_wLnKQoivzUK34ytDovzRnbU
nMh5WFoFFdciM5lyck9nkFWF_5Di3wy2cAtOeplQy2tZqh2u_iUlgVuR_zHg6Vw970D_YRFVhjyOL5CivyIWHBxoJro--wTssOFfy4wSQAicJbTI3TY1qnjI
YUYKC3qZUCi_COquE5dmsrC1Ut1wIuhzK_KyASo9_9FTYeKvTVZCINVZr8j15VPFsNsCAV_MFpcYOPph2NxtCw8RSleOKvcdCKQ34_cdd8oOiWQpSrG0WzHM
d3x7LBdt6FK6SsB_TAHWRDLK98PB0T1EK83gBfoO5AyoKTW_SKnvzazCqsv5Xfzp5A2ravJeFlqqZQdqnZ_n-H7idrBwettxMevT1S8eNChGpVk_xWaESlXh
l2HpGZEmx_RjLngiNhHKWwVgTL_JfnTW2_MxUtnCdNdsTAhhJrnSqfu2lXUGrAapBpVw4pU6nrErv_o9AQIJIl4ee_q9ZYAQgiqzeXD3vGF_JDtlJu_ntTfm
ub56nznP-jFljphSpQ8wiTJwuyN0VBK_sOBl23As50_df59svPZQRlIdDCaTbJgvE8LXuaUA-zDnzYVvgoXNKT2Vn2ce4XzJt9zKG_kJu8TpKXUMIlVwasea
w4_W54Y9HfdA_fI_EUanvLx4ARGI7rFQdsHFJB_3tcReJwKKSGhFnCUKzgTJXWSxBIxRaKueSOgdnCSKzwVrvhh-sLN4AOPI_J6rbi_zIRhldVwqxMiIf-1A
N5pEwlAvFsthkP-9_KdNxOujEJZ5PE9HPavB-jgVPjaJkxpLuIcxYrDm9IuksbL00ueBl3z5LkBYihzyL_Qo1_0lz2TlH8dV4RQKibjwoGL55mlWnexwapV6
zFZoU7Vpyxko7sxi9bdNlzAVl14bBYxx-tTbcVQVKjZ-n4hrxmZ7w_-tFHUd_QSDtX7W78_Cn5BsEjzbS-vFIqr_Yg_4KiMzQl-9dU8hyIXZwgHZxbhVd-8h
yIF5_Md7_QT2NIK-4qizSBfnbRvaWwuINucbxC6UsFMhz7tVZ9tYA_4ZTJf1Vv9H1hfAcqoSEpNmNhbAd_TLkagZIbnSv4IwSPMUZ-GkJcqgSN5vzF1mSN4p
SMfHgMB7XUClzAUscEftN7vwHp1rQbk9Yqk0_XH2YOkB-Fnc_yaRKwg_F5vAMIlwKxjCB2NxqpPLx3yrgyHIAK1_YgN4byUJdquooe3JKp7nvR5LzAVdKU9Z
QZaIz2VOwsbTYOyf6EoWFmLG2ZJAS7zgducbgljJ-qhrw_hGdvvDYOjBVNzgducXSaL_2g0KfBZi2xm_FPCIIztiJnqeqIYZ_yp4gGScFgQuF_MWnCSKzwSU
b7YKuJcu1oO-fjYf1oKkBkpKXn8VK_HTMNzAFCfCLgIhzCV4nMK_ZczExlqfyOzFlojpxq-9Yyig_SczFoM-F9xJdjp5gJCc7cKMpoPEtIdnCRMukpXrfyIZ
33XrmiIZJ0AdRfHuOrYSG6b8YPCezIrbuZIOz9XIfw6aZnGudKf3Ifo0QKYfaoeDgDC9b8RKYv0vAGsfKYoR3oOgBfPVj51fl2DOAOvAG-fl8qUb8LLUd0O7
I5tyoGseQqn3AeRIdm
}

