sprite $image355 [170x264/16z] {
xTYBZXit38NXtciTKjRxlsqhO02d-sVfMTd3SW6TDlV4-q4wv1WUsL7xDwDYw9nHSUUzFLB-G1zHOITIribOsOAMFzOMfVR5bnoj6w3C7rKFb57TWZ9bpvDH
MITpAtlnJ5qdKnRA_56seKpPysIKUvx5p_NMtXMLlNYcxCKpAkjaRcKldhcNTJ9rdKn2GOjPMqPk2SuY6yjQOeeUAAFluZIlEF6ClFT5fxATaDQy-3vJtTcc
SqtQqWkw9htbEgq_KltY7wbzyMjIItSkIjCBkYXLzWPbYZuwErEre4pHHsTdgcvGfbf1rwH_P6-cC5KBobHwTCOfNz1OUgzpyR5K1JOJKxgWiRI8awcwcPYg
4y-KTrAg0e_ECCKBIgcfuiLJsfgPgPgJqadKfAfIGIazVCgnclVLF6ooQQroyOmPh4KkdjAFLgdAPgBqm3tgMkNYAMK5gZWffRLAGIareQu9csb9ohfMkNXA
MO4gJaffJTXCQr9MG0KE558UA-kQxwGqha3-PgBq4gjvJvAohlaNJ-d2iIOwALstSZCbIscLyfoC9FY2kgPTF3CnMgX0mcQ2TC6QSl6KFhSATSswU4fjeQvf
JhxdNwW02feWNQWh2fecDS4QLa2u-0of-_bZVLZXp93sxYiLCE_vqhvGLpWpfAxMz9MD9SkM7Zc-_EcDPTuzLVhnKdNEgcdCbi9wfgwzfqjPGDIrZ3IqLfMo
hb8rQLJNKjAu0eMaF5PirshIOBiMaJAeW4f9uxhMaiORgvOqjfQIndMjAcLTcmxfXDQGnXkhTvUAIEC7h9jaNaGQRzTcNgcdhAiAlET_5lqedSGoKaPLfOnK
LSgeh9GfBjtIBTtIBTtIBUt_ltHBjtHBjtHBjtHBjtHBjtHBjtHBjtHBjtHBjtHBjtHBjtHBjtHBjzJatqOgy-yXjMdz9j9fzMyYDS5QLMgeQncfctzuzTVh
wk-KSkJjoEjr7UE_0FTbAKV-8NsvhlS1QL-NSkJnQejrzJ4eLMiwBRLGQfBCQ5suU4hDr1giAzB8wWjEIasQLBqkfPKLO8Vef9J7-hfqvca5WlRw-5JgiBuY
3UkAHH4UAAMTrdNfgRewsqidfMwIKDSNfN5T7SiM5__fxFzeVKrAAgsWuq0XnJoX0WlIm2epoHtjXPDIMb61TIcjaWnwEPpFPXzrNP7IIZhNEOp1x4kemB8K
Dj1vfMUaBW1XNPVIgfzRRyzx2Y3gkY1Ti7vbzbdN1UbYNSL3fTG482fmLhfUrzPEI0caTLLwdlvKwluvy3Zi2wImdf8AGBRXaFfhKbfFIm-X0EG9stJQswGy
rgP86W3nKrVJgr96qQ46Z_smhlExV6biPHkElz3VBnMbpsS_hgicyaAfjQPdqX-0mNRrDyy-hrzDjt2Ye68RZjbtkr1wM6CfWSOsk4bNIFK1e_EpBw42cFrh
f3CoIBbImtS0CtP1J-s3r7iy-mJof_BUhv3ghBIVhAjTC_icwQHKL4bimm5zavJMM0fWLDVkiZTAQOsbqKFfqjad0b9OJwxK6VbbKdD88sly3a3MUxwKrgSh
THgpfQG6m8RPJvAkrtKwKwNh7rAeILbIvdRo7K3-x3CwNLUPztnfN85YinzR-I75d7rFbovy1f0_--iLK5EUTDqwyxdKHwPqt9yyO9kEsQTpN2jbFAghFfjz
tCc5qhW2yQUIk9CaAQtnfvAEVviYZTyFEcUVBveaZH-mnzawdB0cI8DZvQUIz_7pA55AAp-LZ5ulLSgZcSI7TCJ9bFBBzOTqFC-bKePID-y-paHPKbgFUjf2
VwwGCX-bNucdIeTJUZu9KduvBD5JKQfqt0_fqejSAcMcTBtgLqeP7ozaMPeVBojbwagPkbAch9IfAsNgIfcoKaRbfV6nTaYhMhiWBMhjOtXDwRX3EWQaHI98
nntI8e6qRkwGrWsaXGDfuK1QE3-N_WC
}

