sprite $image186 [285x183/16z] {
xDX7TiCm38JXZOim88ZxtpQXN2G_YPDUETygw_zX6DlvSwp97JBP1R93QPefryGUPO_IB7a4jcVAb8DruA15CLeKupaijvTDMXIZD9GUcolbcUoje4KnMXG3
BOg15iLeKPJIC50QIeyDepIK_dqpqDamaz8mLV-ZcF_vKv_oM8-sPJtA0-lGjgfzCosAmL__GApZETkFqKFCG8yD0rqDepIK5iNWhvoDyhZzEbeKWz-THdac
-yMKXjAY6FosDCe3wz2sglqfMXIbHJ5AGsbHr4-bKPx9_ho3pePH6affg6_wGAodn_wXhqwZFB1_2_famqnQ5FFvQPJdR8Cuwsm8LALXj2Zch7_V3BGevaDj
bCTXFTfM5ENfYeW2RQiVnrrvI1o7jjMFe-CXSPI7nL4UzEAKQo3eUZPnYhPrqOkZFBDjd8ZmJEMPxLoEPxLvNAepRUDKFzMiEfxc8Ov7kBTbLOy2T-LPnoaH
g8bgvmo7NoZFtARLSI-dSC_hwQZE8RCKcC6zj3_gNClXC-M1pUOyxdK-9NYZF9vBdPQdn3DVmwXvK28pRNKyqHH_W27JU4JaCwpoB6s6pdEPKCxEw-ln7HXj
KREyMkhi0uPBq-AyEiz0ZyrLBg0yryTcYRFD0v9dW4Lju-ZfMT9iusXRNc8RHtcMD3nEO-CzFMrH9Cx8JmyyTkM-2GDjoqlGE0C_FMrHBCwOs-9fccJ-_RRW
hCrJU-UoN3a80z65GG8X_V_lJbqxDvgd9gxEW-eAoonFfKyZkBOhEFpPgj645sJO9mhpgDbOmOLRFRPgDBvcCa3m42PgcHL4gF4OW8PyeZ074WMeXq8sTly3
0Gt85eLiq5qFGNqNYRg_wx49uDcnll6tN2GTbRc0dnxibIYz3QJ6CzNS0JmRrVS2iFmpM-xkHRROPLFNkdk1XrysDHv_he8EispgMayu1PvjPUFLpWPNpuKd
rXW57lf4rTao5IicYaqJrG02TymySqCuBppRenauX9fEuiabBV6Gr3U-wqauXrZYOP8DVfYXownhgcVZwVlpyQX7Z4Eoj_PA52mRuA3mWXCcMUi4YOBn_08d
v2jsFRP1eceyiXAEMgg7jxxhDNx6Ophy2QSTBsRUehxjSsZKjJvb-WMdY_IHU1XaWsTho0L7tBrtIpmCzOtZcHUSY9XDqO4BF-gRdqwZlgDumecbsLjRtjHz
ldeIZcjPwtXzxukchlNf2IVnCCW6h_KrP2MSf4CoVUEx7bqAN8zYzMqRu2YpPV8p7AZMySFphSpy0YINz0dKEl93cstLaqkEGwwyqSqA-2ypnEVCYO9aLi1h
FNS-uy2EcHTmzxsfUX9EpEFebkeXg6zOFGd7cxQk5nwUHE7dgDrFECjTsttr67AUjRzwfWn_m8bO_UWtrMC4igbxQugTSCBxQwqRYsnmFAeddEXZJ4driCW6
doZy0MT6h3VMEfjiQlLCF-64jLGFJQBmmmmxuOJsrdEYe9Y-SVMOjWlES7-UCrjLt_MFybdmf7g6F-14kAHw2APlzCVCMUiFEE7ZEL4iWwPlBlMeFE34b36U
jMuaii7lA4p4JpZXtdAY0EkRgzQdH8JbHF5_sMHziwtsUwsVSCAErkJwcmE98lllqNx1QMvs7MO0Q9Zev0zN7d0YzD240znziwd7skjlvjXc1NoY62SSJpWy
YS9_wwrj9HnWGyoPBTFX2GUG3MUjJx640oUAQbhFtym1QBXhVVu53f5iyFi_ukaRVp8RE3pdLqynVN-h1zZPqEDPXMo-yJXGt_JgSI1Hz7WScBxfi_MrYVe1
}

