sprite $image322 [197x284/16z] {
rDI5ZKD160FXk-3QZ_glDkWmqqhpTJ3wONYD9Nb0wnK3bmxCJY0Fe-W2VGm1JmXM0Zp3Ue0-Xe0dH0z800zZebSOFeOmF24AuQq-HXz3q1C2a00uZQAle8yX
w0a1JuW2RmXwGf0Jwk-KzLFqCKILEV0p6jV8y8yZciQgeFznH6FqJYLYoQkPuDODn31KiqeU6xd_RRiB-COFJRXX_B0MM_CWaLOdLMlC7cIdv19g3QzcPV2l
Xbv25etezeSwoKw99OxZa0rZ54jQ40snX4mZghtGYOPMuhU7QATcUR4e4zUjNc8NQWnxeJeUXbvY5-vKinSQgbkzX5R3Jz50TQkNMBjefxAZU3Jq4jtNBgfR
JmKMZIMME9hLM8ATEYM2rgrh9RgPzUthEzKD02uHkOJP-68qPZ40ZePSmifNek7r_UVkl6xb4cOjKDtU3yF8ImH894A9f9ETuX_gyuyy2wweH2vXPTxMy7BL
gYCJWLawYQJwhRgDHa8SlSVB7mASXIg9f6qu6hnM-vLoGvU8Lk9MtSu2mW3eghh54Y0QS1XUGHWGGtk9O8caihgD3ZxCaCakaQMMUBz45gdL7gp5kB1Smih0
EpN09c7Yd1_Kkae9Uebu0xKAY4eSaX1Ay4jabjCc4ThRKG9POedh8ttmMaqwSJWZbE1r6ot3G1Z00N9ReXg2No8-juqpqJSTivGI_4ZdUC4Ec0-rX9M1ei49
uC1OCWaUZNlbsZwVLNSG3Qs4_U-RI2CEuRtWcjP9u4k4qoyTOhPoVObqjOGLSgIJOge13CXlPrGIINKS3Uw03986ed5JGbktNZvtY57BdGSgLqhWQF1Ygi4C
h7P79ymj2MdTjdS77-2lAst6TeLO0byYk9XA_3RebOu0ivGI-4q4Ntt5qm2FWECw2Lotk9X6BtW4Dv1Ay2TeDmWU0MS99VWbujK0P0GKBY6isr5a8pZpePFW
Jz3HTICuevD8AkufRxeHd55BcEzhyJUHsdqJ4dA9WTz4OfGSWHYnn34ktqI6Rz-3M0BKxNUpr19cRNjUGot1VpkZPuab-2MYPp-q4abxBXhhECGI_0bQho2M
e9U8FWo7LY9E4ez4uu-2L68x1l-7dtYJ7f00_qz4jaaFIA1eQ3T9Bw5xWkOAZqdeev5XU5P2Ueba61wMq4VZPxLseYj5449XkAlt0RJV_sbTIDhrn8c3Xld9
PdQ_JC4zNLGIEX3wdKZX97KXwaaaJr83eh2TqOG6H64x8vkX5r5VXbj4BwBU6kRHZAYFMq7eHUZjp0idII6c_uCe9n7pQ4VKaaWIUX7rnMKI-X6L968HlOZw
TiOy08W_lrXD0WEXaqYU90v29n7p825qQqHW47hSbX2Z0I6JI0LXQolYJY8bX5iyvbx4D8ugOcpknsX5J7iH4LzFfViss8WybM4B6f6rMfmp6v43stqVho7M
Dq5aFWxRw8XiZSU2HcHj5iTCH-JVdNsW4NThh6I46BT8HDRkSGmw8bjZWoB4k6KXT6jm4IA9O14vRltf_z3U3Q5R0ut8sdBSeX4vRiDt7a8c4JGYQyax4Hf2
jmOTaQsneH5PSzw9a15PgySvqn4PqlT1HsGIsUY87BUsq14vRiz1HqnZ3z__8Q9yjJ-zL9b4q8YiDPC83Q6J20sXamWTaJl3q-c8NAV7HaTCmyBt0KTCvXQs
uH5htecm4R7cmxvZPYF4TeQ8k9C86t5VGIzqH5v17mEEo7SYjZ4HuWgQXn3R6HnYaTiP66BM7tvCX6WD84Ay4q4ZH19X87Hh415Yt68H8ebm4Pb4VCCXzBZ5
8NHhy10oYT0GUjo-As8aeh0C1o3aCXo6qCjm5a8lmrSSGczdS0ZzOfMEc4Okmsa8_Kw4Xj3lH0OQaRL7x7X4jiQAG-WaWaFe9F8LuHN4t8h8969MH8JlhOWC
wLv4k8UjZOYiHndXaStLYJWB28-RuSV08Zo-CpOc8kixnnOUulBV6EUCGrp9-FbCxGE7kEmtXcqun2NEr6DX8JJ3Znc7k3wgra0XiduPjvb4S8XBZbiOuXvK
8ec04BerR6CXiaoCMnn2jmOEePF8KyHuAuHE8kipnFHk29r4O0ZDE6OSGhS63d6vI28uX1wtD8GEwGE6q25zmo7qkCKXT6lW47hS4X2QeSVjx0I43kap3Q6J
o60XiaoCMn92jqQ4hJp45MBSiX1wtCQ-e12QuOP1w41r_sk18VHVZNFG4BerO0ZDy1M6o199X8UuGYGH64AVgOs7q27zXNgq8b9HRmthHUYGJaFere0Xz8zX
2mwXxqHW2FtXjmyQGczdS0XzNOX3w2je6aA_4s4Xiama4Hf2V_ZDE8Hk3HpYEiKx4Hn2ZriSGhS63g6tCpI4JY9F4Fs4bvzGQKG_uScBLOreDDH3kaRq4vwy
MDM84g5Zt2h4sn6UlrXz3V6XpQ3VYRo2k7ehnBWLY0P2-Kv486g4jYHo8n06_U4d40L2svcw4Go2_ZNCRmJ3e5lZHW08cY4G089eZHl18UWpbGXf034I0IFe
3kSGT6iaGX1GZ4Gm3LdcT_48UjuA0kp740RUZo48FCPV4pu3
}

