sprite $image373 [413x354/16z] {
xDX7gWH130JHTIiB-lwd_TwRQiU868XSQ_TaGElzP7dAQgWqM1vjk3pIK7cauUf8W-NHXiiZ3PL76gwED5WURR0yqd1rfC7oQCFbaORA8mrNHneiZpPS7cce
FD9mTRJXyaY3vP66oYCDLqSRBeyqL1vfk3hQS7camV98G-MHHXrjJl188uyqPtYaKKUR_Joc5YoFIS0yuYI5rH67EppY7EH9DVE8ivydIRNgYBEV9qdly8Yp
NoVfun7dA4zryPWg3izF7N6MdpgxU3g6nwHgAUPkCqbgeVA8Sv6dwgOwuYIdJayrd1vngBjD72hFQhvZr1cUfk7nGz0zFBMJHvp-tPRXz4po0wELfyQOuQZp
9qQbuVHKnXn7dgH-OhHyT5vfHYObyYH9zU-sLvenBPLdWd6xZqwDFMEZpWJZyaTdlj4sjUN95vr7TiuhtN4O3A7FblU_tkb5jmNxA6WAtFUfvmiGVfizrlCI
JV5eEDkiPrmtc-AHCCQYzV2CLZgdXY7e2ElXPbCyGidMjOt7v-8PXniFDflIaJ3MhKSeMl68Xa24wELZ0a9JF1CCcxP1iocT6p0u7X2VvU-QtH0yyPW054ts
fb5mjFNmHWUW4Rrf51olzJmRJGeS0CEBHsja3fmXlj6i7nEURJP1S4IP1eu9NaMBWYDW06rpAbeQ70vZG3mSJHeSOIlWcE1Mj1yNeU1NGAZQRK8pZgI6m60z
FaKRNs45mVcRhUSjcZEn8H3M0uu95aMB2GGIXb_RjABDQ4POMkCmE1vkDa5m10n3euFDvdm1A_GL47-Zmyqc2mw6mRMDAreQ70Y3u-7nEHCE_qOpFDOpFZ2R
6LOA70t3t-XeivbX7MTIbDvbFTniPbWZHDOm3DxeyFWysqzV0J4T4xYYZL_uEX9XE2Q0hcOscv6KrYGCVwEZu_CCAmaEWE5vF7HSCfiiE1W6VpoKn-VvfoCH
1hN3yJcu8HZxh8V7vnbM0XmLmVp711sVt_razHKG_p51n-SFia978coD3Z6R-PEL0SS4GrC6PZFXIuB3OV1Z0eZFCwoEH3ZLZYfQ41pSTQwhdGZB8YiamBcM
VYtM0ymc30w6iVvuwAFuhBD2HoAiZGumcmbMHoAiQdT3qVeAo1gC-vJ5gLFSTJeIOJqc24NxC2jq9486hdMc8YmBM4bmzjThq6mw4Z7z-8u9CZxt5H0AOvsf
q2znr-b8X5NjRYhQSNGaOb-zTZy-fy5nvW3nUAWuTOfaq9681HZwjxbiDdq5XCBWJ8NPY6JGaGXheoFYiu3LaGXdepE4eebaq948wp7X62SgrZeIuLSxO3OJ
h0WuDXWwdKEpwKZ4EWpzszoFpns9s5QltOxF7OdOLwzzdCXaiTQH2FSnuUF7ElN9hICHPhKJyLc8NX0SNiLmfi9i1AoEH5ZhjHlnkICHcoyxGoGo0Ii8plvw
xHoqMEj8XB_HuSLQHoByZGukrZeIuLSxMgnr96BurGuKQm1EHo8GKroiTIJ2t-XSBjOw4h6_NhjiDXs9s5-luMAj8n5-jUF5MXgS_TQ3YxNjS3eISHDMHoAy
p-hYOgqZ4Vv61nTh7OdmNtPmiUQ7qv48NAnr9CAlThXOwqY4tteMYhNFxDn9SYiX40RXTIBV_xnlysOyq1HkAflwZ-0lB0Yao3CY4GGmegQVtyWg4W7R8X6j
JHms1qKY05PWC6SQU5XxF0u00OoewUJ3sgyTG4E6ICJKpU006oeIaPO6XZ7MFwy57jQUYyFV2s14_y6wltj58lXtkoCHRnM9-3Dwd5tFQu67jKT68kWMm8YQ
_lrthqW4zDiNYNYzLIJYSnig4f6MXZcCLf686sZWHWoeICGL6gX8H5uRAXAHbWOg4f6M1X948dxHNC9g1zXGaOYqDF1D3yyLYOZJW2GIqMCzdmOg4f7NXhOh
4j6EZKGml8f49AQfI4HU6xIH21vF0zP8n0juE0sCOv0h4W70esaW-l2yBH9Xqs5YoI8HurXWuc5gsaW4U7YOd3OI0HOUfjUiaGWiEWGMk0zlZKI0WeV8j948
4F0GMm1ZRoI2Va-puQQtplMH2DBh49us4W6vULWmRII2r3micJOIGMOTrYoEqVP48Y0j3wlM_SrsHo96iVXiVXhKaGW-dzn67edWYvbfz948lfoMnX-9O61k
6WXWx8r4C3Ir3JUzTQwFH30s8uq_4i7eV3J-I0JZiz7u8n5ScCp67udWqbGq_aW45-UZ8OQnFX8nZiNbQMpyaGYkJqO3anXiZqGmCmUDFnB1t0GqkaX4QntM
x0GsUI8HZQdViZCz0Oqz4a5W3Xe8OEoDH12QmCOJYUW_z0WkCOq_4a5qUMdyaGZYouhZZqImOW8TPII2GtISaGYA9uZHlZ4ISGvF2s1iYaGSnFEznOxraOYp
TFP48fZzoWtEuf558axZCKKYrY-zZYqIKKTFpaX4yIWY4V7LYyvhQIJYN1r39A9u1968uX548ixY4KGYJjPHHYBYgnUTU2IYU5978eedSoIYT0IHYEBP68de
iUXMdsqBZvukph4e4b5V9WWY4NNqP8b454_gI4Jnf8v4b8uW4b4yYaZ4UXm1Zo0IiO56VVIqlP68E8r4HnY9YDjuU0IHY7qq_YyJfkghlzO4DEQVXmOUrbvi
iB7nx8f426YKHqyy4h61HijpGoJ2H-C_UdY9Fz7yFF58X836oBC-4h6BnizpGoJ2O-C_UZI7pOb7pm7NPszhue3hi_VdeRgt6h_E-aY4aCR_edF0zTdxPKBc
wtDzjkNxH2kUqKY4cCR_egExFf_qefFu-boVROaFc-99V7ske-T7UtPI0p4CHK7m7lw0Gy3hhIrLKoZbVMjczdmEq3WzuKMpRTs_EctRvzY4Vz7fFf-TdlAn
iMtXHSCJfh5juKNpyOHfy8GN3K_u-UpqX1VDnnDUD3neBcAJ3aqvDEdOf4EJ3aqvDEdOf4DJ3aqwDEdOf4DJ3aqwDkdGf4DJ3aqwDkdAD4hJA6sZD8tAD4hJ
A6sZD8tAD4hRA4sZD8tAD4hRA4sZCetID4hRA4sZCetIDahJA4sZCetIDahJA4sZietID4hJg4oZj8tID4hJg6oZD8tID4hJg6oZD8tID2hJA6sZLsb-
}

