sprite $image206 [277x178/16z] {
x9W7TYmX30G7926Lm_sFw_1puYSmNZHJ1x1twxtk5dlS2iLmERxXeZPU2Il71owAEk6l04sEuw9O0DvUuHNNSkK6lfS2qUfnNiJXMobtVCRbnBdfIO7GSjRS
zAK0hPulDtqf9qnHqO0_IEcdA7-L_5aAXDKpLCc_ISb-qOd3_qW1roCdwl1VKlA-YpHWG4h2YIu634i1btJjEYu5GjCe6P2IyN8HXxbI8AocKzANGeTCdQi1
0r8oTgu57nYCJv-G11iyMmg4fbCoBWN2IZObur80AmdEajbIm6ew9UDIeDK4IlfIiccf3OQbvD9I6hoh5F2QGCbiAU0rWPAEb0GXAWRJfEJGKYnO86MhSqu3
Paf9e4M2ESG7-bBOvgbOdLdSFpo-SCSyGZQPd3uVd4oL0b6tc9m-zn_eIDdbRD5W2woixDTT25tMhpiHibE_zjcjMfGTiQjCVeKkAvChGyNOcrOsk4osdsTn
Ck3rBN-IlZ9a929qvGpdpr1_XgyC5ICb8HDd-CfGTJ9ZvKPVmxvNXZIMz9t4FeLROr6gTPkZfRHL7yUsALnb0Vhgtgi48U_Rw7P3c-C6q8fyI6lSSk6Mjhxg
Yc7LRhTmDLYAVFYVuOJMnflotDwvOAdAx62qtddLcVzqhyWoNUS7WpHcSIwwHw2xatn5TLpWX54i-pe74HqhTtA1EID1UbyyumpCDCNm3d5Nvq2x0pTKzbkr
m7sqj1GY7ZNGDY23ikU60Dg0Ww0MAn662Q3NKGFR0CoVbNXFEjkPW-EVmC4GbfZpD5kWbjAGNWBD3pC9O1QHtlkV7_gkTAvRMnAzYp0JpMNwFa6g9SHQ5Z_w
Dq2OGIGr89C1YxxZA9UHDgICz4dGPCZgOwIT8C5Ki0sWlAI5UpSKM59iQjG1kqFAGj1g2T5-yERaKJTjMygs0bkAcSw5Q8SKMv2M4FvkuZxYfnLVAJOj0MrB
sKzd-WMOTXoe-Jdo5Dg6vyhVG6vqvKL5_Djupa1dmht_4KEBnRC_Y-fZ-YMrdghapmsvm_H5bSnILCjNoOmep5ybAkMhHPKCKhvQP5QYB2ATFrw9IXdXJrMY
WCW7Q-4L9PrpoBIgXJzCYI8rJ5Gsj7oOaWvHxsODBH-bX5Bu8Q4OMYwkH94I_YRJ1sbPLT9R30igoohy6KemXJKYo3fyMIKAPsCtrD1oOIMzns1G-CfQU5Ao
f0i7azXEqT8cu2Gb8X0sg2o65bSfPoZfSgE43IAnM5hyfVWhKRhSYM4B84kBfvIJb0Y5JIgHeONPJGgoZnAnb4oqi4acjM9eSPRYhwIBaiCc4Sb1opbIMCpE
cU4OjW6YJItkKloLABXdZPQ97RNuIv5kTexImWiaNUe2Ol7HuY-5LObH9ZfIja4YQlMEhSLVYhyI7IdReLmVD7lYUadn7oOAXfV8L0V8lrXmbkAan7R2ERn4
h7z1lbfKYd_dBE4MmskK-XVDxTHYI_5N8fZ2JYSA4953F3j8OIE6br09Bn9BNK0JXtl8Nyg-OLBZ4IUriOCMKuf_vq0CltEYqE6Jlx-KVPsJmr4d5Gmh2Zj8
SSgS4euxqL9no253okanR3kfIAzfEIA5lG-mTWpRJkp-sHlF_bBOOPXOJfH63v3upSMYKlpBX6lOHJQSQ2XZAwM02E_GuYj5kayCJoHLOac1LlEDGjsgblrM
GALuTWwcuvspR1-yqSgafRAOeuL_8GNOjKouX5rKG6ZL11vI4EvQ2iex_nE24tkby1ubBUoZu8HjHJ_v3QZb1Z7Hktf8_ap8FYNY4SDAmpkmKIZuGnkj65eS
fN1tYM45SAPjDyzefShMMOxTfB0unR3Iq2oLd69HAKC7LHJQrE8ZHVgc4gN5S43AcfMIa_uW5KTWIgI-VV9d1odSdM9ufE23_neP92V01zfhBAJm4Isygwow
Mmmhu_TjAqOKM9GAT1f0p_LAXRllC57gV_gdJ4QCWjAg6hvmYJ5MGulp9fznfZzIAYgbfBXHK5fLfFrJuqG2ThN2tIs6bvH1Idugk2r7hKf9SQOu5WjBTnyc
8rMJrgYvl1or3oaOOyev9qyht3skrhPhfQPW41UZLYi59YMpbKOkMbYwHmpRf0fGWarz9WLhpWyhwMayiqkPsCF4dxIGmdIdbVmWnaBqxc9XEH33tkI_fJHY
kd7lufzIYJJnpcBXVk1gpPywIcamtAd0JwaqUgiMbfU7IGwdK66GmZny-QfIYddoPtOg4oxXB59J9pLb-952vI4bqOFZnSBY4CCEP9WdIfgZd5W4CelKGOh2
nwn8V_LCdyAvn0AeyHqhYM104Ln8EQg5nIc6_KaeGYn2S_YebCDMfFl5i3ye4poLoKGbmWPyK0jtpnZs9-8yQLkADn8IGiq5DxJmMye4K_X7YOr5S3xQLYIQ
hxRRQCNGSg1Cg8H_c3Z7yypZYHjeO8yLwU_UMZl_9S7wRCJq6oqi3bThfxzXMozSXh42hPAyP4MwGmoVIMo35AWwLQ2Md0j8tzJ2tU5CVpO9nr9vE06OTpXm
ouhqbpgdnV3_HK4j5MsdOOU3-RaM5gUhjVE9TI7biSDHIk4RJwnmFps6_H-b0LcTw0v7PQRLOc4v_qpl_oWDCDJ9Q6KzdljLOjX-b2QLCbhH9IZRYT_Lsldn
lBQj8BnoykyNYs7xBHRFjnLu8UL2CMo_rn6DRGLUbMB4y3KeXEQs0gkKZJFzfOXjMIeejB3Ihnd3-xSLHYtzsJ1XYE4YsDiAlBp6xPSV9lPYc4fHcAKRP_eh
Kd04caeP45bpKiELi1V3bbBOlgU_VgcqsWmfHWnVEO1QeuMKwyUmlHa63OKsf72BuVh42Ye5sEuUZU7havg63otWgmyJUuS3ojhxk8nXSdboAN7j1NzinF0d
aN5D2gNmsTI552xXmnb7YyRm5nqjh5jhNtHJWJM6l-Yc0YzY-Akb_NF3v7y
}

sprite $image206 [139x89/16z] {
nPhfTl8w34NZGTEHkU__k3Sr_Rm0XugIDEo_dVRIELAPbWCeeZKjdoTLLH4ppXyMoMo0C2jWKZueKiHWPi9iAu1I-bGoWDbGwJAVo2bH5xbNwJPIJg-8cKqg
8wTpAxAbSd9EHG2pRPK1JCevNGrKHcbEw6gWCafJ_qp4XaYWyhSDJcDf0fLxO9J-Q7jZbLc6yoaYG-K4cH5De7A2JA8X4gX4Cdix4ukOgOW5x2zmLLYCNovk
BydKTqMA0cOnMB6NUFFePG7iQ039EzRcQ9bVzhVk4Odx-wkIs5y2BHyhILoP-AITb59yIKvCQNysmBvTEco1OSJxKgf7BJ2dXM1xkWN9czdORocaJ5FFTzOt
CV36lnHONgfm62mwGNtdR4HqvLKj9XMkIN_wDkt85_oFgRvRsTnylwpSQ3rhRbaAyPQCC6_yBW3kSttdlV5BQyqTC5CLuO78qoSOjCfKqkraVAMjN6vfKttJ
_F_6BtTSjNvyg0QWP41fkexjyeosiTVJtg0D7dyJx1dWpIkDvzWZtlnvtt27kyEU0XNR0RnTcg_0zWFi4xbqbKDaTecCLdQ0ZugqotzGzm_AmCTAILggjG_9
395rBfQNByY7ZEDiaGxg-5yeayoP8esN6ugv3t2ko8MMUyZVbX6MTqNwDSdB0-hloWZp6-ixRWcMHnX0BBD_AjxkHk9D9fKAitiNx9rABBBIQ5991XCDP7PE
1KFavixdPKALQgMWCg5AB396qcbOPYfLMj6WCk-gm3T4l5cPJLAbAm-LSHoYiYq2MdumgMoF_OrLtYf9SqbR9ZIe2hFVfCGi24NYR6OJgWopG2PMYREfIsH2
bSm2br0bpeRJfacXUynCQbLioiGgyTwuvcqH9dgSYWhNGYyEHaGH7DUm99siAdI7c7x1XH3lKa-W8SWcNE1EKRbpATMWtovzy0XSS7cYuYqeoJoL5QxV7ddz
ninwXGYu_ixsWmoy-SiZ6INPHFGQKItZsxvTf5vBmAHHIXE-9HAztL2wIhtLBTygn323V6txxrombGreYQYgKkP9hN0lBkLQKWqg4unaNFc0N1-_YxJB2DbA
BMLrOU155xHeWLzdj4KK1WUjBhd4kzI11rV-joJg0R42xgXVOr6O8NH12nRu3J8BfLK98ETISrB08XbuSELtaGskEQTagjq5prtGWfBi99cRbCmcn6O_30OU
BV1-KZMOgIe97cImDPAW9FlVW5THOLjH8ckFCcZ1bJ-EBAQYhBW-WE27mQ05L_vGYgYAzQ242jtM5nwKv71gD-bmOTYGQU6L_vlANA5g68lT7aiIBF1XbUb8
5H-xrAOhVmfrFAx2MEmsNVbpOEtmU0y9ju_o92_dKSS32DWLdwxyMN1t4OPTmRJ0fv5wH693vTIIpDTEoWW8uyf_X9p6kx1sLadYptHWbEIpL0M2AtzcXu_A
vdy
}

