sprite $image13 [236x176/16z] {
vTo9Sfim58LX40BfBZDz_wVjvZEnJItdSg926FxPkf2Clm8ILkJ--Dz9j1_dJUWke3oPM7ftKYVVEPryLt6Yoq3HLQ3eAb1q4IYw2XHTHOek8aKNWQABID55
fEWYKdGHAkeeBPcedamhj_90L6HhjH3rmigNh2hH-loJTf2oBq9STxCYNdeEgxX-5Ijdi_9QEQjL2Ecvh3nMJcUbjLjVnFGwTJl8AWGrQbL_sNvM4akzYDp7
MajzzQU9k5LegYp3PytI9VD_gjomm5Ab39ys5kcGhgk97G89Ago1KfL8HUBLANQ_4bXXhIW7f6aO5cAi8gmIeFBMpnctyvIA15h6WR36i1At9kwsdU_JL8rS
0BmLzR0kthoysemoRhZUSv_7ipVKkDLrQj-seM5cN28NmBfHffWLjQbngwdLiVc2bj1vIgLv0RGgxb4hQbFZLX6rPMYLIcYOoTlccUpUjCQnGbZ_QD_SjdAl
Zl7dhVp9OxVDkrjT_cQIXbPBx0OiiNbchFudbTomHh72MaMjXawjjRLJVIT52wJIi8QnmblVthRZ8zQczhdDfPGy3SsouMtJaLOmSW0h9kD0bUIlL8MqoehA
My48ODKNXbfm-GfjbLvMC4fWdCN0lQdvBkrW5SwwIXkZZpndEcsHOfuHOQseenMCz79OaQSQprllvvbULebKoZCBrbKlhr1NGOs1Ep3FiDOrLaAfhv9NlRf0
gyiwjHoLcgmhULuUCxUebLq9afVLLw_vnR5cS-3gRIYCMQw4bOwtYfhNt8BEUZEel4pjEJt6-k8Q5ZT1QwtBilw2bAjvMyhNaTfUjNPO6rntaULM4NNl3qLX
Ax_ibs5znqKiT7zhOo9HTvNtgThlt7wdAlVc-NjQIse_uWbL6V7cjfUrzvYqBhcx2b6TGekh-vU7DrJxudVCyerQnhThOL__Zejyasfw_yPJEzpwgNpNonTD
nftLgR4cTNHBKpgA_yxw_TjbERPFb_s8UQRL8iTMqhlj4zRnrf_n_OwflQ8_2QGzR_qZhUqrXifUle6LcCErkSEDAeMvzVVFP5gjptSOq8dlk4jgzN6UKI7F
Adthxt_ROds-u-JLzqPLwPGP_xeaxtAZgdJB-8jjt6EUKPD-gOgWikGffJ-4b5AUo_QxjNPVZ56NxfMSNioHqxPTBxN_F6FU6peDpS0DtQxzHrznrrtUjQDn
Zbe5rAvMYn3ISmiZHKliGIAvT4xTdNYeoMqfjyzummRTXVs0ehcxCZzzrUZRiTWQmnH_SvxO3oZwxuon6hDJiiseZPr-0MirtV0prQzRbo2npPZ3EyqJ-I6W
rMCTQItZG9HAQ2qzzxBwtuosOdsUR0fXXxcBLVsM4jR0ZPflZtbbZDssEJ1myrP7HbkNjgFuHpLssvR0mCrQrHqfPotfitqTfYAYPaliSow1dUQarJyooZfz
jbDIG_ikvPxMjyl3l5Nzdcwr-jiT-P16DYpERXhRi9WAR_N7jbfb3EwKVBzXSRBriQhvpMrBMiqViqtMt7uzkNsTgEN01I3s_hRDswtgpsdS6jyfkSvq2Ymd
lV-0267rTOILM9y7O_qZ7sB3Ojngliu8Ax7ifxv4rdtLSY-h-hyfOMNMvrLpu08GazJ7wjx0ijOaaFPxow5UUbZDNqPOkVLvDRVGOJDjRLCHQPqXxP_Pz3Mh
UYkZh7dvqvnNbJvQ6Lahg74ih4Ivq_zK9TCdLYEemFQophRJ_v1Y11NONjR5RMThd8hiEEj2MXagEinQI2j5HNeoAqT5UdghUJWzkTMtPAkjU6dQN3tCghun
vRyS7MKr_fNoLfL0tVz9hSFtODhVgawc-sEPLYULp5JEbFgNiXD9pT_t8t0XdoD8IIioFT7borkHdLmAAgo4zaHIM84ziLRDErgHwKcbeC9wLgrwl1_0njCp
INahihDTlA0oLdVJSvrIM84z5rVDAIgiP-42obc1FGKNK9uAwmcuWF9M7ijxUITFxO55PdgSaxVozVSgd1sedR4umReBawS2UxWOIZ2FiV9atMG4iZELmVBP
dnJTPCWO84z5Vg9uAxe65Ls3YYv1HTUWeWjGUsDLn7oTY7em4Ub3_T_Qch59J_mZmP-bucYUfcdsMthRSt3BydWxTEbDxO-TXe-c3zZg0mquRF9RWctbgqE7
sfNQ7vk6XzBwpo1eM_Fgq7xK_jY2RRPpkh_O3FW4WRQjCmwTHW9BK6ai2C3K0Pfwtr0jVmbZqohtZmvWkpyjtG5x_pYA9xpMyVvfBFocjgmJllp-zGjFZUUy
TOHW-HqWK3b-rx3QxQkHudS4bS3Ie_0i_j62C_buOXlMWYlWySGQ8zr7MmUKYpxe7M7q4VpnOylzxz22tnBKNR2FXh6-i2vDw_fGd6v2kfCM69Jsj8BAHpya
0hkR5TBzjIxpnyF0c_jrMg4o9kVLg4PGzz2g_0u0p8_pyojEuN4OT4AwZpP3yYUxJQNrt_arDQpFCwhXTuHq1-ngci134AxbXzDQ6jQdHoNyXfVoRPbUzUO6
gs3emNNTV1v-VdGsF0yJqhsu2Uzp5WnEOFrfcZ1UITFg6OTE2KCR8TrDgyDJTTlxr_MXcP3kgDLnnLg_0w-TrYKWFLPRSMx6sVvPRngNzdhJ-j3P2EZ-NFdT
gwdNOnaEFLgA_CX-xDvLeEWgK7GPA3gda--SJhwJEldEokGxhvBlEnb_0G
}

