sprite $image213 [312x205/16z] {
xDe5KY1150JHyEsg1VxzJukxT-AGxmWPDJxp6N9gDYaNEXlKN9ijZesKinefPxNTSZfAM3Z7HifPRRUSyh8rWDd0vApsi9oQ7NDE_x9fpOm2MArXt1hbGnNq
tx51LeFgvG2gOuDgDSXgJt5oAn_3iK7BQf3LABD1jHgqh0RvK4KvDignGSkjGMQ3QZNAQb2j1fcDiXfKgq57tkT2Zeso6bIhGMQZh4PP3Qht7f1Zewn6UOX2
_Nb_oJYv09OBOBa6i5m0muMmN4DOhitlSiAUVIoxii9G0BK281Jk_t_kgnQSbw_nYOCkUURfAdeBjlIdtBIEt4VSp6udfp_ZPdNcFkPcTZyu-Nwtcyfzlrl9
VTojOku3RlSzSlgTRbeVwyVSkjnOJh_F3GcQ_WLNSY-wiKzbhPXxjrk4DvQAkVUxHKniesBk_Mu63DphDlSEDvpfDjtRg9XxXzk3xNABCAwOUzsDbQ3hvHR1
sBZaNiutGLXkZGUtONMRUyqjl2DfkeKxtZhcv2lTGY5Zhbr_b5l5tDcDBDsc4dH-GwHMSWUtJYFTmWLWkyskD2lcVkkMS48cQvuw0UdbfX63A-P-xvOqam3t
FOJuqIpTGgbYxWdSaXlCThbnJ8G6ceX8qEhHUf3hQEaMFW17kcN3z3pcwinfRrtUvkc3TIFU_EdrwmjYJf1XkmrwD5-8yaB3L357pTQbP2BWHcpGgc4wnbnp
lzmovcQwQJPCp-KgvhXXtvSIUB1TRjamgLNC_U_lrrlCDKP9jsoOvhwKgCrpp5NCUSvJ5uG_tQJ9OLzOSgIwvgat95rkWv2U3uYIcmoqvka4UZHBj-4sUjtc
diAP32PBDvq4FTrUMq7KdOGatR9XMcuHZNglc3kSEL9PyzJfpQrZnrf1d6AE4DDjpGLDj_2WrpxMQfZI3Qu1qMcl8ApaJWsJBxSn4KQwHG1oUnfp9QUjDqct
y06FxJRwE7Pp5NECUouu8Ulb9X5oZhcAkR_cAJsQfrjCwWUvaZCRREaMLyo1R4GyFxrgG6YwPJVNqurSbFGaLoi8cPTRX6KtjoubvwTNFI2G8DqS6a7tT8k9
xJMvwkOSHWW2KIBYkM4gEUaKVhc5Tq1DDp7hjzvwsPUi80O9h7847soNsqiDKnqvPbnkD0cwxNq4zNwKgvZhVhbbDmUo43kT6wOwSzEyqLyhY4GCFCLSFLgP
QCrJWsoO4b6fMJLC__-J1MUZ4rgwoKGOwHPEPcUvMa6CTDiDqrzkrJ0zbLCX5mFP3PD5MBhLaJl92G7jUPeDKxhTMavz2tn-qygsvgaWz7Ixhvnwn0RueeQf
KJwzU5FTC-RCu-3spePfp3LFbSn-9tUBm_ObRd-qRnzOZiCm341JP4i4vRd_SNSzsAPjVdY5YMNo2Fy92APab_ln6oQEERhD9qUr0pVXVFmDap-1AUNWsoQu
IJLNjku5_uV3QOjDS9D_m_He1RwvJVRaG3N1JQovKdQthKyKLgg9RdfOAul0RGuv5flkfik1Rkvpr1oBJNVJvO2-ksqpr1m6DSrDhpd3fzlMSMuvHaTtqyz-
o36j1wFaP17LtVImMj_TZZO9JX3H2BUnvfXMuScTG4rtqslE_PIRXCKMx3QkEN2Jd6m7Uz_Yt8ut2SvHSw3QWLk07DCAMFstt0dK0jo6RsQQiULWz-VJtbiE
Z6YCs_4cSRgjhItLtrYEQe9RGCtjRjk6PnLgBZwYWbkGdAEj-xChJVXa3TuUkbl09g7RLgkx81SOKS4jLgxqmKsGYuYeu1OiPwNzxjPUNdDKqzZ2vMh1wBRM
bpyvkABMeyH6E2oFDYAzEgpULRKNoGtJjqBO95D5L9Sxo6cW75nLUnivlF2JrSN7zaPmAuHDCcL4TJapz_-kEL0krKQvjf17a9kns7GvSr_iM6xsOjFXc5D5
Rlw8wflaCAoffikzx8Ugb0iejg1pmkboyH6zRitfssCYkTY8fXpcKkCr2GwffZyvV5v0iKqc1rv0iSqbX-ztwOZgS4HxD02f9iZHxRvWlu2_kKmZHxUdrG9W
wcBJvVn8xbwMvwqk0AuSKJsiouhrXbOgW83jCLDOwyqMUou0SE5Yq-NiOLXkTpG0LuweNdErsB9yfLi1f9fKSuzRkLah3PJJYysdeDB3khQR0ORzBbnikXoM
WkztvOZgDRSM0tYUQaBDMQdWzMJJmZgugMefrrDjl8_3i0vkcbe-kQwofHpTrCMMSdHJtrh2qKrdIpcwQMefHpTLBUNefgeb7DrKjfIZcwgMSdHJrLAERgfQ
mj5DPKivkibgAGUwQMefHpVr9_Y40zt4nvPoTDFKyaQtZmJHvBhysFASRh9Q7j1ZrBu
}

