sprite $image220 [277x194/16z] {
xDW54kim38HXMub1jkv_tJAepPQ67cY_8-pu3pZz7QJNd1vG7MDeINUqwZZH9T6rd77J9Psn7E_wQ64vdXQM0-Z2Se0cB0UecULiwSfoWBwm7A09om4gozcQ
mdAUJ3DXEPjDdaPXENOaBCSn0wEmd1DXELTs8opdR1eSPTKIjfnXXaR93VmGHIbd6XpbUjIw12ldzIYvZvkMevJZpSqeHOUZ9KmvdXy5xQfhb7AywKOf0-WI
enmyI-a3Qpb0ENYMELxI4gOSpqq2wHAWdDzr2L3ExseEKCxFjB0SG1UM0tHXEK3DB6TB2yi1-i9oW2Oi1wYPvG0iPyECvO3_QfO3xkjO3hYLOZcENVoVvVJU
MYr7jNNz-Kxtlon7qwCiQwcVnZ53e-JolvIZ2PArwkjZ0aVPCsicQewpl1AMs2MH-x_Tyu1nPEipCtr-RFVKh4sllA5AYaWafl2sSrw2eiAGQO94PHwqulzr
vv3_mVagj6zKc4gEtfrEJ2HhdKieyUsh45SM1cI-y1ybd_-eSea7CZx_wQZyzoUa-Eyw9wCvPdCeTTE9Z6JbWYPVB9IqSClwgdC2d29mgXoySuY8peUK2ujy
wN12nJ8xB02UNfvNkhA0H8MPPmfWX3wHo0QcKh1VmcB1j7RB-hvpLBxy18g2YMLmaJGvixLBwELvPQ0xRo0YJQ1CX94tBXBdX-L7v_NtdLF2WOCKzpSFbPIf
xRuNv1HFG4FX7Z3YJU4TahUlGj9oc22rLCX_yL2rzPXpm6CvRiUbbh7awHVdbO5MhnqmjysqXtbQXnIABSYYUt74qbRSJlgtha9SMSzNByqHxM7EVwn38amv
1HzYJ9bQFJPr1qidL_qEwNTkMTCzrp293dsjBbi71BHF16tTITn39quTj10jxpb7St4WaK-PUiY3bKkZxh3JVAsV6g0hF7eLWZVM77SAapr7-YgMUee9qxRx
otBSZujosAWuw2hFtR9YfeJtrvoudNr26F8j4FeEusMq11SoIHCbZyS3Aqh5ToeoK3_s0WvFJV5cvtZ-M0InLc4MKvt1vQkQN2KgD-kPkcTsUkYMDT6cuc-j
EH2bRZib-sIE_BLJ5OejnuEAUgOE0xb7RbbTeQ-okwdcEEtGneEIzcYX7LqIPnEt7QIXKP1hEb5nNmF99okXLQDRHJgfyGkq-ZrotSz293-iL0SBTECOQNCw
w_nxm39-Dry_HK5KCGLelNFGXBMAPJLCGXyM5Lrmj8L4FhPpNJMPph-a64BCTC32Xtojg20c_bcEba1NMWiJB2DUnHzhZlGb79JQojQSnfELzNz9iIGz7WCY
iluVwEONS0ZJfLQwnCP47-AkLALlJu89Lk4_-5h3HODEH049wV_ll48GOLh6Gk5wM9BWtA6DZ_CQ8PkdaGZXGlaxkKMbL54hWUmVjw8g_uMoXCMUlvY7NsZF
cBZR0qiQ_tvjvUCuHXejAatGCuZg3-zRluQIUWr55ZnqSeuZpP7elkqRUJD3-DIYIq4kXWgsMJsS23b0eMKejKwWh62XO2hCSNV83S3UvclYjeygXyILRNRa
fYVb5AW7A6anKwJEeInuI4yzIjjlBp7fbBXj9Ukn46vBMfnn92vP9Zf26amzTnsi5DQgJwqdAB5uXRA4HVVYHRRlLC0-rF7uZ5Szv_M9prMxGCARg53JzcOv
WA2kbMFI95eECogK1G_LMXHB6R6hKvH0kyDm_xZ46RU5RwyQmf-7ENKCR9lwcbbVE2Oxb7HeGUKa_dzZaNhgK-FOUQnxES6u4KZrMs7Sld1PT6nnrnjcuQxj
ZKKeKbLo6k1H651MF7HHEOAS1eYZweu9WabSyJ2NlJXMGfMNL8yIKxv8P0cBFcdpfox_iotkngAsql6LRwcgMzTBxg_ZBxvRKayICk-LeQLeqHhRbMlTMD6-
X4dwnqcqWQ4BStdYktLYOe4fbBLegQUdm2xhxM1G1ji2veHxOFnqWXpfiSCYbfQ1iXujKHiv2jk_6Xfx14_YzNSyPDSCb4KFsMZ1Nlfxlb8uEE7JD4sIkNnv
08jCJe_SYUKyIWlVAGgTfYXjIH1KjtjejN4nMlUGUiDHbRx8mVRqPSO4XzOyjDguJBJSjMZTe6XtTfslBXOTvbVA0HVgq08IXV9Kj4IAewUlUuu4VzcaxK1K
bTDB7gfdYToFvQFHSkveyxourC7XAnrhMteF7fCvbFix_yZx93l2bKBF8biBf8CH3qOkFuL4eJo6XTpXHbcwiMg02xLZ4hrhsWjl6MzwVHhvK7ck5vAvrijp
njFJkaa3crjwk5DYQ3fBrPdL0rYaBa0HuJKFOPwzbZL-cc-SZazEWqxYoVaAz0WIXVACX-Ji8GVNsbfj3xwTP3d-k0qfDRhoJDTIhyLUv5aiVnyZLMwAr6km
BUs1-faBisVFznyJYJfvUz934MRIINn38XUbdPjgdX6bcv5ihOJ8irZ4bcSh6b0KYQeEA4ApzkPsvm3y44f9TmtcvYT5sEYqV0qbqSt790By60g1eoKiEYoO
tXSJ6vsMrJxcfRbtE-VdK1WWh4TBpGZp-s9tLM8fwgMW4LApvVtEwJARbKiXEE78orZYF5JSHK1a7EyjODNlv6-kETTG2W3shLjvG2c0-P5eyGEABR7a1xBn
FtE5KkLUvyoWZ1V_YbN3sET4BCjO2e9LL8CaHHBr79dQvPvqZeN2iAc8LGOWxEyfwnvAbrJy-OMgnNtDHU5PvwYfPr12Ha0M8mBeMudY8IrTXLnxo15tO-ld
4eqbBlYIS-PGM1WXN9GVtAeWjXgww26TGDcBrYhsxbp2oywnK6HBZTJ-DkgRY82D6tbFIrYkwr2aQfyGLZFCnVnapPa7BOjmybcCja80a06WlS4t3XLKFkP2
l8boz1PRVSuvSoW9WEHISNZ7jtyucAF4l31Ki4BdlSEhogr8dd6EoaH7b26svGUI-2riGogyEbIeUYN_8s7vFEuSbJqGHN8KOMVQk0X0qYjG5g_rQH7BR2Im
qC2kEiSs9Pq5U8GekKVzgSn4aT9MkMSAqqr3XGX_Lv1tdACAVARIb6BpjZqGlMQZT2W4aSM8-QxEVw4CBpb7TTeUntvyqcQJ86UrWxH3WPWCbgMkPHuchpf7
XLbK57rkHkb_aRWY9sJf2mK0wQPeIJ1Jh6yxH-NizX3ILenwGL8H7Q10lkygPEgS-hfpLC7MO6HkPW5mFfoH3IX8KRAFVEDLoEyxnohQ4Oe3S79He_86nOjG
J-MsbdW9orLvph_b71ijjhCFqcWX80lfJ983Rs-rVM1VTf3kzP2NjlBWXE1_YvO-31G0R7lFv1MAo42Kjcb2x7LflMlHrzswvXpvHUVCeuLOMgPq0gMzyuGi
RDrS8W0oK5RBSzGm-KNdgCusK2ZipAIIovYp841KAClbEMuz_GlEMOYM0MKBLPQp0WJgUQnGrgz2FWyuPrsUH5N25me2ntC9PeGY6T50MOgMDvop7YrVA84u
08gz5V6KDYZ9tzBvymlEMOyM3WDAymlWALfwqvKxbApUMy7od7FMTTvw4jwXW3aisRlIeGIbkU2XLvop7YrwTyfjuou48Jjx6r1o3vaNiBpk75NaStm0juqB
v_r4C6l_Awcv9-ivUi53Bpf7XKbKnNKePTolUXQXtItaOQjFhb4BeInWUTKvwz6I1nG426uy8uoogRDA6G4YgVSMFFJMX60zMZAEayACaBQIbEbhC2HEu0d0
DNWByyf_qpdpUINrsNxx2pSeOV-0dYgXTosH07aXMjvppdgqQ3T7aW5eG87lMK40fCugOLn8t9MQyvhSsGm1l2I0RA489-SfvuA0L2Ixo0lHikwSLwE57M0h
omRA484h3f1xbKeBqRBgdBUZnRULeb3iGM87GJoW1x_WeNUTipvKo6tN4oZim7i0pe3a8Iv4ox9pte-M0vGSahbx1k3shXIG5uOAgyvvFreK2jbh80eOE51i
hkF_Q-yyS2K9OIXO9Xlt_Q-xQVYflv4MnQMNTuCfgLuZMzOidSblOywyMWQKucn9p2AvGbwz2jd4d7crj3AWa7l0USyqqENpXsiJS-RLaa0hI5NeTj-R9IWs
J_UXR6IEFw_i2UqW12WcGU-3ET-VURNOPTkOCz-oQhT4QW6Y2Q7ery6SBfqGZQkvVSoPhq8KcXN41A3QKlgDoMLRcJFViZO8KRC9jrtY4fRn-sq_S_ngKG5f
9j26Fnf3xajKtZIntSoPhq9A2Cq4R4JywVuSYrqZjg4vysgnJr0KrbIwtcDRcUDNYm-b0Z50jdKeUvephvRu2OgOPT1rA9kQCw-MzkbxP6P2MeUoipaZaoNo
2qeL-ZAKlSqPSJSzChQ5kWpbsjOSlrhyKvc-16LpS_ng6Ub2D6lTh47k2r3sDsS-LAWGgqYtTciTFuyoPruj6G3frl_cmV8yS_nvPGNWzVSUCkoQve7c-5lM
dY1R14a1CQqspoFDcQz28WX0LuBQB8yqP_vgAT1x6XlvDCFoI7FcrMA1gF451MZZTEYMvvhZl_nx10OKGRkQrMzFboURurTBoqEVOBKBej_NPCysnw-M7b25
E3xKsOCoD-UnrLBg-vsGjsPzgZb-jNZ7Kys7uflpy6hHaCmQLFFrURuw_hpIh4En-hz3kKyE4j8FbE_L8dAWt5OX3JXGxjNIoz47vsMI3nIdMhGTA4wr72Yt
QZbGRYa7Ybij1ugJg0UAMoq7YfDoe3YHvaD9Z9ngkKOimSYfbi54XVUSQZbzSfzN3YWzC78IzGMbSl9rNdbPv4jEf3JXtyXF
}

sprite $image220 [139x97/16z] {
pPZfUY8x34HBaXTjplk_xIpjW2Vff84lVU6UFxD3ZK-rBC3F4MtuNq3TtQtWzLJp3HMy5b6_qWYlWxl_YzMNkrbOURcRHN-ncqNwIzqi8eU_rirAigAyr4ra
Ng9GKtwA6_y-oOmYjgRC4ztiJuNwcZBFTBFlIh6dJ9dgDuZq3tJ-ZzoOFqwZPxevnkfJtHnZvULk5frVxERyob3r7sDX-3dbCJVcNvB-AZTs-erDpU-cobzA
RLrtGV8IXUWPRXXNIEgAu-kQX9ZLizrqBlR51JGoN5iX05JqyuqzprZbJ3Sg-qNEJ7jNyyYtj-6L04Z_86Y6D_VEPxcn-bLQnGLfbc_316io_etIVT7e53UD
0Q3If-N5Iccj5U7tKJI6oKeRSNGnFUvcZV0I8zkdqnj_nFmbRTgnCVh1tQNo4pVhtxVmq4-vjGgpb6xvbYe0UWmzo7AxCgp-BHK0g5U0AgE4ozMcpPzVxNG0
pRSi_P6BYPgMUzsqCKO8WFeM-LRNlgiQVz3DJl5XCqi3oExVPKJTlFDzRegwTn03ebf0vI8rH-OsMZe1CWz4FGXelZYkJ7NxWtiJlR7zYBi0mgYHZK10Y-5b
7gTfRshkCOA0uYb0zQY0tBlBgDla-sjrJYpKaLE9PCPR0y0HCJesQ1R9pL81ij3DJGV8Zsbu9zniyMrk4b0rgw0AKEiCwWoKpX3lk69kxW2f-_n_Re4Ei8Xh
bFWGvhif7qCPHAWnObFISwGIWFwM8ndha7rsrGZGw5ky0sB4Yd8SfXC0_gj4iHsyfsvHtBVt0JVJWdTAk7khjRk_2wgr7GN9p7W_PaGSXh6SSxMg05q0RWpI
3b0bY8S0Z2jKp3t7I7VVNdN-_3ksXouk7x9ZydrbBaPGSmoZhRzZf00e8tF8RXMEo_k47n8vepIVHCJnmPZdS9aZF1H4uBRrLm3kobzUfkRkwsKEiuHVayTT
ORQ65aQ9A01jPsHy--k6cs7-BKtS4sPUnUzAAW3sYAnOq1yElo2xhIeM1vMnIsMuTmOt0agZrG-RB-PTbgNxoKaiRbeoncMaD2nQZeoD7CFuKKkHAyhTOUPT
HzqzLXJOg41HDsi4yh66Z3uI94V40s7UBL4bND5qOOtjPRsYPV83tp-i8CFYPXRxP4dmBpJde6_a2BD_vL6x-qWAOeVviQMXZ0MxUuPTeuQvxXRsMq6c-PYi
pcJbMvQoBq5axcsLegjxnJlKHzpdXe5B5AsMCSaEgtOGPdkmAouqTq6xhbWjZ32fETpkSuCLXO1-5KGD9VoEks3Iec1zRQmks10VOVUwML4Sqg4nSI9m9uiR
OQulKNoasqTtf2FTRWHPRbQKG1srnZiCOK4JFwxCiaHLpSpDhGisMkP3RbQK5CwCyDWew0AsuaTJPbeg7owXjK0zu6RXMrqDfLX3cMzTlA8ecJymPHPi8nvm
iw0MVr524HAvFaNDeDpzvbqmruS5zOVTB7ZsjNlbX9RvL3TJAA7SlJuiDtS5oOOlaVdsJXLpOVM8D2WL4zPqlp5bNF3O0xpSxAbRPOoXL5Xi6p9cQ0vcK_BR
wyEj1zZpochxObyP3xH63NKwqu0mA-ps-j2evO_Sx2jJUoK7T3hBmfKxx9xA_DZDlZAD74tnVWyLgXrMn8x3cCS9RlQLSJG3cdj6P5T5XuZbOPQJt2oepv9G
Wnb8KpNJI4bOlD-mTDEDCkvbLSOLfgXabTp3eqYLYWDBvxdPLyRS4QKqKh88BroDfHoil-UvsLScApDNKkXyiBLmCwu7MKvpiwzCHTsYpEVQMA34uWTXJdAp
hqnwLYZq_L7sGbgv-86bCzqiognCxUXWcISJneKjuY3CUMxsbN7k9CpMjp1TqFBhB1vVkX6SmQoCH-NA3Pkbz3O5xS94nlbkzXTJuTh1FSAwPonM6C_CECdD
SMMwTdX6CA2nPxv_dENck39fswG3LrZioR-47Ravip8U4IX3IduNvS3DsPM95Daqv9TH3joSNvamjEQTwa6K4zqSJvaEY5MHxwFiFexyPvMnQa85sYnZyHGt
-uif6pLqefhfdwECg7W6Qye8EbDhlN5CdkPcNvdMgGP0yDXueflzBbDgeCc_KORYkQprDxcs3r4QditQPGZqsYYhCjvU7sLTJA-FiYhp-YYhCg-FiYhp-YYh
CZFA2C6B4Trsfc64rrCiCYl-7pHd_9pV
}

