sprite $image277 [312x312/16z] {
xC610000080WXFrj5wa20000000000000000001crpoK54U2A1XngdPbvl__zem6KqUhYNrCIOYHShtVoSZcDGIVJkFJ0Uvi1ZTtMWFDdGZFOEPEk0CpTrh3
pPtMS7Fd7E3cpjPmSwSsqDn9dQr1vauc8ghCgBbJ6fN60AUvIl-H8MkdEPf9bN54ZcgEBXI64PqvihNSNf9sJ769BgGAI_CSCBMPWblpc1xIMcwWj0uxeBLK
KMl7zJQzUaJLSJHnNzEhHrJ77E24EcgGDJKzYhMSgJJKsXWxY3KnXQqTCpXlZKqbmfhdrszeOZE5RXv7zaPNcffAk3Kr_TMnLJMBEw8U-zrpO8fQEsnmatjW
C_I8XWV7p9yLMrKujdXl_CtdQCiI7Xi-gPLlVCgAcfc2riA3Oyz7nAPORFeIPjYx07O_26ncAbXiqS7n4lkFJR7OmeFZ0VkDhON7XWV7JzXdRKdY1s5C9j3Q
p0vhAwiFWeVfNwPFVZET6uJDObEXRoR0shxCkJEwMMmgYUwuY-x7c2lt7GqVX36D_izoRAhZcTh7cnVgjcSqKmTtY5rGNcG7Yz0sFQE5UZ8_CezKeTmqobpy
8cmP6oVgI7KfDYcZbq-lF_fwQssofRPCFMKfDgtkDuX_cFF3__KsRKasFAEDUd9RYirbsPapS-RUfKsXsCBt8DN5s0evEdDYogplCKSpUKDjTN14-zWQBL7S
_rM44NFnsf0p6hy7RJ4sb-NUpFsrjRP2FHM8xK9LatUQksYBFgDcMjD_bChguCKZ2iJcpTq7GhSsTwa-LflDQBs9aMTxq93OFAcvWL2vw9lPI5lW6JM79BgG
PNJvg6XidiIFviIP-rHjFZbYbKGT6Okj9xCfRsrk-jR6KTgivpwUPNX4yTWyMG1pSTfos4ERBRAqd-Cz43LZ0Ybg4cHkUsqseeqw6SHM2AS-cZDRpTmbyXXj
Dc1uvb8Tn9Re9PggCwVhFMsjgBRGs0elnrO9fvzM5kUDEJot5BC8Da96iRNbsFh5XGV2dzOxUzHcS6nrEJPhX35-rjeJg8rQW3Q3OykDWTi7I0qm5wTDuc9B
ZPUrCSNGngzGn1nIG5jSR6MKSw4O_43qx4ARmR7bnWCI1P9b7NEWjh3OAW-fYI8fkeAv2TA6ttH7iV5J2Wq87mZUGbj8R2xmpSobPg7cQ5rj3TY3HrgEDSSs
dDOAUuEqXSQslRdoP21uFzgqGh7rY4gbK6h0G0Hf2uzDLFotXK9f5c1kMa-RLc16FMeripAhhlKmz-E1-4AUN86n9UJEvZ4pJir7mIrH95b-Q0xG9he86blx
at_9PbGYxy7ZruDnSnFLdsa3OaC6GQxsLxm7DsL-qHm5QtiU6xP0lJZHM7ED-KLpL0AqWR5XviJzM6C7uXzkpaJ9bPHNmc5A0hJT-_vF-yzCbwS9KqjIZNig
ZZEMsPVpTKfA0VOvDZ_3bkUnZPjjtDlTunXhaUHzROu1jZZ1nl8Bs8ml3GJSw4fML_Ss8Dw23VrdpsR2FBPvis5keLdVF21WeSMPtUhxiHcVLuMvcGB1J3BV
vahRIuvQwtXpcyVc5Vn_HhXQyyv49fdAmRLxVBx5TinjONalDcmsLGyXAX4AX3E9kl0qDlNO8sTnmetUZSthG2_nC3au0uFal5_yonloXtVS8BRwPcp6OmF1
tDtqkcobvQQjBKcPpn_RVXjdt2RTDcus-NxM0dXXMNXbSJF_-O38sDfdtEOEZiRDLfhpr_W_not2YeN3Qo_ylkxmFAJe8BTvR5v1JKI4C75r30vxOOE_NiVM
bhZ-s3mJSJrU5gQnZPjjvSPVVoB0A1rESw4_8LVxVvFr0wSygvbeWjluEsSyxfK1jr7Prd7kcd-mo9jxCzxs1y2OstLis6nP-calRUXFa_F-BaBunukyX_VO
ZibDOyDcszRN83RvHxXYxVMpH9N71gaTDbcXZV9bS3x0JHd-RCtCkjy3jwNfiIebohd8MIQfRgvDPNWYF5CWn4RLUsusZSqh_f-CSFFX8IhqU57-1nzbESea
jPKOoC6rxv2sbZlOU6KxMCCc7bD2ipLkXLX7kzhowBcjMlRG-Uwwdn6srj6wGCcqaUtbE9zw5kXrA96RkrGRdABbqOaQI9R1J29vU2AOHwE-yu_j7uk4NSVc
Xin6TU_VPJeYVlJAZwQi1-IwJB99StoyYveTOoiU-zpYUfKgoS47XT1X-3ot1nrOnZRl8yhXH73h-1rYguVhLlXLR9w9Yf-OhUYCyeORfnTmXmdCLnHxxo9g
PqzVTrC3x-maZhc5NQtIBzkNasGv9Nb1Pk5bURKW7M1xPfAzTn6odS9FVdQ6pQBdXWq7FmS_RpOyJtE4YRjq_ZjU8AH_XLepypR-cMrNZhgT20qRDXpc1fPc
hF61wX7AB6xq0gxeAf19iEm4M_7OSCEZmKw_1H0CX4cb1cZDEcmXJnUcXPXPm0cJNbRTcGYGcr_XLiRDDcyuMZS2-_uMY3NC4JXXWckG8MmQa9j7s8KwvV61
CD_XqY8UJtbkFEjfwhI1enGxmyRMOOE6mzpWG9YNf4JyhxrIQpJs3NIPFxtp4smU8zoyuSVW59jjNhAaHzCYyPG2mmtBpYPfyK3SLaKpBkHMqJfgEgQQQLc8
immi3MJnfT9daNbjiLL4hMbtV5-mM-qg0AkaPgUYMr4NsOgzO7kaNyEc45jJh7B8hO8QZN3PVD0JOY51VqVY1z7BkbL_1nlR5Xi65tOApXWDX0WZukfkQ7T7
gvDnjzjtAh-2BNk73NFRaXitMvE7vUT7PC4AYYXOsTdjcouy4ZMC3Ky43AxiWxCybZuyD7TtVPWReMfUw8T-Y-tGErpb9GwnOMuXL7QuoV26O1uU4GOtARog
AnyMgWnp4ouQFe1D0JO4hXBN7bm6w-YrpDuWW2vlLZdjSUFnf2P4LC81jduY-F-FoQEfq9FSOFfGcpZKHHJCj71wqF9eIaM7vI5CjEEuZ2R2PSDvfYUvarMU
vVMDnOZQLN9DLtgLcQcKl8vpBc9wGRPce-YnuObm7Hm_o_3BR8nkHqC7CflaTNbAwp_wNO1B6IUmweUlIGwmWOc05HjmbCKauzjH9M89qD9INsOhWLSCKakf
ekzNJvkd9i8nEACpvOFC1XQ49Zvmv9Ch5VrL2HzC18GDWzChX-4UofGZOlWoEU-kh4rB_KritKJ0s30t38xbUcQZdbk2QCj_XAq6meOrySqLvk46oxH9K1PE
eh-ZEZWHvi7DdqyMwBUw8Pl_2sm6iLtd5lLq89XU424eik76EYcyahAFO9i7L_i7nUCYjCSll--tFhQL4MppuBAyFXMmS42kvlplQqch3KogfXj90fNy3kMP
YO3trAPo-5hHHEIKNAN7oui_qyAqB9GFrYHvSTpowx5D0opoCuQBSZ0GF5n5rCD7LlTKzf_thaidhqwsyaqkPVi5R33ilXzSsGiU9g9n02uFn37Xr2ovZfgQ
cNCHq_Uhmh3xVd2Y5mye1GMs_apaiSY-IRwAUw5STKu5JOJtWykgCEpYE0O7WPmV1opbRHD10cER1-UAXVt6y44gWL7ne3TXKu3jJd04ZyAN3LhuBw5t359s
C4Wdz7_pu1Bw9VE66pPjdPy8nO7RfXHlTXmFb3BX9idJs2gWTWkuohIaPLbVr9hGDv7TO57XN7ZBhbz0QxiTN5aQ0_uYP-kvjvdY3M4PkI-KoTPc2DlxmSMr
3nwaUk389NszqYtIBcV-5bKRk2yiSzZoH6kR06UNZjYId7_KB-NdVOc8zBSpKf-NCrOJ-55CJeJxmH6EOoi4i25KNXuxzuM9gisrDWc0xHvm2xv2I92i2Zzs
xmlDR3Bi6g1s5pZ-mL5uHVHPeQw7NOnjNZ4yLYMXh5LmhBZmFD3SxVsjxNvmY-8uLc2nBtgWS7SF6sjjDG2sMy4fWGehe9BXpjfauQjiv6GNOBiRd6bUqjcH
JqP99G_xpSEVmYUxazZcmU7fO6PgsxSofSfcGw2HgLpmjoQ4RMiKXDtRmM6LfR-SeIMbXOhQG0pC0r-ljYc035hRZU1SnoJBbeBPtkqCj_l2BXW3Sk5phUt-
9eUp2PqV1wHsNqZ4HMqNrFaN1TRvrdP_hVB0EH0Tt1SUFvpqqHKXUqmSxTu8Bk7nUEbp2H5Uk7WOM17cmkxzJMwvj7lXvriMKOcu7f2hDBJ7tm_EhduN2E7T
gu1NzLQ8sCD1ZP8DOxk_Lc4LolopDmyj4X7dDPfz1jlzjShT6J0kPHdxTaixhT42iDqD3bjEkAMCaQZ2-0sz6lfg8mc0xNPms79cKd8-UIj3vrNg0urKUBwr
tJyUi0elAQNl-q9EJqUoxc6pgkV_ZKBJhUr-os6LjBalrFgtr7INMo7A6WxCDj7QRWHdFtqvaYeU0y9VE1oSwuBMzeTRBXy4NV1DxcmHfYYqaKrWkmTSc0vf
mMy-nlTIuOdMTelyfvPBExiNbhiR60YWjVtfbgEXet0pXHAURMttWnkV3m8MAv3Pm3UcJ62xcPmYLR3gjym6leiRj3Q0xNPmryaHEFxmY4oKBHoO3RMsFumS
gZ3JGcbzEdFuPQxFp6RuM1UtjWzgSxRgDBFHKMQhX5lR7o0_83Sd3_S81sQRQMttAtw7dBlXz45rWjhTycboeq_S2dNI6MptAsR9-SX44PveRHz9pYDSpSCk
cQqumFRnv2n2kqy2GxEH1C3svxOvL7tz9u75mu7PO8r-XEN6JRTMgHzaDgQ9-F7vv09djbKLrEYdaDlo67_jN8bm_F0_YH4cDv-59TEdrIWcDu-kqaIDVXAv
I-Y4GOqsR9z3RjvqXK2D0coVGGwx3fjDFemQJiBOTjXiR03RvoZEqTc5UK05rEZ7aSEsm-6360o4ZoU7VLScpFQfwF2e40Pc0zW-SaPWuzKDirmr0BQFLWpA
jTRoZwg87l7-gnqwA00G100W5a3L_cbLAXm_s2BisSbv1Te6RPcrJ5kcBJlp6hcDliQPr-Xhd5DfdCkV0G0000000000000000000F01
}

