sprite $image402 [215x219/16z] {
xTpfSeEu4mJm_x57r3Csx_-sM-pLHPpGgAUi88h-cWD-cHaYiEobaFPli5mcQ9jSHDLUyhmMYhaUQdxOBsqdlrogLBDV5D5avaFzBaHpkXe0GPgl4UEVNAeH
Wz4oJAdIC4ofqh3fM8nmpQZI1PkJfGis9KiNxFSfMTerfqetujIik1PBkp0bIxkcP6dNn-Gip5YkqC4rMN5kLeDWpUZwu9bqit1Q5i_5OCL9MOs1my8PMNiB
X9YrNDXz1IGcBPTOqNqKodKY567rSftoiVh7hAmcqiEAix2Q3FxJmS995l41fSfS6zLduKTO0UoXul58emj_dXM1xr7vc9NrFGmhwYzMCxhmvra1V8TQMK1h
c94LWTUX-eVLrjYivu-m67mQAgheCbZdUOqHILIWYnKdP0MmHJqs9VHO-3aMWqt_4TNFOax0YYGgsZOOUYi9iVZoM1mgnc2vC8YBgSbAjDV0Pm5BHvxjSyei
eYoNk7MpRokYo6B_MQws4mV5L5bK6Qxg9fGFzTC-IxXybfx-jfiYAmAc2qq41ef1aHNcVA7f62YcoWh0SFdx3P_jMAgi2CFL3WM_l9u84070TscMWg76GkIo
JVOKt6PvC7rAlEzPDa7VRp5PlkiWwZEhzyzJPcaOxzFqPF1Xmkv9Q5YTfM4QitsOe5cwyaNM_iKUw5FnPawgn2z6YQMFuQ0qInUimj8me_y4w-Wn3PO3qwKo
M841h01yb62vBf-bZw8lwZOhC80bO6ge6A4oN9eb0gF_1CiwthEJfOBDf2cKPDakcrKjN3mAB0PZMHgMckK_L4MHfM7QbK0Abbakd-N3a7pstP0cAp2GnK2u
0hpQMwmOpDAks3pxHdWi25UDvQosWTVoBSmp3cKKo_yl7KcMKQu1BC-5rhfPCO2bNJgzB0nb-Qu9M9OhkbWnakMx4Dd7GfqLgBlqRLYv2t_fOw4rcB2sZNws
knBjNzt30jgQzxd09HJQ61QNEYOCnvzjhALQKnukpOh6U32znlWd44UnMVAH6M2MIpy6I3IJfQ-4-emSb-u_gjQyZQLVLAspghlVee-bUmTr5_2w-v9v2qi_
7GEgh8ZNtPVrpOg2XIQ2wiKmygl-gszM5DKIgCnIkSZAQAt8qh3ZZrcgB2I7odLrl3GPOhnuGhKkHBB_N5VFYqBOWV6g_1SBiCk5t5EjCLXk9tBICmBYs9eL
4EMoMGqQzlLI1-hOcYL6s6VfTxS3UqiTMCD5rYuC1PP-TplsbZfrLW2U2qr6BEI_VgE9tOLa2HXABFtkzjmkTUgi5acMs5pgiv3xhC_zny1aDKJMxXSExIaG
B2vrF9O-Ow3J9L7vK2mEbUSIf-mK3FgvZsRjB7KAh0PqwXcDqYoYn46D6tyF1Z5KHraXN0xB7p68eJhCslbTBiiVCOZ-ws85O9LBp_T16C2A2bGFAqAvDAlS
OwB_39Ry5wHP_eZf4DNFYe1sIPOUKNYxBtrM0CBbi90P5emNTPF5zBgQ2hZq5PqeXifW-R13Kv6Yohh_wgm0XAjx_PPk-nBbivZZBgYf8AiRng4oMJvCJCK-
Am3HlcMMXW7T6_4KAm8T_PT0bba1w88f55a2flilmGxeO3cT2DL_P0cOkgXdW6239M6K0G9ra1M0wh-0k3iMB07ZSXj0nrI42CHGlHoXoWgWbPSw6JBiCMRd
wP79yhTjFVfP_FFj3DKsGDCi5wRxZomToFxRHh9quAB8qacDsgRC2i3elnehGnvJidJWeNoMLgLW6J1zKSygIo-a3PReHBtKGLHPUx38Xy4I1LDB7HRHPwdF
L3HO0YQNEYJxBF6PYWPBmlHIXx0YAmAlxL5WwH53xA0ehx488yfYwK3SFso3i5ZYCnKrouBrB7LGPWN0zl1PEWAr3U2o6B0ztiTAUV-m3GoMEEG0LgA9O4fM
GA0UEIKhWDsLy9mijG5pObO4la7DpI9ikxoVdnN0o_t3x2p2s7_JinWGnSIqB0PS2L-4nM-u82iVerXhBifQBiPYBiPYBifQBiPYBiPYBiPYBifQiBBYDAn7
aSNaSxaIY_bvriswMJVhPjsictMpRjRDkbatwsRTh9jrisxMpLekobemXfM3M8pFqkV0BADOp13MWb4iPWHhMOQpbW6iDQDOp13MWeEiJFKhbwDvFskDOX6s
U_5TEl96bZYAVFjX2fJhghEOGwnSllkLIt-6i9QdPEMdiqc1adadYn6ivsT_2fJEnm3M2qnDOagLJevWRM5g8qdoIb780DRspwVsMwIkb0_pMUeeujeTMLCn
pm4imlXjRq_vVekHXp5GVYJhQrZst_7neZuYJy4IAnsEYuBHFYQQzJfWAL2do17Mjh0f-k-SCFb-lcIfpfrT5hzDBE1E3akn5JWdGT4bPmSHaREWUB7NiyC5
t2J1mTc9PRA4CJlJmF9QACvEBZ-UFm
}

