sprite $image372 [413x326/16z] {
x9g7aS0m20JbB43zj_ivcS-Hcv_T5dRCdS3jVx3QCJL5OEbsnTRaWEcmEzQc1MpsI9yRA8ND2PteWVcmXCXiWsct5rcQ3aoqp24GFTJdLzbBeuVwd5297jZj
VRfKz10srRKQvcuVPcy243PoqSD4quaUM2oX6ZtiQZxErYfWLwCVFOJDorGU4zZLP0GsEjHdbTa6c_qO0hMQi14u9b2VLQE7-Ypswc6YIJO3whDkz52VvQE7
KwV-R2Diz5yzd3hreuVwh1yzJ3JzwA4-Yz-nsTNetx6fpmA_K14syj53VHQuOxEhqOyUJfr_Sao0mtH8jHfwkCcGDph82IKzUQE3dF2aHwTM8qVhuyaR7UI4
SFGWHonwsXdaX9jaz217CtgG8wedMW8vAdfy3EHOADhn6CYPUxo4rwj1pcuM8QV7nnN8wMuUB-DUh0Ov4M_egPfezo17Iq-CHv1pWtj8wF5n0ZatI4IFnpY3
dFVr5Ab1pkaRgTGJund8INQAzFXu2UHSKJtRFCQB82TBk6JFldPaZK4O0EjiN-3zN_VqZd3mi1rVHzF-Jx4pvELv2fgu4qv2UE5iiuB6BTst2GTMpulHX7rR
lDviSvCONlPVZpcYYTYCSrSWG9uNA1l_uRORvm4a65XvzhBvuOPmD9CUyCmJJJW00QyyVw89vvXWHlBC4-qtZN3m5i5mCngSQBznXFEYrMFUf17EYCUUeMmI
Zd2UgNhuupEFevaqW7kcH1CEaM3pYOvHYIOSBi5ccyT1eYKQuLmzSWdc06vGDi3jPl7Oaqom88xLHDaWjxKwRcJ11AoUyV4vkrdShSLnvmxFuKxm31Fj1zjc
73SZTE9uPW0qTA9vn78SPx8jY8aEMpOvqK8u34yG4vrfsOHmpdERX4FmJCecXCDjdg0cEkQJiX4EoHF4H6UQQC8XUO8Ok0qJJJXO9wy4Cqq8Fj4IZN3wcoUy
hyFIH4f2uH0y2GVoJCf6EDVLsDEz32fY53Sf6-6KrpC6MgG_YgFAfcQxtOa3vseLJd_MGoGQPDkfutWeNUsSBa_pgZFynBOK1v-U2vpqaeAdMJPse8d5E4os
_S31B_cpH9GDtb4QUmAUZDFAjcRPO3RXmEf9E5qUulWCs8G3Dq-1SwmU8j4Ws-DI788duHnlkCCkJhGVBnCEmPDmSBOPIvFNXDEgdW87yGpBHZZKviauk7ek
BXlXVBftPtWyCWv-oUJupEDex1b1lEJYH1CEYZ20Gxm4dCCmct1g1Voi-oyX4WsnFIoid5e1F-l-Im0DTKQuNeTpTJmz5pW9eUGXoWQpNM_4wMoUZDD-2TWQ
7DjQ7FfPzrz291fYMun3F-l-IuX40sphSL2F53YDwcbUTU8ruU2Ta72QBm6fnR091p_hXDDwoRXiXDEx3qqu3PvXsIp6kQMcdWKEhfxHyNanpXVspct7aLm7
Wh1TNJRB_V-_UyxUQp429fOEGSEccyzpLS0YdIbcNnv7MlKSu21HSQEzCvmhj0k0aoBg9RRBcy71wPdXC1r00qiWPxrVnychdi8pS1BRc_raqEELnvx2Ct0I
srlvqn57uZKXm46YMc8xhc_3PeiuuRoYCATrR2-nRU-opHOddAJgAJm3TgY_awEkznZWy5cFSF94bSJs3d0kUyG01_tG4Su00OXwYQq_d2tEEjAgvrbP7LjB
RFtXt1unm4a-zinx1jwX1ZXjncU00mhp28VlDdsZlGMSZmY0SvuewZ3__VFsvnb_2ecjFvnjGCFjWk4mdiCvr02dpVWyVcuO3yDXFAhPz8TpsMEi0wPdW6Et
GF8pmjxwHXlXy8U7uJ0UCJu3d3xZymY7y10SnZFJDDXRZyyZ7CR3S1YFM09f3MUFG3ZWXmvdB1mTimJoUMlNR1WEVtZECnQUWPROZhYriZe3uEJmV08Tk0wz
n1OTnsU6mtxe28U4c_bB8D7nHcCut7f6EDdhq4jiqNHyPZXyrYCSnZDr2IIQQJKC9_yzFx45CdS99BgEpmdP4zYa79sfIo3HfDam73ZI11p0Csy999gCpmm7
ZZG11_7CMWA99beDmw7f6U4mqCR9KTxgP3Wit30SnZDh2UJuqYy5it2ucmESb6VW9RRxjT7up70O3yDXFCwXFYjYl_JHQXWEjXw6mtHiipdXH6mDncSeyHHN
U0PIOdl67tLheDK0d7Jkwb37StLor5zrlxOOdnbEwdk-TNIyQV1NxPSkupF3mR5wW6EIemvX6lnJMwzcevxY3d14SfIGsEAinwtB-3pMgma4PWk4cmrXYt_N
_L9vV3Pey4WPJjRWTXBR22TYRtUZ-QUu4vEZajZYnzgAZiyIJW8Fm5cO71L3FQu5nsTN8e40ja1CSXJF235KkTQpXws3ZpG11qahXvhWH7mqQJR-AUxav2Z6
nd0YRjMiJW-7yJ0SfkENG1XEtAyDcesNFQSdHp4sXiEAJlqRZP_YSWB1kkGeW5DhhBw5Av50070M94S17AleUAt6bKiW47JcBO4S0NM_5jLglEpv1DbJUmPU
OaCy--KhDXkVGE0z0o-n7O6rVIcj9aG20S19Re5uYOtX-DRZnsShU_AHCfpiKfoLs0ZEUaNd8wRNmTCpmrcV70Lmm4oeE3xx10A6mtSREzGeiGrmeBRwu_Fy
10AH72MMG10Ec0dLncU60wqd0OT8osO3SA3rL1-V_LDSwHcePWDmu6uhEJxx10A6mtHySXJ0WRhL7vzz0e7q3CIDvk34_LfqVFO91007yVWb48R3YaxjPkEV
uahFG3ZK28ThgsLrnlm40h5cO9P068vITFpuN4Nsz9w1bzY6MjPwjXLen5FSuOYVQvEZGjHUO7p6eWwJWRC-EShmsGfeDL3GOJ9my8-QlmGYu8ZMiyUYekav
1GVmp5u24N24ehF5ikBnB047LS_PIo3FaFLH74u23y19R9HwFqV0aQtdil1QI-9XE3uvYh49E60cr1e8Kh6u06THSfI5unMTsqeuVAG9EDnwv1A8X-F7wezr
S5Bzmde6VWd4m_5cmkM-4WxxeGJ79qSXDW6759rwmcTEzGGuKWJYPWDmbhUURI4SnlC9S8oZmpC2mD6r5LCBdaBs13WBagCcmub7hTP3qpF30JeBagDcrlrI
Ig7M2GHdfHycUebjVksr51sHG22tG7Xy5aiWJHIT5xFI_1Q8bzW2geEY8vxYcYqGBx45rCBM4xy23y0nZewNs0AgYvcGIo2ebHprtNeIepJXyKiW2CVN_Okr
7XZL4biWxYU109ncYWxZ0JX7AWd4DXk6qz9CU4tsF981oAhPPE3u-ZAApizLb2En1IB6Pm57j9wYYWx7FGs_RNror7Vh0O4h4u0i7Mg6qzbCICGzlHI0B1rg
XjFVJE2ufrVrRT5i19pEPi9Fq6Jnh5u2wMycuC6iJewA47IQAJfeGfuGbYL71LL_Cs6CUv8B9REMG0GSeLPND1Fmgf-T74Le11nniTLiFTY5CriWVWb4m94Z
GSNMyyEDDbOsEMg2n1OLXcd_FDJZ0JIPXHBjK0iu_cjenRiDlrVyWkIegirclPaGK8aja5ccGLIGFhsYKskXH2o1B8VpkDRF_-AQaXoLmrRiHkFQYi1Xpy1B
REM-TNBj9U3u7n_Es6gEpwpehAzVa1nLPNokttgEOtboL9bcKx_r77EJerWPBJe-UqLdVGZL_2MG_xTt9waHn50GH3sesjFzx-kzLu8FhMSgyWe2HP1P0_3C
ZOYUyMOmttE0fzM6w7c-4MpTRVH2VHtu3x_q4QhfGitfiz_eFEtBKPe-IsF2V3COBTIYFljQlLjAZru2uQREUHxMHwX8sBm1F-GLDeFRwFD-emDj1i7cRvRp
4QeRwFEWqG4s0qQV1x016vtvPh1nDEQDvgDd_X4gI9-jBE0hHy5c0psdZeViQXZq7Fu85QpFtMt4r0ddEdayWniDxshyHcTZCnWS3N2ZmMF273tmr1bwqkUj
dD5gMPz3J_eCDpeRHtDCdqCFhCyrEl3KMQEJFYkFXsuiEf0-XnvuwWmzi3xNwC1JPtUR_AJWxSS4kAkfqO5XKwC3JvsX1zRdnWJtHWizFwu-Xnwtgmazh3xN
wB2mQKnWzRanWUzgGey_TQRL_jJPc90-pxDaVIvN-XnwqkT1ewFgSrdfSurEi1aqEkbpw1bCdQ6d6otqZAREq1Di6XFskvfo1PiQdK5NqvYWTZLboJTQUT1J
P-YXzRb61zRdicZOrEZG-boZ8-jpw96dph9eVGuzj3w77dZgB4lMvtBHKsUD3gtFDJgmFfSbmwOywAuczD3w77hW6wqiMfzhTEYkfaP7dZf3ZmoRicXzJglf
hgR7G-4RhInvwYmNhS-XHzRdjFhZNyBc5m
}

sprite $image372 [207x163/16z] {
t9g7Scin24Hp-zM2ylz_-qgQlEDrt0TXffAgCt1MRc_FhxcimzkhrBIZO9zV0sPOWL8Ai8ylGBCKbCy2qc_SlAEqGbaomumRKAYmJycbuGAsCQqqLAHGmd2c
OeMoIvDOeK7iMLw5PW6ZDcuTSaZ3D5aLqk6SMI4XJKg5T3ZdL4Y7y-L0Su_IY3tBg90EvwGAQMbIApIQeCchq6Z4ar8XnZ4GK4A56ET10ofB5pWF10eVq6Js
C23KEPgcMEF1VJ3cuJYxmLhXFfWES1nu191vhTu3ZjdzGFY0wGJ7Z7bmovvzr7iVE6Pt3EW7nckTEi7HG9VlsGUCOOkbcM4cUGnNmpYAsT1JJdDpcJGD1bwj
hvpcvd9ftFx3T81ZTYCGIrFiVnUFGmYNAmHZQVoZYySXXaiLmj6ULUy2XnXquVSzEnYKrzXassWC3SYbGZgSATsmHk8KcTDQ8IqDRHrGjrWShlCPnz9mki5h
1pYu78YFpuFwwBgOpca4xloNFVleki2vSECEZu_ZFNEFnXbXkbm2dP36ST1jlGo7nm01vBKzec5fMhSFaJXWe8PZGY6lIXhgYi-nqs6WXgC2ekfmFaHx3yRX
OpSSaGbUZMzH7A5vdVeADZISez7ndgbx9nf77li3Hrr9GXhgGd4MOk1bquadfA6ES69t3NHgqz-GuKneOnWEL0ny1R9107cbpP8ARP4uN6WuCi4_Bfup2jaG
YiE5XYE0T3XpPz7JuKB3OI2OEMsMKYWGPm0FXToHZwvbE3DQ3LkstNHzd4-IqcPfXQh53GSduxZgAuasIzyxYA6PYt4nZfi24j8GMXJEk47cMiFH5y_vUmTh
qASaXHmqdR_LdSkk7348H3MQLR3z_v-RPuzGWlkGHgGYpoxBKZWy2jFNeg2Gd6FTyNbK_4foRtcwd4tX0MZ0cj8y-69sjXvFLdVScfA_aZIxLtCt8LoH1GYv
7F4hoH1BKKva2-PgiAOKhoGZ745EB4bOTroE51gNipSAl2tOJmWB4TB8ULtGk9nxe-2A7oX9WD1y_vSdx7iuN4vegBtkSElsrXtb-M_RhpaVqPgwIfB9h2bE
pb4D-05trbGO2i2QKjvzM8Yo8ATkJUdlFg8K2tB0cWA4rfUt_WcxxM8fo25hQjuX14-G6w0XEJ7YF7x8cZ94oCynPKTvjizhvdB8cXg8aB-fbjrz6BJJbvpT
JWJyN9Vch_XLHtaMQcIGmzRKFK9h-Yj-rL5UD423d3rRbgz4PlT5iqF3Seo23QmfhZiJ3c4QaZFzxnZ8sHUUV2Ko-H2cdfnP3gU21SlunQqR7CAKeEcHOrLh
olYMhFyepq992R6sRWfFlX9PWs_9-e_oZ8m2brEqfWRUajMXuLWphA9rQoh88OJgdndW1jHsSk88bwz4N4wu9NlrGiEPm88SiAO08PV32757KvDZsv9VjQQ2
d11nxzxF3B1HC5qEMrFSkb5AXQHD7Gsh8KFt8oTGuzPKqhePdsDc7Wt_dXi5NdZ0ceBMpR83u7eEA1W5L7XcLdSmsZXfruEDZGAqfjAwCr4E8yIfe6WKW3ML
hqH03Y04YRhQWDhlSkYvBY7aSZG8vKP1RaqHGY074E8cXtzi5B0rbQv485GOeVh7L8oD0hQcPeBGB7-6eewGPS6sOXfuO4t1JuJGFaydrbIK1d80eOOltfZj
vFXrtgxmMBeIsShXYEj5A2RXQNTjTxeI0Jb5X8eHDzT7p82scrSY88VZf1yXN_9IDWzr1wofDeJi8K9UKeQvpfsWTKcckcF5Bxcq8lI1XlqUNucGDLNIOqvG
0q9ppH54XX4kGXF_PRLeUpNEgJRci20njQPsqYfo81TK4VeRNzxobGZ8AMHgGgZ1xybM8YwdN4URpGHkkm4QiAOAAHeGgkkfMrDrQ3ZYdXjnK7XoQyeQFXlM
PvDouSbN8e_YZA5fDh0grbH3ezQyOk32WtDrNtBkJzhsq9eQ3HrQxtgE2m-lH1gJSpz2N7XYVrD8pgBlpNBXwOT6Xz1c9zAUdAK8eJLrIHD0qzRts1-211sD
4A4Xw6YK20cWKI8q1HsD026N8qZEYZyLu7847OqAeRaQahFot8AJjYWvQqO7irb9pb91po9EdPm5qxSG6jdqpR_2NxzJ8oI0Hf2q1N6cxti4oLc7aBIZqOyE
TGDTZz1vq312QcZqeuC-EUj71-ve3aE8eJaC8KxEXo74u-O129qJPupGUScP-vw3eU7HWJkQWoBkK6Xu-cPepa98qD5eHmVgQCv5wFo_WUy8GN8-4Y7eQ4v4
w1ycvsy
}

