sprite $image141 [238x154/16z] {
vPhPakGu24K1eOMb_lzt9uoTeLuLxSaPHue-i_JpZTBf2xZW8R0FWhy4hA8g3U5lW4K3gP0U6g8lHe7KO1FzbfvPtohw7PdrBKD_WN1AORleTsJMTmhxCz8f
OUjCCkjRnY9iCdrn2hj2HadOEYjzSNTXXzv0AcxTEdeJuGHZuWq6PMkTDGqJZ8btzCqcx1efUnqdtgLJCc4J39FpEF4sKhErpffHDXuJxoETyhNEMjzahRD6
E9-mQttpjSvQtmJ2xh4BheyJcVN5Ale8Cae-OTTjjCUOc62OnAOBakaRmZxFe0rQPpDzrz-mKkcx7XEVPvGDMcU_OP8MmcRIT_s8KxJHkdKowrj4Fmpf-D1n
8fc-Qs4pwykY7ukCyi1lJkJKbxf-F58VE4vaqvT5Tw7J0sDYWZPQ72UIwbj5zqFA0yU9tVHT7oVIwhiU4_Er4OlkpYWF2BkRljXrGJ9zgsWUX6y9crhVeRbO
xu9ccehrPtrJquGC_dNQmYdpog1VfIN4jiYRgusCg1ADfFh-d1QWL2oIKbyfFwKbGcQecZBlfUzCszmGkM2pzFf6MbU2zFhEjAuYM3YhlgFCjDNSrNqWC6D6
VUSkQ0ZTz4ZhlJ9nmPvNtqZhRjtTnRrT-cf2X5zfNTMEjDxmq9SrgRw6K3IyrKZjNe4PgcNCQyO0nKvlpzJ6W3MZlkPV9PO5hE6jcHn_4fU4-lhNrnT0rOO0
rSFRRkvItHaEVSKoPOsqW5qOWFdqLkr8wnp3P5NByeW3EA0Hoq8xlMtnh4qBCeM-AR86SC9nkXeYxZxOtEKQdXCCaw-iCste2m0exgEvsX5RUwFjszU-9ZCj
O5S6G3lIkhTpU1Q0kGlk-uXdsWc9401YExsD4Xw5g6whxymwqqvO3trnkCiSdZiKXYAsUTQPTjAq0g1eZ1dNyDonCW6hRVY8rsclzWKwlTNXxeOCLECIkrdM
TThW72R9Js_rJ0l03FkSScRMPTgfBvNNyAp8CAGYbz1tYzQvaHOmz8NYuUq01dLde4fGrNPxnEkqSvYiFORdCwrNfdBeQxRV8muC9h_K5_gPTfnjH9U-EsRr
1YjgjE-8jAAHrWfW3Nrt4ZOO29E5lXWlsQA3rHIdlbi86sY1oLhVozj-pSu8XH6xsJx2LlYEjRu4SgtwqS6zuTHt0s4xmXzpddB4NRyzF2CNOB7FVyGk17V0
hXMmjjFRw_0Citrt5NQjB-ayFFUk0wU-7_k8Azna3fD5DRnLyzxTEtn2-zfQs7z9YrCEXxUcDNx0ZR76BlYHZtWXx9fvoc4FRsjzVKUXYg7lnxKEmtiKaG94
SRSQUdvFQNJfkyUOU5zVQ4VQQzLNDmOkG68Vr3e3uRy0cpQ4rdbSgxx6y3prtR5rrct4vuS5r-ixcSgWUShPPKoyCKn6tE-6PoeK-cxREkjTiF3fhKPgeG8S
bzWDniG5Yrsmp-5vK87OVLbjpzPPwwiCs4VyVDKYBTT25Q6PxTewQttdyDoeG7SlK1Xms1F2tc-Tz_Kb2s_xcTOOvoNsqTOX-B-9NH2GPrfNCvhjkwkmwrtm
I4lm-WnAG1pj-vYm20_1XxwbCX78wvGpEfRO1RTfdRkd72BuxZFer7U3CV6slaGmmbizFwTmcQUS1uuJJq9ow8jojP77dmrAZLFE1cFYJLW77Q73MpjRgSvJ
pWF7YMTfeM-ny5RZDPTUvoLsozPPwpi_WwhxgEuLfhuRZ8ctJpb8zTfzUurJ3irJpWF7YSVrXUgdjnondQU-cxRE-fHJst3tplDNdZbsmKyyJho_2vwxRs_N
Tr1HcUsxQUkizGMnrgvJZiJmFFNTj7NMd_MX-VmEggqYCv3O6rcjm0SI-ivJpciv0c88VJSP4--VSiBRQxWIv7CEiHs5NSDpUBwM8qM-vX3RLzYrldHwAsgH
zgI8RJ8ctZ_bbF3ML2Bj2QizS9nuN5_X-JkYCoq0czaVZea4Mp1tGMxpRwaJD3ExCIRkGelsvKZR25vOi6_hhFLjCf0BLvffWnrRPqsHU938fHPc_2wjxziw
QtsHAnSkj4YxL-kiTq7aKfdBAkqyJkmD3Qt8_3BNpDqZxMF7YUTtGNgzvCZfPelMsPsgW-X8st2clN6Ss57Vuq_uJLhla8ZG5w1Yv7IpTUlaq1TcseMmQVHj
yPBDR34cPW6xlLYCYPdqjPCfR6fOPbfZI4zLCrkCYGdrdMDYVaYUQvr_
}

sprite $image141 [119x77/16z] {
lPO9gkGw302rsj7YllznF-d0c1xp3M6Yr5jPXLrTIk0-s0-2rr5pjuRmAd8EFNy4teEwkxb_VnqCxu3jEgdxzRVZIrAleNy6cvOFviFT_8TwnTJd_VuEBem9
THqw5JSiZCPNfkAA-rsbhZSjPT7i1tSgY6R7L5mOJQtYkGaNTegvNEgAJSKrqUmLlo9rioyVs8H5YlVHb2lUIxqH4pwm2MiLxwEvhxXEwbunraMpLtn_4nOe
hfEwAgR2QExlIpwMezOhnbuvTCPK4CtzVHcRinOgRfkFKs5C3MYDfrvneqxByxLUiVB7bEI8TnKhPupEfEygLlvuH3RYLnLti4oBJ0K-NbESh8IUwUcjeTWB
YiqZ1w0gKMGUDhfWkMApo346090oIVgHaSgr5PjvZXCuOILM6vOPGbnNiNcC2xWGHV98pmYch-8YgRzZJyN8cM6Z8ywA2-xt9E4Ff89w-aLh-FY-_1awJtif
PcgVXZwEMV63zplfy8Ce2PD7P9UhukUYcKSrWhz05SGO7fdAK_5pKiS80LYX9dn4UcOGRcAw5Sqa6_mFt4Wyqx8xurJyYDG3uOT5SMQq4GTl5D--NsVOWghK
yWWVtWdLtUq1gGfxhefPHaGCqyrRpmsf7M6olMcrx-23BiKFHhE_QMm-F9nmMTGtfGhSW5Jno64aGsa-4f-8PWytGNFYp91PyKFHx1KBeGxFC46vAgwHkiP4
cU7VYdLHl9FwYLjIrtsfLqpCKt61r4KnInyHPi4q5U-avXW7mOOR5LiVwKHVnV-s2UzKtCtIqm-aLV5VGrFX8QW9j97NelvHl4WT-qruls8-5STe27GgVZ2Q
lM8M6vxjF0sRcsrU7nu4LQZvqEybKeJRaz7i5QCfy_c_HwoRi0ff3AA2W1uHIpHrQ1C-nqP6vERruNd5JG38HyRczQ56yHoxYQP0iSR8MAIMe_vr-qc5Ly4M
CQM-29aJtES_
}

