sprite $image300 [213x174/16z] {
t9U7aImX44CnFT1Yo3_TzSitPtIM6l4oKC5JgSDqz8aL5seA2s5uK69OX8o_iB02gU8V5b0h5hoWHdMPNgKeo-Hu2nEkyRTnoNhVGAXHK2REfbZZd2nOuvoQ
17yUfqJ16kUOH8rpb9OJaOcefIoJqd9AZkzXaZNErPByUKhBAUF7s0GsaQfQ1J-C9q6PE2KArZZ7n3RHiO-I3RzAJP8rpjKIh76E7N0JAIqdmqHgd7JQpgKe
rZZ796kSgoKf4rTBiCOvcsADSqpmvt5g4gnnJeaJQbps3nOSYpn19W6ro6ahg1QNILyjmu7nFE6qFUPoIhNQX4qqzoX1Sw-9R28rjT1xSozno2I19nQgxt0t
iecar4A_ihixnDX8g0jDC5OceIv0BrPD9DHTBOXH8Wcb-GUDXDACvPc5wliAQg7KFbX5BOGmKYsZ5c98_Sg-a5hm4AwH6jgkhbOSeNfhlJTS6QcabzCOj7Vs
LTJ2Y3H2oSOQHuatt1bEoTTxY3uozO6oMgqZ-Cjd4ls38mQCH18xIcunuAyLXAPQGw1tRJeNOru9SWD12Eq92btb-r_NIJZREFKRwai_6zuAM1X0WxJo1AKN
1M05aFu22cXEX9aC56Cjtam6Yj4Whpm31M7nodDGYBLuvVqj5D2S02G31MYGDvE5Wh5uCtae8DvXvNaem5gWyX0eQJ25H44ftXDc0g645J0J09NIe9J7Gmah
e3mKIjOAA8-44bP0UIoKDCWZyL0UYpSJ3oKDycRYeNnpufNdeNeMe45OUHwgQzahC_4EACz0bHu0Qt587af8WgAinPj9Pxu7O2tQJ3hpFO3cH2jFPruJO2rS
UOBQFd-FAljzU0qkKyqnxbD_bYeOYqVIxMECxKAfwm0DdeYPFDIudLz18TP2pEIXndZK--SM5QT1Ndc2qctzDTOR00jGde7IxT8WPYr6UHvgt2UcGJKd0Cb1
XQqbCos7aWQDjR1H8ZCHKBeZ4EzI7WSr7fFMe54U0ALxujOoogEWPAqglZb9UJpKovgJa32eXBMCcGWeMQjfB839GBsiEGMWnWrlJlLwABuv0RQgX-61HecX
0DyJsfowvYmGwRnP56IKbEaGWF9eQmc9XEhjBuWMZP8sROypax_R_rch2sfxkdaVxe3cP5vJm4pBHWdwclhtoYEQKtiaFiPrAqU9Seynar4UQotCJVrSGEIR
auTgFCPvQ_5Gyw_Dj7AK22eJurHp4bGYne7cX0N5SGE0p2W1e80ONp1A1CN6E6yj3yN7E6yjGSLY71Wb1egASQ0vKL2zmHp-urm4wY01_huv2IemRO5HiWwg
J8o7ubrGWHW7HucWW6aRj9QW0fq872M20c8yQ2r1SMPAD2T11M8S72M22dGYSfG82fYsuFcFSx-6wbcDJrlUMbz3TUa1Zt6-EGdgGX8KFMtvKJ9rWW9YF31A
lcLgODe6cfD1ecASRqvbf0V5E7zt8LK1qpPehIl-2eZnf0Ql_rf0Z8SrYCHuVfGWqpRVd80Opz_1JDjyS_fQUGEus2ZH0TABMGk1oeyI12flBGGgFqe8gBor
c7Bq3W
}

sprite $image300 [107x87/16z] {
jPPPijj030D7-n2Wxt_SxC67Kgf0hCV-zT8MUqHhl6IRvp948-k5Y3ZwHSiPFqs1kJMRza3y0TVQADec8WJYNDeYIIJPtXBfY9kfAzcksGabwvrTKp8TSD6M
J954KxBj7gaXcI9v88wbAvAVpDz2FhYsjaXte6GDaUna_XRomTphMqZuoHfdv-yg_u3xoGfRg2UPVy3BkshR2f5goGBdMeXKIOPadBNPlVrxYSnapB2f9qF-
15EolcJuPBPUc98jnvdPAbEovLYOeAROcGn4p63-aKLZia14WErJZ7sLg5b6pWYaQ4i69Y9a4iJySb4cPaZLC4M9f6gL8VCVLKioC1zKVZ9VT5UrJ94ff6gG
APAhgYS3qrRLBqmYNrMNIMIh168M8zrLP0e_cJyxgOW8EbCiYwJIS0rP8P9K3p-bbWpCPx07GBWk9VD58iPoPGAWATCK_Tb9DSOMIUZ2YZ9a6gen3YPGdA8N
MwgVKtmfUoUIwYVhB4-HcPvAR2Z85CbNLPE1ML2LaY5DA9MIHVBLNMQxFjUuitl9g7Tu8kuo-Ccq3PasF9SXNYMZZfx7NCSJIlPy0uFfWctSi9FnbOZ7-2_d
KpBEGBfS3v6yPFHFHAp3P5EoaWhxy56omW1vEeBdPBvgAfBFCfNCLyKsAYYPeLAaCZibCrJQGZLEJL4gOmkLq1C1a_6i-i28v2UJojX2POxVoNwfI6SBrLb-
9ei8C29eRw5wigcdF-k0rzaaihTGdJq052BLabMsK3sPxgHzDBFXjqgHEZduoMIhGYmNFr9ris8Ec-y
}

