sprite $image269 [176x128/16z] {
rTY7ThGu38PXOG_OAhx_srqyCrjOE__m4UM8lEdzEOeeIVcXHCelIdfSVaaixtxHSD_zBktznJB6Dr_SiRiFT-pkslkBvLDyS-tOFG-p-ui5wERQCRwHjfxQ
bVlCza5ZcupTvJ3RQAmskObuelZWZLpZAMBkdHUjxI5UaVZhmpBt1elbopBe5OxJzXwOjnUcxQsejnUaxHNSsmkx3UCnRL4t5NAYDadE5ABjST_XHQJsvqXX
sfu-lIenOZwhVT0x4zwz3GIpbnRnFZOY4i3hF6A1AjhAxgs0rrKiO6hMvxi1NaUnNAbxLy3hjiOibxtvxQrLhkGmNCoRdbvzxFBY80Qrk9UwzzNASYa7BU3b
btSfPd8nnhNNlPLVscPoFU_3R1uNvf9vRzUgOE5YSIWJqMPxykrWBTvApr8HZ_Y7jINHtprOFF9UtFajMcyfuXAWnTeMEfPPN79QXNeSRgAnxVDNusiiasYI
7DeIfNeupcQbBrZRybfmcYLZWnRrranxgxmg2ttLAfDgUYxu9-yePW6yvT3MZOaFnzcifSvEJIljPS3x58iWteN6U3ZEnhBiLPe4UOKLyzfGQqqIVMvJaTaN
DvgbCazL8IzFAdIgPCgJ3F2gDTqxxzM5nigMw7DP5DW7aqbctTixxTsUG3waAX_5I-s2z7pjp7njgktUT-UyPfg85h53UhXjcBMPofwbFcYrG-UyQaUldlEA
sjR1aqgcBtgeoIljuAGVVmwrGNlmJiNMXan4L9axOAnEnKbCZvViQXz_qD5hDdfx9x-DTi0qpkFYDZtUOsogyla7wQ0TlACOJ_ydtipaUwaDNW2CYH_3RmBE
RF1wY-qjJjpCGJjutSNQnKjf7gimUjt5DQSid7DAnM6uWzSRN6Yl6krj3jh1won-K8zj8QBYi0g3rrNCYTxUrBtEskvr1PU5QDNSlVcwrmppNXUNmjhiwLq7
Bwp5lRXOL2HrxtRDgmPuNSHlRxdaDKEzOzUyzUdbbK4jxXsxukNkvKGBewk0UyTmhon4MwQbWiF5lVDWRwAzpLfJG0ju_S2FbCLapJbBQmQi0k1r5MjdQjip
1RI0rqjSrw4g7pAWLjHLN6XezTBsofv2uLwJhrDOYuj1R_w35zQwYkVUnTnMmHzSQCoyLi5TFFTwd1Lw_kAvjtvNEt2zn7DlSLe5V_3Skpff_SLpRvP33be_
CHSUynuk3eR-2skkMl-bSBoSXOeDvOQA5TM6Wl7BMQZOK6we65-5G36-2h5WGxcXOdmL0iG1MfTBT9Ys1uCDvSQAOMsm6DF6Wp5kl1ZJneknwqEy6Fj3FHwC
hKAy6DF6Yp5jF1ZZneinRRmOqyQBCMuy6DF6Yx7BMRmOuyQBiLM81sEpZHTZt7WnjWhnO4mRByQqyMAC6o_6jF5WJ1ilXhZnwGzf_m8
}

