sprite $image281 [260x260/16z] {
xDOrOiKm48R1CEm6xd_RwA_2z3fhPshZPmkUzmC000000000001GfS3oDBv0A10IX0AXm291A10AX0AB15MjGFVm0jNxDhZxQu4OFWmwXW-33WNUDkY1m-1z
Wug1Fq6ydqP75NZVO8-DOzVf3JRPFbUS5E6hKpSl4FrMVMNt0l4kmV4hNDL9tXKuU8KwLGhyx6gZ0gTJ82G81PQdyGL2WP1WkHzV81HOMe9k1ReLw9vS80bY
-ayG2hnmSnxOpUCw60KxIlAy_zM-cL4is1OjWn9y4YRtbEb5by37cl_cWFdN6I2yGkHGe0vuuPSOm5Po3F10Y2dNHdpw9eALwHMq4k4LCLSwSGgFtNvoKWDK
4umGB0zYdSBFQg0bE40iv3g4dr01rT1zPSgbjYzgoIbsVqEb8GdydDcAO6CWbaRImrZpeudKJ0kypqm6MdXeTfHNC3waPgol9Vp4hbhuA9JXXWfuFRRtuHbU
M62BEOg08YXbCtQOSsN6N2fsurkZOM6GdpV0660bimgu5KXW9W28Jme2Cwn4dCG2dm1X9U36G865nfm1W9xr1UURG9h0mlzy2X8l1lgP8dxzNPNvjONGVbm2
du629e4Qw6OAP8xQ3Bs6Mvva_auBEIUF0INlA4XmHsQksWmz8arJWRxDGbv8RWFSz3CV5N24UuXvcJDs9QYpWFmj5h82JWNwgK6ahuyRbJbhCpotK6wDum67
3AHyHxePS0KYRXrKK6wfIBoFj549_bAeUGERs6cGjWgOODiCQApv10Sb-2qmbln0TSHGq3BekwHR2eiO4bPlWTY9FGEs_4ZZa-XWYx3IDKFfDWzM9KHs8gO3
far35FJ5GP9dVXHI1GQoYijE1PQ31IeR2-IP6OliPCNHsfOq40d-gxdRXiuT2-gWxZNAyPMFknj4XXrOiU1tm0MKn0PTZBGtNCqnMmxwMCXuCW_A_fWURl3W
AOJ-EiBU6Q4p5lfXxiTqNzFBwa7drHolsBl3veg520k1ExgDKpqutsP-suDuom6J4GkUGIEuenrhXk1Ne1WEZ5Xm3be3fHTb50-TCz0ha0_3mVDOG6Rt_x0M
YhrCy0T2Rq3v-Fmq73XZ0Or2a0H7bmdbrEouPq0-FqSTCDLpiP2jKOjm8paScEmQi1qeL4vPC0izm8tii6ho90W-3GSzc4_4GZF7E1oR8QD6Z9F5m547J2TY
GSUj34beu_jnTg1jO3kmOy6s8CcK49_Da5WJlbXSHeS3RODZ3XGy7WjH9LYQD3ZewuQkx1TD4LyRU1mmjyEn4At8am9AA2a2jA-xo4HxUmmMZm6lWxuX2WrA
Y6IT6YkP1OFUhtLfaCKH11u72fLZiI392duXJKRr9Pms_K3HKGOQ10u7dbWGhU6qOqiamuOcqXOPlO8ghZRmE-XZmTvA2GRZg404GzyF5BKVxXGa4OS1XmDV
BDpVeLVpRxdrWvHrrN1J54yf4CD0vy0J2_OuXqg3fL1PC3PziB4GMSGR18h_bG7cBXQ6BauXb1qBjUy74U5wavFEA30CU1mm7Oa54Sx60qmHPY94RAtLMaeX
Pf6c1hg739us-33EbHsnO5fGqXCDie4n1tXyq_J-8F0_F3iM2rp2mEliLO3-pRUdVUyA0eS3SiU2j0ZtX9GhKjTbDSTDDf0Qy0U1oq59QCM2RO5AX2qXnlH5
Z04MEWFofZPmEa20x8W5hNIg4OQ9bUNTRU390m10Looe1cvvn4DQ1Bon3VmEqjxMf-L35hXxhjyJKaMHTnlmEwW0oPWdbJPuvarOIqunX2K8GeWnbTf8Ljwu
CBOPl3GONZuNP0inuBSlZFqEEAo1G8NiM2Z48npuV7yR-1taTGFS85H7BBZn6_07GWQ0wem5F_uWw1cwJjPpGXoAXOpimny4RxOG0V3g0aPtrONcReEUeK1e
UeU6IBo1lY4MN3ja6pGk4ICpbsiSO5oMypyR2_BXDj1Z109f753OEpT7RopuWy3Boq1epDTdGVN5rNdhOs6E8F1RA025yVhP2LRAo3nPQORvq2y10QB6mN8x
IaiejA5viitT1Zsqjt-cjAI2jWJdhrjZSiJ296tGixD_Rk7wxPe4SUc6bcWW5d1k0ptFbylhjsiGu5TX12Wq4WiJh0XS3O6mqDJ1MWXr2Smy4WkLfWw2dkVl
GUZwk-L-CqKxpz0mRsbpjq7FawTMKMD0ApwzE6mZPopu3VZf7iMKLKT-jfHc78Y5GbEj26oshsBQgYC-FMYAGyldIfC6WMsXHG1I7Np7cehj-S_hDsyi_9o1
taBD3yS9oZKLQObDV7Sio0yRK0lzi7U9MMktZNB4WdE7_7wURgMx_KJtgjYAXQc3e6Ul47IP7FiZ1NyiJ6IWjq1XFLoBTF-UD8uztb1mxY3esRxGpuWHLWbj
v1KwbJuMfcq3UnDHOAMkXG6Gs0BpO2nCPq3Phfqr1VDk8DgxwiaDz7ILaEvsbVN4cwuwSH3Olt0KHltnWmWByVYRBloG-OEWXnMiZNHI2A5R9Dgnm9-VCdaR
sB5m2yHQ0VAnfvvLFjN1x0PwdXmjTAj7CnPm-JwnWs1IyhOCK6yb3sw6n0o2UM65hajd10Z7jyJYQ8EfB6JI6xd33emsc1tZ0Tkm0_am3CmCTdjgFEp0EYEO
7zhC4Fcm0pi8vcTp4qC77JWCp6a14rIV0rl1_ANGij_1vNVopfy-_BsyoS7bT_CE1vVVZdWTNFu2BWUNly9f1vU_n3a7bxy57dTm-NiST73vcnnmSFcxiCK_
xT1N0S8050ImN_RvTyj1fuQ-H4867CH1wkwW7AGSrDr1EKWvI3ae1oa7AGVrSL0EKWvI3kfyaB6sWupsFyXqprmV0000000000000000V04
}

