sprite $image190 [267x249/16z] {
xD1N0OHG302mNrxByA_s1XiCt6WY8TCtYLKtLHSx4oiN6RiiNj7dFb6-Ohl8NaMVirx5HeKA5IfKg52XGeKA5IfKg52XGeKA5IfKg53nsrIeKA52XGeLAbIe
KA52XGeLAbIeKA4YPYhcYLcMhuY32XKgxZ9McTKh-inreYzVqVVvrlSgLlzJeKA52XKgL4HhAjxQB5H4stJ5Auw99_dqZLmv40HHqA7AcbZS_xWRtwCcv2Wy
jxsCQjoP8ZwMsrBusYqf5j_tT3iAFtSl2hzt7uetV_Lw4mfhkWD5_5r2PgU85QMKaZ0pnMATn2DucvR2HWdCIP4j4W78X1HMzb42ormKIzWmYlXG9gBWY0Hc
eSXX2IbJKDXGUVIzqVWKuVWe86LiYc9JlqYWb74f2ZQFulVxe1JP8n6_bJ8Y1KuU1KX6etYolRz70MGe2YuQ1J0E1NifOcKPWiBEoXOA-gS8NFmVG3gde1g5
l7PC4LJw3w1NYZTgKz0ZnU9GsKaXtL5m0eLTBLrHq922ZYWqfg0J2jfJM3gWY2ueI6EADtgXe2a5FL58CmfEfeYZFJMXY5CxXuBw5A5F2kfIB4ul3mkdb8eK
qJK5gKGHeDyFGQfGC005kPm2qFk7G2wb08FC0jTH51Xe5hY8WWeKSMwvW28mtYmucs9HeojcWJCfeawvoC9f556hyiW5vHIAmEYpO3bCyOGvB1oam3mMEK2X
GUL22zb94QQpy3OIHQwri8UYb4nfiOTYKekKxHIFCg65b2qKZvP_TJ3gMoXb4qNolvppK7hSXe5mUg9TG7h_fqqLVRJseCXpfd64CELw-R_X5j6aR3MII8E1
eN__2oY81RvQrOK1lfWWT5595HOB-8fjOW6pB0FaU7bUHq5Y4SkeiZ2kV_g-q7S4SBUiXJ4UnYzNYZUi8Q3VMYNalp0UAic1WImOMhpX_cmPIqaOruettHgL
DKiboJ1Wjd_bdMKW5GQJO621jGYnXr5OLh3AqlWWZ5uSxJkPNHpWI1e0mdSQxcMpkIOJWxNDC1W0zYyfGd78quQ0QnuCK72yyUyCwkVwI8uluZ3fujFIYFys
LGdwijceWDB5KsaGmBUfGgcgIbGSOgGfCFJh85u40W0CQQfA3ibXTg02G60auY3n_qJGGH0CCOnZSi3jqCKNwUAfEDf0HWXSqTOJ2XL7VXUFWLmVXH33qFsA
dGhnm6D1iEO2EMK2l6egNV6Mihcmw-9HiEOFPBwfY_VYwAbO-muXNRpWo7v5J-LX6P0kNXG6rICzxk9WNHZOIDclC4eNRp0Wbb5cqF9KzokYntUlQHcmlbii
T4qEjk-8PG2LGBWVYfO-VEmqeFlYnZ8WQEv-rZgrYxDh6UPLKD3SEnITPRY5L1OygBYj_w8m5D16Gz6nqFsAHaNtnTUD_nsWdHe6w6raTozA3bD7nNyejXKp
cuIWY2m3W7Jn7GyRYeqJQoD4iO4yrggTYkoBEniAJ0j2K0YCg8kZMpGsDmhGFKQXAX7BwBluDZCAcbz08LrSgEmHCYyA20X5eLb2A9M-U7FjKG2pQKDHn30G
12kDE-4kJBaQ9WZGooZYBeuEZpbrAN3RLawc3KMXisgmeklYtTVSezXyIX2A8WvMwU9RWC8cCuaOnVLWnMGeQFuQYXY67CAO2WKKn7KKcYK7AW6AsRIXAE81
AViLzbKO41GJQ4DGN5iPQXdF0-zHE6VGHepYSXVdrnS6-ulHpWb0A8fNWtK118RU4KT-kNmdYc1VV8S1VBye1CHxK6YmolslT1IgZJ4ej8ih34MH6g13KEXM
CCKo8XH8CeanA1G6WEU5WH05WGoJ68L2OJG6iKhWEmeI6IOn7iLcNrZW70PTVYt19CQWK1XAHGVsGHYqpu68LHAs3BfzY0K-1KA3zO9bBEWsFBv3RQpVG44N
1aw3zUdf9JT0TMnxo_2QPSZJovX9174zMELyS06JY600Py6gvrVAcCJvmb3BwCK1yFqmC210nmJhipZGg1JGXivwRXd1Xz6P86mRDZphueWEXawT6_7W95WH
taeh1oAs33tinmEL0YOHmi2vE1Q8PNmoDxXzQ2peui77hjP09MWZHoM88uGxbGHj9C4ucALIgGOYxkATEAApvADRzfOpP1mXe5Z6JYLXcoe1Hd1onoLUocX3
ktWV8TG80SKoKX-ynWThV787ycg0CjeuF_nvUl46sAaKqiRviJOnKg5I3uIUKT7pmK8bX07EJkByxYR3U4amYGmOVNY6TmjGGXiwvtStW_Tc32wN-PRXYCtI
95vAc4HSFobcAUBeRp-N0X47gp6c0fAaMIKG2YD-AO8SUQkp99H5_1uLeqG8Q2m2GiSOHiYoc1Wf5XO4eIgvr3evu3FGzD73dsOnbNtvq1AsS5Ci0untW46I
ITh8x-8Q8MvrbqGSh035I05MN14AGr-AOB9nmTeauiTthHkM3Y8_M06IjD8WD5WPHyWDIEYn310T5O5H6eG-lflfnsMy2gAyPSGeRAivPB03pEmbaV_4Aavn
3n3ntKtIhBWshj_T16y68kxY2ujhu_hTJPZkpjmBHb2yRRlNaD5-nNQxGSS2b1LnruMnK5R4RM7mfaj27zzDbiHj5uQ0k2yCjqzfuoy
}

