sprite $image208 [252x260/16z] {
xDRL0GCW30RXueJ0_kFMzRt-tstmeTcylb1xsaWMYkrhKP2UkvqgGKmUcrthMKaUgjqtgjnnlz9dbw6NyIXVIyZkFgvoNqlCxkEazxdqx7lzwRXBslUj9MkV
sB5_UTYnOyUE7JjsxDYnOyTUXUqDEtRisBycxDYnOyUE7JjsxDYnOyUE7JjsxDYRiBrYVr_OiMF7ZXqxTkpOiMF7ZXqxTkpOiMF77apNdbpNNeJjNTSUniM-
vEp9TUr5sDw4xLtOFdJjuNljKTOUcxKNw-DtsaErGpNesRDToYyTRRxFdhhTwkbjzZdCl7xuejytHdZJcVTMzvNmENhPLNSkwf6hE12EOxSnkk3tVzjTGYUL
fl5eI0STflRcFVSVgLJ8dc_caPo5dTXfBxgz_sTL9wf-yanU738EwBxqTIs-w8bLlTWbxD-qBQtni7jaBXLoKR0F4TWbxezQdwBd8AAmEcGkVRJxQFQ3lmJg
PkFV8XKTst3sKlFHx3j_gYxxmyHVRf6WU5iSsHtUNOIzfNN9_qJx1xa83wJtPryDzlsstiavdUT9gFt-_e-pOz3J1Nk8XLpF_qk8Xj7xisFOXJPvuPHChan4
BC93wFtPOVZZcVmevANT4tyUGY8el3kmkniUv9fvfJe4atv-TdoBrCVA7tHNCNfz22eyWdvbHtOONbM-IXy-o67qrY5eH-tdPrUL641U6JrbNgxEmw2VdNtP
wOjTuxg173r-TGWgHk9DoWwzXpixtvPoaQbp3UsEGoYFJ0JwPJvsMsjaLWaWHtcl3W5DOT3FoWxTAAuWHtdnY4Ee1v-AiULCouxE9xh8jRDz27WaA6uJijla
TgubkJe4WtvQTf1Vajc7a19Eu5Z_6VOLv7PvqHJrzAylE_EpWzmghpNzwv4_Cpl88Rkyz_EGjZDIgbxjJCeESeZ5BA_X327OVfkM7HEkLZ8yNqUWiTzEmswJ
4_zrhcax3PDIKOJjFTdxoI7ctd2lhmHtygnj1dQR7B9xtDvlyGbz8dRSswb0f2GDTf1LFMuS0YuxyQvzcOHzAUHLWHEtEnza_TDVZLzxr9iT7vUWz05FJTNb
RPz7VSEv7qA4mlgVisyWBtsfV0TGQYg1hE_6zq5EB6GqlXVxUZo10Vf2tBFLeDq_a3aPZU_63d84UO4tPULQtUwSMIcLHoWi3knch4bIoG2QpbF8L5-uI-Oi
ZuKSnhyvi5l3_Sm2jAsErIwJVlUyF3J-wis-nTR5vMJgaHZXNepEcH2UBxzL8hGlRkorqJMfb4ltcVhOELs6Eup-mGlFCpnVbTw1lMvtFb4dfauLyclFIztk
o7aIvLRfRVPVlClecKK_bf5h97YipYDLfH_CZdQ79Bt4BizR3QL6ZyFpUAnSFu3TNjUONjPrhXNojkU9SG3RIFPbfs5Ajj7Rvv407vPXx5kaKS9BoNPZN-Ly
bNPn6y0EeuyKSgrbT3pMCp0IIl_-Y-mmkeEu5MPMpkTMKS9-OxBtvzfuPI0qTgl7hu-6ge5li4_MxZ6BwB77pPp7OvNr1ljCxHwBh5oZovmdhgvv5hj_hjde
aH5cHixNLo2gIlyY-nQzo25cm-ZNvm7T3FP9ZDvKLyxZaQXAEulTDhe_UYbaNywJF4pyMoUxVwwrHQfTETzSSCBoC_RDfTqDDHlRFW_2oEjWzyqrIuHkxiXv
qlHLV7hlOFVCDLE4CBDolfg1zDatQoUxcz5j4NAU--uzMQowRXQxVwvrwASvJw8zxFwvPekwSnxe1li4kMQ8fI_dYrZKO9yarsorSwtnJXD5xs5VmxJa1TBE
UGAwmJvHhjbbJqyvt_8y-lsQNPR9SisMdVDLqI_PjybopLOxvt4U5Verk-xJNM1jKVfZpXUngiKUMryMNvSc6OMEZp0jpwFeDZkFU34ZANVV47AelRG2tMQN
vTUDNlwX1fD7IerSAoBM8ejz_MsZSww196LYbG7eC7Jb-QheDhlUVlq2Mv0rvN8eoCS8xTu8TM5YgTXPeJ3e3MmkHn9EoWF98oAkqUzyxFj-CDZhmaVcKP-I
XPX94geoWXtaTR_JNXJbYfsOXz2h2cLm9aqSdSHQesS5aZQx91r5dvX8pvJEqmUUH24EEnIuoQuigZA2lbGzHr5Yel7e3rHox0_QRjmOTimZwJCwIqf9UIX-
7UgyLphQxCFeopzHkUlyNoFfwr0_hjcbOXz0ZrsoB5t4AV7OVeSa_2sxdgNpa_2luKT8plJvm0v5hrhUP3-5izGO-fteWBzdF8qjEaHzx2d9hz4tNZK9ZHno
BzOz3-GiUPd-OlCOF-GWwMK_XUNro8kU8f0ywkXdJsTYqC-FBdeXYS5cbuhzFlMaXDy_LtI8ZmjsnaHiiF_Kzt62eaD2mM0_skm4-adHMTIIn3_t_At9BaSm
w6SkEYJ77zXbQRE7VU-YZxCL7RQ_P8zlb-mTz76weaD25-noo-ofoPvrP7epyABxUEyGtvQroSxBDRj1FtNH8SeluPUjmHxV37QJFavTT0dBvxV6EkBaCDX1
Bw2VlkYjpypr-pg-lTdiXRvvrVClkdQ9tj--j1BOIpzOx51y7lbnpc13lxzzrnBGyh4SYi4E1T23VDvsLzxUAhtVkvVAxx7PQ_fY-xbd74fRQOiil2zl7UoW
9mozcTjT1O0FMlQ0C-bYnyZtBJs9TlUxeMvsq2UKVhvs5_JxY-pXJxQVa5nbjv1jzd1yO5DyfgUlYJzTkoklRw-pyvaoDJ77O3J-FEHoB7s_1evUi9-IsKMI
77ijXyOdxaU_TVziuPeQxCVvKVZx3sDgslu-yQSWho-njh3Zf9fzvyAUpYobPkCh6j-XtUsbhLzhhk6Pk9hpHsvrEk-I6AvBJqvRYntg_ReHirJiHNH-YO_c
n3TSxzFkSlJsUxtcI8CzVR4hK_ExDahlq-wl3xcBDOThTZa1px6nuI3i7Sdj8TTlUswom_FxGKTDZvddR7HiwgzhkT4pEyiZEpztFcQUfz7j8TTl-vgTuVYK
sKMLWZ7p_DeTDxdNjHwFx0Unf0Vs_237KzYZz3xjZdUElwWjCX_XOPWbi1zIdlXepJoKtg7TEzRLdciknV0TIyyYBUo5daBZdlV3qeDymBhQUyrzf2_0AGdO
FquY6AKVP7HySncYDL8yljEhYZ23FKleUAdqCBfhijdQYEBnMDGFTWPx4gxZhhlqn1CKtROz5VO4UEK_N797jhk4yRywJDNubDa5yAdDZjBRv9CKtRPz29bD
KVXo4GWL-r-MddZEekEQc-chArnwP3_Y4MhsSiqZ-dLoV5E276oFOQxVsKCcF2fsi_GaEdFHiTq-sZv4Vc0lzGqrUt4z6RascTFjj0-KCEi2Sq4CbT-lIuzs
d-0YP-f6bUqvYOfyiXV40-pdgIYzqUwThoZyjOHdspCNTYsa9E4RUwfS_p8vLZP_hS-slxDd0mYpFB2VKgfU1huntNjVHlfhYpNz9pkdiy6k-RzAwOb0xX1i
BdctbvudEQN9hiZwLzfzDuBDAUyg-imkPqgdDjaJCwkKqhCwjBjFte4zGrwpoztwZf7kjzqIiwJ4DJk3FJ6pntJtjttXhTbJnSxYTOFrtMv3P9kTdLv5-c-t
PBDxvPh_TdkGaC7kbMl-jW_vqM3toZN_xVRNs6MMNBElkHti7hdclztQx5ultlstMvlTpUZ-swt9xfXh_jljo-nyCt9jqhoB5CDhx7BCJ6v_kwtPzQ_P9KwU
Q_Orrs1tp3N_lACViSk02wo_xTbWzpIw_pNNO7TzCUDlUuFTCzVyjrjYDTZTNipuqmSMCTZ_xLopVuZYdzd5wGBhhoqofuhTuSNCF7adNB4xx6lJsBvYTyYr
kMoVdjZPmUYJs5u5x0wvDfFjYOiSZ3xXTWjsXroRyPhB3hasfMx4xB2lJPlsq-NQ_m
}

sprite $image208 [126x130/16z] {
xCy55SD050NHPVZWNswRE0WllJ5mpvYpXHfDgrocIiKtiMqYgblSXC-ysyGQMkX5Y3PRM-dCeYrrrHNUeKE7NhcrhgleqA53X-udrA53XmuTkkEMUfIMUcwg
LswfqvEw_TTkPskEgp0GWECDa4g2zt_R2RGI77-EssfxwkhiVvU4ScRr_lCtwcEasVlaxzA7XUo7FFqwKhgcpudf6UR1FtaEprpX1suu58FtrGb2op8-B5DS
1gSEPXPrwbJr52pBO5DaK73FKDMhHm4GmplJyBGb2pCuZ2vT_FfIzT2JY95BhZY3u-ZNtOy-BQ4b9cRMaa4e1MI-LtS_EuelMqeHGYxAh1dCVCuVyJSz0D3C
SoHchgorbrA48URVhrl691Bdo6pikdt9p3R_-tNB70AZ3Hs4RVkScn-6_wIFBrkOstF_R0yMgVuo_0TzYjKsgxKlnduiWHaqtwcRtI8PlVtU4fI9aQOxzJ5o
ZxujlB-CTNk1FVzRTBDxmCtYRqi0CJ4jmrNTR3IpPB15khM_111ncYxhG-0Q22h7FTac_R44jIM0cAcE_v8-B3-zRRJhmDZr4goz46bHeZh-2_fCpPQYW0fl
exBznALrU-K-Vhy-fMh3YDrWS-nISc-VkTRdCFn17oBNs75_pthts_PPoUhlw4TuNRZnUgphwW29jksPhRv3dmXyFcBjUQTzGNjzqtbzZEoBMVlj8TKFmpbz
2EnE8xwrLxBjdz1dWjkkuOFs6Qt-h_gK_BQ5wNFtkchFr6v_FDI7o7wxHxwtRyVFj1pe2r_2QmxQ2uWuTltwmhTX_Tw-L5rctjF7TBMtHRwt9rQPU_ThLxOV
_jQU2BghBpSClOVpJdiY5ltGXmjNTfnjUyFNkapdFrOX3fi8-j7-P-gVkYxFXI-dR2tPWzVegxqLt-YYwUoLIHQHh0wR2DQ-nZOjfaDhs75bMbH4c1o13PsQ
9Yb4Djs-6F3PG03HJ9umhPvR3Cz4xhgAE7oHN5HzzVjpes3fEY3dlm1Ye6JV-AsuLQ-9ArqoSCetKPK8S1GtN17sz29PplXaWQSvGr-H3nrllQZeRpwvOrFl
eQzwQUzPSAjDq8yWRdIiT3B_zk8z75UwQEgwn93ClxjuZz3wrStGbrxd4XD4v0wRPSzMMORPT54yFlMdJr31PHkw6wxVcv_5keUDtlrBEFQBQtoqnBPs6XzR
tNnHmNr3Drpc_dr4uVOdMzry5fK_yj23gR_zuR6hMnABWkyPkarz9rsNc102fxVVrdzrw8PZVkmboael750ahTVFVFcbYoeDNt_G6_arUQOWfHJ4z_WzzV6j
k8J7zymiVUzLBvc2XM2-U-WzF3qEiq1XEagDnXZxwmTxxUrpEyuGNpfhAnz9QFFw_0ktvtOY4qbg5kVAHof5KtzzOF_2xRcToqpKCCgrEnTxVhs-T-6YidX-
DmmbMxL4gdg_ldPypg4hZTwVauy_VgBS-DNZ5m6V7RhTcJTJecXbJO_HT8W8dnswVQoxir2oNLUT5mB57nrM_yYsR8lxrnyePwL00awnwgfhdg6EZJioslWZ
WHOg1U2c5yWp-6tXYkLnAJFz-2a5oghoqdDkzG-7hd5mICVh3wGbTxr0LSGxT7-6-Bf-bRMUo-7GPxzqlFx46nroxQNxFdmZfMFTYgVnSMzUr_URBlQ_yJjZ
7xx7kl_A_1--nzt5SsN-zH_epYlpPwXuqxFflYkxVdqRtNLbrpFHhfuS2x-K1T9r_vLTNx-OxhYoUzUVSzN5SMKtPcQfkkFAxit24CV2xyuGSTUL_GC
}

