sprite $image88 [236x164/16z] {
vTk7akGu3WJGeGKWJSJ-_zUEoM0PbZ8aL3VlYYFbsHt_Le10edh_-q3aJ_wxHAJbCbBaAbBaCbJaCbBaCbBaAbJaCbBaCbBa8b94BqFLPRsET5ql8HLR_-OY
3nMvY1GvlTJ0xAqYfspKPTrO1Jbl-IBzJpop55PvpacaY6siyf8pKFcJbMrE86NQHONb7DB-JMo2a9n4YbZtK5dEGKNKLFPp1ga__uwqb1DeNT8QV_o8zIHQ
sKtwWIJf4-_9uipiqWmeqfiUtvx4dQaRDK3J4igErPcP7sgVM7UipimcvSyLC6QT7-iwxcwr-PjMcr3Qpd_Bff13uTPfzyXlN6GqRGgv4gjxFJMBb6k5j2sn
phX7Vl_QjfHD8UzQrHQROe_yfMkRRGfvnshBt-Z17bb49f3ojerEgoujfdGvHLQh7v0MHziIAvKYHlR8PBVw0Md4EF6tRKli6xMFWJzWjphyFhEzl9LqJowb
v7shBTkehdssVuvFI954lfs4M7MXCUkUwoBRVEu-az-rylBbMXEQ_nirabFWkrP8TxHyYpnUAmUfaLpU_DPEklxykJAi6f4ErtfEHkmKwBVgm_GJeLep8Hc9
THuLwEMjjyR4asr1scCrNVzeQI7BOOPJ_PUtpgehpQPOHOmyMYTMXalzbxSZAnV9GhNYoMYf_nJuz0s5tcTOL4INLiZTIqjS6I3rNTw0eobSsY2RGjRkZOmU
7hIIAdz2g6CkRzng7GIkNcltRq99gxoHFIdYbLR7vOrR-NtcBvHekxyNAkzbbueu3uIfEjgMMtcZijUHltpzsjBbY5eZlM3NSe-eIjgt6dqTyRdgaBgrKleu
xpEXx1w9zwmAWsEkEXlLhpMjdRLMGLXo86TUjtNxzkLpjIzV4sG8ripaHUizugTthRqKhkrSTJIgF_PgDPNYqMwt2lbDgtNLkMbGKp5N-VedVcz5j3gqHlQy
nMzzQTHLHRSDwfep_fCSinffMzzH8LQdjRAzcK5BfJP0ogsaRTqVMFJMbMSXKJ9NHpNgouQrixAsTLzLYPLA7NDrIAFgijsmTbRMjjwhwXDVjx4EGkVgyF9j
wTRcraTes_AhAe_itcV8CLz4HvVl8_ttl4IzRUkrzYkMHRSDEdhE86Jlg8Ou2fbSLHrMTJJe-4PjKdjvtcOkhV-goigtRr0oL_sDwiUQldw7jVZQzkcRL9K-
MY9rp5Lde_groqPAhBlpvyTnwEA17_E7b2_lC6F_690XpaBsMpSBRjAsGyktj_7NbPbVwxUgTLGZntnRMigFiYuoEBo3doD7RUkqsj9bPx_TFXx9_qifizOG
GgoxRLk2mwh-_ROcikSO63GgiMf0akuMSZxIgdaEleWLikSO5pGgjqfegRQhRMN1ypn6ZkPg9HSc-cMtuRlbowsnn_AsLGTrPGTViUTTVcU5AG-pOixiMul9
NwqSJLkbiOxAjFqfdtssDyWAARSYVv3PJFzWurUEZNsZhaO-WEgbz4E2M5rMV_boQy4JDKKLRo87McC7NvZuWhlzaRPZBBcjVYdIxIK2i9R9WsM5_AnLntwR
70Zv5sQMRrcDIr_s4W8i_aVyznyYPNEL7mZvXIbKOlNF6IxjhLO3wbSYh5vjltXOsLpj6tMxvo0BEu_LNxulrbGQjfYLQeYdRQs3i8NImNs6jsrsMVtItXfY
DPHnDXxUjlf4MNNRe7Quu4RRmiOJljce6sjx9G5RhCLNoBRJeAnH-UItwBVw7ohTXKEfPdexJ4XEHNrQiTqlxE2Dwb_OXM-KBxTQn0F5w8betPqdB5JBvofl
LBvd_vfLRKVAhD19Uy3L8hdsEDgMpLLUleuzExVwvmot8WbOFE1aWFxzpnVRrbk-v55whFxovLQqQbQSY0K5hAsktszRik0UQlLBkHMq5a7zubjqP_uGBSAb
uwtca7AhQMhKQFYVefMCMqVRaaOTQlKtAhSYDGAPhPd_M8C1vMrR9OqwnEelNozMQqBrvX1g3eYO9NIo8QAk-TFATwpLFsTuZ0R5AwZfOkLv4rL2qRr2XjQ_
uDRZVB5H_LgybL3JsM9uO06lHuNi_dn6ryCi0yftNrjHogQb3TkScn4FESc1rbHSKJkC3fHoB2u3ebcqOXNLJiommgwk9Stuc5lgrsgyez2qKEQR5T_4stQy
rZzd_5e-RV5SfLqB5DQ2xyf7ysU0TaJv-gTjmiWfxRLKOHLy5x3xsYcb76krL1WRIr9fLbEygnnBcXaQbSTO5ASdH6zMFErePjNHjXCyLBSsjtlyRRx6-hZm
XYYEjfrHoh4QKQyntMTEadQfnqjwU27x3uJ3jN2b1DnjvgG89REQ4ksdvunVMvkmFCqS_bnv8PSwGVbwjHA1KrYbsQDoAs_REQNyqKQyanup1rHkvMqxmPnn
Qn5Osyiv4-l0-QF-HXslxUvq2ZInxhRj5ENBmwsXgE4maOZLqROVc3EU6ByIn0fhk5abvshEjfrWphYr4g4juM7LvdUsxGJbwzQ2YOZ1AW59wctRAQKSYrlE
qtF518gmUzlsutF6hnMqxUFT94dnkDMyRLidQ5ItjgIYDwkgFIwwthQTednvZ0RM6aBCQjezMDc_xLMTOCxiOhareNdJRLUX0cjxMV52bcMTfL5vzgr8CSjj
vkvyRMFz2_EMxpJQsgnHAyJbVWTYrbR82jZCKgxLWajjUdt8aLjHuIioLVdwbpHWFQmOjebPaKPnp9aPjHLlfGfhnDiObUompbI-F1GRGxDYobQ7TKAf_oDv
r72xvNbgsEQNyaVRDerjOM7boEfOFCohjNGxH9dTvYkk1PLQ7UKxixQqowpUhPdSzWYGIAV7Qh5MnCqQMeHOfvRwfsrj7_W8LXWuLp6hdphpjCqIOOKRZvfP
vvVwbpImjaMS4klyKl_dFwBudoJr-S4Ea4vs8q2_MZjFPIodMlvfAc_RsyofDVQludzSofzjm4VIsHGDN9WLqXDWiN9BUA2Q7jRb15G-RQNDLed4Ee5q-ATT
kSHYsbkRz5pQ793OMKyWtJjQ4Ei9jTesnwUp8aPoHYjo6Ijo6Ijo6Ijo5Ijo6Ijo6Ijo6Ijo5Ijo6Ijo6Ijo5Ijo6IlIhEUd8h1UGTgqoqUalm4
}

