sprite $image22 [154x219/16z] {
tDM7RGGn44DHPsj8GUw_MjiNYCivVTohu8CQxFuyDTS_ODke1P72QXMnAp1Tn3RLBW8C1cnhTS10FUGgu5xHK0UsQW330jWL3TWL0dR50xe8RHzr8U1WqO1T
CMxuAq8zwQXh4keXLmdO5GDrOAk0WmLni20E5e0lnKx0lKB0hcY0mz_bWWD3jDLZ2DWLtwW3MpLG1xOAETZkBqZPYBPjbozWcwf8QMqbZDMMBqXgU4_gvHh9
mhJvdtXFMhCo4vzKDhNDGJgtJ4QSpRsRsAR-pyQroJrbEzhaXvpR7_DsegIwZeC1M5wb_vUdvltVTienwS5q3e5xYBdk9KjjNyaI4jjm3TbvsDQxPjdtRMpj
GFPz6xsTofnVIBVkEfUj3njREvMjjmtNkMnzmwB_XhLzsdWftIvFi5bsOiFLDdR6eQpJo6_PwEsPxByQ2zUdst2To8A4kZvix89JcIJwMjjmdSiKm4eRlRqY
oo4u0H2hqcsupcKf1BZJcuRA1M5ZQo_B91Jtrgf8X5zhcrtdCf7gxbL2kJZTwErTMM6NAG3o2UqlqwsxtfLLXMM14o3rcdJZaU5SLeecoPtK8CdyupPw-sSo
gAQj0bg3YAX_mdRkEfSfq6LIu8xJIk2xD9vZpcLqYFArfa1os4vT7v0LOnPr4lI2vpOEqecDtZuYiw95Whgtvb4o_tfFk-iZCW2v7uTCaZzPBz3OskTaxB9W
xXwb_DKCqbqNoEW8QLG2_vcDtZuhGzfaO0d9dM0h6Q_OEDkwwpAPT59hMKBbcvN0rYwLISGc4qdwpfRIsrMoY24B7THbGH9UjNNNPRAyomn4scGYbQUsGMiN
oF9l6IpUPE6LTAD_GHPV6CUxQfqit6H99Ddp8QIrfJBvaTMJ6QHzNbPVavcpqsoXB1TzHLRezDP2j6KoXSO_oNINxUEuYqWvaIt9itedaspkBX8grybib-Nd
Cf8I0D2KQsGQHIJgcQmQgWHtqc368rdxj2nqMQsQZcJnHrPg7OtAw50iadLHYVSoVPGPhFOZkynLbOjafIAVoBOReGmPQBf6PbLpHzWJMUaovP2vMyKAMJLq
MSo6NQQFijnbjNQPTPb2SRtCYcwocdDwAbFhCcmoTpDUB2i6R3AudiXuBwDMkrXMYzrap6_9GBKFoyeaWmrPuP3LbsNkryfAnIQJK3P0hD3mHndjSbdTPL0R
iXX31nJBwKsPNoG3Dbd61WhLMOvaqOWki-KoSzjanRtUoz8iqs_8s34XA2TP_DV8H7B-TyLCTvcMECbmBBCBP2cCKCoo2DjasVKb6IwGHUa2oNcIIHsWufvU
aC6kaudCCf53MTJVChjO5kvbuK-oa8fzHPO1n7jPn8zi_1boMYcBUSXYVf19qRZBmf2XBfMLcWOWv4dMZuSoNIHBckCEU4sMiKGMihF6zsGsoVGgMNB7UpB5
6bbKjqsLuqtJZyzajIwIrLB29YlvHYtfgSomHXPIlVNFVjnazL2MLySit029ZaqciKooy2XJMoo3-q046R8IuZTbiOGXYmb35ZGDcLewbjKbikJ8GrPokSdo
aDK_oR125fLER9AG7cGIuw6ibejbXYG90EXbUfIDSSXo28SouxKo09Qoyr6MGWb3fXg_8CDO1dTlhSiqxxAVFAkp3Bza-daPvqy9T1HeQPQL6kwRQ9bbTetC
xsX6Jv8KT9OkavA6B7ROaAK36QwH-PtDB4OG0Es6638jaopR8fdp_xQQw0HzbbMTPAdO2fdH_M5BlRKkgnftMPrb4iSBQtgfB4RpoMPWyoupPysRB2IPPFrl
WKmaOTvICwea0-cubUCNP6ECBOzRccLK0iERClsSZAZZqoApBSETTE-oy2ZBSSYYpJ9-M0OK4J7EDeDxQrsMMOSjxhAKooQJCidiyp9O3WhwR0FSFKYeTCol
qse9byl-upzP3u0FD0CbsNO_tilejaxMru5DfMwNimoE1Rk91zg3JPLEjdOlImM8em8Moe11cqgXFSfA_OBiADteiooa7BgiSftis6R6S2_RfqZrvR9Ecstf
I5PNo4xJhOQmosg-oO9rcQwJ7OSDPPVjutY8W7z3XiBVMveaAEZKCRXzHsOIweDDOmetzYOhzXKPWaZKntIBx5B_gimjZrU6ZiPnYaWs_P9i_tojFzZ0yKML
whxBRBKCg542-60p418Ld6MwL0Oh4U2lPbf42V1UPejbW1qsXQoT-YF3vsNacMoiuv7tIfaxpsN73GkyMEREKzdnM0bUB3ksqS-RAKrvcGmyf0tPcOrErGjh
yzX6Fv-FwEuqxRB_DM-lkMt4G0o0-svDIjdxtxOBTKsm4GB2q6WHvl5tFunceabYRv79Dij2sK1oa3R9z0WYoaP6YKWyG5wsf-nFiQmHC5gK_HhlDI81NZbf
rR9XuJGAIJPsDwSzVl-gbGtBe3L0jYJ3B-rkibN_7_rfWPMDYBA7TZUpdNE0EjaX2awPoXPb_tQt7-0xMw7iCCl3ZZJ9nkxsGp_Tg9J9pb0sRpT6cIz8GBrC
DhKRa6KU7Mcbh1zNhDrQqyEop6sGZ5nrTSdCngQ7CSWKEzBXuYAi6SpRpUiGP0faWqwpec1kaqosBFCZNU-pOywRMK0zBCfaqmIKmPGc2wWwCCaKBChwx9hR
3VFgbcMFLTb7AXsfAWN8ja-cncz724nc5zPMMTT41fiiVYbibCcLuvU2R2YNoVMMIOgN3Hg53RB-mKIcKHWeW6gtGfckefS3dmGTAKfbFRjoksaTpx9QLswt
1hLRa5MwiWrir8M5TLbVXFaEWjCZswfChegowV4ZMApPKHAuXO1iGHOALcqZlDrUbuMhUsLAlTtmyducLxaDbmQOQ5dMjOILsuIXjrkM2NPiYibQcsoIRM-m
V2ayRK5MNQzyAJIgtOAig_FtswvbtATKifiFqgCTvDHHDid23hOrJJRRGGPiblNWsjfk05mMTehTmVodhLcsk_7poZk-ItPplV9-XFzb_GvO_WrhbWNNNLCw
ouBhvdPpsOs0R9CiJUJzDhQBTZyWsNH5VghWAJi-NnhBN7y1
}

