sprite $image7 [148x95/16z] {
pPYBTkCW34G1yx16ylz_xhxNBRCb9rqQmVs2ETPSYIHC4giSOI-oGAIbi0_72Va1fCQm1x79No0vx40Ho1iuZot6reEsTe2fGOI1b7MfOfMFmPaN-Zy2BUrG
9AR6zKLY86ML_yoYlP1vRAjhnMCRm-V6t_zngkpj_qIjdFmVrsfraTpEJIJ_Fpt0xEE__m1vRFFKwE-_txcPAD9WBxZuFryh_oBnkN7mt_7SP4xaK2ldiN6j
tFoVFpVp_lkS6_RVUO3-HM9GutD5WlW1AJF---w5SP6MrofMo29gTF1_vjoCnxQ-Lkp_3hLIo7ButAZkaIftcJZL-bhfBx13gXgxJBf9hRfCkmmmtvasIjNI
dMcVMacDsWFPWEDKsokLMWWPQliC47RPxuS1VQgbYSp-Fg3kLBOk5VIwx0VtxmDRNdQrotuH_d9GAc31s2XJY5cfxBw9xaZMlykr1vvZkxb2HnJULlw9BWr4
fbI0Iv5kBglXNwhhje9UtKSwO_Y8L9MsbTlOS0IYsmlsFXHSngObF20U3WE4TMEp5iDZKYhQWHUFJL9uWjHKLGgbUf7_EJp98QPD1RGNNFmVKs1MwzqjEFe_
9bOrHG6bSl5_J3fL6o2KoiF_nxMoLeosbOl_Zsi5BVIfVFmV4viQ3N2-I3bCaawpCzDxmSd_CHa6hUUTojF_CLNjFFK6_ryayd-kLZP-iZ_lVmvV2ZqOWC_x
NyENKs2VUV1Xpl_dpqq7lkQGpEy5IlMa_oMyZWWrLHlKQkH_Y-6b5921yuTadjZmS80mVaXwm7_n0VE7P9x2NSV7_fyf-14B3t3WlokfAarmuByhIVfGnW_9
1V0_n-J_Cjxl1V9_7Uaj5Vc_alntBppna7JV2-J_ObA6gPB_opcWolwlfogc_VyE
}

