sprite $image354 [179x274/16z] {
xDe9Ybj138HXTbibjUV-fytYHDcg2Mz6Z5mDgWEOZ-P_6_YjVR1lUpjfzdCdWNCu2PoxouDX_mvdYVNHX5Ml0_QVwHyn3-f7h8-sQtFP4zPFsjurVJ0FMc1z
zCC-EFtBZWS5i3xQhJeyz2yxtb7Wd01OCcaOJHnjdp01iD11tuqcZhPFNGDO7Wrh61h0kcXhdFuHyt0Ss4Ew2Px7McSTSQnL8ri_k4Q-jqUyYAn-nBc3mBaZ
mBvMZVnuKSIvWvh87G2kaM_z4VE48pQFjPjs4pKo59fuJXKS2UJ9Dy4J1TV8hX9nJl2peqY6K1Cv-OXvyZSsdlJJUJ_v9dWYdw9h5ScQ4UVac-2T1cOoX2FE
2KHS8Zy0uIQOR6Pm1oIRO78suTy6oIQOd3-5H8irmMJ0_aG3kk0a_tcoUABL8cPoAgaEeOYPp6Yv9fYS3MSTW1gOoPoqL1DC_kGw25mdv-Y6rz14aSnreE76
LYHp7G8HCxc8hZTH9_CDJmFCv7hIt4GZcUiG01EvYkOc-iZrfFF6ra_cf0jDT96vZXSqmMG01NGBc4yvqSMaC-8ESg9BIMV4NMGlrv5Dz90JHUZhhwK9RYKd
-deTe8ZxoPp7zJeyLZ-va7GsqKsE-6ZIsKG_UIKQxqkQccWahnNlJvh0hUJ8AYuahK4EF1MudZHYlOPCHtUn3iHQBoOx4dsjZhLUHgP6hw53WPneIbgPl4zQ
cxnFMfxCTG3Yv3rQdBnFMfkyJrgUp7TfWpXvdxGuUP-qDdcVj3nv_mnFScYIztKygUwYv7qTiG86LVB-jHI646sPwyYaHIy_Hlznor0dPz99Njha7FJ9FEYJ
UGUI_Mpoa8Syv24FUSX37lAGGuiyv24FUSX37lAGXppa8GyvLCb37lAGXnnn63aSvd4GEV9V-t4AsM6M_z8-Wnm_j8HM9hidckhG9ISQzaIVGNRyYGvzydEK
j3wPajOcHxXJqjhajGAPDDMXIlRR7PIqXpRvThDTqjBaHDCDJvVyt2vfSV8-QMtor-RkG-Tn78W1y7N7rCX-_wUz8kmH3c4b7645URRzBSct0u9E0U9ifDUJ
yv5UJsOwyf4-5vA9zjF17IivffC_HzfwAqULn7mo1qQa2UwI0pjca_lfKBI2bSnB0_F9H9SlBQrW9VF2aydzI1ldLH6oe2UJZMEuW8MiwPXF_duCZ_ChEI8k
_-FPvA_7SB5so0MIZjda_Z5yXqDkL45F83kHRlE7GMQE9HspoHffeWroWQ8daDr8euH3PYGq7VF96kaIHib56EYPPAO3A17L8TU04Uc9PAAZUkG2pJ4_d4tM
TDG4cLBzS3gPypB85Xfu95bph1y-Znn1NYSTpoFNy28T3VC8Si4E9zBHBCl8Vexv8GjyFLbv_NIq0dy0MNZz3zlW6Lasq5p_ene3toDTuYcD4G2CHJ-kCOnq
H9Ci9njzp0zRWIV8WGnvJv4Bl6hUzmmviE-l6MIYhPP3X4Vc9Lupo15kDIFJ64JF8DS2Bz9HIVRC1TQYyy60a-CcRXABpBSGzT1vijLoB72I_KNlURAQnz3i
vpe1BUHHjAIZhJf1hgKOaNR9vqWreqHDa7ap4ccVh9EgvcnZy8PHD1rvydYae_M0ITPR8Tedvz6Q3Zvt7XcmcGwVVCA8TFg1rD5PZHp3i-HyEjeuZN5xAxYY
q-HnDDWO-PEEGWelHzQ16Mbf31iCFjALI9laV4lx3wIY2sxa28dqC5dHmm-aUgS49rdGUN8UpNxEPO9aHRyCic_M7EjJB_wfVfMiaVR9VgIl7zOEkG7HMR6G
9Hq-EP-E_bClzEcLuPPSgw0jSXxTRmnkLD6NH0cvIZeSShxmU8858Kilx91hmYsv0e8soFb5Hm6Wv9kJ4Ulru8PScBSVttR8UNJxgv4r4pfgvaCQPhbz0P3i
kMJ_6AvFlHmYTj4reE-Px97paKPvQuoFvuN7JJg8nivXf2_aupX-2beVI7qzfVRHGLDCD8VaDcDe5PDidGISANjF1yNlPWb67MGVzwzXtnpT_7Je86e8cJEa
Bagk25rn9XsTyvDToRArSJJ9_3hWeCzFQF1AIHPnGuz5ckJEuJYH3l1Rk6wXaGKyReuEMNQMYpJ1b1K1YpavxBYJyoe-chr5z2KJnemMNjm_fG833VpOLcMZ
4Jo1p8bUolrq11STFEJF8VS72JGxwtyo8pgPh5C6qBMHHJoVh6XuQAe9TidB5etJ72svbUZNUd4-7Ol5d2E9zi7rd3QHI4TnmRBYfP6sm29U7Mcith2YTsTM
W_F7S5Ivw5z_RTlsroy6U4qwKEexUUCG_2mqv4cMNxQDyzhc4_E5LwA-aRVBx2WnqPOlF7qCfU8z-Atdf8DYkluY-2NVMeJkWOE5Hl5Ubucry5JS2J9K_8H8
eroUwTLObDLYlOUdA-Q8E5PoTT6uHxsdOYrMqT51iIkMhrZHKhY2BWG_21qVK7zjyOHCg3d6KVy
}

