sprite $image327 [346x417/16z] {
xDq9Sjiu44PXpOH4lnzKEVU_xOWJbQ049Oa0r8QDuDMIVVlIrIQrm3zdirbJyMT34rQACMxNOeo2ohcTwLvrEsTjKUcdBDFhQAVakjrOCznDXNCxYrpBfZMR
NAwTfbh1Wetd0wbqR2UijlEXDhdGJjX46wRTaHqRpmKTdzeviZeNfPUoCqkheA2DLxIpj0kAYXwoSnViwQdiB5t8EWpjNBAmbSjkJsMdguVi31naPn_WAJiN
GUj7C4tA9wujLrrnOjv7tbQt3FHOThggRcZrX-miaCdMqCOhx5LsPcJfIXkBOPFi3FAKQ8jXCzdfciaMFLjpWzrbPv5diWLZ6mLxocMdQovxU6mtaM0rPU6O
B2XkB-OrmKvPuvZiSzmjiOAaAGiKoAQNTbswabwA4Z1bx-Euh9a1kHzvKnRAPFTusPI52ja7lkaxfopKoeQKPTnJbcRPr9JDNBrbzRUv2dVPQp07rakMwUeb
2zFLHVOliOtqaOKvi5woJ5S7sS5jHMzPc0Fh9OjDLoTP-9YkJh8mNRraOS9woS9qzPBbDEApihglbooCDh3AwoJBkAufNzdHS3aEAxd90eFPVXJ1Icwoez5I
22jraoL-TrVqF2_PWMoj0BQ3xFUzkeKwMVMKXUF_h6wktrGM5VwBJXrSlwSiMFcjUGVOxoURGt6WpgxzPSjjyzT1d_ylVnLqJzV-LrsbwvPRE-evQ-Vz75in
YkmETUB80PTRnF-2-0bFxtkmXXIFllKCkS6cAcdvQh9fNf_Rkcw4g6PQlexiLpeuj82fqBLTrWqs5Tre2wdAN3l9Ai5rf8tbOvW2N6NzOHDjy9HDqL1tsUty
9SvarOE-hspy8cU3wM7VL5PfPFiEhPxKNTOyjsmg-iYwqXejifZVCl1V1vAdRGWjibOZktqTMK_Ri50lInXRLcsoWMhP40RT1gaMsINKojfQ9QjQMNMGbHfa
5wkJjJN9Egy3TPILwcKNgv6rjLnMBNSAYfraLI-xX7BPiDRAbW-jEijArRBBQcMoXBLALWq7X_QKbIfbV_nOWXsHJQuDieMq6swodhPsbTrjZyhQkYnNMKfb
LVl8jnnaVMdNg-pU6bxBsZxbhRBbpzR8HTRLDYJPIyiQdibQM9VbJjQgPI5k9R0-igwsTYVxxwNBvAwPx4trOdyd6sYGHV6eA_AHTQODTxAtTi3rLs6zbCRw
NjOQP0-yaaDSavUii-sQoVvptqqxamqqo1Qy-aXkiiwsjZwGFPrE2JUN3JJ8Fdl5N9I0_hBjjbOb6zgVmE1v_hBkjhQMomQQPVVwolhJ4afa4soxR0QSVgod
BBO7xRROKYAxci_JcPRgAOkblmhjjc4vAhkQwnF5tMK9b-oDjBRRlfPT0mmjIzYpOxIYO6wVoQPvxI7xuIsROEzbqJji2UkF1xA9jPEim5zM8PT5xx75mhhF
xaxxotNVhi58TPD5thBaiasqUNV_vlIlx2yByfKDkUm1Mk6Ulonuol905hrg15dmaxKIMGobXf25JvSbTmrc8Q3K4BBW8nkEomQJX8DjRrcwozv6LtUD80kV
A9lJ4j86CQM6aCNwoofV2IF8GbzPFzl-il1fiZoKpLU2Hf25TyfQdMnkEuGiT9HrNGdzPNcRB0so4i5GQWHPU9EiMcJpTJk2BFOUMMkJbIoWr0Yoy1PPscJp
cx8HPA5TLh9MMUbtMeqW2-sojCigeFk6aALPLbPn3_RgnqQGXLPPscLbfZyQGHRQP6NjiWhA6a4MccHbkIoeJ1Pb3I5BawoiMTPCoXj0zfXjV0oJoQfC5hlz
5w6xHf25feNm5bapSBZVzPJrNmdyBgigsP3kTrC3o1x3vPKj8BN8Yk1Xwo_RlcxZ8nv8hWsosMC96a4MjRzZeLrMiZPRVrctiVMM5Hxhrb-s_NEGu2oRF-EW
0MGFpgstRBuIHf353jXwoYRR0OvaBVySnqHdsNpTZY0BIyFSjidwhrltWqFRrwszJJRz5FTrQ-PmSAZ_kcsNTL-tvd1mgCVOVZZ8MlgwmmslBUPvS6ZxHxBK
ssN_O-zEb1ldSI00WoS0Pclo_c-xQxNaM0uzfWoAdFAw_sFk8r_9BL2IcKoUpwlR79EyB9iJIvzyjwHqboKAt5AtupSEXUm8MgIlh0GYSb5KCq3xNL-4RCol
oNA2x4ZQFxraaUmljbaJKUvTjpc2zhWi9yYEeqLA9raaEIBoxCbrhbl8ndHOLdA2x7ZQhh8gaOZ84UNETSiHERvnw1HPfAjiPa-NUFi4Lj_UCXas3XrEA_ra
cGBdnRRpTCi9iejjesnECSwJHKhf9aiK6NLhci3wRnmwdXRfA4ikyrAtKJekUFEDhB_WPiF6eQDaaNwoH1vrwrB7IaWtifU4-7ZZq63PEBG_hVIHzKiN1Cvk
8UvcotUoI03VcXW3ifVbYR98wI8hwsgCuq8ilUestyiwmyQX8sLXQv2La9Mn2iiUTGlYNhSSKaNMi76e8VhzGWooxje1hEkNx37Rzgc4T5pM1DlxxNdbTLcY
QmV8ycMw4BjkjtDIF2eBsFcoY4MMN487965F55Gb-itFNhSvjieQOVlB8ZjPFY2BUM2hsKLM5QA1V8UwvNH4Dh7yOx9o8vjTRfRrievSonSEiciIKUfHjnmR
PUsk_MNbLZOGSREiAj-CN3jPzUJalcxLOFj4rkxQNrP4vCecy6cMZTSky7U_CYy7RJOlUD49VvUD-KnN_NhHTISRYIWVaFNajz4h-vsi1d8YvBiyluWjRwko
O3tJzUiLMP6zh10HwI5Pef3ZMhTHxmvQMRw_puANEQSGlB-ohf_YHSwCbgyNPF-8tCl6YuGaQPVTZrvw6qTEKCCThoyoS_E-eVOiheTbHNx9yiM9cIZo4LaY
jzMjtYGHRIjVSzsE3ue0UTbrbOLJWA_FqYYxNld-VG5SlCy_zo5DTJi-A8BZiYmrsNWXpOiiPgacsQmI22jTecsANNxjoiSE5yOj2zxnWUjHMP6Qx09335dW
XYnFPIcgub8CLhZhD1i4P1TOz_l2E1lsJ1XO1CXBh0YEh1zP9ybVUUCcgxzbUJFBH4uqGHRYIN0FCX25x52tjeN3U5VaPLV8qgsi0WtXJPRbjaN9BzgeKV4x
sUmXoKGk1g8elsiuYnfiXnHikwpAGra9Tx8N9eT5AsJlwe23ltcS8xYTh4fQIfk9Y1RJWDy__UsAyBzsmBRB2bANpPwolvEDoZc68AkitirBYWZGhhA8UCZk
u_-wQSA_vDek-oN8GraHtSdcYom2MRo2Qs7_MrOZPcCV7iaAwwzCBuB3ibdacQpgLPQaAlkOLfDx91ksnbuM-JlCh9NCdRGEoueSatMf8WlQ1xOIgxAOoj8Y
oq_tK46c5q6xhCX1MInOmRINnUAq5icwbmshBBaaE6e3DydgNDTsMP6ZieWZyXNPHxRiKarsYNT47W-9FvD5vXLikwp82x8k1uXKPUkL88wyhyZw25t6Qe4h
ijDjuNf8LkGrsMsXaAgoTLjFH1NPi5rN44sEA3N88kEBe5rMv7NPwscd8bkl15veuxqiJePOaiKZiZhOjLrMn2Oh3WUXL6Hh5rMmqkNVFUjv-wr2iomokGZg
iYmsMNmBbL2JhLS2isv9T7C6M_-Z0xB8n0EsBYk8JJQGmyFo0R8rMwxZhBV9yyqQZDaVb4MckY8LLwiiiKfovEkoZoUmJ4XOPkBiLjBiNf3LAPDMNLOiidAL
tTv39m6ozGZNVDn6InHkJeRng2mol63hiY8TP4LoyB4oTJNLBIw49ub4a3rm1gjdP17KPLMaXooX9S6oassjsyW2q4ss_GnMpvmYGE1gbfL0Qx8ZLv5jhrlb
7radsLbaTKuHG5QaXwowgsmaaefiQzsYOFqcgnejigeJN14no-9IODv6K9y1KP5jhDi5qujgM6GrccHLHnVi6hNBgh8k394N1KUXBjjU2H7tR7FWQ9VLmGMx
HbMjieWaNL_1daZgikssSLqXYtVP98iCBe9DLYsobOx4PCyrsVQwpGvNkYBAso2BZ2m2H9VqayKGwbKfDyjY0glUVypeRpR98YDT8OjqaaL54h6GuwfiUoNW
COxaEydgi290z9fEihB81YPoa6stbLhRaayXgrKMCRXQPBMFh3hd0xb0v2ko1-iM2v30dMHrJ14WUfikiimgT4bibQq_48Ummpt6Fh9gcBHCigfcMGGFrUva
RNLBt4TMHnG1elVf8gkUoCagQww4I4HwJLPJ34LWbDKkik9TqhsiPG8BiPki6bmDieXT5bbbUrI2zfDLGn5OP953ij9P5hOpPE5wcYpIB2lUfTwogDkpPDLI
17PPRPLLJqwwow9k1yjg-HeXgzeecubYVrbKmZcoQYW2iopI98iBr2AzPM5xYgmQYy0kgqsoJ1GrkTHT5hSS1iZ2TPWiybmM1sqYyjnT5dLxhYmATgmiyboM
YI8xWcrVMLH2Trar5gnT5dacgvxSzNdNphAmbHDb5H1JPFMPR2B7rpTzTfT5tPuXYoAO9OiybbqaHI6Cj-9tbqNTdY4Brrcoo2FPHHAusP73bUhUigZRZh9Q
THqlYzHbjmUye-U4ToBZIhLTjhxWbMwo2e6viaXL5YSkrKWKBhIyldU-kopg5hpse63doswfoAudhlLk896BsEN02sIxHfZxm1fS-yiYlsLnueBiRH9aXyGE
ErzMAxAwodfdaFt8gZwKJHA1wftpWJ-on_D0rZDAboBQy2FxGggoH56OrjN2H_PbMgt8aWlR5Z3yaRLaBniy3bZKRUmc-v5Ds1BTeMwTz9Bzo0PH3klXwZhA
VcI9aZBgDdQG_SXAlCfYBmq7NPliHrQIfrNM4tGbscK_if6Gl9p10aYLWrNs8vi9SO4eNU_OsCzW7rdr5ycVTyTkQp2px4UMGrRLj9VjqBCVsJNXHzPBw2Vx
aHN_8wkQVI_PZwoo8vTLPP7jTWRxo0AJWgZumApgEyb-P46BmvOfSZ_PZoowbeAeEdBKIVOZY-32RF_Pu2ExVLArw3hBVcItJvKGWy_wrhAbb86oIAJtlmzM
YkfuMPNLblbydp9U5gx3PH7si1rnv9Mnid2T9ekwTKDalqeP8BjpdIQBH1VFbqNA85cuJfTLuJ6oi1qYMrGdoo8oIlPu9HIpw_lBldRO5glh-yk-Q5kihkyl
ss9hbotb-EzHtaSM16RPkkl_jInIUikM5t-FxxUI1KLFsLBq8tl4jXXSMsM_taYslMvBgwj1zlljPA5Yb8NhHxOgOvCjgbRPx_UHRJ_eIeEhNVRxRMJRROl9
zIFxsBQqkDfblzz5jjsfc5pRPR_VGTQ-veThDrdaRMLXQrYzMMNb3MIjrrPBqRwoo9ztbQtRbgfhTrdaDDdylyWqsRfSQNAroo8doJ9Zkwr9idMzqkXgbqLE
aSsLtGt7oqAmuGvQVrcad2CBMvaXMxSjxQvsMQIS9gkIiuoNhLT2EU9gbqLEartgThRiQbbsi0DaaNAIBEfsiYmunyiYvIHPsCfSMNG2lX0H6ISBstAIBEfs
jYnSLP1XiaX_sVwLKEoko31Pf7IMxMzRUhWYmsH1UvgiIfUwBLrSaM6oI0TPoGtR-PjaxQx8C5caesp_IYZTN95HiaZiAjjt0YiTNP5HiiXfifZ0HiggFCim
MKHB5rcEKglROR8gBHacYvGkiaInQzsMtgx8C5dGbYwov7B72QnqTqM6oI9sMKrk_JmMAQOU4rWvmHKP9eiKgwpApyxAgRLkxR95NiWeMKGiieXW4xf0Jknr
MqvoHSoo9jii1sIHlDWIHNlT5iC0sv11ilK9ZFDHMKcIw19NdMxxoXQnPOnilMwp79Jbw-TT26ATmCgPheX1raWh-RWi-SoeMxNPbhuzK8z1rcRBV5oMA71o
5s8sLK8vsHKP9ejKghPL5ebR9HYkBvRJNH63h95MZibwZ0SP6zcdr-ks3715fiZY1TmcAukiOrcxO2NMcktBiYedP8OiR5bQP5qKSKiLR5rWgjjYSBNRVfqf
Ar8xo1xB4hcqTO3WouNOltOxfunoHSRAYjIMK8zbYNpEVlb2yALoWEpnIYZZN96niYAL5_1ZMOnS-48Ybc8vwfASZrL26UYAZ9JTs_9JsQK38aTy0Tardfpe
4Tior1KPAyiYbHTmNLRvTkJQoJ9Hg5L2WsoHSHagoypokswvAglhF92JkvFLG2HwmBOCTqN6oZBlNy2FPGEw07MxasL7GJKsLq8PxueCbkNxkirIbxsENf73
JbOZ4QkZLji2rnaP9uliwfPPwx8_evVBEUu4YO9Y8_QMIYXOo4w9bg6o-QPkGL6JtOzUUfj0hlhzzSiJS9q5ErOsmnPvBEjlHo_PNw-9AgZXbagOvGgyiR8v
ytFPxSetX_iBu3woggu_BCyVg9bql8wNHNOYDTcacXpgrj4snSORONPO2EjTfjF2TPRitfQvTWRZzJNFIpcWOrT9oSeNxchTLcQ4uQvJPJDBfGuWgz71JDn5
DkEOlOehaykHoEUrXfy_uJ3KTQOimfM3rY-okjQh-9si14ZonJqG1ScL-v0iysZXEbKMaT_bcDnDZpgtarrFN9dfagM6FGQqXiToHhhEbyqizLCwZ8deHXO9
aDt7xPjMwnauQCsNpSoFRq9AhCX6o7guh_6D3pmDS1qXMvxAWbOUB_mvF9HTtId4cB8qokeOr_d7B6HX-s3XdrrTbZmc1wAeo5DPPA3hV5dGrcqbQLsMA42M
N6wLHGQwpfTzN0b2GUgo60uYxfctoY831zZviYmFR1sHh_LinW6xrcq-9Ai3NUVBijGh8H1HJNQxhi3A_f0iCj9rlgn8PGAJU06Czx8KP3k3IJeeYunqdIyh
Mga42KJyIvPSL8UwzGso_MqDhiDbzxPQ2mVQdy4IT5-IrP6kysNbBxUrCaetCP6F85L9xYLPPB3hVDdwOs1CYCj4_dhXIpaSahNRga5pkcnz0biiFVxTf5tI
P95L7UawNxPU2Kmky0KIijOps9QHhlDbwxPOgeKRsNZW36QtrVBr1hAbFBe69kv7LZaOPP61hlDb5QdOiYCdaCMtxB8wq7M-x7TvD85bNE6AZaHLerKM6USw
N_Rx--l1WqKPAruE4hagszaMhkyZUqcfLm9lJyrvYg67B3BETRxiTwo-amPtSJrci7woEiOLi3DbaVg2Tzsz8xjkiiWOr_coI2crkiNZ7Z4w8gxAsctrwxJy
PxeiKf_0s2-swR_jtOSA8piCXU5xjrYo6NBU_sctby4RHPPRslcfeHa-WgRFE5ThmiLTu-51PA5Nn-tl6nRZigeYgjaewXeF3oCBY3LkQzkKtKH-BMpZbZsk
zvSzxu5T6RV_VGx8wcbXotQVwtxPOhxzfnwtwVnieo-hzS9RPOzXM9H1MUDx0rT7mkTFxTD0_rrufomcD2WB8_DoJgFijOMtoG9tboqPLjNbdA2iN5ruZ-o1
EPKHsNm1NDia6fPDTvCzCAqXMToi62F1bLLZuVMocDc0BBoCyukUh5WBBvO5daBMFB_eowRxo69stR800hOoGLRNoHvOKASislfKxO7vide7MQmfzyYYkLoD
smUKnRB2iWeZVm-iNxQctJm8-ca3ieXMZOH7aiNgsl-p6HrTJhRUgyLtoc93dxHDzZzqTRf_KIJfWyXYKtfRLbNBX9TRgeZcMyacsGDRIxRiX7C_sMg_x87z
LROsQrosoLPjMPqcU-0PisNRR1jbwLh9-hQoMXPuJLcVTksSLRoih8XZAojbWLUMTMorLPQkjQndAusoTArbNLjP8ejtaHN9Ljfm5f6kjcnAQjAsoDBLbhLj
LMPU1ojuFzaaQj5Eaps0TvHDvZrAi-ut0DvKrhPLvxukkdgozhXLDM4p1q6JR9Bi5vS5A1ktRVs_KZQ9JfKje6oVRMGGK3P26tAbRC0sD60f6x2Dm58sGXjt
fQneYssNAsMrJrRXHLdL3bduKTQdxNEbh6yxC60fgysoM1DbiIJAOcQKBRy7x84LKRPW9CeMQnXWCCeYLvL9hfG5IWLxJ8AbB722BJCF3IYBov_VSrqf2tog
tmt49iZEZx8bOqcKpR1Z8xAuMvGbRLpMXsNQALlWnFfauSTIXonQOXALLGJYH6YMpGZ4f5aMiTYbJROW7akkBBfZsPJ5e_GL
}

