sprite $image147 [159x204/16z] {
nDE50S9G40DGF8BS_jDY0q3x9NqBdAPwsFg7hBoJLdAbMCrgCdLpJKADyWYjhHqpUzj-Xvh6oPZciwm0LYE5C73MR4gWh5f5UGtDHRcXkoJFRewuV06SrA0Q
ySMAcIqygiCm-AQMlFMy_zkUcO4c3e6q_8lkMFFLZcnJ26WUcPdXfW3uwplmF_kMAD1uJaedyAjy_hsumV9vBQVehnLf_nOSu_b6gSBVuJljSwA9r0MSvlE3
qi1VIF1aGAf7vB_5CoFSI6261FDvGwdh5AkownsVTObwNY_ZElgHYEbwjDLKFNAyGbpjMO1gtWHRyrc9RoFXt0bLR0G8sqEkBIO0nnly64025bCGkCwlJNXR
FZTvH9us4_IGrwYepWmv1t3sUjizxhH1wwy9ORF3Fsq7dFAjuaTQMuW3YE-t4HhZVcYh4SiPoqRfTN53HqoMNuF5zWam5Usm2hT-jk_jZahFPngZ0W8zLIEI
kW2a55pRn2jzfnmJW0rmeaNsCcA4cn8ZEFTdeZZJ0FkWUy5RbRg0PkMMqCYfoX0iGAyjSRDIB-W40EIoLLIfwui5OGfuNbSXONzhL97XDEjiack-4qDksdDK
RnfBNUgZh6kFPTkjB8eDKIUAhUeVB_5i5kVNd_Bgelqe-Acp1GNezoYpnqzbV9Oswnelyx1WR81078vDHVCPnRnMbfj2hBVX3fTEG4IkyEma4H40j1WjwjNV
Azadk4n_3HJLinnHprBqnSI7BqUkuhitPrfRmggKw0oNNbEDAcHxF7NmEblKjqDgL3E-ZrUYsA5J1BYSGqFnq5ELT7WPLcmJ2v0gzaOVQnuU3T3Xn0ekdHgT
laIfn6gsw_f0Ix5LmB_pNQXXy1P0wT0pt6kvDD5L4VTzat0_6wHdhz_4FzajrG3l6qGgemhALUH4ytBm7FjVT7U8zzRXEPZgPX2HEVdH7zrkK62E71MMXpgq
IGUtFpZy06RxiGHghjOrtheiXokWH0LmXZiDzliveX4bU0XvKFEPYl73Hirn3q_q9HBe6xTlPcNES7MzMduTX-Zi9eUIDcXRpMvADwrC6B2hkOFm8O3I3qpw
2qYl_GhxJH5Awy69WhlmQL372RbgVDOkJGTeloBbRZ9ZzaMh4yqZJMfbCO6zF3DQeKEX6q3zCLeLW83N6AANCNOo1XUR4hIThMnS-Axidrrsbjj989ipP4Cx
l9jPW3pZIIrTqHwLnFmbcHbkfd8FZxwPmymZStwvYNWTGA13c8MU8uYj_y-Wq9QVuQLuK_TAXSDoG7sdRj9fEKUSNp06d01e_Wf2vWMUtyLBBpUenFEJaimx
_wNjnNMVC2_mqauIgaNcrjhsZmubf2nMDNWj5mWiiwAiWDfN5Rbogw3hG5RzTAq0UlPQzr7xXlumQnxgjOGW4BO2k_h-ptiNTZp6xtf8BvEcXgp_Du2czNuU
7nDHytys6v8FWI6tlHqVrUQ7MqiY7r-brc7VnuJBnFcLpkTabV_fEqLqWD5NwkoguxCIq_7bQXts_KN1FDy-cNA3ZkyopxSlJCbJkXZYjvW7dP_42o5yFLwV
Sl4ITFmeNkjJpSEJjSPcgN6j_C0JiWdMQGRgvMj2oFXYGf2VsZMzFbuCuVAGhZM-FiHmAVADLtIID9I2gLp35C8TPO1tIB6PfA2gFftF1pnYqxKrwqmXYuuX
LZmeOnrRfvTrMyCGQJC5bs-2-NpXeNeR4FNjTYOn9qKISv6pVQ8OP56V3Qyo6P5PpsOcsNDOr4wdy3PyFfxkeK92RpyZnlXGIz620vxbE2iH8sWaW95yZyxd
0ruk9jOfewom_zgvg5CgEOQ1HmElsWhMzAcNhh3gq_byOykfX8Nw38zHLi3ZYQT9noGyL1ow7P-FHzO0ZdjMayIyuEtSgsHYXsx3v-F9QBrHIegnu65C4y-f
lViyMDKzjLtjGMmR9UqwiIR9efaiAvvHI5hnqBcnraVd9XOSeEjvvwkTJ-_SYWDPmSmVKvG5ptfRt_x3ezsvbr-XQsw2LpmnhsmV6iTikXCMDTPOsVWqXXSy
N3CrlRmroYjbrzeh2POfcuoryNz9wrsCPSPuMSS0o9ixzzpbqkcGBvMab7Yqr4Pdsu6SJWL-gQmrShQYX5phWDUS5lvIZVCwYGktkeJi_WWWbPmB_slVFhBZ
Xe4W3AzHOVh-ftM25zG4WY2HPFFVsfBgjVBtgCBxTHkW91K6TWxKfnALeCznvZWnIKZQY-WwJdi14XEr7oOSJihB2kVhTqAeL1x619KZHXvkkoibIkCMWZhK
Xe2KwpuHe0w63G515H4uTpNgUFX2G51bh1Y9kcNRITkfzP44y74LG59dUY4WwbhSfekz8I1gcV2EWBZMkZNtvIdIgljs20YQ7Jz2GLfW7qe4n5NNIPXxGAQN
TNwpZveIZX8GffqEX_vNeWQ7EW82DJ1K4T3WWJX7GE30SQc6W8ODn4K2elh5_N5IWO2wdX2uHa18_HOI1mc8-XnJbuL43m82cqn3FmB2fOaa1X0Go8jNwqz0
E3oI16OH403otL1--XKTvAe4b8OGK5UTol4B0R6J0ENc4H3sPgvAGBm9Q2woB4r0r8LzDm6jkO-T2UWc8Cqa8Eece9k0D2gkJ40yGK1f3G9AYn0Ggma8lGc8
xGX8SmceFF0_8A3oQwmd8BOZ85KI42IbMW926m9YJmB2oWHK5Y0f4n1EOSPs5bAgySETyAUv14G2_nW1OGe1iKX0M8I0o9O6XEz7GEhGJK3JrfLbw7uAgBnk
kszr0g9cHNnp0aAQTK2-FOtVGz4Y16GlJK3MqWGaxn6GPXEGxBa4n3s7iC85EPfAG16QI4151OkmfmmaKd6S7H4wHa3KS09o_ChQYsaQ0TdnEqqYe0JjzuZV
sTK4fFh8IWAo8cUV8I1INGd8yJVv8W59gdeCI5B5lB2R_94La6j2G8wet9VZaAU07DlScu2eocARJaMYJ41KVLPypMufG8LHLUjoraB5Q_PIwrQzd_EwPUyN
7xDNkDso-sp5RfFNHIdEVySkUK0RSIZR4owdE9oiiTcFoAruGIiga-NfNudd3xGK9vFatkCS5tfO_RAjk9ebTneNRPAjjbboj4kItF1kZjRHjbjCawDJaknh
qnHzarH_HbkM6OEoRSagvtmpnV0Uj2Jd0Q-VcVRrJuAV
}

