sprite $image134 [159x219/16z] {
pDc7kkeu40FWhSJI2ExxF-qM20WS39CJRAAjj_-VorXyvzVxJF_bCFtQQGxJEVlqJRSS3dl4EINshAEE-y8T9WSw7e_xkX5EYUFnoZliSL_FELs-VmSybljz
dQFh9JvzdKSMx-iSawVlyuZ_6A4RJfYSmrzVvv6KSPnsCWNDyyP6cVOq1Nb9jQ_xc8BswVc-7eyxuWMUJi7vOVdlFtYMSJootEFcS5RZNKft7b5ywERWjjb8
fFIwkk8vy8XU74ZaKawVz9atnpZ5v1GO-3wdBhps54Iv6FFv68__MsgUiC2j1Q9yXYVpdat1Ogbz8tRPF5QyOW_Av524qti9JmrUy8f2gTuvOdN-sdetTFcl
UNFLAcNnpWL-a8_mTBiRF0UmRMw5CwzC0u00PbwS_wDgpCIpTqxmaEbwIu2hhyMBvJldMxCUk0vdddZXdPNcAPwySzMKwNEBYIRFKr0piyOvM1lcbywy2qSL
BwJgdUFqc10xNE893XtpMF6Q7qNoKp1_HO2dl91qFsQesSld-wgVJa7cTK22f-NQbJXkc89vNPiNvYtR_Z4p1TVxJcZoTENuPaXNteKCx-lYAfTF-93WgSbx
FGKt-qvubWNFtzRBjb-tmhBHXqRkZnuPD2-kl7ZTzii7sZxQ8KD1mBoGUNtQVbu7CEYDhdYiUVM-bf-TmApECK-IV3V4M-gDBMY_S_dvp8sykax3-_hZToxC
mpfUlEQnRlkUXqG-rYLJyUWwRPwd85hlt3IjyX7PtFDYJTi_pearxnozUDcu3-36urEUWfYsjVspBh3M9_4UM_6YQll6FJQRvEt0of1HjtttrHil5DlRldah
qsxxgkfq-miFol2uZJSdQfusjNtxC8AdicpxAHus9VjXX2_QVa6Vr7trOKXNFA8Orvw2utbrssUZxVVajUkqUMJnYBREldx0IF78vXSU0drIjtsPAoxgj9wt
_L2WfoyKIBLzunnA8lfbsVRrm1FDMtuKaSphbYQF5Qzg-w5pq3tv3oCa7d6AeRnuv4MZxLDwnsD77kzviMZxeLiuW6UWbcr_oPFUynXOcUrjFvOy3E5v2jBO
qAnfyvg8KASfQ1vh7iy9EMppY4vfj_qyh-F8QTVf_D6Jz0LU_kX97CdpaCxm_8C3wtJww8L_T20lVVIyjkDu-Pj1BsvlOBWXf6-6-LrpVpF8zD4B-xlxGWHM
yIY7w0xqHkUEdZJ0vpHvR6-jCvRtxbnPzzMs7spEbF4-yunBwCQldmzTGZVU9oaIkl4-j_s4RhpFRJ-lSuWl9_GotA5k_0QdnzsE5Z2MkjZD0bBBa7ivWQ4y
Jp4Os60mGjy7ica8VlqECzG8GmWr4_m6pa68b0O3yq-O50Xz2SZGou3NVoM4et4YulhlmKBRsWbmlg3A93ZG9YyRGUKIv7PQA1ElMc1sPecTQJMAEPyJgura
A9rwIm78MOFyjxtpI7OSXg7WMYyOzp_jv3pu0Q98mh_KE--wW59g9xof1P8gWtyI47GQaiI_CB4gsI5vsGGa2QYF7zC4XBvsOXi_92Pz_F1Q0c8RkzmFsa2Y
qD4Fxqb0r1wOs3dptoA8zoSWQ3NCxPWl-E06kKe20jVkDKz0I8-GfOAe9w1bWiHG0i9akO44D7k464j0E2OQCf4xdO302MwPN3q1NQr8Z2UWFEI275N3v0I4
yXJpXsDeNW82E61MIK0g9A3YCpRJ9tMiJq3u3abyfr2dSl1hQhK4T3gaOLK2gcSgS4C28e1t921jJK0YoJi1TG6j4n2UD04T_DW9w4v0l1FGdO36o1U7Em6L
OUS4nDC9wE0wEQOUO8i4HAM0w9s0ZW-HWC0T2KZFdu0mqbTojVu929CJ4DibeBm1RKX0nRw2X2TCG5gMW50oMvE0wfzLwfc0U2UW3Tm9w4v0k-2q17Gd86mQ
O1wW-YSWzqf0-WUtJa1suJCvwnEGyq5_Pty2ijmv0IcKqoC1EUn20bfTMIBKDm7P4U7tbPeD2SZn1IrEG0JoRqRcUW_hLNZiIa2AhsXP0ghb0iTtF3a1aG1E
j8puZbtPox-Mh1MWN2q_R9FnbHNp1dIgi-HsyR2x9I0vVaFL82Sd82l-n5QTwgU0wdQvttW36Yj0SaJYrmGheg-V7HbzPfSZTvbTZjlCBaVsvj4vNcMpdU8D
x8rsZqZeSeGuteNjBaTiZknzTlqMR4MHHiThZkqrSeyuX-Gkaylnr17QViGWccHeYN45idpzKXNNeIktRDkAYybAT1rF_4DqUN284yQM7SkMosA9sYpuOqtl
tAQqn2m_ecrR-RGaMuxpV0O
}

