sprite $image198 [243x171/16z] {
xTo9Sfmw48NXkuEwM-ZzdpRn_XTk3-QwQ2GaJctPcO_J4ZDAuj9Q97sVqatI_yfyRQmuptEcLUQdz5Busle2_UzXNl1h-ZyNvAB5kftFRbakujK4rsbtmUTh
ZJZS6Mx7Qd7r_ZoeGJSCndkKkiLLlJZlmMffJUp00MWT0EoR7W3iqCs80OUZfPsA0KUXsRm7gBYbwHPNyJb53r2nAxfontCybTJTnHZg6kOqZ9W5FGyZnYm3
YEjktEB4lVUSsAkhvFndbIAk54PxW8NibdFdOqtcKnzLxtUuffZH7c2iQ-pQoPNSzQxjInvX1vFno6pNmqms9OzIypmUEJboxu_cB3oYcbdC6aesgR9xtUIR
BE6xLttoJKx1ugPsx7Xp8bD3P4bB95aQV2iYSJMdfiWS4aXA4aZMbZv9GKvXOiXfQcQkDPXiqahDqueiSUVrHiqjp3Kjn3sXp22tKR9aIPX3o9BUqaZ96axE
oflE9agsU38rJpN5b1n6bdSoDLSqpvHy1fcQvnPAZYEd3tAsXBcoM2oUhFafYha1iPr1Dc4vrnGdpIUG9NyopxN5sL8msRWCvWfYNej6aONzwpcQC4zLnLcY
oCOmOJvzGSzUR19rp9c5nVmSgs2Ud9Wr5aXEbkdvtE6UaXCprnf0rlLaCr8K7L-n5riScG_AvioWpm5psvarEvwCJxCtCztnCvt4_2kG279MNtCsFG4z0Vui
pYotWC7EvgxfYWOT1rRBXDKMGiwI66rVDEWfPWrpk_tzbXn0BjnIHfiBXrGzER3cLLXhGMHeyibiaevMKp1HUo2M6B8vis_we0cdNx-8oMfp2I5pMp6x9Ns8
6kuMEDjgRx4WieaRigtnvgkex2uNxZROZPoLO3Cz-wftkZtMQHtOYTbCIqJOCJ3lHKD_mMzzaI3ljRmfrWmvfEODCsf91mIlYv-s4XFZOflcRAW3l5_TToj1
oPZT9dOiMvG_UOSuBs5apBve7_iPMvHwNVoSKV9vPiikpYsxhFAYjKosAaQSIoWPiozw6wugNzhbEVejTcl4okbcjRmlzYYPxAqOiPNGS6s73e-ffFCw9kxo
BEbJmKaH1yUlAj2dWAaOSd3CBop6EnPCz0mnoRveq05Lc_bxcvtuDBE2HXrLiA_O40S754KJ4JkeQyDBnEpiZkaPj5Uh1NZT49KJOnkd8QZDVix5wy0rn1Jj
c_QV40xWLWTJj6_QHt3lqihEuw1I8svhtV4fwIN-NRS-MsNFSG7YscQgtewuR58fk2wOwDOk6tZ-LMh6maxxy3O29jd5ZYbRd9TZheRGXCttG6wsqaWMCpld
kAyq4n7PVjZkaOk0RTWBkTXtXrxw5FTG4WxxqBOCHgobb5qdb2vGBm66p4vsU0nlOsIUr7QekBGO5T7r3duKTocarPB90KSYXRHE9lOJAiDyBJ8n2rYxJPFf
UyDksTYOEo3ta9lyptXa6OyyWFWct-G1SfE7YDxFg05oamV8JUurzpDAnojv6OyycdX8ykK9xz4Htc0BsUsMw-xNAe_Juqh-4YX2bix4JalcpQf5ha1sNoFA
aLoMhnUsN0EiwIKUl7_mXUzUG2pfFRAhOAycbvbfmhoMtLckumLCzAUl-nfQm8JjgCyioOUkUapwCZ80U1Iof8SPfc8YtO97gbb5nYABwLDa9FAB6FG8P5NC
ev5r037aJRFqJ9REnP19zs1Fbfx1n1xNNCe0P4baBcI8oPRISSoH0VTkXbnwZzgQl9J-ioBFPOW83waoIXPzYOoX_Gq
}

