sprite $image404 [179x191/16z] {
rTY5qlDM38JXSZ-j59_xlzfI4XKCpRy7Ldw7C_ICPaDkkc2lsatwrRAReEq_tGrStmmxQgiinh4PLS7-37QRSS3z0btsoEVekaVExc3s_uJwPh-VsNVXRkIz
-QiyUM--0zbHYRpzr-275VgjiV_nuBNFV7Gv_-3CLNvXNfDHWMoxhiYk9zjHLsIeoUS_X_s3C_-a8H-YaUQAv6Fq1Hbgyg4PKPgyXo3YyTd7t2Ob9mKU7vDh
_C7pY1TvCvGdknaYtkI__EN9y7YJdowK9qVczWoNv5Q8Z5IXFZd5vsQak0uvMMa-8gFL8hlZr9mdhaPsMBOdjrQFV7vev0ECUkHZDFB4rSW9p81yOIjBJlI-
hIxv75sNV8v6QVAnsL2NV8ukHERGUZ8nQIbPV-XyMCYHComqkxrZoUTep7zOI9BFqVF06NZotWptuU0lsuMD9E_H7ezulLKcFQFFkiY9HiIJF73KTXfeSfeH
yIJREvy3pj17XiUJxED-bhhzNmmvYtVZFZ_iasZo_g57XYdW39raX-q32IRC17dKTpZiMq8V-H0zIPm1VMJtpcKO4Nh8kqCZOkA5Cz3a_wBXyIta3KQ7BdAk
u_awiGacW2Qd6V6Cs0GN-iY0noi6pADviaT6R88EpfCZCWxCenUGOMF3TBAD3rF9DYLW6jccXJdaBviP9f1jTXXCjWK10ycmDM4K-SlMXI5aMnkwoROye8iC
KuGEiga2IJPX045s1m0X-fl9uN-bHtzEzdSmNI38QZH0aENh8CZwTH1aFPeWgz4WoFf94sJzEax9ZoHNGyC9idmT8CZoTH1aFPeWgz40GPPFcY3hrq6GzMY2
h4R32R9yqWHPlmw2h5y7HtP8qGHPlWw2h4O3I79zTCQH7H2RdKXiThyPcY2hqI38waatvqCLSdsqTmN8o7pGaVcW9jT7mucaaqRucB3mTxEF2el04StlWqO4
GHPE6f5FndrWcBg998UhqFn38nyQC6yJIMvU6msF7NcqsJ4DdEIsbKLxn9xyxAlaEX1nGCwYtA7XSK4MJ9e09xac6X6Nv0n59WsFAxBWq1muoVNG2JuXhp23
7l4nkHOQ7WHPiuu44sGX6X44MRWEU13asUX-S9Brw0Jpv6o96H43oGtJpV0Wo0iFpOEJl1eDOXC4UUWwm86prfQZGMo28hSst9nWXioZUJA2h0dCe3SHyKZn
MdI2kHChq8X59nxtb8RqHkEJa6DhNIqdFnujKw2v4VS7friEpbQHKon44oDMeubDgCq4M8qcHgn64rzsQhJqmXd6aXzRMn119ZxOL6XYn6hqjRYjBNh93s_B
woGtIJJvyMYgI381NZVfmmj74-TNoJxO-F_Xn0UR-j34YjLe0gn6oy3yBppYSq9zw0JdYSkZYMzdDPhuO1DF-YymiGdXeOaVG6fq9BXysqlS-leT
}

