sprite $image272 [208x208/16z] {
tD9N5SDG50F1V_lECt-sGP3UTndCaOvtDIuqnn_bvaeMWD-t94n0X0H4I424jBouLPa6W9O6MXhCDpGT4NH4Wv381sjf8CQXfO4OXvO6q-8WnNazQ7ozQN6G
-Hf0Z4ECGun3Z4ECmsfnM2qEB-0aGAH0f42aGAH08mNo--qnZnY768SOXvednY76eUQ9SOXnJCoZnRaC6d_Orfg76CV4F2vmIY3sxHNDYNPpKPWKrO7mj2H0
GkRzNtT7qbZI8FfVjixPcph2PoebTjk7ok_A3XM5IkCPS6pxymiYQKeKVbKiagKg_O4s0r3Faty39sHnvKHG2FIXGD31JOEwRNEW39w-FA_Vn9543tNYc07H
52ZE2lJxvTcog2lJ_w6ui-WklYWGmkqNkkUL6u_GpyKnyWn8gm8k8YBkn2FJwxs5y0LEuF2FONBDCqtKAyjx3C6y13nuZpgClL2lJw383t6YYBeI4Pzr_2Uv
JflcnqKrJJ7cOihzWKU1CYOA7jnxnjaXRkF3f3wLXpiHOBgf3seRYwMm_LF8fls1S1n2hZGWyF1dAyGTP6lH_wHvZe4qZZpZ_8clfHQtjxBb_iZ3SKfjQ6uy
2EkXEi2X4FX14sLjusG-55DAaR-gP7bh2bhuea3oQfVI03GFQwQ3XtFY1uvZFOQ96DfswLU9n6Wd2M7tNBJCdR8EBPG_USBCRNvAuHWflcxTXb5YPDx_IiKa
LgZCST1-pCNMedufVGwc_Q6jG292I8Hb6d0uoYCKGeo1Rjs6xedHgrCARxj8BT_mGFjMo_LIaWDfYVsX-rZlbS8BYN3cYKDv6W_5i4VsNIAGmcuL9yQengq7
IfdFVAviiLxAx2x9DXommtGPbtgUZtOdEkoMYM8CSiSZgldjWHHToNBOteecyRd4gF9ehjE8GtNXRTsEDS89HyTmQpnS_qStWS2rF5ALJhFoBa21dacBMxre
_TCqN8mCdWp33NO33zedxJIKrpmlP_51zeJUOxgKKrDdIuFgKQEEE20hFesYZf6QiW8em71NTWjqZWCAH77DmmvJ9IcbEh99ut7FJ6QUvh9S_s0qepeDBP_7
ddW42NUTRk2XwhSrpoiVEE39blpsrJppcEU80xCM29y7wmc8ck7iycQAzWb2CTpb0QlgYSSbnZwhvfdqL4SScEMXk2DFnYtrpKFNSH2OA1BHaaTKLVI3Hzki
tBnQqbCX3ehKYR39m3Dq41qyzbhnv3qKblTJEfzS9UUKSiuj3WxFv44f3HjsUQm5CYtlG33TTsP8nmAzd6UIrjlPRyGf95ekI6NWsOSq2Rluy8nCW7gMDzyH
1wBMYZlXWILyRhe3xJpfpn1lu0cKKrhUVe9sFEeZopiEahMRYEQJH8jgJYSOx3hYGCJSAjbwUj5kp8Z4dhKF8Qwhyle1AE5QdNZqFIivRY8bGyMgPEOwVGU9
bYmexeH7-yYcnlEwYcjejRpM3nvn7eGKFFEM51CAWTNqn0BMTnoKdAq5WlR8FOy6D92DJzfCdpoqJ0ClFIH9H4e9LMQ7PwH9tokxe2QZ40SYHo0K4SdvE44L
HarOyk23dIaFrR-jmZgDFFkuHnpeuHcLAe--Ah8YW_puK8z78EnxmFDP8CybvnbQFOA7uYvKvzPku4dX7GUcpJCLfaP5s3nmP2oGdk90j2jkpi2P62uw3oru
m7gbCF9engp4f7I182BUyBksP2gTi5Uj5Gl7PU1C4ewSP_iHJvpmY4Y1KKhd6T_NU7ZaAURxIf6pRS6ZK9zmM-MnFmiUlkMH6O_g4GVbv1brbOAWiQ8VAeez
v_DuuHKQRwdszr-ywOA7mXtEoqyxy1pNLVAfmLs-prK6dlve5DSxyug7FE3-IHOyztQZAvxSua3LrDbQBIo1HspWILqrKLpm340YqGFkdzBtUSRs0K_4T7lF
Q7dl0_1PnTWBOYWNZfE1n-KDb7OUNl3Sjq-Un7KN1sVFz1P2qSv27C2SE4vaW57NomCRSVqz7krvnDLAGkOyy0pADGi4c9CG7YZkCDB77OXsdh3AWpkShNUn
jBJ3LHqzq_OHwZ2B0z4-462uwP9dl_HXvtbTyzp7MpYN1Ju0GT4X4DhA8Su2eHnnuEVhYWiMw7n7tNQUFmkUxOw7KPUJf20E1iyS-nAGPt4WyXa80fYH9_iA
6xVJoNgKzKx5hEooJiLWaY6pce6AkB4-UGuRoaSW68RfnzhtUC3PcYVgToMjsKVF82fcWG1hEW-ENr_Mec-UikAXy2FX3efsmlL69MPnu3o8_gKeMtdv0a5N
FDltXTxehtevsD1ZipZmjaHnRqOhjYruw5TuC5LuJ14LXa2Onq4BkFo0HspFObtn_DnlQiCqJ_SJGo3Cua1LKDnRYT7_ouDMxmC1fIfZ84Y1CHM1yAXJhtce
yN2AFr423m81AuVI1qBjbddDRgUHooCUiX-gZ34CCdIIitHnK72lB4y6AigNF1k_UKAwSrHnQO7E_urhNCYzPO0eHo3C7nPWk4x3V_l61S-BwU5h8IzrNIr2
9XCzuc0m5-A0cWNrLZY8dAVy6NNaGFmzdaX4rKZ-zfuLaLByXRtUbaJ4zasUyZqUIE-4GAXpJoPrnhKcnQX25iG6zbvBbZosuk7NSvvrWKphtDboBK-oWgA9
8SdgtjnuvFRSKC1wzFg1WUvu7XkkUIlM6OlpfBenWuVhNZNzEi_cF7YU-yu3jvGgbT99HGlqdcgjXROPxpjCAa-qyfPHtJi_3JPEy-xbpp-prqRvyGSy-M9W
KR28o2aGVCPEO4SWk107ECse6O-gjkVJiEIvQQ1qCR0gMEg_jq3Wrl0Eu3pjXeKum6dkUNmOQPyVq8edq9g7BmPMKNMK9W-4RTlUSL25G2Yx40SBddxZSSdo
FfkTPs8fUlo1F8rZz6M1t5lE8utd28Gt7ffhpOE1cjLJ-_mjhNdMXjimnca8rKad6vCBCqOWw1W7o9cH1mCTzcD_fSB-ocIMt7Xk3QSO64DChwn5y5GS109R
ioJYm3NbQQ7TjLDuVq4tMo2y8dZY7-B8OHtOEmbOBdWoDQ7X4GWU1zXx5N1zNm9vzr6ftsVDRwXDd6Z_Ery5NEVYAwSW40XnC0G2uc1wMV08CHb8zydW-xch
6wgBhhyI9hzQ67ZHojGau44W80vcF2UFJNbo-tvk7TWkuH0kBBUXWLOyc3iQP0W4nC7G--YNWGTnmCwJRdX88kbbSYkSViTJ6Eas18AEST1Gm7BDiviiESya
u49N7mr1zb7d3NGrVoaZq5uX1auN26CST2nh7iKBINzj7N2S0wKGKuWtTzJx1h9Q1XjJl0P25mUjzQL02vxid_RYxT752xuISamKBtXUgCUQnzLWna1079pR
vPx7eyRZm7acqSKd7aefSeeSveQJ6yEjjo8G40VTVUoEHuwx3pUUl5pnv9WvffXIc4SstnXklTMq1K917AnFeZgp6ruWdN-4SF0m2mVE50Al3VST7WH2YuFq
7Hv_--1u7_QrvA78WIFBLMBdomALcNIwh1D37DpnZFjVQ9-h1gBMG2bb3XH9mVCuuUvuLFK8X1O7Ztdm7wdE63pJ9NRZ8OxCdEBriv1-ot3gUWT2CcEFWs_m
XFv7Zd_jfe4ISoAvv8bVDfnMVQmG40UFUB3Ros5_XrzdpNyoKqBw9_ZjPucWO74PUo08bjvdFU2XxdLoBE5wnSQJAEGScP5lZzSyEcNHQI0W3ZhfEjvyhOEq
HcAl2XGen7pDizqNw4pomPEPcS8Uel-a3tdmxygm6motwg2Szk6OjZ_VAn1GPaUPxXpUgCpbYpogCluW44k4-MySSvGqNR_T5mWibposvsVODcBcREMEfozv
ATpP3GatQcj0H8hdXNM1rYWuQYXGs75YUSgZhjezi1iAHDT0BaBtt4SSK4QUIO44Fq8l3tXmSds76z9jVak5vJYuukq7fVEgF2gGQToLK9rrH9xslUSjVmqq
MCDDYBYAiFj2Sc6m5G-0R0StkpbqSgssuTUQ_xLt7ZgEWq0OdWaTnfVtVzejfFmof21PHxZHVTitMChdWG4tG1TqY1Fgm5kXlf3yyhXe4vYyUybt3pSY8nm4
AM4yG2FgSAdiV3BrsG23x8FaKiO3D6e95vJ1RmRJ7tG-cGvY3WUejNpTT-NY2Ozgza8f7gJ8P5Ai98G7RFyqPrr2Ptq--kT_4nq-G86EYW2fcwzJLO3KpNUh
I-YipKUNqF_vurT6zAzNe7zz3D7X0vJe02KwG8SE41q-G4FFCrz8ahCso8eBq4cgzsYwa6KRf3ZCnxtO0e7PqXrsUTocOXPRm54SxJ5fP0U0lDG2csAem-HN
eGdNgr3ENxJYKWkWMioD8fAlxzM_BMym6qkSetF-imsGw8ALMrqoH2o_SM3ZGyf5PBU1hx6v1V1NNoRe30jPwDn877v_HEG8uzFzzRpB0OR8hRJ0is16RI1o
3mHmjo9Co062JHTOW1i-uMda0AUjuceyBrjR8b-do5vYWNJubAtdUXUavFXh1kjqtqAWRADyVW5x-CZMKGZjf5X2PXQ-P409t3pR8Uzq9WYPP_59g5OrCQDS
bMF7rC9ENWv1PmZ5PrsYHp-4UR9Sa_XSy8P0dA3pGWYrnpm9N6ZAaQ2Eaabowx0gf_oNAnju6w3KUROxtA6SQJP99oJq5pOJXD0SsXQKsw5cGeeBtPWeCgSv
mNb_32wdAjHKbj3clGo9tFV18fDqmBiHjfU-Dzq530sAkzO_pmQyEmBY8FWVr_zq0SkGfTFecOBvHf6fOcu7tAKxz3pTwXWoTfeTdF5M91XzUhnZswR1iC4M
kWCwyqDKFBTZ07B8Rljp7oWwR3FVI9Bbsqvd-E1y0PAwnPcJ2JO7Jf-Mc97CYDWuvmnJexC5TWT6dxD2108rDFs_76euyuqaUSFxeNCvS1ZwIICWENfN7sOF
MPQr0GkSQLzTwVnnH4jeW8BGjAYH0Q961kXn0PleSG4VCla6
}

