sprite $image189 [243x176/16z] {
vDE7TSHG20LHb85D_LVh-9nmjbVfp6r0cWzSLf5n9oyW8OaAbWj1XWXgn3AXWWMnqrMF2XR2JbU96h6mWWMnqnKgM18LB8uAbfqNiw8p_euLBEVBpXpY_n17
NA62vK0uueerOa45In9skd9Ki9m9ErsXHYo92XPMi22Ek4ADM18rON5KiQ229JSGJ8ZEU0rmqkVO0i9ELuaAbbobUEocMChKZL4iVyHJQsQznnAyCxFMbusE
Qh07pH3pqxTiYEMYCmflxKaxnhp6nfwqljH9V_ONqasp7h6zqenHBJBYw4saZVcqjxIPwReRFGY3nxDu0TpU_zL-Qth8DE8yeedrC_jh8u6TxQvpl6Wzy3Ys
k-hQkjxkEiPQQ1q3szXrw3HP1YmsrPVO3RtAqa9KMZKdNiHihMpFAdtPvUzmHNjSnZJr6koVwyJ-MMfpx83vyzNDfCd-NDIj45sQRqobniMzGsPPGdpyRcEL
UuplxHEDQRy7bUYqCyumru83nFL2_5hmHtz_kdoeVAtV2_CvFWiThlwTsAR0JdA-1Nt1_YTc9zSPFthjqSlTnmQ8FLwomYtmScOxgE_8Mnfy4XowYfYWZS5J
8QyQCsiXx9o_AHgn-lQiFZNOurFrZKQjUeNCOtjM6x7IDKsazUdjk7rcDl5mxi4yg_Es6kK3boPusJ2P6dRurgVfk-FMA7WxrGe_smjdOdgJgua__XknXrhP
6z-OhYTcAVYWPZrpW1F6nAoJYmPXtPou7tINxkTzfD8v8ZiVX9ivIqkoNHgUG2ypxpRqJL4jBvE7DToGjEFGpaDdZ-g2DxceYHDxpoAconVc0yvQeeKAC5TF
0yEGsXKxl0SE_yRIFPWlJ70uwqLMjYi9ZFEw2dJu7WqdfR7Jrk6kFI6RzBl9AUM08KF7TLrzyykDGtpbphsKiXz-6fOhQ4W3doAay6PsnOs973QZX_5Ax6Rw
QjlhgoDTE96qm7uaEtYOj_JWTToSXQqSE7oOe7vs-kYCNNl0LHRmIoZz0C1qOE_1mmBhUZVn10GrB7OtZLSyWTmp34wSHYufv4Cz0U608HM7yEtX7gHA2aBa
qyZ-CBHX3v37XP5Fm0OUfYMgAd_gvHwODkZME9kzA7RYGw9KuQKsDG6DrpRUe8P2MAoMvtfNBs3Oq0fLMFpvR4xL37Gbs7mm49nJqxFdC1FKmnkUSauy1Xxy
ANn-8IjZwVW723xCQKL_IufPyKfL_-opUBod2kWI3jYc8_CR7Gm6Ht0VkJzurQQ9znsqGJQdZGVr20Ou2LQ2hMb7vg7bmCqpEBERb7zvvpyo5JoeUwxOV52t
O4e_5P_eQ617vg6b1OUv7Jy-rNblFnVblZoe9RfG6uA3KHWJ0sJEqbAYCplUEkS54UZhSwSsVC0w37UEAgI97JcpqNeoLpFkBbM1H-vuZX1LVDmkelWwIeIk
QKVceMNWdwjo2xPAjlRlMqm_2d6tU2e9xCWvQ3k2itptVgHAj3acSCN6zOlwY1mkGfdOfKbcbSYrxS7xtwSIKpf8UBH33-hT33UkoxwTBY5o4jek7BWwg_SZ
OdnZBd94xK5zg0KELsLhsf6JqAe5_vDlC-O56uGRLKGzemkrPcHDOsIkOTc8hkQSbyiktAWmjU8wEKs8neIH-OqMgm6pf4RqpCWeWgEhgF4cTkGqjDhv15nx
-hYD4enMkmguK6DCxCX9QFyd_v7FCbZLBLHDd7XDVb7tATZ4939lQJ7Tj_ALppHoYP4BZ_p8y7tRsbJ2n3oo2p8tDS_dvBq_RbIiHFH_wZujMTEEd8U6_JUV
NNZKvgab2-p8UMWbUDdiyk1FKWjTqtbajtHUiBlmZOeN0CPIMYHpFhloZOflJ1Xv4JIVNVa4mus9HruCZIy6w56RlRlC8w-szB4HEbUO62Elt-YsKMeBJ8oH
rqFl7FAnriIEl1xwsaZL9IR6o4ijtGkBNDwewRN8wRzeQLqBWHrvENJR4khhQjgHbqFl6UGZsvZoqkNCrvPIMrRJZhmOkfSSyhu8sFLJ5qEVMrBN6XCxyJzw
brdUpov-r7uV-3_zMBZH-vRMkR2cNROAkb-rVQbpQjnqcPVzl6cLfNMc9GjhshNCqc9vwT_LsiTHm40KHC7xQWhopvOxtZLwA8EkFxEk93AznrS_CEWVVAh4
8Dq2V84HPz2-nA3InKnhT1_yyZiPzBa065MwM69UwLAcO-dsfyl_akvhVmW6jurcfdsb-s1mbmwKk9Zk0pQcm3eMoBIlT17iqRx4vrr0CTs14eCD2sUwY0xS
c08R5dZdoLLQbpXPQL3YF3fOOd-NDgVBUAL1flkL1k1wkeNOVxUH7uJ67qq69XmVz00uZXuuNSRD0-0uUY3JSVG0E8uU4CSth05mVD03u3XwGjm-U0ziJF5A
3qmudku1S1mz88vNUW0S7_G0E8uU0CVHQuhbNnS3uFYW1rwsukY14SVJFG2EJthWE1qt3qmuZXuGnz43uBXv01o_ImyiM_593u3Zw85Cn-_I0-3ue0V4SVG0
E9xktGL-0W
}

