sprite $image158 [176x274/16z] {
rDO7Ji1044DHUjQUA7l_qz97O7fRPByJV8sSClyK08oP0ezcX04qnjIscjOE2FSPeubZUYBUarFR0eQh671Srnb3k8zYWt0V1Lf4CPJvZ8cMSEA1dmgOWcB0
59J156oBBo3SHu4_iyNKDeF7p6aKM27ck6t4rBP5RzoSOYmt0gQmvazpWp0VnO5_n83XgYscjYtu3_CS1Lf4COJxZ0U4-upH8ee93nLpstRyudDcEGhOuIzg
lOet2FTH586WOf24hp4L0VFY4rs3Vp2ajuYaugekheZYgYwczusbjvWouse1C-P3xxx754jln8mVCnaoOpwTjSh_tLRxixFQFtYyOSyETno5bIK0IvjCkhhQ
pli_xXLcIcGm19C0SCyv-PLbHwjlMwLgcqav_q5UDiRIoYlnTMFCADmywZFocg4eMdbpnBLZp5uhBvsSZ_7vskYfyaOrrYjrcw8WxmWvgUUvKQYyWbsjswIj
lO9TfzlKORKtLSXhh6XfAs-U4FFi65FQsXlajMAi3flsHWKxTqNNmPtkiyl4cD9EUHV7Mg_eKxJoaajZhMDyHXJa3Kw8UTQAbdOX3pm_neh2abU5TcwCfMtq
nhanLd3RlQV7k4MhVaZISM6ijPu7Ha7pbQqAnL4hMiktEGyfJOhRTWdtZaBjpVBEnDXtZ36bNULr2Fn9jmLtrjPUCuzlOhndXqrxpUP3iSyjMjfFlGGhyNuh
cj9-ucNnLg5O7cibtg739ll1pNhq5p4ExXI5sfjIUF72kNktKTfll2a5EYyCAyIrddjfQs-mUAUwRPCOAxWRUKieYjUu76EkZx62-xsN7RX7U-TrmnunfhJV
UjqyUcyAmgn38wR4Z8zYBErcNZCMRn4Nh-6BRdDMO0LtAw_nHLoyRalYzb0mvSszvY5me7YtYB6qEtXBanLl2WBzq-zMj3fi9wyXL1N1yjI_Fcb6oZjw0OQg
mejNC_xi5YtjRbvJA58aedZDuzCLpRI_rqmfJi7-gN-uebC-n4imXeMdgN-melD1NZE4XXpedo9MndW_BsglcIiKYTu_bQVbPT3nNlWG2bsOLiJu1A-1gehm
ljfMhEWjl2bYZLUXA6GKBzYyeh_s1kx_7kkynZ-72arzUKL_xmsx_VltprPwnw60MrkCl_Gcl__hFdZZXKzvpS2N2vFEdeilWxxongDettkTqrx3_8M9ip7c
5rxUU-tjnZTUXhzwCNWnSM7oK0imfJh6ttXvAzY7HywBNcBAgr2aIE7zK-UlD-Kiv2PzveNxez6-zo9yqbkgjtYrFnoWl7HkqsUQxWqfDtazs7bHUzqyYbUX
W1aqNp6reZ_tHfTTvRRLwpxbDUDmOUgykgRspghRFl6c7t7NU8FJNlENK9IdmQ4Wgb1yu8LQR9qtCEs58oB5iF3wVqAJTNxOP_h1wCBxIDjveHbtQCBK3t9g
sF8sBmWKzQDBG-HDlMOSGZ5uHw5OuqrswpD0dHa-zNBIwyCjMjvQB6_ZMQ5uDTwjlGf5vLMCsxs9FpefABqxU1MAogiHjthZSIlSErKEdXkz86QzGENjKDDU
YPUz2RtszYWXADqRpLwtMIydl30mv9qKfnGjXzpR3rDM7EwfoQibZCb-G73AQ-RJNiMOxxpHZRCJ-Y-H9RvvnNmTHf_q1jmCbTTcl1fnMbXbEjdemHelmntc
DkjrN-CjVxFe_OdXWNKFRAqNvIjWbPU1PkzoFzJZVDJUMFIoyxfRuXyluRzJnoxUIAKUHdbmM_Bs_G1OUZeS4rxku4suHywbBUxfjUqURLvtYnmmeF9w-CRU
qcitUM_CuZvkMdPBNhgXytXsCuoytDQR-7ChQwBFGqzKEV-qUTKF_ipmAQzZAszvZzDxVrywM2gdYlBOrdW9fEncNdk36tdllolkaVe-AyyUZtlHtiHjyZe9
mgQyYC0MNdtwXUpwezoUyoflm0s-k_UEtyZU1wjMoMelsSb8syjxCxaKYE4_yP6N3dFivBqz-ESoBwt5ydbdv3KIyiBsyOuADjczm_vuj9tFHbxOd_dw7jun
YOn8hR-_6FUloHlUUTrszkhJxZMEl4xuw_cNxTwqgrVdTVpr6anUk05ez-PzlSvVWu_Ew_8wTPLhygRdlbw6gmaaatTq_ctpFW_nidXX_Jv-yIebRkR6PMyw
n0iTRyVxM5uGVLKiUP-7UFlZ5s1_zl7WrG_OaZSTwNL_yT8_EV_c8xtQnxDU-e8tFK_mmcQyVR-zy-P3lQghpxtF9k_DqjPU9pxmfXPlUIkvgLVxsDnjbJSt
UCcKT_1QyTewxrFU1S4-NaMvsPkEy8AOzPOHWzRepOTuORDU5Y_CsxpFtRqwvs3IYs3nNSeBQfArj_XGSa5VzAP3l3h_pdhTLHKBtdoWjuXyCW-XfqlUvuxU
FFBgU3lZDTC5v1BUyUjTrbvTGEQzwN2l-wnNxzSlvUMyLnUGDzvyiBV8tdlz_vat-CRxFC_hjLVxRJll_xp65Tvq1I_iSbuidDSlu-NmFjNUpTVRl7blhzFL
N3DUwFtw9RmmqFdBuwHNFZTUmMlcWL_l-_EluHfUexFdpNbrY2IkuJNGvGNVdNyluhLEt2CTCru5XfVmcfCGSiOBNK0kuJKZKNcjFl_QLRm6Si5xcVdAG2nv
UOwNZ1pX8o_DYLdlgVrBCeB47wztvhYaDoBHtKcClERXr_G6lOZ7NZWXhxdRPRnHn2H6NZCdvRKhUJLYZBo68HH6uzbUEdkln55TAa2OlA2zU7b6dpaPCOX9
7tbBAEH5vJtyFaGVm8hnU1-J-dgwToJs8XvxtUachz5Vl3ZKA-LOx2El6UZw-kVzEWv_Nw8HZs8yyfeveQydUwT3mP7Ng53e_VeftgG-gyKGLKZGNLwyyUPT
lQIK78bzv3NpeQ1FyaO7cu_no6jEubmllH9FXa98qB7WJNjw9Pljjf7N33pJAzbqZ1KA-LY-3g7ul-RkOpjt60G2yEulWCpxF-tj9Pb86CaQIxFCwZi-Oo2z
wbMs5_-0Wy37t-3z-VdcQutNJ3LJOnmLBv6sjt2z8AxFjXUE2f7NtLvumoIQRVLFc7vx3Rp6dsVrKk2bYQD2v5vl_1VOAZK6x_DTzIhLguBYzeeMtCShlFXO
unMTyPPRvfaaQtpkDRfNfQF6frxbUGMcGsv5h_76qo4kHUmj76_yMECLBP7NE5w0nJKMND6tUzrp_poYETkQNYLv_QzbiCRlbhUGlExQVAoPsTRo6ithdgun
phR0gqIl7uaQrrVq6gyxBhdyYlwx8Z65vmrh7Aze-IaMhSIuNXGdBqrHRJrWkjTV04lCjdP_jKptgaEwQoo1rsPxlPQ-5VqEl3hNw_LqhsXHixgtW9UYlR2Y
CGPU4dTy6cDcUVqyGvScfapnUYeoS6bYR8BNF1ljh375wzcCNvhevMl7L_HKhm_arNbfJlJwM2okCUe5lFTfno_Dwzx3h-G0sEcAlkWrlnhza-niGo-_2lsp
3SJWPMklNvf3Nf-OetT5cwdToiLOtuh-QIPeUJKMDS8CuzNOylqrPqNoAxeKMw75Q6v5vxsU2dL5__OkrSPYr6Uzvf1LDSvv7NBh8qOnGKkjCKFBl3HtusAD
KKzupMYbYBqEMI-ElEPhSsZNFFFrmHNzEmGjjHG4BLMyCHThB3MlxnRv3DvOYv_YWHUr-zNuizTytnnVvvdl7PXdldz-Uq6xlHYAkxrujlOx
}

