sprite $image27 [338x230/16z] {
xDB15G410CN0wtVIVxNGWXUmErD2Ngu0082U0000000000000000000007pHTYbfkYT9uw0sJODg6WVLjBH9MWVLD0wgQHnKqz8cQHrKqpYefgLDqZgefd5G
JUEWcfOsIUkWciP1DItj9P86GMqQzDGq2Aff5bJIFgYcVL1Dyw2Q1a6Rf9gkfUbQcgubwLgQhgNfMfgk9UbQcgwbwLgIhgNfMfhUsRMJ9Tj160QWsuSaAl__
jM_gWSRjG9oUmLhUvQaOYrlyyWCXJUUv35fKQrL9qcakWh8-H46iDFL1KLkGflDCGA7wCieL5I3r3z0kpAr_AOEHf_E1bZITnu2wNwdAymz8qtcEKoLqIuaF
kaZIMK2UJZDhPQURxNGUYYHEbTh0NzfIQGf9_9VXCFEJzluQdX8VSZxCjMKuzKbADT6XALzVdgWqTJoDA576JQhVKqnJC_16r1oddgcCBvBKU1hHyUYZ5Vri
KZQKA-gF_dZl8qVVUagq6IYXTX5oxHV8Xhnk2ky3tNhqGSdcy53BoDJkVUrhIZavZkgGOj9EsvxQk4b1yaLTqt6JGjFTTaL1EXSzQesCVd5ELM4lKb0ZKTzq
tAIAd2ArZIbrdcD0IbmjKjpg0GgaiMZSrByybJr67z8bqVXn2dCPtUG12XKGFUgD9eMj7g1G2ed6Hv_cM5sxdKAAYSP7tz_xYv92YehUR5AiNRJergVYelUF
KxFt5pI5T5VqVfFgznHM8eLqI_JDJQhRK-kOWWgB-gIHunJs3wbrsYcbTn6DNqnRqL-fIK6wB_eEJGgVys3Y-th-QUSERXE8WY28dl_qEFzqVTm0A83MBuVm
f6hDhe57b35bNqXztpGBY5AN5E_9c_AUZoWtfmiS-W0f4ZmW2gGFV0iAC2KyET6N7qndf_txa5b054Z_6tzlyWH4QqtV4JmWIirfl-diSgB09LLlcYL5dTDP
4jJqUK_WaYes7JPuqyyk3zflMX1ytPmMU5vmIGNsl7XE-G4rVJPuJNdF2-Qq8_Z-IuhtD7qsUDvqjopzoTSz-oyfFlXBJGk2hvlJ0i_YIueVq8ldb1zGqoy8
lkeLF-rf-aDwQig3NZ-dAV2ikgG2Ufe-3shwAV2ikgJ2Uff-G4zDUL3dD0MULPTKM4_J9prDdmVL5FPqJc5FvnJmDFq2qDu7KzZJz45FJNbGv_ImdbvIX_Kq
_GDwcZuFwYLrM4_JFwodfWVqT4vvK2-fmtgQ_c4zJNzOK4s7zNHEX_LqJeVqD7r1gH-FVa1PJzCVrbFJ0JsTKnxKIsfOJzCFwsdwqHDynS-3cdvOJqq3UZgd
FAYNL5XFqm_igIdjgIaDAYdjgIdjgIdjAIaDgYdjgIdjgIdjAIaBgYdlgUaVxgaf3YefxgdfBth-0m
}

