sprite $image289 [269x210/16z] {
xDa7Mkn030JX5m7rEDp_jEHGv63BQtdwFq9zqbWiyp74jL_pDOjxiyK3vr04oMD1ayU2-axX71Vnm3dY4nSTReY7urzyZJU4v1JqpocevtVpDNaiQ78ASegW
GzxUpg5OWxmXvAa8ybW4EGLLtn3dc2AFDuGkd8BgFHRESHvRyOQGYln9vk5eiRtTNnRE4ISZfo1lI937WkGKLERspgTMvSZAfs7mXjnH6nvYU4E66zwGQssu
q-zbmSS2CVnO88PJd3B6lnqz5kIn0AU0ZY-BrxfCmSyfUKF0AQ3BsvkeozkRo1i2Jh5fZ5_xVYp8Om5E0PtUtjl7AF4v9My8E4LwZAZpEQM3_vFiUxmXu1Hv
CLgvnu8y5j3nmVcQKq2NjpUH7mjm2l1ZiMQCVyKV2_A6W5Ei54DLRk_y6DCnneAy8T3zvvIARyYmAcy8E0KK_jrxVKLRQCZW3VbX3AbEYlmOhQdEOv4VeqbL
nY8_1d8KI94RuuwgfCYFmHpr7ujnUOmc7MCifdbS40CvwgSOvtbnZErt9Il5mXWa5RozsM9v398AR4Xk35A15CanIFLkxxmOJKeSYnenICfAKIO6gLYAvJ4Q
PET0Ye8ncfGm5hLYa9IGebOCKiA658j1IhYzoyPeqjutX36c7_-uSrNEVIWvZiD00Bt4YC3__zeBfjSMMw2eMSzLWRLTONFGAw39IQPJk0SvN59W12W-m-0X
0uVFia0CuU_2u5DWEDoM1UPp38Pyob69jyLWYCNn0SLM6FZu7t80nIOOQ44vnH12ZBdIJ-zAfHqeC6X1AHoIAsW0XtCARXzXb0199iVs6xB6w1QOHA2nuAZx
K606YnhC54kZ-jwGsZx4e021uI3WsBWirXWvzCHSw-DXNsKQBGsgkvS5nXYCJE_a67ggfK5rxxB0d0OZqPWSUegjKNUyMQmnA3vEKZebWGPoUAAWzaqO8SH2
Lif1WywfMvU5ZL52fabgVFS6MTcU0Z4giOXCdlPQO_yDGGpz4M6Q5GVP6hjJ88ReCJpHYEGKeq4-d8nHHDZUb6oEndvtRpiqvkqXTeiMIsF_iK0Cv116ZLTj
46HJ2Wmn2vuXF3G7tZUICHfRKc1On2m9cMYaoQBm_XJrJO4jmHEDQ9ye-nsd6FulZpL1Zhb6iK-KxSl2Fa9ueP7C3jsLWdi8yk8uQT2GQdRebXJAFLSS0Xf2
Gx8r6ZjQOF-CuNiQLcjiII4Y0Xn6TGWC2oz7OpUAuT2OSTWQScwD31XRMQXepu83DLu_X0CbZdzo9uegFSWnr-2nDlWq6XKmTknD4U1OQ9YB4a-dwpPlg3Fa
m65gc8l2rnMwoTsRZK2JWWOSg3pQs7konORCrbgM6hWeVBadE_GcKI-9v_ihxch8QZGolkswGMyIKosbzeSJuBYl8QStKGgMXdkBL6eAFQbmvu3XG0rSbEEF
64kZ08PZYXOIfV1E1euh3HoDyvv4UFl47GLQIBS03bjZFXfsXKQuXBgtg05JNiC16elHE5Vemnam_51W0aiu9ucgtjFGHuuqSd7jyapHGj4QZ4G2ZMbjyBb2
4QC2XjTtzWRM5CpKImqS3PcS9mK-9EzfB30nAmS8Q2mM1LfJ02C3XgUfm8GAMt9R0_T4xDB8yC4aJrE12Q8vB3Gk5mK1630IO7XwGnqJLLEOXqoDgmh51asm
9fx60fDLOxW83xSlcOp6iJG08mA6Bmh4a4kCA8E6zipt135w8T6tOsZx7r8G0vFwein70p5amCY8uNKi4CDE0GqO3IWAmEXR4XamF58WXXqQ5WL60qe3CKhu
Bnam_50WXgumegn7GqOCUJS6z2UvkMNP62aiKjwZ0QsnmaXTam33qLZWqPh3AgpAqpr1ZFwzwQVLEwD0Z1fMoOyMkDeJ7Z5wNqJhgt4yKM2IA0MCtQ4u6ZO6
FxUa9llBrZoL1IQ8IbWcuMZCCQH_9x_72cR8qLXW0i5nOeU6re0zGGoXSd1am714WGbLjTmQ3I5QO3o_8_MWcy62l55WWrA0B0uKs9FXF1ML55w9bH73LLbW
egY6TRAgB33uCHZ2L5AC_TK2-6H1xiO2IoE7TKGLzWGnY8Y5U-2n0SCD1UQl0dkog50J0p_eXA5tlljTMT-_9_4dzWGnBXwL3l4t5hWdzVQUs1YYEhzKqH1d
5BWdMLM-jYU8mQeoUrw2EAF0HBvrrIXl30OCLU5cFJATuzkYXQ8th-HYOuWgldRgFDueCE7UQCW4GwGzGpVYZGBpsxtHuDwWYC7j45h69GMsHWshL1C3__Eq
Y4iA70sDjneKCHfaMHq-BV2kGM6HF688_EzlSZYam6HPluMI30njPcWUfnJuRWs9Tp5akYLh3gyMsA7yPOohMICxRYbmKUeQOzoITfKlO6ZpbL1qKHlvTRJE
1sFTf7x70ayKJTT7wtjBxZs3ti5e7fDOLIuqgifhCEJkCrI2kAP0ZHXcuMTb25XyZGCe_2RBrMp84qD5llOGKmngdbCkDD9pIqIW_Bys730MxZLoi49zC8Hh
csVD0HIkKrZj-qPKeVKph3cGmhy6HsCmwCFRqH6ZRPBCOWn7LgPFdq5_OBIDqZzoMeRs52Pk7uS8HVr7H5LLQdfPC15z3pIrxKBwY539AUKgJEsNZXxIVety
0m
}

