sprite $image10 [217x162/16z] {
rC-r5SDG5C3GTFyekF-qWG52ba5M_-3U5eeVk-qb9fOc-SecNnZb2wDyNPKlhF9rLRwiojTL-MgiFer23LMVHge0AqqZMS3Lf15k7jPuHIplWiEVZIuD5Ep8
n-Hs8PEdkHnNWI5OAy3KTk5gmn2kDWpXQiDW8giFOwgB1x5cWkKe30FHDbvB4lU_xgGpYyE0KXZdDVy2oKSBbl2NJom7wC-ASRChFvrrtJCabbBP4uR4SCqB
uUkj6cG7XbZ_1yjeeb_owZzpJ2YOGxT8lb31nCiJ8omLb8gJf6kjYNWvOfI8zxJu5KwfbN2rvpfUH8oJU1HY0w4k4o-JMR4GHakj16RV_IV4GBoOM5ohLshD
ZGAt1xoU4OXOXtXHCTDyFX_ZoKPJlKG0BejXK4mX6Xsrp9Ch7ZUNOygwKh7Ej1YWpcjxq_nQE1dOv9zhXiJ0lBWOn0fl_VMDFM_n4GyjatfH3DV40D5CftVX
ZQPuBRvzQoam8ePfiISgqQaC0Cm-befQKl2AonvUAd34k1acn01jWLIHqsW8KPzP2Dmb1j52OkOs6f-0hZKg1k95nLYoDNISHkDHrmSA_BYOOOiUdIQZEFQC
R3rSLyJ0lBXOvoWV8UZqHaE8qhMcnJYslcBO8UtWoQEpQJG-uM-BVoDMFYcczegUEiB6tHyGhM_LbjQBQuECRLI8ro1rBxR_YsB-Q99bxLbuWnYPfRnQx6hM
yYvkCMFzHWMVW8kDUtLA5ziWQgkXbXIVvDAUKhssxXNZmvGyKz5rss8cWeynuSM7gKXgGKHLxO7gImBMVBCO7wPqNJ5Cx8UnU-335DPLBpwXfU9-wkBEKdQz
JcF3pNYd975UI3vjSSQUEqYELh9Xh-HiAU-W1Z9CdQSu7mJke2rqc9f_GbSHcUaQP9XYy8sYcTmW1fH0XgcvEdqkFMuH4oracE9u4zh2wfIBpQcbtRuC8rIo
KRn7h6yxUkh8l1UlKuuefj5sENKQsIXUHnNpY1QdnJCMzoMec4Aws1H2KcVWhLpw4vf0p0GVGJThm0SfyyksqMdnWXl423N7iEdQiRJpLuqgqRfBhCJZWr6g
vyH2py8vHCtqKsOjyQixN4m-LFCF19Iql9B8UU-y6baTNqOSCTALbulNCvOAtZnmHDfGJsMYcuk-M3HrsZOZydD7g3Hbqqan6nPRpHccE8c_e6CZObc5Po89
6H6ZnSKYqdnxNwoimWFsP4AC51UzbLITHaF4QC18oAXO2LvWKYavy7n49OrcN4n4xIyNnUhYVmvw0lTM4g_G-4PCMS18o8XOVFS5UJLzO6Tk9MNNtXKZ0Uk8
38jbUZtZxAqa8VQZOlQ2Yb2npcfieyWl2wJNB57_Lf8ZHhmwEYGcconamvGY7cvgrBVl94UC9AAJZ4IiqEiPvB90tVkB_x06n4J4p3FZOczlu7dB0-glVgav
OioBbrbaKdnV9fhSZIfjD4oiUwdj4H7mNIsvWKVsT6HJ8vednAG7Z9WHiU5DXJQwgL746J4pOkQ8yHRFbracp7v0Z7WHCo8sj54KxYzQg1Z9Gsx6nGA-gLlQ
z0S18kPu4JCcnacV-Y30nRgN6ZEJQR4iClrzZ8YHU16pYP_-IR5VtTlPcjiW343XUBV1y_NztxQK7ZUQDKYVQ0ZdmecNBly8qwlYKiYQXIbT5A6z1YpWqidQ
Xx5jQ6JX1M01Ltd8seR9PMWRshuTgc9jc6rS52JjV5EbWctpgkfuYx1mQOk25hGfOAOVcsIPXrQz47NnmpljHMWDLReAVobfxRDm0NiPMj4g15PA2ysmugc0
jKyBPInWo0fer3eB5x2cQL85on46ZPwWObWA6B8osd-t1JKB5p3TsAXD5J1aUXlLHl5cwLt0R3QgY49bWI6psyWVXShciiFOIuXyJ0JA34FcWIEBI85Ik90v
uaZXKIm_XGkOhqvV1EK6G-QXIpsDX4ibymVYyHFXii3iHfaQOuSXwo4iH1swg4CNTUYYBbrssK7YqhwkwnRP5gzxGVxd7dw5-7u_SNMHnNMxchcoYdFEpjIK
FjTyl3fE-Vr-CWL75zbWDEOBipXNmoWwkiW6eosTRxVKC8_Cp0QRFLraWl4nf_Eybgx17PzWV-AE-2PE0hFsT949Tav_GVk_bJHagHR6Bt1saHasvq69Tsqm
m1P6xieYDOn9xVZ4TlWOjh77owMu-hj82Pi6-Ogjznln8Omu6OTyhE4Y7OmzyJFiKC5ehSGYDMpy0XPqCAhb8WLictd5n3kstLBQpMDPyh4QYufXr-OkTyN5
jYjEwJXKP54fZB__ft_7kC1v2Im_7ogwg1GMhhLuROyRV-cOboh0_I6CjxGgYyfW38ZHJUkSFrY2QNNcut1-Xj7APHPpPHOLmR84I8xJF4lQ7yCOTQpDeiSm
bXgxHcwAF25S1J3MhfBbRujhwaojgODBypIjOWFObscQOV5avDlLmMKkxcgMFwr-g2hM9OkwL56NAkfIHNsgg3kKh4yLzMUIzMYIzKRwt5Czlm4
}

