sprite $image315 [236x171/16z] {
vDQ55SH030DHquBwB_YOCGpAhy5w7fcUPcJPXi1H23-lEAictBJWhgWGItWMv4DzviB82Zuf9cmquvki_ETx5tn_vhlgR7_cWdYs6Srajg4IpzOgdl3ELZCQ
8SZ6G1T9riVHLH04OMFL2FyCGJO6-Wk286pErn-45mJPcF24UBQEeGN1dsci-eg3a20R0-F9I_qpUsRE1DTrPWN2HKyqjlU_tdVIiNrBifK_FDHMqCGTayyK
OGWwKnvW-SqwCqSiFVrYdPcL62g_bwZp_k_wEtM6MIrivUuvbf-fC_DPJTDFoFSpgxuim1fj6-DrvdlM4GyDi8Q57AyppxC-F-qr8slfCTRdqxPStfO-mlfy
sgP-ewWscpMUjl545OhrawpMywFoPLQaHrddjutvqwUYw2EiREtPnGE_O9lRIyJJDhvuK1vvcBMhTYCZyW--YzLwUdRnqEKKER5gkXT3fYTNwF-kv1DhO4aJ
RGXxkJCS9YUh0iXvJrFIi00fxu9FWBpyl3-2B82uM8VLINL6yOMzcTAwRMi1wBDf8DcsRHNeBw3-v-iBN07zymqeRjPusyXPw6TjmBhzsIfep3fG_wmWcq27
to2MKOUlW9kLsyPudV6p5fHj1od4gaZRi8xKWRU_0kSps03ritBR6AypVjPsi2PcHTw66P8UhDjWNGEiN7-YTSRFMe-u5d1SJpv5ElawO89-nBXxMUDj8x-M
dxNlebm09LOJj3sDgoMKuITaAqW3l43ConfFszpzctcylVtTrl4dsPYr3GIL5vAE5z4qGWc8ZiWeiVgjJVuYbLjYl8n_Dr4_JCLGbDwOac2QXLZDoioB1nvr
YDLQ5idjqWzh5gHwT2O9wK1w-RcRYpMUjkN_-XwjJDgPiXKDj8tHopgUSkQpfcyLLoTyaTfncDe7rbR-h0TOALmrdhOiH7zSPVA-YIMK0oTXiOCTeKSqavK_
xjqV9V6B1zPmdixAijHe_McXaolfpBeNb5JqmjfhIlbuhPh_-UtFhvzOhVdVQuucAblbXysiXG9Eh8rQ3AM-eWk7Z5dl2volRVJN6SzkhG15jG25M0TUrbu1
6GaWxUNZdVVLclnNZqZh7l-q5x-iKtvzwlrrdxqximhAFX8qoqZhk_SlLY1xxvzErgmt9l2_wSBo3LewvN6oLgJxcGxhETO2o_0xvDnHhC3NJQqwsaQF69ox
DPxLC_N3Zbdz2wiUyJdgZ7ilKObrDzh1s6K7ixXO_N5gM6mEQuDimmILPG6ivsuDwCDNYALT1mRO75Rhwx9COJMWh8C9nlrmGbe77lG5jBpnchKt-2B8Twpn
Zc3PR5tNPGfh0v2p08rhZlNnsma3INO_lOj-oXaG-vfLFQJROBs4DipAfQXHBq6rlL1NKmWlcNsiEKseKVkQTDrsLXUjfZkxi0xJKjfDFwordEBhVtu__5Qg
_iUitWN-LFqZ9LOIScZ58pgpzsTL5OzyYJLAcsZOcidAxQXBlinAGewrY5DPMJuE-J9ha9QVzKnMxaITycLMfesCT9DPbUJZ86NM4ArI1RYogjxUItIYPj-q
Vx5RQ-v4lRAoaFrnxNPXpVSRh28us_0c_pQNIZwpicL0lOdAh05QZgioArT2lH-s6or86cy9Fx5QxMxvCkijRNmNdf1ison1g1yU4Fe-BUZMWBPkQmNKTFJF
gmBr0wjJlbVMK6ZvukTafQ5y1VY6u9njCee9sl0hicMKS-O9iXBfXJL0UstRBZS45OLO5NBU41Ym1cu87F8brYWjBwcdt134IParbBQyfBx4jTp7LIckos2D
tH1melfPERJ-EKU1vJvVTJjsXu9wxYZo7l0Mo5SYzR8ohNz-pO2kgmB9cBMCpzwUWFSzmR8j1L3hG5x6Pt8Zre1y7Qn4wsVbGYf6h9JSV4FGo2z6h2xvXbYP
riyw6YGfbtwuoRzsIlFBr-5tyjsiH1fW9I7xMEVV3pDfc9Lf0wna4rWfKKEiJElO-p_6oeaQPsNQBwv-PjnBnENBh0uXVxxwcJ2hX-NBh55QddIciCP9cJKY
P3vYcC0QJ5IsDW02eUM-_r5M8dMmHcYxpB-3YSkNMID2ViDMcyGQbo-pHcapW6PFiXBf4wmiv2PgZx2oVEEiyMexeHyEaJ9hNGEqDlbdBeGJbSqIHAEqLrOD
Mxvb3P2kPRzP2mbv_iz8YSjtQpYiB17QwQnn-Gh8Map8yra3f4i6m2OzGZkFDPwe5LTB5XBo58idgkBUol9pjF4wSslnj9rWiKGj-631-lDRycrVd3FEe7sU
j0k-iBhyhpdxk48eXc8WIexzzykU3FhMjMjuSqQIvpZaI-wPpsyjiHtX6O2jzimA-8TvvZMsxf0BeDwzhEsHyxtUUQQ6BG3rpZCSM-yP7nlpuI5_w-oGlMTU
FzNsyk4XVtbil03FU6ozPxn_FAZtRnTXEmZK5-UBiIqF3wyVQ7k5uO5Yk-JvdWBFWDW8F0FQNcLuk7-WxG7FmDXO71uyjW1K5Xj186J-cT0pmpu9mFcos0Y6
1uOjy0p35WmFhEq1K1csm3CiDlO6Reyj61vOR0IUOMtF3m-zJmBW6TRsW6SOji0pB3Q2GCZy0uO7rlR0mCrYe_6C-IG0mmF35dY6jJqmSBFO23p3sXxm3CCM
WCfY8mY4B3Q2uO6rFN2-hEs1uO75Hk0PXYqO7fX_0AYixG7FC6mDg3S
}

sprite $image315 [118x86/16z] {
l9Vhcjig34MH05qsTj__SGzHdEEaLOdRpcJzq3UJs_eGtZ8kVqjreV9XMDtXxQDE4eTFOFLpqXRE04gVQYxy1Du_sDmJMFjkQJ-T9r3-JcSrU0PSw1CR6dnW
UwaxV06iVbDQra3v0yrDwFIrQRc8jIzDIx-4EOo_C2tb4W9t27tPXiu_snjgAOglID6PbldtG10_dA5X_USKDGl3OMtmEroQPqXO5ocwtbpqzhELIaKQrx0k
XkJrUqkRUiCVMyFR_deKtHf5YilMnP2yVcy1MYJYReKPt5ND9-PuLCoQMA-dw5YQcnvOQ5jOAr7rEqP40cEY7hMbraZHzRIW_ThqqHY36xWqEFNDYd4RLhJM
uIIGmxewQgoRY_gh5MpxxXJxghnjUwkqRJzwfJ4h9zOaHSjHb5jbtvN3QZJslNR2h8rztrjDh4cArYSnKpiuzrLBxqN2YaPIoU-r5sbaYJLBqVh6ZHi_NSDQ
gyugvkwTswp2pMQjrLwk9YoE6kkJM9RNcC9cxl7dQtsPmrIlR2y9FAMMGdxE9hWxdt-UzSaQVnMs94MKtblojNP_M5KVimakzgZkeWYNU73lfYBVtdLp0uaF
X3Mc0HzM8QO6dRN2RlLOwq6FjMJRoykJ60wCertJEchTjbeHLjBTILasa73V1dT8AQqVIFnuorDqf2L1seFe5aLUFQQ4YjwdHA-p_f3AOrQ69Fct_C2UElCf
CRZlUsUukLl1ld4dkrNMswp8h7c0OUEw5Kgr5esp15ffnEYbCRkKokGtA_4TOeeEMIhT1aRkbTg2-jHXjzuCn_rLcxX3Mp_hkJJOpSfP8p6s3MC2BAucFwwc
Oqgu7rR4ttxMPwjarr8mjicu0rn8pglLVs-5fhc9vWRZ0Jo7uliFQ-_khgBkq7whrkMeBsljyMVItDEwN2uzpIOZPZA_WLugLKZXMNLMTiYfWYJIS9xMbLVf
_mwFslQzSSnXA_vZa916ScJMzcnrPCtDh8Stlvhqc1BdMM8_fiGUKs8NVhPcpSsj0Sxa7BHQWfY8SMQuMQtOZbZh88crzeKrd0lh07u_9OmcvjFgBeNZT17x
Ia_xcgTbRJsykTLTn6UvNxsYYEeEZwgv5I5QMWCyJ_yUVZhp6YpokcZkqZg0v4xt_4otUE9ODNTj3U_hRBl-dBDkRe3nEv3Dfe3MQrqtD_3nnciSF_LghUkd
vhKph0DOjHbky4ci685qHSBhMXVERNUsiLek_A2Kgd97LLBQQSNAkUaj4RxqFgoN48HplT1QWew1TrwcAoZUDNUqye3qpVPU16-RArIUg9UsTys5vlAlOtRf
zKiidMZfq-k_jdcicrjosFx5-rzhzc42C0p4K3Izxh-l9_17VAG1qewd79W7-gnq-6O-SwG54YWI7_S_5uXG55PHaA0abHPEK99Q2-TAn_i9BVDiqNYz5g-8
1_g15bQ4z_LQE5oINWk7IxAWHIWgQ14bMT0YIfAr-F2gmLfyUDKGMWgA2bh4lwYWHPJaPCs5D1G9BGL5GajXl49BGL5HIxvg_0KjOjKGMXgA_CST
}

