sprite $image375 [260x256/16z] {
xDT9Ujqm30FWBYC0JEv_savlO5Fv2SwkWelCyUx_15B--6SoVWOVLyx0kEMg3k-ZSrM8SPGh0M0iSkL3q7cxDa0dlmO-m7y2ANeV-e1LbJm9VAYAD1Yd0rL5
6dof1g46nEaQf1eCSlW0gavS4qYF0AbI3MurTsq0LNz6o15u6tS3ueH0vtPkteCM0hX4G0kqmItV4WJQW33xi2FX_aWH16r0B6lG4NfLnhmVWOtW1OYCE_Fe
jC64W5S2_IX4e0r8c4D0_FLe-nhC1iIw1jEZW4Cm8vogGIT0O3Q04w0gog3p2O6rt8UR6n33dWIp3_Ste4VGQX1467W4BVPXX851c0qq2GGOM0HLH-nLcMFW
4JJNGAeW0ulG1Z8rg9Aueu53Q0EXz-5nHDMM1Xv1PX2qWFRiWaMu6LY1ehJhFB08eCeFWflKzWPytORRJon6eRRU2xuDRX-AKWKOB11ErI30m22OVLW11WvX
EGXKOGQ45-Y8ZBWh6mGt228D22_G-p3Je17ynJZ904S8lWP11dFk0cK4mWmm7GJw6ioHb78E2ByFZmLgQmEG7JC85iSZvnnGNnQGLBMz0Po1p5j3W06nD13z
otDs5wH53LXLuGQ-1j46Na2gsjq0F1e9iZU2njdVW5YT0tyZwEHq0PyCv0P1YW5c19bzs09fvw0HvA-5LP46ZI2_3sCC1euHjAo1NkFiPl23kZlRcjo4WG2S
FQqgpV_-RvjbDeupg434ZP5kdMNcEmZPOkdVp0piXgw7uf7NFBNJQwUfUYW_7RtUeHr3idyW1OhD1vqTwi9W_gl1IvvOwIAu60FoqKSv0JFCzW_STOBKCh38
WC9WyEbOom0c3D0CKcbGoy3CykE0CG7Rane6i1-2q0RZUbZAu6MTcEWVw9NdKWRXSHK8W_HNmqVH8pi838Rri9O1b04Hz0zqFQnb00k3VGHFrCCA1Z0Hx2E8
B90uh7Z53Ri1_OLSh7q0p1c0brWHy5Eloo8rGcx_WRlyU3xMG2jGz0-o0kSQQ0Mn_o0fSBe10M4msJ-OQZ5MFA_4Fe8B0VdLKEMiJhv_G3q8AXYeXE1uxTqJ
tqqbpsYWWt0nS0O0tKUbpYTe19zxBVnKnq0hYFx1g1vMDI0nHl14FInfG0oBWoVgOKq36YJ2PmFgDAXlG48YgAbGufGo8A0GuWQAtjD-f04Y0r8Wh6t0g9OB
dmCHmfh0oGO83AuAmc1IeEGuk4mBq0Qk5XszGbr0r-2g066Wbzogr4P41kIF2Adp6sNV3zWR2kWQ-60Gb390P43YYf2R2-kFWwRG41Ajr886Y0n8D8J462Wv
3X0PaFY6CBC9ftR_0COWW2y8YQcmydmG3mMIorltKSX0142ADmBv26PMnm0G2bn9WtRDwc4620nqw3HGWy0EL20G6u1Hf0My2HodG18838I2g8So3LgWGFz0
HtuYwCHfQ--n0OH1OYBe1K--wyD8hP2fXuI5SNR_G4Sg3LJWjBNtX44c3NJyUThQUy8W9Q3ZjBNts00T0ob0cmoSPK2W6SGA2rEXZaBzWuk1wzV2P1otzavg
XV7tOJwEMtkdZfLwg0Fqmmm6dyvKEx6M1FvLFN3jdIBMwg6-dDcFwnze1L4Fyu67ZuCJG62W5EwS25nS9rUjV-1SJOF73NeAHcg5k-fX4tZKeATWf5QuAmrE
k3B7q478zm_S5mMUDxWUM89QUnS6w_NmUOFN3uTrrDfxOB1O3m4_uVgexa4LD0EfS4CzVDu0mHaDe1c8XBYX7Zvj4Eouo_SFLWMUDz27UG4QgHM-2YocmVC6
TWcn_q0an78Q7B6VU-fGju5QOJqDWY3S7pldlzO_k5V02VgcNFWmcpMWLh1Rqm3OrZ-mNY0ma0e0xfiAkQz_OFq00WE501AuCGqs6OY3xUWPI0Na4a9qtZRs
3ooCOVy0VGEXaAY7-_e7uqiUm5J_09n606E1ZVq3c8YP_GU83COAWub066m2IFSFUc1OIuED_GCJ4VOF058guFfiiHxkCJ0Hedy0i8E0o830GZtSO_2oYUXM
FGpw1nY_E8fR4S1jtuqs5Vtt7tO34ALYDWr03nvidWjr_m0WfGAwp-RgeLgltpe8MkXH7pn3y6XS3ztbIkNMYK0RZ10GFbCz0eVGuMS3WsrD0pqEf8B5puI0
UkRVcpA_xSi2RQ0J0XOzMqm3-gKnjLV038cPJoIBDd0V_-AbmrhSdGOwI2HgeAYVmi1L8v7kdJxz1W7TFm2c-WUOCt2H8UtPnM1TmLQY_-uxsJ_0X057_OF0
mBQCWV2tHW1IAk3oI1bGraFNYzUlb01jCTge5tzhrJ-0Cd0XuF3n0ZxpMP0FYB-OG0cV-NGzT9_Qn72_W2wD68x-VkQWP-0SrKDXa5Mmsmn83EV1mHpgK_KG
djdJbHF81yGhOg0Wgwcdwg4sQB718Dq_iDwpPk2w7YviyiKx4H2z2Ki52_yjJzH3OP0T2w-x3KQBpgI5GEuk118dVx9Z0RSR31Gi7YOGzL2NIXl6cn82z_OF
T1heNxFx_uU_SBE1L32kz0zqXhXDXKR06W820wLWJFOFEBv8osqkNkz8Y8N-WINx1wJyqGvXi6rQGCT0AbYsVo09j47-UB1X2G5nRSpTa-5f0M6m-Pq97GC0
79zpqGOEVNMACD3nspiJejK50CYUS_5KFHG66uQ2L018V0kvJqNt3rBtvxYbunrjfLOFBZ7Sfz8t87GzJ1XiVNq6EWR0w9uCN0qMVWXT6sp-gcvf81His3-0
_bM6ZC7-jmK4mQOW-mU9UfWmsFiH0L8hw7iol7MCarU9qKJi7GeWjO8-v-AodwwlpLYEszTUm51Xfd-GI8Eqm8x6inuAz4y-lYTZ-KQzzTdWBGRk7GN_Hg3F
kMmG40GgiWRU4g8D0f_e7p3_UtwMY_KBrz86buHW6mIZUpAI18I9kFkAhQI1uOl2Dm6Vl2SZ8-1-_rIe0pa3-wRmkUPFtvEnOoBG13gGCcZtINlYdCi9zL17
qi0CT7TN_GDbu7mc3NGWQM3uR31_JyOfzL17pi0-6vW1S-TSvdxaUFD4a1yB88d_6fXXfdz0CGZkg8VusBof_MfWDdDFnb7rKCUIWTdudentJeMlJOTSj841
pQ2hS5ezrB5aOARx1tJdOG8wbWpCv3qPeXu-bWOwbWmCnZ2EhOVwIWGTuZTU1S5f0ZlMghN1t-sQjvK0GGn2ipDQlQN_Qi-aIc4Dm_mIU0WqXWu2AnLQtOS7
xk5BzuMbdse3dY-L5TfE0VsVhdvoCURvLWn4Io-AF5Le_HZO3KHh-l04mTCzsOeWA0oyL6X-BSIpy5zOcWs2mi3F2YtlGxzmD0m2VK-wcu3tWhq79bk2Vr8K
uC-JF1ZagO11dWgViA0YJJ3P2lnXq0QM0m4_paW59aUc0fEjW2WMOCzMW5mSgx08z4QGwmMiXkW_JLH5O4s880XK0KiJcGEJ8iOWf2UHGX5VxLUF1OGHcGEJ
sX8CAo2L6Yj19bzFUE0N
}

