sprite $image130 [252x155/16z] {
v9b9SgrG34E73xYIi__TfkyZCCzK4EKp_J-9Jqcckm_NOppnq9BnH4zxZ2TQsiVunjAixj_fPDxJVXcA1g5hEfXh6fZtinyfbWRccWxccWxccWRgcgc1kQQl
-VNjOvHO6eIkYGRccWxccWRg6ZGmrqG3SysLFypKQH2wPcfZ3eZe6vW3bx8_rFnIzfzp7wSEN67jHLSBvbU9Vlevzs7cuF2s_slkOzIfVfUn-HD7c9iNNy-D
gZdDrtuziOeypIzw6uaLx0babiYlxeMrb-PqYbwKLNGrpT_gj2f-egk5wCKEMTplnC0YiQ8zdQvvQc2An4hst2mIplymWz-miFRIdFZ-FybpGzTThTapOVvl
xlMkvldB_BiwO62UAIjtksT2Xu7wTbSnzcDghj4Ng8ez0Pz5rsJCyyZGNG_IytKdnmQcLtTDCdJ44nWRc9fhCkQC9nBshlSrpTQYCpxWI58mBwkJUpBQh7l2
tgNkI4oP0_4BM9ipaL4EnXyGBdLVdHV7cUlYspp6CP5HkkuQ6jOzCMKECDR1kVUr9JSlwtLNQs_p0CjGe59t3KthNbXxH1gucPUBpyZ2_wyxxfaMXziJ1W-m
wOQc0HFcEF_3JAJXSLjFmk5D5QouQvYiUvnwu81TwralFk7qUIAtdhk1QTrrHdhU_K25ZXFkQnAKwgwXhFim-WABUyr1v2f56DHTmBlgpc2isrikkiue7tfm
kKrOlm7oMzrFDnVJGfbhg-ds13UU-upkQs2eQI7CjVoupPJ_s-vaaSz5dTMQKYwwtXF2-i0XNrJy5UCyBOjE4vO73gBNhxapUzumpyjqcxR_DmCcto4regY2
n_BEH4Tr78YYRFPT7E3__tOIA5aq2Pu4IIGFpipRj9-kAjUr6wbLJD0c_N-7_l3_5ipR7JZRt8EvB9AYcvDVCBdlDlUTnUxnq2yDxj8IA1lmwq4w4u3wZXgP
bqsfLmRpvdOcA0km3SXIQz-fYrdQJhktSndOlHn-0RoRH_rjghNlOfYsijUQCzeHG7dnB6C0iW3nfcwBjr_pZf4FclkzAtRngrp6C0z_0hBPik-s_06nzarZ
tEucG0lvkD_rx66xqVYR6_Jb-quk1c0p_5FlVKodewBiD_j6dstfOQOjFxNHgOTsptt5Cq1HEXpkzY2zrLlB-vYaHTLn7yf-n81qtErEL0GzUAFjRj1bEPAW
kvrivDCX3NNV9TnW_sKm8kYPyXRDYHujDQTrSuuZdVcmsnqoJiEyPm33lnDazeWseB7wPTszHWGBxLq372cmTzud8EUq7qxv_V3x2Q9hnBMqhK4N7l2YXhUZ
f09ohteIysctx-sF-rx-UCerw04oPNjJW_uNUe6yRKP9TRnL6OVeznfq28Y4H5iitMO2h8csUnjJjW2RCdljdYFHG-lHdzJTlDlCmupmZ6mlqRUeAAayjFq-
KuHDX3zD01Rjyk4NM02Bp4K0BFEHNNExRqTywFxnjnL5_vZv3g1cjxjilN7YYuxSpjlOxm5A9W0vlgHqz-5lf6VGcXxXXldY4_zFRiSnqs8CUZIJ7isx3vdV
ErkUr-xld_YertNIb40gshs8dnxq1AXgGesz5WD9F5FAGdjIY01d4mHKejq_kTTgiHLsdZFexRgt8UqQSUkZbVJ1GG_av_Qc6-q-DfSRxerjJyWKU_na_lat
AJrADWPzlETTbcBVl2tSnKSRVJrtG9mexmjpltUfTGHusOr1Ny4Tr8n1b_-wsmktlQX6kw_b3f3DTg_crTrS5dKym32lsNqJxhNn-NhG7ztrHj131DZADjp3
_kLUUrBNMq6lcbTMTSyvpnxqQcus5luIvBAQUxw11wHcktioyxyfRn8gPHttKqeJzcoPJuUWjym5zi1b5NTSaCVoL6FGfpE_mANg700XdrToFv-Gmdt2ddfI
RsL-BJ4NRkAak_CwxicNT77A59uGvxQxjNpi7U9KtDjNS4VAwNB9ae3HsCyqP-F4RmywMSuzg-sud726H4oD_UIWjpC_vuJRkxhShPLf4UHJ8l8ffmdxnbvx
zt9lHiszMgPr_zTg3sHT6FPuH3FRFQ1QwjtvVhp7e8VwnztZ7o5wSp-VDCYF74VjtixyxK1h5vDrq3_lxclbWd1FFEFYXB4HFRFTPRVTfMAxb3heAxXV7ydL
FjzEV684EUyjg-qkahZPnmFT5a2GSfT5J27EUiiQktUTdpPwAP5cDaAkfSSBgEQZjUn9zzxIZeqEtWUzkuRvHa2JQZ_hSl-CxU88CuuvtnPvXlsyo_sKl8j0
D8wu3TR-EUOsshrnq5rj5wlnMUWDrhvrkssRTuypVxt6wTvTjykJ-IcDB_TKkzr3jxF_FiOMTurstvnzEfU9Z0znojoFvZssg_e_Gtvmlo2b5EuZ-rVceUkU
HdBTADMTPtRdbA69VSS9ywT25vU6-SRbSpfr5r4Qd_XyQVwesrt_GH2YAHLDFsn03aRc_poefIUGyiI93qqD-bTmoM4__BgKb4Rk2FCWzlTtWCfmk-L87VgM
drJQljsUy-KyVihsL_zaxZhsn_E5alxlKRRxClcmDqEzqVMHMx-lyK_429THhlakSiOhQA-rtTT_sP3jRorwm5RbtVWey9UNtdQ9el-SlQwbXFdFsSlNNs3Q
NTVVe57tNxIdhp_3xZVh7loeUu27bmrTVusR_BNd7tB_3m
}

