sprite $image130 [252x155/16z] {
vDQ55SGm30DGGz3k_kiUCqDH-GiK4Zs9baTA4MeI9z_8JEq9vZiMgJ5Q_QGgDOIpNobChOX-9xKLz6iM29uKVw8gVD2VWE-xQFvQmk-rQ_Ynv-8VgK9eadyi
CtolFMUnXLv3xplE_eCYU0FsSudXU-qvYv11nuzzyhyLXkurl9ahrNjY0QJNy6CVpJy1E7FLl7yHeDU0Oy_9Uz9r2vkvmNhxygq5nLvhhr--jP2Po_dutlrz
-ffQyrno80PXyAHjbVp-RtkzUM85EsG2fx_N_2rIyC81_wBVJSAhBd90n3vXqCM17UJW3lljDhwlYN9vqDdyNTibNT1hFO8yU-mlcpgtbvmtOtz8qTTqnJpm
j8mqHIySTCLyzCILSbrp9s5MH-mbEPknFuPVO0sl3iEpHPxecdjS3QzwIgyp1F5s6pcOaUZqqnELHEmZ1pDjShfhJzD8Y1_Cu5fqn5wIi_vLu9vXC2F87VIq
oR4S0WOpFg_QQf7Nw02tKvx1Z4Qd8_JIxkTKWnb5xdYxaNQVqoqSZ0-eCQc71t8z9bmuUCbhARi71rsht-xaRgXfzqlYXKDdqL7UPBeYiA_DFgzgWULJ6Fcr
tCA3RiiAEikF3EFdw6laI8rCkm_IWvYY_XCKufI6RFA-s9FF6zDD8fv-UfQ634j5Nc0fQkGZjuqVtzSeQ-ItkqqFSexgQn2d71TaqRMbWA0Bh3ulFNRN8ZBr
DLqZZzsr6DNNZij8FE4XrqAAlcRMo65uBQRgQrfmqcitWVlp-feLT3yzs46E-C5CwHOVbteI6GOpe8TTYtrsFyKk730KJx_nYP2-9jGNps71i7kEXGFO4yz7
q1DYC1CuXuJJxdsM8d8k770lkJMkQ_MrATl2WNVPdONbDdrWNviS7yrsqGktUK6XzL29m0jiBN5QA79DjSnled7l8z8i7C2YJWj1hk7tUQNuxj31Z8peDgyg
fXpgQw1yJl63cN6ZebN6TTasMKqYvS91-FgpxkpTDxoMToRgZS9843O6gGw1t_znDmJPmzfA1_BjXzcavhxdjwheLaj991Fy_dTFj_4K1mwH6aODf6A2Dkdl
7lhpvoRvmOEPs86RoJsJoo8fEan-GQFUlQUknVJhXtu9j41Be6p0NmTf8W1zEEfz1mugUpIJXzMPe2p0DY1BKRtJMBEq8dzpNOlxCh36j241NCZh-jjKLEzg
cDvHrtOF64O2A5-CPGn05Y2Af6pH5XqyHavNrw9wL_nLNyPAVkS7P3EY7zztu10htccqxMukfizzjqJATZL-eFCCPlRNExaOWCtAdsPNfQ6NIRl6tgMbqmrc
OlXMHQTMTi_pQmjGbAxNXHwapzh0_bmcQL6FkC_BtcEMr5yk0rKRFQpeJtKJrA3BVac25ZhPoCCr8Syb19_YFEj6RVHMnZ_JJL0J0BINdDR23DaaymV6DMEO
pPK1p3zEa4bIj06Lizq49QfsqllHm942FvYx1EISkjbWtVpr0FrxXMpfN3T1XPMyo_2-Bwc0_84wY7cuT3cdllk0xuVyQFG0cR9zefkW1jRQ5NlPPbrIzP-h
Z6lr-wFH8I0I4csnZAUv2MeYPezboikwKkR2qXC0QAtvIItavpbm49ubstlmBQekgJpRliiKOVFEJnE0HRiSVR9uRGnc0d8H0Ci-uz_xTdy-uk-uQtvRPJpu
PB7BP2uRxIvRFtZYY_U-dP-nxm1A9W2vlgJqUF21GpVGQaSu8D_znFUwRqUVQR46lPf9uz473ZszE5lUPlUVF_7nsAwJfWHIrUv5BEF1WvbhrZzC1NMj1f9u
LYaxwKb1l3Tw8A1IxNxaOAPBydg9wIr1ZzSz5ca_Mjp7q4ewlgx9p_Qc0xk_aii1Ur3j2PaYILVommSpRaHR3eF-NETTzigMALfOm5t6O31pA3iWDfQtIHwm
HzAzqPFiLT1hNNidEwWDGPV_cztUMUr5MHh3cw37imDaPFTAlcOtzxKwdiK7UHdhOERTx6lZy-kWhzdrWqOFMX-uUZWFEo1-MTUUqBMnqOiFfjM_bJtdl2te
Qt8pAFXx97HlOy-VmafIQ7StU_uVmfk4qflOXvGQz8p9Mo_EZyW5aWJxjx3ZXlmAJmL1R_Vy0lUYSm67h3UnJmDIPM_GKrufxlcXVK7_12SzJdmBU_8jtPmo
XIU9M-rkxO-zApXL-viti2FbTBjbIS1Bx3UICthYnq5dgGTF1xDNz-Q42HBHYdqpw77FpotDxO8krttxqUpgBzUyq0-9o4DE3VeL-lzgSs_MDNVTo1pDxYLZ
VQK7icwiz5XB6-rUHJc-5LdA0axL0TtHxCxTOsQ9HLctQT0C_yBOi7lGyuViXhqiVAatWezcvpfZrrHZpmat9xmIqHljBZjcb_8o9Qr1FrnORvxMna_vyubF
l8ZSDikAsKKI70Qv3kXEeM6XJtdC8beIDyooMkpZwAUApaig-N8UTNVZPtmXAXnQoswoZvFbcLmLd6Myd4tN5NL0lsrplzPmINPnRMOyJRoSJ_ttz9iszy_Y
jODT12Aew2U9_LhFRMviTxkqb2zNkZXetSyI-xMYtMrCFgw_Ex-kSZ2QF5_iyv3oeWPzQFTn6ktwtNl24uEAVhhOfwaqUdo8BN8_tNQ_qk5biPF7FaqtfDJe
SyN0xez3rK4kGSz-xjWdJXodbA56lQDN-k8IR0hUwV_POv_JCDv4wVM9lqO_vBRxyR5FgQWzs81STS1jzuFL3RakFO6KKrxqGd_a-pq-lia7a6ybDGORbRng
FA9pERxUpRjRlg13l-KZbSQxsodVfjTHjd_BH-QETxVzTAEaxuQom-z1Nm-rJ0a8NLz6_YBoTRqRY1SvUAFLtnFxjcW7rVsNnFuhUja-u2hmEOTQj7s0tSyw
rEfLwbNWtwi1JV5oITVBRrUNskn_GzVyHzbhxFyeUztT_ats6li_obvZ_tVPQvkRXsvEmEMlgKkvNxxp_zFL_0S
}

sprite $image130 [126x78/16z] {
nPY9Tlki3iIzePs-_-FUMeaILyUkxmSf_-c-yKCZHkPq-YiLATE_qiggoki_OS-efggcE8-75sUhys6qwUBiuCisaBrGi4D6owY6WoRumFPlajbXVncGCjCh
6QyZKdOjMWQax5AcC0ytFQLlGCf6jjzJTijzfsz0oX9xL_3B9qrttRAFVDu-bhAdxjck3mxV8dRGBToLqjULChDclfIkXliQBNZhJf-dh9Ulr9qo--_yQkgg
qZlQCh_UuciAVlUpBC5l-CylS6vAsVN2zsCds9MNJpxBJjZszMNdqxxgrc9wh76cpAvVtphhX1bqfApwcZTojlCpssXkJrazNJCZ7kGJVfMrFMMMrhnbkqor
9sLFqwscDKEvuLdL-bDMJzQyhznLUrDcful-N_ngFIbBbT-xN_ClcK7lDRtUbvwR7wRJqdzZjFfRs-tC_cfTAKk4nCv3FDjlVIbpsG5LBqol5VahMnKfwp6z
Abazh7anlckjcjMLig1phMVF4o6MzEs3JUqfooV8Zj1WCp45FtX6Kb-xmTwKXHnkF-34xAzof5VnhNhA-anFzHCU_VV2dS-9t_yiqvjJnRIBjsNPM9X5FdU1
kEI_6qx-kau5YBPeV_y58W0aUYLtUsUNRpeIJE1VSzy5WWzi0EHhE35JcLSeopGlyq9n-ZvoJMS4H0GyBr-yKfncN1Q4Rn6X7q3vn3LT41vm4fPJ_CxVcxuy
sq-4nD9uJP-X9DCHT-SPh-ntlE2oa9C9dQrLjeQp9iZoDZtOlWtdN-49FVH88eqfMqcLuupnotGc17nygbVb4pyE84jpoaH5nQkLQ3WGlxUHMf_RJyvkIfdJ
nUaOfRvDzqz5n4c_j3-bhANs1umGTpOUs2oU0hhWYxhYj3Kx3mvqqp5C5sRn57Z-VXc-0dC77Q0utyi7xtqK_jeDwwM4YBPMEWEQmyF-7wR7yMD4kM8ZANVK
ZY94B_l9sMxwCGLmsducH55eT5vvsvo9B_kVPpsEto45bDhkR6x-pwVAlki5zfLj9yMCzuRdqPFIRyn2f9xr9k5prok4_VXaugCFAGK_yuw5rBFUhSrn8NZo
lU4OAGYw2Rlff6K9qpir5uzz210fZvwWAsyWJAmntFlbxN_28cSKdmGxhlLrctF3--Nj1wBjbRumFLolKbZDzcj4PlThtX21bBta1p_6tlkg3B9DVwIb81HX
VjlFRzCR-jnYFm1JWPynDrcc4ThjPv4uX1WdVGZTq-Vse-irOEiw0Xx35sFo3MfxRZzYj3xTtSQqFwhVIfa6QoxET_emQ1w-044VhjLhfw2Fjn_MQVsJgFyF
}

