sprite $image259 [347x234/16z] {
xDg5bK0X4CLGR3xGVy7hxZ9PJOguvo7bs-hhg2K_gyS-QvJiBFPbgnVBjM3VD5l9ojhSzueqSaNsOIk3N1lxNW2v8lkWn24ciW-Byi6indvG3hasdhK0669Q
093huCeXrs8_4p3475mukIBBaoko3nlbCpcuU795bYTN2zAk6nrSmDbN2m1o7Lpq41FPXBElpmX9v8eiaKEipeqakR7HmbCjrkeEBgpP75oI2o2BDnnSaWiW
AxdSlms-g0ukgZMqG1M0mUKGumONNpYu91T0Ld81P2MN7rny8R9Og_kC8Bd0u99S3bc-uU2IN61muStglmsiS71XhU7WmbhDmGKEiNyxk2IthVrhMzt1XJMR
o8BaEhYmXgTQa5oH1SbrS87aYYpL6be0aklW0idL0goe3YwEN945LN1lWKDC2h3Y3pnyESJcPfBSs52IUzhUkUuuoWGnD0aqTDj-_zVzhgWqIz3K3b1QcfJt
-li87TaKqineCSdNZHCP0pULEp2ARIgN38ARocryXujKxXcPkS6s8PLx6jeFLcwO5If9AW1kRb_ml-XqvURhHf86DulOcNcICN2pY0sqf7BFJI4tuBRZoI8s
SPLKxbcft4mgztX0ni3DxSkDj7gSRIhtjOqsbNiy8pTIwt4hvASsPHljyPQRstVUHdkyYALogoE4B6AxqroqkNrt1ZvQxJf2f7AvbTf8IsxVGBIft5YqFpr2
f7BXeDsjt2nYpKMRS4svnoS3jj6cSdSCNGUjSuG0ydNZLfxOGWjQTbiXbJiqlgM1F05kAhU0kmBN2lcwyJdJZ__W8hVlHbvr9znKhfyHt1KVRXQnvmJkYc-5
tBwl6L7AJUKEZHt2pIAMoft1FK4gDxA8-N2pY3NcavlAJUNUFHqLiTo-FboaSdzt-ogjuBnkl7KHo-sRoYs1oiqYTg45aTkNgTmB5B7Sljj5p8VRKhbfXPDJ
WefOmWKVZonY0G757__miNtAnMSfbvAXJUMU64WEsZn2x0Nhe7MAc1yG_-MpYXWe1ws_VLtbOWb1V8noAJbeZnSn483XnMTO0PA7zdWHmuBMA8Caxrt4G1r7
QqS83wt-3mdWvbO09GVjiIAcBsX9oK82kB4LA7beZnUnDLhQl_TLBYGNxN7bQc57K9A8_xBydxZZzWKLWdPx-nfQ032uNE3oLigbT3PQox2fN90IWJUuf7GV
Aq2AG6iPyItQrWmkGOBKJOeOg4YqLiJMQB48OIwbJFMN1xTxAnZOMBHMnDPebyUs_9UfOM6Bcy2b58FMtxw6TiaC098CRTT53Fe-U9oPWatRpcN9102h5jQf
Sa45eVNVY9aI09GrsmMjkhK2fJ2qld954f08D6Cxcsz1akfJkP22qVf538jkgx6j2rl0djlUh00g6gr_X139DLlJBK2AnhQF8uI1ZKVhAnVyrGdrgn94YbqL
CKfxq0OKCLbDm6ne0Ka2295KHqKCqZwqGKLiSUi2js6z74Io2-M22a6xV_k2aBrD0DxHYkp12fIkWTQAc4YpgqMIi5eEruPBAH3j_YC4I3kHmTwChz1UMRcG
heJMb2k3AnhP5LgGrrKkgAkXjIE4NHqiXjPOuh9Me7H5j7Q4U8SBuYjGN1GkfCkYjUqBaB9mXPO0hgTSK05eWueOIKaaLcX5-0zkDs3LNk5KhOWPseKf3Aq5
5uEx7on7XqV0zbsZvPV8s5u2BlQ3ZVcfqlxs1T_GMk321N1r5zGu5_XVWnZQjm2nLeXt0OOTP2A-1ja7bxYi2ug787xx-cm3u8QxO7Oa6rx4FBRRSAEj45-u
ulEQNRO1LeYNxFYuG8PsERZ72zVZ8YdWDv71TOeOBrEu0YGRf5mH22XYGIveEmfN-FOz3fVeid355p7volMjW02m0ONhMif5c7BxBrp-zWsmGlU5Axw8nSFj
lt3vHuWOvTw_SFb5ZFkKsrPmB_E6AujO_1cXg-rB7svyuGgGR0_RjyypGlmHGcTO8IMxgTmekF6hDelO1Su8dHyX6BrgqmgVMRZYjs_0gkq-9K2vKOMhmo9s
oeFBknMk-Esh7rYXoy8L_pM8Ziwp1YAWS7MVwMVRjnLiAnStBrpnHuZsgDiFheBF2FSlOkqnSrhe8WlNcM_4scCimsjg1lSUPuJuxUl3RS_MNgzM9j3OuWBV
RVH_X9W1S7pLMb_W0XTPkFmYviCTomoK5-RXCNB9Nh01XQjdvTOobnbjh7ZEmxE090DMxISMCROojWfCutDuFkiuaSnL-tiPNEMs2QKsb38CP0N9bEmvHmWH
cCQXDhJd8kSJLsqMiUcV06rvn4zTjLd4IXccXca0oOWpmYTltrg6KXj0yiplDhA8KMppE9GP87FLdlqr236DKmKOKBXIkMri06CALnOnW5cuOduu5y0iNBkt
hwDS1fqHieZ5dH6oY8KLhjo-UKO8-m0l2rVOro1HPuHKRfuHmZx02ojSMSJEAboP4IlbXgtQB69XXIlVY8MT4LAv9qisKqovMRZ2lWO9EoEaSgDMRHQneCAL
cS0u5wHo9Sq98Y83_bml-1i
}

sprite $image259 [174x117/16z] {
rPe7RkjA40GPDdQFxt_S_ryGzja4s8P7r78q1n0AYqANWvOdRgrrMzxbSlzrPNqBrhtXDorwYi-wLVJ7eUsnMTVIqVyTGkkR7gpZqFCQMTZZeQN8meuBhE-Q
E_hPeSJIDnqb4Fg6ao2mlciH4aHRiuEmwieQRhMqla655MiMHTZ0-YR1AdKeQm1Xu-gx5S4QG5-TsLZwwip6qbUlbfyt1LYjEFeAORtwnbij_RDaE66rlW65
rVhEpwp_KBQ8mcfzvsVMhqCAa5d7cit8R80O-rTh_i-IkrYjQFgk5O8rcBwh43QUlad0njDt1VsyysFSJU26qxUJ7BpXzGLvDs_wYRUFUmTzTuv3V7qpEIw-
lkKJQdnzsw3jFRw-ED16qbVJHj0tItrvfBrTX_IJjmsWmox2EsX1nk0zNxDgn84sXBudvIryu6BGHjPtQ-G1D7ICzovu0yOuG_06rBUUu0QDyVvc-gRlzKKW
VTU2cBndQrQ_rm6Hz0sdWzOtuytq9S60lFuOunPz5x5cmNX16tpXzQKP3umwnW00aWHcFo_C1gs8yG6M0ERh0De9xRc-0CtCo7cyW_M4LiGOC2D9CsAYlZGx
eTKnXXa0a3RlUM4cQ5MCGGDQRQ1DuWNjyntHz9h1Y9nIwQ1XmleELl6s9p462HfRoYatqF255tWHgwQLCGOD9UMSEsXuQTnWvgCTQ_ONjwQK2c04NyOBcfzs
w4lIq4ek0CtnmuD30aqhOsm4ZUW0E1xtQdrXvg0zYx4PWJ5ZLpylQ6xQuoKOyVYymIbuFQmEMh5cXh-VEK1n6IzDN5iSjpKZ0G84UIKk1Ee7qkAxlHin4A_Y
1GKho-A_3EFNmxEyYjNQwYKT-fxXZZN3DS9-zDs3UDJt--V51S8oN_IrnmClV3f0Id3TTxapB-3LgxKjrzrQdzLNhvOGrhrc_dK0VSBwBy6hWnQs2c7dhvaM
jWjXdrup_c3DN9cTh--4p3fZhFLLh7grvgyPhipizJ7kdvvtGcPzCHwyUnkyi3cPzSUOkUmD91oPVRs-nwkjfvew2ReoEtVDUgczxLlk32AiZZ5wBIrNa1Cp
wu-nePPM6tcoMbhO-MjcFPS6UZCxNzzMG7zcPyVO2BepUqUC7PczKL_VQjqLOzTgtHPZaTc0-ZeoU-EQHHDMnpYQi3h6UhM2hHdjWsbvbzlHdf7WVm
}

