sprite $image382 [275x222/16z] {
xDXNRiD038HXgaj3bVkVDZrCuHgcWPMGGVW_v-d33cNa-7DXUMa_h6pvA2NiYLX83NiXLfyYouzoFVDI2lb2V4WGt_olFpFba4_4XmGfb20kv14fb4-aK3uH
NvyWBkov6HVoYHHA41zoCouaIA44yI6FY0_vH7m9KYX1VCWZukF_ttkYB9UKc_7D2V8xQ8hy0bat1X75PIBhjd6GgE8g41uILLon6IuI1Ku7OIDHnRcReIAn
S1u87Oc5SpR3J5B_f1W87uc5sfiX9gcF0ZK8SX85QXqHJXBHGa2LpR2ID2YYL02X9H4PAgBO4U4caMQgj1ux8lGa8krS1yKsmqyYqYz5b0eWj2JI35eA5JR3
ILBXf3WGPXAh2wmdjXb-4gj702NmuQKdQQRMrZC6K0AReIVHnKoY7-J7DxDYfI8PqDqxAOY2b4FN4f58DmuwYXN-ZH_Vp3g8K968T32Im4bv_8Yeq958ypQS
m4a9ROQVn9gM9luhnJwySPA3vhpQ1sVITce39oMm6N8IdTlcuwTQY-NxIRcvdW08ESddHxXfW4Raxaana60h6Ocqmw339y8arir_6woFQBpzDHl9C_LcWPiz
34J1MOZjDTp_k3_OKboC-bNe9zXN48sYdI1eNC2EbeULyWgIbWI94v6009YmeYsht7_AlqNIYm18FmS97vAhtaZIx2jMNaJIOexCIZqDYLJR4YwhwvMQi-Fn
0fAUnV_F0Ca6bEEGj68wcuNUnh5mOEUgFqNI5BotqGIf_GBYlAEaNCrNPKjOPl6lLiepaWgOUq-GGq7Zl5qYlYKiYNU9UbTz0GbO5z19ChVnVvw41AHya70O
Az5azLUHf5YZ5RKny7hahLSktHAsrRrAAoyXgGfe7GcmkKjYZDh7KKW4LahJrRNcrEvp_DUG282DSG7H4_ZzxmUjrsiZYTN5juJr-ZKI4T3ztqT9s6VJOhTn
j3WxFqBIibzrf5X8CZFMne58ufOmHDtMtUlb4KalVOuaIxLr8kbD058_yycM-IrXVEDOna4UaVHGwV-dCLCc4hcyLxVKpdrAdXtOqUfRmjKVa3G3wPi8-Jul
EV_v9v1iIzXNjtYMS64XkK2B0kbe956OKRPnLfUu9Spt4kuRIGNQoFieqHZd8QaHmJ9Ekf5ONLriIrZyQoHnRIGEldw8qGIkDev3KY8sakBNQbbh0AlReuIh
epUI9f36I1FFYDmEV4eUAyoKiY_xIl0ksRv6Ke2D99X83D9uo0dV1REYMy8OW2Yir2fVIZWj9DKcaWByfUPCT1ldOI0StIBbzltVzZzfZqgi5kl6HAd1PGHd
FqZpgGgTVFH_7xT4mWGaPugIy8M8EOsoGZ9alntjR6dQSho4II51Me64fLvYYwClaBp2Iv3qwr2o8HBwajCeaiunGSBoSQ0b4aauXjowR3Y4nFGbMi9j96xo
znTSHySraf3-bt1xlGB4km-IJ3hof_RSWjmXGS8LhbaYAUCylGu6a6MyBn5qIMkGS5FzGdcD9B18UDFfFK8Gp4QNBxiafad2QItXdP6GYZPEJb-k1D9LBmG9
hv24lYCIMYEPqokGb2eBA8xsMoIu4za82IqZSfd-4ywYqzek2VVV8K6hReI42LaOfmRfLaxSJ-50mc69v6RS4m6ILhfCPa72hu9wMI19EoBv96JT9QLYITIk
95oMICgn8H8cbLMzPhLBOeQ4vLaXQPa_a5sG3D9P6oVzVno1X4k0XEila1p7n_tuNI5h2RTmIRZ9Sxuad2OatuityQxhjGP8M5P7hMsairuCaFXR8jeumgH2
mgyYI1039Ew0K3-HL8fIAKogNhP60l7UG_BAauIpaZ2t_P4mtK4YoIn89Aa6IBY4hP4Gqpqaalz7RT8aOTandTFMnW6FEqYGJfE4vJbjBM6wcwu6vccazlzp
AP1mgRiYORgThWRc2wVBE8KVb_31pe402GRcGs1IzV8a4Y9okcTqbwG22QUc9DoVHK9UWUXwJLh2RP9m2qyY8NAuPpGI3CoNWBjNgPVwe8GFahW3ifOm_KB2
CJwAn1xA9xsJhWVcENKPKSkGSAxF8w7kgaIGhWVcAOr-WZ2GCCrnjcU010FpyjnLlHWWCOFIwUrquQ06vkSCiaD2x6ZFw7gDf2HCyKJ2iKS3999F7q3MngaH
4fPwAMGWuJakIWJfA0qnpYJXyunlZ8JOHOdeUisGiEoWE4au5bCanDtB4W4I3CntI3YHdOHrs0aGR1nM0_DpMZ15yZwKGVGiaiN0V0YGS314yZuKUZWublMa
99mk99cI9HB40P09YHwOBwDcEUEtFAef4eH_6WZgDKB2SYMGkBOX7qSsHuBS4gyTaZnBc8lK2oGSx3SEqdzoYG39g5LE8mqIZdqjuGyJ998V10894yO4WkwN
7ksHt8T2faZqh5wIstb8E9WZqU6VHB8Oc2yyIPYJDPBxK8oH83rV4YvIBwb2mWP8V461X1CaB4AELFebOR90ydwbs1gdJ1AkifKk9AyGJP2y3uLD9LobKY3X
q8BQLja0YQ_T0mdtqgubqVKeS4Bd6Y3nj52qXEENzt5IX8HZD43Y5afNlu8Ki22oF37baGsGUEtPfYLS8E5Mv9OnZsgBvFtZxED8KeQ4HSYnvyiuWNu0oSql
D_B3IF8rCDyvSJk5Wte91aXyLWgGr2h6pP3mgmJWC43Yj5AQ-6QIS5KIvco0n6RtV3vQhrNjafGd2IS393OBfJ-51By772S91qYuc27nTvpL4gOwILZE-3aP
IDXffK325M-jfIA-cIJSV26XPYWV64V--aOm3kh5e5xTBXGWQV9IR9ead54ltf2GqTV4w98oIRYeVXdL9n8ZAAZNedP9Bf1mokwGVDhD4xJL-pYGC1b8s5J4
I7z2mdn-a4VfKYff8mdhV0k97fW_ts0haF2hUa9YEeu3us1W7hDwhyeE9VnfFc_HzC1y52JN6JyaHqZOUYW7NP8o99phQqvm967RYLXThvcLX6iuaNHvVW39
C0VoVgKqzJvEdYGiEwRryf243tu3IBTz8mNfGKcO9WbBlOJy299Z602nM2WzVqN2IUP9SeA4StuVoM23FMDKAItEcfqaN1wKyC46uZLSAJLCWedShcUCmIwH
s0F9F_Fx0-M5f28uJkEqTv4CDZY9s5UAdjIhVP9mMqZOGOcOLmfIHyvoncyB2U-sPv1Cjoe5vn9Y-U3x4ZwCzupzAMKMSefqIJWbZMHN80Xzfr8oXRSaV7Wg
aVSh1GarB91uEOdOxvuJ0IGS5aXstJC8tQmKI9ZYgQ4pdiLhVqefa32G-2uH-qf92oG6G8Rddw4h0KpYds-SmycUiRysq4ZCIiGxb7WJoS7am3FMrmOta1p3
08W_9bGMI1pl6VjtiFCIYRru_GiPI0ok05matwqK874lNlkxbAAGR58YzjS6G6Bo7--EbG8aJm1X0DaMIgqC90ObuYcTwKyZK0o-ZF2M6qnOa1YSHBQ6Od1j
jcUbOFSOb8ZBC9Dz_cxNBcWW288eY0Q7mR_R4r0TlkLw4dwQ5jf-bdguiX_74g5IZxEVgbaXL9j31EoPW84SUQMi_HgErK2pPw1P8LIi46ecGlOCPIk4cecG
FHEmGW86GYOIS8W4h12oH0BDG8Y1gF5lCnM-UrUxRi_y
}

