sprite $image411 [222x148/16z] {
tDW7WgGm34JHiIrPgd__-sxsvZmWmEy4_PjSBsTgVPZFY4nz9JDZJhSnsiipjMuUAV69li8YASFjMP5jp1IhwRTMPVWp4eUd0FqJ0EMqUnTsJq3_1r1ulsbQ
ivNs_q1fxOPjKw03W6BShqs7WRnJdw-s3Vk6qE4W-WtQMe3EW7pB0xUGxTeu0vq7ZIlZ79qBkovk8csPj-AspNDKWN55t40bKAkFQwh2tFIYgpytM-_3RAeE
KT8rRAwn11MYdntcaIkh7Dvw7-_qtjhnPIa0NOdr2p9ZskZ7f5ceDAngHrjfkYK0vV-lJ6EbtHVmVu6Me0S0mlujhRb0Jm7vBtshxJ50Vzit4jMeNz5wW9u8
PljJd0dLg9zXMg070_zDN1TwDcRXV5UFADn9wf4Rnqb4RTprrvwXRVnmv-oeIltCrBHNNRQlwm9jXRddHVVZYjQq7UA7MNdB6qlNTjvIQnzARiCm440NZGJN
__-_6K6MJzUBaBR9TGv7Js1pgUArbeualzY8_6F5azMJd66VtYatTNBCendVILlnWeslaIfVtK51ydp2bMd7_igKTzAnHGa093i7UlBLodpM2M06mFZnYpiD
EaR3ci97PB-iUnwwyq6eTBct--swx1YOUSG0oCXxdkaU4K1l0OcdUeizZtReAdAv7phE4HmPVEYIhhO707GZEW-TxPNchRxoHcdIqO7LggkyrYbUnawwcYFg
MxbLOhRfnddQzUl8qgtRXxeXIRkB190sNSBPeTDNgJKzPye6dNu4WCIMSTTLj6w2nQvjqLKqEdJ6JmxgawicrQfLfIRPEkaGWYqv00pjqj7c7z65L60AA0tg
auVE3KVC04bfqqN-6TtvyklNyQHBR157nLQVRkJgrvstmXfcQvnrjNIi9ntBPOK6HgDkhj-f8sa0yhOffWFcWCpZF7heoZCui2KFNMVwTPLTLueLW0KWcoBE
EdhfgDNL_wdBJRV97C1yLJlPZxt-R-diMxe9eARTEka6jWIraF-KJh-g4m2Qg3ZFEi4MlIF_APq0yCzq0tjqxP9vqaK0K1oHVqbNrn8VwqpZq55tGMNNgG2M
g4ZVMQMIR7X4FZ_U4O1nX8wgDP-Vn99U5QmHt5YxUL4N7prvaQ6eZ1kPCqooF3azUT855xLC0XsDkd6n6mMWdpqVBE4gsBAYD0xOqS94kVVZP4JhZk2yFZ3V
xMCNUU28dBxbiQhaLaUNceragqulxdOVJhi1m9CB5R7XUCHAzxWtN7v_H1Zeqs7nQkdq_HvKa_kS4f_tIUgen7FTOar4xtr-_4e_pC-lPBzcdOjCATLkn3pf
dlVOLZic_8hE0EWdjaTXrX1Wy5wWFEbUJrKsFO4i5zyOAL-_pLnHZJa4mVqNetxr51DLRvfrZ8k3WFn9Spwg-gkxyq0I8uI1e0GiA_h__tMsLG7Rjro2wHyC
GL8HHhCR4U3jAlpA-7Zui2en698G-TLCZmpEYb1rByupTrweBapTjLdi5wuND-bwp-0IYYLbe3TrkhFdbgZjFQxPPR08n89PoZaKc-0T1NrKgIzSyqqtrpT0
L5mQric9IseF03LnIMbt7BT6eJtnumWaVaygV5lZTdj4uw29Q_QGel9bUSu96s_TrF3cX3MPsiGs7enUR17VMndZRcxhT7PLbjBMgMme2qPCx9UFZokC4T6l
cig49e_cRedMvD7jhIbxdmObf-UyOedQsgJQ0eTKcpHx7ppG4vVuZQ2ufCDcPmhhR7OEJnHRuW2FEEZs0VWLWDogJB8TpjO79kkKUlKxNb3C0uTsWIZyDmwa
A-oMsjQFSQ4lT3zQEp3vyDAJKIUUnUTq1l9dSI3zfe_ewbHv7i1BpRvg_CCKEdfr-rHk5WEub_OhuavCLUBkEpICyrTdNY-rjdPzer_VQAsMuhO75miJTmp1
Ggrx2eq7pPS4fYuNfUBK4TL42AQNkffJn-XkAlYaZjUXewlDAXFlTna2NMtMaTMMwnBkQchuv4n0QzD1N6w2TB9Hi1mz7uZeqOwJzXK
}

