sprite $image424 [130x87/16z] {
vTg7bkgw4WJGQdLGLvt__z_tmCnSdpW23BvXhpYnQwbHSC03p2DhDZzqpraPm_0E8wgf3M-q8RlI3Q_arRhWh-c2CmTUmw8byIlN464uNbBY8ebfE9QtnCro
1Xof9Dv9we6ZM8iF41t761GV8WMEO1GV9SS1flWmqV2q59-WmiDiN1V_vfCCZx3zulySpQogpF1XM3HogyvZw0FP5GDViMn9V0b9OkV07uoYn9UIE1s_OKNn
3QJVP0YARoALuKSs9RxFpzkMKtmhqKyCi57i0uWdaEF3u2b4snr0Jg69JOadKUm-16VsOOgdKJmt11Al955yXFgUJu7sUD6yKkTKFpmZRJ6zvjY9Qs7REgZ4
SAIeQNihSqm5roC7FhkDO4lIju87nZQxzbOIDFAE1DNpeWV6Hu8PcUcmWBSqWTbTtJqxbnAGOzwH879ZMm8237oQjmJ4e6BuMW95Fzo5cRTCvR2gkdLX9E0S
68i9abnF47MJ9N80W8V_7xpzbi1nuR1SJ33lIU1_2R82Y0I0WP6mQm9h0z80hyK4_U35Zv4Yq0rFE2mGeYQWX360cgz8aBMPssHee2UY4C10RGcOm6oWjp4u
a0gOmow678FKbc0uqW2qFhim0eZb1AivbR09c07WmDYwa0a0wO2BrmI1WGlBrGHpDO5ZJA2_5UoQG9e0ObR5JA2uTG7eCiJIRDoabdVoQC1ZmEWOjzaOvGEH
G8wu9XYbWB7cybnmhJO1rTZqW543Ljjal8txDG75EKhaydgmTaXK6umTFdk6srOkg8PN1n06k6u99Ag0nGI54bSKKjJLxLGXYMo9Zb81AKqOjIK6u5oWm11N
g7TfgiMDIAb5pIB9xltlY0l6yZbH_2I9U_hydhJxdULZcl54IW08yJGQknjs_ysh9WtSfCGJgCwzWK2rdN0RQqSSlxYLfnFkOEnOpFU541s_Ofxpd1RiKNmr
QHf-R-hbzTln9wbNrm_ycUk5rSKP-5Bh9RMtyWERzxUXPuKRrXZ5Oobndz2BDk5rfQDl6zvjwk3bxym8udZ56m_hD0qFig8k-0mnyGIBwkPFreD9Ss3P-Xej
kXU_J25fEWuG-lN6EdB-OJ0aiGRMhKyACNvuFOhw6RlSS0pxwcHXmsF_ba3FWr_CIlqq0BzX5pXUwwTdjUyLMdY_wALQ2mrunn28QJY3KLlzCfnZQgi_S98G
TMPz34gTXjCOEHrdoZIym_y
}

