sprite $image279 [312x312/16z] {
xC610000080WXFrj5wa200000000000000000000c9txq6uK1g8m70EQScU4tlzjLo9nIEA67MH3Lh_RzlAT4VNi_fdmdgJbjKOIVCIK5jOY8iPxoaJBv5fC
h81GO4Nv94wtQr5Xqw0UZUXZvDB26fl7adA1M-JMt1GWYz4jmn5oSXEk9SG0GcPxU-COLPVlLDkuWIQtS7GJahIavkOnckGt1dQuXNDtovNtfxanIXodJ7Rd
Lh3cYjqptLGiiq6nBxU2Tfe_QvsMD8UFb7WNQdOXho_7f3X9Q6zgfuIfSYGuYJVY5g_aFa-NVtxR5x_dB5JzQ4F7lV5Q_ebsmTDzJ3Lx8mR0z940ohHrjVY9
SzMq_kKGvKcEMGiRRs17kOZjrXgkVcO_xr25AQINXwlPUxZIC-2OY4MHKzd8HQG5RBZUCmv8gCGvogKjz4ksadc1i-fkfVsuuMR9fiRAR0BeBjnKpR2WwImC
CjHrOuynRWVk2XipiCmjcGbpNJQBEUVjkp7hOhTaYPbhkY76JS7XKhAK3McAS_NO97w4ZRif2-vogpLmRnERnsDAkUswCMDfgIBSfCQ8SwuqjKqtPNt4ZIkS
9y3YzznKABT5DnOiBbKQE29HytWsD-MNqlr-t6QtaPdIIh427g_cfiBCwINPsKHiUQd2mB4eScRkrw_5AFDstC1Oqmtt9oVfP_8zF5ILTIgCEqgtu1Grsv0R
ItDxm4rP7_mZ30-vDRVqNxi9ut4tlkIc_IQIYcvInUrj4t4zDtx8hRcfFkm6aV_LhVIuM-xNReVkqDtRiztiDEJiZjPswmrBqoceMlzajtWQ08ztjBeRWa2H
q_8qV3gQ0GOpKy1Aek304WZ3yztyHm3C5_VD3UkuaKAK6IB2gWn0GX0HLL5LWwd8vAW44HLwZTlfEhNb_PWtNSDjSQhlJzs2cuaU1LKNkN4kJGch_DfjwFex
wuOjk1srX7CBt7XgjUEtVc2zC-atuIPM0fVqfXk_Xt5oIokuYSx98hTDp1juUXUUMkgcm6fkc5B9iU9skWatOvW1_1vUvQR2pC8ydyIeQdbjratKSCCDxtrt
0wtf1c9MW1Kv2IBW44X8S99imqt5yCYy6Q_gfegIJc-YvKrKHRVYTf8nPZVpgtrp4qwhk34BAGiJ7UdqJ3ZoliBjRA9VtEBLlhdnIcuI2XiHAN-uqTlFg7W5
0VVq0ZSxc_B2TLgQtPInaXijS1E5K01rGP_lXhDPKPWzhZV_E5PRSPsIYAZeUppyJ01L5WZ9Tjn47dApTTo8xupwZRZPGswoajkXEtRevlhkPuVFdkxcPpER
FU0tcjri9RUk6ueJvVS9yVtKFPHlfE7G5y53_iPNkiMpkJssFpLVoItqNO4gPCNjxV3XrWjrWOdfq0slTllTlCLOOTuoKsuehycjBupbxL2UfGtCczjf3vul
M5h5hJ_TZdNN6vfRcRUUxghVkvklv1RihhZDssMtE8vZjBFHTjpiqyqsuUOfZJ5wtBpRVBrtuVKtmBsUMsQ3Zz4cE02RTRl__a8og-OMYvl0P9pOFjgcsmGd
I-zd8IMhjryOKuhWOIXk-DehtIvdjkX-FJEx5xTKpysvBwTUe-5RBzkV_hvKocvkNi_DGvyRUCHd1dkT6txVqSqgpbjqW1c0psnpj5yty_pqYcvkqAA54xXT
prjoCqlLt1p2OGW3QRIPxPPRSpCL7WOY7SS_v-QfcfkpAQi6GHhTPhJzkxcRrNEpFhe28fRIQFQ7tAomLNCBXwvZuI0MKtAO_HKtCqD5j-4mS11YLObHcKNn
9zpSt5CrD-Wmk0bKL4c4cOZuBxYPrNHJuPxWLjmaCBDmJlVdPiVchtggvoPAGJ2wgO83CvYP6BjpioyXDx7LStELWJIE4L3b79MN27RcPj_TpDnIgka67jXZ
dDn8E2VC-tOhOKnLtSnb8Czm1XNHGYQimljs0v3gkZd2493TN40ipAmioljsGtqtKne6AMxAeHSvkkdEtF04DuhZcA9DkO58FBf1mY0v5O6mplS7PMV78OPA
RfnodsvkG8nk6gYRt5IDYR4VjzFgkvLWiU3H44G4gW0JVRh5NRjvJJV4Q00FWwgOmes9vEUyDJVwweRtUOkgqW-gS5W44p7Ek3MtCTeSOeok6XWQpMA4CBFj
tgrKoyqjft5qTnKrSyzIAimNvgsvUQd8JMxHOuHvBgRHvnr3KPpTcbkAFcKv81R7-96xYB1ScxVcvjF0nJA1xWPXea14DzPfSukMAsvHPGWvAZ6pw4MtvbQ2
X30CVJVqXtSrdb9CUJowDRUWAi9KOaZVzrqfO0ZydeW2ElIveP3kqStNT-k9Gcx8XVdVTtJvYuKfXC0Y4lfZEtNB5JTVqQsWbJ9JA6oV_-7KsqTPSMh7RiMi
jAhRK9f8fcaxOirk1Uv8r-tLhMHhkfMwgM9rjkFYBUtPBQterhtTrQ6kMtDhRisjkVdpt9fRSqilTsjkXyCxo7rkpQqhnxv3JqFV_mTklfhRT2RQ7Kf_torv
NCdjtdRkblmnj-OMN-JMxzij-IfkeZU3VcieRisD1wB0Uh4GH9M9Y4c1l-3cgxX9A2QubFOTGuMPHHIvtRkbLTo6S6_zqDmwVg2-kTLe-swnkLrDSdhwHuZU
t2wbgW3dvCmVuRBROHF9wzo4-KwtBRLDjzZShdNHpMDpkvgMphYbvhQWvbRr_7HfAkM9Bq-L_yCj_SfDWXwVSdmglcUvqyyIyrxTtDCAy_PbwbG5Yzr4TkkM
hhYjbUh9vxxNwJnkRRzWjxl2rjokTCAsbfijQFTkXMtTug9IpUgxkSVKtExAfzBzjNahQfNTt0omdFyPjqfzGyENlj6DpUr79sZdvPhRzowhJVb6tPPNrSrn
AM_pThQhR2LhRkUwpbQovdQc6smbQswd5RPRMTild1GTjxCsRp-BM9Bzdsxzq5yAkYZqP-lsvlQFk_F0RHw6eN01YYi3lVzf_w5KUfJP21bsriCmJOtQ7yJH
JIHSgkIaKlNZPE4guSqbruc9dicj43jNgLTPlH6NUkstYZbjo8SXSwxoamHEx9Rdv0zXVg4AFRCk4AdDNhZnal1I7DzNPqpCfjpWZFjTA7xgUQFYflzbxMMg
tEf5NUlLcXjJr0r3OSMlsooFQDLuKELQRahqF6v4ucygUoutAYleAPMXF8_R5nLvHw6Y7WOzgYuGQK_LCgGPDfJGSOQwDOUUS_YuXmmp8Ayor7Dfwv3zy466
gxWhoO8LRZVWjX-uzJVhtOXo5HoMPemWRUcG2JVX88lS9723M_CMdJaI7BHNPjawJeaOT2uzLGRKsJ5RUpatXJlpGakKEf6ltgANZRcPFrWMTSjIN5ren3Dy
QhC5DrG5rzQOzKxDvSUmRc1EbQFbouQEnd8H3FICk36OU20T7aF3XaHBRA9gfXNTTdM1I0mPcgji6Oum_6mUqsHOt2-lRefnoZ2b-cMUu6pvgPQgxvhSRBSX
DqD2EGS7bE2v2DUDtE0VUObxBlHK9cJMZrDKXPveO27YBZPyPbWoL9fYdEfe8g7bQuEhH3Coct5J9EXNL6ER4bpZPi_WHbHyQ0WafJf4g7MNPXSdLrheOPOk
6ryyX6K_udAIu2xWTh_6ge0yZ5INtdNcoWijpPfoGxSBXF3dzj1TaE1eHcOZRgPoaY4zpqzPXeHPEa5v4JS5Dutv3SRey271xNTPwyOfgi9BApMIS6YL3Gbk
zp1kgf8KAngU3gxfO7R1YkKQyYPKyI3v_PDRHK1ueQ_sEVtct50LaYH6M8hRIGL8iJaRXBm9JHgqR7YHw13yqW_SSV-G_4OaoaasVsVGqfosF0rUm0rAtCxc
DOlF0MxvmEqFgtDZekddtScg1gpfj7bSHsL6448w9m1K3t3Bu0x7rUEKY3EiPDwelF5jKeR6feQHu38u_8pd5jpCkmHHewa7lK5f2qIzB7kDPiEGFgeyAEG9
6HCSVeuC_nltyFzsRMv4nI76EmbClP-RNiejroF99nx1ZC-uOWTtJ5gzBX2fGqWWqJH8Rv7Z4tYO_xsnsKQjxavj4o-GMU1ss9mR4x6ylXY2IYcqK8UJgAtC
JJvBaK_wDObLuzG-IjyJhSxDzv-W7R0zIlkFqFVVzk100000042Gl_KWLsS00000000000000000000000000004
}

