sprite $image306 [312x285/16z] {
xDe7JYun30JWDAzBkFzrgNujmdf_Cx3HV7JKH-lHKCet8ndbMj15LRcNQq1Z_N2qSYceX_v1vJ8mz1yNrHnqrXMtSX6SwEgefSI0D39A1BfeJ7e9O7iihgev
55kCbfg38HgwVfEWsEAQWtRe5Vn7Bo2z5XNeejUJWUrn6sxO7hSvAhQ7IpXM5DkjcmJ5Xfghf8z25SMMK7CuqPWqR8_FOPEGQ0ggs1wfcmJ55cyIR0_Kt13D
9mCdYfgxRNkWvaY_5bLiZuIQGx75kA7O4ZR9Xji3DTTPlvTqd6XEpM5xn3M7xP6mIR0zOjnHRBVX4nphq9-8AhP7GitXH6FSi3r--2OPqi-uFMBqPIECMyBs
sFj7Bp5_kXEARUUQasdwRYHiZuqtYSmvBNwwwwWvnPPlfESspOB_VH--YTgXvyCzEpTFRgsvBlvDqdCwQc9kpjR5NLdVs5JHqwBitDQQg-IfJTCpav6Qstgi
GywVckEMbzkQ7EkRA3NKt9gR9_NV4yKcaRcohL9pqjDpcsPHQgYvE3Ud-w6QdvlfXcJaFs-sPt8jExVuaSCcYNDxUjhsaLDApUrfusFjURczYOyLcyHpioYt
QQYvC3SRjN6Gsvo6JHBankLLrpMtjmyJDHVdHkKTsPhR-tlKNFoyVUYsvkOVzzqazPxSj3XQStEekKzpcxsu5tRjGzbj78R2C3j0d4E-_zjkSQ59hnDfqoqv
qtBxlTzmQFmQrDTk_AJNIxVgrmEtkhNMo4zwhVygiDnmYnjmKMljwDVSjxhXTbh3inlO-mptcKbMD-9oMjD_vxV-Bznm_Cmagnj0Io6-U5relI-l3f_qMjs0
kylgnZODSf-Pv8KRNhkHopi-rznUjo47a9_qskishCOxFkcrtusFzt_IQxyRfckk7JqW9FmmjrHm3uX-TJjpUkrtinYMW3XwxTVyWzn4Hq0iRgUSIVQx9LyV
0T7kxyKvqslRRSX92HYGM0BYm7BPVwDR5DpSgc0920otyyqassx11IL9bbAm4H37b9FuRMxEHIDPNCH6G9nh9jbsSnwaflILW6ZjHEcrturaycLrgpUv4H1d
kkRsknLBYnjYiXjSEqD0IFWsDs716gpn2WcqPH0-nJMttmsKnGrw3LRo6bvdU92UThlLU7SZZOjRzFe8YCUxmHEarxQRYR-utLLWz_-A99ul82JiSuD9Njny
njrDvWDube2esUzogovAjidDUG59f3JS1jNr7MT8hsstc7rMdTpSDRrAU1w4nrUU8BsstN97z0cpcuiWytBUrjmd3x-9ytKt-zUjTt51dzmGmneG40ouTlY0
g7cFcxdeOrtT17brYw5UfN22JHp3FZTbzXd3ZOJoALYHv3G10NAVM-tTWW1sSKia-UI6L7X_H-_jo0_IZTnsyzAkRbq5aFHmmvS3eW43xcZNd84xtAWXr8UR
iiQhs_qpz2Pa8l8g88vqpGsrRJS0nVl9JNFnarjriTxSogk0EDWc3iXzRhLKMdQftTt4XI9rSdCkWoH26cwJtA4sSGpSxGQgKQANTdCJyL5rTdDUIUQGIU2e
cpYh6cbRRhqB51f2khffPtRHPZUNIVfONmR4yog_7K6DnBPRXO8e_kxMUt6-O7Px4VersxBAttYNEm3RVZVIRBYfAo7eucPgpmETrmC4n53xPZToSaCJ7p6v
eK9MDojAFgto4qFk3TM-tQrIojMjTqO3zEv6GXUt6Wf9yEq3Ob7RwsRroKrzvjMj5mEa-BiRkRebh-FjzrtbD_3_kq6hAHStMlGYmqrPatFbyTsquEQcgk--
YREgxNSZJQsMsUsINixPS4j9mkpclEBY9gAlDt7UHmxajxcrnghWvAPQ0V7HXblmHIeURkwQNkQJllScZf7VxjO8hNLoQwoLadtcrIrR3Q7exEQSaiXHl_mW
dN_y9ew1t-NM6ardjqj0i4RlRswzYGzrSHEoke353Sy1CUJUIcs_MslaugPGaXhkRhrdvx8zkKcgYvl44H3zJmy8aD_lrdjxvKRWuUPhz0MBMpLPt93z1HBW
Kq30tkUmxNVhbx_oXHivkRLUGvZT0EZYPYf6R0J4cwXjkmsuzWMt93UttlxcxaxNsqY1BW2pKyk1-x_RRr4ZkP1CR3Hsfv_KhvdiUTEWEgY40rJptGtGftLg
HW_jPu4l9gV03xcrmwr1bPMvMJS6-I27MuzG9Gh3xMMKlmQw_2IE03_dDkeU8BHQDsZsENwuWREtRYN9S6FYYq_YYE9tt00XbWhZnW99pk7Xba9DvSCjZxCw
r49ymYJE6MhxRhTkJgmRAQcIztntYyab8lrm6vCux08l0iGbv1JuJRTRzAh6hNTcrEgZtjmq0iaNicxECI0foTS1GkNY6zlxRWrsVwkzzmg2PE-6M-_iFUcJ
MmrH9pTM0DSOvHV56swIGwGDjzRmwWPmVBZru7pa9pV9ChdbG2-VQTKXTr4rwpPwrIJVTHjTwuiR0CNTpIExh9ERCazkMhoC0F5N9t44UC-jZ2-F9HjkhVtP
BVIkCLWtuCcDYjpxj_voaYuNVjYis_p8hTqCtCgjjCEjjwYgwSDDTN8hFZ--OVeiyDZchgistDYDAjzpQxtTtKY4s-G63fwC6t4SRkFN5BsxSPH5W3XBJl5k
gRrlqFFttDh33KpAFBb1gu_-mmsbUkiM0mytglh70A5olOVDkjaBBjTkdty3b5ZOkbLMpTxZuUPzoQGVRiubkRcbCh_0dXiWPhLzDxl3HTbqQqy10Wm62IJu
sePRe10hgN5plW3W47Gnoc_bpbFRTzFgRsvXt-sGgyQjTs4GXK27M-oj-CJMpJa5A6JzqoZ_Rye9y2DkaFpUytOKT79h389M7uPRxt2kw9DRJdE0q2e0NaVv
LQxsiDcS1OxUixxdrl3YTeDGLTB_T-lE1qywkHNavyQaZ3zGsmaGvwjPDmL4TT_D1WXLt89-ex7XtTp2pIsswYDRjmgQtP0JLW52pkyzzdFzljj7Nw8hjzwH
awe-tF3afZch6UN_dG0XYgkusODqiDPdDv_qSEkQLQNuXnim1tsVpAsQpwFyAYUedUlMFjo8XNHoWoHVuDBTJIJFRbN7VrREVxnLK-G4jJFTveDqOPhS51oz
oyEDHLEDritxgelF0kjFNijlrCvsQr-vZKaSjMw5LAltyd1pFbSJ8FoOn44A6Ly429MJ7hRptHgKM8qRDs98yWd3BTvcwDIu7QE75CFgKXmhTm4rGBxpVlsE
smWGrgrt4HL9FgTZdVPEFj3a5XH8livkkZ69SweQ4FbFRW-u3JSR85JrrWX3L00A3xUk8zqRDyqbJMwQU14WvAHGjIxdiYpT5C1RRkOgU1bkDm9-kC6bv8jE
RWLF-rlrUKZrEK2edFMmhTsShx9o6t9josr8V-866BVI9NWsRc2KsKtpMBZQrm7YVBNXvbmWMQnJ0xVhrjhABRR3hRUILVNX1j3afY7P0F7EjVoANoftLEBF
tSPYtNAp0MACCCrk8V3XrgMeCeNXzXeWejdmT3z0YEANtPpFyfcRaTjmiz_0f2HgtQ359_vmWnPltIJ9FK1GtGWGfwbPjtcRU_q7nhjkK68fanlV9d7omur3
JTPjdDL1IwdhQ_dLo9qFvqn5Ud4pSljkTXB7k6ab0GTFxU7cKoKnRkCseVWI8EmepjToSeRRsEQicuNJ3wQ-vtQBNcBSf0j1Ye_2HPN01SddQjn6WAWf_vS0
eUtNsDJDvOjOjxbJ_of0_74IHwnR5nNLxCDmwrs2hvDR0k0zMpVxIlNr8oUjzLzp4sDcjZdSwlNwIc3VxIXWSbCL1IJMkriNvmBFRbeeJsxYgqxVi9OJjDvF
SXiLsUuWXz8S8BRTp2IETGFKkDNYaqnkLSlCHFxu1YdwBFUgTgRRa2kubuw_ynmWzjq6_hCRZ1jrJPwD6-J9JQdAuUOAi9RJG-rqjsF9Z6hTRYz3Ri_D1WZv
n2sstjbHxxrKLNgu0VoqJfCEjmp8Qh6YzR_bTfnMB4PU0EovsG0XeeIkol9ma-Yf7MwrghAauVOyowebvU4M627havoAMQL_oStviXvv0R3bDWS8OHRh1gKG
yeSRf0RhHkEi3bA9XblAsVjI5Y-jqlwQsnW3dwVI9iSttQ1CGjPDw1QrwiEj-bAis_tfbrJBpKr31dklDP61itBQpdQp5MKvylAsst6G3kic993eI-kLRcx9
XqfYt8xRX3JS0uGA4BoIvgmMRbgiPxlPohAy_zwyxxpbDWxIZHkw4fYZftAuSQi-ridD5K1pCYTDmMj9nUN9RPRxUsuZAThbsHO1OiEjDR1QjoxAqEhTSEiT
qMLzTlDUFjmuaKfqcJAfSREBzLItzJRt-eLa0Rpdre0NDq0ptzqwEU-hJcvY3fQ6dBWQd8jatAoSdEgsxadM0MAex0S8wpQ-ORW9-S2J6-c7crI5bk12S2Gv
gN6pYrLFTxDLT0eGJrkUKTaF46itxQquCMw02H0IYoYabE8OO7bsKp5ovxcjjxdM5W5YswsjtA8URhqdLgt-uGOrRZMCA_lo_QTko9taDcOH5YVM0FRSMdzy
0xEIpcwQVKPzkB7cXvjfltDD9AIt9q-js-jYFTNjw-Wr1R0jD_iDGY94rWtWwCE76sgDBsw0vC8v7dULi7MRvKHnkjjwcpjgSdpJhO596SQDI47UqSCjkroB
Fhj1Qw6KcG59l71J1VwwcmkaonFhjzqQb4d9k3LcrUIJtjqe-a93ragGfX9I1O0hkgsZbxs-SgYy5I2KYd7h7GIMv4iytBHp2FdL3U2SYQxjDYe_1OXc--3t
0uHERft100SdmwstEFxDdYKqbQkwhQFNpmM8zeaRjEhThMUNV9PNDwXSs6rzmdHJcllWJRSX_U9sA-FM9FgwbBY-szoJs0kKWFyU8DPklJVoLtNRxqdCteGV
2H3K9ZT23douzHukxxP_mgIA_n8WXXkJainkMdpKRxi1rtKRqMjz-Go07JSxxA_4GdLoWsJll-Tsx1jNTHkLz8k3z7VS6eH4hLib0KTNl-E6VblprtPpllod
0B4QzWTFWPMwaABu8DzokydXYcxhw6K3X9e0iUVM0AhMhJS2Q_7fQxSsuAxejZudqJS3X7LR1mX9_Xlxsu2xfjiwUZqVfB_brZyF4E2n0QpTS7V3rTr6Jx8E
4Dlxsv1U10XbKLsxcGVkacxhIPpsSf3-dbjRk8brism3hbtVpMvpouDq09jkTiYkWZ2vGUIBZxotoxhjJ-9ikTbl41BcPjq05T6bcnvxAgxjPkLebbET7Tzp
0vYKoBZfw_lnduGhlRZREdhDVV2xRiSaZWqGkH0J4R6kO_q5tVOdSN03-73hMsxZDg7XTXihz9bk9MhSpZiFOVVpvIkU0qHx3H2RRgs1XriTB-3baDD_n6tk
ILv7-Sqi_vPRmwZaHiLgbkhbtVQZLri627pRpOornuydEpF_MsxEc-Y5nIZ_djl07sufUkTS_DVSx3Qt3X3xRgqTRgbMpZStmJ_WjZM9i-VMh9iljIea9r7y
Esxh4wPv4cV7RTHm2xLM7Sls7tGRqMizol-kMworZkp-RxhDRr6l0yJxRlrlk6boeqxRvkme_pIAywvRFzrDYp-1ROvUyoYE6UNVTQFU1tW_sOs2Ewjy_KQ0
s71BjTBm6dlSQMwIJl1QH2yJ8CmapgvRmu1hxJGtpITOBO-3fm1X9t5st1vTI6_z93UjtfrVlYn6-OtSzlDsfDrsYXj7ztSgrAy3nBuRMkyRRYTiR2T4BrNx
VrjktIxx3RSBzXxxny6gquhzZbkukxNJtFIKtkFzIPmDjzgiMzzmEs5ZEoDwpPCu-B8HrdYuQMztkFQhRfhTLIgAaTiC49eEDsgF9wwt3RUBznxxapW7mfrn
xLQESwJw6CXklxXEERXhbQ_wnm3Hbcxid2krLi8OuEaRRYVq7YT6BtHxaZxaLcwQZWEHokZzjg0tNazFw3tEZLwgtmiGu-AfN8c8SNFh6tdX-ht7_WSphTyw
GAWYE-VBUDFvjzmukYjNgBeP85HlhOZBDpWPOVU7tIHVasjz7AopuwTk1roijF5-_Oczn_dH2_FVKtNXTlIYlcoudTDxdD-Jh4VvjJsFf3zQX4oyuNPoxt5-
z0BQ523mYLlh75puyVVh_xUT-yoA88PX0Boz95RkVrkwtWwUX2AgywmRyFqmCkEWTu-_xoIT1SA0bLl3UL-5xyxQDvSOdMHnVaGdmBaz1uARq3s2Z3bhpHTY
ysuC13UXUmJe97w1OBmR8xW5w1x2mqn_oyzuDqPm4xj7bDMBUepW5hbxw0yp_G_-0sxr5415liGn_8nRFUysq-Iu6dC0eBc5xnxwwcMB8am8mKtl7b5NhuwR
GN0JbwgugzVoBR0n4Do4fIfo9x7b1uXR13UXUyGVSzxD8Bd5xnxw9Gu3mKrOgaAFkJu4FkiMltlebpW-OpVrY7wkrKjm4mRRb6EEJ-K4D_bZSlpLYswjuTDk
HHbiyJk9SslekW5uPIWSiasMtNNfvkN8n7-vmWZTOyfEGZVAzTmQh392zvYoaz2DyMu4fPkmL4qgHpSAkVb6Jxe9tMFQDeUs37fke1jVsMOEL-8mCBhTJ6tb
bZcjuQg7GxhrEadFZN1Zjyo-Tjn8XR5RvcWTDy81bcx3rQllnhzmZjropFNScB5Rvb0rjyp99BVCzgAvPNP5TSlLQ-nssOoJEHR9BRCheblMu2AvPVONrIr_
FqXkcUsfg6uvvaIt77EgMvOvqIt7dEQMsLsAw9QTH7BBR1_7d7I7b9taPqu5xm4
}

sprite $image306 [156x143/16z] {
pTg9ak8u40HGsTPLcLdY__zseySL3kYrcOPc3Bdt_K975c8d_IvBhrFwo4pL33r_8gqOpCpGva-JvGvR0_kiZPrRo49NFkcWmMw2ldp8TdwNVSonMpfiBx0o
lNax6s07WUNtzqRaSpOsUkD-W3gzkpUE0ojlxutZe2zlxesFENPBVq1swXYRAc0F1fRVt1lF7xlpjtE_JyxlZUVwvFpUE7zZyszbqIUVSj3s--IytZYhJ-Rf
YTuuvzXLzENbsxdV9myVEm0tXtMwtnkdzeaHYCFwHsKvUkFbUVoPRUGVNOus8uwty-m-CNBLzIKRW6FO-NrYPEWUa9tK9yR80xAp-iJ8BNOtvnyx8x3XS1hE
olJ3TLjr4d6UhkSVsAo131i9VCx66fSqjyscKpUsJd-rfLGtcqvTEYltRJskHDWstVlx16JzMhYmqTqb4f_G9o1fS-gRRRYap-WJa8WIYJsb99vyxFA1BMIR
JUJgUtkVXElQ5h_rz_R9lisQI0ttz_R9lgsiDaaylq-ERP1abPGKsFFxPDycpXco4dSY_kJvnsv_tUOqovRL9hvZK5W-jaso5hOAnQ0u-TZjx-cK9WfXAoRI
XyuU5AZJZWrzdYY91XUhQRiKqhbzicD3pf2eaffKJDkbqDaRc_zdCxF59DMKcfP-O_EpnzYDZJHSobAnsbgiMuz1SVAnutTRkrImgdpP2AwsAaf3fmuAKD_s
bBKjl7HOITqbec-sxKwSeGEbMni1s5BTWBeqIK9Qp7iH5QkcKmO5fHsRX5ughRCKkf3IuZLiX4Z9_xKEMiDlizvbej7w1NFfNxPPrcEz2aIEVpmeGEtP1BYC
4b65EYemfKN2QaC19VVunu1_9TjVDmDi_PsQomM6FcL9OZCNAdXxAVxDGTktoM7hke5j0OmzPxYedAgOmTjB0Rn-qOvjBb0YwB2MmKuiNM9EoRY43IIb-D3-
SjcnRGn918V1GJHTbbgWFxOUjjP4-ei71QM_szp39WczZ-niVsoAhLHjekIl71IG_cxxYWY3GIBOokoZ4sKoIR8giVMu4tpHe01rPCF_RAwmWIYLdLPpbQYU
PlDITVMI3TsBPJ5_IFpFDfohRH2MgxfvoP1wIjbBMsqmaNB_tJEREWYPqsBydytZgDkWIQJrIy-rVTcAp1XbJ6ulMU25YnQs9QNKY1sRYp2dKQ9LzNvfw5FA
MxzPuTMT8F1AcGIsbD9anArj3OdrdoUipkrYO9-AAB7qgrSsnQS61NKl97DAgHxOvCGwACYUhOEjPdEHSohnadtwqnEalzdOfjGERKEGHCY1be7kc9h4EILQ
3b9_Ob20-e5Dw2JtRTkWq02SH1jZxWMSqqJ6dL3fruC2hv253UHTcxjezBNmMjDoOMT9YTlhS7qj-lQLvoyFMcHruTWMVu9cY46Hv-6TMEPrjcPUlRAv_XRu
rQ95mdLWsnyKjLgdrL8bggR9bDlHe7XU9bKGs6oCBTonkPCImK6YT1ekUJ6ffbItRm0i1iKz7VNJfBcJs6oK7zb67FL1I8JPfTPMrrSs4BQYl_nl0EZdIUdF
o4BOHEh0jg819oW1XSKk3NrErKMIsqlMnOD10UenMqe592Y5JvljU520LgT-CR3DpILXRjkW42boPsEfXsrfgjnS8XdBj6Dp9qmIG5ff3UWjcuj8ANlBt-y4
yUI6IaoHkLFITf3bOzyc7nwlHOTw9MnWgXIcDCUUIcpa_syiVJngYonTqlQ9PrKTbN7Ow0BwK4O1Kff5srxPL3LNw48s_75R9CEtroUfEpONG84Iq5il5tJM
D4iIeR3bqfestPVDdx95AbsCxRXRnYJZJe0zBuETM38bAIyGYqcjvTnDsuC76i_jQMHgiQFQTdRisqPyw0J5LglHUYrqAgS4pIRAMx4bSEi5zoTjaSKaaHfN
bsBFvZvY2mV82fekozArlcGhH8dMbsLf5CdGyKbRfD0btjo9VTlmi44YEYu5BLwo02crZfupRRN5iNlQ5csdhr2YRWU5DjlLe10e4IYMDHhxadeSrvuxrBh2
5altl2tQJhg-5Bks-1EmiA7DDZfPbx2jtpEYTt4Bg5_Qea-sx-vZ2_TiFhJkALoefHBTSWkRX58baLjUO8jZjttIrg4jFdO0Gv1rmYvzhjWGnjVReayqjZev
i7sfmqQ9Q1UhAjZvvFywM_I9k5sA8vkx4qP24j1gQHUpxpOHBx3j73k6SSUsXfB5fO3bFBxRuCFrMbkQAcDBvTkWsBN5eA39sKl-lgS-nX1UPui-sHaKExQu
53GDK1qYhspGyE5ydIsoGDU3Gdva--A7JJTLnctXNcpR-cIx4_ks-1CmOlixhsoK--jjMvzmUmtSiJdNEs6rMyULZTIhzpGocxOj5U-yP6DGM4fJwTsaP-S2
qi-JSJCeD8vVif9Q_FXqdc9BgQvJNx6zVkSbworDjQI2ispH9zlhKxksDItbBaBIgsVz_JxPBeNksKhtoyMVj_L7RT4dKGcCBZwonTbxneObFP6fwVebAp-s
IHh-Z8qbFPNe4_bA97NFfl64hKtf-MJePb3isuOakJzgioNzBfL-zPBLliqb-NZ8viZfbua-YHqLOzRVs1h7QkC3jffUadXcZ-4xNtbQMbht8Or7rgtFwLKf
T55nNsy6XPXJw-OZvDpoL6yysIVxWqB4DBNUwJ_j46T9Byvi2bwitZOeCAVI-u_dQPlIwvEnEoWezP_F-kYDrwTI4kEz8CMWa5_47yrJPqx_B5E_6XIILfl6
vH9NuRwjJkbVPZ45GL8OVVp9ZktvtdY-J_IOBSR02PdQrQ0G9VtTnfBEIOmn3T_EtHrRzCPvoL1iQ1ZsRVkzSSgnkpRuZcrt39nwxBRisA8tpizYSK_zneQm
dT4RzyTO32-53Hf1ZDvuNwOQ_ROzPRwW14cnfZTdwXeZSEJs_Hl4ERq_2o-XuxfmFWG8wIDIVTLnnNtP-2csDFLnsMoKI0ZfKpBZSd5k2Tkd96i8dsUBL1AV
QajJttIGfGzB0ObFjCMW812sZylSIOJjyvAD7sgBOoUa3ytK7tWc_mS
}

