sprite $image211 [285x241/16z] {
xDS7aaCX30JHpI21uFwtNUVigN8Ez3j2rnzXzsS4xxjW4oeFQPPQNqAnFKIPQxQqcmTsJEwZSnFwq99fpg8KPr4AQIGM9P56SHP5dgDfs5Qp2t1i91QbvFwU
ibq5YvB6MHJFUh8hOr4IQIIEZP9ulXKM9P568etY71l1-MoaTqZ3rzFi8VXi9D98f54opxVI-6mKqaWiwbL-zRWzdSQY5D8eJXkbaKOXZSGR9P56-Q6DGXhf
yMd8q-n5ES-tGXh5QQCaqYYaaUxtV9CdsvifB4eXZNJBHP6dsLjp5gMmAEdQYs9RnMqKF_rKKOiTmROYeZfv3Wklv3acSh8QmUav7EVlBtdbz1o9Cv7BKDlo
K-9Cs5Yd9vyGPoAL6Ehqd1R7l0QdvrWSCw-SdjquES_ZJ9IDPvtJ4pcNgBwCOruYAgTdBagDYRoCOvoUfLWgypXp_AFOZbDNSKOyFNx2bpFXXMt5NFMq4uTd
VHcd_9DhBjkjmZ0K7I3hBP___zkx71m8bFPEa-2-HcsJlQmjws1X_W57vTRgcN1IcI_Wo49wC_Nq7tIS-JSuIxDxgwT2Vu539aHyQ_MKkiird2nd8handb8M
Dxc40oItswd7-t4grx0BE060JTjzrJCZ2mlz8MGfWBF73TLZ1pWiVYeSRSIPd43nFTKpuKmw1pn2hL5h3e3T6ZMDl5MOqOz9eAU_bjL2t1OkW1Efj3IxLPZX
HpXcaVu2PraQ4xbp0frlffx8sSfzQ-MpjYQSWQSHDHzmmeTwRjBMFQi6dF4pzwdSCrxX4BMsj4JdH1ajUeSmmwEg2bbPO_a3ZfAijRN18UM5c1QrHssrHM-G
eqRMOUM4GqtDBCAVS2ArFTJJRCBvzgp7i-eI3biZNjLZxG4dWMZqK8-Z9fmjHxq3cifPLj9JYMHLZz2op1b2Xdg8TSBvsXpLetwiK9vmW6vCJ_KmaNQ0r_cS
YMZHRyvHusBR6FE4mnrmSwQcixP8AZc1RAEj3pZk9ppVMb5Om_KDJlC11xMhHucu1T27WgWrjPoosTNpfR81ofXtE4IQPW1KsbIF2otI1vono2o1SliozNXa
NS1nansEwD1k1pH2YFIfdfQnmbbqm46FxrBFXkO4HyLjXzC74mSqKTvszInjWnC584v_EVqhAWeumM4MFtKhCKa0ebCz6KhBjdCo2d44Nn-i7e-T1leFECpg
iiBPkfK1a9xwgfu91vKPFzbdV7P5zOxUh-0mc_kpMpa64qCD3y_QiaXZsfnJ6uWFLuyVq5oKrReamaoQfJdGHQYf552odtgqJJYxSpvRFRji9ffUly0n3pVZ
njO13HSY0qfVJpr2QXvv2SVymt9KZnSqA03LyGkSEOrhQxDRMIEjK03EcthMlzetE9-hdbqs06hWwVr2o2eJZlcAP-rMdRKHImV2GcPjJJmRWKzKpras3opN
GfRJXScXdZMzuOgrjjnGteXruhjQ7pLHUBmWw5F6Po5VN9YSwY57yTgj9DQ9OZ_r_FSVPtp8hF2GpOe6vtFE-TgRcstgOPKEf1XJMoUAUUhPdr5yPcqTqVH1
P5gdTrp1oGd7VQijRSs0L0mc2cYYnpPHV2AUy_Jz50tmD0x-X9ElU8IiXm9uR1v906nCRF_38qsdUjuxwjk8RDQvGkCouG0L_geUcHE5p52mbpMI_wX7beLj
gkUDf--Lo2Pae83Bb7J2wK2wlwg7371VJpqz1whWatgku2pRuz7tpREcWpVh34YNAUc44q1MZuDw9DHdjv9reWZvMptpiOvCF6_xN07FiiBbEQVAvN0dC2iA
sDNZPZAxLOOIwO23xd-gHvPrRUfvpwXlq9XuhWVF4vovUohI3-enTAtrr9Ck05nEwhdQEKHJFUyPzLMl5-lWAiynEr-OB6IYHvnEFGbqCIRc0jnIMzEfdciu
yIuNBZthSZs9_35uYjiHZeK703-sTT8r_nfc1jpHWtzHZz03Jg6CY7JYUOlsVHPoH_zxy6HrPJcn1hpNiRQqbm0OJ4mDWDfKJnxnABSL3dhJjgedmzz5DjVd
dD-JG7Cz_SrAVmcrue6dpMxbGaqAqFp7ovKekms3m6bYMpPWvV__jWF2ASugAdv7c2E7ElEYZLXOj6c_wobgFRXFfE2OU5tG5FRvULQNaAFmVBoT1DBhDqjw
UiIUXgvdzVdNSY-r5hCg8_NOJmEMPZrG6f-Wh7yS6jytzZb1NI4XHyCakkByhK0zHSWKXLQhejHavoYMTTCTosIEmdNUZzlIbG6UZv4D2cuKdk_JoWWP3azu
8r3FKhnQJLEfoj6LdjHpWAFvPeRBQJDmD6QumlcW-gwrTtA0TGPZqWtgJdpfwwTgjUocAEGyHotAnJmtrzDQnQ-IFpf79G7Q7VOvE63l6IR7VzAxdiqKHLcr
wn7bwD3r-Eycgjbw59uoEJWmpFW4sKJ1ZMaLeS4-nxeGDd0WbI3277NT7uyYejMgcgBWyfoZ5dslBdibevx9lPSmH_r0-SP2bEzpzcYOJCFZNKyjqheUQefY
FQY7DDzO6scP3Hu7vqE_wu_GeE36FWUXwG-x0hKCmgzmYYaAgrQBA4SVNG_hWLeMDljoCrm6S22tVf5iOY4QzpdsOWmEqHNgqVbNBNNN4bOVHDxrF5rFkpQ1
bHlr63Y_3W_nMNG7Ia5mNeJdcn1oS7OcokTMCLESpxzMKnHbA_-kHsUcMJ_LN8nwcco3AvpVoIWGt4FX6PTn50XZqYprUBNIaz8KXR9mEQXdRfOvDcOsnL-P
VkqAXwIxRon4E60F0QD069FcgMSgfYYgiV1UchbosPnwxhFbraDRnkE7ElmxkKNIsVUGRR43GiCaZadprAD6mfbDKL1P6Wi_vljyh1icJKCOEFPrqYyuCuW7
WdiV4N9SGCCaZabtkaOziys_oBgUtS7nTQDZUe8Z-f7evs-FMPA26uNdkz0bBYzZKYEUdQvHJx5gPLqFynCSfvxxp8_TJux8NkcdRuz9ODzudTadv7ESXUT3
BB5mJFeGHuMINS_QxYZq74q1dAFhMMVdd2f25wz7hqz10Pf-Mk5XYIyq6YNZc9GlKK_nQgNTzXaSfvw3a3LfVz8KHYomLnJSa5Ou_qBXwV3mEXYJvilwNijk
rMg6zTB0aMg4d3I5vSd681W8RZWu42WyZpX_D1oJRfo0HxLLQTLgWNMXnJTJAwLDOVcCKXYmlyERtdvqXUSpEjzS69CwzIGKXUbn1CTDOSx0-aJe-yuCuZCM
IS6DqNTsXOWV3SUaUUfPX4_W8Bn4HZv22LDOgdpZ03Wm3kmRuvspQmWFqSlhHDrIkyhK1UTyHw7SmrrJ65tCADJTlbqGdWDekWFsSy0t5rubg8UyhD_xu9pk
ACpENEaYzI0q_NhadHy8JuY1iolv7zPdSul27DLY10_PNuUolXhrPCa6wX4GyjZHPbpqRi2E8PsFbisjO5p1HMHshlO7pylBiXdrPCa6wr7VqTOdP5jvXsyl
zklmECaIhe-fXost-0oE_xVd2RAfSIHHkuHSwuK1UvUGCRSop7kkqxeRwgsFSqjUSwi9FHOQGjElHpdXcJSIz6DFK0ySSzheKbVKfvx5eYrrjKAY7YM4PyRP
XN4zjqYEeHd1-dNgETtSOoSqgaSl7N9cmDvMZYU9jBe83-yUGkJRkKezujGJmM64XsHKZwuBp_eVPzSeQePwmYUMZPH92QafNzOZE4o4vRjVZu0mAWZF_mtO
_Ka6d3prFC4HQaz1SUIfXmsSTLDmPWw79sHKgXxb1-nfGixd5ZAayF7CkJMTMu5w59p2Efma_aDRo2sIjFCeBpmXyxA4d8U7nQ3nZn-EpdNguGDh8hxDjxdu
wG5ei1xbXMVUsPM8XA8G2hmCWY1BFJ5tY5UUIfc9cIFP9EfHOjz9PrSYSjJZuE0_pLDF19YPkPJrpp9l3DWawj4J4TnttjcLYAJWiYs0ABgMM_yANwjMo_rs
A-LlU_U1tJWCn01qgmhB-FwdJR73u8LvXB516jUQ6_W_SKX2emGuVFBe90Jiig-EWp23jnv6cA_of3qtcZNbSwNzLyAgellmy9nZJ7R9XHXgt7goi7OORtv-
Sv_oK-qFw-ej4zRjvweNJ_WI76jR9pfQwtbwSzzmIdwehSVX-n5-jt_nT7ZqXqDlFMLTW1DddGv7FEUGG4FrxSfiFUawptM-3JXHIndYHFTTXtVESHeoYiPG
whPDQjtJ2fo7AgGX1owUGi0-z0r04nnpRMcJ6PnlEO_-0YTggIY-7z4BD_7j0dROk3pumSWNdDPp-V-7bwe4X-r7_C9DFvtsQD1w-liLS9pMqo8BuF26h0Ji
-iNJfC7Rupw4oi2HMe-By_hqJt-tudkfSdAhLBpxxc9IUJB3mK407Dx5CvhlO4LPhQTKf5tunMBhyPPL-05xRPjTH-FNonodx3cZLwll81XE41oo7-a1ErOV
iN5QJwc80Yz6kzDwbZNb3OV00OuJiAFWIvgDKRNHu15AkzDwpgC46y7H0k1_2jZPK-Fp86xeOb9rrhlV-0WE2O3bJyRHc40Q3W8_zG2dz1Hwwq7_oi318V13
0dQZsUXPJnxQwAsdL8BpCG6xHEFpZ6ZqrWESb3eSDs2FmJb7f_5RJpR22hncw7QhuWJi4J4Cs0dD1_08QuVpj8zu20wPDEQ1Hl_a67S5uqPXvAJjMmFW5BAi
kjF_YGViOJysVklnWq01nmxOZUtRkr5uCVEULW77cEoo7Xj_RLcjPrdtVMKuVH0QuujdT876Lz3u0vVzmEH6SBp9Bf_6vn5k34CSvAHHAt24W9q76bzDeqzc
W8T75gNg0NleWOPHNx2jSnm_OAz1CfjfMW_7uViH3pG8pIIjX-Fu0VlfsrH8hQV7sRO1ZZNPrTyLvbXRUKTXOB85x4MxUFA0dT3Cr7hQmAI0eqzsVOjcOtzc
WYy5SeVZ1Eo6pTVTAFZ09724oIuIi1EQkLeFNe4H7F5lPyQ9hAWPMqzv7fYaE7h0JcYcQpqOc5Hmq7G7arrr2Xjz5FwIaYeue1bTF6UXGMUM1YQ1Kqh4MoRO
PwBHRnGfhGH73jW9pSnhQptp41pvJtcKqtnLmJCQcDm9Zlp2TpONy5mPc4m4nvYmdhVr00Sz9teSFcaylmrEFIAE7B1JcldN5iVX5y-OduQVUZWE_NIQqCpR
UdGS_kdq_3OyHyN09CT1GpPevcmzvu590GSNJuLcVXuCJ3QSIXkoCjGtFyzWO9BXT3JbFxL1ZWe6uDHXGwv6ivblRG4d2JZ6zmfJyhJlohVbEevnj9cIfvGs
C2dWWEOsgbp2zQN7EMXQPzuMWdEJDAZpemCSCaY0xVkcUFQNEFbuR52bvkqrpa43dXxde44n7DWSE949pItZLE0GcWC7s_TH0vm31Zp0UKrpy9I6qzCSbHvv
QYOsDrqbFnIXETRM5z7S0m
}

