sprite $image334 [173x248/16z] {
p9S7hjn05CFIaz7RSl_JfdrX8HJNmVEI9o0UQ0tyl1wDlpmDcs6AhwhnGh_mPqt4Lqs4LpM6gFeO0TnMOndnLHCXLUaj_1e1N7Vi1wFArosDWuX_reIlceYl
cjIrgZ_773zPhy0w6dpLHBXOr-6VDS6VDP40LmLSTnY-xMFqyU0NaF1L4pNy2k1R61SXdEew3R4oRR-DQr712qZLsvsy0Obkz_j9sNg3QiZI2x0iVWF-gXgu
gWim-0BiUK9sw3sn6dm12Nwk4doi2L8rvohXgRg0axAFznTWa6_h4iIvEYahWLJNPNzXOZNuM1FyN2Nuxoh15v3WLHFyN2NikLgN5RC0Wz-01AkwBakErJ3d
Qbss9781nhLMbS2gnWMehCkCrJnjA5LTqe9ZFONzNhhC0apukGLc0POjNQGh5p0bQzrC5rP0olgQgOjJJTcLT1a5fEnAkXXLoowq84m1ARlI0aNLikkwb09I
jYbTgpR8BgOBA21aErhmszelEw_hMFjbfrzW5z0lEv-kLVjbvrjmhDV8pi-OO-r0KfdfT5r07rMsdKktNzKPoBhJwQewNNNxAslTgNJxLUlRPyjQTwA5xWB-
C5yVEfVYIXI5LzdOsAxQx_-uDy3ndqQDkZd3Z9SIIkWJsgHcP4tikriOhaVBK2RsFUxpOms3Tc9dTnvZpp-k2aDku1Dxb_iuDQf1qm2B3smeRctXuGMe0bGr
o5-nkiSDFTe6aAD2rLTiZF47MvXQFPRNK2G0YmtQ5spyt_Yxt1SruZbix7RUM0PuWY7f0p3xtIsCa9x3HWPs3QX0ComcTch_W1lIarXbeAX1DzWWQs8_kR-z
1VtDME-QHOIq0oag-0P0FR5Nt7yA6xkLgQufRI670sgn0z0-iDTRU1ux4hompG1sHG9w8cjmk3-mrzpdiOs9tJbAKW5sA0e0qpVizNIVnxRNGIg0kHgGOPSo
v75YBxGVtEUncnyO8uUs0-i6m91gwg7lsEijF8iTNGf9vSGTsCW0XEGXNM0lk8zW9T-Av4QAs0rI76Qm2Rt0Napt2MnKAD8EkIUmFIHrWA8BxEN5VGeRxMHj
S01V9mThSOczvZw17NbY3SuRltT9AdLIBx7NMtWVwwwP5zB4yhgMmtP9cjHhx3NtRMnKQvfjKFI9JQ5ene7L1VRFjY0fmkzWky47DXAqBrXgsu1-WRt1bMAC
MzZA2-iXEJ0crZYphWliZIt462FY3QmNSwc3XRu_3TBG1VO6z_3gDdQFtQ1B5JPDx02m6hh0tj9wI6zW7Q1A6-mVMFLITfVUnKxknBhq5ZOIa2I3CR6pzx2p
Dx3Xtx6g0Ev0F8FrkzZOhSt3EB43e7N8UWZhVWlR4xINEgNy-TjIAbH97QpTmrvt0rjuOJrpjaiLI1lq0rjSws2jIue4f1TsSEQIV4ZhO3UVw15sOcK0fD1i
3Um-527vgImlR0MWQ36ivAMTEf-Fhhc3lXesgj6a31QVs4YGHwo6hK1J0EaBLYMra9R2-iJw2xjDh8Uq5DPBdjW1M2XiOgMbi56Dz1MBgm7K1R43Vc1hCy3w
luADgx5-nmPdrMfeBQoN73-m1i3cGre16osdF2J5Rlp4gW0abvR0jWHWGnhmLwmds49BOADmbd-1LGmFBO6DZPd_0dkq1BO2jIU0jZgs0rq7Zrt-4sjZ8Mna
gFDde2fER9_Oube8sy5Sal9NR3snVKWhOJDaITB6nAReDlzRbiBwGPpOTc39aB1zEMmxY1FRJooKN5nQ3LiEujnilB3cBgs7pHCR2P8K1jYG5iH6cbYtSxmL
DjVYs0uCIJ56Q65iUzrVsrIkZ2sI1j2rDbO9CDUmmxmuTWD86Q36wjZ6PvilZWtZi-HhOzKDo2q1gMbnhBpj8-J6llnc_zlEtUms20Gn0BxlUEFtVzh-K4P2
eBXaDtAdqleIuFIf6bp-JpVdos9zMTY5NTY5NTY5NTY5NTY5NTY5NLXZ-8-mF661ibZoWkre9R4FagHuwhGEbdlErYt5i3nW1RS05kG1AxW5iEHJB22rVYmL
jYC4ruqb9HPf55mNbXJOD0gk4Kigx57RXDQ3fS3AFwuVIogivWgiWIhQG71DMDx58fhGEh0yHxU1v9wn1gfe0y4LM0CriGFSn1gfP0ng4skmYXti9ZUnHkgr
kgBTu_vO0pQgRWEzkByZ38DLO6zg4Ti6cAY97UEcsKHDx30tW831UhiDslD5z1u18rKVoAZ5ZJc99UUmSO39nVrZP31InzjWeyvWEOZLt2SdErDj00vbl0mc
UfPy1nOlS0Dz30kA56W3HHt7uhT-FNr018O9c3sG6Ms31-Umezqri8E1ivbi0oTLNq7IsjVQW8VOPo6GRU2YPjhBNCZJ6csrZ-v6JQnXM0NtdQSr535nqpn4
zOzkYowmmkeSNTq6ckgVXRjjG4CUWYjEQmQiDcv72uMbY6rqSqct0KNCexida5X1BSBDDgXW9Q6uULfJW2f6LxS1HSnSVLhZj-h_mFgqXfbotCGAQfbPoDCQ
GIt4pJOGr39Sz0EMrNAr9fOLSyKYaDJAt9pLOE6SiRKZi6Mv4DPoN2IrVX3u4-id
}

