sprite $image341 [199x286/16z] {
tDHN5SCm50N1RrkDFzhK0P7DCDYZgtT-mdtV9-_-waVGho0VGJ-2VWJv2leHz2FeLv2Fe1z1Fu9-1Va8-X7q8yXNq8-W7q6_Wdm4_GZw4VGho4VGZw1VGJw2
VWJz2FeLv2FeHz2l81z1FO9s16EcAvXh_KM4ZFAUraUxOiprLTyJzGYo4VP4_IceHv0zib3_5DJtH3s2-fu8LOW0wdiYUsIX_Ycexubw1FKzaJsoKDyJsICB
zKz1VK_K8wZlYUoHXVgUo1vPg7yAwdkY7o63KTtJarixKMAK1O80ZE85Crt_-p_jVoKKsXfsNNQ2RDSfxi5NCn12PS-8VubqXM16wYUHXX15PTu8WdI6098Y
EQIFVk8aHORqKGfcI3n1ka0mG-Jaa0OdZsh65QIFHS6C5fr5Y6g67SGUmOplBX5Hs32k8HsKWXYcdSK88yONEqi0QuOzH1Jc3FlEKi2QOGzHm9fXtrcY-0wZ
37bWAPXXqrds29s8OTfP0fi4vuXX216pKhWJmsw9g5qfY65G46k4pkx0Y6884RDI3Ex0a1ZD869P2cA851nLcw_2j1JCi2c8mB8KAJupB22YiChgFZ6ei-eX
2hjC1GP1wXmAo_W2upTsbjWgu0gC6iXN4OW_PjHllWhhR6M6IlqI4TXdAJ8KMjLPnlsqZfSht4qd1g0rcwybGhnpbolSBLUCcirNOVk15zxp_H53_v_PtSwo
P-YhZTRzjmmt4kCyg_iGKPWnqhpTl5_XW__4Y3atEqi1CuPEj2UzdlqbWo5o0oA07ICuFfAFhzcV6GIvsLcAnB0gHOhkDgh48qO9qemHt25XDoO5Hc69D65u
tblpbmra6pFAIwGzOmA0-RtS2unYPxLd-3msbnZbpchES7c5hsL66TAQ8K1CaoymRYoH9eo0j56XmBYnHDembdGK6GkCkvrbpt2KASacX3EZ0l8THghA20pl
ijnZN2-Hxp7ev05z3sI64kFM4Z5YXDbFgtvcn93cdcN4kDbPlv-XIvhiYP6wQblItCkC-vllcL5_RnEPCQUjwlrbey2u3zanL2iPubsEPqOY-l6bAJBkTrPY
I8nrZDKT4eYH9ZsyU-kIKGTHw7y3AbfR2hvyqgnoXyGgndLdwN-ZYWf6SASSnmC6VhkS6LMG5mA_pj39dHE9SIYNlsJKEWIeO0HtbN1uHVUsquxXRpDIcA69
KL4ApaACpUsoLZ9IwXbS2ivCZ4YbgcIar3Au51nF3F15pvAyLGofPo0CxkSPOtut83C2AXWfLOp5kHkCQR_2qz-U5CqP_ZZle84OULqVqGlUh0ru5cC8UTgP
iUmOWJPZxxpWMOpK75fWnCFz232jmCCOQKOOYR5_o0nGsZ3Yp8p0CcOStlb7C1RdFpBct6RCo5lL_01675rYk3DZSIaBC_AxhJrZSUukWpz4HcdDaD7zB6Cx
CIJxsZBMrFVCK68asRHduFzIH3HcYCyDGmoS6G80_i3mL8esZCNzcE6FG_vGlca8w8pXq-FkBuYYDyPC3Cg367fWa2nqmmWbXZwMuOkCmn0VLzQ-62iTUNtg
iCOCtQuOAp7ywMV2ikknIV4T1Zunmk2l6E43G_ddWrIADWoTdPlkC1O-OwLID6Eawvlb1aFp1KvY1A01Wqfnap6Vlb08cZ2e56N6HeoDYa5fmLYSEp56OYoP
SLHjhHa71JDSaP6VHZo5CTzZJ11FRn_1y6M6SCbMbpEZ5qRf9dhK9pB2NKP4hmnMzC-8w8unLIZQCPGPlaBHZC57g3DZ53oCCVm2OrOyZU6AZFc2CGIWCyPw
PaoAHpCqCvZc2Vja1YuO8CQaw8UnyK7SKodwO2nyXALITCAOU26aXuSnfCp8Gtd02nxCa0E3LlYK6IlmP4QuOFZJmSaBkcE4YWk3zepXTBkpzSJWQipaweqX
eAkqFXdByOUH8_fak2rkGtuANJ8uC_u4ng1_12FYJs1iw9F1YiuOMb1qn82nmfvHk13iZp4JmYiwPF0QNu4E6NoL9kYL8Ivb342t3CJXXTY0dXd0DizB17fd
_5FTdID758D06CubNlNzJ-lTdSpopweMH7QchmI8miii3kdaMDME8PqowgXgnP3EC-OONHXM2Fx64gEY3CaCS4GPZ3038Fio18mv499dIC1WI9uXNMTK5MLM
dY4XuoWeaJn3OaRvxCwi88CH_6uO4cGmmWo6f1Yiu8OB5n9WICHWI9mX1pEg8BCY32EOuMC19CFGlOmQ0p9hFKCKK1K0MSCG1unJa5bB67g8mH1WB40W0yvk
8J2M8BZX3YeHO2n0KCEzBRE0iK01j-6p4yICiYU1u8RB9UBdid88RhXG8Z-tPqzAmPiHpYnxCWWpde7uuqFC221WKB-vHCgTAe20bSBD9L9kk3a5RqO0vOvR
An7Cc3uYGluLPKu88K5L8AIEiYUbuCq8lu1-1pC8tenmPZdAZ032Z6SW_coQ188t8tHs-6oQ5GeUr6yl4JVS2887TSuiDrmFwX44hw8PukUoWWeUr1dYXXj3
C8HlnzSIGZ04lg51dH5RGIODwgo8bOY_dXxKWmY6FByPOKGUmfiHLkHB13OZW5Zdc5GYCE4o8fzPi580n5wGwGath608hDI10OXmYS27kW0Y0-7D22csXlXN
BEiPH3wpx074lX37B3C0iMLcmRi1YZ24Lz6Co3iCWLKq8_8Gteom8W_XpGWZyX3UZ0WZxu3DY17T85v5Mz4GCjrmZMW6ETsCg4N0B-cfJLnZg5DSOgXRd3BK
Chep7DqP3c3qWfGLhHsr1-8J
}

