sprite $image233 [272x184/16z] {
xDa5Sa0n28JX827B_GzSjtI6kgNBTmVsVp9-aM7PkDCqyigKSQqvyWPyZ6R81x11JbTkGWSncVaSY6V4SySz8xQomDXUYSnQoE0oyr4VZIDV1UDiR2sKix6r
_zzUSUGxm3aRMrlAsTXQI0y7mOmOyiDWd8sjXVPmx48e6rk32sLZQqjxE7QXb8sjuUZsElBBBUjJsItbR6mjf4zb0p_xuPnxHZIomDXUcSW2OtiT-MDWvpwS
CxPN8dzSI9_A1ixPs1hifCPIjdVcBvj2EHmrE6TZQyiu6riBwU7OpGCQIzDUNLbWRA_C_AEcK3Qs1kTiR6qPPsDh8JqSkobzAXiOPsDhI_jKTY6KZQt1UpXs
oteuTg77_6GwyzUL8Gy7xrFvN7j5Bjix4nt7UHW6R-z6fDx_SV_J6AAo8KorHJ2ELtlVEnyeKf7Rf32S7pXxzPRn96CNQXh07kUgSHnmX0TWabJXaEbWsGi0
C4cgC9mVwheNQ4GkYN4iP2D0gtyabGtdYsIlUDZsl2N6iKhs0WAoGbs_moCdibJs8W3fc2oMlGZ506Irx8qu6DfcjUm5xXPu79n8lZuZJcUBF60YibZsWdP-
TZo0LMr42CH3H1R9tjnF8v6bHdZYPf676R2gZO08FEWEMqOYyHtF1gBZuJGHMIjxJtVhUIn7H2Fy-N9vll9eG630CZQYewi7jcUOnneGCooOlG-sWdX07h9S
zlOy23E00h9Izef7p5ifPAMckOb7p5kPwZf43E8HynQAtKM864ZnwFAsVRkChHevv06qlALtHEpGuY2Pvwsxnwwn8zCWyxm56n52IEouDCWqRnkOYCICTYWS
LDt6-GBbhOWuZxY5Dv2gN-VRSxFj-SpoLaIEjOKN3V5eTR4qRzcG76qBRmobHSX37odRzQsBI4Doh2syiQkNLurrUSkll6r8ZhI5Dx2lrvSZM_j8qxm5ID9i
SY8WCnwDoFbk0DgCskMjUBX3yJjfg-GyP2JMW2XlnKGyt36jH0nCUCIwR030B6_Zqjdcfo4UVTr4WUEyRM6yJMYiHhx1GySGIfS-RnNA0cBJqn2FlivF128n
RpdX5jx0lD87-SWvb2OlN6RRmeEiyP2Dq7iacbAaa0c865daeVS46SPvIogKvm1YO9L76EB7UKk5yWmI0Ldd4Mq4OE21HeG-1H7HgFDGzlPvIpQDWDuJiGcC
ey93De8kRoKHxuZO1CPHvI4R2Nah8eDGjWber7Z8HW8FsSXuwJn1gvHuo4OYZsOaJev2sMm2SPHuQ8IFFDGqBqJQxx3fQE3svdtfn6D011GF9qHaZbOXtxvj
oANd8HjfeTnum5r4fg2nNGgtEDW2Zs0ZEhDeFm6pELh5hjLxvuZ7e6b4o2MH2OpZhLQ9-rNn63ODllH1EaNavxRAy_nxjz2v6t8YzAOFRrqplN7azSIWsZLD
q4UJY4rl7FdJmsnCf2KjANqu9P4V9mxaRzekZAkgne6TFZutZG3ssLOfq4YlUcEDzV6XfZ6wEsplLgbSuwd6-c3mrIgDVuhO8sEBqyYGH-iRwUCJJGF_Aje7
MkL3nj5F8z_M1-aYKg6XWlq0uqXNHIJ4WnZfepx26pqMViiuRfzkbNXCincTua6YquUpU9LdS5NVD7Y_LGADZzVTR6j4cZv08EYZEiB3nuNoSBxN3MD1Vl40
YTu_wFzz9c1MQHKLhPgnEzw9tBP7uz4iPQWFIQHCmr6ZmTjftuSwFCpvSZ3nYgAr4BytmjkdM-Lnslk6vCgNHWGO-AgcaOfnqFQ-Zgrdh_oKKDC4VJGkBY0x
68TsnNlMrMW0WQvftXxXaRGAYhlY_Ujq-NK5m_ac4FMHB1JJASn-PCRcTJQHw5RCFXZXBI4oJyRc1rSaGjECzU7-tQOX9ZAEVXD08XAHFaBQP4s3QJ8stmHq
JQCH7aqVT4Vhczn6r2e_EsFp4NxKDBr_V6DWjR9nt7xMioq1aHYEyDA7YEnroBH_dKOs0lJ-uVaqCbN6vaJKD44YJH-KFfATSwLLoiQnlutaqqW0CfLnrBCt
w2EEy89I6CvHpjZzirTWUl_e5eeJNCTMj_1fqyI5W6naWk6ycBsZfXdhmoKHcpbZyxhPc4Yl3qKDp31tnkQl-nutZQFJXvDjfsGset7KipTRA9A0YCoPiNbT
XjchBNEl3m1cA9p7JcmZGA8F4QcTnqwSlQHJ-X0F08PQniwRlKZq0M3oZCthEipUJ1-e6CUKsOjU8ea-fipO-iuPU4yVA9p7pfMzYJxgk-AfHtYu9poIuNp-
EdVPIn98z578sAcpbnhXSnvJPMnzVKOeQbuIg6GSysUlcaVwe1EePUpysGk14GyldSVERoFY8Nq8oCJ3UNtdhABWb3Ds_knLCSYbch7psqZK1nrOn3Z6sIiU
RFwHlfDfZUmL3tpqF7RIdRDua00Uov68sIiUkD_jlYWDPQzu_EEZmJkMin60uf6ax4hP-uT7oDxLUKGRmHyUyONVjed77uKOdgVh1erYotl8ynygU-Bu6m
}

sprite $image233 [136x92/16z] {
nPdfSkCm38Dzso90lV_RzZ2ZP5EFot5NjB17_tvZu6DpTF-JOLs7hddwENrbxXjZJ4c-EMIRMbACgwH7f5qv_M8Fmo9fQLFEN2XU97E3IZP9XyWstains30E
4Pj9as4SokblTFKivd2pOLXkTBXVnCKmX-znrIUPcrJYEXplgZ-JU5VzcTpZgayoDHY6CvD8L_s8r2cdTrozoU7fSYN-gOztrNSutbNVuJXNuntsNOrts8PH
7SDUhWMu6kYmxsgymxwhqGvF_GLN0nr6cXnNxva9W6rqNOrt601b6HrNunt6dcW8_oqNBEAGX3kCXE-GS4Y27SQSZCDv9j4Emq8scadXe3mu26b1KXnUo_FG
R4YDPZ9lfPTM83OJKT8u14f16vBfcqEj5mNiYJIPoPE3EGDP8Ir0eAzUe2hGhBWT15IAglBXBNUGhBprr0jLoJb1djvgXe2QLMyxzG9LajpV9mX9S0VHdKG9
W5PFU2Lx7gy8GG1AOQd5E891n2YCmqY65UOjDTjqGRid4ZkCml7Cc4XL6qWci1F5NLYnIjuvBBFmuIsv_wFIG2Hi64SEsucg3SHOWavzgUJ8KJ9ir792JAA0
2rjSFUKeCs7X8AYPC92gbNWSDfD7B_pEioYfwghFqVLhsKSXUQ18_M5OL4_US8lTiLAEgKn8LLTV53ATlVssv_4a0PKW2Qaz35AvTAVfry9HIC0zaDgLR4Ft
MuQ5U2DX0P5AhbebO-Tb4hv052o13_AJzMmOc1q6ou8N2LZYaq2LuhggN7kVeIXyu719e5arAxnXfDSm_8m9u8l31n5grkzabTzSnNJzm-LoJNmImKvX771T
lVvXE-sfE2J_Kl1y6BhrV_po0GeBt_BkXJmfD5EIq7FrUgOb4TuZ4JgL-Axw6Ot28ydEC7nN_Pc01d9AKav75LVFCsmya1nElSWlHtpgwcGIjvoQhlgd_eoa
jglUAmAUE7m-ZB6hdJ6HiFoSYIt3SRLUPZafXmAgLdJLT_Y410Bg1LTZ73OulU1gZCF6fOwhjJF_B0U5mtSroE43X-DghCE58z9L_rKzGG9AgkDgjCFsmtbp
5EumdZZcQekCGfGuhjxcSDeQOXI7mQrp1nhlCC2rQvyPGckbST8y_UrwVG8
}

