sprite $image314 [236x171/16z] {
vDQ5eODG44JHTUc_uEyQ7AAJqm9xUKFNnz51py7wdH4-hVvKGjWu-rSo0VF-pu137L929DbZKWWDHqy9XZvVu6orUbufpZip09fjz3g15Yfmjb8zW9ajHs-L
Z7k-GqwFHtil0nY4gvK0lZC0iz7wE0COXElfemt2z1u7C1jz-6q2CriTRKuIBrl9mGGwdd3f_G_2aebVCy1ij8NRuoFPtlCx4pI0aYtdkgFJnv-DFlCpqH2O
R8UX3iusU702-_XzlJElr5hhkXeX32mG25xU_tLxfUaodXtNndouvrSRN7H2Xib4PrpjI_pzdBHDZJHribVNShwsaPTlwOHjfsiRImSsSLesM3zF8NETgUn3
-frVMJPuu7oi89AdeotNcNabjRtZJoUWRUvCPn0PeZzJsvZqkSvWnHPasyUxFKJ3FxZiFgQVtpRY0N6TIIn7BNswsqDwyVv0c7kDectyu069MWJgMvwnJGBS
NfJET5of6sAMRkIkkxIjdqFRqbd3XrIqO4l_Lki81xIDTONEQCR3Rf1ySbddJsWRAzCPSb48i1F27-Zs2hr1sVlPgc0t_N5k3z5mPUoRPLnjTCyQuFPYTMOG
KN1LHvYTdKItZVx10ww8lTz6PomCUrO9StlnEcD7fYdDH4qZlDbJqmW7j8rHWmTCPOOSJE6QrMfjlTlZWmTkqN2nvxrdX6o5A_6q5JuO8nldlbTB_MjjgElS
7ZOmlCF1ZPD2-B4eEtuC3N5xzRZEl6PC6aIrwERzS4yXXnVw9G4lN-fNSUDYMR7_oBodZ7yLmA9rXTlZGbuPRQ4XD5itwOo5jpiKqZP6k3r-qn_lS1gIjwbb
6ToUM0BZt9vuVbd7EnorLQIRG8x8BqZYloJWp23pRBQnm3b170Khkcry_SRZjWwM80mPIiGfHxczf8x2AB0n0EgAxoT0JCXDhDiJLs7Wym8w0swlzB63XU7a
8jrUyHK6qjRChBtAR1tep0ZdXtp5j8r4PpoqxNY_35jNgZqwkpsyBhH7kBthk_o474w69Wphex39-zrUlrqTQ5c7qtVaksSokmE7_qwtTxrVRhUR0ontUw0p
nx0sE48dRGtf_JTMnz4UTdio8eyrp2gbxD5MNqHwkm-i1AsNjdNMcJImrOUhXZXylzlxZTImEWhvkTjBkis9WERmSsL9FLw-WDM3bhkzPg1djuUjGJE73_jq
XziRvGjOtqbRW764RZsZmw-sSVb_jsT80Ij1wt1xVDg8gPA_jwvC9rb9Kddvxc7rwWzrUunh5PzhYesNagGIf0GhH-jtUrndy8eL29Exa12LOEM5x7TxgP4C
JGLBvYOLaag8Ih1oj7wt9y-UAHt2G0foib2-36iyRRjqV6sQhRnfyHJctyRpykLO0zf6LWDvuzbDYy7XqrzPyFBbM0FQHifji_9YXJ65wJoLbozY3K7xlCEf
EupJ365jv3gWI8zZZN5xc0jyWP3fFBdc2L4frjYsaVy-gE8ibyWt8UfXhF5j8tAwG9Ze3An0-JgmnhWzNCmwKDgeZNmFG7J6WJNAxI6dJMSCTdlz-nr0Ih4k
eoteZDawfZC4gGDhUDk8hp1PvVg5HFLWZMyRKKdW1Ow6q84rskqz2atk3frnO0rg6yjkAe2e3fqXM1VH5XV5qH0wi0RJLhzOBFm2HwA-zjSEWuntUr8KISnr
9WvhlDjp31uSM0CBcQkbNsVyMEFTdcFm480rictqwOmVQxpR2zOPn5gl0645RLFp3nwUosl-blIs12tEizqD8V-xoM3_aaB6G-nEdU7rQ_iA5FAQjf4GrLk-
SnO1mOAsqJ5uu7_N0jkdlWYj_2ZUFcm31c8OYhgt_GSEMj02fkdafndkuvCq77wN6GRgFdszvRC7WDXO7HxodG4IXssZPy91R5iyysnJEEkVBGJ20gZ7pxyC
CcoteQ1Uy_IBGx4nWrhtJBvPODli6Ozjlhfdydd_z7ict-uUSXEe-K3Rw_9CFxO0rE0PXgttZ8-DzU6XVdFj8NlFv3Djhpuy3BkzX2tmZCEMUSRxnuCgsbuT
rCBp1MslQNZ8HzfUVU3Evx4T-NolWcT0R0IU0MslSNZ81zeUy0oCZIyE3nvR02gBZI0GihO7FCDY8tY-B3Q2uO5X2pp3OcDXUD2t_HLR02h35dY6nSRt1cwF
BHWUM6m4dc5j3mmFB3O2px2s1pp3i0N30ukD810o_u3XWRKzC72ps6WyOpuIWE61OGiymzeUy0oBZS0phEq1pp1i0QWiDeBXWSL6C3omjWUUBsjxO7XWiH5u
Xc4BXWVc7m0gQtl0CmnR0-e7
}

sprite $image314 [118x86/16z] {
lPU7ajmm34DFdOGs__-vAHQrLfWPHiUHbwbROGDyiE_BEubh-FhmnCOCpX_L39N1lmUKFYUQ6Io35ZvbBlWUSFcWkVU07e-tA4snEJwfcKWqrK0eUZXGcUVZ
3SfSFQ3q52qW9Vral68kAF_Fvd2QbXbT8aitdwK5DPZuo83YELhchaGvUHXhLSEXG3bFgobks5mEc2iT87kyF7Y6eamG8ERfhLiLob6AD2r3e-5wCFv96sMb
udNG8cjRmZpb5f-WIAgeIOP3ASmZu3lUSYnUJSjmbJZBGrPxZHCK1KqBXjC5dFwW2ivnFzxo7LgWQ943Q2Hhakcl12oRywwvcfOaBp8m_n-87HHjqy8vDBHu
lGWgn7ccI-gzFefaCLPQnDn4NCeuir11CLI0qX6AfECeZDCUZ-Qx6yOHYxUW8ecojoJLeTQ_LgJSVbASCG1LFbO1Wo8ZNdNjKYi2Ig5Utni9DLpeKCnZmn9z
goHBi6vpzNVCzoVYAYSMAbggm9yNiYlUVz-elwE5T_IW89y2xfAKGzkwrJ1CWIhQB86soYtAyQmboRp6QrDaB81Q4L0gb_CZtjYa92dDhr3jOfQauOQA5-zK
CkkI76LI6C0MHTrGbMDN5CatndT9thZ5kbEIU7LqGrTVra5vk9TZGmlldG3AnFU_5A6_NkY_1wOkoSRK4Lp5Mf9IsnKjY4ubMF7sr-_fOvIkGT7DN6ZogJAC
Bg5Wr8WcO3NtcZx7b5L5MrPQQ28hfoWlBGIivYhLZeruRug4bXLP45EubUQ5ED1gxbGrTCsI5BFl-veQBfA7gtTHANELwhVY7LFUoCuNCtDHfQpCLQeRyUeL
IOBiMiwiqT6Qehf_kdf5vdqDbyno8T8xC0ErLFVZdHIL8lUy5HIl5TULE0ErLMsRrRUkzuoCrLmLw8Rg9aKIRuiBBHfIqJHKFHJ9aWajSzkqkNhmhw2d93Te
MOUxqlLI19iMhTenTTqKGMMj0zNpWoDrTRgEU6rQjEQhXJzl5LqFHN7eQdCjqObQGOTBLqfULP6fsVFoSx8_NigA5jDSYK8cIRnEYX9jcKlnIqr6TrD4B6Dg
8Yl94OpRPjuoLtJqHDhGTMgIyTDwSb2qIOinRefiMeeXwA5eiuesPgiazysDNrkpMP8kMkofThn-Mko9M_7wQV5JP0SAWnQR8bFNJuizTadwQR77Bia3j3We
Ea2BeoGFqE8eIPiM_zYt6ZOj_h5lDHoq7A3e02sEQz41MXmbgMvp7nfDaOEM0nGPj3mOhuEM0nGzH8jzgz6VeiM-rR1eUP0Ylxc_
}

