sprite $image371 [260x246/16z] {
vDW9Wjem30LGoPisp_slMvgn719c1T8w-D-0H-Hl2_vR4YFCdKWYKcPMG9Bt99WrHNfuJeN8SXqAC5i2opu5fWeMwPbq899y4Wvp7WGotx4GIBvEnedwy3PJ
t1OIoqz2yNN7G7uScgaFFJFS5Z3BByDnfZwSuhOGIEx8IxsgIUvFcg0FPpWMWZmSmlClYXvFmPVfmmcFXIZFJ9Yd3pzF2IzzCVQyrAiwinoGKotRYie1ETUQ
YKpbg12UnS0ELCXdCJXK8Pva5inCPpuMo3AaOnKAdi00G6pUOy4DijcX2Xp7DqXMWXuw48pZ6oJ0VEn051pNW9i101_SasbO0sE4l1XaCvtkMF1xOfPcK23l
ZeKPNjL1RSdI3l-Y9mkC5sodG723etjISC1Lgdy9M9e1f-C6Gkrjk74W5MaAkau4bcC-1RNwDg21sQfWt0mEwacz28nfO2fTWTmWcZrRGMjz6zQWVGgBWcPk
1jGkZlh4CL0Rqq2uAzXxoc9GdjcJgXU1ce4k1ZZYUo7i51JTm7loAGU188nhuF-tze58c1U3P5BK5HuQWqi8t63q_O7tP3F808_sv28mla6oiXy8OpVmS_Fk
CQY4SWQ3v7MuAXGtkBCd_I3G0E06PKm3sUyFUazAecOWMEvGQ0T1XE4DJ4BV7wZi1g8PC03ARsyBgdudSWCiby5G6FAEnDeCCWJvg2VvZfxqQ-5gaEn2a62u
8Ets1xSzsGoYANbF_cmCAWNh1akgAGKOByMMVBW_i7UFPa1-PFoi3nK0jmPLHSI6GuZS_c_ZmCs0uhudnGsy9_K7DuAm6kJg0be7V2-qhtut4MdNayaDyFkz
gxPp09j13BACmKds1-86_dzt88cb6N3loS_xqAuDh2u7WLVba0RN2Xpw_a1vgs3DWC3BGpyHa1XNWx-frGK6DLX-gtG5acP0DnT7TOFRdbp7O6c_hK5Ldn2M
KU_AaVt_tkyFsgVW2f8WB0RHZFOA_ayRh0PbCmOIXtuxRsiWxFS7gm8t0-bB-Ot0jK48kXa3Fi7RULLGwli3ZllhCpS3WE90teVLhWsqzZ4uoTlP1-8FTTUo
zae8mkfr1Edxl-uvxJy8ndPFrwmcYZ4nVBEKmgNQkI5FAWPvhcto_bxApMDWV2WiFwITJJHEMlv11uU5SdrN4zFT46y-p8-7ny0E0gaFy0-2QsSsXiZBFs02
dhmn6F-BFAUsks9Gw4Q0NfMHVa0x9zFElBieOsddod0if1k3HqKCqcK7WUb6s0UHjNCXk1UPVm0DKHxvVJvcm42cvyCDWqpob1vGDQ9s7hhh7K_gUcyyUVMF
6FY3WCLXCAvNgOI3m3wjA0O7JpwgyY4sn4SCh0saUEsifHfnW4DtVRvKErVZIV0FJfxq61JsRN0v_u3T_WYd5vf-3cfdVOe5_w0XJpeCQDq8L3ih1iCGYAcP
30NKpdPRk1Bw1wmbvKQPoeVe7_JNAIbQ2eY1xNhGpdCJ4LoNV_1eZEwpFFr189CC0tzZ3Fpsxc-7xBKp_zNGFq2Ur7t0jvdS4_e7Cxf_0A8HtzxPKCWt1WTF
YljCoU0VE0HuHjKB5ROslhrRgTqObCdEKECfsWQxVv38K-MBAKPOpPHWlMTFNRLpfOq6oFm3Gu5Psy1ZKFhSDq4EhHixhFUXdPc19maSDVxxNeS17WJnjVDL
6L00xGmy-QecXOl_79IMm3-u-V1NyWVrZgWv5BffvvCdLJjtLbxWPFv1tVXGA0VNZPRT9x_Ug9srXlv1ejC_QEAfSfRu_a57_-3aoN6Uc_chVz38KUMFv0yc
jx6o-nrHWBTtrn1V_8DDEeA7qYIYU6webd2zkIUddO4dFs9WRG0OL1QP4OTPoiruwSR0EUPwPPgcdJlm963GDpwKKPn_eAKUq4CXNU_7okutj-j1EoDFRXXq
DHBrJcGUYkkGS7gXswudbzs_08MUNdU8lrNV6wAs6mEgR0S1v0-Akp46zmymkyzQ0-ryN2e55FBkeQHnbsZ6r8smtYwxptxNetOsLMqOc8CoFGOiLeg90Qvt
kPP_S1qywRMpiiUDWPEEND4_q998L0n0DDuOT5rl1r2tj_VkI_AK9HsbVVKFf0RLpZtZ0KZW7oX0e9qT2kip8N_Gn2DmHTPC2GCdvL4rkmy0eNQse9vQXuP1
Od1GWli7kDwyillvv4bxUxzBsWRYCLYoGNx4Fo1BO4tCxezZcxHTEpE_-vwBzm_SOuEC-Hl-mJ70q2oxxxS9QEUisbagv0-K3uLoz7Vdo_m3M6ygNRFxq11U
EvVJFyZ37mINqyujg7OkYe5go2_PVIk1TaOCkjpNGZdo1nJLFnZbkZ6ut7f3Tl_aoJ6-vGyyLNeCsdm-Huud6-y5hweK2XyygTdzET1ienC3VsEK8Gu3VbDb
HFyWNQ2MEZO4aVe7vxdPJmpinZXo-k0VZ1GEWhOEGFKFpgJomk3aIIhEJyoiRV3wuWRv0or5dlqddktpH8zbz-rUPBM5mH3bGyWVvEbIMW4nW0IMkOeGQ5_P
VIh-t3GCvdHyw35ebpXh8I86--UiL5BTU1Ap-mmbsTzKPlSO-1jZK0nmW47zWr4S3M1s7m3QukcpEkqCvafC3FpBCle7c4EZRFu1UVD5H5W76cVo_i5chWXp
MBtGG3Gg1YTF3kSVa9NkpqJ_e3XpvLK9FRy0fzmm_-0RJnBEWlFX7xInlxbHYgqRp_Ks_u3tSSTPCBk_nXTuE0pmpIs-TcwFobzc_q-UjEp-VMx-MQd5j3CW
C2Ks1bsrS-BDOkRoQVR_y0-gvXFfuVC7dW_bYkuVS5Bjt2SS2-kjWGeECF3AxhT3EwUNLF8vfE1lxsDERgdVkf4QVVCF6iHJH_xc7_JvDAh4-OLui_zfy0Jj
tE5Ae1XyuCdhn02EGiHWoBC5Gw2xUx1FAllrlhBDB-3XU680ORIvpI_qAPDxZlVZ2NFCRNu19tfKE-l5qMePymUk3KIw-GVENCdnVaLbWHEwCUYfAGhe7oIQ
6DGp33A9RuEHVFx0p9KSxSSJl3dcNJiY0qzcy0ySG8iRrKhbmpz8pPToj5yp7abbwmW8d3Jr3ohFJzbzpuSx1c_POD8nH_iL5JwzjyTwKzWZQipBFqYU9mq3
KyX27eCfSkJK_Z5tBLYpiZ1Ca5SBi__b_W-_mOc1-RmUZbwwX7XiclJ1N-T3WM1h3BKpJ-J86uEM9mloOH7ONm07fVA4cICH80RH9hB6uXk3bYVDFhkV5L4e
m8Tq_m2Rxy7CK2ixeTY-EjE0DsyCNCvwQCNwiFi77dWI4m7kBuI3kGAp-nFm8M7GE6hggfOA9dpP_KUUXByTC72xophD_84DqaR6thigJM2vBa-IVm1beI86
q7ChasXdGe0mSCkgp9DLEplAcs6f_e5w1N9CjFjV-R3e5DeP-P1p8le7Y8BuNJjhKCoR8hj_O7o58AyuVm14eNFCxjiaNwBs5C0_01HqryucTMxaQDMJVFz0
QxEXUpjmjgSPjoot-mVHIfSdKvCtD_7Gzm-ib2-x_zjaGfo23p7OFsXv4dR_5VEcUjzYG2UXoa4xEtsLukPxch6zCXwO9wr_ys5QqgNT_rSwwiOVrM0dV9fH
wKgOpmfh7AITQK933M509w400zZzd-s5KfodgBttrcSNKxMpexpf48Crrz-0PlTj0NF5plLKSIrpsL5hUT8jxgqRDMRYoJS6Lb0Vuko-b1TKZ7QsDyj9EbFl
NRdJk761JNt_OEV3GhFxT3jmjgUAsGw97_zWLLBLQTVEiTtzn-Qx1Tr8pVS7CV3oXv4thmHf07hldgmItzdzrsRtFnZGpbWplxdIpC27h1UCq36CYa679zUw
-uyZIzzs_vVrC8LJierRtJW57x9c8j4OpUB0Fm0KK3kl-llklx77XTVYVZIJH3FNYzqPUWfO7TRUExnQfGeyASUyAThU3XIi644tgeWtCoG2rixUnCu4bkln
fDgw-wzPu7RWI-bs8F0XOI2o_cK-xFi7YwFEiWN_W2xgfLqxhwaIG_Oqkmz4uPKna6XlSuolOw0LWwLPMFdqtkiFqUx-BwdLpel0IQXDAKg3WKYSu3UezO6u
VVTVZZ-4Wd_0FEc-xY-Oc94FNvxs5rHg-3cUxi-zk_iDJwRk9EFQdzq7FcJ_m6xc2iHwlr5q7jnfR7coOj1CvAYUtGva3DAFkOAHp0HFzrS7rL6dKJ_jj_Z6
89d0FDbYW0XeG0-b3ZGJ2juydGWuK1_7lVSEFmJDxZSyYHZGGcFex_whKBY7-P03hHAw7KWJMBLAvXEJiM9W8jz1-M20FJSLZhW-peUidNkt0mFH0Fe7sjtz
By27D7_W2bQCAaqCbSz11eCsEsM5k_j75mLwxm0Gxlu37o86KN4y1J7020EEyM0qqvTuEv3IWlpc7s3pFNd401TU2s4mcXQiG8nXW3y4tzq7iosWVu0e5Eof
AFi7du5cbmW3uia7-P0nu4CuwxVTVt6-zjvjvKdU_SVz1OidC4emK2jt8vZd-90nO1IY2N1td_LaxRt3H0wKXU2XU4m4h1VwuGSSuo4Cy8Tet-rplLUh17aI
539W41HwRd-AWIGtO1IDOz3ofElnfBfFxptLgddhFCU86C3uGSed6614-m0VOcGEB1phx3vFhYhqtkFEZMB0Fq2Y44FQ-IpY426EOv1Lzny2RmSAee2zzzZP
NmY7CxjVjFD8MZ3nHWpwF9dQrnb2nS0s_e7DUqN0i_jLK9o7VIuXv6umJwOkJxg-Vo2mydl486I4O3Gjk7Gh1iYJS3lGDthozzt_d50xYzPwwMjSLDN-LWoG
9_7kFlFayklklq7jN7jkLnu3TQUZThTYW2ZWtNt-8GuO91JF_Tr_rCxdaTOp5Ex507aoxNVtUS1Pquw1XSrtslr_KwNcCrwuhghTlHYWenRItdjtslCFL0hi
zG868VrO2xLWLBaMmTnSC6a-HQ6z7RX8k_kF2bdRtN-jQsxNCJXtdssy5mLC2tnt7su7WZxCwzBS3aH1eN8vahtLK4GxyVo7C7Q_km-3Mzzt_tzQxk2q0mQN
8jYxqy9N5D0gOUqSQFTVcjdzTSC43ROJ38RAvzlJ0lEa84yAAEJUxZyWS8B1aAgswG4KSgQx-p2vkjsMJzHxhtmuWC6qQI5MxLnRiQLqT_yh7rx0O90dlJo5
0j_TP-tiNr0H365mtNr-W2T5Jsy76Yd0XnSn62-Vr_XKMb1lR5yxnwrCGZwyYC6uglwtlFF0SXY8GQZ6dfAYtF-usrTRKsK8B-O8F0zVo0tDoN3XwBtthua0
uy7vUr857WjdlXru21vYF1XJuZbT02Tx-U71-FOu7iY3pPou3GUAXLh3WxBp8q6Gy21nKxBIE1dTkN-CXSSSY0g960_uhVh8V_iyWk2e_8W3YLspGAiE3-8O
W1oeYSTq29pqu27k6DWHgSI21my13YIUrQ6swXYC8STWp9PJ8N0o6Z8e2FAgy5Pz7nvASVAe0u5CmDf4BHOSTGmIGS3cf6EEGRE4sAtQPNY8RzL7FP3Z8RzL
-_yNmHrvoDy--z91K0og1d31Z_0Gi2YIvQJByP3VgftFmxpcPJdfY_7G0EAqQZ-4246WoKbVWeSR20zfzwfTYuVyLXqUf1eou1XmMxK3DiP4JKkuu74C28En
Q2mG-g7wjB0Zy51zV9RZ8V-TOV9WBDYg2Jmagd6FmMoAAaqy20HRDUV62LyJuo8e9gv6209z3JOFzMD1FmZuhPfm1_LnOu4G19HMpLuKwRTgVaFcgn9ugAzE
uA6yob3deNwh7fCzX2fvOopSglayr8y5FW_rOu4_6FFLb1P5-gsws-Dg6WGUogiA3CRodAp5Lg0o10PZsLQzAROYrGs1X_Bg31xgSvB1G_tncSP3_McXsffL
Ef-7zWm
}

sprite $image371 [130x123/16z] {
n9L7mhGm34CzfDYI7Ev_sx-4h_UIORHZbGT8B_QBb6XsormwoIXsipGG0EaNkqbg44U8PkTdSn8F8UeD2e2d8MEp4rD1l0pPJwj32UAj4Eta0hmEerw_00t4
-o5zExa09zTX2nAVXcWdBV3zN4lKhnPmUXsGmfT3NA4Ew25-Xw4k9oW6VOE1ZBASm6l_1iFoUvjkyStF0A8jPF04YqKjkbKTDYZZ4iK2_0w3-a8VCALYKIxC
hp9G8nRwWA1OKSm3NqDGQlWw7_X4aAfvFO0-2JDhtNsr3oXrL8l-sJAPEM1h2RosoP3PpOk59BmRPMixhAmZO4mVK08ei9YtAl6zyqVOVu8-cYrA5-SGDYN1
kSncmJSPcCJkreQuRWfMeCGMnIBuf99lB9CQiBQx-HY2rlL0nwaFFg1Gebf_kKnbxcvzHmo1kR29F7pGKCmzveEoMN--JAOs_qymHX9AZeLRs2XIcUt11vHQ
L0jt7GpCCRh5xfi6eSojB5rZ10XApchH-iCoevbB8ZN0lPllcGcc5lkWcfSBZo7uem-eOBFUcfJp_Pln-06bBlQ16ZOB3_711-L-cTQRUUQeXXqSXCRkqmS-
gYrAcms8wMPGYUc3-twoMZy8nbm0ul21HbpM-O1Ii5YqzjG7HoKJsoHeAJ07hEzkCLB8jJx8T8lP089YdJu84P2a79b4fgOFoElu8CbYNej4FFfWra4Z2GvU
7dp075hfWwh9y9TMCy6I9WM1S5LQBaHWt_-uymINx3Kdk_rF04-DZm1i5U5bBy0gjV70bKb1xJnujQHODMwjpYEgEfkdCiyyoD9uKBMsRDmVf8qyc57R2sXU
hH2J1u7K6ZiFAD3c3x2L1nQrP26aipawcwdoo8C7fO8AqJhyWOPjqmkg7Vwi2BbHCYLN1HSFbC9AE0z4z_7WvGunF4gthAgvbQZSbHdQ6QJiF71_aFu93zA9
1oeDXUxLd0Ukm7_b3uOMtI5EPUQNURN10rQ6mGE1gjIDjN56VOoe0WLRfNQDOF8W7VHidflzmJbgE8OoGudkrQ337r0fL6xcGNZaOPGfeV50N9baCZPFVo2L
vjPs-mE4ZqOvllDgQVe35MZt1y-oZmU1tZW_CA8s7kIXp3GoyETOt1-eQZasRbI8w3pG4RKzIUtlKzZz0VMjD7_WsMZPfqR8iab-3ANn8Bb6t1yGcFx0xV96
BGWeGZeFubcPmx9wHPP77ltIRd-mol7Y0Pq7himMlrfzpDsjQTZh3uPHTXuCeon7uu70BY2vF_3Js3q_Y8zyp79y60_0S-ys_C6J5JO_sJi_EC0iXxLAooWF
PMBne5Gg1TCVP1xRHlkpC4wZ75iBgn3vp8CvFw24NTlL5hKFDL_JA2yUC9Vc3rf2r3a_8AIMBSirY2DW33NXoipIU93EF13KpWCHDN7aNSir5b0iKEiNbZAJ
yS3Jeu0LHxOCB1iqEczQhl5uhdByQfsyTslMoGUB3k7e5mATHww5FSirjegmHYUvMzRUmcQ0eDOYVNu0KOhpODToZHvr3ZN3B8nWwnUUMFC3byDZ-8DDopKo
InD28aTXZ5EP8SV1WpU0ZOVk3mBn_8C2FsnC1WymBElhLABYv87HEQRk3oXXrtfxDiubX7DXpA0fCpKU636rcXRo0UiUowxrjaUT5M5QrkI5SVA0LSJSEbK1
_HKFdkchzJ9ZDlcjKQeTof6zanyyQFFaRFNHowFKl6kzpSE5G1-TZ1QMZ8_YbXM0LjU35EDHwnSgq_C-Wh_CmAVxit4EooXBwnSomOfGtjAZz7u9ZGULjtRX
p-__Dp0F8KmUfEIFK9EnkQinzVa9dyQ3oZlBpv_-Dr3xT1y-Iiqd7Z3ByWTQdSx6WqCK_tyN_lfnlGwGCfgMbf0O3vOoFGEuGStPUK0AvjU8cmhyd06m9aYh
SSxmGu6L1RW2HxzWubaBsB_zRo01y3JT7pmOoYJL5KWOaKYrRHVFk_0_V30HJXDmdkuZj6CGMJmO_O9dasFbzTU8WU3h34XWJVT7fHuyiFM2--MIt1-XgV7o
fyny0DSPU0xKETrtPJOUPEE1HcayC7-a9JiFBdRXVWCtCh1Zq3xTdyfCiV70-uM3Svhb6Ln_ZOY26ncC77pR1rzod7Z0ETsERyXANF-KSHJUoC1oK8ud-O47
45GUxW-g0hp-6Z7AmOqCkZBNTD-NO3KB1TqVbAWj_ho5Fpy7y7CEUjhsOV10K_5fNZNlkZAuleg8cpcCYb2oAzFxfMJ-09L6HwsyyOVjoBXz3Zgc-yQ3IfeQ
GVNuFsNWeBxv780lhaB6T9-rD3NQVWciLVqCRlvXYxzv3lBCQzkNIty0Mkjb1WBayAb6_UOvSF6WZWkerncuAExNwS_dm3xTVnrKW3F-zIt0mN1Tggwlmgep
b69Blnc_Acvy8_pBSt0Uy7m1_vLk5qOCmq0KH6So9FZflzmmcktNW71NUBTQ_mX3nA6rSVszIJZfQQUPVGZ0kRUz8RMwKDzh5m0SX_pMto5YRzU-tSOjI0m0
MAYpSG8M040SOWOkchcj3H40-4BrR04Rk8n3NMj3q4378TsYsJrs7Wrq71m0ny4Dz8NQ3NGSV08ydSGDX2Sd0y1nS0CT1mS0zcq7m1TgDn3sRGF05se_13aE
RA3Zu02ucMwWuw06-bGSde0h
}

