sprite $image73 [174x197/16z] {
rPlhdgIshqKnnZT9TBt_svxmcse3jM77FktvDzbVainrjMjP2Adp-WkHyazU_uqiPSj_XBViaQUpIgbvFc-1F9iLysnMpDE5VRQz8eNdKH80x7DvIrlaqS9Y
lXvzi9Xd7opcqQoOHqk0aKUpOkJH4c3aoQmOoO-M0FDiLioZMJ7vVm2RPvxqaEELiYLDFF4HEfGjBRGFg6PQnj1YP3ZlLod3Q34oMbXAw-2MTMUii9mssI7o
gzMt02rcpbf3Q6d6id9lVIu_pYXMfCKivNTvfy9fbmzzG_bnfb47YxH5FtYn7lHd42lIPblB_4lwOeMDxYfJJIfgbjrlw_i-e33nf594pUA7lh5S9BWUJQHB
WcRQZNULVzKtpPsQI3jh1-qMCVlKTpbnPJ-z4qOVR-cb_QD3ShVLB80cWtY_Ig6qyt98oAKSUCEDlg3945uSnCQh_cNT8sMFs2h-iff9ffhmjFM5I5kFHlQK
SkO5hl9FG1FGDtqdD_CAm08j_IZVrSoXlAAcWLKvHskrD3wwOc__8heUk1OruPfmsXgKWDC6-b5UwkjbFJJcOeRwjj8M0LPAAneQTAXSRdBPJ4iDV-WXBGQg
5g7DzAD4VJTMGKsmPqDQFjYHqa8B7oNvitF1jxFwq8El6MXl0wotjEtzI_PRbIkNkUhPGZDjaLPQzb7Yyuzh0jMicLP5MccnVq6kHF_YMZMMpj9OoxQgjD2o
Zn9wBT04UClSJQkshdG2aEDtofZ-1NgsPbgnTTre2Q_SzY-VNBbiKTI4FVJQQKKtY4fxhI_fNyh_hty9DJ6bq4WhQckbPSVR-b7EgQb_oHFFSYS1q59U_b6w
P2RtcgHkMcH5MfKkNhFtmpXeVSoIjxH6MfG0QFdnylvbxxNOMretBHuiqlRhMw0b8Ffsq28hqlRpGg_5sk-TDkfL1AeMf-tNbsfoodAWJNOLHM4vRR--3Mzf
LL_wye4I8EruNco_CQ6N5Md7yzfQV1yj2ekqFzQtjty9hDVgeXslBwT52JZjUDuSzd5PZ6ZlqYC1qjfO7L9tHm0IKDgLyOwdvH9msknbNMzv_pOjiXgbJTCK
RLsDy0wcfSAQg77QoMLRX-cG7K-Wmghag4Pej_WoJ0Sn7cN2ciWypSaOxPP52UzesYe1miO_XsUSTd9St-6v4bIbkFVXYH7QBNDUcRuZmgkMYIpxuQaHsYqD
rMmiAronqpkeCjejGOaEeoN0e_KLfEeBjB1fCXtFYwoO3CLP6UsMkP1MNGPAW15eYLqsHhkb36xLstijcC9FleiM8mCbm7o-qSdQI3jS1vG0Ot8QhuQrXvRp
ZcTLET4wRQJbaJ4I8AkSJ4Xh2wtf05vavTbOpo-UipNHDk7AO655iWSGe8LuNTjuXrGj5BPoh9mM7y0yCbpOOuJGaWSmYOoIOCOZMu4s8cbz0FVforavRV48
u1Hfw_0Ii_JeouNbsTfQJ5gHLYLCjuds4tr1sFkZFTsjKAiNqgeUFmPiWVfrG0buLEAn1nTNgnVIRgar6UEbMmUKm8pViNc_tF96NmnfQ-8zR-ZNLzG-UCJ8
qTQw5Ao-HogTCLRH1rGpCNoLZNf_ntpz6EjxP5mfhPuNopEfPdGkYQnlXBci_8xvmtkaCqAB-leyt-ihR2u9PrWHmYLjBKhve71U6IrMi_GvXmzxDGlB_OCP
_0G4-5dtFivTOM-K5lLrTIs3-eRtlriJhKX41BnZSIClMBtu9FzRWSLMA_vItx3zUwt4G8jNREzHJFLcXg2hoVkpNJhs3kAgHrNbyyCuWChtj1KXVFTQsKu_
dQTAQ08D0j12KdLXOmaE7iQ1z9M6H_l-qsfVcF2ElJ_yug1w0It4roztG_beakTi0LG6MlYaqw4lB7Z7tbt19fcpFbgPgWjLvKEyPvNu-XBDnvS3ft37wddB
adltPV7emfRKt5VQTVLA8cLtoXlUCTvJgBQvqDbNsdNr4ad73oZW7UDHbhAxqDbNscNrojbVjTgrl4ihBNV1tXIWB_ILIBltA1vR9baFJuDvRQRbBbHStbSw
Ez3Yh1lZzD26fv_IeWkyhrIWhNVeEjxg5NJQJclMwC8Maxc5jfOdab2FFgojj29l7CXSUo_Rlwxicy_M1BuoT_hTiTwnPjhuKT_HXVTWtypAWjuYxGuReJJR
2JTDs9oPKTfjatRD6-kWpzHiB-wS5ghNbhgTLJT1yhcC6AE5-eukh2OHT6MqjNhX_vLKi3gSoqZonGWjp0t0XO2oSbgiNh4ImCsByAHUn1WjRj7va8pJOlMQ
vG0KFdydRgKTRFq125wspDJrqrvLBvUEIFvyzUngAprdOxIWBzoh7bfJgRyN_dPrUCVGTL-Cq-ulMmRtgjVRUDLPlbFmRD7rgY_GmjmWqNlbmlAljFYCTdit
aAvlcHvSh_hoQNFGp56NN0SxzEa0loJStBGCXuu2lMd3r1MV10OxjrrDSdUpRfsFFo7mEq0KxQVrKN2mWxHGhR0jrE9mBRO5U7mtRPLUpocUq5Pz0QcsuNZJ
SEil_IRKVW47EvHsoxU-1QRXLpVDL2I2wpsqhlwHYAlHKTegus8hwoNpzIxAQIUjJxKAoWMjoa9fjso5Ht6ST8oJouLaMdjevp_tQgd6csAA1rhWpR1n0iys
LecVyZNJkb0-1ddfPgAVvabWdW21EtQ-QL9d3h2L1bf4pJZ8c_IQLYKsqC8TowUJ3DcJhJIbFOxZm0KIeANJS5ic5ccbTRKV0nVwQFaqN6S26rP2ozQGn8Lk
MX6_7vquCXz1sZAth27HXNvQt3XjoHUOLrlfnZMa6NUXdHQduLkm2OnqAos1ho4D1lpjj7pZjENZfldCjz9ysZcNoWj3tMPQKyCxTjKzpeLifR4zmQfTXoF7
PKyVhOaKlP-6YwkVPFDM-g1lIMVU-DQNk41fDmIVxNJ75ln6rg0DMscSTeh9rHeIXhgC5lSwGU6ElMFnNO4QjjAehvZgvHhoiEonTjfzU_jk4U36sx9TZzwj
j2RtJNkzXap7_gv_AutJyEDaaMsbl_GoeT92POksceTl205QXArRwGe-6MtE2i2-NdgPiZZHTt0DgL29UxRIngVXUhELjjUM6zvSQN4DAUcWSlTMMeHFmw-t
qgyQfRdITyP6edqhNTp1IumkjNe1QnCkwelV4DAqbJOLsRyf1LC7FCu0jektUDP8j6sbTN-RFV1WB1KGjfStpwoHQDnABzXcym1eCszisABJhNHmy0R3Oq3P
e-_2j-XyAtsyg_u71pj6tqotqhE7kKmtQpzl6h6Ldcq0QviEaT2sRQM3Ti8Er1Tf-LRQoo3M_ch6QKtAZ8Fv5jQnl3EXPLlfQCrLgpqsWXQtqiiOOJ4_fiMj
j2_39C3yY1QhbqiZMJ7o0rgeNdwq19WVq4BrMiG6is9-HEkcKuBOM5RCbrucEqwx9MChOKrLQxo-4WajNO9YNaF37i3yMHR9h9kpZkVDCwN5hRzJmZeol7z4
sffZIvpwMCVh42Zj5iiEsbg07H_-Ee6qe6yPm3f4NwJ5cSPYKBL-XJSwfCMPXZOSxE38hRwERwLD1h2EqtVcEnrW_MNUHbfzGNv3XpRQro-4qtBMP_7Q0rWX
NxsqzlhLv2xQrw-ddVRhzOGqqhwU4a8Bh0_4jGUp8gy1wvDv3QhMusANjA_7ne3szUXKMf3WmRm61_jaN0FM9_FQts7zFm
}

