sprite $image7 [295x189/16z] {
xD0t0SD0002nETFpPnipyBat2OB6vNwJmNnIY98KeYoL9qaXIbA8iXIY99KdII5AKeYoL4Xg94MI8akHf4PIP2cIr4YA94MM8acDfCXI92cIr4YAB4MI8acD
fKXI9AcH55cA94MI6acHfKXI9Acn54cA94MI6akHf4XIOocI54cA93MM8acHf4XIOocI54bgB4MI8acHfCPI92cI55bg94MI8acHfKPI92bgIyGazbWIzM_d
Fd0T2K8W33_dQK3Y_gVTE0ugKUhnvftYFy8dmFsYsvZNKEvkOqRLJlxDQQtZJ03LK9JfTVCwplGwKHrXme7g21D2TJLJ85H7c5OdMvswYgaOg8um1K1rX0ac
gYDC0O-e3fZOG7KrKo1KHvW0gaCc72X8D0Ec7gWgZqIclkMOHKHc0bEl7Y9zPqhEr0FbyM3Ah8twSU2nbckSINVpB0APCgXKm4198I5JJfZKe3m84vEAfvGf
ZH9dIiwa16M19SQOGcRpp6FEb9mf9A0yYh9emhHhA8koB2DCi7eYI9mfETEUdJnOIGEc_G-K1ozvd2bs26K18HDlmkHcUtu481CFc7OxK0I9CV61uj-BslM-
8H8liZZXSCiLaJ3Ej0SdVn-9XqmuKA97QSw4jrnrtp1mgLQlaGWJF0uKzurBEHieqL72F869F0xaa33EzFz0cVyc9AIQ39JSKPf3sI2tN77VkDFbk937WJGI
Get3fNeScEtwAvFteOQvsq86Il4eyTLRFcxabWlk6tUouv4y3gGU0RpNpxkb62ZLVUERDuwNOg1KzuqxhPktIhsUg4R2pHksIeK3bCmZWEUF3gSdqyD9zIXn
gEF7GonUdfkY-yQTdfiNyDoKUWJmd1pp1vJcld6eos7u6WoKuhvngCNTnoY_Vcaat3npHoaJUmJCeMuVItMXp7IF4lyMooW6odJt3Q7mcEFZe95UdPRZnQlL
qprAVFEy6AWUfSq_g6eauXHmotVzbSdsA1D0YJm2UC141afmtp36151oI1XX2e1IUGJm6DEQQHub3XLqeAJt3Q62IPdO8u17cG1ARjym02AF0zbzcpCze1ff
q_zYaNe4y2WJJ9JUKSAc0sMY-_R-G8aZRR_bclls_YqtuL6Q3nGuoI5Xb2cYX3ANGzh-VxKaZn96cV2ty4qMYGyKVEPf8t4f-CmJFKhOXCbxbEZ_rThEb4Bz
C5EAzMDCgTVxJ2aPOseaZ30r4kGHcvXIlWrCIMicHEg0YIXraS1K8dN0n94wO9eYDTDSgQ4s8RNJ9gI6-XUGFWC
}

