sprite $image429 [100x72/16z] {
jPK7plCu34HPL5YK-nztYnd53Y43g_MVGVkgdiCtec4pr8NWfy6gPjRmXuYYTaJhhmWizedmBmZKxIlzZsl1PfRJy0SYShJ-GaIEbb-8o17wXOY8wX_JKdLD
g1Uurb-8QFWzH2rFHEYAG020tyyW_2T5T3hm7hABfZkvBK9h1WbFl7l7kIKZ5VVld3PCpOsvLtCpKtEh_ryBnPZBHxm4imRUJHltWw8bABjQgEVcCw36fm9M
Vu-UvQ34gImRMgxpZM44rrgSwwQT8T9YOd5glTp9dUMdvl8cSvJ9r1gym_h-cpWLswbbwyvrHaISNNRJcCOvrBLyuOtbfn-lzKsmUEv8E0dvMSj_ltEk5MUP
pWaIaBOvMxtABvArP14viqmdOPPQvgD3GIYwagzbAIBdBDC5QnsWkPbvkvPHrJrwR4bB4h7QJ9OGYb1CMi5yQuzIOqz7917BpUGctQuX03hgNALTdb7A_Fl8
LKjTYpZBLCzHQg-C042bgxcRMtcVcyjtHYkevQJDX65MfHK2U9_aVXHRpQMPMofVYlfAzInJAY1NKJgSwgN8itoo9fY_t3D5ZdFxCBqow9YECw0kgt5B6A_X
dYdQpdUFMmCW_Dok2j2_pv9SfanuZM049QrRRB4bkbcTJW2gwx9yQeiSX60aoENT4mEVtoC2LCtbAsk27cCQmLXJXB-Ndd3QQr6csniSXCp8b4uneC_t7_sQ
TXwBMPE5YCJ8bFFTKzyKlfmuozJVe49m-JGQ8X9Z_L5E-UVqITm_POg_Y4WQqvAnbi_do5qPk_crJ6fkb1WnfZMZoLZAfrE-vyrqcaUzzlMEGL0iGq8sdl8r
RoOLLKrZkcTWPqe3I_BDbfif4-uP1jr1xkI7xxlDbCQKyjAJWGYXv5v-RAOzmikWM9oheBLwOHtw9fbb-TXiOqn1y7gqq8UxAziO0eLCW7MnZzsw-ZrXZHZp
bbBtoEZqAbMmGbrhqSqnHV4Zyy4LlN57i-Q-6jWoVYk2uPgffH7K1bZTkR8aohQ8bAcb5o_5gJior7pnzqNaX9On2kfmmuBCbhJiY4X9MXgo6HQes4Th8o0x
OyeY5bg6bQx0M42zCSSGxyPqB-8-xQ2uIGD6TUh4t1S3snAHWt7YK6feepUkW2r3V6oAo8dI6bNHqHeZ5lN80n5hBLQG3GiHGp0cPL_4EjNSXqWZPgPWp3mG
iTHYdOYGpS-CrnCHQosTiNXYF12HKtIuZy8iYV5GHDOot5tJh1wAM6j9iyeY7eSaCvwBM6l9ZBM8nreouxc8h2KnxaKyrnACUn7FjGHZLyI-bl7Q5R6l9KJy
CgHMO3D_0m
}

