sprite $image236 [236x176/16z] {
vC-d5S1G3C10REJzjmtKCqhxNRV1PM_nLEuhFZCiAy6oaZpXU4BnX2CAHHIAA0nHAA9GJ66OmX25OGh358Of35KOfbXjUfLp9pgEub0KXi4sNgwFbFT_s-bG
ELAi0O9lhYkKyi_QAtoD0LTmaeARftikn6BTbQWvJ4q-NKbRBAFqAPUleYsckMchYnpQOfgVjYlcVPoQfftyvx75k33jLJwDBTOvZLMV0VNwnvLzXChsgA5y
4bj6L9STQos36a5D_yglhGYRLC6vBGp1TivkkS-pZ-Ke0TB63QUYdjv2YCRO7gdhEVKgW3YtFxy0A0VnvxCvM6BVd0Z55rX833_xxvSC75CpfS_QfCVggToH
yrZ1MbofMAlzCwreX3MO6wHoaDJ6MgNd3vDb7LPlZTDEhXmdTLcjbT2z5gC9j89gD0tYBtNwIULS3B3bubPMEjDIsJBS6XHdoKvAAfDffzXXrMqX_RQrvcap
1oihuhIPH-bEHsM2RMn4ULKwPwrbXrfBVpeg0yHFasPYasdLl3wL0Fbrgm1ehnykFFwR3Qo14-1c2ubJhUxqL6A1agB_LuYv0ZmMuTqnp3d_tLRYyjW2GAeY
fPLL_2zEr-CxrkocjO3_9qMPbigaqTRrMv6dhTRAuUi50DejID7tbfNUDH4UwSfzpIeh_wmoZsAx1Nt7LEr9NDp1QPlJibfIAXibdWCyDGsZrLRBU-yS6qVa
yqZcV6Z4cTUsIgbbvbHUifQ7XfRefvrcUdcYkiBXQvovbPUi-i3vGoYvkRtFK7fzAq_Rnyw7UNgTTzFQmXDrGAGEqQQfCo-yimnfZ9MdhU-YyZxpfwmyj6Ng
Ad3u_Y4hYrDdhWpj6bGsbsiKEHLmFcR5gW4xR8x1kVkEc2-IufIcoINbWm6cVnmRPyKYgR5BayAaAvV3qjoz9-EN9atAlE8Q4CSlJSgc5oRMGsNfeqkJlDgQ
58F5sPsiroz_aJLza_MJIvF2hvwlimnVceJzijgAWzAqNUwmAfSc7QMb1XmLjgcmiWgGkvScrQ2q5YdxRUx9d86JabDOfCwbIG8TrUFLdiIvbIO0OcFb9Y0f
-FjctF7I9AOyOr5Fx4dqCnVB2JgejPp5jjLoN5LX1TAt9wIUK_Gyk-bvj085Lb07x0chw7bqWtjLH7j9EsuMuEIUT44PHu1jnCOkQnwsCxJMCghijIzAsCUb
08DwIDsfuJkFrrQC6ZSBR_H0ViNr6KZDixqH3NfyqZv81IIwVMYgGFjiRqHSu65T-o0LF-NsSHqNpkEdvjdUi25iFuYvYe0FKgM25RunDEOYpJrIdjUMB4E6
iFqWZXjFeXhkT6zZCj2kBHamXAqFR79xAnv4QcFbj8HHsom9imkmFh0yutPNF8ZawPx8_aDgF-3-8-ylaSenUEUS3p4_hQpZYNgmMFPWdzebOJc6u5q8Ip8u
hFe3cvlb0JE_5Idjj6wTjiqMV7phi38nUnmG-6UdjRPBmjfchHRF6JqDS2U-TgRrvDgIDg--j-f7SPws4qhLLcgptUDeGPlOl4_PrS9qLYQ6Nmo1iJSFAqj6
rZZjPR3ujxvtjhB5o1eKLjrBL7fhl9mLJ8cLQQziPCrMQsKgDkkmfhqXN8siTVTflewgnyhEanK7iRB2xSnLb2Uh_lgq_Sni0SfXUV6Edz-KN-sattw3ZfAg
nyh6DCuNe7OiJNBnnU3B_FaiL43wg4PO88UvVTcezYrDcjEBwwSiRc8XLIYePbYUu_p5fakJAcyF_8OPbLNr9QvQBqsIdIqOK9dgtKXLT8ikPiKMBAXCYddf
dIKi8bAO0NKqDgYi-YhmCMpwNIjwgiKsCLwQf1-_umzjpRgbIVRZT_oX5IJTqYHxwdWiPtnDSm46Zr_xSQnQ93Ld-wjWXRegfbW8FsZBXoGmfmhUgWxT4J6L
LXntCnx8-gL9uuVlpMGWzo-ICePorEYjh9RBf9VYHgjUUtqfhSJ-NQrKs5bPbRyinOtMFweLdEz6xEdaWb9xAwj_RF2Igh1UOoWBUhiH-xUuKg6ZqghdNXzA
Ax7NvnAgfz9wVIwXUYkn5_RIQK8bLb-jSaMdlPNPUuLE0wefbWTOhiCaLO4TBgQIpCjRMxBq68aSHMKOMRqdzwZdDsfL2DLKXkjbRsLVGMLVGMNVG6LVGMLV
GFrLR2bo0Qg5Tl7t0fXVoxpFFbQwkVpqmylppys6rD5OttwgI6xU7BeqxqxdvujuFEBF_0Kgix3oM8LdgvkUaw7MsyaCh3DtdrQw_-NuKmPQRwTxtpeLS0XJ
aBakbekFup3hhQVthG4yb1Iu9uhmm0wntZfxrpfnxsabx-ay7cIzTVU6TUORcpE_4H_ZDZTFIePORwhKrdLHVtWSlUKX25kVvMLllIbJMzFJ29M7m7DWZxJU
taXfNVSw_mnX65ljgKnf3UiWNeUmlTLUobJMlCBMCvI2q5hjhqqtYnJMTRVlEWSAOdCTpkjymz1wiwhVoab40WNIi7XLdfzkkaLllHdMRUNaiDAwibPxCs_o
d4_IdpyePPtMLSZ_utoO_uSyqPquUUR_VbZAEgmSn9dMf-cZuty1eF8ZV_Xf8H-NiWvhuL72uTUlI5FJ5QJij7KzFKDhHMW_Yc8jFacT64h7QnU-W9Juuj7p
gqWbF509O3LGcYy4PT36bM-RwyDmDId39xlzUby2PLy2PTy2PT_YPD_YP5_WRFi6PjjtADkkPFmF
}

