sprite $image227 [236x172/16z] {
vDO7RWGX38LXEhm5Q-z_stZIo3GvFV7uKzs-lsGBxdy0x6u2djafPGPAZTHYnqBfPAUK6Kfb5aed2wMJdL9cA9LPA9qib4vsIfcXL6QXTB9JogwKcYi4Loaj
thdO8BX2QGtkKOBsMaYYUrKWq9sQt5jUyTf2KBtRqBgs4BJW3YH8r8_lvDMjBGJ5dGiL0hsBkXSXKREeSJUtMjVsuujQHjyzAPy_AYw46waJm-xvq23GSI6S
0eWwReEegXfaV7ny6z6uWN7jo6uhG_1VKmzInbBwh1Fr-F6rLN8XNEemBOECJrmR5PmpU1xVJMtvnDh-ztDcNxheWyR1co7ur-SC9tKSwaI87xys_jTp9kA1
MJF1ZHs6OIWouybY6-ZzJ_lN05qKl3AqeVzzWSwhnP2I_5ceiP3tcRBD7pn4do7QxiZsl_EPjHFfksnRcTljvVjCQUz2fLD_o_RXopP_y73bCorSAiXsLhUN
xpCR25MGhHqRymSFfSkaSsDZlizKy1cusj5kBzzd5l0PFEFTNlxWmIGDtLvkR3mSfOBFQBAjkR9bql8UuYga0EFygsuFGyCfeXfk0LA0UFAxFGeDv_NvuJqr
Dlhb6wvF2E-UR8-K8AL-Yfx2BRYdWldGcIZKwpzlX7TdOjMEoRGyHOhNvuTtVsB5PvvGOuZpmxi_iHgdLQP8yHIIxVr2Ng4HdaSBwPxFom_l_iIApxJolGXn
HdZt9rRR6EsjRSLbY3F2kpUnsXPH6e2gRoiWn45ujtocj_YDrgK1fEgt7qRsMdZtVQQCHGlhszyWzGlXtVIPTRaj3I35vlJLUrD6zjVtlgp6PeI-qNTbYvaK
DakG-dbLuq-iheBRKvSjns_uoc3gftkt9rO5l5s07HeHOEgdUpScLlHAwY7sJUQ8kaWZUxvttep0Li5aRTKT4GYoLLOr-_LJ6IXVaxNrrWHQ_CfWweTxBxGP
0JiWLjPYQqpBPGh2bhgzbPxAl9zTUy_8F_zaRUqObYsd_dDL0mSt8tKNUYmiom-iysJxqhiz28Im2W1MkjHtLgRbXV0E8tlizlJD29V5rWJIarMWvJ85sK9i
19z1duyARrY-WLM1rTuHLh7RYpxp_V_vBAhm60va5rcPLby8K-g7-z5McFi22eVo3Qn0wyL6xFR8P_I1xIgG0gjCAyH6a6qhiGhv550u29LOTV_fuzsUFk1U
5r0uN2gmYhGybD2xFQn27jZkUlaognuRKRRrksvlwzA0-ybMpENBhET9wFP4eS9e4Nr6PvtUxSNOs8JoDNo6MNrQA5FHZ_dPd-4p1cj2jsVuJ1Tync1DwFRm
hD3omQNAhBvikKmh5BhgCulXCy1gq6APqlAYDyjdcDHd7U_sS2OwCH02gimwtkqPI_BrqcUQSQaMgnyRbmSaMT5dDaEeFgilMqYoOlc-Z43ei_hT7lzmtsTO
g3wht-tnn6JTvmN2-QpcaY3-y9EhmE31zXcVrU_s8Cc-Vu3MYOC7dtKyDaAIBI5T-OE7-Qn-jnSVOwqXNJc3XoHMVKaGVlZbkjNmcJnMNRRlNnXugceCk1DO
ZTXOMX0g7Cbd4bWz_pb_EAoCZS63TTv4Bh-GUuMdgiRWmKTz4s5zsbj2LNp6HpLeBLX0DNp68asWfKSxUY1iewI9j67SQ0ouVLGRrZUWDS5dc7J-rN9kZ6TB
84schTVjNZ42eK6QG0ljdZLuy57dolRGPBkjh-VpOGounqdpPNkUVXmzcJHVjhttayFmcOcaUR6nrjeIBZNvQlamwS_YwwK601Y6eTYzUVpn3iLa25Q_-Ilr
sdsGKYsuCs1iGVl2qdgfrmv8WHOK5OmjaEBI3aYDTW4gqHwGWhG7fB2q0rAW1KK5zmT8RMblG6gq2r29ze0KZ2sGkjA2GMLQG7LQ86LO86LQ86LQG6LQ86LO
86LQG6LQ86LO86LQ86LQG6LQ85NOW5Hf0rIb3KYLDY1Ls81KQGDKfGr85JOWLTe0LMa3KgKDI1Ks85NQ05Lf0rAb3KWLDY1LsW1LQGDIfGr85JP0LTg0L6aZ
qWS
}

