sprite $image153 [209x152/16z] {
tDM5RGH050FHSBAUW_wh3LaOEAQTwU39N_hh2qMI06j9QHPJciL4VeTcdZH0n6amAKT46jaMhEQRnx9IceMKPY6HPY5b_s0XuZH0n6a0U3XfG3oUHkBXD8Y7
qm0Hfu77qyXrE2DdYwShhkCukwUSEzuyywHnCSug5ubuE0qKrzOQb-2OH2DHYNAD474Q9auJSHfuF0r4d0OYJWCFfq4ydaP4d0OUJeCt4-VmaLQvuOXddWO7
SImZlQL9HbgbMKOQcId9jRKcusmMPShOC8z9bAcpUM33vn68qZIYECB3QPGZQbMEg3LHHJE1YW4DAEEh94HHGJM12bII2bIJ02GY5IGY5IGY5IGY5IGY5MGY
KP26LD1caWfK4f1PegADvIl00cgJcE2ZUZlHLLm7WZ1ijiHTvT3l_xO36aeAuZGOIpZEVvVPj7sg3dDMhmJf-eRt2FG9Gkt3eJrm9siuQc2Ilf4F7oOIPtmI
gU_HhEGe63YmnqdKSjI08v7mHo0gF2EFf7aK6RyOnA8Hvr54CCzEH7GLW-I9Wnauw1TUW0X0uubYJpoHF50ZYrp54mc4LQEAF8e8FEz9jgt8uqY917fY32cY
Vm4If_ml9C7C1fed5gqv8iKY3iA9do9nrWKYFN4ZSEA9NZWQwS-9DDBcddWYo5CXqgRSb1DF142SEX4i86tAqKIWgXUP0eVXQ2Ak2qJ1H3r6klfNKRqZ1HFr
89atU60vuriHRDNFHDxaEQTqmbBAEr4yaKRQdYFGvUOfoosHM3dHZqcfqME7TC3olxUY2AJ0RUSHQ4ffMbGe8X7St6z6kdeh22SD958WUdTp2jnk7Gs4Gpek
gmY9lhmvZRIPHw2KBYkFpNCaUWzIu4OSWIobUGNAqpIZSYBxisuFJmpApw0fLqvaGI1Qewjc49v1k85cQxuvYNfVMmmgynGT7O5AaFtqpRQumbiufcbPPLDu
TFKWw_pmgCTRSkSrgEHueXgGwd1juLiAn_8icgUvQA9ca7LuBOXUvlIMWYAub7QGwhoEGCGnpSjhVu9G1L8TFC7DdLuzckZt88zhV_-1Fm4PktBMxx5EoskV
GVQftXo9SZe44_qMbBsYneakuSt58BI1bFbFqXke5e02JoM8dJa2yPAE9Ng8sWUodW-FolgxwFmHX6UGVQu39vee7z8KWDe7il3QEeYcbEOIWEH1hKVrdKSL
tiCbfIa6iSLZdJcAUkrEPwuyU834GSYf1oNtlgB3hBCh-VG0oODwZWBxpgD0wkhISG9lsJbTUE-L0si4kUedcW_frk5ulF-OvL7YrBS1H_5_TafA5-SD7BMT
HniH-K4w6E_vBU2X4UTha7d_2aMowNmydZFbqTiJ3HvgdKtY7prF2BI0icyLOex4-DhZcnPm5ByX0MJiwJzIYVuOgFRmwYDqry23YBgHe8t7hsOaoBEBplmq
4gXpsqdlHM0mpnxFJjS6trbNa8WuccUV8-sV4xvvfsFRRroHy5Wdkzen2TBmwhiF99Lls3y
}

