sprite $image5 [236x176/16z] {
vC-d4S0m000nREJzjmtKNLXwUMsWURK1CBzhx1POhZIMWyYJnfF4aqQKH9H4b4AKH9J4bCAKGfJ2bCAKmfHGTQ7cJlTS1M4mZ2iWuKro_zSx--OO6sD-jNs-
dir_2sWvT5vBb58BD9vCYu_Q58Xmj461ih0uPMLuotb94wJHYu3oVQr0NFeSLYYVnUBPh74jdjMAWFIvh74idiuQrXwzYBeTgrnaHO3gjR9kTf7LZmrTHCkn
3XhutoY1gHAcea-tMf2IwBz6R5c8Ka7JpMP2GhnkbEWIwARQLhiou8dWRrJVV0rWOLjTDOUqJ5CFh5K1AnpKkFKsetwC08AZFay1gmyBlxN4fkqoVLM7Pm2S
jIB3sjKSNZQ3vWFZlUKydbdKGrRbQazRrp8pTyy0M3UZMbO_5iUimZ9cyuAwwtqgP0u0ArArh7uiZbe1bZvP5N8jC-tOVQQfcbO_5W4hmB8pRV7JcFtFM-t6
OxUqkriLxmdAPDLz4v1yzvbvw5iCm-h68ce5ot2zjM9hot3SKVkd58RLZKNSkZjjvzzOiUVXt8YerSciYRucmCLMGAGvi13CKwY2Tod3jFgn25ajXerbxH4g
VGtVi1MPLh2IOvsr5swxvKUQO4M25M1ZzS7VXErfQTzdW7DMv5e1uRAvhE1FnlFM_dqcomfFHEkj4coqEK9Nbs8ltFPzvhmL1wnWNOMjjWReKAnZQLwfO1sr
fVzELBpMw4uGDXjRrypubyZY6RtYse0JEB58p6y5YuvcGHV-C30sO_aRNsFT6CDGCQvO5Ntz1qeRehOqNYBLthNM3wl5LGNwHmHMTK1ZkQtnRR_sOpMugnpG
owt6ZOHL6Vinosighp7ZfsLvJ2iL-n4FeMWsTYMZrkmrQLrHLKQWKOrToQjhqmvLJlwD3GzKdtVtmix_ZHqFqYZx7pmvOUeNUkpXErNHrnAc_eDCssvAP-Xh
alVQDLoROzllMBJpD-BQgEmTdv34gRy4_hwyx1tz2bCQd_fNMkqzXX4TlewTcCkrBM6YWW9J_u84TRK_dx2W6t_ZvR6Ct_SPHl1T3KpzgwOjnGURCLTp9oeZ
AP4JrzNkCb4PQKbyiCttkC-m82zcV4MzrLAcrqefRQ7ZitMaRyQm8ZrgPVhNN3lCca5bP2QQ3QsJMUr-Q_xgYz1h5pzLDozUAzAfK1KFeVojEwHMtVSWKHJ9
iQe67cgQBOsTCpvmGBT7lw0egigH_trbxySntnv3zNyuBz4lAEfh4h5AvAIapHZ6IJ-7TGYxXx3gUMjt4ct6uZvfNe9V0d8yrZciD4-12hdsqbkMLT-JKzPH
fs3LXPsM52lhHnomEYPg6_gQqEoRjisnSCUj-fc4hTrsa7utVDEM70jtrChw5SUiL6wTwn06m2BTzpqNnqdpe5M_av2rtZefoQvpb_Y9n-xsSDpA-XCVjIgM
Mpl-x3gmkAYmxy1YeRXLVtVKYjbvKdB_m6ALzUzbRZlJDcWL_PqSiZRxUfezJbYQOm10zgTjFMvb_HixhFwJaaR2rR6TjFy5aNRSgki2ri3-_0-Z6UF9Us3H
RnLT9m5hODkFjNlsVLbQbfNrVnomHlRdcPjZ041GSgow5P-m5XZI-4SELigmYcuMiCRsvrbKNBzjEMqLDGfQ5uSqbaWzPsMraf2rzRUMjefoj9XFM5djnB86
Qaa_gGhrXbL2L5N9iovofv-G8Z6gggHPkygrLjPRoNNM9TNAwkWoAsLQMLqndj_AweoVtYhgZf_SgaSI_8vAgOSRbrbP3yR67_TtbLNYLngtCXoblwIIy7S4
ki3A6eplZurqzarzAUykTEM6WJ0ADmnZoU__jhqvNg_BE9b_Lpw5o_1fGf829GlGgXUBbhsHz7T3pKuBiZwaVs4DM925YsyMBCW2ALIi0Lgjb3BOjzQUbboj
PEUxIYbZ5MW5EzGCzcywNrFgRoLxhuMtbabmv2Wu6imL6y3LZPHoimPmPL3A3Hl05KAXDci0LmIbx8B5-z9Eg3vOChm2fy1A_juJfmFL6ri7VBeo_QaLgnUZ
hCm0goVv_1jZHJfJ0x1VgGqu5HdX-qeOG0KhAzHAlL2f5ofrGgLUgDGBbRgXKXzKVopdW1yf7L_U1drFFywMyRh5fqLHwKOhZMVwGNixWIQ8IZTQQVWfbROe
AjrY7QQFVZOwO-1RkQWoJ4h-rWhSFlrGCr_KwnLEgO-ZqXrMucnI-_eQ1sEihCORfu75KUakwyxxXkVbIDThsyvOQx5IyhUszp5TndgzmYAyd2p8MpYLRh4E
u20UZqLwvla_7_zeZ9UIftNYSWyuCsGkTXdP5k6iJV5KyhEsUDTIzhF6b1_MvTYP-YwGahyL2mlnoIveVbYtki-P9LHojav7s_w2t8jrQBiaaPHShFD1YGfg
JCYATMgx99MK7BV3DUDzZoLs_TggavAhbSQszfPFi7gmE4cbv6pT7jRdsZlMiMvYARbQhL3d1X_cYNVffUHdhGlntjuWtgENafzr-sg8KwCwGEEvHtbkKRBh
vP6enNkRREVGVx5Nab9IbiEJGZlWPcczG6kzE6kzE6i2fpO1Kvn0AU-LZ9y1
}

