sprite $image391 [362x328/16z] {
xTl1RYIt3eNXtRWaDk3tVzjur9vmKOqQ3A7w-n0-tD-Rv8FmWrArFrN7u_5uF1wFn-FnU3oUCJv_nhoPUgpvOTIyzNAsDJ5ZKDPEI6DgMpiXjdQkdH1Rszgv
jhMfdH0dnDRU-9nhvzhMphMjdMiVQrix8RPshfqGvzhMphMjJUs4-5ZRsXkV4z9wREs4sDgvTa9iRMldsjREzPW-reZprzYQWLxKqmaXd9UrtrC9PoS4WBOr
w-nS8yuvnp6cZ_NzpkFuFSC9kVz0VuzpZJYlSQu9PoVara3dE270WROrwvmpfY_eWBDp3K0x8PYpDpx0sRa6DZld6ZZGpZNZx5m3pau806rhrDcvPfoTQs2p
SqAu0-s4yCwsvfrzGGS2xLm31ze9WPozyV7EpZKFxLpppiurx-nS3mRQ2G6SROquEzUyi_x6DuIXdH3UsGdXdRtnyPkTB-YGitCz8MVdEc8AIwTrJjTSHmXR
dtFz-3E4-bxgI6fTwuH-EOakQftI-WavIr-WXwHrH1Fh2-ahTPrSHpIn7XVGXQFE7-k4ri_rIRgkpbgdT9U4Z37cd7cujw07P1snovfNJ_HTwdVcEaxKW7NB
etwYhaa3kMv_rElMAKqafFzHJvPubAGfw_v7_HjbFXvbQI8X_OzwF9tZKPPcZdN_epw_dOlIdm5Pzp_gpt0KfTSSqzPdzHDvf7DDEjzlq5phMwzvdlEbli9H
btxrnSx7UhoOTAv9p-Dxd90Bw0nqNJhYR8rVqFMTux51EYBHmhd-gtDTEgsTwuj0Rv8Ev_eYq5kbdUkBSEoLhYTa_81mR9JcSjq_75iUcFRdsiufVM7D9qG_
q8znVDQbiOJq3_Jp9EvwCpq0wvxX-4Cpwj90hlk78yRnd5sV4O4BUjD0FsVdPqG-r_hXcCTpneOj3qX8yq2lS6oK1YxeZSEnKvg-eEjlTkcyNvhFjVvcj-Ss
3kIw_MQtHnh8TVT00z90hbK3dU40f85SgmSw7e0qa6lPS6IW0MdWFLL_imEaWOJeNxq1QU0zLJNG6Gv0ciYr_cR7I0FlgUAR7I0Dv5f_imEaYOJeRtQ4D7j1
vyDH2pGlpL_G-SqEa0QizJ-gGD9yhlKtErwQppM_sG7IQ49KFwh0qiW5NVYZ2Y_Dvre_qBmq_vxARtQyD9zh_kfDI_C9KGy7ByrRynzLzANvzrH-i-Eb-Lpp
cnqlpIU43xIcD7z1vw_Ul3IVa85lThYqZ3NyKQMdD9zhVhFZfVaBEd_rvgNvXB0_bz6NvjzJ-SsEb-PpZMvslBH-hlchDo_DvvhPx7XfnOJmFvVXfRKlwFnc
nqlpxwd0psLmQT5S0viTBIsRQ-3gpKeBvnhOx3XfxOGCuACA8wrl3GGQanRFDNBrvgNrBkZ0HnL8MZiXrQktfGllgONDpjA5N1UktfOkND0B7rKiNSXrPREp
T2KXXStEqiKBUc6pitGj8PNDpj9rwqAWBLt8TM6pitJ9kl1HnTAbX1J2OUcITI4SbYubfF1HnT8bwyBLszAbX1G2RUdIUseXq9Ok9UITL-yup_pdEMhI_7lg
-y8HSyECZr-_8aSvrncEXixpopcbnHEoRxFZdOzVQo9QMBzbivkRmh4cEwsTaCQ1NfExXxhrOxODnu9EQV6437gps-oSqjBMET4q72ajdf2-crr2wqj7D0zq
8-cO_JQxa_EIdiUKjvwT0vtI7nz3dRfvE5BwunXXwVkSK_fhj1E2EkyFHqglEVIbzGETq1VIohdk6-Ypj7P2cWRwB2rltMkpkvRMJaYxg_VVfKKtlhw1Fajh
9wJfPdUMbhVk7EYpj7AkzSDHa9RCjVncLv3MJ8XwEEhIQXVqZflTMJf6qghckdMWKphYI5hDNEj-LFb7wPXfBPbhiK0VptBKVjOx3kLSQuNZY-G9NQ4MpxLI
EDQHJEU2jN92XCAnD8w2SWzheN1ypJpzzKKfrv89qN0UJuRJtxbKSwsuyUa4-eX7GRfFGcG2FGj_kzNAMYBGAnm5wLQvVdUWZtHEwGtKUXTqZK0NfDibvCtX
o42dD6Oj88rkTWNebXTqZN2SdQ5SJs7fsEfSWEwQwtTUlIlEVTzJkmIwVwwx1Bf_GWGskm9qHslO6GY7wWMT3yS0mg7udjfbi-kVa2wRNN_hTsvsu_XavwqR
t_isktaS1q0jyvxA1NgUdOy9wAeav3sRNOpb37HQvuAEXECSwAyfV0blVK5_Lw0BNyARlwVYcrqy0mriUMAvPZUx30SWBPPhBXpf7C3DHU-2ZczsnI_X_HDI
TuwB6LU11gH1wxhqbfaNWGQa9TzJ7_TG7nUR7I0DvvgNpl-Nk0W78AsOaCVz4ncERTAyTGFfT4Qb-GiwBtqLQDwPVq_bfJFGWBD-hhk4e_y5tU6WSkrmKE-f
TpaFs5a_rmuqTK5teA4BkWDD9GG81-AiRtrBE0OV3lrSEz1KhhtPKGdnPaUzfpeSr0NTcntrdkhDZihrFcSW7AtVKnreAjTKe9qGQhEpjSD1NT0T3kg2NdV-
jytE2Q42RMigqCwr0qrTqAchjnFIvQDA__TKXuEwe7VvgDB_1q_KPkTSUxEZtbE1G3lNYnhOx9oG9GriThPUqa2WdUib3GJQkLxIm6RdX2nf81osJkdTuN2k
NqW37rLyGL_ImCzbd90b3GJQ6z-I1WBjZMz90vkTSxsaWN0urw-bn-vmEDSlfIDYxjxidEiNql5xTWVQrYVMUCujphO-EKVSucphatF4BSwcFaF7BT2sFaF7
BSws_iOyIUzsDlN_c2aDGRlSGJdRcd8sDULiQmhQrlsS_mC
}

