sprite $image229 [227x269/16z] {
t9Q5aMn130FNDBBVvX_lXsFICOqw0rMvgttwCcnrdAJ9-GTSTs3qN5AcET3MtD2fkB3c7ksoDthBahfMnpn5AKb8w9G91GUk9w6SaePvcP891QTZMmbxNWjS
A1HSIPbGS58e55n9cL1mO3AXu9HCA3YTCg7Wm8L2mGCY4mfEoKZ8wP091GU-WOHAIbhDrv0RV6iQIdhFLmAJ2GMdJ2KKd4wPK73QXKB10o8Z8QTaGi7fa96G
0nUwKQwaJ2WuANIZN4cPK73WCX9oocH2mKb12RzUISFyDc0oeU2Kp8roEcL2mO7BX8ApJ2OKd9AHaDFn1H9gA6ar11KbisSpycCtggVacbUnyqytvsFsf5u_
STkDdQ-UkEz8-EicDXaf4v0vFER_HbqbvuWLUPmtLZ9UdWWiNuU4admYK04D9Vb486F8njr_kkDw8cIKv1ClbDIe99y8L6nToR8N9cefoITYHMaeoIS2vKiZ
87mYKDuQFnsV2CJMIdQGYKfAmkd4-qeU4ahoYK06TWv8_UNcJ9GSrraet8bb0GV8lF_J_elTJId6qRKyTRCqjSu-Ny4dZfmb8mhuDohP8jhDTvGidwta5l46
eb-t9Lj4kTsK7JjAyaTdkWQHn0Ifav-k93GGevDEz8kKLBCD8kdDYOa5_1kKXDatugLG58HgBUf9oh86rmy33CJBPRvhcR2wctoqab1h4UTokTO6XY6YxigV
6rpLx0wn4arVKq0IL24mTzxTai07p6X6f7hz2YM_hOCPqGSg2RLTHAAvKL8N3ZZuyxPa06P4el8LIYxI0QLIgdfzPoLXraEa-ZybuyXHc72DDcObtnim8qQB
OakokfKv43z0IQXr42LG6YL5Y8MeLZ6aJFT-IghjbQw8h0eGPIMPYBWmkPkykP8mUunu5OMQCJLAbkPHG156984tLH9g7KGnNVFgtVz-dTQvCeZfEmdWRPLK
inwYkhkPRIPnpNHIgGhBWW5tfRTK4cPzH2o8oRKrqu7hJFIDeSuxMx905NXBm73Ht0sKQybq3AALKI6kycvR4ce742SeKwfO8C9h4b28bSBljIK3i8yOspvg
g-HF8xrWfgZNAmcpOuWqNwxpFY5pSyqITogLc8bvFxZYJMOq8nALXIC1YeXmc-c8XUP2xdYzaWcmWnZRFY6k_-DLoQY2MTrDNgiap0OHYMh3SNyr5bupNQ2a
vnxfBlbom8mOHqj2L2oGRPT5Kzf9IhvIGlU7Y9idECq-N9MCBgyKCEUNRCb_0ao8UTktnT2OrZcwZFNdJ5-m9M5zmWvYkYvcoENW3KOLayfFtfAm4SAC6DV5
phH-bG0NAp8J2JqAhi-VKVD-5ribwH5aT9dLd7XcDdsMaZWWuK54YcsVfrKe3buncOdPtC0T9PyfONTG3offk3zucTZS7G-L19woA1QsWuFQLz8Cn8sIH84e
t57o6HAE8-PCnr0pIPbELqJjt2MV8E7me8QIcsaLufpfi22QktQKV8A4GrsCYcqVnMscctxQAmkYA-MwVYrAFa724SI1J1UZ_8t8ieCu65p79UmFQka2zZET
j9TfB9DgYeHOpYi9wrPY2-03YEEPZiGSRAf2p1j4ekcCaj1H2NSHmxLKevcEI42c2X83Rn2fNeUL792mCwWpC8ThPvLikoocIk9kia4aciUKn2a9SnU_BgHI
qh2EPJfkBzEY875tO_v1d7iBvFoYE3YeonTcAayp_OMIm7sN5qHdA6yGgLuMHlnx4WPXY_Xr4KMTpYkfPkdj40kY6_WUaUPBzFwyXDQHC0XRn28YK9Jf06Di
-xQHPhRjCgiRmzrrWqZNMPV2wHaDk5q90p3gvyir09Nfc99fMaqvTrbqGRH0Z3Qg1kI96KrKMS9D7slpLok5aaEPZXzq6RQ3M2_eCXwGi3keMKPHD9375aYp
xVi7B_g8gZZpPAOpg7k4Th-DeH9A3cIwgAGaj8COa2Sb3CHMGa-CiS1ZMZafsUVe7xoS4VM-yBSIMYlXBY8do4DAjjk-VvbU4V48KJ4ieVd34TqTr6bAa6So
dIgdWxT5_7D382R8Kn86L4kusyLIIn5DIfOn9TdTEHsyBUAVFow1cAgBDo3XFkBEMscX0vak4B7JvGMnBeZ_A-D0727SH_GaOGTnvtFzK1tBTEfk-rrU4MrX
z574NX0DH3-061yY7bOojZrRHYGgLwBBWaZY_qEytIFMEH3FIsZUHuI6T5D1Kd8Qk6R9xcF_G2J2BH0Legew2mNYYKjXI7WKaUfKSMg1n1ESFYAnng1A5LMj
PPfH7o4cDj-JSAIB-qgYdijq34w8H1nTh3IByZJDSs7LavT27qNCd-iVksQrVnCKoXcHeeiq2rSXOjIgElXaPa_2Fg9IJH-F6iXq-UqGee2PTX2LcL6hGBMB
kE7eI6XTHBjSYD9NRPo_PgclOOKxYAf4LFzNYeB1GOrLU7nGCT_zBwZyNQRZvH_fT34WIsLcLHaRrBw4-uXiB9l_wlbCTocqkWBw9qG5CTF-qXYHCF_6X4Wi
tFbS__0rYznTcJg8KI89iJ-ePcwznBe5D8760EQLbZFTmKVdCoIbc__IThRhag8w65LG20Jl_tBFcH6htct5W167FpFT-tCzPbKI8DLglmZ4Lg2Q9CJYTSei
hYwye-HjH3O4AlxKb10hJjEKUGb-NXInXcgwGKJ18JlZZeI5tLGHqRzsngEC2MHUHn159XGIRXq9IqxHLKHaj7jAMhREnn6Lfh0hOU7lNF-tcOAIrnSmJv3B
pJRBFKRK9GHsGq8yaxKYGf_hQ8MIngtp0KGfOIDGPOnYunA8hOt3zN5D5qOHw_zQ9VmkBa3iR1mkxc42UOhOah1q9SJUSqMad6H6wr_0p9oWvEk8geI0qoK4
O4NCd77Begdaivfkck93HCJh0manrr_srgxGAQE5-qe6jxwEY7ND1aGzHXb_kTN_Jwt3O2nlK78S4JZNWTgAKHaFzIdcf0vj884aIqqd4TqjHBk4HG4i_6dj
Ak8nsTQgwTQ-adP4ynvnNq9yfBPsEFFyugwD118DIeuWwe7Qbn287F44wh1c_p0uT6kwSSHn2O7eFqKD41EK7AZfnX2VISZb4Z4Y9ebtH8oOX5PD9ziijxw6
U5j2xixrip-TXgR2CIOe6HUBadbruJyEr4wCweWu3QMq8-905FZcckxzGEqa2WrHzXb01BuIhPsjyvUJXar28CgYXXY8dJPhcGChIhuOg9jHGecOw3ScCwfM
Uqq79SSHHoG48d7EwRVFe0p4df9EKVBDG3Ka2ecOyHOYMam2trxJZJ_5Xp6AjJ6Zqr1Z4lZMccuSqHQZ-bGgjIwTti0FcfBZWMf957fFnWSXwMc2WD-lwT1c
-T6dQ9SGuz9efX2bEPCMavbJJybbbaf6jmmXsYMKuz8bvmWE35iY9iM7T2NzrTRvCyJ74cu2aPrRJyqKuvT1JABFwYZfhjei5vuzHLECWb0W-k1S-E50j2v_
4RSeyCLQPzbcaVSF45N0nBPnwTfC-TDjRgnbcbTyQ1kewPOnH0PWjenBeqPTwkEYV21Y-KzCfi-7W69B8AiTqIuX26KpvUklGCn2Bqpo3zLqLSdLW6YMK0tK
kZvAabxKu4FzDkiYWP3p8Ne3eYLHw8ZeDA0araXDvo-K3FCqhIP46QFsSMbsn9pJWQAMu28cALCtWKWbcOXDY0O9zQTOtwmGlnOWcp59fIGD7m-IH4rtlGOI
HU_YXkmqLdSl9WbxpC0NY9ZaR3CQ4eLjN5fs6aWWkf90t9B05uYHxa2-9I60HQUHVdwrlf9KW2YKJ3by4QDtegOJwr6Y05iVCGcKHhH-OZ83KTHqEKmh4AT9
r7GzH7uieIJamlaQnIkGooScqs4m8B_ub2SVWRYwARIZrHwZWEhEzRCJ43qbKTCb990pFkSSWRYxIYr8Qw80LJzG6sU3GLVI7KeYWMG2_a4FnEgghEcm7abO
xWNgie_L0CMa912HGA0a43ylLQAc0w91GY3U79UU0-Eutg0asYoykgBB58YLVjQKD4ZOkGe7mFDSV-EutdUK1AB01oBeVRw4L69qR5mQYDDk2UcLMqj9cK20
3qGivncCWDHZT7nSUgfhRHtNhtDNIUAI13uGbRb-CDwBqTvzL11U84vpvCPn_T9NCYLPqiv01FkKMKAMroJSjATObMmc4FKZarFnWOWrHsO1sPTmUpmk3SHQ
PiK19SNoLuWki62qI0YEAmcLGCLQ6MU3DvIaiv9snFvS__YuD12XP8AIdGa-D2WUMH9YAeZHDjVVluyA2Rk1YWHoKycoCSvUeIGnPxw9Y3RBa0dLSUb-e499
FO50oPztZL_dgYJLCzby4n5p_VPnQI5XBr2nGaD9x13ZpUtm2hf4AgKcSWCYysiIzX2Xv5xJ-T0P5-8l8fIaumVa8KGfeMbSklGGKTCjxLD_uWEHy15NVqIA
OuYGS6nSMaVirtHLoNghd9R0Mpu-aY3e6AB2fdPHTiJQPYqkD7VZAEt3625X2oYJMmKYMH45s-DnwQcrdAAaEFLV4juE7ZNTNyIKwQMdY26nRG0Ho-Dii5NJ
KSRRmMFd0uWuHty3KMiRxOXGSZqhcUIbXrIJsyw8cWw8E6BN4SV7fUs8gEdEIYRSRC1s5Fxn6sJ9-OouMH4bHrz20Dv5H9lb0n2hTZZFmFlwRIb5V0I8gPWG
LOvoPrpQYeWsQxcuhefefRmJXeL4fu4Zzi50DKXeGqHDTuXNTiHqlg9JAu5wc44ayoAnoKMpX6K44MsMh-BbYhZNC3ZrhvQkIugPSxv8_Sc2s9AmKR7AbMu2
egRRKOYPf987IEQSA_rGTIFZhzqsNXFcvJuWsgmT9P6c99VCBtGQkeJzSMciOE93JNTMajBVccu7BtP4-xWq_gGYqcpaGqrNbQIFafnGq_cZcSfn4D4YeHAZ
teu79QFpnmaZrRaLmX5ZXg9MnF5nQInU7_AXpPer9LtY9F9Y8ZEYtXJg0_rOyJ4T4WYKtA0aQhfVn6BkDEpZqbZ9ZG6YfZiIVaMi4EWppeXe9u4uFYuzd2Zw
DTtiZml75EbdDsuv8oAQ-uXOtQw_N2oRXFsQxYXF2VTmS9nZHxIFIziJXLr9VoW9H2ZfWCX6n8SIPek4zfeEY1VDrF-hEHDK2O4OYDgntVN-n_sB93Wk169D
0Sa9ffWktelR_Y7nBrwxUGP5RGXJ5I2x2HnQhcaqukd95Ha9hqllqvU6CkMpaXfnMkRf554d4Z5Umi0P1PpE5aFTD9o8q445R0sgfDqhjqt3YOWSL1WKkDDD
-XlGY94I3e4IeavNEbkcvf5oK0EsHgpaUcmQSj9mFE9A0KNSwUhn28wSD1m-gF1QZuy-3d7SAvUpXeSYEYN4RGrtEhlL8VBfgEi87DG0AEWZkzD9Vu-uZS11
1TPwcjErlKKyQtZyNwI10b-pgaOyQtWy8W0AtkZZ4AN8wOB_guFA1GM-PWbcDpWe-4utWdR31mM-PYqJ49402ehJpUFBY0HGKDSiA28E2dubrUcWY3We-6iM
41471R-IwdH0H08e66jMsmSYia31TxfXA6x43A3m7uSehJHUH3ue-01fIrr24OSy0QsIpvCB5BxJXIBEjKauCZeHVL2agkHzKeB2Txhh16uKvW78UG1Ror99
u4PX5e00eCXIIS3MibJIkL6OVCG00gprMIe9b32Bqm6Wo08GmDQoE1tJrdu1
}

sprite $image229 [114x135/16z] {
lPlhrg903aLLAlSKt_k_xGnMHDCIbHdn_EhxXcnEIbohJti2F9r-cObLb2u_urr8HKHKyFmJtXbb0Gvc-m6m1I-OFFr0O8eUg_E2ce0nMZXC9uZALfJRCG9P
fSeHexrGpOkc7DM8cWb7DQ9cydHK8mxK6G8py62TvweHDRCTq8ZZT5veFoyMtr6DY7nfyHK23z1PDE8udNKZzkl4ynS47gApVOaNvzZ10lSllZFgLu6n-8vg
HCs4_GCzg2bQ08_JgMg9URnE0JOx05OlFa44IRTvj4u19i03cEKv9a1427IiJZXdui8yM2UtH0ocsD5DoKGwN6SqHJ1uFz6v4aM9VgDpkX7_X7-cStWKcUL7
EaqGaOd85TduS9tgNR1T6l42OdCzJcVmkWisW0aMZggwqGW0ctwRPxsxNubCRS85QMfyc4xpXJU8H8HJGo8nmzpExmvq9Lwh0LCZ8Y52CbcPPjyRQ4I1n9mN
G5jqCXER6oUTtnfe4BttGMHi4pAJc9fpqlabNX35ZIABpa3ATtI6m4J4w4Ra-ZDMpmlUz0i28mgCKqEc4LQ-wXGY5EUYdRi7cednd8wegKOxISojQkV-WMPY
37DWJ0MdDkYs8X5GxV_YzPw8VBinOZLLWUjeJVL_rQd_3hHdufBG6KnUhe1DOn_KEck16RT139qnMjTe9_aib7Nk7sX5ZBMpH4rMdREmyGwTQXkyWXXh9-vJ
bOTEvjafml3k6ueDWJKnTDBGQJUTnDxbTfjuJZgBWMPS9Y8cu5DJQ9mfuY8wY4G0OZi4PkA528Bvh9Drj1EkJ9sD1v6maMdHY8At4aydKWJAOPocjIbkSGNI
NLtWF2wAtRGMM0Dz8b7bTRHRJU7R0yLYimKHcosUFn4OlDMZYYnCg7H6HbFORqHgjaIt6z4tW2lHR30tTUBJ5N0c1lEjmFIinaTJbIsTBLvBxbS0PvJEX62t
w0S3JKICpLNhb5dNAo0ua_pz6O6jUS_BH28W3MRH5DTruxIb7Jh_yPWggvizyhm0Pc9yJ0mcHVBYYs0R7cqX2XiraZS2dubyUzFGLMUn-CJaHYG2Cq5c8go1
cpj7GIPyE8ZgfeXRjqGqPMHbMpNMl7oF77VoHYVDtJWJpOJO4h441h5tRG-Iu6LJa8aoSOa-F3blUTwrwLXd4O3RQ6MpAHj4soAwR_CwdqwAUPq1wYkTxHEY
zsAWfe9dnRJEtkdS8cQFjK0V_weYhtkwq9aJH2o8fK3NE66KLTD9aNKoOa5i6yHQeDlZ2TDv32phB4RBh-wn59XEcDc5Y4o9qZfBYmy_8zO27uzi6ulKP_rN
9sIT-ubve0_l7UFjhIiRrpe1znE3fwl0TSijqoHcdZiJ9vsOTGQHIs8rqFmzmFhT2iSZX5FMcKVBxGMnRCG3q9LKeXmi0OAiayTj1lC3eZyr8iNYrb8vQfql
freq8gVFhaJ4QPfCUV6rkqvyTOzRZNXwHxOnIhE7QRBBSBlgXBQs4ovK4gj6v7Vard0XpW-xZkU-iAfp3A0YkXUDo9zN2HekVIHQTUhMuckvAGKnDQ9yHyO6
oFpmaaEy6amwrz4YjBP1p2kjUaT6bSNJrjS1zApp_ebFDeYLm4Xk1pHyVdzqvwIJOH8DIVPCZ4Pe7kWzwwzepEpEvAKSyJN7_G8O2IT2M9W9sYk10Sn4Kxbx
QhHcw7HPVyB4ZN1YF4ytdObO37I3YAl13PsZgpUTmZ0nNgYjEeDuvrd9MuaJooEpRUZqMU82WiZOcZumjnjH0FrqQiAmOhBECKqTDXUtk13Z4N8DvkOPKRyZ
d_uRL7faJeqIauHlFxa4aHYNFWQo49Y0cNYwi61vSbmUBg3TY4HDxSOi6f5ly4uScKG0dhy1O5b-Se7e364cBlb4OC_422ITiMgawzeKDUCDegaM0qr9nCYP
b78vhgV8RRJBlygGYH5_AR0WLZhLY51a0NHbmatYEu4rSJGbwrpagHiJumLYgi85iG0Mn0YiJP65SXsjgRbSTROhKRjyGlJtznWwOxJQ9NIAgTdGEUvnzW-8
NksSIDO9GAIp4OzTnze5YOd3erf1h77t4ss368kFJRbRb4EOr6pdaxDrDXgSjeDA3Pdxp3ns7NNlpfyGwtbwTpgVgbokEiLPVUZKsJviXvS3bKj1IujFPrzq
8W24HrREnFKUNWlKTdeN46x0RkGQEWUnTow99T3nz47EgDYGuqmccAOhqMRP9jO2EsyAB9hIeffCD4KxYdki1pfLW4sT3C1C9AR5ireGFJLYJ-3Qb4K5mmvY
rOWwUV4rMzfn9JA_9thPYCzr8X45qRKYretOdoRKWACTixmaUj68ElNYQnFZHD9V4byqOhzEc0Wd8kQQU1SuVUa_HC25wsVrphDs-awQwWGbyK7W-VIrN1TV
IGo1bw-WykBZWhXZfUrSV6soJMAijAy7X3aHqqex96SoJyHYfNrNPo8MZVYsJWzYMcc71jI368quFcTST1QDE4vdDE9tQRhlZFWF
}

