sprite $image376 [294x244/16z] {
xDY7SgOm30HWq_5A_7d_fxq2oZ14OzZqe7YdtgL_etLxkazgfcfGJDvJ6ASQv6EgI66GEAOwIBnJDV9EDNEs59rg7iZdcPvgydLGZRXK92fptTceL2CgU5GZ
AlM4H0Lra4h1DLCr4hceNKM2w2A_hdRvTO4kYrFA-LVCaO0tMfLyvlXT4m6uikrABk5tVn5p8eoAIXd15oHPW_EowL9MilIX5ssnW1WafnItTl1AQu2YaLCA
xlJ8BoDxKDZPQAMCg2Sa4UVaZ5WbG8AUjEKOkBAHIlO5GU_-yYA0CwAKx0k2NaV41OVTdrKor9ZNMeZum0Q9LjfH0-nih5BHIENgk12dRBmIRtHx9G4-GaaL
nSU224eYhsNILmrI5AMpSG889S8eWD8hdPGhcpEwkn9VEw-aG6dtZwJqQYSbonPHYQ-TKaRHbD1dmiafbHOam1c5K4ffV4tjz7oGL9UWIfr0BDUrKw9iFgg6
T6UbgPsfvScKzBL6WWpSNocbYQoTcX5RDaE5thjnxQOqoWp6gLYsfH2LrUZkDvIntvIwXfWdlALieX7EIwQK4eZJqvkCGYYXCoMCcNFY5wG0ht20eKppfjGq
pEc97oJL2Azm-_N3b58B8PpuiWLG4knEw4rfxjZQGPUJiWLxXOEXP23zLpevFV56YFOAjr_Jq6vAW-p_zUQoXL8wrcxePLNg2vSMtYYIadSofPIoE2T-zu-d
v6jdIfEh7RdxHrF20EU4QLoLqBfB2rUsU4gfcNpjn9HIuoujA1gf6KLzXHFlb3jJoeSdNtBtzu8Qu1Mkotvvch4fxSCcVDdyHnynNk6yaocbNY1Rtcm4qLih
DVOA9ndYJq-cD7JpYP8IHdU_eGpFht3jxCSfowQKqlh10iFb-Ka3t50Eht2kTar1YIwRQenJPMvD2HEyqpWKbCW5wIztPxRaggu4KKP9bNJS-_zVUuQ6RDFE
ihLrm0f1lUwnLoXBnRA4Bs_X5bQ8j73kz4HACY4Lp4-NXKHh8XPEsjD8IeLXkuc5svEWXPjCEKKZfQAmtO7IKx0IBPp4ZlKxR7b6jw0a9D3JmksxE8JI5r1W
JwvEIVVzQTpyalVGifJi_ZUZH19YuVHN2nhIpIX9xAmdfOIdNztsz_pkVpDA2DxZ6otSa7vJrFrT6zBTBHo3jRTmJw4i2DjjBTm-TWCjt4xv5Z2ImWqi7BGz
HNksS43fxizQOF-_ZOLZiB8MJXTIJlQQuIuMJX_VQE4csr4gDGF6keU5qzWbMhZUIAdSdZmgtSN2aLFEmgcC_AERSpUnS3gCppiBLwfp2UdAd41Ce8KR1gUD
GoWLXEq6c0okXTFsr7kKilQ4TMrEsn4liN1GJa6wTrRdlYbSqCAHKnGBnzYnoiDsW_Ka97mB9vGA6DrWFJcFRtiBfr9NFimj29lMbIWnTiyMhdTaPTdkdwyh
KI89jN3FltemR5gNeQISrCBnLqL6AgFIIjSuCMXYb_Gi7DlJWTt_TVtl4guoUEqfYOK332Sl9DPLxkqg9pmi76Dt6YEjQxZA9B7pBDpvZ5Yuagia9xLmU7jY
47QyBk8glVPaOk7ENqWiNEFURdAd9x5mfpDY8Ltbtgx63fDOEDdzRys98EnnRzULkYyf2QCxjYU09EBJYK6PdaX9mtPxJj_94bVfneuMJXZT6fDQE9Dxk-Jq
A2Tiz-Uq9OiaajpR9KJMfnSI2zPUzuO1Sc_NvLI5KLllZjcRN2EcUNo-jwiMxgDXiwPkhIJRKUAAyKuCSh6HKWr6hL0osoYHnQCzcTxR9SGQOMldJ1YCbD3F
aDY57rVvrCO_pAYfMokmhQ1duNnNoTXLODG8fMJsJCaUiJEzjui7fuzMI--EWIcbs4sGEJ8wztRnsORK2YLRIoXrGM8dhlA3d9gwjG8JIaleDqfprDXDT9Mx
XvQFCc9zjRAGE2zPf5yQiPyAr5No5pyHjbOemQGW5axR4_QkydnEF6xO1gK4ipUO-fKInh1hJtfYa8LpmzO8fINxLchGButEOwvG4av76BL2wVL_Sa-25WxU
Gyj62Rk7bdCQKYkKOAyfxLTC6ZSBrytQdiAA3jsOiktf-Dj0grEoDuNTYjaWq2_fzCJVC4hipcQq04ixa0pYRMTI2adR4oc5WCESo4XhFKFM32FFmYqMw9Sc
ZHqf7PsUtj-ChcpXO7bAkc9y2_URKXUN7U5JmxRzOYECI2affz2lb315uMJZj58Qn1MSngWUfSaiNzWsBPctZNx9cPviezJrXMqy_rwvNH9RQ4Xv2nTeuPpf
AVNVbBe5CXKSMKYrBHoiZ58AaDYbOQLaZlArAQsKUd45XyF67jx0GXA_D3Yn-_5BizFZLqeoFHtP_Py_E6w0aLeuP-EVQU6YnYxs7HUYS2hU_VcBjMxwcfLH
McpSA8qJT7gQw9ScWOX0n8DCJ_alkT2699I4KyM6fFEIqI_rq6Jjtvud47dSKAQdyeOabBQgzeMd-QaozRHmcgnbxXqB1xRuZT8ul-64pExlPf25Mc7BOx9f
fOHXD6bFbjJ24IBIHgaReB7BDoHPI4B93DN3bhTmWnUxyA0a4DDAQLk8mgaqR4h9K7qXgOLxMDsDaWMDNUnNIXYIyz2oKe8-j1IyNS-dnAh7I0k_U_7CKrxE
zCI4lPYUk11tYoqZ8_7-5wKgCr8B9pTICnREu4nF6oMB3uW5k_zp4aqBjHfItiAbOLZDoJpZjONhrHLWNYd5xgV_bpSa_YA-N4nJdTrVAMco4lrIBojcvvUI
4xkDKXUotncU5GCR9QbgOSjREFknSAOGHrguO1gxOQCq1oWbV_VtLnafIQ4s8r9IJZQkb31C9kqfXiqlzREiH4IEyGD8IJ3a6GcbGpSpxInAqfxmz5uucPvM
l-Jq-BHIwcob91Yo7mja3vEZKaDIIhgXnPuMBagoCD72ZUOyj7YKs7Foxt1KIbgLrf5IqbuyyKQgzz1Yz4lpeX1zIbyeid1sd1FiP4gxXp3dHggts4PQE40W
XfwKoXgIK3gMEpkRqZHvTq_Yi54AgdmHUdvPRnI8DcsK2dR_qXjbLIbnPVGp784KwPS69tOR9V_Q2YanR5an89IEBwTqEgMEfqnBBDn8Ib5YHqe5OHDAnpcT
JwdR-hGyj92I0p5Ecr_Q8PRl32yL0qhfmFI44p4DtLgpEpsHaiVfcv9S-YMbpEulloYKyikf8YTI6bwH82KJY9WsIfYVfgUltEwllwYKybKZTe1IKaushPIy
QojBShwi5y1Iq92EK0AgS19A4hkzEPdUMhXVci7-ewaKI4rC1H1AFYT-O9vqtfxxbLBQdIXyj_ldB5nfLPaAF4glBPnt0in-_5BCMxZiAYl7X1fTV5PAoecK
DX8oFT729HopSEnBHOKQdD8abBpOXNwZD4Q56FXXUXz9wGM6J18_zbOmErnnK4hUGmlzqkZfW2X-INR_0nRkU7lgx725NYZvqnCj71pbkwDKQYhLmhNPde97
I3_375PA609K-KQXH0ob5gxPs1aMBLqnM2dvqrC52zV2z2JbNt_cfL-5E1LRE1CBTw1GWnEUEKNluxSqqY_D6Zi3AGc6xBQdbCeBzPSJBnB8C9wpS2KV2mYb
At5YklhWSPhxZT8i3osaLD2GXDAngXsxTU3qLem5-gMfleKxZWbdSfewginY2wSOTDkhGAb2x4YfwryyjAoKC4R7mXM8WVCJLusJKjA75j0lJKyMplAx_ycK
TBYir9wKaiPkeeN3Vdf21GkNNqULsfDIKavnM2d5nsQ8jnZU4pmEgJudeIJjgU2KLtRR-yX4MSEfz4B9UsYPIIaaKgeVDX1IQSMpL6QVSIesqozDU44fk-sT
k93gBwSq2YKlTbaB1siiREUhJAMad4B6mbLkslNRU1Z-nAd0X5ATtHyLhppbfwUyyfqTIb-DXAtYkOAyyYMb5dV_TfJl8XRkWumidlsUWLgnsrDQFhlxMwLR
gySvGJcHKjt7aPRR4oY_7GjNiscttPxGTRsShVngVFUl_aaBlfrlUh9mkTs_NKQiT2edTDyrsIyBXwgxV_kn0zrAbBDm5slQEepZjEM4JWxvBgZuxDz-Un9A
UGjtjQy20OvpsbCAGgbos1gUdZAKpfMH_7JaSfnWlKUfxkD8-vWiJGwbUuJjx_RjmmY140YZi5bS6Vx-kxK0mp9pgy3wNWdVHLAiqz5H2Z1g6fp5BBMyLmfQ
7KdWTDw_K9foE39sgQMyK1hoGbfchg366YLrgiE68olD5TJGiN_Mswc663L9cPrgr6HaQgVjHaMJ5y2q6KdpPxV1QOr0wghPn4OyTarUE6d5CEhBfaA2gScB
nwx82oTJXcoq4VUJCZNiXOIJALzN7hQkVlkmuMGcBvnCwJECUhg3r1L6tptx8pVUJYOtdEI6a_wsI2EOJ6uuYTfc8zxYLaJUsPygD-udkU4aDvYAt73IsuY_
oFuvbQQXFG
}

