sprite $image388 [73x87/16z] {
fPZhWgim28JLt67Ozt_SSxAkZLEQPY_ygvTF68R4klq-3aalZ-_fVyImVnEp5vY-EX6RV4QhEMphI6e6o-vug2BjZ4ux5fWWPW0C-tEQ3qmdwKSEyPquHJkb
frIO8r3LdiadnWnDf8MPE5cXsZdsd5A2zZXXC4WJXGq1A990zGIvb9gEW6bhYdwDbPVYN1Vwb0wzWo1oOk2RSjH--0RYnYLmHehh8d3tiduUv9HqdAyCeiUn
EES9S4hnqGLL0k7sE1dYDAWIo5qJbSBmGigZ3OqffHxXgXmlG8gRI7l1kDkdLAZv3ZIUbkHPOpYvII82wGNgui3kTmyeoHsKWnL8nMdS3tDjrRj85PottWfL
Iicr9Cz1C2GPQSpbJiEERCW1sYjUtWrVcoY3S0Vf5WTe8lTPcsyQWUfrdbBojSK--XHWKBnijgYj-06vfOQFrZMSriRpbaWUv31oizhRMWZaixj4oj3R8Nqq
4IPXsmP8pNcIHIgaITlRLmAQQ1HN8kMjFXAwH1C5jEoy3hEvlG7Qc7qyLiIGyq7BfmDvaNI0BZzm5516c40DXz3ly0nA7kH7hqUyWyo3g7H3dQjD4k5me31A
XzKqTL9PWOQpk-tceCQWtOEESJviUGgI9UZhvdDWoXIaQz0kdIDXRlCUM8EsY6jWTfs2p8Dyr6jW8fdgfo3skGVfpq6xwXma2n-v_daGda7cGDvHD6i4QejP
8nkG3i8va3Cilk4qPOaoWog1qfGJX3SjQu7oKpAzvJc8Tr7OaNYrpmGg2m-DXCeuSDwP2DI-f_NdXQ9tK8xAQ_Wy4WP7zkrGxdSWq5jhjqS6zNGdpSH1FVH6
ydgRnXDBMZzAXytQngikK0QLDaIX7LFUpmYq7XUKD0hZ26mzRLc2jzNr_0B_6h-EvYhR4e5SIcjtNisEmw0BJvAbsERytdAHzXKdghg4U6SuIReW9LK6vQ4R
aJxo4Tv-ok25m6G8HsDYa8OsrJmJ1xVs92YHj6cdnLb6mfongWQgM4Kw1ZQTbaWjipGUGI1HiwyIqzgCV54ZxKRtx5YjkYG0sLG17IHvxsjOtT_uL0V95KTY
G89R7RWsLInIIb18yiUveNeZpOmfcgcgYKZhHIM4zJ0R_m_xKHnA8Fwp-gF8c7_I-5bKED340AjeK0RfOdjQl_rWyNgo9CbBKFdDjs0gRP7HYlHx4Ei4LrhQ
VadYppwpOLj7WJMvGC27RB-D5FSB15libOi8Zz8aRd-AqCw4ylRdY4sr_hIgVm
}

