sprite $image256 [324x221/16z] {
xDe7RWCn30LH5Dkhpm3I_K-Rtdl2IVMy8mp8hLg_miYvtVeyvThw9ELEhK_Go0DZDJY4ZOMsOA-Y1LiLbG0HBTYeg4hIggYyIwq62m9FYnO45jg4m2XQ49X5
2pwDg4hIggZqBALjkiOjLXoXkCQ0ik0dMF4aF8UGO450-Jm3c0uXm8842mBArnB0T0W15WIK1G5bGe05eOeMTA5dVjxE8GHOa612mB0Wm884FxCIV9u13DSO
C2q8y3ChmI44b0K1__FqXnNp1raGO462hoK4Xn2m--i5VVtRvPzm205bGO9V5m0-pn1SOq2P4E25aF3xPz2AMux2vcTMm72D0HOaU3S638SGO462QmmeOWQh
SjmciCLrz1M12-5P-tQ2CpiAn01ujDDsXTp_jBEWKV-otijYq8iYA1_X4sKgwJIGYhtveKj4z15MDBe1nTmMqPAAt_GR0hsrcEzpY6-o5h_fEeOvq9hQHPYA
6jkmVw1JyGEauk2tOe0c1rhJPvYAcYx376WDNKDVCH-YomSIVw1pe4iPLKp5Kkuf9Y9E35jWA-Qsg8P30vq3ZJAgc8fRfQEOY7_zQaXk6qePgCKyYW1Ojuye
UWETYaqdQdoSMXJ4_B603OUHjUYbw45iuLQHYax4yAlOMOkfY9_GgyL4n6yG4JLoe9rKDNGkbnpeRyHGBXUh5bCHchPpPoqw4SEnMio3gCbQl1s4VBOqL8kB
2Z92xcR9ZHSwET2CY93dvhnSl21Qv8jYvtB9MWH33EKe3ktSQusn6XxNOirQF1nZDMpXmUMIjQW1GmmraCWBdQn55LJ3QyMiHIr2DRo9oAqoQr4EeHZULTom
RYsgeCRvAf5rMxmM6N5jg8hZE_Uq-umQcehBrY8Ohg4YPYqoD6heAwwtvo3Ymj1LtA8ifGZ6bQ6F65jn505CAAY6FY8RuXAN2oDw33Nbw2IkCD28w3NK723E
hmY6O-WZXY3EM8kC63FK725EN8k8S0rznM0fqmuq6BRXTGX0iw5CfgY2lg5_5DdUuqnOYmWdknKUh8bsBKvm2CNGoYYYA4uX6B7RERcSPtYVmx2p3oFIG7oz
8YB63VrQt60WlhiMmNZCS2zwEVk8hrHaz6Nl3ELUCH1VEz28UDHG5Hd5k9tVgGZ6quQA63QY3lJh1Nr3_uOE6eZlKsGCPHzA_IB2G7pPGEDvGGtGGcF3UPSY
62EXQFHc6F6hkDGOQyxMHC1IN6gCDJGGNpJGu5i8Mux76QRYKcEiOKEaKOd6GBzmZEl-1r8ROdGYgkBhntWpO6p5gEX4r5fSgGWr_FuHGmBuYaiLeKQ-bHN4
rmmqufM4giYex4HKnPN6M0FAjx9IYMujhZJ66aWj2gAh-AennYvvk1PzH55SPOmra5eKH5jngZ7szvmAHUoinPaUItp5kdq4iLDnWfU4GmykCO8eYlCKeN-v
K10VLtobeB_dG10V7MYyJz0Ff1OneZXd4VhRuWSZ0xtI66ies-BGG6EgVSQlnVf0BSvm6_krw0_qyu9BrYBd6cEjnUs1MdpW4CwnBJubk6GjpYxero9DHImW
wDPY18s1dcIC_NUBfg4gBZV6VYqoWXUrkD8OQt1HYsB8u8NY0rz_l36uKuiDXepWnK3FECR-G_IHuV-Efufh2Me8nBSMFmU6JGWy76YGN8zGZ-9fBP80cg7U
BphkN4pGhyLc62H-XzWSk9gWloqsEpOfGCCXmtsQ500yhqK6qQ10KdXREEi-us-BPuf188AC219w38Ch7aB_8PeH_6AHmuPr0ZHZMrIl8CZWeE4-PoekjqMI
4MXsQfY2zxP5VGcXXZd6nhRuHLJ357IsHKKCst1V8RoknI3rcc4AkjiY6Mh85FHhaKU6IQYAzQmMrJ05xMtHDzpN37LRD0oDjmjPYt7FS9TaBVg6--h1MIto
XY7tJAj5sHOjm_GxhCLhGnNCW5ABTmsnkfkcK6hnZc6YtNgt66AOXFPFBcBOAPZR8iMmIp2tnG_5i8Sm7wB5q1NCRL4DlLzBCl6jnLyCcJfsBL8DKyOVw133
L35J2TbjUWWpHGpJeoy_XYKnklEEbV0V
}

