sprite $image30 [244x168/16z] {
vPa74c8v30Nbh63kVzoDamYlTlnt62EvRz05NKy6UYTfZ4HdqUGl6Xr4PVa7hdG8cUKRdEa0KfSxUZeWv7lYPrrONi0bSCX302EV4V81MLVv3shSVS9m2Vsr
Zfzr4q3Oh0lB2ZNoFk6iuuQC6IdkFc5Qn90ndb-PQSZ_WdESVGgxMvNbLz3YxXE6IznzmemSEMISTTnzmbHF8SVFEZK1XCsw2Y1irfdbtLJd--G_woQ_YP7Y
xXEcnTqd35UV8Rj-PLRPGaznGyOq9p-4-D-j9fiPEVBN6cSTTvymDV8-uQmZxnFEEcx8c9RYXeof3lR9JzQLPHtNhypCyjcqkFk4uRerPF-xLLYyq5FSVSAq
3I7xtwqg3XbvmpuvphggYbSgNKBcd0QiesPjDe5rtApDlbYBLrfQT_vYRUTaRL-aVMUTrvpdZ60zqfBpxOkqzwmNdMDymUiLvxYxXPtzM_UqudnlhI6pnius
ev-ZThjpZfarTewVDNQETuvYv_1PO-VuMMFdUAzCx1m_Q-mSxPM9dKFk5dOEc_MQSwHN9dQEkrlOENxMs1dlbl-i_n41H3r7cqrW7JZhD2vOY_Uiim3hqETe
rNbWrlsWh8teiAnjJlf64R1RaRBMERyudvArshntZf-rpN-XUnA7pLhdVE6CivOcNZvgR0oSqJawIbLpRAqsWJFUBIr576TjymvwINxCMheQDtMvMpeV841v
tgrUciEFMcq2vv_9MafHysPzPmoTSTOyr4PJHzOw9t26vEVTQgKvE4UnCNR6vwYKukGmKvjhplWSPVPnZjg44CJrArFdlEBi-9MfDgyv-trb0kC5Pr-lJ6oy
xapPmIiJXeoT_MUDGrvtTlAd1pJ6pc_QBTtwjSRExypQT8inXfOfMtSBXxpix3nhOBpWxEqSrRc2PBf6_fpTKfiBM2M0etFKvWgT08xEKPqhS2A0ZwpNZRKG
nCKvkXvo8u2JhDT37WJOdFN-VVhaLwRQXf3lAV9xF-eD8UyyHzT3JWJOirlg8EGDhymDX-Q6tTfmQ6x8UiEXkJthppaqDxmoDnoQExFUiK_xpr4V-uH9VC5w
vpxjUsNksAVzMU_Of_rP-zYdw-UeDf2rWtsw-gU753C57_MRVWZPVevAKQlymjh1FbqzHxcCNhYF5rdRKiYL5jYRDLVJ8gPD7gnlRa9UtoqnAp96gtR7xNRz
qFIGTHMJCdff0fpNGlQHjNGThLOTtRumWVCR3irjhynHQcjckkpSwVEf2bPB-KlHAywSo0NT0AClEciXBoG6qj9umTaQUQ88i5xeUIHoHbE3O6UyJzwoNdUs
IZx9VDMvar-ANd7cHAvfoyvQo3jfB3bRemXa-NddGL6eYfpnFlcdGMVyGqYKhB6pTOf75koCzyb_riXPCeMbltIsIf59_EpSAJf5xfqvqm4q_UwiXSuWzI_E
rkWSCjkypPxeA8g-UP7_1
}

sprite $image30 [122x84/16z] {
nPW93gGm30G9vFB1_x-xcgFt0gEr4cVx0wLngJjeDbTopzl_oDwOkEtBkQao4n5JJMl1XPW-OIeBkKTd-XNknqB1VsIHxbG9O6IDxWpkXPqN2aRYTQTgSg4x
k4ascafQS6XBTtIJudNRJRBPDOKsALut1FlOFKSA3crOAkG0JnpKV3cqKtV0eSCQPZSfNhSXE5etcZI9dUC5sxf7cXIlEq_dOb073Xsfkue13jUjgg5iks4Y
eYfnQ7jGLL_is9FdU_8f4ivkkqsMCDqOL9CShzian-i-RB9ej6w3l5YtgY1WSwJkR91NwbPb4DVfXkSBEhvXBzsP5RZbkgkeiCXYtUsbEtK5Us73P7lb8DMr
kaKL7zkY8ijEpgeAyfQgucVN7ijcqGyPsQ6xDQP0tIykoCZ1NpPbZjBDgXSoT3EB49UGauDx9M-fuUHTUEx98VXAXkwmXe5ha36eF7jG6KIR3DrJsysY1jdG
FMjGmJN80Rfjhfu6UEBxoRVSaopkhFUJvHRC-O4xvVsyvqfvn0w-d_QXjQLdwDZxQH-QZd__WqvDtNwkvCsHtQdR5gnrS-PWYyqUmNrtCFs3QZVfSF1SWphU
f8517MiIudq_RQwUv1VyFAXA_PTknrIEwrQghRD0zvmcFGygo4ojDyB9xviq9DX-FvMevVfcw-beqf1k2ARQ1UI19da65Mpj1BAZIKEw1U4h-KIJ8b9-wGRv
qgIWf2fwIpx5Q5A0Rf0DmR6wGSP7HtoAACZuw5YLrDviQohZTR_0VL-9nQ2UcChLgTwf_04
}

