sprite $image207 [277x256/16z] {
xDp70S903031Bzn9gFzgISxsdpXRmXImzLMfCvWwBxLwf3vmh5JKjYPHfTus99bLwejAwva32fI9fKTEA506bZQG32XGXZBtA5022XGeKA10WG852XGeKA10
4PH7KA10WG852XGeKA10WG852XGeKA10WG852XGeKA10WG852XGeKA10WG852XGeKA3eT4HHVojAswz9e5nkxDW7ZXin34RXz1c-d_U_RXfdJHSn60jR925l
UnNuWQxOd_YFac4lZMRoOIZOTVEYlEQosqto-L2-OVVnYck2vwcpeEoMlPABu8PaEXIpElgFFLI8aqT6yLpaWkHrMAI39SuT6SLjstOLbvow_cC9af5HjFs8
YZLvHPOyT70K3vDaiITQ5MN_STLMaDGjYSAFc-pfM11bkraKwudLKBWcsQqhM0p5pf58Wj84M0fbFqDYVwTmKP40jX9AajGf1cYuGBROnIT9QfHaeM4IJOwI
AbkIrCcFEGIwh0kFhO7YsAa8bsCWOKQp5L30JiTb60U9ejbHm9uAF4p-VFIAPLuKdYV9TOcXIfLvKS3wGZ6Ee6AP4yNwWxWGkLHVXfWF1UkFACSgL3fGPYQ9
NWPp95fzcmZ5NeCaMOIyMfPPK7WTahmCkTUtG_iKA9IpTfZaPQXKONmKwdkfxYuuJv9TndDQ3OxopqTwKGr3dVAlQJGoIZsg6IXfN1GaLJbXIqN3ebYpuu8Z
7JBkRHUodelGc2XMcUHwUC2qN3YH_8JAI2ZMZXXNkeQ9XRbc8UjMsKT3AKJyTtcvaT-uADVbV5wZC1PA_OphxUN6I9VyyZcMN-tTXsuxEQy5SBGhYKNY-x_j
XKSP-u3X9rYEykUsWsPitnzODF84aNSMSpuAhyuSStn0fs21xBBWgJ_C2YLVXENPDmGoteM9Fs5PNL7cemoAmzhzmX7d0XGBbjt80YMzSTn1RIuST8bP-CTP
eEHk77TGmqMikc0vKYmBbBJ6WVE8klhm4gvnJXLB7Wej6mSMZZ-HmC3HoNAyM6AKh2g1RtYmSPpBDnReeGF5aeFIA0w30ZiOzerp3nTXQ9nJnHAYvDmpYgZY
pG2ZYqh04ZKEM7sS4Q4a7DM-EeTnuOGds60FXyN2FycVHE7LCyvay0jdVLABf-o15lgEaj0ueek5isJnA_dr1-MlZxAyQ2Po9xN89M3nnNAkXVu42gyt3YwS
7X_bmshnUtYZXR9HnkfjBDytk8ZnfBOum7gB3f_-eYZCj8g_eryiOc09YoLg8VaheYn4v14tKC35iSpFRiruYsE3HVNtK5O5ucxelrsPC8SdjVW06u-JJrL4
-w-Xq2ei8kfXO6f0kIZE4DSuOGjvbMsIle5oZEIrXc7TABi3BBBu0omAn8s3FfialuN2wywProKoPTmLFSuJLo5zVIRnd_PLdWhdKPXMOLp3iq_yGOr25Xmd
yVPrRRMzX5u6fr7UUuK4rx3h6tO7sDKUzktYVNPKWE0xYjhd6KplnQzXluUXkpVsCFfig039UHIcpV3YmIyShT4G2Gf3jrM094Jf9qdsNHoBBnRNGkjnWdz8
tYYJqoXCdmVxnh4izZ1GUH_i9L1Pafn7eHycxXjPZrRb1O6A_qEwVl5hYRAlqkX4MA4gt3XnGsHxdCoJ-w9CJgCm7Of_7bxldcYmh5HaKIQdKPZEnJtuhNQF
7onh5Nrp3rCZHHIHJr3eO7XcUI_DKRl09xzwNEEiouHhAQMo0WgYvP7iZnC_RfsARnptWoyGAZDLVe12vqsG9TuzyM5-eS8OFy0mN9vf6g6aahmpJe1WeUBE
9dxPTOpMyaebsKTflqko62V-qrf5GSGdQ1x8K-LT5FfrahtJ2NILKq4I7tQ5yYCK-YCcyJXn14iLNoK-qZ5IGXJidzCaBDiaK27lZ1Elek99rjt36oXdHeaC
wxnDuYoM3piRZGE5SWA5FWjtC-kyJnBUsx-X8akI6UudKFXJ4hM7oLwPn2sqLha_w984cmUZTH-5wTCyJ9J74E8-P9SaFBEXZrU1q2BQVQHkej1FmihNM1dN
3IvlagokOhsAtpXh4n_bke72T20ohehHeKoycyMGHPLuuwnx1wFqBWeToPorVFMGydRY8RlVEBvEVAIzWy9q9DFYcYeiOmZlHkAJx7xZu39Uz520ehS9Tl_F
MUGQBJhCzbNyiNNTEFics4CnYis0o0aP6PrPp6mVPNsIXT2-YOykK83a50nt6yEiitpqFfgxXuok6WcoDqzmSlmVeg09Cyih1s2ciGwpknAxVAoYBnKS9cTC
BXRwNYX3Wlp81Hl1vh-WZrqMNLqrldLaUeDa9kYUbmDnxy8n36-P8ChWAztqOnNVE6TDFChp3wbgAuND1jVQY4EO3H9KaNjwybu4LLIEcfXXqCIktE-ZjLBQ
V9uhfJ9_viBV8b0Y7wj0eT014pKNlb7qnQHzeXIsHxGsOI8c3bpsRzPa3FsH2eHEc1W6500BKKhjruPkCjzHguqsN1Plgl89bVCc69qa7gLrheN6H9aiZvwY
zrZuDw9uOACJ9hQEHxdcB9N2umj5UB94BZ79-KY22QBCEQkjr3fHxXvwj5NZ5Gl_VkYCoIxAFMUb5X81bbQlSKFylrYIIJ3IJvWWIcdNtpOQpQCBzb2jGRdi
aEIRg7s0KcdEMNkWg9br-8K7FFWgbsyisIJdwyGFMYvL9iguQcQQT2vp2eSiVnqJFMI2AFHWe5BrYMBzYKAgPhtDeHiKIxu9dpF1zkbVwwTCb3xCz8KYqita
6hgU9PVal0aEsghpZrIQ06ms44LqsE0LIxx9UPH2tLw3jlCmGvJ9qkdrhik6Igg9sgSePDegZuaYmwxe2wKFbKjBssHnnP97GdAoJlpsCQbL9ee02asKQ_32
QAdOGwac_Qm93jhvRMTfipM-1WoYJ2IHOOFB8ytrK8w9dZR1cTA6VMrbbbaIGsyK_aBv-aF3Uj13b672vqqGfTJPCmyVkUDGRfP-ZvR6XrietyJVfpITABC4
04LKXitWQFcbOZarOkF5it-VGlr2cMCqGi4U6WJ5ab4cqllHGedlKtghNCjCunZ5ZnPVB0cjSzGalazvfiKes4FQUFw5PrJoJUBx56luahP3yIogT3LHPLH9
k2WuP88eAbE2naG15bQfY8BH1qetw-rKiHmearCeUb_6bYeJ1NBzSPahsQK_K7GkebMnd3UHuoOUXUdAP6dQYij40HM78jfjSAtqKvK3M-U4YTsNzbVQnK8j
HX7j8ShhyHbRY7xFHFIuYKT1bSj3J6g88Z9257q-Fl-eXRQcoNaJZ3YMMiIqymvAXpFkvorqj4pwi1zbU1OQLAMtWgcoH35xtipHXorqj4pwB_okEwPILMl1
j3awOXGy-lD7AkS6B3xn7EqXubQe2x3SpuWnofMkiuSwgXmrqKsJyoorSAU2gRn4kJXk5jxAmJ91a_CiJBMADjT3VO42pubxu_R0WCNOmKWmMfeVBQJZRfO1
A9vbRBJGkSw9JSwFbcRgJlrqhRlUHLGT2lJGq7TLtkgSB9EOHQmNbohztkE8ubdULDaeamoJc8MXKc2qh53cgMNGEoeR0pR993xvr_8z5ADWiOpoXih6W4qp
YOkb1IgLNoWQ7fF7TU3ZPJOw9zSaVY2AMLvN1o4Agj079Ypf9XYUAhpieIPmTH2Yh5LETWwQ9FSGtIZIOnIyZ_CvspbTxKz4ts9PeAnL3dQEhvFqqL9eYI8L
LEXz4-sP9kk4eyM7hwaIevX9M2k7ITGWIJtKwlT5D2AK-lZCtslbPETWcMJsa0noY-WxIhzGhZywrAaSAXCqoMSHwzfAyFWyHMwKr-iTgC9yW2JL93wri75J
zJtqnJ94nuKoq_fKUMkUI5wPx4V3-qh-_lXifbr4z4PfzvUn8ixaV9dazn3ZVINUpCcL6yMkbr7vQYYUEKaoB26xzvM5rA7CbpkgMb-hS5BddFygf9McuaSB
ebGpcwzfDxXrEbCcQd-DI3nQF0jK2by5VhKP_MyKbgF399-baeb_VBvHO2StV6Js98VB99-5nRIuLBfHk9Qcy7DuFFFREoT_FQj6Lr0JnGPTEtcE5eQzdD0v
wNSjfTxRv_MIOOTIoJcjvLygtDl7jDwZHK0buJad_L813_bsZnPbG3c-XlCZdYLMcGDbZfPk7IvjipedVxH8BPM7pT5IgPMxL3ID97-qpBT9zHujzs55KjTm
ybSXzUgSUxGCdYW9XxKK5jz3NpZrgtFkqJ9VAyqXoU-XpdMggE5IxgL9rXLiFikmJdufLpK5b8GoIHujmwfgyqkvrNqKEvVy1wBNNGiivV94qJoI_BkMWgD5
02MdS_9Pg5QUewNMELguq0QAdKv-3-6hsysaqZ3hW998ajz3hKjjPeEgc09A8aa-Iorzq1oqjG1A8aa-2rCtaliC1oY99lcN2YJMdcSuGCaboU-X-Zp3AQ3a
h-7y1wBAPjO19O4aDoDaKK3vDv6iNzrkl42ndEJVLxf1cq-Ipx9OoVOlYhzK252oIVBlAzcXP9Fazv17oJV9PubHB3lveyMZM7hoYyMXsByzCWCeQlPV7Cf_
85SGnVuBNkEgD_al8d_vplb_
}

