sprite $image32 [236x176/16z] {
rDFLWS1G20LHeXDF_ztk-ret87QdWuFiPyT_stKZdAeodgWodhHJ7ypfIJdrkLoS93IU05IMozq9GCMuF2W1gOAM9_O0gR3MpAf0YbgmKFZh6d-rsN7K2wsD
HQeuIgfWXIEaAbRIL24hvALnwrWQBhH2N9grJgLBhFLGIc2vnTh6h5C9ebeSrlg70jOkRIKWTLYjdtxiUYivAdy_JDhwrZ1zQQWTLiXGiJzhnlEiO-lOgmzB
m5hgph9spXj-8TuyS5q9OIWgm7t_-_qTVOTS9nc8D4VjzJS7RB09-SsMANR5o2jNOHw_Q9Cn1Z6_TzLsALydswhwyJw7N7cC_BoDvU7JDaXAL-yNrgQBihhX
ckcY6Q6-JWlfBtZzQXBEhhIn3aysLA7hYz4UoHDzjowGsk1_il_WZJqdiQ6ANCrgsyP_H1lwbgGfx_2fIITfxlTSTKCLkKP8gsr7AmOXKSfqJaC14OQkLsJr
ackz5pI65cF6f_c4gx6IKPjI17O5VCqr73qHuHf-g7jUN-tbtZdQowKUkrwGrMkkk7OZZt2m-D3phklbU7Mf0hn9n2LNnQexhX6o5efJHQKjyx7M5-P_Fsie
hQ4jHrnrLQHwsTLjsGFRgiEmOlQdga4UPyuDDxF3uw8hbjKDrnc6ta4zxEOHzZGjKsIndND8Vp-VFsK31COzhZaCcyK3xX5FiarCL-PacTdZugMMfrmYDboH
hEwuvebPwdwV5eRts4nI15W7InjTS5rbTTDrsbfxY35B5WOMsHM3alFhzDHIsBZ5DN-RVCvfjc1KLAnuBFZ_htDRJ44nZLonh9wvIcvW_ScYWSAgjirBqzov
cY-3SDLLhxYENt32awlaO39TCSPDm8evDlrDJwPdhlePHPW9F87FL8qkq7Kt0wtGb3NTTDNlk2uXIj2rjgtXljIOLYzedxhghYiOOZYnPHtVI2jahVx5LGzS
zT1rbe4Ryvfq6SmeQdFa2wwwxOhchBlfWY37JEk3-1zZj5Q4_9chNd9rS1fAe15n-DBREVmLrtqQR4JGpvpJZrtr1C4TgdzjMbjUZ6sHNT0tRBbY3y53p4TX
-z3SYka9NmjXYeJdcT-7_B6hwM4tkMQHxf6nRwXsUtgX8_p8LK_WMJv4eKgRdZabqfcKXUbTZ9bKHG3t_V2D5VxhVwjhbyfqx8Ul1u1-ZwhTvzfO3OSljrtJ
PayfyTVTAC9lS-sgwiXKjarnIlpMT-A8k75UHRyRleHCPylFSLyGKpeoSB3wxkypE2Na5jUyUmfugjFmnIcXSMF2pltLyh79DlfkHLUxqNMADVb2eM_5IIBb
HiTkSisPEK3uxglYbA1RNJMle09CztArI0bLYrihfo_HtfTUNJrzzmQ-vIhlIo-DE7Eruuojw9tu3zJxUrVKES0Wj_jSjI5DMW_YJEYbS0VnYuFyGDNFwuc5
8O5nwUzSlSuEY-CG3jLlHd5ZZnSulNQj0qRYE8Jz4rTf2rAinKtYBLovhY8CMmBTvxE1UdCgFP1f3PnRi9rGLitJAlo8VEhgvwvEe707r9VtSRl6RLKD_7BP
nxVDprqrU9vlPjnD4sR-wgwteoUXHTKEN3qYRDirFvCkdcQACA_IjYDNTye1uthWclx0WIk1UhR6YYMP0iu5zOY97hXQ_EQwgxgxhLdLVUd6IinXsWfwm97s
6prnzJaB6xTWxBaHaUMl_RthtqYgkPKbZ7M5yycY7RccBDXq7Sl3ucviQ6NBuA7HOMJtD8ZbJQxtcHEswqgjlClJtzqimDU7kUmNIOzSq_AsuogjlDqoFhY-
XQyFz_eqXmvSBIQsuzhhwnxL8AmOsdr6UKBNUDirxORNNUL5VyO3oUAqrORV1OBfikTgUKEyw9hY3Wy-zu_kCqa3FlJgt7LikKRccckhdqLyZXltLePXcPD3
F8q1ej5rLu-CNt6jeOU_PIRZHThIK-pR_o2Z5xRzegl58_O5rsvvvAmwVHdF1sTjYC7BVvYBhh5oxDfqVMT3_bIuz_O_a6TAjZO6Ip7oz1rNq84TkZ9uQmD0
-JUT7bfiyBFcO5_RShLunavS2QH_OMkVF8o3YddJDUAIxExBfWPrtTwOke6AUTVL0xBhAi0Kd4QWV347eg1YtdRrADXpxGlBQIFqDVWaRaN5lErgKU6AERa3
cuHziKqFCk_vyuAecJAtJLUB6l--QsPzg-_FSku2Dy8O1g9mkMCBSl_J5fwet8rbAMlDky7tCoHvIrBF2YbRL8fMwqODrXqgnLJh9fLYg7MRIbrMlZOUioel
IZrMPUOng_B2DCTAtwsHLC3UldMttK5hxXJFNyj2XwpApNJ2odEJjljiZTmk3bWfIvMf51Ejoc8QPuqi5nfbLTOxCVolRbNatws6NTDSbEBmfQAL0ksLfoIg
MYccIsbXBMXdIMc17QrLPAkLGbEbjB3ErIelRu7TIREaTIl5f8ENQ57Ih4DPkTiYi9EuYYnIiSxX0grPAOk5Pa2X4jO1NA35LW5Ry1vtGkt1KeGEECzOgTyh
d8rKogOYf4vcDvMIpejHHj8PQvsiBMDaVuiAsB8wW1Co4RwAi4wb75NTIYvKSg6I2PLSgEH29HigkL39XKekL7AXaekKRAZaGYKRARbGoKPABbIoaP8DbMoa
v28b6odvICb6IZPIif6I1PJ8HqeMK28BA945bCW3IkJX9F9m4fauYGoOdU8risiolW8
}

