sprite $image160 [236x177/16z] {
vDM7RKGn40DHX0iYlqxRVxNEDc64or7pEXXm1TLZw5CHMDzSirifMarD_m7ELq7OD02fOK1fr4mMIOpQhGupu7nZ1IYD2L8PjKEdCc3Js09AervDamIfbGI9
jIus09i68JK0fG4e3TUpiYH8hMu4K1hZASyNC6tJpG7EDmme3K9g04h3WD8me3GUzCz0QlLGWD8me3G683K0fT7gfgoOUzf5JmTmlk5RbJ9gcvuOeJG0vwi0
b8RhOYkz3CAe0IWD0qfZE-r3ZG2C6Zwzb55hlRmjODGueHHGkqYGM6io3N2-GIWDIcfYOwMfZQhU-yYcKwknwtrNPG6CiVke5O3x-D2j-ItzlJlxq8wTns40
l3M9IH1u_wVTCXhFnU7wA6N_8Wkdtdw_23GLJv5aPUmlhHfM83UlRzKlApBsbMQD4CEwhpPHfpKnhBMdDb2liF9XBH50R2lrUIr9ThGR3UgrLOMTj8cwje9F
Av3RrRTRKQSLYBtgswrKeKuhCcukHKsjug2QTfVwTcjHWYUtalPp5L1fsjXaKBiL9GceYBnpaHFrkRLKV5YFesbtg6-tYZMiHy2IkqZTIed8Z6P5nWRrxLO-
hyHcDUqD3tL-hXBAhAQzlzIjwjRp6LK4aBVRCtDhIMuzdyWrgXst7THkHV5_hKDRaWJJtg--tPh9PdqaXxNmq4R6FQLk7SPcFQVXj0A5Z9iCwjmwDciqwz2U
rfMwdAYVM9tGhNwJijzwg_fsQqQpUl9fBJoIzwfljo9FhLaxjgGLZZOIzNEhQ-TMqRHtgM-t3ct4PrQ9CEqzf6xre_t4wjhbw-jXrh2wzdFhQ-76udl6G-JB
cXYPMK-iZUtIzVMGvxbMnecTM07JmhIBxPdvl5QEg_xSAWBiHSurwpktkZOphkUrK5sBMBM-7fdLK8xjLh7E8YFjXhcuj4fgLZlQDArRt_CiCWZOs2uug1wV
kZ2NQxlr0r53crJHndR9GNMgq67PBb9jvq3ykrGeuL1H1sL5NhA-LT28mLukrveLe0u8oXXZ-r42aXm76x6sj1_jwVAnDIkAUOGAAW84bM9A70SRArm8UsHf
sk4wmhKlwqCByN6a1L1l4gJNsyPOS52liNYv_7r49imAb0eYpssR7v94F8ys5gflftOjXjL7jra1LXIVmcAsE-CYUyQbFV2qRTkiA8BIqqYp0hbiVJtHhQvr
Q_y6hsXMPApsz9qVROQzM3nJXkrQivfsfK6TFgJyQ4zSmKCzGpjqqowpP-PQlo6QLOIdN0luaonM7DIvjblLjGqxLlFFZZR-O6alSdIhheliriEq2-oPRnrj
jufTwrPVpHchrjV3NzfiqtbTP5wlvbYtlXxqL7lRPAbkjI8li6U-Zwt-jibJjfgxTib1dMlBtZRPsFPazdj8BZceFT6iijUc6I9whbTpnXzy8Vovrgr7rLER
-81ghat0jEiDQezRfRV4iyX1HQbfhrVpjJPMgQ_7TmvK_z13c--gqa72Sldo9l9gR1UIUd9OKTHH2iL1W5N_X3wEb6kFS2qUiIVoYeFQCwn0COxKyHOeW54w
XCEBV1okFN_EjAlicRcsWA5LIl-02YNzGmhVFxPOpU_NniNgEvzSAbA91x0AyUwtniDWPlLhOwmkzSjIrV6UU0g9eraDTldvIHMmEDMFjkeD9xxOh5tRFpyX
MLXTwbg_5vTRBG6_DhgLN5OwrnAWMQ-n6SswqfxvVE6MJ5iNre4phLdlSQW-jbRakNKKsQoBI-T5dblzRa5aSU7wphLpQqN2GoPudqFjHPvRsqMAPF5cKjVE
hORzyRnIqX9QVc8rxG-jMYFmpxNYqchQ7rcrJDZVHtJhcVYPLKl5iHaNrXXVWlo1DIMjgALftPeOFndVjqgBMYNJkbLyQCrwIwbZ9QbUO-jMgP2PtxDgrPnM
sTYwbIgptbFgskAmdbgtbaHytGgj7G0bsICPBoj5IMQzxw6w5g-uLUBNhTGj0izf3UeRLkWkuONrEFBhLjqfQ1ctY99RxrxVhlLhOnH0iyxgUtijHU0Jgont
rb9IpQtI7bYGyWvl9UtQqjmgQICjPTRjfAuLgsZMtQIEbKHSMhLJJgjtU3kgQtbjrORnPnD0cdHBR75OAy6DfVv49gjer3q3drTjdlsj7hVk7r1ctJsKMRSF
-KTJ_mq
}

