sprite $image117 [398x268/16z] {
xDq5RWGn40NHy6ylZEz_sd1B4ORZogZU5KhVNjxv8TAMLpTpDUMDkPGEQOGU3WEPmnQ4wyCMq7tOejK4CCQ2uqftQOZZobrWUhWBI0-b8NBOWj53bI-e2U0k
OFimHjicW2rOyp16kvi0jW0SLxRWldXbYpQ_GHT983rK2II7yZjgVff66cKV3eEp3rjmvc4Bm3oqfS7sOGj-3myfm8ibFjk3pSDXy7lOWl_moXRVV-_35XvN
nkWUgeIRmnRsi8KzmkCmK2vyVH35Guh55YnU62YRmq2nXJqMjx27BRm-Rl8VEGmMMw3u38F5OR3O0gNc7jncBpQ7WRAx5lQmXJqEsIU7mM8BbB85YnS6oet3
GF7rGHRVK4BnuuCiNXWePGiMOw3WMzZ35lOOeR37bYRM8INMt_O8zLgj3gWBGnUe2qEe5YfK3B5QYDL2g4UrAjGmn6eXrgT1nBemX3gbn7fDIZiTXg_jZeem
_rKxHc5wU5oDHvGSzXY3qyCNIyRWz70Uuz0zifmznk5u8Cp37bsZ2j337bqZ1RW-pD7RACGyxD4d5Q67FRh6J_VGTs_nMdnz-2C03-tTYMxZF184O4gYo3w8
-FtVTbSHd2a8DbUntCi4gSRntvU_wIgAqUG7ZNUl1-U2nd0FUg16G5nnoYKDz90tU71Ur32peN553zHehVdG-g07QcnZ4VN1UL6ZUKXSSV8tDNp328ihpYiQ
srY41qTFQLJGC8-h3yutD6nFAG-i3yvtDIoqFZWdDNGpKBNW-k2Srt2pzZKUKX-SKnhUO0pZIchmUj2Zht4_Ozq9eZteqTUmVyiXLRJMTyOLn_eQQWSDt0rf
BhM-ywwTyt5UmyrGGxTVV_FfYjFJq7k1s-xnkIAWqLp3weDnXHfO77PtWJELtJK2wuFheOQVi9tHg3LeFLWVzuzKu5m56dR_s1qqeZou7_idYklXMuFVDRu-
z8OQRtxwu0XmFF0uQiWd1cZ4r0VNGrIFSMM7sb1Hr0YEAyRLe_h0Mrn3ZPYuudJZ2ZKSD0PvqEEh6jf18wO-MEQTk3AzpnvKe15G7np59tCxUC0uQjI8kEA8
kOF68Qvmsa4Z8gve0HeFFCvhNBnhvwWxQZnx-i3Qk6i4n1KN0pHmu4UuFD28yQ05QlJZoliQr-k38OKQVO--nlNJBYrGe-yXSjG8Y2k656hqrmCr8ZneWHfz
Zrt3KUEDzS6GGetEVDm_KR63Ha1zS35GexyVukvcswy6UD02DBfZNt4b5UPAVN14_V54V8_MVdrmrFnb3Rmi2LiFXXHgz4TZFMY16YVtGsg01q-r7Ot0-X2X
XVaL3PmS6LSCATGulnxqk72glQ0HVzfbOVGruZs48NLL0oUWFcW16X4SzC322D08g0-UQZiQh8-8a8hNk7tGuvn5e0QEiJvEd6g3DNXPSdunuZLmvBe7BSvg
y6iV0I4Le04ZFErsB08qM1y18HMbSVjWN1qi0ZHuMH8GKl4Ql2p1Qv3n6hmimP0Qhy4lrOfw90Rh8pwaSEm6m_eO6b9-2vWSK1z_mUBZ5ZJ1zS72YESG4_Ju
KuNHRZ03FN3LfPPkVR0mukzsHML_WDNoty7w-2CM5kg0ww5d_djCVSEevND-LLof1op6oBWICtTtCvETu_V4bGGyOOpp4FaC9dCt5JFJUlHG4HO6JEHTkwnL
DXDJsL3Cx49SyLHxyRrscQPLDe-wxyWsKdw5XmOink2uaYcbgKZT1psEzS6GYlUGITQKbeeUJ-g35k7r8PCrMrBANnuYXXuLF7Yg3LeFr6XDvZJLUeoh1tNE
mWZoG8tc9PLwzD17zS6GYeWhrDWcRneYNtbbFxC-HEEkGSRlXqo26kiA7W7rCRumP3X0XqEcL40Zfxb8N7qmfFeUajE26XCST-FhWnR7-YYpWKRHxRWRKH_Z
GwhTVkfKt0zlbkUoQxGc4poT2tYSYIkUQg__j2ZDANrfj5QcbEN9qmV65KCggCwNjFxJQ9ONUVhq8N3NphlQc2_LbWeQJL6ZOdrKi_zpN0rwmXX_rovvyQC6
nfLMTRUSqOCX5VRqaTFig77qC7UtEUMAzK6B88yoxpSb0XheiM78ckR3YuaiZ9ZwgElM70uQXn-fAjkVStmnaQVQeFKGTSypQC08TCp1Wo4LvL5IMYJWlVPV
-ShQ-BlsCe76MG_XgJRAOxyvrF3tsXbIvxyqw2tQWnRdFQmrb_92VV2BUm7ljPTYpNrV4oq1zH7y4p5-_vZYHxhUqshRahFhmP2AYgkoYkmQhTb93XLQn7di
6jkSvf0HXV5nYv_nSGKQPpbKU0qIUDhLSnemmf0AyoYhkeF62GuLXbIOnrfiqyYb6pWlSAXpCLxngAMMD9rO3l1WI8N5LQbrIYkiI_UO2nwqYAdpilmZc5A7
ewPwPmb-PUqFU-3CAJ_NAAagh0SB8_oRCYphy-ueQQdBBE31a0fQ3nIP7r-mbrJoDAqPzYFmL4kFFFVYIhBeCcdDwyuXeON1k5hIKcjTq_BqwqzvagNC2xHv
L4ZH0vyz7dlKkKfEKrq5FPGM8QVTikr6zqcmB7N9IvgWFbIZB5WV6MhZSNrCQKwrBcNd47EDmc1ShVyphgIKL5L5FyVSxMqM73jmv0KVq1_NUTwA73JUTwhb
27Z0WlJgOvqhQ0Iz3SBwm1khVdsieF7MaEAaWqV99zv-0mrQZFm6hoAeCJoaw84QunU37g0Hi1SS-vQ726YCtmkk1sWCNmnw26Z4BGOlIm8qQ17ylrz1ZNWB
NfPSruYtO7sWncWCnXLgZBRWUg36s5CjwmCrp4Q_3SBzG8tH8SNB4jGORS7rG8tH6FH0ZT4Mz42DqHRqG8tH5kH0ZT4Oz42DqHQyQqUDqHRqG8tH5emhr1Xz
9KKFr1Y-68mhq1Z_ZZFN0pN6BmOzK6Ey1JrsZHzYmVhODUmsV3ZsgU5o-o73kBAVdbB_0G
}

