sprite $image219 [381x259/16z] {
xC410G0010Cmq3-p8DzM0G00000000000000000000000000wDbxzkrpxr4T1iAui355chd_oprdUuk2II4sni_dhV_CJoziIMcQvtdvtZnFKnfZ379OlJ1E
ywg6-vckSng3lB7U4AT5iJzTfd6Gb-k5vBhditMAyaeTtl1Iptq0lJWhxcTc-dTcPd2oDGLvg2vlTzKra_CPwBJJlnVkoPlkpfxnxoN5RSp3vpy0JOFawwFt
vL_tNwBuzUBoehplp-pyUt4zWDxPlyrv_avFGhrUd_yIv9WwlP_FtnkM3FrX_Bt9ChV-8Fv--oMgCtk7_W1-c-JQpUx5EIuZyJiT--mT--F2N_pB81TjmYTF
Zl_SQKcks91vllpK-DSWbojQANjLuxN7dr30tj6_ukMVIzdxfqUZNAUrdBslZoGNQT2Yzhx-qkqBwkjmMNkQbjQtqEqBwiThsaEr1ltnWiyvf1QA92xpqBEW
rD7nimlfpoXrTBh-wDlJj5ouY7wmkeRldtsCqc9Qs_3zmsEntOFl3x-cmsD1MYkYlk7xquTAQrcDm_UdZxMverCjll56VvAM2gZqwlZJHvI6MgiTlZzz6wIP
HjIChxVuMAIP55wi1H-EVcf_-3IjvkuqUdZqBZvCgxaxRHwUYDhnuUb7QQ6bUdppy5KQQ80VAyT7alCtrO-lzFHDpf-U0R_HwGUS01yklhLpTUh7Rs_wUc9y
RUXPftxynfxrnsryL8HFeB7NtFdK-1ZapAtOqWUiRlmaPyusyLaxlZRobE_ZeoRynkvEF3j-alEMilYcvJFSiyVQolkjhrytlibvc_FuLj7LQUizQydX4wWR
FpNmc5_pz6qBVsaR7rNZgvmsnGcclsKFD8rFeEBX0w7HimFMC7riuyU6y7tzUeUFrC2ZPhLVSv71drfuoV9ZQNq3j_7dLl7B7nvpXj_AW_wq4x-OFi26yUlM
jwmzLZbh2LNh6rh67r6d_dvxg9orW1snbFuUUvYSDbIi3x1jVAjN7yxmsy9VKPE-Rzyi_eG7zQ4VoHpxvl0Z7jQtZzeJcLJE6znCrLnz0h2QxB7AULFV_XOV
_DZu3U1UUopIrj7Nhm65z0sFs6EIynResnkGuQ_37gcfVwTiZhsZ3pkQdjXJb1CtU_Yu5m_bDpYptuuYJTqTWzVn_ERCFfl9gJCy5e_XDyCJzbZar2NYDNvx
1psUeWUJd3jiPAgMvOUzbvxO7OESkvaRz0w-2sMloVlq-KnEti0jUuKVR_tjSNZpVh3zSPQpjn1kl-pzw92PFIuFFciFHZbxWV0oppxl3pFRxGx-5HvDfD7f
_xh7Nbay-zejkbdcEpTyTVm644w6NV4fG_uJdeX16cWYyba6SgybRyDJKQM9Z5dwxIF4vyEpSPGcYZa3tV4LuAFo04qQQM7MNh6ZG-3zcAIH1YESt5VTVBlT
-_3pXyUtp-UWloioIJlDvDRm3NL5bPRI3NtxzyD0uSWeBJM0s9LfSNnoaRQAv4xxylWOfB7IBdqj_nM07AMvPl83m-z7ns_Dw_zhhseVjpTfCdNrDx3ru_Wa
WbnIl_mh0CaaZJOyfgzV-hJzBDAoFgiTFibLfEkNUDyYgT9sAydT-FPPUnkayPRz-kZsxsxYJlvkVq0ZI7RxGWKZMPcz3dAHXfKLyRFOCsO__2IvoAMALWa_
IIIvMaiD-YHfKQxN298iV-u7kMB3mgyLfSSaLorQENv-JODSk0dyMfzzoTl3FliYXVNJ_EIl1ynUL8V_OFfPFbtdv_UMGNxNYok_zmdw87_N2mlulKFbuTBt
XidueyFevq7kr1jN7E3F7scIxVhybU_qvy-mHCdM2vFnLs-19zSak-l-oZzw3Hvh6kIHUaDQy8R__ezbV4g-5z8AtWOltePr2l92lP1c1H_EblGU-5uOfzN0
NK7d5ENDzOQOfcLLW4umNUTf38CSMsy8COw_Yl7_TkXO0000062Gl_KiTXL2Hpa000000000000000000000000001
}

sprite $image219 [191x130/16z] {
xC610000082W_QaNgG800000c7hpq8uKXg6eZS4WlQVv_y_TCncJ7HrICIF8tKrlL_9pIta1UHZAdM78wIynZDCi2e1l052LUHg7T7bANHJy22DKQidNJSku
F9a3WAxW_rZ8TCbHQEvugAkgU5HrBK7gnIh8LKdYuVvchbiU9V0Ebl5AyY3PnDIhRqi0tz0ffqjmbr-TLFGxHFLHBEe52XZrNHuY-XD4rWAcitEphF865Vqf
eYrkMavjFGWsUz7V84eZGCxd9QXojQUA_XA1aJnn01QIE-tR03mIL4-9lH1yOCr-Z_-T9SVRgxVly0TrED4UeZiHjOS_WlsVaaFTZ-0K_vbWH_DFzX-VxAbz
SFNFOS47sTzyl_o3ce9ONFDxuUg_f10A6qw_j_q4fw1LnsNdgFOpPleMWYjsWBxG61YVnUbhlpxitNzChsQWZtw_lgxw35Xz9k9P7yVeXxLVIFhiTqFZYWHi
MI_KPubQz9k-7gaFpY-Eli7fKm_AVaEZpff-xlOld8qIjUflsz-l3zQmXQVfY_P1r_qbKfz6z4RVwskiVdVwOKuVEIhxs_ZqDvyOelMx_6bUdqFSmjdyiTyV
RFOnAsSb-87_OSq7nw1Tjx__qkpZz0ktMFFljM_wOITEFFdl212QlQS4BVnGvSh3NphiW_IhuTqUFa24IhSzSinT5ytU-V-u0F1ZUoAz5gLZKy3FvOqRG4bn
5nO_1iq8gf-FWJZv3R2QNeop5nUXrGhDr2FDdURiesQkdxpRwSjdCsnZ13Ht9-_Hz790hFhW1kU7TpPlYyzEOpJGWUqOh7pmcY_9wVM8z_SHsWh_L9sm9GMG
wSwTphwF8KKm-aCktDFTmEOKmspSe89EUwGePEEFPW_knKeAGmrqgBfLwFTOJO6eqT4R8PEKJlU7wavxJS78ZLkmqnuvHJCR3y8qftWcCnx1hTb7C-Zj2Fib
dSNSFG1cKpgFeZVhaR_fa4vbulu2Z3MTJPvt5c2s3Ea2vFhx0inCIhe8UL8p-qtckPHq9Se2C_kPkw4Eb_px5RjzNOBTtUUIBagfybQ2sLRyhawf9LsRCiq2
qcvtpEpnXD1vAZdz3V9GngdM-KwTnd78wI_nhpqu5W00000Ov6yzYrtL0000000W
}

