sprite $image2 [153x38/16z] {
pTY5ZiCm381XCxt_-nwJ5KVJgBrFUB3gL-CLKdyXJBZ-I7YdgkuURwgB23SL9hY8MDGy8ciuXjjjONLPkjAsIJth6hU7pK9WWUBL71NM1K93hUffOPaHRczK
pSmZQv7jc5PR-UR-C3TbGbYHH7N-PnMpLk5_3uL4h1PvIzWbiZievJ2422FanuU1LiFRy-K4Uqy8mse4FaLroG37Xi4OfkktukWmccOCh-o2fy-OpnSAXiF3
CASpazK471x6lOl6vIqvD6oz4Jh2FFfuNPZmnEOmvBzKrJoh2OPlNdNbfDQLSht2py88VaKrSLgOCpHPZPzunj85js5sU5WNWey9KvdiXfyQ5XaUc5CtItdq
TGmbgelDy1z_vQUeniVBnV5XQmKF0qcdX44kfmohitF2T5stg2Rnb32kPhgu-7y9WrmMy_obd6AhxFJXjytBRj39bmkQV_t6wSWmZcgy1tUfOnkntXHc-RKB
Hj0XQTJ-mc0ro31LVYUgQkQPD-zTU7rg6oiUuwPAQ-UiQrmVTlCs54Z-Xp1dM976gM5XZB21h9xF22CMKJLtZuYSDeSHBi9fTpWZt4rLv1K
}

