sprite $image43 [230x167/16z] {
tPg9akkg3aK1Cqd2xV__s_T8KpT9s-uj3kaKyQhf3cV8YhHRHdXxCrJPherGvTgUcUx8LINfcQixDlYIWRoy9zC9-NBDUkboCW4kLCXBrvDqy4KSBzksdW0N
AESNTNE9PiLSO7fSpJC3bHmoYES52XcCCU73oqc0Q4t5Hk3voNLCpfY6In_gwP6aDuzu4CyF3QGrpzX0ftpDwIYuMVTOqBOVLiUyc6FS1xKjmK2Uu-apF1bF
ZnFWLE4FcXu0D5NcbypUQ5Zop9u424PBcBPj2P2iqMFZb9g-TthOvJcDTY2UqqwFKEBFV__fwIUB9_LEZuNNzTdIbrLynqFV18wWNHsLjN3yuIrhuKNTjCJJ
RQwuaBjNA5P7eX-MzLUj9TkxOouyoyg4DDJFdsnhJLcBC1rO4ajP_ujh-ovcq6HIKZz_Q86iZaUMpLFy_Rj0yDT4Zktpiy-jG2UMhUpagQp2KspwlfYwuBAk
hK2dblTVntCiugaVlZaYozhUCiU5Gw81W6K_F8qZjfpCasWsoyeaZjXocdfccjIoylOHYGdOif-9cZN7iBZT-IFbAJnVPBXOSuBpYJJaPKa3Y_Y1PO2k4W6j
yEoITAtk_wIS-00P290Mey46tOaylDnJjU-m4P-aHpsJqnsoKxyZQ_STBe4lOdI5v_MBspnGIBGjznby4LgM32rV6S_ERRdD0-jcUCydlFp5lOfgigDQ-ZCH
w_wFFQjpF3oYakjOtCeB9AFxsMPqTFnTp04kP9RRURa89s-1vdw3XEEfB2TtRilRlWEtguqtmRLKrahXeuAduysAX8vx5Nff84qeQn7QaGuILxvBoCn4p2nI
NINiVoKTmBAkBujd_xRyS26rYr5Rp_6-H2jPLOtQudRyNYLtthKwEbj8nLtOQXLFFhlilv9ZmlynPl1UfVVbXy32b0znvXbV2fylRGNCrO5dm-xfCO2jagTm
oMO8cq0yzOzp8yGcUQhfp03eeK_Vh6CG-185TyfuEHcTFKOX0CS_h6L5zSxLA0bVMe_WSYd0Wfa0GgEnyGHmPW3DRI0Bi-OQSWZGK74t7CxmvlXn0pck8iBm
Uau6aWCtahidchYUi3i3ECrje9IrMceysHyy5PoHUpHtpn1MoY7i3vwD2olk5flbKTlYCnwLzPYow5yFtQSXYlAz6aspjeye3QR-U7hYGuJjFa3Qb_HiuOwJ
0cp29qliUNZ6yrd_qEQJQet9eZafv7KjQiTg2JtxptXSul5wEQRSYfZ2yRuz5yO5Zyf07bfgfafMhM2aQfvXd_IWPFZ7wR4UMEhZ6JKh65cpDTrOMWNkOqaP
o7DBtVJqUEophEowvweSI1BpyW_J0rZgueaVbgNtcSdcKWHCiRPdWex0KXrF-_ZXJhSTGUyOPIty-nJph0baMR6bFfxmnrsjkaIhSanoBj0sbOuKpTeSiQK-
dl37NMsUGju2HK_rrp6gK7SWiQKmZ6SXAgiYnQlySbFhmarHi81gUY3BVizx0K3PwoyidFpFPuIGgBHbD64qWSIM_Mtxz0kWwChFHInh1IW2OBDYI-ofXrc4
deTZAGNqovYZtdBWOw3R4qVZu40s1CApMqfPiIM6PxRaic941KzWYPfrt5AO9x04qmDROdW-IwwEmvRZdYdfB6CUS1opZ95Hs-BR1v-nPLthX8503bbwuz98
F4FRb1zRsXytCJOE17B8ikuVKDlYIq-RVhCCO6cBcdNSiX8OUwBTeijdbj7YnITs7BSqDiAsnQ_2-BtbuPvre5d7B6ifO3dnwqznPtdm-j108GSjAw5_PKAx
EeLdos0FzgoC7V_0qdutrI8x5DUU1W1kwTJDEcx94ktU4iUJ1Q_my2qTTXotR9baNoq75hS0S4k7cnMpVQ5SUXQASengSGk0jtJZZZVGJv_88lpFdX5ukZpS
hDYn0YoD5zuzx7N4qm--up7YMBO7VlqPMotjRchgurdEBuRyU22nuvsl4qlcQByjZM46dlYsllkMZcKaa7jEB4NODyl5jdgEJXNzBTre8B5dQ9OY3-z3y7Wy
zRTqFEw8FPDhbW8ibMrBxcbw_Es4_8qV4d5vihJ6SFQ11kBvfkc1AF88ouDbb6Jf5j2nUDhuRaSSpxibYH3j3YdT3trUtj6ic7DB4VQculvvggnlcXuOFhEi
v92NSqti-RPcnPnPyk822RlJfiNnf7Stgzupks_BS1i3j-S-aP3xopcLu_wXBrbwNfEGB6QX4S_tDokE9ukqMbfJoR9KLz2sipjM3jzZ3fpTVvP-2GGyPsjM
x5dDBClIBB_HhH8cc1vgJxB6k6YVB4qIu3bRis9DPsuqIzUEeI2UapKhzkJexDqoIQYkndW6dfCvudfoUB0ayuq5qtEwGEApIgn-ZvOLwetd-ERghprzVBIC
DPwkzw6F9t14RVjeAV8zGa_XIGE9poh9FbY6Tkm4djDC3xqdXxjblArN9JchMYNmH8vuUjApPMwxA-0vMI2nvxEbRrE5v1YUR7hepsJHtYtTpV4NJU6XG7vj
0um-9DX7orIdwI9db5aBYUFPBByVRLDjt0Gi9tJ4diqocCeIZN70Sb977C_sCzRz_hnNfdR4yVHUQZ1Jldb6O3ch9FOKIRLNQrsD1vOJEM8EhZqNOWvc0PRp
EkApocqZRUr2zAgEtIPXfra9_0hBiat4psVuIWAMazSHdrKeE1TbsB9iqo60VijjIbvhkStAru0bSFmupp9z837b1PRR1p1gkNq88vPb-nY0vGKA2UDPhk9O
wRVSFf8-o-rJwR0ismUZjTm-78tbTW6WvNO9VhVSBiEvvNOfZYtBTZNsbcMx83yjjuloQBbTcFyijqjJgkNR0_a_
}

