sprite $image110 [239x166/16z] {
vTg9OgGu3WRWadnAhgwy_zlkb4Neohym9cgdGvX_Toxc_6B95xnzHrJ-oTj_8r6Mw7z1Ax-ZZwjZgtpCrOSMevV63hoNnLwyXLN-BHSUskjxHMMOnwNh6ADw
PIn6s_qAsCTHxAzV5z2sOzf_i1VWwb5ipsMnMCUMgseHYrpzUHlBShoEaVi3jnt7iEsf1ExFEpayZjSnSkKrrnbPAsJa2gHTOuQoA81L_Z_NqM8ztt_UuLyi
3l2zgModNW2BBNnNsO_-y3B60OQX_GctE-AFgenoykkA-T5pr_7yd0OBt2k37s2zDbZbx-Qys9BzgR8NFMiTyysVShuH5fNluAhUJzUqSxbu9t2gJHHo-JCX
u6uUASuqjCYDyfaav2BscHECx6JkQIwaLRw1ktaXhQ8d6DevtF65T7zyWg6TpSLxFBYW_LvidSx5ErgeCVr6h6JAixbu8Ot_9Lg_hMdBxNRB8svDaPbwECHS
FycL_y_tOANqRK82BbZfXWcVAEPx-_AJWnpNzgHTRes0xQ7ZKzLTl_hRZgfoCFcs9EzmYpt4y7WXqhjXLNRpz-yOq-e5BlmuXiNikQ1L_NihBOAI81Ur708p
xN2T5xGweOvzteXSAI_KLCLII-INloQkN6SUN_ALK8fxeTK4tBhsBMMOuSeShkKhcXPH6EIQnC9LC0xkv8ekCfTR2QRXYLpCRM2hfGo6ri-5IPkgWpkteaiF
O2TpULsY7DoPuB86i3Ev1KhPnStvZy6rl2GUNMd3RdQuULsF_TmqgetnY_y2mQ6TiUwQmrBzt0Izu1bW0MwTfOLT5SDXeEOF6N5D2ru7k6cTw4s_jS0bQ5tO
Fe-vzGRju5g4Mvi3nh7TuGO75xSf-JFQEt2VcLNH-KKBt9k3w_2Eth0q2uBTNXFwkG1oUV4D2tBdLNHUWN_Kkx5i9XpsuXiMqPKx5PpVVQEPELaskUFamr-O
lX_jzF72dTV2HJQvOUTL9Y7NxyMXNRcwF0Jkh1P6xkiIbVnSz8wnU2kjm9sv2lFc9f9cSSkmZYto8QrD1XVamd4tpU6c8qEBjz8Arb4B-wUgjNcfpE3kQpzY
5NuGMrwjxXPE6miHNCnn7NDJtKmSQ0trMwluWm2khw9npno0kmwlXSgOwzvcc6kjOtpOTY8xODycSkrUIwmURXfhBQhtZJe6xhY5_KS4t4XHIAN-asoy0HUq
IORHfi2t0DVVmkX5hlq7xsRCBGFjiBYHEmPNz_7UaXrSx_4UfoxBHrnLTqNZ80JWzjJWvqeUQ0UhC70r454e0DPjS0nxsNrfOicyfQKnrxn9Xi6ctU4MwWaw
Qc7VFVEQqbyZmRHrY2ivEPfsXvl8mdNOmdwkfPQSuZCfhz83N6STxtDJPlEEMjZ17GQvyx5OpDeq4h4qZ08uXtDnntMCN66Yshet7bYKCf-GYqEBUJtlHgAW
nfOZswmKjqApkFEnhxSPvWpIsScnhyIjtZBw79cUqsyiigJcG7GZ3gc-FB4vcl-SgtjOlAkgrFksCl7HVMNTrGhV81JhanPV7d7kAzCDawPZxs_0rTQAhKCI
ITjHy9xMk0WkMEoSuGbmtNMCME1AADeA4r5fhG9oV3H4hN6zITER5hdA5AHLyqAEjd1P_sidSESsBN9R8CgjoRvttCBu2QY5GupX0vuunC04JoAJdolQ1bZW
PbjlXPTzHWaXos7mYpV9AvUBzDJ4QxlMz_aOdnG2xgmwHguvPVbjwdeYpf-jw49fz_FjJFWDMGdm9BgugaCiSZimwFjkKfbwakw2AuB77-UdMu2bgz3wnCqz
XaMkHg8WDhn5Y2Wa9agE5jxbIXNCu4JaRre5ANARCX5dAKIKAX59_mcKvWFpz4salscHQv50H4plt2HD0x4w5gKvN7_JFjw6NAjdIvPbfYf4nR4eJUJwTunZ
RolSkIBSnpaKfj17KJu1di_rrp564Hn3gFrS99bwbaD_qjQsvO9Wurg87BkgcLXCW-Yo79KclRXhow-tMCNWWnR-uasaEh08XcawQcir41KDP2cTIyH5XnKT
Rlx4gKCx1figFnsPKs_aalj0BpUqeGvlTyANSGTO7pWIHP4iMeNVZm-iwuLqb555v-HDSTQnmukh4YSLNiSrhLpYh5DV_4zUVCRPzje6MgoVMJkt92QYg8SM
9N_cD-ru5Swj1HlTbfbgvrQRjEEHLVXCMCmTZpsbsc4f6oPcuzf3UmgH0fccdO75jErLAMYphDoMg4zTCgE5_IUVXe09u6nhhXftMOV4t2aKTLJqh3l6Fuzk
3I_Nrc9Q5w8epTQdxMjuyOFzrnNJMhZr0s6Y9xgG9KLwvyQlRM4trb_HbGsPExT4iW1tKD4dQbhC0xsX-wHpw_A7GO7h04zPVEPNj9R0eQmpisQxeGNkv1RM
YLZdqT2ujgS4hgE59mxjVF1lha4hS2TKD61TLdyskLnqVV40t0dWkIljb9DIg9tBid2rbAg7AxhEFldC1-Ca7KiWedTk-l0H6aO7u9bDEn-icQbdvQezY3gb
eYVKyMHm-iXjsMvgIPe3F7lncUzjOYsi2xT9AbhObc972qzkslbWhIb4QSPTrkJwUb8Sjt2TtRJpmHZZQWons8woj3Nvt-yhvQupJpxpyzZZLhl5gnzFWv6Y
xEyhzTSlFLlJOkxRt4nhGckQE1GuFM0BrwTDuUHp1ktuQ1XjPraY6pTsjhnoiQ9j9FLqJJkkQ4sf2H4jqtLeIcJUbOjv7qdrlQZzxabwlPjDJwurCb7SvRP5
eoTjMemsY2otMKIXLtQsRm76tFqwrhSJPUkW51DrhXtyDHpXQZjl7OyF3ainipwVZBddhUFnxKuEp4-kB5pb4RTzms5Wyja_jCPsL5YFmYbLv4BEYHrlipA7
rjAobKoT6-5rC71FtRJZarBMLed2ogtKmwNzpjqnj6S5MnMNr_rb24HSWUl0dXGi_FJQL6Kl2WiJwv1xJjuON6rVzSwj_Ka2xab7rlzEQJqiHMcHM92BG_jp
mP9224zkwMpEcQW05x4_6goQdrmX2jKkxW9m0VlZmObYFoofNTMo0jU1FVSgNEtpoaudbfLx1Qs1CHhDMIDNu0Bs4c0x2wjMhG9SF_RiPs5cYjAG-tQ9rErL
E5o6YzbynL87t2k1SwxjIjpn3VpLk9YhSp5wSIv6hyx5N9wBkJmNStKkHg_EnLoUYxay5tDrBaQ1Ut-xU3vm7s_NZt5XQA-SpdtxZlmF
}

