sprite $image52 [110x81/16z] {
jPRHbk8W44G34A2hs_t_pzsCWnADrB8Sl8ypwZtGHS7sdxYGSf63adU_VHUV10To043AxhxdSgcQ7W2oVqks2-GTe8Hlk481v0D0zii7bW7f05axFhSBX029
wsIHk5QFpxU1KLzoQr8lGq3snQddeCIrgUS0sQzFFH_VVEedV18NfPu3p9s6cdh4pRtX1VsC904T7q_zORlGiq6IgryaPKPI_z5MU3NxZEluUEf5hhPToXsf
u0Ufd2QLGCgCfhxQgWwc1u-T2luWuQr4ekhuQN1rpitMwHMKtn_7oszwCP0ouwclDbSU0NFFXKCUDfp-QyhBZ7TzNHiikvSgQpPjMTXLQNvurpTRWUf-Nd-p
FJSnmC3BZ7Tzima4Xd2UBUHjMmpZTr7edABT-OFVrLZnBRVLrWQ6Wu6hdNQzcfefv8vgQckHawn8_g5Wv2wAmvUpQdpiksmN0WRkXXqo34n2JKJ7ni1UFyF1
0n6rKam5yXEprwX5Y70Gye2jd05AAG90aKGL-W3oBv17tZRNjekuZzqbd90Le6mVRDcJ1-1oM_hmBWF0tO0CfsG_sQvb9aZ-8B1ZPuencxxSZV5QPe9VFR7f
ZOI9N1pnGvdzomQztPJhtjyqKLorlPLPACfjQhV3TcUauchNlvnaADe55uaDX-jfKs2WlfEgIBMToippHrdTn3kq2gul7BpQ08XQSTocTgje0-pQ3OyNJWmn
XeGQdlo3I20sL5UrzNmVNpXGEz1dgr_8wBcQhJE-xCWBXzWk0sks_lAWciWBXzhgm2uswZEm5mxOrr5T3TCAMH_lj0kdJIGsCZuAgGvkQypfo2PIcofMkYec
VHqcNNhhWQ1zi6nWbRWbM-b3rsMtF-bU5Cjyq1iXrLkBwh1W4uz_j8if2FKjs4IDsuaTr3VhgbZQNd5vO7niO6GJYzykp8-F3mnX-qW4zSriuX_Rjov9XtpZ
gSzk8_Yi160YzPGWu-C3rFgkbde6FmsA9tfW9FLZk3g-4Ooada1E0yF6Ky_7Dxqsalg1yJ6Cf9v3oepPUEh7yM83DfPw3YypRXjFFIypRckf7npOV9dPNEhv
QU0sOwbVUHfi8lNpPMOJgPylCvRwzUCZgLy-FbEI-WNZ4xMcGlRRTmcf25GL9SN_NjTV
}

