sprite $image154 [274x194/16z] {
xDWtKWL140HHRqNrnd3_qwBb95f3v_DmC-hlT73oxUhASVMNKdUiSQuUiCbHCnS2YKN88cGHoB087BuqrEqq0ue_6B873Nj0_82G0u7OWqQp2uHeSo2pn850
70WCUu0zAFQ060HY3uWzw0_ti4dgspWGY3teB_MmoQYVua387Z3iCJC8sQF87f069_jR7Gu4Viz_sMrIlvSzo1xW1uGS2DY3x47VUwAQPDHV57ymimnxpDBi
0Y4Q3WJi0SCUqEm28HeEP1PxmFYa5zUPy6Ht9lMVsGFU-DOYo3yKbm5llyMSIVLZ4B88M0HY4R08n29W4R88M8HGH1kAY4M48dgqIDOj9dbOvDoUrabOvDos
DtvpMEJAbkeeZnHfteH57jYhdwd8lauQ3WL5R38NiKbOXFRg14MWszbse8XDMEHnMonYawc8JL349badDjbMcvorSqR9ZUCm4FqKqDqAxt_RTIoXIWfLD3YU
hOWSloEy04s0L7p6NtY0J-n4lKLYV3Aj4watIKXyGqpPEth0Is3BDOQT6M_Qz8HzIXoLabcSQATQzG9_OGJqPIOdgeoaoiGb4JkqPHedKcsaCE64-WPF5iSi
yubqQQIyFdHC6u03lj2M6Pmeg8oKbzEQQuEs6E343FTiQXWfOhjrJ3jkZWSS_-vHQXefU54csk5LjWOOqqTjPACzd50xrG5iPkF5YTf6CavSEpmRCKgaZ-L4
oXbf9oolZP00I0mK9zARHWYFOgYDUEGARP0uaTus4gtZHoCX005fGqmdwZI2rbMIKv6iH6F_kt7hg4dVXulmxK_l3b2qo5KIE_Ix3x5IqaXE2H4Mt8y7ZNOb
RhHx3spgD1AWwUICQvpzJ-et4YXzCmrjmCtXpihOG3vg8_dMgOrmYzZRVgCalMSaxyIr0yStlEVwf_UC19dMiP_xtntNF-aD8yauWLVxNsiZzX5yj8taMySh
8tvb1GFuQ1X9Egdtlyt8AjocJDH7GaXXWwlzRtaOMIc_HPcebyolphC5B9GSjXrV7_2YTMm87ombOKHgE3bCygHjHXxWmWdkBwIy1gIaTkkOs-A8zOzF8rf_
zRfUtR2KhvBYwoaEJITdNBiJ-I-LYVef_RJZv0oqRZJAP6WV_KwCwyP5mE9sGjRon_Iq3iD8XTyjGDw1hmPxSpl5YIqN68Plc7phc1zVRhGPgV492YGxsBiV
9DWMCDP8aw4B9FXgjivMASiHhLmgC86F_AdZVbHYwtfGOX74De6Fh9D8ao0YDeI0f4NdZ1iWUISURHCMy30IYa1y4qzY4nH8zh7h5B8w60cspi4SFWAaJs8W
cWO8Q7ybO6_W8nydxbU3209kZWOOsVzYd5H2T7WLZSB130sJZvCpL2WvVWBgq_W8yZknDWXtu90kWmT8ZR9EjEFBSdxmmXm--ky9g0twpmSldw9X-kE4shdu
jvIPVEJZnBN3in5pDyC43PEFar32in76lQme0lCKI3vEN3jXv32saVW_V7oLN-NhLPpWP0IdNOV4H0KIa2_Y18UkqMuf81qtt_dpv1-AGKaynSX1YM6c-WWZ
ajgFeZ03ATecvFnDB2Ro4KgqhecJs6AhEUuwnkLQoOWD4v3gUW2a3aeMu5h9Q0LIatUY7TZYSF1wV1tVH_wUWDhWTi56Uzj8kJ6PCa6rwnXh9X2IQvrwrm7V
CrA2WPqmOsG27_bb1zfvsmXAnPWHoxzaf0m4se-Yr9FtahK4CpWndhO_OyqaFl9n4hiDXUKFZB04qpWv_hfOlv7IPl29hTz86HeadFGPASF3XfD-8sK6lXfn
qckaJ0ARJl96IZ2vaxIH4ipk1EuP8sKwZ5rKpr8pykT6M6Q5UNxw-3Zv6I0V9TS-FaPOvaTyeAIHCZ_nAggCaVBFG2MwH-MV0snI_aK-Hce-Hce-CNBjHFfK
o85DGEtZWtvFo7y
}

