sprite $image94 [236x172/16z] {
vC-r0G81002nCZZxRqk3DBYzN3R8VW2mJm3eJD6PGgYApXGwKuIgw4oXCuNE5A4gEbFeJA4pHQYApXGwKuIgw4oXCuNE5A4gEbFeJ25KfJE5pXGwKmXLwKoX
CuNE5A4gEbCOpNJvLGo_TVkw-YQ3PndwoW3JmQuCExrSrviFhK_N0RUUksu-zipLe5CEnDg9WkAi4WLWeOggub_V_srlz2J1uqR3trpFB1h9I3uWAFJ06luV
4rqhiauwQZNDAINHLYmf9TiBvLPO7D5hKLORiAxJ-h1LBaTsaALsa8wocrqlHtJGwkkbVIkeMcuektNo7HpgSiEwtnvpoIWUi4AxNbgIVB22asl45I0uRDRR
amZ32rTagb5l_-G7rfIDjMkbw0onzzPzH09oiueUrh9tzjuGCEv3eMT5CwQoGkjlhHXvdwpIhCLhDRAMuwJpLFsnTKjImYwGiXLrVhOcM2EY4TcAKuRw5P7V
r0A5k1kU65x2t4bQiWBGp8tONZGCTDbFVRnVMuLy3R1Ua-stjDH_nTDEmwLIn9wic5mbeQ_OYXuK5Exa94_py54XNmCd5zBEIzagRwreORP6w_WIZzR8P-7r
g9n76eDMlebcfNqh9nMoUhZcBL8y737TOXW0Hs5S2oDAlaQz-cThVbcpp6eX7RIYH9lr9gZNHD2sXICeEmhZEFIELTvKBJQhzGahYffrBfDMdfE7fUFMR56_
PDMWEiUaurQnYEzOKuajJXcG3bl58txFwWFMR75GAHDKDxr5x7pcdhUa-pdfgExHQiMetGgzSt4gj4ThsIjiru3PczkuIJbZKgGYRUh4IqP32DMnLHBA5PHy
_q5iUI-4L_SZ8MkhaA_Xn2f91xJkurOUGcnDhT-n142mccr7mgV-rCfjFAZrmHGUGcmzS5uBsjzmjYLuRWzH5NGyLB-r7QpTx_vzAJ8lPQj2-c6j7X7G7KiO
i8wrUg05yaqU8MY8lfL6qo3M9s9esFvQdQobRRxOqI3ukwrVkzP2RJoazRaSrNNMwb2-i9Qp8NZzshUEG5dhqzR-VjFno5OxEnsFUTZgencMZkyZsZafxRe4
Je9EqRz7DwVkt3GVI1TPyUKAdoRXdd6qawqLfl18hT0NM97mgHJjMmCzUtQLfBRCzTZiYCJzkZvRVBQQJ5DhdT1gkgI-rQE6NHD77ORD8ogiDN0TTEfhAxvx
pQuc_gnRObXwwLgHG9p3XI-EsCerprcZ_ldddtKGQnYNVUjysChIIUicXNL0QziG-eeLROpC3Dzc_Q6sf4jBsg9k2J4NFD4bLiiFDOjxGjGr8Hqfh4X4zpPz
Z3plPUO5ri8rytQ1dBFzs-5BrdxNuWrdhBB54LFPejx2XzTY8okryQ2LfR1sjHX2SrR3pCdBsTFE4pfs_TaAo9GLmvUj7IqkSjXAEn7jNLHEhA9mjvPRmQEL
f8DMIDdQnuREMMdcB5YEOtMEmsPjpSdMA6dQMW4aQryR4INDMR4DTjxmuMxjsxwaUslM5zO8ouDMxbIszhKHg7FKgXPLoTf-V6Lg-xRHiRzOxQKrmcNG2cd7
sj7AeBNYEbzPKTWchYkflB0wj3fchKHaQn_hZosSd_Vta3jh8pOZBjjG2EkHLrPKpJSHrnndpHqfh1qjSJLDMWDxVmMzCc0bRSUAuTkn3cXHPuujzykJGDvQ
CUWG7xJob44LqZL0EcLbBTVv_jidMpLlGKcKlE5IBd4K2mhtMDvYR7rr4tNMCtDMndATFxN6tUYYdovJ8TAEsCetqNjhWDInZckZOvqFMpcVQ_wpRntN-XUi
dPgZmZDlVR_Q-sojyLz3rdxDaFQjSrtxrlgRYQ6DXtah9xvkdPUoTLxxVMi5PDewZwt_PskGPiOwh_tZhzzCz8Vl4YjhvyUm-zbhLYVwbQKhh7tjm0vprbAA
q7_kdjpWdhUkn-hb8TddWawTjwxN9W0fPO6qQrslZV9CbGN3jszThurQYzn3aqQDzLAshiTAAiSYhcZU8cgnlqzEjd3uidMzjc071ejONbKOjiUNIs5Thytd
tLdQdiaDgkc2fB9m-2B__ZTiZ4-_AOkMQqHuMYxhEXNKVu5TsxMXbswonq8fgAkrQkwrXlQajGPENZ5y8LsijRGvpAFMAF8EcZGWtKxMfL9a3HQyNLi3Cn57
YjTT2hYj6hvBkzQQB9VZqyPDLV8rgiLZd-5CKjClaAxNqgZDwl1I8iAvkvCj6BxBjL4zyusPjNZSnQr8lb0qAh_90YdosrXeEIcbB29f2nT0McFHy5tVjJK4
Z7vIUPJM1TArscfzBZvuQYo_KTThA-QVTv5oWyQgsNSzbhbOp45CqvL59UXYwNgjHxmef3N4wk6xNilUKzoKS7vDYgnR4GIoSZtpxQxbV5lwVMrTBbslNT-f
aFwlMZgeGXW8e1XutVt-1ICYG3iIvYKFQi_VzpNItYnLj5sgQFk-hz6UFqYDj3TB5Ut9qXTgp_dLlaRQcwMAjaiLRT_tzThpHQcHzcOfeyrII1kfb3P9CMoH
QjeWvRI1occ3bCC6AQSDL4uRf1msI3bja7BQGEMqGQfX5wIQTe6gQHUacdP1gc4Nf9fsWQff5wGQTa6gQHUecdP1gcaNf1fsGQff5wYQTa6gQHUa6dP1gcaN
g9fsGQff5wGQTe6gQHUacdQFI3y
}

