sprite $image311 [232x334/16z] {
tDK7gGLH40L1CZV1-bVxuqljOAboq726kUvh_hfuyy6lz4DdoPabLnPSMN9boPabLnPSMN9coPK5LvPSMN9coPK5LvQSMN9boPK5LvQSMN9bmPKbLvQSMN9b
mPKbPvPSMN9bmPKbPvPSMN9bmPabLvPSMN1boPabLnPSMMnbBJMpzZ4hQvsJJhHodtIoa_t3LpxmX_bW7-QRFTatTxBbLfQKsSCizp3BdMovlwJSoPOxsN8h
o_qbvHvckPCjzvUKEzbo9rjkPRc7MUvXbZlPSYTRxcJBhIptCCizp78dM-vaIwziPnc7MUvXbZlPSdz9kPCjSxBLphtOodRkjQJ3hFTazuy57MPz7EQwL-at
D_QXAwiH166OMN9tINx_ftKuNbHIZLEReO51uQQJFhl-PHO3sZhvbSqvtYucoulAHqaTZI-YPBnTAG5taHgbFOH99wKotjU7gKvt7I_rxvwiElqXcHfmhVCH
cPhZQYTHccaFIZhlpzI11EVTcHgGvxpj7cEE9EUjcLAPwNJF7Qy1wSxyJ0r8T-PdQevyPtwc3gGxyyThmAtEdAEWEMvmfcVgmDtEXAEW0VSuypAbCj-PEbvp
tEnCkSSuSACpArF3JTSlPjHSdQavxhhiEyECJ1ttNUwKNfkfuyxh-wFQYKoV7IQTFz9hCpN74vpkrsRgm2ESqV76f0OynwdI-7WVhAJpNAP6QJpCV6VxUum3
JtIUlyUOJFPnplQPckEHJdZJUuodI_wh4sYMQVvazy_otvr0cqpJbJuDGynfvWsEWidAfGmXfn_REv6fURPpAyCGSRhnH_s_cHgGxDp7OGWvJSytyKpDGMTQ
c14dePI6C-LBMU9aeqxjB3vU8Dqv3M5dBPNnFj5PuauThsRwHASDSUVvJFETQzZP8jDyvnHsjiWqtrdYplEPvZjzY3WZKlxs2SujxcoGQRvpEkjKgOxt9gVl
akS9P-0Ua-pqfOoIPpEdMo3JovmyoZhgF4lO6Rl7MARJnX_B2l2Q__HDGMSyqpId7vOFmElpyrTb2JlZcUOu5xxWM9NdTC8PkCTSxzpBm6kkybmFvnHnnZEz
rAbdzQ5KUThX7AFEw57mMkSFWzUcUUAaCtuKREzSTpghTHv_3ZbFPthWp9evzyzWTEfmzs-UKUVvJ07uzsyRtKiA3gSCbt_lPvtnUmpy1umMJb--8wLJXZiU
_tkZplEPxllk09sddrUkbPDdlqCTTfxFb0zm6zrBJ9m7ddbkbpbLQlmxe95pv6jExVm0_6k_o4bfvNGqSp95SHusvdcrqyqkS-vSACZW6qs-nvwkT59waNDX
dlm33_E5JwYtQvsKDdTgddHom0Qid722qzrQEpLFEfstqECHM46MqwszqvWdG2T63lURvvpdT6_ivDrp5-V6in_pVAsJZsKXJY-7S_gI_LNEJNx2BsTK9oOM
oXF3MvpxHnvN6c7YtEN0CB_7wHDVSJJFoeaYRz7UulIbS81LdhLpgG-0_ClfiSwjo7ijpLEThWTwVa3Py4WdVsePhjDLEJ5AdiS7bCNnI2UVsEbmD-PPEpV9
y_i1amCFTgwIckPPExrKUM8TT-3HJXskvbaxUGlbHpXmjpC-NCrJdRo5yYEUxznaX9fdxGI7kp_86H_kJBSujMcynucf6kv7TgnEPvxlSUfmoPXhf_odsTxY
rE4IJeKu-H6ZusudVniUBbN-jquK7lBUuzJXZffdxPpA0hpDgSEjygoTxdYTKuUxIvxYvFKkfmwNUVRbrE4opwwSEbpcsPbJXslCipid2eUxIfxoMEIrJXtk
zxS5wbmSRtRgS8i-kUDZaVSxKGXbddIM7UZ2EQdJ0LuETEBSX5aWLoTE7UxKgtEIF3jrwd2zLoUAvDchSvOyUtMQvDcbKuVh7JjdcMsdJWxtiwDd9mhVVVNg
v71dH-zEuoFshfsOTk01pj_Qku_SYc4O2CFho09u_zEcEcyMnhmoQNzaAbsx3oP1JPeO_m-ZdUriPplRsSvsjhETxMndEzlPpdQsivtjR6SxszdEThQpdUri
PplRMQTmLft2MSOvbt9MMUVSnW9EAPrpqpzQp9mafdVgNqh-SsTftVpNV7odLpgdf7gaUATNUgUWWHJbBEFqqiJ9KSgPIxsJfVJpCsXJEN5CxnmxRKXATtgb
hrlH9EKwlT8xZpJThiXrUgLt7cbgKxYpRZYzrBGfqbaLEBTXf5HdLUGyqkGcEYjnpgnuvMGfR-ViuQGePrNg7A8PASTP5JklqUHcE2jpMjhHFG3EgjHvcwOl
hHEazCuRD2-L4w3CShO_2XedY-cTdkRRL4wSqkVie4tb12ZZd7rxniW9O0OvszFqvSKfCK2PvsnVo--wVPUYzCwZvVusdTldBaUPvsnVo_j7EI5CxxoVThm8
TSg9KUOvsnUld0nbdhFzKN3JNA4myvpjfPgV06MOi--evGjpuoZpdEsVyAwK4w3CSxOltbVblWjYvZdRdvTqCi8eyvpjZuBQ8oczCp_bwZfNYZBFsRwMTPqh
WFbZENi4rxccIaBErcSGfNUElyxPzVDEJmjoDa29ojcvCfVcEVj9EPkarEBaxFhP1SZPKlw1DCtPH6LUl3vd4vbUckTigj93yvoTA-bjEkVOTwbAByroDfYf
5OTHRR6L7df_pjRyp9NyDjNyp9dyDjNyn2izDCZPWP9Ql47Ebf8lpNEsc6HfaBC39RrDjPag-SLhla-TAVd5g-zJyvdvKN1eVkPAVflEAMUkvBUfvcV014jz
pWwKOAZFsO6IBBKvErNofLfwdY6JtwOVeqNEKCblqw5pGg2aIytFiyLSHMhE2LAk9PLJoXMXSagvedHUe6Ak9vMp5bndSTRgJgsJE2KLSsseb6jBfLnRYcQ-
}

