sprite $image284 [178x135/16z] {
pTc7oXin44LX-aep0h__qwOgBBROQmxCX7lJ-vVLSVrV_Pk_zp8Oy0Ao1HYOVRnx_jvZ_bvWTWFxcwUQfLVF71ovqjlyOSlrUo7CNjvOUsbgdaSGzopJ45wH
XbV0mEmIy1x8sIC8aBD1420DWo106WPUPhO96EHi4R11pYW8lvmd20AaOH24WHa4OP0py3hb30FcQHW4ZDFm2oBdkAu9pANtQ3pSwz-coBad28uTr_iIv5ph
vTYzaJYD_e0Vi28DO2v_ZhQnUa5pva7m3lG6oBagYCoCUm0BSYxpvjjH3cJbEVE0zTC28K8v0p88-E3257WQF8W7hzuOOt_pUz_IK6OU1FBg-ACWPnX4JBRy
DC-2d4aG9mbVvXmbEMilly3wRl51h9w79WwOW--jOm5ZZhLmm3m9_M0vmHt6dpyFWW1WGiwXdcESHyrVPAp9fvz2XNWUT_vH5eI-nFjX0gHyfZ7NOn1x_4cx
uDu7YoxoRHv7mETHQo-vn1ynWf9tpcz1FFytyOkCbE3lvFMuL07VmoyoGXTn3sQnTC3tH118V9M9yyjHWxTD-g-n3c8F154iva5iyVnSW4CJvFamw3t7ByCK
vE_W006JGqwInVagMZpi9GrOlNBd7rZc2nR4uniZxFZktywNF8XJ_6ZEUdA08AIOfb43va5iiJINaeDvjPZc70LW4l0fnZbpSjA0jPZddCmS80WWPcaay2O8
0eYvEKgyEmWkvZblC-yXHH1KpE-TC-9P6xbum5pC7xWp8quiU4ZcOfw6_hlOYmmkXcdmyI2uc9kvDrU16EGC1W86ugASOS1yBw75QV20kVTrYwcv8WZkLMAU
StyGKinpxW-2Y7dEzLuW1cc0W24OYRcvFc0XvcdCR0y2Y47E90ZkvMAUHiww8BYOtzDbPH1SpDEeya8nDnS7pCKyv-fxD4xcETS6mSqyZU8W-itbGTIdqUxj
DzS7N6-k3hZV754VH7yQvK7qctky_UQe3Q8_vrel9_DLU_lDrTv-SpMutrpjxITNU_lDrTv-CmGRaA7Nm8oy5cO0DZ43hmaPU4tCm6jY1c0JC_2Qa87Nn0p0
9cRWDI43huaPU4tC06nY1buJCl2Qc07On0oy9cRWDI43huaPW4tCm6jY1buJCl2QcFyB-2S
}

