sprite $image294 [154x167/16z] {
xDH7SkHG30JH6LcYWEY-_sdbfTorDxdWEq56WVpRCzG-sTxQKaTHHk4sLQwwkem8i-3BGdnP47R1rmLV5tnTEBxBsBRKZMrqWq7NXUM8CDTiJtL7ki6miOLX
qOL15mPT69nXf26biJZUCK1tIzZ2G5gqPQL3c8wyh9JKPIKbBFENfQIk7hPQhLQhQCFCPLBfakhnbgMKCjFQih4USoRMoQQjayr4EPbqj9vl4KucJUlvrROm
n7PBn1Q6o6w9ZYmCRGj3syBGqOMH9Wep_Q4XpFMnPQ2wQCzUiLqI7Tib4S5WXjbwZjAnTVLjsp87gvVShkszlVlSbLG7WW1ya-tkBdJy_azxDw5PL0k5mp3C
Xlfz1dsgDa447NBfU4g5UhjdtQF-A4l9G0lkXlsnxifITjePNiZIifHoNBMd1iXr9AlxidMvRN5nCOjXDLZsYFEYdAikQ8Wg-29p7CdMaR8kBb1Hu5zblYlZ
aJ8lsat0qfbOPN4auv6o3t4iZD0c3Ljb3Y6pbl8vorJW3rb8sSiJ3zcM1hjT5hwHRUU9SgyClf7nFQjyemnECZggtIQ3aunfi7ja26SPqvOeDyWGJh8DZPUR
tG5ZMV0VscjbS3-KSL3UHyO9Vm_PlGd-ZF8TPNLMzaVc-2CJk-QRow8IxMrajRxLBX0_dUp-SShFFV0-oup7-LlA07GiipLnzJZnBGsLyHUcdRAEEmJOf6EO
e-Cylui1S7g7kSRwIiDO5XM2ZOxp-J0SoKACq_546Q9hcBgqd0p3DAxCKq57PNeVo7itR4TdML9A1baPvR_ZqkY6xPGCAQKz6y7QIaFQtTfOPP7ME0w7oG6N
nZBUMZTi7UQQxBl3jDfUMgH7yjOs0WCzRL2LdPyyWxRso83Cw6b3S6L1A5KQt-tE0KdJbN4CN9ccWMHaypuRRufj0gPBixtDHJkDzoME1SjqQIpZP4CJxNnB
11CoffLqa6o1CnljIZl9BcHYdYpZ58UmBTiWxsz1mVGySzB95ih5i-GOmyxdIJAPEB_EZQI7oRBpUIATfomY4gOhqpGqLNOM73LFC9KFcYScAzEm8c5wgSMv
30CmgingFmtb36PZCAvie3MVg4p3Ci6wQSWpbONuAS7wQOiFLgP_cWasH8EbWxXGqUyu11kY7Uy9MLMcTnyZs31jWVLM5acaZC7sd-71igwC9ocI2JP8mx86
KLhFIyWNm8X6RvhuTrnM--H5CAO5jdN4EjQO6cNKyHZNjjLviKKaoWaCbJ9JMryYgxsopiPdR9u5R3esOuCdZj6DzPduX8rtXKo5tMihDCdwp0JPqEv2kENj
9EkJuovmYlKrbgcmAsqUfDFl15iswPgtiIu0jBu9N2-CxoUskUtV2FXGwaiItfceBynSM_TNzr5lJ5nLrIS
}

