sprite $image144 [187x249/16z] {
xTZNSkj838JX3HC1hF3-RxjoryYKiwb3KDDLyojSVnVDw87fDN72T4G9fyIR8aAyVeWLZaZXI4ZbI4ZXY01EXZT5X7ZzTK8AHwnmH2f7GWf7Ky0fyQQ83o_w
nndVLhPOuOXKZluZXQD62aUdmIdn5qM4U0sD5OvOuOXKZeGKZYunDrfigz7p2u0puKsLqwvFZLIEX1IEBgHmn2f7h72q2yvf5qM4U9qrKZXYXIDMEMA58r8u
4dzJKwRyBcMB58vOuUWYUdeheuMRySgD4uuuuOWJZdZbnWb7d734ApTEEEA48quuufKR9nnnmX6lt3ZXY1EE2E1iT3k6BZ87V3-zrTgdWE-dbrHgEn5lHz9J
lk9b1lX--XLVWO-77qn79NxoPZ7q-DLO43ryDMQHTE2xnC0ZwP6JjrXwtEJDWkbHapSBfaUjnYoKNZ_17sItOBf8-M3l0V08kchFnzCDXTDLMpwORgVHLUgH
T4F1z3peghqSHJSxcNu_-Hu03wLlg-a1ya0waZBe0V1W-fXy3u37qt6Yx27oUBhMX-Xcf7GpKhePAzrOwMQaT3DIkXahtLZfPfJqJRxeYxxeYxxeYxxebPSE
9oazLQ6artArvyP8pxa0toa7aqk-uelmqVEL3NmLDdejmDzDlh3G2znOpPXyINB3pKnFQRYtoT_JpQQcvphSO_8jlTBHp7Jf1Ml77tf3jvdf8Ysdl4t-ZguG
paoNNlCs-Nlw84vB1xviat-bto4dfWC_JfGR_OuvCtsR_4SwceoUDpecdz8NT3Gh7RMlwCCwCRr_IHzQJlhmJaJlE-Ww5JsbsdzFrsdeuqpU6EdZJ5uw7JrB
ArTynchOwDfhngrwhhleDW4T-35vEhfg7wifdOwkqlB0qz1JgasHZCaJqRUNThtaN0eFFTUKoi0B9bzfwDhBzj8Ea-UXgxvucmvy9QB3-sRoD7GaPNjFtPde
0EVRv8MDFYRFISVaIwUaZybNHlgOF2CTDLwwvkFfYxxeYxxeYxxeYxxeYxxeYxxeYxxeYxxeYrucfY_weY_weY_weYi1NHRzuFmQ9Tr7V7H_xS95zpSHqVr3
97J_D0AwVrKCFLwEfgRx3yciTF6VcvFklsi-kl-woUY-gudelhjPwFv0CWFT7oo67Wz72dgI07ga75r0hm7qM3ZIbb8gSZRTZoYzbDkvT3-cX78FeCV2OKT5
pg4xEXXV9PmEU0G-jm1wi7nRJO-aEuh3InJT0_iNzbobfm2wnvP6nzCzl22wdr80tK_hQBhxgVPy6DrFxgzo4DsVqWP-dExFwgPxa0xu1FZzT7zoDeJxwVxy
P1ZtqNsEWDn5TpGL_dTqdweRz1TqyTcIGVs9xZDsisxqC7ZykIPWA-6J7tGU-C1_GNSqFruH4nnTz1ON7Ec8JhxXwU18RdGd37JrkFu7
}

