sprite $image231 [236x172/16z] {
vCyt0G0m402XcUdzkusBjCC1Sm1C0a1dYiuKGbLqfj2P8bH5PmgTANIc25NHcK9d2fqfGbLqfj2P8bH5PmgTANIc25NHcK9d2g4gdIbqfj2PGgXAPmgTANIc
MDIR2vRZE0X5qL_0s_zsvrFJrZY7o8avLAVhRi2v1YGaan-lEdejETD_f9nh7VEFietoh9cUKje8jFsyQIzqHQeRtP-dMXEz9FKFozxCqVmqF9NUf7xGbkzG
w0iJdKu6Lsm_RsfZnm-CHBSe_9GFgreZ-sDdeTkCGDbuqvbfqTK4-owTustZqvUg0dpG4r6aB7zSjTCYCx32EZAv6R6oyOLA4u2OO7j8lEFFIDzsDcsqS55v
ouTCETD1KK2VxZE9FF057r0zAQK9g3pRPmO0xG7BKxGitsBGGTqMwi0NMkacXIy9CFMfJa0t-qnNOHO5ECUiJelVgJhfGB22ElFp-0Y0wIpOU5k-IrggqCik
loxR5klAtsrggbBCHhCvkoYWXTubypluJBt5Ej_f7l9a_bMsoR711jgoWxnMO349V9t8mzSbxd6O-XOcLHFf3Ur8P5Hw0-LmMVPH3m6OI6z9ux2LGg_eoZS8
DDqlmYesh7lANFjFeaiI-1xVfhh4il918SDbsNQwGfHl4cngZwnD-E1UdwlNRUC4toVKr9RhC95-JLvbosMhAkmXKDMwJkiQKBO2OISEqu2ukiks0C9kh6cK
Qx_hQjj6eGVIjAf-MmwWsqQE5dVALXIPJdGiLJ-XgZnDWowPxbBCUQ4ge1o0DVMZzk0rw3wvPB8NhZ6o78MiWZNwRiPAtn24evZcfaGdkLaNhe6eS12Qrkdb
09NS506K0n6eHjdAYk9S-iZa8ytWe0e0rJ1R5BCKmodReqqLXwig1o1gBtBXIEErpuIXm78D2YrM5hVb3mnw6xlFp5xh24ZVvHfbAwZs6kp6JQ7zi5VC7RZB
TBa6sYggJMC5Pd8Lgdbp3XJ6DLuspVERdUKzq-SVzbg0wN9rsSvQJgDBTYrg3u-KbkYIEW6exCSj_EcxNBssVHrEpcYZHPuFjf2-Yswg4ylKZbkeSvynhbxR
RAh9Vj8evj4yMibqejJE-4AVZLiaR_UlCAX3rcWrKsABkddJPeqKjWCa_kvV08kgr_QykgQndz4gW_z7R6RXyN7zPDgYJ9UhqrQ1JeiyAkr8RV8Zik07Pai1
tRzYv-gqlRxGjRg3Np5xYUZ-5JlKBNjt3Y2L2z_PQw88Ky4ULQUjRmuWbTh6MNcEKSqOV9u0DCpKklfjszPiGYfjo6bxKmnteRfS5tp5zHn0nnThmNc7Ek4r
5S3XwYXRgrC1w75A7lKDt_Ahgv1mK-lgjxLp08K1VMWXTFQQjvfj7DsJprJXS7NlFwZsjjF-5ENPUoy7jVV1R9gdq49TQ8YidGFeOb-zuW8L2JYEErpT-qzw
zUyB4NrqLbsMqQRMDTQscoFTDwE8TFMtZVMJfXQDbBLp08s_4m7YNVrjuz_Lrajke40G1S4P_zs5nFrlwwNNLgZL92SWbAy4a1Q-Cs25itqvE5-tpdp_uMo_
ji_NhVxRk3u-FZwlQwlKhQxzVPjrOBvWXRQp7Y1rAp1qlc0jQTS5ppqbxH3rlYUZNHTILRiwqensL7f0YrAd-ja6vbj8wzACTbGQqNhKRTXvehIHTerACzh1
g805xQdvDjAwDACTbGQq81Mgd-t1-JRIhb5fHilIW7R3V0-VxNvf9EseDACTZPhHBfK-2JlRfOsqezA8rgC-53jhYxIHTerACzhHg1djAaZzR4DIJ-k7sj4g
DQKbQGmhqfeMg3ajI7DQaEQm8CrfWPhJWZI71MbE2zAS5gWvBKXpM93cj43DQK6Qqu8qXmLfG0lKjXQaEIn8SrgWvhGWpMb1ciE2DAS5QauBqfmMf3aiI7DQ
eEQq8CrfGPh30ZMd1MbEUqRw0m
}

