sprite $image350 [225x222/16z] {
tDg9KYD930HG3aDtPHhc_xzs3b34ECCoDRaIs-skk3PyxF12MQrImO-6XJ76-77SDM8TbtTa8Jvf4EBnU3mJyPy7IsVm_YmE8HwA5mj1N0_46pXVB1vdAxvB
-M8TAASGdfPGY4T9fsx2MASxvL7AfpnTECRcqtHgtyUzfdF2uxss3FxJviFTjeoRwRpYAV4OhI7HIqxlh3NCUKhSE-yq0Spt9kvYyvdbuv1rYCsNlxthhGYZ
DTpKorQyYysdWBcUGZnMEa4XO-_fz7cnk3VYMcWDcNvdENslTFPSNyzfV-S3RXIXl3UnbtCPf0vIds9ZN7Soqn83b9D9eJ7gsaTh268rdQhVCATf_3W6AhpR
0__xHgtXwsCpQhmDMqOvVlEzIQChRixpPoRayXtTve8zUiLZm_8f3mCqqcdezv9E2f5eR8px68ekYVN6g0lRtkRAwwZoye5_tSdGHmnCMeEb_zwMGKX2tNpb
RpjxyxjR1W3e3-h6R-S3Fp7-4WidaxgUttD09G5S4BtRNEJwwdL0Bv1IHAi0ni3lHGETG26Q1K1yghynllS22I4QZH5Zi6jlwke5obQq2X0vRNmoGOXjGCqf
vZmXJkfZw77n0bk1IWID0ep6njZTCgX2825QUxFEqzURW3cny1DMBlhrBJG1yvnQl04swJNvQojGMuOLFmpWUmwjdK3DgLS0FTfqyEf4vak5zO6_Vj6F_mmy
drEY7crclDw1N_L8Y1um9-AIo4a1lBvV6_Xze12dNN7UsViRenJH1gfGrvc4_6CRDKOAiGzuFii1rUFLB_hzWTy7KXk_KG3PkQsrRmPgop3Y9rsnTs_s0gM8
LW4OZlxVW9yQWK9q6oCQZ-owVE101jIkw1U06621Lnxu6S8pNnzVaG3pqnkjWR_vejyYacG07nwUbXoOv1Gqdlrzlm7tMqP0Fe2_r_D8WJdnVx_eltuTSs0W
_W0_rWkkWA_81obiS9zXTSK0lhrzCXv2U0MKw8gG_i3VVz4_vi2tFn2yV09FLq29hkRKAG04qNbeNQV0poAEKmg4H5TQXbS08XpjZH5pu1l_hFNf9l0XkeZa
r2g044iy6erVWUJhOmACzRJM1twEWTudaro3pu74cW5ZdSQiAyuBW34wB_fbu9y3TIdmUYj2Y7sjmH_uXUW2kJvU21-NgoAgX5jUzCC7yg97nbOSjuWR7Dkk
Y3Om8ATBuWav4TxJh_kYFoL-CEP0SZnVvlJ6tPjJ0EcAhRSvI0xRSo2vF2P0wOfc0OJO-XlmLO0XcGA9bmIOdjvG6FYRB_gPhnlkSSg1X131EKy7_lwB_k43
up2dmFEiA-O5KAB1CmT-7qYyFWhmxqUI8le5AFBqHHf0sOgNmFXCGjpeeb-xeWcCDLuaeXT2W4BqUNMzlcS1TMb4no03-rTe5404VNgMWGpYM9OHGB8myBVk
JGIWLC7ur5YMPKK02HWyO-0tzF6rdeW6S1cNRSCjG12xqXcl0qLWV4Y0GNJ-RbQ8DYzFPm3H4D6p0A-9e3Fm5_zmKRz60YW1upDh0YI4s3CrpFNQ4Xd4ubDK
WMbEZGBKz1eNKghe0oEY0io9DEyp2fjFWOdGUufU0O4yfuM1tsWD6L28jOY6I8bsttS7Vk4bG2NwZLw0O_aiLv9J9tv1TDEP0uNeD_ep5RWaHEzaeWE_mSk1
8hGZIl8AkApZTaxX3lnEQyY1GdGZcW63Y9Hex2vYldLpdWALQ4Oq1twTKx2vDSo0AeHt5as1qvnsJWq6C8ZcMJG11b61cjEsgS431j4vYwR0M39qQawjlWzw
wLHWIZGQlGCCeZarG3uZF0kemYzyMaKFIC2yw8-NcARJ1sfEvyi6AX5q1dwT6doWhlC_4bsWvfHJtYLHqba4oiHV1sBM5UUj0VgDEf00q0JyiYkoq1egGDcA
HU2ayHSEBYNWLqJ00KvFRowl3fnC_FWm6S09qRXGwWNcmlY9LmzuCwUbgQ4Ep8XOGcW0WvWKiPJEEZ0bXcIumCWfXLYQ6kh0Z0ZWWxLum2YY7WIrPHGsNmse
Gc007mOB62l-jnEYbyuwK8bOFuMZ0wWv1Gky2b29wxB-WQrDG2LQwQm3LGXvZlO1YQJncxmwa5HXFQB8YOLq5e1An1gDi034v8vu0w1MaJKWajDRZLS7gh0A
J4zlbNJMWKgi0pDYWLS6Ah4Ep0-evus1Igm3TP3Q7gZ2Eb1osWja3HX4h0MW4D4AbBytT85A76MW_Xt3hsxiuq1G68Y2w5MqeVAFTlrENyOZKEjN13n0TXQG
Iy0Icjin0nZJWN0LM4EnAH0k0OlO5yXv1LX4zwv0k08ieVK5mbLWsp5OoGD17eYf0q4U2F90GXq8qi0YXZy0F1O1CNUV0FIsGD065b4MM4Hb8AOE17aWo0FX
Ay2n8v2X3WHv8CW3EUS1HqiWo0DX7j1x0a4UYAa3GHu8ya3O0fXSACI_820F17aWvsIWTGE2F13aWI0FnDI180-4_y135SXPZwm91F-R3IdW-yJG0XRna0LY
zUHhWPa9t4YqiHOOLFSDnGXV10IudtYuhm1c97TdHNiU63pHAc06JxK6o9Cz3ipWsU91OF6MVCGn0TYGHn7jRc2mAYlCPu4FtMBFtxtT1CnaTLx4wS2C0DeG
fmCpw96NQHAmlbuleeqHFWUO2T2Gw1E0vMj8d0IaOvE0cK7NPW0pZSPT1mQzEwy0CvB-bV3Bm03OXsZZYq20pOXV0IORLGUfJmEfzlg8nsU0wS2snF4XCDap
-qzy5vZ1jjMIyT_gKZmeufj0G8eezVbgA5PAlCghuYLA5R2srQ17B21wMG43pLw0W2nn4kyd
}

