sprite $image97 [147x113/16z] {
pPQ9RYCv34HvIAAeTlR__tOF4pjskY0W3S9XlvdSrqDNKHGbQTReLiWmio5q6xXRq9dkGRCNjqXFRTexUeCIdPX3oak4T2ul4TAgCfksOmujpmmPKfjPVQNK
VaOh6_pQIc69wjDhTfNsMIaTqwwZzPdzsevXoAowKcevsYUsHuvfMbuYP4Z1u2SgbHZy9EttjaTYn-HAL5yfjS_GkMpmzxJopF8x1WU_FZsrQP-dSTdWxz54
YUegXIKgg5HwyFEq-imGpLuRVs_7g5NIEL-YprVAgutmsZBxCA2sKbOrRliTOqGaTv3IRqf4MfSUxfW9PrFvWM33uv79RIhb_kN48JNkKIaVnoHYlb6bJEIf
mtUfr7GBcv2wGQNcEfvAB4JrwONGSKmc9b6Mz_IgfFpu3rDJOZv9zHgXmFrhCXEpAdDTfIApmCV3YJYagAnI8HHOwq94BF52DGU27s_O7mEcuFShvUj09P1A
L2gHMJ3bZr98gT9lLchwSSPU5TgarpvR8iHE8edqyfa5XXuegEEZGgXK9EN71WEFHAMoGe6124kYKhdCWWaFHxnB8hsaK2YT_hQiDU9znlJ6HpCBf0czmynp
6ILsJE8H1KJQJWzAnjXq7YkL5qAUSIXzb-B4WP39BA3_mFG8tnU60o4jj5SAATv9XMztXKhbCzihOQMWs_rmVglK-83GIGagzNBI8KB4xapCKAbiPdkbVQLa
_JMVxojJyuOx9l-8K6cNNaYnFvOzkZ0HwLeAEoObXD29fWpfjTxMrn4pPw64wUKp2qpenAPIStMAsLCX8drLges44E1AmAPI_BrURWoLocVsM9q0gDH6obSZ
g5IwHCO4xDCJUY5CCXlic6nc4qk4KW5AiOJlw6_fvOGUgn40u8uvl-_UNkcPPpBhz1DmnvobnXglVJFSvqTAjAyKBcCcxQyl3FUGoWy-yeCTWvsdxa_crKUq
Az7rIgcS1TL2whZ4O08kLoeynkedgQRFx5Pcy5EL6ckr_olrP3oEYqeFA56kKZfN-rQfCR_yajBgb0DtJDTlKSfeVLrGCgOSU6tvzdwa1qgPpFAd53Ce9RT7
_fGI_h7Ie0tvIfqFWL2wEFXv66_2GOT38BazyfKQ1eV0bMiZajynOgs3KcBmqpi63e5yYVBfCIZb1pz_88HIRl3pwRt3C77P4kKh1Kh9mSzN2eBBRFnyfVPA
Wob18ZrKoWz-ViUWqiCRrH2LQeFxykMhgaHOALy-_Lt9c8hHkMBjmhMna1PAi3qguH5ACFYLYFc2mQ-cpNHc_m
}

