sprite $image161 [238x184/16z] {
vDW7ZiCm34HHT7DeWBh_RHUpZQXR4uNEVpVu62cnlRQGrK98lLi0QWbgjGFKQgHO0xLQW5gjrbD9VGCnR0jGgoNY43V6i0tKQWbgjNDTKkYF6CCsKgk1MYr0
iKPgDLBh_DxGZHLYs0PgjLm3fUucXWwBcBTIzpPiLqXlIfZSaa5wjHcerG8KQwHM8xNkxptrOB6sIGrGY4FSThLIUakZn8OFCOnvPP3Ur501QhK3SOWROjYM
yrhdzvOkemPSsBdNzuNR-afK7GPYC4o7Z7wP_Q_sDdFGxIUl7Zfv-pmbWfrDtE9kP63iiFOOts43VpHnqtOUOnWWrfRUQAStJTpOE-R3osktsgyTqVOjRxH6
_RtHsjJwtjgd1VSexzYb5MxYtQEjAhVt3djgzJXEReVnrR-qwAMjqsOtB--mD3lvVjZivjunB7aCj1rVMffuw-zRoj_VHhoqesjvaoxouFbqIs-qWADzZexU
Q0r4ExdjnZTQ6n7ji-5sZXRUNXnjh_96MzWsO82iBTEdlj6gxapk_8gsHvXy_Afz73Oxunjjc_6DDZavtcXjT_16cvoC0NxH5aCqyBwrrBN20nnj7KytsQkF
R_6tv3ZIpbFxEDyb5X_V4avje_q8Zl2XFLoGyCfUOVk_EHccjiut99MNzHQsevssFt8o69lB7QcEZtcnbhFA_aMRrPISdF6jgoIThsk6oTnGX_cXbION6noj
3TZRNTeEKxkOjx2ZrGyk9Luqd25EbfJgT5igNSKQxK3whjLsajFEH6iZB1j5QrFh36oqivTH7RUqxdp4XfGhVEtUJ9GLrtaW385uKRVC-p_jlzpZmdI2Gt5h
viI9QfrzlhA4ctQh7CJA0LrBlnK8hkZa0hBH7iBACM5LMdlIKddfpf0SxITPsXLbTXXMlMypNbkNRBHvkWUqdsDvlQ9iL9cuHTkAJKbLsdGD19kwui1MZXwi
LaSdF_JJELzdml1K6oJBGwoSuLcLrWbnMFt9ItVxKOvYvK06suQyTVgqbKsLOsLZ-8Vs4khFZMpbW0hOxMIIyY7Kq3WRO4-TFAwLOyBQfGNuCfM-rCbCi1UT
x6-i718s7glMAeb0SWb3qWk8EJOyoXN5wpJJ2HlkrkbhALkrQMDpD9EPNiVy-HjmJOQTnxV3gYKEQqydg-lAydXQLvNsSXChPvmcrggESe4c4QYqNEbalQ9u
JOGPH4mESkiexGylaQVSSrWntRFgv5TSklij4GXNYhWQfOcLzl5O9n5K9zzYXkiLfLOE0e1yXOZ9SPfOQH_-BedGTF9bhcCfLiuhBsROVAcq5DuHM9NsGVU-
mvgdG9XyBs0HAuVkH7gUhOplphUEqWhlUuSLFphvPbqhXopS8PNJPTschO0TdUmv4C0KjgmSTb8vWpInqbP4II8qZ1Y1FCrYGmgjBryRN7Xtl7MKTecxJYBK
1o_RqCaXaUzIEQJjEx1zMkdWjKwcvPwLW-jyhqwiqChnxjl4IgkyIvqCgiFQUAjoL2l7AwtmxiwgjCghO-cYavkIghJjoVDjAiTitu5LscKjQ9bPGD3LOLtg
v9pgnnfNdZHijrj7QJTvDOa0DbgzekP485oWNogKTyScLje-hoOHIBw_eXWocfQglq-g4BPV4_TfLLnf4g7Ylh5oeebENk3I96IsGnCBRO-t9X4YKQqSDcgz
eiXyVz8kspbEK_g7TvScLjf-rK-f-STXJNs7bIxAqHUyuPwiYfJzMFkqAfuH98aWl1MJgfEB_hvm2L0hv_k1_GNQEf-sJ29yrCb5sY3E4StA-VM1LThFl6ML
HE0hxVMMk4xbjDzd8GBF1IlOBpUnqdxcBPf4M3kiaVNdXFRvSnO0MR3QWLLejtafEhaiTV9TT39BfMrZdXBmBnQi3FJVftr0Q9kXNCys49hAKI55Bux5WfNz
vi7sQVlZstLOfqGWtYXMZl1MHqUjd5zbLThFjQHjR3aII1Ve3QMy_3ALO_1zO9MNN5ivAG3XigMJ_SjK3hWNguxlEeb0Ty0QxKfmOSva-pb9vVnE4-DBqBwL
uwGN9p9NLawjUBybTfx_ON-VbTzIRbivLELO5hZX5Y5MpbOgn_2dOSiNT5zQEPhAgRHJ0Dg2rNeM1XjOhIMjeImTLX5SAKG09e9BPy6aYVU7rH9QNcypdQGw
h8qNCGB85_kmO6KOZbLvDOdGqycu6v2dl9NACHklYPLNamYLbwXI-eKNkJx_TrCv3Zev5AjMw-JOaWXyux2InV5XmIg2fJYv-wtJBxec4HHZzSRRNR3AKpIm
Bg-CUB1gvMWIWIxLJUMquEXb9YXBxSEmQbNSJOUL7Pty38vEYPMsb16RM76NIGJbJTFDbbREGnUiAgtm3dEmMlHEAgTMc4F6ze9Ln1-YBNyNTJkLKntM2E15
E9RrWbKGsk7ELKjfLJXwl4SiKZc-IkK8xR2mogj9XCgRGmIGR_1NNbsmAa8x9AlMahOzv-O0V5gm4jfXMLLiI19X-UIvkM0bjCF3RgTo04jzdSnGRo0NsW5P
jKgzRrSwcHyMh6Qm58Uxq8x8gkNh8YWEwtB1Ab_ZpzaIz5AEmgguVPtywEbaXz2E2zldPQxZsqklsqsKuvUIU33UE5qJjnUiXFO8vzhd3VTew2nOUSMrxsan
1gZYQXAXbyf9GdkiWrNU628sKpcWg8kZiIgl9X4wgPolQCjWd8ex0vyMh8JsQ0Uhl2bjBrYfJZuUg_8M1_BKTLXnlMUXFHQhLl7YR82Ky5XTi4fAsvSJ1oWd
E-brKOwr3dMmtwToyXI5zf2iMaAxMB1IdNnKLgt-WbKIsiF2Qd5ZmKfeZysgl6-j7AKzFklsWbNVb-9XMVkfdEfB2UtnMVkfd58Aw0lQ0rFsKpcidKprfSh1
EViBLgmpMueqyPbuDObGIvhuFBWTdNm-LbsmcjA2beypbllR9CBZh5MTAxpGblDHAcuEIdjsNgKzEMyHshCNXVRqPIwqfo-bFN-vq9w_XFRyvN-Fzhy
}

