sprite $image64 [260x180/16z] {
xDZNcK8n44DXCaYa_glT76RpEW1t99yI_c_a1v_xX-V8isj0R0WyHZE15RwBEzyZYEqz18YGvJKGVqU36LWp40KD0SrZG4qqE0AZJQ0f3eB7Xi1ZGo3p94W0
rWmxzCzr1Z6IjW8n-iuWbkIZo5i1rsab823xC6m1c2lWwb50GEjvt0CmLy0jeu20W08nXMoF84RR8uZHLY16Mu4O4toLARsE9qmutnd44dmKvVzVG8g6m2KL
Y4mD0G3R_ZCWaQtkHv0HWTt_Iqd2TH31rNGGHCXp4FYStoa0451WhoMaVXRsBGQanYdWr690I2YGBGOK6GHF3GOo2cWna7aMJWq6pgT0oYaq6EWex1eCT9w5
2eFj1bgdm683p6UBhTeWIWrc3ortOeCeDdXi5GSXeC0AWzbyepK8bXiyAeWz2_VbckbsuoeGX9j52mqEx_-szrWafAHnobQuEh98tNLcVl6vkwZ2sSV03I8z
si8U1bwT50rzsS9E1dtQmkiCpEIagg-qe3iy4ULxiWNz7GCnGq_n-QMiN3MQBctXUMVoO0LW2sxkXyByZ45mybW-T6CB-lHTkQn0txRm_5tP2yhR_kv9PGoA
Pbm8E-ooXMi_EYjeCh9LPwrQNtXN7cIj_kv92k6nBPZUR47p2nHcArWSm1Owk2S10gUmkIUTI2UjcaFu8BOmZBtPWi-F5HGrEq6PRrle83xJf82QB3AOR2Vn
cKFWjc34z1MVyq-QoJtfnxvUdqc5-jaMZ8ZferLp2DmMPFGTnMTz6K8Oq1PSDwsQG-3nsOmTnUTCn6p1sevQTGRnuBXjrRuVMyX4t1QywIO-PohUgeTER44p
5M_LGo-jEZ_H1stLqaMhrepwguzj-QdYceAJjNQqwcinuF6vbo-b-39m2brzAQKnPI9wJw8ktAertMwPYiTdr3LRjSRR3HWqsi8L7ziqfXjXi3y-u-lp9Mn1
jH001gssO4IikL1yhWIGGRij3FC5MZMkGL7AkqLQjVkU1UFVPo4uWTdd_L8MduTWtZq-unhSr8dDkPs2MnK7AyQ-iorel5N5GMICcUYtzwHJ-oxt95-3oOXN
vebSCudFDhWw2yDxZO82WM35XaJkXIPRC4PC64wFpzm8l9Zf_kj0FB7jdZHX574dVbVDZI0D8iFzrz4JJsor1USBXxDUd_bzQCJf_N_6EufCrDggJPX4t5cj
cXl132Xogpv8gnv7aJ2TS4_I-z2B6TCTXHCxfvqvSV_hin49iuWpPyRdzHgCHlnY14D5aRdQqy8yYqppYMb15Ot0YWjt0eWYj-lvTzLJEAzLLm8m_GL5-fmA
pKGD2-45LHXiRI4SJm7Ne4n_B1rXXIA33bi8EqeLXL0e76S42YZI7SNq2qzi_rBAuj8SI-4V8qYr8-1KG4uyqXPGuHK8UaGmBYZi1eMHpDGUdna3XC0fj1k1
3F5d59chtHOO0tRIDWZ_DEHKFd94KPjZFXY2ZeOoq40fjAz1EIUWIDkf00R7sG9Zm4T1cu8nddFf22iKOvaAmg1DSMCBX46CT1JQrc3yQiY0mipfgowb6p8u
sXOCOV2_Kj073HbHo892NK6128wdC1Z2e9t2bW2SSuN2HsYEXC11jk0PWyXjeQ4XBoXk3r0G0aUc1SAWVHHuGuQEK50SYO0_Cn46-odmO4nH887ZjOtFHXym
Q5i8N0FiGWN5jYCq4sYtXK0OxAF06pAYmBe4NxIUHu4m-EL2w3OO8mhi22wSC0JGgZa351q5Jc0TZ1_KfQ9yYdOmsBKGk0Qy8PiX0e5pH1ZybW8I8BMmTWGm
WhD46UorXST6a73wiIw14Pmhoc2_BMZSlXWN56v1CHfY16Sg40Ox5sAr1eyQieE6Z6jmlWY3VQFmGqCU2meCncG8pX9Xy385JJ51GuQFlA2GaJRayqKOS0eO
Z5DY3HbG086tfH3tGYX6a5BzcQgqGM4N51CsvBSKOK0em7sO4fnpZQ960sZ8xod2W53GQWDfIOEr5YAAH8pWlVISGG08kec5CJXCW-kwX4RmtdhAmFeLXOSD
-QUE00ZUMayOBEU4Fwy4I2syXX6Wdld1xCHE_p18DG812eCeYZxo9VJK4oSZRWO6zPmffU2sA4WmVcDH1dh_Pn3nMXdKSyQ0qrzGM7mgkv20WP_YMcuvV72V
jh1v5DaQ0NanVdV1aSM5YFAVXv_jOWiu_VPPGxuaXJBs0yn5FNpKqOWBzPnXiKgeXT2G0S4b8PInZw1o-CB766p8AIqeI4E-cbQV_5m9u704Ntzim7-5ez8H
Y15SIvjFVf4RlZnnSSkqddxi2EGskEG5eVxB5lpduIUp34U2Xep1c1Z1TIa4jpvyr574ApHa7emxM0WuV5mENuR3M9p-b2eAIk3QzsGzl9IGu3msvBZK9IJG
8OLG3s_14ylqauRS5uHoU2XEAQqRCWv1lnI-4v8Hhph2Oy4OWK3N5ChXosOO9-wx8QVKEGAy9sjnSXw_HoWCSj_Q5AUxi26dr2a17fyJ_anLIlqXuF5v43De
R6x8bs_LreaBxBsqVmfJyKJQ3_kdG0XqBrqpo7zJwPj1_hig30uYy1y
}

