sprite $image314 [236x171/16z] {
vDEt0K8n40JHazT6l_zgyR3eGZothuC9Pliy76qI09LOa48fAPIIG2efb992AIcKaa0gAPIIGYa9f992AIcKaa8f2QIIGYafb992AWcKqh-LZXQs5auninwp
5gjg9td4gyLg9BigCrOiLZFRlOeujN2gEIdCjbXrSvxUzkT7zGh-lTQFMfQydWDjkwVMJ7JKse4W6kCr-_z_xLkTeUSGIfPwIhcWRMHV4CVkSdMPeL0VodQK
ADjNzH-Iaclyblz5_OT2HRsYhb-uaBNFr2NEAw__-57x9otB8UPzj7wVGRWH-sw0TP9gFKRiTJt_oVjCd2a3s_zIRQFs6PAH_bfjOzvdMB4L-TqWMokf_k9C
EaqiZvdMxpCbJX5fM6NhzvaX3Ypm66Jh8zK6iceBzOrPTzlezvd5cHw4MTURkFjJsVRhq1utVAF4mL7kitqFszj6ly_i6MxsWBZtBZlIdjzdn8rQWpenx92j
lo7ahdAMjuh3clRy3U4AqvmTyaQn6sJhzPajnCRPkRYpuuffx_mhjJlUgl2PC1pNe3TZslFxpDwoMSfxePOz7DPWbZriQ1jT5myyaMvSWpZSz-pUP5_Qoryy
o8Z6ITPb1PNuACouQGyknhWCR0Z69xmMTbkMY5-s93thS6Q9oy1X5kLYsfk-j7TEUXvC1dscpc2S_DPDR9wpRTIaEg_o6zQuAlLjE02r_LS5o-n_ectKx-rA
jcm8TwoBFXE6uoTKqJOwqfucFUzm1iKxPZoMOzfhOG6TQU-SLBU9Ckr5kJMiaVWF4d_Rg575VROosuPzmZWDozasdfEUnpfCOHWhHF_frj_spaaFEvnH0BHc
6EOc3IwRD-sTanvsE0q-WxHNr_w4C8oTiyds75MdTeRP_LHCU_2PFNnxM2zFsoX8Cx9TF5zshAizl3McFJP8SpdQnY_dZvwtZNenPk7mV3Iszl5fx-lNBmbQ
rU4i1frn1n7X3Gd_uzBUbs_Vldxzce3LQGy-SyOwi8LvsMxIVrbpMwlJ7h_UVAnXLIaroZRXFr--VjkiWZOhs_xUPyfcwmz7ZKZu-RJtF-bcJHJoGTehCwv9
W-VeVLMBUbw-OCtGwhGtk2qxrh4r637XnyzPYRItonUi7obRO9p8RTsOyEzUNC_IdYXVi0hQLDhJjurSglRhr6tlThABHTNb-umrwpyoxIcjTRvlJ3PUKoog
81MiWZQTzeJFCE7harUdFGXLikf2pgUzCjGAnO8DGuJgM5GXLC6gQVDfhwdtH0doeyhGBiVorQn-sQws-6o9KJvuyHu--JLUbwzcDRIDgWPk8RC7BwvXMF-N
XIvVpMfj6wdj6ELRA8mmBEzJHVcUinhItlDMQyJDnl0SuZYGfEUidhJ7jU03JVnhXGwoGgYArTysqcXQtEq8A-nR2FMOrTysKjCLmy9dC8FoJR1wqXudRtDJ
bh67nUy0mcSIh9Qq1qt3PpRsEFfzX-MRPVNB5Zxp5kkKpmZI1AktRUGJqLQrVr6e6LP_sqWdmGE9XZ31Qabxr3H2NS9d4gocjh4-NGe8DU4p2LQJR3dP4WrX
WjKis_cRoQeFS0hLnUfFUwrEYbZxZ8_Ld_OI5my6LXIo8UsbVIRFwazxYOi74wk_RSpxJ9xLd_RoFfDdzSksZFEBXyJh9m7CjE8-EzyGQj9_N-TerXy9bi5d
WFhdQ2bEWy-0z1JMtpR6FJQKxmLesmDfCGWrGUjh6_N5GnxrIhAjDg5UfP27qMSIjCQsiGnd-LvAjir0wgG5REhrT_5qJ0G03CGmR0z_m0NG-MK8kZX7H_sn
lHP8cv1Dlbxhy-r3xlFjjHDI7x8_gjVsH-r39b8_hS_NQ_jyUwsIzhUTaFff_L6zjZzg7xALUgtFruUSvTjhhTI7BAMzLXwr3zaTjTSwQO-5r5xhfBtMINkj
a_POH-srJjfhdRJ7EcclTTHUwwIzrabxhAFsMYVjjKxQQvsqnpfghtNINkkalTPHUwoJzbedxRLEscCTjTSwQQzrqbxhf3tMKNkja_PQ9-srZjfZdRJNEccl
TT8Usr0V
}

