sprite $image57 [59x121/16z] {
dTTTjgEy4eDXyskxfChyXti262t3fawJp_TFlr5mPx5JEqCkO_fFPwbcTHr-XrFvmbgjBZ_2CN_XSQpCFy1X_TPqpFBhoREWyDl9vIOr-Gsr1rocTrGudXnJ
sNXoJ2sU75Cq-kjaKTbuSapZoIyeyNRodOB6fx9fSaXf1F3gAOi2xUFI_0XRFFbEDumZI-ERfopQCFOiW6XoG65cPvQlBhRv0OMD1e269rpxoHN41RSi4KoU
HKrIcC3nRIEShEhTjYneg1PFFgRTCVHjMtonArMzO3ra19DRDS1kjF1Jb-cirZ-suiX6OPxLSJ8-VseyOGFzh8ufBITcZ_MGUmowVwcTD0tvKAHm1OXsCOLj
WwxgSS76merwemgRZk2NugYULsGs0ghkOODr1-udRGLRcjLa7RjBLTkXpNetG8JtDVSgovJhrF1O7YqWsbVN_RqWZvfymmq-LEScwgh9kE4_rA37kf-rtYV7
r4NRpgp_orFbw-gGbsFo44oEgsDxPLlgeW5WG5alM-VpAoxTKuwegjUph4it-KrLPvtJcFFOmjYFCwWEhIBwpULLz52yLjbe-v4KdRRjPHO5IGTSr7XMgvcj
W-ZWTVogDO-gkgDHLKLXTHQbStk-AzSngfe-i3bXPH9rnv8MqZJrMgMsmjmTPgietOS5naOHL1lTmgEgphJe9pge3gBkoABkqy9gOVL6QMMdvxz3_BDQhQzE
YH__7XQ8njMJUZakOd5tMaPKjREQie6YnqKqzs5XL0NEwZANmtAZqs1VlLZgg9EFrT7Al5Jmt3huVXDxIhzLSLApFAy6sa7fxdduVrKdHAskSpQKHkaV75Js
GligONMPywIgSn25EsxLamBc-_sVKzlQQ525gQexN3lgPHLruaBXD-gqfL6wEpDULdM7fxHomyXuKRL6aO_RD1J_S5hVRDKTpaTrkubCox-t3ZSwEkOlxcXO
JQFklsvJ7TErwfTgz-up5P3xLZsSt5VzNgLeIdC5QQ9qflwvCgZkPrWD6ysjsbEwus_LJhfFNaJTbuxUggITBsl2wKl7qOzi-BC68m6mfEl9KxAFyqhnK5Ms
fsdTvR-gODt5F2NH8Gsv-vhYAkTjPIb3e-F8l3tfj8PLlS3Q-1LwWTY_OImfnLMO6TfPXpHiNjJTfhWgsh_Mwk7mSztgKHLWdIxqVfl8a8B8mvKE7MLG5Lvx
wlQsgibv-bBg8ig6L9F7FANPDcoYS4TCPO_NyWKVRNrHrSdZ_bQQWf_mWB9zNyCNfxZw52MxAn9NmGVgXAv8N9qg-RTAQ795L3t-XhjpRIQ1gBh_2eBkprZq
uSVq_1lEtICQ_OJhJmD_2dCxSRMT1K-O13tu2HVzJgPm9w77nw0QJURj2mwe9ZzA48_LQ3911bMJqUHCOQNwQaGrERZQ0GqdwtXOZIVh13IS_9vgiknxgiac
_8h6asCQJ_wTQZ9_fJgpaRzJJUQTydxzuyd23JgM5wvD9higy_2AQV91szjkTEB9z8_DFp5DTchaRsUiHIF_1m
}

