sprite $image381 [294x214/16z] {
xDhPbjiW381XiIE1Pzx_RLj7JZcnWcQvgh7--sRv1W4vzUV_6I4YVMfPo2bErWUEgd5e2qbRJXRA3EKK8QUi9mjd6Osoa1GdCrB7pav_FLDA-5NKjjihWIjV
6FNDb030LmMfRtypfRse6EsP4fVURqX7fdGajwVMjsUczAzGvR0TcHACeXYseMHA7evS7gV_IScKACCpNuY7JIYPKgrfZDrk99LCgLOaUEOaaYcnJ2M0u6TA
dwR4HO3SlPihcHANUsn-gcHA4VOyXXwcIgP4nR4JgKfs4wYmvznKoPHIqMy2fiGqcG1IqfLC2Jn0wIxCbKo9ArqxuqpfEEAoecHAhkNmS79LKJAbWlZ56MTA
49BT1FIO9Y90hjzHiZFEvw-KJ2bhDm5JSXHux1vAVgPaPrpol9ocIgO4RVpQdIirf1kn8E5PoOLToQjAjteiZfwFl1DX6xktBm25vagtUbWUJtsSVkrMzrRf
z6yM3sKySNp4zT3zEwMEhztmMTmTgKNOSs-LEjtegLsSv7UbKjWfY8dhRI0jFtOLPmK0mEbDG1Yjl9nm5ZsKm5VYXQGeYMvZr3ehWOi0fJadb1hDdUeTZ93w
nafSwP6SK5ATLZ7wq8osG-dOkYbsBvJs2ASjFspRKycrxDYflLFIbnEjQuGFew5KCCEU0wdqjTFAmpQKe6J2oKrWHDCNkxGIqMpOM60e0LG4I76gnD7anIwj
DCP4R4X2YVy7t7jDYLzFlDZLbVZFBuTDA76rpSuuwJHUxFfAU_9hIIK-ubpMbJWIBxQ2KYEI6zBHk0aSDt2KIZ8QBtPz9JgDoTYGf5AXEZtZP4JyOWie8TBB
dv-aqRXx9_Kc87jziGiRiT982WqbW5G1QfufoRO5b0Y5KjULm07K5j99gQ-h50b_gCGLSHFeHBIe4dBVLkAZRI--AdNUz6b19S9VAFMK7I-deTJRU9t5b1hY
xvJa6TU4zofAX1mH_KG9_hHt9-gDsyWMW0_sMi3x_ezxFmb52v8h8kYEOclQDIjcITA_M4NWa7B79Fpu1BpFfn6H_ncbkyzUvDJqJWqWlbTI5NQStbf97djD
pYZPQRVTAJqulR-Ii3EHbfNiTU-n4qYpaihizEPAp8zASa8fQ1gzvYYfCvxUKyb9sYGqMLVgXOPJ3f-KdF4qAsb_3oLYJmc8lAe4cNO2avBlD2lr5kGjb9Xz
9Q29B2eXCWCfE4f-svcIHa2spczdP4fQWCQXo9eIGW58WgFajjrLIJhZegJCydPl95bNS6uC13wp4oZip2N7wQAa1Se8hM_wezyPQEpKD3k40JIXvqeHW8rk
ASuzxh7jBF2M02XNlVGTN-iTcitTBxM09iXoe1Hw3iD9NQNPQLn8h0nWdqvizJv6fYJrAYM5100TAPNf2VYav9HetoH3696tMUa7jftmaH9Yqsi9W7RGSLI4
O7MWT4428DB6snXLXf9LVfSBoPG0Ow9ug0GG0IMjA-c-NO8fVTHx69bI09hOHg3IeH8YG1h3cb8I2pE11oNH_Xv6TeuhQ8nGXzEXakq4D2meAL__O9f5WAYp
aloCyuhmef8gCmDepvNqgcIFcEXW9p3_WNe5MC9bEkdz8_5tG9ft0XA19ebz9Sl_2n2wZQGegqgT0N3N8NttIFm7DvkVd4WDJO0YhfAzy4unzA8DLYjAabY0
P2nw_tpzHrz7Vd8YukoN7kF_rehIkb8l06kWRic9MhDP_T0VLYwE4dya9vBS_L8NdgeG0QsixmIuzu_aH5biyTrpwU3ASPHkoKaBiv8Hy7rH0LXoNbJAum-d
0P1jv2YT8hvNwNWAVSgzwvISNBJwqJTmMYHPsmb86bi1qR5V6aN0joe97ogHY2md9rtOhLRNTWAZsRI01Q7PeXCG--KFBZ_lGZAJ5CbvA3Gd9q-Dh2IriA3q
qMoiTPzEw8JQxGylFyx8b81YRUSa9pm5rVhi9V2uk1FeB3erMmFGHMyVWiX_QoJBIacRYBZ9IU1ToHb8K_ougYGPh8ZSJScQxUvIfM-z-_jAd90qXcOAeloO
d3nfDjiJhYfPizsIaus2BVhyv_WfpJRt5rMDG54LKm9eJawU3wHkhLENb038b9niQjCfcfAL_1YZUGeb86iL4KjEY6qZS4rEL9uOMRKUbvIIZ4jdtWb873k1
-MwhBtyKULv92hB6S76wBeWHgeuw64XMzQRKPJavkIuwOLUQdVAFk91CAO_kuZRQRYp4afEdJdVRpL1i9z3Lz0-I4-pJANJ2MCWza_m48rEAI3ordKx92IVU
b-8rsrp1fhU9YkTaSrfloSac0UXKR67ruenN-2jAI1zXIRwAsA8nKCHnCYD7QHx0ya_9YG99vyD9juLOlVHwoeioylYyEsckWu9KbOCj_BQR4w6fukVVFKQE
aXEzA0NQzX9ndBxjxY_tfxQKD22IMdrAJkJHoSlbAeV23oNYxGIuxmD9jethb9o8oyJVqcmo_Nfbk6W0iav7E1A-9ITj6a_MR8wI-jVjezASdF2szJav4N6T
XBzX85aYSjSKDI1hAZ8M0Ct9IRDxdwqtjuxs6gPqbvpmD9nCoNVYzWrt_-cwKBMDGCuQ4PejQ4vE6W0vUEoq2HywFIOdD2SdavB79DzmzwzaOqPKeqqaqJXs
0bFRcM04f4RweXABh2KdizBnU7hztJyZyzvF4QXxM69AjY16vh68Ke6yfEGx-Sc9DPlOIkIfaxpGo5T2bA4nhg1cOKbMlIKdV6ixqGfWISaliV-l-ic9e-Gv
_TzBcyr9jeFKDW0oieRGT2-6BUPqG2KjA_abunut9IU5v-J4b0wSNcuqVwmKWsIaGK1DmtGRkqzEI9NP5d-an2AFoGdVafFmH4dlWfkN6yqx0T8C1BMAGD7H
QG_92QisvB7uCoNMRKfE501FoOcQacFqy0UdroFDUwH9IGgAX32S7fEJ1WJHWvs0wdCdIcNRRia9wKDoyazAtVa8NZIr_UzGSBeevJOMJGAGv-I4vlqIqP6I
xLJzAa3Uh7e5ICESd8o5So7v5og_zZeofPnuQEYpv8H6SZAcM4NYvqfFdAWdKzgRZRpan6isNudvlr2QXdK4if-Sq4To8asETW9FyheMSqysa3P9T9YSMFLd
Gq_aLVqsAqMrAwW0MUDzSZ9e7jhkKCc_d2G3kMUok_-rsMYx9IVHJqwa7zuQNdarsTEbg3cIZQVo93cXsnGxKFATscWs-x-DPji74j-Ia_embtJf1dhym4t-
w1xNikQFCIHZl-Gc9wnQaotMbEQsgo5l2LatAyM-wD5s0fQSwAoaVN6RSTns-YTAQcrdLO4YqORGOt9IfYcsecHErcnR7HXowInDjX1zI4vcfNuYS7ZTtdkK
vAiIsQ98GB35VN9ILf8Jv_iKEjtPj5p_NTyNfBVaH0cmlRSP7IgztabqBoew9ISIWFBbvCJzsJZ98f5jyXh92VLRSg9pSg9zVME_Ffw-gcJra9oKn-H4LfCJ
zsTGD1avPhqerJtK_DHiAcDXHWTAhnzFivANd5oyk4p92UQsEwba9HcvfyZxWXIsU4nE_k2G-8giSYv-J4ve8JbPL-hRjTcuJpi16qXJSd8F9DLNUhsJhpGb
9_LZ-PYS4DlYl5AdSb5gcrM_DPib9shJQQ0EFQGLfVDjb_z4oP8JiUI40q2KnwAoQe4jJYj9HDwIdKtqgcIBk-H4BJanC7nIKbwgvP3Wl9BSaXFKVS64iR2H
5EGhIgFPp2YdYm5lJdB207Jw1j1NbLWMdSuhvQ71RTe9i4njD_BVHbzI2cJz1QH_IawKOGlDm87IwwydNmdHXdMQzqkFoKb1ulDAPOmTwGb8NdAY0L0krcy9
VwPKqjBhOLzI0aoZXekIY2s8W38MJGeGJYjr2qkcv8JlavEzsVuLfOguzdhOrvI0B1_92Nqa9tFRjVDALXN8lLXoaW7IU7ldXFVav7emoN-YL790FDDsvvKm
Q6md4CLBJfugYQ_KUPkJa_wOdCW-a8B-cL8B011F7LhEAm6HFfJ07ya9tP8JUgeauYXHl4zE-Yqv2G1Fu_ofal1X3QHsuaaBVKLf7azWmgdaf2kBESrAPKvE
slNKAv-Iaqu1JvMwy9fIFFbx-CYNbB3JP2OWpFib8tZozLIMIpdxfRiDTV-Kd4W2dYdretQZMasfdNw085zIGcXJs_57SXAa-Cc96OswPzgcv6JBytvfIaus
1fuggHmWPG3XgXHuGMbzF8chP6KQBO1fUkUa-Cd9_5cRqwJKT4YKBSDFJZPobPQRZG8kbHsbFtwoAU8fMHcD5A6Fv4JKto_PP-qvpSb9sdBalRz8CHPTVILa
FJQgRKSQ4-bHwLzvIYw-abMHntH0EPcIqsmkqvoSf4twr6naOCLLYZn_hTClIgZCp161-BEIqB7DkjEiv8qdYk1RSf9CoJ5od2mvoLDCEISdlG2UKg1-F908
G6tC1MWj0eauJafcTABQKTiLMFdZIPpavF2ptf-eSKJgzyb9bZqVSPLgNnb83K00SG0Y45kj786otcpdnrCBS2jFEu4eazBApMSe9I1rjTrrlcx5-vwFU4ea
2qQc150RXuOMGHmJlUormZrFSYjKSPAJnPkFzf6SjC_9YMR0LJg-IAqAW50v0yX4G68s8ttHRmHdezcjqFpaf2iVrcM-v3qvcVPBlG9FbSpe00cLEG5eBI3G
l_I-Cnsq7KMubSRLDYSdzbaVbrY692bj6KdsuuYhLAQBT5d9WDkHqNhnSoUf0LwrJyb9b_Nik8_a96qZEUcI04yfoUfn98N8DG-bCf3eN_tM8PyUJwOq9oSg
VA94UMespO2d5AalDbiTLr4TIXG0v8CBwVNZoPGgtP8J5U5JrJEoxWF9KmfjrOXe_D-kIZ4ISwsEqQlRJblqbB9DRgipJDAtnllRDvuI5rqzicN4IGaWPj_e
zMrNNIMWoCGawqPMaW1NgQ_T_IsCZF6gr4pf6EbbkwViAY4qFUaaEZskzQgivoDZL4Tk7qhXgDbUl2lWv2a1aSwqdMYV7jUwHMV2oFhXKvX3E3wEl7uy1Ky9
IUUIjMRh7E5MraMZbcCUIisKNlmp1zOFBSTAAhBGR9lJR8lvY5K2WEGfwUjyriUJhqJ7JZBdAmbEdRZx1-lE3wNGJZNRomyjdfA4Wrs1DPklj7mSQSb6JmHA
1D1CwMm-ylf3ImkU4f35SVACVAKiHqQKO4Ur33HEG6ZxVllydUtrXnPN2QZYjvqDfBdY-O7KC2en0Qa689FD9S_ezIK7Jiok4gAxU_BU7Wsd1rB3Xr8U_zfA
v7gyG_h6NO6l13ITIfncyvHMZYCKW53I5ILSOLj0uLgck_yFTFALgjwLJ4QUqde-ae18JDcU0gIBLJX-_ly3TWK7IfRrFbUAj1iT9lzjoW122K3x4JzElidH
eSLJyf5yfL0NmyY4_SefaJ3gt43wvaFBrvNMZoCyceov1YHxtuQ-7sazK_cgqdfWQuVQVIHLRW6nJ0FfBPo-fXIecz5Yyf_jNt_Oxs-n_lx5UQMuE92iykWu
2a1nZDx3wRoIdZ6o181QX7_tVvEsqtfEQHv8gzSIdC3stPmudr1QVZeopQLHxSSQMUbXfhAejDXiDG9fzzgteCT6FtxtLCEnqh5H7HOZ9YdJLY0KVWEabKpb
KEdexaznp9wu9ofxDVfvTxRpRw-Ag5Fzx43AOq8de1A0u7oBwnrAv8nJNs-sMQbUa18iF3fuElAMusak_nNdOwK0P02bjJUxaDOp5L_97qY-KiEbSije2qRl
FvxwoRj_YG2e08YD0kBy1P8tB5fpwcUCo6vib00GfuCNIDvzF7bAVVLHf2c50DI3S-txEws_uZpdaQFZiXD6lc_bmxOxaOyGWCO50D4SHkPtrLdFLFhQGAhZ
WMtaeSGjv_LpxVktNLynIW0QZyFj6DodXlRxE_NZ3AdOiJO0YHjcfJU7MHzFiXH30eK080-manVI-rzE2qYvN6c6LaxqVaOl_U6qLBa2YUFUSPV5PFINEnNR
HKQEI2sEDYiJqjiY71Uj6Y5SZ5f4fDWg4COmgiLfjh_qShB7HIN4VN-KAquzPdl_ufMz4OBTsV8LwRf8iz5VxfJjJPCHQxVnt3y3tkliVslRrG3R3zbjpNQK
kV24z7SxjJYTzEFOOcSupVPNEsMCQgOKx3_BVwEHbQiK7fKePtAC_kBBAQDGc9MS5v5-dHen-qgpqQ_JlLASdexytQN_g3Jd8xyblbAXksRxBLV9DVfrcfNS
WVHRuYd9hyjZVIWT1xQ_rrCw-7RjRwszPFDRicJqM_BzpVR_
}

