sprite $image425 [461x94/16z] {
xTq5Zfn134HXSUnouFwd3IppkXqgpxud3eW-kNj-_cOUHQeUD73naAHGFM-X94NMAsspfAmtsaH9KU-qnf9KxxQ3aaBLQ8CbHVNQO8bbDtzBBFlvMsBPRvqb
bhggeUcDYQKoxluoig7fQidnPSQxHoqxB3c5bwtXNM398gleZQy_9ejiTj7Bq9AoOtbLRC9aaOsJ1TdQaaKsZkJBs9B1pCCvziLaC7MANwwO3AREVo-vMl9J
DWQRh2ScWvcJNTRJai4S_2TJJ7x-nEm7i24cgwo6ysneoIeRmvtM49DLThpLsc6ookRuH_1cIrRPg-I6IPhy_BagRJ71pFa2NHQO5BDLzYgvOeBvEzkjXINb
RCkyAjmnsJBtOu8PW_zSTtqoY7wBGvU32MPQOl9ZLXyS4yomn0Gp_m8cWKbWKXfW4fW49dicc60I9ms8qtdaZKbS0kFYD9ZSQM1ssmXd3RW7YBlpydBkc-M-
MPbXKiqtpVhhcCIp9coQzJkhx79DdXmgNqmsJQr_39uq74rT32OlDGZ7zm1HZKPJtfZydjNsDtHHJ4RJzAsMfFFHJ7zCHZCdYwoJ9jNfGbksc9I7cdfaQQl9
QAfjxu_9Q6fWwQH9wcjcBSBa-r6A7lkLfPycPRK-1nORlhb8giPmPhrZQOd99wSptXtBSltcD6MzoHcfQbWwQg9vbJAkojIkR_kJgj-LfR4cQM3fgaaQMBfg
aWQMhfgK0qjNJSg1fQicXGQKhfoK0qjRJie1fIqdfGQKhfmKgJxb3m
}

