sprite $image109 [239x166/16z] {
vTg9TY8v3mNWU9Ta6jx_RGViogMfWoOwH5r9KVTVPb--beHjqPUVYF0rbsCayn8vWfRlaVExOuaVSv3I8d8CB2A7mBxv20l_NzwmjCVnil2NEH-XZn6H0s5P
-kaTi6Shzi-VDz1sc_QAVGEkMB4ZHndQF-_05JDspHMMlM6RlO_Nt1rUEspO3kgTkx-NmzdUnslk3Y-MR8j02owlqj_W4mgH5LWOGVQkrVlvjB_7ly8oW4zT
-7bejrXzX4_2UcINRQmN6ANTptQ7Nuy0gsO7wmhVo0xws3M_1YkyJNPmOtmliF2sEGWMaJVjOptlUVZeBujZz35s0h_x4bNYQwdQa-9tbpP_l9QYlPysh-nM
t9zVI0jlozKNqiAoUMdjtDBC2NUklf3Uu1GMVftRs1nmzOKq_iYFOlsvA2q2BC0_ZQMKo8sxO97rludGJmzj_FY8_upB2F9JM6YlNledpNpg3Yy7JoobwOla
_b6bxop53Kp2Y2NrOqaYBowBd2PMMCrFdRJbqniTkFO5hSZcXy_QwyArBsXbcpxMlUJ2jUVyxtwM43KrwJw_6t1THjZmRsL88dyk-tTqOn_kHqnRSP6FBspK
sfFIkd0HS4jwJAvau3fsT1jHi6vS_VqRKjEu_k260El93V4BBcm-N4JhutioJbetRcZPmlt8xbmcjRJ8XUsfUj9TomOkT0hNhS2yuX9xf8QxLkEccGXlKxYU
u2xaxsr_QJLkv2MuagGLDxD3PCNj2jXDgtFNtKsFtEIXFQsujoWTxQ0rSNcfRrQuZj-mzFuKpDy8HMYDt8RtanCNIn25wzhH5A6rSJcYcrsum8BB0gu_c0Aq
9Yx-53ykrZsVJpivFt1THvW2j0OktiVLWulIWYlua0RNUOI9sCx5UgluS85TRwLbnVKzbEpSvicLaxwLxeWTxCyb5ovAgssb1Kh32E-YklA8bTKFn3ElqBT7
EALNPhUwLFUkbVKF1BXU7OrhKdhXaxbvpkwfF_cTNGb_1vpmRsla9jThXiZfIH-lk5uZ35ysSoauNoAboue_0wxZ25ViNAtSwlH4q9jRuRgCS8RNoCKsovcB
Zoxa4KVYqD4hh_cz6zYLYw5zpfKKGaXj1HO5RFL-pQMyNbRnXmCNGwjmMnX9uZ32bB1WrBYXZfGKy6sXDtTY5Mu9Cv6i8no3cWyaMJUHpPcBFjQvfSRfDOom
TQsUaebRME4wOBLcbYxvwkMEg2FiygK94YgxSWLOZSin1Eh3cosdi2StDVRaIbUqbtxFrPbaijbqpOesP_n_ReZb4GkkDnRR39GtyM0NsxqoM-fR2xXgFBcY
OYSNeJ3cbcA8ncjMpKhYNqEv8LV7dYuhhlJUvZd4ESZtBj8jeBQy9LVwISEkk9oQz1QluDOxALZZqv3-qZfmFOPspPKO4dUQNiJuDDIr6t95no8TII7KtjdY
5Lg3jKxUZYjTmpxdrddUSbpk6IsbocRm4swel1bNxsE5Evoy_B8C_TLTxHsjBDgsu8geM8qxW4a-RvCImqWH5Kmgk46x2LV7wjnvVKmyozluIarb5Fg54Mu1
McUkVMZbedBnuHnYvNOhAeKGUFm8jFu2k3Lsu7eChSxjd6xp6ZwvXRka4EN5GycVQn_QyyN07TKSgRnyKZMKrrnWXLizkFOReydRMnnSvZZgd5eCQLIHNmI3
6vCvsERuzJ4YQt1EYSQxYEjDZaT_aTwVotaDNd5VI_J58dqLMOwZrdaqD_NwznQh0MuOOL-k_V2nW_4ndQLtIbUsf33JbYrFR6BeQ0UkQsbry5JLcwF6CWQv
rL7ePKERg5l1L5zBOorch1qyfZSpLnRY-FbyY8A5T6Qzem5sY6SVwrwSIh48HzIrW1jY5Vyl_lqF7ptFlVC2pNEUemnkA_5MO35qj4CSXjP-2jVUqwnkhp7G
u8uD3pQq3k1jiSYfFuOQpSTINGfU5-vy8bR3lR9jDBGk1SPcH_eCkBs4yT75Muom_lBf5yGDNEUPAvExd4CytILPJs74SyVu_SYpyaRgFHSSH9dxE9-KDJox
WiMzZ_KHnigztBgNS12L73wvsM647ORMiQCfJcGTt8QNei9LEjftQ3rpNdlJyF7WqlARIS1r03iSFduTBIt5rF39B7LkQ1MkqmZB9bZzQGZkl5CgNCi8-vVM
7tpdJYWfN8UE1dOBA_AK6vlWYmTmNS3-9wtBIodHu4PUkD8QYRcZoU7bimqO7zAvtNxnoItuIMZF8YhOVsZzmL9Z605Nvk_8ujBH3dti32wFt5xZtCXpjuFT
3nz_By9pX6NXTYvDMfn7iNc47OPsAx1GIPdxv2vdCk6bQ1fXSXZQRS38vCgLtkQDidMa_l--aa_Y-VBnprdZqjpYqUDhC3_RLm8iV_w8xz3wv_ISMmEIUfSI
qrBhh8qmtMoYl7myjVvFmpnlbYt7oSs3pGftTFIif3WCxTOTBQMCHSxoSPswB6LcSDVvhAHOlwZzLHKMx6RBZJi7-KfLkNtHo3P3wx_EucMRTUEsiURW58A1
g_UnN7vHdZsKSWaBDtBlaYnSwNvzlFt3OMdcE2uT1kvcVUo_tQafnXkN5wx4hxZT_J6m-Ti_zRvyXOQdS2cqvY9xmEhNh1fJxsMvIfR1pNCDR-HYQFTHOAvo
6ze4BeMHsFezfzsLLWTtl1HmlumfX4W6Bh2x0dEyUUT7rVoYiCKGvKlk1TaNcEQzwfDBu_SKbOlAxjOxi7WiPUuvH0PNAUr-mLnIIZTk6-nOh-m6heBTCrYa
thWSGgAvk4lWxXkhxolpU2p9NDL60NVNMFqKdbyPja77y88BxVx1YEJff1m9t7V0wgTm914IOd3V0wk_XMF4lHbSQ7SUUduAftVZ8a-_OY65-uxWMgc_8rVV
mByf5pa85v5ZS14v21Sv2XSv2XSv21UHWt2Het2Het2HWt0HMN5FbpVF0_TyUV-0UxeS8uDx-Ody1m
}

