sprite $image25 [235x171/16z] {
vDU54SCm44HH7VYW_uB3d9XvyoemQEUFolBOGyjVi3m9Bl0qyigfG9F8fwhW8iyt8GLKbL-SuS_kay5DbZthADP8BHk4m0McdZFSIEiPN63gXO851dUo4jc7
4rnWwbKGWS6Th4OE4mmmKiJ9akSu2X0OhF1ev1ISuG9JpmWWC03XqSXfXS05ffxpPWFZEg7OvFNEvYYYRt2o6ZdBgsvkiXoPCxtgdTF60dD_LPBHZjJQYNgp
k0u6O6_OrdB_rtk2I_Gmg8dgo2t_-MQVDY5lG9POXFeFdTuL04Mjx8wYGY_tDnXDtT0TePwnwUu6ewa5NgRj0JkAUc_9LW2RUg4b8KnH9UMc1cDHMux7xY_z
FRLKatfRuqaAggWjwQhMLFa6Ya6Lj7HlaMfgkxx6e0fMKUyylIi0DbLzd6HHGsmcLHhF_MSmGgrIqFB9ca5zf9fKATdRBpC8TVmByf4-sgrD3SMWEXgFey7O
rCW8Un1v_E_Nr1p4Qb8bzUyQZBrNir2CJyvTzb7LL4V9-XkCJUr7OPT7Zds6043y2C8ro2pxg2kgesJz3SQcaleG6yAR4EDpsLDKHydw6unDHRvq-iBZv-cH
RmaerdQX6jcMDvX9AX3Nyp7H6QqP-6dDYkeeMM-3iQd3olshJFFMcT4UzvzVZgAQsBJoCiCy5P1PGWWs5KaMuJcgp8h-1ZDFbG__2FJUVdOIH-KuWXNLJbbH
f0wgy1hOL6bHQPOgZSVVOFpKyZCgXf5Pgl_qRWDOHGrz7NLzoUOE3cehaYY3WKa59nLwyJQOUQhQP2mD90wgesIz3QR5QbD7Yfg1LRf1RR4vPaLdWwd3y4Eg
cVg-sPJHTEtKvKKg9vhvPrIxLkEn72ggsjXaoVeRJ7o-I55xLUacTNit6CefRLfKijk7pmIs2vLOXIngEoYeg2DbRc-qkFHf1kxoqchVo32eJSxDlwMYsfYL
pTzWz0dr0FfkPCXQaaceQcDfxk3hPU6JECWacyzNQitoesfIvLCHAgfOMNuhpvxU-P_4mTFcer1rhIH5VJ7H8O5Gtrs2YbEpudo3wKLbg_MqUkiR6PBscbfJ
E4c5ch_RM9vk5UMZ1jFCULAeka0qLVS5P12gcJe_Asu03gfEaKLcwwUMsCmlFH7313MKoTExqc4vzG3mCpHsmcK6LXLTcK2eJgikMQF1-AYHy7pHg1Yx51bX
ZfgcJkyGVeyQSZiVFrtNQZhlqY6TeHOcc0ZXIcghQbbAma6XweEtZBbnZbePPw1CD8D5rZdDQvqtcO7LLDQlr7RwcK3FL60TZF8QdlpWH3DO91qnHUJpZOnw
aJ9Sg9TZLrCxgRJJnd06EgW6rehqhCJqtniPa8EaeBgHaQJ3CDaFy-YDpHoxGlLOes2Or8qCXZe2h6vao6d7neHWKlN6vekEo8DjvpL2tSYWTpSopXLdKDN6
6kCCLAWUh5eZr8qCMVWkrAfMKOlQHGe_bYAnfeuWVcX5nlUNlEk5UbHgPWI3ggm9UQ985LKoQINUROdPkhgVbKNEJNzCPHhlnFHXPoHoOOchh16QUgrFcO6F
kYi41bLziOLf6YfK7nOP6QthmFgCgscBJGLaOfm-TeNgjiglJrm7FgZTecehVZxL4Rcny36rpL9X0cfI1Vj_IqLYWpgFzLEtNw0ArA0wh7DNz_kmvELKP3Qe
arW_5SE8cwgXDjMFdRgHWNbWob8giOCgsCLKcTsxWwgXJYhXIch9Z-m-2YDn5HMP7LIDzJ-tnCTW25Z2I5v2HU8FgJrrXNLHfQtGGPNT6k82ge9EKFTlMvtU
UQWQH4scOoSLcJtKHye5k_gv9POf8rK7TK0zr95A1dPcMagbdQYNXwFBnrJY9TGmipxDF-52d9nKWVgfO5XzL20kBYeoBwCsebOrrayLQ_-SYiGBgHjH2R5F
O2UVMqBcyY5LGNtKH1J7wgcmtd5VGapb0oeohwL6WcFteh9wPk3hX-xTe5fGFpMWF3QbrYVF3AoAZgQen8kfQHSMJHNiF5Lcu6lGe1fGD_LXtQ9GTN2MQZyF
R5EHFqvxJTt6dXMgQHLgAkuegjLWx518_HLLvd6XsjWIraLJ7T3d_VplgN1q7A4QsD-ceWCgkst3xwXq_52eXdKzTHKKKf34Iycsk5Dp6Cg32jlM3EmlKZr5
UlbGwN8KrmTrxCzyK67y5XfOueLPyxOrg9JBHDHe8Ej1BN86y0wBj32uuDZjKKlrgJZXE94xgC-N5ADa5yOFnHnU97Rrb52aWng2MFyKImvf2I-ZhvxbSgOM
BBBp_mQBgufKHv_4qEa0tcZyGtxOOpEmzq4XMbAzye0iIpkrVlq2TjYfQkN6V-JO7OtIpdLMXB9JsnUrZtzW7CW-9WrQZ_LFWJzEWGiMY7OT7RglCcX2NOhr
DvWmbKq9sewZRUYIp8oAwiVwfy2fw5cHXY_9T3oYgNwhVmgSJmBIwzE9ceLgOEzlC7OAVclTZixJ5DM3NJS5sh5dHKp7HVyyg4VXhhGY_SOK-57ZQJcbqLsb
ymZLY_LFWRx8hAZBDWjr7qnATsFzbndysL0Hnd5yK57Qau6zOmhqDvus_c_TgGDidBVVC0MwIrQooKz8_ZKR9NjBW_4t7ah_eIPgnkdTpLEWQrOiJseRFyHz
cqZK9x3-1WCvsF6NBFG-g11a86v4ANN3UiSKw9yL-qwb_GSo4AUNDOjt5gc_P36dSIYduqWQr62Kx4rJu7pQPST-3HITngPXK6C85Sd6tZ05EXlFSHK6jeTu
K8qpdZ-ypB1-LYp7_yv2VTrvyBufq3yhYZLs6jHj6zRUyHKMwQufq3yhxZYfrK6NLKm7xsmm_iO3Mtp8wA12U3iOtznW_BCY03sfndsF_rLdLbSKmr0CInds
t_SnbbMAxGtqSOyLHx1W-AxuYrhbuI6B_GXO84vIZw3-_7xiXPg7U1d-W_v5BSEmEqaUAI-U9l-YrW1LuKZvXnP0tNLcYE2AEwCMGIfvztcN05HYWO8dsnO0
TOVFfgYks3G0bLgWMl40LBM2uID50L052eP-Q7LW4IgV6PHS4JYmaWNoaM8u1aVAYsSuO6RGJmLHkGMAkc8t1XO8NP6Zri4q1K0b5gZiYjtOM21tnMvi2eQx
OZSs5iXTiHix2ro_AwwpG4jNN3CpcBeYi43tui4MwEkAe63SYmTPeBSh0WjqFrbWWUwk6EL8hm
}

sprite $image25 [118x86/16z] {
lPY9Rkiw34I7sZbK__ztNmFQ8597K72TbtENxZqrgQ68ub_9emk-Z3JzfUAhLEN3of7nDVAW7h0dV8NKgG6roNSQweItu7-cAFK2H_v6GuDexzUA-uts7cbP
UyiNYlk5zgPEwXQoosSRsjz2jNuoBGDlKSbHFjVGXrLsFAmVIP4qghgr6UqrzF_KhRyq-KnQnl4SEeQIggEKhYVq_pjEAxNUB6vO7ou197TLDpYrkjVV5ocw
UxUubKFWD7QWyH1axmFTUcj8IbFg7sk1T5ND47N3QGLoFEkD8LdS-TUQZRGEqP5pruC6ruOrXkIjyUVM1aZE2SXKcx5FM05GwTRDaDoavMfLLZnuI4Vo6yYn
2a17M0Esz6ztIoJ7s6jfQgf-caARW7QnBbEqB-vpNcsoTLN-iR81-MfrE0hsQLbRwRx1oyaPG5fProbQBmiCQykbb0pauMSuOFzZvLzzasrQ0lOyU5ep3cJG
Z1gmFLjPoxgz-uPMG3eFQvLqe4EU-vg16bRDG5gl6kkqX1LeT2ljWC-doICrdgsGmKLxjvlO701GU9ocqMfjNICvKRnYSS8uc_-qYqroLTnnqDa1dAaufyJp
fE_99qS7oZYm1hmS6bhMQM4aJFp_c8ZveHWvzUWMa7ro1887PR59-jsoj0O-_UUqdmuPjCbeF9fvUYuKlaolExVMv5PfhRUCn25-_ln1QVhAkfuQ7hir_hsA
xqG2fvzdE06GRemD9WBi9NY5JRENNXvO5m3L_CwncaGagwbRCu1Y_gtTQdGg00nxxVoPdZzTKG2Wspc77vy-9zt0VZvEM8y49019NqdvwvnkNNiR86en_McQ
aggEb1epK4sTvmeN89CldFRpaBfrhJNDf1xMqNhhrVqsgGbGVMcrLcrHt1dMjPV6s9jma7sN4AI5LSrMnGthfimNAxG33wkih2-TBdNhJXlMPqDZ0iR2kYvk
MFVUwvtZprwuigwTOGsuUTRH-kF_KlnYwDnQlQ4BAolNwNKhIGw8yl6Dw5j_uyRgQLbP5T8E_yBQIgsr04NFVLW0vB6sHd7NLg3EXVVFtdHCH9_CXMihmxcs
PkiQPRucHmvqU6d9lB16MlPMeQ3Ht7knCZWDj96gEc5T57TbnG1GpE4whtw6Zod45tqDvzwQa07aIuhSgYDGcnp7EyuNJrQkdRzbpsE6jGZSUl6-_JkOIClQ
QHKePqm5BG7fOMLeULhtk7LJt1_VMd76L7ChI0NPih_BERHlyKPnHy916kOqb8RI0MG-U_aEHa_BsiaC1Fc8QUqFAwHvTydmxjaNjrvQueBPK0RIB1ZMIQcX
lUtiWWlINT2R2QoXDKWNqBRUzzAY2Iz9PuewSaBrptBhphjFIy62I545q1DgWRXrxzsd1MkEoFISMT0De2atsdrQ11kacpCx2W5cVzVAktSoOqkao38IP022
PWlllhXMyIRLsyiCo13q0fBXvPsqh8bTfe090ZH5dw6zavOrCII7DVIAh91oQUycBInOiMzlGYbj0F373U-DjEpRQnceYZo0N1ZQUsdPfsXKLUGf059eNRfe
QCODafTvpe4y4tf6X6Wp_kuGGxBCXD6HPrXlDtG_96axQomBzuaKQLfRz-FlHehQmheTVxTIn5fiOTsCltif2dRZxvFj3JwRbdsAdC-cPPyYvyRukz7U6scv
aQ8RQRcHelaJQVa6qcoQtKZBZHHDR-XNARoHbly
}

