sprite $image91 [236x172/16z] {
vDP5WiGm30LHEoHP7hZ_QGUgcGCDTkljigoG__SBo9zl5sJDIodSbC9DAjoKmaiftAJ2JIdSbC9BAToamaqft9J2IodSfC9DARoKmaqgt9J2JIcybC9DAjoK
maqflAJ2JIdSbE8jIjMqejfbfJchZ5DlALBEj8vKSwdb2Qsej5GffNM2cbDfdQIsKgGPhQYi53nQKvckkbHgK-dJGWfGTcaNkyfgPQO-XX1YBsjj0rcapDIX
2G7D86W2P9a2IqdRQ8SxjQAiKfZkrNOZMrN6A77x3Z5in7v4gvh9A2NE9El9GnjFMrMFLfN9I2NEfDI68_jnPcdl8jCwLb6bKDDueLKDkXkFj8xtwdCcTcTU
v7YcLPDjAANJMl7AKjxNfZywTOuSbYAb6QrusI3SEquHpXfuraVMiKacUqdgi3yUhhJseeQSZshjoTlYbrbxqP4UnQ40Z05ZdrH9y_vlkm8A9Ma7DV7KPjgx
SzFzatqmfFvhXgpK9gTrEkqhEkwzlTydh8gplYbbBYlQyoaKoyUQNgSwshRtgRKgpsbbGgsrrbeW7mRvWzP3dOyaqQFsxR1wjNFfkbOtJU5SKKRPeAhewpF8
hpSUUnBCElMBjXIZ5RgsAaPGN-zTgn_fzjZxHsO5gEpOSh5dhYuFLrOSSedzMEhybyeNoYqTLa1dhMKQPswhdMYjEbZsMB9IV_cfpMgqTg76yejLyIEeM0Yg
g_pIOOMDxR3kLwMv5QD_sxy9wk9EyaftwpcszWb3UMhLpHoxZl75l_ubKzQiTf3jbuV87olRkuCvbkwEhsxENpBNfSsgGmovqEP31qEhh7jXe4x7qdPpVFNs
BvaEQLCc8c8po5ncNnwIoAX1FGOLEjQi_Zz_yJBI9IlLoXU3FBH2rrRTJiVkonNKqTJzlOUxXvJSiIRkMAlbMYB9MCUUCSVI2AhZjpt77xSOqlKPJX2Y0jZO
vj5IOnrxvg252Ugo5WVfkbM6TDagH0ocs9mcjibQZq75-tqEAdBoFzxW2EujAp9HraXwlNyu6glE7wbC_URXAJZ-k0NqZbLO6vO5c6dJiNW4rHnB-ocMVpuQ
rs9xrueDWDwm4g4G9UnbOYkRkJoyZu_Kpt_Wz97ctgztUEsbwuSQ1dRr72uLcw4viMAKsRQjT51nE7OLWy_3EXuCcePrMVfQoxkYRIgiQu5-B36HPYAAWhtC
jjN9RN3i6RoGJW-6DQjkHohk76F0kXQ0HaeA8ev4YKXdWrm4qqVgs3EwlPHsRLwnwcQQkXvkO5tRFDIGJ9J0b74gFMWRzdrwfBv6UWztWUE3eVngXKzghD0L
ApGHzRx6Sjez9hRQWlhw6TItdWx7Osp9MksU6TBbyJNM5IrwbKXHCyLcHawfD_mYjggYDgZdQh4zrr9GTN4B6-kQLh5NeQIPACbu3AGuj7BMOcX7KAr1w7Uh
DwXpAtHLcwX0Kti9n8fDH4dj88kgR2Qeer8hPZvXovU3EWgcL9QqGfHY5gO8ZIJeCLPxaLB5z3qJBek_jsUirJN84YkEARM1HgAOYA9UnNOslbYn-lUCjRgr
oYchK0IKQRpsqkMsnVLp7BHWXKywjxfZYqW2G94eQd_QybLiBml25vMBVy-C2-7CwcdjhYqKLNArKYmWudPgsTWMiQNRLUdtzipSwji_cMhriobsAqykoNVB
6TG5grVB5Ob4gPrMPLXjR6zYuPEkMRtxHvcbMlipw6njiNLelNjctUgFBH95DEV9kX3RRxvd75PdRAE0AJQhYivUU-NXyPrR_TeIYL8agbObedpKwd9i_Nl6
O_N7bcerQwJMPiSW-uAwlNnMpPdLrThsykapp5MkkAdr1zLdrL2BuTCAMbzJAiYKqIh_VEqLuCcWpgqSMaNrl_QuhTn82SgiI9HF-qUtoMZ2jsVyrXnwaVfY
2svMZdsUYIHHEWooL12-_U71trSjrB3UGHOY1LDIgXMRTTGsUlR0-AxaLQ4fX0nLzxQDjPr2n19fmOgNVy_uhOWX940f1DMGuOjj9g9cLSZlLlK7rMyTZKqj
jnbjabtNHk542TMATaY96EiJUyPQRMAZbX2ezhZ06ziK-riszyj54cDz9gXpAtSigQRGc-k_Dg9GRDP2jSHOtH-ulsCDL3fMe2WXH025dVi7dmEAYPGf6gjp
p_ZgycXYjA-Psh9BRUTIySLM8r6t9c7Y7zQl1TM_NpCgjYaxcK88ta7c58cbYXF5tUeEgh_-cUpNXisjowLVaGkyMY56kpuHwR3wzuoV-e_5vhPoMcRRVp1u
l0RK-TeJC34aaWph0tl6KgrMAOIaGEjbgTrD8NH_YiNNMcWa5kPX_O-aLjkoogKDiOOGGU6JNcfavo0JxNbrNmZzqhqCjbNkXrF_6RX7EQBuhesQYRAn-Zuy
-AaMgx5RIpkSScX_2KgBRQJYZkrkVNnyvzf2OQpMMh5KPVrtwGlO6Tjc_Q-bLYkbD7IpPgq3NVszqqZgrMxFxfbvpJu_5L28dmTGw0yWxxLnMA5F1NKT6yBe
Pe_hi7glZTlZuxkkZJMkBRVrt_HZfPPYno1twwDxPbtBrJPoI_XOmJt7TxNDkZd6ro5rO0k5CdARCQpjYrHmn7PxRdnThSN8RHdMCTsEs3uZzMk73CPwzxNt
u9xnQtC_eyxMc9lLeNrcp_XZ6zXOQspXm3upldvj3cAjW02QOsHrQ1-GEhKAQwsbmN4aFnDKltPYJS7nszw3JVLZhJK4nszxJqhziVrfbJR0EWvgfnOFI1sn
ZMThQPtkPeP3-y2UyMjXh6KqM04nsByzlhOMh4YjiREFDCzB_JMpwh3MnjBdmyMw5iz9_ThqiOAgTV1rFvyNj8ytrNzjZ0Cz6bcepApGlo3rQmMVmD8ksgtw
YrRnbwLMkm-noJ5Yije_icVyMXwDrRFrwewiVsPy_G_vL24XwzaQOKh_XDIlrNxppstxnFeVChCsBVvNhbsO8Gm4KH367QR_Qd6BR7Jvxjuo7VpHCmcflRTt
wsczjTWKh8N4g40zzaPyjBIjGb9xR-zvxc3wz7fRAPHGkvfDfkzlqshgRoLnzlnduMqbVPPrkvbwMiaYo-hv7SOejNRXRyKi_IVPrqfc5IqRHoj0rbetAvds
0okWePsRLccflKXJcwxKrcvMjTITCjNM3hMYqcWhGesp8jO8AteDj2BP42kozRKYNIyhwdMs4g1kLeBKmKgSMgp4gi5Ak2mh8Qkr4hMAbSWLh0JloqhydbR-
ewkL15q
}

