sprite $image23 [177x129/16z] {
rTUBRgqu38LXGiB5zfBw_cyxmyn69YMAIfOgbr-NSp_ze9QJ_VKhoT7NQv9FB_A-YInrB-2-IYojNiFrNiFrtiBrNkFrNiFrNiFrtiBrNkQD9yj8iTmtaMMy
IExo3hASfIcjVvyi5--_pPkC5E6Tf__ByeV9ukNfR9Q_IXR2ov5vRt4lx6-AvTfwyKAOVerBU0F8GdXfCk_TkjvuiH3U0B8yywuvzhIMU-dkTUr4dDRo-zwx
DlQqbXzwNUi5N3obrNptkjRBoox2atblhhrjRTa1g8p6SzlUjZOjEuvCPPkdmf1vhfJAUzVEgvvQaKAECi-LzUAzQ_Dc7-pHCdrA6q_clLeQO-jQsTBapRkC
n79bTLsgnxRMYknvgXeTPOehszHiNdniVT9lhIIPzzPZwrfPq-ILp8xo6DSFZFROUjiyULc1FVtQIvP-Mq_hUzfBE_vh8ITPXhXo-Sh9nxPkgQOMW8eOi9Fl
M6J0AsA0vMcQFsDRQU-hh1XWvpyynoJ9Q0-udXfGlTgg_JgyinpSCvtEPBm7N4yRslOgMqtzKL85vido8DNkcUAbjV4eMRYSoxLLq-2yTTlg2uS96SbjhpBB
KxjPSNd68aEfi9LwbHsLfdS1whl6Ck8rKboVmm1C56XmYxct39_M1ZE2NA-oB81LQwpiQyvJoddT0LZZ6VCk3r80PWnvdRp3fFLGPrnIVyPhvGdt19kEacsj
pk7QEnKpe3uMo-Z5Kmqdc7Z91jX1o7uENqqclRl6_EG3YG4E9iXgW6G1JEzZejQvQsIxN3ot7qo3WqdoPK1hxmwLItkrhgM-U6u_v096YqKTTlMkbRSUtWs0
YW7R3wvnXXfCazkN_0BhhkkF9PsFrt-zRR2JUUyCwtniijl5itIvRJ1Ftfq5jEuQlgvl6x2tocemBsxG5FKgyv9eww3SsyFR1_DaIFO5uQkiRbu_VvIlDutE
DFJ0_8exbki6RQoo-VBJKdAw_X6qm-s3UVAwGDkhR9dQ5Q0_3NqmVLh3xX-R5Xmrx_P9W0Rt0PW-hQMzojG0AT-vEu3xD0o0oONntQIdnRRiVr84W5LS0mCs
9U_AVlEihnxRkku2EDUdWG0p5unpO8lrNg7fRHe8C7_nJBCurrFrxrxDfS7ynHFwOB_GO7x5yTmxc2VpAK23x-HGheFZoOO1S9nOyQYlBu8Sm3qA9AiDS0F9
XW4l8GwO1e8Sm0qbsm2N9Ai636_0IoQc8O1ChB8mCi4D41FJ440ck45a8xW1P6ALHOYLu0QG2Mu8sGXk09bulG5YWXj3De8RG2PMMOHO2Mu0cU26a8tWHf09
Rv2OuCQG2MuCcV36a0bkZ9ZWnf09RWoPyCQG2MwCcE36a0bk39dmneW9RWoPuCQG2MyCcU36Y0bk39dWnf09RmoPuCQ82MuCcV36a0bk39dWneW9RWpvjxp_
}

