sprite $image129 [159x231/16z] {
pDY7SlGs40FWT1AxyENztpQcDK9qbvqBB5cKaFozVSC5Y_ttbCpFuuOeyKPkpHkvAq-vAK-vbqkycm7b4a_XlQOgddB3qd5yuVgZnzrudPyyX80tuxKlN-jv
UGK_7SNgDNn-dMqmhmDAzShBtiR2HMiD0bx4gquKnbA_zfcuSXFhdtxPiSpnLH--dW9UmbFmjMJveUJW6HEUm_lQ4PHcgPy1dCLhiP126YoyxKzTnHkm7AHL
e_fTKa7n5A9paAIHxw89IyRbcnmgFcbImAaJ5e_1vIibdpICTiM4nUlnHTe0yQmX2k0qtdg7zLo1x2-Qh2hucCLh7D-i6jNlwWgADn1yqWZpjeASm5jl_Ymr
TGKfu1IUdb3lD7K5P_1Kln6K6gtfQmKvWzU7x_yqzI6J0CxcBIzuGqFyPy8C08ZpUAgVeQc6dW49J-8rwi9uU-JLGqzWIVintIEUU7gl51fZw84rFuBh02ZU
jdvAZ_BMhIUy1JwEBXn6n2lhjzMmE_TS2dYeXW6yyEhw-HLCgeA7PmmKlB9-tx_d6CU07PjeQzJra-Pz1JiYoG_v3W21agV4jdxEXiZLLVA0_JZntjJFk7NV
yn3-N0tUl_KpAcZmx6C6S7XDFsbMK25Pyu1TEl6C-hszTKUYzzOAdkSBsBoMHVtA2dQ4TWPRAtXc0m67LzUlhg1W7WzmT3NFgb-z8NnU63gFfm-Dwe06prw_
1tnU_JYe9woGMnuKpmU3PzPFwG9ce7TwF1YwWcVNJpg8DpfGy5mV39vVFrt_2YsUOkWCdkfNmmoUvSD-NXkKNi0CdkbxxELfUsJATOHNFn1mXDVYdIepW3qy
63gBrxA61NfRieSdNnpXgNuADx13lDJY7UHr5h33F1pbAH2irE_WQNV0u_LcnEDramUVzy6Op_l3qa4VF4pcmUE5FdYOpOENN82CFfKNC1Fw_DnCdk9FcBYG
vrTmFi-lu6vU7k7v5SGrFB-2VG9lGWLdyrJ1ZxY8vrVmP5vCcF1Cdf82tfA7q2bu7Yydt7FxUP4J3XdnFhxBIqwuvuxmuiSEcN1uxD_XaNdEKwlcZOJF2vBd
tNCrxuFXyf9adFBKgdcAnoF9FEcUEyuBZiJ9h_td7PkqUQInV0VkkMhd8jBa1PV4oQ_zldYqOuCMZsjEVMgfSnbQjJJ-pHGlJtnCrriYmXsjndj21IkU6V8q
NwY2uf4-JwDLyhnFAMZ7qkSXICztl8BQiKdn3Dt9FcZ2M5SjaZHr4tmwP3OxDZtT59ycB1uytIoVW3oca--a2lA8JWdWd0hIryts8UZoaih40IDovt4tQG5t
wYQSWFv5RV2kMi0i7S4o6LVELObC6i3PSvKXZKDwDaw9f8PUwY_1AKYrRoBGlyB8HF8YO2JV1h5-PGXdunX8VMq89zaKVGg8JZAcs9H0KD-QmZXEIrhHggLk
b7E98PeJQD52FfSe8tmQpSXKI7yS6LepBzMAvJwVc0FwcaonTkcY-E5DyazxPvdTx0w3mTz-u6h_gxqVimAANKM5AVEyXfpZAJ59G1XbH_t1ckF7n8LZ_92O
pF73jGJ4CNQv7zHBhZ3J3_Sa8EevCB5pvi-d3TtYFUy4TKEK4X3L2ge926oLouU4l3o0OAiSL4v0R5XpMma8FNBr19ISgmx3f1KK4X2E6-QVNTi92E1XjqHk
Bm61nzts4v1GE4GNr4udeDrv9e6k10IGLRFKxNR5A2IWuXcRVtWLXn-Bfn8G4kfrAaz0gYKWOYESjIGW4K2n0DKJKF9y1P80YWMeFm699DC2z4OJ44Od85GJ
KB_TAqn0Ysyx0Nqa80vFG1YKWFIHWEw1AnqOZaX0h2IWRa5UJa2uSYribSjCC2K1WKhrg9Jc17J9WhWPZ_Z2Rcy_0Qrtau2ONFH60k96N-bBGDkZI1OAK6S2
8W6KCmiNJYGWtZYd8saP6mceg9XNeFsVPy732GYhIdrVSIq-de3uyWa8cmb8ZGbewMG3uXSq905z923CJa1w_Gde8m5nlUu4jEOc8A5b00kZuwa9gB-XrR-k
VQbWZ4X0zkW4P1VUlJy1sLSFZtXk0h92Dn8Gdvc05FRS1EG8-Ja9w8xAOaM4dv20W7j-vTKH4RhAHWBQhqhnXMArsO6LJ-RuYgqR83cpbgd-490Ltv0BCrAG
tFeX8Ec7dWjNNsX0oOzg5Dpi-86ydO3m5_kT9QBk9sat0TNjGdAzhbJ4G9MmudViZHy3Eb-0xFWJURS1yLm1ak9lR4t1Yd_H61mPi-qYR6i0SGdPW-qY98_Q
5RCsiCL863E0SGVFyhCZflfPYToO6ROK1Tpj5qKiDndQZWUmtIAdU10rpB5Z1tTlY2cBq3RZ12_WPrjna9Dg1RUQeDrtErBdFyaRXYxS0BSkHLks5LtOki_I
oKPemhRrupuRBMltV_v_0W
}

