sprite $image119 [317x219/16z] {
xDN50SGW50RXC_hwhtOzYl_NdQ-010Qplm400000080Gl_4Wf4jHQaSw7zEBQTXsUZosdHQFT25jI2UTM3qU9rQFnudTtBz5kewOhiflsGZRRbFxbFNnK6pg
dx8UJkocyIdhuCHkcbyYNNlVRJfV8jqedkyXNJTUz5sqQyUBmO-OaUx9pfqeEmeRKHW-sjNgdihxlsr6NkH5fh5qTHEAcfDzJxxo3nXm6fv2TtQ-CZ_HwSxF
LnRWANHdrYi_cipGjPsKRXnFoinEQ3UE9sLsfwRJ9urkUgUb8n_syRZySAUaAn60IJeUbmKxdrsokCnHsHoNDJjRiGvjeVp-pbHiG9lIxjATqQvhDwKKmzyv
QsDPDYdbD9SdsUAwlbtyHi_ofvJJNDanHxpDfeLu_TtyCzYrSV5zkmDuvtejhOoEi_dGxdgyux-MDbKJXwxTl1YlFO0x3LqRayFR_5gyTb_cB7PwkohU_Ei6
vw7JssqBYvBjyKev0LrhTp6U_avVgJk3NHqdingl9TlZbVjEG5V79Ip5QydsUELvXwVB6a62jh0esGTUUTknwSYhDqs2QhSesOPNFkp0TideDpmzDkVeXOFB
m3w-bbOsTb0wSdkV8el7b5jyFCWtzcRL4UZq9kt7ThyhbjjVhCLhEvwTqpfCVnU2LuljnzDuKlGTWKu_6uHFjTfkQHkCUGxl6A-bbO4nsUwcIOTd-Msbfnlc
6_dOjHtk9vu9R_FqZbUKyMIxoiTEsn7ezFl5KS5Jc2XO2sjz-kR3D_jYsZ7ez7OtyBIH0U2y1MpUvzEIrNS8EhtTSRm0858X3u1sszMJrNS4ExtT6Jnpl_w9
koUEcMJRZa2djwlZzJBPkr3h1O2qU-9eoSxj87Hj7B_7ussP103xvzsMxEoEPDVQrV7qBsCDZtOl-hIFtNgz_7SAtP9njXfUezD6g7CXwV_q_-axaVco7z0H
bUqPAFCTdGePd3N6kbHAKlYKCyLgljmsQnU0iCs7xPcaQQNG6n3bdAb4066pNIbBDc9NDqENR7COn0iQNIGoMrr6r0MjtIKReQiRBjRZDakVRMVk5LCftgIG
YWlbmrB3-t_obTnlXAv4j6sqc_QBxTiBniNaKeo1IgRIBLXZUrOLSxsUCELk0tPM4QbBAGMbMEMgE8SGAQNidNEvTAES1-dMyub8oTtArykcQx5pLOhL_zVc
09Uz2pJ4mMNvjl64UpugtuutxnVZiS2lA_g2WRdC-bnAigcH3DXHMJR-iuqddzgTVjMajJl_1DRQJ7LbVCquBdl7dkKF5mLFX7_ouVlSxZoUDy6wcHxvzOLn
HujUB1NjarUtkDsly5XsJaCsq00VTrTFOG5TdMAtsIxzu7vnsiVZhQ_sQVjgy9jYbTF_C9sAjumlZRxYoTp-Ghq2iftUq4yyqa_e1l1-UDaIXl1Okwzab1il
l5ji9pzDrxzZrU6jQrV36tcK_Kf00-VOroNcIRhjTwmwl5zkD_J5wdy7sV7o-c9zcQNJtx7gyFHsQR1T7O_lTvoijIv-reiF24EbRQJOl8gkVqre6qzud8_i
VGRTFbvljC9i_iYNWxtIsJHLR6HUGBVvDAJ3KzlDHLl2vYpjtOs9dyy4bDFVvQpHRHNhQ06TXYSFl7uyzk6BW_UA2VSv3-Hsv1iQRnLhPeijVxx3upyAtl2X
Bw1DBRR_vwSIOAaeVCF51kQo6Az_vLd74wRl-QnQRB-CEcClVtw_6F4kT-sE5sjRiSlnMjeDRmcVsInMqoPAW0DyJDUKZVtsocops3H4Dux7V-eQtefsTuhj
Hy40Bbd00juZNKywDhHsfufjbtRhyLgnptZiuALjxh9bvjAGaZS0Z37nUiu8C96QpNInw_6aEnatF0V0BsXN6Mzvf9ZZ_UYOW1flSh2aysqKYrRiKZpfYdt2
GvtNsntb6_abG8uv9Ih5mZhJlbBmLB7hyQGhjiU3br6-8JiznXoSjRWqxEpzsnoF5PkvB9XAju7Nz9Qtotildzo-qHaWPgAB2odQ6yL6XMuQJxHl7jNkWkTg
Bq7KyKoxkcMBp_gK0UsVhHVhYCjoFEakJpxZPOc0axPLXpx-ukzAGA2Bn-nLiSbSLkqZdVpHy2mhU7gxcRwXes1jtk2ByNO3ZrIwpM83btLhT4gnptWU05oC
IMIExyiV0e1sNZm8CrV5bhWiN4TNYrNmXAtoiHjhLx_daZRR3O3tQPykMUNBs8erkaUnEfxa0JnXZO_BvoMtyqvOffbYVLczIjSNgnxpY3nCheX80-sEy6Md
FiEVAHQPos-kqUbu8X5m1VZo8yXvaAzzRcpkK8RFiMqcbjyRwtJ_USDpg7EP6rAXaKDVrbGQNvnw-OGSsjJVZwUKbj29RlUEPu1uZRWH4MXfkuK2u2UA3Rjl
-kN7ewVVB_OogNCtF7p20ysrMnG-s_4Cd6FxXVSdKBzVx0EFBMAy9HlZEnvOPAXTsbEXJDvQbnG-lLYRJ7V7MiDRN-m3JnZtnMGgNZK3tV2ieiSqnUUW_uHC
BpPozqisI-lmlgDhU99GHvTiaq74PQNYDRqbtzYUFOpIhbAi__Ws2xo2jxBO7e-SSx48no0IBfJE0VQ2voFWYYnjbxmnBi-SOstc_L-X_YPTZzVclC0Bu6wd
4OA_23fHngDyy-VOnD-y4VXh1piTpyC3tZxmBD7rMaOTqppVHB5j75RYZT3LzGe4s5ZnKemYX8VZ-5UEgPSejeibrkyej_rkiMtI3vR5EgbxmOkYJsrtNR5j
bEfo3almM5ROYMKHUi93Y0P6n8aiR7U-s4wtt_fY5Rn-0NKYjogIY42KQUtIscB7yTONg-F5EvxustEr0lbYHU7Z9SMskLLuB3hTC1urF0dEkHWbwtXwktd-
U-pu_sqXiF9Wf-BfetRd83IyAJvQKknwl16wUJnNyOhFIzlLYzKVKM1xImzsytZ5rG4GGAG09aQIwpBBndY0RxJODjxUscBdzGZN4N1_I1dbkcXPQLVd6ozs
_KRfvlKY83UzXgVVhDBrvelLjx3O5Nn458bSnIFdJ8n9n0558X2d3ts3nOvlVR7pfmq3tEyhqmKlDhp9TjLYtL6B7UTZOTpnNBdY8Vg6DyN7l5riFYxTk9wm
lU5Pedp1iu26fxURIzrciGSysEdRrxlTOxbboxRXpRVxkTXZ7kpqxUczVl8gPyKZeX_nnMCMkpvUGbryFEcDuW5CjTluo1wosFLwzXtFe-5fOuMFEHwosFNj
UkVS4vu1hBDoctEE1jlDJy_1x56BNNhLr_3gI1eO05BWbNOv0V68nOvl0TxueQ-SWMvVhuW4m3c3kYZawGcFd0kZxL8vz7UnzLTzROa0Uk15m8WSYM-0RjM-
r_E0V-0v0AuCjviFNEnwFQACkee5zy0pH1wWYSkM4nGxTCqSFQZuPpo6I5Jmr7OFNEnwlXJ5aaZn3pnwu34DjqidA7Ru6vjfU17tona2H9RoBNuSUm0zr8M6
vngU1HQqU_o3dRvzlC0DpoBMaGY064dZox_7TmYwdazt95ntnVD0aWNj7lvWf-zRlFY29nw8C-rcEa6nOte0713hoXLFR7MSuZj1iKDy00pm7B4u5KzlzmJ5
Zfvud_5iQNZAME5RNknX-MACxe6N7G1FnA9DRvTEKEn0knxIve0etuspmhUCxl1yNcuZYe0dbheo_92exTSFTWUzwXDnmCKj-bNj7lzWfsyCZovuyClQFNwn
-YRmu6AawNRf1CK-DenN5vUsEr_iyVcYWZVETu9YX_HoS0ulsRgwED4kyGcA7UHBmFriUtjBewuCV-NuIxJyVkVn-IBWvHsF1jkzb7c2WzqmNo9Hy9Jn4rtT
AGvsu-s-u567fn_w6j593dRzliSZkUB5lwFzTeiqZjCKs-zBF98R7kgIxEnPw3p5zfl1YoDu9oXMsIZUuuAFMi8Ati3boUdu2b5vmICHbqJ8Ns5tyOOFTgUB
zu578k9010pXdP6kxLiyTyKp069qt-BnwUZ6lx5T27F5Qzl76oZsn7pfYkT6ySvAD_wD3O2xshLigQNz4U_yTEE_W6ud38fodGlITdwx-TVwY1vueU71gtWw
tVdvseNV4vw98iwvruUzytJdZ_S9Zn3VddhKdPjEtm1UUCOh3M_UxlnyJ1wNHVEC9_Sje3ipdpZKEJpXEGLlZExyryotFV222EU6fzdzunEshv-y96oH6fvA
zu-FxSlPbjW2e8QdqltZuopaOhpXIGHyT0rFf_kdryuS8iwAk_y4-f_TVT_Y-GvlZ-uVNxfd6okU5_flEtTn024C055qS2BzrxlOTIMPTVv72dWN9A8XGrUm
_hvTySAAfpv84tQ5kmPrQSDJAtKbTF2b1MzxSHwQ5H2wqX7UurVzr1JZmHVMsp264FewFBxOj5Q71v_MnYey-BgbAODd_AQ_WKSM7bbuvE2HXKSM7bbuvE2H
XKSM7bbuvE2HXKVFmOFFi4FFe8FFe8FFe8Flk-ak
}

