sprite $image49 [223x161/16z] {
tPcDckCc34K1Wm499-__jYtZpJg9d0kHP_EPdFwt-HgVaUuAY-i7oPNhb-9pvLi5yntVAFUzVYaBlbgkyZrz-Rr-6N4PN8voW_4d7OR6xqiCZTwNtzUX3Ep6
5ynlCxuSXhv1BiIn_L86H6lCb0OMp80qcH_2g1sQ4TxSi7D-oQ2JRhRc3XU74uIXS-O9FrO42OTEC5G4Co8OmL0HJ3sXay0XaKS97SIVNP3mC6XXGGG72Ht6
WY4nK5yE5i7s2QmVjBOO8NHJjWywoIg6n5c7WOrbUTHRU3ORZNCQdQjqySakbANmOp6vBEoV_3BWN6kY-Lw5biAKdtgLU2dPtHUOCY9-JgvbHtUbSRaiXN9-
qbi_LVxMULu_XQ3JR5A8boLFQ-ZMnnPwbTgXuIUAQu4Rq7dMH6jf0c-FlPSpuhAGhmNUv11qdjqibwNSryH9lVN7i8Y-H9n3RYrDVMoiLmL5Nq8kfrbVKhx3
lXm2T8QDBsK5I4yFVQnoUhqp2UPJwLLE8uVrz9n9BYU5tWSwbF9XOfZSyok4drC6V6X8N0whUMjUOASknM3HnZVzexwCiy9DuEQCYQwnRYAz75urk9WXipCT
s93Q6mtyNIevtrurJ4cnlPLu_3Njxr9qAA4dRpvPQbQklMY9jdlTH9VV2vrhFramRp9rRMnGK7yjTEq7y-PjhEmzAc3T925LM-Aok4nPCEq-l_DXZZ7Etja-
FvBh9Xn1KjdX_LwX3ZiRCfVbHg4uzVY9TLFhMZ0VwalnHTkg0UREfLAbIk7_AVzJ3OFqUxdJw8yWQNUpIRJ9_ledoggKfHIcxQD4jPGqDGV4jcxQq4_12pmQ
xJmqvNRmt6w9gPPbDa_4j0Sn9_T612zlXqxsnoQ7Y-VA9YVwBXe5kfjvUkUontdlfrsiUOGAWLMJDrfm11C8dPnYUW9SyJ6P8xZOAPZnCD23js1Kd3a4EXVt
dy3qP0pvm-Lh2MR4P8wHCcOoUcmgtDnMP0WbQuuGclibDJEtT_UKY1eN8OV2PpD479bVOKNgrd6A8IuiFoIFjNfyUtksuSgoXpoNzTqfrRCHSqjmMUHHv7Mc
y0aO7s9ZsIKvS997dRUiUjpiq6JbD-oJm9igFWePnvGbSG8dULYLLQyjM3jKn2JH7bnyt_4YoPRFt7UINtf2jzpfYGxLlraoor5fGuGbMPaBDK_oBlNsvQO7
1F6RfSyx5B96OlqSqrgF62Ph9Bvmyr0nzye9FT6XsZTB4dvTXCAjaxpl3PtKKqSmxlZnPDub5baMhne6mAuZWkGxLbmbchTmj4WxOlAQOR1HY5ZGwD0bkTPO
8_5JWDZvLXSvSTtTCCZlzMLXAblvD16SQ2cq_qK579Vb72FmNMyEWqsEHNVsHZ2iQQZrVrrc2hRTbZEZH-TwwCsglbnjMT9pJgDfJGF-ONBo-7OerwLWwxkq
Sa2l7S7IJ0Ej6ytPszsbTUIoTFrAhmhT0lNQ4TmUh9c7ydJYcTFw7yJ_GmKz3uDxMmP0FyfT474fItYet4rDxuRx4jW1GJL4_a6FcB2QNewvFCszJmXEuXLU
3Hu6vV6V2hSWEfCUbcCvzzhGgVHmwEJS-uJW9DQ3Al0mG7CFGtGIFHmwFFVqWdezbIg9ILV4Fo6zunqwMpktzT9aflJxeSDsnmMZUtpNzL9l-zVXQ5_gvnvf
EZHDp-kciAStMx7JqCZ1VsAC2_HE0QLBsDCJUo8NrNs98yWOQsnyiqETM3T9FRadcdLo1-UUhT_yNWHJ4EiceIS_ekfB746TNdjRGS-bcHx_HP0h_NVVM0iJ
OrM57X04woQ0s1Df-nA_xs4znSiyM0KgBWs8tmjTjvwvwKdQwoP0-z90Fmpkk5xLUapKMZSP0Bmqm2UmLWGtkufMhzsX88Buqa0_33RAzOPEhtBWPdxAFQ4h
ODV0G6wvtb6m7e9whmKLDyZwq9Nh8rgzTWHtj_41h4bLeMCaLsdhKIPT1Erpw6WfXuS1xal9vOLUu9LK0vDq4NowgJiw393SvVgAVJqRjn5VPK67ucl1_j3H
uT2r1JUbALS3ip8H5iGtyq4t3504OLzYGVAtj72kVwswdbaRmUd3eMiB9lUdfwgUfMIDYTeXaNzv6B3eIuLWj6lzZ36EUJR6AeV4FmtT1VXWFvgh7hiVlMpM
yf5YI33ztgv1qPSeWlwdRiHKLNyowU2GEBwRnQ5Jb0vCmHIPVcAtzcWm5KzwmS-73W-9DNOfcbf4PtvmpI6XNpn3LT2NUa5lLYmPW_pQ1TGFW_QaqqTm-YFr
C-vJdTG130drRbOvwOuBhfcRkJRdEkc9zOBwOO3bz7xPM-jNJMAUgYe57waHGVrjZofqUi6LMhVySwRn7EwEtHdixBMXqmy3lU1qYrtwqx2kslBqF0pf0xk6
u-oMBsQNjcEfJQlrH51G7pg5dLvmlYs4c8aZpMktJjKQH11FElrhp-yBXjkGcAoRgSx4IUgjqA-UmFG6cClUcqJ8QnLTBT-cXmM9-dSDh9GxFkM3Svwo-Kjw
gST49maTXWLKnRmrLKpgIK4y3BXv0lkmO5Mon07hLUY3hprwQ6T6X3kzn2-Xj_gIGLz-K32jEwPD3t3EqBNNJNrwvLTs3PyNd7sVteb2Xtco8DUbT-BGuG9o
jA5JhxoxQpY587LK3tJYEKA73w8jlVTs3UN3Dks5eSDwojkUytJed1a0pbmWTASHn2XsO4C95hHhEAbTXJhrJZmCC6_ebVQkOKp1eXW60maMnGbi8B-Y2Dr8
WiqJsDY2UDADxbTqeHjb2XOGkf40UY1qemkMngGRl4CBwiln2rYGtFY2E7JZ2uBIZI-8IpU-Nm6xsN6HUkNwJLoUzAxVngO7v4ONB4XkVC7oORl_
}

