sprite $image184 [169x243/16z] {
p9Q7ZICn5CKyojzZzL_ktURC3Gu2MG61_q3fi9eIzG2Oo2CYHhPhfXQFzAJshF5AsxIQPSGxYlJgFTuXdUhMuYkQRQebY2fB4ZEAR9nCpx8aCMsJ9Ocfrgj3
gaH9OdhIZPEdAaiIKmJZD4vrgt4-BScIn5JPrPbHP4bYUjObYLCbIn9JTUFaLCcInFIq84dAgQOHDwFeaiHJrIM9fofB4bDjIMAAR9pCC2M9EPvsKP9OSvzp
zryzzjCyKtIhiVBgSvufcXTV_KpHrDTU7KHrumHHLvBc6tRzE9yu_k7gYyS9eheadIcQ5uyJH6r90b5TaiuKBOl72QAk9A7dFCh6oQAo9B6ewBqyKpHrmJX1
L90a5fKbYKLbloGMbIM9HML9Ob5PabXKbYGMrIQ9HOjpdF_RkHCboL4U2C3W4uHu_zVzevsXjjj_KwDYCi9CR6alrvpVjgI4cikWOqPI6nf5nkbw6xeiKoao
QDSDYgwdKa0TaGceHPA0-d0ajQ7pvPk1TB3XDEXQX4lbTzsWi17wpugaDlHE5HcgwmQ5z4RbTvq4lTe4L2gJ2EMFwZcSN2X_L6qu-L1oLA7hP2Y__-Ww7Sgd
uhpaGzkZIkWw6ygBAZ3vK7B_fLHsvHkK4bL5AxrI0zf_ggBhVEXYBiwe6fCFZGaemgYo8qda2jq51igeCfcwnVq7j1IH6xNpL1KcCqqXtA6GzlUV7qagSmXt
A2pvRwZyheVGW1gr9whukrvY6ue1w8egVYJby0BQFwf2FuYs9jIg9whepAhp2wYgTesgTPq_edTe0a5hLLZU6bLc91Lxal0RD9zGaRVxhpIdBB5SHZGseNe0
l5Ji40-gMmmXLTJNYCujQ15hg7DKYrP0IUVb5mwlzEjvQq0X1TKHLH2oe69RNhv7T4fjA5RQsN-jHEZsStds4CBQXiBcw3yNgka2dOvlRWaXv2RqJcsSLMne
dZP0KL9hrQ-5rpRKCQfaA8QpNA6R_VI70mffOrIPK5pcrcfGw_r-WDlG5wCgmeVQ0II0MkMA4NL06wDAXy8tgq6N0xfMdKA8nG5jHHKRYgL9rQ3u_O1HCQ8E
Q7jKoT24cVo6xk6hKi9EjQ6UKQL0LUr4XyIWkDmjAoRL0VL4LJzKPLxqUvNq0gsOqdYCg0Fg6TL-Q5dj-r-HJHTejjMVgmFg6DL-gExHGkXej5oXs2x4Fg1h
QKATKGMWWTrLB31ZgJkM-mgjQq390PsorXRKFwfQLUo6xnxELMThRfcE3ongFw0OMvlSdBJMDjG_gf95Aw3kuKnL9vDQDbsXEjc8ejfGV__nPjuF5Opa-GOJ
j2iK3tXgGlrKwRlXRsWfnAYeDwZzRqWtzDf_wOkdsLfwXj3q_r1TGeYxzaEDsWtLUAPcCkcYTsXD5adTKAE-2zNBx_59fmkrwHsgKbkr0-gkzw0obxFVXj3r
jau6HH6WA3-qBDStbbWUJA9L7W6Ayt8vdfVBEOHSHyNy3KsFGP4riLOakUqIJaghM02Tipu65L34pAcYz6Xqj90gjUuHv-L3qFrS636nVVgaY5DC1BwLfw3e
C8OqsIxP6Epm1XlEHw1v1sYs0mXcswLaaxdYixC-0vK5P-Dv3HQOjthwLppPUVa055VZyYE44ipey7LSouJpyWde1fgrUCAGbXDdKs3dwrDGxF9geYtOXjik
ML2XdeDg1AtYOeSVIYxRUMtVO7uUYbNNYbZ7zICjtxka4OyzKFahwEyfdx4qC-wUosJjnkio0XIxle6qOYGZTFO1N-e8K0pfZ5tQptUTqNOjRZe4j2u7Ix5B
y8AEproarZ6W65BHY7OdEB501PUvCQ0OqbsGKhLSh_8AvXXGJEMIR6imfBRf0q4nbHDswRmZwNXGJ6L4k-tbKiU3wlNj48OqxZeS58UyjHipkvHQHuHkS5gx
KzOw9ZHVeXCrA5GZe6bqQ5q0bU6XEvPUXuVAuKnrUAXE-2cYuQ5rnMLkVAXg7H-A-Wz2Fz0FTFjNeEiGq0_q0_r0Fz0Fz0FzG3_GCZBq0_r0TGl_0bHJ33Ue
ZWZ5JrBV0SD1onh2Bz2Iium4rJq6r4sGCwHZG3LFmUfE4527WCeIGXDgrEUXkiNGXEeXbI-fF0f59Bs0wkM3-Y1K4Kale4NaGdqAMjQRihtrHdq0YaYoScmz
dZnGVYGveEPhK5jGVYIreMsg2ygFfFUs7b7LXF8ZoGi5Iindw2QK7qc-rjzz3IeTYaXoGji-F3QW_4ZgtteR1GUK64d-hM-Fga7faUHVfhOFZtnesOAL7rgr
Y6TK3SgF9FyojNtsTFdpLwYHrB_rxL6rl6L6KkVMlnxLur-0SYF93pN9dqOrY-hVGPkHvD_wTl-p-GLJoXzE_zOxLWdR12WralnGbQQFj_M8f7wemzVOUbBN
_L37gMIVBzrRNvOG251dbDgVzzHrXMT0rHsbHNkMAKqXKA2rEaUrQ-klmydQUaErj_w8NFfvsQxS-068rwEgYbiMFvBQjKhFhKJmEOIk-ojkpIXjZgfjlJ-I
A3KbHvJsRZqYYLLpVkkzgBonzUg89FQedayAPt4D9xdYxhz0e--0EYA9NRD_L6thVLTuVYs-g4A9bkAzmlDhSuygjjuRIVoQTiy5LSeVjbutWeKGLRRrv4ZY
HvLjFIkI-azLUHrLMl2Q74dyKzNWZaXwVbHLVu5cGjUfereKMy-D9FwfQbjFZYJ-g2hUYHHo9F5FLIroh1OxalYdgcqzEvBuevgnzTH8uaULs0yxScz9_565
451k9B7Vgwf1gP74Zof0qv9J32FMadz2mxYroeZGTbG1kW_ij57Lnez_33UgYfDzz8hR0zVE_m4
}

sprite $image184 [85x122/16z] {
xTJHrgks4WDW6Hl0CrBU_t7F9buvUzh4_HtCJTlEVRw5X08kNZbMt7pBRjMEV2UPDhDQgzc-t6QMQhMTrItTGkQZaI-st5AcrNZprQQr_ecShxR4v96jQxej
UUoWJCoezjdlEmXbzbJRqiICkcnTPygShZPj_UHNvrL6oV3FdIcpN-t4Z7hd79pH-1d5-v8tqYLnR4RZoTL5qtOr-VDyVaQH3EXTPGRqfXcfYwRBCr8NBNF9
8pe_emuwDQCkMcR9YCxEg8FULsP45xibUKJpKSrjdepeTdhcNxAklpe_6jVOkJ8ZwY_MffD7r6sy0tDf3FNX3fmQH2DhDf1y48ti91dHMEsLCYEw1pHKUwLC
IcpeOVQ9jIl9kQqDhTxKBZkUl2ueBzGRs-_01zyv456t7ZkSNDJnHvJiTj388NJzZLep_IDhOybheQGbeEttziwQkNv4ANa1gkH8EQBjgTwgfNv6HROdL4Kf
4Otib-Y-wqIJFpRi4Usm0oWpx8dYK8P5DAgjom6K4hKZYmiM81E9xsXysD4dNL1FTCr8EufoG7ji7wLqh5B5mXFT3Y1XVsJaW7vcANPGMGQsHy6k4rq90AQS
waSqLallZD-t8m7OaTZGNpmITRWww8ljZzzIak6yJPJoB_H0gvCzjB7TJgcrRHt0yMYec1PJkoxgPXtKTIgRsaSfcVX4POnHpBltZd9D59z34jEfkdYYb2wZ
1QWF0_mv_FCMQiakNK8fIKpdaEefFP-t0CWqwI8gEoGxaSU6ygnqEU6qKLTHRbZKtWtFoLCPksIhFtGTJUthbe6QKIL3Sb4IhwFj5MKS2zO4bzRmog-XRPMR
4ZmZOQ4SC6aErQaKHz86e4XRSSsZMh0SA8yAO1TDcaUf5SZO7fw0AkeUj7r0f8ompDdudW2OT9Xq6weC94eIRqEf3SYADuzA5QlVZjAasr7f7uZMVpFw7-gt
ezJzAFMu7nNtz0BkGIdL1NW9rUPHIbQ0twZLQdCe9Mv0GDdOkIVT4zh5-5RjAagfPhIByGCRq57II_FUubkplqV5hINln0_i84hfM10lnZ_fbpsCKh8Sl4xy
newXb7m5EgXRiw9DqZamepxwie9j9_pZVp9UF_vls-aScL7_IPiLRIgW_Vza7xKG__-scNDaHltuBoi-Cft3Cuh7XlBjDONuGpEAjrbZ0_XJV8OPTIxjP_PW
XGdGEJQZzykL7wVg2cZuj0zUiSRsuiSPZL_QFdNGuiSP9Nnrot6YdVW3CngjbcxEEADBjxvNox4PZLVhadDiHkFLjlXjHfDNAbziTH-RqNYrvlncHeF_NCgF
cd7RBGTFb0ctNgbE7RZxjkil_Ny
}

