sprite $image253 [236x271/16z] {
xTS9RXoz4WFWqjPQ-_xNVS_1u1yu3AB4GumfHRp1XovsbUp5n9gT_HC9fVu_oVQFo_MHk3lrgizalxCqri-vjgsjBnKIzoqgfeJjntVZsWOGxbfRdu6tQMtT
LUSfOT-YOhBRu23yurnRxPcDQvlgtwRuBVOCkxRwUsOUVEtvv5RTC_DysZ-nG95Nt3Fpiz6b0ljtnJqpFnlz9LvaboibCHGeibYWgCIKk45H5zo_7ehAJtQw
UuQVkE_uOahGtJFyPAzx4FAJdDgUqTm_-aL5hTVTC_naftiGyfFUH_MjagA_Vtpl3At-_l6vNhttzktQoxtddzIwmASjyJsBfdK9hN_3HIYZpUuzTr83x3xx
f_miQ_lMje1iezgYLLLxEReLi3grZMph8vgr3NohxY1dJxMAQnFRYjYzpaQqRhb_qAfUMqUnOYfgsmQr1QjmRGFLkkt-GQk-DZcATQmno95XlM_GQfwDdc6z
nwxx1wthQ1F3UjzztzgYjRHTzmzQSrv4Upc2DUUwnDbO8i4AMjspaM7DgzJM4Qmvbotspzmw6MInsXAieDKz6mdMBMexjwvMsqYmBhr_vbPCMwAssHEiozGs
4QmmoAhQ4WdMTMhh2TODzi_4kcPj2TPrNdk1O5scjjaJhEiCiYDOLpaRIoHOrtdjUO9rcTTUTWJhEhKbM1UgBS4gkN_QgAZr1AlSQw-D-wuLSpc2LQksFmpr
bua4gz1hhutxQOMKCB6ArnQbJoicEu9LO91Rl--PjRQ9TGrj7_VKsiSWMD__siFndLXR7sDYrQmjIYVMzW6TMlK7kTytM65uNx3gd8rjt625uPrOHGSPfHWO
NeALS3OIf1WOthbLihQuPp0ml7EhU6tRGue1wTmgMLkKOfurXNImSb8OjPtl6GpKT6wLh2qM5JC6mohnsciW9LX5QejIjbLbaB6eJ6lBMLNRngravR_sKCgt
gjMstxUabJ_8VToILlxPs40gO2KDCaeLhVpN7XQLRnMfRHktbfL_De9KoyglRUltBMdb3t8VjwILhmMfZ9L_DgfQ-RNjGzFA7-G-Raah_sni7qf1At-GFwIQ
LhxslhUrvj8sjg9sOokcRcp5j7sjc6CzrcCzrcCzrcCzrcCzrcCzrcETK8_rMD-ROptMOptMOptMOptMOptMOptMOptMOptMqMhvDwoZru-KVy0wMdtaxTJo
NkjezPcojxL-JjdEsaB_BmsqMrcpsTEAsesiFTWdAshBjraxrrhCm8g3l8Er9mChGQjehSx0IgYjeZMPWPLGMq5hymPMmY0hMYypi1AqWjOM3Ao4GLQqPZEm
4hI2rXviOdth8ADrqAp5R6ATQLUnzc0JAs6GDQpLsLUi-DgJj_O4JB0IQgjWRTw-RaMjilK28rW9jPMmUfjO2OCiOgr6i1Aq4bR28DEjznki1AsgDRs01Qsu
rLn-KIjinVXA66HHAoOry13EHWqhvgBLLjzghhoe5RPYV2FKLiPAhYqEih0LascrrRUQ9zHMrOg9XDhAMlcr5RRopyOYREMVZSfMVcsLhVpNdh2LNrjbA_zi
LBRoNtlALlvhJzZAV-q9Mp61K5jPA_ziLBRoNtl2LlvhJzdAFnkLhVpQAblvhprXA_-rfspbrrRPod_j2LlvPwEobV_QKxRoNtlALlxPA6pbdutALlvhJzdA
Fnl5hVopaMyLhMrHjlBFHfxrCepMsTZeLgtQQblvhps-DHf4exPqQtNsjbmTFR_3DggrHtjdyBLdgK-q9EjueQgarvxvMMqvrkBi6vBQpzQQ9zYNhItODoN_
P2sVYupQ5ws3K5J6sPZZXpNrMUPM_axbl_OUrYiHhEmzmwzj_R0cAvrlxOIYSi_6aX_MnhJYdj6exSDgYMaj6amy6_CFg-TPQp2nf4-RXMN5Wr2jjaGhlQZy
ip47WdLo4Ehi7uAr1vFEHREEPEfnXMFDja92UzrQlIsIr5wpzcWB9RzW7PUj5L--QYtEbajiNx6sO4icjR-rZcYhnkM_isPRERx-kRL2KVUeBLfxj0sI9bR2
dj4z6z5QR9_uzZjh3JiOSV-WTKJRBjUlhBvSjcDyGQjjcz0sjs9jdzPgMoS_hJriwCFQ3jhve7ys3ZWVjaqgCBx4_0y
}

sprite $image253 [118x136/16z] {
xTVdRWD730JWgrjOylwF6n_WCWxMkZ6uOfhchyk79J64j3pEtkgw96SjlKi_Sz7pZNoBj3tFt9lqzqZTSiojIl-AzBAcBFGT_NAFPwF7NqrklV65OXBMknOq
CT2YzIph_BRyxBPZMRRIPUQUZuRcsAs5hp7VbblswvVAEhCjVCv9RU43OmwsXG_MATuMFi7rhl9RD7ujjz94aGskbpyBek0cZBczQqAmyrhqfMMEMLJVjS2O
eKMygW9kUBsqgXF7t0zUrSJreggQE6PHPBDQTAbcQMD6rVtTJMWHgYuzPxseclVIH7DQX6gjjKdEUb6zaZLcLA_81olpMdIdPeqPrVVqPxPeh6Qi5rNCyreq
LXFMEr1JnengXdlUg9F7B3XcL9_eYYcqQAJE7xEektvRBwhySt_bghavgY8tQdpCOdv5uULcOpK-PZHHlSoX6dTneQ2-cuGQ6REQEweNIQWXLymX2gQPKYe_
PXmk1iY1IhfouwhvlUgeniSiO19gt4MJL-FhLVUuoZyN5yghKHU76rVvCIimh1fspIUf_9X5BKT5LyrDCrGSymKcl1NSH1NPb_fIN-eeB_MbljINQd_JMrk-
wYgzPQhmWRPbgOvgxpcgz-txb-0MKfLHtSgomBS6meshBjlohj9kNAtB0YgwJrDTzmLKvhbnrTkoW4guSTNrM41btBZgRLr0_SbjSzNpqa0bdXjLpIyKrPYB
gj5gKzADgvYzsvWLbkLLp2d6FJUkOjRAZZckOhPkZzs9AkQWnnnNCKL9DwvYDh95SPLe4RXjcXflKLnTLcAzyrHSBzkYk8evY2CPLEFhZQlyaOoeWHR5rS2H
3AY18nbG0qSoe0RM6r13BH96FKWDM_JGlLVDVISW-aWogfd31ty8tIAhpHHPkLNDNOOlvLjaPz6k605rREh9A-CZQRNsNGSPgsPkzMQuN8lUrBCRevgvzoq0
udf5zzxQ0nM6UmH1_AXHzJnjhA9f9GxYaRHQXsgyBVoHH3NU5lv8eigt9NeaKUNR4ZoIg4RQmXz9LCDjuOyagbnRukj5LOcsJ6tHfQeHRPcxNZUlMmg8HzBz
ZpE5moDfU8lonboMt-HF
}

