sprite $image104 [236x164/16z] {
vDYrOS1044JHz9t6q7-rfinhY8mxluCd7T__Gd1V4K2F57gaAAAYHmezKYYYqYE57YdqI3arr9EKI5r9UgH9oV1zgKUQL0pVQMMhT5g1ZSDtMW6i-wdJ2W0M
I3-n6gsXcbhCjaZdZ3rWja4wjPUFsYA5wrCfhA7YElmhh6-jHmezKYYYqYE57YaKKT4ZHO_KwP4cBTGhIOyqAHc-B-sddYl3YhN3zxKLs2aTLW3BfEVpjzN5
rDoRRP7YaLWpKOuSX85e0mA1zlh_lzsCLNCGAqCYRDDx9dM-KhVLrgGvRgkBIBba8een4b4kF3bQgQRMezP24PyLgNYVJafgQoafP-MqbBABjjLtMaRQWPgu
_EFOre6Ma391DQ3D8JZyV1RjBEbOaHVGBY7L-Qw7zUKquEUYXQFr1pMYrxPLKmm3s4jZMpuqZvfxW5ICJRiwjaKrILgf8ytVtKFXojYMXsP8QyABiktnj2DD
fQJBObiw7OCQkDeg0PrYBX_AoVB2yRIrzAgdeDfZ3LHKwS5UpgILnXqhy_nZgOpphFPLqLNRLaJg0RG1JuKVsBUK74xSjlAPLLejFUtSMEDuyoBSIHDs2lca
JmbaK-CvscusOLmSTq7LIUTenTPFQhBAN6mPdOfH7CsWXjs3YWxRjlBhAzQvs1QeJ1CN7TOEAqThqdHCRENJXRLZjMBhPGLPUwQtQs_VbBj9pyQs6HVMZjKV
MsKrQnDX92Kl_QIdOjl4_EdLdjLlPDYm9M0Wer7CRblvyi8gdzHSjD5w9-K8M-D64V8Td9oagcQmpXgv6CQaRv6QZOBS9RaZbPxqbyWXj14-AMjErgIJ8xPD
J59zN8bgDhOCbvGisTtH5zjcsRSflI5h__3GnLw5lb7OtP6cpkRoosBr6pbZHdQZiDyJnp99bTLFEp_PGQEOlqUfVMrMVsmvO4R1Q1JpTqRvPRBEnpRD-jTk
53H3QhBE6vamfPXD-wOf-zgiyxGq7LWZg6MIr6QTZoqd7AkG9-qxPlN7jaGSAE9vqZ6htyWvmA_ZzyoOjRqnyeYMwHZx-eCgDke_CKH0oCrdvFdOpkyPc_IV
nLgnYGqZNnNRn8UJsgmC5Is9xVoUiL5jrWmWH01HLiGsv1Fi-swkLJW0eheqjiJda7wTrohIeixrcjZE5y81gSqg4KYRcQ_Ujk7ue8vO6K0HLGswVww8xGb1
7R8AFM7LXNagjklsp9XLONM_GXNRoR6DV8vznwoI0DGxQrJO4sCRocds7REs28K5G58ZmER-EURTbguWjLdvXX6qIqGDAzt0QvsAxO8zCsP5VJGAoK1eDzZj
MtakjbSLmX_0gc4ZG2BjfHWh_axL4TihzioOLf5oawWcvYSiuwlO5cTiYIyaLHdb7u_oNm0KWzLdP4wNxfanBKCLksPXiFfYU-MU6SEsf1RhciN6AePSiQKb
fFPe4n2gIBitYsQm-cDxofxnqwgeY3wCiy7gD_A2e8vf8uhebjspLY_j0liQCbX1RQDiEzOIs1NRzQGsBT_t3tW_Lo0wOhlAlcFQ6g6g-xm6W2-ARPCnwJni
8sMLFIi1-NlxXnVOrpTQWlqSBcfYxzlUUb8xjbKCrWfWk7_kMb08lRHtLZkmx7pRMpzKbSbQxC0cXEAAxNfIcxRgoqaVs2HQh017RRoW47ffQzBhq2wm6G19
fkg8xQAWZcavzkVYe9SAlSHb83ksxNBxsh1gMw0Bh8utw7G3UsAxdjIcRHde0wiMrd-s-ZoEBI-mhxCsze5L2zzP4PjlswuVgafiQM0hW2ZAoa5XNR4Taowb
9Q1a05bP8Iq2oLMIntjcCMq1AAY5bLMQNgTITMpRGL0NqrPiIl9W5Tg-16XK6xavxBiIDk2cyiAgjHd33mdghryEqfMqX9lQdJLLoHjbrpaC8_CDR9rz_KUQ
9ChwSh1vtD9j8olOOOU72siZFrbLJN0tSJDYUtVhCllwQsEKEsjKtY3AIYB2njlUdSn1kfpsoIgLz0LUcTNayGsh9wZhQPNrBW04L0tqMzRnKDThoCe03LWT
f6iqP2LWmDgMa_eloJqhMvyM_2_NBWubXg4eXhumH_rN-s6OJAk9VTN1sUjcTGSSNpjsJzQviZRT2cI1dP-jhTcKQENGUQoZMPzcvUWvhNDbJOgL779PExDu
Avdai8vcRQGL85DjTxlVugn0ljgn_RTsSLQ0NBMtfXWhK0Is2Lk1ChIzmvgvrBtxkQq01Mc7oca52iFElTjQdhPiAoXPKRA2aXMKhA1aHSaAIbPGieAI5IKh
A5b1oOgI5PwiW83s9XNGVaNw2m
}

