sprite $image339 [330x192/16z] {
xTphTiAu3iNnGbE8zfR9-p_jEJDUq0Yiqg2wSJFn_ylSRxzbEG6xC_sf8FzqcNvOxopNEiNFaZbsZNXotzX5OerIr542NI2ci6KFyaNeDc77-ikoEyOjEsJS
iYVBkdIfs7eimnFBtc2b4DukUtUEkSY8zt3FkCnocFpwHqCOnqMKw7JEOCCfjbrsnvZbEDdw1ebdVRyiUnUvIP9nIdH8Wq7jbk56Iy4qICYoV-Y1sC1qU1j0
n2txOC-IRuSJ-eX77QtaFnr7BhVi7tgaZFzAvjw5SACcYAclouluac-tFa3NCQN-DR1Dv9baxd0cSPUct2pPF_H05aZURPTAQhe6MHHtz6MkBsaR95FEYaQo
7qy8badc3YSoEqOa1VlR87t9t16QOfAv7NmqN2fvM22vln4NgIMvxsK9QI2Psu5ZDKdivj4pBe44gOU8v8vESo4B0aZ8yAfazUE9xJiYKs9yVov9b8wBBCVz
E5ujvNpyMb8_oG38hhu7baM1_AGavEFmXIIHCuXxePI5WJIMm3YuaZ3jwZHN5WVoqV9OI2e-8_TaUP6N9Mcav7IubwI5351kzeq84f1ys2wDf1f7LUfkbgM8
12IB4N-_IHesJKcfv-Eu1qlAgm5mBS_l3v9CAML9SspsttsCo-l1foI4LfAQPibyR5PzMMxVyIjBwWoP7Ora_auTy2DbqvQ2i2DyIqrg7Atairi6rAHRFe4S
8758dn9ACzWvHPQyDe3kkRYHtDw53Ga4asjPE5AovDp9M7B-SrMMj6r76qZV4iRIEa9coUAMWUfihYARj8G40mZN4dArPFfC8L9AvZSYcZ_n9KcCc_rek7HP
0YH1lNEqahOFK5D0CdVPvc23U6N4azh1zYKp9LDO4jYWes-9hondIK8a9BcPxN8KYL1YwR9CQWOx8BcPTIcnG8UI7cLICzZr9MqRT2mjGHGZJcMMp8vhI0es
vbXQWYZVY3GfGAgtgUfuh2-Psnwa1IHHR9VKfCXixZTmaDDtafHG6tEqbY3AHqzsT3BVNShmL980jc0fjG9PO96gz1dAOpDVKf6JKDWO9EQziTI5-1N7Phua
aGjRZbjop9djSbdbiTcXb5JC4NztMQAIOqvUj7IFpN8dUf2QAB7mnnrX62EMl5LS93hHEHWFFC9Nihn8l6_kHN6H9KlAwtPvOdamdc4btldFBaXJS5c2lkLm
bLGxsCbA0X9eAuwbPVXaV1ojP7Qqal47-JgEyNE6w8W37YL8m4fIx-u00mXJGlxScmz8_d1Pukd9U4fAv_nCO6g-BAL2e0eMMGPFnfFwvsUcrfQKIf8VXpF3
bZ3vbd3Epr3Mxer8f9faFWNyrXAU9HQSvWBK9uwDBKLgIjfB4twIqOZGoNWvsFKiqTQnb7pwVr-XCekv8uxdnxdMCHMEhIsbigH_BygE9a64JdEvOB1jb41e
wrXAkjT8MHmYyYLBzTzy_3IfX49RnrBo_Xef0Nfd1Yzjb-fia7vPNMKbIiYlIjfxKLJLhqvVG2ozIAGB1jikVWaN_iwdlgJTBgd9nl39k2vpXBaK6AxHOFkI
kG7VdmY2nBqi7aQSYI1rwM1Na9G_9PaRNKb_MTfVXx7Kf11WgMD0Ccw9zfA-9SgJSMgwuYuQR2kvLKjGXwYam3yPlpyON-0Obem_niU_9PdTd6UFAiswNJ3O
SSdu5TPpUya5RqGmwv4B7Kl9U0qUF00v7eEIrjAF140k6EowaZAkkrsQInDXoUV74-JNbanEAfK2LboNTwU0poGL02IoB9a3G6-mwqlQLgGiBqtuaaHE0fPa
3eLbTlGbDsZvS0fuFlgIc7lP4fmjIUiOa6ptw8dVYnf3zw90mb-JzvRKL5MoFMLvq2_3eoIDeohanH6d3G2DOpN9zXzwt4iJHokfzpkRaLneIQgbB1mzoGrQ
ybfvZVGgoJj78xdOyihtcMf0ilK7oFYzg8-tyGhtyCgYUFLcDHyeDQqlcQlmTLleNfHOoUnOI2vRbgInz2MLwafkwD63d6j9DSDzVpZucgNT8Lr99G2k8IbZ
HSlbzwBouyMvXh8uW7ZSYhrzKilRW1kpXAsqLET-6G8_JygICZra_a41oTPFSPXSI_SQogk1e0tUFgb9hvO1oGQMWNjHnJMKGE1TdkGuy6Qf0SdcZnxmAqkG
Y0vssGB9jxUJNhTBQfRSmB9SV2-gk83xYvBvXFrpNwRajhKiGNnfgHhO8AEI__IEcoKQIjOVSIDPEjQNp7qmwLgKc9O6_DHIpSV3DIJpXIHToN9wfV67swLg
PB3ZahcZQ29o3HphZpXlaX77k6HkGDA0PU0eV0LBJGIfgX1PNTAy4Q7X1bc6borvknS5aIQIURiaSkq7E_v6fERbiOLaxbtCYBTqZ2zBQYAahMHku7N4sqB6
jqjLY3ILjDibIRHrZ2zBY3ILj1sJLfHizvEYxIKF5IKnLMp7afpgDkvLSgeVzYXvcNubD984ufBj7VqQIH9e88dfDpkta2IofIyfloKv_NPejIRXIoOClo4v
hH4QhKd0ls6bSgmjYMcbLfQ4jNGaavuFLIMdzKAJVTAzWw44DF6ZdkIqRh9E1XBmRg9cBL0Jtkj8ObgzjIJjVDjzqfwuPSln-7D9J2qQLf34_N3VhqcTgG2c
fAV33oMdLicwbW3LG5f70Fbt3J-HF4yDMuFIMbATkqRubDGax_RxoQquvbPSbfpNf0Bp5ZbBKfEEXv3ar3wiQ0dgROF4pH99PqbI4qylI-8osVQmNMR9g-FD
4fejgIbTtvCm6Cd0Ujp3TadD6oHmHqdLRFXv9Ljbo9B0bY1puqhBKgsZjKnAp6dIB7cj_XlazhTBXNKiH_mQgVDq0wY_7hS_uY9GrnBKHEG82CWP4Dp2WhJ9
6a6LSACg0H9BZ-Adt7ujGSzI142UQKeH473SmNOvRug59Kb86H20tCk89_gMuWMyk47s4NS3y6mzzX6dD-Ak8xvRa7t4lxS42B71S-phyjc8ZwVJkDt1jW6D
jal9dJy-FauZOlTJ-XlH_5v--WVopAI8EVOFFIHmWnHDYSM3PgjTLdqZ8kVPFabAYe1ZVxi4Y5bkbAG8VodUHrpcb0W-iVkZ1v4lSxjbyDImZtYySGhNBUiF
ThUSmlKFaFM_g-ZhajD_l8qDTly0EUsZlXwhXGr0zcLvcVOM-dgiLN_Gr0jzGLOBtR5MGFzeMAknseBiLNFiNPe_iRjbwTXhEzZzZMZeR6xLrcCFrI1xzHuq
lMhhiOTg2xA7QewzUeFTgmRP6wiDTg_UUknLMv2zePfZ3zK6k_S77VyF
}

