sprite $image246 [241x173/16z] {
vDU9SgCy4CJnxrockqVPzt_QdAG2QQjiQkI0sNzTUoRvbKO3_dt_01BuVTgSYxV8Fu9B4dCadixE3H2B29xyT66H_vtsT8cByQINsRWcFZ7NoOXJSK436vau
rOFtUZpB-dBjgIypGTxiLMRxexXldNDNUMJEdUczgX_pitRINUNJFDSUKnpOpdtacUPMxhA8X_DMk4AyDftJwznaV7O-BvMMOjcvkCpqubiyZpSlnV1EuQNI
ymC-Fhd6JOHrQ3Dht5Jqc_uweBV0zO7s7dASZTlTM1IERTwqcgyFD1jrYNoKoLPfcdrZ8J5D8HrrielJx0ETdDv2AWveVYfEisyiQPf3yd1a5gVP1vevVSMZ
aQl7wniB6TCo9Whamt5ze1FJkf2EGgulAzzOucJro4-7srRCt7Z0r7GfIB7tATUNrHpi0blzXHqFTxmfky2Tk2UPjTlhtlu5lhwmUOXnpjlYzGky_y9cxVOk
u-e2cxT0FjpnkZTiOVN84TwqerTvMoAMOE4ATPStx1XtlCBAIvfi8nbtyBBiRH-zUrTWJTxMPzJJqSQvpQN8RzxWjAbWmi308RQLS_5Hh7FLzeMDmtZR5vUO
2nFNoS2UNkSs4GjlbOoKY_Vx9EZS963W8facnaxlpiuLp5idqydOSPoR7Q-1dLnTs01tyZOxtevtzC86TlSIgpXKx6G0F_ussHO9gvZpppVkAaEgYEjlawr_
lDHhDjj35hQJntjrrIiQLqaJ3oS3kB_NkIcuLvcSC_2uPnI0-7alZVjUpZMPUE0p2i0FUyKrrsi67lcC0i0xUtsSdKjbQYuvMEpa6xt_rRtiU7zDsTeNUFps
abRYltxcVDMRvgPiN-0FCMdYKGiRDnroLBsf_kNDrdBnctolSUXWmzRrlRm-pajgfdhbuAky5cFqFFlrzUF5hsWjDu0hvDWWZgfNbxZAN5nUBn5LidkTFFvy
_NZdthcfFlYhCZcilZZ6UK6xk_rI-8WiB-omJ3pcVFsp0YNbz8jsjbwsb3w-6g96ZkYGEVnyXMzHIZ4Th7wfA8d3wZwV_gjvax18kxpNgsmlzrBiZ7MCyJfv
QuM5xLvaQt9ntIkYqsOnFd-wpMG7__gb6MpYeXTpTN8M5hRDCzJcDMXYN8bfTSQvEDTD0AZCjd5zkJVQQq-y_7Ywe_UbMxjRKjpNWG1-0IHnTuky_zkU6YZL
1jC61Vx56QQlThAVlvKZMnwgHGP392MfSa5GQD1nFWVw3Vby1GCxlQfvwsHCSqJiEN1MJXnt3t9x8ecIjmVpiHFbTHrI1yQkXhtu6762IUpswf4Nb9PfgXQv
Fw68MPzM8DUzMp5HzUhvSeOYS3WS9i6HdyxAOkaRKjxRA8wyxPnWJtxHsnWHMgQPeOVhUfbQX1C7IkB5UEU54JJUhiIEp26OQ8-YoCWqhyAih200Kg44LtEz
BFJUx5ly5zIyxN4G6NibxsTblzO3-xo48g9vS9RuJ4UcRBfsvGE_y84Dg3n3xKhy1CxRbxWdKpuXZ9d2F2susW1aNT4NkJ0hlmZMEMJgsvKuU4_UxsM4ZeV3
KUXgtGw7GyE6B59bS5lUJ3DWiGkWGV3mnMsdKul0RSF6yN1iaG-1V7cBuFRVWzqB9PzAfzg2uoUYpArcBIf-JAGfX8At8SLlWvLUsHsAhysD8LJ4bwuGtkjA
N1I7sdCnOHu6NvqRzI_42Dmksw_AO2gav-08s6DpcnSaOzERaRz08XBgYbotZy1KRh_6wy2kRTvpWxQioqyNPlTKfyDXPlzhEPrcl4wE4JYYx4qmxgfSEd4e
8dWwdXZSoguxr1JiJjZJuN00Nxxd2om-aB2Kl522Mqko4uy6XhYagpulpm15T6ypvwafzgthXb1bK2w1eGGJxK8EEV1mO61au1vgj6tLoPYNd30elk-Dsv4O
IRu1T-KrOi4y3C7jKDhLh-EIkwxLsalU1AVubZmkBowhwz-_6Fd3RMjMFaOUp-tL40hxaXkKsqjUgRi3s997vSrZyuctTLMqu_44tD_sp2tfAD_p0GoPGRar
02IUYRqtmHsPLxBXvkke-NXSGgOBKxWV7cPXv_srbhb5oDLRLtfxoIj_1G0gH4d2wBsL8g9hIcgDTmrRysbcQETbhkB9Y15jfzU3kPrg05iNrBkm8gCH5ACY
Ir9fKwvx4xpIa7t6NPXsJ8WCh5U1qzAHWKxg8-u0KmvS5mFSzERDQn0I2hSz6LtlDu4iT_sp0vJQrlVGAnbmcTo3D1spIXbGN3Qj6G-7Q2huZomLxmS2RQiR
Uw5DOYs82tVkqQ_klEsflXtCfKCfLF1Ijw_9qCiRhzRNnTcKk3JTzQ_bT5eKgDvmHc3_42L9Lmx6ODs6gn7NoOgCxBO5ZoJGa_NMg1netej-vajllSZvPuwx
C9xiHGnDyvPCYNZhyo52gtYbn7gn8yy_sOXvRJ7mjpt3JeNJ0bjwK-GQs7dPr_UytaJFYumBkDkZiBtjsHnR7hsrOWZj_agalKIEPi2GHWkwlgp1jZHURulz
RS_2UgCY-exDNEp0pdUuFVD6TE1QxyBrMHRQt_RKTwFxXu2ulrzVzxMkCNHU2rvHwrqU799Y00Q9koBJLrxOJGQkltwm6oaSkBv14SkyW1tusR5vQhTaySck
3EpWjks0wxqUx7kNMzb-cNAuOtEQWDfYttUPYvPUqYzd0oxqhif8WOUGRiTr0ND9Lycu-MKmtZ6ulgpjPE3ZNz0C1S1-v0cbVerRBmLrYG9uFTV484a1kyZz
e85fXbiJujnfBBVp6gu1ruhimH6SbngPMUB-PcWYpA_DyzYOZ5Rm6d1HxC6A49YAsWlQbrqHSZrGIzDuNUVAAd0Bu1gP9DLrvr80k95uV1w3uPRAwy7L3Ggc
n4d63Yu3Cv1V33PmFZg7eEtshizpBXmraqpMnOmGfWKtnSnB3pDstSsDPdekS2lXCp9GsQzTxTGWT0TFIAtrPFKyTEKjUDTwIaKUWob9gExAkZkFePkra_jU
TwwBFHbZxpmjYb3jSXln4qmYgf_4hdFhmRqOhkkQGCi577IDwn8KAkyovgh2tL_aKX2XZjNfEBmTA7YhtFqvlq3sWwzVdt3VP7-xlCdzK97h0mR41TrY5pxE
hHUv7e20M_VBgS5SZxW0GwwAtDUBZ1eiGq0Hzkf0SpF8LxddzJy9gaK6GBCgsQPfYGYDjgYdP90Lx_gVXIKoC4spcu04oFLiiB8RuSFSUlEYq6XW6EyuU3fp
WO-uCjpF5HaQV6y9UT0qeRB2zU9wxiV92MFR5P0e5DUbndqzSkBzGUb_1LMkripdYspgRMwj5jFPzdDLuRuVrCbeyynx6BJCF-3W5t1taTMc2QQ5AQHoOsQL
--brZV7d8bIQA-hSzAwVovcsoXuc50wW-xbQFnhLo0ch1x-kkXaMo3qVU9khvFuQCiPSFjsBojpVJmQdQTBZQtlyRcwIYuDK42XiHh-RwnksBxFi75Zdgi3z
K8ha2uL3xpTmCmjzi7it-ltSp8YCelTxgfi1tp3ZgxYPyyjaV1qtmzVC3xmot5zQvRgPGwoq_lxi9MFipUf-BLdgq037tApkrvBJHWB8huVQEAzV5Gyk9a9Q
lovu0uprE_CIE7HUlpTxmH6AzRkpjyBhzwSEDjNzSl8Vhgu_SlxHwley0Qz_CE8VvlhyRQxF_qtxFm
}

