sprite $image72 [223x162/16z] {
tPlhVkCw2CIjkm0vVV-ttTfuupgunUJsKpnVpzdT_0CZnAZzUgSGllLrKW7hd7m8L-7fu2gmpWc8SAjwBjD9NSvQkHETCHVuGtZUqh7gUU5Ob_F2iSv0Tp8B
0kkSW0HMVTeDxBI0SAVg2KwKx7nH7FYvS3KCtmfL0VnGkZWiYfzeGT3wShZAPHDW_t353nlvyaby5JNJ2HaisBdfac1JB8WVDGm4c6x1pu2Jflim2ogJBWgY
mnQ4tk4WkK5NCbYmvs7mOHPKRs27vRiR4XVz1hObS9k2tHOsAXRiUnYuqi86jjNR_oFrioffgzjjRHADjtXZos98z04u09XEp83ZIBX1TaXjfAXTObRrb84X
KLf9QXiR0cpn0B2D3VmAXmqxY9lWW9364GDpv6yA0c2yLG0CMBZE7iPHu0d0Jc8Y_kIJ0oDDVGdxU31tQ9eF7Wdt_WwDS5mqbMQjYSIx0cAciH724NMKpL9Z
k3_mkCvSu6F2Fk0Oa10ql0bGmBqTiC1zql7iwg1qKa71iwWJE3lU-piKeIyyrkMjaywErmKWF4UrPFTiFC0U-hBcu9pSq7tCS4orlWQGu66Lk999-LHrkFZd
hbjVqvSrX0gAgcIJX5bRhPHT5ru01r4940nPY_kZXCMjw_up0UkXgC7bX-4OyCZV4PvcmOX7yprV3C6xDQmMSTDpXWHQSkUmF-EiIigNzBHdGLlkxF9kacHN
t5k9AHsFc_3nILS4N2CKT6wGSY4LG292A74NF-nkZ1YEFmk2JcSw2-FkckttIaFZJr4DUltMJ6EhkuU4CNS6JaXKtwM9hJKYGaGYQlCQB_-_3Fk01WkYKZb3
xhmB1raq7OwtDSOvg11Dx2f88Tai2FUKhkpbpeH7JlFfMy3zJttx_uQqfrnAYOFXJS9-0vDzsMY_o8AkuQzP6lDPPRSW6b_-tQyQRaGhdH0si5FPBGW6qncL
DdIIpm-Fo5S5q6Owkoh2Nw8yFAO2logQXu5TshvT7gjUKV8qD3qWsvKLllI8zqfJNrtWRn4-1XWCsQvDSZH98I4UUEXvG1lpwsCa_QAmTrbGuKOYvVyXSIco
JGOF6ocNxpRkINu2pq-YwWiEJKBjVoDvtQJsYuBaEqoNsfva_nH-4bNwxbl4Gkt_X20xVryeJu2Z0zKH6kw3AjoATyI2ujgEkshvs8-DbI27M3FiALfVhdZ7
EhJbGvSYR74lxjiIrkIFtN2IM2eEmp6U0H3ZaRBGOZ-vhkSoAQVWXXt5HcfVvcDzAV0ETkYHy0eRrq-Jlbg8SE3GC1W5dW5Gf2rfZo-RwV8DdRmpUHWDVIdn
3Ww9fDxQiOt6wuY7dK-ErC1lXW7gmq3WcG4n_8H39I1H978DqIscOQ3ZMUvf-RUlT2hpGK0tdnT_TCl16vYW4tWM2ueSK7wNxS2o64hRMaeU5MWO1WgUmO91
Mbqs2vRm5rl6KJilSC8da-aadfHQm0DM9_veERYTCPY1_pE28ZGC0mNFqA6DG1LYuo-sRDZAyebQGmHTvhwKUFO28XmI8hLsWxUarWOsQrzAlE86dy00Q11k
XoNQoEnm4g_ylzMz130PLdXJNnx5yzSjNrYmCpm9f-FXUX51Om7jUEN5VIdnAX_NS_teLjWP7iEPyIBdVbdoOKzuFEdiU9K8tJ0uf2S0rde8hxoWT18FviYS
YF9IFaHyg4EJ6wAELyFWiXtEZ4SyZvWp4ALfKxK1oXZ1PGKlYQS2Gr-Qy08t9n64mI4iYvYjG-MQxSiktcqI60s_Fd0VNbxFbEAXNEEDEm2ZY9i4diY9ag4l
xNXyfdXY8Krup6SU4ZBntSEhKOHI1ZWxtfoX5284MXpeAay9Cs0MYQ_04_bbiPdEZeTkvij31E9VHmEAV9ng7Qh_h5JSLig9d6maa-diU3pw7ASVStTwm3d5
0P-jkwxfMJ2YjjMYWBFZqPfE0lUggzDyc3hLLntG_YmeyqkzB-ruaWyAOM1BX86dH241gBr9s490VJEmw-kBVchvoWCvNp7o_bSb7WirG8fFU4761-0cNJOV
EVjvs8LlHeWBrXKFZ1sgXDMSNxuGZdLRb6LtJtm0rXKls2rOtE-cgyrWEgCQesq0nP2V-FmFl6dw6Zkq9Gcs_bBjoqotaG3ayd54KLUylMLN_Vun3bBnrQPJ
0EDy8PxmuWRFav3TWi4q3EnmEjywcFsCLmMUpOBl6WPiEXtmsbC1T_2ATKYi5apj7Nsf0_v_MqCdchCElbej6CGByblX91zcJbwym8kysvllQHvUEmnqjPlF
l5pMuayyd7isWGLm6XBmqXlOGT5MJEFmYiUyXVoGq3e5tz-NKXUwKUBroFt7k_QiosYoO0Tmat1lIhXXmQlhpBUjIY_gIpBIoIbu7SnXyI0mtcp2Pm2-s7HI
-rC-NgDG-e_igZdIVdzVIk7UhbkMWsN54tpc0YAz7Ku2OdBSYNomC5xAZezL0VWEqw46OEjGW7MPMF08FBUiuCD--r82RkDwNF4879yqDi37uIvc57qANW-M
5O_IKhwQYvY2B-jB0u3v3AqRF63tfK5_LNh_CB03reWRF9gwiwBVFKKHUpET3aWIBwCRM8MsmWw6WIxSnGl8UCjMw9J4ztsRWLrDu4r0XN-DA_83w3Gc7900
xB0lfNOpUpSmtaGP4DnyZ8ep53iQ1gOuXfMNd11vaGyk2y3UJATtwFeEL9UrmaEQt1T-MvKUoy3U0oZp9eyv8qny3Y2a_SINi3_JwNcJdwTT7dn5vYEKUAmU
JQSlku2ymaSCp7V5WoBmEYoTFWNPUJJp-GLF1g8Tmya2oZbHcBAiUDjjgLyu7N12oln31nky0GLU_t0Ia8D2FmCfU8PXq0yVk64HA7XTbqxFqz20ro-S1CnB
rfiKl4xxKWSimGUSiRp4-nWuoIUF6RmRhoSu2RZcIzcEnpUmlW5vl8SQx7Zjgqir4HYo1Dudmad0wkx0wvPDTYXufdDqLVzmzYcO3k9Hzt1ormq-uZ6yphaa
e9Go33uTy2Ch9uKslA-Fau8du4u1-BccaxeSm6jV7woguNrzk0IUW3iJe80x5-2fwEGK573dAg20EnUWe3iNu6dXs89lXli7
}

