sprite $image422 [91x138/16z] {
jDK93jim34HHBP4ipb3tFsuNBpL19sZDkFy03yh0ODApbQ4gh_GVwfpwgv6VXb-OkZRnbPsx-zrLfXvDoIqyInEHfUwlBUl8KqqaOt0TijOtb7qVsOGUscAH
FxLE9VNIbDYRAMS0jzHL8dGX82QyisUFqi3VR8dIfCFLqunjlJtJhUBjsAkFt2fVlxe8z-mgLDBQSmG-wXLnE5ILrfuiT-K6WZOGA-nekIjNqVMXbWPsy9Gd
xjycpCsmzaaVC5lW7kiU0MDJJLEN7FXlEgEduoEdlEZK3xQX0oEtwpqsTkmc-V-cwxDLutGUQcHlsqz3bnpVmjEgXXxbvXOxSCr_qA-xzvF0RlXewC2b6yGQ
_u6-jtDUMJhxaLSNueWVQOPf-TLfEthgSPwctgCpPEizhJgmqe5pr-G8lDZag2bt43grvtjpB786JrFgVX6fezoz73OGzYWJvm2lcg9ZN9yzIiafN9TFz4HD
tzJnZdQVGgX5v2tjxsPSzlGKjqLm3Iz3wUxcGpkJwFbRkLtWtWHOIlgsAhwMdgc8hwQ76WuUvIcvU_bdU-Lj0r4Cmr0gEUq_y7MNQhz2mFS03uJCOBV8-KUU
ryZsJzQrDp5oKdUMOUH_T_ouxceCKzGV3b5_k2I9IRXZeWiJFOM9Tapqa2XFsqrqON-eXObsJdGUIhJcZpsmKuUeKoy1fqRkKTWzD35_s88wJtBEUW6DhQGw
K5DB0_j5JImmMjWlseTy2ZK8DUR1USymxwsMtfiTRRsBgzJa4XFSviRJrhzXr1D64cqRoxcpQ7uPJt4vppuLqhITEg8drwch9nghQmFH-mTDTUfiWuwMw0Js
YqTNJpItkgC_6XWP7Br9DBTVYQ8Vz6w9heMX9S-nza7GaYngxdrIpFESbz4l
}

