sprite $image57 [118x242/16z] {
nD05SWHG20JHU48ZU__JnjtvCjjbbBuQ3fyhxBw3DkmfXARRMzATQjU-fXWgP-t7BhQPPRyb6AfoiR-xsR5Jxl9VbgKgnt2XuVeojSLQBLJbRuQkQujK_Lxq
x8igVpE0VYyCkxEg_Csy97qpoDqNLVvcc7Qf9MhVNQIcjrnOeNgrzrxFgnaGqMEPLIF1oxjpRKfz0Ca7EJUvBn2ybVaY1rtsfgNwcnl50_XoUDDjgMzinHsh
TQBaA0X5OJWOD-xY-p_kP6ueAaSyJMZxpbfRVoM_856s_kV-xkLgTTLhsVgVkovNOzgovJywvewfnNMjPN6Xx-T55Lq0uN7lkwWYQneW9BwHbwle5WSJwzyy
hhXfKHjNhNm78F5VkA9-cBQgiishzWUkYDhXe69UkddbnY7vZeegkk6WR7hpYYDcRvYx2iTotRn3RgCUhbIjczSXiTxzvakyJaNbBjcy8-vnxXeg7xPvdR3z
vnLJxChp1WYRTpWlxShP0a9Yrr6NT-Nk2pmd7ZwjIbThLEwQjub7MTwLk-70-JoUL_mmeZ9MsythOsvylhrZeKiMMhzt9PxJJEki-IlN0mHPlcH5pUMKzVcO
vHiNDszf_OshvkxH5TH7MkKRrkpYVEwvOlv_H4lNghvcsXh8pD3bcvUxelwUU2STrTSyymcDF_rlVXqIj4pRjSmig9ePijfkNXXgHbVNInNpchhx9MkVPN7Q
e5MDsrghHjwTgE3YguJJ1ALTos1UKmCMN2rbhrXSNEYgeC8iecMgIh_vn1KmIrU3hYkOaRSyh9gfAMM5ZNaxpUSrrwV5l5R-8YuRrIirZd_yOViK6EIjJqk6
cbILvaUigN2GrmZANMMgkbsv2yaxmgfIDJwl9tLVXEJjkcXozNnCgCnnBf6yFHVDhxlkgJmPoTiPGBaQjpLuqFfalyshCFskkAeixzZqkpwR9oDvRwiYHjJo
PB_8Ez0Lr4xUJUwfVfWIzMvUhi8j75JCkxLvvLPNPLsdRRkNbwjAkyuvozB9-qjLtOseoxRad6xbvSzAkwRzkUPwj-WSpkDTdNITjxsgdSDvL5NX-tNRvrD8
WQEQv-rtLQh6eBfFss1UUblJxzKjIhQxTyutklRL8AJDEu5aNLL4nzGuhUIS_5Frm-tdhdRkEkMbexu6yw8QrE7ALJ4_xAIAxC-UMlA2YkuHxqld5Wwgo3Rr
rCYxNAlsTjswjpLKuNr1DMrr9LQHcNIDVwnp2szLoVErEhdjKyshfKQwMj-WUxSrL24lgEwsVkPDgE9hxFIsHbJ82wgxBX-dv9BQhdMPXxgQnZANlAZ6vB8I
MLNpFE63leiQKqtRhk6v5tScgjkUYlhVlLnVflf5r-3Yvs9UL2FlMmq1niQxgkXRTLF8UrRTffTQhzJeTheQLQkx_wY-N5JTe-lHwKhLiimvTLGnSWophgPK
hMwUEseE5Ln3bT_29r2XmyBK9Ff2GONZoVajlA-kbwhlAUvIMKvTus_ULKjNK9MeKwEwFG64zRMm-IqSLHbGVMxK-fdZNVMYQyorkdAL7F-igrjFjQekhxZQ
Kyk75RhoMpYgC5MDZxc2IjUNTprSXzL7sirZR9T9-FeojHp3eEQU6Xzpg_iLE3YU1he-ddkSpboDcHNKuQwgeARdOyvnUbohITPo5JUgbgvCLRTprwTiKreb
Lg6CMbLZvyXSycggAhk5Exs5enhNqcdxM6OHLDrplL2XYiSmxre-WwXAdbFaLRjMtRR4LRDmUxSrL6FsclTAhRT4rXLkQ-mMtgeIUTzkgyRe3EhWBPoeaajU
8QfxJg2Ety9RDVB6xYKgtQ-HrN_JrUqZRrwNdZfo2rVNjgjgkONNl77VfYfVNwfUT3NLE272ZRo15lLVhVQX7BSEnG3KQhR42wx-_sjVKJ2wAOIXOPQOycfo
8cD58vmiHdswmkCtDGfLhdzEHAghKP-kSAMcUqnjjPQreTeL7bpXMgq8eV9fYtxEqBtYUvK3PX9gJRLdXMkL9w9N-rUuLwS3JlKhlBJULwrUCw8O5I-xmgDn
-ckLTyB1nhTzQgXq7wzmgkKFDKz4tWbVNsPkYRuLxbJ4p-fykVD1jN-5QvKfgIxOkIMBK3jMk5NNd2_RhdPJnmetAkSBywuLpjq2fVAyMhJAO_XvhrVkMShW
JxLMrjjKHQzoXJESfVbh-rMb-pbzl6k5CzkHRYbDjTOo-HLkxyAdHBDUgV9z3R72xLfhgbblgY5KiSB3hF26clM6KVjMk5PPhr7xLdWebVLg5GlLdXMkLTQx
B_CFTQMQBq-g_IkydUMJ_grcvc2wxyBt3nMjBj6_mfdbFIeUht0-h5S_Fk7KrzCLpgnUvINN5O2zTgvmvh0gBxdumvTrYkuLtdxOIQcyvE8fqRd28veFknt7
r58fVqAgBwvmgRBNp9ReVdmrFyEyv9ftK9KhtAyrvdw-zMlPoz9IAmwknEkwkFiklFcm-xeTNqqrLoBLdXKk_i3diX_7Aay9RAcg5IxLAy4m1wsLlZYRoahL
hN2lqftzYSXwgPeLxbJcQ_QgVb_r2jSgwnNgvjHSuOzKKQzGpLhhw5NKQrI_mhtAUhrgLdY76cNxJiKgrffTuLIrkpPLvj2zHgVAx8jMgrlXNjNrJb8rAzoh
fbwgAvpgrnfLdsEb-h4KftA5E_LHzdczrBpagWXCPeLxrMUzBxdulavohTNtgSVzSRxMQOZlT5o9tQe-hTP2LQ_mlr3rDwCDLCqAxrO1j4whcQfTuLvLHRLE
AwfYnVor2f1bxequTwnmcbP5hMJlR1DLVGnhrPDKAr9blKArApoU1N7zpybclRDVuVqg_b1PxzAnmi_dB91g_bqf7IlyF4y4Wugcc8puN_LbY5RFajyUubiM
IG5vT4XNgp_2__Cbdw5bWBXUuKPDzeLu6a0zRVMzClV_WegdAe20NU5QfOiAlfZzgb_XL9FbLxa-Pw5wvUCwbVMYYdfLiO2y2_SgNLcl_XhN2hl2jKfNrAlO
82jNk5V9-dffvj_85UvL1bcl7HYjy9BBgQPUgKAmPeMVAiNNYuWQ0Rl2lUhhzQfVuHIqYteLZ2Qhr5TzrgkljwcYfVeLVZeM_3GtwmKkka8SmrArsUzwNoqM
d5J2DQgh5rNM6q25ME5MzVNgKGd85IvLdnAwNhd2hUe3NQzUuLxrhgXN1HszgdgHzNhNg4y3rli243vUxQztl9flRwruuiAeZmDHxoYLAI7g7QKo8UeTfZ8G
zGvJcSYDCrIrlr4Ohz8bF4hLRaMj0rNziNfXeAgdrLXLrpjCrHchwenLTOQgEXtgA1S27UjYhCaK6FKS4mYLvh18zHoRfdeE3r8Lw50NmXmMgi8SwaAW8uD0
o_mN
}

