sprite $image255 [236x172/16z] {
vDL7ZWCn34HHIbGgIO3lVrhdL1XwFI3xTLx-JZpz0roT3W5FnocD7miMFPL5BsN1IrdqL1Qzb4KlPS5BMVHK5hsK1IojaXfimKfxaglSOOgKEbIU555gOIlo
fS8MehGb8Id0YmnJp_977hvhOLCn5TXSpvalIbSDDjTpvYcDlPTw_sn_pvalRLzJzyPtlWwOVC-PSYi5vlNG_7wsi56HubPwjwwrHJvIWytfd1dNlecRP-rK
-SWT9ezpfb4f7Y_oeCyMDcyVggwz5uZ3p_RtdA6AjUQ5URDTZbI7WMW06nZRx_-w-mcZuIIjgrnLpUA_wzgYnottaI3OSHYvXyhspZapEuH4jOzusTu_PtQS
6OrSOjXu_vnfurcLywRvCTBjtHy8H-jFAbnsiNtjvRROw0CXSwOP5HRKzObJGMoyRQ4UENF6o_QfR8lXb6q8bEtT1W_p7mNNCAsNibqlE6KR0jtUlO1mks0I
gB0Ssu5J_MRTdczVMnNi02gi2spE3NxPtcNmG0jgAfnWynjXOpndLc71evaxp5vXypjrU_6S6Rre2redjqBfZRgzUCxyZjCP5aJEJCvLs-pi4ztUEtBcVDel
ANWzRGwVwwBmo_OMWuTseM00uN1yRlzhZPJjlnayyAhfbBE_vapJFZ_GsJRaNnBaSyOVF922oyNcqkVLfiZdXe2Htpfug4XAKd2PY5FqELtUR4EWstldu87F
GGgcpKc52rt-NcoCvmplL0vPZeqDDeVFwN9kyB7nNGDkdnqsQmZQG_cSbxcjRBUNpnaE7dYdiguBZXvY2hfxM-_ezkA31tMdeWABJex-r5fxVpisne7GOmUh
mD_hiIWB5dN5vRkzF12o8oCxdDkj0krfpOB86HyRcscDbsq-Pv2Kk3BbuA4DKZ37QxpYD8u6khsSVS6-BZkiHdfT7hsrFUstHxhqkO5Z-2L1FcTe8V_AfCr1
mTRss1K7dnCSe-_sia2erHA59e59kB6lG2Xy3d0C3scIEHChc6Rfi7LrzBZCe-sHRKXYer-eN2mOveoFZNt155dw_3CujcYtbygPW96j0XrsQFrPT2jS3f-N
bzZ2XeIH7I3qL_qgAdrss6OKWlGv2Zg1ZHdxic1OMPeTB6TSR1nDj4U9RYyyuEOYi1Na3ExKh_AZBTA2RVqGizL4jwUK0idyLHuh1W-27PWVvpiFlptoPgln
iGMbybQABoOgxrIwN1mzm14-L-T1Ut1HAHT2srr6UWuxC3zuz9yBslVvFcEwrxGOADLlLlorjlB40Z5uM9t10oWOu0YVoujpsXdKNFn7lqNcEWLQj6jiN8JB
GS5MqB8z8g1Zkrpgb-1ZwBNR-ty76xiDMU1ooa51krSSFr_rZwttW5g_RAj5k-wpgc87oa5i2P_lY_XyrLFHEzJgnz1hXKyNaHyhlfV0qTklvRP77ySL9-fV
sEhKsll3NsHjhedHNaH-u4vLtTIqHGmMBzGnNhI6ojPhTlWqqwg-w-6Todq5H-yRhFI8VIzQKsMxZy6Kil3dTpsyKmcEzixZQozQuQEkFQNG6YlRnICbfbJ1
U4tSgG17VE7c0VeMio-rKco4jJawAyi6koC_13i07ENHCsUYIgarRkHDU6YTpgDgc-ipiWF0qIe158oSQP525LhZQklb2aJpNV3hJxzDxR53dTo_UoW226Cv
GwrnjNmC-sKzZgo1q2OuWeBPSiLpXbgvujXOOoszm4QhQ_gH5BpDtyyPhJMkbi41pqQdZPUwdhOMvhKv18IUrhXQtXxkxAtrWl6863pCc-QrJCxuMkDgHPM2
L86D14Um0rP3oDMmKgqrKxPwbT5KjsVWE0Gxv7CchZNVxSsZ_ztLBsKBS1HVnykSYIkDQqrtUzDv1cs-l5K3E88TKeE7aT7Q_yioJhVNpeu0epw0esA7VCx4
jMQxlNqqSWR1qGlj9P4pSQqPRBHL8NMg-oW83XdQ_sVmaD6Qw_RAw2z5Ds-NIUz7xK5sY1TgIckgsvjVf9RzxxIdlQRK6Wtj9LIeIQsPRi_kfMKRVuKUk_hc
lbLh8pDu-BxM53QU1MPFylAmQn5lrN8vazUQwVQgcRkV3Mu9_FNlpsBjwpQY68QY87QTS__LElkRaCy-3JiOI1Uamd31FKYBjP_s_WWtuz-I_rvmNyRQJti_
WDkhqt3QYnSFtTh7nglxlu2EJ_Bzug5Rvx5nRXnpNPU1i5jxR5UmfwlKPxgrntQXuiL3j_ROhjTra1Ph7nlF2yfuyT2jVMmSQldY8TJRqy7Qcm6urcSIzMt6
zjFUK0jzfb4NjE6qDzNvOOkqQtl_wGFXB3rAEty92nVSaPfZ6xw4NUq8Qj2sHuBXPzq1Kg2z5NtcBMZRs0Zwp07OvIzXLmzRfIIsfC-ms8QWNfQwOsoy1K4D
sZGsWZxZjA3FA2q8Aeej2AfQMj1da1O45MZ1zWMn1LAqj63xGYteCr0Bjg-BBP32fGL1XLgmgB3_0AbRMZ0GGYteCr0BjY-CBP2wfGL1PLf0TLeWPLWWPLeW
PLf0PLeWPLWWPLf0PLeWPLWWPLeWPLf0PLeWPLWWPLf0PLeWLLeWPLWWPLf0PLeWPLWWPLf0PLeWPLeWPLWWPLf0PLeWPLeWPLWWPLf0PLeWPLeWPLX0PLeW
PLeZ_G
}

