sprite $image248 [241x183/16z] {
v9W9RkDG34DdZqbAwVrFsyr8rTZo8CAljz-7PQPx7qX6Hf_MXI28f-u9NG8W-USxw0eWHaYmUr-G2DXxiHcweJpqcsuAIVLSvboPtUc6RAwCQsUwH93IKygO
-MOGdIWF8F4GfAo_IxGCPUPdrqL5zmt_Hhgd5mOAki5PTGVYKMXsVc7KT0EtVdr3z-mHNr4VRz2jRwvhxftMcR8SxyutT7EyFr_I_aT_lcQT25yAkZqOryPx
_X6twWRUYs_edh_JGzjuJ_T0tT3c1FSEVAq4NZckBbjrSs60PurNLXV6KPtL5cyEyPbpnKjP5ONluN9UEzw0lUgAM89TnvipxAYhBUCDs7MyENleNhTuSLw6
NSURmqFvgjcNHwfsQxp-YjqZt44IZt26Edkmj5uIaBb7wf3v6_FU7xtE7eIpPhhW-E7HRtnBWq9vip6p9LxFC6DIPXi_gF5RkhlXShaCbYfVZrbdJp4bkdS9
or_XPGJcxi847i_N5vZ66zAIA9F6Dby-O5JzCxiyR41LNSrrexMtTErDDrYOyd2Sboj_A5uICLu3RlAESBthzKpvpzQ-LlJLN1Vm4SHuC-3fb3VrPKEyPBJa
rlKORqe-PUxjwmLVSXon9CB6OgUkzIdlxsjAnXijPRGvOtQYA8NvTJlVUhnnUHM7Dsjp3drKvlsY3-SxYpU4TJjCcUvohtd_FCAjVElnndzj5AR5U2lAaqLp
JL-rn1lm3K_6-zYKfygx--Rn1eNnfbEUzHh7ykNSDsrpVShrNjTzwySeT0EBDjULBP_olhvCT0CMsvm_RL99h_VnpUCDc1oZ4lJeDOALVSln1kPj6SUK9I3G
chxrU0DQVfFg9shA-hxrUECi6TfwdIglu-jjlg7y5RsUeEryJGkwb8bvhxM2SgClotNclHrVdHGVtc3AtCHtALw8uzE2rfioCM5zNsFuXJbviveBKnBbA_Lw
RL-5neUuRDmrbFdAtp2olTU3FQxSxBiSx-NVlu_VX2I2oLzfwM_WowTS5yOBBsUutZYh0-4OsnXcndl_btkQ3K-4XQFanDjlVfQsyOia90GED2Za1QkHvn-f
GPreVyYbg8lLvdjYNESL3R8t89u7PNXPRGc_cgBA24m6o1eLczU7Q5Dz8Vn6YaASdqWIN_26jGPWrdK6_i-hpP7u9J83uAZM02a9pMPY_LJubMfp17R84Qy-
g3LGSyOxksxhd5AQrzBX0a4eNqXH3XXqo15lc8oQgEgJX5TPfX_TxbeF8Ipn5whDCffuH8RU0XFdFTZtaJi_UMzJHfULztyNoWSOPs8JOjvejJA1siM0jqpJ
atXAz5aP_1SfIg-NBlP2mAllDhwZfav9w1BnFqfHLIwYu80zSi0RcFTJSPbCUH_QrrUhpIBlqa0DY0deLAHqoRnDqFgqxxRpUbOUCzC-di47mEJBEv809RfI
wGjYRikSvcMZuxtU4C7BKwsHE0OspY_DMqfnDC7Q1g1-STvM5Ppo6B3q2J4ky9OrtTVbQSulnlEoB6ikxaJL_FfAYsia_hDBRu6RetobBJqJxt8sFBVXQQrz
LiR_jt54Amz8uWMn8SiXdm1_JrnILsci67Wd6rxG0tySohPNWdnxvJmxaTfxvEkydgZPS4homxC1JrD5oqf1LWvBQ4M5NWzCxORiYLriNAaqPlyiIFrmUM22
G92YWbGK0gC7vhvtoA5v_qzshWQKgjmeycHAP7LwNssYBmuGMkS0hBr37inx0HWggG7D6ETUg_7MOJZsQqj552d27WynS3En8JlpNfE4BQ-vy6pk8QpfZZjl
UiMBIbzj-bGaS-LFWRbtoCPBVCDOjfppPauPlR14xPBEsoCDHN9PsHTMQ8yUyXhn7pQdDkI6gwzmSqkjq_AY49dJZnQRaBywpDPMZlr0rn3nRRi6p9YNpiHo
BsLyYLjNowppsN1gmsxK5IBJUbXtVIWN6M4RqyWR0pEwjXz4Hr1AJ0i7tcvuHlLQkb6pdLoAQga852NnioU4_0v23lThuCPqNuhaXvEhD8BPol1tQ1ko1Izj
FemBzLJOFJ0Lu7xyCXccJkjUeqgZqeU_doqli3M0NrKQg13hcQW1c7gB-zx4t0nefjmeDbTuEKs-8HAB-ra-aZWc1SY0ZJZ21V2HKmjhuzbE_fcsfuqNQHZD
nZkBzQse7Ws7HHi-_NN0VzWKu7v-PKL2BU1vqIALTPxd9MDNzOBgOhDL0mNFQ6cPjNG6tazxMv__Nx-7NrRBhBxNNRPIpiFGYo9AgVoYn8DhZvFBxPQo7PQT
DcpnEV5uc93AUI6IVeQdj9x_XvBNPLboSRFbLWwzUpJ2lRXEfBOBRww_7u0L4ljEAbuS9gGwgDXmAj7Ho-n6pHzu1ywReg06vHVFsrELCc1lOazirN0t1Wwf
PAmqnYr-GjGGINKKdozuiDJW40UrajK4BiQxK0OS4zjX1E-MM44CnFcunN-Hbk-yqmIyBhocQQKRXVG4RkBh61EVsGX8nZlJlg4j9WOiu9k35E4GCxwMsEHD
r8zEz6NWseyktYkPIuE40kBZ2tumTpRU69Wu1kekYStlD12p6bCUdWVbK4h0ZTOUkCYvC-w65QLT11inpdaj6u6BupNWW1ZzdbGIbhz_BgcwGAQsvOSvpPad
yoyiZMSkup1BCkyu3gFnaUjwjozWwuZ3TUbtklduRJ4S4UFuqPB4Mgga7KRSObnxq2wWMFAQDyY0J6AUquzijlmsUHVm07cJZ2femMUy4J0wOZ_PQce-vGCP
XxortGdz8l-oOoNIpvOtz3bmsoZurTcqUbulUM9tAq7-Wy6pr1fcrfgNkqsNVB2bfxMVim4392KTtLcedLYddZU__nfDUc8ZKxTAOd1hqvOiqspHqKlQQYJj
hOa8IRPewHY-46nhn7phjKcHWMDYCmGezIuAlDxY9qODaHG2SyUwQT-51nXrv1s-AGAOUzofX5-Y6HFxAozbcUSCuSp8KzDjEgiqblxe9JCsCUiJKbkcutKl
hB9CZZS2ZeazRsrBWZX6CcTtYoEeDB9gJ6nUB3wmNYKZShtrId2y3lXZOku6_4Ei8PA1PBnrhoO_EYKuOD-0P2DkLLJt8Tu4gkd0EzFnUk2Os0EhpMQIM3qo
cTE3P-LO5X7p51ozM7tu4DM0fGvNrScjLhV5yyR0yiHZ4LANwOUtIZi6OZocWJfDhLJDyuzoFUqcOQYOGHvjYie3iL-jV3hIxe178I3cdTZK7itxzT3ns8gD
XRr21MFDczrMiArMfitnDk0BnFkBon3d2_ksF2vvB8qvb3MYSLgTsGPk5wsswZHLZpi2nyJqdzaifB7W0wF3X2dNpuNJUXA71Pojjkerm_4QS2Wn2cIgtvqY
GkxFLgQFSSzFy-4BR72znSkL0mu4H-m5SAoxXlYgc5sbyRs5WN4wqYqEtm0u9YQ2TnEtsUekRsIimHO_5DodGiDMC3lSgNfU3nmh9ZRUPzrrXipP7IPy9y2d
NmpcdU5uFV1rOgcRvqN26Chasd1Jbhxc7PDHlZcjYdWDE2QEaHy9QcwVsEek5ygGwfQpkyZyrHcAtKeOpJiLp-k1hn9ReQaj_KqwaZ2krzRMlc1UT_zXDE-C
wxX6x95zeIdnGRNBP-Nh0jpIJ21vtloXErydbfLT1lmlaJ7KsHhCErLTMAwy624tFtj-pC37Bv3ZN5Gdpxlo6g_NdvWOt9_YCrvnmSh1ngYLLk5gfGZtkf7j
3JoY9MPiUOE82yWMlIG0jp4AQiaGzpgn5oqlfo9UiZ9WWIlOljVNaXTuBoDZbwJa6a0DcL_nsjlabejCC-Lq5TS7SepCNNs52z7lSp_77VP5DRqthwxZcaBY
7bYvRNyfyQiiXV4xFx6CviNluHfnZDmI5BSbfGMIv5783tZb_uRRDF1cNUEzZcodRYPBp1zxDb3Th9nvSqAC-vyHwu2yDs3F3CJUBDZlm7bpO5wF-_l8Lk6t
Hs1tGPnuR-P6oTt--CIRKtsDgmjm0N68hCDxytX4zRfk47iqOA25w-0qRtPQvNK1zogolrpMUATc6Q6QY4uwQLaHyuWxrL_tPYz5o5wwgzwQwj78FRt60_Zr
zgbvOzphukV8k_gcoAoUcDNaplBHWjSfNJNlxoFhBp6NPzzBE0U6W6xeVzsS1xA3C0m5GmSzW-v_sjyRy3IEVhF5Ja-cxImTvANrvwr2MTRqWenzrq-7OMGn
5kW1EHMnl6cdMyAOhxsRzdpvZwyvXU7cogk4WifOpST08gSrfyZEwynRNbcI-HW8noTMmDpuyzQdJ2Pco64B8CSgVkMSY6unOtxu4lQp7FGxfcjVEISbrABC
mLVvdkfscRm1bAcmZ3VAL5YNiu4YuXaOwLbU6BvQ6XZabB7xBZ7xp3cHdJU0CX5caNj7thgK9JDlH2EtSrMw7BWpdmTTtgTfmNsrBXAycN4UxNfPCC_E6qOP
meLFZCDSQruEF9bn_qAnMY-uqvaB8vGkLxQT8P7pScNkp8KbP5xkpAMnimNDgt60XvIexgQXy3ZolE6OOHDVbvCtvhuQbyqjl2QDZO1XwwuQ7qzXfSHtTcxE
yPsvhrwCdB1U4LjOhmiH5lqp7W4
}

