sprite $image407 [130x87/16z] {
nPhfUlCW3qH7W40px_rVxxVa8S5T8OqTpg-ewod20u7Y3rWkNblmJaHhrKiol8DKQf2wmOxkPJJFrsea3qeIlp1Cs3pX6go49CwGf2Y6yocKk8Z4UhP33ebF
8D5n9bNYioWIpi92_0DYsIVGaMyM85Lm0aryWOINAU8BgE7FMEhX_nfAVuo_6YFjNqBDQwtk9ITx8VnVGNV8g2MjX3ybNe8aCVnN2QkKU2cIMjxs-pjIv9yM
Fxu9gHa-OqtY-n0pFf8elXMfu4Yc-6xa66Hn0og75cmY7PRVBIYwGHKt8Tyu2JhMTo3RKDqz1ABDPi7dJS8eHprUF8_Ax4686vJqOqtrLm_30MUeJPgW301c
gVHb8_NQR-8A0umYvNr76KUMsk1Qs-NrfVDZhRYz6WQVmrwSeToc1jazFvBpKEUx0K8FW_oqWSVKeFwJ8W5mtGoQUbtL3ShH89EjHaIBj6JGo9c1YnHxmsy6
VG8aAW0p87Gmg7GK1P8j6SIIGO-ErWtkUHeA85MWwDY5aW5li7H6rWm30gW7WxWP1M1CG0o3Vf2KKFAf1gG1tWs6KG2c2fH_3uDIWUG0wha6elqu1af030Cb
51cCYrq8hHd4ftbG0KGtQ42f3mCQZ0LfrQ0j6cG0SJ18W54t0pB1yiF00HG3sc8NVCL0SW1vv84AWA9ke0RWRf0C-LQcnJ78SmD6optwc83QQ-FTWCh302Wi
i0fRomCQDLkPx72MaXwrXVWmQCCWPTBWSYvc8gfMLYOh8P8SDSLke6wQ-xCWra96h1bK9F4Ngl-VsYXzKulkbIGLxjww0IMHUNLjdEmJTUTJpL6FZvCgS3ss
mTQqj4rBl095QnGdZ1bq6fz6PuhovhSi-zyrgQ3Z4ZUWjkK8Po0c3Ao-tq4P7qYLqfP9C30FIjfnYZEmx8tNCh-0COgNCh-4QkB5p2xYNBo4zSl8B5w6f733
Z13FHvF3_QlRCBcOl_vfK3Mxy7vjZcXuagRJLw2T2bB6yrZJHPSPwpXrRVxEIVM4QqUf6lwEbHO_filohTghMEPdn5BQWeKK1ITGz6rZBVjl5fBOCawXYaSa
_x2T2QhpyUYx5SCv6FLf0ER_8kObuJoA5dSMPkb_cE5iOXX8BU7jv8D056oWQJJ0i86YHxGbxC2eVHDWP87KCZQHjVVtmoYn9cp3GgqODk9l-lF_2m
}

