sprite $image197 [161x218/16z] {
rDW9Sbin30DGV-s0xd_UhfncJsJC16PnWFGD1PErR_zFoW8mIrfVnT-CAwUluL_wbTi7h9hqVIC9gtZXAIchEF4sgoKju5DcpVV0EQlOyN7wbMg0GXMj0qnQ
nOMlCXvQnOAli_gLu8MpLd7XBBCa-mndkNuLvrdjobZ11_z7RE2k-5VEnBtfLu8FSQAL0oMp-e66Abg0_ki7EQjb1Fgl7n4nLD4DZEjd11fMZW7eVkSD8SwL
GmXnhXmAGciL8G2jLPn22QrL79iGugjY4u3MAXO1QFtkTr4eeVNwBM64rdSUUqE8R-NKBOpG-TtleZ12QnKfZD1QHMnXXCugOWiZT5u_x1EXNaKtq5z5K10Q
gnZ03I6UbGDg8_JyyXb0GUXxPz0WZEkd0mt2gA86326-ExDgGCyZHnLLe20qLH4q2rSJW5OXPf60Wj3otGyKXCwL0mf2v_K3duHUuYY7G47eN3cW87Ik750G
EgyV-5OOn1nL10MXiuhW6-41qLX5K10whn_uWT1C7DS9y2sHFcAx3e4Xz1DNFGE6C4iLGMOYzkiK648_iRq57XBvcEi77WZTnEiDC1knNuV08FgDgpq1puKH
-bPE0Eysahxh1zuj32CzLGGf44s3v0gWO3GCadipWET26p9-cRvTu5tP1cJe0aXI87wVClw50w1W3ANAVFEd0oWJ3vm2JG2AnWYVyYGw_3kS0b0mgk5r4u0s
8ucR0FGWIL806f1X4u0E9ID7G3qwpGECw38TgEU0900Vdv_jtCboN348XM4q2x3V_t4p9wU2P-ksVPA2PQ---hcz5FysC849J6024vZ012OmWGbCO08JcC04
9Z212MpimCaEtEJ0ekJ0PkJ0mGwSxC353jpiGAK7Vh8mWGcq_n-OGEK6EZlGw8563bHsu79LQk1qumPsTc1rLsK65YC7odPJPGPETsvWSoIa11PpfmRAGa9E
O7DtNY0ERn43fxiRCx3-02elK1Q4dC3gFuIyGDb8I0X4GgK5oeAG4rWCGagWZDzNerY1_UvNGcKjUEy_XCJ0Fq9b1Tv1I0aCGZvW4582x_5ec1GuyOQTSyMr
GwYKG0b2FY24fie8X10HoO3IB0ZPW58rH6G3Ijr1o0QKCZqGoO0YtVu8GVnCOFi1B88Vr0c8AW1jtGY8DUDyo-S0dvkk7YgI0QKi3nN9WFWIKP4CA6LQ9780
CNMvXqtp0B7dc947YFzpD381fGppXqOI88WVRzHPta9Ku3vWr_fzqF2zHBTRXCJX8vCtJUdR_SR8U3NghLEN-UF8SsKup1I09vi-JwaH1-1xfgrN7BTwWolW
Je3u6gCnpj-2Q8ekqCw1C6xpryp93Qzr04J76utEMkHywjZN8qrda-kcj7aXqlPeA7SX4YLFmlLwCImgbzhxQ2jqkw6ojZ7tAvrckcPl1zcEe7tCjRUQHPJk
DKTljRmOxIi
}

sprite $image197 [81x109/16z] {
xTW5bXmn40DGjxiDgd8szp_jGeKKS1AF5TpHmw7_QjJiz9BSwv64kM3MBw5dm0jvYhmCHCngbe3Ty854EKH_-4CKLNO3YzQof44cztQXOlYAHDa06u5SfQ12
KPMaQAh4D8OY1QFASmDKLMduFebwAC4WBoMuVc83YP8g6u6IAeiZ8gioEuqegT9eH4cLzXCZBbqZCARWRISsk2-9riuVWKiYNsxde2EYgH9kDAAWoW3NHMjv
3gwBysj4W2GkLZa5ZRRCLfKCnf3RLGOO8N6loW1foCqg0zmK-NBBO8X1RbKPe814FHXaCKYxWRm8r93z9915CfUh9938cqr39P19CXTGC_SZm8cveeRcRWHE
I58dhl6N9-3497doZKBWn5mA4e5xQ32EWy1RLG9eGa7-QV0Eti4xU0UpcHOiBWQR6kmc1h6Dt46JWw-lmwO6YqCBPZSjcE3GWdM8mUmEAPZwC4Z1xAu5KniE
APZT3UP2S8Ge1D-4g0H9r80FwCCTGh0bn90oiAUZXwW3OtSCKW0-l7q1K_4O4jlW0R_IIqxi3XaWfpcH0Z263DAW02F5XXEv3wQZMf0k08cyqKGbXyaIv9e9
cBcdMQxkB-P4_U9TMgfAy-IAC2TgvCkbga4JJar6MIOdh37SsZMHoBnQeCCd2IkmacV8rsZjC1zVk1_UCBHo7MarntcLrW6ZvS_UQZapM-a9
}

