sprite $image173 [246x196/16z] {
vDY5iSD040HH5sbdJSe_sWzTO6PslmowRiwMDBv89SdeGhEiUyXAMQ83LtTsAPfjtPqLoyoNEMQf6lUAODo6xcdECwZ6lI9injUCMzSTkB83LtVb1hvcjAyP
KyLztZLH7VJAPnsqh7kQ-B83LtVWwguypg2uqBjSurxnDQDypLY-unTVpyopefbvLZGpxxp6v7sUIXJNEo_cYqRvcb6-PWYRuOl6rDSCOJDyqIXVCuJDUEWx
j6Vc-H3BXpHxPbxvBBvcbB3vzkvyBbypRcYMTK_p1Lfrq2l2PlYQKS9e-9fnkjdMNOalEt1rLw3gZaEjDtSqXjMsNOYEZZ6Qxku8jJ6x8MkUphgXQfvHRUh-
QwRQbDqpK3sLTF-MRrvhckf84DoxwSWoUl-dNGUKe5RJyuq7Dg-EQnEZbE8lmK5MrChqudutSmLif8NpTcxPAK2cv65iUJbpKIiaoKElvSPQ02nCqcjhZcn5
ZUNERI_abjcQEeUxsojhZbKwjOz0uNeTDx9bmD88EzMS8-zaBby34CCzJFAtO3VcxkiXsEZbRZ6SokkOYre6IiCTB2FFrF2cSbVOeZ6qdsjcGAGuyZRcyhKH
mtRwtML1vJNbxhus34Z771IoCpMyXhdxUgzvdMkjvcyeT_Ur6vZZmyxqCOAPrp1tNoCWuwYvHdBAAyhTVUqxunYsrNo0m8Tnv2NCTM-ciVbQZWsl8wx-CExF
ZNr7WBwL1MGY1yB8mJcFtT1hN-lgQx-UwiwHHvUx-rgWqNnTz3Q6g3oQ-Tk-7i85xdiLAW_Tq6jVnzhNuwX2SEIP6_fpNsltTUPUXRd9AqyjTv-lkwyJxRws
hUO-11FyiSpbwvgl_LZP_k4bzogCfFAySd_kwqXTV2tyjCahJsGkQYzVs-vhTstVcmy0kM467jYmLlFdb7ljwtJCFYxPkG0apOzka_jfpDtN62TQy1Gk2CUJ
3mGo7Pjyvjw6_jpN9sBvrtmjG2PB1uazZzZGQr_FRogTvsirNrSpygJlnvIx-xhQCtqDqzTHljOOL1KgJs7kypNxz_Ml-fhDrzhsXJ9en_dDDtJtjOqXwVZM
Y_cw-Rgg42TzFs13Dr_d4D9H8otcQzF9rzSgL6vUxhMltJYMEoxNIDQdiApdH9cjvZTchd22qKYhvRPzlWR2YHIeUZshK4FPaPjkwC_dQnabiEXRETY-G3OS
f5c5PERE6tfIjw4g9dTirD5yNL-WupbH960SkMkvAx0uf6VDrURhbQ_hn0igjsKkQWbix3KFV3YYJlEvieQQhnsaoxrJvPuRklkwpzTUDVS4z9cl3OZ0Mytl
jw7NyxMmUH-kujRPrxxvMitNgtFjZiph-RhkmnqcjvyUvdTV1qZh6yNRRUYrh-Vw2OXG_Qd7jtmj819BWHNvdJPqfyODV7KVhkAMR0GciApvUbwlzWcbSgTo
LpxOKxuUGStN0PFRSkthuKG0XjNaRSpSZjdsqwjWLeUq5xT_xkjvlPhs4pMN_UwC_sHVx-dhFb-VUxxqTPTVFzVkiA4h7sCFUvRFhnDa1xTv6e2VV2qWozSw
R_BARSfjOoRPylL3MiMjytmTYtqXy65RpOqZTsC-rzmCB6IZpTSf6VDSIoXVhsyKatwktMD3zz3FjJpFru0LjyMnbQ-FGwUlCx_tHf6_mLpSPr_t-LggzTRN
VQszvZQCS91zcnlz9URYBbzddw_5YJjo-ZgxhtiLAd-9MUEp6ErSYtaV7aDWLjnc_KPHsdqjC143KBjHlCc6NXzhww4AZPHKIwIBh-c-5cWuxeGvH-woeTSr
hqlGFb_hr7FN9xwkAYXp19KRbNlc2q3pTStNAT3i-OUanNiTQOhDrpu47l9qPlwIeJ_F74biFLH9anjzvkkzvf9vkEk2VHVcpdtsjQxqLswx-5hRlYZvfKcI
nKWgV-GZz_Tcpg3ziK_Aqa2sSrVHrxx6JAajbY6Et6gXEtU_3u-oicGdRkHP9rxpTUY8PzNyPiozvYQ888ReXxHafibjMliwmegxQdvBvk9klaQwpDTMtBNW
xSEBEvRfgfhRxwREKVcPcjTbm-AnZtJUuFN6JjyN8uy5zzzChV7p-NAkUJtsQPlSYtiJKkZmTTI48ikqHdsxSlUQhuUg393XmsMJ6zdvmuj6u0wAJ9Vsy-ok
p9rx-devNxlfCbAe3wi-4i-8xMzlpZovjVjw64YBDtQaouBRvcjysBnUjSYHm8sPAm9eliP0-tsu31iECZugaaanzuK5S4pk3u2kvLuFLUV7FYPTPoht-GLp
c_04vk9klbxErn9NS5KLT6no7i5Szcw-hlawJlErrBdDqFO52W7mryQC7wzvjfkJkb6S_zz4SPzTThfTUC92hsjEEiWMy_LgmUNIVDtu8SozvdChsxmFvpnV
UzY5swE-01x2t6lUVBsSh-swtidy0li5yV4dmnQ1tEG14ZPyDL_RYPlJJVjp5hgIJ7qBG99Calj-rI95IfBiYbs-VX9pHN3QfAZUrkefOWbKmohFOkx7ca3J
rxXjZ3ijsq9xrdoktLrFWwxCclVtEgHGpTVjUdNF4mwnpxcdhzjBBhhCruv6-VgnpCLzyRLBcUitsNw5hySjycLnrR8n6lNOfxs-bC13cNlDcwyN3_FDcw-V
MEvrpMKXS149QFs6xGzHQzmicZMVMrbr7uuv-xtJZ_jwt30biG3ql_VXqzUxknwyqEkQnp25m3_tzVEPYxlxMXTV_-1yFMuTjipdrzvzFS-rjp0NzpTz7S33
oxtcRiPQ-Ff5pDDYlyJNuq6XOiDn-r5VvtXM-ijRqzUKhzzGxlKLqu_xsiSZym_s_D1yFHuR0J_cw_7ei6NfwxSo5_Tt-Ngy8GA-nzVZ9M6BPVFrcvadzxVd
wu_ngdm0t_IrHkLTt9_Dr-ELeP93mFkP9_VQrn_ZnL7L_4ezNXvcLiplvtuvyteMKzlGhuyEQX__Ln78DFvI_WK
}

