sprite $image16 [295x208/16z] {
xD2f0O10400nVMhxxnOSab6yIGcPswtTS9uKeYI5A4lbILA9ajIZ9FKeI_r9qX752YGrbY99aQJ8KYCfaXH9YYmraY99aQL6KYGfaXHPQYH5aY99aQL6KYGf
iXH9QYH5aY9BZQH8KcGfajH8YYH5bY99ZQJ8KYGfajH8YYn5aXf9aQJ8KYIfaHHPYYH5aXf9aQL8KYCfiXH9YYGraY9BaQH8KcCfaXH9Yb9Iu6bhtsvmtDPX
803dpx4u8_7-nts8u5R8cxZB544HqE8HFcXc9SPhWPbGiC1CA380DPqOSPfGP01gGf41g0b51A2c4n5mcb1a06f20G6e2KK-GM63cYEXuuy7Qa8D8u6Q8w7x
CzI48WLAAsew3PxN1sgEX6uNQaAH0QZfzCf8tdbpXEVbWPeZ3IvGSrWxr92PK3gezS5ahuscKn-mTgOdg7cW96zzPaNzbBV1f7_p50g7H58c4vw3hrXOnnZc
vM0NQGoyyVzGd52epmDtRtXocXNLaOJ9tKoXZhjYOPM1uubfLXHgrO5Jc8xyVb4a3HqgXjCHLooW2cdem2PGHrgniEuDw8C9P6r7VBzetZHqS3TKRZ2iZKUh
A4LIfWPtL7TQZsQ7mk7UBwn_74DpTzpktZgJjqfAHGLMB9cHUjJO6jPJy-qqjIR9IrvH-0c9TVim7AZiJEkzkVS3XV2A1Pak0JgijJvzG0zMM7FKLbbnZ1LB
1Aap3IYGpRrTw8CfcBoyUTkO-jYuDoqiJPW2AvR4I9rfG84ahtGNfiYA9MFUX6chSjBOX2dZ-uMHepIO58grKfYILHG2IC8aoHEcNEyNC82aJ0hLcUwhoGHM
B4bAIPaqUPtfijxA3r0x1of5tfH9eJeJiIp9AYgEf4mArUT24hVx-nK59CYRCEaC9YwdMwoYv41bG58cTRgWCr4gAhHYoP4tPLAewzgPYFjVLLGE96LIAAuF
9d8zIqL5LYm9yYPCBvtkvyvKJeiaB_8JSOAZ94oleMutF9WAFv2yRqUACobKAUnCnA87wljNB0ZbxNqbXSBjzc1Y4QRlVx_y2wHHKQTLcU8hbhHvqufQ7apW
1xx2puMabuDIu2OJNB4apPj2hPTYi5fDvXk_mkS_EqhwVc75YWAOJ6J5aZHl2eLg1SqAyDKLXPyGFe-acmDuCnEeu8ebGIb5eTozoe6AhbYIvasTYZLtfq15
LonPaHGAxjuaUE7tIzQyAHJTdQonv6b59RW4X9oir4QvHCLNB6dpfXM5Gc6ANmvo8YdKDiG7tYz9IcaV2cnIDT4LIzwZf4wtjXhmWHLB9YI50aoUB_-oel2r
UTDhUJK07wYeHAMaKANAhVoT5KlclEdx1G8LVh-aHL8ezrRi0nMLAsyAHLaSH7yY1eYlVfbylg90itTNB303aJXlMb4LmBll5rok1X3VkfxyF1H8DXiJMx5S
JgV5GE8pUKFzEYLT7ImDQ6ya3vtfTBuRYAnvKoVGhC8i_dx1zVIOIn6eH4WArQNUMR7OSkfpCu18S0c8GR4P6jvvlvH-e4P59RW41A1Wjh3odVVBUkvEvzL0
vCoREXbMj5OHWW984blohWMleC0SIFetpxqHGBoYRh-J1o9fAIdKoW4LhAZBgS_TG21ntlJzKl4N5NKP5PKJITyleOeQMAEYI6JDcqBXxOgwRibZzqjwb1IA
7SfsXdiLjV0ngP7q9sBIB5vHzxCmfKJIduWRtdo_B0J9pAMaK5ZgO0gjMCfA0anzb1GAeXHPRXAPaNHC9lWJyGSsRocWo3zkWPENKXog6h3_VicTjpZKlQ80
knML6odk1C2v0mKmUzxYKAMvcq1jM8SxIWg52hDVxpvxNL57GrAeOdLpiaBVITumE0QIEjtFLlcBx94yc48ThPGKgfnlbQEXJ997a8VBcqAjXORMR9DPuLuB
WE4471D96sgX_POfLIhge7bJA7B856lk80RKOO-IGhdRW39lfCEscKXzzDgq6gxafeI9zDj9lqWSMuEfz0HLNtyBZ8aqfaTjlEoKQI9fHGdJLDgjgC4qaHHg
Uza9qqJIVrSWwpFJHD8kH-FQvDuqbIHvjbAO56b2ZK44QK8XeZIT446QK8WWJIX4a2OK8ahJ2H6a2OKlGFeF
}

