sprite $image170 [238x173/16z] {
vPg9Ugkw3eNnR4bkUV-tlTU6zH4IGGdERahEEcDsESCVIrgIpFW6KTNu-GBhVuKt4VJvl9dMoXyVn6ln1yF-Tt1fIn_F-jdf2wgLFlHyMK7zLDwii7uiBm5M
rqTLPmRifZwdF0Cbxua-X9Ve6LheyWwRT_K1xijqWXQwTEl4Xs4Xld2RABk7owJfkYsnoDxH5bB5LqjOI0hlm1RQqjMM4w0jl0aBsWloaYekfUYvE_q4kbOy
VzCMRPLmNgkUEMYlXAiFiGI9b4d2J3JzYF5heBrMEBFMHY1lfMnA2lqa-PFdcZKrsatSUkpqiwx02boUiNHOeIFw_kkB6AZHAhmYWhmzeWii9veOU2mY86N1
tz9rS9b-fgNLWJQjgzH5UB-FpNIWKuGgTG5UeeEqHMGBjj5UW9VeEAtkGIBhlCqXqu_YDoNiOLomQIMvyC8w3CCHtk-t3-o7gfJSwhvnZ6QeCl7F7I_Tg-pX
ubHLqQHa1yYcFyLBZz8dM8mwGbnqoToQ-E5Mxk-4SoP5c63rCEOsyoYQMOEPA3tDrEP8-hvlXcqiJDh10ef5FrUATZvHAgNa-OFz2-dBj4txSBuD4BGJi81K
65T4RZxEL9-JKgAPuHD1xxdc7XxCPgbI1HAU90KIeKqXOGEginG9moIVttcykgzEj6MlEToaHS9wBi80aC8uxq0_wnTPmLk0-ym8cv2ZUGfsYD-Ulhn_vIoD
IsS5oftWEYR9mmDIv9dqbLzOEYdhm_tc45gxZan1Z9nOmjaVJrzABtUTl2DP05aciOXMfHvTXucYisOmBgp3cTwHlWcmEs8fJrIf38pSMEin8whNlCcWcVmb
t7piWht8DcmHDM67M7-2QI3azklfpiNZRpQJ-UW8YuAamHRUTftfc4siZ-NMF9AUlkP8-lPNfuDdMpHUUQZ9QPsmv1Rm5hRnyLQ5x71u5gHNNR0VMIjYRbr_
aCU4JHChHNoOuzknTekKdd0ZVicimx8Ro3UGK87uFeY3e7MgJM8kWXyvONeG7sWcUtaVlsBUCo2IiYK0H9mGVm6AScNFQM8TOX6ApiUKSuhvblVhdpQJQa39
Dcnf3sWItciJEI_kKq-yTenGE9--t7Ek-mCxOU4Ywi6ksyI8D0Q5H6UCiIwXfueUHVj-fap_OXRalIjdscWQ4NBAkQgp3iI2SYOyv-W4vUZnILRIjzDzIHVB
WW3I6pg2c5cgc5btdNlnXCghdX956_f7pIHjYOkidVJ0bRFgEYc4a6X3QNeueDlCAT_nvgMPxEQb7ThTvd1_EG40qEYnYEnsSxn7LycCI-URoNEiFrqvboFB
2R0QQzO3mCgYR8ltDX92xivzdva5dsI59Z1HMAkEB2VcayjIn5Ignp16l8FS199KiLwTlapxubK_-F3tUyk9A0t00bo4wk7cnyLbHfVbbrc1yCsSdWNvILRG
0X8g1TeEui0t0B7HH8FpMajWMlvkLl1QCscGli_oqi_Ymwy1wQwJst4ksUk47iLCw2U7crd1C47QAkUvSAOZOgJeaTU0qdevqMI6mHTUF4QojoYvTqfjmSpB
h22KlBFEf_FDP48G7rFPkt8kcyk95O9jdjBgBcnOYqMsbI1wCw4KhjJWMl5wL6Sw5ivqL61JM06rsoQMR46NOI8kKLBACxExdHNIHEs2kmlRx8-LAaWvsGD5
UH7O-JvXOPlho4l1nzmQ8jJdKYf2UYXN5Ep_vJCk3apaKaezynjMimnFnn3aEAwKJR7Q9cgTzbSfHH8U4IO_w6RKz5KacpbE2dCSG7ixBbCHFiPQH8JxSFUN
4sjn5P6TsqD4Gb8t5YB2JBOHBWkxg3KkHyJbwqla2LvMUKLVJkY26LaHHYJaGXIzSzgma2kHjFeytmKgTV0WQwC5xZbUORLDREp6-H3yeyM4ceSfMim0C2pD
Ianz0bspoOK9uBXLEI2MhoQHPtbPRb5PQHEbmJUpqVr1_8txuFxIUlVmABgIfHpnwbP5-60AVe7s2Lw89-sw3ejmCXj-MiZRkfy9L4h4gkAhj0qahGMpDJPY
ZZgHi0-qEASJqbo7HHBc057-1-PvYZt-rsMgI4dfuM20w2IVSnsWWXOwWRljEeqLQpTrFoF25532voBdDck5i5873mSnQ3jubUK4bDShbno3L_Sp5klpEH2O
YN9AUJ-4lfuEOj1sycO7MkQDbKiETdFuhWCyCxBHYoHlSCcr7KB7MLNQy-dBoY8Xkviw0lEm5TbgXsiigba1qeCRPRrnsJVBBuMsxtZrTqA2WHKXVRcKfCoY
WgdS-5mapDJC7kNvJ9i8LeMsZrT_9qGAOszevlr54GwQdygNK4g9P1fNCIl4czlD3jTHQBjuzNT261kBgQeiRMxUE8LIE9lLh81dpxI9ygLBUd7t5mdjEClI
vYOXJOpYRXSl6XAl6vV3hWDMbRQVTtiF6EiH2MgCfSAKCkcgPozBjvGAtxrySy9X5TekNdqF25wk3kEiGGlDqTHVyDug5bCFC0OBEYPA_Qvpd5RuRFg2XINW
mDkcDNjhC2tOErp9zcPMABmi9pfSvn1jlnkPY7fDAOH4WfUo0UKVPmL9zSjmrQsamtLEqFQdhqit_mlu7sPEHZKJF8g7poqdpj3cHETuzHUC-V4kToiFkQNF
sUN4ALhNljAkz7MhDRuwAsZIzblK6yJxj0H_Us7wOYMwoiDWNOWfnVLmrB6SE4ER1cJCwvh99h_a8Jug5x7dNAUBreQsg7vPCzd4sKwp0fG2JZ6lPiL-rpbE
crl_mw7--IIkVgdCfSXDzoVOILbwU8FCFxMSwA5bK_jPaMIetttNpIJ-3K1RtGFg-wt-8DwdhVjFrmwP-sV1yf2-ojwgPpdHJLitrb7-pIouoaziP3kM4_sq
4gl_0yxwEtBc_bamtZTKqNIuJX-j1E0ILVVbby-2sIDYrwvpeatieqNgjeeSZL_HzZQJy1ef516nDstYgPLuFwsuoMxZKCNzi-0N0mbk18kXqEiw_RIrqxKi
asFcVx7AKLodWxN3WNWfp1odxk35gvnNjecztONZgL9PmOnWN-H6grdmv7AYGwDgjvQc1f8dMZUOLwrobcRofEjqmVvVMieEliKOJRISl2ZgQoQDFU4wVQnD
V0yGXbcvqPhs07aNSZylNZ26uk-oQiUBSiAWHVuwwkPbk6_7Sg83LZrURogRBBGUSVUYzFtjX5sho5gKGkGRMZkb6d3xtSZQz5j1h4bKWTQqRYCPR3JwcybV
2k8oRaWsPlkPDaoB3VSYDtf74A-b3mXneatpnop2r7-yRmlYHKKDvSJY6ZGEbupNUQ_22gcplQj_zet7riWcqzTC_hhh7EUDPZ3ChKfDnJarskm3TQJlEnDs
rtt9MvuITg8DbTRKAgs7ypM2UFjyUHeMU8faNpyqvNyKpYo_mmgfTmYMQfK2hQsqp3hlcuEudpTKmeeP6grZzbdYO2DhkFok8FvMM4vMvwRSQ9FWAp1H5F5R
MCi8TVDcEoyoo21dep5jWwRoljLr-davUHVubfQPamLkD-_RM2650RGGj-wo7vVVoGhjqgQOs_hPaEZYDxXEbtPeOojId3hkoTwOiBg-7m3GMRdvLTrf4EIS
MULzQn3tytAoUPuHZ3EDUDfM6jrzhyIgBc9vFjia74pRS4n-xFJZVNyGzrVdE7KPkT6si7xQZNeNCVzCwYB7CcXDHGt3u6rISVaIGRo8rLaXiGUj4w46BPhu
3xI9_Ssp6K0RfYzW--BeZoSij7-n0DeMmXQq-xmNO5MRvuWgrSvM_4pBl3CByYLOzNYsimEvERZDjC_QA5VlRHFxSJaO4fhVZKoDDWzL-khg8a6ytssqKCRP
XfrxilA6vSIBcsV1IiCrMbiFDkeNHwN7TTuaqJVjVdAWwJKLCeDJQ2_7ghjlioFGEcf9J2-ZVHEcpfkdDwmC8daO0hDL6gjoBLQTDpY60-4stqGt65PehyIg
u_eMkn8QRTrdXA695Dfhme8NXvgOJADjzOdQ2QTksk_nB-d-Ei5E7sZQGSTEsl7FQVtkaPVbdYmQXVRQiC0bZyi_t9DfxosKAxBglC6w91Zr1v-8Enne_BjY
VVODfsdB-ASbToBNGpj2L-7bx6qyHpjUGlApoYUmGlsquvNqtKaxNamzjEFrz7sMjeoN59-Y7I-hvsd7I-ivsl7oEauxVeAEqeuVeYEqumVf9zeoVfI-Tsd7
pzCcxVYHOfLs_5WzqfRnWyLtjEE72xHW_NI1zlD9mLlU0_i_
}

