sprite $image338 [173x248/16z] {
rDS7YiH044DHibigX_kVTgDOOYt6KNed-1XDDRCzZm2uHO2i_gd47xhdGYJaiq92KcM4fCeQqYeXgLAMgVPRm3v1gGulC0cn_xY5NInUO1nXUGDw8Qb2WrJJ
N9mNaYeqM81LBguKaYhCI1NYdjG12VYw159gSI_Rr7l_0qzu0aC-gpZ-hdeCIPM41GWhA7LUKXR0ULcMcDHl6GjOVcMCzMZiU6C14f1wD9OlBK2Cnmgb7ecj
5nSWvkTAnFTS7OsTtbw0UBwjZOm5YE5bxHa-M3shiTRoluonYk4Dw1bUrfxXszhB6AjaZ5KoKiNmmUfbZ5KC_WeSY1qsvwhdku0-jkYrW3vs1QgAxgcVpDa7
RlCw40JWPLFPSl_hFZYqFF5QO0IJJpy7BJqVw16RVx3rPG5tjWOWFzI3opmZ5O4FWpjP0n3um9sE2gomvqxN063Vk8pgpaK5jj65AHe0x0rShAs3iBwwpFCq
05W4F5HtYWQemvvtOGQgR7a5TY1tV0Cu1oA77LJTyLHwP7FOHdN_MGEq43Mm7LqONzOzq3Dx2zk_0lStG1TwXHsshxhZXrNp8GqnYyFsLNVyp9ge9c-75DY1
rSNQsZ-kYTKGO4TL5sNjdmPMzIS5li352dpBxcgjPTtDHGJQZkgEf1fZ3l1OON0xgei637guDWEI3oou7TK5jJzRdGRKCEDkm89xjGiyl068Hdf4NlP8m3xJ
qmLCLyEUhc8r-uFki1tLHGD63YnNNIRwn7vHNUQ13K3skXeejWSVs8xgzb9rNqhPzFYqF71rktrOFLPDl-f2TrbrhHl1oC_FwwVSnjfNtDwoRl7m1Fcz8EWV
M6M-N5reU_S0I5RC1T6Us13EiFemNkK-gQfzM4a752zzhizNnOPLeyDMm96hNM0rwyFA3mHP7b-iNykr4c8E2-qrBde3R9Sr415UUmBs4OT5eBt0jMvihYoM
zT2gcH9gqC922-x_Y5sXA5GZPe91Rc3RNHYFbG04uyGj6EG6jiqTZys_ju41M7-j4HhOHdM7OldjB91UMAMQfFN78cuvW6rNTpmslpr61IHwfgYf76LUr67R
NHYC5UnM7bc0nVAR4X4EkS1UuGx3GYSds4m-uUWli1Uhsu_5CnuKs1T-yzOeri1U65nWzIflbOyM98_L-lWZg2kmrxbVOdKB91yBGdQj2CV3XYGs1DYhNVW6
oma5DO2A-pmV5K5RrHpsE-vrh6GYXwsUnMqJrlUDOrpL462_w4ArNi4MybWD3bjv_FjGjh8Q0knNt7go-0khfrWXZ2IMswZM2B1VT46PMV-g0HSzmp9XP84l
reDjSrd-wgoKX-S4kpliXXPqO1jQKQlOvXcRMzZYDWh3iE1UdBhsM6lOmEQtRU0-18jSnAAMgxMmGGtJHTB1MBcENOxri_60aO2EWUt68XUmM8QojR4BtaSi
DXwBjB5IHwkzA51WqnLpxErObje224wms677b_f-h2wKeLdi38il8MmtOh4HhF-OmJl1ehGOrxknUwgpvz62PC2wqTD4I1Ax6ujtiO_RjCrZJuSsB6gtOp5O
kLA2DB2sXVhL8cRtOms79rwg-HohMdzyIJ6leDxSsVN0beX9zWFBxbXrEnP5G73ENe4rBKJx35WJTutjiNMvcW5RMOXyO7MFH7DWVH7OOxTCD1FM6DZeEelm
15WFMywnYMq2h2z2O63T7Si4M5-4fC2wfNKIx4h8vhwKnP2vQb1t1y2cNMqMB5g0P61HrdcmTIER3kr-O57MER0urAxyLeGLPPq6Yoi0mKQyFBw8iaw4nQKL
4ug0p8NLSDmPuIsiAR6ukbJC2fbjHYmcsVGwFiPDRLgiODqofh2gsRpOvVUX5cV12R6uEKJcnFfxrlcn1OVQwR6AI-7viHjQC3ysOMQT7YlO2CwFnKPmVgmM
R0Idnvh-rxwTB4SA0q4Olaif_-__jBCGezamJO9KxI92UUBuiQMf2dTh3y16PM6jBEp2Bkp2Bkp2Bkp2Bkp2BYpFmS9_M2ajbZssgQJ4ikNWlqvpOU5JRDcI
3Ci1jdCJOU4Osxb9i728bGpj6x7m2jjK3UwxiBp6QZCQt7Yiu1ZRZHOt7ll12TRLncC10sjmux72m5hSU2nOM3KPt5Wik5ZLOcWZiNZOBZEuOLZ0nzPYSCEm
O61jRYWMyB6-jcFhJ2nNiPB13S7YP3_M65pZTxS1LAiDocU7hKbr4XO6iCx5LIrb4fQRM9_RpH5K7-jpgyQn6B7Re1mVQa8RC8HjCYzkdL1TC8Rz2RAuMtCP
M6SK26-3ZJg01GQnny_hNZlM1jpA_J8Ow5cOWTK5RbKpi0urlWtKso2GQYmvt0yPwGQMUTXgbi7TDe2PMB-xRhnW3ETzRG1CvtRCgTPe0uyQ_opKIst0n7nS
vkhAM2ECn3swsgWcblcvf9K_rc0abEkt0K06RcsdM64c-8kn6cCDHe8lhji602cuEXrhU5FAERVlcJJXOOt_2_nwoO6R-6VXRCa1a8nxr0P00gqtrW0vkEMq
3G2ISVzCbZ8w806tN-4ZQgf7TuSbH_RQ_P8382_tdpOGa9YhzXUMRDbREvQCsMDLrSYQ_x6DpD6JiF0eBFo5vG7vXUKPKTMNMBy3
}

