sprite $image426 [231x47/16z] {
xPf7biGm24Gb9w3m_Qyx2NTKwCqab_stMlrNA9Fko9F0Fu2fx9nb6bATlC2lG6NlB6EgC67rUo1xHvSoKLdz6PNTynoeXYMRfquDIm1KdlTvBfibBCOCD9vo
cvzZkReQmpeKvBGHsPdSe-5fidTqlfLiHKZ9oZOtobD9ufJb5YQanAZYH5C6977EAQMflQ8gqM8hdSe4pna1dSIKfch7hWaugdP9SwykOx5bc9pIpSjOBcJM
rLIM-nXYQhAlGIyyS6h-8AVcgNbgll1m4is3x9jo14qPbqESQOVf23SKIVaOzytKctx6ytemhv4O-LjGzcPanlHGAwtCbEfNRF16Q72Mbw0lf9uQoBuuizVo
1D4NIZ2lXPA69OJf7rSzf4nlaeI_yjby0p03tDa-SOCCBs2pZ3nNHiifFIF-27JtaZAcab6vefGffogZm9sb1VDHyXq
}

