sprite $image208 [252x260/16z] {
xDB7RGHH30N1e_398IR_QEMbDUVrhpg30dg_VkkpjpskNtccljQXKFblkVBgNFesCVQkC_a4sVkWhvu9itVzw7kRF7jt_UwUPlzj9jQ-iREpixEpixEpixEp
ixEpixEpixEpixEpixEpixEpixEpixEpixEpixEpixEpixEpixEpixEpixEpixEpFmWzoyxENi7s_c_OsLyrTlOAjlV3sjTQeVRrNGNQgzOlljBi7-NTwGAR
k0u5uBi6VBIz_zjEOqeDfyOfIKmWFR-uwyndIHPCjxJCNsKVqpeuogv8IJvf1yj53xBBSFkHuHQVYe3bPiVOSVkLJzbNUAZPGVPCR-l_rzqkvP8NiwFiEjnM
-NzmS4__dOkvtSdU3w_fnebb75EEsBd8xNwSNGXEU2npn3yqFjAURhMCivpoNVRXLa_4Y2cgWXB_HZi7KyIv_l8jTcpOXpGvyz-2Wd9HE-E7XXmQFs82G5I5
zDUtZvMBBYtQtMK-1CSgNs2NOKjkTwyk3u5oURkjAp_Ei6dG-H1C1ILzxVtnPlghz4EMbq6l7O9XbOlRpJGDHKw3xdUlBCw3SsLxJYfo6lJQ8PXY4RcSFHRs
sS9xRMftEeJyA5YbZxsxdkJKutG8fIauFUpTzIivbzUNXy0NdodfBsNdvgNoHkCGyYDMkPeT9Oszvhfv2Cl8XUmeQVTuw_PtmI8NiIUKjChBovrlVwFQdz-E
aiVbRT_-bF7aTb0UbdS-3wrFnhhppsmNS4GVbhSr6Lp-T5OxDkCiQrzyiVrzct16ksCpyiTxpUhRq6sc_yZvx6X5PEzovrU2MPvpAhlZGNRsUFtxDlqAJcC7
HTnTA_OYunvl7q9vsIdw_vt2lb5W5t14IBRtzhUqoEVjZagyCGTStlfvy1lEpqD8gtpOpXLtD_a9C5JZZV8scoBB8Si3y0_QwmKtD2DxlcfAksUo-BhnyIbx
pHK5tyoZlSRjBbdgysF9P-pSxQPtW7c4uc7sBNVDylmuoK7wO-s_OuBHxUpujBjBbpElwyOV3xAtzre8zeG_xUg3dYjTPXxvKTCoXzbPRcuwlNI7xxEBLvOx
3thsbfaNdlaS76HdG9Gw2NPcac_Fl7AxbpqFDQ76xswllwm4diw3lGRrZPaFRpH-m_wAdAF-abtfg-OUfnwdcI-FounTxVzgzkxpQU-rILwVUGWA_jRHZexn
zg1lduSZbVIo9_IC-NBGkR4tzpnlkzJ3ZkwXlKQ3NlOytO7yckVljeyu959RPe_sFCJNrzvxxJWaASqAD7gyVZH8Y_olRJ-X_1vWtUFDFK-FYw1fFwCyfxtN
iBdd8IQff6K_Bpt9Ofcrzpo_0e5A_vez7IpF4MaEUliyIXhsazMSit_FvqU0yC_PyL7wLCXzUnwwll7nhFrOEGTc-_Py_GEdOJ-LdDEQ-VPvB4lVi9zPdZ0L
SkUUXxc1w6G_uQ1pGCkiiUVf3iJSDxRF_aav1sNFowxtdXmnssMNZyivp-vvgEso0wUZO_UUB_GzzbF8EQ8xztoEgEsnfxF8ETjxpIjxlXIzOR-AF2F_RCyJ
lMxNSmyw1-Qyvr6P-TBlBRkTTD3RQUzvAdh3VZavxtb-xodq7VPBoBEokUUdYDb3Un-vkVQYbn-4gSmy5xrjxo5NZt3f8yzfVBGIlMctjykdlwdEyWIlxRKS
2BaRTddxZokOkWd4j0yzHunclbxqjXrlpaGsjzo8dUGvtEwyr5KWIdQnHT0bkHokuYOTvQcik4g_vrz-FGhPTTKClNueMI42TKFg5bl8kTzncvAqOU-YDrCW
Zxsvf8CYHlIS0RfXzsvw5y32FU8OF5Ob7MubWsYzxcgcNVIvwXxXBa1_-agbusqTr2uxaPxwErtKtKswydcfouqorktTzDFVqVIkyoCzzRpKnssxahs7VlKZ
GlcJswLllvVeyATsYwdpNULj_5IYuVE3759qRlcsFR9QtdVffsLqVlD2hw9piC_khc_J9mhC5TqlkUVh7k7JV_IoVkFBe-Sbnz6zzb3HrrTUEZAO9Pnnlzt3
XVIdfgjjHDEmspxVUZejlmiLdIFZXbsQzcVdFdsqw1p5y9mTf3yVNTGUHTCpFQ_ZGFfh59sZunFsuNRRfK_dAZgFVTqUc_OT-dIYedCKJRlNx3dZNVzmuQKJ
NE-D34_OMN-HedCy_b-tHzl-M9zENdIBUvPsss6Vz4hwYnHT6t-QNTjUzFIgzwcYspD5hziZjksKzFkLdqwvs9ZE-FAVDEoKeUX9VhvsPtgEbh9hxB0N_JJs
vxtZMCvwBVz9syuP5fVUgTkTwGMh5h7FpbS-bVvyxQvH3n1xxQpt0qkFruhEsMCVMcD_Jhd5g_PXp6oaeJhsRaVWqKlUjaluNGqHqbFZdqnkiSjk6_RGkrtL
TRnngF5Fq-uQ--nYNh6FaGiFYmYNsjZFD_vvv1Rx8bESx7FJm-CUGxNnhLVZGwrVqLcluKBt_7XlTSJFQ1gsIuyENorTwQndUmxYLsIitlWqzPzgTujd8pbQ
iNlCCK7rnxNVN7heGKNdsfkmNME1JzKl75xsnyijNelajEoXwJPYPFqRxpo87LHqJjKkkhRBxvt_hdK7qUFe7DJiuZ77xtOrmz3ZpeFQeVtE0Tj7YFhAdXk0
6t_4gwM7s6VetFZZiBhCV67NwKd6sfttTEaX7oiwwv669SjYYcNx5CV0fHTvjlGaFvREUgpq4zXTYpsVnF2UqkFZSjQdSQatKnLPsKCnlg7q43i3dHj_N1Sr
soL-nLLutL7fEmwwUL1wZZqckozVz1elkNtRtQ9hLBZnSRThmNlLJgNl8jVe7I7zCDnjYoFN_9yDPF_3qaFEM7JMqokSh-rZ6WUsJwzvG4j-tgBplYiwY2tj
mrqualrXwQ5spgAtzzsGP6MVwZkmNTHr2myvgvoZmdfukUi6aOauqBnlbrxENlJss8khgSxsYJWMUuHHwQ_JxXna7Oszo6ItIGeT5dQdgIVvsUbSUXxxsUxJ
NEZA7ZfLNMrPUboftTlwsIuU5Rj5wC_I0w_ADJwRtnl_DlKyDBHgjxBhBzZkxMsVxHhkOLMxYuZfL7gvhfptNR7VaTjsdKV_Wd8Eifv_EDw5xLBiBYBN77IE
yzXdBzkTxAANBNhx-oxzWLqkNFIs7btiSSxmQ-u8HTj-QNbxx8Vy-3wxnva3QlntsZNE7idw3lQWd5_Vjd-NdBzks_Pla_DhxkjsZMj5YlvLUr2keXzUjiSb
W-dhbkr6zgzgTsxyXlthvAn7m_vrSjO_Puyl29woQtn7dh37zoGx6_QlatFZgpRiNzZkFFPAzgykEkkzRTVurkJAIyCUtnmHsROZlZkQpLwnQtn_9hIoFVwA
kFmA5VrlYB0zA7-3dkH_bPxaVvN-TF9_
}

