sprite $image151 [211x241/16z] {
tDU7WGGX34DHS1Wizz_lvQZBST6-5l07F7OMbNES4ojSYN4sve5RPKFRD9lZIkBHCOSgouM-Wep2CpaaHVKJUAu4amhqSo3B14-8WKWavN7RqEhNWUGSUxC5
b8zvD7adAHyRcuaRgvge9XM5Uqqqa_A5fvhe9MK7M1E9f3WYrhf9HO689sKBvFlJ5tEFXO689pMpGCIJyW8HJueZ-iMazeX8Fwae4F6aVE5JPFv8Te289pKJ
vC-chto3Y0IJiWKYdjGyGDIJIf3_IieksRNJ9Rbj60Z0r2sYGR__s-PGKkcAXtPnCDNGxDJYjmzz1fgYeHNVVl8RPIuDKJxAl44OedoKeJK5QHM0nY85RoJ9
GgGtiIuGIUhRZnu5RoJfRpzw542IulQJZuA2n8CxtmG8I3ouyr60WCJTJpuAa90MWh9HK90OedmJ820nHFa5A4ZJUju5CdS5QJbk0y6RW3JVE7FUMe0Kl_te
Pwur0Ud64A4r0UdU40b8DuSeG7hl40b8zuP8G9gFEsTEGLfkdJa9QONT1fAH0BibH4fIFWhUXAJDgW4movqv4Od7tOLA1Eb8qmNAHQ4r8ObtXZGKl4b8t9Wa
cumW1OajqgDuS6j8J54k2jwKf8b3buGoWWAak8Wcqu3YfBY8A468XAIzilGeWpSrQHbx49W9Pav3ujWf6qMGdZHNbXR5cTEJab042KZHRP0nKg6PavEu3T8s
YWUtdiHjK1mL3r6SL0U-XObHHf205FmM5eyKGNhImMTIDeepfoUTiAf74PH2WXnb16MHuYX6AW1IaZIDOeZoIKeKGQaa7Se8keKKHz5aWTkFXAHf5BpTGwg0
16K4tK0Ie08W9UdrI0L292QztYXF8FbHnaYle-0ff3gNfqXnbBbdaB1IC4w2MGIKGVAzb00fq2Y3fv3EgGH84HJSSqXp2P02A7D_Hr8yKWPF8zKI9X4r0ieZ
hSEaE8gW3D9H1abnbBbdakeqJ0f6ok2f99jBZDH7zK4v98g6I64KGKcaEfSnKX1btf99nrG2fE586LhB9TbQYe846BTpQIIsI46wKF3MSaddKegG1BIMIwgS
EH79aqbxAPz6McuWVPE-IVvn95lBPv6u3VeGaXzJ-ImIRzuVGW93z1aatsEWQSURaiuf9beDxqco9GQQA_2M96p1cJi0FKb_SBCsmrkIlCx145NW7KbkQp14
9w0bPOTe1_99-I6wd-HrYSwSsLNlHi8QdRcB4b29ITY3CxVmd7lQvDxSHIG_vnAh5M3PE8eA2SbjAS5Q03oWdW7z-A4WOIlXgdmSVyha_Wz8GUB17MyIrymq
3O4498OeLZkVvgf14q41Kc3t4vmxDgf3weaa96nJUQsCS_U4oGaAa2GXOe6aZYcFnDkFWjGydSGGYKWDDEMHl7VxYPEyTKTFG0eUtF4JZwPaKYT4uJgxf0PW
cDG2f87RJxWsXgdJfW5ISmH8WH25BaJZRIB9WHT90o6AdW_ZRIAf0G7Is08rNaTeybhZp0sJ7a6-5K4jY1mGtZXp0H9lFvAotxK9loo2egGw5r5j2BsQy289
Qv7Lr6zJV_BEysLI_ykNlarzKbqwU_C0oS-fQCiwfWx9jivYDaBoMjIrui7K8V5ucewNI0urYUycT4Zz7ubTpZ39WGpIP7ogBidMpgUevqYuIEx88PK53oOd
oVQfkqWV9rqGNA044ayzFXT9LuZcqgtvi54ItyvvfBB__6JubrINtpJt721XvuoIb6k2-tzDictuwswVX7qgDv5eObatHFr8zKdN7o0WXNyePUnUEH__9s4_
SFN7Zcjc1QJe9_L-Y_gH8kdw3yEyBClCD_C3oIQnf1-DStxsz_d3khJp3yK_FAkczJG0TgxFV-xrxhfqhlP8Cj9JLFCyJu6fFVgJUbgFP7KgNw2cRiwiJxAj
VDNQVqKwladlHRAEoCulJ7eqsIUGx45aVxPlbmWCm40KH3SCzxzlmPIP_tR6HRwWYZfftTRZX7GO94YG846210aIf0RfdY11QheaI90WGOAKpv6AB2cCqw8H
JBOuJegY2HUxCz7flHSK7OUV8BQSzS3qIGVz3maI94YG1gIN1GaI94YG846210aI94YG844Aa211WWJ9qxlKvKdva9HDlhelgkQWFBQWcSr7gVQvulIQxDqj
0G
}

sprite $image151 [106x121/16z] {
xTU7SiGu30DGkLi4cF__srJCP7sxl15ThXefKrAUASYjd9fXdRjoTJw5Vh5gwtYbqazhjRfKgv-nPRZCMGps6LZzZja5IpZCVPc-7KLMdRgpXx6wojbOvzRL
JTMqMY-jfJy96bVzoyYoUafTmo9dOptNTTJfvhg1H9rSbmhQ95bNlY3behhw9N2ITUKBQgnhI48gA6zPhgv11Uspa2yeRtqvpbH1UodGMwLHJjuI92bJKDu2
MgL-Da7Po96KkVJaAQ1HqgLdFyHOYdTsFd0FfNXdvsFqLcawwZHAmx62t5kbwL11z7PffXrPk7QfMynWUvs4DEcqipq5nLAy6InBWPwHHgjAqZ8vRP9sNTQI
av86gvkqrWNtfAIEacE1dfMwgcGiavEHXhNMh6LmpqbwymeIrWLwauJ7WUHanZ8vEMcag6PBJbu2OBNHKa4x9UBPYki2_OZKObcmS5cfQGdbj4jqFabDOz6J
acFSIcYnmBJ4kPH0YYsZPoNMhWHIJ1c_afNc4aYXPQ3laD07KcZ9oKgSIY05bib9IXGKIbjAJbe2Q6DfacGPN51sfgKhRP92toVLePISvFiaQg2h9RfVBucQ
oyMI1bgxSgqanuOIfLlJKknWAc4c42T9pgKBdR66JbwgVUZqAudZaWeQIvWPoX593gVO6IjWPe71GCeNL6RYAm55TpPAL45HHW9ElgP8VtjhawZ7dpWLFtyc
wia9fF3I4mU0VlE9-eAQfRKhRPAcsYLHzw4cILHQYYyzSKzQlnSIOaa5TQKboyEVlPA8KDAzeIzj6H-MZ_YZv40iwTxG7CEheKZeMop51SNNY2U9TPKIIRhq
PD8PmEtk8wPIHkEVInnBCYD5II9qh9CnbaZq9Plbcv94_cwcRW6V97UgmRnKLb44iBsF3IktadkjqYMbgP_OLBPHNKvtVcbrBCiHgSmW02tSDjqCmXrZFyzZ
_t1O7CgUz7ErEWQxSo7d5uy29khC3Ft3QlvAjLoP-L7ghvKCIhLh9TGVowfTBPafVwDqIxTqIxSq_4fOowMPp9JQbMkpG2CDvMhfq7F4BSNFUxTqIxTqI-i9
qYtnSca0lnokvVBqYm5rAiby
}

