sprite $image96 [148x95/16z] {
pPW9aYKh24LHaSc__-t-gREAHtHOavsGPmKtv5mbX5EG1poBGSnC7Pv39-7_cGsUGPliu3F6ngy8ZUUCpPdzEMDpi50hv1sZJ2JX7KAzH2J-cDdgHDg3PIBj
aKIj1Wb_4UebOwlNgY57whKQ_7s4HkP3KgNLNgHwhP3FmBh-9pqtyI4f7s0KwHniTVtVCnBwdwRLVcprMY7V0nujadSnwlg_X_gvIFLQ8MU0XVq_tsBQv3oe
Lupj_BaPdCyewF_9SxCNgUnUGAu4sy4YcQVL9b6fLYh2aNgjL9-H2cCcLU5wQ8HCJqdLOwRdQ7Lbid1KzLhfXLMdyYt6Cva-9DLidkanMaaZDVDCzKSbjW0w
gRrbgX-WhhL-FSFsbgcuWcBhNzwsp919HQeIUIPeg7PDi6o0kYvUbirteKe6gEiTS9fSQGe6ABP29WV5xFMm93EH0n4IKxNaYrrNG04YdNo0EQaq7f9D-9r1
PgRg3PJ4iIrku3WDvSfq-r69he1qsD7mIkFtGeP8Xl0HZVN2KzqzDe9F6QBAuWkV98gqPofHMFXk6zjVEk2Bj2bXWdANI1E-GMUDkzKj8ZNu7YXgQtae-TE9
fCFtcRhCrcQBEHO9uKSqygEoirHY1o95XjXIVg-WI6B_zw3gcE9NQ6B_zxH9YAmk-s4YGu1pEatUt5R73ycHLY6K9FP_3uQ7MQL8f4YZAzE5fFR_u-V6WqbY
__SCkGPedskbDueKcVuNOwegYVtVGsAg7ambh_zxEfbTLiKrT2zIXzj1jb11-L0a7P11GxLGGTcBD26BFkrgdt-cRVgVI9Vu7IgoUKXI6Hg_GsNJ_rocsAjL
Ap2XWlWNeredKWJ9podqlnJ_Yma_4hNq6JDHWmVGsJD9XuVGs5GjB9BrD5BTB9A5T3dl_py
}

