sprite $image353 [240x236/16z] {
vDa7RkH034HH10UnkZ6-_satPuVlH7NlTrr0U61Hr63ktf1ALTrzb1prDHz5V4dzIlpS-ZjoRUfUv8jxFqDUvVlHQ_tY5CJ5BOvDon5MsI--gfSahYfpScMf
ih_KerwNo8RBYKpBkSXUKnpRS3aoBUTALcMEOBOgSRrx4fUMayDLPKviN8wiofp8j9oBZClPJ-iNfyvCIZPRpYvSlpWfYEastLOj0zUnvaML3pJYEK0iM-Cv
VuhBCMFsgaRCNfsOlUl5ES_xMxmIN9SJlQvIirTPQlRARXDxrwznplNwrtXEkPYzwzVuwFRUJo8OCNWbfMQljDJizOidW0LhJ5xj9oPxrvSwESlh_ANu6pLK
fMPlPLznTNYBnGjBtU6jZB7jRRfgy9QerEmrYjbR0V5AyD7WtNh4QV3QIitUlMzJtjdBQpmMht4Ql99IirVvuc8lYxSlDNj5fMQlLSnUwsrYx_vhV3Hu1QK6
h-GsiTUonkpb97FRJym6hs2DmUiGi_T_lKsN1Y-1ruhVu7MLchtxtoOMizUmnc_m2ZwumAjQO_PgrlXey89u_MrYhsgDqMihzNZKcogb-6Zmxlr7ENXzQrpW
zPKw3TwjFp5pWDTtcy0h58DNU9iwl9NiUvkkm6ihTS0h4sU2LtMRCYPu5uouLGjUapXpWjSapfpWDQrnnWIlQiHZJl2Qn9aJl2l49pzwz75x_s7Zvu9NK6ge
ia0CsZNWUzxMsvGnAIFjNXvnpyDOtEzbyTkhpE1qUrdSK6LuPgktOOr9o-8sRtUfCo4WRl6EqI06BO2RlQEXr51b4FTwdnO7nA1T8MRlMqhDLLul_ipCcU0u
hiD0rB8jaIpESl_RVeIMC-hGohUW40YnpJxzeAedTZRFgrFYyeSx3np8owm3DOwDiZhY05uY6GXrP9HL7N48Bn46Y0EBsvPBWH1UUV0ASAl6WSNr-bI4-0fC
948pDQwqyxoEE23FedZmJjJOHNc6b-68FzrVr5Ip3eRQ7-uyBv7y1CRdVSKmO0OFr7YALj_mEk8GNu69OUXwur7CsIZ__TlX1TMazOZdVKNcAr48w7wD9sYD
rnEh3Tb0kZMUzvKyVKMFkRbYJXNtxsFmygz2du6pj7M0P_lBK0WTm6AyTuWnfQdUnoAV5oJOr_Y3lZgrnG2VlEz3FMdbl-VeJs8Sn0Sl4Jh4axmaK93vIXJw
RzuATfxNvbM6QiFLMt0hvgolvFILDBwooViD7qto-YDkQynmePxb5Po-GkihurrIqM3UzyICJetdV8Mdh_Wdxx8aQ3Yl5nUgk8oNt8evsrzHL5yf-2VlmXjh
D6-_ng2EjoPzfLU-alt1komx0daziAynGLoePtq5bICz_tXpvlN1QpMEvUtNs987Tg6Uy1MRhnWAxokInLhC6ixRluq9tA_nkA_qwIiuNwqeQLcIB9jeFEzV
N8SQJEHDFUChyw2AWbvzjVF-u5sMZ73UzxSniMAO6B-kVIMdh-J9AzlXgyoxfNfNZURjrzXuuRvJ7EPLFdt5vYjkVKMdhv0ENjLWNdyt-VN3hPWZl0AyyHML
wYlAbLUZUVirPiRuRUppB8slwDLN6_9Yljfv2-PzVnkxzSCHt-3rlf8BNstLLnBAUsV5hDvI4KSyv2iywu4hNz5cgSxXl9xOX_h1ooxKjtbn-8e1vwjIA1s-
8YnBJ7_7Qmmc7LW_7AzMNubwNwrFN_4UnJjUOnWlaGlrNL_9uIkyzHK5-6eir4UDtVgXpU_VuNs2ikB2LxdwAfKmNutNs5h8wa9ztrTilk8VlbhDLwa4-Meg
r6AyFjHtVQMdhxJnLJbyjPB4-shyRcAzKMFlAw7gArpuAWVwQZRKgZVM3vzd_FELE5_js0zVPLg3U2Vk9ZbuMJnndvUuyHKxNnLQ3rzHYA_cQqpWNgZxliBf
A_2JbqzVbJNAL_Cr1ZUFVdXYtr-hF4JHVhjbKwWiXwyunbVZCxn-z7s52rzjlFDYgBn5yiw7skheYJqlCvJDLtpjgys0etmrFkg8s_N34L_vIf--WlSLKJBW
K5_DrzXuNskiGCzNvxDJhQ-I-MhbijYKADxvKFVNZwwlnFcAA1--sdcFzVCyiLi_jFU2c5TVyOMlal8QppiVweDNk2NslW9BzHKxNsMi3rv9H2cATvuOk5m_
z8hNVbFgoLxvgYJRhpQMUDxvK3E1_LBTzvNGYw_IHlig0RuA8ZxNZvTGkzV7Lb-XyHNlrLTH-rLaZKyFEL-n-OgXudoryrPzHUcJlB_VCiolc7p5gu3QdBvI
xwjKggzMojzulls5g-5rzrRZAtA-uhnKNr40RroDfU7rn7BXAreEN_6UhBy1l94rFdaxlzUyFhOEdxxAN-kh_iCVZjVz7holCgtcgrLB2k2D3RNZTRztwQja
ljeunbVnnFRp7h5uNqdrrHxjg_dvS_L4-IyFtDJO-sejifclKX1lyDrKVzglSUEhpNorSfoluaDTVz8dRl9SggysAI6yySIUrzzDhQy8QNbCbZs2Dxx6ZjTL
_CLNj1fmeWXVnP_n_xyJutM_oYKPyIe1lE70VZpnYwzIoKl0urVVGrnhd5EXTFYAjW3UuC7O4Lj_rwUlA7qtxtoegwzuEtnLSlbgtlbG5-DTlzDNyyJ-Rk8r
tbVnCnBgKdqbCRxwlXgB-IhHNjO0tc-iCMyFtYNb4k2hhmmrfKIFG-OutlZHaL0N-gIl_Yl7F8mGY84OI9h4MLR_rP8R47-CNcOxs0jo00HVqnfV-dm5M-SQ
j-KL1QnhtF4U1BsK_6uoZBBrtRH15XIm6t--FxxM1NNyILs6KNOQbo6LdSOLtLlz-qC7exXBVcGBxfOQtMYs-JsU50XlCJ0OG8KlhawBxM0Eq_25aTnYW75K
U4pfX3yCTAw6KKuRQePZ6EKSOox1x6vkVei1S2d4osC-KntbV3fYAbyON1XnbFEPOaxbunfbl_7alx2vkNS
}

