sprite $image218 [329x233/16z] {
xC610000080WXFrj5wa20000000009YzUrjoMmMYC7pX8xqMwFtVTijCuc87hAWpdI1G_tSvZlrL8op9PK-VhBc2XQE9f3DQG7fY0UabCONqSUmFwOwUpERe
u-YENYWOdyunspZwBkFBEZc7mJ0QZAChvlxcpmdEk9LV1v4EZhdP6PyTHj_7KVtJ-bbEzSIatOICqk5dvjnHcqncsVEvo6RNyHb3XxFH3ezakcC-PBlaZ5Qh
N88xxa_6n0mAnmwFQfWT_RWFL6GWp4El7f5XBCEn7v_ax355qjdEpaHXgPoU-HtrahbUTw4moeiBiRIqdvgHJcp5obAQfHDTl7fQMChd7kQlTeSv_T9Rocyw
pmL0KPNq_rXC6IUo58EzVqR7N11LIU__q3FMZZDQNaNVQMwFY39hIyKLlk7cqZwOBMkVowVHEBfbhPCcTCobVp2NPhkCRprYwUYMOh2iVHlVD9uiTxJB6SqQ
qj6FbCyv6NqS_G3fctPmnbPkAPrpHhlSqIvtjCiPxN97gp0q8q02Xt3ao8x2t24SER9ZdaZYLMz6nd6lz1H-00YWeoFZFCkw5oIpOnn8iZ47aDw1mq5A4TRo
21PhkhDZ7DBn8Biro0BIbxM9Onnnj_wnim14LyRX8Ak7N_drTumZZEC18Lau3W9PZGBG_IGR70-otcDQfpFz7UCeZErh503HbP5n2CXwLKFwNw8eMr9AnvUK
PdXr34OkFqjHHFn2-9ywflhzsEwu9_w_M3lct54rZemM7o_govfStaNjhKKVnpOaDFSMtL6niWynbs48HiQOggr6JUdZoBYMAiWjItTaqp5NGkejVHmPVvOC
FedC7T-KihVhMHt13STtYGPlN7F7DK8K1MTiExOfzNFfZYG1YAxJE7AF8uj9N4JRYSUHB0rh5T5sTaVY8qX7od4OsLOKVEy9dTAHs0Nnxod3E8pCYdKsp-my
uqYe0KJLL8uQnPpfafl64Lf7W-EN0MMOtr7_GMGJE89gHsNNlt99OvvTnlvf3-m8AXrvZE-RaT4TEtohr0YED76qnnpC4Lh7VtaVtnrLGJwNnd04bOx7-VPK
TpJwShjX60a5Ou_15C4GZbBL-yEjQqWIqZrkrucnxBUI8DdR4ch7Fks0N0FyyAYm3DKVaEng2IeTbwvztct8Ck3WZbYwbnsRaFqiGQNZSjGoPDFInr4FsSjo
ad7CRKu5V5ah8NjOOXx6d6umV1pra6NmSRI0p04-ZefjMs4vzxcCFQIzfPvnGiXiEVqL2dj8Uqke6IU6pA73RPa9jcqRIwWPvu94K5dQtRIU3lAUObGGg1tH
PfmFyYQCcvOxCCtUgJVS5KaK4oaY-9ObrEyRdGQo_Erh47bROiDIxIWAns4XGGXAo2_Bn-R1JiCOuroE8a1BafGVoBV29Dr12HfBj17NPc7C0V8AM-lxBZd6
PUq1XcUASQSbceWvpEIuaFni2VoSICIqV7K3vIw8-opH9CnX9iOCkMcP8KDQtbtbQnklB5iRCcAPmd5EoyVbybo-IkaXbAk8l2rbmn8gnoKtZIKgo_lbSikA
hvuWBlAEyQw0L3ZEQ9aXisACwId4lTZ5bniPjP2SbJ6NsfPvQL-k8QtnShy7ubRiukb1Pfj649NZj9PlZ-Th9b-EN4bVaCKk7c_ltNWl92Tch2tbLyi0Ngyh
f13NOXkFLp8IJKd8UHrpRKi9jylQaxYjd3_OKxo34J6b1YIRaDCxbabXYM8kRoz8NhzU3wNS4up8ZWr8nYee6AUs31doaN9a-fh865CJqXrViRRCvIKUqbgu
tAvW9DFQ7aYe6MT-UObmlruUCKK9byiBCalkcKXAMLXELMo-90hF8BYiPSZ8pMDast4vNsXQIhXUrjvQ3KZKZlKukcLUurkGG2ohnj4jKLWMwtSR4kxuZfLb
RXSaTZAwvVOv8Yj7xyFBooPaxPYMTcx9kXhoM-Febcz8A1tTiWt9_Onk2JGWMJh2kVIM9IHLu-YMA2rBIFoPerl-0eblCxgb84P-_mg5MmAH1kFeba24YQDR
me3HBOrs6RVqJUQ_zk100000042Gl_K82rG70000000000000W
}

