sprite $image132 [238x149/16z] {
vPlfbgEuiyIrvX9A-VqVz_ujqprKDLbG35TTPk83ixJnwTzHX4CfxF1pLL73VqKPhJNDuR-W9EqbYU7selQFADnR1Mqjb3i7LjjdQGhtLEIs9RvbV6lpLE_O
Ehuqtx5rV4cwO-luebkspYBhxPDGRjWwG_Rudyo9xzrQfp-6kjshZIe0XtQetwYDCjgJTOFNV5wKTsqT_29maZjaTsWZMZCwThvBV0lMXD-tStqd4-i6dMld
zswZo1jaZftDMTstETgedqsy7zzkzfwRoQmUgn_VRjwhoxkqpd5UQxuqlKNh-CBEQzwaZGhQ0ThT5xr56oKzid9mu_jEHnkHLq2kW9DsblHpJzZWiRelsXV5
dpkmmpFnULwKdtl2XfrFudUDBntfLS1xqLkrKK5p1H_gV7p_UkluWWFqZl6DtFQ4Grtp3crKqJpv9EyINxzrvlEY_epdEjOFZG5lrKRaiOv3bvCa-9dnBN1O
Luy0PiIN_cRh3DQ5rq6vW7Pg6qLsJRoMR-VphFEFDkgEYK_p-gcrlzL6-O29JzePlcMw_OqsIh9ZulEyQ5zQfi-FBnrWFMTdjDstjhbjLE2Qs9NVHlkmKCK_
kDtcR2RzrjcdzLs8NTOXB4yI1koUvimwvlFwVr5uh6lOWTkEiLgVDUlO3glFEou-Bfwt7sFjkB9ry2LpTpExsx0-Byoi7P5PjtfXwm1DSwRZTlQUsnqNMZzu
ltNZU6NhIEOQQ-RconmJdzPXrgxfmjP1KN280jIO3_4ErWaQhArSs3gAfZabrLfgf5gEn7SQgtMZIrj72vL4XS0nLK2-Nju-UM4bNjiwe9WOg34AEDTOEKlp
PJDPaI-UTII5gBMKoBMef9GLeABDrGMiirjdFLqa0SKyJ1mOMge-BsWJDArrXYY4o90K0akkaIGJyBeKRXCqeNNMOqM5bX0YGLBE0l3hme0JtpThdVM1RLPG
6CWvXCIrAB2-uFhDmhwkRXtIXlh40yU1NCDGvb81NL_e6F2eOZk2ykYsntffww2XvbWYZHMDB-H5TJ4nZ_YESchj4CIG7NfPdzWwACIf5C9OqO6yKYJA0enB
YKb1fSg-zvpHtfkaR5Bha3HDeGASOab5KVvu9PUYq5foabgKOYve-n0xl52iDjfzHkj06sgA12gSCXK1RRrxuKnQOoQ0GbHeBdI8rJ-OMvtBZ9tdZDP1gKyJ
LsYE6UEwPPp8A241d7CIpiofvEySldPp3cOmcBfDQXsaM069aI25Sk9CaiCd5KWEjHQXM8f2Gc20v3j7LdsRThIKJPXrXbGLd2aLoe8wXe6nT66b_8foNKnS
SkBHHi2tZYFjJrwOpPfrXg00IieAf9X_xo64rYQcKS6QG-PC56icG5aFdis9RVC2PZQZTTO22w2bvYphFOIMC5GXQOm9TTpCCJB0h91cHqoC58eJNvlIEf-b
m69YoVJFvKcPTL3Js6v4rXmYrm8eDxC39hOIaZwwEEqxeNKs9A80PVbquTUA5aWQo7NiDG3MmRflOWwXzeV4g4vy9xJEXl2KrgBGzGZ0BnENvytASRm75BhB
kgZb42WzYNijEmzuBcuTQLz9MG0f1FoEhwHOb47ZPislzu1ACpiGM8F27Xf3eCT3Og2-qKOJMiUHi8xw-NM9aKSvnH1PotWFD1KS2cpBIx5t2Y6dKDh7zfqm
w-m88lWTMegLYcXEIKO5ZVU073InXgYzDmgXB9zKdsNJMcUHzUQqaKfA1T0O25fAIkCz8FicNfG3lvOu1FdVjJkRoLcjinZG_eol3XCB9DTO9PFcb4a4KC6X
XRMgZngIBTZqy6JpMiSyHmch46TPJgLIA01NV3InZziv17xq72AtRXIY-O_mfxLEz-i0ekrbud6WyQea4RCZuvt644P89ONHpjr_pdjbwyJacXWwykPtdugo
bYevZpOIGLl3kj5jEUGIGhLN1Q5rVs6lR9rOH8YzQcNMPbyzRbN5OcAfYa-pYc_dJZ9sne4NJ9VLhfnrCYkUI1i2l_JXqN3l6tvcK5Q07LO_lXANpd5DV6Nh
958CAi767k8bjPqltK80m37ntaaKHVPXxShMYNL0WdcB5mDNpFx8tLRxxfZORzxkirxQEeNnmR6AFo5Mo_NbgP-uhFjstZUnfajClABTjFCAGRNP5wT-3kkU
dIUqpj32kj2wlElNQ3E7rT4UxvJM6S974dRil8emByQ-IDRzrd5cdGjfVLxmRzXsfMn2w-pHic1pRKURNgn-edMke_LvMIzdNUpicfXZc42xQUTliAesNyU_
DfP3c4NBeksSXklnJTwjPjCyZtRO-OJapCrzUyYID87MjVE-T7Npz-AxbHHLcaLxdDUjid_vDHCHOIqJQC_O6UBSV4vWUUAAvCjfB-3LhNlRMQcmlc2bnVz_
Mf9lsLcT79mJT70gYy1i0ctD8Xi9jCslBq4sMO6p2okBZM7TE4oWZQ68VBApcMrzVKas-ne0pWQMvNdHDaRR6RJKIYHPnzUU-hp3jQOEwpbQLPQ1AjAMqNOA
RU-Q4g_jlD2kM7i7EoO-HOjVfAowZBRNqe9YhBH9surZ_c3d5wtzPZKdi2TfLNI1nNMZxH3MkxD46xHFjHgghknigxEuRew9Jz2QBTk9fNLwn_LJWPQmADEV
j4D8xSEwsQw9pz1s0rfRLXRBQ7ijBTQvY8KsQNjf7t7inTfS4vyoCYTPUFNYqNO8-FoMgHwXPK7tJ7oQLLaaPnttZDQvMhIHYqoxj0lLNc21RxUESgg0ZTQP
fDzshb5SMcQLVsjYC_pPEYLoep1HiV8GnP2RIxlmdZUnzGOi9lwdTIXCrz96L08xj4EY_yh4Y961rkGNh5hl4ppinfUeTTYWTNdFVnAZXAn0mu1r6dPgV4bA
qeNMi_Fvrf4K2e2chB3UQlXhMZQJL688ZLs9gc_YVQKG2MZDc-lcnpT_f2KY_-FfUyTFrf-zcWJcD-nyEwzPXxpgEV8pKM3r7p4ybRsZjlbsNeigaSzxx1Ts
1O3xb6U-_CqaLqZTn1NWyE-wHr9FR8Ldjj5GVJo4wXOk2mx_hdiaLLFucIgqekqLAzYr5CT_OPTB-B6AzHSjzywFNebLjjh8PRsWJEUt4LCLVZnKLENeGVk5
PJe_lbJR0-hGCglpMuUtqlfeO_6neus7t2MyWVnPi7xhgH65DrKYtfLk3JjlghBFYyrX9xordNr9sr2uhPrreuB2-of_pIk0yxEiMyPN0UTdMRUChmBOt23V
Cxu20CuGUyVuQbMqCSJUHR6mAyc1chD1lbzyfOGGWwFxsRc6MwhGBktzxLp3NPLeX_RsyQtXpYeExTtZI-C9GmatLw9VJmKJIGgtLwOIVgR-3m
}

sprite $image132 [119x75/16z] {
lPU7ckig38GDHXMHlF_RNZTz72_9HZSRPxRNtnen0gOFAf7EqzTLr6gbz5teB5ONMSKlGXCjm5scvLjKsA0ku_mjVvrulCVBMvpP7Dfkj-PEmxLKt32ENMG7
MEOhGrF_bQtWvavJkihV3J22lT5NE9smFf8jt0l315eVwyempJBGj0xwS9WIrRXComL3AGAM-QD3AIvAdnfASVqzJ3Zu6tUw_6KdTmNneJ35_MstzeRJcDxV
oNteE_ZACC6__jvS5Y3P-s6QnSxJtjLUWTluS9JU64hMcI-TLds4DONWKBA16obN5bKRVyDQm5-rAgHsCYxON5MhTOJg70cDSW7YOJEFBEK7r5OXCfHKe10M
93avFVWRancbo50opa052CgvuFeMj4cE-6iL4a8cBCZC9FLFQhL4Xf9LoeNcJ6LcflM5rDw6cc5eA0cNXPW0qvHcEi3m06ojFVYU3Vv6Xf9I0S2rshtwGimC
XO06xnuiwlRZMqr3_ifAG424tckYWWH0S0xJ464LqONRh4CDOpkv5CGDWYKTL2oPOFiswpYWxqUW75ixr1gdu4wkIkLOlxYv39ZdrV82B59T7SgsWWzkPyQ7
qYvL1M0c8cPOY7F6aWfC8ABsqz-x5XAzhqw_CPJIwQIaAaIylWZ2N23Da2SKhVRJtzOu0rIIpUbtXj998ap4l0-f3FDK77hobm0AbxdW-SmH3utB-kBWOnaX
p9bLnwOsJel9gMfTJUxWy51wT6TJOK20bRr2xGVsReNQ3CgptHUgoq93AIVe_ggsKuTK2R40yuCRz5tANEmcnEqVQDj3arz0MRXM5nEosSbf5IIHnnVPTkTC
zrxfySGlGvDGgo29rqR8NarV72fg3uzd2-xUzFOJQgz2KrQU8FR9imEadaCuKdk6XgQ-7aeBPgkMa1oyGWaZMznuUWqCfKqBQiSITQVNRsWDoZfqkDb5i8GE
U-QgF3s1UqTCtDyubiXRFCYTboTEzzL7-NzZkzEZb177nngz4OOti8GhU7IO2MdLYwOBCx6a69QH70gxqsQERhRxwqsGNx3Ap2GcaMgt0E6nbc7H5gPgPduA
Lq9q8rJrANGhDRQKLMlbUKEj0crKS0EOxQ4qGVUNLLNqEPIv6gNOajgETFE6GW9fhI9lNwcNwb3HvrYjJAGcUGf9SVBpw8e2RNPJnhsFrkhPtsSMAmDLjLgc
eBeb2OW8m5eJzWB5gJjK1ghPiNwPYj3qbZ8IPMXRjHuc9bpVFoqLs9GNgUNfRQrECz66zOuoqIzDbGAgB2PlKztfadUi-yk_-Mij9Qo1fWQSnWqAYFWqhTOO
r0zCEVsLsiDa1D2NSGVscrJ2oZ5WlCLeLO_2VMSQRr9XQBp5IAP2EEnCWKFBdrgCMx4kHESQNiJiJbCNKZsac2xa9ZY3KPnxm-bAvRFDfA5RygV2rBcYVY2z
LhupEHTHuMBYs6AaWVcD5YFXzwWU9YJw9jQT9WJ7VjDfI5FEqsVq7m
}

