sprite $image260 [303x301/16z] {
xDdPTjim38HXTo69cO6Tzt_RoW2hABMeaxjk-BFdyZi0RKblVrnqlsSkUxkgUe3k1o-oJDPXAxaoSUbLFG2yJDVAgvfOqfChVdg0eMXUUwIM91V5-AxqUfJE
IsPWOkd-Z78oxCxsiRICBj6rdrpKsgkuuB5_zps9wNN2LLhXudv_Zm8fT_xYLSrLH6Zf-pUBduxmqiVJlg9Pg2JNzzljXdZV1U1ylEhaaeZa-hPnjHWlConE
hzf54dP_PZ-douU1FESgBi3og4SFDsaOSC9LN4ek1jTC7B6DxcTSnMKs_DrBFf9BAwxYiftBVVHhhbh6JSZT0qkZz-jbh5V6iHcPt2LhhVV5KLzSI2xRkDe6
rLfeBTv859VvtCRqIgtzw5fmrJQ6LvPQELmgehEheF0QWHLQfzT0rJ3Zz1gPcG5pkCwvwlQWEDfSGmF8nUskwZ6zx2ENV3LSDLxfTU1QQrNOaaiYvh4bkNEX
LTd-N7Rchckjye9yJxpIgdgVMxZ5p4fbMMiRc24Z04EXN7Fbw-9UeLnoXLSKMYYKPIsv1hVmIQxY0aa9oRNogbfo6OEBd-4ghi7a4fFB2kQqMt9XSkKwOZ5U
LGikuywbDLVLei435uDhxLN3nPaY1XSBvtosEdQk35Xv5LPgPJfwaJjOzMZP0D_J7eDhWbMzzzRwCF2OZit_bDLyf6W0kEPot-7-voqSpmpP9LSMl_rWtqxK
6sMX00mhmbdHtF_TJeXAaYPLqcajfEVxbw7C_Zu8fCiVnMAcSvmguigDyIzYSRPwZMkyzCUuH98NOOfI7yZqiRZsPxbmtkh36W2iVCJ4QrV0Dha8yr_oCTXj
tk1fvRgAvU_6gzeLJ3IJ2H7l9dlfGLpuVro0-z5-l9jn6PTn6PTn6PTn6PTn6PTn6PTn6PTn6PTn5HjXILGKboIv6hb4vTFqLueFATV35RhlhF-9VAY9g_g6
m8Tn6PTnHUCoBkCwEkCoBkCohbGpNCPbNCwuNYZmO5pbuUYx7youZAiV0k2dWNV6bRa2IDnBoVTTPrn1np5nx9J897mdbxR8HHSgAIY9SV-sNFrzxbaTH9No
D5BddjNVrnoNGuq5eGfJUImnn9BODyKL4fRk5vNffIHgGGciRuRhsIF6JnEcrs8j-q2iHkbRuN9HkSo1wTMu-B6bLhX8cUWtkL8INHjSlJ0HuKtRVtbuNlWG
l0Wit0QNID8gvKBdXgASWuKBmaQPbYErm8MHFtAnNECFN2wm5CNW5YxVx-Ndnn7gv_9HQ8Fhtei9lHGNOE4YsGpTXOjL--gvM5_Y0fBYUELYsMwOkKIXTgvU
vP6Bxi9Kvc8fxrKkuTgvVERQwH0khPqBPEMYmJq9c14mTGYNgvmBnt7XmhvxKa0CuI2kEEfGEzVff9LmoUaKN-8oBjS-5pno6HU9y9DaZd-TIsDDNAIo6TCv
umhBoSWgsz4X9sDVEPSNMRXuCpdeLbyvbxjoqLR7S57jN7rLN50xLySrSONgkN3baWhsBbSzLv1gJaQHldgkeQA7aRlgkVgAkA1-hexhuV8DS64zNAu1hb3F
Ljyrm3LKSv6W5hXSqSFO5fTnYJR9HQzm6LUGul1jkSfFnXwBjTpADOJjtDkkBdJzu4D1VkXxdBa8zw9tvI8Clh2G59XAUcEkbG8yqXB0xLiOY6PJ_FDSw3MU
OuykJZa49rEEOLX-rCm5W9i53srnbT_g0yya07wwfi6DKsuCRlbHKdGoidlRap7eB88qn2b7ECYK4mouCFxfUrVcYao4m9aIRzzY8aBMbSkuE8q3O0hM0GR2
C4zX0iEPoxZYHOkcInnWcel1ZrDg13gNtZ0kcIQvQCG5oSkq12iSfI3zo5AkTpqPqKUTDTR33t116Y6CymXf1jK__nBxUXz5bbGU29rR1odmO5mlPbmGaFQ3
8HXNSW0SQBy1UoJwwrjzvehJ9I7YvVh0H9edoMaFRysrtPKhq40afoMcSHd5cydlvzBOwCFeUI3IgyoqZCRhf10vSPdBk3WRPIIvdIJ7FdCP5t4SpscQqJ4b
UJBo1oxZucN7YdaRcvZeEabEXhVc4jwgOEzwQQithl5pBdiOfvs7yPRBk4Z6zTsgf6aqQfuS-HCkkqXCH74PwdNoDIwxfhu_bspsaKjEIrJm8iYuIAVKU7s9
7Vbcydsv-YzpfHwuKb_amXQuEdwD2mS81G-ZHuSlSWrDS0sKab8kGgI2hPwGQEMYeW_wGzS4LuT4X5JsnSKKlFUXu281_XpEN6xOpCrShX4kJwKnXO6PANbf
FAU9GsDAw7OI71BHG4obOTS8LuVbN5wcStetAJ5rDxVyEC5ohg4PhXwBkO0JmqWtoJGdTrpZp5hCvRjckBe-K55010zSkd3f8vSGK57ekcQuKhqFiD-0XFoH
Atyaw84h4ZaeA2IiThZA6uXGaiDjB2ccsq0l5rVVbVMENFaK5TeFHOX2zyUvEXVm4l5MXEU2w_uwLywpBEcOYdADGz_D6LTk_Gl5KsgIjRnX6TTzdkRLDPsB
CWT3jsHS3_N3VQvB6LTnncLSzMLSncLSncLSnZKQbt4Pbt7La74Pbt5nS3_Jy7s5MhXI_ZyB1oJrS5s3_N0_seztauUCoxYCoxYCQoVZCYxZCYxZCYxZCYxZ
CYuwLyXbN8Hm3ekuZ0jX3WkuZ8jW3Tld2Zu0-906i0m2OF20408YmjUvQEP1oBNFvNs0uFtz8Fs7u9CPx2onXt7c8k-J5y4rUjVL5RPM5rowm2nZkevnvS9t
u2e9TmEuhgWqV1mp4o9lSzbMptcGUhUzoqv6ktULfockybQFjTtgDLKVLofFrC95cYDxZyHUUitUWLEiDHLlzSQL1iPLg1LFBt0Proc7s3gNdej7SQKGckLI
ZTC1Dww7sQJJ65TUL4TxvG3QuCfIXtdfngl8LALSMUfeBZrjnP2gXIiVWB-I582bi0Qk2vJ4qs-cIqMuU84vd4ikwQc6egwL_dWH9iHZk4GqNZfLaxu45cM9
cGZnfxX4T87AN1M2oMcdKMMDKtGEowBT7fngv4fDfKiiFdAb_fVhWQd8g_ub5k-m-1OBKgnocItZojlJVgVgYljWesvf8R6etCGfuhmhhT_AXrHRuYhVzgD-
faKi_vTgArpb5uluL2jJ_QJOgTPqAJwn_AXLQ5MUDiTr1NlAbR5IBD-UQbjSgVZKAsQj1woVNcBZgUwUUSMiTOzrn18xrTwZbzveiVnmsX9NwYDNLBwKiOu4
EpNd5UK1wpYmiKskZ7KqM7jSIOlbs5IRuOhtN7gyLahRN5qgpF8hQOjSKLX-AQsG2nvYLO6SoY-caH-ZxqVemjFW2-5Neo_4NqWAs-0AdmV7cT5HOaTo6LVO
oBYCgwXluJ8k7tA8Urp65Qv9XAQuKZ_55NSlNH0LrhxAXRXmmTmoVD7jbl3fz1BE4VFDa36Fd_QlNVDGLYlfWV0Vzewabihl_xOR3aRTnmZ60Ro9hjJM2Ln_
DTFIKE3hj5rSNh5QiQwuNAfEBcxjnKRvmOO5Rojb2rhpWq0NFAEl0LqEMezZNVKZ5Y7M5_qhSQ64GCKLLoQhlCF8rkGSXB9b1X-k6S0LLDu-Aioonck5jYXz
mXqLl0PQVJfVY6jLqcVPPrnMPnXSHeAM47CjymhPMcrJS8NWIZVFOXfLjAzicopZ3nk5pgwgXf6qyKEuFkttOdihNBDBkApABJbyLzGhBbIG70INt-AAkCM5
v-32lY-Ajokkh2KRS2AN9tBVXoimhQv8bf5YmpsIk99SG1lvR5o_p7lH2XTqvxqO6bsui-R-odCNG5jefVZA1xW-A5aw7oXN05TbsfXNQCix3WIqJnaaT71m
bq8WvDhL4wRrdnVH3ILnzL69Njf4j-kButgXFIyqfoMvY3Kr_lJsysXWAQD0oeFH7do97Hq0a3y1VIsJvKH44gM5zA3CqFVrumzmVOWgrpMkFipM92shjN6k
3sk5IqfDraBBtii9uIsnbUvHcltWDUqKgMtW3u_Ehz8To93RuU9U_CiUiKEyuWfd40cIjiH55XtrWajztW-l9M2YxAjmXTC62O5bXxKGRODbXxT7UkDAa52I
KTQ4otF6bOgh3aGZhjpYmeEzcBbE-l3O3X2qNZ74cbdbD6vxGSh1SahA4Ec0g-A2wug_48GRmTm-K6g-jqTbFpIWUuoBCJvCKyvSjtbIjH7NijIxzIMcAJr-
9Ckec75rnqEXVLQlz0CTAhaZ9D-zwADoZyk6lSXDAFmyhJsmviucT_jqc0ifvxsLnf0ltPZtS2tYyibduS0rxrHw2AwaVxGNlqojyDT5lRluxnXJyu9B1uds
A9YWkyrwxBD-ulLfqnVNMZ-dCo96N96nmpLjtH2FoeZyDbpgvyKrzqL9h8LvPmRMS8jv1bcaJJxAsrUNzRpeKTZXwkSIycRrUK4KEebnMDEivro_nyMGfUwC
-I4KKyC-s-e92HhyPL9kNsNMJ-h_DTn6NN01uR4HFayPJBExMI-1bnjSInhRD2TOnKJH4kCeSSPbCwwn7rYbuh8rYjzzHUm5ML7dh4-T__qgpVtjNgIMpT5b
ipUZrIIVlT-kd660lzC2lWxNFEVF8QM8zhYoriUevVOJ3q5qWxQuV2PuqnfnGlSOutW0MeKroohedNLtAPju9xCmRhriQvbTzqJNeyACtX-2nOIhdwRawCE-
2UUOqTDjZBZ8Q-Y1r9phkSqrBsnRGYPzfUBgElsiMrmu3rwtk9mVALaFMDVnSF9QvxruHxpoFRZ6QIBLewrNj0_wKJCkFetRhEyO149EwkeVuLhhj1S_xiXy
VTjcD6PNlEpBvn5Nq0-uHDjyHzKZN5x-D_j92GfxN5JL7LorzPykoQMuS9vHTv3iHS28RJoM0ts1kBnF0mYof7VY6gWVM3ZNzpu5SUNrDxatVP6ua3PDfSoj
9ylq0xEylSx-MSph0rSKN59R9dITuklQ6crAPY3uL0U_QNWHb_P5nPKOmhvLpyULDUCAyQcjaxZOyDPmk24k7_j-GbecOisubk92hZEkLVu0ZXLUYWlYNLVQ
1fVVnuMkj1gB3NwXqFeILyNDMun-k1elmBLQeP_-61SHMOgN-ih21TUQb5A7u8ePrpoZUgctzgmy7HVq7pRwqFakuunhfTnPKCWuifuLbSF51_rfDvhYMZVW
pSK7FIjFbeKR5U9TlQi_DgCKWZxaTHTSMMwZGZoSFXNN8gwDrlVfh_OR2K3_yOros-9w_vINifVXUkDwu-BXuRlbBr0yLVYxwAstidPwA_cTHEtrra7gDm
}

