sprite $image219 [381x259/16z] {
xC610000080WXFrj5wa2000000000000000000000000061swslPRHY8mV3z0ckz_zjcqfinb8iC3ed_DZdjCxpo-XLrj_1S5CyNhC-uwofkhzPygG0-7TyH
ulXm6902zNS0SEqR8CS6g470yu-0fE7hT7ZR_YFV6bw7X_pJGFuo_tHxILxxju4_z6h_O_uSd6xMcmBRm1_wdrduGw_v4-Ijj_1dzf9-VlvS71swFVgn_nh3
_pLSV7BokLC7CVlho_Zfii_blndiXVvs_7JPwzCJ--ZxxAtwZ7tq3VQDYhxHFlecUzRbHH_txRjCzKRwBO-EAIZz79teNs_VA5_SH9_cuUkplxu-zF2TmQQV
uLTn0trEDtmzVInlhuVldpw3_y7fzyhuj5sTJFys6ButzDBwd1g_xk7VLhUV1P-MwVlnKRFU7IwFJzGCBOpFwV4fz8DlkpjOsNvsV0R_8_M2-i7tsy-Fp_lu
t1C_-C7dclP-_E1p8loU2p_uN01VwPC8_eNsjgCVV8pmEHF-OlgS6J_uA7-Wi5y4N-jFZi-byL7ss1lY6wOV_CccZutnMOQ2FydqVzgB5iRtNttiZOzonatm
jRv_-4lYp_xCvSRuRdsmDyNt7nw8uU-4RzCdUrDylpw4_VhuVdrmPVoUIb_RRuplqbVsw-FxzSbU6l_WlFeKmry7l-twO_lTyBK-woD1sE-1h_NnAVjTyL65
k_ejz7tsVIocZsy0Kf-utBw5_VhuzJNIf0yA-mNn-xuzI0E_i3VWcwQFl-obFd4rVNDFVAhwKdvGp5xNVInrTq2I1dw8sHk6Rvh-kBw67w2mNng_-He_ta7F
f-ZPA-EZ2aD-uhtqJIk-Nrz_yBaFXHVa1RtlwlZnVuBApVtdZyVX8RwPU_X-_P_sO_xc4oy08BzHy27i1_u4SDgTtOBUYk_N_uf4rH0FN_iV7HXyyMxsX_ZB
SPBWASCMNsR4zqzVXn6ajXp_xttj3tOFwQj0NJyVoQtnZw51dNW2V5IUxEvZ5VsXVV545y1xX--VFiJmLQVTC_onlh0VDaAF_LWVmjvPDzV2r_huzyNWUyhm
zVJr6o7s7drKy6twN-qH-olqJSEF_T4dzF-rhyBdxVjOC0fzZLrLYFtLszT72B6_Ullw2CN-hTllQOVVt_2Z_nFVP1zzLC5c7ttQxCE_W7tqOo_qO-_Hxwde
-zWc2lszx3D-GH_z1MOV_jWh_JRJy_XuuMyn--tqsphxy7jd7_xrwSFV9llmTslwyBULFlnzeVoOFlpzUVh4Q_px77tgD_ltq_BnxtV0FqyV_-wNuHdI9_r_
zWJxqvjFxFjfy_V2fpxJTVB9xfvQP7-svcM8ofVsu5W00000O92_zIZsLJi000000000000000000000000000W
}

