sprite $image271 [203x277/16z] {
rDQ9SjmuhuPX2Ty2afhb_k_s4AHLdZxExzHcsNd7Oi-UF0L1wd-VBtvH-_TFwuZ_7VuWH_mc1Fvynns0zkSxAgoEFmBocxN1MpzppO_ZZ0h7yTl70DxxQOmm
WoH0oCxMsZ-_yk1LiekVCumJmPabsH99huJuE9yFbEgdE2IATLJEcUGgxTRuGNEKv6TPQZbYCRWj1T3ApCgcRPqVRhEFyPi78Wf49TBlKobHPfkbwyB7smm_
Q3058S2tHChYR85CQuLilNS9ny-q50JBKITu9rlEbRBjP3kxUiR_m_mCot50Z6sPiJ3Y2deBaekZrdlQxDs_iyHtZ8G8B4N4abHo9TzZcPSbiRK-itBqE3w_
oOx79G74SbIOaPjpVqgBqYfBBeoQi_Du_JzzyorsW7o37AK2kNzacvwbBO1QbXBPxgxHP9wlc6-rdBXdSXx7-JuMBKuiK6PoNgBSd7M7DJFx64qzFrqOFYa9
C128sGs1600btmzaByf4fE19gU1fwMhZqxaS3wu9NnQb8d5I4cRU4U6Yp9HI5aKz9oPR-lXiNvwJO4lYdSAjGM48x6rXYdHPD2yNHdjPnaWUdpt77fHWdmj2
1559hDEswaFAcSYqswodhBwMfKtBwmlaMoXugIZ1GEnrrxRSjzUEiIczcwsF6QV5-CJ29pOU5R6A-rhRinobYOMXm8LfAT6BecwLnIsdvvEvy9cPn6RKPwo1
rCbbYQ1cW4mw3HI5jIcijMTnfiAZUsI-h0iVjWGOn6sPuKH1jYMe0grTWMia1jDgbJYlIHcfxffCptP-trWGn1s3zny00qH04cDRWixAY6mx8NjPkZncrdYP
YvxS_0Y2U8dtJCvzZys25cp6jb1mgte7ioYZCSl2FlHDOpaGMyBtaH1rx8MXOba0k0AdHCeQHr7iBXN5lRd6Ca7dzspBHW2uRwhx0t4MXz9QUyQc9CD6JaP2
quBUU-EaQ8ooUEJhBVRO7NOobeJnVcCLx0pm9EUbPG6jK57I4JafCwCfUyNiapAwIfG3BsDvXdAm1FUInvx6RFzTa0ZD8YYNPL505AK2-iviOrbAbFdlysE9
4Yp9lHqumQqZWlVRFYJFWavZNk4t2jLNWnfLnnXNztYSSko9yCRSFvl2atKiJSWLM98PL1Av9rfHcjksqEEwiZzEEIami34VAK1HGbLuXTEv8bipsqIKPQYF
lIqJTrr3rzFFun38amInVrufDP7WgOhB8X1PhNSZMdlR-UPYS0ptqTerCXyUIu0KPdmV1sxAdWWBePa9rvN2fZGVMPHbOTzBFwRcokBetsh51wO2GgGAyBxh
Rmm48h0KvP4Dxc_5mgR0KPGA6gjEJShbtYuTJr8EGO88n1uAtoU2E76_LdIMn3fevx8K1TaotYYKnqgBCjYlzYY5miAGQm3aFPZpVa4IkB_V6t3OULlWDjiM
zg4S5LjEokLsNUzBGHByscKnDqKACcRdlX3WCb4yLPrYo5OuLq99AaoBiezjSGwtekHrvUjQabz8EKHi2TSqtYyi2dZlYNZ05P6xG5lrQKdrCLCR0_LPopBo
wiUltc8WlsJfnKs1z972q6oTWQ1NOCuSAMxAjA3tKR4xb-dgUKrNKJw6hw2G9aHj3VzBYKsfJY9adQuoOrv4jaQLvAQiY3edPBtmB_xxM90XB8OK4e55sOTq
QiPpFxw0JN4Op3Q35mKjULCuZr9ehallUJmbEM3AB8eMvNqol5yd2EYKg_h86GzdMo4d1TcxDQfKqw8qNZEFnoY2QPCe3M_ELgm3Pt29N2aMXO2oxQ8uVIQ_
VIVEzIXMp-lHEmnS52j20byftA_wLNWLobn7kEqIMz87snZeqwC-XzAkjImjdwD8bcm8ECcRKehpfadxrgfE0rb5UolOgvf8JQRYk7HTmqNfJr78DPIYI22m
tf1R4QeMrYQyYbDPDR5LYSRSbD62OzMThUwkCLhlpopBFqF2eeZUcx-Fs4Tr6ywzApoTrNvuDQEslcrAXiRgigxAEQvyWZ9cTYmANHn9VAU0_zqIq8h_Vhsl
MqmiHSCU2ZhRfeXNbPvNF08PtH9b6_EYYiERibIsuzwIWinYdgqoeDOhQr9Qp0EZoknPb5wKFjfNEwgMsbjmNxuf5LoHwxoN91qtvIp9YcrBHjCykgvBu-qB
PQk__SMGgbcP8Pit1QepV9_hGmXQaJkeLMIBcz9Hallx9CT-V8tilIZLbpggNXII-eIYCt1_yzgTsPh3ys3V3Pzzx3ZKztl-ShqY_uzP-q1k7id1C3ngX0-1
llzrr-YcAM5bSxYoLRNlp9yJdm9GZcQnUXEaKw23Vg083IAU4WXXPimWji-Su3CCjbZPG5QXRWTbzJv89OAf4IBk51M-ZS7hH_iqbiJiDZ0bRiCh9NUA5ORd
J2NdfNWSlSrHWQ4ACA2oFZxCdz7ya3rpGHuep5EYWyaMnKNSdJaYe56P1EyKhQybFU9lCHxVPWJ1f61VC1OHfI-3JgZW68ifiTcSYbTaDXQ2FIAC8zNAuD09
ocZv6mQoCk63ihwI2P95mKm7LYHA_FNYqMSsXiNCUKaoUOt3FDDGbDuR89Kfw96oJu0P5Ibc0ol-fo0LgQ_uXjWJDuwY0ElbYcR2Cfx2tpigDU55ML_9f2ZX
S1qo7a9gUyCh37MAhqWYik8Y5CN2uXkBlm6IHL7kb8fmYAe1eM9Ws6g_zs4UAh5IiiWP1FERGBfdnZVzCIGoNKq0feEYZ6gqpPBR45Wri2HkmseaNiFmg4I3
TugFh89pKZ9-XuaBPOQOmeoPTmhe-7fzeqmamhPIMX9tkP5DIHZFexS8O4b4pMAzDcdJz6tvPv2rrpefOc0UUaTmVLzb3695JSFs1gR4U8oIpDZ3rcXupOJh
4_mqWTmMBkB5mLZ4PGe0BSfdBFEb8rVh0v42WirORALixYP37Vn5SLQEAW5JkltpsUrseq1DPHOlOU9gMRdOGR7glbgb-ABWFXOp6R9UEiRAXqHbohVfM9JR
aCtYd1B-lpjSOFuD9I5YfZWeZ2MocQZD3fFBA4Xb53EGKJXuBCP1AOldAaww0EbnBOm-S78rdnfgPeBZuOz71zbA9zH1usO-Ys3CxH87qHf7erJqeYNEALLn
u8yKDs7C3TE905ibOZDwM2oJGN2LNH9E4RWnZ-LeZTjge56kOax_WD0z5ZieuMgo7boiuZOEKLi9qn0hn9YIYeL7FVEIjCO-bp4u6kNQoPp-2T1ZUb3I3OwX
1uBxE6X1xelbAhj4oh7wXd9OXfrJzZhbZ6-D8fEoSdKNPKQZC7OAb0U9ESFtnfIui3kFSygoo2MBDSe9nfaUukWKm4q62UR9L0M3S3t8CXZvdcg4Ay6WCcOB
qocF5lAC2pNA2KOQnUyKKtSNTuT2cEX6LNt32lD3mEPLX0yNGaHWg1MsStRAOHcLUbpfJZd3A3rcaKTGT_NfgRWz-LgiOonpm3GGCpSp6gjsDRUYD0jPNAfJ
gdyx5ZnGGjpL3eei0sGNy7qiyHcORSGganZebgfJbcLeNCTaw_nO9F8UokAxnsqtaAyEYd6ua7Y4wdHisvO0z7aiOr6wXVso9RDtkc6U3wdYUSF4V0OvReJO
OaP5sIh8W56th0NhArOHubgBqZhRi7m8Reo73UkRHUKmOLQEFUYYk8Qw6SRiSIotFfOzyRXKVjEr3Kk4YwgXRTXE2OWoYqN46ienbe1lMrWEXYvB7qktNB_-
xIE_wySDitp8F3HSXTJk1cXzOUO1Zvbpx9c4CRPAju2PFAtOFfX6kN3zkNry5EKKOtGw5aI46EuV9E8RYvglTLg9nTvWhCFVmZuv0w2dqwVr4zroVltbM9Hp
ZFny-66X4U7rLRZ4J2rM7D6_fwoILLcmkRavsegjTaAt39mCv9HI_VjOpDrAkypUzyaqzXGH9kAPx5yMrzYs6Ano7qllS9nTVpaQvHJ3pMBDeeQ8S3oEHPx7
GiA8MEyQceKvvfx1ZBkbzpWOiky6qYdd5foC9J5FGfV1Es6tcR18n9SzCqCrj_2o91FGL-m4P4y3kKufZFUne5iCQZzTYxX3HBs-btjSaAWbgx6uRsR-O6cU
9v2sWLoXz0BKycO9Wm7iqz36OifZLyt5MYaNfF9Co-BSHFcsEgU8ju5Se_IaKVZ94k6igYNwpC0i8WeFe1mLa9K93bHAhTZ7noPmAylg9mV1sq1UemIrDA9R
RBzy1mCmSuuzYToJo52npD3ZogOaFP8OUaeP6itnCYL1BNHBgaMWhPWSxrxEFIVHo4gznbC_iC_dYlZ827FN7oatiQmMv9UKP6fPT8mYGXyC0UJAiCvD5SWz
IImLjl3jOwizmqsKlgKG8gl5-3t5wTnYQilYcZFnNAcRAc9DOoKSMMs6JqdcLW5kz4GPwjaWlwSadYmT4s5WZpc6Qbv9cAgItwVncIjoohOqyorjITPBVcwK
6rjp_14bvTnIXJny24n95Hx7cIyUrEQeSfetTw-Xh08USgSCZGRvEqeozH3F64G-p2LNZbq2vTn3GRQOhiEIScCPxTANuwyfmTJJUCA4-ToXRZ6K1oZDZe8L
97Ar83L0X8rw4H8TydlA-UcJ-1Cc37Ed8lF-ZGd3SqUKp7CBByZHbYiVjo7-WgFANrZOekeQWva9rejz1M2HZjmpqTosx93eissGroaHronzoRecvaGiebpj
YinYAwDrn-p4yGebPYSMVXgCHzSSkSKqM5Ok2gzvzCsAXtu5gJfaTVdsAtt0zE6OcRkR0kQHwLu_ZkyOgzyugYQvWD4d2oF-kyuFDv_zh5WjoAyfqJh16FN6
65-OKzAXYX_BZr_L89Sm8PrICJp-FLErq_Tb_QucUM4mOu_aNECG4dkResgGonZjaXMncd-dC0WDKZ-5l95oZWbjbEPHcFbdPWOLfhQ1Rt8iocymurBype5q
ohRbHKiF_7_Zg79PjdW9utgg8O77ko6TajlBc0pxdiC2YxSxEkMmv6kOokU1Ctt6BAfmZxFAyIvAMLuzcLwqtZkGNZRB5l_fvhxIcsLYC0mVePb1xqJxN-rV
b6QKu83H5F6SVBtSboNRbBWvHXrjAOmE64Pj5riBs07J-G6n5CMqMnbMI3SAezMKeRQFkJs65TAFOZ7iXL7760h34wEG0HJ_AKFjIV75ZAVuhinuYl_AzAVu
JTbuYZ-cFGNCsA4uJbbx2fUado3EXkABQKz1ISj7n8Po7TEHmfcMxmYMuhCoxIbOqxAj64gpAOFpPD5Y8nXAAmpy9yks6aghbK6ZoQ9SIZ8JniV3uPNnfsmd
A-cH0_Bx3mp5TyhyAUcByV1Y0lMHeRXYMbAee7vLhb0OHp3DA9dhOwm_QIZUA-D20RQKWheDXj82mxXEGI7UKkgFTWRCSMLGBrFqHUG2nMTbkDRhbBGiVrEm
ysJiD6MCsfUI3SKDWrhxKNZdrTvZohZMdfIo-KtCVXX6xKj9vfsn4yPyBKaF2czMfJAxOMflIjRt-8uKni_u30MiitcQmZi7n7uOVWn7JpbGnaaAQ7iyNDad
upXAmSE18V4f2lId2EuKDWn3ENIeJZX1OLhCWrBPk-CKf6LRFan1NhI4AIXCYubmZCAPp4mEerZ9r_VA0GfMSsfoE0MqQ9HN0ElxZz9pYbalbOod86sFr9dq
XtXA0UT5CtiobfBj_wReJpodADUShXXEuO_Li0F7JocQUK4TJaaRYPQEK_GH6KknRsdjo6NUbvbJazDGydR5jP8U8BiKKkuy592ErpRK-YT59sigohfvihBj
KtIofgBeV2MF0-Bn53DVWIcu3uLrxkz3AVUXfFjGY6z3MMZLNmFOdDcCHC7o4VsNkLeQZ5BJycjKub7AijCQZWBQeH2YKVOVbXADicz9yIYL4pq-Zttz0C4e
chwUC0FG7-H5usYK_PbRxq2fwJwKSX_AUZCAFw5GB0fsAMb5g5sXkaCf-jqe5FsuUainnQ20TEl3KR2tAj4eA8HVBuEb6ekYbnFnz0LIAPIvJax9vZ-jCPdh
5BcWrX2KR7V-5z_y51qbWdbCT5EYKTOVbrHNKXs7ex2vVu3JOd1XAA1tI-7DRHwvngFetckF9oSJ8b9uCHsLX3ZHcb5ZKfYs45fh3KgfgxtD8owbhkGBqKH6
K2hqWwTpuUgNY8oW-ASKURi9HRiHHUv2qMv4aHjHv2uKxKOKkH55riWKMrYA_2mcHNul7aLs2qQHPqMYo5z5eK2aamMZ8HhcfyZX9gV8cMQcoDbcfSWBJKcH
rvgF8gyt6KMkD145SZ5CGe4uD0L5V1fF4RS6KyIrWPGtSGw3A13_tePGf4tTAP1ceIz5cjQH8gthHP4ETQ58fvfJ8DrgIu7q30qfqhjM51bG2mfaJ6_k51cN
BqM6vaXvaz5vKMI2N2WoHxXCaNcwH85CrGMAp1PUfCYClKAHIJjDWSpREOfCtGcApDvHYaJe24M2z2T5ueId58dLFaN2jKUHYFr6aQ1P2YHkMuh4xfiYuVkW
o1q2e-E9b7y1
}

