sprite $image82 [322x205/16z] {
xDh76G8n30LXCfOsgFzg2MVVF6JcBs6-9-BM9ycx6gN8EnkY_Q66zcCDlL_SqFtnXlRZ4UtNQqNOx-vSXFtuBTllRYh0VjqEjUQ8g8xp6zYXMYBkZxCVvyy7
MDWF2-yN2_jXOJ_EVfpzEFjnzkFinzcFCnyM_do5nLhVRqg2MxrVxE3FBvpxu-o7DVjnzkFinzaF2_jnzkFinzcFinyMl_BzrnskITZmd8GDyoVOZxCVvzil
Pp_E--Ninwtsmmxsu-o7DVjnzkFiXpNxSURZU3_XfqyLV7_2Fxye-FxqidxkS5xc9DnXNjktcoMrOIS8u0UGBQcxH-__jFyFOSecoc2YNQeCLbzp-zMCfbbN
869OUNbjXVaJms6OXMeug7eDimXaT1iEmooIoCyDH_O4xuOOL6xs11T3-eOZEuABePuOZkm9ajYfDYDxWiHUjHcnvu8aygxXCFG5NppB8uxWwuOZyQ-28Fbo
jHbf1HaJ-7gr6KcDOCefDsVvcU78dpDenfJ_yImFmurOCZF6VpCSINy8QievuVMpF8BCxHQR1PfQGpg68zH6S4eo1Pg9yuk6mqzRmH12heB6EU_FuGYaHy4O
GvW2p0n1fhGnHFD1QWJKduB9E8SmqGp1p8GvkMTvX58Z6ElqXH1L1Oqn-TLc-3c25c88OGwgcZIax5IRyG2sWZFDB40fX93jliivipafum5q1ESgQAOvX013
dKGcRZCCgSTah3ev2xTRV9r2c59z3JNp8TWQ3ZyfFsnfkbwpcJ48KxZMRgZ8nrGydFEaG6rANUnL9rvG1Sroc4BKAZW-fe1IcrAgeTPLJXA2bcOJ4XV1OKZ9
4IpvSPLpl2o2YjTmhOBZOmhbfDGyhZ9Z2Bgr6KwX4JpZMORqJB0rnCoRe5bk1Cztba7j2nRxOvLJdcvzCD8FyXaCARqWsAvokeRS2fwlsa3Q4VGDurMDuDdE
CgXzGTyGYKGapshe-_c21KspQGJFKsqelIxeFuU9JSvnbY5r23Q6JSvoba7r2rP3di-mzUiNzCVm7DM6KfVWlk4vpZAaJi7Ma2Sq1DKfs2OwXbzTRIZr2VQl
ibzjXjzgU9Ap3FK1xXlo58PWdr_767vdjQ5w0DzlI77uBORyOaFelO2LiCyGdr1jm2w_7aDyvKcX-W67ORzVlo6_oX2TVls9bU9RgWtuPa1_bVlFyYaMk7-L
yPJmPeWFzbFvfPXd6E9pmtmSGxpJht-L9yNKULAE_m2orBpNS39Zp1s69rdW_UTmDZF3qGsX0m0wOrW5JIdYkDK6F82VQpZRBPgEMcr0zRs0xpHy55Gbh887
h3OynWBxXXCjvBlWb7YmQeF3-RMh7EFb4dWJd0zsKi030hQ6c2-Nk0YQvOWEmtFvjQkCQRQxe2aTn90wC60DDgkS8wQrsiJ4LmpVweU3-xNFOPetrORJIsUP
1rjWlbLhtt0ZQBvW_rdkN-1oj07qs-4acza8FZCatkvdLeuAs8uXOhvUPZc2pYyzlFS1B38xhbzhcAVBPMu5VKDGnFiUG2iocHtOhrtb51n1xwHGlsV8XaRs
_npjWhIn1yCeHz0TG_5D3T1kEUe0-i-X8-WPKhzW2FqLK2OhXmTi3VblXDKGlzy0bpySbSFwjORi2cuJn7v3EZxB81xq1Up_EE-lCdx5xovc8W6wCrWEcDnf
A2AZqn3oAhIH8C7ICO2VjigIk5ZmXmzWiNK62GA47Nq0ssRJ8oWjgop-P87BjhqGjpNkyFkqLLRDVPN5xWDYjcwn2PMG3k2d6i8L9CMy6AAl0TxwdzaYo4fe
7Nu7VWurooDCy_OvH4y3B1NmBcWaI9a3-A5Zg2ZJtmbJOCRo7EuQKhiLkjmahVNxQ4D5c4EOGfod1D4nTFpSBIvMKveAyzc6LV3lXeXr32CtXju3w5TeWgLu
luhBf-NQFeTACdCCfHmGvsaPF_2lXc1x6HR2GWA4oiEh-Aa3s7xHgr6aFIDCZ7CCYQvXusTh0pII16JQhB4pW1-xoaeJRKbY4p7DroaWPgs6y1TusLNRLcXk
_wrykb_RREBb0hjbPflQ2OEqdX9IXDjWJ6k7De40iG8M-tZ06cmDq-MIhKOpwVIQUAVY0aTu3N1J0CioWokRVODVJTgiydm9k0a6qZ54p1l2YWUd0TQKROMs
ZXyX7_KS2jEr0bga5ubw8CpF2s2nUuN-fDyW_VzLL1cI1SpqimB0xT1hvzCYg2ApyeM0xIeZXiiby5dqkCUEe4ZIpDQh8ljEltQL6q4F4Sy42H1S18lLV2jW
pNQLhrU-48cUuDfVsWhT-dtXSyZ8b_9Cy0R8fa9_fL__dx3X2v84rnbKQG27uLF1Gf24bZY_GRvsbL-F9sXI9ImjxJPZ37t18gEeikCt3E4AslzJh04yZU4F
1MMtk7vZ35V1BBdVvee3ECPmNz1CHKs7FXsXNZebyWYR3dq-Gr3TWiMADO2d74Fr2ZO3U592I7s2DW0tOzWZEFoMsAtmTGkM9MCCrILOHjQZh1t1Ji0nXlMV
-ls68Ln13ZHdbLyKB6q6OMFe2mujtr1IAzWFE9x3t0W-znknnnyfQ0Ht0KSMiwrWZzymfEvBdDbLOOOXLi6k0Ho6QzW3E896S9XqZo5-w3SCqGyuiWXoIFId
2fQZvBy
}

