sprite $image128 [227x235/16z] {
tDQ7aGCW30NHtT-0-w_sikDtcdG3eeCt82s7Vpa272OVKONHm6W4nWgJQ38KAPeZSI8ICBaWHcSPZy0ZSTn50gQ8av17O1CJ9nX5KyH15mcOPyIuEH9CdX9r
wviKp1l4H9YHmZ_CFR72a1J-dI8c0lkcy58OJRJuXTmmXKUO9XT8tRAIW4LKszkx2FOGUdCvTMqtbxhPLm0qDqIzFtpQnEMHW4aJxtTHBUBg8ta_XK-_uKLS
UYH12wBwc9YWHLmL2TWGDK-9HYrY8h1R2kyJDLT6bwqaG1wcC4zlCPT8Lwqas12rL0frgPT8rwmaQ68UfZ2Vn9k9OkEw3aEraABx_p_ynevpuHHbOIlr2-_g
MNCgKe0WJsB3oS3YaGxCdvz2HanMwXSRNYiZOYG_2yXJf6ruwpoQYHC0vEUKWjjHsF0-OlbNmruHsGg8wFp3fqBKzbpnqCVohD5f-6XI0VbnAQG3HBBt-78i
Lqu0a9zSGXQucavctreqOemHZ_yr7hvAY1Z9JqeXdmgPSE_H68-AnrF73wO3yqTK4ajOanPBRRW3y0Lol282SkB0_34fNClGezyXmyuv0UxMpqiX_eqUHN6t
rXSUGlm_MO5C2jklKkW4IDtQkJ4A8zxVhRaKjbGArnvbG8RqriI16LRWJi2QIM5kmz6ZIK50X1Eef98tdmfVD33FP9m0HRUYuDbfeoR8UwMGLHfFrAEwMzbF
g5lq-wKmj-4zQ0brjoQZ04I2l5CAN_OUbi9a20Naw9aJk2CK061LKjX82iKGYcwbrc14M87xfP1jU69c_5gtqe55tABVB8Kl-yBFGc6rL3i-Fqev0RGD8nBa
7E645DfFWAsi1KWhZz9E08o4-BvANfJ2t71xAyzgUxlw_ko3AdK2fHAYKaczpPoLmkHGUEpIPzMUhA9m0k8M_NOf56Oc8le1qWXHEG5zYrxkba9fPc8PhHmX
6J4_Ie89Z2oJ4qief90EwC9mHtW5PEkCo0A2u4FVeWFo7Yaye_KHOKz8b3Rd5sxH9mvDfwLG6cwC925AI3j_YtwAiWWffBqdywFUJ8oaH4Jm0KH0YblqjwLG
0q83j-fxMQy2CH4GCd3fBRe2l2A5-JxwvEZ_GHx06553XXFYr2twQIbKXy86XFuU8k-jGAJiN41EI65-AFGN3HI8MAnGtPew0SxE_qGA8HHA0ns8zNk18ZIa
7n7rWVbzAUnik0yVk1TKVoBMM0uLtv08CZbAqhM2S0ApKYZDp8jZsu7hY9SQAExMM2BfLfP9TOj-NWhnRDhCe5jH_kEA4oJXKhVgM_GNo9AtOn9Fur0ep8n6
9Ca91kHkFNUBZdQz8eMPuUurCJCICTPF7a7SmWbSkqM_A8NEW5P_DZDcLdD4RazmoBsLEvC53f2Nf11cXcKGa8MA4IC8adZ5tYfkqQ6IPwKmwL6lGEW2qLu_
QJ0n0BKvvqzQablqmxEGmaJhoSoSGLo29evwLFXMGanlqSzAeKMMp13aitFxjtAUGQ7zClXWEQ-CgALG1HUl1_hcJqI7cpceJ2HGAQ3shVeMVIqXXG0ySQ1l
lBjmBu9B06f8VOkkfP1wL6bWZfZaaC99Y6vLj-XI2livCxDuFO4Oj91w2FNUocbLVkrJZ-fHXH_bZ4qWKdlIqzn22YUWJeKc0R5xz_OBOX0a0Sv26YCU8KL0
slKIsWapmzq9GaMX6GCG9sxH7ykA7pb8e2SHuwVrwgLFKF4Evh-yTiw8tmPJx3CAaMUGaZg2d5b7h8oyHV_-0f4jqRgumtPBAjze00ZNjvNtHrrTHdlYg5lq
YgWOjfGEWrImBsiYWoT0yIa_0bkJk3wMvRuusZAvHGSm8yOOlTcOhGVuuDwYd6uIqLVXzjzjE03PezhZutbhFgQB3qxRuwkEjZd4zPC50aYYeCj9YeeVg_WN
aC4F4QCVktK2SUil858lKh3CKR7Zirdhrx3uNC-quVK5KYDIP0J4t8O3a3qg45V8AY15jWR0z23MDI9_723cDZnzWUWLSRZQN5dhWnfMX95d4HrYHeZVxwto
Tsc1YEfY99NVbj4vkmOkR0rktGcHqghirfGHnRwZDjEGBpkW1E1JnLPx0KHXmucV4Rb5K3b59DaQZ57lHechtcKsG7_-qbRFst00CgBSToZPLZtAKwWH-_wR
-yiidhJX04yHEU5dDnVg6-SH8Ls-MM0WSXeEe4fHiKJ4E9nRC2pj529l10048Zuyst3fKSLlzqvkuTQtUlx7kct_iVHtn10IOlv7hoagJX0LvCmLHHmlZPV0
OsBMC8I424OP5RCD5mOZXyGMEryy_KvBB6tuhxUcJeW4QIdaJ7YelvRKECA6gwWuHzIRwny2_ZSHiO2G47duT5Gi4J6IDvOV0Bz28V92iaT5ImFnSv1G9xUn
V6b461WT5Gj4LkGx2fcAcLlyGnnKmeOdKR4I3Rsv_l4kOwjG-3_4SHOHa8m8V8seznrTkZMWX8GuOyC1c22AhhfXbt6OdRnHyRcL3I_2Xi_kE_E00u3Zjraa
NG2aZ8hZQdFvttWP3E7lYB4ZWf4kZS6kRFZT-mu3EW0pn6NHDbn6nVEVS7wNmH3cYBiPs141CH4LpwdPsu0OGaO4u1SG0IayAaV5ixl5kxkCZmmHW40aKPY9
Yk-7nC_1438Y7e0eR7XLKV5yoqsrDmyX8s89NTXmGXPHyLsRAqwUtAEC2C3mdaJ5W1IlCn3YRPihlXf-06J41O1ViQssIHkke-9tpq9-UWWPa14ZuZc3PXCs
N4J5y_kE_X4i55pRwW7GZpQy9kzkJaJ5Kv3Tpuce-_Yj01XkBcmuU2QYuhbzHqzhH4A8FiKGpjdmjpsgk8aGmh9yZLE42xmv4FCtDYfvr7iGaS4m8BOIFq6u
XDd5gBZCHiNp-mu_MpU12A6WBLVOyFceU1wI0Ss7Zt-8SYzTVlGzseO3S28gdZ9rs4QXXBxaYAI4AF76ncnK_FxcYXqMom948Y2XK6auWEQYulStroSWx2WZ
Cc0ghjg6jwjHSRVt6Cq8C4LSI0cfPcouygXMsbyWEhvKX2Y6K2C2SYegzbBUHyIo4A8SGaQqdstuV5HSYx-DQ3u4Of0IKatOy7ekAcwbR_-nUKJyr0HnaJqg
tjW09DrI2KGCevVIfX7zLqJuKHU0oeOZkD6lC_0mzb9iQYNDG4Y86CArmbm2PZQS5qvuL1x6MkhsB_jJH02kDJJXiY62vc9K34GUHYlhHEBjzMkDcY5Y2BSO
c0dpD1mSSr4n3-EwY2jYRmGvYVWL1oLqllRc2ivHQn8LP-Vb3D5BtJURTHwjbJBiNSID34fenhU9l8I4I3PyEYgkfPNY3yGLkOrQVGAHzr0eeIyxed3doOlJ
AYek8YfkPLUCKff3A-SGCO9GGeb8QJZbY6z6nLRsvIjbX-mRiiqY1eU7unV4U3PqDqji-9jHyQuO6sAlfRJT3dYfDeKOB-6XGem53IrVd9wFYirsH1-z5b_f
DZTGho9IWdz0p07HqFgDZVce-8cuU-fIrhLTdpMYE3BHAX8X6bg-EAsZOeq8n-Ebr6A8VmKY0VeWn6G8SG4fNvnkRqR5NWisMUkbzj8tIJcDkF0GCY9W479C
l3Wz6HKRtlFkjJGlRTk3D28FeK344CwzEFr-L6obha9IwgeehX5v21dnnnZ79bwSplXBkH8LUrb__AXrj5A7HWGWFZEl8Wkd-SIBqqbKJ3PSrCFmjE8qYeGe
WXaWyWboxiLfsek0RXSGrpxTN4uf9X63Xp171E3Np8lJULIyrXL4gsMtTcLeH1h2v0G9eTX0GoF2Xkkek5rDmtqVoNOAaPMGZrS7G3TV4iGv6pw1Y7xjPn33
k-lpxlAqettYnMaH5KyZRWT9ZRZzMoA-g8hdYFQ_xkv3MMuG1g2ezRRO___3wKgv8HTxq334EoNbrRCW90C3icF3fef_d29oVO7jJ8sQGEsdp2h_93vOUPwu
mInVVavAnLInDs9MQqOylX9vfK9wG8m84b-bHauLkp23yFV_asD4jjwEZImCYDnXB27sXNWcj8tJUTvc8bixDX2S6wCHo0d47K488eKx3kvhbU4fX1P7BXSI
7OWW52BFmT-sJQUAOUJ1sPE8-u4W156EPyo6318X8Z8YSD9TCT4dPaYqKveJALF53MJWzhqoelTHFb-HoEFyQ9IfOXW3f_S2MKTa4Fh6QGBvUmCP6upy44Do
BoSo2F7n1Z63C5h2ltfhu782TE507O26B2HYOiOsJkS1gTdB45vid-0L4x8Le28aVS8VGTXu5uvlG2wQ4fZ890A9IW18zDP18cVY6deI4OJyJJdk9978YCO_
CEuC4WdCgITx9H0t6ZEr4nau1HwVtHA_iYN7Y0Hs5uMF1FgeGMHil8x1Ae7ysr18ihJ-zUhkFM6gzxJ0koSIII1xmzYuaqJEu7-BiyE5bWdHC33AxJRI6oma
-qHamjmuRS3CXD4MmgYNQqWb0BuW-qG-ChrUHjmp22bXDUr0XgJNSruAz8byPFADqnc4yjpN_gVVSsCxaBmKw1DRynOa4eXVHWP60Q8XPKGTUM1E8gir4lsk
GknOm8SmaXgIh36apuQJo23KPq0Y5NYn4eY834aYdSXv2n9vimGTl08JCGYX8GbaC8ICEqRC80JHRrmudmaTo4hWGoi17tTyDjo96OGofk13cYZwlLM20Lbo
RECqKpqaaZG0B406Bi43ScZZD4SPpuGXcV0wqYk1i-FEmtOLCnDwrwJVWMxqO60fC4JC8BGHXXz27nr10gR8wrjkTm3zYObzgkihgWGYj1JmBRS7WX2CWape
o0YIYCpWjra1trNy0nYIfJGJ3YCb6C2NKa1s5UTJlRsD_123iAObhTfWI1gHePX1wC509835Heu5Nfqx4JDFzgGhcR08QSMEb092HAhN-GeYIu4SMprf8II5
Y5HlvGMHwAErlTN70Wb94WSoeG0hUojTZYIHzJOPbWe5M8li3mO8oIJYfgYMf1sB7eJr8TbVGyV2P18HXBwC5Z6h2OdiZWKH67T0t1V8X6xCbhGeOaWcaK1l
Due5M8_iLm8i1NuGEVDqFXLE0dBOyLPaAV1y08Ylgyo4zKXlZDUFGlk5L2yB9_3F0_hCEIi1XkJxZLJFUgOm4ywl1EBxm-IEkKDlVWl2-GtfOo7_4OjbGaVw
pBdp9IyQS3vInaBX1qduq8HCM3Dp3Zua1PbmkKhWF1zzTCs6xAS2RNu0rqI6fW9VHejO2-Xhw4JEpuJr4nzK5MmeMGafgS2MqTO7ihVApFd0Xf9ra9So8OqB
04lNq8b47rs_jqvOHbiFYOwwQYQiNqEN85o-8IisbAoFl44ch5b3D-3wnluQEe3_8tB2CjhAbS06uFsGSHCW4mZ7qViW8-u895AgjRlrLW9ls5i1l1qImFkz
FYPdmiy
}

