sprite $image127 [258x187/16z] {
vTpfTkke4iLnG1FKBaNl_xRNVPLLpg1jP8mvKlJ_dAb-3GZRlSxoJuFSMYwSV7RX-QsBpdzfWYZMDGt4kgQ1iFhhpczT6C2wyFpMTUUtBZo_TM40wmBpNym0
8fScaD8k363zbVclRF0XScq2gTAvvx-oGPAAnSiS0BphR03UTUUtudNdjqvp05pQGDxUXUUtph41Ub-lwIm4yhNErMiynp8GQIaWEDxypGIiem6q5v13pSy5
_51QJmMi0ytF1RgvD2421pE0P0I2b1Q9mB4CH9e879P0f8d0SDHBeaWxWICQzD9Gu8W48WSHi5hFVnI1sAL_O21o687eNKZIsa0E8M1Vqfn0v2W2zXK-IJi3
aGC9s1VuAFTIW_cF8X3STmAh0S0n199lIo1ILo2bEDsAgLW0uXY1D9g_N20ENvPmDyGY0T7axaLvfy67L1MOWljH5qi4H2CXg6qWKbCWTMwZFXK8Y4xktlGk
WYHL1L9mcuN417nua7j48Cqt01VW05R71F9nWjXw0-G5UaSRk40vWNoqdfyBvCUABmXm0cavVrwWSrOtJZ6ElNTMzxA0Jx9LSm0kaEvB7lEijsOTdPLU5F20
RDPc_h7B2qosMXMo1fssFnsADG2ijyvlmtLPWS6j1PLxQb_SRmlu1n605msYFDze6_cHGBzvx2Vxuas1SUR57G3M6nU0BUy-8z1jdddmRirl2WoW4G1M_Vcj
qTRnZZLWPvxLXz1r_J2CcmAzi3X0kO4KDJbho9m3ctTWdTVqEO7e2K2vGIzbHU-i_f50TDQGn09iW2S44WCeDv3IWE2iuO60k2-5CGalBn3A0FX5MLu8sZbh
O0As3QpGJwbOmBuW400UUGBM9EY9WBXVTMCg4z1408eCvDMWlRD6Ae3HMMG_4052G03onQVddtmkTsza0c9Gt_DcG0Ge0GVOVnpiV-JlBp01qOvyH-G2D4q6
K9BDNr70eW9GzfCcAi1JXRnGCe260W8LiWmY5U11AjHAm5ALmPFtDp82zLEq5B1qrjZ_HkYR2s36hNS8U29WGMULwUTsICyAf55U23hFYl-gBj0dBc11TTRq
RJ-CJmgapWqlpRyAx2D8CTFWh5vt2DXIY7U3ZWXmWF9DelDi0hiCe8zBNm4Gim8ML7lRF4I00sG9EFsQmghmg300sHP8SHg7lljv-O7QAaX4W06K4DZy9c3L
0zWMIEopK0oF13h-ZdmXWSxtW2e4mtS08Y1qQnXW908PzIuLpcy2LfKLG0N2Z__KLj4Qq282wCm5oWtwhm1SO63BrcZa2G7HWHBav-S2A7rpm02uG2Gl0IRx
wfm0VwaTqjuDm0Mi4eBX3i05nCvy7pVVQ1s8G1q2p1i1bGnql0DmWS4PmVtwDng0Yri2OQHDazjD09s9G2K3dGo02uYxvuSfnZZrtba16mBvE06Vtq950WFW
0XZSew8GWPS9T6O1zGmWLC22TxmER_e_AA0p3QXei4T07Cr3NXQOoFmyPAej84YEvELbWG2G3S13hje2eXBs_VMn2e3EcHJPAWk8wkWtbgz2c41u40Em3P0B
Uweh852Tkc_Zzr4Lz4Tqoei4mEQl8u2A0lREK9h6uR_6A3ehHBW0Q0y1TDuJTbP9m09KTRwbjv3x4Qpf0G3cVM5t5GHg_uZ80Q1pFG7hQ0BHCm3el3kjHj1U
8300cx-UW7KeWUGt0Q1p1G7UWGHKl07G-UiBu1W2Hc00jW6g2V2E86041c3pLnJW7KL0L3g0R80g0ho328WgokQtKDf110Is0Gf3UGSGi30NXrSwYW1qRYrW
7K20pDzA0FzUmEPl8H37IJ86hGMWyuj1iRjX_OII6B0_FvKs4O4gyrlBikmdS6izVaK4wiG5Aio_fliGallCasNGM43d2W16eCWdpehuLMi1QBNvznkisteW
16WYK7z-2_dwzQNej7w-yxjs0dNdjrJt70JZAj5dRWTfgbSaL-1g09P0yul03OZkbW0O7nXenQfl01uoUNUhax2k1N5-8WOrQpE_fNXKykk-ZC5rwyCXfAO4
hy-lIpQmXWWajn8Wzgk0Smc_Ekq2C08bfq2OFbU15u08h9rvVhuLflN15Dojm0IiSsu0VaEoWIUWSxTw9c0TPNvhUQuFnQ-wpyd3EhW9iCwn0NXGtRWHsUJT
NO1tqlaj9TVYTH_8Bu4f4eB37m0yV6jT_pwkXs7y9J2wJYeODBW2bsy5ySuQDmIS6_2hCsu0_bIGpWIcJG5oKJxV_7mTZEwpj2b0BifdEG2u0Uv9lyu98d2h
5s9mhWN0JyGq1DyB4LWZM-6Cy_CN2qJ0z_JVaJhX1k1RWGi4n41M0Ovu1IutC04__H2m6zD6vzW0FFrXuEtmlmjuVD8CsEoayrlOlXtqOWAkIokDntQdt03y
iH23tH3lpu9-UloIgV4Lk7wg-DBukHMyV0fO4RHJRW1-8WxhmEcdGCA3JZa_lo5rNmI2z2j0mCFETW3aZmCJ098dzm5kWDeteFPROJI1pnVH0VdEk06uWGX6
UoDziayMCpMu0hVR2lOq7EmTnHsTwW38FnadlpuOHtj3FP-UTNw-32pVH61fNFwYt3khXS1Y7MShfD1CG1VIKOw30e6ppSzl1tOdogRd1k17OXmZTgMddvz_
qFXEWUMWeP70SjoWsa1WENIg-bu1NGuVtYgmd25HVPU0BYT9zJq2oubIhI-mdApA0hgSBrMjAB2SCjGIqEMqgTOGM4wTwgi2ozc3lYQm_85U4D3bZmHeaS3o
XqA1mFAtKdrMOFbpAVG9WULFXjq2ovzDYG05kC9MqAlCRo4Zi5mWVI2WooK2b0WibqbLJO3CVnq34_XOhjOFWUM2VH7GvQ81-d-1vS8fz5_F_py
}

