sprite $image193 [243x238/16z] {
xCyn0G0G40306T2_hGKAcFnTWnjFv6q4iCSVf9MLbSiTboZbiiCbJlbILbPMLbPMLbPMLbPMLbPMLbPMLbPMLbPMLbPMLbPMLbPMLbPMLbPMLbPMLbPMLbPM
LbPMLbPMLbPMLbPMLfxit8MHnJ0C1k7Zyxzl9lrtUymOaYnBsGQIRz2yWGoY4Bc9vugG-LHwCj_BJEQtafBvA-KZyszAHMPULrd8p4y9mE9RgT6ignmOQ6E2
nPOIWDEZsQC4uBneziplXzt0_T5RluH5aL_C53Q59LzXbcAIiIqW6UjQiATW9nmodjcU5f5nocpzOl6-Wl0go5OAhaKWurrtClwfA_cAFlKZd-ZLr8bCpxgG
HTVaJwPxpPbCWEHA9aXkv8amEP55f3p8HCkSJC1ioI9aXcIYDbcHHTXaGnQHam6PyErD5k7JlcI6I3kI6QQzo0pKFcJ6QWToOxGsancmJUI94LDRJvuOjTLa
1cuTcQ6xNK4MWxUOJ8AMaHifMa8cIVF9v6acMIHASyXago2PKpqo52H3GR8eHmP-9kSsKv0C1Sby9-StyoDPvCv_9jM_WvpUV93VAaXMDV939EqWtvTt7qgg
ur0GXZVlekxZVl-dtNJDT24FvXGoCX9_XPl3LqeZC-7cMlanvFBNvv3DdjgCRzFQCZ-t9cjEBiajUJgpiOpO9siUBqbZvoQlth1sNonTXlUIKNkvIzReu8WD
bx4hrcKUBm54RCcg6nXCtWukloKNJM1UDoouYFjaRHiIx05cx9Fbt6LOCFaaMOE2mSYGnpORt40UoRmYhzn6ieO2s_OTkKh3cWq6Fu7i8IQV8FSo0oyOOiOZ
CkjhXNgPAIaEFPcG8XChs-HEPaXQSFGG9yWRCTJD31mzn16FoOOdoNhRZJfDPX1aXlp2Tqtdih1Hd2JZAkQvdoDeaHGjanh_nGJPuehSsnnBe7c86SoG6G2V
8ElDbd6UJ09Ca3kQGJmngSc7P1_7J93xcR58onD370cobt62t6tZBdxZ92rEaYtEadiz7499jqAIP8kRo2gdL9zD6R9_UoDPEbySaI03DhQITUhPb2SpQ60Z
MJfFd2Sp21v7rdbYyZ4P_FfzvhMIfSj9uiYGrzyTSODh9KizmM00EJAzZ2CgMYjPIqSnaIJ_5rTw18iE8RlEOgR8_Zv3EfgifUUiZiYGINwvTI3P_TLbZDDa
1i7r-zfKB2vgwCyEuWIvla3lVnLAgAqEOcR8z4QzzwdSKNH0VxrQ7Dc9_UFtgKil4wV817rZb1iClL8pP90aW0X2NNkDs3P_fxeOUwDMzruWZXro_IAS6Zhz
pBfYmHsomG0ZeBCwKBn7fi4aWD2f7RHPxv6v_Y9zPJgvScaNtoFJl-IJ-2swD6zTv9QCQmp_ijwdjeMylVtRoo3Wa_YTMfuJaxWbMslmZryfUiEUNiWcLrxl
vGOFZFRvvAtPCTRJkheJ3ypsjBPyEy08tn-6Ls-fvlxmCbRoRngX0cJ8lEk5oHeb07WaHi2HDBUw4m_IKlRKApEu5i4hbzMLQQHM5-w8xxmy6c6onikGBNbR
_LHFOmQuNJ9PaJLk5UqEkNx4fR73fbipeoPJeuU2lQ9-hAaPGfuCpL99aXTDL89CQguUag7vsYCJHJEst2MJchOxPCrSGHK9pHwgv3u3JRdFGEk3AXt1_m
}

