sprite $image261 [219x161/16z] {
t9o9Sjiu44GD0XWSP9N-_sjpY1p9J8iQkkKnTjMxkHCvppqz1qkLotz0JNLv7pNG-q2z5LipzPPGghU4KhqZa-ejeLJ_MwRk0pVUg3xFCmStdiacEmSt5ee4
6mzdG_5WV5NwC_5Wl77-K3mP0pU2YGThxTFtRGs08i5wAQLsXyYD8Dk1rN9L7LULJfRLSbCR1ES3rifEVKZal4AsLnqmvPnhSMHLUjNYU3XFCDIF3WAVXgyQ
6Zcta0slIjTQR7qad6F3R_EoF4ZUJ-rUVhLO_u2rFtHGep-rUxdLOb-MhjyEcN9k8LjkRjK_S5YL_hkNJyDlyovZRHuGEP-GeKq38kSLCiM0wFrOv3mQ_h4_
uANdxlNj8QkOAYDoNhkNIyC7OT_qhqg_XgyQ5ZaEp6xuCdtas_V-QCfGiiw3mAdXI_oB4wMKaZysfH-Ed4_8qb-KiC9DYXRs1dllNjy0XWq_XolOgfGKRGAF
xSWr7iwXuQ_HKhBxTuEWouwHuqDcr-9T8SQOyYEN7NSliXQFjunyHTcHQJz1bpq70TVmZxSC2Ge6IkYowxd3rUBnbj6YrY9goZ3MwNF7Hdkv5Z5nTK8e3Ly2
4c2r8yUZyM2Q8FauKBgdqc7tweHhtKWPHAudXO56eWWEvyv29ms3PaHkhv3l3T_btEc8nXfdHAxioR9nnxs-UoqBGQPmc3SxSbYBJkTEPz1Kq4pCo6rLEGau
SYJ-t9aLxTLhfjTJLTccDMIO8vasAtNXJEnpBpMDGECYfrk6F6xuyJR21Qu2wb7ph6W46H4vjGe2b7M4X_m7KiMTEseQXSOF0eNR5vW49Riw1sWGEK13usP5
eyZuoErgKUB1BPVBFvgNPJu00xJ5GFEfIiqPtd8gkEMEpe4AO6hQKxGIGl6ENCcFJvuWPyPRxK2cMguw84lNmgykaTF5NYO50qN1-zkkHLK7D6JxI9wHg-5U
Yw047SG00zCKhO6sEqkUqxouUuNZMsuwNuimhWsqLlHPuLEREh5xuRc3YayMPEFzoxEY7PkcYlLf_NKwShfxeIPH-dErYAOTewNTqz1aFFPvQVSgM8zPQ_Py
mqVJbeTaShVh-XGxVk4zxVoveqf4mmVJ7gELi0kPH4YR0GTLUURSKKMX6ZwQjW1PtJvCRY0RZZztWeQCQ_XtBOTe6ZBYRVljzSZbuqM_uWSxDWtHj35EfQcA
f9Iacd2l3u8v9wRXesagI9g484sLWpOjEG-dPCJkHJPyR2A8zhYVJDfLpi5XgPwEN2SQFfYcUaQsJG2T1YSZXs1VENVER5MMQJPQLAysjjmiE5J_whb3D7ni
8gkEoQuhK5LCw9gduBw-Ux5WQfgDfZZogM_-DL0EhPjHdPXoRCZGjAKzKLYN0uawmyjqfbUgYDsBQlXecescyriRv8eu5PyfnzSYccQZjPh2jjYrbfNISeuy
T_XQL2rxdVnJEkEIb1m-tGA2RDIvmpTyD4rrwbEYXsdI36f_4JMGF7VuMhHDM_2pSfmvfPYKKgxP8y-TRmPh7T3iFoyQCHqAYbaKc3vt-93PfbtCroXRBQRj
kQI4Zorh5SY8SySyesdJBlRBf7MHhFgkdLleb174HmvhaJVjSkALQYoVpkyL5CWaLcuG662yQPUll5hDwO_aK-B2MhCvFBpCvtEHCyvehlDV5Cs2GoKbanXk
RdAHQyPMHPW6QF3nhQvP92fMID8aXC95pgX5oZH4c_jPihkcVBjN8pK8233Jj0lrscNtharPivTQcHu-H3UgaYEpJRjGdxWwALVUAZ2lnq4n1W6yScV0KCin
6kh4jXpbyuzEFM7e3GHWj6c8HbPy-TV3IFuZJ9q0iqm3DAusqeS-bIr5vFXExOQdF5atq4WuqTkq9irV8lvo19XXcgBHR55NoWriWfNPNzr0O-7Ikb96lUZM
bb8SIUpE3sWaN2qwwFxYJUk94CUQfcWS7BQIjDu6AQvefGms3T7ezIJgW5iBCdp4EimqHEFXhiKejLNP8dTbhCDCGpGUJfzIffhqQUpFDCg5G0Cr0svQjyhM
FfD96M6QZSRVgIkPHFTkkJ1eFDoQDprJNTawZSRlNdU5CQOXcgrcgDwOSb8oITN7D0wDtxrMhjfahSQrCjEtO_K-7v0fcWDSJ6Khp2XHFPHlX9fdfRBHd2CN
vRkCKYQJJD5uDfii974qoaRpYrnnCmh923GEhXw_j-jtD_Lomm0CX43qd2_zTviMa4P47fVmTW60QcXx73S16SOzLoX06-2WgKRrD9xArQEuZEFedWzfF9NW
KMiPJoLz5AVz7SSVnMKS1r1h6gySstCkcwOIF8hHzZY0Wh8zxdqwBRcO5bSU0SvFupY9B8c7jhTvP4aaj3tE9KiCj3rE9qjYft6SKfPSJ4l4D8xpof98QToc
C_Ku7Qh7wKozJOVgSJfKZzEPUfmErTjqfXwdG_KudQd7wL2zhJRvS0NAYYjGLbnXijhEGVq
}

