sprite $image336 [330x191/16z] {
xDU55GCm30DHX-Fz1oupjqhv_Ww-9zjdIRq6ao4sdoccGQY-rBC9aBjlj6WFGkg-HymbXxtoM2uHYf_IaqauR26NB9-pIZ01Xxtoo29Y-PpNabs1rFmcDTgT
M3vwBWday5ooVCH5nF8vJtyW2UJb1nBP7o0za0JoV2uHcijgC1GV8lCQ-XLwBba-VKN99Skd7-21lA3qAVjcWjl84iDGPEm0xKVs_O_xTqD8kKlJrlTeK8Y9
RHQi3oas9IefnvCitmFa9UTOPXdxjhT1RbCzjMzxxtosHC_iszx9PyjqFX6zTpvRglS06HmZ-LH8lWV8r23h97DTFxxppeSS9Uy1yknI75AIUk_RphPT-9Q1
z2tKa8XMtldW12Lsrxvj_QKujfbyRMIhQz-sVjk5RUjs_0DfgrXFV7o_fJYoROklCFybRDFLGAxVTac-I_0lNEJ_97NL4-kV0yXuAbctkhOVt-eSG3RoiP3L
rK2kVmw0RV21HE6Bqvuk-mqo_tQ3x53y2mqDvD866IBGeVy483j9GRq3PFzeM2SPD079T-5qTTHWb-kS0s1vgd5QB3UGdyiyxBgmDM4fR0ySoomlAoMV-kj6
HnnbMrEGeGQxNEBEvuvD0qU6QN7r1hAUVEeVRuXGzDe6yhgwGUQIGv8aXoYGx3lOw4y-kP1d8a3cwXyW-mqIVWeIV2XHQ22xxBB_OIFb__qFBnAE9nh8mW2v
Ol919Dj90kc8yNm3oQe3vBC6AN6ECV_gsGRoviA-RStaWvJyumbX5RhSL9-B9X-a6iUOAQVJekpQlctHqH2HccSkJyjSRBj_tzQ_50yXKUHuGr507bIGwgad
-WqoPnb8pmiS7_KxnSZq3Gra_yFEXPXmp8L9PagvePve7WthIJqN5YVsmVrssRyx2u4eaBIGZoHw6yZ-v9FRPMaVZF9zS5tRTH6378KeBJ41EIJGonh8oqeF
kywIe4T8sVKGJoUY7-t9f_-9vmsav0Ct1WfssVmh8FqiyHoby4YIkmfssPfy-fyudfQvo2D9GeL4r6gG_Im3sb45gGUEeS80sPXy-fyuTt91K_4N9XnhBA-T
oQUVvHU0m_cG4eubkxpqxNpwdpZoH1d8kbts9Pz-baf0fXmR4b6pGIPj81Ar7qkHS6omo_xaiptewHqHageSjQjtttRT6ZXEMNAYeGJT1Rb1XkGz8Lctotw3
F5dvovIi579vtnEIHRliJpxd3_OaacQy3DBxFrBRlktprW0o8Ob8cd6A697t8DcnRxjihI13mP4WMdZO2SSooHWWYycddoGI0GVnCeCCgQ6UI5vs2qaGysQy
3jBU2oGBYQXf4SdFI28cNvYK8phvi8DaJmDv-LKFdFo74eafgFn38-KS2oGBTjcNob4EacIYoJT8eCGWKvBLHFJnEmEbJFAshTg-3KdCMCfxWMGX4VL-mx6P
Wqn8fe4SIH8W9HmB90iDP5UknDFRHsohjcz3ch0CZWd99HCHjcqUMDx_et9Q7IH7kzI-5qXM1iX-kvJiX-F7s3LIgoTGe0oMyjv0CX9HhrrA-dglD_n3RQME
50AaWMDEiZ4HlP2aaMV2gjKJI5Q8u5WWMT9d-sf8DlX_7-n97EJ9aBtta0nTckrIjdN3auCzQYUiI5zPxWMIVNQvlUxRBMxoqS4UjGQIUDLJaYSs64iDa0Iy
k27B3_PobcEUd92qG2wGBDXbJzMe_61FXOEDCKyU-gI6NAHVjJHi6o3bEKh9gbty8mqilGzoi3n5icwNJGCazYG72Tcg7MmWASJn5ySnFmR9TUqIszRqO8_Q
Rq-WGOya_wJkJBVT1e4ON193G2FU_t6xuRd6DUwESb1xzt_VOHI19yChSsTfd45Ilu4q1sVt3Nj_NkA_9fa-FGkF4fz0KdtUXevVapDraF_CSapoMpNXWoKc
u5EVju6tiZAHPAicSxiiqnM3O0hTM2WJIKRVNv0cOfctsKyWxrwxosIIJK-Gfa7f92S-WGH676UJT4MhYdMPWgOly7YXyOOz1SccyABRfI2WQtjLTIGrTfat
TV-qdgHhGvrdbr7VigedURPBDAcZvBss1KdsTgau3L9i8FKaNOzIgvb1a7n4TgadwKfqae9zZT0kzIGt9ob8FbAxr9FqwXOOfD8kzIIZanGa7uLThayo1S5R
wcKa0G59vIYN4Dz5qbcAIUPDC7f4lYPnHp9D8AaOUVLylMjD0cEIB8y991LZsBOi9xc3nDrJsbVuxoJpKpOFKE-JxV-8PBNuVqdc6BIZxFHh4iCU32FByp-I
J44vDrL94XrBNZZk3v3oOq1oXR6-MvQlISEbmuhE2gnCOK1Ia7oMs402v-86UERe-lu7s_wPfCeWzNRfB1qdUIfibx-nf3p_WQIuiFLsYIwSTpvfw30woSeS
Uf8BpP2FHSUoNvD4SKmuID9OcJgIArqL79AKfR4LTZV3qweT9CrORUj82fBFedR9Pf1eyWXa3QL_BGydkTZzBvlEBetV3H9mjJyrXlpexkKhVIS9B7OdKP3P
fNFiv74IJSvo9ma3bhgN_Y5AbqJ7yLhYBhD6qhki1GQvMY92AMQ_Ocd0ZnDr18VYwvstER6BZ9KtLtSO15l3zSxRO2GksjiD3IDgW61hkEG0PTB6B6-Y3o18
FakUjy7kM688qbQydph4_COI7me6OM6lrx01_XvB08Ba8x1BUObVE4AGV1I9IC_IdJ2b30FUbdpMJqGxnnXZAag3NBrX0wo6GsPmaAcm4hhaitx3Hb_YNitV
GA9McZRvh6-NbOsZ7RMThD8WEFDHAQfAdES3j8nA29AFK46sWKHF3cUENzgx2ok40IYAeRZjFp0JuA5wkyFFIHxIo_k0592tstG_xPhDYtYYKLn0Fd_ExmDI
GFQVTi5bbuO2CZ4Vk0pI42v3G0h8VlE1orDmsFQsO1ItjmNc0vU1-S1bO3wCA3Xi0TblFYRr0902CX_5uJ8095m6QGYNWVd0PR3vm6LWFW8oC1y12P31tYOD
WxsjCX-ux4TnHjIR3oEw78B35f21-J2Ym7pWCZ0Vk8pCXn5LX-qvnkO3bmaW6T7apESE
}

sprite $image336 [165x96/16z] {
pPe93jjA34Epno8rzp_kNooZchXM40Onnko-FvZAavhsz9lSxNOwUAuJWEVbo8YN9s1cmEDyLCJptM0HsFsOZBT0Z03JzR1DPuutckT7ZvYT7saqSnZNcBSZ
QSUs0qoNmmnZdTJH-ARhZDVHRNf1dFxF1cRgQ7JJKyOYXOu6QcVgiz7vupnqmIHZPhIEKZiAP6pAiTh1YX8MAKPpZ7R0LqQMEXgYdGYSrZ4sM15Cjs4B1cnE
B5_rvXLaT3xWsWaojjRy_ynV3joKjt87ef5qRpCXsJ1eKuPsYi2RSqbPz_uwYgPhIFUicywLFONHtE_QWJi3qBkwfoux7-xHjBqFcpiZxis3SSzDMMkd3XYF
CUh6nvloygjXt6WQmFgRe0SdiRafTzHHQgV6nF9rHF8nzR5wK-we7G18tCrDsJCwwqrvtKyxGGUWLYTiQPgjgPjIrqwDYRSl9VUmkxufTUtKgIdXfBU8Eukw
2nsfsX4UPhqfwVgcrBMZFqmiYp8E3oUBdr-EfguT7JCsvL8t_zIDEOAE5EtecDmwZ80bmk4kQ4UcH2oWM9N1Y8pGkQwTFc716hEh6tyZ0gAEiccHiCOC9luV
R3n6U8DmkClQgUwmB74REHEcXwwZizvqPhqatoDQM1ucRyexO2fa1W2gXGuOCl6AgY3hmrrl6rWzoPUUrupeC0riBI7rJNcRFgOawcDnNJM3EeSn8PLDgHk8
hQE4-njhWWpCfUa2Kj3H-SFEwSsPqkQxmvqBPI0Aa2iToLkH-HUlvNeeCS4v0Bq9aCNXhjmNxltRAiutHnm8BAUl05deIBhKsF9yYERBXOvuZ7Hl4O82P8wc
h2FwkkuI4z5sTwSJS0KoTAIF9XlftLbhLH1TztLZSe8kG7wf8tXp_-XTD70DQQSR7A1wMJ_FwcaPEl7u_Fs2-nloT7hGOJ0HyoxVHVXJDqo2dEOdC3bJfiAh
NDLHNjWYP4ozEG5nAB-_u7J8o9sEm5GtZwuZ7JANC8blHAdhI8VCJ8ulXh4SpJ6GjSW57UcGNa0A5_eEemaIUDauDQJUT7suwv0lXnflDMIj7VqTInqoAPrk
buIKjQEFfWv9cD6VvuIKjVDx7I7xpZtFndj2QlzwieEEykpjthUQZsPS0rBGZjBvDvZWt3JciWbtqAVpv83qVrzsrH7eX65ECCFCkSohe9sTHnD9QVIW8zVl
oWZQsKL7o8S9qBlZ0e9szjOHw5avaD-FIZk3HZCxdzFXGczQrv7UkS6UJm2_qSul3_TyqS3iSJSMsXdUkIyFylbWWwoT_NMKenbVARHpZD4Khfq1EXAkdV6Z
kODsTZZS5UqCs9H2qoD7Kz3EA1q9sXcZe_sren_kzHkYGnCwahGpS3HrxGpGaQoTGJhIjJD-D36DRBhUb4Eqen_kGjCZEnUqCr17WdO6wkXNslaN
}

