sprite $image63 [130x83/16z] {
nPa9agqu30HPR4jAYRx_SMVWzHeEC_C_BSWBK45LiauNM5JcwK7cPc1rUenYc1deEZt2gc078CiJ1O1z0ktkELJ3Ve2Lcmkm7zmyXqN0Ehevf1fe0x1wau5Z
q7A7WJrz5Va6zlHcvXkOFeVUm36zcVa6tZk7iO5Zi3Pd6zYJTA5UEWClp279m7CpymnCChCty3BeccDWlfczWGbpI33mnCm40nFDx0rCc4EUWUTcpfSCp9z3
R-3zLSod1UIRsHkODeUB1YPTg7i3i-UGOE2LHwXp0_FDd2yQUFr2ZMFF079KuN5lXjvCZqSpQ3aIH60F0VfAu8uzWs-l1AR-Y18UsnP70fqBzsSWjdzHtpFO
FAqqkpK3lXrCYtby9EWo91TmiD-NtRtk2Q8sXViAE8XffqPeerbpBGPt7d_RFXuF8aoYAf9V1Vvr_BTeqpi5RuXfYoQvLVZt4w3pz4LpYlch2eKx2c3jdjHC
99gogYWa5x1vdJfMQ2RewXGriWeuYC4VeWhLV5LJhm9v1TWo3PZ5hQrkrKL58Ac0SlxgxA88bQCAVl_uXu5Ztisi8Qfx5R-IWO61Onfc5QjUYoha6JXctgim
eRIjDeCy0yUijbTH2u9MWpm3nnImjNbLcegHP-2OkRdkLgh4KKMQWUTcMe5cuYBEbGBQz9Uind4E30c7H0F7LBUAc4Y0GwQ1PnVg0X8OxYGQE6OnhBLWno7L
mB6PPew1WKEYWMEQ1mQygY3DmFCv-BSCgGQEpGp7E718D71CvLiLxda6ZfdRHnNk4NYUWMCM3STU2SATJ0F7PWRsdY3S6HYOIdN_J11uce7dPiP7Wd061kQo
s5U261YOJJ6-4WmCpAPuV4lm5dMw7_7uJ30oC7yEHuAnWVciU7G6tappImR-0m
}

