sprite $image262 [176x129/16z] {
rDO53kGm34PXfq4_E_U_xcwMOPXQVw8HZLwZlz3V0tea01ggTebJ6wTO-IN2AFXFhDebm1GY57D1hDebLkqIB1SqLEqIgtOvq3CimYXuGApQPRyf12hcAR5g
bnsc4AMO5z5GjKkiskLZmuqm2juYLkso-nJs7mKdQH-elk9QFb6BRhsGM-KLtZg5qZ3N8hrbgG1ZEqmn9pGmhwr9bchkrhNrSOWPSvgPuNM8YCrfNjCGES0H
Sz9GSyp8ahRMC4DpagqgEnTpMjimLgxGPpLif2nIztwsmTbUOrgMIkl5c6GfCclPzVN1UMhkrgGsfE0-ryzX0z2nKx5oWStfQA5sAURJj90xe5Max38ABdER
teQ8p3dDnnX9LssIhxRF7p5N6UHDKbPpo4E1bkI7naUBbUjiv9n6czbmbfxajwmVBBxvl_Bi3MCPc_mbzKy5SmSVO0vQv3-LJnHp3yEOqzPmJzZq_SNSoToT
AcVqDt_CSp_3W2odbNSUCG_pgTkNuki3nq8W1eAeo63ttF-uc_DwmtognPpWoIeiN8E7FQ37NcVIMcYBLKn54ITVAekCoLKSmHxgsQAEOjY25LC3KDk7-hCB
KXpOovyo7dSEd16aE6VlPvU9WaD5njmgJhNanVjWMiNIexSMynalfxNltiGpfl-0Kf-zVCRaAaxfazSXtWPi5KkLby-OMSNIJzuCEEFf_2fE5LvR5CTuyWz8
Aht6ZC-iOgdqMgFGSkigJbLUkxZbTDCgblxhzMSyR1tQmklFkEyFADNfzMSyxhzgkxt-ZDUE52glF-FX7n5BdLuUND_zIvOfT7fvSNttZw4iXzldvSNrtRyr
LLh2cu4VJ8kKLGg8bu-YjJ85oCkBIotcvSLL2hWtdLhEwnUhvst9YVtQjZsyAy7PDzpdbvU9rSj5nNxjbUBi3lU4-9fmsH7xK-35VYqV1H_kfM81N2uAFWLO
RDuAbugP4dWn7owVCP-2LOnhxM8wNByO3jSFzgVW5xDQNWo7wnV3VpP-S3h2zOj9hL-SM0cysC_rWzaK_69MwnUp9VZ5BDSFPbFmYrcjNyoMu1UpN3-OJS4l
PhL-CQlrY-jkgN1vC3jSlvZL-iMirYzcm_M3sU7wnQpMBsQrVZ4RhX_C3jSlPhL-CQlrYrtXtWC
}

