sprite $image290 [236x171/16z] {
tTU7Qjr064HXchP81h__smOHzoKdHKVnt7_ekEbZPxowp_y_yynpcJ0LiEMae2qehQ-TQmfJrvIMrjTEIZKffnYLKqtAgIRb5ADogaavrQISQb9ECIgdcfHJ
JSefG2scdLOAIAjefvrgL4unAUSnfBsIbgNRPc5dDdLiPqODB4lRzZDJIt1zNz9c9Ir8p_Gf9dEexnb5i7DDsxvcgaaQwfestUJK5x1QWkwPDLt6XjMN_aFr
yK1Qb6AHNvhU16t2KBd8ercr3hXdkCZT777MK3dPHJQbYRFbGsqNgBb5dh_806-sbgdaBJ1Rbh8tVxOiPMyBAB8fPMt0R4qgfmVCrfQoDd-sBAqqMvQMdksS
0ZPxjYpr9-lFDa0QLMI_lldQALApPpilfu4XOBOW5OusiyXJIe_NJZ4zUhRJpSYPBLDBpPQbbMVh7sWFc-szGns9ixshjssapVREXRQmsUuttZDXipsEtTD-
aMRDTdzwEex3mcvBCcRx8Zsjmj5oK_ktptO_dbwiddOqVhxsFRCzfUzMeSZSrFjdo_LziO9MB7ARDywMwxjOnTcseDcUqiLQOBPGtyNwaBDbALdldwrRP1ug
M4lDzaKALj2AHHPdsx6-R7s9XRtvjR53VS4AH-kKs2zo6r1Vi8fQOAZQ0VK5AsYL-lBz8m-LhAHLNYPwTsVBGsMhSBHGt-v_skEXifMrbwGDcWfQOQXW1Us5
eGxtjP7hArX9o_TCzp_jjGdr5QnGPAplND9WV7zKP1YgO6KjrtVDQFpqtRXds6eKUL1ztzFvwKSJXWfMGRlSCv3Eunl2FKFMwqLU7elI-DkwTS-iLaVRryVY
PNSwUd6eR6KjxHK8NpB-OlmDXYfOyMZXjDgqCeHx1go2TehfHdrNgr9aFmtk6S4QekM0LBDoaVrGVNqhQqEbR0qiiZhKbpmV3wIz9Zrp2Rj7rPUfZZQ_lk_9
Bx8WLRNvKgV8qKFLjV53pI-o8_MFDhc-lZPOwXSvSQZvMaiQLsI_lkbQlxxvHRQa-TfTaiOLsHzgkjOVQdwH3MdaqVhrJTVwzStNYjBmsUw2DF9e_Q6cQ_sX
vXTPa4Ph_Vh65jclRxvMaiOMsPJcQzsXfXVP6sg-rfFcOqLgljQJvcizQRxMa-PZFMg-rfFcQprfFjQJvcizQhxMa-PhFMa-rgFcQprfljQJvcizQJxMe-Ph
FMc-rfFcQsjH6LjBobgK5jE2j1mMgEMq82sd1MavBL3BOK5QJWlISbgGbjC2jHmMfEMq82sd1MavxFTGVm
}

