sprite $image347 [157x233/16z] {
p9Y9ikCg34J9RjHovl__TYRZf0kNT2d58hbshM_bZ4u37VwyzKcjTVgpoq-aFZuvxn4EaBfykuGZdknnSZV84s_Q7TobJ7ZXoTxWJkNKkArxWpi884AyVS6L
_s0YZDwUCbVgGYNS6Rk1cygflhxzkELHyY9xkDqL7aqAPeNGxHwY9nIgypo3RlTmwZ5i-8UciYUtqtfiia3gwbYHFIXLMRjbzEGtyEv40yT6IFdTw5L_R7IR
YTxudM0Xs-ZLtneR5hS6Cd7g3LTAI0QGZClttGC4Jw8A0zcwJU7b3n12pdQIaeXUQYT0VBSD91cVUFUlZYq0-HstP8EIg8NyAO2GZ-ETLpj1V4ZkX3Nasktq
mGF44Ba1v2Jfji7x51l75eVyiDl9x8GUfC1rgoiy-SHEK9Zjkj7jRUXEg0r82nbpAmymoDXJhpQVaCY5Z9o0RlJoR6tkZ5jppVe1fDiHUEAogJ20SKWbf5Ec
ycnqIn03wNS1totnicY-M-FFXVJBQ39w1iYwxKEY0mbTkPK4MyXj7789e9WBDw_KkhMG4RVOx9Rh9zn686K37X2Rd3n10f3m8K6tKJm1-Eydt0OXt-pn049u
V9YBGzek80g9kYKRWcwhoDQU9wrRBYS1jZXUlEVvaCQjHE3YqMlTwgO01iiKOF32RZK6QH-c8cMASDlS9ije87gmdqJXpDWCPDUjTiiKuH9k9TppV4ZfHG_O
ZCUGPSfe6prnuL9kkIeXOrsWTSlb7BYCsqGPvKYzKuzmQRV9CYfDz6GDfqYx3PPHyI5rVU7A2cxEuhbZ8sJqrv2D7lxJpPfo6-y2GRTLE3cepfh44n1aOnar
RgbLvxpRN1SmPQfIwm2ypa_kU1bTuKq05h0XqODkxm8qmEL0hPzn6myWqLINvKHdODaEW_02NS2599lg0quMB6ebOzgjgChRBwECnGEkbYlXrbhpUFBseoEL
Bd2tSf0Nd99fdDju5v1cueGhzKUjsg53s6sqZ79iBTpj1KUcXX6QZfuje_uaEJR2JQLScJb7AwUt5Q_N1Qg_4mWd3PpP3WnXrYtwFSygNU1mAfElTQPMukNT
kf16AU7gcRkLKJDQ0sqbyJ35iHauy116H-iWj_6nMJXdEo1neyNAA7T27uvqAxoHDvgzmJYs29m1QuSvf4oXEagZS6iSZBlHR1bb6EDmTdfqdSVhZ2qAzwDM
nPWoXMQ8RyE1MktHn_yiWUUEBGx7wP6fmGEoRYrR7Ex2NnLcEv0vZIVGJN27SX70rxfmvQCdgblXok7sbEkKq17F0z1tu5HNSAKSfuNEbj3yyu2enk5U52rS
AUTAWPxMhMx95eThbpgMvtUH5OZHkWbFeE_2jKlLqyBsZ5v7QpzwaR75jH9lul0UqJE_oH8NhXrRN2lNkXrUU6UwfTRmXIiI65jSAvUII_6ZjtuU24UFRDkq
4i14RshRYdedJCIjG3V0ARYq4pt2GHsjiUS1ZYsXrMx2ww61WwkLKTIkMuujeTL4xzp2yT_pIq47JpK1nrMSwBLme5Q68F8ye2au9-2SmrJDKYO4_US1JS9v
F_Zz6FbQ6-F3uTgb0kT_vtd0YPucuRn9z6gbhvL_Cy2Mrzgvs_rN7ukNXxEJYBgbLkkQR6aumFqH68yUp9ze99mzvRXU3CzEVI2S4HEusucZ_dyz4CxSvHgF
7joZRoWSrDCQm_EcFXOEdjP0zDJTyCFXq6YD7oiAU44T3iTLgBLbzE7m7Qtyk_wMxVK16u8ad1guIAsSGpSQjURXxgPCj5h9gAImdmt1CBZxh7PwljRebJ4C
Rhx_m-jDmWG-4Br1S7AO7dZQcGIrngCt2gwKeznxUAHfe-ZY_QNLJd1KYM4WW3fxxDI__tL_HnDXjGNMBExColv4MH1AhPS6uPYknLlt9V2tbVXcjf6ujd7k
w6cit-95uj8UEoTR4wiQF-aYSRGEpkLzyp2Fw5XfRDUdR3LMZTdb1SIAWnjvw_uvl0-nElk1C1plFfCIgyvcwyOAF8exVMPP7W_UPutdS4ssRlCQ7DsxCa_D
J-4eTv41AQ_HQzSVVDXMleiLoel6fLdBw01ckg3NwCtzvpizZeK-WMEU9Gk0sYzUORfrhiBYx7hDACR7ojVgkIrKhAPL-aidodDQ7-N5uLQdF3QlvL41I36u
S_IulzVJCsDna4fryiwM65kN3SxmREjZZB4uW7Dgp3nohOBLCPB10RVHSs9LNXGE5oTr7WLSkdHWDOl36Jsl7b1ZB6vpIYkRcIi0L8EpsJgnRcCi3dlqyWBG
Ss63StYtraUDqJY0CtMWzzMglC7PqVDQdsZS6RtPEo0bASxgbEUqFa6uTRki4JK0A0PdidrR3yJ7AYAt2xbG4JDp7k_9MBzYkbquCxNbu0xFVLc9modldDTJ
IkpXjewzTxH8dFBMrvcD79oNxJ46ugRgrbai3ixXnSUQ1n-Ulzt-_kZ5uHhLLxOUxljFNboiaoZnqOcB-pul35U8gBFbMPpFinlbA5odQnL-BVaX3ikCNcIi
cVQQR7a-piyshDdaIfghoTR1-RmOtERDGfIPxxp_xTq7Zjqm48FXxMKOUEv_slH6x5Ei_A3mbC8JV337lStWnWTJCPnKpxVMgtNxRZQsHylXLAzFJnZdEzmy
Jgh2EETLvN5ISPppAeXp7iVPAMGUfogASruOvpp7aUHmpjiPfweCJZcSypR6IRKpJggTST8_XlkF-u_hOsTSzzQuxgrnVUoCwzuQrwtQ6DUlLHlZNbzhOzoO
jmTkrEq6k2WlZqjrcyS5U7cSVsgUTvl73Nc2l3mktsqUvxm2l2oEyAw8wmfq6yG5Ho-FYuxUUbpNEUyAEDvj7XVdvN7vqLkFuplSF8vkzP8uoN7nRZbECbo8
by49u42t12S17DYi09m4S63q04wQnN4UnGdWmEWHd8HmVFJcSHB2yT6RnqaCntdpE04SxjO3Q007kZt7IG2Nur4QnyrV7X2m0HpSwZ6QupZlf5j00pZ80pI0
Wzq26y31hTufhG0kjLavetKtm8LulxODRcqztrKMrmyNkvsWlUNTtpmPRjNeJT3UthQykxattAfkdUOsJ_sCkot7vNa_umOqoq-rtYp1jPmtINFU4y31XNTI
gENxIwE6I_E6mfhvvTtZevRX-c68w_FCReHvwYBkw9aSgt7T5t0zcsylBlIwbEFwTr82omqSnvVHvdczElgAEthBVC9Lmtm
}

