sprite $image268 [188x134/16z] {
rTa9SlEu3WHWS0494DJzZ_kMA9we2pHIrYGkfckTzU_Gdm1QeLzEfhyQ7aCI_SLK7VzFfp-N9ECHfh-LFYxH-hUWOoJzBUYO_fUWIsa3mlj3ln3FCXpx_Q7p
ce-axQ7tzFInxNj3ru9_k-_C7g6xRevzsHHwGz5RiyTkaWcoF_iaonbO8_RAEq4VsAROCNbRzeYX9-YfnnmshMxClkho4Finn_yp3ysRia-onCjpslZCF2Jj
oBxxkNX2j_4LcxDjnvx7QYucERb0U-Ejs5TTpiKsv_2nOvHjs2TPpaMsQSFbyT3kmRulvs8P0DsrxpZ_1TldjqBNyXIwL30D3-txsNleZD0lSr7AGmN4xQh4
0zBU1BqbX0xDuQT4E2DaNzy0NV8pwBsicy6kUYzxX5wVGUyvkFc-dxt_CpnqTEINgDzLRsMVP3aNgs5p7mvsrNlOz-LSpFz0Lqxq95c3NVMhx14wE-Y-kK-J
zQvAly--AgXmqBzVwBd8zmzjQZ_97g5BTj1Vm8d5rhign-plGwy8_PEBL79vYVr0zlfpx1dceeCkvSOnnBkAiNs_mHvFeJleGVFmmNa3Uu2knKF75Hh7pt6_
gqBszw6pUtTn_zCa7glOOUNdsFDoBgR-TNKngtGZIOFlLJVPhw5Bzj0V0QOl13pZhhhFtaEl7ZeoJ7T7GF3GtcIFeyn3zvzYN3v-PEDT5REFeNS7_HhvWMj6
kAjYzZ7qug1VeudEl7Rq2Lq6kofa7qFd03fmUgbydNavBMFsujX7q5loq369RfINOmvtmLctvzTknxoUYm_e45rYY9Fji37P7LQygzRidq3Nwjv6-mYzNBwU
_wUPecc9kofWpm1z1Ra0T3ZtL_EuUPe4qrBThWhPusVN8-ZetIV5NXwLohCBZXPgxg6DsBTALDV3Nw0vfj8YAVJoY3rv2yB-lc2pHY--nJH_aPaIV4mGMYQ5
NivOMrrmUbvSTZZ1f3P0KqZCh1CLZJuc7wjHUUy586Ut4QNwLnqnO2KYiV-7YTXTATppZGN2yl6a8WWKjAzp3QuaDli_tMraeexJAOPZGNdl1MDC65zGERgI
p7djRYP4MN4wUJZ-EOhRPrkEAlEqi617wAuvTZ_XL8Mb7CAneuVbrrxyaFS59GVGRRhk0CSjvJMSQS_SfATUraC-ZmkN6lt6SyvbznDEaYNxgk5z5PDRGIy-
zAnWIo5qx8vfLpZDmN7e3ycBP-uuEdXniUOAUYxL3dDSWkus2b5RlZV9icu_6lo1Ce_3vW67xZCJ_gRASyd3GNVTNJHTu0mFnxS_ZY7j_n6Tn_7HnUBgoejV
oN8CVTMzDyESYnP8nwlARCxZ8o4KM9bkXlG8kirrTw4aXXcLY0UmTt3kHmjyhO6_5qFtPZeH3yDeflGrBwk7Sp_iXxyoG8-veFT2jK9pjsWr8vpxwSalovP2
w67tIePg_A8z-e_0qUgXItu1-gex11UjkoRSXzFyqMfrqFsXnzsLcGtY5YrU4tYy7Cd-Q5-3lkxUYSWWk6ZzlCpz3XU4tX5wm2NktesgOVoYdUqkd9RSBj8I
Gt-nUslc8ucImBny7KxrqFa6zAXxIciurqKxyXquBLEVJxWKWEuEFUokyjMT-xTm3aatuCnhSycteA_lOfBbx3wQ3R7r3Qq3-rVXc9kB3dh89Rn7dcQwrFL3
sw-BrkeTE7wDiZakjxgdipiLgl9HbWrJYHYk2NScJiynz7lTbJ-x9zEpQhXeZtu3ZbQ47dE9ksV5STXpAZLPxpdNIkj5guzvETc_qOt3jw5ZFcTT6NYoPTHa
J4GvaIt2rqKx2hvCZzFlGyTKUgGPvkoUJpCfhU2ivsKCHug3Vk_G6rqZE50AvuJTFHnnypA6etmREaQXkMElH0BTunkQrU_Xj1H0jrUXOv2zgDL7TyeSBbgy
9gpXIFvPw1ZFlcFtUD4UFJs7e_LNe5F0_cg6BLwqTipcuFYvc1rqkmqzPj_vqPsfgK7WLOZ_MiNBkTYF7uQEgSCWP_TAjQxXmABLZ73mwmNFVy65QPcOVJkx
Tx5CUSHm9iA1kLWCchzsw9s21EpbepiLwKpzesqB5grTwjPqmVXhq37-V2i9gLd_w9xpyeRcvoL2lyl5Ca5UPTyeit7EtNBcN8952zU4Tq6FsJDLovIxuJz2
E30ltmlTiyVaLBgHMkxsxQAr2j0XlmCzPjyvgOaPB07tAWJdPJ-ETq6FsOzXLipoXv5kdawxpikZBw3RRqB7UDl4evXzFBTr1UUwQ8-tGu_PKyd5J8ajr_KD
xJ8ltmOzPe_BIiutKTB26nh6tWGzPcys7jsxBLBFUVa-w76wOQITRusf1JUqMro4VZn9_DdQnmzGoh3rehrnw2CHv5VOjqnLg5ArH7a4Y_Obw8L-Aun7Mwqp
rQP2OekCJCM0orkXn-o7TUPAggpAFCn59-JTq6FsdQWsFOTwKdEPaBT3Zzchg7NLJ2Qdg9QX-mRG8_PM2bKoJMoYLXDqtm1wo5w999kPMA9U2tJV07hCNcKC
PXQhJ0cUsLsWnvUSJqf2FLz8RGCzPZ_Esq4LeZIW-nxGO_Pc8fB7nqSY2jrtW8vnCpqH9IFgPfIX-nRGupVVdPcD4WtxV1vsWnwpLwFQrQXc3RitWkp1tfX8
xVCdsX1wp9xpWExRGVVi8T0zXhuR-s16DjentLnsXkxPO_Q67hCFeM_E7g7l7rbsL_eJoUgwZqn_9MLWzqhRnx_v3g1lppw0lZtx0FhcAVhBqFyB
}

sprite $image268 [94x67/16z] {
jTRljfiu30Jm-A-i6UNzNtTF8epWrEbTIgw_xBQ50NuUGHxNLcsFNrjv05f_9pjrK1KO-HV2cr85K0Lw-d9sLRv2y_3yzcrmSP2gW3h_zy17f3N0-Ry6lacu
T_eMluEBnnIb_z_artOVV1I_uq4esH_t-GDydjz9LIY8UfC_mATj1NMxMvYM-_nLlOKE3eMAGj-1t6wu1FyzS6ZpMGAWB_vqv1_bCdZRmV7EdjW056Jp8pT-
oPV0PGS7HZq-qyp7F_7NUDIiCpjMruq7fWT-GDkbTtWICaYFRD2DNoxm-vdp6JiDiZo-A7JVtddUp_pD3vZWVNciMtj-J5V-WT_1wmPkK8pqbytn-9YkZ_nn
yJR1VJJpNmoz-p5TQ_u0dorisokbVywExiVsVkPlSSaA-bdZSt2kNgyjtgThmHzFT03t4pxNjv1-ykncR6_mrqF3Upg0Uthz5DuD6D5DnqPCLzlvywCI2aV9
j2qRdzcJcggoHZVHKtD-Qx7Z2dQCyd91EppLNEc3YilDVsqZl_9S8xqFsMWbmTXo1wbbtu99esiLFvVzM0fYtyayp7jgzG7IKBE0754gU03odofxJRYrsbks
jJ2-a6RFTpff8rS5sMENiSaTaijKyNJVsDaoBNDKe53GddiwZJqtWAZ1u_7enRCRBMxSRxx5XslRDhmlfAziltUeaPC7r1myda-gAcW43-4AI787G2QuDz-U
JvlfkP7EKyg0ptJmg4vdFMUFCiTwb1YL3SMsTBMUOS4JCtreptw926_xBuKQu94TwGr2Sl9qW2Z1irelYZoYXGuUAAVqMcOyJLyyi96TPva_YZi08mTutFWv
lKdjdND9hkhymNDURRwZwneyqa6WIMq5WAVxy4x-9G_fz1FSKSxPCKsejKiICvqyBnD3MVCevWSYm1dWXtInTxoqabMYFivZOyKp-xW6Zt3BhrxPk-oZogDa
Z74QNlRWYMnrDB4tk6AL_PoVKRppfQHUsQgHn-55FV542mDyWVBK75zilYAXKjZJCCxXpUzsQWwUlOK1RejidhvhUOjiRCtwC3lncAIDPtukitgshi7_-Aev
Fwrtosqqd7dODfwU0lmJol8tblCJp6MqOI8sXpVQUGQdhS6NAmcTfqeU9OaTXnSsVszT08zrv1zv3D6PRl3XjUxWIvGr-9gVQ09jGfw7Tqnm_a_mDJzwP-rL
CVETvphucjz8wGLTUNgt0Qgu2hxcBtcKNiI2Hnnb1NvXLM-dZbn5TEmydRIBu6j-shijebBoiEqAwrTAkPWTxRUQH4UltNsUDy1N_83aCKfJl_Sxu6l-hf2I
04-_0RxcPwqj8mrFtxEn1h_EpvurU_fDy7NxHQlBhC5lyXlTVGr-dv-UlWA_p-_f3lxrLTHyLkNxsSvFUuxy-AtLzIBuVm
}

