sprite $image352 [172x247/16z] {
xTgBKkuu3WHWtwssm_3-RxkO1LLgy8I6oP6JtVIvN_agrKZcD-xMyKNUalrDf2CrNPsQi6turCOhIqC5q5zKMovRMrymChHzI2zSsmnDsrxQXMiR1VkqbolM
LekgqI9SiRO-OvAsQMthPMgRgWWckLvjes1WCDTUQdxbzfO3xMv-bTL5AArDjFCYIFBhhIDof2Ncbw7rk0X4RGsjV6spNs_L8l3pozxAQTUlNRMIjHMjxKhh
zMkhrelLbhSsRktMS0KhltQNM_crMxDVOUszDysQjSjRjsrJxQArorjVN_lo-SLRMvNbyuktregsTktorf7MLjUMjrRvLMrhzkRM4LonjdLYdMf1rjRS-liY
I0bsLa9Bl4XZRVrzRQEbTQxbvrSDAwnLpDSkRsMqtFmojceHbfuMUUlwjSjRrzUMjrvcxVBMXQT5thf-xVBM4zQkP6zgjQyjR-Mr1dSZXFNasde3Aw5bxqQC
hVPhbxUkNxkyTVtQvQthvnTlDLYxDjOg1dSZXDMWjbPM-zhorlFNRWq6LeFJ8cKrq39t8xpLihRHrAh1oMkNjvhEBtjh_QDt8q9RrvyMmLeDJel6rXFkHbWh
28Z1shMnddStmbljYp2fhONr_BiHtcg_Tcsjvz-Dy5RxjMjdFVzkXBVQhrt82LQRjTjwZvHrUMrRVmi8wxeYA7Rh8v6mhjMstbzU1dLBX7Lb4TgxycNhsyPR
xRLA7GzsuwohYg3IlYsoycjNfHjlNLI4hbJMkahRLBh8oXT1fOPMFZFhTarhATBsKUa5hTd5WjjOdKlxsbxSwdo-YtNa3rWVQxYFDTNRM0CGxcAjGBw9jG0G
_tkh65f31H3lONKHGBsH5VUnIhYHrJtMmppM-5X_TNQH-rYTJtUnZjp9-bWVgt-iFybZVQoFzR4-riVwM1_hOsttjBwyljR_1-jZVQoFzR4-rl2_O7siZtKx
jZxMn_fOm--jBt8FQ-z_lRw-RhUmDf7-XlshNTkgMDc65XRMzE-i3I9u6KMGQrjLsqPj-vMj6cXjBspLV1JXHMvWrI9iLxTg4VvMMm40kPnrFhymSWKhKrkC
o7ehKrl1UovfrVdrsXIhMbbWnHGvhwrYPHH2pAsvpJDVkr95hO0OMpqcmCErAse53ApqWvslNNctIYY0c5hzt3UVN_jfApu8036qkj8qJ6tLYfI18e2XrKKq
3LrRG4g0k0m01jP9P-dv1KW89OU0983OMPtV5u5Rkq0DnKSlkK2r5bRdWj15-AZj0CRiIetLYm3dM_kmJfD0O7NjzeyrLX92YiKNu7ohLzm9jHKW8xXQOXI8
fTNvoiylhIroG7O9W8rL4_dQQX4Wo2cBkLLhow_TeHrzVRUAZLLJVbnRG3xw2eYfrOLwZ9oiNG3G7msivDejBc5MMxK20jOQEUjnye7LnMbjfIeMOcbrlX3M
sMbHiGPMJP0ZQvQlQtV_8QIfLMixjmQN9cjtfxMoQlBKwkkmkZ8zBMeFZAs3DR4w5_5kpNN-8esOlczfoiJg_SSVHHT1lBPeO_KLmAIl-TEgDT7QDdkhKaU-
M1lyi0RdvhMrjth1Pvf6_7_dW5hZmTs8cJK8CC6slBS6vsUdHMDhnCXKkxDcvwIrwl9axPfP4xvaPgr-CCDkkebWq_brOFMdMJE08stvj4ONchYHjAljj_Ch
kIXnP-s_jnRW6snBzTrQd8CUHa7KLgr0vQmyzRW85SwDLPQ6LNnXvfTQaKwmjWP6MxshpRktXFfkTIuILtedMtldj5dQUm7AfzKJLtfdMpdiI7L3-CLwi7PP
Qs2jl7PCsM6DE-ktjKq-0d9etQfdhRosUBGojJRyKsrJhe34Gsj3fdRM9xPnHPXOZzTk2Y2ia4XeyyyUxRG3HsitkGeWVsS5Aj5QN_kFj3NChVkrYxqr0MZV
Mu52r3R8pxGojyvFYybv03YquZE9ER-qdzKMC-kyjkbzEMRAojNMbv_LLkAmpYCVjSMdDI95olgdQYlStSYmkknuAr2e-QLQ0ilUZIGtmbjRtvmxTNxnToEa
LQ5lSLHywITfTUs-PDhQjX6rdZY_-BlTo5Z78rKhcyIkNRws2EdGsXGwiLhNzgzsOFrRMdO_YQzdrtOZhQq4LQogBHXhhz7zAgcTMLl2YkJThrDEhErtLcG2
QbNR8sidIdhIsiM_jdftIX9NXFLM_hHeOBMPNxpLghO6LeErQsnrlZ9Q0wj1RGsj_6dHm6fGMsEh2zJQNMxbvrVhMrzZvK-BAXtfjBMNyspysbNeIE-SLS99
B7v-ALI3IbXRTBiOr7O2RSKx5-GRQq_E95cBy4NQQz2HV6GjpYg-zizi-qXqk-H_iawAQb3RFHLfSfAOMIT5DQdjlgIJ1FbYxTaOghNLaiwZjLLhzTPChQsM
z60axwm8Rbb2JVmdiFQMtFKJCQpPkriaWvB-1m
}

sprite $image352 [86x124/16z] {
xTY7RiEy3WLWJKwvUV-tlGhRnh5aN06qyszYTdqm3WxDeE5t8a0ADqz48Q8QRqKBYoeZORxFp2JCJvUGxeeXWZnHS--A8LRYVIm6AfTLikSRtClniehAEoig
Gxm-LLHuS8TuNQgvSmpbgYewng3KtNHDDVSa1eWNL9EdUArbzOAwgQgv_fRDQdimYR4NMpQgW4zZqJA7sbqTt669FIe2aAZ-n41Zox9JHNp5eEoATrG9qDWz
Xj55YzUbxZ7ubtXMpSMvPSEfSAY8YvOvLOH5otpgqB9vYNtg6E_SCfywnZ37wrBNBVEewvPXTgdh9OuETH4lsn8xr27UHSjMghzbQzM_nB9GVKkyLjTBR2tp
gUjJuLFNI-nIrqkyK5qjavR-d-fgcMxQqAsUnokghJNogtFBpBoiZl6AcTirTOn1r4otEiAY8ePsyHuL4492OszMGnIzNuqVK6kYTBUAM44gt_-icVaJ2J1y
HAty0LK65MzfLls86g9yGWqVKUE_Mwt_3FK_LKp5VvtwdxhzRTNj4whgrqC0xbQ5zF5503UgnZ9lZuPmgoggGlBrK30Nu1RLN7x6m5q4P4QuhEvkUspKNH96
uxsgofihz1ClCvD5uLJfnUxn2Y2Hi0K1BZM_r25U8cJ0xdhKW3gumjoUCG1AxJOXEDHGH6LmYNlB41XAhiGdxbeD4GRNukqn868f03Yow_UhJI8rTsePCjLS
WC7OjGhXC9dDdLj6H5tj1ZZK4AeOExKC2P61gBiEDSH36xJYRykGkYhSNOTwZ5TpF2unCoDCQbghrh9TRLX-ubNyVJcur110VzLGQY0IQvcT2YA_Ag9gQYmX
K8hq4oy1U1C8ACmYAg8bDkXgIAAg-wbmg964cSrL8UrgZ96vxaliK9EXBrUfgpbY3QyO6E1TZMMj9duRwQCiiPGKO-ZMth9TJG9BjIeFhYeYXW01In0zNc9J
6G_gTgOsaTcLc2XWxUf-Ac3nNuVtoQ9wuZAJFQiUJeMf88EgL2OsWewkIP9D_JqLz7Cgi6JXGMN1TFecqFbnHIs1uLIWxTwWiWZ4oItSJbqGFPwA1qCDEKyg
it0DqrHfSxogywduGjk2MTKMveaunp2EMiiangCgJx9jMpYRp2Vk-SKygggTt1g7yoaMmy9bqkseFas1eGMhbkdiYXnKnJnHwvRf6EzHnS5mnckplWNhbgbN
7LisnkjJr_5wr7NBpjNjeAu6H0zkPrHrKhTMbjGSxukqihFgGTqsFg__kcK_PAFo_ddFlYabEARAQyrhF7pUq-UpGl1D16t3ccSoLnl5u9v4qveNLbNAuUQ9
m7EW_mC
}

