sprite $image393 [225x201/16z] {
t9fRUl8w34LzjxNbjFEVxVaJ6Tn3YI5HQ5FMM--iJzAs7FhvAz0_FjyN4l36Uc-i2Fe_RrY-DpRyeBkyLVN-gk8Jhp7JY3yG7DXRFg6StMzSXK2FERdUi8Zq
77yWEQ3mEwSY7hz6sW0-pgWtZWlQoEdyng-HQJEdFxZ1TKVvpYU8TR_QlsK7P_UhTQeQFyAP_S3r7vEqvsxoYSidoBSeEAaVLs5I-GbdRKyH_A3D56zyeI_m
sMvrg1tGLfArtfWmI9iJjAV2BnYVI_R69eNXgm-_2xpPhpWJoqnonkNVLCHBshCucugGepM-_Df5-2Nbesp5JyZ1cAWOnLUdomu_utBvIheTHVfTFrtvADaR
lpwAFwfODhIdgdwjJwq9HQ5uV7ioLz1sijJlE_EH4HM6HwSBCq0xSEQ-N-jJnIWUsfxC3Dh5B57Mc8yCpQceF_pKVeGqIvJ6ur4iFx-xJ9K1sWqe61kxuiDH
B3z--85K06NGfyeZG-ytLL83v56Vbc_R6txmy0CT0H2j2ODHlBr8bHygtqH78QDOriWRjZUz7-zeJ_qeMkFoiKLKjkVhH_7LXn_eQ81ejemYNbU-QVea5Iaf
Hb6lY1SVViKRcIZzgSWlI9T9coxPcXbVxYkEjxVRKGJqzRjjJv2AO1esh_Jfer6qyLkVOeCV1ksfBnyLQngPryA6_6WKaxiTHMoPHsOCshFo8MlBFnnDFFkk
71dZYvHn-z-MOcPWzUgWh5ui1EQvIoDNj4SosqVHcxJ_dsru1hYVdgGYMMF2ebXeIUBY9MrMZupxenXCLBotM5aKNvKkDYw_ah74gH1MZepxenXCqBmjnHTm
xE6NdMdu5Wl9VFdCqwEOlTHljoAw8RgVVZcBfk48bq-r2gRAuulKm6zxetvm1-33Rkui0sUY_AeoVuf2YrCGbP2VUAQHdKtQ_oVYhnnJlfnc7SxEs399kjYM
DZxKYLi0-V9eUqks-utPA0XjkhX4c1LviSdscZOyLVJr9fJXHIhsJVGn6mHrvIjEHY_FYXLz7CMw2JVSw2BbfSRFafyL16deMHbRUdfp8U4cW3pMrZVoHXQq
BJnXA7xA-Wc1QG6b6LgwdAnCGOJN_nfGKg6De3mMPD81JdQnARBdIThOMRWkVab6iRXPcAM3m_qYxk61eFRiM-Pk7Y1_IHShWPhS4gVIhw988YmbZtGCu64D
zTtfbyC0fRPqwMdJXCsCMDU-tiYdbCYMEHh3Gz8b55az-pYAzKMu1r3VL_Krx5lc-Zu3Q9-x2BR8Yy_cWllsFQcYXsKRMUZr1eAVf2HrF-vlbIs4UesRx5gS
olUqj96HLNVdIB2G4ad-_b8BaQJDPLcZiCpTRDsMjUBiSl0ZEpakb7eZGL8ZU-RrP8lMjxlyB0ovF4dQe0b7UmqW-HO5g9qN-P6idhZQcBPTD-6MDZs0l15y
9h2wV4F1FIvhYfByrlIxlCJfRG0LspzpG7QE13zeEs0Cp7lo1_GdlorEkJ-kQIDRrU4o5AGzO7Hcuc9eooKv6D7ATjhlll8fVRhKEXJ4Ni71iIbfOtoRnz3I
njWiDkaQG7AtLvPlBCZ0Fi61ejpbqpLTR5ny2gQUBc9zJFd6WipO9IXWFL2RpUtgcMy2I5s-nu8Cx1CS5x75QIEq08g39uSAlv7W7iKkEFxPSFLZz03gJmxr
xVbOi86zWiCyvIAhPvwkUShBTdrqkem51MmLVApOxlBkaYusjW0ATLAdosP11dOBCWPfKsfFbtQzdwgsV1i4zoZ-LxsPBSbrwq3mNgz4OPR__rflHp4HiDYJ
NME0eODdM-eCL980krK0eObwAQlkDLstjey1_Pnc6eZbgMtpHPzP-U81-eXhNO36_wlVln7-f5xxVC2K26y3IF-lydfClBw86MpVI_uBC5PuJLnNAQqcNe-9
Fws1qwNYnL85JCNIyuZhey96J5ZS6-Af5RjPT0KZLhmz8kTqjdrQaJi7zuW2F52nluJfZ7myYtwlee2FL6mk9Sj7iwZgHmGyLh6pnEdaMRH-M07UoPmgMRvd
xi6IKo4VvrH7-FAZmGHOhWm1thcSwZdv6B2gAC0pheoEzd4w6R2gACQRLv7RL_00iAeevfk_CfH6EX6mgYZ0crQHsrVn6B3c5F7cSwf4-Ip0MiGtdrCPyW7W
3uaeKpuVC0KafefgYsUiy3RwViJ_p4VocO3pEPMQsfThcOzEK6f0R6WVoCU0iofwxOEbo0OSH6ng7yl7W8CggkTLC0FbOy1-5QFXT47v670kf-6K89rzW0gr
vBHfz5G0dWUeY1MnvvxaWnU9Ba35zRaQLFJQPyXd0zRcNGKgZhMFvVC1Anq0PiPa-rW-7x16am5JCNYwS3fzmDey1ipKYNW2dW6eYmu0QyL0-rW-7_3tjGeT
02AYpsVCPGuWVvx4KWoSBYmV5tmQ02GLKmQViHGPfVW6fzWLF01IJetbFGtvd9Aq0znkStvEdru0bOPydeEIuWCGjZaxfy_kk3Baim-Pl12vma0iW8IejEJp
Jr4XubTLVEeTJGtomJsuWD3DQHH0-i5CWtnyqQiPyGEG40LpMG-WbrCzdrDwxrMsoSUZsbklYee2k4MKinGrpABPhIByxYtXHQAZNjzBAPklZ7YCg0JvMYeh
e5PqgnZQvrHmDRIKGXNm-aH0wAeO-JsYSfFERhoCUB3mpgi8SraFtkEVKwx-d0AWskLJwF6Z4wZOaDC3ydt-REZbr4SSbo_vNNH5zvQX0ZWi7m1EgzWubu7E
6y2QKurS6I1V0nu0-YfwEPrA9_sSycNtYRw4g8ZF44VmNdPRv7ij9IDoJXLhHUYXYfbJyjLwBRFsFgM-YX-F__f4nGdvOhzA4A8vlLrq1N2NqxcheSQJ2VsS
1WDcTilt7TxhQyL35Q-S1jCT0MJvzdoiOX3TUS2CZNolxrWoLOmu0yZolGBU_bAiMmRJCU1v-Omh0_1E0IhWvkE2dCQUZWbdv7ir-NYqqHV_uMkUlFc-hc85
jBQCWNI-SFVyAqC5RAFc4A12TBPqghW_SoG97EnA9yl7nTDR9ODgbizedtrb181r0se9pfPcn1qPL-FOQUBvESslL5ywGRu6nD0fm5ZfJTKzjsAi609a-G2l
xyhGE63kdd3UkfZwLNJnO6kOpgcleY-VVtRsNnb3W5hgFblcLVIM8bZwViISElATnUFHfXCmOfDEE3l7SnfjW2fuSuUBl_0pOElLCDz4NqK3hxzxyrS60sfM
llah0_5cvx9v5K-jxEUl30QSm3kluecvxFoMmO2A6EdU-ON_yCrtFgU7bwBpqzlX5udpAZxr8l7-ezPY5VrlYcwc8iWtZJS_lOs_nPydh2eM-UOFb_FJcp5s
tbF5JvQYzpkL7gbOyEwNJbxu-RtivZc5iVFkY0g-6cwk8foTzsyYjE_-Y81tVqIu-Uwl8losy_vDXBFb_eYGpliZmbXsVqJ0kp_XkQlXJm
}

