sprite $image331 [173x247/16z] {
r9W7Zjmm5CNIu__aSl_JfcvZYe3LMXuEJq1yKFMud3rLbUCkg0To9weFB6xLfOX-hCIlgcyXzH-osrG_LGzz0SIkIYAFbKJlIZIg_kdkzLeiPojnxRfxQX31
TkLDD_Ks5e6gCDqw1xigYRq0ijl7IlIgPFQ1vTUjQMJQmlBhrdHYdoffPwX-hQjOx0KGkIg9MfLa7LRThrPjwwRU0wYwRVTImBODoYutK1sLlK6i3-WBU50T
aTslB-05yZrW0_82Y6wgB838TrOYk0ZsOYNodPN82o36i_M_o0iWSbLYAs1Krh1T4Na1HBvT4N-iVTbFySHAvB4IUQn47YkvzIVBgAnQbR8n5q3PnJrMohP4
gqhPf5gxKBUZskTX3qZxGOInKhOUWAwc09BKIzt4LG1vEStyqbKLG1hyq893bR8TNKkib6q9MuXBbR9_fnjF0PITt4BQTWxj1VcFhg00o7RIDQXIjfEk8LRA
Tj8rZ9MotNGbgfGTJtT-0PJjjo1GXUouxlm2A3kGxkMgb1tRnkONGDapMqZRff5aN7T-0QIrz7LVy-v9Pgf-PzzEj2DbWIW0ioDGTURzd_PVSe-vjfMUqx4Z
-Y_Cld_YbQ9aWXYG-zwgI-gPcJsGXTa9407s27SkLNgDMLRisrdePr9RyiubO8zo9uMrH_Vto8p1eInCIK3rReyLESGz_xbApbciYXp9miahgqI74NBRObMX
7QzEBhWwmUehxXwnWadzJXPEn-OFQu5qczcEyNeMkgYSYsqVqzhv4mHG-mgt3zMJiH9WjLXg-qlH5JqTMpyoe0PBxgjPqFEmlU8lztzZXy4-vyx7Zk8Z4nlq
2VP9TATYfGRd8fU2-0JxBBepiIrI63vcLYpszrcOWsLjZOoiMyHWN-1Em2vkWnt0kX1JBdKP5liykZEmsM0vV163VHxT2TZeR0muAh4lPE5ih02rFbLXX_K2
x84id81jZzZYTcC0Uu1x0hR-xIHMzbFRW3sGXH_2Yl3xoJcNYTKHBVOG5yZnBdRaXJ_mphdbeHBqfTPIeZVORsPXxIpURGOZuSwvs8Zbw9xOGroLyMPR8ql0
Cxuf2TbY-QmDO8zaeVSXSXmhFQqtToDQliOkNBeEJgwyyu19PekzAGdZDpCRYNsP-twdm69A6IgMrw-nYHNirV63s6qnxVYPxfnBn9ehy-DRs74Ejh8aL69D
2ee2-_huOUp7Lv5Rhlubjc5YYNrvxB3o5ZOxCDPzYn2xNsKNFO0TFubjMBpMN4QrM5bmMN8vTWGiNWfbCLXfsCr4qQbOATrYowUjO8ets5vByWxMeVEmk9l5
Of63hbXAHRKJkm0AwqIij0Z37ejlAduS7h4LKkHr5fQrjHiiQbC2CkjNsD1Kvs7PhnIBnHO5towFs8BtoA9piONRW3rsOF7wA0d3O4CTgdEn4haDs6Cb8fK1
n2ssBrrKPsEvmye6YsI6ZbCvOZccOX7P6B5_DbZa0BkOwx68RAa8fy4Acczav78iOjawSc2mcld2PSMckLXfLRQHzKC2H0RR74O45glLH6pF7X3y23Ss8mS6
Atwx27UNX-eyR4zOwBUHpMkfpnRxqELALvs7HMa5bf6jI0DpG2okWdTY8hO7HonP_VCLvcAmWzLjAbQuhGl2o4AEefiCLYBoCHahTPMciiWcif7R6IzxB8hO
CXiBgqjDTgjieGygOZ7tOP79M6GWV5AfQdolufB1IggYEXVR_KCByXXPJhoNFLP5TJ9Meh6kmY2RHjKj1glJiOKBrlxGCAsb0Zcu7Ziyoz0-ibL7zZmYOf7j
5s7pEcasigvLKf43OBDSW-rFRYiQ0OUHcGFnBdRHsLWxiVQ44qOqtiY1n8NKoTZ12DeJJhR_2tD0wdGiZwziP3Vj_s0Ez3fiUh8NgT3biKr5R9TYXxTx4Lv4
P3mA9lbIR7DF8kjtxL_tPQXUYwqi-ZQozU5dLA_6fYVFLxLLxHAiRh0IYJMHzUDUsE7P-9l81hqzbf7DTyCw6mCsLpV3TelL8OYiw_V3xlTS8mv4riiziTkJ
Yk078tk_1mmklfSPMh7NkYVMZUrnQzU4RS3Di1A0ZMFpdr-wOXjmDwmcXn5ggz7XkvJU35iT1wstn3AqstxhjbZ9TBA9kI7MJctggdV6QllKnYPwQooFFHAe
DyUgy2FPxekTEVx7wl_ONx_-ETW_cxUlxSPX60Z3zy9O__i_xLPkmpaGjR1WODAON7rfOxFXiNffA1OSTjsx78ZbPu8ZigEmOYKuVZm92muRSVknuB0Hjnzx
4cCbEMql5YwnTfZZzc5n2TjWSHkn9pki7PxRX1N4s5ZRWeK0c-0MO-4ELjfowx442Px8nDnwBDp6cYDwRJcM845rnTnwB6om2MuH5fTK6tXj4PR_n4gx7suP
bY2xDjXp5zOUmvvi4arhjjo5bJs55N7oRV1dz9tw51PoM4-CXp_VgvZgiJdk-ap5L8_DSaslXQsYvjl0Vr6k3Qgf-sbDF5mtMLLR0ViskCNzGNq7Yqjb6wn2
rYUjH1VOtT1fLx9OaOlbkykKnC8ZMEasrvHi0_4KzdMt3PHj0tWAQxV-NdzMbxJCdw92iWnCbcW3tinX2Mwk3SJx-LGR0DHnDrhN1dbg_UEO1TEQcDh0pKnh
sAJyJ_V-j4P0AVV1QGr0AtT5Uon00pVL1hWq_UcQzcr0VMveLnle4di28xZxDX3Ge8tRu08BC8XxXUNJsMdZHGuQSbnpepOGC8eRBtA8lYZWHeiSzCPh_RJ6
KqTobrcnjVzFDvxMC2KEwnSv5dKkLsjQuwdZ_XRyrXBp4cqqCpFciI_JoTXuBADp1DZHFrmvx6Yk5dL-JcjgWQy
}

