sprite $image325 [346x251/16z] {
x9e5aWD130E73F__y34whDNXgel3iQSwShpjpz0jLkCZPcHcZCP53Czdh3V1546-irYr5Nr5VYHcOo2cPyMtwrRqKbUQRYNO0aMteWWscRfLqghmTIl1ydMh
f7MQ07IhKVOwdAPR2RPY6tMhf6LZEb-t4gpFSYydWKa4gvSJJKbWgglrom_oqqgGOEEwypY3aS2KjAf3URgLO0iKtIffzJEjm1EOajO0z54sl5eQ02NgbfXk
bRGADDqgQU47FaxtHKaBNpn8jmCHBAvRBGsi0oq2bAAaXMcbwbQ2XJjrpYmIhBK2JRTAMZWQU1TP1Ff_yRnWMJvSErN2iEJyXkC3hv8MpW06NYKjsi2hKRPV
SyUUrpdT0hd0PVZ9kfiDTE1LqkehqavMjcGfOE3TLzAgxJXTsT8OGBUxMXhKfvslRAQFNGsyLR10PU_REnFjr9KSYgAXf2Bt_x-t1pA8629p72oYjNnwJlFy
BjlEzYbN5LoOv6I1eoHwxou2r0RgSvKiS1JWlFOMGSGbEnqvMU0e7NKBMYvlGN4w0BBfKV8OTszQUGObNax8vaS1_jwT1Pl7DNbKDHv-gAK4dzHWsr-mkMx5
9a0ME0gW-fvDArSUZJa1ii1HUkas5ooUCNnk9HiPEfFqLWBxt1gGx1FZIXqc3HgHZPWq444hiX6Zhashdcn_tKRJwarskdOTojQJxQzRdRC1sNxjLdos9niP
r42mBSbEbpw2hIVRNmdYiodPF4ODHD2Ix7Ib1Y8e9TjVjwG-zu-XPFlhLdnMn06opHjO2BO1sKQw3S4s8DjFj-gp0TbEkir5ODQOR1uVz3eHkCPDhJ_P-kUB
fFaMEVKEPDrj35ML_qTLnp1_iMx5rqH4mvzEbeZvdO68C1FHPh9kGvdeT1jYKSi16rSBrcNFFcRclhZYBdm6JbLvHPT4CjmptTOA5Xz3rCU7F4g5rIgLGEh0
84NzZs5byDt-3DUvvkE9Z6kM7TIFejWS6F1Mxczd_oDSXPwzACLrPwvJyHvHptMNT-woQzEY7PxOr0sTY9XPX2yj3dyRnZishIp3PrtGcmrTcgilMXmbIyjX
tMuNx1yMGVxMINuywQQClHbzUjFoyMT5aBzl4dEydf4b5jzXA0jRlpOk6sUNJ02qqxXCiEhxWB8X8imYEimHiFW33HC0xHpKLx0-c6vb2O9L_zMJRdlMyqNT
-644TGDJOlF77KlsIvUGOmA1HL0-IJvuoucqT3mOpsZ_7xE7Dfw80pK4vQhbWdNUT8zrMdcP3-55lrqzEsEjudLgMeEsVHoevbUioKDRs4Rc0xo1RMrQljkw
8nojSuR4-D5hIi3P8UDDWat3luq14s3hbv9zYpyyRcBBf4B0BndGj7PEUkNbaMUAUsI_D0Oy0W84ksielx_dCGmiWDO9dons0IODzW_FsyWEUqyKb8laVyg4
623ONIFpDhpbjEHnz3oD1NMuqz1mO0AfY2njKKaUHU-8Xf8DS4ZJwd_D2gZjfUiTsx371jJ9GiyguDaQikGJYF7vB-mkgUa6WjfW_68s-lp_l7wvim4SjlTP
Gp_tGhOtvxT_Ru6se1iWU9o0CLWIxAuuPiGtrxlpltyNiWdRgjkO8sYtkmyo_bBr3d0DieaIHeKI51eovJtSXrx7PcGWBZ3Qr47ER_-koUQwVTMt0xbkcVfm
-lbQ6vI3JSxhU5Im_sx8RjSjyQ-Z-DzP7koBbF6wZcPtK0P446GJjWNFP_Fu_VKLdCrXSFRe-wU9DVNib9818hWbkrstOXFDzhNQnBgox3rtZGajNy33yzyL
1KGGP1EsfGiDShnZQBPP8v-x7KlsGvZeQt-2hmsI6131VRAvRddZt6rzu1N--OsJ7U0QP1Es1UiDoXOVgGCFga2m8TZ8lEMQwnQOe7nfu7LTmHK66rmJiWMw
BHT2X8UdM8SaG-z4113PxGrirWPyLXUzuhQ19Ey7u1faSRODrizclrx4eiCyCbIOac4P9e8WcxBji-ORVyHCbvoI01SiIBQ_RWVjiBimk89awmUyzVjhSAvv
qyB9vWFU0YKCDI_S6nfS8S7YPBVhbiRpUYc9BjUvke6FTJ2iXZUjd2ok1C5F-VR6JyIN43P7dMp1JsePpXKdY-jMRA-nLCGtQ45MwBACm0gA02UBjriEhWLa
iRX5URsjkCYa0Kvsksv3iDLayRYRZKlC4gA0242ok1B4PmEoIU2cXPF5bP2Be3_PX2j05cQh59-rq9SipXKdY-jsbs6NLfBD1OkInJE1z2SRWiN9ucbF5XV1
pcGZhSdY8YWaU-vB5XT13Tb8KxAu2Ch8HXgInRcMaesyaAnL2hQUxBaxsLom9MJd41QrcR2j9JiAH511zciML3nZsvziYA26h9qY2TlsP8Dh5Td5hka4RMUo
8O8oikDcIql2jYtPu5f7ba_BsFacpSc620h9plYK8Fc4F1Aq3Sb6qoebwv_thWi_3RJBT2SRN8l8Me2zy9FuNykq91iYA2KRDp2F7mJPPx5r4VyzMHFnLtF5
oV9tF-YM0MywiKuAaisFWekWdgpUjbYdSVunczTYqW380aU1kDPVizzHkf-JRFxwBJQOR7uKN0JrPEsCPFEQTt60R7AKWgQLPexpUXmW2w9rJPZbPFEZaFeB
H10voubi7LBO0CdcnUuq0BB9KLx7zMrGFBpAGd47UoPRatp1U4vsVTEgMAbW8qwn4ped54E3PxBLH_QGZ1MoBkbHwWGRcTzEzLY_XT5v6zhjUqXoii1UYLB1
wiroujLRs1rfC8lD9Sl5JpRlpM1BoQwU6nwb8WZ1BYCJ5osz3teMfu4zkMwnBNi9MM1FMfrW-ISheJhWEt-XNv0yo7OLpyzarqvAlM3FahZj9rlIVHdpdKa6
Zny0kdrks5xGjF9JpGvTj05bh8qh2hy1cSOBH93iyKrrE_ckQTtTzFsGcfB5TRizwgzhMdbqWYDSZQisVMN9Do2BlsGe-rZ8Vi97yovQfsXb2Ta2tT8VQ5g8
RiEfdDpXE24BwBQ12DAcXUjsqkrDtyslS5f2jaAtyXh1eg6nPEiKpInkQwJ--MY1RyZ2If1UJUki6_-eTz76C42lLdhPnRHBiZZRGOq4QvlznNwBDjXE2h_D
q4525c3RMx1u0viINyFvVuGHlVnRIdRBWBT_qtfqm1jYqK-oHF4ECxAkSvy6nlONcnQkMwTFifC-4Fed2BuYEzsNAsrexA04qjTD6kJ1TVinn_Cnudt7_SwM
WYpVp0FPSWoIirLgEvJThjlBPthAXnbk7jdu3own6CG10zxcJGlNhOd6yE2JPv2Dw6BTdKC3NhXfrJ_JUhPkO-QHPahs90bPGBUT1PjdQSt0oVEk3TXS0csG
HGUyz9U6idB2WmzuWwVDywGbsVcrryaIii20z_MJ1kEqNyZkFfebeMKtaA19Co4BwBQnOF465YE79Lcx-hz7GXRGRU-cXJzV79IHdN7H9cIXvujYlOQosnlO
-xk--822e5q_BxU4BA241fC6pzQj-pppVRBZWZqX2x1jtRIsJ-V8BTdekGbPP3f7MpSjNBTnSTBy8gZVvdWy8GkmVVtoZ4BTHfoloV8tifQGHT7sRrguRas2
x6bUanq9MO1jWqc3tGQyGNPSazM4BC2sSTF2ep-HfRc9REJ58XZL97FT1jaOtzubQwfZ3N83mHOtCBiC6ZukPxaX6pyLW6s3eMn10vjw8hqWd-DqZwo6Im2s
3IODzjVjrDiD9a5sNhd40RH5WeL4KD_0Oft7RPyT9m3j-RKx3VwiRgCd1DdFEiCKQDEKxZJuaz5vRsN2xHCP_Y0wnoTsaEsvmQJ1lhgLwseRP6CFrEG7DqSs
Q5grkdMXBqt4pCtLxDZaHtUXDsXQjRgDHKWBibUy-VnGAfzfDT1j9CZozUlYebrF0y4M37Xpil6w0Mn3Vzjjqg1Ds3AoUlqw1xQXlpMOD2WTy2x9ZWlKZzSv
y0JihK2m3NNhNsJdfHjSZtP66Tbyfq5JtJf_LbjwxxEn-4KGilL3sGu3tdUouyEjKpzVM4CsVwRLMxSMJsliQai9pNAoUTDgssur2e7pIyYs56m-u8sBLgzM
XXMGRTcqyFtHTjq8fb8fsRnfTM-t-kt74xY37O9TMIukdyl5WRmLDAt-kfrozHtU0Dc2IOFskfMG1Khs447Um0QXPBiEPUkNYmjAzcXQaVoBMOmXiaVJ0jOl
JXLMWEmXs7HRvt8I1YHxDArSjtZUZgO5w1OYUmWMqorEzcXQkMvnicNBC_eFUB5KJXhq7_0YEPhMzW5ldhsQrj700150N0_TxYNOGxTxDQr3jrkQrf41a3s6
ilZwnJnxDQrZmBjv8UmHpSdk9TYZtUubsAE18HzFT0JvEgszXhA7RlUQbJq6l7jD6XowtMieUmnudzIqZembsxsQrZ7WtQjf7GrihwPrw7OlmHu3thqc3GxT
xjMq3jtk9TX3jtirhKEt-pIj8-nlteZhVm4
}

sprite $image325 [173x126/16z] {
rPhjSgGw34GbMRPi9U__l3S3ap3JIxgMfKnn-yz-CPC3rJx2hfK9qHec_vDuzDwhYjm_5dsDozsZhVyaoiqRqD_IRbpT4Xros-fQwpi9lsDPQz_YMkzSNO-D
hYeyvwRtqzMQi9q6r_lf2Ylgz-k2m-A78jz9OoKeZxNxQCnmOF6xyJleYeE0nkwWAxe2QLMkrnK9Qanl_tRbGIRmbRewNF2mM-ZAz9KF_erEuEjrvRt8bjAT
QEngNOKY2y3YtMXSgJ4Fs0h04mVOlKkkqfZjRmMs9uwmU0ccwcHTONpJ0y3Q-oMn--d9ki94iUW45Y_1Jq_H5Gk7vMasGLUpOB6wvtKr5RQ7JophULXCs0HT
JO252NnELzDWCJwX0TDWUvHJkfeFYnexfQlviAYnSxeAZvcm63-r5TWfBuNLho0i9bhriiHhRN6YkXPW51WC528YUe-8LclVJzIYyXOrRr3T4vj1BbmU9Fq5
H3sELzT_hO_tqmbNgXy-WVaEd-dXx59NAyMz55FPKiW4PhfgXdeu4-nKZS0EOmVv16Q7wtu4gZLOtx2z_5E5iJtpjgSnhgj_dMNXfjyBF82LVva3BT4Owkfu
MV6h4QlWeMAh_fKQ-5CLTz1SLrYEqVykZNnj_MPTlonUQkhmSUSJs4bDh9XP-JMsVJRapyJMohRa3HtkoU53mCHrTT3BU_Kgl9_GKttx4_QBwue7EzXrpp2x
rHQClTskxrNCYAvcmjRTkY0ifYg-CXsFKoawNOW8Qs_t3naZnzbzXO59yTXmBxfVxNXhC6HyV8oldDnZLfZc-_9klcRtqUfR2tGFDJy_FyOIjg-mKdWSFWpZ
6oMwSri5LDp_I7vyVgnF5d1nA3WC1Pxcfe-ODz3LErdxdWhcWHTWneAwmWBj-HUkYBsg6aplzOKdy6TQ_8BwcMC0xeHNMQILqZga5QWvD01W4TTFdY7mmQNb
PvSORrkoieUw2qirvlrai5-gzXLLV4d01lm6UxwwqNcgiPV_7LqHM5hTyZUzrEArhS5cWWQ0jBIz1b1Or9WVN6GcMmhJ6pasm0OWBAikxG27vHkrMjrhnVqQ
edBOlGdilP-7vS4645XUtUZJOH6LmdBSQR2y0GXBSXaiwkeGR2RWpeNb3U2mENh_uRq0bZU0msQOYDK1jDDWEIg7pQ7FCGrTc0RB6y1XgppZupjpOJagXtKH
gSlWyWJSER2y0HnseVnA4_rBZNabi709rTLnM1E9N1PQ8TPzdyRM22nSmXh0aoCHjZnXHmu8E-GiiGkBb_06y7mEYqpex0gxHplO2PllmE8bPr0_mqHAJxH1
ossMvS_la1QFOBJkm5Ob1pG36i1GHv4bTUGBR7_LWDU-KcOyxwdJJV0ehx23Rum0bR5kGXLjcQyhJ4Tk0y97hbLkOmqxQNLxPST__DS6VBmVQhrKDqEavbXZ
AgAHQvLx0ksXixmIH5Uq0Tq4uZqt7-ZMurZiy0OBkCsE_uU00sLDbp-ZtzNDhcBhx_CH5ni0krDTdlhF3QW2WIvaYEZZzzcij94gBG4MSCCFDE2GhfHyQrzm
yt5DYJ5qqOrBMM69ni980qxeYkQvzhijw2AoGEYp1hdYDj0OEOO-goiURG_S7FLHN1NFxj-mnRm_DLQ9ngReIcXrSrJF8YKpVOLTqdA1tIe16fkbArhTrGJz
GPVb2QlLLeqLeh4fkk9vQYohIFcfGViO9ZesMAenFQyhuS49d4tU5bWNgOcmMDs9kkBLpLxRqjaLC4ri0EpE19wYAnv_LZT4HhvCNO3TmvsdAmnEuEnb0VHS
IXpVi4bmP-gATo5N0-Z8PPqzOGakGJsjAwwnRQMLaRR1kbeRfBfJTON12LnTpEIx1ckx3BjxcQwunZAV2xMli2QYAefL65DrTMG2kuZuwjcXOcEus1YOQtJ5
gxjseQuJR3nWUwP9ou4vfAipPUKJE3CNM5tVTMk6M8w1kKvNlBhZ2PicAg9rLIuaBzGLh-x8feiDIb-wrYZiV5tn2Jnor95Tf3-mfHBOQtJ59_3It6LhDgeu
WRrALxmBwt6DZymU17QMhevFuAwYDNgEmx0Joyhtm3O8xAMwuXhBKPN0Jj3LoGaSRG-MwMfkMVa4JW9xlQxu1DvDdj3LvEfosEjrnJN6OQ_N5TSOXxrULtm2
8-mDTCKq1h1SLxUgRb9TtQowUGzTyLDeW2Mwkb5ra-ZgJjLTOIVeQje4pdlfYa_W15tTDoKoGLTtZcUVKjR_
}

