sprite $image361 [156x232/16z] {
xTpdajmu3CJnooU0rCpxl-t9YHiex_-sMTMGguIlJhzHjm3dvoyoZ_Ws-RpSnAkvbYpZpMnNWhLtkBY6R8jZikKxNLwdPvdJeuiBo7wko-ky0jdoGhLhULrT
QmF3mVfjhMM0xb5dQms3BRIzny0-yTeusCWwsnpifFkhpiQroq8RrouhRFMrOni76uy2M-K-OLkzZcrSkzXyjju_NJkVRPzqYJgRRPzq66o6pNReohOTs_OU
dwrTscpxzc-KxHEs_RjbrJvXsz3vzmdRZebMf6FRhEFQfSrMLpksLTMERH0iw2osOmg2PPjUkpJOXiwoJzZM9rdHFc6RNhlqsNYVJ3gFpNh6sEQkdMxJzqap
sFGpzd3O_6UCRRnFalQ9mIRNBXqslNOEcxvF33QzTk6mwJzfDzZqCsQmwTik3JOzM8DDtoVvCDZqC-QmwTlEODDhbmQRViPKcwTs3fl-cm2ApLSxZqq_OxhD
UyROvgrT2ZPRxLAm6MkdsKndB0IRRv-4mQR_fg9ay-yJjldtIQ2jidP_WQsuTcmht2TWAwuTs6fh9zXyPop1LbYxR62hgrtstM1JVZMMXqUm6SvO7Xos-NMP
0mCsUx3P-c41Muqk-mwsgc3pK5JOU9zastUsrGJRTxGvTOKsdYYqyMITZMUhi_7SjjjsssxRRRjjj-sstRRRTjjksssxRRVjjjssstRRwdzli5tMrbl6TarR
o_Wo5xJrZE-pNStM1WrqVjjtsfYBs5XNRslvLhTTmpPq0Rewswohjq6mLJRy7v9YAxGz7wWhintJI5TdEmPhLsWJQcUqFJlgYcnrjMDRNUtOLbKxjjK5oxQg
ODccw_mswnbZspn9Eg_D7opRT9tV9fmnZys_xTYc1skrwMVCR-FQUMp-sh6jhdPigweTs-p1wZOzs3fRHYG5MsFxhc2TtnPZg7PkMxoQrZlKpcdBU6Vh5ApB
jcLCDjHPR8-8c6o2JhTnqMPR5xQTOcFPR5kftRejmCQw9Hl8m2RfrcqPPDDgjsxR8j0cr4wmmTuW6-ja6yV9DZnZYWraO9DqkYr2jEqKxAejGxVjg5kpjLon
xHZiagrbohQXWtqYsq17DWvsoTPQIhOn46p8DjInRSSpfjiWMBRjcNp6T5jhkMAB89rc6vChjiY4O0KRwjZMnY-pIQVRpckNPElZ6s7jm0QwCrmxjSsqO1tO
tasAkbDQSEt0ni6oRjYchmmVDj6sNhjNxm7h99jUkq4xmyqwmQRhfh9HxGIR6kn4ms3PfkdcHpVJM2VOf7roLZOEzfLjdsmm_N_hpcdywDYsNhifKT1DWpRz
ZGKQwjYcwyveN3ksCGvqC7C3bcnSErdsJQ3RvdbCEadM-Z3ejdcsTLth-vWbspmTW-KunpmV7zewORXsdudpXseybWziu91qNBJzTMHdDf39PupZV5-czxQz
GPgh-uHbymA0Dq3NGT5cslpJ7PscRxkvQEUVLPNfjKkI3Ht8LeFbEA7dFbssRfJnJzefpafTPgMCjntiZM8Tx8t2O47cdezi_LazFxLP5Qph8Al4TP1LwZhG
AdKTP9Nxf8EiRhxO7i_r-Gy
}

