sprite $image401 [96x119/16z] {
j9ZhOkmi24L7Ow8WzltVzhjCEdL2kewSs_vRt2v0YTF7zyfLf6wFlwHqo5D793YNyfCWHVJqrve2AAfISznzQoelQOsYb6XfMk_JNtIFefIOlLh_JpB5cUUg
0e6e-hH_Iq6nntktIwejuY-zkmqaGMrinlbIihI_zBMiOAQd886LlqA1E5CDN8DcjmqQ-JC9wxZxovBa9mgqzQaVhwe14afxBkEiYpcIc7znMDmrTIJH6s3l
grHAk5KQ6xUNLKV2mEJEiZQ8fHQhrXmhfSeTXRLzWhKjEAow2g00sBcefl0qREKHrowYgYeg-pBqzA-FN_nyjKNMHVL__7ZjSrMLAPKjWEAFCUiupmrybk3p
HOUVxwIkl_2fpZ08Z7s-jF3uZ3u5UAYhggHl_Jq8bvAdfpxLmD_ju0An_dETdkhxcaGeaFsxVYc3_oJXGFQV6xI5FmI6_Vl1_Xp8e_aEje4_1EALWGtkXrGv
45JKsBzNGA50hqrETrftkSQx6fEKG6amyOd29Az0uA5b5L3ma08F9hw_NlsHG2uDWsL4uVj-t7XuNQiM37HVwA1_Ptk-nbju0nl6CNoDiuOgr6rOk9IZldTO
xFo3A2qxtQF-tOPSdmBfgKVf81js5MvmeWpZ5olxssYr7lzhF_e29VF3anVDikPLv1xXDtEh54uTa7ZjlZxZQuDpbQLe9HNyAO5JOwDAMlSa8VzXLwm3-85a
xJ_iUe207qX-shy3Fv3mJyu9Sorh3fF0xobVLfTsSVvCacB-3kkO_aHYa-Jd_GNyYSJN7zEUPGtw2_076XmbyMhVhF9O-q-Gi3-dNS4VI7xQNy4VIDR-Fksm
lz2F1f_sRN35ITYVophzeS4qGhD6_1lu0mc_jEPflZUu4GatU7VnMDRaOfd4pGRo7-RAMYrCmaUJqsuM9LdOJzTt_pZ9uLgB_iC-2po6COblm8UumSdympvl
QDD5fCqrlSn_nO9ci_ImCIGlCntsQaLDztS3-_T7qU8Q1P5gJnIO2rIWvDwrx9_RMHhNNVQVX-sm44b9y5bSlRWrJ3ALTCa_h9l0inb8_AkGzJhpsNMNheer
cFgWrwNP7taPUQ8a7iii4-gkVyDPeUwUCVf2Tjg2cLuAb7mDF-eZbwFrkmGCxqgtxaxxnXFLe_IzYZzyla3YxQDj6SEs__FVBZlu0crWFp-nI3ysFj_9kRpi
9JurHfabu0A9lIyHk1TaFnEW0ir_gDb7B_1UGNiUC6d-zJmfmmvypdcDZxxnXBbTiNzhimlaXe8O1iFsMvgirViVjnpKm5-83j3HfuRTjqhdwo40dAiOm0Ow
PvxlK02W5w_YWFAwwFUWhNCL0zX05W1ezjSDu0DnW4PO3603SO1E4H3GVmMe0m3E0r603qI-coS3s40Kq7y5g2G0Fb0N72ZH8yYpRI02u0CDmLe97a44C2YW
4WAi5WHq2A2rbZM103ZGOOyW2B1Q4D1_1QY40Ar0oMq3CS260qtPKum1Uh2iKfqZOnk0FuBEESwVT_Nm1cm0rJMgW3cVGRMTxAVUEbSv0kPynft9g5Q590Vh
qqygrOpdPTJtD6y
}

