sprite $image249 [273x193/16z] {
xDK7gYCn48HXc5pLFTxxttOjowafLkmG7yNx2GuYwLFwymDZ10cW__ej8eYMFSa1uByukeUz21xTBd1Oa-0TBt00TEOOhpgR1oHB3vdeU7luY-ZItqOSDLg2
Z4Zgk6OAeZkWZkBVcOBefF4U79BG5aGdtGU798mq1j59B_4TrIFJ6aIl4ev5mX04Y187827xmmwaJbf9E1fADv139YtpZbPcXexaCo-E3YAHNo1dAwDNE9n0
eXmBZU-nR1x1_FgVcMOW11I4L1Bs3N9CquBNtumq0q5BGOvD7vmEaijqxuXUrcmu56HT6qaLwI1p0vaf7YqV3WMvjxEIz2EpJAtLRuS0Gv3MTXIIVgbkasmH
0v0RD0MHSzEs2AT7XnK8D0NfxIWWzpOx4E82IBrAyltEF9qSG80h8FqggIBRD2tf0W9S0T6hv6mbpzC3XBW8ekVcV5P1-ZUNj-LlE_V2s3Po0m6uBvF43DRv
__-sPws3cY0vMI5Y9SQ7llFETy1WTtMf08cQPgn4leuCWKk2cDL0SfIuhptwJUUQ77MGV2e945xpKuXvq4E2H9H4UNfc_CFQmrs0nDp8j-RvqhibSsYG8A4a
-KFQ0_G48aXCYk1Fc1QwIn0T9R1KVq1u291AbE3gqv91vXq4FJUPvDBJ8a3gKMBNdHODKe-IvOAhbZu0Ke-IzyjEYmQvVfIWC2q2f3mte5zjMZH8dIGwa5UR
5WrIZfBem7QrtQ91ob4I7TWkTXBJ8FMvYPy25vsMEaX-OymWpcjDYmOfHqc8D1hyIjEYGSfH4Y0mk1jUr2DnA91YpHkGtYF-YXpu9KST90hX4IDZR0xZgtc0
hei07Wy2myz_mqjv372S0j97XhT6yVUNEQfZWECSa4OOMpJA4ppg7EUEJ6yKs0kC2mSuJWCnT8d8LhSdUs20uzGEwHAHhJJW2UDIu3XjP0mnCZrHQ4zh3uvp
dBTbO8R6TQFmAHvmMKXrtfQXsJfRQU2hUH2fpjqoXYuHIvZsdyToB8LnKHnd7ioC3MOMF6TSS53mKDDo_i6CPlR94r_epnqNtHxd7ypC43pfOU2f7i3_4IJj
MpEkijNuY2Rvp--C2o7gzBiCOMPCN_ZKqmT4dJKo3H4UD3FZQexOWAUD2o7gr2tZY9umC-OBpl8S3-WoUpo8XqJqH9-R_8LdhLkMsyFi392-QZVx5iO7NN3E
yZ0x1mHcI2Fp-M-6bAqD5P05PuoBsLaWNrTjzCJX1SSB8YGA7jGSvu4W8YCIL5vmAY179AorXtsfixOC35qYFoWQQXUSB4ASuF4G4EQHkQM3t_etibLVS0eW
cQGU7sQx83Oz22J2Wx1rjhOl5npB5voQ20gdCUcnB74omr8auT71BDuIdRQvuFXlNN1s_-Qb2eXbZmMCmlmGaBnglVCyz883PXAwgj7s210nDxMHYV2uJKWR
k-3CTxT8aBYk4O-bbwr4k4mF79dLt1nSSBwkvsKfWP20o-A8HvIjV-nvUj38HAF4MwA-u2otgecm098veioGI7v_PDBLbdPmmR6uuDYot2M2Uq2qH-Om06IE
aZh89YnxZnZL1MTPeZ3sNdQFYFPOjXv1abPm3GHfP296kPEjHFeb3JI9sNqWb1wP8of7IH4aZgZvBjCtooPRaJtCj0Yi5uT5ME3OajXS0w7TYfjixI3vWhFb
CBDVjSUTBNBiiIWF4IK5aFHnT-y9RYyuI_RG8XQ5yimCSeWegO2OMHnHiNV1GVC3ZX2H71WMQQsvy10S8aeg89P7PdDGonpwppHonN4FI2SfSO2-dPiw20nv
2KVgxhI75Z4DGWdIsifZ6VRumCmaPP1OjQbHO9AZroz1tEy2OV98708aas2PwY2MpgqoF3G8rYBUsY18p8pWq20juMCkWyGHLQ_Q4H5YDOtSzBBo822cHPIt
NfkvAOFaZxl5jAJIZ-tWM8j4UqWEtI9YRaeWgzSWmQ55c4N0vhyMwHoGqw954abQmKKG79pJTUbF7mpmvXgaJmjGvCWYcQGC4gjMScYHtPTshaYEE52ObYGY
egG8Sh1gTIqP98lOAbntfgNQ7bb4Hea6gNFe5k6123n-bRiSA7D4qPkOcoA8u52r0Q7PCSdEjE2GeoVQ68wd9aaa4gJU7bhatRF8DagsxO7ZyEWl7DDiWqsY
eaI1r3dg8X4bcKDCIxpuBBYpINIKP12WC2sgy3yH2f4-D-jfWGgF-Ciw5v94HCaM11ZZg8l03adSWmCGgrPqI7bkZa5GdXQzVD-bY87n6YGvGcJwp92uvnVd
9aWEGG35KU-HzoP4SWSSSSGtH6oPkDK-84eKI8b3BryjOfeZ-cAQbitPgqRYcmlEFeZWE5V4e3tmCqhjA1uuaYNYLB87KfiMa8GKqLCJ9NVBMzejeacA95kG
6eVt7nnb4SsHb-s2w7-cMU2zAyTTW5Id9NxqQezeZYpITmiIWGiFQU9-25BTBG420I95WaFl5blcEMumcp5Xvo0vZ78h0L9SjMozA3eaHFn8HE-MsOvNXkSu
SUBEsWSfxvQRzV7oy1zAH7D4SapnPNAzX561H89OlRPOFwH8SEZTidpf0K_hnRTjmo991Xdt033wV_tnGuiiT-sMDO5lPwPCSWmod1iqNN3V0KaYYIEFnXAx
9RN0KPRojviaUTX0nOT0fgSbWMIHBSVUjft_gYMrG8fEUbh1DH0WG6ZbeuVco21vQZOUmn_9vUX891KFCqC7WU2eTGZT1SWxGyHsVkQ3avJdW-al3-_kphiy
R35GS5Gp1Fwbsez3aMWIIxLxNSdhXRfjmBjMSEIPrLOj03qjKUz98vxGz9kHlhynmlIuIU9BnZbEENgiEThxFiWx1OaGsVQ5vougd4eg760ypQj2uiWU-LfJ
RnA0ErdgWd6yFUwuiU0UZl0G8kCasql-mU-NlidVzc0EGniuUY1FI_98rLWYyP4ipQSILnnQeGuYE0PwX80KoGVJJ990OaltKHSUNUFp1wL__j2Z8-FGqw8v
3i-iuqsIB_bnwPLjezl30EOt-H4IEZ4wBS6XHMeaUGN7VpzQBsRBOeSSNICIwlEtWW6IuhHeaiP2b1nbgMzlU751d6qtF6u_76sEIRFfRPecQzoAG3sdrwT5
aw1wAl6Tmwo7HpmofPC7yA4nlTtkPtqr-lBnZLk8R6BZF8xwt70hahyaiZG-pRRS7hq_Fhv-RetBTAk5ZVFRnFuZxIqMMdNLZZU9L-V6rSD0h-KjEYHnB3T7
_FLLxijRrEmD4pvfKuD4YrJ3uxmeOLpovNg9cPcMpJczC_eqyTOcKPCtPzkqIDooozDIdniT9OUNVDyNkG5OS8G7Ur-PDRwjokA78V9VVg8yBUT6IKxFV4or
MoRixfPUHaRqu0X4R9NAoUFyACbD4SlNvhnRyhK5Nq1yMeqCMyET81MEyqybnnzWH7Waa7Y1dRvue76U-uz8qbBLBlddHubQBnaasYE1V8hOmkPnN5dOCBrz
W00K88NmE3rAr2K_HkReaW-IiMVcsvgzjNxpdoUJ0AbFopFd9Y-NPVuuPjdXanZ8Q96R73zLu-pUlyKJfYM9P1984d79bsz07OHzzSOXjJNU9g07Qe0KdyIU
DpUb5y8GYGnO7UsaXrorhqkYtzD11WbuQmjlxRFJukjEEAUV72NrztIivZ9gzSNrM-sJegGoBL40PG5YMaHulEBSQ8ueI8yJmkC9ftaT7kCaG3qyNZ1ATZaG
V_S7zE0GBnGUzTEydXRGczFwHTTRCW7m9LrFEAS_8Khaj03UtAQum5dpz0CzuLPR5Van72NYdDxlAAk7GZ4OBpGjUWLhaiFT0hArxX6rD1UBf7HEVxqeiSDh
YzyUWTBBgG0fXCVJIGH7zZW46HUH7AyrDveZGFB8pBTWmXN2equYRd5j9rG_glg0_29r62NgO0fsaRPQkzq3L-RGKQ9ljNrgdFqFcT2RSn14Shpct1nnP16w
vpytX0k4H-c28pZK3GwumAejpes-rQBa8JWkG98uKW62e_QU_lfH4Xo2fCOH7jSYiSGXRyJN3GyzDseAwdL9ZdXZB9bSFppq2gwRN7zQzDo4oJUR5arIHy7L
EMBVE8N9D-2GKQ9DwhVQwyzDcDJ3u-8amgIqQgykaiEa_j5rW7n74nqUrwzn4nqUtzK4WkCReG25S_gV7oY0uFYM9jGStt1sQXzTNv_azd2oX_BjsYDC3eP7
S7pFuVc673faKtZyRUBVc2C7YfFqc9PlRz9LdgBnNm
}

