sprite $image307 [320x204/16z] {
xDa5SWKX50NH-F1kPFQ_saXPtEWQu_TPGgC5y-7KYrcWNcT1fLvTpLsSUrrJK0zLXGgwSa51bouAQ3rIq7gae1jVRq7TrX-rkPDpx-ifg5OlG46FZTw2gZwn
t8lgDwiOZmqeNlWetwYW1pS-o7gKzQ1O3uhl193rA9Sk5Ej1a_KWwr4U6r3pdG1gpZqeRdoGzQ1O3tBZEz7NrLPx4Qyib7CFQXuRaFKewr7MexpmGTQZNBfG
h4TP3shMWqOuDYmurVAI3Bg8Kol8Yo6FuhNgBLdGUfJre5YF6gxUQxxXFfccDVCDTnjChPnlh89LmotULzC0zKW-hWrGZvoyt0eRtvhzXYbOAygs0RDjF2wl
Qe22hRRhbsrUjhB-v5i_uB8pz9XNbYy2vfV8woxYbbrUbr_zDU0sBrklOVTPxwcz-r1k7eU106md4WkmKDx_QQ_Ob1rj8epcP0MyFzhfdluDiImfRYByOO3U
zu8YcsUxnEWnu9oO0o9JgJg2yMkFIz1Fm7bQLLKs3770FTS13E9hORycEFIYvunbF9ues4zfY6D7TyD7SNfL0F8ZGPQBVU5hdosT0lKKQtvp3VBP9lPzMRuc
w4ccwQtvyH9iUYhrPxA1Bq2CzHm_4fGVr6jJwV1H0lLyFsrYFpcwgo8Bhs0_1Hm_5ln9lPODZHW7AC1clpR44lmowdqe4Z6wlXyBHbpNd5KPk-cwVbqA-ZCj
4Ng-NxmW0_RmMmYav_jneeSud4-0_-etHGznF9yeDlh1pA2Bc2hY1BlMOp_OBM0_uA0XzdsYTmxMy_qCDWVi1qVmkEj6Ivzwx3VPftpZXrSFiSZcXvOelKfw
Zj_qJvv-O3yL0FegGLRQ-D0Y4brylj-qxYVNGaDyr6cvvJlYxlJORrhtksH03nGalHNYCBtzVeFgUtrb3R8FwQq8HklvVZEWVkCtvCiuKWs-ID1JYW1KO8yV
zAlVDMkwZ7LCHmsnVzwBFxDizrFzwWUfqCieMWuPOfyeMC_tumA4Vki7tFo6D5m5Zk1n5xOeFT-F0A6wweUSYkRBjQRSXlW71NlKu_ileBhkfmAaGV9RkLpU
3gt1VlLyFmhvrVS2oF1s6IxlHzTW21zma1zclw42TQpNTq0By2S9Yk9WFnboJg80ybNGSkILhdyzfLyJSlqWEKaPHO7yLd6yOFTwylLtoJq_e0oQngGA6KP1
IzWGn-kr55Um-RNab8UaGCbO01uX67jNyoEhluQAR_tqkGQ7lCI37JB4VHSVXOUO_MHCpneSQi8YWxnUiFVHPRz5XFrABaddHLYL_N9Igi60nEbLmSSo4_b9
BhdcCQC9abyfkL0D_g5w-4vFWGyAp1RzbqifwQxqDTSaOYzxdkvvsz3lzQ3i1pJ1vgTfABcKjE9d_mR_co4Ml6nqsw-HSt03nEodkIWabwIEdw4420ON7-kn
uDslvfo1EexWQ0MksLfIG0t65X_piI2QNycrPW4uafC-_Kf9THRye_JKqNC1s_pUzuyau8Ze9p_KCjALxe_G4qVFomr20KXAp_t3xBDVcz-MSG1w5LGSNtmS
RO1QjJxsZxpqUtkhDkVQ_FghGS6HnUS3wWqavq41G2vrwNUv3Cf-i-3l6rqE7eArkQMbt_NoJnB8Btw8u_Lu3NAQt_LVmMiXlsu4vTN5fuwL8xZgzsxfya_U
XVpw669zPV4vUcw41CdFTFXNS53o2nEC7rr_YDdFJDulDq9H00SCSVZeajxUDSX-PkLwMuAfWgCHWl75nnc-0jPFVeRqZnzGa_Gmn19OVFuI9B-tqURS-qzB
rcX1KHnyrTrVWyrlBFR8-z2U5Gf2Qr0GNNo-uDAlAFa14bc3WeElkli1zUadATVFVWO0Yneqeo7-BSNd2pO_e6Oi_0pjmgop7maUgnT-ujk-aKXxLAtuv9Ug
OQv1dVsCQZ10BwRu_1hKSYU2cfdU_IggF8QupdvcnzUWlhhuvEEmO1RCjR6WrF7cPwP56rUkpOy5VqtnRH_YLCfuzpEJYXjNdVrOKEGt5PylMDjEaTF3pwoA
iH_NOC_5Dnr3vjUWbAUVeOgH7mzng9x_FFzJeHgy-xM8afyZ6A6d0SNd3B7S_Oe-eCZla1eK11JV8UVfzcvWKk3wyLdc5vpu_0ZLe4abFrymJYz-yV5Pfju0
KUMptxH9CBxuy14MNTQWQT67N_lRpjVMe6X8yHs_4pzhK1LLxdu4kBy65SSMNsGDvdeNhCtFPZzVCBJuD8JClzAPDJykG7-8uuklcnfiVXH7iElY2xZIaT_-
8HP5qFDym9ME_VOBlbPFFRtu8POivBTpY0K1nHTQWwFlvxzinHTV_10h-UqPOdrbyH5Vjqkm-UqN55Z06rzWP9SW3x7QP775r_yQzAzqShl311HVS5upnDBk
q44dllw7s5-3Tpto2o--_ZSIRMjG7R_0ukj_YDNkW3I_aSNNlo3xFGLjT_5DKG073x7lfo9qVWdzuKR_Wkmt2mOMNtmc5z3tQqEiuSNN_rc6_KWmyiGN7_Y2
lfyA2OQS-FglGVPZmUZYw_yimtuynD75rtyDiXyFSUmRN_z3p7uig66_Wjl_6fmczkE8MbJnzL-3a-VNOXPGV1qlGGRSu1VmjmVzr-1slu0JNyzhq2ZR_3H0
h-iXtkuNyPje_GjkzukuwlOlkDqluiJN_qQotSyjldC9Rl2B-QEh_iyoQtu0-QsV-4v1i1zkgkHtZkxQbOxzx1ui_4ZlJ7a8BlrWSxxwVTKxXtZf1ti6v2SE
tobuyrl-zSZijtRYEpD90sn-_Esmiz-vzloV53S_JBUmtuRYEuVukVucdb_Pm7SAJW-_YVQFBNhdMGRw660w_vrwsox58iy1XiwnwUJPA3W3FlMs-vtHcw3z
mwVw7_rEGH5LtULt3h787hzJSA_VMOF07hzp2G8VE_nEGMdhS8_VcPr-PwQTVcUwy_iR
}

