sprite $image188 [241x175/16z] {
vDe7SiCm34HHI6B18eNtFsrwifhqPd2iVHVmV19m7rFWtf01GAauG3BNIogv52gvv0Az2dDTG0fp3L98TdpjUXn6n_UeJ3D89PVy8EyZLIxPGGh988Na3YWL
1_uahaMccK8cbrHogOmpS8t_972zvxNA0H98necumFA-8dEz9B2yhuJAD9DCBWaixsjYkVDNEP1Fvdf99fTKffckHpB7R2hJJA6IIw6IIpwXjwsR8uTlQyCh
sRc-sPsA3DNkR9wP77YbBVPWQJWjFfGrl7AHzo-DpLwi7QVagxtOFETL6Q_rnVQAurIysDxIyLf2BfhjtT9cPWkhsp0GFaxiE1wD-lvlsut-8IhZWu2WIrP_
7ksH6b-lhtRhwv6XKaYmqhuTmS7gTwkoE46D1rX1V94NjF__uHUxJJpdRNGdliZhplwS6DUhgtbtl_FkjLtdo7M_4_ieaZZQjVBg-2rmTpjIzsNfgo-d0czq
jqN6SRGhvTNvUJ5t8ag_zWlwo5XrGNUkCP36nSYpeppm6XxAH_sqZomFLTSUY6VNUl5AOud-7DqvNwVoLUZarXQ8otxT52KKaWaBJfjq8k_tr_U477qNT2iY
SGch5tYpSkZk3irR-WMjbI0UsKlz45SxTAMRLgKPFW26zIbnUATSiVRw8-rjnGxUlKJbwSH7ZSOeCZ_1kOgRqBQdSUUsneR3fF2_XZiFwNlUa_kvwXQPdymX
NdyV-PLqif2GhSWUAtDs1zHYrONEJ-PDIwpjm-rwZLoGcMnpPwpCBLcAOjKTsgc9SEiVRB0JGeHAIvFtK1aYExS3wij3rNNlaWmUh_tjTUwh1R8HCcFfJBRq
x4hZhZ5NMO8uj4_FxNLS5QemsLmtPyXmYPFrMNuQCeh14fJFs8l1Ama8-R9HjI8nTUszzprSf2IpAF7nSTPGYdCswIFp8RmUGaOT7Bf7EVblkPrqtKAigFpK
rSl3nClFpQGtvu4RPBVPAI5M4ey9Rhd93FCkByTCnWI604wBR7dUGBP1aWr8FnrEd7YZFuBEehmKB79Km9j32fB1gwNK2m78cbqEWVL8PTvajDgYqvCGFccN
0myDV7GYaycF6XW9uFeIh-5TuAQ1k-xAGXfG-KdcuvZurjb1yWQQ6TvBMdKIsfCkHHDliZbTXPI9VqnDOMOl86EMGlJBHKW9FsbPTfegvLrVsZRpgPp1wExs
2Z5MMV2no9UjdLuz7cNJ_NXzeLkepJShDWiBNG1oPdG_W9F8s6JNZatgOFO3iNR3yQgRAjh3HYl7gtfOCHdP1Lbl3i19PDq7O3BLxF_HXWSnLgKxk3jlp2jD
AjbCHpRIk17OWETk8Sd6PEj2xsit_zUe9uqQJ_GFysgkfp10Xp0omIk0Co9RrRtj-ALy7Kx-u29ugVZiSIgwoQ6aKZVfXeIy0ZY5ZCcyvdKotxaxQPW_LruV
bPZiZJ1hqXEu0ZY732vIObgHpawdGVGkAiSTEklfSdFeHQBztflT9N0sbDabcFa9PDtsEu2OgAELURFRQpa9IHd12_6a52dWlCZ6PPAVjgC2kRhpUDXSPmZo
frOLSyWai3FXpG8uYmpki_ru_MTlTRjII_IcefxByzwOuPIzo49Bu0hWDBAnIeSqv_vJWMY9dPZCMxgQS62MoGQH3LuDZ6V4c3s_euSA92pKrLGpZ8FP8NT1
ZPOENWsyrF44sNoN-e3krBJpZFLNzVQX8piBGm7uq8czvVsVzY-OIJHh8SMvikvoL5TjzGcCWJ2IU6FB__86zUbZCPllWX4ghScoaXIeQoavQfBXLjjmm2Dc
_J10FiRpOZORm41ewr8-rwSdRpaY5WdzqME8BYkPdX56C0AjnVEBW6XviI8RLYphBSt7USP0avLCpsOp6CTwlPP_od5s8CDxj1wmpjqX7hDLp7LkkZNN3gxB
5dNUgfuTI7bDAvPkJOQJ3o-ArmxEQhUfn8iEP5YnL6kocZzMhSWE3ZpIbosAFjJOcbSitPfivWyz28_146b2eGMPbDQwOkajjIr42wuP7C8iOW8Ggl4EoBvY
sLlJkh2VWVCiuYfpZNGfsvEXOcnDXaEW5Tnc4IUe7lLKt70ZxVaRfpy3aoW92loO774ZyH6N5SaEZgE8gm8_9bVSIlMTpMjm6KKS5VYnEE1MWkziNeCx4EH-
CYhm4tB6pMH7xXeScG8mfc7C6cmdTznETsX5Dy2SW1e1rAB1TdB4xII7uhq3hZAPGHfi5rSOqZndynfyO2Jn2znRfwVa04FYirRq77oa_y6CaIPWwL2XFYDd
c5BSYbU39Is_Dbc1Nc0PfDZPJkwm9RWLh-J_Trewikd8_08dIAfTd61CzYbUoSVtY5OS4EbPmp6Ezyo5ZUG6Svf7yKgkP__Aa8384omePef0OnivHNEorsn-
-nqvgL8EzG8ViaZtUQ5f-U9e7XDscitVFwCD9vZaXsPCOGnnDYnUz64kC_BWQgycymbk64aPyrIHZhja_Z27lOfNvsi1hZWZOEIxfKmFuj2Abc5ToZYu0sZK
qWLEAQHkA6LZ_6Vpcao5HWt_ppl214koUUlbUwMnxhm6iYHB1wPtC1An0zbXDfl9XzpS4avmeo9_-9B9dIlv-6de05BB9pYGR3_xdufzzv66A760P8BdKJ8n
Ev0TMf6TJ2Ny11SPQHUoV_7ga2Qa5pYEbYNxpXRZOk_rgrgHdInTEVq4qxoCielzYzSUPSZn7TovFpmhhqEEizbEFdw2kGQ4jDY7CFtYuhszmKxlOARIU9Qt
3j6lArxxlAxX3JnYk1rmRaK-v0jCAUPEp6tTfEZN5Q-TV84Bv0vtDYaRsNzjVfuLEE5A7zUyPN5mT2zURt47S0nmpYUuhevHP9xD_gDhxyeunWQJcLgIYfvt
zeiMvNmVwK_kDCQPvdXVsv142_86nQl4kYsN4onVeGfGGbs87QuqN4CA4O1yS3d1LMuC5lFQlHNvZxBeCC2lvjHnxtg07BZ-PCfdM-eJp4c15TcnUFq7kQGy
XCVBMHLOYNttaVwh5yPcEiw3Of_WcjBYIxftA_8VvJIViyNnbu2JR3nPnxzu_GUvpQlSTeBx-iv-9--QV1LlnNMo090qU3_k-ZC5KiO0Pndd21G5tf6hBqGe
7pIm0axIfIZge-EUNhtrYYXKmmiyx8MuwqdzEpklVLuN83ErsiwT9X0Qwo7UStGrcG90Rwjq0X2JkiVTbAjBkG69viP3-3q2Ug7UrQi7kG2nKvRkb4TNRW7g
Yc-xujMvn2Fou4asNgIVvMuxkfei0me44dsMZQS2RpkycYpVLklhWZvrQfqxAV2smwiV3r2l_ReUGD3V5xVdhhyhHonMwTsvwyS3WBuEC1JlXeDSateaO1ZU
7SawctDr3633RDwOlDNesi_AEaRl_eDivEvFDXRl_cGZTt-oSJRlBpPozoSRlVkJZSMxlzWuklkJZTpzoLRlzhlDtRdc7v0OkVlFQwDtV_BcNFk5oD_Y_Wi
}

