sprite $image378 [191x215/16z] {
xDa7hkmW34RXWHHZazd_Sbz7qyIlyXf7CWkuzxE64pdAxO-VQbPlr5DE_tQEmjJl_kliH7qB7wTL7j_xm-zduV7xym07Z_ywm0xaztWCO9N7xo810bya0E4_
tw2suVYlFu1L4byaWE7J7gA3VrqY0G3_Vea40FpxT82p4FZVJeW40Fnc8H80yAt59862u9kroGqw67mp5ma0-3PDe2BuymJEWk2REIE1cF2d0xGDm5S9M0Nm
0Gb8law0mJSJRvC0ljWZAe2l4m3mvHx1u9jOfGbyjKe3-7ALBW2-J030rma0-FeX2k3B101ykKhl0BvCe0BuEW40NwxI0BvUfG5ylKe3-3e105_k4G2-JW30
rma0-3e105yc0E3hLHh0bmaK05-_JGBuCW40Nw_I0Bv-Y0BuSfK6yFNR982lFym0-2A1s03ysGsAwxulpDUhTFJhpk4_tw3nJr3yCS3Gy_XcpkQR1PjlWUFp
-SbFVlAV7vpR6lpa9x_0-Kz_-hBPINxoav_yv2S_-SbFVlAJV_K6vlTmzmRbN-4_JoFodxzV4ldF_eRYYm58_1vF0q3uDvjymVU_nAz_4b-RUqm6QAlpo_d3
6MA0XVc7ZnDT9B0cVsl-T48ai22_sXDH3j3MuvVppQuJM8o_Vzhr3Lg8_tpfRIjFluGQO1L-CH_dB6LlVfRHWKvW2VxNOirmsMqLYC463E25lF_htabzoOhA
PfXiEkQdslR8nwlFMYSHpFVV-pvGIEG6ekLX-pZqsRk8tpEEAnFqg7s4vVvNVBDRYa1vpZxuAzuHzYDStGoY3zcFOC5vc7My8oiHiDetDuIm7PUd-BK8sEoR
6qBnAE19Yn6ms3St197az7PG18er0dFxzeOWLNONRoOemBymLccxVGffTrK2zpPy9DWZOBTFVCIno00WYe2zHzZjH_oLHhe0YMw_ZK0mHS1k7msKS1dXUfWZ
OB2_3Cl8MdS53s2AWA5A6-sxX3xmZd04xY1ggD96-tZVYyE1ke9eT0nNGvKssUTt218_zwIqUWNH8r0435NQPXzlU3b_fEmdYDghIPV72IhUso9GLksx-T37
uTwxTFx88snUtkPFsMUwW4cFM8s0tVu-9A_V37bVG7jLKJaKZi1cZO3HlYyujHW5aTfabFUh2AGl8W0NOB4__EoumVapGIGxdY1xbVxQ_iWEz9ahZ86UH1II
7rVfTVkXK2NkGr9V3OkcodMnIkCskJv1w_P7aaIbpRRvuzLEc-d_36Vt7fpoaSjw1FBYDhbiduS-UwLDzgcZFljFXYMvGOx_i4hFxJD2ze4szODw_QjIGUwN
pn7OZH5Oj1yAeHwT2iZTASi-_twRNB4_mY-CjEp7NyfbaA-gj7MRdDfdM8ee5uCqwJ8OzQ8KoWxa-W-tIRRFGm-qUT-KfbZij25PuaRoxxT9ji_pMaAdJV4d
wkMKFxJP1ZdsAeho4VFljqcspxI8I9lyGNt434UKjOhkNUvi_VKsMTZ-EFJPZRHvLK7P9PAXYdQv05j_lKt-PJ-KyIwERLz4PN0ACbRHy-SWM-Eljqb1-t35
LCxy8LSGTOKWIZAprLwbB-sB77YgEatjfVyaEvNRkFYo35SRfCkBs-IqIhFzhkhVFy4UtjiWhBYIt2W3RLWkVWvHMTic6Q9i7o-Wjp1NMkjTG6cpkQ9BeYw-
81VVYVM-slY1QFhTDids4QsdK-YGoCKk5u-qAKrB6x0r4KIN8p2hqXVsQOBG3ZW5cHPVO6jKji9VZmpHhxP9jiyNeFY3Dsh2ChDLRnT1D9ctIRQlHuW2i0PK
0RQ230KLaJk1w6gLdcoJoFtBTe6qEPT4mSLNPIm42D59GQK8V56buQbxy0qOkPWxM7B2AffEcTXQHuZscmWGjLHfjD_Sdn40NQWqGxK4slXTgGXD3jRs4lRR
Whg-JJ94qNuF5KL0_pvKIwoYGCMUOKJk4K6bWcghqcZ_FBvG1FGn1YuHx2D4NGA8BXHKGvN6uUddDWBWaXOpPkjwGRLKwTD-au8CnmZS-tUboTM67kiN1VNh
AlqUKcbjVDDm-nJej86F9PYjntf1ZIglHc2Se5Qbml1F8z1fWzKoxwNJ1jbw06sM2YgUIPLEsvXt-JC-bTwoKGImYdvSbg1SENQ0gDjqSSVUsZDSmY3xilR1
JFghCidRFDXVY02y9emZLrf7_M91HNal2rLwtnAP9_iK0UeH0nN1qnS5LUKuxH5yazv3J_Rd4S0J5o2wpmlgs0TTljqccVj7RH_tWeZ3iqyWAiaXHEq5TPVx
RJ875yiuD_sqkDqVxX4udWpHuwGD5zHZKb1HvWzqOex-tZp-kjOZq6apG5HfWqqqAsq6kUWdCo1VLEcmvr5IzyV2zm4c4Asb84HTcXRKx0BAlOh6NaILhSI9
orzztTdjUWHEW214rMcR5zG86QvTHhRouRb9P7Gn0WnH3oriKb1Rbt7nlMJhU1YMhKo6tWBHC2ce82D46RbKUjPWkHu1F1AfYTuNL2aUPMW4nDRReO-hhkSz
0W774EsqwJ8ilYeVa-N_ErZocMwJkhZ35sIKDeEij04Pbd_ehJJq2ClrirwbixxxX0odGTOgskMRvHzFNOMbwIdGbEb06q1zfmt8LsmrmD8G0K4x-9uJP7mu
79FbtmRBvHvHvn1DSadBD6NhNKEGXQ4tFmMqXRsxW58ekojPYAt6Xh1PUWHoqHKSuxxueipBlttexH4udS8NP9GsAWDRYmU8_XAMtrTfKTGFYs-N1xPMPQkX
8TWXYea3rEFYMo_PscPp4x_nPgtIz0MPG6o5qcne2AQJhY-05rylSidMt6NZqDiZm12L-FbR3I1w18AeiI7yFWAu-6gHAVY9jJke8bXXQOy0LL7_SPcTqiRH
VlxxXc2lqc-kZ5-GsGkm5O_OOVdx7Y42g4VQj2ghwzIZ4JW8elwjo3qiBJv-toFeCo4H0omVY41_8KWGPLZoq3yVWKuRg9Q6Xl3OKo06GhtKjORmV0G0ekil
NFayroEaYc6TUZm2veRmQ8zulY4OtafRrgdd8s1f2Cz3rBXEFHy1OqDuFWB6Xl0yH4smV3u2C3S6M3xM8vfjw9-kqitI49wFGBCC_VCHQ9Q6y7m4cgKXFDyZ
_ab3-0y
}

sprite $image378 [96x108/16z] {
xPdRalEi3aHj389kCU__kdiZxCXXJdmk--eVhb9KiYZtweWvB9DhbR8jpwq8ah8-nYyAW4YFyQiI04jyZA_j13A7n_Zx2R8-nbVID3p1hwT7ADi3_0yxu1aD
nlz0qISqE5yoJXhY0tp9V423yxD8uVqQd9-pv9C6o7etFylz6fnlImODT_Dlrp3oJGDE6j9wAtzUmtN-6589T_F74sIzbM_hFQHqDzyr-0Lw4__6hexykpMC
_0aDT_B7aG6MxGg_E7z2mxrydzokuMx-g27Uoxy-kKV-h8QAM_cZXlfHdk2R1iC_nSyYxO3d-FbM_XyV_tN-7_-FNv7bGJu1b2pFy8yVF915dfa__GJQ2NVp
8-W_U4o59B3xAy_GGsvOzWFyX9lugx0j-2EuXXlu2IIA5CDwI2p32TVuMo4XCKaK-0aUqaM-1q-McFeXcISDy1EkybS1GTaAEot5Cg5XcX_HO2L0OOlCCNb8
tbMvmjyAExL48OyJ9ZHCyIruSeUcdj0UKluKKX7vDtw2UJMiGLCXS3pFg86cOPuV3PRiLMUo905_qJ37js70urSF8NX0yvi6VZ4o9lYha60fP5wNZKfaND7W
_35u4AczK9QgB9iza1s0b3oaNpGuV-maoseFKgX0wgVotpICVEyakFzU6U2_9YUszLa3Vj8mybSnTbeZb4aicf1LSqHLIjYZ8NxLO26D_6WVpw6TbAZAalR4
L96tRlvB3UbB3Sxtu4dPamU9OCUoRNSBrjjf3SwtJbh_e8ohHPDQCcj09KMeY4jI9QIGNsd8dpKuln_VJAxjX4eqmR4eLMqx26qxX_OE31g-czpiV1i6Nahm
LKg0wDkBRKkFqhlwfc4CwU3RQy06WcNGlxfhgMJfsx6dQkUAado597GDu-JU-VRQzWkgTRyLDAisTCZKR2U5rYe8AvbVNQNyfA7pgprEFm4bx4rfBe_UAX0j
lBPjGauQqab3UTVG-Q9-0ioizHCqKAGFqyHNXHUPwghr9vHTYUqp9Qr4jA_krYTSOiMsMJHMuILg7RewNg3amM-LG5NNqFjvV7LBMdf1gwB4zX97L_tsaVZb
oF3lR-8v96nMH7kxU5Unom7fNQLhE8-C7bAjgiTqqxFe75QBHg2jHJXrrHpt6PljcJzhqBWTe5gNVPqrGAcroRQ2ekqcgqzff-PWju-mjksGXybjSTbUo-VW
Zney3fB8gxt1kzegxDlm2_JKeV_J_VUBpnfeemUwTzNmHbcFVh84U_2Zgqr3JaVuZSvjkDtpkmQfBPhMrR9bwsf4PRIkfgrLEDXReXnTjTRsQ3uqETarU4YW
zgwQ1kjdltsg8WUhi1vr3hA7z8gcMdgVL-HnWdSrs4UFBeFissi1qBRTmYjuq_VrIcyXbR3alQjCYqKZcPhNnQB9K6msRc6h1wznOFwWWMf5N5Q1mgwSVllO
rxXNk6X5NshHoFBBsifxLtiFnBhQFTbszErJD6K8_YSDyDiduBXzMeGazjvcnJaQR1FqpoEZz7xQxIEmQyPch8rRZyQ2drpjywSJJ8B5OH9wQVmHlPFpoqU6
8MIruFn_WKAy1JzqybyrADDcqSIMpBhHelbk65pIi5ypLj2gvqwc2_1XSjkY6HoZ6OE_hc7_pQPE38FvbTurbAepm-2wXX-6mNKDrJLC38FB6kOxULq3_OAw
R_dadXi6rpLKx-JzAqAh1V_O4ftlvFy
}

