sprite $image15 [296x190/16z] {
xDS7Scqn20HHWP20_I_uv-3iiVtYhJvxOAePrsUxrtWFehgxOhm5i_gtyl4QMFP_QUD5MFrOZ5SmJ8_L78_1ir-IFl2e1LwpRVo1wDSyQWHQu6qr1opxVJJ2
Risc1Tx1J7drHzHac3Hfj81cqGAQ2fuKJJbFYcORBQ09XabJanRGf8_3MdrAspWvIGKjeAb92sZIQ07DPfWq5RI0ffmMqAGnJ9erxfTNNqvDMk38hqpqvMsZ
1JHnl2U5cTfzJUcqW6ORBI2fu4dHrAG5D6cqW6RH0feAdXHDEIsWIMEOD75FBK0ZhBvzwGoJPXij8AcW1JGrEJbDEYsWsRVO0ipKxljLas6wfLV6g-_UkeqM
OAQYZwAS5hZkA-FP1nEqWAOcBQ19PvWqsoxwfD08gu-k9YUdIQC5D9idHLD12sZA6IPD6YsWMRI0fe9XqgJJ0ffjMWiWnjk-iskVEHO38Go0UNt6zlslk-rL
f2NXTsAaNE0JEDFSIxsj32pKYYco8-MO8ZjINYEG7Id755fGtifSG4irJbo8sP1oJ8742yfIvOdB11ijvPWYqP3oYSkyGwr8UOr0WBn_2r3UojoHreRFMvdn
qKwrbDS87-q4bjFdc9eai3fyZga9hakvhf_fX6ADu8BuWPJwwYNb0gKhISB3jr2Kf3WCIoqLz5SHSPp5y5dggIJThuDHIEqTYafE4JSFNw6KdU8u-4BoLYQD
N7AAE3ccybeWLRvJI59xFd6XL3l5mJ6LHgvmgcAA9CJTI45QSQhN2D8uZdr8KIsdYCj_muTn9zmw5AM6KnrJcdV2RKj1wZizjp8vfculmirAWMewrJ75cGX9
O0SZbvoAIYSkqeX3Vhf1x63a6axvn0KZBhT4I19xKT8rgifR6Mh6yVJntdnRKjHYZKEKbRSouksZd-9q9oI9xIlXkvqhtP4c1s6Gaq2___EkCjNHx6tjecW-
H7lE_ciLBjifgXB6QLnqCHKwg0wPYZPoZH1-7sLU9er-VpqT2WzJ2OG9eUqhKqLcfSCJpyb48Ch47xd5z9_GjV4KaL4EJqjaF1G2eW9VJ5Rf_w1kfZg_UJ8L
QGwPYZjo65r4PdlpPAR2DMoKKUG5o04UcwboU9eiKeZA0am55APAFfGlcMeyrMnDNakse0ymVD64gP4VxP6f_l1akgHH1OrBG67oWn-PgbCsJvik4Y867Y5U
IF6ZF39Lnk5fn6bSx88N01vXC0yzF8769SZ8zGllrDmoHUtm11gN45vW4e13flOCqk3--pIueV6yG240dqpne46rD7e06fUuNi0lKpJgubegA8OJU04WKurA
4owjq0PeNE9w0N-KQKIrJsO2CXMtiFIZp2VqKPsD3a3Z4h6mzAEzPQeKt-RnVPRkUm7Sk4W3cyTH2ilxCbN_OVFOD9KNm1vX5h1vdCOBO9a2cyVX2qi_-CWK
s3oENbZwKRvb2Zokdy4Bu2XJmEPn5c72KOR1vd4IBu0z0dXSFqXXUJ_AuCVrunUMVjG97jTFuWKmmEPnaCBoFlvffGym5Ioa-D7Xham-Bt3Ws2gAMrZwKPOP
bgduXQKVUFDOKtW1Z067x_hXPGomGAPIU06CWZUFKtW1Z0vbAeSNmC0U8O4N0BZpWWJi1OAYOPcwLbX6bAdV__hzyEao_O73ot1HPjMffj4Bo_jHPZ5LEKpT
txO86sM4YQWlCqtW1HoDopCkF9RfnS8olaoTE_cHgNk7by6ZZ4u-9rjgUY-an9SfxUS0VfbgN66wtxYiTWxWrVHsI0dTk4ZvdKmv3Y_Z0xphJGT_1nszLrZ6
RrnMVm-VVX5bTiaBn6zSdZiyxmzN2yluZOkKmrC2B-1fN7Gmh_tndXU8txZO8rEwTFDa2Ro0lt7HPJzGMCPhNDJZ1R94cJDtzmlB-8sBcgEmp1DbB8KNy3Sk
BpE75yWaKycz06vSZeux2ij4KKRDStYPfd6nZp3XA7Dq_EC5K9HvgAe4y94fUzcW3s3ZydfLGlYWso_Xlty3
}

sprite $image15 [148x95/16z] {
pPY9RciX34JD3ZFa_t_tDUXsjUWJQi3tQ6kqZk8pEAxybL2parlXItiZodrmkQ6zWHha9iIHQ83YvGQ4YlO9Md8t6DiFK8srIWrDWHhinwR9pgh_Q3FGahb8
bWFK_P-3uar5CjPAYpG7XzQDK_qtroggiHbhDSQs2ePM1lstqag9PAgLxlywnHkAD5ytPlsVWngFB1A3Ts59f5FhHlVVNgi5aSwy2tfirbhf_XjfjIxIkNMZ
-s-jbHR9N2jN3YHIH_DI_-srYcfi1bejzD_YNN1PZUsCLcRzduCQb_jlyoveaUorAcfizbhHF99-5q2Loboh1XgdqaSp0DY6qki67A5kfHMeKfbh1Ju1RgDL
SfTFv7sqgf6yGl4sNrLFGoVSPu3iNIJpIdN93fWcUZmpYQzt6I2UYKOcaT289xRl0lWOaRh8u4Chy9BBPco3ppFgKwiMMYSCnlOZquTM09j8H2SC4Ws-_omd
haoZZiJXiGqU3_d6q8hDXu_lxNIY_c1Irpd9vjtusv_G2jyJzU94yGnI_FWhxDSAV7mRM_EJQy_7cfs8H_KkinEdH4AGEIxN91wz1k-6LaV6bkHtVAanisGc
buPMknCzj4YQK4kAgJDvIQ_N2kmJaNudrHmgenzrxCG-aHX5CzSgnH2UmjTEx18fomgXb1X2zFB2TOF-lV_LooAn5k_Zy2-3nC7-pt6f9Y-3Hlur5IQBP97n
BdmSg2IsBP95hMfGH_E6HRAkbJgQD_L_vLt8ZOHATQJ_SwscH_Dw_vsyY946XBgv3lH_HfmSpSi_95zAfafrglzpVFsH2kVwFoUqAyrSgxb8KJQWZkQHwbZ_
vxYVMW7JHFF-xzMgXKhyPsmjo4v-_Y-6RTpGAujakrP46Xyn5yd98LmPpGF95fuV0TN_oG_90rg1utOE5TiMoVgw0OZin87OjaZMrmr8H0VsXKMoMwkHgW7a
-YBPk6wkXJFhlvLM1AaMYHNkKwk5HNBeNI0d_JVKYbJzjoM1fEg_CQxq97_b7m
}

