sprite $image98 [294x226/16z] {
xD110G0010F02FgtfGMu-yCM0000000s00000005000000000AO2041F093jdDiIspOCH46080dA-l_VxOYJx1WkhB3tIk9vQPCy-Oon9fQohTM3nRcbKkgl
M9uiazJ1ujGIKQw3nQabIbe7YpDBH5pgO75cYNx6q-BK4gLSOvOdKoAGuh5Rdamb4G6k0SkJPKhEKn1FIvC94J4J24u5ovCDGQmSnDFYmnA7OxVui4GkdlpI
iZmPPoi_WeabZgVboUorxusP1i8qy4lBycIzlVOTuHt6qyAwzdqt9e8d-eYdHJiilVRA15OyVT3wPbRxLfW9h7ZosBPj9bbn-6PQyVH1smwCYM2fvpLsdyCs
iCR34YOjXMENoYD3U_k1iMZ2Uqc8Uuh7ZXyPIB14bBCm7QWG5QXvzDA2OOCbIYL3J2FIzlHuyewGtehJj_4mHO-E9zk0_umJJH2ZH2K_yrG0Hx4bIlcd6Eb4
MfyQJnWsRwa8CGyRAZH8HCe8yYV54nnvh8vAW8byirigKTF7BIssXLYtr_uIViyal9yIWKV4K-jRZ8tcfCBIMpoH3MDnfvBoGnp1qcjl_kEUQP2OFEBZwG73
1akblqpOsz14CNvfkRiZOBcsJCpa6MC7gjuwdk9XYyzBdgH2GFJ6LQPt56CrmvA72vFZhakBRR_4E1KEB4NnTCknQzi4neSDPGh9cMOyvRiEcy-bh0I2U08t
YYUKaVEMMBxRqDl64npDMkApiCwtYoS_RFEMJiFwRl44H_EMn9IO4TRFY2VR_X3MNiUoox-qeMacdhZSpX6QaptpH5WhJSNJdORDDoUDPy9QyzJOvNivYfkJ
EAp7mANhBoss_HdCIdzLOJeeNyDQz1QTYdyZpMDI2cx0BNyBwsmj4wVvfKNkuGYMtfeJ_HhMsSngJfS-5TZsfx4iwQUbr0MlzYEiintmXPSMs_u2neSKPfSj
fIGKu86b-KxbuiFcDnJ9JEyqhGeRaQNvfUNIZe1LmKi3PashQvXITPQk5K-s_LMENnH8mvEpPAOVDgGPB26Uhh2qjEslWs-blb-s5LXwjv6DhrNvOjZ-kgL1
4tymhB3qRYFzeKw5tiXN7JPO6bZbzxU0YEYa3UMvUBgm8rWQyUHU6YnTjbEP7xPvIuWd_cC5U7otK3Y8foiwWYLWBJWLd8Irvgzlj6eb1MDtjM639OSL3Zp5
ySH7BuL_gVnXoIn7Iyj5FlrZIy0KyNGUrjpxQzyLpaJJXwKcqSFrLnisMF8qnDDfMESkVT_DNGHxIrN-WzCJhYB_8KiWMbgGGmZhrBblpXAb8Z3sPYdumOBB
159i2QU2o5CgbGbXNQLlB_4Q1GCfiCHHF5ras60fnfGGJu2jl7SgfIjvb0Zn95c53cgDJWLNSWHBK_74PatBoGgd_dCm_Ooeae9EvHB3vYrDnPEOMLKVrX1o
w5CwKCGJWjmaMbekuYYs52qjoEIguTAYsxxtdvP8bBsbgl7ISe5XExKKBotMgaPBI-fjs_UYcBkiAR0KnDC573bB8UOx5Kv94JblySIT-sit9PPXoTqj55YA
7gx_VmxRlALuQM4wgCKlBJOEJzgEkPEFfrTJmpim_HCFrxV-tpawNrfOYU19Y5HxtyIEfQK4Dor9QS1PedYwlgEuKoaVySIvPkAkxRLl9pSjMdjDGJnTTzXE
EnMjz8uKEZ2jsxwVtBIeMPKSdGekx6Y-K-4HrggrO-88yUGicMby4NpPOPllL7XqAggzCJ5vfAJ0Kj2fNDkHNrgOGqj4eWN_xqYQOGAM0a_vWiCstwd0Z6Pd
AUfKfFsqbFaln5FxdphodSeNIqa5bZo2U5AbGIaj1V5qvM4xxrHWQOHrQ0bB2p0pbUXKO5jlfux-XyCsL_aoYHAf2-iedhmbonp4q_56iQi5aiTV10EnVJTI
Ef2SAOQBU4lAmKLmDtYwsh2TToffNAYeubGW52E-Ar0EBeAx3KszNTTHlBHmbz498ADcBeAbmP8Rksu6JvSSjhXJmOMAKZ4cddwuNhrB5bZwuSckyEa_lxIe
zFxIiktxYpbSTUEb9P5369RWwNh35YyjJCJQ2wNUt2-4diTJZ2HOmjXTs96F9nvMkjQNwmGuif7q_F4m0_1qkK2AbvPXWvhMlh_u5z-4IbXQOhJ-pjD57SNn
fANrph0KnnDRIPJ4nPE3IPgziLtUaUzKb4icx74fuTTbl2MpJF8zdfWeQJDmVKb-QV7DYLeKriEIDVuXC8UMYCJ0JHpvJWMMg138sLio9NGgeIKsS1D7lbE1
9MrX0GvBlbCvjtHzH_vKm89Yij6W3dzOMX8i1PrAPEbMal1mVHPoLBFiugd0KjYfIBNYBDt7aUzKcA9dB15FN4s_BYsoZQjF0xTov3kLv2rPyV4a_7LfQMty
wg61UqdoIujuIphzS7shslUz6BYR8tyHpFYmXwMPJaM7fMpWTexYY-04IrETIgkz2nkueIE_j6HuqSblGab9SaXa0pUK1AgFfpJxJQYa6foNxkV8Boqv_T5V
byagpj9j7I6UOa_dLIOJAxE1kpe2fXYxY5I-FfbH3TnLqlntVqJJH7DoQqVdyPGOIyjv9t1tHrXQ8azY9I6UJYtTNrAyjA3PZPOMvfASfKSumj82Jx1aDOYd
Dgu-3Jp4KTofC9PWlxJKtlTzOmFFS1G_lGfBy2Gqi7fSfAk1fqYAuoarM7gFfn8q9yzm57SgsPh-Vcb9XwNA1fxaA5vQX6Y8IM_nL6fXOWFFaHJ74p1vM-w2
yzAJ7FcbHGYax1icR-bvZkAb9NLvrvJLMNgWetXfyMVlCNO6dYhfl5FXaUS6dkhel5C9qlk9ZlpIadd2qZCbnHV1iQMdEZhlL9Z4MNgwexXJgQzzIspWuOxY
RmINlksxiO4bALXQ-cXEie7bA8Yd6ZOdon7YQPmAvB3KnS1o57KgjPiI6rYIWdZAyNbfEV9BYsLlQJcAEfNU6pjBIrAmj9XPhs9WEGgmWzuDX8uMvfbnj3JD
I5gUPXmjJpEEbgOPISlJZAFbQSRHyZJZQ6dw7qZw3G
}

