sprite $image166 [135x312/16z] {
n9G9hjj034E1Ph55KixzRrjZJ3HxfksVMEy43wIeoq-9bKirOKebvlW3QgCe5uadYYJAHPPuHtaKPYcGg0i4qQSy2eDo2NCibp15H_5CUHG6vHAcNi8K7SKp
vL4O39Ee3OHXAaMMCAKYCPXbW4HD87DyX_8ep5mkOGOypTr4bjY3yYZCiLp2T2IgHM9tK2vXbje-hZoDj8hAA9vFv70yHp7BvTTXvJX7CSrYYcAuMfoY62XN
ZJEg9J8FAo3g99XfZJEvYUolGwKrLj0yA8Bxzs4Dnq4c90W54jOu15UKf435FZ3DLUEqnS642777ACnbcWuhCrV4b0F1RXBM877obP8fEH1yUQJF6cGSNGkb
r0eauCiZVTOWv-DqrKWcA09VxkDPGvg2ZTm28IHm9uchHgR0nq0W31zfJuCRrl1eeD57qTT8NlVYqGZas3wwfJ19D15POvkkC72a_JIK92tYDBOBeORsqI-b
SMrcciVyToXDNoDR6Ya78cl8fuen4lqqScaQ5g7ODEXJfG93Hjel9NDBWHQPDmtHpM38KVINqg98oO4GIOeJKfGe0YFww2-bYUZQpAOHcs3hPin8-qjnCnQn
nZHdUhqOq4TNmu5SJyGQKoPR8AH6zD7NuEE9WDP8toe6Ipnhw2hoctVpK78SPvhWhGm9L5Rh_T_sDwCE0XI6drMVlsCOvgAocjYEc4aHjyGOjyGlIR4snP5c
_AQ84iCEZ2nzGOhhfeJjio8613umJDuIlvF7EZVoxJ4dCnJ1YU70MPhlGApV53AANnK1s-EMo3VoM4DvcG7oeGW9ukb0ldCKQrFo55P5ub1a8f6-0x4s9Olo
ZnL95eEMadxbDFATYo8Hd1N9FzuWxVdOKuflONo2-4AHyKVVVduF7F5bZ7Cogo9d3Zt-VvNuw0KObugioRmNcj_4C044Qp8NynsqtR-FuHpc9v3h-Txtv_t-
TOpH5FjQaL7UF8gYK6OT7BvI903phC28M7IuLWImwO-AK8BVTBXwPWFjKU36MjJhycA3qNv_F7jyjodhBB-UxtPsfZdYoqrPP_drV3SOW0ACfQZZdMjvgp3M
ebuhaZnb6FnpHGouC9JuvqK5781T5ygQmZhVfqEfmLXJk9hlnQ6iHLtdUpt6TGgh8ZOkn5YBkZwhmyXhpqKAYpPbYhunV57KLPiQ31FdezS_BgzV9Q58SNPW
Q_-il561qNJsOkkjNIbI-4sHMf-FVjDTM_zTaQWhhA0tZQDds_NS-w-Ak6oOIu06Y1tiRTzs_QP8wMa0HpBOTdjksfxzLDHY321UXhCYRN_sVTTl5x6YmaAy
NkP3aTxRjktBBAyCnQ_N2nlrDhMpxVkkPRxNOVnmc8XPaVXHP9tlbKs12E8LFYTZiru1eh8fW5-VYjXXrbbUrvJyroi8dykxN07otoLDEJZirwB8-JzjQhuf
HrCWpAf8U3wx-gOO8DwAw5T5WFgcl9oc1lwSxnnHK3Q-F3Kb5Ldd-u9Ht1JyZnG9i4kRucmAgGXypFU1KTKKPrFEYdoKDmen0CShpat9g7nEnebHt9G0V5Ba
TLPamQXkob0ao6HgCTQcv31T52d4yDoK-3c6LP78P0enbgQiYk19aQZQzaWNJNanJv5CfWm32GVEQDQcGBmIJeqZbFZwVaEQckBNMH6EZCZBsVSn800apKrP
XocEO1EWllSQZ0IvR8hVptZyjMCXwZ10mhytXLI4zeD19SQYoDeK04ignbWLUHt3DE6W4CCU85meaiT1OIXsJ20NmpHuzjhJm16U5JarvL3aMTyKEtoXoD_Q
58VZGn5IaVgc-6DdpgA80KySXQ5uWCp9_DrDIK5NHSvDURIYfY0YB_--KEJKbAscAUfzyS9XdnI1Z8RUQfeYUfS-t-uu9LFV506z2yx948iYfKqHW184NofI
sfJ40At9h8gOnvuf5M4mAN9PNjZ-sceKfGD8KpBNvHKgQWeeFzxNYZ10gfe28Db8buh4h4XDKr8CtY0QoVYol3MXP5Cm_FFo9aeLHYQpWh2E-WgCqLYwG41_
jdzKNbDIsB77KHSIxNvlLueKOLXIQs9Iv0VZGf40R7yV0w7UsgoVdlTsfGWGK8013wdlVLQazQlvNeKXyQUR8naRvIaiyxqMOrC02U9N67Muc29r65a6qHeu
7356mpBVwp0UsK7_AE88Hq0NmEboveXQDsp0cOp3ZaCHpOgusWqRtmIzDH6Pp78NgNV3zcFRGRsDP4I2ZFAMkn5kk-um5370b4mT1hCRjluSYiGOdgTamXKO
33Vku9s0dEyHi884hdNZlksGSrkqZWV5A6_DXtvnmpb5vYyldCUg2p0MD-OfCYCOaTVLehbXW-yutR1nQwd8m3XEf013SBZHyDiDX_Vd8yixMPhbBIYiZhda
VN8Zh1jxdvF9-QuA36W9OipiXc5xEEVxAOyIDsv24lX1kc63MxFRqyxvFfAfmkW62Tz-tB01s_lpYHq189rkYIKOEPybdTte_--63U1KfB0fvDZ0alG77rD4
FsxOu7rdBc-D6uc1fCcDdcxOU7zuBc-L6pPuCnB3ZGtR0JZKl8pL4ZTit_OEwP-3sOrCQe2KkU7eswwTd29sTBQ7dMwakT1QqPKutR0j_H4vHVg76pOfSgkO
eiEDtUQ60Gdlp_tiHbeZTPMxOKTogArks5YeO3qxkT7-turZcoBQsmtURkIhQp0ypGtpuyQO8lpkXchdHaitiC4I4h-v8ShSiF6joNOSuwjdUMStoZ2EmHdx
v8P3-mqboE66NOC1qo-PFhdXsDcU846z6t2N95OtiBV7czFbRkJIIPhTyDiDMtbUYLRe1hl28B7zk66JNvWRSepsLheXaIq0zPCRtjYUcSJOAvHXt9bkNpUC
Jsxa-4gJiL3jqab8cjoGtLE9zhJV81PKkP7ZQznwi4zk64UwAb7fXkEvxMYIyJcvWTCV5Re1GBWttKW9Z9qty-NQqmkcwBfOoC6vSNPZ4hbYYWutX3kH0wiz
XnjX73d2gjtmOrewOV5WU_hiXbtIb61se-swCHoOVzVsoCSr6Fw7IoTfSQCibDMD79mxIDIx0JaQlIuam-rvp_AUt2Z200bMDyBSsHkIJcxKXOB4uiOnlf1m
lHlyoQklxzZjSAFjTj-EywfrOooTzBEG93ml97Ff12BLACFmCJZtT6Ci9DkOu5IxCQM-BYHpV6qf41RKNdkGr0XZ6xUMRc1xVpZBQrKldPxJqYd6Gd9QEfLU
Uux5mjRoBOiRP72gk_QqV4LetxNbsIzkfBaWTLLTUxADZANJSCDlDsnJj-s1-rX8slTfwRHTB9sgtHXB9uJwwePDsRMdpGl9ZJ3auREwuHeCQtRZO-cajlss
TAh1cDtWVYmM-cdfr4lT22yBoR5qsc5PEbLX88d9ZR5qQZVo2Z2xKNSQabZTS3Is1s_CUZSWpzxxXnlpqgdU3IV8if1i63ifYzqGJWxQZnkU5fATPUbKXz4D
hq3Iif1yv2cqQUb4aHjtGxnUHbAwiIwTZ5IAuRlDotvpV2maStmTIwSIDo8C9an4sCC177suKRrqYd2M829_QdsISPlSK8uD8VKA30aW7672RqLOt9Z7L-yL
eKYGeKGuWXoSJwKRkLZ8WoaB1Ib3oJC99Fgsk66NOe2KeOHDf29FjeSFDwXREiKyHUtZJFmoIAnkK8XX24iSeOG3MzBiXasb6tuONkyS9b4pcVgbKpR5Dx-h
2f9Jr20SMTwJ6tKO-s45aiXGvf_c7cwuBXG7fwew7F5-IGwuSZTI_8-gPYYEumch6_ucHjv4iwgHLNMAEkOgwKOL1fohwdTLCvIfl01KOGZulQefQkIJ1B6e
mJ2CgZfyLFK7oOx0-QGKmq16asSIewhlKAOd4Yx1Q8RNKLNFLPtBUooTUfIuSJDJLVrHrNY7ul63bxqLOEIL-BggDWxFFqBrVJS0-wXgp5LrsDX8xpU-HS4L
Yh9UYTUgvfF4KCbfI02lKrKvGXbFIZ6kgvgYZYVZ2bqJoaLLNv_VMN0f1Xd_vNVM-GI-Y_7Nm1XNOeYmix2Zl9xA2r_5k3_wX648arKrQrNj20-4xs7Sxq-H
67Sp5TEZgfQ8boDXZcd-JOpxVPVt3hvvhghNgkQJVFktCUwFntqJRZul5i8VvJs-AJQOxs8aIiT1Ml6JW_pAaXvLhHdc0oCTuPzMTSAGIZ2wcAjgaCXGfgew
CVW-ndFleDwdgeQpl8UeaUK5N82nTG2IOwsgNuvyuhSqu2zZF7O1d40o5DQgUanp-EQrvt-BEm-qHu4OXlApWJ2sZEv_sYqKpKvwgE_B0TuNHy9CMfDSIEH9
L8kLUCCM1KcsLdfOIaLKTPDGr9VPPaFXIDMP2qr61mlcnKgi5jr8WvangoX45DLhrMAAgeO2R5JcO46R734y9397jQkhdwJhBBPiKV0Ey_d_wJ1v94V_J-Ed
hbkFlX_xVSCMvICQdpH28aDKKrt_T3kin7o6_V-lS3cytjJTzYinNm0BG2QZ22BSYl1kKEPyWsMDm9oPY2cy6FjzRM3vdaZI24SHterMOl0ZMfT6G2qIK7sj
MudvCHsaWLba6eeE5XQknFo6ogKH62UpoKhCRscp1ZIP-Ju5WKKjoWKOxbfatS425nAMGwD-NzgYN4w5h369B5o9kOxUfG5DvliMvMeyQuHB1DzeS1DC6df2
lbc9kHKeivj5Fj7WXdWeknBvg4MvCQRGp5jYTxccDnhSWL1ezFUVbvSQFNSXGPV_VpIlDS3T25UJkTjm2l1CWxi23ysb7Ux3pH4uJ4AuvcA_1gwUsiFcaUar
b-jySbPgy21ikiBO8mqUY8sztahZS0bvZDrHQl1mXYQ_51eyXV55AWsUXfiqZ2U2KQC9dapzJuDh-GC
}

