sprite $image179 [461x279/16z] {
x9e5RhGn50F3y7xe_KzRXco_JHdYQEOA8yMoNowMf5zpeGoCAhVHYShjTE9ItoOgzzI9IdsTgDJNYSlTRQ9INoSgzNMYKjycBdVNYKfzdQZKrubBVPket54d
AlLreXAbk5nFAIhHYSgwXKvSbkZT3JuMSPkez6uWw-f4PGtk55z5THAMqHq9JL0dBfCxJvApoGlx59OXrrP6jKL99ohRKrZwPdSaoUWaB0TlsHuP3Bie4ftK
aI4VxOJgLQEJEXAQFISFR-tgqKbO3dMas1d69pY8H2Tr9DkHOtGAs6IxYztc5B7ef8wCw4OdTQJOg_GekF1HH-RHkVnRotRNxAsKfOzZr15VxKt8BdpKaJbT
R-6ZZinf0ZM5xUxDb2MEOzIH-NOd5fsupE-k8szQ-DglsgIET7i_oiSnwiX62nzrP6J5unXr97LxFniTnwWZSuhUbqpgo9oiLbC8I_tZ67L4xJZ6Lu8vQnx7
-DdyLlGNFhuI754-Zl6LOFs5Z-sksC-HzOvZr94vQoryV2LOyJZ6TkUR_GPyVxzYx-mM6zT181nXIKQoy_wFs_-MXiWnpYQpSWstv-ocgoy2mumfmDaCY8x4
CRSI75eSytO4BuwvbK26RlGMCQMKcSkE9tpUZiZ_OqZ5VOjZRYMGrAUvxquSSoj1Uej8HB-WZjKU7ThVtKgGmrCCGNZxkxSZJEeMxrOSSoj1X0yLjk-6SYk1
gVebmACFH1npAm47kSMxdl2vbQ2Gci1tBevvEuBFiFW9dxSZwXRtBOxvx0xVZk1Bfri9IZGOWa1H1aFfT6SpkbZYxUzk9HY3kiLx5SUy7M7LZknL77ChWNrs
XnV7o2oEkRFPtew8E3RqAuwvipaQR_5s_7Xnp9tD76G2ltjnpBSIv0srh_GkZhcpMMxn0SGnTpRhRdJNufXl9R2BOsv_hzqiIRk_6yqkZdt6DFNvegMz7KdV
prqkZatJLE5BqXxOZd3u-H6yT4xlKI7joFs2LCWhzTJjxm9JS7Qm9CtMZiZ_8cNxyEBO93JxA9RsTYIVBcEezU3YsFGJjOjsn5uifMFv-ZzzmYSm5KwhbG3V
ZcYpoTTFnBuRIb2QS6PiEsAffr5XFx0uDYcQLfRq_5n6RAcdumzttmqb72quvMlvXAHc5CVAHJrbHC7iltGAJ3lEay1yyfS_6Ulf5zdYkw44fW6dm0HSXMAi
f_6NYyJ5iMaJpMZiqL4TInQmRdyNc3QS5qOvOhJVN7sHLC5qSMmRJYbP-1kXntjIC7qtb05dkGhLDmCDEMDZRqKqF8lXjh_7lLrEELUe-jyUx-MruGNduP3s
T-FTLFy2FQ05ZVSi1RFauS3YcELg2ZPawIpj3mgVrw6PasD0YcDX9xbs2MPbOEaiGoC5358m5KWwNGNnuSGnozMKo05tMaowEEVMjuWJdTf11vpmcQkcb4wG
fPMhX1JCGJtj_8eXiogrnnF7rhlDHj-CDvk7Y_jMShoyXudnBlXn1wMpN8Vk6V1B2KIFbgST0NbpHHJdGubZbacGHCOzQEXJovKldtOeZiikU2bk6ReRgd-S
wcYn4pu-VOO6kMxioqBuGEBOfijP1cpfFEa8CLji9v9wHv3zVPUvbWEkHwzHWomcOvzyvTBHn35xhiMNpXoa_oZM5L7fzmEHYsFbDiu8tkuoP3Qxu8L_u8EA
O_PSYv_myHONF5EByT4cV9CP9ruSap2q8u1yqQyu9Z2DfTCiZi5Ty0bGoG6xeI0qDKxiXC_UZWJ5-5ZsTu7PPUcqjICaT-CzakgQEjqDXTUipU8OrhMdCwoE
oBKUrVuk1E-Vy9NdiWoBixjsK2Vszz81pVucVF5sEnBYLqVA4LJA0U8Om5UB4ySqEEA58SmmDb96FApzNN3sAuwnjHrX0Cs-nJ71sRaufjDQNjJFojxjx_ZB
MGZVTHQw_TwXO0P7tdlfrE8OD9-DJTORlrXUEbM7W6iBnbLxPPIRYOz27PREhiKnLJ3RpMS5XrJiVUTQlFqzyzBdP63vNapo4cbdEF7Y6DVA2sbsQ6NWnEWE
HIByWJPbA0YJT5nAmQJkwb3GxSbsSGnFinlx-tWrCk3OAjjCeBIh3y1BvtRjASIHto8DAidh2NA6zYKwyevmuiKnQN1rXDnAk-_40LCfYJzOEcC1NmNADuut
n15NB7KCt07DhiMnJ1SaKrazteHuXlrRfHCtuIjZYaGqfCoB8aPCRn73qwfdDf3yCnC-hX9m-nTVFUuEw0ph4xw7F1gbvgoDdk1FCeMBO_SVRroQd2P0EwBY
RubZ35UXykAJIdY2WDcAG35bvYBfZCT4z5Cwfxa3FsQNzdTzl7m3zVEB9QMHLqwjpkTpLnk-QbUbasajiTFZOCOR7EjqCpwlvVaiC7t2T_DuRptbqjFQaI6N
QJq-CknPmToVE4Ry_699f65g0ld1eqG1QOkF3Bi8qyKnETxycKlBCcvwb3T48gHniiSdIWtJnJ5zlEaxtGwB1LLOydlyUpj2SYLjSLw6wVRt9DTUh1jK6YY5
SicaHhht5KlATH5QbVX9hFCyByDq-_keUbbPqyzwewdKotZVKamc8yag8JWb332FAOun2IRDbzwYzR5qtvjZyR9ELWj7YMbUX-dYs1YaYTL5j85Ie51AQJ3k
WTBVHhQJ59m6c6v_pxmwdmcfw1LWwG9Ijbi9g34McEVvFA_YdBV2T75CRt4djUNhYui2dutjI2mDakzetc5QSMw7wU9Ok_b8UdnBAr-j-3kVD4aApDLSEuDW
uiMnNFz7NCdKfu4jxSZ0RP82quJJpDBjx_REbBUr8wasIMgOnbox7QMBOy8aDDQ6sxNkaEeoIO5fnWa2X1V74iPjdguoPxQs8s5S9QbXJdKbZ0ViufYEg3_b
Yv6j7I43Ie4fyNYQRd-NcK_KhQQbM1AlaXIO29p-vjZ56qHbM8SPhIWrpEVdMdzpBAfvxUrFp4sKGd8DffVEaB5lJyOLhJkCTfG24v9hVJTK9jDdbQ61Sbv5
AKU0mEcxeUHNmr7abNOarIqerGa0SgtRtytMstY1SWMa1Efo-cueUrqb4qeX2SRfufZzYJUm5UNA2G1mkZYsKYoDA3UUW4_uy6y23lKEb5tbMXV72brbs7dU
GXAFqoTyzdPa0yg_Npgd_iKnFRih1fJ_V0HUEX5ZllH8b5uwyUAOpFgf2ae3oGvn-cweT39UIuqIdslT_cwq4XGBodvnkZWc8-5aGed7wHE-xQ_DymhBHvo0
utpcX2_Bfc4poYvphOjZJ2TRYWMOKbqSUzIID7u-IWa3pMELplAWTaIdM0DAF4qNn-nRl28AfOG9fa_ujblqyWsMo2EeS9hxtmsbx_Y8lPOIHfWkZjdtlXJq
jPImm7Jxktr96jL5bkWZg9jWUkcKTaIp15zB2JjC_KwdYsD9lPS0lPRjsCnIVhWZYsDwILfSIh7_umJiBD4mknJ7cFfYAR69POSmyRyu9PwQBFjObsLdsHzC
l3ZssjwT83aEWr00dVPkaChtF-tiE_8mJHGYgF-ly0gf8c9OFxGjIp3BuJ3zN_ZapEQvRNa5i1m0qxCvfizidYYaPGZC_ejJPFNgbbS0om2OVMT3wGiEpf2M
0J3xBqvHLyWS8ItZOFP_uRjV_xmsBAy0bZ4m-tyvjXtdSNoZ59b2MWR0x7zrwg68bW4m-pV7zEp2yXhSagjYcVRgr38FOqaEbl5dG-c7RB0Zjes9gtDbPYOk
i8pI75CAapw7OrYomJBn2vyiJD5D2d1T6YnpDiTaONuBbs17h6wPl3accvWl_wCRELWcR8w9xEB_6G6EM8DbyXU-Rs61IOIoZFapPMAcHc0PSZQKmFJb9ByZ
DlyBtyfqaw4egTnPWdDxavWourYoOechKs3A35QMTilyBtmw9er0oVzfYQjpUisy7K9PFgCvHkpCAIttQJfwb2MkpiL_u4xhyz3brCfIjyJLEHtEiytkldZP
jBBKBS59p0wSWb8-BqxxesM9izPpk9doUUXye2mVQuunEt1AolQp_thUbwLkYRFMQomeDN9-kp7b-5msKOAJsO6JxdA8VoTDEx6nB75rEim5fNzb5ntphLei
eScLHNfpldlYIJ5GWfDBbPWwPqT9UNNEP2XBS5AfLM1svNp_ICstmq09JYhAQkz7EIsxDxPYi8GcrnzvolO2CcHVs409JlxZ2_BUd6I9lZW5KIrhtzqYH9wK
u9IOjkBy5i5efzGj4HNJmDarPafmIao5qvLIjqHKJBkcFoMYOTev_IaH3TEVirIp9TB4xBCqpvyI4PYNY8ycTwE4fXZJwiOfAUsMo6-OAhhCO9J8TqpZg-vW
b0YBhIvUnLcg0oNYmCaPAC4fAVqj4Ux5MMeEIXGdPw44Pqb22KukDIubDALaV4fmbYIKuEHI0r92anN9K9JW59AHAS6PJ1ASN4hDGGdDMjDGWZCH9JWJIO8p
4IKq4r62Cv4aE1D9WZCH9JGJIO8paIGu4qb2Cv4aE5yg-Ga
}

