sprite $image214 [277x262/16z] {
xDW70gD034FHxOja3zp_j5j89htJRD2_WLygwh87W9sw8C4vYpAYZzxLbErKp4jtJ2Xcf9ToZY8Kyv86HIX24OfGX28KeGX5A2K5Yb248XIX24KeGW40ePn5
0BTPX48JoZ4ZhxPjeTpSjeLYNeGY5A48HIX24OfGX28KeUG8h2YaK7Rn10Kcb3uZsQCuwKKezLo2vgGTRnPAPJcxMIZrue4e0D2k2QKCHcdHHw4ythQ5ObQt
RQ4CsBQJe_28iee_lK8HYb248XIX24KeGX6AK81wiK4ektX48IYKFZEIPdwsRGkbLt6ZbIAKHzksKEh5cq8HYa4e5pNudr1EGqqeLoILHIYug1CARhHn5DoE
6qR1tRXL53oAcqJ1ixWv5EA5-0fAMGjAYzUYRmS5hqVV1WhUotm8Ifi21Mz7ymcsxK0HdpN1jXqb3EZJRHjdstQuC2n-ECxjjsql0L68mJKVRjjapAzQmoWD
d753rM2qLeE2CUCgK31s-L4mHRbHC5LvKJ1Xp8c2YKk8WkdBXaBC4JEXD9WfCWjAYnbZ3XJC73qy2kQF5Xi5oqIFYuBbeiT4mR8HyL0Ge2OM2e8K2CKGfo0e
Fn2h22W8LxCq2X6nHL4GjiLG43akWeBepO-23CsBWYpDXu94pOH2P8gpe21Rd1m56UEaA4WQEHaAaRUzYaZECnyT1VcZbIAI6omYkTb4KwDO6apJttRE1MTn
70Z27R-xRUFxdtOVHY1YL20HPIRkv3l1wbEbgfDX_sJ9pMg5Ty8H_IqfKewf92n4vFcla6izPB-cXPR0pYIEngO_VyCTz5OBtOqnHEJJ0NwTS9mLzaHa4tiJ
3l0xbeDSz8x8H8wHsPdufvHqZdohXU2PsTd4YToVUFLvSEptlh04vhWOG-JsZycJOoZ1M1iva74kxX-J9uV_b_9awJzIC4J6fzrZqfdWnIzv7nqH6MSNjy-v
DZ39kx0X2lUIyVl6f3F9vu54z2WPjyEvDZ25aljrctPhav7ZAS7pxFPICZBJ1sdlTjZXdwImJd1Claj9h18Sa-zIRgfZWb6k19zhlqbXxJ71d519hj-0IlJ7
17DY9HYWv6mx_5cAd3KcM0fVCHcb25ynwO1RxLJd6fR2LqoUd499hX0iXQ-Oh3Yn4anZldPuHAwOl9D5hXqUoK7aYicQagqD8jSEhxOdMsDiUcgvOd9hNSf_
E7vOkM9obz898YVQOQna9SNOA7Bo9wUsKSgzMgwOl4hfU9Oh9gCKC_qyRoXO80LMY_vphM4f7PT4JhV3GChqrI8R2XP9WTMYFoPO2gmM_JkCfOmu5Zd13YCf
22-YFIO00L90jQYF2PO2Bd-jvngMWglb53kCfU1gqR_3M0gUP_qnmL9mjIWlM2m5urbKx_1dATO3BK54UqombCmELuloc60fEKSBvZc9AFXiyfEKaYNWUTPu
hdsNqbeh-1aA8bfs62FcJKgtaZvTBVhEjUzIk3KW1NnKq18JBENMFBUIlbp-wdRuivHUqJMPpaAmMfJjy6SfkQwaq08l_ybt69F3cvHSRxVya68jaRMWMXJ6
f9E7zRMvyvJYE1fV0ggMoTi4MydfDGbXBSKmizGg3itprESQPZZiRNgLGfpxVrF2rNBa7oLjiY9-rHQlKcef_qj1ZUjPfZxNC7cebY0lKZev6YBuKM66Ssrx
jLW_Ic4Eou8l_ybt66iH_w9ba58oimTIm4U5gNOOMsdHlKcHftm1Ki0ypxR3c1miab85L2su_EUB2OQzNKan0gI0QfcwJJ39lMWX8fU15F1HOSPpxJktu5wp
GXGAa0AgPUOTneXVXsL9GCeUrIBvA4_EIF9s5HOhG0gu_ASkM4mSdY7FRr9mjKo-mnWPgmL80TMYB2QuMWm0pBEUcE1g0L9mjIY82QoM7_4ia-_mvyl_HuB8
mJ-RRAyM32suMbJ415_-65p2BeceY0ck5Ym5Q_4ianSiHZvL2xdk1L_-a-ymXd6rK2nn8VfKBUfYWgl5iRjBgRLumbeSYqmU4qmOgYNKREzI_aCiU8RWvPyd
LeBdsURgxb8wQNY6GBLiZKbkW8DKYukFf7HA7AJWoryKn0JFyrDA9sCflLfs-CVGOo31GIdbAGLLYuw2_JxFvCkx53pFa-ym9gs_jHWPfBXWaHPLCS7LGaH-
a29L342A8YNuyb-8N5bBuLe3bBBzM_qKrR9GMA-FhvMX56KnmPT_xzeipqcE9K8fsfJWQd5IYv1zhe_5dQBF2QuMB-2T44ZHfGHNomOf2foWQjaWHO4Iz4k5
Hyz6YwKeSuB9gylVbifOYcub-8Ker-esIYbjJl3b7pTVj4qBARYd5S59qQy4Vw_S8AKf8tcxLKfJI7IRf9IcaXpixr8QG7UrID7l15_-KCf9bU1gmL9mc-Yl
5YobdGFs5aWvdn9SBLXAEnN10IadKeBd6KifxOH8j9-aj7EI9M0fxQH8pknUf5nAnl_nMSffsmJ_JGKfLqpU_gQ2bBMIImkxBkLoCbHBBkzABYtbtSbbfHnS
oRy
}

