sprite $image349 [181x249/16z] {
tDk9Sjiu4yHnwXRwFwJV_sc_Gw3SjIYKGCemHM_lcViNL6V0CPElVrUcb2J-5ZizygVOIiz8VqOj9RFv8smm-yzq143fRx5103lkY02GFmCXIO1so3OPWmJA
WPrM6qUpMKwjsh4hDFcJSYfiW6bFQ0aLsMUruNQ-2iFBrAkjpwBJC0p7H4vONUd8RjXSX__be1aTPk-usjo6_-VoZQwpYNrKs_NmKKSEAiaHx6Xgm_6XlhaU
PRKXdkYTJ6suFz1NibQIPhR9Hk-asd399srHbiBSZ0AzXse3r-zEovO8CDdeVLJxOIL76Q6i3gA6tiEpDZX905QNwFrq14SsLT5xwWWuileLUWyF9FgMQrQd
1dedKriWa8nle7So_YIjGvijf8-m0vH4JcgZpHPessf_hxNXKGr9JRJPo1q1DXiTJxGahK2F8n0RLnkyZ4U010Aq43rD4yIsKnkSBppob19BqK5iku-1CtDd
iuWbw9YcaO0nA3kYBT14FAjXSmjDJ44mJbDiDhM1o_6SljKp6sYJdI0UtTwYsjvSxXYAnIP70qr6R_FG2jVX_qb6csro18t4Z6Q3QiFjWJu1O9iWR6wWjtuW
0Gq-Qj_5831v3VhtgmsSl8xBnnEuvklGlrzj8FbZJ4f9ah8wJ5w1tkH33SojlW7Cfo8r5jjFLpk0T3gSj6n7t4criTPHUessIf-fDYnTRAKAQJ5Rz5St5riz
WYDZsXqHlVSnB9QChvYb0YqQVO-vHFgLyUUILj0cHu3HYdYD7gSH1Bzriq_pUTP-ASuJd8ZLw6aaw3v7vZt3Es8TdQI8jUZyp1eznr-vs0O8f3ewKKm_wO66
nb4JjIkI7gFZYSv92z0WjSmGGVIz8i79FS4xOXqDZYGM9A0d6noPaeMbcjAiSan7rD5zhyXYHSnoIIhCI4gboMUM4-FOGFUfzcD5FDoBnJOScoK28iED5l5D
VesMrACZVityUh4LUKuJKQBzinXVehErp-zycLV4CzXAPR5LceToYOv5Q3kbdrURD3oYyeqjsEpfyIOQ9KVLQiSQzBmYtietjZCRyU9oIIKwNf2TdrORalTQ
o2tmx1BrEUsJzgThvB3E-McrlI9wxlezio3AELqU828CB18Z5EGkrGRkn-6a-UWaKEMDhRxdjDtoz2ZYiLsGczNM-skBKZdsb2J1eaTJZsqASxTgKujKeESX
6tKqg8AEWjonslN5DbdzSdhCwCgcM9BR7J7xpOPeETghwuinrx_Q4tFaMhzyDBLBtl-A5NnfzAEf3I_UsA8wEYc2-R-nZDntQayljl6GQdCwMuifqY1thBRV
sDQtSKaY414jD6gmErRRsxYCVZMdKGtj7tsBZdYnDResfqiqkD8TsAixucrSIQ-tSKyFvPf8EDjs9AFbRRo1Jk9xUa0VjbQpVOInQ4w7EuspURMzRpb8xw3H
TjKcYdm1xJaDFTZlxsCHuOppJI-Y13NGMrVx2OxHawK6Yg2O7f-iDjdyvRmo5UHpwjkHvUo8Q2yCxZOuX-6itco1sMkYDZh61teuNDMpsYACNfi6EiOne_-N
uxrRjKM4qLtOAj4SXqTElQeTOVIRgPuqO3JNGsPVr8CT7T2kjj4IO3IwPFNXfXzrHFH2-x29CQE9A3wkdawPVHJliudeXZPxciPSZoSwpBldQgUthqX5z44x
Cth2w2Aw7enUpHRH3UqeloOC6Lr6vneQj8ZS4-qyr86IgkPSxGJhsOheZIwh7J6Dh8pK9FT7bzKsvtxLZzWYVX5jTlm3xHky4JN8_T5EG0H6-mPVprR41cXt
n6ZVu2ix8gA1jhel-_wymG5f4Tla9fgfezewt-3tG6a1syreeBs-z4gOSJjczZq2QH5R4GlGChfNoXjyk4L4ABNP8XQXap2wFpkTd-XwH-wd14viZtOcSBLd
TBKZTm-OfMZFZzu1vvOYIhRHtdvNeBN5dq9nb5IWlVqkHtzjYYwhBM-_-qMN7V7sUzilkcHx-xti6-rgUy3i7-rgU_lTExfUxUkVG9St-mxHgCxMdj4QBZIg
lKVqS52ZselHiHrwk3UglHZDHz5chqF3nz6kzd8qdqCxh41BdqOx7znSbgFFwG-YZyD9Rw7vRtlteUIs3aDX62J50XnczVvlUyUaC86sADKnSKT8xryqlobi
5xmGJPJn6sWblmfDeHhOQZSN_Wmz9ef3D5K7Q4VeNZoYEpAxGklSw2UCI_J-vWkjun7z_smQsTNfeIERGMDvj0x7DT7Nwbv3Mn9zpGOMHL-prqKhI9BuG5is
4sKuGWCJJQ5uGWC3JHJP4ngIXZgvGWCrEaH3Ig3jJz3o0ZGWsn-XzvUW0V681boY0PTem2KQBj60IpJW4WsuHCCb6d291fw7lj4t-aRVw1jzes_qZRxHD_f6
t-WRVQDlj7X4Rx4vH1Djx11D8OixTAmnL6zeIbn2QhxG8LBcZJPnXMurXD9IA9xoe8qpnGUzEa9JA9neUwJD7j29ABR7LxLfsYxGeunvXeJQOYWkq3JA-9vs
50TvPA9H1eNIHjeEq5Gu4ONQqYX5-rWRFS3HfYtheqCaIWEyyIm5hqVl7TVeLXGSPjgo0hhtwpmcLTEEj0YwNw7rKHZQaVOYw3FxZ8xcKJXBmIfeopwZbSf5
Iv4rqBAb8ePjqI4TnuQclQs1HXZXVgBEka_R6moMG3SQKpzffCLvGubLqrxbo2iqXtk7Y3LNaH9c6KctfaNGzK0dT0XRTg8Yae_pEO-q2sC9DDCnhNTXDkpj
uGMdMKOe8shv1JIUXkxXG6y3RTGyduVmI5ltwKY_X8OyE-g0YMO-lrlPJV08kioqVmsD9vvvSqJHPlkhWUYKDduQBI80djL7UuSMk_qzk1JRI3krckJdqSoA
VeQwdlDeywULpMccFRVgrx-_F5MtC6yl4stMFvDsdjTShj3u9-_0GNbebVk1Vlk-IPtI3Wzwk403UFu3KUVy4N1FFtbE-n8DMBGHFraDvbCqALMOj2_H-DTe
PSl7JIgAJVjBDF02z3x-hVs4tcOFHYqbV8e6NeBMiUX4Oo9wXq3P2hFazT1KHknYOPOiiX3QxYHWPeipPEQbq4p7r86sEdD4BeRkyK1l1vhVey5heUsbJXsw
INs6vgNGFRz3R_k-MtIVQ5a2hMfi0vtj9jMxGSk2w8uoRoyMhRCcMjS_z2EFtGDwFn_7vdyYM1EjGiMPdog1OhF7nxuKUiSKoCUJCCEWzxeEMY_sfy-IoXQz
xykWhtUIPj2FMHfT3tJ42Qri9Q-55hD8wUtz61deRzzMG-Fx8fNqp6FpovWVEb3Ho_KHS4QVPp4qqeTd_Yq_lKiuN-dT0xfpE3Mz-r1B9efoeCK3-atVBTE1
tbqCxFRtjdkPqpF_dAb_ekR_
}

