sprite $image118 [239x172/16z] {
vTdfOjD030HWtvRauhp_qtARQp2RIJsfAkONj_cG9hikjpU8-UV4xV_87lujzZze_MTYhuwDdzZw6ssEgLjQ_skssgN5r2zjxGeRQ2k3mzlPQvSMK-xmgGyE
PsArznXJUuynKM2qzS7-U29gOp5xRIocmDb39Gfegu7zqaG1R9KAhov8l8FHrWU7wx8ddcpz0K_XyjGUBIPIbhPsXLT_PehlCIRB7jVVQ8VK7V3kZTZ3oGVU
FRoHldiqKxP32QnYBiOoOFLS1Ekn5BU_FmJtIHNUmpdkulV7EAuUx4SaN6Uv7bfiDgv7o4khvr9HZJOfDrmvMZrtVEkBzEgUcXiXtMCzbuy0cu0h1eTVpxMn
xuRbScuyOxGyrxxzr4HozGCELt37xbkCuUh1JeJXTjyp4rpvIfkBkARbUeHWZMaklXek19TAx3hjCap6SUVlBy9ES-T-lXCiAkqwVFcBBnJNfw_QbUKkFJph
F270sl4XEwmCrzTvNjXhndeyQrpldCJLfPsxdnbDUgkogVkPoQuwb9p8sFsMoOJSeVir9nLcmSvb_aOwqY_wwHuPY0gti7ntiS9jhZtOtPCAa-29rnwVp53X
DjVceMSlaSlnh0igx8zc-UuwCZMuPkiyziIT6Tf3LpYkl4JPt465JxdhySLpWdjrXQEXvIjyobswZk1AAXpjUs8htHyPxOHhoppr3Mv7F8kkC76TO38XzyZQ
k3CJeIli39UFdeltx_FSeW0Nxh2dYItYwLmJSTlO3zksnVld3kizs9SFNxW0leBRp_rpkFU-0iTdx7TkQwFNiPKU3uScTpZbZlyCd05tOW_k0HPTCp0Dxi1V
qjjxV72FnCFO2NTBnRNnmT82jm5chkqgBZwBs6FWDZQQs2q95z-zxZjyZW2t0IPsIy25VrXgZv7BR_HVIzlc6iVbt_mGYrmUFC5kwRZZAqkBN7wZbnvAIt1x
XkjppvOMjC2bmJEKLiLrczZIDhdyHjjuTeiR7duZ6eXddUynmMN0wp2PKzob-nQZpzrb84fBSCb3YU2kouyM3lEoifT8ugGbkCI0EUxonzbbLtEXjC0bmDcv
SM09BW6ckMu6to6u59RdOeLvBX6QYuSFpqLmMYvYUIucqdC3i0GN4tcuF9RdRX5PkRZ7F9S7wxay5hbC8Y4t22p19S5wBZzQdhj59E2oM9xBW_LSm19S8g7Y
6iCD0ajm2J1m7yl0xR6UkqKekIIMv_89FPVVOvxBW_LSn4guF5YVsC0WvsA5zS7IyhdTRfd0N6bvxPV4Ay7l1djaImFczvZN2ZOwA_R8dXiSrs7pRtHi5s0L
uFnxBAXmKYpc9Hiu15Z1HgSOxGle1E2aUvozml4ChE1UcG2htkX4fSqF5c3r5SwrntfmNgmUh2yjOXDLM7_IPgzm2B1fmR4z4IjzSyYwn_e1wx7vmP40AtWN
pdJuwDySqk-n_XGMOFDME0JON1MMlEPbtcW1DZSu_HvV_NyihyJk0fCIBC1cNcd16cVs2hIPmG9iPh3WyCdi5OmsCrY0pGmMO3Dx1ThCO04sCrY0pNolr1y-
gTw51QFDlD44jWAOm5O04wLDdxY2czZ73vZ0LW0Js0fW0bi1N43BV6OHs0e39h0Lm8IsmaOJs0e39h0LmCIDiG8OHrlQ2zZQOC3M1XEbhN0ebHujVZaBiBKt
6h2rmM-4_GG
}

