sprite $image162 [275x178/16z] {
xDY7iIKX34JH0TdU_FDT_wtgUST0dnouJMbx6ablsmVg0I1r-u-Quv-KxGzIV8Y-aII-iCOtyyNoIMc6BvWKJHpWVTdXFSmO4IR5S5hqPOVtC6-CI65jeU6j
LXranHTCYWIku6tPuJtC694YPVxXPL9wu6RU6952bntUmr8OaI8w8r9uMt1uPpuRQE8XiZCYHVHbXdVciu7XqLBvPegGPOVtC6-CI67J_TvlbyA85D4PaVqa
fHbUnlRmUsTIUkB5eWyzl4oAOGof4mplb4dfWQ54PqG66sJ5a9GH6ULiq083ypRzxttyIwGcXfSwwl3EFyXrU9aKmwxOiiDxM0eZSaDIReu8awA9_L96f4ZX
ctbiKffX2juOaK876Dxfab8ZmgGO9cIt92L_O4PvGrBmgvtpK48RI8AeX41qc9N__s-l45CYrTtUEiaiZ7Eez8f-qnw1xKSeNwK0jDdbp8UVHG8en2xdzDD8
0CTNAKz8S5FATo43EOnUbJB-79A-bJB-519QeFrLoXsI4kPNAPV1V6GYYOJowKh1D8nC96K9iLkbuFzjAPU_U4uaouyV9GHyUCS7fc6-8LbAV7nB0J03YQIe
h4W0sVqlvFh6YT2XBD5xIpcs89aGFvO03GbW_qgf8t5SNMB8m0g5NIkbZgJ4UNK9mG_f-7MNU5eMWm6BWWn0dzVnnpcHnChaWWG2XI3LzzbW-XzFSNBjhb32
0222OCRd4pl-j4AXuuR43CWmvSzKodX2GYbN923CzJiwFVkfIf73G8wqfOSTjvH3BJqYa4CZg839-52b7F4o90GBmgS-t3ZXPIWG5AxpWHt_CByWCKm6JNxc
sI2LSZ-424A2F_RXnl6Cvw5187VF9ofbV5MAOJ4W8GZmgvJSFSnNorSf3-cXCaBwjXJaiSsK4UovfGmDIjbAYjXjUXH-8L5HIf240B17pofAUK5IKueoE50u
l-zcv2WRahQE3mAG5EfAAIkG6f8y6xoC2KWhZanF7vcf8zakaVyD2UYiRZq0gI2fAIMH00o_VyUNIwaYgI_aH9BfWQrtbaWLILqfqeRahPMIcQaZgIl5fHZR
q2R0y7jcfewaTZP892Nq34MXzynC7KbTALUsGJod9_IEcQaZgNVyH59CRECtKqe2gIEfB-H44f9yIq-4CZtskxJt2f86fLoHQ9QeI2XSba8m_2OTFu5Ka3Gf
nH6s9JfAS4MoB7oBbfAPgI5fLmfTl4AHLwMiI2XnKyeRBDuAacQbA5yeMjEZiYpKidXRo7wtpDIHr9MYy0g52OLQBaoWJIdlbPawahfIw7X8pmL9l7JyTm8I
EFpYnz31sA2KC2EH_9jd0xbKHWsV6wqfnRfsV9N0El-WKbpDp6du3JEcKYn7h53usF6Xq9javZp-jl_uP5MAVE8LDT5-DjWVI6558iqj9OeLfKH4YTUpWQr_
NIB7uVVEyGojiJbBYjQpmVuIYNbec9QENqnbTIEsSKqf-o_U1ecqTlo8-vQIunAkA6NFp0IduK_DzDHIj27HuPnA-GSNRxD4sfKITnq_aN0wJKobzBDuspi-
dKfnuN71SDpIqq5xRrRAbfu89n8EmpHlK7ffx-qTNoebv4Ho64RamuqEsdkxKf99MIUH74-d8mr0LfyIgIj5qbhoDPxEbqmjosc00DAX3jfxUySF-wmLIVxU
iYppB33u9vKYb_qMRrqfKIx3-Jmc4iu2H02ozshlux3J704dalCIf-5mK28Xk489xP0Px0LaKqeYMPPB1pW6hy5HmCxq_DNs_h9uTr5A8k7XU1Z6QHPWGg21
XDBTugqhXICkI50m3dV1GQQdlyLRLuhEaum3bgKSRy4HR9XGwAy0-QkBjtw9r3oE5oGBxeD3mSxqx70sstCEPr3JOOfbESy2S1SSvkdj3o_UFIHIx_YQfb8k
I6We8C62IPE2Glr9fBwGXUCqhKWoE39iM0msUBQzlLSMxwvAyJpCGWxl4iHSo3kSpNPVo6A-FZ8u8WmG50ZQEzpUzr_80eCm5VV1OL2kfgUzlU-vUDlVPity
de08WYO0MpkSpVRk-01aY30Xm2kFhTJILWVjlLKfe2b3HWXn2uuC2mftkNZhRxCcjbU7RdLMHYgbW_RUhXGH11x-7PX3MnsqztQb-2uus_uXJ8YqUroyTQL0
0ZS8t1fB252uLudKFfsjkoxxM6eLwgMzjttkQKqDWnISkpbbIzhgeBqtAqL4428ZWsDnzOlYqRFgHY9rfRpMMQxVAzFJyD2xYncF0FA08js2y_1meuFstgmK
cWemOCD21WSA0A2Za_RU-b5ARl79u7XRHxqkthfIf2H1KBTb3FRItjixVXPO8vYDDX99hnAfBsI20WaH9CqjE5qltlf25a60G3quWGuaKZyRR0SKUWjEtnAf
AuM4bNLM007sldZhIhc_dHn6WWtldEbNAGp8a34E1xBBzjx-wUpKoN4Om8R5sx5IjknCuvazIwJzuSPbsD3UUrSANvTmPV5shvGSjjtU-rSAmExRU_lPeFaj
g_qhvIkHvqiads_lNoZptroy_m4
}

sprite $image162 [138x89/16z] {
pTe95lCe30FWB2H8ifdU_xIpPBOyCqlBe_6l4-Z1XscJB0FPQjsM7o47HPvhUey2aQHOSdjiLVmZmfxNOpqf_XMfRfb0xb4EbnrY5x4a01530fS485Tok9JG
8qGyrZGWFPSC83bSrkxa9d4fSMCIk8JH_bw4yip9JU9oK1o8T6uFdDpPNEO3wRca0ObHtVA0zByNye3qN6QEzYGkFP0aBYNsoE7I0vd6vKCWPmIImwM_-tEu
z7T_3fT-jATm6J-vytylq1YInGMK69B31O12boGk0CAoP7410DcyBkF_Hiu2M7FbSwbhXVdhPSzoAV-yEzQabiCbDd6qHX89NEAQc1fu9O_BTWBoNmF-5Z2H
orv1SmTu1KZaKYee0E0VoUEo7lWZ_2rFNm21oxsAW5Gkn1MALpAvuBv7U7Qwd3sNczn7krZyiu5x6JqsNSnz2TdhhOlqp1qjR-tM978Xo8klzFqUeKda8WBV
xsAjnIQH2vlnAlHDBkQjRnAd2rjpGroM-HiJcyGKi4dcGbNJLxh8sfNOfESYDycSUZbjVfTRZzWaPglc9hcvsK-Qp4NUtcnoPOUPP6vwMQL4wHizl3Nk___8
oqtcxghpwCf23ojlFGQKoveRfnqZYnjpllrer9hHF4oNMK0Qja-U1hfBvW90hvGq3OW2aBUuN5revrabQGwGO-2fiTmaTvcmbB0keq3gElOatLpoPkUnd3Y3
tA6J6u1ynCMiULaNlW2IqcD0OWvvCxMoaI3vmHPD01Avc9ql7cNd5KWQ0D8Ya34kmCvN3NyO7m4IKr0F9_Xt5KqOxODRn5huTq3flOtnQxJFp7R6VqxIUnk3
TPcSlP9XMKRl_lbVFqYF0Ud_ZSGg6hlxvtE1f86xVnONnIqQ6EsJk7Hq1qRx92wyHO3QmDq_Yylj604S6ktpfmkWUm-LvU6KghWctfeF09arNRGNZTpzywUB
ZaqZetq-5m4Cepqd1GG7H_jyBWgZFIqRR0Z8Bm
}

