sprite $image363 [210x248/16z] {
tDO5ScX120NHBp4kJ_Q_sdYwucxqsK4NC3NxLwiBkqVTy0IvabAtnJ4VKTD1FUPWRCzMJx4it6s2dkddr0L7Ky6nUWL7K-ejuXaGH0F2ZFaeLk-ae6ZQwcCE
nXyG8Eg1fmSz-eLxdAS76V377jLKNsFJz22MXRjjweiDu4IoSBV5qmFBmjtcwK4q2rSG3GYU0I6U7coU7dp1byVKj1Km-fnIlyR9-0C2vXyGu1aGukd1_0S1
40q8dW6XFVF1vfaFFl3b6TnKqqIpS0LF3w89GXvlwXGCSqgb4r5IdKjtQh97BYXjMJqwCho9Zr7JKN6SKv-BQlNwKahIH95dzOgYswitkYaDnpbbQHZEASkw
DkQVKtfTAJAiNYyhHSERM3YACFUSwA5ex3bnG6ZCN3qE28sPgyV28MVTseTot3WGX65nCmUG-VvFUs45Xzzxs5weLSE3KVa2ovyntI05nPmc3Xn5C4qMfsW3
nwcB5QH9uiI1eqYOZD7BzR0P9XWzFN3ikcTn2iEKqDWTqHHnui09qHnnOcDhKH5DtgQtRTdU0T8YtH1nt-tQUBiFd1RfqRi_h68Cz_HeaTwdzoOIffm0QH7Z
f4NvSMA0j8YZfqJvsnJm294qKIHCcHujOfoaA4f4LcCx8iQfBugi5oFjuVUHsAQUA2Bf9IBWaKkzTuTeRvXo6bjFNQXzeaXzP-G7Y0jR8KWGYVkCt86ZI9lM
eAXdIlNehjEZHv68K-R0SM4hL9F38-AKqDX2z4gSQebGdxY90wT5iiaZ2dP9c18QMuXaavUAkHDnoWuGHNgRs0mwJla3Hv6E4qLozB8z_lUH7htq056auqIH
FtewGBv8RnD5sfGmS594anBfE6KDd1RfxoCpJdhWV96E4qN-VGO7Ba64qOD8a_YTaUAXI9ieykyp6A0K4UC4aN-VmNVi9159tMOmRwO3dWmHjm8WS_IqnnTf
qtl5XdYZnyRE5vMuhrAnIMDDJXCyYI9k1RwFh3W5FVcYRZECdqwYiNSJEN4I0TfBPCJ9y2I8nkCqXOYZ9s_Rvn5fqxqHfXBfs_R_bwX25258audqVSPq8jri
CPr8Nz74T29zdp6VIDzdp2VISPfFfECqdKWt-NmYRPfFf7_HOnxH-6txB28zUkssVGBHs6rxhJE9T9FNINAaHs_6hgDfKf5gjlb5D4qjqgCtluYc-KMCq_mY
RjEy8csQNyJQcr_4E4qYgdLezBIerhgpg4IKyTls9w9IwWuYNWd5y6txSn5CMIAIO98D4L6h4C6K9k8snT1jknQLMdTi1fhq8wH8R5DACmJYf9wWHJJbDmFY
v8k4AQiPE7g-Y77ARmQEdYyAQvlyPWXX6XSTZwim9JG3ukIA3czlvy3evKrT4wWuZOlUbglOfencm7vved_NuJPWSaH5D4D3cgBxEg4YKaIrWaAJBngFaoyg
eAWuZOiOfuofWq34QLJKbcnoNoIQ0VlbYKISyfg1I5_qjbmGfyHcwCoW9n9DdjaCZ9CdOfnsQGOYRH6RlExN3DGEYvRVuqHIIZFqaJ4kEiIv5wVCPkWZnqMb
hCSthjCgDibl1bAUcdw8tbyMbNBxFLGVevVM3F5i1kCpeXANXQIRs2GpHwGytw-1FK9iuiGmOUwIcu7_Pa24KmXn4dENsWo38fv2rrz7xywi2SqWzciT5Ys_
V4_yskJ7pjoP8a5vD8rtNPmwSVf09ZH3yPgXVnwTeg39by0csIAIZ6PGeby2T66SpjYaQPhXq0B4E8boo6m6zpngJNvMvR1jXaXGZ6RWQzpjbpYTLJbicp0P
pH16CxIr843BvOVeZ4sY2AOnaTWL-vq10Mg3g4M2j6SpC40hNk-aI9loc-7GJY2SHr9Kjv_B-vhGSRBEet9VbqM8weOLNZEe_HeL7HaWd4STqVQmt6Pu-idq
icXv_9RWUKGHFTgacs7rcg4lOe3QbyMf9zfwwzkdcY46cq6BU1vTsddK5r6XuwIRGSTfLBIq035E54bFMpMX6RJek9wwd-OKRIyiencwo64H0jGvZm2I9fqZ
KN9UCnmHeEvvjBsyHfg10hyP-kVHYI9uzD9JnrtHpU2VH-owieqk9GgZ6QppI8kqARyP7WEqNBL8Bz4CWcAzCp10F8ykKgHD-Ss00E4y4YAzkhyN97Q5Mliy
kYw-Y2zxxJpxv3TvEEVHjTsyM2Ak3r7xf4fwPq2042U835F5ZoM6BvVDywWrkTaCN1K-yRhgDWC2XFD8Yym6x9LSkCs00BKuPOcu6U4smwL_7XtN7D4NDWFp
Rvn7hkWBcu5_V9v7gIBTv0CY_F7ne-94aRx6XAX7-ccA_uhJUaeLWIAQGMmJ_lZuiZXIb40QQ0Pjuk_GN8ppo20PpI3ZT33E8yFaD0FZn3QGvr7-w44qi4s1
9b-4o5uXHaytWoOnJeR8DQq3pQ2kl2-B5EN7QKZ4ImN6YQ94az4Ctnv-02_UwrBZDDuC1NzNY9CGPO_UYw8d3uxB8aIve_UII3muJaAKQz8YDTCjJXJbarvl
XjSUV5s4A6sRb4Wy64qkH4acY8H7N7d7wPeXqhVjVL7zvD_LbhHYLFJf_T_Irf38sFyjSRqiilP_IrslYRpdRiaaBN8Vl6Kl8V8VlEMl9wBDMJU8KbVjYJPp
GPIx7aJm60kYT1D5N_Lsikst8AhR7x74Ru_DIX8Hcj1K4pn_0m
}

