sprite $image268 [188x134/16z] {
rPc9Rkiw34IfXQAaaV__TnzSjpSLfWu3eI-r1_jT3zYZeQBO_vlMxQxfUsvAVgJTbVo6eszzpfs6phaHEQVTYBocqkVSHVIMHIHMfh_-q5MEv4Rq5oUt8F-Y
fFsLoLkIxmdMvrnOT9KvrzU-VwO4uR3sL-p5A9HBQi-YvtdOLzMUHU-pw0dRq4jhpxru9BPjT0naH_iBzg9je-yPMulNqfx9TGOS0_qpOwlXWjetxiLFqT4V
mHZ5qVuglHZgeSj43tMqlqGlbZ4w1rjFbz6-_zoBYe5EeKFxbzgtdtinzKbqehUv_qdxF-b55hrcSfeEBMdV_geNotZeKXDPiOTsLT2tZhvJBvBeDJtcokBq
lzA-KI-Iw9PEo6XNlLDxxaKMtIBTVFzIUzQ5HIUFQ8dIhdgdzltdNioOoJbwiglUfdtxkHVZFz6R1Zb9RCwkMj1-gHT9T2RdbFeZlOKrxTTxaKLlAavYglwX
3UuJu3fvZIGwbSvvTZ1lLqL7-sNHyopwfoxL8NUrxxFspQ5VxKKMlIQHrsETmhjA7UsNUf55zydvXUbDslUf5qbqY_9IgCUzNSNQhukkz7P1FmidjAc8VaDw
JVlrNWpskBe0MHOIclUvQbrxxaKM_SYaASTlIzvLwzgpw9b5dtzpmHioWWwjgxqlUZyHVTATu1UEBEsgLUrdE1RzCrKeIst9kyhLtXSzaUZVquByIn0t_4T3
xMVqTKdxJht8ehDEhyFd4QajVUshGp-BNWABFYV80dpTHf_-uNDwVIhOgxsuYqvfB8ERY0rzXh9EeLtbQS-zoA_HpabruVFnBur0HUBiAa_x4v4JYyvpVzsN
FQXFshBHhdArRzIB93hxpWcEBqT6EhlWj2I53kqpxO7llaocrz5FayM5Pr-EuEGLHFc-W34BJEp0O_2Zqe_f94v_ao-FeF05vxXH4xo6gQdHfnZsc3a_9Wgo
3y--71cHBZWrqrE78p3C3lQ97fdEDuS16FwygOJp1OY7_K-k91ZZmNw8G-rqBWuSUFRb4QZCOS2cpwuaOypiW54xaJXqZXpwY1s70bPh1hHPT2AVs4bxTSN1
PXwyiYzSyWnOupFHnypEuc13SiKPEFCcdFaobJmzzz1Yvsyyno1s5kVGdiNX-oedbZJxmf4pm18SqK_OgIyzSJ2s6eNFtBRPv0i5XG1PbumDf0kndz53IHoc
xsNw3-lODenj6Zfd1E5lgbecZuZyb9txihlYx9nRhsLFRJlqpeBdw4s5lv9LJtHcjyBmDYdjhIfWZEqZ9ChFiS0TOYGw3PtPguJgQi_YhASb_bZJqYkYipCc
eXsFS5zc5cSzokNVb4G_qOLyJv8pA4PzIU8in08lon9U5PtPis2sXiNPx5V4QPb5hz4HtMEVGkBGDM5HdCAZRPb4fw4xx4rLCOKNBPBp6EsaHXwjBxhFlYk1
ALvVHblHPHRTPj59brVP3P91eRvS5QS4saKjBOX-pbuAADINA-9a5bsNH3zd3y4NfySLSKeK6oUwf8VeD7IFlTK7kvehpbR3WZZZEtcDowBpNQp6Uh3tWbxT
lYmBue1waKHdNNps8uSpLhDaLnpa5N5uZIf8boNsSB1Babm_MDMv9YmrZaL7z2Nsff_i0OtMBOkpsO8uBPFefCi2-vvgCQGSO1PZdjXvqM8RIY-wJdHPT6Od
-XvJpm6wQnp4xyl4Z-ddiHNHpycP7ZZOu-5C25vVlYfEJIJwsj0t-mh3Mz8OY9t4cVhI5QUf8_eIEjCtaKhiJbywufJ0eg_hyeo-DkGlTedgQn-VYrFZBuhE
ONE8_MbVXdDnMlvbqNtuxyvueySs2ed3lHX9T2oX-_IcN-mgfVdQfraSxaNRVarqd_wBFKlEhZZJDI4OVRpGGReiaRzENmvsguWI-tDnnYpEr8k9deNns-GC
Np_O9LLJiG_OyaoSRxWvJDy0BEkoFH7T5oTBbGOSlnFZgtt9el--Bhuu4XKQeo56ZGaSwtHDU8_eFhrAtdqtx2m5Vb--LNHVd1YIGHgYuVLh0elUrqLVfpSD
3HM83I_tfMtREqJtwNi74X0_93AKvtsvcUXueow-EQ8zxUWnMlR4sVwKdE4bnGGqKSJiYDFVBZe7lApgyH9LdSPv-z1zxO7-nMvmwDzFxi--xEo054-S8syb
z-_sab4W6IbrR_JuItIcBr5obImPGM8_4USYv4nVCqmbbrQbdeWpy3Uw-FGTffgbDMrDjOD2R7z6pl0msUSEj20I6YWNGcVwLXkijIYeeiSnM6ItzmHpKf8i
Q45H6t9OOhVtXHxH8e2A89OJiL-AdCNfNLKhiagOpkmLqLaSaG_VgrXKOhyMETFtutQGgqZen7ujSZO7gBN6BX8xQYFsIv6pE44aGCG0YSH-ANIcDrM51EcG
uuvpONAcHuDaQv0S6x7Ja-xbw5MaGPISePbV4ZvsZzsk5CmXTYA_BZrr98b-iO3ZpFpIy0xwfUdlGyxq9FgDw6dcDu8dz1lH4_cDw4dq6y4J-eteIPVR1Fyt
-Ny
}

