sprite $image146 [141x257/16z] {
xDa7RkKm34NHL4kN_eZslzhfnUFsef6-p22yApXuH6TfZR-LgsEP9mjuia1W5fQj9Z36jdmL9b-2iP_z3-Pb-bNgIjboq9XfKMUBcLp6LfPbkPNoOl-cfjbO
bZqqOcnT1UPrMjTi4TF8OPQbVfYjnWIcwpGtWId2qXLZ2bCsbYinPMbnXmaCgxQer1bJZZ0Pa9pxO-R5B4BJsL9UDfYJNQJcjRIrPocy4_CWXcdKp5MOyYOi
JPfIwZ2b24g3fhZ316Qsmv3bQLC3wyrEafmqdVPGYJ6Hi8YwMRGcJwgNSPWqoNfXj6Rwb9Z012OmWGbCO08JcC049Z212KnW0XEOm0GcC849J62IndXwPEHn
63tDo7yJMLcwQb09IsrpYuK6YtUCuGQJuLwO37KMk2i6QYXtnhoVOmp1a8iE1c50pp8Aepam2gCrZC9eJMOKHclW4WmcB4Cn82pjc5I1GLiG5b651PCM41PH
JjjrKc8tZG4G4i7PM02fuRZE6AsnSHYfINZ0v9yON60Gbh4Ol65cDnWh1JSOV67C4SPmXE7JOmA3AqnQOMYjmG8vBUD3PVZ71CPcJvWRVfezOMutStIbs-pe
Iewc-MRvoZjzRRaHmp0OljOFyFqVDuN7KDmcmsHtZ2sctFGTYRJcRoKLrzpI-9jTLKx5c-_wwYouep6cECGGwjSEncQCqI56NyKu6M9S9fWE4dI1ginUg8lK
Z4OfqGoZAjrXr8TbzRbq-cNSJxFsyvvTKi88WyiRqnlPBRZ7S7lQiOmmlWyZ35KA1cy6zzVaNZll5A2XPQxfJLmEHhKxI7SDJ9NpG2vqt3094unQj35hA-wN
sYOtU6oPQtByxYedyepf_UtkfIQLDRRCDViyECCacImpiimrmL2bCuoWipBSPc0PQuBf1qzw9idK7GKVHwSOgYgOUfecWjg9TcZHx722wSUkw551zGSfk4qG
uD-rWDREhaZJmmb6ZUcYawryAqaBiqipko8nxPnWSDrNrVgir4K4knfsBamx1tXNyUOTa3BLh7EHFE1y8MEAXV3RS2L5VXVavOFeKvHaoU2ZY4zSKABb_liK
1_auY_pxWETidvvr-l_57ZZRP967qmYkkPqaHq8qLu2GF8YsORLg56akWldNRi9zEIVnLuMSZ7BVtVnirioMx0PX8FgiRdhu_w-TpTcOf0TRDYATTJOu2DKj
dzADQAdmQregY31azS5uCzn9Ww-RCo8siuoV2cvbsKz3zvmLzOtZzqJK5MT-VaPTSURRCGgBCxy8L1K7mxcDn34ASCmkf676SfJW6QDahCJnonitW7z2osU-
D4ZpColAmm756wN7uRCaVaMm1Nr5d-FXYSLYw1gpn5qW4dDtEa0OFAbC0FCWymC53w8B2WUG2P6ObnRnqoklAYNWcJYuWo6nuXHnhGNzErhoGjaYE43bdVA-
no4m_2ylSFT53X4PKHax0_Z7fLrtEKRGM5HPJ35sq7XdYtqq_7llYC1M5czJzHQtdyQR4wEySGXVWI9DySTNkU3wtUeTpc_bxMgFnHKud7iSeJ7AjCFbKN1E
uh0IXx1FN01BbHBVpVcTn765KjAY_6oPo0cWJtezyEFtN2d1zKB9E7nbgL8IvnO13fERuMGhH3gDysF1QyO4aATrydnX8vms-IEEKic1YnnjqfDuSK8mON3F
QXmZ1cj9o7mInDkj7yJbaM3xob_ItK4SIM88ITuTnN7xM13_rrZGVsB_M12xM6BJMD1lMq_ZpSchPgav9QogH6vbfuRr5YTzWIt0iUDGsTbXWSM1YPbTbSMf
oJs7Sp4A3KkXKXB-gEgwFh_BvrirLEzIYSFDBLNglMlwi-0p9BFBxwOqHk7o6ZTVH_qzimCbW39pGQb_qkZxfaiuPMOks3_pOc0Cp_pXd-JrkQ3waQRSL10u
mZyr8QjF_MTED-8gePJwxqY9HaXp-BeSKMOeQ1XCHqqAOqgJVhDfoqPzJ2kDhykH_ImZZJQpcCQfJ3TfgY-BJpbCDoc_AGrNP8gZyhBu595Oble-LkkdqwJo
Pl5vMKSZprBVoLBFf4agxnKVF8dpiLA_5prpNJBNa-eUtMiJSp-v74TRyFgMBv3lQ5yGlVHb-LZ-CxC6IVHh_jOa7M33gzdnsUozl04
}

