sprite $image333 [173x248/16z] {
rDM7MSDG40HXCj8fzLyj6OOCLjpvAnZVjtwQzjS-g2aSgPBSQg4uAnIfC2m0dI4LYWN0a8eoB02tXhD2SLOehWf3AXIjKAGYu7-Lczkqouo61K2HYjon0isq
iR5Tas41A4CgAdUiG6CuAmndHIbIOKX5apjMm92ACYm0Ir9tRgqkVW6azeDb0TKFmypOhlPFVM1Pm1F10XvINpZ6-Y8zjHi6nBOoLWWMWEpKcR7DSMD5yClw
LLWg2vWPUtj0wipOyV05G31MXBMI2iG-Lq3ijnM8VQu0mrX_ZxsA6Yi4OuLWh12C5O85uD05a7fox1Yw0D0Qzbm1f6QE5SHMLVO2Y7tyfTr-jVVCs5cMipWC
1M1FOAnX_ylj0OhS9ERlTlbWOJtLurS-Dv9G9rNrJ00pk9Cb07M6bUXVBSr8HHqyS2TC0EhTHyZ27EsgnZ9LtDaI02ouYEvy2G2spi9SL60Dk4Z0JTWwkfDH
WUs8hcq2WEt8WYaLs1wkVGA07PO5K0TWExX62G1sI1Q8LGTW1t0HLWDiVnQG03CiNXFSHwd0tfK59C0Msp-1GRszY7P6HtJD4e1YQDkoG8Rjgex1hxdsOGKM
tCRe4bad05XmEziOg4RO_YmWh4ROVYx2QeD5TRGn9C0Asyy5rH8hAbrPG09CiQhIqSO6Khd8dx52r9m5Q0T99GVd_uWLVZrMOzSb5Xc4vTNzK-422m2u3T4b
KHs3bUpTVsEXRUEAwY0i9tTKlCQ2svm57ONbu5gmJ5KMxB7i3wbFcVvtA5HPCCJYNMEHtvoFmBN4ofvNlu5wXMs8hWKsxrs0Eyv7YAuLblTtfRxp4R9WWrt-
nURkyn6uOx5uM2SDs8ReZiGYiTg1lOZkQ6pSkrORjZqBmCgDLl7zBtkTXK5OHDQLNYnJpHs69NTKICkQjo8DsCRe_aiL7e15BTA0ROgkgX2DmKBRWRsChb0X
6V43Uo_km5v6b_Zkp6hwnkOEBBZGiYYmLZdWvY9Wx-q6gCtVW0NtRgoKDIrONpalASLm1vQ9xiJYEpR9zx_W-x4ekXDBhoTSBtQQ_XyOwZQiP8JJitvMmUIT
0hkujzekiV8CjfhCSbZz3pPTnI0-WHLQWdDXvKf3KYvFHP8GMLiinNETWhQyDfNr2ai8iYbM3itdGKZ22qYkXab2Yx34ShWQzXc_TRd0uk9fYYLO0L3n-5l2
DrPMz2r3BCvifxOWiLali8XuLaii89cb_71Nx8AaHqKykOYKYCy4Kwma3Fvo62BUMu3z-Udbu9s3rHQROLMD2EqEztZzSsL1trX5xR08R1J8zsoUgF21pUzO
NrIjiGkIYSy0FYCRFxwyYc9RM5ZDiOoD5FtKqVcMwUFCAGSML6FiUjXUvLzO__wo1VzJyc4bLMCi6h-YmebbO3_3WitC6hjzZ_VuXiN_8Hvmb24MZRzKM3wn
Jj0aoeFOgl43wu6blKTujEBdi0L3z7ki2ZvTEM0lU0QBNX1hx346zigKqMEVn4gilgpGNPDxhqqVncBYex3uvShwB9QhsuLWdsMFRRpeyrYgi8InYlLg4Pq0
MohiXX2hBBiyaUeCsAt2Bky15SgviEgaM0drFMWcBBe1bgk9iQdQn2V6OjnommxmS3TmydupzAHpOWatZTVCMdLIB3k4LcN3LZCZLWAULbOSY2R4OhFowxPw
jrUMQR6Rgohoh5ZsjTQNIR6QWKGjCYTMuekOyChRb5XeOr6EFshIIR4gPKbBfjUbDfGvnsqDN_oyhQlMYkhqMDHexD_jtC7Mb50C0-3rz8R9-p-jgbOL2KIL
2NUEP5Ltty6SIb7__mrxOs_iZRsnD_R6tjZd6s79DG6O5ajki0jgIYpPs5KUZwhfiEoeVtvSas6fiPwRnv82QxW66w3gRL3rMLiJOC4Zx0BpSADOyX2BQgDv
k0aiUOXje-5ciAJ1hlhQuqLOgXmkWnxpMD9ZDRVAO0DKimrMNQWWbZ9wpsxwscC0Awn-6_ZgDdOC1AcawQkexWknD1bcTwt7bs99ZztXwl5rMF1FiO3fGe_d
OvzqqMUDhsvZSHgMEduRLDdgVi42ex4fAtLV_TWB6GcgEsli-CqSAAl6Qcw9yKlgXCuEslYpnbUtqDiWq03p8bEk2mEzkY9KZHqbO6hi7qQ689NqVTLZBsIy
xW-itpzhtFZjEnDIrCPghgjk_mgH1cWi_c3L3YoD3JnMVzRiZrNrrzk0F0kBsYtfjr7y0944rPyr-sF_5Y10TMUDVqtixqn8MlsRZAf5fngRe6gkxsjposm3
GqrseKQ_o0If7VpnHOu-Qm9Mp_Ld3TeSelhg-hCcGBNSqyuQa06jFMjgm6D9Ci0rrJNRm533rONV1WoaJ7NDMMEi-UhwimOqIMxTSRmDQ1AixiDyv60w_cri
TnlmYfJYbll8GPVyriNEDk2LsUi2v5a3NXliSSLPGvyyLt_ae4--2_giuJHvRXzkZTKsu4pHFvl-6vQpHLWRoncpnM9WuQIfNx4BmNcpmSuTWvsIYxREdyQ2
V0yjBg5-1
}

