sprite $image180 [243x176/16z] {
vDU5WGGX44HHd2xEye_sV7NScQwNmSVvE0P-V131FwhW2vfYhcWq24KmpqGN05JHxxXWYSO0qHXC5Hqm3jCKNnGzmLJHc4p1JSmLZPcAWc2EQC4o2bwNsgEn
3gRW2mKNayvehAoG1TSVNR2Dkh-8LD7OLkt115jQi0UgARvG4opUXvZaDD5OBfe_rlcO1VsoYel9ctlMnLpnCOPLMDFWGfOQex4ECHVFiosLHHUi99bEDaf5
qLXDC7rSwgW-yqsSK_JEccu-ezNXmIAOv-Njs-iB97hRETN7HdyHRwuBgkiW59wG6m4w-_tVzfngLQh47QdfNZ_d_ia2LZ8rcS3f9rGdiiYoIHWps5rjG__-
inBZTRNcvXKHispeZ3cCG_yZu7JlEcLkB_YbsbHWsDxd0xUiIr7RKMtOGaQjxPUKJYQkgXmUSoD0JANkMUXAZV45EfzQQ1fQgg7wWaY0LF2PMYYzk1jFW-wK
w0MOZfmfGjJOjCwpL-YJ5jRlK5GCHHQXWsSAoBWhjT2plMCpzJiLs3PrvkLZOlnRo5pzZM2OUsgX-vRKWcO0UyyK8U6kqdbiOD0aOBkDzvuk8HqzKyJwW5wM
zlJhkaDouX4HVhH2MuGLiE4-MrXBqj7Qti8a2wTpc7_RM8qZgn9NC1DY_qmXmgr42pgfhvCooDo-wscxnbaMrkdpfZI0BBTeBIs34QnLeN4u04ouzaXFnAh4
eJDQ-w8jMjiXCodcjcV-zfqWlhs5rIgAE3zN2TkWQ0kP5RfnYnSAndwsXL-zzi1kZUDpYUeWi0wP2BsDn4lx8CyxF3tMo564EdihqkDpjZ24c4hLr2jqVRAt
Ogu_MkyzH4U1RLi75khihIgBC8q4aH1t8NDPEFQO9U_ZptlHT_u1WRiIj9whWHHmJyay_vEyR2HyC8DnnEWh3H1_bfUoa3t5a-XDtUlfq0cPB0i6UmnACylS
bnDOQszhlcFjYVMcZjr9yt9Jtzr8yV6PP9QvBt8k9hkJgsYxsrEyc7Su-cMoDv9crcpCmIYp4xgD27HLEhQEOdmYLFlbws-aQWSFoMD3Myi1R1UcFCpRc-Bn
_HgjANGlFLYIkOI9x1Z-NXyl9himP1Uv6iIckTaCcVLl5XOOThPMlud7VGriZjxGovyXlwQjDMHojhCpIJ5V2YhgYy7tJ97pgYgJQVVATZ9DQhpd29VBNBo6
p1O-iZ2bNEhshU9vlCPzLLNjQhAokxcfTVz2kVpbpPvK35ifumgf6sBJntTFuy1cEUrhC61pxS9jYfVmkfTuwLYOhgMyYFLjhmWpCn4fua7e8xTpTeSdiYqX
rBdVWykaWgsKs9gYa6NJojY-8pg2R7UuRGcYxhCmIT-EhA9sqwsKrBucPgOl8wUtNroj6zpReV4YzITD4Cd2p4nEP3ID7UrPLzuZDrB5d0cyN92Po3M-gZs-
7h_0EFFOnZv7soJaguQPZS9rYqz97GotBoPyBJATGxm2A-HHQBAx5jybYP0gtS-I9FYyf4XcWcfFA-HnQB8jt0l36H9UVvS8tQyfyzDr4Pq0hD8BZpA_jt0s
3K-ouJAHZawCEOOG89PryV9vdjR8uz0z2zktDXVSTxz_4JhFqnfv79h13iEgp90UrIVgtjAlkhqU9TOpW3NoE3GLkypNRWuNguwC8rgb_sy7PLeJcyZZpCIT
sndyYQMn37grteo09GLrd9xIn3RoE3JlofpCIJLqCHm0NXvMJJZNqnfv79eusBSsDcu_mzbACptTHtwVGQNk7bfItTa6XQ5B7F7BwT96_h3G9B0DvahYMZ6n
2zo4fZInZJmEpVGJCcwJof4ZSXzu4PhNn1fv75fFAYjb-1iv5bxq_-rogeUQs8rijpIhoUn0Vdu2ACJDCqoxfszYTNlQYzmlDD4nqmaJObs5UhkzF643nUTf
5x8DFQlFHFyIJC5wrv0Vs40-7vgOMQvwRfxwCiwpQp7vaNLBprSrdloA_YRk8vzOwDgpgGxRMj24l9xk8vy8NTVnd4f5rApwCKxx-Mx_OhAHJuGETvOG06AC
013wwJEpNbmfeT_JMdmYS_pvG67D9ayFIiRgzxH6FWswV00Sg-pIhDhKJc2DV1Oq3lD2eJrmsMrgeudTo7CN5epvELvvzHFynZETkeczoFCBdVLKjdMxIjBd
bGf6Dj6UTYFFXrx7Roif6YCw14W5IOLjkyAhW9WKi0jvAhHH466YXhMMLPU31V7kStRQrkzQKUdIZtnAIszlsBKa8ay_qdmZS-95M3NncSZ-bgR7eK8TB8Yw
OLl7xNLJAy-uaUT3OstZmcBFEK1PXFLYyYFFXuRrSh1K_3jjYk7DnHYJQcAt_Xnbfl5tl8KGKow8dJU8GN-9fTN8R7ZQG_o_Za8xWcO0Y5UfSqLFKDUq_JrW
nJm96bSajq8cKS1y77WJJOG6Fo_a9lgo_60Jon-jUIsTlUMDbVRXaxu3FB_G9GK7RccYUB_InAQcGDCrMiCWECHiXMtY2S2pvXZBBJrZpH7UL3OL91OZR7-j
YUSNMaThTKr_FrGy3XOAIRRgAlrNhPqS8Gm3GG1yWw_yi_NFzsrFTKaPTEqCAm6HJ8-dpLJw_v_3pvyMdsMwxKvF7K3FwBDNnVXVyhtNLsZ4WONruWGodKSN
1VRes68wDsjqeCIcqZxJFjq-q_Fp3wFXOlALZjqkIQLzYNsbVOd17HGi9b1faMcVRW_sw7c9mUSqsDAWnABIFjC-tNunfRyf0fSjNscGQLzf0EQL1el9ey5Y
qcO0vcW0rcXGOeq6O6q6cTPe0DPeasdwJH40wq63J6iq0Ejd9H3hPoK0wtG3i4O3i4utM4nwq6346Wt06WqohRSq0Ej1l_WROgbeK6AD1cAD1c1j1c2D1f_J
6Wt0-k8DCgq73S0Q3JAjqM34sWp06WqohT5Wn7fX0R3-FGU0TRgPk0S
}

