sprite $image264 [188x137/16z] {
rPY7ak903mO_QKQZDBp_u_u15t3u4cBMjwOhN-nYMv8DZgJZK-aU_fdsPF5_dF5nQDmmmaSXyIFZiq9_nkMJGj_ZxPD2tsFqIQ7lqOyAVS_ufD3tUF-aqFSu
Vqxevn_Qxb50FohqqzugZJhUpnpw-RFl7c-ZT9xGwuppXNx-x2M-0kVpX5x7w3oXrz5JXNxQMoNnzNW_J-XrZ4yG-bblbSQXZ1E5RlNiJnAw4QXktyuGEh-v
b8o-E_InCDtwlQ4J7hGe8z-tqVloUlB-FQ4hTf25YUa_Vy3KvOTQzeZ64M7sJs-Lh9SwPeI0M2D2_P_TgkxB-wrdMEkkHDmimlNOx1UMMyCpvDCPO1Plu2R-
Xdtx5w77-4KkCWO1B3IKq4Iyd7tzLidwCsoBD6aW4G13U3H0neW8jHuLj1ZwwaedcyvYOp2eDw1PumwGgBe0a0DkrHTTSPafGq1g8WJg359b9c3aLZ3f0KEh
KMQV2ySS06XqD5Vf036Xnw2M0pVOllXMIQpFg4ud9W90qY0-MWD0OBEafpQBGriElRxIam6qHWo06f6wC04OER1ZH8LH2Rs-qjcdu0eFRbTxfkRUgKNGwl_f
KWYzEgFZuhWpXELgJoHki-6Ni2_VAbd_BX4javyJx3mO02GDlwKlHkhhBmZa5y4pRDQw4aSoTYnahxlercTqJFkbLIURuujlobW9FNwRovwk6TYpddr_XBwu
qidce5yhnMnuZLuTjkRhkK2ceVkl7CV53djsjSZrbRujxku3lpvJEEQ3dv6v-YN0LC8LCTwTgL4npqiMp7FEoCnS-E1xgjmF1Wt1dJ6Ty3Babna5vjpSQ_Ov
BtSfTkSnz36yB8GhFMV7wumvisQ-kPVjvsMB0IE52MAYSSzbUsRqMPdHbfTP2Ntkt3DAzjdGSlHG5P1OrySSC8rPcL6oaddElNizdBIckhrzWbIxtKQsPMb6
PLvgkUpTw_RU03Qp25ThO9Ecl9sfOBmCnsKMpVVkTNbXKSO8lTeheLjl7MEcL6RqChCQ-jwzRZyltiUWvguUuJO88YtIgJIZMGdzD-vr-xnSGbH8muT7c0dP
p7xOIf_p1VV2Ht-9OLqYJ2DCCwsuqXVCD_T5UxLk4QfHcz6yp4ekBxYNmxdQguRFgNWTMpRVkyUxzfQbQzJdfPJBA-wZlHdEd8NIkJAZFkThxWHvRzjdz4Dc
r7E-w6v0Utjeintms3Ndg-uDeDpnUZSNey9ZrwBvtZq08F9z-pd-ciib2w4Nt0SwOFapXON3guzTZz1BxWnh69ahJmaNnU_GMYubTmVbs0zhFPpios_IFcVH
lQEdWpDJ95RidHTM-cPUTGSq4yZC3eoLxETuVwLxphgx0c1hyAkxh3tZP7jtfS_vXZi3Wm3erTrIBJED_SrmZEehVSkbxkw0P2f1CZieKy2Q2dit-ocFD-cI
UTqzEo8p3IspGp85L-pzH_lWoahtd5KqRsoMeCmElxep05t9tWflqhCEE9x4EkBktW70Sy5-5dAfei1kfnZixZvC05guLSVbCXqRJs7GkBjhAhXbklc1yXwp
J3Bkq4FEUtRqgxjlUsOiP7zCw1rFFBAFD44J1d9pxtZ8hzklXpxmn3vx0W3Qt1Keo1yUkc77Ni_CEjhc3a1j03aa5ktNSmd2ZbzadmAvktjcGmemSi5-FPTi
sF6Rx7bixdHrxrTtQWloow4B_eBSdJnJqOVWuGuG-uBzIkYA5z2yem05_UY-y4Qx5BfZnmlPDqfvk6iAEj1hzkkv1EDb7jcxv02RDTgcTmj7Ak6iXzvHekS3
1e2M0hkwaxyVZiVoBQfb7mpqkBaFp_5mBzeltA8Q_f2do9kxRQlp3NbVlqNLx3VsxaQWaLVq9NlFvLlqVlRwvCu0eNjcjkUrKmXzvHOLjxqyVUvm9_HCHtyX
dELRj9JzngDttxI7eFyjUr-_HUlPxsSLFUclfyhpa5jKppvuSq-w_ORz-RNAuwWHhMSVVdDdPlHC-UEBYHzwY-hPR-wyDPE4tZMR_ihUZxv5zUp38easTmDw
ke16PEuvv1QjRtj2oq3F3lGS042nwfwC0tcK8G1mspE2aKdz_dkH6qktwC3i1pFVt3iya-dsjIPpRXmteklR_k6E7bTtGSjabDqTDTQp5xsvTm2qbTIIAJTM
HlJux6_kQG2b0W2OMsuSUulMjxrlxXcDSW2Q2lIAks21jUo3n_Os5RRLhe2yxcvOOttRD_HidkDQ4zsRAe_ejsJVY46vFM0oB3UAj-Yxicz0IqUpTC1VSkzO
PZtx1trRDlc2-y3tqvxa2Q6WlxiRpi781mpkuCoDmYqwGVRwzACetA8pP3-O8G_tmYqwHVPz_C5TSKOUsVjltHrdnND7wQkBSstxBDoYqstxmYqwtROltABJ
PL-uHQVBld2BJfTzuHQTBll2BJfTzjFneR0nZkI_
}

sprite $image264 [94x69/16z] {
jPK7UgGu44QbogdlVzrjmBOc57p36l_EwLcy2XftCeN6ZuKyGk5ds6WH7X4odsU37coFS7wOFIN2D_Z1DtnQ-CvUV7XQUApuK_hdX_2_yF60VluGtl6T7XI-
yaXvOGa_vIjyemlZElv_oylU2FTdz6Cdt3l-VVsWFSQvgSHD_LFE47CCRelnx_hvH8hZvtJrUETROz-VROgQztp36yBRhILkGEORtxjVkztXlXuQJGS8Wkpu
y1lwoS-hkGVK1602uq1rQGhKwRyMxfyssHX9Q4vWciBji_RJ1NhQQL__dUSR228mXYgiJNHHtYNyiffJDpr8spjXeKPd9_DSUFXwHbOypYey1ziyduzrjyn6
U5zDNYmnQcwlwFNFNdYiQax-bQTToq7FDupq7lxLuWg3lWmPdjsz7JyZJyvkz77mhR20S-yG7bsaqhkBfLwHcT4bo-SW9H3dZVo6z7EEKStvDlQh8hFdksSo
cokYRAx9gPLYFJlhLRNHp_cCPEw2H6WwEpXdkf-m5xtNKwcaxauQxS71cuFx8MNHZtHoAbNDKsvKC_9WBteS7rf_U-SteQYuaBBe9PW7lkLpNyrhzg8dZ7Fz
dY-7jffz5_v5jpdzGdzKILFDNlXVz28XMVNjLkehSC6ryanAGu-Xp0LytJsVUvSomxikhEhe9OCcvgImKZ_NaxogsGblaXkTIo71RC3q2ptbq5IpbxBbzKAl
dOQEOGC6N-kfHih6Rk79Ot3KTdx5yE48QNx1T--ajEpIUUp-dIH88yXj3AipFMqNzbBMZC3E4vn9De71D5l-lmiF_6DfP0KdsU127TZewOJtxEHcjjyX8Dhe
OzgQhkRuryBRgtT3gOAYGkARVwRdMehDqURGpqEK2bYeQfNtXl0cItzQAHM6KI1lNlxKuxkKNZYDot1MfakY6naH5cajFTTTMD80E_qxFSFGfYpzjuNtTt6c
Xx5CsCgxLlzL5pgCFhr-D-P27wAhUsuBxoDPMJeGPHWoMMLvPEQ9SEufr_gDIOOYCnUPS6MUhQlRGQ_AsEb3P01AGs-4tz8lYkw6xCCM_NnwxkfF1p3ot6jx
jQxkPqSwXw2FMFJpTNLVVrR6n9dlDDFppV1sQ1cmw4lu0vcxVblqDJsF12oFzElg4VtljCAVqL-PpVGyfpzVqGX_JFzDuVy1
}

