sprite $image295 [264x192/16z] {
xD0t0SC000InsPFveqtzev0gGT3vTiVD-VUEiJ0MeY4MOc4iH4CinC9eY8LO60lH40knC1fY8HPYOJJ4GYn4mrY8XLWO3R4G2rVkxKIdTXs6ml3Aq3WBUF_d
lTqCMeAIAZVsLj3vppnMVE1G5-6GsAXWWJaWjZCWCECVbo3tE91_Is63mz-Ju5u7_dK5EMIwayEVb21tEgZj2liTzaimnA7Ni-Psu3w59GTxT2-rva3kKLXn
E18-IhK7EEoNu8f30w2grs4_1BdYKF6zCkLWRU2mNO9SSZ3yhCquLC063bibo4M7WhDysADMS9Pc71B0WSDE2IuxQ1GU7JYRS30W3nmsGf0-X_Rzz-t6GMDn
31osIP1UXsJyg2USKTsCHLzn83Sht9yFIANMMZ8q9RTr877Wi4U2NeS-NgF77K1TTk16XR433Kg71IsVLVvU0MpTWOnNy3km5wXiC_UJGAB38LQ2GGvaFqf-
L8vEJZWqe3WTo305lyFgtoX0SpjmjuBV0G3z3gHV8TX1lpVXeB6GmnO9RdQeG0joO8n2l4ETS4W0lGxAeH3fqEfN1O-EiOF-fFWS_19Spihl3Xa_IfdtLM6D
7AmyLOBhDG1sww0cTwonGmEIFGs2ZYeUDQ-3TgonWoxcauXNq0jRvnoqNunthB53qSNY9UWguRDySR1hWtDIfdRde8iLHalGMy5doRptaneBEOmkraCX653J
NkrpQ40TEMXqlZB6IJ0amrU7oq4xbXnkrOCa65NNtFulXsxV0c2VZHrewuS40nLwLGfVfH_dv8_l-ZU7Yb5V3eTTQz3Hx9Rm3i6u0sVvwsyIPuOpom0gvnqc
IkQKOBo3Uhw3QdH8aFiSL8W3ZcK8ybzoCAvqen3laC-Op-pzktf-ru8TKcT8yGxb_lsczei8XyBbNbvub_-MSi9X_foqszT4NLTuUttrIzpTxCOxZCsN5LxV
tbxFt13ZvUVf3dNrta6T2Wy7lyJjCYm7ovV8gvIUpggXGzP9l3mIRt9m3yTuMaqEkFIhWm5bpi5axXW9ESH9T4qhLnqgS8mSHXVpACWXS3YQJiXLXmJqAGTT
p74mo25MmXA0HFxkO9z7ctwuE7GWSSw1vhXvUX6272A78w5msk7Q0HmJ3hgOQoJa42_Hw758WCqxiBb7GWxHm-5o01Bd7RmZ8GUNXDz1-uMUpYuuE1Ja43yS
w-Ta0IpSONmmoC4b4Uy0W4zqaCAzWoJsE3IWB3WuHa8E2syI7eUMSnuw5A25EsWa5Xma4UlmbTLQBmuQYtW7AKmu10_7_Dwj7Ml1mJ4ISd18X3jKe8KwIC7X
eE48Tp2po_D9xLXH3ZeOF0wIY7Uu_9vsh707AQmvIEBv3jgnmXmq4cu7ISGxOB1ZnJbe9FmE6evmXt8z7u34K0SfE1py4lVFetAZ_ePsh007AGGwI2BO0Vdw
6LmMuA23mU7Wa70x0A3RGGU3mo5wEEu_Vb6flw4TAyH12Wu7XuJdVj8IMeo3HYBUGHBFSY0x7GuEXV-wkGiR2s8WZC4wmJ7qN-tHWod0aPnuIlYq_bUOSQ2V
17UO0mup3C01I227_wa03c0OaCF48RmN19803aXY71wUy8t3wYJ60SRXlQl6anW7AE4xJ1B8WKde3gC07QY4x333m1re7FO11UxWIqmI_Bw-baY82cyh5Fxl
v4zYaGA6u19-4dDo7Bw2B-4Fmvm_4tmOE8C-4tuIRXn-4eB40GhoJFZ3OC-4Fmnk77uIWiGHIVWpuIVXpuIluCVX3uCVXpyCVXn-4cuSVX9dImWAuapuIVWp
uIluSVZ3u4lu_qf_9lma_9aGaZWq3al1b_27mO_37mPVmXy6Nq98ue1_g9w47uUlu4i8mx2fX30Ccyw4ceGFCISeR2aXA6mfqM3W4bWX0a4LAXACeID154eG
G24b0HHI4e0X9G4KKX108IK1658IG24b0HHI440X9G4OKX908IK1558GW24b0HHI4a0X1G4KKXA08IK1558IG2450HHI4e0X9G4KKX908GK1658IG24b0HHI
440X9G4OKX908IK1558GW24biO723m
}

