sprite $image328 [346x251/16z] {
x9rPTkCw30KDJg2S_Q_tJVXm-tKxWNGg84Fp_cTGEQnp8LBAxST4gfORdvsilNTD6mISrBgboeQ1Yg0_KYYsErAq_nhDcmcItFh_qm3TldtaDwwiRhTWBP1k
TqomZv2wtKthERnkjs0vtUwcvOcUrkqUPRrfe6wtO9zJh-bsDwqOtMx1yWriYo2-WMskblPQ2LkmBX7m3MmtBLwtMmIyRdVJ0XhORbfGNkxmxas30DrkmGAw
tKsBZLRPJGi8eDij0aYtUzE0r-rkMhnkjs1vtMx1RjtoJOjFgsytyCO8Dl-wChJ85YmgrwnleuHKUq2g_A61jBIR5bfYKuCQs1P1VlrZjUocHRLNXsvNRrhw
LNo2JL_-z9RUh6bzjKxbWWWGtSulM8oidokls_a5ovFLAYUQYUPL1SkJRN9kXxYcHKN0sq3poVLJPG4H46Jz4mAWsvMEPrGdsUkkNMZWBTf1ik1jRi6L42zO
dkm2kcK4ovFbTPiNQ5e0MK2t-C0RBrYUx7ih8HbNZgobdCj9PscHLJSDwkZbrVAYkuTrVETkiapJYYVBwtR-JOCwnSbeBPEEiWpP-CZCkYszCsJ7wpPD9bY8
xDOj8DWuildaijEyW613oChfTTVI0Y90oFAJOvD5ZcVKwMuXQP4rdkcSS7BKlCBvjpgbprgQKx0ysNYVLPbDi0pP-7K7wvONB4zMpwKAjkuqXne_d6m_avRH
TTTId0Yc9gj5uCqwhH8ZWhd9-YWKdUk1FIdzUz8eiYqXWkLropUjbhE6aLL0i81k0mHhpfEY75bUi81kQS7wdISrW6nDW60H9G2LshzyKkF8yeBrHzFurnDf
TbmKHLPBs2EKLGQBe8ZZst1aCoa2le7nWdsEjCjarVK3-Ke0w1PjMibnTIXPPIqBMPrlMkubwIVRqBETZ6xZHU3ufXHPl_vm9VGItRGyLmUG1Mvn0Rhb14lL
oWQG1OO5GBU0O5a15PwiAM6YrztoFzevljDaBHgjX49i6j1NHvErjEW6bW4Hu5Vd9uilKIbW0mEuqhfL9zbSpYJVmdKBV93qTfI7B1--WM7oOVjbF5bUjmdu
177T1f2DrgtVEaaknLb6Hf3bTQjLBdnqwHPnU7WrtTgu2P05ifPkat5Td6oyRgLgNvfiSRacTxPlsa9OcwmFhA9zqqJ0aztlmspfw85aPTwtDD4v_aqSsV8s
Rnw_VzpTQDF-9rhk71yVHjR5Dct1-haQMSliPELil2qMvth_U92rp4ss1Jm1GiIuFfCzfYPRWPkbGI9u9ckPdYo_VykBu47MoRRcQ_49B_l8ic_qv4NmWgob
ez7aMvSAa0MEpW4YU905q0A-0yYE5knBidws_Be4o0Bd4Gd1FjAFFoPq3wn3P5iQrxHSP2rn8W38ZXQ1Wwm3BLny0BB04o00LnzPIy3v68nihpAeQJd8OcnR
zjvY8iZwJs3dW3zO3rdBDmkMiq5osIU8gv65qJPlyG780YVfqQRb9skXIwmL7vgiN-wOO1raORR58LYUhF_OB2C2XEo1gVRXEfwit_4LuEeZoxDjoL5y0BB0
eps021naGRPLJasMAW3P0DqQLu0igjlKUWV8KcVD0H4uoV9Ao2-Q5a0MgTH0qtAIvPMG72BmaItjJ0g_mMWY0CXYkdLTWv6DJr60Aq3MSlNV_SUJnNHhWWN8
mhgjsWUHPNHhWWN8ycmxIPPFLa0405dBEcHjVW54094zLY5hIHKG0K3MiWfPIsw0202obfz2Lfpj5k0AaBKiHHOGB4VsMCO6gG62fSXQbY0h5H01ITQoGki2
H02JjImmAI1SURB73oQR6YG2dgm58Bk0O6cobkybc-kvP1TOMB0yMSktaYt0xZ7GjEB9MYOXgnaGB40MpGHajGhGj02oT4QJRGbeMWXPF35aUH7mPFaC8wi5
Q5eaMJunP7d1ycJ7iqqEieXW7KqBIQy1Q6col63v7FacRG1Rdcnn2LQ3kDvDJ5dZsV8sQ08qBIWgZryxaYrFrb8442oGvsk9rorFjckPGR3bjnyToPOdQsa9
Q5g0O9-JGvN0axLK6IhO5vSnKhS9Um2nYFjU8T-qNaNYTSkJxPg3HrdB_VFYbpI0BK3MgziI9W97wnkZX2oV9ryvQvuri6avKle8jFfvBhnTDtIKTMN8mCj7
HpMjmRgDpt6FQLfpwPPFk63zaL3TyeaVPVr9FrQtKO9jShkOlziv2zo0WI28bM7-_-2AAohNEbdnFI5WUNOs4U1M0DWJWPS_vqthHE15pY7JkXHk-TBW_MXm
wpUjyxYzW6dfSNjgfYN0hGMmmE7QSmrWxx6bVWTkHvaMS4tv-Q8Pi3u3yvkMOBueYB820nD4MI5k3QPbnQtRjFouFRMU8SUjmBIqk7ML1gx0Ap0j-3oyGkSq
280eAy2j0B020nD4MQM1UKe3Fsvvm08W41ZOWIyDheNRLw5fAHPgNWMbWGMt0jFIubPWMbhS2cPQMjmA02iDlFEL1fA5cWbA0sVWdG2mJjoE_jBWihYT8Cew
3Mo2cPOJjnEObXEt4qHPP-2TmBISk1raMk5s0HPQ5nzaMk5sK6aGRXS880ER8Cew0-yohK-kxL-GC4EKLUulBi12VwWPP5hXTf1fXTj1KJRSBjFw7cw1Atjc
FSCVU2d05dWpBMg-I9bM1lO34FpekePRAig6sqoBcY_-1h2Tx-2MCgrm-_Lr_Prf5NW5Yx3IBqYeA9lT1bXgNPpwFL61bpAjS4kriXaOLHeKUAaeM-2bJAjh
IvbM1aQPLWP6cLP8e01RuALAWt1BcLRpHGgmuPOohN1BcLQ1TwRIu0q
}

sprite $image328 [173x126/16z] {
r9dNTiCy3CPC3L9A_Fwl--zfqWTHL3KgxdkCkkZdTIn0ggNZXr2ijLRb-04aQtzIZjqHRVzWUVC2sl_GZTFDrYvicsxI5c0xfYkrENPDjrYxHsN3kRgdRZbN
kxTGsajescYkc2eRpHLJjfehJdUJkTevtJIkMefBTu-vygZy5OwL7UQAQ_th3sBfStDb5w82BZ-jyg6vKlaVXmGBwqUaVcQkzBXmBI25nLl-Xhb2MRaziTSM
qdVC5SlofSlDs9AvObaBno0EggoUApwpdXxCLO9qv-UAPOyS8mUaks2kG1Q0T1VCrQoidx6oBjPvMPzkMZ1Nyx9o7E5yg2oOAv2T-DyjqmKmkiMhl6njkMo5
1ud9kM9PZJ3D2rxbqLonR0lecbuz7UNhOlK7iEC2t1jClCgZkN9D9HsNBNWwtarN57xbR6EoAXphVRfS0CHKXcJzQTBU22ipSwKIdtsMpUyjZIMQgvShIWQo
-5p3gBmtLpNe1MJvFumf0x7I-Bmiss6xwB3ZTrVnh7jPjOWgxwMhYUVAqtkWcwtRidVHFdbVWEajAQX7rx_ZBVU_NXqytZUyaBJims7PUO9qxSLqfRQsYIod
6syg8P_uYDBxeuFiDXzH-lFPV-EhPLEEcVcCrX_d-Un_yBMorWSV5PZ7ytp-SMQThfPxWbgTX8RRCrN0-VoTVh5rq1K-gR5iuniPLZqVlOCkdnsGvKS5Bi39
nhfyLygoPJRMKBQFttE5ilIa8DO72d2og5l30a2MRznvhW9PrgtY3aUoF0LSG2pBkkKIAyboH5m0otPOWyjnJFYYq3ii0gXwMTPLyNz1BrjgW5Q1T5q1AClf
PciWEu0eg3fPq0L0baZ61NXPpn9PJt5pHR8nAsJbSAWl89O5vcMPOhw0M9POBfilgY0BB9KLTGM0B34ecqj4BO5gTQeeou0ilohkhGeKC20B3CcEt67wkM9P
PaRMCXV0FFeNw9AiXKzWhW3YxCaUaxeiMpXMvZmj7KTkixQOGPMxM2FNMBN_LLATR86RjGAnakkZ_cUPHrf0sTeybYOAUEh_3Z6KBij6gCHpnGKqDtlb_NIr
_XzhCINv0bZrKGwFJAGxm6W1zN1CfBjIzJGvRibj8brWOgxkA0jR69yhGlJNtklZXc4WY6BerM3__JfU3ONbBAS11n7lGpk-hk3g-CG27vpaAalNStLyZZ7F
rS5fnWAk1jCDk3euiS22gyknwWKEk9faJCPwoDKyOmLNWmiSS3NCcEUgIrTpbQORS3Mum8AhFbq4LtcwT5pv1QRZoYymWgky1GnNDMDqNFa5fkJAlWCZkChJ
vOYhurZxTD5SXGkCvQfSO0HNEzFzsmA2gvmn15Vv0YEuoXb3S9KpXk0gJnV1LRx02AxoT15SbUd-lgpWAbzW15Vv0YEuwjCLNEMCyTWIwmi
}

