sprite $image95 [236x171/16z] {
vDE5hGD138JXvN6u_seV7auEPD7Apj_1PtXr201U7n66FaSA_rgiyYtbV4ivtrBEDPNpBULyIpdVLCwrbFCYzQ-5EjzKphMKyotbV5CvuzBc4ekjSeZLdHPR
bHX-IisN5XlL68Oo_6YnLGfpRWuPMxMmBZPWhjNVSgx6jDYk9T8c3EKmLG13MkmcDPAsl5i5PhGuJ0fXOmM0I5OJM9oNMTiKLi0I5T8YQRF62jYG3aaDbCeA
CzBjjrLO-skXBUcid2Kgf4MTbRCX7PAYit8cf2N-bwBEsbyBTJbGPrQvNWIRzPFML1hEIpghNAu_NT1PYtNogpZtHfNrSXsIdbXm8WFZs1iKra7QMultP71i
U_LMkQwxzD5-4sycEXAZG0njmbKLal__tUtiHSjQFCLOwhNkEVD46JCcmuv_dBSTJDN0g5EQRNLIbEU_byVRajUSoM1yKIR2wgXesVk-JxA-L3Y-tnzaJegM
lTwmru7pp8Kvy__Jnev-vO6zoqHbl9nql1MqxTTFINwy7ja3QvDpyjRE1QJMkr_Z-xRj0TdVWCcdQK4frw1HnzyhU0AjECWwAQPiVjDU6JWvh_bY_MnSNyoV
t_orbi_xhg-bAXjVN3yV0vTSW5LHqRAFohXzGNhGyKLQzF45g8HM9-MMdMhNVyAcwXRD6U_uwUliN5yWHSi-IkbPtuBdNaOwa1PZoFgF4adZSa1x-_OJFvlH
d7cstQK6E9N0ogWj1oqxTTnlpONkEBxWHDnsoPv49P3E2YNlMVOv7yyjYXlrEc7R1TAFKqHBFpw8H5hWgfXQTgguBupQVPMQU5f2e-RGW_oQj2QuAevPTkfW
uui78ZklSvap9VeWGLH-MPp3bfsFnKYH5Z_zILhJneD4I57r1IfpdjuwqgDN1SjE5PweECZhdC4R-jmLseshOkoG6bYMv0oHTUT6dKhTkm2xtd0oqZPa1Si6
SuO4AYGgleXGtOIxFRwz9g3Dm0gMZUKC12hcJF_86Jn_kN3RjNzLN9QiPe6S6SD8eDBnFP2KYvA6RRjWxTQU1p8ZHXqEWReUtqAszNtO7f8PkPF1bAL6nK15
seiOjJX7vRJ2LJ6mJl6SGLe7evASCKxAQOMhOi8Av2nGEyiPSlxQf-sxihpBQZHGkwqFX9Wp0YdCMaYjjhh3YZap0DOXXeISuJBVCNfw4GKBReT0NUVCmN9c
Npw6Rz2-c685DmGga3ev46gaTew75MWrLbvmGw02gfepdFHVrj3PicsocaS35NC6IBC-lfCrjhHrZnL8WNQSyPoHIO4rG5jsM8q5AiqPF8VAHWNM46qjJ1Oi
k8qMt5NF6IG5rY2iKKKBRjye7dIZ0YlGoW8K2DIlvWnbrMdHYHYeyU91pnd6gjEY4qcWyfmf-lXILXqM4nK2bUKCA3MHbBBgj4u3TSAIdE6qhKN7bxBgj4O3
bHVS_5QwfPH88qn8aLMdvObg6mKtgi21hUoEBxBgiBpWzfs2knLitRTORGpAgjDYmGsmQ5HUSDi1z8ILZIzdvRJndF4nb88R2xmSP3KVGs9r8xHB9_erXEB1
h13_4gEghEwsOrG8L59mimEXMIQiR7mvgqPxdkIDCw7WjduGLa9AMGLQ_iRWgHNSLbEKrKT8Bi2IDmQrWdlvJqk5aUgid7Pnq-QyUC2S2HTRXOolpiffIJ4e
50-Lid9IpYhHacsNvGml7WfZnP4IM7NRwiL39gnaKJLMVP1_LJmSX1L89LQTLY-u6_pO3y7uAgowRVzenYxC8uQ260Y78olKVxLXFhxdySrsy7-hDMYMWZiR
vvSKj-u-sxi52sxUkZl8VC4DM8_zR8GBxcEj03ODMN0FM07jzk81akwUfmdGSWNt4FLrEEtr_kyPNlev63PNlpeo_51tKz7L9XS_nOD02cjlpu7tp82KrLwF
lcTcbD9d6y6XygiTdqo0rAaTbsBQpAjD0QbWjSIXybfJV7cjHyfheumllrg_bDVoyVLhKq3AQsEFBxzQFhv-BI_bjPxuyje8fVng-VZwjI6bosiJDhworMBn
LMeHgLOBn5Uh3I0LhnQ8hrqRGAhK0l7rQW6f5Wj8jLf0gjK2L2qMa6grW5Ih1QXQBI3LOW6fLWj8jLg0gjK2KYqMa6gr0DMgBI2rQWj8hTW2Kgks0DMgBI2r
OWj8hTe2LAksWDIgBI2rOWj8hTe2LAksWDIgBI2rOWj8hTe2LAksWDIgBI2rOWjGhTe2KgksWDIAxKcaBm
}

