sprite $image420 [62x118/16z] {
fTDTqZCh20HWdHyG6lU_tQD5nJhV64dUsFTFJKidQPbCvKo_vX9LvUCdUnPL4L6vyvzjfcOzMgu_ubjKHlvO_omlEpnzM_zWVM1__ZSsU-cPwpVh4IRuxVCF
5W5qmUFrCedsXFvQu4iSISYr7EzA5-qayD5w3Ea9VBGU6_J9Pp-lDpHc7wqtwS37wx6PpVppUaFNoN-vdklwTtyFNNkSV-crbdzrrTBzD-kfrLaJopVr5RNQ
f8MOYdxqiDhpHZEvLrsjrqklT4jGtqk7cea42m-haNPUuFpXX_sify-huuMs_saJVdX5DGIwDa93fnF3-wL3RL2Hqhthh2BcNBiDjVadX8cQ1ku3d1WUgsjT
pDnstZ_VjMdJ9tox6ceuVlckOP3Zn7dg1qtFQKHCBW5GS2QoM9-AfxT-DJH7dtJc8ezVbg9fC04e1Q6-cRYe-w5HBb2w0KEehuQPMDmFRJ1A9rX2VNJSUFCO
Ng4Aw7tXJ2NGcRfsF-gBcXmCGDStjwvln-xPlJPT-irRIbxeQbSw1txLRwP7Zmmw5QQATze0EGOSlWYS4oXTgvi3g62Y0H_rOSRfj9lVQ0EiLgZmnCTwG26S
YUsXtJPTJCliVJtFDTtSRGiOW1Pwuukwrel_qJPmnOqUYPxVC_ImFJZXaVVrzQ6rsn5aU5RrvV_wzOAXas3ugBvRgmzT32F1UfDrJQwZ-YnDTZlhstNekQZZ
IPy3HlKnITS7ffId9waBdTL9K9zANUaa3pgjHsnhpUPW-NpIkjQtwsLzaXhewwqTzOajqiTIUttKI6T5aA8rr4aGnJvejXrDM_hQqWV21DgQplgxtZYwws8x
chRqjQLFXFcWyvPE6chxe8ljQDhIzyzwv-YkyuR-zUX35zlHlANl3VtZqOS-jdJMK5kiazYEvYrzR-aBl-cDem-TTKSd2RKjzSx_vAKls8PEcJTqoocsvB7s
N6eREcN2Us-X7ZdAZfxhnteEmNxGqNeJj5fnJtAnNfqvfNLkjNLrgxKSQ-lrxQc7rJEqlfxDkbkxGpUlvzh3UGbMwuqFon62P_sXkyNrXPdNishXIl5wpSOh
nUj5Atsk_wxqVm
}

