sprite $image282 [279x214/16z] {
xDK73WCn24HHTQy1QUz_slGUasZImym_mZFW-VFrTRCQg0nWX9Au22M1aKeA8vGkc9ubb2If90bbd52IX2AO3YMKSK99ebMPY65obDOQ0CE3iexIfMUrRS30
a8mA04E4Wi0Gef2TcFj7fK6RH38gE0m32jycTM1_EWR3CIez8ZgsIGGe7kjymc1geqmRb25Clrtbes9ncc43K_UeNDOncDBxSmm_CUNsnsESOvzrhL6nIC8t
gTXH8O1vwgWyVsAgVSfvXfsOaljZRKcTcU16hiD0D5v5idJ_y_wqsOXWH4XfclI7NRFlunVLeoJlUq5cavxV7snVdiNgANWg6DuV3cKzaApx_Frru_Bqyq1G
AkM0ihzuVNDPKnJpVAaSIsN3ePAlXYMacESFvVqRnMnDC4WOrlhyeJnzKq7habLi9NuUUFYcrdM2MijqM1V7JqphlauE9t3by93hjtxicCi-dVLTAqy9AkPX
KkdlMQRLJlDwmHCLaxhJDstB2Vi1IPzt7eXB1SlNQt5qkYM7O_R7dQpZ_N4idgsUOekBrmcjhc6DWNd8zPj7Erh5riJheycpnHJpe9icNNxsjYtoaeg3ilaW
9BwTaRihHWaLibJ8hC6smvTAMpRcghcpOlIloF1gESqQIEVmsFebVY2uyR1M5ZARpxEc4PYBobfg2rx79BYQtu2i2-OEJTA134mYdpMdRSgHzRpnbP-kpVQY
CnM3bDifHiSYTD-liqlZ95e7TKAtxQlVm_YQyaoubMAKPrmnsh6lzUymf_tD0KVpfd8hnIZ9k6BwzfNEFSA-xktFgVi8Tte5gVyQOOhfFgriopmlM_-kzrop
j2k7V2ZnOOrctueozVQqJSgptkaLf984mE3zj6rehwBb5nVdLUWBoF_pFA21q6qljgzoBebVU2-z2t2-LivHacme-Oh1t3QzsulFkK9jJFLZNIWycL3o5UCB
OcqAdb5F0UqFQL0g64s930phnQcqBkcqYEzlMA04IZ8NJGjhakzTYihwiuNnqUC-3ac59mbAlc9SA9wfe3cOOh52baes65EIPCLWMxwpoVcjT8b99HyCO048
mVD0rNbaA5Ce-Lm0c7s-CcHCCUJcBZgKyy40du8fdh4cWTpSnVgJ3mOU-rmYOqtIsZyxXg7O9M001eQRLSXgyTZl5wzhUATljU8ABl2G9b5xT7wLAWRXeUoa
hm03386XZzrPAgn9qVvOmvpU97XuazXp2u7IQL9iAED4qNAvu1mBWP72WyfZGr9foMyIy0cO4eWmC2ZZ_V7aDmcUU9Fw4N8U858X_RaE370X625N3eD3cKB9
LmowiGmmmiy3SQbSf1Yq92k6NZa4XtAziadmf3T91WvAWQ5yDHZW4Z3_VkMWWVxaAmQU_2R9uEKT7yeSIhvYWCl0Z5xUnQMItoIGX9l4mGIaajqa9LWkLGoF
HlfZ5cyIIAvNJ6P_xFsNXy40MM0aefXuVw1oSdbCCI2vNZ7n_i1woWeDQup6hbSC7ygSY2VS9F345IC48PCA9zBFnqqoiCIR9EItZae50Em88H9M32gG3uP1
QHcM2jfI5K8ag1Z_bq4ILOoIZFG7DkBg9CKOAi4ILumeZP3-mBGRyPGYhwGr2QsmkAX9eaEHBfJnHx6JVlGFC30EXM29Wz7FOiC7uRwS8Lmnd2y9QL9wR6of
_EbdOuhX_p9mAp2ed0hdKfKOXlpB14kWIO7-S2gS2uGi5dB6G21cLq7XLFY34RLq_smSInmCsUa7-kUnmVuOAi6I1oR-K7_i4qNOXzoZ8_r1xGJXM7P_FEHK
eR_JVNFB-zCDuZ7BxO-7dRNeXxs5zoUE9HyC1jzeb0-myA7S3t9YIVt9nyA7SXnBFfZQabqYAfKeblmcyNQFtiwqf4ZbFshjGqbk68O1A2tRMej8-V-lJU78
sdICE0DFXFHoxPr1UhMNO171y0_djnCelg3vKkOimYRbOTfaa1igUHOz3CWdEcKBqXy9Ytx4U9j9OYaBM3GZ9k-Iw8-8HTyaJvYIfQnagQVcjXV9-UA9fInW
EMrxFJHYVFw5d9WBMSnAUsPPmnbAOgZGVCwoc1t-r8XnWf9OoepbSuubKeLDuX-kEz9BcRC4J8x5YZ_uU020tm6GkDEVO8aaMFOoN9GZXeSlvHnBP9hbH1qk
-X73GuPAWYKopm8lPhO_UkIGENxBiqIcMO33p5v0lPuPCTdZjpnBP9h5DxCDgBQBxcB4GuMpH6PPy8ertUAYaS10F5GuIsII1PjP0SpiU6B4A9OoPubCiSHq
QIZH9HMCkZ-S9JB3KgC_P-3eZXp4_U4iaGcMAtvxZU7Y-YRnfQnWYKonx7WFbwe-Sk1BMSKIcM0fG8cV0HJjaGCVAYeM3XCi_QgemH9_um2QnTNZ4XZmeQ9Z
uIvXqQ-A4YnnqLnzCLc5ziW1H4t4mc5UMy0STOzV0E-rYhztc6sN1eOC5IaBX_7JtgbzfemEmNIdcgG_MXOEqmwxqtfxHeTWaTC5CAG_OXRkWgjOPByV75rt
Xs3AKqqzIh3aOMeP1r5kPhNrIGExKveO9eQAY2KFurS38iLiZmwzEeiVes729Za-w5XuG19Z9Jg4pWAqCbnKC86YPyd3LBF8CLZ6pHwDkwG_UXOEqphBTRCC
h0eD34VHgt2OBLGst2n-_wv0SUJWU58bxtAyEuG0gdqIcmk-B4Q9aWaPBcsmn7OEbWj8mApH7mvpZWx1Uex39bW0Nwy_7COFEzyifqK8Im96Yo9mGMjl5hIz
is0cxelrXyECT8mh9imBIC0iY19XBEEH4gRZ__5GuU4ig6G_Jy68KVGk9LZobmlWlbv_E4mr6q05gRWlrnyEu-TWCIJZo_M7ku2oyBWlq9yKp45OACogAFoP
jWRaurXEXSECvzNoMH65kxHYLS2YHj73l4u1oo8g4IYYGbaSHeAolilNTkYW2c401g2OVzSOwEqNsF8Q2Vb62X2plqB4RASWByifIingYXEpk2B5hALOBrif
MCpE2XUpakB5z1Jo9QUOCN55ZMafR4n8aL_2YXmJKkIOa2A_X1Gv9gp8CI55ZWafyaj8aMF2YXmJKkIOa2A_X1Kv9gJ8CI55ZWafyajOaMD2YXmJKkINi2B7
X1Gv9gJ8CMFAlOmh5pEcNCoOSZ7ZohsCAHSpfbpCc78nuygzZ2aNyvUK3m
}

