sprite $image421 [271x276/16z] {
xDXjSaGf28NXlxc0pVvtEsFLdJbglapGYgURTmVz1BmL_1cJErNrTV5Zr1BZraYFDs0qvPuCvPxqFHAZxpKV3T5Foz7eIupN0n5eJ9IFHjyZzwGlzwJF_1cx
vZ2UVsFgxn6al-Y9CEuQZDS5qMMbnb1Y32L6Ns8CfSPGOlJnOgI7wVvoDFeIeoynkbAZBpNwagClDVfIW-LcAFe7vN2qMMeWiv8Q3KRXv13Pe55gX1eYrtN9
UemQamOmQh9qJ-x8DEH2iX23ZGCOgq6iD75e06CrY5avd6C60qaKut2EQOou1p1EvNZCOI2n-6WWYj6GBp3cDUpVHemnZY_A9o1gPZ-R1JFhzcICGKC57aZc
CVgVRxLoEeT-aTH269ETZm4FQJ5-jYUpCMW011XBHmDnO01a2mPYEefARGS68XaDWEnuD1071fB0Q9pFeHi21Xs7RCHWv13PT1NdvAZjm23caAKK5j2m0pXg
woXgd1ZWY8DO6zcY86cAKY1M3PUs80KYmq3I5w90d1ZWG04AnAe13XJNCBBloSYXUf_w9Zsib6KSVb9IQ_xMCo1cPHc7-L41Onh4Ibd5ONvOebLZnWCOopZy
j0nDW01Z1OTHOC13FdWqrd4uYmOyP1oDTHn46Bq7C1PoC66q7e8z2N2mQY3vFup6StBOJDfuM5dBmOE1T1i74mRIC0U_nduEuy90keM32MC_1nq6qkKSHgon
diCOCP06EBWnzdFu4JrCQ_Qhrd6SS-yIgVrAH0CSHseqgVuLXn-IIjVFFLPm-359BGAYOGu_IIFc4USmFoY9USGv_7GDUEpdyBEIW4USmvo3GtGp1p0eE4It
SpXA3lUZEQxQf4USmmzDWJ62w2QEXvzRhr7RoL7yyFJ627Z898SJzDPgZ1xh_gDragwsqKENd7ySKMh08tGSB7Whg370eP5BkfDrVTuaXwgq7FmQeMrH4N1m
OyXLYuo72Xeud6yqeXmgdt4ufqPeMzpz4mv2Z2Y7U-q13lRH26sB_vSE74we4UNmDb5mK6e4ENnCRmvplkIASVW7FQHoEELen3W-GrPx2OsUmv-hwvzsxGCt
WX28eg2pMun4t_-qpg6TmNcNUaSe_G4SliIHD1uvEeshzdKQCOjHnv7xrgn5vUZBQhHND9B68qUkgv6vRKyrSbsDA7-Mev7tnQt5rd9TZLmZ6hKJ6AL6enGm
IgPHYpaCsmWQfNCQfLode55gC4e7D6eqQZ1eqA0ncsTvpJHeq1WfQDG-fK63Hj0eRJHAvxbO9xwKcctGUAlHByLhjELosKRDMvG6ZQ5eqA0nb0U7ST0OgOzf
64UdOHolHuD6_CmFzSP10mSDvwXF1KUZOHmqXl8UDGxZC8xvvl-HmuFKE1gEwN6uLeo31WuQ3OTnu72G6WSE6ZXmqC21WmOE73Hmu5YWzZKDuy218t8wHuTl
1GUE3KUDnY073XmuQ0GEtmeE74vI72uMHyTlXCFHWGC73lUiYyMtWWC73XmuSE30WGC7Zi1X73XmuC210mSE73XmuFX_THmlml6Y5nnwdGF9UQxP9G
}

