sprite $image69 [90x113/16z] {
jPO9ZkCm3W1vawBL-__dxj1AHcci4PYR377rbJ9HAXaDDqU6mhyOyimC_ZeNBNECaUdqNR2E76io3R_7vSYn9uTyKV1udTBzDS6lyoNTKe8l9eVXXu8lm5lt
rmIFx-X6lH3HqDqGVAr4yLF13Tsjqhwa-rhmvxebEjojkrzQGtTBS4jtGt2JRTWehQkx8RZ93ca8xkgcnbLkw-wAwEjkS9kwysYmMnS-ZwF1xkZEe-RxIeQE
UVmJzl63LjnlitF-J00_ZjhxYxhp-FafieP_LyanVnOPs47pQ-mixYABAm3wqtP-XLlaqi6rULwo-u8tcKJP631qFDaV2Tva7mAeXWWuyeBT5h5jY00WcG2u
-KM1JUucdogOW4s0W69UwEu8tcImG20J134206dNNO8loUogo2IAfHlWekwUYDSJB2DYB42c081RTr_49cF1JXFif-wgc-BUsdaXOlUi0hMdAY4fqrFt7IMR
UqaEXtD81P6Two6bUxzVMu9VUmxb1ziOcPINRjBOkkyBtcGFUGWm0r42K-PJDx76NlksY6t35PO0ISRrXH5YFOtGShDlYjXjY2uJKeKCm5EtCA8f0edlexpB
hJa0E4xouvgx4hBnOsKJm1SbkGNV8OE4q6AVD9q8N7moUkhU5tuLV8-iRgfIcId3iYnSkj5O2ANu-BVkujucHwIhSWNy531bwJObN7MZ7NE1vsto-d_VL0bG
pPS0LKCwTSjwMZNKMRd8uXQPHrZjnYbrU0YO1bNtAgIU1ZYooFEsPz0G6vaPgcTuMNK3iCRfdKWUYKVTZtd_14MPJJp_Z8i-mZi5U5Gg0cmaI6gEDk_wAB8F
Bhn6iKqhF9cqwjPXmCf0pWWyo6Qd3H06B04QTHVeRtZLcxWGbcuYGEVHgawSw100Kh5nf9Jk2ayVkcFK5rHnG7Dd2-BnK68ffRjChF2aKeHJDmxt5fb4HKdI
2L1KQUbM14X7uF8ELRsAIuySWsibjE6mTQiALdW2QWZdw43jsL0-LsAAeG1KIZ8FLvKoLOzLgC6GrWcIA55IMKQEVEfUIkgxg0ilq3x1kdsAEhp24vGHMBeb
ylaoOTVrViMX3S_hbHjCTYW2APEcrHUg8_FWfRjKgB9RD6naiJETA8OitJx-rYsvTDUW1MXdvvfYAtB6QPbeX9G02Qc7bkuQ6Xf7ZxpOGr1Fo_ht2wLwlvww
YsmGdPtdBF93D_ems7MJBTr3LH4es5hadyLUkf6zmcCZyfJwGiu2GwhtQDcelvolkcKCEdLph2-UxswlddlanTww9OrAztgPF2zywf1eaukzTHDwQkbcijHd
tOSR_5_aLzts28-LCKBh2zLqnxwDlVPSIaftF7IFbRbA_mJth0Rpr0qLtgexgcunHv-VaBVkibnHCrbbpeC_8x_eHlR1PPdO4yXfV6JZTzrSuO4goSNxkKdU
1PPkHat3qWqu8ZuZ5thhTa8VfLlDw6FoMdlhfZZ36wqsvYNvDtieQ0IGI-S4ezXNvArxdBeDo5ed23pcdDVaqZqVIfo0XZLi901epdb1hlbLjxX4ZmpefUGT
UR4RFS__99n3I_SbUUwwu-O9_lcRmV0OATsNv5_lroBVu1uAUqxTb-JN0aVUGHliUUY-9lzY5_dzma7mFqDnITxiaZ7VSvFXSiXBzoLvwPvptX1yELQLN9Bh
s_SkfYEy6QgwhycLvRlI2DxFkl0zSWaMk36InRvDdgkqMuEbkx5pu2tirdr1xWk-rht9J-yNfGcqftI_9s_1pK7BET-Hj-0-ktHVaA-lSb_ttEGRLxcdUsxo
hQlSgdkJTscV3yNpvZG4TtGNkHwWyDNHd6ld6uBxkl-Gio6ue_k-YFy2
}

