sprite $image353 [240x236/16z] {
vDM5bGH130FH1djivH_mCTzw6Mj-3DAhTWfBR-inKbBEjWvzqRiORGLStvRUu6Rg5sCVD_HNJlXnly5lRAfuHpQebaQUCd_KhjsMpcnGpPaDgkN47HT-OrC1
UUEHEe91fWo_iUjuCPWDgdb7DgYMnZnkBGUrGNMRc0sgEM3Ae3QvpYy6jK7rZPaDgjdT7nT-OqjTM7HcW-w_JJrq7MdC1jLYy1fqV9kkto3uZSi68Tiqufbx
-y1j681X00WRMHh__sxt91fsA9PSzWF6LIAeBFTMACQuVxWEOkKOM_Ya-D3kpNmHcsgCqPlXqakDtd7niTSxBxuSMhtlOjVj9lJgnnYz-Z56hteteLS_nkYT
N-gbqIlQJTmx7-ErtPlfep5UUhpgtOHUqMv2BnThTPCb1xlKYSczyp4-D7WLOyozaYScUYD0gNPYejSyj6ECNWEnNepHQnwXt4teXH6hdPZexH7tBpNtcdk8
TXDwkqRS7sFkDTrkyY-zYjt4lJp6yMzZ75UyGjt4lT8nvjxlnOFWoxg1LwARk5SqnjmhsKtePNy29oRn2iQOUwMwYNjbObptcdlkzSHSDl3kkvkM3Rnx5byE
PQ_WYOdUEjX7kwda5JenkLUscxXNxyJaNh4J4xr2uaF1gnDZxgsBVJR61Q_AYObUiQK-NFUwcQ9utS2xym_AkLSmnjzxPRk9U_LEJEuLEp7Hgoq-4AzkZFFc
NdFVRJUjnAlPJU0L5tiIhrmtUIHukqVShGMlijWpqIifHYrw5MFiaSGhD-B895uriMSIxvIu-T6n7RVx4pPyBlMgB3MkihuOjVtWQFWD6_nxsyNeRHlnDreG
jtcvkBxAtuEztulYXbM6PtPxCSODMX1tUt6fQwiyBKPlH5NCjVDWz4PngVagpulHoyMEuhgsNupUobBpLPuNenV0TJ4ETnwCtiibVXJZ1cq4Y3VndizsewNs
pA8Nn1jvpsSlYAjQZ1SzCUjUksVMJ9URsK4WYcO3chp_yzwof9bF4-HeRX6hmj-ifqmVsikBLu57CVvWSBq-3H_n5OHPbGCnThG1tW5nd5VKyE8DnDYjSeHN
C22EvnTrgyKUBdNymPMtlCnw1yRl-qgGWGM2HyJnLQODRtaTyKTy1M51HhS7hs96Lvc8TklnWkkc3OW3lkBiApKe-7cC8xIPbn9RHrUS1ue1SS1NUlcAN_Em
OeQiJ7aMlVrMsBLmUTkwmF7y2WpA1LWhxvWOeHj4TJRSY70UICWWnZ5VdTeIG2hlOAc39vUkEMv4ACI5bnazuZWlAmoSVQK6imV4zKjnNafYDnbQ7gdUWgkO
KL_fwIkzV5LdtyO-YlCIhUgNkZO2kAMEyYfENw7rLUQbTDW4tlCsUM919yPnN-7obTnvYH9i0YybxiLOCY-xYXdDhngghmnovoLPvVU9ZTmiyjM9CRZdhRYl
hEShtLwyH1icyFPlasdXLNN4GL_1j6pFFzvzb-N5EuXnX7SSuxnv4BVK0Lz9zfN0u7t5ckC5iGcyRsASUOSnVkuhktm5vwi5Ho9AIglQftZ7jmd2x4qTyLMv
xchWxxxQP7ln4ktuBEyuncButyJuwljAJr_fnQjhyTKkMzxgpMm2Bz7HYt6j7s83uX6loUchSksazHMVla8gl6OJU6cvLKnVFtp5VCwhm0--ugFwYlVAQnDu
YTRUKejWV8t7-woDh_YxhrRib7sroJgHDzl24xVrmnEFURsljEEhjVfA9_BsRrFrbgaEY0U-mXKFz7p5gvOwC9ENQF6tgJPySKlzc1V5Lm8uNnq7f-8h1j7C
_0vU_h3dzSFpMlMLclVLSlbAjccyuzjaJVtmn6DVQV4LVlGLp_MLZx6L6BlwqNpz4Uy5AeQEh_RggtHCyzMuOfP2RMwfd_jAIdsv-Mh9lah7V5-DOwoPro_r
Kr_PwIjhV7KKNosiCttb9nszsoGsZh7dDUNgAtHyjK_prQXYTcwJFQWVVf_nprVgVBLXAxxQUPdDEuwn5bxHFd6VbwNnbJXV7RmKN_5yNuqhfcPUlzGZN-7q
5UJYbTDNnpBRLyyh9gHzzSCJe_S6f48DzUbMuoi-gFXAPljg7EDn_HZu2XrVhR89PLHP9_06RbEEeoVsl28moRwIlgzMoZFTLyyhPbi_777FLtRv2jvNp8c8
Plfg7ECl7sDcCHTZ0zxvwdntglLLohvQvA0ynmJUm6tgru-tlbBdA-Qz-6gJROAVGp5szSFUVG3ekw-auwjaiapWZLPC55wLbjZx2gBLL-9yjMF9_Ienfp_2
wzye_mAwzSDwlFcBMX_Pdg-EbFlLAXDy5O-nCCINwlU-KlxcgxJojkXVyTNu7RQpVjoNsdy-jleAZQzagxwQsg_Y5RFbDUShoRuIc3fVRR9MNt7wJLw46CUl
OagFrm3BS_hAlA_IKNsry3wFDtwR80slkrkDhzZvIdQglkA9lF6AgGsl9zQEhvYAhsHBERzJUUCnll7whpMVZwqZfwzsvwi9lC7Rv7ZTr-1zjVCYsGbsJF1L
S3QxKpbUzxMkhrBsrIgpVHMFiQySFiRULrfzjVr9Nuq_nDMv_asClQ_-Azyyi1m6OI0w0ak0yVslkmssf8V8RtcJp0q-YVJ7BLY9KjfEcCyx_g1yQxaynd_s
LGGo4FAyVUMlcDjsW_Wd2klxAXQZuJrqqodl9M-rVPLMQQTM5XRUmufvWVTWn0-l1qC_jHdxobynRt-9STolrAIV6WzlSrFFRUB3VIMcVHCGyKBotSHzZ5Ki
ITjNATBn0h6C_SGAX9zzbOIE5z1rXBXV3yP-Fr2DZXTY0tzgQ_sASLyTLipRQMxAWNDV7IOE_AbDUh-AlBo0tk-cqgu7qsA1bnUIxX_Z705943MZvGN2W9kI
I6e2tuitu_-pt3_6nTAU-wekc16nWJ5UzkCrmQH8tkuVuvtsLGwOc3WonidFkqOCP7R5zF9MXICJtBIwU9DW8BChPdk8_ZXl2N1aMiMiL0xoLynAvI3_63_2
cnsqKoecbuFy5PFBGVwxc5mEyj_5v7AGls8IECZh9dyCB17p4sS1KKAUu21QDrK5ORGIEyXVCVqE8dUJtq7yOsoWZrKo1_dTLFaTjF_j3yKJHQl3GQHkSZY8
CQ7iuY1-DncUDbeTpuD8nzZX8FQAMHKla6KbT93_zaSDU9c4xEpAxm
}

sprite $image353 [120x118/16z] {
lTU7ZkCw30LGLOeb-V_VVR7YY_KyOOYC5OdRcy-Ql2IGu1Pn3lkhiAgsj5bDJLL4L6hSg4RggdIvx6kn72fWvJtDpgnW8LFSDTYVfL8NirMwEigSTmnsBEpK
fXQl7pDsnvEbB6kn3oldjRlZZNdJOCUTYkjsP_sOozzKdCw5BLwuK_MEEdywHUK6F7ywpHnuuKxPup4fKxpfpifIRhczL2TWvNpJdMvsYxVSULdgFNVhcE6Y
rksKxsxSARXRnmnNxQVygdKx1VTbYcuUCrpvgYmKFtM_BPVFt05UVZgx9JB8Yqydt1Mor0_TnMFstJqx1NUTJF43TzkOuIwKiLE-ktxClhlwTC9TBnV7NGbZ
pBwxydJ2DP5DibJVzMMTaBauxkATyjorfzDn5-_Kmt5TMLLdPBXRNrdj2NUZhFReBDnDCbIuUs1zFC6QYkoHqM8FzbjrJuPwLzO7oZcTJellodhZmwiQr5im
N4Vs1ZiZmpNxM8Ow9yC5x9rE3DPJ8N_iifzilyKeCy2VkyJco6wBxUBQq6pVLNwLFKRPRJ5OWskiW-owhQbGKnkNsTkTNh6TFta-pAYT0zFFN25M4MvYDhwo
FzWG4h_VMis4I6HuPSSLPH9jP3RAVfp2guhYhogZRv1Tzq2vYOW1_YU3TTmGgdL9pPHVi0xRxEHAXVXGEUibfL1zDyI6LpPX9Z70VguwgjAw6oAhZrt-Km6L
vPzCD2RRpzMh9ASSsX_TwvZDj353LiyzKDNMtxU5GY4I_y55aVMdOSpscspeyn5cv4fYgBcMKF_kXiINPWiBJkVe8bSYoiZL2yqj9hC_kEEOLLi_lv175xdY
CrUffLWIsGZxxh1JZNeB1zckkM9kYbn5gY7VS8UT4cflsNHqaIiwSrMFNELomnt7p2yOoPOnLqUOzTqK2Q7cKaAzxrvFf_2P6yWNLzixLztb0oqjf7ikYhea
VSpzZ42-kCpASxdonyndTW33xUYhpbp5CfMhSQSEWHJD_d-kv9AhaFECEvvEQT84iY9NFSmgVEQAIWfpkKB5o-diPwGt-qUkv4UkQ3PNuqvfQyBleutvzZ1V
SXLZpJJhehAYsOepSjJJhACiBCXLeZAHA-Tqyf4X76qpOMP5hcAjnofzvDg8-3kb3BVdt8IGAmw1SYw19jonaa0-NVnAXT-zbrpoiKffmlLF9vuBkPsvoZrN
TSBrJgSgdejVsJjNAPPC9PGPrn_pzRcArlEHgrZpJ9_zqpb-DkXkY9H3IBJ0nPXH5_aX9UTmV5tWudGEigYr8rSXJkVAFvrsFJuzNvB2ySQJkV9h-2XqoD9A
I1JHPxVkkJYTLxVB9UQu85V3JlqiCvMAN7dgiyMRAaud1CYghUVALILDgDYfKLPpLIjXlcWqp8EV3mfVgSZZAyCTrIUdyAtACiY_gPh3DwkgBwF5TS9mJkV2
tV5FvyhTyK_dijtnJ-V2tV5Fv-BTyK_dojtnJ-V2tV5F9zGLk-EVpeMxuvzEPtUMxXG7j_u3
}

