sprite $image415 [243x176/16z] {
vDg7RYiX48LXsi3CEF9z_xUziOsFM6cT00BXc5ybJUrRoXgKVsjI4T5_6oMvwpvWf3k1qSU3MT0U8tsLq_XpnIglsWUCz1FHhF9ZgfycbefqWpdzkKlw0l4c
wAkqfBp58ZwcrpqMyR6Dm4XtcTDbkj4Gevt0Q2SnsWYC-6_jMjiCjAgCJJSQOgGRWT46knP26u6HxZAdotGZC7hNEHt3sFWTqNB8cR6bzxi7LPbFBkEt0Syd
ewLW5bb0NeaMUK5sOKoPVDAxW44c6PDzIHPT0Lv4HWl4gycY2y2BoQAo0BoAZ1QyYPUHqNfnIURWd4-24X4zVupUUM91zDtXfrYGLw85LP39tFFoBE1FxCmj
6my3of9BnXW7yifZ9Mir6UBIR45s9lSqHrEIGoKPhHlYaimc1vStJt8mp-o3cMmcmrz9Hil086UM3tVNZH6iUPBPtduPNFwPoHi3SY9dEiYYoswsGBR6c917
B0d6d0I_4_UGOGKmva8B6Iq2WvmoAozWa2ch71Pm1ta-MgILd3dFdtr1phyAWiSoW8mMW46cnnh6a8Q0jIksNDDHKWW1P8aX-0xom2MjqaNExncGyTOYIF7D
hSEEpJraT1tv7qphoVC7MgMJd7sdP4piyMGqR17tRryWdsnVCyZ2WqQu_oMLoISlASjZoMZc4FjmHXRpdS_E1FB9Hv7HP3G1Z3EHV_c1q_dyWHDah67ZyT9g
8REBKfkEdzCu3pYkELRGwR6YZHppDZ0M7QG-AY_OZsI9XyCZoCV3Ov8cCk63MMsZjwraKFpzYW3ayegWYUmnDmQYfQraOGxd5q4X7Uw1S16KZXT1TElmKpmX
K_64grCT1iPmvTpqwxxo4PCqb5w1MNhonLOqcrm-OZ_W_zgbCp8epIQNZzYnj3G2ZA91D9yi0RCgILCzstJYyyfDR3ZPXnooZPiOqlP5xCplEPl9L9JoXesY
VCTK9BUeY3FvnqBdMLfa81dRwU7dl0YHUou8nFbzZAY6R3nBMvZJVuwCRAjP8VwhP2-jgUeaiYswauEroD_9jkXEjaMnYapjuilbeZF88yfacqC6sTWE_lgw
DA2zRTYnfxsN-r_CelhrtULM_Upciw91NjnaClkEtHf333BGNT7iJr_d1ulG0SxaNBSv61JbDpAdixYQ73lt2u11Bj7zfyUAarIAPwLQClKkOmKOPCpk_Zi2
BpALt7-AmX23V4Jt7wBcambFjnyCCbBflVlg9fFtuH4H-kbMX5fVJ0ZaVZGLIwkFJE5_z_Q1v3OFWs4OB6e0PDx_j7-XjtdpnI4KSGtglS4p80MDIoJK-jjF
HS9ilCIGVFnqB-5XGrh9Kmf45lAsviLwfZ7vE7gDTKFQoTYBoJWx69FjfplDsn7ormCTVkq4CgiQo3QqXGm677FpNhQDs4eMvaxawM70QMfTKiV1c8pH7SWv
FWpOi9UFWp4PnyV9Ash9uTk0Uv1PzJXPc8-ICu60ztGoYnh86Ds177C5To03C23Rq7Oo7d0NChEgbOpZ4ydrYTM9pAfdaONPJ5uNr5G7t8VCeWRoIUZk7n4O
m3OoZbsJMPiJG-oMpA9zoCBiW8p17SWGRIUliCr0Xk1kv9gtVyEnMXDxx8ZCeht9DMOVv0hkGSPe3sHMxKF6yJDoNiy9a06u4ncZCVdS5iEPxaqMvXUG0RWJ
6SSl8ZDmBDATZD7zoNZ4QmpDv28detCyjwK1h4pKIDwr_DVVcddh5ZxJcCoju1FCmYy6Lp9n8tWeD0l06iXVn8ESRWHEiPrSldTpFcWaMebQoNj1iMCqzYoj
vFq6l8wlDBx4MvB_oK5QoC3g-qe3i6GAhMGfVyZTe25be-_amCyMq_DMLsWMRIGB1hUbBj0OZCaRKK9W8FPyfV6Pvea1UIQQ6nPJNtGNSBN5AdyaHmfi0hlS
qYnu4HDbLPK7yaGqMVPIyR2bCHYJQVvAPfLC5ELnmc34pgyqgpuXq_P9ffX3XHyyqqvUl5dqEJdmdRpIlSW6iBU5XS4y1GhpdHn3DLQoX2gUv9CBmAvFDmRh
HBMvalD6_vKgMMSYIXiOyJ1e_Dbbf7j1AldZT8kgyYO6iCChpQ9Od59zQjt9EdsI7xnwApYt2uj5GOaeyPsvl94r0V8E5fFpqysie7UaobSorqVO0rW1s3cQ
HL4ItgSPlf1r8vewNEAUxw0OZD-fLwt5hsHT-U5CQm4vkT8sS9sjVf2t3xBXxTBbwMRzRTidaOW4a7S0Ted68uOl8RFMc2Zf1nb_2E3vT6Cmtb3B1txzdvmO
dEc1qCpwlF1Eba11LTVLSAOzdcxMFqNl1piJhV3JwQ7GBDf2Jc-xAbd0JhUqDXI9Q94jWJVgyfBwatDzcIQYmE3jyYNr9c_mOmyjhunF9kCnp-0RY1VMbwnh
pek0nJGaMWs12O-87WQCunyXQt7L3v2Bk_gIz-AoRkHTfJYj6xauxdpohbgSTphvLlnt9ddNCaIdaS7RvT1eCtXyzCYFBPo1Z2i3fdz3BeDsZBo3nJHEjsDJ
BaEdHlA-Qna-6nc0huCsBAO1urPokL0Ao632r-evUGU_OBeU-j8ZnbSQFQSlFcZmfThLqU0INnrj_zXZ-1TlyrDh_ESO05_zTB_iSvv_0G
}

