sprite $image13 [236x176/16z] {
tPo7Ukiy240rq62y__DsyYLrKXLXnObxllKFtzOd5Y0HVCEZYIa1G6sjTRn3UmS0SahXlCG4q1hEq5g5V2xd1ALrt46haE89D6l7DVHMygiAHzLSIeFySfwj
uyDe9P_oUVfzqzD5IyEZw3M7fv5hnuDf44yWUbhTM3e-aGCNSsxuR7gDuV74sl4bQFbyZzHFB_61fXrVZ9h2Gu2EBqXBPpNrsnvlUdxRtF75QJ4i8NsODd3G
yJZgadgA7q1mq1m7T0VuIOSLWUft9Pp0_skMX6rgksu2XOvnLKfmKn2Vukh_DJq75x7XkLpzZnOGp-YAFJg2u5ok_XyIEvxBrLzhy-HDvFkGy86kldLSSDQL
v2xFShNdu-gu2LZZsbl7MtgQ3vNitzbLns9mmN93TwM5wbN5DbUF_T2Mdfmfi3fLiHbFH1OQskdPd-whGrLT3O3jO5sNvIfrTSWstEVwjqRMGuM16dUMyJfK
jRecNzYMYLv7IuwQOvQjQ7Qj0lCjcnOdrZiisPx1e6hONONo86mjQIPMomBO4Z4FN8rrDkEKAnDljc9Z3HZr0kojiYOovNht7cEVT4KaheEMXYdDm5oT0P59
L-oZl6Ht_R0TXArjCrwi8QRRRYvJhbWjmJfs5Vo4CGrodIa0cwtEn2uV4CASwytr2PskIDnDZvRB874FJ9NwROe3Lrl8ThVhC6pZjIpdqT1G6uuo0UknQU1g
ktb0fwjgW44M6MDmaV3JbD3dYh2v8xUhQXXaIMfmq7JvUbrxk53zhWf9i-HPOWYJ53NrksBP92Q_gsgKS0_y2LCEThJEeE9plQowjjjLDTBTj88_-6M_DQup
Ursh9LgLrhQj4hp3tHMgjp9CtECwutTLeaQh1P8DU8zx2xGBRY46godZbWQbNiDwZI5YdPqWy_Qp2k4DpCMoUjdIWBEuTgsjRlokI2mTVXCj95fHxq7y4yA_
oPgPrf733IYCUDzMRcSB4tGMDLr8qypamjgr7gmn-jH2h5yq997LeafSkuGXt07KTQ2hc4JzDrSVFOf28eHZYFWTuNU8y48fQoTb7ZrGLKJ4FxGK6ouZn0Vb
92NfPc2MdbSFaYLuNA2gAk_yYO1hW8BxgN7O2zl_4okkeBO5TMPyyAG5ePyQxgVrzSjNoUnxglb1yv_zOIEF4UKTNlVP0JuNGzjlsN1iVT4fPP0FU67e5_rv
XpFkw6TKquMX_opNSO-XUvUleHFpT5jO4AZOFA5_F8nvsv-VfXew_Yy1SR-kCuJEf-eD_UF3Lllp2ulNsa0bN0JpZlk2GmALS1diNspnY3f3ZEiWGgLLo2bz
AAIKeBJvQEtBcp4ak9m6ATmGyzpKIrzVPrWEV0KtLtkuFY3xkZux_rHTB5PNNAwAja-lffzKXwbIRHk99BWO4X77fWO6fguvuua1tUfzGP5j2Q3z_GrDJtlU
CStsmtdolg0exx37bHsJaWEDFfhq6xjsfedlLFUxrZ30f57Ca-R9-HAGRklyhlwNYbCpzT9XbQjymhjSUmvEiaasb2Mk95-GrtKSgD3b7MxH5hPWIDn-L_c6
tQvrEEYhT5lODaFYzhgIAEHpRUclkGucH2JcQdlFnJ1fxdGLKTZbcl-Qb2JJt2LUe3vi3_jTIIxGhAiC9_BLr32mM8J9Dh2OcjzLhfbrnMYSb1mFB6RUNai4
Wx1rkh9SmrEk0E4tG4t7pTL1Aux7OGlphYG_eQ6hSr9o2rCsj9F6BuWuN6MBmzNHdrUDpLS-Ze55kolB5dQuEjf-9DNIzoM6LQuajv33rTEV9mB30a36jCPL
xa4xN1EgwR8Z1qbRuSfo5uUhhpzFB6owh7XSnwgAqxMewNAOypvNajzWbolK3mfiQ6jiCVfSLNLMjWK7iEXlgiByXojFgYgyphNmGNz32i-gAhpCjGe_rvNa
B_XvhdMfAuc1fxcsbQua9kWVk98OeTExifYXaxlA38pNj9JoDFrfhYIJaFkFAuUvchV0XZlrkX8QMFwHiiox2kC1E5pT3wNA03fUreCn_tAH4Knu9aX6O9On
V29JbY4r63BCEM3v0mY6qm2TU_agCJH7eJoZgN08MIpmkKtrMs2nmMTDIGfelzC2qobDbH1q4P_JbiHC3n-mJ41dCrMojh9du5CjNeN35p89qtaUgGANBnDF
fKiiit1Gn0FJ2KIL6fGgFfXE8AgFLM7nmlJAeWfifrTUrLSz_M2u1cKVpFI2daeArqHPm7fVCdZQ4vDIP0tCH2-YgT0l8mzFDbPBbeMaS0EBibIPfXnPbbF2
BKaU27z0t_peZh99q4yVZ4t-CsWm3VlV68na_JTIM21xObM5v3y1OGZzSzNrovWGMRPCT1CGyG3L1R8TT4XFHD4vhTJacv9preqfvNVqzpB4hqlhwbXTNtfo
24g-itU9UBaiNv-vgbvweJzELO5b7sUwztlxo1NMh36AmKWMDory0BMaoytg-jKdJh-x5hqqxfBjmKua_mfMcQwVMhyS6l5J8VxgYfTN1p3vsturJD75nrKC
fEzxZPe4HF-b_-QQhqCeUTj-42O1lslyDgZlV8kebVxRVLV-qI8XNyC4OvWceZyB5zmig2vo_M1_SMq_oq3o7AjhS57sP0LeT6M_EJgZI0uRgkZ_Kwh-gnrA
mKd4NUKrzZkkTU2gbsx3sF5G7PHzIJ0TweefxAExDebAEj0LmcuIoZnOT3CmYjUyaG8jpfkiPg659G3FVUr-lQAgb9ztdCnvMDKjz1YS-6tXwY5o-DJfj_Kr
tNNTLbGsrrVCOILr8Z7XppsKXltbiRQxhfkjalwBtzHFONDvfOjtqqYgkgu7--7hhJFhVjXXUj1AJlewuNTokYgvMGyl-AkhW5wQDBKTRge0JlQU-zpvTNif
E3BIEcAVEINtEwMlB-fBS0cF1qY6z1G-YOLl-asn3lfDcqiBZ_Shnn0Ron1yvrxf5HlynwLKmf50boV1BON3WNv2KJ_GM8w3QWfF9PKkHz0XXbSWLvH7Weu7
UaRVNd9uHHAqbS9O8OQN9a7jjDUornp3MKYvDfnNHgn5BKz7pgLMHFnZczHhXPp3Ota3
}

sprite $image13 [118x88/16z] {
jPhhbgDA24QfEtp0lF_ZdcNijAc3PIwJsR-Iw783MXJsQdg7N6hhOp3BByoZzrPBeYyGVQrlBW0I03Rzw5zrbpOuwixbt6l-GevrY0JXfNepfxzHDbuRhytZ
Gt6gGo0V0ndb_JHxKBuBmEsjX4j8ypCWFR_iP404P_mpRnuo-e8XIt2E0D8JFI5rGQSb33cdbHLD88qkgGAH2ojMrho-f8g0oqMY0oA2xrgRoSOotIoGVsO5
fqLrDw8r3Vx5FhLk58eqo0-3PZARgTtGbPK5EofvPPKQf1roXy-UR66P00lYob7qH4ihsbAwMIE5PuSqIaC2XpDQexP1eZNNiAYcguTGHYQwj0eg7LJ8YRKw
vxdCFt0v2GKy1TdxcLLG7fQCd5cB0IDDpVBcw7Cek9VyWO8_F5lZqyuhgmZGukhgUUxR-FzFx8Q-i8vmKwDL1DC3N_RdjS-Jt3obTNE8hAneiRxHAWBEqoCm
XHAewYeY8TU3MuW3LzQG6-C89PB5JMHbFOva2J1kgCdEr4MRtaCPAJZP7R8pShanxAnzDgntwBE5LlGuRHx8Afkh_0BRKP5uPrbU0EEyroYujosZDiJS82_1
LEGfywOiDXzJqz-D0SmlYKk3N10RG7DSdbZbkHTjIE2gerVNfREderjTCrYMn0MIHfJ6rf-VPd8XZHjnitDf6CTO_eAvvHQuoOAvzSCWdpBtWiGN2oFFtUa3
QVIsUqTVIaFh_mAGzjFHTsG6DRJ-fq1UG1K2uT5RRRspJ6OEhVyZAyvo6ZMVl53FuxCwNfJ6Wd3RwLUlWwbB79z5vJMEtInSfI0sW314RIIwqmIoWvvtcfnW
XgjH8ZQ0E2EZnr2EoRUg162kQ-jwL9bpgo6KmzfC0kfckBBsUJ9LqxCPkOLn_T9gPgvBAyPa6EuA0NeAGsC8PRR6LCrmRgswQFr0EwHGsGZZUbzQOJldrZIb
X6aaaZBtt3Ykpxd6LCqrMEFiPuZxRZV774eWMc5tiBAkEpemr5L2AD4Qf44RhUkE3iLoNrnRxH4ihQdMadyOie07Rup1N2wjvWijqnB-x8yXKHgrQ-kwlPTB
QvH6xNZVYfUiYDBZXOHJNe6_iS82qxgr9P1pUkiBv6xLwJh-e3N8XwYjqBFgii_dGBvD3ChHPwkRodU9YPfp2NVNy6Md1aKZk0NmLMSK99fA_EqwmqwSBaJP
Te8NtoYjMyGh4R4ll47yIMaZ3gAGx3V4s9I7CwIwqTsknNY_i6uhN6W7RXVuPdvDZSrerrUpJ3lP8j6ykx7GGM_2Q8nhzKvp2opS6pfn77i17tJGtTx3xzXR
kD0ZmrzCTPrO266nQDxIka7DxnqaYFquVY5DTF1IaNiYIdtxDBPFpSmvLJFNdCLTwpwjNvStqguYzKvKyXQRj_rb99iFodlLv9P5kYwPCvrHz4ARQ6p2v4pK
pPYe_TcilbiB9J6jwxNlrkYSnEvhQuMPY5KgxkRz5a1MiysgjtRknnOMf2YqfAglAqofYbkcxlizKgOVm4JgjnPRpn_lGMlMwRfpkOMrjFuqdc813ub6Yfnv
5UgwYQLGswoRvwYmx3VKjuF1gOrUe29uDudw7oFYJadThL3suscoHCtT9UpMxjeJBRdskYOg8er8DL4UMzRyvs7bTABAFL5-mnafREudYssuIxf_EgptTP7X
3qf7epT97VuWTksjTVZsQUoV78EtGsEecKjlZSqFfOv2dr06ZepznlJf-7x_zL1oJVGnfSl5PhBOUNG4vTkaEh2dyjIt6Rbb-XAfj25w53Vgt0pSQ_fN_wW7
jGc5yEWrloFy3m
}

