sprite $image229 [227x269/16z] {
tDU5SKGn40HHixMZAbt-qPgvpVO7zSkWQqS7XyNKZHp4wi6m1gQUn7j2TMI1SACa32JVHYcMG7LaAm3X2SaNIF45KfilSDHF2Kz8Wa3FMbE_DtoFa8GR9Tz6
QVWsIiADaY-GCjC_2iUtP2rZWa1BP6f9Pxv06hwDaY-GujieDTy9INX2ybsGuhiW3Ty9QOD0NsIlxRNb_p9jBxwDaY-GujieDTy9QO50RsHgl-9xXDHy6oLX
82tm22rh7JMJCzz6IHX8VzYeyKccm7R8tlMHVUR6V3DnwiZshSGsT-Gt4dFDZHti80p2O1nt0FtQKlR-ZwlRbeOC4gy3JXxzXVwbCKGvZBhij1QD59EkcQGJ
0GgqADA9G8vOD4ad0YdAr4RvJyHoIVR4CycrfhKd7ador4ZzGrmpoPu8Ydcj97iYa1TAqeazagVUwUG_4OYJ9wb3uc99yeZO9patyZyHI15J6wKZYl9gIQO7
qVOAFwiihlk3k2kmt2lP4cNV2rST9CbJ6niYn4Jz9bT9KeiJ_IOhi52InUn1HFaH6IpAAoIfPZTnI_2Z0g9KQXTb2fxaH40dRbjkDLduPpIPEaajrX9psW8r
65QH7xBml8lh3NGY0V4J7Gaz76grCaP9gaumepqH53wUv5sTcW4J9gd5XaGWDqcMqw5LURvNqe4z4KWVJr8FXceYT8V2cvDKjms9eFY9_fDJr8I9dTObEG6m
9m8KjkH5LalPYHCawH4EYUAK9aaHi014OlemqWkJTE28o4TuG9_a0UV4y4tWlKcgemR484MB6QD9CZL_1IHXzKsWJ_AzC-f4iQB7PqNxxQzfpSGAnhq9w6kJ
TE2OM6gjPlQOn6kd4m89oydGMWlUbsG_eprHVyHEY7kdKwOCt8nI6HqoV8ax4-rMLXoAnZM09jxz_x_jPPopWgEIiShkc3Nq-7AzmzabGO7l9kZfFWqOksYj
cSiWUZgIxgHsoARy-Ihf9PmZhg9K_K01ORfr0YfisqOVhv9UmZaYgZs6Ln8JsJP1pVoyaiZe7B5Frh8V4n8DoonkhMwb4bMYuyPLFfpH6B7MhNCuG6Pc6dkw
IbpthROcdrVI0yQ8gFOUyVQ9qTCXkx9Zt-E3IefP2h53WkDdu1CJUZemOj_Z4sj90AOHyMXnY2eTSfnbrgZRWPAVbR2r217LVXpS8Q4aPlb68TRe8rLo1kWG
VRKV1maWgUwOvVgzn32TLCaFPBHD457j8yZ-u0MZid6XFwwIOYb2ZuZbOfZMFii0PzjuhvLhrBZ-VKQjpMSHIjO84hDSIQrLsebC_qf9UKB22QBVmV5fvPy7
BnllbSYQ2OLA_gs4yw3EbJIvV_1I9MkjIQYao1yK2X3EWpfNqamgGSdR029JIidtIvX7z3qTYPgnw-dqXgYPjUJx9Sm75Kh-IYjNyZsTT4HhJHDAlbt2_2n2
IN1WqDZJhPXUxeXDgn_BLrVoRoJC8yvxEaGPYCG7YAd6DI_XBAXR23VlwNXSJ4jFggaun2sXP2wZZWt02SH4JrVPcf2fSYNwXLZhUaP9qQo4XuXmpOrqJrSh
IpLLgOnU08Wz36abKnB6GLNPCGkdbHndcKsrCZO5WDZ7dbDIKXB6GVsdghoviEPwEXeNqwnoHMn61CGzKK0IXUB9eDvkQTAwrnUK5BcVvOxOI9I0Y54kg3dl
bp0AQhyoBIfbFQ-achdZ41snj-T0nAy9StzQGY36GRLVYD-_DTbc1H8lojr4cjamos0qabueWGWpT-r3pcSKS8SI0l1duCUAAA_FAUdIQaf-bbaxelr6t2-g
W3oRKL054hPxJ1b-j5OecUlfA9XbiGF4Sf67Z7F0zZ2eNaRL0VB90e9gFttmIeW8o3CxCq5G8qB3dmD8XfAfdWx3AIaQ8G8oBM4SrF6NS8zuFv5AJicOO_xW
9O-ezqDUbT3k9FI8kDUVLXBLVhQO1g94Y2ff2Qs54JqCwhewo3CzdIeTFdY1-Ey_yOY0F2KXe4R2uw1kPTlOAxdbbAJM6Xq-U87uxrzZ8Fhn42yXuJ7YmL5Q
IVLqG9I3MUw8vOfu7KP0p106YCr962FwU_qTCjVJQMjsDCj0jCxOieWF6r7Gj2aYBX6VKXBLdimXzgL5hPUEMBbTloJf7h7i3Z4leRKv8dArYLDoJIopc0w2
3CJhaFz-48LLLNUkG3opAFGIneYOZoBd2WXsS694DET0v79bBDkwIuaG7LixaZ0nYu6IKixrT2Gq868G4ANKdPNMTTytKZsvA6mvH7-lFxlC6d-Ig2Xvn0f4
hZjJuLf9Ib5Dximu2QU8Mekx7fNewVnn25OHCts0g4HNE1RLXuW1n-INu17jSgar_AgD_39BswrPeGYnZ-j_AAMeR98DAahXyq6L7Py2QNsffwFlFoIUHK1k
XOXKEH7KgOJ7Y6J4lpxggPuE1UJcYjGPeaebga7HI4eOjE50hCGKt-lFBxDgmqkg4163EK2CWce6cZ2eXW74A83xSj3JFRbrlWkxxYPSBm9n4jISX1ZDcgex
kl0U9Pz6r4nGyP_c4WBmka-ybJKwZbfUwkbUH7GSmSeub13RnDr5h5ydrwEI1UIoluBeAg6JiCqa56QMZeYAzgIIgQtprn63HU5KGbE-3I3Mka6Vw03c7UJs
v39hEOyOI-Y3wX67EG4Yz3bEAvHCRvsVHmma38BgCueXQCCd6uVxwPwkl8Q8PZGj8OOQ4ASRXzjoie2SHNmaeSqan11qDoJiAzhy0AOepvKyZnXB2BYPX69e
u4G5fomcIfxhwRw-wad4KScyX0feKxdIqbr5AyyhMPRzVOYUSx8z5MTKXnzo-_ViDWuFnvfGydL4u4H1dMLqt0B2B0gxNGfVG3ZJqtd4vId4l8Hs38ZV55IK
fe1SmW8oLpAFcDyZdak8eLZQuPsd2L0U592QKV8yOXZKgOJZKAst6G1Yi_dBu9BewSuYdfVG8wveQduGsIcPxUbUHpmdeTeXuf19qXkY8RlbKK_dbrdB_cP4
Bs4geq0StfDrkbfvK7BBA2dxKlxFGKrb58ZtRqE9SRxBlGnEztJl3-gaK4I8Rfqn8W8_IckqTVx-e2OAXKFqJGqf4AVBhErID53oZK5jIGaz8jFlJ0hwdPCz
tLBUXfYNq2EIYl3lTGO94ETABe6Ixmngeb1uHC5NY4mo2VnaJ_VwB9xEA4Qx_NoUPHBusPxkTSJJ6VKhZVZGwHFu9LBozQ1c2aMy9aCpGt6Pe1b-MOwspjSN
Pp4leRyktSR3-28KPLAKPqfk5wzaNRQN4FCIkcYhYGmSpOGECed_QQRaUhHrVWxnj8JD8Ugox7UBAHsQchMwTTP4oULecRMKSxEOp2W87U9QbgKu3apNDYAs
wl7zKzSlisXTquY1XBEC0j4lfjRXDFVz4nIP50FYkPvkIoB64ahkkZHwrEqsNIJkiDwAJ79hzWibLq3s769UmlZ8BJxMtY5LeqEd9FfIJtTJSayWfYMCWze7
bAIugQ7dZy7l1mM4bhNKDO6OAHGJHARlZvLfQgO5v439SldwscU8-OpE3gLSlH66Nb4BxZ99GjC2ufLK8aqX9YICPv7xIkFdOm5oaaaoOuVl9f9SJtSyqeLY
VdebNcdiotEP9Emn0_yG4JSvPuo9Gf6zBkrN6hs0J9G4OcE7xn0hFGFv9Wa7OBVIu5yVRQua6H0zVcKfGBmshgwdS-DKeV1iCI9xyUAq8fC2n8EUJihN_eFu
zULwkXcYdfRG4wgf7AEi0UI6J38CnYZ0hoGT5uZxybKUf_L4HW4rlzUlYuFmIaOz7OE8Vk6ho83ONQL7aDb2qHBNfH-y6oonaWkKX9S6IE0pZuZTLTVJESIa
XFPaK5Mrh40veIGUFKfUII3YKULxEeo4X0vnUbrQ5TzUa58Ioop_TCKgSqG4_ILICY7Xv2ZSqMd63ibhADvKII0w_14HzAiSGYOochak3SGR9CMTsoCbZme8
y4T4Z6LLFL1oaj6JrwM12CRuTVr-cIf9Qkpm7QA_rm_6vp8wEu_g2O48IDb2yUPAClkMzdA0MBv4FQIzJSBcPn7ZFzN71MIB3vt6-1wnNgggWvnBsCvSbmOY
HYyWzRoIVgn7Y4jHnvYJ41o74iP1HLg7TuDp9MbGCe_e8UNDrwM1w20PIavly2bNm4392Z5Zn9gxrpy_ZpfAE45CAsbD-IUj2_19LVHfH2op4fKmkYuz3-fJ
1MHK4jyQZxIk7V3sJbOcYC6z_lnHE73FWffGSeEI-EQtyGcwLJAx5V84ekhR97mI4JtTMYRNXHI8WvBq_GT82d4kOUgwj4qHeUIoFNxhJ_gDICFQvFP7SCqZ
nXBchqjxnAoIs8uIbIlXLXJVpR0p17qLCMRpUSq75P1uDnZlnX7tonXb-EOteMLtY9H6z6pvwz8n8j8QAEdV-c-ChuCVUxeHaONUDeku9DRoY7x8hQVRPZqT
2RuE_cxd0uXuZ_ucH5yipoD2oVrUIVQ77XX_-OqCFTqzOckQGSnVbyuZnaeoPcHO-j_zvJUeafTxn9P5z1np2G7e4AUGD2Z9U9s1znbWLBN6FAn01XSjXHXo
MFQwD13dZ53I7rT5MaawOTd8hJJmYltbe2Oap24YhLr9p0X1oQ60Q6lIvvh8rqNIb8jf2Ur5HFHqD_7aXcZ6lzxwSxDzuoegSb3wEOKOInW7zV37JC1yJzTH
I9MyajyWLy1E_rftu_FNMaB2n2JwdgwZC4LAgec-OwKHIzWc4gO9VG6vLv9uxEawk6KHyzUb_MJwqLn8iqeIb5GUUhhlnPJK5n5p4kOjd1UGzJQFrlDgGZ-l
60MAvX7FNvVsexcCffMyH4ekhEpg8bCQCLuKcajeBgDv9HkK77ewXsYfbSRvwzAOzJHJi4-7WjyH0O5rnXqYbfCPnFnrQOoOCA_afIifpQZIhzsuRK34LAUt
foQh_W1mdj5KJ_VTdXBEuOolS_A8-UlIUS0yvFgjv8W89PSVH4qYvYNCHpJVqm7HBwRmHUBltBl94xvUG4Y6CqhVD40SJwuizFRhqXXvmBoItuYimWwnZmHY
Li9pbJ2_pC9R6pDE86Q3ccXctWb9U5UEbKO2CHVKv1I-Nqdkd-5rn8I4BGzulgUxx5XC2Rqhg1-JC5RIiD8O4PbUHlmy8Ov3N3Or1erhmnE87vHmNa2s2XhN
XYSGvn82y0EGEEHPbsL0R4O9n4Gx-X58MfRY4LiEqJvS2US5P2rtY0h4CxFuwIcCbGGYsl1JYDb--syBoF-wjQi3Xg8O1A3FNVQVjl99lQG2OODpNLAM5Jpu
KmCrk55yVqg6JpU2GFnW7W94OI2kEsE0kDpCfc33TMSWYVSt2YqZNBC-G1Io8VAyWSI9go0GhrbHeYWGptGCKRyByUcyuucxTl2QLRvFNCLrUAQhg-8MqLo8
5KfbCzy8iHDg6k_dBd3TpV8kSPbtY3EIs2ZSZCHdjXkIs0dTaCGwweOakj3DI3mzkI5J2X6P4eX80EOqmYgJ4mbTc1DfSsNYNvM_EKQF
}

