sprite $image145 [238x197/16z] {
vDW7KaCn38JXAHHRRlS_BHr-EeYInBlV3NQqYfotJawzqPQ7-c0PY0gBmI8iig9OPCMILEe7mcAmA1PPSUPGOeJ5O14oMLtoHirOMvirowB428kicC8B2tWC
5XPP4HPPSMOH5XPP4GA_n2hNgDI_frnYm2ChX1SMK5vOmAF4iCYA8homWCTWOP4LiS4lyVwFoRDwBCeb1Yoo8exmcVYOF0OBZwmGU3fb58l1mYChb4iC23mJ
CyAYnF382e-i47WcPfnP31OMMH42LoT3Vx28RfIrZR5-ejNzj3x6C5dOwEEMIudlIMUbn0ziIfnFksbMg9Tu89CsjbtOVDgvSucXV7NUqhuw-RInVOcXUtK0
tQi3E2mi74eCtQi3E9GOkbS745lOVDfGMrW8_TV9fxrKB35qhmwWSNNoQQjiYI7mSIB1OM6XUtK0XnB3eSHmA372eCHeBUIpekqLjmqWaRQJLtHXqVeDyWgM
6DVTcGbkn3eCGx5x8LlV_xH_2OomY-Af08J8cEW57lXagPcZMqAyMssTc5RrRYonJ9REsqgiRYSnnBiTgsXLhdYt6jZOPE7kCx2noS95tqxYs6JnxYLnRB9m
TvCuDbcy6qaScypU3Bn-rjXazbAxWTSti76tnAGjfHfmxGCRcrp-Zq5ddyInoPZT7Z7ex9CuDfcYjO-l8bQJoQ7EVeaDRt8nyVfPHQitMV7gh85rcnppTiVM
yNGRcEpIMH9RQ75XicCRIM97nWXDDeylQ88Tu15T5n7lhRZTnZf6QB9XVCsid-C8LAve3UDh7LYE6L3b4bLuZl65KU9V9eDgrw1pTxD-VvEjl1rELdMhSWzU
D8VEe7DWHKi2WWNuv_7jRoAn0XoW92QkGMStgmAALo5RkM4RURTEa8awMPKRjf5zwyIqLBKArxm1xcCbLlGWYpS_lcyWiKmc8Ptl6r-nEeiDhujRnzSlSHnG
i5ZhNC6Mrzd_lywQLgVKahVAx3HlzqkyDbcuWSvjSf7PyVLldTVT2ZRa9L4FMh2bZad_mAPCNkXyCB4djv5O_R1hazUy4EsrpgHu7oEn4i76EYzefJF5wvOu
R_AYNj4kZqbIk7RMlCbhNc9zJ98dht7hPBib0jZqCTcWhrmFOes_mirqABbZigfSmigQDramxTKskg8Lh8Dsf0ELCVF1Ne4ShsX1GYRROVCcyuFvySsRx6UL
oGIHuILHroRRMVCcYnV8wrnDRp9pZ0fKxeIODQhU1MypcXmNcyS5PJ9OIYEcpgqbjb7IP3-hwfN9__TrwbpBgth5AvD90i-IMFdyni5QIkKvcudnDPYyeCZg
35t-n4ng6rLGvJwFLGc8yjkeWZhC7iigNYM_ZV8c-s6LZY3IkR_chS1D9dCeXdg9KbzjetQRoKDnwLpho_65dYcuYlMFhqBEuCd5AboExvht1fE7ugatjuqc
CGoi1ftNhxFADS0QU8bM0juRJ1w-O36-hGGw2rUq7bR_wyo4oOaVOX_BcpSvNwoVT_rfWvn_k87LZyjQmUjjf79lOFNpikXJ3gCV5cJo3MUYdrS_J_CZsaOK
hQ5O1owNs-Z0DR1QU0dmufZagJFoh1YBF6uRIMK0D1JhvQKw5kpafPtrvayvhANyvZydry1ghRUNtxWdhs7hU7cF3ycCO4aQYZNpylTF9oUlWTLVBucuN8V4
Vju0zeYXM5C-BsbLhelLluqKaZBPpEhNMIRROVsyf4pUX5LPFLFRi2gyVAQu4QkIDtcyTN9tydZtL2Wyu_fCxCzVJHwRHBYWQBTarJ6fShabgx8qUUmNBLo2
EyEALoPlp2fUcQojisq8WAB5pgogDv1uOrwnRX-0VE0Njdy1
}

