sprite $image280 [329x329/16z] {
xD050O0m000mtAL_MpfWjot2pdW100000000000000000000000000000C2Il4FaIqgB52bIf4YH8gSc5MFSaMELYa7a8o95ratxcCYBlJjBSbk7eJ1iYmHm
3aZA-z_j9IIxe-fHjkyZVcjavUahC7FIizByfSWuwNHlzN99oDfWFckpk3uwF7wt2D2X2eYPQq9EIA-Lhave0q2OEU5EXXED4GWFPXYiRP7kC01Ma91HRGWs
9wqnxk0TacRybxitfvCUDPezt6s7J4X_DSOvIyYewl9MfHH9o5cLQkzLwmQPaCBtqi-G2GdEO2z29gJV8ms0WlvKdo4J4cvAWHdVWan8LLEZG-5Rt4XXY8nd
8HFIxhiQTqXK8HoYgc9cPo4JqiCnUjp0k3xw4p8XWSSnysSwGYOaLQ0ALHDHeJ-oycrAqjr09mn7o9p8gd0pY1gK_aWktoOCGwdcA9VA3yY495GDPgO7IF9t
IAlYg4KEa0af6eSA331-fCktQIZJB3GLvFyBcR_MJiZhycQV8HEoR9ToC2hnzatNOtV8X7pWgTIbNEV2NAcrr0chjIuprUNw42opxo4JigXiExHka4j0biib
9bGa80kiBceg0LgA_0IP4oab1avg2RiDSZxMUDadCgv5QfdtdoSo8U_VDSQnb1rjYUBbldoipBw1JCYVVpHPJbNka0aPOAztNJuW4zBmSdQ0J4XlFzPx-pMU
W4p8ljvcQtyFCY77fZZw6Et7y2TaGex9s7oiwuUa-mkG2NaBIBGnl6sG7ZKFJZ-_jHEo1sGdGFFrmp6EsVc9JCZOsQDHIwa1wPyx3vcGWxBzqeMt_WanpfDR
Eo7NfcM90h9zciO7fFyDcP1KaIfgnXNkxRM9JCY-XfEoDM_TZptt4_A47AttJdTd3xpFZgUtTaAIu68g0lQ3uvEG2KcQwb95b6rj_eFaNv09ERH1LQOZscsC
zjf49cHt7JGIOkotDKOoZkWfo8GiM1lT7SRrjjvwcpqFcP2uYYf1w8HS9-MHyVptaGcvn9z-2QnMiBNRRINTduPCIDQb008OI5WV3QPgzASW4z9H2uS3pe1K
s4ndvkSX4vA0bXgh34XN3SRzmzEG2Ua0fGZRsbj0jY9cS6X8uWd8d4X2n3ZMqPpS9nAmcHhzB6H2TbAhegzZi75cs0nd2l8yP4uaf5eRi-PE3yCeE6dd8NCY
6wLgto596h0nqemu3PcGlUsGVL9s-ivd1i106FpiBn5pQxkM8XQGm-6c2fin8Eq9o8IaIQaQaBqPj5I496s3j9yX4tAIhUiux6sj2f-ElJbg5KGEq76476Eq
0sH2ZbjqWEmDXkaqIM5QwWTaWohQewdVVuDCoDRSlMy3oIgbOCQPDrEr0-INYKp8TK8UScyz1jAfLHGp3qS6f1yWlqnaGgvV8KTpfzLg0DZetjrKbIUtTaBw
VMkFxaxKgkJ42rg7gfgVXqp8OEjh8rcBaHnpTSB2L8t_8DlFa0dPmpASTabLEdltFjRkW2dy2SY4T9zCVJJ0jc7iOzmQQJF-jBKJCYH7ZpR8kDB3jezEpgNP
M6_32TKZvFWMCY6Z-r2wpwNHnpodvcoTtwWJPeep4vcGtRi7P8l5YRWtr-bGq1Gy1PcGpVUHlA-EkG1J4T48Tl97xOGSthQsrUQYCjCzCxLJ4vcGqPGawKuj
LQvL8bLJswB_zeDD_lGdzlFMXDHQbZsLKdJFO17SOOPPK1yW4z9cghAdf9NPieScnMQ0xNhUcalPghC3P4AAtXbh936DrtjBbRBCnH1MDRexjPQFZf09-Gzn
9ziOBu_YyQEmdNqBcP3rNeacqlK8EU6Ea25vg1mW4_BoUjU4JCYl9MH29cH29cH29cH29cH29cH29kHIwsKfoxmlDLXVXKn8APTIIYrIP5A-29cGGHacUszi
xOHylUKVP4A-rmCo8T-i_3-G2VdAHEQNON5-2G_8X3I1GfL_PWOd3OZ3I3z29gJBOeiMSVhlSLaAILMfeg9Wyza7P4BIe03-OyTCa6A7OI3wDwjRhFU_xQyP
dE2sWzbYd81URUD8aEAXbYbU5_dlRohIdTiNaN7P_FiKAMxjAtzl_BFSf10vcH0P8ez4Y0oHRcU1nnHvGaBa449aY0oH8J94XiWG6I93P8WCaI7IJmyFuH7V
WVaQ_m60fHDZkC0ZZ6DADXzy44i9LmxWqVpCG4pEysYhHzW2VGN5Cxjm2LFzEECBHN5fHF4rxjnuqx9VK7xayf7EbA6-mJaxtWzF7j7po9Invn_FM7o-jAok
CXJBRnEvNNxXgNvsjsmICzSZ_1iWYtAEH_eLhXGdW5BQwjkk40kNjlB0pGEBBZrK1K9PXXfBl2UjnyKZqWAARNKjMrbYMh2YJm_9tL4UA9Mt7zgNCXSKk2pA
cTSCPHhOpCOR1h8tk9s35xHFd2pEyW9XGhmbrlPyDnIZvPH9q_dqj08vDPqwl2XBEhqktr4RoqETXXBCCScdM5iHw_8IDRc-hVuvzUxCGBwmhL6-9ufIFkb2
rN1i9qNGHVdhIzSZ_48R4NrQDrN7xMval3QZDaI75hFX1T_upIWJ5YK0vEHKkziyOnfPfXLA5klie-gMepPlVws-YBrU90LVl2Wf7jd4enaCJL6_xFrvxLPz
WwQtAisuSZJMAGjJJ67hqAKg0NCDezNjtTcrAXtU6y-qDYlciYWnt6FnoXxGZAk9xP3NPshxjiXdxLKtrZ8sVcbeeUkY7BuUJSEXz8FOFtCl931oCqa-saJn
A-ADxB6z4UL1shw9v1eQ3Vn2_NhM7KWDQl9Xv7hKa1czbSON7mtzJsrl92K0cWXbzA9KZvxV-MtXC9CvrWbKS3BihQGbtWF6yOSnO2WvrYEu1ySrgR4UX_ak
88q0LqxXCVbEsB5D_Xkz7kaxmP6BaeU_Pint0nEkdDcnrc0VDTmQxsDxfEz96chovgCQRoJMGu3l2YRzHJd_ht3kZ1tGfCOwm9KFpcD1W8-ePFkVgU039l4-
VfP8xEOnUAl7cox1xUCRkR_h4ToVL6I8397_suC30G0008P12FUtlS48giOA0000000000000000000000000000000001m
}

