sprite $image90 [236x172/16z] {
vThRUkmg3WHW5mWau2Bl_xHp2Fl45pob5NLFsDvrxRMIFrOr6FV73qJ_au_7Pqfd_ZdIvsDrpTEfQvukVRvMx_9SwlErIl8aAS_3fC_7gZjFal8yIShp82dF
awWy3v0-LgknF8fQSEL7Q9MbulfFKFxsMgN9rpM36jAUBvNhByaXxFb5NIC1xTb5JIiqNjlpYxec1MfxA5MmWyPhUtvH_xQrLPfqaOHgUtvHuxKzVtm3jJr_
G-WEX6dF7r-UmBRnn0tXZ5nBqjVQ1h175JNPk9QKBe7QdhpErD7jMYAjjtJO-iEbVFTRUZVLQqbMQyD0DnPhZgDg7_MlgjQRwbUhggqNIkzs3bQTiTxBDGCR
pNHhdHVADPFQQEh8ITAPrbl-lQYgM-jC6v-rnRpGbNEaCxEDorJkh7EG5RFHxfn5dOZHL8brNZWRxSz9qXapPTOPE-SaMGCXra3EeN9hEET8kJMUSwJS6iyP
KcuzIgk7MsSEanR9m6fDHL-MKwHL4gvzaDrUoM_KlWeATeOeobF0d_VU9fKBHMa8r3lDDRtnGTvtmeBw2YbNv3SU9FiF7JBxU_Y3wlj_NbjR9SckCvFa4d95
8Uz_8jfVhI0A-Gs3jzOqSFuMabQuVh1Styi6QtrKlE7zpxUEGfkVcbBvZ2GGxExeAb1RJkK4wTsSL8YDlwIhCEnwTFNIzp_VECdVd_lL3I7P6BsPpIlCMkjZ
R5zjwJPjMABrNXDRPzP0HpFT13jfDzCrrlge5tcdizIMNxiciCwiAQERyrAvkzHwJr__u_iJPmdKDb3KUPBlkgqoBzsc3Ra2eUjFlAXNAaNoFbzkLEwczx6U
0b9lRVthJ2pDoAdg5GiVP7zHWn5ZxqBI5OuGhNDyeodAKgvu2iCgYqSQjyeLZJJJQEIA9x_p0y7_AfF-DNgFQw4iqVz_DAFItXgvQhuQ3KP-TNYat4MkkoqD
Vrr8iPjlD4GVrFZkkO-RLBwbsHF6j79j7vkZWJvk8mJBg6B-Rn5vYZh6jFgqkzhMVfT6nfXz-ZNtexDlV1UhhxRkZQZLtQxLlNnNSpvxT9zqiJe7MTq78Jrl
7zLzHwgvEn-TktjyLolNyeCGlfr7BaLdIicuTadTF6TSvbfdnfsL3t9lmfkuOdauDSUAkhToxJ1VRUsRUv3ikQlYB2gnEcfRNODic-juwh3Tpwo_lY4SuyOQ
gwtSNEVQSAsARkn7mZc-pEglRVRycTjGU9bJqVx7ZqpVMMUujPdnRIFTTy-1JqvfggCR-v7Pko7qM_srBQCRkQx9nICsEl-HhgBsuRVwQolUVRT9kku3qJ6b
9DQSu-kt-jUVGQM_dtYFhYLXCxbIsnYT8aY8b5evTcqrzuulSpi-dG4eMMU8bMW3iRPQIm_y_wIepFf-BNaL4ntVW9LemrQyScG6potF2FO0AnzVRfqseZt8
QbDASoSbsXEiNCgjowBo5wmTQIL59TQ98hVs22ilAhU-Jbk0wh8AK0FZ6x06jUjvGkBMUM4Eh3CXgyLhctz7PM9Dv12P53LgZTzQ-QkgRAsx2mFZ6x7wjVmu
5tLZtLsOQa0Qi0Qqcw_cRApikuryVEFMcdCXjQMBmLUjVB7klZBLNhhES6i2a7IZRR7tFzSIqFUBV7pZLdn6pQ_bNuJbIJO2KfwFc_ig9XCRqlRYCVfVMxGH
eNvyxAm2c6M8SIn__qFZFVUr7g9-vglL4f9Mm2oi7PPy1_xjxTAPBrO5e89gCy7Q4gZd_QArg7IhDQiGJK0nMwDxhGLhMnn5xL7g7ckcGBKqFvlKPeArpRTI
-VyKTQyrcnzB2Saga6f0IxysbDfuVr7ljMPMWMeAb0m0Ok-gBTw_pjndMiq4a0e8a6j29RNzxjU6IdzxKGdM9lQ_aGGK0sp9YxQD-Uth38tDr0JC6Ku9nQpg
Isgh-85rXbdDgXGh404W1Y2hcKc9rhQuDuGzAFLZPm1JGIw_FmnaP0tLjlKkFxBES6r1qbf402rpamn8jBRZHzOPhXK0A89a9f1FAr22jVsPTOPZ2u1QaSmK
i8nSynxhr_xOEiErLStckYEMaSq4qC1g-vFZoxLpVatDvZq5YcLQsqEbN9iWl_SrLK0iGooW_RcYSgpYlx6Cb875Ifxs3hofN2jJcAq2oQQLQq-Lyjf-Miq0
NQnaa8ySNwwTdqs2l5Y9ziXrXcDh0d8LuDCgMJGmo2UCBzz8JQikUoYYFLRAjVE-GbAWjWSKbMfLSlsqrcgMK6tD7jlit9lAFv6b0ga8idr6igvOwxqHx9dI
cTKg-4osWYGsqJCwPtDQRxLsolZoGPOAMCt81W0ohN-aZsbTOyUjCnmxar1Ca1L86McnZh6rDhDJnvTlaWN85QWceDOPErBAjPe1P0FKBBciKtjeKVcvHPxh
ZY1RpRboQpkMohUDyqb-5XUGWFK0AT6Q0TKoSW4aGRZrP2aVP6GWotoPMQdrO2dNLc1-82CNP6ezcyfhE_ig042jXqkvLh9br9g1ogp7IxdMAf9PITnwFfLZ
1SWengtdIxasqDSJfVn1dblFbtBj3BKUJkLvlVNZuBpM-d5uVDOUe9wKW9L8ZyLEAhTowVdQAULMBZrVEwd4-W3g3B4IwMEmdKYVfEr4-YHj9zGdQJkHFWdR
YVH9saweJz9s8dsIjXFfax2TI9-axOJw96qdqYTfEv4-2Ti9zKdQJgHFqlOVaVuR
}

