sprite $image178 [435x264/16z] {
xDpdZYGX30HW4mmsx_--crl32Fh4DIpjMTNtztAiaWiDmNN0-a42lGW8-YDxUW7WipuaiWvSqcUHJ8Ee3SkH1a6q9pio2LpMCqm60MkV_KX3YFM99ujGx5ls
8mt5tlx_ZX1rN22RKEnRvczOAFRdagFxGD8h8Xc746j9Zi7JPk159qcEqPC1236BVGIYNfS_xUqZ4FGgYSUVZq-s-WYkKttnx6WIw7wuJhLI-uTlED8GOlsh
S30KQRXEdJydy9uUeir8Gx6FTF1IFeZl_KyhWVR0x3n-LdIv_13NZJH71Y34F1suL5BtEqza1ufzrFAi2Y-s4caezbo7MAEEj6picGYAVIfTrTS8OYZIKEov
dEBktmscMw7OQ_c7EhocRrYGLXHxALtzIBDrmqAnRxM5FyWDDopCpe4EiGnYepSi5Fjp6cw_OQ7OkrJ-Y_WxPXaK-qw8ZKitpZAuJWKjLyIzaOPYJrMnlqXl
cMLGx5EPKCyofcvOAFQ6RbYOdQVidsKmEyyPdsKWwCfYFo_PcMLGx0tSiF2UT2B4ZCqoc9rRLcvOc9rZcM1Wbi7i_1SZ3SNUy2o3sNcUkAMHXlUa4sPd6Pg0
sNc2-La6nNv-bibh8WtlIKNAhygBPnaKUw4lpd_W3r8QjcOPl2TDxN--lnffQJRIC3j7Qd1f69fbC3jd_XIyfmSfwoMt-8Q5sJdIWL_XXeNtfBpZygXXrIU-
O7QMNa6nEyjWTjPrbqVCCbjcP-uL5Bkp3AvJKqyAzZyjnkmilYee6qn-uWkAlNQBlTrP1hCppxoBs_-q6CK-pnJx_JSipCxYXmgAcLa6itCSAYZg8pCd-L0Q
5cSP5FjCJtmio-dGB8DYFrfG-BvP9dky9pre6F_z3zHmWbbcSR6NrSLUHQJwtUFTDooy9-LUY5tuOyOiyzxUcIwsZi9Gs8XDWFF-ZtktJjrHWtD8NIiKStxE
UktFGe8Z5BtRpic10WNjt_HjcTbFoYJOAkpVj2Q-p7vIkN-RhSLdz9CU5zw_JLl6z7NR6U_VfYsJNpZ6g7t_fYdV-o3-abN761qlxASjKqh9scECi8BPJMBJ
bYb_bRN767LipFG_YB-yAH-mdVigxCUtPOfWfZ76IA5jUEo9BsLJxgAmFnp2uziofG1eMcECsjk6sP8Bd876RIqkfHsQLIliNOB_b75yqTRYqiuiWkjVHzLM
s3kpW6xLqIU-bC_A3K5sRhw783XO4Ev3spBbNXaYunDVZdzkiqtfSgt5fIPGV9nuwXVIq--HhpRnnUVI6cYPHDUCdeBz5r94NXR-19WDE_4bb4PeublJs-Ww
wUw5EsPqlTPYmstGH2RMEawArH4Jyc-c2vvXsQRLKNnh6lMQzAM9p0PD_bs-f2tZCsOclZKTQoHzWXJi_tTalBpfghPCX9MZ-DOK3CXgLPZyzh6mmWBTzo1-
uhOm-vpI_Fd8g9PIQ5bWzH4TnQ7Fi5m66pJvhMqAPo-CfbPm8s8fs2iCulSPLo2gAItKrpw7OfoT4QNjm6TO9e9p47bUkicbSvaHLryOfRtmscHSV3jDZiFQ
CfH4c5MOgQQqhSYWzxEiQ1yTmR0JgsRWZnTCF7vAmz222D3JDqFqHuzIQ71tuIMiRZUkBUFXqTKcfv3Iagj-M58SH7Xvld-pn0Et5XjkXfPKph3O4otxNqTq
PlcG2xNroyJ1RHdAxIbDxGpBr-pe9CFBSVsL-ikTOIMGqZHi6IFUVYMyR4WoDadXa8OxicLC-M9AIwTwLfHsYddU3G3YgzWoiRH3OvsKPfOeYtaPNlKYF0nc
o-0mmobDqPP9-OygU-KANF3zZ3c8Fs9c-cTOlh9NthVzAGrio-0mmmM_j6NEVZSkua-UY41lyJ0JNsIOzNM65SHUkVAtxsNyYAt5ECoUFyCwAwKn3a8m_cgy
YI-oAwJ3b8RFjemBd7Bc3nycNgIrs6De-hOCNfbSpQrnGz-MaHPQNoaDRsdz3iimt8z9OWjDrvR1miQdV8rfo8als48xRiletx1E8E87j6Ly4TAtPTeJI0R8
T1J0n1VTbDQRBIDJPwxAQoFBl01RHjT2QxPbl8ejus0uiwZpTKJrKM7SRS6lRyjO9-Ae5eOcxoeuuq_emGIsJ4ytcxGBVYREOI-LHN3zb3s1qlP00V9oMyRm
5mf-hPHM_n-aXpUhfR5jlo_ifUgsp3p3eWgOv1vyBLpj6pcklIWoF-aCI-UsZ16dqGA9-5HWtyZn-bxgzRPCjsTOzCx7Ucz9B4eFcy3vX1s7K0TdMDofBUCR
d1S6uNL40CEFEyFohsajfW3kM9psnKWDOClaSvG2oI02TonEi1AWRFf1jenHiMMO_HynWpiMfvpVOqrR1ejzvOx52QTcIFIVZ4nfR5HJMfTdME2EnGaAZqdv
m5o4EFhtGClhbY-cBTEqL-RWBVsHz_pzXJtvA5QYoaigjvljT3gFVcknXyKyEzgRjzIkPFTeRKlGFhAotWIogzioxl5UEPZlQ9xp4DS-ilmNc43MjIsZrLfi
GyAlklq3mjZjXWleFs0IsRHbk64FPNtaFmeEhTGuYHdFfLdhJI1J5_Lfo-3kdWYQvzeBUmhfGKYzwI-dzQ-UGpPRYsa3bgfXavulx2daFLPI6wZrrenijXRJ
_aUIMiECZLWF4w1LXOQHpTPY6TfkTx7psJt-VkIN5Y4lgR8YPDEMaThs9hl8xFRzmCAUxkl3TLrlWbaD6aGsRHdP8xAVi8nu5DnMUiVh3GOAjBms89jdM18P
8HmcuDy8hVBQa9NS1AsOPKVJbi786FuPt4SRHusNGDQqEgx85zMtPJgQ-2BNleSnPi6HYSzLNX8PXdQxyO8rRPcuj_wY2MNHR5UlztX9P1WQ2h7-px3EIsd9
-uU3EV5mbqJrPL_mgY4h1xeFhclB92SkKSJFWpbJSEXJSGAO2320x4S56hswu9U8U6ym9_vVXZgmsvxAPnthfBjWQp7TCKl200NTA4m2M2N08B82706aWLkB
CRDDx2sr-9l9LO09NW2PGaeRqPPnktSf29nA-sU1bUWMySmAAMr8MyPL_rl9jHNslXKOUoEVMUhP7f9hspBnm-X_LxGWb9d47n-ai9KTU6Q5b3QMBVCHKSvx
xsXfA-nj4x0IRMCQVw3myrEQW7vQ4pQb1uMzuGPWAzjdddbV2QUquIU-u3sGuqUhL6W0nWu-SpkqU_ZJbWdYTdHuM0ku38kEx50QLoZunv_uaZY8gp5xXJqZ
O6kahpxpqot-qvR1HO17mB9hVUPpKjgS-2AJ66K0x9cIt1qk-ASjWuz9WBaI3Zppj6LEQ9W38PRTLvvvdc6T83Oj8PRi4IjgsZ8dt7Qcz0WOqx5ddhRCzpSH
-qSXnkRmCnzFQRErMFvt6G0xA3gSqcPhiOnUoll4s9oPnYzaotphI1uFW9tupFcHuhHbXFo25yLaJtzcV2A3DVx45vdUAUy1orOXZMUfQSjW1ytj4LkTmZC3
PDEMgN3tUo4Mb9uv8qrRHgwkSOSO6wrdFZvvQVI9BxA6INLYnUgbyTPXxfUrPMG9cAh0rg3upBbDwm8qxCGNB-ExIeoDvZCt4hijG8Es5aU3YQrEqOfg9mQG
3MhBC5Lpw4qewgRnDfKRG3QeBUEgLSyAoevpPHg90MHZsZ9XQI0M5sMbDc80sP2sp7r58OY9BAOeRYScaOrdos0J8zqJO_r5fOqOG3Q4BOEjGXR4NZI68xJL
YXZPQ1DVmaxEbCGozKeC81lFbk4Q2dT7Z1TrnJPY0Dbmjano-uUQgwWxrCLjn12oeMoPXMYfAtqYLaX_xN-QMD8deDfQZC_srfU-39EU9PONFUdRCa0aYBqa
ZTdMudxJ2Zx5KMoPkh8avfPEIqL1Z9OVf7ZCbgcdoBo-hl0mF3AnuxPCFSYsT_A2Ts7JoCIEspBr8DjcZ-hkdzkzsD98RD0ph7gGlQdRHL61MCUjnL9M-C1C
wY6cG6m4MqOMCozh43JSl2WgRFFxjcNaklYg6q6-tO1ktq6FVuPbIj6yvFfyA_ggJAn_MuO4CiMK5dBhegXhklPlo_ZoafvtbxuGOhWJPVmpB8bCBwKHFnDY
kaTf_RSMKr6_v6f2UwkYVd7VlorZYlObLv_obnR5tBvK3sxB9DtPevR5Zrb756BwXKV_hSLESr0RiVXF2uH29zn67AYrcDLcZrAi1R1FECHM-6Uur1bMKffg
Gt4dJPe82aNbDDQ_BQCpUrG2ItP_lHJ0QhkncT8q1hLH11S2RDeDCMoJN-uCw_n1RPORDkf-2p6qACwKTlQWDizj6tKJ1R03bUBWjap9fmvgCo6rnsqGi0xS
HnpPbidhRJtnztDiVEAYjaatk7sUAQtypUvdpHurFcKeBqBiODqn_XdMMt6sdZ9xr3ZEGc2ZxegW1RhCBrhml-VwSdZsAEQ51YoIM1CFt4SSsfOf7n-p_TRV
pp6UytDQq-rEoLoC4xPbLh7-x0JZqxQCiQ762tiiCuj9sGoGVUdtSzZBG20N0QvMO3TUfdm6oFOxI1ugHl-cc39GEx3oByIc8a26VXBkk71hXpm3dYBUGuPs
tvh0n3MEAPS1Cf3IpWA6A_kPqYGoRjbzAm2RPGSumv9tDl7k-oHWU9px52M1B1p-IRZZLIBUYisKjY5Bvgcco1E1pJeHspBhGozgxmphB61i9XLuXhMkuIi7
oYUaiBOaDaNngqsHXu7Dmmxz3fA3A-8fy_UdllSCgtG0R7gaHu7fRvrd1ybXNhDCrB_O-_E0pPI6UQa3cpfWowmJMASNUq60zGXiDaK2NZsNzRFWnxnkfGzW
ioaIyEhpQ6gUOPKLyBebkqnrTB7t9jL_pJ5Jsgtl53OLdqAMEafXCwLXP6liSqMSPrW_8S2cF49MUWsmQSlKaN7V0JPjcPjKxfxNJ6c2b-zwGPmA4bc9j7Ik
ASCRiXn-1gyfod-HfP-q7axvrzI7lm4
}

sprite $image178 [218x132/16z] {
tLhfOZCf3EC6MsJV_sttC0cbzQGxJ3FXc-hFT_OGjenaQbu2Nx8pln0kCp55yzjW8p7z2ox1_2g4mdG7P_Ux6l43JCcQNm6Rc6d4Rv5R92O5BjvS7BveNjUN
cmYCwGcOIux1sMiAZ9xpeb8ACHF5wt4Bt_3Y9BtevVOElq1WMcEXS1ydrnTO2S8fHNit9qpPNSbAROERi7m1mF5n2dmDkONoZS2o4p80CpCeF3gNIxYIbTg-
e6rYy1qexZ5jXFHL9treBC0V0ESFkILx6IkbZR0huCy0HvNVhZVfRUOln9JS_DKclPUI2YyDABbTPz9BJGZy3E1aHQPTRjUmKhPFUeLjkOKB24nD-kS0-JzC
RZRnpAH_3g1fBFuXSjjbfLZX1BajiLAx0GeJSbjffMJIJm5bGcxhhHGQc2yXjx3RIY6765FAcJ0dj-ryizvAzKcFBfWu9pUVTRvP7vf7WPLSXAnnD26tYNN2
CYi55D_69E-0pZUStFf9dpOcFIZCZacTR-pv0ikJLWeS-vYSWbudhBTIUeQxWcbYUfsmBZHhAmLTnNw_pHekecJVF-bPXURd0lFE-n1Z8XoGsnzYfPBLYHF5
F92uOs6-iMa-DCTDGzoDXSky4q1MSdjZQ2wQGd9RYHEajBSWtqnPAGLiyPgu14vV9sJQOQKcpbvDq6Lo0xyiD9UPC7f-lW70XqFp3fUrJcxjMftSIkqH69Zx
gInP9q3mbThi8DZOwoVhGh_RL-GRG7FZB9--ybwGLHQ5Oh36sCXO9JTqyCYibs0dOgU0RXxbrDs16-0rwuH0TODQD5FZO9HKzjOO6pA1WMYCfMNv9a9nama-
xIK48euMc1bWQumAstDoozuSXituGatwtPhvwmcnkJKvQviu66CAFfKMRrqd-5BHG0rza8iNdcH6Cl0fjjebVB2Y75mY1jwORm8tRZnG0_bPkKatUcg7vCQr
9BX4TnzCkU2TSakedLhdDYytEMeVK-fN_RrOqbq-aPoNPuKJdqjTncT3qXtFr0q0YgxFNKYnXALnCJCg1s7yLiFLswXJw_q-PKY0Uouj7yKoNkG5JbPzhlV8
ZQ2u7P9RyJO3zsBPa8KkDt_X2nRacr2Xk7N7O_VRG32NHx4A0_rRb9vVOhX8KUjocpjk5DUS2D3RIg2Cyflavj6eQRc5QRaH0rzkNX-Y5mako3VTaEWRGCbj
qYsvp6sA6B5SxtykzRqZjToKuPeuy0Im0CaOksIT88RaiDmqeZMZon9cvii3mSGD878xd6_ICxdHdDm4GGpaK49hZ1jPKSxxg94nFvQR-qPkiuOBXP8egy-I
7W2wG_6xsr4GJf7RVBw1b2aHCvD44blGXabtA6NV2EcGV7E2tAAPbDlT-3lXOQEmej6XO9V6HhYVh1Fi4xcXourtStjaO-iJLt2ERd0e-wvghHZcm_d65GXU
a6y0AhaG0vIyRSKYeGK0UzBC2EkiioOKUNluiTnOoMtoAHT3_eobiM8gEQL2mBVNOOVriPsFVB92H3MRWuWRSkEZwmG_5eiXMXFuZFyLc8kPW5ehxgWWhdy9
irVBRTvmfJWegwd7X-15j0gzCzfne7FggBTwwynMomryHvkN4acbCXx0zgIteV07AnRyHwhMsmIpIRdDhnCwt5Xk16DA8cm8pETEYqVWzYyccStBRVwX4rcs
kEC-ptPt-N5cBh5eeUcBFwF-oqpfR1uslqnksXUZj4z1dwsKBmzQGaAtQxtTs9iVmvNlyermn_v709AQOHWK_eCeUN5GjNPQZPdcbep2kdn38KYPh2H9Pig-
6z7Uu3RnGAipKznACAz1Ui4wmHiJm8pc-gpjuxMd0SrBVWDiSdFc9R0_ppVaxfOJN5Aqdmz4Bf87hv5MvSnrazg6groqJf3wsaJTAFk2ST97OL3hIAj4--LK
Hr0qfyjjNxvfP-3yby4Z7-zfvDLe1Rirn0PinT0rwmJ8ssWBCenXqhioy1AF8MfKfwgvQS-_OftGzn-3oPSFJ11YlLn8RkDKtoStFhPEa0yT1URfCoyEHkDi
kMd3DVjSgaDpmiYhVYCTJnDoEsMT41cxdm0TLH7OWvVRFSHso6rDlcc-Cm90v_N_tvzTABUqQvq0ZYATAhpQF2nkybHvX5wohbWdY9LgdTWBHdxwL5bmdjpc
yyszPxrqOkE5C7cgcjfwkVLh_S6htcewTAgy0JE1oP_Vqkk4xVLehBrWv8wTAcjKe_2MTKAtpoCnXACsLgFUZE3aVAFb9bQg4xiNp9fZI5l45BCprmdTS85Y
Fs_SYTLut9rl4DFCpbydO7n_S8zEP6TUMJ5XzcB4_yitANwGi0n89sPp55dnklU0KJXxdJ0YrqOiceEmvGcncpSAvwyJEdnjlUYFVwLdn88v1-7v3J0EG08p
AWvBBB92FPEODbnQRW8FPYPEXsFzFB7prmc2Z9_urx3TYRSwqTqdhHCCuRX_TOKLQYCsqTrd6Iuw71TjOYR-3Do9iJKJE6UTG4VZOg2d1RiLCu6pyaqyjftn
hH6ZBxfWDpMELiYDCn_OplZS_-j7xHuBhweAlqHkMq4_xkF5iUjjBDYy-JpjkLJ0k-KMUl_HO-Au90MRCf-dvnlCFOVPk3bn_6FZ1MzMG1ikhhUAdGl3tePg
uhZoA5XH7xH6Rc8NAEtRprkVYBUGKozOC4kWyutyY4en_kbpMB0FLZ4FjBH9N5umWJ0Pc7tt7COb_miQM6bUjV5I2bieDs7s5wddiDsGUgaLvM884pdje5F1
32-rebmEbwLcsMw6y3bU7CmV1652RjTpc0O6NZMQFmx-krImbrUsPZ7cKy4ENlB8TXLekMbQwh7t8eXFvLOlpKlBJPThyn7xYdBhj3elABzyJRbzeNNZg7XT
L6wVU5KAvkhe8Nme5ouWhuaG_g1LoxNBfT_q6orIwheu8ekuaZE_3hPGF4ph7m
}

