sprite $image332 [330x192/16z] {
xDk9cfiu44LXuvKwLsJU_sqdxQPpmsSAor4MR7DcNxBzdqeGI_blLSL7_N-DRVKnjb6qHKIqMsu1HBFb5j1EkIM09iijPWh79bHLZskmt1993uxubiHliToI
AHj7V9CirSlosyQrBDbVcaTyAmALosxVImqZlaMCahlT4T5WkJcEaX-TKINbr78hmfBNzkbsgL9YqgRdYAdajKD8Cup3C5XoTiGtHqkEdT2CeoNTSLFqO5lI
TMVf1-BeQCbin3T7IxglDw8HCPFSJdhwI2JTCIGDGohfs3R8MKbtKLcIt2o_HTH9dXSbDyfm3PARPH-_HNAp35SZETH8kZT-qhHB0lYVU7j7a3XtZqeozbvl
bvSbHv14dEv8mgtZZINll217I-WF2vBbXnb4mBGtsIvZ8KcsZCi-anJNZ9XRyaQlubD9KueuTtEIXRotsIw9kv9Jo-EjfFXAghBaRHoTncwsIqiMdFIUbiJT
P4gyNNQM73GvWL1vmzFSIqIbvEs8dxuao_IZyw9XVwcqX3TOa0wGvaRyE9M4Slr73PrFnjzYnACoo2onvFWFe-Jdvy0iz48Zhdh8Z5BILGwVYLborvqGMI8S
xxCWSyjX41viIrxhikrIPL3yt8ix6ZAtB7OSapHqsScu5oyHBs3PF-Zev70oP24i-T4HtJXQyhb7dAWEQTuIINEEYWYLxvAkyqMY8l-_FFzfRZmIkINIpGP9
M79wCkx_CPSClhsG8znQCcSv_daws74ZwUso3BcaUvqD4edw4RznjEIqZZ8iIhhN6Mn4L5fQieXeatJ7rtdI8AgsIqkAY5P9n_CxvYEEvYcB1xjHSjgpEpe4
qwVEpOYN8gdOyRTA1ayCcOyuucR4LGQ1IfbxG9L3isH4_vGFcjnoIkftxA68-HqLYJZlcoKZddqzEgHF5uSqGXAtJJu7xXOb1V5abj4IAjpooexJc7uEd4iM
e8fIB-18_aPKb22GdenF9GLKMhBEO-pw07BBI28v6PzA5jnpMDBcY2b5L4LoCZwH5AwKgEb9roFEbdMKP2VZbYmu3KE9glHi6oG4xd5Bva_6zvPKyclALhii
-yR5U6j9ZINPoNWtIchgQ4bOf-LlSgpOBcjFna-VajE3SKjMFNpw9nbigSAIkv2PfImv_eCbgv_ZJ_74HbgoZ1fBI2drWLSqStuMk3LPziIlXOeGToqbbXnp
opAKsuFn2DogBDj-NjXTg1fn4iXbIzzu6HCHy30bgtMqv7WAM66PGkQMwM0_RdbSovjFBbbtBmf9F7uoFdLK0hc24OzebxntBqg5G12e_gX7CLfE7Ldituqu
yJiaitjHNb98P2CE8b-NDOFjHDnfZOwMl7ylIlpIQIvIAVMEb4BSRGKRP2gPtOloPCRFgTxoXsHHXUEL-twiRK5QSlPUb8e7SofPkrrQigXYiCjWoJkn4iTS
qlUYh3YLp4TSKYPPwXmjUJzMCDYPf3k67IsvR3bpCgw1gsGHDODjoRfMyEQJIRf3XMI0BH5yZRXn2g3AmRPaVQjnp2NtcMIoNKgOTyGPd_TKEbhohr4Iwv3q
Y3DpCbviKZlObgoFFx51dlj_89dTkxG8gdUibsotp1ttkzsn_mUI4HBf3WgWvS5kb0pudOwNmoV0BqeUcYG3mS9_GgfmjEJZyRi6kpzsNsyl3uRlHJL8Hd3d
SeQK37QRfFjDW_tXkE_69Nb9m2lkHUMI1OYbG2IIesN5WcoG3DgVsDSxEDtf_F5HJaH_s7N9ogou5vL92d9Acx5uEKE9OvkaQroHdp_-GzztkzqfujXT_ocI
Qkz5JIKBG9KbcQH7t8FT8DcqB5aOx4l4uVjV_4z9jVUYffB2wL5Bf8cb7HiaMorZhbFNdJ_-ijljpfzZ7ddrzw8iMN0gYZj999AZfGUxGR9rneynqtMIBzrt
mm_7OtyjekrUb2NBT6TJpTT99lb_UsUYvJghAs5BW13O-xx_uzusXUDEVdjrnw0aPpKwmvwdRr4WYK8f67UE9YJJt7BiADUL9E8AK2SfDVcYAidbSMURdttK
au4FKNji3IIj9Hu9BLeSuyuxP9ODlYYGV5YG8FdiwubxbCi_KvA8V7rPQY3o2g1EK_eY6ficXWX8Fd0y9tbUBUwgFYEvBCi9IMkMnmBNSdvJu8b2EN-YY-h8
nmPVrB8B-ocI8BXzkRCy95d-j9ua4GqIhvbGpMHSfBftnik-g8Fv3FcfHpqFMp6soGUIsn_IGB9_TXa9xI1FwpRfjqhyeY_gq5-6U8BbOpvvS7HlVqvFaeZh
Pd9TzUqbQRpLAoG_S3nbUJ2VuUc0TU0M-KZT3vx0dYIJDYnBHomhKWXRUDNvuRyn_yZoqOPosPovnn79HVB6ScaWsL_YYXgohaQ_DIrRVL6NtPa_aoIIpM8v
BmqacoH-_AVg2j9hBI9PWVUt5_qvWUK9HmEIqyIwRyivTOvyUR0NLcBOGKPV9FzhNrJ6BVM9i0r8VeMxIRo5PEUC2F9cBI2T1fmzxac9t_x5u6XAiaJu-YCR
KDeLa5YHvD1EHu_e2POW2M6RaqHGNEnOfkPYV28VFOuVSVBxxH8aaVdOawp1QR6JUBgEKXsQGdxDX-9fDnqe3qXYWtmLIOJ_qEqoAcf8ybowwJxgBoI-BBcG
XB1VIt8YcTykyNosC17i9JWYug3d4jy6H9vb8_OaiLtQIRm1fQ-RvNuDI-4q8zhjF3cdDv6i6P4LojnIG9RE6kf7AKtCS3f4f75lR2U9yBCXoqPtGRXrC_ZC
zB8A6npVIX9H2iXvjY7Pm18Yryrdu58AuQIZ-7wI2Cx_PXEIkSazXEnILBxrY5ZhZqXg23EIavgGpArMLVI72ATFvHb2X3cBuryXcG6oaQK6nqGkH0-WvHGF
-EAFaCnT7TIuvl6QrB7dUXdvDqXsDV_gpWv9EwHjJ3Bd2oHJPvA-ixDVU6CNzYpTd2HO7fESJqZcdYHpDdXj8jz4JiunlM2VHDh_Hf9cBw2Ymw5JWeZzAzPa
Fl5WP6zDql1rumgIIp8K9AgcBO8OhScC_vxSqYQs93cRZYGG3Ya-tadWJjTYJTwp_6yiaQn8PlE9TLYOSkTNH-9kioRd-jzbEJ0EBF_cO4EozqFmV4AIxlpg
26UH1PsiIN34rEdi-fFqBvho43ca6gXr741s9dcdxqSdwfBtHfHINvB_z_g96P5HZrC5gUBLOaqMeYTcoT9a5kf8ylNJSDIXxea0gSLXJK4xeNnWkHnwZJPN
qEpxaCpWQ1Nv_3QNfNpf2qO4nTILvOPpEUQuVT1WSZr8wbkcXWbJ050g61amlVOllh-joINVWmJ9vKlYIiqatpR3L-7AMeDhrusZqH4EadSNiSjo8rcge5dQ
IBvtIYNL2xDwYlUlTIhBPLaWxBopNDF9xRqFz9_zPP9PtppnCpedECLXgORPtu0bB98PKLbcUB5154mJWsIso7piCo9rj-wbEEhU0yxGRZwOzutxuRlFwLWA
IOH1QMZAKXdlp3ox0AzRNvLZyPtC-rxXFJnQhalozom_vxDfrL5GTtjzmYWdUyRA9C-7A25n1BRDdL-UyriodoQNkgpwZZ7mX9jn3TgR9eWTH6KvWrjEUnZC
fRHd2RVBjcK6WvOwY1sHnESO7It0t29i-uWd4f-8870SvKvYPvRO51y3dvzrdFhaDmgxrGwyRPd41WacSiWZbcVpgQrqRLz0Uhsv2k8AL5yYyTEVR2Pi-qoz
Tjfqwxc1P6-M-JSiSyvs2zA-fQuUbpfwAyE3ZtQd-3dBR0pIVbd2nBORXrQYR92fdxFKgE1eBcpxDl1sTaiGJIfSId9xbk0e8OIOFefZcqiTz-9bFIe1fML6
XBmS84M_C7zMvjFmP5pm7ZTuddYxCRFCYEQyWvnnqsFGytdFkWmukQkrJJMAg9N4RtsqA47Etm_a_z5FJFSqaNSuUkezZpDWkIr8XCOla7OSxKEF9Uwhhxhw
D21oWupexZjc0mFVcoKEQRiejOfKcOZxEuXolYTcSsA_lu34qGrTXpgin38-dMFhL0Wsj5KRD7FV7_wHPMI7vr4-k0aQ3zuv7mV79xTBb3SnL8k65_2qNvhs
9xPz_EUsZ4CC367NZL8ZJnJ71lbSqHEm6k4XMZcMdXi6D0vXFoLn5SVCFg8SfnWP_VIOnCKXx8izefLaVOeIoaCAFuHzZML0Frsz4u_RCnzqBCXhFg8LtxPx
EaT6cVhyyNZQMMe8MoTOKVNG47P3lmq9PNqvWKnzwFhQNFfmk-pn9TaC3UW-k9bhxydIc-VoDn8V2nAHVf2uAqG7nuOHZVJjFbSb-22D7FLJ0HZtsu1pQsoK
83zExAPJ75_8-YKFZbUdGf0KdXYQGzCK1yUBBEkWCVKqEIuNknB-GC_7mcG0nqOj94dMBpYE1VbJ7Ffrb05FcCKZMvSuCf-BHG-SRMXiC3zXCeX_4-DvHYJE
VsjikFNBiI2lLZt-TeaRQf8P8vEFW-FpKo7WNHKOh6-VrADFSnmiHRVfJYvkGvV3fR4VG-BxwsRXROR1o7okNazGqEtmYS9U1yU6kVIr46_j-OoY9s63R2yD
nxfq83bEx2xlzfnsuJXOwWLXZ_3TUXKZR7fdWsMRi4VqupYYdx17TECuma3Oeu1ipNn6Q3TXZyZTX3tY0ntE_my
}

