sprite $image317 [355x255/16z] {
xDc7aUCm40NHyy0VQC7yerslSZY_RDdk45vDVOda1dH1cPdPp98eG2Yom22oLO8QMvPeP85vP85vP87Nfbg0C7380WF80bF8rlAVTUq-SCB08GlC85lbmvMA
7pXXO9859jP2O1xPFsh8MbY0fgmWyBeM_b43aMq6hHGEtZU1-GIcSYq-XSr_oM5pBS8cyiXvyfymNxaHV0A7pzSHuVE4-Ru9p2VmloTo3vl8kSYc_oFut8Y_
IUHlkV3A4UQR0lFvAyVNFM6-8J3Vz8yQNlUpHlZS2BukC9yZ73vFcAzyrk2R0lFT9x7_BGPjx7VgCM1ars8yLoB3nCiX-mSE87OjQ6BNWYLUa5qBWDYru8b5
vecTP9pOIOQ9NGkSsBNWYKNcYPradDX9XebT2vPOP9mOHjPuB3d98B5hmHEBp1FxBnbetAbnvWKGknOyiSWyyLf5P83OIGQ8NGk0M6IU-BudUPo2s4dcYLqB
dbXadjX9xZonXymJYnoUsBK8J-mXDvvOv9CIbyWiSQMdxdEIYo5UWL-ApzGKSVfxvIGpnDMUEnhxdPeWxcqSqfQfS99t9CxSvfjn_0E74B_k_SDnAKGcjhW_
R2zdl10xoNiHZpxcjeqNulYQaphZmvpL-lBquLhyQuVnYzAIrjvNGcJaaAktba9VSxeMLNkzWHEv1j22x5hiL0f65lcfdRjRRbG7WW3iN_LCasFU_srFuR1Y
JLjU9w0GKTENkVnArP4OIqZ6gEHLaCddLMsqvDpnGkPFLJ9BvpvZHo3QOYaoon-Jxt_pP7j6PlssS00bu_5FjgII0vd07sCl4NUqv35vAkJZ3MBtqPWbucv1
9ST29l1VtvM9StpVRT7LGoRGzJVWAJ7u09wysp7ohHgomMutUuUu8r9iuBvXJC0SyhrUYOSmHIL_OvVi62B2GfmhEPwuAEMriOkc4Ci6Bf3VNiXqgM4XZagk
yYrPYUdct7qbsmyYWtFW8OnANiTOYMbZk48b1x8Iqt8yAlbV-GOn3R2Sl4ikZVVYfiZjwyH0EgVPxvI9U0YkdAyIEv0EXrGcZhRGyCkh-7YuF2Ec1t8fNoH6
EbrjYFEXY_qAHYL_5ncKBnbcPFT8R9x0gEH2-3On3G3o4duWraro0JcGoyGaxyO3i10FkiIta6Fo14u7PwVdZb3Y0VaRRH4B6Sp2kI9An1qzMI2NKYREm38L
4UBk6vKSo23Tfh14d4D0aAEGNo631k0TuXpVRoMp4xJbbGm7S3hXVMAjP78lm1yV_UBmAR6ScpkI1U8TLR822_4Qo300byFfaPXknZAnRk3QH-R7FVqQkN6s
7W5SKzwqFRvjaOar3jd0DRs4XNYz7neIzyo0X_05CTbq9Ikm42yCzOSiHex0ELuWpaL2amrSey0vbPuPSiltJcTRE26M8f5ARbfOYTUQF944V6oDTBeeiGWF
OTELhC1Al7mXwu62z-dITKPihi3vloDDAhbHO2LU7ZrG4C3vS2uJE_GiI536Uwq0At5TP8CRaCvvkYJ4172vpByQoUSZDYDSdxYNNt3Zdd6wfCJvB2Z4if3R
0LRYgfLi63Bsh1O5WFDq5loRc4v1RWHOYIjNCe2i9SJt8hbW4fw8hqcG6n0MuahHRpmbOkOYSNQFn8c0IoKt0Qp4zIiPB11tFXN9d5W_9PED02jn_KfEHYNE
O-gn8uHOftjaCy1ANByjE2Uccndfpgv0d6j6a1iGha_St-HUxmCnNISZIgpVBJes02p4jK8vK-EJy65CpG9n-LCo6m5Mulh8QIIMCNM9EDVChqEcS6v3hBla
Jq87WBoCNn5dP4WbRxo4DoHMP2Kqu79CqXGbukqhMO4t9bPZ9JuVZlDLpD4G_lG7zRg1-tt0IhmDii7kFw67ZAcTGZnxV46HjnVUdbYHFG58L-YOslcAkDCp
zIy3LkAja6aOafSmQMFy1J6vtNHFWRSdrb3VS9gMS0vBnAIPSzDA5k2jYJNpTKoTBfaNYEbvTB9H9LE4Vncn8kS3XG6N4uHOW8Vu1Xku3Dm0iLGoxfe0JeTJ
YLYBfFk9pvmAt0nnJpbG670z757iOXfWCaF53uxtcCqQ81PaJ-O0hdcwfCGENCyPEVzHDnprbd1RnBg1I-bXkYJ41bmEHoMMi1PmSyIAF6tXX3ZVMCTK51En
i_P25k1MYBMIypTX9IQ0wxZbS3uGfsHLaId2hH3hGlRqWjYWOsgtyVgE85S0RfHOAzaVYUKiE5WAiTpq5UGAm8qGAp8Idn6JP7vxJuYVdaHOOQFM8h7UOc02
PyJvElK8hCH3N2kvmX9kb5XtoVoRc2x39oKUOj8M5O1R9TPAdeWfCrGXbffP0Lc0soPMP5n7OjeKBn5BpInk2mfKyyGwf-QTc02GZVz1lA2IfIFsIQntVGa7
heUpDeKIvr0hkG9mAyGQ9OQ-zDQHHUBbbIp0Eo9MOoQ_VqU-p3vDZDfAlBoIASBD4sie5qMko6jusc5GYELfTK6k0Dm4iURPc_KwHQKGBwXa0TuliIvaBusf
lKXCD-VNpzJyg9BRByDLP3hoDnu24EANhtuByayluUutwYeo_wp7GVjupKqn8zOYwQYLN0JUVKbeiir4TTyb7o34XLU_tw_a1e3hVe7BL9-F3bsbA6HC_R03
IJ92ZILS_9Ji0D9bUX77viJvjhKG2t9juF-Q0DODt6nChSHw5Xo8DOmLN3Y9p2v12d4-2mfn0Pa1_FIt06HN89wzo_2Ak2DZ2JzToQGbTaBy-jNlGbhT2TU_
8Ua95EANhtwN4YlurGykX5XU_Tw4c7tBqMyycLZ6r5iHzqr7Rp7mWPXMVlMxb03MpDh2hF3gznR4jntuQbjSxRrNlqk99ImHPEPNlnEs9ExwVOLFdwG-OZlY
VdUvFIC-d4klVgCoCVizXkLNlvtJNLJdkyJH4HfvzJkbPzUfgnFtUyvxhtxN9Rxr-yvjRZm1Jwb9p7x_qUlK-kftFU9zsoeoIOFppwlVvtM80rWhcP_4UOQw
Z3Y0TKxjC38_rhi2SGZhKCII6O1BdYuj9mvWHNxSmYqdLk10_YHUU80EO3NMLx_N8zRJSY2d6iHzXF8Updh40QoVEHtWOc85Zdp8umjCHU8GNkCXEESRn0k1
evBBn06ypdMSL2OEuBNcr4NYHS8HXTKi18wyIRmSE7R9vIo_hH7vM40SUcjKSdNWgEJgm85SNJZQeZfm85S7ZhQeBXp8rUT6qHRLLt0ivEh0WLpzj1p8rPTm
65S7ZlzxrO5Z9LSluLZ8rPTmBEIV0VuV
}

