sprite $image76 [112x81/16z] {
l9U9Skmg34J3Oa0j_Fx_Sr-yT4MvxifKUPQ-Dwifpg0p2F9rAsMqzFMnf0R0wgTmYy7CW54-GQi3TWJe-Tsqt04p1jRIkyMHHM9zixYOjsei0nSSDRvH70JH
blHgSGRITYu0l4zZDKxUSzeiefLI1eJ6buf3uxjq-VxQpuMIsFBBTnp6FcSU9myOPS4hDN8F753uxFkSQUSTsXfUfh4EqWQvqvVpOKVRsH68dbzHob7Ftb9o
BZMTIp-cfaaIMtg-UPKJRteeWTJuRFE27zRgID_OCOODhgrSWOPHx-u1_BQsKOjF9wxOR4Sn1kwrE8eZhOD4A-T3SB8yfjjS0l26HZQlFItjRBIKKaudXSLg
xjiOFu4MW4hZu-O5MlCcXc6Uu_nu0TcWJwh7uXYShxsrOvVjVOpYO8mN2TGQzOu3hQ7oMNTd-qXzUfpt11QBUQmnBKPQEy43tjEfYpIAYy1y0A7EniSthvxF
dxPf4akOeZWDhFh2yUWSMBZZytKOnJq2QetwvkKeXwRy3O2xMmxYH03kpYK2nRrHtxnyal2Lu5ZOeTqXSKQrYuMe4VhcrRkXie1yRGLJq_1h1FOeZL5S37gi
T6nUfkr4jQDiwP03exZ8IqV8uXuG2U--2cm_ymZMzqQJ3tpFz7PfNd_khchGF0Pmby0zB5InH-9OXzJ-v65Ezq2KXKf_YUC8OrLp8q_GrdNdESJJ-jFb-e2G
_AkzyTx6BA85hIjvSeczVZ6fD2A3-g0Mm9mj_S7pkP97uhNMe_vCaPTXHFwhjhVMbZQQvB6KaQVN29zkImx8Ra3imDddDf13hZpI6BAeKI1d_CCWrHxKSljA
NXGdU5oYHlRoWqYNSoKVaaCwWZZ1KqGjavZH-MCPEw_E4CHIQfucQfcfRoCNmlNXpb9gdjQePIu-ORpSC1dNuQlWFLYYG6AZZU-OzoHuGfpWIQ9ccl5YcCJw
X3Z9qqNL2PKKF8gJl1jBvFhK-uMbr9cOzuYu9fPImzR_a9hV86fUf6bWJyV5vAv6lUCqQrr7vZNWnX95A4xJK69xVGKHVz3-ByMyZXYAOHYMtiJzvqr-uuBZ
4xc02op89_q_iFEpWH5M6_C3DoJ3oE36XfLYP70rk276oE0Umo8nHgw1ymbpFOon1E2kndp2kbH7NcLEH6p5iRpyYS-5CThoydDz8qPRNXmV8zV01Xo7ErLn
ru4WncrqI5uvHkt0RUILOfGbhn0ZhyVoydDvmNgUl7ACegwJv_uHh6U0Ip6g8Qy4enhoIZ2g8Qy4eq1UlV27Gmrv9HY5yiep_XiRyaemLWDSXB5R0ry
}

