sprite $image121 [325x433/16z] {
xDSvhi0W341188kv_uN_lbf20jBErAa2FDcb0000000000000000000000000000000000000000000000000DJxgkKHhjvxd6KVH_GFSPGzjEW_xbfsY67_
PpsDdD6JhJIAOHQjpABTFLbC8_NgsVwR5iDiVzmHm-nkPOSOFXXtnF1v6iKmshsOHZjU5dLGoM4QxNXPr7n5nsdaweD_c7xnQXgDDL7J9yjfDDP4BNzTiRm9
6ckYpiwGSHbh9lxXrfksuqLRcyQZYU7qFsdHvz9enuks4u1J3CV_SFvD7s8u_eVpRxg9uIjxPwAaoCf4OVOaqVT_tN-Hg9wgy4WV2pCSPKwiUlUl-H8oeUFI
UqIIuP3ity2hE29ULXoIuKM44tVU7yZjlb_v_Y18_Jqg6wwYRXV9FmnrtVi3NoeNxRXosrRbXgv_ZAhBtX_aIaThl36i-LW8LJnW229fjMCDThgqMgkuNSfj
aGA6A1BMEjRWwBRB7BSJRLgv5B_0iOPA0GSREdcjOmqEyFcvI5oe6E80dv-EX4MA8T_1o9c_WL-W61hwt2DfWM9ewNEFn0MAeQNFFILyOu_7H_oapptPBr0C
3NtkaRH4CUHzNg0qRWCl2v-95Tw8qhX0CPpnkLqkb_RffJ5NCZdi4ez9k-GSUP_rqgD4QVo6OusuKya4ml5YbF15FLvmPnB69bCOY_-QOyr9huH2E7QwvWyy
rjZxt4tcCKhyY69expDUXhJJuIi6Ndd2PuZmUWMBqRuqsXT3UvzrGtZHzXn6IHzH3Erzril6yAPknqWxBV7Z1rvIyf-aBV5FmXRVq_qJP7BxWVgaq-7JUpm5
QRz5TmW19eJHO4XcLmmbWk63MHIjDUIq6Wp9h8gXPF2jMRGDbDqjncip69AP3RoA1-lJB0ti7sYxkVp5zmU-37wOeTYRZD9GhMIJ_VjD1dksFS8ht8RROvCb
oTzI6YCm6M2sDldQxa-5JNU48QOHnl2-7a_YhyANlCkB4DwMNM_rO1GAEyPO_9jwl49iFNx_TtXDCLHuAXoO71XD9B-X68v_V4a0H3U1436wTngRl8_FZp76
z_HucX-lMxdlacN2PD2308mAVyuinXBUCl3I6iT_KQJliivD_ozNQFAuQCl4SSTauAKIHiit7IIVCFbXfyUQZ1boVutzm4j7fJ4Vg4uiGunHUPEtPDM9Jj1i
uAMQt8FuTFWqWn0vtPursSMgH2TeskFnfH7djCdNAy2e9qpMYKxG_hTuXFddoibZ3HvSdp1vxYMP_UXQY_irvLI3ikt362DlikhiIpBx5rwgwNLBkw5Dv4eX
p0ubY1eyiZMO_ciDRfX8cmnEXT1f9V_JYre_ifsSnF2bCT084SMEyOp9INNYaQrrCUGxGVwCquQBROImFZ2vQZqR2GQF6YPBevmQNIlQibcJFMVo_91ilh-L
t2-ERtV5vxTdlP3Z_wlEc6pzYatKycL89eyrLuYnZKpsvqmcr90J45Nj82Qk63Pmcj6HoM9WSa-xd8IePX03rw2CEnGbDz6i-WA49o6UmkWT4y-FhZ56tkJu
2fClKn1LJI0wvX9gomME_qcJvHKcJqDKjO0epqp_jMDyeydp4DNWoM61qk0EfMCScbniJUufKn1LNm3H-n1Zohc8LFHtREDzmyXa7k4yH1vZt44BCQLSYjJw
y-nGU_ZfVu-UCRdEcpmDyHp5Keh87JIbV-BGwVQyoQyfXlCGps7KMqv90vzRuukySPCNNcAo2KJLQf4sVlpVdZVv9GsA0KG3Z71q3J0-Qt8oC7a2eYr5tA0e
a7fWiise0ITFGBJ3g00H-piKaWr63G2X0SG9Z7o3KlLwVQF9TX3dCV8DIY-DxpRP7gB1lst32-BAckoY1S9fY5OO-GO5cnn-kzyLaTUPR0fHzVLrHtzlK2J-
VZ-PdFEthZE-1A4fH1uZtw0ekiZZxz5zFjwOohJ9zX3r34AsGRagC9bwzY9uuiOZn4b645Nd6fJBg47XcZmFdcsuBMd2P1k8ynWRsQ3m9dkvVw3h_opOm2t3
zqFK4pqUqQ1GWzUiurjrFu7G0E8ynlRmP7svdZCvgXu8WmXliXL4FZJ27WKD2cao7XfcXvEd4Df3B9N7gBy8syOcCqF3w53IbCds49FBD4Kq-bV049fCZXe4
BjT9XFOGdHS2OzULka6v42_QmAX1Uk06CsMoFSHR6I9BeruUOjIXoP4P6eww69bQXlOryVQ3LXxZ1QHDc4mz6CW4GZBH0A80Y4yxFMbopt0cCMsoFKHHdS0u
OJBxXDNF8BI7MFj1G-SnOfFvzqdP3J9ZiZr4FK2i9CQ-mn0c4--JA8XbTXdQGym_7nAWI6pKlCcYf_v_YPb0Q0KnSH3Jdm--dC28JCwyoJqYFHL4bJ2PIt1F
fZCPnsyGjmzPUOoFJGuMBmtd4RRapYHM7IRqGGhu02Y27MRUP3vjbg5uTpBvLuX1Zn-gy1WRkKNazoFKuCx7YpvETCxv_OUWAYwo-pHhidwWoRpJgKCyVAXq
QUHC3XzdCawc9X2fVr2qVi__Kd7vK9DvfwLpEnADSFsUCpbzhicyq_i9HDa-z6PZw3JNv8LgYD3UPEmqFYZA_M2i4mb2OiHTdly2amcdEwqCPZermAQd4XY_
msJUwRuLUpZJoQ3f8J3-LIOxcsHqKYnmflE71eynVvF9lDDrjxKSAU-zv34cC6gmGSYRREzqkSsExsOw_LFeu4cAFId-1IONPvrytxK8XfXgt4wID4O3XDCc
spiTEouLTnZZ-Fv9l7EgDVCOlybatkcuUoKOxyTasLMj7Jn1SG6JiTDvHnUCoQfgxU09Z0kO39tkplOaF2PJV41QrcJiTBvReEaUeejgYB5PcsplT3_XUJWc
wziCtgUNDHaxhINd-WXYsAQ3DXZrOcgolTFKQwSmkePTocISpBnsYkuMhpXlNeOrk7Sdo4E8ijzcmW_LUgVr6YRpJeF9M8SO_RPio_rmHrSocNUwVxtRPaBS
Zjy9baS3X1OcspkD8VPj9fHjlmvuKhwKoJXfzDf9RXEphKewukozWCamvUuIAnulLtt7AkxnNhsgoTZflfSSjXbD7LnshaTHLZKPEotUXOFSAlsG4uSGbK7u
bIPZfzCHOjNRNjD5xr_WB6bo3xZVgmU8ei6vg7tVtY3Yc29iqVtzIG_VIkHDQYVzYyTPoMIS0j-3bjl-8ddRgLtHGQnCzkvJ4WH0xEKmzPbtfphC8YRpJiV-
LNGkz0Dax5J7MS9a_fSFKeTON4_UgD8OzRA4oUDzkc_CrVN8uIm-ogecOwUp2_lBbemXOenjGPEnqpN_lF_qNUoWL5Or6JlzCto87Q9NAcr9ax7JnsjycO2u
ZidOwJvza6skGwMjR39skdZdwWJ4vKp6JYU_ULsj8MO7yYLERn25WxYQoVm-xNc8_qo6Jczp7HRYFvEnqnASopp4VoPZfxCPH0KcVwlJLLY8_qp6JlDf_qm6
YTKEeaQtIh8LnEmMYXSBYEBTVzktOmE20Y0AWW2S_ki5AS0zuC_qiE6Uf-dgbwpfwfUiwUgNhEdgbwpfwfUiwK39cWwKhEb0oPeEbApfm1YgwSrvzK39cWwK
hEb0oPeEbApfGCcQ3fIiQIK7veD0oPeEbApfm1YgwKx9JDT7WP8r7IXPq-sIcQr_lsG000000000000000000000000000000000000000000000003O0G
}

sprite $image121 [163x217/16z] {
xC6100000CEW-rCVPDMQ000000000000pfoPQAcEmq1KNaiIx_-_TmRSeKxG6DF3WwJUllPDRaLMJcSvUL9Jd1koGg7Qavmr1QfGGBMU4p9tlU6fGXNbb2LK
G0dPy_bAgEEhOlkkfNCv7dIASllfW4Gzb-D1c4KApbR9L5b0v3koifBd63HAGee_HIN9SliXxsVu2IevZ0P2_fdgePNadHg9HtE64hBdmqf8YXuhrnMghEHH
9IIZrYlLK5glFzJT9IZgGINSGUHcRLo1zLHj82fjbmDAo6pCs1mh2VddFNsvX14Iq3okOdOHDNstX37G7zFXBt40VRM4CQ1fQCWN1b1zT8mOcevm7407E6Oc
fW458L6_vHXz5zpIQPg1-iKLdwnagWHaC1CM1hTThZ55gEHd1mtqYQ-aT6n-6N53gEH7ImZjCWbDu-gOyKzKSfHmCcgIJ5CKT6p-PuEqlpubAtJm0HhJ6rEP
yc_gSBpTEhlS8VMlhca5WwsN5Y6fNzLYw5W1fM_Z1REIRvLmwmmRYH7-T19rDX0A-FRJ0GYkQMzFmfR2Sxq8IyW63c33-4zQtK6MjrQkdX-XH-lQ59U3ndLK
aA2u8wNsrfh6EuODaUerXICk0Dvl6JP8EhwBpMqn9TSbt8Jrj6SVLXAMZiTD6xXqJ1OfYm6qBY6lK8HfTVm8nRA4nZkg221rc5eFeFNAfQfrSdnC73Dck-Uu
Ja_LrstdHy1DGxZ2ffYNK9sF2Hrt4gHk2cLUFXCJIxXyDwgAw9XJKCTZCd4yMT_NbQpFzdvxq532rcfyT35-ENCSFawevD9nt6bk1-yECIkYOqAg-NRuFNpS
JCSJo2QJ59yZLWb9VAJleyLfrrzr73jriJcYcGAJTyyO8hA4ZyiXXzQoIvJnHvyX6Xqi4PjYjrOxGDytmEWOKyUyrWNY7Z8YffHpBhMsrg7N12Z0EMW0Ebwz
XlE1MoEQHaYqtW7bPZZ87muJggRZz2l7hoAoaXe3XYLqGlvVnvJn6cAqJQnmtMxWQJ9pt5zm_3j4sbvVju8VuedZMnQENqTSGxA4d7vJnz9USan4h15f6min
XBIzu_gu8QFaKkhqMd-FICXdOhXHkqySSzxSxYeMr_eQujesdIeXnwyV7HUKxMSvBfdZMjz2T496CGOsC3ZcKgWzJPRCuFZtYAxmMCbmc1WV6TqxRge8QnY2
utSG8JLM4hvNwpl7o8zB8LhhZVTL4Ho_WwWYwg6I-_u5n_kb48gm7b76suYc8bVLZxP1oEWuVXezXPSobd22s5U8J9BkvgfEsm6IZij_BmnxnAhix-_lOXue
0R4bc0L8lqBIiTRPmj1RQ_qUn196n2RJDDj3PcbktYNTRU_RJiSzE0wXWGMWLtcI37SIUf7gvX2nLcCbeGl78zXd1NXXUISfwaIiTyGk2HugEGY3urbUSMnP
cBLjRr9yp1whWpuSDw3ZzLAe_Zl7QziEoTSVHU2kPT17o9he-AqINdfmlBJjMU3RWstfHX_Nj36noygn-O9Ge-ErRLT9wdv3l99caUOU1v2YzWNWcuxdjhsB
D5p1RhUqQSxMesternn7spv6GFDj1C4IRNDAhbwTtd2yjErs5T3lYEvv48TAVibnj6tcsjhFb2p3j-JLcmCJ0Tzt76sxEwUaUP6nez7sCy1FEOxFza3CusPc
wUwjcYzi0_OXnz7sGEmROf7YdYNrfxRnUSTCLH-8QTpCciKi3T-4FC8nauRjcjIlfAM9geW8FBxCSj1ymt5yjiVDB906IOc8hEHN7KVRt2qaLob5kXj3sr3_
ekDeso79YYHfLHeHQHlwRSVnsSvYNKGm40EahHtB1pDcOJSL4MrItKAES1njtrR8PBVJ9kGWnz4sKlO-GJp4SRJjXd7QX1pfc4dT_EVHZZdISRJTYyKSwpZQ
NY0IC3Z-Zkqr8XqNORviE-Penz5sdDpHSHBc1BRzaT22uwDj-uFZ9in9RFlECOBZesox4t7b-7ZRld9yl6q_c-Desy_cE7x2mOFZqzdsqpcEa_oaZlzf3quA
0811003jdlqJ-pI4G5bnHqi0000000000009
}

