sprite $image367 [354x273/16z] {
xDJL0K813CNGNswn_QV5tIqyIqOubNb76ssQ6-hBAklBAklBAWlCAkiB8-lBAklBAWiCA-lBAklBAWjCAklB4klB4klB4WjC4-kB6klB4WiC4-lB4kjB4kjB
9p2UldZwyWcCfo-UldZwuWcCfo-UldZwuWdCfo-UldW2u-dRDc9z9Qv8Z9OQZokH62fP2w-hQ0oKlJ2YB75o40QK9KxEX7-jB77k2w-hxvGbJfu8hwj4uWyR
rnFXBvKbNjCzD_xyBKkyTNjc_Bcon7krC-AMAdTL-8bncvIxAloviSJl29yJbyI0yBbn6pz5ggl2IshkHMjr58O2S4gXi4FV_tbdAHBuIQnTzUX8vkemrw-T
RKZBYV6oyJU9UTyngN0WbognCluLOkHztm5CAamKhiOnlkPRX36hiBiSn_XEG8WmCAqmBiOnlkGhmi2ameaSBiKnFXqGIXYJ2SSgJEGltSRyGL_UMsMqcaeu
9rU5wLeSyqS3Ge0PcCyu5xteHPXJripyloG5v-U-u3m5C0kU22Toh8HV6-Cp0IobVFTzafGGuoPC5FYccu24hnFR0O4_LV0d4UwCawl2b6guCd0M6TyAO9J5
UOGp2rxiX1Cdkr0hGH5_AI1c4-wZeWcJFm6XYB_YEvUmCXPXTrfOYZyT488_dt3c5iVBPU7CdmzWgVacy2pJjEsoS6PyD20c5GQFKS5yGVZzCCQh3crMuR14
5SVNXJC-5H0J2nEvfE8uhXU5CpuG4Fi-kJ0v7STyLJZZ8m4ylp3tnfU4hnEV2U3vXTCGnoU4mHU8BmVm_C943eqOPuIV6lC70c9UOVQa9_0Cd11-RimVwT1Q
vTaUSeXmgnF2XyJuK438bPX3kFea4KvBEdiN0eV6-FSTMhiId2UPIx3mY32HuxF2nyRuJ00NttacFsBCQnKcmZbXumMXyyHN0rXMPn7kfsgk2gTpmY-VIEEV
1p3BwZp2_LGjDc4NpmY_CiRx0Q43U3fXYOfh4tW-DEOp7Thv04QUTm8lSUp-2kDUXxlcKyJl1uIipYcSMNpI8i8OhW0pSs0ax_sQE6_vbR5kZ3bV3-0fztJs
Gmw8S4XjLIV94iyOurzrQBCARu5L78km8y_g2g0A4xcs-jmOrpkq5i1JJtwiXnok2XFfLVP4d7E1Fd4Ru-qERVhPcZVYM8I3yOMON1RXzDeOxtPeqmixZSYz
S8IEOn5sosjZlkHh1mIGfnH6w8q7uK0wh9imqVegZey28f_eqBBy8Kz4b6OKJaCS5s5VXSquNgimXHTn_6O0RxJNtxdNikzpdZ9mFLFfX-DIXPqLnqiJnf7n
MnrQMkWXlDAZvX1kdO5vog08PmvDEB6AOnPXvmxY-6A79gn5s56f9G9J00j02YAChTlk2baHjkDOXAdrpcgk-SuMcQgml-468iy0vpby0LOJ-2KrOV0WRCQn
gyBadiNnbOSOz-AxiBzzkkVOleV7Npo1By2DAQCA4wqimhAH5c4otjUCInDcq_ZY5ZdHjk_ai8TztnSYujigDihxFWCmUEWCnWaykjNGX5blf5c4WttmyS93
Z1sERi9fJqJb5bvkgz7TGsC2Nu27RPnhmh48vyvOX9CLno9inl653krEIbk1ffB23k3RR_ql2wChxfYi2Jo6RPm8MwCCE9KaOdnfXhOLuVfDHsNGTFyjVbSO
C8HxOoZXVZLGdoIoAd7S2ylobGvD2sSgNtIHYDRzPuMXXCtEG8Jrgk-4MQr64KvELYzqQ5euHxfLskuVVXKOKCBsGuucR1WtOGfgjK-Ie8nF1R0jZ4XIwROw
WMyLJQoOM8ITqrCr4NuQnwHVWpiVmBOmemF-JM7Oma_dPZA1zsgLGtbhvLaSzyAoVBP3oxRmlY_5rt5PdS5NXDkjoA88FqpWLHoBi5xTch2N93eJ47ab3CAP
7yA9YlYZPl05-CKf0n5cVUok2Q-RCcx24iTdjiZXqOZ5BLPX3zIv16zRsgLcyEs5XutQA1nSMpKcy8i-QSDB5QQ5jR3kq2efoitgH3WNuR4c01w4qz_EO10c
Awn35IRQT1nlz2T9NdLe8fpeNgby3Fl-uyB0MU4-ZcK2dnpf2Nm_ocWJUBqQB64xW9jmf5A-z7tRZmlZkBX0cASCwWG-zi8wZbc4rwYCZuKbW7jXAGVVX1UC
5sSEuDOPY72BOxIvX0Y7jOyADO5tEexpeeLr0Dl2GOIZ4IwOmBSt5k5K8vNR05w4dyTn4EZn2WGHDWD22xiI3qxwuM27onI-R9yoI29Sbx7OSpCPPRG9l5xr
IjXwpGJf8Lo6E-H5-4cuJE0ByB1HKnDuMSrRBwotSL64en77Wx3XcprjXJGmxi9ntoI0pN2P0HWyT0PA-CdSJ6-a-mcyCryGiZkqbWzLEA88y-tZTj3TJU0B
y02HcZ358dnYRgQVbdhZDduLm2BCUoZld6p-HqyPu7pnYrC6K7DDIPA5hQcQJX9PDGB25jvP1cY7tTq4lerrYEExy5g4rOqgIMB5iHTXJiFV-jbxVdwhmjdJ
hKedyNJ-9ZK3CDZQHB2J7mqCLcVGXCqubYGPHXb_GXI-tAObQ-i4mfCK_-Wf0-2Ii3hqnIBiOrsraeICgTfMXOVkk0lHl1R6Z8KwOGusi1qk4_XMuM3SYYBi
o45T0LwgC2t6NDCP4tX6CnB8j54d76HFvt_qb06k2fkTWVT7fmo2USf0_X_eXEiwLzz4Kjj3EFlsJRSoijMXgPh1jmdJgkCOXwSCUCqY7FNrQSBoyhQynZCA
1qOdlFteAGFWFM4tnF4e7FLCfmaxVPStuJjX5SwUIhak9JnuhS9hVXN0KZFuziBZHcqG3kJwLHw4oK77yQ8cy3Lem-En9XVXdAa89vWTcbqJ08_2mtT_4GvL
kApgE9O9l8xZpHGkNLevAX2Ai2l2HmDwNHFuLk6qL65Qz2c3v8vE6R1hmZgEsHR6u-ikiATMnrjaNJFu2aGuEcMGOnJXP9p15M6tw3YsXGlm0bJXbLO-xj3q
wXJ0C5vmGE3-6SSuWLyFJncuPBmjg5EYR3WYUADId8xVOJDNv_25DO7Vcd2_KND7STmcy7gKqGktsbXwutGYW7Ly_BYlFcN08aoEHRXr1aTpCxWcp6gLsH3U
yWtB1EPpRxXDu7iNO0X4DpUhmlsyOHLXrc708XnK79VgztFow68xkKN-ZxexKP5SXw4mJBQkM7d_vvtTSwP_LAA5ns29_Uxt8nmKEN9v_Li5u6PWEYLyzHns
vsPdj6N0Gmu9j_u0vnRn_J-xkY-t33Wtq_JIWhaPlXRqJqifV2OMyOFuAE0RR1b863ET3HDuJDMwi1F74cw1O69Dlm2mX17744Pd867dzXGb2RyM_Fc8lYBX
9xU3iBPll6NGTWc_uYq32xOCCChu6G4KpWUmQd5V2Wk24_Zj5MmPU8SSThpVChWXdElG85p0Ly9Wah3cPeXZJE2n-FXkoq0vdE_GM0M08SmuVeLR1fVcPauS
loIytsg8VmjlZnUnwVwjW2-4QTomPK1Z2U-NHLi6XwbR2munilrR0Lz7M4mGlhOxs39uToL2VywRXC-13Wt21NmTORLN44PdyFIrBapWyO4GfvUFnH6RYOzM
0DWJ5jDlOJl2BOCBmkYT8JpQeL5_MTzOc5i6zovXRswcBOFB1hOCyd_sPoth6mjp0c-Qm6F4ZWcyi_Zux8ajWqJ_rcjnu5ZOtp8ud3ZMbi7fNOaWuTmhSjnV
c8pNySqBgpC8jmpESClWQX1cnARxj_Rftg25VFF2UecuDmZZ0o5j6Lp9BODy01jllbh8Dv_3OherrVatZeqJUCGnXTcXvVktfrEF4RSbX9Mec9lXa0EdfRip
J0e28XiV4bRbVLSHbZ5kvsXE78TR1Z8Q2mWAzyhvhYFClc6BjWpkwwzmurnpi4EJBuLLLOLvLYVXlKLR1XXb_8yEZUAiii9YuWJ-yhfZtUxuAOx7EpILX54r
SrXC_5KKFuwFOCjWC80flAvnNfWFgkPctY67X3NN7E_GA5p0E2dyc7ixnqUuPT1xv_4EZS8LYCs-9jmkYtxBm8lZreLxxnm99liB2LSm_e8mR-77t4pZCou-
OW8_tA7npvKsfd0_SkPh72RmEEHmXBCJjhVyZKNYvOqfZ6k5Unn7MmOFXDC1pCURmlKUurZufsEmPO0ufl1uXqRXciQnyE_tDCvqZYxitkwu-yAMFmEbS75Z
2lVQdUyrkMN03uGaF3w2ft3TEAQmwdBY-9JmRVwMGRf3ImXNUunZOUSAHapW_KEEyG2cS6NZMBXlTG7nwCAOgabui4EZS6rZ2hCESrwamos3uGwDmcM9BHQE
urZ2nZWU3mWArpMEXLLuaUQlek2GOxn3et1buqWuZcC9SmStSOYH4Avh70ghJY-Eqxzbe03E25Sd_eem9puwv92mudWuW2bStJWbpAKl2IkjXpiq_as5ZVF2
mPP1Z-Fn06Qgp29MBIRCkIQs34PUaLdoBVeOIzWomZJUSSOn6i3qhVuOw-lMZ32NlYIyGa18E56pXLkpd72yPK2g0T_PmAhPmiqi8So9podX1G92lgcQBToQ
NIbXxk0cjWmo7TfyODKqOTMP4EO7GlwMGOc0K4qNRgyz9_nOj6NGdY81ePektEmZ9SmZa881p9echBeImZJ6AtAD06PD4rOTWN0SnsKwjBZc2IkEKy9wZ6i7
X6gUiE8u8opZIXrQNDE4LMTEM5i6LZeWLDE4LNj2k1kN3c3MTE5sRpdXnue7C6kwSBCh9_oK3s3MD67LcHEk7n2iwSBjzntntzct3nG40YW6edIz_ucbXnO8
XAWx_1pXiSpsS9n0Q3jXNRczOc6IhpOJbd4ip0g4jXREZMc-sbOuDyO5Gfi9YpWn1boX-Qs4jO0O6GYj5kwD8O7mAuLxOwglrWdtn9m0-pN2lJ4jmBtnEnBE
ZLc1y2k4IsDu8BH2k2F61q8hX1jZO23yXiBUcEZhjnFsDzBC0FkjXFrXZ0jmRnm9vyRqGFp-N_zr88vu7OWpNlkUyJh0PxmEy16l0t76wq2SyTZtZBLFEtH2
0208042iVsh_2gS2MuG5mOhzFlps1EVyzlps_FO4v_ps_FO4z_pc_FRyzWJd_FRyzlps1EVyzlfV-c3oN_fV-b_wOF9V-b_wOF9V-b_wN_fWyb_wN_fW-b_o
N_fV-c3wN_9V-b_wOF9V-b_-7Rm3
}

