sprite $image50 [223x171/16z] {
tPlhikCe30QJs0OaoCdxF-rSFRKXbTv1H4mPVpztvzP6RIIvpkDVHaJaSTQe_CvfuVRe-UYaYfxlw4uBA7NEfM0MoZcEZgFdWEFaSy1nlauYtSaKbERed72d
1HHp9kjHx9dtwD89AfJXbiijIaloX7MvNNvcIHCV8CE5wsNFEgk2N9VnTlalrp0b84ktNggqAgWJILTdILCUe0XNPfrjlWeLbJV99LM0aogef52vb_t5sQNW
qJimrNBFwsLc1UL_exaKNQPHaE4Oy5xIjLz1FL1TieAN-HIKncWc1TVZAYWGKb3UANWzg88gcFaLJCAPNq61Z5LG3mJ72juEg21BPrSm7bT1UPFrsfpmIy7y
Li4bDl6bSN1VyYxBfJbXhr0zuYqeue1tL0LLlF14j822jp0Oa6ywHxpV2cxz2eewI-UATom5HPpnN1HKJ-diUBVrDTMvs1LCJu4JT8TZl6l8zvTagTAW8Dsl
SIVsgqjxSTvYhgDInQPWzQkYXu8Y1ZpJD5039bQGyJu5L37YTUx4MC7OWYSw48xnshyCAIkO4AyYzwrBniDfe7TXk19UdK_XqfPQy2HUlHKCX5VdevFRhbML
CHvKcOE2ZBUdMxfuuoghyO9XBMrHi0LFkp_zlrOPuq6LEIW8U5NiHvTMg3B0smToVmMN1ZnHuzWJhd3R0bxJYvvJFnmELqAol59Mg3Bw9G7MqhqACXx7SjD1
bT4dz52jfJzGK9OEF0PK-ekuoeHFJzmKP3m3OB8_o0tmwhMqRZ0Dz2h8UApWH-t4TdjATFiofBbIaF0u3N0jLPRBKrIgs1JSbfUiovNnsW05qbXbX6TNi7zh
ms6wvYhJvy33eO5yD9va5OgzokmFPooUbfor1hGhkCJ-ZxEtu877JkKCWBOgStWutNZyhxtVOOLbhZA7X-EAfp_XTZmB8CsS3Wfkj-R4XgDxmXkbe6ajdKjp
j06kmXkZe6ajRSVZkgpnx0hU1YYepMc0g_2i5Jf6GKkuBW6F0BdAt1LqW0CyGuKELT0Gg4l2iokO1YZe00Tu3WgwVHcoroNZ-IkOXYh8S7MY4A106hy_NjzL
MOfFiIuCEGfmEKgC-X6WQIrThs9D7sVjHvVJJpI9IVD01HdFy73iS4MYb9_kQOhoaO8DLGPuXeTZXDEOyfzNYqON1HTGaF0C3ySiNVpDlLECLv3nk4-xfMxf
NWUYD5H1nkE7SqjPkwMhxxtX2W8U_q3LDUHxQPWCGBeQpqj1dWO0ZxQfgzvBrWOugCitUECLhF7uuInI0AwbBX4lguU2l9QkyUZXt68lN8A1o5D1tjalDy2h
5NIG3l3y5UH4-Br_ERe6wG1ll89Dd_yTf0CyRmNDUFqTsDi0XPU2gtdJR9SknuZjIme4A6CLP3oxTFmctOy909DTmVGSqPo35Syk7LSil2dj2l9F57sEfye8
VAYwlrheJGde0EZmbGUbCzVbd_y3yqBt9U6FfnaHvAyLc_TqAQZgXESltPud2WS5tV7wf2klrxg3WdOyD-duK5-EAVGew83dNfTxu9Yw5OnRSv9p1rPozNyg
l2O5G_fhXPPxSt9V1vOixGiSKxU2cfkZpXsOD0v4wdCBSaP9XtXE2XhYAHtF38y77rEFWX2ViOShbk0UmDUhuAYZCqXNqG6WeuBZfMEuFNO5WuE23cCFrcKT
xL1GZ0hsTs1tFDGME7y5_UkIjxPCLyVyfhGhQ8TBTkaeTWMJYu8eNTzbmE5ZSbWOUdTW36S730uAEacd1kb6AzZVWPdR5qOQh-3u3gmzEbJ1yTBrAfXy5FJl
m2Xs1QL3GQSEZE7i-Hgd84l7TOd_v-lHcUAkeF_OKphP_1KSBzq15EoIJbtWnYi8SEwNWSCj6Emx-y4TcB-2nWeTsO7vAnY3SLi124xI-GCQT_Okqdqz1YHx
AEX_6HnAGK0OBXt7TM7OXb0SnXxdMr2R5Foi0tkCJ_b8GRDqt5uUKK6t3koO2lv6Y8HGaaDTEiJSJkyA_a88XiMpvqqt_XQy5mdf63TT_yAGqHqMptxnRqGT
llOSMK7NiMTyYd5dR-Z0uAOxj89JIDT_2xwHBXYaExg23fV1qHHaFCFOCuU2FMFFH0hQfPjAmQcait-vDeuziocuIpT7NTeRqPzm6XB3pG38evBXCfXGmPnJ
C4WtdOB1i7YU4D0mzim826FFZ2bjU8zf0tW4DpyWqvsYGW7kB0S8S6S11BYp00BTMG01xYny07SMG80x2-0_fliE
}

