sprite $image417 [294x192/16z] {
xTsBSeEs5eNXqpQ0rje2lV_R7eSrmSG234OxnWp_kLzAXs-q5GM7D950UjAL6GamBNLbdamWpwBavqGIn3cK_9pCZ02wqoZfVXokVOxbP4CixfGjqnCebLzE
e-lo34e-zvFvdq2f_DZPFPB0APIARoFPTK-WLFv-PlpFeQJx-V9Ofm2xZrLo6Zk7wxvRoM4RTxZk8PJAdfuShlis9JydD__tA3cDtU9rUHebtKz8Kn5xhYt-
ioZ9gKkFuRjzwnJW6PJcnoDWlvB6-JHAkHDGG6dfa4_WivHo9moLMwVvDFEuIkJpxHQXa9BAcQ2E_1IEjkZK07LLDSMKyks9EBQI9CZb-scgiagwBZaO7Luf
HkEI4w6b58c-i4M9AyOPJND8fLyeyTR2s15IiexhxiGsZBFOiuLwZ8m4nqfnVko8dgccOOFIbd6kgweEHrIoaLDKPkGaaWghzmvmopXhAR7b4PNaD59IyqfO
gqG272bbJjdLgwff8_oKI6sdhtwm-A3Kbb3I66NZZ8M5MZUabn97RLPIFafZfs6HqbPTt8z87Kd9Z1iMgfDInwaEewJUhMISxbXAzbQbXhDTIZ-12rrAYijT
IhS2BwNdyMaRbTIfb4W79NKU9JegsLcKp4r9UIXj7-VExGImdSacSr3QFCvMO2KvAYaN9Vip9VefaNHKKd-Yr75rsF4HYfUIdCnRYHlQh9GzItHGKhvAz5MA
Sd9H8lb7Ifspql1HauDITbqt9VehwTaq2odbu-olH7SbPJIFixUMgRTIS5RoVoOW9rybVBwInjbJYVnu9Jd5U20bVFPJE7ldKhgKBgLv2zimS2TNMbmmbzBY
AM29CAbhBQN2IlPu8_mWfUSE9PJKhniXo4lfwITDbDEdA6r7mWjAwduZKOyxIYZbuqmML9f7Ah6KKhI91gKODNO5b6R6sLa9PPG8JZBTxqfZL_oJflXidAtm
hjIyFd3fzwCCPZSbfn9AIahPuwOP9U-1wpRz8gdycMk-uMvNIfmPv_nnaxyIzlwK5uUn8q4MK-BCEEkVit5sLUfsBANivxsD04ifsT8un_iuMn4bJhNx6A1i
t304fPJ6JWGuFSsjln8BA_KSP26bV9pzbNA83Wu_oMn4AQLydBsK6auMvd_-n5vNKXPZAQLyd7sKk9JNkmC-IiCuNqf3SqTKEuHIEh2IBdOg9JknKj7tuywg
LFejGYSbEu-Iyb4oUvyIKd4bFULmKBAtANqvA3a-ztwF4bBMmT_MUOCIqaubSr3QECx-IYdhuzxMyLVgKjQHtjPnLOB3IZhVspfqK3hXspfUHlcTVFBREbmJ
2YZnez_MSLjA-Tiw0Er3tzPnCigLeXdngM_hW4yAfPJaHBeeWVHKIXuhQVvj7NxgspekIDlVrccQhKhvE3igOGEItpE1fgggi45frpWpRQ-yaU86fI2ahKhv
EBiffV982bojr5HL4wFNspgXRZAb8aoDms_rN5vBxBXUYRPneTQPqcwd_tdzLi_vVIdKWHXNS9ph6nBtAYc22btXlroWnnFT5DQFCsvAw9Wf-UV_MpqBZdDJ
rR75OPMKWzBMSMx0SoevZFFnbSn1oOndKp879NKQ9NKfJMHvJafsBYLpKh8pAUb-hB2IEe-Iyb5wFiwNahgKrespPLrAUUMLBgLBwLAwb9hmLEbIggigF5Ew
bAggDZvHkfIQ2gsRKbE7i-pUD2-bK5KrU0ebabvAJLKXkYdPTpJUi-zSb09efDl4nV9APaQ5h46BfPNCp4k9855KYKRnXDc4PLPKYJ6sNaeWoM9AqKZ-yi5Z
OQYNAgXaCJef1Orp4QNOWuzrEDa82wJX-6j9dvgNK0hsG_J3OttnTzOdgn-dOahHJwcDSR-I6G4HaHHEUwlhIwhhQzjMMYGWfvX-Tq2bk5_9o858RvU9PhPl
gsyfKaunFVIIKjiUU2sHn9seRUy-ij24aPg_jXl_hsR4DrDwxANTsuwcb1lrH5tt8w290YRF077ulyKvflJ2n765Kdh7n4LoP9JwskmyC45bRUgJ4z94cvH-
Zjv8JtDVIxaHP3GGcHQNGj_K6K3p-OCAfgcuGQbfGi0wfSGNbCpmef8z6hKs44c7zf2iXiDIxESk8eGqsQRdIxDhQVSuWz7uefA6xMwahNZcE30-16WUvTHz
uqffilNFbq8xfxHxd0D9lAIaOQEPZ5Aq_3WmSmhefO3XK6c1J7Crwsu40RP1QTCuXwgfmqjAHY75RlIVHHIZWERheKWvcI5OJ0iL-GmbBwnNgaBa2qf6QDYo
BKhpbvT3cPo8W3Ojvg2qSPpj5ILII0C8YM4RNrkdGm12O9UUL5v9hHtdL_QbAAGH2S1DHkF3Kc1Cp_DHIbzkdw5e9SNnc8GGsAQjwH10wz8Atl9Aoad9g9MK
HWNDpTOYGu2rgQEbvvLNKWvAEW88wHvDN_AsVWaGKiAwFxJpKKeih9GZgRQDrF5do_Fne2kbYBN2BAwaIYdD8wbEAsFbQuIcOu06jxDUUEMG5bTI9PLi1abV
s87X-zYbp6Gqx6vjpsHfNJvAYQMKZBpVMbuRzNt7_S5tcBf1YcXyu6gjnqyhAwwaoYWPiO2aXsyI6AHel-BzoHCuEd1rEe6brHLNKjrU9IqadPEMl_4GX9hv
DExndAwjYMbz1PGSnjaUlhrTXkgbiF2aKaOFntc6jA7oIch7MkgDLY2fuICI4hyZQHdHpyu4IrjoKahnHIKZ8QDsmuptLj76nTddJfsKjZLwk5678ahg5INA
I0jfQtf8sJVw0BEGKWAKtln_WkGvpf73iBMfG2vAzGyIKw4shIKR6NNfi4fLLR4r81NCy5DTXwMb58moqh1vrkvSItNRmbAPyeLQDRD89YD0HhwrHE3BIcWQ
4gbiepql400NPirzs5HasAE46aXkIariYPH7hQEG6JagWUdrjPIKpyIXDRnz7Mdptg74LBHyd47aH8EHPKQEcpVjjHi9oISCDOz6qM4TkMrBAG3eahCIyzs8
-3iZK5dN6WD84kauYGWpsv6C_B_uSxA3AJq8ZOZ-PjOu7Gwan2RRi8Tb92FlE5SwPD4uMaQPaH-IrsAoqkp1H9Gl8tyajyKK-RkzGaPY8AB5pCWhkYfPiUkD
5b4sQVvX8WUbFLOc8JmyhC-Cd952tOm-KXanxTwITYl5iL00AA9i6Rb6a0p_LdNrzVLLVNrtNqrMREFUJZMyvu2x44ZBzoB_Qh3jObFXNbtHZ7t9Kub66_Mp
xen6AWXe47e3aIAiwxhmIwbkkywmMucl12MS2Q4klQLlfHPVk5SrDxS86fEhKdYQHbz2sedU5MZHmbZfgubTL-3h6q7TvKoOfL6KZqceEy3taV-DbKAPGm1H
_tlhloaRK45bbcRYsGBapzJyz_LLtQgRfkhN5ItjpVZrl-z-YuJwLgC_nKHH_RmDaWxJyAMagM_f4qSo5LRADsbhypgL3XcoKe5iMQbDLy-LOhfr5Qj_RltB
YORrUXNn7Orv81dIhQj0pZqLGBhQ_8JfobOeNHdFh_H_
}

