sprite $image46 [111x81/16z] {
lPUDRkGW38J3Fnuxx_-wTqkSqXLoMLbDHpztRL4-iCT3ShXKA1z_fjG1jFWtiDW08W9gU1uMAe4kuVcAvW5J0JqztJJwhYTR6Eg4JI2LPrfOQ84zryBKGOQ0
7XynlmsiuTcchIrymlosqDC3vZVqIqCHZAOzqy9Yr_7tXo9tW31bCQRiNFERVzz2f_bHZl1D7RHeh3ccEWXKVER7UoTMtBgcuMgXm_ppKQcrsfenRwsrNiF4
6RcsD__SUU5J16gCT_EmYCo7DnX3iJM_ucByAYy0whNaz5yvrqONiOLhHL2ScMjsyazSaQBc8QeflBktzDlvaKHnTgxPvf-unA95ZL-iRz2e3H0cBUP-AARv
LvDd40l5hqMvKMlCrElSUs41KLo71LJ3vyaFPXw_5DnhvEGQZZGSmatxUbwBH0HshksJ_xOVUXXh889oOL-2IBjucAkdhFUrVVAFKnHXr7XXhsac2CP6AhQv
zddoeuuZoBNFs8KlutM066ExomFizxMi_TqSJWUfYjm-Eb83SHqRnlPg-ZJvqQ_6HHqBhH2ziYGHwFehsPgvDirl2-so0zVNvkujT3ub3fUCJUEZonwWhUu7
GZWVH-Z0s44g8tJkizDU0FCdlAJt3mkbsbAxUE5L74PMQsu5EPaLk6zU912nS3n26oTEmY9NfGC-WPq3nzkAyZX16cx7wwmXZ082Q45Fle7nUIfk7j1C5Kvt
680WbBMEzoLJURTVEITkNr7cS4rD9G1o2hESw3gyMR2luyHP5KK-mb7mVZN7N6lhlTSStoykv112WL77YJCEg8xCNoyUAHwh59e9OtM1LKV5cK355OsVq4MW
Tzoy-rYaNlylYZFgE74c46dUuLMOm2ACtceffROE4M62i5xsKN4BpCOny8QRRs8C3GQvnRXxWxaGIzCid0ehBlLQIYNGAb2jjVUuubZE3Kw5YTk_HRTtvy2e
uyIPGEGFlX7w6wvWrj766IraiMmqXMMVMaSBPnyGRp8YOra42oOdv2UWHnEsIa9b6mW3k4b-Kw_R8tR-lGEoNSUJefgNVgcY41l6-RjzFmBwwpY2TIeqvcqB
_NLSlsNJfgB-Eev4NPMn0VfWKiplEzu0VUOtj1iAUCq_vMYXm_o6zaFXDR-jJQxvpM-tS7D0b_bLZg7mcjzMuP-0NlFR2kq7eC_yxg4Gb_dzBNIPtpyKXlc3
YxBFDPVv_IrSOLpSX7skkSpl7mgd-Rsvze7v_LhVrrpczxVGPNv_2ptczm-5UCplppKPXtEOtvThSZhCxrHiB2VoyMTAQ8TB_m
}

