sprite $image110 [239x166/16z] {
vPk9tkEs2iK3sW3bU__NlHEJy1ibvjgX6e_hdkxk-gyvEe0yjxyXR9Hk_nL1uLzg-D-WpSIg0jU7nSOcoXU7XSg3A5tUjAFgPIsSY0TTsi9OsNJzYYxiw8gX
b7b35IvasiRRojSB7r_IwIAcfJsmzn-wSFYCallFpnLmiUs4DTphc_P1Um7SJFjXHrouTXsFkDYuNADZ72LTGGTSgF-wqH3AVjEQQ7H0IvSA7ota4NTilofS
nBGg6O7fS_Ol5mWVhvwvEAFXsIUV2F2zIs0qFBTfVGlV9J0QdZjy_1UihzOJvJC25uvANDZJXbBcFwg6frvNp5U1CuVFV54-tUHp_OfEnCUfudaxnbRZ8j_2
Pvryy1PNEw65C_6nkAfsWZe-35TwXpE6Z-7YDmB3TKUA3gTSLs2atog6wyvF_OJXCn_NzX_zNAQTZpkEnlriTJmVLs57NAYS3mcVut55OGtNFivAVtloeVcu
uuws3yT7nRyw-LIeit4Drd2nENtbiUiARNdg5YwLZ0YBCELAN-92TVhAmqtRmFx7UBYqyZRI5yLyxyw2zkZmKLhbTN2TFHliFwhkues6nwyhwksfwk0w4pfk
1v42tzqr7XKuFdoAyQxYrjielvWZ2zfq_Bh2W8hXUhIO4Y8ukB45BHvWMeStZxZZe8g5M4Kjusz_JJRSa2hycOwnP4_WRQ09lREWjLcuUXJEDorylt2tT4HY
LuOR5gLu7K_49HYEuTcuOnnk2PpmcOPhXpRGFDpelZBLYgDfYIVZeaNKFDpOlX9h-wK2G_XCncr3AGTnQsLJzDOGSdigxx-eJQuSt6fv7CSjLXlnK4grcMfo
moUUk-EvJ77SudZ1LVcafJQePff4ooCklWq3L0Vjm2s3zuCMxl86_8zmYz6ouGvcHwTztiQbOUwEtXhsFWjuVBSERWhZcXs-Uh_27xYzSvi3N8ts0_SMnutp
Il-HTznLu32l4SPn3IZEQqiG1tTMHLS3_4VUpMrLoU5rOHtSUS3rnRTrCXVLAkwswjulJ1KNQe41Tvg56w_Y9kSg4ppSEA-zMiFD5ah6Ej728-uOKMKEhl7w
i8QRo4P3nPrLqJwkUHLcuRPzNqeBDZOrx3q072Xc6tVB7DooyMfNzxHYb7Cix1zLPbveCt1zsW6so_lL_ug4mXOkNX1n6tOt6xY5LfKzsW7AUxNBrRzgKaNh
WPJMSDb24zesRhJDK2w5xIiFkoDsW6DDfBbNbIc2MxPfxSfXfOvTND_2yH5XRAGWbKQ_L1Ll5sxvOYII4TOCRRXpB5oT0T0RjqtRk6qNhL_SFgvluV1uhweX
tFXuRqUNQOGZ2LJq-aj8AxXCAOxBDK2hfbt3bGG0gRq1opfmJfvMBassBsB1nnrv2--LcTR1RR0eoPQ5OtjcKyimegRIQ1Skrn8mhODRG8MqQU4uhefQBVcX
Kerq1swmZdtSKd7WTIqSnVKruaw7LTt7OfOk6G2vgtmBrtHkN5c59UmcHW3g2s_U4KeLJudhlzexZ_Dk1aYYsBodpIfvJN00RgIEUncs6SgPUC4keRvoRFLG
VuiPuN7yvcO7LKq0Dy1KwBSdUaQZuKwku_Qvgo9OV4i8kBUl99UMyVFkZTulCh0koUICipDD-xc9xBrf3d46wNk1FLh37O0rT0TWVJAgJ3MjvC_5AwSclI40
jDwfU_97mv5MSQCgCqrROMNFB0Y9EocleoqBD_klFGxNhsCLmVfQFG7KtjdXtR3m-YUWAamvfm4UCEM4yFOa8yHnRV8PnScxHQYQjupFFgEbL7atiF7QVokE
7_1GGRChlSxZzoSD37T67OkwQnLNyrP_MnPw0ApVLdI3udw-NU7zavwMXYVHt1KtV5pS1J39gviKX4L5N61Q0TxuEBzyVENIG9zuk77JQlZuk9814klhRGm0
gI102LZOnUKHrfvuk77JYfdMm-s205Yv0K0X0E0k6Q3r630UqaJw7UCcRkS400WltC9T4g04GkaGND-qRWYEtfGCgihFawe1j40e7OEx3ilfvWlg0DnmmUKb
Zm1IGqZBM-GlW0_0zUjuwvhfxVMrd18jSn4lOMH3lnR26Zc_0okk2Y3GLKLXxtNN1_ZZwth6KUky53Vr-liMgoduXeKdD971oMTRy0aW25bwfmJG986gBRW0
s6IpejCjhXoTV1njLRHIrGT7nR8OkLK0eDU6Dj7cTYVzCLm_VFOBtm4oG6QkBCJu6XzGR26TUQkYQucgXTOLNofnNqabBC9exxKOBc3TOU6evflMj_38gmqq
gvzH5jnM402ox0ibNvCcdtoB2Ll_IE7QUzAtsoi2BRYaXtRkFGmyVrrXYbkO6kcmL1KcLyNLXr1tz9NjR7KyAdDVIIMxAZFSNc0vkZXkuVdhYgY5HrNDN57S
PmwnSfVK95JHyzSLSooiXnJrdei5KUQk-RI-XkUfm189dtWewSgz500a2wAIuOMRunQEcvRnDb5PHbvKoAf1b44ruiwlQ3NjjF3PFnfIMlXumQNd7oOnt11m
F7mcGVeMbfOmDJkPfUg6ri7rB7ny-CH3IQGRhlQK8sx0mf799qqazBSxO-ugA0sumOgEhztc2-eABZQnYmV53G37rXKGeeZtbP9V0w-wLt6bDPBT5KqdCwrl
OJkaSqi0yC8jzX7QciG5dh-kc1zAKX4M6QxeWonJAdgzZYUODhhTaJBYzggRMk20XQFhYldozvMi5fOdRkVIfA56SS32WLtviHOMAkdnH74rayacnLqMfkYk
_7WBczIxEUMc7MNhflh_zvLy5sVoSSBdS65RnoNTuj4u3MR8xFULylCZmOlQuoqyubOmfTwbO6hkzA0LJGys2LpK7YnuJs64h9rbowYuUS7c4NUiQ7sJijan
mj5usobSIcS0U1xNgGk0yhhzvUjDofnrnT5zfUrc2q1w6XaWkxXAgxYkQGy8d_1sXv_Rh0Tk0u3QEG5iuixUbHyr6YwCkS22guE_f6tSyAxyU65Rs-veCUFI
T6pZ1YQViuIIr8JumEKdhk0MRk_t4uHF_CgXBK64EYhOA5mAhU2g3brNJBzog9XwByzMiYouMTVm3cuqV4xILtALJW39S0aM3N-Pbl2fJ1llAsrIiFuo9G0a
1_VWTSNyAmVzhbAFgkT5OKD06N7zoUVygYCmQL_rmgNbIN5m5PPysFDRc1PO6vOozmp8XXjULvorh-IIKeBdi0I0jG8q3rS2ay_PGacaFd0P894kxfBXdZXy
ubSEKY0lmvBegXPb3JSMFgSS3Pdqyye57P0Dz-mTO_nJ5idAIHd9S4FhYlDRs6PX4HAojtk1EdP3IIyD4V974ANRDOIqbiBfKhY-XUr3y8lX-ljAhfNw5N7z
JwIlYwjAV7dSKLakZUjR-FgugaJNnlL3wVgugY9Nn_KjV7rSi_3rSKrP7DohL_JrSLNG37Vu2FlQ5huxFsRyeXQ-3ulbYmjg_qktGVy3
}

sprite $image110 [120x83/16z] {
lPUBRYix24K1Fp0Rv_x_vrx59V4e7etLaoRhFFhkqh0DEFJFfAPCNuUh0LQ-RIq6CmDQeY-I6-m7G8M-X2XWJs2LlnDiM0_cBuX_WZs2teK-J6hBm_hjrkLx
mGRUR-7bp9yATYtntJgye_wPFa0Ewn5_U4VzWPO-7Mo0OVO6p6x-KE-ifzaFbO0L_aZlhE3bmvR_RYZ-1a3J7_SEhh40gFoNmQAaAogECVzXi12wei0cQ7_N
EqX4LCvvyUA6ju9Tl6mumpYyppc6TouK4o2ypKuPthagVhovbJU78bJnUDxupFCjp73m-cs0aHDQUclRAP7Yu8Lf5YPcISKmlNDeem8nEjyOYan4EhreGazq
UkTATk1t5w4PB0ue4L5xUA4qO64YQaTlcEFTjPltGn5D3-JX6TxeJIxDp9hcnRkmn7mv52ijX3SHaOn34ECHZQwyvp4dMOAzz0u9pSASU9SJiiRCHRNmIUz0
MHwC8CDhA4IKCG_0ueKcEpFdgIqHtx5tLc29Y5BCg_Gun3fecDxGCedXCcP__B0PBhHoroAy4eUuq40MRoOAyMAk3wy_p7fb5g9aM--3LHoW-_JwesFQgJZg
dF3qfl3Mb19Fh-G9dOdXVOpj55vtwCOCi_166MkSgpIz2xBSUcDijqGUs3HllNN-pertlUExOfn8Vu1s4JDCPEvV6sq7l7YbdDPv3kqOs-E3i2unNvohE52v
lTIv-EMvGh_vt5WUR8gT3dqK7nAbd1DDRzxq4N0eU0ZHL_CwDoIyi4mJdjxhkJ6juQt4vJNc1fL9pCcvzpLpV4Bgz0PeQT7EbAStKQA4rvZFzq9x5grfhTf-
oZUz0s3HHh117wf2CCvBp9bFzr7yKi0TprqOtfMrnFrsi_GZejoLMdyrrrAr3ZJTdKn4jPJQxYOjfQYDTtAfMo_yQVNyc5UD4dBffpqrg77F2KHLOel6Enil
3YMkp_cSh940ta_CQdSexdLNP5oME6X23w-Bz4RYtlIqcu_tMCgr5XdTMsjDntSozi4Y7VPHLz9Rezg8nCxDntix01LHt6b9T9whRR25WiWtangdGbeOFbYw
-V0w9TR4V2VwQDSxolJ47ft4b0fbvEpdCUzVbsLSzuxGaOnXkHTCAOamK4RCo-YyUXsQQNhFWythwnBlxjtHmGsPMYOIwoRgh-RTURuCTaMQ3tfbGsqYbiN1
9Esbs3LTKR046qImA-aPCmaaT-SAbaJbV8xWd7smAoLYpjLJSjTYd7kbxBx4lB0RYYjhpDrxO-lUZGMtIWRre9tjvlrGt37ZpDAIWebh8JMgVHPxCM-7ufuP
SoPAuAHCRE4DimPclnYAastC5U3SaPA7TtC5s_JE7jQVc3j64qUTmxmKUpCKVuN4_bUcsYWRLUHYb-OrM1FwFNbOEWhHyDeuxIV5rlrGNDd7t2tBg7E3iVQX
NBfv3RPlWjt7FDnKcsJBCZwgUYosccCx5FynPd2jb8GPojapmQSPjtuo5DybDgHP8-kPJOXJPlYJUqsn3iNtgL7ip9hO97cXe_VkUfQupw7uFX8nLs4soTs5
CRlvhbg7ullCqTbT6LdS2qDJmSCRR8RYUp5xetOhRCBC5jxDK7mFdZ5NuSR9YuHtDnJVZtbG-1up9sKTrV-htjblI1Maf4nvFYyoVPBOaF36y1BUTIX-DkRQ
mkjCdqTQn4nK8r_GLuXkHlF7yzANY0tf_itddHlowzw8-VlUk0XztpjZxhV_dBuCwtt_MgAla-oT9VG_
}

