sprite $image338 [173x248/16z] {
pDU7ZSGm30LHKIi7ckl-oxqSvtBopLH000zVK3k-cDRHaBMnPkRI6pBMrxnjZYOlvdniQkgcVDPwQjfEQo8jtRua0bqbLZPqSvK8TCLOnNG3MCLqOqhafJiW
G4oturGntPZpgqtXU5kjT3bNSWjzoUytXnehcmnpfPinOXNJfG0nNRwjPhh4AgRBkHBJ9LOptId_hd70N3df4gkORanvH5EOvegnTSYnagvehXZRIeoLfvvt
gm2sdVTzzyuLJyMnNgpx_krZn-5OSQmQwtUFZUEnFgQVgwUPtbQ6KxzqR3ySApFFrRUF_HUiJ3rNJFgslfu9AmMmi_TjVLcPiR8opnKhyronCWjWPPuhLcQi
hCnpnSgCbPKPAolJLu2nCcDbPHR0oZbNZCUQiVBOLIk0nqPlMstEKtdib3blLRLv1LosRoSwRiCm441z7pp-_tUBh5QPBcjmrOXm2234iIVGLtSyafoqOfUI
W2yjPQG2YsTNn0zkmWG0ky07RZOgi4oMcom1mAuF7hY4wEQY0ijE5b8a0DWRk5XROx0skaHv4W0i1Zn4DqK2n62ZiX1FvMFPWGtanYU0bd4OB3Ockl7KiYKq
M2UwRqk0hCFWO3ko41_MSno-v_Im_IjmVm9a6vv31jiNtVZBAakLZjF21jiNtVXcdP-l4nQfnVP75sjhq7MTIHJ3Cm7N7Ls4DQO6TlbPPFFfQBtDOtm2C7i9
wsbRzs22jYEwWLGbT835Ce7R4Lqa8EZcEl0TfYSMt8xeWjezHwa1KJJk0IouhLcWy0HWPFh2yjC-3GRBt9C5r5NOtRNMDVT1jzYEw281WHUMIbXBtrhi_qUN
A301cBEi1eBjmGNsnUZsK-NSrlMG-kNwm9NjThLQhAYyb8NkiCfUDe8JVNzTlYGVgwznfREcfkeP-Uy5GNx12b5pTA7jtGDW5a4NJFgD7SShh3oChTnQ0TA7
vRb2yK-_bFkhOCTTfWiiKvtMB92ezc7v2uBP7jyitriAZjLYeMtZ8kJ0zbZ7Yftmdfr5ornXmMtEWdPZby8YtgjML6L033mijE26Op4x5FKsOrN6HNQmVXRY
iJm2GJXnCowoW_MvyTW5RQKw6YmsipmwM2UweLZwSHQOdrZvnivIVcsgFp5O9xhnsEN7RRI2D7pFAYfSmxo9mVfP2COoTYkFsO35yZlFvHCSSkbaRkE6OQ7Z
2-mos1bhVe5jZ6u_5lVuAC0-yOUrJgmEjk7Y0Ykjl9t_IS5iiL9kVmpY2cmxzqMi7EF0_om8Yqd5M6ysp4ogBjRFmYjOcX5G1MWrNoyr8aYhg8DjuhPZSUW3
5bkh3KM6Si36SIebu62Rir2iBTXri5WP3RRmwEz3sKwYwcFRkULayHjMBh4yu4fYkPr4lV6nVXQ4YEIt6D0gLrWQS6M1NxK7wtE9Vyiihm_F1VOqs0CfwC0w
MXOjMFUCJHvsDHk5C2ouZTLrJYM63dRviGqyGx2OHYnYkQk77KLH5xC4OxaTkzNrqxd11WQzvSBg2MpJD62n32tgOpUyZhXgB1RZOr56fxye32EfxEZOsx74
9GKGN62nmvwUwlkniWqBD9jUOV4j3EcDM6m4onzCu5rW4LfSrxknv_nip-tPyi2IVV6epinwDnQlOjUdQOV5NbxQSHEz7OkBjHJAo0vMZ-z2M5drVgpYy4HR
CLzZHSglR_EqxA3UdDczOjS99ViFbcOoX9kn209c5FENeFfS_io0LJQFiGssx1eJOC529rYiF7QDER0s26InH-csD5WbO2UJMGmbm5hOTesTIRDWPJOhFh1u
nf81QuCm2x1cQKs1XGoR0tnhGKDaYq7P7G0xdw9Pi4W1PW4MOSs3BHlPkMhFYaLOSs1ngDtfHn1sXBKNIr5OF09WRCJNh-iXcWsBXrQ8BjRMV5WPwpCZl8IL
4ej7bu9MM4WpOb6oy_FuE1sYQR6CTKjf67T3pONT_ZxKuYoO48idXvZ4s1DTbH-xub2R7YjuA9mVUo05-R6pRTRuEQAmx6m4esQFmc8Zc1yhApQ2wR4AQcPi
n-J4Vh0Vx0VxmNwm7-m7-y5-i1_i1ojhQgnzAoQdn-9DxWOhaW-B_vbfiIgK3olrlKhEkqvJOF7kDc1XXJO7bfTA1TPmis1b6mS72-xxiN9Ca5wq0RJlnAAk
FAmAW_ikBEhAnqenWlikhEmZa7uRMExjs1DXjLXVUp-MK5SErk7UXvKDF0VhS6_1Oct5-6tWStriV5tvFKijMc3ZrzOcB6GUryV6rvNV1etSUAoWhbgmxLnW
xmchnRPhWMMMyBMr7IlIoWKsFgpjrKLjt9A262nDyFIs0LrzgYh2m7RMLGUsvU8A4m7RUHHenxx6hURWjJM-3IfLWEslgzusWElgK-bj0tRggcyZOpzbL5T7
NVLX6J2VMveBsC2rDRuD7bHWEuu27LWdhqQBDWWy2iHlPD1Sm7Q4jIEpxLmMVGLxchgwfGq4RT2njdPXfMYQDZ8Ym4QlhVt76doADWXUM_sPZXUx2pTOxDhg
ptpUq0POMtl7lBu4Ygz56mJNbJ_Z_lyNbz46mMjhV7G5nvg6jJLwbl-AhdnHWUrQM_kZwsi5nvhWkegFBjgWewxkZ2wn0jknjdRCGeqxHiQnfcDjxPsj9Rfe
0_ybBCoxeWihItnOurVW-fn9EjRMoEZwAp3wjdjjxP_HYQx_a2DWROslCRI1LrS9eejZJVZQ6hzvH1lqhAtnqGKLN9minQchHD755Gwlg_ZD8x1ENIM9BXvo
n1y5ubTWj85JLqcYArgniWxvPY5h5M91M9FDHWOxhNOZc2wwmEQLOWNEZqLqSN-DcQ5OWSNk1397LynE87TqtrAkVm
}

sprite $image338 [87x124/16z] {
xTG9Zkqe38NX0ncnVRB_vRPYbQKRwwKeqVJShb7J9zy_18nEFOwAsLEs9jAsCbTTcxJMchHr8hgS8ir7v5mceNKNHmEUatXhqXup8_5w9dH6udf8KYSaBdj6
K-8vKISaZaFrFRnEYZgUsAEsXCv8l6QqbtWiQZ_nMDH-YQLx_RM14PiHDQDgd1SrHerav_eR-FoyPt9K9T_PzHoE-ixMO_pplx9b7qVVsV6edsFJ3bLYfqRD
h4Tj4z3ChbEY1ZivQh0JesPscn4ri-icEYrgiFVd5rMP53NOqpTrUCxd3rObmOEVFxFge4YuNTI-0uDrLtwyi7HGQyfWSudng7k119lWyQXd0HBRJwpMKJT_
PJyZz1DB3-KAb4FDMxZNBU5eVzT5B_zNcqeVxaUbiG6BqKXrLYN1ER57xH_LwW-BkgxE9ZSbxfxK-7C26_s01UlmIubkL6kd5rg0Taa542pj5UwVr0gKHWfG
x3hnmPhAhpSMxQYsufxgO2NFPGtM0JUpgsQTXxK0FktQW8LK7dYqTJWjJ7RO5JXi0t1Sgs_BwvDrjqakOT-onlFsg03scuMHr_vW7PO4PpQxrHUq0cnt16oq
urwTz9uPxhFnMksqMyT-RmdKukg3pOdVMJ5dLw0vUxSGmASs9ZObVcDrhT40ukpDStLrDrfcSs9craZw0NKUpdfR9MrVblt-oypc4gQQjZNX7cp3pTdDB-cA
-60Jx7-CJrRgVZrO-JfcpWMQsUpcjZkWmNeDVsGBYZ4cinb-ilOLS-Kpmdvn1qx-bCq7p8my7DW_7ncE5TWuoafTwP_sWxKAdvM3hAu0HFsbSjOYxjs1mom0
R2SW7-nTfTPDECf-NVe52uEzR3k-YjieotWppzivRlOiEAu0nrahdl6BBTKlgj_D6Zs3jptWHOw4Zh2nxXBifkGCji7duCskGje4rhYXR83V2RK5EkEHhLOy
WzgLZ16MySJEQx-Z6ccJMByEb5OMeSyaLe2LHYKdilx2DlfCtRQYs6pMs92YTaVwB7cS9EUpnlcipz-8_P_zdpMgJcUDbsuXp6DfHq488bDO8ri548I83B4P
bHLmDY98as4sKDk1nAQDHxOz2Xwix-hk8EjH5o2nJehh8woHkWQP8jok_nxOrgDcDZHf0IUsj-fPFyWS8IKEjelAHzGSmSbdOZhRZRe1RwocNVrVSxh_fdx3
vbtZ_vz6xKU8qA8UeH-r4o5sZN_DL3jHEwn3iMleqbIxKJiHqgx-sqo_k_w-O-qHuR4sSuHy_RtFShgRTyqHylNNdrKSphk-HuYelTdLVdbqZQhlrrz_oX6m
1Ec_nTbq_QKPIAocdQWZYVCDTgQeOudL8wGtTM1gIjpKzErD7KkS8jXUnj6Ss3n2klu6fqHYySOlKSSI-_Yg7dNIBCrSfPpvJPsGsAusqup4j0tJfvwjOdH-
0m
}

