sprite $image299 [264x187/16z] {
v9T7TWD124J9TD__mius4v6y4irVJXuUL1NmQj0O3Er1d-yuGMzaVcC8VU4P46WA-TpGKoRGvW77liAmnQ0LFEOLqiehRnW4FT2PuDX367AqYLVcS0-lp77g
F18HmnvUcIEzl3AoUDIs-K-S-Wd3ub6RndmCVqT5X8a8G_MaZrSg7F4W4okFn4YS8PvtN7UlZ3KYE99tJFqGRRYT6IPvHotUlKgQi0TMQ_BBF-Mps-eBG_wx
bZ_0SHsljBEAnLyq2dQnHnO9qOwdbmyELGbsKNeZrwVt1OnzDE2Jwb6R4s58CvS7kpZ7iBvNvj8gGE_eDc-Rl4CSAbeqH3izgofCxy062XDMsIiZBFVnSoGl
SAmNelLqVWRV_QYd2cprlTAkpuGEGY9YtgsW4QdjbP9qocLSI1vUHXZY_BWa5voKAMcsIbw9_hSpwTNw9Bj_HBx955hHAtNJ16_Cd0boypeCWosP5hta_jTz
gwOD__XJR8ogXhE-9PC8CW4GJ9gSq2hF-DXcpSVEFhibPlAQvRa7u2JPdl-NkKr2dZyuSAB-yNG6vDpKeHJbWXlmyxKo5MBuKk-qeKEdDBcwUx4LSF-Cm0dx
nnCIRM4tuPLTYvbPzDiEVVZ1MiaNnpInliiU19eO5JYnLXgQ7skQhbfd8SvlqaHoMIiNkhXKtbhjxUn2Vb53JJ3H9M9Os8yLXjtTrp_Un1IhFJvmoklhKv9N
f8dx_584gptUH9TJVaEQQ5lj-2OfoiNOYJmfMkcWkH1Uj_o7vs_0cd6kVQ9M5ZplSYf5D96N-Qc1FCW5NClmm0crqhpj6OpXjcPlbdUnjgVF2PpiY_p0CzIB
8wlDlTaQGHrkPtpW5FgXwHcuRUf_8iDGpAgCkhlRr_TeWgBDdwMLoUcysIzPRLOiRzEOvzyDdE9Li6Tejmty9tiZaGK-uRZ0YJdktMZ1RSDMdQ1rGKDx1qwr
yYtFKBXjMazTfGahxk6n00ORjvofMeddvT5Y5IPokl843-x0mAdkQINFe4_avGAfbpHSAqNFi73R1EIvqqeprhQHovbyWVpWKDf47hv9asa4rMaYhufMtY2_
HRRQ_7c3N40p3rZEt2A_YfesaSD5HBcG9d9TAos4Xu9d42Po6F1ppcRBrYpxoUMCGduz9t9i1NqYpv9M2kGdgIiRE2YL9fJ0gII1_DIsOKD_e-m7jNBU1FBh
Cf4pjtFrNiviiqn-_IVoTRjO-z4_SD8zWpwHiwczLCVZqNKvumbFnJGnQ2BdsX__LBV0IJYLqZRwHCue00x2SWOqH2S_eMrMCeXhanWUW8COE9Ma3KozscQM
AAAY473GjF8R7y4pT9l8iokIiJ--gqFWL8yXU8PE4tag2ZVKbgZLGIkNJkIdjer9bl9uX0AHqRHI9p-zRUOLHunsIyIw25-waOHa7-WPX96peX0BNdZDI8kd
Mhkc-3ptjeaX5hpmnc0bU0OrnU-gbR7WXJS6RPdyzBPfQ-LyJIjZyGjFlgrgSBt3F4EERypjoYq1rNwXXs-hjZouZVKC9irLnmCB0YTSIyBr2fv1J_51ApLY
gBLlhJez0T544SXFIV6jFe62Ld8Tn_ukhOgDCJSCh0s88siLKIiPXsDd9DPNFJ0QQFXKUehFwnkr9HW7G88iTU7zZKv-3NNjhvMC0pH7VCzwSc_jytfwXZbS
Wg2LW0BXG4Z4GoL_sHRUe8aUAJwRDe4O00Te3izF7ydhKTrB_HLCWklzaJXoNhkOQCQ1aPZ3My5gMB3QGegVrC19mE7FvZ0Wfr097bFm3AgwYbgfuX0V2S_F
R-L-TZGxEN3kFP6hWTDD71Y9aYpWOcPMV0vSrdSYBubG5G8d4GTM3Wug7MrD9yzGrC19nu6HuA0oWDDx8jUrKiC1cuDTLIu11xentJCCq4h00P00LrNgMUiV
oxISUa_aIJNHNN3Wvl1CvCYrRB9dMCJbJ0SS40bUMiLA_IPoCN3g1WExYHHusjBPqJfDvFEcBMVKykcuWSGI39pdFDk_5Gu6h7RFCnGjS59hInFWGCrHteJv
3WSksmtFOE9oHgnzdYR2WPMZlTnPm_9BciZpgWLEOXtrinw7Y4JSl4StmMBNzWowLkh4KEkuL7lRO9VNFuwupif4leZB6R6UYFYuM3iRRFkwmFdffvF0YkmP
nckbJHFZmCq11Xks3SBoIpFHQfLfke43J-JXWSrJJcVdfXqrI8eGEEbQAU10SPMHTDJobPTVy2y7QcN4GKPYjTWf_rRnS1Rm0H6tyLeP60fmK3MKVpbfZOdy
rxIIST2Hm9L6tYuilmn49FsGYSuJuY0s1m_cPXVdnZABWPDOEyK5XrHxUmFuyij9zvdkUxnMCWuzccC9pLzLDIozG1B7QUMQfZuuC1AUeXXCrygam4dNIgvo
G0bk8lnoylJDNYzak5RomzdfaPYZqENQ6J7aXmOT43YzBzlx8E4UEiLVA33N1uShZz1AhgL7Sv24yC_9Vij4SwNr9v0eASROIo3LSO7JdSfRX-Q0vDAgZBOC
m_HtTMUX6p4Kn4254_N_lxTylCSxsZSMLTmZZ-qG5AA3zvotYJXLhJkC1kVcbh4IPcYSgcwuDJqunG8O6k_xPvUXno--OqFqyivzaP9iOksFN-1Xb3WT9qRs
uCnRchBIHBTl2VixoMxZUPeOAbd9sqIiEKwEF2khRI9U9m9N049qYiOacuXFnkptQG8wE9EewOD94_qIF2WE69pIr2q9FuvmdLZ__eO6fmHHZNm-MsVtk006
fmI1ZRm_RX3BE2xVQf2LF4FdBcWGmE0426daRR6oif5JWnCWk94hZ86FslKXkZvg2rY9DdBRJu9lvFpWnAi3R09WfSGc-C59m527CV2DNC9Alf431sSGyOqS
69oyDi6pqX2r2mQdDXkvWvLy8sTPwOdQmE2aj0aWH2iPMZ0uDTd8WOCpIfjmi99lvC3WfBG9W9NAgCsoqjF8ILQQ6Zd0IcNK1en1QHF0uAICsiZW96pam4z2
6RM1mKaPjG5MAcq269oKKTjX3Fpfg00hbJO168CnQWC7PvGs0R1I6RM1mKdPo871IHcr0LOg6pamE2bj0c2bCce3WvEIeO0nA1iv4AALKHjWfL3Tt628_W8
}

sprite $image299 [132x94/16z] {
nPWBTkEi4eIRDrrazh_TUt4VMuKPQmW_9wbv4jkYeUfhOSaX9KtokmeLYXhaz-GoeAgAukMNb1HgWcRtMpPSWaRvQVa27VJZiN1PePFmauP4ge05JJyP11Qw
deR4d-6H9jUkd68CmNidPOFJVHuDI8l5bOAwmUc-3RPWmoFbR4Yu3KvtUMJZGmMgxmM8X0rEjtc49dVP4tjzDOd4wmqKYwCyiWrpVK74ubfhAPdBF1y4tcZt
TAb2QrNjRDWB78lpF6gy2jF8suGYufoznFjrdaT72QtNB2ufj3vVZg3sVTO6dXB8hfT7HPbBmLiog7qVvj4KdplWCfdZBPvEf41XelWSvT4N8BqchZnB13I4
g9sDd5ACYNRl78yk0vdYA95UzBrg85DH_wLz-x_pc6p6nAjFGEAiQdOXs0yoYAQTy-eShF3QULTGR1eRA8S5hmeBQ1M7U8HwsgWaN9n_VVeneU-EL7BJxVB8
bmPo79F00-BKwEqzo_YWxTpWaRROzdDCGgOINUPP2hIcN4jATi1nUPrJzz666cLEWY_8FAY1QeR2NqKHNhiyeiZVaw0ygFmXLSsvH1loijRROXWwGD1FIKYg
nEdOlkqgJiIJlSjjaNcqZwN1_75GQC0XYW_paaYOLtVF8w-5qBz9GXq7F4jInBu0rSdbPHu7yySaw30OsxUZ_bNh_7N8hVBuM57yd0Hm4jYTDDxMeEz2ZOiy
QfJL9CnMZSUiIMsDn-AMaY2VsdS9rohVXA-l9HwBVap2xCuyy1oi32MXVVKQ5dYSBX-c9DnObPIlDzhmrJNpg1I4RAcOpET1uIJCLeNHrj46qy2ZgRokQ9km
q0O-MLLh6OyzKmLT50GJG1EdaVpL90GoFr9rOn1UUglE3g4vqBQptvo4wTuzSHh7DZi6WHGhbEHa_lw6ij06PgiydQXSdcmWDIZB-sYVyvKQoq8IPglcriGs
iD0mfY7P304S9cZyNXBYmEDamwZsVxtV9bFl2AXQqtGmcjh0d8Jv13FpEDVmsefg5q3edtN22dKr2Scly3ZMm5L4QoF5lpAPsDIF7Pi62KiypZKy3K5Ls3_F
I0wxYidy2TfGzOR7-nh6MDZkHdkGmhtozjuzli5DDYpKS15YmNeqRTSblEtvKn8qvMKUMNyQYMBHhu_YhbWmfnywTW6IBDh05IGgW69HhA_LUiKYKoocZZtn
k6h3dw_YXAQdhG3ewMAVGm7g_U-SUd5vdKSkGRq8rp378ZmcB7rXEQKOv4FxrZornQKW88eCDSo4HDlLx8SxsSnf09PvP1koo5J370lRLKqnFNCnFNxRuD4g
g4vkQ-1Oy3SHT_tNKkWaCO_Vi278Iy1T5Np0JAbRNqjDt2iLoUtmAAJMRgfGaxT5HvdayYwFhA2jeTrNKVnZYJKwv-tJCGjfjIqoZwCYMhit1AeOlu7cPYnk
ypXlwAqXxqze-r-brff5zdcSvUkz8QQ7Yx6gaBx7uv_gvBEYtXjYDJmVwZWlprXiyFXP2Vyo15gUAqwli-G6ZpTovP-SWWyuFHQwmUEzmbeih5tqMAZkySZQ
u5GrFsCHqx8DKRwZVtCAjOu8O9_7U_d5MEYtxe_hMc_VUeh7VKvFyCZQQTzdUTnitoTvt6_V6_V77UNxME0GZ_lj6-tk_hXXmmQdQATut6_VQ1iy7kOKROF7
mvoYRV1uE1Pe-_V7K-qRROF7mvoYRV1uE1Pe6pmUvXHjWySJSbVxHjlWyQ0Xe1esU3p6ATe6ZuSvHTlWyNJxRXiy7e_51e_7EJrcm_y
}

