sprite $image362 [207x244/16z] {
tDQ5SSLW40FXWO1FUhRxhpQS3JDANmSx_ydZ_OVDXRq0CJL16kG7BOFye8qCA7iqGFPe06MF1d3sdG5RIGnAOg2I6cJ5v0TfFgeb1jbt1Ym1CTaFvFaIbJmD
N1A3aXWeuECS5RGD2e861JtpGx970wZaQU2I61oLnA2a1eh-100wAeb1IGpqityqDK63Wg11GSysA0WQ50Hf_WMrn21yD439q-0e-mi0jBmCiaS3w0jtbX-q
pF_NyZGeYO5AOd2K-746e9OObDJ0pzPOaue6BAFW7ZtpGPChWbYDP3K4MTCKP2Auk4otEKI41ostEUwvEBifY9oE2Saec90EHkx54REkVYZtukJrWX4z8Vcm
aeF02N5dv21qGiIGapaXxWn6w8I88GTf4-BE81bn4o86bkJCYvEfWQt889u6R4UJTt7drTg7SfixiWJWUpUw0uJtVzeDyfHFcDMl_bda5D4dH-ihpdG1a0lJ
ENT0xtIYkU0Kw9I9azSrvwGLOiCqJZnnPNjBJ75o46Krq7Gv9vpAvSHHNYxRkorDHRb7Ngiu0MXyphwyxp3WY7o3SWuu3TGu5SulpNrEB-tEcGUnC2cdWm9E
01h0XFSTNdBAJ4uiJHmo0tKEENDCa5UUwyCQsJZ3pmbCCFbzXuqJtxxdCNNVYIQkE8Dt8IhNvFSTid56JjeD4oGxhB5nWeaRchFE2IQkEFR50nOvNixvVQU3
lCJWEM5qQJed1v7om6ML0UPvzvq8D8zv_BuJJDpud3r-ttdXTnq2p0lkEy74JS_Pu_UTyBiEyvZ7xpl92WqipRFkEz4A3Nmq0QT2Ck04ApI6wPpyliDiXS8J
pIivVU8w9_ysIb3E0vpaliDeXMRch3Wfg7Foxpe4c05ESDzXD75YKCu3dE2-y_WA5UO5d0XaY-h99wxFsJodGbxSTyYyj7ivptFAqtOddBWIa6rfPZdvVITS
eJPdxyd9LwWmRyx9LsYj0pZXn54-W9E2v7K09rqXhtK09_LulHCdl-_m64wu9Zo4awu9UG8dl--0nt3IYJk2auF8GpZv2ft64Qz1Xt3o5Jg4auEEuUGhLF-3
0pZXzxwzB1t02IVEuj7tdJvozW6SjBHzmEva7z11LT11nt5oqFaSaUJPd0uwYPDFtFcS2idpEFaAvHpFS_A9ky-XFCx9GVSveASvpaVkFWSQvzpntETOyYId
L_4pxZjMSGY0dkGGAIY_xmZqBmxWsMV349JVTmoeE201ZrO10GQW_BvZ5aU0JD3sL1Na4vTN0K7p5mMGA0zL0TE9opac043B12LI03rM1I4eBsf_SaYx-Xee
q5WL421JJlJvrEf0I_YCdinP5rKGh53EMHQr2DW4B80ipoivpYOkv_J6Da01j0Zw5PnU1GmdhZXfz9C20lGIe1TpVdD4e5MStFCP0g0DyAMSxYXXmCaY5gS-
8qzK0PYiKETadG0AbHTpN5z_i4AD4yTB04q07A-2tq2FSootIbWMwO4g25SevwYDbSbL6Qs2BhpFCT7F01xWk8CkIZlc83ZJp5L1Bxlx79c1PxGAEYZdU9cW
PpdrPSShb7FMgZEDxH5ExxRBJ-fc5Vpy0nS1ocExqxxi2s5SrApd3b71MM2c2dhPnHm3AXZACy8Hwil-lWgOS-g1Mlh9aSepLGNX2kKS4sIzvx1AmHxW11qT
Lq4_6920wjCIwFagQCAy2hg7TG5LZPpy9bN0LWN9FSSc-DaDTUVHN1Kmhu8ihix-8yVJLO2W2j8OzUY1JmxN8drM5VJ771QdtZ_abrL1Vinfd2m4KAr0mALw
SHNWyIf8xgRLR8I-u-pzp2hWtIe8Ivik3h_bxFs2AkXb5tFwPTgk9G89VilP7xSuZzzuSWxbtWa6a73sVhSgQ7THipWAE0sKSHHszFqgw4y55XS1-egZ_Ljk
SnHyC1TL47Cg_fPJaCh7BSwzZbRCaJkdOa9VStRB4whWIs7C0LsS5il52J0D55T1ydwOSw1FZcL_SOnBC9M1AiX_reTMYzautXTvHXLqOUCaFqtYVm-M7Nuq
bRmAyXjFpZ4-esMPeBqkiuFShmB6LP2UEadPWEXBJPRdLW5u--b3TQGXmVL5lECmgGBcnvoOKp-A0R8uNhxuPCBSgGBShuAa4kgPmAQ2ZoO5vLN0j0gYaMCT
fENUSVk1V4HL4ArGuwIlRMQzxDeNc32ygeBaWRfNGHnR11THEmJw0XFcJXKWgu8y8gkuBG1KW0b1xQqa-c3kLu7xgHEWboM2WIQRkFvMadTqlZicARSTaabP
0FOJKbzDuMxVUEv-8vxDOmCW0auA-gtf7tZyY3b2zopHHkLZFp_VFUm-NWK6AABV0b3XApbPH-TLK9FL3sfxW9ElaEvS46W1hd-v6cZ_hJZxrPpWc9Dpl0HG
ed_hk2hd0KvQsZ67j038TSRH9wOoC6pP2l56iqa4P5H-xD_o0M24S_t1tAe2_dh39TjuSGznqYf8NgO4_9IWVhzVcuy4b5H13m4InTd5gP5xNQnAl4B5IJoL
ulH6cvgui0gk8-8tGy2PNw6SKttGiYlJeAWAWhV0MKw5wWcg87aAp3dpAvHpzgy4d35GNWKTK_cHSEOdBg-2FztDFkgO4t36GCohOBVy23ZpAnHm2jF2QDhc
LwWuAQON0eSzFzGJLi7b-V2NIEyoSOsJQYeC1cuIr3WDatZsVEvoTXWMPpntEDfvYZEUdBFFICRPn-JZUyu-Ajzml4_B5MUVcAyu-zGqJc5EJUDudnrLMWES
3MfRSpQeQSxsl1xpRm
}

