sprite $image66 [158x227/16z] {
pDQ5GGL140HHdEkUa_oZHHeRuBjMHV3MTpb9UczXPYaDH9n-0jiIrvPCic5vWzO5mDbQcn6t2DEd7Hguk0Is9S260_cqRs1R8Yvgxmes4czMOlfqV5nRyjd-
8bYVJXdZfAwFQqlcuXBNbdmw6t3-7dJkPi8jiZxFN5iwpTE0EHw3bP0-9IRFkafWM-BY4jUM3BQbTJWn6e0Jrvl_ssoGx__4kK0yTrtPSXN9zznq5PeBkBpH
ZOLTtkYoi6RvkgwCytLT1SRQVZ-wvXEdfkDjFt_fnh5jFvjXcw8B3xRzNECKNN3lWRQVtsnJcxjKZDl5DINR3TTzBlkAYvgghCOZB6ziAIixZU4nV7vbtqwK
smPoBO1YHpT0L_x_RnybWZ95IQuiL5DlPhAWNFiftgjct4RAjjELxzJwLU7skWBjVNMw32xSNaTQdbFhLw4-wgGLvx5-5UzusqsdOBEZGEFhLuLxfHFmIAnu
nzUl7jnh7KWGzzAzyespxNLW32spbMTW_IhKdtLAu16WnSbfmCkjJf7Vqm7t9Tv1fr-5-hiwC8AUwJz_F4RP7dK86XrbrUNpqsL0g2zqW8qerdyjJ--htyxs
cpemmeZGVD_fLw7-XQxYRHNlQz-RJf577Uzr08reWHrUlohSx-leKUT8Cq8gtkFgLw7-ewu1S7UMhqFZBTiHEe1EE5MyZxwAz-Z2_Rwk0KSwHUboe_kxYuCg
t5_g_5xd0DGsyKx_SBfKgCVg01lIb37BVl0TRdkjSoGftJ8aKYlUE-1ldovrYXoaGxlJ0RfLlA_gDy-37znh7UczRkOXNnm_VcCUXzfUw_11Po0z-HRlZhVw
NfyYX-bgx7K0PYpJiqkhr_MhmetGaO5cjbxnvifx7M-5-ZQTyPsEB_7s8XLkxzlR3jVXJKVtEW1JqbkyErvMlBl27QmZurLdijEnWMLQnRlxLQTB-HuATzXf
JAL3skiKg6LzP_xKDsNCiq9zXquNKusTRedNPjtqJ3XzPU-H5UfHEjleel6FEb5eaUB5s-jYnat7wdohIxlNaGDlTGpeGTAVwgRBtwDr-3sawm93lEaQtka0
LD7hNcse3W2vT2POEeMzJh15a7yDrwq3wQPhI3gFZMuUsebZ6gQ3-y7EcsUde5iTrRrQnNk2BfkKpklPxNI4BJhQrpcwiDBDGq6GPQS3a4uKqmawOB_JzMSw
S8B8xDCqMWV0LvWjEeBIeMzq3T6ZeNxLtSP07MvriEh0xdG0tElY9VDy7RQTRXuO4LwtVZb0rrxgG6OTTjpe02sSvdXdP9oggq-5GEdMr_4IRyGq3TNfKrt7
hQukNk8TlRC_qk5LXx3JpKF7wkoPJWLd7JpH0SR1EdpKjPzrnFfA1wVhH1cLk7J-QReMQZGR5nrycYwRC-DONRlN-UlUDNSsem_JoNhUiNDB7wzhlwK3Oy_c
7wiZ43DyfliwLQUb0_ne7VoUxdywVgVkVxesG4U2dwmBP_zO7MR8X-bye_C7dPsiQ_2jK-6VTNIcxjOx_3oTV_TEb9udYm-wDae7sakdQVAjas-T2UfmdTT0
NdLTd-eYr4xJhOFCrUzrVDNrT6C-MISpuQbEt8oRqKxdGtMQfazrhcmSgIVhkbrrwhxHLUyyxQfh9-b0J1UT9ZtqJbJFr3K0v4K732nCgsvM6pUNatM0Yquk
EW_SzUvRvsVgPXWBzLKNMRqRhqDyrA7ZjdVjsZlHKJhVw5nmVxiuYrcyhJfHDUuk8tImqsMNjjDvdtMILBfcOXnfP-WYjUzqCum524ftWP75AJensUi0WKNr
hdTQlVEnkYRqe8DPPuct7rMeSsyoLDTllLjqJ7Swj9iEmAjtmtLhxroRSFMExjwpCyf9umHT0rGfNJPTTAtfLQUBpdZM0OgFrTN0HSVHIzVJMUYcYwwrmF92
ztMS3XzqK3eHgMIxixZIgajtegSwF5hN-8LEkowzCnLXwQbsqHbBCsTNVARBWtKHZZjTs_MkpqxnzDAPY7E4lbVtAsBAzFuLiT4XbOxxfdSYObgw2unRsdjr
opOVyMpiSjDHAnq0V_TEn4rADsETHFNDoLvvoZPbPAFIRNUrQT6PY4XFAzqCTMuchtHvYAxMDQLbQf-jkEZyMuUtticcTovSlNkpRgfTORp46rhn-bwNJOHr
spjww1s-GLVBf48-wpAaFTD9U-WTY-e0NUqAQuzad-FT_EnBwAhZLxqReIjVHD0rNiFR7fIKhiVii-_UAJj7wY1TnQjuNQSBhNYLIzUoYSZQExhspjD6wIfU
Zmoy591hLxjqv2xIN4gtz4xqMzVUh2lV6c_RB4Ap0j2cTuYgpjrbg6wDjsVEGB_JWV2jTxC9ZI9jgAvyBVAwBHa2GAN3MGSaDnqOMGpNLRoT-FebS-awoiD_
ToHzfeitwieNYf7HfgcNJk1H1x3JsG1TrIzosPRKxsUdJtLjiAvydIYdZ12HfNUE7w6h-XbdTf-cg2rZXm_HbI_Iw1AluKMdUBhkCTxfyhKg0y1BdG_NrSjD
CvjMlAjEpjJjuzLBlE5qqpcUhrjzqPPuqwnq1X-Xg_gvppIPfjHl7VgfkdsyebD6vzkdGl4JTELhnDSzSVSbL6oBpa_MLRojPGhdb8ON7J1yYAvyjtYbO6_L
_Vgrwdu_NicC_sl6Fh0T1s4e38zB7D0LkVjVxRn6UXK8x7y5tpbqe27sq960pHU1QOGYZDyBeh4kyqp3A_EqA4IM8VnhhYC1w_0kG12LHxyQZlztBFG9CERX
xQ0ZB5qExtxee2F5EFtY5815aiGEkgBXbN628avDTBpfOFRbVxKmNklWQYiVtZb2vfWGX_oUpJf_M-7kbuTtzjCfdrSml060njb9nvoJRoUGCIJ4qK77Yxo6
Dx_CTqEjZXSv3kyG0QWiLJhct7rx80pxX0eT3S5I7ju9MgnJch9FltaGbEfepturBTGnrzWdG59qiTaFNr4HmAPJrWH3AZ6AJSVQ33g8JKUFFjS1cc2mzUIf
QStIBtSTVNFLqJrnqobR93uwjif1nvPLwjYw2fsoVSKwzgb8ntwPTGVsJ6mwzkwXJbFIjMsv3tLSAVb4n_NITpgksqiTr--fJhc97kkubIvrCDXwTQFZreAU
HbQvlGx8EcwpNnrT-W8
}

