sprite $image28 [244x187/16z] {
vDW5aeH054J1iO3EpyZzJxlkxjjGxmOPXVRfxvhW59NhMfmuQEf2blheQHLmMJzl5oU6W1ivHktjAauC2nHdgHl2r3vJnOaXJZn_zH5XQb-lPYqEcheXJEr7
oXEZPYOEcdf4cDelb2V6iVk3aA2fZv2bzjjLf-AWgIU4gVrXUM9CtOY3fjuXJEtVoXEZTN0GaZ0rPAaXIzrqq_5F3qAIfjPTUMBK7no494qDMMgTboT6_SgD
d3GrPAdDgZmnweSEwfEcXYor6PSdnkxBDtBIr1PHdXZrXG_DbAaXImrPQaXJLo2wAazjQ75gmt2Xjj3gHNCRBjgEELFVcZUhJSjHtvfNgvqOzQtveY7bjcvZ
kpMlrXctzJILTc6-wRny-rniMuUX0Co1GG98zFvlUmE9SWLVTY_HFTtzzyKuji18jR--MhH_XDqy0Yy_u2B1xCclM-ltOPP-dMtFgtzkkPafc5-_rjA9XZa4
NnRTFj3H_FgrbcqxPpldPtLvnG4NjNsNx6u6nMSqySkfrMmt4vISSpMJ-cGcufT2YzamOycUqipwjTYLwQLsQr5xc0dXK8EOSKuZG2DTNcQi7sP7rxm7rSvQ
Pm0Sw5UejPX5CzKwr8KVjNRp6PRbnS7Szbqorp7WjPir7_3ooTpMhhMeNNFP9JDSQat-7tH6j2rSQxMOi5ULizQaff0IdL4pOM9PUApdPi-rrYdnnMoj-u2l
BlOyxvAvrZngdUbX5ZUhhbThjRcvnLsov2FdMrZptxffKpFbfMgjDit_TybIJlE1Lc4Yukvcs_ygguxro6INF2fT40-pcNNoo32lCU2YzdcpTexcL02HiAIA
FDw_fEzKLLxbSZIAOnwxv3Mvb98yq8Z4pQP7hPb6kCjYOntDH3NdD0ysQghY0yuKmhAaEEwIStHcfYvc9jg7ziGtMQh8qGmrNzKLWhesPl7vFWOS4UbCbvMA
_BnBbazg88fehpMBc9bA8mGW8kPGwpN6EkvL5ORQXKYKdaADcfYfcX004cAezJ9Z7VUg0dMeAs19pobUQrKrKt8puAFRJPOPwxXZNBUgd6RnMlTnBNOCkAUF
BNCLSJGxwnpmUR0Hws5-37SVMwOiKEJvNfNXY-gyrvfvLp_CfesfoG95dkrLrm6VgujxBsJQHwhhsAtlFTQVtwk6-NFgEjw-UCYRcNQpKUkRZ_KmlqztIK-P
emi04T8ZtDsyhzOi2uZTB4_cF7P989YZ0P0HelfSCvlSjiXnbxoQFHK0a201NxyKrvEK0W1qILFJe-ZGv9P5ZkPDfKLpAb3hRaGQrFBqPSdHx5rc9rD9jSiT
npgQjmhX7QlcYutm82BXqugDpQtCtDnAJ81ZO51kETRHdFUSogWhNBt3atPJP-hSMsiyBirmJ4CckTzOHpF0HLtXQOptMcSewJb4t1ltxkeTFSoUqkHcOntD
ZePoeWiWHjkezSHCrFUqGus76VEuy-YUOZTx4A2UwZBnPSQvcLM6kfF7pQAOF2YtAd8qU-0ouBDKhbEpKEjxBcQpNiSTixSgSZHxSAQEjPwQwL0p4VDfjXPg
VPknZkPOwtc8vcP2bjO8n-kCSfYFWwOkjnZhkJdMUfhCC3L3AgqXu31JLpS3v74Z_2t6EfhZIvs_KkkPsONj_7mMOOJZ9OPHw_k8Xpa6oucU1pbFp9vwciru
DvlfutFh1aKEvXZ88tMEpeHpSyhKXjduC5ilfOnQtw38dpMFi-wAbp6kLCFbA4pCdjem9T9X9Z4f5N7K-WPZ7SmH3OX89CfvK90enrgNgTbhNLDkmupSIrMJ
6chznyTwRexnNXBkMoOzcffJ25AUcbCcBgdw-ADrH3TRgsdK-WRYG9v5ExW384_EGATc7trA7ZHJBbNC37xuHdZHFqlsYBQIvk7UfcQlzV5PPNkVMGr-z4Ru
FoqUKU4yDIErtYTc3tgjKTtS2LiDpxVSTQoZ6kTcecYEjSwfCdcVEvxcKEkxZNMCQAzpCwkmcoSfZJvyRZQjAGJbdcCTezhAtCojSpJ7MbSoivfYCilTnHuL
oZCp4NTEdmcsaZARk3ccTBbTaUUrdfg9cE5o27m5PlPQuwGPq4J-L97V8kG7QntD-3XGG6ujdfONddyR28YQt7UiOwsdvfHe7_tZxBTXJcVYabPw-MJkgdBV
iOwrdffJPdJXEFk5QCwdsOppQLOpKxcvUAY7Xw9v72ZqFjGFSb2ZcZpCEjHt7UjOwudP0rmozpqya52kwj8AwMcMKtrtiKULyzISCb6kunoqFjx8QndmVRRB
mmn2ucgLsuvrhFNrt3EyJsC2D-EZmrxyceyyPXjRLspOsnXmlJVPywxI9cPFRJMNKjCrkSAfvdssgqXNLUp4tTNt5tj4XITc3uxvZUgpsMMS5BbP6XDmjxSL
n1xLtgPch_LarO9JdL8NwLtq8urHrSqBY8TQEPZ3EM58l16BTtFlkxgvUHMorxhpn3pxhbvyVgjB8r5jvWFkixsAsAFIXdb-_3yVy894RXOpLxjv6R57XDCy
cMasu50gOUVJR6vUYknvEb20yfLQ8-Q4lG-pvsqjiKV2WG8mvFYqLfhjaXpCouZd1mfeGdMsLqKp1VDoOe_q-Z2RjHB80JqphqZswBa-D3CvpMMYdfWN5CS3
XIfk7ZQOgjtScWJpWcAFTdHGHYpNfo-X3dGmTsKEvXN57crrbxfvfDJ9dLZOUjVUWtbDiaSuf-bQTLLN4JTBC2yg7hME5rxvUQrABBq7yzfYZtIuc1lLv-TR
HEHdpNeVRgorftJhMC9QbTlL_FO3vhVjXdaNpW-p6SLQrowDVyAytJGYU3X9tHoMoKeV2URbnR7McKmfd9OWKelcbSTwlcNMU1zyBIb1RpzctcuV4SZPcUaf
bO9vRN7CVAjoyu_CjcmhfEIHNs7UrWZcW0xcreDvVV48GfsgtTo5Mp0lBnw1ZzHQ_gU6_ZrxbMvBXP0-ygo6xxhUtXOCKLYWltElsbODN5R9xzghthTrawvg
_kQzQbixyEbHfZpPgrvG79_LoqWKp2ygzk0nu0M0IBvibkrLqhpMGCnVCs-l50GasdJiaczlK_FsQi7cMwOUPlS-cxTNpJ2hFPlVjXSsI-_cmntDsoj7fNKp
jM3UNZogOgPwCM__GDJqQjx-ZLpCsx-JOTx-gQZQsv_yVFeF
}

