sprite $image77 [220x160/16z] {
t9c9SgGm34J3OUEMJFB_VxkvpNHHZaZNPXXUtRkvtaXg2kdbxp2yyd952bwvfXqQTacp2vREmDYrYiPSoeovH3jUr0vzx59cp78fC-RvySpC4CFimSoUSOXB
jIDJBcN6NAeT6NkKeYrH2Xh-6Etu56LubD8L26wdjfiDWjkfxG08RcUs0mGtvjnlCazXW7FR0ReRSqApljjapk34SewU6pCiTRq5EAqT47HhTdO3EjZfpDYD
6Si3l1yOWcxCZ9FREJeCVRaXdVhj1uYwJMclCHU4iVEOiLjQRTgncyefxGn7tEQwrZA8OtUMed5FmbxjyexSa4zMEiDXDvZNrMTnxCefpDZj5VDrnRWpTJZ0
yxrol--6zyPS1dPRph8l0WGtm5_jPkf9nq7kPjPtWtbDL3O3xczd4DpeFngEN_1yhuLgtotJ4yxllwR5KNmB6fIKCFoIFsn7fgwDYcyAFRiTlyRkThgmBVY6
KZ8R1EvY5dwjCuF4dxPZ7qwIoI5YPp439qanoBXmkT3f9ucEC6ZZ46J4Jt2I26wIdRRPtsVGamJws3a4Do59_g1qmcQ_mtGaISgIvYc1ASE6VDmE4Dpa95bo
ciRXUmdD_tipi4SRi-0_kT7RJN8kL9wdyQTjM66tBILafhl5awJaD8z3PmaTTeFD7RK3rwQS6NHP-8Nxer138AHonuq9cR4RC_jwIxL0aZH8gikuTDmYTkNe
PZ_xBTPF4ecfXDrWiQAnMtnroda-Fecai1lBXIE0cwNlrF9SPyWXDxOpHDqw6SqFta7ncARTJpBWHdRXw1w6tMPfo8KQvxJ0Q_rSGZFpqdVZJ3bqaKdxpVAH
vrAXvbpCM-ZI4fg8kC5USCYDJcawuvGMM6rErTtiOmdjINA3kSNT9clD8ZACSoxmUkjaQ9Z_z4acTF7gxXPsQnSBXR5OHwfXTQrbZBlnDw_-YbdKhJMBmB9n
CZ1ibt_ZzZ6w_ew5tCRlxxFfm4JnKP4ArO6Eab6thxRmJopcrfhbfyOSllEy73e2P5h3l7BChKMJVsDXjtwp35FAnRpMhucQ3Xq1ulsUEcRavcO1DsuMpdEl
51D7LdUwc_dQy2qMTjjUiFd1Iz5ty0YG5JUlAxdrxFA6PIUZTnwymkfESxEwtk2CzQvDXDUDaqchExqdpLV2dJ7hN0a9QrB24K1nuzndDyRkUGGeEKgXTkox
wNRw4S3NA4vcGJStmKux0fX7CHgqZXjXvpmdzdEVtIGxyGYWOsH6Rc4xFKagT3ZtusxwsFMF03gS-t4tnlvNagGDHMX7mKsoMpX9iD-jIJ0JtCXEJ1B9ZGTD
STF7Zb-u8RXnxajkUkaIkSr5SADsrDnqk-69IO8RcGbkGcFsxbB3ehfvNNKtlNIxsx1_tTk7USGm34FXj6iKRUm_RNelYc53DAMtmVy5pFMRCsVZ_sYyZTVP
DFt-UmxAniju6w-h_9wZOYF-xnCszTbLVy_1sufFj8tNaO-nbr_FZh1nS-Hjl8vu4_f0o8Gs_TdnjgTf2smiZZyxtcO-hGibH5V_KFBGGZO1A54wFrtJDYiR
P21qvEF1-V2vu-bqEbvpDYk-aQRNyU_iw-Sem1LJsFGobKvaqyzHCaovJI2JwIGs_Hprm-Hjel_x1K2CxdYzj8DaZevAghFZFsqIph7UBFhJcI-jI6KXmxIb
4OT6qVJ391B-ty-iip1PmEi3uV_zp3fJp373CFLpZDV5o3Bhh8Xa-SvEVcZnPwUVewxpUbtAEUg7gV-_ds2OyZbcqkbaCoJfXwbvlfzPfpgqV6Td0bb6dUZ_
VivXwkUeBvg6q29jYCwYR8uTYh5XfzhRi6DjRTYtkPtDiNkjR4XH2nkoDAjjZaHfRKYMpeQ4QMn8ci26j6sr8NLRR4ZVMfkZXrRPq4cy3Ht5sT1NCs53T_b2
6xfiYGtTzfyDNLUpEJhlRni6w7SR1kaN6uR9ljamL9zj6AutMy68FTiGrmC
}

