sprite $image384 [276x214/16z] {
xDg5USHG30HXXJDhKF_L7fDbXpbl_nBcszEHynSICEQPiPU5YvGeBd9kOaobKJrasnwPyb0w5YcR9GeFXMTu97FUo0AVLaUXS1FnEYuozzZgfrOFXS9H0CGR
g8MNZTJ9GpdP5zd0KKgHGnGt4QWx4OuodYVozg4yv7zKYtWejOYZg1RncUrcF9IExWb0gzy5u_hHGoaYuXP7cOYjE_dCRebpaxXw-D1GHFu3m6MJM3mhl8xw
uNyzMXCdQ-xkRDrH7OS2C0PZMqkgUl-txS6if1nq11autyvNNFKLJVsUn4BP9-EzYQBswzVV4wM19dFkAAczYC99yh_hxsgj-J-96EQ-rIvrX_A4IB_-fW2w
cwnYfkd__oDDYxmoKVGNhx_fsrwxcLZj9kvSnib6mkkl-jfvDx54aocL4ULasV3wkpxRt4qoJNRdCcAHJqr4lcDZZKtMRi9hs5QEDn9URpxIbtxip7iJkgpA
2y56yf59vfs-yzDUsPciqDnHQWrGG97tJTfFXmod4VEyOjXF16OTfTotbKSH9SFR9W_6N_hvLm7eOC9YfTnJ1CJBXfUXlVj0Nzbi9B2kCfXOeSaq5QXgl6n8
ej1tXoX_POz0os8AB8C9xYRJN5LnAgBszlDydGYtsGpJx4tkvpBkvw-_57XAvBS4rtVsaIpJL5IBD-6L8QBX965MS282YQwl997MapP3sviKMJlAAh58n_he
SRwpjMQTjiX0badqZyaYPgrF5B5msJnn5aD-t0IljzQahKnJQu3If5EOhP69KUJCPFhfW9lDHg_cxhMZh7DH0w2ZYQQRYLyspzHi-FdKV-YimMjRIZztvcOA
24tumknDZClcrEGBleI08g-Zb5kcjC2qlotVJ5PlGf5J4_pyvo7vfBLcC-4hSKtJUdivB3JPdx_d9Z_VFjdmKMlDGfFjNDPI0XEUl-ScyihrdQqrbIPCsWoB
C_4RIMmYBrxVsLgJQSBQLQrLwCx4A79cqbvkFlxzbQqrBQtzs9MvezHrEvTfuixVs8GLqekT2T_PMbDAcgO6iwMd17rR0S1p9res_GewRLynQT_PMdDxtq4t
sSfzHTxUTm8HBgc7p0RuYXOMPkqVej34rljxSOQrDAqIYt3ZTVN01IXVqLgJQI9taor5A80Ua03Ad0txlVudjraM5kMZynZpF-KdgPaUJn8rPJdmBSt7rxNM
Q90fBI8H2RbOCtvN--HGMCZh4uLXgpF9TU4z0vCXKmA-gbEG9alULDhB4vZHejNKJSPCQGrDnWhkAvkF-uEpjQRCRxRMcEdgCgLCasZPt4mg7CSFRhCqAVVM
6dSkurIaNxfiLTg32MWIYh1ccrBzheb24xRM-8wzPvgD-duoYykK5cVYNtnkJM1VWE9DZ2RyX7UEmdyPJRQNFxJZJ8ddBsndmf5mrq-RB3HvjRM69gpIrkai
Kr8HmQD9lpwgaA3jNp8fKznQ4ulGX5MQvCDCYRTJRpBDzUs9ebSs7okMlScSNcsjeGanJP8puKOotCkS2KVYpGhfGXFJiZCfRAr9fU2vrXgQfBnicAQb-4n9
0OmtUJHPIuehf7EHIqr-cSbSySSatLfhvjMrrWGYDAcmnZubKvyfKUH-sMYoYccla6egU6trw0ttmgin51jDD7KJrreJzWWOtuih-vI4cH9D31Jn4mNTf0gp
b-fUl71QHLzlCgMo3UjWOYjDc2B46mb987pVMVY-iy30JAbFacY03UWcO3zFzTlA-RAvtcJY9xpHHEucKtgcjGQP9cqpuRUURZA8kDMZ64oK9hiy1-Sru_Kc
_8IN1nFGv5Qju5X4tNinUp2MzI231oEbcuabcd0a8XG_PwytuR1QISvaRAs9ep9pMG4nnN1SQAc9U1EEn2iLqlKc75QLz6YIAjYm9uVDHjuapVsUiGTNZmcm
x4pISb8XKUJVDs5hJHAb2LzRgZVn7pjjUJH9JNlbTdgEca3BpgIfRgq-w-rSFcbGlzw4eyhM6W6K9YpHLsVYFtQQbZIOT4mqERtC16gojC5a5cM5bE_Rod4L
VRq9w_4-7H9RQqOJE1F_pc-DPThTvDcgN4GgM24D9jfDxkSovApJLd7zEw1qaucVy6GmiSMPk1u1JIpJxYPFNjhx4ZWIWubbcl1SFkyzljo45TFAjpXjeybA
awZPY7jiXYdpaoolN0k_Uc0qQJJXTnQSr8nGlTx4b2PRE5IJCmcM3KqOdqYQfjhaDHEE12jfPn9NI74xzlMPqbHCQsHYYYWhICsGYmXUD-58E1DU2mv4WkRZ
gpCbjjPu4suaKNwo00BewoOS2TcPp6BRGrKSDAXVVEwuJEcnjGOx4pv2PB8q0S-9rqqupvRHfDoQZwiSVIUwE5DQToOhiDMWArjhQ38yGc0oBrNmLZ_S-DND
060pkGrN3amuPoytCIsfx38bdNiLoNCPcIPyXCYa2F1MujutBbP8DN4aQ59P8T4aEFmkNZic2jbdIkWcRAsXIIZ2sZuBtlqqC_T_kdGJLaYeWudDD0cMpULr
B6i3Z2QMDnEsrinJEMkjaOPF6YThtxUw2KVYmMHn9kxmkxwstsTAZIPyFItrhDa8dtNqT1FGv3OIIsZYvkpb9lo4jqIPKgh7hJMVzqgqvlAJLRLbR-8Fl-jD
82lhPqCEJ4vRQove2zYPCARBKuKpCITogGbt_LkL9crlKjfodYb5A7ZN9Dqh96d0Wqby-5r88dcedwqcbocLs8IJU5xnESfWKdMhaEQSjH-uD77dx_Kca9j9
kas7fbfTfhJG92mYvocLZrSF7Z8bdPcV53C0CqtCYLngilzJ32lxb4pZJ2au3VlpjqydocEc19hqIe4c9plzXN_JX1MPBLjMC8lBb6QQHFN1p7tueucopvGM
clHAeLTrUj9f-_4ayIRofq_9q4QJJ9EWYAG90x7t9WfidobLcl1ShksaGb9yBE9DBD64hJKkKtAJP6_2HFczNea6mnnaIlt6Y4JuE1U9qCHd1QcPhCzbIZHP
k83mykhXbucyZKIKASrD8fAFCoN8gScmYCyp9PeKMEsO9UF5YSARvMqasiuaLUGfp4_64RfiaWYmDqbhthNMqCHDai6aiSyY5TUvByzrasQEH9kNqMHbXUHC
tEDSDaa4rjAZIMDhpLpOWq6JlOWpiRcRxFlIS2B2IxUH4DK6w6Ecj4GcdsTAmMDfgT37FgNAJAbr5PhiHBn9emdFvTTw9SnMzYcPxZCbeSbXWdBbdz0g_8Gt
cjZCzvq5zqo9Zt1WeZJPdyjdauGcDZDJQYvJIix4Zz0b8hnMbcaOJMetOGz6xIPyX2TDnd8VPo8qQVS-9LoQASKYiKb_0zKeF-dlxEMWOZ9dadOD98YNpMXY
D66EDIsnoSUPKZv9Y3cg9UnJ4ZiYqPr9QjgwIYuIh1xrDtDzIeQQ0nFJJpEbyzISyGbotPkaso-JO968cgvfD5b43Rt_VhvjAmYMJMZ2F6Vs9k5MVvq8JRYA
CJ-Qp68on_a9ummO0EZD98kQrMvoB_Vbl5VYZybIr-4rHw_Eb22dLoO97sA-cx2sHmfDkAJc1HrdDB6qcN1RmNatgTvCaYWhf7LLnP0f7IOebudG9BEp-tOk
ZoPMQHBMa7C_dNh0aDQRoKeJDXwVTvC-zYcLMv-IwPWfnOUVuPDbuqsoc2uF7T2ZYIMQHDybPsRx64qAJJPhwB68ga974qjy1vpbkKn9ST4aeSduspUsriJv
YV-SC0yTWjw4nqZOJSfRAO3HfD24FHWzKuf93D3F9eatOSLqBzCaHVc9NzKqwPfITYPpQpC_ZWUJXBSoqwXFgQS8BHJXHBj09CwKMAO59luFTz243rzI5ljZ
Kc6sR2Q_3hj9rzwq76LApHInIEUwrCJrAR5CAyvaV8ITIMBj2aC3T3DXCQV9cVXRvMqat3nPRg6i12ISQ2fomNyEDSwKk11gSYR-CEIv0sKzp4rwDB7YJFoj
k9zY6Ks6dpvNEOwK-YP-qKo1CrbkUwQg03gOy162Ty2rctHDxG73UZE1C_6t-hEVPfhSynCaciHBZoPeLwX0wywamZfDMcTMApJX8yIPKkecsylJWuabP-9k
TVkxGuLbsc1YnPdumu-bCYxOLQ26x3AbjLUHZ4yuazn6uamgJVZo59W4dpXP8TM98p5cIagJQABHXDS5DGhKzB5FYHNJodEP9d5LFImHcdJDLhr9t1d0hRWo
FWdwbFn4yoQ22nOGpFQ_VIkR2GlKbRrgJsTArApfZuaWN3OqiKeJLaWkFmaccZCH_BvY0OM_VUDfqA1FPqfZKR4AzC4aN87ZRzyu4ZaquKGBJAxRLdIDCgLf
mT5NEAITIS4carUUouC9HSxpa_d_eiuaFlpqnJzVyFivbPQy2TjZgXnaIbYcVQRKkidCJHeqSV-Qs8HRqkpxbBZqJarakcApDV_RjwRrk4y9061DeFQGAPLk
marQkedxrqGcypgpAPldCaqE9vgAlpv-JUQvd4GVCoM9JVZhyZd3iCkKDD64c_GaSF-Q85EQcdRIQSwCJvGcRYC9JAvUG03mO6A59e68IEfLsYvJoZIvfGXo
9E8pfRMRC3vXVX9EjDX4yFbB41j1T3JHVpPHa4GIjqG9CwKCEoBPCgK74qtTX7dETW3fyJsYFjEhpkLs_jitYj247OBUX5S1Zjj7TDUdjDBaba1Kd4mqPtBr
kIp-js-H24tueQhiJ59XrDjmt2iH_VQDbGxaH2GsETzMydCgRNOcuIEanpRVXqofm33J91BfjrOrpK6VKZ_V4PF48fU-19cro8IFy60oSpeiQb81UyYKu4ry
FQe2DPcTIRfNI968nYBNb_khC_6FG9EABUL8XUVoQ6AhC_7rg6uZ8UdHP15hD7bRXDT5AK831fFe4LZRWvdIgehNCoMzZuJxxPk49fopdvhmgY-a23Ivdx-1
YULkmcyzeuacRx8lDNJu_zp_zcsboGUJX6VoPIb2fWa79JGHcl0xSv0fHRzGtes4_-tRHo9oqQTJFY1DuaVOlHUpIjDIl4dyOgkxaNWYKm9maSZhvRuiKv50
939Xut6KALdyhi-HQ2TzIg-8Q0JmoRbSQ_m8mDvapcbupTcR15M--f5OdCbLo-QgSZyS15qVJMRHBM_E1OnwQNAKeAWV2SdEv7KHNDCrwo_WK8pJOSmAPlOf
yOzud6TAwh5DY__j6m-_YqNy9PzTXMVsQ2BTXEVoVzix4rp9GHY8_gmTsoZS_xIpkPVacpZ8mmZ4k8xmH86xLEx0aucMAH6cQ2DyCYN38Q42wpms3Szjh5F_
P7ptbBZS0gWN1H4lNOlCn6gRAaTbu8p-egV4AS88Af7h6_oq-sQuMYjH6GuDmNH-ij3TWd8WxO9d9W6DXyGkD3CvD0G5as5uzfHG_-z_KdzuJTnJCX2fH6Ku
xAjl9oOypsgPqZjYfPiy1sosgMMWuTJpdHQWStwoIYQo6K2tNmMkzYcutNZ7plCp9UJuvCGaZ8A976a9L5MmpL-zouV_61xMrvYs7hA2ZPcaRPF7n42aWe74
Ry2DcV2OfkGdWaX19l7V2IrCmiHCU4nRRtfAIbV2hBsThnWFOlUDUxw2YHQWK4E7n1vEwld9IWI2YT8CeCQ9iD38vFXVQ-TCIMi6K8D4x0OIcT8mCfK50m3Y
cKd8xKfK-tHLaOxW97RVy0-LULhey0_UmZR5c4HMErGmq6FytbEYv-xRi1vwIeQkH7D4M5dHfDXzsvW9bp2UJ6xw5c3I75cjKabcIjnB-m8aIrV2FhRMDn1T
PqgS8W0IsPe1TYBrhvM0mqMcnEE-NXzf_oAH0ing24ech16mC95756hpMi7lFQK9S59xIjIwRNHjMLKUkVisApqbRCusvGTR2WHYzuqpfNAssM9Jmjnt-PWL
F2uofGg7fDgxB38bPbBt_Qt_BfFSVQl-_jOVR1U5YPK8nOQLrn0KJ3fuVnNDUSLZaIdrP1ifo4eHnEvRPqJiAG8pCHDXstH6XPbK65kR7VVflVlMrTLgdrQu
bpPy0VPf6_kuZmjqQXkxWIXGhxQn6wZ_Co85nIKFYLE9NSY998HE926_I1BQdKX2MBX_vGQAtSg99BJxHP8G-aMIaDic9IUIaes8NojR_E_aXoIXtV3-zYzq
soIKTqYSIemkb4HScB2DAtL8N1M9_0G
}

