sprite $image163 [275x178/16z] {
xDS5UWCn30NXSlsqTF_JbddAbFZp_4SOIyfcsubSsnweSgisFOu8eXZaGJC86UG9jwVbJOx8DIUbyW63X0n2pID2wv2_CsvFlimWv5aD3N94Z7AU7_A8K1c4
LeEGLpNaYD0qsfS8qSdMhpL_ezmPcWn2_N-i6YN_eGmIwZE8arBvPwj1o9sXSaIeUlZ7w_QisRLoPwWPXBPzaJrY42g3q5uT4GVb87lBdGaPX9f7PBStvIIT
sDNE66LALveZGWQX-hyWRazBnnoHa46eXljO9JB8BqtAPJldeTkm3iNGjzh6bdZu_r_xfa4qaM30BrsMJ6nZ7rnIb2uIIKsgZYJ-5nAf7oApkWT94erd9eO2
I99q0CZWrGtOe7WPM0UDiq6fIpJte51B1H0gZN7cF7jGAHK0BMkWJEqUK2q2K5tNSa6n0Ga0gPP_e2opGo6IL4fPHtVFUWp9ssifw_1GVZc4vENbhKuVAH19
vUrjkIsb1CgKxWaGWwJojhozhdD72a5YWwHwU_lzfTHrAVDLjnR91kNsylB7RUAMWiI6953gwzjRbT9I9dCFjIX8CYXbaQHQfkpug1G5IQ1iIgJC10LggGgI
1ig4aP8xZk-4mcJy0xcqJ6YHcAcWk0lbuSFbdZiaai5tKCfqK01726HX0nEu9zfVxHWGiqNAkeC4GC3i1t8a0O2igIEb7HCCRjoppEaUoHcJrZsZGt5FI0Am
G6QgYq-ftcK2GhB1Hj6upmPhbTmNKg0O6p71WRmMgOyaHjc8o4PW0p1ifAobAaZseG0s0l9zi9OIp-mYIQ84YNY0KakW30IaHTA7uZ1feQo3UAP5ik-U3OdL
k6S4A07I8Dc1OXl9Wg4Y9PuvXCGcI2GFvvwrI8UHsE2xCO70Ek_59o5o44cRjJAjUyxQyHiW1v5u8o8hJCuQAGcH9v4W0NAx7ip5vyGX4lduc0WBm8PpHaey
ypmIaDw_6Q1pHaeyypoIrDcyGUfiBIL0daNIGf6SIdkkbfA3ztaa4TBTc6HGpW4bG9v5qaPARZxoMTmJppoFfEyUtLsGsmDvFH6Gvv4aHOBa196I4Fa4885o
nqGRb1_x4lbvG2BW_ZAeNgICxvbMA4JGJ-tuQ_a2814YOsBrdWr6zqmhII1oylouI5c_5aYUsyYOTDzIvWYH20dXZ0dgB3T6FNZteK0gRQ-b_DGGgVuKGQ1i
LkejDqRtJ0i5QJjo9FTV8YS24lUGCR7eHChF2X7ysK8YOoBeHifOJUJ8QX2idOu_l6UYd3PIUae7oZZj_T1g4EYvHt7F04tac2Jm1YMmlk3Yi_vK87cLLTpp
9Hr__QvgTlpD07SYvLj2fFhx92b4XDrhAUCSlCVNOE1-IndkuDqNAEvXPpKuU8Zq1oKNPEWiDqOzUFUXP4m2HH_edd82p_JSOriDaq0PEKHQ4SSG5uL98cM0
zdv4UL9IbZvXaWDvu13PNmqYQ9Yaum_GtWy8DZA1qlansDWXqXT28FUX95B63P5MUJDmwnubKWPexmUJrd5FzmyVvl5Ca22XPEoZUm9b3Y1fASaJk_yl64CU
lFlUGGYBh4lfjvJd5tYdSe_51WFwaJA-PrhtvBTFT2DbVC-qK9mnGUv4oZn0uXwKiiBTVyYi9Uuvv1byRg4jJG2G5VVexMLHe8mR8gr0P4mC14fPbhBKTFm1
sllHrU0clO-KzOzR8cNm4DbV-bYv-9JRTl6f4m69495v_rvzgm4o4v5q4tZysKPv-QCAj2yye52WW0WKrTSgs8LIFQP0Y9Zd7PF4p3IUYG04GH8e8anc0T8E
oiD7OECo3P1sK1u_KfCeJOXC0gL5KgeUaNWM0LA3HBLKO3eWGU062T8T4ayj86g0N4Yc9S8UakfBG7Hvfa62dz25v49o8RcGr7eXQUyu1Ccbt74Ua5nC-aYk
Y7LqgOFaqfSH-Gi
}

