sprite $image349 [181x249/16z] {
tDlhVk8u4uHn3CQswcbp_tVx7jA_TGyT9r900yxsbptl_4cAbWfdJl-o6UOYD0s_oNmj_ni9ZR-6F2x5Hw9SVeVvghADu7T4Uq8AzI-9zWI4-dT4-xo8nEPW
qHwBvZz1moH90dJFdWyJxSi2eEkVhy4784VxEEbrzPQC68uPxH7mqUNZ5DJT73FQ2zkK_w_dDFlH7jwCXdcSvEfv0gNPZ_RrpUZo_nmNV2oflunsUMkq-TW7
Wt2qLTZ7EDar-rrZG--pCNAqzRveByNF4pdQ1sMo6GUAzeX_c-U8HuwslnPyNFtcI-kW9SuO35SwEyY1FaQqPwx-Xn2vrDbEtj0f8-_gOuEOjanhixWQiuG-
IBH7KC57HV8_UBujepbAj2UsAG88zPTezEveXrfXgg1vUnyxpyiyATnxQj8SOsiFywO5A1NqKRRskIZG4bJGn-XZawHMT6OBlQUFJRutV4eRsja2lRQF3UFr
ukXOrL3KY0O9lRYFZGMqd1sD9wGTlQw0lRIFHMlH_zHdUPO5g15zkzt0Nhd-tEbJ1W_rTWkX5MtOQ_lOp3QpznVX0c4jQBlTLWnMUzsbLMoZozL0Jivcuskr
OQotcw4NHHkudiVYQdb3T4mRsSUmZso_ADgmn6SsR43BPAkWSVHheWr-XfL0PtPqnpGvso_hOuNPFpi586o2ExFHF7y_sXFwHm_RMHnie9RgrrzQpn17EDlb
9q9SVok-uT9QAF4PaqgH95TRIdRhl23Q5vYtKyQZWLGfjez4ksiVcw5SXelQEk91eZsKJHkZKaUxIc-8jgjzgiLMsY4riqNNFZOB2Ih5LX_psQEcZ0Yahj4U
piFfAf1oiSrcAQ559U-6XqX_vVdOC7j8Tz51DeD0g_OcNMyh2FxQyx4FjRJtLfHlSCn-YlRxjYBQVKxsOPpYL7Jr7hf8PZz5-vtLUdwAbekjWK3QHnVkq1wc
YXbMH-SZKcFFOejFgQATtN1fDQpl9wrd88hj5KJkY1dD7LeqZ7MzjEPYwoEvCAl9PkKrRVOj6bGwdEpoYfYAhQHaHbB9ff9E5rlN2ZgnUQoFVLJ4OKd5rlAm
FG8rXmTQs4R-7YsfJxJpO-RzOYjyJsEMqV4grc_HRWtsCrkRsTSUX9MTOkk7i7r6MnCwdDBpqIx5_wZqn3OLMqVp43eXYtZs9rycBh55yEn2i17V72wVq5OX
-pmRxJF5yV6_ZuQ8anEQz9K67oVlXZcFClk7bzOI5T7DYkVCWhodFoqlX0KmcrT8v2xHldnyPxmYulypxJonrRQdmwtO7cbYRITohsZFn4XH4Ka7eYHelfhw
sYQP-qGxLyJKnlFL5FiAhHsq9N9Jj3KD3nTR3qZjQhgXTvfYXUmZ7etsC7qkjcf7exrMNY7tYFPmyc8RiQvVJJqUqVzI1MyTwPb7lyFCrqziqHxQGut_qQn2
xXrjd-dhDcxItfvsQzeYYVnejCTMDAZijt59ma_r6XebTlTePxJh75tPqoYZxvFpP4OQetqH24ZejASp6YBI7TZbnpzbFiMPg4eRtxQ7F2OIFfqpChR-V8sy
ZJUWYzYs1_HXAx5RCh8WnxJiwSXqGdUDzb1dZyeriKXw18qwHVlQ4kqxiiQFi5VtD3xlY_QoiV5NUPubB8Cgw9xHNbgYNTmSURgKFP0PkzkZVxJL4kqhPlVl
tAk-D2NoMFfcf3tQmpJkN69tqNdZ3QTHlTaYHRjvpaiDRIim-0li66rX-9VZWKdHpcXRLqVx2-mLRM7sC7e_sifepl42ksJ4x1bqH3j_fI7GySdBLJtOzXGw
eftHqXrwUwSFivxAYEY6ziTBhjokAdUVgyST_YmUPsFM0PsZVRkjYXCHsyniXrXv-8YKMMUqV-TljzitjxnfSFH3R67TqHxjzNOp1JgFHaVdKHEvEzfdr7ep
LBHhzcWdT1jRPhtHETfcjvKVZbGbzqT7jF5eRxDCUeejh3ywptd6xj2-nnj65N9dTDxQPWJQJ_37s39x2JgVrql-E-qP4VOzUkwg7kQ4zhyZDRETN46ZiP_P
4v5FyCLGQM17CYfe0PUkwgsknATmYnbI0zl9TRIWd3hFfBiJ_3Jx9prrjh0cT16SUizvYtOP_q7lPsIvNp3MZ5vE_US24Mr7xsPaYGNJZcPUnh_zEphcOlOL
UuaEbD3jUxe_EbDIHfReGCT5vsWhskznqJaZqNxduw8pEzhlzU3e7EroEGPwu5jqZlPoFZfwFzhJhq3da_s0QFG5-yXedQvKedr4z6bG9Tf7H9-MIhIRqPUt
evtz8pJJkz4HxNOqozlHpcv7Ip2z7Utpe-QY_xPt7yXnuq0KXbyZTxZ_TJSq5XeeqN5MQ1V_2ixsLwmt0pg9NuGk_0leyKNeX2m_XTR15L-61khcZF0-xMXG
FnZD7w6z907Hw07GWT3M8g9DAqT3UwUZ9I0QrAAXlJIYeRqH3vqvtgRxDpUjDTgxXoTbGuVu4oQFqwbejOiwZIFHrspLGz7Nx7FH2oHPJaKdrK_O35IDWlOc
6jJ2e3r70uaZeLNoFEJZeBsU0g9L6g7y2XfVW5QL4WtjIJYq5m_jnKDx8T4Q3-t5Gtlnq5v8jCP3U_7Gtes-qJVwHj_e6tsZR_IDlj7FAF_Xw1jzes-quFkw
qH8HNT88Y0OA1qI3geH3fvweHqCZSwCyOg4feN91aL3eqOdQoDG2eO725UbVUW-41ZNEADmeSmHq1jB8GEfZJJi4sfSntqEeZqGj11g-ZCUqamIOHmLy6Q0s
VDe1q6YS0UeZ-r9y7yUZ7PpsQHzmfOclqPI0xE32Soa7N6daRw17Ms2QqvOJq6RNyvZKDUs44z35pAxGJlLB_j-qJq1N-xUB4_7nAfnBqJFGtYVeHUMsbY87
e9kPbDp4x4CqPHIksxJB2UXkIZxS3zHrtK_l1umUWHxhC-_P8yq39JqE63fZ7WqpDbCHtUeYZUOoyhfhEW9ThMEMrLHuPsSqaUhBIAW-xNR6YMWCpCPwmi3-
UyIkdESogFcevGVG2S-9r0YpCj7CLROFE9PPHtgvd_wX4r4bupaDQm__H1EroNOkYcWZeCrfVpVQgtXAoPGmauNsMSmw0Q-chT-D5X7LXAV4DjwZWQN-buiq
VDfvz2pVZsPMRS-wrDPVpMEiKsVcN6JMULVzWnylhp_l91_ap8bES-jhc6lQTLvpkKBhcnVYqrwAxjFHsHmzybhDGpsdJGcuF15LNwEbDGAUg9u9ryVKFTsd
VObMVOiUU6fDvw-qNHan6pbttQPzYTR_7OqqtZxIGMp0DxnF-rEqwXUW0SgBlD1bVlscbaOVebM_2FqsiGmlgPdA2tl1Tl8nQ5veDBEtpv_RoIBdeFj-JwBC
lECsClD1w6Byy2jxuorQc8z2arXwyUiqe_0hjF9XQ3HZpBAfJ3HGvHsQ3qAJMdsDxdxPztcm9-UWqKpB-WCTHzVvXNtJnw71fitNFNK34-qTY_OZV7GrdqUd
UVqFHxlQqtd7kj0gkgDRbuFGe66U5AowMIEaCMaJZJJEGQyd8NJ2XkQvRNr1Tm2PJq5xAHEmepkcUg7NArJEG5__uTzuZGPrEHEz_-5VKbFsW5aQ4osiPw6p
oMCfAW-qLrXDAr3a9FH-8vNDTlIiTbgF--eufcuBGxgZtvOApYcfPinaeS-lcz2RAtrwRcNQDzqGeA8c5KWoqOCGeUQdXvcZAu9KrJpbHWXJPaTpHgWAgtpF
Clu6
}

sprite $image349 [91x125/16z] {
jDVhck8W48HXSZ3GLSNi_T_j3lRIQinaecRvi-VtYLyQSDF3ccr9_sLD1O3D_q4U0JC3otWwFVDg6v27SvwrU89X0KZ7YSi9yaKYlw7PI0GEslGnJMlcNAum
7BTpabjAXQ28ljXnB9ybBoaD9AKRpfEIv-cR5qNIcr1LF2NvP4EoQm9SVQbUwJEIBuH8W00bLSdfCv9VOBr7iuC-9_bOw2Ezeiz8Fi87WolQgm1WVYFviEGn
JGImJGl4UyadY9oIiSaRjBxKaxzwtA8vDlaUTBdoVbLHwiVjIycLnq92QimL5jTBV-I3-5foJYaPwPx7q1DUtvhoTXdE8irmnPtVMYyddpccaJJVZQIgqzku
lPIyy5BwKp4sUYniu8TlE3_tWAUDxX8sgk3etX-62t2_qGcYqrY_L1608PBlowtu_Mw4WPBJM9V_geUFsmkGqzYFrKxtAi1AfceavtxoB95BCfAm7gJzfDDO
qSUFMqmpYKn6ZYe0UdoDgjh2zvEN5fgUje_7GskfoSy7BNzDNeROw8upMZjTdNwA0VoMFETlNl79dOcHmxyUwgpeiEFxoGVc6J4V3LOb86fhhYLOhAZoK_Av
lw8-Uyz14B9BiNvBFkNiZyrDkhUAo6jy_xWTylr6Vsoj-DKAFfXybDjq6Y0Z28rrWzvEFZq_TY7HdremX0R1g8qWnvDF5jVkKsiulOTZD_a53ZCRedK42Tpi
ZUH3bghoa8O5tK84yVLsyj5iz9-KUmh-4rkE9j__KZ7PZMObAPKqbaF9GHB3xXqHjD_qxHFDzdjoFuBtwE_aFKY_NDhBls0V9rchzf_Qa-kh1L4_l-UKCdUg
G9LKq7jhnXyzJ8YDJWU-WgiEqPuyBe9UugT1H3DrbFRaJcDSWjp27GxwW7oRyk7w4wnjt5hSqRmSittcsiapWU0p3dQuqs0-_bz07xwb4ZVSw4jLiNpu0AQZ
QsWCvbohRlWqGowlQIvJEhoAQrMwuLDA2pPf76M3TgLMkTqkyX6RzF0UtN02z7TRFgRDwJvaKINRMNGb_jc1dqQNP2v5yazVOz2MiakHV8C6o_0cxQuFulPJ
qzwdAxEg9z-YyH6THgjLFz3JEwynQF-UMtNYQrnkT4ALJXk-MkoEvXbqbjCjmSbqci2_xTa5iXmn30HGeMt1l_zrevB3l5axt0lZebSzJB6L-pH-ZOOVMI3l
R3r4MtHwKRTL8vSZz8gTlGFMh_7w7MlTUB8Mr_X9kd42NDixJOS9y0swCySTkbFgBRetn4jquzVekDQwyRX6ny-YN_vWElv8-Z_zdvxp5fqAOfTQ3s0PTeLM
O1MPVcM144jbNMajn2gYTgKrawZe1LguyV4yFV93cakc-ih7T3vCwqSqRPdrUNgybF4UBRmNoO7MqubMlhVBQCidMizPVvQ-QPkzUH3BWTPZxVSLvhr0Q0vY
LIRzF8qFqDH5BCnrHhW2BoNHpxVsi4Ti6_MtYcRWY306dK8oFjywx97QgO0URWWO-v4MJW7Tz1lv3UqJ7eXaUCP0ABg4Y1xJEtg_bjmqmqCXI-CUfEB8Kbm1
ctu3lw4D7Ws-jqermoDDczxm4_IReEFUMifkR3_sEq63ITSsNsFJwMPdQF7wuw9dFrFDWpIO8OoYfOO5HyOn6ZqzSt4DUrIqByi3T6L6Z1xKXBredp1yFnru
aWP4w3ZrVbEjQpgxTHPz8hqNZMmQW5UQhlGZz9prHz5qu_LJFK9Z58Rz5FLuDBb-xWhdCpDwGxmHyHZmSLu1
}

