sprite $image288 [236x171/16z] {
tTdPRYmh44JHfo8pkotv_x_sZjmnL7QY5ZjCn_iPbjWKP_ZaLx_lav-5oc7zKbBhbxw_jdJlJ-Mnl1JM-gMybfVoMZ-Ln_BIzzTMVsz7pRZYBR7Y7DVlYuAr
lFIQ4ooW9QLzR9rCvR5-QHzR1qlNiNKmTHrR9qfvh5-wZgs3fUlOEfYwZgq3f2oMbsx2ri7ITMmTIbNi8B6yT1rRfqeLUuQs2iEMNKfYlL8OMqOfZoqZbSUM
MyfZ_T8O1BRyr8hhkXXicQKf_zBDO7bfZMik6Mo1KisNnfOdt-lV6qLXovWlZyNpbGM7BJXVBxROTqOt4iGMcwykS2mlrQFDt8-jlTISrk-EDYPxCxPsIFMw
tYzh0WB0rZRfN8ohj_p9sEekUjW1O6iZTIvxt02mjKcwVhW9O7T8zJlLs02mjPdQFze0iBLPsZ_Q1B2r8CMFbiVMonijRGBOsasDgxT1O6kdDCVLNX3OsYMj
k9QM17OJjV9Qso2mrP0I9ti5WQqDKlaEDpQIm5P3IeGSlPygNySgbGyv2MpTIB6dPsuWs7gKpFAD0h3FvsEJTgo6l1dx-FXuFfyDBFtOzh5zwUzMELfVoBkm
Z-V7j8hM-DXkmVufdTQV4tAqiElvJgjepOzj4zlFLwqQil-nVHqxfM9jQ_blb6Bx-QfrxaS-jehjIiLAQ9F3waLLAnzo_-rPnwfKhQhblr7P-3-ZxEMhLbV8
_I-J_izdDl9jM9qXZ_R_yEPAlchrXvmtuRQmagzOOMqq2zPm5TkMgbMrZiSs-b-oR5nKiS8XVqE8-0eQumuhqfQL3tdq7jwegXAivDkpweXlL5Jbzyu94wpa
sx2Ysf0_9iKNqEcynOgqPUL3JlNV7MWfTeYqOUMrEVCLWpfli95oKRjMFkGG_v1mRx0ZvA8sh4wjBkL0lvf86zOM5j96pzdFjs_bjHkaOkre_KHzKVlMCuzM
f1qhh-NpLMjVwy-NiVgrKmfO9MG-NyQgMbvAM5LhlQZh-tmUf7rD-ljUmZxi-VQfZDQVxp_3G-RpXRL-AHuoVr5XhV-YKY7xy-MFbiyNrlgbVCZyHJr62qY1
aFbyUIsVxm4XKrA_za58-P3vYyfh_HVL7p8YvO-MpvVN-lFrQq4fVstvTuO_MlwYybh_HVM7p4fvBPyl7x8jNx-MbV8XarA_bhoe_f2vY-hNSb8_5gJwjPpK
h-MaVYqdzMCvgb_BIVrQJkh7SbA_bgFwjPpKh-MaVYn7zMivgL_BIVrQJkh7SbI_bfFwjPpKh-MeVYmdzMivgL_BIVrOZkhNSbA_bfFwjHpLZ-MaVYqdzMiv
gL_BKVrOJkhNSbA_bfFwiHxghm
}

