sprite $image398 [147x98/16z] {
pPeDRYmf38JDFoxRx_x7NIKehsUzGGhZrdRg0lE9SXKmDDsXner-bSe4C0lz6gK1C3FG4_qEDGOlWTilyOml_GBtylBi4Z0oFQZK6Um5Vd2awWNaeEfpmUVl
zKmXfEw1_4YbXuA_5xWzxvaNPdqY-5wF54BQUBQ1wkcXuEy5hezw5Y-4UF038_M0PwuGqlyS_4SA8VaXUjwzARpHOuKmL10Zkd-FQT0DqtE5aBg8Wtfyf3Ba
7gZxibS4406YI3RfBZMH1HK24aEvRtSJ2KE9Qh_n50dvOdeN2cfMwHxL2MR8qhiZ1J5JAtUUI1RIs-w9VX0vfE3r4VAYK_UmW1nIu4JYa9nx1q0EANeYWOYA
lE4UH4tL75Bu5BcGJEKGwXeYZnI_FYuakw1-M0Xu1LBJ7F_Vo2EPwi58GHQGGmfUHJoI7RYtF7D8aU3la3oKSyzvvZHJ8FWRfDr2uLlFlFIjoqg-Whz5Cf6D
UpxuNc3C6he-xf5qCr9kY9mKxcGP-j_88-qB0Gx88QtBoadmVugqAmI8EY27T71PMS4_GV9G417lcKSwkAoavTaXadDFrItH5icDrFQKTeha5igjq1x9_tkn
z-mSoLU2uzaYNL3r1y4_DivCWJUH69XvLzPl8kdVNB-3j2s4Ce1ta1QGy19mZkGBmVVHEPAQlMuZU0TfNmYDSOxaV-0OoHN2yOXxfELP2Ca_cTNYtGDEa0GS
GlB2d5PFekUH750S2Qes3ZSLY5nDT3iIL6jAbFD9ZI-a1OJRaLGp9QA6xmi1snlYt-2B270N4WImJaKorQD2WEXLrl8XX940PXP3OqqqBL450wFyi10WSfMr
B26419FEa3-3g89eJg8AjnUxaV98UWN_EacU8Ec_aGmfYN4deiAq7CB-n5Bv6oOmEoGH_1X9xPL8bALGiqPKqa9gcGP6FZjb0WvfGJcaBP2yuDii67reegoL
ChSocSeinsTnu0N9kxT7Sbiqb7LGKavP4rKhbDL6eLJJ6mzU01pIXx11sdXcdBLzhaxvGf92HEdaNkUXn0iUQUyPwoJIHadRGfAI9qPDWTil0Fcli4DISrkq
rDG_aTOg5So3HwXz8NmZE2JdsIN1A5z8GjIn-PZdx485o7VI7m3XrRZCTM8J_FEHsY1v8D_m9bFxGf9AbN7-x7laddeY1mJJdj8N4hSMUiaiymTGklDiLJ-C
4n5X8UN8Y-5-Zu53sWKVgct0c79TIAXvnjvLzuNWa3R15ydK82bnMKW7hy-naT9TpWH4r4Vz33itwaTlz952qCipDzPCbAODQfrep8FWHmlXWsPvvji-4NK3
9SvKva7mm-xfDy4NKsOKec6DYCeu-IecNWWk-C07qKoK1KHT2b75aMVnGdWT8gXXiDXdh2Q8g8qoZe8VVzE025w0k13DFuF691gVI02uFVGH6iIa4X5DfTGf
DsQY5Wb--6zoqRuEYHX4r7kUF49b7NzC-23ACYbRfIHptHYvFlUfxa9YorIrKYfK0fzSHmh18zKFXFbPHO4TFr887ccfSws1u0SBmIEbsOaQ0i4F5u97wZOe
3KI27oy4XuHUEUvPl10kf1O9_ls5e6qz4J_WsUwb6hr5Wtz_8GHFQVSNGlIKTdyXUC-ULmq7_ny
}

