sprite $image175 [236x188/16z] {
tDY5TI0m3C3GE6Jll_1T6LJ6l4ep-0VSpjJtYeQSnQwgdCrVpAohSZHv8-kktPkulkjXkK8CbUKqGsMxcw6o5MAeB6SeeJBR_JFhxNPtGoLRBrJR_HEha9Rj
p49MjeJgPKkeKhQ4gXxac5bVQeKOAijfXifokA6IhG2gWYsXUjaIgfSjeOhP4ggNBQ4wsHAgUv1ZPVr2EyHGMKupL9R33PLipL3P2ZLKidL39TkZKBriOzNX
SeKOAijXXifsDqDbEynGsJomJ3h8rWsLRCLGMQuGG3toR2HKBrj2zR8bL2_RM5b_fPncg6ntCrIsGmoLvGmnL9R33PLipL3P2ZLKilt2qrV0rWMLR1LGl_vi
Z5soSfgXikpjfWn05SNxvtytvxPUBGx3qFttJ2JRx_-qSo8KrVLapaD2RhXU7rw9rB3hzdP3KUlOw15y6PseDpf_F2AYtKtK-lpn-6rXkp_jQsSbsjrHjtQm
ykwq3JXPYHiFyWOeAqcqxQRZYyIwqzwM572yu3TMzqwxtK_KlhpzaXCZQ64qta_R3USA_oKrMP311hERQRirA6lu-mD1qbeJslkH0h4lacPehV4-sWffPgNx
JdkFGTw00Mk46Myoo5l3aDN3U0zQ9SsiSkR4FiZ6XSyV9QrPW_iWqzcQ1rUDZHimPksvoVWRfDF393QkFxxPLnw45jx9vVnPdJIpMZX9dUUrj5NICMiupKWp
Uc8bqPOLjMOz2Etp12BfGhle-6PMSrgGj3x8-X1jroLLriuKlhzDenjfzdMGjoL5pQm7KtuOZRJpj5rErBhdaEwqVimUqheyP93N6j_wV5L7kUTZkl5a9R0j
DxwPLPZgUTROk2AfiYgQaUQTJkTPj5r9rBhJPRIp_nZTD3Qk8sfcLQROcSgygB5nAL9bhPbqOoR9t7_c5tNSwN9GrFvZz1GRbn0rinPCHeQD-W-npJQ-VxFJ
MJW0DBAHW9c-Upb_fYSTTpf7QrjUhG50qNyc5dLyliBPb8-04JJGq7vT942QtktDBchTwT1EJ03utdy0j0Rg81FRtEDRTxfsWffqkk8i0W2Js3Zh-2fhUsxI
wR2Z0ZaAzyF6peqPW6bid9qKYEtnU9TEr_fhDJ9tkghFkmxojABc-zVEX0CMO1Zjh_GVR5EAghv-FEsiJeOJE8mjq8pwXwcY_qmtlkDEPsW7h7FGVvmi-a-R
bJHtEdPa6UJldQv33lhFRA9cLjTE1pGPvDhHtd-iw3_RNA9crXplPO-orEd-Hl-vVdp7dOuuuzDtfh1HaIVQRAJZJWVTaRr6CoDD-hp9QJk7gBgstEdqOQUs
uDdfekZp8hneUxsekXxFa4xdHwUJ7RdJulkTrawkfgV-CyFuAklZyMhvRwRAn4zQ7_oDGhflwZ_Ja0Bx3rSC92t4EfbddDr7c19htfY5zdfHbVNnutb3DxQu
fyDn03LuGYCjzvyyoDkLekhwU1phjGtYlPzRCfMfxZ_-jV-q2SONs9xr5sRl86bUNs_WQF40SwSRpBF4naj9sql-YU-Mhkkqqm5d9r2qOv0jKlynxJ_RfQAY
-kS4Bmr2aH-GA9KwNJNFNVXEUwMeJuzolO5aVK-ddQ0nZFmB_OTe4uYQ1_aTIcY9IHeGnlqdnqPWkqBKr_5FcxT1PWZfUoZwZyj33Z3HzlyStvP5hRGbFwrp
qlHEYq9hffjOxpys7EJhHQsrPTGzLMCoIaT7_UTwKREs7-XqrJn3ToahxsWrQnfTJziPHCtQWfhhNJiTE-qXhdQw_kvDDsQ7QMoyNjIyNi7VxJ_cH1DQQAVJ
TDdxV6jmEscl5rMNniOKX_eZlTkldIwL16k_B8OCyjMYrjhgyH6cdQxJIkNBVVx8Lco_BHrakrxKSMpCyJxHChpQozpHzWNp7XkRXrqlQXvaZOtznKWKXj9k
0E3Et7_SqFewzcTuHDZ5ejQnSNHF1wLjC3SnriBCQUuyQJzPmtcrg7LihEDGAIx0t7_EbmjXZPX0r5hRVeeKcG7f-mEIdlymPMweMAyNjTPMYtpkT53Q1e2v
_uGx0JTXdKBK-lmPVgS8OwULsv5SVDmYN5cl5tKS6_VtP4K6JY-N1Dteqd_C8uHr3b7hs3YyftCZ3Fdb5ltdNsJzjqIjOsFlgHBlqoFJ0inz7XvqPRrUr5fR
lQVpgjC16PUawuScy00OCPse-VoHe9WoiFHvA6s3rFhEQe37RABMvq--fylxyqahB_Vix1xXz9ZZH1rhUnRvmUyEGIWjxEZpiZTDAMe-VqRzfpFHlkvJEFOo
OPrIrBnU6qWQGOCvGTRp3A55tyI4TL9HQsrnv5m0dn-G0yJnEQh0jcxiFs9jx_-Fg7Li31A0iRNVWBwkj3jPkBBEB6hMjd5Vjij90phoGTX-XOSxP1Fx-wpR
oqMa6XkBUphGMDtHAklSejRdp_Yxs_IDgh1EBseUP8sDhaofqyb3MESMjOwDzVK6KwTBv-iIejQniUu_-l2_rUdQQnhV6RJDJFKTxLzblLRKEZOgKzr_Z8br
4L5hRNUc51HjVERCBsgjRVMTeiiW9zP5H1t7nlfYFdUwnKJDslR-GulwOjxqp5bArBhjgQCI6xteTCk9ci-VSP5dpJgElhDhIrhK5_DDM1SJjJv_wkzkJLbN
5BN-IAhkFygwgAZZsAYTJbYN57KS6prLEsKTTzJLj2s-ksrHiduyBqkgiL7xZx0kBcfz_cZ_4TRbHQrZetGwPLrVr1mRcSwSS9gm3axKLSyV5rQ04NSHDMlB
e_yOsQBVl_wDZhfKREndJhz_lOceTMnqFL-pgBVJzfFLxoDg7HkLzPQCgktzMJKstfvLpvzDM6-_tbnOR_zkDs6z_Ng6iDv-lVBn_wsV0G
}

sprite $image175 [118x94/16z] {
lDRNOGGW38DXNEMdiF-qwKqfrq_V2Fo0lIwNYAKMc9dsfUGzRygMYjLyGYwDn7o7K0LbRQgWh4mKb25KGLcxAYWhKmLbgGhA47SCgiZhc7EKYO8of2eeGwY2
iZPLK5Oc2ieGgg2iNHMKbGc2NlD9MiyD8LH1MRigA2iJ1ML8LL06LmLbRISiA8gytYE040JzznMDSz2H7FFUI8nMheUzdten3rtNOHY6tjtQ99N__ziN3n2f
WBUoTFSyZOvfnLLvtirTLYfGRcLMHAEIzJvc0S0lXKIYFXztCO7b-oT4aCGDUaj5h-vLh9DxjL1igK5KadIRhskkgI5oOQLWlTSrrrII4XL1j_bAfZki04FW
Gbp2RSnCPODElI5Oxzb2irTmuO26hFVqvcQl3QW635BMUnNJoH4aG-asdoaqKoTmUcrGweGsFpP2V-yrOW37cpV9avjhAaPRWnG12cXWf-XafgaDIA2iLTS2
KA6SekD2irUknFxe66AFhW29Jj71XERYfng8AnGYG_XDYivgxfolZm0LQDVA0SmfClSuCtiLrZyW9S50fyXw3mhDaoxKRvxgZ6vie24wHKU5vaa7XTncGzCi
EjXSroCsasxenGII_dPAqTxckjxUYwWvTApNGC-YbA93JA0VhK06FUdQzJAbI2b5EuIwMB_7CVB9RLnGUtf_cwATGYtrtKVcGit_7E32sXxzQuh09QLeLtFN
G-Icll6IKPRspvYZ6s8wA3p-YrdoioBl3xvcj759Xg5pVGszEuIY2ytrKIZA6Ut_ke2lALee2I3ARg6vlYgrZKjjtChXrU6gc7ft2ytr0xvaj8uH6Djxd5eh
HH9YtI4qbrFKMphVC2zOeZIKerP8mB9ehr1NJf5T0fqBXcQu6fTZ4w-xXURwhive0qc3MofcYhI88LFt2iqf-e7ZeWxdR3GSMrDt2VszNWwWgBw-1hS0xdpG
r5r2VvyYJpeoMClCA1SshvBgOQ5PhrF41bLGOXahcd27ZmlDcoG5YO0Q7926tsUbPEeneR_R94arHQrAMTy0GE7a71BwUxrE4I7HDyjCr2JqO3b53UQ9YuZV
Kf-VHtWvHVtDwukc7XNw-qqofqZsUghGl4cIGKEJrnE5vXHXpg89jTUpXMQzhxE8YShwMw5dfMXHzbf_tgwgxyqiagaN2CrwdI9JBn6QzJf5fcQXL-bba7E-
qaAlhX-eJpf9EuGUIb7tYXqpzDWcoPNwUBkvlgkfzt9bwgsrS_t-0W
}

