sprite $image177 [243x176/16z] {
vDQ7jGCn24HHWK03_HVyexEDSnpT1XoMTsRRQmYYjvc8vu-XRHeM-S_R71Iv4jRuoSWjq2bkUjkGHgn77kBC4HUYqmvJ3SeVCNtIFV8q9nuc_gGzpmPbl6dw
f1LvAQEAc3zfYxmEb3RYcWjhnBKmchVByw5pH4mwM1fvBou4mqIOjEUTGGc6YIbfHJw62q745E-WbWy59OwuJfesufeH3rETD6t4DIZjJTTSM8Uf5aOSSPtq
UmtJiCYxWE7DabQKtyNlTRxVp9ldWeCu38HnjrNU_t6l5r1s15hdDfUVgNoCobXswWoaz6UIU9PtrRIHm7JbOobTxpQLwhR4zmLoveydSNxNQ6HSWhQC3tjG
7DDlwryzO7RQ9neJRXprNKwwVBHBunfAC-yiht22vaMVyg1-9IPHRc3MkKNSHOK-iAmqsGcOPINxaHaaVlc29ShqWGC8DZMnqCLZZXCNLg6FU53Sc58ULw4R
ZkquSRjAF4hUzQ3xxjAgpoh3VlGvihte8SesUklyaPHEtMqFwIgqPIvFYMriJXMoXSrtyFNTZGdx-dPXdjzROZQNk4C5tf_IPToxowEwEeydn2yVKY5qF-8f
lT-OgcEGIAH_esmdsux5YVcZHhlq_ivuzLo7I0kdSpL8Fh7lw-f_uYvbPLoPISIyEe9XdLa84wV95EpI-xDB5kNgnJR5EfMbMa9Oj4og7DtQs9zT4giqd5za
qxc7H6v2U2rPWUa67MNFNSvn5ReVa8jDQEU82Kby4l6bvLtzoN2NbVlkyiZJhSodDyiCPBDzhn2qP5Kk_gIu3Qli9V7CLaaIQJYqZSpbUObDk24VHOHinfPT
3vgQ4oKMIynzFFquJ_3IRK_k0bSQYLzln-Rm5xjB82KvLTk0F2vUZ4MUhyHRmrz_nGGSTOS-YnkCR3Uk2qFzYp2gvAd7FIZ-s4pOCpCdU3lMzLDFw_KWg3yv
bJoDU9V6mJ6BKvaRR4QCajc_fGkwaEnOiZpZawBYk4kfi07JWc1KllZGF3--qYiHrf-X_eKbw47zNIGMnrXmGa5FpSIyrQr-TVNvVEachd5VO-Nx0mYHdGKI
h2LRBL61gG3PlAqGojTawXeoBtvA-sqD60jVIuXS47A3LjVg3uiNyyFjlS2U0jU0bk2ATv7BSlL_1bqURmKJHcx_0sIAd2bw-cPOf5PzRs0Nvvx1mZQU8nCp
Fu8Us5QKWFwWV26mYNyrksjTVxY1eR78cU1B4-kFa2VqEOGROF-Mp2IgVo0pKMHEutj2euIzAZu_xcuQ5QWb8RlfZtBqJsGWD7OkMV2Qm1e9YyBwx-ClPCfO
InW0tABCnA8dP00DbXMBpOi1_OdP_YJLfrfsunJ0Yp2c3RA5nYftF7vCvEaF7ZImbWMMDY7Wc36mHSOfJNoPMZV1xhvYJzXn614iHJGFl5G__K0Q8kJ7j4Ns
XMPL6UaVOcSOHtWOwrmH5zYP6Uy1iFx3t5ZLGRu0MsHcGc7nLxqOuapLcy1wNTWHOU15oyBRMwoS_qmP0mnY6Y1xq5IEGcO_4C-VBORN4pZX2Lh5-nwiqeyy
HONTndIBp4GW7OJ48puc5ZcpQucmiM19U9J1gdy487b9390jDBnV3AFQtrOPBZ8PcREpL3VR1w6OniWOcfmJMbNmC2wBx--auygitc2FE0YCaPcYnykAECEu
oJS-mQlCCcAd_N5COsGiD9w75tQtLUvCl4nScKLw_4yi45Y5EG1jaF1U4QZau84gCpvzSjG7xZ8YSjo3DX5ZhgF3EERixFNeJA1gG-0uif_IB78kNyCIuxhc
3r7nAIFAfv8joduIRo33sdtse9dK8yuY7YkkpENBevAfWqxi9x6F7FIWJTJaCTeVzH-i_N1Tnyh0JeEOXiXRqAkKfSgE8qkaFh4vE-Mv3cvb-S2ikejyxq7D
MPNwIim-g7SgmHuFLL7PY6c074pfgyGZ-yHnvgDUaG9c2oDlGXFerf3OP_PT1-q3OsGC7TYipvWOCm_udvsukzn7PehzrqSWiIVMIWVEQ9p4-yXn3sglj6DY
dzdui3spXP7teOdQTLqWWeXZHoNBucrWZBpNfOLAwAyls9ESXfTfY0hlnVG-CXFwSPdvd-iC4jlRL_zUhmHcb_l8yIujVnhloa2O2FFlzh86PfTxo7l6kw-O
n31anhgPNOh-7B8F7POOAxZjBZ7oMrCQI1o7VdjC_rgzMU1644KnR9dc_kSjS_jALhHERl0qOyMVXf7vXpwdmWU-pxAxmA5ZGH3FkM_IFHfwCFrWqC3B_gb5
Apuq_wVlA_HLOcr3ppOAylwS32FjXtZvjDOxw95c0n--UcG0aLP3V5eFpwFEREWinAoOXcYHll1YchEcIFl-wP-VXsrWOIK61lbuyfz1MWpndBq6wG348z9i
PejT3h4YpUroY1Df3l5kzOzSTrcvi6BwpxYvPMKUug6Of4ZpV_h-005c1v7s5jESDKLQK4nMfFd0zyL44zWfia2SHzeESTv1yn3xaRui0eW33fewWDZnqP8x
HVbj3p_IVEyI9k-WqMAo8YqiflnEKQQOt4W7xDAFTA2Oz4YZJpn0B4TQLqnv1mr0R4SQd8ndadVGW5tQaGv0R4SQ7AfbajyfedPPYBJNBkV0EqNMOfg3xnG5
xDBkeE1GhHNfkcBYTuf-UJ8EYaddeC0kMv6kWvWxA3WPjo8DHWPsgKPQPvVvqqfWbwr8WojRG_JBIb1ChKYF3m90v4ZNsIM_KmJiiXLfMan-fC_3oA2Owf06
TjdgeC0kMv6c41SkAm74hGuAxB8LQM2NhGuAxB8LQL1CdTalLokcMm
}

sprite $image177 [122x88/16z] {
n9QB3kie34JB6spo_x-xcz2968j5qUqgrthI4WwUmORFdqUesNt-GhZSH5fy7voQj7z3QdYN6wkq4IB5lyVrHQJT8Isxzmnk52_PdIpt9Rj3DToNx8R1Dc3t
UmQ_P7VSSc7tEmQlxNxFO2jvSl-ZmOjAUiNkQ8L-oUvWXNx9RfV1bKT4Q_VlhLBgFlLxqZI8FrOI-XD6krEDeYUxVwgahsjPjWdxOSyiVlO_jKef3zgO58T9
lrKtLR0q3nt-2oq9NnOrKiG_DFX2QKzxz0tsqkNwJao5FJSO7_bohNHKWrw3GzVHnNoUsTazDPY4IjUWDw1N7iFYBlTPyqMUsys7I38I6UYA6MB1rI5ZcVSH
hDtFxy90QNQiMCIGl_ES4lYJ7pTK68msg4VXh0DEqLhhfcF4PytOlRyBfSKif70QYr3IDkKuoibzmQfZfKBDV6dmt2hH3pgyllxKxuT1o46aVEqkGdd52GXL
nDYzRvLHeF0zalPTTbLHOQ2mKu17KcotlGiHs5KMB7N3nDzoomY8ZUaPMb_plRN7sdqRJ0fRsD0IjkTunedpan_BRJXHUwcjNvMYRWcRb8qYyJR1WJnbMMWR
kdmksLSbRVntCcjDTWykYq4vcss0743csNuvUtN7gAhz_IwCyOVP1WGe-OowWU5qBfFMVYZOfcU2LN3Sp3Rqw4S_b61skcAfRD3IZ-CYCxkE-OaA8z6wg-Rf
nyZDyzKFy88Biavswt7YKgUBjssCSwpHF3gpZjg53Bwu87FQlPVQPGPdRb14Ha_rCYliHh_jfHrg36OoiwMV6SiDZZfNMx2DWPeUz7P5i18BJMHc8wg_tpXY
bATGlbQ47w6MosH6stTixEHWqcP2FHGcT31SFURe16QsZWwU6Hmi60hVpqFLUCwJBiRWFPdjrZWMGFV7ayU43gkHjHmbrAvMw2tPihLtfSU4Kviolqm_MUJa
z7KbxSaikU2nCBrnbkWXE9u1LkY7P7lKwhqgIKYXUbV2zaHRyfwDmYuaeKNtDCfOrzpdP6we4ix3Qcc6qVmdwSRWXsHROK9ABwFJ93QOuv_Mx4E5OHY80IZD
7ih__suvmbANL4vYbIdYLvypH3FliFgjSlpOIHnS67UeRZz-xtLCTPJYPxNVxG5NRvrlzzyHeSlMm1NKYN1ds0HtTA7tWPwg57SIc9BZ_WsCXLipt1hugZdy
dk8MIzu57halnArtqXjmYll4Fy0XRhtGsy0j8MwzaqRx-y5XTVkZafBZrgEIakBsHwMVKN4tWDlSKM3EydF96y1TReI1VMxOepBD3J4gstaGjsX6dON9hy2Y
cS_2QCOTeba0Pxdn3YmMEiKDyopCSyCSbNbkcACopmrpLEQv8KPbClmm17fi48boetgH1zQtItND1d2U-xI1yzmTu2S
}

