sprite $image157 [275x175/16z] {
xDe5WY0n24JH3XAe-nzuTzmPbwIfTuXVj1n_J7EEunwDYGjstA3Xk9PwN29Bt0avI0AFpC68FCAaE1vXKZHHYC68FEEZw_3MqjeERoqw9KKIxp97s-6jUTlX
hQMs7TvQIEFXhPF2YBIvyGsVbyg854avSKIO5CTtI3lhzSwaIE0RJMaxl3KVfnfU9aKJFoA54Jd780_7Z_BTXvT9qS0l2DbsU9aKno_ojiDRIsqxlBMGZIB2
f1Z-Z34YEoHb1FvOZ0RN-ywl3IonXBIsmrjBNNfukmwouH4cHHCBIcD4dWbPOdYP54kipPRvswpL8DV3owGujZ478r8CShlXVJifZCZ_Riv3EMwbLy8SpY2Z
hVT_sriYXUBz4xVs9D2B4oiuVHAwspsGRwuD7f_UlI7ZFpgzUuHxWwGyLqHqMaHuWwGyrdXrsyWlAFs6t6-ySWZs1QLTKlgDLyxlNHksvwd6AwNR5X7T6Ry_
lHUIUNmkSuGtP_p-sgoGSD3tyaHu-xL1Vtel9A7p6qbxnk-lpIuaPhAyeJPeDTvx9DVEUFIbbFxQh93i5cKtl2RfFmXbjHdlFP8hm1xxNT6jHrBwQpCf_X4H
VDqW59C6IMbzhwf0l_rip_x_LAoOD6JypjgivDM-ML3u-T6WDRx_un4DJMH_RLQEmsEZqEqaOqPbpV_KwDvXlFUvH1VxjvIC4uJiXQGtuvU8T23v7ZurvEV3
9gKbVHc_TgON2TNdXchtuqQbzqOazVzFUXgqXj5nOT3piyGVz3JexYq7GrmKnhRD6oGDacBQ0kLIZNauJZpeQT14rIycFSAY4VwSQmDZ4RLEAEDCyi-vDZ0X
uJOePSCMuOyvO39XOHPjXB8V0bjC-YN5L8H5-oIbVBYOz4kAgQg8gbhNzbI2VGeKDZr7j55Iw2W6dW75iv2e2PVvz30PT43f1W8SYwF7zl3njxgt6U2klKWy
W1C9huB2fRDDyP5RaKG2XSISJoWiAjfaoBpt8l44S27v-gMinxYSok8T1ZZPUtVcGiA_lhvIv7GUqsCQnBzvPseE3hpyrzSlBZy-_kqDZjYxCpNRF2WGvnVh
_v-UcD0F13ZU-5HLbeWUGrH86fXqYaZDMKYVYlA3P4mk90rG-aIaffxwJ6l8awQg1xCtGEdRcPhh9bmBIG0awa7Rr9E9VowG6oIdf1IIE91eoh8JogUAo3sI
ROYTZco5192DFdHxFF42IPqWdPvZXIHtNTAWitr0aDirbwJ8OlKWiWGXPTS69Yqx0wJjMqqDMqKrqX0d8EUWafHFDTuQd__ZzgQG87q6817KOCWDEqCtnnK7
4WP0gYa9p56Iyhb0PDn_vPg7xWuGGYa1M_e1XkmtEsFxgqEjY71cNG1O76x8jMfxFaz4Ocqlvx0PMyC1ILCpmCSiIVcqdU7jzTINooWPE972YUIqAwLyaF6-
yQSD7ybLrd30HIm5Y35_HqdnDuptRkfYcLR23Iwd1N5b_8_OcQ3jhIb98IK5Scc00TzhUpxMUE_dy5xT9v2IgWo0PvpZ_ZkBoBtnlfOKfWW1Odd2PcX9ok-S
tbyPxsj9sVS4s2LiXcwpGL8wZFTUKgOa66aqGrVwPSY_8H0Tsv-TTHWowKn0lv40EPvT6xnhlEyF7v8o1B0J2LYuQeEFIE_lp-6zHf8wGwS4D10xDMnFW_7U
PdnRsw4bgXA0ZajIFYYzloyfn-84AU2I3RL1WuZSrGOUHtPBG4tS5T2jQeFFIU_l6x8lJcYaaG8vhQ69x16H-zf0Pm2-DC60xYKfdvNUtwmD1WEkeSP0phr1
KXgCzrN6bpG5V3aWaLTjy47f_VtQO100jhF7NwD1KXgCzrLjO00ZTGLWfAlXsg31U5_L1lBJuwSPSiq6cMqmtdj9-UdnNTI06F4p_h76Up_pVDpGh1u_zuZ9
1QN_qRjZpem_DmVCLB-HZFsIb4ystllQm7a6p10o8aOaLqhfDDx6sNzIob8SYpC2eEk0gQiswvog3UQU9n87dAwdmVxtgaP98OyHCTZWXgJzRzoUQ37Uzsi3
vx55Z3WDESUaWl9F6cyFW9jhWqDBKYa1XbCPSj_lUFib9M8OuAgQ3EGO9IaVbDxVhmrcm0sX181Lof0RhitwfmwOY4a0a3Waa7iraKtflLzIof31QS9vzFWb
AN-RyQPrxyphse3iq9Ab2LVOh8pVbjxx9SLb7mc8YRi1jfMa_2tflMbdtcyYAI49PmLo-TL4TjHc_RFR-Luw0t0wUtmRMfBIPxpz6Nydm2rL2S3Yy9AKljgi
F-DpcFqSC177LHiq6c-_f6m4W5s3E6Yiwl7xqdj_njUfcOoqoK6IDYlZTnflVst04m1na02-rG5JOstMBoaq38K4ypBanjgiF-EJv98WqW01Fkg0gTDu-oLb
ao3vCMIQLnFP9oBzjO4UYnFJ08syBehRZBVVa2De0I0Nrm3uwl4RtwlwcqX94D9M0CvN4_btdda_lpRWcO28PIZ0knQKjlJUNnlmEBGaH1J8iIhZTuf8VyQN
u02C0Y0abQHyl8ZSNnGh46fdZx-VujjhlFqPVpf2aReI43iFcB8tlVVN1hG4m1A797AdY6okpVgl3TP8WE722TYCoFRqtYyfPC50aYIYa3GRRt_6tqS04cfM
IBgDj_zfa2aWYQ0BIRlnzjS6l0TgSHgCzv6rmKu9BoGDnlj8II7NGj9GcpqquuyB2RB1U9yeAHoHlSRxn0EcR33UXqjADhnNFLnIiY6zFtnx-aNa_m
}

sprite $image157 [138x88/16z] {
nPTdkk9A34JRnYrLaD_-b_i6BfF74n2OSyDlVQWEfHuzbi0w-lJPA3AMyMuk44cAstWhQqhyGBYCjx5CYbzHhkyA2CJlq7lYigRu0s-9on8KV-0jSPaK3v1Y
ETVSOyHvihd72Dj9vXvmgj7RyHmTe_lcDkBIDlU0hj5zS_jnwPlRYCif0MaKG2CWZRWqp6qXvNfwG8wDNjgBaTYWKG0DSnj6dx2OnhtGDRTV07rp-qRtpUt7
fHyGo8q2UAAvYWLslm3wvcgEiT9wILosVp5NCIxB27VZqZTNCTANpPHQ1T0tLp7cRf9WAovzSnLZRBAsCLPK8oxjhtR5MCSWnvNDQXJ0mNFgNtAY9N8iv1pX
HW4qErSneiWvPb6PQjyBDtCVdSJt_qyf08cFieMe75knmTS201wUHRooBDPJxWL4KkB3Q8wifzmBo01QPy0wr1z5kU9APcCMB0DbiOSCP28ZmSVZieuLPWlN
Zapb9m0-JepPKxdsVITott6Zyx5qaFShbqH82IH0MpmTrtvZZEsc3-PCIYMUYsg_CyPO9e141R7Hrblcs6jSMGC8aP0cwxHPvAzpxFluu1gN861mgdngG6vK
ZCzCWA1HYLJfrCNiEvOVdZff27icRPsu65t6zwnmHb7SC_JIk7mtX-VucKtAs2bMXgqNB-P6vS638qHaKH9Grii3mdKSiS1965OYotffGBoDtt6XW_Ajf5dM
2UOUCgL9Pre1bKumzv0bh1b9Miyh0DM1kRzdXHmsTI-04ymzv28XPPWAbKymzvXf9caKa2gTOEuXInfX_b00JNErZKTO-QK0Q5idc7ldk030BLLk1UHcReCm
aGLapNIf4v3Bw74hW4IO2jXwrDnjzBaLG1Ii1Cjg1AJDfWf9i2PK-kV5O1rF8ynfa_Qj01f7MPiLvfGXQHxCSh2OEPxDXVS20CDb_PsvkOmNCFLH07imLNhY
L_kZ1U100BOQvhPPQSmzWNqcRNNCxHijJAIkiwZSCBTFICmTOaMwr3At7nSYTrZClA_8zTXHre-BalXQ02rp-t6Pac07v8wvVSAQCcb7jSpjiy2SAZZSCFU9
1S0A7podpcIAgN33tESMGDN-NzlSFYliW-VKwLoahhd_0m
}

