sprite $image346 [271x347/16z] {
xDQ5OGLG24FH9_Z--zRj2tLFpWxaCduC4H4H4H4H4H59sXotQ4TTqN65fjUjt8Eq7iKQs7RM0UW9MLx7KWOggtDYWyQr6Zu7cXNr31jGfjK1x0dHh1V50eqh
z8HChrTJg2VqPIcGSUt5WenhpoPYN7kfl9C3kNad1tn1nhLd0745ZExE-YInUIV_wc-t-cGA6TTU2cHSUx7-mHEAFI6QzPKKCgwztFyWheWJelLDR2B6jPVw
3-AACo5MtyuNx-I0yKuEf436jHSRCguzdn1FwEifx-H02cHSUx4GuzgxPCS-SDmAOXY0fhaDoVjVDwX21bcqiMM9Q-a83v_anz1dNFCFeiiBJ_w1AkMuzCg9
LCdnkn-6H8znpSz9ASUb7qPmJ4xYEEEgKevkurhAyQTjJe9ZSXB76TSYZijgcvCuphXk79EJZMF6TUEOSTquPbp_FNpQ2qyfnyKd9_aSl-zU619cND_3SV73
aF2fFw5V7sPSqpcCnZMVuuzdJe9ZSXA76TSyZilop4aSPbmtZib92iV57qFIcd7TE6PS3pZCNdZEEIOd1nncBppd73Ek6yUCwyiu5bnoaiznkVnO00p6DP_Z
v-MnrWFeuG6gaYF-DD02X58Xnw-OanOWa4ev7bYh3GYeSWwi_q6iSnBtEE9WZm-4KWiE0FKWeDfmV0rIXr7FKLeXb9fn55O8f7OSPHK2gXr7NM8eDURWUq4W
zUIeg11GlJdoAsJ7yE1uHs8esN0m6mII2qT-Oa3PSM1bWL1ouSYl4EXTTt-M8xz2GDbmv5S89HUE_CHGSk78JmoezXmNnEL-8Q3KboFkUkg1X9oKSzpMMgSW
6UDQtntXaLKXe8muiDO2yxuGIbOSn1E9GK9EgeUMMOa1PSW100c90ILFZemAeUJAyVeA0LLyjwSuW1UEBYWvS_2bYQ5aoH5VWnWW1udPGI3PSqWy7jq0sN9Y
pY5o6zsZ2WaCVmxnoGhXfk4Ubb0u6rte6t7yPUzEb1rLdJYEVn44WUxtVzp_Sgtg2iGgximawk3fskRi-edqhyba4Mk4lzb2H2VYa6BrMtDxLPs7ex_iwo-6
RXMTZKCQ4FcL5LDLRyDHl7o4exz2pEXluf0LFiTHow25t9nZStoKGmOjvDOSrSCBH_m3Zd4BkJ_7mYSv1Y5JvUOSbIzm34BtnXpRrpXa079BZl053gj12xaV
X_1LZbe6BUHc71bmd-KOWzY_RiSHOV5VvP31c7ehZWNYTpZ6BKHknr61yZMESGkv6KS29oTmoA25t8GZGD0JE0OxtPjm2B2TnT6t45inj-78G3s1Oz12zZAD
SpXoaAEOrJ_c61YCMuXngDHw3aSDa8zYjkDOly4nRY5Ig-h-hnCu907uevWzcyCy-XQYSjR_ivG50Ef1p9x1CGOffUmc9t3OAQu7CNiQntZhB-Saos97Bcyn
UpA7rHk7LDMpEL8Vit8LH-qvgfpAuG2MRWrvlOn3wgKS4O3SnUmb75ONSbG0GXUp5t5ONSOXeSlQ14wlvgYNSHG0edtMm_hE4Kxc4Bc8Opzj9rtCNiLXTGA7
L7ddsC08B6Qdvv0j0FZQSuXbhSNiz1pLUg6h7OSc0Ch-IGTfTWvPmSht7FAIjHMeatDihZtEXiDIj5hCJirH-rF9FOTbhSNil1p50U1YBcd_vzPpg6MjcDOD
EJxto8GbYxskPD8tZhmpMSmQHvoC8mAGxAmiQ1iESG3UOdRdiE-TXYDseqOoc8R3idQ1P0ARwbmSqHP7Lps70B1Qp5hDnB7jEJBaiAnDiEYi7CKqnXorknkv
B__NSyXYeJhciFFD7-EGUt4akws779Qr8BDnIB7kw6JCqNn4qCauyf8iLU8RbSWXXsNjDXT73L1iigeDHLuNO4d77EB05vsA8pTpjtkriAWa7d9eT9lgN1mh
uErVnb5MrqJW8OU8piRXxSRtTjurBRIrTHnMat48DZauW2MbTU6jue1ZbZ6iO2V8GIqx3Uj3E1AswN2qvTOigjKzwUe8s4qVMeiY1WRRGpXUTYa5gv2bJUBw
30wnSxMxprtOfD_pBuR7KdHUZjmySaNobgiS32R9E9BymdLtVuxIxbZZO0_RZUwngax48IlKlfDkW_l7Eh1vE3RNtn7gW3g-E6Rag9x-GMuLSCCWJZeZnyfU
jLq9OJIbUPcHmuulTganqA3gZ1m2zAl50sMWaNLAZWoiy0eWtP0fjOyXI3edHmHiFsPZEVwrryQt9oSadPHZ0QShhrcIcawINcqaOXepSWWGD3Uh9Up_jXYs
HY7sk8vPEJAGL1p0-dB4qZogmssYajSTmnKzbSETo161iaShJko2iULHw2k8JiGXxMthTuK2jYRoQ-iGsdAR_bcvMt5avzNAheHcjKI3UNy0GXITXCCQexor
3crMI_iz5QpMgZeHnsPBeciTpMfniBm_O10N3MCgZhLj7OWsgwLstwAIGWYfYEfa7D9iJjeGiTMo3GQBUJZKTrlv0aJx9vQvzHaS_KCl4f1VZpFkqQlFuEYV
lkVx9wbv5I3CpM5TyE3vMKixVqe1jeTms8E2-zPXsP8JK9_2KS48h7KqZonUmUbJE7G1orODW3GnGrWWF8SZWXb8DtywO07ISpXi6BVviwU2yaqERiMX2uQG
W4rxAf07SKGiNKCV8WxhB4_XADYSxleGYPOxp-2mIo2zjGwZIl8eZXKWwE7MrH6gwgCuCe2JmwthbbKVnY6EFKoNqVmvFuUjbcXRrwTpP01lzne_dKC0a0WK
_U7G0502EFdXs1EMv23eapZqWCDMYmVI3uUj5g3yS7JlYd5soUqux9Zy1HhnXXpguPBMyT_spcGvRXYAWTBie_Vu_v-RbGUwJ7TXgXWhq10tERTE4GqgYvxh
ydfEdnsHOt7Swz_KsE4hJqDmb1oA8vRbbZjy3MqOZf8v44UvHVdctDTb98wIaGDmx9Jjj4ZH3yksRQuueWwTOJXY-nC_72nN7KUVnnRfX8FbgkC085uuDbck
EeuQ0ABYC92hDCCIUCWu3EGgxmwk4CRX8rTzT-29OHmcSjLnP2K0F027brprtV6nGl9_nV5Obu4um2eWNS3X9bTzTtp48-8magk-E-Z4C0uNkUfL-X41d9XT
SJn1hcDtHsA5C0uVkUgx0ok4SHZ9LN_VmHL2EBpagkyEE364mqwkZ2EIMhG-0GuRkUgY1GGDgprm9CXr90xcqJi_WCDAhemZ4qzCymGudEJQvjpT7NnYMkC0
3WEvQZXAoYS6S1Z8LSAHqLaQkDihZio8z92hZYCwDK5FaUtNYjDAheo3Qe8hf9IiaFxDvubtmS73b9ygfNIJA-Feg4CuCJMHaNPoPHo9rtjGplQdXTD7hlhk
w5_lcKTMqNh8LSVH30_MRFjhsUmE2xdgEBB-laidvXi-6hXlTy3rliy3TeU1N077YzVx3NQ7XLmP1r_loJXPVnXf9rV6yUhrVckI6MaYLxqxlcfHUA7Sx0uN
kUetskuL7auCx0u3kGhlExhN4pHEv83T4IZN7TztwDVxThnbH7h8LSSHhr_lszrX85V0CUHw7r5XHAI1N26d1rtlPUcMvds7WLmXvms6c7wzhyJIGQwSg_mN
W9X7tHq6SkMiz-X4lTx3xZ2GArG8dXX-Yl8x4UacLxr2-7eFkyD7hdg5wDTxtXtwlzypg13jUW-xGvQhSuLyXbL_c0Fawb4XO9mQlJisA0s32a7freHibhWi
HhbHXNnfd0JHebmDAuIlztyumUv0kJfM25_latO7ozMoGbYw-kx8wsARctvYO7U0NCsoyWffJqo1tG5oDSlv2JnWTuXozQ-G_lM-FhTcuKL-z0hXtV5KIiE_
GgA6TyScozM_Gh8HIaQa85V_N3Qe4DWT0-HgTv61tG5ojQyGuD7i3f3hqIiaONU0N0zQ8R0xGAu7hv1A8wfeKQx7hv1wOfhT0N8zO4wT2ebI6XntFYV7hv3I
u02vlak5L1hNI93hWRFUUpYM5KhZJIganG5vcmgPE6fk4qUtGZfVetxd2e7jzOuLqbpOPcwHpH2TMSSDqPcPcPcPcPcPcPcPcPcV
}

sprite $image346 [136x174/16z] {
xPQ9Sgom3aHbWp6Mkld_ltqBg49b4ceOZGVUagx5TyboOfsM8_z9-SjV_lANLET1xazfgbgJt9jXrYr5Raok-fKstYP6qM-PizoHiUbZfkiroRF-adQn9cdI
Wyp3lIFPK_FLNVNSeqcgUf1BE_pGrPiq6Hx4k4UJV68aKKtYNOreqh-hDscIPusbfhuZYQVq_LKddZRsNP_npBblL-EPUeeH3z2lg_4OQ1sx6gSWxVwHaEzm
b6uZUOTZw3YIE4Ug7KSIvoZQ9KRkiHkx-Wv7xZqIZztKrSVOtIFns2rTZN3qxsg0e_lwv47ixf5uxCQkxW7riguQ6UFetzKuH-ufHfmZgRLEOiGvKcbDpVfS
Hfp3DuQPzQ28SoXKdQJ3IE8S3MOE4YOniWS7JDyXCR0FX-4T4f2zEBwJ12YwSPY5D36mDuSTQ1AaY7Eyh0d8xXmUs6bDZ0nmD3cAEiThmp6mCyU41v0p921x
SrIpLqcCdhvpKJK7EQM9WTqvt5CrWnrg4g28SQmavuO3ydCSjfCS32Tm6P7U0WPxeebJV9Q31E2Q70q7vESv_3OEDJ7WROWJ7DPKTMt98udJyLqEuDnUzvyQ
ltKOvCuHpZm_vm1CZqbwS5YHQNd6iPFiclJbG1AfppbsabsJNXpknHaE3nuqwSXHd6D-mk7vhWdGYOF8APtbED2a0mTeKl9PZiVXc0ydp05wi5IPJtCSQXBa
005w1h6pSpaUZe68F2-Q9xyJo8W0nq-ImFjYHII1tjgP0Ow7uKJU5t0I4Qd4rbf3Y6Fli27YgMyCoRvCC-CS1bY00u3VHnv56W6gJ4kOmqbUu_0FSmuL6Gai
LHgZ79xNzXX0Mcjm3WuYHd0GH3b2xpx8DYQH0SunYqnhQtab1sYZhAdEWIHfRUtACLt30ROaQPg7BuwrlFDInBRxu1KSO1MPmCLoTJz84ncOCa7a2eBrenoE
aPG4zjvkMwJAH116Vfe3s-xEviy9TWuL4L5kQ9_c841aKUBx_jXUMacWvyCSjP9LYd-CDVtYm5PTNC61KMPYaBQGr2cBoBJV1yP6ylCSe8aOJQHIwo1RZCxX
ES5Xxt8qoLnzpFBl3EDgviw13tFWIyX2ccmGrRXKIUjzf2lkOrTla9dWdDDGrIze89OYzPgvpBOUI684_GC0iAnWJNa5XutRcgHwB_nZGFE5GLp0OKaaSriG
PRyEOcqmyIi6iVJb09llQ_WKG8V1iE-j2pWcARuejttELWcIBKlXOR1CVJY0hv9ONWVZDbH9MAWhtESvG0yaiOWesMJSRaNoE8YacHTmq8gv7cLf8XDPfHAW
V_rYnCSvm3cvbDE_pomP73SzC8gaeYHu1OUiKm27xGKHPH9mZIgSulDpiIGP1B7AgI8LCX3q0Bo40nnb7ODkrv9bRBuj7E8gZbca4hkSkVZot7DDNqG6rmEW
YYGniWT7Uec3WoGZKW998lyRwmOEi8gqPTDZhQ_hSJc7YPIbIjqurDVdjHm-cEoxo__n1WuVZ6K1FRYBGqNgsfb8i9HUSs6MBDFD7DuHQJ4Ei2E7YgGW1J6b
fnm0S6Oko6CKOyuYppa80vvpq88KEeYSuJ1LDJpd816WW9jnmeyLn7384Gr0rYGdEG1i941V3f0jY-Ua7wOhIKSEa3QAvwmV1lXmkd1uLyNpaX-07oSuGbqz
xuSV1nonhWRyiFq8SxWOHUHr3km8W1yF7F6knltm8yRXNOrm0DxQXsFd27MrYnz-E4Uygx7zyNWO21X2NOtxySi1Ms62NOtlZv-QA81WL-D-uCTXEEC7GEnT
3NFWo0-u7u6kXlpGdtxuS5Q50rtjjZ_imOz0LmD-8EI7TpN9MyauumTXEDNLUAg3uBYrW9hXN5VZoVD6WeEjhXiHpdOrdb6Tv5K_lAlzKknXE7uS-x5tjMkI
Q_Ax7-P-1BhQIHFi-oFGrQwQsEg78T3Llfgu7v6knZMnNuVZVWIwsaaJxFiZrjLuXkOazjl-0AdHhiOrqGS_0btjfidk1m9TxQM9xNw0R86kTjD4LK7p9Nv3
YW8hY97qhjwIDBac94hDSbjS4n1CScDS4v18SdUA1XTeVqq6kJj_-SjV_Wa
}

