sprite $image263 [188x137/16z] {
rPa7Skim4WNV3D84yFxNtINbLQdeyFLCSKrrXH-Skg061g9nAg9uLtg42TwHvh4oy7OKZm-yuQqGYmUyu7qOiUDjik-nussohnuxtYLxtPc_J_PYyICcxnBw
6sNVThcyJ_PbPqvaVz7Ghv-zZ20PLzsYHFONdKNNpruzVet99RVezRCVSHHlLvf5VFRNsQBNprujNiYumYowVlOzNe-N2uH-uUoBnscC2yoYIsO_s0mkattZ
0nQxGlRy5YrOQN-VlRBcTc2BUFlJMVIORVdBqxuVVTN7NvtsZSt5zVFbnvhrmzcVFulwtjoN66sLwITaJymYVj7xdERMpLRxHdypWgETxfUgv19c7j7wi0Xl
xV-JVJ-ymSINMO7cmsEKCJp2QpsGu7dNnVefbyK00THzXDTYgxqLpjxh-OykRFyjSicjLn6WXraCgRPcM57EoruiQFRJn9RP83VveYWUmxoWcNK1q4xAlX-_
WzIv-EqlPRDlHKR4y0weebbXPtK_xT65xdA9PIfkQD_-fgss2E-rtaR64AYHsVEpY5-Jlio-vNAZRv6WZERUzNuCDA2IsPEXyz-ov2qNQNBV-ErctpisfFzl
9VkhifSHXnTT_9uBMiC7VVMK8RXNDJONPLUh4rkKNOa-bu4xQkMUelRwnVpe0lN3sLSFdlOfbn0y86C8DffXJzjSZcUlVdpHnPPPFWksRR2MRnkrSYJxBRh3
qwZTSjcZxXZZnrDjoE-p7ozu4AInfE0hn4F-DKqQwEmFF4RNBuxqrl2PaXq_SJyl-UoBls3HQowcCKHxsPkPF_ayt9GDm2pyw3GINtCHxTwWJV50p_ByVNlK
OCXfcNwibpxdLeMeT5TebRjI6fv3Mh3CkRgpzhcCnvmNAz551D0YVGXKiQAUIhrXICxympsfSEQoXDwFz5MmkgieW5gbLK0464l3yzHSaidbxixQvxBCUZlI
PyD6YovbjMvDgW9jXk1fn9T9cj_TDyYb7z1Ot4sn8SCBwchVczIO1S_JvqmcbvqxQvzpoIMjUqGNR1GV8hq0QeiHvXhqek_T-N0wP6psJR3HlAACCITJUcVD
z-vtc5D-38NwQ7w_cCeODMTd5ZqNEfVFxdmuQpE2vcsrB_Vhg13gjapU_BCxRv_B4jOWmslrCDrU_thMmPZp9tS--xaiRXN5hLIFdjDnri4uvnFkNFPpcMQA
7gF6f0x6DcSIva-wRpXZFwHud7SmvYJSMVkmN9ARHfGvuSvcdslttC4uYLmeTtxfCuXL7rGkl3iVJZOyHSab2NFUdGydv_BCseknkV3k4RpzifZWP-gSIPhp
xeOMT3XpcHq_eCGqodd07OXCtZuRSKqdp4btUr7s_3IQywXx_-Mc_JBxpkHotBskVnbvEFlzmSYRy-ww-a9-PPyL3nYNot5tHUQcq7zrEmvz-9rVKkR7tGiY
4m16Fk1CzkGrFUUht1iijsxjjs-hPgSEnidIltKVwAaGmFCEdVtp1-FaWVetxeRcK06El2aaSc4902ZnfNkWD1I1qFTBdacJYXljA_U404sW6GAn4-qdJmNk
Z4_kcW3G1IK500OTpdcvZFt5UkTUDdSJr060p_xKqFTeFBgZRUukQ1b54Y2oFp_qFVjD2m0f7x78wgv1s9yT-fwU3mWWAJ3h_mMhEn3DY71E37tFValsRP-w
OYFJySfD-uBGzuW_M5agGg6gG6O3kaA8xCyE_UTD6veAk_LUWQo0v67xV5teUre-ei3OtBV5xu2r4aGuvuR-S_OLmBPNRuUym2fGSe_xYQ5pMDunh6JYmHs_
3ITF27tFumKpgkxTDOSHzYU7_lEi4gJVtB6vMrQ89PdzYqBdDstRtEtcdlbTE7v-wFoclSdMpLq__kczzzZcsDY5SqBeB8zX346cREvrSvUi7ozE0Fy8vuJG
kLbbcNXmBza1e6mbxR8_9tIU-c3_w5vlcq0o-xvzFvPBu7NqVAG2iOMVAn-xuFlpaWzTy59i_wHLWUmhmCW2V7TUJfe20cfMRGXMydwKojrzPpzfEYZuMMMz
AoG1KGNoxhvdiZXu-5bLKN8pXcI2S3yXTFw2kIbNmlsqqFbPjIbhXsGGxkU4pi-gB00WQOJxMQ7piseKXMGdtVdGJvfLaAoSEn_wMRDA99LoFp_qvn-6DCQT
3_tiMTK8TpRqysUL4UviwEVFAjwzuu-ntxex_XvrmfqC_NnAqEu5bw5pxXsNOZplxhWQOi-vf-22Q3pXNd1HsjwU2FrocvOC_LApYWhzOhEA2Vrgi-eweVCN
J2Bqoyqg8lJBpIeYzClDAYBqgr4D9_8V
}

sprite $image263 [94x69/16z] {
jPQ9RYmx24G16vi2p_z_xblIT-Atb9NRKQUqPZig7GCPkHKRJNugwiWSAZ-IZanamkNvjFXW9pBZQJqsBtPU_6bF2X-PG7xcKVsEp-8RZ_weyDnvJBzDmdv8
lmx29leV4fwFwU-4_PH-2y86rwztXK_6FlBz5jip0KOvJIVwFU7Ci8aumnFzTxS7_UqCUKi_tnx-jpeZmEeZuJVE5IakCYfZ0ZCoGVIttziUNhpdL4UCYPYW
_6ctX2S-6scWVVmUl4Tev_oXNmZdl-xf8gQYBN9OSpVdUlntpzLMsN3fiQvYSwXuefDAP3eTn-BlIRcac8XwKxk-Ls4jljBVZ-omNx_ntlNcAkPlimqrZFmr
Bf_aCSdvi0ZTpzERxFJCRkDqcy_2T_6HqrHab_zdT1IQnU4u8760zryu3EcZs_6JdaMEoM__oZfuAUYrzwEBM6ygeiE5HACekzOhgughMQk9vn3fewcsfixt
i840W5gljRAAyu5Qc14kekvD7IuiOnMObDThlUbK3pxc0T7_vYDuyLm9AcMjJI-kRg6r6SCSdHgVP_QcN-6_EBj7yNyClGhWKZPzunb_9T3ugF3Ycxtf9pwG
YrhnNPn88NIk7rZvl_A6HOfSKZWT7GVzjK9fSIw5qwKVzTGQj3YNmkbM6LTzaDVjUt-eb0tbTAqGFqxdWktz8L8OVVspE_fbvwHdsZn98Ncz6ZxnqEuclXRd
NvW2sBsYy3L4-hi-pCLap8RpyW9iDNdnQyvqr0S_calNeM9P9_xlIzaxelD2kRX5XbM0Bo-HmjdLHNOiLjL26pPCfReQtlgt32w52_zF-WSkfrjeMcz43vN2
XVy_dd_t3-cMugLkGQRdZl2T_RnXyZVTN0RoeFyifLoEiVYR5I4ZrILDY-av5rzpIs5fMBNInXItCWdjbIql_fTIOF9L_8FbwhRCgic4vDP3f9o5d_KNnBN7
j3ubQqzdtH3EO_FQNN4ryI6rymtXN7-j21a-XX0u4Nudrt7h8jC9dGY_cV7hS3PAtr9SRcOVjuLfafH-5RyXd6uN1kd-FU7qk14wkRFVYkSYT79dlwkVqCcT
_Rx-jUaF22VRjUb4-3Fwr-iPuVouFIMSF-zweSbFfS7bJlu4
}

