sprite $image393 [113x101/16z] {
l5Q9agiW40mCCDCzyF-_-oBw8h4KzqXjrx6tlNs1ZnyZ59F77oA1f8Q_eXCZ0H3vJoY3abX1IvyNau_V0V42gV6ZV9caoLjPI8mWo-TyZSg32Z7Y229_hehe
8CfBC4x0yX6-mls9JHR1Hfo2zW6wyUbUMthAmxay4lZzAP1sy-Yjjl9Gdgj3DlwwhM5uEkkJhy4k-5HIJE3lJe5nQhxmLVA2BqU5fLX84EddunlbrUO4BlZ4
5gY8ag363zXPg-C2J68RIap67vq2wM1dTU9Q7-o57FCQvS_7LrlZDLqFCDiEtQ8q-V7uQkxVk0GjIHafHNGoaQcTzDee0c86Sk4OV2tRH4huVbkQTOTkG2vr
6P2sADEtnvTaPkS-J2ADKKBb8ihf-1eaSyQ7z99FsfklA57MqovytKwToWCqZ0qZLPBQE94qdqWOxMpDKyBSpkL9Gc9NsISoHgdiDSwdbGrEZdRgpHZK8LfT
OnfDZcL8SjLFylnKfplNjjI6gJpqoWlSUn63lKVvciUOqKbbpPyWlTyCSpiXMyLwATHfu64YA5tVxDrEgxltcyWv7tg2crXbYSLPM94VehkM7cLVrFpThlmd
96RejKjqxp8Zja_2FaiYYIJSljlbbN3EHrhOpdVc7XziSLZeK6oKf9uVK8UZe7Xrlw4hcLw4bJcgetHvYnXV7XNo4FC5g6yNnPolLoqKTxUu-hhg5P28tU0x
iFhxUnfceAuZGAzf165Bzx8JIkPdABoZQus7isqACYMlI0AtqdLc4hwmHYMTc85z0XolYYkQuMzyFOypdRgQilKeyLvUhJjXkBxu3l-vnVvqmxAhuZHTijLw
9w-rEXAgJtxNHqfwqKeDFO4kM8pqhyWR2St92U7RJztP5rn8wdwHJh2aToIytY2zWyVpnfngRZ7OlzRCH3To68QXc3CHvVp_v-uHk8GpIo_LmiRHkm_YYwIP
f1NAKq259F0prq36-tm_bLajRmH6IoOdW0BP9-C6-F84y2N-vtdsFN8WNf3RxOvIUSGTRUEGWKIUknIfYqnaLfg1l0OaTmMO7KRSUMA2hCL9N2AFHc0caSJn
J7AresnCCu5sN80aVkBckVhoA0ydxW8aKl0CqZL3GzTv0H8fSNELlhpiyIfW9WHEgtJb4KU-0cgYpjKt0-LDWRv8IA2Ea_8CC1ExpHM5yfBfEc1c6AGjZsaQ
O56blLg8Sq2Wa6lOybeoN0qSrfDNwSfZvnbWpycfd3R3A8-uAP1MGglqSUfMqC3REq81cQilxw2yK3W2xu_dwxtj8O0gLs1IdfXZ6hWX-dyP_kkyHP2GLuli
F1tfOmyvldIkEEcYF2rFEto5GAP6eZUFAazqdZZzab5hGQcyhYQMv-MnnA_teYKaWfM3F2TFz-4zegOom4_P31Lvx9aEV2Q9HcKGsUs9EIOEV_4Bs194sbp9
AyjZx0HcPiOtSvLBI1_-8e5yz-Hp9R8gRznMHmS-igL50XULxLloke3WFOoDI0Xa7sdN8elocEPnu7cvutqI9oh5N2-dsIqVxVtFJUzPhcgHrDFiE743_FQM
AcURgvGcvTqd3sPuKI18uu46Uddv532gP95yHgbRfD8AMjvSPLn50W9eMs6_sIT2WyeE8ia2cMR7uJ7Zw1OH90iSvLKV9ZwPwvnOaSSq_NcdGtfvTu_HBQAH
A-HfbT349V9qYsYabAVdc3zgYqYWNa96NbNb_u2ZlEUFGBv5v18oygegPQwb9RHIfLb2rUEt285k2QrMQPRGWbm_fbrr2IrhaN6EnMCfI4-xrVByjFDBQ6cB
c2MqLkL9D4jeVOkO9RJulDFDiVMv_cYE_GO
}

