sprite $image31 [177x132/16z] {
pPa9cZCX24GH4K6z_tN_VSryOrjYadu7cBoXIt2XCp2B55KrVwIggaXcfdl0KhJw6ggIt-YTSb5p75FXDzHLFOIff9V9bkeJxYMTigwvv5Hy1IlyH5kflaQX
R_3oMipq39PjlIRwIJPVv7YTMNqLO_gB-2fM4Xr3p5SnUOYH-fppqKZ5rodq0JPVnkHq5kPK1ZvGD1bnNSlq6SK1zfMJEe3GX5GXPKB1owA9vh3vSxCiq0_m
2_zY_1EQlE2RpP4d9Ox3TOYNjoP2o8OK-NnvZQEB8_xdDV3HpdVB0iKXlYpYKTOBNmlCOJZAyKMIVPbA0A7AM0huHjRR-I6I7QC6CeoH9xuGWIw1mVGHzWqi
Xz8GoN4otw9oe3r4ZCrtqOJlgN0gCDzUi5k39uXu2CjmU6ChFFabTPw-6Zfn5E8AnRWkzMxPtwQaUldFPbiFXIo6DEbcb6LQY-LSviKEKLQFaiPmApC1HehH
JmGPm896cIlG4hckh3l3rd-1ebp0ePFjiiI2RXPINOwo6DuBovMF0JCCY_AybUsq59jjUYflJu7hjL7JNjDceh8vRqj0s7XtB9RF4b60dGmgRBA_yJ1AWRD4
jXtX4jhQiOHEQs9puUkLWKPPIkns91L8s7BqUA8AttzVJpBxJ5ZYBoncbnyCZt9zt0DQ_OwcqqTioxI7L9NVP6P0BBIs2zqL0LhPFIWlB33_998JhiVV8UKd
zIVbOT752fBAyIlKR9Ck4Is8670h0epGYN2a86n-XU3hOIeyBmY-dMYnRYpcaB2x17j3YqIPpHqLTikHUT7w_ejwgkw0yAGWG2jhOxl5YJiWF2a8TEdTHzix
ncJpWB2RRBQoCVhEGP5dCYMjt8eOxxIoDiR0Z-9fzNRawiOJl_NeOum6V3duTgJuZ09VUezlT9zX35tqmjT4sALt6zzfFgKcvA8NloP2vl3uGLz_KY_GAi9k
F9Fw5Mtyf2s-OOW1QKUZB7xD-CtISnnN8BnWb7CslwQFttI_neAlYsmUf8s_jCEFNdYKeG9_m_SHuB0JzWL2SUI8mZKKYBYnSU3yXp5-WiSuVggC-UB6yNEx
xWGuR5n3DoEuRzHOA4H1VSF65Z8M0tq1usY7Y0-zFYRqvySuLRW_18pZIIxml0WPnrzPehuztDxujUtCmqNsae214Ow30TqYrkB4ZamB1P8SYN8sFxBQF0Cj
UR_5fOhgVjPyAurnIBa0hMn_LWZvfCE5enmFxoE9oXZdb1cRm_WaTg8qna7bceBXxMDA8I8V5xJzA0k-rEOa8f9nIMzRKSvsM7SOVQUDqyeycyDpspcPQ5BY
WBCcAW7ToPARb3ZcR17RUO69ybYdjmLfN1OfyAHHF5UwjJuW4lqczJ41a8PaKPJ-8cEBtd3jDdUT1-8lTMpJU_l6ccaF_Cp33FKHflzK_qYVYO8TOXBZUw7q
2D_QkD97PDmN9mACx-PxVsEdpyZz_lcz_yghDCN7pH2we8uxqJDT8ZUAXITQWFs6ussEZZlGc2RShyXA4ENDINOcbFhED0Xja7oyXwwqIVRRwyQLuxf1kBuo
kqe7IDh7It2XKuW_FmkLwIIfjF54JEWyhEq6jXXS_7GIK5iSgSSAxPhf9IHOEYuR9wjjMdijcTv4Bkg0jfjAflV3MLJzStDtLyrdJBy2
}

sprite $image31 [89x66/16z] {
hPW9Zkmm24IzWp6v_tN_ToyQeLHNhq_xoAem3uAZJa_8jVKXelEEoXYzbPmuFBFlG8pgQ3L_4ZfqJejPFJx6vfHUtqfjCi_qbF80fOzNitUjPqPEco98Ioyl
nCe4IFaxeF10JPIci54j7EgJHFDg8pqsFwY6_zONnwFgs8W8T_Uwj7CLdSY5v8wzfGZK83ania0TuGnMfZsptAwuAIGtk22ICK8ynA5WhMOssgICZAQDqgwd
pYFMPg3JUHZv_9po9pXgpGEeXdAb8E6oRU7tjmXM7V-kzS5KrnGB7YLKTbATnqD7PSIIIv1BNDhkjHhfQjXXfPEPZGLUWe4ShBzBa4i6AmPhUx90HEFpIHNx
pjEDY80gO7EbqWkxR7AYODKblKx-Jw9qCBs8CiOG4MrN5K4SsIAX6QmTjXtZKUDRH0fjtQrveH8wdiRMM9Kunpc-pcn5smAB0hwaS-UW1OBbcazG1LoEU84y
ahlSW6gq7F7pjE4hszmTt1XuEUBQjABxRxdxjXpfO3cIJx4XfmJpZRruvSN-K_mAkwGh_z33BB-o-6S5fWZBvSaZKQgIN9hCFzDpfxatbk7emfOZz-itZ0p5
wnhiB--PQ6saSKI3-eOMhPMFMYptXWrWcgjktC8DARo9KJMN6sXfUcGPKLt6Qx5kALK_WRErvevJhx61lRYcWsYOhIGrihQvuW4I3aANGrhQT0_4y6M68cDc
PBccA-hBAIlYbEMMqur9apbOy8tyk-JbAomkFVn7M4a1yPzmpDCsREi76doaCrc_ZJsi9aYpxvB97TdjyrW9TdyHlK0iekbwSnBSUeXb5_jBsUkQEcfwdT9r
-N4yAtLDaah2XLI-J4VDt_o6F7JQ2ebJfTUIEFy
}

