sprite $image100 [181x219/16z] {
r9W7Zkim34GjqqN5zp_lTvGom0gpIqTYFZCesmZu2Vl4CJ9vo7QaC7rNbdASsRy9UKx78-lNCCS3oU8Q5JBNb5oEcXY-GUQQVEQ9lVb63W-PItxayUFYc7d_
WGpiD3j5NW-OWRpKzeWi1SWDji_r5s9ZHkj84PzhZgKSDOwQVO7C9ExMdoG5CXmv5iSoS-mapcKcwoyuwMp4jTepEbiJ5yskaDdR-jlecjDZxnuw6t6u_e92
PYLs_dyle1sEUEXiVT8QueUW9Oz1pbkuNsO7dQtDFZ-hoLbdyqIfrLIbTjRPNERwFol57bhIG9cdjHG2xLVcN0YqPvaBWVOiipaqNa27oMmFlHl8R0gD3us6
oMmFBQDaNY2pCNGmaDaQUXifypIN3q0lGsMMJq1B7hkPLtle40VB_1kqk98PczaUUYa6cvb0bp7GSp9upJ267Ysp0RIrp7z29q1xaValw1W4qFQThPUPG-UJ
jXDwDv6PG-TwDkXX_GAgbvb3x_KAzLn4oIOoS-XuEzkQExP7Y2OoS-YytCwMUrRUPY8pXyuusxlGYutC73hYR6z2IpAHcKCddErjw6GlCw2VCjV1JkYOR6Hk
eRVRsVPI-g7J-S1a9pEWGtYkkNxeV3l-PYOpeCy8a3lrk8kscyYCpeRC73heeHzNMgA9pEXioCoWHVJGP_Rw-6GXCpfR0IrpWpWpw8TpOJEG6PsjWHRvwOW4
3ltSeGOoOr013Mmumw6VQgUXCcDG2_tJ4P70eV6CKJAZi_NGBRQ8S6YYTg_C6DH3mn7SJWuDjRjbBcHG2GriESEWaSZLriiSqTc_9XDeE5A_ez387Qr3vgmS
pBCGQ60t2uL0bmorYSoApbRDCMWu8ZKAw58IrBugyzPsDk_soA5RLGWqKHioQpjRFQU45WRDrTRBBETWoAgvskrgw5a33RNtQpAVe_fkrqEB2XfgAsI6fDiw
pPfktyYUvb50mxsBCly57Q7QDUZGGlDCKxpGsGqqcRiEBQEX8IcW-HohyN_4smbkOpaCX66JRzVzxpkBWSB4oGzHgWZJwjqGW2y9MtmkAjb7vrAqGYD2ypv6
lwAlDj3L0oYXkRSpkcQdWIvwDg9v7wFh6eabQ0YD00tx45spFJG_W5ReEzG02tHL8_5hTDiWD09qsw1H8hh-PFjeBb96gsSV1NgGdRDe7FGGclQLwC4QcK9p
psOqx2lGu-mqq10Q0Hfwje7c6eaPD8T6Y8PzG-WjHzW66denexLl1hrjMTT8ZAEvPpCQzWbj193VLzxZQ0wD40q38KQt0zwDPnUThzSvZEPUp6ZOX-YJ8mIn
ENQQG7FFPlGBzW7w5k0RMZOE-ARGBQ5dmu9zGjE-8e24A7KOFHuQQH-XQH-WHUIQ6KVZeAVexO2cVNK0gS_y9Fer5nfLQEtheoMLVnwT4w5H1mtF04O0EOQE
snW80Hhs8Phmq-ZR60WnMlkcqTjIDFTsHckVWyw5QExjZDO-2xqjHH_gsHLQ-qnq6cX_8CJxZ03IHFi3eJ92gD6RZUQUtIPwkuyE5ysNEE9encKF8u3qq5oa
4NdLlVqgq6NQcoQQUtP4nFPKlNr_2dJ9Tj4gqg-TxOdtsbk_j-zPeCiQIHUjGK_-G4US3GT2GiUv882qq1hq43home6GqDaM192ZQEZPZ8xO7-ZjGiTHeelZ
BmsqYfJGMaVxsFU13dqOMiq88EVG2etwwCX3-twYzq_olW4QQiJ9FQ1dCrhhlO_GSNy-H06wO0-ZeHTtq2fjH6VZt6CyxHr7wnB725gbZUWuFzyu0BhuPCSW
MZrx1Xrv8JhRkvWfzyYXOoJ7q10Q0HhO3w3ZK2W8JtbHesEiFE3ugj7GsNVrpUZa7W5e8u1KBwxHHMaB7Vgw4NfBG7lF7Zuwylg1pdxkaO3Mw-lGTtJNzdn7
DqP3D0Clha4VKQszVQ3ZBD0I5W6aXrQFw8hrqDeoGgjLw2sXqDUWTUSwwfN7rmzjhz22waXPXrPlVs9wFINwRTMB2z7g4GPwOpImzUSQjB9s2ntNV-WJq5eP
a4_Rw1RgxHuwMmSDU0_DeP6DZcCAlNbe7WZvw6XJwCr3yq38H-zpwF3GEEZnqN5FeJSFpGCX7vrpwBJGF13oqN5EeJSFpGCX7vtj3g57BiWQQ0gDVBJU3WWz
mevfj0P2Qz4fz529JA6BWL1B5vsgwR5xlJ63hYvxjDDbNqAFnUeJwAmlUxJ3GwVGO-mSHezTzdWsItq9FLOZesWgPXwyULKDQ62x-NJz7LjEZHn2ZzL8h4Fh
S6dxlBe9FSOsqENjxoTdqTivbVI6WQulrLopx9HnZ6sY-Gs1V_ozfjHfeUiROcrVWkQ-7YQwllrzvogrVNeuDyJENADsE-BTEUQCpcwWdLi8vWsnPr-WNdT9
HOEUQbrBq2BxQFLiU1dFbj-gxOI9YZa1ZL-E_TTeaNsqtX3aSADyDbCjTBmSD8LuZEQpvKfVBRAFriqlG7VFbdOQQ2qJJJqxgqRvp7RsnMYu8GReuhiyd_n_
qTIp6TqB6_Omr3wQGZn6GzZmfz3KixCO403Q8FleX12Fq3fRBFHhBPh_NsKn82ZG9jd8FHWDPmkZVVAouISE20gqJrwFrgrI2_rtSNUHs50Kmr3KOVB-jrjM
ANHTaFwqa3Dmh1TKHT3QBMEqo7wqCllkrMj0zg3frpDrDo0xqCfiGku6P0DQxpvbvZut-z5wWG2IUtjEzgELsOoyNzGPsOnMPYEosbG16LrhZZv_GfgikS_5
ZNzahXL7dsKs9kj9Sv4JQ3qXpOTPQ97DQ3xCf_FMQv7TQ9xPe5_SX1uEywugZ5PcO_9XKN7qWMUsEeopQ3tE7gsvD5fF6k4rLnL7RnQpp5vM7ltoYwDXpgD_
DipvyPXajWVTu8x8p2-7FnEwVuisDuSlTEy1Q33CxavvWCQPxQkr1cXm0BMtuGEqxm3AMxS0sfRPlAol0TgMsRmMaQ5vPfiQq0cQhpd_-XDwcjdvzIVq-PD6
dejNuPsXyJ37rv_GwM7czOvzXauECo_I57fu0CslFw5vPkVNdz2J9utow-y5FJo0vjVVQNKm743_l2TzlkRowsz-0Csll-W1zESFR5oP_GW
}

sprite $image100 [91x110/16z] {
rTg9ikCe30LGIUn8lF__tAc4Toi4mzXPPcdrlft2jsI1EwQFArXc-YVAbTQQnU_3ablJgjRKVrcErgoMKggsLkIBiDTcMakjjPHgpH9_CUGEL-0QlW5pliEb
LjGzbUg-5N8TgqUUvREGAqAkCsuVDQAC8S_u9ut8gI6B7Tv-tch4e82tTCtvv_LGN4KMUxXu2krLMj1mMxZK6bcolKXpicPdS6AEQWhwUiXdMMH7lfegw6-6
x8gfWlvco9pDz3KwNWgP0k3BjByOCcVJbsWfLqEMDD3f5EPB8PDaC-MNw7YzarK5jDefxUkba4Fj96ZJAA0_3Lbrf2qB9z1ltzMH69qCsegZeFOtTD3h8G-q
QUYNiQMv_hJh8QCu6sx8FUr-Skmhkn8oIe8GBcDFjqoIW2-o20ZvKLQvJxs1vXLjjsNbMijPo80HyXFj13W_Q5NDGhvWuRkG0IVcPAOpxPnqKUH1rwgQc7la
9o5RGSW76hYuWRxZSOXy7x8dFry6w7in4NiPQBrzgxT5zkNkGeuaPVwz3BgN43l70ztnB1HwvAkGBVUGftm4z5ZFz13v8cJSrOjyLZGFDF0QI3OXarituOfs
CzqZTxGAcKkKvtpGX4jQHXgu9PwpoC9HBOejcX0qoREzeZNnb4KF6VJSXA29fsMVqGXKGKzD2Fg8yuu6alhe18qcf6mwqtCg6teE53IQS7jOu0VEAteE57J_
FLTNXmKvf29-GIDa10hw7dAU3Wk6vWCk3hJPWHwwTgHTOUGZe2txHr_pI0l9WbxVrP7mUtSQcGNGmAN3jAGHydfh0Oqc18rsPkU4QKqJIPxXXBdoeE-JK0yp
H0J9hEZ3wCppriAf8RFb3DdHVBwrI0pt9jGDBJjw2dcnjJ0osz2EJ-XL4-8GYNn0oxJi4nfD69FDan05UXvyZhSqGfPgQfvyiQScj3HDlkF2DpH6fvDm4nmp
nsf34rhqCptZigFDCbCqxq6JfA49BLAnOOQi9lQQHiZcGDzmxpbKmrtl-q-A1ptZikxhtwvzefdxRtQQELblUT37L1PqGjS-Q5HK0otQPsod7S_hvWLDFT0Z
ZSWxpLu8C-GuhuNNaw_3eAtJA5Uiq-Id6IAWJ-v6qAQHfmhL8jr-D1rfYFs7Kpgqp2mJJHBwRsKRQE3i75sWlNCKrFDSz9iDLZtDQpcbJUNURuutHSbKMtbX
NWEEt9jmIxFKDIqxUjvQzZG50trvNbjrlRT0xwhyqZBP6thOlqzf4Iilp6lxFKIY0krf2gtJCxwawV1ecDtUTg2lpEl3_gqjqvQc37h2JmyBE2sKi5tsA_DQ
KKDxcvLTAlB2l7wICsFJqYJhN81Ey_ha75BGthW0EhCnhyzcIE3dnruhGQxGSZ93B365m_FqwRB5EwRJ6P9SjEF94f5lQ1QYFGsaUT3ZywBLo5iRTJP33AkU
JfQBHhn80m7TDHaURopHMpGv80OQpuieY-Tvx6S8w76_sT5qbUQEW3Oy3-reekkqZlJq30cQ9lWTklVAL0qqqRkq5-PyWAsPX_mUZQbtX1FJAKp4QngRUZt2
hGWHu7TeqrN8ziedhdpnFosGHIJwYBOYov1RPlgChduJiYFwZ2QIOoU_yIO1wv5UXypqActjveqqhqAMDzz8q5f7-W1Nz_xBAgPreZy9UVwSMEkA_lmbaw3D
EWvwkAi_B4uzSj08sTCNIahhE6XhDeNyuKiceAsr3q9UDw8bnbtzrUBSVghNrjJ_CUzweH7VQRY_
}

