sprite $image414 [147x80/16z] {
nPe7TiCu34HH2M1o__lk6a_oLXVHIFBJY_J6wAH85s7rbLbDnd8Jfjz4F0itgZc-3TVVagK1eFv3wmhx1LKIG3q2G2sbdyKAzHG0QJ-g2FMQ7nMbgBS0KcWM
LlE8JlBAx2JlR4hKcm2Bvb3Fmd-fZ8Lwdp53iIS0r8CalmBAtSrCHPYsuLL0ZO63Bl2cF93XmzegbmbTOW7rhRIiAwKqK7EC5FX0_H00qdcWBey2r19w3YVg
Pq4j7ZKIW05HFXT9hMT2L2ezfAw0K2QMLQWF0HP_BWb0dW4O4uQIJoKXl8g8f0CX9oBAFfE4PE9OHEHv-uGQ46KVXNSxpRxyzZbLgd8Wpk7qFpWkl2HUsGDT
zkgDBO1li9FKk_oL8q8dMfzgqeyA4ygLcNlyOO-yITHF9HNlJ_hdZ85esmBuiauz0BKF5lsNXUltM5z0VqDLReLXr_7LEqhxRNL4hU0Ua_T1x2_IJb1A1-9w
t070Q8JxHKr8ap-nTQPm8Zqn6KsqjYQKBWhIQNVxre7Q0JarxCBetbsalrrhKvJGW9qQPyslqtSMHgG9ZBKwScoCqK1I8yltLuImkUKbZj3arM75rjyN9ffl
8rivivWiz1Ziqle-m92alPn1PTzHRceqGqX44nXmN2CRuGc4zgKzuGT2YCYlU0yolc41j0oha7NEh_n-GK3HSzXtH9NpuVZMTqC26zLxSAy9PIHnNw29l5_h
eFGQzkkYW2oW_BY-l6y2uC8ay1oBowfGIBx7Owi9jvmmqe5uRcnITWord7Gz2WjUHDB6KvnBtbl7ZXltzMvgAu4NRhi4sye2tXO688pxmaYyRdn7Vcu-WdjJ
5r9PspAe7eBrwIRMiJ6t1OkQlpqX04RQhMQ1dq_2wAgs2zVxC95qz_9WMgbUg2UYQ1F3fLxAsHcUM2zx35A_NrAlOphnVF7hyGTOtosfW7ECahwqTIrCFmvI
NEmniLpkJs7vMAy_C-m5zXR6GDrBE99QKWGmgMcXhkBTXoEitPTAfFbOaz1LP6FeJAKJy_E5uSBUphoPpXOZvdAq5rGKndfUeYu3L6QTrh9kR18RiyfCX1y0
vphch0ewDXgG56g7K2A_9nK_ZW2Xot1isYaImE9NuuhJ1hxhlCesWGuFTVTYl05INrwCeZtqnN81UEIzroQc5-mi5m1KNjFw5yYP4o5r0DmFM2qCRLrk7uqx
X6MSfnHsDS5e0XOHLH7cZUQpuRTz71WmqYnQ67XMC0jVB618fc_74XXGD8iNC71cRHIs171X_FmHT1M0WKEPax2jmfC3jKg_WjZAAg0vlwbZD-htO3LVaPbL
cV6_X_V-
}

