sprite $image134 [159x219/16z] {
pDZjkkeg30JWqrfRCXdl_tRFLbST1T6WOftzkVwz3o4X-byWutu__FUh6QPvMURfHtMxUJbbtlqWRfoNI-RXr-gwlzA1FrRWwGfdF1pcNxjqQv8V_YNzqAMx
hUlX63kfVsB8pEcchgVWt2hpj3rm0fBgUWxN8zr-oEm0s3-9KpfJlUTnuvc2KoWS5cNxAMW0eC9wkjM1snPumJ6NkguiTSksGtfMSLLNJS6jX_GadbjMryDb
I8_d8JCCmpYEktF6SHowNymHuW59E4t1uJXevZdP_QHbtazZ9-XWrpnOqeW-XnToieT9ytut3jrQbpZ5DAAB2sbFapxzs2pYhH6ElYZ917oSUHe_shhYrQUW
fRCnbZJlXi-rxj6IysW5Ji18bcduLEkATsyA9adb2mdVFiDLX8oNvB6qA22i8UdDjSBkynmhobBspi7QagRtMvSuniNxMxLIAjuvjzQartVl-Ph7Is_W5DEb
qrRevmbdJNaDE2vs5ldf7sPZnk-zSpGDcQx0OJOp75FZUU2TYmCRPrwobKUSUIUbUFGxxrphb57Ihg6koUm-JrEGVymSfrXRbkYOcUqlQbamupcPlNDORkE4
jMMA7vruo7Z8UBMF8krJq9RX-QqpHJedUJrcm3ylxjULhqr1smKAgmHupCzEtQ8f-A4M7fB5U2vUkUqVtfc2on2uTZcFAqUTGQwyCzbKrwALMu2fvjkPFUMn
ndio1LjyupETKl3qCr7VzikjC5ayOqWdeAyOECJpbUUFj_saA_Zo-OrM3U1qc8dd5A_7jY-VUhOUE5JeZ8UCLzGrBShB_R7Oy-2cKzGRn2LvOPEz-CujDxgz
lS4hrsbJNLzzv_P5MuHv_fY7VDlNFCHBxrkoKCIJ3hvEwdmAMksTYzt1L3oq0PzuReRmjd-PDmtlt5up9Hpj0tRXuIwF3blUslP77LwJZyGrDkDvjkqBT_2c
AJFhy9g0RbRmrfL1wxI_lUsFEhp6rBTztbcdxtz1pSZn3VPwS8ddF7vYsn-qlNVbKRYMAJZfENifqGyZUB3j9wjcQQzjVL-z6T8P3vQ4Yq_1OUpBAxTzj6px
k-aZlFewBHwGDAAbU-ZRpsOV07g81tXbspUlNBx5mWbj-nINADPftj_sdHLUIlO9dzCjjEqBfu0ah5_ARPytF4AyygC8ALwtL7d8UDcsxpp5kYV-OGImMnpT
kgU-xNjbsmVvZ8UEF5pplDZsdPVW2pm1MMxx9OzypeDROzxVzhtasLTuceAmK-G27_2g26UdAIWUSjvwFnNKUR1EgM_xSLx7aLDVf-DNZ-G6lFZL8_5DdePq
XDVnGQclq-6hvpm66_12Lqzd-prUl3EWm-qDz9M7U6U8tpNgZ6F2Ly_bx-vpmgo91ogmxa0LEdRro2_ub2eFzT8gt-KzkrVIRRhjEwepPGCVrWXNrsruVhfq
5TssFf8Uq6tWqxPVrstdqxOVrocmZUFap_gasxZ0uN7tGmVefSv_vW31Ci2lt41dd4V7XaUdm9tR0r4rE3RlOJWhWTESrJYsm2dckdtzWUrF6Edct0W8vyCO
rh-QXVrnXFdwTr3OtwQuuVoFCHB75stKiS70M1nud-QCHAVcUb5YnBwq0eMOJ_5c8-2CfYYfwVer8l6K1VSsMNbYRhA-mdH77g-emZhKVjm-kFCLqF_jtGTw
upWGHE46GQIgllzrToSuMyIm1I787zy9obR4hxJEFjua8AoxJhdCFhmiMNCVQWJ4LTUzx8FEgpvX_ZwS8I3gd8Xp18Gf0t6UWA2Zu-rrF3W-Si8u2m5Xu40S
4b05mKSDX9s0XWqacWW80yOr4H2edK8R0Q5qNCZAE3C1WPss5MWZ0Jrw8j50G5N81Taw3Pq9231Ch1oEeVq82633CWi1gO60Z6TitZofOpm1uMyayRSMdNfP
LVHlDWAw6z8mYe3iJ0LE8202E450EfM0b2Gl0bebB4r0U582AlpP17GH42y2kWYemxMku28WSroPW7Wt0HME6tT0G5o2W7Ya65YRWCgF821m1W7fynCG6dob
Ccrj0a9d0kBg1FHYG1C8oEWhkD4J4f0E8o2ObeqX8FjxbTOa85u4DA6BW2u2cXKR2UWY80F2Z7SCFXC1OIq2qiynBqr09HwUZbSWeEIF2QZC9w3TSMK2SfBr
PaiGK17P3GGqMbcYYEEw1BI9I3edDHC8A8k8kC44HE3avt6z_2vfDPP915JaJuwZ2CZ61Lx-5ZeJ48ax22ZBQxYBW5vMyem0sPc5JbxR35UTamRKx2oxl1UM
8w0a7qjsNUbAG93F5RNNxrr0TF8vzrW3QXCWzIALVRFpyhsDAwyJSLXvdOWhEZzwEIpfxB19fQ1poqwgUUZ4WlmhbwTViFLswfIIdCib7H-yd6uhEZO6CRL3
1vQS67E1myPjSazZ1kPDxYr0-yQqIKi-znmNdBJc8lfioruUaq_K1sVuRSkcXVEtlRJ5ekqXxquwvNn2qzKjRD8x7pFjov1s9wDoFgIpM88Szqqcv3OVOieW
Rt9CJc5l_7tu_m4
}

sprite $image134 [80x110/16z] {
hDM5ikim40FG6xAzalp-_tDVDjc20sLTQ8VEo9h0tpRTDFL_lykGSavZzoEjToqLZJ_HkicrZFel_NK_E7IoMJDL_IjpqUdhGq-qMPl3adFAwTjJ3uHpilIR
6Nk0jJAdsun_dU_QTNq__tlNwspnhCICrOOffsBNb9ocSUXV1WjGAu1cnb8C5e5dPgVXfRA9a034Z3cbcNFIsZYQNxYDfl0kCxgsVC1syPxFxgFXthFYd6ic
1R8ZqyEI4o02z1a9eAGvPSOhB9TZCWzdMfy1SFKa-6V96NMEN3uL3pjs2R35ei9R_fo3Nv8nupwmT31TGLmFTnuNZtuznep7GUbtovbjFQwURBRM6GKhvRZY
s71fuGAK2FBcuJAZqwSpfZtdGNHpQlbIYPZH3xuCcP-0mKL0kBhrNFCTI_Phw1oCxTeumTQBi-RiAda4hXlsPeyymHCpnjsdIZjAxrx1CIZHfNLCkaTuHVCj
LMPtVzdCt7Z4nOpEChprqmelzqlUpuWnwfrcyNJn1D0rYqSuiIlOsyF08yQVRY-4anc72Izu0eJmueMGOiRsQiIKdtjSdF2y5Aupcizu3vPYJ-AUeujBtByG
a1UDiBS2Hz5wdBbusahsTc96jzeN0YJHtazuY1T2p0Xfw-5baEBoSV4kdEu9y8sA5XxbrB6d3uPilKQWy8d7nUHkFf_rtOBXCRoc4Ak4jq6TUL1LrLjS-qBm
REgfVdezObVFkS_0omk1pMalmKSWNMl7MrC_Q-ZQdgi1VfoMkwhuYcEjWLrP_g8SgKZzk2AYN7Zr9X8VQFU2G5PTKoMyhmKGzH3yzTIlbmGKMiGne4gj-1A9
fbhKGwqoF_6U91vRgXjDArLfSUAM3FH_Q-QXv3WCmr1FraqWyV-VUoLQpCbQf4d7xIKl2cVu1ZO1T5CR-dDNp6yX00BsJFCmEfGc8bcv7T1X3TpYAb3V3fLm
8GPJ0pXG4fHmeYE7YSm6Hm5B90SFXrQcUWeDpwUqH2lJfeduZAZfb61wlv1HYMyYALhR9_5qMXGX-OgL-cTUV0NcJs4Xmi-7VbTXVNy8-Se82uXmyn5n7sdJ
6YQIWQJf2re5r6hb0DTd8fW9qBUdGfsiV8EhgIH0RwpKkNHEgnZXWirNL-nBA8jJ7iA03HmksTfWJbV2JUkbFn5bWqXEwAhFGzzw6Q39TNqUme2msEYgznL3
H7wcAnrElkhraWRf3ICQVHwYYBBBGvJNrLq6IBhmeXnWIgDj-eqWWdrJb5sKBfeAeTHgauUIjZNeBZVUpKDmuK1o4QVXFcekg_duF0zvuqpa8LxgLO2HQlvl
7WhbeMcSVZHwcSr3475CCEBmuZ3cN1x2eMEEvI7cDGyTNqqNFXCMV-egkIuOp4CA4PSyX6LPQS8BujLy163oqBOi2-XUX8oLf0j4FW_5_NvskWiuj08mWSZc
eRggsMmU4lFzG4JTm3_eEow1mWGYyuXpKPryuPRk1rSioxywvlFGUTttJEOX7lq-2fp0XTdi7iDvYAVTEzuAEKB3ryFzPI7vAMsrA17Fp_9GwMXsx_Xc7cAO
pQLjv5wIh_AGNQm-FkMwbz18zBAASgotaNt_kXztaQW2vTpNsxEjz6y
}

