sprite $image234 [236x172/16z] {
vDQ5bKD134DHiwt-2rw6CADoA_WmxsZa3W9jyX9iyA64dpP-X90B_1iNOevbhKBA6cjI66bXe-0ETTcOKF713gLyExDT28d40Pmxr6LjR3l3cwqMZXBSntVP
ED_ERDVAjpFRbJoPmXc285J2R6rmjbQ-dTak2OulJRQEIsfx_WiXmRMnS0NnJA5ELqIuVS8f_1bsfZDCPH53jjfhh-agwmYoVQVMMfHTnM7O3GbEYFt_lxkF
3kU4gGAetd6xrJnsxniH2ycQh4zFTZfrtonRz9csNXt1zyP6z1cPAcl9HKJQjyV699TlFgzrimEGmFTiU-NYOrbgjnsgsX_uNhVDxOpf8dqdoV7ZqPOF-Wmo
JLKVF0cMNoBRzMImoZRXsUeZF9KNvVd_sFRAoGT3debMEMQdLzFI6Tly6P_9vqnhMTp-sZ84ia_4nYHpyQncDeZAB2GwlhUvVJ0sbhdXBVt0j9NapKt8etpA
VtARKnKptNRKFCjEkOZuR2K94HkZV0QfZaE5HqrbPAVNndSP__T-sSf9ObjsfZXPfHsoa-ehxM5gflcso99GeUA_KWPLcH3LtXqvGSpKR4k4RCEBXtgWghD_
joWTdb1_HH_lJytgssMBFfScLDE1AHAjjR92tNucfPjPWVST6XlBUN9PWEfkG0Tn_cOdpcVgyGztivvl1taDA1vmWdLG1GE2HkOg468asQ5cBTrUD2bX1NSQ
Pu1KcscVQ-c-5iswCpsWgvaSv1IrxIMv_D9dm_VQJSyoEk4pfXkYcod4HaQsVg7YiMuTXheR_DoED7t8YhC_PxlbGFyvVu7ZM76efrwxh9kQ6UCpY25RY3M0
xFMPMtTem2lFg9QVvgdV-Gm0P1iI6_63XoEi-3Cum0y3qduTy52eRjbAyliCOfpNpoIEESIi0Q42Jq3OXALcsqB8rkapY0gYaQkXraxv30S-Dl8-Gt5jy28x
C56zUVLfW_6z6sHRxsMRF3w34E2QWUlli-X6-mpFrh7jEM_MITunpZNl61Ewe_RBX5EC7b-CZRni_JVhr9ujnA1uW9-PzcOTcBBWOcF-ppSUkkxey3FZMNO0
5O50w81ZsmEXnWA5oXzg6_hmRtlmQkA0WP16WNI3iXLMjad2cVfzHa2NZcqlQdpvug6Hrs309RonCGUCBrSy59XCGBxvg7GkDaRTh6DzHXAC7k6HCfFjlHXp
mCqwkdYe2ymLjx8iUBJSjlSndyamcNI3DBDy8VAGzi_uJ7hoWLSYtkK0j3ClKrEDP8l5mpoRIt-byUKsOPnpI78XFeF5mz4hoiHj5w97u3VXhlR3LVLjFeCL
mtm3q2qHNCc4elO0X7G_YDSD5GDi0D0_8CgBc_3XJbaCsm8-S_OGsiz-iK-fDYCsOM2wSmrWonOFOto95GN-EcOJLaEkVh81nGFa2503kGch6N0bsBe2uUPY
YfKsVdngedncnjNFrbzmap4OrYDo4-vgSwv-jlw2cn8gge7t6OAhdsnp5DnCHuJhqOvwwpF85Td65mzSzuVh4IGKWYbmzR8bNhTBgA06tcS8hiWstcTQFVKP
_FYidCyGNFra_GLtsLTry1bOZsYVeRZwsKvp3J_t1PPthy-O4LoTRF5gwUeng2JWCr33mL4ZrBnS-MsldvNIV4F8-ypDAa5nzHyjbjAEm13WCyZLoPOifVd0
W3xpMl70SFMo9KjfeY6CyXdawYVhAQKnCF0-un0gS7MpTPNICYS8wv6ZUF1oHNJ7NGPYVYcVoOJFUBdwsTxUNDTXJspnyCSZL8GwoVgl80rxEYyU-88xYYko
vQyWuLK7X3YB1vvh15kyou2_750yEBXwOoDnSnr-6Ju-VF4GpzKV6r7LKd8Eync4-j3zLv3mUVlcA1xYkFfZuvLiLVUdzXVSyLnv_w6tFRvuSACfWVXjZoyU
_D0_fIk1u6sFBnxya8SXA86mRI_4Pn3jTxAKGDIsnnSFVcpvk34g8ZusEee73xGyhL8Ws_Xjpr4y-8GA40L4RtjyyU37V8DCu3_Xsrwyp-JpHbO1aR6nHliC
5BFXiiLr3j0YnhV-kG7uJzos5na8Tqk_mVAcs1ZkCmpU6nlJzWQV-RHijnpfCmpU6njBH23icUC8iJ5MjX4-GmZr4x8D46hzknWxk88GYa8Osd_NBlzM5MzU
1JCg9v0t_vIilJbd7WJLnXPmvbbi__wGFMSyV_RYON1WxKt4m-10ROmuOzUU3wgFRSyPilQKUEXZQyN3ELyR9MVws7BnSCxNnheGshKdETF7Leg7lZO2yJ2D
xIV-UCw4Qy-9Xvu_ZZDzRNISwMkZuqo_zXnd-jWwplIrqOc7FhQECtrjt8e77zl1VmNYmSVMSQPVUquyzFnnWhjVUwuGzclF1RLVUwmGzh5rdEdNdXCFVMrq
dEdNdXCFVMmTP_hQw3ZJrqR7cNxjEV7Ghpqd7lhOEl7GrqOd7dh-ECxqQyznfbzxZZDzRNJYeO-juqo_zbnG-xNdEDFNnYQe5m
}

sprite $image234 [118x86/16z] {
lPS9ijim34CZMHiXvVxNxRTiZ7uuuJXiMcEsxCyc28fv_AssLiFZPeKYFyhtGhDWfwAb-vXRWvn2ZVSmOuKiGKgunL12oVt_zYRDFEpTRZ6Kki7UK1Jp1dkP
5fkRRYYkozxlqm80SeEzeP0dqcejELUpp3dyoxG0KdEAuNm9TfdJFpCKKhOTI6MuxVKRMXDhlUNQZbBR0hvCKPQT6GzYgkXzZFuZc_hza4mDmhPChOyEGDhU
JysehS2mrrdSTFeuEaHQEVifuVqDXWeZHQwpPNvpmzWVbxYg06iaRWtg5VVuQ_DhTJ9pMFtKZFaG63ItlRnWGeDq4PHm5k3e9xmDQUxOGnEom9iY6dgMDw3J
tL3xEFkfwO5q-e0nhpHwxLrNYbaUsQ7RSIVxmvQtCAU4BcwRFaZlnMalqtAexK_BNjvvfstiW4rr4sjOUfTJ0qdRcpxV_jAix-xfRAdEkt_4NDlh3oOCMS8u
l2cslVQoiDSbCps9qDs-CV2xU566wgu-gcsllIomm1NdWyO7UK0PMaSNqUezQtjpk5uMK2UC1MPt1UYqq50bdFPcQqWoBKgr7TEWrLPV7t00S6ffuTLUrNdM
QZs5_YFzWEC1Xw7jFRC8B7jBC5Rh2wcquDqyvltHtlJRtcMeHqpBB42cRwfNjmRQksbxjwFi3Z4jsqnBZQj-shYqqXiE4odK20TKZx_jvVVrlsYXMfpcoX8R
n6teL7g5ldQe2lN2O3mTM4XUuu_PM8E9qMOMhL3tyHozVyh5c_5tX8e2uilkgaDDvfZKJxXevlZJHylPR2hKBEvpa7h9XPZZJn-ZR3RL0xlG9vDKOcr3Lrek
_bSHj4AjYgkeYckaHGdIe7AA7RH2JO5CHRMunt2XeRgi8GjpocRZPMf35TNchfGNWL7M6CaCzSfGKYsilHaOvoMRZQ5MXffKcwiNFpt-64kcnJJKff9hRmPw
_D557MeQQb9jh5xyJe7tgjEIZRGOL9-zF3bNMd9uE_uSLCLLcm6vROlX8YqMrS7Lcq7VluvkfyNG4mRNjBUfnK-mqg8CDQ4ZrAwu_XGPQR6OpxRRqeXrsdkK
6TL8YyK45n_nsYlyTsmi2pQpvz-pp6tlaI9ZMR2WCtnBeHBXizTO5emRbVXGYkAqTo2vql8yFg-LuBOt9enFqr8UXeetHSEJ5aj-UrrfiRLvxFtGqBuCDPKT
Gz9jgAtWiDUV5bknVMulkilGx-szBcus0L_OUv4MZZ-Fhiv0Xw4ENPw1ZhJOSW_9yNIanQVSXuDgZZ-_lGwgCot-595gBmks_FRQL2uBVZdEG58zQV6doA1w
q-AtrwRwq-8VagH-dHRN6KYgFotV34bIFMdvtbvIVMdvUaYIohJSeL19DLRh_sdlU38jjob9vx9mguhyVLh-
}

