sprite $image159 [248x185/16z] {
vDS7caKX24DXGRWXi__zJk-zuul_6ZXVTFGmb8_z92yTDlOInHivDkBWlPfZ4tRm2VW-9_vWayndyJKnf1duWdxcbdm7N3VizwN9RjVxAfItQwDZ3txQORhR
zRvK3rjvqopv3N31xTBFtC7l2wdjqiyy-MDmYUtIpzp1Nr8Xi5tQcGT_6UmKmWP_NmfibsBcoJy35zWkfKrpyA-bGDWQcnR5_m4N2BiXyuOJrzeqI_wxcakU
kFwnEzWbRQsmzJCFDYjV96pzp1rSGwxnxvBUj2Yk1DvsulgPsy4LHKFO-fdFuhhWpM5hFLqjkRves2x5p2TuAWuJsAx_UBfQpeRjQl-X6abumtOrRvgTNPHp
7ygDv3eKG3jt4oJr_v-x4c-f1hhRS4tB71H5uRrDhdY6W14Seb0hC7fNHsKETuo2774kRF-Unkueo17VtkNVqzWD-JOQXTrHcRCRyjL8yPxAdDqeyz1BB1VS
KIHGz5Vcx4OGlDSoXxjNEOybxEvNVYmNtFqdExjPtbzFOtS8GVejSsilYUim7WIFVVUqCHpxlizb8VscCb-sExjamlPmv_GLPJuLjKWOXs4jxfnJzprjNE_g
8uX8FCPXZ-Mzx_3KTPcFomQrW5UK3tMtJuvlQT_l0RMAd23lU7GDuGWIDdBZlNEdSeJ8FjAyzbIdd7BiS4ELb1_kUI3tBQS4TRgHl0TsJFdSdT8DxtqhyjIH
76foA_aT3NLdSdceoKtofEITm2KMDBafygqtUKpvtFtQo5E667_bJvVBKytkVLne0K_f5f_gpnxQeMRtL2JpCCp5dLMo5pd-zx5m5BRfVkoXUtZqxwJbprpF
dof7OTlkC3ptq7HJmAA6_BE6TavnTazmnxZTtOBtFfDZdA5pZ7oWcjtnm8BoHFw1umE9LvNsdrmYizdz3Bmta8daET5xixpznsPtE4HzAZFa-43pSbRRxh3V
GrxVEsD6_mCjcscEhSEvTzdkSSMnIRyta2bbbXUc165v-xsBtHlKybBV6VBIlHMllFSsp6MmepsjzHHdDqviogtKcD6LFAd1pjXGsrV3VIWrtC-BIohu6z-R
deDTatiQzoxRJMhakPQdhEHgi4l8XSRahBRTnnfrO6w1MjsRb7mRXWstYURaGceZZY1XDUOMTLNbUrCuIgqZ3zgvkdBlicDOjt5GRXvBar9JDSEDZvEywHI7
kuGvf-8Fm98doWMIjvVYx1u3lJVcbZCvkSrSa1RLx2xx9u8wEDJ9qgcF9-vfhVKkTYF6BRw4dbkK3lEv8UTpJ6k5pMx4T91SpItglaXk58LrUsmjnTcDcAdC
rPoAVaNx6CkH8YHlfdVPRYvpxk3nHkzjBN04Rol5uQOOTtfogDM53HR1dukIGmrvr25jf3YxEQPWpIQGnoZZk1KuNoNKG4_onjHmSomITT3SWhLaVy2fTptL
Fd8KTWstsTFulKjMI8oqcwi5pcECYIdNSTjbJdFBCWnZUUzCSht0HGff8CLDjztJzDmY4xwIUFAz86fjZHpIGehRRcjqrNFB8Gh9yfIU7s2uD93YfjiUNNbk
ET_DetvlbZUGuhRR7bsDVOpazDuaTrVRRZjceTLSUupT7F9eXJWNzdKtbpa7x-PwAycnEXo5xUNcdiRlRUzZrUK2jOERozoQPtWVgo-7siVDeok7tisXXZnM
boF5VTs8xKIUC-tcpysa6fpL_kvXeZAdBLLlehcsN2ghSpIGzkYgWtTpsiTgoILMLgUDP1VAdERKaoyj_HrSt5Cy7TDmDSRjnzty_BrJ-b7kdE8oC-gjdlQg
Bd3UlpddESIpiDUtrFQ62ZaIdUPpSXjobyBUnxVPFBho7Vavn17jUhBNB-mmlSMrHrSzfsRQlzzDzlg5lP3YrsNE5_HyzRqXRwbtsR44akUNkGNFUmql_x1t
ZKErs8JbYI_eLvFTgNTLBdFrteRmhvBThtVLwccdSul4Io6LdpjjOrspFRfYJbMG4zqYDhoc_EfG-lxe2dNMZl_BPLwt-8CyfhOAszvG-UpsuWuYH9ksDTfm
gTB8ab7OLSkSvVn9ck3RkiGenuLaT-XTDKRNI72MonwZZ9if_osRXrAlCey8afDjsMRB_JjsN5pKzjMLavq_kwscksBlyYnpXf_BZwM-Et7lSYnp3ZlPJRT3
xwewkbQI9uUXr27PgSphk_cWuX_Bhv9TXDpjzIwxfyLtvNBi-q5kzzxbN-PXlqU0s-6Wubhc36Ur2BbTzox_dYOFzH64tBwzox_C3wM6stNlyXzT0QLV30Qt
U-_oB_DmuB79xTQx_CiSy00rkIjyCQ3HdgRTaToUlSk_p2styq75VtGrt0wzoo4sabCORg-zox_CRRTdx_BlQRRRitVvbxdjTkfTNbVN2sw_tkNVqsotL-_o
B_FhxZ0F7nohN70xz2x7Cd_3pLyCwA3C3JT_4rONiOHpTmZaTXXA_SkStRBJFPKEAbt4k9DRS6o2cuRIhc8AsXsAck-A7HIsDRh27N1YKsxlBmRuzpIueKOa
6ahxYsc7M-YUYYzaznnpaA3V6kuu3zt7Ud9FNOOlY7c7-flSFC3rx-O1xklSFC3rx-OzxTlSFC2nk__Ov0lT6E2-qetROyhpy8MnoZzTIVu3
}

sprite $image159 [124x93/16z] {
nTc7Zjmm30HGDnKEwVp_vmPR1al8K8vdQ9L1JNqmwU6rvNwEcfR_awr0KFTbVjOCY0XGrjdq8P1N87C7lrV89wZ7l74NaAPUjZbq4Yzpy7cTFMwlfmczwkJB
VLkpGFh15zT-UBat-7NIefblzerdB13sRNYlWZZoEdNSxTedz2hGjw6zchRsuvRCCpjpqQr-JEXLOEqZUnNlszHnjtsRqAinPtQDZdjytux0kCVrROsEUtpV
3gJW6HlVjsmgnvXU_VhJccIgMhOnlOf_MiFdLbLK2T1Z-qPRDK2Fx1ljQJZFhBTdwlxC9iX-O9hk-xQcKlUbgDaqd7tRSnMLNTJEMJhFRAaY-eoTvsap1ty8
Zcoqf-emmPhUjftK9-3GywJz2F49kjf9s-rynk3nS9vsDjqsKRFhuF55cNPwzFi5shVVENtBj3M37UFWltHckLRQ43MIHbtLg0yVDstPKwdkFUFQ5HM3SIXL
sgKAQBj7jx9ajP5jLmeC0BYRwdGi6spOIyTn-rJP_KrrpsvIrVmhFqncbdMvs0HDnvnPzghDyvkpQbUyS-Y6B9hs8rir9r4Re7FSNVkH0pngZHqui_5UjJQJ
ENZMF1zGEvrkRtt0k6apM_L3DalFVlFG-JkB6-FksSmkffHCiJrjhok3wBW3DfC-QszUDFvU7ASSittVpDjyT7L1QDnns_VjRJkz3K9ot6RVVBcxEd1dqOmr
jk_RzSPRxD7LGlAflP-1DJOxrjNZuoQUM_JQjujjVJq-xhDk3kkktIxFRTR3epBs7x-Poxvrx5Q7nMHBLwpRD_DsP_2jt4zP6oQqTkq7eh67bYq4jsVsV27W
ivViTS1-bF_e4PVzcQKjUEirAU1rlT6hwE1LgHFBILtiRgyYVLFYr2LxEz2hEydQqKDsi5VzlbrAvNN5F-qQw5LWxRJW7nsbG7Nqk7rIP-sefOggTdeL67Uu
RwsEKWIzVLiPuFepwtLypitTCtQ_RyvkPHn3o7xVEZRFsE1iHLsS7UpLgBvvEzQhaNtpDkK1lOfyMkDjucNzAis-qNxmWLwDxXi4lAcFSH_Bf2Gr1QHKg2fx
DIjh-HnszcfUzWg-QsckxFjcsroNWxVfjZzqystVjvFs_1JyxYt_2m
}

