sprite $image295 [264x192/16z] {
vDQ50GCm30F1nApz1oupSvlgTl3BxUiCsHizBSn4uzOJAzQ8ERPA6Yd37j9CIEA8DpOzS99ndyHM2jTMdXUTRIi1ukC8N5TA5WRIJ4ZXPj6vjl8yepW9qane
uG7P_-w9Vb0GR2LP9WpFAI7OIf9CzCGMxt4uNaRRi1IlbCArbUT57_-99is4uJrA1twYIJFH4syLP5jvdWqN1j9CIE93idDjvNa-s4da2msGYIarTwBqDWe4
SVoJG82Fzt_UbLMhT15jByP_GZcpPnAVlr8F3575hPLvv9jaC95FMojdE7pvLbkDOPA3AdvLOvZle0hVVk0aX_M6ImvWgpsXCKnr06rYNYJcE_0smG-Sk4E9
UoNWmBVQV1FTxv1VPHu17C1M6w-L_GxR-LcNM823gVHLZS4xr9ypOWVU9lWckjlX-Y73MmuvDHp8LfklbVqEsKJBEvnwsJZmDi4FdFeTml5_MtvL2WVeEmxx
rzBr02RooMkbT_ZrR7tODnoodYq7tYRuMeaSKltpsJZKNsap3k1Kcnyu8GUrbhASruFAnQ8q7C1M6wsLf3_yB2766DPtCrREBc8SG3Z0MeaSYXcZMpqlVkGW
-U5h9NEuBfpfpF9UqN-LR1n0co1h9NRGBAIMs-oJPooi0syJl37qpnTb2-khmbOkZp0JGp0Ee4tG0oVku1zXOv60Wvd8wLevtq5hgtK0MsqG2UgWdsiuA1R0
0KtaVAta3ifsyWwyJV2raZl4XeDcBEJ09_AwCN275CyArLhi7R9Y0Hn0cq2D8OV_TbWlrzlQlfOtvw0twwXjubgPz7cDW-hD6SixfDxqXbcD8IfJm44pbdVG
cy6jzlX8wCl6znmqN_WPopi4_u7vLZlSI2s_adLnoDSoVLAc-NyTbWy_SvnmXrDGkEX-Kh6GWtkp0hVQVXFDjsw9EIHTy7Am2q264pbl3FwEXmqvQCQIGqET
RxMrYUPLbDikXvAhsdzMVKGETdCKm5ORhvKbgbHwrT_wv6__AfM3Rr-dmvQlbTJR1apa6mk1h-tuXESZZwzp_DyHqDZdqDxtmArsnCt0rmG7CXDjPgsSxA02
3kowZc2j_5g7_4cFqqUPuR3kTNlzAn__Ylk_qc27fNpuBHfFv0wXiMvglY0EV2Iutn53UqlPSEZhazaydNRx-_Fn627XDxlZ7RpvnmgFv_En5uRmmyyVTuZy
p6HNE1omX1-6AuUyNgfwnELqLcKTLdNYZoFnb0CDXq-hlp_AtG-Zqrdlm6SBHK8E0oLAbTPU1vtEEWVtPaH13WF3aTGX-nrqEkiSp9k1nY078E4cbyNTDvZ_
RMtwJ-MWqzccWvww5D0OAeUnuLYKrfQ3MNKtws3U34H23iCbqequBFgwta6LS2JaC3eSo46nUCU1Ha8EI88xQBxGwMoV0rUGm_XmzFT9tHZMuG0QWtVW4jn1
QM4ElZ5u1nuExg1OX0u77Wavz5qIt26jwtfrK2mIT_2Hy0vz4jpXh1nZl3We5kCTfE0TU3Zu_NAQiRm3ZqJRWKjmXwXO60UW01nCEBX3pha-dzIC1HnyOo0E
Ne8xN7xEpbZSGGh8mOU3E_WPYpie4jZ1It27dyQCXHqK2UxWmy4TmhK_A1RKGP5W3boYVHwrfkeHch6mWnIeWmy7Tn14zGZDMD11ZG4u00dceAR17TGOk0CF
H_FtBsBz2CrOt44Am058aFraNduIT50aW0CD1zzNbnjoa09nu9S4do-8WsyCt85BTDp_m1pK68032CVKFoy8H08uG0avB1cN740aW0C8Xnn6LGQH00v0OgA3
8e4ScCHa1w00783490Sr1bXt3Y69sQN6WEidFVvsYJjNU1q0hOLBp8VWaL3Tmtb7rzzxIN25HrB_sIQqYI-Dn3_LdDKLmq0GnCBSVxtv3iUstZtfEWYiD3k6
uzCJ7C1m5C7mzBWQX8aQ67PldzPZXyFloazFx94EzO_4QVqvhwtXuV2xylEJC_fluWAuyisB86gOkDAkN9KmmRlo_U4T6WF3-xCbCE4CqNyTE6hRHcBE6uFM
BanSRlX89331k_BZOt02XzfS-HaJn70e2gSP1z_8zQxqOu9tPH4Jbs5WS4Lj7Wp0IE0RUSILWesSBfoemqTjGU4amOJ5bNw78eKJV_YDN12YnPZW2oV-y1lv
g8ipUam8GhGaQajSATZ83OMJQYE_25mfYDgyAuEO41HEYgWj2D6EZLpWIaNK7dDnnX-roP4eOq9GE2cYjg1m8Xqw6nEGA_EOQ8A1ZzgCA_kO48HeHTGM54wA
ZLnGE2cYTjEL_4RE54vzJE2kZ4Pjfd3gExJfIduZ9rrPZjfDCF0NlvWGtST4qvNyHiwCH3zguuLJT2DdNDd715CuzQCs0uP-rEPSsTx8AJ3KDtBcRk1-r6PS
sSS4KpZr7Sguih-HCwxiOu8fdFeREUFAFYQOmgaVjPcBC_sDd0dH_OrSK3ZT0G
}

sprite $image295 [132x96/16z] {
nPY9SXmX34G5292QpVz_RWuLzWw5Cs9BFbxk-sNKBHXJa28zqO-IclwbqWzI5VeN2DCFKGGwGS_q0-GEVG9jwGU205t0TyU25Re1AJyHXCctnoBrpI0GYq0V
RooOlXZUnX28HRYFHY0MiJxwG6lwdZv6On7lOo0MuI3W2FkTdzdJTEcZb2F4MT-XFdOweZi32VLHY4hbMsecaa_iQMg0hWxK1cuPbKYSzHrQp49KOT_felPj
paqNm5S7YqMyZxk3b9dLYzG4cuF58XY4tK4IaS6muK2VS3C7Pts75hCvL4fDH9X8qDVd8CHZSzXY4LhCvZ2OiaBHY0HIkUixQDHX3ixw3YncSq0defmJKR75
gKzGqin3R7qdc--TmzjppQ8gQVdzn327qAbkVVGSeAss9jUo6kZKTNVOU-gFmNMm2TIggcilmAGt3ivBcNzHmk9W9qU7wjgBLB0wm1t8-KK9ql7kqF8_x0_e
jHVer5O7z0_-Ig0bluyxagZYkH_UM7jXerWSAcM14ulZ82IJd0wzJ5ZNNgICgmFQyZxYzDIzCVTaNPnh4PEr5n1gq-5jF9Q_1gUdVXyDQ26Y9BERCswOlP1_
T67g8hOd1PDcKyRDIvd_ubBpEsIsbidIc6jfjSm7a-c2Cb5vWvCD-kRsxOu1XJOg2d6YGYLHi_DYSzX8SdFxja2zwi1KSsRYaZgi5wv3ldifyuBGU5BD9hVr
g9wzM1qg4TVBvT8QzL-0uJXWCYJRVqSsXpqFzPB9kXPZ1-E1OHOkRMunYw2aILPOByo5rRXsKygw87R6u_4OVm7K9LiGdlU7oPIoTMJjqcr7vPlMuV4mXqEB
Glrz9GaLD69aUZylKD9shpQ9SZi6Oqny2O5U7VfqqEbFZDr18Pw1EPnRVEG0wuNT8rS73pDO70u7iiy2StaNKdt10OyBumfmxY2rApzxGGMxWpy6OwpWo64k
Upn_ebFR7Vmnx0u6ZXoCObkWLPcN5zzXZi5p683l08CORxr81Rx378FlO1PU7YepLwRKvdaXr7o7QU0v-0DPzsHIp9S_EPc56VWE4-3EGPfHQvi_KRBw3XO4
ty6tc7cONDulF8Sv1j_1jn1QHWzeQu8hYaea_XXy1mCVEcGk5_WlPO7pve377GFZfKVHwOX-Q61Wu2KBuIFaA0Z6hqVkmxFG1Hnn5WHJq49KT0oSnU9ru1aC
9gE-DX2Vyp6qoql_-0eBp-2NPBgGnRK86kmA-_iJlnQBU10gRRmKYtWGUg8FIJqOY_C-PlelMVo1nCS0fZlyM03nFheqFnOH0qdaS1YBO1zzZjPtk8y-33SM
WJwwdA_lQ1zzpjTtl8_nMFXZ68rUuFNr7UzZlAV18FZuwnl-HIc8lxuneeiv7WiCvwBa4ey5nk5YZbCi5ev3O367rZU6ivZ3-ASwnYjzZFFHInb6T377rpV6
5_JHx-d0vX3kO-XKnuZtaOAdEaQqZ_5OO4Jx65_V6D4-njStHhIFyLCT8zx7-AaUlYZ5Os4VKVfHaiJx-0S
}

