sprite $image34 [321x227/16z] {
xDY5WGCm20LGOlZVVznpTx-suMqGGUb6AQMKKahhOp6Bgfcxcvcgy9gzqJlAM6AUU4s6oHgDNb06QoG-98mVtM8PuebFSfbqeRHbYQz9vqvxw-pudf11kshi
-0cnvp-SblWnlhRxV86VbT9f6rqJly06RM4OVejFEdd3yPjYqadhXe_AZ42QNa_4aK3zmgRuW7JbEHeHJUJZ3OCuFi07dIP9l4yQtPb8Ueo1S_BCQ6bY28R2
1H3f-x_kFudJydT6NTVc2h8xiz-S8s5ToCiAdisEVLzTtikA06ngyo76L4ucghNAcjDdcDAGbgMAutRkVV_Dd7tJrqa2woaex9sLTVyGAPT8F-JZm2jw4buc
GdlSXIhJ3HE0lToatxusRLHxQNqBCnv7coYdZNX4KJ2E5qnp874QrVs2_1AU5P03GYauU_WnXp1s6DTMbnRNk-rFFu0O5LfwppqohHWRE3oDAJoLz_Slo6xg
CcuxGJIg8wARg74Xfen4JU7EsqE9VTbFxpViTxGlx6Mx1FcaQA0dqxKt01pqcL1hf23dcoflMKloQwkRxrFDDwinveyoxB42DrC3QTW3TLGHpuA-srMRQVLr
RPyXglxV273mCzjUGsm6SN9g4yPNpQBQhtOlyoR3Qm9aOsL4_zhcedy1HyZAGcdTtsmafqhcs2RkTH1wVcrU0ihl4u1YCR0TNzHytujGBIlPe30jRtUpcvSF
s3Ov4IcZ8C2Y55cdY0umZEg4WzNj5ciIJ8Lubr8ILzsVhtSd79eMAHX5OQMBIOKgCz9PHyYipS4P5sU6mQyNVPUV387-Mv4clGjX8D9HLLHmSD5S7wmy1v-3
knmCRHO8C2vURSiE_9mA1x-SsLvTiSN7702_1noCOeHU9WAUcHuVvVFyoFJQuaHxT40zIJUwzvP1CG_6_6FFB9CU364m-EB4xd_SJn_ghcIc-xUU4bjuhCPT
eVJJcGYwZ1zjYlto5xcA2KwMsDHkG8O5gnihDHrho-IuVo1FuzYF-ryoQy3JnMv3HzpYvkUAxmZM4wUbGlwHO9x34RoPX1OSq5PM4QnkUt4vgVuOWgd58LMg
s3rGf4tB1PZSgeMaTWpzYLrG_Rzt2_-piuWz11Y8yzHbPixiLFn_GCTYfVOuskhzLCtnNXpatFoszDLj1TdZa9KTgt109_9WOjXEec74kEEY-64qT2C--yz8
S3O0RaAhUmpkzb3-xAgQXFDzdUOLM7QMZ30_6Eo9WJCyxacQnmO2D23H7u-MytK4P8y547H4-XdqS65lqk2n08AC57i6aj6Bpy4U2o2G9FOyg9dJUJgeJOQp
QR2RByH10a-0doHMkuTF4dVp1y_bi1nIPXgXFQ9X7WdjaxPCWjWzVFf8DQ_GPmUva-H88dmpRnv8pkim36PLYktx7_ULlyQZMOFRGE42YhzX0IbbIJsN2C3T
hQeSdrOuL4IuLRGVla80tgKgpyyhjAQQVNYk4836v5Sdg2N_u0i489TVfdyTmT7VYFV3fAR8hv9fLPMVt-q17tH-cLeN_FrtQLIzY6YTNvsWHOGh42pXshj7
VRBupLdinPu25d536lMexOGiyglbvg0hrn3QiVLw608_9FyKmUSHdIta9b1g2SJeoXTc-j7PGep03qi_Gx2nZVZnREPNBuDc-cORIM6hti7CaY4l03HJ40Oy
rOFVSYH3LW5e2WeHMLuelpa6Xo06-2R2MvSLlC7YeJa6YM0K2PgkayFRePWVZQ0N0PhD7zBJX-rumlmb0aoh0ZHTemyFL3fY32h18i0POVHuwITgNkD5_MNG
BWZkkz25JtKsmFGQm1dXu_0E4tElLC1bog1DKb2DcasCZhFuPH0J18wMNWBx0GO2U5Pd4SHdZWw2_h4SVl2dEODHxoq4hGvGTQf7H2MkksEj99xvwOiJlFDx
I0XGh4NmWf_eyUJt41MaiLGPdFXrMUdwYJPMAeCN_CXT1CTyVn9ZVdD5eifhBxHp7O8JFz0J6KqOIzSfWnC_C9YsDc5i1lbby9AVA66O0qLtzIG-yPkrRsmN
8pNfM8JWDJ_PTg49duUJc5y6h_d9ur1X2KSyJcB-PkkQdzm9Hl2ZDRVVJcD-SkCkfUqzNT-QhCmCKDy6E8veyj7B3YHw4k0dUIGVuDfbq2Q05_makAC8FgxV
onZWTvOJ07uYuBqR8E07SeeF42Sn6I3Y9zO0SF4ajeaVy1LSW250oCjGXpd0hnrWlvV1ivmi2d3PWSGGltw0IoUn0txj05DavIHsCy2ljmi70DZjPTpC3F13
Fh1_4i5Uvblv6U17d4JmSVo11FCpm8yu2-EAmKzYpCy0lzPjZ8AUnHz8C3_iAvW26sckby7yiCRXmjJ-5226by7yD0Ievqv4jas0A0C9vfTUlUWMgXwxo099
ZFbbcbJqtDb_5LPP8OanlqmjrYI2OCtbUndCBwDyJzi_o_474imlq_j7ONnW_q0I9twYaN-avO3W6y7-9CRyCbfj8FOn_2J6_3nVfPMcI13mJImlW_d9YHy8
GUhhDlmOX-zbCBzC0TeV8arjk7yWmVp6wDe6udqClmnYVfOG8Dx5yBi8tylK-KLN3y5dyhqCvZS3L1mD186ePoTnFVw6r-eHVnPfJsBCRm1-O9zFU6VEJ6BC
JsT-gT9YencdbW3M-Qae23z-2SHntpcGO7wfqhoAmIiqsa22-KtXPyqNIdWBJarYpE-CBpWVWWN-Mi7nCfXVuF3ZcnZy8epiPJ0_77xOqV9pcEzb03-ZV4P_
3kCanl5dfYA1mWzdC5-wtwKdYKFrDp-pcPzz8WoeUkmgqk9b_1T1E_73uOUNqVojQe-N2LNzmyz1-FK_JSNt-Vo1H4NF_73uuLT5ZJSZ_874H5xvZIdyAb8G
0qjQGUnbigGGEVCBWfCWj17YGFA7ty2BW_v532x1_8743OJVMc_B_stlNXRS1c4eW5xn1ad__xbzuRWPPqBiC0iJSvR9gke5X6Xdlb4a_8ZyA7sdVfDNwsSn
lAC83VxRhUTlkMRjCd_Fkfy1xCGpW7ty362dCWFOn-ce0iuXwvWO9s54X-Hm5b57L70Q93eUCJWFDrkOJlbg9yXSn1OzvdqauMpoXHRmNCHYSJvktk4wnTb2
Tofp2DE7P6w0VQpC3R1Fc1rWf_JX1yWyI9XmRiHw29zWXZLo1MFNeXUVXZw0-mVy1O0NVHFRWw_IuZ028ySwMihl7wTKz027CLWviA08W9DtudSulHwZiBA_
esMsDKY7I3WUNGzyLWNJCe6GSFZmJWGWo95ZN3n6OcHVHsjlUvCv_23a3ntZuZ0MmxiwMjQ_Skt0Ss1zHP9BIpjNQbb8Fgr-5V6UZjQKssQOLUtBjLyS0BUK
t4Wcm9Hn-xysoY__H0Q0ovng5Xc0tR6DqUrHpQmReIHjOOCXfHShYgGOB7pDOT9x8Wzbi95btK5X-VRN4Lkv9GmgI7CaabKrMVpbf7RLedSoxZCfvakgxV_l
2ZLFhOHnMMc4mY-5oJ6LfLpkcxTlrchJx9JrBJKs-oRn65UZGnP7ydZFofkOslz3Mju-MxdQBR5hHLtPOd1nvo2BiUr8793i-c6eOTn4C2HgtcCoONXk_xtE
Rmf4aW34TJtBPeLNlhrynqTvxs0cRnh5eBBcaXuAcF6NoVfCCVWGNlRDfhQtDL7rjmXk2loN0H2Vno-YkaO8pUPDZvSLNMuHj5zks19ODS7p1U9NETQ6kXnv
SyRw-0SjbGrt-waaGbGLResxFajpiItveYpFcbzUfzSXb-HfRHax3j_ncDm8J2sFIxmkODZrbthN-S6EIqvLB3wKBVgCP8T_o8PIDxpxGNB-igjHQ-x57XjN
sGebUy9VATQQLMKTq4hsrbeNItlM_-4yQmD7HqYe0LpOpONcmkMhND4cAT5R4-yF539UNsEFYx1PT3zXqHsAmuLG5Fr9aWokncNH7r8yBebyqNuS3AwBV5yE
Ip2ujlNwSPmaJ_XdClvW4JdxJVGciY6nx6XgSd249oRZGin5HBT4Iax16UmoaJ7MEUUzTyvPQmYdCatJD4tJD4s_0G
}

sprite $image34 [161x114/16z] {
xDC7pkDC38DXJfKq8dt_s_ubCPnuUtE-RKyQkbym4Bx4Nt-LDgP7hFz5k8rUyTDeCv9w5pDcBtXhPGJteBlZzuOnAjvGlzUH-X1oRonu4yNo57SQy1H9gtYv
wZpgFenFZVJwwlMu5noLN6uZilK-fqMU8YdffOcJfsShKmQKKcorNe4Aoseypqd3YxGbKOSrA-RcwBhP7AQKeud3UCn8AJjUmKxhHKCTGINgSgCeWukQC0LW
ulEAZilLv_b81QesKQmefUOjBKGrh6q2JM8ydKisNAlpAS_AaXfiO4WTwpxJm99O2bLhHyenT2IA0rUQUdfM1nhbGBFKRRWCxgM9fiGCk1hYSUoK3DTnaSTH
QfGA4mkuAHae1LXIHqgEkHaMCHQ6nEJZM09N2L6xbEHmbDI4UOFdC5_9FSPBg1x_yYn0pwDmbSlx39CAvCJG0aftwenYdz84nZQ1CGjSEWelxQF6xPmJpWBN
lDUHf0x7aIDvRnkObsvuz8boz0vOdPl1zfGFOnjQg2AbCVNOy8hxq4F7YW9qCHzr7qObcgZ3DPSopuz857AYwGjG0wbiwr_cpGCvKY26eWejDM5gxt_R3Om3
x6UC_LiEhw8Zpwq4XRp_5RVYRjF-l-OsUfT_n_SUHRErRUtwg5s7ta2aINyeX0Nj8du3xT82WSGo-EGfp-F33tzZSQ4aga1iBmo1oZIqsyLL6SKDhm_mEFL1
3l2hCqmfOFr4mPjMLCXdqcKKNPkVaFsAXk1lQgl987qIGJmkSTcXTov-FSLgWhG041Sz0GAaCaJEhDzcQCql3ASkGomDixB5Et6FYFRs8Veg8_Y2Vh632RKf
704F1i3YmvZk0CMSIqj48-F3A1YQrfH9WmX74e8D1FU6SmXDx-Z763e8xXHp4fh5vO3tv0mD15yLRH4I_D58KZ10S6Uuk934V2eudePsC9nII7hAaTPfGpyz
mKqm9Y6PNOveqe9X83YUX0jqAEybGJxuYIvArmWGMM5uyDiYHU6p02D1Tko3TwOGYfW4iOeqFFf9Jw78Bi1G9JSOTN0Xeii0OqU8VdoVwI5I6sI7cvcDnWXY
xcAGQK65QgIOcW1ZlSR1hrHmlDVOtQzUS6YWO2EKGi7A8BiP-84WKSLqaD7Fm6-eYZC5u7kDFzzV8T7B9WdVQzhTJqsGpC5Pp0uKz1DFEyqb2fz4neACVX6X
PzL8eL1SHAy1lq2RsOlkg8b7AFGBsERIPUoPXEmrw6Un0KTeiv1a2Xbaz3EnU6Quos03vGSA-gKF535M2HLaz5DxrWC_cKrOjXybUWtwwRDVg8pM22OXEL3G
BxCL33gypI072lg52Z8ruLbCY22Z7sOVHfX_i6DxJTE3NoWnyO7p7aeE55SrKssxuqFc9a35CC5UWuhPz2yj8tieSGG06G1xeunLMaIcNIKHpv9noJJFy_I0
Fatpd2qUiUZm-_PFvLTMl72_udgRuk5Fhbgpil2ZbnQMGaFSEol0F_40M_rctZZrEtgwVfQXIGsjNf1VqEE3p0VuHrOojC0nx5P_XlufEwB8nHoX4f1VSaIs
DLR2hqirVRiS9dhVUO3Uoo8fBka2HOQOwFwlJPx8R__uyAUTir1o68Q1wCgoPKUG___R0oNdSUSwN3fuPTvPbTkNOk7NypqWeOSpn1bwVRXQqFDS3ygN2JrM
Aahi3WxLI7nQ8zPz0uUL-fZ-Ljzb8Y1Y7IZ1M4VfgLTfL5HY2xFBQljZZ25Ffyeh0MhWywWcbdTD6kwXQMWPjV0bNyCzAMjJmYdyfG9s7Ct8VIdbvAv41zlQ
BUFEZDKAEzrDWeLdfuDewWzPOK5VnxiHxaxrC-BS7XaefOAzOUoASfvOmJRFbqhO8w2rnCo5RJy-O5GL53VAshRgccUTzPLdo9CUHk1knq290Da5A9N0ZnSd
9sqrSNoh17I672-o6eEfD3tFajicI1uQSSselNEnz3ZGlxsec12I9mZaleZGyzNayWHjU195xCYKn0LVHrWlU2Oiwf7uoXmyu_bGlRAW1RUjLyBhG5oRzF59
brQPy5luvvzt
}

