sprite $image108 [239x173/16z] {
v9a7iWGX20KN70KctF-uFmSs-sg3olODkcgw06VN0YuwxLu5ocfcabx3DgbzKoY-B8lzauFBKh4zDFGNFQaT8XmsMh5JP0eURNnXodO1II67ptc4OqOR_elc
ObNeH34snbeaHOisTC8iXf8fmF01q2d6nXWvOHyjJk40mmT0CmM85a1JW6ZZ9Pp4Ab0DaJ3LHQkVZ9zmhfQj5KwZHwkEWVTA5a0M4IuqShIuiERklcDGrZFS
54vej9vv7Uiqv7A3h2tR2fo6esoCPsMtMbspgRFXWt_76w3RFc6M6sN_TO4fFCpmyIpRzg-htm093n6jPrb_TR6fD0qqV3osVDdEw1IMD5IqFjzrwNwlnACz
ZwcdnuG97Zuuu0Dj--SAd1uJvl84MIpXziC7fyU4WMYVvQjJfyC7Psbu6l8DmqVoDSh9bNfjzO-5yWtVSSNZ2-i1jWAtacRgQ6F4TMrnfo7mGDiuMgzRpf6T
xl5f23pGDjyOlQwUGvpkuMa8JM5kFNnmNNyQhZFwGDjsOyHr_McutF10so9QNDSBctfkIFYMZL555B05T9-mICFHIlb0AcH1NNh2QGX7g-K7SR9FrWMcyAt3
HyeV-iwhlQutokjG09wbeorbt__jxWUtZFaefAepZVxC-V225fP8ly6wF-6wcp_bkh-w2zFh4sDadrv_YXMmtt3T6018_PRh37aLh7XrOepCQ5OGApQ1-1LN
QRu4yakkZ-n1NuxmQcWdDpFyMx3i7lKJrmTsblXNxjy-97jr5-Qbq4xkg6E4tIzRUMwDVkJw_ky3dwr6wcTkcyCWsnDkl3vNIklVSGVuyWPV_uzzSlSuiOge
x3_mhzbL7FhZkkAHlLAw4Dh9tQlLmU8VNEVznpmazec2N3oP3-2xJzEorqfM9yR9FKVOXR_K38WEBZxRUszrkClXKfzgTY7PvOSjWxlyWXRQUu4R9jg_HlZf
u3Qaipbz_v6E7YYK-DM-b7rzhfJMIzm60FQreuLgAyVMvZCxuwbMADZLwl-JPvRYTFYKkKoGo54nmIhuDIx4p_Vs4VF7fH0tEHq-LMvqXbv4MFbMoPVDBCLc
PZk_j7la-PbLdokrLslZCIo3qFBYK5BpMN8W7XzLxdpng8B_jupldrGj-fIF41VBC4DRusO3B1MQpmybeqCZNXv4zEGWSdb-yCu7zEIMIYD-n8qmGBj87YhE
OEFPY7Egyhy-5PRzuSPk9wuVhzNJhtNuAJU6u0TSqN10O_l-tIcyiUQ8EBc7Uqw4EKMSPsQkp92nO-lSxUNr-C_MkGR9Hf1ncOxWRhFqGmNvkX7Pzoj2K_fs
G-WJM-QE2vIZeifjG6G7F8r8-n7SJc3ngttNdow0CxhFGtlKFgA67NzcxyQeSLEXaGOA0i3zDi9YxMwzLzuwcUH-lM-cNkZZWSseOFSBb3d15Mumf3N00JUY
cDhpNEdFNjwuBxohMiKUkY6p3luWCROoGBj3Cs_1xhLNSrRYpj3EoYY7Td9dHO6ReGHG1q1A51azRW-bDMuvjEK-FdBBDtXdTTEM31S0BGWqTWQBgqEfmDK2
z-NGJcuT73dBOTaOPW36pa2u1lyhRh_2rljuSklWcE0GU3Hp0JU5RbomnyNR7IzpwtsyXftSOzLkS2SmISX65RID2qY_Yl3ht5phumAttD4X07NRk0sI17K6
zOkvKh72VJsq9MwzexltJJgwDmcMeU2uE9IsoOBk2jzm-m9sNA02jzRHaRFuyuOIk6S0BQrTxCBFNt6Z7jhrMpkvwn7E1kucFGaW2uAbm2zEOU4d9R_JntLk
_L1o0E0aC0CONBjP3LkfNiSMkEiHRWoCx8QDZXPOOP0k3L5B9ssDknxXQ2qtxkZi6DnZjJNlScZhtFK89utPIcSptmtIx-_ZEhSUOIEGXO46jrcBpCK8hny-
2zpbKrW09c3Z1W7ISYd2wnFZ4dVz56uCV79ra_jzXBtUnzNGBdFNvqeNzj7CqICOxJR2_exGrhdhcr9ktCvitI4vgkjvDUnvsyThQzuYz_ME7jm600IEC1rp
THpdIe__FVxXuLDWLhZh4RO6wiQWK03cu3X4U7liFjuLsZftFS8HZ9uD50GmPEFE6fZtXRRENO-mWrq7rqA18_SnkPUXNJzyrhclTpG1WziovNjk2LiFxJft
VP0sKCZ6TN14Q_t8VNSVrxdhSwM4GpyM1mN83zmtJ8phtFLd5b5F1tS20JQvRmZjEdVz57QG2xWHskZiCtVfWu4YRfsx3ZO21fUyWoVtZQ6TvLNRUaTtKt1d
49ZG9tVv0wxbUhG_z0PmA8UYDGPySjyKsbbzl0tb_liT7TaX4KQwS_kx-pZcbrd7hu7pRncacRUTku1zgO-FNnU9DtHqAW3QkU_juqUZFyTwESArJOd-tynv
O2aKX41mp8hi_O-xEUUHNrXz0vxKwmR-k8sdSeixndbelsZB8_nqwC-RLcZplgs-Vqz3T_IJijTy3jyM-uHmD1ISdT2Urh-_8U8HpjTYMypdT_48PvVJdl_r
s7C7T_IJxtP2-xlMBCBvxvysim3jPlnRcnE8S7RqyNPCQHiSmXFVCHOIu-mJNggZsnFZLH6cGzHb_pG8ZOOqjBaR1Mtx2pu3vYD0c4cC1Q6Z8PyO1GY3qEx7
Ojfr51pzq5AZ8Mm-iHaBQrqR3T74M30V365kp1k0W0KjaXXD2EFc8qFO32sVAmCm7nV24Sth2a6k1A0r8nnbQ84-9X46p0T6U5yejzJ7cz6i-fdqyc9Xys5k
BC1Xm6nAAcZvxGu0hTc5LOcH7mtd4-DwU3IDSE7h2eKc4GPsCsQ42VCHvqh0VCm8gyOyVhi3Z7dcN0bSfSq80z2Q4TOwBNFu1zOLPeI17QCPOUOghPs5Vows
O3xUN0cOZnbX05epmbXYT6vtlYaMM5Te45RrCNzZ-P8OqMBxJUaJme3vc17-K2sG66K8az0A5xH0OZJdIc1TOKPuqUyO_GW3q9fp9P0OpGXVAJ7U0G
}

sprite $image108 [120x87/16z] {
l9Q9ak8m34HjwvQS___TnN5s4XRXMgQ0dfFpbRhT8kNN0fLQlgxAvcxqRIoPcvcxmZUfe3wmErdQjwXD3kf1vlgjOErENuaP_wL-8-OPRABFnbmvfqwpFnOp
FGPxVmi_4gmcr6NCx-_EbAecCNywM9rwC9lgMuFDgPhCRFYXxlW5Ang-YFdDmPvKxzlvyFjMPrrQBDQtxSRDpAQtBiMTSShYnhLzy8UP5T-v5FLE8XOcEfLq
whtTkIVBUUCTCQV1hlM6c45_GrKnVuWPtjGT5OHxePojSljrp9NN5aijjTLJfR3kyZvBbNn2lg4xWylNsstU5DzcgTAb_T_TyTDgNND_RbfqqwdLwbm7AsAU
K5TSsR_NRLulHJScOfaMfrn9k7VAOrvVK4mm4yiTZnfTvcMe5UN25G1PWUSdvBex4QxtP54Qp-A3ouTh83jNH6LCWrUoP36lbw97T1SYvfCyMHE4fLHe02ES
dtbnp-g2zSZQlBnI3FCUnZkO6noQUTHIIy6H5ionZyUnbcd9bFMjPssc-lnp9xnLZWWTP4fE8izAYYQHJN1i0olYdiSyWttWLW7kHyoCRGWc7-PKF5mLgkF6
5DHoSTfwg8Z5bbtljf8inS7j30eUDnqnptm7K6iPZWBKYgqK-EaH3YwUyOgCeH-vOsI936iZsgOHVP17cOc5Zc5aW60VSx-ZpJhBSUhkBxvohiKMaP73cp4O
KEoQCMD5-Ual3t95EVlBhV65AhPJjvvSz_LjS1DoT6dSe17DcLtcqRxkAzblIxwlHECfTNya9jZ_uKPe0sfKpJHYT4fetoEB_VneSO_iw6m7DndPzp4T18Tx
7Id-jfdFUUKSFwLkaLjySdDoX00o37e5dJ4FzWrap-SLiLW5U-LcPlkOMSN1NO6jcV_j5DPsLIdyGh09Do7ttXdPi4fZaXupPeO6LqaIhAV1vjpSR6u2HDMG
PvkFavr8n9R1fjp50Uk07GLvTkg8MUIHkhGuvIvZ3aUeI7E5dQjJ96ri9DI-BRWBixkY8gkWz1w-nyn4ya9tLjorsKY0WCQ6jiVC7l-x5DVSDJdSW0cnOjK-
RiOMBtHdpLstsR0XY5MBeMsBbxgpvguxfKBKcm1wHD-veilkF5FlyHhPWHermicLzL9SI2DU8nirRbIbtxZBxZndzcsp0fQCl8xPKOW7ztbteg-eWUKcyXVD
xWQWD-xsEuixbwagyHgvktWyR-pQOltJcbbOCGm5CQnCv-u_RXd2iLxi0GgdPtrQDquf5kRciAk051lVUkcSL7OKS-7kFC7s3k0SCmUhWGSsZfbtPpD-om26
3RjpsKtUge1X0x3Fxipau0oRWNrsnxarCpfbWttcxDtP6Ug4KZJYOKPI95aRc2qfWZjeeaucnH1cGufEi3gBI368MK2AISm2tKbY5kXE4hCCATe1AwH0TvAO
5G7BrQa-sFKgdtrts09IJ68M09lib9f_rv1Y2hEu52Fg591Y1lCx0jr9OjPLG8evTGf8COYvPEyKm-fSq9qx
}

