sprite $image83 [138x138/16z] {
xTk7ZXin30JGk9l3aVx_RrD4m6SmpJjaifUYDFHxM8r8Mkjy-7VN_tKudm_lW74ytmomsywOu-KE06O8pCuCl66kfvqP437zZ8mv_Xx6wPeO2GC0zylnrpCi
CJem_OoCEUxDYC0uvwM_Y0gCCSOuDpDM4OMzpa0ug4lg33mOQvrtOrWmwf8w8noTakDsHZoE96bhi58uigJUKiHmw98w8noofCx8uQXBSeFLmr6Nv5gkXqEN
w8nmL2Mvivb134TT4enKlUHmw99So_Lmr2K7f6o8uQXBZdIjSlHBd64HTgLV4XQ5qIy9YnAEVabOok6eIy9IsvMwnFt9OWL6NG9dieZXg4iiMPh24MlEoPSb
mBF57HQxqk8OOuxN9Sl29qiN8_xX9Wdm5Dr6n_Pd0X06RvC4GvGu7fQ6ny4nTOaXB4L92EAf59v9MChn28USs34S1fXJPuIWc5WVSowBKtManAeISCul5dFg
ZiTVVEHb--x0V7onk5Ddf92ezSJmnKAdLZsIGAyde2-B80a6q-Ee97Qus8Ep86Ig1Ak3knKJEyDIgIU8mBBsJ5hgYOL5oKbpOe5baHERyw9Bne0PwEN4pc9Y
Los1FH8hOXew81Y15IGvhDMP3QdQ5nDRg_OSyjd9krBfWBuicgIt0ux9oYUk-SrdeqbYKhBTEo0y9gKTEw1PI2pEiHTdjdnmDYNMGh82ksTYVStH15T8neuT
qESSaTX5mcuTq6-OaqkoHdlRhGEwNSUa4H0cfSuEI0SSLn32fDJQ0HS55nCcfUR4CYmW1jL9AGd4pu2aEnsHMCBw4hjzTs0WlJOfFHoLn1ABGe1nZlVgWAGR
u2nCIjyM2FM4C7EcIQdU0QVG0TtX9CPO5kpN0UEMhpOfnQdjcDb8QLBgdzaCharA_Py1BIObxKufLjUjHN5IYX_QT6i1uKv9w83wdPBU0NK9odTAFVVs-gJK
Vsi1wxjJqXDRdvIo89QQs6NfJQnwfxGirGvOJMoQbFhgoQ1yfzJS0SbvgTufrMyjOlbfQs9ZEa7RhKKCa8Wd8jyfrMUsS5XaH7hxXfQPBHptj2_YspUzneQ3
j-EhZYonPIadDXn-FQGVfhnzgtT0loI7E2bf33vU6IF7L9cKOARNs73ODs8glttJt-HJ-uyfzKafEsw2et5I2iVcuz8_AKLUewfN9VOyAIavYQfUbZXXfavA
KKsZgjSbS_1fKi86IQhgHOdVEQSZ7ipcinCnRPBShdEwQPEIfvWMTyUSzxT9oL-JKAZgBzoMszcsJKfCLRr5GlhMIOcfghT9wB3N9wKuBX7JPabO2AJlAId7
HPUGJiQ2XUMRaZohzwzB_XRrzoUbDAkthyEDz6SAp2bLzVewMR8uorMzlaMEa4WnxTyYfrRL-xV8ALRr_bD4jQhtRv5QrVktQCGgL_Nw5gd7fN-BXZQhzs-H
NDNxjqYjwlrRT7mNZF_h__e4
}

