sprite $image292 [236x171/16z] {
vDY5SG0n40D0mv7wBpZCoJsZiXKyM2EDo_6gmSh_87WcXLyFl8fMk5N79w-5cE8x8G_gTxqmQew_U2jigY5ZbU_uveIlPtBHUNecGHTRmpJ65bJYsBR07D59
UYP7C1i5IsYvduwbX60GJXQDi6S8PgDWFI4OXDDrWa7uYc0sAX9qiUtOcl3rJ2xwZGSXmMmKxCS8UoOdV3rp_TceID35Ld0K9UoPd33qpFLdes2H27UtBzmz
Oi5il7JFX9jfoim3u-JoFHDkEic45-vNldY8H-RD14Tw50QZNLKDDZPLzx_jB16ZpCyi5daG-bqWUlBtoMIJD8GegEtEecfE5yZw8shxL33H0MHxRHy2HZfp
kFhwGV7LD07TTcnyePdEdst-4GV2dAQHIMtN7mWbJKN0tHulAXyg7oslBJyGQbg0WhizlcUuAfUTVsnCXQgkbvNdj3t3LJco-cxlAKXr_cJv_k5xXgjoMNtT
-E0XBGOyf05x1knLG2uX6UmPcE3rAUQrpMMST0FWtHueAXWhG2Q_97XgkKAU96ErlZ_lTtKhaeS7sqXmpwoFiFhdxxnhhIMFDhRn3UAx_ZxEcc9dMtKmn0rz
WZspDiBbDEnbNOArCrPR_YOAglhdFwX_Khh2uY3d0e2kxywmbxNXmZPUArwahfZg6UDpiehVxJsrR7JLp_zH3_BfYZu9UqZ1m0I7WxNEzM9jKo5mr_m9N0zY
r_ZO-2eCldDan1LyMzBs34VskiRaBoiOVlGVS0MZKRTPjZDMJhnqj5p4Qd5tB6lkrQQ4EDuvbqthuOf6Q-RrJno5sCAnAecmUMskrssRvm4x_NkOO31MhmV5
6mOy3umT9ooQwe5SY-_f6jY6dWru2olrFrNzhyHa4htcEX9ayrwquNsAkUtxJrMJu1udZE_f6jX60-KfFX5xTwQkEGMgSNnxruPTz6mfreIHuqBkRlqNGm9C
EzV8rck4xtnF5u_cT8s3R3N25ihAS543LsJRPFCILINnxLrva9jioNjLMtnZrtYq7dQso6pJ3E8RkA8WUvcUOm7n3LofhSqTRGQcaIklhPTvjbbHKMDNFjfP
jWgB6hjoMvzXcnN4Ty2L1zdWfxKoUaoYhjoso1LTKN1C0gxW86MbwKBHs9IxSbkteHzqSlC4HGMkACYdRlpZLPRJ4nGLkZOCNCtDVlsXJd93_a3rj0Jn1QuW
o85m08qlT-Ms3Pje2bnvRMDybgdNCRAFOWQlNGO0HUMkFCWsAxxCbGVPG89PVBdh_DfkY2zmHK6s3V45hiJMjfWsSl81Q91zIr4RvVdraFji2mIO-dVxPksc
8Dks-DPyVejeTzZwllZ-yfLUlY78k-9hh_xJTsMsyIniKr7JrpzvbgL1jZr5bSxoZjhwhZtJSKTjjnJr-xyy5-uVhxPbpqIybjJsVbCzzan4CXBaUHZVCp6F
wRNTlsVMrtRNdWbPltz-hzOyZ2E8eXZa7FllrmNuCdFeU3Ly1acx8y-SFzRsXe7mXkDjpt--lmSyus3hWth0CqjizvuHOgCmFE1xHW_Pymm_tlRSuO7VEyVM
zymUMzypldzyK95_4BPt0XKyNx_j-PvHsfumF3majlpvVW7F-B7HzupSzhpXWHzlUwPdzh5H71xss7gWxcEZ5mZt_W6UaOz_9EWyNnuRFS_iiUMUwM3h3G_x
jWT1JM7hUMOV6y70dSFM6nxsiT4R7lPjRpyyU1y9EfxXRGzu9eTjnpCyDe90cFEFDppisnxuimwU7nixdk4V2S3maCEsundUzj3m48kD7S_mjWSyayCMW9gB
ZI0Gvc8Z7nuwRGy_tr3R0yD3BZO2p-Im1SD3pZy0r5pR0vx9ORi1zGy
}

sprite $image292 [118x86/16z] {
lPU9akew34Hlm8lSaeR__zj79anv5gSnoWizQwsdqk8uyhzehgqi_zwSIsqDBRsLkPI6TW_a-ZveMfbRK9TtbOlMWvRVM6uFvFJnvixiGRsSoRmAsYW8M1GO
QC_9urtMSabEiIWHPc2yWN99pSjPjd1kEiqMFjxBIRRme2od3ZHkKRnS-Sh_R54IZ7crblmzfLPX5XqlLqeUfme_9EEsIEqK0evQb1fs7fEd21blo9QQPrA3
5Yt3WKgUZKGioer3vx5yrU3bSYZ7SekuBHpAiTmY_cuf-SNmTn6tPVxJcrBw_9K6dsHY4NstF6LcWPgPjbeUtAbLOoaRCpRLvhT7tB1nXQmQn9RvWikT-V4L
TvDUCHblBpT6zPNPiUOrRLIoQdHROjJKVa1l7-OwVDPkKRSbJjK_L2FKxP3Sc3n2gHXIXMvq-emADHI6BNTIpytDMpTd59X22HTGStVb5Kl7tlzp1ozOpQ3t
03l45MdcrWh5LhjzvMCJf-n2rUxHBS2OkCMrPPuAyzKQXUH4fWgpRzHVDUj6x85mQagvh5d_sOT2hLC7ZmlxWNM3b3mT8ULsweYhzWlRPh65b3kWCgwxjhd7
hQJSCLLrL7D_t7g0IQXilEuA_hobae4oAg_PJ26rx22537H0fJNhZvhT5FYyNfNEwvShLYwdSeisanN0upBPQ3gJK6dDdRm6xNbWuq3tWaQuvZh1LDj9qp6N
ZzVSGinELOovtAAd_HAcURk8AdHslBFzWZ6jBklAho_KFDCl-8C-BW4PlshcXwGRukLg-dPFVccyY9Vxyt9tVM6y6Y_tpqqdOMwyyNAHXhTNNlD1ffMzcxfm
xX5RXDpMhzoY8xQGJ5WKiIKJu9n5eQDe8XE7PCWMdeb3CcmBJvaTBmAsa9gdnXkt9MuHUBd45cuHvSPjuU67PDmM7dv8HcmvRj5HMsA7v35ReeSajoKUlcfm
M-BXgqR4bkCM7RSbyYwAsNBqa1olkJp7BOhOSjmYOik9uutOSjoYaspXguQUPGjVDPWj9reKB_S_
}

