sprite $image50 [112x86/16z] {
lPY9SkCm34CZdo98x___xHwA9ui9LOpZKOkzJuXu9kJsSKjptSlZnrGs0BR-bDrgC3EWpZ_XDbVOKy0-VRVRj0Fs4h2LxmPdne8jtsUts9kRm3W47Df4vCeO
nuCx__D239jWep6MrPe5waoZ2eo3m2qPvN2CFCr64mkCetO0uIiHJQ6kPKXvaH0uSnkDaSkBvL6dnt2Cd5Xs98nRnbX6bHTXNCPYP718-kTe0p7o_u6bT3Jz
mrZeR0dZT1CSklpBFumkCMxbm_BIVhY0ySFoodvbAa_DreImwUlTGLskW-lxxH7-L-6mfZv6R2TagZYr0zcFZzDaJn56-kSuawmG6Ec0GFOJiGKO8q1-4kDI
SO8-foI_QUy__HdZKi5-xSxK5tXv_OByt5UHkWUV1nlvqKtL0xVFhwUK_SfRR9KSyqqranzlOtwoQk4jfFdQ41oRn4X-l8tv4S1xRA_vEBRS2l_aONFVZp4s
Lk92tPPrNPUDOiiOKVScmzBr8upjcE92hV6KlE11OVNy2EFRxudOn0Kl_LW074OIxqNYF5Yk-I42xkmeObFdsTUUxFrV7KVpS_hlH6pYF1uzmKZmusX-JUY_
5nMwKFLZ1TFoEDZFxs1qTPuKPLCqB-5eVOneIkTHRarHuKq2OyaOsmEohPjyJsDmfyAicXon_rvqBa39v-c2EnNuvuMEetwz9JywJzEERfHDC7y-BrRn6KRs
uvkXR5-xEU-VVOHn9Jy-p-e1TlDWSC7xWCymxgSVLznY0G7kUDi_wphg2xNmCE4YolOZ-rt4EFNyz0uuUpjD9J42WA5XP3zOKegIVr51EGgCMAVvhwPvcRHV
tW6Ur1sKey0eFcnfKk0uLyTpAe5H--doIhawSewe6ICMvQTtW7EbgJH6E3gw30wlduMVqXZHbIgld6iSlr0s3vfAO1IIu6ZIs5hZvnopFQIZ1dSETzHpb-OK
gjx63tVWTED7VC4bZ2fA3UxmzS5I67MeIENL0vS_oJNLMnZr3fp3KSsJRc2y1cvX5zRA67N5vHr09zSuTu1q7wFUWLC9t3sCDy7TntXf1nAu-nZZIdbTLTa5
HlAJvPN0QOoXRwguLbxNjMYCSQ6yX3H6P8p1u7Hv3S4OjtRWFaPHNZUbRwe4hYa8t5sj56f5ybFbDH1Z30IdAyx--uL1bDTGZ27AQuWsnkYkosiCHbu70YVA
Qnn6NLxZCN9vZP5-uOXnEt3fXICakF4Ou_WbociuHjVWnk_6NN1_
}

