sprite $image360 [158x294/16z] {
p9RPRkmm34ERFHQJ___TEyQjkt0M3OYmC9yBupGy8-dZoepxEdnqcc4jjonzmYtbCrD_RDDUlhADVR6DM_cLTUXAE4f7-itbKVQfB-4uszYRS3tfDomboTAD
S5tfDv9mkdx-ATALVYHSbhc3AIBevvyY3ltymd6MeOCf8kXd4iwhdryupZROrjObMJeJZZEwrvQUm37N9enJH4ySvpdN1ozRRykbR3Uw-Je1fojBhN07pHV3
517ooHRIUlCBLzaGmdNbdYA1imOXpp-_S26iDxjmyPXDrszOtC8LNRzvTmkdNrUZMpX1F-CKkUwujmkdw-UV8e9-phL5KVNphor1F-lQ4hCCNGd7sUS_MLiw
tvYMwXSkdoxJl25ymkbP_fSQ0C8cd9vOsik8CAqj_S5ZGn2VGJZLaXjTApKgdwDK_S5ArpuQwUTbovjeTB_u8WobIcpVTFYfdtkAv0yodQ2VKJYcq_GBat1C
9-Zd4kunNQwVNxY4Bj7FB1pJhQ2GVkQrnQKoNG2SPBcPrjOZke98-1uzvIkLwH34b-W7xnHXkig7H3-lSA_faDORnYcIq-LyhYcIqnq7aEjdMbivtOd8zJEj
hPmkIecNzSO1a74MuPYk0RpYg_ycS1wyFlIGSDbljl4zrAy-1Q3zXRrKfckVxri_fgFhobmgqt6zJ4VpnLqgqm51V4H7wyrNAjErH27zY8xMcvUDwLW_fkFr
9Wcdqx5-JCTyed0w7Ul7TAoVNceUC1rOFw8JzMCsdOxrgtH7Sbqfmkbqh5_W5Pyad4x7-j7NI_HBIzNf-3XftZ4TwoUKAj0HtpTTUjmBnwzAr_9Dbn_tGga2
7QVHvSTzmcQbouzxH2ASbmx8zUCfeWVnFbrBLczIgf7kBVqIDYTTHAhVLN3_sZaJNTTj68WcjzbCql__kTrqKMSWp9rKjHvPG6xVlXs49w88XFFlAwjcI_D8
eyFR5Vcj6NJkdysMgNHwjemyEZrRvjEXVZNe-6nPZWxrgqU7-jMZG_sAq24Vb3UNJi-MuPPEn_KpZr9qg5zgdzMpPHKwv2j8D_cEOgNfjWfqYsxHBRf5j-Zy
Vqgtw1RTeelQT5QPphRD2djdjfcLeyENhwftm5VFEpFWgqJNk42_YjwrRofwPr3UIdI-6U6huntgLuYk0I5cBU-shhnbAWklspjVx7jaqBrGEw9Vk7ao7G8X
vhPPCbq0469QVEvTpA4p_hO5xnBeEg1tp02s53etKbVmBeqEWH3JKxnxmBk27ySPtjbl5tBxF31xxo9-1LtS_uf_E9Rn00WnxTsxS9jFzxf-fonioDU-GRxD
WWn7S-Z2Zh2FcubRLDl-8BFb-NHXRs4VzyTBl6rZ3--RoWGwN1rwNbiAX8bkYv_gY8FxV3hu-EF3sdUC3p-zTmVtkNIu3-OHp_TFRLBz7Bo3b_SyEbn0j80q
0-13_MAFSAVud6wygF6sUqpA2xTFF8qD-CwWY-xpjerEyFLr1oxW4tIAZQSPs0_bzTXTpvP8DouSJpFeJnUOUiHiEKZdNL61JfGt0jnYiwMcqyBnD0FEXw-e
qSjCwohnNuGZT4G_k7tgsT8CwNJR0ZPEn_Lpl0KWKF_kZd7Xy8cxE-4ZssxWNOTf7fzx5oPsV-BP85Xv3xetLcUp9VTEdo8ypK3m8Hq28MOZZu6sHUZqoaHx
HGpPZV0HxzGfmkdqoaI4lNUh7sTBxXqNJj39yW9TiBhoqrYV8fmkT7dDz6nftxDbZ9uYFCr0yxa-xiosZT5nuJITgOqOzpqwlhvhe7UwRMcwOu9b-fctD8EG
jwZWtd7XDDrFV7wa6QZP4hoJmcawlZA1dQpDPdgs13ebdARZ6p589sTB8rj7ecr9Eb9Ue1EN-yQ7tcdXD1tdGxeFPqlt62mgfoFw0PsUBS4xqhP6wBX-IATd
o_0OB2gdu-L5Eg6VWNVa51cYu-L5EguVUgU5qtHo8mRev6pP485jGfe1w1UxcvhTuFR9XHkdu_gPHRZcisFgSIpgoNIedyC5WEbtt3v1k5bf1aRI3AX-xHwZ
szOu7V8TTE9oVz1j85nccW7oDJfIrEaR-NgsV3z7F27DGCoMneewd-xpj0NpZAtoa7nj34bCCt1HNazFC-1ydfWNiAdPClOqEZrRPcuAwjaocOxFblbqfBp5
Tjwhfna0NnKwebyvEjIl7frxzJG3u4kcqxDbcENJyTdIzofqo9UR6YHdovLciD8CrkxnebjqYsxHhJI3HRVe5jrACx01kfLc07nLlJFWgvbcO4MzAvjcGDRT
y-duHan5xuvlIdbdXAzQYWRmbV8ECOkcQ5HEC-W_yvUTPc0RvpFBejDhs-qxDT8CUapps7Ffq3l4Z1ff1aI_SFCaEifNAiqW0AX2YaRSwwPenEjwsKGRIqip
iBzNtkyc5ZlRoWcc6TXiEh__nKRI5Zhz_9Uc6SJpUldd-Ne9FcYqm3U5Rliws6JQGk_TWJ-1pcx8flKpzExWFfqkxXsQr6_hl9kIPe32uODX7pf50_autRXm
GZzo-qJyi-Yy2SUVwmFq4oaQfwOPnEEYdwzUlpv5WyrkutJneaNb-kaK3UJZTBfjuQFrKoaQY3bEvtU9XFer1fQYmPeofzEdY7veSzisVE7uR1dX7kUT8be_
l7q2aDvZr6rhyBd3KeT_Ebk6nsZR6j6llHXFbQ81-sGJX2FwDRgRID60VR89mX7zlkdkUhQ4VRA1jZMeN-n-kv7Z69RWMOg6RblZ-ZtzSRdSm3iJAHfosZhv
kNsOei7fTDiQVxviB4L3jwsp1DJ77QGPJ3X5u96NUvAYCVCKqUrjB4N3RlF8FfyjWvuYyn-utEiKZVd2VJvRWdTQkFdwuV03th6sbQGVU3TTE7sx8hVFAMrh
_7AFAHgyRQNeXoaQ0srhQdF333ToYgJh5yqxSefaweUtJoV2PUfdthmZqrQoVkqMa2iSRsv_dI4F8bosVetkKl6vMQFRBZMVk_iUpr98gD_9olq1
}

sprite $image360 [79x147/16z] {
xPg7RWGv34DtjfkYy_z_UsMC4A5ZhDRnN3-beUM1fAN5o9ZJMtKhrzDXTNa2U9oFWPqVG2a5k6_hiErMK5gXt5PfLy5suFEovFE9dQPQYN2xTx2o4g52Kor4
U7aQp7YASB8vl3p2nT1wn_UvviXuzRnTtvoe7CRAXzfmFZI7HQq1ACDaef8ALg8emsqjj4-OWDUbq6eaRQZcI6iFRTI6MpPHkKyVlCrylWVhV7g4qytnUl2U
UzDStmoDwU3XlbqB85uMMcu1KGIS3yqho1A17OiyjBmbMI8-WSb4vKVLS0q800kXiGhNU0AQ_3T3gwtuZ5Q326T2-yGXq06dVUuWuRxo5E54SrJ7aG8gmZcV
ZWjNk1yJvs4oswP3HGO0J8HckAP8m2RDW6beZdDWfJASy6cuG16mqhicz-au2TmZPCCPC8SvpXrx6wQXESx-FoB8Vl2Iq1pdm8XAe0EQpmcSJZOweFcSneqc
6QnPCSOu2YY1vdCIrvyoI2xWUXxh4iw1wpWVl7MS0zTnvfYCDPm38zRLYHSHnvYTR9Juwt3_u_x7uM0SSAmwu51r4hY8C-21wWHSnpKOTYvNSLBM_Y2EK2V7
_Bawz5PDsoIEDQYpaBhuiJhU7WPRK_VSJgTpKQUuEW1JEE9nFcstPt-uAk1z76E_dYbHIdSUKYTWZWkqHztI7YuTuBEIuuZFFR_emKQ0O7YS2Qx1G2tl8I14
ipXVu1Y22UT0iwe4-3AqwhWl4LR6Q5RuAZJ3cK1MPISOWi5NFeKFm86at9fZllGftBSLHsqZs4XToAVZI07bcE9z0OwReyDztqY2rDIwkd5eZckAR2D1FtXI
vw6DSPt0oi7WIPqrnmZdGEraNu2GEWzjZFEDfE7wEI5feIKuHQYPTI225bgEasD-7poGL6ZJTm7H2sGDXJQ_lAC7akPp4ZUyMv3FUHpv_Mw1AtS1Wqkz5Lmf
1bpT67tmk8fpu3hE7A_Z-ZPUnhdZl-jT02Bu7xjQ-1_tFmx0aJW77hJF7gfE0ezG9-0whd_ENCO9fWYFKTU-3rFNt1waJjoVuLW_IjCYs98wta_R8sYT8dN0
9EwvxMz058R1s0zUZcEjq6iVLp04ytqsmGaMzbBAFGIC86rMCbmBpUly4C3L0J3SIDhpx315wEhalk7IqBnkUuHIPt6ImM6dnQt7gBOMeQlpZR6ln_RwXRk8
-02apZV6tcVfGXj6o3iw6AJEV5vFRzJjVAQfqyOuQ8wyl0tr9zXFL5AM8SCdcQGtnrnT2xjBFTf4JTSD0eRKARJfqcUNr0qdQZh2nYCjjDdopwwcZhVJQjsQ
us0oKLCHic8gj6II-N5TX7Y4RtR7hm
}

