sprite $image6 [148x131/16z] {
pPc9ZkGy28G17x71xdt_f_qF9utIORLeDbOxfNFkKlYg81guhLGJF4kXSEKIu3cYZUl_uetW6S9KkUxYcX4Ue5Y68tKL7pCsrNAiC5UZnLWfI1TnJRWk_oep
mFW0aAmhMf5_JndNvLzbiNe2I2jwGVFlItjXMVvzhDQFpQoR1VbVWvK5QJrMqG796s36Bu2q62lSgj5Qh3J_zxNXWh7vwsPT_cTUCJR_4orfBop9lxzkreDa
iPeCqgfUi8VaQgpi8RaMg_jZcxzkxFvVZvK7qdoi5kJVxmLS29A_Rln5iXwhkCYHzi9wa2nM5YHZQJLMpjYMz8A8CRKSAn7ZQZbML9Qxihs0Camz1IlrnEqn
0nnOaJIX_22i8a38hJqCAw3CRLym3naWDq0MWQ7q1AnO-l34O-qHuBPyWD9wQu0YJCFJsCTjfIl-tz7kIP08404ZGDG1hd8qF3K6G480Z1W0iYnnnMDiGn2u
3vw8010ZX3MzC1offpHoTxWYI00GHY_mWh4D0HPcs8K10S8tUq4TdIsDBgZm5X8ERm2ew-PhOxEUOj010fahvajZqzn99G286M64ZmY65AklEjBdD7n4tAH6
7U0ti6Bf5qlQJ_NTJwNBkFL8NUcw-Gf8sWMbQJ_XrXfdt3ywHBfklZ6s8Q3438ftgArnWXDMPjtCpx-TNPLwwgU1K0sVM3czC6zijfyEa3Pfif4ES3PMwiZt
54W7ICLY5Qh1QZf8jfyI7bLE0w5MjTWjLlFpR_k9433Y1rR26y1Sh7HihgUsznCCKHxz510GnvqtFbAiTDtC6flVJm3R1zwKzazMEXwWhfjPZln-6gOQf_VQ
mnJVHWVnlUYwcJissqzykbG6ohhsC0nF8iCeoeiKgvcE_7xAqgJe0FVd9D8A0LK4SnnF6vlrXAW3nDBwfX-DBIZSDjWJs2lgI_Ej_FlzDDAbQs_BeEF4M9gq
jXqjmQ-eLypqiQadHaBrTFnbE7sKM3Rks-uHi91PDvF6fhcJpX_DgFVJkPNorhC-naEArJH7sazP-sbNEFLJn2Dtp6ttf5TCPLqtaq1I0UMFVWAeDHqW7QqE
MsEHuObGEwF-og0lpLD0Ka4GuG-G4dEXuoDwzvEmP028fFQnPeFLlR6fWFZjIP_Enje4GriNaROXdc7QLw54SyLuXwIlyIyfsAK-OZn_X9bxavPtqZxIIQ-6
YjNTiQd6FWsNVZgawwOqRZrTqZa-oetC5UCvyYLSAsU4S7YoVncoI2gl_64uqe6LwGKF95zP6fj_W-fVrhzNhlrK-fYlrYl4OOer_pSqWiFdVom4lBhAmdBq
apx6-2gNXyeoN4cJtkvfF_-7g-tTJr6RKU-2mnEUZkDuANrfp2BIftWQmHaiPEsdZoUGjP-2zfCPDTKcp2nDvdW2LAm081JvVJ-f9uiS0UsN0iiKJmgoOfNS
VhBffB83rTeiJmOhfv-iAngMPl3KuQIaM7tqDMIHVEqdcqxrTBETki19sWiZUIhyRJ-rSC5AfdZgWziFKMaVRQMvkzvFwLVHNfZtd7gl15QH3LRvqay3f2rT
i99srrFl7C58iQh_AQ5sfkqdkFPJsAJTyzHr52gBLJbSbzRyVi9KRtdglI3yIU6DrUYdLFT-8lnJFrLsPkU05C1JPBrY85MfqhFJJtSOxp96uahN3HIHjBtx
2G_FOLu_zQQDw8dUM5MHMjgbdrvwFNYUV908F9brKwiqSUwddtUcvZ_0ZwJhHjyvrSVrVaB-ctxgBS4FfLTChPBqrFrzFoLski1T9BukLqmj0I2QVj9rWxdg
SxgnI3pPAmRnT2zS-kc7Z7UJ_x_4Aite9rqazsIlc9Hkz9CkaZkoLupUUBwd-_dtryt8IkZQJp_rr2N1FANJItC8JZ_Dph-FbTTFy_Flzq89RZ_Dpxz_nVZz
D3__u5ynJZ_P_C-NVMds-sb-_lrrutko-Pyl-zBil4lDpRz_nMWlK3MUxkJ_FbQcdvmNoIzXHONrENqf_-2zD0SHwwdtEo3TNpSsT-D5SeNqYgcidcuiakdh
HZqj0ickcxCd-oAv32kMraMSHVBjNc3XQXV9QgoucKMo7AlE1CyIbGbf-nS
}

