sprite $image324 [214x324/16z] {
vDg9ZYGX20PWH12iclT_tRslNcADFS7wrrxsd9pzHVb3MkY_hQBzI-bhkSJxjt9v7HDx_rNEhs4ghJzKAxH_QG-bkvkgznxBwzODPNrGnjisb0RC_kqb_PsI
dTDyN5vtJlDnMTavpSUbPUCq7vVBrca-Tl6-3RLnoal_OEcEQGv8USZbYsMyHPhltrxLUqR91caEQ2z0GsqrHCdH1xLpokjvvBfS_WdLcUvYmgk-Lc0bf3nQ
bNzSNU6g9IwlUDMAQsYCLRszhN6rWbNzOYMx1AfQvlAALQswXbPWggKk1QfMNaF1g5QxZB4gOChdgo8hlxqWoQxdwlQg01LHMvs6nW0L5SUtLxwAg1wBhs4N
W8e8qLxhLLJQwcjevNuL4Vjgbm9KDxIN2q1rGtiP0rHK39_o-IeYxlWXAbz595dNqDievG4gefIKTnc_l1W3L1b3b9NBLx9Mxb9bf7pyt7hR4DK6gjoKb-l7
Cgy0LKBAwpiFcrRkKoKCKU4in0VkjQhyzfAfXG4NW6gwlSOPL-gFVrUdV5HbjLVyfFBp9xQ48IfDHSJ7SqEKozzB7QrSRmqeG4NjdBY6yIF6IzV6AGzG7VD3
bF4u8EmgvHcWcXoYl5w4kLF249MfcarvljWeyf-VUjXY0b1DfRoEXoIEg7ZK0DLCohiCzaFhrFwUbVjLHDpVTPaFap6YOYb0zT4XgZsnvYi0rOU6A8ieLyv9
-QWwdbDDjjSm_kGFKaBAfwgU_oQg_BYy3wJhAwa0rNFVHDK_K2OFny3gmvG7g6X-Y99Vg4TIgSsl9t-0QZ14ZUuIFv9OBU6BtcJLVCeRXGg7D2u1gAQ7gFb3
Ykq5K17D3L6_3YdxEIzVDJz4SJoa_FS6IrBDjrThdl-Sbwz2FkUjL-6VywBgd4eOcy03d_EYwd2UK7MQANy3BMt46wXdIrFrzKiRFAUYOgTagN0xKJ4jkFUQ
eqBkHCKCbDDBXWgx4nMJlPqjIqLac9segABYXsIfYFjgbywfYEhHEK45seaQpnPwMibGtTHUFAUYOgT-RjvEbzouOIWAi_Scc-__kbdaRASyTAYvA5pnRzOl
7g2EO4LHUIEAAdPFssJLEA9Qz7ZDrktMxbLGyUr9Mvwg-lN7YbDHyIL4r9GA4IMhKY9gGeM8abLP4KNLwEtjNY9KMH4reM94wQgo94JKX0eH9QWolrZ-QnKZ
Ib2bZjVp_9-A4JMjkdsNgDRxSq-hNX4bg7B6gprzIiNk4LGPbwWVbWRLpF7eNYLLV4JnX-zRggiYeZHLkVMFb3HzKtLNH9IgsWCZwkdVLztuZ2Ahj2rFaw92
HCcge2tVUjTKY2XLjGbR7jjSLJ6YT9L-YO99K26Y99KUKGqUGOM8qbH2HD6agnXHWgfkKaHne7GLBr62Ihf4mHIgUctvLLUz7r4Da20LBr6QQluInH--U1Kd
eksAwlrB54rZrIseS8aILBDRllMUe494QQhnbeSfGOM8KbNZBO-1ob4negge6aVKq1IlOaJfgl5uzPweOaJ9gl5u9QhuhkUGL1mlJHLwF6hF9QauNeggryZZ
KLia5VzcWggUpxK4gKfjpncbAgiqL-lz756g2n5bLBrsQTk2LA-8MlsgltRfhs-pTLQ5Y7AhodBzSYBgDQb2HBbLhrtwxBgA4ULNbRAtkgagH9HHnVo-5qqr
SuagTKrG8R-VKrJn4kLKiNjsKSLBb575LAbhY6guvLkIYWyH9QYmvUqgH9IWmYNAha94oQfIDaIKIuM84bNuOhbLXOXIL1mlimeH9QiGKKOL8qfL8QAiAaRK
jAfT4vSeeueH9QeOKLOLZqUYYX7bLF5uj4egpchVN2g--Y2Y95Kfk4H5gkgRgckPk4ILTiwfzklPIxoglgr2HAcg5PSeg-eLKKkCwZMhr-9NCQ9q5IDgh28g
NiM8qbLblTlkLBKJ4IMh455E5IDAL36Yd2f6bAXYH5bLl4G9gcLmYJAfU8aILVnEb5d5IvIkmfQtgmeYIbJXY-LM5I9AKE4IPLSXecGL8igeGaG9AewNMuM8
abM8A5LroQfNHAso2X7bL36YH1KZogbYH8agHfHHnSNSzaTJCQ8sGLKNISN5t2z9nLbjWggrKr7nFVrQ11NV9Vq4dcqFKzs8A4srIQgot7KDKfs8g7HLmxRO
whM4g0v4LBRgfggKenqXAaIKNLNArVO05IFAhofhlLTPXO_AHXKIx5fq5Jyg-rNZyMh7h8eHPLGnmTecgPZVRJUgc63t8gimNZuL4-mCK76y_Ag2Y19LNtsn
l1M72X4bg729igiGKRBgvuXw32fkULs5Y3Ag456o2X7bKd7IwoggU8cogXXHeegNg1pL86emNfgA4NKOLPpqkcagNg8seugJtaKL8whRL7pFSoeglXENAAEg
dOWeJLMUElMB-YrLVqTr8A9K5IBAgK94gIf4b5E5Y59LY2Yd2X6bgX1HWQhdcwgotlSggn1HSQhhRHKYIbNnex9JnOWILRn4kLJFyLD4YIfUekmgNg9qrMlB
rzMYsWUNA4d5yRAgU8dILRn4-LM8A465IvHTXOYILQ-8MiqgRdbTXOWogNY9saGLBr5k5IDgNjKdBb4s5I9ALN7BErKSBr75IvHLnOWILRn4IQfBKp6YkgRY
9UeKLFrU1HNVtczDnKkKekhzN1GLZqTjZrALGrFrvmXIzUCLKO9AR0l-kMsBK2tzG4GvVgtuPzzBY0eHPL7nJt_E21M-jE5IqRNhAaHKkkfwldBLLLJj_-cv
ArzLjlgbwreq5ICgMNM-_gbWOSiBAaPKkgei9rpOyegAbwXirUi60jSmelfRAbwYqbLbD5wdgE8bAbl5yHfl-Rwzg-8bAac5eHwCbwZY9IfRDHwlHLCDj_oJ
eNeDDLY8A5M5Y4fGOQW7uoMfkENhcgugop2YT1M_MBuagieueZGLnojRDHwlGrGneh9LuuWILOoeBLartl9raLJyWUZfgd54IIh-QMrFKyr6bAvw4559gl6M
tu9KFxPyYcewedGL8Yf1DHDHkWeHbQWQHrJRTHN-xxpHEsDKyn6bgX1H2QhPYD9KZAXirSGbYgfjLiM8IbUDBr6wYfSeNON_rCAMrrMyHCMhX8WILBn4nQk4
Y19Kk4H5glGjhwkuvNMLFbwQYbi-NAL4bAv2H0Mgr8ZILOmeNQMFrpkgDd69YbAf4QMfE5vnAZcYH1KZAagbHzGnfrf7AaQKg8hRydsNLDotBKobHvIYuhj3
LNf4wIh3jb0kKNwL7b6Vhz8lKNwL7b6Vgz8Zog-AZoX9TIMgz4kKNwLVeZvIfM_vrQjAY2YdAZwYabHxf8M7Xy6MTwaI8igiYe-eVXfK6Lj-TwWo8igWIeae
WoeZeWogb8Wog1AsVFMgzBSF8iggCboYh2ezeZQhIdzh7KHKXieGKGagIqGbg1nRVZMeN9SelqgFABDA7wzd-X9LRhjAlqGPL8PBL8BA4549AaD49QWCMzwW
IlZjF8CguRVp19NthQDBL8BACbxpgeds-fo8cbHDTF9dHTI4QkPay6aHLTzGdMx4_2LgGZMeoCyRhqaLYrzuXjzl6AYuM8Hdk4HHfMzpVqHH5RhD_H55bRxD
_LiUgi1jxe-eiUeM1igyvQ6oRtFzqCiNkStzuqMLlitzumLL_3RtZzUJiCqD4HMupVrlkw6AtUR-Y4hOveQ8IjZcXajKmZOtRFdPRVux
}

sprite $image324 [107x162/16z] {
lTO9hjiu48JXuhv8klzrnoau8P2sLNZiQ8Xzjc_4xlmcp8cj1VmlfumnHy7p9_SvNcVs_30K6o5YBJu8XJeelQrH7njP9hJEOoDBVK4Bw-c98HdfcP6LOQ5r
Y-6VB_XtBF_R1L_diP4LGigQDVYfVWXcBRwVEgQ4LgkSbCJMuZkfyvUbC7-hI9q_mOgJ8gOjlVYQkcWzFJ9IyoBc7PcchWFvkFGjwbRfhpg0qCxhqP4j2eXT
tw9kbQPuqhpSYwzdzJv5ZOp4dB9Lca9eUl5RgWjhSPS2ub0ZYto8oCNN5935o6PUpoinCaK1rIo-VMk4gXSVcaBexAB1E1mwYMyVsIfD0UKyxSZU__z4QXsp
zYdVLPhAvKEhUbwFqpbd_ONgLcdgGwjQm7fWpSQRrgtIb6aLh-dFW6OFRsbEsIfDsLQjoGrAyoNtqiNYAqgqAe5IAn4ScMYLe6vQDJCGMi_SyP2g-94Mr5sh
9YSP-JTB6tEA7sb1tRQAouQGQr-E_7aPWlhSgZbRMfyZVgGb9LerNqUzgonrdYL82aZ73zzL9TYlcgbcJQ4LnxjgNM2gILE0vrsrPbLgL9JlNRKeX5e4vNnN
BGhWo0HbMgMndXSrryVKAAdFhHABRoc4KeEWJAlaOQiC1SHQlb0TM2SVFnnPjXGNNrAsLHeZPLjHiwMQRTMwHIaTvqSAeNT1cSLNq7byff1RoPf2RiJKBRwW
6oeZrwIf2DsgUPw2Ogia9Lh5kzCKMwKeDJ92Wbgj4jHTgoOHIQrM2Sgqoa2QMgrIb6qLX_HJYgrIb6tLWYHbMeN-bRAjujtjK1nPQf9QhJe_K-UHD8LGPr0K
5_yyZ_cDkcQfKL90hrbJ2FoghnH2vPQjKpwMdIE3fkOD1QIMDSLMUIbMEacAhV9J2AL6IR5LdbcjFwkQOglS54UcgTMgug20qgAa-FrRr03MuU9BYgroKq1i
-HFLJQj2zb906bLJ26Ma7r3p8uNSJQj2WpcrPpTLCaUcg1mvCYV5nLTKYMoLcsAh9CLM-Icswlu2LwkSr6hLBSLMkIcExFO2LwlS55ibANw_dsAh9FLkLNHH
R5NH54SMRgaP5CMH3KqXb7PFbQmfX5cZf80iBZ3LfAd6aGdg-wpcxrdb4YN5nVTJ22K7IR5LRWg89McAhN9JG2fHKgjL7eeZ2vB26ba9snH7fYcsoarnP9fY
gzmKdq8b2OgjsfxLEY6FB2aWrnwy551xqXJGMtHJ9SMQD5KIH-QZCXTVKc4jlgIEhnGNNr5njKfGryrNhLRTK66rQfjAgrMIOgly54ScARRAJN5accAht1H7
fYcsoatnHrfIR9MVGiXLKcnLlQFEiqT90MbcJG62kiwggT1IIOgwczL1wxoEeYaklgBIpLVznaQI51T_cmhrPRrliGT9SV7tg074ziAElqPMlr9irIO5fF7d
5cVM54UsIG5blh7h6b5I7DakXL3NBROWAOviam9YFzRYQugjsgI0l4OskgHuYtMJuiZcUsGzIWe8lUnI26RnnTiYbxH90QaVNreLFvSzbx190TcqwexYo7Of
c5RTKrpy3Sei_barnLPjKQPLccAhDYYp-2DAYYFRecoh9CMHxL2sLPfYgpOeswfI5SLRp9hI8vjHKMpA3gLR9SgkgRjMvKSetIe_9LjrJrqEQYs-6PcVqgrw
aBBlgiSek_WjF4VPLZr6sLRDz1HbMtNE-02bM-MdTAkUe7Ih_9HkrGEKRbLsKxfL3rAsLVTKzpYsLSzzbMtLL-gwgjEnhVf4yM-u6Tkgqr3yN7ly8pCKXoZE
tkB_HN4rnTbk5Qarf0nn7ArQ53CYZhDLf5OSnV6DxDXOyCrM7HiBlZkoSotuioUEJml-7m
}

