sprite $image170 [238x173/16z] {
vPg9ckee48N3JYs-_-lE5x2CQ8NB3NhpnJcpTdUcnryepgd2vGpv7CpoFv7B093z_uBLHgXAxkTPJSZmK3G_luaR_NBvsWIloh-wdKq4JSd-8glFeEWtozUL
JPmRWUZ7tDT6GLLuVyoDJ2YigdwkV7qMM4s_vKPIi0Euu7_3TN9Fl-2-uZg3jA9ehxo91sWl7oOb9XwWlMOl660Jvfwk7oOzF8kwYuiN3vDIi2AYtj8oQ0hc
EZ6n5J5sO1bKPNUnuSH6oxWBAxHNB5-NuLt8p7hjrf_iAfeBk8v6oqoOMm4nzsaX-yl4H10HSHKX0jGVeNnlexrC-KfCrBsKc7XN97LxbV8LrycQ2kqkBX4t
j9Tm8nk5LSF5WhK7I_17PN-9uKHHeLLuYKYfMrt9NM4uKOI2XqGaf4WqS4gflU3vhfCx0jv4LSefTO7oDN6afoFg7CaCeyh-z9WuHCj4kx0CuqhkNDSPfDKz
YAYjsnpo7ylNd5YmOxZ2fXt9Z1lhiYn_vWrdkSuc6Zgbw5dolMRLv2GuCKpghjE8UxXgrOhUyw5DS7gOr0jMf7UmqkeG8EiYr4vRTthvzYzYfOFLjp6MdaSH
jdTy7hms4z3To9mod2WgBFZEApy0XPUmJKaEc3bRITwdkv5iCftsRNqVW0XLk9rDXDYUEIQjpn6pR59tRldA0Q8DWvbOH5Zrz1s2NKd11ZcTYIbiH-69OTAe
VLsbvLuuf3-zMezCsmPWT8hDwV9VT9tTQJ_hkFqMDacDvhhPHNX--RhKkt8cjM6Nxs4luvj4RmyGqtZvHllrJQoF3_lXKDIw3jLDB3MnRMS_MhuvcC_7nDmH
RO18LKYadLBlheC0qLcp61VQxGp3vPlzfsDYxWc9nq-fpNLgmMvBOrBBcyo_3fCsZLomC-t3CkaB4Pdf4G93BjzFBouU9yBaJ4pCNSc1fC4oxhjENMOJryUo
t8LgvMk-NRxolnXQMzPuwUrCJct1Wjl0oxQDxxSgO9VHNj1_AYRYo5XH-jRs2tels5HP8SeNzrVgKBj5IbyDavgp8-MEk8Ma1XjVDt4ehYE3YCmaFtAac1L-
DKpgnpuozWm8YFU4ByU8mzi3AfVpATrVOcI2w7nCEQUOdtbl-5KtylbzGr77RSi3cWXxCH7pvZw1cFBJJWo7ozSTS9tHXXrau4BgmhOnCRP-X4pH6MEiIvAf
eZVgHrM-LRucxbyvmqveb2sdhAlQwuYGv3WZlDTeXNBm_YH-idoxneQq8GZf4ns8495M8UAUwxJ2YefDfZH97lrMcEo75cHgdNJWobbrdHH2I7_etuAapPpo
2s-U3vC3qqtaRZZijzi283Io5_NrSFVz7jrAPbpwHfZi7tVzAsSU6Ku8gx566W3bnLbWnZO7kXVtzLFbE_GVFoL1PKkF32VkAvU9oQnKsZQk-rt8JG1ApV4y
Nxv3vpesUV3jttl3YKW5m0eu4QoBczy7brbIbjzw1P1tPgeNr6DYdrOWHVpG_YOA-0GG2qqqibwjI4pBl_GANWkJvd3v1lYJSFXZGBhhvBASM_KwWdSXFlBa
yjGh6DGC4VteYy-XxphwcKoZ7mDAxN2Yo2oBPzmyXhAtSkI-A9K1Cswz0a7opZgVviEaJJ0Yxbqvy-vmea6mnLFAkPlT_fkDTYM8tbGKnc0qrq3cn-aCO-Lh
8en9s1HMWUh6HCxsGIScuX8avNX6TC-zGghKBhYNRPlztwnNDFfTUFzGrkwSyRLWnJRRdPU2Zxa48ZcVcLU4z7PSGR3MMf_bui14PEPrpTjhFccUO40v4CAe
Y7U5QapKalQDcId98uJW5zsCYcvCsTpt2IF6HMYVssNWCGWa9YASm-qF9rhXAW1xZuUo4n8gZzRM0cmXt0PsKGik8qA-tOZ-WXTLNjA74xh4Z2mHoax8312z
Srgpa5SYOfHFbmHMpi51ra8hkCTu2TMOMDYDyo7uTui9QnscQAK7I6u_g9lr2KdD9fTVBVRfQNWJtug8_fONwHaLbPX81RwOZUuFv9_SH-ulhNVAepMLRCSH
DhSgX8CbU1DQbRSlhEgw3X9XCZj-ok2jCSO6O8uoghXncK12Ap5ROwFqKGSAzesM4E6GTDT1eYHz02aluDvFePUNJlL4Iag64mEK92ckCxo9HVIi0xZxhfDi
CtPJvZD4267hzCiYkzspWb0v1uStiT1Ey2h32L5kHouv1g_EPwoCp-yR0H4WfvJxM-ZsrvjOQ2TvinDQn9sHImvsj_bU6tXyLACdIjx8BB2pXOPPLThZvOlA
826xftD4pCEko5PRN6FbDEFiTiP6MGakVI6fi7FBgtyc91Yn8YbVP4vABqeKZ0nscSAT6j7Nutac9jxUH3J9gtycX1XbRcZkymic39gVqeqWfGHKsrNf5U8M
4c72THJQALxzCo4e4ujwgcmnD--i0ZDcq_GAykoHc4WtLJIDsnyabENaBUOc0aqeXxlTl6X9s0QNSTUvxOXebhS_1uph4f6SCHOO8MNGjQuzRMafCRv_-6RS
ONNQMLvz3YYyk3gCiqOYD4QpViDxgrZCke0nMA53W3JlEkEqX4VBLrYGWYnucRHcRurq2_O5bx9zwXKOj-74XEiCqSwxaOboNaCA8G79Xx85IhaFf-IjCIuY
CqsupW7Q-V9rwUabo0j6J4Or4tbK7Zusd3X2cnCSuzK_O8plTxbxTOYbV8uE9mxHklAMJfMlQyRuQg-WIPjlmUmcxjE2-Di7orT6eaqT1kj2J2cspT74SE88
RNgScPyBaqM-hKEltQKUTPqfMXlAeFfZOR88iwszWYW5MSNSz8hphZDEkxfyBXa-puR9jXT4PdfAVoGpAGjldo3p1uOJnsZHh7cMA1cOTzysJCfl4BJc7b2V
RyrluZuj-NA9I9HnlXVaj_9LvbOpmubfsdLY7R_K2pRrAHFPYU74F2t5rVy5pleNSiJvNZ2-1gfe9bndZfQ2u0AixeiVxmMpbntRkiw1c3XFItwf9t8qlg6T
3PFYDSGGPSS-nSH38_5vMdBLRkEo2kTxmHiAahZHmsB2hElCqwv9ro9LnypV6EKehZF1Ek50k1tC66iw-C8ePo8c7XHvKDA5mtfIsKUFO3_aHaqlE36SE2Jq
YuduRhSMQe34IkiMywbHpXOc9rpda4XSxxra5r_s65HQJ9uKpOL9O-TTProbYgeSj011Vf0BhS6ovDw5FCyh7p0MnQ-oYj0kJmf8pv8t0ZTQQDwNsKdiebo3
VhLW6xsMBvRpmz56wsNVVQXy_td1RbBA5rA8-4HhQwa9xhmRMVjFNAVCZ3GfRhJHcf8saf69ndoO_1URM3emJIQWsjlVQKCTRBWFkT6_sCHXwSaahK68bJRT
lyn42FFB-szSfo-RbQsSa5o1biK5uoTvl-ywO9S1UNZlxTtwTrzuxBgpmSo5oJCBjkz6wmbk4CifLG_dL6Yp3t2mV4zmdOviMxxWBTQ2hRHXfJNhAJsndKzm
7KLwcApD0jQTxDSlYlANjZFIJ4nqor_B8xLAPItpyg2rAotY1Ey9hZDQlkNNs1Kp55g7w3F5nKRibE_PhdEuV4cQbrneq-CjC94KuGci-wvpm8rgzLiYC5Ap
qHZPzlEyyxtEGUbX4fDt0Pzf4J7PFLp24rndGcgO55eHbdGvXpllEi8wAPixj2dcCdusG1Eyqwu3RlcOFEpHndfufvbxilc2fTc2xVU2ACdArTMFjH74dF40
x-mcdYjOtOrUZYkRxps2SQOyKAULHdVV4sBYd5nk0V2-jeamc3BXYFKvVNbFxdMcmgGerfIH2wrJ7nFX5ro7m_95HMMGOr5eIyu8o-9jKd7nt9Wu7oOfbPBs
Gkk8e42J9Zmp9iwNhtZG8hIXlW7x5qSdnCGf6G_QnO91abR12csVbqvmdVbU45EKKwgiBVaxBQBU2vxiElDXqjuToDqtjwdph9tZweJXn8IqUq43PHWBjN1D
lG3U6rrD3YTEq6kOHAfRMTOsTEx9-7JNcH_bo4Z35LgxBcpKBuxuRDUPToEPjFlgGAQ44J2BKsdFZudplM0r1g5rK8eO5Dffrpb_E-Vw2IiZEtajRhHAiEAJ
XXCV7UK4Xvi3-VkxuHQ3VThvuSGfxkkhCOL2kyupmb842ksKwvnUlhAe2Q7iv7e-GLdXfD3EkixvvRjT9zZw1TGPT5HeptUT-LvGLi7JTayMpGpjoQxJ3vDG
NrpUxic8y7ZTSZmTgnyc8LYN7gt-uXEWua1NBDX-c9ID7HJQAxdE-BM-qsalMx3zC8dPstY0baw8YVCN2xfuO3Xn6PaqHuj-kPHiFavBORcSF1oWrLpd-kNB
5uY9a_U2VLefs0lBmIYj32UkBOywhUuwrrT4XNOY9bugJEgqf1JipvGlNzvr-cu42ksSwrod5-I9aVZrmYHF32UkLxxyamMhXqcXPN3BJyia55fndP-MovLM
Xh6_BW_4IapyuV8zfs3_0m
}

sprite $image170 [119x87/16z] {
lPO9ajiw34G1hjXq_-kcG8aSZKeAah4z_NyIbxSs6dW4uQV2HXb-NOM4kIVuLQKkmip25U7NX8sdXCklvSjCXzpuTrgSYUaaBxZXn_FjmlHDUulXeweiJ5VR
JoUT7PeRMvVqz35eZig-QN_oKot6neU1VVDL_IHCXOKFwQPV0Dasd_z0YpCnhqQgRPkfYCXu97oII4zlpFSyGcfcso5JKpxfZUTblGolkjakLG_v8g7o7cWk
e-lH7jhChhOJfjUXkO2wGXxkCfAT7BqEquBcMkrmM-NANbtXYt5z5HeLEebLpo7Bf6Q1_HfCUUKccvmxgompPLFPosgKPaU25iURV9wtOlxzy-6cWqzLzUT6
4xEegZyeBxQuqccJwoZExFX7Bq4c6lugPT1sCIu_tkIoG1tM-lqxcwfNpopA_YEUMnn3So76Qnmop_kSO17j6J7tyPHsZ_mXwHWQ-guPxpP3dlEIs3XviWaw
krGRm0DC8JGtjfUGHtJOLGYXg172B56btC5K8Dxa8a-deOSyVtxrfdR8IWcGk4yBVO0ftEHYyisLzRHoc6L0myey7YDW5Qa94JB_TulFis-R7WqUq8wcxHj7
9ZIc8ditMVnfRsfc4TbXgly8q_d7YOrOzycTI-O2JI-vZe_iHXt7Jw5M6q-OelFosWgnjMJCTKcgY7LFDi7gPmNigZq3P4nqQV7JvGClSUoWcajj3_aCpOYm
gHMe8dAy8kFPwi-syUo4YUJXyZ5VkORi6WyM1JiqJ82Zu2BKsfxqV9OIPE7UMHPCzVRouJbSPIlbKU_ycGSqdcb6m3vY_FhQ13K1jD5L7FcBZT6wkNoChb-b
s-Ly46dfWCQbt1ffywW5WKGERahfqi6p1nZVFuPU-29Xp-n6weKU9Ujfqqn2ngQ3h4ve5UgqmsHg3TA8kiWQ-hklLxqr5frhJawR9gTISkDT7NATKMFXGmrg
zwXrReeRKr_Q-c3CucAMy-Uh-pFBqUrS-ZxL3OeiDZ5LiJdqV9MCeT4X4NvItvigmsSCbH3nJ5epr15r5-Q36pNZOrFSfBWDwQ57tn6m7ALcDgu9CBMlyQME
W4I-TUcqwEfzKtUPQc2ixBth8jmogRX7b_C1XPWw5myVWTRGF-OxRIFZjL1KXGcXcpP05bb9co1KjGv0CeV-sNJQnWMhfrOyGeBC5I4nrKxhQjcWgCV0Ga_G
U5Cljg7nMYWib11pLwbvB5tNtBfDvM_GFDhQi_5QAAeUAyi0Pm7WT6i0pODjnletcDO5V4vr4KVfzBi2QEvj6G2G_zfYAND9rdrgUau9iSlQ546-jxP5Kh6u
nMdiqtqLITvFBUa1DCyX9pJblS4nJCAdg6DedcsDeFY_XJHeyRmPK3e6A8RcsTPnhqOPgWKKhmiuZG4AeBcLdNqRT4cGTIg6YJc0vbQsML_Dp689LG2IHiOw
MqmbWEPUrY7nuPkW9H21qbJ5D4gw0c09eBalTUDnQos7IG5msxfvql8lvsK0pRsf-mnX6qaRbMO2rHeWecZSujn3qwkimPSIkR6PgbTRWImbTGKmXT1SIwK4
tvIF5bi1xa36qBL6BVxVfae6k6gQP6HefbW4IWzQ_5zDjGftmWCcqeAga0G1YbbSSPolgoCyA97jQpTXWIo0lNEceE1_XkPP4oOf04szLiBWsFfNQ08TC36h
G1bMM3GmZg69XNqwG36js0ZO_cuSGXFg35Eh9WW9eMd9jApb9MZY5lkVbAr38m3ekYGlGVEiULwgaNks1grZuejn30qX_ASIpUKFq3lmLg6PslALE5z-p3Tk
iGbZO-XUjxN2NyOHD1L-g2exJAIOZQ7p06mgskG_5_RLub8yQo9O8st1eVI2vkL32D5j4zUaX-mPcWAlQSAK-aOUSWO42Qgr1czHKsjGCZJ39dcbRAz24yDa
_cLitIUQPxNHeVIwiYZHe1ZRwcqCpUkgnsRA-N6ah2EyNVD-gLFsJcZYytBAtWbD3DEKlHEQ6APb-m5euik7sYUWYIyV5a3peHPR0CsdODe2Q3u3amNGV2hf
5pRv7m
}

