sprite $image321 [399x290/16z] {
xDbNSeGn20DWS8Nx7pYziztCBqz6ttFALYCB-G-gMPKza4v_CLKsGCC_T46ZvZyqGQ9Y_eiLGI4T7WmLD9vJw1EBgfzLvLXKfbymYm0mt0Rm4SAXWHmXLCrl
SanlmaRa9aVq9jJzBaC066vt6I4Cjn6WDs4ZWXmXr7n15m26svr62CFjHhq9mosWD-7GG9vOLCmNe7iJXbly2E4vrMsZ4S9mgtsV4S9mQwAe4S9rNzH5R9lU
XE5Mmzq4Lxqpt9g8AF0Mmg4HNrVRf7hd9Lp3xy562DTzRl9AWTKxrtrn1fW_faecDY8QJZbSRyBcrkIT0gjthllYOJCsgDwvxWin05YzSzqtv0kmUkVGYC5e
-9eXLAOlaM-Lszj5clg91cvlUKx5IzpmTLCPRXyNAfPrdU4sQVfwZiPrtsDgnXzbzTuyHoY4impbkc_zfk1v6iFjlShg4SZglNaQax_KCyt2TTzQ93LFDPID
oCrqfOta21cUoYHIpsQLG-FnwxDvkgaCjpTuPk_S5jnMOIWgG0YG-F_lFGszpFZ4haq2UsWcwwallOHbjeJ2k0uXlI7lYKX7LlMbrRk4HE0AvQ7ANx24X385
Dxr4YS-G4e9lRW5PDJYj9DpjjFYUYFIdUHxYOlzFudTpUu2RzNScziTUat-1h_kmlUSJ9YAxpxjC5JStmJUte76h3Ca_AMfLNwRfZMKgKpev-Y1PhSt67k5T
D3hEoGE68R4s6qSa_svkBp-VydHKXOsDFSIzcziFHfyxjylhJcmq-9rJ5sTwp-usRJQGetTySmly6bkUivkQZHSOlRjK80oTacLF6xZPU87HknGCGYSy_YrM
JbHhjHSOlND14SOz5zdTROmE6-jUMVIvm1Wtq-VjCBZMXYA-lLs_Q8mBx4VMCTOE6qkFthaWSNHAxDuQNkilR6X-uWa5IgPpNE-LDgaDKws0AukBJqJ69qFk
Ufo3zSRKlj_r9oBuh6h4dlAJQiFqNxzlmWLEfYkuwxqfNzmQIU1p4_n4P5ONaoyV_FQtHlO-y2-2z-xYfqr-yUOMdrKDldpmQ-ZPt-FpsYKabYyXqpLSpy7F
TkwIFFvfUVtc5dyzCry_-Ec9YzvFcyF2pIq-gnfyzU1d9oxQrb0rCy3S1D3SuhDgFwtI_i7ln0NvXmubyGMQsw6vd7iFVX9e1tvqTCBmvXOFNITq7Vma74Xz
_BoUFRQvnIFKmVM3dmGwG3ks1ho4I04mR70g5mv-nouu5_9FZx8OM3JmFDICPtzmy3jsuPkokBCrkWceh_lm27LnTl1B1owIrGyKzxO0V7CBVTBaRmU_pExG
HPyD_Do4on9G7-7eu7VHHQilGs10Smj7g9FzR_okkJ3LQk2t1U0d8lYgk3tuQRpceln05tnRW9Hbe2T8lIx68uiM3Vp7OGExs8SHpUtwMPMFNBW8Sz780J0H
MJohMEN0XK9TD99RDwSW8slsmrtWFqSeg-5e57WNMtXuSuid0roWo7xmH0HFNCS5Tcx2PKNS5xe8ycM95N9PaGntiUtf9XW9WEPsqHCKvyikSheXV2Fu6qID
47F1lgWtbZL8Tv_TZNTnj-oEpd11Cgo4y69rstFApsTLBZUot8WXj6L_2iyn3PF2ApUtIPZzTWlxm98Iqq8ubZnvRkBaopKu-XS80fYRyD8QWj0Qi01crV3c
DYVXS7KtU5da9o53hhMQgSvj75r2Q-Y0ysQO2oJSOBaHFjsLQvXEcvl8YXgszmKJQDbJkQ7r_uXByqShhOJmN0sHWwT7YVKNF6pPWpHAerx5FltIT69xdvVJ
45Ya5FkS3lPqw5iTWbcPY-b26jAdd0Zw4GqougZmc1Be-DUg3TjyCa333hgPjU6KM4CRnG0ksXgODI7u6PyBB7cZOL_6wBwAanukkvO3322ZFIasp4VgqM3r
2ZhfbMeXvh8OLXjceuIaCHhQazfshewwah--4jtirJ52Q1SVekHIBshum7R-u1TLefle72J4HcZ0l_xHS_fY6PlJ_Z0V5herb4ju6e1RLOdjD1OZX6YMqg41
VA77LqsydXAzMvrHGlJ4maO3_kVbhRLgYTr2IjJgcOx7vySz6l2N3rFzXUM_Ad4iS1bR7OCsI8y6_EL3NnlhAB7zftUOa0uDkApQfjKwIlGequS9KLtwedHK
ku_g7Ftv5GLcH4urx0ZLrxeeJQwjmyv2d2W9uiZb-JdLi6EMyC4qZ5mQtKeQSNfEDSpM5kBc_6nylnAVfyjeEfOMaed6fjM9aY9XwWPHgnqwblF1D91SxkbH
ujAKeh7LiRGG1tYJHuUIaEVbLCDiPI52GocD3YKZXQZL3XrB2Waq5EbUC4qyI8ZLAzZIFl0l_xq_A_xsuOF_HSn3SsghOs4XGeCfZJub_F6bikcCeh7LiR2G
W7wNurR93ZQWQ0pIWP-R05vLtgt41XID4Jhm6qHeE2CURTF-d1gl0oyaBF7csSyBfJymC-sMELu7NiWQ_x62gGuuQOpMWIyXGXF0Nai0w81ja40J4A0CW0wW
49f1W5rB0EX02X6Q0kek6q07r8UZAKH8JW5qO8LaceC3v1H01rf8f4baW0o03h0GHvE8WA81q87raMaM3b0q03gmGfYcaG4v1T015U9e6Wp8AO0EvDmaqpmS
8AS0Ef0RX6aY6I03e0CenD54650q03fmGZBDn06A1a07pWVJL38Wfm0wO49eBW6GKm0TA252am7a5407IaYWoGWWfm0wG3veDW4W0w038qHeEe2Y0T214H9e
EW8e6W0TaBa9pIS0SWgW0x51X000SWgW0o4a4001o03e00WX1654Jk5ru4k848GHCl0wy1ia40GPa5Dm7NWXcJ04G7FRZzfYGiG71DulbbCD8rdDXrO8Y-LK
GuZ8vRM4M8MWoyd8ZXfXgSIg66ojeb4rq1_YEaAqWbWhF9asf5Lyg85OAQVIplkQy4BM1oAZEDg1zItaAvfRfWte4gBwbl61q34klJS8khdzAxxWXBoBHg13
tYK4tznU8jftB27uYSWbq7EJTtDxZWSbrdTjRWDr4h-b4Aq88Zs0V3iV_xLt7rGCmm0GG_cpBeFkyNsLGUJqf2J-pcZS6TW4Rx8_6YzSPVKrzPuHSISak0My
IKQa2Vb-xhjz86yItEvw4pZtdJSXmQsXteDRR486Sz_j0tkJu1PJxy6jgjxtSzz1tYIulNq0w9tAVVlUnCzzju-lteDRu9N5pTotw4tyTzcQa06ujRt9TEux
KRrdHAm92MunzJwH-vQyIN1hgVUft3UjtltSj-bDWbjiGe9RNhtxkM_VcmItlZVnSz--UlTptxut2MunRuBblYOakCNKkmMtJSXCxbjvPJ4ZWdcJu9PIxrJk
ovlqdABKEvNxcf21tBUatYaZqeHGev4teOn84qB1RTw4odsfTohtDI4KtEPDWblgbKKARbFl5Dm6lLJkovjGkIzlGi5jwftAVKq81RTv4mfkcn0gz-LDv5zN
_E4hYnJSDY7KQAJUARWDUgdSbtgdSb_gdOBRr3kL-veGoeYatYcupPjGkI_rJkM-9eI2sxm9bVlo9XJSfjufk4szKt3RX51mcpUXu3RefN9Vwfs2szGxbVlo
9bJkQq8ek4szKxalzKwzovOteOn84qADHjw4CYAfTmfkcn0gzwNUARZDcr2vB_LEmMtGIy5jwfs2sxm9bVjIxoEZSG4
}

sprite $image321 [200x145/16z] {
r9c9SgnA34EdTrlTdV__tCSCk0YFH43bTXMSMkyQQv24dRo64pMxr-Fn1GgD3rVXCg2gW8GdouWAdG6AVwgA8D0LF3GclW2wuOanSKcXEo3XeS4mI4oUPAaL
Q78Fwbh2GsAI5Ce193obQpb0TayB1YJZnvZSE1W_Tctoq1-0n4TrBVnBG3hu8S60JD47YSb3tXYOSk3Ps-GXNOl9EwknRhsgH3hcHoVK836vgQNCLXDU6T3i
xhw4wFnP5nmeYVTUGb0Mwq4va73d9GHnUMngt2uc5WoE6T-CTOEOq2M4sserrWrYGfSGRglLM3U82Gy6jvKPwmOn8LtBR6K4w0b03j-HNSk1cUISiG2K0XQJ
yKi8jzMniG2e91_8uJkmQpd8B-FGM2N7IRG7o4O_F1ZSLeRYI76e3MIZ7zQr7EXhGyRl7UK-3xjriCDtVDToMt5ZhR561-dWuS4W5zGM0RrjIyVemzUHhcKN
rB6nh9cyIg_ay1qV36uhRYpONygjzpfuLGd2BCLjnOq5yOl0tci5NLN6T-snhOo47orJUb_w5WRPw8Si8VGmt-6XA_OfnzfRjT_APIAdM7PAuj2kvROYnhB1
dDZ305Jyue52OpA-QxcjLcC1nMqUnhnTsTz21Od9-61mMwt6WbhPzbvX8XOyUgiWFyeQsRLyrLqf-FPoIwqtJ7n46B7r1dBuZWa6lw3sH2Xayp2-YmYYkVVA
_Hf618CVvdiSh6np--hOY2YrJpGS7xx3bf1ZMnavB1lwf68dejLAP92O30Y6sOhXfDSIDYA-tYAWX6iRlRSbP82jZAZo1n5s-0xhMcwhbR2A31cz7uiWwpvR
GWRRoWZb8sB_iW3Ku37XNJlILkH904OHd9822GEwrcRXjbepCOS2wyWYybaI9yE49FP_NUjWb_zWALkrnOLKH87C2r4-Vxda56CCmNllt5wu2odBnPZmhkNp
sqZ1ksK07pnltRCxHPPhCGa2_7d-bP3-nVMsynMD2Gy6d_-tvcxbsiZU-n1YIYddB4LKKv3M-sxhfJ4vrxNVv__D5ZwayCgrznuE3LD4vFFVrlQXV_YQil-c
jRq83ZIV-libqlbpKRJMUyMxXEJu2QI2zzXzeHdrG-kNtujezSJB5E6N-MMUtpx6p-c0T3h6g1EOuUz13cflytzr_hXpy_nrC_yyZgBk3dEEZv-UrhzHMxT7
YSCzm_duw_pyC3_MefZuamhJSQ04VFxzi-E4AibljMHHeeK5OubNDG2YcSw_SjPMzQltAYdyg0Mu4eo-LiJn8m6T_xgjyjArLV9E2qHmoLAcWoYXK5jntEUZ
MRJe_xGubu4BbZ8T_rR9kROIg6wrRDvFGN5DXUbO0GPSKEGxri1I8Usx5fTuJ62MMdNimDWBoenbRBMKwFxhrKoms8Q149hLIaUG-z-sUwUhrV28uGQy0EzF
h7RoGZ4MFZmdIoZV_vhUNlWSNpXdRFVxM4PguKDteiTg__rFS-CtyiAizTQkVUWrqMErVgOnVq16lLACrjnJER7IWzMg4bPgvQDLNgpMkXaG8lXGdJJVcy4I
jbRmCQkCMAsrbSwra7sqIlfYBkXQHgG47wrIOgK4gmmNYezMoUzxz63fnT1zp39YPGUhNHW-MgN5Ie1U8LAEZrOf5vGUB052F1-pIeoL7YmzKgqfgBJ3N0-M
7gdMb5H2h8HhodNHFdmdTTTzNChOMjj8oKoY1qjrGOxvffza6weUur5Mf5h4E5qURSHoWYT5FLdErhR8R--7RlKE9rCNoYy6oDbNw3QDchnLKu_KzYjyZYdB
D-8NW_p-5h1r_O2u4xyO_s0wioQ-fbwC-xylcsnD_AqzxxzQCceIBiRY7_5OJVojhTl_uItef8jXR6qhN1C_KZl5YDV4Xv2ryZKn8AJbriGFLnaGyhBE1j47
84IGGVJ2rkeGekjsM4rK5zY1a7nDV0ZHvH9z049qNVsQ-11Yo2Jw08JeCb35tbgX686Q60UVBHzL0X0Ih8aF8Rvyeiz2o8547oX6fYO128cW2W8GagW9682G
G4t0mDO6QW86jZPG4p088GSUlc1kQxt3r_V1mDQwXoyOsDf0JS30rWQ87imSVFxXw_WW0iKGYLxtGQQAuH--eF6lSrYNeVdm8IIFAc00GW8r0GC7Nu3emG24
18WU3418e2PW0482g08682HG4p008O6QW86j3TG4R1S777ovce0120aSlc00GWA7BnWeHW1L0X2IgCb4048IuKf0o2S
}

