sprite $image318 [320x222/16z] {
xPtXdXev3iHfi6J9yiBxl-qHHadYfD6v6I_bxFX_jxlVw-SgLpKzSFgxMIIzay-dLrXSH3_WxNIKnSRwatGwneAquQKONDPr3iNWufnr3pgzmBBkeHXS9D66
Wp6uh1kJdtUPnPRDYWP4CRWWgtTCDKRsOd1nqUeKtI7iCejDgXCh64owPTsV78d1nQNKXYCnk3XBRJWIWukDM-kk63n4AZLWnM3CMMj078DhqctPQioAmRYp
T64h1eEv4R2wJ63T6X6RUCLWq5bM31xkB2i61yoD5OClpOqLWmEiEzJ4vwyrDyOhIDlNc1ih1aVDZV5TvlA5vyRgCl6d6-yniTAshFkvBfDMPuammAJ3pett
cvYthpKtnfkObdK_9Q3APNMMsCE064JEZV420cCGtrdCId4NbbBC1WW8w388wrfHoSpqAyoS9L0n410GWy3EKZGpFOMpsh5B1123k4ytYhXs4IpbY8206CHq
5bEcJbYjty6060HOruJf02msx03E_sHhO-jIRxo2sWsV_rxhAjCBS1bq01tQ_ixEOfbUH6p00OnZSFutCWhJox0DE81H3Cu_DmerZFQmwJ5uczEwu-LpIhz-
usCGFpSeO8Y0UXYvpDzP76FwD6nZzUkVTFX7f9a6a0TT874CugqxthrE6Q-VIfhPkawc8V1e_Jm6yTQDCHg4TUJVy1Z4VxgXD0WPf1y-1i-vzfDf43n6FtmC
ajK3C8rYG7yE9Xqk-69e63Rs-cZXCxAppAyVVj9vPy7f5yJV42H1h8k_FueE8b_cUm5SQ11vmF43TXbIgwzGQ10wuFO5nQ1_gTnF-o8Ap83ZXvfqPzOF37S0
PS3nmqowZVG7nK0t20yuVeWOTEiwBvdOQ00bkdp78pJyI-LULx20t8kFmOsruKKJAqG-V0mcqNsAlLL0wQ_Eu2uJM_Tr4oj0FkoakoGEz0kwpEWFuLYFouSt
yOM-4IfOx1r3BjiByk6x37t0Cax1aWU-kX7BXuz1eZu5wr05O-lsouVlCaHK_4tbaJ5OyY3rOldmCPY8pApauJ5eoaIVVe7SD00VWwwVApZCn8vfvdxnyF8v
wL3v8ohsG7cyWjMAPkOzwRAK0UzBmcDm8r9pX0R7e6DML4No0n7Luj8DE7pm62JAvhY9QK2N6K1H9BJr5sZxIHbWuY6eA1P9dVe9kO6R61nkuiFr9wipkOcl
LSrfOX1eug1EpNSJw-rMpS77e0UV13aosH6yt6x_MCFXBZF-skXN47y4_xdTp477e1Nz2TR4_J-6mus1SJ7ewWKAJjgchxUhjVHFEljt-jvK9gPJZ3G7y6WC
sk2Zr_BX0fxQm-UR7y30nA62OyMRqCGItyEbEO21WkCbD1SlOWOJd_iEO1o3iOI3j9iq1iDRn9e36CHWI3cWePL0kobDd0vrwDZ4iOWM7xf0kgaLJ0SFOAnW
JBbZlr5A8Dpq9eu5l3G96COW3Bo2gUi0CciSWoZm9hvq740b8ebD3EJ9eo6Hx8X0QentGDUFYkqJ702KYINppeTJ-Y-n_TyEM1uAsHCAmCJ1f1Ec9x3elq6E
dwFw6ID-t9TH3Ee4CPWf9B_rOSBsum3oGxz2nDF685CN_Cu852_HLZBfHmvor6K8R6BdtMTGdXx0Q_CWMXyIpHg3cJhXzpcOsnL7JmyWFWOpTSFlkuDhi-A4
xfYPIfaj1ZCHKC3SkU8o-Jr2EbSC2X5Km7FdWrIL4lHfN0pIGUHT1t2xDLT8qAUHCPZf8Fos7Pnt7WIovw23Zq4Y-06CFaolUmVmyHy9On2X7we5deyy2DI7
VyNh8Fp9baoW7mSpUETHVd6VDlT85e29uVevMu-3utk44oj0mJdqe-X9wktfipzkz4if5y03VkpzuOIlSrnj3_vJlqJo_XXaEifxFm-kppxDp5mQ_R9GIlHs
4mkk_yKLnZbVxoUmMeJhLosdbBY42k8FuDkUv3lfTkUV7lrgBHw3mQH32oXlVwkDRus2WNvtbDuUWuAyV1qv1QHxYt4Jn_ez0CGWG-Np3HAmvOyZM2Fzf3fD
30P_pmaGK52lfPvBO-98Fuz1olR661JauVCA69FgGy7QeT_p64G-ns91lLFfy3M8GNBzMXE_DGObSd4Mu7lbpYPkubW_fxn_qadUbP03yKRVm35dSmL3_PpY
a-wzRL1oPcv-t13-KdJSPMBzsYwZx2P6W3QmaziOZFLZmAG3aK-TRDgOEDRFkymROX3ETkhbOasNYVG3J3eKbrC_z7iCKY9vebyreT-wp7yo1lbqW4skpQIZ
HztRrU-EuMCGtc3YISVf6rpszVD99mQ8GNm0nfFEJIpq4717FqV0COWFm7ZIbMyUfHtzK9CE7u3za-v3GKvazGVg-lralyjG_We167SPZq4badtz7AN_SWoU
0ZgxZ11hhKLiNxzgoKqCY47S0edPSXE3n4KJQQ0VjClC-DtRP_tLn4pyJI9vgXzwqk6_BpMUT4B9sTSFFkdmtzSRns395EhdamxuP0jltNZI5VQ7VtlwUPTf
Oh00OX3yVUNnfDEF8vZBZdxeIOUtRl-a8x5z_NpIpTHbyBz4kd4JWnycVgPVjGnwieKFllZnT1k3E_gramuGW-ZEqZ_f0ls0asxgNy-aDWPP0_sUTHcMBsNT
UDBbKglf7_evHfX9X-yi_PDEh2Gk-_fLIWamwU2T9IPPOsBA3ucUwWUOTF3ESdpIqLFzDCCc7Tww_PFkgNwbFkfY1iGWkBFqJpfNq7Rr0tGPG6SPFEbQ_Qh5
amxVMG1iVFrpqkcEVir7xVDDEg4JYBDw3FvYOhPz_IhaZIDyP-cVT6xYyaI_EMCmNqvOg3PT9j8FzNWQtrdw9nqdjbtzd4TEiltUPMIopeBiCX-tSFb3FwTG
Icg_cpW3vmQUr7vAHrehYUthLxFhrvgOaPq53xUJZikZov2Nwb0_Dp7FQ5tOfADqXtlriy9419qRU2uxdz95-hLa8fwiiw0dNQnVB22-iqmwwLm_W83ukT7_
UBgTTALBFsEYF65dmK-wb2tGhn5GPkuikCVJqgLV8I9yPvbkqdNhPqh4wCuorQIhtcMoTUbdGfG1rfs_ov06-dL48Bwpu2TThLaZ_Jm26TPPPfvqofID4vT0
ly31yCw2xp9AH2cbp85-WOCHriL3EvCkqYzsCBwpuBkCwnSwM9Prmqcd5i54NxApzFyHIQoV4cLayCq_wTG67410Pq77e9ku50ifH7a5N_Yz036PQ5atd7Gn
XOYXdMN-IHUJYMHPD_WZaW474DrPy9DkV8cc4m1SbuaFuDVjBFrVzHPVmSkwyQIpk0EkplAKI_L95nx0PTtNkqmXogkpz7p7KR22L_2zFkcKI5Pd-SIa8-8L
V9_uzcuXMjRjddIlt23fj6WVJyStoB9kFEc26oJiB8iVZwU36oIO6ulDkqpV1g7J8lebajZ0kJFuLfTHuazqbjLbhbS9EyiY_YMI-xrihtUMrMNgNSg3dMMH
RpyLlF_t4vrbnU3zFwkpVEBnzFr6BgztbjLbxl-srLbUVpnzftxAkglBL8wjkuX_LOrEBxFWgYSu_mC
}

sprite $image318 [160x111/16z] {
pPdhSkEu3eHZYxW3qVk_xQamyiXYWhDSU8hhRoxvbseJhMuA_dYH6_7zutrfeY9uUrDr6wk8Y0gyexeRgHmeRsyd3qJbHEczRDZCLPxHTxBXNIBSJGQ5xLsC
v-4TbSvxsH2igpiLlfKDDmb_naORmdzfmnjx-431XYj6stah6suwg4k7_5_OyCuno7ih6w8dwZ8RSbjQ5wcwjLcJryK4jhRonhh8oRC6rcJAF5gtORqkHY8c
Zh1imtfTT65cfcfccKmJMMH3l8ust9G9uG29rJmIWKKRrkiYN0b6aDGZyM2Xykfr4Iu8luBYFv1EmORLkWX3I26Bv00BDYpLHGZyNpGI1nPkNeMwEELbI2G3
dhTXlIx2u1-nIFJDsx1U5mJ_27bkmBcRL_qAQZ21HN9-kGthTP6vBwT9ec_MXlKhQ4YRqCVnu_dDKVttMTE6qTRFBxTVtOQtiovg_jEO66_vvWMYwWygpo_c
JsyvQyOzeoNoGkUFBtTVkVBkfFADMj61ZGl7bz-yyZsZMadWXBnYrcn0Sa6J4ME3X8Ow8QzeGm0O5Tgl0fqXWMqYMgesR6m4m7AI3JbC40OQO5St8wzMUOtT
51lop93TX9uq8ebw-8IykWtlPEOc-P17YMwcAg8wli1r-KNoohkZkfaRpodiHCT7b5WowbdZRb-uKajiE8dIyH7hAFzyadctRrmI6yvlXbvN-FC8xtjO9xVX
_DwAZuzOHsbqeUvsaDjmVgd60FYY2xUXGNQtJc93KPiL9tzbo6CMscudRZzjUAJ95JFBmWvxuDVHgy1s761kmmCzaOJSXdM1_G2TKHCRLhZy0lwYMwiai3lG
gP6PdpOidi1eGq9ygiDvxiCZx0fWmbSRoaiW8C4LvEca7ZFGLPmQ-p1abJAAC39l6uMnHDnT6fYUDZnkNbK8VWCh4xvzVjeNJ4vDpZDKhDkGeLCzGQMF9_0x
OzoS6zeJtOPQir-2pA7ttqCQqUXlP0raSEK0psk27LbZvaBcvbgo8UVwIXb3-vFj0FjFRi3cHHk-h4zXQ94dWVAj3mL0_B1XxV6jFy32rmsHxvzsu7xe2-U6
wYKRueloHBUhGDbF4nxwtCEm7JPim0M1PNcYE2uJVD_zgkzO3_Lv_siRCbRhu-3sCG2nV_gWpyyXzvjNMI6ITAe3xd0Vygcl4xGrifeDcUaBPZce3xXpruT2
Puo7liROk6B3ZggKu8_VQ8SDdS7YSNuQprd3iePaiuMVNpPqsHe_z4cKiwQEGhekxqCMs2GU-jp3g6J3EfHlVQqh9BGuz9rPuuKNW28VEQrdZH8h-KEVXxMM
L5wL-dQQkWq5jwVlNwm1BR1Xkd7xMNbVGbhZKvzRpvho2y3hY_EnyfHQ8_kZB_oelFeBG7tZ-tlbAMxmq7TMNi66vOrv3lSX2uY7nxU-SjQy_er3NdbC9kg7
FlVW3RZy0b0tNbvvIj3er2SDQvLNpvGSFBAcjJ-bB1iNRbxbJ9dB6e46yj174OQ93QkZhRDPlzTGspWU-huhZmixhqAcJ6SDUlpHv-42gDyxBy05cJ9HUIGk
NT-ZbCaVomPUa2aJbKSDgS-vW-IFZL99e79zj7dbjJ_wWFnSod4XKvBHre0-PCNM-79-7ITOFjgHswFoDh1Hdnd2WaoPhBmcyKEV0Uc2J9ciF7QpkEXp1LwG
ARELHzW4BkVd36kCDt-zxlfEa7H1fanMdXiF-bnWHQRCLvw8NK5SFDeSwaFkp3uYzKofPyqL9tpz2lgNAsyym4MPCfyrCmUelC1uMUKb1rYjYphvHcdCm3nJ
rjFYoOOki21J2jVhuPgmB5FcA-zyGWgPigJokZvfN7YjNLLvPgvS6EqAZgpPev0f2oilzWLrKRzUVyPkXKnPM7cxRX_loqtZvSFx7m
}

