sprite $image99 [118x86/16z] {
l9TPcW8n28IRiBVtF-yiHYBv3EvQB-xz3qKNPBPdrOHX-xA0zK_qNIZfKIRuFMOJqn33zypD8lYUkLaVjnbr9MdVQMZey-q5DcaR5LpwM4DnTJVf1rFKH9Mo
qOo8hSddsXlrcU6e-_HKFjZUqKiNY3yZK-q3AS9qLJEEjmVLV7SxjxUzgw5PRZHJVV-NltD80jiC5M99MF4zv2b5BvlBa6U3pNsZWCxbck9BeqXQNcmsKvkU
SC5-jRsHbfQJmqG86uJaxAmDxaifYlgCqsI0unCxogD0wmmBd-s5zewqc56y9PsgcelhCmaQaBreyvmM6pRtpmPpC70ZRHl5ky-b24WdMKoae8wgJWnXLTZ4
r5OfWiVC3GddGTVit50xrmPRewAzUD_YfiQPshgx0Psh6LWcFlxkmHH5GgJbpfff_bmcfZ29dXdG3pXrYkgqS3AwLt0vYcn02Odj40oPGcHt7JLGRBfbAT9A
fcRzplLKH4CY4c6rJ4bj5x5RHuqc5xSiI51pMWO00P5OpwQwZMzvlulmugXHfILF1XZ6Zzjr05JwLoHLc9WqVbkc27MMM_Q3ics37qCQyaWSviBwmhWmTqWa
dnbuX448aJKgIYCoOLqrUjZKBqwIUP_Cac7kd1OAqw9q9WmBixdnGxVgm4wh3xPrMleTiB6fxeVTqoX8QObiabbvODU5ZDByYxHOxme1_7iAe8UeRKvB2tDD
QxajkKUfHGdZceJjptiLO14zlJsd9SoznZouhxYTwGENpu72n01_T9mYx6dmiTaLvdxuf_hoEzcs71U2XW3C8ZaksLoynhG_PgUkoissANFYDZ9e5j-gqxAk
v0yPr0KtppxgQO_QZJQiqhAnNpStg0KtxKaXs416ersbIWlSCZUe9TOILnccQRnEo_XlNfXP2cPGQswscHkB30jMQHbxcSUWp6a9PMhDZNAD-yxpAYsnc8ax
VMveILsbo1E0i6-r8YqNPyaBSqjgRNC4OcMk-kaZJjISbffws-OgBIU3f26rJCtcrjJRARgwMtXBmiBScbgtTx5RFAsgf5OmIsfjy-LkoT-Jf4XBHNsGwrSM
jqtQA-PUK0kR7zajDVFlaoR-GBbZjznUt7MX1pkUb6zoi_2-nLqpTuhsFC0z3Zvwtjpp_8BVrki2Xs400A5eNTZzxxleV2GVoW4ga5VPmBp7iTaNjsovqxik
Shj7EEWvV_tHWPgpShKEFxAUuBoytFthp_avxu5Eoylz3b34jPW0HLIBpxW2HKYBpxJRUUcWfboiADUIpykr-8279D3YWnwINWie5zKCjB1OHG9QMAQDd9Lh
uOhqJyk6JW3dLQ2bLwH0Iwz8G4i-hp-hKBcv8WLQ-da5Njma_bD3WPPUaLwqbEM2JmrTfGLzQYZGqYjIeALNf1lNqYjIeALNL6Yv0m
}

