sprite $image77 [110x80/16z] {
lPXTSkCm38EhVn6Yz_wttMsTSX8gAiFnAiLhb7uM0IBZVbnHx3Ly_9921K3vTs25G4H0J-zdfGxGAQ35zx9Y4zR9e_9Emmg1bDveNvvPD_lYMuROiH81DRmX
zPHJdfNoE-mh1D3oaziwzBGrzKHhMY38DcnDlQO5JQDDzeLA87gYrS7ZbDg6VQa7JH4T-9BUXhIbfavQMBYfPDZdwtgYcLQpxcSjK0dNk_wPreuU7xTGoM-V
CITrDmnkzsCRoanIlwOHU6GPW3vcR8FJi2cJv_26t4vDMzbtjUj5zKlbDk6e1ZdBA3CZzKhWKsUloDKQI7Hb6u8OPWhv-xGwQzXdfzuMA1WPqTjWfpw6PyNf
6L2N6NaiCeXwibA__6YcwOpW555lLJn7ArzgKFRDgOU7XYuP6H1CIJ4yM85yVnnG3UlKQrhAwLGcB3D2lPQSujDJAvgoJwTU5tt6mQUWtA3mieSqZSG-dNgX
pLSMpEqouMKzz24qjGrpweKMxeCXSIP70nDJQG_ngqARoYnBrojQxq6-67CoC27csgHck4y7qvIkFB0iUXulQxNKJkE4ZF5j1NCrQ3Jav4m366bz6J7dO1u0
fYv5_ea6FdXy2WiQqU0U7p7fTXbPjWw5QT8xSKt3E8uRJNYQziLhfpEbTNpF37BZ2DAqEsD56tpSQ8gd1HxGpf1ShNfe4IH3F1HD_jp4nj3EeFnGdJqjL213
L3I5C1MaPfx6iD2G8IgQcuUcCs9BXgXfVfxE26voiOIcPNzPPGGrffHY0Mcfr9iq-tew8xhejPHX1itaXSUVA9i6OLaqUvn9lHiBpHYYJREl1wR7DmwXcKEq
QJPFlN4aeHb3rBGbpYwpCjUJbtLmWURPzW6WSI1DDDimqHyk7w4D_pZRAKBHDDimKGldyMwDqrtqzX2FUxuoB9wNXl4pQsJz_m_BFflsUeXSdrwbnilhWTf2
_UKGL-_XYQnnMZzYDaiIFAl0vZcxNkEAyNhltWP_wWsvjy6TUbk9V3n_wctvoioVUblUChDJRnXsmJvdwcqvoymshFWOxZAxalhhzl65r5_V1dQcVezz_5-f
DylCHxDJxzy6WsQaVgDzFB7-U5FlB3FpRcoaViCsy8RK-ykCNQdVjGsy8VN-CcCZzVljOqVgzsq36rs_tpx-IlsxIL9cOtlgxJAxblf_
}

