sprite $image385 [148x109/16z] {
pPa9Skiu34J17MWmzx_k5245jc8p_2CxIZXhRRzUgH-8bandJ-54V-ja1j3Y7oAA3H0HI0r_X2XKGBO3oNyZDe7u0Vw0LeaLSdz-NQlO85KWHoefuVT4Aa0D
56y-_RfMMNIN9x5J_QfMYLMovJUIoYposrg5wjR4DjYYG7vNgo90jVnQ73oj2EJXWFELYqH4J9dOK4CIvVeK2ktAHUBAf2Qmy1XuX99mvI9nPJ9gCDRSy8K8
bp1bmHTbcACzl95IXXqdke8fCV1ivaC52X4bQL9Ykux9HNga4jGua51fCEmPNi7aiJsXsf0jHYhoUNwU2GgPKN4ksv8BEHG0LysTg4wf023kCy2riZ_J7zum
q04renAx4jfcrh3-aWqZgjzIGNAHVUC4ohXYmq2agou2p4GbKqv43E37Am8Q5HZKTx87Icta5o6vEbKDFyJ4H0LO1ZZ2Ava7HfQRLZ_7L2C_qmft0KehrUSj
ETMXUSRyFgRQY9f-3H1TSTGgMLql8PPKv46hK1tnLIRbO4prg1Nqu-EhOpLI4QZaG9HOZbfPea2DRs3Y8gX4hL2KMu3QFupfa2Q40J64O6l7jV95_fQhIni5
HXbCn9Ltga5aJ0SgZogoBKFd00lUM8xHY8emIoQIH1d6yN5ZEWRu-PfbQ88sASVnrUT4jL86Hng6IiEHwKXL0nKEczFCSI_7m07jrQiB4ctkgaYLI452Q3Sc
OVK0RqfnIJ7LBQAOAwHaVdoLVsa7bpOSpw5f8HfSS2QcB4Ug_R7iAiT0LAmeDpnS_kcbNj1eSnoSlZ9H1lhZxi7WI2pIMg5GIdcdLbd7aMHCAOj-PIejj2Uo
0xNYysR8y73VeLK3r4wnkGj0YUZkqs0YgWvre1BP6ZjBoSLx_UjQGR5HeMvpbmUbpvr4Owe9JwX4ylQI4SZGda6TqKhq4weB8f44oiva4BPuAF2J00MjeAMM
Y4gXy0nAL4zsNy6krJPtdjt-06iTNFMfLiX4NApqDU1hWEWV9vbkL4q2HHplp2x32iwKyBJxvQsaY72hJNOgN-HdcBpFxVzJx-REZoHgcOYTw77c4sSwQ6MB
_1mJUv-JNQlooCJI90tv9Y_DqbW6MAZPjN83pdKwFL0zsNUPghR1D7-Hu44KGY7ASA9JJ76x5ZDsAi2PkY7wvSLTidpt9bY8QijsvPb89vb2bRqN17Oe65DN
kI6gkRHukp6jOaqL9j99fYmGHTckwdPFzQ50_-WAsQYgCIse0Awb0HRREQQjhgemY_K2yW05srL-vvWjFOUQKtbi9vZyTm9jb25nwmNyIQMxuqxLznIneFBO
JZ3vP-RXKu5OGvCKsiFSkMDsSiOaG9__aqotMhWx7fhMmKGaE39vccedKVHjF25QCQq_5wg_StBYmHGpRan0TwgTYQIqPm6wI2UOGWKEQrkIhTYIHOtfVj_n
JUqjm4X18kM3x2xIEIONoS---SrnGGtoq3FrNYkE98EhkbQJsEPCw-_EsA2CYKiJXAzCdCIfj8ar1o5_W72Y4qoJxyx0rkUoEPuWaT0FVVp-lepsTXC65zX9
9pHhfb0dtvszpvdZLVYk5rJATibNLNSSN2HG4hzalqNgQVq3nfogcIc1gjwOkd0psIp0tV4aY2C_oi22gGC82v4cn_lSCFWkEwDAM_TbwRQC1pbGqc3Qvd9E
fD3-8NcwI0vd5c1-qdsrihtyKOLg3MpFgi6OYEgSIMqTTokYyzpML9gUTL-sFavYIk-vgSIytHNJsBhzT_Bo6Ih-cQebpyuF91lJFWqsTv85SwRkuzWnU_cC
3LX3JRjlP2s32Niz9ne-DQsKLIUnETtyvJFplmUu_xc7xgijiCAd8HfN4zO-9pAcRxzfb7_MoX_vFPC2NbowjE5KipjY5jkHwQHM7k0WSaHdEhv78D4pnxiw
aJFvWUIpMgaU4HMPclhn06jpfaDi4wPJMitJx2ogZrJiJ8Vvdp3DjGf5pb1jfxHZ7qQggaUH5amYa1fE13Yz929bVD7Avyx_TyAqq2hnIQhjQtK_KFM9I7Cc
0Sga9fm8qBzMtr5r5sdEj5Rgl5PrwmKYTrfr5sd9DF_nuxnMAfoDAQGRbNfiIwRvZqJdjTAOHDFMVVsTM9neohIExRnMneCQ1vEOLklkgwiRSxLkramagGA3
YQZut4sFOd45lAILCmLAAcamPKxuzZbrBAxArxN2vzTgAIp6PEzvQwArI6TQZ5zHB5jkLIib9iepfgxuloATBySrsDoX2NilM8bKQ7rUASTTwjPzao1DdbF7
UtxrJFzUZf6txWjfzGbJr_CYdI_7sihMVIjKJyp_kxN2HYNX-JjdnsAH_A1MYfJTyJVDlv_pByrmfiKYUVc4_wDLSAQ5IDS5s26gByt_czUDTz-rI5ThrHzY
UqsarRV6DPKnzSKYkLohlXJfUgqEH3mHwMAjrlD_lLRhHNAzLklvlruhNoGNdoAuMgJpBMO-_zThTRr8wtAy_Y9nlLRhHNAzLckHhjVg-lbVhvlhvtzTZjUB
vFe0Nvx__m
}

