sprite $image248 [241x183/16z] {
v9Y9LkqW34Mb4v24___TP-NrdbQANLcKQy6z1kTXctC8zgCoe_EB-UWVwAxy5UN1-iZVK3QBtxCCVqYtVsKp-pDihygJJ-XPUN8UzAyyEd-17RlRH0hbldM1
cphSH7c8HMo7coYlks9wtKIfRcJfTHEbkX7kTnC1aXtDdbkBIXVuDdMDLUg2eSdLwxJb1RR5-kfr0RUtcMQDRihSut45tHJkyBWYaX-OkZkk4jrsDzDKeDlY
PbfAoWjiY_NLwm8slTGtqMrvCqt5vGNKP7trQGPJ-t4cqS1sCat7cKI9zzxEGxEdCujUUCN1kQL76oHgo6-uPMZij28MBGpVnpaFrSRxJEVvVbrEV9_JPsDh
ZZVbjtVLw6gFDsKP7tjQbO_tMT4UNEt3EO-T7dAtgZzUZDaywxJYOjzBVJksSrg5J-G8-mD4v2znKnFBDu1SUrTRbX1sKsS9Azzpy8va3qLn3W3EdEXw2bz4
l_WMEpvHNeO7drRX314w2RE4BpX-o_NJlBNMoPcoUUZo3QS8fxh72VFNApRY9VuP3imF_5SXPFW-NaWpCx4mnpJR5uIeLp--Hdy1QtKvrKLgj-cAitjGvTfB
Qj3xGZS_NkYYlE9VvGtUWdskIwjSdcTH-l9HDn8Y7kKzmuVIAfVFbmh6ItYTjwoZl0a5LQxj6nI-HB74p4mnsPAa-RBAmqDzXK_AYvGIqdn6igA8cP8gL-ql
QSURR5x6uaMQhw0GbMdVwBdsVFM-oNWXpDjYokXcSatx-uWRt-Qh7ozUbIXCWl9gbD7eyYgRYpnpoNW1hOHCUQ-h36LK-G6-oNZ1HNclgenSHwQ7-LBgcqcp
jig4AbVprIyZw091cjKuqLUvlY-Tw09If3b_soG-h2ZpYxxPyK9Od2s0Thd6RREshtgyG4BPZ55bPl_23RLzzUF5eLNGulm3aSNKzzMF5sj9V66kK-Mvacye
yuNo7Ra-uCOt-WfdT8c5wJpNVBkoDOM-f8up7Ut8MSluSFqgJ-_nvLoQcU9jWUjLMVFKozxZAmG_c1DjLgamCJDng9Bh_8OoD_aoD5xYBFzxpOal7cdH3Rbs
aYfFjUQR7wzTbjTlGkcXZQUq55RydLNEnrhhAnUdbOVvyebiKYaXWcdVSTkyZhKhznM6v7w0j4qnKFQs9LHpHPsjv9b9zRpzOho00_0PgCQAef_lNOQOgS3t
7ozdk2ydgWJn0H6Xkdp_rxqv7ZD8eMt6dT-jZyicyM_JT3KmddeDe4LN0lp_S9k-2LdCBf3D0VQy1in8eeBT6xaNlkOslKIEPe8il1xmQNXhphYBwp9FCSPf
BWTSu2kfJ46UbBYO83kyRZ7QPQnQ95GbXJywtYBPKKdxljlKYZpPN-6p0nN3-HxiVUPERzvNoCUpq_KxgImJB0jnjG7Pv_KxemhZIdDuIzZq2nnDgpBi6oMA
zP9ujeFWyF9Pupig71I9Go7-KecgNCtf6CqKsUNLy7uiIw4fhyFszNzrcuMIKK3fY1SJPF1KPkIJyAh0-HtVPRKlL-LYie80MfwYgIxlI096cbYb1yIsf2bE
QR4BtkTk4sUdMafS_WMuSJuCRob5Q9or3K1zSDvMUNtA4yVAv1FZF_2MEVwios7A5-CvfJJd8YUgRLu_y5cgOnx7vHvudoYFj6oubnSQbsaV3dCzLcLyrZXY
jmTNNhbqVeky8LwV4vTuS1ep1jxGXXCwO4tb-ru9bEsLY-PfCQv7v2_m2j4Umn2fmrC33g5kbAjJbLqBVTc3QnfdCwuhhuY7t7ZkD2Pz5iJZSFd5X05EYN9A
aGUyz7PhNG_8RdW_PBUv0SMg4KOEJT6iYkxT9exc05vqOWVCzO0yXlSvC5ZYt_XYVFUS6szTuHs_EQN8Q4P3UpouMJpPRuWRyaLudud4akTSxEpTWvZZzZOM
Nl6YchfDBKMKgGnteGxsIzoG6w_X2MDPSivBcvJU3vQCAydBxP4jX9IghCOA-wExix18ayZrWBpZyX5ktajhI1T6P8f_bDeBsTIzhQNq-u6o8QBRTZkm-LaN
f4ca_2ZZ8MxTilBwhlasWtLqD29XxjPTJUN2HhYFKNWTu82DsBksxsI7OoL2ie7tC3oXgj9XjCMEKgBsKWIZYT7tdZ1gaqZ1VGoyC_qiHTJXA4x3ULiPtHtQ
XjoIrzRXU0DNZuvfQ1BfuROUn1V2GVDQFQTHJTDVtvOAjcy0NpaDLD0kzXx69f6tkFSXjgK1JKOPnIB6InHqGyINhMVrYBInA83poJw0uex1lIScvfrdEVdB
kBnZdCXXD3VUYLPlPJoYeLkq8Vzdjv-NT-9ht0-kh92e1NPkMiWoJzEKCbPM5LXJUrlrGydllrYjblOtSz5pfaqV_BtImwUvLLRTwovBAHTfA38QIgdsmE91
jiVj9sjZVX-MbTTHQGV69yHwc13BkH69VuP3dC__XfBdb58kyhPavU3TendaX-k6sBwDR2IhT-pYBy_0nM52h8DA6ux5EtgPPBJD1_i1pWkzf8PH5y_6jl4I
UdYgnFB6U1Y33QLaT1fZYn_XROZ4YsLu0rwjL5c8P3gRTK-SZhFtzCkIoKRYTXYnxQ3FC0p4kM_nByhoPZG2S6syGfXDHa6-WNVPTOxHtjK8wFOfAS2wAQyd
POTFzXMYondr4WirH9tJCBM1yt4qwQoqNFu2qo7kV-27DfqRhm3hqHhwH5qFd-pZG6orCUNXUL0wAm5zr2DmeKndO5lEoPK6kpgQHByu4vREU5a7u8W3SNT9
XIJIziT9whKiuv9Y277APuS9HDfvfZ8EMubjTlJ3sFdCvfbRhz3M4S6LyXjUah_weVOnZGsGM-mahPPASaMLkmxWwcmN6AtaEI_WsNIavQqzRczBs-ILmEKD
ACEmjYuzaV_bqDo8zMLpLpUd3kdUrQtbXr0N-SiTAvh9sz90Nm5Zw0qjzSV1Tz-6NOHORYLmQCRiehGwNmB9wIUcANUnLDhstz-v2pCZsK_dtWjR3LtyUFzf
s2h4ZQpx98DEQprR2NARKuR_vTCPNFTDH91iYnRxz0NHMYFBVVJ-vIkQ0KgiWO3rto41hblyQDw6IBnf_J0lN5VY5ypOymvVYW2cZgJmeBK1Yw8Ggq2I9KrJ
1d4MvB3h5SwSHZeUlMJpGspr3Sabc_3A3rQjX6jUhlQwqcGUCGxvFzF6JBP9Rd4uJYEp-iHj5jCshCjYP3PBt7fU1_YLF69R6_1h9eTC1kBnCA4swMY8463T
WBHsmMU3GkEL4B16YPhmAh1FhC3StsOahIgoMOw_FBEDjiWmXUxeHTNRAUCEJ1vmMKMMXK1u5LWr2_5eGceAFuiEkM8WnkzhC9wMLcFDqn_bUhgRXC4nmwoF
AQfHfiqaTeB2wmFxnFP3tBG_cixhOSTZAMtCtIkaZetEMLf1Aq7CXF0Ay0FYzU8onFd2lgJVInwfr7krZMYSkhFMmAqqzLQRGbNS4TWdRaZzDHoEXW_c7IQ4
NFzTEFMJw1Pm4s_remd2Um7i4kDqExpvBa6-F5i97m2VdUP33JPiVldBbGVi4wi06ttNa5yLapYDvn46njSHNtxw2h2lP8eyQiDTfkQxDCYOdHRV5OPRpKCh
cDKNL-LLO5y97d7ZVVkkCsIRv33XcG0jlnZ2Eq5vHs1VqnrnjvEGI8ofRFOtnZ6JZtd7OfI777Jly5U7Kpe91_ctGFqj-xllabG6MPUSvIBpepEKTYjX36ye
7gyiRjSArUpMQ7A9Mz7fBsN28DlQpyEhzn-6yFhJcKluu0i1fiYZqIJjbsgbKvKV2f2bsJIyQYQLjyJN9rfSOZRR9S1VGiRWivd7UUZm8hq-r6mUihNFiPvj
6ji3PByMrJ0-u3KlvzVdId23REjRzivNV2NAOsDayvXq54doFb2i6cHbjjriRRXOyW8Q1FbPzfe161gZfkI4jshoFbswBW6irULOQ8-ZhFSN2EbxHoyvyaeR
zIoHVMIinmtWcPGs_W5l-pMvr2BPoH5UMTgUQC8zigtT6GveqkT-WgjzKOrEU9MNClU_CQqD5y3CU_jhf3sgKXY_-Obq4eBByChS_zQqDfnRJTgIOanWEnZv
Q6Q3-cViPBNDLFa-ylbgxJkljNy6NEpWkBDPtihPR8wWo4lUvyftnEoGpozbm01_DXFj_u7CPZUyle_yVf2RmzyVmGuNn0ttOTufRMr_U0ad3q6H9EzNDUCE
cTtlvh7HBlEyWDQ54cDqTKFBphp3JDK37_bqkLPalLosyuQ_aK5jCXp4_tLp7hYLmp0KfBhqgBt_SRSdSNbocE8ww0dQOAnFm8NabfMoOAwDT8kJdGYDANFc
Jz_RBFBClg_k1BDWuxpDouuaM9L_zEbDaJ2_Az8cB3RdqyCxFhqQPLzSKPjo_skiyVM-LmSNHWT0Hf4bRy-oFxwQbF5_IY774ClYOsGC5lGeej2ytBSwEOH8
ZZBTlTldJFx7Tqvf4bDUFegEFieWngFRGC1gvnG_lEEyceHmr57cokZ3sq2wl6EbMfqjBnz5-nEQHNdqnOmkfpSVBXxSjpavWGYr_7o1_HaB_I2Cp7KHv1nS
vieMT2eVXH5utfxaF7nL0ZuaZ2oKGdJPuJt_AFCfjN5Diy11gM_pSZe9-fdCcrlTNAMw6kKAkA8K68Hvv4ZpzYnN8LIb0DlV6_78dkSbS_g2okFC05zEu3B9
IqRHXPKnlAR9NkpKcAv6kI2-w01muHKvLPANZAAhuBFQCwjrKMprSbrSWicP2xEy279nObEJiyAGLvFSW51rovaBW-GbX_UY-0nzJrfdjahoDYyt8ZKrqmba
5DtlokQEd2mtn6TyKhWwkISkjKyO8yYD2GLAU8ukpsmNBa9uGEO7vUMuM0t2nSc3SAbk2skGf-5YmKXOipoJa2fMmehavC7uM1hw2wZ9otxy0W
}

sprite $image248 [121x92/16z] {
nPgFlkAk3iI5KY2JIT__SUygc5AvzdowhkSt-xThrw-J2IbLRzSKYwpXzkiAMI3uTNHO1H0H_38wDQmqTFujTAgE_KtqujYHNRwDZUKL2n6eRUc_mD9eyjsU
UeCbQSltkFazbhJwBMme-7zOOmSpV2dUElMoOnivVuMxo2iN7UjW_GPtFS4wENqrNgyoNsNozNWnONjZf_XFoomugxBB24XTuxVAx5MUkIBIs5yOLdYBrM65
ruylqlcINHSWPVcegwxQ7Tarnx_kgejs8GUvxK-xoewufjqk0BQ_qvH4ivskfhsSTfMvndJLp1w_IwaqxRRJHpDovDgefrs1GbIXPYXtYJtHTRdQpJzp2Rz4
cXb4k6ajNUWF0oN-9LVDJkosaqcgRfIogwfHcdBuA-wPNU1nGZEDSfJGL40897s1AsQcCDCo2sPGeqTzeQ_qfCpe6GEsiOKxIOruz3XA_9nBD6mNpCETLMaA
cj_ZNU2Us6qobbn6pL6h4OAQFl7hTbrgMikPO8H2lDxN_CvsCImud99zQG4vNENETgkgdxkPd97FfcYwm6s_XEPaq1lxZSIi4L32LR-wsrKgI68_6RRz77MF
Q1d0yfOxbnd8OgRYeXalHRtku8eV-baTAqBQ0Gpj8tlZUTJFT90TlAZkQ0pSkQjKeUJEHIsbeaVzOxrRrAWUjD3He6jSH1qBtLH6fHZQLab9FQktJz53q8cg
3GswuTckW3nmKMuXjAnqsrhKSWREjRTtQk00rOQcqJLotodUoOltm4zBIsWuj5YcDZdO22Yzp9FmG05bNOj2W4wMawLLjHaPo04pM4wrBZ5c4O6gYg2kQIsz
HTGC9xtrIcOdFsLwnbr267OEo8_3rQFUvgZ5J7NqWzPXbSR1ifdYX8lb5lwmLks7wN4OqPVr77NbfdqR_1Jg0rn8Uw2V2Rzb0X1WZN79YcTJfJ_WMBr8BUhY
qkRgfKsNtbvcTtIpAszLSYuFOtY4AxLK25H4sh48ngWzN5WV7oyfBwhqMnEynTROm-pAz-FK2Y4YDSKOLxb7RSyfAZG2aBv6flOITlA8XKpdtiCC7bDuT5M1
5w-_BXz7gaO1_Reum55yUZdMXRcT_oYhEEdHL3WqsVwmeBs2FJseAgHV8lirYggEdSYGMWK2IAbG4S07I8RkFRSiIr6Pj6-Ok9cXL4281ewlN8pZiYmnX2IT
89ANkAoxWvhNjVIhbpP6Ft62go7UGgemlGrpSp-D4FXogV4uCL8OcmpbqNDfl9KNA4mFO1NiqHOZVKF0tJDCmotKHlQ9KOzX9dtfkVt-WW3DZ0Uo6O7KN1hD
mM58Neqbtehr6W4vBQlqCE-e-xhnYY25Ftg6Iv8GerBr1RmXkb-JSIlYdjMCD4CdIt-e3n1H08f7pxK1KYkS0e5nl2GeUh7BpRcqzUPQkPEXDAf0WM7KBHuc
Mi_v0DdF8LJRZiHBtKg9r3ErwLtVx6HliPpRnTUt74FMDOmzDu2D07IZjyncfZMsHCNeO5SvaD7U1gyjMmypgOnD5khm7nIFc3R0g3u8e6HkX0ZZ3FOvuc3c
6AiDjn6boBxbG5bJ5jtDRfis40GUxxZ1MxHp1_10Tal7-pLuc2Kjmm0vZaZ_bo7U4fvTrBaTF9675gDH0UtKSSkH8BFwBcGuD4Dw9cdMiGuUL9oyhmxaBCDc
SlKjnomenog39jrk4BVhu9ayZazxhBdIo90-G1PHELElaYGV4oDtaudhsrtiO5t3hHXwr3v0paKpHGt-f0DtQqq-AUc1hDRcc4xNhJT21s-QRbxcqMz_ERCM
S4I3lBC1QgVYlCZz3t_-HEFEnN9xgo0lvRwBLlhcyWmD4IKnt9o5EjZTT9rnSukDxQsjoH95tgFX-mnFST7TxiPo-qa9dA9cMM8nbRVePv5PepkmdMiIpv1U
eOdSn9Svvi9X3SrsFToBfht9HDbsR0ExJsypK-GmsxMDwvLFA7H4-p8cuxq1rNSea7u6pVOgBp1sxcObNFmiY3gWVNTpNochOTW3Az2lGvDTUhXNb32XOJIz
yyTtLSqC7kvermV9PMLzHOFJXmIWRLZ3R7UUZvUYrbUqAfy7lfTpxDxCdERZDIr2Hx-vGncUFxZTFXy_qOeT_SfkOCynQSVwVFn8mQEUREDvAtEOp3HVGlyK
FR1zXgo-hPgMqATeK5qOm4sey0iHqh_-4XidsplOxNBznbUxTBGDUAcLGxZVK2oWJchCETmlLfo3pARv-BsAZznXFdxJjf87i27UVaKnoyXLj_iRx5H47zIB
tnBz7m
}

