sprite $image370 [260x285/16z] {
xDU5aIKn30JG7NQ3yW_tQ1PK_Wj5HvOxX5V2fp-RvMpxK_40q5hSW79CWsam3QR1D9W6qs0QfAoKessL2Gv8Dd4KDW19KRuA6r0YxIXk84Uy6ao3QJ0Dfa6R
1g5phKgml1e0UzahySM0Gj4g82KvB3bg6gmIITboH5q3YPGSjGrkWUe6SOVBD73Roni8kDPo1aTl09or6c9hV3JWLQaFBe3Pm0JeA6Im4CW65a4vIXb8hmgt
0EI8QWOY0L9wQOCeQF1Q2hT0KODR0PIZi8589848BFKC93jIXAEYGUG8Q5iDWlC30mjKgq2mDxvlO99s0OEr0TcW4uWeO70H01yCB5AEg64W4I2JGH8eOo2-
AJYrGIM3hE1K19KCyhVW953Du5OWHRAx5VT21Y81T08HmZMwGLCAgKuWB74PMc0vg9H70Tinji7Ue4yCR3bYR8EL13ysiEmOta0YsHlaDeWA1fs2kpOeOY0c
1USsU8d6DyWAVXI8yBMERo0HV3Mm-_L0d0KCn5l1II0PKDlO1haXtXEmP0zhi4iv1EK70iaHenei9zNdKO1sZ6jmaLyGs9GZHZOGoKyCVBV1u0PIX-2k3I8A
67GApW9oL33e5RvpTn-wyUCy4C2ntPmPl__ZVYL7G61shBFtYbSIUlurFuWKLS9LJGHjAExp6YH2DT1xTaIyfZMe2cg9e0vHCRL1AgI1G5idpMYG9ub5GPi2
wuG6zoN0DuIDC9ZpDVyDaGPLGN82angGC0Ws32Os8DuLP0IcDY01x3XQpy7Rb0Pl0I4da4Fnkivcu1Jamo0Dy9hGOC_HUaEXbaaD_D6wNo2MgGWMvZ17wwGN
cChW-WoGJa5R0bhdChY6hn41oYI2L9dBu9RLaL7OIWGJ6j0hTC9WFeDC0304NY077tCP48ZTH-iv6CjK1gdW3RQNoClCDM8r4Dq2eNKsW_Uq81S6fNoUnU31
Wf0A_cYzFj2QnU3w1Fccq0ow0dCON6kDM0D2BH4u0OAwJ58aWXiAKcSIh4I0SnWm5Kn0z0HoYanYq55m0kMOVHu3Zq3A2LI3rrn58euIKAjqcSN0AyWAL0DE
PT1zYIFv0pN6wpgN0VrsmP-gfi44NPFkh0Dsk-04m3I8k4_GAtD3GPjX83AY6U0rUg_CCinB7Arc4aGq0oY6Dg1JoAzfGq12H0GWPj-WmGr8W5v1Xa3waI7Y
Zm6kwmG6Mmhqao0l6_6ZGAqp66mhU84q887y7NCO-5BP2gH1_HsOmC1E1PdTGZLel_YwJ61W56GdWJU8U5p6hfIzWep0ja4ijocgH5ygh_84rG1wZaXmzVLH
CJ02xRVKla5Z6f3zKhc6GGuYge6oKyHpq6pGKv3TCehjHYud0QHrL8DxIG6cLFQRvlPdIj-WSGqwKy4AI6fAJM1aWvx2njs2sXLr2anXu1Na1D8W5QHr5WEV
5Zp1gYsbvz2NxdugR5-nUIKCM2u_GVOKZ437G48imo44oPw2toruWrmaRnCO50IxMv3eb8Y0j4vWK1Ny9IEgKcdBFuD1LMW2rI1-AwN070PrdMo9e2O3rCzc
o7F5oGnoAZI1Qj0KMYAOqO2v6_G6p81eOP3ZTPdAW4MW6gG2Kw0DZFOfJlZS80FYxS4I8fRhO8tbFpVmEqi4HdhF_m2E6qYztw4VbP4CIE2WWOZoErppfC4C
I1mo46BJGCegOJW30aSCM17qEmm6D70AVGF2NSAaG8wuZcHW5Ve6fFbfw0o378pdPI03Zz0tO0i8hQvr42FYFfo1Lv0bgE-LMXXKWrYkOnycUWDHln5acoSn
OfHAwKNs5VIRODLRZqr0PW4TfL9wWUmZg0faB1G5k58nXgcK5fS3Ug-LzQVXKauJS1_1W0Hx2gfDP4qJAVamoAomN4Smw2keDCOI0PSnlC2Q3zf7CEW5XCgZ
VMKUB0Os39f1n6C0WzvKK0gKWyHY9YDG3M8PmA2Z88cg1TBcVW5XAoM8WnXu1QP0CN3xXROULeCVbc4CV5gG8QWACc6GlptVQNsrmILOnpj2_PPWUaWf1LoT
a2mSOHfK1M-WqY2ZAMXLJ-3R3K2306yWHAH1KM0c0Xy6OngGy0RSQ3Hg4i4gZDAFknfuXNBD2eVG2uCSYkTrD0CIrQ2zHzonPNfdKHQBWzqn0VK9HZr2gmO-
4LG3y3h0fxBvgL1-WcjFjrN0vqTzdy5jYQW6Ng4yohGAAWAR-V7h3AxF26DW55AW6NJs2vty-7Lhm-KHqJ7mCrqL9zpzGYy_AcvVbGYI0Fi9b0HcAgYV21hH
zpH9kBuY3ay34U26WhfXKElCv-KhriE8JmoG1dw_q0c3QX3B_VmmYFZCWFGA0Ke4EWB58F0wVJtytC0h040t4LG3K75-8lZSm1-ozDR3of9D4fPpryDF3LIE
q0xl5-fZvkNyzV2uWSmzQs-_q1D8WtF3uBY1g5eT7Dalr318WtFNm-C6r0y3p9voztw1AN2YGKa4nmtA6omt5RGt3DBWxFMm3kmmyEU8_ZrIz0NIuFH4K0c0
7GQ4rNhRBuHzYL6-UiP7Op-ZDq23O0ougS2oNrXT8Z1NJu-p2cDlK1MyWUt3NjyZzH917H8ZbjkvYQ0Q60LlqFrW0dJ3e1A84V7lxA8l9X4O0wFW3Je10Mm9
sBP2Z8ZSHP-q7bO3X-0DjWE2kyCWxnuZn_tVBuozWLVm1bvXlu3MOX3BxOJri5iU_9Uvyy1r6uQ289pVcPVx7pUTgIlFYyQa4tIXPi2TNOZ2znZ807xD3MFm
6mFGWXx6VGPCOJw4dsVW60G6z3UbV1yoWm01deL0L2i6cG6_NFDzo0oOGlxRsoCm-58TG60o-3KG3pU-EFat1YqACI3vVk5815SPlC6bj7jHnET0KFXnZefY
00o25bmVYYnm8B8MgajWeWh_G0kk3vc12iIyNvXzY0JULpW7q9E-3_aSI2rKFWIPGCw2di-N9ue1Ps7q8EH0z68mV_WkC810k3va1leej4KmvPaOq7nc4JW6
da9J1B4NM0k-3vc1fm0Yc3501joJt8U-6yz1w1s2mC1huM76m37mHw5301Z0VFPz2FSBcWBt8J60-GmYy0my1H91Pg2r08T0C3Wndo46i9Mf9rc7de4_2dq2
LM4hGqzo6Zm3J-4e1laHC83vpAyBF8CpypaHY36eu0Ed1T-Eu82k5Y06j9Mz5ZG3Jw4f0kW5eOLdoy1JW3wS18212SIx5yl0Qe5ZKB2L_Nn-U3LZsH-5JWo8
WTV2qra8Dw70VUWOJ2rS5cc18J25Nmx1Xzo7de7NWW_4DIt461m_CatstsgX9uAvg1K3_hCQJ_S9nFplOWnWAulvV7SjK1_chIoqGEzON_TheIc20YUAjI3d
i-_9JWmgV8EnKWkNhLhen-040wE5bvqKAX3WhUoF0by-xGj4OH_2LXPY51_bU0gPGV6T4pFmhvttzsGb0iUFXYVm-Y3k8fTGg5_wa2yU0O4Op7kr49nO9Rv2
iOLWUz9heK04We2ubjwhXPe4w1kCiM0WBjR2w59O40DtAxz_FcyYm7suRJupWaKYU5Zt3QkdK2o2yQbyyp2k40YYs98Pp-k_NQS2cAHRdyphu0SaaG0G4Dj6
OI7zFfmE2-dsuOHOo0C8yj4Mnd-QpvdEX_tvd0OVqZlWRo6_Pmip-R0_dmE00FPXFnO481ZkoUbys7zM7O4FUImyNrSchfVsRKEmaC5XRC12T23Wypa67mw-
AHK01AmF-_CvkiE0locLqJuKU3ATDqvcpMUX3_aN9MKWu9_fma6Wmm8UnZui2400vBFWC11XWVUX7mldKbDlkzG-vB7W1m5_LesS7qgsdW8GAFFvsagsdGR1
Nhujfm04Wdm6VAZ40kz3loVle-nRJgqF-NpsWu3FPzw7VYpmFlJdyxdMlzjs4pxqOm41WT-Jl0_z-Spxq8-5UwyNx21ywCS2v4C_5dWV-Zsvrzks78GF_LW0
VAZVUaj1m5zzFkhbE_j1y0K
}

sprite $image370 [130x143/16z] {
x9g7Lkqu34LVwerF-V_FdGBAHGbc2c1xojCgTBoNVRRaMtvyhkQo_XXRcn-32TRn13y9faDSnmQH4COIY2u_2SnvQ10f2yiuWfsGv6qWWK39wqW2oXhPb1wl
13m6xSBy02dRW9OX8W0WPGA3eZ2HA210UnW10L2MnX6GicKPsmWLtmWiQEqkGi59O943pc4LNXXaSKmMrpE7Z2mE8I00d5ayfkxtivU2RDcMl7UU2604KRQj
xWGp4GYnlkHjG3zy9P0aTv_H4rDBbb-ANRCuHmx1Sts9chlUKCzo053kIR0I0Q1pVTdgU0eBoTjOiAobAq4Wo19rdiJIlI6IQVsUBM47ev8BGT2v8J9lW7iI
440Ya2IxutoSoM085zvEedGq8UQ2yleq-eXGoDIKdm2KZDuv12xho-YTGyg-H55hvnm6GUfAd7eEvY2uT4Mr9vWFdWW85J80snCy22O6NQ8Wz21GTk4UHMhk
GL0T2n59xrq8oFjOS91GH_DDE7Hp8NT5IC3UDWfR2k9zBA10BD3M-ZdCv0ApYY8AGBarGGxYLKKIa5iJR299r5HGd8hBt5g5n91L20ARsDe-UvLTI2f4Ccr2
fUKMN8Feh298MQJSb804gtVrT6zhJP0PaWfnPxBLbE3W9OXAAiGtPDdj7hwjOjIxkxgU11R1kMato4tvgaAuGAa70Gaggn0k0B8x4H2KeqGIW0ZQihS-19IV
bLk4RRHv23c37n7e-OqO4LuQFM14dO0b4uXoCm9-G82a9odBUpi2l2V8BJamn6DfjmVlhyhF72ekhpPQjAL7zHGawQgdR05g48LI8P1a0Gaf-h9jR2q9ybLP
1B8B16LPmB4qtOEuAilYnGKWsW8AsVeK52Pa5_1APGiqsxO3sla809vpGGujsNGgd9jUa1_EszTdkriJIFV7qh9iChP2vVjwuxI1zrBq0bnTq5kl8lLTGt8j
g1943hCBrwtG_4tF7W6bGk00kCw5d4MfhDzm03jGAW2qJJ0nIAalKlwclhGLbD-hGf1bhBjWen1VwmB7o_hrFP38cWkfBG0qllQE7vGF2PvJiUg2P16KZIyO
M52ULIC04a9s8KOKPElp16jUlsQZKN1nuNu0SIgSFczWAf1t1f50Pf2GxmXnTPVAzba3RmHtXbiEWPn5d5f8Ad_Vo4i0FdRXAM5KEe2qlbKAy9W_OM2Lu4vI
cGi0RQKdkLx-lkpJtpUmlWV8dznSU1gOrhVYFvJrrzRC0pTYA0YXwStS_xhfoMAzhqN6Cohf6MHuk1qba0euO65lmFTi_pWX3eb0AhXkXIu1sBq6DAJDYaWW
5MGDHg0v8VytHcOWC2Y01elYRh--NB0nCWE1L9175W1x8ox_FqOc28I0gE0D2dW0g60TXqVkpmfOajZ_DThutqWc8SWAg44cm3w10f297DOvu7vdWN68PPWL
y842emW5HkPjEY7uR5lK81m09f5n89Az3_BzRELr7EuOXq837_EobJaaCpV3stKDo_rqWN40cQqLwoX20MP1PXa7sNwqSh22bocD5I8AK12mH1pYOKYj_FKj
_9zKJNqSv0PSxfl2VeIW9PEjp0EGGJWPXyA0V07zy7BWC6XNnhq1VL5hPm3sfvD2Z4EsGWSC27SmPL7B32W8j6d930I6w-LeHTQmQO30SsJg984v3ebC121S
aeGfoDGSWMrH5mJEng4dS8ZCeeBduz0JE6z5Js1Vr3s1yt7e2UoBkYTmFWuzWNqSQWBdoUm9d2_gdi3UYiA0QJBd2EnV21K4ZfDP43WUXo80qt4e21mcyxaD
m0S
}

