sprite $image317 [355x255/16z] {
x9d7jTqm4CKiCGxPVxssVyvHmej02LZWt27_uF38KkC_PT44HOaxUjO5GkhnI4_ws9srnGigKGiZ_9AYbXt9FLu09ja8lmGPS4PuvoJBKk85P9ADy4kG0MSZ
u2GxrFPEifGl6W4CE8SQdMGZp2VPeVOrPNkI7MhRaoofnIRQvqcMjSPcwiT9bkMBeSOdsGZpINQeyGFEQncugMt4XbfiaEor3DpK3ZKWoLxBJ9ADC95aXnfE
ImurdBhwhO5J5eSQdsGZR9BveMQI-Q76qylYjmPDJrxBE6trMmEdBWurFiaEDPFC3JMJp0yrRsfug7bJmqFDcngEi3Sr4U7JJx93pIGlG8In0MSZ-9lQQvbF
iX7cRsg76fza8soI-KRmP8TQc6GimYQP7seEE3x2tjHy8qnoZBWasdA2YkTa9Plac7CEKh99Zda3wDW1D-Pa9NjJpmV6XINvb1J3aXrmyn6J32isoRHYaumh
DicuOfECAtx9CCcmOczgIB59vXMRP5xnfG-uvGGKcsH6CIpPMimlSS0nYaqohzWayufDCg_OcvfNR2runTxKl69lQbwn0uvNR99vnPS_uD89ABxuctezY6AJ
p2isoRnYaymhDicuOcjHbaChzgRc5NjJyufzvkGLE-1unSCaiuf7z1WccLCyejyGtjIKud_jt8bkvZWE1E3_ieeivNZ_fzt3dGXT-Crqj31xLW69SwRl3qQ1
b6owVHGhadE82G33k6Rg1693Vt6CgAYPEe7OtzxV749SaNmgiV-7-FrLag8Y-UGijjVt_J4MudfrQBuGybd_psFSCHaKzJRdSzsC0PEzlBqH5amV5SaJzV0W
ZU4EX2bHC_L4NJS6pp7WWN3DrBF8291vsWbSHVBzpu5Go8zBIYJFbpD2haXkF8KOpLYH7DGDd4g1uwWsMdDM0nVKtRyl7Crznaw0DLD7jV7Rm87n_lzSqgAE
EUSZsG54nX__oxwAv9gf_oHCuDFO8-9EQrvRXwOYMOdTFumP4VVPIAv8LkBNznuJZ_APjAYPMedx-njmIAo_SAJ57795ii7UtYma5bGqLYJFpzG4p27dzK8i
nOQQgUSZsG40GpWa7f4SfqL5ybV6pXuHQt4-ahqYcIun711_BvBhc9Dzfi2ZjmzFZEGwvWIFtZxaH2HN94yHqpwA5Sad7NCgCMsKdnB9TSofn3J0HeqkUVfw
ho8v9WRQlPaUBHFrCi0NTSCKiGFjSca1STqyHP4y-HHVBuyZOleKSaLoJ8nsstPWfsInRs2zpJaPoKgi9nbcP5TYymPEHdBDrC_4D00OZx0GTrgRJeiwvbHY
ahln9x0G-nuaSyZrDgSIq_S4TYDxGBodzNnQr4mD3k4H4H5nfpUhI0xhRY4nNURccBY7aLmDN1p98Dri52FYKGH-ClBb_0OED00JnBtxpuraTW4xvsrEE83R
3HF4Jv5C_XJWbvT8RZwIbVXfRkua8-8uajS73eXdQnCS6837vQR4T3D6nDB0_HXalhm8yNcHJ6i0jZQQDjbjeSHQ3bFanHzX8Jutaecz57WlVa5CBX_92dmM
iHvpwl4FgS1c7X2F8A6jsy0fS0AnpDHkuxjJQWltH2n1id0agt0AiKOo-JbG46YtHqYiIS9b8rc14uZb2qaTABZVBcscnEO7m9_XJLijaXKuWrXdQXqe2E1-
kSV4VZ0B4jGWuJh0wSHwp4c36z3kutRfYPW07WyzDTf_N8kB2YjnKWFNiDVdxT8JiSo28N4dLmDMujH8jftu8sUVWmB0NMR1yUDqAl9Qm4gS7CdZTkc8U0-I
1pw4XNXh2o2BS3vnF5DxZuWvWiJPbRWHqCJWIi1Ad1_9O43SNO94Y0-Eaha0S2fnVCpfpIZ4UaqzCaA83s_tk0nmFh4USzAQDcrZx23TsGDYYHb1Na9OYVCZ
6N0XfciVyKoiCJEA2m07nDcHx03nYr2kgHaGnqV9N00ubJY-f_RsGIpNr16nnCp_7JBLCYREhwj4ilyYT02GkJaY7iX8YEJSHpYVEFvetTo0nxL9KeJ46P6S
3nmJPyxKIdo_N6qynRfy3txuGdr20vSA71FdHxB1zbVeyNHDxOo8zxA4cJfHE9yuFkRq1g1jEBYcvbV4FM6cpWIEYVCRE1e0O3p2f8tKY8d9XDkz1E09uiH8
ffvnkerYH4oQEV_HI8w1vudp8va6W0UtInuGqyVLIHJ9-O_m0iHoJpq62WCUDqJ4-fnxtC3b0oz1hClLYLqJmEroYuarI8xVc6K-y3B4-keG0NO3jiiLOHRJ
D4ZsCdGfCdTQNeDub3PmvW2sSRlqJEp0TX_8ut_ctg7g8xmQiHvpqbgJsoKX_ipgopKc7iKiu5M8uqZMQ-f1h5-im_Po8NPcFyW2l1InpjIKswMdB0QmVRGS
JY5kpLAHASAB4MiaqrjCJ3kuflOzCK1xGau0NfRuSeL4iZyHwopuQId4-gNlNam0NfLOFred6e-8IL9sxmdnuIJ2X4PjAU8uaXkenEDpQXTW9UxTJuzazfVL
YUCkcRyJqwMFY8Xxjo0j4e3N8OuZ6OEOzbcCY2LcJa8Mu8M9uvbw-o2csIWFYJLcD2qIGdXLOjtDIUx4181X_0VYA98JCc8nulYZTSA1xN9_JegOk3E8v0JW
POZZHN34uQQtJWR4PqHo0BmsSHp9pVTpv8TciU_Q0N4KoGcFyAh4EbEZ0TZa3NhQNXJYOBMw82S0BqgiaUnoD26VKmV4Kv6S3zpR2IAvCxL7rzGUPx6RStwc
vaj2sVK4ZkH8fcESyH10G1ni_VuIEVyHzdi2JK8aamJuUIv_tKPI711ha7G-H_BVp8WjWILdfXvKUvTyWH37Mxyd8ZadX1Co8YkI1zMlfKER14MyzLk-a0hI
8kyHjjjbWT9ZJg8vWFPeutR9x63hznOG2t8sCBD3E6kF2FIQ-fbOPa4brkAg8PmVoNfD_KmyPa4b3f6P0OphPRMwczwIaZqWrhqCNn9tSib6BJ-IIMli0N6q
zJkeb11-BCGQpzGDGL14Mx-ZMhLHop_c70E5MRZr-vyWxdQxh5rtbovPYUDhQiR45S9V7tE2GapvWE_l4tFJZ5WxaaTQc7rlwtTKopTg-JFrPj_R-XrL_hIy
VYHpRFrko2PUlr6Rdwbr9VKLyyJLgCN8u1FnvHvj_KOcSSVjyZFhRj7MR__jMrJdDuYhKOjdQjtwtThHvzIvnDn-CB16CkEjtvF45S9QDr2C1VYZ9eXJf-Nr
8va68DZwdKBiiutQ-f5Cqk3ytFfzJo1Ec9RNcwd7rk_hPPiWhaPjOe-8utFhzss2k1grcIwPrcnlayVjqbV4DIrFBe8RoDh2CIQkHcqwalL3qua1kXgrYO_M
PUlt1765yEnCxMs2kARb_tMczbE8zLgZIXiuy0pYoeXu4Hoz6IUFvAjHcry4vvmahaPjVgRscFYSHgqYkSN45S9dxUOCYKzgr2gIupgfKQj8Zkka4Av8ZgiQ
jPDU7Ohhb4QjQcDCd7wjKP5SZLh2Rawjz4Qj6hZq4Av8haOjuMrEhTC_gwr83eZpFgkjI4wObgkqWKjlr2gIqwVbcgcpbb1LFVWxSRUy4AwPEZs4gu5BRzGg
afCRjQhjBqtB_mO
}

sprite $image317 [178x128/16z] {
rTk9Rjmy30JWUbUMPeOztlzf_uFmXePwX2baWn7EulmA36QOPFVBXr_3_kKplSSGXUUdyMwT8YcDn-S0Duhq9_QjllS9CPxOwWUOFB_YSTvsJk3YSMuGV_N4
VQiVY3aQhMYZ_VwLYyR-Us-zfej6UzUyrmzmekagD5hnEBUqD-9SFy2pkTLfjEfnJWGu4UVAWPY7kq2Z5OXpFi35uzmehdXItqe5kCXmFxguyWcjGACLQhgM
3KI1uKuqMe4uvnkjPDErsLiZplb6AnzdvS25XbisaSl7MMRtcBKgplR_koiQ-xP4VASPRPaueb6-wLnxQpJwjaHyRvnNY6-EytE5k7wSPt7zEC_Y-yrjcTXg
3_UChH_dcLe_phEqVfndP_qusnzVXMZanLNkqBouwXqw-rI-wIOReCfDDui58CXLxr0x0MdV2R1uqyd2BFtuEi3Ym_t0YSolDgZom_rac0c6iF1mxnwDTvvA
nNaRPj9lcVu8retphFH74Yert8spMMCWo9G9LAdXdkCCSCIWE5PWlJY7cFo1avZtnrbwl-dESTOW1YUnYL2fuMuAiyQWsIIsSd7UUfWb-rbCgbpJdUCyYqNF
Dg6YmpsBEG2lF45M9yxHTBDOeprSBAEg3NVt6CzYzEVHUAG1gZlSaOe1wlWtITQDiujr65zY6S6oToWf0WuCiOzWrJkK71t0o_ScDjrgbhah4sUEiUs7MB8G
tpg2ig-kojoXmjXtJuK8w2osU-BitgykVlTr7Jr1cH40S1QBl24QxWrnQhYTnTu608LO0EZiIyroRrRiJUSuSZpQ8OPd6WFmU0jsNJHaN_FYk4CziQFxYBp4
_Z-OXrlNUFFYk4FbSNRf8TPe3V14K8PBeX7UIPniEf4AiG-td4a95xI6GfiMpyCjy2KMJiCjuJGeMXw8l7WURgyu6JGDjmIpbQtXteGuSOUQA2F7goT2x5JG
bfZTcn1dXnlespWFjyIL8oW7Bn37S8_HkeFrbX9xlOZp0cz2d8kpC0RbNe1diIWbcYuHY6LYlqDD16NepUCSOW9W8iw9HbiazlV4aLZqhOVuFDnyaRKW40bn
RhZ5uSCTEKP_z3Wr9dFIkruSm-rcoEnDpF7iy4HeYaO-mEl5SOT60PzIuPUqYybeZLo0BnN77Khmw6EHHniVOelMK28GLukZwGX8CCKA7kBi2Bht7h4Fzn5Q
-71p4finp8b0N2xsuNOEqBQNM6VnkpUTxEkDuhX3ENeRW1pFizYcE2UybueZpcEubnxdirZKR-ESzdxZSw4uXjiC-mw0ugz-KpwRbVRQlf0RSHOXZxEBDV-c
F8Rxmu4OsoNVy3iDjxs9iJ-cKyFD7_BogkzrzUCEfTb9t9y3e8NOpSm7GkqIRSJP4njY3H_kIMoM1Lk_-ikKHvmFiUAu-3inKW5US8S2E9OGCFjhSRRHLjoX
f8auUY8Xlg7HCiCz7iz3BCtYknejFzmktXj0-OZmWs8yxkF6S7CQxhnuSQFbxr02CerzV4my1_ZME0kantaMtnxW_70JetT0DedJZNP_dCKnc6YtEmASlqEf
bDXwBX1t33UOI4MYqUwCC_6EMCa0tpRSeYRnFCcbtcFOzAeqMluJI5KQBVy9fCGF6HNYV29NQRJy9v0IZLOipeb6AnRdKesM-kXmej5gnNdwjKdzr_WNZVOl
}

