sprite $image135 [159x245/16z] {
pDffUgCw58JXd472Cjx_UczmVy-DWmJMSGnM_UafmzjL0Z9zlJEIfoddd9AxcwcgV0qKITCwIORI3Un3DwPFyXsp_4vKpSpTx-0yphAfAdIG_YfTvHj1DwIF
SxSDppB6kHknlqetbA_MjNqZBIj9g_CtaYud7Q2_JLr6K_a6qUd7pvzqT5UTlv5qzVaRQLbFjMyW7JLMh_3vPT5fVVv6qrNxZh0ikgPlA9rhvHjeMS-Dv-z0
kfoitdUKPNFEwCxn-RH4GhepVRpvtMLhdPnr_l35pfsTztoJokTFbcq_tqxhJzDJNRRJdc-YUVNV5zdJCVBnFb7pxwIKL_tjdhjATyo-uecqV93sbZKzq8UE
J9NlwRcpd0xqEJ1tKxLKdRzKwQgHinrs_coXcOe8NQxtrVrpPobdF-pyoLtt-1Uszid-ikWUSdy3_hPfNJg-SjQlixSztNJHLJi8ytnOnpMh7Sytspbt1-cu
Pgtd-QlfxExWcRHurVdJatNmsZYfVCHsTM8fVyVaN_xESsdZH9HzDtMfrdbwZ2zvPtlWyD5VVtUUghoP9wIvhwIeBhq-iFBwJLkxFqsFEldrUdhNkHhnlvGd
FfMIuRLmRPyiHdVdQ3qcBN7xCVlBvMc-b0AlmktwABqEElqvfw-MPrEv1nwwJf_jw-1HdhwmwWKSF6nzFd4ategfgiXFoVu773m5r-KJfoGXH6s9gl8lN_9I
UGRkWMSYtJvqrUD0qPajlBlmVa9ZE9qA8LFwZlJwH1FFwBPE_l7q7ayfvSYuaa6jr-tsyV7DfkxE8-axbp9PSDUwFfKU7phNJHsyX_Bk1KYqkZXFrV8pdJRA
MtBfA52fhiMpJTF_FncIY3UNHLMNHz8pdPVIpmE5Yg2pLNk2RisZF399nx2TF4safLlxqArvHdbaTs2PIeHdBHW_UePlGmUFydYln3TrbnBY-I-JgUhguQ2o
hJFA-quX9CLryEfj5HDf-mHTpNFAU-xJgSHujlkSqmSVkff7UHq-GTVDKz-_4sAIgZjuLNcxlgb4U9Jd8izzjKuVosiUAL_fSedolDgswIFQMnwnwcuSud5X
IATFMppAQ-OYrPEiWnVOLe1WQV1udhMJEmyUkS3hl3042RecZ_8sue5fuNMNLrq5DO_oDdDHT5A2FCgpVHjfwwnLNdlUrCjpxRWmz5dW6ULjHoalocFRrt3m
kAliPQAy88-Bpi8uqbSUzSabmeFmOmtZQEzfUPm-Am4U16zigo5TuuE1zhrvYl18VTFJWAwZFE9i6-FPUjkO3HrtbVrrjGHvrOMXKHoytF5El_m5NcBRCAw_
FA8vocFR5t2HyeXFOHxRnd7nyagwH7bS6A_ZpBlBAxc4USxluZPqbFTMNld52-hYvP5BaCUsGLjzygPZU5mOh-FWbKxUDS1Bb9UYjhgyetXEYt7TunS0kqUR
WxpKi-sUZFAEu7LT67kqQ7dNMuHdpxTz9ajvclfrrrlluSiBpzYsGmUiAJkCjr_UJcSvAEFatUO8ptVAGzOgxG8jcbkvKLyNRwUyjyh8TU7D_Jo7LyjIIrR-
c7dXKLyFRucjzWnq5YxlpfiZF5SIlJZZcHSUzVNnAEze6UN1cmCyPE7RHZmpFEhhufqYepnu-E8yBe63TF0wvyqdoSWChzUNJvEXWzSvRsvTd0TE2w_NX-nK
7JnyOmGTlE5ywE0DvqC7RoGVkff7ve_hvbkRX-ywXgxcaUiGmnAuGmoCfUADKU2rGQ7F0KxWt89Su7swm3PZBZFg6lZPNJ7Ck0CBdu63TxtnZny3xhx_woBS
oVL3ECgxtkPo8-TNkDqC5qRXtj81FAyuSkLBGBnSX_0K6vdv4X3rFHLUpxDnLrbur7UA45kVxh_sxYkxKXW8md2BgAxI_hSxUTf1sD08XGdrDD7-RthWE-BO
2CZwwYRYQff5gOKwHdyZBEtYtX2GzJaZSQKBPF8ExmZ8-loL1833Aklo3Xa1COqp607PIwqSgKvJHa0SfkwOW31CtJ41OQYwd830pd74vmJ4ldMd18H-SNc0
7iIpvmkhF2KWTAd3AG7PyyjEJnqk4X0Qr-4w0RKFn1q2Gjiu92y1WUtYN0H4RH9851CGEyKP0Pq5WZNR_0IK1u8Fj-5f0WAVQ_CG42_x1OeJoUm1bn9G0lI9
H0BL20X55zK4K9k0ZgxywRXMTxwBxHIGzRaJhHFWwm4V2G8g4z1z0q8Z0ag4iz4DBJG2CWvopF4yMfXhK4sMH-kxRK3vQ5ctwlYMW30c0Jdw-X8G1YKWwnke
pl8QzFKdeFy4nFy4L4P069w0-hm3ZsrCF_ftR1ld9o0sZtCI4Dl4ZKn0l4T0Q4j0z1AG1Q9Q78e8YAq8A9KIa88LsYpkDW6neD3_DViJ49ud8ABamj169oKf
NAU0xZVIoWe9o6z0z0lGLG9ARWA2veEDFsQ_TGYGWu2gdVO2RnAG-dd5NzQEW2mI5Gu1MP63WDm6nFy4rBdEyj9VGq3_2OW75vBiJYnvX0v4BAPGGnCGFoSW
PRSNzeo0Kcy20hFht6wdRCw_xwuZ4L3sJTSjPHk8WEObvUCe1CGG3Xi68I28Q3C2yd-RJMGz-P_r2dbwq6WMcNXEGEX3G2hVjZiE4lbM-eNNxtdJLQu16ny2
2l9zqG4iBGbebHyBlYllkmH4mgKib5_RKbq3ebssUpviY_nQm3rW0QpITISCquL5iSs5jrdXQ6NtWN4IiQskDtVj-y3ifRN5giU0_D2ooPi5t2GWe8e0oRjD
A24Wyba12fBrCRMOlyxwngopFWnJDswVMbss4BlNHQixsjQvRfFFjx1Z71SvswJTwdII2riuv5DdcsA7kZZ9vIre78T5N5lPC8wRU1SsDeiBOdC5ZXbdWIig
ns6Rf6IBrenRWvHksb2bZViaZopC4K-tnIN8SmjBv9Xjjdd78wzfXJPx4eiI4TSWbHVcJK4_wErB2D9cOPhNgEILC29konIa_SAyh7jKyFZvYhlzaE6x-me
}

sprite $image135 [80x123/16z] {
hDA7ZiCm38FXY1GL9-__m0SR5epgkbFUxFhmPsnlpMBV8oIvRRzOj7sijVW1QD5acva1-WKOJLlkEcZ9_GXCheBNENe1ht48lrfeDnph8L-lSo_WjJeFhCAB
TSbP0I_M8VWT62tkSlhoedZRiOsnSlWAv3x1y5lEmpu73OW9Md9OyeSWrPVWVyxu4GZ92I3QB5JXf5culmEQXFbF5bPkAhOtVrtdOhdAbIltwAkw_j42ejOb
zuR7zRzjlWwvS528w7lNipvFa7cmoUNy6ST8p-OI13Q30eO-IZx_saCCQcSJbrOAjTQvyP77UOZZF8xkJQY0FObZe3i1iytyKPuDhNjkTq7lHNCWG9WPzC1J
ryP2w5u1m-NvIIDXtGDSU-D_3VlGqZDR0m0oBsDo00WOr3kYSfnnnIFTtQKnfoKtF18ZxpYEi-66qzIAX-5qSWYaBMvwqj5t7gpSsfuUvO1PheF93I_pnlY0
wnvjpCk5wU3afYUreu9ChdgGfxJ0mQNdYcCDWqFHbaUnS41oDMzSbE7jvmCF4eesbELnvYMecwEj7kL5owNdcPUpbLSy65meMl4oRmN6XeejJrwqocNUMZET
3pnGV8Y1WzDHTlf-r_E_Rkr4Hv4O1W8ePqEgxF__tHKb39XrHwJ3dhNtCK_EpCGgJQERTEXeyYu_UOichZnzD3fQZ9TpQMlUIOSkjNeyvLfvrvjtFdSrZLUc
zhGAQYouycoelTjnrxZOYENPM7lrU46fUfKSLZoDLrgYP9MUeUi5TUvJ4T1PUUVxSTDKEc4_f1jABnrmAQWgS9gpy9GXIg7J19PUK0FSpJF3koTgE32JvmAd
0tDv2PpZv0KupybpWSuvZkuMtlo8U2YaMu3SAj8U2FJxAJ498DqYFYw2vYy0OH2Vn6sQneE3RYznaVWKos-B6zOqu1lPDm5cJBbHD4U0YPH9u8s5AFF0CWUd
VX5OcV7t95dyTURGp6a9BDL8achEjLyeS2RY-DWlr0MSq5o2oGlGVFjmuWGznmNTDmw71ilxnOrQ4pwk6Pgul5_SgRyNEO19euS2MbelnIsg4pSphoi3pVCo
2DBxLlhFzkAXMYzWSHD2YljTB1ZaVIKnI901vEj1MSAIPaxGOy22b0em4kkXn1xRMP-9zSR2shQA_vFYQEf31VZSI9egGb9KM2c2Q07sbalnfvABFXJWr4P8
VOZcKvpnhGzX0WmWzo6QRzLOzg5OB-CBfkv34iT8bzRfG-30aBhk_JuK5ya_cUoXURSF1UaTIzX07uex6ic_DmB3VKWeQIcwpgjzY9_r8TppOHz2jm-rNz27
gFnNVSZc-f157_9lzo7_QXy2t0ByHX-wNkRwaB_reUNewRqmsuSEEsplGw4zXRRRdOlr0csi3NteziG0t-j3JLyUD-_s8Ru4_JvqVtpgbfDsPavCNlQXUF1r
NUz3ckcPRX-w21Cuq8TAAxZ8PRuFYNjaSP_ZbbtEaJx1yPWrFSarttpMyWdSiMthGqt3LJbXl0-X_t2rZVMX9gsNmu8F-v1ZEVIj659ae2NbXkKuycAGqwBD
bbbNZEroslBobyDfkMgHH8XsNKw7dlK3
}

