sprite $image193 [243x238/16z] {
xC-r0GCn402mHyDv_td3q8QgdBI1fj_OMaJqianPp2rkjYpb6WzBad8yRVdA-zycbSSjF4QUyetoMvILbPMLbPMLbPMLbPMLbPMLbPMLbPMLbPMLbPMLbPML
bPMLbPMLbPMLbPMLbPMLbPMLbPMLbPMLbPMLbPMLbwtKjgKf7ykxq_J6KI00m-nGHP6-_sqdoYXTZunfOoI3mTziMN-yWrZKSMnjFU1FGQzFbje6G0wyN9gy
SG5l0YiN9NlZcNiCp8BapONbmEkro5WHEBKC6KijEgKbrhNAXYMr1tmkhyJ4AHlm-S19CMar0xpKXfKDyE9JMbh0Su5NKu5T1bvxIYi6dwpNRQNwRjWbdPz1
Eyr12FR4KybU6ZZLwwbWssvWbSU6Xfv17VxD35YrHanf7YHqujbqm5VbrG1oXo4Uis65Ph8AsDBuCsY8k1UV8rl0bnVqQyZVOTnwXYmzzWYyUWrvpus-gCjJ
UZpP0FOBp4WohzGzWw07avN7te5J8yawu830oc5a0pYcO0QHBU2ml1f1zZWoSB8tMGOS7DY-P1LmV45t96l0TmYywa3EnHDFwNgoOV7um7OWsqmyuvJEoPE8
UKgV9qyYvZFewyWMtxDWJfCd4_EKRYVF8-QSF4MUICo1lPhiyEq3qqwUIyn1KDUH7U0KWPCNaItWB86LBUGPnLpGvya6SAh0gvDaFPMOftGxMG5E69XsiWIS
iw0RoJBWj7dLHFOuSM0Ro0xd3iopP8kp1q4_HJQ0ymTErPCLu1A1bPLa6N2LWgaZUrmdyAg2R76fmCc7PC350lk8x72vWlutMGEkbrTbCb_Pwqxfd6nnoS2K
oGeMDGTT8WkFYmPU5SWQSDN0ohja4N3TWYdTIIsSXpja6N3fxf25-Joo31z75kRpo29y7bd3nv65_mWoQC4f-0JoyRRIBatca6yh9QoDvSAo6rKijkGAnZmY
oiZhhM2CfPJkaBtWx0Bclrp6teHggSrvzoRMvbd1pRvgxznRBzrRhpa3SuDJohYKZfUr53UvPRpRsodTab6BssIO5anq75owGqOZyXHC2AODoALK8djnBmFp
WNc0AHN85RzeC26Og9Ki_8pWpTPE5W6dYC7doH8c6UB48toIB1HC16RRFJANaUTwR3Q38pMGfpFp41Cradjipp6-O8WfFI8JtrOmkOkP_lpvaoxTcM8LcRPt
Cd8FS_mMVyMhXxY2_ByOCt8FSunN3t5ADUJjtpPav8dMi5rIGURFeSh8VStqzKKdnPNaVOmfkx0xFvlArubrR3FiorO5-Q-OikMhxtFcfAyKJmun8n-GjpVf
2JBdtseQrvCtAcNaeSz66IasNDH43ycy7LEHF6BXZj-p-gjXY5C5cQTnJXxuRCbyEAaMLv9PN2AFkhWZLhT3giaipibZdZEvVM-g8VENdoKBwM2mEAKASeni
R2AF7-XTKa-cnCGGciayq6F4LMH-R_y6C48OR2NpGCCOCT5ZSgJ8NnVHIh7bOXkPCp14d6h8Fs_kRtj-s8y_IHRITGFpvlIOpDDu-mpeCqymcwTynwMwahn5
EpsH5QA1F7pjPZ7LaFbjz59SH-PCw7PLfrH39jelRQ_4RHQp7wYt92rq6EDQyiy_szjen9qSxc8hk3T2ixYEp5FzTsFAqpu01AU6lSHIlPXgo3iyaPUYdEHF
lY6QnQdsmkQ7Mhy-QG5U8guYqwywWX7zaYR0zMjr1PaVGv38IT4tHbyePXk_SNjZl2_KGOd-AGyNYrEPVFD3E51JlWOYY_cyN2GpUEFRAL_QCnUNoSHWeeXE
Jla2hlbYNIPJv0SlykboQD9uE2akaFbJ6vYo4_FWeOPJInTHJjwi3Du-W4QADqgx0CqJER_xPo__qCBBTtmTQdXQd3r0WBKCJbHnkXmthQ5b8ZFvnlkxTl7f
Scerxq-yD7EKzjrwixiLNccTBskM7mUO_sUCcSJN_w5eJcLk8k9R351YZfIl8LFH-qkEHioJ3l6HEAQ3bfYxhzvefPWfQI4MrNpAs3hygY8VIxmIioNT3-sk
kFJZKTwmG8iPKs7NPUIyumaRZ9Wr0_6t8Zb_u4zskfnlIdCbyk6c8cWnTzBT4ezcIaSop0tcALqk7HzUxCGQ6QWaUocMoM856PHOAUdn0HcDM2qL_aL6ArRC
G8bCGOarazcKvfrusPJ7Z0n6h9qEHtIsCIq_fHUTnEKpQ7QwN7rAenMVb8RefEZJVm
}

sprite $image193 [122x119/16z] {
xTc7SkGW40HG4yHgWdp__xTtEzX8vTx0cXfTeftZAzIAyFOy2p4jRxyXKPXPqc-Gaydv_v9LHFu2USfJdlAKfppbAKzvobEUyfIdFEKfnrpMDPyicygMDPuf
hrKbOYRc4iwQeMcgvQel_d2yNAMMPZlN7VBQDB0lqSzTYE_5i-vGwjw46QmxXF1qlEXYtUbLk3oUmCrttF6wip2pn7i3lbItCoMyAlETBPMetwrrvnTbkIqN
1dYaRfJbjXnMSCVhHdbWIuDD9Op8cG4UgRjVBWmPgRjVXel3KDtzSXY5gxw4rsJSgHtg1XbXfxfHHjYbRfGHTgWRP0yOwqRP1svrnwVo4Dn_kuJonGF6soMK
YmUCTySeBnum7c4e9myFwqOvaeU6TQEyEd5uGZrPnhgRdFcyb72GOT3ETJSP3Yh_kdSv0EnhamYSIKvAas7G9ycd3vgglE15qZzYgKTtEfUrACC5sbFLNv4F
lSh17nOrjaLpRJgTm7wIjelfPN-K8rUtejVFhZ8BmSESYrlLJRRhvrLEkno8oSrLKPHRegExwIEvVoyZUi4ryYYBWDnzao3zi0hA37Bl9CdsGwZF5IEFieY2
t4-BRV0UU4DPkGZ8VNDIfXA_lpCzSL6sqoSpo9O8z4sSLPY9g7VNgX_KWdB_P6j5ITwLRiCYYhBjSRhtZ5awQDDr4s8CxbhrWzRiCYQjVJOHtTlI84lz_WRo
o6mlme85LtZDjEbHniJrUtOrGBRlAMVhKamUN4v0MAJAUf0_AYumipwoX8AmednztThZUv9hOkUoKJzirb6kuwN361SYoe0Ds0RhJLcMB_-sVvcEkaVyHQu5
Xv6bIUg1RvuxXbOlquKQtdquYS6KXzT6LpQyx_P3nLmhU3ofqDqBiuZkpOgOAwtWyOHzgoEy3rR4FjjMA7W8p-qumwj4ZPgB1Oyd5FvYLtLdnGhsI5pb27-q
McDVR9VmvfH4yeaJjx7M_SmATip2pPRFs46rSVPqhMuHGxarREUFuc1XtOqrsRLWhBlPTWGdLmxhDdbJNdmjhDkY2WMVKhU85NnwCjDt2lu9
}

