sprite $image392 [113x104/16z] {
lPRhckCW3aJD7PMWt_znTx5nH5eRHfFPf7xDjS_dEb3syV-Eo-7uQdAjsNsLDvBSDtaZ9NoHDv7-2xnKrsJt9PuaVfONgqe9N-99ilycxvDN95J9HrG6_vBt
2PM-WDPJxtUuVxyYBWD4e6ZX_RjAbmWq0bHlvhtVQxnm4pcgSYQUVUtSKnTdcn9GzCK2i_VgAaNvJG4zP_0D947-YHS8X1hkmu4RymIsyuZ-P0mW8g2u2pvv
DPMta4HkpykWYM1_fCTlSYmnreK88_5FF376FGiy9G9AIFIt3qb-HnDZ1EuD3ttnH8DIoFWh9BOyCKPedK4pIFbXSlHgHo8OZilD4rlLor-W6derylAYhu6M
b5GMPBOY4NSuLrxo29IJD3bKMgu8elMuh3o1o6E9ojqLGR8V5z81QiealPQuxrLuzkCYh1loIsL-ZIp8RnsN4PG265HYHMvvhcnv-JZ2nE199VIjdBX2PNjS
jdN6-KK8iqhDinyNr7kQ24HMbLGtl8I51r90TxNG6W5xbPBozd41CG_xgJS2-I2zxbIYkBUE2oX60XfY-U7vKsuCK4IbUd61qgi-cVRwN0PuL7qVSrSXvsLH
INbzSSql59t0m2jUcVOg0VIOZS946vMBZU8F7SSya6XQNtuSAXAYenyGoeihKcC6qRvNuX6jZsX-A9P1g9VAmtCdGZpSgbAQH2gW9LmrC3TcRbeVWHlvm-7I
vmh0JEqygsVHMUxXfLA-2-IbGneO1n1Qdpy9XVizDQ4G6ik93x_UbGHwue5R5-1An6yUBbsn3hL4zzJusThyRnq4h2hhrQVWMjD0-K5hve5sD7A_jJtpIM24
OQ8pWK86P5BhmckzDmsKQYJo30wufgRwUsfgA02twka7r-ZvUYE9ddYjlG16G8tPzOdV-j1ogipkCJMX_Xg2I2hSUti5pBznkGADqpsUumS2ZPy9aARb9uY-
WHEWNb89A9nNZ1ltnu5qYOZnJ93NrYXN8dKgeCoYUlVvV17ICZL4SwaSTH08uD6yvxxXAM3a_prc0UjlouEGZparsPr58xVsMz_Aqy36W3wUUH3cbZsc9bs4
tkOGk4m4jL2YJu2RbMdd3QpdFFiCSADudjMRmDVjanvUrBa3haXmAm5zwZl7hIzJ4x7EWWSsl2rmwVKYBCy08l8B0O_XwrjzU-3QAuWm2Ouc8HwFhvf2uD5y
wLfVRnQWHavBSsekbVuufuRyLJIZuyLjjm6rIlUO6Y7C8GYLqB3HPm2gNXj8fYPEmZe49bxhTGDKI4K8zn3GJfyTg5NEmrCx4G2qukQqwTjk0oODNATd4Yvz
ePxZ5betr6a5wbuv3S8rgudc46nvTY086ibjZkU8oo1iRhiHA0ZeNWaGbww2DlgCm4aJe3eyzsdrRLEd7RWgUwboT9es-an0vtm1ILQWLbdh3vjv6fXoBgN-
DpHJpon4_HR1_hRlWP5m8QW-v_L36exBTaiJ2MiDiGafTUw1PL5Og9gGmBkytZWUIu8grDehjsx2ePNZATEa2ksHRC5r1hUV_0l8CFTggbDm3TpwT2YfZHdM
NeLdQxEtrd_IyPo8WQnsfEZRuxZtqMeyL3Atrxr2lKMus-JrmHM1QzokLvgFzKWtockzLtUyIA3NIA8dOEiMUQDDX6EJ92eLJG5DyjAnZojQ9P4LgEMfDdNy
Sw-WcOijG8iyVvWI8KZz5X6WGPunBlD0Qf40U0li_PBNH9ujVhaYz4GIuAxDLaIUCV5I2Jae6gXnkEIHKPwU7ZwX9g1S1SJZlRZI-49kW4fUIyVx2QGUKW5D
ykn94AG22euDyioziY0rq2xF7az2L43PCOCySo84AK2pl7--8W9yIvvzUaQ81BZvWh36VaNK5yGdagJNGGBa2-93SUNn2INomYT8kjSFoDjEpoVaxQT7v7qX
leudH3Y-bmX-TyV-0m
}

