sprite $image421 [136x138/16z] {
nDS7Zkiw38LXkOldaFlVxWCn0fvd2CLEBYF_KuFwmQHR6TPoL07MycpJ3e0aZxays0O2z9HxUQfLw8gMoZF3cIi0_ghEpom6-BVzaSM8wT0pPv6W63wS3H0w
ezy-3JWIoj3muSoLeV73cNR6nWzdW_ADL1vPZ9WU9RsfylrqAzbLvISjsQkX_2ZCkRl1q1ExEk5ZXvR43kKf0BSLncyj1o0YkAb8TSndXNYt96gMwfWaAZnS
AZmjIQqWMtBDK6r_BDSnrp-hqQ9gvoYePvRhsFah_4ZGLSJqEtSsu4AHxvWFCjPLg7t7iV6TWYBDWHI5MVd7XBY9w2lKh2OuSCFWzHLOIeO3rmQlDn9kfQGu
l0j3nw5gUap5ozaFeAleErJDP2uf2QbUaAZQXKFDk9QS9gWN9MfsuL3JlIIrKJL0cY8u0cD9UsKoFKS0RIHt75lMlLx_1ezgTkrGgoMbdHOST0VjXaEDKqbe
XQd6UC_X_o-9Yn6xSAIUiDEXffruuKYyXcxKq2r7wZLq5X9a7_BQeMPOSzvIuF4ZXrhMDNGZMhpZ298wbPGg4I3tZuSifPNq-0NlBOUTpjMizMZnhiF_PTrA
OaA85o0zHpFC9RSAyPhafUF703UaDrSvE_ZYEgPcF9eXkrMy4wHpdmjNYjnsyNe7nFw_xtUk5DapQVrsc2np9TqHteooPz9tj9UXLGYQV_XMctGTvnlvj4Fz
mvUQ3ZaL5hNEf_7vEJ9WDSBnCAnbJ8jq661RZ26jFGKwkp1iG_TA0Y1bAQFQWw8kZWFvNxlcSHr04C9G3M71qt-_JaTyDzz15VotIDf9Bw55ZDIdp4tVfveK
Ayz8ljP6Ye3HXi18RUZqZ8a8NsCKrbPIKWYCq8wUcPCTvGLOO_vXIrChwur7Ip86ncb2NgLYOEGb34MEy8RE22p17AqTpRNv4Q8vN6jgH6AL38_QC0SXAo54
WvKO9ZMjAKQV4_xsXv7PPBYZ3yCTgJr1tE6CiAWOtM6ZIWcX3KXenHZB0ncBwtyia2xDonXBCSPo86dnKM84UnZ57l_sC8Wz0cAFXx50LZ6MG6gSJMz0sjJ5
s40PP2qcI6m5YIs4us7Knqq8HsXHaB-j03K6vlZdwClWyApto0wE7HtFwdUOmR75qg55lG4
}

