sprite $image215 [294x265/16z] {
xDareXqn50JH9zO5xN-x7Z3RGsP_LSKTdRHVRwROokiy2bL4UWBYh2Xx7OgJigc8g3aKfqfcQZwkb52oCQPMGWabb5122IMK30gKK4899PHGGebGEWWbb512
2IMKOfUCqeqJM7gSKQdSLf8zJIYTfAOYwYEZTAgqvEDI2IKVFw-44ag64aeeeVH7Qk-LFA9qL1Rze2GLfODKHJSbL_M4qe6IcQgPcovInqeecIwPZpCbb9RK
nxXIGid6tr122QM4qgzGGWcb-9ygeOGIIWcbosANdb2wSG9BYoYTL5NML50wKp9JKH_dIYWjZN6fX9B_Z19AAA64ajzH2hz62IMKGlsmx64MfTXwVAIKH3ui
LV8KIg7AKWqFbAgfwhfqLUzlNcatsYjFb3Qc_GI-K6flGAd8PprGMb9Hyp61KfOlqzjA7ppVlbAMRrEKlYXr-MwAqfT6fqmenIPdgQEq6vrdFhbIg78ZjPcL
5gERzJYjKf47rJ2bKf67bTUxzkvqIKuTYUAuzYLJkDx_RISGLPTEWwjFoAOrPDJvFEilXFhFnSk_KoftYqXynUjJmWC9NtQwbN0Z_7gIIei29I2Gm8MtIXbK
qcpKLxm-9JoGy6MhJmatmXUrAjbO_-MyIYNO2Ay2TKgXNh1aLIc5KgzPqA64H-Hu5U1ADj5JYKMTpfyhzT9b2ojPglyfLT8HaVXW9URz8t1J4aZu25PY8bgf
bgLfCS9712frf_xCDJqHYOzWfMxKbVH493vkTrCATSA8RwKKIfqpQhTHygNE6oTOIQ4Hle0gQOn8VCLZIZgDy6MBA6cDI7mHKD8RaVW2eAGs8l4L1oYfZKXy
oG9AQetmHLH9Vo3XLI2LFaRxiaEKz0SIVZqveVGnaWk0akw8nA-dSoLVYliOFPVjGMb_799L7f7uuecIezf7wetmXQCIF_zM1wi-8l6L4oNk_npOAWoayT5H
YPTLwMCaHe2Isa32HtIkz36IemOegGqaVDmEIX-ZuuYbqlzt8CKopmbIcc_Ktmpc7T9iZ0UK9aTaSLCpdXbGclx9FwmdtkNkDUNd7A0qFoBZzgUG-fAj2JD-
TGgkD3-GOh_vSlhnOCALvaTas4vi2Ix_h16kD3-GaZKhZz-UlPygoW6boH6PKwork51gCEbd3jA0qlnF_jwLzNgonfZo8mVfxvLc94nseHHhGaor_CX1-dkb
CEsJMSZkseFSFG0b92BdBATK-l-0w6tyWOCabTf0HCvxht9RGjbqIKS2IhVuTQF-zOQNBZr8uqekr-bBvhg73L32ZEQlU9ik-V4FAU4HET_f-eSDLv8HgNZS
5a09ZKYgVKHLqwWR0KfWH39Hb-UgQAi0f8H693FJAi-g3XAgX0RIwmCwA_gOz7uab00ZeQJy8E5ACf2aad8ZNAaRQLRYjWmgoOZKh4JT252ovQKK0IDTIemX
BHI__DN-nHqYKhCIjGKS5QBzh_OFqaYt4Y_mg3p_jeBUYK64jcebQWi-gipTgSi64KWgbMH7uafzcsmGHdgLg2r3IajV4844A6aomfMwaN8b5aW3IYdLgai9
FqYu4bNjIjoM7rOYLGS9LsBTIhoCZRrGgaG3IieFKal62ANa2v5E9HezIEJCxqhEXKe3IgeFqecISua8L59lj5Hh_g3aV2PIfSIZ1oaQSwxK5meHeAJy81Lh
tYYjYqI0akQ3nC6OxvISJqI0ajfREni3A8dh2L3Irf46LEfLG82IoeE4A_Nh2L3Irv5lbQ8J4uyTeAIf8t6bFb-802L57JcY95zQnfMOjl_rT8EE752IBotZ
IhpzyVHqZux4bUJrDA8qO3kt8qULn4lB1AL9F_vn9RdOhoSYelx_jp5n6r6wGKSEACcN5df-CMUYjanGcd2GC2LvFJ5tf_w_PqZf7XqfHooLVFJkpKBb_Tzm
WTB4ZiILV2BcjoSgSL-xG6bkH-9AkVAwC45fUaVYIhojTWu_GMb-H-9Al08H9Jz1QNf7uafXLMAcU0kbyOFK1KQLo7Ubnbp31AMP7OahRJIqF1uBStwhH1Se
JUj8N6b_pEZnw4p-ZH9N6bQQtv7ZIltAVYcrNm_cTsUfkaGqfZI_8yULodvowDSZnyVoKhB6kdLPAlMNbW6bkHtfpBYI_3f0xV5O7hzs9MEEIiSFmRZI_8x4
LxuejV1LYPV7uukIZyRuS50wV6d1bUPt9Bv0JwN6mGcbbMdPbMeDeHMf93u4WqgpEt9mgIjLJvIaKjzBoPPQQRKKIk9B2wOqyo1bCpwRUJMsYUjUsucaaYcD
ZahoGp2aDBiZn-TCdojSmduyM2ejhRrH4jSJe3I_8yVdYRFVZuTKMlT6ILG1e3I_8ySNlrvFaI0bu7e2bUPt97vBrVsnI_yfLK2fNqy3IlCwSdokV8bmK4b-
2CQLvdVa-49otkDAmFKab6xGaUYSbqgsD4H9lBGCAStlo76d_WCGLEeVWX6bws_jOitbyzrfVz-DZ2d9bnQfT9kEn6T_TogGahoUfD9zEdByiKkGadnfaKgt
wSXn9tjGYk6DKoGQLfhVaUFNKvPAeJ9d1rnFGkbM7OdF-dEbmkkIapk-j11LslvTZOXlsf7uOoUL6c_ptrvFJ4JCRJLQ-AOTYJkTAoNtVf6UVqm8hVz6lcb7
ubLmhfJTc-ssj1qElhWZpUHPVwuK4QNzM-TDEnBVcH95Dw1qmux4bmvAoRl3Z0MK9dJaBAMo6ybNOmietReZSQKQtEdCEa3fJXs93tsFCy4AfoniLNGahbJ-
g5Isus-bqjB7H1V_Gjlv2_HIQiUOzE6bz8exUrGglX3Tj2FnfQxKilC7fVoKCsM_AOvAsqlBRLz8y6zHcy31AItDxqfBoxOp7PJaX-1xTIG-xrynBfqy2QNj
KhLdIivd8WKT2R-qY7ctA_NLevBu4AoW8v4ThoUXn4SbyI5OGKUEEfa4AVKFmIew4l_I8jexCAJaV57GaOF7QUq5JCabLj2HOqxMcFXLgS1AU4VUT5v-kIke
aeAE7FyGdFhbmO2IWeuSV-mYBurC19GKTYJkv3CxOm0bbHs9FtRU04fgEn9_QR7VAMNMr97ZLU0G9RmZbJe1Ikew4h-US2My8nKw_Ld9no2Kr7Oa_jWTbI8n
Pw6ajoFnbnQfL2klIq99RKVYrvDKah_gARFkZiGVktEbA9I0ZbJkTAwKX19ma9JFdoe5eGHqfFRber8DJYWDTAHw9KgYbqOwKhzIzgAz1pfIlr8DuWq5xKZz
IjXx7DwH-fNoGGdwyQz_ps0IpvjGWZfI_pnjIkHjy4Ubpq5wBX8_Ax74WnBQaVfdSxPcdUCQXD9PHtxcAsT_ejH4HtuMY9ANIiUE_Cmchb4eoOxyJFmnHfc_
xyZFzPJvcn__dqMYojzrv6SsCoC7wNCztQ0Z_mS
}

sprite $image215 [147x133/16z] {
xTWDRkCu30LWwrzwf3ptl-t2X0DjbXsZAbF52-HTO3xGoYEdsuBuajrsgtW0xMOa8kRRaVh_bFGXqOVqd0_fG_gGOatl8uMlI94QbNkH4bEljoFjxoFvUqw9
tPsc572GghiHAJ4EbByLYOWxQr9_AwbhafxIXwH-Slcdf0_9vHflHghKEDwDH3tTZSHzvPHq2PHxaSgxfXHA_9gKGSnKbfDy0P3BLwHA86Ai9GcejGRWAvBi
uhKabu7s25YJYFjIaijDGCFqPf9B3z08_3j90j99p__uGbAi0j913MyXXOfJf0CKVqrgGbe26gZi_arg4oH34Lq7BPf9Tf1-KWj8geWk0nGd9Q183iGz_L8H
NGSjDI9DQhABqwkAQ2u0DCaHWQWNEoWAQ3eWHOAChfX1utS_6-Wf4RCY6OfeFdWzAHG16LA39kLVAgA9GdWPoMSZQ1I28XcRqHxKg4ZcPhH_FMya6K2N5y8W
1J5Qcz7-f0OfeL4oDECBdzI3L0Yzs9lH7W0dAJFlsL14Bmsu2udsybgGGGuwIVaRHJG1oiKmACfRKIHZCnQ_PG0_dvCYcPinn9gp_sczKsT5CZSZqFoMIYxu
sVFM95r4RJevrP9ZcFvyrFi5oLH4g2bx5tDkc1kH8Xb0UfEcx5nCUMf4LoHxCmBmYL0o9aQaI6QGVb8Dtsx8haY_SQAXJhmYHT9513IGrOI94IcIQaOGTMuB
GjoVGeeK6quxTykKfhwP9XLregsQ4YbHfmpYZgYAIAR4YqSa8H28kAd_lAuWKPTe4X7tgej8I6j6f4dSUzKdcf2MZKYJg0b8aPQFg7Dd28cLo502C-MeHRr0
I2q35wHr8-e8sqboKaYAj18aehnj3vBtFZMi8D7LYFmsI3vuxtE38YtxPjnPzjeWIQGi5Md5BryCco8TaIUbI2j6b8IZIUD9NP3qAMKVKNMR8es4t711qaU2
_PTFSO2UdlT05G0WPZfDzih2DqUafpIU596Wvadp8me2KQJOoZEg4L7lywJv_I4CJI9YIZx6GQf4_28INU-Flv2OYAlBb2T8zlqXvNX1Qj7bVKTy9i5A8hui
nmiIZldaFtqlyjiBlf5yqDnmIRANemuHoISz67ddFmV9ROyfqTWnYcJT7sxxIo9auRbZE9dtFza77tAivvJ2s36AP1fHt2wI4Nqfn-TA83v8hb5d8M7i64Mo
xu_hf9gajba-70xH8FcG0Ksoxu_hk5pZCP13faZZR1aaGpcwxPlnsOVWZspO-o2Di-M9P3YkP-Ayc9ohuosDv0PDcZ-kP-DaK6uBKAJnzOHaEAvduwMYjif2
6djl79sAD7TS_nXrzb8X3DDP210IhFjZ-acriOxzKq86WOZPjZ_cKSyaVKfnv-bojAO-I2NuC-VlyQ4rbAE1n2pzUURuFIhIn75j9Z5Htp50mOLyFFr1mjnn
RK-cpkEZbUXTt8_cVP0WXJ1pNDlZYvUfI6hnFdRv8Jz8KWZpnxKzxaI5uEBEl9CR9DanqyUrFR9Z9Avrxiya7ufXVnXo3chpYXHyP4Cvsb6kxHs394aySro_
_ac5MhV_a28l7f5-KjkcfcGjH_kJKYJZ_h1_lK6AmGT5KiVr4jH9abDAICRzOVzwuUbkIMpV7tQK8gboN9usJgb1KljZDMcSKedrSRq-ZOdxFaf0bUFw-4hS
Mmo3fFR7-iGMjordBxsqfXmd_h2HUEoF6yIN4k8OqJqII-LUjdibl_wu_WS
}

