sprite $image254 [236x172/16z] {
v5ZfcgqW31kWikhxF-xiYmtSGiytZihDlrcFXAP9V3e1b89z-YzWOtg5VveV9gHFqEn7fVI3w6O-gKiSmKmhr90gB7CArQScQ6QX8gATJAWn0MQLhG6XJZp8
Ing0crceY63dyXaPtipaCnFBbf8MqStcCpFu3_gC7hTiUo3KUMMBGfrOjXQ4EgjiqMSUnpB7-COuWspTu1beJBRsve5mqKowDpVscM2KIPakArHQ55xYqX3S
9Nt66palKSNF3TkU2Rj7id5SUoRSJROBZ1efBiVUm7zGTfnvhn0TNJysuZfTXE4a_ZDaPhbwR0IRNBT2M5_R3ncsL_Y7P7kHG9ZNROD9fLRueTVVAsMhcBcY
RF7v-6bZTUjmfBnjQnQOkL1ibEUkhDlgkPhvdyIta-wOWOLsDTdA-uGD9yA_Kb54Pi85snuE7CYsoJozyP0O7fQjEx7Fu6b3_IVfPto16NlDs2ZKCP0jC1_W
f08p9xSzBV4vEwvjBjIQ6QR0SziU2igBvstx39_0_HBFRxBbvBZJOYFs6RcvOLYiXKgmXLeBRJbRjdv7fer3zkVPIHaL1BBr5sfx1ED9lR52dq4gZEV-izAf
RGy_sSg3HXsVGONPmAyskmkqFJFGt72UOake28TkUtfif97cPeL0oAcWidCP0lyvj-svWUO6ttIrKEr-j7Sk0x8zjUtPq6zkVPznVBJPkB8jT6BRCtwakVLy
XZ12eSjGbytZPKlwvaPhxJDij7FJPHPay_ZOs9CAzXE4gtt6ucYtNSQ44zkUqJSt8_WCZ3QuZ1GRZszxos1patq6HriMFvtIzbpg8XVg1K8BezqNl__pjcU3
-ZyQAH2oqGQ0onY8ZUNOs6YyVb82EqtWSN8HgZgup1-tFT8QDuhHcy_d9O4zZMmFY8t0glB50p1ARq9CHb85oZRl175CszDpvYMXxc8ktwGkoSWHpEVWjkUr
IGnzXlY6OvjKK1fsWxKbw5zjUwIa2dsc_iykiKqgJ4rlP-lR7XHkXGZa5myO1kc7Z7yt6haRfEH2IWUqFRNFu0rW62mWMzon_Mv0m0o6yCVR7cai2s-W3eDm
btoJ0glO3TZnIV1XTMpK-mpU019XqfghTehHIEu6qS8E-eMsf_djWFExPauvY1BQwUScHN9zQykHC7AvZCunmW5n4hB8PorARAUDQ1HCenjusHsGYPn64MmQ
HEwjGHHbtKxP9ZM-tGqgGmozmf66KMHYv9TUlRw2TmcR5E98E-j4ePecK58dSvSYdLQt1b6KTJl5Vr6_NYtGQnRSs2gBXNvOvDEEh47y1PHjGjbYcePdSdiY
NfWt4_MwTH08Hvij8_Vz7_Sk1uNFLSV4z4mNkcLt_aWm35B5R-NBOzB9EZnx6UjUbgG4xbIFMu7jTGJNisZrqHePQsmZuw4NRc_oNTgccnbKBulW8iMhaSvO
5rLPuxJ-q6jTI5ljnUrL0OjQWU02mu4DhKzghE6qRU6qNTj6GBebO2k0uG26raawm1fSsb7yzcOzdLgT-taEdAWck51dyldj53o7mgi2MDzFs-PyWALjGJs2
HWM2YsPaksDemVR5h75Qz32SrxgHvTwsDoYu5G-Ai2Ia3aW1QvmM3xsS3sZNbLjl0IMaC-r-00WwkGqbAcQDm-AX5_u0C68DwWpGkMl5hsCz5qEi8Th0q0ld
jNcQ7UdCwUWCQ4yjRQriOr9Z3T76XrvZoUkkf3elrpeBviprXn_FDzYUQjhgrmJR5x9YMdxRg2LsgalzRfw1TSOsDhxAfukutaiEiSRr9t_jzgmNgiPNdkbC
4xSzbG6sRuYLxlPceZR_8ZK-6cytxMb6YXfdfRkzpqIrS1f2HrIlxMc3EXDdZRazb4xhDpBmekr0PrnHbM9bUw15ZRFItHvUDvqpuvDE9DxsdEBeJ9ILx_Pq
w5FHUIO-wSJt4xKzxO0qm4hHdzNjTLIp_S63AH0KRtqEq1a2AxTjr99SIqccCtSddPvuopb0eX9OAMuFBi9mJpfxgwKTFuZt1dI6nSftUqhh3Hxai5sTLRmT
dI6mqjmU7kIAV76Znk2kQLlFKy0UuRFo3Wai-lr9Px8zQsbR15HV7glmtDxp6pLztuzZrhXDx8S7T8RAsjBETtl-V-LfwT8LwT-Jx1mWKOci7n_PrfPqIE3h
ZANch63svO3Ea5dLL57Tdd-Zfbf15lmi8-Mplc9ZkZt_Hat7-OrrXi-gi_h1EYIukr6pbPpBDiwzbDB6UVyLVo6h1gXHKRU7PuAQg6RugZLLjEshqP-mDbN1
HcWRKLJzIhiji_fw7gd6-AZoW7MCJLUMvFRm6QfT3U0cgeOcKdl2EbxVYH3RngLYsH58qUQHlAZTDFu1wpZqXLw5vVOMeoilBVt_m-YaL-7BnzUihxPWZ8xL
DfwsvLYFDPNc9b776ubQrn6imvgFpvVwwBeH0hJu3A234KkJCOIeCneRk2ZjQKwLpnNkO2E43mcq8KH6bv-eK01IlsTLtL5MZJVIzcZQ46AZIoJrAaGMn6gX
h6_t5gQUk68rgiuuqGInrlezQvuR-wSF2UJUw1PMeZgAZbVBidGMxQwiGog27G0iPdJBSGfTPpoXWvgp9uLJLlqttaZv5Ik1mGD1Pxoe0lNrwCSmLckakfks
8QEhRfsmVNMVF8mcW5MZMyLkkh1Xj-V8oc3hZ1zhsoXjPTMcLLzgB-GYZ8rydaBM6JzGsoXbPTMbttGtonjkZ-vdWCC8fgq0Leqy-sGP15gMpiG3kpsjJLhF
pUs1WXoaPUaCIDH0sa9MbQ3FHYlFoZn2QSidNNnJEB9WLYt3cjFxVAck6q48YKhN6Lz_4Al29drVUdKPMyZjyGSFbDWmwqYQhqefys4zaBR4H2qCqBLjx5EG
R50nfkpSbJFvMtK6nxLRaAnCOetJf3Rh4wFb3nwOQRkdQTwJhQFOFMSSc9RM4FBZqZQk4hnRqRwBlqLducahnLZDybXLnY6_QC3D3DmscddV3LKrDa1BrvbV
dBPPgnMG6nJ27t3p0xUDH--6YeemXkKFkFc13mbCRugwdG0jT_3mwzFMK3kmiJZaRz6PkDlRFajKqIxgGGXryF3h8_MhsjQfiVzMQnue30LH24nlw_slcvvG
5mOGNES4QGzryi_mpTuMonc-zgx7tnJO3aX0F5ZNtkaTEuo0U73LndyftW_6YZd3Q-DViY5Mp1c-zlvF6I3MpHbU6-aN6n0F5Fud0OoTX7ZmhxtJ80J4Wxas
SWfo1jH6Xa4yfCyMKv0pOEqnBE8Xdpy8AXxMvZG02XT2_zgRevASuMjlZWo5iELiLP8pVEtDaLayv6lZ7Dd5GtxjpH3EcVwpbI5dMcgZS27iFriLv8nhxSab
k0lMdh1uw3zRrUSChut2ug4_VrIVCtpjgJvd-DgJGJoqr4PXmTr_jghF6RxsnCL3VMqKBOJz73A7-W
}

sprite $image254 [118x86/16z] {
lPW7aYCx34DRMGnz_-l-abieMYwPtpiEtEo44Hv1QlRuQwNUml7Z2fM8gFnMj10FLQRyEytKcMPnYx_HZ8t9Yhc6dm1bMeg_ZpURfXNtz1kWgE_Z3PMPdXHJ
3TzCotFT_7rpcVhNyKRJD8NK-KjuaPP6lBe9qx-6DrEBc0tsqTPW7yOBeDd8ceqsgJwD5n-QhOkvunzIfXN0-w4X2N2Y505uIYLMKKvurIU7f9r2TAxmC5jQ
vVPedr_DnkRyYTsYKWAUgIhuQhI2_aTI5Df3TuhcwO3eU8Qldofu-0CfAjJYVIgOvb4JAS-ZN6OmyBwz0rFl2HulTeMk0cpmTU0DRwJ8W7AsVhfxRrN5mPSc
rpVnmgWb5SM0sWSbbeJf1Bn_7f9e2hEjp3y9vgPfDLyn1bxBj3ia_Ns6LA2bfoPbM8qOWuDe-nFUK7bvhMe2Fb7CkccrnNYy4NYBW_VboqAB67yy96a2XIOX
E8RN6vB1DNUR5kwvyStoieuFpCNKQ1tPJ1xU7OirBSXxOYsRWx2sgm_NaHsxWtVRTsjQR7KLjRYidaGIOhww-RKTc8dtJyPh_BMX57k-sNrQN6nAZHPdAlDH
5-_JXdiOVxVW1ZbdFFbiE0W-f8YYrJezuANT3ZJgLW0plr16EdJ6KnHngG5DtURf8kn2Mso_KU15TDiGbWuWgzS3CTc6pw2r3EweIXjP4Td8ujE17Ec8JPJJ
n1lk5m8fpTUl2ourtdpwEMItkjYQ1RhreebuijQxASKjeVlGYc7Vo2pdELGtnzriJLR3MsUAXiZTkcqg17D3spUow0dLlQvjpGLl77ZJJKMG1inguvk4DutC
GzDKjxhhfSZEdreDGsQ-oXePgnJlGLjcquIg8_kuDUtyG-OSnxHrQpd7d_N2abWlSw5fgl-0TyuepcCcsBhjmAXgctQyNWK7tQY-ZfTInOEsReijaYLvnD3S
gBw45obI682q02XqqNdPqh9HTMNNhScOcdStcmwWOhQ8zamgI8kZwkcs1xnQOxZIOj_bgPWjdHQWZggdQwY0TzG06d3DuPv2PeeO-ukchwhY3SbrsF2w5RaC
zPijYMLDYwzApKqHyFBZDKUevjnR7i-eR81wgjgFHEheMhkirnnk0_hbEV46gAyw76GlHP12MXAfz59xYR6jk-LPwSdwg1hJ4KtMmJkBbFfmNLJbtfNdcgU6
9lhWiDGZlZ8ar_-bIOHopLKzp_7ss7LL7TEkCV1wGp8Zd2gYlgOT55PbrdkkLUZ8FF2gEoHZLoK4vzvSJtEs1SQAgGwoYQu9v-4LNIvsqFJCdQz6XMRTL6_7
Fq8DH_7mBXUR-egvmvcr8YcuSid4Hr29HnC7hpKrljCK5sW-rZAy5AA8gjAmdOyaqJilJ5N-_xJKuqbLKU4kesvSyn56Fwid-tfQdfQbbuxGutNUACAExejf
SGinfIEEFkcYvI0EsTVrWMBdUbLOBuUxQWWomfkEeyBcdQwV5jnk_0e3xyX3fdYGIBu5Mb3yZq3ZyMB5FavxtU-LurZLzyLl0VNnglHu19RnFdvwnN61Qd55
zdXLY8U_0LIj-1LpcmFKJP7sCRL2sDpe_dNy_IDUqdBODhHw8or-PTOhHcaZgkxuUwEGtdIGh-gFlp_X5U6K7TLtqkAdo3chdvQty3fSdRIyMLNKKNqhBNwA
75KlBU_ZtQX-B2r-YgpqmsdnTo1AdRHy3wykL-llbk7LvMhzxIgYKDKlfCKTaYAwkrf_5w-A82q_hCo2yVVJglJtjFm7
}

