sprite $image119 [317x219/16z] {
xPoBahky3KTbovOjItd_r-qcSPPi-2D0i5rAEUrttylC6V-m99l0IRc8t5hpwBi8fJrXX7LSv3PG8opd0hdze0HOp9NO4GHhkH8xm1dck4ZS9c04YujOcu6n
Srm4QWRMpd6HkSr3O7EL9nt_pd6L9ywTuofFR3Y0mPLO0r6EO70brb1tqmmFBgYjGc-t6uF1rL0OowxBkuYyUjcvv5qFkoQtpYKFiYEn3ovvw4YiLzwLs4bv
WV1gACnbDoala3MhkX8hjm_uJTt_rwmgbkRRA0PuK3UGhuR2Jco71tLlC5xbYPtOGHuPO_gheRYZK_8o6sFwgpmnv3LZ0UUhFB7bgJrdFdzvufUdqcnAF5jY
VQYXpe32cHBhHMrrvpzYIzpSgAdkz8--MDi6r5HdK-B9Bb3uvMbR3uKJDHH-UTfSS3vBG-6NfyqDusdB4qvvNfwqJPHuplA4PXtheCuFXVCr52NEVwsqFU1y
jiIYeuXsmtYcUMUsRUzF2QTfABAHyr8AvIymHcgxeUqy3KMDapiC_4QUzTRmDDCJ4HfvBnlbsTFySAQ6GbeQPzUGjxNKFjcyKseOwJVaRMnJpZRl5CdZPwPV
ddq0TxvvfumBiBIlFBrrpf9OExksFFTrWnDSeB2pQylpHtOiBnoveV1drvRd7-9_p6WPZzLG-94IJ7d-o0wCnjib76hUwKTQjkJv8plmhgwJZr-UL4j10Oky
ER83Wxe1ncEN9vnCoNb7T_Qblf6wdjq3boSbs5-Sblu2aRQ2svYkRaG-Qc8PvrPHNFOBPD3dbHVeBmQb_a3b-MfmsI_escIBF3CUnsieqFgsyaNEQUKl4BSy
RHRvU1SeykHwYZ0GHvHfOI8-UT9i68zsWK8uZiIFv4Nvm5XhY_KPoyx8xj5U62lZZkHJNZCGPtOdbfrDFaH3OS-BoP1dQE8S8yIOofB5vxkOndYCUQUTNKEU
-PaCc290hFFwhCZQsJt4lDFEhY7Fo1Jnes41disk5LcRV8XvfvrTZxpmgdzeTkCm8sl3U8J4sjcrvOtDr8IvjSRmHPdTE4QH_SFivhOPeONokXKnfZ3p--uG
MHVvEFDEExjnQe-LINayM_Hvbfq_ku6IqL3iWzIuG9uq2uOxc8lzvOvbvyykbbfBsl2mOsxJ13188tMco8mnX8YbjMBeS-mKtkm6gWyAUXkAR7wfkHDPjaeU
Es2kjN8Z0CYJsTMTB_NPowv3qLEUbDWzh9QNBNN47APoIJ--NVxgKb-W-auEgnERPhgtufaLSsifb5mQvkcVcKVUFVYpcqhz8AqhJyY8kIal5Akoom6fO27A
t2gt4Jc6cDTD5FRFBWlN3mgkQ2YYOQGFFREHMACghZaJbr8J8jOsWcjrgDitkwpQwYUbjANKC9d5kBpRawbJIy2QCFCg7V9Vowv-8MDzt9OYa_DY6CZoasQJ
0uG7CTNMIYmJIantt7Q3mxGyrN5swuQh9g5il1yRO-KxhaQcGxlTiHUziILFLROildzdroylXHpHaqVvUM4SUQUBfMZBKzqvkulaYSviGp7p2dqogfxo3kec
vGKT43RqhPyNbtbvCjNQb-bgS55Y1qBPgCwGXwfxwRFAyMmCxKHcAg1esPj_nQDiLcVBix9R_LkwBK-ikL8m1Y-o8B5ZytvrWpna2eQy7RDhonExHFwfW5Vi
iJyf8dvr0pXS6A4malVBsStZnDh_WgEHlCM9JMshka5UeD7xkwG3LdPvMtRpFnTAoJ56f7_Req54u3Q1dTZgLpUIbziR5ARbgQpNn_55cBjd81y9Y_MV-cgE
JtMnk19B8jlLTOZRJoYCv9dPhSsYhBrdG310WuTtk9OlQbrU5GyWRrTddlxcGTuOMRVuQEMicE459e0wjN7Oo5HYWpUnxRPCdjm4eEWqgxAROS1AxFZhIyiG
sIXRrYSsEn9honjVUMu0h0R2o_L5Cx5ZQd-UFVxyAaOIre_iUX8RhSHkbzUZpIDvVdrXCh6MRUO2W029oZFA8Iwjp2OJMnQgyygJsysGvyhkwhjyd0C0bWWG
0LA2yjnqOZQpQoVMBksso-k9VPSd24axthB5KnfoIG40GWZqt3Co1EB1ZJUn-ylJzyGEyaHL4G3IrkpQo9IFGfLUJyVoR2KAGcHRtqHYeKZRYg6k9tQGfr_0
dMHdTvC-iUSXbMeft5g4YE6xfH1NOZTZgTFRX3n8kbRVAdTs66l661_Q0iPNDoVh4bkbxO2fRbAURS-VNPcxVD8xkW10bVdXXGtR4uabGvrRdXgTno0FCG1a
DH5tTWrzFNmnbGfWVBMLMBiPyyjJysFM6R3BgqfzFBNleqyM_Ai2aFdXmr4L6ysOZt-gqvibBueXpyvkvINgECTO9_GHzG4Uc-ec4viDTLvvQiyA1da9la2Y
ekhJj_JKc6Sk7cH7LMoKTYu6TKDYBNagqLvssyiMWWTbChiP8AKohwv4indRJbTd9hRBo_gWslBcMuxP_R7Wp9smofx4fhOtNPsPs2wF-ZEFEK6eTubGNDcT
rrVHFCFt91QgjBsnrGqq_9QdIW3O01OkGQaEVPn-tWyNn-J9yGgc5p7KQGRua8Tm1wleYyPh7dtLjjBraUlo2UF2JnCgfUoYJWrt1U1JNW2WPuZr1GFlcjt6
6I0v4fjdR_hLuUZfbnFBZmXqJTZbmR_a0VkosmnzSQHdVeyro9ydKB-QM4dGuLwf4FN84dtA0rbNjbIUiyALKunO37rsOcC97_MAGvupiGITboQ15rG20333
5zpbHSEUi4iVWlqAcPrOaYRqePCTyZo93V0fJmlSuKTiIm221-qXpx3dwDZUV0GZkqPYqxy_pYOPydPBBC8xNGiZ8ZKLoghveH8H83xafKSHexjcbrC8M3rx
RAmo_nRgBvOdx-W7c1II0c3VHXZImo2gWJZqEVVO8ajk1FxAmwu2pCXBa01I7EH5vbxBM0ZxzQrFx81aZpn_UMBB4sQ0I7TvXKYLOV2ulkLmNQAOJYoBEL4U
s3-n2S2Mru4e6djCt-MHsZYowqjiXykTMhD3dgCy6OCw9eeglyc3J062Aghkdrr_Obk6INOlJonvOt9VbpqLHLN1EIwel7zY_VByvSboUVIIfwcVgpNG1JH3
d-oKs0x29FibjejO9u-_vMb6H2AjjZmxkzNHnte-jh2pNtaIO9gaCx2-9WUvotFgu-s9zSlpppijQBaylCjhgUwQNJknzX45JBDNUMAJPptW7G1G0DK648XO
drInMmvRdp-n7PbcjtcdJMfgm_24x_8qlIzNYc9arzBdJAmVVtbYGxB87ZtaQNgNPm-hB7kEnFhnppld2LLDc9cOdnqQOY0ggWZGb038_UXp9jQFlponGPxV
DWB0QwxC3taqoFDbrqmi7YgnDabi2ohmaeVjAGyeTNbEVIBJYQr_eiukJ_n5YyGkBpBNXxneVvUTtTeUJ2LMsjyTnxe8F6UlprXwR2LsUSx5PoIsUTbUdhZ1
PjlxkV9KuaCUCs_IHuT9B4VOGbvKjj1mqakFsiMRNHw_MPkFNPxO53M9d_8IT7asOkWJeGCabc078fiI4YA-oGi04QDs495NPhU-dOF5UlponF_ew_0WxmjM
rWu0i27UoAuK0Fgxn2Bi1ubVdllHr_vAdHBiIYYc0zKCW1Zwzi69t-GnOZQokrdV_iUnkuEpLTytXG5ua4S0GVL8-YnrZF0RfBRKNW98Wpmq7fj6TkkV93R1
Rq6cFUOAT_3nfq5UO4u0x2XR_YVB4_-m2YW1j_GkJq2L37cEx1wwFF4_-WffPDMM1dayo1DUdLq-OaFX9otgsCAtF89NESC0gWvz1vftReVK1ExaRtduBIy2
_55s_SUn-nDuJbwMRtaHw0u__ec8BNt6uZl4l7F_ZitsoF3aAIy15FLazqZppkraMIQFViZJD5lm6FeEC-_SJbaa3m7eJdlAq_ZmwD5tn7cddyWBv0M0zn0h
6l8SsJryUU9_zC6TTtcnTNacuj1trFB4FwmY8XpaLGI0n2ngOMUNZzbG-8TLDWcqqu_6bo5rkpwrvvr707d6ddQO2I3rXTSSXqITGvSd_exD1W3wfPOlAEsG
NV-yyqZG6ddya0TfUtQFNvxuXrMsF40YTcUN3rYU-45UAUyExPFT_UUTX-lOo92tNj--vSdn7tqr8yAFsE8TScINnNSSUsG2gqa1UEss_PR6dRQwvVXITFY6
Ol-EZG2IVihZbTbz9FFuvSd-7LjXDUGPo9kwEtymxpp8i6gGn-_oR5fNzyHv77jy8Y-Ln_gKroVrDi9lgyizxpm-s1R9O-to5gxOsy09ofDfI5RB8uSyLqDn
V49P9sye-9Y8P-MTe3nnTsoDkVsGnwfOL3briGlboGaIwnnM3VBkdX6O0HRAEqTvOaFBvE5JNW008bmYxm_cdSSRLfKUstgNrraYxrJbYVzcrLCUhfHtW7dd
4OPLvRNR0i1RR7c8zaYUZIGu5QHBtu1-RHXC-WJpIda4PoFm0dlCWxpyBG-I8UzavOdTiTc5tvkyGAg8s0zxbyeJX9D2eZPlyXZexTHZeJpDS6BAOddvNLvR
9g_2kOci5i897b1ubwTBv372wS6c9ay526_oK5ySODvvx3azT0PvMLMgBO_WNFXlLadykVAAIeHYo3jbUU9_3V37RiiI-qd7ZWt5UOTLKfMHgCjJ0aY4ghhJ
lFFy7Hi2FEL5nTShq8xNJqvAgClafGbv_ddd-SkMyeejtUKbPSYwNtbo_c5LYtTvV9S7YG7AYdddzUYJg8hoJ704m8zvvqLWovugFWhd7E2Bsm1SBEZOg8_g
IrWjx-hOMB_8nCpfakSQLWd05Llti0hkq2NFzS4j-4NHIvv_Jc_9kmXbWxmBv0toBf9ia7T16-HTXBf1tWMs3V8kicoGTq4Rv5q4tY3l0ji6UHSa6-HTb0to
BYB_Gvx0IgvXrOOR5jUZRuEwgsFReEuQLhdLNIGvjhh_
}

sprite $image119 [159x110/16z] {
pPZxUkE-2aK1NH1iDE__kEVdTEegQQZTC_xoPVqrzrdMHe1DrrAjqTiYmzsjqbl2tMzW57e_ciC_KQ7teWpuIcTw7rZz0NXxeroVW3Uv8yNWpuZn5itakHpc
bBTf9eyWvXleLSkERaFUDDUOYvveVQTSVPFRzKGTFeHUJVCirntvaDjGVeDciZ6_gDsHTEcN3ObSBnntNRgyFjTSB-0FOCYhcabE9dUZyskQIKuYjvJW2vi9
x54taLjAy6MvmfKVAp7yY24lobLblSVmitH-IJCfQnUqMakHxYS8UqapWVBNRojjDFWX-DFfKaes_BtI1pp6MRsOVofTY2ovvhrMpkaXPYnw5-MQWwNGZ_Km
vvTU4Rf-I21D-5WlvfTU6V1sTJE1jZlXpin2E_qWs5sl32nT-gAD4rRlVndr_caE1zvDhosFhNpTyDVxGpKRd3zDlcnTC8VBm0y3gMu_OTvKsoVcNm38zP3C
uN_UEB7VKrQC3z701xumkXeIlV3lA5_IJDPxMlf-ZeyKgfKxdkh5-Kth_9j4llLM-2F61KPiJ_G2_xffYVhF0Ce_whaPEWc-wuMdv0dNUfJhYdNLpedUpY0g
ur4Fdf4dp7qCBNapySvrKKP_w3w-eljFRQWAgo_0KzBlldNSw9AyIOooNcGuUjg7JLlJBq5eDkJE9rmnTDneqf-6jBR1eRsNRtruLr3jhTVkduoHpElJ2RS9
6t_v-TMWkJlVhCRjRzWmlwFL_X-cmnDWwiV0v4ullWJjsUCidVX3x_aXe4bL7GxFw4nbd5W82-tqYOZmyScFNudBXvubUV4oRz9sMO_aPZ3jQ6nwWLtG3Zln
ghVweT2D7n-H--765K9KL5QzE4WOdP_gsNhUWscZ8tzth8uVvJQ2PJZy9ZXYnuScWhMKAklAkLwRObyds4IaMdhuCexaDa8TxX-28u15yEa9MjQ7XOYuYBi3
lf3bYkDFM-l25K4MErd2q6mWCt7bGkhUkcTqJWPIglTfDq4MRWU2K9Q_jCU98er8H9rvB4UJvtfURyiQv26aiP2KOBuVr2BMMRLKv2sfE_oaNc2lH110H9ea
V48GDhGMbbAu9Rak2-InNgpN10oGL1g1HF2f4bO5ubO53cJh1siYbwtI-ns6R7gwTx_y3gzeKIn-viAUvzeSVe9T3dCkUk7CY9WFWiW5JOXMFtHfbkOwuAVu
b8jTBcQKG6czU6ERYBCbs8Mgho39bIfmzsAPWpNN6t-Ybm1rfy8Y5a30O-tIYI1SMSP17rvERtlGhdx4cclCEOHg13SZAavrRaPiWHCb2E_LpCvycstsqTVv
KExkwBmGRNhEjsb0LRc54_iybJ1GYKRUXwbzUh9cUhbSDDfeWT2Ytbmh5L9matwo1BLKorT3mp9jZ_LYhWoc6_qZocbL2eSqb53wrcGqAK5akRBYsyir7nRT
ckkY1o1Sh2B2gGzoI-_mlM2UApu_jMX9zD9SqMX7TmNC8Q8Gee4UvvfCdkiDD5hWSxagBUWQeb07Mb5hiP0qcInNKUp6zOGUvee9hLWWLjoWrDli0u6xtyDF
WXZbsMhIPA6SoBNIFSNZNh0JSQcpK45CwwTA4BxckeAL8xdez9s6Uq5joZMgTBJk3wkCZwU2dGzNplFDv17MpM-56gWuX1ff82t19DU4uo6H8RO80j4Qg3ka
5D8P6yWJhjcthLyFYPnwNu8EeXhSdBInnuzTi5-Ggp8Tq14hAZMuWfXbqsiziXA45U8qrvFDv1WUzoK8I3MY6fiUIpYU7-1mwB_aYahdABOA8fGskbW4tnQk
DE5VaJIJZBp9ZCx4GZs2ocXI8qtu_yrr2Fq6xh4oJRkLjkbrxoLWYpqImTEvJY_qMsGfGI2c4kaMRhNmA2Mzm-FgPhAIppdN4PkU49LWBYDF-88XyViIdB7f
CPVQW-eWItRL8q7CWrpFmnexs4I5o6U4iDA8o1EsqnldUV8vj-DUB10GngwS25um91AoERSRrTgBX-lCTjMD4qFY4lfg5njKGMCwjOE4hnWIlvzpKOlTz8WT
o0HrM9fhTBgIOlU2WyccKnz4DO1d2Qi5pZQJgqjmZevmKYUIU0G-L0rpujoGkB04LvpKL2I6sgEWOVF0HKFYztCk4E6RCKi82IA0LNzkuCfcyljLgncmwNKT
C8W-qRkocVn-rKA8H0jd4VtxdGQBtfNDvFoSmz84HmbkHXlz8-15xsmpkRu4TpmwaP0OTVSvNR_qNfbhFkT2ctC9wjrrE8qdUdzGAE459JY3YrChaBBfuL4l
QIQlAS40meM8-QPdC-A28N7jgcLTY4EACxf670o9LvSWOlheoiMAKaKa6-ThwLW5mucgjShmk618NBvgmLirhTHblBIPd5-rtBoJK9qRdGvuVPDnHBDQRdLN
w1tW7dSOKPiRxw7tEEUW8zxXzF9Fv--cHzIMuyDRwELpxhtqrZdtjdhhd5jkxblHyQwdjywv_-IcCRqZnIAMpyNlHuDTA_S_
}

