sprite $image423 [90x130/16z] {
jDO9ZYiX38HXTcoNkVzntpBEJYErqyn_W4_1gYW9-oezXzyeTI9gQJTRQoMhnfrk8QPdPUCPcDxQTExOcEcp5Y-0kRIUK-tylzckNw6fD69B-1PD9UTDI-t4
KxFDMXsVTKANDaFLCP4CuQb3MrJXb4_H0eMuvD3aXCrGW9ab-xuJMDaYp2m2gDwE9i5L9e7CAYnLuEwg1b-91IBlgFuFU7cFG1LEs3GHGv_gsv6WwfPjUM87
FKBj4D_98lPSFD79_LQsMwmsTqc6yDAz8biy9weRP4osG3V8PgyESMKR0jEdGroIJNhQvbwNXM-zd1jwqF39iVCpiQ27-Nu7C_5RItb83fugVtOi3rJl9Kx9
GtjqmOdub3muEKV1V4OUAC5NNRZlyj0MdBKrB9YMvgZFQc_0KtOlpOh4KoM4H6PZlJG_tEtLXM7oOcd-jTMtVqsmfVdXoQLN9NPWI0axu3ODlOKjyDzspEDA
O1Y4WaX4qt_1UpTNPZC5ZFK-WnLKLkhEra7WsE5EtOm2gonL3jcMAbwzErjWVu5bgvIHGkHGO4aAx1HOAR3Ki8B8eiuU-0umueKkWctytOZsXK1BhaCjMQab
XmWanX5Xvjfbiu9gtw5K5gEMB3bI1lv5bmeZXGh3i30E5KRya31EKM4ePeQFCG7--PToheHp3lerj_t7F6m6OkPirbNmmVwWYZNGc_mtymtyAUS1ie7yIIEe
1ZPmXa7KK4mDR-hS79XqHQbn7kwiJqbdc7G-f4Ekn9GQXQcHW1g4peRfx4tf79ZEzIda2wY1l1rHWs9DaRsf4OnFUVnpIhfsIhesG3fW10qZ-qCDTs33NKyt
Gxvg7bbZk5S_aBl3_G4
}

