sprite $image396 [139x109/16z] {
pPlTTgIy3aHB_bV9zFi_xbb0jFWOfsUS1CAfc-Ogx6Ljos07N12fBUB_8bb9BOB74nkfgjICPnCggLl8HwiaPGTnc1hmK99IJt5b7fBaJvZye2IUXvIHh0F8
CygaDe0CoZnLcn4c_Ue4zZobp2398yhu19uDDSllIVAGCbA6sZoaJ1X09c6kdzYnytiiIxmUnOnV1x7b7fGlmzYot8JoHHZsvLOK8-T1RaFnS5AIEr7cOHpa
RfGHPgpDdIZfZ6Ba7CZokXn5rFu8_o69vtgKIfk0iRwSqokkJZII0mk7sfpowiOUhqSviummOsqwpOgb6sRG6vXX0diOGil8Tw2G_JqC1qcMWZLw1qeBrJw5
8GUGnOm1QrAy0mM8-dcLHX3LW6mz0RW71MXz69W1fPChGtqjYybzADMyIczHZBOqeBpMwm2vRLGCeMr-l46nJPm6sVGnn7H7NyaRYc1KvbIRzLTHNljlkrwN
QjOrecxLp_rSfGFaux90LvIUaAula2cjMrLYGqd5OGuKSv2kWkso0IdWskIFadIZR2ZXfCmXoPOUi8sA2gIdoz-LpHi_yuu2P7DbN197YPjS5L1xnQlVbJUK
Jd9J9lUupQh6lKekYQDe0I3xqCIhtvLflKNjNYKB6qeIxp87HRAboNx_kAeRBzuHtL20H2z9bHKbOrVcg4q3OfIjg5bqSPJhDbGS1QBTIv8GDYM5_srn5LjA
xI-prsKeeJY8em3LcYlJoeYYWYsXs_1iUzMEgACqmw5CpsSKeo0KrR0olnpbwXrHcZ5vuy-k3Cj_KIY2gBQy50VAArszsRMvsiAvyTkgZ3XAJq3Okei90dsa
vEeTKUubAUgDltgLr1i_0N2_4jZBQnQltX7btkIFndyeyu7IUqRP0HJXM9MioBKxeZHVSJG2UxSjH-FVxXh07QMiflXYG6h-eIGZYg-8BUmeeUl7nDxkIWJN
0zb1bXTze_AI7L57SHYgD_xGkd5DNtf6t0Sb0z6V63hjMtlRQG0PKFoveE2ZyIUr_Qu92DvmeQjMILzBGLJwSSZF91bH3cNEZJzYMubx1LAslZH1oaaGXXEq
kIu_W-BAr7pgjYK1Kae4yhOy-eqhnxtj-Gdy7gLeTvYXyVU0BRblxlfj8pbz7E9TVWP5aDcFAZ71KOvni9UJf0G09K-UeFa4daC9W5JRuazquYW4SitRe909
wyMB0a3cZaEyoy-Z0F6aJ3CVbHAvsDhbx5YQomd5bPcGP0u5FFlhhco_h_t-nne09CwSeCL1aWaKuNfvA6FcNNuF0SHbSPJ2gHEqD8T2_ed2M7UOZyPlx8l7
4dmrMYgWd3X1comGEQAO8BPZOCxxS1dnk0oSE46REecZPq01qWVW0UBBONlvfTTd35d2boOppLb658HFjthqg4yv7_MDoapQwxxICw08HvHD5VEdtTDK7iCs
fuoZE8oIycyK2t0KYm0g9ux6fpgTwx2dXd-ZoDxVUbz99F8RXwwXpi0K0VwD8kpM0b1K_u5YDYWpT9a1vgD6ckIlA5qL0880o7jX_vAk0VdJYVr66PvWsj-r
VIskOgBdNMsCaX2fPC7tbA5nG1csrBUMJnTUnrYl9KeAXTGiyy-LNYLFUEkA4GYv9eH69-as_ZtJY8HGfHwpQ58Pdc0qVOhIgQjDrQoM0sHPR9IaPYI5I1v5
cLTcJui3IkU-KhJrrq5iMSueMu4DAQCnX9n_ycRc_fPuHZ5tmmNXAiG7euUzrQKc8cTKwh0EVLCPHnj1ZjeuY8U6e8Y6bA2JRsffPc8VZqu3YDVc3sMjGLHY
Gwmb_UYrTPpOjBvqeuuWFbX7QBI8t0KIwp21VwACiqpMHgsNa1iI1MMepK-LsH0cGPGzGge2fPM8hsTcOh-hZNesEEq5rBfQal6DJAm58qXtIOxvsosljdP9
h6MGv69btjUcDv0Yg291XWbyhJ8ZY9qxYMX80JKWra6IwvLvFu6x0Yt7WC91aZkK6Rgynwmbv2ufXZP8Sfiodu6mHsd85L8kgCta4wTFu3D9eWYHMYe95sJo
yM6KH7k41L5a3bt-LcN6BeyMGQ2L8hWZyPqorFEG9A0aY9GMV-UxXZ5KDQD1wegIMdhi7_bDjJD58X7f-jhCRoMobzYR08hKfDRmt4SVFIDHig0XigP7FeNn
5JWWCaL1ILTq-Uy-SVQ2I20HEOnT_ZULeGca034X39ByhZAq04YKK59DJtrYvoWY0LaIippyJHbDGa9j9Jp-fHrDf0uluqyeewHapNWshenFuASZjVr4aly1
}

