sprite $image204 [258x188/16z] {
vDQ5WGG020D17D9_mUzoxfxfWGroNu5M8UQ33ocijF73XLBXNvlG2Imh5IesM1EC0LWsJde0T3bmBA7BWJMMiEL02_kDCmPWMUlBli07Iu85fCj1ubXZ106W
oO4rJXG42xYFCnx0iZQ21ToZz7KMa2u7XKiPVu40qEN01XTM10kuJp0UmB9nWWLyWKVP6bUL10kuJp06ODaOmGBkKVe4Bp3VAIHkpEMXE6wlZM01zoXzYHTu
UjNCS-NWdNaptL8iXs4mkR6lNS3xl-viDEceog4rw711lsPoUlDNaUJKeZPWxAL84Da_R0NM2Q0YXKNvm0RK2KWKzazimCp_Io0Yuca8zca1aFk-1n-5t-4b
mA0WvFOX3OWVLN7x_u4XFYaEsixuElL7KF0C_6CCmFktsWSo7qA8ZuY3ddomnrDL495BhF7sHRa5CGtFW2e0_6NvtaLvPmo0IfB0uzyQWXME3m0tnsiWB4HP
_T9tlPitCW3iNrQa5J8oSHbOPqcozsfxRm1Ok_roaa6DPT620KTK71nlWD_yDoVY04Iq88lKZlWaK6s0eSeA0eJyyTST-MxU-0RiCpQg6UTdG0Ii0cK311mS
ioXJAp3QO9Z0_sI5g5U11msGzANQ3mw0Vl-lzZi8Unq7DO4QGlv047oqs74hiCs-jr_pM-M680ZWVB54G6J9TcW3dffFXzwOI8pRqKqB1laT0Ua3FGwSRi2Y
0ZkWN5eX8yjL02TS8SYNVhsvartj0Bd1lO1B03OdMp0B1E03Ilt53UYzRa0RXxTQuBU3Z2M2e2w1lYWteW711z20tGUQwP1UbD5c-Uq0_pV4Bp3fA_3cl-zy
yn40tSUl6BL0BygrzQE-1CBNc_K6x73lpU3gMnqLdNWtr_S-woH8vJknz0R4OJ4Lcu57biquF1zH82WkGLOs4E90R43iEaCl4GHGzQCWIkkp152x4W0WRqYW
G62b2_PIjIyMIq3rVxnC-2GGokgFQiS678lot1NR0n394WYU02gxse0-kWwcQZRk_3Ziq_teeojgCy1yvP0X4015qneGkgxvLFpZ66e1Az30EeylmIuIMCkL
1iIG-xdy5LjnhmDqyvA0aWEyxCa6h9uwNZu0i7VAigXlGT450W7otRm_-7NB9z1Mpjgy-cXRzOOmtWJOXkG-m2_AHdzTo-PHhI9ZrShKCK2tfGLmeBYhteZY
flmIPD20r6EruwYEQFgtpvSPDE30OmqCGB-RyoOuKzLFGLa6gs2K_JPrtJpg6DRxDZTWWm0bbg835ESpz-lcD6WEwm1i2LQbd1Nn_o4CpfVBvKooObP2Qz1r
LO3sdL4U1E1olLve1lddPu6Vobbx7Q3llmRdw_L6u49Q8Hy_3N7OPjMljfrMlDu0rq60PX2hJm_WiEFGHagq4Q2yyjK6c0Wy5GSsDs2RksxKmZIrGGhg37G3
084dhT2X0TjWuE08svzNl73-GK1WWER7hZCY_HG6UW0WWQVY04Ujyr-_1dk-A02GW1W7nSPZ3RlYxGpG03K1fHdnkjCvuEvsbpjl1Tq0I42rWhUv0TkemD45
fTpw3vdJ37G3807T2dsgXJxQmednEGZvWlc1GCs0VpUFrn9SVNP-LCqWv00W28ZDQB0gi_Fpzo2a0E08w74mj2q1z7_Kxkf3stnaGXpK1g08w750N07xRzhx
B-kJsfqT8a2bO02A0Eg9HHbZe0Om26mTrSRf6a481Y09wDj1tvVoVjEO5BLDvqkA8SpF4D3ZmFUr-Y-X0P311fLGASK0g0deSK38nttlIxKx0HCMPGW0WO3G
ZEiKu2M-6T40F07T2eG9EBc40EPd2UXME8f040OG24WC3Y6GX0440c8Sl9v02FCB1DGum2JS-b9jz8GQ03o1uwpWOnzest8VQ8-kGAGG0081uTrSNuBn9a1j
ysD12021mClZm0Q1Wa6RZrqrW4v0ZuCrWl4CnFad0Yuqe43WY3YmYS2fWG76MGL0302T04gnWjSHEDHxDo4010B7nO7rXp8N0a0WS6GSk4dpwmRG2UXnK4Cm
Sy40Ae73cz7T38PtOGMM21nk1PJ_A-4DhCc-902Y5Mhf3SZht4ydFtyU0pu0D5tssmAoQm3aE7YR0QADB-_a--FWY0P4uK-Ysj5MUBy1xFHDVb4bMq5lG5vx
-NE6VpTh7uGL0q4CHFUx5_vy0o3DLU-MWpKZdK4Se01OF_NZTIk80qF0Nmx4WGY0iVwy61aP0UktYvDn8GJiwi3r80v20J3KeGEYx0Zeuo0N0Ckd3fqHvNd9
AV3no_LcGq0V1ySl5G10b0_T7Y0WZGEWmB-S4UN427J_fjTwSsW4kdyVy2ae0bQ1tXmQWTgC0w_0IfJP2FJxUJ9w0ePwSqC4PABCHg3x5tXW4WJqSU09w7gp
9-3n2pmm1KQWNyxrPaz07mTy1FAYJ0dOJc_Uw0ZaUpCF0D-RjG9xKTO4z76W5TYJKHFGzsQjm3uEz0ZaUxCce8y3JK0lok0PfB7Uh0deUxCUWRmeQmBwED04
zAAi2UXxioQW5sKz0dbHrYEGZuCZ_y863ego9g1_OD8Za8y3JK0lode4yd6W0y2BiYQWxyqw0BmeQmNslLcFG3uEz0ZaHLcFG9wCce2-D-iHo8ko9g1_OD84
z76WHo3VcpK1lIXh0lhUR0deh-CA_0K
}

sprite $image204 [129x94/16z] {
nPU9Vl8u3CHjwtASxlk_xa8Cp3hr3wtSalw_iwS6pOoWwKTatJZz8LpRrgoaFwBSnjzeJNFw0xAsxK7R95sEtCQ2LYbT2lNjWskZKAnXCdpGV9NvsFv0kwQI
F1kFA5nk_bLHGFKSsYRvmzNp9V15sxyo2cFrV9hc2whdHE62wda-N62-LyahpAzFdElygUfL1MQr_d8KUDY-9q3ahg8wKLZTVZKrnmipFR3gHY5UFTCRCmaL
2MY7p8FgH25gFXPzpfeD4RXFgpQHmElLmtZ1VcS2f7_q9S4Mem3pnncS4obyW0Fd1DINvDMhaEMx-TA_cY7XJ4C2wlFBwb8bUMe-TMagvoZO903sVF_vEdFK
VEl3CwjfoMnQKXcZK4KGWBxzKK7CXwnJyrFA_5h368LgLk-O3jit_7ioIdEqUbrpUMb9DAzajRC2h62CGgHwnAgIKnQJGcfAYTGuPvbAEDw5oORFE5KoKBt3
SrOfBn_aMCCp2aV_QeK2nGegF9X4mRcxi3oBuhyGe01pR5Z1p0DSPwzwWWqmzqD0gbIETn-MP5O5hoyrNq2_paxr-jMXO_lT1-aX94GpoqI0lm540TKxF_oC
ZQS37lwBopXweBw0CGgetgX0oiDdwJvaLc5LeMv9aKCZVGj1lT6FWrMy-VR7A8mV8oY7ptq8aIht4WXtSII7E832XMZR3W7d62ZMh0KtCECmZTY2XFshxMqc
0JNC_F2aRr-ETwC0fpB6Q5zVN_iDI3ZxK8xgfI9sDzxkCeueA5YNqFQlBk2T15N6yd6Dtb03uo5WdqTX581x3EH1E0gFyH3mDWf5ZFFT1ocaG9Zf0RECFlZc
ZmBUH-5v5qI7yJJ0ulg0xPy5m8Uv1CxVt6UYd5EcWvno9c8l2XWFzf4tFfpC9wBKvtS5YKO5vcr_5E17GVGydp8X0tHe4QUIUFWJ0MuKHW5JnYMfEnu2_2Z4
1LYTLCyHu4JXZG0kPm5rOhulmByAA06bGloAG2hytmoOk_rHG2WAQ44gT93xVoKwVYx0kSwuG_a6tIdvHi4byiq7RGT17yPJo8pn_iC7UujAiCcJ0NDm-w3U
fkmB4e18h7eZM-8D4Y9H0E7gWSRfXhQu3rL1j7f0KoVRlXw5zV6rf1Va--19Y9hVA0rmMuY2QgnwO9Tq9gz78Rvzosb2gKjHY8_VO3vOZa8DLk-VnkaDqdq8
I8YQh-azMOC-h5SFh4SXUdSf_H-Yrndc1whd885AXghd4xtEw-RxKGZui2zLx-TH2DxTEFvr_dNpur7uhUgjNcTl-qlc1vwedGLeYkDVPrz0l7hnw-mBQ9xv
yIXu0jQhjtwTsxvSlVLA-W8st_prAFW25kxk-dLkk_UIvyDHQBjJlSz60G9GlGiWH042FbCz_pgt_NFLyv-e8G3LkupIez1slEIv6jeE2KxrFbx9_KhpfpzH
3ozvhgVKdrRlNm
}

