sprite $image143 [249x182/16z] {
vDQ5jG1124FHXH6I_Wl-xgwpPBWraFCuLdA47_NOv9LnL3Dufn-LDF01_AZ2Wy-4LHdt2pMctlaMj3BZVYcyp9M_D6tVX7sYLxZoAbFtu9U4bndtIsEZgNVm
6z3BZFibj09NlcdQRF27XkqqxY9Jz-2lX1SQj_xKE_W7CBP9sDPfyya_52wQi2fJx-2VGvTBM96fs-I_cPvutE1_6gQHi29Jz-02qMGIjdVQEhWCyaoz1PT2
ovAmvS954wO_zGQU15qjOVffiy6JJK-IiFM6IIHCV-e-cKOqWOHfJxs1oM2OGC8qlrYRJ2fS865gNsmBfePk0WbJIPiDKC7q1EFM_s8zA0GzGSAKfzv1FTCJ
94nnwZufwxAy-zfvN8U10BpTDelU_t4F72Q4Vy_wp1hQGZ2woFq7SJ9Iwlgjm4ii1KwnlSEDfzYs5SPFiGKghF25bKzvwshxIjWjgmqhh4VK2rHOdLCi3tV_
g1DstwYhIaSnZxfoUSzJh6fFEfvY4TwV_lqQtZtgNw_WxnTrLQ1thpQ4zwysXBzPr17Ulze0_cvHHtV_g5_3LQHtjG7yVQ8EyBU9kkfRqiNq7UMYxghlHrTp
XFUdYxa3l2CTsGZlBrTtXFUdgpd0Mz9noc_2fS4fLjJzFbmUz0RXlWyFUeCflmyN4lNQx0ausVJIuPw04thn2fk78xt-bC_3ITHhJpd2xGQSR7hbAKVuSBi1
DoNqibEEyE59vt0VhZ3lHTaKFeQR_J9y37lIHKg7cyE3pjm9t-amx-N3ZN07EOSFXwZNdd9SgwhTWyU2gDTcu_hqRLEr-_3Zl4kbS8URh_stm4NLISW13b4l
7sw4V_gyg9AdTO13rAjFESBZBskKB813r8jFES9ZVHD61tYjUGSsMOTlA5oRRTXBZl3XGAywvGYFUL-kuMvFke4RebwOZV1ONxSBkPiFYtbNlw13jPK9DuVl
rNOnwZOiwB3f4FN2uKOuYVfmSwqpxpZby_2iDXnrS_krULUfEkK8XwZ3avl7W_ib7IwirQOSuJ3lvwYxkwiFUppKY3fE-JmyJh67PJ7gPZ7lhqqdKQ_8HZZE
-ugZhcxkiVt_EEgYasxzt_yfEuswnyx7zYFzBrvOPzbs-eizg3R9KRVnU72ptFxhQdDu6RhKbFlsbN-p-ZZgyN3O_jnqX0Ezq9H_0-Tbr2rxt8PvFjYHZd28
UWMsqQ_MVxomFgtk1gMk8kO01tc9AJVuwr0QzISudzpSdzklM6rsX0UzHhZbA-VYATRSSjuFsu_pZd1LgH1kygtowrFiRlKSzKTV6rnO4HvogLfXkF0KQteO
TL-NPP58Vz3i2XxqVnfkKc4qwZdlRhRiI-Bgbb47ED1hLXYljhon17mLXmihm85UiiBuAJPkBBuyrcOs_97-f2CSebwnmdZKDPxSjjXoZU3dl8iX_4Z_o-nR
5SPFiUxc4bkkUhwm2i21_lSgR1QCfzXXMy3XmWfme1UkC1xrvvwlfdXX9N2LoXN6Bwpkicsl6mjSM05-ZoxgSqj8XSr4FQsMesvvOGNu7VfykESgZ9zY7oD-
lh360HxWG2zSORpQyBKPtRCUCe7FlOEyO8Ln-W8NrkFsg-f7w6vIe1UkC7vXzSiBAyA1NhB2UBN1XNKSjlzdS9XtALnX_CAQrW-lLy3cYkh5l1UjC5vjHx2x
wt1plAB8pmTUAbJO_8KrTXv7VHLDk01TorOOZtg0BUVz35_MXCEsrwumVeezt5XWrDVz-gugM_81NhV2-8Nr-AoEy9qk15wpmlWfDb-Lyv_2ztdFWHUTXzls
ByAD7nxIu-KSuK7FQakwLQYm-QW_RomNy8WwmkjN63_5MlGum7E9Ae4NhJ1URJwku1brW1SudyvVMF78-fGdNLK0Nht2SE67X-1s9cVw1dLMlyBuAHRM3fNb
unA0rwym7lNJYkdUODC1Nht2UBK1V54zpVkAS5vXvQnuYaNuiWQTmCjN63_5vje2le_tXl2A5JP_Yiq-Kttr6C0dAgn-rEK5NqHM0YTlT9TU-17uXEzH1_XS
kEj7VSrg0_XCXTMF-fPmsJYyVhZvAHO7NWJWC-VJ-b6NW9EJ6wsm-Wk_oBdbm1Euyd3NNwTJBC1vXVM8-ahW4nLMlDe4CaxU9UWJTKbuWmhZfrY5PJqgZ5SR
WsyGxZPH1tYl2kEdM8JRZtvQh3Q4hn3kpb4t_esPZjMMS8CAwnlrX9CAQnfr8nNMC-gRgf4AQnlrlrnX_m4
}

sprite $image143 [125x91/16z] {
nTW9Zkim30FGoUP5adF_u_wwBeZ22DBFWKRb1HuYHkhoywji9Iq_tycQfKhPlq4lgKfzHF8QRk-3xdeDdlrMdZJu8x3i9CD6f6n1PHzrekEgtyj4XrIFzPeI
KJtMQqfKzHTb1rMFzK8YgaVPi3_nUy1wHLIFMqheVjLlcQ6nTej7sLWlaY-xuthnVDuSRoa_-xIwtbA-UgTR6bVzxa3ZuZhUKhxwnVEMyjNxtrBwulBh5L4z
VqlvwidrYgkUBvklFc2zY0zRufQwLkzVDlyzIoOwj7hLG1tL0m_byM4BNADdlmFNu8V7zopWuTMd1RX-fthzWexg8SVpOd2ZUT7Me0RpQWrui2wTliAbym7q
DIv_p6jhDpZBysNVuoBG_IUEg5tZ2jvvlTwZvsbNU6juyzmdZjXvdkqAFqzdNa0ZIH_C9Vw8OVQkDFApP9lUEk3zuS4xbetqh-rrRXquPkzRDl2UNTxvPWfy
p1wyryI1zon9JO4tCnM3ZkhzQE0ZQrRWZvYADkYOFH-KVOEFwe7pFF_OpJgE76831p_FNbne091HlJP4vOrlv8idUWktLjUX8cjHipOoprw5uTNkQTs1lbSF
VUAbHpllCF4qkwWUl2cg1mwTfv6oGfkpP7tn9LNhkXfmdNc-RDacyB9wAoaBPWzyujcoZ__u1xRhDQLYxSK3dtYkxBnya56zbLHHFt3evCJRnNhTLg_Me2jm
yDp4PQV-WfxM3hXSyFA1jeF-yttYNwdGvGEDZBAfB6biFNJWuF_lbcuaZ0zRyC3bwODdRobN_U21Iwwz_weZp2tbiylGWQUKAuP_Xzl5BUMh7xF7a-UKYeXq
7pXtI_dgWQV10oTkAHjysE9jBwdpkMBiv2tbSmYUlDRny5c0V_ogub3zUE6ArlBa2t3sbl9PY_QKAgbAIUaIDsAzwEfV3o-buicd5Afildhf3w-b3jpXbX8V
jkEr4xnmDxVKl_enUvd6ZhB_DlkeVXhxkAK1ETHqn8XRwbazSEAM-gwTuPR6PXSRE6vfQ5B7SKkZivRVhjS_
}

