sprite $image22 [154x219/16z] {
tDQ7KG1024JH8uFzzslEYX5lRtmr_5bO_vjaLQMkqx3NdP1r4hAiHyxh69hrN9wI6qUzSaPkvFMUu8L5cjLm0Yz5BvN0WVLIG4jHdmj6BqNF2HrOJ_5BWS_D
whk2qO7rZC1BqKj51zOBsV3h_90pO2c0kR7NX5J0AGBarYq5FZU96cQqOIbmkLdzZMHqO3sdgLCqpqO3m-T6bhL1yCmfmkV6NlkaqT0fcfSoi1J0t2GAmWYy
5BrKT62zb86bs9iRrKKreBbfvXNpzg7bg0w30TXTqY-___FUumZsOeQ5P1QRCBtcEognQ53z0biwIkHtq3WUpHJFs_fnd4npQPjVRhpL08hdRPnMcMc-AMmK
5vbflgpSJFQ5DiwhxDlA3MgohmkRrcgoBxEXLfDzcGrQzpApTRG7REOosJU5pLnxsVCs66edUzu6hPSonGFbPgwzxFcmeUwselgupLpxpIKviKrQiA3rGEPy
mR5hsdoazMYpYVl9bC8WXpBdaZnbWzPJcGyPyylDN1Sox_m3NGepNCXSXCwrcUjQHY8oqmQjbpAZAKG4CglSp7KXCvgeGYlvWWbXmwNBP4RBghKMvuBeM9kv
tfSvLrIrE9y7bnkqVYhBK2tM2JYX_MEvcUipMI7Xv4GX0j2OSaEjlv7bJD6bHghY8kljDcZzdKo8ugi3QXNd7EcTDdFzJaRBGPWigdBP2VYKXbh_NGOLHtXl
KG1WjdjSvxBCI8uK46YMSnlmJjoWzHOPPyhEasgj6bp2F-VKN3V8bkFVsMGkwids1WsrtYT3atbMrU3oFymWvXeWWugFrWdudGrQxvL9VCa4sKTL26f-S--l
jvbhaCmrKgtf5tj_g7Mep1Q5bjv8dwGKMaV9WfZCDr2JUHVbNPkv1idIAcE11R4jhhYq6QqEaAMVCk6moFmxvGPzG1RU6CURQfxCBxBeNEJp8QJMgJBtHrOk
Pf1wlwoy9sD5e_54MShqZYn3eRNwmDDa91J-9gDLjexZwfpBqsGdsImRcKkigdQmSfgCLrawbm5mNaJ0X2aokz0aq9Mii1JdLG4MPXp9wjqotsIbK3oIXJ-o
N8ejL0mLaYao4-MmbT5UniAbVKIJAH5XaYmNIUSo-uRF9XCmpP5neTGGV2BBJKOmcIeNcI4hB4qM4iigexqiDLafJSPDHa8oNiQPNhAIKZoL4JUPl6Igp1Wi
oomMCr6wa64h0nKUB2kP5ndIHp81ySqoxxSoOPDbcAoyBLCTAyl5ikbyVW52iHySoy33PMML2R79Gl1sWNcA7yfqa6pfW2Gla2-AV2GB36aodYvZPOkPQjdA
OY-Z9sHe6Ey9dInyZSovbBuhPhJAA8TE9iSo7Y2peP1tiY3yaYMbjsGoGcQwb3gPAmRAgl4DcV0ucNEzpBb3MQ2VCXuiyrkP_vlCnyoFo9A8XAqio29RtrXI
d2aBoMGXxMGk_zy1tcHIfifoYGRmQICpqA6C9iaYfR02tfCbcIBpIL72PpBkP3HA5bNbCnd975aWvPSgXKKJN3YLbJ99LdAstimf63N7KndB79cFrfkHI_Gc
AuUoD3jcVW54g5YDXTp9_5v6F5acgeRmpcJPXoTb8NkJXIWcynHDHXoFPMMABAeaa-MK5raoMVcRJ6R80a4XBucFEvaBuL1MycXPy2xQ-QBSFSk6OBBa_Q6C
CLOMI2WcnLuMVVOc8mhpPUkDcoogMckJKLfbV-giz3Bv8QFxPOcxgmGQIi2nb-NYjujexcKyHhOzbSlGw2895DbEv4IJXGOpMJoGoHYPRcpC8GX41BmWJ4Qv
aoMU95FyRoiH2e7siaATB6QU8MEexbAgjJPPeR3AIYzpmGwiqL1P2AoTZGLLcumLPJd25rqdixVXCbl25HiRWrna0LIMTdn0PcDitgSqEUi4-0zbT9yCKkng
aTwMH1LGRJA_bwLWii2z33VBx5GDOrzkhHEQBA6OBQoocF9Bvd8du_jbmicJG7kRYBQO-GAL_ZWjPJz1zgVgHGGx6WjSvDVtmrO6vU4oLUcslOrSUNtPoqHb
kaomin51WLgtifX5WdN0HDaQjguLwbwMomEoetA3zZ8Vavt2m0JPgOqPVYjRfqZIoJAZzRPu92kJPEVbLhnVPIKjCczxmXDafs6JlChMSTm74Nr29Xa_KngT
frUWR71xHiREbvsDGlGB-oNB_8XCsfn1-t8BQ59zLAQSxCZGqJYErvuAFIHRhw_LdKrWDweKrLN6SsMMFUT_Fhi9n0KIz3AQAXFEGGG_5jFi22BOodYcp1I7
YqAYHlqZa_jbm9NCjkEHTwHC5IUoqmLBC5HcjXFPoLWf62epsudi9ALWmZ3PGVrqibCR54G3U_FO1hsQZ-nJC8sI7TjCTXus-woHXia4sjdEPQBCzjjGNMoh
Z6-MLGMCzfwik6GB_KfJujjbw_qPNIjSosnssz24ohqoipHQ1JhRcGp5PhVUndAdBCCis8HDSIcJPNRhR636VJBB2fgaoTQmNSfiTalGdUr6cNE1LujiKtek
izaj_LVBUUqs4CD0qDtMylx_TrDS1WJJ6AoabDSRY7DS8eLqj-1C8sCbITKj_YJB0vAqX6otpxg5r2BZKDAPPEAdmrTqspOUrYA3JP25JQQyS_96INbODCbo
IUzSuRQCiZzKt1DeQf8DmIQxcjziRhxh1Xbi3R9KKjUpibmTtM1HyB0E6MmRPAPWdAgRWdk81XbiaBc2rKDtKndTMcJ38xl-kQjPt9G4stAoSUXimeSi1TPQ
CfswozsVB3aK5f95PySxkX4AiAbDPdQAFtNZsiIhi89ib4xHrEqE9GMwjSYCJj7KRV0cK59fAbaHh7_EGZV6SOFC4wpgbiTAT3F9Y2Bd45YABGWi-MHLC4St
QGpONB8QHPPkFFv-v93LA79q4oo4WXfalIZoTQFJmjOWCwBedu4LMJSrvhD6ft1BUbRgj8H2Wyo8edPWYPgYc_faCZf5PpxYHrkmzSYYrobytVBF6WgP8PYj
6p_QGhTCPdGAa-tw38KqkeL-9KEmrUVmBAc6qWm2cHD5lcvfFj9GMQzXHf4VMEWcAPEvWldThVne2p8ZYYPtDsttxv0PWatlRlSZo8mecgnR8NE6rlcwPRA9
KUIFuyfaSwF87ySXkmwpKypNxIdO_3hwuxZnHYxk8DiMHY6NwdRPpJdl
}

sprite $image22 [77x110/16z] {
hTU7agMy3WHWoRbRdFT_tOinjIhEtE6tONfp-ggbbJV8VqPBY_97IOr03Nz1XKhi8Og-fRI0627Iomb1UFXcTR4HNodwQbdN4Fa1fHbNosTDJyxXjx26rnDw
YAAhv-1vlhfyJ_cPF3Y7sTNDBsjzTNuEyroQFeVdguiJ4qwkJWkUXiYwUWwU-nSMgi7pQbOjx7cfSPp9cF0Lvo-CzbhpCu7PNt5eDFihpZuqrrvnt3xRm9wN
S-gpEVQAixtM7cxsXdEg9pItV7NB4uw8f5VbQ8CwCGcPzeZp2HrJhNRHd9kTq34fHhRLSavTCQaVIBKrZZxX5GjM4y4LpgblBDOSO0prRdNt4pgMc2KOjKwK
ytEumrg9HXPSEDAvouJtM4IHQ9j6ksld4zvZB29098XVNfXJCvYYIh4jHFo_5-RdC8q9B8Xc_kG6DOM57GixfWqg8g5yhywjUKpGP8y6N3NRfIaiu2S64Z3F
PnQBBVt059yiSAnBqsCgwedL0vDiAH5uW2NHchsPTgo5GEnvW8MsOzoXTcA5KJA81gvZjOZM8eunI6e4KS7bPZk6R-oy_8PPJ0yizbQrYjIVc87yp6AnOst7
GX0fnR4CWW1XYnYhAB98my1onsZOOuymzdRv7QPjO59sg9vOSMnXPtAsA_rBFzg44oC8MyD2ntfAFR7s3DEaeY6Ehslec4W-Ni0w5fb43-5m74idrXQmm2mQ
TY640_LcRHtJ62Iqk0FvgzaJh7-m8jBt5QCSARwp9QoK89gJI4exbXrRRXOqq-hOLOYY8JnkfXaDtDendQOeah9ZumLCOoJsMD5cHRIBevbAFJ7EOsQ7LgeH
egfzRmDBMCPAFZW21ib8tgpBQGrhgdMKGqaaTy6lHH9EZ9Z135co3QxHJ4BHWSMuStLWcCC8jWgU710gCLgLjgjb0VjitI20askLt0QMgQ9j6HkXyVnoO26g
H3p2l1nQ43auaSYdc7EbKosBX6Rj8KQ4jXa0jgILbaJBOmnC4c4yE7BBajeBZ2qe_ps95CWN6C0A3Wx8C5WZYKdC2C_NqH64OGKpumKRyIVHICwFEJZ7Bfon
0VEOjxXY8Cn0wnn1pc06c0tk6ulQDgEPeJMRmfeHjd5mLmn94W-Dm1Gc2KPojBjYP0lLR72pVszc6ZW6kcAZAGStrMoFLYECe1als0YjSzjcjzZdWo17GhVE
NtR1dBF-2sue9lcNH2D6ESSylFz_m6ShSaav70xk6yCTzlaqbQ-4QWJ7cKnWJZ4wueamdh-lCzYWBCiloUnCvpY5VRQgyckq6657krlCp-4seHd9SIOtc9_3
VI8wG-SSkpk7kzMDTlp2d6egaz7Q7ThW_6XzMN4EyjLXd0aTEobBifX4WnaxvsFwibPJI72SoS36smdoA5gD1sK3yxVpA156tzdDsvbV7M3-Tbv5Yx4tinRb
3n9QjvnwcSYPW_yV
}

