sprite $image339 [330x192/16z] {
x9hNagmm44CTWPRC_t_kvcNRapmsDqAVvtawLQtIoBX_YxXCtkt62BE8BCdjm_2JVB94jmCZoGzpS8COOP6AF1oNTjYQiRWqV1QDdVXuyv4xz3OYQpxtoMu4
EsnDLoCoqY8DHkBIci_kkBJc0q0KNOt8oDeZcYvR9sxD1mfvn7ptnAtvG7cyexBz1z824hVfR4Is-U0-NOt8cWyUqT68hFc075KfsJIgvWCMvN8yBctp0TSa
fCNbQFFH9hrB84PTPc-Rpuz9voUCnsMopMSp-KPOTiHbiCr7X9yctuXoHoNB2jk8hflFjKdtJGPlUbnhanQNMUInIUTd4XNl6ckJreZY8YsJTLmMyjEZDccD
I3UVQvEQ9DoEUWCsgQk0R9XKFoQLnuR9SqtgIQHfKXDGreR9KyPbdANJf1ymgUFoN8SzRh9DFadpsM-oJJfWy_bz9d6U4m-pD05P_8Z94qtgVf8s00b9lIQV
tDlEyvqFtY619JusIOW2cgCtel2ans-NCeVx9ikc383WWaPS7l-mzLiOIKZsTqnoKtQw5yWiygH9vH9OqasJQD0yyNJSvgDDrYx3bSc23NBKPJngywbDKfcI
oTScgKMUwGNIPv5kanTngKmMvR4K5eoxp4VOVDecwnEFtoPPJUU5PTxpR1OFiFdS0y1DbtEyCCbr_JHvzMnsn4Ra9-a5jrKIGcsIPTrCgcUpepQYL_RkHCTn
d0S2S2TZkwsgqli_xl_l6Y44WtBMuK142sZYsFlw479B4YUpXXolBAa6gLgRfDsfuwB8oU_R_kmXnsjBLJN7a-IxBGEgAlrAFJ_vUCXhIeX6OoKqoI-_I6H_
hlAlrFEJZuUyjdIEB8TagwrPWktFLU8BPFwTZo-GVKiSbhwnKPgaspAGchbcVO5yxYLK0D6rH7bPiZP8bE8bZqH4-nETPDAup4y-kFkn14Y2EZjwILiaKWr8
MelFc7n0VDBYLRKrjfDijR9698zQPqq-tX9NbasIA2KWcTlY-Sc7mDsFPLLhxBZa38beAv42FQMpD4bhx9Za9EDo2JbwIn2knIaUakOuJD9gdQcn-vOWV29I
5K2gDrIrFmEIiN6PdtpYb2JSkAIgSB1rR-1Gjl-IP74L69VfoITkQPvdovUZAxIxoxAybQIxM0kDo_pa4xUamo9jDhhopsPzIG48KkxBF0FIn0mENlVAm3sR
zIK9gv3bC__E9ruugetBc-MVpHvUKcZ5X1RFlVEvselwqBBxR7RKnXwaAakerX-VV8mnQ4ahjqYqqNKsMAj99YIYlEJpVY-AjopfA6rSRlGFuouC9IIYbEI3
Lj6F9TYtN0x94wJEiH9869SvoGU-l6NuPNpVpv8w1_Je_yYNf04PVsU8jZZWACsoIPxUVKwJEM5S9YGVaFpBZoNUlepNsdc7v9t5typloLhANnUeWbkMmPVn
glxxcLNOSXtLs779zV7DeAKNyPRel9_1L_e1yZhvn2Nj5V2z9NgMkF6Q2r3UqLTw8hfEFd79hnlVlWA2YBoC-yRkLtuYkau-SScttxv2yH3hjZZUFkUU7Ajt
730kSmUab-plHLbh4aJeDPUkiTyNinAH3SWXajqrKhf7H7vaAPzyhajLYGV8PI_39Czhf0JOUpFuQ5pgQa3sF_mgeLeVeJsV4P9-BugIhbvVGDnT9DAznlPB
WV54bD_ONhADovU05SCluxhd2BSKE7HShgKaI1w9oBy8UZYSPN5kSR0IfEusjfCSc8YsaYJvjR-Nz1zB4AT4PE-Gm6r7Bpam4ItxJv3qbl0lurHzuTvgR2Sv
Ubm-rX6IIrIoeFyoVduOl-le9OSceiVsOoJDZV1_Ix7znet6zf8Pu_BFzu-Hl4v4QBy6tdBqal5QKcubVNzoVyOblQLVpY2l6tk0f2MYp1PtInC1oVVF4-Ir
9MiT8MdZClCEu_GA-4vI050Y7qlIB3kDFKhI3f1vzsf-QQ8lIHnL0fOqIe2kiSTAbdr9EV7ulIXyF_kIQFMn9TWiIUSOaymVb_6zg3sq5mK_BabwIwecI5eY
ohWPyW_zPMcIVfr7mgSR_xGoItDCa4myGDBAhP6QfCwJpIJlMv9YAvXZG3AXnTU_bVHhf2R9awEJl65fNMqb1IJp3f3HH0JoujjNzXUSLRkl_N2pcZnJggPA
Mcs34z7rNbGnoUPealSiuVBafQIe0PAf1yZh1PIN7TrhDJx_aIWdIoyf0c10CZiHHVUYrFRBQW3I5ZREexWt9-Ms0OVLzsF80H9MVKjrziiG-F6aT9Ikk-qV
591CFK36l-R2hw5yMY3EUR8t9sLBWGn8fXyW8tjHVWqbdWvQUSbzeLdA94TQ1gxKWzyO0XBHnlPrG_BhQrEL_IDPHjVsb-Foixqeju0xKF8uzCfQV83ay0Ca
G5nQIcv03fCyHZpC4YcKWGDagCNP9CrnfEHHAwioAEtm66ZnaANSyN2Wf1rwbM6vBv5LrVYubAon4oIjdaMLWotNSJykmb7I9CqnGT9gGTL8oyqrzi14f4gG
aZLsgcHBH432qNlakAJjHQ6KV4aRbnnYkMHizbiYaWkFgPAsejrQF26G3qX4jb-MBUbhiKIKS4WSCYxTRCoKTEEI90OadvmMBrRPahwULIJoBjEoThBo9Hyc
cN316sZnwIHpaq_2JjQyacl2jppCAnbFFZEFIxkcovVqTpupZqkJ990lkIHyGrEs90425v9bZEIQzgrX-Pz9z2Khbe1aGcC73f1PdqcWls6byWn8vYQVwvsi
L4cSBBrarVSZAfa_87qYof-JtHqC4L3b6f0C99zv4z6fkNkRg8SMg8e_0Sd0dS-iYOWyzRVDIRUI0AhkJoUPSESpIoB2kRdFdqarAe2rQdiuoOGxdrd69Kxz
hUwk4G3W-5sBavpc9pPOnrEYMOBgx1e19gbQ_hZxoOJaCykuD4gspwI0DYAR95MrFmAIovm_hLFS4fGDI9WbgfeagShDIKxpan8jQPQ7vClHBA6gLpvwvIGi
9fam8ASxGBOh3DXaD4fRngPekzbbEII1XEGptm4I9DKSpvPLvqKG7PAlIaW-qoKYeJd2jxWLgTRT018QUx83950ArBK4ROl5liIf0O89oMU-0oGaebkK293m
VmqIBdFdkr87UvP75nyzpU8AI4W-yutBDXIz9VlH1qWOaDCT8CsIVSkB-PgGV1B6PMQBznsHa7pcF41QXeIhhYFcQsn_WCmVbtv7DY7vJFy2-Qx5zstR2u3m
dSzl8deryRgksuveylbDH9Q2jdLTlra5Do0dhINvq4C21bbKAqF9vpSHaQstjrAh44W-l-CI89hSNgeGQkpVSIa2fPM8OFBvFK3Y_-tQjnM000n4CUB-AzD3
-ydo3hudX-3Q9Iw3QvSMZ_zy393zjKkBD_8XeaW-uhAL3n7jhrtYado2k1IGiOZ8fr-faq__awMnZo8YdweMykb4H3wTYEnykhYivADMykdYadowdopowGP8
yia6IFBf1iWk88ceaezQElaGKTVO1iXEFkAoaezQE_c8osxdOu3iv6E0pEIZnJlv454d7oAgvAFMnybd0m
}

sprite $image339 [165x96/16z] {
pPi1RgjO34M1072FpVwtEygOq5SoLcLDKxWB-3hwDkTQhqhtEvdMiRjv7Ykm37T671QG17D_LyH-5egWcyvy53e2w-EUowWszrlDVWQ9xvnekXFZ94JaX3dU
QD8IH-uuys49D3BCkR-7TWoPKanDjz2EBzrYoSn3HrTh9o2xOMqnxHwh6Tg9-1p_hJkc-RQXRq5pVv5sr40-CuFCVTjso6jr5DevGpvd_YHi8AzRpRXsJf2H
QJj1NgMZq4uTCdHqmRKJiRNF8Dzyz1U7-t2wTWB3cBv3xWfYJwAZZsld28R0zFY2T0H8LpHbQESTqWnXjWmxf264MOwfwUFQUOSq4CRyXFH0T5zboTrHrL5T
E-U0FOE4QTqsbsI-kJ-wcRyyua8x2QFqmiJC7V4qkljuAdHpFjgKet94G1mpHrXyE_wlQnv7eM_RLcpAkdOoo1UcxPZcJqIJV2UOWEXphpTbNJjjQ6oj1jDV
bZmWkrvRn3_Mb5CoQSwOCVEmf5h8Rjqy86jDMRzhbMEoprmoiq0yGsuvf5IOUKKxvqahCDsRannR-XnI1HqLj9DXSjZIBIdqW0pBHmghMT1EgiY64drbxo2D
Nv0c8L9CZR-gdGYHe7lB8VTr24X7wEJpN4TrxUI8EQKTXMvpl-vVF1vtPc4rozff2N_2X2zC4RFs_HY6VEPJNzDE7Wn3d33JGiVSZh8KaS9gLhKJmHyZfXIp
bNjWwcWYZgIhETIqaqDs_UbT1TeAEjqTl2E2QZhAjPD3xcSO06QR4yZ_VNVia_xEY96lPaqxEUJ-hc9nzlnGw6udH9blfYofZeP4EndaCpE-jqbQw9Zv-wJn
q7jLHnEe2jaTLrXIwF5blqzwsnB8v73F3Pv33YdakT0DnTXRHDyIo5H7kI5po363Z3IKpUIRIIUGMLFMFs-4XIKQI4kket2_7PY1c41cgraN9TQUOSgEi8OI
2qeKayuWywQiLuvPywwYviM21FDLuo7r1FANLzEiULVHSOGr1yu94mjC2yGCiguZvPIqxofnuCWyUTpbjPFV6Bq4AK5HHtpDJr68mlV5VCzHZM3-eZJm0cJI
bFbgmlbTHLYAk6FQYtABk9iiEO3BEbhHEUVxHiUBHHxij9ACE5W1ihQQv_lck1DBa5qtcmEgXV3UENtCFCVqVT9LoAvVtHBAYZ9p7G4w3XmtgGeP_p8bJ5Zw
qY5COBh50L67Z4pDpElVpSzDoUd5eWuPs-G6XTP9ake8G_y7CZBWL5nUVzJ_1SXktYYh9yyaFW6vE4fIU1XCch86IH4ohyF2QfOXeO7qCO4iQUTd7TKXQGzU
3GbaefrQ-cGrIv26-T8da0Nj56PUXTnV0MrA86lQoNLKn2Gmsti9jer7G1Qqyz7LnCmmVzrBPc9pztLe80j_kI_eg8pfJjG-vfWZytbreA2Tpwuck4dmTPo0
S3S8pB9sFjAKo8mN9hPZ4cHbxNoiAJ4t4H5kw1KIxLorcXmpRnWfQAUSOIrZUeCPU41HEvzlIcimqJn3_ThvV5DYlbDgdMRpYdR-l2abriMTWdR-j2bbHk2I
QEUYrQnVEzVhABzshb_DotzxC1QQidJjNDIK1UrSjve5xLobeu9shjCH6k_pGwowTYxMKQwTQrUpg9sBT5JLplKwohLp_MeMj7EXZWhQkNOrGpitJhyGshbt
7h-cdNy
}

