sprite $image172 [328x222/16z] {
xDc5bI0v40HHbGhbly5topoWsLoERq9JnbElVn1YpYknlWUyprlZwwMm-tpKUxq4TftFbQrRi3fVotK7URvfRWO7SHxKlfu7CUSnjTS5KkTXQUi2gVEmM1T8
dGTSTJcfyx27knoMvy95bpFIjuC3dtD1rULSnOzchmkaZghB6Uc7fJ7IHoAuYXhZf8v6RqPQeunJ7OqaTJGcI1sDteoqHXbNKIEDr96O87KqnaaTZTwaZaOP
gQEHZBJ615THepUfer56wcYaaJfy9WMfGvSBKeV1KOqqWvDpVaT9wcYCapeQlKaTZJ9IHoD97P7usrE7mSdpPsbRlw4uVvuoKaSZ66cDyR_gAjBbkywVhepK
qKWZTIGcEDNH62TrD7epqXfbN4MDu5H7OvpKqUXDwcYKaJeQQQIEn0GZhJ7ELTJeJUfef94w6i5Lr1WdTJHwapeQPPgHHfharmicDAc3thzkfBcISRw6D4tg
83IfWt5Dwg2t9dLGfaaTv0zF7RgSaVwVtVAmhYI6OU25zGe0W_glrjdcvLjP_qLpIfW7W5nYVB-DnMRSujLfvFklJYEFs7rr6fb7nFwhqnQVs7vrkjBFx1_f
jlZ4jiMkz3CxhqvRB7PUdQvqiVFgjCLY9ujTwS9DtAKjHhZRXickT7dSCzaMowFlbBihNHxDBfXipEEl-0ptCUmZcUnA5vupNUUTFZ2JNUaYFMQ6upZN8zaM
YuGySeQT1zPdiYsMHq2lvSQfbKpsC1QUm3beaPckunXsVIOxZ8MbS7u7w35d68vZ9P9jiJpI2E24F6Q43RxyvI8RoUCQbe2CE0xG8cRwCvN97iRB7W4Pdg15
pdWJQUfABteaJNY27f5HcMoBQnw3DE89USpAfBhIAnxX1ifOvQv8jiLh7WbWq662L3EPdtScPR6CfKG04WoagShjPRA7yK8UAG5qkEYicSpytm_KbIwK02d2
m8Jqyqp-tsHRB8_F9aKuQJ2XVg2P4MMoX_7V7k-EPv6GOEAlCpcpPhA7yUyUZJXV8wdnEfC_bNlcgqkpXtREHBjndOV1YcDR84Wgx_-q_s9QZfnPJc-Lthg9
UTUPi-CO67sWrDFIVnefM3IxpZKckSGao4t9ShlT_5RyJ_N5gQBbIub3Jvu0sMBI03IekEXuMvMKqzAF8zUK2XhDQamQCu065KF7syrVCYRxLDGnfQeZGxCQ
a_GC058iVbSjT5o2Sg_aQUcKDXrH279JKYH-Tq0f6a8M3nrlfRnMJ5AxL9GXDJfcLQYmcbj2qpbTM8ejEZhT_LRDRSep6CFITGe5o52Xxc8oT5HpozSCTK2j
hERsKFBTLRGvtST90faA4v9wDpTokdWnpIbDwW34VB7sBO1H-Tx1Y24rOsQBYnLgC04frTmoBBxEALtLwovi-oOZ9jyr69tNj9kw7LH14H9wDxUegDcgemh6
2Q1xw5X2oNSDnZazZ2xmJ5AWh35PpQsbk8QEWJqv0AVz9jyn6759ZpFANKbcsaDCwjtNmktAG41t2Abygs0CVFdTJ6hB20ang46bRc8Xr7m97O6c1meTwxdy
hJx6AVrXBdbHqYCcfO3QeY8mZg4ZIMq09oRozMrKp9VqvncmZqaJe8b987H4aRO72XtBZuf9xRJqaFu-8srJKhDg3lzM9TKtx6bwe18wrjFagmTZnPU_pxp5
f831rtF5Qx6AFQ2sFL03ECTNakgT-FAX6R9QFKsQ0CZfQiKPV1seI8M1tEt26kZcAvzrXlJHkSfcRWHVquiZ0-g1Yg8mXKbpPQ1fr4pvnfR-VKmAaDDW2y-C
K5zHSLtFYkvsOUNeq4txSallvpBVpOtBnKgfFBEjPrKY9dcFoIqdGyaNnfUFpm2hIiw3MF55noB8rxoOcuG-nkG6E44uhwDYD1AVc-k6YkPkw_T8HPw1DYOL
uFqCLDf6xOKiFQNFprHZilMr4fWcY72BoJqg7j7SDE_5bvwvR6SWyrN7q6pQwd8L680j9ZTpb-FK5zJkHg9tXcfkmHWwtZMhCMc1FQe0i6lKB9JysIhgb9un
8rSbaQVGaIRjLX4CTNCfQqpwzar6JF97MpezQ-ePI6fFuSHzgqYAnt5zzEABlERHg1q0kaF5_eLg_xIe63fcAhIvCX2IJccW5qC6p1h0kTdtAKdz2dpfZqbt
CjQpef0s9e4v3MwcSvfW5cUWqB5ybvBKhyAN_ZEGabBNiohjLZ6dmSko-HdDW1o0qvXRUK1BzpSINQYeK8VAxih0jFXwqT45qnNGRspKQ9tuqcdfZzNb5BY8
mfgOL7EpzNka8hUDcjTp-OjPkXiL1IfuZ4ahfVfQbCZN6HBcNlwfCNaS5ViRYVwOP5tFQdC6Sglv64fMLFGxT2iF58pzZKG_AX9IO_9kRi6uwjW-7Vat6pNg
DpGIlJ49E4Htg8WyXuvgTQlON1aeNwmazNiRYS_KvRh6PAmJDrG4GaUuj4z7saRDb0TGiRUHw9_BL56HP5QBdi9hJ8QEMOdcXPtRhb5J7YOO-_6bFoP9Wa6B
Lrtn6cOLUqZ8xnirK_90-zJ-HgB_34HTrufQYeQEWOfAk53RkZnq_09pKm-0Bzqn6Js5cbkU0BC55I4AiyU7o4sZPihtjNGxBIhEQIXkdDDbDbjHaH07Tp5P
6xMddijfVX1ywJy3uN9fU0RJzi8E1X92oc-k39WgNnbVFdFvObPRUSPLydZVT5CSf3GnkNhx6PyazLZuqe-ALeenlaTH0ZcsYlVrh3nS6OZ3P9-ID3yQllIZ
ebTVXsRJrCQavcQhQ6NHSHNIb1qg7WvV-cDIDOUEErGCx740-uV8zL0UCVb2bkxVAWhoK7KKAkxBC3XpBC5gJ5hPjWwVEfVtggXJEk1KLDpuchwhon7uEDsn
nztZ0BGf-KgMxaV5fgTWOsukcexfwkkYssrjrAoEibl5_YlUnpa3-MBTB0gLNKmkEavcpca2N6kZvcR_A2QfFm9V-cEIYsPAKMXhRi6Kvk8cOxfarpXDHfds
SIMfFmfV-hUAL3X5qIgPmzTZIhC7ziHLNlkmkMd-eng9VbIiUuTzJ6OpNtKCx8cjedrCIPhvqHQgNz-e0OR7cBHIJ1OT5Ke0KsmLzqg-bgNxBr-em4GKRCpj
gwzrlKmvrQsYjJ7PeUBn6ed-kbn0mcKNayefTDnTGFMRXv8wgvco8nWxyENOCMbGsMyLXrL7hTWZMisjWqWe-KmLRKe_SiQ8IQqnQIrU2u15nznYZtdSXXwc
wuITajGNm9TUL8oOTCcBLjNSguum8NUDcXiuvddIYCcguW4MgeU8oRX6dbdnMjnORwKATezmp33dovmN9SFIhu4l_VVqAJG02yyKMpHp5Kfya0gLvl95STFv
EWmpp4pDZxHG_VwjOkqfp0jpw2Zocp_F6J4fk2hDp0vmnVjGg2WKO4opct4SPhXkhpxLe6rCkjzkfZA5ZczjwLR9PgiufQaKhpo3N9ypFM2FkfURAKB7byEN
VbIKwzKgpvXW6gDHKwankTigsZAlrqZqewAOkLdeg8ohfarCSXUJQpFvWlZI7vEattqjzn_AIs5UiKSQLBovdPR-qrRntbE0pG-A1WniiISQjOv6uaNdojgA
vM7L4SrMyNVOOwUb_xvLd7FeQBl50-3SOmyFi50zCYhMda8SqjRbOUphXZrIEXg9LvvhZSb5nzY6xPG4W26DA_P8ES12zT2eM9G2PAdt-kun6T-ZcOoNMSfR
u4l_1LGenQ3SxMUNEcDfkt8vppf_dg6zfq-uFZv47XTVXuxlWI_z5r096fHYZPBcnKn2nzFIVvs9sZn4ZfXijuhLrwUbFtxvWWAJXvXK3r-_3RxqesADIOgs
MqN9rvJBYIyVGaNTnIIvVwiuetneeNhEH6jZqW4qCGaf9xxyuwqYQqy1zwfaETv2zVXRHQxhsMdom6j8URj6ely2gf9az1IZboAXusdfprr0NNISp0gd6LBE
HkBJMqMCAHStkQO1vSINprz0dTFafGJFzE3BUGRAPfLdEXg9CoQzUEqfkl3bHCLIUxFJqdsDcieOEfwDHFTMyPBBQUbdR1LHde4lPqnAEV7b6Lj5Ay_1b_CC
z1nyEMFoELUyJrHyXgNF6VKdMVg_
}

sprite $image172 [164x111/16z] {
pDJ5OG1H54BHaM-F_lkDkznuW0fOmDd-9kUQ-nQTOqggdjnmI5KbhHRQS1-bkeqqZyI6_RRXGyiHDyjMgkTHzQYMRKdrAggSMPvlDhmzpnd3pUjwS1uFDnJL
s3EuuPOzWXkELelX1cTfuuO3fXkvuLdk6TnmosRW1iAc-xdXywHmmwQdSCEcPt33ffyftF0iJTnOJT-_pGsRRk36P_fFkM7JKxZXywIScKsFQiYc-xbXqrEu
uLccSCEcft33feTmmwR_ufczffzmPiDvdDomwIbdPjFJ6hBfp4tQBDioDsJJcHl_B9aRVqlW9YEwRCvCi1pLOXXQcNYQJFQ_sfxYavuRVkLJe1NeHDSMVadr
C1_MeQjgOTtiBAU-gDVDKMF-fYiE368hFZ28BTiwB8YjH8gE6dDhpe2j0piii-uQj0y8OYiPa-UP4wF3WTYAoMbaBZdMuM9kZw00rbnfbqUAkJqEM09KSvmz
NSgfFoeXA8c0vpcETHWGVwePVHN1V7LfwoWWjkmnHB5TrZod0zyTn5Og8GRQ8m7Dz_jSiVO6iPLK3KCOe2WH4k3v_iLcj2-8hLJfykP1Ym0fOI04S_-YidO7
CLN-Ud4Pw9WfZbDg6b6ronr1x9Y_NQuHUc10uPowdCEXH-3MhZ6pNm0IYn950cJgSeemdbXgpvXR5xRBdkjSJo4r1lFLP5bxE4pb4NFhvef42HG7C9b38g3Q
pgLSIp7_fDFedt901XYEPpqsbXyCegz_U1H5OWdZd00HqTap2rXk0MAclppGAx76ANMv1A0eFbpM_0XS7mHYuU_Fp9CJuJ7NOv1ahoJDZUNc87Qj_4sDPPBB
AIIdPpsoiQnOcuEOXVyCUm-DgudUwJJ0hiTskMtCfoMBZQN2qHD34USnSoXTZz8s3fTZ_XLBebaaTPxkE54lrwDSIxMoLhs7AFFX4fhnXc1wRLiwYryFwzLO
FkUQAhx1r1Zlnr9PMIlhTNCYKYA5GLwXGRFhyHvBhpbShfLbTJtIUDIZ3NGzLWUk_mV4_ALMLcD90LSM8HFixFFViFIBCI_l8V8ytNcHUgUB0ElUXzdhCMin
vcKixGdVvdeCKizwxC2jb_RDKiphiKpX3IQdGVvSZ_4_iPHVhvNrU-WC3Ge0IH7q0yj_lxtu7RNo0fQK1YtrYJlTIc1glfSJwpqWPcsjhA_7dci296_docKA
zDLakrm0SNMjlBQ7AFTSSwgSBiK9_fRthyEZhM9UnlB7kSxf4X8JCvUTnEj1z4BCB-sX7-fHrsk0Xz-vec5h1OXzb6wbqsYNW0IGmT3pSNMwmLQ3k5MjhAz7
OQ08Xi2p7alNgs9lyFNmZZtanrpV43wobm3cde5awrfPZoMkt-OQ4qNoMO_sFqpsKVe1wdhyOQxx3cyiyt7xPdaF-Nm9kXv5WUPWvfrZ_XbB4m4i4IGDt6p0
bGs-7bwenn2KA80YJfZ7pPKFZddvUeIwUAWRv-bDbULQ-MWiHR7dEktnXQ-7BUknvtgyQSv2hNouJfFxDHqKmE7AGgtiXYKD8EgvVk7hOSDwb80JPmnN5cBU
5SlprxbsPSUOb-lHFTSBjRARpaoSXySzQcLzFUgcIjVACJMvd5euIlV7iclbqBfecvW_0m
}

