sprite $image137 [238x180/16z] {
vDQ7TG0n20HH1JX1_mKx9vpMsNfpKmF_BUrFct7qTfBwogkidIBFss8sV1RvqEeDtLXPSZBO8rzaTB2r60tOZ7oZezF1rfmEjXOWlfQw1U4x8ak2B-g8qNmz
FrDCrkfelgpLqNpfO6l6MXtDbmLMywM3hNadhOxE061HV4Va3xOwQNLqJWTR2oEjZYu6QNLqHwU3hJbhTVGQyS3k_qns0HR5r_CFSnPOpPUrEfelQtKqNphO
ccsmEX2-6YoPR_VS8DzWTM1yH-GsnTXWTIXhvBbTpbeTlKQ0rVd3DT9WqNmjDyzPO3LV5bZDbxKwcYyTRCtuHrpvibP7ywM3hRdacuTO7HJVo-xkH4UH70O3
S9qaldZ_nvqkcbzWH22PQaectgErEkTJ-M_dajPCreh0TX9VEvlH73sm-w_reJsVJVE8gTD1hQ-rc_U4muaEAYyljPkNCrCtbQQI5gNC7NbFOq7RgNSjQL4c
FN7pNDOYljnhVBss__XwhQ6TU_8k9QsAzHjVQEskYSKwZI-q9cAtoB9Qf_65bWN2ItKSNxkudBRZ-Dh6iWSjIu_jdCRXZ79QPkroCLdGmjjLEukMjQnzJIDM
UwKLwIE-i9h9IsqtyMKnUw6bYxQN-8hQAoqHGVlbYqaqyMij2xGiNxsOXBMipSHofnN4LxxFAsPbBT6cJUb1or-wc6IridQJo5NxgqH-lo--i9Qr6tRJPcY9
6DflcqQOEcLjJYJtttRJtxGYtpIDHAsijMTQ_8JMnpT-4x_Mqg-M7xLORVZuHhTMVbl6x-Jy-DigVdmHs7OjlgrVRVXsZXzOhpMrTzh7rORpXczYhsMnTzf4
JilkA2Tw4tkji5Yb5ldryGtUn3wt9hLQdr_Npi6R6DgjtdRozR-9N4UxevpuLcZFTLhyX5PSV8C6ThyMguqmyHMrpsYPnPrjkCLpq2P6oQfLMeBsoMyh5z-G
LfGCGx9cRSu-low-qGBhjSD4q5ATzidPngsTELXWlNQhMIvQ4-RNsi9kmI-UGpOnj9TQRn-dKklpw_U2qPeOnRVtviXUJISNLnk8RwGczbfuy_NpAkTAxUDk
uIw-aPhOQr4pumzBBC9QhKL-NNn3MRtMnrU5cVzBw_Q2CG9RrcBwdhLDIyHos4cigEtMeaP2BzPhStRvLHVV04rSq6BwRcNALAjDJYjk6WMmbhG-linrMdh8
xyVYAsP_hnt6MtpVQ0lvzV4DyM6zrjU4-DPh_Mh3JQC0LcWBjLpZAnNQGdvTV8-TElLQr0b_M2PkqU9ka1FzLNn5xTFQOSntyMtLKau_HUvQ_z0chjUY9aRs
MhH4B3dzLcONtuEjlX9Ox-FRe4sPqgsoY-_nWKNn35D5V5MPSgNMLNPFl8yEB4hNeQx6VCkUy5ijPuUb7Mz4-S-iQQop-hqWlzC-jVhfUtmJqpGqrOAzu1ij
Esi6jh2uEgQ9PMcY-hsWI7wkrPpALcPH5z_3clZK2FLxGMMc9rfHLV9DxCkVn1vajOp0DjSiT_7rMlqjoR1czbKuYVtqr6a9R7alwBLP52MkYH-rVYyOBR3b
-DvhHU-BN1DxBRZmVdRgx9FwlQ08vqshlZZ3wglk99RrmAdJ7b_nLiaEMz0MZtAENIQsnxVMoXKdiNpaCj5NvLxG9xPinIrt-IJs-6LYVM4lUBCoh4NjHYgT
nBB42MnvCMc-YSlrvYGsmDIfs0j2wwn5RNvyfOB5f1wmJDmVNsYLtvO8tRGFRsBD_iAhUHm-MfFKQeltHh9fBqqIPUgKYrIjLKlkteWtxVxlA-lm-Q8jUOrQ
_FHQVDuWKwUijIQjpo-qLs-OgLFMdXkrj_oIUAr4c3hbogrQJ2AiDlPgCNNYQnF9RgsREh6rUQSMWUrVwmCRNvjtT3826rcRlNR7jqLWlrDhQfYtEvQ9SRK-
jyfYqEvT9iRNch12ktUP65zxDe5szzI9hyKwkMhgXDMAcRpMIgqMKoUkziBGVLe_TS9gQS4JRzsjnTI9ggNLNUllqcBgXDMcwV5QNpWJb4rQt665rURv-HDl
RjTYweJLqb9wuityFrgPXnYLLUn1IwVnnRrWkrRN8Kgbd9BelJPFB-y5MxHO9aQfvPH-Ykwrw_3cYRSmKr4RCB2ewM9D9Ahkoxv_uirSfPKbZ7LSBzWiSjCk
bTVwLLez3S6QEBE88BUd-clzzrhDSG8xeuc5L_xLfh7XZQYf2ESNMfw3GDTfN66LxNkkea9pTThT6r6lbIZBHDHuIYSqiLoxRKnBKmZapkkrqQREl44f9PRY
zwn_ulrCgu6cph1GJimaKfoiJV6zQbNieiNKYQCb4X7Psss8hzwVEKgagOF_xsz54zS_ySQPe_pyv768LWlLD75zVF7kukTVUOXNe_y2--DxHKFRRytYjRtN
gaxRVQN-jRwTlRR_TkvVwvyyEstlDR4vRU-rI1e-MVy
}

sprite $image137 [119x90/16z] {
lTQBpkCe30NWtC77Ddt_jzqwL8eicat7uiUxCwFx9tDw25DebfpcQVJC1n5e6wnk17eFyZeGNJFeCqZB87H9g6frwHWIyKuWDoCYtZ8yEYBY9O6-3Vuoula0
w6P0-pmer14Hhqse0oAsK9y7w5gc-U5yNSHTRyAV1taR5QeVfAL_QOP4t8Gw8k8j1r1NfXwb6H7nV51KzP_4U6dYyDQvDFqZjb3xgFwJ6By9WsMQ0wKP4V7I
6VKHns_2UCJDIMEBtuGKlozBeILSclWdKKlHT0JH-7sfnU01hFyalb63PGXC-yNMKGx0yJBfwR8OJ3GiOXKs5Zpkf2rYLL5ZmGFXRIesnjh_EkgawMBjZmmf
4qGy2_pzIODLBvP1bVvZc4KTIyGdo_o7POAX5qjWoipsBm0NSNVqOf7Ps7DZm9rqtr1ls5mFkiACtg5UhAfd6VMWEz-NED6B5TQBzHkBdNH_j6uhBTkxJApQ
i3vRlp6VzoNwhcgibTIpVcFuYEEePwTTtBRDnc0NSRmqdftcf2zbV6TjOnTnl3IUVSz2vILVML3TM2pYyFcsmzCvAx-Au7PZ7t4SzQpDBY_bkuqZPMBLPzOY
BYy5WUc-J1MEXzgoDU8YZesM2HwzP-jiPyHqNoPOpH4fZH-P_1ptPG8X7mSzjfWVJIsO9ZzplYiJfNJO__MJ63vVcpHFpIpuMYQgQAOhuWWgghHCNsUJL_6R
8kNZICTXA6xB1Fu1vSrZRSIeR68HfBUQAdfN9XPz73aQgucuic0HKQ6KOLDPm7qIVmqrpzF3hAXbaZfC1CUwLy-FeQxJ3xEV4RUeiMJqzUg9X7e_zaaq5Lu5
utDzr8WH2_L-PZ8M5-fPPeDLdbVDo_HFSwW8esMlPrufgYB_YsAT_d4sBShDjfJPQ320DslmBLfadwO8UxFjvmbWR55vk0cxihQnPvzlmlWXUzP69LgQEAjg
RBGqSPPLvVacZBC4Qbajjjb3QUBiIKfXpxQ_P2iDMsdwi0GSy_b9lDZKikPQQNgnICldawXCk65zQUAiL9P0gtlr6EdOcr23RCh2HE3iNpqge6_Roju1NVOZ
GTXI_VRgQTaqzrZrI0HIgQcshnxtI-uJwhI_qSnvdlQythzwmCMckGcZi-HCeFNXrQEVox6v2QCp4_F-owldl1mBpLEVcVVvXpEXyb9RTvl6pbf_KwDPArCP
pzOoZMVhIVyZ-ny
}

