sprite $image255 [236x172/16z] {
v9VPejuW28IZ816Pzt_ThdzBi-BTKJktMHN6RzY-GAnxtluBvQe_9DlwIhj-nDlYOdLLsXOMwL5xMjQekrvKrZIgwAruRQCULHVZ3rLzaQIbEEDQkv6BTeZM
CMgiFQ_6cS2swt6cF5tWrTftJyy5hxGIPtmrzB0Jot26umDQjiaamUaJRCX4ucwgv3gtRNEDqq9yW4tDcNz49UxtCZ5dNAa2HjFRbZIsdm0mGDE1JxF5njnH
7mPWgWs0nFqWQIxE7EiEcFwI0U3OvpmhPog0fdzaGAEuBMX6piZlbReQW9f2k-zvja181fWUDADjIqySOBEcLnbWWzisvamE7UshrTYsbMRXJ7shMGDuWjYO
UZZJ041UTgPqka8c28HezZSLKdsuNOm7ZeqKpcFEcUQfaEzypK1NRAnvLCwm0UQkn7vfVFOuvJUCPjiIWp3_Mi4HfkLWMpd4ARyXcFR62uIxnwHhAcI_NU3t
MT-qHsDmnbMyfdUfi92t-UM6KQQzrDrPVkDJAapUvgF5ndxEo7CB6e1FMSgbpSUPzlev0-Fd-tsIa-jA-wUzIcDmnW3zaFFXTaelHstpsd_Hj2UTdFdyxNqA
ba-RVsVUV7San64Ola0fJDFtVztxDzkXzzF4YeWENJuZ5YzExBXC1yz5KwYs_Ny43srsmJI4NV9yt7MFjktpmGD7ZH7EEUjC8yzvrsrSyDWXWIBQheC7kk0o
qLpmVBzIv771CxOn_YTsA2LTS5befyXpihnD5sXlkZySFF0vw899Sxh2ZIoNjf5L7WiUZ3EL8SllXGqq1y_1yd71GzlU4WoujNSuheMWlGJFCSn7PRUzlCum
UE1CvJCKl7g0ATZkhuflU-M1uC6RgUZ0uYk7VR3k1fO_S4WGDuJAEqmTs3_PQ95tvOZBRtlvu84R6Rt3k7nquFoqzNkyfcrZkx36jxsypa0fCJBTuA5rkc36
QnnnufLfsvZN6NXVwHtgHZl5Lp_kEb9aQoPuFcuNFYJ8wmmff4ScQKuNVAqzOyIHvpIEmREz9MK8vQMqGejZap2n_sq8VPxFrqL3cepEn2dGBdKuJBnw3FFO
UZGk22X6IcTqQrDdj6sq3Icon_Clnh5bjpsjCt7EZmwKtg7Pf-agM0wUbqcsS472DWf3691YTfRs3iUAHj0yft5C71A8uA64BHOxItY7IsUaRUpDMOyosvuE
kEFMkK1dC5E_wKVRN4wr-YEorHlRdgBlQAcWL5K43uvte7wCCm-z7gbiDJvnncFahIKLbJELB7TUFOmZU2xVHn4_089gi23QiYwd9xm3zEFBgsT3QvwVAzAz
vcBPC3R4oOgisih75ZZ1GnN10rmmZ2DuxewTvQHGS_I_K7f5PWs0WwVADcuEo-62aIIIvnHoo98ivp_1nn1rZlD_QHlj2bd0Si91GyiHnyzNzMipYw2jsaeC
QHS3OFVqZN0WM-0vHXm_NzKep83MVGnH5JpT7Fse-5u2h_xwRydrwAToarRq7VSUMCrUkkYrMGkblJZwWPbAhquBf0aMRzJU9woXjbNB3fzcgTvtFPoflAxW
rMk25GlHTyQQQjkpTwZK47zyr-FCL1Z7wSo3rMpGd7sjaG9hh6qtvPIeKWNncZDJOHpnXPiow4U4li0gm2glpUYiR0Ve3lrml0ECe_lggJDHfCGQ9_BXSAWk
urMrG_ECsrwXSRHlBfWwqoADAh36qEuSWVFoNV3VNwptfhp3liZVFHJ744PqHcFLQFaOrtzM9ZjAj3tZo8bTbriwex5gi7oCs4hlsCQhhyb7kk1ZlQ4p0gj0
gnu34qC8i3YNNOuMzcjho10gh76qd1uoUsjMc0Tmgi8xAByMrncDDOwMmg5t8Df66aTu1rI3oEqta19hecr5bTwyRUyoZbruXvpEnB7cjxsrs_igczkMnj7v
ElwUpdHL9YgvxItZ7RHrFbM3SQHtI0KFFO5LRdiyMM6riH4WweDnzBn3NcVYMBFRtjaRVGQDenBjBQ4pSQptR2Dh1zHbFtk1SBYYVITuo63DRNkbszHqwp6I
NlpkGNH_lb7ZM5FRtZf1BUSxxMcpIjMeQ6-XHarYlRVjSIvjHty3_RtA3dcgrdeYUBY1DMKRHuDTJp8zR2tYL2sXCscicMrllyXjOy4jwjU_zmDkL09hSjiR
4FR0joNt0ku4rZnQPaLdtHQzxMM3XppMl6tSJZIeE99F10zPhBfUoMsFLNA6C8yrRnlZjMmfdSbZpRTjjFB1GnvhlcrZbGYudy5gxUQsnye63_4wJLVUDkfA
1m_nif_I_bkqEZjEwqoywdl1qfNVzaJbT2PUvsVbC5tvRG-L2BXlrQptwyjGp-fFrX3giZ-BjOyZYu4O1gBVkya_txspLbxWOmpgQW2Q8eHd3Dlb9s7FEAZr
NbbiVrFOtiEW_WlGDUoVptN2CoFecVkqoiFODdkc2gyLs_5ezCnoa3dWdurFmkv9pwmBgBSqji0pq_TemFRLwXc9xGjuPkBYiJ7ecMBofSl7nX7yV0ke5Dlb
6ndFJ5-mxGKzKq3bs6hFJ6CR-921PuH_aiF3WGkqlVJmi7mcDdhFWBO7G0NOGi-0jfSP7ZosdSD3FH0RWMSejldXePwAZJeGWhO7F6EmxHmUV6mC30zHR0_v
vmSymzeU61wOVu1dM6m4dc6n4NY6jJtW6OOjy0oBZM1uODW2px3Ow8Q7UlcV161uODW2px2s1uO7vf--WTktFH08MTi3eBAs1mAXmXPuXhKzC3oms0WymzeU
61uOji0pB3O2pp1iWMTOsmF30sjxm3CCMp0yiDW8XWVc7-0PrlQ0PrZR0vvXiH4C3mnRC72pjWT0PR4HU4RTmu3w1m
}

sprite $image255 [118x86/16z] {
l5O9bgmm23HxMBp_TVzF14NnELjtPtP6Ku6YYYo_NQcti7nuXGh_L_aiQ04Sg0ZvSvYf8yZ25Z-36Hl2iH1h-0YXA7Zwy_tqPZYmwexRqmS8LJvZm_VJ6oh2
9RdSzzJVH6ynnRsDvhSMLxAgBRWAl4ijkdKcPYgUxNUeHSiOWH406UK8y79w_PwXCqc4UtJdUeDQ9aQ3VH6tu3XuFQ49UrZ226iycEEfIRvMBQ4p4jU9eVc7
xkdzlKbw3mXr8vGfJuoPVoKYxk52R_yLlRT-rrVTb24kePR_sCWZDlDV_coI_jYfcEo1rZwU0jxFGVAOBT0B26LCvXyzBs5PYXdmA_Xt_wQMIZJAgEqxLLc8
ye61qD8IXLut0tzfVrj8sdVaa91Hw0MKHolJh-Yzjva2-vhc6vVOcTGa9aQUPmDapB-OWTvI6seTvoAA8yXeZv62MBEqjvk1FoIq4Errr1tooPrmRUDDvgj9
Xk-Pf1-LWpnJnvb_16OITz97IzGMceln9eblNnRgIhQEUTXVOr9r5a2Knk9sOCnOzYOPdekxqn-rioREsASmdTof1PbxJ4KmKEhHetERHxNSnc40BB6P6TTd
iyavK4oaHuaHLx_rarfy3N0cDUeO3pUgPrNHI2-E1cIb9ViPwDK2jzegkmMWgUDiB3oP978RkH41x3G8lHrsUaqookXzRui577MKkSggAeIz7kMK1NNhCqgl
lg4XyeAEUNOp7dKCCrP8tMcSN6SjgxWtX2W290lI8bfGTHQxojp7LeGfwgmrgf9PgyTgg3qYJMuN4LbOpSMiMCLiX3wSoZZL4Hc3FGTj9gAtTRfW8gq3zefB
PtgRf3FT1pTbs3e2jhI4kAG6rn4_ytTfhKpaqzN18KQCW1AAVPkhREe8AB5weg7ijtMFoKnaS3szQRo6DMOW796Wrgnrt6VjVeM3Wz1s9HG7fg9wNELo9J7k
eDatEfKa7BDMPvEAlX0xGbTML0ThMxCxzzG1PcRjwQXHrN9VN8lgSTKHpcRLC0bzIcWBrgmPWr6BBwv7lLLHF8kNDjVBO6QjtbZDEAiFc8hwY6jLb0W0opOl
pAnLCyOMxENE4Zf0FUeJlJknWH2cfd9U_AnjFJsgvHxrcTwnXYfAA9rOqfCbPloa5e_grxr9zh5TPsQ4thPi3rFiZshngD_2fRgr31BsckFbEe3jMIqUzLkm
UZthBKTtzK4bj5yn_xLQ7hWIGZ4G4xq4xd_St-j6Pl5JvW8ZOJnv7nzNjD98vdpSEBR5jF98KiOCb4lF7Nfn95FO5YmzkYMW5orA0LkeyroxZvyWKWpUENBd
oPtxy7tl6_6oBLZwbz4K4cyhqANxZoR2ulL0itlzvZxpsi7yCT3yrlPumm4zPb9zLXRjqXQ8mqkTR0jd47ZJ_94j2MZET3sIgLS1vNG2hxU5qw_NUC4M2TJZ
lVbnuKGruxtpSVaSSvxTG05KvEaDl08Aja3CI1x25fFh6wZcp-E5U5igBCB7WeZ7Iuy57tC3Aspn8obiASHROOiVoGfR_0qKjXJY5ROKuhMsr8oajALe9E5f
hU9leB2bRYJZ443BCc_jjhm2
}

