sprite $image374 [262x220/16z] {
v9c7ShGw38KbLnNs_H_t5cIl4GaPybS3P_fEzJS-nIpy5f5IIGZFLbh-awfmpU6fBB3eiah_bp3b6E1ngh9qQPTmIOz24Pb5FOOkJl0K4VCN7C93af5DHnmg
FY4QcNSOzXmam-rLUEZG5X7khS1EHnpetl5GsKkEE1IyUJIUkmvoszP4OZxFWMuQ3vbtUc9h8X_AZ-gXVEzez7hGg8wyqoDRa_XhoP4j2jwu9P_OciY7Uj2e
Bim_nQ66UpqWVZ0UfDom9P_NcXQD0HsAvxKc4dFvresuuripCnEU2eVRVegoqsTt5HxOcdRwWZQXQ_ZvUC3Blo22PUKvtMXKksuexZl3WqPr5k6tN4W-gJMp
wk2Gto59FykXuiKegBunKEauyizYq7mj2iR1oLBpEQsPLR9eiqLNiWPzJZna5SIYZWFXGM7Uz5EKKO2miqKDI6owUMjw2ZM9uz0XvFhpyH2kGm60d2rCrLBo
zgsPLO9HACeVsYBOm_ldtvgJSy0YaXi5Z8w3lJNBCzwQWLGQ1K1njYYsg9ymgaCLLSP6GQhZa2gRYExyAGhpMlSgkQuK60APBRmYv1ktPXPcuw2D0iIn7joR
kzmt7d8_hgXIQ1JgXr6D0FZzUEYQlZNpEAweL5qf541hYyEhS7vKlrulZoBFIM7BGHbN2b3KZSaQ8fk-cPAleSv2qemKghoFAw8Sar58YOsF4s4ypK460qTY
eJ0V1RHM6DV1A4G8RZsOabkJvo5u5ZGX1K3njY2ZW2Bxrgnm_j6jon44uJGb1IhE5fAgKO3Tg8u_VnKM5HR1AIa0UbkeXfK2HDtQWjAxAof_BJrce8jEHo6i
522hE5jKR1IeofR3kpmZVVigBClAuFMQZ49WvTWen3QMkYsAKQWGzc_k4t_mVWf1nEZCHc4rFkjA8RHM6AEwKO2Yg-Jy1rfPFZU3BOZPA2HPZykuKa0MLdMZ
kb78nO_g013FGV21y39DbmiYwqX8nIX0Oj-QHY6DUs9AlIiIdOd67WYJKh2JYQeq2X1Kj_6WP1I0_ISvUd-FIeTNmPlXzPgPWghPecAZGDNR8ZOA8JbR7AUa
7ffXMaUGdKn49OlOcpBwU12ZW13tAHa1W8wkWZV3r1JOZcpne8q2bFrwC0f1cNmyV6Q8nJ4mAhDJUE_3DfOQXUH7DIUZGBjHJUdO3xuTvwTGwpiUXCQRqe_g
Hc5ya_1ArVd11S8rA6HdYseKh1NSg6uKIlt8eNHlwDOCZi7y5A1kR46X6WNSZUfg5B9V3wuiPF7jU0KAKPI2KP1G1mSn2W11_QXk582qS_2JMXPdXcjGW51L
o2Yq8XHR3wLH4FPlxXeQXUX6TKQRrEBUZhDJyCEf6WLK6V70oIZGRbGB6uNWRK69x2gCj-DrA62nYnwC0c4Pjj160VBE5iKeeEZ-pQsk7Qz28OvNj57mexhW
IY5fzQEQer4GyADQbeD0cBqZnXx8dKBbCQgBhXGoH3dnIKvT85o7Wdj5vru1ISPwO81axmZNcbgmKQZK-OWpmvKek9ED8dIZEXk5i1lLMMHtJ_n5E9RCLX2S
nGTVev1eZEhnfjpPeb7eayiON982G7MlQ38AmTcY60KKyQEwOAEGgkfP1g-bm8mBMZOdsnQXR4QrKM3OZMeo2X72MGhBKc5A2YNnDXug6WN6EcoXZGAa_Nem
2d3I3uioqvGKCY0vMuXH6F4fefex1TgFwlCKR4_CjnUm1vpZeAaVcMMCwcm_5JUMH4LEKkYRQZ8AILLoRg-foEvhGkf7xWNPruDvm7TiFa5XFB8KvtjBIQC0
mHj-7DcDwlPJtd-fFgRWlpZCHm79nb80MjyHN5myf4wXR4OrzJoCkXlLomapp4WXCPdl2xVNL20tgci_SjxOelxBp7aepPBgCBZ9sCnz_yUz2QiEOlyQRw3w
GANTa_kRbYqBcFb3GSbKVwK0CLox7s4V96RAoWTRGE4HCjMJWWOorHk5FO-_UeuGuz1Zd1GocMejmIZ4rLHF2kmUXYE6YobC3ZhDywJmHA4qGIO5k0UTWpWc
Qu6fbk4mk9W27bZ_psFTcjN5FI2BrSLK9nppGCrW2fp7NquX5bquI38A8VEi6IQ5lfZg_PY7ZYz7DswcW9D-QzY8CJegxzXE2lR8CDMWK3iwfIE6Yob8Nvvi
jF28_J398k6Hsv9KLnppoFoyUnv_FmMaxIXyKZ169vurY-tUKL9j59vL_auUVoa5T0iy6OtHa0NlOVxgcZM0WbCGRgMGncZ1A6GB6o4Bez0sKmqA-PSiL431
tQs-r47hq3efMCO6MMZ3D1MfQqgV58Av1yJueB0LXFifn6PrpoW46ReysJ9JAYNLQ29h9DSYAD1kzVKKGXLHnT64IK5ZMsNHer68cwas2hAQwjafIGptKyYM
4zc3oQHWzH1TKsLciRjx49qK5lSm_GA9uNOAECkzsiQCyuwobeTv1niXFBc7Y4WEilZGx7WzXTXaBZplCXZ4qPwwbWT9CYayd5JND2cKNwOQByBr572L51HK
ZGC6WqZdlzNS0mP8DjMJWha7Od3ztbJkib1e-2GdXp8fb55bDTNrrsq9uf10eI9okvm2Ym4KbedGwbw1FyohB70kjkscUjf6ZQ7-UGWIVtzt_0E5OhS95UvX
SSdWG6CqcMgZy0I7mfeubAk-x1SKC1ufCZQZ43TJlToMMBfcTYdmjAr3ms_jZZzJe71LL9UCBO_LL7Ue9IebrKeK_3s94IuH0oXeCGg2yOWpDjMbFAmpfP8i
_Xo5ttvx3Drnfu3nIBhjGO53ZPE2PMpWqADH29kf1WL73BWzTj4NmSCtvKaX3rraeVj9FuIDHc5t3mu535aEXPUw8pDGLHr3IvWKQhBn22xPJlfrMKrr1GMA
v5OAJWmxmWK5WTw4oK6qsnZTLrcqR2Vz0fdgddJClab9zSSj2FZVdgxvAdpemHf0H9ZGLpDf58mEkkRFxc5yUH70051QVBSxkXJ0ePP98OQLWsPGA2oBaCnh
Tt0OJa5OAOYKy6P1y2b05iCeF45MKzqRZhqLSWzjKiXFcku159my7XIavrTdHvy2E4Wo2bh8L5U431p9zKa1xc7y064G0w8WqjAhiwDF0R9etK8dcZMr60NP
JVMaeEd_zS4N0rCGgU4bCVWKi4mM4Q4JpPgABGgMXM2QIZ_iqF6U15F0AkzqHv-2T9A59gFGs5GdRDG8oQBoJEblq345wUcDxkXJw4yIaaL7zCRk0HbR3LjI
JHJOBliKH5fyeplw59wdA77GWEXDo5JpiJSarOCeS47mAQ0yl5yGcC8K4SkY68L4fbeJA3HAgWjH836u59okUMPsz2aquzUP0oxP1g6akauAoR0XgSwWmDtH
fm0EwONkw510FI5PI42OKDazuFmtcMgZG69mAN1vU4CCFeMzF6Xf5Zf5DjL6GJCbrHzdnzwX05FzGdTqA3nfRAOw8NGYKosJGdZguXu-Ja5mAKZFRtH7dq84
1Rpf4es2iAdEaq8QowaecXrz2iTbaRgSfC2cMYrqsaorKMYnWuDJ43mAw9el5GIV0dCO0Q6JhgOQ8ODpUyoXSA8yO7OyJu5dJQDGoLHhHDJIdSHj7pI_hvuE
TCT35BXh8dGAicxWr3mfvD0S2kGhtTNYEsBmAUmSi45DaHoTzFkpQb2VWzHme3iUf00Ecika4AAGgIOAlXXqc2ISbGzqnqCKb4rrmVLIIggxJu5F08A2LnwE
T4T_UHHwR3npHwEWbOv_W8B30BqK5BnLtV9GvS1ITIWyM_QWTLAGtLIx53ugPgw9WhEANnFES70eOBY0B9RJmMIgzS_T7dCe_7LJ7TiP3Xw59rGorJqQXSgc
-kCp80f_baFqIyE9bHqAbZqivM5C2d0FttVew0IWIy7lckVR1AgnG-4FsOCYUbjDzTVk-2-7mWtbeGQ7mlFKpLGRXPmXY-68mQ7WV4xlb8VYKGYRcLGEdLJ7
b-xeKV1NUwSyzEnJO0uz60MThi8f21u5_tqzCbRwk7qA90lwBdNdzfX7uOIfZeVAGtOfC8TX56Y7ZXaSf20jlTCrrQUmou8ex5Rn60LmSBjcFsGcVGfiga61
6A1pkXIETyqY9pdu520Bfk1Vc55nrXscsgNGEd7e4HJsxkXJkBThgZeKoZvhMezm2e93uJfJhUfGmAo9un_ExJ6NmgMcMZqAJsWaYu_3mA5mgwbMXy8sQv9L
T2WSSddlTCqUlbFWMTDv4HmA5tVDdXqAJrYYA30uGE5KFXlQeR_fEmL4RtzbSqhbP3hqZgbkyIY5po48DPpVllFtJ_zJdNqOIGW3GHGzF4ZAFzuhUnOFiuzL
25tL_q_3JIcK74R6U3pSb4B9WPQCj-PGtv52Ji5gYCV3WHGm4ERVNLlpG0gk3F57zO4K0ZAOMTK63-ba2g0CmLlpU0ebfGWxMZmSI8418VvBTJgIGecsexDc
cay1087YOMhdKW1bmDOSwvaKPZA8tOxUcdqram8u5JKUkcec1R0TiJN7TYO500IDXw6UI-4kErOVuQyUx-bjzvt2yu4G_t-tl44Pul_l5hyT_TRCXP-A_gZE
kPJ4xUWtDmU2jsRGJpU01__wW380FCWo-AFQRqUF1sz7ZmTlHtzKUo3uepfgE_eSXXUNWMVWhJa4b04SrM0xIcjwEtfhUZjwF7Wx-gFQRqUF1my4_-ene0mU
2Fwe1dPKUF1byDRqTlJMz7RqjV1szDRqGF1uyDlHMzDlH_yfodzCydZmTlH7jRUZnuEteyU3jwEtfY-3FwhzTlIlWsLulZMz7JqUF12yDRqTFHuy43mU_7Rq
rlJRqRyMRCT7rWBOyHC
}

sprite $image374 [131x110/16z] {
nPVfUYCv24NH2lUYlF_ZpYB9AUjp9khO6eVUVzLfk0Ugv8yhEBMa8BzNaUsVSeVM77y7GSbsAsULzrSYG1-DS6-D-Uq8Hc25m9l7KOXHzCdWpJMyCui0BeOB
ehmFeH9NBTD8RymY_WF2ujkok1Rlfb7V48bCOgar4cyGD40hbdfx92g36Cbl8VvNGICj55ANGBnNq0G2D8a4VYaIwW1O-swO5EyMr9eJW868cG3UBwXfRKuG
h5A8dQ15pfSL0RpdeO0quzi5XGOJkCy6n002xnKqg9be796WIYP0RY9n6A4wiqbHxH06WaNvJa7DGVTKIo36D5XbLME5Q5FGmrAINcwH06lecVoFQNoqNduk
4cRg3X1gOda00M1A-AB-0VZezG-Adse4gem9EBE5OkP4psKY7ewNVypw1wIv7PDIB9Xt28-r1B9356FV5EiSxW3eVcWKcMgYsPe394km09-vJA84xvlG9e7J
sySfX4fU4xYB102aHC3M9lGMaEtZ788raXxBd02ToMB610ABL5vD-0JuQ0SHp9ph13oMEYCnDpPxH3z3q04E8kJ-jFi9iA-6W2wesVmDxHQ2Zd8G0Vrfxdq2
OKx0KKsqJ20WX25a8oV0IOHigc89Cn9LbaXW7g_I0-Zq2N0KGOepcLI3as0H10n1FUOgT2UWW5ypE8sW19sXvaWw7HMYzJQ1AeXedUsQmN64QHzpj40ddV4s
0JhA029MW8bmxjrnF4rLB7z68j179AAcHBYl05rBd48e0JOW8a81dDS4UYHILl5kv5BdNfvGemd8_hH_8-7qEG6rreTaLRW0p0NXuPGGCB5exJCIaSxR16Oa
qe9mMzB74EWi9bMrFysgYHKuIKz90trCunFXMj87ZG3Te-P8p4ZOBHAcdv5eDu1hIHz4w0_sd5JeCnAb1dVIaNiad9Xnl0xbIGHD_Mdi_-NRZIu1YOrq1as9
z3i0Ft-c17L0P4ZL8QWL4wiz4koHQEkbFefW5amK7S9ZxP40w0WMyZpZAbmlzL64Q2H4OvrlApbQm8W4hqWap12SFrEXaY0LeTGyfg4cbkOqhCY81Bqjb_eS
GW4nX2XQ1FePYM8JeXi19vSP74D8HWAkOntKO69qlpud20mZChdEO2BmrH0e2G3UdUicYiNQdDVdH1UKCTUudgdffxuMWW824q4ZtMSaj8m0zZqzf_7bcMha
IuF886QvQHNBR3qIjSv8p9VP2H4dmdebFBmcugtOhuAeSKO2ClywFoU8zKnT2yB3Ao9UDIwpQChUfm68fjASzFj8J8JrIcXyMiJxufWzOzOu1AqMizKb4ikP
yW7GKMfuKaIi2FrfgbLGPYHA5PZVlSooBJEO_oA8_8o83mZmtdUBa8eP2O6epqZa6hpD5YnNWW1fwHaHLuIMnxS2IQavZKWOHFE81D2b_E9ASEHPuyz5N14y
YnIEHY0bJJwcOIdT8f4vHUm0Am90bF0Z4HyHKlTaHgAgeD8xH5R1FEDjkTGh0jP8x4Ny6a54su2m0AbZPrC5OKPYdS6Aq2CHzoBk46fpz_j8Z3CkMchx4c0Y
p9g2xaJSTs4s0ZbQ7f78bXBqNn7R2h0Gp4ZiHSI-2pu4rNn58YTzE5EjXvDOYvRs8kuHgDv8EcwH8DaHrXRqqH1BVIre8R4fhWYGDBO4ABNCI5IsXqkzJcAD
n7uEQx6i29zRGYq7osCQovcQIthjmZU29jiozExfXI11vvR89cQSPseIN7eGZ_NrpjxdWJLSNUWCKr27M2ZkSn3BabuGTf48bJi8P7r0c6Syb9AkCpMNz3S8
oyxUx8OL77n0cDEm8cClj7L9hmZxI6JitNX0G1UqQUnTM7VarqRWkvqTofz0h0Xf23eCM6RmY71AKFYAy2de5B5zUQQEHM9MNX6ce8ztQkw5RIFavv6Wnecm
7B37GxdlmdeqLa7t8_GLeSTn3x0vdJ-8157uBK9VqlXP6DVAjcFW0yBQWYt0_itwJmHT4JOps2scfo81S46u07mFyCqCVYOeYwm8hMr2iFcmU5BGYV2aYFjf
WFkMJeHNHPGN1CqJOHE2ZOYxIEm5VLN40uAsbqGy8-WJ8XwEn34HdztP1qGy48cDY6SgRAPnGCG3WXuGyS3EFY3YSplxl8XxGS-BU3uIUn7F2tfUnFtEFY7Y
-KZiHJmkw0aHpqTYB-BvQHmGyO2W1qGy48cDY6yGT2FYUo91Y_AhbUrf4Vy6
}

