sprite $image280 [329x329/16z] {
xD010G0G000W0FmVx0RKXCBp00000000000000000000000000000020l6uNVuiKALAaI94YHxh5Pky-b1JPOIWCGzkIpf7jdlT_ssirONh3x3HmDqoLVhAB
Ibz9i7djtuQqqrT94_Ab4Z8XpqjvkOISbUPFHSQDJlTMJwU4h0tcipQB-rkxfpyx1EXG1SJCDI4dfDTALoUq0I3Cd70dmud628G7CmpMjaXt600hk4BcH0QR
azOOZ-0LacPypwVZzZQF6irkxdQ1J4X_DiPjbf1HrUMbIYcIaBCgrLwhrWqo8OMlfTz39YIsEtiICY7z6ca05FI7-Xuo8U6c59Zn9SY4L3KrEXI-nOqKXiXu
538XxRhLk4AY2k4GLHKpEmgPa1wEqUrXUyrRdq8c972xploHzf09IHMeGjL4LEYthFmqtQRJG2SCUyYSoAfmCuWQz1rIJZzD68PIpL5EbNV8X2HK3MQcEqZo
rv1MnL6Bx20JKZIkAZ30U4-NdwQXJBFGL93_BsJ-N3iXpykBVG-Pa6MxApkZidkrxxpl2fcGDpoLkfJpF9WdjPOwORNMPQQwd6-2PVPpo8GiAjk6rWro2SXo
EiM4YWHaWTL5JIL0Iv6F87CYfSJ0IIrXjq7EfpLUN2OoxelKCXy_diY4l7qqbZ8VBcXB52-kn_lAx2UG2Vdnjybog7A5JCW0UxxpSeTCICFJsGuo8RrzME_j
b_40P4BszMsszjSW4t9iYgEFqJuCdq8cv9YCpSUwtYNTdu1CoBU0H1l3smRfKVFWzEEhdP0z83i1cgztnxZEZazaGiPcZqOjfGQaVzzno8GSbEsdBdphto76
xU1g9-JQj2nHG3RVz_wzuvz39YHLf8gQSSM4UsuY4xAluQHipLltVO_zW3mXH-kzqztP0-zxnyEhdP0ak9YAW7td-21aGfAckbGHPLkRVo3v6MH23crGbUc8
zZP6UsuY4xAx3Xe9CVQtDKOohj53a0bPi3QwEuphs_hMs-nno8J4MLG9GYVaEYdtZCS_8nDoYT_z4bYjOFnAq4gwFmoPaAnB0GGmaB0-6apLw0z19gIZ5Wu7
d06fi9dEp8z39YG1BJLE6P2k6eoN2mz39gG3b29iQsy1sOgOmQ4XYGSWSo894UDOHtFoCf60pTJeHo4JifDQ5NqTWuqpmsOuKv378NCY8TNQc3LtUXX6mKax
3faJsIXL-mMIf04R8ys8mv09sTi5ia_AJh_mcG4m40O_-bF4N6tNKiG2SZZSL64p1gGz09cGD2bL0x8tWvQAaAHjaFOnP49EidKTkztMgl3fs9kZLa7a01rx
oFWGtK4cv7YBTf2zmJ2T9YbCIxr3DgYYtPhw_LUG2TcQk_Tj85cb5CmuysQgjeFyOI8JSfsGkzpRX9oFr2gAcOSZ0z9ta3zCP4AkFqAE-K2hrG2mqRsxgIeF
hdP2-dMrHtSdQbLouWMjGrNDZqCcPB3rjP6inKYEUJfXOQh6TyZsCMH2zh0CfukaAfszUn_hX8Gf_078X7IVJ7qqmBPXx6EyDT9c_6Yr4p8aHuysoBYdXsqV
dPn7ix6-3ITKzv3Z0yY4t2X3qdqUZJxcRMhErlccJfWfZanaGdRl7f0j3YVYfNbEXuAcu278X6n-6SdhwPW7C1KHZM07lxKJSdZRsawRYyfCBvcf7Ph8X8oc
94btQgbohXAfcjeM_LTVDld3dzZdhGcfjIoNL4hHImQBu0upp89w1vcGDbELIqfQcIsNqAHiVB2BdhVcKhRgR0UPaA9NnXf9JEFvsbAbBFCmX5MDxawjvTuU
CY7V4Iza6-FfLZoz5xQpdq8cPBrMeebqtaDEk3raIEugEyY4F3tVEI4JyiSICY4JCY4JCY4JCY4JCY4JCY4JSgdrjFqpfdMfmVeiP49AEPLIQf4Ya_99o8GC
oZ2vzC9g9-JpBU-G2VbQDyY4VB7o_q0cv3CJcVyDY_E7S8DCI1CeLFbfPd3IWBWQwNl8X7HPRD4YJlzrN9P2KbMgg2ZOV7Q7J4WQ5C3daBN8VhlTTv09kTIN
afAGKN6-caj2_kKICY7_fH8o8QbV9VoZa5-pX4p8_x-4JCY4JCY4JCY4JCY4JCY4v5Vltu1SxEkt_0lpQ6OgNpYrMVthZc9c8lhtioTJaUtXxwxtMSDH-PKp
aR--tekPwTtHz1PuptPd6bt_4O7_oB4EPKbX63RlMBV__-1h1DPIifahEBoYQJWsJLYA1rXkY0CfUHHQEYV21tTIsM7vq8z33vS6npk4DtblDzkZpNXqQT3d
wwcdumYNawi69vR_XCXn-iKg7aVepgJSQeyMdm1ibEljKRmrqOaKcJcb-hfnnkr0H4GEV1XugiA04cw8ewcjoVlRJVOeVXfsWoMt4l4SM5AwQAh3G2B2Sk2K
-VE0R-gv2Xuv_AOvQ8Djng4RlEkDFsZ8FsnS3YA1Lben17o31f3tKXuV-_Jut1jIQuL3fs5_XfmmYAYIczTIYhetu8fO-Fg2sZUbqXoqnXvLH9EiyoQgi7qh
l-TexrI34_kSmpKjfLf4XahY62a504QvhUBHpFJOhZk9q2eNKJYkjeOWPeWDe0EJXWDP3BuC0enIbjbZKmvvjqQ3ecHTG6z1PoZPFfrCnTDpyKO-gpL1sEev
w95vT9O7hqQWYkRfcFVhD1i3TBMGOiHIezpjKHfX24KuSSZ-YG8B5ADo-RHtbTGHi_OKA6P16Sr1XVQORZc3eSQ9YQ78ENOg7nBvf9sgxKpRuADP3uzib5fl
ZqhY8Co4E8_zAe1WO6SYKs55UPRtMx4zzZiYBCXu9w9jg1OxJtnxvmgJ3i3aLlQJGZkHgKTFchzSAlrJEsl99W2kw056ANNsAEa9ubC2ZVAjuYU5Y8WvmZuO
z4yXDNFGmqpbYw5Y3f9I7islG1cJSkbF2gc3nYKmgG0PvGNsM8Uu25h6f6qVmHxzmfssJjwrzbWlxFl5JNDGbJtM2_j-SVCSL6-FwuNDa4ec7-zvUhIu52Qo
n2ZljqU6NmmjPV97EtPj024K1G3i18VzrqKht1easU3Bq-XxE3rokW_w3GPJZYNAOBIP8ZuGtc6ynrikilFRbHudiJDHfjaIuiz6nIAoUrwaYtIHsIAIpn80
00000000000000000000000000000000g
}

sprite $image280 [165x165/16z] {
xC413G000C8W-wUsnmSi0m000000EBFrWGKh3WDHTC2of2h9iF_TZetxvvprEZVf7dAJFrlx3SQ3mJzPu7SWGO1_9ApelmT9kls1d4-_QqrI_li3oHz37j-g
0F9m1uWP2N25ruiEDtSlW8I_PGLzCoE8Y0JXhZWAh4dxSlgy2Y15xQkf541sS0OwFnzw5QIR-L82nAecqkSB2qkOMJsaFsqO_5sO4IY2x6QgwWGexutcy0xf
HP0xS6RojWx2QLu2AKtUFDkolLMstIa5aErevzdR_3ndJTQFiyrVxTnZL43AELtIrdlRo6ULJkTvFDL07kTypXRgzR6_xSyIoCFyNUOVrseWaV6sSLyZu_sg
8D-2EExCYUJRWkMGST_X5idOmbazPDxivydawiMiXnpMrIAuYvB8o02mTBEY1mw3rgLZL4Ok6zp67SjO5QdDO1Cv654MsRgPkGVDd3MHS64IK3LJHJ5alf3M
UGLWwcPM5CdkOopaaxCcKYmdydKlPDMGMmcH68dU5n8lP1P1vdsFnqFFCQdT7Q0YPkEIKiWPCyD5bv5gnP1NFiHW3a8KmQGgYo7VhianTSxC0RDwoDUwl38P
EQuxN54DcRcKN5_7o23TRICB7TqvY_cu1bJxJDMGcTSjDP0naYGYL4JEBlikmy7_sJKFvSPX68YUHM9tWIl__xadc9Gvdd4l4wQyqM15GUKbHdf8-Ym_unZC
QgqekwJMKiqCaYtBBByBghkIv2yi-f6jirkIIIIldFuZUOeVoH_9tJudbonbtTOojUIokyGoYUH5fdXF6dYPIVuY1dZ4CHKXaZx9tnR1Km1ZzuCba-KafOpz
NnyZ6VF_oqrAijhBgNofvBluof8_aZ-IRqQxvnr1l1VoMSk5W2Gcqc5lLEce9VKoQc-TwzEeyfHZ5UWU8Wd5YXE0762hT74D3m-1vBxAcHqdinFk8YddYcj_
PRk6Anuog3xXQ3IwYnILmOp4CtB1hDux6NqHoZZL6VsEEo3i7Xz7InrYHOx4XH5i8J4NBIGo5nn1iKNRYBPjmvwM9YwFZgF9kvMEjE3UZ_RWYEpr61Te2tQh
Z10QxZIgFZIE1W_77eLlUj5jdRr1ZiCC9uwM_I8UlQM-kQ7H1jCU6KUCkt0bGotLalAMRIQ6UKy_I0t78QSGDXHZCEyQHxhhu9TmUzeX9PnE7kKMxh3ZouKE
vJ2ot3kEqOSgGaWuNlpKx-vCUX2yH5x6HE4zGwCPzmrc9Ieb9biaPAyaTO0l0tRxIswqEwZWLQnQhTKiQzyPEOwP6SJbnd6y1_XLGdOxLBbb7AlTW_m6ME-n
j2kEXNOV2hy5sCrS7KoZLRk3QheDtdLJibmQHyo1LC-EupoS6ymIFXVB2Kdy-piL_-pahsPyAgByRmyE200081Y0wPzQ3FYsMWy000000806
}

