sprite $image189 [243x176/16z] {
vDY7jOGm34HH95jX-Y_uvwZDmOOpl08sSf7miaxYsPOz9OQtGfVTr1AVcIoxI0C_PL_u4yU_-4bte1Qo0yGr4sB49NBIOZXJD4B4YVEva24ENCw4Tp3napPS
NIZZOA8dhO5RCs52p4-wuyv2EH3JazR0Ond1TdbhsGYsIrxIBL0Y9osEPzO9jaisqdKmqPFMm9XC211JxA26eKNREc9wqXKnFMbnpAflShla9zq2StFTrZND
JzgmIjbtWBYMIZUOBkUoDc9-qfOeaPDkYMqKkWvYdpYQetabFHznwE1xTpqWqPny-Djnz0t5C3uxlWracuIuZaVrULD9SnPfzREpiSLGn4NN3D9Ybvxa5EFI
2y3GPsoNbP1ZPFvAgvaknc_2GBm2RB0atlznUxhHaeowuot_VDpxXpIZWtpNsAzU_fRnhikjDbr_6R3wj9h_fFsIblDjffqEYFSoUry5AmDPt7uHunZBDTtY
YyU-IXoVPJwlyevvjEs52SUul2PrbmrLEg8c9qhko6qiwVqZOlqkOzFLEKlVra67KQbDRyZ3iAItZeZ73-98-6sZHuHBlixl1tFRFLQsvFHNOfyQbMJRqkI0
zK_T6rCPszuHSSYgOmV4OIzx5Zt72tDblgFN3IB69oWQnCV6nScPCvj0ENykwRUJqLXUEAObCMvc-ZcosP4oNyiJVSEc2CiGktMBSjntzYPgqqVIpzfSJaDs
R8eA0iPavg7mRz5t-x_jrYKudER2zlQZq8M93FBf6ez_8mvJazBvmdIyCAlWGSq7Fy2TGegOKx9OOjOzY4Ubg_HeQuxPl38vLqBDfAJhU5Gk7NUWXtja5dEK
4O-ry_2E2v8DmhGfIUS9YD4K1rdCDOWvmKHDMPahR8tK11WOy-6yYA595SCA7ul2gHCTIN_XYitP3f3PbAHnTydwzQbGuILhJgIppbf3jGsowNXy0Nha8kRV
Dt1Udn7yjK_IEBbMHAJKc8RrI0hIXSEYGeWPP18jOjniPW_ZaoZkzbEsnrT5Eh0ZcS1wf0Kyp4YQTLEeMKcATQBmonNLinQjCrPjXQUiw9SmaduyvArdYnzM
cDV5DHmGvB3wAfh8U0Bv0K43EKqZooFaQk60iC7G4vlmyd2meGCY9Qsw6paUXZ8S2VALr9s6sTgdo6hFHhmrdHBH9jKQUtCaHI4-97CL_izy6WcTdsqUe8vC
MFsKrtmtbC0LgoDFB7u-czFi2VH9i8N_A_Qf6TvJtHNLy8wxd8RRmCfFuVCBsHX9vpz0yJ1d9xgML7U9JBNux2PXxuyIw50Es6SWyu5E6eEQx2FBpMklEn8z
K81yJhzkwYjfu3Gv2JQd0vc7regBPpApkyfVl7FEwQQuKGzVyNbJzwHBRuOdEXeua7bexSamL_3Zqu9t-Rd8z_McrcoXTYasHcL4390vIQjaCpiENV022upp
MQaT3rZLSUKubH0nG2O3RIrTpU19o1IEt7aVeMPut1Orl8vIfNCwa7belV3FDLsCxNnNsgaICweGkyLc1310fg6z9hFyY7faHfGvnd3LOrbNCuMh4Y86o3Ip
QQRQVlF-_Qb4bmuS7aNefYxkk70T_f_TPOxCG_k13TVc6VM8QD-OHOwQtzJLF56u6P7J29c7DXDyjU4pvmK1GkUMKyzieTQTp6cCp1KilxBLNF1oteKB5QOs
d2VDbIXC69aFjFgPCEkZ5lr9owYAhKlCAH5ZP1xQlBq0d-EJSVlpVmpiXu256X0nWKn2nqt-xS_wwN_e4TU74CVrN-en5OkOHEObhMxbD_doPnfPScJXaMyF
Bt_TzXaXukV8Pf2vcmD_vlR-VA72khP_gCVq9ATvP1uwhx-yTwMjDa-j6J2Fp4DRpijx5pP-dbf1Jkz3jZ-gDmziLs4e1XAQmT7-j_jxJJLldWwMTg0J3tTo
3RNkB6LuaxAp_2aCAhVf67XsWJVO6o26bNdfnVhHwErWufLvwTl5GBDgj-ukGMKJqXDuPnH032hJ7xeCJIa0Ob3PKdfigpm1Y45bH-bbQCmA80QL0TBWsTMW
sk1CyyhWYlPD5bwOL-Qbot0W6pxJl38lFHwfF87112hJpkW3umBET5CqRgmqVdRTPZGNtiVlpcCe3JvcMG34RrFdNw-wLTIvycTNksgZml-yrd0fjXzw70vd
Tftf_nbp8RqjQ_cJhItbXLs2tEl1N2sbhn_WpNAc7pvJ74XN7S_LSAPlLkXcf7aunEEhpqbwAyq7a-hqxd7PLsaEyTBmQHZhNFiwq-L6_WAGndRPcAc7qyqd
SJqaktnAyt2xF9RB2gTq0iIt6Mr8-y-qRkqo06c3NVQ3jDyk0v3cVn5Xh9iYFyG1I5UhNRPdWKXtE9ZiujrU6EJMBWEGXdPv0t42qXr0RDWK1K1iGTe_c0AG
hYVOvRaEUZNOPMT86-pIdajXfJyDOiDWSYz_QsU3oRlyDGmcT_WLhU42WiM__DK9TdcoWye4SSTJMhr1xDyKoNK1uSzOG6Lw0P65jBXTfY4jR9TnI0lQPI3I
GeCf4caTWXYSwNx-Lgetk_HlYjIbNV9D4Q-i6uYJaHQmor2a1Umo56a1kmn5Mc0mXI8jO9UXI2jjCF5DaS05H2ZIIeEOBt-LPfTy-Ii0SIZI0dRPVyQzeJAm
onIabMQNV5EaDBlacoA1bwT37LHf4FFbhy1WYifVf0NiCjH11IuWGf4MiClGlvLAWvXlYWGk84AHFcqmVGK
}

sprite $image189 [122x88/16z] {
n9RPjkGW24LBJLGEvly_juUO6rcdR6fui7cvGwMoXOtYu_j8jOJ7VuYG1P1zFNWNY8YWfhNShK9w02MkuyO2o1sG7DO95h6nIFVEt4MwKoKkwLuWcABhNYTu
aUxDuPBk1O9dkXS8Ng0xJ7QInzuM2Fv6z_U25-cEcGKlq3qLl4ZtneLUfBll903u0WhWMzsX2qP9c-2BIgUAxtHtmP2zdzSVHWxc5TiNEmboYOgVWUDuYwFR
EIfHhqgblenteZzseK97isv_5bfmRYg2-awZzwUqvKUFWidkTWLRS6qGGGxkUBu18KC4hTgiXsvNCDkgxVvUB3wvnEu68aseGqYtCmjnhR4qiufGFV1FaUA9
lhBUC3dClSiEVhxOJCTi2X5WHWL4eBj9jErMDUbsPY4wB2X6-lifl4nq0_dKUsIJg7PA0XtcSy6SSbPA7xkLOikuSQ8e_NT-St8lExWMBw3qztkTuqYloIGQ
HwBeIU-OpMwUXTHVyVn_kD8VQSHwIjltNlauJnI9oprqyonapHk_QxlILq49rs0Hj6WGbwPHeFYFsPscjqh49xBW_lUkLoMk_sjt4sHKQ1_a89D0IJguBfdh
1pDCi3sHCvCvq7IAjeXgwfU7qRvves8qltcw33Tn1jPsgCxOThcmxHhlIw7MqOCeVrSAKFgZS1Hent6IcKs95fC6CbhJdjmeYxQcMSpUtwbOJzoRhC1KTEnx
T9ZMGs7tNL_G2TTXcTEt0JqEI-QqKKpIqc_UbJ-_5pSYftCrDdrbmKHczfLe4FnL6ZFQ0RxnK3Lx8RMat4RL7W0LcidCXXsmsjq-dwvSpkxSphUYn9sGIRUM
JYxWIvZnEMrUcC6mAGjcCgVTvqxCQ0ozsij6nVIaAEcH6aWmaUVi1YuojzSLQVhGULY02itaEHk4vIqtea2ceI2kJ-wwAQYzAA8uGOAPpE6Y0vDv-lCETiWE
ssaljyb8i4FssTnU71kSGdzCLi1lBsuolz0SsbossrxSP3wN8rL2-snCsci-3E5mst58-gle3RRNNlFZs-NgVYrNszkwUnFZEJueTCjtuK9vMxVpqBk5hj7M
wYFTVi3d8f6cztNxyRjN-y1H60XWABfzARx_TUaT9b_oL_018CcJF9M1NuIv8GmyEaxy8cxvePTV4xiLo-AJby05TmjC-IoukIeVWOVS-DeUs7FpXnurhkUU
_jyC1ZV9pS0B0AwvUIo4bDm0l0PWmHq1xBW3Oo54SAUiIi-TiYezTru3OrLwxWXWnnq1xBWZW1rtOB8p7tVAiT1pfnmBFNSk_vltt1owS4S0E-uKm9PxSVnd
CHOwRZ4MEkurJ7Rcu_vNLRa5
}

