sprite $image337 [173x249/16z] {
rDK9ZkGm34FHx75a-VxNdUgLq2n4Ie2cs3h1W_F1JF__vgEjqm-vxNhSkVm4wjgkZpjcTUfyNBXTsxfVuTegNW1EETtbZ4wagnrhl4rlhiYrLJLMvHPG0Bzz
bg1YhkYrJI1MNa2SCRcvukcAnnflboyWpfZ2N0cdkv02XDBbSoKtOuWrV-SgDbVyZaLihlZjite1CLsvkUBfoiqLdp6vkUBfQiSQhwroSyN_m7LpfPpkLgd4
ZCdD5KzNBbQUhjHSyRCkDLVSwaE-0537q9shMC0OQMo8jVww3s1Lvme502iVAx3YS-K3f_XlZS-QnIulYHMdFLTfxCjYnOdFLJpnkOedFbVnvERAB533QSzL
FDUUgtXTVAuYLdok8bPyhY9MQAxIsAq9KJbsLIg0OvT3h01WzMC5Ldok8bPuhZXsremLMF6vYbZHkU9OwG8YTfxDJ9aAx7gspNetKoq0s8yDiFuuqwG2krzl
1wvU0S1k-FXcRrgJemAxupN1bIi0M73HWjop0jkDS3Mem8AB5fGAY5ZIWWGLMC8LAI1YArlWr3msDsFr1KHiLGlMnoZ05d0HQm4sdsvz0H7BqrMW0fjlWSTQ
ZoL_uCnSrMCZBwPRNm37vbkeBm3OkVKyjtwk8hQP6TKQQw6-W8ZjdNFv7xYU6h7Gfbj0hENO19V4Me_bNFu7HW7rM72owSO2wh7v5b10_Hcmzrk8N4C1nNTz
OjspwTPHlRL_OCVmJ0jr1VYrJWV1sjFSkbZxFat_nle3OVPC2zRhiBvE_yBYmUnskcy1U1rs8LWyryqMx8tv0coAw-DLM9HmkuNnQcmtogt7-XDOta8zrlP-
4uiM2BSIwySC7PykdcuzrjlRMyxVJqkn95rewx3smBtTUHFBqot6RjF7pNuNozEjmiBsTcS2IzAjnIwUm98MIh5JIs192xNOnHDOqa8LTld5hdteHWx3G01T
kOla_F_dNf49ZEnimQrmDWqulUU1uQX5BEqNs3Spy6fjmkeoJSkcHPENzWliszO5JAK5g-DAKsBdcQNz4lkyTM6I6x0s9U_HmOYryi7U6h1FMhSy64ojOMxr
1o4MK_b8Ri4-du4Dts8pir-8nBAq3LWMLvft2ZhkxfLNM2-jD639RSVQd2gerv5ONVku0KjkCzPw9mxPfFk1PMdRiIhIYbs1NJO0onEiUckqOTjtjpONBDVO
uh0QQwMZavoBjJaD1SlvNzCg8fQbFHMRku9vWbssM1jAQRiJiKMGYQtQG8cjFleu1qk0xR2BvskBjU4yB5aTjbYZiCP2JiQE7liAwwYaFx3MlyBcGx25k6on
ni1liSZRtIEnSWJMF4arraRMU8UrdZD70_QB3IF_uAYnkiOextRUB6sQ3JWAQxRBrr1XTKbF3c16iBIZ0eTXTHnt-PhhjO47o9vZ8G8SXhKvUJioNr9XQNsE
1Gx3MgQE-R8TDYs60DY90m_prMEB7HJuH-poFx2pSwn-VzfW-sm8WELycRJELww7qDc025YA7bBdo_WfPc-3JSlnM3RjvFRYmoVi83W5AzwOnlV6zzY1S-kX
MCOeAVErlCUA0ITXuUSOcU_eUonm7ZRpi6NDLqADJQ6msh5fpLSnDLRZODa72i_N51cxhDW5dgyS6Ql9czPtuHOOMuWU-yvNCL6nx0E5UeN3Oja7CxBtRbGi
LO_1Ihvq--7U0c6vg4qsb9V4SjyQ1Sl5Z7IS4hXl3ONbOiOtjjn9YY4U5bFzhovgWOZOxDBTkYKcbXlPFZuM8qykmsFP1_a2M4kErGjWCV0YINpiibephe3L
nBarF1RzOpJW8jWim6Mmm6MmD_R6tbYz6FR6tjWRUsDD-ijWTNeymcDvFNYFDRE8MFFhmNkiIZWihmS_kT0heR3rzM1zffKGM3OhiNijkG6myhjuyr2D9OY1
uEMWqVl_ttsCQOU1tK9teZavoRdmDQNHchs8Kx0xk1NOCTAig-DX7pOJiW2mfh3E103iluGi0AnFLnI3U0Pa0M0zkbfhzru4jP-1JOMLODUygcLOhwuOTish
Me9rwmfjiEPLBS2wmyesWEYwOJLRox0P4H1TDwnqLOCL64JN2JiKrXBiRbwL1O0rw0fWKRLh5W3Me2k0XRogzS26mWgrjzOef9knSC0cw0ez6vm5jNoJS5zN
THjKelk5seRLpLVLWhoYnYJazEYAOUlkKgjFPLTN2CUm2nYsiszd5dHLFCWKSIDb0wUkociDZzsK3RowOjXHoQlKbMBswQg-rd0h8QTHLmnRyQjQja5VLs-l
DMEZdHNAh55Nd5dAw_hH6BA1uNJLNslMTc8ArgAh_beJQj46l0osAdYj6Nkj7e8qwsgju_sjey5y6o_P8AMhNfqVRxXBdnXfq1NN9NRSHUqy70ZMe2lAmcqB
5ziOie55LrodpUX2BEe7cQphgXxTvoihRfRM6kdAKLU8BgmrRLtvepjV2TQeAuvkKMCr6yJbuArBCRenjDRW_uNSTIn45spGq9Lj0ayRf9ZXGgkzD84v2mbh
JLbN_kW6hJLrNVar9bouoE7K5KzWr5Z81WrT-ISmh3LkNTKFZx3MT7JbZ-xlPfa6NHaciDQQlgxyqVqP3WPT6GwFoq6c5LR_10xPe7_bmX_TIIdOqLi6_HDO
3t-CR8VLhp71dgwFTWByqHMiuOzgq9W1rZQ11PjzM7zq9wpXB6ZJM1hawelkHqu2_m4
}

sprite $image337 [87x125/16z] {
xTY93jms30HGMhua7lx_psr4A1X4MABMIhrBt6toG8x7NY3qxQJxJhHwjhCmbtDRgnw5ou_XSYn4KsOkFinvNtN_rT06NqkIE8kZc1KHxnch0ivp4QUxeRtB
Tve8jRz_HSH7W2BYLQ5YKBRnKiM3YATA5IVnFk8Z0tq17nEbceeOfHg3hpHJgXYMYLA58sghGiMmceNiTdvxlzMPA5Lmly_o-qDskoRGa9q85REmL8RHfQ62
NLMgW9rvKzK2TjNzOETB5REBGWKxMQgOJVko-y5kPxr5U0aAzXR_cH3cgLBrR75mS66W4Pl5GS2JzuCDu85IHQo37l7a_JsBY8VlZzaWYN4KJP0O7WyLlSK4
4G-4YX0OPXVn-FrWMHXma0Jk7s0bWfbn_pZhBiT9iDhmIFLKuoJ6q2m6reI396JeVjwfWAt2nuXPT83Lvo9YiDLrk7VLXbYxExQ3nrdLolRRjeVFWCTOte-F
ss9XXmVPYwgdpmUsIsA4LVenHy3w88bNhBPVRo87GrOOPGCReohEqaPqXcmViQau6w9NsdQjxBaJIH127_7llGxPZx-VoXQYCs81krl9c2qx-Ho-hIKY3Lcu
SRP-lzrLB0VHNjdZoKHtZbbCp3wQxQZdFzosFKmJfMkEpTlvd4J5Z8akpzRNtwROGfGhcyqoKN4MxVsERL-KnkwKr9nLkoVPerfdtVDosxDrdIxzXXLt4nrM
sViaEgsnTTr3p8POVFxCXEXsbbnjR7llthAuFHDjQcgb9kZibWqiPeIrobBn9xQfiwTQnF9xrX-9Fx6zubwjzZzs-PurVrDDa-DUiCOMiszOX4jYJ5J0OhxU
LgY-NfasMShQJdG-5oLRoVhhcNxOvn8MmqJ4gNBE5hCbh2KY_wRMWXrYQrWlwqQRuhTybaKAUAEMiPg8w3PTo_g38bw-hHLAnTQpcjMMif2NifY_afN_sMSb
YwgKz5EOPe7oGIHjc1TjgnSHWIs5Lx1v8mAhAWntbCNzkwE_XW0Ox0Wg9r7FEWbuV5kzD-fPTH8HnsnSAg1WAzPW7c9HAkfPa81VizfAzOa5YOYTVLcgW5N0
MDiwDWXr9ufO0GbTHS06g23K80H6n8oDNvKg304arfOMGhXgHgcY4Bg6TI54Rsh8HWrh_seNede6OX02rcQDGsYXXgpYKzCtJ1NR1czgDEaMTHQxeWu88IfL
F7jnjzir3a4lUZSdDxYhWtqA8ITwEzlbIO14246fNaxApdh4q142FlzZWuYHX1hOu4qTY1XFZKM2KetCTikliAX4fHgC-AUB4F3vdvW34ViF74erELusR1oK
QY9YCTKNfHejcnbdb6h57BLi-fHr8jxd-5CzLRRoVG5-0m
}

