sprite $image87 [118x82/16z] {
lPPjZkCu34IBfFYbxFtFknbRQSlcHC0aSB__meDPBahu53OZ_3BK_4d3hoA-4IxuDTZ2NnZZLo3r4qgud-PNudQjL6T_qDs15ca-7ftk3hH-wB1oe_i2hSxD
Iit3surjgTO7xsc7yMt3hTwygKNDtv8zVARHNMrP8pS5kYQCxmfqZT9TWQvfNmHw7gx92Z-H-ccWwcSCAtmYyh_Fh5I7QmI8_Gq6wDIcnsEpqhTj6T-gFNkb
pTPuEliVAvktBziohEBcLynbilPjDV-diAr5ybLRXhM5Lw9DrjYrnod-iYsqjXwnzbmioMLRrbOLPXQjrerOBCdLOs5jDJx2ADRbabm7khOI06dRv7HXNIr9
QlA-BKfinIeWj8Wm0gXQm_ZIzXglg9dotzkYl4TziMwoOODUhIPbivLupLJLh6buHUSzDQoZj_7JuBXQHuPYx-FDSDsyvfNCDYS-h0o0U0C0sSKQtUZTKisX
pSmmtHZUEF1yfD3FkXfMmWaTrXXuzAx3gzTNbWph7znKJTKsRviGKUMV9b-jr9xGReLCfzG4jOhvU3ojf3Ai6Mvgmujt42vMZYSyh9LplBbjIX6FCCv1k0ul
OS6x2I_Wuo9wFMBp8FOnQxls6GCf4vOdD5lh8VBy-TGUhtXpSCHhgZ7X_3hUQJ5XyfWHx6XFtuaSpZ_nvapufZMFV65y7BzQGKymh947FgGolz6FU8VLHECO
yuQTjcVRZY-jLjO4Ut76vXnM1iZdU6rlKTi3ujYFhoOCcnSQ0MGztpZxi98nXdPkRzZfE05I_wQhDOBtwVY57CvNh0sUp5bQv3tRTlom-hlcs1ITIVmjqE7i
Ybt3S8DTMcIg6hs7NwmCEcAbQdNFnN0VJi3kS8APbHPjt-jNQvw9QlNtpc1WMD62OPbnyPgPcbsjSSRTrzOvq3PjVw4CHZYnPTPuxMojwCeQ8z3-w0PCLeUa
GmKCpQpnsifQldKLw6nD0mk4oGsUR-FbVxR6D5p1WUmMPw09gB5a376v0qTV2w7LMjjofaLcP9gcaZ4e1EoPfjSn6ut5K620R17emmXNI3TjPf2cYO85rXl4
Bzx6U8-jsrBPlYrYZrSDsXkbWj3YV0TQCr-mRWig4gzunQ4PP0fLSCmjKZMBxFbN5e4MIhoHoP8PeR3kQEbPxi32iYrho4Qy1dDD1MamXKXjxy6wBI6er7Xt
RmD15K9FGX2BvRniImbq7QynXy92e2aK6U-Mv3-qPOdcJc_GdYoRTIAiU5TjgQpZDKAB1XSArrZVWRKjWWMhUAE122OK3DAo98ktj6N1gaKk81TARqOjwnru
U4jRFe8qTw-dK6YBSHUvpV6gHMrBC3w7N-qLSe0OcgsbmQPulJyMRVaCsUFr5jIYGHLWnH5mv5DI7WlVyrh-2ZTeWpQ27UNjctKEbF45vGviHD26I85bpjOe
RVc2qYA36ZmL5atZn_fOjEKhPBJ80gqRh07aB-kYBTyoMfHjovR9nv9Shh_l8Jlk8XE8asxMDu-56-ArHet0HwvTSHV7adI7Xr0CQmdqjdZ9L5zMGU6sU26l
lk8swf9KNrZlYpVljzOb6Rzi7IsgrlkHM5XlZZVxKul2tItgPHVU3titVCh_
}

