sprite $image269 [176x128/16z] {
r9U7TgOw30Pb6oohyFwlUmDRVSLPqF-baDcQoYHdR2dqGTH2tuWoL9c-3QmxijAtODLVIAF7iuZ-nNXunbLKP_ZPnopmu8ox1XwSyIeQU6x6JVIVyAF3VNR6
XJNmu8ox1XwSyIAQW9yq7mP796Jyd6EsKAG_A6FMcKwHiJqbu_LEd8TlX1znpEJ25yeOFsQH2z-GyLVFXvBmnJF6vqDB-E8PuslOal35CyRNi3NXYsUChs6S
yFs4Z5ala8W5tmX_sHgsHO8lc36-XiL75zLn_1tuf8nhmdR73b_J090nUimYij1FN8MeRAOP-1EEMVHTEX5fzCKpnkT3X6rZ8XhH5yyOFsOHS-z4r5_nnJEk
G_FilklacuFXDIplstxwZg5vP0NdGzwt7hws43NMFDAWSFE-f98uhtZ6JLGXNv6VIRdhQt1kFe2-GtxORcdTVCQi4C8YtEGDtzmqHpxZLN4Q4NNtT0lvZ1TH
c9KEAckEVCPL58Phuek7CYv3OMH9J1miuwuulUGkndp6uBMkVoCrzsqOBsPyNXgTe1EzJXlHcbkQUldnM3hZ9ECGRjPtjB_lFowvAtBK8_0htvXnOTNRlZnn
v5hbE6St1gRmn7e4Vk4RCkwg2Tz24GddBDAEvz492LzL9fQKhmUsRTDArtHJFVlWZSumFKN6C9M4hvp0T8lg9YTumjTSXfdTzxL24UwLhcbgYHvSJt3VVNVa
hcy_16N2J2-DozWDwl4_cV2RlkB-nzTKRlcwMoKgwXCshGrdT3TzmoiHDVE9MxvYFlb6utDVDU-xy0dSYCvPpFK7jWjN2yy9R265oVSq2jy2hgfc8eT0O9mQ
LtMRH_RmyA10I27wciczJsDkjrUfCZQRTunkfjU-5b88lZ6AF2QpSNTN4FVPTqO3WF5YRh1jz9qH1V6VnbKsLmXnl_R5ZMqtBhpXATpmnJCUhJQLrcfbt3Rw
deB-H3lyE6rG2WbV88g5TiGB4J6GLC8NY48g7OXNnDSzuGiOSo5QhUs-BVY2AKHVF0fciSqFt_L5Np5F-E8PcshTVVkBlkv9NppZmvU3Bv12y4MDe-yuV6KL
F8Ne2qSHVMNtbKf5q1IYBsuSVRKGzKPbuBRH5uyY-jPZmlcsMIxSl2ywefVQr7LjhUcsUI9Sm1UAmdPDszvmGrA8o6e1n7YiWG6a4EX4moQmZ9a2AvB2Z1Pw
ewebaBIl0obCBFIJnJ98phVv-wGmVMhEHP7nBVvEAKoKzycOAU9u2jOeqF2Cpttn53gT0jzjvxu3j1KA01bV-pAMGgL_KCKItFDT0LjVAO1bVEtRNazXq0qw
aB6mHC8TXgGGmKQqR__7aHIkUTSHZQIG01_H-3ZBWDzj4K_GA04yel5nbW2yst1R9G1mHEERpHTa_5_lzN85C0X2KN3v-k_O4bHWI0FvtSC8I04GFNIoyHbh
pW3HaZD3jEAC4KquaqJ_BUhc2ddUl3y091gaG6SRu8mI3JYZ6GFEAD60Cvenu8mI3JYZH8CKAD4W1KeqI87EDi0P9NfWKL-TRO0pIlJiekup1YSRIZH8WMOC
JZQKQC0P9HfmHea6d56Y0MTqje55dH8D5dKwsq0Ab6Z4sG4
}

sprite $image269 [88x64/16z] {
hPM9Tgmw30Hbl7RB_F_dlWqOdM3IBvaxTTSaKF4f968_9xVDFazg95ko3rD9WaInJr90uZ2FR9yYZyFAmzm_atdh95uG-4Zcr4Y0mMSoroDipIKV32wPttzS
30c8Fysy3LwIQXVdfzxFdFgb8DWMhywijoiC_Tw1EhCE6w3MrcfjjNfyNcNMUn1CzZxHvtG6lykyzSNAiPaPYzr6USsizu1tHkxPM98pUCoizs35PxPHR3AG
cVNZ2i1ilIRana1a5e_hHhPMZwa-49d5urfffVOwOXvKvlMr9K-pOH9S49ch27lyLOzKk7zPP8x7XHTnOHnZ7KE0H12PlxosYFJASjvRh0AlA-FoU9Q8urKY
CgSUby5Uz5B_fIHhVX-WIfvVpidQ5sza1W6kNWoC_m3okfF0E072MnsNo4b_Ec_gPkU9-xf9bSrIFUZXRQSNzEbqTvBtlevKfX_SXgVGoMBdbvckMqulmBdl
Jl-NQvpcXPDWFER-Yh7Xk3ZdQnHyNX3aVzPvUQyO0Mx_7_deus9zZWJxdAStpBXuk07PgZjm_yPn2t1Omtl54BJKMYeK70bMRyHOGJQhtVB_9bYysjmAKuLb
GbfNRvYVSLgbPP5WpcUlpWnOTIizFn_s31jUUA1Z_EjDst281C_drUP67ztdtOf84EopS3wQRunjotdB9Mz390XjDMj-c6NcOHUTU4uGrdsauqtj8iRTsnmw
mSvi9ndV71chjn8nMmzQhsP1fOuHtYmJpBxye9SnKEf9Ks6nsS8sfZ3xFF58SBTwiKVKpE75jmcQVKkLCwTdQpD1wYApdYs1cZb2h5SpXSuir-jdFAystqqG
FA_sV7x324HcvTtt_hC4UhN36-lr1gb9xx9U0htQSnTl68cUkRc_bq2lTdZtDnEignrUlLxlpTpSrNgzdtdkOhqqUhLtiLuIlTeprkkJvF6B17y3
}

