sprite $image9 [118x88/16z] {
jPgBSeCu34NzjdGjxVz_xWxrX5cjC2K5pZpR93wMZI_A8tn3ogMstebuXwYtLakEuGLIhcrp0M07iEbxUzITQoUlEvPJA-c16ajdTi9JzMQETvILdF6YkVzH
74jdy9y1z_nzcOt1zm2eVbLmdcNU1jpIPIS1p3ZYDM_gtDk2pajm30FSuc_Es1WjB27mCJMlg0okvzB2O3wnOcLDwo47CoYV5Dh1p7ZMMeKtbkKc1hzc1SN5
wcvuQ-oq8t-pJdBmr7t07Yo9H8RyC5PMOam6fvMLYvCsy0SwkhAPs01Y-9Cpq69OMb6zr5XzSbW7rn0xEwpJMhssWhqr5NUepEXkAZsTxAlN5l21jIWbkymy
eNmm5P2PP6j7LaOE7nBpaJKBqAC9onz7CrEPNjW3cV4FMQk_scbbPGQgFrqjsTp6__z5AcWBQtURwgtCC1TydjThivsSxTAQA9XNLbI_ljxA34hc4Z1JSPIX
WvbXh8QVANQSMLrj13iLIs8LvbChcYjrQl7349wO5AtZCvKUdPDKmPEUyWzTZkApOds7vXtiAvgdTNgpMLiI7Rm3cGnclxF45q0_pfe1QdMhg7OM5V0bA6J-
5NjJPh6F3HdxZG54byIvWa_m0L0Lfqyi_BiNjRFZBD6BZgMpnJsjVg4Jh_47f7kfZ_xK-Hus3EeubhfsZFW6Dd8pL7Y1ZNu8-1Px5aJIzLZ9fjDDwVJMFT5_
axedtW0yDvGnOGkAY_vV0LzW332OUgkbjaPipBGxaz_vwrOSrTHBEdX3RTldeRWezGj2TTBEtWx6nhvzvi7N66P9p2WPFW1S4xKHmuVAs5SWJIeV88ApLi87
WE-HqUnKR0jQ1ZiWEjRMTQjYQojsAiPQXHr3HN1cRROp7JAEUkJgslLJguZeM5hHZQ6h3Z3GeciQtLIirPSgWcDh6JRwF_CpFNB6_AThrzlI2faSMwCf2QOb
ucmprxVhjbPVgkZmLajoqGzACtFjL1pU2lc0bNMTw40VEdmBuArEwhJUkavq32plYskh_1SihR6Kd2RhreGwRVHEb4-jebRhhHwwyM68aNhjshgEztngzLAl
xTzRSSaAAxLlI2Yc5RXZXJZCkPKbu6DQRGluOnrc79MT6ytTa1NZQ7L9xNF0J-CdfMZMgZBuOVnbf9JTxWeUTWwdg04g3Zpgz88Op18_lSwG0wTo24acpeid
bbR5esKBLrruf_ZcqdeK8RXYdn1ZKqxdejJWTjQ9yMsHHkbtTO8JxHnXN5DZCyhvQ9B298d7cwSR2nt6Zz0R_LdzK5KSA_TcDvZ7VaFxDAwtTetkN9FvJPrq
bLVmXyPftvT6r_Jgwr8EdYhwhfJ24NdeYqwfuPX8gcz9aSEIyawvgjsftYvNNQ6UpAhFEaSD5oXGVT3PeZEilUyxFPb4zQvIKSENn0PLlQ4SFOU_a3j4zMzA
klCRfznu6-Gheum-bNU8fKD4lTlxDYFL51uYvjfvR2Dx-_vFK2lnhH_gOOXXWActahuH_Wi
}

