sprite $image80 [105x172/16z] {
j9K7bkD834DLZ01BdliVTsLDoyl97LHmVCd_4G3fxKCIf6phDPnLzB6QewXJiBNZPBsqqZzZTSLOwLeNROLhKRyHTALh2_sJh3-AVklg_4tGHINuLIdhNEkw
urHqrnRwrrrRw5zVdPN-sJjSk-5K2EepIbdgMbUCjQvr_svOdJkhtW_EIlyKTOVex_-lNkcVisvKoWhNtdygHjJzWhrZTTRubtC9vjUgrpfGqJfedmjHAHsq
51MZJRGKHRj09sbVGkgdedZEjDQ_V89KQb-CskS1OWODAr5pVvmWLeaQhwWMO1udg4neLF7QL_JlYTc_Wto39aerPlFlnd4kK0MLYQBeAwhxC0saMf5Pv8oj
HNKBfeCO1lC85X9-NrJxDSuBnAenD2AOoLB9EwAwnZbmtoxhJ62GOOuaM11fM_LfpALlt_u7dQtZ4FV8GkMNexem-y5f80GCMOnDmq4wDnFxV5JpnJam7QJo
lNL5tomY7GTSfM_Lvp4T50fL1mb0XxlbHiniKNq2S-WW_0WYAQu68i1yHZLmg4oK7_IlOKx8yVvePL0OtTHmY8oX4LPaeX_0zuxJZRi-UkimxH28dAcRHKGX
INb_LBDtxIGyltLG6fHWbPb54S5Dn3nGcVIXsQ9wRwLFmcLWktMfFicPelQzTIdguIm6VBnZg_Q-eM-WHmFLswsBT4CX6Mhct9BJXtf4aJbrQr6zgz8dwFIl
WGeiyGWt8Z13pGSoGH7pp0bO-cXH_JMS1khrhbVhB38yY6Ifc7k1m10Fpoc9r3yUm1ysfu7QrmkqGJFB8jrYWfcR6bW1vYRkEJAgOcYBwhULReHculu2mQ3C
B5gaMTAvXQadcO0DSqqG1HijgbzTkzgsDzw1sH_DkZAD2LHOXla1AeQgPv6Pjbbe5hAWBQg6EKjmhMYVw2ss2-J2S7bhdIFKDwBWQea24Z8yl8gaYxosgcEk
dswDliPfzKRLi33H9scwfs-1p1adQYRCJPue1if5EK_rhlqAEdHWVgot6GtghkPa4HPm9Hcm9ueSf8cwEpABEcBVpu5Uc0lKikbbxwrBK3t4SWSo9TAi2D2U
T8aeg5XOCeEcyOng_z-r2_HIszq6Oa2PLP1m2K1pSy-GB8AXPW8Y9qJSZKWpt_8DT76Er_xecDykh9Tx_iUMcMW7ogn0M5chQEVzN_V-ekaGptKc-_8TeBfe
o2Bf6gRH7JOoNL4L23DtCb7jIaOtPZNecaTdWxeutOk-e9DNgZ_tEWiJFud5Y7HbCSh48eeWLDH37CuDkZaJj8kpgpMyxZxjxc04krH79b7k6UuBgKYnoCKa
LTpIZdX13PYW6xCHDsIU8xyJST42094MeK9amZ9TVKbcdwf4OkKfpFC5JKNlLhSL_Zb7fGUlgXlL-Llf6Yws2D8YNGya21Ft998Q6VM2DgSZQyu6NGqQ4LLR
s8rQgIm43_KmHH5qpTGRG8QQHo4ixCHlHDS6VQwdMvOxTR7MIxhAhJliapyK0X48SJ99Luk01S46JGqFS_qjrZTrN8tgrpJ5IQxGSBNki6PmGH585miDHFs2
jjPcZOO9Th1irQ4jkNtbZWfsT8Vj_FbYQQQtAsLMcYhio9swoTcWfbpjh0FKXlB6qoQsGgt0X4Qenf848b8rWQ8hi5KtJ-W4tP-RDiYVrDKczUjonuea94Bj
n4to3FMge3cIlw2juWswEUqN7n2rhgfVr7ySBBgp4Z3DE1r08IDT4gbJTTlN9cY7yhn-G2USh-XUrBggBtdcLKnuNuAAMGnF4xWJ3UhdQv-RCspz1OcJRt6Q
z1-eha1LU7Q7LSjsS20YmiuWkl4Dp1VqO5uTlY0MxOotF2-AY4LSxUe9Y_1GgSfaPlfMtVrC-voWdRKT4RFiD6cDRnIphloFJJKiIOH7g36pw55vn3v7qpw_
e9_p-u3oC3lBJNdzegx5pFlj5PhTOSt39Of1SmO7Q0llcxfV3seGrUpCNAPxRcK7LRSi-6_5cI0Mt9zIQTY10UfoVq0D7ws9JuVrayagqtYYGTKh2mZMl_8J
1RG1ci83Fa3JFhUf3a4Eq9ccqOe-jKl5VubwGMguBhWNmSwVda7K5xJxwyTS9wYGfvYna0mnNXTMe9xycObaNIlC5mFqI4i_SuEsJVVp04RM9YWpnKNDYSJg
RL0v_sNhZo5Ybay3WUU2UaMhRkHeWEPG_acT7jcNOeaaVhP1gBRQ_rXffkBi1fBL7RO23NhiRDXdSpVdcxgG5EHo5VMi7bi4L-MTkkwzS16xsp1K2x0mOOEQ
z3mVpcj0ZTiWTmX1bgkOeySMrKVgrZeiDvFMIPZJ8XtJ6RO5_HqmNqsCr0cxbsR1L2rwR7aNToR-w33qL6UNIeAiRuSTd0dwkMBY1e4upGoLmLHHYnvRx2wL
YRqBv5HJYRuhJTKD-npjTOzwz-StA059KNzK5wfwFcEB2IfDJykwyvTwYhSMX-gcVMxKS8aPaPuGHeYvaU0oKNjMDAPMvQUgTX-XQU_N5e4Fw4tPJjqynXiK
ceAi33MFHIGEKOi2G9MeT1EDMZVAvSn_z6x46xJ3QU3GuXUK5A1xgfed7KVQgOO26A9PK7bziE9MFczeWmPccrrt-7RqvipKLLXd3QxFveIL8lwiQ4ACT5Cn
jlxgwglC1dsLDbFt5vJvZ60B3eRQephwgMxi5Stfv7DekmyFq0ndW_hJRK0V427mS4EhpjJ44rdffqRss19dLBI_jW4shq43iq5393krMtMPD0y3WULgpmH6
jzFykK2QPAMUskUthYx0hFW43Uxzia7vg0vfRhOgWuUuEm7GH7e7nO8eQQPwT-0TqHFEpj4Nz8IpGQ04YaIOUxJgNCsY44nJqKoYNOdq1kqQpMlG14tC2pfB
jT0Z2X7khiQJfAlxEooBQf99F5UwhRfvWzi-tS_03X01oHGd0-py7VsUc1jOMIRM3HZCDi3Q4NryUe1sE1DKaB0C2GA5T5UFLfsuUn7AFDMzcAXKvVy5NT_K
DUPHvKvTUztF3cE5kMko0XdY7YMHy5FDaIYQiguD6Zuz8zgOVlS1BHS8ScLucbRFiFPO1UYgpxwTjDCiYy401-ZZqxiiM_WRL5VX95Zb7Y66o9vXpK4mtCmo
2TPpLqBUeFlPPZEJE37Ddg1hXIYxsNc6wgCwTmrMCkD6WSd7bJA8jK7xLq-TJKbCK8_8Pouu49uk1pC1Yx2ibMNghJy0SQWxUWNoWZvJvCGCK1w7lOCUJ9zr
j4Mg1eD8ZHi08TJToSpUhF8uDcZxz1UqE_mFY7k42DF7wxobNe5C3REIo0enzqWG8U4o8sfBcw0ztVQR3MhdVqTaiQkGF2nTl0la5d40OFaJbSDTJsxGji-D
cPlS3wX93qfVhtEOejXI23SoGJDt8DLTumEQrw2zOBq-e3LHC34UB7YaEYgHQMu11Yh4mfuXUeFsCrlJN4VD6atKIhMZsxfbYFDAcgTxef18zH1tmnVqTrBv
hACsw8EAqvDPsGQOf13cOG4awuRBaHFKc8bjq13803LfgE94bUDn9KX4fKKdi5K7umJDYNA3vZ7Qe8tQKBvUPnQf1uXUSBWd4-PgjK6VhFtMQ8Vp1zJNoclc
3sfih_C8q-v6tgg0kWatwCtQkEDDq8EPe6STCVEtKh8gaEvfwZVfSILprchGRZYpEGpGWnarQawxnLe3LQ7TOLMHwbW8GZtKjzSDl_d-iQMZQym0TGQU_tzF
5LqVhxDCjKIWGc_LuHVKX0OrPuCsPe0sfsFwWuBQ4izopH150TIeLtNpyjYy8SFEsWTq3KuZ9cgb7G39BbLKmjp_rxkPw3OEmq0qXqrRuf3z_x_TjJKWf8P2
rwYnshDjaWVEFCiv9JeAZHjnSC0-G8Im9emaj8S0fPoxqYBxGklcBny6PmG13SBVoL5LbtFNA_BUjjTodECvKJnzHb0s3a6hycZeTI2ej-8jRQzRTdckIxEE
3XiuKOeXg1oGeICtXK4L-BxNxcMJKcNPQ9s5qG7gb1v1SdwxwmZk5Fn430UmBEqC-vVu3f2X0sNZSA9gO4THaq7F2l1PrV62kXptZwGIDBouGamAMc0nh3SS
SmFIlNRRZqtrCKpa1EKOol3MTed-a0KS0SAurvP5pXStkuvofItHswoF3yD4v_T8eXMlLIH0YT9p43ZsrucAIOBZPaDLvTbPvvbhEKYLA3wI2X0vpBD3oJD0
wJZ8GU3h3Bmq54eGtE0EAjAXAgDBCVE9uf9eAq0M73UC_Yb1IMg06pv1bRVWHfHPW9WRQmhL2OihZ1IjrJm1RI39FBwle7ZaKFiH1KRm7NEiBBh7McEpQVF4
xN5Nvpy410h9E5hRqWpquFCkGDG00pbmf_Omqvv4HiB9GUTQAiQk7OpIOmiqXqOzkMYeNAKQCj2HNry0peBSRUZ8CP9iFf5itq7IVHOeXc9q823ELASai3a8
9Eac-KJChmGArfgEZd1m75HWFj5U3Wvs6VdM9eeb8GNQ1UWt9pi9MZ430VjIQbL5wK4mq_NZirGALasKVNGq1nb4-6AGzEDWUmOXoSyQIhk1shopw62wxaqL
AOv8hRmddznYVZ5KT6JS4EOWKIYJ0p6wf9ZHlq2rGodide6gDCwgRcZbo1J3_BAgz4VG1eNkKirWW65_JHdp_9ZO3o1KsHGdncfIJfxVY5AW1raMdUvI0AHA
volsly-f4X2NYkmA94fVoA-jzeqPY3-OAltF_bdaDm4HKmUbh-L7d2g-R0goHEdh-ONPEWNbIb_FZxwvvQ1SwUlv4GNN79GgVJs_8C5I6HAbVvjV4XrtwRIS
N_ZtAGCIfM_9Zw11wI6r6_C3PahVbn_QilGKUdT-1aoKlZ-_Xa5Upft-cMLAtvyVB5Vw_lmCylWFQzMBgVq1
}

