sprite $image164 [131x294/16z] {
n9KBjiCs20L1VoJX_I-tgG-fNihxv9W8pmOyyHqS-01OMe1RoVIW8Dn6R4Gd6UuXLFgF5i4VBFH2TKyYDVe_1TqZqAJRDl1F8jClL7JVG9FHwn1_fgLR8l0w
q4HlKz0z0arstC3fG37J1MfmsC0hYL3fEcb31Fv9f4PMAdf4iEsRZPLCsB_PcJv83UuRs0yqLFeysV4GxGUQQ1ir62BmIm8hxIOP3j4X2RM1UnAXaX_PS8Zx
ljc9tAb1HU1FGNM8xdGHoBS935OR-38cdmhtRJ3v0M2fezybS88q7jmXCLX08f7mZq30HgrraN3UO2bGQzGz7VfWGHGQjGUoXlC6eY0ENcl81bfXIVJkAI0A
oq6Iy8f0A-nEOaMW5PR3IcBt1bfXEQmajcyWXBPUWrfZzmPBGHoqnCuDj4BlRR6Is2YW5SQW9dpsG0VpcmfpZ7vX3KC4Ie6FVoMQNK9lyBx2mKl2Ug3h4DzN
67myu74ceIMsHA0LJjYSnDhWei9XJM89N5Ouax2i8H4O56GDorTYJ3OeMDUG3UmA8d7XcoqRs1GiIQmDx0fN3bGsi2d4VWWNaX01em90raMyzSsM2EmA5A1K
VbKu9Tv8OaLWRA4LmFwY86lyb8JUm9mZPqXfl2eS_4SIQWFZHOoAKFb5uOz_qBM1NK4UJ276nalXvCSar0Oc1Mpocob0d2yAFoV12jjHnYcFov3IF1KMh0zq
yFoimaoGapnq582s57v8edzOuK6l0981DynBGQsnH-6aOOealxah1JdGVGhI8a8QNuvoyg7MwBiKvC4Znf3NKTRGzHgx523pKmAmioWGG58lOfT2U3xuu1fI
83dA7Z4Lzb7W2ldvrcS5gCySAK7e7WeFPWCeyxd6Eaekc6BtK3ZVUiAoMZmLdc-bpTqAGW-G-fUZ7FBW7Z9Mtgn0pxSUGnphAB6oI23a_W-lvfecwma2OL3m
YcV_kyt59vHqqlatdDa0xu3rILMRYq1U-2Zni8jm2mD8bUhEHAXltAlA_UVj5cOHXwX4E_CipABOc2PJy-EubMXYeKb5-7NkkBth5y4B2_iLUf8LOIei_ZK8
eZo3gA_V94eJmkfuZwDtHPJ4aX6QZriBZoTAKlzU5j9-SaNfXNzrxxhTmhYzHYEUgLruupOL4lz0Zo8y_u5hFo_A-X3kk6FNSKsTJjHzeP4y12yiVXP74EKM
UROx4-4MLaRNByAxlNISR0I_fQZgVWXp-2RLgAna1F5njqBjF57MXTjBrL8HYF1by2-0NNF7mzns4xMJY32P6hgkLDpAB1703KuK9SODPmjHNZWiDCcYD25H
tnc2hJrDiRYaAsAr_wGi3gTgsGWOTvNv48Rw6Mt48ncX-BX7J5b6kBrOoqn5U2dB5jRRTRiN13S_ezTW9YBi-iQzz5xBTWit8O7ZJHIbZzkdqL_ASk7msR9C
XDjrc4UBASjKvBBfehJ1f1P4UN1xQLtP2FPIbXPI5dYfGTGj5u4Rx3MLzKH9UgApJKKWNYzFk11s2xDs5mGJMo9277TCMSuGAjlXaaMv_owChZzHch9YeJbv
232FwBeZU21yCaHf4X7SsNwaB0OuvN6I4R2ir28nPS5l14IwSX48XOLesei-gxsKHImJeIB8G9vW5uX5x6lAid_yB0nMT7tGHyh24xyHv25Wt9Z64sLqjkUa
8NZX_qrPu6mJ4R0RVAOi6u4mwKb6y4_IaCBpYVAbqkviyn2emAxShYDbAIiwsqm49HhxCq-mMvYbmDccYXBZHfw0bAMzN7RNF0GKdkZwKyIg2cURhOZJbSlw
ah9SsvsEW77N5bCMdD56TISZmCRyEsNPqTdcYl856TvrkuLvE5mdxfa88mGPNQZwrZJhswGwvuhIciQkFr4E9ZXRJKD0OO5vx534XHF88my1ASlu5ELpjfQE
uEF-J5bQI5bc7iBy6m5XsoWazaJ98phR7qVGW40OD_84kuMv0mufImx2gjJGzP2oR9LuU-qq17zWXk_n5IKAmzaEoq90OH5aMo7w725bIKJ00xDslgGiIbft
DWAwNciFAGiiDMnt7WBtaBBiaBAq3sURYe0WmvIbUcCciuvdkujb3a99POSy8QOiSBPveiIu1xeUKXPXl7vRFzo53GIiY5Aywp5bMUqwsmH5h83m_O4P_WOh
psm4x0orY4M4bxAqdOj0YY33k-u8xh6KrJ8H2b8Mv0b0y4zL8R94X3DOoumfoqDGE5lUQGXV7vW1GU1ixQGXU65X70aWuFr0jY8GPDJvKfPpFfnjCiA0ZIbb
VLxMU60saqM98ADvs851u3VRiZ8H90OPGWs9ssCvGfIgY5NkkD7rg8Y1_JKF0OLVdX0GLAZdf2oh0G7Zvhg_H9zuFv2BW0TctU8H237yJaPe-B6uK0T2W71d
cuTm4nIaBFCJ8RuVi3I4JjHMo1DsGDZlzTlEGi2uWxEDeeIprJG459QEb2KWDFsJjZFRSfQ7WM3O3LXv_xVz5sTIYCvsGrz_ozJ8wNCYeSBvIROt4MNM1JDP
TZGZi62s2G9Ubnc1OTlItwOG1Bmk8m8QNvedQ2ZtzXZVYB0bZQ_D4nB2qMDvGyc26LCM48PZ-ys7m75Fpu2MN8M9jjkQ29soW43RxKPW6tuOYYBWTJaHlcfy
TBPzyI7eb6KIZOylBeCjbB9Fk8d6HuyrEaF9SLFr7Ce3hbwBi2Q4BngVJ5cy2FUwdXRCeC3hiYBmi7ZefoeQ7sst5u7V_bNZez_lvZ0Yv0MpvRnWDiwd1REw
kH1YwJZk48qFkFcs-n2-Qtp7zbiu4LhLVsjyFWGWRiDxZG-l2uHwDG8jzTWt2D7uWhRRXV1Hupilc0sx4s4yQNotfyONJusFAOiFuRucQrCqlYvfV3u4zWcf
kcXyB9Yv472stavPxkLekuq8339uG1Sl6fyL8MbyurFZYpSQdnNXLUCBDBwZior61DNufjeGxb7wCMs_UKEvgyONxpG-9u9gVCi3GU3iYOWoTJrJbiWQ7rwN
6G6D3uIrt4NZyo6enaSe-wJnZRiHGJM-qX1qmQpzdMiH5X3O9qmQNxpL-5m87FUUDBxsO4hWPYk2QdmDWQgWyJaHqFX8HuZ6vqKGZG-4CgLbnn9UXApnZHK4
dX54q_Yi25dZUtma8jeFxkRrs1yOVA4KZQ_jUKMWyT5ZNHtAaX1KuoEKgl6v43ZkfF6181gV4q4rlWZH-Dm8j373C0S8el5v4Mv9u-jsGgaQdmz1DRvXQmWd
ZI_sjc1cGsZ7JTNd_wSi4QhnrTaOIewRgXFArja-uNPV5MWUUweEWcXyHWGqlZs54iSGhyk8m5V4zh8aGjcnFT7QRYj2rlYwDHh26utFYQ0QNqDuQ7nf-ysP
28uR7w4XoCkIIkT4O9yGZQyXQ6SRvaJiMUC30OtFaOZoTifIuWZbjajdwqD0uuiozlqAmddAKiAAyAhnHVnfVAcpNPq8KnvaFAOiqNvmBnhVWL0lHb2DZqHK
qVXC22oOZOMgvsN7exEzMn5Kusi8mCqb_0XeV1K4qVYy2Ahn4SfXayxMXy0t9ZI-YDSfo-94o1hVmwQBGEEx0-TB1CTDPqieJt2J4G6DZwg3y70CgpkKx1Ds
NT5Gqjdw4LJZYr2Dpun0dNNAKkIPhHD1gnxnJkFp86nxZHF4EgKfIzRuXgj3kO2mxxfyJYXLuxiIeHOkMbfV8VP75T3u-ktwK6x3xLRASdhVkUmnXMXyroBi
xPBCCZS486eeGXb4uxiAeVvTxpm3m4T24PeqWyQtN8MmSZlcz7fjIII4zeCxtkpODBuh4BRnT44f0FgHU3TbcQu8PPtrdjZbxMc0S7w9_R_5d8MHn40C16Kg
ds3p3_UPHm_RJnE0gykQDdj3zW8GqIHx3_7cAOkF7v4oLkkoz9KOGpvs50GYOf_rb4hSRbv-unC48gAchuGSgXxMXHK48gBPp3HUfbPRS1rpjy-ZWhuzWuvJ
fAGYlZyDXP3pXY104JMze3gDUOIApIHpbQW144J4cQnD9JX2dGRI7hCXWgy6ir-q4W0XTWCHGQKIWl1T4QUEsOB0HUI2VXbXGiJfOxOWuACn5pG5OUACA477
R46W8l9A208k0HSq1G6Ao0KD5mHM0ZuDpnwX0fG02XeX2514BcYw8B0p8XVKumr2KH7v6JJz5G8_8_9AUBv0gCDuU2KY7X2mYDyND1yGOhD_oN6x6suHHCG_
dKPwnR7OFsQx-8-qy1e
}

sprite $image164 [66x147/16z] {
f99PSWCX34Gzx1ABxd_RTCOBHSgZMBZ_-nNznEs_7B7uspVnXOcps-wxp4n4JEdOwXy9tNkOmWOWeZV3nMy8MCBGOHMmnARZM0SWHXtXeZzr60KOTRZ4J7gO
uc4GS34bN0bO1gYCxDzVa3uESt8NNtZ6g4CNeEkO5xI7ixlumeOfQHLWJ-sty4sVM--nrhezeNOaKk5DHiK3a42b410x0-w9XSfaMFjtmZqCXb709D29e3l3
860IxeZx5DE0IQXLOMZzIHYDFzG10Uy9euCnTIW2BWbWA5Fc08q01ciCnW2587U6eWDzXT06Wx5E0UFF09tWOnCv4MtHiVHLmY2Vk_mIC6NLCGNe1EdPbo4W
WBBec1VKLv18Yu51M7NClauGZg6AL4-ZhqhvGy8GeH1HxXs8EmCwB0HeX8WC7IE7rpCiX7YAIBwYc0D80p4Hf8N8c0AL9ub5Z8I6jazDiAAW3R5DR0Gea04H
CCaEf06UYI0jUuB6S5xphhGOFKWzVyJeew4T0ubnHKIRVUpIyO8ANWZLjYA7XESNzrEfcU0ygyDGz5URaCbszh_R9z-OuI4-bSi2ZkA1OwVKsxfxRysQtnAs
5OLkgSufmzIcrM_LQHoX8n5zUXG57T580WpJKXQrWTwIBnV53CDipNIHfdM648PfC4oNQILjDXb262R1CFNJp1DHhHE4C4p_U1I2bFQDhEQiw0Y1OVft6vEC
eYfKYsfczOueIaLXU1463BDwotBY27EaF7R331X6NaOXszqmpTEOO1Y60CDu1TqmPNMOTOBWzKT7X66gJLc66Uy8fs4KXX4abYFabOXb6F54v66T8CoIVEQu
OSoQzzOicOn2itV1W66qOemJX4V3T2EYU3BC-6Q6y6mOxWoksjqm6eRX26aPPbmCqoW23huCOz5RVQC8ks7qC8nCCefg5yDO68RBGq97d8RHdCWenjSDKxlP
tbl24JHUhAbc5XqH1Dum_Y0H504l0Wm3G85Xs6fY-PggVWX9C0n5mFAr38D4y8RPi7mL6CQimJ1l2UKmJ5k6SS87Xg48OyRCGHGhiHG1Xi6h0OB2C1J19Ll3
C6Ph-7QAS3MCxUizHqWzjb0G9cMOSZUC6TRxjd5d23MgW126eGXrgJ6gYU6h724CamREC1Z3312WniCmQxqNYc2nV6676N5rv0YGh5TG_QLOF8gmBr_VTlIM
L8e08op3cCouEdA4C8nTTXZXed39xeQfJfebaL78RXYRSL5GZZ1mS1YcrZMzs6fkkXi6qmk6OGZxyfMR1MbgLxAQSU5N6-wgLBXgQXWcY-VXqoSIoqLHCMgR
6mQk8Wmpwc6O4eR1OYTpCWIrTXgcRF7Z57S6FpY6hzhgBKsP8kpBLsrc8BbXNbQpLz8mpmHTXidfC8p2CCGPOlaQ5yCCZd0iNugD5Eiz6SKMQenVrN1rP0XX
6BaOnhR44QPWvdJC2md3K55S3TFYwiWHO9W2m_ZqGeTHKRXaNRKPFOdUqgPaDIMVXi5wJqQHe4OOfdpYwaWHeCRTC1txJCiKOJUCZ30CNZAAW2qqtGpJNXCQ
jgUhOJ1yNn5MxzS-T35A0md66Y-Y4DNsgIxhrcKnR1cclZACg8xqxry-Vg1tH1W6YVWTXMpnWHk824LjAdhhXM7gv_X4Mqw6cXqNXJy92A3_xtDr0k5C1mpp
PnH8GBv_ghwbupJC7tlixRFzFHrWg3uJ10buV92ECvIOUZyIS0lbJCSV156L_EFF9zTqj8Spt1Fma8wpidgh1LhurLyuZdG4uTh2hvwpilqa25hu_HELxUro
XleZ0S-LxI141UadUHoj3dbeOI8TlGvvQ64Y7Qs9t5kOJ4UhlnFm7m
}

