sprite $image211 [285x241/16z] {
xDe7MiCm44HXgtbtNUv_N7e73JLDlFy6aEJDPqlJMK6sk56dTv3ckETbUWqrdbcUdg5ulDBUfOTVr3E_JmzQVCJBXEhHCIVcMsZ4Hl3AV0kMcUzd8Zt4XlIa
5jhxMMU-IK_s-84vCTz2_M_F2gH7p3VfaVDDUdHiI4-Dl-A5s0YMY8tGqZZF2d_FwoZF2WVXcL-KC2VcMsWZFYkGdk9n19Q9ZKpFCB4XFJMEoylbnuRq98iE
qjFYPEgbFYkGdcnnOfQPRw4bOjFdbVaMl10RmT80h_h6VwAeSPOgiH4y3_2iS3XpOhw5nYzAyC9y2vRFw5c1zDIuA8tO25w8ZM2P-PRf8JP2FVuLOjAZvvlq
j1X2IyntdrVcM_12R0HBpBVGqa5ZGtgInR0iCzy7UgAe7gDhV_wimAot9Nf8ZsrhT90Us_TjYG-H7bksth-7z9XRRFk-afuFcC-pBTjEUZxWr-oRXtRjAWv0
rpmBTT3__-sCm2OsopdlJajpT5jwsHTjbKCO4P7jIUg1VmyEelogvtquI5QVf9v__7jmfDSj-othjt14r7_Liy9Xxd0ox5JMVzN3p5PT3pYYMRS6dj-opdbM
QkK3ZZnDFI_m5AyzRC9vePw7xL6bxk4Jpg6UtuaYkImdPwhdyHE5xUT6QS9PSkl1NG_M32D4NE7mxp93QdL6l8536_3JrQEA-1wShSYprSF6xy018G1yz4J1
h4htSBmg0ZnPFSn8AdGB9yAnF5KzSofdaniu5X4eN9wgdhco4ECLpaOr0htPSzN3XuzrIHmkWExe4HMVgXvcd7GkU0XAWL8qSqkbG4dr-8FKism2rVMSLXjW
sR3dLZXdr-EFKiyLZeYvdk1iMq40rSojXWzJZ_bUodMMyioj2IUZ582Y2SSqrVEGifwd8E7alqv8yyLsXWDGobOy6dfKWOsViCnGgxN-w-I8rmpjS1XevXOD
DemR86miFRVAnW_Oerfdud-fdpU1350uNsjwm37dqjLJPC3vyRkUYMJ_Ty91AO13FL8w78-m0bqz6ZNX_EmzgauaRq_iQKND6O26UWYsRPyXADK3o0ddf-vH
fsmca_6lCUvm8feW7Ef106uHEEPp182DV_8UrRoUu6oUVmlY3WTRX8eY5Dvp2wZs6S9BblM4e_f3yUWPJLQhugw44qxHX1FrJJqCWCNInMcWKbXyocQgv-UX
6QLS1KVirOfT92AOoguU9TYe9PmC4F68glB3rAFczGQEokda41V0r0oR4G0VwYbk0yx62IUQ_IprJ3GB72QLDpWjcMW4UrGjR-hPoeHZDI9i-SYkFoAZ8XOu
YAHBjIAXF1_4kthS6BPvSjngs1LyJVLy-_ATAR72GKHM6d1cjPA4qvnFwfbfLNtHp9meldD6jHQjtS515DMZMcaa4ucQ7jvpIym5OJgdJX3VN3rwGNEJLYF8
J8IAk6X48uB2b6zCRrqFbm5dSSwYdcyfcnrDg-_04KrjO47frKe9G28gdxiU0iwgTmj7z9ljKTLEQ2ADKzjx9sUVnhcKKQsI2LVZY52SwXaVTPRoRwcULJQ9
9V6qTYDadhSiTE0PrQfXLgjqj8dHdbixdadWEwfdbKt7SYzaMYvCfdh6zWQhZTnIwLqFyexlBfQ9uhjaL8fcoFXEoEk5oLqze55nL2koCL6yTJr_-udTlici
q6KpqCJQvwmN9bLagWTxr-Ca26LC54VNOpDnlcLkNT6q9B9Rfrs4l5wOLDMPMrmojvmZcN1tTBCvKNn7FElqVOWcuZ3E9Qtg2iVFU0YazMhL3q-VA50GKFuE
3nN-ekfHgwUOHDwiSuBZouL9ZQYcP_NGFb7GlXHiMU7fRzH3suOorVDbf-z1P0evuYfad5lI7KvQHlMidbwjT7GzpHELuQAUEpZRV7Zqw-wpTWTFwwnzZeuj
wOHZ4LwRNTH3nhfNAneJXT4hzSp7l6ZY-O9eCk98gtYdpr6wt0dqQdMSdfbRj5ShDmRWX1DDNwg7jX5JFL-dV2zfjLedNi8PfwUQwqKz4ethw7fSAIAK5lNS
dHo0hwAU7SrAfvwi4tVx797rmcGDpx9jIzVZ4OsoMc5DHpkNmXVrh73igrouLA-tSH1vCNYIoXMEc5f4wBMi0u_zLvgvExePlgCUWWwdHXK0u8dd2vJlLSWj
skl14paHBQmZjDLhRd6hcL79HBXF54VNurSyZ6N0YLQuRFDIs1UHpNsVimhPvif2b9UFMLrFIothUCfUhPIWv5FizrqFRGLX0qqurRfwV5NFn--pLZHhdzEk
VOvEE8Yw_izgdXwN4RFhuNt_XHkrbXfoNDMJS23nW4OjgN6OPVtpP1DncrPndgxoYLiuf6RhXvudvwGUSkqJHLOhIZNrStGjwmI2q6yKSgd7ewLi4y-7osRv
lcy7pqjQhN14biEpl62g1sclLW3Kqj5DfteEE9blM-81wN0ool8GpeTEtwtTdfpLEl4EdAcMSopFvkilrGgh9o2_xb4fNMobzDpYvWCEVEWULNtLxki-PpnH
5pZhXKbv5RftFT8d2c84H4z7NxeUWhvbpVgVU0WEE3iU_KZPB0FtabRNmRDTJuxrBiGGQKcb9LRr5AuHv9xLglM9mcZkKIbVrh0sxUg1RSAPUzIFAjzh8Vhp
FYVXd2vC_Y6UsVKqyj7rw9We-52FPhuPrWWl7S-4yo4_rp_HN6txeizPqMJeNx8ikqvgUH4ZjmgDYIAh5New-kXwB0yKecLk6NVrJ3YdtFe0sIo5w4MVqzRC
KxjRa_wvUe1RD6erIrWBrRthcRUUQhHIcmtr99p_FnwrPUYUIhb9gsNml8Ok5oP5gwd-UMuHK7NSzr_S9meIUdjuj9YM6b4BTVMCiKqMzVo_fkzru7urUDwz
Ml_PpfceAOu3CNY098whRFF-Rxk3GwEF5ct4rbpvwDhxtloJI9PIW8L9gaarF3UtkjmfMwAug73wa9vvMvdphimzyJUtt_OAnyh3woOZUb2myzXKiJ19DQae
FLFgYQ9r5QvfMwvSybLwJdD_jivbdVgTqoxu1yzM60rVDwljy0G4jrfAiSGrgIuzEQ_Jx3rHM5es5Jx_HFBnrpkJBKDqEFs7qtx3PeRv873NWI0pDLXvNXxK
fDLUavwvzr_MJpqLSAxICyrsWrDg0vnVA3rUrC2DWHPz0UUmuixPnhhmL7jDUb9tgtxgSGUSJNfEiv_h1gUMKW7dLqcF5RfkVfrPQTYYxWw1F-TabXxKfETo
fMBYgMVTtb5SxgC9S6wdddM-QauhnOJNex4MbD4qXaDeFlKvVMRBZsfIVqbwqjMjQhK5S3AavoR8M6EEIG-o0bqh1svwhBZ_uk3Pvv1y7TIakgtNbcftgvd-
UjhWb0P13Ys50ImKU12uwSQXuU3vCSViDgf9imjuBjagRMwryArlo_LYMhFeKXW_KV0ZUh70Rtfv7WPFp4Ht1sfIIC_JHD7pECF1KbWsxuzLiVXcXlaz2p5m
y_1crmO7CxiDQb9PUfRYTt0OhraNdsAnfJ3ODnV0K1o-RXxQx28uNNeiOv13rJB3D-cPfuTmqADUbHbhbrncw4yKvMvSBWNF0Hhm9JWaFLIJAj9ZLri_FOPp
zuwYd75MPkdHqP0V8N2VANZoy6ONuD1CmhCpW8CUDJ_3O_NyoDPNI8yWDkH79CXqtPGowfS5Ey-YsFRZCGIkJCFAxks2f-IxMPOCwH74XlpeuKOR2p8yZlW2
3izXVGqFHDR6-5Xwl3zRVWS7Ntl-x8c27t4Hsb1rwGNxG90nfwmexxrF5-zm-A-Fdwto-TdQWXwqYT48VeJW6IdOlvh9LEd1RMw0evoAM7e0Ps4tm55Qy2Cr
UF9c5yC9IGy-mfzDagQnzDozkUUJqCYFFfsGfOAz_zB0b-64f0SblHakHvOUsBhVmN76OsNaHwy7ppRSxCe_XdDI3drMiF9jLc3393sQhGEEcx5zF_OZ4en6
mVDfmRxzZWQdpooyeYcuSVhlKkBGfSSxd3LVuCoEcmTFbEX7Ui5EWYp1GQAGsfJY7xy7RTMUBKXFXvEyLa_c1yi6F5QKpIF1Y8IYMON3YOB7IqU3_tqdQLAb
npzOc_bnFix9Env2Gtwa1K-5hmm7qfDfg8o08X0BMNhmx9YlFgKqzvl7AqRq8xrW9xu49ouzDpXyjDMb1nJStLDQ3ykSdTW8VdGZWkiMDxjqE92UylJKKlku
PHhvsOBnRMwrd8x7b01dl7bq5WfsZI_3YKlFC4xxKpoMyQtdvdqi7yq8Zk17TDtwPfSEXthKeVIuyEoCyFhjpRtvTVASNTomPa6kUl04NuAZpQpv3eqkFRSt
znkSukw-4foX7-6wWy5JXuDJJ-3cKAIdf0LmMgT3SBHp3XSQEb-64vSUUuxdERuLS5ejXU2G7o4O1Suv0K4MUrHJRNimALi2d9zJ1eBS43o5Wftv3ZuwxPE4
GoypjCsCCRwbh_u2JgkbOiP-D0pS0xvSi9TbH40kCt31w1S2qjFbUFLjAi4P-f4Ok8MFJgy70OCWFSXNW1EGdbjb0JXZGHOATYruWg-T10IIzA24Si2Hf2SA
Xq__m-jM-5x6Pmc09ZtcbMfIJNei0WS5S0i5ptvx0Kr9z4H5f0U1o0nNB4fFxB5gyO8TtvxJ9ny3GBX7DS39xeXNwZk84Pn6S1G_qWlsppfiedthPKQfzrLW
oJaYFKioNt4893ZnWXq3lW7x7fSPjTvNWPOZqjDN2TO176tJ-9M2VKCpiE-8hTUAke5gKcdNcuoFu4W5iF2HSJOymRwZqWCuXL38qWFzSi318V2t5En2LeXB
ZnERrwMdL07EBoxOkts70GZIGsXUanx0CICuiOAzVN7EqUqxBZqUA2lmck6JMvL8mTwGhYhDhnURs6R664-zLe43EDgcCGgDyMPN2MQ5U8-gIq-fnT9zsKLm
o8-WEeFxYWKvdXK2FMgW21JW10lsWDY4f2TOCsTB0fpmPXVRznwaPqavfp4SN3vj7j5zHOL6eEeBJ7mV5GkJgm0diDaLoWhnCaEN7eQ3dhJL2ZX2mQuK6h_V
lkER6S0phYnArGls9XKQyQelFfDWwngSUC6EuCdslIlfOJXwy1GA3RBl7KYF02TUiBFOx4rwbcLT2KvyiokG5VwPH865oMl1NiJWEIxO_vhOnFTHZPPJJO2Z
RtP1RFwzEUhIOxUs_WvEg60Nii8kf0TjCU2CtdWg1RkG5VOXFNW5Hd2axyxa-shB2lH4xL5wyAtd8pXwmVxls7Ty7zMnCAd0WUX-iTaLo0h_OfbHjfPKWGCq
NmLFsFS-Pj4M9W6dbDR-tmPxmBx_sKHXbWGuqbTvE8dD7gGdZoQPfG4SyQiysBvtBZrOcCm4Hpld25NVRgK72vD6SFI2NH2R_KaFu41p6i4HDesH5VOwf-mc
mf4BTeZDxcSs2y3XuDagiiB-vq3I8yFXJUFGUuLTb1aw7FxeT20hxAFCmC8amna7pq3LjwioeozC2d0GF0NxtkqavuN93pYLu531lb_xriiCNfWSmm4QoRxt
BpsbCfpQHfjTQbROl_G0ZWtXuB7QltthFQf_fCQ5uV1Z5H2RFKeF5YR7S31bEVnuavcyBqpAS0hi-nrcyNKHuR3Ol87qMBg7KnaEiiAxpIddUpXUQP0Ltcuc
MmTma1NUT0Pt3kpxRMS41rdX6qxpYa5M-8PJ0GVs_VPpN0aExFjxfWmuPD_VCvi3plja1JsebniScxw1K50lrRzO8VwUoTo_nMPmMlvBOlCV
}

sprite $image211 [143x121/16z] {
pPlPckCm2qGxBGbH1LZl_xJ_ejXVCb4yMTeJTTtCSdK-E82pVRsThENhr-Ix4jJqEs1EGW8Ww_VN_1GGvn1ocWoJbBY4o9Eb8QupKw5J0N4RiixfM0PnBqGv
JPHc33LF6ExzaFezPRZtWUGqjq-ZGXE6UyX7X_uaU1Bc4tSZlm2ptOq9qanGQ9HceaBZHPYfK1xwD56XxqhyB4J-m4MOeD0WpKo5qjlI7F_eCGxtJ8N6Yp1J
eNmypFheCLUQKQ4PmxqVQfumtCSC_NWH9Yeq3lS759eZpJZq4uRxWK8JXlkzHmywFfV7TqFD3KEcALH5tOarqnMg8aAt2K0ef_iuGdVx7GhLYYe0tOdv2fte
OG80zXiKOaHuHSymOv-_6nxXAZY75bE6_g9GTeXKRFy_VUYXLpXI2s8Aq7Otgg8AUbYr8GjZea9LHC6rEYNCcUiaXTAw1hU7BysbU8EMUGfLgIAWiVFbN836
KZ05oBxK0W8eZT2SSaxP6Pxn-RjXxjNFQx08p91IDiqvinNzzDsWHtX412kKLWI6ahnfpQLc1Ju9n4xYDKn5e6pKKcbLY8QKizfwD_WHQQB7Jwn5Ab20PY9g
b1AMKjPO300_eP1vh3XVgkVgi9Y7zuv9IIcfjmNuHCTwdvR5ppXILTTciHcBqBIaf15-CPx_6gR5XYEYPEtDgcXMfPffrcY1dd-ga4MdMPOh706fOXvMWEPT
8S0SQmQ53fLcQSkojArPS1K0HYtMoCBmhX1lY-hyDttgMQkJVNiQfB5MDDQ2HahbBP25y_3XxgMvL2SYmYfW1j0WPFDL8Rq1Kh6meuTx-RCw28S8uCq9a5ei
t0guX8ZQ7q0fLGyxhayhpdLrJgPz3T8x48qgR4JXOYv_AAGvfQpkF0ZcfZhR6gmY083mnNl7gfwRrGohGXjEXXI4ym1fXkfSrc35EKj4LqY5N5nKcryhL7Bo
LikWq3lIZDMvNeChDvS5E2l4nQp0ugAGvfohisbIT_jHdvQnEbSuGcv0Xcte1SrGq3Q5eDKaPrayfKnt_cIuzzsfh0AiG5isXLn4csjNIALvbImrvQHyvsvO
X9y18lOcQtkDFW9feKKKnH9T8G5YaPnpIihNxmRzilRsgcFhQtIEF5qXDBC2zn21eUZ2g3bdvQjtWxwMvYvEdEFRQtHV1g1L8MscHPkPL595cclD2lVXqUEn
D3qZJcpn712fWBM8kq0Ge8NKsZm1PAtghIYYnVEF7kQnYxFE-AfoMTSWhONpla9mZwB8060eDKJfuSy-Uj0Zzd3Q6SOtdA_lRGsQjRYda6qAvOrFaYAQZuyU
-mRluQmmssJzyKwt-nAuhr3LvlcYk88Hw7cWa7MCkpXZn_pcSm0F07iAvMj0WB25s81iLvfbUO2ptE0Cdv8CG3JJae4ReDQ2s5LexTC3dALT7uajtqhkyx0h
D09xsnHIDRyjwKgmZpEUq4iITWf49xWMP2XGjCKwZWXixDCZd7RpW76TmZj0j0ZdZb84kBHWnn7oPhWVuOmdTCskGkZKDECkaBNcK95gPXUObt3MwjW6ig-G
HxXvXDylKF-FM00QL6XhFL_4MTsnnn_-qOqUAyvknpemQwdM_ne7L6TN8Oi88x0Fn8W8CqFEy8ZZgjCLgkJDDXkKkW7oS5GpCuN7eTLvl8Nk7JQlfPgv6z-k
ZeS_-Van7mEfLki6lLUTS8_Ghp6ZGaRoGOMeKj5nuasS2AOHObI87ZuidK4X5Qa_m8cmyjGtQ2mYWkIEGiVWX3_t_VICY70p3_kxqwfu6oS2JtzvHTo7DJW2
qJpiFPm8oozzDyrYlQAxFEmCR-64ozThIGnxi8KYmlHb78ybzFJZxpMEGEvuNMMFO3hWMvyZ3w2lulWmtBjv_MverHURDGptYqb_wvYAl8BZut2_ddBK6Xob
ELOXQjKNS7oGvc25wC5dSUB8NopbUmgzi0P7QOvNA2BykUfOFeXY_-cLz61znftX8Xobq6s1wkF96Y_2aGgziWQ7Yt1yv8Krk7SHZbVeyHfiIxy87_mP6V-6
4-D5-ESAqR234s7vmpz1D8_mkpWHBX__8UrvAOyu4NsuFvk42CVeJaGWVKr8CIstE3vAyq65nZNeClMtsDSu7g5zkEVn-8epN8GfES7FAEj5c9x2jJh3HPWb
j8SF5s6cGFZ9SFyN
}

