sprite $image359 [243x176/16z] {
v9dhekCc48C33BS1tlznUwNhP8EmdDgDo-hdNfoZM1-ZuJo-8nEIU_nIylaFHVlh67Of_orlVWt3DkPDybXV9kGNhO-qv3S5ipZ48_brCnqpK98r3ViyKR8B
GfpoNC4iEvYm_5g32MZLWUKphMWN7amOwMKXnl9BGRm-qf8_LBGBGuoHNgPTyf85skM2IEDskJxI5XXU36aycDP76a2y6j9uC2s8DDykKygVozyQOeoaB8Uq
J0_UVtsm9NjdY36BDYumi0Y8tMddcpV_YtRfpvnYIUxVBgCvkQj4U_TscTmk1-c7xemq_yQqgDivxRQi9XRfMxTBhQsEnuidBEFitBbTQgcj1WC20YpV4sb-
ncffhGXu0h1yDwGnn3ZTROoqf5tBqQAFylTfbscSxZHCjvzRJcuIgEHkqou5c0x3kDY9PRzzubUHDlljqe_ItP76IZDS_HUHzam9Dd5iEblQSdBSwI5VNX7d
1tgfhKRyMkAaJNyDQPluXHOXNG9X6UnCWf3-rhN7gp3IAi3olWK3aVv2kvJzBwal3wMKSReZ2EeNaARQfQhi_BTeZDciGilo8Lt9NTikyN6C-OkF7KMGK1ff
yz-sIuN7iV6iPVeSClxYco8vi3zua176SXYZuG_4Bibb4EDqOwJZPsCHbJQ7aBwgNMBJ5I3zPDc6D_bnf4Dj5JyI3QphscLF5utqPgJzB7M0gL8LF_A2jLBI
Nhjqe67vERJrLRD_BlsKg5SZpT_7UtWbW2L7pbaJm2DFNojD86_GJHYRJfQmJ4rJ6_iZBqEQNn6xCDBxbfDZfyO5IFFN7k3VuocDBTFCUMBmG_nuY55Ws5IK
Kc0KyQDCZEPIf8-tIzMmzz-S-Nk3G7k4J7uSFtcLpEy2UAJvTacaonAV0K9djLNuAZtnkm0MQRvT4kcYBFjP6IZZLodRvv-4DDykuRNqmtEMWvclILhQsnsm
QDNdJNNyfQCZ5tuK57yj7Q1bNYQy_Lh7vjQgWY-THvflbqUkfMrwikpUPRa5wkyDnVqJlzfgqTSl7S8rbY0CUE5qYNbqcTfUDIWJcFV-AlifhinbbqrAb6Hq
sF58OvbINmNcz7ZpwlmuxPb-re2g7WQbMXG9yRXXXPddhCzAuoWgU8YDVqLfO7WoqZNFvCqy_JpIKCIzgs-jJcu-jDQYpD1v2GEM411pzo10J0sIhFqXutL2
cMfXqo3J0Eci-R3ufOahkp9-YCs5BP2Xd-Y4j6XHqZHMWHSRv4fZmllDXqcLXLWWnECxcp_qiUTeDaqiUsfxUosoOM0ZZO7F8DFWx6cbV6IQl8s7KHnokrsc
o7OMOOYtC1H-mlomN5GliOoY2BfYHzhsztOsnBLrorrwXULn56skSTQjQoC64mm3pdHNsQJdMqPHdAn_MkbscOyRxfO_Dvra8cSUe2FL0dTkbqUJsA1sMPI6
65W-YhGsh2Au8w62tXTslbtIom2mVFn5QqK2hNaxbmOtEYRqlsNR9PzfQFcuQHqh1oAAFry3o84LyTWa1fO_H_fO5D7ExN9Z1rCyE9YmvS-H_ZoAsf7kXUA2
Tjc0vHDVDD-HjdJND6gNxfJ1n5lcJVCT2VzabxLBRFciT2SKnVcRqT-REHCSjs4W2CA9Rkd_tyrz3c8gMyPKxtmWQ8E5BewO_L-xF374uyWyD7UaBhiSH-Qd
-zwHtgXq3H0F8kFGt976PvhRvJWoEjtyAF9VZaDS8_FGTQjSbO53pEsIHQwXOJUL7ujNEWyyZin37zVDAmuEyG8Wnf7hwURFDpd44xeYyiWrDFtEpY46nGGY
iz3W5OTWbono3Gs_ioCl1yK48Wj80oy7Pvf4vaZlzqZVUpae9X0PX0PFPmIx1945f8Ts2I0caG7IwEcCQfVZo1RIqzQmksIHDQGVCu0OdMaUcHVMCwHNoox7
aLMa7oh4TQwF-skXmTCPrIxhV7iKE1qDeGTFPrIxhFDJ3fVZfSoteOk3UdPPvrh-K60ObryhkLto-HkoNgJBl-ROPPtwkwUGdayNugh082cxLlh5j3wUDKLl
InzJiKihSCMA8CqtHMLtgPpfQLmOiuJqxDZb4-kjI1_DI8iG3_vRG66ikQMdBLLC8jBrb5wHOaeYBHNJc__kGbzXANPPbyLPf1s8qKoDIFiGvv7sxJAFj6-N
YS9ox1ACSAsKx9BFGq1Qi4iNwM0nyVdGWBGCiOzqxvbk-XkD3PiYmIx129iY4MA_fJkA2TYbww22NO8HDaKD7o30-DTAlvZoI1-YNUQHbkoIJyVtdDUAQGV5
b4RQNtlKyJT5kbtcaTOXpbyhTRlC8wr3d4UwmIvLf45atIxpIEjscKVQjyl4feX71iNKFU2Pe0vn7caTulorKeSuZxJmKUszNIjrkymZhTjb7cdTBlFNIhsO
yilVCSH2CVaEgXTJ7cbzxP57MjzTvWjBBwOyqZh4UQJ_1R5QJ3xIkbtcaTOXpYEjssL--QlRPHvfVUsHHrelfZpIkbtcDqLwCUMNlph4UQHrYFCE6hFBpm
}

sprite $image359 [122x88/16z] {
n9U9bjim24MZpHOFzF-_ssRHoLD8wDGdTJdBxBg6Yy1pEHwbx-do7o9j0aWx7zm48WBqSYwtT41k0UpvF6xUxzp9tj9PWW5P0j9E4yn1kayGJ46wJn1CSOhk
jBb2dwExEkuvkbdm_EGCtImOw15RlgaxDS5YC--8sFNRWhc3QyU_rhtcHnfd7N2DGFVNHcLz_L7z7ItG_QrHYO6obAFV7eBJnHTqrmv_ebhFr0AIc0pq9WXq
7xX9-_D4i_rPyievGngDEj9zL30WTJdHjAs_J7rFpqowZmfkhoVgG5d9QuAba-xZkn3L_Q1tw9w83FILS4Itdr3Qqp9MiDrmb3EaVTGLwuvt8SosvUVD_Stp
QFeir1sFIg6UgdJYFUVoY9h84uO4kcF1F0AffqoUkcweRTWrXcrigiDiJu7kG33_9Z-BNa-aQE0wyY6cBTOTxyBgwezXZAduS5ZjTEbMtIq5WcUqbvx3rbhR
AvEvW4Lsog6h1Rg36-nx2a1smuPFQJhe3pQHG7Um2trFbOxosXKlbMkODQwgLyYgcnlNFP5dTthiV4kcFwA-cmGwUhva6JePpnzECklcNVXsX728NOEpAPsR
oLJC_9j_KtElQikez86hFOhTjSbkWnRs3eEhQO71lIuLGCBei9w9WvaB9pflMvsdWMpaRlgkdAe16fBI9N4hzNStkCYubZ-BAHuYkIRsjeM6Qi16VuLib0jx
n93zWs2yItYCeHgm8ILJbBpwvLlJTGhkB7Ze1-uawmVTi6UCqVEQ2mnbrfk7L2nOnvZaA6qyWqSbJEUqoNS4t63UpF1MC953jc_MnBcOxPkzkKdris0cn-mu
5qpkkZy2mIivqequ5oyunOAP7AUzSowcuN_DiM1FZjc5n_QVYu90i2E7RFWbpx4Apg7WcEnrGzsIf-1HcNQpGB0dnsdx9K_iQ5Iou9WSix6-77d11ICG799Z
jdhTg-3m9iNaMBTxf_k9O1i1sG9qgBlzO1T6KSIXOzrbujp--3dNnhYUKn6m8ztnBWovskRRgXtH7O_A8EY0lAiUq1timYZXjMY7T1SP1mJNon9_hNlyQiKk
R1W8WXYAXj7flzq8ZicQxtK1HqytrixhIe2rM3SWRW3ywu6NkRmgt0Xu4SHTlk_tPbPm1UuAyF9eIBdBmAy5CEC6m6OBYBa_NmZCkNqNUc3E_J70PkM9kNqN
ca1ktuKcbDjteGdd5XoLERSWSCuj29npgz25RRa5W06tp9t1gEJS0btOXbkW2o7tSyujs8Kvjm0mpst2BTY5ERTW5-RSWgCovnOSbJctM1Vct5yAd7D_aZ_f
3m
}

