sprite $image29 [244x174/16z] {
vDY9TGGn20HHmQ21pZzWtxUDRtkrDJy6rMkUnb_RAiQnU4ggRHo7xRgLFWuYz6YtSG1RwHb-rfPwZf_rr5lIm26N6dCmUQbNmTsdNZatvDvkv7tYP-sfpwgD
6t8l0Lc76jYilVGDGNhM_AodlY-Ti4_yh3trOm486PrrwBUaiKBcdAEM-bqLt7tgbP_dHmXrjxpqPoPWdn2xDVNNqjVU9txMdlediMh8_An3_okTl4zzrjnd
tGloFlLPS_UfbyRTfzxaXjohuEvJhto1aA6xPQcbp0Ns2RTRKLfG-WA79YPhsxMmM21aGDRDFe6pzbG3bdKVCZ_hK0ERjPVEJ1hWqFoooTsdNWLtdthbt7tg
NNPlHxdDwpeGWDlMbYtEQF_RlOX1A6cL4UfpW_mq-Tgd3-Q0f92UdrkVEwgejB4s4bP59PrR1fvGvrX7GHpgAYfZh47YKDlbrSlVpStL2MEjpOSwRQorcSWQ
QsrkUMEjpRbZhSqDMMBz-NTpdbYl9ymaapJuSiBSW2Jghx-RAQPrXhcbpOrC6sjjRfdcbZRpfpdnEghDBM-igSqjwpeAK9kPCzPe19KvwPM9rW2HPwQyCjqC
K9kPBjPk1gGvtvNPpPYPcUhAxERUu69w9ReotUmbpPaQVFbfXZ1dUaOnT7DNQtEAM8CSp80q9tWyClAf6PJcYp-Z6DdD7DJ2VEa6Dz3Dv84SsC_DxRgtDKYl
5KuOr8DvQ73QnThQw-Dp0ybdQ0Zp1QzC0n_gzYEQAjNgEvENQd0NT_Ej5eDgS6tkj_MLn6u-gkXOkrGtE2rua8NvutCN3MwW_CxnOssWC1_r_JpMMp5f3lzu
179g7cDD7EQoWODvQ704Rcjjxh4cxn9iHYixgBvps2lJg6hu5RUh_KlpPgQj5TeSKcsWDl-kRszmU6-NdUHUvxTrk2KSvCGyrWgGS0JAMkmm__6sZjpMskph
g1lANjPjgt--hM61srgRUwm1eXZhkjPVxuIjXRsjXLYPnxc5cvaezIgtjP7dpRrMdrKRUUJPxcvfxcgB8zPc7UjjT_DgJnkyXMbm0_zFSxyoRTlBpRoRkAs3
DBWMQxEETIt-dK_Url7QMfl7TTH-VMV_rCBy_iSZ0rzezYlJl_EW5kOtNvaWNshkLwOPXjBctk0MIApDUbgFDJ4tk3f8aBLPnrgejPdiSoj6aBLPhgDQtRcZ
sTKHsbgRTQnLWtDkzbY7Q6jjdg-ZOqtCZLqTH4oS_TTmfPRc1j7WRm-oL_qIkFEnvipy-WR_hs9RjEtytD9cfNv_MxFCRUTZFJUxslvXM--VGlJVOysPMSJw
dMtzVO8ehinHhSsYmT_OrbW7n8jYBSo3-jrYRgU1UXqzR_POHvvFyojpL4_DrKp4EcQGzPKfGztti5vMJSGwPf1rhAMPX-sXYFgeVaDRRs8-lJZMTtFxfQQ1
LklvkVKlWwpNKM7kwgu4G8XOlrYCvULOVMME_vtsa68sTZLT7M3HF5shkyIltq7oyTG6IRkh0ooQBrX7VvWVrNSpAHeyo7mw7-lVPiB_wkP64UkOysa-j-JR
zptMX9lRFDR6GFDfVcKAysEi3ovR0odMqH2BvlbOktHiy9vt0AIuCj_x4FA2ArEOMrUJfDE7ApFkV9h7sWs3kSVwnZEqmspxWphsVD9Lxf7M3KvKu-6lA-f3
h2tsVD9NPZVF6jngFSpBlcvtTV3vfElxC3mtTpK94jYBBLQBZwtsoeUGzyTQcni0kXmmB7KhnSpDuUUJhZ8nFyJwLlkEid-lcmbpm23hTLIQkzfhMzTle0fp
n23hAvESDpXwsLfbRyyNpMYrJXkSUAoo2tFO8EjrL9a7TJsPPomVGUkhJXlyX_gKkNm4hiMcFwiIvfEBPiHOQpCfp1UPJphMyvzLINFy-JIFjJIJrERuysaU
QsqctNpD-QIhG9iRwUQBpYTzPN9YffklEf_qbKbj9jakF9zqBT3cndRf-QIha9JcgyydVMMUDcyVbwzlKsOrdpBK2c7E46IzZWfpYY3hTHJ2B1RD5BMOCAiW
9ucrC8j5CqcieSmb9TXZFPZ5efairjqivbF2AkZcVFD9NvbkJZcVz9NfPZ6ViiQwiOdvbBVA6-RJ_m
}

sprite $image29 [122x87/16z] {
nPY7pfiX40G_lWgto_i_Rjh9-frDBZ92N2QzZineSTa6kUgn_G-EQgtT9TsxFzP-OEtATPUxMNEidedYqxqlzxDd1dx7Sd8N3wpkQxduQYvMRF72pYhUbDo-
945phrvIx3up0aUvLoyf8NSGE2Lt2GvwUUvJlKcvzphkzTnbTaa3w8LQrYufnkgvO4aB5-PBckSkarVbJEvrIvfVM1muANUP2HnVgAkN5BlFqHST2Rc39UNa
hX1nMcvIr6cvoGHtFIBpGdVy_4awMAnkLmdC2KT-gbdSQGlZEwaBevENEp2dB2mof-KcGISxDsaGTyw5wcQG-RdT36JdDf860-nlxeLYa9q03Bz8UzX6agTv
rhmZTo-vRJT88irjuCkybKftU-w-z485N_ZB_EPk0FMnXGipVh4v5rpDXbPN7Rc1Olv9kK60h1LjKMwGQdRsIeAjFXLOi6wZiBrn65cD5MOZwnxtgjbpjrRH
R7vX6ZWsE-KX6ge1ysuDh6PbRsGpmA5YCmUjPkKq8bA3iBc3LhFcZjp0c1laWDbpkrlLFdfCUtklMy3H23DL4nqVFsnZBBPJV55kCOjxC30xBd4fzrTkCOjx
xA3vmGUpfVBb5hD9xe63RaTWYtAJ3XmpWB1XBuB0mS9KRVvxxXu9p7liur2wXszk_y7T0qlQXp_ZTmtVtEm4_JVnwPAERPp3ABl-oSiDcrZIHxcXzoZ1btjw
IJ7b0UKEfnc9Qkx-vv8qy7XkKSE8vwv6SEIg7EUqBceIQFL-Z7reIUFS4FTFxBaZSsULm1Ev-QUR9kPWIPCShNTL0-pZInhdb2DNSxoaUMwgMyqzMD8qfVwk
ShCiQH67YKi2h-Hwpztxsi3nmdgN5nsBsQiRtHoyw5YSk_VWgboSsysTLPQKaRlxLPdDtjXzIVcSgADB-Wu
}

