sprite $image158 [176x274/16z] {
rDM5bGCn40HHiQQr-STxZ7qCjaiLmS9_FUbVopDAsgUkcqPEUzH2z_MqGINqLDG4Bm-zQXOuN0lDk8RUgq7XJbbanjaem1ctaEUCwHIyHjqmE6E32qTHGp-f
PpXSBnfnmuZRvXi6P-nmsOppq9-AoeVhZFaKd35WmsZRvd3PZ7t3u8phXnI8srQC0fjnxZfPizBXUgESOSEeZ7t3s8ppnnI8srP3vsjaF5n7aS-mOP0JxN3P
ZAjHO3Fs3GCmHi7rPeLisF-Vw3B5g6SyN6Vy3nj6OkmRncPSZ0ASSPV5PjpM4hLPtXkn1NvYFz5hYVt0qTFBZcE9_iJrrVC-Fl6n1UDhTkn4INbTIG9mt6R9
fQH-_yUT-6MAniXWinWyCzUnSNIsxw_8o98TaM9lFyPdRsm_nlkHT_in5dOdRodR5-UAJk_cOvmh-iJq_v8Ows-i4TlljYWNOusjnzYbrX5oip5ERNfJlDqO
EngtNlMPlSrGD6rwQyIsO-n1crxBlXtZxsjZeAOtkh5kgDio2lbqo2czlnk5pfkmhNLRQdjlmhRJRTbXlRTqo6siwDHstZeXzhTZxDJsth2t5cD70djlTB2P
5VsLuFPzjfaOkzIRpm_dnjglw6zey_cFF3VMFiPVY48-kx1xiR-reZjjxssCRSJOdRRtPg5zFyQfdVSsqPTZx5Z2hV_nuFrsZ6UrsMTsbDHvPgoztX-CGkOX
RLqeFhMY7QbPcDzIEl7Y5HrUEmgzjwRtHeorOeoTseUyOeAVwRRmojhU2oXUYV4A7JRZ1Mw7OfstwDG-wpNTYTTRqKxjCrutRnUA-R5suXKwRB8V10pe5s8S
NYaAlRUKKFDINhtRdDfNlAK40P3W0-9UxxMqlJVSl5FTzfOOPt3Vv6sXQ5vuFiP-AiPHwZkyZb9EQ060m3LYx59VVFRPluh1My84180n9NOy5UFKliqBk7cR
k7d15xfDxi1Hwrkzy8MuUOKvyV9GkDItUw4pEDYyxuXnQbVm0efJLOJ9uVIr5PqTjf8NZAoAS3lLopVDA7L5B-bpLQXvSyRFlKMdTZNlEHGbYjcyK3oxebtM
zmAPuX8UJlNaYYxr8rxJSLvuEVLdLdJza1TWdAk2modZmHYlvsNl1PIXADPmcfub7uC-xwN-Gk7JwGCn_e8NT5P5QAYs1rRqExmbuX5lXgAHsRpquXNziZUu
_pa-veL7bugS-loAVjqRsFty_E11xtKeA2oByOlUeltFluTtlDIK5w0lNfZoxZdxCUWbRnoRzhvNdlQ2jr-OV3F6Vi7h_Q3TxNp7wn37qKWl9rwOT6u1bzB7
-1MlTmrxLDGwwpMdlA1FtX8QJkMJjzIQoBVqcHhtaAEzxsLeqWluucuC02ATNillwRESxewbBl8g30FilOAYUJCK19ZpbIx4zWlU-9VTpErIhpJb1VptmWJn
_9ewEBjkUyPR3ibzn1kUza8NeMYduR-2w4BnX9VPOezvWzDUYX4b_XRUS2q_JzPFzbd-W_4llCVoFYyltgABYUo7TDhZFbky8DZKntzfYFfMB-2_K8oyenW_
u2tO_V3S3QZFUptfrTzRT7fxyM9lqJupc-DzjpT3qNapnikznOUyAMHwL_1cA3flZdYfDuwxnjqxoq5rePVcJI_PUIN7j3V5yzx2GRixjX2qxet5Nk6crnDU
WexqJefBYRdWDkt1vLnc-xBK2uBaP3ymFEK5DEtD6FkUDuRW_knr8hh5jpumNn7Mf3SeW9qNDxmvuZApol9camUFU1qI8TpqIWzuXwJCUW_nTu1_1tZKo_QJ
HETrSB5tlX_wSHvxRynwJHWIYaTUKwUfSnLlb5eFNHw4EU_G3oJAhoXEUBs2jt0VjUv_nlrGk3ikyqg86WJPUHLwixVrsYwzEv-vnrqkkpcl1Og0gW1UUVrU
R_5XzzEyBGy3CSlviCoR_Q3VIarvnNTvstUSmNlww83IRXNj68zuJPOgGBqt_2RlVdzQo6NeitPsFEwRTfVSHLxPD37bPGJVuSrdMCZAlqotwlWvp7Y30hMw
TyzJPFSZxY7g4rwR8coivTtXx49Iym_nbDSYn9MykwD7B_EfHTGwu-ML5_RPIwpa7HTimVuVzg3KtlKALrvYD5-juRqw3Blz5nTuWIilSFQ684XOsPlFSYzy
vPMfo_klbtlBkbwgUJdsWaWl1PBBlNLThtmoQEJ5sIkZfNgXj_okwtKeco1bwHtVVnTwVp_YTVCIf6nUU3Cb0WJFUyj7lCphxVK-JY_DeIhclByVyIeCWJnx
RLvwyn_0dBTyqYjTUArdxh_rWzvk7tTUQyPRVh_W9MvuXtwxvwsVzee0dlV-BlBkKDxjbVc4jopnjg-Ix_Q2427X8MzTuBLBNS6BviLZtj_U-_fJbdepoekz
PHLlZBqqRtf523GMUkj7lCHDhvkNq3BlxoUy44HEUXbklarvwPpaX3TucY-iMM_vY3VllpUzKbR5ZBT-qDj4cin3vEcSztT5RxtovlNsXXVd5v1DUAy_xxht
kdbvnri-xfLkUlFx-gQylktD5v0xtlfnRmJlU_M_p1k-u_tzdbVJNaRmVTx_Uk47l6KBNc9pNjxn0Xlo-kGLX7lprJ9lNTihAvlhXfVvVNqJNeAMJpnFUjCd
U0jUGC6Jz_xz5zo65vO7tXsl8S3yclSuxWShlVIz--_Nl1Xv0NhmGRpXpS1u4rx8PY9lU9al89lm0ZOxB_hxBxRY1UqPxzVck--zpM3EUVqLxy6E6g4hho7p
ZlUB_M0xmkR8Am2EJNeZYYNPlF92eMrwmvBapakPwOM4pNYZYMrUUG7PwSKMlFkJDqVCAo_u5meO_hRt80_U54VtKa7pxALnuVNdlM7P4NzYMrTUG7PwkSXR
rlCsyHcSCHvx0Jj_Vjix5cUChxsITVR2kl3oyzwmhiMwyWAqygVo_dlB6ojwkn5dZA-yWCpy-MNlT2XyvOMjinSolkCjsMUzc6ElGElivHrlNTLhfz9TZCTU
G7y5_ILlIFBj65zv8PjVyofXlRWFHI9fSSPRrlIcx7QtZRq0_Krlocx5sDQ5rwUgu3rlhEqDUp8KUQuhho3nVuex4oHNGXY6EkaLszp_k7zVcnP15Hph1Aye
pPDdp-5rDnkfyLKLfohchT6yVyYmsywhAbJFJ_DUFiAqvxRxJvX-ylg5ryDz1afnkJGRLQX-b1VzUHSyqHVUezpoMgmVz4gC9rgRFKxWRPwrEz4ZlFKZFjF1
6h_czNYVAL7ZbxmMnwl03ls9pk7jss6W592tXl0MyAn34wqzNW_XbKt7_pwZDXFzULvv73hmpoEWso2l1V6AFC_cMOaQ5yHRetX5LbJZ4RSXNe_ZbSS-LkFM
RPZN0db5daVV3d2YatX5bgR6WnFzSoBRr51UNEF-HEjtOhMRU3GlhZ6UwE-ew86dy_ekbw0QOxVX_bgTpAkBj5aALMFjyFfKNjlaDjn4bmwlJUJruo4eZvsQ
Q3NtUzuwYzVBKt3uYGRnIRowogkiH8qnyHHUsn_oEW_-qcnJt-VruobZUHp6NPfj_6tUiiXu5hR6F2_lC1p-qfpBww2uV8sns-Rn-laKElob2NW374RN6BXj
1gzjR1NUkJG1Bps-VF2bsPzeWfTn65zZocsOboykduNxOX35opji-aGN1Rm13fjqQPgxEVa919-PbsPH2nZVg8asLVC0XyNLsAipdq144GzFTAqUuB2eYUxp
yWuBdUYVl04EYvfem1imlZCkpPz9S1WnqIrnaiDmLktMECzXkCQz0pxJONYYyQL953Uvne2NA6vaDcLy1egRMsFONyigBhuq0IyrlYaJpOrlVeq3Fe48kpGR
Nk2mt3pBly1f3kCd-iAB7PQVdsxxpaiuBB_6VtXz5oA94sq_7KOKDzbjdCFo9xewux3yYPxjiAy
}

sprite $image158 [88x137/16z] {
hTW7UkCw34LXgn7t0gJtlzmP2R9YCN1e5RpU_iVl69YInrVJ2Vh7_JDHoTJTh8vGabIETwgzADTH37UfNQAp3gjqzoHuLpt6T5qUKAaUOxmSLXcDIdyXxCHG
zSofkxHRyNZcixlL6CLmPRTyRiaSXerZfExSRhNbyS9kNSiSxrORRcSUlrKFdVOWWNerSxnRrpEV21kSzeNTEd3QlLnKusz1fwjgVDgYUX6EJzkKl5UUt3LJ
wgqoXiNDBlFUp6QcThUiJ3Ffy9so5ZENxyoikHJBsSp8-sAebVypQsk6Us9OBkvwXbioUuBLpPxXZioUmDrikcMucDaJ-5GPgind4lYajsseOfnKVSHsppmb
UzZApQRgs8dCLTYgmqvU_NhdsWc23kOxSIhpbg3kK6mXNBRARyPmDNGriOfH-TfA4BkM4bnsfd7QRTNTd8r8M8XsvZXixEQi8k9ojNCMn_3TQhasotZ5qCPf
jnBum8gAUWmHVMLcdBbI6suIBZ8IwipXQKTXOnU9ImmcSUBpQLTXMwvWbeq2-IjpbQ3jGX8ySnBmS-Pyr9rfU0n9MumwWvKpRe9d5WZ2qzRcUtCEN47odLFv
SDgDzreQk7DbTKK0_NpQ3LVwhjETgvINcuJsjitwbe5_TiXJrq_8bGkkxkphTjfgbhEwkUiGiQC_TkVI0BZhBzrEEx_Uh7-wgPloVprmLJTNaiTWWbdUCiVk
eh4R_1_MhkvSWMTULijV-t7FB6d9OmTdVP1Zz-UqtPtH-Dwo39q-qOt-J_Oktro1R1-Xvkokoq47ZbsVSfawAO4hU7FVLmFcxlRalQjJtqzQYWqz8vS4e2gB
wwkHPFlyR9lQdRe1Yz_7hiukIS7iAgYGoBLIkzEo3dovPhy_Do0J4F4aHEJcmEMK_xlodDaHjMiW8SY0hx8I-EQzblf-TWSjXg5ZU1UaGZPNssu_37DYxV_3
uz3rYEz25G1qTUqBj--JbPB7lk-xVjGIkvmzmG5tS4h7VfZuwuvbZJgJ1056Rlov-MJVXDfT94KI0310uhuvsBDggWwo7eVV1Gb8yDvosFNZzHIsVdwitVmy
xDA0xVDQ_oYrMywulh_kCjpV_3phUkMNQzoxvRSxsLUkhmQWeVlyvTPgxVB7JO203DoykSt9FtUXcxkk1g5xjnntIS1TtryVk-pgx8ARI_Kdxzpd6PSAoBjB
LFkRpxa6yjrL0lUugfMhjxg0XdTHplRTNDpY6W31stktRzVragj29W4tbmR13MuIWf90RYuL0FSTdaTSUjz42aJsBeZBxgn8SXVhdecSTs7PNKaazYxqodjD
YSM5W5Bjxtatcr8fa8K6VN_rwlwAPJCbERk216BsUNL_JTLiaR7kWt2k8bTTKrM75Qyz0zSVzrnnxUV9fA-6qFyNUi7ToGfPLuCKkVBj-gAzP5KgtHN__Cww
Qm3zoRojXe2oS-sOkt-oR_Ew6k1vDvjQBPEBAmd4kU_ddT4gXcxVL8ZeIRV-Sg7BLFx-UM4-r26x4yIuucPJEXF8sBjsm4sxnzQP5JktVEy-UcJZcrpldBwv
-O3xU0pyIxQJxZoJvkYhikllicrpq7rqyYdpVifNRYvFVVZ4cLqkzS_Vsh1qZsr6pViCg-nzrscxkHJsZzrCzYbp_FFOMDLnXtwNERVUczCZcBzspgVXegl0
PkQ6ws67sFGOwIr37SFTMBKwR3qzp6FiVQtSHjX3cNF9yMFHDz7wj2ivKhKAsyvSxvm5Qfw-HJ-VTb11gjqwadaxlURHdijimMwTclgq6xjrEdDrj2UdFcsr
QhSkJh8risrXf-kgP_OOrNS8byTtJYtShSkPpKxjLlkqi-_MtTEJNuRz1m
}

