sprite $image156 [275x185/16z] {
xPthTgiu34O32TYo9EVzttQ6awW7SQh4hHOBLFURUoy_sClQKXJ8N0x9cAdUxtSkytZfEm84xt-3jryWGwxtMkiAohLp8XDNoGSM67e-8eMPbh22KbE_H91G
Gho6mbEdNWLSHqF13flFCECsrBTIRWK_2Ikbp3q1kG8QqKgvTLCp2LL-bRALo6kbvA4xYNIlb36Zf1qAtVgHIBDIoazLogHhvbSfHkDjLihKZKJQguUkFtXw
RmzLfPIXeyPhXtxYsc04TCLO6tJGU9jd_6itZRTTAJ1qqtZR6tBgf_6sA-NMJ-Drh0rwa8X_4nbV8ZzuRJ1at2tC4PKoutuXGk9eQuDRsHN84WgrDXXXJo2a
d192AKFQ6uY4ECRQODgtPbH2AEKAkmFHqKg9ERtxQqP7AsKAExtxZuYjb7uQhnr2qck3NYMYlqbgRT13uxMZffGJRIBdmsh6UecCrqubibMANXlqqtWr4SsE
bL9wbOZ-BpfyRJ2Tf6QiAGN77Xgl3KJ2UctGZKHi8cIi3M9FxpuWs-gXMr-DLuSSQuF8qxiDXEormT1JuxN_MwyDeZTUFn0aOstGZKGCGWwbn9lUNmCnb9Aw
aeZDJwyD-fI8RnCPl_5QX6meC4INI2i0Exji8cSCMJEsKcvTDLwTNTO68yHgl7QCJMG7ZRVvDkkvWyQx_psHO-O7Jeug4VyzaVO7Q5GwP-EL_zxnkIVx0pGg
1PM8_vv8-mCqEAv4_8zI3gLAD9IW4l4_IZbGtKPLpy4rOmFnAEKr4gmg6ah0cl4_IZaB1PPTdQwUq3MZq_ee9GkH_4ZX1YZ-cl41sVLHokdvKnLoDg1KYjHu
_OzImlDdAA-2MoY19E9_b1AVFr7oEe16zSIKY0w_gHxPAa3M0Tf0eKEcTmUHHgNmFvfzVhDc5KCfaMl6Lihq2PAx8DbaMpqrD12xUkO696Rri0C87YqHUn4v
lqEI7db0OKCfOHgl7JAO219GG2I6KcBNZAwUVtqYNmKXiesXb4YDrmvzNDQgxyWNYqAYOYZbWDtxZapgeARNvKkeY30e9ePI0ah4PeBgXV3oDTP8YD8wBvKI
5eXcaWN9LVjLa6GiERzM2eULY0x99TsKNxULmpapS8DITjYz7yQ4jpAf6acgmAc0LJq29NJDIFXH9oZJoKqkiQoG5AOAN2fHRb1AQ232X4efesh3Ih3pb4e1
HamPO5CzQ1oK08tNJgqBaIA6JN9zwsCoJGcu49I4M1GJOqe9UqH49xWmUGwnW_GS9TXvcY5nHiI2_4uf51Q8X2kNGlUw5cobKa2OV41XH8HK2ROplg6K08tN
Bftwz_NVMElpt2Wa2vHC2nBEAPM66J-CHEnEBCSa2v8r4r7A0mbKJ0rA2LWp4gxhbyG3ryeB4LmpaUf92n8YJXdUDUIGG2IFww1Lqw62VA-Y4mK5Sww5Cz3R
jG55aOXzJDQp2TVr3AkW_1dTYaBIffG6GcSx9bc_-DC3cr9A0b98pBK1XwiP2LVrIYT_N1LjcOXIk0WI5KCfWMf6GhfoBYWNfLuIg-e1XlHP3AL40YALerRJ
8zldHAedKqagjb92rOm-9d2HtAh9H3BDoOWnuqS18gcoSLnrOd4iVCva_WAKIc5gHYFXJ-wha9U0ZL3iAIKO4EavbrNAwefgKKnqGqwjIeb514cGR9dK-wfw
agjwxgI014IYcLJwEXHhRK0O8Xg9Z6mA2WeJZrA4I40aybQNgfuYK5nAYH7YAYiJbUlgWdPGoed3p5NM0viarjL3kG5Amun_xX0_aS3bamnG7KgngeTE3aIG
JCQJqzYLKeYVgLebEjFcWiYZb9DN3qlgcyzkIEoeda1A8LuZeSkhZ5kbXAyU6uWWuS60OIe5lW65pmo5DH4K8YyoyqzM2caYFBK-6xg3Kau5H98khHbB0ANu
WNpjWyTkP2fbdeBE-Ao2qmQ8HodJz6sbdEQ8q7pHSIfbNlwUlxKsu8E1s2NZLqgUSXob4AiKpmT8tSorGPwc74Kfh4BRlkjKYcmYvPYqLS-XIg5jt_N6NXla
n_L-Rsrm510O7IYQrWPvcbkKaW-3mYee4l5diZUHZGqv7w8KSalagsk3l5HFTkpn8pHUEsFp9lBGXcmtNfz4Tjf4siyzxI-Hsmv0cZQHy7MbL3foUlTdUBE9
H7GevOmIyQyD2kOJpFZ6zBvVRgysaTcXb0YDrx-9R5SAxpIzxr0pEsqYyxzAEU_qllycKfXibKAdRRp-JQJEYuDIM3CvP-Frhmrq0BEg7iqaeu920HglNoaP
4BLID1D0nMJ_wVrufK01e9BiSvA159De4cbV6qW0e40XI2OJwJtITzmIIOU0QB-12HW1IYwONp01Lao2D5wTzXkOCbSkK02mj36fXq_l-wyDIgtq1mf14nC-
_VJkNniihi0_IYclcOXYZv_UzryR0Dsv002-gXrrJC99vEitCC4VfU2hlbEUlqgbH6YyVgKiLrmmlUt5NFvFWEczEHE_KeeWiPYGFE4UP7htp_ZgqNHJiQLW
lTF-RtgVRcrWwuHP1hP6YHpSUFsRoFUbOpJY_TxqFi4cigaJnsky_hM1tNKU51rlUeTMYdrCQfZftNy3aur47vDOqxj_4saZ0JNMUzPcyPMIisuwDTRqxf_n
RIH5VZRUzExVHEfaYMm9ADZqxjz4PWk9L0uVi3OxU1EvH0FHFQSw6czCfHXHCedNUFsRI9tDjEQOteCg1TyX2Tfu_Pj86uc_yGPT6zX8l8qtxDh0HkAOteFD
-8PI32GEYOHU6wWKZIIkHFmtC4de-Osw00538bqf1QeWyKtlyTS69518lYhJUp-vRfHob__xfXmIOthlHIcIlryWH-EDF-CBXVM_Koz7n5uRwDnBZqJqsa27
fqlVcMW395r-Cs7zYBp2wpxZ3CIL2UQ3WFm7
}

sprite $image156 [138x93/16z] {
nPe9SkCw34IzYY3M-z_sbs1ve9YH-Si8wRw0Nw6x2IWpfuzrgMeczNBwjehOG_NyLOuB2XEBgfdfyaMGAn8IqPE5RzyQ291hnu9VYSj2J3knEWjCZyiDcLxq
bRXSeE7uIbpEXHfz9IxtCAOLEuh1ZERMDnmH5xbFR6x78hgE3CX2VKMZwtbIS_iMQVb2G5gB9E8ohhbzhT0Hbr5FUr_Cp-Z6lJ0z8C4HBBhCQcvhJ2WMmFI0
_009Y_8BuFwXCIqBdESrzoZL-RXSSiQqYv6lyveRIiGbrTmUT5XKSaTPdYDOv3wwkNt50XZTtBvY0SnhRZuk5nXYJDjekKreRZukvuM4qnpvy_8C7YRbT43w
mdSVZ7SsVP0gZns82m_lXU8SJvPX7FqFnjlA40QQZELmuQz_Nq1Lum80zSd2YO1auYAgLi654d4PD92MXVvPf6fQOHDjSP6H766Hi-XrHm9FXKKonfWsBcPs
-pcJigbAn6NSGCAYc8gesKQoqKHSndAu74NEp-xGWuHhSG65HS4n4eMsXyt4IG2HeBZsSM4QB36pjSmNVTZZlq-4OL74PR1K6LT_qDJOXx8ibIfkBCthCap8
WWJhSsygMr2MfH0ZGnENiK8HjRK_f8ZeA3wMYa2bYSjOgHckvwiAAJkAim1AhQLfz51_p6nzzS7KjYOxIwbKbn8MJM1HixBURFxeOlc7iW11UGecM8IylIbN
rPYAinJNnBYeoUE0z9_Y6kjd2PWfSL6pqmv5tPI69HezZaMSP4Dn5eH02PRXSS4WELt9_AUa7h5K6SV2Qhhx2XJpN_ALF3KkBA96BrzWq-FY72l9xUKVNpUB
chYCQxGyGE3t3q9lT3EMvhp4Fng8ADzFhSeZBihGZKkW93cMu_-v475PtiL52CVCesbqFovCc0k8b7CBS1INvNsZCT4OhPV-7o738ZXgT2SkVMF8gzlJfRui
W9Q5FurB4zIERWFY4iO8dBi4nmi08HiNV1g3rrDVnmi0u3WkGfXfRbyNxCKbBCB_tTpJHxfnt0ijo_uZZJ7NtBxQUw5YsQCuYwDyqDn4N9m4QzcZ00TAPyLa
rDuBLR0wIw2Gen3-NNFx2y1HcB7Y3nJqgRrjxaS1wTuBA8pGJ4M61EHu0P3lHI9uoOfnnQFc9WBIlHUszWHALM5J_3KW7MDoSGb5L3oqkQUzLVzUQ574vzK-
xGFKtWljKDgZR9ZYNgWlcVMXC1BX1qzxUW70deJTdaHpKmjWbNDizYXIvcbFtGiXL3NDFEtfUs5FOfdcvkEo9yatDnyNtpsQRMx-NW2eechPvkONWFe3Of9h
RlvUs6IS74X-0PXpf9T_NbTWLSuy8Vy1
}

