sprite $image136 [238x165/16z] {
vPhPTfn034JPMr8p__-vsIUnFDI1icmQaPlj-HwgN1ectJMOPEx-5qPHLHd_2zT-qT-KuVwoi_vZwMyVOiTqOzUXw7jal6zX7RUkxwI8kRztOGjHt-o5bV83
kMrzvnVNLz_Itx2mKjv0r3TbY8lZVPodzAi37Yo8yt33mbervBlqDrcT9rP_eh2-TrcTdsXz8gY-urqAA_KD9ZUfxoIWi1v3SLxwz8NLwl3rpNfC3ijEOHs6
wvjwTHn4VVCNrgCvZycX72ri_lhsH67JrtVoha2Mzrs63Ai3IfksllXCz4WzY6RuBDZFmFNpuYp3HLTd6wk727mMRFvoufFhU-6N4toSB_zP41IMy4rpJEBL
mOJZlFJNMvslhEzqvSB6uzo-lXFXchs-V64zagY-_KSAc_2On6SYZn9f1lLjU2Ro61TbKDz6PoAF6EMAZydsgnFtjU8u-LKEA6mCFL9OCixjLmTZHqECFmks
FnFvEECGy_LjNrYCW103uFgsFnFv-ae1aFLjNrYCWS8IzMqNOXun46AYlkrMXqS9Lt1C9WWnGQo-yTLfZnBr9GgRn7TgkpeyqVgcBYnVtpvpOJ7HxmNxEOrh
_9YS1CYcUxoo7sBdghbSg-aRh5AhmylA7vhasAevrrg9Cv5BiOYQGrNQkkxOZl9HML7RHALPY7zWq_xgy35MCuosSgtLXht2yh9YEsYB4FzaNV3gl8TsnNnj
dj-vsjFryLZmwiHbCNfsYEkwFhPj-wAl2D7OXhhowlfyiDksisv1FDbckhwmtjNPWjKX7wqHo9aXThPWTTX7gyRmwQuunCuMh0x_Q2dah11lsquAO5hRfhc2
LyVRuiBoFv0vJYcijtM5HPIcjl72Ujj-LarZonVMsqwYQMtt2kjjNOW1qiesNbZFx5O7sZR-cSoVYS1sCjOMOnHd5TRRcdsMhHY1dXTYRskyRRov9wsEjntK
VaBQndNF2x6thOPyUTkYDImRFnEnRVs1xVaMHxYxLSyjhBTz-XAsWJHNatCBwsttVOLBcjOQS0qM5hEMljOZleL4RKkurk3hS-D2xD6XwwhJ1RvMUEJFZm-p
vxy1rNY8wzHrpXO_te-cJqIUNP3ucMY142zTzzuM-rffIBomqdSRjkjZtVOrAM6Q5TR6xecNVVpLjOiyt7XXvwx3jjjnDaqQugNlTcotV4qk5kB7qTNPjtLn
RfbbZHPsttRpyPfbBYoszRv1tOPdOaVOllgQvIeiP-lho-ksFHCfsoS1tPPd8c6BVQrAXZEHiyM-LZNLwl2slhxLKgmERyi_tlQhmzdM9zZNgiafhcgKgmxT
7kMeRJNdUxaGszGTO1HWI_YsSiMhWvaCs-8uWpm7N6EhSvm5sc9VtzzuNsDl4oc6SjIsclEj6XTMgnOx4sb6tR45nvLLqw2gwslWvGJ5PEkZbb99NxNwqISi
hwfg5YWiGp__lBgqqhxglWOWJ7s2usSYJs-4hlbdOeUK1PZI8PwxEBrMmjUdqEeV3P4jopVVbgWZS2Q6TMN7KzJvUkmdFW1cVqLiGpIsEd7c7TjIWA_NzYWW
kZfn1jsnBMAklW7YPsASPSUs576Fb-Q4Cv5lBxO5SIPei3gOKQ7j4mlxyYydlepPTcpv-hPV7KnVTcnZzULVYNynWs1RghxnmaxT2Ko6RAdwDZeJUHPW2-gR
gh0upjwMY7FRCv5dKc3B-RO_4_arah8DNgFsPoA_Hi2MgI__ScBe6Z6gioNZtFvCvEFiR3dVzcSY7sTWYux95Ak36HJO0j_OcTYUIO4kY7EArS7qYvOzpFbc
M1tC8Che1bw99ucpUysOPNKmYyckxTCtqUhWDT83jkJgTDTbLDspPV_dnAMPJOxOqYydBXjdartRDMrXSPnvMtyc9c4o3ThgqEMXNqm2jdNgSZ684RRuJ4mM
PsoBpyIKBAQahJyJyyLPADjrxZ8pgW5RS2OcPpO5jZbMXtzp9S0MhKxsE0km1OND7cVpjebNX_-MUqsyElpNWclYmlBVSg_4PvsqB2-sGgnEsZYlH67pntab
LYStYzMw4eLDJYzr9Sx4z8nwbTNv3W
}

sprite $image136 [119x83/16z] {
lPQ9UkCW30PzIaBWll_ZRh3TtrM9lWMNUFRiEKNAa0n_XsGU7cSH3O76PwKJQtYXONrGEbBGSA2oF3RVGyfyY7bwGZhBBXKcOjcz3wnuPDLlAK7ywHMlvto9
E4JTnUUAvqz6W_cAnXUxNpwxueaXPOq7AkIik6yqSiptGlc7UFbKD5aHBp1fPyNzeb4hjIjMfR7VVB-ZuHTYlUMAr-xHC6Er5XlJqdE-dF75DgPUqV35cMs1
lIzxHCDimUFPN_7I8PeIVzA4cFeirOAMB4ACc7ZwIpGb_ee3PwwOnhlHW8f9umimwR3qco-mCQcSKYFcwNuqDPF-_GNclcoBfbuScDXWLdmtcl-j6FCrc9Xw
BDL2xa_ft9TED1rnxaidcdxO-x9-ldHnKypXNF7xQ88GbL9cESXlt9gowg5DHJIdzUrZKK7x2eWWZL6AQ1mhmtc9cwGS88qfsAMwLj4IeVRvwcxTr4HpmkHR
hRTzlbcwRMgYyGxB-XwcrlbcAxIOhtDOQ6ySDqlLI0yjegdVRBsMsCxtH15DDws_L5WtdI4rC-unv7Af80YilfOfw5igbwgGGakgMcWhZylK48tLQbHrTcky
mRFMpnUah_nUY7qj4yaliJ2rHGFfzXMN60inatC0c4DWfjPeGE9no58hLY5lScJ-rnGDZhg5QHXERThWnN4zzOlsQ22Do_02MdDWOfzRqS1BsMcr4AlSyVhH
uAWo3eNsz6gbjts-EW_0Q75W3KJtvkilTOMpq4BilsQv7yrFajLYqgf2ZlXUD1P9q9O7TiJteh4icg2rOjKWYDHtraLJGdaiARuLgx0nbqu9TT6KZ1mblFM6
_SXlBgVpxUoiYCOL3vF2MuZpFv9TW9b5pezKHUERVvytG7oeuR1lblC59XeNZaRC771jNJRhQuZ6PpO7tck4sCMFffvLBp5J5cFI9StH-8pNf9cEczONjqVZ
CuK4RVOIkvFsesa4znQqVAsuJfhMuIOZnGHj5hDPSOTe72P9bzQik5Cq_gI5u3KhxXADpoeCiLsn6qqN9hAl_FU8e_hHz69cJ1fQBDMDfj-aeNMZwSp4mcIq
oOccCxC8aTNwqVIVDBHEDFqPMPYCrekc_wIDzenc6ZxD6XXQHFC08sc2jbSqzIzwKjTewf-AjvxHr3yL8vedcG8FV-SV
}

