sprite $image412 [76x109/16z] {
xTY7aXud40HWsC32X7l_n_Lkb_yfohF87EDijIrL_eeUzSNqxPpjI4WuUoMYkgTuyaNKMYEwjgXqjbj2g9qvGXqLqaUhwsVRKCyIA9gBIRrMyaAzvgJFsHPs
qDw3VGGErLRFPZiOXrh9tz_1M3kYzURFPZkOrCesfknGinfFx60kB18xb8L4LGOxM92KnnymynABYi2A7WeIhCWEh9vPiHr0SXRgjOLwPaLty6RbqY8IhD0E
d1NOWRC2Et3MVl7I3hprr2EcoA7CQi-Ze2tNCwio66AcTSdUnH-DQAqUVBF0_5xHWIGgehtbYaxNKsqxTvRJvdUWTAJqiQfPuxFHk5vvjlwnBfE6P-DHFQdv
fdRwt9wOm0oBZWz5-_EeAlohHSHCDDR6Eo2wRge8RMTdCHDx3TYF3bNgtO_lq_UM23H_jd6zkgLqrOJarblyMfJ7zNOG5TGfn6eMKoElYV1xFJv1yDU5VqGv
KpEBKGfcPudAwxkKyaCTgdfRcrmv9UeiquX-RAcArWHBvR7obcwGUujTKMz1eaUuJhFkv2Bz9knfq4QMSibf5wQlqba7gugp-hDvI-N2eOgg5hFs1ibRADfG
r2ohrxQ4x2fcvGffO37rPnEnO0Suj9Z53CbRlcZtBfNyJ4dFtX9L6LjMzDDHpBgVr5IhTJpD6LiMRrMiiwZecI-9MKtrUFuM9UmWzAwlXefsgCYxcdteIT32
8YvGOUj9DIfgxIWOjtAo3vZukugO5BLiKM5B84Kjot_9-cdzjFZliNvQgbV0SjyGCoCKi_0DiLb4wnQ-ppDBeArPgcrFYBth-RDWgV81gBU0qNSjbPBXk8wc
JLhumGZn7KsRih23FknA4arPYXsyMEAU1cjY1yYuenNrWlz-triEeaRCCplmblYBgV1u1uvvtPUr9UBn3iQMNOoxZYmyiOCtovrUX7cmWs7s9c-dVyAZ7Onp
ajFmHtYuWt7onRtcEzflb6QoLL-KsErWCiTlpyOYtE_07sh-R09kj8Fvitt8YHrCxODLs7Qmb8DC8sBRmLfoOO7MI7Xw1-DzCA8YRWUBPnEbFOSfx8D5QvYn
VIpq-mK
}

