sprite $image113 [247x180/16z] {
v9W7TeKm40E_ksJm_O-Rdb3Im4lAUkS6yvx4ojp-2fyHRzPm2IIBjsKTm6UoioFj2nUY4N6NkQ442zOHt9EzaLBloSvIlXSG1pvQ_0846_asKN6V-Ir8WvVQ
HiKZU8YXzceeF4DouvJQcBXBu7bA6EjecQYuB-mdkz56sSZ7B89IYX_rQ0srLrtcLQJXIWq8Agwrr7X2K76LHmkl28wPkb9ZZVQzwaxbUq7tNWsbGrfxnNr7
ljKdtIL8f35LZSSiogJhtAg-9walidpFhRMgRQywOQcdkQsqjVnVJPJc-ucgQg-68fPUj0N7J4--zzfGibUT8DzxyVdyNer_8nuWb5u-QVF4ZlM2eEnexSLh
vspBNjCItIFQgnf6sVNUY2gErlNY9IWezG7-OyNxNreb7w5B7Ed_bZeUorAFDedud_8jr-OziNQqtBokGW4u2mcGm7t_rptZf6N26NjYjlwwwohJgtur6AJK
Drl_2kN-fIopgPq7mSvBdFtXr-BeA-XWopXF2tQWYsVIZhySMkliM5k3lR2lthcKhRDtz0_xBuOPU17Df4Ti5M5cKNrZGqFzzPE58-bVRgAyFyHWXxa1-qy0
D4xi_BGtNzXN_t0fa-_1bDYv5YcnWxW_S9z_iAz2rfjQwUL-PtCkn7R0NZoIub_Nzr3zXDOKURc3FMANfDvxenDsJdrVnJ-zFj7dvdo83dNB-IxeO2kUd_it
KLbgxDySPYIdw0G_wUQJo8_l0Huf1NRjVdLzQDcGY0Qwn8w7pQF0NhbyMHzQvbFVu86kiJdE79_OsdKLth6-YPgx3Nc3wpYASaxFx1OF-vGTCw0jkxKj3ArW
kvk-myU7H56tU9DJD3dtxqXcX_eHxiNBbtfJPtOH7kgkmKRmulVXGpOUY-w0erxVcVtAJ9L-WTrqbDb3FhlTovSlzKqqsBd5FxW5UIT_OixO1o-5SxTjNrlX
_rVhzHtiCZnUo0Uz_TpX4Epp4Zp_Tu0dUwN5svYNsFQZdwKM3_QBr-DlSiwEzCFwtjKxkx2lLfewinKWhRMuIh1ZRaElio67zPs_AfrMsbTZ4xt8xW3GhL3f
si31Jc_e0pQz1sVg-OFs4J-nSeltCGji4a8plphCTWxuZJtIcogpyxhIGttyi7s-LNprVhK5-WgRqTmwsDqlj7Yiglp6_lcJTnOLFXbWf-g0RvR-25SHWsDe
5TWJ49-46UuF-whsb_k77MM-1-TpUmX2VPIPqC6-jg_od3Ms2w3M8S4-hVJifc2FaHVbpCvrSgRELqzxAX1ngx5jEWDipEvdS05o7X49KaFy44qEsKD8Bg3h
RDjybnJOix49qCqyPqg4WvIIs4DLUc-jxGskP-TjFVL6VKSAYktBTxSLddQ3kW3ixecUMfpf8tkiNJF468iKq5yxE-0Nt-JTNO7X3FHvLkbCG6ILVLxVaSsl
2Rxh8txbgsmZw1Dl04338tcOCOleC_BsIcj4r7YlQkNzSvVzepn_J2MsRGbjbnzrOhlPDROFGAQ0510XcgSjBg9lryEzlw_24bi3zVUEW5RGeQwWWntmIsnN
0W0IW4tHFN8qnTEwSfRChjUtLT31ZjWbjey6e0q0xVMuxNoOwMj6z_731i8887syolR_Kj-vFjmByE0fz-44sVtg39Bd0ZSEzrLjZpYAz5TNxy2-2wLZ_oW_
Aolqj-hxAnBiovMU7gj0J0ay0A2PkoBUx2Erk6Z-ebU5ciRvZBJm9fyPRTNw3dO9RczmsmjyCWiWVNShG79SwOczOuCN7w-mvtfzPtQkz6lm0VGcKq3k0jxP
0Ea9lA_FRVjQHWUx37zp4u2XQEu6CWMq0N8yp9viblC4-rU6rZcxtk9JkjW4kRkseO2P07eupBWwmDQNidZKv-nwYqSQXkzHOBeBo7pOqRvQPwytTO5TQt4V
wERo_KgpiUDRcmVxQgTFQNgXlWkRQ85T7sQ2ra5J0UoVC9oWxeV3RDGp5vgwmAx3XV1YJmP05kmBjqw_iubQe0liSgMFtiGLC1y4ySokVqkwVj9Ao0Axtk8l
jWzAJ_lA_UeDGwl0hhRu0FfmQv0N--Jo9U0tdBJgxFemCo4GZuR-P7FZkLJf2qEhmbwlT6C2WBQp9m5Wgy7NXrRILTXB--hiEtPd-sZSqUt3vSjldBJgxFKM
7yppoRRfpf3ponSjD7MzlklizNsLe0Fege0_OrqiLxhQTcjJrzdrOTQmYma4c74JiuQHXjdmh-tUeLLdrokzwG3DqG4J06qsg4U6xhPWhzTteDVOw_3Nyns0
TQ1HomlCzZJz-achpbvlSGKfFzdT9k4Asn9weRuNsEkBEW5FDhlh1_RQIUi6Tg7IRGXWihCdGNtgiCJ-bPFMEdkzqeNcG3Et1ZK2-apirPFMLb1NsElxgbc7
kX5K00BDnBvdQDNPw_kgJv0ge8msbIYn5qzQDxBhmqm1FDbW4-Z_i_FlVtreBMJu7V397T1TJuncmLuvQIraC_HPKAuSIQ4JRJG0CzWB9ws5EEFnWDWjbJwc
TmnNmWZs-achdctWyGoftmBtIJHiSB3_0Ztf4Rcfqbr0H6mUHNhJq8eOFrBORe4F0je1U_Cxq9iWgszhSLEP7koRcveU1sdZdahVizrUtvlrpBspnODzTrCx
Fyw3tstnnBxXf1NP_bVDUU0u30CnK4wFpFl_SwytD1SiHfdm1uAN66w1hrDRq32OPMGIVUd7jghZYBoQVVLTU_IfRTAPjtX-wfitzMNQ_ai6-eDduLEZq7gi
nJEclk_7jbD7jDA7TLhxLOTPKG2q5iJdLO6f5tM0OCRNzwaLHEHL4RJOlEglRnvcVATrR7NnUPNljFmMxuEXnUVLWgaBeKnWSNvyKX2OLpiy7WG4mCm3BJwl
CZijmDGmpEgcNkYqp32R0MWfBGxij021CEjpWF6Ws-BrJgkDrbItU1T2Yy-hK7tpcceM3zDfsM6M0hGAzGt1Z7ys2Iq-huP8edwOXHWF-YqU0bf-YsT_4kNh
cy-h8Q3bjtY8JijlyH2cziCin4xBR_4GdPQ_qYEkR_0U88NhAhN5wy_k1MX9OHO0MWABbvzzAzItDwy669yeOBRyy10xBR_5GunF_1OFqMdvOPRIzQ3VuhkU
FGkWXTu3XDXf-M4MejFoM_mfEwtw_IhIQVbXXbnN-IsET5h-lFe_YGBrRSshYAdz5YzS3tBYxm6GdPO_htx_CG2GEgyodPOVPe-3rXi
}

sprite $image113 [124x90/16z] {
n9O9qkie38J3eWt8_Qyx4g7YsA_7vPg9y_hVryzIqnAF_w6YaXv_HOcjDQE_WIPhPaxNycjoqHReIPVyItAMHLvqJhyqsdRwcUtrI0QstsWqqFssPyRaIJTE
D-VgHCtgRKOh80FRRyxLAbCLsNv_hbmQSjunR-bserKq16hNUcUkckbReWtOVeFHY3pwwlktnsmwQxVBnlFPOTxeZW6gcyIUhZuVnjfNRSydHczr3vFjn7yf
RmaDK3r8zEs0A1gptypLkRwoNLUkSCt2VqXq2UJjcxb2XuX1sF-BxObFsotEJhHJi5VO1zwktydLh3lhfoJOA-p3q8gn-eq1AgMQrotnATLIAicRtIFiuD01
syyk9irVOSti2N1sV9QMrM-sscWgE6_OTZn0HQpjZ1PwAVllHTqSzX1JaOqjdo44OpPTk9WqTGW77H_kO9S9tFm6mhQVvohiOMAdwoREKoLDTl2gofjDytCf
0kdOTZn0M-zDw4YValGenTayZSukskekqP1Dq7REvmEqTPS9iUj0P-VMnLQULiswXLsKTd3Hrk5snRdQwkwZ6mTTzdIHnGweI9xiJHzmcKiENgg0qMzrIrb7
3zkFfHDFjguI5pkzD0kPMd5lgc8DvmrVJAnhagnzshwdUxrI0qlnj--wQUQBFj7pDYMYxTaDs9wsN1rxNbXATwt6ixoa3al--X6wkfsr-ebMyTUpIrLl1jag
fMeV8-YllAt1iDwhYsjsLTdOIZjxHCpxFY3RskYz8NgNt0jtac0ls-aZ70djagCa70yrL9stmzLGpojfhidveMKxiGX7pnsUCd59gJ3bE684o6rCyW3eFfx1
HlJ8M4svPix-wOXNuw3ppFLXCZhw3xQ8_JjvFLJlaDx2PbDdSqqoHCPOjWlntA729Sqs59dFWzizEYRls4VRN-L6gLcAygDQDFv5FzuT8kiCsmtjNEYDZKll
L3Ht8ogShOyrvAFdPQTTpqNjtEW36z7Rf8_ACGWQ5PDtsciwYdUvEZCQi15zmbjDnAccghc7bC6A0KOtc2lCNd105wCoAblkeuCn2ut6xORiKzl7qCIIfHZR
f1lOxTToXTddjaVQfMWfqljCEsYys8LSOVQvxSDCixBa63lw6hF4TZLNJwIErH2TA77IMZc_RDSnhW_GwsoSTYkIEL5PXyx_-cAkJjaNRTUQk7J9tTfYum6A
sutPrnklLloLKx79lZX0iKO_fHkWbrngvkgVEblqGgwG_4VS0VsyyKQLCoKTphwMAmoNHnR8F1-pLfJ4sV-qPXP83CKW59plaiVzZrltbacMmWKYE_k8Q3Ve
rQEs_d8wtrGmzhxV93FerMExzyVnOzefTftpnQAWDR-UUZXsbH84RMlt-Op7iGUyajdsuoRAiKT05-Uz3MFdNlcVjzs2i6ElrjuPc6FdNbLg1DYHLmveZ9rx
rVfBtmFi3z3KgqTntv1N8_oig6rykrSp61R4BF0ALLDttMjU0T0KEmnGlxXlWW7AiSV6tX1e7hFY0Sgnax55l8fZbtymuGMxgq20PcDNcbUykmfubO3T7rii
G3bsTsmUeDotLHzZEmSJMBoxYeDEYjd7s0bUyUugTZ19ZLc1WqcsRm87asJiHS2hz9ZzowiZ
}

