sprite $image394 [222x174/16z] {
tPs9TeF83aIDsLebTVx_Sr-8zTg9XaETwG4QezbNSq_NjIIyv75KzMb-FcvQpnc0ZBTawqQ1V1VIS3-uGI2l0kRd_K8ffO2fkr4e9sShTIFzNBZ0b_exiFKf
i0NzRYASrttqwoQ1R1Hak4CNy2BwtK2uM-XNXEDyCdKtw09tqM-8eRo1VYIKDz3FnwwAWepT3OGZ-drg5-1uICyx2FU1mzbOn_OXkr7I7UWkUsiYcOBmVMvt
6A2gwdWtqwzF2vpptKe_VxPKtPKlzPUwLLdexgNVg2A5RjTuNa6_qNvee0Vm3HUWUz40V_1ke9_JEOtZtKa_fzFZuZbs5w3JU-aNwLm_lOr-aKw1OuuFSzUK
xkXueczFvpJOdGzvQajte7umosDRkiFqW-PihS_kAFtKifbbD3cyAT3jh1yiPrle56beUNOydgWAfRtesenbumhOFl74AvHEr-IcH1y950BimVURBHkQZ6MJ
8H0W2GHSFovSO5lAv7Jl7ARGELwjVZ6KfdWZIvljzJTTmUFnvA7ypTQ2plaANS3ZV3oK_lpPYCxvd2xYyLiJaQs4CXndAxgtVYdWaU6C2-V8RUdK2IJWaNYI
Bb12sPhE-IG5FD8Tc72Et9hEBpWbhq13TYFeXd3jwRoGLl2uVaIugz2f_CM3AjTFDxh0LUcAV4I_hIvmPJh78_6qDJP7RaetCJh7supdsjZbR94Efz8zXT4b
0R2jtqON270sdhoz8j8XHJmH9yIwVaoumcRp-QzEWj5v5SIetsON-3Eyu5oyqL2yedG5CSHpkmlO-sZHu3dJ-IXTASr_zMF2-T6YHKU88nQdino6C-6XV1rg
0xh01qvdOTJaRAAMMtPp26heL453wU0DwShnSJeiT95lGpXdQqGN-IXTDWsrAPo3jwPpFldNT5kXz7_Mdixrgw8Zmbs4JWDSBLtEwbtWMXjGTJBNky2dqIcZ
Ay9b-qGwnGPTw08DwGPe5TtgTXx7hfNwadC_O86wP48Gw3Q4UuDBT-fRXX7vA9qFqO0Wqhbm6wqzzQU-PHWA8F21qiN1s-boNXVk3MvowkTQuVDp1PtpEHqB
fH-gd1NAGXVvmEdYOh4oTgsrTgSxxMDs29V9wE82vFfHuHpyUBgNS87EzQDqSG7oU9ft0RRWPJdrOtPGfUihN-y04afpyAp36S95kiAtHiVNEtf7fPmZvkTv
tsw0U9ceeLCgNA4JOEeEwmBRT0f0LIheY71lEleng7hX29qVNmqT4QxGyJU2rml7wRXtokbYA2ETWEXNtGKudQA2ZjnH2NIoetv322MZKzccKspIHU4YdHTa
E2AKd0w4JWGhT6J1YtHHl_gnYz75sgBptHihT7p1K_8ng1s4utIoILSwOwJZ2nxv65H55o1qD9fqlIjqETEnXNmCQWVXE9qAeGjybilrRonuqE9TqAzoxAgb
qmswyBP0fyjqmLFBWOxeHySkJiSFZwztQfa8vu4jT4G_AXoabYxYyVLEBUlcWkVSWOxenxj0FHqA7Hap5pxI1PmxqiLuzXLTe99EXTEz-MHZ2N9kGaU6Cz85
gW-FqoceS9pEzTjc8rsWvec5qwaHuGWTwGxqIsxgcrwaKqxt5avSE4h7kqFzjsPXdGyhT4cpChee7AUB-bMEA3MRK6XtW7Aw81oX8_gHJbxD9v5Er20WT3vs
aVskMhzkt8aFaQuCO1jqFdQH_OxhjtSyiNfu0Ixm1RhG1GXTzJUqz6aN_IHjtBWETA4BC3hEDnokNqhnP0jVe8jTWDErrmzfbThv2bti0foklNuE0Lql08Kk
2BS77T-D-bHrVAJYyH7X25rR_JXVw0AxqWcszPjmD9yHuGXTG_qu7k32rT415SFPcVf12TkxqSU2MVhltruv7gWV3wKt-XMsRCCJ8ho0yN7ERXIBaldq6Giv
pzrZG4LdFr4_opMX555RBdb2dNUnXhtqutGyb82OBbULKB7GdgYVPS862GNzaYGcIwHGqGzEr2_ISU4qvzGDoDCIA5G_MUw_6t4wBXoozCkXvO5eHuGxPpYp
J8GBfVfO2jQvTZMXt7ytudHSkFVxD9CjrrBL1Sxi3fPvA8jmqumyFvQQ5iWUrI-Sd3ESEHrdWsNqZs7nRQb-2jgH-ofjz7CwBfpfk6HHxMLJj_nXHgLml3li
n6UPT06lRxYbeCk3-pLK27UoVfPPAE5lGNii9VX-vCa50Uy2ZVMpl1rAMCv82Q8_UPlcfOVxy8JgRte_QpYplDK5eDaMZRhaqUo_Vp_QYs76piBjVsl2ybOe
BQVN5K_mQ7w3JJRyW98kq4w_VzAjTxY5mrFeqLpEpAQVnsMtzzhhvtGkN8J32yZf9i-BOFQ9YOIolNwMYt2XaB4SHzyv7U1fWOY0T86BwFT7E9Z-WjE5Q_uQ
d4uycWE8S1VIxrSeeJcFvThrjUDyfKUXctyUAM7tBd3OhGbdyxNq-JuPmn9BcujthsWouIwctniEYprlkl7H9VFHmpltipzJk1ZF2ltYMbheq8-scDRrRpe1
MlwGbZvLyod-qWb-bEjqVDCr48xiHhLqwd3vkROFu8HGqbiJzNJ8Ft-Dh_bHCNQrxGwSJlDoDi-ymDMFNMs6Cqvd-l-XUUWca2vmAVqu7SHI-TX-aox0RqtK
qi5oqZaiuAGBN4G_JgSvfyUS2Ypf0XVIZzEfPVdsQf8kF9kq5euFPvnk_DBXjOodAG5N-l66V3VYTBwZJY1ZrmVfvtHUlkUGK5vKFqxNZQGBN5S_JZSaaB7h
u_HJl4C9yfh7v-ddTDLZL_lXZDCnuJvLFnKNZdI1pumdPl-d9unTJMvD4E5keDy9OrUBtOWitpVGxoD3oOSpqWLke1yPkswW7ncxFaq_8jmDzBk1S6GuEs7i
QhKRaR7hq_LpuUvPm_5Zr_y
}

