sprite $image403 [73x93/16z] {
xTcBShCW40LWHKJsxDhtVznVPinit25iXFptdjwzVCLJC6qp-PaJ4MrndWOJ2GS4K1gYbWmw0rgxcR01f45UkfXv9T0rM7lBiS5sjwb0maTW9UHxKa1nbEgM
jkBKAMntUkRdeB_nADoWiBmD9U66XDnHKLsAxq9Ps0PTGoBcjXGQozE3-AqVt98lAvB46L9kh78WpQQZXZItLhdUSJOFmj9UvSZnCezCMXCWP80qG0u5hqDu
tNO2o8JZmNCz2YK3CHi8l9VLZRiGZCIoxySnyGM4b_SIN7SVZ7obaE50jKlJ0y1xYH21g1DYW5WA8sSFg4ikn0TJej_JQPlIt804UY0S2BI-WeJfEMX3kWmi
9A1hF8Y0BTGWEpdXGQHt30Cnq9PW8AtAGFPG7o8WBmQg7Gm7AX4oKFLmr2eogpFN8LiLcXN9lZSWCoZK1tIkJcb2Igc5obKva5vV8oXC2zB0OHp8eRGS1t8e
BSU5tAgWJ0Do1mLMWbdga4-1TJYCaxr2nNUf9qRmeBzSo5O5ovow0zbSog5BrbkGEfM_1c8F9BMRG1TKcn6T40DcdlT2EYWKPW0wAOXkx8FiZ4Wi0v3eqftc
ZUKZq3Gj99-0IYA4MOQXaiGoEg8pSyvf3D8iVmGalmVwXg8FVKFITkHTA40-0-dDiXVIX2nZa2QIZ46Q5J8CQLMZa5Or1caYP1ZInvKx4DSLhMfyHFeGx4F7
1seuMfM5ZkYcml3gFmF1Og7ZOquikacsUV8Jia8dW_XeKCgN59g0hKeBIRgvg8iBc5LpGa-N4R5BfHotgWBHSjcyggfngvATu_I1H6nJ8py
}

