sprite $image82 [161x103/16z] {
pTS9heGu38HXTh2hd7V_squFQ4fAjnX5IY_-J_2911k6jpGV-pGaJ3n_b9Qud3mHC_BC_969c99N4NFoH9oJy5PpbouTSHJlXfYL9-8nP-GfCn4Jy58Hnqsy
3c86deZBztZJvk8b8zQybCHf5w-3c8sdHCp84z4-H9p5IqciUVt4TNmlxn0l6L4y4oyTSH4l7R7cfIFMl9J4HLy4doLkOz-lHahYA5uMOZ-ldvYK9w9lKyV7
SWPYpKj9dCJx8N6V6hxbCnAtGxoSH90GC2CHZt8HvzSd2D0jAn7aIKH2ee0YUXhY8I8e8HCITSJfYFOVqKdIFItn0gBGaXAN4-WH5d3eRKb3H9n0syp-U02v
NcXp1lqoxHle1GQIo44qHqJGU1tnlc_sHwCd8Pg3SG51EcZ5riFzZvvYB9epph2216bReJs89PnNS15_mxl2C1sdns7sXtKp9qNK2_s3ooVWC2n-FSIzqBav
-KkYBf-0_xOY20B7yKUdqjlo_TDLFfoDEmdIZn2mazX_kW9UpNPv3kDJS16_URe2gjMlSoP_GpG3uoMh_jwflalKvRi1gkaWSKzqi-zSFiLo37MBtn5n4Rzm
-HGZZd5uRaCGNprdq-a-XwMsQUHyzIhUy1Yn3pVDHgA3s7NvbC_3VIlYAqHpt3s-xSwcS-vueVjFrwSRsCt80Hg8tJpvk0qjBQvpDdVKmfFuYSl729k6nZHo
FEZUS1KxBf_YscJJEPzPb09d0x7tTCF6eJsD78T560szH9tkJLoQPVN8yNKBXyCxYJhTXitMbbQBky5BkFVD73Fn6ZPRQvEH1E2b50Tv-qAtNxxIjDdQM_ma
7fk05P4YDbw-yWmiFWzzRI3fgzzySelOTFbAb9VDrfT63WpaQm15RFYeAezuizawckr_5tJGpPecNz4PrvkjlnMtGX8KyVxoNIw2XTLcwwZrQpQ8YtX_-VJW
G3PijewHeq0LmPC8jzlJBUKI0WsRhMVa2EQa2Z_mA4IiUGAo54RHQFv0uwQhw2mX8Mnt40YA-Bns6ILuEjcmsRf6pfL7AONGC_JT0CsSbyj78Au7gSVtgMOd
0VeQfOHJsUxNwy9hyjM33wIq-_3XLf34UfGIHXKyLRZEEcfW8Hh-sTuySemqfmAlXwINGxljciwbTREzRxNmc0w2LH7q2aYmNCzHc-qxhKxIZQ_LG5q-RRPl
DUvtoxa6uW96nsRh7Zcy1nQoz6-s_jLo3toapVQBThu4HmKCQZJ_eWL1iEePgCtscyOZuXuOmS0y_BO5SGjajTaIFCGQIFsp_RhPHHHGcor7Aw9-YxNPiZJk
Z0gepPQcoHWNKFzisLgCX3kqsVAr-WNKQ4xNkBc3ov2uQN_FxFi7
}

