sprite $image216 [241x154/16z] {
vDc7aS0W30NH8ne4_RTxEUpbR9klxU0D4v1quQizkMRcXXnkkBVr6jnmlP13lUKoaBMvV6LLhhqNo9fSVNBSxBEsgCVL9vEhJoRN3JarO7v15kMIhCzbBQt7
pU1AaybrGyxTa32PN3Va0kuEP1KkoVdaouo_h-TpS_N9N6ReapdTwvF9tO5SJi6Du6gJEUxgaydTcnnEmTKd9tBroQdPeVKQ_719rkUoVSWPN6qokVfaBZE4
oVjpJxJ8BkJgaydL9mTmnSdawfEvkrc5d7xDjSLgQGUk23c2AqxcTAzF9bUVJAuRScecKijYtD-VAtBhXlJ9DkOqJ-Gnhid34VbQEsmgaijxu5kjF9dWM_Bm
GhOvdyYcIoPOdHnUWKaUecI2AHObrq3m2_BK9lTxgGrnijsJhyevroN5THW8CmEERQbRUV-dFPUmOXaDx8YYSXBdz5x-VoMvkn5Lt82bww7TowTy0pOxDB9F
-HwOhSlXaQi3TpDEf8WJ7pEZb0rNrGfEPknTZfjH2jw0srJQP6PLA79GmmP9EB1OBwNJAioq7H4Pv5TWOocJN86FPzXAVWNkD9jGBqNCj9cfu4382lwILd_3
tMmoqwbKQ3EZ08SnRF0cBUfOqekPrJQLgPfPFyo72l1ESfh4iNhfPbNPozJfmCCZA_aL-FJPz8OCL3NJKeeq7E5pb88H-1zTkZfLkoocXLecO7naCAgV5ltU
QocykdH5q7Y6hUGpuDD7rHkoJirDAqe7GbRm8R3ht6_8jQXPWsj8ztBSg7RwhI8tgavsO63aW1k0NHztJxbEmB38IgQ0lqIK86WOmrRmkUezhaTKHWloNhSv
3UmH5JMGOOFC0uU8IWnvRyZAdpH5Me-eFB8EyNXTbu0Q8ceev0IkV0RE455fzz8XS355oXXHuo0htnZlwn6r8E_yyQAS4fe40nXs0fVz8u7h4RLlzrA-EzuO
KRj6LYHuMsAyCQBooBl3rP2zkRtUfM632RK4OIQYLBSsR6L2Uav3neWAQBr9mh0ttcRK15eoehgYRuWCvgh6E_giUWyCC-swZNk1VAD9lXvH3cmcVGF3Lgu_
tXXH3cmjaL4RFDvqrSX7b0Wh5-3M_z2mTODjJZN9roDAs_ai2_0Vt4k03N2HgXglHvIKjW3_u5vO-V7cc-Jx4TNx5TXCrZTi1TUg6lc8KWSsrfNT2qofha0R
8gePu7wz1dB4jNcLyUOZIdixDphmAeQjzxncQrMDV4ILipZmyo4Jx-EIviGhL8ryHA4tEl1pP11lFrvRjC5uOqHfhy1FoChNaPLC0VTrnvi_zCKXKr_VvWWy
vvlaIX6LHrOG-aRo6W2RiqronOZA8uDPPDo3sYzULM1UfKckSkWZ8Pf3rh38N0G0QYiqoPKEVIIfL-HNeiYyRPW2GBfgh1zHKVeTsFsQo6npp5v0rT9DSls8
Ykf494OXeGkI_eGRiyWC2XXTSjxyHuaZi1a3CIuoAI3w35aPPAG3puuUgyPUzhhoEt53qIx1lPxroEl_0CnkiquqoSqYgflPT-IglIW84KHay64MGQ_mouGJ
LMEpY6gmHVgLMFjKIrT2l8aynlt5TcVD3foe6fj4L3lB0jmH9BrI5vW5-S7ZDP-m0VgRT_RnxahdfWvSdrnpAVqAeSkK5-vepLTYe-9cpUPLOsygSaMMI_C9
1n529nOb-2oBPWAW9R_-t3wYElZuTEs8U9H57aPkL7F-wy_j8wfVpXSyrjs8WmnGB9osADqajwrUljSE_90PZu4L2Wl0zRHp-Lut_7ZnYWAWyDSyhrOrrhyE
v84zZ6QpP9FSL_NA0uSiib76cxyEV0UUZPv5tYG7qaULLu5jKU9ejVE8UhxJV4ISE5eDiDSvuDc1lKaEftC7NvomDyb1zL6LBm3FvbLZN5q4J0A79Zdoa9a7
Xezty26dWBrgZAz9mGmmfjD1zDb18W8VRhnnhnc04R_-F9G-VAy3y91DCjyr2PSui3V98-hSbGp0tYGFgY9AtsZ1q5KZVzdK05nFnzPd5LKL1pxoUEClrCEh
nl5rwGjmg1g7LkaYgAV_aJvARwV_Hdy3
}

sprite $image216 [121x77/16z] {
lTPPhgKm38HXPk9oEVjVReiqgXuuHz55uFyEhv-25SDmexcKUSXltW5WdxFPWfReHDPm_YjPz580CvoPYKvWeKIdikgWb_VKSJ6nYVIuYktGYQneMz9PqUlu
7Bk9pQGdiJcqM8XDfCKYbPvsiRVexHuzYts0pcD5JyciQ8Z-oUisbTRh5i_H-tJZlPT2YysbzRfzYvuxBw1CUXQRJ3lzRVVprx0VPTA2oJJQ6YtubD-dzLqe
-AGjasumF9rki3DCDBBeGpGYa4cRUO2axIN0DDeC389qnhwN2dTcq0QF25hG7MWqtxvROYCu5P8mWdl1YtTBBAFbmp3Ze4i0UuD5l-4oGl0mh7vOUz39jsWz
PS57uzui4opwwQUiCFnkicPHYNw15TnQG2LPz3F3LJnWjJdfLngmnuQhk0v_DPMBhBlru5DcX4t3lytsZNw6rN6lhVuahU4gHfJnekfgiKFV7sxuSY4letRu
FLhizRYxZlkf1N7GSEBstJBxm68UEcrE4gm1UkTkzOShTnlwZOLqx7J0-MFQu5SMKrVLrJ83oFwe-rSegEFsMn5qC09KVThQK-wiZ4xZnd1iBhXFQxYrVbuP
_NIr0C6IAVhBSAjWhOmVDYFeCaMJCFi-t4PJA-DMrotQQlJduTPWq7bT6VtwMpJeRFJrvbR1MXctqrjBXm-OangrXjlWoXfHBolZLWlOrAX1jc3cVj8QReq8
DhQ6LiRDTBNQ2Kkj6dWff7kZ6tjoplDvtp_kzMfnWs3o81pEnkeECLesFSFgQla6gaCsJJTOfQ_3ewqUleF_1C5q7d1qLiRTgnNy3dTMnYDNwmhN6bKhuurM
_qTsZv0SuVFmMfC5_HCS4VlmQXj5qn5A6pBZq8ArCjvjyQ0BrbT6GkFvl05zPMGr5KQ3zPMHrcmDhhuCsIq6Q6NajkBET7y1
}

