sprite $image64 [130x90/16z] {
nPa9RkmW38Q3pMf3xd_S9yPfJPyL3TK4QgtLnbV_YqVACJkOI_Bk-BE1H5I8_Wp2XKAb3_qHX2zKT8XAnBq2P1e1P1Cvm3O1ulM-WTYaXXX0PxSQc6_ULpMy
Mvr0CtOHiDC0Dux0bGcSWyZ1FMy00x1532l0VWQRmFbvoX1U4xYVGHFu0KF6HGPOps0Jk5aBJU133B3R09OXkj__27fsgFoc9r7UVvp1Bn1WXHqaWSiOefki
O6NOBiNmy1z9GOAmbA64DmJ2i5IA16y8Q5pQxZKG4TCEAPAx9KY-i95YOoY8_U42RM0WYZS4GMfnWnqemmr1xotCMzRWRmXUQ5li84eO0hqGbc6z4iH2XTUL
N9vCAcZwODG6o_9s8FhPJap4MQWSoB5SBWMbaK3sFXQMYykJILdVksB8VJDgXxnQ2YgZ7oM6NFp0u8qTrlfHziuPHZkiJkOO08rXTChWLXUrHa9Zg7Pm7GMD
7TRse-oT2ru8Rd5HAuA9OG91WCL5RH4aXce7TxYbTziYs6HADXRQGH6i7RB6TMbHMmIDOGBZa2KCP02qgAEMzp8xKAtcUMi7yGCka8AuDKEWUn_jW4kAcckp
16RlwKgcTq_RWVhxJVv7E_PkW-iCzcxJ9--VvFteH3jXj0CwXAUAchY_NmEKLkopztVR0yAdTb03j0InCVgRfs_kTa30Z--s6A2Whwyb76y7HOfm2HC0Fofg
4O0zKakG6k5R05FKFhuAmwHYNe2pHiYjOAZLOva0C7VxjHcoKimdC3RsoAs3J12OkosZIr26kGIYxs-NCyCBP0x05BKG68O90mIabY4r5f2iJfotWnBCha4h
E48wgHiWN4iu9rImTziD1Cpyda4D45hL57W-sK-zR8lQZGJyLWeHWBpi_ImWAJXRD2_Csy4fWQvXOB0932XxlrAGsfbX_bsRp483WPN22F2rznQWT3NgIVZ9
zpWTvbi6VL_Qvpi5tlDPmuSVXTaG63kG6a3Drq6w0PBx_BiiAy7D6huh65_cqnIS1HxwDYq4jmp4UeEl57GrvX8uNzJy_mm6g7A3Mz0AfhF6uxdnXg1UThWg
K6-mWEIpPNSyEVW_GYHX8Bt1ceBO984F8_1F0aYlFLmL_BM4V5Mm9F1fX2hRluOyvje9-fFrPJunW2HmnK2fN9CdOS1OC_O_0fQMlrE0MHAuQ49_4AAuq4Ek
2G9A1N_TWdgIFnQEIrnVsw-Kk20If_hZ1ai2bmxashTVQf0Li1X0AbWIk7nygHmXCFKLXEi6rmJ99d2X7He5I3L3u5eZbBu4My6hxL0GIuqGi2_1qzcYEtOE
TZk0PqhT0Bs2uTWzdheT8YUjuDtZ8ZSA6FH7qFw1L2kR2juxMEfl1FW7
}

