sprite $image310 [232x334/16z] {
tDW7SaGX30HHij1-xdzTPrjEunpOVcTWgbMaZJMtdF3gz2iziMNpEos13G-p9AZcJmtaJClqW7syUVYhAll91YkmbWJeJ8lvEngh9Tgih65gbbajqGRWo0l0
cNR_a3C_1Qj_XMLMIxGEEF9WCst-FLREvCZxjf5PBT4Qh2LQPGrJiq9hYPufgoLQOp_PC2kh9PfbLakqiUM70NIcpV_2B7jz631dcit_K0SysOrFmUf_pygk
Hzvvdu9v-BzfW65kTGhMwV_C2g0bUvo2tJVHQ2tHCsMrHBFCQedMKItHJgIMQCVYj4GxhRKeBT5Enxf27wOVwyRFjMJJOTvXjYI6UO_SacC5SaiU8nnv-ic6
z5rR3pEmXnceBNaEUEIzYlra0-73G3_Pm6g9nZhoDFOm0-l8qrWjqHWV1kzZV1YyZzKIZTKIZTKIZTKI3TgISCdUdQtPYeDG04uq3W7U_tLxj6fLuMw-lTN4
X9QhrhhwMzO1pHdUTiuTjopAmomvxnmw3oRAwopHvM2Md7EE7eA9Sh3adN1w2IRATp1HVfOyknmiUKUSaw-MHNcT9ReypXBREP1JfNOoaRTWehvRDWtCJDw2
2IVM7s98tRGid5X_Y9YPo57Bel0gtPIKvU8QW5BDwq89ftvy1Ac7OCB9BwL43eAfdCmlcvTSj2oSG6cfWvPLJcuXfiHIsWcKZgaB9PotnnJAeiwROqeY5Prt
pHXYgUMyCwPGLd7QCUsqPRMpUaoXhEwi7rDYgU-i7rCewpdhDo-9tEkiiWeIontEsZ65yZvd-LMGH5fnsZ7jIWbdpUObbhkTDMOCbBSuAyMKvAOAYQ0f7LDY
kQkchGrhn9JblbgP83qHqrQLS3BzBJqHqxQ32US_KYeQKs9fmSbCHMCAvStE4yqBQQCj2oUaPvgtPIMSfs9Aa1h1RCR9byyOA9jodfynf5gsEUVrCIMM9ft2
VEMCgQvSrZUT8jV5b6ehSmppsqwHQs9QNSbZ29yvYPZFhuALbNC87paPm_1mJ8bhEzSOFd9-jo0TZoc9L7Rc8OHtdJfeHCTYIYoLdPn2-C2feVbGJ5cajdCC
7pgHiyFDArBV6OyujHJtg54dXGDEgtapDUbSZZdjc3ReJ2USHaoRSyOJJYkcZJafd73QCMtAkPnmcbByPnFETDPfnxGPPppdXDHgtlfEJillwt21qvunLPru
-nhaPwt_-k9v9vCHqtfEl7tnYtYciqvxnb1DPnvXKV6Cytcd7TDgJhnznNqyqoLEEwPLd3p7y5sqY-ToaTEUCIMT22OguGVJ9h_AQSUqj1ElqhfnX-t6TKvx
5Qpg3AkEvwLEUnMiwKmgdklbJZkc6uwei3FmxtXo0QSHKtm0fiBELSMpWDEUCSB_WAMmSzpkRsrSn6d7T3ibA-b4u-RjwHPmcZ7Tb1MSYuXywxYKKqi9zqIg
EAFWTfGoJaXtJfQopW6xdo2UfPrCLCH9opoccLuuyJ5e4iIpe1FIgvtOs4VQEN4m5e7Zeav8htHo2gX8EoSUwFfrTv2oJaYlSwf_c3IoTlBFtIzk7Lp9oNIH
Sur1rQYTal3_W13F2axKIIUDOLzPErSqxe9uTk94C7KbxSJtsfGGpswSImmlA-wS4tw6U7RYp53g8kqa_UhIZPDrCFUC4LSog8s-4oVFgbDJ-YcPVpddtG7P
83-T8xVfrBCaJlpFJTn9EoUh0nKuOnPfqyc_ct3YtQ7cg9pw931_E-D6Riw9JNpVTD5mhY6WvCkPMBfmnbK4DHbEYVk5APD83qxTTAlbd8pppiQTimwkvMGu
S-TEiPmo89vUd4avLLTtxuolzmJLrNFtpj5oIjekkNCd8fYL4usBYNcVao_B9xzqIiIIvy8PvRLpMKGyE1c_e2edoeCpuxvZ9zwRoRCJi2YUdOZdvDovecr_
EaTovXpmyGVEk8fqwcJbLFnLu8mpIxTEWVF5uum2Ps8HRyv5FqwPiuWx9s7dG_bpSiIhYbydFkacyUoaBsPapqwS3sRnwyn3K71tJdMadSIha-TOc2dSW7E5
4an_JYZ1zEZKH_N-dGE9RoVE1_qx4uluTmvPnBKJ1_V-dHEB-7UEBEBV6RE8VsTSHBmxCKjyE_69tRTp5N7ljEjnFix7-JWVv-Dyd8_pSJxEn_au7-VZV9oF
yt4-piVvE1zd_byuQGo-dVXR6lmxbnZ-mobUdFYBa5yxXSc7arC8XfDp9dBWd4EmdFWh9RjsvXXGvb_DrxEJHY3Xr58yqjwSc2M64r18UtGk0GMdBUtFcOTW
E0rfLqvAqDbEaKCnXVFcMVA-auXKJ3jnhZ6yxsJG8Et0gMU9xTGqohXisicJnjbEJKDCctOkGBth14t7j3qdPia19sXQsfeJmJpatDFWRiY99U-8KmuqxutE
9OQ3Jc7G3EdDJhJiKIU1PiRqVYUd40uxBHhSjpenIquuGJDZUhipnt3AQTDmUPSJmJphj6culC_vPtVdeHDR3CN0xILt__ztNw4DdHiBQn1MePSZOlcCWSsA
B0auUzKgo9owCUSu-pfXqtZEl7n6SNv6DcLEDKiopfx86EOK2eFetAuPxUsB_3vLA0nGmDbpDdswlMoniYJax36cR7fR7byh50OeuUmvcrxln9nobkIS_V7X
VTBuxr2XC2XnziU7jpFd2B8auEoLg-12hXXBNixPSvEIdtQMv9ozuYppwnKbItBEdhGfVtObP4cPitdnxhYp6GbPKkPizYKs8w4mA73s1wiWhpECsUTitfVh
NEjPOd0sBoxaIhTyzZXx1DUvfaVMvMpoKoWCebnnEVkqAMXCn6UNiycIXhRd9cVxnaIxopTnzXNEphEagSDmEPibhwsZoTcKptrj9mvlWRCf3EhQNISERy3P
GPO8DWquEouC-Ze5DiquEyyIFsDkjp73sHG6XlPJDiqvcoonT1mXZFAge7mMj3r5C7edyhDbJD-cv6Umv4aw13ObFmjPegs2EMVdHzOYjZ71sON2GB8fdDtC
4f_OuEncOU2lWhooQKoVsEYfcrdY4nizTS-OFh7zVvRyx1K6latvUx1cblWPGtus2mEVsE3iPfRun0PdDxF49pOukrKO-3P5_3nRMU9dp5sqC6UfCF29RR0d
zCfddzYUagMO9RvD1tj2ip3mRSgSlIpnLq5EwrYQMU8JszEzmSUYCNrYOyvVgECGvbHq4kPqCuQxX9lootjXdLLiAgop2h49wwoWtVb7f-PV
}

sprite $image310 [116x167/16z] {
xTY7RlCw30LWoLiSx_-wDvQRWvHmobynhRjwCBhpmJobR2H5PjpMdBecB-MHkISv5zfDsiPUuhXLiQhhq4CSrbq4MfRSeSY3HEZkMYShejOEHIAejKEH26gz
Rp_UgrDuaNQiNgtnOxszLko7ZvQvIv5sm5FmVdGOC8fiG-dAtcHlhF6rJexexKryaV6rvkM2YECmVZzyTUeoLbjh-7xufWGVTBx88g7xuOVbaJv5OgmrxbW3
YsGvqc4_ZEYOqnPP9D9hFrxJQpzUqsK_J7hiXqsF8dqpX--7JO_ziEauLkJU_V3Dw29zSxoxIAHZaKYt8gqv1XzqlZcCAtSPAyoyr87G_MD5fb8rWdgVY62i
n4Ht5mcJ22e55UcRK0dgRME5oL29cMB6wfkWK6luMArfrI3HDqsj4KNwPdkjZkYRpRMII81frE2n8WlCjbfPFizCC4zg9GeK4IAB-WCckPR2foePDQP8c6nK
frQ8Lqo2wjIAiSQOxDPwPQnwPigV3FXZKRVvp1GcJ-KFYrIQqdXcShqK_c70_A79Sqfd9jfwMok9V6HgoUcDoUIeygavftScL3fLwMDJnhScUeCQP7BwqRG3
lcJgiqxFj0F-tDH2nyV5DUs0wJDJUKwBFklChibaQcqsLPO7CnnrvfIcx9gsrcPp6zAUeaUTUKcEULPhetcGQTQZpc5ppFDQgycDPfP7feTTtflEW8aQpRIf
I7vye7UchqghEQdibyZ5DwrAVtRUwbxVDpEphYaDuffMFKpoJELj6iRbQUPfHrVTwzHMaud8DrNMZEEcNkTMlwfrwkQRDhwfPKnVMVGmQTg7kslKSfs8OofD
2HdaC7chN-tVY3TLblGQqcgIP9mCmIOEkc7PvcCf3xFeX2Kj3x94cRXLvLLKjQBhqoo7oQBR_kD0SwhpOyNj6QOCptwP8OQOzJbIfOPVpQyHpE22JVbAVkrJ
gDPvjranc3BkFSkz9jSp5hHkC-lT9k5CgAO8nDjCtN3seSSxJNnU3ZEJT34vuxuoizneBjK4NqSw5vKkvkjTKgMBMSb4qEutbP_dUpzppUPizUA8lZcCgP4K
lcRMOB0zpObK-ff3WTZ9nAD7FnDth6xcW29xcSAYqiz4_eNch_bh_fg_fl8pH7rCbQNpTQfiERsyRWTJQKpfnQH2TAlvV126oKHKeDvXuYswPDyffhjCBKCw
yhrFN6gmYRVehCb4K8DDvIMzX96gGGqoiH-d9ZJK6cFYlTQpsK857c4geyWJKt2Dm2-RAYZoVPzcmDTCrMr8Fvb4vXhh1yTq3xhJW3J_ki0Tqpde75FCPA72
R3teV9F0MFmue_YZWyxj4up5gS8NziEQ21YBru_SlXz-dmo6hCheqnVDVZXzlflipZbzEllXz7bMAwFFjltm-mHZyJteqzqFFtHspoPRAw5FVp_yCD7PFViR
Rlfq7WJyh0pLNAFv4gQx7tx6ZVb0VpWKwZUS1u6cJFHTFS5hsyw3G6CMme3DDNfdFFQZFGDgFHsm2FfqzgCfOx6rFZ-WJtS_sZD_h_KLHv_EVhGdB_okLlHf
7fG3CcodjT8k4Zj5njMAUpPpP96srfC15_I91u7GPBitwDCvwAxNob0FajWyA4TdGgtcdkqy24JLYdksSz15rrgtnTcFsBqvplZ8_V3lSjMSjwc3YBjSDOTE
8lP6L78V3xKA7iwxPIwnLVu5
}

