sprite $image335 [173x248/16z] {
pDU5ZSKm00HHixr9t7-vnxGwVORCQo0qsiXX1tMKOBZoa3HIC4ofwrEB0Ius_Qe1hSYC38_LTMYwiSkGqwqwfC9Z9QURXWmrNP-hmnezLbTmSqLEDtLTeaTu
hAuIv-gm0e_LZGGlmBK8c2jakcNeLYC3v-gmdW2nWj8jkgSAc2j0kWTYPQPRPSZf5ZrEUUnH09nkR7gq7k6nkagSgyCASguEfukErIqhRQuEMxV9ZTKjsvmJ
N83VwZlgN7cisxpwPhEU_be_OUVAR_KJVgxc7_Yv-Wi-LmuUg-FErVmF7gj370KE5-3WS-LmiNe13ZvN3ZvN3XwhWy-LWyVg3XR0YDM1ZWAdmMDryBboyBbo
m7_hOV2vSl1OdSNAcoi7dgl3DqkErMysnh2i2tEkNgcr4zr7NI20uuASSxp_u_uFngbGDIMp8N7PoswkJ-Yt8pQ_VXq5H404U6kiklHX400HuQq5oA9p1W0A
zvLKmGRn6RZsMEtOlbLf0LurhXXAmGCRPJT7xdiA8FbXfDfXqTR2-bZ17mS1wh481kxoSPKtNT1XXRSiNHkLq_PPjSCQMbW_hl9fTQ1O4tVzk8BJceW7h27T
XR4YCVd6HDW2CezOGxhB2g2q0HTDjJAFM4CBwwZ5RHkqZTtRQwYroy30NHShx6rKjM8zGDxTzGFscAwr1Uj1CCfSpTkmTkgn4-aQ2h1ZmpQk3cjeOK6iFNR_
mg9Y3Tm5ume2_iBkCAFLT1TkQnIGOkDT1hw8TZBTLTJijX5RHwjls0nDCT_2adjh4c5_cRtVOmRYzb6BCe4HVt1XZckF5IF7ArQNOAjY1wvzZDbZTGzOGcP6
gK2nFTVUWZtM1omLLvXH7siwBDhJjHSWx_43jlwdt24vANR4_bcwHYgpRrYwO4iOHy68jQGxKO0L6tihye0rjZ0nhepOV5ftv2yiCPcuvd5LSg5RRBjq-B56
ObtumJAJ8LqZLKHmXssnxXoE12hp7POG36FCzjHoIEYA9TSgO0h_cmln7POGG9JJBG0Hel4B8LdbYgtd6Gj5UiKATPuh8y207Sv-OSH-xW7XANIyQATQG6O3
zb3fSZHWTwnEDlOPQ-Ao0Kjv-reuO7Lb_er5c6h1ZitR53RG1FQMkm8RAeGHcyS7sJdiV0jsh6yJQiJMOL-diGWNxfzZgSVAc0y3bivUYIUm4orOiTN31IkL
qe7b8zg0pBFOUQvYwJSLmxQbUwnJR9jfBWBp57OYNHDMxgsURZFOMR7CHCHim3waQy7gWGI-iA9C7LQM0VlGWW5BJh1fmEeq00FMm9t5mdd06h3v-CzT_ZLW
vzATnmfA5lHOFGYsIbmcDc2dDtSU6nGRUom5VVV35f7PXftdYXLfBbcHAHR3vxoIWDcAdM-1cG0Ui9Iy2tGcAqR5bkpwCu0TEyybR7_Huq5m_oGRjOFXrEMG
rs2lBJJlRRFL7neyalLLEnYmm3QiQNE9-GOBU_--islFqavUzrXNUI5Mk3-cmN28Bime_-voIEcm7daj5dzWvHl1woSAvP_-Y9s8LsCHdx4Iwx3mcBBCvTZg
0nk0UJ5MrZEsAD8d9nifKtR_j14QrbTYuuA2bdN5Qf2ka5o68rb_jf7qtleIR2Iz1DdiVdcvjxu5AwUKNJQMunTs1-QtONLZoUjGpKvZVHaMuwPNvpUiKM9z
6RPyPgtdShxtLM9z5xPViiM5MDQxiNAJ8Fuhi4bYU3Ss5YVHjXUlnWRiVopFmvknMOy9UkjzCxQTgM7Y86Z2rbNOy6_xzg7ZE13307HBweZw_y-zHbGXDqTd
G9m7aD1irBTPWlAaHEOEsE27RNjWyNr7xe9D0zM3jKnZFyS-s6laBbYUMhR0FX-Pcs3zqrXEOv_ROXlRsCOsjh6DRMnZHsCRszZ6DhQnZMriO_tp6D7Onjxt
mSRbOmyiVvnHiC19iVnsIC4cJeIjNo6ks1XZd0pBhxKHE_b2xpcm_5fRmSfSFxP-txrYgrR5skkAymeBcUl7igvcsDIuVYphgapKdXr3uDgnhAiPbaP1wyQo
hgPO6WMk7GlMrGGhSlrOiAuaR0nEkRHYQrWbB03XnNLYmR1As8mXPC67BM4Lsa3W4Xi1msxLiPpNbrOiT-jyn3BWfG_BtQfXTMx5EdQht0O2js0DTQMs0VuP
tIY_kpNiLX7x6oIzkBG6BBjLRmEDcnX1hB6krjk0LuFtCDQL_Y0pfbeEY3NKbOJ5aHSNYsq0eQw4DX2u0LQNeQvaB7njeDULtWQYDi6_pb1NCbRlBjx3K5So
LkSMh2ci5IjmNs_Wzze0GbYNZpNr4cm3GrXrR6Xb460Tm11MGniaQ5xVhVfSnj_oEgQNu3qCktKsj_VAWFSuTXHOdy_xUzn8OWrrDPllvt5kW6tWsArwTETv
hMrWg2iX2mUZIsl0K5SIzt64conaEEjAZ-xwiOPrvPkh65rUWzZreu2_njW6GbqPvqkBRcGIAuJLEPSINQ4DnB3wepi_rXZgoX1TtiCGLaDq2tRrA61-UEIR
78RTQdXu1DjWBQp-w9RtPnVgohs1wx5ceQwyqPqVQnPsgpkw90SCTULuUEInnd0KC4INnneirvL_0rD9hBskriyzIIpMwyg_WOczt6jOJnbTOWt_VqTqOS2w
DZ2nC60TqONXIS2sWM5u4l1juF_o9F0J
}

sprite $image335 [87x124/16z] {
xPI9bYid30Klq0j8L_t_Vvj57CT3fwquRRA-gRSlKqUK4RXBtlUCsQIrYRGjOIhBhzBMf2sOHzv5cYDI2-QGjYvzYESaNfkq0MdhnubBbPEr9vuJTSGJpudg
p4YydAD6YUz73HBVZpeXSTfQB1qJtuyQ9xuNTKBY75oge4JvuqszWJ2CMkz9bNRdKiKepIpSr1i8xLScHrNhlBfKxVRvdObHnQMTgL5VQvVRKGS-sDGnwiYq
g2F3ypT5waoBEZ8twgZD4oxLo8HDlTQMHNJc-PsyYuYgJ3k_m-gJkdYEL8MkLHd4dqIbSKrOkhOBHLG-Z4hJ303QjQeYRmyiVEKqO_ABnOTsA74pAdUkA6no
z0XdyRsRsZ84s7LVdzC-IqI9DJf_HjhHsGzMgXCdZiz_gBXsHMSzk3sbKOauAhRZLsr5PplOH2x58kz6rHtONQkjDbP0ZABguh241ajLokxp5IGUZLPGpDZK
lO4uN7yckBP7A2WPKDTsqSl4eXQWNxM-OgaPkzRuKYp1fMhB8aJN6ZFA1g2eqRgMAdgTM5-FAWk0_Dkq2gosRysCvjf-LBaOMCcNmsvmQjSkMW0nEynvjhqI
cxtIIa9dSwsp6yb1wzxsknAyq7evsu5KDRisLxTkvenQ5qiNnzf3nCmtuDYxLXEGgrrennAHbXkMhlMVQq8ssIfjWEwu45zhQIkGzEZQ5KaIadzI3BH3uhEM
_bC6K8z-fn8M3X_LfNPChFqcFANk5G1O-hG54AvYJgWTIz0dVaYtL7XKf0ImmhT_zN-8jQFOV-4pGksdNx0Me5NurDQ9jQDtQDkAUtRBQ3kmk7QtK7if_ghb
2Y0de2dGLY1jmABs6XLznLEhlaGx4YlWQvjAC-EdseHyMC5sh01IGkhddw1j6KYQWPLrfHbdQ9_lrNwOkNIIjYGW0zgLaxJ95xP7dQ6rhirsL62bJTRIMX4p
JjVIfNErnPp9sfNpjVxpRAtpxz9-Qx-r-b_JVck_jPolTRXDrzAiPZmCAXEqBfK2uA6G9fzgNQehuDe78lBnjDmJlchPlVA1bcOj0vrXLcaIQ-Ee2t3MkjV5
WJQISeDpZk1Arz-PjYPSQFKvgoU-q8PH2t2bTUMGUD36KkrHWmX3Odj3-umQH13vEZPT7UARwaGHP4pSLD_Or43Bywmk9lMTJGqZd6TLDQg-iQcnzZnhYo9m
Y1f5ECywHeYZnX6Q36EJga7KYALnU1A6nF8YGeyQiugBpxEwdHezVp5fLrvUNHerVFuGawjxpxDwX8ldBo1EtErDgU7pXpk9FKBq_Ft9n8yI5DNW-RkRk0br
UFxkiiXpu1uXUFvk9lOcmQRUJUntrpTr1kMHs4SDdh-RYSsqjOo9R4fL7eAfU68rsp2TqZwu03y3
}

