sprite $image126 [219x159/16z] {
xPc7ZkGg44KBC9WA_l_VVPkGEznfsuMwD3rwHt7p7fbxAO3c-P_C8iALVXnfbRzmePz5bPqrqS-XiDnHwOUGkpp22_q0KXC4P_fqAWiW879H8SFKpovypATl
15MEwPa-ZuNb52rzQk4Vm_MJGnOVkVZ2__2DeB0uQ9-x5Zy_SbNySFwyml_yo6MMQUgF21c6owU6B63s2YZymCZ5hyNFZzmuHgzrZkQ8N53XLveZoorh_ZQ5
FwzM7BDNJCZcrRxHx5L5tg468XTV-5Yjj8kKeVOzDeAyVjdOpIxIXXgaKYpjnV-XEdUn91XUOe_HRr2ZwECEBlmujH6veCAFL1lKYCAFLkCrOYCeBE5gd4Pf
zHnmRngenkcca5iAU2WBKHjcknlNWC8FKHjckvjm2GXPXDeAXeGrlQ7muzMqesvk0OL_LcsjET4lKbvMlg8crj79W6l4lUcn6jUJHmP1s8hSXFCR2l-gMazW
k3wl9hO0Dn0vRyZyQlruYLVdQRNE5Vwi6fyu55Lokd6PBto_MYOC-zI6sw1dvrgSLrk91kKN-BzOPqvKQt8L_hpQCanu-yrDbVlKiZcEExx2bvRubLgYFoHJ
bL-e2VrZzVpVigdZTSTN-8rek46r9mzjutSzgnLCncQth7akPDXik64rK1h3urbjWrW6Pgvd_YgNp8RRQxNbkJFBwVCQCFCyynU-PZRS3jIeomxRzWixgLQ0
6OQBUorYjU66rJBzemmvqRy8KFEQ7My4JQwXSkksg-5YJilgEwzXCqoTB7pi1jM4xYYL7USrR8RX1U_oCsu5gccb1rBbw-SrR8RXV25aFRzWTqDgeXbs5LR3
Ri3iVEJgmM-bKsJujra-VQWHmMx3x3prRE7tcV5JRO43_6ariKtbAbp6Gzbxr8ORsd3gUJLHSR1cOdwRsi0sMUYHVahD3pEnlb5jeBP9otHBFg_MnO4niQho
bDgWORNTplf2EtnMhLoR9SOinoJw2tafn-rhCWqwtwfXEzls4tyxgLOkpqciso-OLFLGphvatSsiOpNXVfUxPKm_5yRZAsuijlrJ6x1SfzsOoRFQkkJy_7yU
ORim7bzm-oSsrBnozTOCgO4ZZMWQMvlhEUCuP4XDvHhBhHbIOt0I5IaNrBIVTHiX0seEERunWsg2RXsPBgY9NN6p3QYvLgNAReRL5dJhUAqXRQ51FLoBGCqf
fvQ76LPRQRWzDmzFF6VWjNYifi8Nt8OPLDEqluIpYF1-gvRKzPo1OHb2GCtxuMoOGJLP2OAlMFrkjc6rEJcLLsgM2PDiwZa3Xmoh-LSbLXieOMJwEMEWG0kh
OJc_cc0pzQaj1jRY5RK1pwk9Qg57ifYur1O3OWur8ETG4xLUxiNwfeBK6BCYin4olveA-zK6jcclfH2bKchNpKIWca44c8sTpAasSAZ1azfVpFJBARiBe0Ep
iHRzQWDsg05KTokejiepZCqOY7dKLDYdXhdorJWXCzRjc3RK778HQXsOiTZcLCDmgDf0vSbiYFdKC1olDjo66GuPfXKzZt2msd1R34nLRZLChDfmgmRNebyD
m-5gedQu5lrg3EJYr4w8-TLAwI1oSMh7EvbVZMWHtObNi-rzQaGWSa5gR9k3bjYbfi9HQgoR1or4HHngGmwffNoH1DNsgSg1DVf3kwWsOAZcfyEGUUY91gj3
RSYzKOrzObBeXiAdrTQkEszLKvUOBVJ08YVLsdqwtwTcBhEL0Esi6b55grAtINH-BN8YIEfdrOXM8AUJp1V-GbzI-AmQvQFPom_BvYpybop7Ql2tJhlD5puT
qiwe5Vf5rZV8UKDMw0I9ePhSgcd_8mZ6apdONVWdAGBKgDsgATClkWAv-BNO271kLRRR1ct_VdtPFziE1ulXmiVWsKlAQD3XcTh1O1aLCYrqcSnwGy_ZSpOQ
G3KD2XakV5_arhy_TwUM5H5U-0D_vEgkfilB4mF757wc2T9Zv8QQTh2_--JyKvKJF7lrEjJ-kAtpRuuispiB_zBirSPItMi4my65Fn-viH3AyV6S0mhV2pxk
SA51cNe0SHP-fKFy6q5FG0qIMFX-AfgzgXx2mOK_7pbPndpiaMCBA7p_xANh0imGmf5JbJzoBW8BtqzJ7pn_R_fsqgekX6VMOgKG2dlbs7rl6iOYwYAiyECZ
Pxx23oPrZrfKuST7pfmFPV5KXrfCuST7plptfl4aTgW557xux6LHKrNyghJPmezdTQZv2Z-Up0wrWCAFcxtCyL3s8P6pWC8FEEvur1fzMmexr7o57y_YLjD2
W8-9d4KLVlpiPL7tfl6pbqKLVlnnnwAcglZ8MLJXnyzU5bNuyP6pgCAFNvKMTMyQFtjPLE77pruMTMyQVzongCAFZvn5JLNnLyqMLVZnaREeUzFusSjY2Z-U
fhRI3oLb2kG_
}

sprite $image126 [110x80/16z] {
lTM9SlIg3WHWC9j4o_Vz7_SUmw-9eyAQSk99rvPrlW8r47wIIBI5lqhf_wN6Fx4oen_Xydbhe_uAfSzQiVPlQPySN-5kyhdn9UgBSFx89ZR3V79yfJjfyU7M
Tp_bwTRxuVnqw_tGzj0cSdeJqjFmHEifl4dh3rncctxA-2PjgwHZGUISXbkjLorsB2DLrwQNsQzQhnexvM_EPNQtzRvMZSRW_8lMtzBGOeCpFk-klw-rVz-r
UAFrDxNQvs-vvw1ukT7wQutA5kEMAf_N1csibA0wvpi3ivgvVoDzQRbLJGk3WxdCdDOxMWqQynEJggV1RxslSJm6M-lOfEneIV-rtDd4tA2QLYuB83H_f5hK
XBcO3FzfBxp4GcXMQs1c79z1fvRy2qWnvp9BTFqaDz19qtgmwQIk91fCn-UrNZDsWSpSmbQe0ylJdGVcFUtcccgaQKJnW5fK3KMdd6cf8HlCZC-sFYyAf6iR
d2Qlj8wgc4sBYzPVLPQr1kaRPxKk_IfS2cvg7U2MvjHffRLB32XYEQgdQsXUvJgt4Jx0USUNXLP2lj1aHnLO3wUKkGJLEAUOXuYc5uPgYeKrXtqV6cHwDlf-
45YrVfpJkKWwQ_NqlYqvoBxBr001BiyReNzfMJyBUUwaFTsov6G_eXeWQmwvWKyQZOkdjPQ-jIHkhyp69hE9HhlQpkE7gkcID1dE6t3UHAkvswdQIB8VkDQQ
iQmslFSQsXR7tZLyQONQwxQBirddWLdDRAUZTQ0pTtCh2pHQOnsOendFQ6QQ9wrqDcV6Rk98jveTdzLix7cZrpQAjMJdDZJh_Lm3HGAhPRI-q4JKkwLfqDaC
p5cRK86OyRbQCLfdo7wbxR1QY110OBIE9OPgDRKi9l_hiObOBVIX2SvQo1VPlckuilQTjX0s4bbeEZxLt1HxJTd8lkijbBk8rQICyM5wQVFJtbfImYiLOhLy
B5gN9sy2Vs3xtc8uHSTtqiQzQzhfn5iORy4aiOXgFBHSmmQ1yUvRo8OwZK-EIfInaqX1dtOFyZTHp8janYSenrdEn_w6F3H_UNxhdJhFOWYdK4j8MPyIt_DR
xoRny1gLaFSSU6YkvxR-RSfiHWl7uZRdQR_JUXjx6cG-Z5syfnRxZTQ_7r-2QiQxsNe_kK-lEq_xfUMqtZyD4xEUjub-w_tnBIE2NxJUFGtho2zQxu_Fr_pM
tn-Vf_cjlvz88excjFwvySa3hNSkCq_pM__0QP0dMkzVPYlDR_r3fq5EZxDj_VFZ4wVrpuzFthR-oTCWJkkV7vyyt7h_CdkwzVvbjgE4Fql-OUl_3m
}

