sprite $image251 [146x109/16z] {
pLZfdkC-2CEt3UxxF-x_Q3p4zL6ShITRVKpcLxGW93Rmvx39mpT1XVGVB7mDJ3eGDNm7N69uzHqJOtp5w6ngOU2lmgSUuI_AISSqGkC4vlQ9zQ2AaWxtYIka
CJ3dav6xpnVCj44vvzJzKL2tcL3V86Qamds-eEOJEp2KcVah4sD6Ejxe2txQ88Rj_kONOqP5cH2bAUoD9fGPcDuWcXjCQBb1-vr0VzOWXljj4qhp1irwQcun
eRv1ljlCdKvWha_CWei6LFWT9_3N9QqX73esSRyJg7XvOb6foBEpaXFiDo7g90sgReRoMvr0bZHXHyWqpT0pEVs62P54gCXfKx1OoOIGgDF7gBgRoqblDI4p
6AhhLbEGarVRJ2WDEMDGEenjKS-SO9C9kGbdfCaRh-PEi65YfEUS2UsujftcOz2Vcb1apcDEKO_VlmcMpoRMzi25ZbDGEWwR8GVBTHD2zSevAkZB83gm5-Ma
_t1Y0LGSzDlsSZ8p9u0BmQB2rOcPRjYYdDxSAVOFJ0Z2z5yLKYyddcVRZBHqOZgfGHxqT4KqqSW9nd9IN6hY1AicrFqweOC3BZzmx4ww3n3Li-o3vRe9-PWI
4k5pzkbn4383YKSE5e4GmosQa6a7Rfy5AMgJ7vbbDP2u1nDNHiOr0NIKJ4Y3woJDd4g3R3__FbW228IGSbumeTad8UMVFu75AMSsYvIAd7n3TrmIyDh4ucZd
8rH8c4R14f9bUtrR4eZmdGafyDDOJ9bpmx2jyTwrTugo7Q5XIKX4E3UXJXU4zgnDN91ACeN7yT3wRdHYWmeW4X7X-6spp-7O-QHVQeCxE0K5cXuigqxY0Xy6
UAA64rKlNoNDEw_EsYnneb2wvljFyRAY6U2e07kwiJiOdXo9wC6r-OiwKf6G6HmJSeCOO8WfDNHfg6Xr5EVQLL3Z980b2te5Q3g1qqyUPXJATMsF_V6bAQyt
Y050DJ9Z-ddCyywVnHNnpXC5nG5Cie9M6L6xy-QidQkTLo-rVJW2sDK1xC6iDOWNF565mSGY6qvT-sU__4luWowSx3E0UTvsfK7CA5A5eQJPSCxQB752JtNu
WuabWAdMkV8o8MRaMqRKI9eD1-lQNBnqpRxiF6RaXvEZ84zWm3MCi3yys72uTbqSUSFQPNnvY5A3c96gn_RQ8DkKmQvCHRqFu8JsVFYwTtaE0m06cH7ESjvH
RTvS1gjmFs3eh4s4-YULip0nXYajRHYrXfFu5q_3CJ-ogdVUiwJvxdscCWeJOpZMtQ1BR3XSMtFnixRb_KAZwC6IvWmCvU72n39LtszqQZcnuPorAyCfPQAk
Z-woTr7L6KWFaYV6jaC961Q7RSANsjmG3lzQ-HdvORMZgnF3v-i45NpV9jvvt-ry4y1sbCe69HDYO7aTeOQZ4QUk3Ezy4y2TQOG7BH8YVkkXGdEQJBux-7Fd
qVK1dFZerYnfSMBdsm0Tep4beb9SOP5LB1Al0pWQldlFXtA3aDyc1HsZCIVUUNlUqkPudFHvU5H7jpiUCd213nbeeP3UShAnbB7rpjU71ni4Zr6O69qEvM64
H0rIpQaEVpuoA1C_h0nYiK5CDi8GCQLXcvXJU-EQqU6hkaj85f26CGZJbDDevsqU1B1hZc8IDvuip4147QKkWD5oIn-FQkVBs1ObJITN3tEKyiBeof6XVzHh
VpALK_a4oG9Iy0QH5Zb5NHqUvz7joaE6A20qy1uMkVwxqH4Hyk7nklCB4wFpZGKPRjecIdq0du8kZjbDJ1IG31MMHiSkNLj73LmMa0oDAvpQ5b6U498YGmOV
th8JyD4DhQH9Y0m7Lx4uEZgE0YL8MhWvrg2NdG1j-na4nPjZWWrEm9_PfOcX41bxvOH2WzOsVfCJz23XvlWOEbtZH6y5P6077Ci9IUA4misn2twrJIG8Q1_K
cXC8aR4NHWuM_E3c-1Kde8zkZlrEW3S9QDq9PW9QZupTmIBS7DiXdvWRRexDJY3S7DiXdvXN_fiAjpZ1ziZu-CIyQ-FNJypLoBZF2TPkZZkTu6u1oS4Y2-Xk
9q19GBSxmPQRO-k9ATqSzpi1HyQtm6mKqBy
}

sprite $image251 [73x55/16z] {
hPO7hkGm34FZk9AIz_x7NJXM1CD_f_rPeamDeITQIevdoeZ7Vr2e1EhvjKy40H0vVEUJYIcsz0rM8rnwTIhz1ZE1RaFjUJQCA1zY5i8bghqSUJeJds2UAvPq
rOvAUCVY-rXOiRGhiOhlyOKDIxjWGdcTHFu5bifD51FuDb_UiDImM6D3FejRiPulPi8bmqVkjaGGR2dMXIyydGalHxiARv-4kx2qj2ezcmd7waZ-AMKO8igP
TxxdMBt41lWLgRXLYeN4xHjUO4dAyvzsebbI9Jp0XtnbmshdTHbh66-ikRaHvlhWA9njIojRWUdwrQ_81UvwBbDJZIzjM8nNtybszR8IDBwQAiqg6OJvxbYo
O9L2gU6aifu-_CNYp_TLplSCArQX2F8rWl1MWR1wNEnrwx9XeGLh3r7kE9olPB_C2oWKBXki3YpV5L682a4y0fNDgCZIY7tN58ZGFsa21_0PcqYkAaXZhqWJ
mN1EpVWMyTeHlLGH4PhFZAGCh0WHr627rN9nm6ssXr5H6LAzDo5dUz8iRJIAj8G3531sqxGPJSbYHbscJINBSJIzej4QiWfpI51aqM6zpk3jexqbgsYMCpmI
1DGBwwmKjHd8b0NGDwWRXJQTYA7JRev4zHi1o_pItsRnSXQZqGszVURP0z7chgbAb3RoJogiQMGPeFpfe-agrKiInd592MSLAHWzkVA7JgnX9PQMQyPjT_hR
wUf9EkxyYq-rxPtgNLvi1EnYYyJxvEFHUE-Q8a0ZypW9kllqBgJ-6MX3GOQygd946KDVg2qEh7IC_8lAZxIKaDwhRzowEa6eqaPFXfNOuqoXR5qsgexpS05S
hOXxwCU7F7i6ntAgyKa6bKjaixhcuwIovIQCHr4wbbDHkfRj4OHAu7QoLhKvjo53jYvxSvfJkOeejwAMcQ3xcCr5nVZl1n7T-8R6Nvl2iPR89J---Qiudzny
QS7Q8d-i_9EFwZFgL6AHFr6e8fkLOps8_2dVOhMLGwf7_bpxKJ2VDV9mlAcm7GNfM-HlQZyAsfz6_ZxV5ld7ShujyiyLZ4_VZ_p5KVV8lr0MZ_nBXIeU-PSw
yHRLNm
}

