sprite $image381 [147x107/16z] {
pPg9ZXfDp4LTcvThkz__RV-bW9vkAg1eFY0uUwP775LTMmSBUbqrvKBVL8K1MAVlgM4mCq0RVKSrXLqAaF8DG0BONh11_xmOi6C5qp-lgWSenCRq1TKDLo3F
_0uaAcD2UMH-nIcrIaHLWCZy4gI1EI9bowz1ejPg9vBjUqwf45NZhq8QMgZqxpeb6LJeYv1cTVkkKngTgCjN8JKRH5zsSRLsBjzrIeMgo7TboHfHFI6LVsJR
zVRIezT6HwHkMl-9ROFPkDmIFf5cgG00btzXsu31EZ4NgZjI0FYyyTQ3ROEfwc48n44mjNqiH2UldVtLjTwG_F15IFser4wWJARUY5Xs93z2sViZrGxg3y-S
I5FX3aYE8rH_Cz7X13poWaIjjd54EXuKmjwEX9yxkoBLkQCu8krGyCYt8_c4WcVkIAoLIhj7Sc0Uv9kHcbrUp2CFICIzL5gGV3uLQMyUHpuh3yKdXGl7vv3c
E8BFYXCI3wB64ybXXayXTSC5QJsbNU6kenlu15BJoVFWuahfKYRItcZlHYe2x2-q8hL2HOJqEhftg8cKcxrjwsS6LFqJ4biZAXFfC2PnGOAz7gd_RFsyDDKr
tjHRwtH3sg60o70QqTxe8GxhPCifbQbmEz8EvMbLXmUalib3342WIv7x8I25QZyZEH2ceyQMOR1HNXoY7OaumckxGohIgT0TaeVJy4pXs7tWfHuo2zuwixjv
7chCm5bRaJWsW4PUbghZfI7QaS87gHtZ7NvHkC4BKcx9P9hpb7pZr-mUpmM8koYD7wI0GNZUoeh4p2EtY8ityEjarW3iMUeUthl73ZHpegtpYkJ4kMKVwPag
6xziZss6cxR1UOpc0Ry0-Vw4YlAAP1bY99bkn9kygl4dIMN79Kl197pH9Jy-vL8MfCmO1CzaCebqRQzf_4dIgWfWi8umenwPSJx7JMX5QaCr0zbxJc-1bDys
_eBaO180e6u86Nu7b9a-QCsIRbkKdh5bvytDOEC5ZJzJhUuiPRYhz8Bmyvt5D91EkWLmG8hOl6kr33NIpGtxoFnrYEpSQDNTGwiqynye_2nm9Cpi09MEGPvR
TW8o_UA0qFghnjzXhetMk2FWLZNSgEtl7k4vAz9gjqjXFoNgy0sQh5lw1Gbc09TVXsYcw3AqXLZTKRfgc7Zd2NMOuZxvZr3X3LiwzSmjojZSC6j6wjTt1ZU7
0OmmBSslSXBUIVNiA7u-tSiGsApeyFIXnIRq3gNjBnj_HQhDtK4D7j8STfKJLo6E1qYxKbxb9FjCr0yIbftAOsrSaRZAW2kFsMX6787Q7U7zAP81KoWpXLDz
m-cKu5WZjJR-MdkAmaCB3_DTJbhpE5zSm8u5at2Ed7Ao9UWdIp14uh53rHcYnqW2L_McuLQgxtB2HGREIES53chDt5B8BDEgTa-t7IWJzl1Z1GEmPqYbmiDB
LGjZlye9Uq1fn1d97VjehJ8iayUKasmpKHFfDZRmP4rN17Y2f9shENIGUZXeNEH4u29-XtI3Kc72bdcLavx859dJ6nvvHB95ovU9j23DI3i2JPguCu-PebeG
lY9DA2_LOmDddEN4RwF-YFGeKjtm66c-24TuhJxbH1ckJQhz2Ma-WYsyrCmClic9HZeySa5w5Ad2XWT8ireLSLUtZe1HTmzRixGhzsOawXcj7-Ka8hVm5Mb2
INaw2bQaYvousqLEs8S6r1yWsP3gMwINWvoCBJEro1OhqYLIVsrAinOvQMI8HqYbHMxIpd8YcMX4kY0zZTGmF42gLQUSu2OdO25zb2MDD2izTpaP1DyoAZr1
0hHB_GlhlY4HTGku5Gs_P0drSPPIIP4PvI0d4laKoNef03-Er8f4D3nGkcYOUkTmd4q0k25nKyuDwGrRNEH42_aHAUxZZK4aZwVK0oGgulv0JWBxqv5bv9QZ
_CX9DA8I4qcsE0C11XjDcGRcFvcUHmeu815L2unTJdQayACcXMynj76coQYnHOA8Q28LP8OVYTHWZQWE6ej7FOWKTgHP7LDEB7piSd9uYOjeGaXpow0UcTn_
a3XEJvk1YT7Be3veu9bjLZr37G-JtU5rbvCb5f6jc6LeXCHcbTf4Af6CRNcwKn6YrfYhuRcJz_FjMJlmoa5E0gjYDTaoMedSl1DTaSZt6pusVY6MkJD_yCxb
SQJSZzymt5sdsRcjXTYyoh0j1j4DgSWUehqWGuXCvj5R__lDyWxrSwpT3Q7Y3ljZkH2sb48xql3rpeo9jDEmtXIZ_EBTE1pzXXH2xFkEUpqcdo6wLat7UiFW
KeYa4oaWzPTx9dThEn9TL-1OW3ndYFRgVmgHeP5qab44sdw_sO6xb1iILNTVeQOJ2Urrt_W035ABDh9EOi3uzSvoZzGDgJWO--sTDWG_mUZd404o558gzKRQ
szhulujKsv6eoE6WTe-DMpJQEKJNGMsbjSADrA3r9VjlT_WLgH1LtA3WEMi_fQAvtOMeKgN1L7gJmOiX_QT8MI6g4udKPy4ZpqWSMvw3Xa5YYawzbJL4_pLI
65HEI9FeWDJ_D8bACN3hHDL-jIHyhYrXumbIjNKI6OGgbBeDNXh_5P62-sCaZIqSzyipC1LjfF3d8VglKsf5MeN5RFw4p8Yz-cCeLUyZjIBTDRuAh5DHc5Kg
yeOFwtGxHyeMf70x4b57gvKO1bDOezTNkOlKFPBZBjD3gDUci6UD_zg1S4HQ6tzGxzHwtLUvRwgc2rIiG7P9TA_Kom2qVV2pNfX8guB0Ifsdz5GRtpGGuB5w
R6CXKUh6jjpP9o9r3uHEr0RrIcFLnWz5QY_CdxrqQcC-yyuG_TMs1ODXhVTMg6aRo_l5JqPgNz6EGSIZ3AfO6__JaPftrBKGAvNQT0_Hfwih3cEemGf1gCZQ
-9-F5BYq2v8P6zOGVJvIKF14AlQiyJyx432emVfi_2-eRhWYmJfzHvLXFeXdutzDLL6R8VgcwjhflzN_0W
}

