sprite $image297 [264x192/16z] {
vDQ5WGD134DHqzgZ_Wi-vakoZ7ez-Ckokq2fqFE65odSjF0XX5Y7Rys4LE0NqanOuPzEs6ZY9kS-YMzbN5jvNohNLjuNGY3HhpbP64WpOGs3fN9jvNr1SHAa
cV262KelzqHFb0HRIPQ9m3pD2BQI91DQ-CPx71qMut9QZYMLSMtbVQddVw99Cn5OH_CJFz6acT32gf9iA--BquM1D1DMs4ZfsRQo5lHCpPckkOh3GBG1suAa
t_zrU_5TDCcPT8KfYB-f7tTVyB5BbeGwniklqPQ8jmCLHfWOS5UUny6eo8VTbUTpOAezlk4qW0FCCJum20xpPci61rJamnjE0pWmrHuV60PmG9WORuaH7AWo
kk7aSrZBbvh1WQds-2HQSuXl2LAQWqwrnz-LxV4gwvzddSfw08Ssl28lFsrBsSY1prbi3WLXkenCehadoqOEVCZbAGxHaaCmSMZZKkqfP8jaMiaXQArdE9I-
V7A8QV0uQbLHiIl0OUa_gl6jjdHQpt3uMjQ_deVvuQrL1zwL1D7kEVI_VVkmaaF_tVc60_Ff2Iuju-_Ac98OERHROA4uz2NLEmvSRJ3L7lToXli43XbQrevh
K-gsMC41zsHxPQfTzhQJfq1yU9kMKieoFvkFhXqdEV3mGMNWondkKt9OTJk1gXq_E31Qpav5xj-LeSvGSi2VRN-y_ANos6IH2zxxX36_wguC-NZ9OLiNX5mL
9xij58VaUcwOA6RRBLUvrcN-rbAxoyY13bi41_MSvOI6ayU18WVQeZtFOH8LkNjNZkEGT-jif7WndNvNXiJuUvNuIu93sa9pqFb-E_skZA3QFxOe70wbso8v
rBZNykmbN5utoC0pKhR778hYa3KMymVchd7QE6gpvpJQpIfR-QFbppa61_1QVkI0T5AKFgyQPE0MvIhfy6dM2NhzWKFiVjZwccbW9hgt7A0dQYnm45MMq79s
O63XOt786eiSM7NxSsQ-9UZOt2B50VK5QYnmm76OZ75KbOtO868ZXw3k_WGj5flo1J5ebRCcdEY_08Vz-UJD8i4XZ7rRbxEcWTcUj3cqRWjmuBrq-3XgENAE
hHWSiiO21oDG0lCPqy3CRUQz7DQuqVS2Voivk1SdGUgxqa-a42VllbcJmu_XYnoOI1bXGXPhVcATguo-eBwQ_ittmeh10OcrOsC_C4HG9V4Uou7rvkIUvthC
NHag6sc2GqfnK0fZQXrtfSk1Efk3x-qLZt8gX_bBs_StqRyfNzyqWyEHgN1CrbtfzoUplXZ28NMv3EMm8qwUMHzUtgzNGSAEao_ZqFupXUlx-_LB7eYWQcwH
o2S7t9lG5uNE0IJEoQEscA4R3kpEwhd1MJfFM-8zEQGv7B7-4VDHc8V9xgpWWEwNGI4v74U2zV1-3eLMD-ei4HZ0mJO7jsWN1tHd9OVgPfAT0ZWSGY9kaZjo
YD--wT-10xkpJ_LXLiCIv41p-7qvpO6gI915Nywr13du9DOfZyDU3ccBU8P3TOv3KW07cCCF3vg3wCvA3brXM08SICA_BZG7lhzeo8-DzrcI0ZdG77xwi2jE
9iSG78pqWO6177mItAVz7E0MSB3IIL001s4ER_v1Sy04ZE20aTMTbY07wqYifL1fZMKZXzOB2t3WImjoMCgz9WO9RGdDWIJS-QWA3hyLfHHmI5kGWrBHbX0S
X3bUE2yNj8KzBqTBQ0uayIeEZsiiQtuoAHWSX3aS3X61_YHghBqScWWC1eSauSrNCskSnGJCVWuX0eF1GPX3SwYXEEWQQ-UyFIrXSI09x-ilE32iQopc3_85
9otXSz3cq2-y7tDO61zW2y51ll061Sd19y412D6FcbikPaQD9JWWWpSeW8Db3Wx420wO546DHGvY80Q1mU1WaC0MxU2GGKDmeFsCm00EhZdqr_Fo_SNjYSaQ
Yz9VpqjB61ny4ZMtQEUSMBTKKnpO0gp24WO7nnoHMxH_NcxT50SO8mmAu60V2Vtv3vJ_EHWLoHC2Wy719j6uIZt_u7qU20E3py4t1pXCOMiY1pCma8DFOj3d
gj4IBWVV7ECvW8B1mI0nW0CiON3mI0pZG0e3E834024mMBhu8CQJa1Iqtjhr_qxYubFuxXNCwm4aXbh2rMNvqoWOToJ6M-BQCWxNKUOO7nZYhjdxMQsP9IS0
Gp4iwLxW_kVbbttLP2JVe8LdsGx4SVICuNG6XsoYPWnVuuA-28QMJk9dN172qCf9_CrnLPCuZXGhhx_8wlyJ6u2Lt-D8GPlWMJcADi6pybWyGwF6SAnFmYQS
8Vf9VUjiOWCOmnnFQxfiOhF3Jo9X4pmhlyOL2HYgO-Mnu4Qk69pU4DR8PQmisWJFog9DR9OPWojgyyO0d0JUo2Ei53HoUd2Yn4TjmU0aiGa1AoCCvGSdNb-4
JGX2jDWc-C695z_8LptE16n24A8LKLl2Ia4ZDmnEgaQ-4R1I4BLvLWPjGZ0uAQAs84Gx6dc0bKiUlvOypWIYDdaIPPiG34wAg2qOd1ID769btYQQni17ROQL
VPiGX6X5r1OCJef6BXYS556xoKg-aJE3KzycS5P6epOpEFKPscGbtyX9LfQZTjCO-CSl9aJtRK8mE2aQENCI_QYD3qxHHiwmicyJpE3KZzgCCVIZDiVATYEd
ZA7Uo9bV0_UZDiFAlaqmWrEVeGmh-usSOMNV9fZ1gT_86LRsRO8PdFfHctcSwJTo9aJt6xdWSMOF
}

sprite $image297 [132x96/16z] {
nPXfcl8m38ETtL6O-n_tMr9J7ChKzF4ixxzP4RMaE92Jn2tGhn9g_qUXNwHqz7-0C_qIYT45j4Y_G6pe3z1h-0KZe2_WfssHHS42EFs64OGVjqLe1mKEMpZo
UABYstEQ3sDmsCAPHy5X2ryURT1B-9ayUctXpwF35cuZy5jC5L-Pqw3ooFGMRDIt8uyND1W3yUIHYKetA4JyXJaD5UXF6khy3e3-6bIbmL_VoWZ0_XpGEpep
pnzoZ1Mh1lKSe6pXpYDgmKC39_7gBce7IWCuToXRE8sGYTAkWGDjPCXm7kJwq5298aDiuI_cIFF_RHeAXShCcOZHrkV0bCUkORxx1cKBNp6dkJhCbnoPOiVc
FN39RV4Zp-U0kpDsYUZPNSppFzJv71eHnHYsyIpvG0hpbU-owdn3r-ixgFaYFyiZAljpZTmxXw3zG1aun23oILkOYn8EogS6z5fgvVwS2pHgCe65UDY-pJ6S
Q8Zoaa0lPIajUMpzXOQW7SFvwgB4ZOKyH_jusssp_9gBa30rLFvFuxez1TXhbhqeuMxngQ76_snNNfqBDAheAXVAaWgWXdVpU8pctWztrbmWqzBLMKNJl9JP
Yr8a2XrYmPQ4_9IB4A4r5AaeOyrwTsCEspkI641OSm6ckcX8CWbh-xOlBhfif9eXPo8a5-B0J8sP7sTt2zBmngNCkhX0u3WTldaorPnBgYN9UH59qMU7J-us
ChPlOmmr2JbjqI4gI9G39Kg1wZmlZXgMFwAAq-rR3BLYzMIc4cEcd4B3pCL1mnFvz5BMqQzhw3kI2uU63enLWpsBWuQNVaZ2oIm4Z1l6GONjIGv2x61v2NuS
qSNmf6RSRhVn3sawEvj9ijdeZdn3bfVddNRJVP8wtFup9gOANZgAAQ5IHgJzl40ANLWxAfsEOJ84lAEXAmrDD7JHJncMXgC2hS5MqOAQXTA0xRn0bOFXE8l0
-CG8gmPx893_zpmBo06IQBtZGFLWnIiZQ0tdAaeKKjokDNSDN5hFZrnGWjOGXQGRHOz1CrRmVaUXgujNewerF9CEOpZHe5JOFPdQJ6tXRNavqL3MCHWQdWTI
ir2ccbZL_h150P0zKcl8PVkZF2Kqw34O6eug80oUmP1ibkt_Xohd1QjHg9uSFKamb093mqbEYzvX6Wb1Sf69rrcq9T3A28Q6quI4BMFo7Egab2hVIB7VEUno
K4OmD5WgOcZOhpIuisSJBp-7oLIXnc1ei5Nm7aLkTvYvvLnPqrXz3iDGOx0rsBQu_hcSCGPXu5G471fi1G86B1LECCuLVDnY6vQAxcBS30az4QK-JWRYL05B
mSWqAOw1ECTGrQL_V8SAKm57KaGsLNov4OvdShvc2xyH2YrSjeNV22tGIuATKtnH7YDzIcHx8Fun8DCPjYq0VnvDgcqBZm8EPF2cBTnvjB7h6-uyscIOjd3a
qU1AVJloQ72zllrvzDl27iEeT87hzUtFep-dNsw4w_KDUr5oOjStXgEOlRQmDNnyS2GRloqmBXIpZ_IPBJ2ynUolRmoZcDtOfph6bJpwUNKfm_0Mix--CQxc
qK_1gWBZvEBYnZxLHOC_ZyvJ7SERHxyjCBnvzDStXZUF_lh6yERHVwfZ-FFeFzNTYvBV5lCJfLybi3-FVm4
}

