sprite $image358 [181x248/16z] {
xDSBgYCx38JXwQJzK4dU_tRll4Mk4CJq6QSQN0i87_0Zfx-jtb7xyzlDTihtjSUToCyklrQEkv0VJNpdBSX7aPVT8Uspo_zNZnkLuIlCPLH9rcdJBfBCpn_f
cSjN3_gOyxJvO-OzVwU4aQSTO-PF-sWokvFipD6d7TziwhJZcPjVEOZFNBwJEkOyRU8pbwyTn37dAyGnv-idmPlDUFuUNRv-zI0k8r-XFdFv-QC-StdQr6Sk
JviuvdmdzPdBqoQEELzZZpaEfbyHSrb9LXkwzDFa-jJ667gpCiQFAVsPyq5_Y2-ZLyViQFOpvsK4D7_C4SqVytNqAMlFN8BcZzcdx6NOY5F-CnUd_6N4AV-P
YrF-CnUd_6SkJlbZZiERPH34F8a-2aFCFZ1-cbn7FrXYze7_pCM1zytE1_up5mVUDpiV-6EE0--RdG_yCSU1yisUHny0mPcRGZyVXoeOO_OXdhcctmVACXmT
7q3yK8FfpENeX__WJpPHp3cwg3lXZN2KaQCriEd84UqjUzeyCUTeLOIqbv-vUNHiXAQC71tP04qPEVh52MUlFNFpw9WsHHavEakRWPoZyxJNnpoFZcclZtaU
7HjPNiOyEcUl9_iaGLzFssDUYxwUjjfOZiuRMLn6ZZwwph7Nbn7H5O3gvKRypAr0DqtK6Njb6JbQ4tRUo7foHC-oWIJcnMZLYschZONehgdwdJ-jNiPYjBlc
qexazUZvjCEPMumsS_LKsd3oUlGOEJjl993Nep7Djl5Pz0yDPjA6VHZjadVJXexnUJHaXgqs2D0UA_36rHw30-riJviOxOkDyADZsW9cT9esG8tEqwP6v-UF
7-riFt_Kw3njPdH-_gZHUTh4Q1yaN6r-T7x-rgDxWdu_xHzeiwNebg0dqXv30KvqVluC0ZDAT9wsGCTWHZlRrMg37UrfmqyUCze7PdG-t16ju42BpeqGlT4R
lT4RlT4RlT4RlT4RhVpeZTxeZTxekj7_SXkzqHkzqHiD5hG1jqEZbYBtGcihFoOtGbilloTtGPlKydUWHtiPFhq1sbfvNLLsj4a9gyQAzZCNrumLxJ772ItQ
UacdREXuvfAigT0USpwXGtlC-PG57MFErwZGXbhU6LZGiOnyrLZGiOnyGeAMNilxCmgqIPrH2mFQW3crVHnj2f4VwlVHVRoiB4SRvCVGPzIw6Xt9y-hsGRIf
_1a4RKAjmwVFbMY5lAosLgPV6Ai_hAlGzah-hxdpm9PRXs7eDAkGzFwN-mjFZYOFuHECTAGt-qPp1NcgHkzAXOmuC-D-sq17YD0Yyl-PntL1vlydiZHZ2sqw
D9Svqxz4c8njcX-8ZD3PfYP0NvUvhun-NUjURXPcnKkxJO0Mp5XHrfXHRHPMluxU16XMSu0i2d9KcuMv4sm2JTMmD0EXUxkkDMuMXj0HRqViXqRQhJ9ZKGiD
qd0RK8IEqwrKMuTsMzYzp25CHjWhyLirh7H4XuR1faFDgLFj6ffXS-YKcc2FrcLcYpjf3r1RXZRpmX6zGDgqzqVvbD302eEjGFl2de2j3VMmhpxA9qhe2EA8
0Erkw0WCjMH6BbYlkZrAjSrqQ8hDgTj2zfpSvbP2Ex22sYhqJkr1hb7RMCYHiyJYz08QMD4H7RfGUroilG5cv6WNqCYAQglGn97HUxigSuvs3Gs0XTe2DCUU
n-0rbp8d-cVG0Qo6keZGHEtH1fSv4da7VGPJMu8cQfTNUxsGUG-z3axKpbkDGHD7G90IsUU7SspQuuBQYQn1ko4s2e8odqlc7VG2v6hRDEFGLEtHMozgpi4C
0Wq-rsfdp3aqTsIsthSrnw5ZmmgEU9mYT8rjRRHjpN7ey9eLRm8BeJs8scqqh3b0Pj06hBKkEHYXGjTgssnZR6gEEqrOr_z5Q0_gYENNDxA3p0Hwmugw69k8
2dPHStKCeVaL4vn7WkRr1sks0BsecDhJI7jSnoOoK-W8mlh-y1gXFQWZH6OARSXQwv8d8T02DjISg8SbArSxaHdqPKS2p63GBzEdePc7cH5e1JkCc16HiNlc
TckcNp5PVaUW1MnYHhXzbTbodp3zYYbRbK0BsSiS7v37SKz7dXCTOMhdhVdpeAyFysYFzzvtn16vFRHSDgD_VAQhkQ9s8ly6w8_8OzmWzr5YrrSXuMO_5PhB
R6E60VDMRHnttXvQhfWn_9DD4W-kDc-FJ6ZG7DdYND3eIAasDY5fZypi0ZILUSPs3yt7kDBQj3rUODi-fEQcuoVzSRNb1skYtQ58IOZCSMQYtm5LK_jq-xJo
OZp0DXeYSoRcW-tQJTJUj8SzmJODEagPKpW8KHjNzeoNJiTHs4RpcSp3r--JSRwqiXkq1rY7jf4GCqwV5coakTfUjWUEncMrDpMtxkqIQAvsG7iGwwZQvPgz
aBFn63HVsUFR1skY2KV253Ntbja2NdprtMed-niwnbsr3Q7VIU-MCG6Ln9D25jXB4wWvOfj-bUU9VjpaF51jUAYN7PEhNIFxz2WhILSR7-gDBjh6eLVDiOMG
dwn-nhOufgvsQKRmXP2hZVUUOtWOEIPJ6w6XvaWb2K8kwFkJoCnjgw5JPb99wiaMzErdsGR8Giq9Gb9edWRG83Ef95N81Jr-mf4GEaoeEL7j8DDQLHlDu9Ma
2paZsi-qpPSPWimwDhdnr2BzK7F7xIzFsfRGuI3ptvnKEr8JaFalp_7C0IUJ-s_CoovFxdy1
}

sprite $image358 [91x124/16z] {
xTHPhYCf58HX3vd06RZxNsuBh50XHq9B-FHOZcVkL_XFLBVDFKf-tFwAtPEeolaNo8UeYAYM8nX-5cronqEhFF8B1fxkKP5F0GnSph38D2IFYOm59RydWeEI
K-Iev4SXc9C_jnySZvC7HkRaWP4v-Vw3Mq-HF2Go9-Sg77dHOc7NFuroxC7cFsTePCoyrde6HiQqmRwYxwVimg238zSAEZxochwd_SXh-jnliQQF0dYl1NO4
FZYYeo8p7HQPwR07ntHqPARlZnYOwQCLqu38H2Vj1u7lHsPQ6ahuHWkcYnbmrHXuf5-ugkbMv3LjYkGxaTUqKV9PYmrwdHmjjkWn-KuBfZDOIhxNOhorAbnA
lWc35eFDoSV8MxG1f-H3v1swgS0vELfiq-xJAe0twIPFgg35BjqKlSAjVaQZhL9ohm4qVZxiC9hmO9gInz6KF8gcAg4quruzYkRakaa_tsXERjKZQLmShGDf
u7yTRVyK_QM_z9V-qb_Q_8gspsalP_Q_X9Pqd4VsU5hJsNRaQDfoSxjTecX47gQ1jAPZf9E7q6CBIh9FemNF8cWvZvEN0sZBwRoQVagxYfPBEtr6kud8p9Ps
uiSVMxHfWrKADy43B2yPjCzeQj5aoIdbV9d4jDKOQHETqGoNd7BRbLs4Q5FWKzgbh_GhD_qwjsOAGZZHfgyO6JklLbJJ_Js8YkYIxaVGOtRjBA9wK10LNT7Q
RSI-_9Afj1C_QGnYAi2dj2dmrhjTcs4LzUg5WYYkFw4xZYfiPtd1vZRGgi2H_986ZYeZdKH5h1tpQXm4kCvf-vNyPO-HlSEr6WSP_mKS8tf8dc6NLmlynKX3
79EBJkWXUSc8hBr5xQCWQYEkQfCWgD9mBNcCN9aslGXIVKQFoOkCaPdcEyioo7WT7IFFWhmbDr_Im15vECb1m9h9D0XN6LkCjpx44OIUYQw300SydjCp7RVR
gIC-9bTVqzWRh6tM_zU-PtDwsjCWF1zbrpvfSDkZuE9Ywo1h6bSMqnl6oSSWc8ilQS3QNmXscNmCuhNAutQeJsd0qjhdGQRa20BOZduecL_J3jXhrUS8St84
wR2dNuVCYHvRLBTqmoWv1IdtuT3pBRc_mVOZ17DoyuhVnuSmT-lJ5jdKsqSPnyaxtYAVT0R9-V6fjuyotRCu_iQh9xJ0a9nfDyD7cUvGVyavqs_Zv0xOy56M
Ewr_Ge8vEMXJfuyoJVx-y6V9lKSs-YYBv7bv1oHtSqGE7P9xBMWNkiSzNqR-0m
}

