sprite $image409 [235x156/16z] {
vPs7UYKX24O1HU7Vzt_VtLiIjaqwevUShUavKN0-RBI0ok3E7wf0lDQcziQFQpdDG_2Gi7QVseKU2-dJ3oHVCtORZwChQWxuHxdfFa1lvZx3yrEwez7Eo0ZF
pmAOohQYq-5V2E2pxTcYW7yrm8Qowl0CW2cq4ytWMG1A-p00JmGcj0SSJLgyOPl3qy6azNI7dm2Cbvk6Q77N1ZyB6Ar4_4GmQ1tiEDMrqp8c_5ouSg2k7t9O
Mki6Fna8dOVSAsDHKAcOcQGFkod25m5dogPf5CQMOlRydpb7b5I_ibu4tmB0R-2E-nnT4kf_6tBp3Ttq-jzwNpULXFhVbW1kdUdzj0duem7uaEAYmJjb9KGV
KvRfRV00_A61zuGAogPWChq6pn2jtR3DuKLufQ2gW9S1auuPy4h0EBj-ih-hmQi1gsuQO5RllG76jXafltZSuMNXWmc9yk5gyA1q5zPYfiSLLVRQG0-oR-NC
95uTQ3HgUGuYjMuIxl3oOCQOMXw9f5GSQFJVxz239_nRmDybL1sDnBy7qBHGnPNxVuELmQhm5BIhze7xV_iL7UQhRE4qaFWa9hZzD-2OpSGXde9CU0eSozNu
ltCb6Eq8GqfUianL2TL_5c6YdRjq4Uf-kYgr9QhZB5LnTrCEbzDLvscgS0VivjgVLBjV2RLPGpNA0VAi2ZYcw7HtM1zkUQfsikhyKrMjt_GR78E8MnrL-rDL
cFH7lpZFMwL0GZM1TQrwmovwJ1DoKKvKjJDL0VapBTrRzW8R4_7CLCM9gbF-6cn6fojyxxlT4bN7IQea8amt1FwaUd_ZyyyWKrKNF1ZQiwh-6DVNOD0LJrIr
TgfgcDvR5NxjjxT_g64c3ZRYvwgoEZnKWNvLl3jcgauod1QhhUkyYOQgyqtEqbK73Ppu30pubOZLfoV5aTw1bTfvgi7V6PY6q0MpFDLEv5YeglS1zKxck2f4
Ow5g9oAnKEMHfyf4ib3r9jQx4D5ecO_xaGNMgJOuz2apIKzJrQZhBL5jnEwuzrhZ0KjJRL7BMQ8wneHxUveGH9egdAw8hr9Lt9_P93cYCEY6ObMhugcC1eSr
aQnrA6XvvSZvYp4H_prK_VVR6KXS0isEx9auF-Z00MRQaXleogMZwF-qwimxkuafQF3Lm5Lr692zvQRvUd3XXCtupQklQG_4K7oPTy2ZfYiVRUYi1dhwDjtz
Dpos2HGCr6DPL36rx1CXzZSDk0q7KApt7jkgFROk1hqTRbqVLXIQSDRRZi0R7L1h0pemEE6epGs1jOGJA3S4hlGn30_b2LUce6om0gQywI6KcvrUxtWGpouK
bEp1mDMJwVC8jdNyyijIvgQkzlNdKmeUfv1IC5enAGNUyWI471fsKssKnS3-WLeo2qCfaudwfk5QtJJOe_8FTCgdEJQf6UN3OxKi9czt5Ln-AIKVIQY4xtkx
cFHfxc_I1P1yE6m-B6_PAGqRzYMsW2ijnF6M919pFrdLiNmQtjhZk8-FwmAOdTQYUAL9XUw4xdjziSUDdORtZWlST7hu9boHa8EyeKcFhiGnT-1O-RaynhG5
YayCzHnt00L_t8Wjj0-6TpJfiRAqrhNh-8LsxMt3UyuR4eRwFPaudiIjXHnFubPZu20TbKEE-sxzHWMiKK7aNrFhL9A9sa4QT1pS2rGEFhZjgI03MGMVZHy9
uPL5YG-wRjtiY_AYf8Z2LcqQOjbNRSGH3LeQzYZWrORdU5pFdm
}

