sprite $image291 [246x266/16z] {
vDW73gGm64FXeMI8IUv_tUqTFQsobNdvRc21vUX_l9xrEDR7P9QI9C_bCPEzveEwFwQn7VcYRfFytCzyPufwbrpewxtLNDZhlHu1TJKNcZrNyrgnuYyqr7kI
GejNh0I8LspFa6B-kLdTX6lbhtS94DURrygtObneVxsN4Y2kzrxp9vJb1Oyblw_kvhLYnsPUAtOivhLYPL6l5TVRNMXUCVDQiUTYBZGhvaApkhdNYkljBZJN
M_rpyuhTSgtyzTxpNnohUQrOMSo5PliTZYN_NlMk5MlT-dEpi_VkN2jsjlwlKvSRPFv0kLPSw4zcAdJhdqrLw2-4QyMPlv0LcjVg7wTUx_DpVp75MbrCyFpi
LpEirTKCQtLbE9PmPc9-VZ9pePdWM8APcNcjcF9OybFYjM9D_FnaJRnMh8dNYZLneLap7Kl-SUgrtd2jM2kMOyc8Sp6l5QSshnMdDgyLfpQl5QSs74l6KnjE
--EfpONcr89ZoR1JS2mP5y6nP5p4QyKYVdwoY9-VBEArOX4NcaLmB1aNmR5aNCG_DujuhLZ4QyKYNYiMSQ5P1CUISH4SIyP5N6WMmR5aN0J7ad4H74l6HRnM
BEBd9ulu-SaYNYiMSQ5P1CUISH6l5OluvsOHhnMBUArOr6l5gKznPaxTsYdEpAdRUMhNYbD3RiM7vjJzG-vvChyjvpwK7MTXA00BN30wYk_xF-rVsU8xKTOo
SgmaP_hsRv0CNWo2YG0HkM2u8LUb92B6V_mdkrckIit_By15lDpnYvj7QXdvD_TRcx6vpMxwvMP-suR6accJDA6tpECNzt3lVqRvb_ijPojj_n8Txk3caaXB
AXspMFpPwW9tXDbAJoveRF0RpbQwUu401dVisIhj_rgKqTZysWDT1pAa0WPtL3D68hkwkL_LN8YEgy7yYhFLakcuMWpkiCjFkrfGsU0EkloqgvU5ZxGthYlk
H1xgnJxSB9S5cLpKPZT3haibDtLpnpUBp9xgtUtDScsodtftcJFasZ0vgHMtoHo_m8arTNF7DOiCpkgMDjn1qKoEQgNCevb5YhzQTpCaHWPVzJQyRMz8a20x
g_NsPaYOrEofrikS8P72oK-jko71KltKUfbBkCndgnSEg4R-HBNKZrHZ-4IrB1-fHlf4jKmdgvtPjmjAtAZs7-rrzM73JMrtsyrVNpvgoJxgyzstVyow6X1B
HaUr7lIwWVLBLmE0M38_HSq0-j3ofQjXLYzFKwF3_4WDWPbTEzMyLttKtKmtHGqSKVCprS01iwvkQ97eQXn4juVPUgVqtquDRDJVrYZ0HettK0CRzLrp-_EU
hKOzIOrjrbKKz1NgvdPNurlk3lHMZIUfsz_4xcfyZ_ApSb1T-zHjkDbLVLiLiuAsbtZfLJTtzLElw_e0hVs4IJrtgtMtNTtU9rVL_BW4JdxdkiSMjghrzyaz
Pk2vMviBDb7Rswx-iUv4Yvo3baG7ChBchYvgKGRQImqwbbbpS_LHw-P-j2nqCDbGvbRrgfZTr1CTpb0rT-rNovbeoMQilRtjQiNifUP4FKapjFO-h5RUhUne
UrltjxVm8VNMhACX5xIreRrjQgMuNTN8v929LRTLlTUC2tRjxUrjLpTpZ0Atpzv7rJXDdSWjuyFsniyOpN6UuFRsjgg14zKZkIOLTHR3prZHOPOeUWQrlN_6
munB3WDO5waMDN2k6edEoCnu59lPNrtedEI21_508y2pJ5caAZ6OuovHzFPMef8PBw-cDDl-nNL8DQYwVv4Aw7UMP8wgxczl_SwIXAZg_aMgViL1WaXCTVyY
LR-p9C6mCWkfrjjRlUAWgIMWklyTLBzXgwb5mgljxQsSA6lgbk1gUtjlPYjDBR7LzlQMnfg97gX58gljYrJzXgtqZVCMQaep0zZCLfgw9QhQtjuYF17jKqjK
jNsHMXBjLek4LDlJp8fwdpkksfwaQJvJBU-i7Xze_DGrnKApF4g_-dPJbWeNPc28dMq_zmSiST2PBHi4nyx0DJLA6FLYsWmwOlwbnXW4FHit_ipcZPfpaFes
Rl8Q3xLkrL5QUp5lw5i7Ugl64EBvRPC0C9ktwXf0NGvyg6Cexgqwoc0d6DI6yzQDtBAkqjGnEdkogkt5tRxJ_ANc5EDP1lYQrplcfeumPwVggTQBUwik8IPh
02SNzrPTBrOFQ3dNl4M3BrQFlkgRPcxe88-poLUzAWtTpE-greixf1e-QgsuewhXgDQBkwbp63NWe5QAEx8Qw5QhvcrYgT6hLXewihhVhJHqEBN0qwsOewb7
0Svnur7IjUf1pEn-jE3wNJt0tus7aKeNXzL_ubbcYCnNgsVz7tcE6I8oNAtEtXySuSzgqELXrzEts86MShrwTFoi3hlGo7HzsCJkHyj256Im1Trkx4GZKuGi
7j_COYzQPWgHZ6uszgCvKOoCU_xfJcWC52Lprsbp6D0oKfmi-m1TPaDJHsRRpL8eLfQTZj1eUuhOt7OpPegN2GQttImOAMA6tSDum2oSAMRIOcXPcnc5ucPa
SOD_E-qSEQb0FE2Y78wCchp8jtI9HR1aUe4CrVE2ZMMW5ycmGEx5u5N6ENPoOUaE5yKSDscia8wWZebUCMcgE4gU3EI08rxONjY6KGwRF2qCsHLmcJAzJT8m
bSfuvArb6XAzOL8UfhaijRQZK03NkfHv6hEVzsy
}

sprite $image291 [123x133/16z] {
lTe9ikCg38LX3zW67M7lVxUlI5xLgQHr0ub1Vy_ZLqPNtSumZIh4C377baEInDKVddUHb9B8lZZBMvBqJDBc2QzH4fCOF8VycXoBpv2JfFSaxVDmEHWmH-um
PAEnYpQ_3zbdv5mevZNo40tOmCFmXN8OkRrGRYCFhJ0NRHwpK0uZjuViDVAP2_Lj8iViCsHxvCvdpKGT5ifAeB_HMmTOTUn2sOa-yX-oG4bx3vdq-8LYKEO-
PFRbVVtzisQk2_KJ7NgTDOFpGYc3qq8PmMMXp0wFXRBRl8VCza6t8OH_eaCSC6IskPyrQQU5QgUt0Gjbq0uBPTFkGoRjDUGw7Ho6JBhhaA7jzC3Ra7Pwynao
QPU5iccNXR9fbuMoQPU5icdt8PDs7p9fY3TC6YAUGsO1IjpnaZKkqvAquBvmbZ2LWX3tEMlmPZH8LeYCNIZs-cpTHdpqaDCwlRL10V4Oij4141-qKFiyMGLz
s39qeUmsnTEMCR1moEPLAs8I6G1hf6JJG8nHJ5pqLg69ZedulKjcc3_G6sdYdM2UTvqkE6texK8pNH88XtmpBAqqJvrdxNBWZF3Tyj58quRsQgtGEewEtzBQ
BInDD9F6KMgrlBNJxNW-BrM6oWTQZMwVDt1Ufp90pT8lDF195hrEqYYfbVn6uqyOXRvE_b0XVMdOS4dobVKHYledZSyqLDffF1FD_B6g_dZWW2Arqe9dxqE6
c7QgqT22r-bygRp3_84QnSfTIabLglHv5VeDng__WQp9mcswx1FaNVxwkNUs2N6aobMVX9jaNIflduA28_zurPbm4orJfIM-dxfDdqePzqRDWhpYDasO_NnZ
oFQNKoTjmPtEsnwv24estE-yxKL3wOPiVNpNHyugS8sEqnVDPUJi5PP1D1VD_8lJiWAZQ7laZpAsQPfj-Jvj_zlAPvuAhUDfZfpFXZnerP4qHruSFlFqe4lZ
Q1QIgfOXatusZcORof3_eTM1PgI9EzBBYzDafquNdVIbAfspwj65FlvXFjBvlB82MmSvM0eWjbtkNHyqbll7BJ0H-sVpTPrdeGNnDhr1e3MRPtsLpy-Hh7Vf
-1TjmsSvxkT0zWxdtKR_3vzQ0e1qUwVhD8VyShikimzz5fbm3tf5pUPEdOJxqNMyN3BXZdJTvbcp-xDkmWbtesT03BmE2sIwcQY0rM0c6k_IUmR0ccNahSCj
2gIAuvyKq-tsh7Yj0ORoec-KAZVXCEfqTxR0i6kop5CVsn0-mYhBrAT5iet3XdEQfrxDKKkentT5Toj8Ri3vBe6kxHol6H-Gzs_UHBDQFby8acsUnhGUHJSh
xh5E8rlt10D6tEaER0bxJ0900KYAUsXOu_y
}

