sprite $image236 [236x176/16z] {
rDU7eGKX24HHWP5n-Y_uvvp3OnTF1zVig6Rk09BaqWTu0q2uZtsP0wH-Wqp4NisEoQL_OC9jWynSkX3Ew1fioAMB8w9T9rM7C_hCf-fn-kcXapfCnZXDf8v6
MD_G_NDjBXLek9Y3EbtQg6Uf7XZrKzh8jCBIfMRIHmce8thVqlwrK86MjQ7kQECYV6a3sUu-9TmUF_MwC7JQg0lZbM2dRUkyRkTCb5m7SIWgTf3k_t_lJ2TH
LQWuRYE3yz8pvwszsJv10WnosZpY-lH8P2QrYNZQehIv13BXoXKNqIQJFZ-abil6i-feb79L9zcc4sa8LzjS_8MkBI-OAArlr_LndDfyJDt2-luuj_b8ecsa
hI6iw9MAxZRk8eYq1UFO6TOaRHcQtT835tBRWu52BmI173v3pBDbYttw6VSR5iYE-ky7CB9OwE9KsN8g8V8lik3yMCaEgUA7mSxK5RkiNTKDTskC6_ccYXio
FjFALbcxghSSWQLp5HvvCPKwHpQVFuPl-x2acwi86-VmOSeS9gsV1kcFUlkaqiqOPqFx2bTgOxYphrTQxXfjMV9AFJjTue6Kjxdoj9lDV7A-BvKsyPZbYaoR
1BHHuhd8O6pBPhJVACTE9-sDghHXd6tKKW0EjaMgggwM_hC0V7O1ABP1640V73u-_gtdNVN8hZz3qQdMAD4-Pgaiq4eE_oNcAe2sHJmRmzbfAm8jfySPT5Pf
uUpTkU05dQxdCwxLqus8L_ZqIgfl9hYpbTj7MTFMwghn5XW0-ZDmC-Cch8-ot63MbXQzrcforTUgQYjsPx2JhTcwdyJDxwHjBUdUxcLl6pLhQiwZoww9jbMt
C_SBe7s8dN7LlarcclOPs-QXNLPwsAXB3h-NuqRjF3Hyvp9_XLQxB7d8XLrHrQtzE0DUjOXQcZ8ra3L33fLAwXCDIHDrFaLxfYMsXGO9h2FB2bmNmjFJDj08
Eiui8cellAHf6mqH0LbRAVCFbU7ujXHo2rM7SMqbFhQ3w5I0VCZrMB-tIBRcw3qH-S4YgPZQ4MeOBWPoY-gfihCMIUMog3GfaeqwK7WuM2HLwgBIf3Lrdddr
vdWmD44cAvRkhdoqD2cGZVthNZvOHVhtgVz3hkN_hjUK9iLByzNnyj8alAUI5UnGQ9iwu6eiJTg3Z4Ji4RTLCSkLWJfScYIHR3Hkxzcy4bU1WoQ7P546IvCO
P2Bi7_MrICeL03p7LKy1BZ4u8lBxfKcACMCX1wua1wV5Sem1LMb7PNkaxICcMGQFNSc0QcCCB8GERQt08CkG1LUY24QsRXv7PskNjezZuE2L38ag2nVk6CYZ
wuZS5h9owQw6fO-Ec4e1rbPcUpg0S-jj1QlY9kb03zJVT4C5ol97_nTjd_GRgG3dzxgX2D3lxQr02pncqs-auaxjj-kqS1vtkhszLI6y88YZNlBZu2nGzC5G
ohLnDqRoSsr9MXB2yuCul-v4zRhqmyPaeAyjMH32inks-7SL3ypouYhCBs4MrpmQ2ynkMCsujnKFp9L-O7w_IQtPlg1PppHipJ5uxqFCzQcoRhVYWVTMWVkq
pVSpnE1ZJ6L2izeRjdRb0Ku_ocewxFgQjjqPGZxLh0fFsmw8-jfPNRKaREgR8k2PIRi1_i2zixeUh2tf2UQnrHx5bRPXDRMxxjyGkXCHhF2SvvIzDCNcgl34
co4eoibcLSearqplc53yA-UoLKcJNAF1rRP4PNVD_vmhS4wMwHrrackTLIiZs6J0jT0sIIQvIg1jgatLBik8j8K7ptA5foqYZCbgxv-szymIq7QfAVXZRyhC
szMC1J2gscLvOneN6Y03fKa-_n9yrL5F580DgkTbWHfTlsmaOwL9hlpIVtBofCGYiAkUbzKSrn-UMfeaEZpe1zDK5J5tSJAxD8a7pZ2egfYUHXAs5LquyndE
gowgpIvdIbYOsNvlSxriDBdQ4U1ZikLQLumWRIwye3J95h_hcrRglD8a-nJucgPb54DfqbHLTLql-pBZqvNa2-EtJ8bZKv6Kgm3uklvN4lOGdYeBrZVQ2h4m
fgiozcZXiWwPLtU0BDWbqu8EsLIQj7xw48cXB0xalaXA-F8nrL5PFxDO3n-H80euWdotgPPl0zzjou93H2riE8BmLveg-fvstshBE4ob7mG3y7UQwWfimX3o
LS6h2Ds1yZsXp1WaqfqCV9Kk2qOHKc11-0j4bKnAXWtXBn3LPbK4MA3xUL4bxZ_PjTvtlQVIw9c6SuZmSayxdfvncC1yNsR1UJBr9Cn1X7c9fXqcHQbGFcYi
beA9-857Tyyfyv2ZO3g9Nl5OYFp03-vc3-G7hAFI5X5_4APj2luUz8wAluOdW-mVKbKOVub8k_1VLhq-Z5lZgrGNowRmGuGIRkX1vL7fvklJbzFpzzO5kRfA
DlIvKEb6Vfd3E7vTjTNll41LYHDSKnz8UUFylD2L7Hqad7Tr_LYUdxpfeUpMkLOwZkEphjIwasRe_wD0Yu_pAjTCGzIphl5bMTO_gR0sx0hNI8F4awxKJKUp
wdNNiyIrEHh6DREhqyYe-a5-n6tjTafMk6OoaQokmHDHVBHUUXZ4rmM1-QxioOXhHjVo5A7yC0WQs0jTCvqWsLnnYzTx2ECor-Rf7DNa6eaetaFuCjT8fmdD
u5flOlSCrNpjNMVtJOMc46NOzNRPFtPU3UwvLBkPJPlcsXpD8WwxQa0Lg05tMjehkwT1jrbTMw2Pv47NIdS4wWhtSE_cJK7da-fVFscg91bnXTv5gAlgvti4
gtVHoRF-Tu7fihnLrqZQIcgeqqUl_pxj0hiGD5i-RQh4TjYrQIjXz_uLXJemGdMq4bSFki9fAwbhFmHwtfZhUCPX9D5w8cE7f0j8HHUFdbUHMdn85K2HgAOL
XwcHhi4LWHbkhMtMX-4mdEXAOiM7aEBfScBzuw8ziGYkWxEdZ-9JnNhqUV7F4tB3IbhNe7_NjwP0_o8-bZQrES_6xNhXN1ddu9g3es_1XrpQk79hEQdbrn52
olcNIP6qLdEE8T1Q_WC
}

sprite $image236 [118x88/16z] {
jPg9bfiw44HBktgf_F_dlaCSCXuPsSsSl9kTq5nAQFE2E-HIMnzZJldBdAFtLaj2Z9k-rW-NgigAFWwE_a_TfOrveRkKprxpFyXOXuYgX7cO4tvERdCnXitZ
X-9KXsoCGN6v7xDlKyR5izqAN4P06K2bvx1p1fnXxmXvSoIddd-4yYPy8FMGivK4fDncpDlmbXgvVHq99rqbWCw2BMce19W9NyHAHBTniyHklEE9gX92Py85
uNePUA9hk3SNlDBqUb8TS-shzXIswBvWHIiMhkzvbFHdelg6ptpsUFzUrYyBJhH5f0KdUNwhTce7wl7dhY2YxRffaCrLr0MOr7r1sMW_TgIC9sIX0qqMqhxW
H3VD4SegUbWrKB3FCkKIVGexR9sVBgo2loJHtSIsZ9aLyvvmaDBhN3aVTSiid_uKDBCFirIM7KhNEQUwTo1rqJTM7HcezgU09dlIfvbK_S2CLe7yzqnLdK1N
rUVfFGljJy776JLB1ACSMQQAgCpHwc6fhKzHVInbQT0bHbxQQOywHmAQp9RNhMjFG7E6P-G6J0cYz2CINaX0KPg4cIWInzXnIQ7B7Sf50wkUVwmqR2ZomkOY
1zg6hEYe6K0gOxESHnPddJKdf5o7N32chDHjWeGzGpUpV8bsi4r5nnlgvjIWDkDVCmDP2xv8xOlQ2jwGMtqwDT-qYgQdy_cCuGtZ5v-mT7FlQjxmeAZBCrQn
9Udc8bdyAjghbYwZZsbSpxUC7M8l5vczzw6ybEfbN99kAWlgPIVrwulGLIvGaotnrmrPLUvW7bTAJq1_4PTnhe5XmklJkLaW_McjItKewOyrCEmzznfxris2
Y3dTRGBLp4dJSmtiKQtHNMLbxMnwRXRESzLSWKvJFQ-Z1IXJLS-gDxY_2wlIIqufjwlDmhBEE6S6QYyvvzAcVeYw3wizuUJSB6ojeku3VwcVTe3qxNxvY-eY
E-k9pOi5TnVLQP_N0OoDDVp2w4Jf3nXuaJi_MxK4hEfVN6lJzfMywc_hSb02xnouVz2QdMdJSBbuJRw-tsIQpuBf6odz2rvhQQErrjSPREPD6pZrB0X8Trer
7hZjUqrVXizIi9NkjO4HXQAoeDl2HNeEe1Zpmnj64IatSMDXSrXgz2-KVblhai-ahhU2dan-RsKDhigZzo7XfsBVfDI-zcMBtVgcguQw4MVnU6TU2JkvA1gK
g_QVUjKk1cb2fw-iszAVeuTZXG9aFubxup7fhx02cFGhw17nVQTJ0I0x_HB-MAnRvHaLvvFTYatl6bVb-bGFbcwyCMl4QB-Dz3tq361juxtvuTRhV6fclZ6k
O_MaqGFmlAPzO_dFzt3WYqw_0HSy30NF3FfDuhPrqFnSIpTryguquPQMC-LiTFQK6fqZ0wavFQT9vq1Zh7bN6lcX5qow9w0yEc822XqOT7OKVfHEN56CxwsL
51mk0Phx02Q16RAI3TUaIRwpmjX-MoiAIVOwerbf1LkgSslD6OC91SNpOwYHZ5d9WJtxk9me0rLH-cqhgGKVA4fUMhCY5Oo1meB6urYP_l6vajOGe2fvPVK2
m0vhHx9VZur8Glz5LbJkd3q1Y7hvOkK0ogyZbYNaCJAIiG9zDc1mwunJffDBRt83nc5rIiB192tZe5ufgGqtIVqvC6rCfmoZ3ldzpzQwqPq-MckJV57QAFW9
PHXFCyd7Ruy3_CtN0hGgVTQ47rEw19REnMXZfuoJwj0bqSvt66VB-4UaqeQONyfv7jJPQ_g_lgYdvjymapbwpNU4_m4
}

