sprite $image390 [133x136/16z] {
nDFL0KD120LH_AR_YlCNrsTpAjW5nZRYtGRpbWI_eYJ1hyYHu5T4Is9VuQKx1Mq2VaMCdkNHMRuK1sVvcdF7S3L0biyQo98upjHt0MJvP80idnMGvRC0idmo
u35SrG77SD8tVkxLR71SnO4WF0bWzv_lVzsLKInWjcSBNCgMtW4-TN_LvcdoRHb4CCJsvKs8Y71kyflOGxZ9tsW13FXwyxK425yOnQiO6CFtQxfe4GK8Nw_f
owIe0eGlZs9L7HHp3Fme5Z4R55C8_2XUrKnxVAUOGE0lrgQcdvWKqma4zdYlOgeZxb9D9nYeKRoh7GmMhNKAgRCfK_VfZE3H8fhNQdKwoqGjpvlO4Pgh5eRY
zRYMUjb4_wTILJVHCWknlQPbyDR742Oz9flAD8MiCxKScmYNJwmMOY4cotCPRCWWCcAC5c9sewflCKjaE8NJGjHqUrxBCBd6f13NGbLDrsSoD9SHUY47XSaR
rZANuRmGPHQoOvIqhkTQwb7B96H3n7QCL0qtFMAU8nmBKMeXFPPS3VTV65hbhwXiAZH5KbVl5AQdo0ZfPawHgk6nOoZ466vA8IaIDTxL7M0aRj8KUhtaY_Z0
01JqtQnoiUzrJC94rFs66lmez1IBU1yGxYPYjtTYOnJS6AArAuIxvXZ4A1A4ty_JRmWt5RsfXfM9KKZsFBqk43strL0fIiamFXHgVLyXifsCqCTRLBElHctR
2G9XSCTRL9ElnghUsff1k4ck1Z4ArUH3eKeVI3u91tK5nnlNScnYfqaWe1gWfWZX-6giscboY3E6PXZmU6CPsaU620Y1wshTpQbQxflu91SJgm4-B60j3uGE
iGo8nS_1Qe25m5h6RGXyoVE5u5e6W7YcXfM_6Y901WXnNmsrJHGyLKajCSHzDPB_2-5QJa30IswocHGaGz_4JZC5WTNeXrDkrfA007NjrmBAq6a827Z9RL2a
CXorP22m6gQR6Aeb2O7hQbf4Knb6BNa8h8PfKGErP26m6WPkD0jnlwxvfzC41A46kD4y15O3rvA7m8yyhYKFWTMutkWM1CIi6fPyEZ4GCtN5Cl0GM8r0jUGX
y4vs1D6usuaZDCHHrt2zBKCdzHWfoxhd1I4mneDDj72xfizpOo7S60GpbJecGUN-9knVaRgzXnDKY37KiWmnoSmYc9JrzVDD2Bm97Nym_LyWMhu9SVvE79dQ
HDNpnGndCudGB-R8vYp6Knd6KzSXHbxLkJoivJYm0sAiHAbXJ6mY3eWZgmK3aIFynoPIY9zNcLS3rJ97YERlv6_sB0H-gYmEX4X-OKAeyKY6CIZjOqYpJQbn
kvO7WgyvmAXh412ubZqj2lmvHyn0u4t4CGPTyGzRdgg14SwR21EBDs1uVibloJ0eJTLRl031yql-G0PNzGvxypTN3tPokvOn_kSC86Ok-OvmTnCjuWI1S_UI
Fzd4FX5BVlh5gj6Y9RJwgvPg7mJVVa0cBdcqI7EfvIv3_cJWu4i-PdnaK2Go74y637xayIH86V0ZZo4I6Q958WEb1eOOCcXyDf78GAg18OOCmSYGF_8O8g_b
IWCSZpo6I6jPVeWabnn0PBKKUXFuaOysKKjMZHmYbm7Kagbh2i7SQ5wDQ4GjYHIF5A85KKlgaiVvquce9QF6W6ZNMax8m5poQ5-l9NxaeqN_v-3JwSjgH6lx
J8XQqcf4SziXY5hobxn-Ejjb86l9dtEwbdmMcw_bFm
}

