sprite $image376 [294x244/16z] {
xDfPbXmh30HGSaOXQl_BVS_EL4qdchRmZ4pyrjyzX4JIdG8aVAPDlcIVKZqZQvOhMyrfP3daaRocn1cPTddBmUDfP9Fty7WQMR9yb2qzCZ8VKabU4cSC90kF
fx7zA-5RmHX8zUHrbCsJl8pjxydnhzPk5OflF8tjxnzFOo2rtmf6sK0VBMFxav7gDyRJ64ZGSjFAU1hRtu9okvaIZQVe0qdXDoAbyEDfje6a2lZAPagSDVxs
LpKdXr55IV8IVI3f6NnUjd8Z9HfFeRU_Mk0uIAH4uodgzjTxWAgHHqdo6lXpH9z1TREnKkZnn9yZ-XgmaK_9iaVz7D7tWChcLu8Ym43QXK9A2f0HALMdF6By
RmH7ANZP_dwb4nL1_pe2LGxi8FcL31K1jhzRgMfKzFFh0W9jVx-ItwX_9S7FK2e5zSS2YtHybA2jJANf84LHKg3E18UImoY0KgDJyPMDDBjNKc_jMAa0jUqV
IwdHgJZB5b79NxlYCegcX5KSJgHK6qW06OLGIcblgLtXWyG3YLDoxqgBEiOJO4gEid7ACVMlTCpPDPvCgRGQAV8QG2cbmrcxOaRUiXagqBVIV2djck5ngfRj
LadHyuEkRoN5lbvAo-GuJsWls_KhkhylcL9ASDoUseswVuKx36Kn9UpYS_8F97g5wvT9ZtmfJPFZzkG-I2RO_LbwVdwOKfgX3YTlsMBSlO674rPJoeklTbQd
Qjc2lSB1K0H8NvKgjwSs8qHxXPE74-PBQLC1ERMMBPQIljPkM_LKMkcZfTKeb18vcL9AekJat_xnbBXsfdHGxPpRFveIDf0JZlrKmamVBRwonLDAqy6rKrDA
4tsqe6fKp2YaKbfKsKaMKvAN9r_dzkSKcVjNEXRXyPHnAQLdxRnbur_tASWh73kPKbeLUiLhnBzsthZf_WedKBuzcTAsv4-KU22nOE-lSDlz5MxEV9n4BwMK
pXzzsv_7LUd_5Gwlht1SkucK76KZGQH-OqDRPbF20NRQDrBo6jcldIjD-IvnsFlIXxUdYb8fyDoVkbTQCrJv5Ox7qq9Alh95k5Kcl4cOKbw5dGunfQQoHRbx
lnOhtr_Xk7QMzx8vZ88elKjSP-b_xivkpLLLYQ91-Irz_zSzP-yjiwEPfCiiKmkLs_JL-AXPC1hmNtEoJd4XIhEetVzE5exwlX-hNsfjMgPFkl_DA844MpZw
zOD0kXSb3g3YG2dBow-rl-lT_sQK9BQsRx1mGzvIH7zN0kdM5Ww5jRPmM-MxfzXkR-7MPJV0mgsKxsv6_6kuWuKJZgTKNYsSoBxkpsDAZ_jOE1IMQk5u8cco
D_lRM3ZUli72rKtBdwbAUdxXsXQEoox3mha2If_R4upeRcBXY9DcuI0ZtwwVhl-sdXEsSBmO3sJXzkjSkSCp5HvGOE66eH7ZGfJs5jizNeSPsnQEuycrA6ds
v2wlmuWKcTZ22NEAbDwgpdq__1Kj73Wbid0eEum3nNRTrs6SW0HRk2Qd0uok6qzEQFksjd0iTNVzCtUMMxsu2qeekws5SmrPkRVxN__5NQO44cpXNdyzK6mN
ZITGOaviuV0hPEHXHXZ9NUJ4O26xn6VX44y7klzLumckCauJnrFUMZXmEZ2HBXTFV6-NESdJmg7i31XXLN0DLvcfx5eMpe0HDYrNSfNWn1OEFUwTZ3mwmbLS
PIkU2bcu0nFfYgi2lhURcwidid06Z11FLxctosKddYoSqltl5az184rmRxSfTOdIiK2wcbFngApqScAGLqzCYOljdl7aG89S9PKTMJXcTCDuOWjNwDukE3s7
KcotZ2USXGE9JFTs0H73UY9X-9DQEBgts-Hap0X3fXFDfis-1D9aVBstonPkjcOqp-v4B-XkdeNZUxiSupQ1nDTTpqB9nVgW4bWyuwdmlLr0j2ussAkJKFAv
B9J41Q6oYp-kyYN6vyb-8X6btk_doqHduTgk4cKdzepEGicbKhQKokfgBj_RbISdqm56HAdp-_cWb1vUQ1sP6lTsnJQGY5BNG69AZqXbHwuIdAoAxJIKXaIF
1aPNAON4PUVXAbUR5aj669Fhs_s9qbGI_D8ecrK1kqf0j2ks_fH2AKJfrSAjuubE35fmmd53ejIt-xSnkMhXnhYA9punY24MnTQVqf2KLwa5VcbiR7D1YJWP
C29AtR-U8zEQ12oSj3OjbPAiDYq6WOGXFRi_KrhFc3nM2_S874znGIThaI3VdaWOa__xWOHYuo6h6LCXm2_nwWb_C7wbx7w_R13wTNyUGjusW5BC74-W5ACS
vWH6F2OX2zVtwyB2CwP4-2NFPGTAokhfsAkoi73zkZzJuXdJjd1RIez4xyj_gTW45gvdzsTAcJb5jr0IduXJ6Vr2QI1Ny3L6eDGva32aDYrQRnVufSRggLHA
3_TnZElloismS5sxFuPguI8iN6FrbDr_b1wJqAhWK6SZ2zSpa9XIZa9bbuTguHhAj_YyK7Ba2euL6yOSxJ4DMh6nNneQPVVZbq8ZunTAj7ewqFqt5awoxzdz
CTZ2DHf_W8LBN7R9FJ0HTKvwzvzdkkaxTWiaxd5bh9H6Bxnwyl1BdY1A1EA1La_wHouuaFZ4JngwTNzUBnNu9ITSMUlNymWYZXkggoSza8WI7GOtxlxwgZ8x
M3Ykh2auKE9uoaEbD8PVE8dI_Nyvpffzjq1YJCLN2pUCXUAfPBPmW2YvKbg_b2Rx0maJYIbXfB53zrSjtD0gk_YaH13pGWaJ4Pm-BJQcX15Tfq1QMxYdrQsK
IkIoIwvQk24tDYqB9Q5DY_uK-Bu3vC5GHkf3jbaSSCghiNf2XRrPFM4YhYQRzW67Nt-qE6tf_zI4qHL2jyV25McidYgbafuGTtT_hiJ6QKiZ6Sb3jt1v61Pp
4eAyjt2ENO64XL9w_EJ_ta3Y7uKc4yMJOVTdIbnP6Nx9qOnP-QNSABjAwH7LRuQhOe0eKJmP1v9kuSgFXIiCSOI5YuNBRgYKGXHGsjNzsSA9SXZSkFip9UPK
nb3zaYyKJobMl-G2pKH9MCOF0ag4GMT4b2YU3Bg_JedYIJRlml7ggVgbHiRdXTAZB9G8WoO6Pcfo54z6WQHJueQM72nSeieI3mitbiQcXIZHTaHzmr5v_yEe
--kKE8izRgIsDYq5VYbC3B5DQPOFB9oeTrNi0uafhJPXZHkfhSasmiA94CJeYDAkG58fOSJ1O5-hK_A-TVSa3PLIPEKhqU5ZlOaW5WzA-xl_PpVAWZFF9AOq
FboGXa1Ay4j3e-mgfRVNLcQMaVhIGAS4fsBVtvZI0wTCFx5m8oWbAZjGsbbiJ4ddDDX74rDwr9ocJGieDI0cN_tI2Z5zCrmN0mgbGwi2_prC0mAllNe2fTPa
I_1BDDdcFTr_rgL0_tYIBQNX7GbGudWINob9U5azpLhtBwg5EqiyYJ0bvbJyGgbrRMNAZO_rYiZqUI0n9NsalnDFqgB4MGmdu7-rS1lDKFxGL18aBPvCjG26
4AKc9vYJd7cz7Tn2AQzE55BttxyEF_3-Xs4yjIYzjt2j4s3bnoybtSAfiqmENB0tZAT0b9ZJ-fHNS_K42vVbc8MZNFfMFFcZyPGzKMgLNNILqfWOOXpnP4hQ
K68CIYNEOdN1FdpZkGEcn9iM-AMnfGCI-INg_hiidDa5--5mF4L7bDgh9rWuQIXVehHV3B25En1FXgk2EF5WfvA6Qk66AAny4r42XgzOkDrEnNxJeiIJo4Af
lNeoid0dtBJmuElFkFJB4Ft75gwGXVlpyHStBUkHScF6v15-AN3P5G4bmg2tFPrIVwV2qmaN2MWnli_2wMBW8mltHQVoDKweBXTRd8Ahb49kUFFvqq1YIkUD
9ouxlrHoonL4-2NVmSATnQc04bJcnnQECN3RCw34QoVxUFAOeMysBTN2ZQbXuJGnqF-Pq6yu5QR4cnQ1N_8l5gxixlx6wMqVJqo9oyx3mibwzIJM5cw_7x2F
9wR4dDAmK4hFPYXxkpyJD8Xj-rK1KU9usd_AIszx9ai0U-MR755gRLe2ACLynC9X6EnsZPrAO4gjrLE0N_BoXfBMzYoxl_sg88z4gLLsceKp3QJYEvnsviR1
b9XJF6BXxBk_VJp5OOzJaKAKpjVzxJSjkl8DJ4dl_Xq2oTwfACeNbCxS_Vihtuait5a3oTwfO2XduIRJxa-1TDvuaWQdkKFtFtKy2UHtmyAL2mIIhLDP6N17
Pold3jt_rF4a_vLoVh5mMlU_m8SSnc_6aw23RYoSo1K2oTwfl51wR8xgNgJxsszQH4293lagP-6kz3KGzvMoQrEo2oI3OhDV5QmfHQBq_UvlHC8-ddHA_MLa
_tWgJgNKNqRstxHahrFgt_txnrCUYT85kx-zKqcEA5sm-ziVemkEA1bjHwuTJvaezUl-rt0gyvK3oVxk3oXzAP0iYws_KvaDpqRq7yENocxk9IClvLJc-V_j
c8aLmb00mdgt-q_i2FaUgEM58HAWmFxnopSmHmhnL63__EKRi7yTdf90gcbF5VRFZvQy_Rj6o_FF0aGy1Up_YrOWa1XFsf_nfFqv-w-199xsgIVBzIiWsGgk
PMhBl6l_aIn7onp9jmBjpzcq_r1sxV_qQD7-Z2U1nEr9-_DeoTXVF1tB115F0_Qt5G2Gn1FONpoH_Mq50ea-5PuZuaaWyUNBPwHuOlkB9vuZPZcq_-XeOVkR
RGn8jeAVs_y1
}

sprite $image376 [147x122/16z] {
pPk9ZkKe34KXRFQry_-_EqeZh8HGefagNZLQC-jHVBpWl7RVF96J-wVEKG1G-7U0V0QO6IZ7FqAK65mFE7dt-oTG1MfGyL-GYE_djvNocS7z0VBlHI--W4of
NvDeH5IJZtv1AL_6GABWtoa8YJ524ZrF_8fIaS0CaGuAUfvwukDAMU93v045kO3E4vyj2DOz6f809j5P3nwk5__9xY7re4caRoJ6cJwO-91s00ColUtLfGzs
3uWTFGr8vP5_kv4iPY-a2gId2fxvjnd9GvvCCAJsYj3dttOabGxAa3eWqtrtu70nO02bvrCYqtqxagH3f8C2Af9W27JAiHSfUWwZwAdYaVXgSWd2LfU48Zag
_8Bg9R9N19nvRn5GOKy-eLTg73F5zRZNfVm7nQTSbNe3oHD8Fb0408WI9KVngPGrtfj4yg5I2OWe1NAbS3URT1BLn_r8Mg44lXpHb1fBf1-fIoKtACOHYodL
9xuOdvvnTrq2YKXLgcJ7LIcJwCAonthWDrTlJywOb0AxGf1dddLEoLwNH8WSXQAcb2j7LEaI__6usQKYAebyed9JAbGaawXpQZSI828XPSSi8hKWv3QRVE7K
vi3LS3sLQhC9XdLW_mXNeL3ObMXAoL2Y3urmG7iraOv8HThZe9ceVcw40qmfS7ti4__sg67x21TX5I0xzYGY8udiaJSZrH4E5KfHbRfS-gem2VFUhGwqZd1o
LogejCJNHpDfbphmngrE5X5k8roDdeHefL9wfpwmvcL0H0ibTrEAHNGa4VQlUMs4Kos1N27Ocner4tuUx57AGni5N_rMMlW6pUHJQrumQckp4QxbtZ1cRwYu
xRPRbIhPSKA5cW6PKiUkssw5egEESDsKo-DZQzvjjzqQmZh2dVKC9Dgk5DbjjsbERANIOZOxFreG26AbqfIo4KvbmhAZ8400KMgbqaOuwnxTsQzKgA-ctNQj
84YDsTBH_3FhN34AzbUfR4ej0q7FxoFvn61DSN3R1MGPo92--p5Ge-VSAdQnsoxMW6ePop-pWjTya2DkIbcfN86gwMb8t_-E0tPqf1elk-tQHdL-MY_y7bBY
nrUJmZuLKuh_b4hHELI_fSi_ynsdJaif9tTJAeiW_OrIpujB_8v4TgoDP4-kEWJH6Z-UAjKDmV57VWK0QV42k_97AJIbGfI7KhDLxrb-vbS0KaeJk_0HIsg8
T3s5WLBZzVp5bxybaHsD7YpIbCgEAo9KSyuE-GkbRaEmhGtfVoP-ZvGyURPu5S_EEftMfqwfTypQxbaeB2V--q1Go54isZeTkn9Icp81L-9BAGpNXdhAqfVe
IFWoZH799wQMRVcgIsPzuH1A58lUUDLRdyG6pDN4v_TdoYDb3vXIKGGDKNEw1BFeIRzHkJtL0JEkITGVj00bTrEg5W7hCUJPPTJ7fqITv3PWhYH-Vz3wxNqB
9nKfPhMnnUKONz_5-nMKF0RCXSJlaLfw8T0Hcr8YYKAWR4fTJ_7nNVmjkKplB2RH5CbM9Ycxsw8mPWSsfM9n47slvUo5dJ9VOlYQ-5CaM5EfMpXZp8xlIhdc
jgANlDQb-Pqb0Jn74Ys1jIcLsPLaqIliShefLTTECfIyGxAzs5BS3EcYloiLrFQwgLnAsNkpT_AIt91cIun0SoRD5xrvBX8k93IA68if9O-OdPtaXZHHQkeJ
_Y1vyxoMIHoixR4uzaqfl2lbwwu-LShdMTOPqdLWTIcJTafrCUib1zkPAaKJgEmDoQ9tb130LX1AFBY8zREXvCBplTYyWjk_SuYTLX12pDuU9ORY83PdZoGt
fBbIyn854AI3KgRiEDZc2GsfwsuckI6DbVAptt7s1mmOZpQeo2uNqZQsOBXx5XlXblTYWVwgksZnHUpLF9MotVDuX9ljnLQKwYldGJUbGl7eTi_wbdoEn42Q
tPd64vqMgmblfUuIlIINXUtXscpm1mbY1K4viCj4EXtX5bnQKWftfAQKpp40pn6kurlOH2_t650mf5wfUoMI1Q0-Pgiz1YW1hofLtYDS_rlGXUgzh1JOa1vA
ZKUucKHVncnzRB6ZhHcFHxZbXVYwKZqKYa4Dkjjt95eVM-nEPwNpbDN4Npt7N_KON756XS9SelNl1Uiz1lNxZyXYuYz8j7Yp0Wof4lrOugyN13lHaFvUeiMO
hVUOmv3-L-9lK0h8B1LfeNiidVMnvV7pWNqIhQyqP3tnzoh5aCqIhVUO_H-TrtlCOlVOhzHcYTR7bWs9lqkfzSJVhnHuLypcOyl-n9_tc0s9lrqfSFhLFpMx
F_7NUypwsBXVgVs9lpwsh8-DMtlCUkBlLsgzU-ml2EiIxUynwuc_NwbLYVQVID-DsNy
}

