sprite $image309 [270x175/16z] {
vDS7WaGX28DXr8Zc_WVUtbcc5z_aEmH_i7ifpcw1AF0LB13K9j_DQkhAu3Sl9gtpDvWkC6gcgKx-PrJJKvo1xFa0Tu5YLNEpcOewkDye9i5v69S-614KgvgR
LM261uhd0pn5jqVKU2eeLZKtgi8CFvmNvOCHGM667susWQfAdO_EGFPyW9S6nQhcPdlegagCTV1wNBAgEMXMTVk_lZEGFH_WhNHRNPsyeQPIrUsFTV0W4cEz
yJwmuHakCTQTWUpv0E_D9MRuuR3a39S-7vth64MnghakMTKS16Ruyhy-k2elYbNDGRAgkRPSLIN6EhWDNXIhciCYLPKOw-3MZA9OrPnVgwhFxPlhagCw38GD
DWQiblt-RtisXAw48QSq4_Q2JNglV-ShgQKMOAWj-v0fT4UFM-qiwn2HUTW16O9X66tQXyfDAv2k7vOAwvF8VC0mgitw2barJyi_Kz_T_fFc9XJUfB7LV40L
B-kgygIK3h1eO5bNXL1faQIvCOMVqz0iYPfRa_ysZQLLa4k6IBCuQ1ys3TnOb9816ENHl7teJQMiD9hc4Rv78p_HY0tpiBC-IuCqF5BBzj5zaqRE2W33x6Dg
sJw-HmEg2i3toKL9ZTk7JGEt_o9ESny7XvRje_yEZPN7E7QzzruajMmVDWtowCUX2qFJzZ7ODCW3K_G-31veUbctQR0yGkVdtlS9rrhMquu6xNJm_JoCSgbb
VTZH88yn-TZxSArb7JiQv87OXzG3kD2oFhsamNQ97W2ka_KzQNmbWMNvIBZhAikwl7BHJ1wWBc8VyGMDWfnLOV1eqJww6uqyXhHfb8p2yb1GLrZMKodfzlyW
pvsILNDMN8O7b_K1h9EuCOwy_CBrx8FgffL6LXHeLhh7HUp3VP6NjJZAsYwQSPbsIMwdGG3enZkkmIC9t0kDQxFGEm2qRnz90BXNwkO5nxrTSYO9lGijBki2
aCPUNbOUMoFbVrehZmIGncj5WUewQh6YQPH74bWq5llGcue-TX2G1zhX8G1i6gwVLnwPjaeC3Tb70YmQL13GEB5Csz9OkoI1HMDl7_JHmWMa3HvaOTEWkX5W
SN36D68VWgzojdnw_F15SswaF1Bm3WrcVQpXfJ2yrCmZ2NvEWufWU66S0sfk5m7UfS6ihxezVFo_VLJJ93ODOrb7mU8TGANJDW47QJ3hipXuDAsFHnAyGSDO
rZKhmqjLzY70KHhxhFz8jhccPJq1xz2mxIFVYyF8jbKq2INH_Lnn6rwqbl1YiC3egBViW_ifZAnV1Oi3N-7typQymCZwfpSC2SwGcVN1PBiGoKQxdDWm4DrH
nKTuoVU_Z31ttYRft75r8o-46NmMPOINCpP9ykwucFMXkZby6ELnkgawkD-di2xhz0u0PsgNP4_Ltwi8lk70y68iwsSoZDwzAJlh5nQ7gf7rJs8OmHsJ_M0E
W35jwrp3VvxrdxFSlxPJWmMcplr1ZLyUH06I_frzfD--Xh-PzK40Sn5ZMMzWgXhsmV0299Gf6_PHpnh-PjR7JNSQClcInU1HzLIrxOEjCXSjMOiOoteDQ_YX
h8zxnqW9gMGnfai3KzLOrbaSEQGCwi_pCDVmplq3HRdZI4KX2J32ImjJrNwkhvfoBjE2mdYkV_hZrl6iVyCHHm3cMtHjJ5Kxwoi0S3-5iPoU-BXrN16RyCB4
Jnm6ZsgdgftrmP2xmR7bqSXKjRC-4HG-QTZYe2euRlsUhF-udnxu9Eh08wFJQ6IMu_TXnXTpfpzk7S_ws1tNMHv6rgzogjhs0M31KEYcHhkS-xXrV5ddKyhC
bs6CTgbwgjhsmLiXYyEmZvCVjuvdVNts3i2OBhLCrUCFvbOQ1ey3nwqA5CaZex1Fr6YN1Wp3olgF7RsmF0mU9rt3ZsTzPXRk8DzjbrJjLBMpFg_hNxQn57Sy
o4B4MiEhL0GsNqHfuNW1vixZ5GyHGIx6SQj6CUkJndR6f8WWcsLzBGmjfLImXXzOrl7opNKVlvI7t2kZ5EEuLQy6mVOLoyUoBXCW6nwoyZ2cQiqQcUKoLxAd
y3B7cJo80wLKFbNjhAzFdqGL0BIFqJFhipQq5FEHKUtseOlOBdZmc1xRXopAfRGmLUrbdKVJZ5MRPMmLIcbYgjgdGde7W77t3WobfPsfQcVziXI7c_74Gvwb
BKrLE-jd06wO0wSlPAkcfggTzHSQlGkHFBvqov7ZLdrP7y0iinl7FgtTGgrKUDngNJvXLN9JS74KG7SoZbjjsSUg8NJUzK5q9mHt6KMiIi6xEKNTARaBgPj0
XG1SXOQTzJ66cGpoBxLCmyxwW8oaKNufayRLD6BLCusIBqY3MNzFeroL1ks3D3ABWpGkfoWV6blxq2sEIzDmlIYLBrmRLD8d75a_D3RwqFZG-D3uqB3auvZI
XyPMtiUOqf-dyHy
}

sprite $image309 [135x87/16z] {
nPW9jgiw30GXcCdTBVQ_sZluwDr1Vug_Wrqhg1EL561g89tRF8tciUSpdscinBnzE7oGZsMWHIeIXRm_1aaiHv5miYSo88fVU283eWXqJoH5YP38W2ZYPDQv
JnHRa1YIo1hdCIAHT4I9zaJQbtH08hwapvAFD22A7eduabQJjtbC57zDf4CKNHD9rH9nUGT4uOH7W1kYw9x8NB6a3OaqNEw6H0RC8oJIlgH34cc8ek6-pnLB
UcCYEDR77uMb8Oh6H4ZYsFPpNtRaE8z-YGW0IO0u0pqJ4G4oVt06kYOYKfU08D8x4SckIyJPLIJzdOQ9sFRi8lqJSGrHtDUq0wCISGtAi3xIEImHro2b8wKr
3qhaDDSWZHyY9zsZRo99NngKOJj4ZBWYk2xZ9vBeGXr4uhlcVd4xLJHCdxX7vqIMuyDcXKWL4GuGsPV9sQXFp4IvICz4lXz0Zw-XIEgQI0QdRvOiauoKA4cz
9WFIDPmL9eab4KfT4ibaq2Y9M34myQV8dVE86fw8H6-LaaYuo8qIKSCJKV4mahSc0Z9gn4GAl7Co6GmQaNcdbJuK4hb98ch4A-8dvFM9WB_0z8kO22NTiBoP
lzd3Ct9CX9IYoAldmNEP8Z4HoIGBL-IL4ihhv4HY8bOyGY8lYcARdY9b5IWnNf7sA8x7z1n-HOnnUJj4yNTNX38YY3H9O9qgUPmIQGJml_zeyCIIFfC8HG9Y
k2AtHn4JaSXCCawcVXuvDNontML29XbQhPHGZA8-4P4brd3VxuuYac0I_IbH328LIzhAHXCb_q6-H9wJK8oY9H6wXoWnY5HSxbQMirZ47oGtB6b38f8e1P7g
ADeJaRb7IAJYSZSp7wKEMd4XaLsa_l6gFH5IPle4MmPzCfact1b5J4HaqI2by_J90AuHBlTTnCyHs4aK3maXYjk8doCe0IJnWGcrKRGdKaGEgDZW4ugVdBLH
j5-HBMtWbmSQBdTB8iInf0CgD5pknaGevZHlaCEEyuXNvDoBXadAqo1MI1cIx3890mp25Rak6wVXYKWornZ7fk8nMYEP2eCrLfFPU8qvhVkHKQtn3W
}

