sprite $image181 [227x165/16z] {
tDT7mW9H20DWwWFkV-2_zuBT6VAjNVaIedHVl589ccLLXH0ipNgrc21nr2SZFEprJIfa2RyB9Y0IzHTd0i6h_f4WbRHgf40CHMynH0bx3Z4KlLI8eUY586GK
hfAywbH6etYT8HLaABAj9409G_ehv3oyXAa7joHjzAyrF-gXKyUMSF6ndmmUcT6Gqzvxb_g6dTfQ6vPHvtDkxwYXEBUySuQYuoCgQTMmAtm_4uQY9xdhIl9L
BeRjk99-fP2nx_HlbkKffuA_f_EKEAJkS2WUcJUpnCPP80YR7Qgxxt_SVqci85EnG8d6Onur7fjFL2yKXDGLvP6vjX4oJ3J_veN2DxK1qRIuKpsTUvz2mU_S
5JMLnuWgeYRfZ9zLurlvlr9ta4bC1KFIo0rgXjro1s3gVBoFjmOrpLypDrDGNiptZsqXwQgQOkxJlOt_2p7xKARlCsV4raJl8PdLLDh2I6_Y_suh5FhC6R6_
YnJ5JB3gqxsF_ojgjfzv8iJjNPYHHYV9x6tyNz7Tp1cnGnBW2qEIkxLJDZwUjs6PFhSuQYpqPLSMYXhEBkKSyVotXFedGjANBX1VNep82iqKaXSLYa1fzQM8
UwXuSKyNwLZUbR-166WV7I_jrWh9zlL2hMvyopLSLoZoFhMgulJiidyCxfHFgrtjePSlrnIGr8ZGDJCv5qCfV3iF5z8QPgrRAwI565lwhKP7bNhPMf4QNLxW
Y-vG9R5E0UFNguPQSyHOu--xjRgZbcq9Yrk8okmNVYSl50fVDqPqHbSfr_wqMtETy2iCqyBUCRjVTuR53mbAzep-DprT_3PPUr5G0ayNNFxY5yLnblQCFCtq
ao2aG7HG9dJvafrTVbfgcB5IE581MGj2bcbL9eo2DVFJXLoRV8nMKt1BTX0KZbw3M6AfSaYkR-jpduI25YZhznKa482gxOPAYmDb-1RHnDEQYRe1UoaagV_a
HOHG2ScsOSTqG9Zb4qi404Jks-Nyd37w3SV4qvfffKUadlKZbCwJzFx8Cs5nFIWf3gEOwQXdY9f9v4PZQx1xBHHABz0-XthA-N3vAAQ0KRb1xzJbCOZhesNw
p5k3zcvbFztY1vvs6u6a3DJJaEJipphrGei87P529PcMFI13bb6gDOmJWYLw9AHKiixdfMcSVSRu92f6Q5V6HOm38RcHQLZ6okb5G40IIAcJaAHEZFDffJXh
f5nFkvARJ5fs4JS82P60b82GgJHIup7pVma8Ox9qGkaJDlhUKTjaQ7fKAbJT0L1cUQsqZt5b8uin53t6S0sACHGpPeZO9hij6xGS02L-CZdDOesUH-m_9lqJ
wxlxCY0sj0MWkh90DLAXE49iXDX6nC2X7iySKt0mPwxEz2HEBAsq_FjrX7QRqdQvWDADcoDwUYEUSzm4-c1amKH5bBWubPKn0vxoeGhL_ixZGHcDttqv3dKL
cK2I7lY9-CS6K0BDUirLkpbvr7cbMkmOUdeAE654xsuOg59bTdbB5-m-B9Il8jkJPrkRH6dSON8w9d8C2Gf6b36zGEjZYT18dU_IxLh_WOJjeLUXdXUSROxQ
GziG3o5PbvxtuStTTnJo-VByl3Tawyn1xirv-bn3RX2Zaauh3W4xee0--LINZPj8a-XRtr4e75-gOS3XGqsnpGt15LMCHSW9o6oH9q6erX6F5r9ObvhOQp3T
dzP3nP5XckiEhqJQyJH3Nm0LOy9RuKNCyYm82V4P9DGJZxB_1jq0DyPmu-53Y346x_YVF4mUfgYW7MxQg3EjAscK40yWfL5oL0ba50n2Xse-PMhAemS4S3wA
AbHeYdnRA0uG1GG9fSqDLFUCpw9TuYgWvtCIRkwYihCI5AnH8yJPGefuPjH4HutCg0XBW0VNYhBZyx0mv63IA25E8HKtJZbQDczDZmelaflwxlhyrWrKyZr6
YB0RkmH8Y3D8QEFGKvDmupj1dBcr9NzmBgKsV0N55UB7QP4oOJPG42uXSaYA5Je4XvZsl7S8QIfiVpkV2Zx_4TDhM5LDG0rVKg4WN4SKOKRgQUZUsc4HpW-4
-VEX2h1o3Kk5pOgaIXfTHcH8iSQ6CWZmAQMCDQIOgGfM_pjr0Jtza4OPSGrI32Vz2kxdzoDZWZVpcueg1g6SHMH6YMJOdHdixQyFQWDSCmLfz1mYGufPSIIH
Lo92YgDUY04PSGMorub-JVZrYDjrSbVKX3Jw2qG1EgFMlcLw2I9LTiGeVGO4k8Z8a9I_Nuf8fK506ZsDo92Klr-5o6fL0hm4aSZEZtGDOWC5uLM8Wbz2vciG
EGZN4QzVoE93NK2imPSVXEHfnEiXQ-WeHqADJpowO__tDEBra3KEBYeX3arPh1Tfb16lPkHsqfUdYCMJeto1HXdnUiZgwIuF8_8bIryl0cJ4wo4ZtyXYHB8y
uihMypM8SqW1GUO1CHCWP248NuSecCcfEu7BDgFY0etog78zPF-hlQF1VwTwGQ7WeUqMsaMGF2L9YuI9ZBoBDBhTialuCICcmbgoYWF-c4OrVydat-RDmeXX
00PY5oRllsuPmt2gwW6ALlGVw2WaeqbNd0gdlk2dl58DoPA2SBX2EOLap26PSn3strL04XN5nEwWIDR9k2XQPaURTDg_799bqXV54eJxTtJsE9wtd2NpdYWw
LXJJKu98fZY4FIHwGmkaVGeagL1Hh9gC4qYKi2XMJy4X6Q0eDZxQHsqhzWNxeX2HR90TxNTm4Kdc2yPg2FbC9uYYFtocuzEQY2IKrbP2I6KwV4VxqLT1qeVG
HxBj0aXhWa1uKVX8yhN--2G7QjQqAD2qvWi448MD95_hVO7uek1h5b_hVII1MizCVW19N1G-adoZy3DT0BMUGh91lY8l2ZxJ1IqAFzC1ea0dsIuGFAtvcGuu
__jlIEADmizqE8H-fiFJceyadjRyJBSohN4xocSwN1G-alZvNryWU5hpaSH5uIE9d__r1OABmaSIJsj-fiD5uTSilDRxIEAYy0M2Yy974cyKVgRJHS6VEiT5
uIE9d__rCnqk2Xz9N1H-fkDglJ-FK-UuA7maSGZzJ7U1a1M5Z-JFqzeP
}

sprite $image181 [114x83/16z] {
l9Q9pciX28JhxWpq_L_tfaMC8UV-UqkMRjQFCyZWxMUHvqYtDqRg8D7U1wmW072Mz_3A92p8aTyWw22nW-YlBcU3ypQplhI0C_1UNCvy2ihpxKYlweYpVlra
egKNTSHvHilaAMrzHKV4mhMGnQiAY7OepPFvLvsI6iAsdoJpswX1qCy4_rj1OxV_UJczJXukQ5wRbkJEXs1yVsHfBbZNLQwXpQNdhuml5iY3xRcvADUEJPJb
cGD_PtonW1vKbWmLR28XEdCLPLpAaNvLG0zH5U0a0chVUVomEolG9Y_tGIGYhdFN6rylPvuFJLB7PKJYTJnANZ3pLmMj7sv8DYUIrok6RJLTsiywejXomSME
94RBIupM9qZ41OH8iVuXskSTOV9dKN2M2k88OXJFsgaphAYf4rGZJNAMJpg2pO02TlFnKwtyoUX4isy0xK-bWl5Tp0ZEvtiQSFtRTwnxRQcrvED-vuAYcrO4
jBeR1UCBcPg93F7gJmMnX2lxRAdUxtSLIy5DXtCIAcc1QEychuqlhqqvJLC0sO4pFyyJgzkgYYL7kVEvolPjpuSLfdLcf1ix65-m6BQLCcsv0aXsq8VRDt6w
K5aopWqQhYkiac6EXHd1kZ9cyJTrQTviQmtD07_8vY2c1QB9n73Z2qFSGROQ_eX25gzOGERLUP93iducmaWFCo8G9m53Unah4I9vh-Vmrq1qQSaBonmytfXQ
sxaG_j3NrwYxVAug77q4HOHn0plRk_wIxUGi-VA9f9-dBjEqy1Gh_TmJHuZU9J8zmJtTAUNMbI3yO8CUVXCl0kgu9OXn71tc0HzjB8yufFLb1Z2asf0NU3FL
FkQSevMR0mbGHGIhIxg0Lk6Z3-H-T-BncFG6Ta01F26X8M8qtIwtHaKL5wd98UWY1gRCDTeWIE5cA7enOokLuORP57iY788wCJAbkpkBrAwA8wZAViohL8Ue
u0ZLdgRkPY9FNYHwERLR1GqG6rvKjUtRuzrvPrAwNH_Y1On4ZuKSeTb3I7DFlrp1tRiKBs0aHgOoFsJznSrgfCVnaKFGG8nCqI7w2o9L-rIUWaPYHFAQXw_S
LvqP1Ot4oBpcJRfBE94J_qen3zo8OY24_bxn_O-Rwfqe7vcO3EdPygH1uD9yEl68I4pUsA-rlgAPrbZF1KyG5NEVQgq6yRLbcdRcLGCD8YENs1EzYD50AmK8
nIOo4r6hO_oecnpGG1j2AVC9pPIr-bt1k6cWJTwzVBe1WVpD1BOdS0Dee4rUVVcutuhvcDUz1goUqVi7Uem_-sCvMZgRn-jEtFsyU5rjRSlEyNisbe4hBUHw
j6pd2bozYIYWcmZRpkjo33mRvpahALuYI9wTBCN3ziUzWs4d3PGLYP1tAqRnUOa8-NRwYT0oYizAHCPECn5QHl5f0vV1rgBjlFn4iApYwriZjBpYGp8HVb9W
LHhBBpuq4f5XwQGWcGY_-60QcBSJb8WrZT75XmUmezAITY9fe5zyo2N2BxuW6fMMB3v4fHa3JHKVZ4GaDNsF5cOYyiM7OYGYh-s-OIOYdvH_9-8T
}

