sprite $image91 [118x86/16z] {
lPO7Zkiw34NPYxB__Vx8T5vc3DE09jyvA5CIu42ykhJXhv0fmfT1zIS2NqLy8vpXQv25lp3wvd3VV2DU53zoVxpi9uJHjmBzpfWhq1x1EzlImpS4sWptpdZ9
lA69zvQszCYDRUa9vplRKiG8Fs9qRriy7uzeuhsjBV5u4lztl6n-JOp7w5h4zxKbmbkC_jz05RSfc8ZOGdi_QmjNXMDcjz3UJzkYDGm103kKjLcIdmstYE3j
UozhPDJT6isOFskBrcVcOGWR_YJ763dlysFyzHd87bUNakOSS9wpC8ySnTEQVWv_q1QZlSJm10lFQHkJp5Xz1Xu3DJtnvpPN503GZCp872D7vYZlSekEWQhg
J-_-QwJYZ-_6s0yQEN_BrHOTNnOoR6fjTt8jHsLM-MUD_Q1JczDfgwyunxPa_lJIlXP-X2Drl2cCxPSmFz8y0_kNXPnuUTzhWG582n-JAE_JUVeKZ2RURlsb
isL6nLjheQ1uCcKLQER8yq3p-OKctdRzfI39UynchbXVThFuTNCVuopGUDG0Ca-UWTtwIoSdpTZ7h0GxD4zH1ysOfnpPTTJDutGEOHH-RXLIpLUyPa85PmLQ
DzTelnBsn7zHpcPTPSQPDqKCmoqpArupZumOamfq_Y80jIGL00xQoET0Jgrp0gUBB1rTc52Yl5RNgWADLw2HTSlen9gFoTdyvoUPPzvCGoJaodOVirgyLr5T
biWgCnsiCJPfdjxjifvu8pFK-OcYfbjcL7lzlOgEIzAEpX5dmzt8Lfjfh4BCQi3-hqNngos494Th1TexozfxZPGjHKdnlIHzZFTNo_ZJckCYq8ErFo-5Axgm
stj9dhsPcjLnwkOs1psp7biKqwj8YeoYb54jAkyPSJdS4sj_N0_5sL_ANoqg5jhIM7iliSo4sTzUA-z2MqwjOPv5CsOsPiiDh_CUdVrmMoi3I1zlf98oKtY8
LxoH_kOwqDvAmC1NOpQUSmR6_KrjU_jTQCkfLI0SrFp2oqpC1ZRooIZheIrDeAqr2O9H8BADDvH51fbAb7KvqACrn17C32pz8juW9K7cVzPiLswspl68t45A
0a-GHBfi4GeAMbbNsbBKO52pKF14JEG0y8pUQyxACgthmosf8m3PArSJS4O5q2JfuqqZrcdzcpC89lKSo-qlLo002I3JCsrvNMg2VLlwuGhyG_RdgQG349E1
6bWxvibO3_JvYS5FKBEo301Hv7beGxxm_Z7G0-IP4Lky3W0fCsRGfaMPO-HQMnx9S4ATB2G2W8Q03GT0Quwx7AX2WsH1eDEQYO3TibeShY6qe6tn6lfc3SJG
SFN6kzYM7geMHUxM70udpy2buQR0WIxUrB9EFHsUWKjjEGJQepanBok33mLhbkHoMoxZBNPh9c6t96EijgMdbcGAHUgqEZbYleXOM7zBIBKtCa16P4tR3-sD
w_M7iCfxIGhuC4_4tFBTYS_QSjsY2O4WE0A5WUQBXVMt2CVh6OWnnuLbBSRQ-bkFrsHEE1WQwq9RrbeKbMjZ_IpGVaccKcHZ_Qmjrqio6cltil0vUukij_R3
_JnUjSQwr9RrzfvRgost8D5PgorteGTh6-WjyPQrULcu0_QtjTeo31hkY7SqWTu4Qbclst9JYwejNuNZQJM4RwCVjEK_
}

