sprite $image3 [1083x469/16z] {
x9q9UkQWhWMHi13I_XVyqaCw_UvC1YoSgXNaVFvFXT7s_4AqrUOnuKLViJVyRoBN2F_Di9zq_K7R2SXVZtIyFScFuNzZhtJzYJomFQZZ_wdXxMUqd_dwc_jy
cM2AruSRUIV-W_57AQZZbF1lZl0VpAnD_399LvMs2AZsNyyvYnF-mgjCK4UDyAhQ5_xPr2RSXzb_j0Y8zWLT56MWZZl3IpwOwSCkrVOA_396FWD77NU6r_mE
J3Vh-jsL4LaIr84wwkDkbtutPxXd1L07wZWV7zQbFHozYeupK0VgE5yWYZGgWZfGHtt2d-GFwVkaWJfG1ypH1Mky0zI1EY3yadDdA3TQ0tMW3eZHssbqyxmT
r84wmFj9sfXP1TI1Ec1qjF4EK0VgWB1M6RayAu8wK0V4aBB3ZSYwe0xK0HNbqJqIK0VgM05vTCyZG1se0mRUM01re8vQi62g8_8eK0VgWD1sBsAHvu4wK0VO
KHCLr84wK0S3ZoiIK0VgM8A1Xup8eq4Tg0EyxKP77W_gG1qGqdQYday0TQ0EY8uutW7gG1smonqo4b07wbW4TrW2wa0TY-2E7Wce0tMiWJl4yvk3Eb37z9_O
Rxh-9xhzn5-OtsMVXRaAwa0TuI_y4OIq3wEgbrd13-z7-pfavjD17QZ3tOUPhOjY7LMpEWwP73fV17MW3dStkrIrtOAecSTZpwHxdaUyJKdr3-qVq5VwmgJq
V7MWZlZjYrO5lSRCHUh_fYGEqiKlKtmqyI-NkCz7gGDrXBkPAjyxsxFSqRCyN_c34Ercxd6mEb17k5bNQGSWbpzboZAoCDEjQzk3QBVXSP8wK8VxWZBAqFq9
muwPDGctBkqEH2_pMLeTg6FNFvKdRKoCRx3CiM2DBpP85547wgXF_RFRqZuFZIn6Z4jQ9QIRE-f07GyuXMcFNI0Dxz9g8ch3KGVg-5p43rtjkB8GqwHLHxhv
F5KTg8E1Ht_UrehtTWxQpGDre8xprWpc1dFW3Tf3-2r8dBPGEl06xI5y1MPkutgAESAaxOBs49vnXp_374FR1cWFuQiZkOqDvc30GNi8lulhcFkpLlpZ4AY3
yDyBFsIne-Uzp5l4GNi8pvHbd6mErrO0saFuIjW9wwGIJ5Le3-5h8IUSHG_4GNi8NurHVujbbdkrAkf07QYZvnxan6rPbrO0saFuaaJntTdEN8Ns4BuYexOw
XBaAxI5yIQxQweYyXz1M0Df3-BfeQNKCXXoqX_15gQoEpf23zX2-Ab5N7H9v1zuAG7i8Nnslgmvdih8CxI4ywkXioT8UmgEECtPNfhGwq1x2euv3fYkp5OBs
41vrH5j6l_q2AUqXFEhm8wOhevM2zX0UTLXRnJ07xI4ywkXjbS0Sj8VmfQbvvzvOvw0zX4STqHQHP6-5zX2Uws-Z_BMtQEMWFOJdDM6z-g0Zf5M3zX2UTw97
-K57RwMWFOIlpomuNn4sLsWFuQjJSNzb94kaj8VmB7NCweCEGHsBe0xKCGek91WlwA0zXAzE55maZMIwGdi8ptobRtX7Em-UzX1-AywWOxHYq1x2rqSB3Zeq
EGn6UmZFeCFR8eCrKjf3U0OT8MsHvEuAxI4yWuwhBT8PTD0UmlEvMM-hJ0OTj8VmjP4eE5qH1XsqX_1SVEjxHqBhj7hG7i9p1DtQCfCp7RI7yAMnaiKKxhtH
7iApHBhEnUqLsaFuoeoYlVJSoOKwba0TgCEBcgEnI4fx25yNYQhcw7nvXVOGlYnNtLOEtcLCUmXV5F72cvx1V8Ns4BucLddvKTXVeJs4BqcF_7f2splfxA_G
7i8NH6VnnSV1UJ3QG_Xoz2Z_lpouD4jx25yCYzp1bFP-XArPsaFuKdJFBSJL5c2fW_OGlZ9zHEx1fNq8Owc3zX2-1j8zSXEXxOCufpfe3-4hQ6D4RYEiVPXW
gOFs4FvMf9j7xiIbVHZXrOAqX_1teTtSSpUkxHDGBh3G7iBlHLJDXi-yXUXtdP5da4bx2B-8lc0lk7lahKI_zVL3h9BI7iAB_YikUyL_4bc9w2MUxZg1Eg2I
EZI_5Rug3ZPOK0VgG1r3sgV21WlgG1tF9wxZlfsDEW1rt4mCRGkmDxiCwa0Th72mDuiwK0VgY0Llb5P7Gns0EdOHen_zoqOTW3hsCqtQ5u4wK0VgOBZnRYR7
Eb07wdWGuLtQ3d83g0DGnmx2BsaRG1se0tMW3GwJRW1re8wInEZIDgEe0tMWZiC9DzI1EW1rl8yvJ557RL07wc00WZfG1-h07to_gG2e0tLKyOUsLxZzXZe0
TImmhQEEGg0Er84-K0VgG1tFnqrGHm5G1-hWIXpgG1seWpUYeuuTe0xKWJrG1-f07TW3TUm0TQ0ErZrG1-f07T-LC44TjV44r56Ik0Hrx0Lre0wMFIntOgW3
K4Sfmb37Eq0Tg0DY29Vkrq0Tg4FyquayZo7VJ1seOtfjudkldEalx0V3NwWiZs-b3jIXX3yELRtCt6VMmaghmri1Q0_XYo3QRNXa3QBp7HRQG_YZa6ub1Y4k
g8Fs4Fuuz1gHzn9NLNL4Am3j8NpbySVCE_6YdwlELW3QG_ZQz3j77o4B3nTrq1x2rqAkMNwrrBd4Gdi8Nn3fdlVGkVz6UmZFsEFBt77n3IVQG_YoY4L1Tt2S
bFOGlZvzrdI7SB23zX2-DkebtP4xcQq-j8Vmo2E4WnsqX_1FG6Tk9Qhjpagh2EqXV7rw55jSi09Jg0BG7iANnsfjXtQsM6WFuSz08pSYRB7G7i8_1Q-qgP6i
az8Umf_2bVkuM2UbFOH_319bTbcCe-YqX_3d8BFAqcHdiOFs4FuaPf5XX_2YCDf3UDpnZc57SE-UzX0UTwp_fn-SxA0zX3-BA766ipDZeJs4FmifiJOfoVOi
xI7yMLY9WrYJ6Glj8VnXp0ep5cF6Gdi8VnXQOSQYoHuBxI7yOOpSGgNjsT4EWVOGdfLINVSNL-1e3-6vHMlhsxFSOw4zX6UrmvTcB2oKqXx2roUg7YZbDOEq
X_2SxP3r6Gl33jf3U1PATNtemx23zX2U6OijpLWOTj0UmjTd552799iij8VmXt5LU3lNPDX1UmX_65f17JttOgZZew0EA764CvARBBJdhF0G5THXkPU9EZu8
wW2le0v9fYoqvwpmO2Kc22ENuT7J7iAZ3irbs6MXFOH77SrpCuuwFWBgW5v37PeiTz2UayA3rb17yro6kooqX_2eGtCt8UrqQ0_XKKTptB4ExI4ywj1SXcqM
saDurD56RcUYZdU2Ek0gemv9t45xZWaFLkSB1fRxcTAgGdi8pnsMzQjuh9NI7iBpuLbVFvw6EsWFuNbVXoyzRSw6qHx2rwUNElCjaQzm9fts49xRR-lxFTo5
eps4voLXYy-RZHRQG_ZgQBN34n9v2z5RFMWFuVaCoygKXKaBxI5ySQJW3eRdJOIsEj0UmZFeo7hBB_LtMcWFuHbq-Fhw2mCFsaFuodZD4rUMoS23zX2-BZst
iE6XizL2UmY_aIYxSp7pHbnQ0MWFuSlYTM-8I6GoQw4zX2-9LNw9NyzR2KCTg0Drt5jEs_3diUH1UmY_2yrDI7iV8v47xI5yEIHo3wErKzsHSRK2q1x25w97
Ra8tF7hMF6WFuVVGpxXJDhC0Gr07wa0TsqzhQZlU7JaxwdW1TQ0EF-SY-ymIn8QX1-qXV74qSX_QQhfZdJ117M-W3YOhrT-UCxCCynBKyGhgO6Ub-XTEPXPY
chHZKEseurD07U8dNWNnB4MCtegZtOP7PZhg-0HGXupSIxJFOMGrtBGLHFIoDrkWZXhX4SSwshQu0tt8wp3Z9mNKWJh4pRfAEn_res-kzwp979Us-r2zpD-K
KKSTg4FpDzDFbeXSaVkP6vPtY_Z3TFSOmzndlb9O7QWZyrY9o3Np5cJ3TRr2-B2kNwWBxMR3FNA1Ikf07M-4kzcbsWgZDlCchWq_X7g4kvcgj0-YBtHxmTrd
Bb1V7QZZR_pNK4IBQSFpFiQ6msobcUvcTgd-5v68_k2otvvO7LVKLmVgMB78fIhjHgJRp5kP1SwpbSF_9ZTGGXseOvtugH5JrRODKHkUjnDVb6ucF44Tg6FT
8_shH2BQpJrh45BZ1avzK0VgM1V9U9qAVymOQkOUMOcGklT-wuCwKCVwFDX-eZ-Hzg-GlvVU8slIo_qWweCwK0VqQhT_wuCwK0U4jaLOyK0Tg0D2ghqze3we
0tN0bBO8owMe0tM0jrLOya0Tg0EiBO8yK0VgWEXj4UI1Eb07kBGRw9xdWZfG1yHLuCs9W3fG1qEE1ImIK0Vgu1ZOEdqae0xKmLpb7LmpZm5re0u8QrKGYtma
g0DrCEB07gW3TO3tjWJsG1se0s98AufSde0wK0S3ZdVGHsGfK0VgW7b9-meOVA0Er84t-1hDAwW3TO2lUGDze0xK0TDwEnQvF78pg0DrG8mkxNIaspP_e0xK
0TCgQGD_e0xKKPzmqrO6_84wK4TzffksPwE5188wKCVvX5lNje4w0fbP5zI1EkepDqYZAABNfna4TQ2EfjtC_8LyDE5kNQKrq6xZCGfnGnqbmkiBzbibyo6Z
Z67Nlr86g9gvntbFrDtCkgfiQm_gM4Vq1JlE9kvk_-iW0rGlixfFDznzc9cgIg7se8vrz8zEXjUPwRpzljfx0T7N-UlDgd0pk_w5Ar370yFhcr7CN_W_zkh2
WA8GXW4Wq6ViF_1tTzUx3Q1jyjmMwwVQgJAHUD98OpdE-lH1ni59_dDqU7oPQnUwVgNkzSskhbsACfFJ-x0zoRxV6-MfWUvCClqu00000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020dAu6
CFHjJfykbuMS_azvqu-d3n3TfqwSg1CVdnvTNHYtTxRxZeCg5nT4CFT_mS_BcUxVwQnTQqWbsapMnvdinY3yWsXKqkcQ6qDSweo7JcNxVwcgpEJ6jcsMrjGj
s_x8-4P7mtjjAZV-JtMcnUiqRa2NhwLRlFs8RdI0I7IcyrAf4tCjsnxIYNxfPnS_gpKK6o0wsnxFyboC2eX9y90R7MJRNAmIHC-vsYPW2z7rK74t-w7qKh8D
a4uXwKFTYzzBLOG7DYcdDogwN-KgMOU2yvwkia7ld2cuzKnmRZG07JSwG5PuJ7XOvxBzqYkW0vsN9qUF_di3MG5oVuoE6nseMcX0Y-HqTF3ojOuomLEW0TC2
E8EVJXsor57ekD61qfmSSY0Xnw73AgsEZbIZqWxYNNf-yPvSkvD6EZg5NbiUXeuR7IZbOmtgA2xhi6shj3ew9CfLT0kH1hIm10m-m-H3nusEurrilTySYmwy
SwM5qO5f1_rRw30m-7NHSQDZC_A_L3lYA7IKHvDNHuS0HlyTT80FN1aTDpgswcG7TM4KLIOjSEsAwC2qe_vJw61mqqkZuqR7Lcbi5yhBifxzWALHqbFFn45P
5ntOLBaOEcGRgEz6nusEhT9Grw6te-3IQA-wxfpNHWT13dOnTDpekD7XTs-gsu_qB_KoWaOGYtV0yX0jYmxqSxe4EcvqiBIbsvDCsihVWWw31xGDv8yiQo0Y
Tmfa6VxRYmwSsh6rqP5XS3KO7QO3P3Sw6kXmIvmaNXyTcb1SNkE3t8DuytqnMHhj5rU4LNYs5T61BRK0T71gYLIO7Fx-XUXG6QGEEcvqeFWLlekxATnuo-Rt
eMGjeujtTYUFSMcENmmUZmwyH8lmPT4XQP0SwBZHqOO7EGiTfP5qM2U1BuVHWNrKQMLqC60v71reXJeG7JSwRdIq-x_u2XsMN4a7ElrnXr1uklFGaTMb9yRf
BkK1w82iS20wRdJSwC3yuQ7gIyBPbtGmtkQuGnWKTqz3Xsonai_HGHL-BG0TUKVTTTETMXyTDphwx60FERHbENPy5ONHuDy4Y_unT6HvY1fOTRaloqDvdSzc
rqV7ZOx4Ni_DpHI5kiMLTg3Q9o6iLqL7_4uLeS5TheoE6nsf-DO5yTOVhcpKcQcq4TzB6JJaHiVi7Nwmc_EbqN6Z8rLFiOFgyL3GD-7XwoziYlrBwE3tUY97
cR9JDm6vhegE6nqO2uF9iKbdmX2QUwoZv7tvRciklxIlGmTFvPR7G3N5eeDqXFBow21c-IFcjT11ZjUl7VV6_FS_4RrCiksG5rKwkds4tEXubgnym0QYOumb
P6LqK2uGSbM5Lq47ye07nuq0EHvuuArgaKUAdEiXUnEq-KR7fvBrZs0f-b0UXGxvqMhe46jjHSwBe4CTtdDqm58GJZJ2TmKg-K7ey2zeC3si_ENeO31sd7Zq
8o-53YhR6rbU0XtYy9xyqtHNrv11QveGoWVc8Iq5eyFlEIbAwwEZ3332ZGxIhIFBtu4E7DqKzdIDF6F2tduyJNxlgUb6noZ9hDDcRtJuHyLANu0EJ3lAVtyV
SlMgcBnBifTRaPMNA3rGDECR7SCa2vGwRdIGETg-DZhmhLAUVX_kfxyQ84bUZaZoaEzNgKgw83hyAhi0pC1mlqX18-izTAFZUTAWBrsgJ9gx2z5BSg6ZSN0o
ZJaDXbrlGhegEipzjMDUCEbX7yMa8TkUfV9Ml1ewykQGBJqvYvBaGyVJ7Mf-xYPKbV3TXTCrqS5r5tzpnQlMHuTVhBwaVZ5qbCqbMtf96CgF3gelScIIea_K
CabHuekZG_Q5Ye1BN18T-MzmL4xBeSDV8AsgyXCjA5je8Ne0EXAtcy5_b43VY0wTWmxTLNOd0t-x8ZgoESuqN14T-GKRXDAFkDGDPVFGOT2G27Ga2HgEtEZW
kkrPgYpGoHT41vNgA9ujYGxQK8L-qn5K9g43ELT2qF6ea6nM61SKArqF7Nhwp0hAYj2p1GpyuNheO3ro37lEIw43iM2yfylp97G0gVDmTC0VLHNox0iMy2td
XT1Xsnlzf1zK89mkX0vCE52b1rvU21r8lx8lqQmq1HteUoa07OXBcOKElLxMGIpwZXzMyj_Wg3bT31qaTcpP51d4tMHqy5xi4R13Pw03EQSHw41CySdeAD7e
m0IkgaybVIWMhTik6Ns8Adcd2WSEEaKZk87AdRdgIgkWmnhawBCZduuEiWsK0z51JtzpAZhq97JCFRsOSj6je-1QDS6xFbfKNdEZS8Lq_frNs2Be47W8HptL
paP7hWScUf0CVrJmRLEUd0XCOwUX0sakowCZEFqGEgbcIobSkTJsPs5KEqxDUC5yT5G8HGzdSZ0w-YNfF7x8AxyYMCv6ntPvTBItba9PuHCORIbMt7x2GhzI
UkqDr6q5T6JND-Ju1B7ewDlUKX0wS4ylHCT9QJI7eeFdeWFp-BPKA7WIlAH0IVlfwWCSm0x6Ny1y9I-03lDDW-4Yy1XqOCrAMsDYYa07shMcqz21RQNheuFs
5KohPWfSrifJFhQttAZZrVGijaO5Q28w40NLMnef0UXmI584Ef2gUZOw18nsMNHm0nlXOnTq_ZfZ6LpXzje7URTndz8AjOxY3iKAh9c8Zf92q86EbSUYGtbt
frWiEcGUEZYtLtVK8dhAsAM4ZrVQHteOF8UsycbfJ3fDHuS12BomuOdeA2aK7GMsWAcljuJ9_bTTSSpDNWqTpF159KeprBR2aW-2qa6WfBD3EDU6Sqjjc7uw
EWYQw_-JAUZmayEpmQ1lBtKvK9Ss6dZCWOmOwk_JSNGmYnJLhICJWjdCmCf70UUCb04S-ri2qqjm6AT5q96XjUv4nIQW0o8cQ4bO7jaEZDSgIw73l9EvwhzH
NrR8iVOICECNGz24AZUvyGC8b53fzFLST1JtU0KTVX8wZ58mEZGeSf_kEmyTI88uTA3B-460oSUeOOQ6ZrVmRhNazeuTgDhUKNm-EZ0-of513iz0HvMKWj51
eoCNNp-LlWuT_D4yNbls22dYX_Ob7tdOU2LWAsCKgr3gWwFMhINbfVRh01ySyKVnwAY5KZWwol38HLXFp3hGv1ACZcJli44fxPd3obf7aYFnj4q5snc7KNQK
zcQZmsyJdOeEWpi6eQC6H2wywMUZGqv1Hnl41hk3zQU_kTZ0GOPDHaUsLrtPzFkLq87nUiWFz5HqGDONXmu9Yjpyz7Vpq87zoD7eOEp70jH0T3H5egDMOkHG
TFZ1OVIsniRhegCEk5ySEWoyBHWTTNlenM4PHPx51yShD14T-DQbQ7IalxgHUiRXxYUe9GrGdOSEiGrKfGCqNHSTwg1rC3gCdmMk5eyEt6jdu6hIlq2T6wUH
eHmdpNi4VHEAZg8Yq94ET0H99g63IdqpUu9vDW0-41tnVya1wF1GB1uT17uomB6HkiMHHdFmHrdcTfUI1cWwEj8KT30KVd2bby64W87HLqR7ZGw5e1hcs9qg
NsEiQy7VP6bCNNLzT9JpqI6s_mDQWNS9NGiTzYNe40Sw609yc6CJcEFz9S4lUN3HTT4nNpG87LowYvJazvqgkC6TTSn1Hr_oj6ohuTY1BtfvkiJ0YQB2WIFH
mLke9CMBwWZVf69TS10iV02pqpheo3SwNZeZ6VWbe2FeHOz36dRCViLz_7MZuvaSDf0R20xyW5OHycNH6HORSBzrqQ4-PomGi1rqkCrDVPW_RXbb4VF_jlwR
w30uV6ZOngHLUWU58ELvyILXDpeUcw_BO7GeOBeRq5J3oXsyC_fkTDY7XGwfMmCStUiIfXss33e8xXos47q-EiphZ6Gsk8X7VQjbS591fur0AVd_XfT4Hpmv
yh1lPIplsBFZz-1IlliR5lj6T1nmHXgC3kb7g-7xnRofiXzZbcvqx7JsCYhXLTurJKo_UukM_EXU1l1cLNIGpndvXMnxIDYzs1MvqEz9yOIuN-L8yDKBeYEU
78cxNtxdsbn2WjrbIsxreuCB9F7e275WyRgxkgUpfCkt-g9pBOQaZipjakZW3Za-zqfj91oDin8Cp0nZtIKt63o06riT7MWZRYu92q27ixgWhnp48ioYXtuK
7c2Ko1mVcWTuXickXjc89V_IFTEmPWPqOD5hnMsDUK0Ejnewa7Sq0HreQktsOtsz7ga4v61yQ2tiGENQsKSoLDpUF8hgA8mfx1W1u80d1dGqYbvh7QQW_WIK
lmGT2iqu7nq5wlHlFLKQcM4PFeAtGy09_ewaFBs3JreeMkWzqkmpFbd9kqvHbfHUeuEXAQiTuKG3Ta9U4nqLp7ugEh2EuOpdCf8T-8Dv7Zfmd5zqUuWpM3TC
rYn2oCYX4-tUxAU5ZgJGcCKEZYpkFrWT7TXgdOKEwHcjj7Cv6yiEFXWICYIGsbHydlxEy45wE3aG7he5EMGR75MmVxYHbDe2w40JaJTDMHqTcFJBB7HK00DA
tlmWrP7ie7fmZPECxXy69ZwX8t6pn1CvM5A60cbK0wInsG-Yep5mjHNGaNrHm73vwkX07yaJq05zPBrkgE-DOmFVj1QrmOV_90zST4SrFF6Grf45kOQIWvgR
_I0wclOoceuEpDbumDKBeiEWnHrq3DrD0kqclKo0ErriD2nW-TXVol3tRlbjOQhuIevvzwCK8pi7ZrJmUnRUCt2jD1iT6E2L71cUfYz11q4hJaT71aCuHoHO
dEP1EReUn9-CZf-C5cv_yH0TnwZAQQ2ulA9LeTH71yuMosnqOBN37DlFy_BeG0lP97GOag7j4hQdbsG8EMfoQU3fIGghe1eMLdWpHuXrx0cb_aqx2hNYcJhL
XTde8B3LRdAKj3mwC7BB77Hav6sR79NsJGQCg0loqVIKXmQhKSl2E4EQJuU7HdDZKsx7SwSwOpmP7KbsSbQGCUkZ0-6Omz7XNuALTuQpVPv7Aw3_AF-61gg-
ip3NgV2GM6vWne6zr6F_LYQZ8-ckqHsQbxu17PW1deuEX4D-3-IyVykHyk6t8dRSIqO6gJGi38sUCcoXYFe6WgFTpzelByn6Hwhzq_YbEe2y63eCekLiTDYR
ya9n6DK-AU3X2xpIOIVHWSkWk6jXsK25G-4nTbv7r7lgEg6TtqspJ4S7rGsakNDSLKbVWmw2Hf-DZjmmct_faNtWscNxZ1m5ckaMITrGkiV2R9qZomSkYaUL
gADUJFhXB3qdc5NhGEz6MH5cvYpQCEdwwC3Ueodei6OABDLfL3lgscIxoS7SSp89EFCCBOmtHsa-PwgsogYrkzZwVXzpvm99Sz21x719qnUXey9uvMHqI2lI
IVqOi6EkBTl-dEFdL6d9pFmocoT_mj5P1eKMRf0ldXvIHq_FIdkamfdUNfyQqkcJi_Y9yNwLz4NeoD1iG0Tbk6mqEceZwAGUCQfkgChkbsabpnrGrTi1slSX
j70_fc4BZ64geqSjjGaythQgahcHfUZxDjOq5HtOPZyvraU7Gk0YEluCpN8DGeV0SxK6rlceQrVtUw-IwmQeCg1CgEIpSBjTHl7rKkD1QOS9lIw8glp9yae5
ZsZ_9ir6X_-eafhJDw433x50TC0OO3WwNdwTGkNuSkUCxVM-5Ep3pKJfupAXyX4Batf1DYu3rn5xnHIqd1rExdALD1aT_iCLbT9NeQCWnH4TwDmy5Xriln-B
FdfrSdKE7yGLQzHp06_WeFImXLaR81kjCl9J5e5y0n_uq7Aq-L_E8jUzASVwwAWOOuYEZBuuUeQb_Fx3yb4qaZcdEtpNs_PEzk7xoBBZfFi-F2I5YAqvolFB
DFTjuns7paE7W-jG5FyMTA1nIWCTXA4n0XsO9k0lsr6h8dhCrnD6pe7hvn5ac75yWWxqq9gY98vQLCGH7_njwC3bN_Y--29quEk36kY0jsmUXWxCvdAZa4wV
F5PsbR7Af-DMIsvn1nnk2rCvvGGdib1oOEGV8nK_Axb5xgF8_2TpLvW66_zSeny2foQBus2P0UW02VuoVxhagFH36Kbbx4R-YFLH2iiP1bXO37ehH1AEAFEJ
OtsnY3vKX2bziwI-TSSCv8X0HoBCsSgdNqcmELnCF76lQjl09LW4Vpp4mbnEY32ouDrHrR6zq1JTAflkAGvNSJZsW3UEyeT8jFrtAqToHf4VvG-QMc1wOP25
isgAbiGUwC2gZjnkXcuHTSPyMNgvLPQ7A8tHvmkfYQy5U7s8qZ9YYnaMeVCLVQXmke1ktRgbbjRL_m8
}

sprite $image3 [542x235/16z] {
x9rNWjim34G9W0MWxd_UDDcR7jlISBbKvlscodfBimo1w8JmWGaXX112LhUZ5PEnObIF3e1sp63huKN7c54QG0pQCHtFWXupO6RGZlb4mVbXnJi0sd4zFwn6
XqCxvXCvdKI7ZHgqOpvDqWcizO7GZldaT139qST2E-PJZhbHnhj1E-QprVGwyyODsl7uc6xRPkfXtjyJsh7rdTjvTDq335_H7n4rivplP-7xdppBLj9Br3wS
xSR_RCV-yB57ClPCne7GHFKuwuYbvz4OuCBtdunMlr9krBe7X3pYzZklRSTT2cZwGktS4KT8UfOCrUB73q8U_IIevLBhBHLmGJks_SC0I07UcQhfIIfGZ6Wb
gnnE5EsINCSEBIPf9DhwGJGzWpZ634oIGDHAzLWr_JC1yu63XqH7uCKI4Bav4hHZrDWVyaxpqPObZK1pfXrFK0Rjg6j0OoLuQCSmFTfuEQgc0z0ECDvV9m1p
3doQX7RWKVogHHpi1ksOHeNlbxP-XWfmWtQWCFIqjFOJk2O0j0E51DQEZCyNqOvvEFGbIk2pYRHZ7XLgHmCapovg1-t8W6Z0sdRG3iD_huIcQzX1EnJ-lHAI
hc47xGZ8wXWl1-t0qt3dB3ucCa8xvk6mIQdDdP3I3ZoA-nhmkKjPse4dzrUfuA734mRQWQV19WbjxgI3Tk1HsD0XmpBkj6CM5JRhA7CNixG3Z-9sqNtkb9Hs
u77ONeVE7Jfe1vwAMr_KORCEsh7of6F7PovOQ0UU1Zn8rGNsEcZ7oF89BkXxKrlvY7RG3gdzHROc-22wfWdG3doXjpBWWbCa0BG3YjP0NoNGVeYM0D2EoOLT
8WyfyxFb3sC7xH3DBSRSJwiJfXsq0zY6htdqhH-WQNg8Bx5HIZlaAwfgPhdibTNYJA51jt6LVZojOKSuba3ROU7_8du6reooFUUjz4EqDUp0WxOZRn-vAulE
FMIX7U-kHhKqkZ9fNj4Esk4Fr03jezjgTj2EQ5c77_RkB6K7xOXM7fYnn7O7xS0JLQ5PWCV8CdRGZhqkkmh0ZckE7PntRFr04_pLjaff1xvqFTwEX8PsJ5-y
SEoW7JjUb7RGZfS5eHsqOyUpSDx1KxXZXxNpnmwE7V4aumQG_tOtp0kMYhOZoKkewRqNRNC76HFvYhjXJ0wAMgxjl2Mkj0E00Up08rgQzrFKIv_HyZxBBy5q
o7N9Ckl20kt08tP2a53OUhia0BG3ZsG75YQso-LAsQsumVIGiVKPQCTAtQnzuKlMj6DucBmkLFc7TXn77B8MhRnbpGuSRpXg3C93E-PtExS5oeRH3WGLy5xZ
efMXQ4Tgvzzh6xWVHZkc8d7wlUQhLgIa7QcSVg_IhrhDbdP8dDumRMDNBRHZwQQq-R9Lz6c7zPV9opRleHtZlrhgkes_QCVmcx0Dr3Im9JIqO_x4mmy9Xdzu
sZ6USjwEFAhDEUsOJJuVpf0OzDr2EsPZWEXEwGUfrxU3TaZqWvJBsq4xKkv7oLUsWxFI7H-Y1-sOJONC9QqVfbp93kw65OHa-5T0E_0eQ1DB0d074m3jG59G
UrZMZnDs4JkOx_3qP-hMZrFbuzb1Eofm5kaTF7pGZkLc7LqFZ4E0BdIqOuNGSOCcYL1VBxG3ZuEFtJEuunZjc8Sq-4s3qayIWF63TW0G7x3nNQ05Kcd7B3Be
aX9UZnv5Pzf1EwID2liLP8rsV6Tlsl4GAGF3N1dO1mIdHQdDes-nj1sbcAgaeMYDeK5Gwp2y5PCJKknM_A24Bsr7RBtt26-rvA-Um4NHx7rq5aEZTt3JEbDv
JWZvgaGkzIR5hyJITlYl3-DlegJJY5Nl9wW7baCmza-YP3FzWdn3ls1cfPHQzxhm3zx-udP4_mjtKOuDAQAvDE_dQ82ZtzciRyTZufigRpzAyfM_ZxAWNWkU
Ni6Yuw4TXuWlk7lxZhj7z0EW8ZfI-mHennGylOpwTUoW7VYFAVj_O0Vjo6bdTJze1nvNHCb-FBHZFf7JERJ4TUoW7VX0ZjNeOw0TyxiLBou8xS0JrH8KBHvN
i8DsH3D90B17FRHZFk75qZZ4ZeqXjCC_WXcIXYEQAr8HZXtZnQXP9RqVebRQyuxGZXOJ_DZpDPBcyA0PEvGjV6KxaeYgMiwbrDhSFSRfyXP10tY1Qzdly0U-
nnroDfLuIQQMiDZMNs2pvx9mgdaNfZRtuyv4kF-G8KeVahVitx7dZFj3rb9orb-ZKisVftb9MDHVGjCXP7V6rF8NoXVgLvhlj7gdV25_mNHF2QN5kAK3Vtp8
sloDzjDJtZE5YH12FhDt5mKCnK001JUS-1TSa53yD7CEhe5tU0000000000000000000000000000000041TNs_0rcVrADwLuoEvrVVtFXjkwRFRHuuJ6Mkj
7b_LdnsujwUxQhmjtRiv3oraSI0AEoLJVFy7tlE3zuY1aL3SThUlXKdoPHgHvfb1fx5-PkQ5lIAUcLvCoYHPs6gxEWjQmxK-9FQXfaAx0yg8Ra98DtN0k8oJ
TBHChEufKMR6IRnWE5tm79bHNJx_wAdBD-y8xpwkc3xTrkpt2Y1KoES98QWsUsFMw6uwA38YsvKu6TYz9sGm_FpbI-SH4I07TCIEKaxJ4HlJgFq5Pq3ag-l8
jsAACHnhRUufYdOZ7HZ1kFEmjJp_o5RImIWRQUD1S2sRBz_Mcdn7HyUEhj2HkKd7nZKodSgzsjjJcXsqzU5s5nrGZ8S6YXpLqqVtNEgH96LSX-Y0z9TqH63H
uqiCM2hUUKVBp6WwoK37QgUbt4a7B8hXCDG9m-XKUWHTxtnlAt7bTeULiKL7Ptbl-ezyn-A2ySB3gomgCypDtBpxGbvyIZS1i-dR-LuwQDobqfQZB5JGuSyH
nwDbK1xMaWw8bfASfCH443z-G4SmJMArW77PAa-QlCxNyT_sFPVtZ4XVZVPXo7IXWvbXf8twZcoya9WAzv8lsOJdolMC9OUWmzg-lADZKrna6lVJiQp_oxG1
2z6mPxivzCLOshRteO0HG6rB-EoW5DQEqQ7TWDpfGAxfUT5ty5Yc_M-Z0-8edOSkGxnXhFtOQphWN0KcLTgcGs9R2B-zT9UEXciDqz7S7B895JVlP2x_FpeW
YcA5PBA7yH_Trpc003g-bqD6nY4wD8zfZNSNjAIuL1NSnfVxVqX7dwhIXZaPRLQywtH6voHrV_SXbmM5X-ZOy1YrxrZJmVH7_189qhfUOnaUakb_Fnt48i9q
3nrm-JpMB7Wgjc6W6KfHqi7lj88PyemCf8SjunRVyMnRypbSjGGDzSByO88a7djgjz8XvXYHALsc0vLdVs5VLRyPoD058_4mQys_ZAlr4zy78gtcN7ofoN3_
9XYmrIz8s5_-htqw63CwA9huprtPWudf7ZgqWz_eCXrjamx93CiDoSCI1GpUa57wK8nea8xh6nVYPnuHZGI0mt6VzhmNdEuTTB2Zmnc1l-dDT42U91dfB9Ft
DnQMo4Xfpq1_0xd1bu2ixN477N6O3bAPfVBQKaqW5PbdKGHQpxL-I3mZeubkYtSxSk_-O_o63isCDttuTxiSMIRrunD-wCjumNVvPA03ZdTiFtIcnN_iEtgH
pIIiinhPEOLoFkk1tgaljtXD5V5IT1CTcb2ucGVuy4jqK9Ik5NJeaWvzKAIzysDjJM7qE1rsj--e9VC0jUCbyByAMUxtMQ21X4IyAhpleKFWC8nVhZDUUDWT
5UrZc8u7wqDazhuYy1e_f0DbqMd74P4HOSe4Nc873YJhOzgZWnG-V_L6kiDtO8z71lSZYDIhtR186wO3ZVKsUT_dyHqTVoSTt2mYeV0cufc1I3DAHroWGmoP
OgpmuF0xw82rGLktsEbo9rqEqI4PwKMJT6Ybsq4wigvee-r-Mfft2Ti-QiGBaKmxYBWIbPUsGFtWjafs6YovI8S0ZWrc8kqa7HgOiBABDz-zpp1tZunKKAad
wM1Cmm4wE6iD-XJ6EiNqZoPqy53QyJuswmpbp8QW0E1t2GgtVP4EOA15oKG7w12U6ZMY5Wb9HSTAYk309-aGJFG1EgHA2NCuuj0yt4K_m1iVofM2Zlf8e85S
aIBVmwMM6HcPVfaEgkv8AAWvTN8mwh1Pqu70CaO7Rtuh7wKZij007IpD8Z5Smx-ZtJmWmUGVaRqT5S5NlDTOOuOZz5fagI40eP5-_kHWPBRweh5iOoEoMF-2
Hxb4uVHn15TzcYzT_bTn_gwptBHrqlQD3c8MRUQn6EtiBwHvzx_sNGSc_x3pC5aa6OZjwc3rXfe5rGdLhvm-TGnwnxDIYbmfwc65FDhpP3-fE5u2qJSwl6jJ
WeDte04W8GEkA_XnK0eqq7P1zMIHsLtu0XqOgTVkdyVfw8x2WTvHEhOZb7yx9aoQPLi9owTdmhw0Zc-U7QNi7n_syIDDQJuMcwGkcKA7eggyV8MtfTzkztJ3
iDnrEY_dyWv7t3r2H-HQ_crT7thn-7qKPoluszeAncYA0gKz-ufU3MJlqLceFNO4DcA-wn600p1SfuFmRVLBmtG4WhOAs1wbOyux5ESpQCfAlnNyM3vnXoB1
qwTAvuu0uaVf8BUcyc6PRb16GATMJVT8Dg9Wm_dTedA7ATVfuBoHZiUebdVX55j8qEiSgbbQdyvHTEt5GKEs8P1ZNmGwZijZGoF3e8Rq9lIz22ve-_oA3kX7
TE0qiJQrrpzRPAJ8CoDva8w91LeTv4UMEIW3OrlO5EiZJL4NGQYGz4FJEveyZeeS2rQAn90Kewfj2NS7v_7RoF9REbRIXoBBsA43BFZgf2bJZczY-1i-HeS_
yu2UTkutrzc-eH4z6-plB4s0_BygAurZuuSBZGYqNCYvesDuq-D4QaEikFBBUGIkyj9hbJtNTWwEUlGSG2D32UQYXEuBiUiLRHLwiRDkfyEtQmiYfbaJ7VJI
qAPts1N36GC-LD8XF_STDHoqipCoqsNTyGZgigbRkc6b-u_7pNJWMvggM4QQg6eaij9UaK65RRxvX0MPKHjr7KMMOZKTef-I3zQjVvbthP3kmXZpzmLjt9tw
D9i_2EhrEXtm45B57Fi17OICigzPXi_yHpTY3fW5gcKiwuZqUd_oM7WA63fjUZx-O1QNTq8AEBx95hrPjbUOqKVh3bxoTJe84FGIVEtzT0Y6yUvt3DBHUmh8
bszqu37amwMCVGDqW4jh4nY1UqlZukKz1uuQZlhO83eUe0CH8VYME_YRC-5OcllfQDYosfqw_gpu8ThE5wnQPugXuA9er9-d0-cWJoE9UUkFkm-quy27Pfrp
rDqmm0KwtbCGV9aEtcvOjuIplfyEnzfsdNHehsQHRa0juuCM7cb5IqxYqgFkRs6aWuPk63B6HiSU5vWJL8OpHqFY5ZCRk1pew0hE2tIKfy04Nlq7T13CFKS7
uaW7Xw-jjpquC99YpWOMTc9XsIjjy0J3OWCV0QO7qF046qPRpwPJVDlrKyUHdKFJ17jtqu5tytaw90DlBquQOEr3Tk3muKP8VGDCFZlfWlOs7UCZCEDZQ7H-
0vCOlVFtYtGWCPe7X863Wllfm2Ywh7IGZZu59KVUjBNws5YzMb4i5ubD4VAHP80EMFJYmtYS3mSUHWDfCD28HkMH5DHkf-c09E7Nt5gpo0G4lw23COgJlaEM
ZMQ9UP5aUqpRFfvz2mvjAao4dwh0e3Ba8u9qTE3iNk1Kq9Z4EuDB1GuTkVwnjMhluWJtHJemnw0tmKfx_8GEj251Xoh94TyHo2RnqxF8u2_8-rQTiU4vsXFT
yFoQiAhFQC6jztG0BnmV7Av00WRp_daoTCCemcQgTMspfk5fjb_es7_A8BmX9YSoGmu-pVR0ynmptdEgzWpWkqS7FXyeUP0n5IuuDhO5NExgKzpj3YiMvmas
ZEex-Fn6Q90EiBxVCl6C9fzxfVXjgn2UX5tJWTUFFA4X6Xrz4lOW7VgSyCBddYglaT5etc7O8pBFltsTRIyUUTWsiOEGsDItEOphyntWu-2HOW2zqsdXvQk6
E5DzhlrHdG8H7esw8x7OE_Q7Qydsmvd7TmYz7rR0XFBpGB_3tybbo7VaPJFeEDUtrtQoGyRcgUY0s09RPbWjaKMTUVAnF7ufOX4HVlnMx9ySMKI6FGReW0Wc
UZRwZkBcjrWFCbXjpIOfFserb-t6wrQE8aSd9_AOkt7u3X3_VnCnqyPlJOS-kVkElsa8U93BTLaxiQVhJVqN
}

