sprite $image258 [312x207/16z] {
xPiBodCv34FpZkrq_zkTzypzOUhI2BxG-keiGI1nVDEcJwACcdOXkQlgo6aBqaJ_H7fw7r95_qNUBIl9GtzbblG6f8l-okxCiQ8Nqj8hI9dwdDSpH_Vm6VxC
qJrUyin9I75IsvWvkeV7hCc7xk7psade7lZCqJqKSXAwXyyiT0_TXZDNfw98etjWIALxOCn2zy3ecUu18OtkWJ4htUE0ax2YpipHFS2POqLn9w5xSEOAKb6M
jUlF8vN3nfa3t8DEWhe7ZZHM54CAtGDZ5Be7EdDq3mYfh2Zg97GFZ97f7X3Iw1uOKiC-YtBcy8hIIRf-7jBe7XYpqZrG9-6mONIw1uPKkWVg9AmeEdDq3unE
zy2G-gtkmPdBNR-IdkaU4DBe7XYpqZrG9-6meJD7zu2GHlT0dOGLHMUExW4XdHN5aFg1xi6PQngOdkaU4D8uR1YpqZqmHg5xe3F7Ya98etkWJiAAOenCzu2G
pc73a4htG6UEmuRE75HH8Wrp3o8LgoWP1NCFqh5X8z9-m3te9E2mqKc68d3cn4ptePE88S5nviGCI8up9_OtwaEQankJstxr4aE2u-abPamEUFKICo0vdbvY
I71q4Z43agEJY1cG76TEp83aU7g98S5nviGCI8up9sP0SaJCjfCZzX3R3OxOUbovRIJ7r9pS_EJ8Ulo5s5Pm7BQ7dvkV72lgv-OdnufUgBs9AYkAv6QiA9QR
6LExQ6eRSDZ-9QLkEznzsAxSKfcs0Ilw5-bFAikwKT4hjvGwatCgwd3zB9h1kHNrS-FCxQHsvSQPSuRjdTpe9Ewm-RbnvloA-hbT5B4Dxb9HFxSBuFGALb4i
jvI1cOjVKJytEicL6f3RVPt4JytFZJDdxyUsPdB0dIH-QW-joG5talWLNIrTt7lcR2EraTCxT22vm1MLaXpYpnnUKMl99VxCuHLDBl6T17UFd3Q0Jg-OxW6H
fsqGpZrwWgcnPiuUS4KFp5nizpZW907Tuu2JX7SFzFJo6lpb5PrEHI6UE8caOGutS0zyvZHbDOUl7RODzu1dRbJp2UOU1vqaddlWTDiXf7kSExtYkmT-UirX
Js55Bvhzdr6dFUSBKZFCFN0dkT0sp27OTmyS_t5VWEJ2k0T-UcaTzfpFFG_SOJlf9AsQnntS0p-zfhdSn3tmBqmTA6iSzy1Fhrx576xW7lZCQHDpkOTxu4uY
W0P_thFeUIUPTPh33Tm3dpbjtLpYkmVk9AhsWe_vITPdpfnFIFV0Psw3UEw1qu7aGhZ7vp_kuy-YENqQ-EF-bpwBVi2hLrZtEF23my3kSVxLwxnxn9-v0-uH
SERiW7i4S983xX7Xz3hl7a5FB_mdMTyCu2G7daN3pTnXzuZl97RWF0WmSmUUHSESNaETvFOg2WpRTvzUvGhtXkw1_zUhLElJ_k5sxe6VNgMsKhlOFtZ3vZDo
2igm5_HXjMg_sdhWMJJ8wLNh7BtOFzpDFV2PapwbPEco6Ti2AXhhz9fjv9PgKpytt3qYdrxQSykgNStMBTq3FxsqJB-d-AV9-AUNrddb1dptkE_CzNRbTaFt
m4yllNAxgNlWfzUYUtWq1NDRi7l4Tv95zu1EhmMv1vraGS-YdBa5kGTdRj4zeDDhGUx1cLleTu-RdrwBxW6TNWjo3yxSWhvxq4aML54woOBSWwVNedj0NvWM
z9Cipjp2AigP-opt-1q
}

sprite $image258 [156x104/16z] {
pPWBakCW44En3OIMsFiVT_-fk6kOqdu8pJk1AkfvmfEca1zdsfFpOMRbIFjnLFi1MawxKGps2snMxDLWD-gnqw5vO6MJGols4RGhnPCRR4JysPqFsAVK8zeR
dmFBSNKQp27EBiWRejYWEZKbO0O4ejZGEhrFecOWykpq36XWEM86uizEpu3cSSPvGrF2Pa23bWEy4U0JMMUuJuhD15PMr1db4pq3mJuvYhsBSYoOWG2VY1a8
yOdsHhXFii5MK6Pw8zWdfwWpyEoAhQOUKNLgO3dI6_hi8hsXYrKp40UiHDQfYmsjK_j4_nSX_koqDy9zOZ11tDaPOJ7ePx4HW6r5STcmMR7PPOC98dnY14Iw
C9yOWHtJmRBB1jXED2Cs3OTkX6URPDrbsoSTsB-30HOD-q_0xTAX_-PuSAzqO7-IqjLsIiV-8dqdsoxXqE_yVfLlSNPWTwHVd575-cIUzEGoCZ8S-mVIYn9O
BFg0T2FC9s0VOCaHStQZP5-GaoF49nWbwpLvX4yMrjdEDEPSU7RZEgyqGFXaIJAMD6BiarlEztkZFuwaEEep4l6MxnqCVpIxai3vX7Q2U15LvzWd3GHU-SBg
z9HxAkB9McyawHEM-sQic84dsYSqStyKKsU0LQGGFY6jE9zChFD8_u2VCMDh__FJuRCPa6YVaAqIBjqoRsYVaApkfrlf3NrspOWR2sP0ytmMa_3yUvqvpK9z
PdjqdNL6dVfPl6069FfPF7y6DFfxPy4CQFIpMC_0RFHdza9lQ9zu24oPWVa-8Om49ip0V9_GhcOaN9qUEzCgl4-8cdC3YHNUyEZFRBQQImFbVn4yQtn2rFDg
u88P6A0_iwk1ylcuyEpSJzV006_ysOmH_5Dl1FY4OWOYpuvXTMgVKDSPvXEA6OWibc86GdqYPY3K9s860icOD0FV
}

