sprite $image150 [135x312/16z] {
nDI5OGGm34FHo37kFt2PMvLFUIjOt-klK6Nhk9WRYNNKxhddwnohUT9xdO6SLyvCnEUTE3UAP_g9e8PeKqPAAEFrdi-5D5AkjpHIhamQAPUGHigvR1JwYSGG
oedu_59W_Hlh-JsNHigrIKV19QIHSY6Db6kNteChaqRA9QIHSY6DbEij7GLN9esKIqWZvVnNez1Fn4Ua81q55_mUKkqaKhKsSW-r18bKBSwCWiThCJBylmCW
Hr5E181T4rSdE8xhG114nvj8PcJE_M_x5udq1gW16BIQ9tXGHPMMzijFutJ-AiB-dw5VHYJ-FmwXtqEG95uFA6mG7yx1kJDEMXq4-V1vTCRu7135iev73CQf
0IGGaOCK96-CFnS0GXGh7FWf1kEq_kKAW4bmv4Y78GQ3TksLGk8G5FJr9NrdG3ttiH37jkM8Bo_fysDbG3al3qQ82D81ytXbs4kbGnmdLYmVWdXcnDBcs1Zy
bIFhIqkwpp1DJup4HFAtejXdg3K01YEo1T-PnpxZ9ZK134OWoFh6akupJWqwP6FqMqRcpsEVuPl20nAdj7xVpVHvx3Fi61027AVK49kWQ2vYdy4L0s0rWJS6
xgccQTwI_jo6RS1zCgaRmqH1WQbHx6zAmCRdTKq51EoYUCM09izZlmtRrwMmNP60MHdZld-of9-r4TUYopQPpYXjt7SqSnu_js7hD1BP62KXWO2dp6EViOms
BjY5q2SZ1eE_YXLc8lRRk2m54ZEkY6jdf5_MfW-Y-AmDFryH3OP386XA53-taQsDvolYEoFOigK9yzXhm-Qv3HlNkYM2EyCX8a9J4EyCkBTHSMB0SRbT-_8Q
RmmxA4oOns2S7mm9049vQYFMcT8OLsGmeacVufrHjK7irpOCozNZlkELuKXp4E-Civ00NqSRDhXMkzviUY8mS7f6aC-VNXZD8E7pKaSjjiljXfsCA_9u6wHU
pal3cSGmn83GQnlj_pPi0AFs2cdNqt-l9hCOzBE11JfXZpQqjc63I-4n6K3dFwVJ-JAJyIylTxRSADC4OJYiXQRppVBzt-s_22fer8nzelAtpXoHbfuk4Jc5
RjfZ877Ow7stOUFsEBqWh_RzTlziZ6viy68a3XiBjWDmgDba46rx4HdZepPitredfuY3qOPjxpQN-oj4nlYq3KTVcXgPmz5P7lPkOvSBhtucOrJOiAKlWSI5
3NkFftl6gB7HR6uOa71xjZSRgKRhlTQ6i6FFeNMsOMFRThkzOlGA6-l_RMmnm6BTRB3PI35R93s_ReyU7upnbJPCrvSOfiYLZNnbj3e-5eF1nfesRB24HDfO
1nkPw8CnR4GO6zzMsGxd-Ef8CDaeYx7RQ8CDXzeD8J7PA8eXSM73iR0yGMAoKH7Z8Gbc6zZBmu3aUXjyTICnsl3BXcnvom6siUjYk2aC4il9HbzkA7-7gBKn
_7JePCCl6pRWtYMARUI59NGZ3SYRZNryfUHA6_k5aJZRw3Pu_wYLgBQHfPE40UpHHXZ7PjN5Dkpdqj0nHVmSRB1VMdmmHXzYSCzYmNtLZHoSsDkT-VJHrdj1
ZC66itGIk3qvsx3t650HOxJXJjxshC_xcusFZwy-sx3z64ed30-MfyysxAYtiJRTqg8bTXjiDf96HGocGd8edQHB6tQfZJlURTYuDP3yLpO0puMa_N-YI72s
KHP3ui96c3jjHO9w6pOh4hED75z8_8MDhuu4cusLjB4sko_USb1luvwbqtrP8JmKabaw0PZCu2WPNrawqKusTAEjUIkIWCfYi8wbqsXZ75zBIYwACOulIIlX
B2JJXhsLJbB6gB9XWvyRaRcGT6XDgyKsRD-MB9qc6sJfL7FRuy56Q6bQaCI53JkDkgiYnjVHfP2bqsWZxxwEQgeWnc1ZiNqVIgS5UoeMFclZJiQmnq8oho7e
QMCi5cfYn6pZA9soa1njE4fYnCc6takdPIwTQc9y-puMadUSdRcGABMn7Z4iHXjZwRI2H9cDCOPHG9RLXms7rXiT2GORTXJ5iDLrOSEnNfPEDJ5ii-MORCob
KsqCKDTSIAwOeNIgjM7lJG_j_pPEXMHdBfsE654G0wH-BYGRozu4UHrAf-8Og4ltgP3CyOLK7MC8mb4wzIma7NlffEeOOv0i90SRG-bK6IDCvf2KPVLWGqFf
9EfYn4Y4qSPSEgag1duFacLr3CM2gRVXi0SYf8sfMAWcwZY_84-MXvqsQiTN735c8dCXwVAJSaNaR8Co6v4nFBmp8v4_jJ5UtTFX7MtKn42opoxcmxlPeC36
8sDWAwz-2i8GfCn6nd04oh7eQoAICd5L38Ya-3iHi2jZW0I_4FcyZJR5G5sJ2uVDMv3Y6A3EpqIwocDaaC75zNoFwXWZ4V-J2E7uhean2VY92F7z-HXsZ0Ac
mpiJ2QdWJN6CF_fqU6SYHkBJCKnSVR3-CDyDV3n6T2wcvh_cUtxe5xmQQnj_z1yFxnx31J5CR-iHn3yHoImbCQIrTVY5I7cCk-X7aF3ruRKhO-HkJs_hxqGg
OtXLc5SGBeaCyGfZuAG_4F4raLeRMmoh_tXuostaMiAPo3pVwstO-DP1wqXaUcVgRJYMfI7q0v6FntZEDiBQTdjw-ub8X0jYpBizu-6TYRZWrPXiM8I17-Qx
2sBCUr_vBlXVy_s3jyJB4MFQ-zf2uNyH2NKAOlomstCvtmsY8CPXGtXeYPSaCd-qLSI0OUzBvzqUnlaUUuoeY37kzgp3tfUvqzeutsjVZVRZRiyutqjZV7MG
m7TXZNjVLdDEaUeOusvFGxkMs6ma25fJROmSHuArwUkqzxMq7299fD26XvNcsOODRizyPofYpBiz_RJtfJRizkptxsKsP6pm0oJ6lQ-q4NHxlmK8N6DZU1xs
lDjpsC0sxFCzIcq4hUa9bxizptm9hDOfjU6OTdi66mdPhBtKnjFsOzZjUHwxFNIRFQoXrCR-VEk6mCmsSZMnoWRaRizpM6dMXGr7JOnvx-kO8hni-6oZAiOZ
RInfmmRtZiHaeop6URSdZlsD1X9d6tKnygRcPCF1UgDB4dzZGnB7RW_Om_EmysvFLOoRa9Xjo6wvsrDj8qidYMdlg-6DA3B5DdBVNwBFDWY_5THbDZXkUyus
rc5_OvMejZ4i8yusnjsUQXisUBMayzvNZgzZ_RxKHZuFYmGNUr_siDjJPoEVXwLd43lQiB_H3RdRWrrfm-h3ROzusJ0N3vILtdrrc_61iZxQ66zxYcrir_M6
eBSRwtdlowROHXQItLawoSjimuxokM6jRolDLpPAOd0k91bBfsDVmdsnNVlHDjl8vs6HShUdteRORJpJHZuFkrdz8niIHo7v9QSKFrWQEj_ss5Kndjg2MFz-
eAml7dBKbautOOxIQS6ikT9SR-EX04clGhA7nq8ofyYnqlpP6CjLwRJRo0lUMPOyomceB0PFczzBfvHS56CidP1qig5rB9saoXWFxHU-7wKJSR8Hbltvsvxd
R6CkdTXiv5asUuw261viX5lJOmyosHWVAEi5CTx_F8MyxMaURGpZ2qfU3KKMalP2a4_YFiYB1YeONsECiurpwJJPi5r3TBJ1oyOmHIvi5CM8amrUDeOfCjke
YU5LQSDFsylm1Nr3TOqSs7Kna8v2SZsLJjaO_uaD8rtO2FSRgv3u6ni27OKal7r1doJgRHWafCb6xvjCa2YtOTY3JANJWZsLJcKnd47wSjXmyBBXjzB9KHOZ
Sp2KJjCNz4bGQiFTy1r8I6ysJb_Ug5gYDqF4jv5G8ZX_GLzlQRKiXkyst_Pt7fgZa5prNZgf8aPiHCD4R4nqJ94Olw1l7Huewwg8WGqH3XD990l9oo_e4nKn
1F3j21DE8jeAoT56nVXgGmo9_Ks9I0Eejzc6NHOZrxcy2ObN60cfdMpifgCk1aZiRufD914LbqwFZ35EKJkXXh-3BSXaep268Io9SCo7TomaAsCy3D_R-v1G
8uR3EzfmbCMu-JYg3XDsn7Xu_yP6su-gWJoyiVzt8q9ljcjj_BUuyy1oPOM1AA8ZLAdtlziV3A9nq0zluBbE7CTxWAkkoQ2YgdefgxnQtgJAYpp_R3pohAgM
JQ62xOYydGqEnIZlq5HLtl9Iwt7jGMPXuA6gzggYtjBMX0Oo4GEcghrrarVlMrWvfc4OI5MLjwfgcy9UNb9dO1GFcwhiLGNhGMstf1DwJS4uYKvLzgfcNjhM
f9ATIMTWM2NM_ZghJ_AIMZ20JEOq0uChYSjN5MoROcDq2WRlfl6igfgyB4Zrbbd2iWvp4_DTLLwSYs6LM3-gsjqo6wEeobvLkqMVRW6cOg2AwQjQLmISX-5N
OZkeztKM68nnlbVY-Z4xLMsRsYs3XPNbl350TAhoWwgagi4ENGsHDHd6GZHLB_9LLTNoZZ2EWHWXY6oPUtfWzAhQfhpBMy9n64luEnAZR00JM-5nvAsRGd82
HX0HYQdxmiAbn4TLLMsAZiOma2K1-5TLUSt421BNiwYgLLKwgd8QXgnx0d9APTLDLUrKxUK5E1v3rhFxXprWhsgRvdLDUDaq7umXzeiU1cAgUfNOflb0Z2mX
h8RHG5vKPQSgcxpZCBY5H_PdZbp_eHJVLEt7LyvZC7XAi-H47pkgLTMCMrLInqxH54ENnynW3sBoAewmywqISmW6rl2IpGvX1r9kEMEG1EhmIimzl4SEPJ62
9czHzPGOTsXHbJeCmmx5QvPKnIHxULECSa9DLOx1o4jmix5YA7dBYosU8oknIUf7DiDG1TiHGNwMzuTJb8U4VqbC3KDfy_s-plAwc7yuHNj9_Imq36K16L29
VKdzx30C0-ahiRvLufz9waTED0m5OFEzZgz7kahyKqdzBCam-WK1dKhyKqdzRBbXQ9ENplWQ8AcRWuPX84ub7YAfdtWq36tpNHsC4PBwEzCmAeXJYOT8waVM
Xg4q4ASI3v3KZnmDGz50w60uzMf48Wo3j2FY2Ej8EYXhmsWLuBzXO0j3SxIPsa0o36Euf7uaQHiX1UHOzjCm9aZgptUJvf5JHA9XE9BEoGPsjNaLMGp3aNHI
P5UQk4WIoXSZw4WwCV7KjYzR-O8Lg7GadPW5jYzPmjyWEyxDEHHJix5SOUfGa6NPUad3Ryk9KeR4C1n9PwV-Vj7wWe4b_EQi6K0o39Fq2zao40t39Fr2vC3U
C78CNqiyAeP9-gqKZ1Y-7na0yIS
}

sprite $image150 [68x156/16z] {
fD47ZiGm34FHn5saTF_hBcniLwR8uPIWFWW_nulbqSxZriucWb7k45KWCfMyAvG1aJMWfnqXTSZF8FNS207vlNYM-by8PyahX1_GqjiX7E6o14E4inGdkA6d
ZH0-oxaHmcUv3k7UPpXB6Ku8PaaT4XtaTvQpkH31B3v4F4jpGZZBcSKjcEL8SdEqunIA0Dk2cXv7KLAvXq3Dfd4CdTjGG9lJivqdgRQXKEtJ86kTY0KHJE7J
01LOo5AYmgT18q3LXH1lXlXdAFkdeajv9uGte0inu7LRV0hk3YK9w3AyueNhErGw02NbcR92FBkZ2q4Lm9pYGrpVCQ0h2yGk4JZXwWwi1sZc5T3igV7HgHaj
AOuhKT00OwbE7it__-szkrYk2BoE7jNuYQVi95M05AquF33cayMJycE8P016f8VLE-AOEKM4b6_ZHqP3H0XZTMb20IdsbeJxX-bX80wFw64S8G37w_7oM64q
OoazZ3j8q9_Ryxt6aB6QH7e8etXjssELqGpG0f4U1iVxiJrVwnxHP0CzFMoFU3tRM65eUiWOATB3DXfB34WFimUaXy6BZAxJ0uY6E3s0LOP5xzD3601SOeGX
PpswSG_A7ZW2qiC2OO-IX-dzgDdxkIv0pKCAMQW9uy36U9qXO_N0GFH-C8fDcx486IlGP51X64uFk_NWhpmGqmEfMvGz24EqwH5_DsFT02qzS0lg7euEO0uT
6OcoXreWa7B632kC9tXwXB3GVdWKrkK9ZCCZkWpGqwF8c1wO9i32BZ0yrVFtfQEgXsqaGi9OeR2GYnusA7gNmRs7GG9N6K3NwO6xKDN3018-F2mR0IM6VK0u
FGokCS1JfNLDZreFo9M4gCyODfwWwG9r3_9pdbaQzHa3lhDWL-T3IN5I5ZqqFU2af11IZP6KhooCKM7Om3MBOPb1jlpEOgyp5BhBKcfAZwwR5J4LXjK3Bbbg
Z30GSSbIzS0Hronb3zDxH59WVKvVu46t7GgkMTOPwO51cGM0TKOxzsEOdcy8LnXpFpZt7pDBgSVDFgW7b3ok-o0PrAF8w0RewO6ReikkUJWQS7fOjY9mnUEw
3seo42fwXB1W_tZazgFg8UTlL2klRLpsGHDGOeZhFgZkiL_E-uBrVL1C3uFwwH664BZ4Q0O8BlkWgeUZIS1r7uIN6EFhl3yzSg_jceSDjCE3sMELeUanPomz
R1SzyfmDr3q8qiEAXcXbZ-OyxzE40Rle8GFQPVAS7PGzi2JImm6gDrKBaHw10IXwqCNbl5-Oq-bnTzvVPgWPbD_hcWmg3CJfON-or3qi2KwFw1Qzx06Y7nxC
B53q02Cr6JuUk5Ldp5qUHe3PyxolceSzSkUVPw3YVE1XZu6aNHWBUxN7-_0G7XyCKa-F2WC3fmhIz5Xaz0_ZQ2hRmtDQEiOb1dWCMumnNqJL0vW6s1yC4bMF
D21VI0MFQrDIHOnrZv07yiSWNu34EaDy6G1Zp1pKcnug5WEFKbE9uU_bfR0kFfeAdqrpULbaF7QDOouW3MPJiSROjkU-EwvD3w5LncFRjXVsy6LvyV2gn_Py
xw4SC4uLlDJKes-_0eo4lpyoNfjrZzzjUyi0wFAHMMXw6By_bryEYaBs6Eg6yttzqSFxUTEWd_-wPGnjhzdqfnvJeZ-tV5uQ-Rs-lvaI8ndt1BqkjtauA26V
JKcFMmB_lKVoQ1uUjcB6HJyrTRkzp_ACpz__PBaslKf4XhW-BqsA67TDCyJxnqjEvtp9zqsTwvdFJPQf4kBU8qFyyBpYN6Tv92D3BDwxUkkSkIxmPR1NdfmM
tBUtat4JOY4BlBTVIaP_LWXpMapy-pNNSh3hpnlxlJqU-xWPx4AMs1xF_VTri6jPzkVst6y6knhcZmx_1m
}

