sprite $image131 [191x207/16z] {
rDg9gkCy38PXR_4YwTp_vVxBL41EPICxOnDazkA1f-Kbyn6EitjYpTuitXS0Q5RrLmC0DCfFV_1ean_g1uy81gFFZ6U-nUYDyYFZJV93ORn5FaTlayyFIwFy
M1blaS_H6-Lpz2Rv7BrHFaTla-yvUfly2rXlaS_Hs-JpBBR9vuLWay-ps2W_CjuadnU2JJv7RvFFqHlbyqAmoUU5O9FFqPlXwmj1FyQYr_dlHqzs-F9XIMIA
dxxmTlXo5fCXleoU3F5bzARuKU0DyOFenX3VPu4tmvSFIrFyM0NU2bz6RualP_6F8Jv7luF_kVL6z1lunBTUM0ZF-N8PlVwsU9r_l_LMzC_vfF3FpU8D_AzR
Rpmid_F5hHTVdAtpvQtNtnRJDBztwuNewH6_V-jyz98n7O_-9Oz7BndpVFtMqUWbtWe_b4utLlZzwAtmKwyRA_nOEtWhVD-BtW1VpcA9ntgEVpxwx1n-w-WD
lhuGf0w3SubM-Fgjaz4Jqks0TnbdsbyPTaSNmYzQS8reWhyqgqz4B_b0TBbC4tp4etmzUic750cT9vsFU9QlBmJ9pyuboYwhVCIpV3rwoQ_U-VefN-7ZQRw-
42JVVNvsxs30x-Ff25-VnP8FH83ky-iN5FmkdaxnPVGgluM4pbr4c5oNZq9_diyFIvqVd2ladKl9kzIBH-2FyMNqEjz584gV_vXdtW4UvCk5eFF_c37wa77X
7U2PqI0Vbdhxz7LqlSxd2mUYVymNb_HbjFLjCKtnTRpEvu_BnkY9PlYewdK-VrZ3nZ-efn4Vb_0wdpzgQMFqHDIw_0WhU9tF7y2rANg6GYcIlnAzphz7xtSj
18OMZJ_yfvFyUpTXvvEU-LNoXUOn_zvDshaGs52195zQdlEHJzupYwLXACE_vk-ENXeGvQ-lu1M-F2sUMGX4e-S-uWR-zkYbdx33Hzp7pqhYKIw41Nmjf6YV
y_M5uAzIhjzNCWYzyjm_nDUZJxdyTtBo8lhN-Vf22BdmoL5T20XTVgLJ_EArRcud1rwM8tmj5QG1b_H46dyw-aytD__bNHvIsfyxLV3Ny0f_VY74NCJ9gVpG
2C_d-m_gnjOE7YI_hzTcSItzqmRTyAaDSEu0oCvAKVZJ2w7Yz1UutMnjZa-4BHInxZJ-mYoE00D_XK4tjStn2LjhsQL5_k92k5WcJxqrSCVFyOamf-WZ2dwZ
CV_1B2x3B_1lE_U2ex3EGm7OSHBRnsdP_sx_1mmMkBGNeO7Ig_4AFbN7aPqWa4Elm7FyoGseHMt93sJclpeMyteB-5te3HlyTBhKLbW6k2yNfxLpVsD2UAq5
V4gX3_usVa1BWtHqaetPElWReN-z1J1y9FmcFu1kbOkxLEOwSgMldq9VwBNgdX9a0sgUGX_yhToW4KarOpOa_l-bq0K_JGYlyDNkOZvSDVY6pD_8ZHIYXbfB
bG5-uk1CeN-HVpP7ove6t_2atiU0CX4Rf7INZaRwZ_mq5h_ELyM4S-YXUkKlyMR--DDxjKfK1ChCSE5IUIpuThjNfiFoTNvyTmnN3JuM5IDR_lGEAaGTLeca
gd9rBFbZUnTydH_as_RDPJ6ofUF4gfIYrT29gACoLvc2l_MKw8te5_XHcP_nWAUXsDsLgh7_D2uwoP17_2M-4ts87qUe9vBqLjha78rRgmT_ixJGh_95P8M_
DhBD0ur4cwEKI-CIzUVuOABVvCkbWh_8pKD-ApgizbBGOOreWvz3_m5-mY_3urqWr8mTdUX9lWlHB_FTx_msKkXN-QsUio-54l-jeS_ySPeqyC6txP5jzije
xqQ5dkIZ4hs3VngYW0K_uJUopwqKe-0Z-6yDVUQVpkBW9_nwzZi9UCdNiImXUWyVqsbs4md-9VGPxoFpAtETFF6xAzMHovZUnH_3eJUjwy_CcxCRizcItrhX
DuS-XsV-lzxioj_6H_PPnns_Q5Kq4jID2U4JhRkDZw7Xmh-sRXzU6xDCODauB3_Gkbd_1B_wS2jiqY7KKkZVohTpwwQP9-Et-MoJevM28RKoJ-yDVHxP09N4
J_XjlWo75EfLKOk2jqF_dfbdoG-ygVawVyIsMslXFi1zC_IV6jayFK-iyVswxPRcqj2fH-W_m7Sy7DaytzJwaezpU1fTjbrc366kl34Xl6LakmqFnYtUGe-7
_85IYAgX4VMcniLSHoVw8F_a8WOBVaW3huQ7V5OcPOKKeeh6fVO8_UVuim6cmVVDvudWYnkn5hyqha9ASm2Lw9Dydq-dcv4DgyyJcTzxEMS_hgcgHUW_oFVX
DoCRfXnwhAtgpQgZn3LLXmjzi2HjMy5FkNd8xoG3B8NiUatbnhG7_pHkMtTA-DLrfTzUKzK8_UVvCsvRrp9-9VkjbHhNLDw9Tk5ZEftkefv2lvvzkMPVN0hj
n5TrLrtm3TlyLcI0Uobe4VeT-Bc0m6TzpZw46jeOdUYx-5YKPVvbj1__h_fL_EtdYSX-BOh-VNn_vdbY6ZrMMlyg_jRpn6sfNKUZB-RdvubShlh5VCiZsnA_
Frz44Z_XL_YcNy2NSotv5hbvp8VgtlpGXn-RpnCvD_lptUxys7oUoBdPdp-THWfFnY_vkDKpxSk_hEh1Zz2lypNAAj6-_BIg-p-CR1Zp5FXEj3FVvxlN5M0J
xwR1LocqEt-aLHqh-6aQmw4Q_0Zzlk59jsp-46ysNvRWuAVGxzgw2gHpF-L6DIBZyvH2loi_h-ePV-KFlLJ7j6_eywe-1pxuWL_ocNR6vrKTAe_uVjRFztop
9VxRPfxuz5eyyQNGL_5rmGyyAj4Fl_tmcUYx-6FeScJp-175cMzC_-TR9Ves_lJpggx1l-Y5pYNJm5ajtec-aNyQOa3muNTFQzpe-ogV-wR1NxmdVpKVupH3
HMxkzvNeCFmnkOdSyVjn-D6wn-H7wnwKFw9r3yctCSzGFIfVrKpl-5wFmy-5eOKEpEz4H-QtF_wBzSVtF_vg_V7_-7_yFtuxDh_8eVdKZiqdEJQ_7fjFScm-
7vjF_TXyFZQVvDZy-Y_ZLpfm-8Nfk7nfTB0gSiXF7yNXrq97h2ONlT4nY_kH-V57XNJSgbtx0PZ_1G
}

sprite $image131 [96x104/16z] {
xTPHShCm4WHWG5Btp4Zal_zjjy0ndIW5jJRMFkqyslQNheuyOXevYt6WFYDg7SSNhtMSdwpMSVx2-ZsZYX_ePw-Q8SMFynT67UVF9Met0ueVv2ycLJFWJ8xm
LVm8FtazcmyjWr6-YczjY5_yMrz7-CaE_UFvLNpRvjE-Yj_cy_raL_WFvrVnr_xsqkqjt4xxQV9lRE6p_DyllLtyjN-yT6CBd_jwgRwxXLixzzkxleflL_xw
eg_YPNuylxRmVXhNfh0tVHKldR5-g1zjOV4j9VdtyoVxhQy9N-f7-kj-V_rjrG2MLe7IN_HLlAQjDUMMkUh_A_vbNsTIliqj5dovh-hdO5_qLRnydnRBKrxq
_zLxh_ZQmhqVQsG8a_bAVctXlfzbRUjMV-jr-T9RlIvUpQh_zVmy_lbhjlmtnRTG_h3TlzpGp_2UJghvNNoh4BMkPxfUNtSzolKMhl93_OWvzrlRCiqNnVU2
VEddleg_lFv4rCCNSPNVStSKoz8jWxx_tZtt_nQVIJBFZosi2VdUy-T-g_nTV089W4pffn84un1-UbNmqzSJLkkB9pUR1CcGRW3eKeK-NsnXdR-zbl_-acot
2U18R0He7d_vOFf-TRNEhwr2hgQO0Tm7iAZL7xhBL-GCTATMrNC-kqAC-FOPiHVcBb_DvmBaa7-z33GvZDXSjoDyxxV6EI43tQbIyUUpqDp03NS-zDuFJpDA
0TG_MxyCpdriZHW0FtIZLsLDIy6IV-LlhLy6v_vUEaXuF7LQ77ekXMdPyWUwLQ7YB_DlG_bxIq-V6SnR_iNDKJNTChZoYO8ZlstwuQz4sV9FK-hyhlWhtzkH
tqX_p96_C4_JmwVuhlXBt_vLCn1-7A0k__BjbwWdnL_xpH_z_3oUoX-OTvyvlrAyVF_dtFFt-fRVp3SVbhELq1P-mUVQJETdq-MxqJ6di0JaNBM5N_3tUVeR
7nRopU6UvfApvT0oUAL_A-Nfxpe0b--bp1c9o2Nm2gt-ZRRxKOyLBJ-dZBIKd5t5lvP_RUJcI_Tu-YMpvAMKH9t9L_ElB9iVBUnn0MW_eB3aWhIml87tlo_e
0kZoOvxUzXb1a7G-z3v_AbZUrBK_TryNmD5_pgpnbgpyZu4VG_gHFsgp3_dnrFLy4hM5uPuF0lAjUpvnyeRVto_MFP-4yRRlzSYl2-31RxentVIVvzz-Nm1H
0oJBV8FN_GBwJxrLPmsQZlxx-R-C1fsVYEfUITGALNCZ_rSpojyFZGTeET-0vGFK_L8hexNmIYltzVv-YUffyZMoLHL_Qn9rlqUDlBs4UPfL_6tVragGY7Po
GTtDlnBS_JHztjVlAreUujFzqKyTatyR4hHb6fD_7n3JM9__U____WmEzQTC3FKd44FzDDYVG0pryxUFeJxpFCXVG81f6ZPp8JcDdAKCAFy_
}

