sprite $image18 [236x176/16z] {
tTm7Ul8u483XaJGgK-v_tZNPaF6J843oYD_mRc_WBvQxlB1QY14HIwsrqGrrWuWfHdXV8IBMIYDgBPZUgpbYheqEg0LZU8FCqiX7gpcTDJXOfgEAwNITjT4o
DQUFN9_ztlZFGtEbLsabmJ-JIgCNgnZE6_h-kI4t-eTUE9XJfN-jbG3hXTBe56hw_5LgMWuBInkTJ8cm13OweHhFN5eBRahrgprdQSFWUkJohqtBbYcHZnh0
HMpa8yCDXNmKb-CfEK60bR4DJxHBWevsZfrKhEGcGKScDnccPN84FKd9JKim9LHwKIlJFrwrI6Rj65OXHot0g4hEAdI82hb2618QkIjmKrFbzT_Kb-Xf5J5k
4ElS8ZHLfNjQmHGtcEkASPpfIIN0JYfq7oFyWgBtLsiEi9Egz_wuF5iwV98bKkF-w2rwFnNdZ_Z9TQ-K9aO_gofzvIBf5w6-uB0cV5Bd3bKicc1Jh7GeTJvs
FhNCVq3ylrLuyj3Hd6BhuLC3v2TRcUuBq55u9dO-bI9q97LgXHvKSeYjvD7AorlvU6pnE14hAZwj2JgQyk75p2xNBUhLMk6sgCf7BpcIoxaygzSOfZBx3Nij
U9pkjmWt9FBOD_Nl3IOxAZ-dkLp4IRkzD0wjlPzaRBgX8SNbVeiesxIDb9d2K-TEwObMlFxSMevsRS6waQFNiv5ci5o_M_HBVUOQ01-s5hlW-wdJRtpuJaKZ
Cvnx9IoAry4ssshtFilrCuqmJQYEDvVuotSw9_l8gTO4Nv9TyDatJ48mWVomNiTCdcd5wnBPfdbS0rF84qlft7LjDMEA0JOX9SorTMvqL2jrlfCQoPa8_dd2
L_7sKGJhd-CCsax8Ix13gpTMiitsuIoTLFR3Dx6LkYcsjVfZRJyR20Pu821TntspuRjWnHPQGgJ0iD8vidXjiRIA2C8GjEECjsPRr1ei0GP46xx-aiEUoNCQ
Gs2XLQhjcLQeCApICc5e2BUQSPFhHAfpRAi5iTGwTg9OPkRj1cpqK809ON1ERSm3jukdfoOrkWyNJLp0sUbN49PDJO994xkxGi-8k6fgKeP9cH_i0sPZCQ-Q
cXHXKb3gEx9BA_N8ivk4VJ2jPEpfBmdJGxNHOn7EJ-cXHf_Ioekd9eNK1zDINuIEg48k6dI8zaMOfNT0HrDTFZMfhy0ar3jgzxyHck0qDQd1958PFVxbYQjU
rwb925EIAeyjII2NL2DI4_n8DZMfBy0CLdruRoU2GVA_by5VdrWsnFf5LbpJDLLvOacebel6gfRgY4LtX1wgKwawl2JyRC1OBii5CpsbpQJom9BOeaoqEkC8
8yXI5s2XbJ8CoIjJYPLES1lH55f7LhNQ75uaX8TIisTxgomRDDV0IBff4Uu8MLJLdkqjQnLQeOJTARFm9HS3t8ALzK9OAQvvXSGEomjVmCrwmJz7H2ev9Rjq
mz9uVunaRJQtn9tuxkJxCnw-S-qAAEaF4VxpR2zMyhRYOL6-yo2LHNJV-lTSGEJwa_8VmfibnvdI_p7Y_wtIFGg65Pkjk9murytl6GysV9zjDVntIbYj3aFu
u21kDaSlOB6PTLOwq6f4ydMpRJa5-19IRWU7y8PzNwwr3NMcrQQ4kRwGQvTdKzBaZ8TYhO-cXFqLfrVhaHKR-gbCzrHhlOVPyN6qwf4L6wTkZUrR9v_VXgdL
QjXlVa1aycdDZjT2kkVuGgqujKReI39pR3NYrygokbLvPWGRTdjtMDMdDK47gaoDO4E3e0EzMWjqD9Mf4Mp4QSMgstuuzOQmoiG8zX_5aHz-KCsmYIGq5Pj6
5rLluUCdJldHrb3Io2IfUljSHQP7iA51GlZtjf5I7mwUtxBK03kXw4IgKwmgrPmkhhTJPF0MAZxw1cavVSbjuXAKjKTeb3p_0HLWvct-pZVCfyx74b-Nvj6Z
bUbJFfR-DyodMgo_F7y2RLnIryScwD4NfnfvVQkyEjMyUWohlZpLCAqmEpN9FtLzxCJKf7cYUhxOlEJRT8IGMJX9Aj6ALDP1JFv4QxBGC3arQVuKM7jarJFG
LYv8L5-RggIUiPvJa_p7RtKTnuvJa_ptlvBr7c5w9wptKDBxv8rAHUygCB53FYVH1n1OpHiFPDQ70bHzJ3wWL0KWwJFaNKjD0m1zZhpdBiaW03Hzal0RbXgR
QVIUjQnFQt0XEe3VgzGakCWwHDvey1hflTHr_g7CEWZjUT1RvRBeA84hdI5y-b1JuAhe7E5JXne18pfB-BoX1i6W7Y5yoav3i4TwZ0YVhjD4s0lgmB-N3tVQ
ZibazI72V8fCmvqNiizGp2oYZcBtHNllP1vg57MNuQ-e2ya5VwCB_YONkaw3Mr0_4CDjLJyFz3JzD16wskUd6jPFWd0NVtwgQP-N-lcn4PxGFZ_LeBuz3l2a
f4THCUtlFz0VnJHHBmsU5rYFARrFmr-R2Umbfze2GvhhjrdixwranI4FOH1wjeRV_m-nNYleOHHWMA2ZhRHfDcZtUyUsRqNQjEIpNomm9H_ynjsgBB_kqyPz
Q-ayIPl04IO5EjPgEMdV_PDahRQTrHUlL9DzMmC0eEoJzgtju22c2CUqewri1GoRzbKS_xJQJsKImc693hLAj9zOXitt7_X6QpXmfxg22vIvrhG9yCLQy7lr
vXkj2JQp1nelEDLggcsFpTQVMoiby5IEjERT1gLgWzXXUxLIJracMv5sAQ5iqCRAlbLWWpEb_b36MXzSVDm-vfIvKdz84wszOqBxtHf6p_vRW9L2csw5N_1N
Auuz79KCwo5FjJROvFrBMBVE_Pi-fo6yHgWotXhtfy5uxPewk766Ly8ss2fsURC_zHr_LYWrmijX6scjkpF-Q-FlrdA-K8DLxjnRqxrMDlBdBujf-W2N2FzK
p4rVeM60CqY5T2Mo5VhHlIqdEAE8bLnN9mOujOYbiHx3hQG0xoAcKcaycQXagtmpAULIYEZ1hFfM2gO4Q_q7
}

sprite $image18 [118x88/16z] {
lPg9aYAv3aNbNUly_-U-e7AoojGbZRCVqoSs8Xlh8CdO8hhe3hdKriTWbc-OH--jbaGV07sjFrogAi3NCnxze-xI1gFkjPnxpH_8iOuZt2wg3tFwVvIDmRXf
7dyeJdK86FTH6UL-cXsKTr7bTYlXyZvDbOr-g_IyxMG81unMSYvjlFUEBM-6I0X_Hoeix_DDz8Qqqq-UmkITZTLeIKKdeeqcniuABej48SA6bKqsk4utOwB7
4tW-LzXrkU14ELrK5r1k9QTS6glCSFrUPFwye9Q42muA8Kq5g7JINfqyPMZOSW66UwRhgd_ueNmGIPX2s6N0fHJRHrbnUq3x21Q05ieBPFgX60H0QtfUWEXS
ZVfIgfr-47zlrGOB86PvUxxCPsXbVMVLwUrPGqMM1UJLzTnQ6oePlFsqpkTF5kbV2zprAXDeAg9cxcwgFH6rIQE3IEpvh4t3_LpmxcJBieFg8spNem8yUYLg
OvmZpjU7yb3P8C7nlK2b41LM6JK_ZND7Guk6xSNfaEgI8th6MPaeSxZiag6hIzGglQI6GvXbPraGlPgA-kKTkGW2C1K1b7l9ETSk2Xsvf2iCBhNaWa4UbARN
5t3giFikIR-aFM6G4sq37s46c2eoBj_QG3juUTDGdacq8EKPcaWAZPMrDSqGiFNMP3TdCGxp4tEc1IFCVnXpcrms-Da87BgzcqmXoC48tVnPr6kfdTrr-vl3
3a5QAQKD0-dwfd5zVqf0GX34NWha3bhf9MLzykzRzq__L8boloKrMOB3GXYtF2lP_Rm3Tp6NDJWiY9efSoEgBEfVJtJ0YBF2NT_OL5JFOS52pwVEH1nctm_w
lpz3zO4iKG-J5QFLKjjW71OwqL2UYr69yk1MQsr3LbWiafr6JHmMT10DWyPl_U9tNoKxLbz81glelA0lKrqaM-3-N5ibu-ySHFr000n22eL0QvgjjaWLQdnn
x5QN9vJnxDMwSTEed-YxsuUQsxEp5Q82UxNHIGjRI9TQrL5ppgLhsEkEP_uzevLv0U8pkhvzJAyQdbYUiFccGJn0kubs64c1fHIrzwrsLtfVYnMsRQk257gn
ffxIOhulVKdiQrL6BQLsYMsf-OJ6fBrHPTZRjwhBuISGvdEOpuJsPskuoOV1RHHSeBkk7tOQA1ffEA0VTQ8WqLJYpzTP7PqUGfJz0BpwYTA68r69YEF2kn3l
bnO99O9aFo7MXt9oOge4dGMntYxihCIk7kX2UqImFRK-ZBwEvfaEiYDeFjnweLEpytrBOXvoV8SpfZqn_Tjxucba3hz3JDnRA3Gpmly2eKH_NHkQw6I_o7D9
pnTni5bUf7du4fj7BXNn1_EpDS7qYcAnyr6BFqX44Xv-JiNnpkcDW7DjhAsrbQzU19_VDwBIQYBIM4krq2NLOcdrY4RPFIebIlvbbGXBL6FbZ440fBkm_jCf
UnWH9-8uh1wDyi89YI958owjWtkY5i6Kl5BzjWvArqvhj46TlRYRaaLKQl_munLOqTaJ0IilMdllmoACA9TCDCBE2fVxJgImHw0r7lmSuUN8DPIe1of36zqa
TOs8NrRpBmfLK-j4TdvpaiLlfOr2Vq8PwX7FU_ZVCvp3muY6qnTPufUIQw8_fdJnCsKJEOAUBuGLJiI8S1kWl4sgGozF_kdvySAuPVeGgRGXDhadJfyhzvh-
ep_KWzyjTlntRBuZ_1y
}

