sprite $image144 [187x249/16z] {
xTZNShKw38PXsqYoLUx_TdSnAu7qa8N0cl7xb-Fdu1l58JbM6fSKiKpwNpN7awDeJp0OV65zZPT8MwdwfbRYZFn356BomFf90iF3IzCluYNCo3zMoz07yTk4
0Xp4NfJ9bwhVDFAX9FrLuxqDGFH0WW4EubSn37aGuqmUHV-KK1xu8FfFtd_auxqDIFJPQXdw87uVvMXRsM8Ou216c3oAdblD0nn4XqFfDl8uaoTHhrePu22E
D_d2wfoWsq7qZnV_WnXcyWlhPGcv7KJ_19o-8SQPF8ZUKSrU8_TFCC11T7WRPDIRQ-MS3-LX9b-Q3f6Wmq4Syr2Yw4YrudOG_QFiS107UXkGkkG_UH0Tjrgy
3g9_GWT67cFoA1gXLjmEedyrHndvzsy34eqLBwu7qN_ofMd8X52ZPXGLRb7f5fLk5fHkZsf8UAz5aqUbcmMbcqMbMrIwML2wML2wMLIwVLuD00zADujAjwXq
iw1qiw1qiwXqEuSkCWRyEBtLoaF0ZzC9g3OUGdwS3aYroGZmutG0h9VWpKwczyX_ycO-TF_Lc1FTVJLcdlIEP_61Uz8z9s--TB_9cpdJlIPlvaptMesPAxr-
WZ_9Rivq4VfWPmUu1rsLyNowsILqrOOdq-qokaezasvFr_J744JNcCwYsmdn4Vf-ykm0TwLlg-6xvNg8tXDwZcvs3tsRF3l0_UdzKBABt9-k5TW1FYpTB2ZT
B2hTejBDWjBDWjBDej8jAjqiAjtM9dtI9ttI9ttI9xt6fGF7fKELaFHA080j8XsHEfv33WO90O0a7Xq1gEEhHADNwlZTv2aAdRfxNGtoIfSNtCXqWExUJtvF
Dxk9Bh-YO-tkryatUANtHgOBKrzx_wydRt0tqEMtT966WDlaT_HLE39TkE9kydlwIXoLtcFQ9lzAto47fg_uTJKRVSSScRvD_YEzDnWTztJX2l05lJSglTU-
eZ-i0zFvQ_gg3KfVlGFH-G1TXw83LFuzNSUXhvUyHQG_BZbnE3fAe_NdV-LmTEMA_QcEzH3T1g2l-7NouUYg_5WDSJYwIiC7FWmTe3RjoMFoWUZRHpicHA8u
TAm0zC1BdtmDGrUcxQDTdtmSkch3xJkrr43qxdqp-J3qdj3sdPe3qNkCBvENOFHjyX7fVVB4yUZRv6j8-ZhvYFHUYqjN782krzCddUFIMmJwf4_wf4_wf4_w
f4_wf4_wf4_wf4yw3KoVz4cVz4cVz4dNk-crwa_9a7I1b1OEI5TAFPHez9RJeqmIYSvBsbLQ6BfYUjV28UXQS_eOolXqBkdJSXsSBf2-R6a3qvNIjm6FIcyv
_HJ9Y7HUqYygTJYwOlfbInk9tW_YxqCPXzvAEbIcGUW2wN2b3K1NIdzguRlfDQU_Xd8ddKjwebn51K1ke2ka9ojD0EhbTAMSdcy1099hwQsaKuB_mdOXNI2T
rTBnV15TCPrOxdYIA-WrftChy7zLlEdh2z43ZysLlX-vmshOZzuFeYjUVEZxW-YscYeCPzDbITuLw9rCLqmNb9VJwLfpkgPyCfrBkgvo8bqWNTk2vz2LShgw
d9VsFBtbT4_0NVTdkYpfjZAjkZ_H5TEjvRhwZjBxGRoxXRlm89rB6Y6KRZn05qY3b4cFq9NIG9MsCZ_G7Lw8VfFVqnr-3VAS_9xkS11z3-L6TpY8tfF_dCub
ZHo8Va4NI8ENKJwZAwK0bVfnwwsa62siQzj1Z1F8HbTCeSea3thDALgbgVQHHsnXtuFuBm
}

sprite $image144 [94x125/16z] {
xTe9Rkum20JW9Z5WO7B_utPpzmOb5UQj_npWapMQQ0jtFyaYrkwgGkRkVIsnDuMxEvoNwVOg_XeOJSRPuU-1RXFjPl0laNLMAVsBFR7-HVmucB1ECdWKz6t6
2kF8aYWyGlFhNDZXvu6s6IkCqzVy2kF0PKciS6hzyGhZGBSvAuphpwym3foN_0hZm5fYXOdwH-7vo9fQuNdzvokSM7_Jq4wlS-q-FxB4Aym7Ha7Xatnj7LuM
GFtlr84w7QZJWK8TXJfGfmE5EWfre4u7JdKJJTknhet4qdYijqRTqdQijyQQjsEzaMWIZ_NXMyAETE9NdorX7-jTlDFGAM57EhkRZBTdSTYHxcuyz8mTw-vA
6oTjUAYx2v_WALrZ7QZJWJeTADHHg0D_fNxJgLBNnbge4pMnicOQKQDUfTDJ6Ybgtixyx3FpuERgOZBUFtG7vkgc_CJB4_TCpjNDEXFnipxCkRgPj0-w0tFr
_abtO8vESgIxOyxU6_VHp7nTjJCHQv5ki4v4Kg9tLlZudYhqHc9mvHfTdAaxlDVeS6LMXqc5FdR9vcMwkv0KwcxCQTr37LgfUrwtVrQ_wJVzfj_q_cVhkpRz
eii77HbzTtxwLMOrUbzU3s_cwxfz-6yxLz-TlXuyJTI_7IyiF4tlQ_2lFw_lqM_vKRyazZvM68OC8ZZMSK6NatC54VABUhp2E6jZZVMBXSTPjYPsf7kiOyVb
0wzrenxhrrSOrqCTUbNVBIeyheSfrkFF_d8zJTm2FLxXTP-Vl1DTrynH949zh31xIeT8tvrdd042VgHFkL1T-EZjksxppY_ngWShJ6MpqOu7Ayo6njk35Kww
88rNcAz_75HLfTaFL_W
}

