sprite $image28 [244x187/16z] {
vDW5bkmm34HHIHPc__lzC4mr39xAtK5YlrETbc-qskLSh6Qcbvo7vbmgavFmkPKg9x1wxk7FMclkuyywvYcbp24Z8Poi1sldtIUiZJTaB9Lvd_YpjfhNwiKR
CbR6l4yuQzwGiM3weScVTGn0cxNtV4WgxpvXJh1Fr5dxV9PItdt2WZXap7dt2MiZ29aeQ-lvCi6xJrWxRyXO6-y-OQcy-uG5RyXOBzvzmifs2va_Qwtv4RxF
Fl5dxJq0QzRM0x1chJaRSEQGSTO4-xJfLwRLR2K8GjxkAzDdHsqRX4opMrgpiU3T9wmNxxN6ofZt2MVDkqzOCEyJpfevP9mrSyWuQzvzmlmRGYR9sdf-jLBU
VSA2E6JCUVS9Q-FT9ooLDsGiwFRfutyUrL0g4woFOm3Qh2jfdphmCsSswKFtmi-SgmxMhE4pcrZJPWsVMSI7zAaTFxD8dYNhghv-Pj5pPArpJAV9bJNyMVln
jxmpKLjRrw6e96koxBx_wzuc4Ixu-kFyT2AXwynZkyBUE3jqc2y3H_tmMjVXFC1FhxL7rCpsu7FFBSDTBwAQ3kUFhxNiqfvdrOIaz4UkpDdvysiDK3FRY311
dnZmQ7tVadLpvYOmeVPnrgtttLcP4B7q7cLoLhMFaexUqra8DyXxh_V5BgOVjQsZzU6imeSrH--6aB0cDJucriDvaowu8wtVQetCeZiVKUj8uU6ifQGrsQZr
SCvQVuHnElk-9R5am4ljtH40w8UpPwqlNkG4A6vR4lckrWe0g3UY-OLhdSO3kTzLTAkrjjuOG6-qtiCk6l3eCp6ST-vhdLLFv-ur0tvTusJUabWAPgrHXtFq
thsrwzMwzGKKuOzRal3WzXRc-ftQcxVUcsMjhscS0CwxYkZcV4YtiFs8tfpx_gTnrLWdYorvL9f43kVUUnq1DztmkDJvD3Esv1t48Ye4HIpVlsAtzjRiAhUZ
a_7axBabxq0YWWtsu-MDtevQcrxYTZJw4zgHxO88QyJLMulUU_eEB2vfdCwv9M49ccdTN-jMq_Ocxt6X8i_ENF3UkZ3SKzmijdmV0HSHlL7ZAaMUdND0R-Hk
lfFEMbj4xxs5gp2hgjcezOLYFPpTLGlp23YBAaoegqVlhVLGPb6HgTPNY7NInguYBcbTM0XcQAjrQwttffipo-YsnqLYdJJDZN6_gX06Kwrhtelj0T-fkJAl
O9oqXrrLHi2NYAkrmtc4k-RAZ0iKEMcFkmhvgJNkjJRRhOTpRsxgSVuY9stULJITMujQg-aFzaZLzjvjtVehjF_VLGKJM5BoxSlIt7jljVUizSbZdSwmsf8x
14k8MLLqO7LptgUrnTcDqxbEpfXRafLX2REOyAFrRMPwdBB8ixFMT1uKPXPbO2CO80m8YPdr3c-z7KLdZnCMUNO6SbUQublAxYYQgZHT5apdGGtRb9MWr3Xf
h9CsthPWiEicg78eYieqiSNtN9kvxN-YB1aOYVF5UdOctBbPFjgH5G3WHRkrcbQhxcvvQoQP1jGuPwpJUJwJ2qyntckDJ32ZQjMjrjrwbqxdlIznhbZFpZy-
gyg7OJ2HjPxOQxpZXxKSpd9SknfdD4xdFA1krhJmGvErixL8wwex111DO4FYJ4MUdQU0hoXMbiwXNdVkd7klvRXISPeYpyv9UMxDHajdFQnDrUpct7tK-Zon
dfsdMgzHNJkhMBYhvEiiSJWV3vfgd2RMi_DSwoLel7Hc87TXIMUjRNDcHlYEndbYdSuJnFYLMi_E0Eotypd2X8-NcBFMfp5EvncQf2V4SEaCK6xElTlkt7iR
vzO9Ylp4kM1IO0cgh9q1rTEvs-7SAn5bhTzVv2HM-vXsOxcBST42Fo3ZsJafBW3QqbcZ1nMHhFMxOpqxJvj9leEWXgaYglXOQvgT4_O2wEaiLgcq7hzuMaV_
hJYie4Aq_z5qD7NgjoWkdG7L28e0WFGgiZbtBv2rVhznuw_zjBR8Z321wWld-oiblJUZ4hrtXWE9jnKvKVW2uWHhhFfmNbqfhdtlixNX_FBA_Ct6Zl0bSDHw
GjHhJUSPsMejRNEkAbvWG1xlYdKK-3BaidPMdPodArLCjpvNATFtRtb7h9l0InGlQsThOUayGwu0PNFkRVgl9Vv-h0rUHfpMpkRL-CaROD7U--GCQF5tZIl1
Ju2ck79MjMhFhXJQgaXKuvn5NjTwTbOrOqYGkJnSgQtMUvyds2FEMEGPzh9qbl50GSodf-Lawu-1MDNZhnGPuTTGewKpWExHFvxzkY3SU1nfLEc7SsqjwaoS
eSZhMi_E-PmGCP_zyeFpaAPntLcrRS6BDznelannXXrzTCu72hMczL1-i9RMOpYtsVeDDvelr7foJjW8hUvOIZBTMvEJjfjptApVSAFvEcguT0PKnPBFGSju
8o-KudksQJXpQ6pMBKvpFZslTUxdT1wG2V3cBAF3ege53qQsnMiJb-ePyBESJyzhxRDpKhmWKO7fCVBDslPibuZQMfEgLdVhtuh17qAgpSw9P7wN3y-HyadH
vXnkobRxj_ESJyz1hJuxZreldpcbDK2Dg3NQTzoajT_f70n_5F9cwJn1q_2OFXEptRdMtTf_fxF27wUuBPtpj9ufQKqrNACrxrl0Vr-s7U5l8AxovF7_Ek0a
gfjpzDvRPllCHPv1jISdsYBWJ4Mbsisv_oRdnl0N8IMuW-a_QYs28BMcyyQt2nHvXXLXmCRu-Bsrbl-5JSxdB_AC2DoG7bgcNRLmrj_d70NU0cePphqxJRlg
3petWNSnQitUUzoSQRB-_Sw6y4uuFs-EuGpCi_LmTezVTwu4xqOOleCY10cnpD-1AvrhCnlEfpkVNgyr4GoeCC_M85vhg_NNd1LEGb649xCATah4vlnBsNQ4
yy0oVRESULQ1HQs_w1m5JWKAtpcxbcbMGKJycdCJE1sa1HAglGezp2hqU-TlhpiRd9AYE9nxryTQbnfka_DvpwVNQutQRiwZraM_CpbVjCZhMgFsbivPQn7r
oVd2HLxVZXOHkACG05V_6MT3E3-54RS_m4JHoVd2HPuPH_94UJtRZU4QOFBhpWfNKaxfsTdh2ywES1cu3ElPkORv5vsZm8L0PYw5PclW-lLTrGGk1h6epjRy
mlss8LoDUL_0Qxkg4boMkm7zmguAXgio3sZxugvIk3h4MMl0B-qgH_W0ne16KVqFvo3u37904xDgF7Dk31z2rffLxBcpmcT1mWXanwxwzctXx0YV2U_Ec_Ba
70K-5JoSstG-Du7F1MlKshTmtpiRmYTJt6ll3wzp9VXqU7Dkmxan_0je--6iy8z0diwEyEzGuhjpBV1l8N_tVFeV
}

sprite $image28 [122x94/16z] {
lPW9Zjmw30KVIOcaA7NkVzmVZOqM4dq3dU7ObNqjv34rlU0xi2i1pqFQMdZ1uvGMhKqtur74f_VWoSdPeYsYLJn4FOPUX0iUeAoX5s7yxD2BkFdSf6letLrk
BsdnqBbbEt3YtEa3xvDNmez2MqdNavUxIyfFdXzwH-cMaZuxzwqb9GfBbfG_T_x0F_q1zImfuoutb9GyTtxe_Bdp9UKBsqlAJruI9QKdJnmuYLAgfFovyoNb
2yiFdJytQRkTMETEbvJ_W9eOEdbkzVQSMmaBrQgnknyeJBM0_S792qxCI-A_MQ8mQwripwiVAMpzyzcYFNbkTYqu4N-qi7bd8HpKzXGne9MXKGwpcBT7w6EQ
XL6YCG1MrIVSCSOqMs4Xqcu4hZhTztidFAiYOR17XKnp-9tkwECWZiSG5e945LFLCTpynWEVQBE22HDGvjRgFORRJKClO6VF92nILKUe-eYgTjFGo-m5EDMW
QZ5wKtFzZTymz09QYB1WzJx2zGlpMuPUQpFHLFBX5clz5LQk2ijxLrKaJE12E2aMVNYjqstMuYSFl8ZMAi3JlQ3gFLIdkOVvZnvuguhvhtERVX6ltipZvuRU
gs8YuYM7w47xxTOrUNRe1TJEgbYA20F0bvzOwkaUDh-EpD0x7JXiEDPc8R3ncjnCTOg9B593x-RpmcHohYmiE15pRsvQgnB07XdlRWR9T3DEI7ZTUlRihgee
jfwXvWwyp5jKBFmsktgqB_El1a0Z4WVUpNjKGczp5TEgnCt10hR83BsRGKn_k4NUPa2geOuAVXaW7ecXTpEOMGf_IUayzziCgY8Zm2sa4cgBrD2Jr_Zpkb88
fF8E_31Fk4Y5D9KH1DA8nD1J70L_8K9uKtsQr_uqkbXdO9uxunsA7IgyPZ1lMjQlID4IHfTlDSI7GplXV-6tMrIRrpz-XUB5Loz8-eT32owHGgjd4vfIEN-5
bN4YtncwLrnn3hjw9X68jyD830905G1hz7yTsWXNh7EldgbmYMDtcW3KV9f_w-9VXcwC3-12_AwAI_Le0f28486Q0MpkVVJuUEY23n6rmtowZ-ip2nCL1seB
jzP7egGhg7hJkZ-6iJ08fRVUcxPNegHhMArkkPrkRXunUkHAkaOgxH_XZdkhHH-ZPqkwXXcJobFuLeE9lK_jArdIDQUkZN9MjKwnpBcIhc4XoD3Zm4o4qznY
cIyVav8mW_WOeCZfPczjcIzAIhEY8j1KqnH7N9WlIagTcrh5bnkrNvWlIigU6-sN7FSMjmlpHKdfSvjW8bnyCr-Mb8SORzWsysL9UMY2TrLjCr-Kb8VaR6gl
QfLq4towLrKN9TqZd-wogjfAkjDDH6hBl4gw6nAMiiohf0TWGbdcLT8pjDEyIdeAzcbT9Jr9YTSgwLd8kk0x_0S
}

