sprite $image95 [118x86/16z] {
lPQ9SlCW48Cv5j3YzlrVz__jK1AbpBg1iTKpbpyZZHRSh7pEmTqjAVyb_bPcBDYfAF4-PiZbHxZBPfyAAVbRpFqbkSbS5dAyorpMXV5ACPJynO7AUCboHQ3e
YsgFhhMP0utiTlwlYsoEdD_pHi9XmoKsivqeycoHF_wos_62jj3qZKGrubrk2q_V0NKztfZBK43o1dKftf2Re--AteSX5JGaLmADajx9dSXKQ5MGpTDjGNBE
XvXUgUwTsfYxNhZYvzk2k3_sBaWd2-dnLgq_KchHR5iGdFlQmlvya2DgiFPdEfEMYnpcs-9S_lvERbSZiw2Djn7NZjTkIuiMtt1TdKpCKl3aVjIYGEPIj5ff
DfGc3hHRZT9rrY8lPIZuX_EK0YsqeQ3DQOo6fDqMyfZAijNsHX1JAucPThmXzwDro8DeExNNIfyGtIfN9taf18zcMyJtrN2q_Ore2-qKqAFU69_ER1PwhJyJ
OmW-jcWF2TZSnksFyR8L-cpOp1itNayBZnHntFxnnl8qbnlw4gZG3PBabxcZqqAZjcXzHY5pqHlAvb96unE1sBjse-xOTtEL-uhd3lUymV6ru_2bnYKgjwM3
-hfV7Ko0TM0l63wVadYYTkbRdafjQHy0YY6ewkWD3KTK3fJov413GR64kkc8cmTKCfSAIcrfTJQPswOZRFAlSi9jsQKSABV5acwxL8bh2E-1JfYhTUjKcylc
QeEpkJHhJ7E9Qc4vK1hqr1OkuTXSfjfSvIEHLcuBJtC9tliqP3BLvhAdYc6W3UuJ3hlJm5ocsjmEeO8EsYAD7uXAJA9Qs1vefZMJkGBGO2SgcKjKWqk7FhL6
KSv5cCeBPUe9LodGmSODEcmGbPX47OiDQZHxRmb49NCDAWk5F1e6oXjty0-5NPcO5jNcKg33KOHT1G-HkHRLZdSZS_-sjynG6LkKp3tVMoo5KcqkAVi_Rzo6
49sB-80hhItpvdxL5b5IK-2JvQAvXrsjwd-F5qjCKAi_YNVUN8tkJGARkypSQdA_vPCkOcrpYtT3XMnpLnPAvfBEMxJG5bEYfh3G5aEdBLfeYwbGREwwkUln
ejhckWzqqgA5jYp5kz2M9PjF0qrkIc9p5zfYoXwITQajTeicg5zgj6KrtZhHblKMrOcshBUe6crPaNtKg1DjMMzHlSXSkqLreYqJt3AWJkmjQosgt9OB9KIz
nboxHPMEkHSh5A8QRRaatifjkLwfKRyqN0_ZUEj6RRdBvlcs_0C
}

