sprite $image228 [214x275/16z] {
t9U7Skiw44DZYJIvHVR_V-qhzwPZa48tGaZFD9xX7cZrT9si_NXusbcMPcQzx8hfKErl-heVgDBjDMtPoV1r-v2wX-4x6aHUhseG-J5Skv4S3yfjpbCFoa9X
X5k-60RrKXTANwy5Xe-dwgn747cz2WoVkbxOvf9wOPkFfHUTzKXVBsnpPRrGgF5KQQ5uYdQRyp5K5ugtlFxmOQf0cykrF0wVlbxOvj9wSQ7qzIe64TSBXPBM
YmkbhrUr-wKNWVLeM2_zuKEzbDkSfqeBnLCcQ7EPCUH2wRRyeTe4gOVxjRdaqmk5qjQBjxc-NkP6e_lqyXZ0cdw9yWZWqjSh8e1BNwzunW8kwPQFvoZhnQds
fLUypsvQFkR6iZBSxB6xCLmiW4k_vStTf-Ug8niJOCctl4S0bxvU7W5S-dfvCAnmtPP_WP7MYrFfwuLKoELgUY4LOddhpx-ew8LKoEMjcPXUI8LSrhgkNXuG
T_S_FmINAAIIQaFKYrFfjpodqb-YF5XSyXs5KqajKULxAdszE9M-NXu3M9FgXLJgUgs4IbulJgMl5rB9jpodqjSBgVJrObJwIvG7ZUux2g5IrmkfzBaYaKfT
Byy4AhdhGYQWKkVoIA2IvufCe1h1cedBCu5AyRgG2Qcs5EQA95IHiboU7n8UxxDjry7oHp9bh1uHsjVbyHaADYOzBc3ojut93BWabYZFJ_7t6rDlTWEz7iFq
dghfZ24NwkLV4IzOGdfnePuJ406zwF1HAWczF90fab29j3mAzNaU8-Iu78J2Vq5kCuRXTn4AgRQS-xfucqFWMgRbucsEWUDFoyM73uF7dxNbUPjZy5ec7KFU
vfmgtzt5Z6COlCqvrNO-RGd7VyGIDIuKKftEvssRGA-nDkTtTJvjCMVBypRdYPVBsY8cQFcXuSC4v6PwnKlCWEjAJECx--NNrHjW3RJv0DLDzUgjmHYE2kK3
L3VIgtVGQt3u_5kg_2tNbLhUHzkSP-1QRj-6FYXKgz_jx8zvUl6NtUzZQoj0HOvV-psVNkDjxkMO2NV5JhaknUwoHFabGiMnUY9LCguIVQb-btSKrkRVfnNB
1AeydKxac2MtF2v-btUKmU6pVtav5orNLXMAfYmLHCp_V-wzsKMwiO9fZAd3UJyoXhDnuKBCZi0iLBrdlnyRASdocwPg3Sf_qgEScNoRB-RA0ohnx25awbSP
QsiD7rHqkRm-4bGaPfkA_q_5HsPIWAgN7pSMgXZfuYe_NyrH16LGgKeGMwinTilCfJ7Iuxz1oDTM-Gy5PLD925LhgR_188ZX7nLp3k0tKVFocjnyALNsK-Lw
Kb7PIUg6ZCSlajUecbShSI8e3zMMdbHRLijNrP0kD56ZpMTa3dSqI9FjsKkgGhMd7VjT5OkYkaHU4_O8c5rKifg2-txiHTfxhvHlYkgIRJWZA0-LNWq8LMku
TyilK4kY2tiKPxyXWl9IoMf8rusUw_dyc2xfKNpz1l8W79uzLA7gbmzqrE9BvENiDoQfT7NOewRIgyIOYIwHbqDGTC3vgBYryz0HaKkoVlguxoXK6RywHt7s
6oL4jYE_U7P-aHU4O2upxl0izY4MNu-oJbNY8IZQRpUBQkpPprpPt5Nqy-WfCORqFNbv-erqktcfcgAQAMw9MylXQoRgNRzn_4VORZugIHP_Sh-Pj8bQbzTV
_KO9joFIH0sSvuhiD54-hFVzHeqtYKmUgdak-VSniCD4kUETFQhvoHHBNCYLAGhSIrTEiB6YMkHwqs_W9am1y-RKbJzT44CYpGLnerLlAp7kDyekJ1iyy6Qe
NBKPa7C0NHqm2DLwkanxf0ML1Cz7vQzwWAtLc5_-FPRwzXL0eIagtM_y26elwIcjMSzkZpqRAwh6-UK31MjhOou2S61P_GQ67q71ziIZAIej2WJBcaDMLFto
soD6FGe2pb2L_SSUIS0FteQGfwZqAlDkMVEoeQAIvIkgKRh8JQK5bRIWX2bZSEr0cmj3BFJQen0Gbsp-88HgtRD74dlK2qeEAx-k4EbbDIaMaxVaMpvKTru-
FwY8FhuWx1QdTzmF7kQPQe60h_AYKHu1Af6eZahFLNCnNCWy5UeT9tyBWkUbAW1p7Z2dSb2LBVVo8dhypfNq1-QfGEsu8_Aljj119PLvwW5ashDGvQpd3PBv
sfh1DKsr5-N-r5aCIvvzd2xS4qcMMurxwPTFjIySZJ-XsW2K-zEb8yvJ-KmKG7rIjLQI0bPbta4ofD8x3lgpU87A9I-Xudp-GN1VvkUfgCJ1ONLRet8rxYLK
ssmiKg5nM2KXdQ7wx0a9nInKnkd5K3wb0htZpdXvqRFRl4oavmqr9xFES2t5LGTjAYseldGK1vKpBVt_fxbmYyCFg0l7QQfKedqMp-ZAsMA9PceX0HI38G5z
bV-Pfj_R9DMEIK1Upc8dbRywA1zBXOmFf11VBmZlyaY0t5JuAwXmEelTL9D3gNQ4afUYgXZo-J4A7nUE2CLBHRyxJj_4JDL0Aix3jwDIyj9KZTFWFXS19clW
BQ5n5YUlPoypykBsowMteL2rXgW-O3JwNgfOpCQHl5Gm8o-DnKJ2fQWA3bhYCfChxVuwl56kOaz503E7ht2Pyag1XMhwWb2FeQ0xh4vdSVnZiZ_fRMsklied
52hzWMagFBi_RJNYQ6uYiU9jkTdo8im1gnb-gjgvFuadNXpDJHOzU-Dtyi8rgbIPy-0cHgYikOc3QbLUYrHI0mFqDp42HJqJ9Hb4ak7PFskncY6lRr5bszpc
PCvDoXuLbQCwEAjyCqoK14zJzUwlinhH41IbLDFiDslNjc4JSpj1fNVSkI-EkfghX7az-xoygiNrcARp55KTtCGSc6fkeX8sThVjU_9YHVN0cikLPMxrBQSM
L8G_N_mioSleKUJfm-D_AaYJLAbOKv4YWqYLC8lgSdanoyNt5DLkcrkPctG9izqjEG_VQNbL5GM0_5JsJKoilQ3GCJtufhoCgb7ykT9N5Relrk-qA6R7zE3B
ycBZ0rugCiojZ0rAx0Grff8hhYzNULR_OPOAhSEggdTQah1tLDFLmSN5guwfTtzLzHkIC2_LihmKrZBL1cD1LPwWMfSN2zSwbPwAgDDM4kQZCjQm9AzLghEW
A2L3K2QLSrTz9g-wG5MK-oF37Zce7BjgCOzyD_zFeY7Lh_ixxD5Fly7ifR9NiswYxEc1PYMogK09gkytN5J-vI-KINDw8DyIBJIcIieUAJ_xbwxayBrGNdfw
GFHATMz4P5A9eE0iADZ-Uiz-I-HO_deUxtSrFT1KmcLGRMZs6oNyFJrus2nlTLYNLm6mgEuYBqs5Thz1hadFKMLygrmlauH0Pog9IZqLM_r6TKvwv4JuXhVr
STK1rRsnfZBx3ToSavwRH2BNyjVBf8_AwZVKvHavgEH_lN3vpBDKfFgDroV5qKarBwyvtZagUkatrDrWykfA8j9ATV1p4RsdYlkfty2WxmRzL1Bv4ddPM6Cg
aeANf9htas4_rVNoqi72DQ9IWhAV52S_bSH-eOcIa5yJOKYbxP5zUUQZkbnUW5sHQ0yk8ejAznls6ttCSxcIsBulBz0Ea0-8IjMcWgW5PGoouZpLzqnK6tpt
WDi3WxdMPb8bvl5a-47w0TKr9WgBUYRE_8-AkVAGoXoT2jx7LBVlzoYICT7LdHyaN9jD1UesMXzMYrHVwr5UfmUIgIO9QoQLEJeLlFAUgewPBkbH4EYv0Tk1
qsGRcbHnyAGukwdiY5VqA4T-MEGbNAsUgO8ML5Swee_gQddnsTGojmS9j_QK5v-ePCTPa-4rgdKJPOVQW8zyYRoueo9ZT2gbOuLgNLvswCgkwKwwmj4R_GMg
9HFL_gJwXyAjSJjqPL21-On90XQfrdiKUmUsPxu4oQOAQ9_5E4zrlRnaw_NoUgs1s-WPqnONgBxPenGoAhkg5mPLrEwlRnmNg1RbDNn6B8wf7LklyUFFhrIb
39ynhLFP9cfUNW1eL7OjhpFLwB2QfRgoojD1HR83fPWhUHcwihvGTaHUeFfgZqBoR5vNTYMl0LL2yqanpLDTQA8GG5Ts9I-JAfR1a-9eGzMuGYLLVhv7aQ8X
MqzlGA7Ixza3FiZCizYcof4Mg5RaLVhAhXrJJuMce7RpbbFDJVnKwpsA-lUw5nPvcPMTzZTVxexszmxMgFnp53iwQo4YOxRViyTEKEOjfynDvgdMJPIEqzOJ
ElCzktqMLrjGVgfrUTcUNSpwKruMLU_-55vAnY-Piq2rPgB-rzjv83iI0o5qWxCzklzjDpcyCXARFaNVWAfv6DIZyLiNnjb_gbkfqlIdNovY4HbNvJkA7nuz
gkEaQav_oDi9K4PL2o_VXLNLrLmemmFDUrgiMcNo8Kgt1tTB1wyrL_Poz-xvbm3BW97HvF5osmDgbNNsummKyYu6A5QjRf8TXUs1T67mcbNPozqd-OBv1RHE
T-5cyYv_FdFtu6dcu3LcLUuavg10NP5tfuwfuCNsOD25dRER2sNNnSsu_m0gqr7O7hWkh1vetj4tRivcA3r-Zo9t3-IdoYSctOe0LC3Dio5Akx1tTar_z0tc
Fu1ATHH_oaaNLbLo4hEx01J3gbMcW9VEMmjsYOazN0YeV8XYR1TMLM_fpyUZYm1LnmjHWsEOSOzFawhpUQz09U9HFaJzlWjleahZqUhXkrDNdeFHHGkc2uig
lbpaWJe57huWNdJXRMntlDQgFXEFicwU3r4uErrucrKHZvRRge2RX_5Q7BFFggHlN2yfDy-7ABgmEhkgEj4tK9M9HtcNrrFEiTtncbJz1gY4c-VneWjxP_Vn
A51smo4ALNBAEQkwxiJDmsKtx_AywZESivk-aNJpF5xtg3Gskl2RgkFk5ClcrOx2gpuBPmUeW9kty4AME3kJAxjzlBPnTtPHbNRpFbxR7IzKnTsy7w9ku8Mg
E53zZe8iLANSlFyO2bweAfJTJeZYZAbGTfjueQeGZseT1LM5ijjpULGLub6repJSl1-Y6l6eZrSZ7lNnQhXvlwCqtBoFLyFD-nqbvkRV0G
}

sprite $image228 [107x138/16z] {
l9G9gYjH20KpfptbvUr_jNyI11hCfsdDoS1CWLNSo__tt1wNh-o-oVI-pODkRydCPA_hBEZwD5bCDdh5nrzGJjjzx7PRW78QKdPzIRQVxDclB2NjfktH7tYn
3ByhSFimwNNjacGrAPNr1LulmsyFl5TP7NYzVAkQ0wzXZxR0-vLbuCUdLDOL-EVmh-s1rrTy34Ygmsy8l3Fy0w2pRnKKhFxmeO3rAuE4JIkZa_NvhTeWDgzC
KYzCfJ90AbZDRnM0sc7ReovGyJyQFf0msqR39oUXPcKL2casV2XW_SgWWFKhWmBM_rQH6rS6yp3fTKjK2PEwmYzGCsyLkUahEdm59dnHh3TyVBa3u8mgaw_b
lWYMprrH_0Nv4Z4VW-7_G8u1ie1DA5E05c81UizSCIKj5xuSG301KzukaCGEA9CEIb9quUpcFU7dxL0W4vM0fYkA0Ba2cQWzwpHi9obH-Dh1JeQVWUVj4lNp
umaugsmVU2nHQn7puyhgm1EP8tTKsLi9AmF_2ojGHvIP0QWEFA3XRINAWRDN_5sAUI2vheHGr55DkBJtlzl_SQk5h4UPKLalnrCtmA192xu2YUtVibEBdv-2
vGLtE9XueX1YGBJm-UABJD2nTsRYajYsiXCD60YW4ovEM5vmputOlrzHrjst9WgugivAYvoB3E7TftrCQWP7HKIcgnXf2uWRduii2kvVmpjvW_SeDEwCjZXC
10IZKyL75Dpyn_0E-4HjOXPMXIS7EhVnTmKt6zyH-VU1Yh8BWmoqbh4jiHThM1Jy418Ir1lGs7ZxFsNn4EHFkoefk7ILVr6zO_r_P6dOL3uS-spo9nUF1JTh
5qfGh-t_FruqmkhYQbYGHaXqksGetRluQPQqhl9FP3agGkhYhudtnC3qP6eqwY4aYPWC5LlewQ3dBL6L6aIqo8XFL6hO38dCslLokJtlkO4HJVoSkX9MbGpx
W3N9KCCx_Z-aw-DnpGpSivvnKY-2A3wyfC7Y36Ng1N-uTmwwfGOARuFL0YmBOOiF1YdARgIsN9mnTAK6IZlsRy9OL9xhuXMHK9QX6EAC-wRhQmFn2NC_cQcj
wqFCWfMX-E8XJLrt_eBAkiZo8jaYimmpKQgFszJbpB-LFLJAOYmHMHmKgO6pV6zTgO7v0iTOjlnSbpSmnW4TEOgTuGOENQc1kJ3ha5YsoxPuxMKgkO7tdQwq
WPB3h7U3k9h3ueKgSMwWbs_gIbHnouzDc5bt0NFnSlmbaSp062fdiY5Meo5x5yvXJPZrUzd53GnTPB7jKPSTpXgHoUAeRsKN3obqiUtlfhBigY4iKNCqS0wL
wtg8pG_9Q4dPgyZcpPUhSaRe8eCf4InkzahOW45tPSzHEiitT547axf_XyLKkxXDcI4lEx_5J5qDGdAusRab_SjTZ0zPd1cu6wedu27HuMRdGbZ0yAtigZ5K
yYuuEoZRx7La7LyRABDyRD9qblmJbVGlZ-mhIkMzB2uDwkNsa8hDZXAy9yhUm7Vv51JUxL580VdFaxARgUmDlCiR8aswwW7rb8Em6emE9LbHhmwHMVOhESIq
fJVxvRfevcAXadX3lJeKZl8_6mL7v-HcztEAeESZsr3TNzlDKJEazHoK8ygVEwCMapwEwdsWQ8HaMC_1H9K_IMGbJ2Pgg18PBrPqNS-c7EKhIulY7s60o0w5
4P9ivyLDSbGLMV9wW6ugUrLj3McUJPcg-JpaRv6n3FEwQtczPbRpPf-wCbGyTV6Zx313xy3MGCYsRGi3XukjdE9vqC7wOC5L5JTxWehYbsLtLTRVGAWTRlPx
OM1P_2FARE20QU1U5zUeObVDPvKqLSNDFi-c2ZMB_oqoaWzL6ogvsGjKkQk8Hzb7K4DLtEpRkqYfgeuioZw4XO4nLCUR_GkgsbN2hieEgcAeucQFpzSbY6fN
JVvHbOep3ZTxV58rGrMxAXfeOxR2m3bKSRF7tPIYwbsLZx34KCNDFk-cGjMCxE0YQrRsUN8UR_PXe_6juAIxgd4-mZpBjvw3mpjra3p-mCcBJvAeajrGFNLu
Pt1TImNuigkOZoCSD_jrtkopx7Ij0OVY5sK7h-MxqZuaSP4ddmVZKFRZ28-RVO6IJ90-ps8Yia3rWwfvi-yBtWhlgbqLgWPkjsvl724L1QyZY-BtmmZxpGuX
zTATA7YzgvAomxsp8Ub4mUjTXTuFYmd4fmjU5pzaHItQ3mKlTnNwhkpoKy7hueSgs8y5htVLp0e_5xpULGZKhmMlTvMZJXNyfrrbPmh-swuwKV0Vfmmd2lvZ
PFgNWly7
}

