sprite $image230 [283x192/16z] {
xDY5UKKn34FX66BOV-0ojog_Y_ftYCxdZ2L9b8qFqEmRgUCDikfxKyOBfDbFoiSZakXN7YU7lDy97OEi-YES7Ca6oXbiuDmXz-hFXJ3OI4q66ohZMu9I6Mme
X2Dpyf0B23Od1umC9yUoV-FujuD6VuIJ8xFwhz8OR2YKmOQcCDX8EOCDfJBOK0Y3ZPGBHmOfOx2XL0RxO26Nw0MKCzXG6eCDXJBOq1G66oddo41f33OKiiTW
StAyLrQscwjWUQaS6IY4mOOcWmsLyIr1gLiEDYTdzbOvWmsLSMIW58xCjaBklGlb71ceTFVVUFiFEGus9yUhzwUCmOPI6MmeXC56oXbig6p1aU7aoEoZcB94
i3avbdqiQGms57gfgu2JWuFDoSa6E3dNxPm1hgky3eHLI70oO_Q_tVTwAXS9aMiTwx-zr31B-0JVTDAq97ee-RS3ixDfOUMG-U7COJJvuSWKHqFYLiu0JVwt
gaJHtCePehcLuw19hvpw2A2vbUEZCJZtTY0l1sUPOcXkvUpHtChnqTn5xgEvjmF_5FJKAOyOcdix60BSoXcVr-1MpY6QjeWqt4L-YEQPgyAPFJJFD5hkxR13
iqWFiCcv7JRNDdd1wNehnz2yW_Q3Phstmz41g3pHA8UvKf5pbsveihFnRsQNVLy3XkOkyeMZg5vTEG_XORgqZgihP-x7QCJWtChPetccTrnSEOy3vJHvflME
YojdQeFdHbe7hdTS0GCpK4wJLvP-iGS7rDqzMN0Nj1UQXRmI7AfkQ8RAmG-QHbu73bGtD9voseLs5LGDpJwbSnTqN6OxW3f0OyevZgwgkU5GTO36sGxh_vDv
M45rZCOojm6Qn6oWwg4nvJXeai41rKMp5JcuYngRV72e-pW_L7NGfDaEK7NGkCfH1ms91E-IWsPmNA669WaS0-EZyPMZQcIG0mvKHsZyJ8CY9xvVEL2DeXcV
a3e-_fPtAOp6ygWuGFFjSAWQGECenz2iN-nZg8RG-CfH1yt9bGDg58s_7VIDfjS-WdDsC3wQa78sDAKJtmG7QecXyRU3KbzeP5qL6B31cS74qVZRmT2iMh_Z
mG4rW2Qa74EpzluDNKNL09fWaHiQzlCNELG3QEBA8HRrq10u_Rlaembi1qZN3Gq6S4uC9ex6_zwX2moDbCuJmZ4mOJHnvRJ5q5GIPuC3_MNQ523Y7LT8Tpxb
dFzTKfGWaN6H6vgLXOFW_EyIQu24evmDpIhAKN3oT-c_-o_vX-00JLEEWnE3wNCKXByTkgY7XaWf6LyvaAPlD4CVdxAmxLwibtYHGs1eQd6AF4bXM_pR5Rqg
VrBQIWVEMTwbW6H2sy5I-1pbSDWaA6md1Todw1DDvI18LzY-SYnbVQPp69oXiCEIYMy7GzCu3X8KTaWvNTH1G-BV5lO7c0osWyY6fi61y_d2VdoIpFvcDgGR
cgdWRy81_z4gY2kdorRbwh3vP64xalc0SdPLtluE79n6Cdug1cY4Wo11OGUsWw5nFkKaM0MnJpbrTT0G2LP1Q3jquRfgvv-21AiWf9mcQcYmW1Pru2IGZAyS
I6ly2IQ1mTbTOaA2LH0v8OKzDNLT5SV_H83F7EETJpaRcbLVRzMgt0MdESRxy765eR6x9xeUe4jIs7ucEKIpRa_DFa22mWvj1vGDZQuy2X8KTgZ8ky14hChZ
845XXvJJXTgjl0T1WiAER0SqwNp6_VrPN38dAEpOxGg0Rf2Wi8C_1l63-37UbsKI7yuyzHqS92fiVpkCqoQPGMv1WbKGKeu5pT1KxluQ9gTa_2AtB6KnD6sU
QYVV13CKTdmxa601G19bhbETb_O-qqXIs77bo8IvD9Arp7EJIKh1Rz78xbtAePm5fHTKa9WVZscghIpDqCGAEujoHAfK2af5Npf0b5P_WmRHmZx_TgXpBsH_
0s5fnT3aben_N05MD5bOUnMIVCicJs77ZojwdTl28cLPEebvCZIdEyRx_EqA00LbgPXh8z44XYQm2j8fH-ei5HM59BkX2HtZfIlorbf5PG4jwGexVbpHnK6J
O1M4VmpYe0aKTgRjK45BpiAEVzK9lfEziEF75SnUsF7Z2gOlxFWroUZtRectWoLSsFcL4xxPcdyxXA_FvrVEiB1lvQGlxFWroM5Xtye9huByss4WcJkL7vRC
_m
}

sprite $image230 [142x96/16z] {
pPcBRkmu34Flv65RfDp__zjzJOKCX6jiLYj4vHSSn8UbqFaLoZxQwzSFoTP48CUFO7cT0X4HZBqUvXYGTu2-5JzIXro1d8Nwl9f0FbAgp-bP2lNPJHWNe6q5
mZWOfq-XC3uOHq6hrq7VAuNnWJmn5blpmfJfOpFWizQdM1Ylp_R035YgzB5M1tZEHsRWlZvxGQi3-gJCG84-WLQ7zOctkb2VFOd5JjNS6IZKnuH9vJcAXLdh
4v-1CdtYCn2uDGg4MTmQeLPNwMCpy420jWLce50VprAh3nd7oRyro3XF_bWm0IVlrY0TJwa-j5JgusdgzV4qhDU7NF5KZ0LPo0El3qaCORq-HYDdwrAep-6-
JM-jb-jpUOFHeApNHxuXXChFe4QV0nyOWcfzNet6WzO5rVfiWz-HtaSP3wH_t-cc3qRlJOhquRHkdRXuKD8kw5IZ-T0795KVvW7dLACnVInpAf_aeKvLDHgd
3-VN91_J1pgdVj1uVTG-ZWKFi1ZDbLUdqiHvWWTKOt4qNfy7le-nN3G-XwYpn-7aFjAAnkkZSv8SZYUvrMiQhuygYQ5mFEd2U9grFi0NXEayndABvher85yJ
JfzqOJpDMX-0896dZmdZCnsDp_RMHq1AdZxKtx9CsV_zVu9sgk8BS6EH-4XpybWWBFHHEdtoX9bwyoS0kpK0yF_gWzKZZUqMYkb3aaBga1dNPyM2_Hw7lpLq
SALFN9ZpDeRNHsGg5lh4XEaBOUxg0rASFl5MtnDcFHPuwoEE9oICQtMMFh5M1p7yhO7x-e1fmgpr4G4v1acgyUJCG5mVJA7Ha0ZFGA8-IWjYmgJeOtzzrEaJ
de6uFltIHvtEWHb8rESAZ2Sy0_4SucwCOVqFp42UFYJHgHpj1446PY1J7vAz3sBVpxEH3Cn0bZvAacXjZD7Fta_yxjjCXbeTlJMaI-z358SeTJueZCzxB4Rl
P-liWzIPFmF_-LJjRNHH64rW1bB70jA5D9h032Jh0nXDvWp4RmsZ2Sn0kZv6ivY12dseCzxg_B5Op42DFbGt0vNPHhJLVm8
}

