sprite $image298 [300x239/16z] {
xDW7JWKn38JXs75zU__pqZk47Jeiynt1KaQ_ChxMh9018CdkBXlxo4zzgUROGx5jrzTA7Rjug-rqVIsNiOEtkhuME5ky5VuGUQlRPzYzxWUAsqlTyV4ARdi_
ikW7YYUNMiyMnPDJBMUBl5SUzmFDwaTMiqMQ_SXgjaYyzxcCGLQDACwMLgDAntycqMyHoax0EJi1LvETW4lbKE52s0auvr3XQlBvuLBP2RWGFZzO6Ji1bvD3
XGjX9-1Sni7CxAzIng72bHxfu_EhXR0JSCRdXwl9Ji2biXDm8Hmgd1rxg3XRtZybXKE5S-7pWvKThHFO3zQ_GmWx0UU762hsWtZ_Dgdi15m8dn_E_cedSBQy
VxTGTWBEXKC5AsCdu5B_HYUm7sRs7-F2Je3LP2VWKja9k11s0goSGuMhoKx0fR8JSEVjt8c-gaWF171wxwGYv_sVzbjijHIbOHRELIIpCllyVoHM1wx97Ust
lk9ne7cBTtFN3weZFuYghAjZR0c0_MdLk96LBM4T-O5MjakjxBQnCknHAsvZPGRTuTWAsrZPCRR-WfK1HtvOQGMH8p-id5Ubb8fZR2rRQIt_Bm2xp0_-txD2
3kLYjTUnzUzP-S6t5cnfwnXRdHwCmv2hme0ZFonPgNSLPbUhuzWpQqKaMXrZgvUlfbP7VbYqOjoIOsmjMJ5k0JZ6Li-AmRGeSEI7lXN240lZrZ6sEbOMXY6N
gktoI5jTgpeCMHYtZcrDnyfgciQjOspH2XN4cT3jTybSmj-o6gBshBJAr-S7lLevFoJCMQ6s1F7TnnvShRmLvnIW4dyjvH8XlZi_W5Q6e61khxXOYOzdAm6-
AJ_qhIph_OrKOK1B4AcKgWPyrRQcRrNFLgYbbJGTTOClWfsdhVWNhSuSY2dcDg2kqTIbIQ3uoh55AoSN3Yc6LCvbhuBgrowPQHM6XAA0QJNJCrQTjrBzkcCF
hGp5EQ-0MJQpL4eHp5cXjaNWbnrxG0wabg-aciLpP7XXnRW5O9TQVicgbRQhcdFKoPgKduCbbQlLb-K7lDoB2kmnjpDjmRL5uCLrvyUUljKqjpSfJdg4mMN6
hNrgrR3Q2fMvNMBCR3ep4pTmVxFt_D2tckRsf4WDwtfOLDdz8f1Zgs-5y93Rivb5MhsEMzYbLknRFUVs0hEIUJfy6RVschP2rwhbTiJRVOLY9eaRcfcufS0-
nrRNQfhRfMZAEXdcQ9Vyb1HWf_d1zQockLronkH6ucrMXi1Xji_y47kPeQPEReUM-qLWFYy21NjU1DRGorS20BoinAcN057qjWWC5RjDMwfyD_UlvdQD3OiB
6ubrjsbB-J0chShj8J2tMnMpHAjzFtR5_HjxDRwoqiVS3kRs-q2X4wlT_VYBwyI-XQ7wR8MO9xaTwMQ5IuolQizMZ5k2JzTI6AsWAg86_ZzMlUPscy_jMin2
dSGjNa6l_VhPMcoIIsdxVRxqg2jokwHO9d6BTnbYA7pB3QeVstvJAroik5h0YjmEt78xRoGmGLnQ41-R7nGsRuKSKhEIQvl58ZSEpUKfjnTSqEhJ8h3TWbm4
Vg1KnqeoIiEgbtrxwkHsOMwt_BG8z46DhVrvMZ3hMubPoKs0kNqQjrxaTYIpd6b5NG2VcBRKRC4AvJBDgoxbTacI9el0H2iM0581-a7jrxUoWdDe4hpCxN4k
jpDGLDYC5QJzfVefKdqhY6JLS1lcA9DzUvxDxSXdAuNDM6czBGBr4zglRwNd5ajHk6-VvdPZRZzVHkwl9DU6RA_cbQR2lnFw0L9zgnBECEqldidjbRbTysDk
HrK3Y5I3q2eElYMHDry4AcoLLNOkbdg1NPNRmtDkPmyMvnBCm4LWrNT_x4gflfNaf3u9hPZR5PSsqrJq7iVqQT-EcrNHuCh5IlsGffjwVUVswriDtckarQhS
NblF0hSyKIgjViOQW7Qf_3iP8Twv_VfMm-1SuWgYjLcAcEJs-ZAtfnHJmmAjVduIq5a4Gj-v_VfMmv1qiXTjrztSBipjJrRvbHM76rJVkVtwLaCKhhPelIwt
nsUhqURN-9T5eBwfLD-gLG9t2DJYldrjRYzvdBNIokKMz9q7LTzgSESndCyG5Vn_JB2bt5xLc1c6WB7YQfMLLZguV1-tz0q7LT-A5Ieikf1B5Lejv7RDvJ6t
brnSZZShvp9eDOJpffxVnFA6xTUtOaMD9Rj2TURskNqxHEt1gemM_SqgYFFLZ8j0VOD5eCB-lXNBPVXAgqkRIU9BZvf2jSUurQ8vP_kOQFKp5YVNUHKp7fSG
1dr7gRuLAxWg2YE7P7dAxV8wjpDVqUfdh3AxiE6zzMQ3gc_5AkpcfTnkpEttLcQWrOzqh7ZiURD1rRTY9GN_oiUqnRZLSdjypksNp42h4pfMJUlzsc_PYbEB
Mqt5lLM92xdTbTEFqcfijrcxolBQ2j0tRB--5SkV8vQs_b9QIPASUlls4eENnCoGR6Jt-Y5XOiMnzMRjjsp52WAhGyYbLA5L5RFSpUrb5C_Cu9ChHMvMsRa2
MltYs5BO5bOSMzKddweehJgvdRFz5C4UH1XkLk5aQIYq-eMnHQbDhGONFN8KMZ6tN-EM9kRskSoGXLO_eynR0RhPeDhCYfMcLfg1fzoEYPMo1rjceDKFEbQs
YPQQRMh5YW8yfAqKAxgvlMK6MfdUMvsqOxN1s5BOBrWnFz2AH7EvtMFyEJrO_TYzrSzftcg3iGMpxQrOll2x1Yflw9bzktV9CZD37Nz6PePyQbTTAq0tQB-j
hPWVkAkhC5gbb9vokoKNRbQ33n1cXk2bEwyujZPelssjM57D4E9a4OXaLfxsxIEO6VnOdHVse7hNjUBOsa1gSokEBVZW4nU1dNrx1ZYlB3vaXjoie3qhQcqm
g3QpOldgfRegj69kbyUTZ2nd1dKPVIj0DnXKcrinoK-icDixcK4VhAmsgy4jMHbKjsg_xQq6vsgZOZJDazmUJxJgP0Q4dXN7rWPI6rkncBQOstbbfj7NaUFR
sRsLr_5cbShP2bqh0tIhzjlUQl2LFQYFQQkL-12P6Lm-gTwiN3HSUz33O0WP7Ii6-GsaDhVYGsfedJnslHGAhJoYZvnNo2wscmvjNi4Fic05g6xKVjjR3Uth
i6fBeKghMy4uhqQvprSZmiMgX7PVhR02T8ESiBqL7rANmUV7fQcnrcO6bAnjR7MjeBf1-srhnGgrXCANtDPRMRdF3F3kR9KBkbRBMWfxDokM3qYhh4QZrUNg
Z7G_h-9G5gm0tQ3zDhUYLX91rygD3vd1c1boQJteBrQvRzNNKhCtjkAJnAvL23hYrbxPrz7qqeFXFZD8gYkieDgHUbihRcjeXMSh51-vRpS9eLJEA_PWQX-M
fSnOTRGKzXbMV7yIMX_IriqmErgPLT-ia9aPs8DvI0jMW7O6rJjRSScC-lZObJgcCF0AU9KPYbjj1TLE-xsl5Oyzy25p4KYhcM767lGjCsGrm3IjiAAMmZx8
YiSUdroi8ijMlSoGszZIYevLqwBKXrYnabTnyXUiygK7tOjv9KD4tmgWr0TPCSalMetZgLqnCyHhPYW6MBrQ-KKhs0TQiPmeYFDiDROG_shF45lprVRm32di
tMg8AwnEriiCxJSIAW13tR4L7r83gFh2YkT1rRDLJIqpS5wn1zK5F9m7THTMrAhWLsRfezNfvuVxTj5BPa3RCyWPAPx9z68r3BJIMaeLtOqLZpqvviaYa3SM
xwldp11QPiYvxUHffL9QsFrTAzMjh7ZiISwbKcLYTQALdNynvDUP8G4mZGMqadhM4lqzAsJdicvgDRWSa_hylDmwZTFtP5HRPeWjCxYB5NkGLYA5MhzXLLrx
zKLfjKa5ZLEhXdMoHoivMwNMV3Mtp113c-qJAwbinCsj972gR6irE9TdujRKwbLcQ6GbJgoQbc1xAwJfdaxyLbJSrlIjq7emlyuCZrRSmcnjXUAUfigmQVa2
wkWhAvB99JEacSn0AzZcLjKFlrzUxh_gjcEbWllCK5fcY7_4IkFlG_7OWzm-mBfM_SomlHK7rHyhby_fF9LIErPGFEyPT72_RbNyy2VB5yJg0nD4v_rsQH-0
OP8PgBMjbVZXJvTtMlqwAxGHN_dEmtHpZ4Q5_GoggLOAwwoqzU3blaemWAMRMXKtl4a5WIrRgRuwux2KLdl82VsNtFfMPZYJrNJD3DFYmN-FxSSAWhxLf1Kr
5SpN3d92jvB-9Ql1TQnsCAZwvGhMM6cpSiClM4aOthL2nP8LnvRVt0fnUEUAicZ5ssjRA-JXpSibNMSbWldQLKvOtjOiZgrDhJIyFnJpmvgnDLjxomdz_B1g
RCtMpd92lrpUmEgpSqB_sBFIIcjLFDPM1vht7rjzA-5pmNziXUo63wsaMBIwVeEa0AnzveH-kQABLlpA95hjE2VqnrRNoinE1fbexJSdz2igvgtCJkCucg4r
uXLhppcXNqaxFupmT7aXK6kf8d_JIlombt85w5arBH4HfTM-Sq8_FypruCy4wozRPJVihAAYP_KpckdViQgxakAnv-Ndu3W-trZVaHFw-U5rPcXQ9zvO-AQS
i3osQ7NMEblnnlgMdD2lz32sY3MUhK2hhya9_VpmQCMNJNbZVLjEM1vRBx8KrbaX3zzIKK2hHvXLFLZzy4MLb5RtD7gcmdVcXFxOccg9yFBhSa8_FqonH7dL
oGdVMF5H2ufhTNB2jvRBYfVLoGdVMxvqhFevuRl75kiOLBFveMlLVq1wZAtv5wcEylLHQ_q3qcDiTGyqHxcaj5ewq1nQHMcrSA0vAbHQBUM4ewBIQYad79KL
mBe3pL6-ADRdX2C__7vE-2y
}

sprite $image298 [150x120/16z] {
pPU9agF03WIvkYLL5VR_V-qx1C7WOOcmjzV6sgFZdenMJWBTQrDywhvkHY9i-48g86h_RLGa0Z5ztLr5HC37Rw92B0Dypnf7ZsqGvIkO-Wh4Rl0DbIY1-3Mm
uUhb8OvpRIK6IwRZN5Y9liG9r8MLc9BfV00RlcTv3vNeFrk3E8Mwh1BbdEcgIcGDdX-WzfSATQxNXJMuh1BJONaDUbsml4yzXDOQD71DbzQWNQ_s6ZHKuZgX
sYlHlhpsXr1x3HegSS7o6YhHMeFBAZ6TCrrLYVOQlE5LTJ2qGJMygZRKu0Azpfckh0JOWFMsXn2eZt55UO7gY7Lr9P9A0kARz4egXftfTT5329HFPa4nFiKr
FKNLEVLTUe4IA5AIFbY9uGdR5oeuBgx4aGhLQl23QvoUeVAk1Ydn-aea5PEA1YaPBwz4KjM9skd5mCMLI2gp2MaxHT6jEY-k12cP8YYuEIbqnT6cL_khQb9n
9gFcxw1K_UDwbVv89PyC37arK3bv0BXABwPG4mIOCt6O1w8Qhwe4VoeQY-r8lTXF5kH5bTXJcPEmr8igXI8_gzU1QhLTmQWMLCvAzVbAR5IhxK1Ka9B4f88P
FgxNHhNQBZWaIdGdgMaonwVrEjgkj9rUC_4g0qGczaUea9KusBxeXOXgdZZwt2iXA0AmSH7wO3kXujoGF_F5aIWaG58CYuFji5Xma70-cRrPBqWh5KL5hMRG
mVPmac6BNlRkBmvGUoe6pGn_jXtkrOoKWc_LYz83bO9kEBCTIilU_CK1wP4ARjLFRHVSrvZklpZu9gQDogVgb4vjPmH9gKpGMxuuG1sfXbA2Qzljt7OwAodv
l_xYeAGZLTSDa2GA8V7CTlfTM72IYW7YtotlIDNr9j4TaivjhxglfL-_E8na-_BEgRfkX8-hNcUsrveRjDGBtUHWQrGfdLFb3AKWgOwsEtE3DqTwLK6fcbgV
sL3EELNEo5Klvnzjlzz8QTLhdbSgYMXVtZbLDxX412JfsFOISsvGTr4AtwX4D3ETKwLU6AjH4d_RJlDSiPKKoiR2dVne5-gSgkl7ajBhO3lzZlHgJaYVmxLH
YKIpKETKUL-IjBCTGLAqMvR1RZScrPtSKKbiNTuvLMA592wt_6ExIbso5JUHCizZethQUaglK-LCKAa6IVksgwPNLa3AhSHlAX5jopkdokbBAGiLCQ-s-trU
DeZqwiQWR7NhoLz7K0rKgNrehPUjRTSjgUQxoELGhOzKfD2ml1EgWru2kVvGr4fopl-ft6DILJvGYJXTNYjLJg5irOkIb28PKYX7zOLgX1wf29mpjLDrlPLY
iL5fyMf6UdK3LQeuGV6W5qaSXNg9IabrpZKP-KZ5kxQZMbBvz41ruABKJ7MCAXUiLI_3TfHbWrv4vmCLWPFbjLFbLCwmtI8Twx6_AqscZMhF1UejL5tlTQh1
bMgVpRhTbOeBeJrLhf7IUwYogXMFLFEyKd5Qg2PN3Ccw7-cDLAdN0zNjFekoAewH6omkJ1H8V8wgwoj5TsnKDv6aEFriSAHAIJ1t_2NLJ2AfdfmXyejZtU3z
FZDdYiNsvQwgBLHcWR-WcbKAree-pLLgh5IQRrfBpkskfksk8jmio5UPlFz_kwbdg8wlX3b99N2xgp7zNwZ2W-HhK36kFyM6xgNfJH8S6rMUu7fNEwgGo5UO
MBg_do5KYk4trRJQ_aF5LwXcMTyrpLYASqUL1x2xA-Arkvhds7RMT5y7AkxkAhaey4aeJCr8YUK_LDp-nLg6d3oUObBj_jMCSQJ2MeQVUR86_t0Az4WbKGY-
H3LZR0OvLe9yqEltDDQWNIznPTnFGmrQPeBqG2MI272PXXgqJQKUgS2e5infh46xNdlnuTL1aaqrQA-4VgWqtsw29LPp3ThrsgZkz_kD4IIRQj0-VQLMAiwt
_r7DgNnx3TehiNdrFwvP4UG7Ql3aAo4IQnO2FAd1PwTG-h7fG3MpeGQDbS3A1P276bmqevC0cL3SBy-7xiAPTb-gXnfSE7NZEjJWoXbinJhKuDeP8xaEDRXw
2aWUQd3vz1NC6dpP3F7No_il
}

