sprite $image425 [231x47/16z] {
xPf7UiGW34P5LO7xNpTDTXfbppz-krYhXqhc4z1lKgbyEABMFb3Ej21NFXrtTApGXCJ2XoFMVjCrZQaKFXrj0_yJMY0jMw-ublP1kwbO5IkteyezS9rCDv7F
fpawYWUwg7myvgcKoKT1ArcRotlP1WP9fYs-ArOoPHN8I9sfF47lxemWoRJD2KISNmQwZlM2KxEhR7dLHiRGj6qm9CPeJTrMT2gCqPgoFOHIGJJt9SqWchRN
5FG9vAUWV1YFvgDf49fFDZqiB_9_4_vN47y4Uq7P7UWscb6MbxOTj85G5bwxe18LXjuUo7MJabvW5vI0rhIw7azGjs6oE81UNcBhRe6WqgdZvokPKEbiEfMd
YmHpYsioFhX8Y7VoAfUa3gyFK5RlZfcgtNzreLy484zdj7HFn1SpdUa_cV4y2ut4mbYlsIII0oYgbwdMFvBl
}

