sprite $image120 [329x233/16z] {
xDg5SSK044D1ypcN_llDS9ZrqRiblD6mXli20000000000000000000000000C2y_SVwVyl_pT-PJjznwKDOT0nPRw6ZacktaZe6IkeOA7bb7PNSkfNKCL3o
cZegMNrOcuuXguuXstLrL7BlLl9QEYev1Zeg6UYePA2ZajcEIeuF_G9rqOusERthI8KwKg6ELAWZ5Uf8dRsZadEWevAfZahEdQ3aqj-ZGXsfK4Sgr94AtQJO
GntPGntPmnsLpD_DbAp7N-aFAJa-iMCcsgd3C1Hi6zkIxfNv_yzzn2or2o5cUmqbqyrdki-HmeAyBFnNuHNOPnqovbjPyQ4AcVBDhF0n8LVyGI5Nccka_oL-
B-HNTlujhYtgvrX37kcjuRmDdmZvjZ6TTvJyV8EGJSjRGaOX9LfAAGeXuyTt3Dcsl2NaaCWqWEDx2y7UTYBRbjUN749ASO1itoKR8jUGCorzTY9ba12mXfnh
wPT2QaefH5WCyMdNI13L2UKZWTTBwJVVQd_rX3Gjc9csa8QIJc7Z4GOrZ2X9G5kEFmABJVdSa3etYm3AEn0mbAAyWEjon_Af8S47WmLlkF-OaVsv_j22YP3l
Xlj4IO5eKXMIIQ0qf6GAIKOAHPEAYbBKkczi3ETafyE4Mn1-jcHAQY842Kr94iQinPN8DdOqCKte3zaLhTz1bpsM9GHWfX05QMgwnK0HLIWffQJQU5HsXmJx
mFAdhpzbFnqXOIsN7OuKLvXp1PZ1WFsxfQJq1uOKsw8xp4pGkCBEwHwHydKskb5AGRSKjpiTPJAE80uLGHTpk-F-g939LRafP826uimgXnAoScN2MhUPTYCs
DAHbtHjolpRaS2QaaRxPuKx1X9FMgNMx4QXNK9RtWCUtt1SoR2eiuCHXA25_k19jg1qd7MbMsvoM-wob7_Yl8SDj8LrOM6JBQJukXqoR2WQSkbt8nlbWKowU
EjAQhxJ4mcl5z8zx9p8yOBMrjYWXNoqcPaB6Dbf_oDjNE-kPnsr-HXt9BHDVv3V7xAcfTwzsSTAwQrUx3PcwGheUoPj9J0_GUGy-apDM8SF4QdiXDwljBAwP
oEp5DQjzT9nqf8KOkQyOO-mDQTnp8QHpXvMGzpEv15zp8TsT6F6S3o5ppZ-S71sBsqMhlgwEwo10hq8Emu1zoErHk0DUlfyvEmvj_HkrJJyi8H-Ar-1Z9kJG
433Xf7Nxa2rJRXSoX35b3D-FR11YIY66a58CjhYGBM4cfAO6GN4jlSw-NJom3rdEQePo41RGy6eX5ypfDR9SQ3l8xfWCkOQqBSmzb2zzRiZXjKBIxu3_CUIp
yJ_BLnrIywsin3gavLjPqSTCv8ey8UGQyZDTGXw2zc0F0y-0fs3urnuS4000G300qp-r6F1jjHK000000000000000000000000000000000G0C
}

sprite $image120 [165x117/16z] {
xC610000082W_QaNgG800000cBdwq7OJ1e8mV2X2sjbPv_tVDa8BX1RtejzjpgsVAvNLnU75miCzRCJtq_YmKRuVugD6V3zNFcIiMzcxiMfb3wzQfHlhLhgn
UcK0wbQwiNfbWDIXJ3SUnygL0LAzSd1ZDSgcTgChQpUwyinOkJAwiMQb6ojNHhoKVAv5sS3uY_IUYBOWEwiwdP2yFtigqfwE1TbIFncf9NfdZBECteHigD_i
2AMkWYAd46Z9s2p8NpgvDWO9aeOOCI7v4wItONAF3CDr95OfrC-OnggtFfoRfri0KP4hIAnJFoyih7ldmqazwHpfSRM-zAox4acIQBv8b9IGBtcA7P5vyhYm
_Xhdhz6Nzpgp8A4oql8P8dAA12G7cPSi2yXBF2ZA5v6N8fL4NsXcyihJtLAdH9Ia2gO5mUPhyA-j5bCV-bp0EvvrvcuY8ozZINXOibdgAr75obJmNUzrpcd9
ziZ1BkCf2gULyk9-fMaLP78v7FcgaxUEtOxCEUX_go3NZsJnAgXStgU-L7ropkXVkW7bXcWu88sS7ybnfSrYMUAFfDcVl9WANGP7qf5M4eppicfqG_HM_9VH
uWuPmf3FGm27lFBinTUmhB1UYOnjWAMkWwga55DAotyH1-w3FXIx7H9ImhBanYeJEbxMMKdqH6ag-bZjXBmhFLjdqvVV7dlmG4Pj2h8tVYIp6r-zhtP2LbrV
a4syKNekUKUGzczxS4m00020CCZ-gGsn5rW0000000001m
}

