sprite $image383 [141x117/16z] {
xTiBScih3WNGBH2Wtvt_TBkCVUDK51oVHvoJxdwCO1NQAY5_yFnfmlWbfugPZV8RA6MOgQfPfxCfrDJqUapRkHOMqxTZ9lNq2jtFUT6XVgVSENfATDx2aZXy
GZidordHIHKwCphg2yozpUddCE7s1KVunp3kxbzeeluWvZ77uy_FOjOSYpz_VXxZPWlA6PXyEUQJSWx6tTArd8XnjqGv4UDczmgTZd6tsSw_1EEJycimK_2_
SJF_OeZfrsI6rOH_1wQAsRS_1Eq89kyJPfrEm-HzmhITYQbY6pl4DgQavJFj46TWgEkaxA-V-nXEbBH-RcBYIKnUFhyxEkOipmPONVMbwwSveNayTJCQBru_
pGkADej762b_CMvVSShcpLG1IJp0k3QwOiBzeSR_y0uc1XK1caeiCNPj5eqkuGyu5dlF3VEXGu3UmHPBZ9f9aQYtVDcA4diturJ46Mq08XOhZAgf1GCwx5rq
yiR7km4s7T81BIHhZAf71IbHhjMxVOBt0znS25f1fl408mGbLBjpqiQtXs5K1PehQqLHQkQnmBXgLu3bbYzBb5sCzpO3FAD32d2iC56ANF02TFiRdG_skZkR
bD07e3QgqYDC1Sn65s2qQxxC8esEpQbjjNT0QpDBc1JWvdh106gBERRzX9ZTXEB63p3jWa5rvGj62fl7Ap0-I2kALB5bD_cjZbB4syJN5s7YEZE1_l5cukrc
c6ST1H0VHGlAIp3pQ2qvmE6gzymKCxvWHczcByMuQsfjDtsF8ULX0aYxkEfBCU4TDI9Lw8RX6U3cWsOtDT5NOjn3nIDLw6-0UNQJD3K6BgxuFamHV_0WpyEm
ZLb70QbLR0OuRymkjLl2f0hTC0NiGdCSZ256MwsTDsOdW3HZCkKs3dIe3c0ms0Te0vCsPZF2AFIXLlUmf9iX1Odp70SYCZR6GTgOpOb2qMDe-cWwO_pjFICw
0qooSJDvOtQ6EOe06l4rHiOCy8pERe3pnkoAvg2AOctSYsMcdsTcU4CLO9Xs_Ip0vLY5tc_Cvj51804rOEZ3Idame3g60C8atf1lfltpBzHjZciq1JSKGOyL
v_wUgQPqUyy8vmdVow5s_e09lnKBemr_a6EF3ipQQ9C6qi_UCsRQwEbsJfZBCJG3AyOznJawxYOytpCqRe-n-jb3p8IVQ-S5naMcftctM5sEHwrcvHfW7_NJ
RhBquSYodPSO3ojiQ0oCoBMwPyQiyGNJM7s1IH_9hjfvhN5JHQlea5ohEqRhy8cvkBYidgXgsWxy-Y9pmhatHAy-DDNgtareBcME0nwsnAYPr7LObfh9kITP
h0FDSwtShLtVCwot1pbxB30fEiiIhMiL0d13enxkvl6UCvCrkmcuQBHWNQPbTAZRqvom9WELo3r6qNSQk_KTpG2FeKPVOLHD-K2bSgqYdBYJUWo0_UC9qpaE
m2vbZNaO7PRdQ-LQgDe5KwbuvbYxZeEXiiOyZaxJ0vpUVM86MdZcYCv5WKR6FFcHR3aIdPWO0dXYCeUU2F33w5HvFZhkqT44CcQRHwhLVCyiCJawUstkMi3W
3ZKtpXkMDvHu2hDkyqFH0Kg7Sh72dzMg-LEOzOGeuq1qhCk0COIbrwpn8vZzw4Gek43GEZHf3c2Mu-fOcmy2NJ6pnuvYyhtiJ0ZtKSR4Y6ZLY8EO_DNXLdJS
z88HGaNhuoZccSTVFJ8XH1e6Ia7lP8SnAIoRqGaXGJFqtZmEON9FxqSdp9a6UeNg0SoHdoYK8nF2Aj0P0yEUnTZ32krEYCuG06E5sVo-cmv49ymk66RO0lDi
EtzJctT15unMDHQOOrzqxqq8gnSFWRfbpBgTNnKTls3cCp2EB77hi_UuQCAaIqnkvvT69rmA5fW3OTcR4FQcQRKdJFYHTlxE2L7BHupRngypDYV4gFBU4hPV
eN--VeQxtod-WZ-K75m_xnNQRkVz2N6lq7OxxxVvyR2yS4ByRMVPR-Vz2N6idLyy8HOLEYawkPtFYuufd_GFlet7ziidH0xBMT7PR-Vz2R7UpCwBZgKlkKw8
pWdj_BZDSpkV5vsqcPrPgxrs_Wy
}

