sprite $image227 [236x172/16z] {
vDM5OGD030D0lrdx3zo6cJdApI2GDt2Koa_GnaGAlr5OS27dM6iJOePjDOIK5lQ4C1g9WvoxgDjQXOerJgZ1zJEdkP08NC2uYxgjbEjdJil1z3F4jNLSgutj
PzZ-PnHkbF9b4dTmfg96iTHM-vzQSq6I5WM2y2g827Z_w-vs1F-yYc0-pAL_hGDCcqEb-S3VjSL5GDl7wyo-mhD__lewm-cdqjQ1n-VlwhW-rn1Q4hhuKDiO
hfoIVy0Ygm_DFRDxdCuegxy-m11YjNJFINlRg0jQdafRD_oOeMHlu3_0DgxxwFhvVFutnp9A-Nsvko4qY8xpp4SgvxaFBt9ubix4yopfE8uNsh8DLux-hiL3
0qfv8QsJppExOTgkpz0Pzq9tV4ugbhOaxJr0PuwwlZ_GXl6aVtUY1elqDRcSnGytEExMEbFEaWypbRQ74spZpNJ67T-9QXSvtZ7jyUB1wamFRGa2JswZCw4O
f4tQPZ-wGD7TIsTyDaHjJdhHThq3RNdnO7KccqFjq7PMsfklCxibAgOjjurtA1vymKWrs-Wc4PNhJ38w0nTvGjgRgZEBqHau4zBUzEBX8bAJzeHB0iqGSgPs
T8RHDirFUzmG-azNaO0B0FEtqvxl_LbV7wnr2kkketshRNInlovB4CoxO1lrj8S9uitnGVC-Jjk3l2XrsxYnLv73fp0-YOYFRXiTvt_z-IlcVRonGlx4Z-eC
jsDB4Coxs5ZXvnpMcOvP7ZVlUcEbqzPVuO7lqNPyaGC8mhfjTF7YFseJp3jih0R7wpfJfsNYk7dN6wjTf6qOkArecZXetlN6Qbywr02sqG_TLdHC73Bl_BSi
KQF3rDXwnGDzztSgUs3U9PtnGzG05WUy-tFRzGFphkXCM0Qf4LVs3A71r999PTy-zoM8DoFxUe4QOK6xbLfhoYfxVbN36ok7PDAE1vurzTyorZwGjCSRAwYO
6rIo85G4nlNJjCSQAzmxhCoXNAseFQZiGTe3DoEWJrfX84vNAm90Mt9L4zkVoj3rvLXpoHcW1M-Pdkjldxi7DoFGoBFjF7Fke2LhQedDqrvJqYpI8qhVCzQ7
grXp5cWBAdjxLLE7teoa239MTos_OFt_QBlnj0SCeVcx2Aizr8eLeUszPIAfxEsvmviHi1Px1aWhLe0MhAcXBR2DHcU8pbk6v-xw6gm4BFkECC6qPtNcz_-p
MIhpCPoXdS4AqB8BuPxhxvmFkyAC2s2uML-35QFbjX6cFQipl5490Ad1Ij2YDQLfBtkxXVtnWE66g7siN7-AdlPumHqMpd1xg1OhHzil9NZQCrl8c-q8rXTW
1MZPLMJwBUtj1HNS3aYnML-2bQFLqnucggqMYSvmh3FJNhMD6Qole3CCAqVRMLEWnw02b7I6OvsVziPrfW2T6SSwF-qDtxIv17G6O5Lfsr_Jr5bqgZCBr1cE
bQC5Qzgxl2XPq1cAb6FLqnxhH7L3M4uTgvxsBboIXwREP72e4bRTDYxjJdH8PtP2L1shJjl1hEhjQW13g6FLqnv_SAupdAWSgvxs-er9YFCCeOvLk2Gm3_x2
vKtneEcCZbLFUzR9njMaUxruqB7gjj4wMM_SbLuyw5Zrj6S_nWh6NGd5msoi_9B0F7ZpkdMYpd2iEcq_tp3WMp9SSC_1gjj6dmrHpIWwmoTcC9B-r0S7LyP2
yK0c_-FJLBIfb0G-LHMA1pOrbsnvAjeXeaAT6P_ueN5l04kWnbdhUwnVTNisMflL1WtXzVKrjUwM9gCrTQDMSFCfmVvOo7cw08LtwqmrvcOMKN-uRzIA1pwV
FOcTLLjavXjTKsVI99qnCvUsDku9nGCVqslQsRCm1wFj7ZRdragSkJhJd_KDjArJZgDGfECwWyPDfsqffU9uZyxCfYt0d5AUfJDqTDkeZQupQDvh6wVeZ24g
c0bf3yw_pTcnKG0n50FH_53_zK9s8O37R_arMBFI-eGpNq7z_O6rTu4pFmjg7zjpplmmgA0s7WVrd3EUFvV4m_6ThpqJr8FdozRUUn_t2w6lZPupVMnz8NoF
hRsUCs3jOV7mdg-DaZDzRB5uUA-lZG_dZ5rxNZpqiVMSQTOU50zzRNouU0ZNtWN1_M_vGyL3lFOSP_hQw3ZJhpt7cJwsJZpqjT5nfe-j4mzzRNISwMkZ4mzz
R9ruwDUU4mzzR9buw6lZM27irzuOP_grDrO8-zguJZpmJu8nplIrSKmyz6jlZ3DzRCSuqzV6CV7GntQCCtrj7EDCl_R6n4CVsp7Ez6jlJ3pq_1aJ3_tQ6-DC
l_R6n4DV6yS4Tn_RCSxqQszCFFIrSQmGzhMn2Ued
}

sprite $image227 [118x86/16z] {
lPY9cfmm38Cda42icFT_tPOzF2Z5NJCRHhsl4VYFv7nzlAgvhkdnPgL5_ggyrxG8TbT8Vf_dN25VmZgzntDQ8Ky1IteBK0W9z-FDdvuirFbkeApxyQO5J9J6
lAIxqi9JpSA--UxXGWgTBC9xQrhuzndl-BJmPy_r9hm_y2i3yVf0qxTRfhCz4AyFReQgJFUKP74EQQhQH9hQYiqLWqhI_wXbzzobhNWFc7yzN3wTkQdz2HJs
_WwC8McPHEdJczPfJ8hyUQNrSxZiktWXAxzAYprCK_bNCBo1aepMtvgUQO6m6A-VjJZGpnyPA8lnfjVnveFdX_ypad1C2QzRal7RNrhS3pl7c-cw7CER5lH_
RrftPfccxwkroSehSCMXL-4Zdwl0QLmIJNAX8y1hen-kmxyuZSi2pihBmSllmCD8Xy6wZUkN5wgWn-kcvL13ykmwYoJpzyiBKfW7puDxh1YQfZPOmXieBwD4
Vv7-Al-1FNC5hx9K1CUd4492vKL7jfoCfPyM57HSkUlwncLOKzLsibodaoC0_51j_1jTut9Q6bFwKf9UQAr1EcdZDk9LnaznaXQ3xxb2jzssy-Ks0lgkWps5
QJvk1XJ-i_v5jsrtFNbTgFHuXV7QOEtknclFLD01t3vTptmfDATuPJvcZDNgutmbO_SqL_Prxd_4svuYGz5dOw8XaAUvEhPy_pl3snQhFwfRPmWxK78bN__-
PxmDBxsBSu6b5sLN7o_rPb-Iy7U0vyckxElV_rGFlFkTGZk0qkAw-dWfHOSA57y7S5eyLz-NGrCp7L1QOcvQN5VVbpinqG4be5vQGgud9KbjP2cromBlW2uj
SLU_9Es0xbQV1mnIA2q4DE0QmMi7T4bViGsa9Upgxi3Ib2uBKo0jBDsWLsoXW88kUw6qiEUcQMsNV5kpovKfa1QJwhRLz7dT2VcQgaqtbXP-KSmMWqk-iDQ8
f8KzMo4e4LlU-Q6qy71rJJIZjLrytLRcALbQOiEL3irrlD1TYATbGsR7E5uMW7XQbeUZ9OIN5KyBwtMy5zFYQvRmcCD0MmVqEbuY6KjBx3_sKWHl7EZq26gg
0Rm3W5x56wi_BO-BAl_76m2wKVq5zTCE3DHVNF6IV34jlqoHnkelhj0Er73zlO8tu1fCouWKQIWje_6gSraO8Ny7we2qN2z93QHbF5uTc9PuIUh0jCHte0RI
CXwlqjMQT2DUTT9oBrxTFUDf6LIIUYDGVmTIMjwZZ4QNXNTfaTU7-mS
}

