sprite $image78 [110x80/16z] {
lPPjpl8w34Gdt_4ux7-x5xcHIaCVSnN1UtwJ7iYCJR53x2tW7n6ga5BmJoX24I5xmiz9dHI3R14_9RRfchuQy3D24Se5IiQFoAlhX_75paNsk_X2FLqhb1A-
tde7Ilvow-dmnVXYetJvG1VMyAKrbH7mWT0fvIkjPmQ23z0fxFaBQuePURY8sSvfs6-zsPALeNShIuwLLvhPbcMsr_ffQt7-N8d8yskqPDzeseoj-9ATVh5r
0342GVXYimzEsxBCTdUzsJBAU99GhpQ4nelDYSy9RB4LfFuaebc41vG8X3vj9vGQTdUzsHXXPChBiAic84sRjypyrh_RjCOGKjFPaWar0dsn_T_umXdOOXEE
CPHAuMcRsTKRcyKNDdQzsVX42mf5hZO1yhljypJajnFaEG7rIKBe8ZbMoidLjXIiPwVrLzWApmcOD8w7lZxlOcEhTFxQdJzd5YleOMifvvnIJfqbrTVHl-HM
WCp5LuFV-jE6A3GRntWy6MFfP0C2Jri6a8HhV6xhUJ2wrNHsifMSIx-qXFQ5gZP0Nezqlas34rYRIBMap9PXbFEtaJq2A7fCmO6K8zpxDxFmtdhsDLGaLeJQ
MW4QU-iyrqKTmeQL8iQop6RhVHkia_KnniYef9gi1Ojro9qjthwPwVrGveEIhKBMII3bd83EXCoZGgX3PrNovSZzSuVgtQeQ4ytsn8n4hJ3waPl9iWxAjEam
7fhi26M5-dZe4yeVs5trmOH46Tfh4rKnMmVG1iynw9SZyeQEXzd-z341GNHkPQ4EgLr44WgJrMFoCcy9Y5HPuTDbDiUd9QdAjCsNBr9qg0H4ohkDTkJk4Yys
vOsFbijXgo7666nrrz84o3SsYvplJtaiDYU-PIlRUua0wTPs7zXgC-ZOf4-44OK1KNpR6TXgytrcepuPGzKcG1FGwDlEm5QR5z_P4kdMoLeQ6n25hiqkqR4P
zDyKLAoJce3OwTbeBizcyCxMyfE8K8K9XMG0K2usn-NOb7GwsHXjJp82SRMz1-RRnk5xixKowOTDg7MntGNcsrBJ0rvjvwQccCrMUh_Ol4iqnbXi0NsCgyzi
l4C73NsrKVzoFHwLOxMnohZ4nunONgYrB6IpUPTekeRGT5nj2IYNwsJ2PphzItmyUiIJ9EDYYuZ8-k9ZRvyH-YucJ3B7YwsYLZJA6P-Ept09RD4Ld8IgOzhG
DA6ar51unkVY1cQqW0knJnjgQX6P3GZBD3YuboWHApC-YJr14be7phRuFh_rcd7BlBgEr14QGWzemx_EpwslkCVYUt9ye08gY9gBgkFxt7e7Ys_qYDWGL2Ca
8plN-RdrFlc8Jpi2DQ9bWBt_uVC3Ay1dYWxL8G4XmMojeesRw_G3ErllCflF0i3sM2eeGoVSQxqVd_sy798cn93CTlesMkyobnbL4sg0sIu-xhL-PLrc2Isl
DYMTDTK3DeX7VBdtDviEh_MR93aaqR7jj1xmbbb7TcnEwxVY6nHrR1kjzvVPodXtCUCh91cEpMdzVdoERQ_r_Z8RY-qRhVUNsMdRQFt6CbjjrlhVK7MSDgVr
tujlsZPQlpaDPXiRhT-DRsoqVdkPFMsIy8-8VRFr_m4
}

