sprite $image289 [269x210/16z] {
x9fNbjmm30J5ML8hD2VS_xJETZzyq4d3bJ2DEa8ziHeRbjUWhDjb8SgKPbzOox8aTRFlj4MToxlzOdlJVY6hETw5qz7CePoEjyq8gSAn84o7U2naqy4v7TEA
QYo4qr46iH1CHsdsrwn5F1QULlJcTCnMvUPKRsQR_ITh4PpJCKqa5Y8pEuw5SZggFOMrYCV2KmLY8P2EmUqjcuwwsVDf9Ly8sMhuELLEHpE7NZh6SogNZd4i
PDFXOw7-Lgfz86iHZuMdISPYFBCXRc_bTDJDZc8j-KACr01pgfYEPWxHT71EZmTGZmN1jMl7Wg1V3vTHpwE2CgHZOTzKK8PsB7xGTMxlyGkX39NRUwpYQ1cN
4yM2TF4vFLp6oM91kkgSKWNfsdFgwHaBqbLlRqAwukqz0XaB0kqvzK3lzXw3Z0M1zfnwaB4WqBkznq1xJZt8M13etTvZe3sd7cGi2BJdr8EC1O70xxt_6cZF
gGSP2mAzstiCjEVKWum5WVQSUf2n8CXO4BpG_vpi1XaB0hqVrCT0UquzqBkznq1xJZtGdbCFCXO4sdFgCUqvzLZ6WbZ6udzb19hJ-JAi8quivileG9ZFOhuC
wWYWOhACRo2EYlaog2D-B6xxPNJWDJwB--Fs_p8845_5xV7OA-E0jp9BnMuP10XwUzF5VXa42F12PiiW2A1YkWo2oR489QC34p-BA388C4j581a4KrG4aq4m
8HPXPNHWmcSHJGO19gY89eDWmWi99uDWmkqTLaO7plz2AEF-kPppq8wJww4ep72holk_xLyCCN3G28A_8bRsAkcnsICTwKw1-I-JmJEe8wGAH435psJm3kYL
Y661CeJ_AXby08eZR5WWFvV1m4zrTEB7oc30qX5U1LBloS3B_w6E42geZByd0rrGBJcbb7FjvFPA_B9ehs6u8sDrcJRKRisL_WmLVHg67ybe2IYcZYTqI1vy
V1cB2wGGsl1rT8v07OVRCfR2IYRDij53XyLx67ueWn80nK6W8snOf06u8QEccLnx_xhOaXQoPODwqB0OX_ioi30ghTISPhfbWth0i7WDzsbG68Nsr3KuB1iz
M8T0MDoLGVbhajA10ZPGHnmLX65nNqPAkP55szYW8_sHkxSlewrXWVIyvWOPF77tzcLqOX5X9WlVnXDtRr-6_aAOFWK7sJQUjtlxCaIty0SRcKmPZmyBh8oz
4M6xKwfP6W_RlNqPAwiFCL8KHae86UI4nNqPg4CORNp71W6FsxrjniA2CuHrWQrzenYbySpT6qbiXeHyi54-DCeJTs_aJRf5e3WC6zcUAC_RlP6nCZCnYu0E
nqQp9yhZnYcIkZL2-CH6CJFqCRityfhIz7vDdNQ8BXnim4GnC_IPk_Ux4YyG8DWgREuRrIgD9uR5g_8Md8_NR5YfyQ2mm9K2TM1q21GBdvR6WtPlN2bKFkcm
RSWnDIh8U5XOa2wW3jV6zozXeEJzltpKGVtTvV-03iS6xsE33wNHGKRS5ybGHUDVR8M8QyDfb7oOhey9Yx4IRzdeC6sOZS9-X3vbd6PYH0x5OKnOsVrI_3w9
FavnvmOTPpQmKTZjaoVitbEVGs9vlkAg3JahZOfdrmUCqyBKM-lpnGdek6v33aUKXg4H_w2UUaapfV6Y0ui3RM2ZhBzY38q6Ca8Vr2SgQQM23iy6biQnJpAS
JwA51P9aTW4wJ1jEQTWHcc493HOMo2Gz8GsBGtJ6AGqxGhyyWumukpVoOab7YgZgDHlwnLQDE6jNhDqRgTgJGIQmyJ4s-1YXAAE3Z3YxDnQ6bcJINHjO6e9c
5Xgy91zgd295EG5WmsyKJ4q16HLaH1gdoDYrfrisi4_43eqABoP56gV8IxGctuRVA2Y0GKO16P5U94CctKK6GgODBq8nGGkqIQImGB9gJWwysxxaGsbiGmDa
P90HAIoGgkBAoBApeJDEdu2CZczfYZHEaOOoaAAgx9K6of2TZ8eoehtdn9U1DB01fG510JBcBiaCCWBitlTa9Der2fG6X0RAQCl13sG4USy9qY103RASbuRi
PSYQ692V52aia8gZrMuK8OBKk2IZp3O9P4GPfqXHNBhi-SfsdnWorf-PRwkFD4wHfDhJ6VKh1Rm-uRsCEI-ozMcSI661JAAK43j3iJHi6RnqII_snzR2xDxs
sKJIAGLAmv4Xyq_gMbPGGu720Xa9neaDxL83-WHb2BMDHmOPmS82PskxL1f2T29Z-OdqZTqABkZVFwZx2Ke9S0SAzib-dehAPbJdpYZZ_lFU_qneQ3gdgig9
3Fug365g9UVvRW5yS45HTcyRmat3HbIXJr064R7m35psJHbqSvpUfq2V-15goy0NdH1QYR9xsxn5DT_e4vJXN2fj23PEaQxQB_U9BKDKFozLj2FIEBNdYLpj
4ri6gxRSxUib8CpkRJFofLMZRK83P2XFmp2MRjtD30cmUxiKlRYIYos3bv9-LJhdHbX4B0snPMpdtzJkoi2mY5uQF2Seo83vbplv1Dcz_TBewOmECknbUIpa
4c7tzicgcgyaACgOx0-gEFYxTmZemXfQzpA4cSdkxwdVa45r768moVa9fHnbbC5c_1mTpkuTXgeg-QeCMRh4BWn_p4OSfyX8gloxCjmUVpUo21iMU5xh5sKi
NTAkl1iTYRHx-nEbdWGehJAO6pJ9jUYmTk-0D5Kj_cXTkuG9mlDgT0GD2sJigkBOw2hVXI7Eu-b7XxTxnmfHTwImCYs5uJwUVdJ0xXsN5tkr8OiCbTzwFE5m
3xltGssKfKl4UppFemF6QMWRf2erMP0otTWKyN1lxzvXKzJUDx8A-IfynYKwOFSEJbLLpaPXqAqknyCzZDFe936Ae-hDcwhYc8MR8eLdRAegRPUUmd_9IZ3r
0BltdNi3I2_VBhXDmv_BrESNrbijfRRw7lvinlpbG_N6plnG_Wi
}

sprite $image289 [135x105/16z] {
nDM7SS0m34DH5pM2sd_TLAPtM0mmmR_pexNbx-ZzsDJRcnciYYkAmUw6KOGHvu358FioHmViUR2sAr1KWxsQXaWPi0_3E4KeOWeYHyCN5K54W-9zI56WK10v
Ekpd8PV8tknTXOB85oW88Wb7IX19HS4JuL4eY1Gk8eW8K114YEUS6gml_7Fpyob0yNwOqtKeOl0P6IeK4H4PKXJpMaOPIr1SopZw8XGnP__SgoBuZ9KeOguw
qdSPOXGn5wE8-N-ZmFniBaOHSp6AcBCe-2FbCqeQYfXhKRpFo7_EYOo4vvp8I7ZEYOoC8-KpzhOE1P-HYkBza7ka5pDEJuXWCe254No6EzOTAP-12o6tjPW1
bk8m34DBnquIMqxlVzjTOACMOEdaJUPVeFz9gijZ88hOubJ3pNwvZstRJjEWoFoNb5bivsdSiT5HpDOO5p77L0sX1fiPa9YhCIZY8DCrYCqS1TcsXkze0015
vlL1ZS0tDD1nDpOpJsB7FsXq0rpvC177ZycVDJmdrLICrTYCKJnJlvR_Qm2eAZSqsJwHoNs4oNi7QfYgYlv5HBCp49ie0K-NvPC6W2IIghdLeYA97XIPC8go
BXyGTy14YyDl51KrUCSOnVnHF6kKP4wgYlh1Oy8eN3yfK0FH0k23aoI74_oKp55yreXeVuc3HyRkyQkZeCOTN4suJ9KoHoECe_XiqIBWLuuUzJZJtne5MMj4
jFvu78h9abZBRuxYigvhSlGw0lyym5hgJpNgUXf3SS1ntCMJHzdZc7ovoQL4Ym30tEcnrxB7WN72qwb4Ghj1aOD7qAFmfVsLKQZ7pPSYVeNFPosc_PREkzn4
BE0EYhnuxBMatihqKQpLWUWYJnvxBM0hungUblDf9b7D5WsEAmSFve2kKVkNPVBbljZLGaJKMkmUNQFdq5lXEEQCWjGgUaCaHwD7FCR1Lap5g37lSdz54ls7
f1SF2c3Ng2CQwR9yXuox1JsuqsCS36NNc38AOYxwu17-74TlPLY3d_DpOA8793Tw75hPDKh_s0-CObn3fTxVss0SjrbG8mdVbDFBFG1wAGIDSJngm1r5-aVb
z7C-X8CQh8Lnl6WKKJ5gd5pk4Mhe4-BFSTmqMlEQH2NtZ6QCWgIMtiRnh85cIKHeuLD6GTPMvNqSR0MjkGUoQieLr1YwtEFZK2aDZnhmbxywVCueIDfUMj7x
3UiQhO6FfOMV_CORvTBiRIlK29VaRlsFiCx9vHwcl8wqTet-YsKjDv4ZiqQnZzJVl2jTe-_-gpw9F8r2bv-IjooF6eaQPI5g3o8dVzcCSq6eF6h4NGCu9dt9
Huzfeo1VcxtLY2ZBpjD4NZ_d4sgfyg8H6orsX1FPB_SywbRaOQ8ER2uBUPt8y-MUxo4rF92MLpWHSuvYiaSLYY3-jtrEn06JPJwf8Od8FOophAM2evZCQisp
YcZvpa5KYav7Qi0jdqlCvmy
}

