sprite $image399 [177x158/16z] {
r9k9RYGh34NPmTUG___S9p2TCMbwrgPUXTctqf5rStr4PSoRZYl5cUzpR2A0alqkl850H0GAtmBN5u3aeFXla0R1bGFacqSv4cWve6XldOOLzzvHTXcWpG6A
kscLqOi397lJAdk9JF7-uLqFYhzfbUsFLDnDg-nibC-dOQsukrNPWIWV3U-ze-nUX_UE5MSJc3NnpQCS2CJybyZNRsitf9TvWtpFYYjC9C12VFiebzenmV-6
NFoLm1qJl23Vj-84U1tolQCim1hvvXKdm2eNzuwo0DSK1-Mzewo1emdyfYXJj8U1kK_OU4xqFQ8CcR1dBt5MKRxdjlPWhiKuzYOZgo7VTLkxqeaf3-2E_vPS
r7JI9GGkT613HBFY_W4PtCfHbn3aL60CiadyRr46rzeukmjSGe0jqxzK7DVMWGd9ddS92iZ6iNT_7MLqt0uirddI9GIk3c0JA_vuMmjkwxYjGYhP7WBMoAbN
ScAR_hZYm3BUYKk4vYzmYOe1R4pvmstzYSi_nkslSGboiGENFsbbVEBYiojgyyTTGeRC6C36yRxYVfq6-NNprxb4CeMCvRIFyg_JKEiPO5d63vTGT9LGZELW
OjtdudKQf2i4-9HBOBg4WneokGuSE85_igt1iyeOIphgiGoJu4Nj4XEv363xGZnVXrS17tI9l7E9R0AxdNW2ByEhWG-xX5rTOegdDRaOpq_8kofRUQizx18G
bt2ET0IyoMGCqzEsVl0gt9NNN-8IziabOYd6z92lGwwRD6XSK77_aqlKFk5a_2gUAWqRN2RYSouHMAsvdKkG7y1UR-jjU9iSnfKkWOTBa0xB03QPFyDIdwki
DUGOGYe0jyCk4OkY0nukeQCSEZ3iPvHr6WINWf7Z-MgNoE8IKMzhi9Fjmlqyfu63sg2r7NK9_-GIuEaIh1PpSHqOEJoYhFSmBQqRsa6NuDKb9Xsyk4HSn9Cw
i76wYOKtpmU6IObsZKkKNxb4xC3sYJSDseJsKTpWZEsmIvJf4d7Z4fJrjkOV4rvvEowySRM3kkjSecYwihg4YAUrA--uwR5KMuqTjQ4_cYzmYIZt4dPnYI0k
iOXdNe07e4DhUH0w6IqkTGbDbnQNKFhpuAskKtxGL0Sd2Icun2Lo49TGKTwvX0RkER2LW-fWwey-wHBOkaHLbrYhImZnr9pSdpDRBOS1NAJNphc4rtJm0xYu
dxi4Y_yGl37McNuYVqHZ77FgCszdNIBhsM5pBv6-kWJNnY0kFxPcQwt7Wv2DSSTT8YykOSKbegeu_k8I6DywLGUpfRLQ1p1QEhOuXaAIbNk9E0A1rIMgsjOq
NS8hbu0nRaJse_OJ7hMM3m6BInHn2Vi0UUaI_DKb-aWJfZjKm7TWbhrnr2LI1pPON89sBf44UFAERSOam2olOsml2T_gQPUWZKkKwHBfbKiqwgju05SYr8za
Z9D4NEWIK5gyTGbdXLUi9tvqu4BWrj2N7aQfrV_P9GejuZc1np05c6lZxZwcwsLgjV5Pbo2ySeayNI8zkOGCaJvcIuZxsBv8k5KGdN89wDIAIvY8tt69rlk0
kBiEJxo0CU2pznB-Lou1SGddLfSGoybZsGcSe_5XT_nUmgzqqoNABrr2W1iPEJRN4OyCr7Ft4W8SVjSbPfJdUvTiv8DkkayRx077td54vhrBbEaIGRRrrYM8
GICCZQRx2AyJt0F0lW3yrILuxnAYnLvSmj43cOT13PzehRLif27g2M2N0H8Gthf449S8AihFBk76atfuMqFel3ZpZiCc6hXONQ9a_fLBsCKbqcUqA9Z9Um8u
35oYJv1QI8ONTYwXjHYBI-0n0Fd1yO6NCleJz3KTt6kNSCjVz5PuHIRK2LNpidt_PxmlYvcJkCId4idTr7I9LJpx4QoWBkhQmkiF_7SDvjKbod29L0ihbo3b
4lnqBz548OmlUhpY4kzCWmRUk4HONCAAIvJL9Hveb7CcRkt0EmwfiWsm1WdJ9L2LU8fBhE8fQA8DJxZY4kyBxmgy8W-Ne6AtBg75Kz1aqciQtk4IKcMlWPzT
mYxYcQDibxZSIsnVq3rSWloxmhi7rb5sXOnxuHAOQhV5PVKY0SZkNMdO0-jR4t69i8ZdaqkilEtBo47uhvapqPaK189mWmTqqRp_wsxSdiFVO6K89khUvlfc
yarroS3g6WQZZ0FRlal47xf4GzxlJVZ-t14REB2bVSSqU9SuB6BjkyIv3GvCjfftH1a1NcJMlxNurINGx18SrmnaVsw7l1HOP87jwBG4IUg4-o_4ZhpMp0jo
ceP5MH-mXBHFvNUNIAqkiSTjVG2_5_8y82y75ecwLpdJBj6smLy3o144OaC_i7nQyQ5BeBN5upoEGRQQqoZh1vQ_nHChxHAxuhD_3HNaO1YnWLqu0yPXz5aY
NU8WxyTe_7wQPlrzZp85FkqIpdGYhzyy07ELmw8Tn0nuR-tqMvVut0GvJJDoz1SSU3-jlKjyYwUrvRLpO3AjO-v4RWFdqjKbzZVHUvfc_jqBd0539XzzRvLZ
HvUWfsd6LMu37wOrwn97ey4FXeqUkiS9y7vQmrKEpaji8C27YEE9pA-odW2Bn6o5TOc33GIOH5o_ohg64s2H6SSDhiG60anKfX574gSDx2klf4iGu66LkLaC
kDqbchmy9QvJ6KY10ZUxH1Smh1Q0g4phMtjuSc3tmaxbvS2bOWvXnLvb6LMP0pjo8JOGuEAx20D_7EcVrXJui2xH0uoQ9In198D_xlgdDG7sY-FM1Z1KhOX0
HIQIR0FJcW1ptjhWBTM0kaYS92uBgK43qxeeUOVxtbvKMsD85aHaJM52isYEJciAJ71Bmrq4UUscA2gIGUGTczQzmBwR_tXLl3xs8ZABhEIv_w9fpO6v3T1Y
KUQSJ5MsAz4Lj_5ftGGcDXpbLQr9H6jTm-R1f5Z6rxXvgMB0t0PKZRBKISB_TncQEquz3qnh0aoZp5vVyR_sXoKeYR8hLSwv3SmdXTKqlyD1vY0BEbQunwOr
W2CmbzU1Pv6m_OAdKqUKNJAj3y1KNbW5B8Wasu0tweGKhzkAqBqMnsqejInnjIYY6x1gIj3fmiqU_SWqolnx_ca3XWCJ6owBE8xC1flP96zWBI8BZb5sWygd
KUPVZ2_f3QnJ7fNtakN3Ctcjg2M96aMY0pUYx1QL_yeBm6L8KyAq9ZzO5sGXyevxqQEorOAz1LYtcnP5Oh5LOXQ9kcYvrWO-hJan_ZwgXLYgRwuADKaeymPS
ylJ0_mHJ_LbggZcuMoL8Y1BN2-NbqvhZjK9tqR1aYo9pUJK7IIpAxeeunyKai-aoRS3P_A14k3hAhdgsBhwJVB4WqtSG9sR3dH47yvtaCo1VuAZ09L5s_RI6
HSSj7s3TZ4f4tbiZ3kPRdkU2prpB9ChkZZW7pgl4_y0bIcHp-7wL7LZa1Qnne9LTFAqvy9GTM7cKtQ-o0uS4XKhCRiFDbmE10IUe8gyaocw9E0wik2FA-BIc
mBWfolYqFWKcyZuiuW09Auco1weyiqUA9qRSuspWqveyO3vFPHvbpuiu4cMFLFc1yl9fVMsK_GC
}

