sprite $image257 [260x258/16z] {
v9XPaiGm24F90aZo_UyxCKvSVOKfNY_vVoMss3_c_tE6neVyi8OuyEC0w9U58wO2IPy48hefo6GPqFuZcqc82i4GzG2z4jmQuPM23KMMXClQS2Q6H6quoFb0
fnXeAyZr9AaXtdqQ8eQugk4qGmb1LKDQ4wwA0VH0CxldarX1E5gL0Ye7brai1w3KfnYYIW7K9B8UcSk1MmzoES3G1nK9KcBqSl2x8sGt1_4wY2qXews32DQv
v1wx7_IQ2yXmzrX_YUNWQhCVK1M4ah0KPEq7n67D1aDcBFABGLeNxfHU2La64k-QU5chWq54n6S0x1I3ughT0ExR0QL1dFrUec3de59GbT1BWXw8jmw6oDkQ
uGcDeQ8CuB9sNAi4nXk7FAmVfqS2cyCQSg_zCB4uhI7-JSRbmLkMGkM03-KWhHzNEU04sRCX7FuGu4IOt2rZuCbYRKhPSIfuSA4buUhO3R0Tg64GZXa3y4LB
GgzxuPmAaX_ljapwqSf0W1iLV40B2qTrWWH_q0SVucmGWKW0_6FlNhUIru4mZZTpU6OcQSlzt-rEsWh85i5Nj0Nx5sZKJ_cj5C9XBJuqc7D9tSl62ci0dncK
wJK5u-uL8vtdVzjWwWKPo5ht6ymCtKl5xcOuoyokMvIv_aKDz3pKJWlap67R1l0fUml7z9_2nzad-IV5ALxTO3VO3NQ3tM0ts0rsWzrWDzWDTeFTu5BYgWa-
opxBRnPpwnZaBUKh6I3_JjTUVmq_PRgMGLYucKUhZJqYHqGxp9-uos5rc5lU9l7Gt2B45AtL38gxAnEBCekfSatQZuYpJWUJ6hE8oTm37RpYAbIDoIuCwFSC
91mA5rN05L1Lp3yEOJM4gmAYfWPLWUaZ3U1PpTIOiPh1yeP0Ze_Fulp3XPcXNLfh6K0L6sar0qbhHqn4IOImda6OKb9NuPGeH1gBceBIxyGgHAGilsQW_pFm
A4YQ-v9JIjwNKbAoUh3qEn49oye6IpJVjgQ3f5-AMecPLZFG3vF_HJ_UYWOupzngRXxcEENcJEcdsuf1xljXwFjSXjvmp9EzCo38FtQvsD8ntOn1HCp_ZhXS
1s9G5L7NHDmz9ccW9hIo0TS4jr8YTY_kwcxqK0FsmCe62KAtJtObIjIkyu-akKSO92PQsq0pyyt92BrZqWV5gEdKgWR4T9_13xUcGOs5Fe_rNeEdt1-a5lI3
tCpvPC1oCqvydl1vwKPh6oWC8kbzAegK249rJAJfPfoewuY9ANMTAASaAamDsMZh1c8UsIyDY90IUyWqbkvcaq7oy92kqsO0Znprc8VD6wYq-7q0Z9cdlqy6
99GwJaAIFZ7eqdmdcuZd9uNS9iXRDg0MNqkMk1c8Xhkn6oXTCU3pxjWmyobPpG1oLyhLW8YI8btV9d9YES-WLndaCbtDmBgxIb8DM5LKHCWKJ7SOU2xvOsIR
txh0TWpOwHu3KNCBE4FzBWC0yR41tCtDTJi6o7gFGRhzkC2iK66M3-EMO4fh6peN4jlqWCuVP03IOd0pJaI8UDjGmSDDY6sQsx81uU5mRE2pdUMg1kmvHr0d
gWgvc2f4vKi6cZEu6LWPnbQnTmQvpht-TUY7yN28T6mZ1Z2O-OK1qPSCnFlYAWfutmmEzITFSzF9WEhCXt0tZzmVHjw80Q4Q87KgtpyN9FTzNyBTOnZwOPWO
XZWPS5q6nQ0mZp8Si163BfcX-xJx3VhQz1PcNtAOHMbBle-Z0TKp8Q3Q4F9mYAqOj1vaeBD1tmUq9kfbg8i_dvyBWqD5r2pwpmpI4niCVMs8UIkewkLm6ClH
W8T3e1d0l1hOAnfKWQ5TNQ5DGU7ZOUnd0o92Z0wOkJM3KUZOoWOI_3Y3sj0FWSL0aSTnE1buDbWkEQmIZ4orb3PWW2mFDIWUeGPLHBZxC0xvxLmGSuDwpi1G
JnBQohb0R4oFCS3O43B2e_JXkVJrq8_ZR414Z6nG06hZC1QQQWI_Q23NzqYTS4fTukyPZCCmzD4FtlV5t1rkUHpxDmFIOX25AiQ-ZzExtLinK8KfVTDWQXZL
BDHGinWFmz60pGnmg5K39w9D691M0qrrC9qNwNjxfB5LDuCmcAYgg7dzIsa6gSPkvW55ZFqWwTYw1bq2z47tYMpzOc20gS5gFhJdI11EDShUUCpBOJpuPWnQ
ZpBm66Q3x1vXC7VpzWWml1cu6rGjprBRCQ37xP66PHqC4NaoC2jZDHWN0t63gLI3GssKhHZem_O7DYu6uvWj797TSnw6sO28R32O1Pf1AzFIsWPukC7oZDdw
iLI3FfTb7SWu663HNa6PuqsiWyHg8kcn1hN1tQAFA3c7vQ4PI9rvpCyK3ajbGTZ8_e2eI_Ns-mQjeGyOpAD43ZTp5S5qHs5cKTfeAJDjoK2W_3s3mspWGYpG
dFi-FBkPGGJBdCqZpo-qBHNGoWP9bkzHOIPcUeI14x6OeFJ3OW3ecy7evXwvzCrW2UiQr4GUTfyutnC8iq39XxulaIS3QmPpGuIxvt8ubLzeZpGRX8geiam6
kMHh1Y9sE29S6XHQso39WmqCK1LOFnNMQWOdX8WR1flS7sWwwvg1UWlGcYXy2bCYg1x3N6a8Osisw5StqCot3LXlnedbdrlLW1G6f5i6wOwUrk3q6eenCV4L
0xbMEaRoz0Rg1kAllfOs6RY8w6J0ek-JUs9ch6dGKSwDu7gt3I9xD0CnpVXw1eMjQj0HKVSz0w94gHceXNuzADIUOO-4otHAaXvZ2I_-zSBCLpOWfDi6wPw8
RoHNutKDBEit31xLXK7tkmRiz0q3eaIjPpOWYt1FbKBgPDCr0z5ZtMdC7TMOcMhFQt1w3ONLyPb1c8XC1g86cAloz4zDL8-onCpfa-ZAS5K3gmQUga5AHDSD
H293MiqWbn95fHa02cr7db8WKxgUfXhHQJXTT5M3Zg8HVDfi07TT3CHppYQJWQME93K3gAW8mpuqK3FNUU8KOJmFLM5OtM2v4xXj89xDKGruCWXj1Wr0eSq0
4IKWYJys43MJUU8CCvg7OWRvLGF-zpqICuj7DfPkNl7WMWKaQWefWQS424gNqJ7zSBYs0JlTPG2OGvWxhY5aCU35GFXO-bzyYfX5fuJdGutNCxX_ZoIdaXoR
FUOeVQUL3TZeji6FjwB1QN_0tBNeGmFuMt6UFwQeRSD0eO1UCSWvwiMoUuH7FduZ3nwHY_gQ1eItFT9KkcPG-jBtKRpUUkJwY-U-x-Cn1aoh6dJ9tRgBhfyB
Tipjs_bIb1nFi3z8Fztp6z1bwIBv0mQBHBiUVnTb4M7XEjO_Oa3SEXbmvFdRh_-GmHITtxQO-8yON9O0FUzL3FR7XTtWnti6Wzs0vOvKfGQL9HM1t9EQoOiO
vBxaOcDVwg6KtalnDhZj01Pz4GEOkQktehYh6Tpy7WD0jcz02mBJdJ4HVwadC81CWTBFH4zWe3IbVzjWDm1FlQ21tXcJOkxrzaYIDjEA1hl1Rk0AlKXMQoK3
a-zENa_XkzaA1flxZge_Qx0Rx0QxmMwm6-m6ky5ki1li1W3-k07cR3S0xDaDuFX70poP0R1STRhYTFNmImEl6MfsDefmjwLvX6EljmvYojwDF5elQd3PFAKu
heEuN0TpBsVm_Vk3_N71rpH8hBQYWQ6rvXw9uL5RVQ_iQnaaZPO3p_9ymRi7nn7XoctqLmqumXl0NpRmG3lyPOCKSHehdi708GytIEz-Py5s3Hn2gNju5lP_
61B5nWpiDFs7Ht52k81WrKqOG9cw7uqZdAuJiQYkPc0GJjqlH1w1r7rI8XRvNGE3C7M_6EAeS4FYDmoipVxt8siArDtC8zo07p5mzuYSStIjjHHCkizBUQv9
61vcC4t-LEhMYX0t5uFc_yet7pKtSHY80y7IJDx_WU_IvSiDpdZDKaAvvjT_mj46Uv36a7uHkbA4nrpwDVFmvnXdaCovVHrmjv1m7HAMv-8Vt1qv25ShXl7U
XWy0-OXK4TEdujzgS9nV3BTEAoZSpztICUVJYW561NJMVvG8yt01nk9K6E_hsVCGl25SHeKOLioq72y3Xk4wAc0SXE3Rk9GfAXE8GKZo91N6uJACfDeJ-5Qk
gS4m4wh8kxdIvgZBNdtGS9OAj-52WDCpBkHPAfHhQN1JIpnBXRXg7O2dYP3NyeD9ujF0snQ47y4_2tw7qjxeo8mlm0SoG2v14i-SN8OarsPaala5k81yeA-y
3YKNNCuIuT0wIfAnm0MpSYDBArU7TeYxSHfxc9h_cK9Kg_8hz-lItCjhC0-M0cc5jWRDMUZLhtDJSg-W0MAm05jiQFb7ezgcdW6gN9FiidMeSWyuPzW1C3Xk
03y7M4C8RDrvia_i9hiSidl36SA8ZHhytgBBPgB5RdcwXZ03XEbH3T4BjwTY7wJ6Uk0zXYsGHeFKNK6SdNY6pzVpkDJifKQrKwKE8DPx-UlvgPko9CCOmWGG
lIb6P-7mgpb1W-03jt8zaoJ36481x6IENFWEaJiQS8C6V3rJmn0I9BBUX9CQGaApS5_rJeFE6spJ88q6dPL3IoZ7kXKI_2oGjI6K5AjMXpMXpUWdQyYtO8jM
dpbr7iZA4CRCTLr1OXE2J5FNF_ovxF-Sy7qleDuOuFeo9JihGxWbr6DbUiVA0GbtQe2c1juKis58pCeG8g66svsfXZkNjVsT_GDwn6jLE5FrsvKOWhP2obvW
zeLbup0NdFaI1bgRGBz-k5-3rZrhVY4Ql1h2dE1VGiTmzHfbrAq0aL0bhUAh4piDOSeaed7BbIV6gCQZsmjwv4snRGYfXb02p6WyVk3DSJRYlWRuJWDqIgBw
ciCOWReCr9txCKWSfyr-3MG0_P90X7nlBubyydqhmCGTdOxLW3gWHtkyOzHM-4lmptqwgCQVCVtN2aG3_i_eFhxh83DcQOKCJx-MlSTlRuh-Pk6BtGwolnla
oaoAj49uKfVqHZtsQv1z3JI4l2w6C4KGOH05ToxfV0twdm3hD1YB8SmbcGssLEtMCkyNr14Qz54DidmPGYdWwQZdOlzDkKb4r6JJAObIVhL22JCBFTBf7eK_
uH706Rkt1fAbZ4ihw2ZCBOXuoB5WLVBLsQkJwwkjXtG_n_PpFADCmp2M0aY7o9JSZUd1SBy6Pe7Hro2UeHZ2hGJJofYlYkHLD83VcglkxNy0p2nbjIjyvMRg
OQvcWTnBA0sPymSQ-4Ti_DoNInd7KiIDheupRnttoQYkGrappM580OOhwA1qwgr3YJm2l9by9sNEZ-SsJF_2JmMFrG-_YFk74iE3Vm
}

sprite $image257 [130x129/16z] {
tDG5ajn038NXDkY1bFkVD-wn0ykygjfl6FKRnqUip4hjeytkcfBBw15vAVKaR7ceodGMHmVEqTgpxCoj8M3rB8YXibpHin7aIcM9BZOLCAlAK4_1wXH1CMO1
6WeMfSM809MvDvqE192Icqu82ojl1TV1s9AGQJlJ-sYoK3ve7LrMWAGQ2tP05XitGeJib3YQR07RQNaRBTOTFcJQMdhcqrCURApZMoqRAFcKKwNsPNoNDQZ9
KrwgVfNsyJqW0X41aFolv6XOngVPn0bJNFPBt84B9u1twJ-EDnLOqh-6f-2EfqRB9xojuAc0fnDuX-vgB_2FATXFJpNmZiyfc80x6KzFVdgqtryWvyVuXXye
a1WWY8a4nEk9yXKinm7o5Eygi6yFd2JGvzk_MQqFzGPE88h2pBrJO5YMzt_RR75Jv9RWtrPlvsDGEGxv6xMUjR5GuBhAT6aDcZ74WiM3g5Pkydj52DB-Hm7g
onfGgQPKvNcuGFu3d9OAuk0HBRDbzJYPNF0TNd37hXMOcX-YNYaNHRY5elmC0eTmfS1eAFz2mK50_8YaSd4V09IFIX7A1R-tL212T-ND7KeG43mX1GfLmY2F
uAi5eRYfmGo4G0JoCEzY9aBHK8c_BU197n1GL-F7k_EYfgHIRsQcFEbAGPH2AOz0c9cQIda5lKKrVK5w3RzJ5Wk21P0NK2dWyztX3ggvgtgu0jvxp-uW2Lqh
iAnY7YnIZdywFozeZHhRd2Dh1WLZRhtluqhdMW6Q5Hpa0ifd1HAZP-izZuPiGU7SpBpj9bWkUF9fGHtRritK-jpE0knfwdMO0Ci5b9yBqCOsqapLnzw2q8ne
aOC2G9Ttuiy5SXIqscfawti6mUfUOn_0-XGicuYItnVaFCRGCiBRteEG23SV2SZo6jm_J4I-B_2npnbkxh7lbH2huMscYAplHFd5JaICVP_PQaGzJWdnQhOT
KN-n4mE_ACZzA1YjzfRRdfH8hpdct27B1Nglmyy5SnyjMcQjbJ57r34FNKLqiQ3N8bJyMB0fhMxd9Cpcd1cvxLS3LwS0-NaAqkUiDCtHCy9y7hAsCK--Mg3F
1NBv483QCzoqPZPtip7sVRIwdRDPBf2gJmKFSA9IlxPMOBqLEF6n0F82GX4be6etVKPRAn3_zbCPW3jfDVmRV_s9X8SPNF_gRW_yuxa__qI2F2lo3Ligi5P5
o8SfMAWfpDrLH2aWG3xrl5PXhO3ffGWU2hIwAYmpMAXQQ6OQa5Sm5HOrWK1LQ7-z3qXhbT2eoW8QwE7ga1UW6Gbr47JzfrrpKMwOrO5mmKXQqVF-ptimEp1M
tBXsdFptRpeRWWlU886l-Qu3oNi7HQHrNihI3__z6dcJ7VowuMOKq1gcxKZmQe59BYoNG-JkYiHpfCtbYVzllHQejSatp0ZGfRT3mEpkSM4NXS9BfaRJo58Y
qddxsNhwwd7Xt-wkKLx_8TRAknta5E75V6gwgAer4m_RF-s0h1vue5oMz7a75tcxWsN7DWj_sFXs1-MHHHseNfjwbVA0Ydx2mP8ly7u72xFjD7HGooiEDE_f
yLvIFalADnouf1qvNKPUS93cFLKImhvqEI0_SCE1hiWH6h6VUTb1OsUXbEiF-_mb1pUVDqOFVue3_ES07tDGIZdXG5K_dWUg1mvKLFJJ3g3p512wYZLnQu2j
FkUWo9R-ovkW2sOGRez1AXSpaRmh3x82ze7Pw6ST5DVyrlM0d1-3v7bLHVUWdTiEl04iN-T0dXVfecPsru4xO5gMTE6n-yPhMds8wiiEJANakVFJ5Yp7mEJk
etJEEp3k-oN4RHSpTvYfqCZnPEnfLs--JLy02VwNIjn19piJt3TttgZVkFqYRXW8hHvViK4ZXDmxTV9Tq_qtOJSJo2kxzr_fE-yMsFWUnPM5NFqi34DjKhxU
0PHMgb-YUM0gtYU1iuCEhWq4pTy6QLNpwtpZJMEGk_frAisVH32FwMP6iIa30nmOqfXVdbIpisTO66jN4VM6YGYQA7J8g9qL417pHgo9rQnHWJybXPV0njNT
MbW5RbEUrR9wrim-h35gzC31TiNp09x3aoTOamX-nNTUP1f8CuuHEq2xD8RO3z3o7lUUCBPP-anKpBNHYu2gZkzDu4sCnSTDc9iSIioTPVHwTP__lsa4nqo4
jTf2NmUxPUD71thi8EnyDfg9aCSyckgnOeeFGTV6a5bSyL7o2NwSk1A2e0vjkWq8M1nXYTlc0C7ZjiOSW_7XdAbDrBK96yv4O4UsxNJN_r45PaWE78mvQnJw
jHo2q9XwatqKk5yC0VYRcGW25LM13sDAvR1SKzCEtA6pMethf71fxG5XB9W8IS6z-GZEL3kjUmV-u006-8m5-9qdG0ksF8I2DO7Z6ZROCnOCqsqskAKP12Bw
vDTHDQXh0q5D2RpJ6n8kT6DoSKO874iFWav2LzZx-Cs1FdU01fLYqlihBGZ6RHu-S9RG84w061DJCduUXmFIWx0MNOLRDn-Ylo4prMmEminfsmnCZq97k1QC
Qar9cHri4pvEC9UShGDrHZqu230M7Sr5ZI3Yzq34kWnq8WsrO_0ATW5DgLJ_qwWbfVy3
}

