sprite $image210 [294x194/16z] {
x9W7abmX4CMMt0th-n_NsTw8-vLhuX_f2Af23tYw8Q2OkrjvsWDv-2z6HiQ6rFo5bX3o6TNy3RiySTXU-9WdIDtVy4cUeFaRDdbY_RVO9ay4QN_i2DAUdXvy
_LsZ4QH_G9xIy03ob9f7aATg_Xyqrb_12kjFdeJd27aIrb-d4YJo50U9F5K_9IqH98NA-cjvOlqLHkAmAJJMNw8I90NBhBz2JmH9eH4a1IkilyB8HmmIUShc
Lw6n_bgU29AM9zPVonFhhr09afOdrb_B4q5IQ8aW2LXb_HKi4oI5aHxvEQBJM7yjJmH9OMJMNw4drb-X4IG5Awo_bYU2fEM9mwPGRsdzoLCrlsj6PlsrF14a
XKgGj3on_bgU2992kqgGoDFq6FAqLko9My5wZZsHf_NijkOnFLazcQKlthkldIPk1I-M-fZaARRKkqto55lwuMbERWMHfJx8as29F0cM3fwdUW9BBzZYqH9O
8a-29VAaMNgv5P2dhQKNd3m9biYJOEdOUMhf99OE_sYf9xJ4dufcgG_dLX1OEdgUJcE9FBtyU_S8RWLpkez04e-MD9RWYI_VR6kwHPxuKwa-fnjvYcXQdiYJ
uea_bU9IdiZJdEH9e9CdyVPqoZoH9oTFv2aazQNcYKVBtjEmLtdoXy_Jpb8Vu_XvqXyjjh7KVtlYopTjRq_VsZaF9SbL68g-2RP00Vx_Qr_0qqrVrr2xgXuz
crvhyrO-XGxM1PlMXed6UheobOrINqxNDReFU2f0IeEskpALJYapZJXTGqkdL8m7Uhhqr2dLMZJ_ANhYlnn32rAgjSWVqNQirYWuzTGejRgHU-6sOpNRABdq
r2YHb1kb9DJqz98dKYncPk9uSxLdAlyXIMAr9g8rYN3Zz8AHhwW19P-U6fEi9QqR9ScleoTiDYSb75fQYn5lQwaMPacleYTaX9JyUjgGD4gr6dDRJYyJ-RAe
-IdjCvNEgL6gLHWeGQOoxq92IauzvGTEIHec1KgWfuaP-IbXvDlrb83I_94lYzdpb71eQRkTrO8TH_FgITGSb3nw8X5-f4GG-KxQRCzJmiYtjHrGckhf2Hav
ABcV2cWbe3HZfi9YvgNarnDImk6Evn2Idv9VJqXfXg45cos84cOgHE2b6J8LRBOIHWdrr2bbPTgtdV2PcwsK6aO9CvK7Ijz5liBdRRPI6wOOIfYfO9fP99rS
JyYer1f62Q_HOUPhwQoHB-x-_p6gjPGmIgYdJgaqJBaXEgsUH1kZLgNKKW8eONti8b-rHedMfAUBV77tRu3QptXA-yYNifIQYIYTA_95HbrAswzuIljCXTZo
cjOaPunynMvLQsdzDkWvJMy__ltB14zFARMrr29VfjCS1ECuKkeZ9ziLmtsA83sjFQRRvNHP-2JZI6sSodThIU3gO9YUcgtRVYS2b41Fnyx-TqPrjvIKVCts
r8dKLp8Eb41F1pKRodjZ1K8AQRPnv5lsb41FHy_-dL6n_Z307r5qnf5lCUWuqDFX-KWfVJtPLhe40y9CfKU-G0drT70OQOtH9gO08NaYtvIH4khfq33IxWy2
6wKS82H7v0kKK4z7Xf6bCmhO_LrlJXC19KVRXJGRUgbFkxe6O73gYG1DUDjXiushFr4wnf4uFINOtZ8vFkmGq6pexwZTtn_v8fRF9FWVmiSmCgjc9exTFr9F
M9cvbZJKKxoGdXX7GeSMf6IrbZL7w0bFHtw7KUZkxyzKa5BbbSA65cwCIlq5fWE4v7WrCMlB2YZammvuEcA32Xz7dZ-HoYpbHYdb7zOJoyCWMqkOaEBrHCpw
HIapfv_H4vwER8ogZUi08NdVd4xCl54IPgOVqHCsMwsx138WZ0pN4-KlIbgDEJ-PgU3kVsSqN4kw7iF0_-OqqTtaoWajBlpCE79F_GUO0iQHc1Ef_NwNTWcT
y5F7R8tH5lwVSFVtlvgOkG0bnEHd15xwPZ55Z2FnJq-KfLE2fdDmOXa48hMKK-x-_ZUdarL3IeZ9duzqHhMM4uuZ_dig_Pa9YqHKsDTic6RVM8rt_ydqH2cj
-s8nK_OmGaprnkh4k__pdtlAOc8gx10IYEbsdSHnDs82FUqhYOce2Jk418i9hYRD8IJ_np99J6J9fiB-CBA4d8x4b_zhT6mgdyHimjumya7UJKZOR2-b9nBJ
py_bVLKJzfsEm0QNeDacBHXQe8YDStxFAva9-vB_QiLnEZBRqnDMLkEFjBobRARChXEaMXpZoDnw8ZPTwUtZRKbgAXieiT-euXX7PjKJBgTb-P0ayXydOLX8
0QSZisGgM9JLT4doNvd8tjeJX95naU-UKruTb2OTH_oP2XObCRCX9TTLxVbhuV7JKvCsK0euYfnKJxYYU41fgZ0oujL4B6BHWBiH4nO9vs6caiQKOFP__Vfe
3u_afpI_aFpNL38vABsAaFnVCVfEJraqG4XJI_mRFR5eW93cJbIWxO1Im3Woyt92JYIY8UF8_Cif4L2A64Vcd-mUzPH4D63tdp_7XBRBG0bs_sivtJbnfmIx
_rMhtDkEH4IZmiZvyxajyKwvKHeBwU8ap2oDqkYgzbKVIRvA8tV_-JaHtodbORDTzROqB-clnf5BK4kM_t4S-GS
}

sprite $image210 [147x97/16z] {
pPWDZlCw24Np2nYmlV_TlfUlAAC8LPOd4vExWgDmyAMTVf6LO9xUb1cOcRON4Us9q_zXMby2j16dJvXVCRq5cTCPJliR94gNc5B14bt3Z4iOq4eEo2aL9P4b
MAdvd9bFp8EmEQ10fKmYJirmWZbWyLjGMypY1olb5pzQAR_umKhDu6OMgvHV_62bl4JTIiLBv3jc7j0UtKe5I-J3VwNKGdTcvi-M0UtHhTI0zkWCq_RCuiSy
27xnWvNoxH6aLF_Y3-eOBr6qKikDnN_eREa06jKnoWugMYabT787AwMqWoksMAMK000eMYcF19Y2bV980C5AUQJXqzldDbAuKXvfj5BCj3IG8fI2kO4KejJa
Wqmm5gfz2Q_aeE8VX2qn0hnBgHaumTkKMf2zKj4TiwONAhLpmWlGwEcrbKB45tJCGam_I0075Bv0AJoP203VfHGLGS3nIatVbQ9Q2y9eACadYLCAaKibI3HI
AT6iqqzynw0GScR4GKgnvdn5yaeX0jUg13YWOrXolY0vfV0pFSgr6DApKAAvWNGgHM9VwJcbR6Pjf5CfmWyIc5BF0Naa7-1qmZpp89X47gcfrESoU0HAD9SE
fCibJ3NJgTGVpgoKMhgGJgK0Qwq8Y0xgtinAhTr8rZ68f9M04_xPBILw47KW-KiO4m4N8RJTu_jxPaWV9iqvBGqKTxOWS3sKCj_vBj21L4mcpLcs5eVl64JI
sy-vINGY7L_f05Be0ZgL0cGn90VLtHx6LFuDZkQfFtO98vv8fbJ_p1mIkoEtIob4z3-k-e4CwOZilIHUAJlFgMjw9j4rMefYvynynoJu1BLqUYxgY1gBtwKK
09KgsA4Kws7E5QXBedR7O2eP0QcjbCsi70_Z1KYTHFUK0a16G9McKZOpAu-VT4lKFbkEOAbgkdzdOhLzDwOUYVgLGgaPmJ4v82lzKd9lU_Gh1I88nYJoPV6l
VMRjyKJ0b4AmS5R-llZbyvNKjySJIbbOMUNhgM_bOOl_IFmVU9Xf9nKFT4xEjyU3IfbDQTzPE1rnxL5kjKV_sM9XWPLKXVc9zkZlc2Cad4HKr0FnDetBUfbU
4dL8Jor-ksDEAeVa5d_Sz2oiLudMAI8W2JsIjKTGrlG3nUeaYWa8qpyeD9UEzh35Z_nG100awix6gCmed12Ig3iRuxAGI69HTpP6PYLHKTSUiLc0VxVu_m4
}

