sprite $image386 [139x92/16z] {
pPY9ak8m34J9uKCjcV__tCKrNiAeWgB1mV3gt7DUITqHuTBDdDRBLp15GluAaq0WGlYyo5f5AjE7HPRSH0Zneo9p0kZEyYqYXFJ9sj0li8uLM9PfIwiYJoDx
2m2XfLKnkD3L07cE0EqoZrCX42ga6PzS2D-Wfs3v6XNAOHhK7pvGoIddTSovORPLqety_iai6KSgwGUY-4wPAG5qe9BJVmZfRJA11NIaakx414xpUq8YFmPW
4O4zb2QJMVBfCdCMhg2w02wJIXP9TKrpYE4KgIdM1jzTpFPeI3XSPbHES5aXV8SCSje3XH9E-G2nK1Cv7alQ9xCm00cT8KciS0v5RubPGdU3bGeC4rjbxNwk
iTCb7QdGtEi2tuhoaGhNOf-i0cCevbHgiSzLOSF4L8a9GikfAZ3MOwXKNIcIfzxOscD9Dc1cf9Iut93uMfa9Eohm3wMHS_qhL7x0-jgREJjSaWyf_w7vXHTY
y1ulcQ1i_ANOKwmYJSKS2vmgMHvCIk7mrwzlm0TZWHJEoG6NHwHSipCa85C5cyWDfcIpPTPOaR6RfcAuW4j5c8zbH0qbUB_ZSwcmbBiA8pipsrHMNu6FLKI0
9j9KR9bSj4hm5DYbKakWLAmjSJ6cOeJ4fLAKYZaOAaKJ3WlSeMB8oCCu6eYJMU0U5MDBs4IkYALK6BGQByJzAbf6PrR2PMug1EHbfy1Af4-5aPzaDasNJOK8
IBDMcIEXIqK3dTdj7ZSLK0KKZ1ftgH3alYLr1hb6GwiGxKLcpUXMaJWblQLs7AxnigVIjgG9X6wL-chxIuQAM2eLx1HxYa2loeqe3rqIOR5KL6IifmlmPvLr
-ms0sLPf82-EPouwL2fAPLKgHcIcQCXqgqn9xYeAK9mSnSP9Ae5BHQiOnROZerNAzjlXgKgfvK8fOgWG42wEOkEPYZ3XMEKQfrmgprM0hEDY5rkhj8-vfae5
SbKgzdhio01AfObK05Eb8fOAAEZGshS0l_zt0Mt0LD70hh8_Cj92yXkygj8US3RJVh6bxKO1Mdmgmb2FVGExsFAm6preXmhhOsXZtmBG4u0G3bG4gi0czYsm
0TXI4VOLs5jilunMOHW5TaU6_E29Yi1VO7-n_JAYH8m2-oFpsfPKI8m2loyoJSKeS0_h2v5nX6HKP8m2TpBzjTZINs3x5hX1xsxyjy0FUWhSVmjy1HvMxFu2
zzy2NqY65Rk_mFstm2ZmYCYCtuqkzk02sv4PN63x5emji5riZ0s97Pd11RPlmU02syKsTZC-CdQ1nnRR2CdeOgUUaFm3
}

