sprite $image160 [236x177/16z] {
tDY5hSP030JXs4VU_Wj-Z9P-3CzNGqRhtBIJ6crAeCgG57NYiwvFmoUufb_T9h0I-eURhGzbKQYX9jXiQ-Y2RkHGipfns512pTQQRkjE3ZLhXjkPowBoTkQo
SC11UBTkl9svh1aur2mAzFC5d8rL2JRRCZHR1UmCAjkcfGm7x0nYVtneOPKSQZRAUVvdvkjE3ZLhvtbuc2_gUHuUvXjE3ZNhnjkPozf9TWPmDbObs6pppd2p
zQuBSFlJb62phKgmsVhGpfhjipFWR5le44RPRsTe-vD3vMPhJKSJPOV_6TJ-U2YXPcjT1rPtE0W1sUQTuMQRTmQGxSnG0MTZLOBDDeVApTQxJgZP_9q1Prj3
fnLEt9dv-vDt1fnj5K7KEJj3svySAZTRQu9fCtS6S3Rw4DBmMpk3ozQQKqDzxURUbYFdSHW0rqoE8W7o_Tzsrx4w2Xmlv-JookRT_zzzPM50AztzhN-SlfYB
dhbFR2D8UvQWtdJC8Y9WxVxZyCLAj_jBoTKA-Asb1d9OuNPVgPEh5LoiDzOw-B3w6p-i5EtDZc-tqZ-ip01WTvLANfcPycXl4zHzQn9tqZguRqLqA-2tExvR
A_Ym0dQtuwlMI8947xUBIy7Icj6fbzSQoDBAoCJNyOjBw-UQ01rZx2P1LMil7O1cVkM3xE2lhKp6XxMrwsfDf8KrWwkrcSJs7bArHcR0tJPMk5to-DRMw2kn
M4LxiOTQFzTCKAoYlR9KhRcrckDZ68lsSZrJMvbYRSryBCfkbmfgtQ_ntRfe-oE7QES_lhNLFRRMPNoysiBDt2ugLMipY7MauM452BUB1BMshirgQktQJolW
DdjGQwiGXbN-JxUgTjhZMrlTzgnzl5lP2tVsurjRuLshLiKoSuP7Qmx-jLMqjJL3j5SulceTMhFQkan0j5UGgdKysjegsjcFhrhT5wjgVsaTXMjpzunQCQpT
YChQiHBRQO-lZaKmk3BS7jZ2sX-jndQYdgcjyMbTL_tQkW1ZUv1zpkDRMxzgtMq_hmI_QMtEuwjMYdMW1AlM33uECbmsp9cbfFruuyOw7gqFhLZV_76G4O34
TggWwk3rln-uR8_KcRX4AzPt65UjHp8ajlC4LGVzsmvFje6vBbBRpa76qm9aeYtM5h8aJtXyQUDpjIyFxQTBjD8vaGs9T5jZ-yu4F69zi6OpIlr5Fq_huz5s
byHsMC7mPaaa0mX4UePdnlfWROA5K0TlFxvzGNl0LfV-8pMiYnOP7u-KGEHh9d9yjiIc2YhRJuLgRBlhwts4TpQnpgBCY4VR-ljYZPvPiucExxCYHspby4fq
nRfCq1XTo73P6IVgcUg7_noVessxjOA1oEp6hkxZi_JCDgZRs8fLj6hL5pp6i09k4npVrdkccESUKX-niy4Jh6gxLRIJz8oEzizs7pOVEDL6zWbvwAATeMVg
sEg6EAmPGkBGOZZbvUVye6vwffwdXg5LwtVj1ZkgsUt_in3kzqmTsx4FgtNl8AkrYVRKdl4__vK9NHktreojTbYrcjtENPEAdgdxvw7rJJht3tBiLxETTtnX
JpMfZgqEzRP9jHkh7EGvUgQU5zk02FvFBI3LBDeJ5i8_3MgzDeBZjabZg-E-tKFyZ8k7Vv-VJQnZ_yrqoy1szglPxOIBXmFcoSJQoAvrl2DPQBjLjSTBqODw
oBmuXlNLqG-oHHfpHwlLBDeJ5i8ZOjix1yddDRR-bcIs247kNTwOxyNMJtYV-Ul-uQ9jJ4jh0GJvWdnlBh7LonlzO9ZR2HSF1yopmHrWMFDihmO2OSoMQ9dK
3N5pUIFzCqlFrDfrSsHOUkOpac3cSwPzxPysOCClQ-EX5m_7ZswEaURfMDkMiBTSiE9gBbPT6qzO28zBBjdU75qOQ68LsExVJqZWX8Nmg0eYNp5kczGgshs_
dqG4CLFFr2zy-XR0FQlUC9jQ8mwyU3Wbjdq22B7kOTtKUjZ5mqcnpPsxjIRZ4ArOv-gPEhQcrwQLjMjDh4UzpvmVswYikbi4d77G-ypviQsjD2L7EEAedZa_
jhLLsdRjd3YiPywFRMrLR2mpTS_KiStQAbgnpjSpjVRTGNQ8xLf5AzO3BXvEZwtUHsojVKoiSmUrZgqklseri_xVXRMuU9XgVcAP65gnUb-9JQm7NJoS7rei
apcqOirOj6ATQo7yyx_jPMQonrQjcOIxY_N8XV3yyibbHcp56acnpjypzSw8MArTArPc1iHwx49uVlbmjNOjHbupCbEib-YPEhR4vuWrex2MdwoREhOoYzKY
2-lyFLE_wgcrDI-jsZENcYSJxBf5CCLwiPwfBrRrgia8X5Wdk7WuxczxgeqCGApNwvdwJ_936vb9iLwlP-grSKn45cUuw9aBzWzJh7NFN3wsqZdQCvTtwfr5
1XbYBVwGUl7OPcP0hCN5myLZcyk8zT8zKx_jgRNicUl7DXxMXIiNtBUR5sEiLZhYX8k76TesWeoYPsuJsqTUNPDwozZQpQqQMx-tLMFRn7hpUNAntdnUJY-S
_m
}

sprite $image160 [118x89/16z] {
lPY7RYmx34EtPosHyl__xSCGGfwHOWIZQpEz7fYQeydcSZxtz-jwsPphgpLxF_P2dyrQExZtVSpx-s0AQxjglds8cR7st35GbJjantWVNvdYVjpsbJlM_Bek
j6M0VkK-rjaoYInQOyiKg_7k6AWoMdHTPykOPHOz9kLMBAgNcyabkSoM-NWNhA9CmQA2BIl6gu6UW1QNPDfIuJxAjbJ6MxUbO571bg95TLiAIx9kIzsYwyIM
caK5MoeM5SejMRJEblcV6WLRAXPT2xPKB2eCj6ZHytwKQxkWkIGxFzAMdTpejBOP2aGGlfT90auGjetf98a883fz3zT1KNi7s0FOm3LGoREI0E1Rc6F3K6nb
kSmaLGsRwxYs_g3ZMQqvahkKEL8Fh06AhR65twdHUL3T0T1jWItVgOpU8MepP-zmMrJkI8LvKDJZszXplalA7QcjMNEaiQfPt0Nb3bGHH5KCO13m1UKgw1t2
-XTgposvW4c2998xKj5xSai3dLCDoa1b75oUv3euYwjXDFEHgYKfBi-Cr-PC42-TLPry-Y9gT_AW1k5MBtU4ydsvVXmm4okv1Y0wd0mz0rujTsJQNOyqtWTC
B5VDuXF8EY88-rVb4gzBvc7CQrXOXy88zf1TQhdALDxZGuwdIAxn3j459IhWvO6gt34Qhtvnzil_iS4WZbXjeE7FoxVS6-0chCo1mbmN6hfReLnygDmXmtWj
gQeLuxlD8EwvSjljz__uEDmyg_taHbBp3d765d_ynaoB59AgLhYSijfNpMTicUTkoBdcHloCYmU8-rScCTWoozC9zEvWT4UCN1DrhFdljimZYnW1m0cdCxrn
SVCz--D0PSiVSty-GS0zG4V872cbv7WBjamEJBhtJkWLeBE9cbBZf2tpt1hGjPgIEjuF3M0ls3B9mwKjIL4LG5nHOuALBIVpWhZuGeKxKBLbFbujgP5gBZ9Z
PainzyOlL8rN3LTjcOztkC_bUoxgp9Pw6a6u9RMv7rXH9xQKStVsq28MbHsMrB8jyuigEXrkvgBsWAXpM-gv6QKC86eVg1DRwdaOeJIBaJgtfPwNY-hD-RLX
o9OrkRuXB3gJcf4jwtBNIcGsFDYoE4yd6DdmtssfM-JHaofRDkNMr323VAlSJNauGTBlbxrvUVI-gztHeX1rTnwdhzx_
}

