sprite $image16 [295x208/16z] {
xDW7TcmX30HH149X_ml-ENfIEzlpwkw1FYN6krjLSro7cVrDsBWC5lsBZqlWrN_K6kTWLVydJoSAblt0wKHXzpdbumIZTE9aeeY0IzB6NqJ0PJ7WrJUL4m6I
caJ0LKnKzADiHkay9cfMIuJxXL4wzltY_GnE14Xg7VeoqUKa0YHXH82Yd56Ir2823dk_x7u5mNkJb1C1n_fYiUXNbKO4I9nHajGY0YGvYG196AEaAB-txqac
Iey09ihxtGGH82c_cmXWeg8_W3GYGBA904aveoIfIGH8meW0YN-sxqdYmA8_i9n4W2ICKLAKVu88OA9sVnffZ98aY019EH4WgSbxawGH0PBzWIA0YOh-z78o
IX_WVfdLzyA9W7UzNxmlOwBq262YPlPTAYS29BM804aQ4I29DxbCcAZT1r6J292a4G6I_KgN2N7WrKUKar6IX1414YS29BMaKSBNziu0kLKU1i9D0jZQbNN_
u_xJalwQlYIcL7t3w64TuHkqixi6Kwu9Gcw2_589sPoHNogTqv2e7gPjK2E_578RrCWl2xWDQaXKnU3qZOgbaDkWXaGju3QeaLyg0JeeF0KrpC52SlE16lcb
h8pwe4R5KebjKCCSpCxejKGDYQftFDq7QfW3NxeEg56nBEGsg25HzHcZFpaDYIfVyBnueCRKbKflyyPGHSGP3L3F1geg8lA2qU2qmj4x9f4NweG1Ylen3cr8
rED0xoFEhIzHE2yan_H2eaxzG55z128oDgyFIHNM-2Se3b3GhmCpQ_Z2QKWKrCSncKb7eixtG56VOC8NJ4EYe4y6nWTCPyql3gc_T50u9vwmOe7lMsVfmEQW
UBwAXVfgG7DC8BMTDhz0Nm_CO2PGti5G6yyeKT3Um1hCe6PSL_C354wNNwZT4JGpmxHO-y1aJKcNg9DKBDJ-y5A4hQ6yDRi_JQtvvfr3eh05YNh_40FGTUdA
qioKPCEtAnPaDm7zeQf-UOCUL4WpQ5Cgpb6nR4DwdoyVYO5iPkrASqp1pSk_Rn_Zdnn--gQPjJccUCMI7v9ZMYKA97cZcMEALYpvzst5v3EjB8Jj0LCWl-I5
H7t0v185agfqJ069ohvlZvXSea2IZkcVh5Z0RKWTJAivm2UcfOXFe6B9Aae-pp_Mn8hfMgRQ1TLzeFBlcy-hJt_nWOcOvu14POVaq_sG_4eIqx9Vee3y-zR7
v1ArOkByDhb41V9BGaW-tO-0h_Z0nBv4TJOl-RxrCRb4tSe79c89I5HcI7rCBb4ixvZ8Sbd49r2n9DktFYQNgENoWQc-pRvvWIFYV8zI7vFdbsd2EwRAmERb
XiJfExSwrRfY8kOgFbag5iJsJNNvxdKycAPtJAnL95j-YKAgbntNpYvlnJ45AfPi-uRRpliBfvci5HIHW4JbWgJJ3sx3PAaL9YA1YYNLlfMVtQrQhbKWgY8x
9EemJWm-IdBv-QMOL1HKG4GY5Kj-4z2NAAXKDAb0NABocu3-NNsm9e8VjS102XFmEzS_cvbkRjvX5GkYedJxdSl4gpGpeuCAL2pPJK0_ly3CskFY7PzV3X2b
daHLcbddd2eWKGUQW7hvzTzcL6rq4nMlM8xVDzx-nazOgg3ICGNDmV6YDF_T__eHWVoInGJ4NHGR81AgM8ut0TU__i_HgHK10XLBqcIois81nEDBGA8I99FW
3qVCL00492f1FHdFBrLNLnweM1BKax-KN-2W0labkmdeIrGLirOb854vwibuVg4N1pkFY04Y0Ea04n2MA51aRyK24H1fJ40ylpHJ07lp2wut0OWq9Y1UiP1i
8hAlOhc-MrMG-9rzm-4cO3k_rBa1JVQO0rpNfn545XCGhrX04ON8z_CBRfzM5KIIUZ8kKIkfFHMBp9-G0I99FHcNA3P1mvxyijvOwX9rm1db0UO08ZELU_9B
kNnQLH0fwidup8A2rXIRe3pUuRvvjmeGkqq0S-pROyLIpHgn8x_8z3za44dgoNZ5KhY2sY5Hryyq3G87d54UbryKFv2egqjKZcGIhrYQOa_5uX958ei9Y5Si
s2rHD__J0d786ULH5KlhcA5N4ZNpVHAPWBX4DPAo8-Wj5yUKe9xynIFYXftvPIP8PZ81yVo2MI6ofsAfXGIOgfwCIvHh-9voamYOW8mpYS-U8s9zEaXc0k8_
x2QxBV01PvJ7vvTdemAypYyfwycuENYOHL61bn8Lg2SJpon_3W3Z2r000sUKwQR_Z_FQpAG2JoKgRpqPpozVBsvTSvyybwYe2SWlKLNqpaagxSNc1Pg0_BEi
lyeJfQnJQpE3F89ARWBY-KNgPLAwGid3vX5ak9xCBr6bKj2QtCaKc6a5u9o0yvY0laJDbF_9L7sGg1E9KZ-_a4wcIZC3uQ1EPGBwR-6RYOCIQwH1xXEe9_yj
YVhJDXN1ZPHri5LFdcPcUNmZqLk3rFNaxnyHw_DtWV5lrPFn8sBnPDV5vCdaX3CzI5GVq_9sqbbSelgOuiaalqHvibi71zIJ6So1c3LI7TDfJK1VeWeQI-Ch
J6L0kkUNAeMEwTGce9zVV31CGBS5Tap316mV4MEOWEyS4MFJ10o9San3bFhb9eO9-4x5WkrwSiobWCUBqdy
}

sprite $image16 [148x104/16z] {
pPk9RiCu34GRMx756Qh__xaB0yHgSsWpRLJ6x8dxmNpowChNcxNiTVqwLrtDpFRbH4HhnS44krvEGhJii2ZKSWQYosQmNjW_hrKns5rjonb4wYLebILIrCUr
kbmDDYfyvBrGect3sh8Rk0xQTgjLylXN2ebnCn19q2fj_0jQ9Oz_GQlK835LgymWqRNA4aalX5Ov8kbK9JD8TAqoWqJNwWHj6ynY4e8aNIjP95shlF6lrxva
YgHhbHSaUWDBMf3eXNtD54cVnIIAf6kL6IIwLfb1eiTDVjjqhVGWIT4gCqZqkD77VwPMcIBfa-E487b_5YEqBLqhK81Arih892fz5cCKe9ArCbAWojNA67KQ
hJhJYRGAfXCri7IcCpNGoBDHqO1pKS6RcPqAYjxSJA1A9N8dpqE5W-YextXK-3GKs0B9sxUPyAYIsjQP38H0bT2sO6gWWHIeaeYSxTj8SwVpJgi0pHJ9_Q1R
gbUZkJMdvp-gBb97ybX9aOv617VYiy83aRTOSPBLWyaIumP-qxRu5Gig0Cq96xqN4jhMgoyyIQBMH2e-QLimzGKwiUsx8OSA0wBE55fjODdD_buhy9b8KJVh
zBrMBpMXWGEHekwFwcqnlrubglbjYs1vs43Swj6-QYBLV2AKPnkjQ_LWcgyLw6EHZl-tvnjIMyKEcF2ePep_c_b0lOnlWEm4JA2QspRxtpE60WFdKaMGZ8bO
Nk_VUwEDjG9cZF-nI0EjqFwDPNs-e1Er6v4MzM8HXGPE6V_hpyxDTDdr8Bb5vFN71zM0eDKR8ksNNvp3Dg61ln__o-_Eg-aq4sIV4IIwLkx0i84W197K8D5F
6-5ZhKe1CJ58TAqCpqSWk1uJUiuB4hrAvOYg7Cp4JuXOfbrWz-TnSsnjhqRC2n9TgoDk-F2e0F9uoLn134GIWkGDhTWSZrGajeCPc1aa-jlA1rJ7YSdcd1Wa
UWEByTbx0MHT2kb2a2JSraH_Tn8lWYJbUZJmtmQIBu8avnevSADLS0o29EkwlRDh5KpJWqIF6pCSF7JsHpKAagHQgnN2h9exWWfFY9Xwyxxii8EcmZra7mH9
xiS18b7eP42z298ChU2EFWA58CdGQk-Junkc9976asDsfhyE4drox4Gm2K6IKij6X4_2H3BvmsRUiiQ_VfSwBqZqfRmBGPBTmFV7_py
}

