sprite $image180 [243x176/16z] {
vDY5aGGn34HHiLlv1tpClcLqxqjX_AjL8xUX1PU7alrYc3mCHxzBbOTWexyWX9zM_m8JSj6JKlg8PyaSyOGxwUmDM0ShqDkLqh_fMT8EqsPmqc7YJzhHXoYb
ZtWMiZBDFWAS9cB-f7tqyKfPXsap1474t4ax-Xo6qWxJPga44HCc7NrcC8A8cGPBHrz64WmJHzA1FW313MheIojTO9Y8ayu-3TmZ2-lSe8vpVJqrpu4TINDS
b_wx4iknDMc6Y5Kc5fi_Twn_NKB-fPRObFJgrsN9HfhOaFGQ4H_tKAtGFKjT-ReSbMvwy5-qkFrr-KoykIueZ8DGUCcL0dd_rzsjbv5sY8EYsVoSY-rNEE60
ARwRvpp-My8RrWpJK3ialJgdiRpTIB78k2rXhCbV6phyVuK9Sz264J7B3PsnWXTwYQIh5U7e9gx1Bz6cbgpqNjzMsaprirE26xPG1TVbCQqMSK-n7WDJogNr
8mjTgJ6xMfW6IzrbYKw3se_PAWtFr4B5wCoNIRfune_GAT9JGDRO93B6R-XL1IkZmof2ao4Kx2bInKEeXSuuUOK7JIx_KtcyJ8n_cSmzlp5vnauDlkuky-a-
DWKSxIcWu27IrRLXr6-vIrl6nvnkKA8zHUuFw36sq-LiPipVx9YEjm3R45R0xg4dzbOo_BL_a0mk1hCjwNXXSiGuyn0wNnMQiwSGuQtbvrM2XpI3EIXf-vAU
65SPR3d0ua2MkxMMhIRZaQj0ezC0b6-CFSg9M8KONfxeqzrQcoQpAERjoFpnuM_gpXbwKyJr72NqjnGNREbfQhTu41ZrsI7fyDW3fp7Evn1r9x0scPXc5Od7
vlRp5O8YdWivYz2aRcMIFmer0kJIkgRUeS-jlsBkXr-We_u5H6odDR3Gf6vr6SBaCIAG3oPp3CupvgCfIU7lSrp51GyXs6PPdKW1EmAHcexqkIBXWpbPBKQe
O45znIzL8JkFYkXAFTCqJ4mcoq2mjq7PF67MaexFuuzfpJzOPs8-v9Vz8At7RLUa_FXDSOLP-GHFON8hkOjETtiNR_DdsOslvlNkRB8nWn5clwHj4NktQvYa
THRZ5z0zdO-kIDqs7b8DbNibxIzCTc3Q8tbdktX-NaPxWUdGWwMOHPZezQy2gqF4hlybEyZT83QlmQR9x7-bi2GxinsIjaNip-l4vjOBXl-qYm5TlwZWQdjd
acO-2chgZzDxPugWlZMggcIcUsVRcHQrlTUSBiDSl9hC3LvAOIgrzTk_objdYWg-DwhgTZHPfRjPgRL-KxlS-MRlL9nkeSmxf1B4VRquUwelYDWCfpq6IsoM
tIH2vlQPS6UOf31TGtbPhAUz8ipCH4Gldsk7zlvqpbPu8JibXDGdd1qKSxg54hTDKTnnnyxueME2j0MGRONRAK4qFGjJz7HaNu-RkeUImgZw8-d3oENf7tVB
0jsRnijot59WaGmshk15HZEnixtNjUV86xc26GSU5sJsNwhRCyPiUWCoUXuxiPUi-qx8r-LcDW8t3JuLrHZU_fZmTv1f3V4Eh92zq6Ih5fyv2IYTVdf94ZmN
AP8OYZ-d5R8VckmKdfdXcWfUhoL2FsFAUXeNqG9WvLxOo_myXQkPy2GtN2RIrecnPW18kUs5bzVbj4RsGyzIs9xQN72VNNy8hSjfZUo7vcIROHNczF3iTjaX
kbFVdqVBVGMmHlP3KxF3V5KpN59LF3UoBztMfVOr4Pl8VcRYoNG6_ybjOt7cQhyd0hO2ZXOs968RsG_DXp2NoKxb60n3IWaStzx7Szf6zaCJWpsrSU7QhbD3
Vo6dVSXFRbxwuT2IKgUxQGNN63tkBXt8ha2JfFlh3oHlbPWy1Tw4lY9Y6zaFpRI_073zp7VwzZe77aBV4x56zaFhdSfm6G4XvyPZg0-ifOT4x4BsIvgjdTcF
V3u11FcMCqo7qpUv1tBQX-mFD54iwOG9iUyBTNNxDMPFBPpJDh8V-biw4tqHB62yDHG7riZheOcPvRhEukdPF87jBqn1P2tf5QiR9xzoJCGsyi90ToDDjTas
Pjn2aPosaHT2ztrxBgqZQbPrZDCytnqfJ3RoGcZuOG58AUUSKeAv-woi2rSf6CXfZRoGERzsO9R7E1sKp3sGqmfv6NHx0JXtERXPLQcTm77aE3IwULEZ8t0x
L6gVYEF8yOALVFcShxpw1BznfjCXuZ1oFD0rmr-yzr6IC3qvSrjTEHr7ZaFp6Boraeqj6Y2LXgJCjXtXVILYKi2haFtGHa0kFHZstlPrQIo83xyptBRrrWgn
Z0Zo4ach5tRFIqHE7sc-o5nu22iHHv3NIPeUJOLgB8YcPblRxJ64LCuiH_P3Oz_y2vkzpoMKUuY9n_jBohO0Ekt3mTRnRzgIuSbWZ2aYuklYiXkx43FvttW3
oAKsnCaBOcbUnCgUo1pFwI4DhgKz1ls6qOIKydMflcAsKbUJm1WmmYDhlWYD47l5b4G1ymWioiVC-HfqUfytrKtqi3mcujFy_7kIhk-6DtTIvZESqnsi8l2L
GBS2R-2sJHHl7DZ8jUz9cgxMEZd1Kww6sOwAkCmlM3ylQPQxUyPUSteIsTAGM0op7HIn62NZWvAUMcirflzfAXwDXKAIGtG_L9ZqMYLfeWEuexNuK4uR0xT5
ajRekgjGPyatQyNTvR_LshkD0p4G1D73cgVyyvL9TwW2vc4x0NqBNTla81tfy-vpkbsEqnsqfqDy9q4TwPnkbxVf3XhIY-bQ-ZpItIxdyKZtOXf3x94-nTJi
CYOlHREisENy2701wJMxz4W3kpnX3dhIPuyGqDAzcFv2jXuh-mS-6TWbBInlbnvf3_72KWJiaY7jxT8ZNMUF48FqFx1BWZIOFRY3WcBoI8DYuWuAYaaZtI1c
UGBIPVQWUNukB02nHXf0h1qqd8o7KAI1NMe7hOTgBqGQR9SQQM2Nsa51CMcaGJ5f1mN5f946TgcH1hE7HXf0h94EXseXT2a2TgcH1dQf7HJC7XffO9SQQM2N
kh10CMcamw6QIRzJ1EnIBqN0BZNIOFRGI0Exr8-Le9YqWmA8DTBXojPR7HJOfKOQGAoH1dQfaGPsYP7-iDdZ2m
}

sprite $image180 [122x88/16z] {
n9S7bkCu34J5Z2f0zx_kZga01pwsF45RBpdo4_XeihtyVfAqiFmF2HKaoltW0W809TtBJK9i8LkyZniRYJD43VS9nak8V0SultDTzos2FQxx3i6UUtI70c8I
8jyaUAZx1i4twOvr8FW6tGF1z-ZEGap3H_w-xjZ8ARR6b4jj0Cc_g3lyA9XxVI7cAYUSA7-c-uhWPq8iukpyvtz9dDQTuqjrgOAk-uy4apATCJDJjEnYGn7-
WUvGGTzvg9mDjggPiILdWx-hE_jNzoO2uzJQfFFLJCyQGtNTloCOtgua6ATpKcaWG3CSXQUfxhbWWFLOXaQCvepjx71kO6V7_OLp-wpnowEI-LZ35A1Ky8DS
Navt430xzji8kEwhWk7WfBP_EOvcN6eAoxDU6i8R6fHyKJ2yd6pgmWlUGhLVwJNv2gRn0yqMBzw5h0UOyAP6mLkEkMw7taP0DMnFu25hk7PKXgq61tVX18Wp
hFsu1i1NlSfZDD7ZkkTteKiETF13E46qZr58hUlblguGqFRMRzSzlmifIq_jZhtlNNXojEkbzpW2WAQtebttx2uyoWm4mBYjfsVveM5FYSkpNkpUw7iNmkEw
NV3uritqaa4Vko002S1MFLyYeCK7Y-7b67tHFVklCfoMcFUI_UMa15kA8QJATTSR2H2_M27s9GbGrGZFYsuNFD8iFCilNd9G1V9ophk4c78fmCOost3wA_JL
ttMJm9oCwEHoJ0shdpxeiDNGSNJOB5HLJiYDhfokMLx8XCEkHcrLPmyyLoyqSdyv5l7Xxwz_7TgwhjepdMrPV1SGtJJIa1yJrfJWzznE7g1zbjvs0RMpiRhQ
8yhM-0rRrzN90pQ3pnL2QZ0TZIYafdvwyhfW9m_PMdowQMP38I44FmKlDzh97huL7N8J02EHVSGyUM_1D5JdEla3JJJsOHg7pR6nS2Nemdzej9F7RFKEZo9I
yoDLQAO0aQV2wLmd3zdp4BGZIf2Imt7TJhXpif8_WmK0jm1e9Kw4k-09-MBPbB34N4gjjPJdNtG9Am4s8GU29-JBxBYCaZ4IJkTEoDVOp0DiQhfngmjtxfny
NRUqvnQ7c2lKTcvquIvuIhvUDg7RI1C0UJuXMZxs4x7I1S_9rza2aAGU8Kb0webTGZC3EE7QkcROTsoM9QHIcuZtlfOKtNXiPlo9-vYLGcV_h9lYVaCCCOIF
dw8FBdJAjRhtHkrwsKxwJ7nWjGkUWkLS9ChrbajD8tX8HOuRXdCkqlAKoxhP9xcxpUcHN4gJOze1WFD6wzjXy9LkgjfhV6luhpMxC68OXe8W6WRfqd-vOQOT
x_SLO7hZ4_Kmy2C3k24DWDzgLt2h-xRvdrsIfk_Dm726oTpl0U1h0kUsbfl_f2CmPpwScwiIOhWPE4_0d5K7RW9-v0qOCoDk3ypSKAYcAaVZRbYLDbFWnh4G
0jn_4XWBAPuxgYezDxzpu5IqpXqO2ocUEp0MKZnt972TEs8i78SxeYebz-Rjpd8ih7C7na8RdYv5ZeLrxiYgh7D7ZeLrxiYniCwTdQhAEdUF0wvpRqjLUG
}

