sprite $image2 [153x38/16z] {
pTXNafmm483Xpkd-1_QoED0WrNgYvdkcL3yPkevW2EiWO4FC8chc7lcbTfdffiA42Fy3YTMs5Ugl_EBVYzmNblMZ488f4i-wmVrXOuvmXPgrMHUsKJYHswjk
3yiCKnLc9c8MjS7vSJZYQLPcH6G-6YPC24EerGdyutNbGdY-9Ipk2Vi9vcpHg3D3c7b-650rEErIsBml3CPXNbqWV4GONU-AnM6mose2tXz6emk9gyC5OJ7Q
FgenU7-O3pUl3jyTXZf-851rS5iO3j4a38-8MDIdvqicb_vStIZwDJxd30TMZQuAIu4kgf65HooKLeVD6JqfZ724UzW48h5udIGDmnJU_Xn3hSv65x-zEMn-
1qerkI3iMh6lqQq9WxXUwTNncZ2g8n-StrmJXjS8h4wMXC4r3Bmw-eXJkQaJNX3cemAk4rl_kDXfdSdI1wp0lAoSO0ZfhZ09cqt1o6h-JSWra2P4-8tspyse
vfQmmxBXfYeRjQYBw4j5tUJsiBl7KEWV49OA8-mhmz8OOGf9unLXW8ZxVFZtUFZVSDZjCZkRGcHfq-7ylc9bMm5_0G
}

sprite $image2 [153x38/16z] {
pTXNafmm483Xpkd-1_QoED0WrNgYvdkcL3yPkevW2EiWO4FC8chc7lcbTfdffiA42Fy3YTMs5Ugl_EBVYzmNblMZ488f4i-wmVrXOuvmXPgrMHUsKJYHswjk
3yiCKnLc9c8MjS7vSJZYQLPcH6G-6YPC24EerGdyutNbGdY-9Ipk2Vi9vcpHg3D3c7b-650rEErIsBml3CPXNbqWV4GONU-AnM6mose2tXz6emk9gyC5OJ7Q
FgenU7-O3pUl3jyTXZf-851rS5iO3j4a38-8MDIdvqicb_vStIZwDJxd30TMZQuAIu4kgf65HooKLeVD6JqfZ724UzW48h5udIGDmnJU_Xn3hSv65x-zEMn-
1qerkI3iMh6lqQq9WxXUwTNncZ2g8n-StrmJXjS8h4wMXC4r3Bmw-eXJkQaJNX3cemAk4rl_kDXfdSdI1wp0lAoSO0ZfhZ09cqt1o6h-JSWra2P4-8tspyse
vfQmmxBXfYeRjQYBw4j5tUJsiBl7KEWV49OA8-mhmz8OOGf9unLXW8ZxVFZtUFZVSDZjCZkRGcHfq-7ylc9bMm5_0G
}

