sprite $image237 [191x233/16z] {
rDY5WUWm30JHoBQe_u8_7DCU1-RLCDh0jhFLOHlLpEukjut8ec_bt7XMzOCOj6wgdq4LDB9VgeMA_hMSbEY5CCHOQcwew54dODuVouc8NWj3TACvO2mv9s1U
_KKv46EfXH6YryeHOwdLH8obbWCHlHPskR4aZAZtRwc9Y5xBWHXBpOqGlLOBqOsMyuH_2AWJ6D42u0JCUs-rJeWUKD3CFaZOxj6ZJi2y-b0rT-m6TG8ZMm2S
W4MVfTm8OwdLH4IlnTXXB04ZQjuNiH3HQpaHOwd5-C5Oiax0-ufg_U1p2d828_h2OY36KdF4M6grTFG8EKJq567YSmgYN7H3KLE-8Q1EmAAXuczrzw4hEsy3
0TZRLzJGx_-sQS8HTixg4DG_CGGp5UtcOpIKQTz6b-NPoYhbvcnuu5dEMXK0hDefyGOqVgrc9ynDv_-tx6nuuf_g21gU-ESv0WE8J_vJv8Rv9sgW0bprTza9
SXFmgza9yCpdiXE4llDFqG3XYN-21Wm8-89_HMwOBpIm1izyeO4bkSdpgzbo_2oVozRcHk773Qp7yyx3zNolRS2GgVjV_lVrjN04h29LnOhz5PeWGMilImgF
cOqw05QDG8HtToF-VslKWE_kMD20XVWXVtG4xd3km6nnRdpC7vu0_Yk7xzJ0sjmC-UC6IlC73Ip8JSJd1fwt0lTs31oX5NXum1yrOAzNnO-R6Z1R47hYHqi3
ZK1dKuHiGUYpV1u1x5wr1lJSPFdS01z06s9X1DJSvFdS0Fn73MK4T7pCvs8_XWqSVrbc-F41y0HK8K4QFi_lE1iSG1MU0b9kydm-WJX1TX1UvtE2t9t-Qt00
UcvKVfmWH0dIRtg1dqtGxjJaKRc9-Sywru2xGpW07S_ybzdq0JWzpwW1FVHpVAFthCa4yG5Kq_-ld-RJU0B96Txx8af-4_7pV7hLXNl-17g0xazB7e2CZzzr
tHihz7C3S2_t5oL83tsUJpgu-vveW8ROlHgdJCnDN2X_l-jMfmR24UYlyRyJPrfkugebUDUrdmPgzWJstV7LhXsK6wzMEfxubA3i2D272FOVWOVH3qLyQY1n
05o1tmx93VC78m0a6tXP7TJ_FVJyGp5_F09n0_sBrlKzFe03SiDLcVyxGSctoLBgs7yedldI38_hWD17VEKIZVNwPHdmjGOIV3qtytmzGGVYcH_ewimYn7LS
w9cVI91ZVWGE2Ztpamt0CJi2q7EZyNa4C9cWQJtZArG-Du396GQN4FeSNny1cS-XZuiimWYGN-Dpw7N-zDkankVGwtpMrPd76BY4qEjy7e7K7W6kR6vKlhv7
JF8Ph_Fr4PZd9q8lylCVLCmc-TK8h_7rfu1Put-OzDpeV4uG784Vg4Py6Q_pkO7u08nKmcKfyCCH21SX0zKCNkVhJm5mXRdH-VebckVpXg3pzGRoVCxDGZu_
1N9y_kgtbizFWHoVGx-UpmcA-NheQmtuSWCHNm-zkzkVVEW9ye2lXzv3lhjoB6OrvlVS2FYOlxlsCeE0BuRUFS7VgG7CDn3mfPlUSton0JFxYw-5ViX_3VZa
Lne0bHJwCRyyYWtut43SGVvTjogX7_DBjMB45nfWVw0LyCotzbDeDk9B1q1yKH_pMmVVV9SEWFW2FkRJm3dpfHDeNmxCL7on1Byr07Sdld82PgXMDJpCRhSS
lxzy4ryOOMqbRlXQ7rVa-Bq1uWjta8el5OxdnH9yVdNwuRjqYKgv-Sd2-_9EyNdnxNpXEQo5lg9fhuyadqS0U-TF783E9xnxlL-oV7mq4FCXykFSb8vtntEh
IRuxFYvjTpWz1cRz_pZqzBnwNqgQx_uv0ioV3f2Kcrxb-fpW-qU243_517w8vwhqu69-fG9_R_fy33i6Qr2Mdm-zmNyN7bk2pmtm9ThvFKEf1feAyw7dUc-M
u_S6t7_l4UrVxJdidlCtp7nkkCfzU_4l0cR-k05E4F7tFVRp3wJXw-EoVLuzrM8-9wZl4SId1bG-XvuBhyksFJ7uCahyr0WqFZt8Ohzd-2tqO_pxkcsFEi8p
Fno1tW28ltUPm8zoO_TjkzduooZpKoD0InmTm1oVyVMlq3yls_MDOUYP7oO8zCinndpy8xv7kNbTWz0JFswWu_e8Z5xdC_nyRb1kstRdq5Sa-Tm0m0rqF-zn
AJxZFGnz2K9F_BZGEg2d0FERS8hVmbrcGv_dym6uV-yHdT-607a-RPA3q5-UmMMPvhDZzpfSXD2_IcVvl4bobMiFFUKcnU-4p1v1V3g0aF-nILwG2dsQx-xn
8mXqYHA_7q349-_lJo3rGQ6dt2JvksDcZ_36xmqWvZlL-_Bw2ds0p_39C6w0Lsa7FSWGyLdFdq3ABHLwhjVu9uTcHW0xbUClFklv4uZTXkjDN7RRllaDaKbG
NuIe4dpw198FFLTz_7UNjYz-uW3G_Ms69_WS_Z8CVIetb-s_TRc_wNzlJpJm_HZsF9y_WVp3q9VRrklwj2xBDG3uU8zWVdZlj0TN-ThfIoBqzwqN7m4tW72J
StuA3Fc8-7XistPz-sJeHty5tVLbimSmNeGmyOl1thJUv4B_lcx3kho21EKkKP_asvD3FviRhkjxq00GBtBSGCJNVyT4VMnXtSfN0_0kJ7rGcU5pw5ENPLoN
XrNs0uwe0Hw1QRuUUguhZq3ZJup0FB-Q5Ffu102q5whi25Y6FtrPRXDrB_Ib0MsloQxIbkVheOz7u9E_fqSWoqT-GyWNFyO0x_xy22JusT0_fkryYNP-VfKs
Y_dvt0X_IUtTKeiGDn3_tXN6ovTbN9UdJUyHjJ_4-1V4C5yCVNu49ZTHvryGOo0-XJxnEgKNxn6jeiTm_V0pKhWibNfOutpkGJlcVrfz1b-2qCiZ03ZSaT8p
Nr-BzH5eV9hX3F_WqET70F3sAC0K7_fbgOy0xK6EFF_Oop8_0eqFUWea-9dS2A7FhzAyI7YId_g685L-bUPVB2FnzT3Fhz8Ll4V8V3iWDze75L0blo4SNxVt
i061Bsm8oWZ42GBLWijIMwL19LoMQqO0cNfkL8j7m8c_xhBCZm0tG7mXz2j6WFaBBajjbMR-WijINAM9dmhz-dfyDa1yOKDOCGBCNx1PYgiqY2_aPia8S0dV
41RKmogN4FeLTNro0qBe5uv0Bo7q2_U8Neis1FrjifMm8QpU8vXV-uPmXdeIVrbkn9-NeSloL7KjZKyVN4zKbtUjIozB_LsOSdEwUjJ3NyF_3G
}

sprite $image237 [96x117/16z] {
jPdhUkew44CB14Xc99_tVzfpSVK1hhnDSd3rQr_NaANfzCBNiPplw_dhztBTOjjkfr-YNzRO_arirybWgObDYVKoctwwRHMln7rk3OleZuHgc2RU4jioJRpX
vzLmgZlPJtnUms9gvjMWdHmdrkN_xwI9drc3YHz8Ea_OoU64wsc2-3arw1WSJTmlHu-1PyAkclYPDVWnc5Y3Zi47ySizFWOpQ_2T_A26IJkv_sIO-9ar-4vE
hK7YvqzOfelt6XQZJqoaYP-P13FZr-o0HEI_YLzHGmALhmbpwI3-IofpBOaklYRC5MzyJPWatlYQC4UDyvMOgCRzX2RCeEinjbV-NS_mqKwsYVgg5K23FXTF
9ENdEO4aeG4VYIV9Rtx8_3ULcJRXA5ruyP_TLlz49cp2CV6ayJK1tnM0F78oZDxdInBi4Ow9DxvFGEwU4EdYdTzE41lKhXvLemJ4R-EIOhyQvsyLwf98s2Ey
fpi_AavnIOHD6EsayyKJnoU0zqqJTeXtVdppK3J1TXKP-fE16aif2Dq7jSe_JNZySNHtabqyC_32rmIJr2Rsg15Thq5yIMAlXlkQZ-oZur4-8Ru2cgGsOxh4
LupplGQVi4kywCv_NyDkySuVrw3i5QyGwOb13OvtyME-9Da4um_5Z_agsYGPtyMF-UCQdliv5F-UBvmTfGhXJtv1ICqHlcf0zmc6ufs_Vu8ASF6x-UCQX3Bn
X_bUW-zdmK0DQFpHhhPy5-_9LpxUJa33h_IH6Z8f_jFhO0fQVi4RUld1BuKOZOXuvO_4gntnrmT_rmG1Cj_HnS_82F4rO33XWHtHIyFNAnEVumcHQAqxdO7I
ldujYFZZ2P4OXKpSxk87nAy9iFBVr02EwCWiszNu2iGVrV26JfPSsE43-hpOrE3y8HsLksHvuIiixDQmaq-AJfRRrk4_ZXWelYQOV_v9ZVxRNsijeBpo1IPq
BcjARu36EbqfN4-tmgg3uli4KflqSm2CJwdHVudBUIiwVX2_cO1QW_ZV4qRybfxBUMMXFkiOl_OCQ58DDS3vhWQtqwtITVnw_0Ie2UAJWFE5t-95_7d9KjXy
GcPwyBghzR697h_kUXIfsSwNhRogQVb4fmQmg0SQNxj-BrtnpY-QqFuMpvuRFYLbknQ9hrijyQy24mAMmfuagEY27Z-NhdY5UVswtEljeHZDgcXNktnboJXV
eXMl4FUJtlFA58Nj1AY6Lpx4Lm6dyogwgRayttxPjF6Ir3jAAW0jFsxiYy-bVMSje0b4xsImpsVfYyVjP6z_9NGyYLxHQNp5nNCzTz--qtrWOQ_ewF4BmjJ4
nU6g0GaG_5631eQ6FVcb9_uwUai_wWJVrKB__gL8lEzaFweX-qNh2K9ybfxupSHRpkjZG6Ms4R7kgujVMjIW1csItLSHVUF1l1bfM0C9g8Pdn8ABNqty-ngW
u-zy4-yx-Ru6BrhymJ7OdsM37oLu21U_lmPDWF7z61pFgPwCEe7EzsFWsV_H0EVxCVYW1l7j67oUMwr1V3i6dqQNMx5ZC2UNLNmx1hEo1CJNCPWRVG9DEmOp
9GNIZi7Cd3Rxoc3oW3MExkG_
}

