sprite $image169 [184x197/16z] {
rDI7ZGHH20FG8UF-6pv5zlBcFz-l0WiP7oyaQkQHLTsDY-wkoWWtbMChOXxLk4LNkcqGNpqBz-iJqujbuncThgipUpPUejPbjsYyKkU2pbZY7SfbGMYgw1gD
DoixNiqBAtJ8yJeIZMLINrMGn5fbPAb7FvjS4eCdkGJEKm_tt76kb8UAtJYT7tSBxA2LxDWZdZesnNzAOIjErf6H1EltgnAgQb_qjU29JIbPx65aiOTTYyrM
bS3cvFe0ygoAOdzr_20D0d7b9sb6nS2XoLeoyie4KgouW4TTUKg2rnGmgQ_j9cmukEHiDvdvIZBEM9FvJ0KeY-AWerDlme8twEIy9TzZ2lWqQMvmpk07DNQ1
5K0Gn40KXqaozxykQuqxNKYTuB-iB-HMXRfFEvYL7_R7t4-OhuIwTRBKvgoa9Tvzqy4yZ3ULR0_MVTtXV9fHjpVtHvWgvWUBBThzyJd_YZlRhwedpeu6wbPk
e8IwZRaTyh9C1kGEwHRdda5FauXX3zITHCpW8jt-f-uiIOZRYvkSEs86puoucycIcC4dvtQvWS47vrRA3S25kHNIxSKza59k11xAxKTk_HUtKWaPVCvfb6qH
y55kYXsBW6jnYsJ78k0kDyMEHS2pk55sB0A-i0FT02i1yBeiGNRK0CVTohC4mBMunR8Z0ExUoz9vdWN0CsUmiSiDm6UZstdDtI37BalbbJoQuNLPekeurrAt
t3rkEQ-cNAe13ZpbRzkx2oJNOI08msDsTu_lVzstv8M0R6danAbwNRpuXPE_G9GdHfzvPuYu_L2rIpw3jULBr4rvUd07U7V0CvvEw5iJtJ6J0NdjfnFAj_VP
aS6wSXMxITypVNLaCYwFFvsGydrREpB863t-T4BvxX5hZoK3yl33afHdJD3g1lSC2BZZvdM_EpB8J7hywOIKF7-4_-h8t3qW_7H2Kbuu_kt8OCO0b3mi-JP9
7fakE_8AZzkNjxcxVirhJPSTUON7yVXm7pC1kkgnB1pmXyzDTvozkXFFAPb-G8Uv1T0ltLZXqHtcrjsEZ3ExbUZ8EA-RoOuCXgUZs4fsP9pHhHqT6HNSyghZ
hewCk9jUSThRaN6gwviP7HanjwlkbRs_8oFaLZKrztVaLHvmSwbu5ydjo43O7LT31HqPfMvLS7Eh8uzaLRaM3xkLLASxSgdy7Rq4rV6Ed2_tHH6tkAS3KGwm
gjmNBajKxHaTEIL7fZk4La57ZijzKObRhDoHYJcBxfxj5lFgfhYh8nDp1jtbEMun0nteoC2cUzdfbbZMaPdHaObv7P9svxPR8f_JaG7akoMHlEZrWOwCl8wS
jajlRbukdhxZ7HdpNpoktR7odMOhqP6p6pX-_6j7JcRaU4SkhODOyV4U6-_80VpJEZ928VPv7NbcS1aTESxM_uvyh9ilsv5rloFFE6T75XxIaNKus_KQ7Pc1
77kgZemRS9oj8yklDfsx8zyDiiEfE_BzjDcTjoEBYGHaP-t8IdPas7mBZd17FhZ83lQQ7Rcn_dmTURjjmgp1AJko9zURsHHecfKxieWzQfUzhJj9HnPtT-J1
teSzUItGaVEIh6zFzh7XrJfoRnzhja30OHrPOdQIXNrjU4f7bbZMaTlLtI2ZhOKxyYfEcjCFodNzGpgo95vtPCySxDUcegu6u5v7_lCjt5nPb5LZlzQWECRc
TEHuHlRM_gmFvanyBD6HwsHax-rYuqjqvC6kDfUcp0UwHxjUWrY83NJa2Dki1OCxk2CFPWduQJjoR_VMuRnkTNP_BSxgPcEfjJFFs6DzieqrSmqtgj-rjpTL
S4zUSsXjpmP4tJuUzlINlfD7tRrNszpa74KRSxEQcxrbhKF4FLLoQoWv_RVSFTHnJuqLh9kBtLrVKPs_7cLkRy9kZKtiqEKIjopevf2jZj_DjI3cHcVvYyjz
cG9k1ivmZzrRVEbBtPewgxfkHeQxjJw0hhjsn5wtD_bkZfqTjMx2BhSipwsfR-pGDVqEkiyPRcQOO_Hkn8PxtEKMfhwrXwuTPYJStOQRypHqZJrbJNVNhjQi
8tKHl35Fuz1tRHWSNzkFj_3si-PjTiwrtJ3zqSDUQCqRVtppWnpjCVi7
}

sprite $image169 [92x98/16z] {
nTe7Zkiu48HXAhEgk-V-nzqbxC88iaIHEpBsHthnWq1xoZ7TDepJlAnRpdYNyxOkypIalpNEwmQ0906bt-TjcSV_w2uR8FGqaiZhF7J2qv8XjXw9hOCV2WpL
oBUTnQehxkBpCjpA6mHtHjJrOQt8BVerlLJaffYdg-CW_XpNCte2yK3Cu-Tv4Cz4J0Tw9HwBytTeuSyVYEAKr4GydMxG0O_7_8N3LbnIQSHN6dJPNxhm0T-f
dFXCVAVfEqUYrShuKbjA-5ff-3zjKfcnpquLQXTBVJPJojUMgFmAtJP-AOewZtssBKj6RimCNJPoUzvbqpjiUD-HH8yTNRO7st5ssHRUOLkFJNTdE-xHTIB5
PgiTtdKYnMwzS8HtqU5inX7MGSjkm_bZ7NI9mX-xcz1VT3YRSOzcMdOp7juYMuJB1XjrjDZcuIxQCXjnXZKSH_ZE1jccMx0EsqjMOGwmGPVT9EkoG_Qjxb65
9Qim2txW13hk9gIv2zxJ39TznoFiX2sku7tXz70o2w_o3ACgg1MXv6S5BTn923_p8Tkao1HxKWGPsbZMqjQ7-m6iqFgPPnPUgTXj5TD3DdF6hTrEWwxzRiCz
clG8WswQtut50tQ44tQsiQZQxj4Yw_1aD-2ogx815k7ACjjqlu73gVa-tLZaQzqzQh2zvDWlYkozZWux15EoA-ttgLwtjIQ28puszc9YSVnpYqFkRiM5HlPp
24ytjkW7tyBDlMGb5bLkN0mXaL6Rs2AyRCCkQhm57sZZUsDh2wliODHMjj1wZeoxXIrsg1eg6XxQM3ouiQBVDZAUioC8RQpmPpQsY8MMhIbvm8umQ0d3MC4x
DrRphVr6vyQspxV7MiNRxP3yI_kuiaqNNHbPxkVRWsbg647PDHYILSmfvS-LGgDz6Dd3MBtUrZoRM1woY9EdR4PUZUoK_YqJ5nDxOYlDB0KVYYsLfie40g1i
0qltJv5r8gM5bGNNXblu_lquhpz5jY6zsuZAmcg_ZzM6S1Ij8w-Ek5Um6fq6uK_iTs2GMp-M_esDBHrRMTVTsRQnq_d7WBN2SjpJlgNJXgrowGZSsH6HntJL
b2zrnBP5NVOyfLfpvZcFM2fsHDYcQxxJFtcVjih8el7J_sd32Uz3FX_PiBm8RcYO2x_tGQQz7Q_Si4w2ktYvA7PE-IT-8dv-z8YGrtdyonT4Cjw-hMbQNotB
F8r3-dl3E2zhpk2S-li7
}

