sprite $image203 [225x164/16z] {
tDW7SWKX30DGm5NtFt1wJvp-pQ1tWrtGo6RqcfY3s0m0oVk9XdisA4dYKUgWim8lvI8Bd-4jPugYuWskA4vKXAGQ2XoLOIXmH54JNz9nh9KeS5I6ey0HHSLF
ECljh2b1DT14qL3Wg0p1xnbD-8wTtW9_bPCaVBKuO6N_8oEfXbeAoUsinJfWBliRcmJLSCRqbhYOIHA-Mh9KGyqtl-PUNkh6rzmUkSxP6ivPf1Pw6K4r-4jx
5od_A2SBVxJcCzcvI6dYCX_uPS2zgnhQFh1_UfiEz7rW_oAbGDS7bc8sL4FR1tP6SGRwFx0nYjVSsOTot30CXE6eKxl4-xzkTDaKP4ovq1YHqZy5xlPd-muQ
QjrL5y3uX-9S-1RJT0fSfpaE-F7LM_nga4Yab1mmwRLrd2A1vPRerL06RXe27hBv4g2QeluxEmIgD4IkXlR0-6Fm8UqT0zKIi1ew1cfbn9_c2hWUpHhBE2w_
Nflqnek0QXl3JtC5F2yK67yChjNmCN0-cZJc_rwRhWIgEVOqLq0xsZKuZlaOspZRQrmBL6FaWPA0EDeq3kSEO1rdl4OBu9wgLaFyisWQNLiGK2qrgo4Uw2Hn
G9NcwjNGFr1jO_LgA0D1EY38Xa2r3W5tsHqmPmTapas1QgvQ3MMW4b2r1_glLVyLaNC-1JAp6L2buRit-a3o50Ys1AgrS5rMdu2-fa0rkzNmDA1AarR38u5g
6yHx952HZmOYayHZWSXcV8Ld0fbDG16V1HHFG0dnB2344r3XGK3G_aGNdW8KJv6-ME0skgu38biHg4A1Nd8LKBnp875l84sLWGht1JBR1q25Um8XtWT02Pi3
0tYA9-5kG5evdeOx0P7j0s0riJrGl1eWSGiWQ5O1LEWVo6oLG8M-WH2l4gXw1efN3rJe5KYp0A287GAPBGIeq1iGueK1YQw0e5aWKA4Ve7YHG8K-WCWM2lJr
01Gl7gZG6aXJiK0VMWAPBHHO3gs0AFBYWGHQ046hY7Mz5KxJvyz5NHxeAW1fLP4nH9YzGGFfR_wT_iqeldb7m7-d-f62Y8KL0dETlDbz4NFb85wUNuyErhPV
rC_cpCD8WXW4WiYiWrB-uRxtVtPqswlEW19KmoYQo9BibUhw8mA4-dnRja_c6BL4lJkZsa_MCKlqK8TljZ_a4VjKBc-p4vJH7j6RI2JxnPYZgAkXs5doEemo
-eRlF4Msee-bXlDCBfTuU7TwiJC0oW26RxORIS3s1gZX4q0PnEAIx3ugK2AXXlEaXIxH7wy6G1c06jPi0i0X1QhXF52VwiCtMI-4CgA9h2Q07r9wToOx0wSC
v6Jl9-rsI7aq4KaDUnnIxdliPQizdAAF8gi6dIbKV00ru8UKdkQQ07v81Qa6VXHrDHJRdmvbe5U3JkeRHVraJqQHzKDAxyvi93L4z8y-2NuKuRsC7qKnpQNH
Cmr93Jnw37w46j1CWrS3a6d81ORHzCVWKfghmnzIGwf1Zy7r0jTa0l3sfXVerGI6K0Qi1dvxWmCbNXdIHn-F7eCFheR-7wd3Xe-AmGzI0nU3msaktwVj305q
9s95NWrm30wakHZ9up-m6lWO7FXAEVQGWjN0Ps-m6lX3wfSQWEx4Ot1O3VmX1Qk17qLO3RmoO3NmszjhUQ0Q-EojDSz6mPES_kXx1W
}

sprite $image203 [113x82/16z] {
lTQ7afmm48HXb3Kjrk__jWw3aufhdMdCZcEb-shvLuCsRLBFsnidDW0jleiBrM1ci1hUucNdpCdyF9SwxC-WfuVZLS3-deTJ5fivUpPbxYVkoPInOVQUJHag
uOIKQhnvO2KySnGusVCpyRX8KafxR1vErhifC-DuoiVZkUD3Kkhn-3IV-OZeHm4rhs7quBaRVgSCsXxxPt3pQP1J-jFKmMFRYNiC1uXB84-vtcEfmFe1TaCf
k02IbEkZ43DwwgZ7FoLV0dbAVXHY6HRxEC2hdv2dv7iivbPZRIMrcchB0aXIiZsMOaunvP__H04aTn2snsBPaMnlURTaUyqAw6HUtyUcBqqylZJnr3277rD1
G9gIlz8Tj6Qenp_pjnJ7Zw0WJydlOtuE1tw0640fCZZVGVXROU3lrGQO1Cuf-NsCx58Tz9GataEWmTg0lH4qx6CCl0t4UBt6E9CSn34YEFQNWoUHWkYbrbeQ
510_E0TF90VhiGG5qBa3P2G7CmLNyKxW09xvX1xl33hv20Zd9f2G0aWu0XBo5kZnbk00T936uw2JCaYU9W49AO9-51Z8IHrqZeCafGnYVv7P1oS_0aC8nwQn
vFy_mE3JyJdtQkDp4iDERulf__WvotZElR0bcqIMSWdQtzxOERUNOnVlA_7Qm3dYjR3vX3eka39dqJMVs2T39LVnHjwckP2Ip3fUtKvJbYdlFSqUPkj-olLH
I3Dq8QNoD4UPaGifWSNJP68D4o2aL8-2ZvHIZyTJBe-87Ez-IZX7ff5uKaez7f_GbYclxR7_aNAznyJ9s0MlXqsVCXWf7WKzvOVS5nvFF28STB7TrdZA2qT1
c0-stOLuoiH6mFa-nkT-Id6FwIaVYiTVNFGewBE-WuXxJ4zvQuyfBoxnAEWfN-IL_bJANOgdJu9w5Bu1
}

