sprite $image261 [219x161/16z] {
tPo7VkCu3yHPmVh-h_iLuoScsZ6z36Z8oixrvjm_Wu46kc9k8Ei3fLAIDV-GN0Wfbo4o_u2iUnW52h_QA1zIAbDbzpkDYiY4IlPt6KMfh2lyEqQX_EsDaYkv
c-_pkMhvc-X6aRFhHjNMMlqLaND-6BLCjWAN_NqUlEjWYt39tNjD8DWwMw6xxtC4MuSBDp1AGdPzvD2eN41ROAMq8K7tqjxdSh2QKifrtRWItps2vNqwWUNq
KFvSv58f6fRbD5G0xffpnwg0bNHIRKCNTY_I2TdGvwRIwixYV2hrpvseDOkeSd7tkWGC8tV1kHDq5Zxg-iXbtP2XobNToslEOgdxaRDoq_GMVcczFqzUhXUS
Eqvj5dFhlPJMM_vGv9BMBDRUw_5BWBkYUpcjaFNXLgwzbyc3GFFS8PM5Nrfl1NuJf7hkM9MGeKqVY1mfXOmn87fNTY-5XJ_t1xpKx5xXtI7Ba2f8u4LJgRBm
GRWtzSyThxFmKTT7BWl0LXO-EHF7h_rFBYwCR7vdvBpEmYV_-71AASKHweiZbrH2zlYQbk76uDW_9xTcpNF7xOFXme-MmTYhCBuMUZoFt7xtehSlV8xM8Flw
LKlWikQvOwKXMvZ5BrdlVOZFN5RiNhGtYzWouWC5XiHJchYyC9MoSsUhLU7Q9tk0WGAwh7hkXArPn8TryMCMGIx2O_sjvmwOjZUBcBZP9MpPE201Ld7amBHT
C4mGcOd2LoeLkbSLTApwEcKOkHhC4ta2XBUUErtIiUf2q31oPza8TznxpvtQLpkMt3Xs9fcJuhGKlwjxzIxjM1NojXGvd4MbSwUUqPBqh2vhaVFc8KVW26Zx
t6adD2k_PcfUcihYE6IO8t9ivIYSGVhUQvZM1HrB5Zbk6VHyuVln22Uu2aIlcXkZWMbQaMEhC41SCtbjUdDevzof_OGMjr_HvKMuyu2HDKp6pW4QH0xGqBXs
HYiWfSYTPf7yv9QBwG-rtji43D0weq77KfvApXdUSaDmoytEWJm1OzFwh6CbQvDsv59yVl9OMdcyvJeZA_s4vf-SgIuhHOwBFRdfBUS9x--LMMJLCrf-Ue87
pSXbEsOH5M23h84DqmQQcvtWz9fcitlP-ItdrcSH7jUiUSTAnxl2bpRLlUuLp4J-HK6UXepLJcZsrNiJdr_ENvL6RdGlbAD1lpIBQDf0eydRhZ2BN8MF5tUl
XFCOnymkBtmqhJyrZRxiIkxfYGepiN_k30N9maVJ-XFJaZs5Z3p_oZhSZxjNzRZtrnS-ciQ2ZfNzKgL4kBrpnuwGoHR-K1_YA6781F_QVjcFN9mN_OnVR6xQ
G8F5w58vb2Y4G7a1RlT1q6AGBNmqZGLBWgobSYZQKUkMuGQPe7k95Zuk4HPsBDmdZhVAAXoEwdBagcpXescCvgTaumd0JuF5o27OJywTbLQrPbeV7GlbXrVC
5iiSRgRwqtD7jF27sWdDbPdSjs7ri3MNu7xUlQHWQ5gVLdl6eR4tsLwQMjTGLV2KauOCJUksp6Mv790_dk79hUrAbg1xYHO-ciQYfNyapA5ZH9VqddBoMKJJ
Udcf77Z_U-9_frBwbCF8xSyYgf-rzbUDPrmWVbVZ2ukGJNJkY1V-tBIwzYt9Zi6-CaXCPYmfd3imYnBJuj9t9PmFLdTGqYDx--VEFXWkaMOM_dhwu_soFp0J
0ulFdSMGoKmZyzVFI6wyId3vKP-FrvOPoFRF7JoZXQPrQ-1ZdawZpmnYxRTpRZ22f973MHIRbenP-AJiqxVpcq61Z7pUVX0Ws8vfvYUVbcFud-XRuhZByFC0
EsPRZDpw6Rt-k3QC9lbMXOECl1rkoY9NfgrARffdDCbtYxTceZ6aDb0XQvCiSZYB-wQP1ghBP4CkZdlLoxhN5XYQ5XXDyDd9VCbwuko5ajpJb-WBKxb7XXtB
0DhoFd5Vhx3BGv6FW_JwGO2VN2LWA3HjeA4MshAdxx-rz8QX5X20xPlMp40JJNpwqqCl_9ymrLqmx5Y09foDO8wtiYaHpU_KEiVU8iCbOW1D14V7RPh3U0m8
_kRaO6XQ0ZGHc-TAEUuU1vLPNTYn04q65xXI-kEYuvMIobN29P8De0dXSZeUTF_7StmY-0-QvW5D2ZTMIU3R87X6I-apfXKpHHFN4tyyu7WWhV7vOwOXcXpk
COoKIoQE75zp-NhJgW6qNRXeM267yJQMYhgmOwsZhNUlwBXLblATZDAbfZMpY2Q_KvcCUALSQ1ejeSdXE6zyfYgpLJ1j6KtUlORiXQObEHf63fK7Kmm76OLy
JSTQGvDtB-RAXNWQUJB3sx5gRM3Q8feSpeTK2fEDn5bw8rHhhJ-H4wF98-VfRKOD9bGnWAR2DiXi84MZi6CDrSPIYrnID6hQiLZKjE1oe7m157Qi8PTLuFIP
q3IKrvbAVIZiMAXuEHmoYQ2mOw6I-bJAZPARjXyvlNs-BcjUA2XCfQfHsB7cYhfJYKQfcOQo2f5JCmexrckvqiJw01HsBCt8uJxNLpKBskzUQ9I-WbcLpKsk
3hgBQInNxqecDmsxr_tHclcfqcz18_DZkVmxq8n4llu2j6HaYlNsQDO8PTFDqRAHo-LRetcper3lYrRCfkBjqD0qzSZTjcFjdpktxLZx3uBRTgpzS-Vs7Kj-
xjpUDFcvS_kE9O_SPQinK_JcxKeVHSkPl3TQSlaJQ2qJUMkq5UgLQ2LJM31AENBlDYe9Z5BgNh_IA9Gh6cWvaNVcuyB8tMwVonNVWPRplb7waHCOPSqTXTth
zcj2_Y0GF7XlBWAqknebFtUc3rvdVfVmLRDudzy_Si87x_sLsdsC-Yy
}

sprite $image261 [110x81/16z] {
jPQ7Wjj024JPHblb_tytaOJFd568rl5DUdsU0KQ2_rDfVH0B5lXPrPCZgYAYt7y8KseVU60Ea4cvVffZTZp6yR1yoauRIFB2UMMgZ1-pe_EFNddStzy2z9mB
s1MFwWUsu99rQM_X6cgma_WIOizR7n_d60yJsdNDutO7rlGkIvbCylRuI9TOdhS-ldgFPI4YcVuslfxJKEyD30-MA1lmhV7LbH1vgambpE8KfR9ipOTuif1r
ycxlC6fQkuPoSs2EWhHJ7-ALCXjwCqIV8F9KnZUkWM-naFL1fG37szVGzKQ85XtMjdzNIhFVanXdFZx-zzRJCJ32Ox7xyVqmlulNqFJMrXFHS-g7jmCdSsry
fDdMFscz-2S6VssAxUczCgj9Y4uo4RoQZUtk-FnbHvPl2ziIzGFexi9lZ4zNh5biN1_EaDX_7YJEosncfQNXwM8tTTHV7SGw6RrvRvNmjSnqSwLrdwSwIgV7
_uor8M4hfM5UPdFpfPMVc-UnJdcaTbvVFxuFROFk6dGxQ8NTw-WrZyFuT9ETDShp-YgQzpd99FgapPFMZT8Qwyhub8Qxs39y2LYG_iwtasRMk04CKGzIptkD
atGEyAfeZxudos1cRNEbfT802dvtfVarIFr-w-x4nR7CsauZjPukK4Pnj-V--dMSPDTWplpJXrzOeYUjwLTfzfs9pbhEipZndDenCCOGehEsFQmrWCOgPlE5
fywhKE1fX-v2n13Ymzhs20uRgWZtusEANF9qHbvy1ZYMqpnfQ3df3Yjx-XswNF3in-jhqEV0z89brhRYVmkXgIf2ZN6Qz6_ZYrj_OMqRAauL-gW0nBMGHfw6
CdCA8KPhctpNgALswcSFsHKwdYPb5hO-MjjUdtUgYWKgxJD4qTxutZNu4ADErYy9VtoyFD1K0a0TzkWBzepdO94LhRNmLnfqhb0Bm53SltlEByPvLLE9DOX_
YrLbz3vOQOSnDYZi7SKuMJEMgD4wJ5CSdtA1UZnIscZf-98GdRLDmMYNVta7GUaaXBrG4cV2yjQ6qKpoNLJheFETsexloTC8FvJio2oU5kCKKPL-l6wCmPud
SWNFhI4uckCvSOLA0w1MQ18KuDdw5wDbF495gBLGXwxv_vjR8mYqo-qSq6KK0AHAQoHlhJfQ6cU7Kdj31XZhzimQWwFb_XW7gHGOt4j_preBj3HFBW35tj3M
hGa4MXed5QZOeV4ebM-YLAVHUgJbzeGL3tjryBynnzLl3ocSqkqEpzIWD1JLdECm3sl3Q0Nd0eyJr8kTwMZJlRtpl8FBxNZCt1pIIikfoOAzrCwhvbSVUmrD
UGjs8irAowjGDZvTvtXl5O8gf_OCCoCcfrbfHNLDUAcTt5k3Q-7S4ff3Bj2ijAvKAFVs3gr7ZB-6Zz9-QGApyNsGDZAMbTd7Q3C19TVm1kgFN6ajZMy9SyYN
LbHUPWkShry8zuIGbTaIHuL6gv0f7zzDEyhOMnBVpMkuOwTN-3-DHvoHu-oCTJlv-2wtWB3NDpdvDVXIdifBMx0-FcVd8x7bPJO_iGM_0G
}

