sprite $image93 [98x143/16z] {
jThfZkGi38LXie5jSl-t-osqP4sXEE-adJh_XqV6DVJffK2MMjVopUpjlnnB-LQsAcra_n8mplz9tRuYY4hplB-EfPIcwiRhwrYETYnDrOstrx6D0sK8txYg
rLVinhjNjMaR2OmzRsocya7CnfONne7n65BN5mILsE1ri30Yz-juGL1QHrw0TRIwfWGdO1rPWTUH5NWTTSiBl8wymEl82lp9tHC2NzNpTUo10CQn_htGWU1t
dGK30nyI5iZWJouBCQ7PTzq5-zew3XUIws0XjmuMcA1ri91S1mbiyBlEGduT87nj7OTvqeQq_VfjVMp4X5qB-f8Xsdiaw1jNfRt7mXjZM0SXRNGMzEBalpLG
c0trjY-YJ8WP29-6Ili86jhx0s4-dWtjdGGuVoGchBC0vpjX2G409omX-Fb0M48We8cDF1SEy_DvY977GZS7S0Wt8k6y5im16i9p8LZlvna83l0Gdbamw-SP
2HC0GtXcuGm5ROy5DrpeTy8y0b-JnuNpHjXZW0Np1SV25W1yJPxpl1DM0bZejyBI86cXoaD1K80jiw0A0cwP1LKGS0aiQ2pqZl_LM1Yv5lprnZjYGNKIJAsF
u1snu9a4dOL3ieBU2oi09BWnXAkleZKdU8RGFmHOCqJdZ8ElX1OAybzGuAwno-t_MQLBOW4F-BLWjoC8LcH5GU-s8Cg26SyGVv0K1V620JFKQ0GMHd26DG1O
KEFU6hz82WBtrZvgJVYe2WX-ITHRmprFez-CmBtr4FwKI2nmRrtk_Z5Uqfohthe9V4fW1Ewjn_KQF2HmR-Kgft9JnhZphOA2nQ-UiH0zg_P7RXzU5WwyOu4l
3IH0fqQ0UciFUvZwba60tgfnnn0TvnD0lLLtQH0GgBVg8Kc0UglMtmbwcMiXEmBrLlqTO1hcVw7thA1cDqRlAM5k6Dp8VWkCV4jGy-G5VjXPI0B6lVMnC0FO
MslofptSMmz9tH7srlFSvUbhGSRSMzUdm4nmRtq8eE52q0GOc0tkhPiy0sQ3U-lo1622Uoi3iy6zTNbsFXjz5lW7bDAsgh71Gcbo3nnBAPl410kht0zGHdOD
0WByS4d603zPAXYNWfKxGgQ_0bqR4xCW_c_bwlojJDcc8iEzLVmAZaz39FYRaKEdG6-Lubd_Cpoj1d-5nEjmGITX8Dj-r7hisneS3-i0uKbsCUgjcX76sg2t
9WHUH-yvWTTXAM5UHrxWTR2Gp5hV5-0XcOIpbHUoIzWgxIYlPAbNCrZlRIblPMspi6qgQtapctmAQta_--SCvGjPgWkd1Xl8hyD-X5eWgNN0HoYVGpvNy2y
}

