sprite $image366 [190x198/16z] {
xTm7agGu44PX6K0cnVsFksQSY6PxL3MlGZ-rJPxW2-9LactTwyUlUN7gyUwF9covb9AYrhwM_0U29PNlapUlmo_V22aycqpfarUHFVnIRFx9P8wJ5VduxKXu
y0d6bCjvKfYDNvz_WdxvIE_vJCq_vgUVO3ZaVfw9spEa_oQi_hba-ipRddvzzWdw9GteqxRdadzB28CDUPgPspCC9AVj6RPo6b7-_Y7A-ddkO_veUv8FQtsC
40V9WFp9Sw_rCNyAfvUgD9-bV9_E7n0Ac1nV_tPwqe_usolppvqyox_wr-dDwf4F_21_eF_W1tomFO7UM3vaUtBznyTV1FamlIB_-3Az8l-o1QxlezoUN2_P
dbolp2S5f5Vxy-QfNfl_mlHDdNz4-hszO_xbftxlVjds9FgzgVqBqUyjLst-AH9zIhbgyzyyqQTKrFaZVKfLlJsHFidp3qGlppzldkZr-Iz4hyy_HQA_mlOa
Udq-goTwlJy2_IMs9z1V8d-Yr-Up4FtPNoRxKoHwVVwR9thzyR1wejVd7u5UVppa583-4jiJw7i-ilmNejVddoBIfoJVda1_YUq9z5Su7e2--uNR4-WlSJm0
_HNo1tfv_cP0hzsUrLgp2lJ2V6fhZUcxtoRxhJMWX_dpP80Uvi-J0NgMFqy6w64-F1cWXtvk1tf-FC3ScPxxUUvZlJQVscoSp5WlsPxLzjq6oGpqkdo-EUoK
3D3FEnxgTuMDa-5wdlyvcgxloG3zjFohjRthHybmFS__7CrtVKy6w6Vaq-rzkawf7_jxy28zFnvwy08zzNUxGC_oiTPsZPvlpzfsaPxdKstVHNf-F5ZRPNgU
Vzi5UZPLg-VvA_LyYbBFX-bl_Qs_zVRLzRV-rjjNqj_w_IlfR_sjtzzCV-jl_Qs_zNMwFlyVzBV-rj_wMz_g6-kjbfBVLDzg-JRv7VNsZGxyIhtLSfYtqriz
-lDRw6srFhK0lq1VWkjua8z4lphdrWhyGdqDxj_nMxU3_2VhjyF_4ZO3-Glq5jrXOW7vpDSdVyJt_CVvwFMskDFu1FAPgS_-o0Rv2_Iskizc6MnFlRvuz_du
RP2_Lc_RIGpodwolOO0VR4-fFhdn38u7cRv6DvxnyQ3H9_y8d6zFhX--e0Jv0ttsJy37nqEPe1--eCZsdAOluGIRbJ_NhmxCGlBd-Xg0dTtENBy1DykVwoq2
DTkUN9-0cDtEN6yBuBBRcUkp1rYqFRdULW1b-NDzyK39ZWUkpmC5sPwZ_BaUP8Fob-hvyQ3Ly-D1g-V7WrJFjsTMw_dneDVpuu7hnTlpUVt2PJn_hPuV3s8z
_yORr-lpvthbyS3rokE1wvN70zThZmUg5nyFK2y_7fXUlpsHNfy_q8lohn_yHAy_7eXUdty5Ubd-K2y_7f1UVpnKe5TCEEL3zFhZOQolKQST7m-_rxVDNMj2
ijDyec_PkyjDB0Fz81fz_cEzhJBUEF-1lYKGpTJZuQm7lqiXoB_hGV2ouw7hmPQK7GzT3uANvT_r5GIlsPvTdu5TDT-E1_9XrUTFtaxwxPcyu_Ct
}

sprite $image366 [95x99/16z] {
xTc7Sbj120NGLvUoaF__svJr6wt7oDT8f2UuJ3-Ck0ngIxBMWy-bL6kJzuJrP17XlQ0VegftXQrzivb5Q7iItrbLH5I3SD30htzjVMOkD70P3OOmfpBOgvY5
ZuVrKrHcgHotgLpuB1QXno8uUE2phWZssrHcNHFQ7XtwsmPqqBHZWpCP0Ls9nWOJ3yMIZK2xld3lEFShlQJIku8631fabbJxrxfyJJw0kAIOnmrW17kAxqz7
qBOCNuZWN25lRiK97OZlxbQCW3RC4sinWXNoZUHr1Ffm17nYlf5KbnJnr5frGhG1FZIeBMdaAKHGMjB8KsjKNT8TyDa89BMaaHyJujgTu1FnzBsMDFA52EAI
3ju2duy0BodWYUftua0yjM84B19uC27S8EBTh0F--Jl1BDfjw8ZFHn3nKO1_Raa7FcZCvoSKHvxaytUYzpcL99-_4sfkSogOpqSmSNSRKydo-GYq-xUoW0C-
lwJT_AMipiSxCV02ZoQaPbxYSODlPeN74LY9nm-WocEV_dR-F-__9l-Vxn_n_tbJ1dwLxoegtDgFuVlrMI251bNUfSy64YPKvTjoY8465TxxU7VOkWrVmuHA
lDEwZ5gfsuo0GGF4ly7xiTng3nCgyixhyheElKq8B6cITplZ5oVTu9BcUPTjYRKnMD8yxzO2dOWWoRjku5iE446Efs0-4q7ZUxph7iGG0PWGvfsMH1qQ6cHu
xyUIgpFS2SoFuZKXWpk1UG5SOaanRnaUtGbgDJvMMD8wZ-y4u1bA-GZgFBuJTHxVYJgFxqI9ZnLVJm2-6i6O45LvV2SOyFK8H6iylXEH_oG5Dzo9j_nyxL6h
ZVgerxobZtt-Jjnuy_WKMr_I-Pb21tCft8d1knEOIs591--o5HGOGJSNCFHgDVruw5y
}

