sprite $image115 [398x285/16z] {
xDk7QK0n60FXvxx_nEdTQRHOWUzM-44dP7pzB-gOxSe0RQwrHhqYS8j7HhdEWZBM2sVZ2gMl9tBk8QIUEASFrBa-ev_LXv0w6rSeRNt3F15NXB7prsqNTQoD
37qGHgG-X5H0szLg0-BA3F9Bse5x44Q0FWWZGXzQROu-X5H-N0cfeB54gpqmbX36GNqGnbmR6VeWZ1nz2AaSVPX1WlGXf7BquHOv-X1IEVemWyJgGqZbnvKP
961h9upmk2ACWATQmiZNXnaal-qAgPtPhnTGsZh0WR54I1rekrfjc3uyxkNhGwlDrmTXqCVUQbCmbhGLocossYHcrMhf8wBLqeTMInzRgnLNMkslwPKmWfYz
44QWFhHQ-Y2CdL64L9G-p23qSK0OueemZeubX26kzXd4FOGKVPIsDkWZfzMAAwtMK-ssrTA7LaiVMwkb3wtMrhw5bBZIQWD-SMgrcMsNCBJTNHZqGHZQRkaB
evf1wEDdOT276MJEMtREGqcI68IXHr8j___1bqCFDhwkZ7fsAswsHqQFbgbnDGp0noSmmaqcB2dqtKqAeJBd8TJbVRjQkCam-uJBEyOW26lsxLHX2Jymu7RO
Sj0yVV030s6o5iNbIyxHxV9tjOXTJOWv8BFU5m3sS9CAqys9KmzSlLf0aBLpcnJ2TtjJYzyBqWOQ1FWWwshXAhlLEFwknrje47IxFC1OQgBGeOgX15axRrRh
Tqmpf876K-tACE9mYTfwFY056W_FsYK6REPtznHQbwNpe57nyQGOn4NKObVx6bSnZE6gbZ-h1RfMHSo_DD2WmGV_vPxTYwSGfl97Dh3ZGuBdhFcgHGbvrPdj
IfneBC1kRTx0geU1w0qd18rOiqvOo7D7rgo7HanrNvU7Zgp5mQUkUrRpbzifuyA7EDaycHw4KYnziO8WQoSRMPC66csE22joKE0ZFyelCq6ZrePjNmNZkQhD
_9YlXnSET8KZkqDfu0bBCWdqk53WB9RNeX43KrYIFp-com5je76-cmq7rnnr9eSU8OSx3TnB4p5JZwe6Wrt1vQyHmHIDLzdfrPWvrrxL8B4hlmI4rdhLgRZ4
PtUxcTFrg1ko2kpgLKUAQaosgqmoFNJVFrdfgtgBqC5sbLKEYlQgFaYS1tjSPWqNwqaDjlAmaj0MSCX_l7eoFZAfzAXru5WUhknu46VZ8vDCZtgsH5LVjeRs
VbRSPOnTsK4D9doSKUZj2NIy_gBFmqTcSfP7WyBeVaHZ-Qh4D7naqkfXnziQMCU9qB7uoEJL0sKp5jq-3Stl2KPPRlB9KKVQL4LLBGuUK9aDAryUWezCPZrg
EDlpKMBbZiQqh3sJNOzpyKklHyox-yWRSb3fKO7XGZ2H0MlKu2wFq9KMng17Q563NezgKh5oH6DqKMS-HWzucmp6j_RER4Tk7GQYsbcK-_z_zsvPPDoOGBiZ
CvQdwdNU-i0y54LXRlmcQYH7VGwEQhUqWrHfSjyqFH6iKwXYEVnZlZCBT1rPbyURGu-QwwrPR9lgmtWO3UtT0zssGUEfvMgHQDyC6klpC6RcjovIWuOZ3__N
7cs58cNGe3xSMVJDeF5GVTG5YfH1ut7wY6KD5eF6W_MHsm95QWAD5VRQKxrrLslGSFuy60mM5WtoyEzgzv49ECXZGf4QDFnvi4ZPDBpB5LdODCZ3lwkrQVZp
e31i6luuMAHi6luyoCAcuSM3HSgTXjtjaeKt3VlpO97ofc7pu1Xa0Wqt7YnIDWr_VR18sJG0vy-3HSgc0H7nva4MzhSXJU2c3nQf4P73Nt0M3v35cKZC-ENt
Qo8GeJv-9xfz40aX5EW8zl-HnAjSaSMW4LBxFutQP9u-01Qf4pH2I7BySOWR3x8OD48SvGhxD_7NwOD7Rvj62B4E7lWcyzO48YxTBZ-CFGrB7m0Skbso63H6
yiNw88ltQ1Zw64IcboiAmwPXwSE11pyCayQtRdU4fuyJyy79D6nzu29za8LDmryV58PDOoIsmGE0Y3Joi8KnduPThiRmwfBJ1ulKe66dK1zlx3XxqGYnUkc3
HMhGi9FQZWUc3wy0iZX1mpXzK1z36AuqHhUxrmVmnVMXVVEcOUj3fkg3HUe4ZJ5ht-jZ8W-mI1aqZEHVzD6cweCi31gdzQ4pWeMBb3yDMn_DHn_FPz5h32UI
P7zGmBSlv0jrLz1-8Gj9mSW9VLG1lWQFArbioE5yOlNN1ukKdTWkFNq0NwwJsdepM9mhLv1l-cWE-dXmaKhXjv9nTFgu-9q1XM7hGt_LXpei9b8OXZxKLHyK
ndbzE7IxB596oi7f0quwNxz8QGbp4u_sg1_pYXDzWI9bNjKETJZeOt5XI0gN9ED07mA1JWaUAOmIhaeiHwSFWKuA7YUC6gvCgaUBS3ehmBEAL0oNnNZ5AOE6
0u-5M205XvIzFlRUcCC5x6e_dRL3LNTm9l7W6EHKKjEZp3f_06jVxcsIWckIw64cdJ_0CSW7tUw8JxbYLslhmut7-hDQwiEVnIOv_C5aCN0uw6FThfRwyEzg
gO-5LjRyzI6NwODThPqC4uVuVnxYNwHA32CiLmjqjRxboe77FOMHmmsJv5fzB7svvv_ee0zsjJVInpANU-nslOkKvd3xPBbsUCKnoAHXINCeLmkihBdhmu77
EYjhx7QLHMgVx71Lky3b7lK1tTROG5Z_z06BX__AsaFA5Jxd8QaPE7owsXWSiinLhOIYky1N634idbXd7GO7ZGA3XyFAskg9CsVj4cAHa7T60bQzt5k_svLG
MWwvvBq-V6UrwwTCqqTjYf0X9U_B5SSWVsnOWb1QRZb1H_g2AslhNzLA5KMg8Zc49e81WsCG_suNhGaKkI37EgvJEeNnHnOJ8QLMeEOKSeWjPnaq_2_tUFgG
bak5b5X2LctLeC6krkcg5ZLMKMY9XZSyno3iTj5gQb3aZ463NUtaRhTMVJEeBGjGSuD1m-joR_r4erpLAle-Zv94fGnlF7jbpV-g5atEN3Ubag4ODDZLpjM7
Y9u8a4kLGOD5Qgu-87ega5YcqkWENUqotIwW9zFQeC4noDnX2VIpT7QrKrAW4z8fZ5dwyATX5oacDNyQzieQaw5Mf4sWCQb8KH_rhK-d-x3Wi6JtwTZfBi-B
gOyQMmgXuYeQdS8uyOgpfbSl0vMHVktA6lKnQBnUciUSqQ1nyUKUozMWyTeaXYWdQ71MEtlMFcZyowD5KPWq7COWB5U3ncjBeZN3eC4YvJ9hhx4F6iKwc7IN
opsMgneI1WthOD9TX44UBOOwQ9H-t5rrhgpvB2PAJdtGU6r81uVpxYKCwaFq7nYz_qVZMtSLOZLeN3OtP_PBpoN5RpJ-YTOGFwBHsuoZDwzg9OPlDBv531e-
irhge-Kz3JLei4XvlU9iq99WqF1_NipDaX92DsYmIBal9aeAC6ZuhwonsqNDtQ91OVY_ueJ-U-9e1WttMItrqIM67pHWqF0J1eSbwGSD4J5eE8v1g8_qamOC
6dvTBOSb68y53Hh-HOfxxJ2-3USYHNtiqs_ql9ZFelgDkbfkblGR2OFww3SI1ijLlz6ECnSJ-vs4mM79ZOeK5nFxZLRM-8gptwL8CR5fly_A6fDbEM7y3G
}

sprite $image115 [199x143/16z] {
rPc7SYCv44E7eRj1ZlJ_dtj1Ksiu7ItLWImJcxFU4dYYh6DEIjHZ-sIB22zxGoIBH-1vOueIY3-nj6kV7C4WogPzOhPjLWq4iscpYYE-2wBkD8hups0N-QOQ
my3pDf8Tnz8caXq7KVUIh7uYwoKxZkLz93jkrk-RI3R4gq6KdIIhb-zwoUhbkrwoUlckbwnClkibkzj4A5bDB6qZMVr4z9BLDskzP7Ti5YMhJqqRIFPttKy4
en1CH2tP7IUIBHQaRY1PsVr4BrbzF6yWMVr4z9BLotV-JNOJ-Uebgs-MNhBwrBIHPFKJqKiMK4zalMGHRYMRRYBh9Oi8gvblUaXV7CwNB17IyHONtq_cInOH
JeIS7r_7_mmih_jm0JuYf6BXwT_lAEKxNxBlYvIh1n29bTB8TxvaFNtnN7xi3DBxoNp9raUJtAz1EEgdOG0Go7U-PDq3UFldol5-60WtCu_0LFbIii95SXXU
hfz9sMPEf3Zqro4EmsJLXUUXPCKf7uQHBWNNwqpgd8bOo5C_3CEk7m68UWbnnlsa8OHXYNZ6V1g4foFLAV9jJGvI4uSH0UCPm4qX4ylVOCX142L7X1MFHp9F
9t21PeVsVjB88OtdjvNxOnt-SQR5ePHlQtD0_3491oAGwTzWjQjo8kqjcA7TOkw5c_yWccGw-ROs014wlhp_gU9Uj6-kjtaSu19J3VOWEtLJH2yEMviAuhNa
KYouIfv15JoBX6TYJ6pMO-F1ToyINzeWQa3KtJRWqEyaUrZY2qs8kakCkI2PQkBLIXPuRcqs21l5fuvKGvd6JDxw9y4YT44_-tGEAeNZbgQT9p4MW1XVDqcF
WXXBGAvn5pK4CPQ1U364B6ZdIOmr7Fffjtx-IMFcW-X7GOpjG0Z1j3qv6Wc8iHi8Zu8OGf3r4CJO1eHz6c40qpZ4aXrZH6WFP7wVc5QYym522J8VWcd7KV5u
UEwEPq20tpGAOXp9t_yt2oSo_oY8yM_oDOi83mYRDH-265SAEX-T3cH-duXnnTfh4_b54CJWHAG7ek_J64CraVKGn62gT2BwFeqncAITYFuenXXCVan4Uo1w
Y346vTjQk7OY-Zun_Ii59-A2ftNDJNQSMw_7jqd-DX4HYBvFZATl8IZV21TFH0-1V0noJGJIYUX7SMlr-2dMhedumedWjL7OJmoS271DH70WuZu5Hp5EYRvm
8ksrKPGd8IXVX3in121YoOx3-md27KtFePViMBu0S3r8BOXUicFv_WbUb9P-59JiowaWo1DZnxoZ64ZsEVbU4JHhlcJ74tcrMVe-bODPrAm6YMIPNWzDhBq5
hqr4Bzcb4r5ALfaYcOXUilCd8f6iFibURDOqoQwMhqQo-fHdcmKd2244abNBTmmI6K4EdMGNonVPik7nFPrarqy4GFRYLmLLabqlNtYubrojjTOrafqlNtp7
OMuvkHD385bvyeyJYUemvsd89QkNh_ktkZBdQGWaEtyYtniBPiJGIrO_4RHlqs7444jMBzznkk1ZieicmlG1Xb2o-jZxXrvjWA6IxFpxISav-W13A5bz-D3j
Z5Jm9CPD95czVEjvFslzC94kb-ny-TRpTZyztZUhooKx_tvIokrskfTCWtMvPEVB5zRlpHstcemOMidEJsszjLGTztlB88PUilFbw-v-lzsT60h9hfTlZzJV
OSZwj7uYkFLA39LarzzFUZtG6a0CZMJNJwIr5l4UGoNPzVSJ44CwYlNtaqx9Rfban51BTlsBmyu-RPk2Hidk79icsRy1
}

