sprite $image155 [274x195/16z] {
xPs7Tjj834Kn7Ot__xjxXlRIWYE4efmZQpYyMzABxdd06ufC3A-di72DyCb58bd1TBdeH9GDJ71HHLKsk4MOdAoTMoSrmDGqNRboia6gTvnWkenySoAKvpKY
AtywuH9WGZBBXd4owPADA9R9bsoeSeU9bsncSR1E1FCyrp8-rWaLE3kXoHvpBTaY7lxmS8tpB12VAOedeXpXzCKJgXp6ETtFCp3xJi84ZNlGIGaJDEukvolZ
8Z_6bd6OQ87uE6KyUkDUJaALVydu1vJ2qhcS76tSvui7qmoDky-OJefqBYUcSL_cXD8OZNivSHR8DJk5vNMOBeuJDEv19tNMWV6TK9XqO7md62Pet6FdM2vX
giRriPV5iouGdnOcNI0-d2Tet8ENnRzuEebDteWl9rpWTwXYUAUSK9gWSG_6fFvkurun2KtU5JL5F6VZ-Z7XF5NZ-kXhBtO2ollpmfY4AeOHOX9dQzpzRL9U
rBXNJ6pZNZ6nZNl5n3Rk5HExGAwOsCQzOc8Rzug97PWh9hPnhvZOnhrYOXjtVFJ62SMVBP3fOnAZQToJnWJZWKbXRj4qximnYKqCiySaL9QpeuTYmgegNrmn
ARfonMG3LITqWW5SM3Ukc1WZCpZHXsB2QfWf9jarOfa-9gn_C8yIpewHYPsqi6TaOzwOY7gSMuc_JKHzPeb9kMT4vAwQMM8I_p0Y7KIMQPoeiqsiaTOQJjF6
ghPq72CTaccSs0Nh626cUq6P82OKxnX1Ni7M72UdLiBnkn7-G5Jnxl1CeCGQuOw8Bik2hOCycnCA0A0c8rt7PcGA9rO9VZSYomVKk3MlUKwjf1eZk6M4cWXD
uiGguMICj99rCoA2ipWngyGQQK3_6z4kR7E2PtPYbIHhX5Z_DxAiJbgROCaQ9SqQOP4F8rsChYcQmydD9h56I4Gt8yl7D-3fdLWbVnYHBoEoB7QTj7PU9uuH
D4RCw9pLYLLYZT2M4ToChADpSYU-4RvdHCtedDc97HlPGh8PqKyZs-XmExMJh-Ln-u9mVQsBOXCLrIyZkagXapgnerA-FcyFP2AhZ2qeAkTrObv04AC4Rvry
ZSwgPbidhfEHVNIa0zM-66eRj7xlBoFRmTvtCgWGQoImUJ7sF2Qo6J6ZupePquSr0ccRcw-OsD5HSphPf7bd-m5zM2EGHTLt8fyviQDZdSYWJjGnSaS9erad
cn5xiFUTZEV36e78wiMamw8Tzs3VeT6SgFf6EaqxteP5DgCZzqQdaLg6ys6DG2GzFZhS1grYtJNIIVJNqI5tTFpQ6S27RwHJxyN4EzZB8ojs31--aQYwv-JB
oFg__NKoWX3VI13jEADZ3_RR__RMoG0-V2F0gZinQImYpZMnryG3-72D53NuewEw6J7lsBzrJ5IF6u4Ykk6E3juV7Npp3QjF6O7Gr23UEjaVdVTIedhOY3sg
xQyJxUEYpkdatMAYUj289RFdn1p6xhwTX6zPnFga4N-T-ADpxvgurFUAYUhFZVZhXF5l1tlHdgCCgRvFJ5IVCt9mdVZNnAiH2Bc-IKpqMID7rWarw-JscdWr
abg0MDuX9gg7ZI203tenSQw9DoEB5hWPdT-AYHvbzyCs5DtOFTXR8yl22I3Ntuo97cVtGnactTXjOckaGn52gSusUKyXBSBV2U8eSGxsriYY5I2Mtud9OHcg
oWbsIQBAkSf3JInYZ7Ga0oGd9c_beyQK4pn2gAN_7nzS9ukACVAvJbuS4pqAHZXCeWURs1hfO83Ndatq89pWAR8yTariZNGOglTk_JiCJ86dUMoTT2FHCUB4
v3Tzj00_m5ydpP0XYMVaUqn-LmWb-269lD6nHW2QPyIFoUiNI8P_G6PlTAmH8CU86vFNDsw0VqBONoUrbnawHfmU7g1nVIBkDd49K1qZpkGCqRW-YVVMISqX
ox9e5cF4ZyaWZUjJzaSdGLK5g4h6oB-FYHx5QTnNh9DG0I2KxqQGq3cklQHn8nXUkKvg2R1IhOyEEfCpGkFw9DwDIVx32FqFEe-l3T2uFrmdjqPgIeqsdCaP
eN5zGjizs9VuPIH130btOZ96u_h4_ODzwKQGcLh8J0Ko6IUYbb4Qz_brqiaXLcRg_sDCKCpea5h6QTpdrqa525Y8SsRi5c9ij75ySlHT6jSdDFbh4vUOun8B
rzHwFfYgMIVEv0pGk4-lav8MNY9WY_WH5gOSp3fXjOpHkC-_Jr13uWL3na0r5yXCJ9X2fGrdcGpGk4-kamHXMRGGz7X0A6cr46xM2JhBP8Z6FNuweHR2abgX
q7hPj0oPkfjoiqwSqzeGZUiJn7jHBKY4qEktAy2G4Y3tTGB5LJ90unurylslBimjPOJKouOAvDgwd1ZHEvcytpNkSLZLSy9OQyk90c1UowP6m7Lq8dMuAq4r
ZDMu_lCLrLydDH3c1l4p9YNr9iwb2-b6lYiPft5z4c7mxs8mfSpC0MfOpwuOe25H8EPkn5LoqCTEuxxPwIJcFX-rgsFc2ZKaYetN2beXnyWWZNlyfYZ5K9av
nGBT0r64bkgDaNRdXutKkCTlYd8DiSUZGMorbqt2i6QaVI8_C28jmFlYhXFEqDkcr0ILUaw0LYFe6dcsSSTP9nIXh359EH4tw5hM9dQCFDUuOwsJ5lge82Qe
N2Cp1GY5c8oHpiD6f89Xl7LIGa9c38LpxgK3XJ8pFcl4QToXrWcjwuIOO-rBfLI1okGO6R9nZp-oXMiJKv-VKbG50Z4wHiPitECtHMk8DGDHAn1veTYO72EZ
DgvFzDO9GFfuvgIgQ76C3Doun-zYCAsTMw3laUnCpS2D-_nTZ1mHe3XTCtBZFl-CHOaGMpjY10ECJqJ_Hd6jzOWHIZ0--uzi-KQED-xuwqJ8Cp9wupv_5qF8
CNAUnZt-9qK9TSy8PpWZYRsSE4QynZtlEj4T8qxZddgTwBuHId1kidv7H7qZKk3i1Dr5EgPnpmq_RWGZp40ILPK7Z726IGWe5IBj694Aiv7vRqOem8HKyOqq
c9BGN2CL9YMIOoI2ORvr8cACS86PgQ8jHBIFnynDM0N49jzkrbs4GgfQuVNy1m
}

sprite $image155 [137x97/16z] {
nPY7JlGw48NZDjrxt_zjBoRMCaHOAB_PsQD6vyifGpd-KGcK8HrlLnFzaBHtSvHkPYggtDxhIhKX7IZore30LFM9WlbD69bqQWQaL8vu9L3JBqrRgCRlPM9u
bFZU5ZRzGT6zpJXJMQE4z7QMOwMe2LLNZfK29bJeWh7KIr4IwWsEkUQGoVwEmZLcil4ecSnnt4GfBxhdzr4mQBA_er19mULOdpXuoJsFhuehnpuAfjXoh56a
_UDaDp1MjpRltlDuKzRtV5_sMTeSEDaroK21ZNl-nwQKZNiUR8gVRBGfwtB4cxAURBmf6R6sYH4WivzDIQ31ifzDeJvo4rqepXIT_-XuioaJP775GarHctfF
Kx87SIWIIk9DyI2-BF5DESbO5oXHfamG1cJH-BBOQGgbfoF4miJnADCK_Y0vqn2rBe0KZs9c9yciHUzTY018R2gMX4uG1kfTM1a1C1XbabIR8DQ5kvqemMKv
mpb1K0R8evi9GIpARAnEHqG7Y5at5Gn7UO88yYT8xtsWS2ZA114p7PQmCPbzWeny430APKO3VP8088aDa3whCb5UJJA_VfAJv2mfgVMlV300vVdLZwmdoRCP
9ug5e9XzWHoP9udI9ugSLUcpAWFkLLKn3_AXTcvdvWCaPr5cLVorVG661paIcyryvbnyLGOAhVBPn_0W1_JvwXFbCnzN5LZaiu_XGSx6kdnc6cxA-Cpdppay
o97GklbyV5K6sr_cOxO26IfiTit7J_dFJ35RWanL-PxFG7dcmoqtn3ymnLOWNk2-ZU2tANDj9SEsAVQprFZw9xdP3rNv45T-O2vxfjX2NI5z1sdT_1FJLrMu
qkDXBTM5AHiSp9IFgqfPL6M0zFwGclryzZ6wr6CfK8Soy-5A__KFaaThRZxxvO0LXBygVihOilH10WtnjYcsaCjaeS8-7nm17OS-9WWwKpOmkFn2iRWg6HzT
_viWYvy-Tr9fnqhhgfoNjJPAsDg9CKnnyTos0o-3lLULElW64n8pepFbRYhvkAN2rtpACJ1Q0HPXGjVP6noBoTwfoWYbWLIW2lA98dPgTxBtgmAf8W89L1ee
wEBPASVzghHc5LffnAqD52AzeEnFTbqLS_aa5025qeJgMPLhFEjoj6DFoJyqjrGR4BU2Z1L7F1UIPJdIiIlf-bKL8Qoj3aCAyOY7O5fszvxVLsxfMrMm3KE4
SaCO89vaaSfMETPN1IjHAoIZAe80w41kt_EjgoAj4PN6r9I9_Bc_Ezdjgp8s0nM1KsD2So0tx_d-LS4A0eJ0XPqZz-_vVbK4QaR8IaGEPEEURrI52Kihw40s
9hjL5Httn9Truvvl_m0Y3xAQR41L1efRpMAo0LKPSY2p7942EtK5aNe4ItllvZL0j1tXgehKBo2BSaHLPKg3x5XVbTudI3xUg8IAP7rHqrYKuoYa6yVZVm
}

