sprite $image168 [257x209/16z] {
vDU7SOKn20JX7oG4z5-mSpZdREjvlnfsRkQElsMhnW4s-qBw0UNPry8E85jzfoQm_cfL0rc_IaFMhmAq_Oes1Lxzid9a_MePiduLoFfLJMJzAXrPlrg6h5y5
idvL0r0_OWf6zQSjGzQl9h9-LGDPlqf7rd_wKn3zZIQoVbK3MRzAHzQlmW3rd_vHjkmVb0DPlrg6h5y5idvL4rc_Ij--VjeKUFPl2sJzgWQoVfM-u_RJfY3w
RmMoVbLZd-s7JO55jw9DmQpUoDoWVjGKHEyd7Lc_2c3zlpy5jdfdDP3rgpHa_IgCMB-gYQnVfIFhLykGzQluplhx5DL0rg_IaVMhPSZwLI3hLpMGzQjqOFrV
dmAl_aycidvL0rc_IeVMVzxUcQutoiDWbCssDkx_TkS98eejc-vj31bzw_2FanVXOwlfcw8yNZxzRuioE2Xr-Y_U2eW9b-kd_tZFZ9YPOBv--jkjG04mAPH6
-g_V2eYteXkK6V1r2cO3e4MGyBKgZYM0M-5hLHWD016l_7e4ODa042BBkhva240J8Ekw0y2NGa2yAe3rLje8NYa5B6i1W83uXGYGh6iEG22bz3e8YDUr022G
ja8chSkdtmD0L0Im8M0YkdZwQm1AG9y35YQwTFgR2SWGi2Y22wU_1Z15Im7o3G4HNJVz7e3UQa042y7s7D15qwyb3m3CT0Emu6MV0vz-3y3UVLT5uDFl0QWN
bGZGdeEhfRyDO3K4LIkuNlez06BYLH5SxJdmwMy3G2II9W9aGt2bzDS0a8XMNcMbHYjGLxvI-Zq0W8tL3G5JenNGLXTAVvq0m3i29lSSE0INI7yD0E6EWFKo
vGYGcRIkaNujuGA08Y3QiK2m500BfhieNoFz7e3Aa2BO00W_XiH8o8do-TFl0T0MWMIjW0M7OGXn_wDV5Pmz_GR0oT2ot5i1imA86ebgLN3szDS0hBtPSx03
843YXY2S_lOz06Ok4ImA0CTm0v3glO8pfzy3g6LeEpqCAIKSPv8RZrGBmfa__he7RCjWfYm407S0ssMOmPw37S6PRz-_1ZSJuDMrWXs0PYD5QmLWhU2awVS0
p0H4IWI0yq9Ik91x3ixvyNi0W5w6B0G8B4niPEfMSCRRzm3C1BYG8RtCsYE5ZqIvX_Ildo_l0ce2p2f3H8Q0XRH7iaS0s8SbagpV1u1EXZ1chqJTC1B943XH
Fjtjrp9a9c0o1AZ56GAgMy5p2T11x_-q3472P2Qmov3g8B5U9bfbPMAkMW4H2TEPFlws3CsBcO1u6GBN8ms14-NptBu7e4PSov02G2mtZ8ICW0AmLs87lV_x
CgJJfBiCnKs6xey7wVtBCiCT0GazLWMd-VYFPSXqC9SXc5EnOGIFxr5Z0RTNS8RRRykGMmQdEm3IoKem11i0xH38x0MX__HhyGC0aigGDu52Xc9yj88DW19W
hWMXzuzVYmvbo0WWu3Ih39M2W7S0KG5uGUZ_zZq0ZVQn336N29ORW0Gu1EPYj4AV0wQ-q-y1U1d2GncooscEAIKO5cP4Z50VgdVzyHi0BqF2xkDkov3Uhm9G
CcboSsP4VT--1s3MGxHTfMG4MZ84YW26e5CaTiKG_88W4Ay_MUHb238Pad6OspA4HOS8aQMnEaw_8SeiwuyMUHcoztnJXeXt6N88t8QHFrJlC_qUWDxK73uj
Gmy0maUYt67wjGYz32Lh1Kw6Za_F0PcGYDSM0YJQDB6xz6lH4CWIKBt-9mM0ayeGE1aA2-GdQSIAu6ZKhhFqQz5DQ38PAbTxC0yXFcHeAcK8CnbYV22WHYjW
1TDJ-Wt0C6Oov5jySZ8K407RCgG8jWWSZjfrb7uFe2r3w6Ke16i5KigGTOYDvE6eNKVfzm3C13ueGsGob90vQmNt5f4ZG45h1PsatmDO2N8PAj_pYPkdvni0
aw6GTmWModuMdndSS_3qz7i04lM7v-d-egU637aJY5CkGm7qiYAGU0i8w4sGQmLTfDy03C02etrzWibG5lYM3453XcQmNNK9msRB2i0VgZy__LgIXblDS_7L
OIP3REzvocI8cZAa19Ar0axQ8XH0lIfuSlgrQ3xuXG5ybw45jNO2jBPaQ54RT9TX1m0BC6tFXXFbPwT_bJ0qAtnAXj1ao6SZZhT78AKX2Y66gHBbPwT_FFuM
hQOClNTwBk8GG4X90MW4KZPVe_NCz4_lVeiWVqA6c7YN8VSSA03RCAhs2fwKVdRfRxO2ao6Qa-fmSNek4WEMCYGEWH9G0FLyZLPNwVUj02QJ8KPCbGpPwJcn
_jkTdcjaOb8_EDeh-FFqOpFzxLOGdGn5XBOCGLk6zB9eYpZSC_lRz2-V-Kf5BqEBoH0tPOXCXl9Mi5sID-Ph-ag__pfnK03LA37T0K1BXjXawBvX98gW_Hpq
bNw_Ae34xTDp1J36JOQYNZOP6gTKB2GLmM4hw2lzVbN0pTFpaCiGR6afPIYP3EfbaLMOsBU2FG8atQJVjmAJ8IaHm84CKIL3rY6aELz3k3ra_7i81ATlVRiq
c0cm7oLkov1u6R9isBcR4O3jmz-kSY_fzpMrHuctVsOdGm2Oor3O06WsicLK0aD0j0DW8f9EqkzhJ2qPWZTaA0o53Cts0htL6hM_MYmK03CXIGUzlzqAtfQX
oWHWCHb2n8IGBIJNPHYcgFZ40Em8k9Vq-rgWEKfyB4EGIXa2QmMo0OZH0T2I7qt_Z_-2FNkAmOyIbp84BHcovo0g06e2w2tzTIlGRTzXzZ8axycGNKuAu1QB
6a27wQ_tpDG54cOoH2P3s90XTlCrqnHJWZIa6a2FwVUju4Y6MgVd9aDKN4xf242VwVUje9OXRCaGv39KRocd0Me0VQRVxvd1LCXGTAF4FDaeiPc0oEeMahy4
GEAV_BxTPSnbQCxVyxnMCaIyov13W3yF0CVX3qe78nM0vZqjw6K82XdYIeRoTG29681kq-z56Ko6t2Ynbo4ua25u043UfxUbx_JxLe3Jsp8KrGQz385r2Bed
04K9I9-z_tXL0Ee2xL7YD4Icx8i9I6KetGBaP0Zs34ZNwVSL3cKepRaCHJGJE98X0Y1PcQNxzFjMO39Kz3SlGt42X5A6KW504J1Bx-dtDSLeCiHqB4C0xyiG
uXS1y3myiIQmfKuzIdoN8MpAqDnO2FMVVbysNwCoHE_8a9wU_vmC2Jmh_VMX-iTa27vKXcWUkYYThs4YtgeXG_8D6Ues_NvLO38q-r5Y4Qb-BE_R07I-gvyA
jh196ebAXiYPGFgM3FdUtqyhy3A4NeOi6mq0Pqo_RmKIsp9K3I6s09mo_NxFp6Ge8LDZb1WD0LK0pjJxZ-ThvhiCfKs6GYb3i2L5gm9mrlJx-PevPZ8KD0Iv
32N0TWyuQ_fzA_0ob8qIEnbo04wRVjyASXb2n6GoH19A6P9F090mdAJq_7TM0ExrRpAqD02SE_s-5QWCrVCrWybG1U3iwVUhOv6M345CHm3EddxV2eI8YQMU
jDy0G0tWvEdtDKvnNmPBDL_J1d25zBS5GLQkJiy_283Fc7uloYnj6V80hfF-Uhv6sEqFjW1S9Fs-GlldAf4R07pllqQDgIL3W6y3y4D-vsy5R3A4sEu1bqk_
RmLUXZm0r_klLMF8PQW080RWSkdtecmoH2aO09HLSW12qt3DqlcQ6u321P1Ncm-uPFhzV4qeP4YOO2SWrqr_FLzZBY3C22Wx0Bng-lsUMGR0nWDOU1bUecR8
P4ZxdqvTNZpzViyi0w2LXjUfCRuq06q5zC80j9Z_0_WFu3y0mfS6G64O0hqg06GLdp6zA80nthTz9bG0BrmBAO0NhlYd6m7_
}

sprite $image168 [129x105/16z] {
nPa9jeDA3aEPggp1zFvtsmE19ExvVmXe0U-86vLbdpUSquGOX-SqDafSXgUqG2GfpCCJcaBSfPZkfzyflYNsyMRw58l4vG7wHS9yE_qgAQRRwLU9RNo2Vet2
8_Hh56wdNoNryGdwDGeFq2yIbWVe5occH-ZNA3n1lqRX4VhrIJv2lqRX4Vgrg1-WVr4K9eX5zqPXx18lac9wWFwfACmGhvMuF4A_Hk4H-dLdUuH-tTcUe5-B
-X7wDGgFqAz5VOx-fTDv7a_HFny5Spb3__nqjetf1FtJKR2TYXFqpqR1bfpYCn9csxcc93uYfUrrDVcC0w-hxJKP0TrFmRaU1e08ojQjzDVrCA008e8tfb5U
NtfbG0mY0h9r6_rDUmXjaIyBQTr4_sCWvKpnPO5EwmRwnG3fp0D2qBg3VZL0EMr9nEj9_fn-DH0W9ISRHP2GhD_Ihna0DWlPXWxA9Ge_ebzVWGGIL1zQW2PU
5lH3-jM0qoH9B0rBJmJALFW5_VeJAD_0qLfAWJ8LVa6_lW8vSuy-cB8_Kq6_eLyDW9Iz4vVrcGgWz0lwrO02t2Z419Bw044fwWlfLmCcEabc6rfG0gcqjGyc
sjRbzEih44c2CRJeOSG6nDb210KwhOlfrp8w_du4bfP4W9GrJ46PiL7GfVHh2ENFE-oH4a626gUEiCfKk8h-lvQHHEfu1JkG5Z5BWSs2qxgCVZK0a9Aj845z
0G5cMGpklyE5zEip353AFdHI0kMqTWkslwU2JjAlIkQn4n9q7rgGVWycajo1y3qLh5Fqgt9eNjF7mCNSqBeH06bxMaYAh3kRhLFqgu6nbX6mj1GZ24h3r46J
cnjBsg8Wfq_GB_9c84eP8NKCfddgQDAnC66c216oTO9-8J1Gyp25R5bIAQFjUoUP2BuMfWPAHr6VeRyfrvN3hXd79nvbzDuFR0iaiIrC0IEEeZv5FzVLo_3H
SdpYfumealInC86z7miJ8YZf1FrSrnY7RurDSNmYATaP43StRo1iFINWc0fdw4__vlz3qRSo2e2KFKmWpSs2T73MPrsHT9P-rOBt9nBSdY5CO5-ODY0gKq4I
gLp_c3A6_wJszOdiIs0l8yhPXo0fqdLday_HhnhxyGXg6P7U5oPo1o8TYwjyadwr44STrZ9YZ0tjip1vxkJcrfRo7Fsg6UzF9FK10c3fIKQGF1QcpO3jF4-_
Hi7EkUrbz04IIErJWTFKqOk1a_Hh53ux8SdZUYyB4th4N0oSfb-dWhPFbBwkTvBw1eAb63XDlsg9LndXNKOTtmkJI78paCN0EVfrEfEBwlLEurYOG15ohl9g
_tS0_S__-po_hlUzZ8v9FHy4g7HUHhzgZdgzzvG2duLfCs3IUI7zgXd__dhdCaUK45v8lweTrxj8bGsoFCEhwTUf86UCvNhVL0RHvVHh5BAMaIIHB0Okfb-r
_FlhNSN0vVJhL41WwVLwrxydaEjVhg9Vf_D-lPC4kLtlnK2X_nFDSDRhlHWez7-a1ULwBtEWPFzd6bkvtek1NzAlHUtFzLuCvBhYL_J_TMSRbsy3XVxljMmx
OVyQHBVGhzDvkzxjJ6LkFm76uKvDSPIHcEdLyt2tPknb9CfzU4ADUMIWuByp2eU1QNX6atDzai0mfrhaWmO6j66OcSN00shwSmR-1W
}

