sprite $image428 [117x82/16z] {
lPaBZkGW34InmNQPtF--Az8X9ismQg7fGP_z3Y-uYZ8XQMkGUAtLZTFVZUBLswXLwO-G6TM11eNNAd-19El82-lvwqoj5V0OW5VZhulPaO6jLRyhvXCPDIv_
8EQCnJTgB6zYpZKs-hQOWGlixsuVliJ40lY5xKDMAznDS642YSBgZj-LDiH4QObxiJfIcefiOur_9HcpLp-Hvs1rTzYBSC-UHwpNMdv7J9Tq0uIAmrtv_EDB
n8875daVIP5vn-ZCucxvUgOh0qccPDmMStZy8vmfoDrW8IBhcxJxOewx_-ZpS2-3koFQMpXgCnbvpZmKQgoX38xIE565_2OjRueP0uYZGl5wxPY25nOSZjf8
nZYDpBbdtBkDkr0A3kfXD3dgisICAPLbYZpZUnj1EGAhxqzDuQXLCguRc1ltduxy6IthGzraYeLiQsdNcLTkEvsHUoBBRLcSKydW06yZ73L9g_H10ui0AYMH
zvHDSc-ZDdyPl7uY6w0xIW8x9kCwy_mvuvcoyKYnB4v9ZUwAEiAoiVwbj25Mp7ZdPmxBFhTHIQdKsv_5yiaPmaAVoKWBCKUtst_30cufyVbuTQpp8utO5jjd
SHf1OSwvy38iG2cXkaFrXaOeMVVJV6QSnOnHQpsgqf2opt3AAIcay7jyEhe7iX_hCwCkpdc3PHsN6-yQovN3b0KLENpX_fC7yFhjtNti-17fRobBSkzta_pg
PcAj8DNhONnLf7TQUwm4Agfc1k2mjf2PwNYchD8T0gPtGUtaEO1N1bvzvqSFgAYSGrKFILnjOZuVLqEsQq-UJLnguqNQ1JAw_mXjF1LHU6Mj9eeP6Idxy4bf
1MqLoXNlZGyoPyYuqXDfXgfkQYgnZIC4-RGEHfypZkhdVg1P4ENXm3536zAWOkvUJQHXpMF4thx3gUWGTvoIELOUmCp4kLB3jRhQgjkm8j6F6eTZg-Fqvnrt
A4qrZCZ9iZDK3AUE0LKHC-bx8Wu2qQGGROMU7HEtV_Jeo6cOuPu_LlggSJWg3W8a9pAQGCHTl5n4wHTKd4Xqg3RY0blY_76j7nHv3KSSbGAhDYF3CoCqiEO-
7R1xDU5w8rZ3iYMQlkKqGMFI2JfZCHyjbUQKPTJ3e_3lK8iDkO0-ZJmU10INqZIdR3nT6nXz7T6pW8hgIGsZZGS1qgvqcLCMg3M_GT7zyp-ePcw_dnrrl8L5
xPQDbBtK9IBY-CbUimbgFVsb_LZMCFBAKN3_CMNhDIRBJb2uDU09PYg9zKT7rT5H6f7don5FFSTqhd00rj14LbBVjhEZz79KZfUB9JByCqEh9FGO1IWnfwBX
PeiS2KSjKpP6T-9YePIeTgeJSoALegV8QqUHhf1h_uHIHvk3knsGf1f0YNGsSeH5M7OUQ__4WylpE5ZqxE3AkParg-fev2vjtV9Fl5xC5vnm8RU4p99eT5Jy
t8v_PbSyMxubywHCZcAcAZePUJ7bmZ_hUzBOwV12ERKa5tTbvV9QhKuJBbhc2hbuEPOkRSfEHLEkaYW99aTj-2V4NBqjmf5AXNeXJII0QSVk-cTzuH4vWtAc
UsahfU9Giv1s7hP2HfXzT8Ljd8et3pCLTox0YTLmr0V--VIYCDgL5i-9I9AubKmCXsbtL52mHdv-9Jgcd5b9BO64Z9ZAYJsRuB9bxdyxYHPIXIIfUn4MUbrJ
mG8RbbsAkN6XxPfCpI7Ab78dm4n4mx9hCMdljbSICpGL8gRi4Vqc8heXvcVI8YUZd9axj0-DPIx5tB_1XtDEcIcL9zG-2eFzwst9nCJgleQkms3_UvSoqGJz
CDctfVLCEK_b_JpPD-_pOSkLZaZvwjTQjLyKSoqjLj18zgz-WG_e70RxOztY0xeT1llIgcry2jcMDg2BOzwtliS7T2SCzgLL-vgOwnQljfli-z8sQ8J1ts1H
6tTJp7y
}

