sprite $image114 [239x174/16z] {
vDc5WIim20PWNFOV-BdcsjHYvRu1Jg4_1DY2ak3JGCzCH_WKKFCdHQXFyY-6uYZoNq5G65gs3A4gpKi4IkB8Hk4M9i_hd8etRKknNFZqIV6cRGKNh-EMOxdm
wJDuQnBvc92AuLCnb2oVOrWkVFgqJlWK32NqV9LZyQPjMRtmwTDouTCNLBoEMm47qnpFIeNFsww6dhC45M_QbkERX4_1KAB81RXuqxO2OJyPMAz8edxoQaWn
lbgHrUF4K4BFWU0_A9QNK94XAk23arvt9CTo-E2SamFcQC7Ge5FcIhIS8SALuGyxPAwKDUDJzXZ16hHgb3XXhiJ8ITgUnFtlbQWvJJiqqVQJ0wzSycJpoO5Y
JTEgFB92w-dXqozAz4JuBdQU73IdCMfA67vufW_E3n_vy7tYyM_fPxwLjvGkV1z_OfO9EJrymXZ-HVRVXu_jkHfAJg5uTNVc9z-4_CpmSINij4ltWxbFpmgV
S1E25ehdVzo4SVqTN7AOY5361N_IeAqtdt1bGhnQFf6ZsQhmYM_StLH5X9a8eOSrSWfzfMa5RuA78VlhTJEgeYN_GOUUb11YoCc1OzRBBfAO3roX_FKMHflm
a8r4h1x35qP_zGwksQBD_y_kCI5UEg9nF7ccm1_u6r4r_ovYnHkUPu_ZS-4JhTmiu1T_DfGitmhUUL_cXPlFYdgEx0iSCZ6UMyyjm_iFjL-xjnFava4O3CEI
s9VS_xZ_McOyfAMudwr0tXiyOr5SG-AoXMblijEBLcZzulpb01iJmDtdFaoGjldip-KqaUE6tPqRqrGbvrsu-B5ahgMKxxnMLksSDfV7evG6tgzmQfB_O3-u
UuBzcMURw-F0BNaxS9ZKDcpZDl1RJd9Rj1rt03OybVcR-rC8GM6IvxMbFdfkFz7uHiJCOeorpeTutuLzZZDpt777O24yiVxghnlSj3FOLkdBDt07rrY1X2XE
R3uzjo-Fk7WivgAJ4XFd5ctF7K-q8UBdGBF5oHDpFEJYcrBuatFEYD143XQFvtYAsy1u7-TZHlYsawBvEMxSEJ1-x6c_EDvrGM6EMqN7s_A6ftxI49r0s04N
0ACtRbfiqw7_mm_CyOYh2cu5rvDjX6_UDEoG2u2nWk7FmUq6A3R7OoxknI_AcEFhlmMm0ou4nlFoT44lD3imnm3tPd0q_I7aVphmQ45kANg_pfLsjfVErB00
5tZ0oEyGs9kJVwjocsE0gmss1p3zpGAB5k2gWRkjM8152t01C7IVaG4im5Nq9jTnWKKBSlKVCF1e0QugE5YYLe2mEFVU8mTdXUcO0UOOuEeyO4zz33nQWAi3
ZlGKW0MuIXFz_2L-SEO3S1S1o_7QQ0GMxI3E4FZoNySPZsq-umAHBOk0u_WK2ST-p4y09rgjN01ijlGH9mYifWMmrTCXarS6utFyTEdLOHEzzXmRUYvYu6Mn
nT6d2JRHYywnfo-p67Z5HIiqocTeebUROqEZy2MiS50xdwE9J5e2ZBynCitbi2MyukOpBYpWHR3LqAa4My8lNhIUwMmMMyAlMxGr2NLfBE45DvznZ2vX_Jck
be0CjeHNtNnMUA_4iPa9pnMahBpvu0csX9KMhMS2KdslnESuCLsNmlTAR8wPBeuz1hvpZXtT4D_tTISZs4WNfl2z4jjyX93qtojBLNfZr7-lp1TlFdHxaY3m
XOisaKgcu61yqHOXfV0Z1tpHEWBItfJWpOT9CVp80VtFHpyBWA4vjlIQGWQuyEQZ7oTbRarChymaJMuszEfSrk8MHoiKLBWrqY99kf-RXTR9fdkvsT9Q-NmV
jmPQhtWNDzAIcGHmaSrd_Ksf0flFGeLhkO4MJ-9rt2IqVYO1N7ppqSzTmAsEjea3oerCEoKHuIP3ksNpJxd5qewvdt4zRHg7yzmej6-Ipd6BeRsp9xZLqVQn
c-K6fdT8uWmt6tgNv5jkHR3hxy8LkYMqVkmxBdP5TVquTLniyra_av-vrTBxvZfk3Kpl7CS3jsQXTqzIum9plDkcL87DPxjyVj51xMy
}

sprite $image114 [120x87/16z] {
lPS9biCs34ErYuALtl-upOwfnw4vfMDSu3_pXn0J_dTYRp6Sdpg0KS-cPW7602IVIKqT6FS0FPr5ZMrWl8DnakRoef9SJXAxolSrfxQcdgAvSiJhODHlQIwo
efwWcRl3dA4vDfLApV6xOXND1--EDP3oRR4ChZbsfw9fnBLs8HnmLsUnK27tkUJIDCt7YqLxE-6q9NzjTyYevK79y5SdnUvdUNvomt2-a5diL7vQXrATZjtH
wl665ZYgas8jKFJyq28XH7XUo39WXafBJorBuy-AuJQxTuS59VKvnDm1b10gb1VI9HQF3EcjnAULyhXfMuuDzXToNOfAnYtIQYbKbjjuj-C6S4SpnKBgHaef
EUUKudzCnTm4sdmWq0yXZXWjM19JgJAm8wN53bKpTmTj7rWR7nyLkseIGDAdKeIKNwbNKkjThddzj6or7LcTtAaFfOZTZ05ZHk8NK_E7tP7ZClZ53AHib29w
E3e4SwSebZ-6WxDHdnXjMRyWFHwOzCIkWxai91yUb3js3S1okIpNs1u2PbXJDxzscPS7z-SdeuUDSQMKSodFDHx31eTikhrItroIqGmTcKjzq7SBYrXItroI
Lz-hqqkJ7JJwm5hicgjh5kcjtP-b50EJAj5RmyTliUGoi1JbumcERtGRBrvNRr2GIYx9-tdIUyq_3mxUEIgLN9MiqqSh3_IDN4Ce61z2iHjSQhQpn_EWhEZy
UyHGhCRLFra_e5CB8Hf6JAw3lBxP18FXxYXS3vbdHDygHOthqindkstKav7Bm0vzbKc2JcNcuYRpHebbHomZAjX-ECPolsuLiSoyZZaK7F39meDQ6J71BLpJ
5ZSPsDyTHjBha7MG6UE8aSCxUNWrCz2e_omr_8nVCwbQUWohH9TcYjL6FDAQ-jIi1awnIzcY-ZL3fSuMb5IBPZkLM5c9TMcsYyrXDqaCcbrY_PhjfSXuD9j7
p5Aq9PggqrwAzYIPkcRBxbGxZobxclzOYeTf_bif7gTvwhlZIbOqJsrtlE4BQUTAT5ErGsZQTiUZUPTBiJNuerVdt19h6B5NytJiZaVpF5Ii_OMSZbBqQ9wE
KlHKvpnMhFaGckzZl0Hx_9gdSYb-K_Cq7HJ7QvuNn-uugdCwIj4rRCVk_0i
}

