sprite $image207 [277x256/16z] {
xD350S90002mUdks_xYuEtomP8HKNu6w3mjZK-tGJc6jhsMiDMFOcJeV2_KG3iHOLJH79RaiKcXJt9MaKjOfKjAc9UMoIv6oQecBabsAbBLIJbEaP2bIf4Xv
cHGfKgH8aI95YXGfKgH8eJjFeV_452bIf4YH8aLAK295oaEaI94YHOeKALAaI94YHOeKALAaI94YHOeKALAaI94YXI1btivzABkk8b40TQJfWFZ_lvsHaRja
DQVhOBXFlB0hJ4whw4sGvvfS-LIKstr6bCUPADSmvv_k0oUYF2Ak2TVfAkKqb7l4TvwJLGgre5p_dr7_mO2xnAbGxlmxbDi38cw1yEZkWIVkGa8pzgoFSdr6
F2I6Uy-QUH3jI5AQ2-LfKIm9rjFXyc2cZOGbpOOIFb544bQtY7fYk7KiKD8_ycWo5DYZ20B4QFu8E3TmxvXQafGcH8ax58Qmvcx-23W_yV45ojHt2sH54GWb
pvifamwMlpTA39hdsg0F_7tYlHDbql6XiCz3-tKuo_mee2WGTW5i3zmcHsdVacbF4l6hXElKAEs7D_mToSf7M0yHFcT6QJ_cHuz48wyJ7bELP4sy_mDGRefY
IMmubLWNqi3rRuzofVtuA8c7eYnaJTRWOrQKzeCAM18R5aclC17hSg53ukrlZW9wJi5VXOeBinIRbSJc-RT6qQkPCN5TKeaGCLCjyVPtHhbI8MaAaMmcKjh5
1fzpe_X1byHVBgATMmbS_xuee2JDBDgvTHQy_rqFRn6_354P8c7-SOQU8r7c9q4gaVGEDupGn2ZtRX8YtOc4c9rTw6-2SeS19Ch2n9BOAPPXAFEJw0o9_BGF
uMDg57zmQ4sJYPsXUjy-vqMn9FQKAY9Cr4HoB5nnL1oKAUkLHSm5s26nuUGibZ0nYZyuHAmqrOSaSiFYRCxF-L3yLR8D3lCc8s9SZ4dp23qdHF47HvT76Pog
2_qYB8xAZ2ZN-kbrUmzXtiEK1QCiIjAbyfWFfKf2iaRdXkN3HVycq-yZYc9od-N7kvR4lhZgtEmXHFzc8ml_Y8BNQL2Kn8P8QrKdvME1DB2OKtybqK6POd1O
vmPLnheGqZSip5GDp85oVTRhLT9nms7ZeXGEIsEUfwCeYGqT3cgwuQXBdOLwStTGJYGX4NjGqurOn6FfNonuSr1EMoMxyuWSreUL-FWROnPBF0D5IT0RdFGv
E8S-qPfLbe6BvUcWd46o--Xb1eVLnR3iPcZ4OhcTWd8DM0lj5EW0GsPmHFJ2guCpPh744r1k0UjXbjtLJq-mAc5OgeEZLbq3r8uodeHucnmwR3Zs15lVX-rY
wHgWTfJnguIJCfWDnpsfrLksUuJ0eiGJ1eV5sN1SbbGP7EuTeNiJolXl5lf6RmR7RCIMnIoMGICKMr36auZPS5A9kZW7MBCF3nkXHmFAy4_2BCUvsM_4-vEQ
Tu0rUq_tBXH3Cqh_EwF6lD4x6_6EfRfOp0XrgE0VHRazVoBXDQPGrCMo2DEdXG4QLYmYpIZz6uwEXVQ9UJ8XgfxKwWVOUfrygyAI6b7wsrNFQtA48MAnoqNs
7SB6mewGKMabIUqe_LL2EZN4eZ1qEC3kMUm1LWLgWsDyMaZMi44PVm-saoCYpDedweBcZRvwKgjNX_bhpIggG0PbP9NOa6x3Ueu_7jJGi9XzsEo-jaxQDo59
gHsblqfqVDXSYDM53WTOPnysus9y6bIKe8A2mwl4ncx3XtrutxcD-x3wU2e-YKNXQy-f19j2tiMlNgssH2eBGvfL92KF9Tr6Lacxou75B1OpGawTxFyk9d-P
-2ZFl_wdUonrbdgrscFzmSVCabMn93uATD_vsbEV6wzQxUuhJicASuhZP69Hy8jsnVxeXovR9wP4MkkadDpzPUAZSFj1RKJCVTZVUsh5ugcmiqmS5Ctr198r
vkBdx3scM3mL-LsR24QK3nHEcdlJXZCgL6BhfBuFLyufTkinW-Cj4u8G0f0eodVRpnq6apJNYQrRg_91WblisGH32N0L9JHiECDDbAM-z_Yd4wj2-rGAJ4D1
4wM20Wq_6XXFujM9FTPxAeUpIUsLIoCGWWRGec3Jv-3n94wTcB_cgeWLqLI7HuDyR5fgQzVn9EsdavUUKT6W3Tc5ugEqjkjuatgT6097HUea6axxS30entjo
tyk03N4BYMQdujU9LH4s9ExqK2DAVxloaXCranWBzxBZ3uuDfqOK6bebb79Mb1OIvnk6gyA6n8PICyf84ichIVioiIFagkXV4KlY3uyMhO-20zjrDH5Q5aPA
2xUILCziUn-hea4daevXy54IZDnmIEXLAqlEUI5g976UOesAsN4S4niXS56Uu_TWNas4P152QerQ-8DZTXntTcm4FPJRQ18iNKkl6H9gYrEoBODZruaDnnzH
nFmXdhqf5gzM8LuMfjQmSv9j6Hox6TiPggF4_Ov3x_IpyAjQPCcvMSMUPDi7HqtSIAoZFDucJpF-VRMIY3YlQKVnJx8Qx3UvNHyMHKyf3oKP14CfhtjGAbUJ
PXZp3cbVJ53JrYSQkfU3kxaGnZ8vaLap0eRMo8gIyYk9lrOHLJ5bqcCYGNi3FnUAm6e5RDBbGfhN12tCd9PM5l6U6dzrP799SBVhmWSAFzR9eRS3KafCFy2q
cYZAGg-aB1qgPd3wJFYf8aL0KQJyuQJbRylQn9JpGW0HgGhJGA9XRLeMQWllLOH7c6Z17jyMgPZeF_B-FLeC8PRxN0X0z9qBcR1T8kqgIHf871ETZrsqLQLK
hwAaWX8ehn68J8Y4L75fVrdZPP5E5GtscvGsCRbZcIcB4Y2jAXYPLnQ4Y0qkz5EaRwsCD95myM9HOY88k1IKmhBE5FwEXSP6szQKIOy9to-DA6lFOWYqR2XC
XQNcuf0C3GyreUkb4QNqhCG0K53UCxIELIIFXVvyiDz4OZ5fGjbwbc4x-EeCWNv9gxDCG-9VT-2YQK09yTMpIyHoTDdF441bkHYIcKtYvHiKmDApUKMHrusb
H6Xj6dej5yCo3ublWew1NxGKW0lAybepnIHHA2rSPPd7n3soNRz3mPK10uYYvAGeA99pYbgwPh6SRk8VxVN8rZe-QTj-Ga59Iyx2YiASNYty_nnPJY1fDD6Z
VNFHWcpR3nO0AWEaA2nBNiXXcTOaNBv72PXorg9DjEIyHoai2ODsYr6PpCHkFEsT8X5eAIXRgMHXHKcBy4jBehAG1ayaGNPDwFez2hr61xYWy0u52yfMl5ej
i9-XKqsI5pObsrAqvMjdY6KqjeBPenGavhLQmffePkWC4qbfLCdQJebBtdPbuh8a5dcZq8QI5zcgfJ93E5-T97bUkb02b9bPVLZpWQ8igLHBsOScgjZ-ahNl
AL4AIW3yH67X9PVig-KFBPRUYlLFz-tlAPXo35gZTHITeGLriPopJ3Xfkaxt_djAYa0GIY9LKKorcCKoo-WakRTG-EyfccXHZZCaaSe_qQYSR68tdfxtb1o3
1h2EeYmY-1eY8ADosaE19bowK8IB12uRYWP862nAYQmeQHqwirZEl1JhnjE58k_7s02iACeImWibPPEqeaZPY8OibjPTP_p6eoY4hnIMA37OiB2g61IMzFhW
Yhqg0tOT3LsxK9XmItonOAoZiAGwYbwV8pDtg0nP9lR6qvuxxbLU7fmPgYZCInL5zFhSDKBDRJ9-CzOywOC50cT9r8AIz8pB7ICqPfdePjoPAvGPqYm8d6BO
1zX5oLbVvl3B4HgnJ3JFItzkfGpm7S808X0qUf1RwYZxepzzfJAiOFM0qfz7gHODnO1fLorwHwoZl9Aap53wGcNGCh7V0eTM2n84IXZs0N9GojzM5chAe6LY
3stzrVB9GWZ04Wypb3mKdQ7KLhTZ2bOFRKDpjzKIZzM2xrf9ibWKPLaQHcZKvEYXRN0UTAoMc2Ly132jB2anYnWKdQ5579LM4-9JJ3JFm_RCEOL3W5DUk4HH
BCilLPgNoVXNfVPJ2qamYPmyb79gMV0tAkCArgwJyTM2kmkH3HeKirYMy0kLXe8zrSIUMcAm0M95aMooh2WXCfER8PEZeTiV_lFkZnUYEei-7THHGlJNIaF1
dhbED3SesxCtGv5tJmTL55zboEHeiC5atAE23U0RXPD5qVL4zJHCpWGcvjJYiJWeligmoV7FzkCJs5IB2Ree34N5JD3GPIBXyXVc5asrsD2g8dMKdBcwLeQH
sA_ePrLB1BiHBJKKMFywsRNIDJdjFxaVdwVTddd1mqPaKT8BPIctn8FAo6MIy7Ov8LTJBPoJn62lpoMBekZFEpvLHf7OEZcpMYYJULG0sbWMbkMDeXzZXKap
u6YYeVlblDnhxvLahyyvIs9cUQF4zyTOLfMHomJCwUJKQY7xNbbUvhXaGtbzPmRAUL6LSIJdj8d_g800RAlbW59-t06Iawz2xPFpE9N3LelEK1IkRC-A0g-I
8LYhHLHbn3BX4mgsvLC8MHPTAVGgtzUOuSyenCrbShlCawlz58APpVLPKNHFZlihS-Va29ezPxPguIpsdgWh1K8K_V_XgKhVv3mky-Lsc26HO0Aq5Us2hpsv
L0lfljmnEQ5v6vxcKI70U_T9-YF3P9TAy-H49Pal_dkb1agXmBjQ-5E5Maaw3x0pl5Vg8J-_gqLqWBuga-TbzjpnaoNKeeMoLalAQVTeopB1cVwKJo4C0RQp
IWo0CT268irbCil9fFzJIFargMpLek_x9vpfvtclX38vMxKiL51uWZ8vurF8XWFRvBoh1LSKFk61O8Rtof08YefyRCffHP4J7WYcg9Ob9pnkoY1P56LycSnV
BKi6aNZSb2Cqed33cNx-Qa7PlRK0QRKeYepSXkUl5lkCgzN2JIWpFH3qVmhH052f5e1IBHHGKKPkm_DN2zgVRiVCi5PBCYWdRCCpl5V6n13NeWNEug1ClGsF
_-bsMh0KBGI3Si8NhZa-XQIC_3x3AShyx_H_zgVRdAEUuHJbX3APh5f0pt2YA1DimnDSY83MOb6K4zxffweMPH4FHSQNoVoF2YjB94MPu9r-blTABTe9tkcd
ULHGb0dEzDDy2b6K2RRXQQg5BCe9P_h9lh8goWHFQzCyAYZA2TlmT2plax-YJB0DJrCjYZB1DZpDoPyLPO9jU99JYwBm1DlmJE-LCi4sF5srYBaD_vSdXSad
vty
}

sprite $image207 [139x128/16z] {
xCu70S0W30H0DcJvjriyT07vKt3XCNdq65OG6p5JNM1IYOc8DVzVOPaJKLkWGY8pOejKrCwie88AAgZm7XLKqZ8LNQ222Ygee88AAgZ4TIf5hsBiRSjPN0S2
C2J1jgfA-FtVTczWQRNf7uVft-cPkaZVpE5RKg4SXYYFzFmO9OzGvcImD7-8OXUKnsjPbjTplfsemSnW7sljzm-KhsBOOsLvl5qEDmcTdsijvG8UyHCXO7O4
iFoQkdcIWFnJb0T9IZcbPTl78mFM1YZB_ERVbSlnIKf9MvwFT8R4Q9Pt57TyS458Mt8ns6LGNhzDYThkGodM1YBGhkdn-vGYqZO8h8tSNSG1sPFctwPaaVnp
DQ3SAI4aeBr-cV8IWGPoreWa4Cdphr8UuRZ6x9gWq9w_I7aLUnE0lcc0oF9vIa20Tv0jSc-sn7n36OLSWH2Xv5-3OPdxbF69K99uyg3DyMGtbWvb50AI0Aau
905fGhbxM53cpr7c0n8IoIK2kmOXEUTi-HHbNiwhOIYEloAkiZFFtNq6PHm2ah6P-9_jg4iC6oFJ22KWpTD2RI40gfd9yNgJrm0b8As3CPIOIM3SXPiy6ie8
15jYDR4J-XSZjjHFkQ7SVK-8KEUw7e26SJyOfh-aFDBtrLpD91Xo0RUDcMyeTn00PBpXjZFXmJW4CHYY7-OEvGuIeJmUcgQdaCSWmDZFxPBI3odF38G3_Aeh
MWQRXiH-ugKVTYdz2n-XsfaG0OXNDVk9bww5KeToSy_YRG-aknDs52GOJMVFB_tRwzwXz2iI8INtvhXQSrpF-ucNVdatWRD3wLQa3Vvymr6d8V5oPQ5xI-5y
Lv5EmFDLQngYPYjz2-LdYZzlAzB7D0zD22vh4XQTT_ETijnNf9_0dFV36D49f8kHa5yKUVbx2D3KfDkGi11xpBv6OYbbkc8gTjNLVmOv4epsq9z0ZDN4laE2
jAKmABZfwfq4_Peqbe3iWUzHJbkMtRAlwrjNkv3-bmgmERFH5OQ52aWa7k9q92YkVrWHLRMGSzYhYPhLHA0BYavJUUG-16jrcjX0pb7da30SNv4VKVb6GK0o
OFqGvhMAC5pcgYPqub8IGMueyd8FYS6ie2JqBJfPY82qeJUHvMOgom4vSdVGw6ibUj79qaoaAt7FhwYjQvwc11A8lBMirTVL-SPolPg8pX0yfsdEnrHMcruc
0Y98ljLWJwsaT6VPOpSIfUEYKfHxdYTAohckba4oE6-EAm7YhONN49EtmIEUc4BVVnFRHSdMIYFC49epf8c8NjwE13ej9qrVURscAIXKfeo4vMpuOpIupnbg
Tn8zfsy9YjMAR2I9abEnqsZmqznB-9YkAShPlDBaJf8v8nS4PW3IbynJX-9PQm7DQrr9bRowfS1yHkAdFAS-fQnLssHKjL6eLILbS03IFMp7MUqko0pLZTNh
kb4aQcLU2lXnYJnVGs91bMQWQlMDmhMAlY8b8uSbEajiUaj9hDKoA2TL2jTQLz7TbWoE5_Q-ikrTCTUI2hXJjDR_PpqgKyY1aOGaeiVqde9QKL9AsHhAlgqL
EHd7Qn9vzHnHswLuPTgIJNcd797eoeKSNquyFFsGD2ifWKiwCAd8QqIahyZWi2GUdduAOGOhIs5EHugeXaAwc_6d4j2_IyhqFY_ic69kTb0ooVMBikxz7NZJ
2GccsoHk6BDYA8V5g8PozDU9NcuW8Pcd-yoPj0DZ-S1WRIdRN-zEfl_Wz0zAFqyZ3emi2hETEG_AVlB4ZkHk9AxUGUbNnanOqX7R744vJfvuBm5zHD9Mfcmh
YifiQP_imZi9DIA9F8xAM4cH3BKMSVbkwU-c-wdj9vM1vHGfE3tPcuvz2NrOqbRc0kCDXTQLG7uPcwU_ofn8EoeJcpAkNvIrEXl97KJUkVO_gaoMJbV6Lo6b
p5fv8M47ejSqaERA832iJcuKvEo7fJkIDcMU1XDNfXZQNsImBGZ959QRtTXp6azKnWeO9uzYIiNhMf8HmDrk6BiPpQFmm7YEAmEaX69hzGA4XUgK94sVIrGc
foPhPKQjiQBkRifZ-cWM_879gjMoAlQm0y5uIVfN9YWinQkNd0dqTiDbwcUyCgLPaDNAJCeleppy0D-_CGd7Wf1P2pHGai7Ae0XMqh8zpfOpD5IIyIjZA4l2
MfKfbmPACdvbYbbsSYq8oa191gzCWNjrYwaqL_wk99-_Cc12hGfAbEGr_PkPSppOcJKe0rT-A8_uNfiAWwAnZmBZLoOeuny5ngzCJ8MZ9Hclp44PBybuPKXv
NFd_DY-Zuih_vrduwTty3m
}

