sprite $image152 [143x150/16z] {
nPm5iiCw34NDjgxS_I_tG_kg2IcnIZv33pDdhi1bznxUnrHg8m2y0Q1MIqx1kr_WOwu47W1KK_YcISWDR0CrkcyGYwWOeVBXZ49k_1QK_QSgb2eaUO5vHj5y
Qc82MW7yEAAGIMRt4B2LboFocHILzuHQVB5649FF2f5HA5R5v6C91JTAAABoHQ7YtGYfAJ8JAkOBYSltXV9rnv0msIT9C3_pGL9tZCZyq0S8Xp8oIx_r0Qeg
Cy47uA38pF01jjsSHMQ23y3DBOWaCXDyiDRnicTc-6nrWaGpnmS0k4gXGDy2uphbgKEWQJvYmxANmQ29GdZe-ATEOUPP0KauS4iT1gRuI3XLT3BpjH24Jmg9
3KVH2SlVhGI4tHK-vVEyF3d1O_VxaVxxX924avqJ6b_I5yYbyAwFXCDkGHvnGKt1-vWRYvBD22SsnIq8LpBCDJWXjjwvTtlLeDd0koKuas6vA-HZoYbwvtpj
p4f4upx0kdE4Ucf3TvbG-VQ0QtI-CTZUHJYq8RScgJRClTo3QVss0Cab9Wbel6OuiDdVBeLUg7Hl5xvje110uCu2OF41jdryEUfYa_fjHy-U83xZGZiRSZkI
PfF5Pa_p9FcC6srj4DmEZsERUl-bs2W-9g6rpIF-WMhr_jm7TDDe0NJtDXY9Z3JE0V5mgEAzL3UT5XdSJKSQLZRD2QVLwlAtk9sG2yHdn0Xh6_Bkc7AW4--v
wIxClKU0nKTHKctWdKB0saOci6aolTLIMqjIBiq8UnaPAfLsl78SQpfK_gScadXqi46siKhQwJoEggw5KyiVNNGkMMKJtHauh5M-AQ0yORRuwDdepTnb8zHh
7HgFvpeRmUDWhboxrgcTHncm4IeBNSAa0PtnQWtCb11MEl3dIv2BW54TRT_eyKWuS9BECLLqMX_LaLqyGe15fubE7TIHSsgGkjTfgWvNyUayWfpXeuIzJhaD
n6EnIMwSkjD9kawlfaK8G0Py48_jP8Mk--3Ffzv4vyA6l3EHjtl7yUtAfq9qBcogiqAY4wMNTJhLMd4JdNCRrE2C9D79qZndzFv_DVa2uA64ufsDodAYF-Yt
QuPi7cHdmkFfuwHQL_Hh6mYKxENgB1iYz16TVcqZj6WjLryiSpBgw3P2zOPoqNhKmq3hw3eYioQF2qN8xS6nxZ7TRhUtK6RkSkFTESzlrGh2feM2eNqwispH
z4QjD1tB5lAqsioklXWELZ2_Mh50grNewALmeEe8DOpvO5Kk3tius73SrPG7nqjsuRdFw42fGzRYc4zVjezlfd1mPCCufhpWut8Vji6n3KE1HW8A3vyatvDY
Co2ZsLXcFj3_Fhqi0rkuC8vii4VvbJaWNvzF0uXXeVw8fMKQiparDGNa2-u-d9S_z244xn9txdr8HhUn1EGp0NYSNziZE1v5S-WYu9epdqHoqVuVNACJJ_JU
B-ga_rQ7WbE8RNNfVeTQhOtu9Z9R05R04EGE2VKezlu7sy4W-RY3z_0xO1Jo-peH3lcYZDxDlkA4RzkWR3SnnlcSZ53NXO8HWujTnnFi65ICEWKlyvw9a9Lm
vi11wPmfyAfMURODt9AA2UZFkBNPDcZpTKJcVy9a7R7P7XAXJfTPL2jZleteX0Q09yk8JfeSZT1css05BSygdXIDmBGyo7cs3HVd7E49pvJ1uz7Z086dHiES
DutCCwFXibs0pFEYGTplOvuMJVNkG8SdHPEERx0ppuYcUNUi0-QVHyFvvEuCyuHeT1qmJuX6IApxV3yQ2cvDO6W-tu-ck2rU-TyVHoCqDlXyDHffdgy9wT4W
kcEW-Vmq6g6mUfqVHYDuw3xyfinnDDMTKPXFBiU_YqRYOPY5x39oK-A2o0pXGqPiY4Olbox4xzP9ehccCGFNHcoKqQEnje-kn8Oo6QCHmk2QuGNZ8Te_XYDO
Qg6WM2eVUJ6IZuaB4sCqTXyxSaBPyOtV5z9lrzWf4ldKQ8G4yPaGZLOm_fGCidkJX8y8oIVil4q1lsaazxm_GgXi4xAT2NPynUj6B2tyENm1_p6bXVUaneAn
XRtx1Y4JBnYjKtHVm-V6QqvSf4xVnCT2ri_E-hvI0rzIWnD-z86GcXKeU_TxV8WfbzhaxPL4xKEVaVal
}

sprite $image152 [72x75/16z] {
hTW9qlCc48HXzgLxfFiVDp5MKI0FDb-Kzm1FDPJ5lvXlMHzpgM0FjUGKhFb3BkHAYWZdHCWQtPPXGmP5I81gml9pbOk5Gg2-MrB8xikIM42YJgr7ULq9kVOT
cv9JpjEHROZ2C2i-rmdPbqOe56NA9aJN5Ur0-r2-JgHlsOTgOvAgx4DuEwKf3o2ml1oWFe80YMqFWGUJ0D2rwo58Z94YGYnvpCvrpO6tH91JXWXNIp7DkNw7
5gDEaTUtPvtpYK9oANMccdU5c3yNc-Ku3gQGoPM4VZdYBYUmwnGu4-GyNfsI8hcYy6OWgRyu0qDd_D4xIyHA0ednLFF1eZ4y1gXcaYg5bg0_hlrWQ1zAF0T7
f1IE4cQ6T6Qepmd6O6HAoWcSmX3fJQ__54bOOsLmaFuDrD8Ouq0Ib6BQBVTgoZbLQdLcAXCa9TySl9n2BPKnZgrqSvXoIdd1mCr67zGSTuoLro1eZ5Hhb1n8
IZBpFH-IKqhgccpq4j7kns0Qn9AhA4mng-hrNgVpc9BZxe04YbyudYHTFzYGV38LP7QhaxMBDkMyERo5zrT19AkVJ0Yh3FfWW0Q1Y9fZ8MrGEBySwpA85gjN
hqZeFwxwOmnGGU0gMnM2VK6BEUWCkyCQLAYwzYATroPH5CpF1ulJxWZjo15o2EfTgKsP6FM-VQN8vLiNSNjJ0R25EMOxAOK0A59J2353RgyWIPMPlpURGRGe
BH9KmsVijntniLOFQgM_GD3QL83QturbAgBliNWOOtFyKmRsxV0XW_UUz4ZXTS--y27JdF1uJ7FS_y4G9lAn0agyVibyn33sBu8FnbHdrix-c3HzeNmmPdH0
_jSnhKWeqEuOFxpjW2RjZr6UC99_7jC74L2axJ6zABX9t1qpbqLxIdMbZz4gil744yeO1TARZ3vcMH9Ye_u3NkQn9GcZ-PvD_2bHYZC_S_cxH44mMxa44Iui
OR9cEvz14TunzYFjv-BzVmv5vh-QxcTzJBbKW0HgIJ-LVm
}

