sprite $image417 [147x96/16z] {
pTcBTfky4WLWtJLxZu3tVzkpi9MA62j2EVvPsRstq-IJ68ymyGZcZoMePZTHxcuXAPCr5qCcUmT95U4gQQ-zXQGg_Xgfrjv1kjXIhBNs5f8osgiaPRo1TAsb
UAYzXQGgRangjRUGL0ylSXjidrI7nnsarYP1rFT9vvQo7oUrO9UuJB9BEjRM1AJFaBoMntAfnsGVOm9E9Fj2QiF32va_j4iHkwcye2X12OPNaZx2rvQo8G7y
q2uHCUsaxoO0maPgIQoR-Wq5YPcV8nKLxgGzMaC01Cwa926V5q0YKMT8peVW1eFcJC8xKYvCygpMeY_bLqas2lSWV8RqfbenHOfuU41s_eFUJ79IEJkBwG-G
F0WUulealOSKsKJTRT9_ASjbahudvR7eDVYHf4Kla_HNfC1pN9T4QisGL7CWyHh9yqrybwGahvDgxHp9Wk1BmD0XrNbycQJaF2aJd2CLrNALjFivIGfDXAka
iimC0PqaMV1j_4T7vHGfjhsHVE2vsqZzJK8uJWFOkqZzJS9ZMuGrCZvG-D-GBBwtipo5O3Jdu6YguwbF4lr6ubLI8BxjYlIwUuzFB5-eEfxu0wcS5d29b8dZ
9ldk4RT79MPLvN4-zKakQqCzvrE7r6bkruJz-wN2NETncqzTKinHjARDfo794ySNc6SJzjgxpUFoo0_jZGYjjL_LOr8Y3htZltpCWnlTpYxr3fGPKZlUnDc8
DvlKFr3AHTBkc221BM1DhH-EogkaFPT95dnhifT8glyrgScYkKZIzZd0E9hUloQrwhapRanI_VKksJwfSuD_cQGpxTtYJI_QCYQr0sNks1MUKC6CIDIQCQbc
XXHFf6Z697AMfDT9ZiVWj4VT0-L88ZkamPkcuVWcG7ZpKzexQl904lH8RLFdRk60kaCSVRKZe9o7WEOWVTBvAHmUACgFpt1gn8yVYIMUIIcLjwIeRK2sQgJK
IBr40I39cs6IvdWcGVYMPBpekLe2s4ZTM6lDbKHjP_fuBbcco7DrragQIv-a4oGjGESTogT9UfMqvoQIwWH9Ro9fqIkacdj8EaFIlqMgkPz4_ZKI9KsHU0Cf
9vqXoHszH5udKS8SoReQEq4IpksINYHP7rEMGtAAxY99YqwGm2ia6x88JX4vg6Bv5AdeaEJIWqCjPLdMHvPbAKe0qZvNOBbESdqIAsa0ObcgPCSiZ-n_LY2t
bISjxqZGSo-PLZjBiZj8dvzS8D-3igv4EF3bxLmId4crTfuK12ZRolniRQ0-KoHsNewHsvBD8HxbpLmYK-TkVRQzRNhiaFYOwyNRjlMPRIq4824LM7DCP3cT
SOUvrAsj92AYJx8PN3PObtVFkYsA7BrtplcOMTQrK92pfjU5wFX-gSPcBQUvn2x92dGhtfX4NRSYmRxUq2zR8MHD_JRfarfj6PznJLGsULxpfVDu8YqKtMAt
JSQaDZp6Tm9ktwFd-eNI-OXUH3SLrs-JCQbUwJ79xw9i7iaR8T7PLtJCGDasHUwqoPXKu_AO57UHc9gyBOH8Zc5lRckTyo5bmTxzSGU7pXwMor_vzoW_alnZ
-OUrUrthY_uh0A3Be_kv8lVQ16ntbOD4bYx99W7NDRwkU3z0Yl8PBUkswgF6hnJRko84a3BXp30sQLt02yd6ny1MT_xmKUfHj-CKgPQubU9w980vZ4IjUkV8
osKEpoCjTPTYdVU-jler4f8wSor28CRZfjiTn7M3DHE9AtwuS4IonioGLBvVCYwRUZCLwRUtiSZEN8-GYFzE2LT19Ph9b2AntxDpgsDsxKRs2LhcG2xdb0kH
WpMVYFTVlqbIfqmoSoBK9w1K6HVxFM5y7UtJmx9k6irSB5XpPHRcfpqFu25zZU4LtioAXCr46LqIqQf7HsztJlMiMqdMJ2SnfySt0ADXw7W8SdPLiSSvxqDC
-SbXMRQrYFjLAoxBSu-pB6GmGv8ULPBto3EeuRuzgsPlVXVB9O4aCrODezwM5EKV1yJtaAfbvnH4QtuVp-So4pGE_ScO-2Lwp9klh7ksRLiNbUZC_naV_9wG
WXac61ELNm6_dcYIWEGKlJLtflA5DHgzCtyYTGf82DRyaKG28aZcjlmF
}

