sprite $image112 [255x185/16z] {
v9S7MWGn28KNqc3A_OzhrorOc2Jg0lyDNZvUoUa_mKhv51KenCmDOwfFnAzKY2SU6tz01QBTFLz1APBup88u4P0Q2y9405R-0ihXJ1yh0ZBnzrGCPNg9rnA4
oYeeXpAzf2MN2rTFHSzb5oW2fEbZHK0cxgEXwxBp7m5OUG3hN-52F4hB3atlFmAmyImgk2mxFSMMUAtfwGdb3dQuSEaLPGawCpsTyHC1vO3uCqvsSAOUyKuY
87NSlHi7GEqIVyRoLnWA3OfVL-rNs7pPIPPjtwpkO6oZTx_jkv2lM04-JBzk-p7vJ0NCbfsy-_qiNxq2ajMoatT_bdza1Q2vkvSib_9DhG0e0-Bb0wosLa0U
A3iPVTlIDOCeMImxkNb8SCSHW6hJ3w2F04jbDry_PLCBLuy-0coPVhu3q43PTN8d9GWJJD-ge4awv3DbkFkx_wodGF18p9qeoOs3O03U7oI1eEVzNtVBb3ln
iEuUCzfoKrVkv6F48RihBIt6TiDL-9PXT-rVo4UyVttPobNuyuzpCf_UHF3JJcmVlWhp4ZxpeM-2Z_p0F_aBMy2dYrwQrFbn6tZo5_RWZmyxuNz8glp0x_nF
xS5eg_ZGnnagykt9VrXv2ZPyy75EZh7NqEyEly-bLqAVlzb9s_qrVYJWOJUy4oiKlHRmoOzHueVqXZsuSAtLCKH_malZ77j6Hu7_oQimopa-GlIjNkLbse7W
f-rVfColNuNNd-7AU8OSy0L-nCuV-1lKfSQlNuNN9xtf-1iQ-38VV_Wz9Rp4hxU0zGtNVCen0Iz323bsPAV4J_u2lzW2reUTkViSXn2z6dqdIk8JCnFsiLZa
ruTWlUWptqrJ0YfwpVmXM_JuwLxYrrj0VTXbVeH9rJ-U-l_o3-bXMUE_3-sh6wxv7hEO0A5T_uglySE_uaz_s2oqW7hHPtwz1GY5_ZM_nNUUVBfgZtjHyDUk
mZ7i2lng2n0U-exVl_FbEluh-BDy5Qw_kB5WwsaBa9_y-fO_ViEV6pxuXI7OKNYSa_d60CjlAk3_v_kVpuKKz-32iCjyRD6ice11__VXdq-yfm_75Lj0rrdY
zq5eLca1eKOlj3wvNFS-3zyFVga5iCpBiN49moTX1Fvz2yXtW0k3hy0FyCEEoGX-PGXIu0jy7u2w0kP-VGlOazrVygFqkSXFxq9A_6W1VSugtnYaHf3I41ml
bzx3ou-kLNvkWbxY3BSgVzfaG6OVxcyI83dwtcSol_NUUqESHCtyol2ly-tXxbRZ3rPZO9WTzRa5Z8KBRvK_0r_ccp--ujzj5Rw2fdN4sKyfc0T-e-hZZZZw
TNuKVPrlKIuUOLRg_EBMGTC7KP-lAY0Ez6cSysbeH7tfFSJ3BkBtt-PxMANpaxaHkW40pPSLqFbCJlZ37uttQ7s8PduTxrRvqWU_b03Vee7L6dW0erFofmHm
UmOZzFppStwwofyB-CntiulyoG03D00nGVCKftkmSEX9VkRZ6d_wTtqT7_pA0V08wm300g0fqyp-F0IFUYtmIqL_KV_zjxcN4k1xp4Qi1dG2C5oPnUB7JuUW
f5USI_prei_ywnLWXr_etg2p0sqoWBRHkStpFLZQRbhavs4NKSLdVZq14KfihgqfG2rc007z_2eiBJRwHVvwqMT-DG77LQU3POWge3RGp2bwWfssW2wwm5y_
zu-aF_1BBS3C_TW3XuAc6qETG0mqEsq1o_prOVUUNwy0OU8vO_WBTISq6nJ-inOWbp_OHdBXt3_gv_uzlru1DisjGJUgRdntFJuByJG4W_zZPFxwi2lmgot0
5Mmnz0WavXtazge52ED2i5IBlexF_1pNPq13cwtDQ7rDEs16qDCA638kXBmPTkMYh_BhMq331dS2Dm29Vz822f7mzM5NvzTRm210elK90yE3NtqbL1XsbMjj
dLyVWbFLDtvSYMJd5nDmmx0hyCijm0bixWgon3_V0dBSCEmA_FeCQ02B6o31DyrFm-f-NnXsHVvw0fGHtQzlV2EWJpz6iGBMXrsTNw-0t0Dt_cG0h8KAkA7e
Q_pw49mTW5eS_gv25FxI45o_sItmbol0LAFpcyXq0Tlkdlzj0RFmEAS-xEhyzGg82Bu0r0OmtStT1qaQWkgFUV-vh_Fh2J0EFXC0TGQ93R1zQm7nlxLy0b_d
rrj0KmNP781gTCCZF-w7c-oKxpUS-oA_dW0tXlWaw01Q0t_Z1p7npuVTN1XsA_prBO3G6pO-cGsyuTz_xkly-XuSap_uxaQd_1k7NPs_tWA4eBhnlOFDPEWR
ldyjlB2yXr_VWzNZ_ZF0DW3gbldhxoxkuzVtOFE15b_zIG21BV6N7-VSpe-ep82c5FnX7JtnxotwEd-z1H20uBCOqqpyXPlTKgZVb00RZS6JGU26Vk0lu7qD
_x3zZSGjBK28hMCC0kZ0p-V-ZgAFyEsppHXsLmMOc8BZHcn_-VMYZrZ5FmJFDoht922Yevj9-yFtpnJzOnvUDl6ygm9yCfXPt8_k-yzzIv-fkoq1rW2qC_xZ
Dlpu9mTkgm3JtcVm4_wkSwzq-bBrt-hE0pM280Q2pc5e__-x9ZiE28gfwzKFTAowMc4u0OBV0y2EnDgyPnn806u4Dkd7XTt-CTTf5_1F-Zxizd7lGJ1wqRy_
J5vlInKGzxlF6hxYVd8W61zsqqVSXWI4BkevxFQNHUSXc0yDTk-_ODSW0HhilXVzF4v342HFODSY0Rx3dOVG2hV0peUW2hkU7y0lUXuFBsSPiBy_9v4Hx7mN
uCEkeWAMMlJWknTQOHTsF8I1k5_qlWyMnZa7CfS6uZxiV0ausTQ2xzw3e0IxVWdmOSVZn5PuuQ97iFCb02Glm4wK05xq1s1dGP333XGzaW3-0uWpt1C-cERV
1Jj_6fOcX-ktmgc2dJuGJu731K6tmW4pt8AWXo4HO5Vi0YAqjP8FbjBF6XMzBm52-WBip5OuGblRuW9u-k-0z4gyB92-LFI-3-RfPtEITsa9Y02xOWb8qpZ7
NmbbUdzkX3yDYm2xuWe8E4MjZVaRYGYmAvQ0WFlpAq3m5QGlm4xuh_f1-aBHLxR24M5NE10FFScxjW-EiBieTW4Xz-VNbu082yjY7op0hba2gehUtmeBkujc
7op0hdaQ9XLzwqf86ESqkm3XIg5P0kHnJjjMM81TimG8HL_jWs_hS3y1
}

sprite $image112 [128x93/16z] {
nLU7TYix29I4H1Fx_x_xidZTOdoKI_OvSslgOAQmARy2CDNoPwWegZB-Ydw8YeWgmr-m0wkAGvNQfzaREVi15QoV5bwUeD8_Hz-_isTja1S-m6TiKD7PGwYC
-e7C1VYG3O1ZzhmDyfaxm2z9KAgVoPoey1T4z0Csw97mVC6h2jm_a3aclYAVnRpmDn3h38o8zN_Bd3woazXcWJedNUREaV1toDosROemvxAONxs3n7R-X0ro
PNjV_LrzcqplZ2XOJorRVWLna8H59QSpjuPeO8FpXMUwuRO71vrWWxfUFTQhiFMA7hH1MCdvihq3Iu4dr0976ypVNUQs57uCvwUd7kW5Rct0-JQek4hyJZts
lv3l1Y260fSsC6L7ffBlcLF_7PgUQYc3Tlv7TDy_Qr06GIKl7t0OIVIP7k70xcPmVY9YUk1dFlAmkCpBpD4OmoVWExuFZqojVg41CJd_2-8ihXzmL1a73YHs
1A-_E_yXQ2ME-TSsY3EdSogDOu98VwI3Vn2DKlfxVefii2fRdLyG7FW5OdxnFp9U-PaPIdl7JonJLrciT-7l_3fjSZW18_83F_4ebNo8uCNFpKJUsE3zdLFZ
2eS8mGhef_nUHnxBw3A_Vy1HmpgQxYBGm2SR45EjzCJVI-Lt_APUoXPMSdJd73gboG0BRO2xOe_wU_NtUFzCj6_1-GCRE7l8JnL9VO331aJZ0eHIsfKVHc-b
OCplKgbj8VzXyt00jJ6aycIVuB31QEKHz_mV8hJG_hRjc19WsZRZ2NHA5MfOWQT3S9-WLx_sEsjp_kuWvb1_sktl23dyoTMXh_n6hLLe16esvqCMlm2bWE__
ZeYVM3U7HUppCjW5GVvDEc8RbQYBgTZKmmR-w17Tt_QTtGxsUFK7_u7N0QQP0YCs0E6AQhTA1c1Ul7uYETYdnAj_veydcDmQDMNW2aqUikZyW_0EQe_yn2lX
7_bZ4TJJmREJ2LMbfdhB8Z86zpjOVInyoEyJ12883EG2MDd3eEINUV_h6_1Rvcp6mWVy2n4wDMvD6psq0HA7k6RE5gkF-EC9R1eNcI10Dc-LF4OmGInylFgO
FxR1nDOh0et6qn5SvhNmjgtutsTHUsCWmdxHuCZYe4Jc0lxb18w6VG1CdaINopnO4vbxmx-UWBZX02e0VUuGtIoHkNVyQniOTO01NFlbA6pRl6TkNRPh_dKM
UyU-zQwultdmqp9pAVuuYo9DHkyLnFaJmY_urpPejKF7xln9uHssRLri1bWSXO43HXMpRVwmR6FsEKePq_vz1LE0-yvi-TLlTdbygvGHWHluzy-ldbiv00aH
JDr_cSmvk_RoWAu96pZ_gcnZTXlb6HKpDaWAlr4jBsW96-I4brO296mmKvdhvIs6_fi8YSnXG9kqmMBr4RYL1HhFcPn0bvc3yWFqjGrY-dNP1iZO85ksFqQb
fGt-IVWWSwVO89-v68bAJcTkZNKMb-n-vzR2vssGo5oCP2KdCdUg3UoKpEKhsH9tBa0wYxPum0bmgWtiZCpbApdcJsGkQOEONnAPIzh0mh9D87cPBI7ycJQm
u8UA1DALRCcopGFOGlv4sUOhEUAdVERobzaIPNkc3IoHkJChsJPBPEwyBDgMoDnvbJmjoDpdqDX-cRd_
}

