sprite $image98 [147x113/16z] {
pDM7aKGX38DXmC9o_mrVphVQoA3tjQ3Vu_QW8DgXZ2IPenr6dtmtHpi6y1jwyuii_XJ-YFX7vR17zD_qhHTKuDgig1J3jfcsFIbGS2KLoQl0TVXQPJWYyYS5
AZefs-5hy6-sxyU0Wckzu6FGROUlnOQ8Z4c1WYkfoE8wMB-PFQaEhfV3SFZBajBVOpsu8j8gmtZuEYdRuMlejeYqC4IqvCS4zvhTjfc6RjjCYsiFtvzKK70b
DP9cQ7yKxVx-c7IbhNzCYksCIQLuRSQa-DniUIWxSa91z2OkITh__rmNJ1SxiaIzXpr1xRYLT8e-zC0txS3ysUB4ZBMyFK6e9H1f_x_lKIgeC35ZDEzNIebo
hQr3_Xwb9AS_WLg-HgaSlKd5OC8pvSQaKfr8OFZDIW6eLXTL8cLZkb-fN5i2iKcZOBjJAG01YOI50NMJKkWCyTJqbWzGTZaGaikpSuZqlkYMzj0Paj834Wd6
uFBsS4GZhYpWw4hzUn0yNGU4E0C9xI6NAONEzWaalRWv58VhW8142evTUnEbJkuC2Gq877CeZUa282G_gXA6wLgbSfq4ZnDmV8QY4vJAfSwoFKwKTnpYVAPI
w6mQF4vCY0Q7b6oeyasfGvBGsII1MBTkB329TAJYiq6mCoL2M8R0nS7H_g-59ojrLcT8_wd-QvmZOGDO5rRgE22a_qY76Y2iJCXdfUoapX1guPPF6o3xFsXO
RsyT24XexmqgFdrtQbOYBxMttXcGFa5nRrDYVUogr99vyHkp3WIaTwYmhQKcmw7rHvGv4zcwKkXi7GcNRKF28A2bLgD2gPHqLQbnHEj8kq58_bSfgu--vXjK
Ahuu201QHq84KD9v-i5PV4PtQVKrnphjWbAvBYMXZTVs6B-cQCtTon_7gU7hirFgGA17LlgKXiGu1w1fVE1ie5GiOVUDEQYpHmaq2vH2cCLCcFRR7agYbg7K
4H959kGdAExNZV4dAANUm6GeTPX4ys0GeBomw8UNS4uo-lMQNu4MEpD2VdDGMgjXd0Y1KgdOC2gKKj9_xim9-HrKY7-YwClZ5qgnsnY4K7AfW5hjB0hzEhqz
ZZ7Kfw7D4T4zVKFAkTIy3fIL5j8XjhLC18iGPdnZ4CizjUJbYxyQRj6-tYzG8VAc5C8SSikX5tyEjHM8hj2Ubunlp9WA1zBQnLyF85Y09B91XL8KfpQGkau7
N_mvr5XEAs7ZC6W9AAiXh26jIZHVgL8K1_VoZKdb6L7SQHBDdYrUbDu7WItb1PUoqX7XdiO6ZXSeKxXqhaJpjzJUeW7usrDofWC3fVPj8amCbnOl_c5AzIW6
uMK45fwDHxO7ACSWj6ZMdqTWzUkntbweSIYLwWF5BLpy4w1Y7FCUKW7IkHBDW_RQtzQXr0Z5dN3n5mU13Qf3xuLdusdjCVuaAEwopkQ3yEC8PANhmd-XM2Ok
bK3NXXbAXMS2qiB5FrUfcF4ukK6YYLAQt84qlVWNAsNlBZdT6MOlXbFQINHl99KCfF75lpsMW3Gk_ltX02Hd-ff8p0KN_tkYoUX_vXy
}

