sprite $image176 [235x171/16z] {
vDQ76G9120NXXLiEwBzWSrRCSVnhOBv7Up_rqFONB6T6QNWzSiaQctfknD2uPCmzZassvnvkiaFaAPqOQO6Mh6NMN703KpEXtMujEcvWQg6uWQcDWXkOcWal
KjZmYEKTN043GqrM8-zdW87X9MlvC5VSmDHCQ0DJYmw8b91iFJ28uQaZ1ILRtoxxYYrVnXLuktMok86fsLT6oassvvku0YEjamNSxhV_YcAlljWXlYFP7lbI
K-hDGsbo50R2GnhZbdZ_nxqmLNzmxw6pTX4xsvKd-eDk91mgZUOc5-ylC6t-Fotj3Uc-rRRzriZMhJKqzqs5Pt-1wOazT6mhF1pI_PrHCz8SM6321TMURaIc
b-W24o_H8OnHmdj5zkuUGOOU1cjWPFTtWT1n4aMUT1f_O8791x6oYSkUxLs9xm9vD6LedR2IZlJ-8UN49PfOPgtHvnLJszW5sgnFn_PkQu7fhPJMVVr2jLcx
uxQHZTvzFbuwV3Us56AbVjYCmMyhC9cEtR3UjBk7Ihf_lhbjF8_jHuMEdapMaopi6BTj1IORdZCBQBw-_sI3ssjSQ4Zzg9u2Adez-kD6vV8Mc51KMdoQaHoo
SBdHZspk0XdLxWBRF96WIJ-y6rxRkw6eRT8iJ2qCzpmSQUiEfbnGAKlykcgQzqNNufeMN8Ecc8IWzc8KbHaFpiamE0iF5vX8r5wDejBcYPGqSRSlilwG7iyV
TB3-6pLRHKMCzvh3mHGMPqZzY_d1g1_ZR2IopHVXJc_TLZDsCA6egir89ER3OBpbZgmTKZzgBYKnAXSLFcZ9y-rS-lcbyyZitPMenk8ZQVwciMWLtxh4aQLH
YaVbxfqTF7_hf57mgf5tmr6vHl8ASuIXdhrGWLc7Mkg7sacQb4z6VT2q-AiDHnO8GSNuaF9VpcTrgO5PW0X2KFL3X6hDJxk9Maw_H4M4O5VLrPckFHwebPpn
v5z3XOuXGh3HgBJtn7GKwdo0cX_q7mcnHgDIjoIKujalT7hB8yXuIOHWOr4hVKhcRs8-2iwG3aOLGJWgxsmKqofKvgEGuFKkeue02r2jZhotgtsDIUsOhqhm
U9THFuHOL1cetoP7COkZdM8ul4keJjZcGcKxVSnG5gM9SwJO0Kge1BiMbVzVNwVpgWo39XiJNiGHKXjLWDMe3Djo7mhZDs6cs1DIHcLXDIeVXjgapPZKB4xl
CYeBAr5PK1LheIlNjmkbsErT6rM0bQWid7EMHnAb_GwbsErTHcKX3DM-wC15wFfs5njKT3XG2JOOjJwOr2f2LN4tf2o8AGIZCWcNMnw99E88gGjLW63KNgbe
gXZ_rTKNKaQrXLXKKPJlLKP1In8L8Qzt6TKM8b6XGp_kw4bzcAH5nULTFwe8LgDo-_HYgc8t5adK2-f75M0nAXS8gVaSmsmi4XIEa3fGILYDohEYGyt6ue41
RqWPrGqh-l-2_uPziHkBK-7sBgEwOU_u1QTJiDU3X25kxpAgdnKtv4QrRxBCCiJlNJygm-v_tBeGANat03KSbjSZRYmOD1XLW5spIeq5XpGSDNvYHQL-Co-8
b48QX1eFo-SL7qyTOdWt7ZKULez4KqhUZKMDZooVLrGYfTCCWQZn4yld5SNmhbF8_MrXLGNBG5yFYbQyAwpXNQy-zlzFo1j6blKBeDA-tJBwXXExphi7tMFx
rh2GdmSzyuFKtid52qDQ7pyg_LtDNHWn30DH45MO-sytms7yDthoLH3mpkwP8cG7FNRNxVaCA9vSCDSpCBAvOAwd0x9OCAzdLYyUBvZM0La5wRnzDMEqOY6a
OoExJo7zFA0L0QHUF7a5dkvFD_P1LWXc6Rn18Fck_IlmvR4Bn0C40v1b5GZ4eohmUdGhrcym3jckfnckXuZ72yOZMt-QmICB11CX6ucdMZ37G300MI0Oq8fW
WsbWlOitc40me1M1O81uW60Kia0mh1LFoGO3Pla_ia0m2jb_1TE2GQq81AEG1O9HhHW81anq3HgSPb380i6eLWI2KSY23KQr8X2C4azm9yxKa0M2KQq81AF4
0mIZa0KLgDQxEi7u-T2AtQx1U6G1f4eyh__IuWhqhGWWLQtuujYjXzIB1mX68HlSYJErLWGLg905Wb78WjCCgXM1O1Ioe09LAmB1AF60qmog5O5Wb7Y0O9Hu
W60KiaGmPm
}

sprite $image176 [118x86/16z] {
l9TTakCW48C7OsDGT-v_tTt4ua7Bj2jiXUXf_gWlBQ4kvkT_bMj9FrzMAWre-tUXHqFxAzJyFMQkQ9U0S_iESplnX59envS2RIBKvV7kmXIRbmSwSajQPou6
wDfusPPGRD5wSzV7gss9RIvfPLjYxhwiBUlZZGEDuqrBsX8BRD7AjepkdW2Nv5fpzGRp25kqfYqgSWfaIQvg2rMJN7d6kwmj5An3jWPfqQ90UOMy9S4otaLj
gPdEk6qT6o_9-RO0mAyxSBlCiOxDuPASDnTrpwM9K7YkN2vtx85WISwt1S_J5Nfris91Gq_eKsEoBJ7rCjLrMgiQRTCMpRT5gMWSnq-UPxRxC2pJcM-BKcdQ
tbxgqsP-6dw7uAbntnQC8hN7sMsqBD7okuhe9Hct1VNuLmMTYfhwGEDuuEW5qKioDXVdUDbgfpQ0RftZUAYy9eYU6cDROghU6Htla1kK9DWntgWjCJNH5smi
o6WggHl21tiQc35riwVGBgKPgWemmzjKF2M_PdZe7MMkWSCKtFdntw3AkZcJrEEoE-a7Gi1yF9okJL9hN_8sSd28tIhOuq4gkHDKFXps5vIZzi71xzelCd-G
-ZiNzTPXEF9FSKbrv-1Xh7WnXMh0UrJAt5mSJOWNOZTNg1JUfPAhJmL-Nu9HQIwf8anG6NzVwDNaMCDWhb1LcAEsivV6hybvbOe5p9Ti4EQevizfivb0ims1
XbGAGNDIq7exJgUzX6u62JIcAdT6S0Sp5gYO6rEbHR11xLxzCcT3Q6vCvRYpsWWz76Bk37MUosrH7MBk17MUooMPpU-ObCFli7DSSxZ5WLB-U22Tvf-psIJG
GA-6RzK_PREO6mtQhzsEJtBlpRLdlwZoEPlDRvXUTDkTyxTvtjoQXl-ksfpDyqnaeaJxdzBhmuPX6821O7gbzbytw6cM7tvo03VYQ0WKbOMUPwVcfbxMCitX
HlLwBVDmlL8BvhoztkSWBHmQIQE5moDfj71u99qM3YXoMlfwlPPAqVgF6xJeUaDQE68aKsin8ncXfQytbHOxaX5QUaNnMegHZD2Y5CtlAhIuaOpG8klzI8IM
Nb64bbvHX9P-92Eqz2CPeQMlDrwBh_SvXYxKrtihjBm
}

