sprite $image43 [115x84/16z] {
lPQ9bkie34J5Zaho___kJ3RiL4px-BdJT-PjPBdf8eMGVwJs97zAxW1Qb3yZDa1LeIN8dn0ge0-W-KyoLUW0w5zFDtL0jm0rV3NJ1YW3BV8rodkcMDDDNyjK
Lz1ptKXR_4unACpj6hI6tow6OkyhapkK2lEbOYJQtx7-dM90yoJnNojCgE1Cvny9Mdwz62qU14_fNYs6zlnonFS_Gvryh6l5KFJmN5TFSgVxAyWC2lzICGR0
_QUiRdWgg_dzhw6RRe3cYyKOc6lCvj2Xn7sjtDRkN2XCv8anf0xLZNAi4K0B_rWC1ggiL4oUMSuLOmuhvw3dCyMO0m13QT1FQCASAWQ0dRTh9SNNiqiRWW5w
Ft46XhTCqJbYQ4k1NfAflLh6rb1XZYU65leY0NKtfzIWWnhu6eYU3ZAbH48RhzNfI_FwoaplHblAnTYhSjPXN5yNKYub9naaVU58iZE_IpZAD8-t6ZLVZKdD
xrWVQnalR1dFf2tbOkmTox4lZXUZsDsVrG3Sgpof_Kdhm6wwFUvSJoduq7ejzKKOHbs1DzaXKCkvC8Kp_P5aTEeUbJrJ2VYmGPK3ClZiEvo16z2JyCGu702H
3uVNyyCMUS5p3UZ6IhUoLc7Bs0VGr7wGt5xukWZdKDpDZ1VNPbLV_CNIDtq27hxDpdV30nlVaj3TFkRjudO3lDx3vvcx-UbBKm3GjXQysjYPE3wman2-B4_b
XtJjMsmwd5a68VvFa45nFl2oENQ4g_9pIyT-L4mxE6XFut16vKnXomDRmUVLwlvQwC1jjxJ5d5xNzZQHbFlI5fk_hSAj9PvSdA3PRgQadANh3bLUCnttvRfx
lGC-CvqeTmgZEy0XTwAF30ZEb9KiFUPPqQ0JE5DMdfTYA752E54wRIa31Ii14jCc7YYrpNxGSPseYbNv67Qn0hDDF59wawG-bxRu7FH3-PowgKypFLQA571X
U9Gc7SfnjsYOPdgibA2KxkSLBp-Lwup2F5F6rT-LlKXpsvN2dERtR4R1fxvbKIdcMsLeJTq6y_azgEudX5xa9daFDbk5pyz0kkjaE8utST32k1-_bA6d28aA
6ypcz_wCiXypZM-VzQRi4imKGIIkSS_dTsYdDf4cNwXtXsQO8qW8lVwufPakRyUPUXKczfS2GHH59C_7chbcTPp8j4SXjbiA4RYr6k9Fy_jKflFxTS5TcaKj
XPAbQgTqPy0EYZ4bjCUMmg84aTAaKheJeIzp-j7z_v6kLsdjfXGfatGlPyg5UNmdcuGe5IGzKmpATCQpC4LoammHYHFfOJ7uJ9uJ-orRR_MXJ1Bf7dZwi67c
XUbtfKNf3lDLUlwmOUQ5qNvJ9kbL0XNcv673p0lZbcxATYjDsphnys4Jv0ny1lQ7ibPHMxbKZEF2D6bPGf3YfBnGZ8F2kA9BQnADb9DYN6DS6egKMabvhHZ7
XIaYfBnOZEF2k3ObvVLYC7nfS2FbvM8S5uQKN8nV9wkJagRmDoWsw-MLOXoVWQmyBiRrmWpboM9SFWFDJnRZUc7CwNhAVA4mlb0nlanISoh6zodspuVDVm
}

