sprite $image139 [238x161/16z] {
t9W7hkim30IZOakSbUz_t5_JQHa9shCqQ4596NY99NCvAR6awukb6c0bXykaX1L8yN99bJkspkcxs5Ml05BxYm1ByxacuubsHs1nCjTOU4PwqIsJ3QnuGy-s
DfDiDctD-qvfc-erk4vNLzbvR4D1_sYRn3kjmKIs2tfmZRF7PcaTFK1DRLhRMD4Jc1cRsfIsONMkVu1jqtos-JN4s0sQdA-bCFJ0-X0_O6l2-GxVEjxr2iqz
tbe7zLsWxzgFCodECh2UrkJ6Du_UEexZEEV1MwSFmlcIuw03wsGzUylpCkAQY7q2ShvMp-yRNUjyYEHlmUNaRUG7zdFauqmPlNNwWD-kwXe6Rftluxpc4TV4
FhNKvpWxNnjlJUnJ_b8FurpYEArJIpbwiFzvRYE_NPKSpjiwtgSUkrQm1-p5EOon9aBf-vP_eDVnXMtl5XoYTP3rV54jnOGVNydxvd3YFoUyhtcGs1_VfkPl
tp5Q1puQNt5y2zhFtRxBLmqhDxxE5hddxdrp7E3MEOupvJg-Rz2QZtD-ZbUCCPnpJKIruqltC_2thzdr5ip5-8kjwKTRv_lnxIEstLim6u0aW9fEUUlyfjMC
bjx6GXWytHz04dt_vzr9xJ1sSfAXSQERtRPNto00dRZq1dV-KgV4-RTV-RSQzbBMKH4IMny-RJHhuzeNjqwBVoqrx3KxrnaNtzywaS6lwcqMFE1A-dB3bib1
ItvLoopOEbZvcrj75JHvXlXj7RFWwwyszDMjuvak6x1-sSxQMFyfhVC8oyt4_k8AvFUqstcbhtqv4NG6uaLY7V2Mk19cTbxoyZkF4sGaJAObQeVtDvBnHsjR
37YNML3YDngMPVIWlwmhYkzvbUbq_gnTaICxFvItLhJNjmxbD0Po-SQsSxAl_vNaZEGBPoJ4WSvPi6f5UtthO3Dnl7mVtJZVsBbSndGi4O2Ek7CxLwrehv-9
A9C70uyn_CWhlB6pCeqE5pUbWWSDh-x-7NHddTFEdyH9f-5iueFmy4Z1HNYN8q9juf0nBkohacf9Utth928M9ZxewP52ED6MoG373fiqMIR13zMiGzhvuqJ8
wC7akh3vgdtPtbJ2vRoR697fDEKrrZdjVEk0BaCGAzQtThwpGePq6NVTmDCBYsDZoAfQqbxFEe4CMkMAzOsTmMApoe0URq6J8Nae-nNMfht-92wNCPmuD-o4
LzoLS3g39nDtOUN8q0y-CF6KTluaZZA4U93odS2p84Uwkdf6OvgEiulm2wmpslaFiR-nUXbUI-9PBiisiO8kHnxARhJToFWzD_6SzlgJk0gvb8ed5KdcqSG8
MJsKNRkZQSAWi6lQ-EAJkBJWVPojSXrl_srMjObHnza5Pi1b0zObBNzTUfoGD7WPFWYbLrcdI-UPugvWpwuREIFe0nCl9VmTh9qRTjFWXvsN9fOnafrZCnAk
Dd7ACqr-TpGDaJbWNIFRfIVn5Xy4BDftPMAJCGCwb9h6PZLvjedtetHYOcLoKTehM-Ua4-lJdQ-rYG7duKnCnU5Y0e96Pzx96JvZhS9bMb-mBd5prwcyIaXF
9dwJTOAEjDhmzgCK63PiPcf0EpqJLshMrGMXAZvFukmpCV_m9D7eyc1Y_ySCMCLuE2rBM_fmw-nw12UnE9YMGXvDpCSZEyleIdRHNJdETLNYeBR3hTEe8dKI
JwmIruAS4OUii_6SiWv-vxteD0GnO1LIXMJnyxvrQS6waUX1n7BNjFfUE9Wuy8Vd674R3LtqYOapKyp4YxxbXrkdcr0bBSlx9encEet-m8FzmoyPOiiw7N25
cOcLcHje9ke3slzooIfoXTkyUCcQDvhEEfJBDXxaJJgN7MN8yKdCJ6u3Yk225fElnDScViUhDMi7zkoiGwCZjBFU8wuEMQSmdiJQUXvQNXUANt-_TQeMdqVF
Q864yt0Y-1RO-qD6HxYCmwpJhAAga2fcIfbONHVPhFEjKwN5TxOQyQOSQSqganD-lxr29aDsrec0SPPrChEmWQQGoUSfnPyFpiGdrflGTdxF6x8yc1XRODzP
aN0QE-l8nrc7cT1v73-KLZxOEXFMTxoBjisZYMNQJHnRODzP6VqhqgHXzxAobD0seCIZCUFNnrkdbKUDs_SOs7dJtSHTzcGaJ3uExDodS5yNE5qN-E_Arba_
dyxRbueR349x_4N2Jrd7Wp4wdMwelE6YbAb2sxbfQP-SYUzPv-tRWRqlvEFimducZW8xaeNCFYgsARNtRNR3NjuwkHPcTbQoRRgR66mJZxCECgbz74EPURyk
K4NetssTreTsLkVte1-pZZo6MQUFOjwdr5QJaYvidHbh2mFUbjC1gyuwccQTph1CR4ciTBykQfViNssTriVjswN4JXU8QTRf30kLRhZ8R5zhTYR-i4eVDEp7
xOiokd08kCHqwo1PEhGhj4yfpBOE_dmTLngR-BgT-xUKXCiGcc_O-otS_wFSjz2aOKDLDzgDLxi-OqqMER1po_U0EtyIxrkOcTgl2sx-dc-T_iwpnOE48QlU
PTydsHvmHwnDYog0su0g9WPPPnTLrRHlUAM1YQM_pO8rDN5hFuEFryNWJDprVpNdeIEh3iRWdKgmUV_NlMN2absiMFWMHAnwEf_o6_-6EREmqIglVQdZNzuT
JLzch2IcTHVUxbAIEeQsmVQF5p3lPCspg0Fs3OPuystvlLtKr36GXbPvjwi4of4X3iOvPcLxqhPk5sX37D0AhwXlNuC0mniESUjurRoo9gQqdhU-Ik-aJiIR
7QpUbDik8QaJq_hZvUmD6zWtODNjGb8deGruKTImgZ8LPzzmY7MxaDI9QLFxEjQ_LTmu1wowNK1I9wPLqOtpJ1ZMgd2S0T0BTOGrTNBQnBxkRK-JvurOpIFn
c3RczKFSTDo-0QkaJaWRyXvbxTctWUUiFdLoslrF7CTjY6wSoGOEP4Fi7qxaj9yobHoliYgk_fzm_C0DM6tgvBIL8k7LAROVWfCI71dMf4vEYtaJKrvW2lTe
6jZKi3ajTojVYilP5L-LOGrJ9wVL1CKIynOflZbhdZevhLpMFnpdOejlKyBgryIS5hrhEi3R-wHkr7MyJEh4j5Dnvbfo-nuelcUaZjBMlsjQp3amvos5I5bp
m-QqrH0poNu9ovT9fAnvwkIqMs-Qo0ul6crWNwTpKaSrRtzN8HToeLvPfIMJuxsOOPMRI-M5iAxlm13m6fsKEbxl5VRdEEyPaDXNTKBNEIgGM_Xo1zi9enmN
vmsnrmCVs3RElTKXu3qlTNAz6Yp9xeNZd_AUq7KItQO6ItD8X-nxUkhaki_ViEp3vkESfyv9UlAZnT7cunm-d3XHxsfV05XeLkTZuvodpkbVsBtUfKWUw86E
bzSqhAOHy7fn2LPdnILnbTJnUc6whHvMNc2bXUV51L8dSx1M1LJL8QVblS2Q60mqgLLXVmSol1TC7N-skwfWLcV1lK3NoM_EhIf0M0tl08OLFLjLSAkpslTo
gPDNXGwisfSNJXslM_c6zSiaX7KKmsfLqABG6sUEapg-AcpxaJbU3f4wNhTFLQYqtQg0pp0FQbXD8s1wODirX5Le1qWTKnNAu-lEDOo4LMZ7I1sFN67tl13Q
0OTOTGErAW12ErBg-BFTLGL0QVt3YN4qyNTL08HsYDJ97qkIYtw1_DY6zLL1lon_dDJ9gqB3NLQDdJg-Ag3gHoSOtB2-AdnONr-tIMWbTORMynjskgtu7usT
Elwv5L0U3Rz3MyOqh5Q5-VaBNsY3r1doxXMaplXAFgytlX2aplX2y29sV24mxFX2i2QEBmIfCxuGh8dZAtaaFhxAbLFdJm
}

sprite $image139 [119x81/16z] {
lPU9ZkCm34EdboLHdl__tTq88U8fuHG1adBlAm-Y_TJiptcv--ldzd8WsltdMxar0ExP_oVn-1Br5ObABwv_1Nhtth5ccHVnZNuj4pc0yGti2xa4w0dcSkmZ
LcX49C68sxM7Qbb1L92TtEU5r8ODId2YadwLHCyWT4mI3BjT8WqFzIt34RzkvqkZeshJyRn4cfXaaydlbqYZCVlRTBjTq2ynZ5kpM0A2CrwNz6lDHwm3Riwc
ATFfqW1XHd1WWRRcRtVQxkTB0tYpSM0BhgqJPBgrgJG8sy00C97fvH7UxgT8Gx1_b8al7y_3qiGiK9zqRQ4NDmvAmouFXaVCbmySwzVRrgHhfzW39mW6SAHV
DnjGhdEFV-hp8nRidZJibr1_1xkPRHl4vaUSWfrA4xQEkewCsatMNA0L131fElCpzWdU94ARMIFO5XYfve7wOU-Oi_81-_2tGxNMp6pvVjrD0ZKVa188TYRD
2BLc5GuCGbjH2JNp6LImKscsI-cj6TEQiqlxswzF9WPIi7kVvC2mU1kXsuET_NBo-i45EiIdqf2g6tzXZ_q6rffPDyzO-cNijYSDAd_y1-h9_5rZiJLn_N9b
owWma8ezQS2iKwtFGZWWqe0ZaYtzXc0d_O9PpvIsR50RfN6p0QhRs0Khqh1VSftdoQmq3ClBER-EQkuUJR0Y3Ri567UCL6kRD6vUaqUvfj24mMERjlj46b87
y0WTbr9zjqa3kKaBpsEO5a_zFoEfu-F13DHO-tLhDhk_XJ5pWuL5U5RUNjOR5Dhg_c8-SPZjtz_qWAT7U0cKVlyhZVJhNFjcEd1X0WMVGglTiAXfFImpddDf
U6V6jI_WmI6ofTyYUeHd5PRvqgMa_J9pi3KZMw5bwjgkkMx45tfY1yhLFpdYwQ5QM5Yuky6HyH1fUk-aoWVS4guAuKxwhLYPWt0WEzWlqxEm18yVS0nNlu8r
ICOTDQrH6iKEN0ItyDXlC12mzijfewR58eqaYIMOx3fWMSKoi42PrTG-BYN5AZYyoVvt0Kk_Z7aO4cs4APR1aB3t_T_CfMaTjLA_OzglOhNf4LgjAvXGJQSq
-zYtkwLGsYHD8rD3QJvW4G6TM5HkpLahuOgKfJJ3PbHau1LCe-HcJwWgZM9_UoBMO08kemeAaKP2QNQnSCIGITC5TfL6eqj9qvT3Y4GejqF00ZtQB-FB9O-U
ETJMiq-E-7E_AiqyzG1iNWG-WezBex6UMU2Xq2vWWHwKHlE80WF0tX6Vqg-yO-JRI9EcTwGvdfjb1_8lzrV0dwGvdhktH-O61dhFBk2FqXpFWXtlj5ujHShh
x_7Sq8jBw99Xu1EacQGbxtJ8cfv9SqPktZkf30WzGPfTYO7tDNrwlvfNF5fFWWCWLgGvEzQJN10hqfoVLn_kDB4YpVcvUv5GoJSisizbUN9DOzcHfqkpBp7Q
xUw_lrsakJ0tztivXL-HvYkn_fL-zMQ3qdmNoq_oBsCfpNUnSMg__m
}

