sprite $image133 [160x204/16z] {
xTg9bXAz5WNWVJAT4T__SU-jxj2MeLAYD93rB_SQdFMJx9nq1R1mYjQ5TLdCJ5VL9JOpSrjJHrKtdI_gArstfY-9TTwAFkAkMzFNYxUeBtVTchu-KnRrKUkw
DNszU8lwijeHpssfugtfewPTjwIlTDsQljmFipLzn3DThE2hCvt70hwYSztxVKbiodkxhnzc4zpxVNK-Koxlz_MPigWlSTUjw9iNpmvzli1CwRg9RuNYcVa2
FkBvqYxWgtFTYM-1uYtWIs8ptW8-QdFT0hwgKzq2lZpNBU0xATu2lg5ug_dwJ5dKrm-pHNs9PxgO-Eo5Fcfw_cGsqKrzhtyo6tMlyoKvV_QvrPc_paTyhekR
_jahzqUTB-tW6tGJt-kAD_W6tUZpdbSLxz1dviS-_yhJ3hE8GJVwkl78vp_phE9Pn80RVURtpCVd76OHNhH_ztBiCxyhJpdCDWFbTkhp5_XcnMFHYc9B-CQP
iW5AIGdcA_Z6uhcAIY9s-XFVdFojXrb4UCi59E74ycuVrL4NfWL52viItkMR5y-K4qfuQOsW_bPVafkbLSd8hPXbIfBidJvgDphJ2g2sB1ajFEaRVVLWQHjz
i1kXPd5FgRtBDru9c7yK3oYgZP9vQLfHxMxVdESF7sOHBaNAnXRbHBc6bqnvEl-EDUR7UR1uRk76zC7MJLbRKQOadevznnxpMHwTALQq4LKqrReffUL2n37n
7OlClyUNnGQUApALOjgtXsf1jJBn7PFCJ_BNXrb466-SvfnLydLxe8GV-yOL7NKF-eRYNS8z5SeKpgbl3qaehHxxZlU3pNXnwZilNlSfKr8ZqufqtHweVEmx
LjZi9sBYEo_Uu2FoCE94MPfg9Knyz-k4ksxYEo_Uu7DBQW9YBdq-7_dyRfqhCt_WPhxpmspqXISk87VEae69RnOxqftxKgjqKhpHPqR8GcuCOEAxFy6_yL5b
PYvqUYMmzsc2X94sIWtNb6VvIkEFj3mxp4QVDJ8tf5Ip7FZqEtsvyLTQcXLlx1-9PB3BwAiSJfM_pPSg_vBF6gfDUNq-Kw52SU1hAaGoavpujFlsvmVLnaDQ
0IYYwoO-RSXgXxvQ23hHnTodjx_XgtYZC5DS_Dn7i1XzbOjPHh5a4zxK9-QtIOqdQVORNnYDlgJEcHDQEB4Uw-Rp-Z32quYT-tpm4OTR0t5XCw8slu2-FyMT
vvbKF7O-VFcgksb1TgzLCjf4zsS-eBdDWPD5El1b2zD6gHQtcgYIJNX_wWD9ACzpyE-ClY99mfGJK3XhesoUTABxOn-GxUuQng6lNnu0IPXIIXoUIXjrV-q3
wdsBh7xP-zBLroyFY3SbUstAb7JGFU83EFHtsyIOZtrP6m6egfLI2Qyb4msyHtr86ZBHHMmwuUvp7tmf0IYoAGjdqunYMGVTepuW7qv3SzMudeyMuUwnzwba
52HMtfIDSoCqTvlePWzo4pVsOGqRT1hAlFEv-tvztL0fPMig1K0IRI2kx8DkwXFk_v6xVCmMkjE9RzxkwqMCxhk49r56Laa_jqT1ShSJdkmToipcWtlkwsqJ
xZ4Ntld4t2FslfO94PBukZsGMlOp7UKlHnZpd_gwHhwMTkTJTzllNrD2LVJdZoAwAOlQNAS9u9y--RslZRxkCLOtvfslFvxkVGGDWnGaIVmvdqzsRNW1YiSV
-3XXzFLOkF3W6-RBnIMf6QYqxAgVswFR3jD06d6_JpE6y2Ix_Ni9_qZV7voWcxCHGBCBtPwA4k4syOqygy1V-7wz7qhK42wK05Jpt_iQUF3fyHL88_o5Jtpd
iuhgtkTpLlUPJpFG8Xg8GFgBJ_gV67IIWB_mcV_YosJkg9IoYllKLx55e-63kVUPzyoBTxzFVPy-dnkoIdMV-meI5w16GxB97VIiUFVxUWPVJGdUC_5Lr8YW
Z-wLYD3kcuK9t-CBKwBcwSJd6eeS4L6wJrCUVDFYFUu3nDtdFgOQ6Nfz5Hjo0Ug9pmhmNJuFrwGdFasR7zHBoD4098sfpnhmc6-C-TJN3pD6ZYq95Wt4iMLQ
lE_s-TJN09IltH665C7DO-hJ3BpELq7fGrO_b54WiSkaU2_qDQ_TboA2KUBCrmWlzMsv-b2rRCYvJnBmBfzYIucvJpFm3bz3_MGYIKnzLe6t-kBq0Pq9x_JD
CXHlDTymKnRp-MSgy5uVwGcF2K_nHTphinETPk0xVHPNtVs-y-8znHUF-OR3xBjz4O_vTZFbCPyS-I8Uy0t5UynNgigDBnxp3OVPGxuCQYhVwTiTPW-5Fdsb
8h4-vfiNxt5V3Sqe8W_vnk8LuFjy4K9KLHxppOltk2-y8R4zwfiLxt5VX08n-2QwcQylRGAUuRFHD_9CvxxvOVQuhyryjv_tqQdFFwF0itoUThuZtHQnOv_t
oFDyuJJrcPoyWHtX_WfVf2_VPKiSVMP1r2TvhMydrBrEJttAh_DreF7Fg9xwJFWPFf8ZNu_lNxnJdoa_nLS9MIF2yf4lTASxyodBStpS2b0z37JhYwjFzTHd
B4_nTM46iTxw8hfFTvdedkJhgGbquulk4ptrcV3JVTpAw8lFQDTDVIhyqzUUuUl2dFodBtfCzTHdmdjVVewl2_dBD-YcFc7U-IhmJ1yFFbSzzqNmpiU4b_cc
ElkfCx_iVHbufSz-fsFP-mhmGj-PBZvq8ZkVLC9BVNCUNoxkBi8xNql0ctrTvvR_xrFXlIy3R_PrNVSPTvzTWgK2x_UPxtnwzL7pHdYDhqryNNVeGy_pVMtB
iQ_h8jxdQpstlgwJ99SRNyMBVAsEGBCzpmfmzUdLrmYlyjLS9ZxhzzjVlaRTbu3N-SnAlV5rdMowxfC4a5rC2bwITFNz-55QQw9xd_rolqqIr-_N1hpSPvLL
zpuRxw8IXhpEfpz-_2YgmjVOv8sLD_aINwB8ld_XRWbOnDToIgLjsVkmZCykNBfkJT-F7vjETLrV556LHNtykN-Pr_IrMamBxsA-YgyBIswZZnVoZJ7NZ9Lz
3LZQbz-7-kVxv_F_jk-Vxv_ld--V3srnNrhSXxguBxMrVQYB-wYjxKDPt4TjRH_AuZvgQ_jG5lVHuZwqMrzQswUqigyLO65V8_GikO4BbajPcmVanZs69KEb
2nsB9jMrVVrhQSF2IPNhkmt_0m
}

sprite $image133 [80x102/16z] {
xTNPUkCs30LWhZZOsBx_szQq84L9hSOQyxAOoPxytp44a6bbLQQ5MeQQhUFwGrldDJ5RvnKsM-TbKbleTJ5RvrKsM-SLgAtpCfqrzm-z9j-q4TwInZsqoFT1
uvPvkOUsm8l6BV9YkHPvCIEhl5YkTLuDRO4NCxB0krYk3xt-Ohc-UoEysylbirxacnzlDSv3U-L5u1kDSzNWmdjLRorNQBMx-VZ4EpUkjwRsePVtnWtK9jJD
x1ElX-RQ2gDM-SXh4ffHAjIgWBwySTSh79gW9481zyhXNSUpNsU4QswecNe5zCkpMru_pKZdbYgt3cNPFRki_veHzzQwjbn0kJqqIEpLwt8Fx-fKSclQQsEK
cNZpx2Kds3SkZFBgL7AdDiMK3kzrCS6Y3K-Z0os_kFAjoaCipnyeArzvcDwHhn68G3LcvEIDvzJLpHFk_T9ZYwUK2W7nFsDyzwmm3F5wvyPTdC_F1nMVWWX0
VB2V-GmwlI9Sgz2Hxtfc6dE0812ndjBvW3uz60fpgtpYBlUDP1F3bEDFPZub1IldJ0yjylzs7cG8la2Q8KI6R_d883KrLE9UwStpkOeGxVdKZ8c7sVGCFFUZ
fKwjoqaRPyzFNe3AH22mCBiHYM_vfBNEDCNAwdPe8mo1clk_FK04nC8WTcEr6S2zp_t8cP3RIVDXhKx3cQ1-ybnsZuXraazFUUkVLQNQW9hwXWMdcVpfuUaD
3yrwEZmGG8Id1sBV-jUccEeCDm8RFhWeTizspWqvdJpCj_1Oz_rzY2tmo5OJIohR0sCny-2a17Pus3s9_0DK8UQsUsDeuLOb_vmNrvRIfHVbLljJ2syCQEE_
kKhfrS-QKK1NNXJq2nz3QkCocogfspXvAEazx_pfe5J-uZ96PTSnJZDIKthJYpekpi59UXjZ7FrpxM7SzcOuoudYIKVZSlfJRypckSrmuJcNb3xoVDSy6lUc
vwyyvU5xHUEkFQAJv_u3ZFaxD3kMwpeVKNZkhxszJesxzcfdq5lUiLpNrK2D6Z7eLo-MwtVFjJV-9LyqxYtFVDJEH7pIz8Td5ZFokzVTHWzlrm0vU_RWKdhN
CtV5zCO6AjEZsCxbDpntDtvwOueC8eB8Dq_nheVQRJ326qEts_ERfmnwEn_Lmet2ys6RTlO4kE41L5Du_l0WMvsqMUzx17J2z7ouXRPxoXDZr3lvvXkcPtfm
-jHSQ7ejfHlUr00I_w6Pi2k1Uqvtl2ZYCwVYmi1GK4dfCq-tQC_67Mjsht_XXURXCUvOuL6dHuKtjTw7-VIOydqFXDxxxfbnIMqOP_9et5sl3-lCD3sDcwlF
-QYtiV3OmSzyPZrzMF5wu_xGjC3hmqcObdd41gPb-GZKQTitwoiyElQZfYNvGE6LHHx-z_wqwc8l4sYbb-fYBn5egLVNUX4ml9K1ITPww6b95H21ujfU4n0W
vBIiSWSal3LLEZub_W4
}

