sprite $image10 [217x162/16z] {
tTlfOggy5iRnbO4aQ_3-R_UmMtsN5kn3Y5Gv_ozxT-vFaWZ1qa6567FEfTRAAzLQIyuvna2dAQQPmntDn1G_cmH4q1S_qjJu5TNFqOLKAh-qLb9uFwenw7ou
C5K-j3f5-lDIuJ-ff7UhpcyBG7LIMsxybbeET5ony1khYOufDNvpBTFho_mHJU6aB5m9fsLXse6iyzCIVsIPnegLFxIMQA32j-hSXo5hUCKefCxgvux7K7a4
9WmRVzXQ75uqg3E-oF6mkQb_TdqoZ2-oRwQ5nYU1pQMkONWY61VQsCJdWd7jc5wdW7c1SBNtHwUoaluj34-qKFj_zAINPLsmdCko061Tii1F2c1MoYBkwl8p
Zfq3FUroSJnuwqeVawb_1YVW0h2Hwu2wvoGGmx2ixe1v2LzeXDfz6ObXM5OPm50P7uNK65JZ_YUJ09w_82o4tgbM0jAxlmk6PPctmzAbqdgnWQEmgeSdws4Z
hDAYo5qmqsdxU4nWeK5dwe4PmPwVDxO-cB9eelKcFBXIpov6kLmGp4jWWc4OitB0foyjR3om-VbvJG-C0te4COp52bxwwozwlCGddbacTJkiee68ONEY4tpk
4BpGb4ZhjNyiPSOmByCL4SFcLDBpgn-aJwLoBJdGUiLcbmhtmHYSIc7ODMq1pIBHHDqb_Hg5pBqmVnZB48n52pXcYuK65zXPdJ0Eu81161fiZJsnGXtLovmo
xu8LVsIxOSQFAKTQb6HLZvlC3rStp0yP3y2yjV78mfulDA0apje7ctoIu-nod_4YQIkFFD_oXGOKRalyBx02ODnp_q3jFjrq2fiMlu1e_PKMcq-kXwHhHoM1
fQEpkeGf_qoCCprfaekFmX5O0IEnixo46IyJixQy-vycllnBXLyG68c3BYeEUqZKBiQrvFJLLDeNokVMS8deo1kCuaDnpVQOcGY_gaBnm5l22Sm54LMrETMx
0LWd7gzHFl2cgLukkmOH5HwEod4lk-35ketBhtgrGgmyMerFhwLi_pnDZOVAF5gYzSIVa53hjyhpMs6PrilMxSellI5G1vTuS36rlG9k2Fmbh4LuCJN-2Esj
oiYg0IwcK7X7qKmEWE5A01TJO_FqQzFZBJ3H0YwcS2tGQX7DKmmRe-N5VXdtLC6EudjWljlXGqV6NNYUughoSDfs3vq6TXJtrvJ74os-n7SLdpu9AWyb3XjA
zWsTGikAFq832PlmIzA7RS2vFDLQEyypVPv-2iohKmfqLqobRN-fKNNMHy5AehL2hjjWmKVXMA9iAd_n9pMXR8J9Y-Oycmd3ShmlW_EzxJImTRmxsGgBy0K6
cN2nRbWyUAtyKCKm_GTJwOGbqzLb6vVmUKUeSCZcZJ2JmNijDT3cCdw2JWt09XKu4hzWAWCmCBd04Mb0VwtpNeleDyn6O9bwYmsU18So0XEnAqob5mPVWHTo
ALFOC1uhM6ZwOI9wWzbEM8s_tGwQuqJhJNY6fbzW2W_O5QQo1vQUtq6UCvqp3dYgJK3V1nDHXvb8Dso2By_O-gea0VfUcDt1L0J2l8kX7KNyOe5yFqeKl2ff
0GCkXvbsmIIH1o-cbDFgJer2_LpkWucemnQ34S4ATUvKQ0jeHrMUFrWTC14nXs5Pf0qb7uMBH0lqw_Efje01byF0D4i4mljbeldfZYfSQ13CNRg4cJoNPK8L
WpVybIFQgH6T1c0oPmu3CW3hsgdG1dTgbDC8p1Ombm4OMEBnPfO9qk-0kSjXG0PXVJkAWlsY1SB0E7GOa6NqXpxriJPyGm30WCjXG9Qfh_og6m8OvYvz0dEP
3CCcaU7xOn2sVhmS1cH3F_fucBi0p6NdWBaBmqnbxZGmSHU0kUm4C5ys4CnbSWAON5q8vhdiWs4-39Snc-63rYftfSV3_701s3AvfzcbgovOpQKhlkYLvQv5
fThJz8uclN57UnusPwrN9fi31-tmHFkIx-oNKh8vUD0-A3GAhmKoEmiDipmbOZiLJRupK2FoIOPeyZ4iDLGc2cOdeOcpO868n7feSWQM2P6FnG-ckSfPQ2JE
cVNIv2qgSHMAlcgsEVrpc-nWMQElelNaDFambHVeExQ-LBmZKM1cWGCsbwmxbIDn0bIWI7DWbY6RTm0AgE010q_IU2tnNc12ymeNo2k6mZXlG0HHk4BtYNd3
EA_JWuSVJkYXQ3Yi6qqX2XSNDyPVaixz1GaFHB0o7WnK1QBUc9Q97PEkPSUaj5AqynVf_rEMQRryVXUGdTY5PUTtZSlucdcjb5BLljBRn-JwnpsUsTt__Oq1
rojblFZYSdlRtxAvH4J54dbiz__tDvBqkr1f04Rnnm-9dJ1FUrsugFjXLCsiqbp8aURoNbZkV_x2oGwO6Tz-dzjnppJ72zY_Q8uV_-TlIE-JgWJQMDq3i_GD
Ql-DfF0bxONv5soiqVRoNbWsomzpBUo0JLrJVQAUWdJ36isrcyzN3Goh_A_7eLXiMnAfiz87I-5-YXN_W4BOjUiRCVHCiKhzHUbU5QijOTm1wtrKDT6kIYyi
hi1a3uo63XSkjCsmcccktTOG_y6zYySqRTofu4W39Tq8kotkzwlYj6zLJ9jsEZCDbZV1_C0idyVQ3HQsmTg6auH2BwXiWybjBDuUZdhzfPNcwXNOCCpW3ss1
NbFP0FEnM6WkbKnpwJO4AIRVJ5zTFChrtJwOZsKv3S6opwN_-havsp3iUgZrM9OtAOBvK9j-B3tiBWZpiRjM3VJwCjjgMkPihipnzLqvfIBsNsrAAJUV-tDw
_TyjzdUNkMQBTAA3YitULyjqP9dj7UaKwEZ2fFR7jKX_KwnwqY68YvFOyIbG7LF8pOwCfqXlAqviHoGrqzkBKrDxOLmIVKmX5tw1ZckEz86bgUxbSIifq6SN
KodCMq5SIqvqhb9APOwNjL9cpg67w7y
}

sprite $image10 [109x81/16z] {
hTg9Tk8m38LXURUkf7d_nvqGDsr4dB3-iq-eFmn4X7DAJnPYogMstlcttbkh9QT0NooaKcy6bjWt_gktcYDzNiorJvIZoTpAHtjCAyIkQx7b-ARae6T1xkLL
BvRkfDUybb_PL6Fm1m6zX6SfW3yDNCC7rFUvK07klVChuIpET55cCAFGl0YUrVEyqXazdcwhWVaAKvw4HYSn67ooM6Bm9PPUmu9WFHpeM1dK5tUsOWoET5y5
px7OmIFCiHxJAESmmPRIgSMevBKAmOYtW3sd8waqnv0FbiDSeR8BFJUm3rm2dM1UAs277KeT-sN7MUAi5idbC4RwMmeymGAAFmMtms4SBdySUgBVGlROA6n7
cQUO28yrzellJjFuCzdyf2WAZ_dNRCC9ncC4-DTb2UxHXP-12QPjWZ6AUn2F69Y1_L8Dp7ue97Uz4xifiyVy0zdv0lEBZzk24qshQc16Sr_lbasunFpYQVZJ
0Pl5n3qz0Bl2zepvP4r_UMnQs7pKU4V1b4Uzr5jD_Cee5FY9aEd-tWBzRpgbAgQu7od2lauPV9b_rk9-IH5mNuAe2XZyg5ZnojjxCtyCSWkybFCZ3hdpPNuE
5SF57GhrcaDzGFLCVpKJdeJVEnGRNzNvCZSTnUzhEXZpkvYRJP5DfvGVZ2BlOFw569hfoRRyO1HSOM3N_44gQk0Jomr6y6NW1m4D9inO6h_jYtumFaZuOH20
UyrfAPV6VnxwHYKnUM8XVgAUu_wTk07tbt6mm-NuqOA2VMXXBVfpxNX9udV6uAqsEc9kz_vwv_XsThmaGTnTWS7VWGxsYQXUlb4VF_VunVUlnWQ70Uo2YfgS
OdumXjAvHVAB-_Eium8J4rN56TQpVyzN4RYhcyD8Amm-mQ0tp6IA4UhXFT-FfzZbUD5OCSSWAwQAAHQ9feCHFVcp672FRfrYeWFp6Xgv_63S5XzRtV8NV1CC
q0qpnGLMTKmhF-DC3yF_2bCRcDCEMEY2tlej_itP68dZ78RL6jZGCC4yo_DA7fKIvnWmb84vxV8pyYmw2N3x6fZNNiV29OPXUMn9W2iilhCpu4ym4NCQU0dJ
H7bQcfS5ZBsb1jvXDZQ7itWQzAILsY_VcnrkmTzfjVPPpGDpcmE-H9cw4edfrpdCA1EYPgfJ3XzJFcj4qVIGwRiUXhHHhaX4F3jWfkAyvwKJoZejHPrduynx
JWIyTB8nzwmTzwSY-ErS6P2JVDPe15FN0Ln4mNcoEdgv2kYdw6vt9gxcQ0L6xlXfff6st9bzZHxEogSozo7EBe51sDBFBcnBTtzSB568djC4Wd49mIoc2gW9
H71B1H2ueJktl7PoKzEmNecOzJ0-mmVYVuNQM61SnpQXfGYRhZ0iLtAQmqgYe21gbGWhbgbo3PGhCgLQ0Q8IATbqWKJ70ji9PaAabR9Pfg8_c2s_zN-Mbj_-
_GE5Vtq--H1fMZMROZKlKBeTRfH-CKlKRh_5aY4KQfpDT6jqLeBP_3aJYzHMJEwn9HPQIaSBYIugQaUiBz2oVZ6hbDUTbHtMJ0qKsc6acrQwBZGrkyEqKR96
KNLHRS7_7CiRfecg_y8UoFMOCoKI4Ca2XR20Lea2aUmVnYf4sYZinrkFz5IXoexBIPPVR59YB6AgBOKCMzJ4jlosr2HbbPJ4VYXfdhekiswUcV-bfcxhjltd
9YcNGAyLAjpSVNPEeqPwfrXOx07eTyXEUhbKMTIkoEqernpeysAf7MFLIQh2hKJwPY7cKbjdo1QOUtlf-q7-0m
}

