sprite $image148 [170x209/16z] {
nDG9skGW28JXHgcYK7F_uyw-Js_nZybxWkzHuFPnPgKwm0WfVvCK9BmMizlLh3X-vpqc1RtQHP4LaNi5lPpQMvpAMGhKSzxIcHyNA8iV4v574UkwJEN1LiIQ
HwuWbcEVaxcEt8xgTELYXpoiGNc2AETqNj_gkS22rgey6MsciqHUmFU78g-Xik115y5v3oh5TzBYPxMORWm2O4XAIH4465erhKMJbG3LnlQtqJC0AdVXMxTf
AfDWzh7TDqR6pjYm9ICQO8xjkT42d1ZM8qC9zUqT8m4TbSg9Ry_jVOqxMkljCO_W3s_T684_LcX9wzrNDQiEXhArrdjlxSV9UNfbYBRjry390R3YLEjZtDtQ
tiJxLoQGOvin4l4oCeA4bv_CpFMPChDHRvnNWV3JMCmWmVrVxpb9xIyQRBbUzdzJgsD0y2ADVB0spTItRhn-BcDq9uyK6bUrAsc-rhW7SaHaVZtsigUE24VZ
7u6FpgD7-N4oPMRi-J05QCP-6TuKfK_A35U1ZmxnknQ8KoLBFxcL-bLLQVl6hFjkNK8c5ZIueIwO_aV7T5fzkp3estWiTihR-giDXssl5q3wn_PaDbvdSAAD
wceOdxM8NBYLXd7kQavOQp__sMfYSk8YnG9UN2Cj_Q5MTIkDKLLohu-rglxukWSPlxvD8dH5SUT3hUfMccUDqVpoVDxk7GU13Csrx0jtkgz96hg6RqNd49ad
fpwZEh3el9XUloozaxJ1rre7c7z23F-HIRtPq11vbYRki4-tgoHTlUImSPbBVbrb9rRb0w6IJJdsVmRCbvIg6uIocerq6qKdxsR0dxS1VyrdMa83Z097CCOV
FSxC9KHUStunbxsjRJysFfNrztvZXKwqkRJMe0q3dj1AneJzA6kWLQ7xNBPRxVk_w0I_2xnRK_S5HUSJxFTIH8X8DvQMbVTzlnP9DqH52quW5Nn2qxeu42f_
fEJy9usV4KhGU0LDSU0QZnr5_3DDTosX0QOI5cQTEJe1uDK-W3OYCwjMhz0a0OADlFLd_jhflxqujBMUCsJJUWhvq7slKni1c1cwfX_CFDTCwQPOKOiex6q0
vI0WI_i0D6x9rcVFI9jg2pBBR_EKBD9SgfOLL9tshRJ3XfOD7gr04t_wK9KgGTH8rS3lQozXsrVea0xTycsUSgVCGqz1xQqedVQAG9xEQ9hpjM2wk5x54hgL
p87h68MRMUzdfMhMFETTD8PXXHXA0XXtKp8LmRl5-pTyknRGinAgABKQf-6pomBDd-WqXh1yDLXeiKz9Ao0-JyRSXWWpW9oKoXof3LE_CyolTMhEdBKQjOXs
6QcFFfZZSAnEvS3hv_NQpEoOpLFgSHtErZfRt4_9thf-hC3Jfd-7D_HJ7SwjhLj96-hMjKxK-RyM2shaVMC1_Mdb17vdeiYYT0rf1YcdQvqLO-f12L2hFUkS
se_iZ_qDzqEco4nLMddAM4yW57pFLCdfSqdNcgB6gu4qVz5oI8OJs5EJsxQVpFHZy556LRSo5phrg4grbZVeqv1GwH5nVAeMRT_xWyjh6VNK7YATUYfnguqD
PMoUwy6cX1FOsCysSgzIoEXhuyOKv5tgh36uchinFOJ66C0uuMQr-2hDc-cPqMrKcWmshaPON-IBCeSVD1H4BrwlOdDIEcxlH0AUKkHN1oVAtZbHjgOepHWp
X7hUJB9ZLfgzcajL4lfDRxmVk1aNqq2o6G3OnU5ZhnS6uT_hmHIbubIY6SkJrc-F4DHeH9q60ZqpXfnuobjOpmgwlXyw-blf_xdVCZEErW-zKzIzf5hzDhlr
SUsVrOPnts5vKTv_ZtPVhHDlgwt_RALrvy2bM4T3XIr1Q37b6Haw7iocg-OwpSxAa4Vh8EGCKtXylRJUJaZ7_sUb7vdQ1kOXrucFqHUNl5BcrY2ZnuNbyYHM
IlNIcvKodrkTHkiqmziBgSEsr-l7yawbNfg9Mv-QpFFdcvXx-nzpzg4T9mm5OHWG0kxClF_pPkU0hnjWROdnduRbBLyao0bQQAtusXzAdRUPpeZ8Vy-oXwQL
w_ryNI1zG0g-2ufeX5hgPkQvLjTiJEGJ7qDopgjwoXTTjkDeXwPKMHnsTXFTTXRQw6niIoTI8LhAZOJZv7kPU2eTITkfkP5mkgVxf1FwBftq2DNNt0mTREgR
-IJqIDfEFVxeM59kQRyIcjAgpp7kQ5bloTPyJSSheXga3d5dYukNHJLAJRqmI0VIKT_ZTLRgMtaNJUs4woRqM0hfZrZ1VSacdQ3zY6iNFeitwU4ZnCiNtX5r
am8wZBZMwP1IXdIn5Jef-2PLG5TQGPs5K4eH-Y5Uv7G1ZMzI1lHJn0LCXozxVMg8-6McesqfpKbjmE8NcGxVzleezpjJ2r2DuUjU7vFwd-SM8DMSNVWiLTX-
NxoNcyZ6afNIn3yIIPoB0TnlpBNdLwbWwZFHuMCUq1EbwRDKaTJhIsXeHqfJ_ngKEpiJIVrRq5sfy1UekvYKDbAvR47VYmMlXnvAXRDx14Nd3kvcYqTV5HDw
93sdMjgx-f-bj08jUtquaEPZ2If_Z-0czP531BRl-yWX84BEGwUXRQ-FuNWk3JzhwRf56hVJeNIbh2-6mKC3DNR5XtLxgt7mu-V-TbYemzYmrtVyoFILwgHw
K_O6rfjWjAPqNMyrDNJ3F7bezD0D1Z-g-9kBmaT-vb48nvPzgNpmyHL5qPFLK_1VL5CtiFZBfUj2jOPkt68f_QI5fgrhK7mKrk_6X_Rwm9qvdToc3canHgAy
-X8zw8tpeUii7QIRSeQ7VMJpC8x5fz5EHAvderICjEwSfmvUopTfNlkMhkV1S23rvqfkJugSq5QfGrhtfTlgXmsACZAbwr3vA6NlDrdMyy0h0Xo_e-xTw-Ct
grbzSLNJsnNLTmFW2Kpf3GJ5fzNt6JkkLrJj-k3SzTnt1X_PwsEaDQLh9NmXpPxYTQo7Kaf_tNsMidYWxnPVYcxUlpE37jlh4pvlng1kpKlr6ax-7RMKYT9S
5qcrGXXBMVo8fSxoeyAM1RHKd4ePOzz9xHUvWqRzRAMUQEWAlGOykT45dzlhi_LvxEB_C7JTzA-wUrjk50Q2C3mI27kwv_rVTy-gc4GnmrX6slzwYsqRRlXA
hZHcEYuE-gpFeA-FrVBvdXkzrwNV-epUL-6ORi2Eh6yzONtGNcj9d58Vxi_rmVCrk374Jo-qazO7PKoa03BgBO0vei9XVQwnLKaQ3b6j8anzrVPsf-NGWSzw
KryT5h2-oDguejLTkwNLgiv5-FS66AswtcvfzRz8zLbqJ_IdBUjZ3p_XFglrjJxCQ7relfjYGkkpvbBxVwoFiraVczfJfofjWgXjwvjkAlN8-ke_6HmyrbS1
RM14dU2nFWp-GfKUGq7WZQbR35WVndsXSBiKTSnMwdFhMntiTkNEazP7lNWhmzPdk78hdxvUeM5z3e6BvLCQ7bYVMYEVmdNb5DWBraVLzux5mqx7QJauFd9u
hFFQhjDoL7gl1_PR2IVwy57GS4Rco0upJt0A7WGDoixOvnSgs1dhCqM0f436H_gVV5LpM9y7-q36JYg1WTDoL0s3rDxxzg4E35CVOzPN8pfGNzpwy3uzYqCs
FDONf6RlnhZrrQdnitqj7qTK-kfGjPRrAMsUwgIszQbDbJwnFkLqG_TB7LF7WC-tXgBpJAKUMn_c6hfVEjrKrA57raUp2GZDzSjO31sg3kiR2MWrE7uPEmZG
72YQvK-Bxt1T__p7vPByAPddO5___6v7-PVZiDo5E_7asBDw3ilrpmzsMrrQ0lmMBOHrIrsQ3pucE7IdCKbD_OVbuiN_Zxj8hNZ8iFTM__KN-OZlEzZtEYD2
7jeSzwVlMXBUYnPvAF5Ix2FWDpGcUQpuyFXrI2LnadrMsOU0zG5yF_L1FhM4-GmWUUWMOKJByhdRgto6skwdXwyYsYPVEuTzk8RwL1hbyy8S7EcFMLejOJlh
VgYljaYxOk6-FfaV3ws5AoAUgUChydsRJTHDQfD_gvlK9fzQvAY5DaEh79TXmsCMJ-bkWzCapeeDRHD_MMrOo7AgRV0NEltNgba2hR2Buoh12Y_TkIM9jt7w
dRLKE6RddCyhIf8-BNTxOxf8nrA1lILiINgNDrhdU5kardiih5jmpOoNojqwf2NB1UMYj73KRP4Bo-jD8tUyv2G3IijsLzB5G_TjpJAub9TrkzqLR63Rdx-c
skLx_0a
}

sprite $image148 [85x105/16z] {
d9Q9tjim2iHzIZ2WxFk_xHf6yYfDt5ytqyjs-VuU3f4iVzUs7sUfebqYjPp7lYw_QjtFe07GISXxAUSFvBq8SGy2eFNS_Y-YphndiCe_SjTJlX2VkVNu1wG-
49-vSloEVDPViRj0VnFgzc2pF27Jlb2F4UVNCHSynOjK4KKehn_CVWxkyTXo4JLljzmGN7nITVkJ-TI2Ad32A5xhLwpkSpMtGrBCymw7LZ42swIuSLJvKlZj
FeymRzxDc4rLaqHsSsO86IFJhUAFkekKqAwlrwkzoqs3ArLlMogrthbeVvM9a9ZXiCZdTUa_8ZOD2zm7M8iu7I5hCgdN-VgjLH38V0tVhfVJuvg3JIdQG79D
GQHELQQ0u28f9fVW7PWLw6Lz6z00mrIT2HQv7pFvAgE5YSMWAtDLL4uzesv1IsNF-qWnOVEKWVa4rao9zEb4o9NxVXGQ489xQXv8ImjrZEhSI5655FMCbA8O
rOu67tZ5A9bXp7CLPru5B9LOPxsDgLool86QLbg7jGlt4h4SXJ7F4SbyuhtcK9izNXfS4Lxcu5buP68gvxvie-U1BShCgo3p4o97TrDgEHMWpKZOCpCRjRq7
IeHOHGREPvH4pa4V18KQtnxLJEohGNDiSwziO6ZfCo8t4WDfgZQTIcWHFXSpgTanjS2oum6LsfE2EikPRx-HBkf436oVJVIyewe6JRjkW9pYbjMF1H0bPTY4
rDhdeTS5KbaLBUWH2USYjq1fGCqCMP5eEBsnmsDnXfTnExekmaRqyeX0bHDVzcNNAfGgeDsi61b_BC6N5VADgwGCR9GL_0fYLqttDdr7OcDvdd0ZypfopBA7
DCSudfagiIeCXoVKxeqcu0WoloB0_C42AAOgg3dlUf7TClrmkXrZg951didxM7lpzgesni4ODw8lQIxebktHKzr2tcuPf7Ady1HHYX42hiME1LS6TpynBz5N
kqKA-oq-1k3zdIuwXu_bnjQphCUwdQf8gOuPw2KSRcQXSXmlZVVV0ZATR5HQKV96p7pqFuq9nVTF2gPxG8-HDnw_I8o8RcncVJBfb5lIlmO65sR8LATSdvap
r6Dyl-eZrITPCWdTUFrabYmy4sUR7z2uDVrLzZzAddqRjpzZEKblKFX4lR3u7SaYxk4KVFGR5aRaK4CwTQNL2Vl1VIOIEHaTgmyJTUBYxy0F8fdMEATwzshc
1jW0VEKbS23dvDNfjDcWVd3vOpPh-fyFaKId3QH-ydWvwu4tc6W9FI8ag6qkpGzgmNI_eIseyxYUwnfrwJRbkXpBVluWUMTwC9kFz4cTPg0T6pIUY7cjhQvI
lKbHLwtQlAfwYqTlJ7nTVJHBw5fEo7filc_RNfTZARgLHRTrNsnVZmNdTcoJ2xV7rGTMbb1z7OlPuWrrVPs7bRBKhRQrhjPMMOzpqU61bjhJwaD4HFfsQLkg
BK2fQpkFSqD0_U9LMNGjUbeRoB-kFlJ3V2vNeyvTLvphMcHhvrdNSvNzWaAsOq7TzcDQ5H-hxxs3YRMKD_C6DBTcrX3FtSsF4XM01d523e7GpzK76zCp_-wF
z3Yq_RTS-qXp48Y1AAmcWwJx7zTH7sKRTPxTr6hYMvdVeR7YnIcrg4UVWN6MlgyrW5DCdtL11uHv3inawCFGVOUjZHNJTqJe4vU-uwHFgkdpxPDI-b3rvikN
fcy4VLW_VI2cOzPmwEl8-lGnhhQAfUcJDtsYRSaqVIogjSaaVSfrsLBwB2jQ4DPw-d3P-Bqc-dRGXpg-oz7t-x3twSFOUbRyfezRwCFF-2nYAdk6FdlPvx_e
oz8d5VJvylNJ9pQt2Vhq7z6dBdtQJnyRVO4eYFunVVGOk_JLEWNwzcTqTUZJug8b6VGjp-Y80emgfy_-7ZyTwBb3vP8r-pGHL66FljqEO_Jwx61YY9wJhsyi
wD0tqdkxGzznsi4N-LBqRMGByYlOvHqlv4lJnm6dKQfn-ex8YpwNlf6mEKsVbBte4vt9PbNjfa-jYSqTI3bDsyYTzF58ruMjYxuzaBk9LLlHdocsi8Xg2z1h
eCJ2sa3VEb1cOU4g-dW9LBB93gMIitE9YOeNffKJB_lK3dccG9KRvXNdgBzlTm_SBL6zy3nNt0-6UqV9xI9t
}

