sprite $image11 [236x225/16z] {
tPpPUlEi3aQP36Yu_-lTE_ru_gPnIiKR4XklqsRmYYJ0gXBtRdm8AQLSIgdqXF9_Kaen1BSkFgHK2erGIavnBUUGjXP3a99Jy0jevafpg6MBPnNs7KsSakBf
F4kbjr6sk6GySTzmkEXMw5FKV61uOwxqOKho2uWkg-ktIWVomMIEXOwcPl-9aEPAfw34zKAAKpV_HjDA9oC7znPIfHDImjLCSLlSzFgsiTB9ATvD8TnCImAe
z3dobFsKRYG7K80RT83sr3IZK75NfW7mjvbIjg6yT16a_27NnkPWDg93NF6tgT51-49hkU9hL29QqPMg1ufWBLVyHNobvLp1F8w35n6VmoeVTCNoUADHLzQd
7ELgNuypS15fZcijbVRKC5ug4J_PPI0P84HtL6XPoAWgbR7z68SVgG5S0ZEeIiLuHsIXa9qQyUK-0whDrKAotLZdWRKATwLiKCLT_zQ83pSLFR9tWAjHjf3L
DM1bkrbx7Iq105UZR2QpQzOqth8fVY3VqvJZMG9sZRshSkoKhMMPyTcG03iynOwhSP-DDEGgBBkZM4yZzNe1zbPPKUsxMewBlWww4h7aJal3jCoaiNqcgGww
KksjItPN8fPEsTeEuvkvKDknMzAGA-NEMnfTbRuG2fsrpbI0nRRF-Aetc0PTTuyF1BeIIpM5LhREUQjdsiZDb3gkjfAji6ktRFszhCJUq53fZZ8bQRTD7LVZ
nIT2NPj6CiYIa7SGWRvCcJ1NIhihGbsRXa6MDJk0qjANKDUwMqHGrwPHBEiiItA3RD-cg2jjkuK9TcqQcti6_KGukW7YNQ7YhjzPLr3NdKPmUvBG3tuvR_Nt
cLTTiwbQ6wKyjahe2KypL9aQdOMxly-0hll0PhB0-W0zurc2rlr3MPBLLEYHahPyZwWG6IiMx0IPZvzPcNQ8R9Ri5Ki3pk9QszwAWxiIYzRqc-Z6sdRKfx3y
XEblOcTb0ebk1waGFRVL_MnXI5MqOufIsig4OUrQTtAClxI8yZyAiMfV5CVFJU7adf2QQq-tOHF5Bow_UnI5LPdwC8k8g8W8CtspRNCdPTuzKBMfAZwqv0jD
m_cfQzAUeAfC03NE7YGBQNQXxbNbnLTCD8SqeoAox_R2Nd_5J3F8PV8-ix_nv0cb7mgzJgblIryN1OjgFEdyP-xqvs-cCk-pItGiXhRVjE7OVD8fvQGtP6Bf
Ry3hpQ7VqOze-XewCGVGwp5KD7qDdPZ3RTE4GgK2bFu128LTVtwKREZudmAMUh_FC85H1Kh_gB9j_Vc9czVSGcMQXCWBrvK-KgXCqn0ysVmdzXaMcWVp_SzX
j9yz2I6ahOnNQvtUZ66bwPGKt0uVyr0Ar_dxZEW7lu8Riztr3QilzDdXKtL-ixhIT5MoVNev_2GZferiEqW4fScmgWA7cjGnXUQC1mPqC_e5HL5LHlxxojRR
CLkF8TflpWFw1KLLLK5S1PYKx6XKwwJVthKAcrDOzNNNx3gOD3Rpf7a0lmIqEzP1hiKxW51ClVGqorM_a9TSQtGWqIJhjYckhFzWrBLVgEdVCQyJzcGgULyc
k6f3ODVS7VJLHhMLRJ4itAWhgpOOSotXhxaEOI9YaMpxdejXqXnqrVyGo3N-DId9fhbB-ePhjpsCkx9-mwEksft8RwQMWSLDXMq3YxxWhdhFg2jvuwHaVs0n
okDZcLEdR45NqNjao3KbmwJa3fRDa00a_RADuwwiF-6-gv78tGzEE1hQIVqlYAHnLtq4S0NwyzyQQPTFmC2YoLNq4G5SWROVQxRqVLdIB5VMFGou8lrvvcH8
018ASrnLXsIBTIAV9jvoiDOPhg9F0Lon_ZoBYkbX6-JQLss0hfl154CalkRA-Xi2kQPyOqiFb3csv47NfZegMnn0clHBLHJ_S1L8LLNckMxoeLz84KnLLQQv
PfLZNLd_GevptQQwiXeupBNCT6KrmHTmPJN2oxkAck75NNK4eNjA276OUfWhwo2CFxrnX6l_26ouKjILoS3qZrG-41O0o1KFYam8p4GOmHfKqHx2j1AiNGpd
urLW-Kl5iCAiWVmjedyYl7pwDbTHW-tQfetsiBLjxGggQzkog0ac9b4ZmikQjXGcLbtMbjMC40kHZi3BcJRuorLq25aiUHjjVbW74Luef0rkhgAwb2wB3lFV
hBGY22yYsWgFLQK5TWbT5iMucvLM6E5JYpQu1PIRyubzcoVEZrbfVH4HFgldZt02Q_YduiixJmHvc1yMdOC8yuaqTy6ahYnkZ5kAJeJlzPWC9Oigyv2Zw7Ja
PurQZrquSeCRpUmVOXB4aOUibIPxHNPgrEIlnzvChYhBJpAMhodRj9x6cYwcsl_fo0kgyg-D9BcQAgbUNRRlGmsvb2ht6uHyHTNrPN4JleYiM0QTc5Okshs5
yM5y2TLhomhjL0so94i7bSOUpGi7bOnFMCuM3vCGhPZ8ZCM8rWijFYhAYzaAlv2BGYlPicagN82ft6F1nxgfyn9hsDelimvCWV3vJLaxPEt1vxOL7farfJJu
QYpdCQMnI5G__8h4fmgfFGgR4qj9d2suWdpJAhfgMW3Ef2kCpNOvbz2N9vPZH35JhSuvx3tcw-8NeIOsvro5twZfoeSycJ3JXdSjYG7RcU75trcjiBi175CW
t_cJKw9sahjHfmqnCSi7yXRxSDqN7acehh2yVsY8TOpg_a5O_S36k2LUBxwvHYo_PWujYM4K2XLjOMtGP-OF-GdO72OIrePVONmO5srXRHJL4-dEN-BTFLFs
-jDE46_kdZHhCppZ136xdzJ9XvpvcZZ1FJ3vk0Cp_uPYSuz4dOm0oimTIn1oUx9E03adC1iE733Ydb7rYWJt5DRhaTmlwENe_7YtNepgVYTSLFNwijNr2TTK
nMNNLsq4rYjGd8aho2Pdf5vNTS-cIyF13H0ll2hj8LsLpGspNJn_rzzyYWF9kXWI7KoWTODwwQgbu5wbh7Tyk7WYPpU9o7fkgdVpIBA0wVLjQtJpIRHUJ75Y
rNDH3AOmlkXfaCszcyJhbIbEACU7rBkFaQeUHmckSN7TcbpZshe2Y4ua5T7Fm3cum_6fBXXGdB1LUP-dTsV3fq8w5yh9dPUGyXHXePoyMu6OCh5YKCqfkgLe
ofb8Z86at2JN9iGOyurAzzHy8yRetIVu7m
}

sprite $image11 [118x113/16z] {
lPU9agkw3aKzszgIxlz_xYjIhUBGiWCTmbird24kBoGFRC9VIBdKrliOHCOOlRLQSWmFa79jcmi0EO1DtzjNtRdsuNLp-MWbtJV6yZAIPwqUxLRDgJhZLNCl
yTCgoOmVYLl-UvdDb3V4e_wfu6nbtWJKqcNdmER4XCUygLDVGaimXm1gftsEZT32aa4BQYvpSYDGFMqkqHlhiiVhDXOGOQImfe68y5rh5TfObfi6w34hUfot
WZQyDRRU3VdOIg0y-nLcxU589Z5uPHs47oWvgr5cKcFCJXCDEW0Y-9F3riYf5MKgDQkd_79GYwdxmbjSTDYqJkgiAOUTMF_neYSxP_-0aT-igzSMqCHQv3Mv
iTUspxu_ok-xe3PltSZxV4GpQnPWRzbUMpjiSFmu3oCJ_JVcLeesPgoiH3XklFhwlHuVXG0wT2LsLIngHNUBwgs_RxCoQMOg5XpCeqoqiDhIHg9tLiBXD1JO
nbcGiJa92wlrk86EzADryzRZQyUsiISE5T3QQhz4SdHw0I7ozrLbUvJcdKqKDabC6x49kMBTgcw0Nm2pWvPvbHDIVose0U4DOJTzjOwTW16dTmrJhtahATV1
QiupHaXqol7ua1pR8i8i8YeCeZ505qYJ1h-zNOlYtS1u9T6YTdg3twnPv6HWwkVQFawSenmYZZgfl_hpe1FE1bHt0NZyRTNf7ZNw2y23NrU_W3x3NKjD5EJn
qSHExGqiPHNsK_btfXju0_H2AXQEuC_1OUNbMYddW0K4qEYzTVVjFlvzhmheG-lq-stK76toN0TcBmPSRIxykE4_uD2p-yB5nChJP_UmNmQR9U5jzii3liEx
f6Vxf9iWWhCeGTKP3m4HrJ_A_f-5oG5HFh6wOEq3OdxpA5N8mIg2fTKrjvBFgh-riPrQHKHvQSKe1oUhC1Y7_ooJ6x7ZhHKgiXVhel-nBAZutHK7JnQ_Z7TM
aHTpQygpx7VCgasKPnizjZQrsghw7e_WiTaDeBax5yVylx9237ZhsNiLLEbu__tQQIkhxBopPlfFCRduMR2CTMkh_ClQ6ckhvOT1Ps0aR_MBQZZhZ6NkpD58
qLdNKfKhLk8BxtLlzT9TYy-jEBMQr8E7hQ8oWt-qM26WEJNbEQcR5GUJxpBMq0hM1LOAon8RytNmgxjkBuE-ZI-KuLSNNtUgsq2pDkEXvXeWrgUyLgU709bW
mUOUc3iLOB9VxXRibOkPXI24zJdwM0osCZtAn6vblHYVLAcoX4YKNR5EVDqCi9Xo1GWgGYTQcuRVkW7mcT52cgWeoFLuhTxactw7Dsp01Qn8zn8waQlx3vNB
W6WFfl8y9eNkV_s_IKaCSar-JihcKRPKyoIwIm_QXwMMOtvfyMINsQHE-rYNLM1IftsgN8jZ9lLQuWUySEd91JLysmkV_Dcj-9UzcCKdKbVkFQ_FGRwxtDLl
S1kdjvGMWVmULQeggnYE6s9JsZm7jCV5hheXjhorNgmSICM3O_0IrSj6KwwToY6KvLUbZqDw8UMS1s9j8GJMqpXiQZR1lyZ6vWDSL9oJGWXrNG637DXWDl3Y
BnbSHzY0VZE7UwKlTIFhZJZiZLxfLtMZwuqqxDRzP3840ten3VCcF-f_blbY85P9mKYi7uHX_z_dQ0axsVhoC5hD-ApMxwIrzdcfQH_Fmrg39q8VbKe9Kxhg
SrAaiA0ybeUrXJLnF5Ak8eUt57pTgzB2APM_wbKPCLmWDkUzuqnEyAnNdVECGg9wqyajXh-I6lHJiMvbbl0PkKES-OgIHudX1gcHw6NpQoHw2VU9kGqMVUks
dwcx8k-GIklqayKz8epHQWgF47EfRGmYIyH4D7gh-O--_m4
}

