sprite $image88 [118x82/16z] {
lPPPOkIi5eFFFE3Q_tflBkLZx0e9_QSIwwddhv6G3FnKP8Pmir3yGmAtYhqhdE4saOMNZ6uoL_qYlIDUyLS5tXFeMT4s_Ej0_LMvRGtl2xGEkbD9y8v0Yzcf
A1ukVzIMENMZPzfXzEVc3cx-KOl4lrIsgmU2Vz6Mi65rUFXdyHy4AkFa9X-Qt6kZNmvKSVnYz4EHJwJugu7IUIwag1F96u6-jYMQu_YzxwYfFmrqrfRMzF3-
QuSZ7_h6Os7Mq6GuYGOfusZJjdKgllLjiUlU1t-cPljGnhuSRTCUlhpL5jJYwuVyXCNTWLtvNCdsKB3U8dwhBMoNItoXHhQM1_U9NJnnLcsnOVgS6Xsu7TpC
rd8rakksZ5kxKv66E3hgiJrEtFXl8qdsxQqbwrJPsbaT5l51hf_dP2H_y3sxEijrbZAtioAsH-i_VxJrIABmiYsj6NwkLJuP7vIzD_sWZ-rYy3nULZEbILl8
Ylz_PT0BDSfWpztRpdnSxPt7QwQgPg8nQOjtuTCIl50Z9vbEp9t7c-7QkNQ67kONzIAkG1yxB3stfzdXtoftR6Q6QTVWnhYr6dNMGy1LaOX7PRemjrvPV50p
tLHDTPmtsX4ZMwVggIqvlArC5-RMWttZvxSgky9DxSBDrcc797PbPpmA5h6rVpEtBoMpHnXb5bSxztJSfZ1jIrTibMbMMnRcRkrunEPGs8bhPkhfEAWnsb8N
wD6wAj3bKLlK_o1BrtYX2yyELrlg0eMtRGIwLEJEp6tRgH5NcmrUnMNkbcrusvfF7XsBCnVL4ELgi-1L87bStZWoRS6lKxgEzw0A852Sk6hgsLxL1tTiOBPy
-MmyirWoMr7TWKUy-sX4ANVgo3HRzhQCDHdKyBcocDlE0Ku3ExVel1gvPvZdZsXlQ5uUoDzIinMpAMIN0GLpngn5qOzv_OYE-SlHQYdgj-PkZj2fmMP0xf53
NjnyGiyVqJot9LfAnNkXpfb1nmupzDEcsvNRiL4Ng4QXvcyosYVgF50vhR-1DWDr0FJCSxo3ksSwcJ-pQ7QcJW_QsZR-L7O9Q209A6FCHZAxjpbvBDXanRuE
T517OmKuY3CdyVRsLg0JAiofSJANBqkNNSQe1eI4uMBdaQnuim9TKRzeorLIevI1vWJ601HfP2ysnpRxjkIhudEWc-7a6Pox5Dp5a8melNmON9yfFcdMbfd8
ZtY10ha5g0CXw3dUlf9BpTio5qV5AqcKgU8WoOKTBLfmbu5EuYsVOn_9nfWsubrm5ssP2oqpEvh8o1pxSyuLV3BE4qtQ4WnhLRp1VSfP0IYAUXddVpFt9T1r
l1eEqXov5NKHxw8j2-bnBY1lUd9u4U-YBUjuUxgX22gW2cuaaRcsUJ9_CwtZxLG5H2jeZMJd_g0jwnOvFs-JvUvpNEDLMxHbhVb8DW5dP0F9YFJpIAfQJDf2
y7DHMMfeX8p0GIW1SehNspPfotkgOta8PY8R839AbY8_8FF7GkcjU8D8W1Kq20OrMwUU0oNu3M5ji128WRKzta6DDzgoRb4A1sXpa22KWxgzqPRbI4QFaJ42
H86HY_fsMzOZ6OG48c21MjJtsx8UIM4G1MIceiuU2xyVBuk32O9Nhej0Vwj5IPJEHPq4-aVn8hB4JcNuOutsCj1ERN23ZktFl8ywuhsP2gXtKwj5zr9BV7Ek
fQCvS9kgHMriuOtnll5o-1y
}

