sprite $image188 [241x175/16z] {
vDW5biH024NHmc7_2nvNHjj8pi_RGEjD5QnD8azP1qhheU1ra2JhEQTrW3ZghTI57bbzAXaTRmkRiaHzbu5I9gyMDcMhNme6FOf-pWdqAFev8tIylHJ8emYT
SiSBJfcZJis0xf7eb3Mh1KsPirhGbCdhiXJW7ebBkHz5u9GvwbePmUFjAUXHz7CXy7XxJW3_PWZALZSh5HvlBnZsAFgPCYhU_G-EMaEbxF4e0gVSyO9J9glv
T3TuqIbpmmjEkHz5w9IjjautF8hGAVUZ29non-iiEVQRieyFZjhVmvne-qPJwYnUf_Qp3poNVUv_JHslZC5E_krR7xf71asj0EvfDzC5r7KNY3TxEi3xF-v_
kHvZSvrOwgaVtVCBC0EfxPbi_0zBcVDK8ju_Zoz9w_ijYjEKa_Z_jhFAlxMeKCyQdGJ53tcXykyV_6MtMVOptg9cYX_occax8zxB3wo8ytPxyVPSxalat5_4
jeSpufvkBbw-bG5c9aEwRvEl5W_596ecyNGSR_5EA-Bw7CLCCOS-jTjcWtG8iYPIQdUMChVM_iOhUBEFVDlbbU6wyaRCjpNVFGJ6EP_dTFRxbD-53caj4t7e
DmwEiRecRvZAeXEftrVlmYQW9e48rnsbJEB34hgPWVE6TaDhHOXttwQMSBru7GcTrOH7fGZ-0XZIbiHjsjPRpe1YSsPRaC7RmnnvDSLVDHfxeFe4q-GyN6lf
ZlF8D3SSGWE_xMOwGj_ycToEhXkeFec1Fl-rHHM_d4HLq5QaJyxiFlChi-k2wvDOyQ-t19SLEGkZ6wYILJETdRauhMXstPqdjMBQzKkZzEMHTd9Q5ReFMTyh
ErJt2MHz4JTA1fkt_VkppNBD88k2AXPNijYySNZ5M1Er8Dt9gg-NShvw4Hv2c-jYEXJEkPzjfKyxhM9e895thzlJxbC21NrQnlDrAG-zjTQd1L4ocKCytgxP
OSMysoGbvYtXD08vny70UvH3_eR7ZwOwrGhJfqPd1M5FEqhPMmOSk81scqqfH1eMbjylkKAiqSqHeJM1dG1xIzbZavIiWfBje7cwcu9qVE7fkXfOba837HNm
tP2IYNhwWHi_403rx302p4SgiKAhLIAN9n9uNobxjySFl7FWqOaih50vC1p0-Gf24tmBN3XmurtP90DCdnBVjKXIcYt4VzuhLv03brrUKOslAb0Xw8kvVlFz
edyA4xc0Z9M4yAS32INi4ClGLPYLDxvfTP5JxY5RpKok42DHmqUaJqivF3jEZDHiF1_LP7ZpSSnUbGKr02UlgDa0TYAZqguTbSP1P1ZVGIh4X9dsBgzHhYaV
LeHMTe0tcoTW9pBl0x2OQleVskb2Z6IQ3cQc3-QaGYDPX5SstBWpi03dQS4dqSMfYrfBJHw_etpIoCSLFPYJ69_205x2y1Gl0VO4MJBlRVUDvJfCzOcBAKl9
UyUgr8GE9LbvaovmX9S0kv2ncDSiB-OxCrCLh2Urz1w9nRaHLasw0vS0-v2XaOPO9T1aLrC1wLsOnequy-co6fz6ktpEPZCAx2rbRHHCx02IQdy1y8dwqpYB
bmddS9osQ0L7nOaLCM1_a4NZGf_gS23xiEVroi4IL9zU5SH0HQ2h8vi9i1SPsbVdu_d_azTZIyNHcn8_f-jzCCEKzY9HnO5BWDt8efacf9ZsfmEfNBen9Psv
YUvOATcky1Ol1yOPCLRNxvxxgUoJn5SzpJ06iu6U1HKLT_5ou9Zt4sInJkC37GxaEGEashUEiz3ppQWAVpPpu2tKpr66Qg5t0c1DIwFZ7_0WGY-T19XSoMOE
l6sXyLAUzEcR_tB45N3eN_qPefloZBW8l0KiYESh0ey-MVmhlUF-61qpnjPCGRFvCl2sVzPhDObF1o8_wb0ifpMnpRQdLrKruRZNWUjdYuAQ3WSYl5x5ujRa
dtp4KRm-u7pIRKAP0_aLYrlJLMPrM94JE3mUzAL5GLbi_Oh5hUaQiv8WV0SyYZXj1GjauEeVpUw-4mhWkDU1G_XJnF-jtaou74U162meBbVb___TFR19EdJO
PwBnMwovx_aUo1A5Mm6uTA9W4q-iOJHDBpW170uJftslwS3AKmfNVkXcnIM0ys5YQTkRN-IC4yhVl-F40UjEgUY02MIFJjHpguyY6jXN4wSEc41EEAL4x6OA
E5OJ-mwO87Ou9KViPWgur75-tMKDc48EEAdm1IuFx4qTKBUX3msOGIuuhK944G5i0YGF8CK6p21xd9OGvcM0qxwPeGsO8KwOK2PsCm6yeKgi0PTSz5jaXmbv
8ehEATkRDe4tCrJb1fngoVmEEM1AyJBpLZqAVB4tvT1AbjC6x8xfbSqZ5yp9NMNUAfKz3AnNzLsm1YpObUQ91PCAh7d7ie13KJkA3PNqvM7lj-I0Q9F86TFA
5vdtaHoUShbZ4C1R0wvGPkg1R7F8ugSLBjdDZ-w0-jlABhs0j_qXNTf0S-B6SNfDndT5h7bx1UqO6l0-2OYRgQjB7CfuaVd_vKClC6_4H_N1qu0pgYJWE5N8
TXRP7jEoFsxUx32Gpn-14murO8IpLjOlz8UZwB-hhMozbR5P0P0romjOn4cPi38Xrhm10usi7BLwk9ZPvXfmzplv6T1bKNIcwoJh5VO4rdTWYDe5o1T6qMah
R_laLl44pXenjF8YkxblUJDMBW0aXoUmqxr-bWk9-IYQKTyss-PemCTHKiokGUQZ29rchQpHzS1nKBnuPDwy7b_8bnv16h2laRNtpknzA0JorJsorsGgIm-i
xNSIn9UQbxAo1lyENApCdfKl7cba1qgkdm7rm9OSd7GzX46cS3SFMj8RLDw1JMEsmzvis-H76eJ6RJEv7y1L9wO32_H8mihf1QpYGz7w8wTSHEbbKSHR-GKS
zz3M8wG8v0kYY97VFWCBNYfrp1i71yS5eeYoSWsahGA7y0HEesEKBXj5OxdKfpAsMZ3DDClkw6DcFuYenQ9e_k1OjAvp7Mc-rH3H2MHsf76L1XrIWDY0Zrke
24INJX3pKJHjNjxATGwoMNm29xFDdTtNIeyqhbUtTWSTAd0BfuBnU621A68FZk4PIwMbiNJ07V82FPAoyXObLCAjSQOXS2FchyO8aMsp2hLC--EWM0xW93Au
IL-WHv87HpbUP_FrHpkmF4tVQm7pibQsV8noynEuZ6VsoqRHMEEN1yh-JJjPuDDuSv4UoLlPGhjeHB6mhxC7edLQeaVoLjQmjP1gHwdZtO5-BwmHHVmCo2Dg
SWqu79kW0C83MmAXYzfc189fJha2fxO9VYynqIDNKD8VpLhVdj82m0kGAE074KNN7Xmp8DgAHyK_Ie8mm1Qnd6HxRcfVD5HW2pMLimFw4HzpDRQObICERMRR
Nhm-l9QxJe_a3uv7DN2wquUZU7u9h8A5vSlhRZMr0RqKpSMATi145ArdPIsf_1WFkD-peMLx97zDuJ5uIg_Q8_cN1_1XuBDoZ-HdG4b2nslSrTYogJmMsIFN
jtAlnQE8FpZs8dla-bRkjNWKyGV7NaGKtTFAnDNOFQrCHD4zhKoOzvvM9jxslOLIZtop7ic_F41SZTspRH8ZZNjQcUsHjpiu4bTZzume8ehkQMMYHzwpRH9H
TC-sIVJ8Urhv_ugYlm4
}

sprite $image188 [121x88/16z] {
lPRhTkGe38J57KfYtlznzn2Sbdl4OKDstVMhnnFpMIfTeDyhrKZqUOMAXkBfm_85QAsXPKSVbCiDRGhjW_cE3Ks56Zvdxflm4QlTDFTTQEbfgrCps4zO7Ql1
Fcorjf2LMftTCoraiTRgXrjea-_uS0kfR6izRExpLZlRGizRlJVtoTRonM2VjbfRw5p_TM4UcRkVekSjX5_53C1OVNZ5o3utdAVPPwZLvrSCjF2B0fkqqA0B
yx25KAwN8awuwRMvrUgZ-OXCKt4Uy0FDlxh8bB7kwdqBARTs7cyhUeEjGEFUd98NKtJVGYZNXw1ZvElV9pP6QCCbTFPADbDqluLGtUHo7__mymAo1S-LwCOH
yaski0jpluLm-GBHZw2m3JZILFaYktcacQBRMxeQNExSmby7MEPyoFLERfTrC0jpluNy357qDxNEmwm2owtforfSzend4lMtNPZMtFVAQgnzMR-ApCzFDCVv
SK1lslU0rjToOQgvrYy_SdlrHkolu5swvl5yAxjNKVMiDSKJ4M0MvkQA0JyDOWr-G11reg3cb0iq8uC0TgymaJNNguMvlgNVtayc-3ISZwywbt8BCsgkgpus
2rEpl0GNZJBSZWBhM4jeOFkPE_2qciVZRSJH75KmVchjLBAVkGSt22jvuV7Dgehv-9eAF7yNVi7SxSMeBr9RYAKpM_JxXpSD3VMhy-OdXmcUmz8HPNxBYMPz
4Mxl0xn0mzQBQnXrLBXtQUDO_Olng6OPi723QTOiTe3NPAUvXWvgz2xZRzNZWE_3DCXfG5bQ3EvTmHRD6j3LBY7F_bSlNbdL_yZH3OT50mxyjxaANg71JbsM
v4U6OQsObQQIFrn3a5lmZMsMx-06UKTpkGsfFZ9iTuWTnfXreoKTnMRv3fPCXPMissKEVp2MzxdbJCHNZDVRWhSiMt0XogBegrz2OK6pgevKwpkeI8tam2RB
9c8AVrdDWf7XtLs3DaDHnjbYiHRim5plLhFwQffSfPlFiiMQQy6Egi0vjTh8L9QfBoDhhlKuKXfEK-CzMXSJBLfgdVCjE7ilyGBlqOwCp5mqBRG19sgEt0lC
mFuMQ-lBoc1NVLmfKWZKH6GJD2gj5B7BifLqbk-8GKGvKkDIUOtMYxvLmGvhkJsq2Ib5F142ZP1S5LwZaMaj3sFk3eimiZGemf8eIg36AKOgIiQwilOjnRB3
NhlFvPbQn3B0AAqd0gyNPiLQhUwpV5TnhpnLlXG8YIX4AjN3v7jt9F_KtFVvysrrTIsD4Xj57gAn-YVQcykc6zEq6bof_2a3F8pZK_BUNB6rgLPpf1G6E7AW
oblqOGjLHqlvAxNPqG2dtYWAiEdgqnPQIgqMRfGR9G45zkFXPeeUj92HjPhHAYLfv3cIfxmfif-ra8mMsiiLdbKMHiHUqAHGbOtLHoraPQq6WmASIvK2CnHz
R6wa7ohYGhlGo7aYpza5gDL7BPJeG5ThjGAAlP678t9j5VJUNDj2FxIQ9LCUO1eZpSEWmSVcxgLJD8_VeymaK16MDpJBoNmyirfGdMVlHl1LIhvPZNqBPJgI
dQA2n8LgBrJhsm3VpqTFlv9TcDbJJPIJtXBEv-EvrJ57eW6Ed0aAFfsFLlifAeEMgMPo52dBFkBDV3otEen-gkrhKOSb-FSjj9-YmxGgmJ6do5FdBNIk0Aan
CyEv6Ak2ZrleN8bbP1Y1rEFz5MElyodQAb_wtrjelp1rQZxGGhifgZ9NZ2ULMT6R5dh4QWNh5UCJqcldvfR-hDNFjT1-Yew8Mw0ForSMdOyVLK2Xt-iV
}

