sprite $image341 [199x286/16z] {
rDc7ZIin40HHUZFKvX_kDsSNX5hUi5u60x3hJf9RGcp9uOLgPYqujcAVYdTSkTkFxA12ixqM7P2lDgkyYMGxfZYKsEsudh6ZCEH4VB7JgcT4LW35DpQxH4-e
o6eje2AhbJKdahe9IeP5LiSN5Lcj1bHajOAAhDOpBB9w8gZ8QjMZ8gjbL6Ir7b6HrLf0ZK8hdXLP7Tyr8akARx5dgXuLMQqi45d2HFGeIF7D9f0c4hkzL7xI
3nMlrkCR8WkOIExs9iMp8glZYugi1egiDWwSo6g7RGEDGXznznc-s7kDxGCZideKs_rdn0NUqnT6PFKHNy2HtNR0aTsZHdO2ZUmC6jaPDB8pQ6HdjCZUVqPQ
O1GAAh8QAh8QQXGQAh8Q8xBtdr4MUayQAh8QAh8QAh8QAh8QuEFTxMS4GcJtK97L01_lBe6Ah3P7jZ8YEqD5LaD5LcEEGf-HEEz9d-5T7f0Zz1c-MQrZ3C1x
4dPz6d-vjzSjILKU3C1H58NalV_B_GxRTcUCrUcX70gO_1FdmBDoQ8fLhP314C3HskhWaUf9uqo5GaPAXJ9qsmeP1w4Cvfk3-pnv-8nNa36QmZ9QL9P1F6Ou
a44God1QfEjwKeO36I8Lod0gQm24CZvNMGpKPjI7iA0wetvbAQ8MmuVqZL16_SfYmMSOFgJRL2YZJcNLHyXY65KhYr4d4f4oQaEuMYhengZN8b8l5OPH8I6r
4RBIXH6v8eIhfMAY2sF9ETU2SErKA6DbTXoFXg-WQYeiWwiaX54_5KH16HKWDKyU6ttBC9Nr62Ae5ul7KCXpXw1c18Vn1okBwof03kC9vAC8v9yPpuUle7Ri
FaF-G8imwaTq6G9vL5cLwscRNtOuBJS684-6Rqq41wAN7KxHORnLMOAwF_3Ib-WdXl2neRBAgi-GeuosNpzbq6mPPbVlG5XGZv7eYFNN3f_2TuoiKLXP0bHZ
o69cql4SNZ8iX0iW3DHZ9B97ygEQeiDGI45b2PHH8nKQ0XrK1yymV4WpHg9B9EWQEmodHPemWfsj-c43QhCClqNQCnO0M8yETnX-PRLd15rRFOPVMSqPf1s-
-GmVqfh1G3utxp0AMgG98_qxgE0m2bga3IEUHv7POPHMLdq6cLXEsOBaC0eW7sK4eZC9qv6MGiRh5lamGqyUaAy5POZFy5ka4YEjOTdaUqPEvzvLPXY5bVNd
6HBFpTuOPrNjyToxpoWPlWxZuRrDjeoLZeZBqIiEenoY38WyP70WZM0P9p7CXyPbb5VMoU2Sdp4skaGoZ7FJqrTjEOnt8GBv_uAmF4s5lNmILT4biiDujxBa
_wk21un4jxYk9qpsRNGPvP03WVSPij0zic5SqXKSnliE1Xum4hsAT7a5H5joKKaEmmlB46KyJ8L6D8oTI6DxnD1uph2fiB4QHZQfUiJGUCgmgR0H30FseYUg
zm63dpEG9lfzngpl9YWZGHaFuW4Z4XKmbck77tzx4JHdXEk-aoJ3qBw-eYE-M3lG5sDAkcrbH6KWcM4SA31wOcXnYCF8b_iHODc0pXZ_xcY-CVH16T1eoCYh
PIGhiupBkz058rBubh5gcLc6Zggr0qQUwMJGdH5r6bc6ljlRCoBHUmmTLJEtPl1ClylORmnMNrl6fdL_POWoBh956Lz_VivepE2W1MCOk3Fu70BA29gAXen8
FpF2TIbSqhTC2OCnmkKn7kaKZCPO3KEZDuRS6IfBmp2Inv1k6S5bN9RiSMKRYx6P8s_G2clAaFqLOpECSFkQC4DhR15yXe7l66aAhnZf6uROhm-QLBHXo4gq
b32YFMDfAfemzFec5Z14Bt1EHW9QCJGLXOprze62qOwXgV0Pks7icWoDjen8T6FCXX6LSLNjpHcgk3F8PUZJZ5uOQnbZ0GVpjWj6y1biKxQHnefH6DvDz2pl
Cc95HYfbPBmRUsE6LOpFo1YEiJYAVXbY6S5HTCkmHwWxOsPqnfZUOAo2tXZaCjONZ2a1Wp6sEsCHTCqGPLXQCDYU6NZ1W64iWd4Okps81qt5G8neZx2QYf4O
Ysq4VUYAmJv3btGXC3fci3Bk7RueOmDwPgGNZ70xE0N6S8paN1ZqpvXkjplxU0pDnggk8HaCSvKs9YDUlnWvOqm6xNcVz2aDoR2nuczWJF9NC3B-1iQEaHcg
68mXZc8W1Xp560pdGd0ynceGGJ0Wm_Ru1Wp8i5TfZ54Ph8V110pBG9uEn8vFXTHW0FkwneoFHQGAZ4z7ckZEaC4O78Zk3878G0o9HAyPdFCmZ9r86SxlMFuO
qf2H0bc6TVJFa8N8OIYaQqOayXZgo1qpqaIMuK0wPN0WyXaYyYkaHuQiH3yo8AP5-cBeaFKPedlFHtJ5I3Ev39C30-c4mGkHo_0XdJ0YaSDm89gGzemqaSTu
074OzOUit-9EPJLWE4FMPG0Ef1LZ9ofbICvEPJLWc25RFd2p0t4PzOUiptYzToFyA2CIbJ7A8VKPQQ9YXeNuPMOPzOTi-S3DFxU8pwW_P7q6K5HPogWxPCkp
eNlt8SeGzTGPiiy7hjyY-kDI_blTUQXc5eGXzEzbvdl_vrsgLC7D0JEHifk49dSyLqoP0cGfSFqNPhRyr22R0pS-MVBJWQot0Ope-X3PA44sB-fvH4QaAa4s
dnJoY8m1BeOijv6VB15t2f3DRUWoaT28Rb6PEcIzZRo6B05gvAS1MRQC-AUZzs0Filaoafqi2MPZ2RB01Z7YxwRXa6NLC8m8lPj6UcCFlgZd4H5m0MIvbYdg
oSaIS5NK0MIX3SGflIv_P6C4MQvNzkBmHWHS0bckgti3Paz7ZmL2bkj6JfQAEeOirvCOsIhg5BBzYEZ_MqMTGROV4R-CSCXotLTk95X606Jh4J7B28CirpjT
5nGHqt0HPBbk_nCHDobmoFOZijLm0MIh4V6Jkcpq8UjrpIAIN-h28SiZ0fOH2bckHnOH_OZb0CWU417v2I5xNaIahMmaaEthzlKdoq_H7BBzY6YA1f1joDvT
QgPe1jbcXTz-6U6GxKV4BoCV0DbIHEmomY7RZuXVHWQ6eXyH4LSssf3bGv2Qke0BciTlznCj8m2oVRtiJxTPo9uV4TbOUonapu-8R5oU7m_PyoCY6tzJxuAD
XcwVWetU43I57bY8o1HwO24YSyPx-ny
}

sprite $image341 [100x143/16z] {
jTY9ZkGm20HGSiUuAl__kIk7M16ZRJHCEinzj9zCqUmXZsjOzr7UhRcebdLuKPXsrQAgPNvB63SJshjzUaCObakub6ry9GWZkbAMxyOoNa4uvAkn3EijUELh
SxpuDdbb7Ruuhv-GidnjNYDbUY48gyGS9-RLAXLBFeXqBFaWOcMVqeiZg4mi-I3oiJmF8bWloNdDnP9S77cZA79joXCACZMlUQ6IP2Q8l00oDkR7GT3gpI1w
lHO461l3yaM1J0IHQbDiZFlpUVNrohp6nlATUVNrphpw-lBY28ntWkZrnSNniLuCmXlVM1onCIzLoti2UJwjjIQKJ9kiPjMYHQjJqlCQruepYwQuKB9jYers
k9gI4ueNOiCEpyLYGIGCIoCHYmMHD5p3IYA8X95eMAPDy4RSiBnW1BGR2INH9f0whWUut8PlsBDvDM8LEGqd1B5ascIbavXHgZeXQ5XgNedLLle1xgXwAy4S
v-OLtEMidQTHJGbZAPasWSInEgDLHxnIUYmfmTxDta1pebWoGO0e837-C5ZZXgKkKITfxyMgTAETzg5XBOYA1B69Y995H8RRkCRdGooL2ODriWOrQdH6e80P
OvEpLd8HcPtH4_PAte1OpSGaiWxMDZDwmiN7aZS6CyRpixrzLPtX6lRC4AZ8KCKPFvMa0P0WMEKgtKN63qQF9MV0NiqOnZPOgyYY7uo-1XC6I5t6INaPInki
MMIhpO0tNFZU20aiqghIZ4tigL42myS2XBi4v7u5lLn64QkgWU4Rfa15V0ch0RP0rCp1llfiMCEkPdqqG9P1f5SzxDH9Mat7tfeM64qfBe_e4bR53DetrzEO
61XnvaReAFypR6djxQkvFZ50SB76RrWkOxzoQAN7DkpatmsGk8pfcjbkZFRL06ezWAJXar2QiHqWXjkOxAk98F7a7cKK9UVJQE9etJ63KukS0FXt0wj8CoPd
3FNOJkDOf2VnPmFJUU9bxBnwDU1OxHxRLFdGgCDbp9TXAS_aQXyiYJyQyCRaZAqRZiWQi7SgPc3indv6RePB8ck0Hzbk0-HfbEl9E1B7B2w9j05oauMuZB4R
UZLl8uvb9V70e4xdGVSzSDs3ittjmyuRi2sqEcEmUooM-8KyCUPkc3PsOv_EBnbKIHdRRT2CgohnsT2QCVOxSsTeHEID-nwr2uCHpmmwOxysHpV6WCWPepTM
TcD5HEIDmcxibp4MXaJUq6PizXarkCHJOxRjH0qlaJU8RjZ8hirO40fvOp3Z-W-4shVJzuro7ALzNFhfBnXpNQLVuoMZrqQyQIGwbJOuIg-PYKeOu7JVWdZ9
M4qOTcOBl-vLFGDPAf4K4fbJvsbH9Wc0t7zhsDb_kSGatK1iNAi3MQ7E8ismqgA1OPKLi0xIZOvePEI9VMp2RG2d4Xdv8EI7KRMQ4XYP81RfzJCFxSe30o2t
GRpX5HzBtW1PHhdBvt4hUSFFwrs-LzOgzOePkNdrW3UAkbZo1kx_pVhKAxk4ZyMCrBm6Ha_Tns96ObuZupxOnm9ehRzg4xP10iC7ugrYHc9UWpnSthTLUw_Y
8FgynddulFiN8Co81BWWmZp-6qkp4_CQ6VxWsof5KUCWfX28TacF1PP7l3ZYglYqI-oBHjJ4ulXVZJlWHlTdB5fg3VwW-rrDnP2VYlOlK1EBurFDQeeRsWkf
9Eg7nP6gORLOebqIBuvKBFLdmuhrAbuSoLYyOhCRB8vaBHQBQvNDRcvUyx6eLeIButaifUMHMHpvM2oFnE98nrBKzbWcY7miDhp1ulXIBAYvnP6F1GHIYoCV
2qZTKuiZ7mjm57cnnlsyHtQSyh7eB4_h7m
}

