sprite $image102 [236x164/16z] {
v9hhWe8u38N97Slxl-_AubXBj6Gh7GRs_9pnzf6Sf0aC1uXCSVXV27MyI-3wf23ZGtnrLBRnAQDBfw-DXQvhMz3HwQAsvV6Tx8As9Hi_oF1oVQOYXMlrcRha
kaRrChYeKRrk4rwpptYbwGAi4YGzFol7qdSwFoi6IJFhrOtgMGckrMSoQMRDfmw-O9-P72l8oQOz3AQlPsKxpRINGzF4MXOpELkVYTEYAsR6v-epSSVgoQOz
5vemRJhRjCTZWr91wiLdw3DnsblrtqRdwpFjCZnVdscNmldwJBluR_SPlKluBhtBlava-ejznfG9ON12PFd6rOf_Q_6WN59w8RVp2loPFYFHDCDMWniVRTGC
6XUmdSAsliyOW_it4hFels9cz6QZPpARn65lHnu8_RL65XkzJ9d07K2MnAJu-VaeetfIs2Wz9hYYbLpBGuVd0m-4_DzDAEXJ93xl7jPd39kEnCOEDJp-7NKW
59VLBRHe0T8qhLYHVhNFq3TZZa5anlVhcjm5ZFeV27rHuhRH9TDgY3IpilMSzZmILC8I6Kd9NWgRR1iriw9rFJPwHzAxlnjR2FNdzsgER11rMbzQxjPd_5VG
AjP0WJ3Z_BOIrgfbAOlziR7pua4pgbyW0CcMMsUsyeCmbCMf-xJ7zgc8mZiZpb-DOg70PbZUhawfqxHNxN_yEVDeBZH2i1xTWDG5rdrMdVRMQTghDZ-hnKAM
n5OgpGlbe8uv-o7KkMwf-xQHQuyZmISpBgbWZBEZvG6713cvSs1p5X-qRQoV_B3U5Gq6i9-vXXvyF5SVaoNQOky2A-ENaWuBxYs76Rusp0VVCBoETO3UiJH-
A-Ez5zowtIQeZ98o59T6v-nsfHYEkabGEG5980wo_hV9AasKm5PvyYit2K1fqwXP72cS6XhMIiF-naq2rhlGzPclM4U3y5I0ZhNNJGBIHLAfXr5Mil8RzHVY
6ZysWkXJN4dVM6tY0QMuAFNhri6lbMEZQ26AUCmglmtoYirLgEYrwsNRTBC2rYoSSsypLCizjqAWGf6hwtricr8QAxJH7sSl_mEXsHeMhb1kET4fjEckswY5
meOTBBk3z5b-QJI6Pt1f2uBtEahukLSSQredibgmIM0HQX9RBeG-Djue3nQEk5_s9ftUigQeRJyFsFIytKW3PBkGRLKex1FMD7rY3ThMRzQqDEfoobykGGwk
mW2sPIdPcJIpWa316hIjtsHhESaPO_bNcfjG7dm-Zc6qS_fcLbw-fc2DszPlEqLjXiN7pFgQa2QmFEmjDLIm_KZpub6UHoEZp1fEP0yhIoO2KevEUPcKFfmf
gGDgch9UPol3jD8jJAl5K3GRivAAnk2FduPvsDYJD6lrlwne8djOqENegyAejTkkvAhIpb4jIDFgAgJKGkjljKLkO9c-7wcnYrUJArUPiCMsvBR8ZJCNaEvS
Ws_kZmLhhV_Ozi83entItBorQtJzsZnDcRKnaVqkYoG0IjsVuNIaZZL6wr4n_X2UCfPqKddaRz-SpgnHs_e14SslTv1ORKMfJEZZQBsVkKwJOsspBGwW5GS2
FfJ_wToj_bP33zBCsfp8Mgnxcnv7DEfdssboh6sqNiROyfYfebltTI2jihPDU-wXGsVaoCuFTQVqZRF6kwqhH8o8XN6Pgncnist_wTwySfkDWHZehqakzp_l
t-iaSWIQZedbSne13SXb4ZY5L-4XMpJ6zj7dIntNMPsVxROjnBOzqecfyuBxLNZ8HXsMslYkqykANMBY8LlS-h6bK-h0tfI1xKgtn-EWDko89R0TWGglGTZk
0sordDdUxCCfsEgryJ84bLxJiLqEnMbV1hj_2BRZsgZaZE0r0Llc3vrI-7nupSTM0fLU8x4TNtlpEKElkjaNODidScQbItWDnRRlD3l_VAdjSeNIi6N-V9Gp
fpiwhb1uRRmFAfylj7JpGsxFlFRQFL3tYRNh7F-Gz-NN_YY02ks1s5AjzOcScL5BnbRDcNnizNjcNbi0jkBm8EY8ndQSCvAM06o5uK7K6e6j3ce-jlh0BSXT
6tMt-l2WOnjnxSqF3xhyjR7rW9n9huq2gFdO-dCck3RwSoOVMtrueF9hexyGll3QwyQSoSSs25HgysFhpPbyRFt30nLpxVMavylyiMCRa3EVz4k2Vl7cJ71j
FED_IeI1EnHRFkJ-tPWFrEJQ-DFOSuQ7h6llzsir30_nsFvs1gVQymsjZVHg61vYQoEz6d8cjZRIgtTuoBhsw5NFcNniwNNcB-lYiTMzCcVYiTMzxgTeBKtn
wigP_DfuinN2_6lFDpparqPVpkJdZszuoCVMLmZphptVy92FhG_KV6nzEPDV6mqvaruRwVLKG4khx9LQUsslnBQoL-gexvNOrlVAsbZVAwyzUgscexPNriRY
NebjVQ-iZVHQLAswLs9Rtojh8xtMnjOtIUJNHjyaaN_j-RR3_DhuaktmAm
}

sprite $image102 [118x82/16z] {
lPO9kjiW38JHZaZkVzxQc2zg22bnlKptlkMtDCpWzBz2KqWt2oGladkXd3SPtST4ooyfthHSpM-IE-oLtCilnvBbNkM15nkg0-Rp0HUdfPSlp4UT5I-obyVC
HR0z45ziQAot2YdIUr5Q-ccVZsAdfpSC7SkBNvDUjhn3nYUdnKnLLCqcN3nhkIg4iJj0ad-X5Kv8YnACbi2QlueFfiKOsdmiegk42MFxEiwK739Ke2BxkQpD
ZuGoWZxrWA66mUzbWdKXFYgFPvqL_i_GQ8Y1NEAExtgoKidssOiMKDh-EZ0FKGq-i2jpfOBkASaOpk05pPYejpO3UywuOZz7VUmjISvDzFStf4I43QnRM2LP
UpJfLlmeEqioSc1faKK2GOq9ISmb8R6Q8xUtKyZ_5l_-ii1rlo59ujc4a0XCcP2mFjGwYKwmHh_UBTIlpg2TB4QhaUMQLGfNTfGa20zV5l1p1iJyAPbGX_QI
cYarGpjgpAfiTNwmeMcyymuqqqKciSknhv18SdQEyOTFz-CTM3nNxABUYNNxrK2nx9QOaCqrvkgE-boMIyDwAMvQDLenRUSAMGdT64aDQFnPStbvKfkrBDmy
v6fgktC28Qn32Y83TZx0RDHuewJjy9QAzTomrf_EnAx4YRB9Tg2KC845T9BMhYc9QacMLOCr1vOCWF-EiWc0nUa0zT-OYqgpjwddnfA7tzSiae2iUQwoO8ld
zWGlx1TxiMAf-yQUJQahqYdNmzxIDBRN69ZI1cOrQuCA8xIA-RWqvZCtQh_cu2fPHQScM1J_O5kjRvAVZrHGX_Q6bEa5UutUNIUWyxnkpF0rxFLnUhEf2AyI
KHls7Deihmtg7NLex-_N6DjqkSiVaZhcsDwvEAxe2VDfa4RKGKbE5VQYZfVRc8uf1NLcxroAtr9KNeCMJYcevwnPNlP-CLHJatkGJhQtDpH7-4hvZZrYBtqO
IYb4kUEEKxJVNjiCZRIyIxoudsqlo9kX1gaNQ3cPQ_Qst8nf9BJZzaxI4hhAtd5QGiVjdTTVfxtsvYbta9QvCDQyioJ7XahwJUm7xEqDXVIpv4YAl3o7QPaB
RB-zOUWqBGTIDBJNlzRVMVPQs3j9orJxIz9yafQvzfTaVZnczNUwlVN0xgc_q96IN4717ARbV7kzKYCj4qEFsnlKSLgEYo958-euBTVPwy7qeuREIpAenzEo
_mxq0savK98LcY5TAP1OSr0fNIrysHlKT8EY96-YXhtkzrAZ96-bXhttKiFUeDucyTeIpw3UPczquNt2VA0B_m
}

