sprite $image55 [130x84/16z] {
nPWB3YGd34JB60os8VU_RJve9BGzwSd6k-rv5w0aNbL_4AICJlWY96gc3L-ZggcgsQZu2ZpCT6FM2z8fVP__mam8kJGr_G7JbYt05RF1sHTmoDM1v7f-dWv7
W7jCQrO33-ywP0gGgmE9cluKfa8P3KpMuLs0N1teJe3FEb1E0-ynRVHx11YcGKnhIWC_wr2Uck0hWQ4E2H3K8Qc1zzYe2GA4XZe-mN4TuXESeaDSWFXGnniO
ro7Im6GTuXCS7-fu0-Cw10J8qQ6gQHAcGe46Fgp3cm3fEbXoWlVNk4R3SpDSXre0rczag2S14vgv9dDUumJTAqZSD9Kpr0APgepoDHq4OiEjb-_eC1W2MQew
LGZj6yqSlKBKLTMLGTspzyaNcXGQvaFDj6Jhu7CjW4I8jWEkWr3pccbp_Gq0SA_4-s1NGPOEDjS6czgPshwAEMgA3kRh1LuqeTBDX-diG56tfmMu9a2HHiNS
XobnULO7c-k00_SAThC1yGg8sQCNS4rmT9YADbMF3izTm9fhsVMTLOZtKBiEVcAexSVplU9mTDX3FTpsKFipvs-cu8sN3g9pgBaLa9Wz8i1SQnJSq7f1LrVr
Lh27-X416FUGIDdlZrKQy467k02puOwZ0-kihG6u6-gu0AiJ_XFkJAqs4DtzN8qBe0K_HPC2HbN6JXJNmJytyBCEXBgq5W1d7Hveu3sbDsgZUmCg7HtY4xm6
uNzIEwDE8pJQEhWzrC3FEXHv9JZh46ZW7zuGWwGHm01jXQjwJ81E2CDzfwVA15oUsz46HdG0CLV6qI4YG1ngKb2OkT9PXy04npX3JSorO5FDunCSrw62AgCm
dJzmOG7YEX3AIuSoF3h1SKYs3g_B87SBJl2lwx0ZaFd949lWk0udWPj56nYdTGRJJh2nVtiBRdY8eyD9u6xn2KPS1-0ay1bfuA_hy9RW9K154ctCIu9m0-Cw
-Bmcw8HKoZW9ZW2viCwTu4nmFisc-tmN85S7lqnmEaMT4UGl
}

