sprite $image303 [236x172/16z] {
vDQ5bGDG24HHx0FJVy6xSNVFvDR0EuEyGQ1CVe8r9bBuQM4XX5nWhLs8ERQL2Yahx1d2I1C71NUeszg4YZUsy6QhXJD2I0nSmBb3tLR6ipFdfJBj376sWMkr
i-qCs_veuKOfNoPnXo08bJ1RQzojb6TdpXi4vqkJhUEHshx_8IHu6nDF4EIXRdE2X_1YPP_y419dEx3fdvXxKNwKXQ40BjU0xli_xxQqSsR4Fz4pD4E--zN-
924Hk_lBLV1isTht6MChniRrVSRMYX2tVY0qjoBouZupi2QPZTHPoRArxpEmododWPKS6-txZBqLPRkmp_1MP6Dah8Yqe50fgwZMacFmtiSacXKH5_GPmkgt
M4PM2VtE3klAiH6VXhTYC-kj-JgRmBfqR4JUiLRynxqLL61LAo8kw3ECTNFbOlt-0_-EhOMeLaG92_eCOSK_WLLm2x77XbkhVTbsXSfRWONrgpi_cNlLQb-s
g3NUsYTSQPJu2cdbUlhNFM6rAbjVAcaTZdVkEZDiZLqbUznLnMfMjYXKpgejGRnvBYg45MEZQVhorfg1gKLUqL3bkYqmrXRP-82Rj-8pnTCi8QwZ4bP4j1q8
UIiEG67jTrE752AjjNZBWP2t8c4phA19YhabDMz5sTeLAc_5maRYcOw8P3OGybPKhBzQlprNEYiPmQhFy5QClx3s-qlahVDZOwhLnEfqgoEiqsCZ2jN8wdNh
bdeh7v7iCzPMpCEoTH5arbfBCEip8doz8ZhhxJmiCb6sq-cRCUlSMK5pX5Mvc1RPei-WykwjgAM0UPYq9c8r8j5dg8uMgBafLTmXyPV8GoikDb-sUMBFS_B4
whfvc9kR4hicueX2PUOokRLYNNXhNuJ2VhpvRzQT2YxhLb2tmbeHmiywaUWpHA84rIeE2THR9VeMCTzOQt7qOtNnIlhIuN7B56iyVKXO-wakTjRnUE-OrI3k
4B53mJgudAkTDNGfrbcLf1Js0teXrr2F_9UrX9u2wtNtyB3UHkPwO-RpzJvW1QpF8Sp3zGkChmWEWZihNto2936qvk52m1IkVoM_F_WxTcjhqFjQLDvnq1ca
nVxlEFRTqYg3HSKytBtZS9pLbSVIVo-hgkMjdvgJwzWIhyiPCI67BE-83cE2_3A3z-FVszg2m0w-Z0JHgUU4OVf6yCD5K65rTnTx5cyfh8gMUrRC5TR-mM1a
hUwI_x1w_MAFq_TaxHAPYt0YmLhpwFx3sgy-RWkisjX2f2-iarf_7W9WBQU5KgnLMf5_wlPc7lQWKkaBAsAVdFpFre3xVsF5Fg0zv_GNOwImqbgzUc0joltd
d-dwnqUYK0TMFf6bJrHO8_x-KslstgivZ6KLhb1XdTKwzFIprIbj0VCmzuu35oFILxFoYHnGFIShUgKIr3iEN8nFNrYdbpR5UhLAetfcE0dOT9IUaoEPlhgL
rmwiunHMpeTzAfgLa-fMQ0sjs9leit2YK0ahgLrlHQ5oLYJoSYkVlgILr_9x4wmbNa9uAzANjlA9JFKSVcxYqvUtyjf-baZsLaX9wtmYzpEYjHM5IbldjVti
7ssjADHvAxIq5O-Q-SayZFcYq5QaxxmLIqjRXJigqMT_FdrvAw-55SSbWR1wrWefRzMrd1MdPYwFv-6-XaMpykdBMw7bh3By8iQVtvTmnFU72IbXvPOMrWuR
YHanwLQ-K66bjOIrYYEit3mCgOKLMi9QQp2m8dqDhT0IrfhTj9LFNzxA9t9lXJR-Scw2rDmAxRqLsZ1lvQNpLcZN_1Xk52eVvPZMybRC4eIrBrG-zYtM2UnE
MljWhHFI8xNM_TXMYgArj-wy424Ou1vQqnRtYzR-vqYPbrQ_8NnvQDssh2ojZNM-K6FNl_U7riqfYMnWdI_Kl5qYFxEsJt3HMbddqxUulxyhzD2wgMKhlupf
z0tZstXlRSFye6mDOhRFA97sE-jn5B-rFzfhv_kC7ldMUhHg9yR6DT8d6uSlgZNKDoh2QgIrAjG-GXrQaUTDd5FU3HBPeC-GPGlhvZvvNh0barhxGdKR4IwF
h15vZY_W48cy8dtfieNrkmsNeoZRsRumVIC9xRApsuTpixQ4Zj5XPOb4jajV52eRQT1pzjIixLzeWtKbkgsbjA9G-N1ojcArQptUgTp-_8KDVFzPNwZws9XH
dbZajwcbD77-jgBFy6LRF1uItbOFTIGEQLOCX0XcRCpkizhVGH6DbZX_iqZVEf6-uwUzFNsthVgkLontFMQrSmSFH31Zu-SU7k_DIR3SPVArxM7NP_X8NTcs
90xJhqH-Vl1WKBORzjzdsjLzPcPitByxyTxafDR-u64--fS4_eELpHKgaTVt6VvfhxRK5eza9hNs1m-8-R6nu6yNhcpN5ofVjjW4sRTTwmT2VcpS8_PeKhk-
p_1FUpM7MBWtcKlJbmytzvBwVp5sKWKm4CCmz5h-Y0jXilzWY9vjdOk7zjghdygPFhRv0-AXNnkBfq3jvq_-TCxqrrxyzWJtLMsCdn8F_Vp9OmjoXc5hnKD_
xMLEvqo_DiQFvqn_xOKFv0p35XH2LXk1U62ryKvm-xK7SeQjFI0UM6q4ESEm1OARvG_86RRsGCumR06eREs1GiYm1UA1rKRmlcpj0V70rXx86OOj40yCMm0g
guqWPzZQ0w2osWW4DwkD86SOja0yiFm1ua7bpqT0_G4
}

sprite $image303 [118x86/16z] {
lPW9ajmw34D9xOGwzx_kZrXYUlXZirnHTIFx-Yo2W3L3_weyEjENnKr-gtuNMWMB2YdVO-O1sK9Fts6c3daBQFmLGo5E-BoznPYEE_Ad3VNwlBtS87U2DFvW
MW9k-SPmFszlwZ4pjlSyBR4WbJ-Mbi_RQuO-crs3i_VOq6UJgn0HD3vFYr7psEhZftgttsjAFIt9ieThL9Xta2Mqqh1_1OXWA5M5KSxJugcrczL9H7fEd78J
4QDQYaxJugcyLonJ5jWiYwE69HaRUalLPTMpBbAkjHMYZkweQkzH_NbgsHafN1PfJ4mmLQE69HaR6b6XjyEXEpIOk9IIrbbrmlzMagp33Qc2mKGPDLT1Cq-y
hu6zGVs5L45VXzKTngWvbpfWrBWaOqDZgXPaMplyMulNHJmri3UuBCHK3KpDUjQbH0q1DRBtnb3SKKlb8gEMtsBYxgb0_0wCXujH1YwePH4WqidKVYO7jIAq
Dxuiz7KCEAerHLixFDZaMg8GbT3U-B9GToDuAZ8HxnvMQyLlq-1r4i5VtCPFBWixZmMk9IJJ0YJAEexMMXSejU77t-1naTxwxFQdpcL9cseFdFSxPoHQicqI
Kzv3kbYKsxIWaLVIivev2bqzhC5DAUd1naKkhbC41tN98AzDBMI7441BgaCWk_t_qcLPOUBPMLcf6Ec7AJLNRNozl52xecRvMvWlp0cvqfyxKjTz7Ehhu7VA
jg_PB13rzS-bgjoTTBvUhxa4kHKKcdToagkmh4VHpk4YReTHxfRfjJHLW4HvBRibglkVTbuXem-1psjomV5CfSRSfg1DPJ-pmiLEnjstVtgNX3FKKU_7ZBvj
P2g3YFqkOlkVA7igIhaqr5FZCR-fIRRUExoLXhl1t0tNg14tfYPA61VldEkqEAeN8ghu2Ok-rVlIQc9tre3fgJ5NjodvCEWEOokuIoWpfaxWbbej3dw7etkJ
6XfGOwvILpLnXzjXB6L_R_B33QXUkAGAkdM6xR18gxKsfZGkgSeCgJ5N6n7DYivsk9F9RZ3nS6Fg12weWfxUr1mdnm_NKt6DDAwdBZN_pZ7PDeLC4-ODLx-x
eaAShs-vl4RCNozkUhABixhZAbKardl229ah2cbuxk9rxZRcV_aSJ7XGoNRDy6F67FjXfd6VKXia7kuiFnzn0ewQc0ec0BDtF9F4m-tkuVT4tzGs2zKvdRqF
X5Sut4HUDb6ZKflIfmouCKkis51akb1HUurAF5vTXm1NLe5YGolTgAczIgt298MOgIti0-vpGqtUtaNDhzaaaSn2mx10EDpOq42M8id4_JKJOKxEIesuZz8I
gs1HEbD28VsPA3OOSrn_ZPw8s-AYKXiwNK7u3emD_JKIFLJgEkOnESsf8tTO7AKbjdTfK9QKe5Z7FKXB82j9lIgehruuIKjihuwv90ki4t2Gbb1fM15VAMOY
JCk3zEA6UfwMsDxmhDUNXIDPIGRKexJ4zYAW1cavahu30-fXMYXy1mRKXsavjnU7QNcU8eVzlw6DFg82ntsMbdFv3nGkhjOVKXflRd1P-A2z1_LtK98FBWiV
I55GVn-qzw3-3ahofVNtPRM3jFm7
}

