sprite $image103 [338x259/16z] {
x9W9RiCm30IZw23N-lzxUzSe2mIN5vN2xZnXO0vMlkr7wTPkF4GrTnztYI1n7_v9Bv91ENW_8Po-Q1wmAYLN0neWv5G13IYd5nUJ1wWvLK0lvbJKuG52JhMO
0fToAffvW9jJBIP-JhMO-3dLOdgC4NAgW39pge3oSwg0ydEgWF9pgeFddxuE_l7fYpASnIWtKPev3sj50NKkLXLG6iffwSv4__a80INdL0VFpwbyydEgnSJF
gHQJ_lCD_pl6lyYf0Sv4EJLmbIgd1Z2TAgSLN-ZqMKCKa5FkInvBb5elQOSziCXfpJhiSQBJvxpa0O9JBQdY9s0erN--ua0qgfnUDme4fSefmMXGgfmIZ0Qd
oYd1w4vEQmQZKQboIZ1A-KoLqsXqivncCRhHage9Z2gdJADRddul2OmgfnIZ-pezxWcCRfHJp9d8wFhF57CcChhUAOwPoUXwfyUSYOokpodcDwCaCBhyCyKn
Js0jWT75Je_v0xXRJM1qeLFC09xlFLeC6od5_0MUyJrQGN3A3cWq-bodNxg3u9GMqCWhUtUstZZB106OHGYw-lwlzryICjRO5OBh09iyqoVVllWTkjH8EDhm
QKciL6dz96N44zOkLRQvCX6cvSlKG42jNGjj5z6EyTBMPvwu_pis4brbgdkQ-swYPWlYL0rGW-yekY1ErG1rtr1qGUlh3R-jw7fJc_7SLdHzd9gJ8W6wg-Y2
E1K2T5_H1Qql1EYseWjDvoSczur5fqqXnAaUeFkBZaa1m1rupbJUSkulEZO5S6jEmLG8qDr5EOQPuIPWPmu53j5qVilv-qG1t7ragoN7_kC9uGAfC37z9j5F
Hi1QFSkHKuhXKiaSffZg3R-_g1qvHVAmB9MFFzaSmYGbJ4o_HxGIp5pQro6FQ3wSJeqKX8df5ucUNtynffIFSjRB1Gf721buTk274A2_IxJKrgY3V_nLXprd
2Y50VvLez46TD4h7fX0cfkr4UvN7vNI4vACwM9IEIQ4tVAypx5AvFIsAHAAKcN9H29weQQiVAFwag1k9qh4fz03jYxeUs-Je0oaH9IrO7JPl2cbYkluYsCOd
8Bo4x3_K4OBX2LB80Tezjpu1uMSNbQAKcq9jU5XVotk9ziz-4qq_9rliKJfd2cbYwejwunCGJuXwxL4wPmgzuMt_4n1UYIYVIZ5DgdZ-cXCGtgP4aK9ocCsO
YXDJC_ZMelspmqBqYMeiIddf0RgTQ2AVtH03tCKevIKs_7QYyMZamnlIdAYN40qsLyzusgud87BbjuUHmsJMfP1WioK4w5wYwRAbVzZOLvygY-5mQpPLJpGy
M6plySeWBbh2wQHub9u-UQW7Ge3k8thKnaNxG7huVQ7aV5ImsyzeKwOG6duBqHwW0r5Oo6JwxC_h7mVzILBCJanxYVO07OjwIFZk5dfg3zG9i0bJ20s_XMWF
qA5eUhZOfqjYuFxgb1tsiobc9gRzH8_Q9aJB_SKUyQ-DrltLgNJIeIca0DL5rpVyzm9UGtaOawvL-HtzCIc401L4LqzCKw90I5JqE8_FtpaVhauE-y4KGe3A
ekiRVYpgCO9qVN9ton__hlkKZGROs1HgmtVHJTwvPZQtQqetnzhNwCC5NpxxjCi921wWOf2MZr-LFn5G7xUZ6HX_Cm9YmtVGjCzx_McGniHMo9TVQcG55OUD
J34tCV6gSPUtr1ebXUS0icSgNwJWfw66nnwX1MXVosVUvAMLPjJKQpZP8ct-RSLmkjrgwkpJFYSWU81oKM9Aj_Rv8pziHfItFhG0HL_BxTq3j9Vnt0Do01j9
aqs8SbDSa8G7JkqT6vwBqcNgvttRU_ianOGeRNt83TzZPu_NKfjnKo1aFX4cJ8YoPOfPJpuCj4tUws_6JU7aOLFzNFaOYtBJBWhvYNtRv3NVnadxaCyF6XyJ
eiGKMe0geki3b8jsKxgtxrK8AH6bSGenG7krJTxhppxzzIOf9wt488JgPWDJ4yuu2g9h0vIBSbDOJFmiRWWHJBGDl-umxydNCafyxPPJ5-say2FS1Dhvrtsz
CXRbfgOsVF_JzOWlRNXTj9kYNGAp_kdqolTE2C76eiB4T0zzvXTyyqCIvQRNVTDv2yzukub_APiJrP_OexyIP_6MKnJbfhWCKAMtUlzTDlv7G1MTsKrX-Hl6
Scr23NFlCa0Tjzc-q6lJ6P8koWEKYxPwh0fGgSO6jyrzxR42jqY3j8JaeYYVcBWeQVs54vCkIgRyrfijXa15SpZS557Uy5oKcwxVSkgYrpjGrZy45qKAnSV_
EWYUH9J4wUe0rKKDk6n5SLn5yJ0yLH__2o46A1TjDIyBK5sKBrBw-2mztkapj-6_4aA04b7I-ii3L1Sr85rN8qheTJvSwYFSR6GAeU69A6lzzLjENVJ-fXvA
ehlG7BB_SAW4OiFtme9NN-VPXjT53PwYtJTfVI103CM54n3srEqJQffVrF2wQ0t7r16QvY2FbuYe_eIPrvcMDxmksX-FD9_ulhqxUHJ2HQK7JZPwzVNwYKaN
DKnyJHInn-Z855A0Tdi3XkzgZUid9btKZr25xpEo4n3o4tkGlcTngjzZMYXgi1ZXmqeXuYBAunHoW1f9KXgdUe2k5VMJtBFd1_D6onJY4HrZroOUfsg0BXOr
U0hjXoLgNNHW2Z50dOhoE1K3TBre7LwSpX0ETpCRc-BP04MF1YhAwyn2WAuMxHUdSz3pP8cIE8KmCTtvpfX68K2NYnei1dDU5aCu-n8TBbF83JyMrUCqdQyJ
zHhozw3P-nBLJq3mYMbIL9-aSdsHg06PzttzFoW8AE_zfoOcIRJ7gP2agqcDdM_64Jv09qHD250YkaNhJ_Pz2UbnWNPGcoaXG0LHOMEQNjFwy1GA-P6Wfpic
Vr6401L4XJYDnqjCOV4ovzjdM-NMHqnHb0UeAgflJ6Dv0IdyxC_hO3tvOtLtm6pA54A02g8RnIayXspjpF7h_-6JmMoE57B3Tr6fZdUUf81uYPvsyRoOgg8W
dfgeFfqkZrDu_PFayA-6dpQ5qF22w5Pn2YynvhDrpkuvQug9YKaGtJjEuN0dd5Ea40AKY4fLtpPEGJHdJI44g22wsNHADATDeGIeBgh7wVf9IZJ5841NYBPQ
td9ZgfD2250YkYXEZmrCmRUSWkW6SRgazK43L1Vz5wSW3I-8hepJ_DwjZxc9IHVT-B4995EG01L4LyTfUTyunIL0uRBelpYzd80W0VeoqLQFxUCKGiCBeaBd
xpgTGl0KH8NxKTl6gH2WWgWGe_l6QOFhXGKDlrkSchy9w46uTenJk5wm_xPt7xOQ0p08X5ylx3_mlyGfPo4oWXK-uTG707LkcpWJ_HS1zJdb9neHK9zJVgAn
6jDzJcC3-WFCynIdaG450d-Cqm21PxRubkZ7RapyNmBbcKPkJFpn8NCQO9v2OphSf783q29ESwin5JIfN0AqeadbpCh9S-hCD43WeTlo_A4qgQY1R-GqOcFg
v3G0eCGZU3tjD6M0-ejf742BEOq1Q3Md4LRERauZNBFhZdw4m6ipVIJw4LRERaw3pjDlJ3wdGG7r6vFFQGH0kwEVffNpnCjxKHyJuG__lTq8AsStfn40xUOq
UE3TEVbDAiBAsSrf143BEHKQKpUdGk2hEHK2NyrfPsFod-VZBzAFKnZGSSe2EavPG1Tz_YBzPhh0yuz7RvxyPn3ybNFH1m1Ta-83FqxvnZHE-PLpd7u3WH-d
7A3Zr0VKvtI0yfmky3od2ppFwLPEdDDTiyEZ_oC0Eau1GCVf07NlGaE0Bleye8i-7_WrAMZbt6BA1twSyerfd0A0ZbEcCOrJ7j1nEa3vhyhmZMcSye2EKnxG
SVhx2PoWunGD_3Zb0pzE-M_yZrF-iOP5_-VWF5y
}

sprite $image103 [169x130/16z] {
r9M5aGGm30D3JYJtt-ypwOzPjnNiZ3PEkHPzHNa2wWImkhrcu9FPYZDzuOUenPKs8GpRrGNNL0S4ITKqJYMgRvpA6iPnAgiPhwxCQhow4gwhUvsgWLEOpIvE
grDL9yvWF63sX62RQYG9mJBL6aoAgcUg0q2Ip3sc1hzgMm2OV2EJngb6uerCldDsglLkxuYVfiQfHb9LNVUFdtT4NhX_kxqeKrGjzm-9atcPwhYrw8ySBqir
vnr4hv3gAwzcjnmh3CFW005YIU__l6Twri0qNkzqe2bN_SzNIv4D1Dh7WxfL7qGLoBy2jGTHPHGf3DlxzGHzP5M3H58Oj_StHtfaLL2aWmxA_deoHQl-5DKE
JEBr-JR6eyvqowgEwPpcNy0OK7kFsXAhPghJpY_O851Oq3-pQew9ixxZG0sE-bb_oysf2vCS2EeOdwqAM8Wa1jKv6FHKsfcGwV_PdEHuK3ClAacQ4KwQeDex
S_9FG44ICDktEfMo61AhVZSdhSCSBptgV3I_gQwbj7G0j4JrFm9jPPgNkcwxWHAM2KXIDLVTGJ40z9GOROBy8Yaj2-F-ns6I77FGi3TjNYZiqtVzEAsqYEgW
fpaXTPYqUOJqdfzVeDs2vZODLeKIStgXhGtng1SARUuLtDoclLMPgEuj2i8OKE-VRUgNTPi6_M6PEMdDg753oGlLGODD0sgYkcCEYgSDn_8sGNndK_IecJdz
goD0b_sASSocqsewRMhl1i1KzG61xo_0BWeiJUUYS5JL6N6gibHr1ntm0km2PTqS3dCfzIZlND42wZlLDMWeMVRMWMvLhlVBlNu3N3Q6gPhg8sd8KEAgTw1e
Yw-pVjMxbFhwh9K6wr2fgFe0K5Uz1yKC7HNTk9NIZa_33G2LOvB2YDUUr_Aikxo6PPTiQl8AJu2ZXldfRL3LtpHdHCLXKivb8GNufreglzy0kZdPjoU7hmFU
oHliM1usKyUOjeewzTqMcZagu1KLBUcYmA-OCvRJKJr9VJjj5u9Mx_cd_Y6IlblM7fjpRn7qgjIblQgJdXNjvYSXxQ9w33exPWzwYUhxNYINKdRr5Rr-rB8H
puUIXwede2xgsPnyGqrG17NKZyrUhCyYAGTrKUr_vglLbtphQOJAxqD9PaxwrRRvKIJbe5ufr5rKAvNINEPpW5wP3oKnJqL_wNG_ad9GhzI-YBBfoyzJAQwz
vYs2fitUGLkhJyoPWph1qaIP2mUttBIR0Gbep5C7RVloC99oq5T9AQx__yNpuPpdPm3DyZIy7xqHIJcebtGNALcTfjsLtwVp1LG7cZNxy7xqwJ6X28esk_5u
qYnBr-eTDAhkyE4enyr8oa5zqEyMBllLwg-X96_sXkHLVXf9Tq1XFfPU3RIWVopDJyqUP7AK8ukaMw36jNRFeAwuFwnAfStUA35vbPz4qarGmzmSmESJeEkV
HYRDtWV07n_bgEq9Q9jF1cbzERH3_LATxrGN0sY8gdl70YsYibOv9fQolNkgap_FIK1p_UVzvqL5HuAfYPAmbl_rH4-Qc9FCGJzqrRhVrH_x1EBBLXKqYrL_
fxh47FIpLQVrhlvSo_Jr-o3COA7gr3jp1j2VMtM-QrKiysQavsT0fHBL0-YFhRhSqnyaYUlJJd-gZwGSzETMVR3_BK6bekevw7Yh-XNrfm9c0ZhAge4qeZfe
C6SAEjwgkVx7b2JnDcZRXriLbgYUWEQelznLe_wkUdhTEidvlAj6rC-OukEpiVMNh0hf0oPk7E4S4rN6JvXsTyy_xweHL2cdtJFdqwX21fggVjUSOwAAkeiP
LHzgLMg0wYEiIYMOJrN_xQvA3OYa0LODW_A_TkxW2Y0W28Be5UGVhnYyFrCd4K3NgnxO1JXtKRsVJJW71q27CqALKY_p_vewdAODW91wc__zB2jfQW04E5DK
JrTIfIgOab9K6pYzLK596Qhm81oW6YmJRb7j5rvB_guaRzLUIVwvrvNKjwehoLNLASbLvKggL0LAYb4L9VMekf9wL5r9__PVlg5Qswe0Pzsga7hTgf1wh2f8
lLOLz6MjghafwGK
}

