sprite $image84 [191x191/16z] {
xTY9RXlDhWHWQteXMLMJlF_RtbyjOY0fbkFW61PruGAoOlkeANQF_FR_Ap_voKz-qjpQ2-C1u4K7s0mPRo-AVz41JXDtyVvY-1STu3G2mAiEC0AF4yK7w86F
4-DK5-_8lE00BV5VC41LV2RcgU0jzGq35C1dvgdaBVNvpErLyHdR2bonhpf0ubzpW1xucbXxGVnJln2OHBpi04Ea-B83382IYA-Czs_aWry_G9o-Z__r0t1l
tyZF0SWlmclNzhtyN05-2Vw_V1__QmTO-2Ty-b-o0jntuWdyBnc0sXKMJ-7_xpkiVQURuGdy_t45iZSHxePTp-G354N-Us_SI_11Yk8_zKOozoZ0_zSTpjAp
4l_pAv3dJVAj1F_pAq3jkzpFV5jy_sR-Oo5pWB_rvidylmtmqM6fC9Exd_c6P_0NywCL41-M7cvkiYi-z9tN5i55uV77UoiWFkZDVx7a-vdl_APNjantffBC
1_6P7SxUU1nydFdI_btyJ1CoF0RvsmvdRyu9Dp_p0swH-E_blyVzS8UvUcDnom_k-rFuUaTBN2VYQe0pFkbNVEtxa_ZKtmOmMmDGuhgdp0z-dFa6xS_ZFnW0
Hzoc1qWj_CuiplhDN7dUF8zF_cK5pDS0MZgQny6Vlcj_Al_n03WIDcRWYf_-_BzdyXyEG5mbx0z-7fP5-AJ8Xto4Oqz-DYTBNuPFYW_vm0r_lTyKu2kJVl7Q
_vYVlNag_zH4ydXbkn-0v7jyTyzBzidyxe1RMgbpRbU0V9SFxJNu92ONMVaW-720vEFeJO7kAmP9139y_0IId_WQV8O1y97T__099AyI7mXIqw_NbDBTgnnP
bW-GCu0vymc8VESGgii70iG4YIFt0n1WJNxorWxCQxf4YYpF9m46I3EHpF9dZqHMvui0INdSdZLYFe7YV14Y64w6XnttC2yHw_C5068OF3U0070qYBjKbqy2
94W3wRX_5H99LkUBe5ESM6j0vJCG-I9yWEGPxq1StSCgomTl-00Zn8cOQIS9gYgV5tho8uudi4Ai5EOh-U1nzO8q4kwM0-eLkh_uWNFeL1ZYA7z5VjpokVWC
2u0a7Q3bmQE2V2FVuqy7HSWWpY00l1x_WivLBbaU9v8l0DTyv2bAE4klBfXyy8vFBNxTxgSVVvI7E6fr3e3ov_ur7yaNA816il8R9vZT3xikZvWxN9nF9F-S
T_X0QRu4WA_B9wuIWOCFuf_ufwU-ynmX0KXWSJuauZXvZkHCe5YR3nBaUtofFfy27l852fNvz-yySSCdABx6we80WdTya40KvujPdjY9SDm-bt3MvX_Tjm02
17dmYJ2z21y4Wif_I1U-b-IJj_miZnl0ctC_M98VGG3PS91P7XBCSn-eMfw-Cq8aKfwldK1GETFoesZtdIkulhPSb_BW-ajyH37-QTlQ22srCMkk-_8S1sUr
xfiPXDdiwkiinImFTCSt5UEBtji8mK600G9P7eIXE7_6MmGOe_MGUDdXV3r0v6q5IXS-M8lVnfjBtWV4EIvsWbW925Xy4639buQJawAyj-xaafeEFv3hMxCy
cqiIo9X1pDQHEyoxz_sQBmrpboIIakQv_pG32Jfv_xuF0DNAqqCh80d5RDruZbFadtoKw_u49L5aRg_rGOaaQlCpdSm7G8bZhN04IGyHPF9PbQ_kr3d4WiDw
CqbSENvqpghyDaTGMQ4TlJlbmtYEaGXMvhExZHd70w0mMpCG92ENe32_JRCv75fPV2VzgaAb-NtEym3JkVWGjNjhHiKCaWO1hCit6sEwpHdKEGkxLdX257WE
2fTdsfZJfqqSEoplHiNe8P5miYY_d-tJLeLo1GHIahKs8GG95rcsF7FC_EqOG23Xf8ys894aMB8yRQxos5m33CiT9YdEzVdF2P565UIFsVgqBC-mQMRWyIP7
sUNx95SAyirwwvRsEQPFCrnMM11jWfXjK6B9Sz_CUk-hFAj6gq8uTdX7RmE2ESM2vLcdPc_3R5xiwoYzUfC3wADrBzdzow5p7Y3FdzpXwJnkWHW3uknMiJnv
wgyTFXx0kK5nF03jiRxFxyNu6CkUwdRvy2tluMdG2a4uzhtawgPzs7487TVOT2p-sbgHrVZ2c6k0_CJ7QEFiNra376zo1G_EAT77PNsdvI5qkOT7xl2qK8Qi
nJzngSx5oVLTuDQFTw2r30PbQgtktBM2sRD2OqtHswK-Tlbzk3FzfVWXPMBa3hlDOJPxlswKcGNtlLfvN4Ve_MBDQsmSRt9h7fi-G-Nuf9IXZJpnrwzv393_
sNke7fywWZc6voS-XziQO1uxFQqYdzJT2XpNblLshC0StSln9LAaZdZlMPx_aZkSzrezFYseNRnPWNppoHsUBP-0ZMhyY5E7Vl-wMu4nia77DLQpF87DT_xd
vzq0MVUiqBmCy5a-lvbFyH8TyTclNuIijpv7GRxjLEhlLg0FomUGtyPQLRv0tQ-mOCUrTVxTPs6-HFt-BTxjSBxvN7xhbVaYV_tY9TVNc1q_X2lB9oG92qun
e2FM-t5jrUPJ8jPla8vmjcpG2_3xvEBVha1RtnnR5ECxsxpXeyrV972tmz7wg5YUVJRgYizcoR_sKxBMwfMdawt73NzUyScR5JZLAK_cP6ZRWExu5AKxlp0g
yJFDvxPDI6BojVZWdPyII_4pmyVMd4h-xry0XTR0Z38inizivdthaVnT07UqiVCSWDIHOlnC3s_RY7LmxWJuczlyTU5pvVDwvTULRys4RTiaax-lEGx-CS0d
yBl6s_TdSuojZUt2rvzyVa8lxRkTtfwIZkZRvW_vfFx-qSVszhHC-g3k-FWCF_7iRy_C5XBrp_p4QxuzEnqw-FSd3_MXthUt0fbYlFFfcq7w08_sLYERWsGV
rv--sBkeIeVbnmsQJLfy97_yeXxsvlHMAISJsy0d-DcRQjaYjcRK5N-dtiDpl5NCyBvrvy7lV_AbNNd9ril9h6t3gGVyl6Jhflbv091ayXzSibKpOcxDZa__
_f8jdvF7M3kS_Bl3idvQUD-6joxgmM5PEnFMjctir8DBjdWsnzmYF_tyHl9IwQ187OVbosLIL1wMhvZDroNxzhBfhD6Rd_pa9p_voVy1
}

