sprite $image331 [173x247/16z] {
r9W9YkH040EdoguhDVx_S_UQKti8jXZIwdX04pI1qlPJFgNFy-b1EDSFHdq4rMEk5tfnLwrzVT2iLKjRn3oCOvsBC4xt68kWT7rZPMOhth4wftlCHHYdMySY
ZDCj5AlWTBYjX4xNF5Pcb1iB4B6QfLlQsk4qkAtEwTQnzkdLRAuqhNZ7oipJRAuqux2BLQTh5wjErsskTBhciJAZciVAz68UAzFkUH0qkC1Ln6gGhYh0EDtI
LXRDRgvqkbPpfObdurYPmFErhNhERDNhyesL2xX-yXYnNY-upXKNi2sR6-jwKNt1FzPFcC_LzHdybsjRsGKGy2w0WVTSCV2DTLlsl6bP6NZ7oi0xLWQ6jtLR
Dlz1K02tM7TbQ_vSRSlcnxejUpeLe6MhYIe3hzkgWNUi3BpdYe7NRTNWxeyi6x8kjrK3qrYrRBKkW6NB2bzLbZtE6eWqNQMgPL_cQWQ0i8kLmVkhG81qFGfW
K3__3X1XLG234_5XIoru5C2ov4SjcAYohD0rYPLb4S4jX8SgWuON_aWtZ0fWMT52mgl0ZYn2w2ONe6L5kWwgB2lJpOzLoufq7VvMbbNfUgYoh4utlm0jgrl8
LzMoMZU_02shqyrNrR9wnj8BOA8k4Bg5XDigY3C26xf91J0n4AohqzKj11NmvSG4XAvOtRnOMHQnqK9k0T_RkG_qs6qO2C1iQYHm_-Ecx7phqHFb634DIIb8
qxwqtzmHGCf5HO0TvVfJfIvvaZTsE0lLaxgL6481TeZh7zQQySa3nc0W2yu9M68uOaM-nVM_hqe8FLP5lfC5vyugEQ3IjEsngj0sw-A2gnTOu_BoxR3oNbHx
5jonqyiwYwAOsOgoPw6AYYzsUorhFKmm-AWrS6jJTSPAWhN7KbjDqHLrnowl3EW1Iwuz2-g7hGl-uwy6spgidUkFRNFCJ6pICwmfklvOML88cQqWds8jqVN7
Rfd2z5fPwR66BBXZELip8njMEM1jN7_i6dRO1cn8kKppihO3rX1TN-pKOLbn5c8DqNN7vj37WBKGQyY2DrQ0UjzLwO2DGgmb2xxOxLVi70xLWBLp_R0OhubO
EIxjHgmn2p-C5U5r2I5Cn6hB1go52sGRnRPfvOiOGbY9VVMgPPdd7C-nzYoyJnQZXy5CU0WXRyIoQYJsMroLDdYiaVMrNvNzI9XEiJgVts3sBDJQP22pKal0
Ukr5wpbs_QHrsHTNHcumcNZ4tes4zXShcuarSyTF2Xocb65YHJt75aumQ_qKzZ1CAtwbXX0AiTr75XkmrlB1BXm92x5T2cO5rbu_Z7tzANFBLK-n6nQMM7CT
i3A4dG8OxtsB47liigiIQw-Vn6veNkzSPksnikB3ajknBQ5vAPHpXvKj1RGjlHGhS-snyuTjnXBli7MPImomDhqEYtTpxh78GLMqKb6jnAw0qghR9LZPCWn7
BFwou7KY5hqCXRo--FvOpjRQOJ6R2f2Jdc7JfdebTWkekSTYYuA_hiH-Z8AuY1AxNO2TkGquOXkQrsiaj0wRbgQxMgi_LZAt0KUiPAGoWRZ7rhMAwjLOxh2c
3ejafehFoX7BkXIBoEQC_NE7HGwmYxaVYyZE2yBPOGM7RsJaTYnYkLNau8Zb0wue7zXoBLQsHVQHZKqIHSGY9FlnZsvr8RPE4H2ymXix8GS7BAxOX6kOckfr
s5hGwFUHdTwZVkgnlvnofQfUXyLe1PQHNP06ve1OV1Hy9ox4rXI89Qj-FC9SEspZTBiKAzpM9M5a8SVGBHrMCl9nCLQMjxJCg-mYcxcTYNB4OeYjLsDX3MMJ
GvUTwOEAMAnzMkLYB3AGFgXKRNok4ag7bOBEUYMsHXv1K8piRk6Z7B5wfFfZ9PzO8KooEwY6jSFgvTYP3Ok5bbyKem9LxiUso35qZEoYROhXNP53jjw4dNZp
72CRjeLKv03OIUx1ra_ULXm40cfY3YI6N4Nlm79Xpp_32ICEtiY1P7JMEx3jamWAn-_6FSkATdKJ5eeavv7byRyn1teVjfpjHJY0fxPFHTvknRRuoLwal72C
nun5lXMxXKyY6m_7lnhdfdelTk7GxoExwAwgwjtOyidzjVHJxHQixh2IYUqY6zkpi0sRGpcDRDB7OndPwMdOqCU0Xwk7OUi9jWaY6-eZiQ7jhRaXib6UYTrs
rXGR8_ky6mmkFfTfkc2lzKniQFjFjrOjs0Oy32i9sDnsN_nI5Tk0fs6ry6TIBJdWajA7OPV0yhFgCevbQ5d5mwhpZs1befE7c4TYZqjRglhKt4QngEr3cpVH
HsFvQOy2wiEnAlnEjkTYdUj_h7_96lyns9f3-8TWsnJ24IigJyJA7CC9LcgjJyFAcWBgx4jaduH5M8djjVKnM8ILM0FtDgmiCHom1kuTM7wUxnmh8jJUZQs5
p7DigutS-x1iL-TO8YrSOlt3Qka6kBm5k-LmLisWlHhR45O3ri3rnSeSWWahOk2wOcMDmOfLQGQk5nQprOnj91wq_bZCLYiMC0FN0ujsPSVQkSJwpDR1Re0h
DondgnqhObXS1smxp5PpDp1nWMq_WvKb6QJdnneJzxMkmFhCrl5kmAiN5LYdsMhUo1WkyMTns0ZQi7OkgWrZCLi7i5Pk4mNMORQETeFZBmgwWSTijVVPQbjS
HJiGdzbgxmOcxeiAxEXizUy6Cd23YMcssZSojRkablKzR9l3DwjzltSr0TOXh2QiY9dR1Dt0ORPQiMhj1i9ku31RRJ4mvHMjImJcuTbgh_cRMmDfx0RsPyAZ
bLO3TxmROBQELzxSkm5dwtXDzOpxXHRTmBrTzHMNlxkuJTMCDSnMp-ZoM3CSLl_eybZZDbljqRKVQnp2QewkaOkIBx1YcAs-qRLtWrg2TnLRT9iei8Q7B8uL
JT5LR0x4C5jzAncwBhk1OIFeM_dhwEArECnMX-WIQsXNtXNdhw8h2knmMFqt3Em60xFLQGAR7dB85EwimYnyyP03ORsv6DtJOytuHj2_wwA8bQ5pgtzqSQnn
cAqEvnu-v1XhL_vT5qfWXpU2_j7LDtPujlf75zXfRUFjoZ-wmARmL2gYUy0-kzBgW7MEhZXiMzsYAmux0R_DuoqxWTy1
}

sprite $image331 [87x124/16z] {
hTRhjgGe38RXW2YGvFF-BtV6k3E7dMeNKkHFdv-5RnEhQ7PohPbMJzexSz_JMhLqxdyFzx8GtHfpjs5kso8q7pVgSCsBelR_pOh4fVr2LoJEbOFwTUBaKJ_2
nsJY47L1OhzKZt0hIwB64dLx5RKREW8VmoNA8Eg95qMDYTT4ZOdpqAQ-XdL1r82AuY5gvIbL5C3OfeuFA_1dTZQgm4R7Nd_Zp_zdDjVvvtTsSLHd5qODRDZK
wQZEBeuQsNJqhz78bYLHdLqSrTd5KPrTTAaYMtQMALJnP_PwVXRXHS_lRBEJ6hmCDLOum1DH8tk3pAEkACPOOHu-C1iwniOIywYp_uUPvwD6TYInA6ROvyIi
61uzd8o9vr585mvmJCpo1WKkrDsGU2AgpO_93dzEpE_Gjb5J4nsEYVtvnwiM8kh6GXsE9Lu-lsIYlDyHr5C4M0IlHZEbVka6si6YowgYeo2kEIZ92JNMX4ym
CCwUqXIIw3ZzWhaRIkWBjgKCDA9-mjd_mpEiR4GPvq5Kc4MT3ILUiOfA5ukThacvgna1VicUbvVrl7I3sTcG-5M4J8cosgsrwSu6UEmcz6ffAMqN2strAB_O
K495dbdPAIaKdKenrcQZv6o0HzR1KZAkflM7LLLibCNPu0wqBHTReIZ4VbhRYQhE1lYPDS3kqmPe8hrPLU0A8yx6kTcF7fpD6oK1quRDMCjDxPnXeLMThHVI
w3YDbQEaAmjcs9QfEyj4-xbJEor29wBKCC7U_tR_OPDUfzn8Z3qRfTt-1RzcxJygwG-BWwYdf2WMeGcWxrY5Bsecwj2RPQ921JVhyu9rM2YtgyBDgYQxkp0R
EiwwsBTofosQR6UDjIOC71MOE2tRY_gox3PHTxPPQPlthAr_kTDs-nHmLX9jc69DpPNLqfA0xOGtYv9vakr4HVtMPZqr4JLdHJ77ti_f2xkVVRkAE0jCiTPG
JBMqnyy7uRLPEsPPE-pkgXXP-bNXh0rVi9M8OMFNYNB7kP6TT9fL-AlKtovLeQXqo3VihukvqN520U4Jtx7ipmkzqdRF_2LxlrZW5rY0LMo1ZU2WhEjOUyUS
lI3JWNMiVMjjb6LhMCMoVUwrZQYeOX4BQ2ORUziCka6Dh5Mm3sgRPIngJlbGh6PXJSTT7MGT7NQFKNQSj6zJBYnYzVwC9YUO-NjMxo-YnWPudeNMH3Okt2v_
mIhGivc_8t3dITQY5aUTTTVW2LO1FOW2gquQFt7QTaSD4PnqTvYrg9jXWVMpUk9Hrb0fhiK8JdhYKHPw9CSU8tJ_gQh8oARw13QSrNxANMHWKnzOlPsRz9-o
geniAZr7u5_N0J52tDHdDfwrMuI1JNsA4Cxg4GOszU6qyQmY2f7FgExqFAMhHuZNWOsD4wF6EMmNmbbDLncD6YTLWyCs-9Q5JHsThLrkEAj72A-_uIciCN4F
4LgYTvDYOeiGNdzl9_y_CREeH_1DdPlDBvj7O9M7rzziOeMpyVKtdzX-zl7rDvVOnYA834STJsn7jTVVcjdPO41wsDJl4-l9j7OiCL1f-MpynGNu2m
}

