sprite $image240 [272x194/16z] {
x9g7bgGu34MRrA3tfF__t0cs056cYwxQGEfxpbRmJhp8UlBnVFntLDqW8dsJllpGYTFN7pyqWynyLZUtKVUofBspZUfJ2eRxjf5saCZDsqZzO0CoqVri5Pen
R9hsfXdhG4qXKCn6wdjchDimfbSyP6_Lt35ZrGZVC8oxfki0z6rrkunDDdHynRWwCbnOILiq3gHsgXYRoDXO4UcRMpGEfiQ1z4NJv_nAmICNZ9ogbyYyIP3b
UEg2faI9jDUoqSaItnx92J6k92TOPwYlF9p3CpOtZhIIFXDVqrqpOxqW45g6PYMgn3E6wfh3kU8nQVdt6pQHve8Pg_22o6zm9uhlq5rqEFUa3Ks4-1PzTPsC
5MWOpdqOItv81AxOHCgCzO88mpcPLs9jNBQ9jCLMqVI1OJZFNOHuaVRq6Ul3kLBAf7s3xX8Po-cqLWpdh_9vvemLMipLPCJzA4cyZkB46Pl-YyCvC4yYJE0b
g8hp3kTU43gtZB32YHTi_AMhpfYntZW0_ypfDQye0o_OK1Lfpvcnc0k2uS3YsRla-phKB_FEjLLYhi9NC5cY0Ay9eKw46_1JP6me24fCsdY4OScc3UVmbtcF
ZSCB8WpdMGadF-24_cL3Y2vOlSnhfJtkEHQUj74uXyGZZ4usp4pDdXcXBbcv0Q_5pAG-xd3k1Q7fSrX1QXzHXoObev4D6mbNExUHglTVej-zgJmPpb4qLc9S
GTWhvgmAePPuParjfAEDQ7UeuLmOXdDZJDhGM2a8rM4pJ6pfoByymlwCe3dAF-G0qriSpXUt2UbLup0MgYCAAMmmenbN7cr4TAYFaB7XUgcujuz765zPyq7N
n1KRqSZuY-MmAj7F0sHiVFmQSjLy9JRMoOS57Lh_gRWmYMZK4OLCiacrTTZkdh4AVrs_j_SswfQmuYCzr8OPCEg8w7oNf_OrQ7OSpX4VlnV4w2TaRx0qFMsR
Q7DUFVIAGeQfvevDUuhsrMx3UJZ1hjxR5wrshJxyWSh21oDg6KBJbmsqso5ZdVZuusq2tScorO9Q-kYyzZJuA6qarBzimUR_RXoHE9oJqqhHQa4rqo9Vv2Cp
hFjGUmELUeUjidLlFrbAI_JPkiZRlDyzOzxHyRzdRoSRbFVsK0kMqakczD5_X0vIw7YROOUjCW6KZJKUOMWEHQAFs567KHKHTBoD_9SPkmsqRApvC-75uNkd
A13Dcnr6CfS7t8WToqTi7DjyURy0dOjZpOTfyxSCRVP1OhKy5BghZrPUWiKH1f1O78bf8WkWxzLCtOSRqPNSWExcOxrnR3TM-FH1-ahG4Noe5IGVgyqq51Zt
yE5RvNNmUB_0wT5AzB4kPE53hS2dcrryzF8UM1pnVXDtRzjkup0CG5Vl5i3y_-_E6vOFYfY9w6RuDjFxFXAaXgOBSNpnu9u7b5EVzrZxXLAleSIXOW197c4_
YTpg4t_tnyI3UWHNsH4yAdaqs-LbaBfv3erOuwB-8Ev1RdZ0VkB6uzvc7ZaJyTsYeeDaZxWyLDLxtDpC8oKoNHu87cdBrBK7pjIznytZh8mWy-Mn80y3gMiF
hdDLwt7pE2iv5O7-8Cb382KEtTTZVC1-ygvkdegd2hTk5nTHzHxlBH3SEnLFge31Tj4NAeeO1qiWdGVR_SB2ZLFnF1S6swLMAFmjOf-FTHvuj5LOM8gHRrEF
cGXe7isceNdKm4CQzRXjAfuSYG3b7bx0MULTZtM9uJCLywbugdPY180VVBdmp8CryD1C1QWVE3nx6GflSD0ElbR4FLZR7hIU1syuUnaB6nvOeVee8MipFrBF
OnmZvBu805I-MEO2A0y28mykL8KkoF3ivJu8023SdFj5KbMdaAsD-yTvfc8fH1Ii-p52Rei00EEVf5ybekaywec6WWEX2pA84N9N1DekSSFqrNlaxSBOytXO
Utdp2WzkYa0UAjpXqMsNWizKr6bwKKgxCVAJco1GVAZg1e-wNXwbU81218jXM6ttDlBzs1C151ygpZrmcHx4KX5B9dLkBojgDy_U7wiJwRQBYZCFvs1O7Bdd
0GshMR1knSWlD21eFFOY1Ex1gp0jmduVDbE1vG__0PinygtTDDaZfTtR8kKQEJm822ICXIEEh_dPEu_LB0ABZ-qC0LbP4cNKoSF7mg5WrUI9nSZOGuNWCGPP
O0MDTD8-yo0K8WfMcmiEcsRkGSJucEwPnOv37WvodgdGxOCnQdNsZZoyu1wnwjqbWXNsIkyHni8hZQ_1Hshc7YgOHwuQTxXw3nzMq_Ou1oir5npFtha7qNZC
HLYFpiCVs_9WrLzgJafszdxMmqNc6kx1HnnMavAYLaghYP6v1n-gUOxeiEayLEVBEV7INB3grxTRFLRhuLViljhrvXue-BdQpGN3OgJpgBSyyEYhYdXjPIGD
lvywx_boVZ4NR7TOnKZdKOyM91-ulGaQYxQGF1Ro-5ezZreYdxtPur7LU-G0wL7uvGy401H5LvKyR7ojj23y3HnbTrZ5IBTVD4tTU6Y1VAeOFM1pmT3_qGVC
wGxRDFFaKLMjns4Bv4E5uA45aUU2FMf1AUMpD--NQZpo0ldyyl1XDNtv2N_lQ8nQYv7amSUZYzHr_1yBfE0UTgxYFBx6C1SSNi5m4IFV_fnd73kFpuC0xf66
rGeA3kGxB8jBIhIpDt-kN9s75iZdTWp5eGB2N31iBhX_1SD5ZFnKTxNr-318sV8uTDBwNB2sHnUrscjNCVABLjd3GJx7iJSNx7TOtskgdob6UWy7uOSvZkkv
O7z61cpliFxFItWpflVut9Of87i0tby0dqOjhwDM8E4gWiRZio14va25Btz-HYQ_WY67I7nBJk_X4G9-ZkDOQuN6BUDSyCK_dK3vB1Nwdcxs4CZwbo25p74-
Lxs_03jNGzH-tLcdGZKztUYHGL3_Sd50E_pSoS_lytuWHoqe9VqV6owkhgURFJ88xnKf98wZVvyt5X1UmU0VC9VtSiey-hDN7Xa4l563LnmBLNwkqe8rluB1
zfgALURHneWyLAiH6Mja3k1vurPVVZvv-51HQrkbzV2prpto4W7hVWrnvFTvewnnwr6hSnKALjEGHrE_6ezZtIvI0FBYEFJAGCH7fBnngwWDTrWFZkpHnmZC
mqIc9CMe8Gv_d_VNPqzZrEPdP3muiaT_zkB882u2rWmZSrm-8gN6RHErjbKQZoP6nD2AW5LlM12N6aVyqClErHIrj6TaqbPHlVhMW-ZHYm3iKSejN4EVkLoy
prjAYbeBrdp6UhtzX5cj1aGYhbBb3bKq2SEmnH7w2wbn-pLgSOvQtogzHnyZ1j6JE4r6w3Mk-lQKJtv61iiA5MlZiKndo28BsxMYHjUtvz_1Qi_8M70CFHGZ
E3eHrG33DNHYvBvzZjhcSZxpq1N-kAwrRR8CGp_PYtrxL6xSXk2OU-ZijKJD95ulIsIDt4ngFlHIrFePE_Nm60a2FOaAZj1XD8z8IUb9unQ-LQOUNj_MyLgj
dRhweNtVtkwmnUPKiVgr-OzRn9gRD3ycVVb1N3zx-hh6_lio_nnMOvNNlcVksrUAsZuul0QlPlfsg6Oo6sifz-qzMFiprekZzp-kVP5vqjGBVNlKMrlbyP37
849c1CViaMwsVNiLs6cun-T1I4myAWTh2ex_kZiF6yXX60WwNP10zr_kvxIVQ68W62jMS1WST-WafgroVgw-t0i47smb3subMAkj8Zpk0e8EBKeUt5PfS1uS
23tOIjyzRV7TlIN7nYayO6sC1oFoZ-VsnU3WFFJcE-71YUZg19b62wqYF60z8GyEH4AavDWHF9QTyE14P7L2lLLo7lLwOXuyHkgE1Jp6_4MIh-ABG2WDvS5N
7L0UF4OAmP7ouFLiW0SY0XoRyA07bmCUX0XmRC83RyWjyO10UAjelSTioGKy017GAcDtbctFrW0FG0JG6BfNPprUhSo34-c0ndjTak986kEXG7XmtBxCRd--
4oOT4C6jSiVEr3LXGeZmLhbdf-wwlJvFul-WqZ8WVI2DktOkx-tx-UBVdjbU-ejyVt76pB7Lz_6-_iBuKV_fbIvDO-BOwljudrcSvxLpDOI8XMFhnoI6V02U
PQaqZPjZynZH3vvp7l8NCN5i_Nsyo_sYH5mTcxyBVxrVb8YTO_FQPEAu34HZf5iujkxUmZ3MVrb5xkdO_9EQEf6GSd9i7YFrfb4UtB6cCI8yG70aZdMB4ULH
T-n2Q_m8No0YF0mToqywLoB2eugZ7uj7xOKO4Hw6ZkKddMk9Ru5ZlMD4YpjshXW1ZdMg_MhJiE2OBqRcSYmVuUSA3Zx23xW1PZt2WnjWbfMvzsAhWE3mSg_Z
3J0-mkSyW6FztQjtdvDtda1mk8pm-hmce6FzOoJa3EF0ZhKVuIC-8ybu0CTwnKYSmWCEv_uZl9w17j2n_YEyxWm8xbZ_4LvuSCVwZ_0XF81Z_MlJEm41Re3D
ECB7NDUn_7qyuDWPH_YOox7yVJpWs1bZ981ZPnpX0pXsnX4-W6Ed7E47E_OZ
}

sprite $image240 [136x97/16z] {
n9O7SeHG34D3H-Lp_-C639xjcmfecb9v8rjUFdwYTWIwZxDL3mJ0iJcLekf9X3ZKvs6qO3280D5Nvr0quqPXMOj1EoTqmc8GAuSicLpMPEJO7ObITTj8B881
8f8I9Gw7BMsxZWGn4YO9DqbZVLnN0O6C95R3YyJ-WAw2MnOn4uMvbyQTrwJ3rKYaM17v2GYQ8xfA899m63vLktTNCmc5uIkfsxUho8iHvZM9jESHjxWc4ORI
2nAvkA_swcecaRSBqdCIbr9CjBjyhkR5kEg99DcI7i9myUMDe6h-hwlSBaOsTZEsIqcIf2XUE0WmtWWw5zJ_qrLS9o7b4PFiiiXAaAIOHGB4mAdC6gh_M0pb
nRWs38nuYYpbI3OyomgkLPEw_pZY9gWxmunZwkVifNKaMcKxVfoQ7PjVTpMah0VlZF91y_G7IyM94VjX9qPgh7wr6Acy6BcdIfDvBEzYb2uO6S6ztF-kgwbi
xCN43983Iwyi5uNA6wd-SLUlHKgPH9YuLBmAfBMACutNchhVZEHQpDF1zL6BIuuoD2p1SOKXFUDeVz3L5yeFUqOOoEOkcgQfoBTJ8VG73hp2o8K570_1rGK9
QOiZHO2F79_5seTov3WC1D1o9Xhj_V-_lK2hon1RXiOh1rJItQOtHA38yQsLYkWY8-QdJBcq8ExW_Fq6oHiFVvc8Dg1_GmwjI799o__1TJqoRZlyPGVHHyIx
8pMkk7TGQdSW7cznz19GZYeXvpnDEPGvNv2yyOuWivD0QJ78B0sw8vVrUCr4172MdCnUad8ey6QHW-we2WsXG3prZXQoRUJmXfOZwGuf_X0QGZCvZwsZaG1G
BxX4RufM7oKbMLuR-WkSp4O2P6a6CyQnGmhK4mVHN-04zn3KGf132xA6ErAAZ02s4uTU6z2LoLFoeoLvVyyZ6eUF3_r-lK3f8RiUldj9JuuSovXoo7HmoKe2
W5vazfS5pJtVVUQHH6bfLoIGxxK1QeYMz2RtH-GePU8EXq0EHNu4GMLC1x51G8JgD7O5-tZga6Hn-9BumkmSq5rM89S7U9cSErpIA-IeemFs4C3BtMqErMaD
9k28vBgv0VM56-jPMJri3j8SKD-w9Q5s09B-Um0W86CUdvKrwXV7AyrH4-D10zIqI17XAw5ygOVb89ElN1m36cIV3eYn9U3uh9pK6q4TgROUusr1y6d5drHQ
x8ZyGGy_bP5gzJ56H9-PFYjepiggN1_rzuCq1nf8or2LQcBGpifwKC6-l9_tKIN4-3j8OgkE4L4NOBtcqWFv9hQTjpW40MzT33428q3gSzjULnws-R_VUSdY
c11CIDuc8SI8iJiY-uCALiDuENC7MHrZvjWadMBAOzXzk1xAlV36c4F3heN0ub1kpYLCbCKOwtsuxtK1Q9ScvQZnFCKv5269pN17G0pue5WtFIacmntguJ6g
184jCbaq93EnAY9sdvlpeGvsPcY39Al3ooJ6AWdqCN_J6oC9crrrOfJ2w1opXsKmIeiOuJjRNGbFYJlsFHp3904W3BFzVodAPb_s-4mzA2LLKVhMud5Xo287
oaDCT2WEztWzr9I8qTu-Fpj3cXhslsROPez0JGah8_hBW1S3D2WBUEikXQ4ukzoyEuCaeWbxEztrgaANh5SWcRq4TO-tNXMZTwX6UiUvHArxc9BRBvqVMuT3
FBAan1JcQ2wSetMSIv1nd19pzF6mIDpX4W-OmXpdoNbf7BsaAmo_X3zVa-SHZQE5U65mfqXZT76dHJ77gIJPAFmxgtFAmzFBVbbWalF2kFWTdYnFI9HjPON0
Kj8LncU_q_ItUfAv1WAPk3qbLtzOupv8lXuv0ahEkUBATzxry7VeaEIqLo_y382_rJjaam2mmcXxzMAPVBWaL3IzUYtyyESISvprwlKoSGYmELwF5Twhr-Fk
k4paw7hrUlZXpq8EAuoNRo1OcRZ3U_KxuodfZXasnByt_9xF9mQjCBw_JEJmNlt-q3tVvjahy0s5qOzwtP3psX2_FkhrPVUr8NwzXzVr69QIdosJ7-dLyr7F
lbT_h8VfBro_KYOQuhySJ_XaIlu5
}

