sprite $image238 [129x285/16z] {
t9I7pjuw34CfIXwoy_wlszsgoxZNI283FLZjltH0cX_kOzrm4EtktXM7aEfVQSG9YWT5a8rr_vdify3clzEONlxlL44EvYjAqlJMTCrEF_afIF7_fafI-cii
QNfhkYQKd_mKp7SfMUMliKFf1vruWk8BSYPftMzHagQtfcjM-SzFqlmfgZmwlPH9IlDdwPeqlJMDITDRKoHdUckw9KrlJUUDwILCKhidKFQdbp99APv7uyRq
Kfu2cwTZw-bbFmNpGyoOtWd6TKNv-OnvVHOenzA_FeDwBlqlyE3vBzYXyaFWJFb16KVI3yeS9z8FRCuvyjCFP7ms6Ddf1x3vcP5yFe2C6Ge9vIy4GY6h_12O
y-fbX45U-Y7Gm14XPAN_iq0KCHBFXq0DWL1u8Vsr0CLd6AIT3u5XMiQ-mdxwwmeKx4yhBCul1BgAFjD3fBybO2PygeT8VwS2eQj8kwaGv_S5XAf6zXcCE-dl
2u3i2bI_Pn3dzmK4j6fOFeNzzFS5f1Z5zfz2JE-c061M5VGPZAtqxmj0jD3CzmmY_Vi2K2k6tKd6-GS40Ekaj5KF--dl2v2gjFwJmTWvVry0K3T1NVQmBdzV
ODhV12ZKgh9MYFBl2YZ_AW2o6L2MJo7IVwK2WWBLPj15297-Ym9GKx75ftESVr7WQmZIG-6Qumjn_XK1-IBmvNzYbSh-Go1uJq0XHEYegKZrB07xGm3GRiIt
IRuee80k14Ira6tC85S0ejs0uYy9a20M0l45TXKR1mMac8ZMyRW0_wS0eEeA-cC2t1O0LMdgXmJYez4V573T4m2isfC2PL-0JmeKoBO0y8y9Q3ajqFLu1TPE
2ZGXAocd163U25e_9W2fhXIgyOo04knEgDP35Omcq5uDqAed1EOS1IZ3e5JZ2O7hSeLKBu1rFI7mYKwmDvg8rao1zf4O-y1jNec103piPNN_ypuuaXrRp_QF
igkWf9SFq732y0uOxO1M018Yrm6Ak7R06As0bmf8yzeU63jW_4GXaabKc2y2K38u3y0sWY2P0fQy203h84ZTLztXW9OnI5KkUWJHFuu3C4f1NWfb5xe204YM
WBntm1ZxI3eWhfS00Aqz2ZjWZq8v2Odg9G2GjnEqjoCBRO2L0nfw2G3WQ0MiZp0U8oaAIF0JG5O10AaIK1m__OX24iH4Y0a2w580O1KCoGCmsWbQ9Y0j8V1w
02ZQ0UqTi6r7EnEBY5m103XBGJvsm1654eZKSi3hI1w0RL-OGWbiDX-WRmIFTZwoq7PJ6PXDQI90Vgxb_4vmjFEZ6bll2vFRN821IzuHU6_diGEEXIbPmM8q
1J0E07K7uqiKTi3HpaaGixa0bMf_9pZQkOuqZhsTLO2900KfO5sdC9xQ-SZ2CPBp0Q3ev7S4gHHG782ZdQEd0m2k4VHb91yxcnDq1G2grVOf2e3sVMThXIy0
H03M7qTIGVxOsNW58BS4A4P-6ycL06JlKMZ_6eKRG9O0bFROMxLzQUUn3h2_OY8_HU6qC2q7W2M-j_DK0F4P01tylPqn4M3R_m4G0iMNTfu9K7u306u8_zZE
bKioOFm203ZxKpkl09WB0CWJ09_QsPS0c4w0TY2wz2e0S0AG0ihHoMi1yWRmt0vIxLS0z2D0jDl-2c203DdRUH60XVah04HWpH6q1Y2cMz8t001cIBNJ4i2e
sWQT0N86WArB5m0uHcVz6q2j-y8q6q2G7cqV0Fe0G0pm747J0MYhKVu5OCptTxNQPWAyRm2Y7YFu8o2PVj-rhfe7KFi1e2n6Etq0w1CWXM9C1E00AA97wti0
TW2B05P0p07e0Q0TuA4zoWZC7m3YShCj0pYaUmJ9uFS0KW60IO1-1qZAqIRq7W2i1u2wHkbV0egqHyeN0Fj4WBm1eBCxY4hU0oWc0lWjGBX6cyLx06WbWFi6
G6IDaWy0N05m-1Z9NdmTm5u1MjvTsnRqLu24zEYnsTy1gBL6BmMeVmKKgBk3E6WHGE8V09HuTupDwO97e2S0zms0w376bgi0hZU0d03s372fCM8Pm5gj6EuV
0GQjRYSuBG24jSODa1sV0K4-scfpMWU8hfAF053dwB4rBGCOUOty0e3qwFa0rGFWfQbn0zW705LqEqqVmnqGtfhx8wWEWvq0V0CmrIYT2mXfmXrGUWDOPyXx
039oZ9a0a1UV0CAHM_u2z1bWyBa0W4DV0HPXNfy0RBC1W9GYt1-031Fx0F2Q2pWMS8iqF0Fg6e0gsFZOTKcJ-MA0DG0nsgEGYGy0MmKuCg2wlqhX8hHe_WBu
1B390FunaCd-AWjenXU0wbo073VvHnHy1yX70EO2MB8D-8s2v0y0wm6s0q3T9QSeN0f0itUyHC5xFQ2U08Iw7sBvFfBk3q2U0Bu2e5Abpyz1waA0UYcyEkNf
ES3I-WnGNm2WrYWbTyG8sWd7I3QV0R4CKEwGYjUHvFI-593GVes2bbqBeB9EVer2lm9e9a3e1X1_0X1r-tCxSoJV0U9bDHFWVGCGdW5eUqJXU9Lr00YJ0Knt
W3q1175lPxj7GQMM0C0VZbHQoSyZwNKn0DhjhoCPl1PW9q1IzAcTcr5gbm50NQTsBYt5XO0YEozCRPS2WCfpEqTS1sYWXElSpWi0twzaMI_jJ3KRmFJzIcRm
yTpEEHCWnu7YEq3JwuY2qXA0o7T0GCPZTru2g7y1gAMEtRd-203gTfgR0Sy78Bu37lk0JWMmAbEplW5yEb9roam0EAC9hm0-0VGPO3AtY21UXX9v0WX_0y3c
0domPpEU05PV0Ewp0HkdPVB_0VmUK7C1eicZsAhz3F350Dy15bobcrgPlGBA7W1R202rgsmQ7bqxG3n_0RmSW1Qtq1na6ReVgRu0R18Wdm24Ied1csirdG3c
hm354e2Q6srXxgLtWE-0N0zGAuMNkVl66gqx07mDW5hZ1d0ErKqwfAAk1wGxfDseMy8ww1MGmrS0XfQytWVCBMKpySe3m9mAYyeEsG4-4S1s0b2xyMPPd2tF
LpBIxfuF8Fm0NWuKdCQvKLZL4w2aoOhM0Cu72dThsfAzdHu0RPMLW7WzK3YDj1Rl_WMuBGISxmDX9hQ9MvRy2S1XgSNTPDNs331R1R0NW6YASJKFzNOFanrG
LjS0IXFKPhovMNI2s_u0m6QfiP5cMe4k14JV3nJ1iL6RTjFV04JSQKinx-X50AOTe2V0uq2X6RQ9P1jAQJv0i-G4S7a269dQ9XLQsOeb0DNl_nsNENMJMIVF
1AWgg4NAwZiWeEx5ct5qpGIa7d-E_Ly0QbNPB59owYCu06B_1e3I9RV_YZKFRDTX40eY2HMuV__RVIKDfqZvEFYyMS6SmAGP8WaLyFn38imLXmZy_nyKlGKB
DAqkWL6vn0e0ojdp3mbL10j0kpe4E4fWt0G0jBmKYFz_05n5WNmLWCYzG3rMO2II4znmHV9SeCOAQ24YkQ0mXPl0EFAC1qo_g3mhQ2jY0WUTyVH49x0ns2We
dGIQpWGuVoGWcIu0AgyKHZQ1y1iIBNH30LLvDGUKWmHGQGC3KuKQUyXawTt12ipcW4R10ZPy8_Kd1JCO_TKLJTrxn0AcL-GndmCalH3e9k1CRmBBV0xQbKAk
Q4QcEQdgGe7Jvm9QQ4tkYpaC_LIWqdkAB1HwsWWKMy9zwUrQ1QqtWKI3YmcuqbkJciuLXDkUAnemBV0bgSClq18jyAy2YqF0qlEnJ58T0bfe7wbZ_kuirGHS
wGMkGY6n2lpf1IJPtvxnI247_YJHbmAe5C3wWrh6NA2H1t-IXlEDBpf9m9bU_2euXn-Vf3Ez-5LmfXU_2ivFlVWa5vzwyPJ7LG3WJY_qtLa1HtfnIPg3mf5U
4BcVNlXj0zqn_A0alU-xyKdQ-oxJNv2uA_v1UiJkVGC
}

sprite $image238 [65x143/16z] {
fPc7RlJA3eCbKMMQt_zrxntRoTXOxFbbXq3GzO6aPfL6_v8Mepz8ejLMG2_5tbgjjRKGUYEhhHvgrPYU2gNLfLRqUVYx7kLWFztV2CspEVHZ_BUAX-6NybM8
jy_vV1MyLlULKF-Z2lrmdwzYhIw3AFYskYpXiuhFyFagrkeU8lGI_ldygcAjxeM9MAjxfRvn_66yZMruUp_UjssCUEz-REF_Alsr-tr-ME_jzVWKjJwU8jhk
_XJt-jJ4ERu0rFf2vDqlW4Rl2v4UNm21beN8kryH86fj4RBZ2y0iW2yJIVTN08i0AyVNT_iTC4s8rPtGikxl02O1pYfIxXU0cGu20tfMaHXV0EKVaOYkAZxU
xLS7Glmh0LOLAtmAi13U-i7eg_iyW1Yol-vnAW7u7MKwz_5JnHl0gY8B8Fu4J8H4om5m0LnXWFuDG98351AcJy0U8ma0XFu4KDqHxm4o2Q3t07Ue2eJV0c9h
2WD4NW6g-BQDm9w3tm0OFaRl4w42ekSHp11zRDrs5_8SG315tRPU5GR1Sm2HEcmUhtAO4EQ7068pUD-svZ00eEaY3vWIKvJHHpkhI0Cg_GYcMiUsbRqAJG4s
wLNb5w46wzknKa2GS22zK76cKxolj6_TOPgu1zi4i22Cw5h5jesgK4i1WeJ80giAXxRHHyK3WAl7lOgsRLrR2i3JWH72xbMCOItjWEUK5hrNuIb0mG-0x5Q5
GV80uGC2TrvLf1oCFO8eaKmNR9UL9XtmuU0425de2U0SWCxXyui94P87Z480yG88CoECqu3WsktYWlS-FImV0QtWTC07G0ZiWHoWWioQNG4oUImHsH8LMgho
rG69CD1p9OefL6jHNHsG8DL1_m4OO3NaT72QGGeGXmCeKAfXCdwsQbc0xW25ebPZMHjz2Z30Ikss0FaEJe2gUEdC3m2z2YiM08eejSgJ26Pw0y1Yn1D0H8YL
7O0Te68HnTC0Zo8MfSWl083N0UevWBgBXxj4-G6eYbdrbWJOx3v2t4kH4x3d63a0aQbRcG0FMIjnpqJeHOH99a8yuWAGKb8T52OM9bKNit85H2HBT2QHcSF4
3RyTG2tH0KOGgj54i3hq0a0Mm6f5YOG95l86u8u88GOHt03RE_0qG2BSKOoF776MM9u0IWYq75M8nG5GJm4AsBGu51AXH60IjsaYIaywKAWTlHK7iH0Xe5BI
WEj92p-gi837Su2gkDk-KdRpaOzmlKY-vs12EiB7IVEGMOMa04wpVSFzfBaJYUOSC4U4tm00B3Jfe01kPG7MIOka0mfJEoBe0a0blONmSdJW1QRhf4KaEx3P
WPs0OlcJjZxEEy953LOD-k2ajVCbcaU46TJ2K7mTb0J0IJnWkubGnGI8cQG11JndnJKyFA0mboXkMK2mk1S7L6UEc8Dm3nTDHp34Z2qs4JEFbCWxyEl7sSuS
4SN4l3y6XE_kmysFTx3b0B-hBow6IGZL1m0pB812RQz2pRC03xFRGTbp5FEH0HI8UzmF2dH7P2DmX7_S0vW7vxR0xXxn2O0Xvq16FHte7P0fiVjmwRqNFn-3
BS2_rxXjJMkjPVyFHza1uP87RCE9MgsjJaAlHHGb91jXsmeJKMzrwa2ud81rKBQlunKqfUs6i4i7Nm5pl2kTukW7ekrLr0cm7H0By1cUQGcrzsMYkPw0SWNS
mmijVUPezit1kJhGXzZxlOgzH8-rXHN-s_-SoxMA7YQAzGvM-63w9jIhYUucSG8kgnFwBzbzfQwhWzlglelzbgES7QntUrMgYWbOgyj9LnKduClgSbMCRQqk
h_Mw-vVLfQjeNrQNgcACtiTeIc_bRVJwx_3_0m
}

