sprite $image37 [242x242/16z] {
xPs7OglAha2bQPeYcV__suD1m93GpBRZ19_rthtNBTvUep8QTZ7y6CQwG37bKfXPMfYvv9mY1MSDN0cq8QR2iWcN5Bt5lo_hAB4y0AVWyC_Q-bZa52NwlsVj
gCW_KSZzfU0cbYV0oUEVqCsYV8Iqq-W-LTh1RyKGoqjWCl0BSLbUoEyBT2ZoOeg7tmCIom_0X7_0zuBEwlivpe7bX-40RyIl-5wrXzaiRo9RU0COvOr4_2i9
pIMd68a2YHIY6BESWptyA2RBWvH4tXc40HJ9q1AaXQodL5WU8fbVtQ43LDJ692qQB-CfysyCC-P7aZWNQI6uWz1YuvsanabQ74pOaEKe2NzN1UTWUuSYalhu
tH_mqg76TxtkOUiCz2IHTD2Q7RoUU5ItgbaMnG60cnaNQJ7z-t8cXm0iOWzVI8dmOaoH0vHWUbLhD6fLETkPSQU5qsiutzLrdOvGpDipMcC66BBKxMaePpCp
xYp7ODVF-BuHl3UpINRXGGoq57qTu_JL6AMbQB17mlZp12x97WGl0jEkRhB8Gz3y-EcHvv9ALdtTcAiDsUepUejujsU_fuGvcY6UVgn3nYd4kXHS1TpEke_n
SNmLQVJlOE0t5BFbOoVNA59jjTa0Pjan3Z3YzGcjwt1qw64BpyRnJdmxNnDvwbsEOvUKeSnxMgas5ZTa19KK748SxjlnvRPuTVxH_XMEpBWkhJIJ97M5vihO
zm_gIpZhPgL9dJLfUcUCFpXpqe7ZgiiomLg0riwLNJN3q62CLU2hoQHk1yNfKcqGVaoOJVqQLhNXX9NlFjWBQG9Ndp3KnVrrJE4wkxBniWFzs62POOg5rqX4
VKYVDLnRpcyNtOlgMgUfXtjTBUREQgkSumy8Cu-dlQ3rvgQqJjFd27Kcgp5Yzt3I7rBARDp-KY-CcsVp-6fX3X3qSxJa02seRdvoSzC8Lb8kB7DoS3RKkLaF
9cIXnQQwLZs_L9csHnta-Gn1zMwBh8711qwzTyLGRLBPJZbGTgS_Ug4mX-hoW8LnErQuFX39SRXF2BqHTU_BLRPiXpcyR1zcL_-EH9cFPKL3vEHXc6oV6rIT
6FEKDs2Bsnm1FVmBJbPG8LuuxWmDEu6b8cVWFEI8bnf6RMfHk__pfo-xtIB2rqzZns71wz7sFAbgq_MgXd4avsVFsElBg8BkUvUCEX22btycUwZRz7nZfwsA
OmFdmB8zqPNl5pvGVSiJVoDH-w5snrn95LcX89mYoJgeALoHOUqmUnwEPZoQqwoJXir4IayVfijILtFLeUwvpeP5IbrdshoUEsBxlRPYvGlb-RwQswdAwSeO
M5Pnp-nQQWnSspeMyQx8As0rhAFWLupFTw-oVreArNs4ACBoCXXgGyrntFc83n6FV80qBwfNeZ7csPRhP8luf29MRDMbijFv-gKKgzSOz7QruayePMHHzdB6
UZVk7o-62Lei9NB7mi88Xyco2xtXZy1aS_3ggf9E7fZsbKtw-J_DXIJx-3CRqphPQM97bX-3epC0nXtxDHcVbTCAvnGpooyc7UpJ5y8VwzENu7XUHxaK4VQm
SZ7iVjkw6Fb4sxfsysAv76LdsheWuSJETDqTYkIIq5Q80ruEsWWo2SC5OQ6D4CC52SBuAI5MMCBE4nSCydhmBmdoyk1LXE2YqEBWvJJ4LyImkAL3KuBBaXRa
Z8Y5osA5pKggNuxr9gNjxAe4uK_fMmf-wrr98YYVqRkGhzctrfFONxHlhJUgB0GNXsPfZI8MBeuLnaz9QgNKQPqqgJydhRLJNpwjwyuDrwUEAqc43o09rJLz
UUh-Z2887u1wglj7KCH1HnI2Zo1AhDHNSN0Pd9G3PKmfNAYG6KVpDK9AoSE_OBYv-TzJo7kxiKifHOG5FBKOK08HELY4cnPu1BGj1dh6syRM3uFjmF4s7jkH
m_0_As1gGLWYDIq4ogsz4s6Hvevvo3Ysa8h55eIM4EzuK6A76MzRE42Gj3DKKqhf_gGb-8fhMWhqcAR5mdTqCGGUmaqA56DqC1a7wC7Qc8uQModRZSjf4PkS
QJ5sD-W96rRkreY5nw0Xo4Plw6CjrQAevr5ZTLNlPUv5tELspjd35t8Lrwn9_InCPwE1nJ6DWqQrVo8yRWn5hERs8avpEkQSl_luPjAyrQLgGeppDeQLYml1
6nYmWSWZVCFtiJMQqshifaAEaTpu9EbAx9F4wyIr5cAwY-US4ouNACCTgxVkcD9qt8BUv_PrVX2HfaEV2xUc8-DYNZkWUU5EEMvZz6UCIKYrbx0QudjEzncs
qAqHMg9AQEILFDMxngaqYjCt611Sp6klEQqF4DIDssh47pBsaZIrbw2-YdtE-QxZIedVktKOjjnAc8cwMAOn5TmaV2jywzU9xlV81z6Npl5LQzAeKbVMJWEE
zc5ZRLeikBeNEmqn0c0fNvLl6aWpVcJKVRdkQtA_eOQQtmPQy2wCmmyjvxKQQNCENOUcuSxTE3neZC9WXDVx5W8u3N4iBHvgeavJeNTIAPwM8mq9O8T7_Fod
QRpbO8xklw6EUG3KjAOOdUvSZna32wvkJg7lMzI7s9GMWXb6IxBqcx7QXK587orgx7Kr1cJixq5_IfbjkAvQ0DylW-sJ-fnn4UlMDYUTFdBEKKFyhQLo7yVf
0sigZrK-61ljK_7h1DCeNurx7OseMjsDNTJa3jhS7ZNEueB4rJAs03RdxBIAFTHe4WlugGoh4TeEnbaVovh5Yb7L1MEL23fwJTkn3fTTfzRR-A1nb412gtiJ
zftQ0BZIWl05R5emZHiHBXcNoZXz-LaAmRSuv_1xfpPWfxn6lHLqMuQJnYGK9QmsBYrZ0A2nKKVp9QszJ7r7k_4TFwlZkh1dhrt6QDCAevHHusvBqXuULVGH
uo1nRG3n_MuS-p9EGr87OGCzsdDA9S9wdXf3MXcxMb4VPrX65NGE0JMrzIcnFYIIhikn4IIBsshLgJysbHRRT_TQ6PkE20ffzzQaDhKnY3vPp-LvzRH8qnPb
z24xFaAmQhnZxYGNiLl6UJ8stG_8JBaqQgRSj0jvtOurxcxitasXG5cc4Io5GAdC9X0SLS2ednQs1ZlwqTWDnaHKJMchsBknUS0uY2hNGHLGDBHAgMfTNppI
YKapiN1mwWWgCHqKwmi1wXvh36nXfB3WeQokZOL0CPhK8rOrfaTbCDR8Jsk4kHcumOIf9m-hGIPrwTtX5SPUZVlEbKifxlxeQApu5WCrljoQ6qUp-0gV2dCP
CyzGPkQIWlbwOGz1iNVwwthwCzOQlJM_wAVi3jPhngxlrPHpqf7hhcagup-76ekiduu18FHZjI-bP6X9rpKsAINJ7vqiW1cs9-I_Rjm2o_J7Oymv1otaDFwJ
NT7yNl2qCQKK-jQLkdwalGimilncQBzpmJA-BsJV7vuWLsS9wtynvbolraAsVLf7qDDJHlYpx1j3xDEQDCZKAPi_RroAc8sqHW2J-qg6LEu4-DCOANdL6FMw
3-biZRdSoHx_j77EOhT-jnohttR2L7fo37_LsafAuc05a_fAjhcbFvoM0Gj_4oSfYeUj85iTDRFh5-5XOnV2Q-l0M1Ym23juYIG1OAEI8sWfPw_7dSeO6sNz
7PeEjh22wq-BgqiOcZ2ODGMM88O13h1340f2i8hJtrw4c5kYhg3nWOmQtt87B6DlZP1p8JTDN3MMb98qZLapfXtZt9Zn5Gbs8F5E8gn3sg-1iePv1ZO5DZ3Z
5MehQn_6zK-affmrdjuwDGmxH75MqkOh1cMVEu9vm5YQ00fAuzQCjJxE6azNKBIyjiXYZHJO0DEWR5BkIC4PF6JicrARoPOnd3QsJMg2lZGr1hOfWi0CMvYa
UvI6MJ47ZCiihDAO3MFRy4dZq9WRmnqkll6m3NDllQjCg5zG_jMuaGvOujP0HMhyiZ674EZMk9F6gO7Os6xHl6dYxf09aCJ2ld9ocaCXpOnlfMEbmA0YDc7P
-DQqi8EJnYA0JRwhtm2QiZjo0UW8iW76Binck6kT3xYIrITYd996vfpntROq271_bzjjRm0X_QyTGbBdXtOdRkonEfR6dpQsTr7N48G6LNrxEzP0xs5ZkXEz
US2OcdoiLnkTF_QCy-Bp_fvE0bowHB9xcnC02iC1N5A2imTt9xmrljgF_QenX9Nbc3LnMaf-TOmDDQvxJO0jM53_-mW-LPWTOxKPFe2H9c_DN7djQHXJtYud
0ZSwtSduRkkW501jreUmuJ5Zy4t3PArBZHgj6QCqjBvioHb3j-N-fWDNQQWtvvspOd-S270Ou-cGySgVMToOG1gt-Z7xjw3bqRteskBgwAQegee_1ev7KeEm
W_wvr7NqBN3ZhHojluL1bT6x1bRHTDRMzHameqxN1Zu2FJNfrFK9U8dLZKyWYgjsgK-W28wtp4ULiSxNroS8rQF81r0FbyoViHlNzWukZsRov-nFyx43cJzd
nAoB-lf9_K5fhKdzIMcjIVr1tTfBMidogvB4hGJzSgoUbaZ2XypKzS7YmXGsAub-xStuWtfNNWnd4VC1rm8-OkvQltR9J1TbRQ8akIpXOxu7Hs643mio0NnM
a1d__xQZp_X6g_-_jKmfSZdAnttxeFl_6oOl_YsYRFx_fjZF-ZRW_x_nMKbo6TBJlhazbalazF6yJe1PtaYcKpbzFgyBllVK4G7eH4wVxzTiuOvZUGliD2ZF
oMd57SaLJF86YZdQNnqyGjpPqrrn013UsOtoYTdZr24g3sbFRzgx0u0_e9pXGGolTorDgVZpCwcgEDfLPWEFuZRUIBFPlcScHG3UZRA3nw6rFZcclF_981TF
aqnakzs-2CwGrjgqTcaskYwMM5uCtnNYQEE4pPPoWbDWMLuv1m0sSV6QM0a0NnpgY9fsgeFQK5QK2vp4y5A_3zslhrWDjU4VEG9v5X7kwogjPY8ZdCNobvLJ
D_RGOugkGtvvVmO3BRRqhIjE6svUcGdFuVXRKXUjAuTW0kk2Edan5e3Cq4ASxXPXiS6oWt_1Iqt6xxqvlF2YBvV2Oq6XpfVKjIvrmxHI0US9KbF2OfFmBz7L
VmILHMitQlHS1a0DPraOoVuLEZ2kipoTxEPhxW0CguurwxyamRyJTwVNy7qp2VcVT0F2WCgb_fEadNE42hzAMNScvCN3XkT_k-9g8tCdc8STnrHzYTQ4NwnC
IxzuqJWKEGbh45K-ZmqfLUln8c65jiwgXh_77VreJ3vcbZqoUUT2qXUwSPdBc49fr2m6m9PN2IjXOnHA2ucUmXWRgry7GwciYaS3FKWyjui0gLhTh2qwhXoS
duZdjNdTBWmy965O2eOQOrcY3ntUErjwWQzZ7Wz5aH6eNbudgx27v-9uvQoSlmix4HfheIJo5a71-ScrZDtF4pcTOZMjWnJVjy0ohMzU5NRmR2old6W2ryBw
cQag1JNmtXambR4Ak74zYuKMhzq9RTr7TiPPjl1yJ96lS80xlimsgw8VsSc86UB9lM7EEUKMxbzfkVxSPQe5eo9k2lmY1U4LO98rPvUd2wiOyjHxb7emStgx
RaYpcJLelqCgOtbYzvwU3ru0UEKkfSK69bOBZPxwcgr4Z2XsPfprASNfNPec6ng60Yv79ikNzY-bzAUst0cxO620wnZOshZCFgtxCcwn1ZjLZq7Wd-jPDIRB
0ao86OTEcmVfN6lvUKtVOTrpl8naDHPJhKJIVNgHRE35n9MJhAilZHMQNgfQeJOsrXW4eq-v1UDG9qdX_Tzv-CdCLef7IA8mr9AsraSOG3L3dWaOBOHwTT-J
qUizM-4iCsDNI-RwZh5td2f2adfjmlW6LhP923_4xa5GlUezfopjLFgSuNgRuS7Tacp17duEJ4UCWMkFElei8xwQRcALoedAYG2_CSncZAlMwYoe_EtYigCO
xCenxTq1LZ3A9YLwa-knGibrYkkaLa77V2F26x1PZe5r4qgrSJsfweH-X6pWJVXoB2316IzALECQZjvQ5oBB4Og3Dn9O7YHPOqoHqt20zuB4yeCm8IWVuQo-
xmS3_uXlGFWz-28lfdZuPRZ4yZ8uEVY5c5SLT243lnMN-2F2MuC-yJDrFO9o0UcBw2gMoh_MheM_1hfOM4x09Jg4FmhQa8eyG4d18lnrq7fAU-5c_HsvAu7M
UOefvLAOMOIPIyafHVBk9rN_0m
}

sprite $image37 [121x121/16z] {
l9MDZhKg34Lt2uMs57t_jxq1pHUO_vaxuqhYEHXXfPkY-2wKfAXvY-YzHpGtBP88VmfBzI5yHOHNOVmDkNhScaM-ZC9hnc-Jj2sIZKtVDE7te79R-yTS3tWX
_0giiutwrvZFAl-IDg9_dOXVKDFKlbvxi9bsngHA-3bbqtw-lRkwu8SaNxJBwj6i5ic9DNBstjHZa_zJUy9Fg6-6tA8R1foJDS2w0g1S_Aq-g_Wsx5i5rq4H
0iX2FHWsJYtGkYAfCAINslQwHz6Cxo7HNsgDGL8JyXXaQ8yXZbvHZjvRD427TbU7V3lcJQlM7V1-66IiBAXJJEDlRlCHKEiwNpRnmxZ9UlGLPUHHPUcHq-pq
Clvt1qVF092Z2wJFGVPzf-tBNj-znaWMCKhA0Dkek48kSUyCyrBxtFP6q4h8RSaxkXE-0hSUQyePvFqOTH9O2-RkAlAi9OsxL-UDs2ku7r6uzRukqlZRtXYf
KkkLh7SPRQI0zw6Sudpjyvr1Jq2oEJFhL6_cBte7XZfMIupSneXZw4VhUTpVmb3hWmGTLMkQMLGWntVCj7aBs4Q8o9U6OUzzCI9HkoFHFlOw4_bgfY_trTMw
urT6JtlANNNR_VqrtSRY4lSCZc2iPl_GR5jB85-2HgWPLFidX0jGhfUgzTx0ySLJLRUZNsR_Nlq5-jftkGaeEbzlcGnT2wbu3zbVau9wjK-BLCUTBtqSNMVG
utz2sIeHlCq8PXTVvv5vszHFrN6_pssFSAo4D_7zgJ6HgnM2RjhFrL6Gp2k1OY_5FzdWVLEIzszZXFlJ-jQAEwc_nYMBVR7StT2jL8lNCzCdGMzdzRlUVUPd
OPUtrez1_n7RpEsCxj28vU-97eGDxKzHiS8z7eEnO0Pw1fXjxop6G-mkDJo7wTBI2S-HWd1J7K_Y1JSjuqcauI8tFCLUg2gUOXUsX6T9RKlwyQnLyJIgJ_Vq
sixS24z3ZG7n_HwUm0NGkdbDy35LyF-f2dZ6WdfQ1b41mDVpLi-Jy1OaXSTL25nA1W0fGkFwUa9sqBR5uXcvuCRE3e0tbPoEjn4hG3O1aiuOILK9gChOcOsL
sXPq1RiJBl9v9g1SAiu90o8CKgBvanaNbs4QinRbVpzL2QzeIMmhc6VO2HVzh82V6Q1sdcVmYDgkm4y7ECvpZ2zOYmmJf8fce1PvLsnITHqgKgl8KJ7Him4p
xpWjsTdf4kiPfGhGpy9-5jo83XzGAci1QH9DxuYrMbcIzmnrXaV199qdvLC1EMFQ2yffuFEWV_kTn-KYt-9QKHLPwNrnDPSrQO8h90mtSMOzPy0wcqqXfq7E
TWTo7EVnJynQhaRI0j5KAhBbTyJYwsagXjG46WBmVNYijwcmAQwtE6vnuvGION9LMG3I0jQY6Ldb7N7UpwWXjmnl3EaPm0Zr500omgNZJ5FCnxMl-JnuMKip
g6e6Npgb3yIfDTu-6j8IMYFOSPdZtivsTksdNeThD7MqJl3nUoW6F4p8gfHC01cNR0NGYM23Mn209QkMPiNMkmE0j8e1wN7s0Y2tCcyVXmEeSHoHCKWbt-yl
BWdWmkEI0HcKX0sAJNpjiKL6ERhX3zd5uaHUKK81Enh_9lIHECrpJDGY0wA_YPMFn6GLkGbAj8I_XMBjQXGdc3CqMcNy9TmsCNj1SYNK5itbJyMUi9MSK9eI
ahQe0AggOY6PUyQ2g5PQnmmWf-K606J6JdBBM20pGcdpPcA0ZbhMjYYz90bTxhXBQyku3P5L_ACd0ArWHsnljolexCs4hqImmdtU3Ld40Zfe6MS0ow9q6C2d
OgTehQyoO53nvgq0rBS7gjqRieYCjM4JRnMBEQEgOQTMKUoawqkPYyeGRr6ROY2BoNglz85OIwrm3koe90TsgBe9OR9CM8ncQzGk-43icLgf2CQ69sh3iPFK
tKf9hyG87VfjJuMEzM2O0zGJReRH3a8Jh0oh9xo6HStBg-O2jR0Mwmmla4xh4qsNjgS0n05Jh2G7jE1jYCO5s4abOuK0C5QohEDx4IAi50L4yJmg03kUn_cw
FCrrbBJWQOe2G3OyZMKC6k5Pk66YvVca9zdnB9vnuUdvdfvKnPDeNL_PJx7RL5D-YgHBljoVXDVOU_HdYAvOuEXF4OoL_tet3nt9OHY6KdAH2pd__xTN7I2u
NF7aiilTwOKOGaBpuoVzvEj9hdrQrBPnclgygBf_VdpVv29gR9oOS-hv5D8_6G6g8VxBEQhuZycwXhqGcSpRpYn0Q8kAW9zzwSZ3R8fytrGKpIvBIjyWNpAS
cd3U7b-hGDiYNyxP521HSWprjxqZJQbZ5A2TV6E3Rgf0JIWPnewaRP6KCk134rKEn1upk7WkEh8O3kzoL75hhNc4Z0GqMT8qE8_1sYBOMEOYgWA-ORiqepHf
eXGWib4zyqImxJ9xb4HR0qBDDeyuhw0nTL3iJKfW08QfTsd1Sso-xZ4TmtSD-7XhPqEH6kfh-9gOEtmaDTQdAMKK5AbvYJvv9kogUsvIHv8ckXOnMGfryTqb
1XFIohQW3cIf9mC0Pqd-JLFTa1AGHSCORerIHfNsITJhLgdv8capyckinNAq23hoDt4QXjGDyIem6E3Z5KYdAUztQ6E68NLbm6g3KHHXbEYW95NKDVpgmD1m
86RmBjoTgJMiR9OJh5K3C1TYJD8mHIgXYzG0ICEGw1Qdc9dV9yeFQusC9gr9Mxml3MO89JHnaTOPHHGfyKAKtuYRagR4OwShYYW2DMAe84dwyQHY1SLBp3TR
0ySNEQgeZ11577GpKXyLDgKvBgs1PteIx5sYBueTKnJL7G3o51_fIInPBEkpUqnHmtskyUcjpJKGbsR8GrsOTNk-lypuP1TcoODNhFai_bgeOFXJVQVn-Nsd
fHIR3Qz8U5ffezEMy37o79tKLMIFxFXOULwzHOghjtZ7yoi
}

