sprite $image86 [139x139/16z] {
xC610000082W_QaNgG80002OEJlHRHw7WG2CMhR4uGpbzt_QFOGKmHB1LlwZrjL_jhW-C3Cwq6zP7zjlWHpmLdu9nDq7vdu8nc-tSZzah5in7_K9-THOkHLo
CsQh_eHap7uBv6RCrX9a0MOn96DkX6GClXDJ4cGbPZqaOuwFRu1OWjo46H0CoCsOFK5km-nfXxyDivkdTHDcJ0IBCFKTpCO4kG-pKNJuRy1yK5gEsVwOiXpZ
2JDDuR3SZHaKgnmONujfssLAjCFQhy1GfjWFw7uCe_dfz1qI1yRlmb1cHFIwDtzWi1PJPYakKpJl44jrIVTXF1fEXrlqTjH7Vk_1k73G8Xew56MtrMMQVsox
n5P6SgjEb7f0uceCPZ0Mac3UeZSBrBDjJup_B6PtIRA24sHjfunxdIlJUaob9097d7QGFB7jZLgFcNXIRYP9VjXfhPjr8VOoodG3flZ0eDHJvl3JoxuFeFZZ
c8FIw1BPqKBMwpE_FupvQ6CmhTWfkE7KlfNgtuJ1_sCsI18EWjshOeTlM-MoPkUtoaInKMeNYABUZgDCb6dXmoaNkth3oO9EgMp59Ed7CBdO-n6nkvkwjR7_
te8fa2H3A-fcuH7xjXrCpLw8-RhOTMkTzAOJXiq6PNMP7A1cYbrRZMv6g1-VbDLtJWLV4dAnhLXtiVhf0wUraO4p8lor81URPeTE6As9gp5mHMY2yYYs7wsR
ebPHIfW58ma5fjvhzZWBUA8Em3hC6CcWs0pbKMos6fQcycQpnqZcABdOjbKv4oOr-_f81gMt-LTrbIGqiSjVODuPoQ3KISZpB10ztFb-P435DKg-v546HF0D
JFfinb8SKuGS6NSIxs6eI6kMaiy20pjTLp1v97djiuHy5hX3Op2SArEEQrvIkM38Pm6yYs9y8XBcqaWKsguGyYNF8OezOdn1Vs8cHf8aJ9AhnGPSfZw6umOo
OIP74j7nSPcGNs-CrdedHNUp_qm6yoE9-YU2N6p9HQD8u2iCg9SIJPHdejYaP3ib4GQOCM6--cmKFX6JkM9pUCY1SOp8y4MPg7Yvx1r0BZOV4v1e1gJy8era
RKnoiJzZIydD79-HSKeS4EgrH6M185tow00Uc97V4IA31aOHhopTb_zmka2ViGKbj84Ptx8ndj1BIbjeo9SySpGyLAxnhGfgO1935y_YwoUsFUPXpJKMGIaY
b2KigmtvmMyO6Fc38hwa19R791TRmi1GUgvCqOAOp9tOQADCYJAprQ-FpCYl9yhKZM1ziSKNKrcyrS-VsEw9idYhdt-zKP8pKUQs-lN5fc1C5CNQhNx-aaVm
IRaOa_MHULAkRVNhYyqdPVrMV_sIzw0isEfNNF8MRFMhpe9OiDMlAVQ2hNvPiM-EoT_jmR400000m21_wrdigcu001
}

