sprite $image73 [87x99/16z] {
hPQ9agCy38JnYNKux_-u_oANkwmG_d7DfFSAgTaFgMbB7Digb8-lApLcFkDteV5a9YBc6hv8BSGqnDzp8WDg1RVqjVvNVSFYK5Sed2ZVwz-3yzz2HT2Nd0ZE
L2-4xTUXWhvXSIAA8IuA6NVvJTWGglP-8_w3nGZLWetXKdxAH0txeLgnHLH4GFrLs69Z8iFwydqgzYr6g8O6DcMO_OUmbLQXOePeYuSfDt0lvxV2XaDrtXw_
I7L1DiAdIU6SyA7wW2KMpkxOrG1NVWnRg5Sj2xQSbwnpLegp7-A6ppnnbvp5FbGkhASeKYLwXiDqCejzXYjyvdzgV0zR79DgLXlG044YvVf1Odp6kIdZTkzX
c_u3MyZtQMBbN4N6PwM4WWQsiW_RQCLXiw3FJ8mgJj7b9Wq_0UmQDa0NBFi-PonTh12y485TmCAyPY_-Ks7hEIt1Q-5jNR2vSa0Eoz95LZ2B20nSetHpfRL6
V0Q71RHVs8VfX3wJtSwvOeKYCmuhsWtx3BO35fiotLp907ei6nHOuSzWPVFatHKnRCfGO_Jli4zEhBSJ1AyQbXHYzE-m3lmiSTsVFbM00hi7PeR53kkX7WkB
dwarvPnA2NSiYwUEt7RTAHW6U2nAzLYbS6ftJknZVQXSjNHDlAu_W_bDFbHA8Kll2kmOMyu9tiAwKDavhDeTrhxP3zlTL6r62SrZxHlT1gD_g62jEgmLl1is
Gl-GribznsOL9zxg7wAHQ7h75c01teQgj3ngwxTgkyeEcEK6LPxUyWthOlPiiNme5IyUfQl3kfXvy4-cAc7-11m7J544xncC_Zrs693YSPnT9nQ-87WFJg1_
zLIsjxtMZYEwmJYwWCedYvV-jMNnYRNCnojS2gnfBAgS1dZCD5lu44nLoTS3XoGTHtvf7U7oMBNr7UGqhCqqFTrvrlNuH-swJWEomy0th0tUwwvph6P-DMSq
C3owvQRZEjjTod5Kt4fMxbLfwpADhcqSlGuih4mgBLf6nmCxU-SKz66NfIju-Xwvi_S5QnYozsEBapqmCTRZvhKJF8msmMZ3ObpdYfDg0IZWVSJQdGV3oe5E
dLYbgu7bK3MZVy2gtcqG-tceNYqWN8kIP9kmToojSu36j52X73vYs-HH7849yyIgmsexueWdR6XS8eWEgnpdv7Zn-tYfP6nWrtXgSZo7nMR9_TNrrJ0BPnz5
1dXW4K-rEFuFbeSpOIpkYZXSfYSBewxLZc-acQ5GpEzOcJUDnafOCzYGiKqiAAxGa9ievnLxgLqtnW6mYt5eMy2YzLW7fP4xRN75egppfPZVOnxY8lS7RB1g
CDd2YhrAoKSS5vOB6tnTLIcEpn-niTBbO5HaZijH5DLQmpG-dVXFgWI_xYR4qaJ7LtMPnQs90EldTqgZyxbwemyO8cYSOhaH9uV5U20r7jImq3yitik6z2Es
M76qFfEqJB0FYxVPD7t2Ol2QatDFdV5g4LZ4C-3THcnGYJvWcUs1pVXcEqrIpKHW4Sz24UysR1tf7Jk0HSR27TVnEliKB5oM5T8bdgNFTwdONZJ2uh1kHxO3
xmN2bkOn8RLtFWfFCEUY5b9JaWAZFTREMJPCN3l0fLQRHh3Gl-5alE5uh2r-wOpvFNHQk9RX49lZkiMBDnnWhSogBTa3MyJL_au7bDc1xujN3Ojn7QXWVZj9
EPpW18psYr0nQkp4ZiIGpt5Nj0c5Ko143gh0Mbg7geVs6K-lHBvWM8ptX14kd4OFbUnnpnQVDwpRBUhVSH-4i3rZBLnp4q88rPDysBI-OT5frjS2HQYS7YtM
TiFoOKAvs64RAh2OiySkJvkcjIvK3qBO52VPOsSsazv3jUi4OWOicgQk2DMcVDYK2x1uHBch3zM-gW2SAh06DbzRF7wbs6IA_NRO2DLUs1ns8rHxOGDsErJx
ONkQLB-rM87T3jL-s1JZzYj2sFgt-lSM8rJVLE9wREi_
}

