sprite $image408 [130x87/16z] {
nTg7UgCm5uJXKJ_pvVwlzo_8U0l6zZe4tYsK-9XvQ58G-a0gjVKHNaMCtblDIMV8jOVDmZTCTlHMVZP6Rc70EsQEqR9-I0t0homXQjBngi5l0hUZCvG0xzZB
e2Dry3-2o3fA2lm1N8uAOFmHg1VkWOcY0mpyCPpqRHL_0qCVIxcqFYByJLcVIAKDcuM_Xz5wxwtLydx3bTimW8_1oevUirv9THZmJm1mjASXKZFuHu57kMxx
4-nagCOdWQwDDC3dsJPREV29jirMCJuRzRe0ssOh6ry0vqtpUpA6fewdgqw5ZA-2qtuF13WZGjlV1INdu81Kpyk8lRC0fqSxPvJ61xkwxvTHf7YT0EwxhFwv
RlLeBNXJja5NmKyI0B1-srUJwjTz4TPTlCx0FGoimMOPx1w6zZH1pSKjfLG2MavIAYKWQaefTsnQBkufXKjko-gwr2zLkTcqifRveJoU9iXINc-RHTCWaXOL
KwKgAIobT5_hh6sP7w76gmJAlKhgz5Qat5gGfJfwbZhpdf9IM99ABv9YMLl6A5AZjppBTX9q-zK-C1Ififu73Ad0LqXb9cYsGr9bgUk4b06IabdB_13ZPOA6
QLAPapedBVudAPbwsrX82aoHsbUNIlnFaM8jsq6yJ30m_Oy4LNT1dLzFICbhWgQxmNw2wSC4QLeIjDyJr3L1cevFC2VDuSNZ15sg3a-l4WJ_bA00utReYPq4
jmN0yQlCEyQx2UP4hGsobFleLPr72URQrCTegTtB0Z_Mta_WsPet8caQsmHbBcTD3UFqj1zKy9FMkIx_CtAUcodpt7BDIRURRiu36vTSV5_6RVb43NwL-H4Y
cTr6VVtVtAUEszHXOFtHtaVvDR-3eSv7lGtWtO_E33jeolXAbDbeNTjNpRuG_NR5N8PozQyieMbmvIwuSYymBdY4i__CDmsuxXXCPN1k2EhUKDhf0RR3YMV0
LNkIEVTftbRW7uQRTfnnSm3tfASA_Z50jAHNWfzxkD-Btj3mqR1ZR0OuJhmQw2bfTSLE8D8vOupxycdZhFijq9KHS3bZm7yVplfGFcBS3qRIvt8RVkJjP11L
tvNgetQbXO6JtWIfF6nOK-rXW6TlvEWGdTsXmbpRi9bymw5l9Mtlq4JHd-PB0kjkzxp_bwJ3LDxhMQIK5odfO0ElO6IThh3fMvviu0dtf0iKhZW0s_uQHD4r
EjTkNuLhjwzay2YwJX0jwq9j59tXlm
}

