sprite $image20 [159x271/16z] {
pDQ5kGKW34DXwit-0pzt5sx9lmBd2rrxUASiLbe048kI9EwrBJhYZIUfYuiLNWbXYYxnLljY4NY5Aq5lV2ALBhhNGgYYeqfGel6jEfMWDLwXIb0Bhr0bA8bV
c1uPns-LqaNtMWfRTA_rG88IU8KhGM_yIoh7kywFZ2HsQ9yucxWIjCP6fGFHaIGeWVtQZux9qAbbXOj9tNmESoKOkBJsYUZcLr0BGrA7Vh2XKqkyyGfLWjOO
Lpe_9lklVGaSupl7P7vah73ODVFrbkDA20C1rEPDkVQ_tYlIKTHtCcFbHS0__1vHrGtKCADqyokekVKjfYNzHLVHTvaQV_bUiTBddtDbq60R0REUUMOmwy16
mFGVpspGTWAsUE8TlZqhE7XRRc3MAszNOBhnzaouXi7R65WEtgO9WuEtAH36Uvu1UoHivC7RSGD1NdaR0c7qU8QbG2CTtkAV34Y7jnW8qk4jhY2C3czr1Orq
U8iJ1kdm5YSCeyDR31muXxSuOICTtc8WI9UtD64OFTvYeD6Px8hcNxL0kZoOBTj07tU4YsN0M-dyxf5BW2xEvyt_oO1yaEVePW5XV9n7uWKWWCcu6-_v3Nm3
2F897ccTd9kmZ_DvwB7n04vF6CPdULLJuSM7sK0Zd-U9niOJSDOv1puxxS8JaTXlm4aL1FawJwGQYash88plyKhDeSwge97lyegamNlzB-Zb-XulXC4JIN20
BrOGndTvUkM9PAFXa-USWtiotCiqz3HyPfy0WlmmBuVKFlIJ0VbvdeJFL136AJmHpVOo47O0ZPp54mbWRuxF9G80EPCdlPRO-JoGE7ATpSkQ-mi9qmmWf_AY
IiyYMgu-FCKpVfvNpxnmy4Iq6iq6S36ltOLxh43DHd8tNhhoOaf71_VYnIilI2ns-B0bJoGqEi3bF95ex9tafZn1oT58SbDU20LEmijvebu5r_D497QZaToK
9m5M2qckuYMVXvIYNNZOaXSqEnLSn5CRQzQ0u3mu5_DK3fv8CVPXn4uykV42QieaEPyNItYUrpLc6pmQ9lDwUv0NhxmmU18Io66PpjC7UNhmyeKdekMm62Ro
f0vUVZPS6HFDIYSvaoTXi6uyrSTvmK9AlFWmZIV_yGho7xnmuOKp3nAA3Hxv9LuczCQpCo_fuCLyvXqLfDqgE9iNqF_W3LQGNiwyOsd6VcmWO3IRo1DDyZTF
rHX_yYHQY_NQmG6SoHFnUDAOxdW9aih1czwz5bnUQl47JmTFO_qAhx2hnylfvwUH9U6eu1TuqU3nbBzqBrtNycbUlkD9AAzqxp9vFc-C6oxYIbxCAeA_UJ7B
IbwrTi-3thfdFQpa9K8Tdk1RtUk_yYItUrw_yQIUU741Rup32qLNyaBqURqkvLMhBi_MXfk8RRlNasZhBY-ri90t4EBnIfQrF3dnz2TFoRWnJnhJbhnOTB0A
eaJinqlikQkaBFUylWEFwAg6SCzhwta1WoUTQKkUQ6bTfThtUVq1NZX-AB7ebhp4baRtwWQyy1kFVV2OrlFqdXT9wohj9q_tu4bek5u9phmKz-3zQyRUjjEy
WIW0p_ae-_qVjmlzTK1sC2H1XccJstnhjBKH884aGgorp2Fn9NZIAiUJuCnBmD7q6hpHHotJ9G-iNeKthuRLmdkTgo5rugd0oeCzlFuTZx_X0LeYZiRdyUWw
Rt8GwbFsa9_FgpFFU-5XojDvTC4JMxB7e-c5UDY1m0KVFEZNu17zppjbByyyD7m5dZhEmus5jzvSUnuFxU29uy_nx8-lHYhy7AyC_uo7uoSFjpCL0OBltzud
7j9MNeralCB32vxQmTDSUSfRULgZF6_pEEZWoP8z7ebxUD4zHhEDgdQynOEZzsZqUdD7qnuUQ9rsc9NLbNA3Dpa1K9-ofqMWMtYIFQTEl4g-Y-UzyW01R0VF
CxFwcCeSxVmDJ-JWoPVUsyJBciTwy89oL1PVvMdWYKSTFyNhxlxOOAbtLQTSuw5CtjSd0U_ZZQxy7rZ7BjFf--p5ogFOokkkSmHFl1w1qDTvOhZsNkDMtWeC
wv4sll8G9m_JbknXroPUJTxX-mLCZb7Lil8IGMtowFEJW6mJhoVl3Am9Z5dJwVo9npwlnl8aa8Gvctdh2TUiwNHQU80mUHfddluSh-i2s9KrIkcI1mVF19x1
MoDOBZKgl_3cJNqARurWISwN3Asy-IHu1c-DuBcc3LUUrnDvQmHdJRVY9KyKdiXR8zWLCJhipADEV2PlZM0xryWg-k1XFpDxNoFeHqqh7ZpG9f1dywPlhMav
U43uSxookWSuNpB9V32-ydmNpzMdu4O4osoCpBp2irqyrPJecn7iuEgiKlnPdekRMzuyuSfPqndouzkpCAzxJdXcCFadjwUchXOQtmFxc8mQPVPZF9KI3TKm
k-ux0qkbEwlmXtXcPg6QAbvzHycapGo6RET9zkZIcDjpaoppsy3gUKKoU3CFP6B2t3HKB2lSxYcPwiuSRQY-aUSV-t1NCzCiqrJBEoBOQJ4wSYUlwzUtnvFE
ijnT_PuMxBPvHPBtyURyIlpSdgHgkDlj5goesTHEctZPtUESg9XNmyLTm_Ik2DOK6cxaTTVvIjf9PcvYdlSyjReoUgJiuwrFJqcs47VHRB_hgIKsEiktyHPW
cffvY7gst_L1xDQLNKwxUEi9XuQQgsQRnpqHhCdBDDorlLaozN4btJwsPrUUMbT-yv0Tl3CmBqf6vlR4mkwBO5gEyjZ4Mq-uGpmxN6q-jVoUac4TdRs5z_u-
keTRdVyzprPBqJ1rixeDpAZSnNlhjp4Ko9SluA4QgYbIqVTzuTp3ix8-yG0vBwwakQgRcbdqVH7Sm1lTrM_lOwYA0zZbWQchXab6nyq8Rk5LZD7lxvD7p0YO
boteRcRgqMPk5j-Np0PUKev-UxCUGuHD1RYMqZKpyPX1JBtrr7hyzYn6Z_VnTkAf4WEGkUGPcCVsr5NjvkVSuxDNtVts_Zw648fm89n6ww85DTfJ9LN2RqLm
IotFxQaQ2oFCGLy-Lzrc24qjlcsPgWbyB6yA1P6Op0I9b1MuphuETt4J3xNeoE-kIDOUdgcBAf6fAGj0TAyHLFEvFRiMmPgFWrtR8o8KPI9YOgDO8bzXfkP7
Hxl55TwExCqH5LTrbfE2ZNaArgUMgyxjcOVc3_E86P44XGaH1QFVnkV7j9dEmzKmi_fHdf2gfAgeXhXoz1XVW1hHRch9bkexULQVUA98IA0YY4YOtJxUFhTk
H9k6sd72iOy7vBKSBebmg1ApYxbaj_JaBH6SJoqhrbGDtyW3eBZW7RLCQ3flBsLt_ThU-a5yjBIvUhlLDXw0v2yU8Z6Q2irQTivsxmlU6a6HCFLeTutQnWEq
wZb7BTkiPMCXoZRFXRUseCtjcRfPxEATJ_YYbf69ZRDJVUMj9tniBrHBhVRmvd1sjmE6Qh2OMR09psF_mbjRS6xFpToijl7c0wgJ2V24fLdBD8ln4o_NfvRD
xKcgf9i_b6TmEJE2GN0QaH1NoVuw2O1s1bQrgxdFIspsE5uoh3CZMCP2W4A8ZB_d4IF5HGk6cOP9kEd3U2Nmcv6SsL805pC-U5LZNF0mH02pbmY6M3nkUsq8
lntKUM82Ganqy5nwBDj3ulNxqboWk-jZU45mTT2hEmbOdFC0IItRSnF7aw_gugabeUQFu9N0jyFHNOgpbizT-x7114P2Ga16ZkKBfyk_yrhXvim8pe3zclHn
-1BD95HXplA5Kzt_bUS8TyoCO4YTUK7nFmyK2P6E8o1SM_3VU4bmvw3tEf4VsHDbLtCcLtC2ktng7RmjeViQmTzDeZFFvvOf4I7gyb2Ol4UKoUsHQxLCgXf8
8chYUlbIc2jyJ9dS7hJwoiDGKMPYSvulmmVynb8CVpKKlzaU8ei4436hcFPdtuOokJgSdtWKhYx2OYacnBg-1VyyVORmBoErReyHaTc0aKXOzElFaBKhTBSZ
c6GchgeY8QQiUkCtbYsXMuVyyZbAfn7KMI-iV_z5iXKVW5jA9f6LJTLv_YtsXNUtpWaUDgZrjPPFi_BkNruoF7JG9Wz0Zbf64N7nl-ErmCDdjg2XYXAZkBCG
ub_nxC6ozQar1vdPnFw25mYRPaOmZjY4g13_CIyPDWvPTKK6mrBBz_9QOVDmJ0c3g9rhkMgCcxnsXFqpMx0Ga9W-U2bnanUqMxR-f71HBALsWrUotRM-zfq0
zE8JO-NjBvFRNpZXpgjn8tIx8fXv3oy9dZ0pWhTv9V2a8R_9QqDutd1-pmk2vuxMTLu9F7tGhl1QuIM6_7SyXvSPpi-y97YXGSrBNWcysA3L1wyLuVM6BK-y
TeBN7CuU8-1rHqlXCVCV
}

sprite $image20 [80x136/16z] {
hTg9ikCe30LG8mHemVF_dpiGvQawfEEs7b4Li_Howke6kzVZtuDKZkyDD6QX_2KjLHOU8ms-mHNJ9iWrxMgP7fgBPRCuuTSHodl5BRDH8wxQKkDESQk8qUBg
GcpLcCgwwbQDIDUQtvqKloFNIsFuZcpMQCK5G6uGk2E16WF5HMjSYukBBLy_NF6bAmIA2zQOgYpSNeqaiWMkZo2hCk-3_YRZhYeitn6BUTyJ2SrJ-OueVNec
Vg56xQTx-qjBFq_Bjokwrb-ydHgrJstnbXhZcdiRI_kgxks9egRPa7lBqX9UrJprMSNWgZR3_oIA13NhpxseABRgwfq6XcjqRV6eNeitLtKlfzOZIw_Qwk5n
8DEfzqKhxiBB6UJi_URIfbruAUVZQ2ftblPLh_EDKx1VBxq-NDSUvYDp_moEyLLlUJXEkxWxQgi6l8GvLUqVnO_8wk6VX-ZidxmpwELvWFtkR7jsgiZvJIyZ
zhD_oRC3tBLlUNavfPxzUrug-IX3-8MNthpoyz-j_TUZNgwOtxs4ym1GxpteZVcGRvxAV8OyjohcF_EvYNhsNtY09R_aQ_0q4wbq5TLOllIwBpJFYrZECvoF
QdxngkShSA3SzRBdowyUURuoJuzwc5xkD1J0k2VkGQkl7cCsA-xvMV9jUGsNVFabdqOzB9VvT7TVsiYtMWSMg1c_vtK10lTWUzzCq3mVxdgGg4A3RG_ytwA9
yE71LpneK9_v2FQzf0oSBL_Dsru-ga9D-DFTNU_yv4s3ypEhcL4FdiVlN7dcuxplmJXF1n2YNbazo0cXJCVxgtUzblw-RsRtyBwdNQGK_txJiNm5wjF3Y4TT
cqfvTkXUIfZfwN4EU5bKnX3ycS_CDXop8_sDKMLIVic72Q6bNtqUoZn04Iv_V1RsVZQlXFBPBwPqaCpa-wRXrFJJNy3JCIOAYH8yis7ovy9Em3FmaL6aLklC
yyKz5rMbgLJpjlBvqYeYx9_3bcUYtvsocyzhb37pxa4gl_0wDLaZwc1f6h_oQYMpbhk3RaMzsbZVCqfhAUn9fpB08hBMo4srfgY7gZmzRlHMewW8bXJoU0QZ
wTNAVxqx6FAU_RVflOd-RantFVKemskbBJLEdrW98fxTDwLQI-FwLkCyN8xI0zxSIuMcz-7k46c_wyrhGrDauZh67nZFpgHwtrFfV1Is3wOCaFcjHhdjyUo5
SqvM5KsllTTur-kDp-aXG6iYZuWyqRN6mBxzFyeuBraccMt9z6fRGRthQPyUPio9xOVFXyVBcqnx3tcJf6xzq-CoDg_nVd-hvu_Wz6hZc8VSNxpPkp-xmwkL
Gjvn51c0UsnvJEHMXaTD8jwHclO6FnvnLvkVDndLHW5l392M32bFJusRbDr6iXyGxdZdoOSD2cSufkTjrOGiF3EMEeR_xPsz73xr8U3moBo6a4HdHgwbNNkc
jUIQrLWp38_5ycK4A5MUDPftjMe-bW4Mv6b9wzfRHeJZoCrku-AjckAgMOrM7bk-EHdad--NizVZmnJfHivyDc8_87_qpfFWWsOrhfw_iCnRDSd7vMHQlENz
iXHNZdyEpgLNp_TTxyYDILNcRIpNtdao1FxsLOLqVFAiE3m2avbBJekt51UR8cSzp2FtOiMjDMhByF34lAMuy019NVOD5xVMs5yyUxWsnX_1YuShNAEggB-L
zWViy_KxiZ-PXbVJyRqfjyBz3m
}

