sprite $image332 [330x192/16z] {
xDm9i-8u30HWd3Y79UN__zq5d4UNNzA5UAej9f3UUvUvla6YmPwz_5lfvp5TmZcJndBDS484auPIC_SdHY0f5sJgJf0_fXkBN0FBFwtBC_qaDR1yRLsUwUQh
Lvu5WULBw_9ygRx1oU-yk2xF35l3xOW_NvTdEXKUZ7W-fPvBgdWifwVhyfGqQlbA8phJgyqJi_GteZEvg4sNRYQMpaPqff-Bg4qtKI6KZaPqffjAgPAtZ19P
b-TdFf2yT7HTgbafIDE8pkIvG79DNrHt69TbgP9aNPw33Sb71j6j8oGnubYNvuVYhIJ-a-e3iJfk9F46ycm-XKfU7ese8bB9CkUp-HGY2MbLNHOc2Slk76mk
MJEfSSboDgBQV3oI8vKyroMQJrpoYniHcaz0acRgld11-YKN8dckorpQn2Nb6ZIYxsm-BOUgZEbLoI_zl2rDtF4cgLA69v8YxPT3w8X_VlFPWgYAp3sNNEnX
jdUS-_6D2Cs7HLLXMQQEIUg3JFQ3TVbjpGUIe5J1V3QI9iYtVgIEviCbMykybLJ14l1OZkcBcWyaQpRh4f8cYAhFSlZSviCbGObrcI2vQ7C2eVPL9v1yGNB9
TiI77qbhFpetNN3Ky-7haZSVNiltHZp_bhmwtYMJ-sHyI9_OVBWainH8rdzuIDwsBoX3ZUZuWmr8GddBNUvdi25Pd_32BVLpxcIbyGL7RhaiYi5k9Az9R5sg
BVefdn7byWeajpGuhhdn9dOoZYUlj1-fVsppWIEZrDRc9oO5ahTaqQqZ9D68Fd518gAwRocWR1nlCwksf6QDF2nDyLWX7wb_LlD1X5kAwcP1Ie5aUpAE1n99
hCiFQJuYMylT6L__t0vssKXYNTh2997y4OEDUVQF-COHacsIs48asReyVlCH5VUwL6i6EoA9TVb9pKV5jIuXMRz0I18Pql6R3nznqNrAms279P5ymDCkRYdI
lkfiHjoiIi8nAedCtP6R3nznKS68eqIgY9hjlK1P7v148pf2y_5RjgJes8kfx6_K-seOku0arkNHcW-drEhI_giAkIU11IeLWajYUz3C_G6R3xU462mLZcsa
_HoOIE9W73b08yf_HkIDo9GW23qPRoLLH7oMOpfKyo5poYtfbo8duv344z9hcG_OV11PGzebZP2JyKPIcoPLoh-_BjCGOwHFInvX9-EGD46KtBSaw_98pKS4
Zd-nbFsJyGwIIdvDcQCH7QZv2CcZIZeaaROHhPBAVatPiuKvv-Cq7w7Xwz9_CZvKoVPW799oYsF43p7OgWvBUGh9B1MIwpz0KjP46z7xcmyA34tnM8fGIbN3
mNZxyV0BdMWuGlCHDVNy4dYCE75abhROzc1ykrG2ZUZTpGUIaYPnZRXmIE6MZ-Q3OealXRov4M51HYJhAQ37aa9oIpxOoFlN9PfFJD9tBwescvTFnbj7fP0I
RqJnvXELV7OlIatgT8lwZtgqh9Qjev2yVLtcKkAIx5uKdbALa9n0YWf_NfB19j50kumtdxZaytjHAlWIhusucTzHpAG46b6q-SGbsRqeJ6RpPTHl-P0qTJXM
xcV9Rsy-N7BtNfGQ1hELzAvBI9ew1jiMI8P6FDvyufAu5mN5LfAFkAeoINCwGZBGYABD9ow9v0B7Lf9RxfoCwo9tILFn33QH91dUttou9D9pIKJQat7vFUBr
RQ8w1vj8HXfHlFd49JicITObrgO8tXrgnNKxSac-BkFDv_sI677PEHatc3W6cqW6rcMa-Opp6oJPlKk8YBeTkQI_4SMRpzYz_ceUbyHeamsA3uFeO0Sa0-kI
MKrz1VYZP1-GnCiD-q-YwdI4P6348yrdpkcFhqH2xaLHIGv6PvzRsh94994XXPiFVawwj3ub9yU8atjHNDBufpIOPoPPBVaJCYvPvXnhFgW2QHZhQz7SNn9v
fEDU59EiZtDT1-QNCtJZ690CDAAH_MJKNZIdosKe9IVUalpteY29snCkIs6I674CTa0ojYup7-ofbFxw5_mJYVTUL2kfWkWhbf249Hm3aYmvKe26bCRrJUZO
uK7HUr6Gj6OY8SaR4PEibXZiW6Ii4P6dstsIftGrl3dc-PvIOlUY86djPbFNHGGYMIdX690Chakw0kTkbHx7_WxQZwM4xaMjajPkDYh9Hrmg7sA0P9An395r
EQNQakhBU9_x-h30lQXERVk4v9BSKhIbj2Kk6Mz4l5REGqfvdjBFq_OgEeN-Zo4Z9E589NcxH9_aacRMIeOpXTRbV7_zJaDt_UF--ZFrqzodF0NkHHa6so_v
48GaB7SaLKKq84aQKMHTrYQqVYNzb1Yx_rvKwuW3HlU8jwkuhib64jz8G3BsaVf0rcMUx_KybvB9MlNUYzgzNqP2BJTzSkUb6zzEG3BIYCRzBvpoMEQfjW5i
LUR8BRUEMbwEQjidT_SaxWG696EDQDhRjUb6l9R2QUpmi3Ogpootrr3-4564x4aRvSVI0fB1Dv3pVbCVqy-pCPCFBVttee8p9yybKnfjNPTg0SbO8nfsltYg
odNjTdFbzHxqIwcMNiUuvEtxYBKSa0o-WIJlv0T0Jla-ykvxKL9FgRs37PUyfd-Ck1IIjxo17DDDSBZ_rw6h3tjnn1TpDv-uv2s3BaOetzk8wfTFVVqudUm1
Rbab_OCTbxoaoVutonmvbrYhUSfJheyO-z6tBY7fR3vnoPgksFyrudCNUGFvNtjdekQc3aDX95iBXBx_wzuB1wTa2bqS2zAlTfVPjt-iuoDRLX8sXVBoPZlT
JGVA0v8GoAj8OkGgkOntHER88IapBRYp-M-4-3pZJZm2-rgI0-dzSadoKnF0MIKH4OkVXtXf45dSoFKa8PTLqpBU4K4iHw4TybD716kCkgXxIEuTqVXHZiXI
NWWZVzHr4rDEcuXKQ6DRaXZvKS4o_0GIGvvBF9yLlIo13OwtaiHO4qWS2JKUzbQb1eBSr-aDbovoigDuFqaCdhuz0aXwVgzw2EvINNTxHEpRMuxGtqzoy0YI
Gk-Mga8V2AlFnbF4K9p5ze-GD6vIPUcIc2W9F3gEnqNmv9D9ndkW-i8s-7XFdBdCu7-0fBIzPk8xTfxAkqMJdAOAacDJaagjhpuf5tPIPE02ac1vSafxyZEs
NBkD8wxZwUvtH2anNQ2JiFrtaVGSTvCCHGgqyIRELyp9wQG6Oygn98K2hoql87arGwAsAsqJ3PgJ4_wUdDAE74VIEFOglRACzlLC0cUw4NFobUMFOpQA8Uaf
lhq39gR-yCkZ73Cd7zlVUJue79Y_FII2f8It72aawK2LKuGBEfcJu8YkqrDgJLBfgYuFnlAYofG0iZL9n7S1EH-KIs8Zoga5oVX-tl8BLQQij85qpHun9rUY
9yMIwoQpKYkIdc_eXWDLJcu0wMk5DOatGlc5vNnOQrIgWXwv1Sdu9at9pavpMTUd6HZBdTscB0lE-PXZUQ31CLMG370-TGaa2O3IYf41Ctlxv7it9-Vf5IH8
_l_MsUazafxkwsJdgCh2hYLstTY2bd2GV3c8dUSdoJKBUkWx9ENcxegq7PYDGYUIsaOkvtdUzGG3oyLEbli-YFyf5v810XdjY59IA0oo8XJx1x14YUHh8xK9
jTWW2gOZW-GKuNpYUx5vUeBMH0Lvqn1VO1tq-yRvyClZTCmhIOm0vnFgY9nnponp4jIwjOroJBwJVj_eYOEn2_Mo8DtKiBk-9el4q_FjZ7IosG2LenOZXN9v
2sHpsdSZ2d0-eNBfeww-quG7d8oxU6kQ87OmmB8K3EpX1VIbZ7T4g7OfaYa1M-eWTaGIZsDqsBiWmFb4owKd6eWGu0YPfDQO9KJnwy3ZPnrRd-dZ7m26_Io1
B999760muI6FM9xrfuvoFl49P7O1pwqcoIy9yTDtZd8-yOu8WKtPovuRI3QtHB_34g-DSZxnZYXZxyYVQRXaksGLFxXX6UbyuXqHYjXAYAE13WSuzNEMRWwE
uSudFe4iQxUA-kZAUBTmbW2b8cBZ5E9yhfVBNCx5r_de19IHZWY-723Lv_aHv7okbql5VLp9F70vCOjqHCYr0VA1avuGvtEz8y9EXXTPOdTJzQWGV-wZcOhY
_a2Syxa-WSmqK4vOUhPpdXJ0ian833VqLVr8vrFV5KBpLbVDu8qW3t14Bwzun3kVgqyW4Th9TCiYNGVYzXL41MJnaRSvd-2QB2pTY6kfxwb-VvtF_Ove9ScN
b5N7EP_x7P5nmlMeB6b0Z4jEASVYZ7S-roUGI6zC4Y7-5Jolcvfv-8k7V9aHB2QC2Ri9fHiF58eotlbSBvT2ttsIBMzSzznIGFuOx7pkbqlNnCpP46fanjXF
jr7REQ9hdS_z2QGj9BV5L2p1E7NdKrF2AjXFzvmqu_GiYtVdKrEJjKv4BkgP4a5Lk_EfAJ8GAJl1ZXYa2swr__qZdqeOs_DdXbFlWLsHG0gH58D4UJMRqfrF
RQFbKdDPGhmxdpgvt8TuMedsbARQ4IdHxZpNLR9e5yZgIprAPMC3xvQxywcIonBYUABBK-xEfxecIx7YhAXf6AmBP6rRGJGQyqn3ulLWLwKxdweGHyN6baYI
Ba_OklEfIo0Py9HPCzowMW_iYWGIE4WA5cOWxywdnX5fohkD3LGILJkVBfVbJRAPJ3EcRDtv_7bN2ApkYW9hemsx_x50TaUaNhex9IjhidJdKvT02crlqWqL
MNS-bO_KCv1uMNnCEVi1xixkT_lIRudusywd9v0GoEvyclJ96gI5y-cEI9cIDt4-NIwzYVFfZgYLy-bosT3vTBciTpvzIDoUJvVBUkVJGpmeiBiZgdS-VP2q
SpxT4RLpFbqkMmba7_9n0laV
}

sprite $image332 [165x96/16z] {
pPcBiYkh2aL1KMHY_lztxrqTYyhg99HxLTT9EE_d7bjmJBNfcceczELL1m0jNqp8OWwO0Ps_4h1eR-OuoWpMlf1Hy5XcmAXV1waJC7l4_BxHP4E3Byh0jAyQ
pMPknEfumfGlqiuF954PWGc_kNtFQ1O5x0v99EOmSv-tsm7v7JhYPZ0BIA8E_106v1VeI0x4HqYInHYGPXZouKwV8UiJv2Trn3qGSyWF9kKnZ55mvHFa-iSV
JCewS8S83aTxX9mms2c3Hlt0C0QaEypWLWFIOR0F9cLevn7I7GPtBNT86EBl_iAqnl-bTiwGZeEhoRot-aUNAdZ6bF-yqy-OcBTf1-AyzQK082fFokkr4mKO
5gO1qmr7BiwflmFTvmrfKbwldI342TDytZqvDGBTS0zq94bvfNQY49GmB4muC9U2R6e4-a4Oa8cEhXv6mCwOxkvp8Jv0Kh-jGfAKbsed2e6vBechgzFDVaEs
CsICvlNQUOCP6zSmtQV3TY0lrb69ONo9YI3rwJ44C3YKVqFEKmfWr4krar0-fcCKS62sHqYFV_dYqMo6310FcB2NWHwGC9Zv6TCQNw2T3F64-JBGH_c1ZB1q
EnLCBjLEr5FM8Gtq_dz6Wy7NOVXfDCjrsZdt4kbYFcB-BE0o-kcd53gwJ3jHSvZ3a602WVc31uiamghpQ5xMwO1ir75UJ0TU1lhz7ov40_0QSzJBj1EGlzzL
VEAeDu5-3yjO_1ZbH4UxsiaXYQejJ9yhJF0cq0zBdX0DqvFHtDTE3adK0CmPYNUIEs8qvxdJzwsUwsX_67D8uX6n_3hGpNp2fpyXndjHdfIvTW1iG5A_pHEa
uHJeC3nt-lpAiJ-Qye3Og-v0Qgpakq2F-0n6d5yvjfCoEXsBNknjuFWeRy-ppts0tzaGmvX0fgDPkk7Xtoc55DBUXRQZyoFaX3rHuZ5xmZa-RnbatlE6OEn4
JKcKwINaoZgJEsGmujrYBgN7CAQGkOvuTTkWCgnGeQh3y08opZTrRHotOudyUSa3yi2CJkUGCPgP8G4qeYA5Qsal0im3Kxd78Ip6yWaJ3lYwfEr1HbBcsxjr
9IvTI8VsSVwHutm3Etwe-nBXzVokcNnWd3vpo7mqUMqV04eoAhKZfV5qlWdCwS2APdkxpVoEEGCI29cd1UkSYGXQwXYDM8gCe3m_M8JsF3d2-wg0n3oGKyXS
HtKX0SCALJEcyVHW4PXnJdnV0HdjvkOJc3cavKdP3B71r9XRupA0L-URwFGEv0n8OfqEs5O1ojc14ZOASIrKXYeiC14zJpgTGH8LsyU4jImZ0HNLmb9OXk54
wUv9ftD88i64xM8EoNG4e11NgSob_r9Bl5Zy4PAe-yH-pqjwRXjz32OneGx45lTq3VED4p_6-9VHx7dFeLIj4NSH0smiqhz3HlNfs9pBNlAxXA4NvYfCL7ed
NfQw0582ShFRwMYQQQ4wh7AOz0h85f3R-oRLqP1--BysKPW1-v10x9iCSjz0-MXIfLAb6p06zY7NnNSLwZRa_eMy1ayVbHG0J8ZRBkIPSix12UHEAgP9YLRM
uOH9W4rF8Y1NYhht17Bh9fudvNqBDH9JgRe1-RlVToZSN1B8dJUDN4TMM9LO2XELiTtm-7nYwu1d9O7CXt57Hz1ZapF98j_0nFsr1GSXC6_kKtyWS-ty_M4L
em-jXpQhmZOnuxN5C1tkXkas7G3-JJlxEgeijTGkfBkB-V14O3xNd3eCbt-MYD4q23LbuYvj3zDm9mCMdyF26flQ-VVHx9LOXAZKlglCYLXCU90P_gATxQIK
GcAToB2_Wm8pFai1xxLpmMXgrI5KrAhOViyDiPmsWl7opxSoOfWArLf52sthQ7eivcWTIBHpsHUzun6XCElOjoOMPTCvaMZdgj44XbIcMfbuk-TnRPX-OQVp
9owjlL0rNUGRb8W_9jgv-7jzjyBQcMfhQh2jkbmxUL92gMebAi8ajHYsCA_NJguZZ5fALQKYKabrx53cmtZzQAwx-E2YhKYbeeOFTJhN4Gw9L1NYtcYZvxlQ
kLv7E8xiJBNKWSzsEl_WLwYEmTHXLrsohazAQtq8iKYj_RF3cDyfEuamLIK1y07jHAKVWmpCAeLQguPF3cD-fzHIj5SchYqk29UTTYuykFTAPGocfje6Fg2T
J4U1AVrurOoFGV5E_u5AxfH2CXfnhOP4EnyUJHjMOW9IxNnKHzPOyIdjxDyf4-ryqsX-NZkvZXBjVDDe9jhvefw7ThwuwhYgq_y3
}

