sprite $image60 [130x91/16z] {
nPSB4Xiv20KV0W42JUv_s_tOJZJviLlZZDmN45LqCpRUWDGPdqH6n532fs2F66F4wFW8pIB6at31Vlg8yOq8QzYB-ElzDOFIPnQmY27O1Ebw_qo4ysu15ak7
FGN-dXXAcmNOgmCL2zYYWwptQoACxbZ0JmAKg-Xx2gnrs5LWLUQE0kiPb6ugSAyEf2F6TS9vJu6r3di4g0_rbWBhCkyjyAP3pLwylq67gi3hPT8M0MeTzXHO
wx2dmFfGRn6Wrc53WJNXKluDsS0gSyC22Xss55Zhi4U0kiogm5qwR1IW_cxlUBy-r9d525jqoFpi3DOoFpn3llYK3Z6F_4fyvltZo4LiNy3nBryVdzjdo7cS
9u34N3hiMi1vWjv9yp73pWMS9uWlWkPh5NiMS9x0Ky34MtI8q_kh1Mk01rDVEknuVqqGPWr-kBQbmwq2_3m1s8tDPqXREjmfm2AUpm4GxyrZfAmoRrp0WZJd
Sm90NPeVxanzhUAc1Io0vZa3e1IG6QlFw8ri7UeR5h2O1m18J0NCJS2kpJ9ILfctB60nyQ1d26WS2dJlR8Vxqk6-z-TnZ8OdP7CqSZSZKfTkCndGQXNN1LZl
fs3HnZGYFPpGt5fFWSg8Gibt1JYcudiaiwER1uEzC_LvJ6c53cykm0a_eJCOaY4DtOL7PkTM7khh2mZ6ho2VtbeViuFCEuqu1iYALLmLeEDtS4n5Y_0EDeiH
wSLt-sg1HYZecKByA5Do2CMK1ebYXWi5bhpAL6_06CRDF1ru7UfuNm31VzDyEX60479hv5C5rQ6-Nc2j0n02i2knpG6iCYyAyAi2QnqU4m1z23JCMt6eg_Vh
0ciTGe1GG9sfpso05cLUAR2cZUc4CJi_3ZMxce2yqY6B0d45YLGIo_7K0Hx2-Drtkpx13HVH38Qb6ZrqQ3xrCTZIuN-UuEkGpz6QpY2GUIDF9jRvqogg0ZlU
WyTKac53dZhqyTD__h908xp3-cvp9XDazDUNwaLSEC5Nq1dSrFDHfd4_Zr0MA7YRyw5k8xk0J2rF50KgBb0UwiO-7SyU5t-ymFgxhI60M9nckA70wb1pOw0B
dnPnGu7beJO2n9nzvejR2gnr0DlXQu9R2gnr29SnrWGt5LZh4FsqXViAhB_R_aiJdR09EULO57WhcdDDi7u4xUJR5shz3TdEwpeN1MxIOHvVGl0fI7CM1Mug
yxq2_mO
}

