sprite $image316 [295x198/16z] {
x9g9SlCu38D_tG3z_k-xap8xWMMrt7lZs9YhTolq8qZA-VMFgxAdu4jkfK6IzJOYG8aqaYYt5p-ZP9iPoP5lFzPg9CssRNEZLX5rA-CBfQSiYAWR9PS54NMZ
f4ODhRmRfSabgRnss-Cga88JQKJTwckKDABoZH85fLa_3mStIhmhRqQ9jaeaEnWr3GStIfpTk_B-Khz7wIcx8ogDTNORLSU8kb6IWliUA9IheNJqoNYKNNP_
gMA27MQasAX-9PJMHb5qvOYg2rfKVmmev8kWfFehbJVILL0A8kgYbJUZzFSZgbm69IqhM03K1VQN3Fuib5-fXn7ruVjBOw3wDFEomq6Caa9H6HXr236KIw0q
Hqoxv70GepINJS85zvVEI3rFy5rlVobHlHKIQ4c_OpEpw-mlCKf-j0fWL2quuqWPbuceyiT2AJK07kC-E37xTuT6pSYrpqD9OpSF03rL-pfmav3w-8YguH2W
AWFmGujxkx5y-yJz9Ot0fSCtk4rp46TyyFuoenJJr3QtgQVb3AKsnBTwzIDGwYc3W3Zo22K0tJQYxjoBXWF_x2dtbnfYv5c4geNr69vI9p2AkcSaQ-KCr8nI
456dG-db0PwEU4mZksKTGCylzunzQdfcQvJcY3enIatzx026dz_ghkUXfT-R7DAnwTaAfI2YJeJIF2Rd0PWC0SgPUy3oJTDRkdIMHyGrchgNDbawc0t8e2b9
BpPiWMH_EHDAdPHqzis4RbFFyyqB891fuuirxo-dGgax8nXPqI16hMP0sxct4TYuRTpRcX4mT8A8oeX3ANiwluB6_zSDmAXQM0IgGzMpBYws2gGuel8Pxd4r
IQkFIsd84E0zppdBzEIkqlHa3GwI-zrVufeH1xTSca2yq2k2CdP3WDn55RwAw8oL5wEK3fQ2qiMELmJCX-4ASkA_QbHvxqS2BHtQ65TTh3vjQekfOPeh_rhb
ZVpEZmI0khz08XwdvCXJ5_l6figZJQUBgC98lhf93Z_UpVGh0krY0D4Vdwvg7pS2yp9tjeZg38M7UdvTRbVfUTh5yE0hGOUh19yEnAJ0gFVSNynYcrmjO-fY
xSbPUGq1SY_-6he9X5UyhhVTN-JF3so2hRjOVrQK6wEWrQS910uenK2zrHMB5aDiawswc0wQ2XebL8oJJXPHsnOR9JRLmn3WDer3PzZPzAFEiB_yePEyRC8e
oousj-fc08EVVQQ84fO3ezmcsMNJyDn1QgR3bMSwm83KqrIUsXHNdctcN3NjOYDBqzC72E0VDEaC-ykUvU0WJjMhYqbOfT-eDm_TnraWYCkcpGvv_zVzobcB
y1f5veW3GUtAl_xOFcnH2cBE1TCjIAltBnPJHt4WMNLmenIKCQv0EY2jthzaSzY1oMORdu2iH-pvwH3LkABRc5nJAB2udmS5zmrC_Q3Kcg9vcIf0FwNrYmF5
rETvYecQz2e10GRqrq35xs6wNnmSMGog51G10HY7T7XHM2j4CVyDA0YB_oLNT6y2QeeZnslnkb3_4jzTqRsqbsXwtA5JCloEbK8KtjXoLn4rRaYsNlHSHoB6
kolgmiHnJCxQ-jmGPJ5n19HyofQkuIKiqxzOQ-elo-Kpa294L8KeauQP_Ol5D0Bgm4H-mf0yL4il8LoOzYKypsBgzpmPXoJ-hAMVdohkcD-_u9ujFtfA3LqU
RVZpKqKlCq9KVvHyabFQZ0hHsbS8i_kN7NcgGVdBnG6ypccsD3j4USu4PUD8941L16jECaaYdkzvqILHBRrS6G5X9i9shZGN6B5iQGAeFtXSqT9B4O1mI5Z9
dmoU92Cczo-xVDlpt5bBBo_iqsvs6Sk-GZY0JGrHTfFvOL3UQEd9wRw2sMLKUbaTACmUiSHlUPwD6NlK8g3o4NN8oxx2bkRsBtRxRH1K_uFEPFyzQCiOJ8IO
x7dkEyK1l35ZQUzswhlNYpLWjaGS7WOLxDQToWrHiXaHnAnFDfBlAedv_n4H_d-Uwb-UB0xITjwwKmSIVtI-WA_lYm3yXgn9hyGcylOLaW-5g1qFWO8pMtSQ
3R6TTncL7k6hf5TbEWfvsyx9d-fV_6NhBceMCoE23NKHK2_DUYbNHDw-ks9GM3j46PFN0fADB9QWwh7i5cl0YGPlMpX_fd-9Deq1O2kB9S0inXP3ioeEsOD9
GzJI_OjgwUKMU61AhhsqY6OHPN6G7PX-8KG1I2QD9RStifW06Sock7AI0MbyH_PWqX2rxd0JW19nebvLSbuL4OzbsL9SbVv0CP6MGGUcvKCKZXEt7Ph5p8ZW
e9VXwwIdtMR1nBVFegHzdkzVzZ7FivZirbqPcdZOfugwDEkP5PFzFXRKYs-CQVd-nMBIB6P71BQjyoeWgANOxs59l9gS-EhGN-QEM9JJ-r60jpuVxp_ev1zC
h-kFaLyNJ4ltBuh9Ph6zP35RN0NfUD19_e_9W3h-xRT6B8gfcSMIbtmkhlnrQV7zuHzC1vPZEA1_RvyL-nVx8Z7MMUpuMz2aLma8w2bY5PCztVhB_16BxYlK
MOokJdfEyIacoisJUp2jBn7ZECdkAvHPLA0oHy_4XXsObkzV55DxQT6bnjBYc3bDq5y2FrSSj9SMzskFEsPFloiHLvWaELEalLrQx8_YFoqHes3IfATUhPWK
qYYcUVgB7vI85LJMwY1qB2tsOlhvzsF8B2CMh-vibXR7CSsMYCT1iQuEIdAGVziv3zoymHY6ThUczDt_k9tP-iVBeAi85cPdaXTQ82aZDt-m1wRtLx6eP5md
fgRvXMFI_yFK-aJy21Ecn34fOiOhhlUOE2IEwQRSdF0MopzCqcR0vFmfIFld5zr0Sc3QjZ6lk6hRZ9XUzkHzRRYYV9WWgFuLYnyJV_BQdeZzc2ee_hbI0FuL
vSTKdZogV0K6uAfOziV4GUck3_q0nfLV7AF84rFbAqn9aG2JyKHiOuH8YNqV8xDWQbMnlAm3vw0a8ALCYibViVWXyHLLfSGnzLzHaMZAamUaL34rgrZu91Wk
A1No1ZgM_C8fhPLrLk5KG5Kf6J0PAXO-yH3IQKmNE6qwAIK39dV5mYcTnNJ_kxhycc-H4iFKFxyamdJ_sriTgKZ9Ysd_5QL7D0gcYa_RQL1LIXnJ_uebdeif
pk2kKkAO-bSi-MnCG9e6J8OLPSMKF1JwCVdp2yUq62PbcZ7vymlVJUiAfS1IufZwLonw1AI0gl04f0GmEUUZmHpa2Kxh0ZaW9J-c_VDB54vrIai02mQEgNz-
oKTpXL9WATtFTpyKVyLIUvJAw7wUBwKDdkdwvvUyR0AgbhYKn8--_VDB99fuxZ-CRqu8-wye9HWzzrzj7yqGziylef2u1fT1IyOJiU5E1xYkLJ0DM57mwikb
PC3Kg6AHuW61mXXBoO2fINxX4mJIIeCPc7CYNZVpuuDv_ER0BoMXrtXRLon-AUNN3yRfVo8E0Ccyk_kVY8KW2PZlmIjAI4fXNKhztsAHOIcDMr6A1YQW_ObO
19900pTqHN4fXVTvwtyY9f3IQmBwLomAyBo11cxsYWAGi0aOcryK7XCmfMBXKZAVuVfNB0g32HXd3W2aWCtRtFmYWmcObry291Ep2UXViSXW0kQjgBW2YPk0
mVb51XCmRqM5ePwSbrz6B2N_YTXW0YQkA4CzER5YkG29toZdcuCJa1hKa-qg5iEDScB5OgWd9rOio0GSAygGJ2PMB0OJC36_6Eh9YHKBgYUF5NKFoP1CvkGN
WmcObryo3XC0AfPrc01IiQ1wybXHXdfoOdv19k0m1uS9G1MBvKRv2m
}

sprite $image316 [148x99/16z] {
p5Y9SlCy48hEPS7l_xp_HDrgN7zsxlm9lIyD1eHMFTs83Ckdxq9rqblw8aRPI8dq-ZMKcfEIH1BbQqGAIYBPy_U85E--85OPd9J8-83wUP46wEu-M97yN2yK
36c2qW23bVUF69WwtPrJfK1GfBUFY3IL4IUfbO4e7n0fGFA0bUKFY1GG-UEN-uTY5I9Dq7jAfWqhYVzZhAhJrx0Sql5JiKhsLoGYx4ckZyHgAnAz5VkfxKgP
ITmOk8dL-qNodeThbeilhEUZPeVLUwUOjX7fDodTfSXoSMrZnJTECVcFI4IBSJTrXxDCJXeS_YeLiNghI6CYIGqzdIeNv5E5bJFjHLRQggsem1kcc0nkWpGa
0XHPgTOwDVoSRKMjyEefflaAXFSKd9oglxy3BHQV5uqOQOs8rJj4ejTJxkE9czJoC7042TtGKZG6jOCOZbyjKaXKpAelFqvrr6nQaC-1GXsDu1lVZcFr_7dB
Fh-jPNuEBdFZ0T5GnrAXlkgy3TYFDl9cY7GxV9P1WyS9Sy3g-LxmBIK0FJSEfugXd38MjNGkWpnIvGX6nwoUF6wqmmakdqwP57kfefb4T_h4nLWzoedQiXgS
a5TEbL-RmxN0WLJFzq8yqn_0vUZv7AJ5Q-uOFbGIEvJU42iDq7SSR90iHnaKI0Jfkw1U6Ii5Tc8Lmq1qPDXs1Exq-gDJp5o7_yQAiXf1YawwIeglY1Kb7R1o
Ec3bL3rSkmIwvOpNn2epb3gC5OBjPGmn1dq-7wjOvJXMlCw9HAoMAF7fMBa2Hx6YhjhMAYo7JaFN9zlA5qcw7AkBuA3Jq5F6mZg8YKzDCPMBDg3VZdcHI0Of
OjCeyfaf9fcshCXR6Q5x2nuEUWYHVMh_w72SiUWHLcCxvOvsdXSMvDJGytX8MUq71jgjiQh-2AkedMncOeixHMrSnYOhHsrrSoyqtHahkhVLbRJCppN7q_gF
L6HCCU-85RsbOcDxLweNGulB1WmeCNjnPpcIxubLz795BrYy30DHKjVFU7fkgsoIatjByPxZfl96LdiNYOeHfFZSvaLY9mcywxZfjyKAFOz42zsdK-wp3Ehw
8l7lAjHZiU8bgG2qL3cSgiCfBEff_8DXgESkSZM6SgFJdSTDkTuBSP5WEDLWZ8j4wbPDaZktmx5FA1xuaLXTdXTSI3D9ucywp4NADw0MSVNf_LDCkY5MS3bQ
6hfw-os3wexT279Pbh7c-CX7ffYCwsr50CCfv9ysBmN3DVeEj4nCJk-9LQGgOdNf8a7jKBexLetN3GH4AtCmk7GWwO1IzCBhOWMd0pt_Lwjvw3OCn32qUsZS
__zjrwK25CP228F2QBDVQ9x5a_Fmt3OICnCKcMBmrUD6WcHIsAgOpEr-9cB4TyPMuEs9YHZn4ROom_12C0rJ3sKudfduMGnlAvwfPZ5e2niuI5lDPTQOYWg_
fmTppSe9AkXssNfBWO987iMaj9L5HgiihSokHOfYKkwvxCBHgM3mQFkPD1DlgqBAy08gg1wEFO19j9NV68tf3weDsKiaO5AS5-mMK-xbLrKY4KpSB6PcygrJ
13oBPEBtN5LD6_V_VzCXxm4JMK_3dgkNvuKfwv_uBGEHW4bdgyWegYmqFn0fQoWljPK7bX-8vE_4X9WAntDhoGX3aNQzy1HyEAxFBgE7sw622VbNQYipwx-M
G95ovHoUv2a6YTOdXSI7ux5GfCpbh9buMv4YrN1jA6aJT33I7j8C9ROL42rx5X0HuTZGIAy272OSus6ZJztdm_4eqiepw__y1Gdijoam4XcExPeeoaZgUhvj
govI2jO_dM8C6edWi77Xs9ne96fR8LCIZKJQRinv8-bjfL__V8fHDn8-nPZlm_Qk-opULf7YHiAd67hzwstbeMyaV8gvV_r_0m
}

