sprite $image242 [272x194/16z] {
x9a7SlKW48FZlWNV_xX_mKApZqnwUq2KvZ0rOlK9auUlqxoBgXuB5uRMj2bqp0-_MaMLsgR1tPX5AH5HMOUEoXxCW0R6o5gv0UrZXcQHMpTCYaR4o7nKRfod
2JKSHhRRg6WwaufwmCWyNiVI3JzFWoUKxjEWKP5qkaZsH3nQietLiKAfs7dwzLr4XLe614T-yAG8ZAK8rcCUgcClS2YUqmKH4xKGcccaZlNyNVDlHeXWfU_k
dQge2EAHmM44Arpo58_mVNSifALZsRIAP-0r7k4xZuexQ5f2eXY8b89BiNkxxLY28puxL-XF1gi6Z7H-E4_fOaQ12C7g7bpIsBqTTspYzaU8n9LIFnunqj_X
N9tny3DTaM4y4bPKQzH2QryTQzX-7ixHj5hYOH6rSEbMIpyNODn-OwycO5JfJmrMAc2a9t0u1YBqAWOYlCAaQyLLAl7wh9EEvVOhuy4X84G8rYUrjjwnOeX7
xWqC1FmXMDNX3rUUrB4q7HMfUvL0uUa3gAqWyhJskTt3UHa88qImueX7H2scw6LjBOD3-LmYOSfxTIsePR9UfxN1ks9iFm9Wl1eaMADBM7b23NRl4g9Ilviv
1YBqAWO2_X2rRz0-jNLNR8zwLQl_BzIeVQksPWxdAVzqneC3aRm6AwzEtwEbWOuDcyruXAQD434XM2irZ97v2N1W8Am2gtgu6YHgtwzzQkPmhj6V_DsmGfU0
sWzflUUxOlDmwMKOYAfNAzH-MCTof-3WzYktFwym7W6rJnpE6yR8l3y2Xy8MXYI0jUfLJD5dQPlkwZsMlN7zYN_REzV5j9KVY0E6UAMHt_zn_rUx4PaYin71
bdFcsxcs_R6QKIoluBazFat45gib6bLjX4k5FtusLcyYXA9sqLn6ca0kRPMOyTnU_bZjvAmsK87ivOprkU8JmoVjp6Issjxcl4GBVnKdnmFhStjPQyxp6ZOm
3YVVMmhFxTry0OlL4erQDiAbugN-mrPww2KqNmXKBdlFDs71cu6uvjpCJHFStFuDkhwlEMUfmG69vlQfKjc-XUUCPN7H2C_juVW4AfAzR1miE2AFv_QaiZPo
bHNftOWHItduQSBxTNr3nhBOHdXk7wXSzfv78SL5mtFxhIG_O2CUHopzahr68xT8LLfuSUgpaPxcl4uBhn8fxaQOHdqRWKgNa81GeHi1cCYwZOGgdRr0Fn73
_eWCh-HnYAAvl8Z7OOZSNicZlsYEQIDmG7gDjNMeofC0UFK1QQpwsOjxQGv7VHl1Lsa6H_ti1KbpE8gty01Bo-B8Fmd0NwK97BMp5m-a2HwLRGG1a0IEiYqy
7aiJECfcBo9fWaTH6z4OY2PmbCpUgoAK9dYKRE4l3R4qWQEaZGpIHQIH3fUzjvwYQQJZsSXvjMWOnw5jv0OyIQJLrJNFWucqmXg7B0y6qafhl2HuiBGe3_4l
qYHuiBGY3PiGs4YA1reb-NUhXOhcj_7WXGkKlR-E1-XUCBNmEHxIQkd_D9HVWXoUuM57CjHvoAoqSC7PICp39Zi03tzbJSX4b6mauZ6P5UR1RmsxQw3kEeRF
thXU9flYCrAZ8_CB5_XYgC_U8UPXgpoq5P2WFRmNRFTxHyVpIhrOp6Ft1qJXRYlHlU3bJbUm5zwTZsbQirHfMi0uw5vmlD3vogzju_-YUYd6W-y5svTxmTvg
ENlvkRAjyTWba73X0YzqdfaeJy1vz61hFFRf8D6zO7ynL1ujT2ORET-UxDUnuuSSHX-_szhYh9ONEaiRs4QUuB5F8FXwBrZSlM0orhykT1OPpzt3cEMNs9Vy
lM2npokFmEUD-xk5pZ1Uw2mYO_S4qsqytOjed_TS7eyMEhFLpdyc4JdzHH_hF1fs08Jl1VEMKRU2mNKVizKsJmmG4UsUwRQsGo2jmJNdZ_PvkrEapchdWeE8
mBfdkcrNG3ulYhjSjVjxmMorlhAM_ukAg9brptGR0TdUECX4dbZeBFwZdMamZ_NizH6dRLlTBva5xVDMlpEkySLGLoeA8nva8nBpQ43RK7x9x7mWN690bxyp
C-4L36skD1M1pLgxkHtoQBffpIZbgl1yuNvdtF9tJ6SQhbG27a7sjh6rxUzOBajcUP-tQyx9QbrbBQMYSwa4F68R4SSZKJDvu-1ztXqBdUyorglxVIfrFBOv
8lTBPjNjytPRHkSYcGy4BtJs6UlL_HAYZkFVVif-WuAFtwtYbQ_RqF1beJDbR3-FqzdP2F6OI_HTqi-FtsyPvONEHWkTEMD97Qzbag5kG8IMuSby8Fn2PwM5
pfWNEYyPoyR1FDPjn1KCIzz0H9Vn4Y_3YnSwpqbB6SlgUosJ2kQTHFmmYUVsVg6pjzg54kwRSrY6XyzUQmp4asyl5hTLDBVdNEN1BMLiZeUtaN41mX8rwAkA
mmUv__XXiqFeWuNETrRBpRcQ9NXmzle3mXAy08d0JFqsEF_CCvZREnDnbKKPc-B1Di87X94a2aTX1bubSV_CKnyiT5OUtAvah1U-jxoDW914hOU9HsccIXjf
o4GUp-sncCXijPInWORlBInpGE8_MmyKqVdVZnPRkOTUzqaR36vTniPgvzFtzC50uZyazF5x0RASOX0BMYgvEhSt_LDPP1omK38ajfOHa4WY2im52kWYB7_J
WkKIR2FyyI_buQqMdB6n9BN_iG-8FmggYaMgshtOoYzq3hw8MK4P6scQsYcZWO3qAh6H9fxRprPBnX7IoF8uNRD0CekjrkVsz00ifE5u94v8ZaXwiPNntBwd
EVSuyZpoG59hdCAvFGsPOXh48m4aGGH84Gc-Y9aoDg91F1AwV2I0l6In5S_jgJaFSH2FdCupa3730vfOAjb02vsfEOzeC8zipCnAyCWLJMzppZIOHxvc-ea0
AIA-DhxHd4-azh8zzkEY18zSzaftnkPvnCrxFn4maCHksixcFEIHr_KRH43ABvNiCOwOHxveUf60bMZXAMCxQJ2FF16d3Xvv6qcKIiWZJyIhWqVEHWogYhxc
d6KVfq097_7gu94W0W3QbR4i7NxgU-lQ-1mK84M4XSJXk9r-JiF7oEhZ0UqaaYkLyVIpEZCI1eDOFK1ofIANqy_hVBcDRGmbo1F9bmgkfxTfk7sCWPg-XWWs
I9L4CwygxPj4z8UDevrFxzSWVooojVPiqUWpHFQMiVtxpVx_MyIwL68YUUEuRK22tiUR9hCdUKX499-nMvGAluz75y13wr0DWAXjcx5v6-4Bpp6Fu8YaZ0Da
75lQoDFrGaHAPkpwk_3MSJvSqMYvZCrlMsKWP2F9vdmuxKjNnRhuGFpvUwerCtOzU_k96AbCniOj_7UA1a2EHhkSzgf1EeXu7edc_7hQisxTDWAyy05ORHiX
7lMD8v-z018_nvRGq54qn2Ft0Ao-ZG3Ou5dn1Ytyy-el5PUnLNIH78-onf5luO-LiVdihPsnsIzCOFLaRC8uohJmH2ELiVMpzzbIeTrx1xMH9pCsGQDM2vze
pgjgq0GFpjW3seWPd2fdRBw5v_64lM38LBk5jxiTnfREsCejFE_yjkIGgNxssaGyYZmhVlrJUDw1RkKpDZy1d-XyP8PCzMs4wYMPiVLjn8X78cCFrSBRRyZO
ZgMIblyvjhvkn2FnhFXOBRnHnlvE3StnI6JimR9tvl6RCZRUJMk9Z3rY2sy-O__H83-SiVy6
}

sprite $image242 [136x97/16z] {
nPZ_VgD02CJLH861tFi_xdNNaAvIQVE9cypzui_lmGnR6PxHbKNcuTEQ2F8bldoKObm48lmbMQRFOSoLWaIvQ1u_Gt7XjHUgK73HzJF6M344KAWA4mkzsoQZ
ZyHGI6fB2Wc_roRNbO9rxGHBBI3qLfjCj5A01GOem2nMGDvfat5PZL4GP7NfTw4rn3IzAwlCq7i3f1Qw5e1oqJA-8wl4AimANHk0jX1UTNr3Lc5GF1BRH5V0
3z6b-n977O0y2c4fXGbngsNgbrKMXNnl395Qe4QNW-QnZp7MaNW3LF4em4BCKTS-MMLk6e17eIPy8BgSdTMA84rYIm6j1HCVQfdE7ObOioXAqKGtrpoUbrK5
C-0DW7uNmh_hUb9MOK2xAFYxu3-9ffUpAdnlWC4BZww1_wnbVCaOAmS9i7lZIo7yZEONibe4OURsZVV093ebmvvL5-uapHkVZkIy3Fj8N0fcRZeXoSOuByCJ
GNP29VbzOvoQOO54GTsmOIIzR18nMfiWZAINJLIT90udgADDr462WZMwsaGr8G6V99f-vqX8-3mjusySnoHygkQS8u0a61qph8tGbIFFi6w41ADlXiMs84Wu
kcPurXr9Wj7L9YFhLaWuUjfaqhsGSFIpoKM30Eud8RT9w4UKTACm25EpwdCES0yHmnxNjMMC7FOE3kBcMxbeZXpMdyFFRFwjN3CSE6xMboD-A-ypF9df5yQE
GquUIVXMzdFmFBOhDVP3pXr9ywtS5DiCZ-H6xSCXuLjPMDomrDfaOWl-aBCemhToKw161ylWkg8biS9n2WZLaG3X7Eo544CGNrxdE0S4mXBluOfx0H0B01iQ
ZMJMSh20NvF41fJoko0g57gxxPuyCNEEbq5yKHmVnfaPG5qQuIm4Mpd8-_e2X5-tiBc7wxqGAXGe595Z61SrvtYb9J3_VyV3k45DYAHIL8p8uHacTW7yjE8z
N9WtXt4tXbdB4Mt2n2x1izE9z_3TNPWUncWvecPlo3CaFaCnX7ju-yG9iuyauV0CUqCQ5CaXLYCKRHe0HLkW6OdhPidTZ1oaGVcvBrBJWCsTxwV3E60IHb8m
DBjCp0uIM8gagfQgmEw04zzuPgaZyQos63oaMXmaI1gAWpiVIJoCjrbjEQuvnrX14cMd97UCGRm8ngWGNmeS4IGboKv9maoRDpuQmp6S8_N8GYb7VkThdhZr
NGqKEKURceH4g_BXy3eIFXX9mv5hd8z9L5CIpt0oai2HwB8K4ZhWI4dgS5OA18g48oUXOmx5eKr44BDws-Wo_5NJJ4IBimIET3Y9COh-8M1a6YypEGjHu4X8
91YZfR3v2GX7kIu5fQhou0ya21IjQ1mIPV5PKq2hVcr9RWoPXgSKVwgtybU0m8u4wKZqEhoaIQpU1sm70n5eIv8ROnbUrXK_zqDQadmaF0vdQ57J8CYTvAIi
vefVvh4bvagoUfOkSaGIE49MpzMCdq1mvxWbMJrPuyyssN3SqgnsjObpTCXgck58acIrd-OudAvPpLTzd4kthEQhFk7u5xBQtIP-KEgTrNpLLu3wJ_UivXds
HzZUaDLyrPltetzMyrLlZJywP_NtLMz9LjzgavZLZzZ4i_fXBNWog_y1
}

