sprite $image194 [346x136/16z] {
xTtNZjjA383XwOL5x_-uMIqXmIQKuhKcLk5_skt1Xmc7aWtOtQpCKtFxPvNfg-3spaepB7ktSvQdMRQxlRFQDEVTY6mMJCNjd1LuXaMtTnPCSz7jd5MdkUPs
oF8XXFXL2C7dQOw3UoyhvjhwKm18LDqxMJwBwbQjHEz-akLJxIfTpS7jdh5ABNktUyOgbU1sprYbEi3MMANYtTuPgzIYsymAkVRtAcuZOstz_QftUsUiKdka
DTQ-OosOw9oFfNNLW5Dhh4UbDLQxndoiVM35dWP6bOrrLD7Tgw1O1-QDTL3L7h96bOnrLDvO1rMCTLJHM0TLZNLKqLW7LOrrLC5O1rMDTLJUM0ULZNLGpLX7
5Onr-3YmZx9i7FXKzsUrSH1pw-SetULxRTlPmu8Vy8cBFIpuc7SVhFR2AwJI-adBTbG7rGwAsi-VFzXDjJEg3LeVv4__XIhlYWI_mpbjhL-kzix3En9FJCtz
h11JgQrVjX--Q4AUrjnhUKLwrVpBgfscnp2-89fBwtSflZG0EazFCIJtvxmF8UKYe_HMfNyTYXLuqgmb_E5gYmhqRkMNnwh4FOVVSGxmlDxQ5KidddJSadTh
KKvdj_xrvVSo05HKrMo6_iyPh4yDfuqODqOh6Eq_RGO-v2wgEWOPhJe0JMibhHeBqBGPoMZT2XIj1KaF09wsmng5TJDGj0QRzOFLTcgqRiaYhBOMG5u704-_
Y_zbtmL0Ug8rs90gAbKrMjr6cx8hhS4sjG5ihrV_AeiejEQgDe3j9zTNP049_qnhi2HxmAkoVwGrM8OYgg_Bukze3PPHBgmVoXBTd1QsOR6bu7vQdsLvmXlJ
2Yo_S5-z8almG6kmrEI-saNsjhIWOTNE-eOiYIoXqCATORbdxwJzP7cw7wt08gjNWhlB4joD5kPmUINef26o04H2UozOhC7jNPrbQPKb5DexmMBnRa1nrWHU
P9dnBYi2VDVolgnwxG8KsHizCmXiSkCgykhxGVOMj33NenkO1o1KifTV4K1WWnjQ0Q75LVRoYwt0Dk_6vZl8F41SP2Uyz8eWiCKDJzO3QP45eAiEMnXyT-cT
5fNiPOSjgBjhR7sbfKKM-PAqe4Riw08ignVW8ZinN8yMDaRi-55B82so4rnjsCB691XU5bejguwjJO8tQNcHnGjD1FYlaq0_vH989B9gsDeas84M5jdfdD_x
0YRbAbNlFb6HWQ1aJtcF8H63XfMdWu_IwZDxlec0X4JQjGNtiRASJw7bbHTFHoiVH3-vzkm-MGB0bNQLPJWNhSWYWxX--i1AyO7sGVPijC3ohU1Z75WfT45K
ieXmgXNXMnRLIl3XV7rSR1b4bYOyx8e0JD1L9B9gX_rqvV4UMsL9JOJZhLXQbkN_jdYdEiOzzY1xL5eaVAO505u-5Qd17QdG1579uY5fPSKYzHMu6HkWHNUm
PDYYoF8Yotn8Mc1PiUP0GcO2wCaTBxtPYkn4dtwBW0ZRYm2Ii8A4icaTij14KQA3VAUEY75Rbk6f7Ru7Etn7qB8VtRu8aN5RzXokKkphHC07MS3FqPACL0b0
_gDbMpgogxx841TPjNsDt_-rBF8w6Q23h5ZBu1go3unVRKNsFz72DvmEvU5gEQe48YixbdekECsn5Td_HWlBIDMoiWTqM6M9YELMhT6TgTJ5LgunJJj-IzNU
wqmbOdmO-pLvTx9y1H1R8bWZWh6qB2Fr8NrR8KYdP9LYcss_SIMHbeRA4ZwegjjggPVetMbB7G2HlaAK_u1gZ2oIe2uHoMrrziEgpoq0Ig0Q8KmY2q-nm2wg
mLsYa1leXX43RCkoN5UjYEfbyZ6NrXJmZixgU2BggOC0hURWtKNpiJGOdNvcbPCgg9VEfx6wI8Z425AhELxVLFyu3Go9Y9cWp-VqDgRRFrG1UpQBpgJ1kzld
VKYvl2tSMwjv5jMabfVV1oYrlOnSNmCrvvXIoZcNh-g6vnw_ocNvBfIgWR8cs-fR3rMMo2hI7LO0AvHLzdi7yBkHMg4AgRjylm
}

sprite $image194 [173x68/16z] {
rTe7ZkCm38LXMrtlKVRzRxiWdELK3L9bvTyw_KD4k2_dj4fRtYRkyZRMlE_nNQn-s_46p5LpiczkSgXFfHw126vkAO1g0JNvwQKMW1Bcbrf0yVD0rwxKk74Q
QJLfD-G9f25NWmxGZf1gIEyYrH3EaJgJtfGxGHhla6eemwL5fVU5CB_KGbtdbrg8yqijb7UHQl1JIiVl6Rn9dzRweWr_vm1biZbGQEb9PzeUh3xcFdIUxO7p
CQcp0vrbQ9qFANUSGuTMbpNr5ptegrdHSGuSsZLaj6tVTtx_W5DaLkKWvjzRMXSAswwrweru64z0MiW_zphSTcsJuwJz42fnFB8_itgkAGfLAVF_Zz289uVm
UKJtImt9BPPIvx7Qoc-RIclykZa3fz0YBhho1hKn_H9a1Ys8TZWFgIt-rq2IE9aACQWjVXTBd6szI1koN_g1qa3YLAjDwRfOVUo9Mg1rfhI3RQTf0Mu_fhHR
LUp6axG0HQLNbfIvKOG4XbjPl4glpO5GRCDmBS2ir1jAGiXbS86nrhJSs5e5mF311N3FrJXF0XHi63Yu0E-xA1kK26veDhZpZQiLHRM29fGNQl69YdWVrRIA
tV0wBUL21OjRxYyg4Q9O8OaNONbO7xq85oYu3AxWHLfIO2_hGta80RQd3oxu2KkRriTQYsgfsATk523yZCrkUKf9jH35olEqi56LnYVU10yGsjxiCIrix24K
G6Dz7jL6GGUNk6UZ0FiVHVGD69OlUBGWKWWgzWujXFPVaae6e5WYA_NPkIe450lSgeK8lom-XQ08zEJgDKK8gTZZxvkm57p6WaJDAdrPQmH5XCIdhiII5Hf5
HA7H3te42r-vVxEXsP8eEaM_3huZJnBNHf56e9OKr3ay5uvRDFmR_N-pNE9uPkVQVQaTQqqnUBVEz-2ZSzxx02MQFIzJLrbnB7os0PqsLsfESVJI_mC
}

