sprite $image416 [113x84/16z] {
jPU9Skmg34JPGIqn__-vhn3ZInnZrHidwLhl4XzQq9BYVYeVKgwDiljx-QWe0W12Ytz82Z6NEaa0JG4r_0qk3LEBj0JAlsegbHeL2D2DqD8lrM-QKWEPQIEZ
hiyU1OYGbDT1be3YFqTf_TgtHv4NpnGeVO9AkMmV1OhUt-JPmWSHYLYe3IyAQ9w6fu0RPFsVTQsuUtvgNnHr5gaUHYJSylnuGv35aI4r-PE85D1UCPI6hwYk
4WK-ZuYdhG20fxd96jOmn4C_Y4Z6vcVuqC72IihuMtuU4K-ueoqO3IqU2vv7965FKrYVi0jFQ0ggpwwoOKyJr8XhvVWmE4cjrjg03o8ISJhxKKZau5nM8nk3
3A2L7BsVkQem8x8FFHPD664cVi-JLbCmMeTLrnLw5j5A2l1ksSHx7kBgmRMre0_1YiZ-Q92HQK3BxyT7P1iMaNdgM8ZxKBm0ZOY4y_dnTIO1PngroOlEXTou
zvcNUYcf5P42x5wsLcaL503L72QmX0g5aGhnqesDg_H49NeVSiDbI3GSCBGIlND5UNrO0nt2DCXa2kIcSjLv49rBbob8KFrxa5cK9xnensr7vLbYf_9vc9JU
ENW2pi16hPOKl5FvD2zmqLP17LOnzkCPubGfECyTW7IXrXRJ3uHNrl4WPSlBUZHM6F_JXSZTgLfqOK10DSrb5pJ4IbJvc6dSsfvNPwq1UnyWcS08ZivdmiYk
BrISVnD5MiavruRPTuwEjjj0adnT1xfiBA9FO0LtYbatYJeZ737hojBxgn-l_uxdVQeuJR9zJMK20xIz22Vdq5bRGWRQ4H7SZAG5R2noq8wnkPcMwBslLGPQ
cKOjUnqFPJZ7TYHTkzoa7JrddUrYi9-w6kFT7Qcte14ekvPzinASaxbghoav3FRphYOTjJRkd7IsrUDtfUiIWmLRrhPd0wX4hHKFu5fbrgJW4QeYlOzGb4eu
dHgum0Y2xNWUj9hyA6C3-j1kLykZONTkSHGrE5-mW6-jEdBBFZ1kzez9qwb2_0Qs2v11NGRMLUbZ23K0SpJpEMfp17lcxNnkRvfF91qa4vXs3KzGtTjc6lTO
KtiNN8RMqgYF37jUTQhOHkA8kAlKu4uv3fjfsEnDdpBqKyfZ1bO7bJCDamUbLUwT5I5T5Mzuw5seZ4IoyW0GRZhe2KQrAe_zLne8VQg2zWAeUHVHfNgNEfVe
OwEpJXlT7D39kpQ0lIuQBOFhhtQ2K1Sqxx86HKE9otXcHO5QcGEwwZpv_caSF6RS8_LXE-T7D9ftLK2LS9gvIGQhvZXWYoVVZN2VogkbxuKMnhFkx5thuyb6
mgcYCSvTu8ZRjhqlWuvL1fBxA7zphZO_-XrH8-1uCqj-hgUoU1k3hw90kwuG7hVblGjrV34vdwTBuH93237bIYmAs-ux6c2LUCU7G8PQSg5mxsYLcBFpTKLB
9Ve1BDxUO7KBQ211h4keNfhFU2NdYO3phuNtl7Moi80sSew3u0AOee_lgGLQCdbu6snk0UshL24Fe3JjTYZUDy3YNGt62z2-Ig4PWInp8GYf6BohGN8Re5tN
5mSNyK8QssIDNriFH9Hd64nRe1qHvjRbM0Yw2BK67CGkTtD01NS3PBiF37kHEnEeZCAkXG2qjCb4lWNQI69gmmlKA13Nac8QP6y1xQiKJ5vq4RsuG9PMLxE1
392fuF8BqNddZ9aAvZubVW4DatOgILxaFSaDIeRw2hqAyXGfTGmF4P4TQcbrDPKlR23DY7IfiH8pBTBXwWASePyAxQb9xfs_rqyk-jVLbX8zHTge1Np1dPNP
HZuWdO79VPElR0buWbf0TbT5iarE4kz8jcPNsod1G5eeMolq5vaHaIxFfAlCdKAx1pxLlK4x8i-1h-PCPPPVTXYSBLzPVX7u8eDbHEIvmsIGZ8Wyvi70M15v
mb8P1is8V4mIOQeb1GDXHkGZ5AZcwDtdof0Bq4GnMabFKDSfyZ_gbrDuZBf6n3Jrh7vsH7OeQkKdfko8NEeNW_ixXSRow54yLm9-ftx_0G
}

