sprite $image307 [320x204/16z] {
xDa7RaCn30DGJmtV_y15zyfosAg9oeSTR0AXYEzoT-gqKQv5mzpTUhaQqtkahUoYhlvEQjb1JVspZHga9lxPHWrIFP3UfJL8TVe1kpN8etlOB2TGDpzWlmOv
MHuXDSZ90jSWZovUWpowXzaeR-X0Ua0DSh80DSZ9ic5MJXP7sE1amLZdPC58vMJPnHgSvZ_71YSBnZed2qORZovcLgQ76Pmi6EkSB1XjFBeOgKmFCpXPCDPv
T37Qc1v6AYSBPdAoO6pmw0RKOChqM8DT_IPC7bsC3HvTZ7QcXv76oOAPbKSNOeFV2J3MELamqZXPCBFow49if3kwhC7fTqKR9mj6AYSBPloRoRBM2gZ1j9Db
FKfPWrM2qdkKhWRh34mltzVLQV7fvQd14PXUlZNOpSFYoxS6ctfOVFaUcPfujlWUsOYTBF5_tWGrMAVdYI--1eV5nhSysWn8BtD-RYF1qyPwa-MjlQa7MkzI
V5sjug7MfG7-Li2pngSN7-1wSkir63jP3WIu_cJaMB-Zexi-E14W71zUWrLtsh67f_Vem8ydqelTqx8kRyS7ykr3osqG2WAe2l3QiF__jocuoNwWD5cmsJab
lTsZ6HbRMQc7dWVqKdNNCsOmcUhlVVQqzD7p8zXEXy_QoSnKX9VUDrtVGW_JWS-7vbU_8aZpM7hrMdR5Ar6BtizKzyxAaK_a-yLtzTKJ1PBtkmZwTPp3VFPB
bjhtohDJHpr3o-zIuiMzL3v7JneIwkEgVQvUsyzKdrxYh2ngAkVartmTn9nUsy_Du4AdwMdhxA-DTDJRzoibvlLomzMJz5eYJrwT_Gne-db1YcVgbVp68lO3
L63VpvLOjFCxetlVgTgfkcq_BtYYdrTntzFtfhllDwBWVgUrevxtwovO1npXAGIlv_sQwLtYxdmA_AtVH-yIz-TJms_w8USCUqesGp_1WVMy7t89d1_ULE9z
dyvt3g-txyVv5ZW_9tZESQDaH3tljqX-fEA7eqkiBGbrwQKdXlt4Er_y-FZ8zy3rLm7OWOBjZcejJhp7nUSJxdxvuqVQVZhpWINsJkvxQyJZw7c_ZvAstqI0
lL7GwLM9E-WTvHVCLZbk1hsFqwiAzjUh--aJe5Ny0aqn7Zs3whFpCxgUrVRzuiOFvlrciZH5YUcT9QuRgGxrcgNkDzdTpypxGGKsHJL-MudRH0FgURybN_nW
LJ-W-8KKPiKx1Pi_OoWzxpUj-E47iwOVAB7HD4iY0s2d2ewcv_qcAYPDFrCW1QM5fsbvwmoEhrVtCzlpavK13SiKflNTCzY53_WtlwWDFzpyWW0IPLu1Ow23
ODUBpoU-F5AwvwU1AAa1e5bHSiAHRcGzsEjZGa7QVb1Aob4De4NmVi7XzTG_2JqdRVe172p5P0ODKL7IhSJzzUfFGY_a_JQXH24Pm8HDx2s2uvpLVBJzFmjN
hlZPuneCz8o7V7I9nx_uzf-43lhgfp4zPZ18mbE27YyuVdMteSdFuDQFYPF1K2BswaV9Zft1pwKdYkabYpxvAJ49HS8bykB7JEncyB_KGqtFeAz-8UUj7uYP
qqN9Pqwg-R2tfqU-RLXLpzBa_82SDtwM0XDpQlZbdy6dAR7YiEeQGFFa4mqvu-Pdn0Oj8zZso-0EWfs73x9CrSnK12z-GaI0n5Yvee6PyZMfmmps7RumDRCA
a77rOn8XXOjIieSVSvAXPr3VE7m-GN7lBtFYfDvFRUC7uUYFT9zVJwjwRlXSvcG_0a1JUjm_SjxwbVxU4mCmgg3XqE5Rfz_8J5e0JKpkzmzwzbis3y_C5xy1
Pr1npl3v6RGY22CAvIiwoRFVD0LpVbV1_xEwQPv-F-4cA5UtzEnNVgy4vzUjnFs7htOUXilDRvv__YHsVeC8Qe_Xc_pRWas_DQVIT7L-8vJOZXs-w71-VmQR
Vjb2QRevlpw2_OVF9wgPjVnorlNsvc5DKFNJLzS0NfpAtyoWzolXkLo2IUgNe7wruVDP-1LGDduPwOSV84b7AB4UEtpcXk-06In-IyotNFRFcAote1eEFkeU
axdCu9DVv7pF6l0pIeokCwZeFtpxHxgj7zkB7w0zPr0nrF2rPx3uQIBP-cMKR6OmvwtW5no-zf6k60bXwtSLD2Ax-Pqdg8Rkh_X-VmQL54KG6xya6RSPj9jV
TZCukfuOxC3Xgn_fZ2z4i9opNVm4elSII_4hUVyCshZ3vxFoHP3aoWAMMFnoDhOh5qdnyu9VRlXymak94tEy-EMiWi8bnU-UzvNuUtltWkCs30DXkE_OfAZx
txOFhv1fZ1siaZ6Wbg2Fy67rhqd4zhhmwIFTVlFn-woxNyHkSV8Z6KmGFkrU1Xcq3NvnP11-v10lrEDRgkV2fuzqo23y8i8SVaHmgPul21_TREqZWu5nfBtZ
Tta6hRKbw_dhCpZs1c5RetvNtykOBnzrhyzWs4xy-25UhwU7Jy-WlMKmscv_-_K9mKpXqpCOlldT3yyMNvX1y_yvV7opvSYWUzljy2E0GWQz9GWVoU1jVnFS
Xr-S_8ZWml2j_Eel7-aYXXy2E768yuHFp-3mmoK8vWmVp-3ct8yVOb5F_mdk-WkRBU8d20fwmY_HrcKGVbSSOcivmyStMzyd_EXcAt_u-FLbPD3X9nzYpni-
FjB1JnIq5Wj-WhiwWn0KC-ZH8tFuU0QvuFn8PySCSr7ucX2-1IETVeXjpD3fmtTz1lyG77hmInq-Fj8zB-ZZRz3XbpjyVAHx4J0EG9pVh7TyUWQv7mGZGVZa
tsozuETcvFv56NMJPP3xGV32d-1cp23t6uVOCuHFtsorze8V1FLVecNE8FTpWs3EEpvzfED-47msVEJe9iqWzyCXpXm-VQJZVZZ4USEdRxQu7mHT25_s3FPE
_23eaJLy-aZNF_RpY0_2HtwGaJk309pqqyENRAIRznEUFSYOmJXT4tx2g9isW_D-mY_H4cTmtYzX-FI7if_m4zylacsa6uBpVed3fs-svltqXwxIRRQONsiF
VXM-yuMHxXs_TgWw_2fy_3rRy0DO011-PDIj33xwuV_AoQ_2HpTRy6k1gvtyo4DNbK7uFJuz0ZyswbO6DtE7Nt_dwx0H5RwFHhhXrpe07_paKJV_PWj_V_ry
VYjyCvkjVlVhf_yVC-6h33R70Nwy_xjDXQyoQ8O3Z04kl7JcCdW7X5xvFRVPCelUm_qrlygWcxbx-GcRBJCpnQyogFfL1fjjzhfVRRPkdt-tKFMh5gf-rKBL
hree-jLSr_wfvS4l
}

sprite $image307 [160x102/16z] {
pPU7Sjmw34LLMUu5kV__jIy9XXhQHigAnfDqfgJQFYCSGjpfVs8EQPqUoxndv1oMX-fj6VadoFlyHBk4t43UdcQtDhi6dfNX4e7y2I0kZx4B6Tc071wHuMpi
dfJXl1ixa-7DX_Qlt9hXQkoUbE4QaTy1UN_4IdbIXlRGFYb3UsWVbQ6nkpb3krB6GDfkNIdtPsXNofCoj2lbIHdQbN9pXdQbU86uNh5InW72VD5A6Szmzbqf
_eRRtOVM_zfWxSw61vouro0k5wyK0BXeNy-xevr_XflQdTNpoz1_fG20sxN1VwN0-FbbQ5UAav__jM4PlGS0LX1mpd0Ui3kyO0m1O2p39MrEjnGSzDyQk_CP
haHQ70ujkbYNxGndk194cCSEhPrVTnctKo1hy_l5OJjjOOr32-_FKyuZKBgVeXakSUmR6hrHhmP4lleHSGrZRZ1p_fuWADQFvFWoXZcdmu9gzzaFHd3G4307
PjYk-u47GlYzBp1uB8oVbA9se90-XiCxHOnVAZ-Hmq-4mFax51hViwDOFxxABmZr4oGHukGZ0u13qSTEqRVQgzPFVYlocuOVXJuP-zWrFwgWaCrlYsk24EyR
cdU7Zrtps-ghgbthZrZpbiefG_CY6JwqrcyALOZk9ynfMxV8aqCU1zAmVdq_Tx-GaBObPn5ow16EZzRwgM0YqVroI92Ov2S3G_QpatujtS3k9q08p4dE6lhQ
yUCbUWuW2AsFHHW2HC7x6NeT2uNuybbkoGGfWg31elcb09EX4_YhNOES6gbIvvjYZ9H6YV6D8Rk7r_-J9gZCgHIAC0A18Webv5Sfm8ZXU7WDCA_J1rOK4SQK
iZI0W5ggHDyXWs-D5hlvL0cHd5Aa2DHFOgorr1YBgE65TWppP9W3HPWeYCrlsbXV8HQt32admhCi_N2etxPCkpu_5IHmSNYMDN_m2wc6QLwYD4XS7vxDiFl5
LvLjYe0nl3Gycw7wCUPQj3_aRWWCsOs7PraIrGzHQgaf5X5aVkCHKhuTdiqG4AAKLue5-cqefPG1GyYtmxFiQC-C8HMoNHwACNGBBvhm_fcX6YAa8bN80XJ5
P7XHU3P3OOQGmbgBYFgTUeHm3S-oPJKKIgbL_SuOWjxXMNRga4dfVcyE6U8VdcMEXo61KginT0vlE4EHvcU6F3nQ4Elam0Or98fY34V3upuv4IX0Flp-dY5u
GNWsGv7COh66buLdNtbYxCoGyMPus-JEXdyQWgLU6fwzUPM_3LbgBLU6PtVD7moR0rYgHtZ-6QeV2LmSdcNN3AqVXIe83eRddw7rwuRM3YQy2pAqVitGXfUN
wJAsdg7r8q67yFmohFMB7yiDuTcRLnSqVdU4PpEKmz3uEOJd-ShhVg3w8JSqlFi8597k1rAHmuxX3YkReVe1BAMedqDuhgyyzQFeg9kV_TnuQuOKjeyd1ENk
yEmhJ_tguMV2kvabKg1-Ej-IJ7ZtPqZMLnM28AS7icSf1FXCFyqG90drUoHBYZj8u_UufpWzcILZSk47
}

