sprite $image430 [100x70/16z] {
jPZlShqw24K31DYax_--TupD4Cr9nz-jvLl_iJmks3QMVogoQ2rSoj-LHej0H7Fw8qADTW0YWDRqBmYCJZWBqQA-JI1lWOv82lXT4QqDmYWWcj7x8h9Io_iY
yaCCBVA221iYid3HulpxZKX2bjeW0UrtMkI324GOby8UWT_FCVj7maWIcIcG5qNqPgJTGSL4SVhVqOGheNx_x6n9-eiv5Xo4IXNJd0QKnhQCbcohbkSYpaic
xPJUn-YR3i-ML_dWno8Q4CCYcP4T13xfBOmB-sHQq2aPBu-3OvuL2vT1S1bJXOEIybFB0n5OajLg_q3p8v0ya0kOyZDU7cq40BaEshY3dJXQflmdMkoMu30r
Dyuxc7y_kaxonHSjJnAyVJMNonq4ugkMeZowZZKVMdAEjoBMP1gZdD-cKbkpyxgy2gRqrOa2sJzAvsHAGXONZeYld9-A0CRcsoxrTOXOa-dc254BHS2rPWD2
bqSdRucNHSIIJ85K6T6i5EasI0P4BY6GDMcncR0car9U6xn_lx1wjDP6t_Rj3NbNuUu045z-8BvmHLmkodXicAlq_cHehRNlrSZLltfpLLKxgbdXvdT23fED
sq4T9IQb76G0Om4xOVNc1w1pqDZ3z49n7dCMo4NgT-SBL7Hk1LozNHXggkQEvc7cPlCLq8XqHDDfyk9WIc3ZBIvr4k1gY6YcQgQ34dFAzRdGqB45KcZZRJNQ
2MRe7G-Y9QKtdbAkjH6a9ANK9GGwOK64cv-4mJ3j5B_7CtlNUm_2385k8X5puUmt6AgddlnkxphMQqgA4pn2OAWwW7TCxpKp1iNC1gLtpIn5sDHo35CTZn8f
7hUfYbWPlRgMf5Z9Hnpgo9qSfYbQSIKWFZFCaf9fa_8Xf-0SfXH5o9P9M1XMwv1lkCaNxxyQzsH21yuCc2RXvjpKf92QTiegloAmF54o-Z0Fqy80Hh08IUa9
a9HPlk9JChNMPX4Udwes1E1knkJCTj3kMiv8eK_9XEzArUl7i8A6w2M52flPLlx-PBWd12Aeq3WfiHYRKZNz91-IoRGMR2MClvJf_mNH5a5CweK6PPRlgJfh
hteUp4nEHA3062J4ghh8_qo8BM5a-Eq-iuAi6AgRBPITY0rXEVBggSM9o7eMLX6vo7-iEXLkpdykRWIfZPa4lb0Uguxwqmi5AneHV9I7k-qe-4c4_dWUHnYH
1Ga9rQOrS5ByCM5_o9srr1g5IOg52bV0U-1u_9WRAO8V7ilT2XSBLcRME2c61wf3dhzU02bvc78jLC-C_QRW9u8-FvsZXuk7LYuq3ZFe55CysBc7XribSX8c
BZwfhbiHkNFF3-a1Ds9ccXW1UxfppxH4X0apCMR6uvrxhiMPPCj84RzxMLc5RSVOxzppwbe2s31InAzV7bypv0KH6oqheui8_ODtoB2ttrIl1tZOidEllzE7
lQLw_mI3lQLw_qOPDeVV-wK7nM8MyNvHb-7_AE8_
}

