sprite $image363 [210x248/16z] {
tDI7OUKm30HHaG14RFy5tpdRFy1HQVHgsDbfTI6VpiHIKjfq5dtesTocCsYptaMRy5mNqla1NHkT7T05V4wXIZ03IjNIy8EZvzHcNS3dvFeUfpvsBGqO43sd
5lgfQD37hkLnS-gftqc3FJRqoKD_4u379kVKXvOmEY0WP4wk9GNriMjfWC61SWfTmETagTKuzR5hQGS829sJQmjnW82OERMX2_JfjL01-kIUsbnG7xkMjj5Z
utCANS3dPAcTEJwWEgVb7nkVa-iuvaODgEOBFpO-fz0HZKOTN2qQzB5hwTI0QjaNUcpeariA8HO82Fda8PBH5mW8bLCV0ee57XkIa-a2FoSR_xkxior9RI08
myrQA2NU_t6zQfZ-fvi0EOSy9NDbp_uTPOH4wQAoMOSOnea9ifmx9gNvQu9WwZnEhnyEWwdZqTj-EiowZjCo7ABgw7_qvaDK7VsRNkCXukXr7QSgukZr7QT3
z3-9avL3r6sSwDbtY3gFa-LzXwZtqSlbRn2chaCJ1mwYFkD43qKznea1egZBqME03j4BaCv6ZmDNHHzRxj34WQDeDJCukegJ_HWuvCWIIBt4YGF7PgYc3aPF
UjXrdOoU7ZYsjmcJmVH6ZIr5kOyuSU2qg9iuiR6rADjrd2oNkcJl5I2AODAZPsKlbVSs0wT5UlJ--SCAnl0jF1IbZ4Ulqrv5mXGV82rYdBGeFauYG4A4qHEY
-6KouH4Yc8H8ck8zMiGuQP5bi_Z6rg9HaKoBBEfW1C-LQ55jRIP4PZX4X0wSdZfzK33PtZ15DhREaGaJl129zupm054asXeaYlHzHlp0KNHfIaRHcIdSezlx
UlGe4d4A7pYAk1IwoU4HSGfgR2sw5QUIpG9USJ5mBb6-QdApZ5KIfh36rgAh9iy5SoVY51SWBTBBn6RGSOeSE3uvYRRM8ZrwWHu-vda_qgCN6I0jOfoqI8zU
P80eaikaHTeKEN0KQPCMwJX53Xn5xUz7_ZZfWVEBT9meSjndY84B477qA299Zvw5UIZI9ehyznaCK8Y8SQB8VP_1CtQGYAJJPZ1Vd0oU216N0Y3lw5LFW4YO
ze85SOmU6ZjKnF4oomMBrDRaDC4JAE9IuFt85IUZ9rvqsWpjkvDkRB_8tABsE250xoDonCdX2H2rnwaN4KTFtxPt9BesvNtlJwHlszzBL20oKwJkHDTjRTs9
hflDkXFfnC3RY-YwhQq_qVLzHd-YwpZr9xgEKtUYwoRlJtHjwarq7IUpZaJDj-qTYEwFNibcpugI-KMDj-sbz2NI9BEoxxs9zEZjUtyYcleNiTdw5z7KlKYF
NlyYcleNCKxzYxXCVOkqgNyHQwz_4UFKYQYKfj6x5XMb3H69Zuh5RRiG-L-UKdPDdQLakVMsNOjWYXAHbAob8SnAaIAOuaGqjOnUqJaw0XeeOZEqcigkHVY5
aI8sWzsEKzalHS8KrGmYJWuHJV7DmD7pYnYd-6RWwFb5XjyGtmncDFb5qvI4AQGP42U_QFpuM0oZ5pTr2HJ4oIVw65xuNV7Dm3XvHVLR9XjC7b5MpG2aH_JF
CwCYGaIbW4AJNzGU9xyeLug8aql4E4LC7GGoJksY-g39dnEn6KISN28HfzXc8D8l-XZMXZXjpcOG59WSeiOctvvh1iR99sAS7297Cm3f5h79YqFaR0PgcqN3
ht4YwGaHA7hqh5qqsd8MfyXc4CXcKSvf-k0p9opIOysGRfaEqNvRbFFsQwZ-7RsmPZ0rW_PVHDdMWQHDBP8_HwJezMfO8yJ6PeO9SnVS3FoP1X5s8SH9p5ru
CpIAk0lXY_Z-OPQ8Pj3hbPf5mwVtYSzDFecvSuW4vSJKt7KsdyJfNsH0CsH7CyZzQBQC9X_g23_I3EPi1Yqw0hGoJWiMYQBjVPjXh05YdAxAOQi56T0Cllte
QFBbeXoseo3RHPhYQmOUuxPFSLekoc6hRxsFD8Cvcg4-0m8qh8TeELka3UlRAYBbWJF3bm2DsnrHdTBtQmO6ADNzI8lAYlF6UpN3M7SWxaTQb6Ukh_TjGiV9
jH_bVvvr428k4EBaQePpPAjeOe3g_vsBobQzU6PpDODyPRej6hwyIs0_EX7PsJV6hjRQ3CdH35B40DMapz-BgfIFZfDk1lCt0qNSZsg0XlL4LCHNnOecTpM3
MMeL3JL0ZDDtecqaGCGfk1aecjByJPpO3290uZgWeHaaibc409tjHsMv_yNorw8YIixV31C2zFr-L5uYG39EkXaey3U3s8zcY988aBWEKCrGAGtDuDoFs7K4
tOkJ5fch6VpxqT36uS4elXc-1cXu2L53d4mrWwRupWmC4FUZrI4wubJRFwuP423iHovHNUr3DCx6PhZz8klUZrw3KyIrh_-UD1opVKsXrhCVrLVprItYxLhP
ZsaEEJCWG8YJGyJHNR7xjbukE_UZEksY6PoFoUEglnaGe2DEJugEHJehEVCs0m9KunGbucAOjndMy_reIZ6YtzWCpBzZF_AAVcCpy9_F_IXK92dMr0puvoDE
IwX8KjWCWlJJPD_5AStFYTPlGAJePj3BX7y-tYoc1qJY0zZsPj0cViYpFhOVyRwAZwCPhkCqFhKVoViCLpCmJco39_SZbD3zqHCYkKo69XyU5Z5E-c3K9B9f
jfCuFIZIzncML3Fefopys2QlmtSYyuiQxZCSpL1U0zOVSOeHVOmYJgtDKDA8CnqEHX4YVP_HtWnvFgtJRPIY-3ZT4PLLrQcjGvoe9bcDtWtHDbpKgSr25DRa
kXd4JQg8an05nac9z4qgu_GQf2ZmO2H55nT1ZDEYH8478oMwSH74EBs4A2nE5B6ns-iqGCJt32MIZQsVLOZYugH5PHlQPbg8WkAaHJOvwXIYY3WbAT81qd4A
5EaaKwGRMvzEGaNyguKeZTuwfIW-JXJPv3sTn8kOP8hoyZlgbABG9gS80NBDTAY8VxLz4cK4gBE7IQwYkMC7urH50SCV6AUobwLt1fkyRCylq9y
}

sprite $image363 [105x124/16z] {
lTg7rkie40DWrnXhnl_xl-qjEfoGbHUpipRXzlg5aGovPGYkERs6Bwnf0v2MtiouxjZt7KXJLsSXivDwZVscba0dK_lQQMglp1GgpHqSXYCBs9wEQauGfqTK
hBGI9QhbkN1aQY8z5TMYJ8-eD9pw_2Ig-vNk4jMvqdsYcfCmxQZ66vKEKVlQ8PnOLF5AtwowXXDtugVI60ad7fLM-YQLvcWuVQAALpeULRpIyQh7mucVIl5A
nwFg5SwvwcDnPcMwHCNjYDGdAfQWCyMgmm1A7IcUIhkPVM5JQO7PDoXpGgGwpWzs77k6UaRrXpdoZdhE3txyXJQpdXGPGWcWqIKgXfCXc4XFKkR76-9pX2xp
mvifPJXJPdY2KKWbk7EAjyDHI2a_dDztEno5b28aL71g2YNxb22Gz2yqDOKa71sTKF6frP-Z0adLurFJZ9JAa51nHg6p1A-SIj5msi-HUVHKqd0Ypv6UIh6f
AQJbLaYf-DIu3583XJIgoDGKgZz7zGj4fnQ3z3cgNo3An256LI13XP9m0f2KssMBEZy99m8fPTUKJ2qEQUlgKGdJWgm1LQCoSUv3jRl-IGXLoeydeVC-Ua5d
2RsWCzKDEbFT8CE9YaFUXYft_RUU8_CEKF_dI2NqWvJg2dtjELAgAwHHAUGFddLwryllu_SWGvKwFVX-0_BAfiwZCv72ezl1JzQ6NAZeZW1oRMY3KD4oK07G
WiPnCpTpZq8oEw053SEyowR2PSXS2ng61KA5ov2vIuZhPQI2a6u8G0iQfcHsZWh_kGoP0rfGYIe0YL2YKiW8ZKkcLhXP02fba9rLeCdJD72Dcva781NoDmWT
PsZOtBSymkGMWLJ8twX1Z6SbD9bvl0pArJAQ6Sy-CoV_bE0rw793LncDcpcZsiq-e5KeBOC8u5Sg48FPnc5Axkimp9_30rz0impQFOKqendxNzQiG7oK_M9q
bJBKCxA_6OqpzvUtvCSFXdmKtYc3PkJEZ3B4nTBdep1KXdf6BsPawnlouzZfSabKjJAWKOPXXkEFiLWgExAbC3b7XLG0yZS26Vdh7uf4fMNGg9ePZJcZWryx
hP5HnSkW6UtlZ9RwVzSJA5G63WLBoGYw7urAot3YsXar8HwBnyzhXbVQVVaSZSne8t0DiUfO2Dg_jXjoJKX60pDQ5BhScjkRaku95Cn8ro8dwtKPE2x9AB0Z
hdOPtCp1grKo2kte79L2bBWL5ZUGaPvAKWQ1AF6dyjWEPAIdaaPL8DsLyNz913FI2mJLCl0om3p3tr65eM7QJACIY8olkNECgWA5erAeNA7ZLg8AGpoL2YMZ
aokKByiPLGZI2yJqlRUVhz25KIt_2zBtIWNALwWsoCpJBb0WAeNya2jK6YHGE2f2kT9NBoiEwNkbl2DR6ozBe71KX5ZfHeEYa7QA42lTMF9Jub6P_sp35zQO
c4ve_GO
}

