sprite $image287 [269x187/16z] {
xDN70SCm34DHaYe4ultdJM-krnJuRM1B-h0lvGtLhdOL93FCTf6ywMxYlFEbcRJ64HIJLS2f3DbOZ0YdmnjNe0hEwOXmEW9yXuHiEhnp92yuqLnoJlC6Wkae
cF-AjTyHMdEQOvZDh4uia3ESQFQdwjgl03RUIj6AnM4OkF5MCYJcz8h35NNIqKxTcecIupWIGqksR6OYrV__kxjzANeHoobKsWEt-UAUUruG02rfcf0wYNbr
vBxYtPjLeFu0GdMiEwTPn3zMnxPyMKnq23VqLHCYPsLVTKwdG9ZP9Sk2MNLcjrlg2M52g8xboeBHPtRzXEZLiSASHWbOgyEVaCR1uAmCmyowvbIj37zr-CkY
hoFVjpecSqfaFKl7RNl3ic3GhmvYVuU4i8frgqEVqpbPQyoiNXQw3lyDtJ-dhgpiRp2dcevrRkYRa90rgqEVKvrSOsRrELryPlKvPPQxeUjpkdvrw7EgWwwD
8S-iVquDMG6Pbwl3_w55dsWSYqbMBcypftDIL67voiLV5Wo-bX333TqmfxtgYC4eC-kVKqDM9kQ5cNKbnAO3Gq2j3l_Tkqz0BmjXPYrpwjEHGy1M7RjBnKaA
AcpLuIyB9YaXEadibZarP8LKUAf3VvHb9CYyeJeC2N4XF4Dt_ZhrOxYX6-RKh-DYc5C__PbTjYnCD_Jj3Sh2ChFwdFhnp-mUuh5OlpfuJcEi88DHvtGz5oZa
dm2bkBYnmz4allDtYCnY5rKbpIdHEf7u7rvyk0B5AhuZb0NJ5z4GObHHGvlJleiW4qGCFrdekDZZGHU9JydNbyLlRa92sYu24l7wX7pd-7ONvhIxgGcHVE6S
dYgERtCPjtpGHG0wyUg4_5S5o-0vJUPvBlmsuXCL98FAmkM2RVZBuXTteImw8S6N-TVdDDd5MHOaW-PqGgCxTV9bPJ6LSHsPfeF1l2WXB8CJOcWCuz4GL90C
cbD3Iamoig2uO1ayfqpqPEZu4y8oU4xd38CCimgMGMMnaWm8SqeoQ4vRAM7GmZcdKndNI84md0npGfZzut9FYI7WNXDT1KZ5_sM_fCZu2cWGXZcbiY3sAz2I
yVoZuIoBkGn0bQ5ZFHXwMIWoy7GPqMWC-vmo-nRGT3HogrDfk7iBCaP1qX7ZQwJ3XVueIs57LK7H4PtqYgHXJWNs-e5YezVhdrC8mwCiKOQe0yqFM5KL_Zbb
wbgbwcX-bOl2b2g4OKubZh5zb6vZz0YSlKGYa8Ov5SdlNp5LgJemsaG2e7zJnZ3CgKZj7z-fKdKyUg8ZudVWmlDcIENu_JLNbQm3mu6_BEAx2fBnAsH7pMmW
XW5xMLm_JaZ6TrFJmu5Xm3odjzF4HCOiAyXXm3oddygOwK3yjIeQ2Jc-pwaWOsfZ633EgI9ZgWDOfIoEEucOofZhG2upfw8Cimt_dEASKqd6N4VbEdEgos0T
hxSHzTmvrMNCTLI-qPmoDAUoZBaDl6PEy_64K5bqPB0E81OeYwuCre7A1UQqAuEVeQFmNdDwy9pgCjo7mt_trcL8EXvwiEr_bAMG4ncQZdoBik0vdRDZ8aEo
KUbJqRzxwsntGOP91wimp2bpYOaCKGV2fg9_zzQvfY33g2DHUFhTM-U6YGnfPb6LaW_z3MqQvdJADXGPynjwFST799burgEihrV7yQt6lQgdG_0Xd8b2FaD5
J1AYiu_lCnJLqN7wGFzzVPt_BCESQcpPjd4A8IE21qh7GyU2vjHYWtLmzIC_KHAHYI8HdZdLsQ84adMG4E3yyvaPVv2PV_vP966PKnsbHSSuTP0DSeBfYKh2
EgSwLmWonW0VZZx-ETNPXY9Zn1Dr-ETKPuSWWxBIqs6Sqpvt23B6oCTj-7wTzhaCGSPpi-AVKvrh2ZB6YETafV-XXOaR11cJwh0S2qpcrBehWw2i-ERKooK5
6PtgCBmPCiti88Ii6ERKmNPNPF3CmZEdVYuXo12gmp6d_gmCebqTm3FU3Fcp0a66K1rwMUXpwcSBGOPmGpSyod9mJP8XPSKqftvk46HeEbftRs5EZMo3P6ZL
ONoKvS_AOFIPxS_fXuG_AuDGiz9_s1lgdFgpWg4Gb1NBhrC_byX1ADNXkNlxsJCRXyDsz_PVIKEmGQ_VR6-6_5c1AkFKiS2SFf0LUfFsm7UB2sIb259Xc5CZ
Mo046RsFdD-FQqALuPzJFpUaACC_ftwsWT1b-1zb-RCIkWp_dFgpeilmpwa_A_c9Z4DwbBK6rq0y9iCmfpvsG9NXVzZhvuxKPVZdrF_sBJeoN7Fgpqh8Clnp
wiyAT1d-3otyMKbHXdzE_Lo146JGd2xB3GYM8VmwNPHjL0R9M7vEzOydZ_NdLFzuybY_BFIF9u-bvrJ_U99b27EwQbPO1fOj2_tZoMFzETK_dZoqHrdhiwFg
q1_shf-Le_6XnRfP-NlBuZy
}

sprite $image287 [135x94/16z] {
nPVjLkiu34MJDZr7aiEy_-FEb7YXYiO8Bmtj_dCltnjBsw6BK-Ocs_9shc9glBnNOeMPgffXVQF5JKqFJ6_ld8TZSds7n8M7X93IHLw_8YlK3Wa0w2AcBrwH
hIy50P2WYsolNmeXG6qc0C0NhyXAytc8jV_GnmDvpOhSr2LehHD4zBR-zLBqUV2OXsC2q2UplIPIWD8YTkohn_k2I2dMdDF9OFthI0bfWS6A_6cal1DEOxWY
rp-Bb0V0I8G0alkz7Yc_y59UiI8UwI7XO2WYoVrUYvHECfdaVgz5UW8uRWQ3-xqMwHFfYd1mlnSY7GFmV3824kNx_H8ZZUGhOaJ_O2NUzJJIR3Bn6kk4U2kH
vY2AA447Bd8hH_hxoJpBXtZhaUOYFez8kD-haUOhOeCJd5iHZnJWF42NI4IsGgHLueeK8gqJxlT2f6MIUBD8yKNPGmzC1v4EBG2Gyianueg4MP_BFefKvLo2
elP5OOC1wH9ghSbPf6CBTWV7UvuCnLoYxJo9T6mXTe8IXNcqkyM7FKLwGAGM3Z4fSSp3BJuqHFg5p5YOJYz5bFZKy4WTFWFQ4BVEmDCyFj4OQKSmfw7WVAHt
YSEYQ_XI99jHq1ZEesjuf0vPqCWYTGb7LuyqpAGub3pImwAZlfg91g4sWfYFDA0m-wq6iyEONmhNQ6R9RYGUJOaqqXybzWzjxUwHbUBZVKQ0-QM86lzeQrqa
qV3VgqK9eZ2Fuom-vD8EeaSVTlQaLo61ieHTbwLreWZ14G3W_vsxkVSJYVssB5tZhlaucMptSQSIgSDr2HhxuufCFAnAyz3BiaIDkAf652MegKJRkaJGS962
HngfUs1neeQBMC43_5Maoq2ZC-5HYdIe4GyakH-BaMOQBcBAMH6No2ADw1uqucHiJWHJaKPkjhl6YOZa8dxFsqoaaPLjTutWuIUIgU2Gc8ZqcOlSDTjOn9GS
gm3zWQTpaJwpyNBR1oAgwe_J3iF_HNjRUQGv9nuURrTH4JuYechku1B3I7Eszbt4n4MwIiGL4WkFDEUYtpmCL1T9oIFDyNeT1K0xH0eI7ccEr_keSJmYaWCf
HFfJlK63J2PJYtJCPdlG88OYXKXpLhJzKMCmcNGUUQJvP8862Ngy0VlTaxGm6TSOh4WUQHsqFMZGuvs8jCug1lU8Ap8HQPqh9OZ4oTWuqhWKTMx2xoBI3f5I
fFFn2l6iqPfDFKdhNCKdung5I8kJSOr2fEN9OA0n5MbzCaJKA4HQO5C1WaOXqj9ab81h52AjSH4bNCCbscoazScuHYNI-cJKDLuGQVP7ubwBjCxMNtpljKZh
uFF5zoiYpLz7UAHlv6h_wpp-1G
}

