sprite $image19 [126x306/16z] {
nDC7ZYKX48DXSYYu_tbNx2HFg0bMjvyly0b-LU1MHWsFMkvppf4VOiSsdzQJtgxpRIrgyJ8cRXIXdVhyk965mN6GN_tfk7fx_kpOa5yGtFEJuihyjQW8xg_U
O2V7LkIFpQC4r-S4b-JFOn8hYYlpDxBWoeZyn9LHgr7mwSJr4LUcor_dLMj9S6L4VY8ubryGdBW-uigejQW8xgyAFfsyFlxA-Fp-folpfpv5AqJm6_CdWUdd
Byl4VeseBnFxew2-vCyV6NMztoBgUh-Y_e3y6NNzytkgeCjz0rtjszwWQ_FRsg2BdtziqAM-xGswrhUrGHVpnmPTugEDkiZ7uAZxlDqK77NLyy46NUCRgA0h
_6DpEkRdWxFwyQyDZlhTlW57wEZpdyxhF0ysgVE-WUJhHlgyZNfkzblUsE2-da8Q5p__sB_MGyZpGjySpj7FAf6V-7H73x6lA_8Vcz335VbjRqu_AyRvQFDw
Y8toCJYly_anEAypruUVpkkfzSJaHvlNfzc8H7vRczSRwBF--Vh0PlGrovFOpApzFV_czQUDTBmuRERmjce2lVM-hCV3b-XSttrwgGUn6d2G_sOzZZLjhVcF
b_l0THG6mW3yJ_VOzx_l2WWM14XMYlsYjlLzybIA5BdpDMVflkaW8_TIM-4xt-fS7O2JPslLwOQdcAx3rklBgZSyfCpMeSubivNxzDV9Ea1gIo76RVYzJjPP
kRRwb7ukitL8qQYrvNtwSx8EmDYoFNRV5DqsdGWmH6rVqZz7ZoGOg5IjpyDtlAwRhfMmccHkJyDNSjBPDNPTL-Cn_LEgpclNuItAy_2TeKjs7M2eU5xIpzJJ
FrZtemueHRPp-hdKLpOqH-jQJxeHP_DJzrcjDVRk6wnBlEa0auMtvYzVQwr9UFbbKjLr7MGIXolVFEZmeJhVweYMVVXoIS4uNGuw4Uvq25ifjQT_aXvbr-Ma
0yfhzzjCtIezwRHTUgNCq_kaPRteiA2isGhFqgD-q06eMH--WtH1r_MRpkj-gJPCronTzxBezAWR9CrhRIc3TF4yJnjAVjO1c7XPkt-83kwwh6UtBpf5NSBl
GColkgjEfLfjjMhvNUTprUbt7I2usv0Dcz5r2C4ew4R7IGTSSeGkSQWwNuGYNtGpmE4j1qJU_R9Xl-XU6GumwO38vw7cyJ-wb5K7VjV5IjSZ5q6_wP4qJ0ST
QXumgdod4xgkzNLs6xjXOn6OhhfHSNGzw7SzRgRD9jpgsVMeCtJHLQ0x7HvTb-GPUXJ0A6yZdwNhwoeShOlO6dcxq-7PTQiC7Q_3dlCUtdKocg6RtEXwgJeH
aFsejwj-M_EoHTxYMFCpTCr7dV9KypFqA8-HH-InveVgrcl-KOSSQtw6hl6eKsZN9MYOpjprgFzLyv73TCzclUeUz5FDAtHWv4kh_DAzd7G_w9HTXm-ClBRc
3bhrUjPnM_FmaVrkgM6jG8JUgkwWa--Jri4nUDei0H01dlKiw3fXh4xPgdxIuLr798tL8Pbc9UNvxDvr7JzjY4IpLNhIItRTOygazTPqq-LT1rdN9-quAYr2
Yjtf_QhUeMMA3WXy2S1dFNAI3XZLblSwlNIhF4s7jUggJizwq3mTekorbKSzAYRg06kq9a-wZCixl-lajBqK3N_GYJ1Fhm5MSF2JNiey7H5W_bppD4tdD7pf
k9WO-OohhkUQdwYxVT5rTCrJqAvpzJkT3cVV8--3T0JlEigDRbPBrxtIO9qEUTSRNLkBNTVHPwT2NQz-erEsAY-zv60TpYzTeNRL7LohkIVtVlzHBxUHLrBS
wI0cprR90SPOdV9ppVlsIslD7C0mNL81Xz9TpHkTTPHM2eM2T9HUrhHYrxberyFUT2Zv4e1HEhFro5zhdjvrmAcsP1rQTT9rN2OjdtLOQwvYF-crFEouslN5
9Q6aimurYcnbW2uXPntfNIyA4WZUT83CMzC1UfPTv_w4XWKcC3231RZJkRPIVjSzTfsE_MuE0_2eWul6xthryzdXlf6xpkLTxxyS7tamTRsiaNUwwZ96PzAk
7sjU20QLfyZh81quwxJLl7_CEy_HUys3TvtzZ_JpZbCuWOKA_PsEM7LQzD2_YBmTTCwL38F-KTwrwtt7iUuwoL_gOJtlgyv9kov1iBcHhs-p3eokLuNEhRgo
wYut_Kv5O7DrueLKlz6jokn-Jzd86vshJjQf-gCEvjbwMDUdzxkMGfT9-sTwArbEEl8lzIoDZpgNDRtpzVsJmI6dghlNPR3U_LBvK7NoeBEErOlMbVSQlUgU
T1OTF6q2v9jVWrMto3_gd3fO1pXUuS_gC10_wfOyN8Tghdo9IYlvf4lLyRgvMbtzvWvvrg4oL4-bHNUNsDEVIHSz-Yz7wRcTNMJLtUJLWbRz3_IwwI1bSGlp
L_fhIsEYa-vpz6t6Agil7_Kz_PdoLxgfA9kRcqkqNlxpzK805bM5tTpTNjrNctxLurVTHO5L5MLPmz-xhqZHMNfkEaY5tL--XeNrz5UhmZn5BptlP2nhqbML
pPVFg_kobkaw5bKtjGT2Sm-_sLpTV2jwNyjl2qHFVoqbPkdLzqbhmklCCLLwXNzBVut6a_J2lcAdebVXxO-qxDrFpYTTnkY0H2zw9LtFVqr_HkMZpgDqm7pF
TPyvw_0rjv1N-gEMAMS7e6viUzHb3yJsHttuLXUHbou3TLBbK5ujtquThq2STczc-dWT8clwPOsrQYzwwzsN6--D1-lzOxulsdxgzzrRMpXuc1u77Uv6vdQQ
EQBx7_NqPw4Pkc5D_wgfacx3psJ_eznyovYZ0nfRqHzMpllkhQtg79rCp5bVuR-EeNttUgICro46wjtVqt_JVLvfhAu0Y03os37jHVy-VBFPS9qO00aqM6AR
EKfFkxUErW5PzNFu-UtIXttpn-lOT37P_UlkPN2PghCn9FPMxpDd2mG3q9oeWm2eRyFNteRleWC-NgUNlW9An_JlOqWKwuVgD1r4Ymv8wE7KU_TFqh7hmAQR
QeYSYvv9-MzqCT3xxcM0bQRhvztRPmu3WDZFUg6FDRyWM7_1FVsgJ000_bsNHL1wri6lNrZqcQFZQbw5HBz4NW4sxhkNLKRf85N-hfCAs6sVjCg_wMtN0LRw
gc-V4iAB3eZA81qGwHlsGTzAmw31mjklsoWTfBnXygZpgeF3g5VT81rWDM0b-3do1gYnwt0T40MfVjFP00aPhWCgd_N-2t7dt_Loa8q0KjbqkQ1xMp00C8l7
3rKNcwxy0agjXRRkMtGmlUcy_q9MNKtghtf0b5QWrfgR9hQttdFacTcGl-l0DcUZVs_X6dvH-gm3OtI8Ci1PgmBTjx_IpHQVNN3i_fVEzAxJC3rvqTrD56yV
qGtbYMTd9TZhZlMD9tK2X03udKu3QXvok4z_yraPQbFrqpDoklWYytG701FRNWo5wYNz-j9vqjbXf_lqQ_fvqK4yNbTUT3y_8x-4tm6I6P5d9NsfXplMI_SH
Aq_9kyZDVVeb_Jf9nzl3gOVkttKPhBy_dBAdxgE-OMM8dhBgvwBVmt-JVjrWwAgl-0zwQuNGRuyNr7pl_jlk4uWDr5lp_a2S-QLg_oE--ZfKRrLxqL-U3Tvs
tr2zjNB0Ji_8tVL-zxBGC7rTjMxlCwUFeTsbo220r5byeDxgwT7m-HcvxiFNzei_Lj6HUckfbvbpIl_vUmj5UQZUMjbcJlHJ7xjF0L1s7R31UcjnBVhJxfKy
NFWErdlwUz6_TJ-121FrrbBEBuQyzq4VlfFqdluU_klkdQstwfUNqQ9z8F08lRPFlh5RLo-xztUTunFVygxefNV_h_hNBzYFVkhty3DKVjO1_Hn-FyqSxzt7
02dphph8F_fvshssZo460BRse_xz2_QB75z6-x7ekVwkVqz_Bxh36Fgrvls_ls2_NbuCiUX07VIb-_HKzC4WbPzqFUhVqy_Yrgyu603zA-qi32K4WYWsAtZ_
zNwNyp2R5732usLmUX_-zhKatw-mNvuNh64U7BYtk20RlpFjCSK5cVY_LtfbsgN4Snh7_q6DDcRQhSPBMBxZfjrx02ZVlV-QDdb1wp77AN3sWcaXS83bcpRj
rW98jQzallteaQJC8D_ptpwNoCBo1TD2om3nSXlGgeh_4jQg0ELhMkRZXvOfMBxSil3aNsu3MXNnyxUlDJmiNzCo7p-qJC6prxJCjyzerSSF6o-0bIzjl31c
zfgM-VXbo-Ji5IqpbE_uJSkyV4tBVFogPLw-eorx1m
}

sprite $image19 [63x153/16z] {
fTc7iXix20PWVa0DoU__klSQUuysp74aEQIN3r6KzKoMFWPo5Vewj5fhXR_3NApz7zOIpZ5oS-q9z5GdnrTOaHCirV7DMyPHqp6ifIsCg-uOjhD4lU4OjbeY
XwQZRnaxovgnFu8KyVu8vhBMtWelbhNi08TDnmIwMDRs2F8PZlUuzYCVbrXw_pP1rUVfJ_zbWiBElowWE_yoWOs7yvdW33_6v6SZi3uUOqn-Le3ZoSyIUDsJ
doMmxdZo0p_hdZo6RMBd-mbcqvERbD-yVMewSf2qiIvWrXqvKR9L0hlZo0dbymXYqv5xSFqyWbXtv5A5I3-C8E2mk08Y7PK-ZI3K7NbhYIWhVHf1495Bwqrk
7pWZyiTdtdfdaj8hqnLguumpbsePbqVkuuWJSHwcjq-zKmx9TXz16oTS59pD2XpF9MvoBim4jPufZ62FvoTdpQtTHb3FJcTYQVPQOZOcadR8GLBy7kVXdw5j
ZoikpfnhIqJgOwnRNFAJmpaHrt4jiHuMFsy1l_du6xVCaR_oDSlOu8aPJovous12wfQSx-mzdkuTj6OBRaMUHY4IE0F9rbnzsOYd8oK6bR7W2fyKH09NdNov
kFlfad7nkik50q-9QPSd2FxaB89TBWbCWQiiJdzCNZXoQDhc3YQNRMvPdo1EVf_tX7yfNhGM1Y9dsHsTckgTUokikZywgtUkpjCsPycfCkQTF-H4qehWuZZc
J5nCQVAztl7cgk2IRrpuY1VlVVAKDZcSvydFYbSunyLLZxX4tZEy-0CkyiDPKYxClEJMJN4_dQz1McRiy2JGoGNNwAJQ1kz-vBrtWNFcaWh_bNUxFYATCpyj
tfo8MrloeYykYPaPn3mvPCaJlxcyRoec9rhnUMapmkd7d23y3rmOz7tn8ARh2kiPzz69qFjNAHzoJRXzk8liSLE4uebEUhSg_y9xRqMTyvrZZpTjmqmvS4rR
V3H2iM4jCNt1UmEbLBj_K5zS3ee7QqwvFHDClZswIgIIdWb6h_buyesHiYSerdiH_CdROdIL-6b5SqwrZrPEk1VlLkKzWfhbW9jmSllg8DleLR3D6x6cjrNr
4GnhYcrEuapV8_1RqB9kSm2IKhwFOFIMiCUV0RtijKI_1TkSAVsCG7m4lVUig5kSc1YQBkiT-3-4RGvYrZc2zptkVO_xDv6hWwoIXR8TSH3hl0L2n4VSPv3q
we01E-G0y4gGb21BpeGRX-VYv1qGRPpEof6JYgQDuhjVMeQp6oSILI781YU2CE7EGGnL4BOu4LWlFhSemd_bzZ_tiWiJGmW4t3WqhJc3T5GY2FZ6lIHkOy69
b97LEr3NauEMf_k3sXLv1S09VpseVnA0XSyulHzpT2LW9XmKVtrACBs21Rn_EkPZ3Zy929kdWzBF8pBBBG7ly6v9voFoFW8btk2zjtHrxrNmbG3CiB7alHTD
R_kpnDn0ej9sUBUioUrxYNZ_Rw5i5E_HvWXyYKW--otkKPFRkSHj_c44IyxrpeTbpNC4obZmy4h1Ht2DR_sii_1A8OnWMVnlhnIi-19rLVpZKNz_fV0QWKhO
Uz0ZqwTN2iqx20_gS7HubTt_YAf9mNpnY9jG28uZcCL7t1Fz4k7LcEbLV6YwW7wBkCHHrNcecp_W-5R58s0J-cjm_SmV8pIz7i7zwDZqnWYscfuHx_65ksx9
E89vGmzYtcC_kZATXozniQp524QueMSXLa4Vupy
}

