sprite $image239 [240x181/16z] {
vDU5SOKn30HXoxQe_uB3d5oOtlvV3RhPqVXDbZN7SNXV21l7iAgl-JY0cNsdre2pw4To3hBTpuJnX_lO7aYMBTHYDaXBOvwovim6QRMO3T9oCXkaXJ67gsrM
W-0pzlw4DEOfQyvia5QRqo1actP_MHXpk9e36iHha_StoiayPSsX3T8siq5QJMQ3j33cS3LdDaYh1MtG_s_JhluTOSm6QPlP8AqMiq5Q6BD1cZCRfDMYDaYt
YTaWBOpP86qp6wJLOZP82sCsI7DcWxJQq0RzVfjM_rDXp0PfpcoGLelP82sDsI3DeGtIDhD1Miq_-eF-VvjshpSRH9hnUNVcWHox3iH0Rf940FRU_xGlvmJM
V5f_E7s3BX7LOo_9unfeqAfjuaVsG8CMFJ7vcOTfq29itbVz3fBzPXgq27VlszhEJpCs3IhH9egNrZe_Wcueq2QIlBU3h6Jy-AUlNdedZN6LDf6an1_eXhNR
nDyeCsFZMy_uRdshpVXgVElD-E9zYxN9-fPk4rdVUB-E-DOyCMcerYOQgisOXcfjeg5QcsWePdoZePOnG8wpl2r5GwLFJCduLZA6P7mh6KColgM4AUDRoXYI
yQra3CdwUXPgaF4jzOaf6TzAnf2CRoLZICQtr8mfuni2YtnSxzlxOiRULkBNt_T_vzXN_SQW_kNRsiO_8QufJFqT_lZx_k_qkrOpXlu5IV7U3lw5Bb8B6KDo
lfG0_eDzdLTD6NY7NUhEHOGf2rlRQD0QDOOqvDikEmTHxrcDGOtwjdRhexx70HeIF6NdszeTexv7HxfF38t2zfLjpFSZoHurf81lknvZlXz18cCgvjlQ3QE-
tXW9R9rlQm-C-EPvr931-BRBxdmJ6OEA-txb-WyDVHLECMDdwtrzcqHZV9emvF6-lat2aU1HGvhZwsUi_zyOr5pVrcupPvnWkCRNplW7tPDFJCWGz6sNZ3C6
DT_tAzSZMvieJV4zOyOuuIbxNySZpOmXpVLDtIPG4ttJpvZIMRw-JMy-OqWd-4PdpCd6e2PnN9eXCcDmgl4qMzoQ8VQN8kWv_odhqGpH6OFqu6JRlKKOEZ71
8N3YSFkrEU9j0WV1ISFblNdY9oOup2bFUMiZnDi4ZeCq3Ogt2MJ0E463eZFc3o1W34s2fa61DXcEVUzU-AqQT6aJUO2Uu_K9q88a3V8pzhxFW_GWHOFyYMde
UZu1Zf2YGNx6_WDtS8WC3V9incBVDtwaxvs630toNCRskQjtEf8qo9-O5c1io2Vy7NHAcz2VpzTEUb8rADwc_l9yFQpgVnBchPt7rSaSvEvyNoIIAHhakS48
xw3t5PciGNx6SOplS8EopDX-u1UH6HlaJypuzytO87zYnidO87zYniauND-cE1aRv4_CE7CRbBzD6P-ovnAUSUWV60lFE763_8aP8D2WfMSyTxZvJyovF-Jc
Fp5TWz9pnonV18QR_iHSgK7-lvYU2STZ-XFJ-nxcAQyxuxaDodzYnXkqvedfViYjDkFWyRZiYHbgqC8dPg11Iv-OWGOjtQP0WvO-CGF_H5_wn3GDAjScqw1o
RGeqQEqJiyR7zIUcn4-OwPQPiIGOtr8p5X_jNiVNdvXuj0kCRwKPIxXRtr8dfaJZM-t4DBx5Pcny2xR9-1QSyTRUZFS
}

sprite $image239 [120x91/16z] {
lTOBSXmX40DGc1-q6dB_uwRmTssPiZPXMXTujUeIE-cVSjGpnMShCDGzMCqNO6P0oP7iOKCTWSMLlLVOPqRPWHK_ocMxdpqDzZsmAyTKpF9nytOejvyvNmQR
1xZohTlXtBYfZGuRK3PjXqARMhuT3czgxNPq-LYx7LskMqJ5wpTrw1Npfg8gvaqjVvvktDGXg4BPUUrsrc-AdwUWilNjw9kAgfWtjM0xwpPL3jhEQlZ7CxTc
6sqdeEnsrLOoLRoyxEExMnAQGs3NRieRuEv-BymV1Uvji37oyUYw1y2qAVT86IYPtA2oJtP7Wifs2YnWK-H6ROhG47cCDnv6wyCDbk6z3pTOzjPR6sweZA6I
o_1ojRStjxKe6IyLlxcjr4_45ijys4_tIl1VvAKLlxde1dyCxlZ9yA4-khdmWHVANF6Rcz9k3BkP9ElROJUb0oHRhP1W_R3ifdnv8xUQ8EiLipkorQ-mbJfa
gMnTPPVEZE5osVvV5RCxSdujstwMyTns13VbyYYt8OjdrYjcTrusdrchM7PvKv3BvefbbpObb2rKhBYygVPisM2LsOlKwPdX94k7PRNNBKroWifcbs485NVi
xCqtnIxBhbHyJiJ9cOabMQguvCJXJH5ZcC1mGRKjIQ7_AVYV0REi7DQFf6QhtuqETwAbxGWLywOUYmO8RWJh5KkR6a7dilsNxUWLywO-OGUfBZzFUlXpX7vj
dyAzL-6mygQ47omyJ-gcvfcmVih0_Coggsz7tzGq2xOZR8gZFqzw-7E4is0xmgOuwdPMRugtipwdiwniPy6cIDR-sjTlIjlE-ZEBsrc_AMaxwpVLwBCuvim1
5VFJsU2URwTuKss_o8qfss9StXIvCIcMdibV
}

