sprite $image12 [236x176/16z] {
tPo7Ogiw340zvA7n_z_xEiIxPDIL5IU4dZVleXoGPAE8XcSJKmA0sbhhU8Vs0G3abC9vYGcWDPoXjGhvNCu9Iklu0Ar2YYVGh1tNq5l9xoeSLNCj3VBRURQE
JwELVChxwVTDXukMXg-YrnmE8zUEBwP1F87eQNLZwNWWBmpctF1eUetX-SJQyIre-Notr4ylyOcc7T-Cci9JW8vlI4jdDFNR7cDwVjlSySrfCImXVPesSD3n
TTGbwob-0i51SpoWEz0_2YiIrUzAE8F_agv8szGUEWaKUf6hKeARWdY8g__Bz1nSn8RdSlNVMa0yeolsw4Y2Sxdw3n8xdilLlzRcoPF8zo7X5xhwuhZWh2l9
NOvojTVZwZW9MEFQMyTRUffFbUpVsLL7CBXWkQ6xoaBrgcARMu_zq3KzEKjWTQfYCpuHMMXefsT_kQyELNMr0BO7wpfHg_okM0sgVjVVDVBsK66Wnk1mDSes
jBecNzeMQwz30y3XQfIjQ7Qj0lCjcnOduXsMRCzWi6hONONo86qjPIPMIm1S4p4FN8thRCOfLoRkST2viLpXrAPRPKraolNkESO-wOf8N0Sj3LEPWRbr1aGc
NR4RwfB1zTDsaBQspNWn9wfkknccNB5QadNiAlW5OnhKEbC2Djiw4xjyGcXm7LwyX4vN9EwcMyjbKBX7fafLKxIv3eAgkrs7QHltifn7GqDjECe4h8zD0rVZ
oGDwNLK33BB868EBX5-cX3vNXAipyhkgXa6Mf0O7RGjVhsk_AY9-LzLebZfB366IifdwNR4O2fFHLJLAk0TUmfJ319aqKPskIWnAUznLDTBTie8N_B3V6gyp
ZxfMKxOghLstIl0EToDK29LHuHwlCtvN9PgoLI6v0kznBq2xu3N4O3LblAP1gNjO6D6OiSvEa7dxMUzTT-PYYLwsDE0ihbtNLZz-LoIM3Z-95X9TKUz2V0dX
xsIjJ0l9uGOKHhnlAxUpXGawoy3KIzFAvCFQjHx467rf8TPl6fB8Sb4bhWrX27S0THtfAZPH_ydLPu-Ya0ZX62B-GFY3YvfNojf9cMSFL1KHyGyjnORB2F5P
DKb98aBeeEVLWsG95kN2G9KVF2BW6g3WuzGux8KzViIAAwXjmJepVl2a1QcV6ZvEwqyBtv3PTrVpcyv_ra5_NZxWTTSEy5WCRRzbmx7rJQUKGJxXXQbVz7W7
CEpePrJJbQb_bEkunz2zuMlen1nk2miI5PiZzG-0CL_tvwUfXex_Mq3Sz-iCeVEkEbB_gBJL_lp2nMjjeX8kWlc1yuAN92hXCjWVRF4LwmmnheC8DrhTlkr9
IWbAcy_MlhmPGuBBQP323J7NgH3kwzSPbXU-WfkhtVK9rTTrxVnJTR5ONN6vAjgkNasNL8-fKcqRYIIu618HnwO6RARsWSM90TtgVK6HRGMW_Vu9JK-Fl6EQ
xG_doVk2edp07bUsJqfQDFfeqc_isfacFbDztBM60IQDOfuqJywNW7HRzw1hYy51QgPUEgnobI_u8TUUWvDiaWrbYIl9D-HmDIGgTFc0MxIbBHWAjzzL57Qx
rk6WxqQtfMqp56wlAya6-LnR-cskWmaHYRdQtdCnJ9exNUL_sEMQVvkK9DFS9Vw3-h0zx7Sb-GVDkifm8bzDBGEBHPXi0ukf-LrbpwmhHkEav7XWCVFrxoM2
GTewNLdsy9GhGFW9-3bEY8iX0937QPldNKak8OEhQr9o3rCsj9F6BuZ0lAjSut1rzETLO_2HZtLWqUxASWqxN1rjFv9gwViImofNabl8uUhfpnE18G2GCQrn
5PcIRTQ9V5puo47ILxYotCNXwklF4mkRVbinkzfL5QThKTFrCEV7N4b-WbskK3yfS4LROulHwQggix8jE815twaAyo-kFAkgy3hNmY_w3YayhQhmCjSgVAmh
oM_mNt4bCN2OQrlfIcA2_e0hYH4wlIkB6Jgvgyp0kAUbbAVfXxcIJ4B-FwuSuJhU0XlErEjAQ63v9MMPTnN6b-9tjHwXoW1wlQm7O_tb8YEOy4oGZC1i292J
G2n3QZ1Kc7F0yWiG34y3TFBmLM9efaftVbFX4B9Ou9ERwgV08kUs9HOJeFrE4qpdD5L2q20-gIs9cHu-OPc0JcUgP6rbJy7d2bw5mpUYd2YKIIO1TQqYfz8b
bbauR8W7fZE8AZLiLF71T0fHlQqAYnUcjnPLu7fwvMrzrTCFXZqeZy5Cx-YffB0doWBM-vB5qrwOb29hO2Pw5qs5VXXvEDfOBGsQZWWsrcA_CaqviYodX5kI
F17-X9HlCuLDWdxwO6poZq63QTY_nc0aww-HmWBPCwig97y92E5rieme0n3v25L_6FVyGHS5yWVRBuHF8cn2b3-WxGSGjpUMlicNzEUf-cLflrxn_oirnPiD
A8OFy6Q5ptolOjOdvgf_wOcxraRR3j33ddJjci8UThlwLHLmRCBwxYlmloKyHptafQk6LynwAPQxKWn6iZU8DOJLENOHqNddldVjEfpv__DMLzU4oeDLgmSx
aNn1l8Lm3zTn7VUkSPSgVRku-jyLr315TmLnrX26YqDa_P6wgjv5kLpg2c4Iy0Jn5iBxLeUwrN-kUcqKnWyMkc8CqqISss1lKasbG1JLs5prFjyzIAmRw8zV
5sKgQBh-brMgEbmVBiEKWfE84sMlR25ywvfkNVDJN6juW68FuhY5y67t5LDuZ6uEOj8GLgbYTLrLco0yJ49h46yXhC5y4-Btwt3JdttGjOKb0DjR7UtVLX5j
wsjshA-EXMQTBGI5_rtaTB5Xs--RTicXwzDZhfZ3IgeXY7T-SOl-hJRMdUlkfwJ_j1-cGqoLmZBWwdaGLJtldcJKTVV0bNFyyJad7s1gZ6JOX_2AvzTycAa2
E0fYTRgLpRTzYTqv9XQdQu_XcSGkzxbj4jMulq3N_IO4DVsXtrJa5xY4vmCqDGerVfbDd7G8ho4sbYEX4bu9T3a8RYcy7EWd5FK3BmrcgYaSIYfTNa676Dw1
N56U2Jfkw1bzUydX7KdGLWfZDSJjmSArqwEMlUOOpaBAjU6yCc8jQda-SYwr8g8COCHUA-GSdij_
}

sprite $image12 [118x88/16z] {
jPg9agCw34NbNRgM-ly_zprmXIf76D9DvioQfJXQ7A5C3Vs6c7AfhJ7B0NEhjUGKw05hNwcR2u0uW4tVwbVTgJJskdCvrnpfCJ4t4IUyL6_cy4HPU6syDhS_
YaDk0lapa9P-dsOLo3C0BhzAE8qq7mEfyMCd0o8uuvzvOvDM5pHPWdC4a1heXb05bPOm5jAILXI15Bea2qGkh5XPu_gINGISQ4be415yrrfKDfRfHe7yCoiu
BAgxuQsXyO7-pJf8v2d71HlDH5RjkjDNLXOCkiILLRAJLiWBFZlPmZ815lXFJaSDjBIYBAJ3waayEwHGQEAOdRFLQml4MsDs7whfwYwK5Y_wwhKPScBDnl6j
p0DE9w60fo1hFRCA4hs88cVMf40Bqx3S7NKAPNZVva_23yzMVzfvPHK1YlzqrJZFRRm_nQQe2sjpJVLM4Km7FetpMkTDRjxIgXf4LbOKNrzl5G77wGXCeJXo
jouYSDQ3FSI6AwlBZJ67CXF5LEJIYkfI7LhiT9N1D4LBVuNIWdEo6MJGOjffUZO-2zPtQ3d0KT4qhCERfjgoMfS3wA2B-CwoV03Q-Qpfu5hI_vGcQWhv2AOa
jymtPT7vjQxzk360-IDnAf0B_00eXiitPhdteZHnN4tqR7tfhE6OLZSqbaimZ-BcfNxqnoOFoVFjurpgrZ6M1ymZDy5K5hoDVeKyufW5WMrzhVWsdI1F0Sen
qU-axeqFW9GnqJ6G6MGt-c-1V43l40YtMdAfbMKoy-6CllEVMt6MKylnxGkrNv-xuKEfBmYNGRtwEXYg-FLPkdn6zoLfD4Zm0y0jKHk1NXJ1KO4uA7A2AgvM
2Jy0_8wCUX8Aod6-n06rlhQkLvKvj-n3EQn5nT5D5LVMEc-cNVlPZbpSkdvfLLNhIolQs-Yt3W5gS4kZ2sMs-bHLSMxD_NJqppjomdZIhUjrQOKEpgrXIWdJ
IYHfdhb-NPzpzQcgTM-TYMxqW-EOkNCe3c-5li3AkfxeGElMnONYhKxgjDwwdkZeMDuNrrRLIRkoXfnJ7AnN4swyqHfpkhIgBRHCI_Z1FuPCKgzTMzVZFLrQ
lTHhs--j-CYAMJf_8U4GL-295UgOFhUw179EBNM1lAnzkexfmOFbhkkAVbPTjlazzzxdGHdgR3NjydMWRn9EhhkABpkxKnI2gGDVTNf1eAd4twupzCHfGXHr
uBpuHcbDFPQ9Y6tX7UA7fVKOY1R9FXDZKmxd8bLodNLY_3R9IUcxEe3f1RQPFrDZC-hrrJJI8Ah7cuSR2nrw7--xmGgzAAQEXNkZJqoltM6D1ilMhh5TinRT
DtNGR9sW7N_OnloaZGW6jr8GVQQL9le_t63MMocifYPDJ4svbDPDTInhJMwbWTwejkf-646oDTe8ObQecCcu1flI8DsMrrFK5aKHiqf1XIYr6YZqtTe3XTeY
XQv4gUIIsxMKwOpKJK-8L4mJPKiKrJPPsQrbqsyFcn7npqrVJGkT4zZClxrIr4uaEaQs5OgxTOz6hMFBjK14-eKKYPRaRcVTGAEW899Dqmvh6-VtwAlOoccD
FDVfHggPihsizMKT1t3ackh_m1PEbwWZYPaxnKHiFUmQIvHtQw8q7bRT-_hpO-VENkW3CipU3tpecvrOjMwApTg8gceR7QyTG3zrra0Bhhs1ADkuMuJjxsgR
LJEDXqTVunFdHc8zn5P345CTfGfrUsOlzdR5KBPmTa9wKneA_P9GOMRleGDg-i9qUlYcx2tHNqWDEejz7BPGSWxqPrALwT8URzJUXl898JTySZkr3UrS8ds9
a4gJhchcxSUJu9h3l_gFUkWwqI7SQew_4Vu7
}

