sprite $image288 [236x171/16z] {
vPe7Skuu38FTn6Bd_jVTxcrudcWMWK9vSO9y8-07IMSPhzNIbl-7ZlnLn_9-xP6_AxQNawwUVydNDwEs_AUE5mSLjR-ITFFyaVnziLqjdsJhU-sBEjxNCy-A
_Jqz0tffR2txPEyBQdZpLyPsYtznMljLJiQsViz4k_K8cxvERzz-s6mpzao2-c3pc7yWx8UDRRQU8M3Jrfc2IiBcCSz0oCFcFiz0oCFwLl_mGCDYRElt30-R
npmzmyF6NdKW5C2chzFq30-RLhrd-c4x377CqpCyR6pbUuQ7nTZM3oeFcwrEp-XXywZJCtfOtwQnBm-RjfRf6Jri7dLwHW-RUv73Wzi0MDyA1DLRQoHihTXk
Jq4Dk7JhOFFurg1Q-qCn13RsRxMl47RysBXt_BNm1-jWqqODX6ZVyR1v31u8lO5y66niOuAAzjN3wcExVz8pA8jXiDc6z8m_a8fwLZysjZxIvwUDaCFwfZrm
1x3--6dznbR2fgtAmmF65HKtWCjXyv0V7jnQdq8E6xl-yE1ziCR3yh7b3m_HX-josBGHXuS-sY1WLR7zBsanmiWqBCQM3oh_j2w7JL-9myFNFct8ORCHFIDu
MYri7WCEt7rr6thOsDG7RczzCWAMYIqEX8B0Wfo0fOriANrKLEXXSoU2sl4O_R81iBuHFKEyBChri6ahCH0IlyCW2oKinhRbLog-xca3mvtKsBWd9zx8eOTD
NucU8Qe7P0DWqvOpGGL-eoImSPqYMYECh80zF_AwBW9MLBOyB99-_CPwdRMDpCEUryVD2hIbofQ7_OtqPgrZPFyAMBJlpGgq1SgMW4Nx0YiOkKBPyh0twSrA
q8f-emXOi2-otgfIjWGia0Ahc3Q6m69GaRMQaItep08fi2ffmuX7XMz6qMTVP2rbP4zKu9VFwB8liXOoidL_uOqU-o9h7IC76lTHqMzVPELf-QTrC6u7B91s
ikfZQnsqO80kM0mgieusyYS8xjQUvGQm6DHdrW96jhxYzNyP8z2-_Qoe4RzHtb58vf6OWW3x4gmgMeSnoTkpRiuds9kKOzKREP3_wK4JOGr82LOTRU2OP0-S
3x0U45I2LMnaVmWo61TavX1KYXLfzGfuqBvzXcVLnnRb7ls71uAr12r1Ih22Ii12KBja03FBqm8fmLgC5kshOKNQ6lRbMUlJ0Yd1Mip8Q5yvAzAM9aLPkmZQ
ma55vRQiFWyjGNeTV_pF6cFaYlP5sNBhE2dQ-lPTbx_9gXkP83ttvPzQWw6j7DIseBPaZ5mrg0wSPMFBzmoeP6pve1wFe7p_rEoPP-rKREkGnhfqg9qrZ7no
FTEdbOfjmPuHnhPgpooI_gdHC_twncrF75GKl-sDj-y5FLCrjdnGeMV6nRPcpnGO6_d30w-LCdAXda59jptzuO5Nes9Rg6VqiQtKC_h-gHrKr475LXHKi6-9
s5Rg6Vss9puyb8qjRzyWUqO_DXRi6VssnnyUUEctlKezenyR1OU7kh6j4rJzs2WO2ClsJy6UaNqacCU-_DWew9coiULxPfxOZZayrDZsoA1E5Lj9pnGT6ua3
ztIn5HmUoewDsiD3hMslmE5Xs4U2UNg6t_Q8dfakjlFq33ys4WFXTFsZE3nKtVQ8_wm3LHyRv-aP_YC1SNYOBhRpz0o_xL67Xyd6ndbwXj_sY9wPBhP4KASR
6uc1SBgnaJyypBFjqVQTQDiZ3W_JZOr4pqmNM-BmC5t_l3UekErXpxmtjjyJr9y1
}

sprite $image288 [118x86/16z] {
lPU7hjqm34DVbYNBxl__RdFV384R8ZIK4BlhL5IFwdoCPgbb-dWuizKQTNsKEPKTkITyUGwwxiplX4rFbHlrBr6tfyg5XD--tksBwLRAWMlpdSp5l-RqxPK3
bbYKk503x8thdRxAFS6g5kcs85PVhruknzPjkiyMn29tpRNb3EiLkJxdsSAno2rJpa95RDqIo-NOD8jMA5V04ekaSiq4B3cIYYqEVp314elKK-HbssGihbUt
nRRlABlLBPeCcByfmhIoHHkMUunHR8MGfmOf5oOzZ6kRSQne4Tg2qsASOgb5t1OEBiwmaaLh3ROtZ0bOOj52pnyPbsBvUgSIbINUZ5j4B3urq1O-AyOObgyN
o-LKNZF7ubC3RQ5dZu-BLufO1BReumA3O_584YRn5b94R0rlX2hKB9NSMpJWZexhbx7HUe-s9nGk6VSAjlKzEvDmfPhz0ZPwFr3LcZas00lb0bKTbw_M3VuQ
K2vGLMuvswjRWUcnNAJgN7zJBoAnzDQ1YXclkI2nVFqqC86AMFrMkGFlHNJubxmp2LNcsiz23P37CWei5AdZDIF277xI7CebL38kZICH5agebAi7RS54EukA
vODYQYFSL2PIMyGTDHDc_rTdRp1k3ZSOizlqUl9JxWYJ3xfyluQZHIANCjjw-4xcwyqh5p_k5cMzu-NEEmgo1kKcb1lhswzNeMQTsSlPbxeBN76XJhxM5y4Y
qHOImIB5beq01OlKKtGXmf6KRE4HZgHi2q-vkjuGRU6PBwrtt9PnYuANIspX5b6kO0k9UYG5MqZK8vbXYsvHXYtwaSomHJ-IWYrI-5D3i4KAVse8jYHQb66B
_dzHXYtwaJnvvahHBH9iIRH8i2LnlO8jYHQbsA8-DLg6BVfJGx0bqwBnSly3
}

