sprite $image402 [108x110/16z] {
xTZhSgGu30NWTeF1FaVA-p_k3Wc92e7bydQprz6VkS9d2Q6eU8GnbrhNEJtkZwcWrWgKVBVqN87w5IZJdLBA5TK2ots5d4twJkrvK_agIU28rLkm1E5d7BLR
i7MdJbgw8Ito4iFwTciYMzZyzXuK7g9Qb7TRsLcyCR75Mp2ht6qHR-txvxgaPWt9i8ZZmmyrjotON7oryGfichi-T8bXVTFF3c1zRd_1S-0TNP-MNTgrxR7X
0dl7dF8_E-HNaOhSOxaX91_hLTEJU8jbzm5LFzQqWZTPTYUA_efQKT6sokDLYm0-9QAYHbQTNhR8JHAhPiEAjvndNlBKjqHLQ4tIjYfgRhy-04fENSkaSsAk
MylLLCmLxZ211RGnisp0-1tPBNYHvG_Vi6p07EQSN_3cqFAtHDFojqih2N-OfMiH3QsUGk3MINWijdng-E81U8cYtrQHwuUQkvRNK2y2elfjFPiTD8MMNHC5
g6fMbjQL9GMM1GADecRPHdx6a0ChJitATx2Aj2zCiHMaPvApMXZcZXNdnqqHKPMcHRDAPFMrZS6MNzk2As9enHZsNZIhUG6cKOki5u5gVTYqSc2DOFLhsETe
TLq2Qp2pxLPJK7MiBGkZ69dYDHcbOQ7MGCFLMytjIqXqiWlBxeKGysyrfmAWRS5P_brlQkVnAq2Z66WyBp-Aq4qCb4twrZ5WdOPUp-A-jaRM7aioQwxYyW9L
EaM4hQqD3DVRPCRnpA8g1AB4O5IuJfu_FawqVxMjlcCnnj3O9XE_6mIsrJVU6hD811YkjqbxyG_TXSWIEPy-d3B0ysZ9eRl2DmpnDkajK2TlYRisV9k3rE0a
KJtb5Jq2VrgOrlmhwxUpTVnliMM7yHhEaih9ygCejgoGuThQiDobw5h2KADenoAkDPma5V-FldoX5QI6StdC8j2KOijk3DCkoYEjlC4VXTAp23JRpGxTskKf
FzBddmBB5_8phW_DYsjW4lOB0ijhldnDYm3i97Ozfi2ArYSDB5AyPDzxOel0MOejemu1D2sBwmS5ICSwpIflXTgnFA345eb3ERmLQ11_OaZ78c7b22o7MVaE
HUrP1FPoX5RSNQR5bbqvRl7qilKilRIaRybfLdKjUS4YOPBURP6mxXgo9Xct251qt4f5HYoxvR2rnGmPjkHFMe-qKEwtxEimANgh9O-VcAhWTikqv-sMnN_4
-ctzjdvRShjbiL26BGvQbbaPj4HpfenQDkw7h8_yI2kbQudgunmPCfJNPpaaj3Q9yuNbpzctR8qmIrJhlbfilvV5A_ROPC1oVRLBcFT3YwgMPqDov-nQjaR8
bsLvJ4MeYgd5s3b7BEihtV98TcZc6B9pnfRen-pAuVD8AMRidDvI4OcwAoqCyuWVctzBoaA9kkkPXXKxvo4Fp7jnm-uQ3njRFe-fYYYczqBssCIwQukC_BWd
CYXQRyYZCRPUp-CF
}

