sprite $image357 [168x241/16z] {
pDK5RWKn40HHZtaMxd_SC2rqaazMlHECv5Ov36QjnS1N_4Mrm9RzGmbWiVkNdWAKLT-0phJu1dIcgVkP31jcSw4drZ2rPgmMQGKsJ2spdbph4T0Y0TEetFqI
XTOYtIZMCBKMQSFKCsMrI2k0OO9cQiLlrYAjHNgch2VNCgr5UgQq5kcPibga5MCDKyi3XacRQVQ7gWOOvgYlr9eFqFEZMeHgLEu-p0ngaJOjAwb5-ifrfGnJ
NpclhnWjqkPbVOCVvdhbdNNiarzvPnvvvR9UUMViOv_ykZjjx32tk2tQuhPeYzkYBU0dUOhReYtQC1NMC3LMYpJMC3NM9wcnMgInXgcnMgInMgI9OGAUV8lS
8drd0hL8tsc0OIgG5cdFxTc9RiCy3WHWoQTC3j__SVUeYTXHgeBhGGrrVnENY_E3oI6Rf7PEfSV1h9svqy6idOEAzAjqvrJAhAhIPylTwUT7z0wfAo-Kdn-N
YdJNSg_fe0ajvNTHstdG-ERpWzbsEYqWPLlEEskfI3zAhrdtgiUqZy6idO7cixk8Tn9IekM4Cp2cPCjvPs1CwLt4Eudc4oqdd87cyqhUwKKqdnvCg23e94uf
kujqpYcb6G4dFwPoNPdsMffEUanvfQqfUMK4dCIEeWPpIaU9LPKtLt7DvuyaXlIJSn5HKbgtd6SEs-TCgBYK65F-I68yb7c5VUDKbn9ZoX_9vKiu2kOqwxSP
SmlJVFxyoBwDO2RIs0LEOQJyaVpg-eHz16JRq7B6fU9ZMWyc_pfNCspBLvwoj9p4c2gChDc_oPvoyXfWxrMSSM5CsPR3p6j87wNVEu4hOqefbzSxG_eiQJZD
S65CBxSS9QTKR2-vu0oEgR_Ioy7v2lXOEMDz5mS6NwaehZenlxyq_MJcLex4AofLs6LdILwpk_FXyyVHsiwuL0HcrvrpzTOSdgTLWC5twQUpbWR654OuCJZp
I9AMiYcE7PMruQoaJIZlz75ijDSs_zpHSCQRpplBjx7M6MQcWr-ZXZCWPPqR_65ou_d5OSr93MMFqMPruN2snfHqUicKS4vtFYS9PKWfZSkGF4G1PsDC6QTl
J7txNpFjjVdMFzM2WBFH_EjER-hXNFT0Eshoyzva7iwGb76kRvaPTzxeBAsSnIpWR8yfuLnST1hFrTOZISEX7CG2pi2OqixDBxicb-55Jdc11Pp1viUTmATp
yPXZU2K9eolLBE0CIkDE6Kljz2QFlYezIIZpjFX-3JWZOnftwknt-kpqTY_dLNJuWixuc69d_k34Zfigfn_D8PrgPPtjviCWqdBwWTchLCuvVTH0EjlD5uW8
q7Rg2v7rpOcSwXg5ThQRBseMSgRfpIadtzU6oWL6E5lI8_1HPofdvth-wd3q8qaucz236NLcFJcdyrU7wwHclBEkYyuq7KuVpzbFg1dZRDSrPnfUJjcP0HZb
LD4hJgzNyiklEvLqxbT8BZYtttGEbLFziqPlpcL-T_h6jEwSo6_EsN-xxCvfsvjpy2FPdzEMarE73TQf4yFXX2jxTFfgzy7ir-cTzy7isOdH_tlht6dg7tTx
TngCBht3QVyev-ESz2yu_KZsxVHFQhqxiQXPnqw-7YTVZ_DnFix7-JWVfppEQ3tEn_au7-VZV9poHvpR_vNpSJxEn_auOMQFyt4-plLFE7LCVy29EQNA2NJd
HCdf3pYt8QLFfug8TEJKAQMcKwGJ9vRqgbhWqWwSA4Egd07exKuPKsewWORqRgVExciuhV5ExtLYpUbdf_CEAU6aTr7RwRmAIZY9NLGvcr1_99pSBggT4MdS
oH_9Y1CDAU4aTb4qxnKquAHtKTIf5Q-InfpyBehblT7ye9FVHLVpxa-4anZCmncN_f8JZS6CvRrX3ZZ9mOpdNNuUqxQJ7ynutYFDXndWNFf8Nd1-y1fB053d
_iAHvFD-F3gNOvQShZb3AH8lXOBTHLUTQFDgFZn7n2uYd0Ws7rpUiJOuLDu_pJjJmUwYU5r9qMlFWjr5yRgM8ZYNs4MCCvwYXfFTHNpU_OdCkpG6ayzxu-sg
vvqOJCuPIT6HTs8mAQVMl6RUuTnmbI4nDPGBALBiVu8_al6QjgXKh-NTZoHVirnPzfwZ-3_iVENrVrts2dCdVoJvCUNpNkyYlgPuynjv3-qYll8YuUP3dNlX
MwrRnzJpJkmYgiR0ZWhcNMUUmu-fvvtOHJUCQPLtVXVnEwgTTsZJASGkOiSqddV-IFAdjCuxluluCVsv-QA0WXZC6qvf8-_yaUJ7j95tuaZUCgOmg_EE4cpv
dQSKS2vn96yOqohlyIDvwodryhpxaUoYba_faNVKkwYZCVN0WzX5j-mec3knfDvgaigvh5fowh2MT-USSkgpSdbtzblZrhMpFgKWhlcT__41dg2kQoZtN_D_
0m
}

sprite $image357 [84x121/16z] {
xTI7UgLO30DWqpaklF_ZxiKGfJZu6sAsZxPE-uE5RkXdwPQbfsSpDUOsTG-Auyhj5MxZKsA_C3SFy_f80TryYgSwT_Mpsob2RLDD75O6YV0w5Cxs8cEOVxoh
gGMnLgll9qcogtm_APhKcku7ATGQzfCd-xZc-odN6lTJg3NTJ_weIs4_5n6xlvyyh6Q5_Lo8PeNzH57CKzyF8ch1h1TvQKwLiptr8d4syk3Po3Fx2MQro93w
Vc8UAZAQNUNic2Vs4yr-aDBPCTtCZOMv88Oiuj_nXUj58klnZ2p2zI9XIb0BPyCyDDHQE1kc9tdKvEpC30NSFrk3YGAWtXFRs0qQJQWHpOjKqv5UcRTJdG5c
jUP5IaTkug657KjhpVUZFT50VJE3AGmrr8gpiqpKjSqFWHbGONnSSNOI8HfadVeEjpi7DTIQdyrgkYtq5Z6OQb13hPae8pLJcxur3p0-AalMv4f4a-a6irEO
nn_dM82OPcP_CjptuympqVYrpwYANPXwlfezgwcPshQDH0tcfrC_gNfXRiAcjhevxFemoOkSy3LXC3VKcfgwqBJflig1YDXcnt4vp500p7Zsv8-aFGshVo39
CramWmep53aum2zE_IsDHFx1Z2PGr1fDqxczcGlHskYLflFSr8Bv_QEQoYTJruvwFSsHgCTRCjDeNXPWY1ulOzvsSzFELqv4YwcgMMPYLmx2D7m8UTpDvhxq
enYIciBeCvg3F-TCD1nVKw_Cc6ZYWxsRBvWtS2MpSz9Nr44ickDoc8rGPDaSR3ZCrUmvK_O9DRCdJLjeKdlMnCyzQPhfW-PCj0IWPjeSzbCpSVF3flrtpD-c
_DFDtwRy3ytVfZw-9RLDHZcYLHFeJ2HdcEkccgqzVJ0RbqmNUI0Yc0erCtDH9pg2v_JxkV2SIqSmSJlGswQQjTwvUBl_Ap6J_JWMRsT60RTCtmz5a_6KEyhH
pFVphQad1JgOsNukJ50Cse8PYyH-eecd_5Ihkx-od-HsSHLq4vLVt4z-E-ZGPxwV_7RGk3tPJsQ6D-JhKadsSnrzwnCKQDoUxoTcSIw-8MRlEFd-asHeYji_
qtvxifyi8qC5xRQf9Fl9qysYyUNxptqHmtwIzAjuy8PmUxQV-xNYTkodexkPK6kuFTjFdcxvLAlRA3BTJrxhnqV5xTb-RkmAjsC_bKoxXGRo_TolLLGrty_z
NPanX_qKQzMj5PduSJMhtXrtnJzztNy
}

