sprite $image231 [236x172/16z] {
vDQ5OG0n34DHKmpx3rpczXYZlXcYVDC5h4BeNv2i9qxuEEgD4JYhJwa4JEkxO08bKRyqGiHUVpB4eGv98IYQDI8OhpF3Z42qca7nXZei1AypmvoHEWCyMwkb
Kj4wWzOVZbh9gJDU6nZ0K05dArcR1UDrPbW3UBumizNQKqh_1o70sUXr00CSwZ35wyoma0uEGiJPjZgSuNLcM2f0Pxev6zdhHDv1Pm1cgrdx23SLeLSiOXOv
U3Pst9ameJzfYu7PzjaPLnh35lM7rk5GZTT-VdhFpeI9M6pvPkp2iv5z-U7kM_B1VjNPQAiIiUr_qKlwyqYzcI0thCCmjB8sci3zh_ltk4uP9od2qSpNxCt6
Pv8I1AdL9A5JFvLxSxbiB5CpK0O-piTOlDiRci9f83_lix5ojzSqvRhj938ICPV9nisq7OcHz9IuogBTNfbQ-VOpQSyjhFXirykaxpAj8F4m82su1OS4LTjH
5oFXZmfjaiJ8dHlRUkDXVjT2QDGpAacqr8Tkso91656DnCN2CE3xxY3tJPgTbBRDty_OyK4d_Uw1n_muIHCQLYhaVEEXVAFYgSfl1stNMHDtUsNARf27XUQY
Dq3Y_V2sn4E2Q3nepMfNwY6A4mUvbzIE6aMSyfI5jT530JylvAcfHBrjupeZJan0oFJJsW79jy93_Y516HzvjvqXqw_c193-Eho1hBEzs1NY90mFQNqvrpj9
Uz5dXTeXGRx1VO1jU7C1Y6txF3o7K6YPwqnyZjtts_YTpiLpsMZCFTiR2KSjCsJwxRaGv5ulKJtpRA-b72jPP4reMwThONN1U4Z8gzwsbNGzi8jr9e5rQAnd
sUW_NZ01DUpsCizdHlmgRQliu5rmWm9ga8sf1waM1BfleWNIpra0YOHpijGR3uWRhwdO87Nx2ePhngY9D-lyQDY0Buz9qlEkXErfmu9J0XFuWk6QDv3sRIXX
vyjFJ14daKdg1B9e_SYY7VZSHD9YoKbraa0QBMkOYYd2ZcnIyCOAv7nXT3Meb753Slc2F5YJKaiBPfM_QR1ShJCsMfi9vNkmPj4wMnHYlt0Auy5U3HwuJae2
YRHWYsKCqehKg2r1meA1DH-ssFd9MdsFzF71NiyW9G6PrbeDLvV8zY12aFJ-8hdDIC8lhbk8vHjODThnK4wZXotnZPO-hh9Rcl4WZTSj8962WLMbtK8tHHkW
Xf_UPw_RtLlQsFyBvP47M5Jr3uO10JPWzMjxfrqywJ17Ul1sFr7_JbwmIhJdsRNCQzkkpdCCiR9u_tFZHDepIKb0fGKvpfv2knQttNu6SumVqrql2UeVl68L
QPyRkX7tjVgnKOFwJoGb8SF-zXv0gKzuRRIIiiznyWchIAlT0oYrzNb6jZbRsu9_In9ff95Lf-sNP4Q_hFBjsfCdzKRLMO5tVW3rKlAHj1wedgedbTH9WLLe
suZJIEAsIvxj3TxwdwfmaLHWrGfv_bHC9Eua16oqxHAppvjwqaX1WLLUVzYYsnb3mMvZZ7eRROovxq4y2Oqgi6gmyHx0yFZeyJGGzuJjkC0ghp_brMcOE-wP
WK2faEgiEktGJZdr0MQowhAnBINLMVMstUkgV-zsKc1DRjibgNKmWJMnRRSbvQkpwh8njgqjBr-TLPUDFiQOv19IdLMdZT7uWl9LMFDp2rz4ciyQOTSFfpmC
_ojQfpxmrNmzxVholIs37SjfroVL3YTxBUnwqhDitVPLjElBDxhO_SzcxSDOOG28WUZFWVuBfW1mVdFiTG1uPoKPW6qMr8Vx0TWMGNr_lkQ23rlppEVYcWSU
vCxZkx3I8soRdbc-tolOTZxflhTg7nbiRyepomTYOyqpJMozPvQFnyRvJthR-Pz07Xld7zy5K0FOwa_wU-QJYhOtxva5K0FOUizSkW_m80Sy4_2FzGmuqFOc
XWTm83P6FJFGzcAWUcnpdfblUtvuA67hXmT_FZRwuQ65hHuUuFdO60Y4mstFUwQARI0G3hOzDZpuyoy9RW7FZBMzWU4Xuv-kPtnix7h6nyQkPtpRSvxfOzlr
Z8-DRdZeOzlrZ8-D0yD39ZQwuQ6FRTSplksvuQ6FhHgu_VcN15tF-BRN1TMtFHS8-x6nwndVzjZmq8-Dt3FXjkU6XpwsRdZenqRdcJwspZFzsEY6XtxRSvxf
O-k6XtviTCD3tp_EC_ssvppJRtlEC_tOw3pJnzOD3_ssvq3jnqRccVvzlMOXl0C
}

sprite $image231 [118x86/16z] {
lPQ9qgCm38CRSbfst_zrToYXb4dHPkfTzD_dHwp8zkDNnLR3usQ58YAIxuLcmKg5fFkOiK6wK9Txc4k5709AkCLGo4du__OcWGn2Y_SOsdM3lQ40SY48iTUR
5Y98kg-ut5v_MeYcxFMdnM6l8oqEUns6kktr6ugkeKcwqiA9qahEAULScW3YRvAfuHlc45gE7ySAiRITsz8_B2vghjJ0s72ao9-MWrFuH4z3Ybo6TixIDkV2
PP7QCGFTQUcFNWn_AzzoAexBqFRY9BM9_vN0ckHy-qFP3c5u6vhhzJLjf4dozZT2Ywd8tWAYcU7gp1caISwsFzJN0Km4yWR52hKMI8ddx0q5ybth_wugWXCb
DQYLnnSLa1ausVwGLuI-yCCTCFrIFnaqHetFbiuIY600B5LW4ecjn5u-Mzhw2-ZuyMa7UnSbCt1sMK3PxqUxSaRrmzwek9nG9GnfOTHuJUtsxkSenauWUJ2K
LLXE5HxjrTmpOqA5bewqC27qTeDydRgmDw-PJH8GgYCvsFX4ePhAZ5GLCdVO2X48WMOr4KoSLPyhTcAhNq_I8AAuwZ4H1e7KAiAbzZHLTjpzWLx12A_JMla-
oGrz1CU_CirK6RViwzV6oe28QLc6Jc7wxhMPCB4oNrJ2NVRkZ9QE5WOprBI4lXVc1jDtuubGPkW6DMNOia-YT1ohoWOsKs3xU3nMQAQyk3kLS1NRVdRkijjk
Yi-LlyJUbfGNzw0oBaoMRy6CkTGcJLfhjQHj4mzP3PHvebAkMWsVaKHUFkZ7fx4ovb7SWqgnOfe_8gbcg3c6yycRce4REb8v5tqh2r0HsQ-II5ibqEr2SKCv
bTjxZ4H0LTL8r8UqC2gtDnGXuiNbL6ul6Ooik9pAxKqnEvY4oijCRYf9ow0dR1xhDxH3BLJz3rmmvhE5rsXK9tTaFg-PY7qpnIpNNrpDfvLd1kitj8RpUgTC
-3U6ZWDi4N-PeTJGz1ZbjvSNjpmkLBYzphGCyjlBcOWFglYJlPX82rVcJH8EGva2jnUEj50jZTlBqi8DzTaxMTp1KAUzCyMj92qaHPJhC9IApq2bXcfw_2hU
9CsH5YO-0qdxMpn8tYGTQN6aw9VsvxUNB0ikyHdeI8kZIJhIuh3NaHP7aoJBWajy1ZhIuh3NaHQ7lOwqE9ga8osE9abMQvVu3EnfkLC9QjtGMrNazxJy0G
}

