sprite $image47 [119x86/16z] {
lPc9qkCe38J5ZGxs_TzsZzXn3oJwunclqtEdJDhIXnggXlvKiVL4NrTX4McHlghSXV-LS0dqDSKcmfk4Ctr7eOhm8P6UlWIL9udKsn6dlfW2ySrGKQNWxptV
29LbObhmx_k6AUycsC5JzI8rt0mLC5CN67Ev5sgBxvlm_mvJ0CGttntgZFWsg9DkGZptbslmo7k8hoSXMXZ3xeVmSX1VJq9vbX6wxVxTyl6Pj-ck9s7TNiQC
zsgB6gT7-NWMY2z1XMHefYH3-6bRXTLwe6OcQr3dgqa8gQafys5RX5bCTJ85uYj3Cqk5OKjP7WRAiu3u6jHPiwql3DnvgBv4HD1aHpxYpqaexpovjv9fKsei
8gzUlpl5USgRjXgBzBBmIgNBo_2WOsSGhq-l3PUMl7U5Mdfz_n9E9I7kARapLhljAhZ2jYdYFYEU7olunkD50hbAnsAHH9iYoi35rXkQ-GwQn0xNgQjgfjmI
-62o1n-h-mGjk53dlHTv80dYOQh3L4NKpEGmpZ0mEnpoqa8VAZ1KCtnSQLSRYa_LZgSZb78a3AHpiSti7EGf1kXuskQHilWnVkQy15JeWEgg2K_IGkUMOAfV
ap3J9zN5LZujoOS34AyVOOzuYkkNX2Ek84GPTYMaJNNjcM4yI-zGcqOKheU13jirhDAcqCnubOwkkXgB6HQfGTYobMKNDY1LVHCrRyv_iR7PwahBD2Ew3YdQ
7t9jlTUQ0hrkS4IDZBUcjjl2646J42J7YaokYiaIeR6_GXKT3x7kyX6ZNW7sHO7HJDaOlONwA7MOm5RbBUAYnf0fM49njf2XEJjG_vM9M5Ve1V6G8aFNb-4I
9y_2jbgecNgcAWgs7cBbDylD6crgh3Qm2lAWgZpiOGlZZnBjErArKmjOqTz7nM3xWjWNJgFEPoJFdIIwLQoezcJ1CbrS-lRFJ_q5r8Svs9uq5kwosehqdupL
0FMeUB7bRexnSMOL5eRjTXN1CURtrtwjU6PhdJARYtWxeKETgYtxeUsPxcvpnMkrZvkYlIqO5yVOTzl0k3FvGmEepufVs78Y2is93sk7yVedwmce-6SNczlC
Mvw-DHPRBp0uLEKpL5JyLmjL9-DEb4CpPufrI2B8ELGTgAWuFqZPRCl2QdvUzZYP9Xbw1YeghiTsi5zjkqbivXeZaVTtTeytiRLY6zDR5x79bgXsXLp4zIUe
-bhnoYYqnPQ8KR23EEkGJqauGoqq2OWbRxOfbbJa9yIPXtuUckCTR1pp1m6nTL4Xwjg8gFcTjk6Sv1vKZkIeg6qEZqxNMgYPUoGwfWvKpUG9Y2jronGpHQdY
6VjGvuenDBxIrcaMonG21QR0RgS_9w5kGnFeexBOlgTJfy01FN2CdIG4r4IdjETb9NhO9gAfOF6WUabuLl5Hdaabua1IA6jtXkaAL1znxe6aKcv4HI5neJf9
wCX5B6ct3I7fPFpXUBCf2SyhF17_Pwin52es8nRz4MgXFrFipnjMQZbGAZhBFAXE4lucOksjKyw8BBXwK3dI1U58p9Gew2JtpZ8aqpK1SI4ACjiwKDUXkOJO
k3ITDKFral0gOZETDK5rX-OwubdsEgbw0Qft9BuKUnFK5V7gkqAzxN_d9-CxeVg80TL9mfiGsp1nal1En0TK9mdlGNn0pVG50R4vGtCpOXj8mcyfTJNS2R-e
B1U6vXy
}

