sprite $image196 [128x270/16z] {
xDHLWWCX50NH41g7_MztulxuuuvLHLjF--uNv5DzAdcfdkjRsSluK3yMH7oiHb72RzKi27XNgfrJdtpz0KWpFwttyypF_zmlotdyPlDDuZUJ5_dDu5N-eK-w
qZ_qXgjyep_gu-FZu-FZu-FZu-FZu-FZu-FZu-FZu-FZu-FZu-FZu-FZu-FZu-FZu-FZu-FZu-FZu-FZu-FZu-FZu-FZu-FZu-FZu-FZu-FZfvcVrljXveVr
lgisNzrkVK6p-tR9FlkQiiMBAlsZxrH-7Rs_uhqFB-9T7uTwVy8F1P6_7xVweN4jYVnjVAw8_6ZuJUJdOUGqVh5yh_6RvKVLxMUK9RuVLdMvxNn8nVHxZfjt
ot0VSZdKpi--MW__yw73JwtdP-1fL0hx5NWyuL_5cecIWo0GH1bk1lZ_trt5IWVZ9gEH55tt5lXwcYCks60DUrHQyKrni0LoUB8aDBGqYgx30NxAWzSJw8CT
Q2_G1GUERk6TG9STH7CdUfakE_3VHc25udySWRkDnooma_0muARWUmCJy3U6m00_p82-WASu3ezLS84lRthtfm2HDcwHDPfUy1hueGO8Q6r3v0nnT2IKFow0
XPtoGHmqy9H-mqyBtA7kLp76n_oAxtiufnY2zpx4Hno1VXC_333OqHlgfeFVB4JL57_5toXfOHzVy9ethrQbXtx0J-_UJFLgWCrOFl32-nWCj3NAQHEFudF2
3l119Y-o7J-FucVmnNEzsFDvKFmo7oF0Mgb7Sow3oiU0adokw9Gg3xk5XvHV4AZ0TziXvhDzIGFuvPcdm3VR3K9zTiW3qk_AeHD7wwJgiqUzRO1HVYgDBqq0
gseNGCbtyLqn8j-tFRWYWDi6SkaU9VDjsm7gpa0jwNjyxTAlCb-t2LWNvTGPu6-px_2vWYzCG5LU3NmLmKei37nP-KfIMlWwh_pI6MXrNAMN0xxcKpSh9jRD
GDyR3YxGymk-fbDNIyxLfiu-j-SLFcK1hNUzSK4XBq0gEmCO15WGu8UkjGdJJrY00GViVOHuSFlRV-ZMP6i3Eh97_6Ss08qktJJS7ezRbymC26_ddwKtZU8l
7S-RnaS0gELW0JuAk4Xdr_pQzOpczWj8kNQ20xp50zgJmTxHeQBFyvL5pqEaNUIvDEL568mNE5ISEiddjX3AQtaWd123Zlv1dULdjIhW0VtOyZKuLAAwmeU1
euNCxqtW7a32o_bZ28ugpSMcZTgKkoLumDC5FjQ9A_MzobuVc_gJTBo1maqTe6pL9NvK4FbobIPdB--_dNIwvu2DkY9__8p2yFSEihl-QScnZ_qkWy8NwVW7
u20JSha8BzySkbDx_tjp0vVBUJWBDq_ozdSKsNZ6Gi4PptLPuHCsQkU7vJsw7QpT-x8fY8EahO_RMq3_onI3CrhTKyBqaqL4-Y4YTLyuW9acX-6VeuGZq2ao
ZDK_GJZ_co5iFdPk-OdcbPyNkRcJFz7KjSzsxjgBq_1wJP_rNBoTYiz-ujZF77mduEbLOukF-JDUSovx3KnAXrOy-y_RyfwVZHuI1fb65sP-0X_AtDJVKGRl
lNFEMgDNoSReUGqVzQTs__4_w-5jjHLyCsLWYKXhuyBpBZgX-BjysHDEhY3v0xLuv7DJlYqEHeboHpnXMUf5Pf5ppYyAORjjFkCj1KlgXCZ7j9SxrOqMOzOw
rqpjB74ApdnW_m4
}

sprite $image196 [64x135/16z] {
xTa5kkKg54HX85XLRNh-mtt9sVdkSN_Uh7Rv2wvRk6gf88cwX4-AZUAMsE8779lsXFS7gdDFzMtVUHhUzlYdlNXC_uHVSonzwBtffv_-kkcddtxwwQUVVlhf
fvz--kcddxwBFvhgR_kiqt9ukohAesfulpAEdp-B7_ZsozPaPcCi7_W-R7WsoWUU6tN_gttWTVG3R-jKd9eTVidf3Hjp1IW2wBq3f8XUb_ZQoHNSu4K0KTDp
tKZ7rxsmKE3w_a9ve6FtczyFO8iVSn_eyNFk0xTzTVx2G0rUJ6inU0buqGDfjRc1McFFxnpl5yXTPk8AGBDjBtIyx3V3bltgCSEu3k0DZtRspDoj7ppn2YU0
UFcrcYKG05_mn9KFnMeG0B4zqOq2m0kVX600Q7Wo02C0NVW0fg7d0stdTkcxbk7_DFZ0q_oGAr-jc0zm6EveQ3WV2XTbQnpxW0tnflxvzu5BlwZNOSC4_nyc
ujHIvXgoOQDU-YH43TklSFZlmqoUsJWCxeVRKBpqaGnv5MDRyFz9oJo9n8ysVtDqxKFT1lmiuZ8UxhJvqS8Dhx0D7FZmktFD9VrXy7ddLvx-V3pC5_oelVsF
Fb32ZPBelyAFyOrZPiE7aC9jZ-0jld0yzlIFpE5s-UGzfANfg4wMr9TmhsBruYl7SkIPq79y-DxQrSrIBhLjrPAJsxj5CeKlMjJ3DpKht_0anczyj_eDBzyT
lr3v2vvvVlkuzoAlqXblygo6vnknm5J2QPHvufQ_LTsU2sifEUTbIUcm6zDI6irVA6vwS4kUxMdjC4lAHDUdLNeg_gX8QykISowbrjPwnxx9VluYzGS
}

