sprite $image311 [232x334/16z] {
tDW7KaGn30HHPrdxVV_haa5Gx923jzyPFDKgfuqrjvpmwlGRFR5bymSjWGqFioIevYyDv4pBz81zl7duMPNzP8CLM4i2TAR5_1sDrH9jLjOmDSkibcW3SEG5
u4oxVyY5duBLly8ogoLQ1nnvi9as_nuh5tBaVTl8h9Pe3TOIhRA6gLbXjKGRcTKIhR6VR9YLrHBDCgibsjZomm0wq-P_OPQzFWoOCytcVwW3dkp6fs3rlsTb
roFlia_1FFpVDC0mjpe5w_H_PWNGaZrEmUwRQBIMw9coMg9PPhL4wwYMQ2TIIxHZSLgYdTPQb9PefsFTe0_JZtNdvrgowJ0VG5iImtn0Ricn0habpn6EFFra
G_gkhOSPsCCCp9Qy1Zpopc8_sK3uC0Z7KbWjqLX7diOUPc0TUHgh9HhZm-1zZ0-3zx5Qeh5Qeh5Qef5RSitEVUZ6ZiDG69R6dUJxl-wMsH6Y_700NaUsPAs9
Sdlv9kU06WKnd1tiaXBE-PQHvVIwIpWTN1YufjTTmkbrbt0wk31mJO-7FB-pWs9YUYqcfwz3djyPEoacfuCB0zVqkaiulUmIl_CbdIhfL96EYabdYkpuKbNf
gvXqpfzNhocfMCd9ZpyY_qAbYyXoqblfngHgXUS55C9xNoMT_F09fBSj9fswAnNfe9Xmgkw6Lpg8B9m91Ma7aOLJMwYfg9tj10erlR6IpkerXV8iP-MQYjc5
pbexHjIkSjQiAPHNE7-kwKqZIwUZfhTKqbcdfg9siRDAJQ6ym5aZl69Mrtd9KL3KQZYlhYcKLPpd7mN5hBhJNzFsbNHU6LvHQyzPViT0sOIpV4t5AaqO1QGJ
QofgjMRwnF2AcghLcrK5qe8rfRAgK-LVwIzgscenwNnBfNnDMSpwJbKvjQPGrdCU22-bxKMMJaXBXfVA-ivVrLGWHJ5RSshn7GDbAyxVxnX1P9jpbg-fg3Nf
DDMIE-PofNgTPkLgAbShjzViTvgLgUdbIXr3-3Edo94TG-d5oZc6Ft9gojulQYfwjNFzL-btMehW9iThAcONExSX1A-JHHCvLbDHW_EAOZgTX5Bg3w-QmNb1
PDrEzknmUCqkTuxXW9DIXBT5PppcP7WXRSufuO3JKTFMdCi1fwUchJd70qvNJHjpnkDEVqthEpNysaafmjk6SotWTDIqkdCiu8GKuQtZr0trFEhqxvWAJftZ
W7eMSwhuQahdMKTPtQbdFEJqxnYvqYd3sx9ODjD_lh60qr7JAvoQB2_BvlLvc4K1fwEc5pZd6DA8iPvZ0QTZnvplt6BucibOpoKvHvVpS4tFTYuXdsYifoJd
KC3fE0gUvVmmqgoifnLo-e-2vPtBbZcPplJZ4av_JHDEf9XpUmN9d0ZkzgbdAQU_fcQcvUwfTNoZw0phzpnhAQT_nvY-mLR2gNCAQM8mk4Fwy9Po-clw-ImP
dSVlAvSTPz1lzIpdzDVqwmAtq2wHFUUIrtCjxgIKJXKnA-GSGWhbZlFrhPx5dPJIgMh5dAcAT2PRLi-pdIfocdFxIcZ6-Fv6CwPNuXGdfUMTEKto7ymnNw6I
wdcIazB2JjOpTyxvcvObHVWi9wLbdQndxjHyXOxfbRZ8gLBUALazCwSDoHbJFQSBd1WuIspF3Surf5bJFM_fvBMimQanESSFMM_bN8VTQzc1JXk_6ieJG_lE
xONhIlc2mRdnuNIjEtcJj-pNaqwBU8js5wVE4TULg2USCm-0-MyOctMk4U-rM4yw5GVwx3V4rHfpyW8MmTNCHQSDg6Vw3N5MQyp92tK6TythIUUAUdv-mwXc
3JiNLirOJperifvcox2PDUnaS5bFElDN8VyTQjQAqnzSrfFEpV7vplQSAqF8UjAPhz2jGQS_k5FcXXETjliuRMHmxOKSqwciP_jE1ZTdJBlE_ALP6tJwWxj2
GMVw7ODQRQV2wGvkhj8VdHPnoBk5ay4TSlI-SuopsTsS32xgkUTKjTiv6TmDzOGJSnSdWujwTkDaS57FRfmCBkhPZvF15TIp4oTFvik2Uk9QvBPE1lVptMXq
pcftTZAu4JTtk1QvhPF1PJtVphYPTU4SwLHysNKdpXNCQ9XEd0pksAjpH3qxTJAusglJ8khPgtD2FNjrokdrDAtkP72rO-U4s7RdP71Vc_Nij8XtNrqv6Tn9
hNUdu8gzLwUDcrbtplBpE1_dutoSZ_DnFix7-JWVv-Dyd8_pSJxEn_au7-VZV9oFyt4-piVvE1_dutoSs__2AKFerSbdvFNlN6BumMaTERSXX1-Tfd9p9n-4
lE_KRHFfm3advRupFLBopau-2DdnQBvxEkLTJ3Wv2IftSdANE9mgaDxCkK09vwxqVixj5LnEIk_bb344dzDijwP-P-LTudUA26fw4-SQ2QIJ2vJILftS9Mud
QR91sgfJfn2yJj1GqwQT2sGE9sYeQMDExXA_CwTHsfgJnVGxAMLuMtFoaETtcYEy3JcN60uwJK5pIE6i65c_KpBQlhIcanS6XvsWEMfQoxb0utQ2vgXfHUSM
ms4dQBxmqbcnc7wdWqOfdHLtYTz9gUCeI6VTOlgTe7bgUgbp6q89fzc1cbxd_Bkxyy2f88fXuAzRijp_kjG7fY-ni0OHUYVIYoRZttPOudbsWp7g4mWCh7Ex
tzfd7-hoL20mK1cUtHhJX-x6PocMc9vTrHhJc-tviq1We78ykpMcuwtw15dYU_RUuHrL3nCA10O1p_x-y6RwB8CbhcVlhuARk48iURvdzpeLFscM-9xzWxEi
YrSGblYUtHnJNUqAO4dOi_NXut4VdmLOalTixKlQZ8308E7Pdw-2-Xmnc7dFrlVguLpZB24yMnzkuaesVEOykuo7StMFBElPuYSG65XSOJrxEWIg6lZCUhPO
agZZdFHiVZ1Lf-MNF7kLP_iiITQbMC_MafUkA-dP2f_pTMmSte1dAp28rsbj75x3imsM06DgUBOT6EHhCiRKy6oB9JnZvDarFjiC38WwjyRKzsonXAfhcJAg
JndXCr37oP3HKU9dQZ3vCHK_ZIKFgeinfk9dW2NOAkXxjdzaAMEhXcS70WDeJENPIPRmnYRFJWO6_2geJoO7apSsvTH9bl36ffmwDvYyiJsyAtxc0WD-J7Lz
i2HBUCQ8dyd0W3SsUNQI9RonoREJBE6DJPwT2WpuCLKzV2BB4funZsXHdw70W3UsqfwG2vzvOtiXIv0b_9YMzeHaOC2FgVhCiOHV1NLQQuknX3SszNa-N8E3
oHkR-lo7TIsWJwGce4-GCSflmniG7zu3womofi0wYnWRiCu2TPh_D3Nl
}

sprite $image311 [116x167/16z] {
xTY9ZkKg30HGo1xRpFz_xdlXfgHSEJqm9K1Rr-phKLnjWZgqp7piCGnDtCx_iuuarrCkKuvvb3WVMSpgFeqGfpsBGCyj3YWI9DJUjIuG4TGwe4Y4g9Kh4kbU
A_RZPtLfNgGRArahFrQYLdO_VFYzuOlq0ruwx0S_OBx8CYfRvCNenjgzreKJ_TxmHNQlDMwao1-7haXENGQCrTTAxmTl6ddGyQAQKVl1HytC1XM9iLgD6HiM
gLPbhYsBH8YB05qaCce_dXcr7y-Csezd1ko7ouWYosPil1y-0_R3PUHOaRxxKJPx5-dDkNkHoCWYaK55UdC-HuqLvZJlEcQiCEEM1o83nehSxm-1sbD4CDPJ
LAHtaJ0p1RLJaTw4YW5t6AitLGMggb1Z9KnGJArYnfdVAY5o9b4hYgHDebQ8jEbgRJvMRtgrzLYHxSkihrMDpoemdOe1DnCH4Q2r0qQHV4vzLSMhlaZULAXr
jJgHCGLgJQt2EjxKYbhviQOtqse6J1UP3dapJQMaAYlA4exqOcf-5FtBW9KpasuXXDERQEldMiMCCuyOVZ1L2ggnPYRVJQZogWfjIlYBYTwWjZ7JNZ3TW1kO
Qy5q0-RDXByx5Km_OE7Cf4jKr5bXgdofX9biZ-5p2gGZX3YLJ5_hFvj7dkUIxZhdEOHm54nNwx-PPyY9UjUvBI64lM3wMhEf5MRILRDvCtgDjTRq0nQfCFSO
3UPyrwbphUdLycnrlcg46UHJfnLDhqhLUOipP_zpmDnIhZCLJL-hL7_SNiL9ViufNjzzwYoQ7fLwCrvEDfSb3_UywYpFrgVQb0kxpLpgjbrrCgOMp2Jog3FP
nStvd9tcN6fpCzdsEN8iBLTxbhAPDXoqZKqST57n2ea6Kt0QvTbEOkrCZI6VfgWJPfO-ls5ptCrQcHZeDLpK2JFjs54xDBKr3qmmhRazcAQuxnb4rlJ1SEqk
5cQUG3IadOaBpv9G9ypyOppwcETdkEcusuDfDYsQkfWOxfzSvvS9iRs9uM9FOI8TJ0mNTOumSOLTSfstkMXF4yFDEJ_cd7_iQk8oWcDNBLbV4yDr9VOrCTmj
3JG5TLQR45aJmvtKggC8RUPBmQesr3p3BCa6cSXfoGQR44UQoA_vQ_wQl-Ql-MicHKJ6cCcsmS-Px8ZXyVyEC9FC8JnCEKNwcadNSENHfvnGEvZuf3bC19_7
x6AcSmftllh4exOtaomXU5D5eBOsasu1WOd9EjMPz7wycj1GQpCpdJCmFrke-A69cHH5lfc6PtG3viracnDzdtx0l9dICJdGdGdFPym_i2OEEXVN9pHvu9I9
Wwva6YRhQeL977G5Ky2uMZzdb587NQbFC1wN3DFxuKq4ZCVpZqhiHx5F1UDLhUup6VQZnXGmljQB56NtezpdMwsAFidzy2O2nk5NL9NS3n_nx-oNMWLz4llX
eo9lx-ml77sMBWArsHNg5-CVMPJT3v_vKBtHdm-5_1lbYq1z5lbMN_3STir5e3xRvVWFNN_6y_lXCw7Mzm6RkJxTVX2PJrTh_i7twVU3p_fTwnDtVRhzO1Ct
_QbMrwUxADEPZjTQvH95wuhaQ_NlRDM6HVfQ_O1Fz5cu2B29Rc_GPzr1nzVw770cHTr5kMqMrEhUsUuYqATMlBEfWuwlDMyBiH_ytkInAhiVt5ikc-knX37P
15S4yXdvlR5aN9DyhORB-RYiPzig_mC
}

