sprite $image32 [236x176/16z] {
tPpfrgew343RDFFxF_3LTIxhKqB4KXHX_plpsIRf48BbqzHQMsjqWsK1kj5QWrhBURah4aaFJDYWdiko8R4CGDXgFO5ci1mmXlgxqMJP7MhmU-6Kpy48b_QC
llLmKMJv6WJbC03bst2hbnQDkiUdxYMJ6LWE1-jNGYg_0KFvB43oGs0z87alPzla5w5FsDODdDAsbKr8FzJwsLCMHBxcsieMwawwbUNtNGNtC2MHCxYAj1qM
txEu2jV1z1rojHlwDLSPIMGK6NFr6rzn1RqXDs1pK0zmnMskVcFxdsyYRxj2mWPN6d7TMBKa7Qw5FU7xhY9j87-ZQmGqT-r6FQ3mlgjGvq4fSSrfzZbNmuwu
zkKnIfVh17tAbVfo-0vqgUQkEVpAbOdQZJhHMaEYTLUf7VNQASkosRM0BhdIyrMa4jVd1th8gQj1vzeqWLjLPMllWkC3A5oyT4x2CrViNuSdi4yrTuMIqXuy
N_ngU_6uHF-7ElUSADkl6brLSzjAwGEOockDGC2auT3lAjYbchkwSyrjMtrnFroJ0LhhYJ8bhXsoB1sk-LvGYMgQt7h39YZxhBYL57HFN3jaIVfStLgwPM4q
DVC_J5_kdQs-MEeJrvvh4qg7QtPsGtEtXNy6uwvhwUS5d2LuPVSErsoV1UbodU2bWwB6anfeE5-e-HsjeQopSYRtJbUf9LAbrzLqjWVMkGujdfWjd1huENAc
o-NMpFjTkKIuttLAGuE5yx2fkMi8ooGoivrYYEftfj-bBIH6hwjGKgnzhazfMDMVC7CFifLLvap1KjNdnKlqCUJilirLMipWVjV7m1H-DfqizFKUEvLjZiB2
qeOThg5aUPlhPAlrASVqmKBVUDgdYvBJpsEuKcZhSgMmpMzndVZRRsxOimMzyyJFV8Rz_JpLcUd2jXbSqookCkJAZnTO2nOrEopcjgPFFOPgim-XqrN2WUaL
xGOzO0-k_BIBoXobv18mGoqnlG5Fflskc8Gr9KapNbtaqejkr3LJ3LUXFrcLFjUuFD6GQztQh0Bk6Et1oJHVqDvfiLSPS7rdzwhzGpLnP8jDfDSr_Xzmn9K6
cv0LIGBKQWbmlsiCh0ouXfY1QN8YpQdGaFwdfIFXCEGgVVCjjj0DnOMBY2MxsoWqv0eXDtgfYnUHvFSC0aEk5DQIJdZvXcgxXRK-BiOwavsn7fOc0xIawPzV
gVgWfyijw-3_bOPJEFPOB8by9sZFjnhm4LagPPSK1lD7T0zLqF2Wmqq662jNceuFdgXYwICfYQadfKE1hJkKAxad2GnbA-Xpw9-_RAVXg2jmPjhALi1y0Ipa
8u556dEj91hITt3yiseeYN_kYZvIiSH3hl1yd0htpaxoahZh6vAxoq6qKbdsJL_CYb_ftyUWSWnOIe7OJC2nVIOl2JxGbSiT7YhKcBvvISWKwIEOzbVTvLKI
MLlHHGzqXNchh9Njg4ya9G4YeeUvOfbemwyPhEzTUAYhb3-G4zF-MarAuj_M8qVHoaxKzQCNoDILFeYo4xn-z1BtCLSThjWC02IwWm1bbUJc49DSZtELkgI9
Olw4ChuKXYH_Ov8FgDhuUM96Or_66DPSBQyEzU4KTf4zixYI-GiCNxlc2SC-dCBsZYlN6PoinPLz5KfSWmWjNWbaE-zzK2jTwVQsQJuxQZ4_CQXEmqJq3B_h
QkEkXibOU8922InTrwZELRrhs2FspiTTnQcW1IKpbGTKxTMijoN3aq-gEk1gxgxZhe95PfwgoRgVbIqikPhXOyAO3BZw3HjsnNYUVO4cIp8kkReZk4_8WAlw
dNvNCJETLnLOk8qbg2sMBKj0lJtiDpBYQdv7Dqt1QBo8yEnlGwZXIqQIESHa-fCUEuiwv3fLmJRN-Cz2qg1eajdIg_yqryUEiSf4noHNU8AfMrsnfhCyi39P
a8mFKtfVH1bozV-nRQvSq-cMjZA-bOyFGzxDmG5NzGdTuWebeSPmvtE8SVTfQOUkqcPNzmdhT-MI0d6C9IzRgVbR817WRQxgVsYdgzQLBouWU6kUYUk23pAK
bBR9rH_fSwqbXKtb7mGrJSEq9XlRokEWYlskvezOZsiEFlrTgjnUb2s6tDU_9CCNjj3fgjchcyDlIKwscdLVMcoSrSOQX_zIEbrzph1hbTcR3G-OCW7KlqHc
UFY6Lqu-UTp7rOAh3RfIUBLX4Q4xW4zNRFE0shIlZRggHtJ45HVAFx7L_3yJNq7ZSLVtBjcjZqrrKTTqnTGqFJ7tkvelijMLWsdeHcJreXP5mubvnDKyOPih
p0ZTHbLBSiWIp-J4tE-gdc6fw_WChAfPVFrcOfhpfnaiga9KDxggvzZEhX6zOG-ewfxVa19LS-pJhZdxkwg_ngxZghw6NSLL_Gq6N6EtyJ1NzRVGVLpLtGzp
LNyJFPThYQxclb6ste1k3dJr7apcU3z7kQfteaUu2jtGRfvTpHFKC-m0ru5_AQZskBgTqLKzX_q5UZfNynn3VuNfgLpLNw7GjI3tyqLNDNy9bT7Gx8zjGinN
mAA-XgdyFkghrCA-Zbt0rAqKy7UmSvjExLVtSzkg-LkqsF7CCJsHQMIw_PtLLlrjkDmnxq3FOHg1SWUz2pj1yaPiDcj_ebHMxmJ3uyHpwAfvBrOcV0kc9n2D
q-Zasp0zWUWKrWdphPZ-jcWSksy-WkbFUKOqz797CDF3FNCWUNNlf-AhQZuEPU_4ZmTO3zMCQFe2zV76gcQ-8r02vWbZojhbQBuxM2BW7yJkw9t9Nl_7xlZd
u6Hmye9eEgTqFKhWih9GKlYwgX7rAu7b9NfTrOXSLpN2rwtL25zKzQg72gqTmr7dHlg-okxCK0bSjMXRwQHTjrGZLQ-HlvTTZnNAHgfUDwWHl41GhxWWOna6
rCy0brr0kzv6auCNBjG8NTWqWdPbqsXxNTD8K_ybk9PFKjb_1CFoUL3zUAILxr3P_4WKopTfx0TX3ENhDBwqQDGr_nvAK0u5KFmR2DRo2m3f0G6zdgyWb5y4
a7NNSBPQVXfe93fgAGIrd0K0OjL-IIKyWsN-RV3wsjfK9NvT_Fxy1m
}

sprite $image32 [118x88/16z] {
lPhfWgGw28NDok7Gx_-yTzGIjGlJjTxlrzJc9o4Iakdf6L8kjRNUPQVttcejEKrV89NQPXa0o1dCpFxsKNUkJSHj4MwVrUaJCRP0E7IBl6TEjSl0E3Bt5yMf
T77ZA-9MddRcvb6-8QxfMUUpZfYM7tMcALqmLSW5lONq1ySvzpfTKYwjWvZ-VefJ4vGFMnlgM5e4GsibdhTMeETHe12vj-QSLdBgFoeX65os6-Gwt2oGo5hL
k64gCQtKjjBhdLL5qDCmPsvrKgTxzRm0-0k0DlDZaYEh84n2XSJMcIohraobjrBcGQzvohcKsaGMinffDWzrP8qlt22XrRqTIvNB--kUzsMm2rILdhx8AgYX
z6ojv_ikBV-QTyUfcMiNAU5ZwbRNka02g_4m1N9hoPrBO5JENt1gFiN1Sh16sWA9hSQwVSC8kRseDBFvDTJO_2Azb-Eyjtom1kdB8h5LGTD_BvEOaLGWRvEQ
a1dGj2xXAm7Sl1bcFCVg94_tfLL4pNhY3sSKPDucaq0sBw5SRqkjp_Uql62EhEYUr85Le6KUNrk3KwPz4ikAscgX0lhJ2-TNHaHMJssICwWfbt_aRkf3qdHJ
z5FHNe2kJf4bzR3PkPVcThJw1I6_yHBePVqmuQQTAe2NgBrvmAgfjoA9inNDGmsjndsg9t7haTBwrhNswXNaN2IDRlLWe_O0NdJx9eNwRFZ5BHyfU1BLeYK3
rIUm4ywiHWkAQKG-3Wnq1NAYJrc6B14KDTBeC_2QehPKgmuPaIjaGFT7tWWHZALPpBXKgweo0BMDh6Zpl3T_BdeUIJktD9R2eRNB2BGiv1Qe35DQj-8WC3Qg
l0pQUZ6TdIrT6ZqDspUBgRp1dAnrS0VE-pGKKjuWtofkcKPq-vM61eMy3Ae_X0EgkNChxQIyG_fTXeBzWnfDvP26RgOo0jUxCo_L2xc1f1cfltPgYQGURp4R
ERJYtjhgIZkESOLjg-Zo3zIZrIW7Qr8Z8RWHMJKilJC5hgsw68sE6OfhOP1Tcsu3NdEPoT5AoclhxJLo_rcLkZVwIZFF-Q4IzJHB3mjpkAYHkBGgH82MfWGp
BgyEC-7O7teuO2rgHXojmK9gUcMjfbvvg-giczVjLDrBqtfiPe2bVZMg7AoD29e6N5fvA0vLf2PlmW_UhLS5qFE-zTwjzxjFN-X3QpyVFfqsFJuPSx0XMMx2
hQPHVuJOcZtGBJird_j373POjPrNXo9NLd0bj3g-uG2W-sbTzQIdqa5Zi2g5Lc-cXjPjms44RnrVRwtasijoSEjTk4BRqEhI5OoigTlFOWEW96r5RyLJlNYe
J-g15Tp1mDgapxIrIAvcyjRbAcznAY02jH_asEhIIFl8SHDmsxz2gOlFor-fjOoij50xjexwPYUskZJIZgsADwmk3RIZ2rJJvws-fSEzr5TczDhw1NZ72eRO
6YwWTWLLBkYYCT3LgZoWTgSL62yOj4Dg5z3qRdJ5pbV5RDLBCB0ERbLvnD2CHumghu5hbByaagFiVXJedQ9EQb_rUg0xnZGrYsQpuZDEkdF7PEsXl-E5HaxI
obAnBhnlYO5OIHgs3GC_AuPkAs0Swamp3iNFcG5bhFIihi0um5Op7X8goV7LzeD8_eKt397SbtcFSO3LuxRt4VoQUe0hDXGwtcD7gHrZP_WuXhkJXQ_YqlzT
QqZtI_xtfM5JPD-LzYaYgttHoUgYO3_p7Kpp-0Zo2rWmkjyDr_-ZSaZ6Pxtc-xmnHSq-w6pJWnIOVTaPUuLcxoeDTNgIr61cRoYrv-aLSjU1UAYarEbrSWCj
K0-Dsilq5dwmyxTws_JLF7s8b6k7aXRO_Kq_ZFhy7-hv8OoZ2kcjF1NXVm
}

