sprite $image27 [338x230/16z] {
x9ZLbMKn4CJMSEro_W7lCCzZ3KiXwAEEkl_z0QJCTSqice3OrZr35mGzwv5qVLnApNf1gauk7D0tZFFdLFfwbwwPysXPEpYdfAJEjOTvufnA6Mi7vvQKnRG3
jgGSKA2aBAQT77cOobYxuKlA0ULBoW7bIye1FV8mbMtjWYWf1vITKtzsJvnPKfwS29igz_ti-3crcDYIycS7b9G3of1kCT6aEQ0qitXoqWn_TZJf3YXDgYUd
SqeFA4_tPqUJve3IpEh9IJCyEMdI_TdHf7boMbBqWF9i3YXDciL4Cwi3IZEA9oTCkZyxcZG7r9AYVtOycmDAa-x9IPDgCV4bvSb9qpqvQT8i9hwa752QuO3I
f7joqgGweFoSEg0q_VUUd9RKjaXyyPSi4W_JCXFGgILLPm8gTKvR7bW4bbHB0ZhrnT_oWkMS0a91fvPKoriiALge9GKBjQHOePOK81Howej_omuiAKRextTQ
Fr-e9KKB_VrE-nSBjQHueHwcl51BYXVgOSeBjQHueHwcknav1r_yl51BYXTgIV52FKnvePOKBzGvvOLQKhnGIueNwek_p01OKe1GIueNwekV5sf9yK8jALwe
BtvUg2N52_N5pmjrJkiL-sQ2x4OC0b6yMz2-_t6p9pEX59Kx9EORwHtXrG0Dblj25KgfMabg_FYkuV5ue16YLf8Q2hN7Tq3AMejfNwW-DfZINujfNwXYyqb-
fkl4V-etq3r6I5hjj5lorlb0dvbGAqbveVuhtMPzmtFjT9tulIK_cNJ_qJwHJjTYQhQlPb_wvkS-LZeTOp0p_QEbhU2VcbBBgGAmhmoBsLuqzslu_65qKFht
pUMuwfTImzxek9twvScmdFPzRaP7xRJXzuBNrKxx1U-D-dRgdSBvNKdA-VH6nwMlMz1VISfZw1XrfJ_igUicvNqEZ8wJbBgvhsliDuNdOiyxrTu7EdNfgm4U
EPbZs4vzqDUfswcXWyX1pJ5gf-OEKXCdAKKN-S8THEdlpdesxOZoFhrHEHc8qc-k0ynuvrF3qAZ85I1Al_F3YKurzGqO6wLBtmSfc-e1YcB4xbb9Ozkf_-5a
Zj9NZ94TPwgTgbj69tc0OY2CYbn19ocTwW6A0PnHEP19olqGLJoTAi0P7IOfOkuNLQe0PNJZmYKfVv12qQbl88nwRcmxTNE_e5C50aO3IMgRKwMIb081eu4a
jPzJXPog8MoKNqpL7wJgf5C30aQ99ENHBUXNIb8A4XbnKZP9wMiUJAJvv8rwpg2S4WUf89a5pnkD9odU9q-IpxXHEJIgdO88-Z4o2vutoYSf_bzGSN9yyaRZ
IGfwVn7P1SyR9KxyIIJvZ1kLK_kWJXCAdZBA9wby4dtoHeaJVmsdXY1NeJYqskrK4UH-49QJbItzk4yzoTzm0KgMlXg2NCGpTP8A-xn9W6Ev9AK8qWuIurof
dSPz6j50goMf_CJ4d_ZpUR7Fkt3m9_vyNjf0Z_8lkU2zdSORw5a2C2V-V78Rw9n9oX9Mpdf9Ad_b39tuy_cFAoVHG6icgVm6oYUfzscdcjb0Avpu4rREyaag
ysRdgNBYJxlPUUgS-1DkTkMJLFxAMUt4hs-GcDxgiOGctEnABwQ64EqasNnktmvg88g168QUEz7ofxiaV4Y-J6BaFBLbn9-k0xe_JDDrGFTBAesJS_cnHBhC
Rh-aqcLs-yIVhWEwNrBfcfpx9PKkizilgJQpctyiKJOvzuc_u9d8juY_R7Bk4pzSJ9PKsUJS9txOx2ofiWEwJ_pi0RMaNjS1tH-cZpKxI-frcTq-yJ_scOWb
zRhCRf_uNvVPxHF_wogc_M7wMBEpf5wNsUqFqzSrEVU9_-OFQDb_oEkQdFl4VwpPMLB7JavBwZoWx30zze1QKhSyEHl_GrxNCv5zuZ_Mx2ofwpAxVUAFavCb
_h35P4cbo-psYJzTPhV_M2Bi0RMauW5bYJ_iv7IO1ducOabfTZJnqmVKad9oqiIlsT74JvkT9KMRdINbvAI9dvwSbXHTJ18_QtOIF_zCn9BwqGVKak8Fg2N5
cvqbLMXsVm
}

sprite $image27 [169x115/16z] {
pPa9ScCh54Dv8zmf-zzj1lxlReV2XQqNAvmLgAnJkhma_HXhAMkQd-MGJyubJSukAf-ex6bcjgBoFrgsD2jhLhabBxFAgV8DbMD6EKiJ4-YVAMUBvdMcra-v
YquqLOsSBIhxdAqZgl8dIG1LYNAEKJcMtxsN3wDbdrLEl7--d2tdmfSJo5bLdKLEOAfuSiwfwfe5eBsgv7k9HztPZpc2geH90gQAS2_XgUBBYVVFdoHyglXo
ughovSIdYdyl-Qgka9nyLRTI102VAZnd8KKj-yMSlAXvlP0JIufF5PmJY4gVghqqS5JThkRaguhdf4tLSYqdSwhGdFoeZ_L_b0xqgK9pybM5S_Ad2ix9doei
9p_fVLNFCe9_LV6SV5NndFofwkVCa_L_z7Fcef9dxB_DAHwXPGH_gjhUBRvmcL7Lsvp-LdDgAJBXLDqgQH5XLG0hqwbgDxzU5fDSuqwdghdPjwXP8Yesqwgg
kzidUkka-ly2cCqoLURXRfMRedCnhm8y-RE-DcODMf5oGrQFYkRV_b7Lmok7LJhzLm7Ax_Ql5k5UIPkwTVhN-1908yBegzgsNabfoMQTg7z_rxSGiW1jwvNq
oIfzLMlE-2fVIoOcRMDMKcLNlwDg5S33SLLnETkWbTFwgfOY7iofQkLiWwQbzFhFMQDIVrAqVxprDcXbasx_uX6kEQkxCdvKzGY_7xHotEc_Fgc0johS-YXe
MlggrelQ1Xq3nkoJ6jQkgaLgKYtF0Sev3df_gd8HxxocXm2JD0ewLXK3RBqbKeybT_g70LflYR3KPvCVZ7erfeUVgM6WAWegPoMYBAdB_QkAWyiPigMMyLJX
m7BkwG6sL_UFozbolB9_7RLUrlGW_Gy0dAVar2qznVgAgHgtRaSQm9YgzZ7N4fwND80nLUD96iX9cYeToRadWC47080E9caW9ssg59NpgQcw7bK3avCzLHhG
lQHFbGPqB-bJPG4yvc3m3m0Bu5u233u0u9mnl9SuHqTLEAUVItePIwCga1Dup36kgWLJJlm3mEBIOuvsLIs0U_cYgT91Jk1UqgVAui9ZZdXLFV1xoRgg_PmH
OpdvK-M1oCcVAW_aCSUVAW-YdFZVAiG3UCoXu1y0uW7SI_vKYGToB_bJvG7SImRjFol1IU9VLL1E_bIHvSJ_LW7AoR-g0Sh9dwh07dDypf-xbny
}

