sprite $image92 [118x86/16z] {
lPgBOjmg34GB2269_F_lzc6IMBEvoXBvhgVlrcMCZWRH9h-ogjpBhvjL-lWhkjUKnY4PxJxFoZ8-nFMsueBkm5i8FM_1syP_IBZU1JHNvkj0KLHUcPPOxGL0
iRYtuAtylYnqqsln5bgUBO3xaXGrn5PvBCbVWMDuIERJmkM1CTDVCLX6XsG-BM9SV3_BiQU-YJUV5hFktaO8N8Nx_uItyLgXoyTszOJMAhYI0xvQBvsMLQt3
VaddmE9rA6a3tve6oksXr3QvW2kkJuWtbnR-qbOyJ1kwjlYmfjniaOQ_ISVApbK8D_I8jsPcYqvnEJrU0aJdgl3SRfaHZRYyiDlQuLhRkwhReNZWj3i3yJtf
tB6OFU3Xjtdej2bZgc2UenaOpvPU092O01wIyw53tUnuRYgqGO0t05hnm5qvhSZ0hTFKv6m3z_jRAIBt1FnUhxNr1dizVrLaAXoR7DmdwSbbuG6GF3vFtJ4s
6qxG1W7UADnY02ZEEfa9cYwy5V3Y38olrfZJiWpqdqogJyk39npNyI4PNwtL0NAk7T8o8iKfek-lrZAjGv1v3CAqe6AyZpCmldqnKVTzroH8ovAudyhw0L84
laL6eFubLyq3LRJihPPLpbeRzVKQPgu7W9wgxBcMujA2GBcLBvben9u7go_-rDZs5FkMxv0M6S5T9GoOpZbL0r-nJq5R5UREdxTXfkhB0NjsFC1pkIxVMBYP
Jtf_LPqBhTTK6HqA3W4JcyuLV3ENswvJvIY0sfm3U80dk0QsU1E3Si9yDDTV63042gwXBwJb82pSMuLcPPrkQOa29ZR15NoZzD1QGDHiJbEHZvQRfi4yOqDF
T8rjvPpbXVpfeghllIDH3v3PmEAYQ-mRp-XdFL0LqnAvecyyesDHc9RO5NtZ6Hq7B4pBfglAtepUIala6ll6CnezMtZynQwnRpoZexGWqDXrqnTdj2I0Eedf
KWwl050iRYmhNPToU5kObbZ7szUnxOltPBmix1RtarGJs_LLZnUElztYkjOZ_G5UBiyk2x4OBmUyZzUbA08Q5nVqCxnJsy_JSlubK4kagEasq1xVVW85Cx3A
Jz82Ik8Lqs6M1fh7krdSD-Y-GBIDDv4MK0Pl4cWUxxRd6wJbgTgm3TzKMgxZLPknuEZSrRCPc4_BfHJfjq0fORXpIDfLeB4eungdvNgAB96MwtWjSVnTnsiN
Zh_y8Mc9j5p7QmcWr_5Q8Yq9aQ1h8YtNyLe2w7MybaZBzHHP8YrvaPft7RTzri_fcanBFaKstx9foUDLk2pSfNuXBNy
}

