sprite $image301 [390x238/16z] {
x9jPUkiw38Chnp81SF_hlOE_sf9RgdAcXoJ2KmzzfkfF20PYlpvO5zhqzMmDJRQazaCGPZbzFLL3sSpiqdYu2BPg_dgcXa10ENmq4_OjwfaSXY0ff32H6mF8
NK-nXw6KfpQ5PCJ6WEwYFSiUXY7arA2GLHZ8dS-nXw69C70AASp7PbGJUIo7GK6YL5DOSfbE8mP6kSiUqvQ6qhHIa6eAiznvATDfCOG3aGVPmz1ijgGV52Ru
AYnI_T9dIEJoTQy619Y1HmhoIaBSZ0eHyKvx6CeYf2C5FqfO6RGisjsvtDcM1WMfJQ6ePT7Rh-QRE0nTpAQV52OsAB0sX9Z8hMrfv7RvI06kY4An1yf5QmnD
lCscHsw78mLlKt0d87UsBDfTl6bg7RbTcq8i8RReZSXTRMbGk9oX8DekKBI7sCEWiFb2rZaAA1IQGnDlpBm71Jz7GU9syb8xrtYIFGmAulOGPg0ajNADnxUb
GQ4O0gLLXBHJ01kvnXLJww2GTO82iPruBIkASWsSjOT1mRrBeHpjaGFQ38oFjeT1WR1T324WoZKUsfO61QaSRoNMLVVWCgZBOMZM2Ghhbzk9GmTjLKfgNpty
OGz34xnFGJ3mkyHY2IWyO6jL_2lNY3FleRIuToc8fGjL8eBg1a5rC-9VzZ2KvNqAX4Lki5SPKK3Zwc7vD0wNrFiDTEzJe1KL3FrgQry3wPFw_TAvUvpWVeQ2
6BxgutS8AZIjNEEJGWt237Fx-U9-ZaBB0GGBgjM7wzYYFyiU94gvFPrwdm9H1gDosWGAXsfUOiM1acIGMbSF7x3ddLOAafJRpQXB8Nu3R9VEmRnKE6aLdMZd
6fRUcq6sdFwYaCozIq6qlpucWs4r0DRUrvZV6GBC36cdCFsqwEpUf51WmABWhguggbBHl8J0ej-xBKqYgEcRGie_l72cTocqHo16Q68AF1ABSurbUbiAadOA
cMPGO0WT2cKmOjXbg7v7OW7MNgbyluNAEQTV52HAmNJQf53bH0V7PUJ3sgi5MEJa6wKWrtYpgNLQ1_7V52ILwRH7uPYPyZ02iG09C84gH0eo51o6mABVhIrb
meYT0irOKvZetgSGZK2bggZZCCpuuhyWiEWtuv0bQQUmc1cuKqXmxrE81wF3r7-e1iWwrVZguJtiuP9-KO30qf6oUvz2VDxnUDeYPjQz4sta6fTtoEr-KpWi
LiHgToIT_wXcXseyu5PL5ej-7tiekTr6WQ3qTQ3WVGgK-oyVLd7PABR0wRiViM1i_npAIuSQ4gYyKJ0pmvKKZgjUXK5zeucgMk0KO41K9IfaLBmTK8Zaryxj
2WN1e9s2jIZqLxssQlW6OF1QZvS22hBgBsYlL5vUEhSh52Jj55nT2lrLBqOH1XYkmiJpgQA_WUuHaIMzO6vdQQT0t4G1uLZpq2eOPdoDN6D9BvpRBMRW3HJw
grwzZmD40E74s8lMIkNykhaThgJGN_NQJZk0GtKzf3_silsZejEhKf1OEXBKet1-rMlx3S7anF9LaF5rnjwL0Xj3qv9UbO8A1UzGwAnwCQh6cMdXK5LnQkob
WJ0sXYPBBqM11bv7eR_g1Pwl7k5SCVPohJPNAlKAzX3aTgSfz5Uz-jNUW0kT77lRLm_Bz38K863lICGP2krLhyuPGY65U3pzbvjptMzRXs5uSt5CKdBV_t7F
SfIkKJ05SlI3cWtVjjxzjmYOehmdu5gZhx4S_XOATQ-YWyB8g5SWCgS1byVUTb_ZyczJA6a88r1xr0jy6DtvjTZxlAzn_Wie75wZKAkAGDuQzK8WRW7mNekz
pKDn_kRsSBn_FhlOgnJug1SlJc6xOs_K0eiMs8EK0bpsNHJuNfev6KXg3I-HsFj8mRozzU3BFq-1R3Ql_bAKDVwv5GLyYgw8-F5Ven1GU-Ye5px0qRlU0IF4
tc-18U3Mm-NmnXHyBuMuirVmOVJi_bg_-kknTpK7Gm0Yo-5TAHJrKmY7wzKrwdKVWU0imqkn5tp1sXPTPBQyAONqX4922jYPxXhreXlzFFRYimLc97kmQEnh
sF7lfz3emB5HBzxvGpVWreCKLgjlVIHYRsSFbxqK6dv9G-jw9_AvdR4NzVrnE2KDVOtp-t0uH-oaWE4JvUGu9_dVtjYBWetGfw5ffZsGOx9FA2IWK7RvAOLT
eruGThfYBwDmiuUsHHDxcFhU149X_rgeSW_EWc7OAHpy-Ga7xFnn2f4YAaD08c-GMfT8lHHIbP2OBxmowWMN7c9lbLyv1K-vBDssHR_1Yq9Fdb8_XHIjLz4o
yL4lVi81FvNvaQMSS_bLsnPTP7x-IKFefm2g3AznX-u_vEbGwY3sza6mo5Vz_bLPN-E79WGkAOrHgFwEW6O67VNgZwSE_mkoXy_qN9Hk0aC08dFj0KwcKGe8
0Ut1w6Fq_b6lEnbpeV9jxDiGReAbYnRDxK5VZ3Y5nDvKJeoQ7F9qHDPtmW6RHtU6K0I_AjbwY9dfT4sfdm9J6AM0OUUr4mvTmSW26TmKHhOUykHqsgQG20LY
3qp-h4Vjx8G3f-3fZW7edW4IoTCed3sXoat9AN1xW7kyYEpCy4EUHArYX8gcHUTVccm8M5KCEaQz3F3fmNfwV7lFCg0yYWoA4VbLqQ9lzAQbKrGLOQfU1LBW
70pF3_9HhufXzremywfjI1aKXHcSaYvVkCvAfwWgpbSKzibvZwyzwcNyX0FA2dCm1AP0GxZAJnEAaVEekPeZXNuPer1avZZVvUI40wblO0X4KHd2LJEE_HoC
CYWoOWZTza04PnbWiN0PJwVS7dBHPKOwVMO8o850s9TQYKMGKIy24GoXNsvtnUZmquQ0yaYlonyyrIn0RDIBLpNIhkXIV2s4EFraEctAF1KDboLhtzHTnpbH
RaxIQRTkNxTCIQUS0SfYc0Er2EyOzK9vjQzF631DIgTB44FGS72Z573KwtwHEDb08EcqNyU9csdS450sQW-S0X_rGZb9fpjbnpT9ftfxw8ux7aJ3Xe1gPjH5
sgu0gUm1eYWtQdD1EYMAvSzjp_15d4vH-jHgxTX3uwavIQT3yXFMaRZAZk9qgYrBoC6UngMLZdePAKPZCg1Gi0zC1HpM0GRAr6g1wX_r4Z4eUbWDX-_YkCn9
f_BKIYZi7VKICCWPAVpcuESfwPJBqeYSU2-NatGwoW0fLBUD7UM6m6NkQKoOMe67Cfro24YX2En1rgxW44Ofu22VhS5bWdGAgfggG87OGtyw3Hzcm2bmkTMl
xm-kWaoJJekWgGeKlZdqRSKT9ORWFau1jqI10X_rqZ4eJyz00RFTUbIaKovte32WiDqKz8QGxV3HeW1bYPo4MvAa6BrC8Nz-4Wu3erwgOeGKi2mjPDGB5AF5
w4vx6LorCNiWKXSZtE512iZ1JdFJwSiKji-Rjgv1FYEZNWe6C7-4552GMjNfr1-qdq5HfZrlUoXEQptg5V9qoYcWFO0XgD9fhLt5g0YN0t8e4GY2aTjyG-0K
eAaXJgUe5ndmieGKYgQcKqu1xU78DjE66Q1s52DK9Xo0WZoTGcdlfO1DZKNLhd3K00Dk3mvzEt6xujHn3dpb71PPkwAXxcA4wa-jydP5_q3gOLawEBWf3G4r
i13wKglFIgV543Y51WPe3kiC0SKPS6NIyvwRJZa5lXoAL8Q06YX6tVOmDPro2lqSH8Q06cF0xM5-EkKKYjOU3X93G95YDCfXIZhz074A_VOmtgxW6cJ0ov8y
dHu_Ng7Glnm4nGWqK8n0ZPwtT3CDqcadXVN2buCJ2aCCE8LFq4XPIhFJAQUmffpJMbO3v-0cO40fP2X7GsLfvcOQfs3kNudP00F8Ou23WsGLYNEObqwvJkd_
9PkB36eIo3W7lX3qxipBqgpDDAw3VzwKYowm6DeSJCR08oKvXqdfb6ijVz8T1eV5GEn1mW0WYCgIFfrodUk_Xom6LfRq4FGSvXl2CRQjNgzVpl1ulOrm43BG
suEsNS4T8I8UTiwn99d3bKPxa33GSz1lfd7TjltousA8UmeMHIqE-46K3xYoj2pfYn5NGP0g3B0M3Cw2aR8aN0YeJS11i9d6AUI8XvYq0WN0G3Y86SmlItpK
Qu12AXIYAacs08K-3cvw1gYivy0tqmPqlVhRPwwiOOjBtLWrE6X4x45f27fxq1i2kdEvxlUBmUjT1gGGxEb1i12azg1DfrpdY6i7gN86l_pIursUKqM1SD0n
qDk3lbs1ybijkj8eslvOQwxCxoaOiuTn1kN2vdShIpZgDQxbIY6dRmgRDoXyOx3L71m0Ujx34CfLdSL1cKwvh6IaBsD8jhOfh5RAZKVHqzGQemi1weMqB2at
qxWEXK9P2xcwhaZXLeXuQYqQAqP5ipX8DzEuJf5IeG3522aKzJ_5TIX8QPbJbZPnEkKOFAxQOWKH2hof4GE6C9D3bc-cSLsyAlAKWaVHg3tmOZIdBEKvwPJh
jAxz55PpXe5pu0oGWwIfiGasqzGKy7awPoU3V0E682zBcs3KIqq1Bt7AG84i1s88H4Db2PLbxGezXI8l4802uT1TZFJsiCdJgPx22XG81y90OQQR89qATRm8
ADIHYXk2WeCWdIfrKb30vH11giUSifG7DjEaEfoVKmWZ50Y78dBNpk6m3MocwJaiRGef8enIu1n8zT2K9O4XwEq1AIHeLn0Av7JYz6TUSJhLsuD1swXDuNXS
XfQ3tXwoODHBLfQG0d902jULUnQMfQ42_zx5YB-EmH53cyB7ihPbohB4AGWsquGwuaqSo04fdE6Bvza3fv05csbQdJlA4b8el_PuMieIUz2dq_ds01IkEW65
Dx87lI7exG7BKasXw0ZlMdeVUz2dKtrgHGv0uQhbTFcHfuTDU3BjpUtXl_REAzcD60Q2JkGoO7t_speeZmCTjl3wXU6t_hg4XWOeGIWi7bkM4ePfk1uEK412
ZQnX6Xjgj7w0WZwWQqteJZ4z7A00X1hPmpGgysuB2hWUWEwKqaDVKC3r09oPnKAD0nI0K2EfE-NrSAOm3q00Ges4xXJlMcUCRV6uiWG80SoyTGXQ5udgquOQ
G5m1bYLz7qKWf1w0xfGCDPI2V03KmmuL8t9JGwSyxtazF8jX6hV8zrxc2v0UWbtrulLGX08IQkpuC8tNGn4zvvKbLWZFNm-L_FKGU7VAws7zyZFlOE8ANW-h
bw-7_nK2K8o0FMyWrDZfxfGFDNWE0G_JU3qaOrXpYAVgJgs7kQ80TAVFjMjDvH2nNZ_D7wPP3oCYw5KlbwLvW08mJAFVfpmApAgNzQ0KcDrVXnfA0LhriXwK
0hNgPJqe1M3LotfOKSZlJgs7-lsjAEHtfzP3BQUte90l19SbkUeg59AxKuSQ-bNe4RtUE2Y5_FzDSERT-bRQxLfPgGiAISN8NMkJGvOdGIY5_66QzJ3aPbpC
Ynw4GkumpNheFnsoRENq9DdE7AQvQstnymN540hfGh0UJaBu2KCJ2hdTgVNGv82Y7B8K2YbnXKCDtSJRVpfaAHHoLxsiX-y88XI3Kl0mBN-HxtR8KYY85pAx
K-j1AKmfIKDwfEHXclKmnkU87mzPpbQ4Gd9tQZtqKoaAEMGvIn4AsSCqbwNB1SLzFWYw2ONyxjIXHhlMeeUIj2c5_66Qor8_sJaUpecERQj28Lq83ZNQq4EM
qIyJ7w6G75TO3qqe31b_2eNCxjHww2CkvqJreciL2cd5o7hGB2dQfg_UAEGFqwo7zft3xAkjiCZlJgs7rjfYDmyOfZdpLWgC49nvAmMcEtNchHJeLI-FH6Vm
mpGlyitWkrFhOLB3D9SbfJ0G8JZKK0hz7V1SbcWAVf-U7GNhWQVWK8EdO3tm5Ao7vqJ1UWYOWlNmN2XO3yzX_yvbwTK7sby1
}

sprite $image301 [195x119/16z] {
r9T7jk9040JLjj9m__FEoBV6_1L6D2vhftXa56XwwqdbCkReUVgoqza7dWv4z3HzpydJ1ECOsmm06ULh22eYmR5D9MO0YX68xu18KxVoZ51HfhnqYEB2ONv1
cr97RWi2OHjY12H419SFt1wYoArP2RObswR4E3WWtRfDDKfU4ReaxHICmCbnRoKW5BasovAt8rbS088RXzdINH4SHUvXwO9WOoO0pzs4Vbk4BDcIJuHr98B2
g7QKco8qoReWY05AqYe5xgq4B8y8omkh1TeZpjs4socHQ6j4i6KH2u6Ek3czAj5kHT0aNH64e2HgZjZZwiAXziV-mVxLW49RLmJ6tY4j4JhZmF4XY8n8bpbi
wKIGj8YyconiqUPozGWUk-apRMfM6SOkInvL9g2pGxAuHivndOVTz7Q85gbQ-IXJfIrxG12sudWh3ey87cQVFzTYps_LGExLgXrbxTG6C2BmACuP_zwlF9n-
fnAvbwH7grQdss-UHG8F2EQwUzRAq1hQitPAwmmPHvKeeRu78OGizmPsFThKj06S2DZQOlyLTTHfa7oubU3hbQXb2YF90QdBW2sVPxpOAmA76FCP8Y3XJKeq
COTHm0QhRJjeE2AszbZaNr5pNCYuIuE0FDuICTBh92XJiqiyqAWM5gGHODULnnU07oFtDbcuxAPubH89hDKgdT7iNzMQYRgajWw4RozWgMJtlF_Rta3NXurY
ZfeUoCUfRCv6_CUgikIP2S5QW7dfhc0kvRFbJCVuUfwPf8Ee36QYjZu3beW8fkKxUvHB5L5m-MwQq2vv8DA-4eptin1K9mzphcmHuEy1SDbMY_INlCDLsb62
bZWS8Sc4eCa0X-0khSuoHKjMLhN4umo49ORCF0AqkRIID86Zy4lbiZTBQELGVPo2a0131w6tELbNlM9hWC3I4c8rIiXuEnXXO0Lv1131pGTRIy76afqifE4O
Zpy5Z_1UgM9M_L_lblsfeIvhnp43DDbqe2LkB6-F03FkjWuwIucWcHhUIzqS8Du8Qq_BePPu0DP1g3qHrRs_xDzB1d3j0nS4KLrnw47l72FGpfKLGLDo26Zk
1RTSxniDJJs5IRBSq-JuUqiyETft46Z6PXTuNzJDrB0vG73f4TGMBv3ZRornbsMqztveAycqRiN2gO7BMaFrW2ndkgZXW7pVSt0iwo0i0jya5WHiR5QRPI8O
PSgz8ay4Plv79UHRIt0i8yK60lUMU02ptAYmEK1KX3HzG_D4mCj6P7rTuwiSuji4l1UywD5Q5ix3fjsfmGMPsWnGHt6anjEMlp01H_kbI-3sFK5h2QdEHZ0r
K0O5iui051WA85sn_K7AUgcnhlImL_Mr3wVj0QA2cYGXG3R_VNe1kUJT7TCJPXM04dS6JgocnTEzTbHqiOnjrP2RnoU08lTlWfG0cXhf1iGwO4NT3jry05z3
3i1zEXSylWjIemzN4lLvv2tXj-a625GPabGJR7yr3xk3r9l0GsmvkWQie5DEmYKetWxgJU05j8-Lj_6v8qWzm4vBqDdDB549RCRo9jXMzRAGAEWcd0aePmaB
B968u6Q99OPSa3hvpu8CjoGARAVJRMH9EXDq3mAsAK8GWTAcjCmakI0D4FATMtoNiZvt16cLC_NFudLigg3gY5s3z3C0M2vsgmZkPpVrJQ0f8DX40D1QGceu
rOvQNP3603cHW0X9b9Re1oaqF88j1C3oiYi_qQ2EPZL8Om3BHU_DFYbQeXka8S2iZLZDhzTh3I7QnX1hQ8y92chTLmHlYQT-RWB55WAGNxEAhQk9imHCHNMl
2VAuhXONAdBl16bOGtq4mCgBQY3unNexx361bImtN_2otW_IxJQwRY82w2CGW7BLLFliFK7Qxus6qVSAwcie1Y22Du5NnWf2tx_V0s13h_qPF0IOWf-Qm2FG
1EiZw5eYVHca7c6Isne0x321Gt0cS13hR081TWMfrtDuZiFJLnEmeuOymYQ0jyJNGUeJINAMUWuLGeCQsetWBR6dXcpSVXYTFfbBSWnykmoFOCiBtWbzItmS
fDK4NZTz_Pc-cBCDe_GEGZu7S9i98SpiqnhIn_OH57umvpG8AqGSH0n00YU6QcI96C1-cCaKPlmUAqa0m458P88AuFNpGMGWDa7mqW8KCXGRAiBAoEgHOe1T
bWXC4BsqQ7cPplyHy7uJK1rBX03WobLJ0B6lc_0QhRpUnv36EiNRZ23U4e49E1Vu9YEsn4z1EiIFGreoy7eLJR8WP5D0H7tz12Q05NfqfoKCkuBKwv5DxMN2
dH9XukbO0Zy2v7fj1PQ84Lmt4J28WW0LOLh0Eja4Jx0z5tZbm0n1a0RFxQc7m17T97c8VWt57jrgNCEnB4QG7W9tdBFuDXpz6l8UZQk9HHS7QQn1n2DGC2Au
WsW130uWjeJdZ8CqziCe4OA7W2roeqraYTxVZyUoMCya5S6WaZo2jqHWrT0I7i2FPVjrOpKj3OQq2FAu9V6MsB9gR0d-ZM0isw_xI0ObH7iATvzRwY5o-RoJ
AyKGZ6LVwf7SGTHJ-EVJYGeXOaiS4AIX9PGGH9WO7eawm1A8thTYnPPWDLKxqobhwTUMYCUomopXG_MOQeg3z3XB4E5OY3X83xM4PHDNHrzR8kyOouwqXBwt
EJp3WuWjOJWXI6DBKFV_FUIlgyaGlsyTNqsKFFoz44Dqp12CPMTL4nkaMnTXg-UO5yMxEHZBpgect-JjiuHlC_nOThhOXaUABP4DOJTnkYM-Xw09eY0ztn8V
Iu7rZcc2U2mxtnAVIhFFpkXzwtonv_WI0M4tSJbBU8GmI2zb2P4EmlT1UdxFuJKEmoWE8GhIQrbYV8uo3adw20nIPu9hMGA6oQZ3w1228BsE9RIy_lmfEUTn
68G8mLXsBKk8iH7AHOUdb2X8hrTD0f0XPnkUF8NWVUjQrQHg-SrG2eXmw5XsViyXbelccS568bmdIEE0fHKCSo4D0n62zwshMKBKNWNJCMX52DwthcO9iGBD
VuecIICJAUWcBcS9DI23j_Hy2i5FExYW9KHLcaur6CikQucA47GJrxL4HGYwYSjQeaL8bpP1t8PhuH7yEjsUIOZ0AFsD4AF8xqRWBV6R4HYm2RyOWG4B_O_p
wFy
}

