sprite $image410 [130x87/16z] {
nTg7Ugim44JXMPNTdSdxl--zcF2PXDXomV2dzqCJH1WliDgwHtAH6Uwz5iCHIlCaTS5lcf7flNusetXA4c_GXD4AFiDQIkB8767ONwV41qdiUpVKbFW4YGrx
SebFah9WBvRY2yIAVHIABv4Qzc0KNwMA7OJuCj7mjYw-GOwNMRaC_iatbHU7FqzgnlSekhlttfuuSPMUb2JkGremlPNN1lyTMvZzRaHnIlmeIL5nWpd50qZv
TqEZU1393RzPI3oEiWp6_fsDJrkLuj7KrW4IZwTwrYROdhQCuYaKcBbu4ZLCgZWvSJk4U1hrSrS1gGJWuebKOJotm575Coc75wAQ_Vn8r1gNxrZUqI-yeyIW
8Fo_I8eaHM-jzQ32hqXt3v9KkeUeZ9zucrgAzwZWmZf5XU4YL74LkHpKSg2AwlYXy3PrSbWmgr9UMWp87mN9-UjpGPiBpAoKwPKD2kA1WfO-TOGQO46cKncH
7IZn7nEJqAh0A4QI6Ipt2_A10fTeG5C1kYY9b2G7YYPpGVbHu44WlW9bKC272gZwNT0aVhiKB0ERLI1qBG3C0Gk7BGLZutLG0RIKLWLQ2W8ewtLGC2a5hGuA
Ke_i1nL0A32f8MqBr03_kXRaL3jbnAWWnWMpTZqQAxKfO095rm9r80CmZhP2VtGy44dHoropBL03ObNWWCjGDJeMwhYWHIJ52ythWTeM952l1In0UM0TA42D
2lnB-dLnbzi2gW5bAIWT1aonlTulSFYuGFmcIRSBqe3LgEpTO7LqDAgXF5mWhv7f1XYvAH3LrmLrAkg9Vh-0gpymBkZuvlgpW8Qbm3pLBwLV5KNtBzECUgx0
NFohWEfOdnSK8VPcA8DBLJJnjeoWhXzuz-LZCI9vaSix4P7V1IGbiW1t2yfmmawIkD35zalhTqJAIxqkevNKuVyrhQkJqWD3RfVu6P9ua_pS2GGgRJEDTIYn
RAVo91v6glZDMXmGCRZ_ORN7EPjWSk2KYXI6sq9dJQekkZxzznlkg-AdI68q3AMuEsrkIX--6JAzLSF6GKU3EfxJn5qfyIpNtjE6JmiTCFoD4auE01ebxa1X
U94vDU4xf8utMFNarkDXKXIyO3H6YxLw3YiaHSKEclu-iPOUTrQ697h1Ba9S4zlcuL5RJA-6VTZeoi9ARHwHoOlCs8p_Esu4iTsB_G_xIstkrHwhQVFueeEb
DXlWd5KWTiCPZCjj1SCvuZg9U8ucwio_Zq8fk-4qHaR5cVf1Y_yF
}

