sprite $image146 [141x257/16z] {
xDa7iYCX34LH2H3YCVjVxoHdgnEMsuthSrTmIYG7SiUY05IOZazmAH_DOSKjFLYZk4zxMADhGiV5U8xx6GmW1--ONdPDCPX2-ySX1duH4v98YlmkYQ3-I-CB
c9ZFoLiu4VLIuTOz8_bM97UfteL0zoM3ISRoJasi3u5RxfcK7sFoXVfONXoDq7qXFvNyY_GORtkRx2BvHrCC9f7Hp5Weco8vOXYCqcDfRlCIPrDoOQgfpBq9
XNuuHZsOI9vWC4AN-DGL4_X_-vscR33Xl6yLSscwlajF2RdYcIsZM4fvUZI1VCdaO3AMovEx9f4tjLSU1QnrCbCm5cTgB2HOI-WKYpb9lfBv0A5OIytvJcHo
RM8b1oRkWncO44-bUgx4SnimIKxbQt8kyWkKKXTQi-IbWk-phwt1ujOmwkkQabSItojWQncCy_KkrQ79gqLggVuOpC0CpC0CpC0CpC0CpC0CpC0CpC0CpC0C
pC0CpC1eJvWyry1ysPu9U_r2ll_FzL8x-YE3uC10NOEn1JHOscOZJArnRh3O6awITwNWm8IlnuITCF45IaRT1wF2hRiNs0jJ06cX2B0h1aYqiGJiZa69jA6W
-0G6o4nh2V0X3B0o75Py48DC2qNWenYKiBv4-sDMbohZ00nand881h9cyMDqCmPvWmKU2p1lCOcrs3mMeAWQYIfCHfCmKuF4Lem59dkc0cRx30PCryhXc68k
kmCn4BD81s8GJXZj0gFcTVmmnev6Ey6esJ47OX28f1kC49LkC8KOtM0GKaUOb3l2PEq8KygE65YC8oz6ysFmvh00HU_3LrM_03CmzLTFc3_CrrTwwq0CG-7d
EG3slznRP76-ITpeRgHHIlj5qirVXD4tOMo-Q4hM5qtfYrfZjrlZwNxH1M2t_xAJk2fE_2tvySROQcF2MGn5VQmnDcsCpcBqACQL9iOnFp18i1KeCVD0Mr4r
hPjIHJsC4YqORSso3dr9TOx3QSOyxzwGAhGmEDwh_H_Pcs35i9zsMLeOhw658L5Xy6ImZidRiUid1QXhgT313CU5KUO6QLbW4jSNQg3jXQdGmIXXmOofM0yr
JKvCtzBNLFkzOvpe1CQ9RJl9lZzgM_gQsG-kOIfrop8jIrzJ619TmsXzLQFID2nTJM66uyREBA7K9uFFHrSn92bCVjsQADHCQPiMDPjJcE4TWnE3aeaKxBSW
mFzhmQNEo9SnrXMCDamLIVqhxoMrmipIz4OakfjJ69orIkdnxi8bc5LpSw6xES2fYXC_0LLMrTjS93Su3wHDiH0-6Lv9aKy5UVXCz5wAFMJmkOZt3AWk_l3n
BWxo-Gpgqpiy-5AqlwAK_MeFo9Spg2zN8tZDT2hL4ahp2X2I6z4qZ24t8_L5qF-pax2MVH8N5V9DMRURCNnNz3j_cpCFR5Tk68Po-W3O_thJ4xw6o2EhV9po
ggKhYYxti6uP0ePiVFZvPZIJXbyt5u3PB1a2q5IM-JHodxCmld7ydWG0pMN92EEAKzvE65YSyaLmL76Ov_OI9mp0CRj8XfdTKQ1NZ5BeYkEN9_s5Wce9KLwQ
adbCZ_8eKGf6wN3KZ2HNj4OfNz5sF7fXCMJNc2KQ04aikzFV889UL2PIzI3b0q7vX2hn994gHA9SMYAzyfbIafv9wGwMn8iJyAm5ls9bQeGotIsXAfoofSSH
pEyg1QwLo16e5PNi3FA7ItlkSW9aB6feiXXJQRopOHwDa7id3QUoU9iQRt7pQRmv2SCRH_GL6Ebm_lZZ1JTtc-vmVYjlL-CjRfp3PSGVBKuQx729mjSaZZrn
HFk9YzHGfUJ_pVcTnAc7KigWPCkWB82zXJADaYhM5AJw2wNmjwzqLKgnk4W-bw3YcMeh93cDysF1PyP4IezqiaoIzYRmuH5JAlM9IqgRD2H5SI9KON1jDKx0
uq6SHDQ3bEtM3-BgaVXqC4ZmtK6S9F5J9EdTKPocZmNvouu52N0wotmQ0fWq5lJRpgT9S_AgETISvZgSbrlPgU5uYnE_m0x0iUDGtcvsEC3Y-6MR-_0pk-4M
TwxcCXDddCLjeR5AANzKHLo5-LrjdayRxuYrXyDLMUeM4MMbfDgH-CjdHCHMeN0L6bTSPuy_Kr1A1rG_5_I5oQuneNFA-hcWBunvGbcUyeT_IO_dWdVy6zPD
1TC9b9fGfqzQuj-i3vyHxJrkZypHIk0gs-kAZpbhXeA6eQYJlc6oYIkZ_rAx0fOmDEF39RxbdiIITPbV6yJFEIQmNE6oQJJB4JxBsCRX5fd9LtKjKSYAGIZQ
uuNicj2vFcTt5ApnSfQhByeMZx9U4r1ybbCzKEujgh8SR4oYQutwh9VQeM2FTxFTQa9oBD4asyMtG7GRaigiHsM1X7EB3bdtYtfOaIrBqeNel5d6m9KSlRDi
-t7U0ANFNdrVvxwjKPVV0G
}

sprite $image146 [71x129/16z] {
xPc9agiw34Hj5XkrrF__kozsK14m14ZcxTFtpenHuLCInSaQJXB7IQOnXkyIivHCNt8IAWRfksR44-_lNRPqukcy5Blk2hAR04c7c24zCfnIUfJeD1zECyMF
nrmm-PGZgD7ar4f1FtUNKqtkpfkf4H-YOeRNaIwCDQfp_3ec4KbXpdWHCpX5AYR6YibbuTrSkJXnfcX-hDFqY9IKHNgGkXbJrcTJ-KmPyXhaSkroRQOFPndh
I5szWpU9XLCmBQMD03g68qmic7CFOYS0KknYts3whkkUtNJlZEW5gsmeEUMSKqbT38SwOvCDnVF-JXxq5YODLp6_c5_CB-ONyukPqb-BwN5dgEDduAmjvfWp
XgEabj9opb_Xz7f4SSpvI26EWWkOarTAmmJSm4oOTXhgCaHkTIE27BUjY5DkO0GoDEymxcBQzoGPyY56a1lAsRMPyfRY79_8imzfnPh4utCDgnttCOB1Nt1-
YF547-ah398tyo764mVy00P3_X5CdhuSodCB8zbllhCuvMy9VeQYFu9H-n6C4T84fkKNBayEe-rKIGY8vVY4epJg7iQUUw4AWL4XKfR-UntG7a5RLg9WbALR
9QbYPeGOpVP6CcF30M5QCBKf5Qr4Y1bsUgzevsmmC11b4yncZ2bDZ7f0QJaWn6p6q36g2YcuNGfR3kgsTgX7VB6zBayOgHiCMFSRRLuRZGhQgXkTjvlI1rj0
0FoNrYhqkOONl1NVhEfBqd1JHoujQ6t7GNeTCbyERyOxSn0kDMAacOSmGcbBM4buXu2QGxoPQezvRI6Pxh4m8pRdLmBLEMjKhUbBQjaPAmgu2DU6JQmD3V25
S-w7jb9JoKyWr8sQi9iWt-UzE5NlWKZJjPeElWxo6rMvfsO5yPpXa7qrLPp4OuGp17Qi9Ygfh1kOb_mSlbDpTXEgorP7LaLQDLaOG2riIEuGz1a0NbGrxgcf
JVFkvgwPTzHit5nLDnHzgwQTcxa8RYH4lr0JhseQFuAeKqgedwZ9ZPgL8_X4JMMZfZj-p--DcbIK-ecRpYYGHar7OX7gdTr-uhwQ1GZtYS_ic7cgvYAveB9i
mJLcRjHKSDkqLfJBwJbwqZIYKTD9Esu2FgszPfQovMmiLDMcjgUc7Yfr8gOBG5yfQP-4dANYJFnGJSmKvtpWEAcesrm6n_Aktp9lrydbggPT9R525ZMdWGlS
xy-BJvfB-no3qXRGwTCcLsfwKMCOsHW5dJSilEL0iNqzQqmX16pLNDnSHrMn-tfMwrUCv5QeYbh9kHotMh4F9IDtvrS5q9hfZDL8DUb0pGQ_gsOEddGetgcP
bU8Px4CrRGolwK3UXn1zs2JPNH0jXpOntm6HdBgmc-uoYBIf3uU98qxTv2D8NNYVBbNI7ckk8_VXIkAGfNhkj6MDF7RXHc8tfacWhYLaocCVmq7-
}

