sprite $image293 [231x254/16z] {
xTq7jkCs3uPXTX00zx_TlypeDdysZymG4gEhD-sqb2SWQCafuwvLBkutL9gaNy5iZSElOBP6_bSmc-QhCxSa_GOchEXbcKt9Nvq9AtfHvfR4IpAfFLR3XPcm
efTZOfeloSJaaapiPevtCs-czx-0wNEjL5BqbsQc-X5HJi5VaXcfFaGbHtyjPYWLWi6QC-sN4eB1XdyxCzLzmM0jcVPBsGy6kpuJbt9WiCPC-wLa7XZiUipK
HtwqOx16JFkbvCTsNCK6JEEbP0ojY4t16p3DbXBRZsLM0wRTKevRdq4NNifnh01qwQKSjmembrtASIoUt0MNSZo0di0CPAj4h1pFzCKSYLRMWvdv22Js2LrX
AIqJO2wzbFPC-wMqPrvoAP6vw9ETFVFyfIGoPvw_b3Kw5yYMUVw7IDgEUxLZdh-KsRkFKhLXdl-wLOBxNZPWdl-wHG7_I0RCSvUofkVts9hCCBgKh_-0wp7z
w59wzxfO5sEcIKk9K6kc_NcjSTVVm3EPFiIKSob4HBLRv-RPL-Qn_Y4pn5peMqD8pk_i_T7Ca0ezDF_cmK8va1ao6Cdcvi427SFqCCTHPOrkf5ZjcI7Jionl
7YnLMsOizAQo_o8o3ZLaXWq9cTyycCz6J9zfbfB2bATA2sQaLnrqys21fZFpFALtqmeqbUdBB6Kbek3c5UiqPYmqIqb_YdFVYQOmKwtqkZT7kPN3J6WUOUAz
FQv4v5QTEb5VtcCYSfgoqe-O3Q1ZpCIWtCFi8p-2Zq-xInUPU8TL6oLLU1YokNJxJ4_yjt4b8j79oVZIHIQUr_5X8XBZFv6tXY8J5tfSYKWSv_o1-hoR6IgF
3dC74fXStCogx6Cc_cgY4ZDvp7NSL7OmCqzY8XB7-L6OoMmRjCSiUpUhOdkHoEGuaxb1WGdA8UPE933dEZTLqmwplB5S7IRjYosSt3wIxqo5lGJcFkXReqGc
XzdCflAKcHYP-vtl8gd2rmepcHiKcO4XejrGGBxBv3gPkK4VcVKD9aBVHHBnOtakSqj_CZD3GdlwLD9xCHGicEq7Cp0cTRSJHWb1mezLUoOn9aAq5qhlLeMX
PCqCp9Xe9RD46FF6J7hEPBAggZ2MR9c1dpFjnYbFcTMMcLynXMnYVShaQCgiBvXMpgelcCMIwVabKzb2AQ-OrP8PEqnb2oKmPpqYI8UPUqnb0-LBPZ9aKfUf
RA1ynSo6pDfdgbIQ5elscCMSYUby9wjscMJ7zFmYqSzute7TugEPOGTJXQSWOPYJFr6olcH6wJ5ddTpAei34t3_Cqojcaiuu0Je1YKfaZXVuEJCBlqeV4gx3
nzMAYILvnYpAtN72I0S6kLSfRaf5aKd012VCTDpOPwgVu_GLcBN93YVyTTOTH56eFqnW3XVvWScxc9ZytrgV0a48okbCBEaFfZJbDvoe5U7FH02uNycgmStB
5_t6rDQavnITLryfhGKtix2jgFnbAfixKOafC2UiwCRqVtxBlMGUKhWxp1RTxBB-OORMO9nM0tr0uZ1RSjFpfE9SR3XEJ2n6YSDisHaKYdEfmJXj1YhSJu4v
izp0QG4LtgDinVf7On2sWuhi_IyGoOf93Pppf8ZiArkrOjQ6pZvKPXbHsTYAoGsSiwG2nXU9jYsnPwApJvLX8YhDcTB0-PRrfrV-nkyaxIlrHanjuBGEbVRC
zZCzIxaLR9I-FQJ2HwRjPz666Hfqe5EqFPHicB5XAeUD4ifsJ4pE6ANbGsrg40pK3ecHsGlAOL14OjNi1UKmA28nDdj1EGoAI4oiNr3ieOZ4r9inJQLeF8F9
3O9qZbG4aLWmVq7fImsDzazxsdQd8iD4RNjBfp1ngc90D7_QQ--tyxi10U6kYkLxsB3s0VprRK8RZ6pUmrQh_Wucsxo7hPPOCDFDF2UrOERrcDw0MMxcILam
QJrcC7dTNAvuCqVZzPZfPeucwp7ppUnsC_LcdbIvcTrkPdlTpRoPD_DctioRUJDlvisycJVpPjxCV5tcpRoPD_DctioRUN_hVl-3l_iVoeVVyUy5_Ov_DP6T
HNh5zp2iNd4riRIOKfnDkk33mUNlMlL6JB_KECbPbLSQPd1coM8VcfVVJYs6pBZCE6ioPFggQoY5WZEihE4K8c_9JCJj_BHISPO58bv1IScPHk0yHKdUbfd1
UOgoEDi2WVC49ILd7Fs_gkSgoLipqwbE-QiipZfFVwfonYYP_XQTUON-ndh2WTrozaNQgdgMCha3AgSuLPW-ykx8SHAB7gUKIblP7H9zL4K0QeM4OHuwJe0Q
8M6O1uyJe1P86EO9upI5gcp1DNlePIiVgHeOLK19xhW2WNC-T3C-7Dde3Yp3iGNfZ47YC8ixD1ZdbrId4449zyy9ntOQLNyOuSWcTt0Pd40T8_QKnHrUWVN4
T2TMGNZIaSKyWREZtS200rzF6Tq9HJYs9bLOp3FNqrvPt4aLGoTUFzvTpebA0kKfrr0rLWRdhkgi19ViIOLlJhwc4fqNKgBJvE0oA4_EMpYPuFOvtLcc7zmA
oXNACD1feopUhLCY6EYKhQJibYhIB6YbRoMtMBu0T1Y9QxdQmKNeE3Ax9VC5e0Cx2QDSSg0W7KGcjt0-Fq8h3nYf1BTseH1AkKkiz8YCY-8GYbR0CbSa8d9z
A6Atm6U4jD_HeN9m_x9YeJShoRj_OJwLQnfH6lCkOpGm7a_jJJN7u2wJZod_r9QIquB2_m8
}

sprite $image293 [116x127/16z] {
xTS7al8u48PXvGuIzx_k3dpUmel6q0rQ__6jF86dMW5mE2aguVJamkbqSun1yMopZqkl9vktD9zh8axdcwFJkIRwPSrSSZhNJ8s5cLejAPvZnigxg4qZhpSB
yHnD8oyq4yGvB7PEoytK7Y3qE7AEoynOP_7UuyZI5vY53iHPHdTrqKQ2U07hG6isqj1ENR6Hzh30YpRI7im56sbFtMPiXwAogD5Sj94gDSGckjhCT2osYFCC
rMlwxuSgfVjsg_fD_x9I3hiowngp78jSvZ_M3yoKIssDY9uT7MHMdvcnrAi5SDzyTEPY5NMRkH4JCXoTELmSZrbk83eMywk3BcesKsDwHGeNo_kagiqij6iM
xIGkpcipbaO7vbuaeXgDjqoVcx496qaYRiccYXwPEE06acbBfgjYkJWmzsjF1-QZ25Ib19FQlZURuXMFoVdt8ceRDQHlp4WgSZpc928HKKucLBi-c74xNHuI
fgYOK1q3AaoGTtDIDt5EKBAPKCVeuHg1X3cZ48zDZXRpbkfcLf0mPnNY4rF9QAA-FrEudhDA1x4AqkmrINSV5fvKPOkT9iQ4sTb1SXU4GJrcqPsfR2TrPpQV
INiJg964QLlS_X-JPMS2DP8mKJJDEPj0knX8wL-ft4kUEQCyc8PHMJjC-o6g_N8ta-xHZbIUYqXi9ehjRcQT1eNAtuExFp6RAF6_PkaoeKXLc7d7iIX-FP7I
Ip2K5MOTSeG2tW8tasYOJ6nh3-sY4_gYcPHB3ROYVPbqwVA0wclnWUoN5gmb2Zn65wUgymCUJ5jNSwWuL5MPoK4UKmRGMTLlGPMfFiPWZwdZ08Lxeu71cz8h
ESHZzd6hovlfkAKECi9y6zNXDzFLHFg6sCTMZtOpZtlTgq94wIqJgdz6bErc6UYkgbT4nMxMWLoiTeYxBjLkjilufdxiAYQSpFQf2RVhDK7RkyCuYkmcZKMn
tUHLflpSfgmorMxghspsQ3RxBs3-DPFP77-q-TVyQyQ_vb_prtkFrv_xErXTm7c_nyU-24t17brMVOq_VT0IFD4AKgFBp0i6xIsuYjm_9ha4NutxfoGdfraO
wFiaKN0McKZV9vM9I_3Mc4ZwkoHz5TrcOdeNxLUIgvl4eAIzkyMkSZMJdyIWh50zehur9gfNL5J1saLbxEOxHSAWKBiHLAni2U-LUKDVkXqU8Y9kRcnUtHqC
-exjlSzM5X5GUo0vX_UBGBra2P-Kw9huo1e-Ap43FOa4IZYzXiH6sb5vJHBsSaMnNL5Yov2Kmw8AtrHv8HAt69QL6bIMPoALiBHCc_h82a1YgZ6iha25kyMy
WKRHNswq8VlugrQieh-OAv0xnzHA2lzpATT6MwsMl6Z2Vm
}

