sprite $image54 [130x84/16z] {
nPOB3Ymf24L1412jsVzkvrFCjqc_iLyi-cp0ctZk3V2JD5E4Bu8ot4U7hy73nnZkHl0LoDp7ZRisAATfl1-u2nOBq8UF_r2i0x--Nwn32m4ILJgWk8yt-2ZG
uKM0d84VR-185EeG3Sna7Ue5ICt4YWOMwq2fWRKwP06sTC3d9dXRXte1iWwFJV2-3gsgWUyp29wSu58TOeAFuCO53Jm-r5c0MXro0ujrs9_WPuOw2r2hGvxW
0XqE271igFC4r-gG6rYimoC2x5_rUOAhTKZlb-lWIO5g7JhghCoGhtf194iPAdKGbeOyvYWYdt5T5dDhKgL37cfXaSc4xJiw043NoIhU6zBuGWPZa6RcP68T
iVitT506SZCQrXcnN0TV2rW9Q9dm6Cp5ElYyhWM08gtnijxDgLI7kQux0K2JZjIdiQfJgzB1rtNT2Mv86TY6yH1Zg5W7drUm08Ak1DrLoGNf-Q6Uwtf943gW
B156Yw7sHpyW9m1esh79fM3MUyFkNl1-9FWRLaOMD5Q_c-d-e00HuBBNcr4RulJUPLBIuQW0yRuJl88YsBexgpZVEZpt0TVia0WTWCm6cHXZw73u_M0fmXjO
2TZLo4NIK1yJO3HuH-W0l5J9ZKE7um8mPB8EIpkFGQ73qGyG-5zYgFlKBZeeXlh01mIM17YlGrTN7jJYZ3lp0ODW5-pIG5oryUHswt2WWGoVq4GGzQ9cCkwX
dWK2P1sGYGSDbNJ6VJx13H9xEhIxcIzdt849tWH56dASaaHnnXsOu6t-VSPrIMVShW2N8dnANWTrOnCZZ7KuCy7xn1bdoYv2s7xSpBdPmCzrWFkCcz89GeVp
3SpaCqw4fo90TpyomP-lWwukWW20DWzEyBuE3KJzJW0uf_-eWRya0GxfW60Z4lYSqoi4WAn399WtlZ71Xs5bY0I1-yu4dzSX4WI-Cy7dTOW4mTgyWWytitbE
41DS1DjwJH0JN4ZtDOEL6bW4wboH84rm6Is-OgK9BeJ7clFD11Vga0Ge1ktd6_WR
}

