sprite $image79 [118x88/16z] {
jPcBOgGg38R3DUHFvlrVzrIi9uoYJklssmkBhNmJmdLBFo6cN2fpQ_8_hN6j9QT0Vq1CfNOPP08MFTT_waw5cm1o1o3IQexqc9WNetmEi9Z34sMvC5wR-PVY
aDcLFmV2wUTXLe4y1AtyAE3aOJu2KkCFdF-E3xsH8VyII0rqGwZoHKuJMEveSGP32bsIrsM6PbJ85UVlYQ2bgq1nyNPJkUBwlVDmOyFbsoPt15e9HojQe1bv
_fcpO4LLxcZGBqpBj8yI7IcOMoasCzNbZzpIhIsUP2PVZfLsFPdGQsrXgmwmE_TMb5EfMvDtITfI3X6kESKGQ264c79baUtBpUE9rQrpRO4ShVKrpE_IbQrC
D-wG2dTn2Hw7mQrJRORChAR3TuNQIhpU5ZaEBPg9MvtaBuZChI8gYNvE53FLDhDAf6_QkLMm7v9Zy5nBYhGdi9cf24-jx4dTaM9AARB90hG6Sc8OMd-PsNuR
BMgcVM5DUG5k7L8RvOXQPwiLSfhL8Lm0YsIOYgaxnsPqjeAn7C7AT7Pdm1_4_ZRK_5d2h1a7rKEz8DEEeZACrePLt88FpckYP_MKIYjXI2yhUthB5bZq5NsE
PxPzkdt5CR-nZHNUpGg-QpB9DSXl6HqMIU2mOZPFxINfjeDtiwB5UIKBXeyernIMQtY_0cWTA-oLEWHRLQxWTflv7T6VxNATFBFvsje-JMjBy_Hw9Gb4jd-R
FC3ZKcFFSDMshyHcPf3ut3hELb5eFKilQbKpzR5N3FA4vWDM57b8ub3fJWoVaKsUaOR9WBUbSElF92g2SPa8UcE5tC1lgojqdzvjDns7NZLzQ9Ni4sFXxLJJ
m5ld3YClgk5Qgd9BtDqDL99dLqqF6wAOocEhpv8YaE5K4zlGlFTyCuLSeeOVZ2WAfNrxcQXtxk4_8OBONPkmQMSqNfZkwo7pOX65ldfC4E7no1g7_cqBy_CH
pePjbPKIzcVkNBa95DAu7i_bkM7ieZIrwfcLuVUM2I44Eg6Cmp3YqC4BEB4sVRja9qvqHQZZHM68TI-mZfvPJJAz7NvHqvaoDpKRxnCic5lLN3kpjh0xMiCC
hUuI6MBcDLLukoWaoJChR0DJgpUUu0lGEXGQhxJ-uDML-uj221ChpC7bgQMjpWr0rHnLhCRZYZcngZawjNf2RMXur1-VG638frQr4JsrvbfBoLyqkOLBftAQ
M5tgAEPMX-ME8SQvLUq0Rgo2frQr2RYnwZCh1kbqJDKsGVM3lFAHjbfX0s83UjyNry1cOD-YDdklovy0UqEAMptSVmns2kDeUnH_v7GAmIRUFtMQ1ggcC-yV
EgqHHRKPglWBPxSc8c9Jcw9ugfnBXSY3dOlnIwNQ2MgP5YQPVTBLE8lIizeHrvwQyQ5GrQxHuBUX3z35ZJET2ozHAxIHxNDqeujMx5FKc1nFxP_XINNufH_7
-a0gz0xRRr4lr4mlfO5sLBjOBR3zRGhebjujT1sApxhNoMTQ4CNUEMbzavSYX43Pa8YAccOlJft6D2F1zCHAygghDVVYgnPJB9OeHSglJ2bH_Ifo93QTImlD
2MqQBYWGlxhEb48WB4re_qfSde22ASMb0CMv4v5EoJhnWbB85j9YPIg5gbcY6B9gayKZI_Y1sbheRDHNkYAmcUh1cYAeKbfiqWECbE9IVqaa_hOovPdLRvWN
9DbxGRbIxQ60bbX93B88O4nKR8jrPbKp5Fg033FJqPg4GWIbLwLErThC0YbJaDUQJ0gW-58A-jwtMWDzHfR-YbirK04bIyG0KmGHr_uubfmjBRLiaRXGCVKm
3OFpdjJq_u2_TKePFH8D98s80eGwYa0KOR8Kwc6Q5FeXeSZts-f_T5kN34tKz1lJNkl5PZJbHByXLLmkldfuwCgM0_sQM4NDrzq1rKDj-nPmLpuYv6xkxDMx
nozJS8dqcF47vseNg0hNQOpFtPNRtgwGnYN7dmZ_0m
}

