sprite $image122 [277x208/16z] {
xPjPcjiw3qIBCy4Yzx_SVsWbHZoWPKVii1FhlDsR-Nmgi0JQU9cJavEJavEJavEJL0EkE8dIMljLouclRQDwV73YSbFAHSkPd0TQpkGefnPNsaEomzkIf5rp
QWctIaujhhGT9BsRbjIUGD8R7yCs4j_s6BRfycO5TX-E8MTohc0VOxGpERTAnk1v32jzRFGtBB2salUG4buP9YhbJCv5YUAmuP9_Zm9h9qVn6htYtYGvjXAL
ejCeuL_1ltJct1A0AFzSxS_j1NYd9TwqlHhUfS3QMdgxexXtAB2sbjuUaj_WrS_IqXTi5DONM1iQIlxoqH9g-rgA-mSBx77oFrXWZoFn7oomnwdXRosmvsZ9
xK-J_xO2UuwM-m9xZXQNspgAFvFpWEo-VO4zHuiMsAKmlLk1tQUF_7u5Td_TaD-lmEvlOChx5TZzXNSzZ-7x_MLzom9hFoQtKf9_lmAhS2Zow-pFVrLo_3Fa
vvEZjAlPB_4lAh1uXjAVJexIRbfJzKiBx7mfutKdWtTFSFx6TnV7fKWrqwFmVlPB-BO5zhYK29VgpfmTFTlxolN9cI_50O1Fybc6s1wJlkMhtt4f1J_mMGmj
lPb8-9u5zg2K22LakHyjdGjs_bfWbqYfoUCpBsnxf5K5ThuK-vikfRs8XE-H7AbxKaAkZRspIOb--p_ExYbLlQ3r0_Tc2vCZtibdKbpXw6JR82abjn4_As_L
OSFrtbudBJ-6nGFEbeByQ3oI0Ih5Ja0URB-1X7K5LlzyPqeHuyI8bXI9KDeuSFUyhi06VE3aiPIgnSAIOYk1Dz8p_pjugSHv1JO0XfLjS5-Sr1H3YDhXaqfv
U2_g3gJdvPTdN_vFc5LW2ox80oaoU5FBNBQaIFRuYHSF03JICpb3iMnaVxZ0sbPKIk_tx_PUBlz7fKY9kE1ARm3WH_y3jua-bmlPJIYmjfNhVrM2iatbebAa
f80FzBnAHdhcPoZKyYl9AB37hQWKjWygVYNqowzotk6QnD7Pd96U-JVoYLAkq6DulXK0S8CFurtOgl6MyQ6aLIizypEKo1ijTRgLcvb27QC15rn_A2NKdqKl
RjbYcuBiIM6hyxLKNAXNKgGtXNg-2ENEIA7sF4tF13ZSZXH3otmhb-bnpTO6Gd9GN4WVpmYl7hqm-goBnNqfTnagNs857mZRPyk1p6rtz254ILFIe_iwloTb
mtXO9bhHu_UUPEzJjCXnJBjh3RjIZcGeHvDmOyMe_nlYLOf5xzEkvEEEb6DQ8dPGAngHlHV2-QYIZOGVE5kACLhgD2aeAWNm3xM4BvPoKQ9IV6tPMLBiqJ9B
2kfMtY8-S0zQehZFfSZ1O_XNClIHBTwIOcTeafJM0SJUdNsJatS6hHnDZbAktdkBDwGeOcWv9AMD3Y0D1YW-bjjNnj95n3YTIf_bPDIRzzxg3IdsQ3akHKPl
0E9WlkkjZnPK8QckfkNju41H9Dz82xQKrqTByi72Npjf0CAWu9RusB3UV6dDvwGvs-z-oDzBEJ9QkW7zjPCVKbh4BPKgnNgCekRdS8RwWn7iJ2clZnORSJTE
sezrYZZS4Bl6Hxa-fghcvw2MpaUgO4WnHik-5hkXwlvUfRHo9sLGC-BShRGan_EZ2leZ9QCRKlOpLEI8atRPCMLSKmSlJqCPlNTA3ZTQZFpCwdEqfHnkBROJ
bN9d9VJ-SsveJs6h4HTS_hbw-w9FdJP3of7HOZifEjQWYxSQS25tVL1kojklLnpLoC-SFYU6bEEZnNQYKdhRg3auvtmiVNJzLVkNONsc4gNkIDaVBNN7INZW
HALSu7Powwzwvjfqp1mcIZQaJ1ijwYIhanifE_iKMqlZn66YfCTIIgW7CsGxKIaqf6JWHeeHejmd9aU9ZwK0Y9oW9Jzqeb92IBT7ksG7Kyf6STFoeqeKkeTI
6d96cJ5Q0ZQIHaMb_6ZoFkRDgaX97ieJ7-_YT2KzM_iKbvZSbD4IrScTb80ToZ2DRDG-EJb372mf2KNGfXpFKPqS_NIa97ztOpXN2IDWIg57vXFK9xH4nDuv
GqeqRWod9QS0jfIIwL79qcQqbgnEPdqCNOtCKpAQnsTIAaZl6O5wkBNC_y92vb3DqvBJqzwz3p8h6dp6iUO__wijkQcHcKggmvwKX1mXYFIPJKYA71WjqwJK
qjN8rEG4O5SA8u06E1_f4CYCs5uPBJ9BocJwC9EpBuKr5lfSdAy8BZ83oFjB1KM-enG-T58TTgKeoLDA1WKjGmBoWT6oM8gjX05uHGgTHoaWSqqW4yXwOBGi
b68d9mClIca1jUB7vAL06YeFZ9Q5KZWU8HwlI55GM9a0vo6oLrpasHLKpdMVDhusEH7uJIaP0JMvwX0egDDQ2vzXfXAxrBykXGbeqP4XK20qiJEqbZwCKdz4
2bjZT6I32AIb-bTfuR2goG4f6mckDEGAoK2aXJrQLc0dfpeyYQkqgGxuaC9Ka3TH1qRB8YLsgRU9ZJRPGIfQgqoE51BbcsUeZzrgiizUbM-is2mpmGlAjnuj
78gzRpoU8LOq7se07Rn7UV5uBdLvSXZmMuH6cyhecK141fGPkvRroJb-3B71ExTjeGfp_fR7SnzMgJ-0AxIH61nTOaCfWEVhMXOb9-8WNcZJ0gEde4PKdrx8
q04jHvNOfNxQyKn1YgZ1DG4tsYjQv0ydnoxrKu_d3A168ABoWuAsFaDz72hrnpCagDd9vGmgaDMZXOOJkzJFpv2q1c6fAcNHQ54bnqlzyGmnkX1u9IKBRUeN
bha-3bIJkHKt0krAYaTi2pB4SQ3KJw-uhV562b1e8xQM-SbXnDUHk8TAyTKZ7nWjyvJqWY_5bUUba14qcJzQ-ZXGwgSUpxOKLFx9fGB7WkGeiUr8IPiKXAJv
EJ9QrYVd-0RAVuJCkmH0vhuGsKhsI_tY31K7J-yfFl09sj7HqiSBfNvTXZAQzsGpPihKqSAXx9JwrHcYHo9Te39pjEmdXm4BsAcuuk4IF3UIJ1qj-yd9M4Le
EwC5WHlUf_hoQ95z9GTA_QgAcuDmmslUNj0YlvcSYBMumcS8O4H9RLg6R2MzO3rUk4zmh01SctL3rCTEDLbDv2x1Kv0Qqel7itI-fAH7V1lAhXH7GM7mfBId
jKWVWoybn-4RuUKfAH4iG7mkGy8n7aZXgkJClmc9FwLuE0JkKJSb3wJqiQpKpz_Y_fJYt6MZa19jndWaXMDcgLzVSPa-f7XFHa_coWYQT9LY9ETGgLzVSPK8
HaSMj0Iaz88KLJAvrA-lk19Oq5XGFOBpBqbH9TDB_VgAwm8JgdSKe3qjXKEPNkhN7yy20E8T6T1AQ7jITf9JeFpD6V88Z8vCQ0ML9CM9ASLGChcQhA-uZIne
FwMKp8PaI-bZGJLPKd7f0iCFAP1Ff7oYP78rMLznMG50weUKQaknQG6pMLznQuoGYh8ZPK5obbRSvaMGML29o5QQ8ML1gLzQSUayyoR50yMGig3KhpoUMU7m
8QK14TMGig3KBwsuDKGK8WeYatj2YZZy2mJP6Is520r83LMbh2trwpFKY41uvv1Kok9Ilpv3J871CoCOKjQK-lKLjw9IYY5bJJLPNt4PuPqnKvQL-lLRt0Ha
GygwKh--uch4-gfgihxYslG5fNuXwLKf3FZtSUKLAJtZFGZol9I4jo6TKemCdLACYdjAiIlkAKN9fnIpufvIx8fxIb7IASNCq2d5hhYd52MTKioAUqgnAwvA
wHvlJcotKfh3IRwMKW7Wn5ULqXDEjE9-IA775MU6-ir5-echx1atd8I0h-BavEJavEJavEJavEI_
}

sprite $image122 [139x104/16z] {
xPQ7ikCu3aKPa07D_t_kbcchARQjfLekjTw6Ks6cyodT2u3fB_9__a-kwOS0QWBf1r347aYzFHko5QbtPzEvKwQAsGZV8rFOtd6wmGJj0xxetyz6Fud4ikXF
oCPYMMAnkmPu55bL2iCD0znBqeZ5dvzCoWq3t7lIy3KxpdTaqsN2xHUAwK9GxT_XRWCAbsTp7AcN3_1nk5o-N8-3-Ue1Fex2TTdSLfbCzYNgNcxDfkCHvOO1
tZcJNwjajdrqyXF3TQejQRXckN9-WtpdDCLIdtyRbokouVG6-TDTTHjEKu6Yrg1yQe3Fga06ra4ckfp2YG4-gwBvyJS0z_dnyxS0rBvGCOQMGaRR0Gzd8xQ7
qAYIISrC6IlMLQK_d7BO3bg_pKPp8j-eOCJwK0dSgd3xfoZqpozspKS6M7DBuPTANKnDY5XDxQao_3EsgXrFAPCmvFa0QssolggewvfJ-vivp4omjEK8gOID
p5EgBCp2zS05xYuF1pCrN1jBALL2A4yrzvouvtCq9J5XPX4IiyCkJSND39z_dNElFNau3VaSJKd2bHyoB7hSXViUePeIuZFhIkfkQYNLi2aU-NULbmmVa87c
qbHoZnsVAPbx4p73FC_7OdbNyGWJRgYzWMLBUW0ja2nTfgH4iRtFFXTPNm-3YdkuoSw7gUaTb9HAIhKtlJILZiwoMLyFg5m65HzIcggG9hBMZlNqSQBDJSPC
hfDFqbIAhBFKLVPbu3qWN3YHhq53-mfDh22_lb5rdN-KQ29gYumgsygCW-qlp1oRIHWd3DmUGaal2ggrOPudvEl__aEZogGoVH7WOat5wgeIQfmg4xnQhPeI
-wmklvnYmQtA9ANHH8qJX1ga1n2cLXE7-xhugQRgrfaCqW9T9UA8p9gEsKlbUGt3p6bTUTxFOMVMcQNslM8I7okZRoOGfasbXhvgr9w97nu9hiT4Ob2XGjFA
QEachHePY4LL6NDA7vvEFircDU7KLHZHObOPBStau8Eoa1yKiRfTSGheEjRtWunYk1vxPgEw7yicSBn1A8X58dnUcPcAGVDmqvb8Cv6SHXMh1Ie8EiimIttb
7LTHY-vnD9iUK9W8KAq4XIQ3FLDfCaT4OWbAdovpE22QLG6HdSfCL8RrUYYRaZhZPNQf3AK8HBXFAgEYlsF-Ho8EQM2yp45SZHXLmprcbPappsQ4Xg6XMf2u
wX8ssJ9dHTedqP8-KMqheoJ05ON0nyh8LEPyDXtSfh4O0s2jDRhXc9AU5sacdDC-cOS9rWfemE0nLaQdCkUpwLJTfcIA2BLI-EUt3F-PYtSHnpG7RTZvyA2T
X8WuKPaJsNGo-LR66UYXmc4MPoipYbXDHoao3ZQ71yeYcTnFLgQBz1Dy3B11nfiA0s5yh8mSAibuWe_JKke4q2APgyzkmVbivYdrmMQeCFZDAjD5-fgVCn_i
OAeE5YsmuvM9PLWbfq4VtYnKiaKeMknKHlTACgxvEVFrQ-8Uae5jhpAwcmsdWUzJUgWG5_2TmpIAZDby3zWuIuBCACXhQtfbH2Di9RxCPhv-FTo844kL21qV
Lh4iCPJa-9e_ktxD4Cc0iSeGqn9Bz6mcg-GqrGOPDP1Q8CicfVRlHnSviUPF3NPeHZ0az52DGIMMSsl-_61xC2614k5MnPSBifaFDcO21SObObNPYWIb2y5n
jwa20oE3HrUvCfinfR4oKYglJywX97v1DfEBxSfGeLZujoVu-_KRfeJOLOOrVpqqfkIrUbEPh_dhKx8-GPCJVFLWUn_cQxEPhzz-WppTG5-_jwlqbEvNwODz
lqf_LzslqWUxg-HqAs0HJvL_BDqDlRQjbNGZVR1ZuVGZg1gOVWev_O_oV_xFlm
}

